### ISSUE TITLE
【问题】前后端分离，如何处理这样的场景？在不关闭csrf的情况下

### ISSUE THREAD

**Issue by guzuomuse** [eggjs/egg#1000]
前端A
后端B（用egg程序提供数据）
A--->发起http请求(post类型)到后端B；
A和B在不同的域名下；除了A向B请求数据之外，他们没有任何关系；

那么当发送Post请求的时候，服务器端B必然会验证csrf；那么问题就是：
如何在A端发送B端要求的csrf呢？（我知道可以通过body,query或者header方式，这里的问题不是通过何种方式发送，而是在客户端A如何正确的取到服务器端B所需要的csrf的值）
说白了，就是跨域发送csrf token的问题；请问如何实现这个流程？谢谢....

**Comment by guzuomuse** [comment]
是否在接受到请求之前执行的hook钩子之类的东西，如果存在，那么是不是可以在这个钩子函数之中,
发送相应的信息到客户端A，然后A再进行二次处理把这个对应的csrf取到然后再传递给服务器端B?
不知道这个思路是否正确？

**Comment by guzuomuse** [comment]
或者说这本来就是个很白痴的问题？因为只要设置了security的白名单；就没有必要使用csrf的保护机制了？只要关闭即可？

**Comment by jtyjty99999** [comment]
跨域请使用 jsonp 或者 cors

**Comment by dead-horse** [comment]
CSRF 的所有的校验机制都是为了防止收到不信任的域名页面发出的请求，如果你明确的知道这个域名是可信任的，是不需要走 CSRF 的。例如上面提到的，通过 cors 和 jsonp 方式都可以通过配置校验 referrer 白名单来保证只允许信任域名访问。

**Comment by tong3jie** [comment]
@dead-horse 那是不是就失去了CSRF的意义了呢

**Comment by dead-horse** [comment]
> CSRF 的所有的校验机制都是为了防止收到不信任的域名页面发出的请求

这才是跨站校验的目的，我们做的所有跨站校验手段都是为了验证这个域名是否受信，如果你能通过其他方式确认这个页面是可信任的，为什么还要做 CSRF 校验。

**Comment by guzuomuse** [comment]
翻翻旧账 :)
@dead-horse @tong3jie 
我认为@dead-hosrse的理解有问题
请看这里https://stackoverflow.com/questions/19793695/does-a-proper-cors-setup-prevent-xsrf
我认为这两个防护都需要做；网络安全无小事；请 @dead-horse 大神给出一个明确答复；
谢谢

**Comment by mqliutie** [comment]
这个问题咋解决的😂 ， 只能关闭 csrf吗?
