### ISSUE TITLE
Chrome devtool代码热更新后原有的调试地址无法使用

### ISSUE THREAD

**Issue by Vincent1993** [eggjs/egg#1002]
* **Node Version**: 7.6.0
* **Egg Version**: 1.1.0
* **egg-bin**: 3.3.0
* **egg-ci**: 1.6.0
* **Platform**: Mac
* **Mini Showcase Repository**:

根据 [#985](https://github.com/eggjs/egg/issues/985) 里说的可以正常在Chrome devtool中调试

但是每次代码更改后 chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9231/**53bdffdd-ab48-44d8-990e-4d4f4b0064fc**

这一段地址和端口号一直在变动，所有要每次都去控制台复制变更后的地址 想问一下有什么办法可以解决
这个问题，端口号我通过文档中egg-development-proxyworker 能够解决 但是后面这一点不知道怎么弄

**Comment by okoala** [comment]
@Vincent1993  我建议还是用 vscode 调试吧~

**Comment by Vincent1993** [comment]
@okoala 那有办法让调试器去读取第二段地址么 就像 #985 里面说的一样。。

**Comment by okoala** [comment]
@Vincent1993  直接在 vscode 里面打断点了，很方便的~ 没必要用 chrome

**Comment by martin-liu** [comment]
@okoala 不能要求别人都去用vscode啊，这个问题还是要解决的吧

**Comment by atian25** [comment]
@martin-liu 这是 node cluster 本身的机制，我们也无能为力啊，chrome dev tools 的那个 scheme 地址肯定会变的，虽然启动后，通过 `http://127.0.0.1:9231/json` 可以拿到对应的地址，可我们又没办法控制浏览器刷新到新地址。

vscode 能解决的原因我估计是内部做了处理。我建议你可以写一个 chrome 插件来处理，自动监控某个端口，自动刷新，你可以试试： https://chrome.google.com/webstore/search/node?hl=en-US

**Comment by Vincent1993** [comment]
```
//app.js
module.exports = app => {
  const reg = /--inspect=(\d+)/i;
  const logger = app.logger;
  const inspectArgv = reg.exec(process.execArgv.join(' '));
  const debugPort = inspectArgv && inspectArgv.length > 1 ? inspectArgv[1] : process.debugPort;

  if (debugPort) {
    logger.info('[egg-development-proxyworker] client worker ready to connect proxyworker.');
    app.messenger.sendToAgent('conn-proxy-worker', {
      debugPort,
    });
  }
};
```

现在通过[NIM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?utm_source=chrome-ntp-icon) 以及配合[egg-development-proxyworker](https://github.com/eggjs/egg-development-proxyworker) 可以做到页面自动刷新 但是现在问题是每次都是 #985 中的问题。
里面也提到第二条才是正确的代码，现在可以通过这样的方式可以暂时解决想要的需要。

**Comment by atian25** [comment]
NIM 里面不是可以配置端口么，你改为第二个端口就好了。

**Comment by dead-horse** [comment]
debug 相关的问题先关了，讨论可以继续。

**Comment by atian25** [comment]
同步下，文档增加了一节： https://eggjs.org/zh-cn/core/development.html#nodejs-8x

你可以通过 chrome://inspect 来看到最新的地址，不用去控制台复制。

**Comment by okoala** [comment]
@Vincent1993 这里有个 PR，是个在 chrome devtools 中调试比较理想的方案，可以关注下~
eggjs/egg-development-proxyworker#5

**Comment by Vincent1993** [comment]
@okoala 感谢
