### ISSUE TITLE
我觉得对于自定义配置文件，只要运行环境是在development模式下，都应该能够自动加载。

### ISSUE THREAD

**Issue by arden** [eggjs/egg#1004]
我觉得对于自定义配置文件，只要运行环境是在development模式下，修改代码后，都应该能够自动加载。
这样方便在本机上调试，也方便在服务器上调试，或者服务器上的测试机上调试，因为很多时候开发的时候本的配置环境和服务器上的环境不一样，虽然是在服务器上，但为了调试测试方便，很多时候是需要修改代码自动加载的。

**Comment by atian25** [comment]
自己修改对应的 `plugin.{env}.js`，在里面 enable egg-development 即可。

**Comment by arden** [comment]
@atian25 我怎么试过了不起作用。

**Comment by atian25** [comment]
启动后看 run/application.js 里面的 plugin 节点，看看这个插件有没有被启动

**Comment by arden** [comment]
@atian25 可以了。

1、plugin.{env}.js
```
'use strict';

// had enabled by egg
// exports.static = true;
//
exports.development = {
  //enable: true,
  //package: 'egg-development',
  env: ['server'],
};
```

2、config.{env}.js
```
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1491894900294_262';

  config.watcher = {
    type: 'development',
  };
  return config;
};
```

3、dev.{env}.sh
```
#!/usr/bin/env bash
NODE_ENV=development EGG_SERVER_ENV=server npm run dev
```

把这些配置文件试了好多遍才配置成功，上面这几个地方必须的这样配上去才行，有些地方不注意，要么不生效，要么能生效，但重新加载变得非常慢。
