### ISSUE TITLE
问一个跟框架不是特别相关的问题

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1005]
> **微信小程序**对第三方服务端的网络通信方式支持https和Ｗebsocket。WebSocket是HTML5开始提供的一种在单个 TCP 连接上进行全双工通讯的协议。为了解决HTTP协议效率低下的问题，HTML5定义了WebSocket协议，能更好的节省服务器资源和带宽并达到实时通讯。WebSocket在数据传输的稳定性和数据传输量的大小方面，具有很大的性能优势。有不少公司将nodejs的`http://socket.io`作为websocket的解决方案，**很遗憾的是`http://socket.io`是对websocket的封装，并不支持html5原始的websocket协议。**node有很多websocket库，ws就是其中一个，号称最轻量级，最快。ws的用法比较简单。

所以是不是`egg-socket.io`插件，无法实现小程序的Ｗebsocket聊天室的功能啊。我的小程序一直无法建立连接，让我很神伤。。求大神指点迷津。

**Comment by dead-horse** [comment]
egg-socket.io 是对 socket.io 的封装，所以可能是没法用的。

**Comment by atian25** [comment]
我看到 https://github.com/eggjs/egg/issues/861 @bugss 这边说是可以做到的

**Comment by ngot** [comment]
*很遗憾的是http://socket.io是对websocket的封装，并不支持html5原始的websocket协议。** 这个说法不准确。socket.io正式封装了原始协议，你只要按照 socket.io-client封装一下即可。

**Comment by atian25** [comment]
微信小程序的 websocket api : https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-socket.html#wxconnectsocketobject

我看到有第三方的封装， https://github.com/wxsocketio/wxapp-socket-io

**Comment by xjchenhao** [comment]
好的 我研究看看，谢谢大家😁

**Comment by mdluo** [comment]
@xjchenhao @atian25 
使用 https://github.com/mdluo/socket.io-client-mp ，支持 ArrayBuffer 的微信小程序 socket.io 客户端
