### ISSUE TITLE
How to make unittest for middleware

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#1006]
I have a sso_client middleware, i wonder how:

* make unittest for the sso_client middleware
* how to skip the sso_client middleware when writing other unittests ( the sso_client have side effects to other modules, so the best way is disable it for convenient)

Thanks~

**Comment by jtyjty99999** [comment]
eg: https://github.com/eggjs/egg-security/blob/master/lib/middlewares/hsts.js 

tc : https://github.com/eggjs/egg-security/blob/master/test/hsts.test.js#L12     
mockapp : https://github.com/eggjs/egg-security/blob/master/test/fixtures/apps/hsts/config/config.js#L6

**Comment by popomore** [comment]
Feel free to reopen if you still have question.
