### ISSUE TITLE
egg-socket.io 如何指定端口

### ISSUE THREAD

**Issue by linxxx3** [eggjs/egg#1007]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

想要websocket与http server使用不同的port

**Comment by ngot** [comment]
不支持。egg-socket.io是设计用来配合egg http web服务工作的。如果起了不同服务，就不太好调用服务了。也就失去了插件本身的意义。如果有单独起服务的需求，建议直接使用 socket.io
