### ISSUE TITLE
工具类的书写规范

### ISSUE THREAD

**Issue by zhengcanbiao** [eggjs/egg#1009]
最近在写代码的时候遇到一个比较困惑的问题。我想写一个工具类，在工具类里有一些异步的请求，例如去请求阿里云的api之类的。因为是第三方的业务逻辑，所以我不打算放在service目录下，我新建了一个文件夹utils，写一些类似stringUtil，aliUtil之类的，但使用eggjs的框架我又想用到app.curl和app.config，但是utils这个目录下的去打印this.app是undefined的，请问我怎样在什么地方去写工具类既能使用到app，又是一个比较科学的做法呢?

注：我也试过把util写成 module.exports=(app)=>的方式，在service里直接去引用 utils(app).method()的方式，但总感觉不是很科学，一般应该是在顶部通过require某个util的方式，然后在service里直接调用方法。请大牛指点迷津。

**Comment by popomore** [comment]
写在  app/helper 

https://eggjs.org/zh-cn/basics/objects.html#helper

**Comment by zhengcanbiao** [comment]
但是helper里写的话貌似假如我写 

whchat:{
    setAuthToken:function *setAuthToken (appid,authToken){      
    },
    getAuthToken:function *getAuthToken (appid){
        this.app.logger.info(this.app.config.wechat.prefix+`${appid}:authorizer_auth_token`,res);
    }
}


里面的this指的是当前这个文件，this.app为undefined，只能把whchat这一层干掉，把方法放在最外层才可以，可是这样就不方便做工具类的分类 ，只能把各种工具类都在helper下面一字铺开了

**Comment by popomore** [comment]
用 this.ctx

**Comment by zhengcanbiao** [comment]
![_20170609001631](https://user-images.githubusercontent.com/6441383/26939156-040347d2-4ca9-11e7-9ba1-c4e7ddbdf90c.png)
测试结果如上，貌似不管用呀

**Comment by popomore** [comment]
你用的不对啊，不支持多层

**Comment by zhengcanbiao** [comment]
但是我希望对我的工具类进行分层，不然堆在一起很影响我的阅读和维护。我还希望是可以分成多个文件去写，这样更好，但目前helper实现不了我的需求，utils又引用不到app的东西，所以目前我才有这个困惑

**Comment by popomore** [comment]
你可以在 helper 自己  require 文件。工具类不应该太复杂，不应该包含太多业务。

做业务应该自己定制模型，把 app 或 ctx 传进去。

**Comment by zhengcanbiao** [comment]
恩，我试试看，谢谢大神

**Comment by Gorden-Wang** [comment]
我也遇到了同样的问题，比对文档看了多次，在helper的方法中 ：this 是 undefined ~
```
// app/extend/helper.js

module.exports = {
  getAsset(url) {
    /**
     * getAsset 获取资源地址,webpack打包后会将资源地址放到config/manifest.json中
     * @param {string} url 获取资源的url，详情查看ASSET_JSON
     * @return {string} 真正的url
     */
    console.log(this);// undefined
    return ASSET_JSON[url];
  },
};

```

相关版本 ：
  "egg": "^2.2.0",
   "egg-scripts": "^2.1.0",
    "egg-static": "^2.1.0",
    "egg-tracer": "^1.1.0",
    "egg-view-nunjucks": "^2.1.4",
    "egg-webpack": "^3.2.8",

**Comment by atian25** [comment]
@Gorden-Wang 检查下自己代码，https://github.com/atian25/egg-showcase/pull/6/files

**Comment by Gorden-Wang** [comment]
@atian25  效率杠杠滴~
我想在hepler.js中，通过this.ctx获取context 
和你的showcase 对比了下，我把helper中的函数解构出来了。如：
const { ctx, service /* ,logger*/ } = this;
const { helper/* , query,queries,params,request,response,header,session,cookie*/ } = ctx;
const { getAsset, getTplInitData } = helper;

这时：
getAsset(`${PR}music.mp3`),

helper.js
```

module.exports = {
  getAsset(url) {
    /**
     * getAsset 获取资源地址,webpack打包后会将资源地址放到config/manifest.json中
     * @param {string} url 获取资源的url，详情查看ASSET_JSON
     * @return {string} 真正的url
     */
    console.log(this);// undefined
    return ASSET_JSON[url];
  },
};
```
controller.js
```
class TestController extends Controller {
  async index() {
    const { ctx, service /* ,logger*/ } = this;
    const { helper/* , query,queries,params,request,response,header,session,cookie*/ } = ctx;
    const { getAsset, getTplInitData } = helper;
    const IMGS = {
      music: this.ctx.helper.getAsset(`${PR}music.mp3`), getAsset可以获取 this
      music1: getAsset(`${PR}music.mp3`), //  this为undefined
      // bg1: assets(`${PR}bg1.jpg`),
      // bg2: assets(`${PR}bg2.jpg`),
      // bg3: assets(`${PR}bg3.jpg`),
      // bg4: assets(`${PR}bg4.jpg`),
      // bg5: assets(`${PR}bg5.jpg`),
      // bg6: assets(`${PR}bg6.jpg`),
      // bg7: assets(`${PR}bg7.jpg`),
    };
    const data = await service.cact.guideStoryNew.index();
    const tplData = getTplInitData(null, null, data.client.isweChat, false);
    const renderData = {
      ...data,
      ...tplData,
      IMGS,
    };
    await ctx.render('h5/cactivity/guideStoryNew/index.html', renderData);
  }
}

module.exports = TestController;

```

**Comment by Gorden-Wang** [comment]
对controller做了改造
```
class TestController extends Controller {
  async index() {
    const { ctx, service /* ,logger*/ } = this;
    const { helper/* , query,queries,params,request,response,header,session,cookie*/ } = ctx;
    const { getAsset, getTplInitData } = helper;
    const assets = getAsset.bind(helper);
    console.log(helper);
    const IMGS = {
      music: helper.getAsset(`${PR}music.mp3`),
      music1: assets(`${PR}music.mp3`),
      bg1: assets(`${PR}bg1.jpg`),
      bg2: assets(`${PR}bg2.jpg`),
      bg3: assets(`${PR}bg3.jpg`),
      bg4: assets(`${PR}bg4.jpg`),
      bg5: assets(`${PR}bg5.jpg`),
      bg6: assets(`${PR}bg6.jpg`),
      bg7: assets(`${PR}bg7.jpg`),
    };
    const data = await service.cact.guideStoryNew.index();
    const tplData = getTplInitData(null, null, data.client.isweChat, false);
    const renderData = {
      ...data,
      ...tplData,
      IMGS,
    };
    await ctx.render('h5/cactivity/guideStoryNew/index.html', renderData);
  }
}
```
