### ISSUE TITLE
enable mocha-clean in egg-bin test

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#1010]
[mocha-clean](https://npm.taobao.org/package/mocha-clean) : Cleans up mocha test stack traces.

cc @huacnlee

**Comment by atian25** [comment]
interesting~

**Comment by atian25** [comment]
研究了下，不能直接用它，浏览器方面的支持我们不需要，还有它对 npminstall 的判断不支持，可以自己在 egg-bin test 里面处理下，我搞搞。

**Comment by okoala** [comment]
如果格式化的话，就无法做到通过点击链接打开文件了吧~

**Comment by atian25** [comment]
可以的，本来输出就是不带绝对路径的，转换后，我们反而可以变为绝对路径。但相对路径应该就够了。

**Comment by huacnlee** [comment]
@okoala 打开文件是少数情况，看到常常的日志是多数情况，其实复制一下就可以了

**Comment by atian25** [comment]
landed at 3.5.0

其实 mocha 内部已经有这段逻辑了， https://github.com/mochajs/mocha/blob/master/lib/utils.js#L738

只是它过滤的不够，还有对我们的 tnpm 的安装格式支持不好。

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/26910286-7884b77e-4c38-11e7-920d-0b3661a6aa87.png)

@okoala 可以点击的。

**Comment by okoala** [comment]
👍

**Comment by fengmk2** [comment]
点击是怎样做到的？

**Comment by atian25** [comment]
oh-my-zsh 下按下 CMD 键，鼠标悬浮链接上就可以了。
