### ISSUE TITLE
egg-core中间件加载配置match和ignore和koa-userauth属性冲突问题

### ISSUE THREAD

**Issue by luicfer** [eggjs/egg#1014]
egg-core用egg-path-matching处理中间件的match和ignore配置
其他插件比如koa-buc用koa-userauth来处理match和ignore
一个配置项会被处理两次，而且行为并不完全一致，会引起问题

如下图，一次请求过中间件这两个参数被处理两次

![image](https://user-images.githubusercontent.com/8154651/26873292-ebe4e618-4bab-11e7-98f3-8c5bcf23f193.png)
![image](https://user-images.githubusercontent.com/8154651/26873312-fbfdf8f0-4bab-11e7-928a-af0b6ac784cf.png)

**Comment by popomore** [comment]
是不一样，原来中间件得改

**Comment by dead-horse** [comment]
先提供一个配置支持禁用掉 egg 的处理吧，否则就无法做到兼容了

**Comment by dead-horse** [comment]
先关掉了，内部问题内部讨论
