### ISSUE TITLE
schedule里面不能访问service， 那service和schedule公用的代码如何更加优雅的共享？

### ISSUE THREAD

**Issue by latel** [eggjs/egg#1015]
如题

**Comment by okoala** [comment]
@latel  通过 ctx.service 访问
https://github.com/eggjs/egg-schedule/blob/master/test/fixtures/context/app/schedule/sub/cron.js#L10

**Comment by popomore** [comment]
就把 schedule 当做 controller 用，业务逻辑最好都放 service 中。

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/objects.html#获取方式-2
