### ISSUE TITLE
使用 egg-bin debug 调试时，Chrome 中显示的源文件不完整

### ISSUE THREAD

**Issue by m31271n** [eggjs/egg#1016]
![源文件显示不完整](http://i4.buimg.com/524586/8cf64cd52de7c62fs.png)

在根据 https://eggjs.org/zh-cn/core/development.html#使用-egg-bin-调试 配置调试环境的过程中，会出现源文件显示不完整的问题。

如上图所示，只显示了 node_modules 目录。

+ Node Version: 8.0.0
+ Egg Version: 1.4.0
+ Platform: Gentoo Linux  with 4.9.16 kernel
+ Egg-bin Version: 3.4.0

**Comment by atian25** [comment]
dup https://github.com/eggjs/egg/issues/985

**Comment by m31271n** [comment]
Thx.
