### ISSUE TITLE
小白问题：vscode或webstorm里怎么设置代码提示？

### ISSUE THREAD

**Issue by skyyangpeng** [eggjs/egg#1017]
我安装了vscode plugin - eggjs-dev-tools，但是提示还是很简单，是不是安装错了？具体要怎么安装

**Comment by okoala** [comment]
@skyyangpeng  目前代码提示还比较弱

**Comment by acid122** [comment]
在vscode下，可以使用命令npm install -g typings，这样可以有代码提示，按住ctrl键也可以进入到require的文件中。

**Comment by solarhell** [comment]
`egg`并不是TypeScript写的 `typings`并没有用吧 
如果一定需要这个定义文件 可以 `npm install --save-dev @types/egg`

**Comment by acid122** [comment]
这个命令实现了egg项目的提示，其原理我也不是十分清楚，但是我昨天通过这个命令后，确实通过require进来的变量可以有相应属性的提示，而且使用这个命令后也有一些代码补全的功能，也许可以参考这篇文章:http://www.cnblogs.com/IPrograming/archive/2016/04/30/VsCodeTypings.html

**Comment by shepherdwind** [comment]
`@types/egg` 这个包还没弄进来，我改下，后面不需要安装这个包了，直接用就行。
