### ISSUE TITLE
egg-rest 如何自定义method名称？

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#102]
egg-rest 限定方法名为index、show、create、update、destroy，我如何自定义method名称，例如：
请问这种情如何映射配置？
method:POST
url:/api/login
file path:/app/apis/user.js
controller name:login()

另外目前Response Formats不能够自定义，希望能配置返回格式，谢谢

**Comment by popomore** [comment]
现在确实不是非常灵活，只能说刚好能用。

**Comment by popomore** [comment]
尝试参考 http://sailsjs.org/documentation/concepts/blueprints

**Comment by popomore** [comment]
@zhoudaqing 如果你有兴趣可以提下你的想法直接 PR

**Comment by zhoudaqing** [comment]
@popomore @atian25 
api Routes的可配置还是需要的，类似这里：http://sailsjs.org/documentation/concepts/routes

**Comment by zhoudaqing** [comment]
@popomore @atian25 
另外再请教一下，egg-rest Parameter Validation，校验规则有哪些，readme上面的链接无法打开“http://web.npm.alibaba-inc.com/package/parameter”，如何使用和扩展呢？

**Comment by popomore** [comment]
普通 router 直接使用 egg 就可以了

```js
app.get('/api/login', app.controller.login)
```

**Comment by atian25** [comment]
@zhoudaqing 那个 URL 我提 PR 修复了: https://github.com/eggjs/egg-rest/pull/5

**Comment by zhoudaqing** [comment]
@atian25 url可以了，谢谢
刚才说的router可配置，是说的rest api希望提供url router可自定义去配置

**Comment by atian25** [comment]
@shaoshuai0102 看看~, 或者 @zhoudaqing 欢迎直接提 PR 实现

**Comment by popomore** [comment]
@zhoudaqing 你刚刚发的 sails 的链接也是普通 router，不是 rest 的。rest 本身肯定是有局限的，所以应该相辅相成。

**Comment by shaoshuai0102** [comment]
@zhoudaqing 提的这个用法其实不是 REST。我觉得合理的使用方式直接用 router 自定义这些非 REST 资源路由即可。

**Comment by popomore** [comment]
@shaoshuai0102 不过现在的配合不是很好，比如正常的 router 没有 rest 式的返回值（比如状态码，错误处理），所以不是很统一。

**Comment by dead-horse** [comment]
现在我一般都是直接用 `app.resources('user', '/api/v1/users', app.controller.api.user);` 而不是用 rest 了

**Comment by shaoshuai0102** [comment]
不管是 resources 还是 rest 其实都是基于约定的。所以非标准类型的还是直接 `app.get/post` 吧。

**Comment by dead-horse** [comment]
> 不管是 resources 还是 rest 其实都是基于约定的。所以非标准类型的还是直接 app.get/post 吧。

恩，我是回复 @popomore 的，通过 resources 声明路由和普通的 app.get/post 一样不存在状态码和错误处理，如果混用  rest 和普通的 app.get/post 容易让人疑惑。

**Comment by zhoudaqing** [comment]
@dead-horse  @popomore  你这是自己封装的吧，egg-rest 自定义method映射是刚需，一部分用rest，一部分app。get/post，首先你的middleware、和错误代码、response Formats都得搞两套，如果rest限定了payload json更麻烦，建议作为fix，接下来更新egg-rest，不然没法用。

**Comment by jtyjty99999** [comment]
@zhoudaqing 你可以整理下想法然后pr到这个插件上

**Comment by popomore** [comment]
@dead-horse 这样说的话 app.resource 应该放在 egg-rest 里，然后 rest 也使用这个 api

**Comment by dead-horse** [comment]
但是其实我并不想用 rest 的那些封装，因为不统一，rest 形式的接口无法满足我的全部需求，总有几个接口是要单独定义的，而我希望单独定义的接口和 rest 的接口是一致的，所以一般我都会自己写一个中间件来封装所有 API 的错误处理和其他通用逻辑判断。

**Comment by popomore** [comment]
是啊，你的诉求和 @zhoudaqing 是一致的，增加额外的配置提供 CRUD 额外的映射。

**Comment by dead-horse** [comment]
> 增加额外的配置提供 CRUD 额外的映射。

应该是说遇到的问题一致，但是我并不需要提供额外的 CRUD 映射，我觉得通过 `app.resources/get/post` 声明，然后通过统一自定义的 wrapper 中间件来解决统一处理，这个方式比较符合我的习惯，而不是通过 rest 插件来完成：

- app/router.js

```js
app.resource('user', '/api/v1/user', app.controller.user);
app.get('/api/v1/user/count', app.controller.user.count);
```

- app/middleware/api_wrapper.js

```js
module.exports = function() {
  return function* () {
    if (!this.url.startsWith('/api/v1')) return;
    
    // 统一处理错误和其他通用封装
    try {
      yield next;
    } catch (err) {
      this.body = { message: err.message };
      this.status = 500;
    }
  };
};
```

- `config/config.default.js`

```
exports.middlewares = [ 'apiWrapper' ];
```

**Comment by popomore** [comment]
上面的 api wrapper 不会处理 resource 里面的响应，还是有差异的。包括 controller 的写法也会有一些差异。无法保持输入输出的一致性。

**Comment by dead-horse** [comment]
@popomore 为什么不会处理，只是我拿这个 wrapper 做示例而已，要处理也是可以的？这样写 controller 的写法也完全一致了，因为 `app.resources('user', '/api/v1/user')` 其实就是:

```js
app.get('/api/v1/user', user.index)
app.post('/api/v1/user', user.create)
app.put('/api/v1/user/:id', user.update)
app.delete('/api/v1/user/:id', user.destroy)
```

只是简化了路由注册，它自身不带任何特殊处理逻辑的

**Comment by popomore** [comment]
现在 resource 有特殊处理吧
Yiyu He <notifications@github.com>于2016年9月12日 周一下午10:55写道：

**Comment by dead-horse** [comment]
resource 亲测应该是没有特殊处理的。

**Comment by fengmk2** [comment]
app.resource 是没做特殊处理的 https://github.com/eggjs/egg-core/blob/5f3f8626e79d5bceb775b4a68490d6d8e58fcdcb/lib/utils/router.js#L118

**Comment by popomore** [comment]
我们现在推荐使用 `app.resources`

https://github.com/eggjs/egg/blob/e6311ef488e8d3aa9dfc2ecfafe21cc02c442068/docs/source/zh-cn/practice/restful.md

**Comment by maguon** [comment]
如果要 put ->/user/:userId/password 这样呢，是不是也要用resources？

**Comment by maguon** [comment]
如果router不支持app.post app.put ，那感觉多少有些框架过度了

**Comment by popomore** [comment]
直接写 app.put
