### ISSUE TITLE
如何egg-view-nunjucks插件的view中引入到后端的常量或者工具方法

### ISSUE THREAD

**Issue by acid122** [eggjs/egg#1020]
* **Node Version**:7.10.0
* **Egg Version**:1.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

大家好，之前我的问题是view层es6语法的转换，在受到回答者提供的答案的启发下，在将页面view的js分离出去成单独的js文件后，我在项目中引入了babel对每个页面的js文件进行es6转es5语法，而且支持文件夹整体转换；但现在我和后台同学有个需求是不知道在egg项目中，egg-view-nunjucks插件的view层能否通过类似import的方法和后端共用一些常量或者工具方法的，因为感觉view层也是属于后台的一部分，理论上应该是可以的？
针对这个问题，我在通过引入webpack加上babel插件后，能实现es6到es5语法的转换，同时转换后能够取到require过来的变量，但是本人对webpack还不是非常熟悉，感觉其配置还是略微麻烦，而且貌似没有整个文件夹的转换，需要单个文件进行转换，当然可能也是我对webpack的进一步的设置不熟悉有关系；不知道大家有更好的方案，谢谢：）

**Comment by atian25** [comment]
工具方法写在 `app/extend/helper.js` 里面，然后在模板里面就能使用了 `{{ helper.xx(data) }}`，具体的可以看下 view 文档。

**Comment by acid122** [comment]
谢谢楼上朋友的建议，在view里面直接使用{{ helper.xx(data) }}的话确实可行，但是好像没有任何的代码提示，最初考虑和后台共享一些常量或者是一些对象，也是考虑到要是有代码提示就很好了，在view中使用helper能够有相应的提示吗

**Comment by popomore** [comment]
常量也可以放到 locals 上 https://eggjs.org/zh-cn/core/view.html#locals

```js
app.locals = { a: 1 };
```

提示可以去 IDE 咨询。
