### ISSUE TITLE
在controller里如何结束一个请求？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#1023]
在controller里如何直接结束一个请求，比如我在写业务逻辑的时候，检测查询参数缺少了某些参数，我就直接返回给用户了，告诉用户缺少查询参数。试过用ctx.throw可以做到，但用这个感觉不太合适，因为用ctx.throw不能设置200的httpcode。

**Comment by ngot** [comment]
可以直接设置好返回的值，比如 status, body,然后 return掉
```js

if(?){ 
 this.body = 'xxx'
 return;
}

// 正常的业务代码

```

**Comment by arden** [comment]
@ngot 可以了，谢谢。
