### ISSUE TITLE
egg-waterline

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#103]
可以接入  https://github.com/balderdashy/waterline

**Comment by jtyjty99999** [comment]
这个跟orm,orm2,Knex、Bookshelf、Sequelize啥的可以对比下。。

**Comment by popomore** [comment]
感觉没必要对比，都做成插件就好了

**Comment by jtyjty99999** [comment]
好，有需求就搞起

**Comment by 18601673727** [comment]
期待建议先搞Sequelize或Knex，Waterline的Migration sh1t一样的

**Comment by okoala** [comment]
https://github.com/okoala/egg-knex 几个月前搞了Knex的，要不要迁回组织~

**Comment by dead-horse** [comment]
可以的，你应该有权限迁过来吧

**Comment by atian25** [comment]
@okoala 看下插件相关的文档, 有些地方需要修改下

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/22049450/346b9906-dd6e-11e6-8731-65a678c00c29.png)

这个插件是和 egg-mysql 互斥的么?  这里怎么写着 mysql , 但 pkg info 里面的 name 又不是

**Comment by okoala** [comment]
@atian25   互斥的，合并前我统统修改下~

**Comment by atian25** [comment]
可以先迁移过来, 然后发一个 PR 修复, 大家 review

**Comment by okoala** [comment]
OK~

**Comment by jtyjty99999** [comment]
sequelize https://github.com/eggjs/egg-sequelize

**Comment by ngot** [comment]
Sequelize 内网已经搞过了

**Comment by atian25** [comment]
@ngot 对比下, 整合为一个吧

**Comment by popomore** [comment]
再加一个 https://github.com/adonisjs/adonis-lucid

**Comment by okoala** [comment]
还有这个
[https://github.com/typeorm/typeorm](https://github.com/typeorm/typeorm)
[https://typeorm.github.io](https://typeorm.github.io/)

**Comment by no7dw** [comment]
所以这个是有开发计划吗？

**Comment by popomore** [comment]
Just use sequelize

**Comment by ruofeng086** [comment]
同问
sequelize 貌似不支持mongodb
官方有没有计划出一个waterline？

**Comment by ngot** [comment]
https://github.com/eggjs/egg-mongoose

**Comment by ruofeng086** [comment]
能像sails一样支持跨库就好了

**Comment by sunfuze** [comment]
@okoala  https://github.com/okoala/egg-knex/pull/1 这个如果没有问题，合并下，然后转到 eggjs/egg-knex 下，发一个版本？

**Comment by atian25** [comment]
@sunfuze @okoala 是自己人

**Comment by okoala** [comment]
@sunfuze egg-knex@2.0.0
