### ISSUE TITLE
How to get parameters from the URL??

### ISSUE THREAD

**Issue by chenjunqi** [eggjs/egg#1031]
The sample URL is as follows `http://127.0.0.1:7001/admin/permission?role=2`.
I want to get the value of the `role` in the controller(`/admin/permission`).
I think it should be mounted somewhere on the controller , but i can't find it.

**Comment by atian25** [comment]
please read the router docs

发自我的 iPhone

**Comment by chenjunqi** [comment]
@atian25  I am a newcomer to the web developer . thx , i get help from [http://koajs.com/#request](http://koajs.com/#request).

**Comment by atian25** [comment]
it's not in koa docs, you should read eggjs's router guide docs, and koa-router docs

发自我的 iPhone

**Comment by chenjunqi** [comment]
Ok ,  refer here : [eggjs's router guide docs](https://eggjs.org/zh-cn/basics/router.html) and [koa-router docs](https://github.com/alexmingoia/koa-router) .
