### ISSUE TITLE
如何引入一个自定义的公共类库，而不要修改？

### ISSUE THREAD

**Issue by sunguide** [eggjs/egg#1032]
Node:8.0.0
egg: 1.4.0

比如一个 idCardValidate.js文件，如何优雅的引入。

**Comment by atian25** [comment]
不要修改啥？

一般我们的做法是用 loader 自动挂载

发自我的 iPhone

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/advanced/loader.html#loadtoapp

可以通过这种方式，把 `app/validate/**.js` 挂载到 `app.validate.xx`

**Comment by sunguide** [comment]
如果在使用前都挂载的话，会不会影响

**Comment by atian25** [comment]
@sunguide 只是一些函数而已，不用担心内存啥的。
