### ISSUE TITLE
egg-mysql的筛选条件如何or

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1035]
开发团队你们好，

我想问下`egg-mysql`：
```
const results = yield app.mysql.select('posts',{
  where: { status: 'draft',name: 'abc' },
  orders: [['created_at','desc'], ['id','desc']],
  limit: 10,
  offset: 0
});
```
这样的语句，`where`里的条件是`AND`的关系，如何筛选`OR`的关系呢？

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/blob/master/lib/operator.js#L184 目前只有 AND。

可以参与 https://github.com/ali-sdk/ali-rds/pull/24 的讨论，看看如何增加 OR 的功能。

**Comment by xjchenhao** [comment]
好的吧，我查了两次用concat拼接了😅
