### ISSUE TITLE
请问eggjs有路由组的概念吗

### ISSUE THREAD

**Issue by acid122** [eggjs/egg#1036]
* **Node Version**:v7.10.0
* **Egg Version**:1.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

大家好，请问一下eggjs项目的router.js文件有路由组的概念吗，即需要同一中间件处理的多个路由可以组合到一起，我看到中间件一章有match 和 ignore来针对不同前缀的url进行不同的中间件处理，这个给我的感觉就是实现路由组的功能，不知道有没有更加直观的方式来设置路由组?

**Comment by dead-horse** [comment]
等这个插件实现 https://github.com/eggjs/egg/issues/882
