### ISSUE TITLE
不可以在router里面执行一个controller的函数么？

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#1039]
首先我在controller里暴露出一个函数，然后想在router里直接执行这个函数，发现不行。
其实我是想在app运行后执行一个函数，这个函数需要访问到service。
这个函数不是一个定时函数，所以我想用那个定时插件貌似也不行，如果自己定一个类，我貌似拿不到service了。

**Comment by atian25** [comment]
> 首先我在controller里暴露出一个函数，然后想在router里直接执行这个函数，发现不行。

这个函数你应该放到 service 里面

> 其实我是想在app运行后执行一个函数，这个函数需要访问到service。
应该在 app.js 里面用 `beforeStart`， 可以看下文档 https://eggjs.org/zh-cn/basics/app-start.html

**Comment by buzai** [comment]
@atian25 你好，感谢你的回答，我也看到了那个文档，1.我放在service里面可以，但是从哪里执行它呢？这是多个函数组合在一起的庞大的的数据处理存储的函数 。  2.而且我这个函数是一个永远都在从另外一个rpc接口读取数据并存储的，我觉得放在beforeStart不合适。

**Comment by atian25** [comment]
没太看明白你的需求，`在app运行后执行一个函数` 这个不是指启动后么?

> 但是从哪里执行它呢？

具体描述下你的请求时序?

**Comment by buzai** [comment]
我这里app启动后我通过运行一个start函数，函数里面一直对比数据库的记录和rpc的记录对比两个是否同步，不同步就从rpc处读取新的数据处理后并存储，这个数据大概上百万左右，并且一直在告诉增加。存储到的数据会用来支持一些接口调用。
我觉得代码应该是这样
```javascript
// app.js
module.exports = app => {
  app. beforeStart(function* () {
    const ctx = app. createAnonymousContext();
    yield ctx.service.test.start(); //然后不断的读取数据，但是beforeStart貌似会组织应用启动？
  });
};
```

**Comment by atian25** [comment]
rpc 具体指？

前面你说为何不能用 schedule？

**Comment by buzai** [comment]
就是比特币的rpc接口，我通过bitcoin客户端的rpc接口读取区块链的数据，处理后存储到数据库，来支持业务。因为交易需要依赖这些数据，那么如果做定时任务的话不好，不够时效性而且如果间隔很短的话，上次执行处理的数据部分和下一次的数据冲突了很麻烦啊，稍微造成一点数据错误，都会对后面整个账本数据造成影响。

**Comment by dead-horse** [comment]
这个功能可以通过 runInBackground 来实现：

```js
// app.js
module.exports = app => {
  app.runInBackground(function* (ctx) {
    yield ctx.service.test.xxx();
  });
};
```

但是会遇到一个问题，多个进程会同时执行这个逻辑，要么你需要通过一个锁来保证同一时间内只会有一个进程运行这段代码，要么你就让这段逻辑变成幂等的。

**Comment by buzai** [comment]
@dead-horse 你好，但是我这里看到的是 ctx.service 是undefined的，得不到需要的servuce

**Comment by dead-horse** [comment]
这个 ctx 是 Context 的实例，ctx.service 会挂载所有 egg 的 service，具体的细节可以查看文档 https://eggjs.org/zh-cn/basics/service.html
