### ISSUE TITLE
egg log setting and level 在哪里配置？

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#104]
SPECIFICATION.md文件中没有找到有关egg 的log配置和日志输出级别的介绍？ 我该如何配置呢？默认app对象调用哪个Global来打印日志？

**Comment by popomore** [comment]
```js
// config.default.js
exports.logger = {
  level: 'INFO',
};

**Comment by popomore** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L147

**Comment by zhoudaqing** [comment]
谢谢，看到了
