### ISSUE TITLE
日志参数设置outputJSON为true时，为什么输出日志不会只输出json日志呢

### ISSUE THREAD

**Issue by liuyu322** [eggjs/egg#1045]
日志参数设置outputJSON为true时，为什么输出日志不会只输出json日志呢？
建议支持只生成json日志

**Comment by popomore** [comment]
每条是一个 json

**Comment by liuyu322** [comment]
那出于什么目的，我的日志要生成两份呢，一份json，一份非json，本来日志输出就很大，还要占用双倍，我表示很不理解

**Comment by popomore** [comment]
一般生成的 json 文件是给监控系统用的，而默认的日志除了监控系统还方便 grep。

**Comment by atian25** [comment]
@popomore 提供开关?

**Comment by dead-horse** [comment]
不搞的那么复杂了，json 是用来给日志监控系统做分析更方便提供的，普通的文件是给人看的。用途不一样，outputJSON 是增强而不是替换。一般应用到不了需要考虑优化打印日志的场景。

**Comment by walkerx** [comment]
我也有这个需求
