### ISSUE TITLE
统一处理 httpclient header.

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1046]
我们有一个需求，前端请求表现层（egg），然后由表现层去请求业务层，但是中间需要将前端请求的header 加到表现层请求业务层的header中，但是在service里面每次都写感觉又很不科学，请问有什么比较好的统一处理方式

**Comment by atian25** [comment]
```js
// app/extend/context.js
exports.mycurl = function(url, options = {}) {
  options.headers = Object.assign({}, options.headers, { from: 'my' });
  return this.curl(url, options);
}
```

**Comment by liujinyang1994** [comment]
@atian25 非常感谢您的帮助

**Comment by liujinyang1994** [comment]
@atian25  不过，我更期待的是在这个方法中，直接从request对象中拿到header。

```
// 大概思路是这样
exports.mycurl = function(url, options = {}) {
  const request = ctx. request // 假设我在这里拿到了request
  options.headers = request.headers;
  
 return this.curl(url, options);
}
```

**Comment by atian25** [comment]
- 可以看下 koa 的文档，ctx 本身就代理了 request 的方法，所以不需要 `ctx.request.headers`
- 我的示例 `processHeaders` 是指往往你需要过滤掉用户的一些 headers，或者加自己的一些特殊 headers ，或者合并 options.headers ，然后才往后传的。

**Comment by liujinyang1994** [comment]
@atian25  感谢您的耐心解答，祝您工作愉快😊
