### ISSUE TITLE
vscode打断点无效？

### ISSUE THREAD

**Issue by huboshu0819** [eggjs/egg#1048]
node版本`v6.10.2`
vscode版本 `1.13.0`

启动文件如下（有在config里面配置插件）：
![image](https://user-images.githubusercontent.com/10299842/27077735-a95fd4e4-5063-11e7-9da7-bbc0a74e14de.png)

输出信息如下：
![image](https://user-images.githubusercontent.com/10299842/27077658-646edb50-5063-11e7-9c98-342f0c41bc54.png)

在controls里面打了个断点，每次运行都不会暂停
![image](https://user-images.githubusercontent.com/10299842/27077929-5392fd4c-5064-11e7-91a4-67781f02839c.png)

**Comment by okoala** [comment]
@huboshu0819  你执行 attach worker 了吗

![image](https://user-images.githubusercontent.com/2127199/27078103-f9964e38-5064-11e7-89de-c5c20323bd06.png)

**Comment by okoala** [comment]
![image](https://user-images.githubusercontent.com/2127199/27078431-47178fc2-5066-11e7-905e-48680a54093c.png)

@huboshu0819  启动调试的时候，使用 attach worker 这条

**Comment by atian25** [comment]
直接执行最后一条不就行了？自动启动自动 attach

发自我的 iPhone

**Comment by huboshu0819** [comment]
@okoala 我还一直以为启动了，确实没木有，已经ok了，谢谢！

**Comment by okoala** [comment]
@atian25  之前 vscode 有坑，一键启动调试有 bug。这个问题还得看看~

**Comment by nickzengcn** [comment]
这个，建议大家在开发正常的情况下，千万不要随意升级vscode，我之前用的1.13是debug是ok的，昨天升级了1.14结果就扑街了！捣鼓了一天也没发现什么问题，万念俱灰的情况下昨晚12点回滚了一下vscode的版本之后就一切照旧了。。。注明一下我的node是7.4

**Comment by devrsi0n** [comment]
@nickzengcn 我也是升级到1.14就不能debug了。貌似要使用inspector协议，但是配了半天没效果。

**Comment by nickzengcn** [comment]
我昨天也的捣鼓果inspector，一切正常，再chromedev里面能看到代码，只是打断点没奏效，反正一下子就过去了，如果你项目急，先别浪费时间，回滚到1.13吧，如果你不急，那你继续研究研究，回头告诉我哈！嘻嘻嘻

**Comment by freestyleman** [comment]
@nickzengcn vscode 升级后调试react不能打断点解决了吗？

**Comment by atian25** [comment]
1.14 的那个问题早修复了，重新安装下依赖即可。

但 react 不是前端的么？ 跟 egg 没关系

**Comment by nickzengcn** [comment]
@freestyleman  @atian25 大佬说得对..

**Comment by billwang666** [comment]
我也遇到同样的问题，打了断点，进不来断点，程序自动就运行了

**Comment by wangzhen11aaa** [comment]
这个怎么解决啊？我也是啊，一个简单的cmake工程，debug等于直接执行。

**Comment by unclexiao** [comment]
首先，VScode有个扩展名叫[eggjs](https://github.com/eggjs/vscode-eggjs)，作者也是 @atian25 天猪大佬，安装后可以直接生成调试的配置文件，类似这样：
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Debug",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug",
                "--",
                "--inspect-brk"
            ],
            "console": "integratedTerminal",
            "restart": true,
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Test",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "test-local",
                "--",
                "--inspect-brk"
            ],
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Egg Attach to remote",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/usr/src/app",
            "address": "localhost",
            "protocol": "auto",
            "port": 9999
        }
    ]
}
```

其次，调试特定的Debug模式启动，而不是正常的`run`，如图：
![image](https://user-images.githubusercontent.com/9072935/68476836-cdbf2f80-0266-11ea-8d27-25ca36f73fcd.png)

最后，较新的版本增加了ts支持，有时候无法正常启动，也很好解决，找到**package.json**文件，袖声明属性去掉即可：
```json
  "egg": {
    "declarations": false
  },
```

@wangzhen11aaa 祝顺利

**Comment by atian25** [comment]
VSCode 插件没必要用，忘记密码了😂

直接看官方调试文档就好了，复制那段 launch

**Comment by wangzhen11aaa** [comment]
> VSCode 插件没必要用，忘记密码了😂
> 
> 直接看官方调试文档就好了，复制那段 launch

我的是c++工程。官方文档是node.js

**Comment by atian25** [comment]
> > VSCode 插件没必要用，忘记密码了😂
> > 直接看官方调试文档就好了，复制那段 launch
> 
> 我的是c++工程。官方文档是node.js

？？这是 Egg 的一个 vscode 插件，跟 c++ 啥关系？你写 C 的插件？
