### ISSUE TITLE
egg-static 有超级严重安全性问题！！！！！

### ISSUE THREAD

**Issue by gx761** [eggjs/egg#1049]
egg-static依赖koa-static-cache。 而koa-static-cache有严重安全性问题，导致服务器上的任意文件可以被直接下载！！！！

http://127.0.0.1:7001/%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F.%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2F..%2Fetc%2Fpasswd

通过上面的路径就可以导致服务器的passwd文件直接被拿到！

egg团队在选择插件的时候麻烦也检查一下代码的质量。另外既然egg在阿里内部被大量使用，这种常用插件就应该官方提供而不是依赖个只有100多星的第三方库。

**Comment by popomore** [comment]
egg-static 的配置是什么？

**Comment by fengmk2** [comment]
koa-static-cache 最新版本已经修复。

**Comment by okoala** [comment]
@gx761  生产服务器要尽量使用 nginx 来做反向代理，用 nginx 处理静态资源。一是性能好，二是安全。

**Comment by gx761** [comment]
@popomore , 跟配置没什么关系。任何配置都会导致上面的问题。koa static最新的5.0.1的版本貌似已经修复，但是最新egg-static还是依赖的4.0.1, 赶紧升级下吧。

**Comment by okoala** [comment]
@gx761 koa-static-cache v4.1.1 同时有修复 https://github.com/koajs/static-cache/commit/a71ecb5d58f3d12263b228b68e66425e6bc1a827
你重新下载安装 node_modules 就可以了
