### ISSUE TITLE
线程间的通讯事件请教

### ISSUE THREAD

**Issue by yejinjian** [eggjs/egg#105]
最近开始看egg的源码，试着写liveload插件
发现几个问题想探讨下：

1： 在egg-cluster中的master 多次出现 “egg-pids” 我个人理解是： 通知其他线程 我发生改变了, 比如app线程 通知agent  一个appStart 或者 appExit， 主要这个我看到了send 触发 没有找到对应的监听，获益好奇问下 egg-pids 主要的作用是什么
2： 我最初其实想知道"reload-worker" 触发执行成功后的事件，但是我没有找到，isAllAppWorkerStarted的设计 "reload-worker"  不会触发 ready, 所以没法直接捕获，我自己做法是通过“egg-pids” 模拟了一个，不知道是否符合作者的设计

```
process.on('message', msg => {
    if (typeof msg === 'string') msg = { action: msg, data: msg };
    msg.from = 'agent';
    emitter.emit(msg.action, msg.data);
  });

  emitter.once('egg-ready',(opts) => {
    const workerNum = opts.workers;
    emitter.on('egg-pids', (data) => {
      // 只能通过worker的个数做判断是否最终启动成功
      if(data instanceof Array && data.length === workerNum) {
        logger.error(data);
        server.notifyClients(["*"]);
      }
    })
  });
```

[egg-live的npm地址](https://www.npmjs.com/package/egg-liveload)

**Comment by atian25** [comment]
https://github.com/eggjs/egg-development 可以看看

**Comment by jtyjty99999** [comment]
development已经提供liveload的功能了

**Comment by yejinjian** [comment]
@jtyjty99999   @atian25  我就是读了了egg-development 中的代码  看它实现了监听文件改变，重启线程，与写日志，所以我才想到加一个liveload 触发前端页面自动刷新， 

我的问题是 “reload-worker”  成功后 没有办法直接捕获。

**Comment by jtyjty99999** [comment]
egg-cluster里面的master.js捕获的reload_worker

**Comment by atian25** [comment]
@yejinjian development 目前的实现是监控后端代码然后重启 node 的. 

前端代码的变更一般不需要重启 node, 目前 development 应该不支持.

我之前在内网的做法是写另一个插件, 使用 egg-watcher 或 browsersync 来监控前端代码, 然后通知刷新

**Comment by yejinjian** [comment]
我的意识是 master 捕获reload-worker 后 执行 新建app线程，后关闭旧的线程后 最好能可以通知给agent知道， 这是我个人的一个看法。

我写的egg-liveload 是在egg-development上 监听前端与后端文件的改变， 都能通知到浏览器刷新，我看到egg-development 已经做了后端的重启node  所以想讨个巧 前端可以liveload.

**Comment by jtyjty99999** [comment]
目前确实没有通知，只是暴力重启和记录日志，欢迎提pr，你的需求可以像@atian25所说使用egg-watcher处理，前端代码刷新没必要跟后端重启绑定起来哈

**Comment by popomore** [comment]
前端的 livereload 不需要 agent 感知的，app worker 能够监听到就可以了

1. agent 监听文件变化，发事件告知重启
1. app worker 等待启动通知浏览器

**Comment by atian25** [comment]
目前 agent 重启是会通知 worker 的,  

https://github.com/eggjs/egg/blob/master/lib/core/app_worker_client.js#L298

但反过来好像是没有.

@popomore 看看?

**Comment by yejinjian** [comment]
@popomore  我目前把liveload server 放在agent线程，我不知道会不会是我的理解错误，我觉得这类管理的工作适合在agent做；  此外 如果放在  app woker 还是有一个问题的，app woker 启动后，会有一个新旧woker同时存活的状态， 我目前时判断当前启动的 app worker数与 设定的 woker数一致 来做woker-reload成功。

**Comment by popomore** [comment]
如果放在 app worker 实现就简单很多，一般开发本地都只有一个 app worker，同时存在是怕端口占用？

**Comment by yejinjian** [comment]
@popomore  是的 我只是遵照你们的设计思想。  如果放在app worker的确简单很多。

**Comment by fengmk2** [comment]
@atian25 在 https://github.com/eggjs/egg-view-nunjucks 加个 view 模板刷新缓存的例子？

**Comment by atian25** [comment]
开发期是禁止 cache的，还有文档里面写了 cleanCache 的 API。

跟这个 issue 有什么关联？

**Comment by fengmk2** [comment]
@atian25 就是你回复 https://github.com/eggjs/egg/issues/105#issuecomment-246257095 说的，给个例子，会更加形象。

**Comment by atian25** [comment]
我写的那个是监控前端代码变更后重新编译, 刷新只是 browsersync 顺带的.

没有涉及到 view 的缓存刷新, 因为开发期 view 是没缓存的.

大概就这样:

```js
// agent.js
const path = require('path');
module.exports = agent => {
  const baseDir = agent.config.baseDir;
  const watchDirs = ['app/components', 'app/views', 'app/public', 'fis-conf.js'];
  agent.messenger.on('egg-ready', options => {
    agent.watcher.watch(watchDirs.map(dir => path.join(baseDir, dir)), info => {
       console.log('changed', info);
    });
  });
};

**Comment by yejinjian** [comment]
请看下我的liveload插件 虽然不是很规范，但我自己用效果还行^-^  目前就是worker-reload会有点久，还有我文件监控与egg-development重复。

**Comment by popomore** [comment]
那这个可以关了？
