### ISSUE TITLE
node v8.1.1下使用vscode调试出错

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1052]
错误信息：# Cannot connect to runtime via 'legacy' protocol; consider using 'inspector' protocol (timeout after 10000 ms).

node： v8.1.1
egg:  v1.4.0
vscode：1.13.0
最小可复现的代码仓库：git clone https://github.com/linxuanwei/egg-debug-vscode-bug.git
**必现**

在命令行跑 `npm run debug`，然后用vscode运行 `Attach Worker`是OK的。

launch.json 文件如下：

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Egg",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug"
            ],
            "port": 5858
        },
        {
            "name": "Attach Agent",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "port": 5856
        },
        {
            "name": "Attach Worker",
            "type": "node",
            "request": "attach",
            "protocol": "inspector",
            "restart": true,
            "port": 10086
        }
    ],
    "compounds": [
        {
            "name": "Debug Egg",
            "configurations": [
                "Launch Egg",
                "Attach Agent",
                "Attach Worker"
            ]
        }
    ]
}`

**Comment by okoala** [comment]
好，我看看~

**Comment by okoala** [comment]
@linxuanwei   
![image](https://user-images.githubusercontent.com/2127199/27128431-03f87b2c-5131-11e7-9ee7-ef1df2ba79b4.png)

你详细描述下重现的步骤？ 我这边是OK的。

**Comment by StephenSeraph** [comment]
- 他的意思是说基于他的这个复现的项目代码，在vscode里通过compounds里的名为Debug Egg的配置来启动调试是会报legacy这个错误的。
- 这个错误其实是Launch Egg那里来的。
- 然后，如果先在终端运行`npm run debug`，然后再在vscode里通过Attach Worker启动就是正常的。确实如此。

**Comment by okoala** [comment]
@StephenSeraph 之前 vscode 版本是没这问题，最新更新的这一波不知道改了啥~我看看吧~

**Comment by okoala** [comment]
@linxuanwei  我关联了一波 vscode 相关 issue，现在 vscode 不支持 inspector 协议的 lanunch~

**Comment by dead-horse** [comment]
调试相关的 issue 先关了，有问题可以继续讨论

**Comment by linxuanwei** [comment]
@okoala    sorry，刚看到这么多回复，刚起床，还没去公司

问题情况如 @StephenSeraph  所述，一模一样。

我估计也是vscode对inspector的lanunch支持的不够好，等下个vscode版本出来再看看咯。

大家辛苦了~

**Comment by jasonslyvia** [comment]
参考 https://github.com/eggjs/egg-development-proxyworker 的配置不能成功 debug，先 npm run debug 再 attach 是 work 的
