### ISSUE TITLE
egg-mongoose 连接数据库时报警告

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1054]
MongoDB version： v3.4.1

**Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiplecredentials on a socket. Please authenticate using MongoClient.connect with auth credentials.**

使用egg-mongoose插件时，启动就报该警告

1. 是否是egg-mongoose所依赖的mongoose版本问题？

2. 不敢贸然升级或降级MongoDB

3. 有何解决方案

**Comment by jtyjty99999** [comment]
egg-mongoose的版本是什么？ 新版本egg-mongoose已经把 authenticate逻辑去掉了

**Comment by jtyjty99999** [comment]
你是不是使用了 db.command 之类的方法

**Comment by linxuanwei** [comment]
@jtyjty99999    egg-mongoose 版本：2.1.0

egg启动时报的警告，只是enable了该插件，还没有调用任何命令

```
 config.mongoose = {
    url: 'mongodb://cms:passwd@x.x.x.x.:27017,x.x.x.x:27018,x.x.x.x:27019,x.x.x.x:27017/cms',
    options: {},
  };
```

**Comment by linxuanwei** [comment]
是在连接mongodb的时候报的

**Comment by jtyjty99999** [comment]
@linxuanwei 没关系，目前是兼容的，后面我们会根据社区使用情况升级mongoose的依赖

**Comment by linxuanwei** [comment]
恩 好的   这个问题应该不大  
4.x之前都是兼容的  我先这么用吧  就是看着mongoose打印的警告日志跟egg的风格不一样，感觉好丑，有点程序员洁癖
