### ISSUE TITLE
请问什么时候出webstorm的eggjs插件

### ISSUE THREAD

**Issue by acid122** [eggjs/egg#1057]
* **Node Version**:v.7.10.0
* **Egg Version**:1.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

大家好，我们目前遇到一个小问题，vscode有eggjs-dev-tools插件实现egg项目的代码提示，但是vscode似乎没有ctrl查看源代码的功能；但是Webstorm支持ctrl查看源代码，只是Webstorm没有代码提示，不知道Webstorm有类似的插件吗

**Comment by dead-horse** [comment]
官方不会提供这类支持
