### ISSUE TITLE
EGG如果做API服务时且开始CSRF验证，如果使用POST方式如何在提交请求时带上csrfToken呢？

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#1058]
-  EGG如果做API服务时且开始CSRF验证，如果使用POST方式如何在提交请求时带上csrfToken呢？
-  csrfToken的值如何获取？
-  GET的时候，服务端会自动在set-cookie里面加入csrfToken，然后客户端在接下来的请求中直接从cookie获取，如果直接使用POST方法，如何获取呢？

###求各位大神给指点迷津。

**Comment by dead-horse** [comment]
如果是做 API 服务，建议配置[csrf 忽略 json 请求](https://eggjs.org/zh-cn/core/security.html#忽略-json-请求)，要求服务调用方必须通过 JSON 格式发起 POST / PUT 等请求。

**Comment by Crayon-ShinChan** [comment]
> 如果是做 API 服务，建议配置[csrf 忽略 json 请求](https://eggjs.org/zh-cn/core/security.html#%E5%BF%BD%E7%95%A5-json-%E8%AF%B7%E6%B1%82)，要求服务调用方必须通过 JSON 格式发起 POST / PUT 等请求。

这种方式好想已经被废弃，攻击者可以通过 flash + 307 来攻破。我们现在最好的做法是什么呢

https://eggjs.org/zh-cn/core/security.html#%E5%BF%BD%E7%95%A5-json-%E8%AF%B7%E6%B1%82%E5%B7%B2%E5%BA%9F%E5%BC%83

**Comment by dead-horse** [comment]
如果是纯粹的 API 服务。不是网站页面发起的 ajax 请求接口，请不要对其配置 CSRF 防范。如果由页面上发起的 ajax 请求接口，按照文档配置 token 模式或者 referer 白名单校验。
