### ISSUE TITLE
关于egg-sequelize 和 egg-validate 的参数验证取舍😄

### ISSUE THREAD

**Issue by MinJieLiu** [eggjs/egg#1062]
* **Node Version**: 8
* **Egg Version**: 
* **Plugin Name**: egg-sequelize、egg-validate
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

 `sequelize` 有属性字段验证，`egg-validate` 也是字段验证库。

若我用 `egg-sequelize` 的时候还有必要再使用 `egg-validate` 吗，感觉它们之间的功能重复了。

我该如何完美封装字段验证方法呢，并且能有`400`错误而不能忽略数据库本身的错误😭😄😄

**Comment by dead-horse** [comment]
egg-validate 是对请求参数做验证，egg-sequlize 是对存到数据库里面的数据做验证，两者用途不一样，对用户请求参数的验证总是要提前做的。

**Comment by MinJieLiu** [comment]
感谢你解开了我的迷惑，💖💖
