### ISSUE TITLE
egg-static 如何配置可以支持多个目录

### ISSUE THREAD

**Issue by gongchao** [eggjs/egg#1063]
我现在想把 public/admin 映射到 http://localhost/admin 、 public/view 映射到  http://localhost/ 我该怎么做呢？

**Comment by okoala** [comment]
@gongchao  有几种实现的方式
1. prefix 设置为 ‘/’,  public/view 的文件放到 public 根目录中。
2. 使用 okoala/egg-multiple-static 这个包，支持多个目录分别映射。

**Comment by atian25** [comment]
为什么要 「public/view 映射到 http://localhost/」？不考虑 router 了么？

你们只是做纯静态页面么？

**Comment by gongchao** [comment]
@okoala 🙏 Thk 正需要～

**Comment by gongchao** [comment]
@atian25 明白了
