### ISSUE TITLE
RestAPI 风格的 URL 定义时destroy方法404

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1065]
router.js
`app.resources('members', '/api/v1/members', 'v1.members');`

controller/v1/members.js
    /**
     * 删除帐号
     * DELETE /api/v1/members/:id
     */
    * destroy() {
      const { ctx, service } = this;
      return yield service.user.del(ctx.params);
    }
其它方法都访问正常

**Comment by okoala** [comment]
@89790094  请提供个可以完整重现情况的项目~

**Comment by 89790094** [comment]
@okoala 
 GET /api/v1/members/:id 是没问题的

**Comment by 89790094** [comment]
@okoala  好了，应该粗心造成的，谢谢〜〜
