### ISSUE TITLE
有没有可以生成egg-sequelize的model的插件？

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#1067]
有没有可以生成egg-sequelize的model的插件？

**Comment by liuliangjia** [comment]
我的数据表里没有created_at，只有createdAt，查询findAll就出错，有没有办法？

**Comment by popomore** [comment]
model 定义可以配置的，查看 sequelize 官方文档

**Comment by liuliangjia** [comment]
const Foo = sequelize.define('foo',  { /* bla */ }, {
  // don't forget to enable timestamps!
  timestamps: true,

  // I don't want createdAt
  createdAt: false,

  // I want updatedAt to actually be called updateTimestamp
  updatedAt: 'updateTimestamp',

  // And deletedAt to be called destroyTime (remember to enable paranoid for this to work)
  deletedAt: 'destroyTime',
  paranoid: true
})

这一段好像是整个关闭字段，我想要的效果是字段名不带下划线，应该也是有这样的配置的吧？

**Comment by banyudu** [comment]
@liuliangjia 你给出的代码中不就有示例么？

`createdAt: false`是不使用 createdAt字段，

`createdAt: 'createdAt'`是使用 createdAt 字段名

`createdAt: 'created_at'` 是使用 created_at 字段名

**Comment by banyudu** [comment]
@liuliangjia 如果想要根据数据库表生成Model，可以使用 sequelize 的 describeTable 获取attributes，然后在外面包一层。

这已经是Sequelize的用法的问题了，和egg没什么关系

**Comment by popomore** [comment]
忘记关闭了， @banyudu 谢谢帮助答复。

**Comment by liuliangjia** [comment]
我后来拿sequelize-auto生成，然后import进来。
您这种每一个model都手写的，去配置这个createdAt就是这么来。我整个库都是createdAt，然后拿sequelize-auto自动生成数据表对应的model，默认的都是createdAt。

**Comment by liuliangjia** [comment]
我后来拿sequelize-auto生成，然后import进来。
您这种每一个model都手写的，去配置这个createdAt就是这么来。我整个库都是createdAt，然后拿sequelize-auto自动生成数据表对应的model，默认的都是createdAt。

**Comment by superlbr** [comment]
@banyudu 我认为跟egg有关系, egg-sequelize的model跟sequelize-auto生成出来的并不一致，还是得自己去改写
