### ISSUE TITLE
Cannot  read property 'type' of undefined

### ISSUE THREAD

**Issue by NeverMore93** [eggjs/egg#1070]
![image](https://user-images.githubusercontent.com/12440004/27272404-888b960c-54fc-11e7-9a42-271d608d323b.png)
I init my example follow by readme,but There is a TypeError

**Comment by atian25** [comment]
it sounds like a network error, plz retry or add `-r=china`

I will fix the type error at `npm-updater`

**Comment by NeverMore93** [comment]
like   $ egg-init showcase --type=simple -r=china ???

**Comment by atian25** [comment]
yes, `-r=china` will change npm registry to `https://registry.npm.taobao.org`

btw, now you could reinstall egg-init@3.0.3 by `npm install -g egg-init`, which will log the correct error message.
