### ISSUE TITLE
egg-bin中istanbul覆盖率支持json-summary

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#1071]
RT, egg-bin中 `cov`命令里关于istanbul的format格式写死了，无法配置

egg-bin中的源码位置：

```
/**
   * get coverage report args
   * @param {String} coverageDir - coverage result directory
   * @return {Array} args for istanbul coverage report
   * @protected
   */
  getReportArgs(coverageDir) {
    return [
      'report',
      '--root', coverageDir,
      'text-summary',
      'json',
      'lcov',
    ];
  }
```

是否可以提供配置化，目前我们需要`json-summary`格式，用于云效或aone等流程构建平台能够抓取总的覆盖率报告结果。

**Comment by atian25** [comment]
可以考虑提供个 `--summary=json/text` 的参数，欢迎 PR。

@popomore  https://github.com/eggjs/egg-bin/pull/63 里面也考虑下这个？

**Comment by popomore** [comment]
默认加上吧，不用加参数

**Comment by atian25** [comment]
@popomore 换掉 text-summary?

**Comment by popomore** [comment]
Text 有用的，命令行里要看的

**Comment by atian25** [comment]
那怎么个默认法？ 支持多个参数的？ 这个配置的文档哪里有详细一点的

**Comment by atian25** [comment]
@johnnychen 在 https://github.com/eggjs/egg-bin/issues/64 支持了，等 ci 过就合并发版本，今天 ci 有点慢。

**Comment by johnnychen** [comment]
@atian25 赞！~

**Comment by atian25** [comment]
合并后会自动 close，不用手动 close
