### ISSUE TITLE
egg-sequelize 3.0，associate，sync失败。

### ISSUE THREAD

**Issue by gx761** [eggjs/egg#1072]
* **Node Version**: 7.10.0
* **Egg Version**: 
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.0.0
* **Platform**: windows
* **Mini Showcase Repository**:

更新了最新的egg-sequelize3.0 , sequelize4.1.0, 之后遇到了sync失败的问题。
ypeError: Cannot read property 'prototype' of undefined

\node_modules\sequelize\lib\associations\mixin.js:12:16

使用了新的classmethod的定义方法， 也就是说先define一个model，然后
model.associate = function() {
     app.model.Category.hasMany(app.model.Component, { onDelete: 'cascade' });
}
在sync的时候, app.model.Component直接是undefined, 导致reference error。

不太清楚egg-sequelize的机制，理论上应该先把所有model都新建起来，然后来处理associate, 但是现在貌似在新建一个model的同时处理了associate, 而其它model根本还没新建。

**Comment by jtyjty99999** [comment]
升级下 egg-sequelize 3.0.1试试

**Comment by gx761** [comment]
3.0.1 可以了。
