### ISSUE TITLE
请问有么有现成的权限管理体系组件

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#1074]
* **Node V7.10.0**:
* **Egg 2.2.3**:

如题

看了咱们的扩展有 egg-userole  and  egg-userservice 
真心没有中文手册看不懂咋用哦!

**Comment by dead-horse** [comment]
egg-userole

**Comment by junmaqiang** [comment]
这个看过,没有例子真心不明白咋用! @dead-horse

**Comment by AkashiX** [comment]
@junmaqiang 可以参照test

**Comment by atian25** [comment]
test/fixture 就是最好的 example

- https://github.com/eggjs/egg-userrole/blob/master/test/fixtures/userrole/app/router.js
- https://github.com/eggjs/egg-userrole/blob/master/test/fixtures/userrole/config/role.js

**Comment by junmaqiang** [comment]
谢谢, 看到了!  @atian25

**Comment by miaojiuchen** [comment]
可以看看我的这个demo repo https://github.com/miaojiuchen/eggjs-userrole-demo
