### ISSUE TITLE
egg-view-nunjucks 模板如何拿到session对象

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#108]
在egg-view-nunjucks模板页面内部，如何拿到session对象？

**Comment by luckydrq** [comment]
`{{ ctx.session.xxx }}`

https://github.com/eggjs/egg/blob/master/lib/core/view.js#L78

**Comment by atian25** [comment]
有注入了 ctx，可以通过 ctx.session 拿到。但更建议是在 controller 里面过去，然后通过 render 的第二个参数传递进去。

https://github.com/eggjs/egg/blob/master/lib/core/view.js#L78

**Comment by zhoudaqing** [comment]
@luckydrq @atian25  谢谢 可以了
