### ISSUE TITLE
建议：egg提供API Docs生成工具

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1081]
是否能提供或继承类似swagger一样的API DOCS工具，这样使用起来更方便和高大上

**Comment by popomore** [comment]
有兴趣可以帮助搞一下，现在主要的问题不是工具，写的还不是很规范，如果都写了查起来还是很方便的。

**Comment by gordonpro** [comment]
https://github.com/m31271n/egg-swagger-ui
