### ISSUE TITLE
求助controller下基类的写法

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#1082]
因为常规业务的增删改查都是雷同的,我想都写到基类里面!

请问我想写一个`/controller/base.js` 作为基类,
让 `controller/user.js   controller/role.js` 都继承 `controller/base.js `  

`controller/user.js`咋写!

`/controller/base.js` 咋写?

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/basics/controller.html

文档有写自定义基类

**Comment by junmaqiang** [comment]
说真的, 没看懂!
因为环境和版本可能存在差异
我的项目目录里面没有app.js 有 index.js
而且里面的内容也是差距很大,如下:
//index.js
`
'use strict';
// 引入框架
const egg = require('egg');
// 获取CPU数量
const workers = Number(process.argv[2] || require('os').cpus().length);
// 启动框架
egg.startCluster({
  workers,
  baseDir: __dirname,
  port: process.env.PORT || 7001,
});

`

所以, 官方文档也是看的,只是和实际情况给人感觉有些蛋疼!

**Comment by junmaqiang** [comment]
#579 #403 这两个方法我都试了 还是掉不到! @popomore

**Comment by atian25** [comment]
试过 https://github.com/eggjs/examples/blob/master/redefine-controller/app.js 么?

**Comment by junmaqiang** [comment]
我算是明白原因了!
入口文件里面修改后,要删除run目录,在重启下服务 就可以了!

**Comment by ngot** [comment]
重启服务器是必须多，node和php不同。 但是，应该是不需要手动去删除run目录的。

**Comment by junmaqiang** [comment]
本次问题变相的解决了
但意味着我要写很多代码到入口文件app.js里面,
实际上我是期望在`controller`下面的js文件都继承 `controller/base.js ` 这个文件的写法! 
兄弟们帮忙, 感谢感谢 @popomore @atian25

**Comment by atian25** [comment]
为什么要写很多代码到 app.js? 只需要写一个 base 不就行了?

**Comment by junmaqiang** [comment]
对, 我也这么认为, 
现在就是不知道 controller下面的js 是继承app.controller 还是 继承BaseController 
继承BaseController 的写法不会.  求例子 @atian25 天猪哥

**Comment by atian25** [comment]
https://github.com/eggjs/examples/blob/master/redefine-controller/app.js 这不就是例子么?

controller 下的 JS 都会继承 app.BaseController，然后你只需要在 app.js 里面覆盖掉你自己的 BaseController 不就行了。

**Comment by junmaqiang** [comment]
我是这么写的 (按照php的继承方式)

```
module.exports = app => {
  class UserController extends BaseController {
     
 }
  return UserController;
}
```

服务就报错提示 `ReferenceError: BaseController is not defined`






核心问题就在 我想把代码写到 controller/base.js 下面 哈~
就是不想写到app.js 里面呢!  @atian25

**Comment by ngot** [comment]
app.js
```js
module.exports = app => {
    app.BaseController = class BaseController { }
}
```

// conrtoller/user.js
```js
module.exports = app => {
  class UserController extends app.BaseController {
     
 }
  return UserController;
}
```

**Comment by ngot** [comment]
或者 

// path xyz.js

```js
class BaseController { }
module.exports = BaseController;
```

// conrtoller/user.js
```js

const BaseController = require('path xyz.js');

module.exports = app => {
  class UserController extendsBaseController {
     
 }
  return UserController;
}
```

**Comment by junmaqiang** [comment]
好了,我终于搞明白了! 感谢兄弟们的辛苦解答!

controller下面的.js文件该咋写还是咋写不用动,
然后只要把`controller/base.js` 最下面 `return BaseController` 改为 `app.Controller = BaseConrtoller; `就实现我的想法了! 

谢谢,亲爱的朋友们帮我解答!

**Comment by atian25** [comment]
`base.js` 不要放到 `controller` 目录下，放到 `{app_root}/lib/base_controller.js`，然后在 `app.js` 里面 require 它。

**Comment by junmaqiang** [comment]
我在controller  service view 三个目录下都做了分组,我想让每个分组都继承自己的base呢? 咋写? @atian25  猪哥指点下!

**Comment by atian25** [comment]
Controller 用 BaseController，Service 用 BaseService， View 自己在原插件基础上扩展或 Context 对应的方法。

**Comment by junmaqiang** [comment]
以下是我的写法, 但是出问题了!

// controller/base.js
```
/**
  * @name 基础模块
  * @description 基础模块
  */
'use strict';
module.exports = app => {
  class BaseController extends app.Controller {
    /**
     * 初始化
     * @param {Object} ctx -内置对象
     */
     constructor(ctx) {
       super(ctx);
     }

    /**
     * 列表
     *
     * @param {Object} model - 数据接口.
     * @param {Object} status - 当前状态.
     * @param {Object} [params] - 参数.
     */
    async _lists(model, status, params) {
       // 抽取参数
      const { ctx } = this;
       // 数据请求
      const { result, _meta } = await ctx.service.admin[`${model}`].list(params);
       // 模板变量
      const datas = {
        title: status.title + '列表', // 网页标题
        tab_index_active: 'active', // tab状态
        items: result, // 数据列
        //  alert: status.alert,// 消息组件
        _meta, // 分页参数
        params, // 搜索参数
      };
       // 合并模板变量
      datas[`${model}_active`] = 'active';
       // 异步渲染
      await ctx.render('admin/' + model + '/index', datas);
    }
  }
  return BaseController;
};
```


// controller/user.js
```
/**
  * @name 用户模块
  * @description 用户中心
  */
'use strict';
const BaseController = require('./base.js');
module.exports =  {
  class UserController extends BaseController {
    /**
     * 初始化
     * @param {Object} ctx -内置对象
     */
    constructor(ctx) {
      super(ctx);
      // 设置标题
      this.title = '用户';
      // 数据规则
      this.rules = {
        username: { type: 'string', required: true },
        mobile: { type: 'string', format: /\d+/, required: true },
      };
      // 分页规则
      this.rulesPage = {
        page: { type: 'string', format: /\d+/, required: false },
        per_page: { type: 'string', format: /\d+/, required: false },
      };
      // 搜索规则
      this.rulesSearch = {
        types: { type: 'enum', values: [ 'username', 'mobile', 'nickname', 'id' ], required: false },
        keyword: { type: 'string', required: false, allowEmpty: true }, // 可以为空true 不可以为空false
      };
    }

    /**
     * 列表
     *
     * @param {Object} [options] - options for request.
     */
    async index() {
      // 抽取参数
      const { ctx } = this;
      // 获取参数
      const params = ctx.query;
      // 校验分页参数
      ctx.validate(this.rulesPage, params);
      // 校验搜索参数
      ctx.validate(this.rulesSearch, params);
      // 状态变量
      const status = {
        title: this.title,
      };
      // 请求base内的公用方法
      await this._lists('user', status, params);
    }
  }
  return UserController;
};

```

**Comment by atian25** [comment]
你需要非常仔细的看一遍我们给出的 example， user 是不需要手动引入 base 的，完全无感知的，直接继承 app.Controller 即可。

BTW： 建议可以把 「JavaScript 语言精髓」看一遍，
```js
ctx.service.admin[`${model}`]
// 不就是下面这句么
ctx.service.admin[model]
```

**Comment by junmaqiang** [comment]
@atian25  猪哥, 下面的代码我就不明白了
`// lib/base_controller.js
// 不要放到 controller 目录！
module.exports = app => {
  return class CustomController extends app.BaseController {
    // ...
  }
}`

按我的个人理解,` lib/base_controller.js`是不是要改为下面的写法?
`// lib/base_controller.js
module.exports = app => {
  return class BaseController extends app.Controller {
    // ...
  }
}`

**Comment by atian25** [comment]
是 app.Controller 我写错了，已改。

https://eggjs.org/zh-cn/basics/controller.html#自定义-controller-基类

上面给过的这篇文档，写的很清楚了，建议看看。

**Comment by ahuigo** [comment]
@atian25 我感觉这样不太优雅。因为经常要手动修改相对路径

```
// /app/controller/user.js
const BaseController = require('../core/controller');// 二级
// /app/controller/api/user.js
const BaseController = require('../../core/controller');// 三级
```

我想这两个方法会好点吧：
1. 将`app.controller` 覆盖为`BaseController` 最省事了
2. `require(APP_ROOT+'/core/controller');`  不知道有没有类似这样全局的
