### ISSUE TITLE
egg-socket.io example not works

### ISSUE THREAD

**Issue by seajean** [eggjs/egg#1083]
* **Node Version**:  6.9.1
* **Egg Version**:   1.4.0
* **Plugin Name**:   egg-socket.io
* **Plugin Version**:  1.0.0
* **Platform**:  macOS
* **Mini Showcase Repository**:
https://github.com/eggjs/egg-socket.io/tree/master/example 

ways to produce this problem:
`npm install `
`npm run start`

**Comment by ngot** [comment]
Found the problem. The reason is the new egg require the config provide the keys config. But the example code is written a long time ago.  I will add the keys config.

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/19

**Comment by ngot** [comment]
solved!
