### ISSUE TITLE
【bug】在centos上用xshell ssh连接后 按照官方的方式部署 退出ssh后应用停止了

### ISSUE THREAD

**Issue by liuhuanhui** [eggjs/egg#1084]
在centos上用xshell ssh连接后 按照官方的方式部署 退出ssh后应用停止了

**Comment by ngot** [comment]
使用 nohup 后台执行。或者使用 screen 来启动。否则node进程会和ssh会话一起退出的。

**Comment by liuhuanhui** [comment]
EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &
 我就是这样启动的~

**Comment by ngot** [comment]
执行完后node后台了吗？

**Comment by ngot** [comment]
ps -ef| grep node 看看

**Comment by liuhuanhui** [comment]
ps -ef| grep node里面找到了，但是退出ssh程序还是停止了

**Comment by ngot** [comment]
你试试 screen

**Comment by liuhuanhui** [comment]
screen怎么启动

**Comment by jsgeeker** [comment]
为什么要关闭这个issue，问题依然存在，

按照官方教程，EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &
centos上依然存在这个问题。

希望官方给予解决。

**Comment by liuhuanhui** [comment]
我也是没有解决，后台我直接改用pm2启动了

**Comment by jsgeeker** [comment]
我最后是这样做的。
EGG_SERVER_ENV=prod pm2 start index.js --name name

**Comment by LiShiSangZi** [comment]
我们目前两种方法：
一种是拿screen启动。
还有一种是做了systemd，那systemctl启动的。毕竟是生产环境，第二种更加规范一点。

**Comment by chen19901225** [comment]
@liuhuanhui 能给个systemd 的service配置吗， 我配置了好久都没有成功

**Comment by liuhuanhui** [comment]
@chen19901225 我改用pm2了

**Comment by atian25** [comment]
这个 issue 比较早了，现在直接用 egg-scripts 即可。

参见文档：https://eggjs.app/zh-cn/core/deployment.html#%E9%83%A8%E7%BD%B2
