### ISSUE TITLE
Egg 奉行『约定优于配置』这些地方你们晕不晕!

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#1085]
比如:
 this.app  || ctx.app
 this.service  || ctx.service || this.ctx.service 
this.config   ||  app.config || this.app.config

还有更多地方看了好久  一是记不住,  二是晕, 三真晕啊!

**Comment by atian25** [comment]
可以再去阅读下：https://eggjs.org/zh-cn/basics/objects.html

**Comment by popomore** [comment]
不用记，想用的时候总能取得到
