### ISSUE TITLE
koa-csrf deprecate warning

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#109]
> [koa-csrf@2.5.0](./node_modules/.1.2.1@egg-security/node_modules/koa-csrf) deprecate: If you are using Koa v3.x, please make sure you are on at least 3.0.3 due to CSRF session reset issue (prevents XHR from working properly for example)

**Comment by jtyjty99999** [comment]
https://github.com/koajs/csrf/commit/c24564ecbf88aceb519e138ca49be205f7034a0c

**Comment by dead-horse** [comment]
提去 csrf 那边吧，不知道谁搞的

**Comment by jtyjty99999** [comment]
比较费解，什么叫v3.x

**Comment by atian25** [comment]
https://github.com/koajs/csrf/issues/28

**Comment by popomore** [comment]
<img width="416" alt="screenshot 2016-09-19 6 22 26" src="https://cloud.githubusercontent.com/assets/360661/18629091/0c512940-7e96-11e6-8df7-888d39f856ce.png">

看起来改的很随意

**Comment by atian25** [comment]
在 https://github.com/koajs/csrf/issues/28#issuecomment-247952906 有人 ping 你们 @dead-horse @shaoshuai0102

**Comment by popomore** [comment]
这个解决了吧

**Comment by shaoshuai0102** [comment]
好像是没了
