### ISSUE TITLE
问下，如何用eggjs一框架实现多应用开发，比如 管理后台、会员中心、前台，也可以理解为module

### ISSUE THREAD

**Issue by ihubcode** [eggjs/egg#1091]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
现在流行微服务，做成多个应用。

**Comment by ihubcode** [comment]
@popomore  微服务怎么做

**Comment by ihubcode** [comment]
@popomore   eggjs 怎么做微服务，指导下~~

**Comment by popomore** [comment]
就是把你上面说的单独做成应用，而不是 module。

**Comment by fengmk2** [comment]
https://github.com/npm/registry/blob/master/presentations/2017-Q2.md#fit--22 类似这种，单一智能的服务

**Comment by ihubcode** [comment]
@popomore   你的意思是我要这么用？
![image](https://user-images.githubusercontent.com/23080204/27470117-e84665c4-5824-11e7-84cc-1a97878b64a4.png)

**Comment by popomore** [comment]
是的
