### ISSUE TITLE
egg-socket在哪配置端口呢

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1096]
egg-socket在哪配置端口呢

**Comment by iyuq** [comment]
egg-socket和egg是共用一个端口的，可以在./index.js中定义端口，比如
```
'use strict';

require('egg').startCluster({
  baseDir: __dirname,
  port: process.env.PORT || 7001, // default to 7001
});
```
在npm中的scripts中加上 `"start": "node index.js",`，就可以指定prod下的端口，至于dev，可以直接用`npm run dev --port 7001`来指定端口。

**Comment by atian25** [comment]
@iyuq 是 `npm run dev -- --port 9999`

**Comment by iyuq** [comment]
@atian25 这个写法好奇怪呀

**Comment by atian25** [comment]
`egg-bin dev --port=9999` 和 `npm run dev -- --port 9999`

这个不是 egg 自己的约定，而是 linux 的通用约束来着。 `--` 后面的参数当前 scripts 不处理，直接透传到里面的 scripts。

**Comment by iyuq** [comment]
@atian25 明白了。我应该想写的是在scripts中加`"dev": "egg-bin dev --port 7001"`。
