### ISSUE TITLE
egg项目执行exec报错

### ISSUE THREAD

**Issue by lys623** [eggjs/egg#1099]
![c412693d-36eb-43f5-9b8a-68316fa5ecd8](https://user-images.githubusercontent.com/4364314/27479963-b903e89e-5848-11e7-9b8d-af195ef7c3e2.png)

如图，手动启动egg项目的时候，程序运行这段代码，用require('child_process').exec执行没问题，系统开机自动运行egg项目的时候，运行就报错了，是什么问题呢？权限吗？怎么解决？

**Comment by popomore** [comment]
不知道如何使用的，得去 casperjs 问

官方建议部署操作见 https://eggjs.org/zh-cn/core/deployment.html#后台运行

**Comment by atian25** [comment]
不建议用 casperjs，估计是需要配置 headless 什么的重定向，搞不懂。
可以考虑使用：
- https://github.com/segmentio/nightmare
- https://zhuanlan.zhihu.com/p/27100187
