### ISSUE TITLE
关于CSRF遇到的一个问题

### ISSUE THREAD

**Issue by mattmengSemioe** [eggjs/egg#1103]
* **Node Version**:v8.1.2
* **Egg Version**:1.4
* **Plugin Name**:egg-security
* **Plugin Version**:1.11.0
* **Platform**: MacOs
* **Mini Showcase Repository**:

    1.我通过阅读https://eggjs.org/zh-cn/core/security.html 发现文档中并没有提到ajax请求API时的csrfToken是插件自己写入的还是需要我们自己手动写入。

    2.描述中只提到了form表单会自己写入，我用的egg-view-ejs模板来渲染数据，这是否和我用的模板有关系。

**Comment by solarhell** [comment]
1: https://eggjs.org/zh-cn/plugins/security.html#using-csrf-when-request-by-ajax

2: https://eggjs.org/zh-cn/core/security.html#同步表单的-csrf-校验 ```egg-view-nunjucks 等 View 插件会自动对 Form 进行注入，对应用开发者无感知。```

**Comment by mattmengSemioe** [comment]
文档上说明了前端怎么去使用，但是并没有说明那个csrfToken 是Plugin 自己写入的cookie还是需要我们自己写入。问题是当我打开某个已经配置好egg-security 的页面时 浏览器cookie中并没有csrfToken,所以导致校验失败。

**Comment by dead-horse** [comment]
先访问页面，会给你的浏览器设置 cookie，提交 POST 请求时带上 cookie 中的 token
。

先去 google 一下理解什么是 CSRF 吧。

**Comment by mattmengSemioe** [comment]
@dead-horse 谢谢解答。是我的某些插件，影响到cookie的写入了。
