### ISSUE TITLE
Please kindly add information about content-type */xml into user's manual.

### ISSUE THREAD

**Issue by tb95959** [eggjs/egg#1104]
I use the eggjs and koajs framework firstly.
It took me lots time to check out a problem(http request content-type is text/xml when weixinpay), because I don't know that koajs does not support text/xml with default configuration.

I finally found a solution in koajs/bodyparser.
```
config.bodyParser = {
    enableTypes:['json','form','text'],
    extendTypes: {
    text: ['text/xml'] 
  }
};
```
I think content-type text/xml is common, for beginner friendly,  please kindly add information about content-type */xml into user's manual.

**Comment by atian25** [comment]
PR is welcome

**Comment by weizeng** [comment]
it worked!

**Comment by weizeng** [comment]
@tb95959  tks
