### ISSUE TITLE
建议先在性能上做文章

### ISSUE THREAD

**Issue by calidion** [eggjs/egg#1105]
我的人品不好如果是事实，那我也认了。
所以攻击我的人品不好就不好吧。
人品不好犯了什么罪吗？
如果没有，攻击我我也不会停止对eggjs的批评或者评论。
何况说话直接并不是犯罪。

### 首先

请先将你的框架性能提高点，再来吹你的框架。

vig的基本性能折损只有1%多点。

koa性能比express高出约20%，而你们的性能比vig低了3倍。

功能上vig有很多egg是没有的。

### 其次

我的文章的目标本来就是是恶心一下你们这些即没有框架能力，又自吹并摸黑别的框架的人。

我人品不好是我的个人问题。

你们东西没有做好到处吹是你们团队的问题。

我对攻击你们中的任何一个人没有兴趣。

但是你们宣传什么express不适合企业，宣传koa是下一代就违反了技术的正确，就跟我有关系。

我至今没有看到koa下一代在那里，难道express不能使用async/await？ 

vig就是基于express的，vig的很多场景都有使用了async/await。

相反的koa的中间件根本不是中间件。那有中间件是递归的？

中间件都是线性的。

同时包括宣传错误的前后端分离概念。

# 再次

你们在性能没有超过vig前，对我的任何侮辱并没有效果。

除了显示你们的低级。

# 最后

我支持所有的开源项目的开展，包括eggjs。

但是别动不动说别的东西不好。

vig的开发本无意贬低任何框架，但是看到eggjs的文档在贬express。

只不过是“以其人之道，还治其人之身”，

事过半年，没想到引来越来越多的攻击，也是出乎我的意料。

但是我并不会后悔，我说的内容虽然有点犀利，并是并没有脱离事实。

希望好做egg，争取做到vig的性能。

目前只有性能能打我的脸。

谢谢。

**Comment by dead-horse** [comment]
有多远滚多远

**Comment by atian25** [comment]
还是那个问题，不要跑到别人的 issue 捣乱，只讨论相关问题。

关于你文章的事，知乎问答已经有了，请移步：https://www.zhihu.com/question/61423389

**Comment by jtyjty99999** [comment]
shame on you
