### ISSUE TITLE
Middleware 中间件能获取app变量吗

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#1106]
* **Node Version**:
v7.8.0
* **Egg Version**:
v1.3.0
* **Plugin Name**:
egg-jwt
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
因为解析jwt需要用到app.jwt 而Middleware 中间件怎么获取app变量

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/objects.html
