### ISSUE TITLE
middleware能传值给controller吗

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#1107]
* **Node Version**:
v7.8.0
* **Egg Version**:
v1.3.0
* **Plugin Name**:

* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
因业务需要每次调用接口都需要查看用户是否已注册，所以将判断逻辑写在了middleware 获取到的user变量想传到controller里使用 这样有用到user变量的controller就不用再查询一次了。
我试着将变量放到next(user)里 但是没有达到实际的效果

**Comment by atian25** [comment]
看下 Koa 的中间件文档先，跟 express 不一样的。

挂载到 ctx 即可。看看 egg-userrole 和 egg-passport

**Comment by jinchaoxiang** [comment]
谢谢 解决了 挂载到 ctx 即可。

**Comment by Leungkingman** [comment]
@jinchaoxiang 您好，请问可以贴一下代码看看吗？这个问题也困扰了我，谢谢

**Comment by iyuq** [comment]
`ctx.state.xxx = 'xxx';`

**Comment by atian25** [comment]
建议用 ctx.locals

发自我的 iPhone
