### ISSUE TITLE
egg 怎么设置会话超时时间  现在太短了 就是访问超时不是httpclient

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#1109]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
请提供更详细的信息或者可复现代码

**Comment by zackCzy** [comment]
因为服务器处理慢 经常出现 用户访问接口time-out 的错误 我想把超时时间设置更久点
