### ISSUE TITLE
schedule 等到 egg-ready 后再启动

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#111]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**: egg-schedule
* **Plugin Version**:
* **Platform**:

现在是等到 agent ready 后触发的，可能 worker 并没有准备好

**Comment by dead-horse** [comment]
egg-ready 是 egg-cluster 发的，单测的时候有坑。mm.app 也需要模拟发 egg-ready 事件了

**Comment by popomore** [comment]
是的

**Comment by jtyjty99999** [comment]
+1

**Comment by atian25** [comment]
@popomore 搞搞 mm ?

**Comment by popomore** [comment]
先搞测试

**Comment by dead-horse** [comment]
我先在内网版本改了再推过来，现在 mm.app 好像本来就不能跑 schedule，测试还是推荐用 app.runSchedule 来跑好了。

**Comment by atian25** [comment]
这个是不是 https://github.com/eggjs/egg-schedule/pull/10 解决了?

**Comment by dead-horse** [comment]
好像没有发版本，我发个版本吧

**Comment by dead-horse** [comment]
2.2.1
