### ISSUE TITLE
因为服务器处理慢 经常出现 用户访问接口time-out 的错误 我想把超时时间设置更久点，但是找不到相关配置

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#1110]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
egg 默认没有超时限制，给出更详细的信息。

**Comment by zackCzy** [comment]
报错504 time-out 那是否是mysql 链接时间？超时

**Comment by ngot** [comment]
请按模版提供必要信息

**Comment by atian25** [comment]
前面挂了 Nginx 了吧
