### ISSUE TITLE
egg-sequelize目录下的model中的associate没有执行

### ISSUE THREAD

**Issue by keepgoingwm** [eggjs/egg#1111]
Node Version: 7.10.0
Egg Version:
Plugin Name: egg-sequelize
Plugin Version: 3.0.1
Platform: windows
Mini Showcase Repository:

问题描述：egg-sequelize目录下的model中的associate没有执行。

问题复现：
![](https://ooo.0o0.ooo/2017/06/26/5950e77ea3d78.png)
在model/目录下的model，associate中console执行了，在model/test目录下相同文件的console没执行，表明associate也没执行

补充：刚开始使用egg框架，还没了解代码，但根据试验的结果，发现egg-sequelize按照egg惯例，对目录是有支持的（将目录层级转为对象层级），所以觉得这里可能有实现上的瑕疵。
另外没在低版本试过，不确定是新引入的

**Comment by iyuq** [comment]
你的Model.associate应该放在return Model里面，详细可以看例子的写法[sequelize-example](https://github.com/eggjs/examples/tree/master/sequelize-example).

**Comment by keepgoingwm** [comment]
@iyuq 
是return了的，截屏没有截全。这里关键的点应该是一个是直接放在model下，一个是放在model下的目录里，两个文件只有console内容不一样，结果是前者有console执行了，后者没执行。

**Comment by iyuq** [comment]
只能直接放model下，不要建子目录了，egg加载是用loader的，只会去加载model下面的。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L49

**Comment by atian25** [comment]
@huacnlee 补一个子目录用例?

**Comment by atian25** [comment]
这个还有什么问题么?

**Comment by huacnlee** [comment]
子目录的方式我们内部暂时还没有用过，可能存在很多问题，我建议你先不要这么做，放外层有没有什么影响。

在这种情况下，你为何不 `app/model/user.js, role.js （或 user_role.js）`，然后得到  `app.model.User, app.model.Role (UserRole)`

**Comment by keepgoingwm** [comment]
@huacnlee 
OK，看了下代码实现，应该是暂不支持，我目前也是按老兄这么用的。
我先close掉它，后续我要有机会改一下，就pull个，后话。
