### ISSUE TITLE
使用RESTful风格定义URL时疑惑

### ISSUE THREAD

**Issue by mattmengSemioe** [eggjs/egg#1112]
当如下定义resources时

     app.resources('search_item', '/searchitem', app.controller.search_item); 
     项目启动报如下错误
     TypeError: Cannot read property 'index' of undefined，并指向的报错位置是我定义上面示例代码。

同理：

      当把controller 下面的文件下划线改成驼峰命名、并如下定义时：
       app.resources('search_item', '/searchitem', app.controller.searchItem);  项目可正常启动。

请问，是项目对文件的命名进行了规范，还是其他问题？望解答。

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/advanced/loader.html#文件加载规则

**Comment by mattmengSemioe** [comment]
@popomore 嗯嗯  谢谢
