### ISSUE TITLE
egg-passport-strategy

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#1113]
passport 之前实现的时候是将每个 strategy 封装成一个插件 https://github.com/eggjs/egg/issues/38 ，但是常用的一些插件需要引入一堆模块，所以打算封装一个 egg-passport-strategy 插件集成常用的第三方服务。

egg-passport 的组装能力比较强，一个插件可以提供一个 strategy 也可以提供多个 strategy。

- [ ] twitter
- [ ] github
- [ ] weibo
- [ ] gitlab
- [ ] google
- [ ] taobao

**Comment by fengmk2** [comment]
淘宝登录 https://www.npmjs.com/package/egg-passport-taobao

**Comment by popomore** [comment]
@fengmk2 没代码？
