### ISSUE TITLE
吐槽一下egg周边的模版引擎

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1117]
开发团队你们好，

所有的`egg-view-*`模版插件，除了`egg-view-ejs`支持`Include`和`Layout`。其它模版插件竟然都不支持，可怕。。。

为什么不是标配😌

**Comment by ngot** [comment]
可以来提PR

**Comment by dead-horse** [comment]
各个模板有自己的特性。

**Comment by atian25** [comment]
nunjucks 插件有支持啊。

我们业务用得不多的插件，更期望社区去支撑。

**Comment by popomore** [comment]
就用 nunjucks 吧，不支持的不要用。

**Comment by xjchenhao** [comment]
你好，`nunjucks`的Include、Layout是需要写helper之类的吗，我看[egg-view-nunjucks](https://github.com/eggjs/egg-view-nunjucks)的`README.md`好像是要自己写helper支持的。

**Comment by whxaxes** [comment]
@xjchenhao 
layout: https://mozilla.github.io/nunjucks/templating.html#extends
include: https://mozilla.github.io/nunjucks/templating.html#include

**Comment by popomore** [comment]
请看 nunjucks 文档

**Comment by xjchenhao** [comment]
嗯嗯，已经用上了。
使用`{% extends "../layout/admin.html" %}`报错，`{% include "../includes/footer.html" %}`却是正常的。路径没问题。
```
//layout/admin.html
<!doctype html>
<html lang="en">
<head>
    <title>123</title>
    <!--{{{block 'style'}}}-->
</head>
<!--<body class="skin-blue sidebar-mini sidebar-collapse">-->
<body class="skin-blue sidebar-mini">
{% block body %}{% endblock %}
</body>
</html>
```

```
//partials/adminHome.html
<!--欢迎进入`后台管理`系统-->
{% extends "../layout/admin.html" %}
{% include "../includes/footer.html" %}
<!--<script src="/pkg/index.js"></script>-->
{% block body %}
456
{% endblock %}
```
错误截图如下：

**Comment by xjchenhao** [comment]
找到问题了，注释导致的。谢谢大家🙏  非常感谢！！
