### ISSUE TITLE
使用pm2部署egg导致log文档输出到pm2

### ISSUE THREAD

**Issue by icezeros** [eggjs/egg#1119]
使用pm2部署egg时，pm2指定log输出目录后，egg原有的log文件不存在了

**Comment by popomore** [comment]
不是很明白

**Comment by popomore** [comment]
使用 pm2 的方法，https://eggjs.org/zh-cn/faq.html#进程管理为什么没有选型-pm2

请给出更多错误信息，有问题再打开

**Comment by David2685** [comment]
你应该是用pm2 log监控日志了，所以没有写入日志文件
