### ISSUE TITLE
logging process warning event

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#112]
https://github.com/nodejs/node/pull/8298/files#diff-9a6f086438a2ce8b714cae31b40e3107R12

**Comment by popomore** [comment]
https://nodejs.org/api/cli.html#cli_trace_warnings

**Comment by popomore** [comment]
这个 warn 就在本地打？

**Comment by popomore** [comment]
这个 node 会默认打的，如果我们打的话需要 `--no-warnings` 阻止 node 打，我们通过监听事件打印。
