### ISSUE TITLE
egg-multipart结合qn库的使用问题

### ISSUE THREAD

**Issue by ogilhinn** [eggjs/egg#1120]
* **Node Version**: 7.10.0
* **Egg Version**: 1.5.0
* **Plugin Name**: egg-multipart
* **Plugin Version**: 1.5.0
* **Platform**: win10

在使用egg-multipart结合大大的[qn](https://github.com/node-modules/qn)这个库上传七牛时，若不指定key就会出现：
```
Cannot read property 'replace' of undefined
```
![image](https://user-images.githubusercontent.com/17724186/27616316-86352ecc-5be1-11e7-8f06-f507fa13fb49.png)

**Comment by popomore** [comment]
代码呢

**Comment by ogilhinn** [comment]
```
const stream = yield ctx.getFileStream();
client.upload(stream, (err, result) => {
    console.log(result);
});
```
---
然后这是OK的：
```
const stream = yield ctx.getFileStream();
client.upload(stream, { key: '' }, (err, result) => {
    console.log(result);
});
```

**Comment by dead-horse** [comment]
这个 issue 提去 qn，不是 egg 的问题。

然后你这里 callback 和 generator function 混用了，有坑。

**Comment by ogilhinn** [comment]
@dead-horse 好的，谢谢大大指教
