### ISSUE TITLE
升级node8.1.2 or node8 后，发现dependencies 中某些包无法使用npm install 安装

### ISSUE THREAD

**Issue by mattmengSemioe** [eggjs/egg#1124]
* **Node Version**:8.1.2
* **Egg Version**:1.5
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

升级node8.1.2 or node8 后，发现dependencies 中某些包无法使用npm install 安装（比如cheerio），使用<node8.0，可以正常使用。

     Error: [egg-core] load file: /Users/xxx/xxx.js, error: Cannot find module 'cheerio'

**Comment by mattmengSemioe** [comment]
手动安装可以成功。

**Comment by dead-horse** [comment]
npm 5 的问题吧，而且 egg 应该也没直接依赖 cheerio

**Comment by ngot** [comment]
应该到这里 https://github.com/npm/npm/issues 提issue

**Comment by mattmengSemioe** [comment]
@dead-horse @ngot 刚才我删掉我们express项目的node_modules，再次使用npm 5安装后，cheerio这个包是存在的，项目正常启动，没有发现少包的情况。npm难道还会根据框架安装依赖？我们是从express迁移到egg的。

**Comment by atian25** [comment]
一般来说可能是安装过程失败，再次安装前需要删除 node_modules 再装

发自我的 iPhone
