### ISSUE TITLE
egg-validate 基础库使用 parameter 做极不妥当

### ISSUE THREAD

**Issue by MinJieLiu** [eggjs/egg#1125]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

`egg-validate` 是用于参数验证。

比如：
```
enable: { type: 'boolean', required: false },
```
一个 `boolean` 类型的字段 ，在参数中几乎都是字符串类型，除非设置 json 格式的 body。就算设置了，表单序列化后的 json 还得显式转换 0,1 => boolean，苦不堪言😡。int 类型也是一样要转换一次。

而 `parameter` 的默认值并不是那么优雅😅

比如：

```
avatar: { type: 'string', max: 255, required: false, allowEmpty: true },
nickname: { type: 'string', max: 20, required: false, allowEmpty: true },
introduction: { type: 'string', max: 255, required: false, allowEmpty: true },
```
不必填的字段手动设置 `required: false` 还要设置 `allowEmpty: true`。
在一个表单中，必填字段也就那么几个，结果要写很多规则去覆盖默认值😡

综合来看，为什么 egg-validate 官方不自己单独造个方便的验证的轮子呢？

**Comment by dead-horse** [comment]
你可以自行编写一个 validate 库的，egg-validate 并没有和 egg 绑死。

**Comment by popomore** [comment]
看下 parameter 作者就知道为什么了

**Comment by MinJieLiu** [comment]
😰
