### ISSUE TITLE
单元测试controller的时候，httpRequest请求接口需要鉴权，怎么处理

### ISSUE THREAD

**Issue by liuyu322** [eggjs/egg#1129]
单元测试controller的时候，httpRequest请求需要鉴权处理，针对这种鉴权的单元测试，需要怎么处理？？

**Comment by popomore** [comment]
鉴权用的什么，可以 mock 下

**Comment by jtyjty99999** [comment]
如果请求能控制，你就加个参数单独为了单测，检测到就跳过鉴权就好了，上线时去掉或配置到dev，如果不能控制，就看鉴权鉴的哪块然后自己mock。。

**Comment by atian25** [comment]
如我们的 egg-mock 就支持 mockUser 来模拟
