### ISSUE TITLE
修改了文件 自动重启了 ，页面打不开了，一直在等待，卡住了。

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#1130]
* Node Version :v6.10.2
* Egg Version :1.5.0
* Plugin Name:
* Plugin Version:
* Platform :win10
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/26592729/27719481-29221f74-5d85-11e7-8534-ecbb3f62b811.png)
![image](https://user-images.githubusercontent.com/26592729/27719842-c3f03e62-5d87-11e7-8a3c-faae50b172de.png)
新建的一个项目，没有动什么只是改了下hi, egg3,
环境 win10
node v6.10.2

**Comment by Ailein** [comment]
帮忙解决下，谢谢

**Comment by okoala** [comment]
@Ailein  提供最小化的重新代码仓库

**Comment by Ailein** [comment]
@okoala [https://github.com/Ailein/egg_win_init_bug1](url) 我是今天早上egg-init 的一个列子，npm run dev 修改home.js 后自动重启，然后刷新页面 就 卡住不动了，是不是window 电脑就会有这个问题？

**Comment by okoala** [comment]
@Ailein  我在 win10 下用了 Node v6.10.2 和 v8.1.3 两个版本都无法重现你的问题，你删除 node_modules 目录，然后重新安装依赖后看看~

**Comment by Ailein** [comment]
感谢你的回复，问题还是一样，我每次安装任何插件 都会有报一个错，想请教下大神 这个是什么问题？
![image](https://user-images.githubusercontent.com/26592729/27723355-43c68e36-5d9f-11e7-868b-3b8a9ee97810.png)

**Comment by okoala** [comment]
@Ailein  你换个浏览器看看，是不是什么插件把请求给拦截了~

**Comment by atian25** [comment]
不要用浏览器， curl 看看
