### ISSUE TITLE
增加 config meta 文件

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#1132]
生成 `run/agent_config_meta.json` 文件，描述配置的来源

```json
{
  "config": {
    "env": "/path/to/config/config.default.js"
  }
}
```

**Comment by atian25** [comment]
哈哈，我今天刚才也在想这个，有点类似 fis3 的 inspect 功能。

https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/config.js#L65

**Comment by atian25** [comment]
原来那个 dump 里面的 config 和 plugin 要不要分两个文件? 之前经常遇到让提问者找某个插件配置，然后对方给了 plugin 节点的

**Comment by popomore** [comment]
估计要 dump 一堆了，哈哈。其实 config loader 完和 ready 的最好也是两份，这样知道哪些是动态修改的。

**Comment by atian25** [comment]
哈哈，有没有一个加强版的 extend 轮子，允许配置钩子，精确跟踪合并过程。

**Comment by popomore** [comment]
这个可以看 debug，信息很详细
