### ISSUE TITLE
 egg-sequelize 文档错误 examples/sequelize-example 示例错误

### ISSUE THREAD

**Issue by kotot** [eggjs/egg#1133]
* **Node Version**: 6.9.2
* **Egg Version**: 3.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.0.1
* **Platform**:
* **Mini Showcase Repository**:
 
 1. egg-sequelize 文档错误 examples/sequelize-example 示例错误
 1. egg-sequelize 中 model.associate  = function () 应该为  model.associate  = function * ()

**Comment by popomore** [comment]
直接提 PR 吧

**Comment by iyuq** [comment]
@kotot 兄弟，没用generator为啥要用function *啊，讲道理define model和define associate都是同步的。

**Comment by kotot** [comment]
确实，是我这边使用错了
