### ISSUE TITLE
设置cookie和session无效

### ISSUE THREAD

**Issue by accelerator-feng** [eggjs/egg#1136]
* **Node Version**: v8.1.2
* **Egg Version**: 1.5.0

前端dva在localhost:8000，roadhog中配置将请求转发到7001端口，egg在7001端口 。
在egg中设置cookie，浏览器控制台中 response cookie中显示设置了cookie，响应头中也有set-cookie。
但是浏览器中查不到该cookie。session也是，登录成功后设置了session，但之后再服务端读取不到session。
不过直接访问7001，8000端口的api，cookie就设置成功了。前端发请求，cookie设置就不成功
想知道这是哪里出了问题？

**Comment by liujinyang1994** [comment]
请问，原因是什么？

**Comment by accelerator-feng** [comment]
fetch里有个credentials字段要设置成include
