### ISSUE TITLE
egg如何支持ssl

### ISSUE THREAD

**Issue by kingcent** [eggjs/egg#1141]
egg如何支持ssl请求

**Comment by atian25** [comment]
在启动的 startCluster 那里支持传递参数进去，详见 https://github.com/eggjs/egg-cluster#options

但一般推荐是在前面 nginx 等来做 https 的卸载。

**Comment by anchengjian** [comment]
那本地开发，比如 webRtc 的调试等，需要https，如何优雅便利的安装环境呢？

本地再搭一套 nginx 感觉有点笨重，加入有其他人进入项目时环境安装配置也比较麻烦。

求支招，谢谢。

**Comment by ChaseChan** [comment]
@anchengjian +1

**Comment by atian25** [comment]
> 那本地开发，比如 webRtc 的调试等，需要https，如何优雅便利的安装环境呢？
> 
> 本地再搭一套 nginx 感觉有点笨重，加入有其他人进入项目时环境安装配置也比较麻烦。
> 
> 求支招，谢谢。

docker 启动个 Nginx 很简单吧，一句话
