### ISSUE TITLE
egg-sequelize 可以将 sequelize 的依赖设置 peerDependencies 吗

### ISSUE THREAD

**Issue by MinJieLiu** [eggjs/egg#1142]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

egg-sequelize 可以将 sequelize 的依赖设置 peerDependencies 吗

这样 可以用最新版本的 sequelize 了，而不用等待 egg-sequelize 更新😊

**Comment by iyuq** [comment]
本来就会装最新版的。`package.json` 里面 `"sequelize": "^4.1.0"` 版本号是带`^`号的，会安装大于4.1 且5.0的最新版本。

**Comment by luicfer** [comment]
ls正解，而且npm@3之后不推荐用peerDependencies

**Comment by MinJieLiu** [comment]
额，学习了😂
