### ISSUE TITLE
如何在view 中读取config中的值

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#1143]

**Comment by ngot** [comment]
https://eggjs.org/zh-cn/core/view.html#locals 可以把变量放在 locals 上，或者直接传进模板

**Comment by atian25** [comment]
- 如果是启动后就不会变的，可以放到 app.locals。
- 如果是跟请求相关的，可以在 middleware 里面挂到 ctx.locals 上。
- 如果只是 Controller 里面的某个分支的，可以 `render(tpl, locals)` 第二个参数传入.(也可以直接 `{{ ctx.app.config.xxx }}` 但不推荐)
