### ISSUE TITLE
关于涉及到messenger的单元测试问题

### ISSUE THREAD

**Issue by danielxiaowxx** [eggjs/egg#1149]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

[ipc-实战](https://eggjs.org/zh-cn/core/cluster-and-ipc.html#ipc-实战)中的例子，如果我要对`app/schedule/pull_refresh.js`进行单元测试如何进行？测试用例大概是“需要更新缓存且正确更新到”

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/basics/schedule.html#手动执行定时任务

**Comment by danielxiaowxx** [comment]
可能没表达清楚，是因为用到了messenger，然后单元测试的时候，sentToApp不会触发on的事件处理，应该是没用cluster启动的原因吧，但如果用mm.cluster，又无法访问application的API

**Comment by danielxiaowxx** [comment]
我用emit就可以，如果messenger在单实例模式下也可以正常工作应该就没问题了

**Comment by atian25** [comment]
`mm.cluster，又无法访问application的API` 怎么个无法访问？

贴点伪代码讨论下？

**Comment by danielxiaowxx** [comment]
```
describe('test/app/schedule/xxx.test.js', () => {
  let app;

  before(() => {
    app = mm.cluster(); 
    return app.ready(); 
  });
  afterEach(mm.restore);
  after(() => app.close());

  it('say something', async function () {

    app.config // undefined

  });

});
```

**Comment by danielxiaowxx** [comment]
undefined是合理的，因为拿到的是cluster，肯定不是单个的app实例

**Comment by danielxiaowxx** [comment]
只是这样就不方便单元测试了，如果`sendToApp`等方法在单实例下（即mm.app()）也可正常工作，这样单元测试就可覆盖这些场景了

**Comment by danielxiaowxx** [comment]
看了sendmessage的源码，找到方法了，加这个`process.env.SENDMESSAGE_ONE_PROCESS`就可以在单进程下工作了

**Comment by danielxiaowxx** [comment]
看了sendmessage的源码，找到方法了，加这个process.env.SENDMESSAGE_ONE_PROCESS就可以在单进程下工作了

**Comment by atian25** [comment]
@danielxiaowxx 给你提个思路：
- 写 fixtures 的时候，加个 Controller，把 app.config 吐出来
- 通过 `app.httpRequest` 去 assert
