### ISSUE TITLE
env 在 local 或 unittest下，会抛出要求config配置keys的异常

### ISSUE THREAD

**Issue by ysstech** [eggjs/egg#1160]
Application.js 
line 171
  /**
   * secret key for Application
   * @member {String} Application#keys
   */
  get keys() {
    if (!this[KEYS]) {
      if (!this.config.keys) {
        **if (this.config.env === 'local' || this.config.env === 'unittest') {**
          const configPath = path.join(this.config.baseDir, 'config/config.default.js');
          console.error('Cookie need secret key to sign and encrypt.');
          console.error('Please add `config.keys` in %s', configPath);
        **}
        throw new Error('Please set config.keys first');** 
      }

      this[KEYS] = this.config.keys.split(',').map(s => s.trim());
    }
    return this[KEYS];
  }

是否应该修正为：

**if (this.config.env === 'local' || this.config.env === 'unittest') {**
          const configPath = path.join(this.config.baseDir, 'config/config.default.js');
          console.warn('Cookie need secret key to sign and encrypt.');
          console.warn('Please add `config.keys` in %s', configPath);
        **} else {
        throw new Error('Please set config.keys first');
        }**

**Comment by popomore** [comment]
就是要求你配

**Comment by LuoHaoAt2017** [comment]
exports.keys = (appInfo: EggAppInfo) => appInfo.name + "_1650157030530_4029"
已经配置了，还是报错 this.config.keys.split is not a function
