### ISSUE TITLE
egg-bin --node-options

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1161]
![image](https://user-images.githubusercontent.com/227713/27893768-655dd550-623a-11e7-9c39-d7980c5336a5.png)

- 支持 `egg-bin --node-options='--prof --xxx'`，取值丢给 execArgv
- 原 `egg-bin --debug` 不变，保持兼容，冲突时以 --debug 为准

**Comment by atian25** [comment]
https://medium.com/the-node-js-collection/node-options-has-landed-in-8-x-5fba57af703d

**Comment by wZi** [comment]
请问现在这个方法还可行吗? 试了之后没用. 另外 egg-scripts 是否也支持该做法?
