### ISSUE TITLE
webstorm断点调试后，请求被拒绝

### ISSUE THREAD

**Issue by David2685** [eggjs/egg#1164]
1.webStrom 配置

<img width="787" alt="2017-07-07 11 04 56" src="https://user-images.githubusercontent.com/7779371/27941756-e75d86a2-6304-11e7-95f1-a1112f99f606.png">

2.启动应用：点击下图右侧的绿色bug按钮

<img width="139" alt="2017-07-07 11 05 41" src="https://user-images.githubusercontent.com/7779371/27941795-0f9d4936-6305-11e7-85c9-8fd532b2dde8.png">

3.启动后控制台打印内容

<img width="642" alt="2017-07-07 11 12 20" src="https://user-images.githubusercontent.com/7779371/27941813-2dbecaac-6305-11e7-8c0a-c829e60365aa.png">

4.$open http://127.0.0.1:7001

5.请求失败

![2017-07-07 11 14 19](https://user-images.githubusercontent.com/7779371/27941916-c06c787c-6305-11e7-93af-cb6c62d8a5c1.png)

想问一下，我的配置有错吗？

**Comment by atian25** [comment]
Node 版本和 WebStorm 版本多少？ 感觉还是 WebStorm 的那个 Bug，启动到 agent 就卡住了，没启动下去。

**Comment by David2685** [comment]
我下了一个最新版本定webstorm 2017.1.4 Node版本为8.0.0。还是有问题啊

用什么版本的webstorm和Node可以在webstrom里断点调试呢？
![2017-07-11 8 38 13](https://user-images.githubusercontent.com/7779371/28046251-fbb04208-6614-11e7-9055-ef002684f021.png)

**Comment by atian25** [comment]
刚试了下，WebStorm 在 Node 8.x 下的 `$NODE_DEBUG_OPTION` 还是 `--debug-brk=65023 --expose_debug_as=v8debug` ，这个参数 Node 8.x 不支持，换回 6.x 就可以。

是 WebStorm 的 Bug 了。

**Comment by atian25** [comment]
https://youtrack.jetbrains.com/issue/WEB-27123

看来要等 WebStorm 2017.2 了

**Comment by David2685** [comment]
非常感谢，换到Node 6.x可以断点调试了，这样设置"start": "node $NODE_DEBUG_OPTION index.js",是可以的。egg-bin 命令怎么用这个$NODE_DEBUG_OPTION呢？

**Comment by atian25** [comment]
文档不是有写了么

`"debug": "egg-bin dev $NODE_DEBUG_OPTION"`

**Comment by David2685** [comment]
thanks ,找到了

**Comment by atian25** [comment]
最新的 2017.2 已经可以支持 node 8 断点了
