### ISSUE TITLE
router  怎么设置文件上传的呢？没找到说明！

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#1168]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by zackCzy** [comment]
application/octet-stream;tt-data=a
这个方式的

**Comment by atian25** [comment]
- https://eggjs.org/zh-cn/basics/controller.html#获取上传的文件
- https://github.com/eggjs/examples/tree/master/multipart
