### ISSUE TITLE
linux上EGG_SERVER_ENV=prod npm start 启动后，ctrl+c就关闭了

### ISSUE THREAD

**Issue by barretzhi** [eggjs/egg#1170]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
看下文档，部署章节， nohup

发自我的 iPhone

**Comment by popomore** [comment]
要始终 nohup

**Comment by barretzhi** [comment]
使用了还是不行 ctrl + c master进程就没有了

**Comment by ngot** [comment]
https://www.google.com.hk/search?safe=strict&site=&source=hp&ei=VaZfWbHtOIaK8wXvuY6oDQ&q=linux+nohup&oq=linux+nohup&gs_l=mobile-gws-hp.3..0l5.986.9983.0.10219.20.14.6.0.0.0.953.5263.2-4j6j1j1j1.13.0....0...1.1.64.mobile-gws-hp..2.18.4396...5j41j0i131k1j0i12k1j0i10k1j0i30k1.hnxoS77uG5k  建议先学习一下linux进程启动原理

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/deployment.html#后台运行

**Comment by barretzhi** [comment]
@atian25 是按照你们说的启动的，但是当前的shell窗口关闭了之后进程又没有了，难道我这样不对吗？
<img width="850" alt="22" src="https://user-images.githubusercontent.com/10612276/27981048-543189aa-63b8-11e7-8529-ff8b633aac3b.png">  请求指导！
