### ISSUE TITLE
路由配置

### ISSUE THREAD

**Issue by ReconcileMySelf** [eggjs/egg#1172]
在 eggjs 中，是否，我每在 controller 中增加一个函数，都得到  router.js 去配置一个路由呢？

**Comment by atian25** [comment]
当然啦。因为目前并没有看到很通用的自动匹配规范。如果你们自己的业务有，写个小插件即可

发自我的 iPhone

**Comment by ReconcileMySelf** [comment]
这样的话，依次配置，好麻烦，如果我有10多个接口，就不太好了。express的router就挺好的啊。

**Comment by atian25** [comment]
express 内建也是没有自动路由的，你是用第三方中间件了吧。
如果你有固定的匹配规则，写一个插件就可以了。

发自我的 iPhone

**Comment by catalsdevelop** [comment]
egg.js里面有一个快速路由的设置， 参考这里。https://eggjs.org/zh-cn/basics/router.html#restful-风格的-url-定义

**Comment by ReconcileMySelf** [comment]
OK, 好的, 谢谢；@catalsdevelop
