### ISSUE TITLE
请求视频文件异常---egg-static

### ISSUE THREAD

**Issue by lyqiai** [eggjs/egg#1173]
2017-07-10 09:58:32,617 ERROR 6992 [-/undefined/-/32ms GET /public/video/1.mp4] nodejs.ECONNRESETError: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:607:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
headerSent: true
name: 'ECONNRESETError'
pid: 6992
hostname: PC201706181112

**Comment by andysjt** [comment]
我也碰到了，求解决方法

**Comment by dead-horse** [comment]
文件大小是多少？可能是客户端终端了请求，导致链接断开，报出了这个错误

**Comment by lyqiai** [comment]
配置下限值就好了
config.multipart = {
    fileSize: '500mb',
    fileExtensions: [ '.msi' ],
};

**Comment by xiaocjin** [comment]
同样遇到这个问题，求解决方法
我只是在chrome中请求一个不大的音频或者视频文件
@lyqiai multipart是上传组件，和static会又关联？
@dead-horse 在express中请求都OK，但是egg中就报错，请问该怎么配置？

**Comment by dead-horse** [comment]
请提供详细错误信息

**Comment by atian25** [comment]
跟这个类似？ https://github.com/eggjs/egg-static/pull/13

**Comment by pxim** [comment]
遇到同样的问题，
![image](https://user-images.githubusercontent.com/5111701/185350378-1a08006c-7647-4168-bdc0-1d7fd1274676.png)

加 
![image](https://user-images.githubusercontent.com/5111701/185350255-c90854ca-a5d4-46d2-802e-4ea5e01a611f.png)
没有效果
