### ISSUE TITLE
如何在app.beforeStart 执行完才执行schedule中的immediate为true的任务呢？ 

### ISSUE THREAD

**Issue by Micjoyce** [eggjs/egg#1175]
任务需求为： 我需要在app.beforeStart中执行一些初始化的动作， 并且我的schedule中的任务需要依赖我beforeStart执行完挂载到app上面的一些数据。

现在的问题是beforeStart 的任务还没执行完， immediate为true的schedule已经开始执行了
<img width="763" alt="82124b37-1393-4514-86ad-679119d51d1f" src="https://user-images.githubusercontent.com/4250838/28005116-7d4a00a0-657b-11e7-8408-bdff17d25977.png">

**Comment by popomore** [comment]
你都用了 immediate 了说明他会立即执行，你可以把功能抽象成一个 service，beforeStart 调用，schedule 也可以调用。

**Comment by atian25** [comment]
从语义上来讲，start suc 后再 schedule 好点。

看了下代码， `agent.messenger.once('egg-ready', startSchedule);` 

egg-cluster 不是 beforeStart 完成后才发送 egg-ready 的么？

**Comment by atian25** [comment]
我刚试了下，是会等待的，是不是你的 `beforeStart` 写法有问题，没有 `yield`？

![image](https://user-images.githubusercontent.com/227713/28010813-b1fa4190-6592-11e7-9acd-3411b542f8f7.png)

```js
// app.js
  app.beforeStart(function* () {
    console.log('####### sleep');
    yield sleep(3000);
    console.log('####### wake up');
  });

// app/schedule/test.js
exports.schedule = {
  type: 'worker',
  interval: 3000,
  immediate: true,
};

exports.task = function* (ctx) {
  console.log('##### task');
};
```

**Comment by Micjoyce** [comment]
@atian25  @popomore 谢谢回答
@atian25 我确定我已经添加yield了，并且我用你的代码来实现尝试了一下，还是会先执行schedule中的代码
app.js
```javascript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

module.exports = app => {
  app.beforeStart(function* () {
    console.log('####### sleep');
    yield sleep(3000);
    console.log('####### wake up');
  });
};

```

// schedule 中的代码

```javascript
'use strict';

module.exports = {
  schedule: {
    // 周一至周五每天8-18点没5秒钟执行一次
    cron: '*/5 */10 8-18 * * 1-5',
    type: 'worker', 
    immediate: true,
  },
  // task 是真正定时任务执行时被运行的函数，第一个参数是一个匿名的 Context 实例
  * task(ctx) {
    console.log('------schedule-----');
  },
};
```

运行结果：
`
2017-07-10 17:39:03,687 INFO 27004 [master] egg version 1.6.0
2017-07-10 17:39:04,087 INFO 27004 [master] agent_worker#1:27005 started (393ms)
####### sleep
2017-07-10 17:39:04,601 INFO 27004 [master] egg started on http://127.0.0.1:7001 (912ms)
------schedule-----
####### wake up
`

dependencies
`
 "dependencies": {
    "egg": "^1.2.1"
  },
`

**Comment by atian25** [comment]
是我看错了，得再看看源码。

**Comment by Micjoyce** [comment]
谢谢 那我close这个issue了
