### ISSUE TITLE
egg-socket.io 怎么保存和分辨特定客户端的？

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#1176]
有没有例子啊？

**Comment by ngot** [comment]
Node Version:
Egg Version:
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:

?

问题，看不懂，请描述清晰一些

**Comment by liuliangjia** [comment]
io.sockets.on('connection', function (socket) {
  socket.on('msg', function(msg){
     var data = {username:socket.name,time:getCurrTime(),msg:msg};
     socket.emit('msg',data);
     socket.broadcast.emit('msg',data);
  });
  socket.on('login', function(username){
     socket.name = username;
     var data = {username:'SYSTEM',time:getCurrTime(),msg:'welcome '+socket.name+' in...'};
     socket.broadcast.emit('msg',data);
     socket.emit('msg',data);
  });

类似的代码写在什么地方啊，只用过node的socket.io，请指教。

**Comment by liuliangjia** [comment]
这个插件是不是一定得配置redis？

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/blob/master/README.zh_CN.md
