### ISSUE TITLE
agent里访问app对象

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1177]
* **node8.1**:
* **egg1.6**:
我想在agent里访问app对象

**Comment by atian25** [comment]
目的是？

发自我的 iPhone

**Comment by acodercat** [comment]
我业务逻辑是这样的，需要一个进程用socket监听来自传感器的数据，传感器会定时发数据过来，然后收到以后我再用app.io.sockets发给客户端，我现在功能实现了，但是我是写在app.js的beforeStart里面的，想到一个进程怕扛不住，所以想改成用agent

**Comment by acodercat** [comment]
请问怎么设计最优，感谢！

**Comment by popomore** [comment]
你得在 agent 实现，进程间无法共享的

**Comment by acodercat** [comment]
那我客户端的websocketr也写在agent里面，然后就不用egg-socket了直接用socke.io吗

**Comment by popomore** [comment]
这个传感器只有集群一个监听吗？我感觉还是要实现在 app 里面。

**Comment by acodercat** [comment]
传感器的用的net模块做的一个监听，客户端用的egg-socket.IO.传感器只有一个监听。

**Comment by acodercat** [comment]
请问怎么设计呢

**Comment by ngot** [comment]
agent.js
```js
module.exports = app => {
    
};
```
