### ISSUE TITLE
should warning sendMessage to app before egg-ready

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#118]
![image](https://cloud.githubusercontent.com/assets/227713/19344504/06fe3da4-916d-11e6-9e53-77f7471824fb.png)

![image](https://cloud.githubusercontent.com/assets/227713/19344509/0ab613a4-916d-11e6-9420-d8897268ea19.png)

**Comment by popomore** [comment]
队列那个太复杂，之前讨论过不做

如果只是 warn 的话，需要 wrap 下 agent 的 messenger，不用改 cluster
