### ISSUE TITLE
egg-socket.io

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#1180]
网页A显示二维码，网页B有一个按钮，点一下请求服务器端的以下controller：
module.exports = app => {
    class SigninController extends app.Controller {
        * index() {
            console.log('signincontroller');        //这里会输出
            this.app.io.sockets.emit('res','success');            //这个调用好像没起效果，原本想通知网页A的二维码应该变换下一线了。
            this.ctx.body = 'success';
        }
    }
    return SigninController;
};

就是一个普通的egg的controller，有没有办法利用socket.io通知所有连接着的客户端有消息更新？

**Comment by ngot** [comment]
请仔细阅读：https://github.com/eggjs/egg/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by liuliangjia** [comment]
Node Version: 8.1.0
Egg Version: 1.4.0
Plugin Name: egg-socket.io
Plugin Version:2.0.2
Platform:windows
Mini Showcase Repository:

网页A显示二维码，网页B有一个按钮，点一下请求服务器端的以下controller：
module.exports = app => {
class SigninController extends app.Controller {
* index() {
console.log('signincontroller'); //这里会输出
this.app.io.sockets.emit('res','success'); //这个调用好像没起效果，原本想通知网页A的二维码应该变换下一线了。
this.ctx.body = 'success';
}
}
return SigninController;
};

就是一个普通的egg的controller，有没有办法利用socket.io通知所有连接着的客户端有消息更新？

**Comment by buzai** [comment]
@liuliangjia 请问你解决了这个问题么

**Comment by liuliangjia** [comment]
解决了。

**Comment by liuliangjia** [comment]
'use strict';

module.exports = app => {
    class SignInController extends app.Controller {
        async index() {
            app.io.sockets.emit('nextSignIn','signIn');
            this.ctx.body = 'success';
        }
    }
    return SignInController;
};

**Comment by buzai** [comment]
@liuliangjia 谢谢了哈
