### ISSUE TITLE
ctx.getFileStream()获取文件流出错2

### ISSUE THREAD

**Issue by michaelouyang777** [eggjs/egg#1181]
目前我想上传一个文件到egg的服务器上
（1）
使用了FormData对象，包裹了一个blob（这个不是通过input type=“file”获取而来）
这是通过传入文件路径，得到fileEntry，再通过file方法获取一个file对象
window.resolveLocalFileSystemURL(imgUri, function success(fileEntry) {
	fileEntry.file(function(imageFile){
		const formData = new FormData();
		formData.append("image", imageFile);
		// 上传formData的代码忽略...
	}
}
使用post请求，发送formData 给egg服务器，egg使用ctx.getFileStream()获取文件流，出现了Can’t found upload file这个错误，这是什么问题？

（2）
如果我是使用input type=“file”拿到的file对象，放入如下代码：
		const formData = new FormData();
		formData.append("image", file);
		// 上传formData的代码忽略...
是可以通过ctx.getFileStream()获取文件流（但是我们不采用input type=“file”的方式获取文件）

另外我对这个（1）中的imageFile对象和（2）从input type="file"中拿到的file对象做了类型判断
这是（1）的判断内容：
        console.log(imageFile instanceof File)			        //true
       	console.log(imageFile instanceof Blob)			//false
      	console.log(imageFile.constructor === File)		//true
     	console.log(imageFile.constructor === Blob)		//false
这是（2）的判断内容：
	console.log(file instanceof File)		                        //false
	console.log(file instanceof Blob)		                        //true
	console.log(file.constructor === File)	                //false
	console.log(file.constructor === Blob)	                //false
我感到迷惑了，明明都是file对象，为什么类型会不同。是不是这个原因导致了egg的ctx.getFileStream()获取不到文件流？？
该如何破解（1）中上传的文件可以在egg中获取？谢谢大神支招，感激万分

**Comment by dead-horse** [comment]
这个是前端的问题，服务端只关心上传的格式是否正确，需要在前端确保上传的数据及格式正确。

可以参考： https://github.com/eggjs/examples/blob/master/multipart/app/controller/client.js
