### ISSUE TITLE
app.io.sockets.emit 有没有这种写法？

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#1183]
Node Version: v8.0
Egg Version: v1.2.1
Plugin Name: egg-socket.io
Plugin Version: v1.2.2
Platform: windows
Mini Showcase Repository:

file: app/io/middleware/auth.js
module.exports = app => {
    return function* (next) {
        this.socket.emit('res', 'connected!');
        this.socket.emit('res', '1111111111111');         //这一条客户端可以接收
        app.io.sockets.emit('res','2222222222222');    //这一条客户端无法接收，我想向所有已连接的客户端发送消息。
    };
};

**Comment by ngot** [comment]
请仔细阅读：https://github.com/eggjs/egg/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Mrlilili** [comment]
> 请仔细阅读：https://github.com/eggjs/egg/blob/master/.github/ISSUE_TEMPLATE.md

这个文档404了...
