### ISSUE TITLE
egg-redis 在 Twemproxy 集群下的错误

### ISSUE THREAD

**Issue by hyj1991** [eggjs/egg#1185]
现象：公司 Redis 集群采用 Twemproxy 部署，并且 **禁止了 SYS 级别的命令查询**，此时采用 egg-redis 连接会出现如下错误信息：

```
2017-07-13 10:04:34,925 WARN 41955 [egg:core:ready_timeout] 10 seconds later/Users/wangjiawei/Sites/FUHSI/stable/node_modules/egg-redis/lib/redis.js:48:7 was still unable to finish.
```

经过初步排查，将 egg-redis 入参 enableReadyCheck 置为 false 后，依旧错误，继续排查代码发现是 egg-redis 中的 ```app.beforeStart``` 中的钩子函数手动调用了 ```ioredis.time()```，而这个命令属于系统命令，因此同样会被 Twemproxy 集群拒绝掉，所以采用 egg-redis 时永远无法连接上 Twemproxy 集群

建议: ```app.beforeStart``` 中查询连接成功的命令采用更加常规一些的非系统级别命令：

即非 [Server（服务器）](http://redisdoc.com/server/index.html) 中提到的这些命令

**Comment by jtyjty99999** [comment]
收到，我改一个命令吧

**Comment by hyj1991** [comment]
@jtyjty99999 话说如果不改命令，但是将 beforeStart 里面钩子函数改成根据配置：

**默认开启检查，但是也可以根据入参不检查**

这样子是不是更好一些

**Comment by jtyjty99999** [comment]
@hyj1991 beforeStart里这个检查是查应用所有依赖是否ok的，需要不能被绕过，不然线上可能会有风险

**Comment by hyj1991** [comment]
@jtyjty99999 也是，那就只能改一个不在 Server 列表里面的检查连接成功的命令了，说实话，我也不知道这个问题是不是所有使用 Twemproxy 集群的公司都会遇到，如果只是个例，那我这边自己写一个插件使用就行了。

毕竟不在 Server 列表里面的命令用来做检查，会有一点奇怪

**Comment by jtyjty99999** [comment]
@hyj1991 我改成info了

**Comment by jtyjty99999** [comment]
@hyj1991 等发好了我通知你你再验证下

**Comment by hyj1991** [comment]
@jtyjty99999 ok，麻烦啦

**Comment by jtyjty99999** [comment]
@hyj1991 + egg-redis@1.0.2 试试

**Comment by MunchTZB** [comment]
@jtyjty99999 hi，这个改成了info还是会出现类似的问题，因为info也是系统级别命令之一，能否支持enableReadyCheck来判断是否需要在beforeStart里进行判断。

**Comment by hyj1991** [comment]
@MunchTZB 这种情况不如自己基于 ioredis 封装一个插件吧... 其实当时这个问题也没解决，后来我自己封装了一个
