### ISSUE TITLE
egg-sequelize中怎么使用raw query

### ISSUE THREAD

**Issue by qiaopeng55** [eggjs/egg#1186]
egg-sequelize中怎么使用raw query ？

sequelize本身支持raw query，但是egg-sequelize文档中没有介绍怎么使用raw-queries
http://docs.sequelizejs.com/manual/tutorial/raw-queries.html

**Comment by iyuq** [comment]
直接看sequelize文档用就好了，egg-sequelize只是把sequelize作成了一个插件，并不需要把sequelize的所有文档和用法重复一般

**Comment by darkestinblack** [comment]
ctx.model.query
不知道为啥query函数挂载在ctx.model而不是app.Sequlize;
