### ISSUE TITLE
上传问题

### ISSUE THREAD

**Issue by lyqiai** [eggjs/egg#1187]
页面表单设置enctype="multipart/form-data"，使用await ctx.getFileStream()无法获取input typer=file后面的表单内容，使用ctx.request.body得到的也是个空对象。怎么拿到表单的完整内容？

**Comment by jtyjty99999** [comment]
要不看下这个例子 https://github.com/eggjs/examples/tree/master/multipart

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/basics/controller.html#获取上传的文件
