### ISSUE TITLE
如何遍历session和使session失效？

### ISSUE THREAD

**Issue by devrsi0n** [eggjs/egg#1192]
目前我有一个需求：同一个账号在二次登录的情况下让前一个登录失效。我的想法是在判断是第二次登录的时候遍历session，找到第一次登录的session，然后让他失效。请问如何遍历整个应用的session然后让它失效？

**Comment by dead-horse** [comment]
不应该这样做，请求量大了就死了。换其他的思路来实现：

例如在数据库里面保存当前登录用的 ip 或者浏览器的 user-agent，用户访问时再进行判断。

**Comment by devrsi0n** [comment]
@dead-horse 谢谢～
