### ISSUE TITLE
egg-cluster模块退出进程疑问

### ISSUE THREAD

**Issue by OnedayLiu** [eggjs/egg#1195]
egg-cluster模块有些问题不太明白
1. app worker是cluster fork出来的，master退出后就自动退出了吧，为什么还需要手动调用killAppWorkers方法？
2. agent worker不是已经require了graceful-process模块了吗，master退出后就自动退出了吧，为什么还需要手动调用killAgentWorker方法？

![image](https://user-images.githubusercontent.com/7758413/28247377-9c9252c4-6a61-11e7-852c-4d9135398d83.png)

**Comment by popomore** [comment]
Close 方法只有在测试用到

**Comment by OnedayLiu** [comment]
是为了方便debug？

**Comment by dead-horse** [comment]
@OnedayLiu 父进程退出有时候不能确保子进程一定退出，测试的时候容易造成特别多孤儿进程导致机器变卡
