### ISSUE TITLE
渲染字符串模板时图片src属性丢失

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#1198]
我用的是官方推荐的Nunjucks
在后台用富文本编辑器编辑内容时，上传图片的src会转换成base64。在富文本编辑器上显示正常的。但是在前台显示的时候img标签的所有属性都丢失了。请问这个要怎么解决？

后台富文本是这样的：
![111](https://user-images.githubusercontent.com/16955472/28249688-297faa6c-6a8d-11e7-8544-cc6e791776a1.png)
![222](https://user-images.githubusercontent.com/16955472/28249698-5e3b5ba2-6a8d-11e7-8e97-fffd65dd79d3.png)

前台显示是这样的：
![333](https://user-images.githubusercontent.com/16955472/28249702-6e7ed5d4-6a8d-11e7-8730-10b7f1a8b4ec.png)
![444](https://user-images.githubusercontent.com/16955472/28249731-ec000708-6a8d-11e7-8155-e153a62cd184.png)

代码如下：
![555](https://user-images.githubusercontent.com/16955472/28249732-ec01f5ae-6a8d-11e7-8f52-2bb367d7ce4a.png)

**Comment by jtyjty99999** [comment]
helper.shtml会过滤非白名单的属性，可以设置一下

**Comment by Leungkingman** [comment]
@jtyjty99999 您好，请问一下白名单属性应该在哪里设置呢？在官方文档上看到这个 https://github.com/leizongmin/js-xss/blob/master/lib/default.js ，不知道是不是框架默认的配置，如果是的话，我是没有修改过的，因为我根本不知道在哪里配置；如果不是的话应该怎么、在哪里配置呢？谢谢

**Comment by jtyjty99999** [comment]
@Leungkingman helper.shtml会过滤 base64的url（可能有安全风险），所以如果你确定这段安全，输出的时候使用  `{{information | safe }}`, 如果不确定的话，把url换成http/https 方式的

**Comment by Leungkingman** [comment]
@jtyjty99999 确实可以了，非常感谢。
