### ISSUE TITLE
ubuntu 14 系统部署运行 eggjs 报错

### ISSUE THREAD

**Issue by doubleflying** [eggjs/egg#1200]
本人在Windows环境下 用 VScode 编辑你们提供的demo，然后成功运行，但是我把代码稍微改动下（View层）放到自己的Ubuntu 14 系统环境下 运行 npm  run dev  结果报错 ，看报错信息貌似是说 你们的JS 在严格模式下 使用了 常量定义 ，我已经截图下来了，烦请查看确认下问题和解决方案，谢谢！
![bug1](https://user-images.githubusercontent.com/13399393/28254335-5bbff63e-6ade-11e7-9e6a-6cf24acae42a.png)

**Comment by atian25** [comment]
node 0.10.48.....

最低版本支持 6.x
