### ISSUE TITLE
vscode升级1.14后默认protocol由 Legacy 变为了 Inspector

### ISSUE THREAD

**Issue by anto1717** [eggjs/egg#1206]
* **Node Version**: 6.3.1
* **Egg Version**: 3.0.4
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: OSX
* **Mini Showcase Repository**:

vscode升级1.14后，默认protocol由 Legacy 变为了 Inspector,  如果原来用的是 Legacy， 升级后vscode调试会跑不起来。

需要修改文档：https://eggjs.org/zh-cn/core/development.html#使用-vscode-进行调试 ，
在 .vscode/launch.json 的Launch Egg字段添加 
```
"protocol": "legacy"
```

详情参考：https://github.com/Microsoft/vscode/issues/30629#issuecomment-315196813

**Comment by okoala** [comment]
@liuanto  欢迎PR
