### ISSUE TITLE
requestBody为空

### ISSUE THREAD

**Issue by Kunoky** [eggjs/egg#1207]
当我发送post请求时无法获取request的body
浏览器request payload：
{userName: "wetrtyu", password: "sedfghj", remember: true}

egg controller中
 console.log('post body',this.ctx.request.body);

cmd窗口：
post body {}

**Comment by dead-horse** [comment]
content-type 是什么

**Comment by Kunoky** [comment]
application/json

**Comment by dead-horse** [comment]
给一个完整的可复现例子上传到 git 吧，现在这样看不出来

**Comment by Kunoky** [comment]
前端用的是DVA，

**Comment by dead-horse** [comment]
前端代码启动编译报错，但是通过 curl 请求后端服务，是可以拿到请求 body 的

```bash
curl http://localhost:7001/login -X 'POST' -d '{"foo":"bar"}' -H 'Content-Type: application/json'
# post body { foo: 'bar' }
```

**Comment by Kunoky** [comment]
嗯，我这边之前也是可以通过curl拿到body。但是用dva的前端访问不就取不到。dva的话用npm start 命令启动

**Comment by dead-horse** [comment]
去看看 dva 发的时候是不是 header 不对吧，可以在 egg 中打印出来请求 header 确认，如果 curl 没问题的话说明就不是 egg 的问题了。

给的 dvaDemo  npm start 会报错。

**Comment by Kunoky** [comment]
{ method: 'POST',
  url: '/login',
  header:
   { 'accept-language': 'zh-CN,zh;q=0.8',
     'accept-encoding': 'gzip, deflate, br',
     referer: 'http://localhost:8001/',
     accept: '*/*',
     'content-type': 'application/json;',
     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36',
     origin: 'http://localhost:8001',
     'content-length': '56',
     connection: 'close',
     host: 'localhost:7001' } }

这是header，我用dva连java，java是可以取到body的。

**Comment by iyuq** [comment]
`'content-type': 'application/json;'`去掉`application/json;`后面的`;`试试

**Comment by Kunoky** [comment]
后面的哪个？

**Comment by iyuq** [comment]
改成`'content-type': 'application/json'`试试

**Comment by Kunoky** [comment]
非常感谢，已解决

**Comment by iyuq** [comment]
不客气，一般后面跟`charset`才会用到`;`

**Comment by Kunoky** [comment]
因为之前连java没有问题，所以我就没注意到是前端代码的问题

**Comment by pansly004** [comment]
@Kunoky 请文您怎么解决的
