### ISSUE TITLE
线上环境无法打印日志到文件并且控制台也不能输出日志

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1208]
折腾了半天，确实不知道怎么做了，希望帮忙解答一下。
我的配置如下：

config.perd.js配置文件配置如下
`config.logger = {
  	level:'DEBUG',
	  consoleLevel: 'DEBUG',
	};`

 package.json 是通过egg-init 生成的

`"scripts": {
    "start": "cross-env EGG_SERVER_ENV=prod node index.js",
    "dev": "egg-bin dev",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  }`

**Comment by atian25** [comment]
pred 是什么鬼？

日志默认已经配置好的，线上是发布到 home/admin/log 的，看下 run/application_config.json 里面最终 logger 的路径配置就知道了

发自我的 iPhone

**Comment by dead-horse** [comment]
线上环境的日志默认和本地环境日志目录不一样，一般来说会在 `${HOME}/logs/${appname}` 下，去找找吧

**Comment by zuoye520** [comment]
@atian25 谢谢！ 看到了！我以为线上日志都是输出到项目当前目录。
但是我们公司有时候需要在控制台看日志，线上环境需要怎么配置呢？？
配置如下也不行！
// config/config.prod.js
`exports.logger = {
  consoleLevel: 'DEBUG',
};`

**Comment by zuoye520** [comment]
@dead-horse 谢谢！ 刚刚已经找到日志文件，但是在控制台无法看到日志输出。不知道需要怎么配置才能在控制台输出？
exports.logger = { consoleLevel: 'DEBUG', };

**Comment by atian25** [comment]
你的启动语句是啥？ 是不是重定向到文件了。

**Comment by zuoye520** [comment]
@atian25 

启动语句 npm start

//package.json scripts 配置如下
> "start": "cross-env EGG_SERVER_ENV=prod node index.js",
//index.js
> require('egg').startCluster({
  baseDir: __dirname,
  port: process.env.PORT || 7001, // default to 7001
});

**Comment by zuoye520** [comment]
@atian25 
启动语句 npm start

//package.json scripts 配置如下

`"start": "cross-env EGG_SERVER_ENV=prod node index.js",`
//index.js
`require('egg').startCluster({
baseDir: __dirname,
port: process.env.PORT || 7001, // default to 7001
});`

**Comment by atian25** [comment]
删除重新安装下依赖，然后检查下 run/application_config.js 里面的 env 还有 logger 的取值是否正确。

然后用 egg-init 建一个新的项目看能否重现，我本地复现不了。

**Comment by atian25** [comment]
@zuoye520 解决了的话最好在这里同步下具体的原因
