### ISSUE TITLE
egg-static在prod环境的buffer参数默认是true有问题

### ISSUE THREAD

**Issue by Tomatoo** [eggjs/egg#1213]
buffer为true的话，

> store the files in memory instead of streaming from the filesystem on each request

把文件缓存在内存中，这样内存不会暴涨吗？

**Comment by ngot** [comment]
内存是固定的，不要放特别多的文件即可。如果不缓存，每次都磁盘IO将会将会产生大量的系统调用。

**Comment by atian25** [comment]
静态文件应该尽可能放到 cdn

**Comment by Tomatoo** [comment]
是尽量放在CDN，我的疑问是如果不放在CDN的情况下，这里如何处理？如果把buffer打开，可否添加一个最大内存占用的属性，防止静态文件占用太多内存？
