### ISSUE TITLE
egg-redis 配置存储内容失效时间问题

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1214]
作者你好！
我在使用egg-redis的时候 发现存储内容无法在配置中配置存储内容失效时间？
如下是我的配置，我查看ioredis文档的时候 发现并没有设置失效时间，以前的项目中是ttl这个参数。 
`config.redis = {
		client: {
			port: 6379, // Redis port
			host: '127.0.0.1', // Redis host
		        password: '',
		        keyPrefix:'egg:',
			ttl: 10000, //redis的有效期
			maxAge:7000,
	      	        db: 3,
		},
	}`
在业务逻辑中这样设置是可以设置过期失效时间的，难道只能这么做？
`yield app.redis.set('test', '22222', 'PX', 7000);`

**Comment by iyuq** [comment]
这个你应该去找ioredis提issue。

**Comment by smancang** [comment]
> 这个你应该去找ioredis提issue。

汽车门硬度不够是不是该找造铁厂

**Comment by atian25** [comment]
所以楼上你觉得 Node 的问题，Win 的问题，VSCode 的问题，Terminal 的问题，操作系统安装的问题，都应该找 Egg ？

**Comment by GalensGan** [comment]
@smancang 就是这么个理，点赞
