### ISSUE TITLE
egg  请求超时怎么搞，本地也会超时，之前说没有限制 本地不应该超时吧？

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#1220]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
请按照标题中的项目给出详细信息

**Comment by ngot** [comment]
问题含糊，无有用信息，先关了
