### ISSUE TITLE
[egg-core]  FileLoader向class的原型中注入fullPath

### ISSUE THREAD

**Issue by AnzerWall** [eggjs/egg#1222]
https://github.com/AnzerWall/egg-test-fullPath
https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L160

FileLoader在加载类的情况下会向原型中注入fullPath和pathName，是否会造成干扰用户代码。

可否和object时的行为统一起来，都使用Symbol进行注入。。

**Comment by popomore** [comment]
这个是 api，symbol 就取不到了

**Comment by AnzerWall** [comment]
应该可以访问 Symbol.for?或者导出这个Symbol？
因为我看到object的那两个是有导出的

**Comment by dead-horse** [comment]
API 不适合通过 Symbol 导出，访问太麻烦，这个就是一个约定，就和 `this.ctx` ，`this.app` 一样
