### ISSUE TITLE
restful 接口下 controller 的命名方式

### ISSUE THREAD

**Issue by F-loat** [eggjs/egg#1223]
请问使用 restful 接口的话， controller 文件的命名是否推荐复数形式，
文档中提及restful接口时 app/controller/post.js 及 app/controller/posts.js 两种方式都有使用过

**Comment by popomore** [comment]
看这篇 https://eggjs.org/zh-cn/tutorials/restful.html

**Comment by F-loat** [comment]
谢谢，这篇restful的介绍之前也有看过， 其中 controller 及 service 都是使用了复数形式的 topics.js，

那是否在对 [controller](https://eggjs.org/zh-cn/basics/controller.html) 等的介绍文档中也应统一使用复数形式的 posts.js 而不是 post.js ，

restful 接口中 /api/v2/topics ， topics 使用复数比较好我是比较明确的，但是不太确定 controller 文件的命名有没有什么规范

**Comment by popomore** [comment]
是否是复数跟 rest 定义有关，controler 本身就是没有规范的，如果使用 rest 路由规则，controler 就可以按照这个规则写。
