### ISSUE TITLE
egg-socket.io如何获取 io.sockets

### ISSUE THREAD

**Issue by BrooklynaT** [eggjs/egg#1225]
* **Node Version**:6.9.2
* **Egg Version**:1.6.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:
* **Platform**:MacOS
* **Mini Showcase Repository**:

 目前运行的是 egg-socket.io reade.me 中提供的示例，但是在 demo 中，app/io/controller/chat.js 服务端向客户端发送消息使用的是socket.emit，现在想服务端发送的消息所有的用户都能收到，socket.io 中使用的是 io.sockets.emit，不知道在这里如何获取的这个方法，谢谢。

**Comment by ngot** [comment]
io.sockets.emit 即可获得
