### ISSUE TITLE
weex已经打击到我了，egg不会又虎头蛇尾给捐了把

### ISSUE THREAD

**Issue by SteveCruise** [eggjs/egg#1226]

**Comment by ngot** [comment]
egg是整个大阿里node服务基石，不可能放弃。 再说捐献apache是为了把项目做大，并不是不要了，能够进去apache那是项目的荣幸，高兴还来不及。

**Comment by SteveCruise** [comment]
谢谢，起的真早

**Comment by solarhell** [comment]
您自己看看issue处理速度就清楚了...
另外 不要在项目里提无关问题

**Comment by SteveCruise** [comment]
是的，吐槽了下大伤感情的weex。egg看上去靠谱~

**Comment by okoala** [comment]
@SteveCruise  放心~
eggjs 和 ant-design 都是阿里开源新标杆~
从每一条 issue 你都能感受到~

**Comment by afc163** [comment]
https://github.com/apache/incubator-weex/tree/0.16-dev

weex 提交还是很频繁的，不要道听途说。

**Comment by ngot** [comment]
Github的的 activity图只会展示默认分支的活动情况，而对于其他分支，不展示。这个很容给人误解。

**Comment by SteveCruise** [comment]
谢谢谢谢，谢谢各位

> weex 提交还是很频繁的

我也看到了
