### ISSUE TITLE
包装了一个插件，让它有效需要在路由里显示的设置，怎么让它对于所有的请求有效啊

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#1232]
我在这个　https://github.com/buzai/egg-loger
包装了ｋｏｇ－ｌｏｇ但是用的时候需要在路由里配置

```
  app.get('/testlog', app.loger, 'home.testlog');

```
请问怎么修改直接有效呢

**Comment by atian25** [comment]
直接挂载为一个全局的 middleware。

我看你在 https://github.com/buzai/egg-loger/blob/master/app.js 已经挂载了啊

**Comment by buzai** [comment]
@atian25 但是没起作用，我还是得显示的在路由里配置

**Comment by buzai** [comment]
@atian25 
```
  config.loger = {
    enable: true,
    formats: 'short'
  };
```
我发现这个设置为真，就对所有的路由有效了，不知道这样做对不

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/middleware.html#enable

你这个参数和 middleware 的开关配置冲突了。

cc @dead-horse  😆

**Comment by buzai** [comment]
@atian25 
我没有用那个参数啊
```
      this[LOG] = koaLog(this.config.loger.formats);
```
其实只用到了ｆｏｒｍａｔｓ
我的理解是我把它挂载在ａｐｐ上了

我这样写ｔｒｕｅ就是开启了它，这样全局都起作用了，然后我要是设置为ｆａｌｓｅ，其实我没开启它只是把它挂载在了ａｐｐ上，这样我手动加在路由里也可以起作用了．

```  
config.loger = {
    enable: true,
    formats: 'short'
  };
```


而插件配置文件只是加载插件，但是用不用还是需要在配置文件里设置?
```
exports.loger = {
  enable: true,
  package: 'egg-loger',
};
```

这里还是说这两个enable其实会互相覆盖呢，有点蒙

**Comment by popomore** [comment]
middleware 的 enable 是在 config 配置里的，和插件没关系。

**Comment by buzai** [comment]
@popomore 谢谢诶

**Comment by atian25** [comment]
你配置了 `config.loger.enable = false` 啊，https://github.com/buzai/egg-loger/blob/master/config/config.default.js#L10

这个参数会决定 middleware 的挂载，具体参见 https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/middleware.js#L94

至于两个的差别，可以看我给你的那个文档 https://eggjs.org/zh-cn/basics/middleware.html#enable
- plugin.js 的 enable 代表是否开启这个插件。
- config 的那个 enable, 代表同名的 middleware 是否开启。

**Comment by buzai** [comment]
@atian25 谢谢还是看源码更明白啊哈哈
