### ISSUE TITLE
egg-socket.io 如何限制连接上来的域名？

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#1233]

**Comment by ngot** [comment]
写这个连接中间件判断host即可

**Comment by Ailein** [comment]
if(this.socket.handshake.headers.host == '127.0.0.1:7002'){


}else {
  

}
这样？
可是 我不知道 如何阻止这个连接 ，只是socket的连接 ，整个网址不需要被阻止。

**Comment by Ailein** [comment]
@ngot

**Comment by ngot** [comment]
能够走到连接中间件肯定是 socket请求，而不是普通的http请求。
然后，只需要return，别执行`yield* next;` 即可

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/28564570-f94d5cb0-715b-11e7-9589-bc16df9f31d6.png)
试了return ,但是 我测试 还可以通信，emit 发出去还是可以接受到。
![image](https://user-images.githubusercontent.com/26592729/28564622-24c265f2-715c-11e7-8bdd-17a8826717cc.png)

**Comment by Ailein** [comment]
@ngot

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/28564710-79c3e652-715c-11e7-9e7b-3512157212d0.png)
![image](https://user-images.githubusercontent.com/26592729/28564716-7e7a618a-715c-11e7-92b5-811784962f76.png)

**Comment by Ailein** [comment]
最后一个问题就是，如何可以在普通的 controller中 发送 this.ctx.socket.emit('res', `Hi! I've got your message`);这样发 我试了是接受不到
![image](https://user-images.githubusercontent.com/26592729/28565511-118a3304-715f-11e7-9fbd-1529760457f3.png)


 app.io.sockets.emit('res','333');这样发送给全部的socket连接是可以的

**Comment by Ailein** [comment]
[https://github.com/Ailein/socket.io-eggjs]
这个是复现代码

@ngot 谢谢 帮看下

**Comment by ngot** [comment]
我来研究看下你的代码

**Comment by Ailein** [comment]
就是return 无法中止连接。

**Comment by Ailein** [comment]
throw 一个错误是可以中止，但是 感觉 这样不太好。

**Comment by ngot** [comment]
```js
if(this.socket.handshake.headers.host != '127.0.0.1:7002'){
    this.socket.disconnect(true);
    return;
}
```

就断开了连接了。这个是 `socket.io` 自己的api。

 这样做有个问题，就是默认的 `socket.io-client` 会不停的重连。

**Comment by Ailein** [comment]
我记得 socket.io里面是有个 origin 的配置 ，可是 我在egg-socket.io 不知道 怎么配

**Comment by ngot** [comment]
没有看到这个 `origin` 的配置,在哪里能看到？

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/28615584-28880c20-722c-11e7-9ed2-5cad2077cfcf.png)
比方说 这个set 集成到egg-socket.io 呢？可以的么

**Comment by Ailein** [comment]
已经挂载到app上了是否可以在哪里配置？

**Comment by Ailein** [comment]
还有官方的这种
![image](https://user-images.githubusercontent.com/26592729/28615829-0b9b646c-722d-11e7-8c31-2ef6907b6b29.png)

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/28616099-fd84507c-722d-11e7-961b-b383e016bd46.png)
socket.io源码

**Comment by ngot** [comment]
io.set 这个可以写到 router.js 里面

**Comment by Ailein** [comment]
谢谢，router.js里面可以，这个方式好，没有权限连接上来的client报403错误，egg 很赞！！！集成能力强！！
