### ISSUE TITLE
Sticky Mode 启用时的问题

### ISSUE THREAD

**Issue by zyc1006** [eggjs/egg#1237]
[https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L130](https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L130)
Sticky Mode 启用时，如果 node 应用服务器始终位于一台 nginx 服务器之后，是不是 remoteAddress 一直都是127.0.0.1？这样是不是所有的请求都到了一个 worker 上？
另一个场景，如果一个用户的多个请求经过多台 nginx 服务器组成的集群最后都发到同一台 node 应用服务器上，这个用户的所有请求也无法被同一个 worker 进行处理，因为 remoteAddress 是各个 nginx 服务器的地址，无法 hash 到同一个 worker。
感觉是不是取客户的 client ip 进行 hash 更加合理？或者能不能做成可配置的，让开发者根据不同的场景选择hash的参数？ 谢谢！

**Comment by ngot** [comment]
根据：https://nodejs.org/api/net.html#net_class_net_socket 可知，在TCP连接阶段拿到的socket对象，能够拿到的有效的 client 属性非常有限：

- socket.remoteAddress
- socket.remoteFamily
- socket.remotePort

只有  `socket.remoteAddress` 这一个属性能够拿到 client 信息。所以，只能从这个属性出发，来做配置。

我来看一下怎么配这个属性

**Comment by zyc1006** [comment]
能不能通过 connection.on('data', ...)  和 http-headers 获取 http 中的 header 信息来得到 X-Real-IP 或者 X-Forwarded-For 字段，然后再根据这些字段进行hash呢？

**Comment by Ailein** [comment]
@ngot 我提的那个问题 可以了？

**Comment by ngot** [comment]
不太好解析拿到 http 的 http header，而且，后续连接对象传递过去，也还要解析一次，很是浪费

**Comment by zyc1006** [comment]
的确不好处理，如果只在第四层的话只有 @ngot 提到的这三个参数。我现在的解决办法是，对于socket.io请求在nginx上再做一次转发，保证hash到一个worker上，而其他正常的请求不作处理，hash到不同的worker上，最大程度保证性能。

**Comment by yxw13141618** [comment]
> 的确不好处理，如果只在第四层的话只有 @ngot 提到的这三个参数。我现在的解决办法是，对于socket.io请求在nginx上再做一次转发，保证hash到一个worker上，而其他正常的请求不作处理，hash到不同的worker上，最大程度保证性能。

您好，我现在也碰到了相同的问题 能请教下你nginx上是怎么配置的吗？

**Comment by yxw13141618** [comment]
> 根据：https://nodejs.org/api/net.html#net_class_net_socket 可知，在TCP连接阶段拿到的socket对象，能够拿到的有效的 client 属性非常有限：
> 
> * socket.remoteAddress
> * socket.remoteFamily
> * socket.remotePort
> 
> 只有 `socket.remoteAddress` 这一个属性能够拿到 client 信息。所以，只能从这个属性出发，来做配置。
> 
> 我来看一下怎么配这个属性

@ngot 您好 这个后来有什么好的解决办法了么
