### ISSUE TITLE
数据库回滚问题

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#1239]
用的egg-mysql，现在想要四个表的操作回滚，不知道这个驱动可以做到不，不行的话我就想办法把这部分业务独立出来在想办法．

**Comment by buzai** [comment]
@popomore 对的，不知道可以做么

**Comment by popomore** [comment]
见 https://github.com/eggjs/egg-mysql#transaction

**Comment by buzai** [comment]
@popomore 谢谢啊，假设现在我是开４个线程，然后一个业务需要一个个执行，这个业务包含４张表的更新，我想的是队列任务，再加上事物回滚，这样是不是可以保证这个不会出错了呢

**Comment by popomore** [comment]
node 没线程，你写个 for 循环就是串行执行的。

**Comment by buzai** [comment]
@popomore 额．错了，是进程

**Comment by popomore** [comment]
server 是无状态的，请求会随机落到一个进程。
