### ISSUE TITLE
egg-onerror -> koa-onerror -> nunjucks 依赖简化

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#124]
![image](https://cloud.githubusercontent.com/assets/227713/19510482/04bc84e4-9616-11e6-9c4e-7390b4dbfeb6.png)

![image](https://cloud.githubusercontent.com/assets/227713/19510565/6ab73442-9616-11e6-9714-fed0ac8d2000.png)

**Comment by dead-horse** [comment]
https://github.com/koajs/onerror/pull/14
