### ISSUE TITLE
logger支持自定义格式吗？

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#1240]
公司有自己的日志分析系统，需要满足一定的格式写入，可以修改默认的写入格式吗？

**Comment by atian25** [comment]
支持
- https://eggjs.org/zh-cn/core/logger.html#高级自定义日志
- https://github.com/eggjs/egg-logger

**Comment by miaojiuchen** [comment]
@atian25 感谢，这个transport我的理解是相当于一个额外的扩展输出，有没有直接修改common-error.log打印格式的方式？

**Comment by popomore** [comment]
你可以找到 errorLogger，替换他的 transport

**Comment by miaojiuchen** [comment]
@popomore 感谢，尝试了将errorLogger的file transport替换后可以实现。那么还有一个问题，contextLogger的transport要如何修改？在哪里书写这段代码？应该不能是每次请求进来后修改logger吧？

**Comment by popomore** [comment]
看你要改哪个维度的，一般 app 改了 ctx 也会变，如果是改 paddingMessage 可以覆盖 app.ContextLogger
