### ISSUE TITLE
关于初始化项目的配置建议。。。

### ISSUE THREAD

**Issue by lzq920** [eggjs/egg#1241]
使用egg-init工具新建了一个项目，忽然发现，配置各项东西太花时间了，有没有打算在配置文件中添加更多的默认配置，让用户选择哪些启用哪些不启用。比如session，mysql，mongoose等等

**Comment by atian25** [comment]
暂时还没时间做，https://github.com/eggjs/egg/issues/379

**Comment by popomore** [comment]
这种是靠上层框架封装的，脚手架做了也需要用户去配的。

**Comment by lzq920** [comment]
嗯，是这样。就是初始化以后配置比较繁琐，挺费时间的

**Comment by atian25** [comment]
@lzq920 如果你的部门有很多项目，你们应该基于 egg 封装一个上层框架，这样在应用那边就不需要配置了。

可以看下：
- https://eggjs.org/zh-cn/tutorials/progressive.html
- https://eggjs.org/zh-cn/advanced/framework.html
