### ISSUE TITLE
请问怎么把ctx.render第二个参数的值，在view里面通过js赋值的方式获取呢？

### ISSUE THREAD

**Issue by cgygd** [eggjs/egg#1242]
用的是Nunjuck，模板里面是这样渲染的
{% for item in data %}
  <div class="item">
    <a href="{{ item.url }}">{{ item.uid }}</a>
    <p>{{ helper.relativeTime(item.time) }}</p>
  </div>
  {% endfor %}

下面这样会报错
`<script type="text/javascript">
    var a = `{{data}}`
    console.log(a)
  </script>`

用es6的模板字符串可以获取，但是获取来是的字符串，需要自己替换特殊字符再转成json
`<script type="text/javascript">
    var a = `{{data}}`
    console.log(a)
  </script>`

**Comment by popomore** [comment]
没加引号

**Comment by cgygd** [comment]
ls,没加引号是何解？

**Comment by popomore** [comment]
模版没写当然就没有了

**Comment by cgygd** [comment]
额整体代码是这样的。
**## controller**
> module.exports = app => {
  class HomeController extends app.Controller {
    * index() {
      const ctx = this.ctx;
      const data = yield this.service.users.show(1)
      yield ctx.render('home.html', { data:data.data });
    }
  }
  return HomeController;
};

**## view**

> <html>
  <head>
    <title>home</title>
    <link rel="stylesheet" href="/public/semantic-ui/semantic.min.css" />
    <script src="/public/js/jquery.js"></script>
    <script src="/public/semantic-ui/semantic.min.js"></script>
  </head>
  <body>
  <h1>home</h1>
  {% for item in data %}
  <div class="item">
    <a href="{{ item.url }}">{{ item.uid }}</a>
    <p>{{ helper.relativeTime(item.time) }}</p>
  </div>
  {% endfor %}
  <script type="text/javascript">
    console.log({{data}})
  </script>
  </body>
</html>

**Comment by popomore** [comment]
console.log('{{data}}')

**Comment by cgygd** [comment]
好的谢谢。
原来要这样console.log(`{{ helper.sjs(data) }}`)
没好好看文档～sorry

**Comment by atian25** [comment]
@cgygd 不是文档的问题，你这里理解有点混淆了，把服务端渲染和前端渲染时序搞混了。
你用控制台看下 html 的原始输出就知道了。
