### ISSUE TITLE
sequelize官方已是V4版本, egg-sequelize啥时候同步下版本

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#1243]
最近用 egg-sequelize 
看的是官方手册, http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html
但是发现总有问题, 原来是版本问题!

**Comment by iyuq** [comment]
已经更新4.x了

**Comment by junmaqiang** [comment]
不会吧,难道我看错了? @iyuq 
![1](https://user-images.githubusercontent.com/1819457/28619347-8177aaee-723a-11e7-9c93-ca2b29c20d64.png)

**Comment by iyuq** [comment]
这个egg-sequelize的版本啊，你要看package.json里面sequelize的版本。

**Comment by junmaqiang** [comment]
哦,看到了! @iyuq
