### ISSUE TITLE
egg-static，在线上环境下无法找到public目录下的资源

### ISSUE THREAD

**Issue by qiuyue** [eggjs/egg#1244]
这是我的prod环境下的static配置
'use strict';
const path = require('path');
module.exports = appInfo => {
    const config = {};

    config.static = {
        prefix: "/public/",
        dir: path.join(appInfo.baseDir, 'app/public'),
        dynamic: true,
        preload: false,
        buffer: true,
        maxFiles: 1000,
        maxAge: 31536000,
    };
    return config;
}
所有的资源目录都是404。
我想问下，应该怎么修改配置。
我使用了nginx的反向代理指向的egg服务。
egg使用的默认的7001端口。

另外我还想问一下，如果在线上环境中 重启服务。

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
静态资源的路径是什么

**Comment by qiuyue** [comment]
/public/js/common/common.config.js

**Comment by popomore** [comment]
访问 7001 看看，先排除 nginx 的原因，如果有问题把代码提交一下，给一个可重现的例子。

**Comment by qiuyue** [comment]
http://47.92.89.13:7001/public/js/common/novo.func.js 这个路径是可以访问到，
http://47.92.89.13:7001/js/common/novo.func.js  这样是404

是把代码提到git吗？

**Comment by popomore** [comment]
prefix 是 public，下面这个肯定访问不到。

**Comment by qiuyue** [comment]
/public/js/common/novo.func.js 这个路径是可以访问到，
/js/common/novo.func.js 这样是404

是把代码提到git吗？

**Comment by qiuyue** [comment]
替换成域名之后就404了

**Comment by popomore** [comment]
应该是你反向代理的问题，egg 已经证实可以访问。

**Comment by qiuyue** [comment]
目前还是有一个问题是，我请求js的路径，走到了中间件里。
从我打出来的日志看的话
/js/common/novo.func.js] token的值并不存在

**Comment by xixichensh** [comment]
prefix: "/",试试
