### ISSUE TITLE
 egg-mysql没有封装模糊查询？

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1245]
作者你好！
我看egg-mysql源码里面是用的ali-rds,然后我到ali-rds查看源码里面没有找到模糊查询相关的信息。
在egg里面假如需要模糊查询是需要通过sql拼装？

``this.app.mysql.query(sql,values)``

**Comment by buzai** [comment]
@zuoye520 似的，没有模糊搜索，得自己写ｓｑｌ

**Comment by popomore** [comment]
如果你要用 orm 可以用 egg-sequelize，mysql 是要自己写 sql 的。
