### ISSUE TITLE
关于egg-static的疑问

### ISSUE THREAD

**Issue by qiuyue** [eggjs/egg#1248]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by qiuyue** [comment]
目前我使用egg-static来放置静态资源。
prod的配置如下
config.static = {
        prefix: "/public/",
        dir: path.join(appInfo.baseDir, 'app/public'),
        dynamic: true,
        preload: false,
        buffer: true,
        maxFiles: 1000,
        maxAge: 3600,
    };
这样当我更新public里的js的时候，因为缓存就无法看到最新的效果
我用kill -9 pid杀掉进程，重新EGG_SERVER_ENV=prod nohup node index.js&
但是缓存还是在。
所以我想问下，如果重启才能清理掉缓存？

**Comment by popomore** [comment]
浏览器缓存吧

**Comment by atian25** [comment]
你不是配置了 `maxAge: 3600` 么，看 devtool 的 network 就知道了

**Comment by qiuyue** [comment]
如果我使用CDN来处理静态资源，那么egg-static的buffer是不是就可以不用了。

**Comment by popomore** [comment]
用了 CDN 为啥还要 egg-static，关闭插件就可以了。
