### ISSUE TITLE
egg.development 排除目录还是会报错，这是什么情况？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#1253]
// config/plugin.js
exports.development = {
  enable: true,
  package: 'egg-development',
};

// config/config.default.js
  config.development = {
    ignoreDirs: [ 'app/view', 'app/public' ],
    watchDirs: [ 'app/controller', 'app/engine', 'app/extend', 'app/middleware', 'app/router', 'app/service' ],
    fastReady: true,
    reloadOnDebug: true,
  };

2017-07-28 12:32:04,793 ERROR 9744 nodejs.EPERMError: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
code: 'EPERM'
errno: 'EPERM'
syscall: 'Error watching file for changes:'
filename: null
dir: 'F:\\shopStatistics\\app\\view\\client'
name: 'EPERMError'
pid: 9744
hostname: sea-PC

**Comment by atian25** [comment]
EPERM 是权限问题吧，有没有最小可复现案例

**Comment by a526672351** [comment]
有案例啊，如何发送个dome 你？

**Comment by atian25** [comment]
用 egg-init 初始化一个最小可复现代码库，上传到你的 GitHub

发自我的 iPhone

**Comment by x22x22** [comment]
我也遇到这个问题

**Comment by x22x22** [comment]
这个问题同时存在于require('egg-cluster').startCluster;方式启动

**Comment by x22x22** [comment]
1. 先在app目录下随意创建一个目录, 这里就叫test
1. 运行起程序
1. 在文件管理器中删除此test目录
1. 就会报错
报错信息如下:
```
2018-02-06 15:44:09,302 ERROR 12760 nodejs.EPERMError: Error watching file for changes: EPERM
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
code: 'EPERM'
errno: 'EPERM'
syscall: 'Error watching file for changes:'
filename: null
dir: 'D:\\xxx\\examples-master\\hackernews-async-ts\\dist\\app\\test'
name: 'EPERMError'
pid: 12760
hostname: xxx
```

**Comment by atian25** [comment]
`EPERM` 是没权限的意思。

**Comment by x22x22** [comment]
https://github.com/eggjs/egg/issues/2085
