### ISSUE TITLE
请问egg-redis哨兵模式如何配置？

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#1255]
ioredis是支持，文档里只找到cluster的配置，看了下有个pr还没有被merge进来 https://github.com/eggjs/egg-redis/pull/8

**Comment by sunfuze** [comment]
直接看 ioredis 的文档呗

Infinity <notifications@github.com>于2017年7月28日周五 下午5:51写道：

**Comment by miaojiuchen** [comment]
@sunfuze 你好，我参照引用的pr修改了node_modules里的egg代码，然后按照ioredis的文档配置，连接不了，可以有人跟进下这个pr吗？协助通过测试merge进来

**Comment by kylezhang** [comment]
能明确的给出`egg-redis`现在支持`sentinel`连接吗？
