### ISSUE TITLE
EggLoader#loadToApp方法默认重置将要挂载到app上某个属性为空对象改进建议

### ISSUE THREAD

**Issue by changchengqin** [eggjs/egg#1257]
* **Node Version**: 7.6.0
* **Egg Version**: 1.6.0
* **Plugin Name**:egg-core
* **Plugin Version**:3.12.1
* **Platform**:win7 64位
* **Mini Showcase Repository**:

egg-core中EggLoader类的loadToApp方法中，第一行代码，能否通过在opt中指定一个参数来决定是否需要重置为空对象
![image](https://user-images.githubusercontent.com/3336443/28741268-240b949e-7445-11e7-9500-67893556b34c.png)

**Comment by atian25** [comment]
具体场景？

发自我的 iPhone

**Comment by changchengqin** [comment]
还是想在 插件 中写Controller

**Comment by atian25** [comment]
然后？ 你想怎么使用 `loadToApp` ？ show me the code

**Comment by popomore** [comment]
可以直接用手fileloader

**Comment by atian25** [comment]
@changchengqin 我写了一个简单的示例，你可以参考下 https://github.com/atian25/egg-showcase/pull/1/files ，实际使用的话，还需要考虑冲突问题。

**Comment by atian25** [comment]
还有个问题就是在插件里面注册的，在应用的 router 里面取不到，应该是时序问题吧，@popomore

**Comment by changchengqin** [comment]
@popomore 
嗯，是参考loadController和loadToApp源码后，然后手动使用FileLoader的。
只是建议能否在Egg-Core层面上加上这样一个参数判断，使用起来方便一点。

@atian25 
我的最终目的是想利用eggjs在框架、插件、应用之间的强大的灵活性、扩展性，移植到业务层面上来。
想把我们的业务产品开发组织形式也衍生成类似于eggjs在框架层面上的风格：
业务核心框架(1)、行业框架(n)、业务插件(n)、行业应用(n)
在仔细阅读eggjs官方文档后，发现直接在eggjs插件中直接写针对于不同行业的业务需求的controller和service暂时就已经很好的解决了我的问题了。
但是eggjs是不建议在插件里面直接定义controller和router的.

**Comment by changchengqin** [comment]
@atian25 
谢谢你给出的showcase.
但是在插件里面调用app.loader.loadController 是不能解决的

**Comment by atian25** [comment]
具体不能解决什么？还不是很清晰你的具体问题。写段伪代码？

**Comment by changchengqin** [comment]
1、loadController内部调用了loadToApp方法
2、loadToApp方法首先默认会重置挂在到app上属性的值为空对象
2、在插件里面调用的loadController方法，是在 Egg-Core的调用
loadController方法之前

**Comment by atian25** [comment]
明白了

**Comment by changchengqin** [comment]
@atian25 
就拿你给定的这个例子来说
最终运行起来，share插件里面写的TestController是没有成功挂在到app上的

**Comment by atian25** [comment]
嗯，被清空了，我刚才以为是时序问题。

**Comment by atian25** [comment]
可以考虑改为以下， @popomore 觉得如何？

```diff
loadToApp(directory, property, opt) {
-    const target = this.app[property] = {};
+   const target = this.app[property] = this.app[property] || {};
}
```

**Comment by popomore** [comment]
自己把插件目录放入 directory 就好了

**Comment by atian25** [comment]
> 自己把插件目录放入 directory 就好了

@changchengqin 参考 https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/service.js#L19

那个示例项目也更新了，主要逻辑如下：

```js
// app/router.js
module.exports = app => {
  // https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/controller.js#L14
  app.loader.loadController({
    directory: app.loader.getLoadUnits().map(unit => path.join(unit.path, 'app/controller')),
  });

  app.get('/', 'home.index');
  app.get('/test', 'test.echo');

  console.log(app.controller);
};
```

loader 的这段逻辑，更建议是放到你的上层框架的 app.js 里面做。

**Comment by changchengqin** [comment]
好的，谢谢.
