### ISSUE TITLE
上传文件、下载文件需求

### ISSUE THREAD

**Issue by SteveCruise** [eggjs/egg#1259]
上传（2G以内大）文件到egg服务器，从egg服务器下载（2G以内大）文件。两个需求都最好配有nodejs客户端demo，不然难以测试对接，谢谢谢谢了

**Comment by atian25** [comment]
看 eggjs/examples 的示例

发自我的 iPhone

**Comment by SteveCruise** [comment]
好的！！！！！！

**Comment by atian25** [comment]
哪来的内存？用 stream 啊，https://github.com/eggjs/examples/blob/master/download/app/controller/index.js#L16

上传 https://github.com/eggjs/examples/blob/master/multipart/app/controller/upload.js

至于 koa2 的，不想再重复讨论了，跟现在入不入坑完全没关系，升级 koa2 对应用完全无感知。

**Comment by SteveCruise** [comment]
谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额谢谢谢谢额
