### ISSUE TITLE
egg-redis@1.0.2 模块不配置password时报错并无法连接redis

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#1260]
@jtyjty99999 
配置如下
```javascript
config.redis = {
  clients: {
    session: {
      port: 6379,
      host: '127.0.0.1',   // Redis host
      password: null,
      db: 0,
    },
    cache: {
      port: 6379,
      host: '127.0.0.1',   // Redis host
      db: 1,
    },
  },
};
```
session连接可以正常连接，cache连接直接崩溃, 查看egg-redis源码后发现是断言检查要求password不能为undefined，想确定下是强制要求设置还是意外状况？没有发现相关说明。

**Comment by treemore** [comment]
感觉验证搞太严格了。

**Comment by luicfer** [comment]
断言就是严格要求。
大多数是允许你不写的配置项会有默认值。

**Comment by duncup** [comment]
密码本身并非必选项

**Comment by duncup** [comment]
```javascript
const Redis = require('ioredis');
let redis = new Redis({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  db: 0
})
redis.sadd('set', 1, 3, 5, 7);
```
直接调用egg-redis封装的ioredis无密码配置项并无报错。换言之密码项不配置实际是被支持的。

**Comment by duncup** [comment]
@ngot

**Comment by atian25** [comment]
https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L19

应该是这里限制了，可以提个 PR。

cc @jtyjty99999 之前限制这里有什么考虑么?

**Comment by duncup** [comment]
提交个PR修改这个很简单，但是想先确定是不是有什么特殊考虑。

**Comment by duncup** [comment]
一直没有答复准备直接提交PR了 @atian25

**Comment by jtyjty99999** [comment]
@duncup 你觉得redis无密码安全吗。。这种约定我觉得都没必要直接写出来。。不写密码就上线很不好吧

**Comment by jtyjty99999** [comment]
https://ruby-china.org/topics/28094

**Comment by duncup** [comment]
本地测试时候测试环境属于无密码环境并没有什么不妥吧？而且非要用无密码的人写一行
```
password: null
```
一样能够无密码使用。

**Comment by jtyjty99999** [comment]
写``` password: null```跟 “不写“的人区别是一个是知道他自己没写密码，一个是不知道的。

**Comment by duncup** [comment]
如果从安全问题考虑我倒是赞成强制写密码配置，不过是不是直接加进文档会更好一点呢？
因为我确定原因的时候来回找了一段时间。我想不写出来的话一样还会有更多人觉得莫名其妙，毕竟底层的ioredis是支持无密码配置的。

**Comment by jtyjty99999** [comment]
好的，我改一下文档
