### ISSUE TITLE
egg-mongoose   数据库链接用户密码在哪里配置？

### ISSUE THREAD

**Issue by ismeteor** [eggjs/egg#1261]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
直接写在 url 或者放到 options 里面，建议后者。

- https://github.com/eggjs/egg-mongoose/blob/master/config/config.default.js#L8
- https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L17
