### ISSUE TITLE
[egg-redis] egg.info() 可能会和 .subscribe() 冲突

### ISSUE THREAD

**Issue by brickyang** [eggjs/egg#1262]
我有一个 app 用到了 Redis 的 `subscribe()`。订阅是在 app 启动后进行的，所以放在了 `app.js` 中：

**./app.js**

```js
module.exports = app => {
    app.redis.get('sub').subscribe(key);
}
```

遇到的问题是，在 `egg-redis` 的 `app.beforeStart` 中会向日志打印一次 `redis-info()`，而这次打印有可能发生在 `redis.subscribe()` 调用之后，则会抛错。

订阅涉及到 app 的核心功能之一，需要在 app 启动后调用，除了 `app.js` 放在其他地方好像都不太合适。是不是可以给 `redis.info()` 换个位置（比如放到 `redis.connect()` 中）或者干脆取消了（这个打印好像也没什么实际意义……）？

**Comment by popomore** [comment]
app.ready 后再订阅呗

**Comment by atian25** [comment]
```js
// app.js
module.exports = app => {
    app.ready(()=> {
      app.redis.get('sub').subscribe(key);
    });
});
```

**Comment by brickyang** [comment]
@atian25 @popomore 的确可以。其实我一开始就想到 `app.ready()`，但是测试时在里面 `console.log()` 了一下，发现比 egg start 还先打印出来，以为顺序不对，所以就没有再试了。
