### ISSUE TITLE
关于node线程启动后不能自动重启

### ISSUE THREAD

**Issue by qiuyue** [eggjs/egg#1263]
使用EGG_SERVER_PROD=prod nohup node index.js& 启动之后，
大概第二天就无法访问了，连进去，发现线程已经没了？
不是说会自动监听重启吗？

**Comment by atian25** [comment]
应该是终端退出的时候 master 进程被杀死了的原因，`自动监听重启`指的是 `worker` 由于某些原因死掉后会自动重启，会有对应的错误日志。

而终端退出这个属于 linux 运维知识，可以自行去了解下。

可以看看是不是 https://github.com/eggjs/egg/issues/1055#issuecomment-317639264 的原因。

**Comment by qiuyue** [comment]
每次退出，我都执行了exit，但是还是会隔一天就没法进了。
