### ISSUE TITLE
如何能让自定义的404页面在当前路由地址上渲染？

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1269]
开发团队你们好，

如果我输入一个不存在的路由地址，默认会渲染一个404页面出来。
如果我在`config.default.js`指定了一下`notfound`，输入一个不存在的路由地址，竟然是**重定向**跳转到我设置的`/404`这个路由地址去。（[文档](https://eggjs.org/zh-cn/core/error-handling.html#404)上说的也是重定向，但是我希望能够像egg默认的那样进行渲染。）

```js
    config.notfound = {
        pageUrl: '/404',
    };
```
如果通过[中间件的方式](https://eggjs.org/zh-cn/core/error-handling.html#自定义-404-响应)去实现，页面的样式又不太好处理。。

如何才能像默认的规则一样，在当前的url中渲染404页面的内容呢？

**Comment by ngot** [comment]
你说的不用 redirect 二用  rewrite ？

**Comment by xjchenhao** [comment]
嗯嗯 可以吗？

**Comment by ngot** [comment]
直接用 [中间件的方式](https://eggjs.org/zh-cn/core/error-handling.html#自定义-404-响应) 用中间件就好，具体的页面用 模板引擎写就好：


```js
this.render(xxx) 
```

样式什么的，就和普通页面一样。

**Comment by xjchenhao** [comment]
好的，明白了，谢谢回复～ 😁
