### ISSUE TITLE
macOS vscode调试报错

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#1270]
* **Node Version**: 6.7.0
* **Egg Version**: 1.3.0
* **Plugin Name**: 
* **Plugin Version**: 
* **Platform**: macOS
* **Mini Showcase Repository**: 

![image](https://user-images.githubusercontent.com/23026766/28772971-5bb01718-761a-11e7-9270-5f3548b00b9e.png)
![image](https://user-images.githubusercontent.com/23026766/28772991-72a47e00-761a-11e7-8958-471157a69531.png)

**Comment by AkashiX** [comment]
vscode 版本为1.13.1

**Comment by atian25** [comment]
"node -v && egg-bin dev --debug" 看看输出，看报错你的 node 版本是 8。

**Comment by AkashiX** [comment]
@atian25 谢谢，确实如此。
