### ISSUE TITLE
getFileStream 返回的是FileStream 不是ReadStream

### ISSUE THREAD

**Issue by zuimeiaj** [eggjs/egg#1271]
我使用的是egg-ci 1.6.0的。
在上传文件的时候，打印出获取到的文件流是FileStream ，但是我看注释上写的返回是ReadStream,我知道是我使用上的问题，但是我找了很久都没找到解决方案，刚刚接触这个，希望能提供带你解决方案

**Comment by ngot** [comment]
请按照issue模板提供信息

**Comment by atian25** [comment]
需要补充下信息

**Comment by fengmk2** [comment]
ReadStream 的子类

**Comment by guhong1023** [comment]
找到答案了吗？我也遇到了,

**Comment by ngot** [comment]
补一下 polymorphism

**Comment by guhong1023** [comment]
@zuimeiaj  能给个例子看看嘛？

**Comment by cuitianze** [comment]
same issue

场景：
NodeJS接受客户端上传文件，然后上传到OSS。

ctx.getFileStream() 获取到的是FileStream，

fs.createReadStream(__filename) 获取到的是ReadStream。

```
 request.post({
     url: 'oss_url',
     formData: {
        filecontent: {
          value: ossStream,
          options: {
            filename: 'test',
            contentType: 'image/png',
          }
        }
     },
 }
```

ossStream 为 ctx.getFileStream() 时，上传失败，
ossStream 为 fs.createReadStream(__filename) 时，上传成功。

求问这两者有何区别，如何解决。

**Comment by cuitianze** [comment]
还有一个问题，
ctx.curl 如何实现 上述request.post的表单上传文件功能？
试过文档里  以 Multipart 方式上传文件，
但公司OSS还是会返回file is not specified in multipart

**Comment by cuitianze** [comment]
@ngot @atian25 @fengmk2

**Comment by popomore** [comment]
```js
yield ctx.curl(url, {
  method: 'POST',
  stream: ossStream,
});
```

**Comment by cuitianze** [comment]
@popomore 就是这么写的，报错。可能上传的字段里必须包括filecontent，不知道用egg curl怎么写?

![](https://user-images.githubusercontent.com/5918515/30752414-cd214aa4-9fee-11e7-9d64-ede411569649.png)

**Comment by popomore** [comment]
https://www.npmjs.com/package/form-data

用这个组装一个 stream 试试

**Comment by wuyunjiang** [comment]
怎么才能获取到ReadStream

**Comment by wuyunjiang** [comment]
@cuitianze 您解决了吗，我现在遇到跟你一样的问题，我需要将一张网络图片（只有链接），读下来传给识别接口，也是只有createReadStream可以，这种怎么解决

**Comment by wuyunjiang** [comment]
天啦噜，到底怎么才能得到ReadStream啊 @atian25 @popomore ，用form-data组装也不行啊

**Comment by atian25** [comment]
https://github.com/eggjs/examples/tree/master/multipart/app/controller

**Comment by wuyunjiang** [comment]
我不想让他保存为临时文件去读取，没有直接的办法吗，接收文件的服务端只接受readstream

**Comment by atian25** [comment]
你需要学习下 Node Stream 的相关知识，FileStream 是 ReadStream 的子类，是可以直接传过去的。

**Comment by wuyunjiang** [comment]
接受文件的接口是微信那边提供的，那边我没法控制。fileStream直接传过去不可以呀

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by longhaiyan** [comment]
https://github.com/eggjs/egg/issues/3201#issuecomment-490438035
