### ISSUE TITLE
egg-cors不生效

### ISSUE THREAD

**Issue by Kunoky** [eggjs/egg#1273]
plugin.js:
exports.cors = {
  enable: true,
  package: 'egg-cors',
};

config.default.js:
config.security = {
    domainWhiteList:['http://111.231.102.87'] ,
  };
  config.cors = {
    origin:'*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH'
  }

在开发环境下没有问题，但部署到服务器上时，浏览器仍然提示跨域问题
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://139.196.125.45' is therefore not allowed access.

* **Node Version**:6.10.3
* **Egg Version**:1.4.0
* **Plugin Name**:egg-cors
* **Plugin Version**:1.2.0

**Comment by solarhell** [comment]
错误提示都说了...
解决办法就是给生产环境创建一个 `config.prod.js`
```javascript
config.security = {
  domainWhiteList:['http://139.196.125.45'],
};
```

**Comment by Kunoky** [comment]
config.default.js下的配置不是所有环境都默认加载的吗？

**Comment by solarhell** [comment]
所以你要把不会根据环境变化的放到default里，开发的放`config.local.js`，生产环境放`config.prod.js`

**Comment by Kunoky** [comment]
确实是这样，非常感谢

**Comment by mqliutie** [comment]
@solarhell 
```
import { Context, EggAppConfig, PowerPartial } from "egg";

export default () => {
  const config: PowerPartial<EggAppConfig> = {
    security: {
      domainWhiteList: ["http://localhost:3000"],
      csrf: {
        enable: false,
      },
    },
    cors: {
      credentials: true,
      origin: (ctx: Context) => ctx.get("origin"),
    },
  };
  return config;
};

```
在 config.prod.ts 配置了 csrf false， 并且 domainWhiteList 也设置了， 运行 yarn start 的时候依旧提示跨域报错
