### ISSUE TITLE
egg-sequelize migration command doesn't work well on Windows 10(1703)

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1277]
```
PS C:\Users\Tony Ke\Desktop\dc> yarn migrate:up
yarn migrate:up v0.21.3
$ egg-sequelize db:migrate
/bin/bash: C:\Users\Tony Ke\Desktop\dc\node_modules\.bin\..\egg-sequelize\bin\egg-sequelize: No such file or directory
error Command failed with exit code 127.
```

I check the script in ``egg-sequelize\.bin\`` and I think this script is only for *nix. Am I right?
Also, I use bash on windows to execute the same command and there are no problems at all.

* **Node Version**:v6.10.1
* **Egg Version**:1.6.1
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.0.1
* **Platform**:Windows 10(1703) OS Version: 15063.483
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
Yes, it's a shell script, so it doesn't work on Windows.

**Comment by THaGKI9** [comment]
wait for a fix :)

**Comment by atian25** [comment]
maybe we could rewrite it as a plain js cli,  PR is welcome. @THaGKI9 .

cc @huacnlee

**Comment by THaGKI9** [comment]
pulled. [https://github.com/eggjs/egg-sequelize/pull/25]()

**Comment by atian25** [comment]
@THaGKI9 重新安装即可

**Comment by THaGKI9** [comment]
这么快就发～赶紧upgrade一下
