### ISSUE TITLE
curl status 302

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#1280]
curl 状态码的302时，不会自动重新请求headers里面的location 

* **Node Version**: 8.2.0
* **Egg Version**: 1.7.0
* **Plugin Name**: httpclient
* **Plugin Version**:
* **Platform**: mac
* **Mini Showcase Repository**:
``` 
app.curl('http://registry.npm.taobao.org/react/download/react-15.6.1.tgz')

{
  status: 302,
  headers: {
    location: 'https://cdn.npm.taobao.org/react/-/react-15.6.1.tgz'
  }
}
````

目前只能手动判断是否302，手动再次curl

**Comment by atian25** [comment]
传递 `options.followRedirect` 参数即可，可以通过 config 配置为全局，也可以单个请求。

- https://github.com/eggjs/egg/blob/master/config/config.default.js#L253
- https://www.npmjs.com/package/urllib#method-httprequesturl-options-callback

**Comment by zlab** [comment]
谢谢
