### ISSUE TITLE
新手关于egg-static的配置，按照官方的配置，不生效

### ISSUE THREAD

**Issue by ovensi** [eggjs/egg#1281]
如题，按照官方的说法，
`// {app_root}/config/plugin.js`
`exports.static = true;`
这样配置了，public里面的资源还是无法访问到，请问是我那里漏了步骤吗？

**Comment by popomore** [comment]
请给出重现步骤

**Comment by ovensi** [comment]
首先我按照官方给出的步骤初始化了项目
`$ npm i egg-init -g`
`$ egg-init egg-example --type=simple`
`$ cd egg-example`
`$ npm i`
然后我安装了egg-satic
 `$ npm i egg-static --save`
按照教程更改了 `// {app_root}/config/plugin.js`
`exports.static = true;`
然后我在static目录下建了一个hello world 的html，`npm start`启动egg，网址输入`http://127.0.0.1:7001/helloworld.html`显示404访问不到这个资源

**Comment by atian25** [comment]
1. 不需要手动安装和配置，`egg-static` 已经内置
2. 仔细看下文档，访问路径是 `http://127.0.0.1:7001/public/helloworld.html`

**Comment by ovensi** [comment]
好的，感谢您的宝贵时间，是我太马虎了。
