### ISSUE TITLE
socket.io-redis 使用sub的一点点小问题

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1286]
你好，我有一个问题，如果使用了socket.io 去订阅频道，那么这段代码放在哪里比较合适？

**Comment by ngot** [comment]
这个应该去 socket.io-redis 提 issue

**Comment by liujinyang1994** [comment]
@ngot 我使用的是egg-socket.io啊，这就给关了？

**Comment by ngot** [comment]
从 issue 的标题，和内容，看不出来和 egg 的关系。 请按照 模板 提 issue。

**Comment by liujinyang1994** [comment]
好的，提完了
