### ISSUE TITLE
egg-socket.io 中socket.io-redis 订阅功能

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1287]
一个小问题，我在egg里面该如何在egg-socket.io插件使用原本 socket.io-redis 里面的订阅功能

**Comment by ngot** [comment]
请按照模板提issue。

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/1286

**Comment by ngot** [comment]
egg-socket.io 里面的用法和原始一摸一样的。

https://github.com/socketio/socket.io-redis#redisadapterclientsroomsarray-fnfunction

唯一区别就是 io 对象，从 app 对象上去拿

**Comment by liujinyang1994** [comment]
@ngot 谢谢。祝愿egg越来越好

**Comment by ngot** [comment]
@liujinyang1994 解决了吗？

**Comment by liujinyang1994** [comment]
@ngot 还没有😣。
因为刚接触socket.io这部分，英语又有点烂，有点慢。
我描述一下需求，方便之后的人看。
我需要订阅redis里面的信息，然后通过socket.io返回给客户端。
我希望的是在 `app/router.js`里面可以监控频道，当频道有消息的时候可以执行对应的`controller`里面的方法，这样方便后续的维护。
大概情况就是这样。

**Comment by liujinyang1994** [comment]
@ngot 不好意思，还需要打扰你一下，我怎么样才可以直接调用app.io.controllers 里面的方法，并且传递值。例如：
`app.io.controllers.chat(message);`

**Comment by ngot** [comment]
`app.io.controllers.chat` 就是个普通的 generator函数，直接 yield 调用即可

**Comment by liujinyang1994** [comment]
但是在`io/controller`里面使用的函数获取消息是这样的。
```javascript
module.exports = () => {
   return function *() {
      const message = this.arg[0];
   }
}
```
我现在采用的方案是直接使用egg-redis的sub去订阅，然后想在接到消息的时候直接触发controllers的方法。是不是我这样做是不对的啊。

**Comment by ngot** [comment]
为啥要用egg-redis ？socket.io-redis 不是现成的吗？

**Comment by liujinyang1994** [comment]
socket.io-redis 订阅的频道不是有自己的一个规范么？ 但是我这个需要订阅的频道不符合这个规范啊。应该没办法直接使用socket.io-redis 来订阅吧

**Comment by liujinyang1994** [comment]
还有一个问题，在egg-socket.io中middleware里面设置session 无效，不知道是否跟websocket 有关。有没有什么好的方法
