### ISSUE TITLE
egg-mongoose是否应该暴露出mongoose原始对象呢？

### ISSUE THREAD

**Issue by chianquan** [eggjs/egg#1288]
我在使用egg-mongoose 的时候发现难以获取到mongoose的一些原始对象，
譬如，我需要在统一错误判断的时候判断mongo的主键已存在的错误，我想要获取到mongoose 的error对象，当时原始的mongoose相关对象都没有暴露出来，如何获取呢？
还有，我想包mongoose的promise对象改成使用bluebird，该如何处理呢？源码里面看到的是直接设置了使用原生promise

**Comment by jtyjty99999** [comment]
- 如果使用bluebird你可以重新覆盖 mongoose.Promise 
- mongoose 原始对象 可以使用 app.mongoose

**Comment by chianquan** [comment]
@jtyjty99999 在app里面的mongoose并不是原始的mongoose，而是一个已创建的连接
`
  // mongoose.connect('mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]' [, options]);
  const db = mongoose.createConnection(config.url, config.options);
  db.Schema = mongoose.Schema;
  app.mongoose = db;
`

**Comment by jtyjty99999** [comment]
@chianquan 虽然那是一个db，但是他上面有几乎所有mongoose上的方法，不知道你需要用什么，能具体说一下吗, mongoose上没有什么error对象吧

**Comment by jtyjty99999** [comment]
我会在 https://github.com/eggjs/egg-mongoose/pull/12 里处理这些问题

**Comment by jtyjty99999** [comment]
+ egg-mongoose@2.1.1
