### ISSUE TITLE
Is it ok to publish Egg.js API Documentation on a third-party site?

### ISSUE THREAD

**Issue by marswong** [eggjs/egg#1291]
I just wanna publish Egg.js API Documentation to [DevDocs](http://devdocs.io/), it can help me and other users search API fastly and easily. Meanwhile, it can also import much more site traffic to [eggjs.org](https://eggjs.org/).
If it's ok, I will do so :)

**Comment by dead-horse** [comment]
LGTM

**Comment by atian25** [comment]
Api docs or guide docs?  seems our API docs is not complete yet?

发自我的 iPhone

**Comment by marswong** [comment]
@atian25 Api docs and one page for introduction. just feel free. you can see many other api docs haven't been completed yet 😀. it will synchronize with the [official api](https://eggjs.org/api/)

**Comment by atian25** [comment]
👍🏻 thanks for your work.

发自我的 iPhone

**Comment by marswong** [comment]
don't thanks too early, I haven't done yet hh. so I will just do it.
