### ISSUE TITLE
startCluster 修改建议? 

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#1292]
https://github.com/eggjs/egg-cluster/blob/master/index.js#L20

这里是否应该返回创建的对象? 

修改成:
```
exports.startCluster = function(options, callback) {
  return new Master(options).ready(callback);
};
```

根据文档https://eggjs.org/zh-cn/basics/config.html. egg的配置是选用代码的形式. 但如果我想用参数, 不知道如何实现,. 我在做一个CLI, 现在是使用process.env.XXXX 传参数, 但感觉不好. 如果这里能够返回的话, 那我就能拿到egg对象, 从而拿到config对象了. 

仅仅个人意见, 不知道是否合理, would love to hear any feedback. thanks!

**Comment by popomore** [comment]
Egg 是通过环境加载配置，定义好多个环境的配置，如 config.default.js，config.prod.js，然后不同的环境通过环境变量 EGG_SERVER_ENV 来区分

**Comment by atian25** [comment]
@caoer 可以描述下你的具体 CLI 场景?

**Comment by caoer** [comment]
@atian25 我在创建一个dev server, 有点像hot reloading server. 是用来和iOS 设备通讯的. 每次启动的时候需要传入一些参数. 现在有比如启动的路径. 这个不是egg的路径. 而是另外的一个, 可以为任意路径的参数. 

还有需要接受一些配置参数, 从CLI传入的参数有一些不同的设置.

**Comment by popomore** [comment]
你可以在 cli 设置环境变量，然后在 config 获取

**Comment by caoer** [comment]
@popomore 环境变量是用process.env嘛? 这个怎样用config获取? 可不可以举一个例子?

**Comment by atian25** [comment]
// config/config.default.js
config.xx = process.env.xx

发自我的 iPhone

**Comment by caoer** [comment]
呃...那不就和我开始说的一样嘛. 但这样也能用, 好吧
