### ISSUE TITLE
egg-sequelize访问多个数据源问题

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#1293]
* **Node Version**:
v8.2.0
* **Egg Version**:
v.1.6.0
* **Plugin Name**:
egg-sequelize
* **Plugin Version**:
v.3.0.0
* **Platform**:
* **Mini Showcase Repository**:
请问egg-sequelize能像egg-mysql一样访问多个数据源吗 可以的话 需要怎么写呢？

**Comment by huacnlee** [comment]
得手工创建  Sequelize 实例，egg-sequelize 暂时还无法支持。

https://stackoverflow.com/questions/29019676/sequelize-multiple-databases-on-different-servers

**Comment by jinchaoxiang** [comment]
就是说用不上model这套了是吗 @huacnlee

**Comment by huacnlee** [comment]
在无法支持的情况下，你可以用 egg-mysql + egg-sequelize 一起来解决呀

egg-sequelize 作为主要数据库的，egg-mysql 作为辅助

**Comment by popomore** [comment]
可以支持下 singleton

**Comment by ngot** [comment]
是不是可以按照这个改造下 https://eggjs.org/zh-cn/advanced/plugin.html#多实例

**Comment by atian25** [comment]
欢迎 PR

**Comment by iyuq** [comment]
多个数据源的话是不是 sequelize-cli 就不太好用了，改造的话倒是不难。

**Comment by atian25** [comment]
支持参数就好了吧?

**Comment by catalsdevelop** [comment]
sequelize-cli 可以通过config参数来配置，所以不用担心迁移问题。

**Comment by dead-horse** [comment]
egg-sequelize 4.x 已支持

**Comment by xifengyema** [comment]
多数据源typescript需要怎么配置呢？

**Comment by pwpow** [comment]
> 多数据源typescript需要怎么配置呢？

@xiaobaiyouxi 想请教一下，这里有解决方案了吗
