### ISSUE TITLE
accepts 写成了 accpets

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#1297]
accepts 写成了 accpets ，害我检查了半天，总是不生效!!!!

https://eggjs.org/zh-cn/plugins/onerror.html#usage

``` js
function accpets(ctx) {
--



```

**Comment by atian25** [comment]
thanks for report,  will landed at https://github.com/eggjs/egg-onerror/pull/22

**Comment by zlab** [comment]
@atian25  还有写错的 ！！

`x-requested-with`  

https://eggjs.org/zh-cn/plugins/onerror.html#usage
``` js
  if (ctx.get('x-request-with') === 'XMLHttpRequest') return 'json';

**Comment by zlab** [comment]
被坑了两次啊

**Comment by atian25** [comment]
其实你可以直接 PR 的

发自我的 iPhone
