### ISSUE TITLE
使用应用部署里推荐的启动方式，如果ssh客户端链接断掉，服务也会关闭。

### ISSUE THREAD

**Issue by BYmax1** [eggjs/egg#1299]
使用应用部署里推荐的启动方式，如果ssh客户端链接断掉，服务也会关闭。所以导致每次都必须exit退出一下，请问是为什么？

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/1055

**Comment by ngot** [comment]
You should learn more about ssh, linux process.
