### ISSUE TITLE
egg-userrole 使用 render 出错

### ISSUE THREAD

**Issue by poke3** [eggjs/egg#1301]
* **Node Version**: 8.1.4
* **Egg Version**: 1.7.0
* **Plugin Name**: egg-userrole
* **Plugin Version**: 1.1.2
* **Platform**: windows 10 x64
* **Mini Showcase Repository**:

使用 egg-userrole 做权限验证时，由于需求是要直接渲染成页面，参考了 koa-roles 的代码，并结合 Eggjs 官网对渲染页面的说明。

```
// app/config/role.js
app.role.failureHandler = async function(action) {
    switch (action) {
      case 'user':
        this.redirect('/login');
        break;
      case 'admin':
        this.body = await this.renderView('tips.html', { action }); // Can't set headers after they are sent.
        break;
      default:
        this.redirect('/login');
    }
  };
```

但由于 Eggjs 提供的三个渲染页面返回值均为异步，所以以上结果貌似都是在响应结束后进行赋值，但查看不到相关资料如何在响应结束前进行渲染并赋值。

**Comment by atian25** [comment]
koa-roles 貌似还不支持 async，你把 failureHandler 换为 generator function 方式试试

https://github.com/koajs/koa-roles/blob/master/index.js#L156

**Comment by poke3** [comment]
@atian25 可以啦，看来有时还得源码看过去才能得到答案呀。

**Comment by Nowforpasserby** [comment]
@atian25 请问一句，官方的orm是什么时候出来啊，有计划么

**Comment by atian25** [comment]
@Nowforpasserby https://github.com/eggjs/egg-sequelize

**Comment by atian25** [comment]
有兴趣的可以去给 `koa-roles` 提 PR 支持 async，这个 issue 先关了
