### ISSUE TITLE
egg-mysql 有没有 gt lt gte lte这类条件方式啊

### ISSUE THREAD

**Issue by pucumt** [eggjs/egg#1302]
egg-mysql的文档太简单，既然不推荐query，其他各种条件排序和aggregate方法有没有啊？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-sequelize

**Comment by pucumt** [comment]
是要用sequelize的方法，egg-mysql本身不支持，对吧？

**Comment by atian25** [comment]
gt 这些本来就属于 orm 层的，不属于 mysql 这一层的职责。

**Comment by pucumt** [comment]
非常感谢这么快回复。

可是用egg-sequelize的话，就不用安装egg-mysql了，那是不是意味着egg-mysql只能用在非常简单的项目上？

**Comment by atian25** [comment]
按需。
