### ISSUE TITLE
请问大大们有没有遇到过，egg渲染nunjucks模板时，服务器上耗时比本地还要久的情况？

### ISSUE THREAD

**Issue by Ryqsky** [eggjs/egg#1303]
环境：
node："6.10.1",
@ali/nut: "^3.0.0",
egg-view-nunjucks: "^2.1.2",

（egg默认开启模板缓存cache: true）

本地CPU：i5-4570 3.20 GHz 四核心 四线程核心
线上CPU：具体配置不清楚，应该是40核

本地打点日志：
renderTime=33`
renderTime=36`
renderTime=33`
renderTime=36`

线上打点日志：
renderTime=50`
renderTime=53`
renderTime=54`
renderTime=67`

是配置的原因？

**Comment by popomore** [comment]
都不知道你怎打点的，写个 benchmark 吧

https://github.com/eggjs/benchmark/tree/master/simple_view

**Comment by atian25** [comment]
关闭的时候最好说明下原因

**Comment by Ryqsky** [comment]
好的。就目前排查的情况，不仅仅是渲染nunjucks模板，而其他的一些函数方法（耗CPU，类似替换字符串）的执行时间，服务器上比本地都要慢。

初步确定：慢的原因应该和egg，nunjucks无关，应该是两个环境下整个Node的计算能力差异的问题

本来也想写个 benchmark ，但由于我拿不到线上或开发服务器的权限，只能发包更新，排查起来比较麻烦。而业务比较紧，这个问题我暂时先放下了，不然耽误很多时间。

后续假如我发现是什么原因造成的，我会在这里同步更新的。

**Comment by Ryqsky** [comment]
已经确认是由于Node版本问题导致这个原因。

由于uae的node默认版本是6.10.1（可能被修改过），升级到8.3.0后，渲染nunjucks模板就明显提升了。

**Comment by atian25** [comment]
> 可能被修改过

这个猜测不可能吧，本来 Node 8 就做了很多性能优化，快是正常的。
