### ISSUE TITLE
How can i generate migration scripts that contains my initial model with egg-sequelize?

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1304]
I have defined some models in ``app/models`` and I want to sync the models to the database with migration command.
Although I can ``app.model.sync({ force: true });``, but I don't think it's a good way to sync database because it will drop everything every time the program restart.
So I wonder is there any command for me to generate migration scripts so that I can build the database before start the server?

**Comment by iyuq** [comment]
There's no command for generate migration scripts, you need to write youself. You can see this project [sequelize-example](https://github.com/eggjs/examples/tree/master/sequelize-example).

**Comment by THaGKI9** [comment]
It's a sad story.
emmm...
Is there ways for me to initialize database before startup the server?

**Comment by catalsdevelop** [comment]
hi @THaGKI9. I think it's not the work about egg but sequelize. sequelize-cli has migration support such as seeder, schema, do/undo DML DDL etc. You can reach it http://docs.sequelizejs.com/manual/tutorial/migrations.html
