### ISSUE TITLE
egg 如何强制使用IPv4？

### ISSUE THREAD

**Issue by iwof** [eggjs/egg#1305]
* **Node Version**:"8.2.1"
* **Egg Version**:"^1.3.0"
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: centOS 7.0+（才会出现）
* **Mini Showcase Repository**:

我在阿里的服务器上（centOS 7.0+）搭建egg框架，默认监听IPv6的端口，导致前端无法访问。
尽管我已经禁用了centOS 上IPv6模块。
请问如何强制仅仅监听IPv4端口？

采用Egg-init 搭建的项目
项目下的index.js如下
'use strict';
// npm run dev DO NOT read this file

require('egg').startCluster({
  baseDir: __dirname,
  port: process.env.PORT || 9002, // default to 7001
});

附 express 框架的方案（
var http = require("http");
server.listen(9003, "0.0.0.0");
）

**Comment by atian25** [comment]
试下这个配置 https://eggjs.org/zh-cn/core/deployment.html#启动配置项

```js
// config/config.default.js
exports.cluster = {
  listen: {
    port: '7001',
    hostname: '127.0.0.1',
    // path: '/var/run/egg.sock',
  }
}
```

**Comment by iwof** [comment]
用最新的egg  配置文件 是这种格式了（修改后的demo可以监听IPv4）
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1502335764735_9505';

  // add your config here
  config.cluster = {
    listen: {
      path: '',
      port: 7000,
      hostname: '0.0.0.0',
    },
  };

  return config;
};

------------------------------
我现在的配置文件（部分）
module.exports = {
  cluster: {
    listen: {
      port: '7001',
      hostname: '0.0.0.0',
    }
  },

无效啊

**Comment by atian25** [comment]
没看懂你的回复想表达啥

**Comment by iwof** [comment]
你的建议是正确的，
cluster: {
listen: {
port: '7001',
hostname: '0.0.0.0',
}
这样确实可以强制使用IPv4
但是port设置是无效的
app_worker.js 14/15/16行
const clusterConfig = app.config.cluster || {};
const listenConfig = clusterConfig.listen || {};
const port = options.port = options.port || listenConfig.port;
options.port是默认有值的

——————————————————————————————————————
我前面之所以说 根据你的设置 导致强制使用IPv4无效，是因为启动方式如下：
"start": "cross-env PORT=9002 EGG_SERVER_ENV=local node index.js",
不好意思，给你添麻烦了

**Comment by atian25** [comment]
本地启动的话，建议用 `egg-bin dev`，线上用 `egg-script start --daemon`

可以用 egg-init 初始化一个 simple 看看 npm scripts 的配置。
