### ISSUE TITLE
使用redis做消息队列的问题

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1306]
我的场景是这样的，需要用redis的消息订阅模式，后台有个程序(消费者)一直监听消息队列的数据，如果有数据就保存到数据库然后通过websocket转发到客户端。然后生产者是一个采集数据的程序是通过TCP连接到传感器的。请问消费者的程序部分放在egg的哪儿呢，感谢

**Comment by solarhell** [comment]
参见 https://eggjs.org/zh-cn/core/cluster-and-ipc.html 
`ctx.runInBackground`

**Comment by acodercat** [comment]
不是很清楚ctx.runInBackground放在哪执行比较好呢，请详细说下思路，感谢

**Comment by dead-horse** [comment]
自己随便写哪里都行，只要能拿到 socket.io 的实例，能做推送就好了。例如放在 `app/core/consumer.js`，由 `app.js` 引入。

**Comment by acodercat** [comment]
我打算在agent里面做消息队列的消费者，从消息队列拿到数据以后发送给app，app再通过socket.io 的实例推送给客户端，然后用work来监听传感器的数据，拿到数据后放入消息队列。请问这个模式稳定吗

**Comment by laiyun1986** [comment]
@acodercat 我也在打算这么用，还没有实践不知道效果如何

**Comment by lawrence-peng** [comment]
@acodercat  方案里的 app是指的什么？这个方案用到生产了吗
