### ISSUE TITLE
feature request: egg-sequelize can customize log level.

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1307]
Currently egg-sequelize just put every log into INFO level logs, but I don't need these logs in production.

**Comment by solarhell** [comment]
In fact it has this feature.
You can simply set
```
exports.sequelize = {
  logging: false,
  ...
}
```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L8
