### ISSUE TITLE
config.plugin.js 可以用返回函数的方式吗？

### ISSUE THREAD

**Issue by kiinlam** [eggjs/egg#1308]
Q1、配置plugin时，想做些判断，能否像配置config.default.js那样用函数方式，同时接受传入的参数，如appInfo，我想在本地开发时启用某个插件，在生产环境禁用。

Q2、看了下框架的加载顺序，是不是拿plugin配置时还获取不到app信息。

Q3、这个plugin配置文件能进行程序调试的吗？

**Comment by atian25** [comment]
支持 `plugin.{env}.js`

**Comment by kiinlam** [comment]
使用vscode调试需要安装 egg-development-proxyworker 模块，说明文档要求安装在 dependencies 下。
既然config跟plugin都支持配置 local 环境，那不就可以安装到 devDependencies 下了。这样在生产环境就不需要安装这个调试模块了。

**Comment by atian25** [comment]
对的。
