### ISSUE TITLE
Worker的使用问题

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1309]
在文档中只看到了用定时器来使用Worker，在但是我想开启一个Worker 来开启一个TCP服务，怎么做呢

**Comment by ngot** [comment]
Worker 由框架控制，不要自己创建。可以放到 agent 里面去做。

**Comment by dead-horse** [comment]
egg 现在的定位是 http 服务，tcp 服务不是不能做，将请求的 handler 抽象一下，最终可以做到共用 egg 的逻辑层，入口可以是 http 也可以是 tcp 。
