### ISSUE TITLE
egg开发接口执行耗时较长任务，如何快速返回response

### ISSUE THREAD

**Issue by rrbe** [eggjs/egg#1310]
* **Node Version**: 6.0.0
* **Egg Version**: 1.6.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS Serria 10.12.3
* **Mini Showcase Repository**:

用egg开发一个接口，需要执行一个耗时较长的任务，希望向客户端返回类似
```
{
    result: "任务已开始，请耐心等候完成"
}
```
这样的信息。

在controller里直接设置res：`this.ctx.body={xxx}` 之后，直接提前返回res，即写上`this.ctx.res.end()`的话，会报`can't set header after they are sent`的错误。当然koa里面好像也是建议不要直接用底层的node api的，所以想问下，在egg里面关于这种情况有没有什么办法解决？

**Comment by popomore** [comment]
这次请求完成后你准备怎么返回剩下的数据

**Comment by ngot** [comment]
描述的这个不是 http 模型需要解决的问题。也不是web框架本身需要解决的问题。

response 返回后，再返回数据，这个模型，能不能描述清楚是什么目的。

**Comment by rrbe** [comment]
比如要拉取较多文件备份，请求过来以后只是发起这个动作，具体拉取成功与否的情况可以由服务端直接记录在数据库FetchLog这样的表里，如果失败了大不了再执行一次动作，所以不需要再向前端返回数据。不知这样说的是否清楚。谢谢！

**Comment by atian25** [comment]
用 `ctx.runInBackground` 即可。或者只是简单的往数据库记录一条 task，由 egg-schedule 定时执行。

**Comment by rrbe** [comment]
@atian25 在异常处理文档里看到了，确实解决了问题，谢谢！
另外，可以考虑把这个方法写在controller文档里作为一个例子吗？

**Comment by lshuoz** [comment]
> 用 `ctx.runInBackground` 即可。或者只是简单的往数据库记录一条 task，由 egg-schedule 定时执行。

请问这种场景怎么实现由egg-schedule定时执行

**Comment by chjiyun** [comment]
也可以 把后台执行的逻辑放到 另一个async方法，执行时不用await即可
