### ISSUE TITLE
runSchedule 会忽略 schedule type 的值为 worker

### ISSUE THREAD

**Issue by zbinlin** [eggjs/egg#1311]
当打开多个 worker 时，运行 `runSchedule('mySchedule')`，即使设置了 *mySchedule* 里 `schedule.type` 为 `worker`，仍然会在所有的 worker 执行 *mySchedule*，这是特意为之？

**Comment by dead-horse** [comment]
runSchedule 就是运行一次 schedule.task 指定的任务，不会管 shcedule 的配置。

**Comment by zbinlin** [comment]
如果开 8 个 work，运行一次任务，都会在这 8 个 work 里执行一次，这也没问题？

**Comment by popomore** [comment]
所以不要直接调用 runSchedule

**Comment by atian25** [comment]
@zbinlin 

`app.runSchedule(scheduleName) is provided by egg-schedule plugin only for test purpose.`

> 如果开 8 个 work，运行一次任务，都会在这 8 个 work 里执行一次，这也没问题？

我这边试了下，在 Controller 里面调用的话，并没有触发 8 次，如果还有问题，提供你的最小可复现代码。

**Comment by dead-horse** [comment]
> 如果开 8 个 work，运行一次任务，都会在这 8 个 work 里执行一次，这也没问题？

runSchedule 的意思就是执行一次 schedule 任务，不会管 shcedule 的配置，代码执行多少遍，任务就会执行多少遍。

**Comment by zbinlin** [comment]
@atian25 是在 app.js 的 `app.beforeStart` 里运行

**Comment by atian25** [comment]
那肯定 8 次啦... 每一个 worker 都是一个 app

**Comment by zbinlin** [comment]
@atian25 明白了，THX~
