### ISSUE TITLE
egg-redis使用egg-redis问题

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1312]
在app.js和agent.js里面使用redis的subscribe的时候，报错nodejs.ReplyError: ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / QUIT allowed in this context
折腾半天发现必须写在beforeStart里面，这是为什么呢，是不是都必须写在beforeStart里面呢

**Comment by atian25** [comment]
https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L48

要等待建联。

放到 `app.messenger.on('egg-ready', ()=>{});` 更好。

**Comment by acodercat** [comment]
在agent里的话是不是放在agent.beforeStart最佳

**Comment by atian25** [comment]
也有 `agent.messenger.once('egg-ready', ()=>{});`

整个事件流是：`beforeStart -> egg-ready`

只是应用的 `beforeStart` 按目前的加载顺序，是会跑在插件的 `beforeStart` 之后，所以你这样用没问题。从语义上来讲，还是 `egg-ready` 更好。

**Comment by popomore** [comment]
解决了吗

**Comment by acodercat** [comment]
解决了，写在了agent.messenger.once('egg-ready', ()=>{});

**Comment by acodercat** [comment]
可以把service也加在agent上不

**Comment by atian25** [comment]
你的场景是？ 不推荐在 agent 里面做复杂的业务

发自我的 iPhone

**Comment by acodercat** [comment]
agent里面做为redis消息队列的消费者，获取数据通过socket.io发给客户端，同时保存到数据库

**Comment by popomore** [comment]
Socketio 不用 egg 插件？

**Comment by acodercat** [comment]
用的啊
