### ISSUE TITLE
egg图片上传储存问题

### ISSUE THREAD

**Issue by ismeteor** [eggjs/egg#1313]
![image](https://user-images.githubusercontent.com/12558749/29248025-e7b3246a-803f-11e7-906e-272ebcd2215f.png)
按照官网的demo文档使用报如上错误。

**Comment by ismeteor** [comment]
result = yield ctx.oss.put(name, stream);
ctx上下文 没有oss对象

**Comment by atian25** [comment]
安装 egg-oss 插件没？
