### ISSUE TITLE
egg-multipart 使用 yield 可以获取数据 await 不可以 

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#1316]
* 这样可以获取数据
*test (ctx) {
  const stream = yield ctx.getFileStream();
  .....
  
};

* 这样获取不到数据
async test() {
  const stream = await ctx.getFileStream();
  .....
  
};

**Comment by atian25** [comment]
检查下代码？

从这里看是没区别的

https://github.com/eggjs/egg-multipart/blob/master/app/extend/context.js#L35
