### ISSUE TITLE
eggjs 不支持 es6  ...展开运算符

### ISSUE THREAD

**Issue by pansly004** [eggjs/egg#1317]
/Users/mamabang/Desktop/wanda-git/egg-example/app/controller/home.js:7
				...param,
				^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.loadFile (/Users/mamabang/Desktop/wanda-git/egg-example/node_modules/egg-core/lib/utils/index.js:18:19)
[Mon Aug 14 2017 21:46:51 GMT+0800 (CST)] [cfork:master:19592] worker:19596 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false)
[Mon Aug 14 2017 21:46:51 GMT+0800 (CST)] [cfork:master:19592] don't fork new work (refork: false)

* **Node Version**: v8.2.1
* **Egg Version**: ^1.7.0

**Comment by atian25** [comment]
你 node 的版本肯定不是 8

发自我的 iPhone

**Comment by llh1187** [comment]
> 你 node 的版本肯定不是 8 发自我的 iPhone
> […](#)
> 在 2017年8月14日，21:51，pansly004 ***@***.***> 写道： /Users/mamabang/Desktop/wanda-git/egg-example/app/controller/home.js:7 ...param, ^^^ SyntaxError: Unexpected token ... at createScript (vm.js:74:10) at Object.runInThisContext (vm.js:116:10) at Module._compile (module.js:533:28) at Object.Module._extensions..js (module.js:580:10) at Module.load (module.js:503:32) at tryModuleLoad (module.js:466:12) at Function.Module._load (module.js:458:3) at Module.require (module.js:513:17) at require (internal/module.js:11:18) at Object.loadFile (/Users/mamabang/Desktop/wanda-git/egg-example/node_modules/egg-core/lib/utils/index.js:18:19) [Mon Aug 14 2017 21:46:51 GMT+0800 (CST)] [cfork:master:19592] worker:19596 disconnect (exitedAfterDisconnect: false, state: disconnected, isDead: false) [Mon Aug 14 2017 21:46:51 GMT+0800 (CST)] [cfork:master:19592] don't fork new work (refork: false) Node Version: v8.2.1 Egg Version: ^1.7.0 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

不是吧
