### ISSUE TITLE
egg-static maxAge 无效

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#132]
config.default.js 配置文件中，设置maxAge无效。上传的图片后，无法访问/public/下资源

exports.static = {
    maxAge: 0
 };

**Comment by atian25** [comment]
抱歉, 消息丢了.

重启服务后, 就能访问到了?

**Comment by zhoudaqing** [comment]
@atian25   必须重新启动项目才能访问 修复了么 这个问题？

**Comment by atian25** [comment]
能否提供了最小的可复现问题的代码库看看

**Comment by atian25** [comment]
@dead-horse 看看, 是不是 static-cache 的原因?

> Caches the assets on initialization - you need to restart the process to update the assets.

https://github.com/koajs/static-cache

按这里的描述, 是 feature 不是 bug

**Comment by fengmk2** [comment]
> config.default.js 配置文件中，设置maxAge无效。上传的图片后，无法访问/public/下资源

egg-static 是启动时决定那些文件可以被 serve 的，不应该以本地磁盘存储文件的，你的服务器会变成多台的，这样文件上传也会访问不了。

还是走云存储吧。

这个不是 egg-static 的 bug，本来就不支持这种动态添加文件的功能。

**Comment by zhump** [comment]
那maxAge的值 在生产环境上就不能被改动？？

**Comment by atian25** [comment]
在 config.prod.js 修改。

**Comment by zhump** [comment]
在不是prod环境上，可以做到静态资源更新，为啥不在prod下开这个配置呢？

**Comment by atian25** [comment]
理由在上面写了，设计如此，基于性能的考虑啊。你可以去开启配置，如果你很清楚后果的话。

看下 egg-static 源码吧，看完你就知道了，百来行不到
