### ISSUE TITLE
`egg-validate`插件的校验规则中`required:false`无效

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1321]
后端校验规则：
![image](https://user-images.githubusercontent.com/5373111/29315569-68535ec0-81f6-11e7-8336-00058c204be7.png)

前端请求：
![image](https://user-images.githubusercontent.com/5373111/29315574-731261ee-81f6-11e7-82e3-1ab213fed52a.png)

接口返回值：
![image](https://user-images.githubusercontent.com/5373111/29315584-7a9fbbd2-81f6-11e7-8270-1f2f535219ae.png)

**Comment by xjchenhao** [comment]
半年前做一个`意见反馈`页面，也发现了同类问题。代码如下：

```
            const createRule = {
                title: {
                    required: false,
                    type: 'string'
                },
                email: {
                    required: false,
                    allowEmpty: true,
                    type: 'email',
                },
                content: {
                    type: 'string'
                },
            };
```
这个页面的，联系方式字段是选填的，如果填写了，则做一下邮箱格式的校验。但是因为`required:false`无效，我把这个字段限制成必填了😂 

过了大半年还是存在这个问题，太让人伤心。。

**Comment by MinJieLiu** [comment]
@xjchenhao 
我之前提过此类的问题
```
nickname: { type: 'string', max: 20, required: false, allowEmpty: true },
```

设置一个不必填的字段要配置4个键。相当麻烦。由于 `egg-validate` 依赖  `parameter` 这个库是  `node-modules` 写的，我也就不说什么了。反正我后面是坚决不用。我宁愿自己写一个库来验证。

**Comment by MinJieLiu** [comment]
我是认为不好用，配置不必填相当麻烦。

不必填的话要配置 `allowEmpty: true, required: false,`

因为 `egg-validate` 依赖的 `parameter` 这个库是 `node-modules` 写的，我没意见。反正我是不用，宁愿自己写一个验证库。

**Comment by atian25** [comment]
@xjchenhao 提供一个最小可复现代码，这种问题的定位我们一般是会写一个测试用例来复现，https://github.com/eggjs/egg-validate/blob/master/test/validate.test.js#L34

**Comment by atian25** [comment]
@MinJieLiu 欢迎来到开源世界。

`egg-validate` 不是内置到 egg 的，使用者可以自由选择用或不用。

就跟在其他项目一样，对于某个类库，如果不好用：
1. 跟类库的开发者提 issue，讨论改进方式
2. 如果达成共识，就一起推动类库的进化
3. 如果达不成共识，就选择其他的同类类库，如 [egg-validate-schema](https://github.com/eggjs/egg-validate-schema)
4. 如果没有同类类库，或也不符合需求，就自己造一个咯。

**Comment by dead-horse** [comment]
设计如此

**Comment by Measy** [comment]
@atian25 `egg-validate`的readme关于自定义添加验证规则是不是应该详细一些，比如addRule的第二个参数需要是个fun,fun的返回值有什么要求，什么返回情况下是验证通过，什么情况下是验证不通过

**Comment by atian25** [comment]
新的 RFC 里面有提到会做

发自我的 iPhone
