### ISSUE TITLE
关于部署的问题

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1322]
我用npm run dev来运行程序的时候，socket,io连接很稳定，一连接就连接上了，但是使用node index.js来运行的时候，socket.io触发error，部署到线上也就会出现这种老是连接不上的问题，偶尔又能连接上

**Comment by liujinyang1994** [comment]
[解决方案](https://stackoverflow.com/questions/41381444/websocket-connection-failed-error-during-websocket-handshake-unexpected-respon)

**Comment by acodercat** [comment]
不行

**Comment by acodercat** [comment]
好奇葩的问题啊，node index.js直接运行就socket.io就会断开重连，偶尔能练手， npm run dev运行就一点问题没有，百分百成功

**Comment by atian25** [comment]
npm run dev 是一个 worker 和 prod 模式

发自我的 iPhone

**Comment by atian25** [comment]
提供最小可复现代码

**Comment by dead-horse** [comment]
@acodercat 是因为 socket.io 没有接入 redis 之类的连接共享适配，导致在 cluster 模式下多个进程未共享连接么？

**Comment by ngot** [comment]
- socket.io 在多进程环境下需要自己解决 [sticky-session问题](https://www.google.com/search?q=sticky+session+socket.io&oq=sticky+session+so&gs_l=psy-ab.3.0.0j0i22i30k1l2j0i22i10i30k1.3971.5826.0.7169.5.4.1.0.0.0.325.872.2-2j1.3.0....0...1.1.64.psy-ab..1.4.878...0i67k1.BAlFGIgIRVE)
- 为什不使用 egg-socket.io ?

**Comment by acodercat** [comment]
是直接使用的 egg-socket.io

**Comment by acodercat** [comment]
用egg-scripts start --port=7002 --daemon --env=prod --worker=1
一个进程也不行

**Comment by ngot** [comment]
你需要解决确保 sticky-session， 你的方案是什么？

**Comment by ngot** [comment]
请提供具体信息，别挤牙膏式的浪费大家的时间

**Comment by atian25** [comment]
供最小可复现代码

**Comment by acodercat** [comment]
复现代码coder.cat:800/simple.zip 里面有个client是客户端，用node index.js运行egg然后用nodemon运行 client.js  不停的保存client.js，就会重新运行客户端代码，偶尔就会出现error，有时候还会很频繁

**Comment by acodercat** [comment]
我的环境是一台服务器，不是多台

**Comment by acodercat** [comment]
有时间能成功，有时候不成功。复现好难。。。

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io#deployment 没有按照文档配置。

还有，你有nginx转发吗，有按照文档配置吗？

请提供详细一些的信息，一问一答，挤牙膏太没效率了，别人的时间也很宝贵的。

**Comment by ngot** [comment]
确保`sticky-session`， 你有思考过这个问题吗？ 你需要确保你的整个负载系统都要做到，如果完全没有概念，需要重新review一下应用架构。

**Comment by acodercat** [comment]
感谢！我没有用nginx，单机跑的

**Comment by ngot** [comment]
按照文档配

**Comment by acodercat** [comment]
感谢，加上 sticky: true就好了，然后我看到最新的egg的simple模板里面没有index.js了，那sticky: true加在哪呢

**Comment by acodercat** [comment]
config.cluster = {
		sticky: true,
	  listen: {
	    port: '7002',
	    hostname: '127.0.0.1',
	    // path: '/var/run/egg.sock',
	  }
	}
这样吗

**Comment by ngot** [comment]
index.js 自己手写。模板只是用来偷懒初始化项目的。index.js 你可以写在任何地方。

**Comment by acodercat** [comment]
egg-scripts start  不支持--stricky

**Comment by ngot** [comment]
egg-bin dev 是支持的。

**Comment by atian25** [comment]
egg-scripts 应该也是支持的，都是透传过去的。

@ngot  `config.cluster.sticky` 支持下吧，然后文档也改改不要引导 index.js 了。

**Comment by ngot** [comment]
config 没办法支持的，因为这个是在master启动时用的，这时 config 的 loader 还没初始化呢

**Comment by liujinyang1994** [comment]
怪不得，我在部署的时候config 里面port 不生效。原来是这个原因。

**Comment by acodercat** [comment]
我也是

**Comment by ngot** [comment]
master process -> [agent process -> agent config loader ] -> [worker process -> worker config loader ] 大概这样的启动过程。

端口，sticky 等都在master里面

**Comment by atian25** [comment]
> 怪不得，我在部署的时候config 里面port 不生效。原来是这个原因。

port 是支持的，https://eggjs.org/zh-cn/core/deployment.html#启动配置项

因为 app 的时候已经 load config 了.

**Comment by atian25** [comment]
https://github.com/eggjs/egg-socket.io/pull/22

**Comment by acodercat** [comment]
感谢各位，经过不断的测试，终于解决了
