### ISSUE TITLE
egg router 与koa-router的关系是怎样的

### ISSUE THREAD

**Issue by chhenghua** [eggjs/egg#1323]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

最近在egg做项目，也是第一次尝试，基本上所有的东西都是挂载到app，感觉有点繁乱。

**Comment by atian25** [comment]
- egg 的 router 是对 koa-router 基础上做了一些 patch 和封装。可以看下 https://github.com/eggjs/egg-core/blob/master/lib/utils/router.js
- 乱么? 不觉得, https://eggjs.org/zh-cn/basics/objects.html
