### ISSUE TITLE
 本地window环境下  egg-init;  npm run dev  没有热加载

### ISSUE THREAD

**Issue by VanquisherMe** [eggjs/egg#1327]
![uuu o r s_gz 5qh6ny_fc](https://user-images.githubusercontent.com/4927398/29415364-659b217c-8395-11e7-8475-9dc53bbf6e6b.png)
node 8.3.0难道要降到6.*？

**Comment by atian25** [comment]
curl 或 postman 下排除浏览器缓存干扰

发自我的 iPhone

**Comment by popomore** [comment]
热加载可以看命令行

**Comment by VanquisherMe** [comment]
@popomore 请教下官方文档在什么地方实在没找到

**Comment by atian25** [comment]
他的意思是看控制台日志输出有没有重启日志

**Comment by VanquisherMe** [comment]
没有重启日志,没有输出任何东西，昨天尝试了降级到6.*，依然这样

**Comment by atian25** [comment]
换个 IDE 试试，有可能是 WebStorm 的那个 soft save 的问题。

**Comment by VanquisherMe** [comment]
换成 Sublime Text 3 ，git Bash，命令行输出日志了，但是没有热加载，浏览器需要手动刷新，如果就是这样可以关闭话题

**Comment by atian25** [comment]
那 WebStorm 你改下那个 Save 的策略即可。

浏览器手动刷新？ 你指的是 livereload ？ egg-development 只是 worker 重启而已，不负责 livereload，有需要的话自己写个插件。

**Comment by Hareis** [comment]
我的vscode  在命令行里面跑 npm run dev  改变文件后 不刷新
