### ISSUE TITLE
执行完controller里的逻辑之后还能执行中间件吗

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#1328]
* **Node Version**:v8.2.0
* **Egg Version**:v1.7.0
* **Plugin Name**:middleware
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
请问执行完controller里的逻辑之后还能执行中间件吗？如果能，该如何编写？

**Comment by atian25** [comment]
去理解下 koa 的洋葱模型吧，Controller 没啥特色的，它就是洋葱模型里面最里面的那个 Middleware 而已。
