### ISSUE TITLE
在config里边配置了一个不存在的middleware,然后在dev,test环境下运行都没问题，在prod环境下运行报错了

### ISSUE THREAD

**Issue by weivea** [eggjs/egg#1329]
* **Node Version ：v8.2.1**:
* **Egg Version v1.4.0**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform linux/mac OS**:
* **Mini Showcase Repository**:

在config里边配置了一个不存在的middleware,
然后在dev,test环境下运行都没问题，
在prod环境下运行报错了~
```
// config.default.js
config.middleware = ['errorHandler']; // 并不存在这个middleware
```

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/29442243-ef4e9b20-8402-11e7-9077-ab4e37b9179c.png)

无法复现，请提供最小化可复现代码。
