### ISSUE TITLE
egg-onerror support jsonp

### ISSUE THREAD

**Issue by beliefgp** [eggjs/egg#1330]
当egg-jsonp和egg-onerror共用时，当一个jsonp请求，抛出异常时，会由egg-onerror处理，这时就不会包上callback了

有个想法：
1. jsonp插件，开放出来包装方法，并且在请求时，在ctx上打个标记。
2. onerror检测到这个标记，调用包装方法。

可行？可以的话，我提个pr

**Comment by popomore** [comment]
如果是已知异常，就 try/catch 将错误信息设置到 ctx.body 上。

**Comment by beliefgp** [comment]
这样就和不用egg-onerror没什么区别了

**Comment by atian25** [comment]
onerror 主要用于未捕获异常的兜底处理。

https://github.com/eggjs/egg/issues/1086#issuecomment-323087428

**Comment by beliefgp** [comment]
我现在做法就是在ctx上加了throwError，可以设置是否记日志等，然后用egg-onerror来做汇总处理……

**Comment by beliefgp** [comment]
要用贯高说的单独一个中间件来做，确实也就解决了这个jsonp的问题，不过在根据相应内容做对应处理，是不是感觉和onerror重复

**Comment by popomore** [comment]
@beliefgp 这个算是解决了？

**Comment by beliefgp** [comment]
jsonp的pr已经合并，已经对外放出相关api了，这个稍微改下就可以了，这个你们来改，还是我有空提个pr

**Comment by atian25** [comment]
这个还搞么？

**Comment by fengmk2** [comment]
@beliefgp 继续搞完？

**Comment by beliefgp** [comment]
@fengmk2   额……千总……这两天我抽空改改
