### ISSUE TITLE
egg 支持graphql

### ISSUE THREAD

**Issue by wanganzhi1986** [eggjs/egg#1331]
如何使用egg作为graphql 的服务端？

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/468

**Comment by atian25** [comment]
好像社区之前有人发布了一个

**Comment by wanganzhi1986** [comment]
社区发布的应该是使用apollo, 不是基于relay的， relay的在客户端转换graphql模板时，需要利用relay-compile将schema转化成json格式，而schema是来自于服务端，利用到了egg中app.model,所以似乎是需要利用egg的框架去提供

**Comment by popomore** [comment]
apollo server 称是可以支持 relay 客户端的

**Comment by jtyjty99999** [comment]
已经发布 egg-graphql@1.0.0
