### ISSUE TITLE
请教下egg 怎么在 webstorm下调试【环境window】

### ISSUE THREAD

**Issue by VanquisherMe** [eggjs/egg#1332]
看了官网的调试，按照方式去做了但是没有调试起来，webstorm 【window环境】下是不能断点调试么？
window下想断点调试 应该采用哪种方式 比价好 谢谢

**Comment by atian25** [comment]
啥报错

发自我的 iPhone

**Comment by VanquisherMe** [comment]
没有报错 在controller里面打的断点也没停
![90ehgbt n5ki bo049xhfph](https://user-images.githubusercontent.com/4927398/29487274-41d15690-8529-11e7-8acc-1fcbebbb2c46.png)
![h xvj ib1t n jxu2_fdb](https://user-images.githubusercontent.com/4927398/29487331-cb75988e-8529-11e7-8b61-abb21b972eb7.png)

**Comment by atian25** [comment]
可以再看下文档，需要传递一个环境变量的

**Comment by VanquisherMe** [comment]
您指的是这样，这个环境变量的写法 好像mac才有用
![8_oj0ou 2iyo4 4 fq](https://user-images.githubusercontent.com/4927398/29487793-c2015cfe-8531-11e7-936b-e62a6d1118d6.png)

**Comment by atian25** [comment]
改为 win 的格式即可， %xx%

发自我的 iPhone

**Comment by VanquisherMe** [comment]
是这样？
![7wys6i fmavx8 0u99g i](https://user-images.githubusercontent.com/4927398/29495966-9d687f1a-85fb-11e7-9841-ff650416797e.png)

**Comment by atian25** [comment]
@okoala

**Comment by okoala** [comment]
@VanquisherMe 

Win下建议你使用 Node.js v8 以上版本，安装 [egg-development-proxyworker](https://github.com/eggjs/egg-development-proxyworker) 插件，使用 `egg-bin debug` 启动命令，在chrome 中打开这条链接进行调试 ![chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10087](chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10087)

**Comment by atian25** [comment]
@okoala win 下没法传递那个 options ?

**Comment by VanquisherMe** [comment]
@okoala 可以了，如果WebStorm 想在IDE内调试 只能是mac？ 文档提供的 "egg-bin dev $NODE_DEBUG_OPTION" 好像是 mac 下设置临时变量的方式。

**Comment by VanquisherMe** [comment]
@okoala 可以了，如果WebStorm 想在IDE内调试 只能是mac？ 文档提供的 "egg-bin dev $NODE_DEBUG_OPTION" 好像是 mac 下设置临时变量的方式。

**Comment by atian25** [comment]
这跟 node 没啥关系，属于操作系统知识，`$NODE_DEBUG_OPTION` 是 linux 的环境变量获取方式，win 下是 `%PATH%` 这样的。

**Comment by VanquisherMe** [comment]
egg-bin dev %NODE_DEBUG_OPTION%之前尝试过这样 没有跑起来，所以也比较好奇 win 的应该怎么写

**Comment by sunfuze** [comment]
windows 下用 set

**Comment by atian25** [comment]
这里不是要设置环境变量，而是要读取环境变量，然后传递给 bin 参数

**Comment by atian25** [comment]
@VanquisherMe 你升级下 egg-bin 最新版本，然后不用传递任何参数了，直接 `egg-bin debug` 试试。

文档那边也更新了，https://eggjs.org/zh-cn/core/development.html#使用-webstorm-进行调试

在 https://github.com/eggjs/egg-bin/pull/71 里面支持直接读取 WebStorm 的环境变量了.
