### ISSUE TITLE
egg-mongoose插件强制把mode名称首字母大写

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1333]
不建议这么做，应该由用户自己来定，我把 caseStyle: 'upper',去掉了。

**Comment by acodercat** [comment]
在mongoose的statics方法里面调用model的时候 ，也就是this.model('unitAdmin')，都是按照取用户命名的来读取的，这样就会造成不mode名称不统一

**Comment by iyuq** [comment]
应该是怕 model 名称和 mongoose 本身方法冲突吧，我猜。

**Comment by xxmyjk** [comment]
这个是mongoose的锅

**Comment by popomore** [comment]
约定大于配置，都按这种方式来定义 model 就一致了

**Comment by seekcx** [comment]
https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L96

他说的应该是这一段，确实这样不合适。什么service之类的都是小写，突然冒出一个大写，代码感觉怪怪的。

**Comment by weber-cd** [comment]
下划线也不行
