### ISSUE TITLE
session token 字段名设置未变化

### ISSUE THREAD

**Issue by VanquisherMe** [eggjs/egg#1334]
![b5c nex 49qc_b0d 6h p0](https://user-images.githubusercontent.com/4927398/29496001-559cbfc4-85fc-11e7-9984-a2df7a7c1e70.png)
![m529hlu sx6kjv 5b6 0](https://user-images.githubusercontent.com/4927398/29496003-5701aea6-85fc-11e7-9f12-e90083e012e5.png)

**Comment by popomore** [comment]
这文档在哪看的

**Comment by VanquisherMe** [comment]
https://eggjs.org/zh-cn/core/security.html
![xy q_5b4 36 wii4 4w r](https://user-images.githubusercontent.com/4927398/29496106-71ae59aa-85fe-11e7-90ff-b2d076ea912b.png)

**Comment by popomore** [comment]
这是两个东西，EGG_SESS 是 egg-session 设置的。这里是 `ctx.session.csrfToken`

**Comment by VanquisherMe** [comment]
@popomore thank you

**Comment by coderhsw** [comment]
token改成存到session中之后，前端用cookie获取这个EGG_SESS获取不到的吗
