### ISSUE TITLE
egg-sequelize 如何在 service 层获得全局实例

### ISSUE THREAD

**Issue by jamescheng16** [eggjs/egg#1335]
* **Node Version**: v8.4.0
* **Egg Version**: 1.7.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**:3.1.0
* **Platform**:Mac os
* **Mini Showcase Repository**: 
app/ 
|____service
| |____myService.js

现有需求是在 service 层调用sequelize 实例进行自定义查询
` var sqlQuery = 'abc';      
      return yield this.ctx.sequelize.query(sqlQuery, { raw: true });`

现在有错误 ： 
> nodejs.TypeError: Cannot read property 'query' of undefined

不知道如何获得 sequelize实例来自定义查询

**Comment by ngot** [comment]
提供下：Mini Showcase Repository

**Comment by jamescheng16** [comment]
|____service
| |____myService.js

在 myService.js 中
`

module.exports = app => {
  return class myService extends app.Service {
    
    * list(param) {
var sqlQuery = 'myQuery'; 
return yield this.ctx.sequelize.query(sqlQuery, { raw: true });
}};};`

**Comment by atian25** [comment]
有 ctx.squelize ？ 不是 ctx.model 么？

发自我的 iPhone

> 在 2017年8月21日，12:50，jamescheng16 <notifications@github.com> 写道：
> 
> sequelize

**Comment by iyuq** [comment]
没有`ctx.sequelize`, 只有`ctx.model`，使用`ctx.model`就好了。

**Comment by jamescheng16** [comment]
@iyuq 

ctx.model 可以进行自定义查询吗， 例如
`ctx.model.query(sqlQuery, { raw: true });`

**Comment by iyuq** [comment]
可以。
