### ISSUE TITLE
之前在哪看到一个写法是这样的const adminRouter = app.namespace('/admin');

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1336]
好像是egg的，但是尝试了一下，没有，可否考虑加上这样一个功能，现在的做法是在路由前面加上一prefix

**Comment by atian25** [comment]
这个功能没做，可以自己写个插件

发自我的 iPhone

**Comment by popomore** [comment]
这个死马准备做，但没想好怎么写

**Comment by atian25** [comment]
是这个吧 https://github.com/eggjs/egg/issues/882

做了一些然后暂停了
