### ISSUE TITLE
egg运行连接数据库报错，看图更详细

### ISSUE THREAD

**Issue by liuhuanhui** [eggjs/egg#1337]
![image](https://user-images.githubusercontent.com/10370625/29542269-67574c1e-870c-11e7-8d59-03913919db93.png)
![image](https://user-images.githubusercontent.com/10370625/29542285-84d71c7e-870c-11e7-8e78-27f27b088e4f.png)

**Comment by atian25** [comment]
不是写着你没安装 pg 么

发自我的 iPhone

**Comment by liuhuanhui** [comment]
sorry 上错图了 我在上一个~~

**Comment by liuhuanhui** [comment]
![image](https://user-images.githubusercontent.com/10370625/29542371-4090adfe-870d-11e7-9114-bb85d7786d78.png)

**Comment by liuhuanhui** [comment]
经过测试mysql可以 postgre不行

**Comment by popomore** [comment]
你可以直接用 sequelize 这个例子试试，感觉是他本身的问题
