### ISSUE TITLE
egg-mysql 如何支持类似egg-sequelize多出 一层model的方式

### ISSUE THREAD

**Issue by VanquisherMe** [eggjs/egg#1338]
阅读官网 egg-mysql 的是将mysql写在 Service 层里面，不是很清楚怎么实现在 Model层里面，这样能够比较清楚的管理sql
例如:https://github.com/eggjs/examples/tree/master/sequelize-example

**Comment by popomore** [comment]
那为何不用 sequelize

**Comment by VanquisherMe** [comment]
是很想用，才疏学浅没太看明白 不知道能不能 给一个 egg- sequelize ，原始查询的例子

**Comment by popomore** [comment]
你发的不就是例子呢，还需要什么？

**Comment by VanquisherMe** [comment]
![s1lvru3o273as2plg 4ktp](https://user-images.githubusercontent.com/4927398/29718671-204a259e-89e6-11e7-9777-5659015c6978.png)
类似这样的 app.Sequelize == Sequelize 的吧
那入文档就因该是
app.Sequelize.query('SELECT...') ？

**Comment by iyuq** [comment]
[sequelize-example](https://github.com/eggjs/examples/tree/master/sequelize-example)
