### ISSUE TITLE
有没有在router加载之前执行类似app.beforeStart的机制

### ISSUE THREAD

**Issue by linxxx3** [eggjs/egg#1340]
* **Node Version**: any
* **Egg Version**: any
* **Plugin Name**: egg-socket.io
* **Plugin Version**: 2.1.0
* **Platform**:
* **Mini Showcase Repository**:

我在app/extend/application.js 中定义了一个加载antx.properties的函数，并在 app.js里的 app.beforeStart函数中调用，工作的很好。

最近碰到一个问题，使用egg-socket.io，结合socket.io-redis插件，需要在router中加载redis配置。然后发现router加载时，app.beforeStart还没有执行，读不到redis配置。

我能想到的解法，只有把这个加载properties功能写成插件，这个略麻烦，有没有简单点的思路？

**Comment by atian25** [comment]
antx.properties 用 begg ，在内网沟通

发自我的 iPhone

> 在 2017年8月22日，17:53，linxxx3 <notifications@github.com> 写道：
> 
> antx.properties
