### ISSUE TITLE
config.prod 中可以使用异步方法获取配置信息吗

### ISSUE THREAD

**Issue by hbrls** [eggjs/egg#1342]
* **Node Version**:
-
* **Egg Version**:
-
* **Plugin Name**:
-
* **Plugin Version**:
-
* **Platform**:
-
* **Mini Showcase Repository**:
-

config.prod 中可以使用异步方法获取配置信息吗？
典型的情况是，有些配置项是在配置中心的，需要去 curl 一个接口获得值。
如果在 config.prod 中写异步方法，大概是个什么加载顺序，什么时候我能保证代码一定能读到这些配置项？

**Comment by atian25** [comment]
app.beforeStart(promise) 挂到 app.config 即可

发自我的 iPhone

**Comment by hbrls** [comment]
这个怎么处理只在 prod 执行呢，自己写 if 吗

**Comment by fengmk2** [comment]
config.prod.js 是配置文件，请不要做逻辑操作。

**Comment by hbrls** [comment]
有一些配置是在配置中心的，我们之前的做法是 http 去取，在这种场景下建议怎么处理呢

**Comment by dead-horse** [comment]
在 `app.js` 中实现 https://eggjs.org/zh-cn/basics/app-start.html

**Comment by fomenyesu** [comment]
@hbrls  异步处理配置文件 了解一下。
// {app_root}/app.js
module.exports = app => {
  app.beforeStart(async () => {
    // obtain the MySQL configuration from the configuration center
    // { host: 'mysql.com', port: '3306', user: 'test_user', password: 'test_password', database: 'test' }
    const mysqlConfig = await app.configCenter.fetch('mysql');
    app.database = app.mysql.createInstance(mysqlConfig);
  });
};
