### ISSUE TITLE
为什么模型名一点要用大驼峰命名法呢

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1343]
egg-sequelize强制把模型名转成了大驼峰，请问表名和模型所在的文件名也需要同样的命名方式吗

**Comment by iyuq** [comment]
不需要，模型名转成大驼峰应该是避免表明和 sequelize instance 方法属性名冲突。

**Comment by liuliangjia** [comment]
有没有配置项，可以去掉这个强制？

**Comment by popomore** [comment]
因为 Model 是类而非实例，设计如此

https://github.com/eggjs/egg-sequelize/pull/4#issuecomment-281328927
