### ISSUE TITLE
如何让egg支持https?

### ISSUE THREAD

**Issue by hulonghui106** [eggjs/egg#1344]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

查看了FAQ，及各种资料，似乎没有怎么启用HTTPS的，是不是不建议这么做？而是在Nginx上开启HTTPS？

**Comment by atian25** [comment]
egg-cluster 去参可以传递的，通过 egg-scripts 透传即可。一般来说都是在 Nginx 那层去做的。

发自我的 iPhone

**Comment by hulonghui106** [comment]
试了，确实可以，谢谢。
"start": "egg-scripts start --daemon --port=443 --https=true --key='xxxxx.key' --cert='xxxxx.crt'",

**Comment by walton007** [comment]
@hulonghui106   你这么写不正确 建议这么写
"start": "egg-scripts start --daemon --port=443 --https.key='xxxxx.key' --https.cert='xxxxx.crt'",
因为--https=true会被解析成https='true' 变成string

**Comment by oneWalker** [comment]
> @hulonghui106 你这么写不正确 建议这么写
> "start": "egg-scripts start --daemon --port=443 --https.key='xxxxx.key' --https.cert='xxxxx.crt'",
> 因为--https=true会被解析成https='true' 变成string

可以问下key和crt文件是自己生成的吗还是用的框架自带的

**Comment by pxim** [comment]
![image](https://user-images.githubusercontent.com/5111701/103499037-a8857b80-4e81-11eb-8b59-96cc238b0a27.png)

**Comment by pxim** [comment]
我现在用nginx转发，暂时解决了。

**Comment by atian25** [comment]
> ![image](https://user-images.githubusercontent.com/5111701/103499037-a8857b80-4e81-11eb-8b59-96cc238b0a27.png)
> 我这样写，报错了，是我证书有问题，还是什么原因呢；我用的是Nginx的证书，把后缀名.pem 删掉了

要用 ssh key 的证书

**Comment by pxim** [comment]
> > ![image](https://user-images.githubusercontent.com/5111701/103499037-a8857b80-4e81-11eb-8b59-96cc238b0a27.png)
> > 我这样写，报错了，是我证书有问题，还是什么原因呢；我用的是Nginx的证书，把后缀名.pem 删掉了
> 
> 要用 ssh key 的证书

了解了，谢谢
