### ISSUE TITLE
请问使用mysql.query方法时候，如何使用日期格式化函数

### ISSUE THREAD

**Issue by 156520783** [eggjs/egg#1345]
各位好，
新手一枚。
请问，类似下面的sql文，如何实现。用mysql.query时候，认不出DATE_FORMAT

SELECT
	b.item_name ,
	c.`name` ,
	DATE_FORMAT(
		a.create_date ,
		'%Y年%m月%d日 %H:%i:%s'
	) ,
	a.point_price
FROM
	t_order AS a ,
	t_order_detail AS b ,
	t_beautician AS c
WHERE
	a.id = '000000005e02ec1c015e05496c590007'
AND a.id = b.order_id
AND a.beautician = c.id

**Comment by kylezhang** [comment]
这样的代码阅读起来太费劲了，请整理下。

**Comment by 156520783** [comment]
简化一下，如下sql语句，使用mysql.query方法执行后，发现貌似不识别DATE_FORMAT。
请问这种情况下，该如何调用eggjs的mysql方法进行查询。谢谢
SELECT
DATE_FORMAT(a.create_date ,'%Y年%m月%d日 %H:%i:%s') 
FROM
t_order AS a

**Comment by popomore** [comment]
你为啥不查出来再转？

**Comment by popomore** [comment]
和框架无关
