### ISSUE TITLE
写在路由上的中间件如何获得某个请求对应的controller

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1346]
开发团队你们好。

我在写权限管理系统，希望用户访问某api的时候，可以先经过中间件判断一下用户权限。（我使用了官方推荐的`egg-userrole`，当然这不是重点；）

我给每一个controller设置了一个唯一的权限标识。**我希望用户在访问某api经过这个中间件的时候，能够知晓这个用户要去往哪个controller**，然后去数据库查询这个用户ID和这个controller的唯一标识，判断这个用户是否有权限访问。

![image](https://user-images.githubusercontent.com/5373111/29597484-6766880c-87f5-11e7-8953-bef7c3808e05.png)

我在中间件中打印了this，并没有找到我想要的。

希望大神能指点一二。谢谢🙏

**Comment by atian25** [comment]
数据库查询应该在 userrole 的定义里面。

你自己定义一个函数就行了

function myget(url, key) => app.get(url, role.can(key), key)

发自我的 iPhone

**Comment by xjchenhao** [comment]
谢谢作者回复～

代码不是很理解，但是大致意思应该是下图这样吧。

`router.js`
![image](https://user-images.githubusercontent.com/5373111/29601525-952d71f6-880e-11e7-93fc-9873e387927b.png)

这样是不是意味着restful没办法很好的指定key了？我用到了`app.resources`。理论上*上面代码箭头标识的这几个路由*还要再做细分。例如第一行的`authUser`，我需要细分成`auth.user.index`、`auth.user.create`、`auth.user.destroy`、`auth.user.edit`、`auth.user.update`等。

我需要把`app.resources`拆分成多个router语句吗？还是有其它比较方便的方式？

**Comment by popomore** [comment]
userrole 有点简陋，中间件模式无法分的这么xi

**Comment by xjchenhao** [comment]
好的 谢谢 那我暂时先分成多个router语句写把。。

**Comment by atian25** [comment]
或者你可以考虑自己写个 `app.resources` 来实现你的目的, 挂到 extend/application 即可.
