### ISSUE TITLE
请问怎么配置shtml不过滤style属性，且给style设置白名单属性？

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#1347]
开发团队你们好。
请问怎么配置shtml不过滤style属性，且给style设置白名单属性？
```
security: {
       domainWhiteList: ['xx.com', 'xxx.com']，
       whiteList: {
           span: ['class', 'style']
       },
       css: {
          'font-size': true
       }
 }
```

**Comment by jtyjty99999** [comment]
请参考https://eggjs.org/zh-cn/core/security.html#stored-xss

**Comment by logzh** [comment]
@jtyjty99999 这个文档我参考了，发现按照我上面的配置还是不正确呀

**Comment by logzh** [comment]
解决了
```
    security: {
        domainWhiteList: ['xx.com', 'xxx.com']
    },
    helper: {
        shtml: {
            whiteList: {
                span: ['class', 'style']
            },
            css: {
                whiteList:{
                  'font-size': true
                }
            }
        }
    }
```

**Comment by fengmk2** [comment]
@jtyjty99999 将这个 issue 案例整理到文档里面？

**Comment by jtyjty99999** [comment]
好的

**Comment by miaolin1993** [comment]
@logzh  我参照这种方式试了下 没有效果，目前还不知道是什么原因

  helper: {
    shtml: {
      whiteList: {
        span: ['style', 'class'],
        p: ['style', 'class'],
        ul: ['data-checked']
      },
      css: {
        whiteList: {
          'font-size': true,
          color: true,
        }
      }
    }
  }
