### ISSUE TITLE
egg-mongoose好像只能配置一个数据库啊，可以配置多个吗，是不是不支持

### ISSUE THREAD

**Issue by mickeyzhou** [eggjs/egg#1348]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by xxmyjk** [comment]
@mickeyzhou 看这里, [mongodb connection string](https://docs.mongodb.com/manual/reference/connection-string/)

**Comment by mickeyzhou** [comment]
这个是数据库集群，其实是同一个库的不同主机，如果我要连不同的数据库怎么配置啊

**Comment by mickeyzhou** [comment]
我的需求是，连一个mongodb主机上的不同mongo数据库
