### ISSUE TITLE
模板渲染时如何跟踪静态资源的构建？

### ISSUE THREAD

**Issue by gejiawen** [eggjs/egg#1350]
问题：

要进行渲染的模板中，引用了一些静态资源。项目在部署时，需要对静态资源进行构建。那么模板中对静态资源的引用如何保持？

在官网上找了挺久，没看到有描述这个问题的。

望回复。

**Comment by logzh** [comment]
如果是webpack构建静态文件，可以使用assets-webpack-plugin生成assets.json映射文件，在view中使用即可

**Comment by popomore** [comment]
你写个 helper 读取 assets.json 即可，这个问题属于前端问题，
