### ISSUE TITLE
Egg 文档对于 curl 入参缺少 nestedQuerystring 的介绍

### ISSUE THREAD

**Issue by hyj1991** [eggjs/egg#1351]
使用社区最新版本的 egg 做前后端分离方案的时候遇到了一个问题，在 service 文件中使用如下代码传递 post 请求：

```js
yield this.ctx.curl(`http://apiserver_url`, { method: 'post', data: { user: { name: 'hyj' } }, dataType: 'json'});
```
然后另外的负责接收请求的 apiserver (也是基于 Egg 开发的) 对应的路由处理 Controller 中使用如下代码侦听消息:

```js
*someMethod(){
    const { ctx, service, app } = this;
    const postData = ctx.request.body;
    console.log(postData);
}
```

这样子得到的结果，postData 的值为 ```{ user: '' }```，post 对象参数传递过程中 user 属性对应的对象变成了一个空字符串。

后来 debug 了下代码，发现是在 curl 依赖的 urllib 库中对于对象多层级嵌套的传参需要增加 **nestedQuerystring: true** 的配置：

```
yield this.ctx.curl(`http://apiserver_url`, { method: 'post', data: { user: { name: 'hyj' } }, dataType: 'json', nestedQuerystring: true});
```

时才能正常被 ```ctx.request.body``` 解析到。

而这个 curl 的配置参数在 egg 的文档里没看到，我觉得 post 传递嵌套对象也是比较常见的需求吧，建议在 [EggApplication.html#curl](https://eggjs.org/api/EggApplication.html#curl) 中增加 **nestedQuerystring** 的说明，或者在文档里向开发者注明 curl 调用的是 urllib，支持的入参参见 urllib 的文档这样子比较好。

参考资料:
[EggApplication.html#curl](https://eggjs.org/api/EggApplication.html#curl)
[urllib](https://www.npmjs.com/package/urllib)

**Comment by ngot** [comment]
欢迎来个PR

**Comment by hyj1991** [comment]
@ngot 这个不算是代码的 bug，是文档没有介绍关键的参数，文档没放在 github 上吧，没法提 pr ...

**Comment by ngot** [comment]
https://github.com/eggjs/egg/tree/master/docs/source/zh-cn
