### ISSUE TITLE
How get router params in middleware?

### ISSUE THREAD

**Issue by shanelau** [eggjs/egg#1354]
In middleware, `this` == `ctx`,  but could not get `params` object.

```
// app/middleware/uppercase.js
module.exports = () => {
// url == /api/user/:id
  return function* (next) {
    const id = this.params || this.req.params;  // undefined
    yield next;
  };
};
```

* **Node Version**: 8.0
* **Egg Version**:  1.7.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by coolicer** [comment]
this.req.params ?

**Comment by atian25** [comment]
`param` is a feature of router, so you can't got it before router

发自我的 iPhone

**Comment by shanelau** [comment]
@atian25 Can i put my middleware behind the router?
I need do some url params or query params check in middleware.

**Comment by atian25** [comment]
you can got `query` in any middleware, except param which extract from url path.


发自我的 iPhone

**Comment by coolicer** [comment]
@atian25 文档那个例子跑不了的，在middleware的时候只能读query，但是在route的时候，query是读不到的

**Comment by fengmk2** [comment]
Add middleware after router, then you can the `this.params`.

```js
// app/router.js

const uppercase = app.middlewares.uppercase();

app.get('/api/user/:id', uppercase, 'your controller here');
```

**Comment by shanelau** [comment]
Awesome!!

**Comment by EdisonSu768** [comment]
@fengmk2 same as get params in working url...
