### ISSUE TITLE
egg-sequelize 如何不启用created_at,updated_at ？

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#1356]
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('v2SignUp', {
    signUpId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      field: 'signUpId'
    },
.....................
    timestamps: true,
    createdAt: false,
    updatedAt: false,
    paranoid: true,
    deletedAt: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'deletedAt'
    }
  }, {
    tableName: 'v2_sign_up'
  });
};

还是会生成：
sql: 'INSERT INTO [v2_sign_up] ([title],[description],[beginAt],[endAt],[canSignUpAreas],[canSignUpStages],[canSignUpSubjects],[createdBy],[createdAt],[created_at],[updated_at]) OUTPUT INSERTED.* VALUES (N\'111111111111\',N\'aaa\',N\'2017-08-24 00:00:00.000 +08:00\',N\'2017-08-25 00:00:00.000 +08:00\',N\'市直,澄海区,南澳县\',N\'高中,初中,小学\',N\'全部,道德与法治\',1,\'2017-08-25 21:16:11.477 +08:00\',N\'2017-08-25 21:16:11.000 +08:00\',N\'2017-08-25 21:16:11.000 +08:00\');' },
  original:
   { RequestError: Invalid column name 'updated_at'.

**Comment by liuliangjia** [comment]
哦，自己解决了，出现这个错误。

**Comment by popomore** [comment]
自己看 sequelize 文档吧

**Comment by liuliangjia** [comment]
搞清楚了，sequelize本身有个bug，导致日期时间转换出错。
