### ISSUE TITLE
请问如何同步读写本地文件，框架有没有提供相应方法？

### ISSUE THREAD

**Issue by 156520783** [eggjs/egg#1357]
如题，谢谢。
另外，想请假一下，使用第三方模板的时候，异步的如何改为同步方式，有没有统一的方式。

**Comment by ngot** [comment]
readFileSync

**Comment by ngot** [comment]
另外请按照模板写issue,看不明白你的问题

**Comment by 156520783** [comment]
不好意思，下次注意，谢谢。

**Comment by atian25** [comment]
node 自带。

为什么要同步？

发自我的 iPhone

**Comment by x-cold** [comment]
Document: https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfilesync_file_options
