### ISSUE TITLE
egg-Sequelize 添加外键约束失败

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1358]
ERROR 1892 nodejs.SequelizeDatabaseError: Cannot add foreign key constraint

**Comment by acodercat** [comment]
发现如果在模型里面写.sync({force: true});就会出现这个错，把同步写在` app.beforeStart(function* () {
    yield app.model.sync({force: true});
  });`里就不会

**Comment by popomore** [comment]
需要把模型都定义好才可以同步
