### ISSUE TITLE
egg-view-swig 设置filter

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1360]
* Plugin Name: egg-view-swig
* Plugin Version: 1.4.2

我看到源码下的测试有filter相关的。
```javascript
// app/extend/filter.js
exports.hello = name => `hi, ${name}`;
```
但是我并没有找到源码中有涉及到filter的相关设置。
是egg在这方面已经有所计划。
还是说egg推荐我们使用helper来进行操作。

@atian25

**Comment by atian25** [comment]
swig 官方都不维护了，推荐改为 nunjucks 之类的引擎库吧。

如果有需要可以参考 nunjucks 的 https://github.com/eggjs/egg-view-nunjucks/blob/master/lib/environment.js#L54 提个 PR，或者在自己的 app.js 里面 load 下即可

**Comment by liujinyang1994** [comment]
我来提一个PR吧

**Comment by liujinyang1994** [comment]
@atian25 OK了。
