### ISSUE TITLE
pathFor 如何生成 resource 路径？

### ISSUE THREAD

**Issue by MiYogurt** [eggjs/egg#1361]
app.resources('adminUrls', adminPrefix + '/url', 'admin.url');

{{ helper.pathFor('adminUrls') }}

没有正常工作，哪错了？文档给的就是这样啊 。

![image](https://user-images.githubusercontent.com/10082395/29763796-3ba152c2-8c07-11e7-82e2-7525c48e7445.png)

**Comment by fengmk2** [comment]
@MiYogurt 尝试排查一下？如果一天内没结果，明天 @atian25 @dead-horse 来解决。

**Comment by atian25** [comment]
@MiYogurt 可以看看 https://github.com/atian25/egg-showcase/pull/2

**Comment by MiYogurt** [comment]
@atian25 恩，现在可以了。

**Comment by atian25** [comment]
那之前是出什么问题了？

**Comment by cksa** [comment]
我也遇到这个问题，弄了一晚上终于弄明白了，原来是一种约定 https://eggjs.org/zh-cn/basics/router.html#restful-风格的-url-定义
