### ISSUE TITLE
如何生成 accesslog？

### ISSUE THREAD

**Issue by xbf321** [eggjs/egg#1362]
由于 nginx 和 web 不是在一台机器上，web 的 accesslog 怎么处理呢？

是自己用 loger 添加？还有后续有计划推出一个插件？

**Comment by atian25** [comment]
自己写个插件挂个 middleware 然后记个 custom logger 即可

发自我的 iPhone

**Comment by xbf321** [comment]
@atian25 自己写倒是没问题，就是项目一多，这个文件拷来考去的，并且都是通用的，是不是做出一个这样的插件，比较好呢？

**Comment by atian25** [comment]
没说要拷贝啊，你可以写一个这个的插件，然后开源出来就好了。

egg 是开源项目，不用任何插件都等官方的，自己写就好了。当年怎么玩 express / koa 中间件的，现在还是怎么样玩 egg 插件。

**Comment by xbf321** [comment]
@atian25 好的，明白了，谢谢~
