### ISSUE TITLE
egg-oss 未能正常返回result对象

### ISSUE THREAD

**Issue by libchaos** [eggjs/egg#1363]
* **Node Version**: 8.4.0
* **Egg Version**: 1.6.1
* **Plugin Name**: egg-oss
* **Plugin Version**: 1.0.2
* **Platform**: osx
* **Mini Showcase Repository**:

![](http://7xojpa.com1.z0.glb.clouddn.com/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/8151a36a607543ad45b0a4ffc7dbb44b.png)

如上图debug框中所示，result 是一个put类型的，状态是挂起的
```javascript
//config.defautl.js
  config.oss = {
    client: {
      accessKeyId: 'xxxx',
      accessKeySecret: 'xxxx',
      bucket: 'xxxx',
      endpoint: 'oss-cn-beijing.aliyuncs.com',
      timeout: '60s'
    }
  }
```
```javascript
//plugin.js
exports.oss = {
  enable: true,
  package: 'egg-oss'
}
```

**Comment by libchaos** [comment]
egg-oss oss.put 是一个generator，怎么样把它转成promise呢？

**Comment by atian25** [comment]
co


发自我的 iPhone

**Comment by libchaos** [comment]
其实ali-oss自带有Wrapper属性，可以async方式执行，希望egg-oss改一下，让两者兼容

**Comment by atian25** [comment]
求 PR

发自我的 iPhone

**Comment by atian25** [comment]
@libchaos 重新安装下依赖就可以了
