### ISSUE TITLE
node 小于 7.6版本 async 支持问题

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1364]
作者你好！
我node版本是6.6.0，因为种种原因暂时不能升级到node 7.6以上，项目中有些中间件想用async。
所以我在项目中新建了自定义入口app.js 最上面加上了
require('babel-register')({
	plugins: ['transform-async-to-generator'],
})

这样做之后 controller service 里面都可以用async了，但是 app.js 里面和 extend/application.js 里面不行。  

想请教一下像我这种情况解决方案有哪些？？或者babel 应该放在那里最合适？？

**Comment by popomore** [comment]
不推荐使用 node 不支持的特性，请升级 node。

可以使用  https://github.com/cnpm/nodeinstall 来安装 node，服务器不需要安装。

**Comment by atian25** [comment]
如果是因为服务端全局 node 版本的问题，可以用 @popomore 提到的方式，把需要的 node 版本直接安装到 node_modules 即可，egg-scripts 会使用这个版本启动的。

如果是其他原因，那只能你自己解决了，譬如用 babel 把所有代码转译到新目录再启动。
