### ISSUE TITLE
egg-sequelize  migrate  :Error: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by ChitaGideon** [eggjs/egg#1369]
* **Node Version**:
v8.4.0
* **Egg Version**:
    "egg": "^1.4.0",
* **Plugin Name**:
"egg-sequelize": "^3.1.0",
* **Plugin Version**:
"egg-sequelize": "^3.1.0",
* **Platform**:
imac
* **Mini Showcase Repository**:
https://github.com/ChitaGideon/examples/tree/master/sequelize-example

```
git:(master) npm run migrate:new

> egg-vue-webpack-boilerplate@2.0.0 migrate:new /Users/yang/project/****
> egg-sequelize migration:create


Sequelize [Node: 8.4.0, CLI: 2.8.0, ORM: 4.6.0]

Successfully created migrations folder at "/Users/yang/project/****/migrations".
Error reading "node_modules/egg-sequelize/lib/database.js". Error: TypeError: Path must be a string. Received undefined

```

数据库用的是  sqlite  ，运行创建迁移命令报错

**Comment by huacnlee** [comment]
https://github.com/ChitaGideon/examples/blob/master/sequelize-example/config/config.default.js#L13

代码实现问题

前面需要  `const path = require('path')`

**Comment by ChitaGideon** [comment]
@huacnlee  例子写错了 


加上path  抱错如下

```
**Sequelize [Node: 8.4.0, CLI: 2.8.0, ORM: 4.7.5]

Successfully created migrations folder at "/Users/yang/git/examples/sequelize-example/migrations".
Error reading "node_modules/egg-sequelize/lib/database.js". Error: ReferenceError: app is not defined

**
```

**Comment by atian25** [comment]
某个 config 文件里面有调用 `app`?

**Comment by huacnlee** [comment]
首先应该是用 appInfo 而不是 app，你上面声明的是 appInfo


其次，这个场景你不能获取 appInfo.baseDir 的信息，因为 migration 的流程不是标准的 Egg 执行流程，而是 sequelize-cli 的环境，所以你不能那么写。

**Comment by atian25** [comment]
另外，https://github.com/eggjs/egg-sequelize/blob/master/lib/database.js#L11

这里感觉有点问题，手动加载 config 的，感觉不妥。

cc @huacnlee @popomore

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/30305317-cb71eb48-97a4-11e7-8df3-7acab86d9cac.png)

@huacnlee 这几个变量，感觉都是可以模拟的，不用传空。

- `baseDir` 就取 cwd 吧
- `pkg` 取 cwd 下的 package.json

**Comment by ChitaGideon** [comment]
是应该用appinfo，我写例子太疏忽了

实际中  项目config里的配置肯定是和migration 共用的，不太可能用migration 的时候config 写一个，然后migration完了再改回去

**Comment by atian25** [comment]
可以按我楼上说的优化下

**Comment by ZQun** [comment]
@atian25 

你好，现在遇到情况是，运行：npm run migrate:new

只要config.default.js  config.prod.js 配置文件内含有调用path.join()

就会报这个错误：Error reading "node_modules/egg-sequelize/lib/database.js". Error: TypeError: Path must be a string. Received undefined

包括你们在上面谈论的sequelize-example，我也有测试，default或prod配置文件内含有path.join，就会有报错

**Comment by leo2014** [comment]
@ZQun 
migrate命令没有在egg执行流程，config获取没有appInfo，造成path.join使用appInfo.baseDir时错误，加上判断初始化下appInfo，可以解决：
  
`  
if (!appInfo.baseDir) {
    appInfo.baseDir = '';
  }`

**Comment by wsdqr001** [comment]
@ChitaGideon @atian25 我遇到一个问题，dev环境下sqlite读写正常，但是部署到生产环境后报错：

2019-11-07 19:05:12,332 ERROR 64995 nodejs.SequelizeDatabaseError: SQLITE_ERROR: no such table: systemSetting
    at Query.formatError (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:422:16)
    at Query._handleQueryResponse (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
    at afterExecute (/app/bff/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)
    at replacement (/app/bff/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/app/bff/node_modules/sqlite3/lib/sqlite3.js:16:21)
name: "SequelizeDatabaseError"
parent: {"errno":1,"code":"SQLITE_ERROR","sql":"SELECT `id`, `uuid`, `name`, `creator`, `alarmType`, `errorHandle`, `linkUserIds`, `smsUsers`, `mailUserIds`, `proxyAlarmValue`, `proxyAlarmFrequency`, `apiCheckAlarmValue`, `apiCheckAlarmFrequency`, `cpuAlarmValue`, `memAlarmValue`, `osAlarmFrequency`, `createdAt`, `updatedAt`, `timeStamp` FROM `systemSetting` AS `systemSetting`;"}
original: {"errno":1,"code":"SQLITE_ERROR","sql":"SELECT `id`, `uuid`, `name`, `creator`, `alarmType`, `errorHandle`, `linkUserIds`, `smsUsers`, `mailUserIds`, `proxyAlarmValue`, `proxyAlarmFrequency`, `apiCheckAlarmValue`, `apiCheckAlarmFrequency`, `cpuAlarmValue`, `memAlarmValue`, `osAlarmFrequency`, `createdAt`, `updatedAt`, `timeStamp` FROM `systemSetting` AS `systemSetting`;"}
sql: "SELECT `id`, `uuid`, `name`, `creator`, `alarmType`, `errorHandle`, `linkUserIds`, `smsUsers`, `mailUserIds`, `proxyAlarmValue`, `proxyAlarmFrequency`, `apiCheckAlarmValue`, `apiCheckAlarmFrequency`, `cpuAlarmValue`, `memAlarmValue`, `osAlarmFrequency`, `createdAt`, `updatedAt`, `timeStamp` FROM `systemSetting` AS `systemSetting`;"
parameters: undefined
pid: 64995
hostname: OP002-web-4258

但是打开生产环境初始化的数据库，里面是有这个表的。
