### ISSUE TITLE
egg-socket.io如何配置连接超时时间

### ISSUE THREAD

**Issue by dreamStar** [eggjs/egg#1372]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问如何在使用egg－socket.io时设置每条连接的超时时间？
标准的socket.io可以在如下位置设置：
```
 var io = require('socket.io')({
     // options go here
    options:{
        pingTimeout:60000,
    }
 });
```

但是egg－socket.io直接就拿到app.io了，应该如何配置呢？

**Comment by liujinyang1994** [comment]
应该是在config文件下面配置。

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io#configuration init

**Comment by rabbit-mc** [comment]
请问解决了吗
