### ISSUE TITLE
[RFC] egg-bin debug

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1376]
## 背景

在 cluster 模式下，worker 自动重启后，debugPort 会变更，需要手动重新 attach，对调试带来不小的麻烦。

之前的解决方案是，通过 [egg-development-proxyworker](https://github.com/eggjs/egg-development-proxyworker) 插件，启动一个 tcp 代理 worker 的调试接口。

存在的问题：
- 需要手动安装插件
- vscode 里面需要配置

## 解决思路
  - 无需独立插件，`egg-development-proxyworker` 的代理功能直接做到 `egg-bin debug` 即可
  - `egg-bin` 就是 parent 进程，可以改下 `egg-cluster` 在 worker 重启后主动发一个 message 给 parent 通知新的 debugPort 即可
  - 自动判断 node 版本，8.x+ 则用 inspect，低版本用 debug
  - 自动读取 WebStorm 的环境变量
  - 原 `egg-development-proxyworker` 的功能实现有点复杂，无需多个代理，直接独立一个[inspector-proxy](https://github.com/whxaxes/inspector-proxy) 即可

**Comment by atian25** [comment]
cc @eggjs/core 有什么建议

**Comment by fengmk2** [comment]
干！

**Comment by atian25** [comment]
@fengmk2 看最后那段，定下方案

**Comment by fengmk2** [comment]
@atian25 方案你来定。

**Comment by atian25** [comment]
- [ ] egg-cluster options https://github.com/eggjs/egg-cluster/pull/41
- [ ] egg-bin debug https://github.com/eggjs/egg-bin/pull/72
- [ ] move `proxyworker` to `egg-bin debug` -> @okoala

**Comment by atian25** [comment]
WebStorm 的 attach 原理，经过一些实验，猜测如下：

- 会传递环境变量 `NODE_DEBUG_OPTION` ，在 inspect 协议下会传递 `--inspect-brk=XXXX`，旧协议传递 `--debug-brk=XXXX --expose_debug_as=v8debug`
- 应用需把该调试端口传递给 `execArgv` 来启动调试
- WebStorm 会首先 attach 该端口对应的 process
- 然后会自动 attach 该 process 的所有开启 debug 的子程序(即包括我们的 agent 和所有 worker，包括重启后的 worker)


之前的修改导致的问题：

- master 没有启动调试，只对 worker 启动了那个端口的调试
- 此时会 attach 上 worker
- 但当修改代码，导致 worker 重启时，调试端口对应的旧 worker 被杀掉，然后 WebStorm 就会视为调试结束，从而退出。



回归我们最终的诉求：

- 不希望额外安装 proxywoker 插件
- 简化 vscode 的调试配置
- worker 重启后可以自动 attach


而之前的 `egg-cluster` 实现方式，实现过于复杂了，且导致 WebStorm 那问题解决起来麻烦，故：

- 回滚 `egg-cluster` 那个 PR
  - 去除 `debug / debugAgent / debugBrk / debugAgentBrk` 的支持
  - master 照样启动调试
  - agent 调试跟随 master，固定端口为 5856
- 对于 WebStorm 来说：
  - 在 egg-bin 里面识别 `NODE_DEBUG_OPTION` 并传递给 `execArgv` 即可
  - 这块没啥改变，在此 RFC 之前的版本就已经支持了。
- 对于其他情况（直接终端运行或 VSCode）来说：
  - 当没有 `NODE_DEBUG_OPTION` 时， 方进行以下处理
  - `egg-bin debug`
    - 假设用户传递 `—debug-port=9229`
    - 传递给 start-cluster 的 `execArgv` 中的调试端口，改为一个任意的端口，将作为 master 的调试端口，假设为 9999，则此时 agent 的调试端口为 5856，worker 为 10000 自增。
    - 启动 proxy 服务，端口为用户传递的 9229，代理到 worker 的10000 端口，并监听 worker 的重启事件来重设端口。
    - proxy 服务同时会代理 devtools 的调试界面，统一为一个 URL，不用每次都重新获取。
  - 对于 vscode debug 界面，或 devtools 来说：
    - 符合直觉，在命令行传递的 debug 端口，就是需要 attach 的端口。
    - vscode 的 debug 配置只需要配置一个 `npm run debug` 即可。

**Comment by atian25** [comment]
- [x] egg-cluster options https://github.com/eggjs/egg-cluster/pull/43
- [x] egg-bin debug https://github.com/eggjs/egg-bin/pull/73
- [ ] move `proxyworker` to `egg-bin debug` https://github.com/eggjs/egg-development-proxyworker/pull/7
- [ ] update egg docs https://github.com/eggjs/egg/pull/1427
- [ ] vscode extension for debug

**Comment by atian25** [comment]
先关了，vscode 插件的后面另起

**Comment by atian25** [comment]
目前 `egg-bin debug --inspect-brk` 会同时导致 master / agent / worker 都被断点住，需要人工去一次
 attach 3 个进程，有点略麻烦，有时候只希望断点 worker 或 agent。

改进思路：
- 使用 [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface/wiki/Connect-to-Node.js) 来主动 attach 进程，然后调用 `Debugger.resume()`
- 在 egg-bin debug 的启动逻辑里面，默认会 attach master 和 agent，只允许断点在 worker 第一行。
- 支持 `--agent-brk --master-brk` 两个参数，来断点其他两个进程。

**Comment by atian25** [comment]
上述问题已解决，参见 https://github.com/atian25/blog/issues/25
