### ISSUE TITLE
中间件为什么跟Koa不同？

### ISSUE THREAD

**Issue by coolicer** [eggjs/egg#1377]
* **Node Version**: v8.4.0
* **Egg Version**:4.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac os
* **Mini Showcase Repository**:

新建了一个简单的中间件，对比了koa发现结果不同：
```js
// test.js
module.exports = options => {
  return function* test(next) {
    yield next;
    console.log('test');
  };
};
```

```js
// config.default.js
config.middleware = [ 'test' ];
```

```js 
// router.js
module.exports = app => {
  const test = app.middlewares.test();
  app.get('/', test ,'home.index');
};
```
最后发现会log 2次，koa是1次

**Comment by atian25** [comment]
因为你挂载了两次....

配置 `config.middleware = [ 'test' ];` 的时候是挂载到全局的 Middleware 数组了.
然后你在配置 router 的时候， `app.get('/', test ,'home.index');` 又单独对这个 path 挂了一次。

可以再回去看看文档。
