### ISSUE TITLE
egg-passport-twitter 线上问题

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1378]
* **Node Version**: 6.11.2
* **Egg Version**:1.7.0
* **Plugin Name**: egg-passport, egg-passport-twitter
* **Plugin Version**: 1.0.0
* **Platform**: CentOS release 6.8
* **Mini Showcase Repository**: http://45.79.143.25:7002/

### 代码：
```js
// app/router.js

module.exports = app => {
  app.get('/', 'home.index');
  app.get('/twitter/success', 'home.twitter');
  app.passport.mount('twitter', {
    loginURL: '/twitter/test',
    successRedirect: '/twitter/success',
  });
};
```

```js
// app/controller/home.js

module.exports = app => {
  class HomeController extends app.Controller {
    * twitter() {
      this.ctx.body = this.ctx.user;
    };
  }
  return HomeController;
};
```

```js
// config/config.default.js

module.exports = appInfo => {
  const config = {};

  config.passportTwitter = {
    key: XXX,
    secret: XXX,
  };

  return config;
};

// config/plugin.js

exports.passport = {
  enable: true,
  package: 'egg-passport',
};

exports.passportTwitter = {
  enable: true,
  package: 'egg-passport-twitter',
};
```

### 预期与本地开发时的结果
用户点击`/twitter/test`链接后，显示twitter授权界面，授权成功后回调到`/twitter/success`，内容显示的是用户的信息。

### 实际线上结果
用户点击`/twitter/test`，服务器不响应。

**Comment by atian25** [comment]
https://github.com/eggjs/examples/tree/master/passport 这个示例本地跑过么?

**Comment by liujinyang1994** [comment]
跑过了，本地和线上都跑了一下。

**Comment by liujinyang1994** [comment]
我已经把提供的例子部署到服务器上面了，地址不变，可以测试一下

**Comment by liujinyang1994** [comment]
@fengmk2

**Comment by atian25** [comment]
本地 `egg-scripts start` 后能正常访问么?

**Comment by liujinyang1994** [comment]
目前的示例没有使用`egg-scripts start`，如果您愿意，我可以提供一下服务器，你可以上去看一下。

**Comment by liujinyang1994** [comment]
刚看了一下，我自己写的例子用了`egg-scripts`，是不能访问的。问题蛮奇怪的。看了代码，跟其他的插件也没什么区别。但是其他的好用，只有twitter的不行。

**Comment by atian25** [comment]
服务器被墙?

**Comment by liujinyang1994** [comment]
我刚停了一下，等下，我把线上的`egg-scripts`加上

**Comment by liujinyang1994** [comment]
@atian25 改好了，http://45.79.143.25:7002/passport/twitter

**Comment by liujinyang1994** [comment]
作者们来看看啊，这个问题很苦恼啊😣。

**Comment by atian25** [comment]
看你部署好的页面没用啊... `Mini Showcase Repository` 指的是，用 `egg-init --type=simple` 做一个最小可复现代码库，然后上传到 GitHub。

**Comment by liujinyang1994** [comment]
上传好了，[egg-example](https://github.com/liujinyang1994/egg-example)

**Comment by atian25** [comment]
@liujinyang1994 我本地试了，`npm run dev` 和 `npm start` 都可以正常访问。

**Comment by liujinyang1994** [comment]
我已经说了啊，本地可以，在线上的服务器上面会出现这个问题。这个问题我查了好久。所以来这里提一个问题

**Comment by atian25** [comment]
我也说了啊，让你本地试下 egg-scripts 有没有问题了，线上 egg 就用这个启动的。如果本地用这个试了没问题，那就看看是不是你的服务器被墙了

发自我的 iPhone

**Comment by atian25** [comment]
重新梳理下:

以下都用 chrome 隐私模式试验，每次都要杀掉重开
- 本地 `npm run dev` 是否正常？
- 本地 `npm start` 是否正常？
- 服务器 `npm run dev` 是否正常？
- 服务器 `npm start` 是否正常？

**Comment by liujinyang1994** [comment]
谢谢

**Comment by atian25** [comment]
解决了?

**Comment by liujinyang1994** [comment]
没有，换AWS了。之前的那台是linode，让我扔了。啊哈哈哈。感觉应该是防火墙配置，或者是什么乱七八糟的配置有问题。

**Comment by atian25** [comment]
换完 OK 了？

其实按 https://github.com/eggjs/egg/issues/1378#issuecomment-327151515 的方式就能快速定位问题在哪了，如果一样的命令，在服务端不行，那一般就是服务端环境问题了。

**Comment by liujinyang1994** [comment]
恩，好用了。这个方法是GET到了。哈哈，还多亏你的解答。
