### ISSUE TITLE
使用的egg-socket的目录约束

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#1379]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
### 1）请问在使用的egg-socket的时候，目录机构的约束必须是下面这样吗？
```
app
├── io
│   ├── controller
│   │   └── chat.js
│   └── middleware
│       ├── auth.js
│       ├── filter.js
├── router.js
config
 ├── config.default.js
 └── plugin.js
```
### 2）如果说是`1）`中那样，那我的egg项目将会是这样，即：`app/io`目录与`app/controller`, `app/service`, `app/extend`等是平级的？感觉很别扭啊。
```
app
├── io
│   ├── controller
│   │   └── chat.js
│   └── middleware
│       ├── auth.js
│       ├── filter.js
├──controller
├──service
├──model
├──middleware
├──extend
├── router.js
config
 ├── config.default.js
 └── plugin.js
```
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by ngot** [comment]
是这样的。有什么好的建议不？

**Comment by kylezhang** [comment]
感谢回答~
没有，刚才又仔细的翻了issues，发现你们在[issues/269](https://github.com/eggjs/egg/issues/269)讨论过来了。
