### ISSUE TITLE
egg 如何配置支持 es6 的 import export

### ISSUE THREAD

**Issue by 369857519** [eggjs/egg#1381]
新需求
Hi，查了很多方法都没找到怎么实现这个，egg如何支持import export 啊？求解救。查到的都是用babel-register，然鹅不知道怎么加到egg里。

**Comment by liujinyang1994** [comment]
升级node版本

**Comment by popomore** [comment]
node 现在不支持，babel 要你自己折腾

**Comment by liujinyang1994** [comment]
Node 8.5.0  你值得拥有
