### ISSUE TITLE
egg-socket.io可以使用class吗？

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#1382]
### egg-socket.io的`app/io/controller`下面好像不可以使用`class`？

**Comment by ngot** [comment]
尚不支持，可以来PR支持一下

**Comment by ngot** [comment]
+ egg-socket.io@3.0.0 has supported!

**Comment by thonatos** [comment]
奇怪了，我这里不能用~

- node 8.6.0
- egg 2.0
- egg-socket.io 3.0.0
```
'use strict';

// 报错
// AssertionError [ERR_ASSERTION]: handler must be generatorFunction or asyncFunction!
// 
module.exports = app => {
  class Controller extends app.Controller {
    async ping() {
      const message = this.ctx.args[ 0 ];
      await this.ctx.socket.emit('res', `Hi! I've got your message: ${message}`);
    }
  }
  return Controller;
};

// 正常
exports.ping = async function() {
  const message = this.ctx.args[ 0 ];
  await this.ctx.socket.emit('res', `Hi! I've got your message: ${message}`);
};
```

**Comment by ngot** [comment]
提供一下可复现代码仓库

**Comment by thonatos** [comment]
@ngot 

https://github.com/thonatos/showcase-egg

**Comment by ngot** [comment]
@thonatos egg@2 还没适配。先用1

**Comment by thonatos** [comment]
@ngot

👌🏻，收到。

**Comment by ngot** [comment]
egg-socket.io has supported Egg.js 2.0, just upgrade the dependency to 4.0
https://github.com/eggjs/egg-socket.io/pull/28

**Comment by ray-zyh** [comment]
AssertionError [ERR_ASSERTION]: handler must be generatorFunction or asyncFunction!  
版本如下:
"egg": "^1.4.0",
    "egg-cors": "^1.1.0", 
    "egg-socket.io": "^2.0.2"

**Comment by atian25** [comment]
升级版本，egg-socket.io 现在都 4.0.6 了。
