### ISSUE TITLE
Discussion: best practice to response immediately.

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1384]
Sometimes I would like to return the response body immediately, for example,
* send a NO PERMISSON response when I check the permission.
* send a THIS USER DOES NOT EXIST response when I found that the target user is nonexistent.
* ...

Right now I solved these problems using a customized Exception. But I think this is not a elegant solution and may cause some performance loss.

**So I wonder what's your solution to these situation.**

Here's my solution.
1. add a singleton to ``App`` object. This singleton is my customized Exception. It's a signal to tell the middleware to end the process.
```
// app.js
app.addSingleton('earlyEnd', new Error('quit-response'));
```

2. add a error handler middleware to filter the signal.
```
// app/middlewares/error_handler.js
module.exports = (options, app) => {
  return async function (ctx, next) {
    try {
      await next();
    } catch (err) {
      if (err === app.earlyEnd) {
        return;  // this.ctx.body  has been set.
      } else {
         //process the error
      }
    } 
  };
};
```

3. encapsulate the method
```
// app\extend\context
const getUser = async getUser() {
   ...
   if (!user) {
      this.body = 'user not found'; 
      this.status = 404;
      throw this.app.earlyEnd;
   }
};
```

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/1086

**Comment by dead-horse** [comment]
yes, you can use customize error to do interrupt, and if you want to share code between projects, just create your own plugin to handle this logic.
