### ISSUE TITLE
使用middleware后 返回404,进入不了controller

### ISSUE THREAD

**Issue by Deval520** [eggjs/egg#1385]
//config.default.js
onfig.middleware = [ 'authValidation' ];
//router
app.post('/api/article', app.middlewares.authValidation(), app.controller.article.create);
//app/middleware/authValidation.js
....
await next;

**Comment by atian25** [comment]
挂了 `config.middleware` 了，就不需要在 app.post 那里挂了

**Comment by leo-lai** [comment]
同问，解决了么
