### ISSUE TITLE
ts的hackernews-async-ts例子跑起来提示500

### ISSUE THREAD

**Issue by zkeyword** [eggjs/egg#1386]
页面提示：
```
Error in /
Please set config.keys first
```

控制台提示：
`2017-09-05 21:46:40,124 ERROR 1050 [-/127.0.0.1/-/9ms GET /] nodejs.Error: Please set config.keys first`

按文档添加了config.default.js文件，并添加入：
`exports.keys = 'my-cookie-secret-key'`

页面提示：

`404 Not Found`

控制台提示：

```
Tue Sep 05 2017 21:50:05 GMT+0800 (CST)] [cfork:master:969] worker:1050 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false)
[Tue Sep 05 2017 21:50:05 GMT+0800 (CST)] [cfork:master:969] don't fork new work (refork: false)
2017-09-05 21:50:05,256 INFO 969 [master] app_worker#4:1050 disconnect, suicide: true, state: disconnected, current workers: ["5"]
[Tue Sep 05 2017 21:50:05 GMT+0800 (CST)] [cfork:master:969] worker:1050 exit (code: 0, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true)
```

**Comment by zkeyword** [comment]
node 版本 v7.10.0 系统 osx

**Comment by atian25** [comment]
直觉告诉我，你的 config.default.js 没有配置对，整个贴出来吧

**Comment by atian25** [comment]
咦，https://github.com/eggjs/examples/blob/master/hackernews-async-ts/config/config.ts#L12 已经有配置了啊

**Comment by zkeyword** [comment]
不用新建config.default.js ，我没有执行了npm run tsc:w ，不过README.md的文档有错。

https://github.com/eggjs/examples/blob/master/hackernews-async-ts/README.md

应该是 npm start 和package.json没对上

**Comment by chj-damon** [comment]
我也是遇到这个问题，egg是v2.3.0.
代码都是按照hackernews-async-ts敲的。
按照最新的文档里面的说法，会去config目录下找相应的配置文件：
config
|- config.default.js
|- config.test.js
|- config.prod.js
|- config.unittest.js
`- config.local.js
但是tsc之后生成的是config.js和defaultConfig.js。看起来是因为找不到文件导致的。
请问这个问题应该怎么解决？

**Comment by okoala** [comment]
@chj-damon   ts 都是编译到当前目录下的 ~

**Comment by atian25** [comment]
@chj-damon 如果你 out 到另一个目录，那你就应该去另一个目录去 npm install 和 dev

**Comment by chj-damon** [comment]
config
|- config.default.js
|- config.test.js
|- config.prod.js
|- config.unittest.js
`- config.local.js
这个是官方文档里面关于config的配置说明，请问我如果像hackerNews那个demo里面那样，只有config.ts和defaultConfig.ts，为什么最后还是可以运行呢？tsc之后生成的不也是config.js和defaultConfig.js吗？没有config.default.js的
