### ISSUE TITLE
Unit test promise or async/await method

### ISSUE THREAD

**Issue by imshenyz** [eggjs/egg#1387]
* **Node Version**: v8.2.1
* **Egg Version**: v1.7.0
* **Plugin Name**: none
* **Plugin Version**: none
* **Platform**: macOS 10.12.6
* **Mini Showcase Repository**: see the code below

Hello, the power-assert lib is powerful, but i meet an issue while test the code below:
```
describe('test promise reject', () => {
  it('should throws error', () => {
    assert.throws(async () => {
      Promise.reject('error message');
    }, Error, 'error message');
  });
});

describe('test async/await throws error', () => {
  it('should throws error', () => {
    assert.throws(async () => {
      async function aa() {
        throw new Error('error message');
      }
      await aa();
    }, Error, 'error message');
  });
});
```
I find this [issues](https://github.com/power-assert-js/power-assert/issues/21) in `power-assert` repo, it is not support test promise yet.
Is there a good way to solve this issues?
Thx.

**Comment by atian25** [comment]
```
describe('test async/await throws error', () => {
  it('should throws error', async () => {
    try {
      const result = await Promise.reject('error message');
      throw('should not run here');
    } catch(err) {
      assert(err.message === 'error message');
    }
  });
});
```

**Comment by atian25** [comment]
or https://github.com/node-modules/assert-extends
