### ISSUE TITLE
[egg-oss] Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by likeswinds** [eggjs/egg#1391]
* **Node Version**:8.1.2
* **Egg Version**:1.7.0
* **Plugin Name**:egg-oss
* **Plugin Version**:1.0.2
* **Platform**:windows
* **Mini Showcase Repository**:

```javascript
config.oss = {
  client: {
    region: 'xxxxx',
    internal: true,
    accessKeyId: 'xxxx',
    accessKeySecret: 'xxx',
    bucket: 'xxx'
  }
 }
```
``` javascript
 app.get('/oss/get', async () => {
    const name = 'oss-test-upload-' + process.version + '-' + Date.now();
    this.body = await this.oss.get('xxx'); 
  });
```
目的：下载oss中的文件，试了getStream，get，都提示`Cannot read property 'get' of undefined`

**Comment by atian25** [comment]
只配置一个 client 的时候，用 `ctx.oss`

**Comment by likeswinds** [comment]
@atian25 重新试了下，在路由里用 this可以，只不过要用Generator写异步，是不是ali-oss这个库不支持async

```
 app.get('/oss/get', function* () { 
    this.body = yield this.oss.get('xxx'); 
  });
```

**Comment by atian25** [comment]
有可能吧，可以 co wrap 下，或者给那边提 PR

**Comment by chengnuo** [comment]
same problem 改为Generator可以。

**Comment by popomore** [comment]
arrow function 的 this 指向问题

**Comment by atian25** [comment]
`app.get('/oss/get', async () => {` 要改为 `app.get('/oss/get', async (ctx) => {`
