### ISSUE TITLE
egg框架如何使用第三方平台管理配置，是否有可行的解决方案？

### ISSUE THREAD

**Issue by Quinton** [eggjs/egg#1394]
使用平台管理配置，在启动时将当前环境的配置通过环境变量传入，在现有的eggjs框架是否可行？

**Comment by atian25** [comment]
不需要用环境变量，你在 app.js 的 beforeStart 里面去请求配置，然后赋值给 app.config 即可

发自我的 iPhone

**Comment by Quinton** [comment]
直接赋值是不可行的；
目前采用了一下copy
`Object.assign(app.config, ...sources);`

**Comment by Quinton** [comment]
比如现在类似egg-mongoose插件，也从读配置文件读取，有解决方案吗？目前从mongodb初始化在beforeStart前。

**Comment by hbrls** [comment]
#1342 和我这个问题一样的吧
后来我决定在部署的时候把配置文件作为 ini 放到代码里

    // jenkins bash
    curl env >> envfile
    // config.default.js
    config['props'] = fs.readFileSync('envfile')

**Comment by jtyjty99999** [comment]
这个没什么问题啊,比如 oss

``` config.default.js


exports.oss = {
  client: {
    accessKeyId: env.ALI_SDK_OSS_ID,
    accessKeySecret: env.ALI_SDK_OSS_SECRET,
    endpoint: env.ALI_SDK_OSS_ENDPOINT,
    bucket: 'ali-oss-test-bucket-test99',
  },
};


```

**Comment by Quinton** [comment]
@hbrls 你这样做还不够优雅啊；如果用这个方法app.beforeStart(promise) 挂到 app.config， 现在遇到情况是有些插件，比如egg-mongoose，会读取不到url配置 @atian25 ，比如场景是这样：如何让读取配置文件的插件 第一个执行？

**Comment by Quinton** [comment]
eggjs项目读取远程配置中心配置，部署走生成本地文件，再启动写入环境变量读取配置。例子：https://github.com/Quinton/node-apollo
