### ISSUE TITLE
egg-scripts 的日志目录支持自定义配置吗？

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#1395]
* **Node Version**: 6.11.0
* **Egg Version**: 1.7.0
* **Plugin Name**:  egg-scripts
* **Plugin Version**:  1.1.2
* **Platform**: linux
* **Mini Showcase Repository**:

egg-scripts 的日志目录支持自定义配置吗？ 类似如下 logger 可以自定义配置目录
```
module.exports = {
    logger: {
        dir: '/data/logs/xxx',
        encoding: 'gbk'
    }
};
```
现在的日志目录是
```
const logDir = path.join(env.HOME, 'logs', pkgInfo.name);
```

**Comment by atian25** [comment]
egg-scripts 是前置命令行，拿不到 egg 的配置，要做的话只能通过环境变量或命令行参数

发自我的 iPhone

**Comment by popomore** [comment]
传参好了

**Comment by atian25** [comment]
@popomore `egg-logger` 的 dir 也要跟着变吧? 不然只是 master 的日志位置改变，应该不符合使用者预期。

**Comment by atian25** [comment]
@logzh ?

**Comment by atian25** [comment]
@logzh 你的需求是？只是需要把 master 的启动日志指定目录？

**Comment by logzh** [comment]
@atian25 希望egg-scripts能够指定日志位置，谢谢

**Comment by atian25** [comment]
就是问啥日志。目前要做的话也就 master 的而已。

发自我的 iPhone

**Comment by logzh** [comment]
@atian25 是的

**Comment by popomore** [comment]
@atian 这个开始做了么

**Comment by atian25** [comment]
没想好怎么做。

**Comment by popomore** [comment]
https://github.com/eggjs/egg-scripts/pull/8
