### ISSUE TITLE
Application Startup Configuration

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1396]
* **Node Version**:  8.x
* **Egg Version**: 1.x
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Linux
* **Mini Showcase Repository**:

假如我启动自定义失败的话，应该如何处理？

因为我现在有一个需求就是当我启动的时候去进行一项异步的操作，当这个异步操作成功 `app.somevalue = value`，失败后 `app.somevalue = errvalue`。

请问我应该怎么去捕捉这个异步操作的错误在app.js中。

```js
//  app.js
'use strict'
module.exports = app => {
  app.beforeStart(function * () {
    app.somevalue  = yield app.curl('http://SomeErrorUrl', {
      method: 'GET'
    });
    console.log('Ok~');
  });
}
```

**Comment by popomore** [comment]
失败就是启动失败吗

**Comment by skyfore** [comment]
@popomore 不是，失败的意思是异步操作报错，比如app.curl 请求了一个不存在的地址。

**Comment by atian25** [comment]
直接包个 try 不行？

**Comment by skyfore** [comment]
好的，OK，直接用try catch包能成功，谢谢解答 
@atian25
