### ISSUE TITLE
请问如何在回调函数中使用logger打印日志

### ISSUE THREAD

**Issue by 156520783** [eggjs/egg#1398]
请问如何在回调函数中使用logger打印日志
例如：
fs.writeFile(filepathticket, data, 'utf8', function(err){
                if(err){
                  // 如何在这里log日志打印在文件里面。
                  // 使用ctx.logger.info() 这种会报错。
                }
              });

谢谢。

**Comment by THaGKI9** [comment]
ctx=app.createAnonymousContext()

**Comment by atian25** [comment]
跟具体场景有关，请给出更多信息

**Comment by 156520783** [comment]
在service层处理逻辑。
1.通过第三方库获取微信的ticket（异步）
2.将ticket写入文件（异步）
3.写入失败的情况下打印logger日志（这步不知道如何处理）

具体代码如下：

'use strict';

var config = require('../../config/weixin.config.json');
var WechatAPI = require('wechat-api');
var api = new WechatAPI(config.wechat.appID, config.wechat.appSecret);
var fs = require('fs');
var path = require('path');
var filepathticket = path.join(__dirname,'../../config/jsticket.txt');

module.exports = app => {
    return class CUpdateJsConfig extends app.Service {
      * updateJsTicket() {
        // 1.获取ticket
        api.getTicket(function (err,result){
            if(err){
                return false;
            }else{
              // 2.写入文件
              var data = JSON.stringify(result);
              fs.writeFile(filepathticket, data, 'utf8', function(err){
                if(err){
                  //如何在这里打logger日志？
                  
                }
              });
              console.log(JSON.stringify(result));
            }
        });

        return true;
      }
    }
  };

**Comment by popomore** [comment]
请不要使用 callback，将 callback 转成 promise 然后我yield，直接 this.ctx.logger

**Comment by 156520783** [comment]
用yield可能会对性能产生有一些影响吧，不过我发现应该可以用闭包解决这个问题。谢谢。

**Comment by atian25** [comment]
这点性能就别纠结了...
