### ISSUE TITLE
egg 上传文件 时候 getFileStream获取到的数据怎么转化成buffer类型

### ISSUE THREAD

**Issue by losefish** [eggjs/egg#1399]

**Comment by losefish** [comment]
想要实现到步骤：
1. react通过 input type=‘file’ 上传文件到egg，
2. egg获取到fileStream上传到aws
现在到问题是，上传文件到egg的时候，是一个fileStream类型到数据，aws上传文件到API需要使用buffer类型到东西。一只没办法处理fileStream to buffer的实现。

以下是部分代码
1. react
`<div style={{marginTop: 100}}>
            <input type='file' onChange={(e) => {
              this.setState({
                fileSteam: e.target.files[0]
              })
            }}/>
            <button
              onClick={this._uploadHandle}
            >
              提交
            </button>
</div>`
这里我是使用了FormData增加了其他信息；
`_uploadFile(file: any, state: State): void {
    let data = new FormData();
    let csrfToken = getCookie('csrfToken');
    data.append('userId', 'jackjksdjkjskdjkjk');
    data.append('path', 'xxxx/yyyy');
    data.append('file', file);
    let ops = {
      url: `/upload?_csrf=${csrfToken}`,
      data: data,
      cache: false,
      contentType: false,
      processData: false,
      type: 'POST',
      success: function(res) {
        console.log(res);
      }
    };
    $.ajax(ops);
    return state;
  }`

2. egg
`class UploadController extends Controller {
  * upload() {
    const {ctx} = this;
    const stream = yield ctx.getFileStream();
    // 这里转化成为buffer一直不对
    let bufferData = new Buffer(stream._readableState.buffer);
    yield AWS.upload(stream.fields.userId, stream.fields.path, stream.filename, bufferData)
      .then(function(location) {
      console.log(location);
    })
      .catch(function(err) {
        console.error('can not upload file to AWS-S3');
        throw new Error(JSON.stringify(err));
      });
  }
}`

我不确定转化成buffer 的方式是不是正确。然后又参考了 https://github.com/eggjs/examples/blob/master/multipart/app/controller/upload.js  这个例子，写入stream，还是不行。
甚至是把这个例子copy到我的环境下，上传了张图片，图片打开失败，好像文件被损坏了……

其实核心问题就是怎么把文档流转化为buffer，求教

**Comment by buaaljy** [comment]
https://www.npmjs.com/search?q=stream-to-buffer

**Comment by losefish** [comment]
@buaaljy 感谢你的建议，但是我尝试了，并不成功。
egg里面转化stream为buffer
const stream = yield ctx.getFileStream();
    streamToBuffer(stream, function (err, buffer) {
      if (err) {
        throw new Error(JSON.stringify(err));
      }
      console.log(buffer);
      AWS.upload(stream.fields.userId, stream.fields.path, stream.filename, buffer)
        .then(function(location) {
          console.log('----location');
          console.log(location);
        })
        .catch(function(err) {
          console.error('can not upload file to AWS-S3');
          throw new Error(JSON.stringify(err));
        });
    });
的确可以上传文件，但是上传到aws后，aws会返回一个文件存储地址到url，**我访问这个url提示文件损坏。**

**Comment by popomore** [comment]
你需要等待 stream 收集完成再上传，把 callback 转成 promise，然后再 yield。可以自己网上查一下

**Comment by losefish** [comment]
@popomore 不好意思，我还是不太明白，我原来的做法是在egg里面使用了yield getFileStream()获取了数据，yield还不能保证stream收集完成吗？
还是说你说的「等待stream收集完成」是streamToBuffer的操作中没有把stream收集完成吗？

**Comment by popomore** [comment]
getFileStream 取到的是 stream，要等转成 buffer

**Comment by losefish** [comment]
@popomore 非常抱歉，还是没有成功，大神能麻烦写一下代码吗？
我用的以下方式获取的，还是不对，文件损坏……
const stream = yield ctx.getFileStream();
    const buffers = [];
    stream.on('data', function(buffer) {
      buffers.push(buffer);
    });
    stream.on('end', function() {
      const data = Buffer.from(buffers);
      fs.writeFile('./test.png', data, function(err) {
        if (err) {
          throw new Error('there has ERROR in writeFile');
        }
      });
      upload(stream.fields.userId || 'xxxxxx', stream.fields.path || 'aaa/bbb/ccc', stream.filename, data)
    });

**Comment by popomore** [comment]
用这个 https://github.com/stream-utils/stream-to-array

```js
const parts = yield toArray(stream);
const buffer = Buffer.from(parts);
```

**Comment by losefish** [comment]
@all 谢谢各位的解答，问题已经解决。

说起来惭愧，问题的原因是**配置项写错**了。
`fileSize: '100kb'`
写成了  100k  
egg也同样获取了fileStream，但是fileStream的数据是不完整的，导致上传成功，但是文件展示错误。
再次谢谢各位的解答。
