### ISSUE TITLE
依赖发布 1.0

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#140]
- [x] egg-core
- [x] egg-cors
- [x] egg-session
- [x] egg-static
- [x] egg-userrole
- [x] egg-validate

**Comment by popomore** [comment]
egg-core 我来搞，还有两个需求

**Comment by fengmk2** [comment]
egg-static 我来

**Comment by fengmk2** [comment]
egg-static@1.0.0 done

**Comment by fengmk2** [comment]
领 egg-cors

**Comment by atian25** [comment]
https://github.com/eggjs/egg-userrole/pull/5

**Comment by atian25** [comment]
https://github.com/eggjs/egg-validate/pull/2

**Comment by atian25** [comment]
https://github.com/eggjs/egg-session/pull/3

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view-nunjucks/pull/7

**Comment by atian25** [comment]
都升级完了
