### ISSUE TITLE
eslint rulers selet

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1404]
* **Node Version**: 8.x
* **Egg Version**:  1.x
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:  Linux
* **Mini Showcase Repository**:

请问在egg 中的 `eslint` 的规则使用的是自己的还是其他的，假如使用的是其他的规范是否可配置，比如我想使用 `airbnb` 的规则应该怎么配置（我的意思是在 `egg` 框架层面配置而不是我自己修改`.eslintrc`并手动`npm i ...`）

**Comment by solarhell** [comment]
dev的依赖为什么要放到框架层面？
脚手架默认就会给你安装`eslint-config-egg`

**Comment by skyfore** [comment]
@solarhell 那在eslint-config-egg 中是否可配置使用其他的规范，比如 `standar / airbnb` 这些

**Comment by solarhell** [comment]
airbnb的那套没记错是针对react的吧...
你要是想用`standard`，extend一下就好了。

**Comment by atian25** [comment]
`eslint-config-egg` 只是 egg 自己的规约，你可以不用的。

> 我的意思是在 egg 框架层面配置而不是我自己修改.eslintrc并手动npm i ...

**egg 本身没有对应用做任何的 eslint 校验。** 目前你所感知到的校验，都是在脚骨架生成的项目的 `.eslintrc` 里面，我们默认推荐的配置，如果你想切换成自己的，就必须自己修改。

**Comment by skyfore** [comment]
@solarhell @atian25  恩，好的，谢谢。
