### ISSUE TITLE
egg-redis 不支持方法返回的配置，仅支持静态配置的，这算BUG吗？

### ISSUE THREAD

**Issue by zhengxiansen** [eggjs/egg#1406]
* **Node Version**: 8.4.0
* **Egg Version**:  1.7.0
* **Plugin Name**: egg-redis
* **Plugin Version**: 1.0.2
* **Platform**: mac os
* **Mini Showcase Repository**: 

被折腾死了，最后才发行是配置存放的问题

如果是下图这样配置，app.redis 才是期望的配置
![image](https://user-images.githubusercontent.com/7506913/30265531-f1d726b8-970e-11e7-9f1e-3d2a7aede19b.png)

可是如果是在方法中返回的配置，那 app.redis 就不是期望的东西
![image](https://user-images.githubusercontent.com/7506913/30265531-f1d726b8-970e-11e7-9f1e-3d2a7aede19b.png)

这样返回的 redis 没有 set 方法

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/30266389-cbe602d2-9711-11e7-9fb3-4b66a780a758.png)

**Comment by jtyjty99999** [comment]
😓

**Comment by zhengxiansen** [comment]
请原谅我间接性的眼瞎😓

**Comment by atian25** [comment]
没事，已经习惯了 （身边的计数器默默变为 10）
