### ISSUE TITLE
怎么做error_handler的单元测试

### ISSUE THREAD

**Issue by abuyao** [eggjs/egg#1407]
要做error_handler的单元测试，但是这里卡住了。如下。
在error_handler中, try{yield next;}catch(err){}
什么情况下 yield 一个变量名能报错？

**Comment by atian25** [comment]
参考下 https://github.com/eggjs/egg-onerror/blob/master/test/onerror.test.js

**Comment by abuyao** [comment]
这都是场景测试吧，就单独测试这个js文件，执行这个generator函数，传什么next能让yield报错？

**Comment by atian25** [comment]
Promise.reject('xxxx')

**Comment by popomore** [comment]
还是使用正常方式测试，不要 require 来测试。
