### ISSUE TITLE
请教写插件的问题（ egg-xconfig）

### ISSUE THREAD

**Issue by xbf321** [eggjs/egg#1413]
最近写了一个 egg-xconfig 的插件，插件流程是这样的：
1. 根据 config 请求 「服务」获取 token 
2. 拿到 token 请求「服务」 获取访问地址
3. 拿到「服务地址」，在根据「文件key」请求「服务地址」，并把返回的文件内容保存到本地
4. 后续就是 定时轮训 检查线上文件是否更改，如果有更改，就更新缓存，以及更新本地物理文件

大致流程是这样，遇到问题，就是在多进程的情况下，每一个 work 都会 重复执行以上的步骤。
实际上要的效果是前三步，只做一次就行（在第三部需要写IO，每一个 work 其实写的都一样，感觉浪费），只有第四步，交给 schedule 让 work 去做。

下面是参照的 egg-mysql 的例子做的，没有达到预期的效果
``` 
// app.js
module.exports = app => {
    app.addSingleton('xconfig',  (config, app) => {
            const client = new XConfig(config, app);
            return client;
    });
    app.messenger.on('refresh', ret => {
        app.logger.info('start update by %s, data:', ret.by, ret.data.join(','));
        const ctx = app.createAnonymousContext();
        // a convenient way to execute with generator function
        // can replaced by `co`
        ctx.runInBackground(function* () {
            yield app.xconfig.update(ret.data);
        });
    });
}
```
定时任务
```
// pull_refresh.js
module.exports = app => {
    return {
        schedule: {
            interval: app.config.xconfig.interval || '5m',
            type: 'worker',
        },
        * task(ctx) {
            const updateConfigs = yield ctx.app.xconfig.checkUpdate();
            if (!updateConfigs) return;
            ctx.app.messenger.sendToApp('refresh', {
                by: 'pull',
                data: updateConfigs,
            });
        },
    };
};
```

后来，想着用 agent 做前三步的操作，只有第四部交给 work 去做，不知道这样实现有没有问题，或者有没有更好的实现思路？

**Comment by atian25** [comment]
可以的，之前 agent 这个概念出来的一个原因就是你这种场景。

简单的做法可以是，你在 agent 里面去发请求，拿到数据后，通过 messenger 发给所有 worker 更新。

复杂一点的话: https://eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by xbf321** [comment]
好的，那在问下 agent 不适合做什么业务呢？

**Comment by popomore** [comment]
agent 为保证稳定性，适用于多低频操作 https://eggjs.org/zh-cn/core/cluster-and-ipc.html#master-vs-agent-vs-worker
