### ISSUE TITLE
egg-mongoose multiple connection

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1418]
* **Node Version**: 8.x
* **Egg Version**:  1.x
* **Plugin Name**: egg-mongoose
* **Plugin Version**: v2.1
* **Platform**: Linux
* **Mini Showcase Repository**:

我在egg-mongoose 的仓库中看到的例子上说支持同时连接多个数据库，但是，当我在使用的时候我只看到了通过 app.mongoose来进行使用。

但是假如我的业务逻辑是这样的
```js

const conn1 = mongoose.createConnection('db1');
const conn2 = mongoose.createConnection('db2');

// Init Schema

const Model1 = conn1.model('schema1', schema1);
const Model2 = conn2.model('schema2', schema2);

const model1 = new Model1({...});
const model2 = new Model2({...});

model1.save();
model2.save();

```

我的问题是怎么在model层使用不同的数据库连接。

还有就是假如我与数据库的连接并不是在app启动的时候进行连接的，我可能是从用户输入的 dburl 中去建立连接并且进行查询数据等等操作，请问这种情况应该如何在egg中扩展。

**Comment by jtyjty99999** [comment]
> 还有就是假如我与数据库的连接并不是在app启动的时候进行连接的，我可能是从用户输入的 dburl 中去建立连接并且进行查询数据等等操作，请问这种情况应该如何在egg中扩展。  

这个需求可以参考 https://eggjs.org/zh-cn/advanced/plugin.html#全局实例插件的最佳实践  来对egg-mongoose进行重构，欢迎pr

> model层使用不同的数据库连接。

这个目前还不支持

你提的这两点其实都跟  https://eggjs.org/zh-cn/advanced/plugin.html#全局实例插件的最佳实践   有关，有时间我会重构这个插件
