### ISSUE TITLE
如何“no downtime”重启服务

### ISSUE THREAD

**Issue by danielxiaowxx** [eggjs/egg#1425]
如题：如何“no downtime”重启服务

**Comment by atian25** [comment]
前面挡个 Nginx 做平滑重启

发自我的 iPhone

**Comment by danielxiaowxx** [comment]
用`egg-scripts stop`，是停掉master进程，那已经接受的请求会处理完才退出吗？跟node的cluster模块处理worker的disconnect一样？？

**Comment by atian25** [comment]
嗯，egg-cluster 里面有做了优雅退出

**Comment by popomore** [comment]
前面需要有个 lb，发布的时候关闭发布服务器的流量，然后重启，检查是否启动成功，再开始流量。

**Comment by danielxiaowxx** [comment]
你们生产的项目都是这样用切流量的方式发布的是吧

**Comment by popomore** [comment]
这是最基本的流程，实际会复杂很多。
