### ISSUE TITLE
feature request: 获取当前请求所匹配的 path-pattern 或者是 router-name

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1426]
* **Node Version**: v8.2.1
* **Egg Version**: 1.8.0
* **Platform**: Windows 10 1703

因为我写了个中间件用于收集各个接口的数据统计，对于一些带参数的 url 的话，比如 ``/users/:id`` 对应的会有多种不同 ``id`` 的请求，比如 ``/users/1``, ``/users/2``，如果单纯的用 ``Context#path`` 来获取的话会造成统计数据不准确，所以想获取 router-name 或者 path-pattern。

比方说：
```js
// app/router.js
...
   app.get('get-user-info', '/users/:id', 'user.fetchOne');
```

```js
// app/controller/user.js
module.exports = (app) => {
  return class UserController extends app.Controller {
    fetchOne() {
      ...
      const routerName = this.ctx.routerName;
      // routerName: 'get-user-info'
      const urlPattern = this.ctx.urlPattern;
      // urlPattern = 'users/:id'
    }
  };
};
```

**Comment by fengmk2** [comment]
可以实现的，得去看看 koa-router，在匹配得时候设置上这2个变量。

**Comment by fengmk2** [comment]
`this.ctx.router.name` 和 `this.ctx.router.pattern` 我建议这样比较好。

**Comment by THaGKI9** [comment]
``this.ctx.router`` 已经被占用了，是一个 ``Router`` 对象来着

**Comment by fengmk2** [comment]
koa router 关键已经做了这些事情，可以看看这些变量 https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L321

`ctx.matched`, `ctx._matchedRoute` 和 `ctx._matchedRouteName`

**Comment by THaGKI9** [comment]
[https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L321](https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L321)

我对这个 dispatch 下了断点。。发现根本没有执行呀。。。

**Comment by atian25** [comment]
egg-bin debug --inspect-brk，然后要分别依次 attach master(9229), agent(5800)，worker(9230)

发自我的 iPhone

**Comment by THaGKI9** [comment]
ok，有空试试，对于 egg 的原理还需深入学习一下
直接用 ``Context#_matchedRoute`` 还是可以获得 path-pattern 的

**Comment by wadeDra** [comment]
感觉这里有个坑，如果是要当前匹配的route name应该是ctx.routerName，而不是_matchedRouteName，_matchedRouteName拿的是最接近的匹配，而不一定是当前真实的匹配。例如: /test/:testid与 /test/abc两个路由，就可能会有拿错的情况。

**Comment by atian25** [comment]
可以更新下最新依赖试试，有 `ctx.routeName` 和 `ctx.routerPath`

**Comment by wadeDra** [comment]
> 可以更新下最新依赖试试，有 `ctx.routeName` 和 `ctx.routerPath`
> 
> https://github.com/eggjs/egg-router/pull/2/files

嗯，谢谢，我这边之前用的_matchedRouteName，也是碰到了问题才发现有routerName，所以打算回复做个记录哈哈

**Comment by moyuanhua** [comment]
目前最新版本都已经暴露出来routerPath 与 routerName 
而且可以在中间件里面获取 

！！！只是 中间件不能被配置为全局中间件 

全局中间件在路由分发圈触发

写在路由中的中间件在路由分发后触发， 这样就能在中间件中找到被分发的路由了  

哈哈哈哈哈 气死我了 
我还自己写了一套路由匹配

最后越想越不对  岂不是在做重复工作  浪费性能。。。

**Comment by atian25** [comment]
> 只是 中间件不能被配置为全局中间件

肯定啦，全局中间件是在 router 外面的，不经过 router 的话，是拿不到 router 匹配的 name 的，除非你全局中间件是在返回阶段去获取
