### ISSUE TITLE
请问怎么访问多数据库？我有一个项目需要同时访问Mysql和Mssql

### ISSUE THREAD

**Issue by john2088** [eggjs/egg#1429]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:egg-sequelize
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by john2088** [comment]
自己怒答一个，sgg-sequelize里把model写死了，只好自己引入sequelize
`const config = Object.assign(defaultConfig, app.config.sequelize);

  app.Sequelize = Sequelize;

  const sequelize = new Sequelize(config.database, config.username, config.password, config);
//这里可以加一个判断config是否为数组，然后传入property名字，循环defineProperty，这样就有多个数据模型
  // app.sequelize
  Object.defineProperty(app, 'model', {
    value: sequelize,
    writable: false,
    configurable: false,
  });`

**Comment by atian25** [comment]
目前 egg-sequelize 还不支持，cc @huacnlee

**Comment by wucangeo** [comment]
[egg-knex](https://github.com/eggjs/egg-knex)推荐用吗？这个好像支持多数据库

**Comment by allenaware** [comment]
最好参照activerecord做成可配置，把数据库配置key作为一个model参数传入

**Comment by dead-horse** [comment]
egg-sequlize 4.x 已支持
