### ISSUE TITLE
既然是企业级框架, 为什么不使用Typescript

### ISSUE THREAD

**Issue by axetroy** [eggjs/egg#1430]
大法有几大好处: 

- [x] 类型系统, 配合IDE的智能提示/查找, 能够省下很多事(对, 说的就是翻阅文档)
- [x] 能够在开发阶段, 避免了N种BUG, 很多test case都可以不用写了
- [x] 企业级, 是不是就意味着稳定/严谨/高可用
- [x] 只需要更改配置即可编译各版ECMA

正值Node@8的LTS准备来临, 准备升级koa2, 有没有计划使用Typescript重构?一时的痛苦, 换来无尽的舒坦.

**Comment by popomore** [comment]
有例子 https://github.com/eggjs/examples/tree/master/hackernews-async-ts

**Comment by atian25** [comment]
在上层业务应用开发中你现在可以随便用 ts 的，至于 Egg 内部的话，目前还没计划。

**Comment by coolcao** [comment]
@popomore 这个例子中，没有整合 egg-sequelize，这个有整合sequelize和egg-sequelize的例子么

**Comment by popomore** [comment]
TS 需要社区来贡献，你可以把使用经验分享出来。
