### ISSUE TITLE
eggjs + docker 最佳实践

### ISSUE THREAD

**Issue by Quinton** [eggjs/egg#1431]
docker该如何配合eggjs work特性让项目稳定的运行？

**Comment by atian25** [comment]
就在 docker 里面跑 `egg-scripts start` 即可，不需要 `--daemon` 了。

**Comment by thonatos** [comment]
## #package.json
```
{
  "scripts": {
    "start": "egg-scripts start",
  }
}
```

## Dockerfile
```
FROM node:8.0.0-alpine

RUN apk --update add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# add npm package
COPY package.json /usr/src/app/package.json

RUN npm i --registry=https://registry.npm.taobao.org

# copy code
COPY . /usr/src/app

EXPOSE 7001

CMD npm start
```

**Comment by Quinton** [comment]
用yarn替代npm可以加快镜像构建，大概平均节省30s

**Comment by atian25** [comment]
你用我们的 https://github.com/cnpm/npminstall 一样会快的发溜。

发自我的 iPhone

**Comment by thonatos** [comment]
## tips

- RUN/COPY 是分层的，package.json 提前，只要没修改，就不会重新安装包
- npm/yarn/cnpm 新版并木有速度太大差距哇，关键是源

感受一下速度吧

<img width="1268" alt="2017-09-17 12 08 12" src="https://user-images.githubusercontent.com/958063/30517936-5ebba4b0-9b34-11e7-8da0-3ff84211fedb.png">

**Comment by abos5** [comment]
```
RUN apk --update add tzdata
```
请问这一步能否用到国内镜像呢，部分网络好慢

**Comment by atian25** [comment]
这块属于具体 docker 系统的命令了，可以自行 google 下如何修改 `alpine` 的源

**Comment by popomore** [comment]
@abos5 可以自己找下国内 apk 镜像

**Comment by VectorHo** [comment]
@thonatos 是什么构建UI，是docker hub 和github 协作那个吗？

**Comment by thonatos** [comment]
阿里云容器服务

**Comment by ycjcl868** [comment]
https://stackoverflow.com/questions/50103296/docker-compose-nodejs-mysql-cant-connect-mysql

**Comment by Yang03** [comment]
`npm run start`  时不加`--daemon`，node 在前台运行， gitlab ci  job  一直就会在运行状态 @atian25

**Comment by thonatos** [comment]
@Yang03

CI 不应该跑 `egg-scripts start` 。

**Comment by Yang03** [comment]
ci  里面跑的是 `docker run -p 7001:7001 --name xx__image xx`

dockerFile 最后的命令是 `npm run start => egg-script start` @thonatos

**Comment by popomore** [comment]
docker run -d

**Comment by menkeydyvh** [comment]
有人知道 docker run egg项目完成后 无法退出继续执行 linux 命令行是怎么回事？
ctrl+c 都退出不到能输入linux命令的状态

**Comment by Yang03** [comment]
可以在后台运行，这样就不用ctrl+c 了

menkeydyvh <notifications@github.com> 于2018年9月7日周五 下午6:47写道：

**Comment by whlsxl** [comment]
@thonatos 是不是 `RUN npm i --registry=https://registry.npm.taobao.org --production`  更好点

**Comment by muzi131313** [comment]
有没有是个人服务器，性能不行，构建放到本地，通过git提交到服务器，然后把node_modules以及打包的静态资源dist外挂磁盘的

**Comment by atian25** [comment]
你直接丢 ci 去构建不就行了。

**Comment by magnnus** [comment]
在我们公司内 私有云上使用 Docker 部署的 Egg 应用，在使用内置的 `workers=os.cpus().length` 启动后，在 **4G x 4Cpus** 的容器实例中 进程数 竟然达到了 50 个（alinode 的监控结果，感觉 alinode平台）；
在容器中验证 `os.cpus().length = 40`，所以我们目前是在 `npm scripts` 中手动限制了 `--workers=4`。

不知道这是不是我们私有云的 bug，还是 Docker 中确实如此？

**Comment by magnnus** [comment]
> 在我们公司内 私有云上使用 Docker 部署的 Egg 应用，在使用内置的 `workers=os.cpus().length` 启动后，在 **4G x 4Cpus** 的容器实例中 进程数 竟然达到了 50 个（alinode 的监控结果，感觉 alinode平台）；
> 在容器中验证 `os.cpus().length = 40`，所以我们目前是在 `npm scripts` 中手动限制了 `--workers=4`。
> 
> 不知道这是不是我们私有云的 bug，还是 Docker 中确实如此？


发现这个问题，是因发现内部监控平台 memory 曲线是递增的， 怀疑内存泄漏，排查发现的。中间确实改过部分代码，但最终改过 workers 配置后，曲线正常了。

**Comment by atian25** [comment]
这是 Node && Docker 的 BUG，os.cpus() 无法识别在 docker 里，

**Comment by Carrotzpc** [comment]
那目前 egg 跑在 docker 里的话只能通过 `--workers` 先自己手动指定下 woker 数了？

**Comment by magnnus** [comment]
> 那目前 egg 跑在 docker 里的话只能通过 `--workers` 先自己手动指定下 woker 数了？

跟平台有关系。我们这里系统环境变量可以获取配置。手动写死也可以。

**Comment by Carrotzpc** [comment]
> > 那目前 egg 跑在 docker 里的话只能通过 `--workers` 先自己手动指定下 woker 数了？
> 
> 跟平台有关系。我们这里系统环境变量可以获取配置。手动写死也可以。

是指在系统环境变量里预先写入了 cpu 相关参数，然后在 `--workers` 指定的时候读取这个环境变量吗？

**Comment by magnnus** [comment]
> > > 那目前 egg 跑在 docker 里的话只能通过 `--workers` 先自己手动指定下 woker 数了？
> 
> > 
> 
> > 跟平台有关系。我们这里系统环境变量可以获取配置。手动写死也可以。
> 
> 
> 
> 是指在系统环境变量里预先写入了 cpu 相关参数，然后在 `--workers` 指定的时候读取这个环境变量吗？

是的。系统级公共环境变量是平台运维负责维护的，不是业务开发人员。

**Comment by Carrotzpc** [comment]
> > > > 那目前 egg 跑在 docker 里的话只能通过 `--workers` 先自己手动指定下 woker 数了？
> > 
> > 
> > > 
> > 
> > 
> > > 跟平台有关系。我们这里系统环境变量可以获取配置。手动写死也可以。
> > 
> > 
> > 是指在系统环境变量里预先写入了 cpu 相关参数，然后在 `--workers` 指定的时候读取这个环境变量吗？
> 
> 是的。系统级公共环境变量是平台运维负责维护的，不是业务开发人员。

了解👌，感谢～

**Comment by zhaowei-plus** [comment]
docker run --name docName -p 9423:9423 -d ac0cee76005a

docker容器运行之后，本地 localhost:9423 访问失败，请问下还需要我本地配 nginx 吗

**Comment by shenzhim** [comment]
> ci 里面跑的是 `docker run -p 7001:7001 --name xx__image xx`
> 
> dockerFile 最后的命令是 `npm run start => egg-script start` @thonatos

ci 一般来说是做build 和 deploy的事情的，直接在ci里 运行docker的情况 不太合适吧

**Comment by mwb-27** [comment]
按上文说的生成了docker镜像，运行docker容器后egg应用运行正常，但是访问http://127.0.0.1:7001，返回错误信息Internal Server Error, real status: 500

**Comment by brizer** [comment]
> `npm run start` 时不加`--daemon`，node 在前台运行， gitlab ci job 一直就会在运行状态 @atian25

构建dockerfile时通过`ENTRYPOINT ["sh", "start.sh"]`，去start.sh里start ，不带daemon参数就可以又绕过ci的pending，又docker部署了。

**Comment by huanlirui** [comment]
> 就在 docker 里面跑 `egg-scripts start` 即可，不需要 `--daemon` 了。

这个最有用！！！坑死我了

**Comment by Shijf** [comment]
> > 就在 docker 里面跑 `egg-scripts start` 即可，不需要 `--daemon` 了。
> 
> 这个最有用！！！坑死我了

文档里有写 使用 Docker 时建议前台运行。

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/3c2c9306-5b92-4370-8738-6bfe4ed41e95" />
