### ISSUE TITLE
在egg-sequelize 中Model文件中拿不到service

### ISSUE THREAD

**Issue by dahuahe** [eggjs/egg#1432]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在egg-sequelize模块中由于业务需要model hooks 方法且调用service 发现这个文件唯一的变量app中都拿不到service或者ctx有点尴尬

**Comment by jtyjty99999** [comment]
这块逻辑不应该放在model 中吧，感觉有点重了

**Comment by dahuahe** [comment]
这个sequelize 有hooks方法  查询之前 我需要做一些事情  controller 已经固定好了

**Comment by dahuahe** [comment]
查询很久找打了.已经解决 const ctx = app.createAnonymousContext(); 拿到了

**Comment by popomore** [comment]
你在一起 service 调用的 model 之前做是一样的，没必要用 hook

**Comment by dahuahe** [comment]
@popomore 谢谢 可能场景没有表述清楚.service能拿到就好了.有这个需要

**Comment by dahuahe** [comment]
@popomore 谢谢 可能场景没有表述清楚.service能拿到就好了.有这个需要

**Comment by atian25** [comment]
为啥一定要在 model 这层去做呢，应该在上层做的。

**Comment by dahuahe** [comment]
是这样的 我控制器为了方便 增删改查 路由 /:model/.....  控制器 ctx.model[ctx.params.model] .... 但是有个模型的查询有点需求  需要在查询之前做数据同步 这个 步骤 不想放在控制器那里去完成 只是这个模型有需要.所以就放在hook那儿beforeFind那里了

**Comment by atian25** [comment]
在 service 里面做咯

**Comment by dahuahe** [comment]
谢谢~小弟才疏学浅.我再整理整理代码

**Comment by popomore** [comment]
不要因为业务简单就少了 service，等你业务越来越复杂就很难写了，model 里写业务看代码很累。

**Comment by dahuahe** [comment]
好的.

**Comment by xiehuiqi220** [comment]
const ctx = app.createAnonymousContext()

虽然这样可以调用通，但是这里的ctx并无法拿到当前http请求的信息以及用户身份信息啊？
