### ISSUE TITLE
egg-bin: egg-bin debug 的时候 proxy 参数不生效

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1433]
* **Node Version**: 8.2.1
* **Egg Version**: 1.8.0
* **Plugin Name**: egg-bin
* **Plugin Version**: 4.3.2
* **Platform**: Windows 10 1073
* **Mini Showcase Repository**:

参照 [使用 VSCode 进行调试](https://eggjs.org/zh-cn/core/development.html#%E4%BD%BF%E7%94%A8-egg-bin-%E8%B0%83%E8%AF%95)
设置了 vscode 的调试配置之后发现一直提示
```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9999)
```

我想应该是 inspect-proxy 没有正常开启的症状
看了一下源码
正常开启的时候应该会输出
```
Debug Proxy online, now you could attach to ${proxyPort} without worry about reload.
```

然而并没有，这是 win 下的一个 bug 吗？或者我还需要什么另外的设置？

**Comment by atian25** [comment]
你的 Node 版本和启动指令？

发自我的 iPhone

**Comment by THaGKI9** [comment]
各种版本已经写在上面了呀
```
// package.json
{
  "scripts": {
    "debug": "egg-bin debug",
  }
}
```

我用的是 ``yarn``
运行 ``yarn debug``

**Comment by atian25** [comment]
直接命令行执行 `npm run debug` 看看有没有输出？（先看看 vscode 的终端窗口关闭之前启动的进程没，避免端口冲突）

发自我的 iPhone

**Comment by THaGKI9** [comment]
我 ``egg-init`` 了一个新的项目，然后 ``npm run debug``之后居然有那行 
```
Debug Proxy online, now you could attach to ${proxyPort} without worry about reload.
```

我原来的项目创建的比较早，尝试手动升级 egg-bin@4.3.2 egg@1.8.0，再 ``npm run debug`` 无事发生，我再尝试升级一下别的依赖？

**Comment by atian25** [comment]
更新依赖即可，这个功能是刚实现的。我们不推荐用 yarn 之类的来锁版本，应该尽可能的升级最新依赖。我们实践都是每一次部署都是最新依赖。

发自我的 iPhone

**Comment by THaGKI9** [comment]
问题解决了，谢谢！
