### ISSUE TITLE
自定义的log如何进行分割

### ISSUE THREAD

**Issue by losefish** [eggjs/egg#1436]
因为公司项目中对日志对格式有特殊要求，所以自己写了个logger来记录日志；

```
const Logger = require('egg-logger').Logger;
class MyLogger extends Logger {
  info(ctx, ...message) {
    let titleMessage = formatter(ctx, '[I]');
    super.info(titleMessage + message.join('|'));
  };
  error(ctx, ...message) {
    let titleMessage = formatter(ctx, '[E]');
    super.error(titleMessage + message.join('|'));
  };
}
const cusLogger = new MyLogger();
cusLogger.set("file", new FileTransport({
  file: Constants.logPath,
}));
```

这种做法可以将自定义格式对log写入到Constants.logPath这样到目录中，但是应该如何对这些log做分割呢？

我试过了两种方法
1. 在config.default.js中配置logrotator，这种方式并没有奏效。**我的理解是配置项中对logrotator是对ctx.logger生效的，没有对cusLogger生效**。请问是这样吗？

```
logrotator: {
      filesRotateBySize: [
        Constants.logPath,
      ],
      maxFileSize: 1 * 1024,
      rotateDuration: 500,
    },
```

2. 使用了这里对例子 [https://github.com/eggjs/egg-logrotator](url)  也就是利用了定时任务来分割日志，为了方便测试验证，我设置成了每分钟切割一次。也没有成功，打印输出了app.LogRotator是undefined，**请教一下我的写法是不是有问题，或者说这个app.LogRotator应该是什么**。

```
const getRotator = function(app) {
  class CusRotator extends app.LogRotator {
    * getRotateFiles() {
      let time = moment().format('YYYY.MM.DD-HH:mm');
      const files = new Map();
      const srcPath = Constants.logPath;
      const targetPath = Constants.logPath + '.' + time;
      files.set(srcPath, {srcPath, targetPath});
      return files;
    }
  }
  return new CusRotator({app});
};

module.exports = app => {
  const rotator = getRotator(app);
  return {
    schedule: {
      type: 'worker',
      interval: '1m',
    },
    * task() {
      yield rotator.rotate();
    }
  }
};
```

**Comment by atian25** [comment]
重新排版下，三个 ` 才是 code block

**Comment by losefish** [comment]
不好意思，排版没检查……

**Comment by atian25** [comment]
@losefish 没那么复杂，看 https://github.com/atian25/egg-showcase/pull/3/files

**Comment by losefish** [comment]
呃，你给我的链接我试过，它类似于 [https://eggjs.org/zh-cn/core/logger.html](url) 中的**自定义日志**，这的确可以完成日志分割，但是**customLogger的日志格式不支持自定义**。
// config.default.js
```
module.exports = appInfo => {
  customLogger: {
      myLogger: {
        file: Constants.logPath,
      }
    },
}
```

//app/homeController.js
```
class HomeController extends Controller {
  * home() {
    const {ctx} = this;
    const logger = ctx.app.loggers.get('myLogger');
    logger.info('test');
}
```
输出日志的格式是
```
2017-09-18 17:25:51,494 INFO 83206 test
```
而我想变成 
```
 2017-09-18|17:25:51|[I]|test
```
这样的形式

**Comment by losefish** [comment]
如果在customLogger增加formatter配置，format不会生效，和这个  [https://github.com/eggjs/egg/issues/827](url) 情况一样。

**Comment by popomore** [comment]
我看 file 是有的，console 没有，因为本地开发有自定义

**Comment by losefish** [comment]
@popomore 不好意思没明白，可以详细解释一下吗？
总结来说我现在要做的事情就是 **自定义日志格式、完成日志分割**

**Comment by popomore** [comment]
使用 customLogger 的 formatter 应该能格式化文件的，但是 console 的不受影响。

**Comment by atian25** [comment]
@losefish 你再看看我给的示例代码，加了 `formatter`

**Comment by atian25** [comment]
https://github.com/eggjs/egg-logger/blob/8eb166defc57bb263a03babe7321bd513df88ab8/lib/egg/logger.js#L40

**Comment by losefish** [comment]
@atian25 十分感谢，示例代码生效了。
