### ISSUE TITLE
schedule里不能执行controller？

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1437]
作者你好！
schedule里不能执行controller？ 
是不是我的写法不对？

``
module.exports = app => {
	return {
	    schedule: {
	      interval: '5s',
	      type: 'worker'
	    },
	    task(ctx) {
	    	ctx.app.controller.xxx.xxxx()
	    }
	};
};
``

**Comment by atian25** [comment]
Controller 是一个 Http 请求的控制器，业务逻辑应该放到 Service 中。

schedule 这种后台任务应该调用 Service，而不是 Controller。
