### ISSUE TITLE
使用egg-graphql，get方式如何获取请求查询数据

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#1438]
![default](https://user-images.githubusercontent.com/21269645/30534453-df3692c8-9c90-11e7-9752-6466174998bc.png)
这个是我的postman的请求

我的路由代码
module.exports = function(app) {
app.get('/user', function* () {
console.log(this.request);
this.body = yield this.graphql.query(JSON.stringify(req));
});
};

console.log(this.request);的打印结果
查询条件在url里，那我要获取到query={user(id:"1"){name}}，只能字符串解析吗？还是有别的方式，我原来以为可以获取ctx的，结果里面是｛｝
我尝试在function* (ctx)加入ctx参数，但里面是｛｝，我也尝试const ctx = app.mockContext();也不行

**Comment by grubed** [comment]
![default](https://user-images.githubusercontent.com/21269645/30534615-88e6e1d8-9c91-11e7-9c89-bd053a51e36c.png)

**Comment by jtyjty99999** [comment]
不好意思，刚看到，
 传到后端的字符串你可以参考   https://github.com/eggjs/egg-graphql/blob/master/test/fixtures/apps/graphql-app/app/router.js#L5

**Comment by jtyjty99999** [comment]
另外我个人是不推荐在get请求使用graphql的，可能导致查询字符串过长，可以使用post

**Comment by grubed** [comment]
这个不对啊，我是从postman发来的请求获取数据，你发的这个是自己模拟定义了req

**Comment by jtyjty99999** [comment]
这是个例子啊，表示`this.graphql.query()` 接收的是一个什么样的参数，你可以接收postman的请求， 然后自己构造这个 req啊

**Comment by jtyjty99999** [comment]
比如举个例子

```
'use strict';

module.exports = function(app) {
  app.get('/user', function* () {

   const input = `{
        user(id: 2) {
          name
        }
      }` // (from  postman:  this.request.query.input)

    const req = {
      query: input,
    };

    this.body = yield this.graphql.query(JSON.stringify(req));
  });
};

```

**Comment by grubed** [comment]
非常感谢，我要的答案就是这句 this.request.query.input

**Comment by grubed** [comment]
@jtyjty99999 另外我个人是不推荐在get请求使用graphql的，可能导致查询字符串过长，可以使用post

因为考虑到http协议get有缓存，但当我看到dataloader也做缓存的时候，是不是用post也可以达到http get那样的缓存效果？
