### ISSUE TITLE
DELETE 请求 报 invalid csrf token 错误

### ISSUE THREAD

**Issue by xumjs8623** [eggjs/egg#1439]
* **Node Version**: v7.9.0
* **Egg Version**: 1.7.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我采用文档中RESTful API的方式写接口，get post put 请求都没有任何问题，但是delete就是报csrf token无效，不知道是否delete请求要进行特殊设置么
![image](https://user-images.githubusercontent.com/12467615/30572938-6f34d366-9d23-11e7-94fb-3e95348328a6.png)
![image](https://user-images.githubusercontent.com/12467615/30572940-74fd86f8-9d23-11e7-8bc4-5038fb94acc0.png)

**Comment by solarhell** [comment]
delete请求也必须指明
```
    delete: function (id, call) {
        $.ajax({
            url: '/api/admin/feedback/' + id,
            type: 'DELETE',
            contentType: "application/json"
        }).done(function (result) {
        }).fail(function (result) {
        })
```

**Comment by jtyjty99999** [comment]
我本地没重现，能否给个代码仓库例子

**Comment by solarhell** [comment]
这个问题我之前用axios也发现了...
axios.delete()默认不带任何body和content-type头
后来```
axios({
  method: 'delete',
  url: 'xxx',
  headers: {content-type': 'application/json'}
});
```
才成 因为csrf过滤规则代码 我看了就是一定要有json的请求头

**Comment by solarhell** [comment]
https://github.com/eggjs/egg-security/blob/3fa64e1bec32ed5258c11b0211b3143a60999967/lib/middlewares/csrf.js#L25

**Comment by xumjs8623** [comment]
@solarhell   好的  谢谢 我去看看，我用的就是axios

**Comment by popomore** [comment]
fetch 也有这个问题

**Comment by jtyjty99999** [comment]
isXHR/ignoreJSON这种场景我补充到文档里

**Comment by xumjs8623** [comment]
解决了，axios设置Content-Type也碰到问题，一直无法生效。最后通过这里才解决，https://github.com/mzabriskie/axios/issues/362     谢谢大家
