### ISSUE TITLE
关于插件依赖开启的问题

### ISSUE THREAD

**Issue by imshenyz** [eggjs/egg#1441]
* **Node Version**: 8.4.0
* **Egg Version**: 1.7.0
* **Plugin Name**: none
* **Plugin Version**: none
* **Platform**: macOS 10.12.6
* **Mini Showcase Repository**: none

你好，请问一下我的egg项目中需要用到egg-a插件，其中egg-a插件又依赖egg-b插件，已经在egg-a中配置开启了egg-b插件了，但是好像对于项目来说无效，必须在项目中显式地同时开启egg-a和egg-b吗？

**Comment by ngot** [comment]
可以看看这里的详细解释： https://eggjs.org/zh-cn/advanced/plugin.html#插件的依赖管理

**Comment by atian25** [comment]
1. 插件本身 `package.json` 里面的 `eggPlugin.dependencies` 只是声明 egg 依赖，它本身不会把对方作为一个 npm 的依赖，没有加到 `dependencies` 节点，也不能加。

2. 故在应用里面，需要手动引入两个插件，并开启

3. 如果此类场景比较多，你们就需要考虑封装上层框架，对应用开发者屏蔽这些细节。

**Comment by imshenyz** [comment]
明白了，感谢答复。 @atian25 @ngot
