### ISSUE TITLE
bodyparser spend a lot of time

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1443]
* **Node Version**:  8.x
* **Egg Version**:  1.x
* **Plugin Name**: koa-bodyparser
* **Plugin Version**: 2.5.0
* **Platform**: Linux
* **Mini Showcase Repository**:

当我在使用POST传数据的时候启用了 `bodyparser` 并且设置为
 ```js
  config.bodyParser = {
    jsonLimit: '50mb',
    formLimit: '50mb',
  };
```

然后我传入的数据为`map =  { key: value }` ,只不过这个 value 是 **图片的base64** 的值，所以会显得很大，并且我设置timeout 为 **5s**。
然后我在服务器端使用 `ctx.request.body.map` 来获取到数据，结果发现:
> 当我前端都已经报超时了以后，服务器端才过一会收到map值 (我使用200kb左右大小图片测试) ;

所以我猜测是bodyparse导致耗时过多。

不知道是否是我使用的问题还是确实需要这么久的时间，假如是必须这么久的时间有什么可替代方案。

服务器端代码：
```js
const Koa = require('koa');
const bodyParser = require('koa-bodyparser');

const app = new Koa();

app.use(bodyParser({
  formLimit: '50mb',
  jsonLimit: '50mb',
}));

app.use(ctx => {
  const { map } = ctx.request.body;

  console.log(map);

  ctx.body = 2333;
});

app.listen(9000);

```

**Comment by atian25** [comment]
没看懂，服务端代码怎么是 koa？

**Comment by skyfore** [comment]
因为我看egg也是用的koa-bodyparser，所以就简单的写了个服务器代码来测试

**Comment by skyfore** [comment]
然后发现在bodyparser解析的时候耗费的时间非常长。

**Comment by skyfore** [comment]
好吧，我重新用egg来写。

egg：

```js
// app/controller/home.js
'use strict';

module.exports = app => {
  class HomeController extends app.Controller {
    * map() {
      const { map } = this.ctx.request.body;
      console.log(map);
      this.ctx.body = 23333;
    }
  }
  return HomeController;
};


// app/router.js
'use strict';

module.exports = app => {
  app.post('/saveMap', 'home.map');
};

// config/config.default.js
'use strict';

module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1505803459071_1521';

  // add your config here
  config.middleware = [];

  config.bodyParser = {
    jsonLimit: '50mb',
    formLimit: '50mb',
  };
  return config;
};


```

前端发送的数据：
![image](https://user-images.githubusercontent.com/7485049/30581111-9024f3a2-9d51-11e7-8884-290db029212a.png)



我的意思就是在处理这种数据的时候，bodyparser会非常耗时，假如前端设置了比较短的 timeout 那么可能在后端 bodyparser还没处理完之前就以及timeout了。我不知道是否只有我的电脑才是这样处理时间比较久。
![image](https://user-images.githubusercontent.com/7485049/30581237-0a7965f2-9d52-11e7-9b62-e17c7dbcc6c7.png)

**Comment by skyfore** [comment]
@atian25

**Comment by skyfore** [comment]
经过排查发现我在虚拟机中会出现上述的问题，直接在宿主机中运行并没有此现象所以关闭.
