### ISSUE TITLE
如何mock egg里面继承controller父类胡方法？

### ISSUE THREAD

**Issue by 799677446** [eggjs/egg#1444]
* index() {
      const pageData = yield {
        // 检查登录
        loginInfo: this.checkLogin(true),
  
        leftNavStatus: 'chainClick', // 判断当前左侧导航是否为选中状态
        dataUrl: this.dataUrl,
      };
        yield this.ctx.render('page/shop/analysis/guide-dredge/index.html', pageData);
   
    }

**Comment by 799677446** [comment]
`const assert = require('assert');
const mm = require('egg-mock');

describe('test/app/controller/shop/analysis/advancedData/chainClick.test.js', () => {
  let app;
  before(() => {
    app = mm.app();
    return app.ready();
  });

  afterEach(mm.restore);

  it('should GET /analysis/chain-click', function* () {
    // const result = yield request(app.callback()).get('/analysis/chain-click').expect(302)
    // app.mockService('shop/analysis/advancedData/chainService', 'getData', function* (ctx, methodName, args) {
    //   return 'popomore';
    // });
    // app.mockService('home.common.htmlPartService', 'getCommon', function* (ctx, methodName, args) {
    //   return 'popomore';
    // });
    // app.mockContext({
    //   checkLogin() {
    //     return 'dfdf';
    //   },
    // });
    // const result = yield app.httpRequest()
    // .get('/analysis/chain-click')
    // .expect(200)
    // .expect('hello world');
    // // 也可以这样验证
    // assert(result.status === 200);
    app.mockService('user', 'getName', function* (ctx, methodName, args) {
      return 'popomore';
    });
    const ctx = app.mockContext();
    yield ctx.service.user.getName();
  });
});`

**Comment by 799677446** [comment]
文档里面app.mockService例子运行报错

**Comment by a526672351** [comment]
看了https://eggjs.org/zh-cn/basics/controller.html#自定义-controller-基类 和 egg-mock文档的确没发现有可以mock  controller-基类的方法

**Comment by popomore** [comment]
Require 那个类，mock prototype 的方法

**Comment by a526672351** [comment]
是继承的一个Controller的扩展基类里面有个checkLogin的控制层方法，这个egg-mock没有提供mock基类的controller的方法，能不能提供一个类似app.mockService的app.mockController的api来支持模拟控制层继承的方法？

**Comment by atian25** [comment]
你可以写一个 `application.unittest.js` 来提供自定义的 mock 方法，参见 https://github.com/atian25/egg-showcase/pull/4/files

**Comment by a526672351** [comment]
还可以这样玩666，为什么不继承到egg-mock里面？

**Comment by atian25** [comment]
我重新更新了下代码，不需要用 `application.unittest.js` 了，直接在用例里面 mock 即可

```js
const { app, assert, mm } = require('egg-mock/bootstrap');

describe('test/app/controller/home.test.js', () => {
  it('should GET /', () => {
    app.mockControllerEcho();
    mm(app.Controller.prototype, 'echo', function(name) {
      this.ctx.body = `hi, mock ${name}`;
    });
    return app.httpRequest()
      .get('/')
      .expect('hi, mock egg')
      .expect(200);
  });
});
```

**Comment by atian25** [comment]
不集成的原因是，Controller 这个场景感觉没太大的需求需要 mock。

而 `application.unittest.js` 的使用场景其实是在插件里面，插件负责自己的 mock api，这个挺优雅的。

**Comment by a526672351** [comment]
app.mockControllerEcho(); 这句是不是应该删除？

**Comment by atian25** [comment]
嗯
