### ISSUE TITLE
egg 的日志输出，能输出在哪个文件的哪一行吗？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#1445]
egg 的日志输出，能输出在哪个文件的哪一行吗？

**Comment by atian25** [comment]
跟 Egg 关系不大，Node 的代码行数只有在 error stack 上有，如果你有需要就自己 new 一个拿到，但性能方面就。。。

**Comment by runhwguo** [comment]
@atian25 egg框架本身可以提供支持么，我觉得这个还是很常用的。性能方面当然要考虑，local可以默认开，production默认关。希望框架本身提供这个能力。

**Comment by atian25** [comment]
按我上面的说法自己配置个 custom logger 的 format 即可
