### ISSUE TITLE
为什么我用egg-scripts启动应用时，在配置文件里配置了日志输出目录不起作用？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#1446]
```
  config.logger = {
    level: 'DEBUG',
    consoleLevel: 'DEBUG',
    dir: '/mnt/data/webapps/ra-api/logs',
  };
```
当用egg-scripts启动应用的时候，我在配置文件里配置了日志输出目录，可是日志还是输出到默认的日志目录下呢？

**Comment by solarhell** [comment]
看一下 `run/application_config.json` 里 `logger`的 `dir` 是不是你配置的这个目录。
如果不是 说明配置文件优先级有问题，没生效。
@atian25 感觉这种配置文件问题的issue可以加个tips，就是看下`run`目录里最终合并生成的配置文件?

**Comment by arden** [comment]
```
    "logger": {
      "dir": "/mnt/data/webapps/ra-api/logs",
      "encoding": "utf8",
      "env": "prod",
      "level": "INFO",
      "consoleLevel": "DEBUG",
      "disableConsoleAfterReady": true,
      "outputJSON": false,
      "buffer": true,
      "appLogName": "ra-api-web.log",
      "coreLogName": "egg-web.log",
      "agentLogName": "egg-agent.log",
      "errorLogName": "common-error.log",
      "coreLogger": {},
      "type": "application"
    },
```
是这个目录，因为我用egg-bin开发模式启动应用的时候是正常的。

**Comment by atian25** [comment]
@solarhell 没用的，大写的 FAQ 在这里：https://eggjs.org/zh-cn/faq.html#为什么我的配置不生效

@arden 我本地无法复现

![image](https://user-images.githubusercontent.com/227713/30623895-fa75b5ca-9dec-11e7-815a-4e3a2cc76bdf.png)

**Comment by arden** [comment]
@atian25 我再好好检查一下看看。以前一直是在egg-bin下启动，看有没有什么没注意到的地方。

**Comment by alex-zhang** [comment]
目前看代码是写死的啊

**Comment by atian25** [comment]
@alex-zhang 你理解错了，这个 issue 的那个配置是指 egg-web.log 这些 log，而所谓的`写死` 是指 master 的日志，那个在 https://github.com/eggjs/egg/issues/1395 里面。

**Comment by atian25** [comment]
先关闭了，如果还有问题，请提供最小可复现仓库，然后开启
