### ISSUE TITLE
一个对接上的问题

### ISSUE THREAD

**Issue by Blackgan3** [eggjs/egg#1447]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

使用egg-cluster的多线程来和rabbitmq做结合，开启多个worker作为rabbitmq的consumer，这个衔接部分？？？？有没有相关经验的

**Comment by atian25** [comment]
@ngot 分享下?

**Comment by ngot** [comment]
这个就是我们用的这个吧 https://github.com/node-modules/cluster-client

**Comment by Blackgan3** [comment]
嗯嗯，好的，我的场景是使用rabbitmq来作为消息队列进行消息的转发，我去研究下你们封装的这个。
