### ISSUE TITLE
MIME设置

### ISSUE THREAD

**Issue by yale8848** [eggjs/egg#1448]
请问如何配置新的MIME类型？

**Comment by atian25** [comment]
need not information

**Comment by yale8848** [comment]
准备要给demo.appcache静态h5缓存配置文件添加 MIME-type(text/cache-manifest)映射，请问如果配置？

**Comment by atian25** [comment]
`this.type = 'appcache';`

https://github.com/jshttp/mime-db/blob/9dd00b34556a8cdd6f3385f09d4989298c4b86e1/src/apache-types.json#L3023

**Comment by yale8848** [comment]
谢谢，看到了，koa 默认用的就是mime-db ，默认已经配置好了appcache 映射了
