### ISSUE TITLE
Is there a plan to support ESM ？

### ISSUE THREAD

**Issue by leaves4j** [eggjs/egg#1450]
Node V8.5 contains support for ES Modules, [ECMAScript Modules](https://nodejs.org/dist/latest-v8.x/docs/api/esm.html)

**Comment by atian25** [comment]
ESM is still a early version, don't support require by CJM, so these is not plan until this feature is stable.

发自我的 iPhone

**Comment by 510846** [comment]
是否可以出一个工具，可以将 eggjs 转为 ESM 代码？ ~
