### ISSUE TITLE
[support]运行过程中通过代码修改配置文件的问题

### ISSUE THREAD

**Issue by junyuz** [eggjs/egg#1451]
* **Node Version**:8.2
* **Egg Version**:1.8.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:win10
* **Mini Showcase Repository**:

通过this.ctx.app.config.xxx可以很方便的读取配置，如果我在代码的逻辑中，需要把一些信息写入配置文件（修改原有配置项的value），该如何操作，通过fs来写文件？
直接调用this.ctx.app.config.xxx=111，并没有把111写入到配置文件中

**Comment by atian25** [comment]
不建议通过修改文件的方式来修改，因为你的下一次部署就有可能覆盖掉，正确的做法应该是用数据库之类的地方存储配置。

如果实在不行，那就搞一个单独的目录，然后 config 里面去 require 吧，至于修改，自己用 fs 即可，注意多进程情况下，你修改了文件，其他 worker 不会生效，需要通过消息传过去。

**Comment by junyuz** [comment]
好的，明白了，看来还是存数据库吧
