### ISSUE TITLE
【讨论】关于lowDB的一些想法

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#1452]
最近了解了下这个东西，有用这个东西存储egg配置的一些想法。
设想的好处如下

1. 配置可通过接口、后台设置页面简单修改框架配置(如数据库服务器ip)。
2. 可以简单的集成一些应用配置项的修改。
3. 方便构建配置管理工具。

主要缺点就是与现在的框架配置方式不统一。
个人还不成熟的一个想法。

**Comment by duncup** [comment]
可以简单理解为使用json格式存储配置并集成lowDB进行配置读写。

**Comment by atian25** [comment]
没看懂 lowdb 替换目前的 config 有什么优势？

目前 config 是可以通过 beforeStart 里面读取远端配置的，你这里真的有需求的话，可以自己写个插件来实现。

**Comment by duncup** [comment]
嗯，远程配置确实可以解决需求，只是现在要弄的项目太小不值得为此搞个远端配置。我只是在考虑本地可修改配置的可行性。插件这个方案自然是可行的。
