### ISSUE TITLE
eggjs控制台满屏警告

### ISSUE THREAD

**Issue by abuyao** [eggjs/egg#1453]
eggjs的控制台满屏都是警告。
node[5128] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

**Comment by abuyao** [comment]
准确来说，主要是我app文件夹内有一个node_modules文件夹。能告诉我怎么配置，可以避免监听app文件里的node_modules文件吗？

**Comment by atian25** [comment]
为什么你会在 app 目录有 node_modules ?

**Comment by duncup** [comment]
app目录不应存在node_modules目录，需要引用的node模块应当存放在app上级目录(项目根目录)下的node_modules目录中。
