### ISSUE TITLE
框架开发与配置问题

### ISSUE THREAD

**Issue by dahuahe** [eggjs/egg#1454]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

再看了框架有一点懵。现在遇见这个问题。还请确认一下。
框架：
         plugin加入sequelize
         config.default           写好了app的配置 config.app={sequelize:{/*config*/}}
我以为当我去app编写代码且运行的时候是不需要配置sequelize 运行报错，不得不在app里面的
config.default 又写了一遍配置
结论：
        框架的config只是做一些差异化 或者信息的配置 并不能配置app的插件配置信息？

**Comment by atian25** [comment]
你的配置是错的，所以你结论是错的。

框架的配置写法和应用没有任何区别。

你应该 `config.sequelize = {}` 而不是 `config.app={sequelize:{/config/}}`

**Comment by dahuahe** [comment]
谢谢指教。因为看到 init 的framework 中有配置 config.test={key:''} 误解以为能够在这里配置各个apps的配置信息替代apps的每个config.default.js

**Comment by dahuahe** [comment]
@atian25  
发现model 文件在框架app/model里面不会被加载,我在框架的app.js 执行 beforeStart => model.sync 虽然运行了但是没有建表.发现只有放在应用的app/model 才会起作用,这是model不应该放在框架还是?

**Comment by atian25** [comment]
egg-sequelize 的实现问题，它没去加载其他 LoadUnits

https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L47

**Comment by dahuahe** [comment]
@atian25  小弟不才,怎么解决呢?给个方向 我想把framework做成一个大的服务 model和service都放在framework

**Comment by atian25** [comment]
要推动 egg-sequelize 优化下。

cc @popomore @jtyjty99999 @huacnlee

**Comment by dahuahe** [comment]
那么这种情况mongoose 会不会出现呢?如果一个项目里面有两个数据库  model文件会冲突吗?

**Comment by dead-horse** [comment]
sequelize model 只支持应用层，不支持框架层。已支持自定义加载文件目录和多数据源。
