### ISSUE TITLE
httpclient中的curl返回的buffer默认是什么编码格式

### ISSUE THREAD

**Issue by GitHubForQiuKai** [eggjs/egg#1455]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
https://www.npmjs.com/package/urllib

你遇到的具体问题是?

如果只是转码啥的， `curl(url, { dateType: 'json'})`

**Comment by GitHubForQiuKai** [comment]
默认的编码是'utf8'、'ascii'？还是其他类型的

**Comment by popomore** [comment]
Buffer 是没有编码的，你转的时候才有

**Comment by GitHubForQiuKai** [comment]
好的

**Comment by ngot** [comment]
Buffer没有编码的、在你使用的时候需要去解码。

**Comment by atian25** [comment]
可以看下内置的处理方式 https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L932

**Comment by GitHubForQiuKai** [comment]
@atian25 嗯，默认是按utf8解析body的。
