### ISSUE TITLE
egg-graphql如何调用model里的对象

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#1456]
* **Node Version**:8.2.1
* **Egg Version**:^1.7.0
* **Plugin Name**:egg-graphql
* **Plugin Version**:1.0.0
* **Platform**:windows 7 64x
* **Mini Showcase Repository**:_

我用了egg-graphql里的test，connector.js里 UserConnector 将  fetch修改成如下

    * fetch(ids) {
        return yield this.ctx.model.user.find(ids);
        // return Promise.resolve(ids.map(id => ({
        //   id,
        //   name: `name${id}`,
        //   password: `password${id}`,
        //   projects: [],
        // })));
      }
目的是想调用model里的user.find,发现不成功，我不知道如何调用

**Comment by atian25** [comment]
- 请按 Issue 模板反馈问题
- 请学习 markdown 语法，学习 code 排版

**Comment by grubed** [comment]
@atian25 非常感谢指导，您看这样写行吗
