### ISSUE TITLE
启动后报错 Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by chemandy** [eggjs/egg#1457]
api@1.0.0 start /api
> EGG_SERVER_ENV=prod egg-scripts start --port=7001 --daemon --title=egg-server-api

[egg-scripts] starting egg application at /api
[egg-scripts] run node /api/node_modules/egg-scripts/lib/start-cluster {"v":false,"port":7001,"title":"egg-server-api","framework":"/api/node_modules/egg","baseDir":"/api"} --title=egg-server-api
[egg-scripts] save log file to /root/logs/api
/api/node_modules/egg-scripts/lib/cmd/start.js:127
          this.logger.info(`egg started on ${msg.data.address}`);
                                                     ^

TypeError: Cannot read property 'address' of undefined
    at ChildProcess.child.on.msg (/api/node_modules/egg-scripts/lib/cmd/start.js:127:54)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.11.1/bin/node" "/root/.nvm/versions/node/v6.11.1/bin/npm" "run" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

每次调用npm run start就会报错

**Comment by popomore** [comment]
执行 npm update

**Comment by chemandy** [comment]
@popomore 感谢，问题已解决
