### ISSUE TITLE
自定义目录规范

### ISSUE THREAD

**Issue by zhaotoday** [eggjs/egg#1458]
Egg 目前支持修改现有的目录规范吗？比如某些目录/文件我认为是复数比较合理，怎么修改？如改成：
```
|-- app
|   |-- router.js
|   |-- controllers
|   |-- services
|   |-- middlewares
|   |-- public
|   |-- views
|   |-- extends
|       |-- helpers.js
...
```
补充一下，我是 Node JS 初学者，有看到文档有提到这个，也就是 Loader 可以实现，但我还是不知道怎么实现，请大神解答。

**Comment by atian25** [comment]
可以通过 loader 自定义，看下文档还有 egg-core 源码

发自我的 iPhone

**Comment by zhaotoday** [comment]
@atian25 谢谢，我详细了解下。
