### ISSUE TITLE
egg如何升级到最新版本？

### ISSUE THREAD

**Issue by kiinlam** [eggjs/egg#1461]
是不是只要单独npm update到最新版本就可以了？还是说有其他方式？

**Comment by atian25** [comment]
`npm update` 好像更新子依赖有问题，直接粗暴点用 `rm -rf node_modules && npm install`

**Comment by popomore** [comment]
不要使用 package-lock.json

**Comment by atian25** [comment]
看来应该是 
`rm -rf node_modules && rm -rf package-lock.json && npm install`

**Comment by solarhell** [comment]
可以加到脚手架默认的`.gitignore`里

**Comment by atian25** [comment]
加了没用，`npm install` 后会自动生成

**Comment by solarhell** [comment]
加到post install里可以吗？

2017年9月25日 +0800 AM11:54 TZ | 天猪 <notifications@github.com>，写道：

**Comment by atian25** [comment]
不确定，要试了才知道。不过这是用户的选择了，踩坑也没办法。

万恶的 lock。

**Comment by popomore** [comment]
自动删除也会被吐槽的，只能说推荐用 cnpm
