### ISSUE TITLE
请问多个worker如何共用一个缓存？

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#1462]
站点里想定时拉取一些数据，目前使用了schedule功能，type是all，即多个worker每个都会拉一次

现在想只有随机一个worker拉取，其他的都能访问，尝试设置成worker，但是遇到一个问题，这些worker如何共享一份数据？ 将数据直接放在app对象里好像不行，测试发现每个worker都有独立的app对象。

问题：请问多个worker如何共用一个缓存？

**Comment by atian25** [comment]
简单的做法是：改为 `worker` 一个去拉取，拉完后通过 `messenger` 发给其他 worker。

高级的做法看 https://eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by skyfore** [comment]
@miaojiuchen  我使用的是 memcache 专门做状态机， 相关插件可以看  [egg-memcache](https://github.com/skyfore/egg-memcache)

**Comment by atian25** [comment]
通过 memcache / redis 外面来搞是最佳方式，因为 agent 的方式，在集群情况下就没辙了。

**Comment by skyfore** [comment]
@atian25 请问下，我自己写的 egg-memcache 能加入到 eggjs group 中吗？

**Comment by atian25** [comment]
@skyfore 不一定必须要加到 egg 这边的，你看 koa 生态很多库都是开枝散叶的。这里很多库都想分出去了。

**Comment by skyfore** [comment]
@atian25  恩，OK～
