### ISSUE TITLE
json数据格式API化

### ISSUE THREAD

**Issue by beliefgp** [eggjs/egg#1464]
有个想法，在输出JSON数据格式的时候，是不是应该在`ctx`上提供一个统一的API。
每个项目，制定的规范不一样，比如:

有些项目返回格式是：

```json
{
    resultCode: 0,
    resultMsg: '',
    content: {}
}
```
有些项目是：

```json
{
    code: 0,
    message: '',
    data: {}
}
```

当前onerror及其一些插件，返回的json是固定了格式的，如果有些项目是第一种格式，用这些插件，就会造成同一个接口，可能返回多种json格式。

考虑，是否提供一个统一的方法，来标准化格式，所有相关插件返回json格式都调用该方法，用户可以重写该方法。
比如在`ctx`上扩展
```js
{
    wrapJson(data, code, message, addition) { 
        if (is.object(code)) {
           addition = code;
           code = '';
         }

         return Object.assign({
            result: code ? 'fail' : 'success',
            code: code || 0,
            message: msg,
            data,
          }, addition);
    }
}
```

**Comment by atian25** [comment]
这种每个团队都可能不一样，自己封装插件就好了吧。

可以看下内网死马那边 TWA 的实践，看能否沉淀出来

发自我的 iPhone

**Comment by popomore** [comment]
onerror 的问题是要解决的，已经有 issue 的。标准化这个事情没必要做，做上层框架可以增加更多约定，但不是在 egg。

**Comment by beliefgp** [comment]
我意思主要是提供一个统一的api，上层框架可以重写，其他如error统一调用，这样就把格式统一了，具体说明标准那是每个团队去定的

**Comment by jtyjty99999** [comment]
我们团队之前推过一个规范

```

/**
 * 统一返回对象
 */
function ResultDto(data) {
  data = data || {};

  // 接口执行是否成功，这里的成功指没有发生异常并且接口成功执行完逻辑
  if (data.errorCode) {
    this.success = false;
  } else if (data.hasOwnProperty('success')) {
    this.success = !!data.success;
  } else {
    this.success = true;
  }

  /**
   * 1、如果接口执行发生错误，这时会返回错误码 <br/>
   * 2、错误分类：系统级错误、服务级错误 <br/>
   * 3、error code表示：系统级错误，用1XXXX表示，可以重试；服务级错误，用2XXXX表示，不建议重试。<br/>
   * 4、其中前两个“XX”表示系统层面或业务层面的分类。后两个“XX”标识具体异常。<br/>
   * 关于前两个“XX”的举例，系统级错误比如：uic、fileserver；服务级错误比如：图片、分组。
   */
  this.errorCode = data.errorCode || 0;

  /**
   * 1、如果接口执行发生错误，这时会返回错误信息给调用方，方便快速定位。<br/>
   * 2、尽管根据Error Code也能定位到问题(通过我们的文档定位错误信息)，但是
   */
  this.errorMsg = data.errorMsg || '';

  // 返回模型
  this.object = data.object;
}

```

然后把这个挂载到ctx上，使用`this.model.resultDto(data)` 来返回

**Comment by dead-horse** [comment]
@beliefgp onerror 之类的处理一般来说上层也会全部封装掉，不会用默认的 onerror 插件的，所以这个意义不大。

**Comment by beliefgp** [comment]
我觉的肯定还是有用onerror兜底的……比如我最初就这样，后来发现onerror返回的格式和原定的接口格式不一样，只能强制和onerror统一了，幸好是新项目

**Comment by okoala** [comment]
一般是直接扩展 Error 对象， 然后直接抛对应的异常吧。或者写个独立的插件？ 现在貌似有了

**Comment by beliefgp** [comment]
@okoala  我现在就在用我参考贯高他们讨论的和我的一些想法写的[egg-bizerror](https://github.com/beliefgp/egg-bizerror)，看来需要配置可以强制拦截了。

这个问题，主要是想到刚开始还不太熟悉egg时，用onerror来兜底异常时，发现onerror返回的json格式`{code: 0, message: ''}`，和原来制定的格式不一致，又没法改，只能向onerror看齐了。

**Comment by tinyhill** [comment]
我目前的策略是，提供 error 中间件包装固定错误格式，正确响应时直接 jsonp 输出。

**Comment by atian25** [comment]
这个现在是什么情况了?

**Comment by solarhell** [comment]
所以现在要把异常和期望返回全部封装成json输出，有好的办法吗？
我期望的是这样
```json
{
  "code": 10004,
  "message": "Token required",
  "data": {}
}
```
正常输出
```json
{
  "code": 0,
  "message": "success",
  "data": {
    "id": 1
  }
}
```

**Comment by atian25** [comment]
@solarhell https://github.com/eggjs/egg-onerror#usage
