### ISSUE TITLE
egg-graphql希望能给一个写数据的示例

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#1465]
egg-graphql的示例里有了查询Query，但没有写操作Mutation，希望示例能多点

**Comment by jtyjty99999** [comment]
好的，我晚些时候补充一个吧

**Comment by jtyjty99999** [comment]
graphql主要是用于数据查询的，写最好还是通过orm框架去写

**Comment by jtyjty99999** [comment]
如果更新数据可以使用 mutation 操作，跟 query 操作语法类似的。

**Comment by jtyjty99999** [comment]
收到，我后面补一个例子吧

**Comment by jtyjty99999** [comment]
https://github.com/freebyron/egg-graphql-boilerplate/blob/master/test/app/graphql/item.test.js#L23  这有个同学写的例子，把以前的query改成mutation，之后需要对应实现下mutation 对应的connector 和 resolver https://github.com/freebyron/egg-graphql-boilerplate/blob/master/app/graphql/tag/connector.js#L18
