### ISSUE TITLE
按照文档使用vscode调试报错了

### ISSUE THREAD

**Issue by weihomechen** [eggjs/egg#1466]
* **Node Version**:  8.2.1
* **Egg Version**: 1.9.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: macos 
* **Mini Showcase Repository**:

hi，按照官网上的[文档](https://eggjs.org/zh-cn/core/development.html)配置的，按F5后启动debugger，后面报了下图这个错误：

![image](https://user-images.githubusercontent.com/16172317/30854750-38dbec28-a278-11e7-9359-0596c755fcbc.png)

`launch.json`文件 :
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Egg",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "npm",
      "windows": {
        "runtimeExecutable": "npm.cmd"
      },
      "runtimeArgs": [
        "run",
        "debug"
      ],
      "console": "integratedTerminal",
      "protocol": "auto",
      "restart": true,
      "port": 9999
    }
  ]
}
```
求解，🙏

**Comment by atian25** [comment]
试下 rm -rf node_modules && npm install

发自我的 iPhone

**Comment by atian25** [comment]
rm -rf package-lock.json && rm -rf node_modules && npm install

发自我的 iPhone

**Comment by weihomechen** [comment]
@atian25  重新install后仍然报了一样的错误

**Comment by atian25** [comment]
截图下控制台输出

**Comment by weihomechen** [comment]
这个是终端：

<img width="903" alt="qq20170927-093309 2x" src="https://user-images.githubusercontent.com/16172317/30891656-229439a2-a2fa-11e7-89eb-80c3153e8ff9.png">

```bash
➜ weihome@moyu  ~/projects/microants-blog git:(dev) ✗ cd /Users/weihome/projects/microants-blog ; /usr/local/bin/npm run debug

> microants-blog@0.0.1 debug /Users/weihome/projects/microants-blog
> egg-bin debug

Debugger listening on ws://127.0.0.1:9229/e78d0a09-bba9-4023-9c34-f5b569d2987a
For help see https://nodejs.org/en/docs/inspector
2017-09-27 09:30:18,372 INFO 12272 [master] egg version 1.9.0
Debugger listening on ws://127.0.0.1:5800/d4dc8073-7725-4043-9122-0e708cf05459
For help see https://nodejs.org/en/docs/inspector
2017-09-27 09:30:19,075 INFO 12272 [master] agent_worker#1:12273 started (695ms)
Debugger listening on ws://127.0.0.1:9230/12f58cef-789b-438f-b6ed-95e5a23761a2
For help see https://nodejs.org/en/docs/inspector
2017-09-27 09:30:20,020 WARN 12274 [egg-security] Please set `match` or `ignore` on sub config
2017-09-27 09:30:20,059 INFO 12272 [master] egg started on http://127.0.0.1:7001 (1685ms)
```

调试控制台：
```bash
Debugging with inspector protocol because a runtime executable is set.
```

图片半天传不上去，我就直接复制文字啦 @atian25

**Comment by atian25** [comment]
先执行下 `node node_modules/.bin/egg-bin --version` 看看 egg-bin 版本。

再用 `egg-init --type=simple showcase` 新建一个全新的项目试试看。

我怀疑你的 `egg-bin` 是旧的，正常的输出是这样的

![image](https://user-images.githubusercontent.com/227713/30891858-205839e4-a2fb-11e7-824f-f74a91f68b8a.png)

- `9230 opened Debug Proxy online` 这行 proxy 成功后是肯定会输出的
- `DevTools →` 这个在非 vscode 中启动才输出.

**Comment by weihomechen** [comment]
ebb-bin是3.7版本的：
![image](https://user-images.githubusercontent.com/16172317/30891983-b1dd294c-a2fb-11e7-8225-0061b248b843.png)

嗯那我新建个项目看看吧

**Comment by atian25** [comment]
太旧了，现在都 4.3.2 了，执行下 
```bash
$ npm run autod
$ rm -rf package-lock.json
$ rm -rf node_modules
$ npm install
```

**Comment by AkashiX** [comment]
@atian25 ```jsnpm run autod```会把其他第三方依赖给干掉～

**Comment by atian25** [comment]
没有被 require 的，会干掉。

可以参考 https://github.com/eggjs/egg/blob/master/.autod.conf.js 配置

**Comment by GoBrianGo** [comment]
我也有这个错误，Debugging with inspector protocol because a runtime executable is set. 不知道是什么问题。

**Comment by atian25** [comment]
> Debugging with inspector protocol because a runtime executable is set. 

這句不是報錯，有問題反饋請提供完整的信息。

**Comment by GoBrianGo** [comment]
用egg-bin可以调试了现在，可是报了其他的错，
![image](https://user-images.githubusercontent.com/9709359/32526471-09f22c7c-c3ef-11e7-9bd9-4ab78c25666b.png)，在启动的时候报了很多这种的错，都说找不到某个文件

**Comment by atian25** [comment]
這個就是你自己的庫的問題了，egg-bin 只是幫你傳遞了 --inspect 給 node 而已，沒有做什麼特殊的事。

**Comment by GoBrianGo** [comment]
![image](https://user-images.githubusercontent.com/9709359/32526614-ef6abc9c-c3ef-11e7-8e23-0761aa1f0065.png)
偶尔会出现上面这个报错，很奇怪，可是我没改过什么东西，上一次都可以成功调试，这一次就又报这个错。还有上面我说的报错的问题，有些报错的是egg的库的问题喔，
![image](https://user-images.githubusercontent.com/9709359/32526738-8f9ad1a2-c3f0-11e7-857c-a2418a6daf4f.png)

**Comment by GoBrianGo** [comment]
@atian25 好，我自己先新建个项目试试，还有个问题就是egg-bin debug 是使用默认端口7001起服务调试的，可是我的index.js 
![image](https://user-images.githubusercontent.com/9709359/32526992-cbdc154e-c3f1-11e7-8180-c76deb447175.png)
是设置了别的端口的。

**Comment by atian25** [comment]
egg-bin 不会读取 index.js 的，也不需要这个文件了。

`egg-bin debug --port=xxxx` ，可以看下 README 和文档。

**Comment by GoBrianGo** [comment]
好的，感谢。

**Comment by GoBrianGo** [comment]
![image](https://user-images.githubusercontent.com/9709359/33756241-870c4b68-dc2f-11e7-9d4e-edf9719ca3ca.png)
启动了调试，可是断不了点是什么问题呢，@atian25

**Comment by atian25** [comment]
这种反馈是没有任何可讨论价值的，我今天经常跑厕所，有什么问题你能知道么？

- 请先用 egg-init 实例化一个新的测试项目，然后用 vscode-eggjs 插件生成调试配置，验证下是否有问题 （排除项目配置问题）
- 断点的位置是哪里

**Comment by GoBrianGo** [comment]
新建项目是可以调试的，可是我的项目使用插件生成的配置
![image](https://user-images.githubusercontent.com/9709359/33757024-3a75e382-dc33-11e7-8cf3-f93ea3d3d9b7.png)
会启动不成功
![image](https://user-images.githubusercontent.com/9709359/33757080-7ff89f62-dc33-11e7-98aa-5b1ce0e50d33.png)

**Comment by GoBrianGo** [comment]
知道问题了，是egg-bin的版本太低了，更新了就没问题了。thx
