### ISSUE TITLE
基础功能框架扩展 求助！！

### ISSUE THREAD

**Issue by rickXiaoLive** [eggjs/egg#1470]
在基础功能的框架扩展里面，如果我想要对后个对象进行扩展，但是这个里面的逻辑需要用到异步的处理，如：在redis里面取一个数据放进来使用，该怎么做啊？或者该看点什么资料来学习啊？

**Comment by atian25** [comment]
> 在基础功能的框架扩展里面，如果我想要对后个对象进行扩展

没看懂，最好给点伪代码

**Comment by rickXiaoLive** [comment]
//  app/extend/application.js


'use strict';
const WECHAT_ACCESS_TOKEN = Symbol('Application#WECHAT_ACCESS_TOKEN');
module.exports = {
    get weChatAccessToken() {

        // this 就是 app 对象，在其中可以调用 app 上的其他方法，或访问属性
        // 这里是给 app 对象添加一个 WECHAT_ACCESS_TOKEN 的属性，方便后面使用和节约性能
            if (!this[WECHAT_ACCESS_TOKEN]) {
                let accessToken = {};
                //检查accessToken是否过期 以及更新accessToken
                accessToken = yield this.redis.get('accessToken'); //此处不能使用 yield因为不是 * 函数 此处的异步一般是如何处理的呢？ 感谢你的回答
                if (!accessToken) {
                    //调用微信获取 accessToken 接口
                    const getAccessTokenUrl = `https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${this.config.weChat.appID}&secret=${this.config.weChat.appsecret}`;
                    const res = yield app.curl(getAccessTokenUrl, {dataType: 'json'});
                    yield this.redis.set('accessToken', JSON.stringify(res.data), 'px',res.data.expires_in * 1000 - 300000);//生命周期设置少5分防止程序使用之前的缓存出错
                    accessToken = getAccessTokenUrl;
                }
                this[WECHAT_ACCESS_TOKEN] = accessToken.access_token;
            }

            console.log(123);
            console.log(this[WECHAT_ACCESS_TOKEN]);

            return this[WECHAT_ACCESS_TOKEN];

        //这里是最终想要的效果
        //return 'rqBllrCEvux_JztPnUrnn0G-Y_ccRU7wYppxNBH2g1OwjOwtpZUfJTiWvBrUnMP7v23cCT4UjTdBKFU7ih61q74c0eNxB3sC_4kNe5f3MzgL99qICRBNliO1HYFLFeGtMPJdAEAUXR';
    },
};

**Comment by popomore** [comment]
那就定义成 generator function

```js
module.exports = {
  * weChatAccessToken() {
  },
};
```

**Comment by atian25** [comment]
1. 注意 markdown 的排版啊， 三个 `
2. js 的 getter 不支持异步，不能直接改为  `* getWeChatAccessToken() {}` 么？

**Comment by rickXiaoLive** [comment]
牛逼了我的大婶们，万分感谢！！！脑袋生锈了
