### ISSUE TITLE
请问如何在业务层里面自定义mysql日志?

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#1478]
现在我公司需要记录错作者对数据库的增加,更新，删除的mysql原生语句到数据库!请问有没有方法实现，谢谢.............

**Comment by popomore** [comment]
这是用的哪个插件

**Comment by xinnian1992** [comment]
不晓得,现在就是不晓得怎么办，求解决之法

**Comment by atian25** [comment]
问的是，你用哪一个插件来操作 mysql

**Comment by xinnian1992** [comment]
就是eggjs自带的mysql

**Comment by solarhell** [comment]
@atian25 那个得去改`ali-rds` 那边用的是`debug`来输出到终端

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/1512

**Comment by xinnian1992** [comment]
我不是要输出到终端,我想把mysql的插入，更新，删除这些重要的mysql原生语句插入到数据库

**Comment by xinnian1992** [comment]
从而来记录数据库重要日志

**Comment by xinnian1992** [comment]
@atian25

**Comment by atian25** [comment]
能输出，就能 tranform 到其他存储。

就目前而言，自己在 Service 包一下吧。

**Comment by sunfuze** [comment]
可以用 egg-knex，执行后通过 query 事件去拿，具体看 knexjs 文档。

xinnian1992 <notifications@github.com> 于 2017年9月29日周五 下午3:39写道：

**Comment by xinnian1992** [comment]
谢谢，我试一下

**Comment by xinnian1992** [comment]
@sunfuze
