### ISSUE TITLE
全局状态 && 进程间状态共享

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1480]
* **Node Version**: 8.x
* **Egg Version**: latest
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: Linux
* **Mini Showcase Repository**:

1.你好，请问假如我需要给在server上定义一个 **全局** 的状态，我应该写在哪里？
我之前尝试过直接挂载到app 对象上，但是这样我有可能命名的时候会覆盖到原有的属性，所以我想问一下官方的建议是什么？

2.然后，我还想了解一下关于多进程方面的问题，我写一个简单的请求时计数的程序，然后我发现会有多进程方面的问题，我暂时没有找到解决的办法，所以请求指点。

```js
//  app.js
module.exports = (app) => {
  app.count = 0;
  app.messenger.on('addCount', () => {
    app.count += 1;
  });
};


// app/controller/home.js
module.exports = app => {
  class HomeController extends app.Controller {
    * index() {
      const { ctx, app } = this;
      app.messenger.sendToApp('addCount');
      ctx.body = app.count;
    }
  }
  return HomeController;
};

```

在这里我虽然用这种方式达到了Worker间的状态统一，但是由于IPC通信也是异步的，这样就会造成在状态未同步的情况下就返回结果。

比如我用这样的测试脚本就会返回类似与这样的：
```bash
#!/usr/bin/bash

for i in {1..8}
do
  curl localhost:7001 &
done

```
预期中的结果是 `01234567`, 但是真实的结果是 `00000225` 这种类似。

所以希望能指点应该如何去处理这种情况。

> PS: CPU为8核，所以会启动8个Worker，然后我希望的解决方案是框架层面的，而不是使用数据库来存储类似的方法。希望能得到解答，十分感谢。

**Comment by popomore** [comment]
server 不应该有状态，应该存 DB 或缓存，读写要注意锁的问题。

PS：你的原始需求是什么，具体要解决什么问题，你说的都是方案。

**Comment by skyfore** [comment]
我提出这个问题是因为在我的业务逻辑中，

类似于这样;

```js
//  app.js

module.exports = (app) => {
  function * setup () {
    const result = yield //  一些异步的操作，这些操作会返回一些状态。
    app.customerStatus = result;
  }

  app.beforeStart(setup);
};
//  因为需要确认结果所以需要放在app.js中

// app/controller/index.js
const Controller = require('egg').Controller;
class Index extends Controller {
  * changeStatus () {
    // 做一些操作并且最后修改状态

    const { app, ctx } = this;
    app.customerStatus = null;
    ctx.status = 200;
  }

  * looprequest () {
    //  定时请求该URL

    const { app, ctx } = this;
    if (app.customerStatus) {
      ctx.body = 'something';
    } else {
      ctx.body = 'other';
    }
  }
}

module.exports = Index;


```

**原始需求**
1. 希望在服务器端保存一个状态 (如果觉得不合理希望能给我一个合理的建议，谢谢 :smile: !)
2. 这个状态能适用于多进程。

**解决问题** 
1. 在哪里保存这样一个状态，app 对象上吗？
2. 保存这样的状态如何在多进程中同步。

感谢解答，:grinning:

**Comment by popomore** [comment]
放 db 不行吗，每次查一下，如果要求高性能中间可以加一层缓存。

有状态的服务已经不是多进程同步的问题了，是无法水平扩展的，你要考虑多台服务器之前如何同步状态。

**Comment by popomore** [comment]
已经是架构问题了，不是框架问题了。

**Comment by atian25** [comment]
> 我之前尝试过直接挂载到app 对象上，但是这样我有可能命名的时候会覆盖到原有的属性，所以我想问一下官方的建议是什么？

你起一个特殊的名字不就好了，实在担心覆盖，就用 `Symbol`。

> //  定时请求该URL

- 为什么定时的请求不放到 `schedule` 定时任务来做？
- 在一个 worker 里面做任务，然后发消息通知其他的 worker 同步数据（不要大量数据）

> 然后我希望的解决方案是框架层面的，而不是使用数据库来存储类似的方法。

框架层面有一些 hack 方法可以做到，但不建议。此类场景应该考虑外部存储的方式。

**Comment by Yamilemon** [comment]
想问问看到底有啥hack方法可以做到，因为我也遇到了和这个issue的人一样的问题，不过我是想全局共享一份数据，而且这份数据是会更新的，但是我又有点不太想为了就共享一份数据的功能而引入数据库。

**Comment by Yamilemon** [comment]
> > 我之前尝试过直接挂载到app 对象上，但是这样我有可能命名的时候会覆盖到原有的属性，所以我想问一下官方的建议是什么？
> 
> 你起一个特殊的名字不就好了，实在担心覆盖，就用 `Symbol`。
> 
> > //  定时请求该URL
> 
> * 为什么定时的请求不放到 `schedule` 定时任务来做？
> * 在一个 worker 里面做任务，然后发消息通知其他的 worker 同步数据（不要大量数据）
> 
> > 然后我希望的解决方案是框架层面的，而不是使用数据库来存储类似的方法。
> 
> 框架层面有一些 hack 方法可以做到，但不建议。此类场景应该考虑外部存储的方式。



> > 我之前尝试过直接挂载到app 对象上，但是这样我有可能命名的时候会覆盖到原有的属性，所以我想问一下官方的建议是什么？
> 
> 你起一个特殊的名字不就好了，实在担心覆盖，就用 `Symbol`。
> 
> > //  定时请求该URL
> 
> * 为什么定时的请求不放到 `schedule` 定时任务来做？
> * 在一个 worker 里面做任务，然后发消息通知其他的 worker 同步数据（不要大量数据）
> 
> > 然后我希望的解决方案是框架层面的，而不是使用数据库来存储类似的方法。
> 
> 框架层面有一些 hack 方法可以做到，但不建议。此类场景应该考虑外部存储的方式。

想问问看到底有啥hack方法可以做到，因为我也遇到了和这个issue的人一样的问题，不过我是想全局共享一份数据，而且这份数据是会更新的，但是我又有点不太想为了就共享一份数据的功能而引入数据库。
