### ISSUE TITLE
调试时发生异常

### ISSUE THREAD

**Issue by weihomechen** [eggjs/egg#1481]
* **Node Version**: 8.2
* **Egg Version**: 1.9
* **Plugin Name**: egg-bin
* **Plugin Version**: 4.3.3
* **Platform**:
* **Mini Showcase Repository**:

使用vscode调试，入口处的断点是有调试到的：
![image](https://user-images.githubusercontent.com/16172317/31043589-6b7aa386-a584-11e7-8dad-90216fd25baf.png)
点下一步后就抛出一连串错误了：
![image](https://user-images.githubusercontent.com/16172317/31043595-905db832-a584-11e7-8835-c19c61f48d02.png)
![image](https://user-images.githubusercontent.com/16172317/31043597-9b2ee696-a584-11e7-82ab-1b1602e7e92f.png)
![image](https://user-images.githubusercontent.com/16172317/31043600-acbb3b4e-a584-11e7-8cce-500c9bb7de1b.png)
一系列都是这样的错误，然后后续的断点就调不到了

**Comment by atian25** [comment]
请提供最小可复现仓库，以及详细的调试复现步骤。

**Comment by weihomechen** [comment]
在本地把`node_modules`删了重装没有用，先提交，然后把本地项目删了，再从远程仓库clone下来，就可以调试了，一脸蒙蔽，提交完按理说应该是一毛一样的啊。。。

**Comment by atian25** [comment]
> 删了重装没有用

是不是又踩了 lock 的坑？
