### ISSUE TITLE
Controller 下创建基类，好像跟文件名有关系，如果一个类的文件名自然排序 在基类的文件名上 那么就不能继承这个基类

### ISSUE THREAD

**Issue by iamxz** [eggjs/egg#1482]
![image](https://user-images.githubusercontent.com/1449558/31043801-e02a5926-a587-11e7-893b-4bbce77e7407.png)

admin.js 不能继承
下面的都可以

**Comment by atian25** [comment]
说明可以再去看看文档， app.js 是根目录，而不是 Controller 目录下。

**Comment by iamxz** [comment]
多谢！！

**Comment by atian25** [comment]
文档再看看吧，是根目录下 app.js 而不是放在 controller 目录

发自我的 iPhone
