### ISSUE TITLE
启动路径问题

### ISSUE THREAD

**Issue by hellopao** [eggjs/egg#1483]
`package.json`在根目录，服务端代码在子目录，在根目录启动服务的时候报找不到`package.json`。不想把`package.json`拷到子目录去，框架应该要支持这个吧。

![image](https://user-images.githubusercontent.com/5064875/31043962-83b81c48-a5f8-11e7-8ce2-0f47b3d5fcb4.png)

**Comment by popomore** [comment]
把 package.json 放到 server 下面

**Comment by hellopao** [comment]
@popomore 我觉得这算是个bug。

**Comment by atian25** [comment]
不算 bug，你既然都指定 baseDir 了，那肯定所有相关的代码和数据都在这个目录下了。

`getFrameworkPath` 会根据 `baseDir` 去找 `package.json` 以及 `node_modules` 下的框架地址。

它不可能这样：
- `app` 和 `config` 等代码在 baseDir 下找。
- 而 `package.json` 和 `node_modules` 却去你的 egg-bin 的执行路径。

**Comment by hellopao** [comment]
@atian25  意思是`package.json`必须和`app`在同一个目录？那`baseDir`的意义是什么？

**Comment by atian25** [comment]
- `getFrameworkPath` 是自动寻找上层框架用的，framework 这些是运行期依赖。
-  而 `egg-bin` 是一个工具，它是一个开发期依赖，（也可以不作为项目的依赖的，如全局安装，虽然我们不推荐），`baseDir` 就可以用于指定应用的位置。

**Comment by winixt** [comment]
@atian25 为什么不考虑往上一个目录寻找呢？

**Comment by songguangyu** [comment]
如果前端项目和服务端项目放在一起 公用package.json， 服务端和前端是两个子目录，这样的需求很常见吧？我觉得这个是应该可以之支持的，谢谢。@popomore
