### ISSUE TITLE
怎么写 基类的构造函数 让所有的 实例化的类都继承它

### ISSUE THREAD

**Issue by iamxz** [eggjs/egg#1484]
我想在 基类的constructor 里面写 登录判断，可以通过这种方法实现吗？

**Comment by atian25** [comment]
你对生命周期的理解有误：

- `Controller` 是在 `启动期` 去实例化的
- `登陆` 是跟用户相关的，是跟 `运行期` 的某一个用户请求有关。

这类需求应该通过中间件解决，具体看看 middleware 和 router 的文档，以及 egg-passport 插件。
