### ISSUE TITLE
How can i use this with Babel?

### ISSUE THREAD

**Issue by MrHerickS** [eggjs/egg#1489]
Hey guys, i'm having some troubles trying to use this lib with babel.

Can someone provide a step by step guide?

Thank u guys btw.

**Comment by tz5514** [comment]
you can create an `app.js` file at root directory and require babel-register.

--------
app.js
```js
require('babel-register');
```

But this way seen like doesn't work for ES6 modules to commonJS transpiling

**Comment by atian25** [comment]
@MrHerickS I wonder which feature missing at Node 8.x do you need with babel ?

**Comment by MrHerickS** [comment]
@tz5514 that worked! Thank you.

@atian25 i like it by the simplicity on some functions (i'm starting using babel these weeks), but let me ask you something, do you think it will affect the performance at all?

**Comment by atian25** [comment]
`babel-register`  will compile code in memory when first meet one file, so it will make some cost, thanks to egg loader, it is completed in the loading phase initialization, so the performance of the loss is not very different. 

The keypoint is **not necessary**,  Node 8.x support almost all the es2015~2017 features. And `babel` is a black box, it will introduce unnecessary risks. 

As a server application, it require long-term operation and stability. So I don't see any reason to use babel.

**Comment by atian25** [comment]
@tz5514 also need to add `${app_root}/agent.js`.

**Comment by MrHerickS** [comment]
@atian25 thank you for the explanation! Now i feel comfortable to be using without babel, especially about the error log thing.

Thank you guys! Have a nice time.
