### ISSUE TITLE
Easy way to disable a middleware

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#149]
例如我要关闭 siteFile https://github.com/eggjs/egg/blob/master/config/config.default.js#L186 ，目前在应用层基本很难关闭。

可以尝试增加一个 disableMiddlewares 的配置来关闭掉。

```js
exports.disableMiddlewares = {
  siteFile: true,
};
```

或许有更好的方式。

**Comment by atian25** [comment]
目前能在 app.js 里用 splice 的方式干掉.

```js
module.exports = app => {
  const index = app.config.coreMiddleware.indexOf('static');
  if (index !== -1) {
    app.logger.info('remove static middleware');
    app.config.coreMiddleware.splice(index, 1);
    console.log(app.config.coreMiddleware);
  }
};
```

**Comment by fengmk2** [comment]
这样对应用开发者来说太复杂了

**Comment by popomore** [comment]
app.disableMiddleware('static')

配置数组还是有坑。

**Comment by dead-horse** [comment]
把这个功能集成到默认的中间件上面去？ https://github.com/eggjs/egg/pull/150

**Comment by dead-horse** [comment]
上周鱼姐就碰到了 bodyparser 不能关闭的情况

**Comment by fengmk2** [comment]
@dead-horse 👍

**Comment by popomore** [comment]
是指配 enable 的方式?

**Comment by dead-horse** [comment]
如果我们给 coreMiddlewares 的定位是框架 + 插件定义的中间件的话，我们可以给所有的 coreMiddlewares 都通过这个方法加上 `enable / match / ignore` 的支持？

**Comment by dead-horse** [comment]
直接在 loader 那层做了

**Comment by popomore** [comment]
可以
