### ISSUE TITLE
有关上传文件  :  nodejs.unhandledExceptionError: read ECONNRESET

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1490]
* **Node Version**:8.6
* **Egg Version**:1.9
* **Plugin Name**:multipart
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

主要代码;
```
"use strict";
const fs=require('fs'),
    path = require('path');
module.exports = app => {
    return class PostController extends app.Controller {
        * index() {
            //头信息
            const headers=this.ctx.get('content-type');//application/x-www-form-urlencoded
            console.log(headers);//输出头信息
            const files = this.ctx.multipart();//获取上传实例;
            let files2;
            while (files2 = yield files) {
                if (files2._readableState.buffer.head){
                    try {
                        const ws = fs.createWriteStream('./app/storage/'+files2.filename);
                        files2.pipe(ws);
                    }
                    catch (err){
                        console.log(err)
                    }
                }
            }
        }
    };
};
```

在确认fileSize为2048mb的情况下,上传1G的文件
报错信息如下-->
```
2017-10-07 00:11:29,695 ERROR 4324 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:1019:11)
    at TCP.onread (net.js:608:25)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'unhandledExceptionError'
pid: 4324
hostname: rockeyµÄ±Ê¼Ç±¾
```

`[2017-10-07 00:36:12.663] [cfork:master:3216] worker:10236 exit (code: null, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: undefined)`

问题:
1--请问multipart有提供解决服务会话超时的方法吗?
2--另外,multipart这个插件我尝试过用async function,结果莫名其妙获取不到上传的数据
我这个问题跟之前一个issue提到的一样 链接:[https://github.com/eggjs/egg/issues/1316](https://github.com/eggjs/egg/issues/1316)
我前几天也提交过一个issue  链接:[https://github.com/eggjs/egg/issues/1487](https://github.com/eggjs/egg/issues/1487)
3--请问multipart可以跟getFileStream()一样获取表单参数吗?还是单纯的只能上传文件?

**Comment by popomore** [comment]
你这个 pipe 写成异步的了，res 已经返回了

**Comment by newcomein** [comment]
@popomore 我修改成 yield files2.pipe(ws);  之后传输大文件仍然会出错  但是小文件正常返回了

**Comment by newcomein** [comment]
@popomore 方便提供修改方法吗?

**Comment by popomore** [comment]
https://github.com/node-modules/await-stream-ready

**Comment by newcomein** [comment]
我把整个项目部署到服务器测试之后,发现上传文件的功能没有任何异常,后来排查得知是WebStorm的问题,因为我一直都是直接在WebStorm里面npm启动项目,WebStorm会有会话超时限制.

**Comment by newcomein** [comment]
2--另外,multipart这个插件我尝试过用async function,结果莫名其妙获取不到上传的数据
我这个问题跟之前一个issue提到的一样 链接:#1316
我前几天也提交过一个issue 链接:#1487
3--请问multipart可以跟getFileStream()一样获取表单参数吗?还是单纯的只能上传文件?
