### ISSUE TITLE
如何配置egg-static,使用浏览器访问/public/ 输出/public/index.html

### ISSUE THREAD

**Issue by xcstream** [eggjs/egg#1492]
* **Node Version**:
* **Egg Version**:egg@1.9.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
/public/index.html可以,  /public/ 404

config.default.js是这样的:
```
'use strict';

module.exports = appInfo => {
  const config = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1507383951618_490';

  // add your config here
  config.middleware = [];
  config.static = {
      maxAge: 31536000,
      prefix: '/public',
      index: 'index.html'
  }
  return config;
};

```

**Comment by popomore** [comment]
不支持目录

**Comment by zzyyzz1992** [comment]
@popomore 
不支持目录可以理解，但是首页也是这样404总不行吧？
http://localhost:7001/ => 404
http://localhost:7001/index.html => OK

**Comment by zzyyzz1992** [comment]
import { controller, get, provide } from 'midway';

Solved!
@provide()
@controller('/')
export class HomeController {

  @get('/')
  async index(ctx) {
    ctx.redirect('/index.html')
  }
}

**Comment by haua** [comment]
config.siteFile = {
    '/public/': fs.readFileSync(path.join(appInfo.baseDir, 'app/public/index.html')),
};

在配置里加上上面这个就行，不过如果你有很多index.html，就不方便了
