### ISSUE TITLE
egg-sequelize 的 sequelize 版本应该更新了，有很重要的更新

### ISSUE THREAD

**Issue by THaGKI9** [eggjs/egg#1493]
sequelize 前阵子有一个更新，更新了构造 sql 请求的时候一些操作符的使用方式，能够大大的增强 sql 操作的安全性

[feat(query-generator): change operators to be represented by symbols](https://github.com/sequelize/sequelize/commit/ccb99daedb69e8750a241436415ccac8abef358d)

希望 egg-sequelize 可以跟进一下^-^

**Comment by popomore** [comment]
重新安装即可

**Comment by ngot** [comment]
sequelize的版本是自动更新的，无需关心

**Comment by atian25** [comment]
只要你别用 yarn 或 npm 5 锁版本

发自我的 iPhone

**Comment by THaGKI9** [comment]
这就删了yarn
