### ISSUE TITLE
egg-sequelize 的问题

### ISSUE THREAD

**Issue by zhaotoday** [eggjs/egg#1494]
在用 egg-sequelize 的时候，执行 `npm run migrate:new` 命令报错：
Error: Dialect needs to be explicitly supplied as of v4.0.0

**Comment by solarhell** [comment]
数据库配置文件把 `Dialect ` 写上去啊

**Comment by zhaotoday** [comment]
@solarhell 配了，dialect: 'mysql'。

**Comment by huacnlee** [comment]
配置文件贴出来看看

**Comment by zhaotoday** [comment]
@huacnlee 
这是框架里的 `config.default.js` 配置：
https://github.com/zhaotoday/node-core/blob/master/config/config.default.js#L16
其他数据库相关的比较敏感的配置我写在应用里了。

**Comment by atian25** [comment]
@zhaotoday 顺便提下，你的 `config.view` 写了两个互相覆盖了。

**Comment by zhaotoday** [comment]
@atian25 手误，我改下。
