### ISSUE TITLE
请问怎么设置egg项目开机自动启动?

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1495]
* **Node Version**:8.6
* **Egg Version**:1.9
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问在centos7.3系统下 有办法让egg开机自动启动吗?

**Comment by popomore** [comment]
自己看看 linux 怎么启动的，这个和 egg 有啥关系。

**Comment by newcomein** [comment]
_(:3 」∠)_   我想着egg会不会有神秘buff加成

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/core/deployment.html#部署

正常部署就可以了

**Comment by atian25** [comment]
看下 linux 开机启动的相关文章吧，然后在对应的 sh 里面执行 npm start 即可。

**Comment by newcomein** [comment]
昂 \(•ㅂ•)/♥    阿里嘎多

**Comment by ReviewClouds** [comment]
现在egg的package.json在/opt/ap/ap里面，要执行npm start就要先进来这个文件夹，现在测试发现启动执行的shell，是进入到指定目录了，但npm start并没有执行，因为端口没有占用，连错误输出都没有，有什么办法解决吗
