### ISSUE TITLE
eggjs有没有考虑依赖注入的问题？

### ISSUE THREAD

**Issue by lijialing888** [eggjs/egg#1496]
大型应用依赖关系很复杂，目前的Service机制感觉不够用，是否有考虑提供依赖注入的办法，比如集成：http://inversify.io/ 组件？

**Comment by atian25** [comment]
没看懂，不够用指，怎么个依赖注入法？

提供下伪代码来讨论吧

**Comment by popomore** [comment]
之后可能会结合 TS 和 decoretor 来做，不过优先级还不高。

**Comment by lijialing888** [comment]
@atian25：
```js
@injectable()
class Something {
    @inject(Another)
    private another:Another;
}
```
在Something中不需要关心如何构造another对象，在Java开发中很常用。

**Comment by atian25** [comment]
这个就是 decoretor 了。

**Comment by popomore** [comment]
关闭了，近期不会做这个。
