### ISSUE TITLE
关于插件依赖的开启和关闭

### ISSUE THREAD

**Issue by acthtml** [eggjs/egg#1497]
插件的依赖关系如下：

- easyvue
  - vue
  - vuessr
  - webpack
  - webpackvue

我封装了easyvue，目的是应用层不用管理vue/webpack这些细节，所以希望这些子插件的开启关闭也应该有父插件来完成。我这么做了但是并没有达到效果：

1. 在easyvue的plugin.js开启子插件(lib/plugin/egg-easyvue/config/plugin.js)
2. 应用层开启只开启easyvue插件(config/plugin.js)

我看了报错日志，猜测加载顺序如下，先加载config/plugin.js，试图开启easyvue，发现其依赖的子插件并没有开启，进行报错。

难道我只能在应用层显示的开启这些子插件？

**Comment by popomore** [comment]
这个是框架做的事情

**Comment by atian25** [comment]
插件自己的 package.json 只是声明依赖关系，而不是用来开启依赖的。

需要在应用层，或者在上层框架来做。

**Comment by acthtml** [comment]
看来目前只能如此。

**Comment by atian25** [comment]
自己封装一个上层框架就 ok 了

**Comment by acthtml** [comment]
目前，还没接触到自定义框架，改加载流程这块。
我先把easyvue对子插件的依赖去掉，在easyvue的配置中开启这些插件，并且在npm依赖声明里声明好这些包，这样也能让我的应用层忽略这些子插件的开启设置。

**Comment by atian25** [comment]
`父插件` 这个我们之前有讨论过的，叫 `插件集 plugin-bundle`，最后的结论是目前没有太大的场景，通过框架方式来承载就好了，框架也不复杂的，就一个 npm 包，带一个 plugin.js 就 ok 了。

**Comment by acthtml** [comment]
明白了。
插件本身是不是不会加载自身的plugin.js，文档上没注明，自己试了下是这么回事，大意了。

**Comment by acthtml** [comment]
这个项目有没有微信群？

**Comment by atian25** [comment]
文档补上了：https://github.com/eggjs/egg/pull/1499

> 这个项目有没有微信群？

我们推荐基于 GitLab Issue 的异步交流方式。
