### ISSUE TITLE
session共享问题

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1498]
* **Node Version**: 6.11.2
* **Egg Version**: 1.7.0
* **Plugin Name**: redis, session-redis
* **Plugin Version**: 1.0.2, 1.0.0
* **Platform**:
* **Mini Showcase Repository**:

我有一个项目A，和一个项目B。
我希望当用户在项目A中登录后，将uid存入session中，在项目B使用session可以获取到这个uid。
我目前想使用的是session-redis来解决这个问题。
但实际上在项目B中无法获取到uid。
是我遗漏了什么呢？

附加上config
```javascript
  // 项目A
  config.redis = {
    client: {
      port: 6379,
      host: IP,
      password: '',
      db: 15,
    },
  };

  // 项目B
config.redis = {
    clients: {
      a: { ... },
      b: { ... },
      session: {
        port: 6379,
        host: IP,
        password: '',
        db: 15,
      },
    },
  };

  config.sessionRedis = {
    name: 'session',
  };
```

config.keys 是相同的。

**Comment by popomore** [comment]
两个服务跨域了么

**Comment by liujinyang1994** [comment]
不好意思，解决了。 
是我粗心了。
是appInfo.name导致的问题。
@popomore 谢谢你的回复

**Comment by 359056163** [comment]
appinfo.name 改成一样的就可以了吗？
