### ISSUE TITLE
有没有ticktock的库？

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1502]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
是啥

**Comment by atian25** [comment]
什么东西?

**Comment by longxianlin** [comment]
为了创建一个商品支付倒计时。
订单创建，15分钟开始计时，15分钟后把订单关闭。

有其它方法吗？

**Comment by ngot** [comment]
订单这种，用单独的任务队列来做吧。

**Comment by atian25** [comment]
这个肯定是自己写啊，怎么可能是一个库能搞定的。

而且不要什么都想着官方提供，自己用 npm 的包引入就 ok 了。

**Comment by ngot** [comment]
Egg 主要是『请求-响应』模型的 web 应该场景。

订单延时处理这种，不属于 web 应用场景，需要自己写一个独立的 微服务 来处理，而且编程模型也不是『请求-响应』模型，需要另一个框架来解决。

**Comment by longxianlin** [comment]
非常谢谢。
请问阿里云的消息队列服务可以派上用场吗？
