### ISSUE TITLE
单元测试：如何只测试指定目录下的单元测试

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1503]
![image](https://user-images.githubusercontent.com/10094722/31374421-86ed9ca4-ad63-11e7-858f-973d04341c78.png)

我的test-app-controller 目录下有多个controller测试文件夹，如何只跑其中的某个文件夹中的单元测试

**Comment by atian25** [comment]
两种方法：
- 对要测试的方法加 `describe.only`
- `egg-bin test` 支持 glob 和 `--grep`，参见文档 https://github.com/eggjs/egg-bin#test

**Comment by zhaojunlike** [comment]
@atian25  老哥，我想测试单个文件 ，是不姿势不对呢
![image](https://user-images.githubusercontent.com/13638996/42610006-ffbe368e-85c1-11e8-855d-87d9dba0e682.png)

**Comment by zhaojunlike** [comment]
@atian25  我使用egg-bin test --typescript  -- file是可以的

**Comment by whxaxes** [comment]
@zhaojunlike  你试一下 `npm run test-local -- --ts test/app/service/fitone/Club.test.ts`

**Comment by zhaojunlike** [comment]
Maybe there is something wrong with my operation. I directly use the mocha use case of webstorm running. Maybe I should use yarn testing-local-ts file.js to execute a single file. Can you teach me how to perform tests individually? For example in mocha directly test ` ` ` it (...). ` ` `

**Comment by atian25** [comment]
if you use mocha directly in webstorm, you had to repeat all works we do in egg-bin test, see source for more details.
