### ISSUE TITLE
egg-static映射过来的目录，是否有必要考虑设置默认文档

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#1505]
* **Node Version**:8.4.0
* **Egg Version**:1.7.0
* **Plugin Name**:egg-static
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

需求很小，只是想咨询下，是否有这种实现，目前在文档里没有看到。

``` js
  config.static = {
    prefix: '/release/',
    dir: path.join(appInfo.baseDir, 'app/release'),
    // support lazy load
    dynamic: true,
    preload: false,
    buffer: false,
    maxFiles: 1000,
  };
```
release 是用来存放前端发布的dist目录文件，可能会有多个终端的站点，egg作为后端Server。

此时访问  ` localhost:7001\release\mobile ` ，很自然就认为会 自动跳转到 ` localhost\release\mobile\index.html` ，事实上返回了404 。

个人之前用IIS比较多，它一般会有个默认文档的配置，常见有如下项。
- index.html
- index.htm
- index.aspx
- defalut.aspx

是否考虑egg-static默认支持这种设置，或者开放配置呢。

**Comment by atian25** [comment]
没有计划支持这类功能。可以自己找个 koa 的插件，或者自己封装。

发自我的 iPhone

**Comment by dotnil** [comment]
这种用 nginx 的 try_files 比较合适（apache 也有类似的），不应该在 node.js 里造轮子
