### ISSUE TITLE
关于框架事件监听并触发的问题

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1507]
效果同“错误处理中间件”中的“app.emit('error', err, this);”一样，
**场景描述**：

- 监听上传事件后的写入日志
- 主文档修改标签后鉴听对应的子文档自动修改标签等

想达到的效果就是：一处定义监听事件，框架下处处都能触发执行，求解？

**Comment by atian25** [comment]
为什么要发事件呢？你上传的处理函数，写到 Service 里面，然后在这里个地方都写入，其他 Controller 都调用它不就行了？

**Comment by 89790094** [comment]
@atian25 只是举个应用的例子，如果要用事件监听的方法去实现呢？

**Comment by atian25** [comment]
具体场景具体分析，所以才需要阐述清楚场景。

就刚才你举得上传的场景，是可以通过更好的方式去做的。

**Comment by 89790094** [comment]
@atian25 首先感谢您的解答，如果写个监听事件去监听主文档修改标签的动作，而后去触发子文档修改标签，用事件如何实现？其实我最想知道的就是框架下如何使用事件监听以及触发去异步执行一些动作。

**Comment by atian25** [comment]
> 监听主文档修改标签的动作

这个没看懂啥意思，监控文件变更的话，有 egg-watcher

**Comment by atian25** [comment]
你现在先别管「事件」这个「解决方式」，而是先阐述清楚，你的出发点，你的应用场景，先别管具体实现方式。

可以看下 [X-Y PROBLEM](https://coolshell.cn/articles/10804.html)

![image](https://user-images.githubusercontent.com/227713/31420812-71e460e4-ae09-11e7-9e46-0751afbf374d.png)

**Comment by dead-horse** [comment]
框架不约束事件，也不提供特殊支持，你想怎么用 event 来实现都可以，这个没什么讨论的意义了。
