### ISSUE TITLE
[RFC] Singleton 增加 alias 配置参数

### ISSUE THREAD

**Issue by iyuq** [eggjs/egg#1509]
目前 `singleton`支持传入`name`参数，这样会去读取 `config[name]` 的配置当作初始化 `singleton` 的配置。而目前像 `egg-sequelize`  这样的插件定义是在 `app.model` 上，而配置却在 `config.sequelize`
 上，这样的不一致导致无法使用 `singleton`。

我的解决方案是，在创建 `singleton` 时在 `options` 上增加一个 `alias` 可选配置，如果 `options.alias`
 存在则加载 `client` 到 `app[alias]`上，不存在则默认加载到 `app[name]` 上。

**Comment by atian25** [comment]
@fengmk2 @popomore Review 下这个 RFC 是否可以做？

**Comment by atian25** [comment]
ping

**Comment by popomore** [comment]
主要是这里的约定，感觉可以加个参数

https://github.com/eggjs/egg/blob/master/lib/core/singleton.js#L16

https://github.com/eggjs/egg/blob/master/lib/core/singleton.js#L38

**Comment by iyuq** [comment]
@popomore @atian25  可以做的话我可以试试搞个PR。

**Comment by atian25** [comment]
干吧

**Comment by iyuq** [comment]
我在想是不是 `singleton` 支持钩子的话更好一点，毕竟 ORM 需要 loadModel，需要在 instance 挂到 app 上以后才能做, 加个 `beforeCreate` 和 `afterCreate` 的钩子是否能增加 `singleton` 的灵活度。

**Comment by popomore** [comment]
我觉得还是用 app.sequelize 比较好，可以试试加载两个 model 插件

**Comment by iyuq** [comment]
@popomore 确实用 app.sequelize 比较好，不过现有插件已经用的 app.model， 如果改的话会是 break change，所有用了这个插件的代码都得迁移。

**Comment by popomore** [comment]
Singleton 建在 sequelize 上，model 建个别名，define 的时候文档改下，就算 app.model 被覆盖也没关系

**Comment by iyuq** [comment]
> Singleton 建在 sequelize 上，model 建个别名，define 的时候文档改下，就算 app.model 被覆盖也没关系

这么说的话好像这个配置参数是可以不要了。不过现在 egg-sequelize 和 egg-mongoose 都是去加载 model下的所有文件的，不改这两个插件应该也共存不了。

**Comment by popomore** [comment]
有判断的

**Comment by iyuq** [comment]
现在 singleton 没有钩子，如果 egg-sequelize 这类插件要加载 model，要用如下写法：
```
  process.nextTick(() => {
    app.loader.loadToApp(dir, MODELS, {
      inject: app,
      caseStyle: 'upper',
      ignore: 'index.js',
    });
```
能否增加一个 afterCreate 的钩子，在 instance create 以后调用，这样可以把 load model 的逻辑写到钩子函数里面：

```
function afterCreate(config) {
   ...
   app.loader.loadToApp()
   ...
}
```

**Comment by popomore** [comment]
beforeStart 就是异步的啊

**Comment by iyuq** [comment]
不是异步，就是在 singleton 挂载到 app 上以后执行。
如果把 loadModel 逻辑写在 instanceCreate 的逻辑里，只有用异步方法，才能使 model/user.js 中的 app.model 已定义。增加钩子可以免去异步方法。

**Comment by popomore** [comment]
这两步现在也是分开的，就是把 app.model 定义改成 Singleton

**Comment by dead-horse** [comment]
先关了， sequelize 的问题不太适合用 singleton 解决
