### ISSUE TITLE
插件加载前启动函数

### ISSUE THREAD

**Issue by yesvods** [eggjs/egg#1510]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

使用MongoDB开发，在插件moogose加载之前，需要启动本地mongdb服务，但是app.beforeStart是在[插件加载完之后才执行的](https://eggjs.org/zh-cn/advanced/loader.html#文件顺序)，这就导致每次启动服务时候都会先报错链接失败。

请问一下有什么机制可以提供应用启动前执行环境配置的功能呢，谢谢

**Comment by dead-horse** [comment]
启动 mongodb 请通过启动脚本，放在启动 egg 服务之前。

**Comment by yesvods** [comment]
比如全局环境初始化，Promise切换到bluebird这种，插件也需要用到。

**Comment by atian25** [comment]
这些在插件里面去配置是没意义的，都在同一个进程了。

全局环境初始化 具体指?

**Comment by yesvods** [comment]
比如，有几个插件里面用到`Promise`。我希望所有运行的Promise都是基于Bluebird的，于是有

```
global.Promise = require("bluebird")
```

也有一种需求是新增全局变量，在其他地方可以便利使用`lodash`

```
global._ = require("lodash")
```

**Comment by JacksonTian** [comment]
```js
node -r pre_required.js app.js
```

**Comment by popomore** [comment]
这个你只能写框架来做，在 Application 里面实现。

**Comment by yesvods** [comment]
@JacksonTian 好的，感谢~

**Comment by atian25** [comment]
1. `global._` 这种严重不推荐。
2. `node -r pre_required.js app.js` 这个不行的，要在框架里面做，`Application` 和 `Agent` 都要。
3. 都 async 了，真的有必要 bluebird 么？

**Comment by yesvods** [comment]
有很多async都跑在Promise下面，用Bluebird一方面是性能，一方面是错误堆栈处理

**Comment by atian25** [comment]
node 8 的性能已经足够了，Bluebird 反而有可能慢。

堆栈的还是要靠 8.x 的 async hooks 吧，是吧？ @JacksonTian 朴老师

**Comment by atian25** [comment]
在 egg 的应用开发里面，应该很少会需要频繁 require 了吧，只需要在 extend 那边注入一次即可

**Comment by yesvods** [comment]
性能这块Bluebird对比原生实现做了优化，这个是5月的Benchmark，不知道node v8是否已经跑上去了。http://bluebirdjs.com/docs/benchmarks.html

**Comment by yesvods** [comment]
理解起来`extend`会在内置对象做功能增强&预处理，不过还是有一层析构成本。

**Comment by popomore** [comment]
这个是 Node7 吧。

**Comment by atian25** [comment]
这里讨论的有 2 个问题了：

1. @yesvods 提到的 `boostrap.js` -- 这个可以展开再聊下
2. 楼主提到的 Promise 性能问题 -- 我觉得嘛，就我们目前绝大部分应用的场景，还不需要去抠这个性能。

**Comment by yesvods** [comment]
其实楼主就是 @yesvods ..

嗯，扣性能这块是可有可无的，只不过提出了一下这种场景。需要在插件加载前，修改插件运行以来的环境，比如`require`，`module`这些场景

**Comment by atian25** [comment]
首先，要修改肯定是全局的，不是插件的，所有的插件都会在 worker 和 agent 里面加载的。

所以，要做这个事，肯定不可能在插件里面做，因为加载时序太晚了。

你真的想做，上面提了，在框架层，通过覆盖 Application 和 Agent 基类可以做到。

**Comment by yesvods** [comment]
其实也不希望入侵框架本身，像`require`这种全局性的修改，覆盖`Application`或者`Agent`也不太合理。

**Comment by atian25** [comment]
并不算侵入框架，而是在你自己的上层框架里面实现即可。

还有种方案就是朴老师说的 `-r`， https://nodejs.org/api/cli.html#cli_r_require_module
通过命令行启动时加入这个参数，但要试验下，我不确定目前在 master 加了后，会不会带给 worker 和 agent 进程，需要看下 egg-cluster 源码。

**Comment by atian25** [comment]
试了下， `NODE_OPTIONS='--require ./inject.js' npm run dev` 是可以的。

等 https://github.com/node-modules/common-bin/pull/18 后就可以 `egg-bin dev --node_options='--require ./inject.js'`

但还是觉得在上层框架层做好一点

**Comment by yesvods** [comment]
其实之前提到的启动数据库，在小型应用服务器场景，可以借用`egg`的`config`环境来启用，随着应用开关也是蛮好的。以及全局注入这块的问题。有一个类似`boostrap.js`的函数，就都可以解决掉了。

**Comment by atian25** [comment]
`启动数据库` 这块，肯定是要在 app.js 里面，`beforeStart` 来做的。

`全局注入` 那个刚才提了：
1. 必要性？
2. 既然是`全局`，肯定不会是在插件里面的，只能在**上层**框架，或者**上层**启动命令里面（egg-bin / egg-scripts)

**Comment by yesvods** [comment]
`启动数据库`如果在beforeStart来做，加载插件时候需要连接数据库就会失败的。

`全局注入` 其实还是开发便利性，不是必须的

**Comment by atian25** [comment]
> 启动 mongodb 请通过启动脚本，放在启动 egg 服务之前。

**Comment by popomore** [comment]
你就单机单库吗，不用水平扩展吗？

**Comment by yesvods** [comment]
准确来说，并不是一个mongodb，是一个实现服务端客户端通讯协议的本地服务，由这个本地服务向真实服务器通讯，水平扩展并不由这个服务负责。

**Comment by popomore** [comment]
参考下这个插件吧 https://github.com/eggjs/egg-mongoose

**Comment by yesvods** [comment]
可以理解为代理服务, mongoose(local) -> proxy of port 37017(local) -> remote mongodb server

**Comment by geesmart** [comment]
> 在 egg 的应用开发里面，应该很少会需要频繁 require 了吧，只需要在 extend 那边注入一次即可

请问下这个如何操作呢？谢谢 @atian25

**Comment by atian25** [comment]
可以参考下我们的一些插件的实现
