### ISSUE TITLE
如何设置站点二级目录？

### ISSUE THREAD

**Issue by acthtml** [eggjs/egg#1511]
目前想到的做法有2个：

1. 全手动，在设置static或router时手动加上二级目录，例如app.get('/二级目录/hello', 'hello.index')
2. nginx转发

这两个都有些不方便，有没有全局设置二级目录的地方，例如 config.site.root = '/二级目录/'?

**Comment by atian25** [comment]
`二级目录`? 你指的是这个 egg 应用的所有路由都加上同一个 prefix ?

**Comment by popomore** [comment]
static 可以啊，看 egg-static 具体配置

**Comment by acthtml** [comment]
@atian25 是的。

**Comment by atian25** [comment]
static 的有配置，router 的目前不支持 prefix。

@dead-horse 搞搞 https://github.com/eggjs/egg/issues/882 ？

**Comment by atian25** [comment]
临时方案是，你写一个函数，包裹 `app.get`，做这个事
