### ISSUE TITLE
求问egg怎么获取post请求的form-data数据？

### ISSUE THREAD

**Issue by cwc845982120** [eggjs/egg#1513]
求问egg怎么获取post请求的form-data数据？是与nodejs一样要安装中间件body-parse？

**Comment by atian25** [comment]
先把文档看一遍吧：https://eggjs.org/zh-cn/basics/controller.html

**Comment by cwc845982120** [comment]
"Content-Type"为"application/json"时ctx.request.body获取的一直是空对象。。。 @atian25

**Comment by atian25** [comment]
提供最小可复现代码。

顺便我想问问，提 issue 的时候，默认出来的那个模板里面应该写了要注明哪些东西吧？ 为何删掉不看？

**Comment by cwc845982120** [comment]
我的错。
我上图吧，入参是有的 但是命令行打印是一个空的对象

![Uploading WX20171011-184736@2x.png…]()
![Uploading WX20171011-184756@2x.png…]()
<img width="995" alt="wx20171011-184710 2x" src="https://user-images.githubusercontent.com/17759619/31436334-4566a36c-ae48-11e7-8e29-996beeda2986.png">

**Comment by cwc845982120** [comment]
![image](https://user-images.githubusercontent.com/17759619/31436797-ae8feeac-ae48-11e7-824f-989e34a489ca.png)
![image](https://user-images.githubusercontent.com/17759619/31436806-b5f9b628-ae48-11e7-812b-3c081a2a4626.png)
id存在 但是egg获取不到id的值 @atian25

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/31441192-0cb0c66e-ae58-11e7-95a0-6be7cc10c222.png)

你选了 form-data，当然就不是 `application/json` 了。

**Comment by BoizZ** [comment]
有个疑问，@cwc845982120 那种请求怎么拿 ID？看了 egg-multipart ，example 里面拿文件，另外一个 title 怎么拿？@atian25

**Comment by BoizZ** [comment]
看到了

**Comment by oneWalker** [comment]
> ![image](https://user-images.githubusercontent.com/227713/31441192-0cb0c66e-ae58-11e7-95a0-6be7cc10c222.png)
> 
> 你选了 form-data，当然就不是 `application/json` 了。

那如果要拿到form-data的数据的话应该用什么呢？

**Comment by atian25** [comment]
@oneWalker 你自己看下图中有哪些英文。

PS：可以考虑买本 图解 HTTP 来复习下 HTTP 协议的相关知识。

**Comment by webdome** [comment]
> 有个疑问，@cwc845982120 那种请求怎么拿 ID？看了 egg-multipart ，example 里面拿文件，另外一个 title 怎么拿？@atian25

stream.fields
