### ISSUE TITLE
升级egg报错

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#1517]
* **Node Version**: 7.6
* **Egg Version**: 1.9
* **Plugin Name**: sequelize
* **Plugin Version**: 4.13.8
* **Platform**: MAC OSX
* **Mini Showcase Repository**: https://github.com/eggjs/egg-sequelize

由原来的egg版本为1.3，按照以下指令升级：
```js
$ npm run autod
$ rm -rf package-lock.json
$ rm -rf node_modules
$ npm install
```
安装好依赖后直接运行，发生以下错误：
```
Error: Can not find plugin egg-sequelize in "/Users/haydn.chen/akashi/envobgm/server/node_modules, /Users/haydn.chen/akashi/envobgm/server/node_modules/_egg@1.9.0@egg/node_modules, /Users/haydn.chen/akashi/envobgm/server/node_modules"
```
以下是配置信息：
```js
// config/plugin.js
exports.sequelize = {
  enable: true,
  package: 'egg-sequelize'
}
```

**Comment by popomore** [comment]
没依赖 egg-sequelize ？

**Comment by atian25** [comment]
package.json 里面没引入吧？

BTW：`Mini Showcase Repository` 指的是最小可复现仓库（视情况，不是必须）

**Comment by AkashiX** [comment]
是忘了引入了，更新的时候把没有require模块的给删除了。但这个有点小问题啊，像这些框架都不需要require的。

**Comment by popomore** [comment]
看另一个 issue 的回复

**Comment by atian25** [comment]
你配置 https://github.com/eggjs/egg/blob/master/.autod.conf.js#L5 这个后，autod 就会自动分析 plugin.js 的。

最好你用 egg-init 生成 simple 骨架，那里面我们都配置好的了，不要自己初始化。
