### ISSUE TITLE
部署时 hostnme该怎么配置

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#1519]
* **Node Version**:8.0
* **Egg Version**: 1.7.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

config.prod.js
```  js
  //启动
  config.cluster = {
    listen: {
      // port: 7001,
      // hostname: 'localhost',
      // path: '/var/run/egg.sock',
      port: 80,
      hostname: 'localhost'
    }
  }
```
执行 ` npm start ` 后，站点运行成功，并验证。
```
 curl http://localhost:80
hi, egg
```
该服务器有域名和外部ip，切换成域名和外网ip均提示无法打开。
后来尝试将 hostname修改成外网ip或者域名，启动时会提示 ` EADDRNOTAVAIL `，导致无法启动。
请问是哪里配置错误了。

**Comment by popomore** [comment]
一般不用配

**Comment by a304885433** [comment]
@popomore  确实不用配置，啥都ok了，配置了反而多此一举，不是启动失败，就是无法访问。另外多问一句，部署的站点，怎么查看运行状态。根据部署的文档，npm start 和 npm stop分别可以启动和停止，但如果想查看运行状态，有没有办法呢

**Comment by atian25** [comment]
直接 PS 即可，关键词可以用你传递的 title 或 `start-cluster`
