### ISSUE TITLE
在框架开发中加入中间件出现问题

### ISSUE THREAD

**Issue by dahuahe** [eggjs/egg#1520]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我在自己开发的框架中加入了中间件  demoFramework->app->middleware>demoMiddleWare
并且demoFramework的config.default.js  写入 config.middleware=["demoMiddleWare"]
运行继承demoFramework框架的app时出现了报错
`Can not define middleware in ...../demoFramework/config/config.default.js`
查看了一下源码 这个中间件是不是要写成plugin的类型还是?

**Comment by atian25** [comment]
插件和框架不支持配置 `config.middleware`，你要在 app.js 中把 middleware 加进去，参见 https://github.com/eggjs/egg-static/blob/master/app.js#L6

https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/config.js#L90

**Comment by dahuahe** [comment]
谢谢.那关闭咯.

**Comment by atian25** [comment]
文档在 https://github.com/eggjs/egg/pull/1523 中补充了
