### ISSUE TITLE
装好egg-graphql并没有自带dataloader

### ISSUE THREAD

**Issue by figozhu** [eggjs/egg#1521]
* **Node Version**: 8.6.0
* **Egg Version**: 1.9.0
* **Plugin Name**: egg-graphql
* **Plugin Version**: 1.0.0
* **Platform**: windows
* **Mini Showcase Repository**:

装好egg-graphql后，没有自带dataloader

**Comment by jtyjty99999** [comment]
dataloader 需要自己引用，只是一个最佳实践

**Comment by figozhu** [comment]
![image](https://user-images.githubusercontent.com/4566514/31707232-4266b9aa-b41e-11e7-872a-d962e7eb5e60.png)

![image](https://user-images.githubusercontent.com/4566514/31707241-499f01e6-b41e-11e7-9d44-f34d9ed631e5.png)

这样的描述容易让人误解，最好加个说明吧。

**Comment by atian25** [comment]
@jtyjty99999 优化下文档吧.
