### ISSUE TITLE
HttpClient,timeout属性的问题

### ISSUE THREAD

**Issue by liuxianhua1996** [eggjs/egg#1525]
timeout的值设置为60秒超时 还是到30秒的就超时了，是设置了最大值吗

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/31533892-11750288-afba-11e7-8d1b-7eeb5678b2d4.png)

**Comment by atian25** [comment]
先关了，提供更多信息后，可以再 reopen 本 issue

**Comment by woer** [comment]
keepalive 设置的默认超时时间是30s
 `httpAgent: {
    // 默认开启 http KeepAlive 功能
    keepAlive: true,
    // 空闲的 KeepAlive socket 最长可以存活 4 秒
    freeSocketTimeout: 4000,
    // 当 socket 超过 30 秒都没有任何活动，就会被当作超时处理掉
    timeout: 30000,
    // 允许创建的最大 socket 数
    maxSockets: Number.MAX_SAFE_INTEGER,
    // 最大空闲 socket 数
    maxFreeSockets: 256,
  },

  httpsAgent: {
    // 默认开启 https KeepAlive 功能
    keepAlive: true,
    // 空闲的 KeepAlive socket 最长可以存活 4 秒
    freeSocketTimeout: 4000,
    // 当 socket 超过 30 秒都没有任何活动，就会被当作超时处理掉
    timeout: 30000,
    // 允许创建的最大 socket 数
    maxSockets: Number.MAX_SAFE_INTEGER,
    // 最大空闲 socket 数
    maxFreeSockets: 256,
  }`
