### ISSUE TITLE
egg-mysql bigint被约分

### ISSUE THREAD

**Issue by yunhappy** [eggjs/egg#1526]
数据库player表中guid为bigint类型

代码：
let result = yield client.get('player', { playername: ctx.request.body.player_name });   

result结果：
RowDataPacket {
  guid: 4035837130283371500,

然而 实际的guid是： 4035837130283371672

**Comment by atian25** [comment]
超过 `Number.MAX_SAFE_INTEGER` 了啊

**Comment by yunhappy** [comment]
@atian25 目前这个表是线上的表，没办法修改字段类型，还有其他程序在使用，有其他的读取办法么？

**Comment by ngot** [comment]
- 用字符串
- 用第三方的 bigInt 库
- 关注 ES 的 bigInt 提案

**Comment by yunhappy** [comment]
找到了，有选项，
supportBigNumbers  = true;
bigNumberStrings   = true;

**Comment by hanzichi** [comment]
@yunhappy  问下这个配置在哪个文件？谢谢

**Comment by meicx** [comment]
> 找到了，有选项，
> supportBigNumbers = true;
> bigNumberStrings = true;

麻烦问一下 这个配置选项在哪里配置需要安装什么库嘛？

**Comment by hanzichi** [comment]
@meicx egg 的配置文件里，不需要安装其他库

**Comment by llh1187** [comment]
请问下可以不返回RowDataPacket形式的吗？

**Comment by llh1187** [comment]
> 请问下可以不返回RowDataPacket形式的吗？

https://cnodejs.org/topic/575f5f23f2d6aeb302e8a68c
使用bing搜索引擎成功找到了相关资料~

**Comment by puzzle9** [comment]
> > 请问下可以不返回RowDataPacket形式的吗？
> 
> https://cnodejs.org/topic/575f5f23f2d6aeb302e8a68c
> 使用bing搜索引擎成功找到了相关资料~

地址过期了
不过可以直接
搜索 node RowDataPacket

```
      hat = await mysql.query('SELECT * FROM `hat_lists` WHERE (`device_id` = ? or `id` = ?) LIMIT 0, 1', [data.device_id, data.id])

      console.log(hat);
      console.log(hat[0].device_id);
```
