### ISSUE TITLE
How to unit test private methods

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1529]
* **Node Version**: 8.x
* **Egg Version**:  1.7.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Linux
* **Mini Showcase Repository**:

你好，我在写单元测试的时候遇到2个问题需要寻求帮助，望解惑。

- 如何测试 `class` 中的 `static` 方法。

- 如何测试未 `export` 出的方法

eg: 
```javascript
// app/service/a.js

function privateFunc () {
  //  do something
}

module.exports = (app) => {
  return class A extends app.Service {
    static classPrivate () {}
    func () {}
  }
}
```

1. 在第一个问题中能在 `app.serviceClasses` 上找到我想要的结果，但是我觉得这样的做法不是太恰当。

2. 在第二个问题中我不知道怎么拿到这个 `privatFunc` 。

希望能得到解答，十分感谢。

**Comment by atian25** [comment]
为什么要这样？

发自我的 iPhone

**Comment by popomore** [comment]
都从 controller 进行测试
