### ISSUE TITLE
egg-dubbo

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#153]
dubbo provider and  consumer http://dubbo.io/

**Comment by jtyjty99999** [comment]
@fengmk2 这个需要一个configserver吧，换成zookeeper?

**Comment by fengmk2** [comment]
阿里云对应的产品 https://www.aliyun.com/product/edas

**Comment by gxcsoccer** [comment]
这周把手上的事情清掉，下周开始全力投入，目前已经有两个需求方

**Comment by marshalYuan** [comment]
这个我们也有需求 自己也撸了一个 不过只实现了customer

**Comment by popomore** [comment]
https://github.com/dubbo-js

**Comment by popomore** [comment]
@gxcsoccer action 都在这里记录下吧，知道进度

**Comment by fengmk2** [comment]
@marshalYuan 有兴趣可以加入

**Comment by marshalYuan** [comment]
@fengmk2 思路不太一样 我们是用ts做的 基本是对dubbo的java版的一个复刻 不过还是从dubbo-js里学到了一些 谢谢 苏千大大

**Comment by gxcsoccer** [comment]
https://github.com/dubbo-js/dubbo-registry/pull/1  等 cluster-client 新版好了，加入 cluster 的支持

**Comment by gxcsoccer** [comment]
@marshalYuan 你们注册中心用的是什么？

**Comment by marshalYuan** [comment]
@gxcsoccer zookeeper

**Comment by elover** [comment]
我看dubbo-js这个写的还是比较复杂，包括了server端等，想知道如果是后端用java、注册中心用zookeeper，node.js目前只作为消费端要怎么用呢？目前来讲大部分场景应该都是这样的吧，不知道阿里内部是怎么解决这个问题的？

**Comment by popomore** [comment]
那就用 client 就好了

**Comment by jtyjty99999** [comment]
后面应该会独立提供一个egg-dubbo-client

**Comment by elover** [comment]
@jtyjty99999 
非常好，想问下 egg-dubbo-client 有没有具体的开发和发布计划？

**Comment by gxcsoccer** [comment]
@elover 后面逐步都会提供，本周会提供 client 和注册中心，代码已经基本写完了

**Comment by gxcsoccer** [comment]
@elover 等下面两个 pr 过了，就可以封装 egg-dubbo-client
https://github.com/dubbo-js/dubbo-client/pull/1
https://github.com/dubbo-js/dubbo-registry/pull/1

**Comment by elover** [comment]
那预计 egg-dubbo-client 能在最近2周之内的时间发布吗？

**Comment by gxcsoccer** [comment]
> 那预计 egg-dubbo-client 能在最近2周之内的时间发布吗？

可以

**Comment by elover** [comment]
这块可以先早点出个版本，我们也能先测试下

**Comment by elover** [comment]
好的，非常感谢

**Comment by gxcsoccer** [comment]
@elover 你们的注册中心用的是什么？

**Comment by elover** [comment]
zookeeper

**Comment by gxcsoccer** [comment]
zookeeper 的注册中心还要再开发，不过你可以先测试客户端调用

**Comment by elover** [comment]
好的，非常感谢

**Comment by Catlite91** [comment]
egg-dubbo发布了么？

**Comment by backsapce** [comment]
我们去年也撸了node dubbo，运行了一年了

**Comment by fengmk2** [comment]
@gxcsoccer 拉下不少东西

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-zookeeper 还没动工，

我先将 node-zookeeper-client 包装一个 leader/follower 的客户端出来，然后 egg-zookeeper 就容易写了。

**Comment by fengmk2** [comment]
https://github.com/node-modules/zookeeper-cluster-client

**Comment by fengmk2** [comment]
@shaoshuai0102 我才发现你在分支里面做了实现 https://github.com/eggjs/egg-zookeeper/blob/1st-impl/lib/zookeeper_api_client.js

我将 zk client 单独成立模块放出来了 https://github.com/node-modules/zookeeper-cluster-client

**Comment by shaoshuai0102** [comment]
之前弃的坑.. 👍

**Comment by a526672351** [comment]
egg-dubbo-client和 egg-zookeeper没有正式发布吗？

**Comment by popomore** [comment]
zookeeper 已经发了

**Comment by a526672351** [comment]
@popomore egg-dubbo-client会发布吗？

**Comment by Quinton** [comment]
@gxcsoccer  想了解下egg-dubbo-client开发进度，哈哈

**Comment by qw9002** [comment]
egg-dubbo-client这个插件什么时候能开放？ @fengmk2

**Comment by fengmk2** [comment]
@XadillaX 什么时候交货？

**Comment by fengmk2** [comment]
每月一问 @XadillaX

**Comment by atian25** [comment]
转正答辩时最后一问？

**Comment by Quinton** [comment]
https://github.com/jamesliauw/egg-dubbo

**Comment by fengmk2** [comment]
https://mp.weixin.qq.com/s/eVYx-tUIMYtAk5wP-qkdkw @XadillaX @gxcsoccer 重大革新！Dubbo 3.0来了

**Comment by fishbar** [comment]
啥时候能撸出来，可以组个dubbo小组了，分分工

**Comment by gxcsoccer** [comment]
之前我的负责，现在思路有点变化，因为 dubbo 本身在蚂蚁是没有在用的，后面我的想法是把 rpc 这套我们沉淀的东西开放出去，由社区自己定制

dubbo 协议已经实现，在[这里](https://github.com/dubbo-js/dubbo-remoting)。但是举个例子每个公司用的服务发现方式不一样，有的用 zookeeper，有的用 dubbo 内置的 register，有的是自己开发的，这个我们没有精力去维护，我们维护也不合适。
