### ISSUE TITLE
访问静态资源如何添加中间件？比如gzip中间件

### ISSUE THREAD

**Issue by BYmax1** [eggjs/egg#1532]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

访问public目录下的文件无法经过中间件，请问如何可以实现？或者有没有静态文件gzip的方案告知。求大神解答。

**Comment by callmesoul** [comment]
在nginx下配？

**Comment by atomoo** [comment]
不用ngxin直接使用egg输出静态文件的话，可以在[egg-static](https://github.com/eggjs/egg-static)里配置开启gzip

**Comment by atian25** [comment]
- 推荐在 `nginx` 那层做 gzip
- `egg-static` 底层是 `koa-static-cache`，支持 gzip 配置
- `egg-static` 的 middleware 是插入到 `app.coreMiddleware` 的，而 `config.middleware` 是 `app.appMiddleware`，所以如果有需要，应在应用的 `app.js` 里面直接 `app.coreMiddleware.splite` 放到 static 前面。
