### ISSUE TITLE
请求静态js资源报  net::ERR_CONTENT_LENGTH_MISMATCH 错误

### ISSUE THREAD

**Issue by JeffWong16** [eggjs/egg#1534]
我在用eggjs搭建自己的应用的时候，采用前后端分离的方案。把前端代码放置在 /app/public目录下。由于采用了webpack打包，导致打包的最后的js文件有900+k。我在把项目放到服务器后，请求我自己的单页应用，发现打包好的js文件在请求道700k左右的时候就会请求失败，报net::ERR_CONTENT_LENGTH_MISMATCH错误。在浏览器中单独请求这个js资源是可以请求到的。在本地开发环境下也显示正常。请问出现这种情况有可能是什么原因呢？

**Comment by JeffWong16** [comment]
需要补充的一点是，当我把这个大文件换成较小的js文件的时候，也是可以加载成功的

**Comment by JeffWong16** [comment]
再次补充，单独请求这个js资源虽然显示请求成功，但其实请求并不完整，大概请求出来的也是700k的片段

**Comment by atian25** [comment]
用 curl 试试，排除浏览器影响

发自我的 iPhone

**Comment by JeffWong16** [comment]
@atian25  还是一样的，都不能够请求完全。 我换了好几个浏览器，也使用过firefox的HttpRequester插件请求，整个文件不能够完全获取。

**Comment by JeffWong16** [comment]
我把我服务器地址放一下： http://182.254.246.89:7001

**Comment by JeffWong16** [comment]
使用curl请求时，报 curl: (18) transfer closed with 109172 bytes remaining to read 。 很奇怪的一点，无论在本地使用curl请求本地的资源还是在服务器上请求服务器的资源都没问题，但是本地请求服务器就显示资源还没有请求完，连接就关闭了。

**Comment by atian25** [comment]
服务器前面的 nginx 之类的反向代理是不是有问题?

看下 local -> server , server -> server 请求的 headers 的 content-length 有没有区别

**Comment by JeffWong16** [comment]
@atian25  你好，我并没有 做代理啊。
我今天又重新租用了一台阿里云服务器。上面没有我跑到其他东西。我又利用egg-init新创建了一个egg应用。只配置了 config.default.js
```
'use strict';
const path = require('path');

module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1234567788;

  config.static = {
    prefix:'/public/',
    dir: path.join(appInfo.baseDir, 'app/public')
  }

  // add your config here
  config.middleware = [];

  return config;
};

```
plugin.js
```
exports.static = true;
```

```
npm i egg-static --save
```
安装 static插件。

在 app/public里面放一个 800+k的js文件。部署到服务器后，依旧无法请求完整这个js功能。
也就是说，我把整个应用的结构变得更简单，也部署到一个环境更简单的服务器。但是这个问题还是存在的啊。

**Comment by atian25** [comment]
阿里云本来就有的吧。

只要你 local-local 和 server-server 没问题，那肯定不是 egg 这层的问题了

发自我的 iPhone

**Comment by JeffWong16** [comment]
@atian25  你的意思是在阿里云服务器上，即便我之部署了我node应用没做其他处理，也会默认给我做了反向代理？

**Comment by atian25** [comment]
我不确定，但如果你在服务器上访问自己没问题，那肯定是用户到服务器这段的链路问题咯

发自我的 iPhone

**Comment by JeffWong16** [comment]
@atian25 我解决啦，我用nginx做了下方向代理，就可以访问到了。 直接访问是不可以的。 非常感谢~

**Comment by JeffWong16** [comment]
今天遇到也是相同报错的一个问题，不过不同的是，这次是用nginx作代理， 不可访问，我找到了解决方法， 顺带分享下 http://blog.csdn.net/defonds/article/details/46042809

**Comment by dengjialin** [comment]
我想问下为什么我把前端文件放到public目录下,然后npm run dev会报错

![image](https://user-images.githubusercontent.com/20273940/39103696-e57b86fe-46de-11e8-9169-e6b104864a1f.png)

**Comment by dengjialin** [comment]
这是我的配置
![image](https://user-images.githubusercontent.com/20273940/39104126-6fa5824c-46e1-11e8-964b-6ff3c79f4f6e.png)
打包后的html文件
![image](https://user-images.githubusercontent.com/20273940/39104137-83bdfb1a-46e1-11e8-9798-635f0eaa3478.png)
路由
![image](https://user-images.githubusercontent.com/20273940/39104139-8ad44260-46e1-11e8-85ea-a09d19382d75.png)
就是引用的css,js都获取不到

**Comment by atian25** [comment]
`prefix: '/public'`
->
`public/index.xxx.css`

**Comment by dengjialin** [comment]
@atian25 多谢
我把这个配置成prefix: ./就好了

**Comment by atian25** [comment]
@dengjialin it maybe block router request

**Comment by dengjialin** [comment]
@atian25 懂了,我去改改
