### ISSUE TITLE
中间件怎么知道访问的app.resources路由，绑定了那个数据库表或模型？

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#1535]
因为想做restful api的权限控制，所以想知道：
中间件怎么知道访问的app.resources路由，绑定了那个数据库表或模型？

**Comment by popomore** [comment]
`app.resources(router, middleware, action)` 每个路由配置中间件，如果用 [userrole] 的话 `app.role.can('user')` 会返回一个中间件

[userrole]: https://github.com/eggjs/egg-userrole
