### ISSUE TITLE
egg.js的目录结构有按照业务来划分的么？

### ISSUE THREAD

**Issue by cdhjava** [eggjs/egg#1536]
官方约定的目录结构，是 controller, service, model，那假如现在有一个用户管理模块、文章管理模块，那用户的三个文件userCtrl.js + userService.js + userModel.js是分在三个目录中的，非常不好找。能按照
user/userCtrl,js user/userService.js user/userModel.js 就相当于一个业务包，叫用户管理。

**Comment by popomore** [comment]
egg 是按功能分层，你可以自定义 loader 来实现 https://eggjs.org/zh-cn/advanced/loader.html

**Comment by atian25** [comment]
这个问题，之前其实也思考过，基于 egg 的 loader，如何去定制此类 `feature-base` 的框架。

首先，规范先行，我们先思考下，期望的规范是怎么样的？

```bash
└── app
     └─ biz
        └── user
            ├── profile
            │   ├── profile.controller.js
            │   └── profile.service.js
            ├── user.controller.js
            └── user.service.js
```

映射规则：
- `app/biz/user/user.controller.js -> app.controller.user`
- `app/biz/user/user.service.js -> app.service.user`
- `app/biz/user/user/profile/profile.controller.js -> app.controller.user.profile`
- `app/biz/user/user/profile/profile.service.js -> app.service.user.profile`

如上，还可以考虑下，是否把 `user/user.controller.js` 简化为 `user/controller.js` ？

简单写了下代码，发现目前 loader 的 https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L78 这里行不通，因为目前我们是不支持一个 service 变为另一个 service 的子节点的，即 `app.service.user` 和 `app.service.user.profile`

cc @popomore

**Comment by popomore** [comment]
这个要自己实现啊

**Comment by atian25** [comment]
我的想法是，能更多的复用 egg loader，某些地方暴露 function 出来覆盖，这样自己实现的成本低一些。

**Comment by atian25** [comment]
我的想法是，能更多的复用 egg loader，某些地方暴露 function 出来覆盖，这样自己实现的成本低一些。

刚才提到 loader 的那个地方，目前的 type-base 也存在一种情况：

- `app/service/user.js -> app.service.user`
- `app/service/user/profile.js -> app.service.user.profile`

**Comment by popomore** [comment]
不想支持额外的功能

**Comment by cdhjava** [comment]
其实使用requireTree可以实现这种功能的，我在express上就用的是requireTree

**Comment by cdhjava** [comment]
不过用了requireTree估计就无法拿到上下文的context了……
