### ISSUE TITLE
求助：接口通过nginx代理转发后提示`invalid csrf token`

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#1540]
1. 问题如题，通过日志打印看，cookie已经转发给egg服务了，但是依然提示invalid csrf token。
2. security.csrf 没有配置过，是默认的
3. 前端工程是vue跑的静态页面，通过nginx转发请求egg的接口。
4. 如官方文档所说，get请求没问题，主要是post、put等操作会提示错误。

nginx配置如下
```
server {
        listen    80;
        server_name  xxx.xxx.com;

        location / {
        		root   /xxx/xxx/xxx-qa;
        		index  index.html index.htm;        
        		try_files $uri $uri/ /index.html;
        }
        
        location /nodeApi {
			proxy_pass http://127.0.0.1:8877;
			proxy_set_header Host $host;
	     	proxy_set_header X-Real-IP $remote_addr;
     		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     		proxy_set_header Cookie $http_cookie;
     		proxy_cookie_domain domino.server nginx.server;   
			proxy_cookie_path /nodeApi /;
	}
}

```

**Comment by popomore** [comment]
```
     		proxy_set_header Cookie $http_cookie;
     		proxy_cookie_domain domino.server nginx.server;   
			proxy_cookie_path /nodeApi /;
```

这些删了试试

**Comment by xjchenhao** [comment]
问题依旧，通过 日志来看 cookie也是传过来了

**Comment by popomore** [comment]
你请求没带吧

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/core/security.html#使用方式

**Comment by xjchenhao** [comment]
是没有刻意去传参数。
整个工程都是ajax请求api的，默认不是走cookie的吗？ajax不是自动会带上cookie吗，而且我egg的日志都能吧cookie打印出来呢。

**Comment by xjchenhao** [comment]
好吧，我看到了，😂 
谢谢 🙏

**Comment by intelinside** [comment]
我也碰到相同的问题，求解决方法。。。。。@xjchenhao

**Comment by xjchenhao** [comment]
@intelinside 接口请求时，要自己去把cookie放到header使用。

**Comment by Yuliang-Lee** [comment]
可以在`config`里面设置
```js
exports.security = {
  csrf: {
    ignoreJSON: true
  }
};
```

**Comment by wenlittleoil** [comment]
建议直接关闭掉
```
export.security = {
  csrf: {
    enable: false,
  },
}
```  
自己先去了解清楚csrf安全机制后，再来自己定制怎么做就行了，不一定要用egg带的。

**Comment by atian25** [comment]
连内置的 csrf 都搞不懂的话，还期望有能力去定制？还不如好好学下 csrf 是什么，然后再看下 egg-security 对应部分的代码

**Comment by xjchenhao** [comment]
两年前的issues竟然还有活跃度😂

没必要关闭csrf，我这个问题的核心是用来做csrf防御的cookie在api请求过程中服务端接收不到，后来经排查是前端发起api请求的时候把cookie弄丢了。

ps：官方的配置（安全配置和其它各种约定），我们应该奉行搞懂后使用，而不是简单粗暴的关闭、绕开。

**Comment by atian25** [comment]
> ps：官方的配置（安全配置和其它各种约定），我们应该奉行搞懂后使用，而不是简单粗暴的关闭、绕开。

点赞，正确的态度！
