### ISSUE TITLE
egg直接用了个第三方插件，报错

### ISSUE THREAD

**Issue by jeremy16601** [eggjs/egg#1542]
egg可以直接require 第三方插件吗，xml2json。 加载上这个就报错，但是加载md5的就没事。第三方插件只能用egg 插件扩展的方式来集成吗。

`D:\nodejs-Project\zh_choujiang\node_modules\egg\lib\application.js:39
      throw e;
      ^

Error: [egg-core] load file: D:\nodejs-Project\zh_choujiang\app\controller\home.js, error: Could not locate the bindings file. Tried:
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\build\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\build\Debug\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\build\Release\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\out\Debug\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\Debug\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\out\Release\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\Release\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\build\default\node_expat.node
 → D:\nodejs-Project\zh_choujiang\node_modules\node-expat\compiled\8.2.1\win32\x64\node_expat.node
    at bindings (D:\nodejs-Project\zh_choujiang\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (D:\nodejs-Project\zh_choujiang\node_modules\node-expat\lib\node-expat.js:4:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)`

**Comment by atian25** [comment]
跟 egg 没啥关系，这是一个 c++ 模块，你在 windows，估计是安装失败了。

可以试下新开一个空的 node 项目，install 后 require 看看。

**Comment by jeremy16601** [comment]
@atian25   恩，谢啦。
