### ISSUE TITLE
docker容器不能run起来，请问有碰到的吗？

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1543]
FROM daocloud.io/node:latest
RUN mkdir -p /data/www
WORKDIR /data/www
COPY . .
RUN npm install --registry=https://registry.npm.taobao.org
EXPOSE 7001
CMD npm start

不用docker，npm start正常

**Comment by atian25** [comment]
报错信息?

**Comment by longxianlin** [comment]
npm start是在容器里面的后台运行。
用npm run dev让egg跑在前台，就能启动docker了

**Comment by popomore** [comment]
参考这个 https://github.com/eggjs/egg/issues/1431#issuecomment-329949889

**Comment by atian25** [comment]
`npm start` 里面如果是 `egg-scripts start --daemon` 的话就是后台运行，如果想前台就干掉 `--daemon`

**Comment by longxianlin** [comment]
FROM node:8.0.0-alpine
速度太慢了
RUN apk --update add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata
会报错

npm install最好放在外面

我是有jenkins自动启动编译容器。
还没有用刀k8s

**Comment by popomore** [comment]
docker 用 aliyun 加速呗，不然肯定慢

**Comment by thonatos** [comment]
速度慢的问题，配个阿里云镜像的加速器解决喽~

备注一下：
> node:8.0.0-alpine，sticky 下 egg-socket-io 会有问题，如果没特殊要求换高版本吧

**Comment by atian25** [comment]
所以现在没问题了？先关了

**Comment by longxianlin** [comment]
没有问题了
