### ISSUE TITLE
egg-bin enable  --experimental-modules

### ISSUE THREAD

**Issue by njleonzhang** [eggjs/egg#1544]
how to enable node experimental feature for `egg-bin `, for example: ` --experimental-modules`

**Comment by atian25** [comment]
currently,  node 8.x could use `NODE_OPTIONS` env, https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by njleonzhang** [comment]
@atian25 既然node自己支持了egg.js还需要做support么？不太明白，大神有空能否解释下，或者给推荐个文章看看。
另外，NODE_OPTIONS似乎不支持`--experimental-modules`. 您给的文档里没有。
console里也会报错

```
node: --experimental-modules is not allowed in NODE_OPTIONS

➜  node --version
v8.7.0
```

**Comment by atian25** [comment]
1. 因为 Node 现在支持的 ESM 还不完整，是个半成品，ESM 和 CJM 还不支持互相调用。
2. `NODE_OPTIONS` 这个也是验证了， ESM 还是半成品的一个例子
3. 不要为了追新而追新。

**Comment by njleonzhang** [comment]
@atian25 感谢解释，倒不是为了追新，前端代码习惯了都是ESM的，写CJM风格的有点难受，仅此而已。

**Comment by popomore** [comment]
egg 很难支持 esm

**Comment by njleonzhang** [comment]
@popomore 了解了，个人感觉倒不是我追新，而是可能前端发展的确实快。`ESM `在前端已经是标配了。后台开发，不少人也已经通过babel和webpack去用了。当然，`egg`做不到也有其历史负担，然而不能不说比较遗憾。

**Comment by atian25** [comment]
后台开发，你如果放心 webpack 和 babel 的话，现在也能用它来把 egg 的应用代码编译后再执行啊，反正编译后就没 ESM 这玩意了。

**Comment by njleonzhang** [comment]
@atian25 哈哈是这样的, [babel-preset-env](https://github.com/babel/babel-preset-env)现在倒是为兼容node提供了不错的处理, 似乎没有不放心的哎。哈哈，再挖一坑。

```
{
  "presets": [
    ["env", {
      "targets": {
        "node": "6.10"
      }
    }]
  ]
}
```

**Comment by atian25** [comment]
这个看个人吧，我个人是觉得性价比太低，为了一个没啥用的特性，去引入编译这个黑盒子。

而且编译后的错误堆栈，不确定是否准确。
