### ISSUE TITLE
egg-cache需求

### ISSUE THREAD

**Issue by callmez** [eggjs/egg#1545]
eggjs生态组件里没有看到cache组件
貌似大家都没有cache组件的需求?

目前只有一个redis可以充当cache用, 但是有些场景是用不到的

希望能增加cache组件, 并提供adapters(redis|file|db|memcache)

**Comment by atian25** [comment]
file 的自己包装一个就好了，但用它来做 cache，就无法水平扩展了。redis 这些的已经有了， db 是存储的也有了。

不要为了轮子而轮子，egg 也只是在 koa 基础上加了一些约定而已，以前该怎么开发，现在还是可以怎么样，自己引入或封装为 inline plugin 就好了。

**Comment by callmez** [comment]
造轮子是为了开箱即用.节省一些开发周期 
我个人认为水平扩展这一块是项目应用决策上的的问题. 如果官方在cache的组件上有一个规范的接口约定.   

自己封装一个adapter并不是问题.. 但是在有个"官方"的规范约定在也是有利于生态的.  

说到轮子egg的轮子还少么.

**Comment by atian25** [comment]
我们之前的方式都是，先实现对应的插件，如果发现插件多了后，有必要的情况下，才会去提出规范来统一。

就 cache 的这个，目前还没看到特别强烈的需求需要统一。

所以建议是，社区这边可以自行实现插件，规范的约定，不一定是要官方来做的。
