### ISSUE TITLE
关于 form post的问题

### ISSUE THREAD

**Issue by nxycdl** [eggjs/egg#1547]
### 请问下是不是我写法或是配置有什么问题？谢谢。
```
<form method="POST" action="/upload?_csrf={{ ctx.csrf | safe }}" enctype="multipart/form-data">
    title: <input name="title"/>
    file: <input name="file" type="file"/>
    <p id="myDiv"></p>
    <input type="text" name="_csrf"value="{{ ctx.csrf }}">
    <button type="submit">upload</button>
    <button type="button" id="b01">POST1 -->JSON</button>
    <button type="button" id="b02">POST2 ajax 通过cookie获取csrf</button>
</form>
```
```
// config.defaults.js 
security: {
            xframe: {enable: true},
            csrf: {
                enable: true,
                useSession: false,          // if useSession set to true, the secret will keep in session instead of cookie
                ignoreJSON: true,          // skip check JSON requests if ignoreJSON set to true
                cookieName: 'csrfToken',    // csrf token's cookie name
                sessionName: 'csrfToken',   // csrf token's session name
                headerName: 'x-csrf-token', // request csrf token's name in header
                bodyName: '_csrf',          // request csrf token's name in body
                queryName: '_csrf',         // request csrf token's name in query
            },
        }
```

**Comment by popomore** [comment]
> <input type="text" name="_csrf"value="{{ ctx.csrf }}">

value 前面缺少空格

**Comment by nxycdl** [comment]
手误，但是和空格没有关系，我增加了一个空格 也是invalid csrf token，这个配置了config ，还有别的什么配置吗？
```
<input type="text" name="_csrf" value="{{ ctx.csrf }}">
```

**Comment by popomore** [comment]
那提供一个 demo 吧，看不出来

**Comment by nxycdl** [comment]
https://github.com/nxycdl/eggtest.git
直接访问home路由;谢谢了。
http://localhost:7001/home

**Comment by w567675** [comment]
我也碰到类似问题。

1：同步渲染的form
![image](https://user-images.githubusercontent.com/6658087/31761436-69149744-b4ea-11e7-87d4-9808f1f758d5.png)


2：传输的form-data
![image](https://user-images.githubusercontent.com/6658087/31761498-ae202c90-b4ea-11e7-9e0a-7358e1505736.png)


3：断点调试
![image](https://user-images.githubusercontent.com/6658087/31761405-45ee0bce-b4ea-11e7-9b39-165db1807d4c.png)

![image](https://user-images.githubusercontent.com/6658087/31761385-327b9854-b4ea-11e7-8f79-eb7c8d5ec905.png)

**Comment by fengmk2** [comment]
`<input type="text" name="_csrf"value="{{ ctx.csrf }}">` 放到 form 的最前面

```
<form method="POST" action="/upload" enctype="multipart/form-data">
    <input type="text" name="_csrf"value="{{ ctx.csrf }}">
    title: <input name="title"/>
    file: <input name="file" type="file"/>
    <p id="myDiv"></p>
    <button type="submit">upload</button>
    <button type="button" id="b01">POST1 -->JSON</button>
    <button type="button" id="b02">POST2 ajax 通过cookie获取csrf</button>
</form>
```

**Comment by nxycdl** [comment]
谢谢！已经看到#1551

**Comment by SunShinewyf** [comment]
@fengmk2 试了一下将`<input type="text" name="_csrf"value="{{ ctx.csrf }}">`放在`form`最前面的情况，也是会抛出`invalid csrf token`的错误提示，直接用的是上面给的例子，不知道是有什么地方配置出错了?还请指出。

通过源码追踪，发现凡是将`<input type="text" name="_csrf"value="{{ ctx.csrf }}">`放在`form`表单里面的任何地方，在源码中下面的函数中：
```js
  get [INPUT_TOKEN]() {
    const { headerName, bodyName, queryName } = this.app.config.security.csrf;
    const token = findToken(this.query, queryName) || findToken(this.request.body, bodyName) ||
      (headerName && this.get(headerName));
    debug('get token %s, secret', token, this[CSRF_SECRET]);
    return token;
  },
```
对于`url query`的情况，`this.query`自然就是`ctx.csrf`的值，但是对于`input type=file`的情况（无论是否放在`form`最前面），`this.request.body`的值都是空对象

![images](https://raw.githubusercontent.com/SunShinewyf/issue-blog/master/assets/technical/28.png)

也就是最终得到的`token`值是个空字符串，也就无法满足源码中`assertCsrf() `中的条件从而抛出错误

**Comment by popomore** [comment]
放到 url ，请看文档

**Comment by SunShinewyf** [comment]
@popomore 我知道放在url里面是可以的，只是对fengmk2说将input放在form的最前面也是可以的比较疑惑而已

**Comment by popomore** [comment]
Multipart 不行

**Comment by liqianglai** [comment]
`formidable`
[参考实现](http://blog.csdn.net/liqianglai/article/details/79070921)
