### ISSUE TITLE
GZIP压缩资源文件问题

### ISSUE THREAD

**Issue by zuoye520** [eggjs/egg#1548]
作者你好！
我按照官方文档中 使用koa-compress 作为中间件开启GZIP压缩时发现，不能对资源文件进行压缩， 资源文件是放在/app/public目录.  /app/view/ 下面的模板可以压缩。 

请问 我应该怎么处理？？

// app/middleware/compress.js
// koa-compress 暴露的接口(`(options) => middleware`)和框架对中间件要求一致
module.exports = require('koa-compress');

// config/config.default.js
exports.middleware = [ 'compress' ];
exports.compress = {
  threshold: 2048,
};

**Comment by popomore** [comment]
用 nginx 吧

**Comment by atian25** [comment]
建议用 nginx。

`exports.middleware` 是在应用层的 middleware 了，而 static 在 coreMiddleware。

要在 app.js 里面插入：

// app.js
module.exports = app => {
  const index = app.config.coreMiddleware.indexOf('static');
  if (index === -1) {
    app.config.coreMiddleware.push('static');
  } else {
    app.config.coreMiddleware.splice(index, 0, 'compress');
  }
  app.config.coreMiddleware.unshift('compress');
};

**Comment by CHEN-DONG** [comment]
@atian25 不好用啊 想压缩public里的js文件。。。

**Comment by atian25** [comment]
see middleware config for `match/ignore`

**Comment by w276549916** [comment]
没搞明白，还是用了 nginx
