### ISSUE TITLE
文档这块是不是少写了一个？

### ISSUE THREAD

**Issue by nxycdl** [eggjs/egg#1558]
https://eggjs.org/zh-cn/plugins/multipart.html#container
```
// config/config.default.js
exports.multipart = {  
fileSize: '50m',
};
--
```
这个文档少写了一个 应该是50mb 不是50m吧？
```
exports.multipart = {  
fileSize: '50mb',
};
```

**Comment by atian25** [comment]
@popomore doctools 编译有问题？ https://github.com/eggjs/egg-multipart#filesize 这里是新的。

**Comment by atian25** [comment]
@nxycdl  ?

**Comment by popomore** [comment]
应该是没发版本
