### ISSUE TITLE
egg-sequelize 在app.beforeStart中model.sync会报错

### ISSUE THREAD

**Issue by freebyron** [eggjs/egg#1565]
* **Node Version**:
8.5.0
* **Egg Version**:
1.9.0
* **Plugin Name**:
egg-sequelize
* **Plugin Version**:
3.1.0
* **Platform**:
windows
* **Mini Showcase Repository**:
https://github.com/freebyron/egg-sequelize-bug

建立任意model，并在app.beforeStart中model.sync就会奔溃。
日志如下：

2017-10-26 10:55:29,908 ERROR 8988 nodejs.SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\workspace\personal\egg-seq\node_modules\sequelize\lib\dialects\postgres\query.js:313:18)
    at query.catch.err (D:\workspace\personal\egg-seq\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
    at tryCatcher (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\workspace\personal\egg-seq\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
name: 'SequelizeUniqueConstraintError'
errors: [ ValidationErrorItem { message: 'typname must be unique', type: 'unique violation', path: 'typname', value: 'people_id_seq' }, ValidationErrorItem { message: 'typnamespace must be unique', type: 'uniqu
e violation', path: 'typnamespace', value: '2200' } ]
fields: { typname: 'people_id_seq', typnamespace: '2200' }
parent: { error: duplicate key value violates unique constraint "pg_type_typname_nsp_index" at Connection.parseE (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:546:11) at Connection.parseMessa
ge (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:371:19) at Socket.<anonymous> (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:114:22) at emitOne (events.js:115:13) at Socket
.emit (events.js:210:7) at addChunk (_stream_readable.js:266:12) at readableAddChunk (_stream_readable.js:253:11) at Socket.Readable.push (_stream_readable.js:211:10) at TCP.onread (net.js:585:20) name: 'error'
, length: 253, severity: 'ERROR', code: '23505', detail: 'Key (typname, typnamespace)=(people_id_seq, 2200) already exists.', hint: undefined, position: undefined, internalPosition: undefined, internalQuery: un
defined, where: undefined, schema: 'pg_catalog', table: 'pg_type', column: undefined, dataType: undefined, constraint: 'pg_type_typname_nsp_index', file: 'nbtinsert.c', line: '433', routine: '_bt_check_unique',
 sql: 'CREATE TABLE IF NOT EXISTS "people" ("id"   SERIAL , "name" VARCHAR(30), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));' }
original: { error: duplicate key value violates unique constraint "pg_type_typname_nsp_index" at Connection.parseE (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:546:11) at Connection.parseMes
sage (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:371:19) at Socket.<anonymous> (D:\workspace\personal\egg-seq\node_modules\pg\lib\connection.js:114:22) at emitOne (events.js:115:13) at Sock
et.emit (events.js:210:7) at addChunk (_stream_readable.js:266:12) at readableAddChunk (_stream_readable.js:253:11) at Socket.Readable.push (_stream_readable.js:211:10) at TCP.onread (net.js:585:20) name: 'erro
r', length: 253, severity: 'ERROR', code: '23505', detail: 'Key (typname, typnamespace)=(people_id_seq, 2200) already exists.', hint: undefined, position: undefined, internalPosition: undefined, internalQuery:
undefined, where: undefined, schema: 'pg_catalog', table: 'pg_type', column: undefined, dataType: undefined, constraint: 'pg_type_typname_nsp_index', file: 'nbtinsert.c', line: '433', routine: '_bt_check_unique
', sql: 'CREATE TABLE IF NOT EXISTS "people" ("id"   SERIAL , "name" VARCHAR(30), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));' }
sql: 'CREATE TABLE IF NOT EXISTS "people" ("id"   SERIAL , "name" VARCHAR(30), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));'
pid: 8988
hostname: DESKTOP-KG3565E

**Comment by atian25** [comment]
@huacnlee @jtyjty99999 我们推荐在 beforeStart ？

`app.beforeStart` 中 `model.sync` 不会有问题么？多个 worker 的情况下。

**Comment by popomore** [comment]
不建议

**Comment by iyuq** [comment]
多个worker的话会有问题的，应该推荐还是 migrations 比较好。不然要放 agent 里面？

**Comment by popomore** [comment]
放 agent 多个服务器也会有问题

**Comment by freebyron** [comment]
@atian25 @popomore 建议修改文档

**Comment by popomore** [comment]
@iyuq 帮忙修改下文档

**Comment by iyuq** [comment]
@popomore 可以

**Comment by gaochengyidlmu** [comment]
图简单的话可以写在 agent.js 里面
```
module.exports = async agent => {
  await agent.model.sync();
};
```

**Comment by gaochengyidlmu** [comment]
写 agent 里面有点蠢，可以换成 agent 发送 SyncModel 事件给一个 worker，这样就没毛病了。

agent.js
```
module.exports = async agent => {
  agent.messenger.on('egg-ready', () => {
    agent.messenger.sendRandom('SyncModel');
  });
};
```

app.js
```
module.exports = app => {
  app.messenger.on('SyncModel', async () => {
    await app.model.sync({ force: true });
  });
};
```
