### ISSUE TITLE
http下，无法使用ctx.session

### ISSUE THREAD

**Issue by klk2** [eggjs/egg#1566]
* **Node Version**:8.4.0
* **Egg Version**:1.3.0
* **Plugin Name**:egg-bin
* **Plugin Version**:3.3.0
* **Platform**:mac
* **Mini Showcase Repository**:

egg-bin dev启动服务，ctx.session为空对象；加入https选项可以正常使用ctx.session。
package.json:
```
"dev": "egg-bin dev --sticky",
"prod": "EGG_SERVER_ENV=prod npm start",
"debug": "egg-bin dev --sticky $NODE_DEBUG_OPTION --port=7072 --https=true --key='xx.key' --cert='xx.crt' ",
```
config文件为：config.default.js，config.prod.js数据库地址外均一致。

**Comment by atian25** [comment]
最小可复现代码

**Comment by klk2** [comment]
存入：
`this.ctx.session.captcha = 'captcha';`

npm run dev 启动：
passport

```
app.passport.verify(function* (ctx, user) {
        let captcha = ctx.request.body.captcha;
        console.log(ctx.session)  // {}
});

```
npm run debug 启动：
passport

```
app.passport.verify(function* (ctx, user) {
        let captcha = ctx.request.body.captcha;

        console.log(ctx.session)  // {captcha:'captcha'}
});
```

**Comment by atian25** [comment]
network 看下请求吧， dev 和 debug 不会导致这个问题的，就是加了个环境变量和参数而已。

**Comment by klk2** [comment]
network正确的，
不是dev和debug的问题，是我标题写的不准确，导致这个差异性的是在http和https；
render的时候 ctx也获取不了存return的值。

**Comment by klk2** [comment]
哦 ，抱歉，是我chrome设置的问题。

**Comment by klk2** [comment]
关了吧
