### ISSUE TITLE
进入example，安装依赖，示例无法正常运行？

### ISSUE THREAD

**Issue by yichangle** [eggjs/egg#1567]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)

**Comment by yichangle** [comment]
我说的是egg-socket.io

**Comment by atian25** [comment]
看完那篇体会下如何正确的提 issue 再说，不要挤牙膏。
