### ISSUE TITLE
registry.cnpmjs.org 也要翻墙？

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#1571]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/26592729/32043610-dbef9e42-ba00-11e7-8dca-54fb696c5132.png)
![image](https://user-images.githubusercontent.com/26592729/32043629-e918e272-ba00-11e7-8497-fc03bb63bde9.png)
翻墙 registry.cnpmjs.org可以打开，cnpm 也要翻墙了？

**Comment by popomore** [comment]
请移步 https://github.com/cnpm/cnpmjs.org/
