### ISSUE TITLE
线上部署 npm start 启动失败

### ISSUE THREAD

**Issue by Cecilxx** [eggjs/egg#1572]
* **Node Version**: v8.7.0
* **Egg Version**: v1.10.0
* **Plugin Name**: Egg-Scripts
* **Plugin Version**: v2.1.0

1. 安装完 egg-scripts
2. 本地 npm start 启动成功 egg started on http://127.0.0.1:7001
3. tar 压缩上传服务器再解压
4. 线上 npm start 启动失败 

本地启动：
![image](https://user-images.githubusercontent.com/20623617/32045088-fc4f909e-ba04-11e7-8e13-d43f5fb70129.png)

线上启动：
![image](https://user-images.githubusercontent.com/20623617/32045125-1acc91ca-ba05-11e7-8a7e-4b0cd39c5ff0.png)
![image](https://user-images.githubusercontent.com/20623617/32045147-2725d0e4-ba05-11e7-88c1-18f2bbc12ce4.png)
![image](https://user-images.githubusercontent.com/20623617/32045161-3175b474-ba05-11e7-9699-defb1772c692.png)

我该怎么修复呢？？？？

**Comment by popomore** [comment]
你需要在 linux 安装

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/32045256-6ced415c-ba05-11e7-9eb1-c4b2dbb5c912.png)

其实报错都写的的，是你这个原生模块的原因。可能是你打包的机器和线上机器环境不一致，导致下载的编译后的 node 文件不合法。

**Comment by Cecilxx** [comment]
@popomore 线上是centos7

**Comment by atian25** [comment]
无所谓，你安装依赖的那台机器（我们一般在 ci 上打包），必须跟线上是一样的环境。

**Comment by Cecilxx** [comment]
@atian25 我是在本地是按照官网文档用的tar 打的包  tar --version 显示 bsdtar 2.8.3 - libarchive 2.8.3，把这个包上传到线上再用tar解压 tar --version 显示 tar (GNU tar) 1.26 ； 是因为这个版本的原因吗？ 如果是的话 我该怎么把tar更新到同一版本？ 前端小白一枚，对后台和运维真的是一窍不通，求大佬指点，谢谢了

**Comment by atian25** [comment]
刚才不是说了么，你本地是不是 win 之类的系统，你在这个系统打的包，是不能用在其他系统的。

你要**找一台跟线上服务器的操作系统一模一样的机器，在这上面去 `npm install` 然后再 tar 打包**

**Comment by Cecilxx** [comment]
@atian25 感谢天猪大佬，上次之后抽时间有倒腾了下，发现自己的代码在mac上压缩tgz包上传服务器后解压运行都是没有问题的，有问题的是node_modules直接在mac上压缩后上传解压是有问题的。 所以现在的问题有两种解决方案： 1. 只打包自己代码部分，上传服务器后再服务器上面npm i ; 2. 找一台跟线上服务器的操作系统一模一样的机器（虚拟机）压缩所有的代码，上传后直接解压。这两种方法亲测有效！！！

**Comment by ngot** [comment]
主 issue 没有提供 OS 信息。add tag `not follow template`

**Comment by atian25** [comment]
> 服务器上面npm i 

这是严重不推荐的方案
