### ISSUE TITLE
分布式部署的问题

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1573]
现在公司有3台机器部署了同一份server代码，每台机器上开启了8个worker进程，通过nginx进行分流。

问题：每台机器的agent.js都会在启动的时候执行一段读写数据库的逻辑（CRUD），这样这段代码会被3台机器的agent.js都执行，引发错误，其实只需要跑一次就行。

这种分布式部署引起的类似问题，egg有何优雅的解决方案？

**Comment by popomore** [comment]
agent 做了啥

**Comment by linxuanwei** [comment]
@popomore    agent里会读取并更新数据库里的某些数据，同时agent里启动了一个socket server监听端口

**Comment by linxuanwei** [comment]
现在socket server我可以移走，独立部署一台机器，但是agent里执行的数据库update操作会导致3台机器同时执行，发生update冲突，我又不希望引入额外的锁工具

**Comment by popomore** [comment]
同时写肯定有问题啊，你可以选举一个 leader 来实现，或者通过第三方平台推送，启动只读。

**Comment by popomore** [comment]
这个和架构设计有关了，和是否使用 egg 无关。
