### ISSUE TITLE
跟踪中间件执行过程

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#158]
经常遇到一个问题，一个请求不知道哪个中间件上做了什么操作，改了什么内容，需要有一个 tracer 来跟踪中间件执行完的过程，可以做在 compose 上。

1. simple 模式：拿到中间件的执行过程和执行耗时，local 环境默认打开，线上环境通过请求头打开，打印到响应头中。
2. detail 模式：拿到中间件执行过程耗时，并打印每次中间件对 header / body 的修改。开发环境可配置打开，prod 不允许打开。

**Comment by popomore** [comment]
需要改 koa-compose？

**Comment by dead-horse** [comment]
先放着吧，感觉成本有点高也不是强需求

**Comment by atian25** [comment]
突然想到一个跟这个类似的，跟踪配置的合并过程。

`npm run dev --inspect-config`

我们是不是可以通过把 config 做一下 Proxy，就能记录下来的了?  @popomore 

```json
{
   "config.view.cache": [
     "path/to/egg-view/config/config.local.js": "false",
     "path/to/egg-view/config/config.default.js": "true"
   ]
}
```

**Comment by ImHype** [comment]
trace 还是很有必要的，线上也可以开启用于中间件的耗时统计，最终将数据整合入监控

**Comment by THaGKI9** [comment]
进度怎么样？

**Comment by atian25** [comment]
@dead-horse 感觉可以做一个 Middleware 插在最前面，然后对 ctx.body 和 ctx.header 做个 Proxy，就可以打印了
