### ISSUE TITLE
egg-validate插件的问题

### ISSUE THREAD

**Issue by tmcyfy** [eggjs/egg#1580]
```
      const createRule = {
        code: { type: 'string' },
      };
      ctx.validate(createRule, ctx.request.body.code);
```

总是报错 errors: [ { message: 'required', field: 'code', code: 'missing_field' } ]

但是ctx.request.body.code是可以打印出来的，好奇怪

**Comment by atian25** [comment]
`ctx.validate(createRule, ctx.request.body)`

发自我的 iPhone

> 在 2017年10月28日，19:23，tmcyfy <notifications@github.com> 写道：
> 
> ctx.validate(createRule, ctx.request.body.code)

**Comment by tmcyfy** [comment]
谢谢～刚也发现了，对自己无语了。。
