### ISSUE TITLE
请问该框架自带的egg-log有写入nosql的api吗

### ISSUE THREAD

**Issue by phper-chen** [eggjs/egg#1581]
我们的需求是想把log输入到mongodb中去，log4j是可以的，不知道你们的是否可以，谢谢回答

**Comment by phper-chen** [comment]
不是transport那种，我的意思是给个mongodb配置项，让egg-log直接写入

**Comment by atian25** [comment]
transport 即可，没有现成插件，自己封装一个就好了，可以分享出来。

发自我的 iPhone

> 在 2017年10月28日，19:49，chen <notifications@github.com> 写道：
> 
> transport

**Comment by phper-chen** [comment]
好的 谢谢回复～
