### ISSUE TITLE
如何用egg-sequlize实现多对多映射，使用原生belongsToMany报错，参照官网放associate回调提示‘sourceKey’undefined

### ISSUE THREAD

**Issue by kimyLee** [eggjs/egg#1582]
* **Node Version**: 8.1.2
* **Egg Version**:  1.8.0
* **Plugin Name**: egg-sequlize
* **Plugin Version**: 3.1.0
* **Platform**: window
* **Mini Showcase Repository**:

请问如何用egg-sequlize实现多对多映射，使用原生belongsToMany报错，参照官网放associate回调提示‘sourceKey’undefined
代码如下：
module.exports = app => {
    const { STRING, INTEGER, DATE } = app.Sequelize;
  
    const UserProjects  = app.model.define('userProjects', {
      is_follow: { type: INTEGER, defaultValue: 0 }
    });
    UserProjects.associate = function() { // 一开始不在回调里面，  app.model.User找不到对象
        app.model.User.belongsToMany(app.model.Project, { through: UserProjects, foreignKey: 'user_id' })
        app.model.Project.belongsToMany(app.model.User, { through: UserProjects, foreignKey: 'project_id' })
    }
    return UserProjects;
  };

**Comment by popomore** [comment]
提供一个可重现的 demo

**Comment by kimyLee** [comment]
这是我git 上的demo, 有线上部署方便查看的做法，麻烦提供下指引我部署下，现在只能直接install再run下，我参考指引中// app/model/post.js， 直接创建post 这个model，只要包含[model].associate也会报错，如下，代码中在model我先注释了这部分
![image](https://user-images.githubusercontent.com/11704790/32141392-dc2a198a-bcb9-11e7-8b6e-6592915548f6.png)
`module.exports = app => { 
  const { STRING, INTEGER, DATE } = app.Sequelize;
  const Post = app.model.define('Post', {
    name: STRING(30),
    user_id: INTEGER,
    created_at: DATE,
    updated_at: DATE,
  });
  Post.associate = function() {
    app.model.Post.belongsTo(app.model.User, { as: 'user' });
  }

  return Post;
};`

**Comment by callmesoul** [comment]
`app.model.Project.belongsToMany(app.model.User, { through: UserProjects, foreignKey: 'project_id' })`
放在Project model下试下

**Comment by popomore** [comment]
https://github.com/kimyLee/ground-bg/blob/master/app/model/user.js#L5

primaryKey 是布尔
