### ISSUE TITLE
egg socket.io   向客户端推送消息未成功

### ISSUE THREAD

**Issue by yule333444** [eggjs/egg#1585]
-->

* **Node Version**:
8.7
* **Egg Version**:
1.5.0
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
3.0.0
* **Platform**:
windows:
* **Mini Showcase Repository**:

1.  想在别的service 中向client 推送消息 ： 
使用了例子中的代码        ctx.socket.emit('sender','任务状态已变更');   但是发现客户端没有接受到。
2. 目前能看到的是  两个中间件向客户端推送的消息 。难道  socket.emit('res') 只能用在中间件中吗？
3. auth 中间件中的  next 是什么呢 。 例子中  首先 推送了    this.socket.emit('res', 'connected!');  是客户端主动调   disconnxt 请求吗 ？ 
4. this.socket.emit('res', 'packet received!');
      this.logger.info('packet:', this.packet);
      yield* next;
这个  this.packet 是哪里来的啊 ？   后台打印的结果是 一堆乱码

**Comment by Sakuraly1** [comment]
那个是中文乱码问题，emit() 貌似不会传送任何无法识别的乱码数据，目前我也在找方法解决，如果各位有解决方案的话恳请评论告知

**Comment by yule333444** [comment]
ctx.socket.emit('res','taskUpdated');   我把消息改成中文以后 ， client 还是没有收到消息啊 。

**Comment by ngot** [comment]
提供一下客服复现的最小可执行的代码仓库。

**Comment by yule333444** [comment]
server:
 async startOrderTask (taskInfo) {
           const {ctx} = this;
           const platformTypes = ctx.app.config.platformTypes;
           const task = this.getUserTaskById(taskInfo.id);
           let orderTask; // 保存进order 任务队列的 task 信息。
           if (task) {
               // task.isActive = true; 关闭 active 模式 。发现任务池中已存在  就直接跳过了。
               return ;
           } else {
               taskInfo.state = 'doing';// 将任务状态设置为正在进行。
               // taskInfo.isActive = true;

               switch (taskInfo.platformId) {
                   case platformTypes.amazon:
                       taskInfo.marketIds = taskInfo.marketIds.split(',');
                       this.ctx.app.orderTask.push(taskInfo);
                       orderTask = await ctx.service.amazonService.getListOrders(taskInfo);
                       ctx.logger.info('同步任务完成后的信息', orderTask);
                       break;
                   default:orderTask =  Object.assign({}, taskInfo ,{state:'comp'});
               }
               ctx.logger.info(ctx.socket);

               ctx.socket.emit('res','taskUpdated');
               // ctx.socket.emit('res', 'connected!');

               this.ctx.app.orderTask.forEach((oTask, index) => {
                   if (oTask.id === orderTask.id) {
                       this.ctx.app.orderTask[index] = Object.assign({}, orderTask);// 修改任务缓存池中同步任务的状态信息。
                       return false;
                   }
               });

               // this.ctx.app.orderTask.push(orderTask);
               ctx.logger.info('成功添加同步订单任务', orderTask);
           }
        }

client: 
import VueSocketio from 'vue-socket.io';
Vue.use(VueSocketio, 'http://127.0.0.1:7001/');

const app = new Vue({
  router,
  sockets: {
    connect: function () {
      console.log('socket connected');
      this.$socket.emit('chat', 'success');
    },
    res: function (val) {
      console.log('接收到服务端消息', val);
    }
  }
}).$mount('#app');

我的需求  是  在  后端执行完一个耗时较长的任务后 通知前端 任务执行完毕了 。
之前的  socket.emit('res','xxxx')  仅仅在 中间件中执行  ，client 才会收到 。  而我现在执行这个代码的场景是在  egg 的  一个 普通 service  中 。 
是不是  不能这么写呢 。 socket 应该有提供别的接口吧 。 原先的文档 请完善api 啊  大神。

**Comment by atian25** [comment]
学会 markdown 格式化代码

**Comment by yule333444** [comment]
刚刚试过了 egg controller 里面的  this.ctx.socket.emit('res', 'taskUpdated');   客户端都收到消息了。 为什么 不能直接从  service 里面发呢 。 
在 controller 中  socket.emit  前面 加了  await 标识 ，请问 这个 和  中间件里面  运行的机制不一样吗。
然后 我在service  里面 把  socket.emit 前  也加了  await 标识 ， 然而 客户端还是没收到消息。

**Comment by ngot** [comment]
提供一下客服复现的**最小可执行的代码仓库**

**Comment by yule333444** [comment]
我 知道意思了。  服务端没有主动向 客户端推送消息的能力 ，更没有向指定客户端推送消息的能力 。
客户端只所以能收到消息 ，完全是因为 走了 那个 chat controller  。 
非常失望

**Comment by ngot** [comment]
@yule333444 服务端肯定可以推动消息。你的问题到底是什么？就不能提供下可执行代码吗? 咨询问题，首先也得让我们明白，你在问什么。现在，我们一头雾水。

**Comment by ngot** [comment]
@yule333444 把的测试工程完整推送一个git仓库，然后对这个工程的具体文件和代码，我们来看问题。因为，设计上是支持的，我猜测是你的用法问题。但是从你上面的贴的东西，我到目前难以理解想表达什么。

**Comment by yule333444** [comment]
https://github.com/yule333444/socket-test   第一次弄这个，  看看这样行吗。

**Comment by ngot** [comment]
这句不对：https://github.com/yule333444/socket-test/blob/master/app/service/test.js#L11

emit 并不是返回 Promise 对象，不能 await .

**Comment by ngot** [comment]
https://github.com/yule333444/socket-test/blob/master/app/io/controller/chat.js#L7 这行同上。

**Comment by ngot** [comment]
这里是 example https://github.com/eggjs/egg-socket.io/blob/master/example/app/io/controller/chat.js

**Comment by yule333444** [comment]
我之前并没有使用 await 。是看到你的例子里面有这样写， 我才给加上的。  汗。
不过之前没用await的时候也不行啊。

**Comment by ngot** [comment]
哪个例子？ 仓库的例子，没有 await 这种用法。

**Comment by yule333444** [comment]
好吧， 是我误会了， 因为我在 service/user 里面的 say 方法 看到  它仅仅是返回字符串 ，却返回的是  异步方法。

**Comment by yule333444** [comment]
我启用非io 文件夹下的  controller  。也能触发  emit('res')  的 对吗？ 
我怀疑是这个问题啊。 
因为例子中  请求经过的 controller  是定义在 IO文件夹中的。

**Comment by ngot** [comment]
用不用 await ，取决于调用的对象。比如是异步的Promise对象，那么可以 await 。但是像 socket 的 emit 方法，await 并没有用，它不反会 Promise，紧紧是触发一个事件。

**Comment by ngot** [comment]
非 IO 目录的，都无法获取到 io 对象，所以不在 egg-socket.io 插件的覆盖范围。

**Comment by yule333444** [comment]
这才是重点啊。。。
如此说来  所有想使用  IO服务的 路由 都必须定义在IO文件夹里面了 ？

**Comment by ngot** [comment]
这个文档都写了啊。https://github.com/eggjs/egg-socket.io#directory-structure 这里写的很清楚吧。不在文档约定范围的，都不行。

egg 是约定大于配置的。 就好像你不能把 controller 乱放一样。

**Comment by yule333444** [comment]
就是说 我测试仓库里的  app/controller/task.js  必须移动到   app/io/controller/task.  这里对吧。

**Comment by ngot** [comment]
我其实一开始就没看懂你的代码 app/controller/task.js 这个和你说了半天的socket有和关系。

**Comment by yule333444** [comment]
因为  消息回馈  只是后来想加的一个附带的功能。

**Comment by yule333444** [comment]
用户的请求 是走得  controller/task.js  发起的。

**Comment by yule333444** [comment]
然后调用一个 service 的方法  激活  socket.io 的 emit 。

**Comment by ngot** [comment]
『就是说 我测试仓库里的 app/controller/task.js 必须移动到 app/io/controller/task. 这里对吧』这个不需要移动也是可以的。

应该只是你的调用方式问题。但是就算可以这么用，也不要在 service 里面调用 emit，这个应该放到 controller 里面去做。

**Comment by ngot** [comment]
service 应该就是一个函数调用，用户的请求，不应该在 service 内响应。

**Comment by yule333444** [comment]
我是看到   例子里面有一个  service/user   的  say 方法。

**Comment by ngot** [comment]
那先关了。

**Comment by yule333444** [comment]
还以为要把emit()  移动到  service里面去呢。

**Comment by yule333444** [comment]
好的 ，多谢大佬照顾。

**Comment by ngot** [comment]
service 是用来封装一些共用代码，异步调用。但是不要在里面响应用户请求。

**Comment by ngot** [comment]
云里雾里讲了半天，不如直接提供代码来的快。

**Comment by yule333444** [comment]
可是 我的  emit 确实是发生在 service 场景中的啊。 
service 里执行一个耗时较长的逻辑 ， 任务完没完  只有 service 里的代码才知道啊。

**Comment by ngot** [comment]
和耗时长短无关。
```js
this.ctx.service.xxx();// 同步
this.ctx.socket.emit('xxx');
```

```js
await this.ctx.service.xxx();// 异步
this.ctx.socket.emit('xxx');
```

不管什么场景，代码都是这样写的。和长短没有任何关系

**Comment by yule333444** [comment]
我又发现一个惊天大秘密 。
前面 标了 await 竟然是异步啊 。 我一直都当它是同步。 不加才是异步呢。

**Comment by yule333444** [comment]
加了 await 我是理解为 等待这个操作确定给返回值  。否则就不继续执行后面的。
