### ISSUE TITLE
fetch post can't get request.body

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1586]
```javascript
fetch('http://127.0.0.1:3000/',{method: 'POST',headers:{"Content-Type":"application/json; charset=UTF-8"},body:JSON.stringify({user:'people'})})
```
ctx.body // undefined

```javascript
fetch('http://127.0.0.1:3030/',{method: 'POST',headers:{"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"},body:'user=people'}) 
```
```sell
curl -X POST http://localhost:3000/ --data '{"user":"people"}' --header 'Content-Type:application/json; charset=UTF-8'
```
ctx.body // {"user":"people"}

**Comment by atian25** [comment]
use `ctx.request.body`,  `ctx.body` is alias to `ctx.response.body`.

**Comment by chenyulun** [comment]
不要纠结名字问题；
场景都测试过了；
第一个请求获取不到body;
第二个和第三个都可以获取；
kao2的框架加入了koa-json中间件才可以获取到fetch里面请求的定义为application/json的body,
你们用的这个只能采用application/x-www-form-urlencoded获取body数据；

**Comment by atian25** [comment]
都说了，`ctx.request.body` 才是获取用户 POST 的内容的，`ctx.body` 是响应给用户的。

![image](https://user-images.githubusercontent.com/227713/32203253-09dea5ac-bdb0-11e7-8756-900ce997da08.png)

无法复现，请给出最小可复现仓库。

**Comment by chenyulun** [comment]
我一直没注意我写成了"application/application/json",谢谢了
