### ISSUE TITLE
controller生成api文档的问题

### ISSUE THREAD

**Issue by junyuz** [eggjs/egg#1587]
基于egg编写了应用系统，controller和service中的方法都用jsdoc的语法写了注释，现在希望把controller中的注释生成api文档以供前端开发人员使用，目前用doxdox生成没达到预期的效果

`doxdox 'app/**/*.js' --layout bootstrap --output docs/index.html`

所有的方法都没有生成文档，只有class的注释生成了文档；
想要请教一下，有没有推荐的方式生成文档

**Comment by dead-horse** [comment]
这个问题需要去 doxdox 提问，egg 暂时没有提供类似工具的计划。
