### ISSUE TITLE
使用ctx.cookites.set的options{ encrypt: true}设置之后，使用ctx.cookies.get 得到undefined，不是文档说的加密过后的密文

### ISSUE THREAD

**Issue by w567675** [eggjs/egg#1589]
* **Node Version**:
8.6.0
* **Egg Version**:
^1.10.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
win10
* **Mini Showcase Repository**:
(https://github.com/nodeTest/egg-cookies-get-undefined)

```js
module.exports = app => {
  class HomeController extends app.Controller {
    async index(ctx) {
      let count = ctx.cookies.get('count');
      ctx.cookies.set('count', '我', { encrypt: true} );

      console.log('这里应该是密文??  =>>>>>', ctx.cookies.get('count', { encrypt: true }))
      console.log('---------------')
      console.log('这里应该是密文??  =>>>>>', ctx.cookies.get('count'))

      
      ctx.body = {
        'encrypt': ctx.cookies.get('count', { encrypt: true}),
        'noencrypt': ctx.cookies.get('count') === undefined ? 'undefiend' : ctx.cookies.get('count'),
      }
    }
  }
  return HomeController;
};
```

![image](https://user-images.githubusercontent.com/6658087/32206141-6166aa3a-be2e-11e7-93cd-54ee663cfea4.png)

文档里说是如果设置的时候指定为 encrypt，**获取时未指定，则无法获取到真实的值，而是加密过后的密文**。（https://eggjs.org/zh-cn/core/cookie-and-session.html）

**Comment by popomore** [comment]
密文是写到 cookie 里的，你拿到加密后的有什么用吗。

**Comment by w567675** [comment]
只是按照文档试了下，发现与文档描述不符。  拿到加密后没什么特别用。
