### ISSUE TITLE
为什么egg选用koa

### ISSUE THREAD

**Issue by vivikcat** [eggjs/egg#159]
express4.x 也把中间件分离了，体积也变得轻量可定制。
如果说generator函数是主要区别，通过使用co来封装express也能达到同样的效果。
而express文档更加全面，使用者也更加熟悉，性能上也略胜koa。
那么egg为什么选用koa？

**Comment by popomore** [comment]
我发表下个人观点

1. koa 更精简，利于扩展，egg 的 extend 就是对 koa api 的扩展。
1. 对于中间件，koa 的洋葱圈比 express 更加强大。
1. 拒绝 callback 是用 node 构建复杂业务的起点，就算你用 promise 也会遇到各种未捕获异常的坑。koa2 已经完全支持 async/await，这是未来，同步写法让你的代码更加精简。
1. 性能上其实没啥好比较的，一上业务框架这点差异可以忽略不计，而且随着 v8 的优化会越来越快。
1. 最终说到为什么，egg 已经开发了两到三年，当时选择 koa 是更佳的。

**Comment by dead-horse** [comment]
我以为 koa 比 express 的设计理念更领先这件事情早在两年前就已经阐述清楚了，包括 express 的作者和维护者（TJ、 Jonathan）弃坑从 express 转向开发 koa 就能说明很多问题了。

**Comment by popomore** [comment]
@dead-horse 那你是不是应该放些以前的链接

**Comment by dead-horse** [comment]
- http://deadhorse.me/co-and-koa-talk/
- http://deadhorse.me/slides/koa.pdf
- https://docs.google.com/presentation/d/1dmZIDgEfmMPrm4RKjCZQ5gyQvlZtyGjUiB7l1irSCUk/edit?copiedFromTrash#slide=id.p
- https://docs.google.com/presentation/d/1lsY70xapnKujmvYuKQYoopMagub91Fqc2Qm8f63tCJI/edit?copiedFromTrash#slide=id.p

**Comment by vivikcat** [comment]
@dead-horse @popomore
感谢你们的解答和资料，那请问对于KOA洋葱圈比express更加强大在哪里？貌似从执行流程来看没有什么区别。

**Comment by fengmk2** [comment]
@vivikcat 多说无益，建议你koa和express中间件都真实写一下，就会感受到不一样了。

**Comment by dead-horse** [comment]
http://deadhorse.me/co-and-koa-talk/#22  @vivikcat 对比一下实现同一个功能的两个中间件你就知道了

**Comment by popomore** [comment]
之后会有文档 https://github.com/eggjs/egg/pull/179
