### ISSUE TITLE
自定义端口 无效

### ISSUE THREAD

**Issue by iwof** [eggjs/egg#1590]
配置：
 "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "egg": "^1.7.0",
    "egg-cors": "^1.2.0",
    "egg-mysql": "^3.0.0",
    "egg-redis": "^1.0.2",
    "egg-scripts": "^1.0.0",
    "egg-view-xtpl": "^1.2.0",
    "fs-extra": "^4.0.1",
    "lodash": "^4.17.4"
  },
  "devDependencies": {
    "autod": "^2.9.0",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.1.0",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.9.0",
    "eslint": "^4.3.0",
    "eslint-config-egg": "^5.0.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=6.0.0"
  },

疑似错误代码：app_worker.js
const port = options.port = options.port || listenConfig.port;

修正：
const port = options.port =  listenConfig.port || options.port;

**Comment by popomore** [comment]
提供可复现 demo

**Comment by atian25** [comment]
`显式指定 > 配置`

这个我记得讨论过的了，如果命令行参数有传递 port 就用 port，否则用配置里面的。
更新下所有依赖包括 egg-bin (不要锁版本)再试试。

**Comment by iwof** [comment]
什么叫 不要锁版本啊？
默认的端口是7001，配置7002并不生效。
然后我进行了如上修正。
就生效了。

**Comment by atian25** [comment]
> 更新下所有依赖

不要锁版本指的是，删除 package-lock.json 这个恶心的家伙，再更新依赖。

自己修改类库源码是不建议的，至于为何配置无效，就目前提供的信息，无法判断。
如果你提 issue 时按要求提供可复现代码库，应该早就解决了。

**Comment by iwof** [comment]
我这个用的是yarn。我理所当然的删除了yarn.lock
然后重新更新了依赖，现在配置生效了。

谢谢

**Comment by atian25** [comment]
@popomore 好想做一个 post-install 删掉 lock 这个恶心的东西啊...
