### ISSUE TITLE
console 打印彩色日志

### ISSUE THREAD

**Issue by syaka-yin** [eggjs/egg#1592]
egg 的 ctx.logger 打印出来的日志都是没有颜色的

```
[ 'error', 'warn', 'info', 'debug' ].forEach(level => {
  const LEVEL = level.toUpperCase();
  ContextLogger.prototype[level] = function() {
    const meta = {
      formatter: contextFormatter,
      paddingMessage: this.paddingMessage,
    };
    this._logger.log(LEVEL, arguments, meta);
  };
});
```

强烈建议在本地开发时，控制台打印的日志可以配置颜色，写入文件的日志则不带颜色。
即：可以针对 file  jsonFile  console 三个日志通道分别配置不同的 formatter

**Comment by syaka-yin** [comment]
目前先用 `app.logger` ，app.logger 输出到 console 是彩色的

**Comment by atian25** [comment]
ContextLogger 的 formatter 覆盖了里面的 consoleTransport，@popomore 看看是否要优化下。

https://github.com/eggjs/egg-logger/blob/master/lib/egg/context_logger.js#L45

**Comment by popomore** [comment]
dup https://github.com/eggjs/egg/issues/688

有兴趣可以研究下

**Comment by pilipala6868** [comment]
> ContextLogger 的 formatter 覆盖了里面的 consoleTransport，@popomore 看看是否要优化下。
> 
> https://github.com/eggjs/egg-logger/blob/master/lib/egg/context_logger.js#L45

其实还是可配置的，并没有被完全覆盖

https://github.com/eggjs/egg-logger/blob/c08ec23fd6bcf3a889c60775caf2a5cfe70ef706/lib/utils.js#L85
深挖下去一直到上面的代码👆🏻，发现 config.logger 配置的 contextFormatter 还是可以生效的

但是 ts 提示的 options 完全没有提到，所以配置后还要加上 @ts-ignore

```
config.logger = {
  consoleLevel: 'DEBUG',
  // @ts-ignore
  contextFormatter: (meta: any) => {
    if (!meta) return '';
    const prefix = chalk.green(`[${meta.date}] [${meta.level}] [${meta.pid}]`);
    return prefix + ' ' + meta.message;
  },
};
```
