### ISSUE TITLE
egg-scripts start, 控制台无相应日志输出

### ISSUE THREAD

**Issue by wZi** [eggjs/egg#1593]
### 需求:
应用需要在启动后, 控制台也输出相应的日志. 以便观察

### 现象:
1. 使用 egg-scripts start   启动应用
2. 控制台*无*日志输出
3. {$USER}/logs/ 相应的日志文件里*有*日志
4.  run/application_config.json 内容
```json
"logger": {
      "dir": "/Users/wzi/logs/test",
      "encoding": "utf8",
      "env": "prod",
      "level": "INFO",
      "consoleLevel": "INFO",
      "disableConsoleAfterReady": true,
      "outputJSON": false,
      "buffer": true,
      "appLogName": "test-web.log",
      "coreLogName": "egg-web.log",
      "agentLogName": "egg-agent.log",
      "errorLogName": "common-error.log",
      "coreLogger": {},
      "allowDebugAtProd": true,
      "type": "application"
    },
```

### 处理方法:

config.default.js 添加如下配置:
```js
 config.logger = {
        disableConsoleAfterReady: false,
 };
```
这时控制台*有*相应内容输出了

### 疑惑
egg 网站搜不到关于这个参数的介绍
![image](https://user-images.githubusercontent.com/10461906/32218577-49508190-be66-11e7-921e-bbfb46876ca1.png)
不知道这样用对不对.

### otherInfo

* **Node Version**:  v7.9.0
* **Egg Version**:  v1.10.0
* **Plugin Name**: egg-script
* **Plugin Version**: v2.1.0
* **Platform**: mac

**Comment by atian25** [comment]
线上环境不应该把日志输出到控制台的。

你真想输出的话，不要加 `--daemon`

**Comment by wZi** [comment]
感谢答复. But 本来就没有加--daemon

**Comment by ngot** [comment]
到时可以考虑加个参数，不后台执行，用来观察

**Comment by popomore** [comment]
默认是前台运行的

**Comment by atian25** [comment]
@wZi 我这边复现不了

![image](https://user-images.githubusercontent.com/227713/32255944-e04f3b64-be79-11e7-9a44-8b45a422a5c2.png)

**Comment by wZi** [comment]
@atian25  hey man.  [最小仓库](https://github.com/wZi/eggDemo.git)

## 将代码屏蔽
config.default.js:
```js
//   config.logger = {
//     disableConsoleAfterReady: false,
//   };
``` 

### 使用npm run dev启动
有如下log:
![image](https://user-images.githubusercontent.com/10461906/32262541-1f04362a-bf10-11e7-8311-2cf052b17d74.png)
### 使用npm start
有如下 log:
![image](https://user-images.githubusercontent.com/10461906/32262567-2ef02242-bf10-11e7-80ad-ef9d71d88b05.png)
没有log
```
5s 一次
测试
hi
```

## 将代码打开
config.default.js:
```js
   config.logger = {
     disableConsoleAfterReady: false,
   };
``` 
### 重新npm start后
有如下 log:
![image](https://user-images.githubusercontent.com/10461906/32262589-5104f2cc-bf10-11e7-8aa5-e304e17d1bdd.png)
出现 log
```
5s 一次
测试
hi
```

**Comment by wZi** [comment]
另, 你上图显示的那些内容. 都会出现, 因为他们是 beforeReady ?  
而disableConsoleAfterReady这个参数控制的是ready后是否显示?

**Comment by atian25** [comment]
额... 你说的是启动成功后的日志啊，上面还以为讨论的是启动期日志。

用 `disableConsoleAfterReady` 即可，搜下源码即知：
 https://github.com/eggjs/egg/blob/5a9531abbec83fbff08ddb6feb475f87498d2a3d/lib/core/logger.js#L18

**Comment by wZi** [comment]
🤣, 感谢答复.我的意思就是 disableConsoleAfterReady 这个参数文档里面都没提到.
想确认下这样使用是否正确.

**Comment by atian25** [comment]
对的，只是不推荐用。线上服务关闭 console 好点。

**Comment by wZi** [comment]
got it. Tks

**Comment by grutty-sf** [comment]
刚好用上 thanks

**Comment by cainiaokan** [comment]
刚好用上 thanks

**Comment by zhangyu921** [comment]
thanks。。
