### ISSUE TITLE
有谁知道config文件里面的配置在service里面怎么读取？

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1595]
1，如何读取配置文件里的值？
2，为什么在service或者controller里面不能读取项目根目录下的文件？

**Comment by atian25** [comment]
1. `this.config` 请阅读文档
2. 提供详细信息.

**Comment by dead-horse** [comment]
应该要 this.app.config

**Comment by dead-horse** [comment]
第二个问题与 egg 无关，如果想引入，自己 require

**Comment by sansroman** [comment]
有相关问题,怎么使用把配置的相关变量引用为某个文件的全局变量,必须用require引入config.default.js么

**Comment by atian25** [comment]
@sansroman 通常情况下，你这个文件肯定是要在 egg 里面用的。所以思路是，你那个文件应该是 `module.exports = app => {}` 的方式，然后通过 loader 加载挂到 app 上

**Comment by sansroman** [comment]
比如我想在扩展中引用config中的常数,但是我无法访问app,我只能用上述方法通过访问app对象来获取config么

**Comment by atian25** [comment]
@sansroman 必然，刚才不是说了么，你扩展是可以拿到 app 的。

举个例子，这是一种实现方式，也可以通过 loader 等

```js
// {app_root}/lib/foo.js
module.exports = class Foo {
  constructor(app) {
    this.app = app;
  }
  sayHi() {}
}

// {app_root}/app/extend/application.js
const Foo = require('../../lib/foo');
const FOO = Symbol('Application#foo');
module.exports = {
  get foo() {
    // 缓存
    if (!this[FOO]) {
      // 初始化
      this[FOO] = new Foo(this);
    }
    return this[FOO];
  }
}

// 使用
this.app.foo.sayHi()
```

**Comment by ZengTianShengZ** [comment]
框架在启动时会把合并后的最终配置 dump 到 run/application_config.json（worker 进程）和 run/agent_config.json（agent 进程）中，可以用来分析问题。

所以可以这么获取

```
const { config } = require('../run/application_config.json');

// eg 
// config.Application 
// config.RestApiKey
```

**Comment by atian25** [comment]
。。。 楼上不要误导人，这个文件不要读取，直接 this.ctx.config，多看文档

**Comment by ZengTianShengZ** [comment]
我错了，多看文档

**Comment by ZengTianShengZ** [comment]
以下场景怎么获取 config 的配置呢

```javascript
// app/db/index.ts
const DB = require('db-demo');
// 如何拿到 config 配置
DB.initialize(config.SecretKey, config.SafetyKey);
export default DB;
```

```javascript
// app/module/index.js
import DB from '../db';

export const find = (id: string) => {
   return DB.find(id);
}
```


以上场景无法通过 service或者controller或 application 拿到上下文环境，如何获取 config 配置信息呢。

虽然最终 `find` 会在  service或者controller 下调用，但总不能一层层将 `ctx.config` 传递到 `app/db` 下做初始化吧

**Comment by atian25** [comment]
js 的话，不应该自己 require，而是如我上面示范的代码，通过 loader 来加载 app/db/index.ts

ts 的话，应该要通过注解的方式去实例化注入， cc @killagu

**Comment by wenlittleoil** [comment]
在可以访问到app的情况下，肯定可以知道怎么访问到config，现在大家的疑问是在一些自定义目录中，想访问到config配置，只能靠自己require('config.default.js') 么，楼上答非所问的一大堆。

**Comment by atian25** [comment]
https://github.com/atian25/egg-showcase/pull/13

通过 loader 去加载自定义目录即可。
