### ISSUE TITLE
新手求问一下 sticky 模式的运作方式

### ISSUE THREAD

**Issue by wyd0395** [eggjs/egg#1596]
再用egg socket.io测试的时候发现，不管多少请求，socket请求都是同一个进程在处理，请问是否sticky 模式就是强制只用一个进程来处理请求，以免出现socket对象共享的问题？

**Comment by ngot** [comment]
不是共享问题。这个是socket.io协议实现的一部分，如果不实现这个sticky特性，socket.io在多进程下无法工作。

所以，并没有特殊目的要一些特殊需求，仅仅是因为：sticky是socket.io通讯协议的一部分，不实现无法工作。

**Comment by wyd0395** [comment]
多谢解答！
