### ISSUE TITLE
新手：求问app.js 的自定义启动的beforeStart方法

### ISSUE THREAD

**Issue by w567675** [eggjs/egg#1597]
```js

// ${root}/app.js
const sleep =  (time) => {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve('wake up'), time);
    });
}
module.exports = (app) => {
    app.beforeStart(function* () {
        // 应用会等待这个函数执行完成才启动
        app.cities = yield sleep(3000)
      });
}
```

```js

// ${root}/app/controller/index.js
module.exports = app => {
    class HomeController extends app.Controller {
        async index(ctx) {
            console.log(ctx.app.cities);
            ctx.body = {
                cities: ctx.app.cities
            }
        }
    }
    return HomeController;
}
```

在运行egg-bin dev 之后的访问127.0.0.1:7001/index，前3秒内输出的是 **"undefined"** ,  3秒后输出 **"wake up"**  。  有点迷茫 ，这个是正常的逻辑么？   文档不是说  **等初始化完成后应用才可以启动成功，并开始对外提供服务。**

**Comment by popomore** [comment]
https://github.com/eggjs/egg-development/blob/master/config/config.default.js#L14

本地环境是有差异的，把这个配置设为 false

@atian25 开源版本默认设为 false 好了。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-development/blob/master/app.js#L5

为了开发期的重启速度，默认在开发期跳过了这个检查，你把 fastReady 改为 false 就达到你预期了。

**Comment by atian25** [comment]
@popomore 嗯，改了吧，算 break 么？

**Comment by popomore** [comment]
@atian25 这个不算 break，算 fix 吧

**Comment by w567675** [comment]
@popomore @atian25  OK~谢了
