### ISSUE TITLE
两个service不能互相调用？

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#1598]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
可以调用，`this.ctx.service.xx`

**Comment by tong3jie** [comment]
@atian25 
擦，我知道。文件名不能使用字母+数字的组合。

**Comment by atian25** [comment]
可以使用的，你是用了下划线什么的吧，会转换为驼峰。

**Comment by tong3jie** [comment]
没有啊 文件名是S10001,就直接报  Cannot read property 'send' of undefined

**Comment by atian25** [comment]
`this.ctx.service.s10001.echo()`

如还有问题，提供最小可复现代码

**Comment by tong3jie** [comment]
/service/interface/S10001.js
`'use strict';

module.exports = app => {
  class S10001 extends app.Service {
    async send(...arg) {
      console.log(arg);
    }
  }
  return S10001;
};
` 
/service/getReport.js 
`module.exports = app => {
  class getReport extends app.Service {
    async getReport(channelID, ctUserLists, cmUserLists, cuUserLists) {
      const { ctx, app } = this;
      if (a > 0) {
          switch (JSON.parse(b).serverId) {
          case 'S10001':
            ctx.service.interface.S10001.send(a, c);
            break;
          default:

          }
        }
      }
    }
  }
  return getReport;
};`

**Comment by atian25** [comment]
学会 Markdown 的代码排版，上面那段看不懂。

要三个 `

**Comment by ngot** [comment]
![image](https://user-images.githubusercontent.com/5243774/32268092-9126de42-bebb-11e7-8f33-e1023db7d123.png)

为什么这么大的字，直接就忽视了呢。直接一开始就提供好必要信息，然后维护者给出答案，问题就很快就解决了。

挤牙膏式的一问一答，即浪费了自己的宝贵时间，也让回答问题的同学头疼。

**Comment by tong3jie** [comment]
抱歉抱歉，下次注意。
