### ISSUE TITLE
egg生产环境推荐使用pm2吗？

### ISSUE THREAD

**Issue by Rwing** [eggjs/egg#160]
因为egg本身有cluster机制，所以还需要使用pm2吗？

**Comment by popomore** [comment]
可以不使用 pm2，如果进程挂了 master 会自动恢复，启动脚本让他后台运行就好了。

**Comment by Rwing** [comment]
这个我明白，既可以用也可以不用，但是官方的推荐或者说最佳实践是用还是不用呢？

**Comment by JacksonTian** [comment]
不用。

**Comment by ngot** [comment]
不用
