### ISSUE TITLE
页面渲染时候的模板不能是url形式的吗？

### ISSUE THREAD

**Issue by huboshu0819** [eggjs/egg#1600]
view的root设置如下：
```
config.view = {
    root: 'http://172.19.25.46:9090/',
    defaultViewEngine: 'nunjucks'
  }
```
渲染的函数是这样写的
```
* renderTpl(){
	 let data =  yield this.getData();
        data = data || {};
	this.ctx.body = yield this.ctx.renderView('vote/index.html', data);
	// var tpl = yield this.ctx.curl('http://172.19.25.46:9090/vote/index.html');
	// this.ctx.body = yield this.ctx.renderString(tpl.data.toString(), data);
 }
```
请求报错 
'Can\'t find vote/index.html from http://172.19.25.46:9090/'
但其实 http://172.19.25.46:9090/ vote/index.html是可以正常访问的，难道一定要renderString那种方式吗

**Comment by atian25** [comment]
root 是模板的物理目录路径，而不支持从远端读取模板，这是 nunjucks 本身的限制。

如果你有需求，可以 直接定制下 nunjucks 的 FileLoader 即可。

**Comment by huboshu0819** [comment]
好的，谢谢

**Comment by atian25** [comment]
看下 egg-view-nunjucks 和 nunjucks 的 webloader 源码参考下即可，大概的思路是：

1. 在应用的 app.js 里面可以拿到 nunjucks 实例引用
2. 替换掉它的 loader 为自己的 loader
3. 自己的 loader 参考 webloader 的方式，支持 callback 的。注意要把 egg-view-nunjucks 原来 loader 关于安全那块的替换也实现了。

**Comment by atian25** [comment]
还有一种比较丑陋的方式就是，自己封装一个 renderRemote 方法，自己在里面 fetch，有点类似你的代码，扩展到 context.js 即可。这种方式有可能导致 include 有问题。

**Comment by huboshu0819** [comment]
哈哈 其实我就是打算这么干的，先试一下第一种方案

**Comment by huboshu0819** [comment]
还一个问题，我看egg-static的文档说只支持所有koa-static-cache.的配置，但是设置alias好像是无效的
```
config.static = {
    maxAge: 0,
    alias: { }
  }
  config.static.alias[path.join(appInfo.baseDir, 'app/public/upload/vendor_b8fdff88.js')] =path.join(appInfo.baseDir, 'app/public/upload/test.js')
```

**Comment by atian25** [comment]
可以跟下源码分析下

**Comment by popomore** [comment]
每次请求性能太差了吧，你可以在 render 前下载下来再 render，如果有更新重新下周。

**Comment by atian25** [comment]
@popomore 那样还是不行的，include 会有问题，直接写个 WebLoader 即可，支持 callback 的。

**Comment by popomore** [comment]
为啥不行，模板渲染不要考虑远程问题，不然给用的人也是留坑。webloader 是给浏览器用的。

**Comment by atian25** [comment]
喔，我理解错你的意思了，我以为你说方案二。

确实，方案三更好：
- 启动时同步模板到指定目录
- 有更新时推送过来更新掉 cache

这方案也是蚂蚁正在用的。
