### ISSUE TITLE
handlebarjs的helper

### ISSUE THREAD

**Issue by 280455936** [eggjs/egg#1604]
@huangyanxiong01

egg-view-handlebars
handlebarjs的helper
Handlebars.registerHelper('link', function(text, url)
如何注入使用？

**Comment by popomore** [comment]
目前不支持，你可以按照 registerPartial 提 PR https://github.com/eggjs/egg-view-handlebars/blob/master/app.js#L12

**Comment by 280455936** [comment]
config.handlebars= {
    
    knownHelpersOnly: false,
    
  },



  handlebars.registerHelper('fullName', function(person) {
    
        // person = {firstName: "Alan", lastName: "Johnson"};
        return person.firstName + " " + person.lastName;
      });


============<h2>By {{fullName person}}</h2>===================

**Comment by amesshen** [comment]
确实handlebars的helper如果不能用Handlebars.registerHelper()的话会比较有局限性。
比如按照原来的helper自定义方法写一个helper：
`handlebars.registerHelper('equals', function(a, b, options) {
    if ((a != null ? a.toString() : void 0) === (b != null ? b.toString() : void 0)) {
      return options.fn(this);
    }
    return options.inverse(this);
  });`
我可以方便的在view中去判断：
`{{#equals a 5}}some code{{else}}{{some different code}}`
但是现在egg约定的helper写法，并不支持这样做
希望能得到解决，谢谢

**Comment by jayconscious** [comment]
花了半天的时间寻找如何注册helper，然而却不支持，现有的Handlebars太鸡肋了😔
