### ISSUE TITLE
egg如何启动多个端口 

### ISSUE THREAD

**Issue by klk2** [eggjs/egg#1607]
* **Node Version**:8.4.0
* **Egg Version**:1.3.0
* **Plugin Name**:egg-scripts
* **Plugin Version**:1.2.0

如题，egg如何启动多个端口，比如http：8080，https：9090 ，其他API：7070

**Comment by atian25** [comment]
只能多个服务。

**Comment by klk2** [comment]
agent里边我创建了socket服务，启动两个服务会造成socket端口冲突，起两个服务也会挂载同样的组件。
可以像express 那样，启动不同端口的服务，指定挂载的组件吗

**Comment by popomore** [comment]
http 和 https 没啥差别，不需要起两个端口，前面用 nginx。其他 api 是啥，可以 proxy_pass 到具体 api

**Comment by klk2** [comment]
https一个公开的端口，我还想proxy一个非公开的端口，在阿里云内网访问，就需要egg再启动一个端口服务。
