### ISSUE TITLE
如何通过配置来区分agent和application所需加载的插件？

### ISSUE THREAD

**Issue by walkerx** [eggjs/egg#1608]
如何通过配置来区分agent和application所需加载的插件？

**Comment by popomore** [comment]
插件加载和这个无关

**Comment by atian25** [comment]
为什么要区分？插件加载对性能没啥影响的

发自我的 iPhone

**Comment by walkerx** [comment]
在我的场景里，agent 和 application不需要加载相同的插件。

**Comment by atian25** [comment]
怎么样的场景

发自我的 iPhone

**Comment by popomore** [comment]
这个是插件里面实现的，能不能给个具体的问题

**Comment by walkerx** [comment]
噢噢··比如agent不需要连接数据库就不需要egg-sequelize。也不需要对外提供服务，就不需要session，multipart之类的内置插件。目前plugin的配置是同时影响application和agent.

**Comment by popomore** [comment]
egg-sequelize 没加这个参数，是否在 agent 或 app 执行是由插件本身来实现的，使用方不需要关心。

- 可以给 egg-sequelize 提一个 PR，支持 `config.sequelize.agent = false`
- session，multipart 并没有在 agent 实现

**Comment by walkerx** [comment]
了解，在插件中实现。谢谢。
session, mulipart没有在agent实现么？那为什么run目录下agent_config.json有dump出相关配置啊？

**Comment by popomore** [comment]
因为这两步骤是分离的，配置加载后是否被使用是看插件的具体实现的，配置的加载是一个通用的过程。

**Comment by walkerx** [comment]
明白，由插件自己来选择是否在agent或者application中启用。谢谢
