### ISSUE TITLE
agent和application是否有提供workerid的属性？有提供的话，当app进程重启，其workerid保持不变？

### ISSUE THREAD

**Issue by maidol** [eggjs/egg#1609]
生产环境中想获取到app_worker的id做一些监控的操作，类似pm2的pm_id。
请问agent和application是否有workerid的属性？有提供的话，当某app进程异常重启，其workerid是否保持不变？

**Comment by atian25** [comment]
每一个 Process 都会有 process.pid，workerid 不会保留。

异常重启的时候，你在 agent 里面可以收到 Message，从而进行记录和监控。可以看下 egg-cluster 的源码

**Comment by maidol** [comment]
因为 process.pid会改变，需要的是固定的workerid。如果要拿到这个固定的workerid，目前的框架是没法直接可以提供是吧？

**Comment by atian25** [comment]
worker 之间是一样的，他们是不应该有区别的，为什么需要知道固定的 workerid 呢？

**Comment by maidol** [comment]
因为我这边的团队有自己的日志组件，目前大多数的项目的在多进程下写日志的方案是用文件名用workerid来区分，egg的日志方案不大适合目前项目

**Comment by maidol** [comment]
打算在egg的框架下集成现有的日志和监控方案，都需要这个workerid，有这个id就好办了

**Comment by atian25** [comment]
但我还是不理解为什么要区分多进程？日志不是只是单个用户本次的请求的全流程都是一起记录就好了。

WorkerA 和 WorkerB 处理的工作有什么区别么?

**Comment by maidol** [comment]
我这的做法是每个进程一个日志文件，跟egg的有点不同

**Comment by maidol** [comment]
egg为避免日志文件的多进程下rename/create冲突，在滚动时是指定某一个work来做的。而我这则不是，不同的worker写自己的日志文件(例如 worker.1.log, worker.2.log)。如果我要沿用自己的日志方案，这个workerid是关键，egg目前是否不能如此实现？

**Comment by popomore** [comment]
用进程 pid 就好了，如果进程挂了后启动这是新进程，不知道是原来哪个进程

**Comment by atian25** [comment]
挂掉后新启动的那个进程，跟原来进程并没有任何关系，为什么一定要给他们同个 id 呢？实在需要得话，agent 通过消息给他们分派吧。

发自我的 iPhone

**Comment by maidol** [comment]
每个app worker第一次启动后会被分配一个workerId， 即使之后这个worker重启了，workerId要保持之前分配的那个。因为日志文件格式` work.${workerId}.log`，而process.pid会变动，不能用。这是这边的需求。使用agent 给他们分派可以做到么？egg-cluster源码里面看到egg-pids这个事件，可以用这个事件？

**Comment by atian25** [comment]
但是这两个 worker 一点关系都没有，为何一定要放在一起呢

发自我的 iPhone

**Comment by maidol** [comment]
agent 下面管理着一群 worker, 这些worker做的事情都是一样, 如果对同一个日志文件rename/create就会有冲突，现在我这就得用workerId来区分这群workers的日志文件了，而且重启后要保持workerId是原来分配的，否则就会混乱。egg的日志方案跟我原项目的不大一样。而egg的框架缺这个id，不能直接兼容目前的日志方案。就是这个意思了

**Comment by atian25** [comment]
但是你一个 worker 死掉后，另一个重启了，这 2 个 worker 直接没啥关系，为什么它一定要继承前面的那个文件名呢？

多进程操作同一个日志，包括它的切割，我们在 egg-logger 和 egg-logrotator 里面有处理了，并没有冲突。

**Comment by atian25** [comment]
feel free to reopen if you got additional information

**Comment by maidol** [comment]
我的建议是，能否由master进程为每个worker分配一个id, 例如我设置了5个worker, 其id分别为 [1 ，2，3，4，5]；如果发生crash，worker1，worker2，worker4退出了，并且重启，重启时这三个worker的id从[1，2，4]里随机分配。我尝试通过agent来分配workerid，但是有很多限制

**Comment by atian25** [comment]
抱歉，我一直无法理解为什么 ID 必须复用。而且为什么你的 worker 会经常死掉。

**Comment by maidol** [comment]
就拿pm2来说吧，启动服务时会给每个worker分配一个pm_id， 并且挂在环境变量process.env.pm_id。pm_id可以在某些情况有特殊的用处的

**Comment by maidol** [comment]
主要是现在我们的项目写的日志组件依赖这样的id，而egg没提供，项目想尝试使用egg，可是没法方便地集成现有的日志方案进去

**Comment by atian25** [comment]
这个之前就理解了，也提了方案。我不理解的是，为什么一个进程死掉后，新重启的进程必须用之前那个进程的 pid，它们是没有任何关联的

**Comment by atian25** [comment]
pm2 重启的进程的 pm_id 也不是复用的吧

**Comment by maidol** [comment]
例如用pm2开4个实例，pm_id 就是 [0, 1, 2, 3]， 任何一个实例异常重启，或者手动杀死重启，最后的pm_id也是 [0, 1, 2, 3]

**Comment by maidol** [comment]
pm_id跟进程的pid是无关的，pm_id是逻辑上的workerid的意义

**Comment by maidol** [comment]
我现在通过这种方式来分配，但是有限制，没法做到worker实例启动前就做好分配
https://github.com/maidol/egg-sample/blob/dev/agent.js
https://github.com/maidol/egg-sample/blob/dev/app.js

**Comment by diamont1001** [comment]
其实egg里你也可以通过 `listWorkerIds` 来拿到 0~N 的下标
