### ISSUE TITLE
关于 controller 使用类的写法的问题

### ISSUE THREAD

**Issue by jinsihou19** [eggjs/egg#1611]
看到文档关于 controller 部分的时候就想到的问题。
我认为，controller 写成类的方式，虽然书写规整，但是，实例化浪费性能，实例占用内存，视乎也没有带来其他的好处。高并发下，再微乎其微也会被放大，再者，node本就是单线程事件循环，当然是希望越少消耗时间越好。数据的共享可以放在 context 中，Controller 基类中处理的一些方法可以放到工具类或者中间件中处理。
另外，这样书写语义化很差，会导致误解，新手开始用 Egg.js 会误以为 module.exports 导出的类会自动实例化，而实际情况并不是。有一个例子， React 换用 ES6 书写之后，取消自动绑定就是为了避免语义上和 ES6 语法冲突。作为一个企业化的框架，最好不要有这样的歧义存在吧。

**Comment by atian25** [comment]
1. 阿里双 11 这类的高并发下，还是微乎其微的影响，那也只能是微乎其微了。
2. `module.exports 导出的类会自动实例化` 这段没怎么看懂。

**Comment by qingdengyue** [comment]
module.exports 导出的是Class类型还是类型实例  取决于使用方的使用场景。
@atian25 ‘导出类的自动 实例化’应该是说  module.exports=new ClassType()之类的吧

**Comment by atian25** [comment]
抱歉，还是没理解。

> 新手开始用 Egg.js 会误以为 module.exports 导出的类会自动实例化

Egg 的很多类是会在使用的时候自动实例化的，这是 Egg 的开发规范，开发者按照这套规范来即可。
