### ISSUE TITLE
如何外部调用 app.services

### ISSUE THREAD

**Issue by aa900031** [eggjs/egg#1612]
想写一个npm script直接执行app.service内的方法

原因：因为heroku免费配额不够支援24/7的服务器运行，所以schedule不能一直跑在背景，想用heroku官方的schedule机制

**Comment by popomore** [comment]
开放一个 http 接口，需要的时候调用一下？

**Comment by aa900031** [comment]
也是可以，不过这样感觉不安全，想求个正确解法

**Comment by popomore** [comment]
接口本身可以做一个限制，正常解法是自己实现一个 schedule 的插件对接 heroku，由这个插件来触发，没用过 heroku 的这个功能需要你自己研究，文档在 https://eggjs.org/zh-cn/basics/schedule.html#扩展定时任务类型

**Comment by atian25** [comment]
我简单看了下：

> 因为heroku免费配额不够支援24/7的服务器运行

所以你是没办法让 Egg 一直运行着的，我不确定 heroku 是限制了 24 小时不能累计运行多久，还只是 30 分钟无活动自动休眠。

但如果你只是用来做定时任务，不太介意休眠后重启那么十来秒，或者你不是每秒都需要运行，就问题不大。

但我怎么觉得这类场景用云函数之类的更适合呢？

**Comment by aa900031** [comment]
heroku 免费的机器是闲置30分钟会自动休眠，帐户每月有一定的运行时间额度(约700小时)

不是只做定时任务而已，定时任务只是其中之一，最主要还是提供一个api服务

**Comment by atian25** [comment]
700 小时相当于 29 天了，那你的 API 服务也不能一直运行着，不会有问题么？

闲置的那个可以通过配置个 schedule 定时 http 自己的外部域名。

**Comment by aa900031** [comment]
@atian25 
主要是帐户内还有切其他专案，所以是所有专案共用那700小时
我设想是API没人请求的话就闲置没关系，但是定时任务不能闲置(假设定时任务每小时跑一次，但三小时没人请求)

**Comment by atian25** [comment]
heroku 的 schedule 机制其实就是提供一个 bin，你可以像 @popomore 说的那样，提供一个 http 接口，然后自己带一段 token 校验即可，反正是内网，不会有安全问题。

闲置后自动休眠，应该是会收到请求那一刻会自动启动，这个启动耗时应该还是可以接受的，所以可以考虑随便一种从外部请求公网 URL 的方式。

**Comment by aa900031** [comment]
有看过 heroku schedule 机制了，也正打算用哪方向做～
感谢大神
