### ISSUE TITLE
alinode不支持node 8.9.0？

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#1615]
昨天升级到8.9.0后，alinode监控失效。

**Comment by atian25** [comment]
装对应版本的 alinode

发自我的 iPhone

**Comment by atian25** [comment]
https://alinode.aliyun.com/doc/alinode_versions

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/pull/1602 有 node 9 的 ci 测试的。
