### ISSUE TITLE
如何在 master 上做事？

### ISSUE THREAD

**Issue by galenyuan** [eggjs/egg#1617]
有一个比较特殊的依赖需要在 master 上 require 才启动 IPC 的 server，但现在发现我自己业务的逻辑似乎都是被放在 worker 里跑的，除了去修改 egg-bin 之外还有什么办法能让我在 master 做一次 require？

**Comment by popomore** [comment]
可以在 agent 实现

**Comment by atian25** [comment]
master / agent / worker 都是独立进程。还是具体讲下你的场景吧

发自我的 iPhone

**Comment by galenyuan** [comment]
依赖中有大概这样的操作：
```javascript
const SocketIPC = require('SocketIPC')

if (cluster.isMaster) {
  SocketIPC.registerMaster('xxxx', coolest(function *() {
    return xxxx
  }));
}
```
https://github.com/YanagiEiichi/SocketIPC

@YanagiEiichi 求讲解黑魔法..

**Comment by atian25** [comment]
为什么要 cluster.isMaster ？agent 只有一个进程的，不会执行多次

发自我的 iPhone

**Comment by atian25** [comment]
如果你只是想实现 worker 之间的数据通讯，可以看下：
- [多进程模型和进程间通讯](https://eggjs.org/zh-cn/core/cluster-and-ipc.html)
- [多进程研发模式增强](https://eggjs.org/zh-cn/advanced/cluster-client.html)

**Comment by galenyuan** [comment]
关掉了，设计本身就有冲突，我们内网的一个基础包一定要在 master 上起 IPC，回头试一下自己做个脚手架启动服务，3Q

**Comment by atian25** [comment]
自己写个 index.js 去调用 startCluster 即可，这个文件就是在 master 上的。但建议不要这么玩，master 是要求越简单越好的。
