### ISSUE TITLE
Nunjucks渲染过程中macro无法使用helper

### ISSUE THREAD

**Issue by 634750802** [eggjs/egg#1618]
* **Node Version**: v8.6.0
* **Egg Version**: ^1.9.0
* **Plugin Name**: egg-view-nunjucks
* **Plugin Version**: ^2.1.4
* **Platform**: macOS 11.11
* **Mini Showcase Repository**:

使用Nunjucks的`import as`引用macro时，macro内部不能使用`helper`。
目前我的解决方法是把helper作为参数传递给macro。

猜测原因：Nunjucks的macro中不能使用locals

**Comment by atian25** [comment]
`macro` 设计如此，不能访问当前 context 的。实在有需要自己 `addGlobal`

https://github.com/mozilla/nunjucks/issues/464

**Comment by guohuihot** [comment]
这个有解决方案吗？不然真的没法玩了，框架看着挺好，用起来各种问题

**Comment by atian25** [comment]
二楼已经说了。
