### ISSUE TITLE
redis设置session异步问题

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1621]
* **Node Version**: v8.8.0
* **Egg Version**:1.9.0
* **Plugin Name**: egg-session
* **Plugin Version**: 2.1.1
* **Platform**: 
* **Mini Showcase Repository**:
请求设置session的时候先执行了返回数据；后面才设置到redis
```javascript
//  app/index.js
async setSession(ctx) {
      let n = ctx.session.views || 0;
      ctx.session.views = ++n;
      this.logger.info(ctx.session.views);
      ctx.body = await ctx.session.views + ' views';
    }

// app.js   app.sessionStore
  app.sessionStore = {
    * get(key) {
      const res = yield app.redis.get(key);
      if (!res) return null;
      return JSON.parse(res);
    },

    * set(key, value, maxAge) {
      // maxAge not present means session cookies
      // we can't exactly know the maxAge and just set an appropriate value like one day
      if (!maxAge) maxAge = 24 * 60 * 60 * 1000;
      value = JSON.stringify(value);
      yield app.redis.set(key, value, 'PX', maxAge);
    },

    * destroy(key) {
      yield app.redis.del(key);
    }
  };
};
```
先执行了 ctx.body响应了请求后才执行了set方法，顺序有问题
万一redis set出错,无法捕捉
@popomore

**Comment by chenyulun** [comment]
是不是需要在ctx.session注入提供特殊方法来同步设置？getter,setter好像做不到

**Comment by popomore** [comment]
把 generator function 改成 async function

**Comment by chenyulun** [comment]
其实和sessionStore对象没什么关系，
单单这条语句都无法做到同步设置app.redis.set
```javascript
ctx.session.views = n;
```
其实我想要的是
```javascript
async setSession(ctx) {
      let n = ctx.session.views || 0; // get views可以不用异步
      // ctx.session.views = ++n;  // 无法异步吧
      await ctx.session.set('views', ++n) ; // set需要同步设置；才能捕捉到错误
      this.logger.info(ctx.session.views);
      ctx.body = ctx.session.views + ' views';
    }
```

**Comment by popomore** [comment]
session 设置是中间件外层做的，不是同步设置，每次请求只会调用一次而不是 set 就调用。

**Comment by chenyulun** [comment]
那这个问题怎么解决？无法捕捉app.redis.set错误；
应该给开发者一个手动调用的方法，调用完后如果没人修改session不在执行set方法；如果有改变或者开发者没手动调用，自动执行set方法
还有一个问题，每次都返回一个新的EGG_SESS；会自动删除原来的EGG_SESS在redis的缓存吗？
因为执行
```javascript
async destroy(key) {
      await app.redis.del(key);
    }
```
只能删除最后返回的EGG_SESS的redis缓存；
为什么不能用同一个EGG_SESS而是返回新的？

**Comment by popomore** [comment]
好像没实现 session 回滚，要 @dead-horse 看看

**Comment by chenyulun** [comment]
我知道了2个问题：
    1.重新设置EGG_SESS是一样的，只是更新了缓存时间，没问题
    2.其实set session到redis是同步的；执行的session.save()方法，存储错误会造成500错误

**Comment by dead-horse** [comment]
可以在 onerror 中捕获到 redis 设置异常的错误。http://eggjs.org/zh-cn/core/error-handling.html

由于它是框架层面抛出的异常，无法直接通过错误中间件捕获，你有强需求要捕获这个异常么？还是一个担忧而已？

**Comment by kasora** [comment]
@dead-horse 遇到了同样的问题。
目前我们的设计中，错误处理中间件处理自定义类型的已知错误，`onerror`中是处理未知的错误，同时给到日志系统一个提示。
在`sessionStore`中写入redis前我们想对数据进行一次校验，这时候如果用户伪造了`cookie`就会直接给出500报错。
请问这种情况下 egg 的最佳实践是怎么实践的呢？
