### ISSUE TITLE
node_modules/sequelize-cli/bin/sequelize  cannot find

### ISSUE THREAD

**Issue by qw9002** [eggjs/egg#1622]
* **Node  Version 8.9**:
* **Egg Version **:
2017-10-24, Version 1.10.0, @popomore
* **Plugin Name**:
egg-sequelize
* **Plugin Version**:
3.1.0 
* **Platform**:
vim
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
请提供更多的信息

**Comment by atian25** [comment]
feel free to reopen if provide more information
