### ISSUE TITLE
egg-socket.js 能只从服务端发布消息吗？而不是从客户端触发 io route

### ISSUE THREAD

**Issue by foooooouny** [eggjs/egg#1626]
使用egg-socket.js时遇到点问题，看官方文档的流程以及demo，可以创建从客户端发送到服务端，然后服务端返回客户端的请求。
但是我想让用户在调用接口的时候，从对应业务的controller中根据条件向客户端emit消息，总是不成功。希望能帮我解答一下。
代码如下：
```js
// app/router/index.js

// 这个是我的接口router，我是这样用的
app.post('/api/match', app.middlewares.user(app), app.io.controllers.match.socketMatch);
// 这个是根据demo走的socket请求，可以用
app.io.route('match', app.io.controllers.match.index);

---------

// app/io/controller/match.js

   async index() {
      const { ctx } = this;
      const message = ctx.args[0];
      console.log('chat 控制器打印', message);
      ctx.server.sockets.emit('match123', ctx);
    }
    // 用户押注
    async socketMatch(ctx) {
      const { value } = ctx.request.body;
     // 这个地方发送的请求，客户端收不到，然后在这里log ctx.server 是undefined
      ctx.socket.emit('match', 'socketMatch');
// ...
}
```
我不知道能不能单纯从服务端发送信息给客户端，希望解答一下，谢谢。

**Comment by ngot** [comment]
http 请求和 socket 是两个概念。

没有这种用法：`app.post('/api/match', app.middlewares.user(app), app.io.controllers.match.socketMatch); `

对于，这种需求，可以考虑维护一个后台任务，由http请求，把任务丢到后台任务队列去处理，由任务队列，从已经连接的客户端中选择对应的然后 emit 消息。

要分清楚：http 和 socket 是两个完全不同的概念，不能混淆，更无法混用。

**Comment by foooooouny** [comment]
感谢！
刚接触socket，对socket这部分暂时还是一知半解，也在学习中。
主要还是思路问题，只想一味的从后端入手，所以一直纠结在这。。。
最初是由于把io下的controller和app下的controller弄混了，总觉得它们两个是大同小异的，只是一个支持socket而已，后面又研究了一下，发现两个本质就不同，就是两个东西。
现在改变思路，从客户端emit，服务端分发了。
这个issue也可以算是给像我这样不太了解socket的人一个答疑。

**Comment by foooooouny** [comment]
对了，如果是动态的命名空间，有什么实现的思路吗？

**Comment by ngot** [comment]
什么场景下会有动态的场景？ 一般都是服务端先配好，然后给客户端去连接。

**Comment by ngot** [comment]
这种 egg-socket.io 插件就不做了。你可以在 app.js 里面自定以实现的。动态的去 on 事件即可。

**Comment by foooooouny** [comment]
👌，谢谢

**Comment by pengliheng** [comment]
和socket.io一样么？
和koa 搭配又怎么用
