### ISSUE TITLE
关于egg-view 模板引擎 SET_LOCALS 合并ctx, request, helper 上下文问题

### ISSUE THREAD

**Issue by hubcarl** [eggjs/egg#1627]
## 问题描述

关于 egg-view 中 [context_view.js](https://github.com/eggjs/egg-view/blob/master/lib/context_view.js) SET_LOCALS 会合并ctx, request, helper 上下文：

```js
  [SET_LOCALS](locals) {
    return Object.assign({
      ctx: this.ctx,
      request: this.ctx.request,
      helper: this.ctx.helper,
    }, this.ctx.locals, locals);
  }
```

这个逻辑对于 swig，nunjucks 等纯服务端渲染模板来说没有问题， 但对于 Vue，React，Angular 等这种服务端渲染或者同构应用，Node 端的数据需要通过INIT_STATE的方式输出到页面，这样就导致 ctx，request, helper 一堆东西输出到页面，一是输出很多无用的信息到页面， 二是不安全，一不小心就把敏感信息输出到页面了。

## 目前想到的解决方案

- 方案一：在自己的模板引擎里面重新处理一下合并后的locals，比如 { ctx: null, request: null, helper: null} 或者delete，不太优雅，这样每个扩展的模板引擎都得自己实现。目前我这边是这样实现的。

- 方案二： 希望 egg-view  底层提供一个开关选项，用于设置是否合并 ctx, request, helper 上下文， 默认合并。

@popomore @atian25  看看

**Comment by atian25** [comment]
看了下，`__INITIAL_STATE__` 是用 `JSON.stringify` 输出的，可以把这几个变量都通过 `Object.defineProperty({ enumerable: false, configurable: true })` 配置上去，应该就不会被渲染了

**Comment by atian25** [comment]
不过插件那边 https://github.com/eggjs/egg-view-nunjucks/blob/fb71b0309d20d6d82ed6f8c1ec3e977fa06c79a4/lib/view.js#L11 覆盖掉 helper 的就要自己改了

**Comment by popomore** [comment]
是不是别用这个，中间件设置的什么你也不知道，ssr 可以单独指定一个 initState

**Comment by hubcarl** [comment]
egg 默认 render 会执行SET_LOCALS逻辑，另外 Object.defineProperty({ enumerable: false, configurable: true }) 方式可以

**Comment by popomore** [comment]
但是 ssr 的 render 是插件自己实现的，插件不用那个对象就好了。

**Comment by atian25** [comment]
@popomore 没办法不用吧，因为应用层可能会操作 ctx.locals 然后丢给 render

**Comment by popomore** [comment]
但是插件可能也会设置一些其他无法预料的在 locals 上面，这个方案也无法完全解决问题。我不理解为什么 ssr 要设 locals，应该和普通模板不太一样吧。

**Comment by hubcarl** [comment]
ssr 与普通模板没什么不一样，唯一不一样就是要把数据输出到页面，多了这一步。现在的ssr实现方式是context上面直接写render 方法，不是使用app.view.use的方式， 这样多模板引擎没法用。现在准备改成 app.view.use 方式注册，这样就会统一走到 egg-view 引擎的逻辑。

**Comment by popomore** [comment]
如果一样的话不应该处理这个 locals，输出到页面的数据我约定为 locals.context

**Comment by hubcarl** [comment]
@popomore  这个是一种方案， 我认为可以这样实现，目前 SPA SSR 就是加了一个子节点 state  ，现在只要适配一下多页面的SSR即可

**Comment by popomore** [comment]
多页面 ssr 是多个 ctx 吗

**Comment by atian25** [comment]
const state = {};

**Comment by hubcarl** [comment]
没有多个ctx，和普通页面渲染流程是一样的。

**Comment by atian25** [comment]
- 我有点倾向于 locals 要单纯一点，本来它就是给渲染模板用的。
- 现在是 ctx, helper, request 这几个，感觉可以改为 defineProperty
- 还有一个就是 i18n 那边注入的 `__`，https://github.com/eggjs/egg-i18n/blob/master/app/middleware/i18n.js

会遇到的问题是，后者 assign 的时候会丢失，https://github.com/eggjs/egg/blob/master/app/extend/context.js#L163

**Comment by hubcarl** [comment]
目前render(file,locals) 原始的locals拿不到， https://github.com/eggjs/egg-view/blob/fb008fea94b3538a55efda5075dfc42116b0f129/lib/context_view.js#L56   这里可以把原始的locals 挂到 options上面，就不用关心SET_LOCALS, 有自定义插件处理INIT_STATE数据

**Comment by popomore** [comment]
现在要把概念弄清楚，前端需要的数据和 locals 不一样的，比如 nunjucks

```html
<script>
window.content = {{ content }};
</script>
```

服务端代码

```js
ctx.render('index.html', {
  // 这个数据是给前端用的，而整个 locals 是在 ssr 使用的
  context: JSON.stringify({}),
})
```

**Comment by atian25** [comment]
我理解，但我们从使用者的角度来看：

```
const data = await ctx.service.news.list();
// nunjucks
await ctx.render('index.tpl', data);
// vue
await ctx.render('index.vue', data);
```

在 SSR 的场景下，是用不到 helper, ctx 这些变量的。
我们期望用户是如我上面代码那样的使用，而不用记忆有什么特殊的 key。

**Comment by popomore** [comment]
这个不能一概而论，ssr 也需要服务端渲染的数据，可能现在的应用场景只是首屏，但从功能来说需要区分前端和后端的数据，而 `ctx.render` 这个 API 只是提供给后端渲染使用，前端数据只是作为后端渲染数据的一部分。

可以增加一个新 API，比如 `ctx.renderReact()`

**Comment by hubcarl** [comment]
无论ssr 与普通模板有一点区别就是 render 放到 data数据要输出到页面，关键就是这个数据怎么给到页面，哪些数据需要给到页面。一个典型的场景就是一个页面的render数据包括业务自有数据，中间件设置的一些变量，比如登陆状态／环境变量等，还有整个应用的公共信息。 其中 中间件设置信息(比如ctx.locals)和整个应用的公共信息(app.locals)希望框架统一处理，不用每个controller自己组装

**Comment by popomore** [comment]
ssr 渲染时，在服务端渲染使用的数据不会都展现出来，取决于模板。这里提到的数据是因为要给前端使用的，所以我希望区分这个前端使用的数据和 locals 本身。

如果插件实现时要保证其一致，那就新增 ctx 的 API 来统一处理，`ctx.render` 里的数据肯定会包含所有 ctx.locals 的数据，这个是 egg 本身的功能，无法保证框架和插件不插入。新 API 可以根据自己的逻辑来整合需要传入的数据，SSR 和纯后端渲染的模板还是有差异的。

**Comment by hubcarl** [comment]
可以先把原始的locals 暴露出来，插件自己决定是否合并相关上下文， @popomore 

目前render(file,locals) 原始的locals拿不到， https://github.com/eggjs/egg-view/blob/fb008fea94b3538a55efda5075dfc42116b0f129/lib/context_view.js#L56 这里可以把原始的locals 挂到 options上面，就不用关心SET_LOCALS, 有自定义插件自己决定是否组装新的locals(INIT_STATE)数据给到页面

**Comment by ImHype** [comment]
`SET_LOCALS 注入` 一些 `helper` 有点奇怪，明明是放给 `data` 的，一般模板都会有自己的 `helper` 注入方式，没必要统一当成 `data` 处理

**Comment by atian25** [comment]
@ImHype `locals` 本身就是用于模板渲染的，ejs，nunjucks 都没有 helper 的，只有 filter。这块的必要性也不好说，就简单理解为历史遗留问题吧。

**Comment by atian25** [comment]
用 `options.locals`
