### ISSUE TITLE
如何在app beforeStart 中调用service方法

### ISSUE THREAD

**Issue by ChenHaoNane** [eggjs/egg#1630]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

如何在app beforeStart 中调用service方法

**Comment by dead-horse** [comment]
参考[此处](https://eggjs.org/zh-cn/basics/objects.html#获取方式-2)的示例
