### ISSUE TITLE
怎么在 view 模板里获取 session 值？

### ISSUE THREAD

**Issue by rupertqin** [eggjs/egg#1632]
比如要做用户登录状态， 默认是取的 ctx.locals,  但是没法取 session 里的值

**Comment by atian25** [comment]
`{{ ctx.session.xx }}` 但建议是在 Controller 中取好放到 locals，不要放那么多逻辑在 tpl

**Comment by rupertqin** [comment]
@atian25 因为登录状态哪里都需要，所以我最好是做个中间件，并到 locals 吧？

**Comment by atian25** [comment]
都行，看你代码的组织方式，问题不大。

**Comment by rupertqin** [comment]
@atian25  有个方法了， 在最顶层的模板里加上  {% set user = ctx.session.user %}

**Comment by atian25** [comment]
我是不建议在模板里面做这些逻辑的事，在中间件做更好一点。
