### ISSUE TITLE
showcase for egg + antd pro

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1638]
https://preview.pro.ant.design

**Comment by chengnuo** [comment]
求egg + antd pro骨架

**Comment by popomore** [comment]
https://github.com/eggjs/egg-ant-design-pro

**Comment by muchengit** [comment]
为何我的启动失败？？
> egg-ant-design-pro@1.0.0 start D:\work\demo\egg-ant-design-pro
> egg-scripts start --daemon --title=egg-server-ant-design-pro --env prod

[egg-scripts] Starting egg application at D:\work\demo\egg-ant-design-pro
[egg-scripts] Run node D:\work\demo\egg-ant-design-pro\node_modules\_egg-scripts@2.5.1@egg-scripts\lib\start-cluster {"title":"egg-server-ant-design-pro","framework":"D:\\work\\demo\\egg-ant-design-pro\\node_modules\\egg","baseDir":"D:\\work\\demo\\egg-ant-design-pro"} --title=egg-server-ant-design-pro
[egg-scripts] Save log file to C:\Users\hzq\logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Start got error, see C:\Users\hzq\logs\master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-ant-design-pro@1.0.0 start: `egg-scripts start --daemon --title=egg-server-ant-design-pro --env prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-ant-design-pro@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hzq\AppData\Roaming\npm-cache\_logs\2018-03-28T08_41_17_959Z-debug.log
PS D:\work\demo\egg-ant-design-pro>

**Comment by atian25** [comment]
> Start got error, see C:\Users\hzq\logs\master-stderr.log

**Comment by popomore** [comment]
猜测没有 npm run build

**Comment by muchengit** [comment]
哦哦，我还以为是做的服务端渲染的...  怎么做服务端渲染？？？求指导

**Comment by atian25** [comment]
即使是可以服务端渲染，那也是要 build 的。

**Comment by muchengit** [comment]
build 报错
./app/assets/utils/utils.js
  Line 1:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 2:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 3:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 4:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-sty

**Comment by muchengit** [comment]
build  报错了
./app/assets/utils/utils.js
  Line 1:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 2:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 3:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 4:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-sty

**Comment by atian25** [comment]
这是你 git 的默认配置导致 clone 下来后自动转换换行了吧

**Comment by muchengit** [comment]
关键是我没有搜索到 CRLF

**Comment by atian25** [comment]
那是换行符。。。。
自己 google 吧。

http://blog.konghy.cn/2017/03/19/git-lf-or-crlf/

**Comment by popomore** [comment]
谁说 pro 支持 ssr
