### ISSUE TITLE
在controller层怎么实现登录成功后跳转？

### ISSUE THREAD

**Issue by yaotaiye** [eggjs/egg#1639]
就是想实现登录成功后，跳转到首页，为什么使用redirect，链接是跳了但是以接口的形式返回。
运行结果：
![ve5s kn f h qke3h2k2](https://user-images.githubusercontent.com/24998871/32592474-d534323e-c55e-11e7-98c4-d6e7f531a1cc.png)
接口处理：
![dwebu 0lk vx x9_11f](https://user-images.githubusercontent.com/24998871/32592584-5cf57eee-c55f-11e7-953c-c8db935ace97.png)
前端请求：
![gwyxd k z0nk t 5f7 p0rg](https://user-images.githubusercontent.com/24998871/32592780-4581bac4-c560-11e7-847b-317dace4ef59.png)

**Comment by popomore** [comment]
两个图一样

**Comment by yaotaiye** [comment]
图已修改， @popomore 。

**Comment by atian25** [comment]
没太看懂问题

**Comment by ZQun** [comment]
@yaotaiye 前端根据返回值来判断是否跳转，ajax请求后端返回跳转，前端当然不跳转了

**Comment by atian25** [comment]
额....  这属于 Web 开发的基础知识了，可以去了解下 HTTP 协议和 Ajax 这块的。

redirect 是一个 HTTP 302 跳转，如果你是用 ajax 请求的，就要自己处理，拿到 headers 里面的 location 后自己跳。
