### ISSUE TITLE
egg-mysql insert 报错

### ISSUE THREAD

**Issue by yanugto** [eggjs/egg#1640]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/7939959/32598230-2d81d846-c574-11e7-83f5-8acbbe805efa.png)
![image](https://user-images.githubusercontent.com/7939959/32598268-4ccb49f8-c574-11e7-8ddf-c19023dc00ee.png)

**Comment by 89790094** [comment]
'Unknown column **password** in field list'

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by fengmk2** [comment]
> Unknown column password in field list

错误提示已经很明显。
