### ISSUE TITLE
定时任务，怎么设置每天0点执行任务？

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1642]
* **Node Version**: 8.4
* **Egg Version**: latest
* **Platform**: mac os
* **Mini Showcase Repository**:

RT

**Comment by atian25** [comment]
看文档，cron

发自我的 iPhone

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/schedule.html#cron

**Comment by kylezhang** [comment]
cron: '0 0 0 * * *', // 每天凌晨1点执行任务
