### ISSUE TITLE
获取不到stream.fields ，图片正常上传成功的

### ISSUE THREAD

**Issue by liuguichi** [eggjs/egg#1643]
![image](https://user-images.githubusercontent.com/11871542/32641077-9523945e-c591-11e7-9af5-8f900d530e01.png)

======以下是请求信息
![image](https://user-images.githubusercontent.com/11871542/32641098-bcbce790-c591-11e7-8413-80ce268b3375.png)
======以下是依赖信息
 "dependencies": {
    "await-stream-ready": "^1.0.1",
    "egg": "^1.11.0",
    "egg-development-proxyworker": "^1.1.1",
    "egg-mysql": "^3.0.0",
    "egg-scripts": "^1.0.0",
    "egg-view-nunjucks": "^2.1.3",
    "stream-wormhole": "^1.0.3",
    "uuid": "^3.1.0"
  },

**Comment by dead-horse** [comment]
![image](https://user-images.githubusercontent.com/985607/32641310-c01818a0-c592-11e7-9269-fa93f529fb0a.png)

**Comment by liuguichi** [comment]
已经解决了
