### ISSUE TITLE
[egg-scripts] 启动时有 stderr 会失败

### ISSUE THREAD

**Issue by Azard** [eggjs/egg#1644]
* **Node Version**: 8.9
* **Egg Version**: 1.11.0
* **Plugin Name**: egg-scripts
* **Plugin Version**: 2.1.0
* **Platform**: Ubuntu 16.04
* **Mini Showcase Repository**:

我用 egg-mongoose 连接 MongoDB 3.6 时因为 auth 问题， egg-mongoose 会抛出一行无关紧要的 stderr 输出。
使用 `egg-bin dev` 或者直接 `node index.js` 启动 egg 是可以正常启动的。
但是 egg-scripts start 会因为 stderr 导致启动失败，master-stderr.log 里就是 egg-mongoose 的 stderr 输出。

建议加个 flag ignore stderr 会失败

```
[egg-scripts] Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[egg-scripts]
[egg-scripts] Start failed, see /root/logs/master-stderr.log
```

**Comment by atian25** [comment]
@popomore 看起来是太严格了?

**Comment by longxianlin** [comment]
egg-scripts start --env=test启动，接口访问报500错误

npm run dev，接口正常

哪个环节出了问题？

```
  "scripts": {
    "start": "egg-scripts start --env=test",
    "stop": "egg-scripts stop",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
```

**Comment by atian25** [comment]
@longxianlin 看错误日志，猜测是你的 config.keys 没配置，跟本 issue 没有关系。

**Comment by popomore** [comment]
加个参数吧，应用启动应该保证正常运行。

**Comment by atian25** [comment]
@popomore 

`egg-scripts start --check-status` 这样？默认 options 为 false，然后内部继承时默认打开。

checkStatus 那块判断参数，只检测超时，不检测日志。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-scripts/pull/17

**Comment by atian25** [comment]
最新版已经支持，`egg-scripts start --ignore-stderr` 即可

**Comment by 854770857** [comment]
@atian25 我加了--ignore-stderr但还是无法启动

**Comment by 854770857** [comment]
![Uploading 1.png…]()
![Uploading 2.png…]()
"start": "egg-scripts start --port 7201 --daemon --title=egg-server-citic-press-oms-api --ignore-stderr",

**Comment by atian25** [comment]
图片挂了

**Comment by 854770857** [comment]
@atian25 
图片无法上传这是错误记录
[egg-scripts] Wait Start: 298...
[egg-scripts] Wait Start: 299...
[egg-scripts] Wait Start: 300...
[egg-scripts] Start failed, 300s timeout
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! citic-press-oms-api@1.0.0 start: `egg-scripts start --port 7201 --daemon --title=egg-server-citic-press-oms-api --ignore-stderr`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the citic-press-oms-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yunpub/.npm/_logs/2020-04-13T09_08_52_378Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! citic-press-oms-api@1.0.0 release: `git reset --hard && git pull && npm install && npm run stop && npm run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the citic-press-oms-api@1.0.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yunpub/.npm/_logs/2020-04-13T09_08_52_391Z-debug.log



错误文件描述
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'release' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle citic-press-oms-api@1.0.0~prerelease: citic-press-oms-api@1.0.0
6 info lifecycle citic-press-oms-api@1.0.0~release: citic-press-oms-api@1.0.0
7 verbose lifecycle citic-press-oms-api@1.0.0~release: unsafe-perm in lifecycle true
8 verbose lifecycle citic-press-oms-api@1.0.0~release: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/web/citic-press-oms-api/node_modules/.bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/web/software/jdk1.8.0_101/bin:/home/yunpub/.local/bin:/home/yunpub/bin
9 verbose lifecycle citic-press-oms-api@1.0.0~release: CWD: /web/citic-press-oms-api
10 silly lifecycle citic-press-oms-api@1.0.0~release: Args: [ '-c',
10 silly lifecycle   'git reset --hard && git pull && npm install && npm run stop && npm run start' ]
11 silly lifecycle citic-press-oms-api@1.0.0~release: Returned: code: 1  signal: null
12 info lifecycle citic-press-oms-api@1.0.0~release: Failed to exec release script
13 verbose stack Error: citic-press-oms-api@1.0.0 release: `git reset --hard && git pull && npm install && npm run stop && npm run start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid citic-press-oms-api@1.0.0
15 verbose cwd /web/citic-press-oms-api
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "release"
18 verbose node v10.17.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error citic-press-oms-api@1.0.0 release: `git reset --hard && git pull && npm install && npm run stop && npm run start`
22 error Exit status 1
23 error Failed at the citic-press-oms-api@1.0.0 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by atian25** [comment]
[egg-scripts] Start failed, 300s timeout

你的某个插件启动超时，具体看 /home/admin/logs 那边的日志分析。还可以看 run/application_timing.json
