### ISSUE TITLE
querystring 参数被舍弃的问题

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1645]
node 文档: [](https://nodejs.org/dist/latest-v8.x/docs/api/querystring.html)

For example, the query string 'foo=bar&abc=xyz&abc=123' is parsed into:

{
  foo: 'bar',
  abc: ['xyz', '123']
}

但在 egg 里拿到的 是 {abc:'xyz'} 后面的参数被舍弃了, 请问有什么办法拿到数字形式的请求参数?

**Comment by linxuanwei** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/querystring.html

**Comment by atian25** [comment]
`ctx.queries`

**Comment by linxuanwei** [comment]
这个跟标准的不一样啊, ctx.queries 拿到的参数里全是数组
我希望的是这种:
 'foo=bar&abc=xyz&abc=123' 
{
foo: 'bar',
abc: ['xyz', '123']
}

**Comment by linxuanwei** [comment]
@atian25    我要在自己的 controller 逻辑里将这种 query 用 node 自带的querystring.parse()方法转一下?

**Comment by phper-chen** [comment]
都拿到了  自己转一下又不会掉块肉  框架毕竟不会帮你把项目全部做了

**Comment by dead-horse** [comment]
由于解析多层级的 querystring 存在被攻击的风险，而对于每一个 query 的值可能是 string 又可能是 array 容易导致业务逻辑在处理时忽略而导致报错（例如 `ctx.query.foo.slice()` 当 foo 是一个数组时会报错），所以 egg 默认处理为要么为 string，要么全为 array，且默认 `ctx.query` 只取一级。
