### ISSUE TITLE
请问使用了sessionRedis之后，我如何获取ssid呢

### ISSUE THREAD

**Issue by phper-chen** [eggjs/egg#1646]
比如 我在controller里面使用了this.ctx.session.id = '123213';   但是我想拿到ssid给手机端，我发现没有办法拿到，而在red is 里面则必须通过keys * 才能看到ssid，但没办法识别是哪一个用户的，也就是说sessionredis存session时是以ssid为key，id为value的方式来存的
是否有方法可以获取呢  
谢谢大佬们回复

**Comment by dead-horse** [comment]
ssid 是什么？可以描述的稍微清晰一点么

**Comment by phper-chen** [comment]
ssid就是sessionid  存到cookie里面的那个key

**Comment by phper-chen** [comment]
看源码里面使用的是koa-session  必须修改源码才能拿到externalKey  
把const CONTEXT_SESSION = Symbol('context#contextSession');
修改成
const CONTEXT_SESSION = Symbol.for('context#contextSession');
然后还得在egg app的controller最上面标上
const CONTEXT_SESSION = Symbol.for('context#contextSession');
通过this.ctx[CONTEXT_SESSION].externalKey才能拿得到ssid 
虽然是拿到了，但是修改了模块的源码，这样很不好，请问有其他办法拿到吗

**Comment by dead-horse** [comment]
为什么需要 ssid，这个应该是无感知的

**Comment by phper-chen** [comment]
因为我这边是接口服务，web和app都要重用这一套，jwt的方式被团队否决了，所以app那边需要ssid作为一个鉴权凭证，当然这个ssid会再进行处理的，但是koa-session直接是用symbol的方式把ssid隔离掉了

**Comment by dead-horse** [comment]
最终都会通过 set cookie 的方式通知客户端，web 和 app 有什么区别么？你在客户端通过解析响应的 cookie 就可以拿到 ssid 了，不需要自己再多设置一个值

**Comment by phper-chen** [comment]
呃 原来是这样啊，我也是第一次跟app client做交互，以为跟web 这样的bs不一样，谢谢你啊

**Comment by onweer** [comment]
@dead-horse 请问大神, 一个验证码功能 用户直接进入注册页面, 这个时候只有在cookies中只有EGG_SESS值, 这个值就是session id吧, 服务端拿不到这个值, 我想用这个值作为验证码的Key存在redis中, 用来校验验证码是否正确.  

还是说验证码就不应该存在redis中,直接放在cookies里面就好了? 服务端再验证cookies值是否正确就行了

**Comment by phper-chen** [comment]
> @dead-horse 请问大神, 一个验证码功能 用户直接进入注册页面, 这个时候只有在cookies中只有EGG_SESS值, 这个值就是session id吧, 服务端拿不到这个值, 我想用这个值作为验证码的Key存在redis中, 用来校验验证码是否正确.
> 
> 还是说验证码就不应该存在redis中,直接放在cookies里面就好了? 服务端再验证cookies值是否正确就行了

这就要自行修改这个模块的源码了，我们是修改了源码拿到的，不推荐
