### ISSUE TITLE
使用中间件后，ctx.status 是 404

### ISSUE THREAD

**Issue by musicode** [eggjs/egg#1647]
```
'use strict'
module.exports = options => {
  return async function notFound(ctx, next) {
    console.log('21')
    await next() // 执行流程已经走完了 controller
    console.log('22')
    if (ctx.status === 404) {
      // 每次都走进
      throw new Error('not found')
    }
  }
}
```

为啥走进了 controller，最后还是 404 呢

**Comment by musicode** [comment]
貌似跟中间件的顺序有关，如果是 `['errorHandler', 'notFound']`，会一直404，如果反过来就正常。

但我希望 404 能抛出异常，让第一个中间件来捕获，在第一个中间件统一处理成功和失败的返回格式

**Comment by musicode** [comment]
如果是 `['notFound', 'errorHandler']`，请求一个不存在的接口时，`ctx.status` 是 200

凌乱中...

**Comment by musicode** [comment]
@atian25 controller 不设置 `ctx.body` 是不是就是 404，我发现我设置了 body，就变成 200 了，这有点不合理啊，我希望在中间件定制 body 的格式该怎么实现呢

**Comment by dead-horse** [comment]
不设置 body 默认就是 404，要定制 body 在中间件中重新设置 body 即可。

```js
module.exports = () => {
  return async (ctx, next) => {
    await next();
    if (!ctx.body) return this.body = { success: false, state: 'not found' };
    this.body = { success: true, result: this.body };
  };
}
```

**Comment by musicode** [comment]
```js
module.exports = () => {
  return async (ctx, next) => {
    await next();
    // 这里怎么判断是走进了 controller 还是没匹配到路由呢？
    if (!ctx.body) return this.body = { success: false, state: 'not found' };
    this.body = { success: true, result: this.body };
  };
}
```

**Comment by musicode** [comment]
如果我在 controller 没对 body 做如何处理，而是把数据先放到 response 的某个自定义属性上，最后在中间件拼返回结构，按目前的设计似乎无法实现

**Comment by musicode** [comment]
@dead-horse 能告知怎么判断是走进了 controller 还是没匹配到路由吗

**Comment by atian25** [comment]
为什么不放到 body 呢?

**Comment by musicode** [comment]
我希望返回结构在中间件来拼装，也就是说，中间件是唯一操作 body 的地方，controller 只是做参数校验和数据操作，操作结构存入一个临时对象，比如叫做 `output`。伪码如下：

```js
// 数据格式化。顺便问一下，比如性别参数，get 参数传了 '1'，但我希望是数字 1，这里应该格式化吧，我没找到相关插件，还是说要自己写？
// 数据校验。比如可以用 egg-validate，校验失败抛异常
// 正常的业务逻辑
this.output.user = userService.getUserById('id');
```

接下来，我在中间件里面判断，如果有异常，就返回 code 为非零，如果一切正常，就把 code 设为 0，并把 output 加上。

但如果按我的想法，egg 似乎无法实现，我的理解对么

**Comment by musicode** [comment]
以前看过 koa 的源码，貌似是否操作 body 确实会影响 status，但按 MVC 的理解，404 取决于是否命中路由吧，命中了路由依然是 404 我实在是无法理解，把 koa 底层实现这样直接透传到 egg 业务层合理吗

**Comment by atian25** [comment]
如果你只是想做统一的 rpc 封装，那就把 egg 的 Controller 基类扩展了，提供一个类似 `rpc` 的接口，然后在 Controller 里面 `this.ctx.rpc(data)` 来返回即可，没必要一定要在中间件啊。

[X-Y PROBLEM](https://coolshell.cn/articles/10804.html)

**Comment by musicode** [comment]
也就是说，现在 controller 必须设置 body，如果不设置，在中间件只能当做 404 处理了是吧，但我比较好奇的是，难道从来没有人想在中间件判断是否命中路由吗

**Comment by popomore** [comment]
可以去 koa-router 问问

**Comment by atian25** [comment]
> 能告知怎么判断是走进了 controller 还是没匹配到路由吗

@musicode 你既然都设置 this.out 了，那你在 middleware 里面判断下不就行了。

Controller 也只是洋葱模型里面最中间的那个 middleware 而已，没什么特殊的。

如果你想知道有没有命中，那就看看 koa-router 源码吧。

就我们日常使用场景来说，很少会用到 middleware，都在 Service，Extend，Controller 等场景就抽象掉了。

https://eggjs.org/zh-cn/basics/controller.html#自定义-controller-基类

**Comment by musicode** [comment]
好的，顺便问一下，格式化参数的需求，比如字符串格式化成数字，内容 trim 之类的参数操作，egg 现在有官方插件吗

**Comment by atian25** [comment]
没有，有需要的话，自己封装一个回馈社区吧

**Comment by musicode** [comment]
[egg-filter](https://www.npmjs.com/package/egg-filter) 已贡献

**Comment by atian25** [comment]
@musicode 几个建议：

- 用 `egg-init --type=plugin` 来初始化插件
- 编写测试用例
- 仓库的 travis 等配置参见：https://github.com/eggjs/egg/wiki/How-to-create-a-new-repository
- 不一定需要用户手动 add 的，可以约定目录是 `app/extend/xx.js`，然后你用 loader 自动加载，参见 https://github.com/eggjs/egg-view-nunjucks/blob/master/lib/environment.js#L63
- 感觉你的这个功能，更像 Formatter 而不是 Filter

**Comment by musicode** [comment]
@atian25 egg 用的不熟，多谢建议。

第4条，我是参考 egg-validate 实现的...

最后一条，参考 vue 的 filters，我觉得格式化这种事叫做 filter 也无妨

**Comment by fengmk2** [comment]
> 但我比较好奇的是，难道从来没有人想在中间件判断是否命中路由吗

你在路由配置最后面加上一个兜底路由，就知道肯定是没有命中的了。

```js
app.all('*', async (ctx) => {
  ctx.body = 'wow, all miss';
});
```

**Comment by musicode** [comment]
@atian25 借用宝地再问一个问题，js 没有静态检查，前端开发无所谓，但是在服务器开发，任何环节都有可能出错，因此，方法的参数检查是有必要的，除了用 typescript，是否有更好的方法，我目前了解到的是用 `assert`。

**Comment by musicode** [comment]
@fengmk2 中间件里面目前我了解的可用解决方法是这样的

```js
if (ctx._matchedRoute) {
    // 命中路由
}
```

**Comment by fengmk2** [comment]
当然，koa-router 给出了一个 `ctx.matched` 属性，可以判断是否命中路由 https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L324

但是命中路由不代表不需要处理 404 问题，很可能 controller 发现不需要它处理，它自己 next 了交给全局 notfound 中间件来处理了。所以光光“判断是否命中路由”，不能作为 notfound 中间件判断是否需要它处理的依据。

**Comment by fengmk2** [comment]
@musicode `_matchedRoute` 看命名就知道 koa-router 并不想要大家这么使用。

**Comment by musicode** [comment]
@fengmk2 我只能说，是 koa-router 的作者在误导我，他在 README 只提到了 `_matchedRoute`，没提
 `matched`，我一看到有这功能，就没去看源码

**Comment by fengmk2** [comment]
@musicode 我上面已经修正了，是 `_matchedRoute`，不是 `matched`.

**Comment by musicode** [comment]
@fengmk2 方便了解下不用 ts，目前最好的函数参数检查的方式么

**Comment by atian25** [comment]
TS 是编译期代码检查，跟线上的参数检查是两回事，后者是处理用户输入。
