### ISSUE TITLE
一个controller如何调用另一个controller？

### ISSUE THREAD

**Issue by jiangchenguang** [eggjs/egg#1652]
开发团队你们好，有个问题想请教下。
### 需求是这样的
前端通过唯一字符串get用户信息；后端判断：如果存在对应的用户，则返回信息；否则返回一个绑定页面。
### 后端对应的router
`app.get('/wx/stu/stuBind', checkBindState, app.controller.userAdapter.getBindInfo);`
### 我的想法
在`checkBindState`中判断用户是否存在，并在`ctx.state`内置一个标记`needBind`；
`userAdapter.getBindInfo`中判断`needBind`，然后调用不同的controller处理。
### 存在的问题
好像不能在一个controller内调用其它的controller，调用代码如下：
```` javascript
module.exports = app => {
  class UserAdapter extends app.Controller {

    /**
     * 处理获取用户绑定信息
     * @return {Promise.<void>}
     */
    async getBindInfo() {
      let {ctx, app} = this;
      let {state, originalUrl} = ctx;
      if (state.needBind) {
        // 需要先绑定
        if (originalUrl.indexOf('stuBind') > 0)
          await app.controller.student.stuBind();  // 这一步不会进入stuBind函数！！
      } else {
        // 返回用户信息
      }
    }
  }

  return UserAdapter;
}
````
请教大神，是否是语法有错误？还是不可以这样，那么该如何实现呢？谢谢。

**Comment by dead-horse** [comment]
请将通用逻辑抽象到 service 中。 https://eggjs.org/zh-cn/basics/service.html

**Comment by jiangchenguang** [comment]
@dead-horse 好了，多谢。

**Comment by oneyoung19** [comment]
> 请将通用逻辑抽象到 service 中。 https://eggjs.org/zh-cn/basics/service.html

Thanks a lot!
