### ISSUE TITLE
egg-lru plugin base on hashlru

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#166]
https://github.com/dominictarr/hashlru

**Comment by fengmk2** [comment]
lru can replace dnscache in urllib https://github.com/eggjs/egg/blob/master/lib/core/dnscache_httpclient.js#L73

**Comment by fengmk2** [comment]
start

**Comment by fengmk2** [comment]
https://github.com/node-modules/ylru

**Comment by atian25** [comment]
fork 啊, 对方不愿意 PR ?

**Comment by fengmk2** [comment]
@atian25 不是，我们需要扩展功能，而且还要写完整的测试。

**Comment by popomore** [comment]
这个还要写插件？
