### ISSUE TITLE
求一个egg-graphql完整的开发实例

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1664]
* **Node Version**:v9.1.0
* **Egg Version**:1.11.0
* **Plugin Name**:egg-graphql 
* **Plugin Version**:1.0.0
* **Platform**:CentOS
* **Mini Showcase Repository**:

最好是用到egg-mongoose这个插件去操作数据库的

**Comment by jtyjty99999** [comment]
https://github.com/freebyron/egg-graphql-boilerplate  可以参考这个，是使用egg-sequelize的
