### ISSUE TITLE
egg@1.11.0在router.js里面使用app.options会报错

### ISSUE THREAD

**Issue by leegang2017** [eggjs/egg#1665]
egg@1.11.0在router.js里面使用app.options会报错
router.js如下
app.options('/', app.controller.home.index);

启动会报下面的错
/media/sutdy/workspaces/node/egg-example/node_modules/egg/lib/application.js:39
      throw e;
      ^
TypeError: app.options is not a function
    at module.exports.app (/media/sutdy/workspaces/node/egg-example/app/router.js:5:7)

**Comment by popomore** [comment]
可以用 app.router.options
