### ISSUE TITLE
怎么去掉egg自带的日志系统？

### ISSUE THREAD

**Issue by SunGg12138** [eggjs/egg#1667]
怎么去掉egg自带的日志系统？

**Comment by popomore** [comment]
`config.logger.level = 'NONE'` and  `config.logger.consoleLevel = 'NONE'`

**Comment by fengmk2** [comment]
这样会导致异常日志全部丢失。

**Comment by atian25** [comment]
为什么需要去掉自带日志？

**Comment by wenlittleoil** [comment]
> 需要去掉自带日志？

自己引入winston来搭日志系统

**Comment by atian25** [comment]
可是为什么呢
