### ISSUE TITLE
使用egg-socket.io插件后所用中间件方法不能改写为async吗？

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1669]
* **Node Version**:v9.1.0
* **Egg Version**:1.11.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:3.0.0
* **Platform**:MacOS
* **Mini Showcase Repository**:

```
module.exports = (options, app) => {
  return async function check(ctx, next) {
    this.socket.emit('res', 'auth!' + say);
    await next();
    console.log('disconnect!');
  };
};
```
错误提示：check must be generatorFunction!，求解

**Comment by atian25** [comment]
欢迎 PR 支持下，wrap 下即可。

**Comment by atian25** [comment]
类似 @solarhell 之前的 https://github.com/eggjs/egg-socket.io/pull/20/files

**Comment by linxuanwei** [comment]
@PeterRao  @solarhell    
 egg 2.0 已经要求 node >= 8 了, 希望支持下 async/await

**Comment by solarhell** [comment]
@atian25 有一个问题 [egg-socket.io](https://github.com/eggjs/egg-socket.io) 这个的最低版本是多少？

**Comment by atian25** [comment]
如果可以不 break 的话，尽量在 egg-socket.io@3.x  支持。

**Comment by atian25** [comment]
egg2 和 egg1 基本上是无痛升级的，只是因为插件很多都要改为 async first，所以才会发 break 版，但这些插件的新版本在 egg1 还是一样能使用的，只要使用者的 node >8

**Comment by solarhell** [comment]
我的疑问就是plugin的源代码可以用async吗 在这个情况下 如果我用了async 老用户的node如果不支持就算breaking了吧？

发自我的 iPhone

**Comment by atian25** [comment]
不能，插件只能 generator

发自我的 iPhone

**Comment by atian25** [comment]
@ngot egg-socket.io@4 支持了么?

**Comment by ngot** [comment]
已经支持了。升级到 4.0 即可。
