### ISSUE TITLE
egg-sequelize在框架中定义的Model继承的问题

### ISSUE THREAD

**Issue by raininfall** [eggjs/egg#1670]
* **Node Version**: v8.9.0
* **Egg Version**: 1.11.0
* **Plugin Name**:egg-sequelize
* **Plugin Version**: 3.1.0
* **Platform**: OSX
* **Mini Showcase Repository**:

在集成框架的时候，在框架的app/model找那个定义的Model不能被继承。
这个问题应该和https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L48  有关，egg-sequelize只会加载app.baseDir下的app/model。
这个问题应该在egg-sequelize中解决还是自己写个loader？

**Comment by huacnlee** [comment]
没看懂，你是要做什么事情？

**Comment by huacnlee** [comment]
````
const eggSequelize = require('egg-sequelize/lib/loader');

module.exports = app => {
  app.beforeStart(function* () {
  });
}

**Comment by atian25** [comment]
看 https://github.com/eggjs/egg-sequelize/pull/32 的话，应该是想支持加载 plugin 里面定义的 model 文件。

**Comment by dead-horse** [comment]
不支持框架层定义 model
