### ISSUE TITLE
egg-socket.io的cluster模式

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#1671]
Node Version: v8.9.0
Egg Version: 1.10.0
Plugin Name:egg-socket.io
Plugin Version: 3.0.0
Platform: OSX
Mini Showcase Repository:

```js
 startCluster({
      sticky: true,
      baseDir: __dirname,
      port: 7001
      workers: 8
    });
```

  请问设置  sticky: true  后,  是否意味着只有一个worker进程启动了socket监听 ?

  如何实现socket.io多进程负载均衡 ?

**Comment by ngot** [comment]
cluster(集群) 模式就是多个worker都在监听。如果只有一个worker监听，那就不是cluster了。

由于 socket.io 本身的限制，无法做 RR 模式的负载，只能把单个用户连接固定到某个 worker ，所以对于 socket.io 场景，谈多进程负载均衡是一个伪命题，不存在均衡这个说法。

目前 egg-socket.io 是根据用户的 IP 地址，来hash固定worker的。可以一定程度上(虽然不似乎很平均)保证负载的均匀分布。

对于所有长连接型的服务，从不应该从程序本身来谈负载均衡。真的关注这个问题的话，需要在业务架构上单独去做一个连接层服务，专门来做连接和负载。
