### ISSUE TITLE
在应用启动后，读取 mysql 数据存到 redis

### ISSUE THREAD

**Issue by rupertqin** [eggjs/egg#1673]
在应用启动后，读取 mysql 数据存到 redis，一般怎么做？
在 beforeStart 里做的话， mysql 还没启动呢。

**Comment by rupertqin** [comment]
懂了

**Comment by solarhell** [comment]
问题解决完 可以把自己的解决方案贴出来 谢谢

**Comment by tong3jie** [comment]
@rupertqin  同问？手动启动定时任务吗？

**Comment by rupertqin** [comment]
@tong3jie  在 app.js  这个文件里操作就行了，这里默认就是连接数据库之后应用启动之前

**Comment by tong3jie** [comment]
@rupertqin  我是想在应用全部启动之后自动执行一个任务。

**Comment by tong3jie** [comment]
知道了，有个app.ready函数。
