### ISSUE TITLE
扩展app对象的属性，在docker 部署下运行出问题

### ISSUE THREAD

**Issue by yourlei** [eggjs/egg#1674]
* **Node Version**:　6.11.3
* **Egg Version**: 1.10.0
* **Plugin Name**:  egg-scripts
* **Plugin Version**:
* **Platform**: ubuntu 16.04
* **Mini Showcase Repository**:

情况是这样，在*app/extend/application.js*下添加了 *report*属性（如下代码）

``` js
'use strict'

const REPORT = Symbol('Application#report');
module.exports = {
  get report() {
    if (!this[REPORT]) {
        this[REPORT] = new Map();
    }
    return this[REPORT];
  }
};
```

在本地开发环境，*npm run dev* 或 *npm start* 方式运行都没有问题，能够正常的 **get** , **set** report属性值，然而通过docker 方式部署后，只有在 *npm run dev*的运行方式才能正常的**get** , **set** report属性;

测试了docker 部署下*npm start* 运行时*set* report属性值是可以的，但再去*get*值的时候啥的没有，返回了空对象，容器里node 的版本是 *6.11.2*

附上*package.js*中**script**

``` js
  "scripts": {
    "start": "egg-scripts start --daemon",
    "stop": "egg-scripts stop",
    "dev": "egg-bin dev -p 7001"
}
```
不知道是啥原因引起这个问题, 望大神解答, 谢谢.

**Comment by popomore** [comment]
去掉 daemon 看看

**Comment by yourlei** [comment]
去掉 *daemon*也不行，*get*, *set*操作都是写在*controller*层, 对**app.report**属性进行*get* ,* set*操作的代码大概是这样
* **report.js** 用于同步报告数据至 *app.report*属性
``` js
module.exports = app => {
  class ReportController extends app.Controller {
      * led() {
           const {
              ctx
            } = this;
          let { query, token } = ctx.query;
          const { id } = app.jwt.verify(token, app.config.jwt.secret);
          // 省略部分代码
         // .......

           // 报告数据
           const cache = {
              catalog: nums,
              title: title ? title : '中国LED行业专利分析及预警报告',
              to: reportDate,
              catalog: nums,
              html: "'" + html + "'"
            }
            // 同步至cache
            const reportCache = app.report.get(id) || {};
            app.report.set(id, {
               led: cache,
              ngit: reportCache.hasOwnProperty('ngit') ? reportCache.ngit : null
          });
          console.log(app.report.get(id), 'html') // 这一步能够正常输出set设置的属性值
       }
   }
}
```
* **docx.js** 验证*app.report*下对应的 *id*是否有value值(缓存的报告数据)

``` js
module.exports = app => {
  class DocxController extends app.Controller {
      * checkStatus() {
	const {
		ctx
	} = this;
	let industry = ctx.params.name;
	let header = ctx.request.header;
	let token = header['x-user-token'];
	const { id } = app.jwt.verify(token, app.config.jwt.secret);
	const cache = app.report.get(id) || {};
	const rules = ['led', 'ngit'];

	console.log(cache, '验证缓存中的报告'); // 输出 {},没有获取到设置的属性值
         // 省略部分代码
        // ......
       }
     }
}
```

这里还有个问题，用*npm run dev* 和 *npm start*两种方式运行，对于加载 *application*对象下的扩展属性有没什么不同

**Comment by popomore** [comment]
提供下完整 demo

**Comment by StephenSeraph** [comment]
我前前后后写过大概十几个egg服务了，全都部署在docker下，完全没有问题。
docker服务是不能全部后台运行的，所以`daemon`是要去掉的。另外，我还遇到过一些跟docker有关的是node镜像，有些库不能跑在`alpine`版本的镜像下的，除此之外基本上都是代码本身的问题。
你可以在set之后、get之前都打上断点看看，这个report是不是同一个东西。扩展app建立一个全局Map的做法，我也用过，没遇到过啥问题

**Comment by atian25** [comment]
close due to no response, need more information, feel free to reopen if provided.

**Comment by Julyyq** [comment]
我没有用docker，但是也遇到了在生产环境部署get有时候为空的情况，大概get 10次只有1次会返回正确值的情况。本地怎么都是正常的。

**Comment by atian25** [comment]
@Julyyq 从上面的测试代码是看不出问题的，除非是你们做了什么特殊的操作，然后在 prod 模式下，多进程下，在 A 进程 set，在 B 进程拿肯定是空。

**Comment by Julyyq** [comment]
@atian25 谢谢，我设置workers为1就正常了，我再找找业务逻辑哪里有问题。
