### ISSUE TITLE
egg-sequlize doesn't support multi-layer model file

### ISSUE THREAD

**Issue by leaves4j** [eggjs/egg#1675]
* **Node Version**: 8.9.0
* **Egg Version**: 1.11.0
* **Plugin Name**: egg-sequlize
* **Plugin Version**: 3.1.0
* **Platform**:
* **Mini Showcase Repository**:

`egg-sequelize` can not load files like `app/model/xxx/user.js`
[https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L59](https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L59)
Is it a deliberate or a bug？

**Comment by atian25** [comment]
it's not support yet

**Comment by dead-horse** [comment]
已支持
