### ISSUE TITLE
在使用egg-socket.io插件时有关this.socket.id的取值问题

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1676]
* **Node Version**:v9.1.0
* **Egg Version**:1.11.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:3.0.0
* **Platform**:MacOS X
* **Mini Showcase Repository**:

**Controller 类：**

```
module.exports = app => {
    class Controller extends app.Controller {
        * index() {
            console.log(this.socket.id);
        }
    }
    return Controller;
};
```
**error**: [egg-socket.io] controller execute error: Cannot read property 'id' of undefined
附官方Demo:[https://github.com/eggjs/egg-socket.io/blob/master/example/app/io/controller/chat.js](url)

**Controller 方法**：

```
module.exports = () => {
    return function* () {
        const clientId = this.socket.id;
       console.log(clientId);
    };
};
```
则可以拿到clientId的值，求解？？？

**Comment by solarhell** [comment]
用了class的写法 需要这样用 `this.ctx.socket.id`

**Comment by atian25** [comment]
class 方式是 this.ctx.socket，可以再看看文档去

https://eggjs.org/zh-cn/basics/objects.html

**Comment by 89790094** [comment]
一时疏忽了，谢谢〜〜
