### ISSUE TITLE
请问怎么自己定义egg启动创建的线程数量?

### ISSUE THREAD

**Issue by newcomein** [eggjs/egg#1678]
* **Node Version**:9.1
* **Egg Version**:1.11
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
--workers=2

发自我的 iPhone

**Comment by atian25** [comment]
看下 egg-bin 和 egg-scripts 的 help 或 README

**Comment by tong3jie** [comment]
@atian25 可以多于CPU的核数吗？

**Comment by atian25** [comment]
可以随意指定，默认值是我们的经验值
