### ISSUE TITLE
尝试使用 jest

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#1680]
如果使用 jest，前后端就可以一套测试工具了，先记录问题

## 待确认

- [ ] power-assert 好像不能用
- [ ] 多进程覆盖率

**Comment by dead-horse** [comment]
power-assert 好像不能用了

**Comment by okoala** [comment]
https://github.com/power-assert-js/power-assert/issues/93
我看到这条 issue，貌似有人已经在用了 power-assert + jest 了

**Comment by Godi13** [comment]
@dead-horse 需要配合 [babel-preset-power-assert](https://github.com/power-assert-js/babel-preset-power-assert) 配置下 .babelrc

**Comment by wangxuepeng** [comment]
Eggjs is great, if Jest can be used in tests, it'll become awesome!

**Comment by popomore** [comment]
@whxaxes 是不是可以关了

**Comment by whxaxes** [comment]
@popomore  可以了，我关掉

**Comment by AsserHong** [comment]
请问下这个issue关闭了，最后的结论是支持jest了吗？
