### ISSUE TITLE
能否官方的文档中补全对graphql的操作

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1681]
graphql我在部署docker的时候会出现下面的错误
```
Query.projects defined in resolvers, but not in schema
```
然后进程就进入重复死亡  重启 死亡... 的状态了。
egg对于的`graphql`的`plugin`只有一个test 没有一个完整的demo，恳请官网说明对graphql的使用，以及出现上面错误的原因，谢谢了

**Comment by duckywang1** [comment]
例子: https://github.com/freebyron/egg-graphql-boilerplate 可以参考这个，是使用egg-sequelize的

GraphQL 中:
`Schema`相当于定义，`resolver`相当于实现。这个错误告诉你，你缺乏了 Schema 定义。

**Comment by jtyjty99999** [comment]
https://zhuanlan.zhihu.com/p/30604868  我把这些文档都补充到仓库里

**Comment by zoulux** [comment]
@jtyjty99999  谢谢文档，第二个问题那个错误 ` Query.projects defined in resolvers, but not in schema` 是怎么回事

**Comment by jtyjty99999** [comment]
最好贴下代码，字面意思就是你的某个query并没有在schema中定义， 导致resolver跟 schema无法关联了
