### ISSUE TITLE
session优化问题

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1685]
* **Node Version**:  v8.8.0
* **Egg Version**: 1.9.0
* **Plugin Name**: egg-session
* **Plugin Version**:5.5.1
* **Platform**: macOS
* **Mini Showcase Repository**:配合"egg-redis": "^1.0.2"

#### 问题起因:
按照官方文档session持久化的设置添加middleware/save_session.js 
每次请求登录，每个请求都会设置前端的session,觉得这种处理方式不优雅；
期望前端设置的expries/max-age为Session；  
后台egg里面的redis里面存储
maxAge = 24 * 60 * 60 * 1000
每次请求前端不设置cookie,只重置redis的maxAge时间；
然后修改下面代码；
app/config/config.default.js
设置
```javascript
config.session = {
    key: 'SESSION_ID',
    maxAge: 'session', // 前端为当前会话有效
    httpOnly: true,
    encrypt: true
  };
```
发现报错，redismaxAge不能为'session',修复如下(app.sessionStore.set)：
```javascript
  app.sessionStore = {
    async get(key) {
      const res = await app.redis.get(key);
      if (!res) return null;
      return JSON.parse(res);
    },

    async set(key, value, maxAge) {
      // maxAge not present means session cookies
      // we can't exactly know the maxAge and just set an appropriate value like one day
      if (!maxAge || maxAge === 'session') maxAge = 24 * 60 * 60 * 1000;
      value = JSON.stringify(value);
      await app.redis.set(key, value, 'PX', maxAge);
    },

    async destroy(key) {
      await app.redis.del(key);
    }
  };
};
```
但是下次请求无改变session的时候<code>middleware/save_session.js</code>
里面的<code>ctx.session.populated</code>为<code>true</code>,是没问题的；
然后执行
```javascript
ctx.session.save();
```
前端又设置了一模一样的SESSION_ID，无法避免前端不设置，只更新后台redis的maxAge;

希望提供解决方案
初步探测：node_modules/koa-session/lib/context.js
```javascript
    // save to external store
    if (externalKey) {
      debug('save %j to external key %s', json, externalKey);
      yield this.store.set(externalKey, json, maxAge, {
        changed,
        rolling: opts.rolling,
      });
      this.ctx.cookies.set(key, externalKey, opts);
      return;
    }
```
这里的this.ctx.cookies.set(key, json, opts);的原因，希望综合
ctx.session.populated是否为ture、maxAge是否为'session'等请求判断是否给前端设置cookies？

**Comment by dead-horse** [comment]
你不应该手动执行 `ctx.session.save();`，如果 session 未发生变化，是不会更新 cookie 的。

**Comment by chenyulun** [comment]
你们给的方案是[手动调用ctx.session.save()](https://eggjs.org/zh-cn/core/cookie-and-session.html)最后一段；
比如用户登录有效时间为15分钟，5分钟有未改变session的请求，是不是应该重新计算他的登录有效时间15分钟，这时候用户前端用的是<code>expries/max-age:Session</code>;
只能更新redis的有效时间吧？
如果不手动执行的话，我怎么更新我后台的session有效时间？

**Comment by tears743** [comment]
不如用refreshToken机制，这样就无需更新session时间，而且session时间原则上不应改变
