### ISSUE TITLE
请问egg怎么整webpack-dev-middleware

### ISSUE THREAD

**Issue by tommy2z** [eggjs/egg#169]
谢谢！

**Comment by popomore** [comment]
内部有一个插件还未放出，稍后会开源出来。

实现原理是在 agent worker 启动一个 server 使用 webpack-dev-middleware，然后发消息给 app worker 告知静态文件的 host 和 port，在页面上使用这个地址。

**Comment by gxcsoccer** [comment]
egg-react

**Comment by popomore** [comment]
egg-react 还没有这个功能

**Comment by tommy2z** [comment]
egg-react 这个项目还未放出？

**Comment by atian25** [comment]
@geekdada 后续关注下这个, 看看怎么把内网那个版本开源出来

**Comment by xjchenhao** [comment]
@popomore @atian25  这个插件现在有了吗？

**Comment by dead-horse** [comment]
ping @geekdada

**Comment by atian25** [comment]
@dead-horse 昨天我们 UC 这边有讨论了，这个月他们会出一个插件。

**Comment by iyuq** [comment]
我写过一个基于koa2的[webpack-koa2-middleware](https://github.com/iyuq/webpack-koa2-middleware)

**Comment by mmzhi** [comment]
@atian25 说好的插件呢？

**Comment by hubcarl** [comment]
@mmzhi  https://github.com/hubcarl/egg-webpack

**Comment by hubcarl** [comment]
- egg + vue + webpack server side render: https://github.com/hubcarl/egg-vue-webpack-boilerplate
- egg + react + webpack server side render: https://github.com/hubcarl/egg-react-webpack-boilerplate

**Comment by mmzhi** [comment]
@hubcarl 66666，我参考一下

**Comment by zwmmm** [comment]
@atian25 插件开源了么?

**Comment by atian25** [comment]
上面 easywebpack 那些就可以了
