### ISSUE TITLE
框架可以自定义扩展一个目录下的文件加载到ctx对象或者 app对象吗？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#1694]
例如扩展一个api目录
 app
  ├─ api
   |   ├── test.js
  ├─ service
  ├─ middleware
  └─ router.js
── config
    ├── config.default.js
app.js
`

use strict';
const path = require('path');
module.exports = app => {
  // 获取所有的 loadUnit
  const servicePaths = app.loader.getLoadUnits().map(unit => {
    return path.join(unit.path, 'app/api');
  });
  console.log(servicePaths);
  app.loader.loadToContext(servicePaths, 'api', {
    // service 需要继承 app.Service，所以要拿到 app 参数
    // 设置 call 在加载时会调用函数返回 UserService
    call: true,
    // 将文件加载到 app.serviceClasses
    fieldClass: 'serviceClasses:',
  });
}

`
按照官网例子，无法扩展成功，请指导下，要如何配置才能扩展实现ctx.api.test的调用？

**Comment by atian25** [comment]
提供最小可复现仓库。

另外，怎么个无法扩展呢？

fieldClass 改掉，别覆盖 service。

**Comment by a526672351** [comment]
刚按照你说的优化下可以扩展到了，谢谢

**Comment by atian25** [comment]
建议学会 markdown 的 code 格式化，正文看起来很难阅读。

另，如果问题解决了，尽量回复下具体的方案和代码，方便后来者
