### ISSUE TITLE
egg-scripts报错

### ISSUE THREAD

**Issue by David2685** [eggjs/egg#1696]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

报错信息：

[egg-scripts] Run node /Users/David/eggTest/node_modules/egg-scripts/lib/start-cluster {"port":7776,"title":"lq-middle","timeout":300000,"framework":"/Users/David/eggTest/node_modules/egg","stdout":"/Users/David/logs/master-stdout.log","stderr":"/Users/David/logs/master-stderr.log","baseDir":"/Users/David/eggTest
 "} --title=egg-test
[egg-scripts] Save log file to /Users/David/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
/Users/David/eggTest/node_modules/egg-scripts/lib/cmd/start.js:150
          this.logger.info('%s started on %s', this.frameworkName, msg.data.address);
                                                                           ^

TypeError: Cannot read property 'address' of undefined
    at ChildProcess.child.on.msg (/Users/David/eggTest/node_modules/egg-scripts/lib/cmd/start.js:150:76)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

打印 msg 得到
{"action":"egg-ready","to":"parent","from":"master"}
没有data属性

**Comment by atian25** [comment]
不要锁版本，删除你的 node_modules 然后重新安装下依赖。
