### ISSUE TITLE
请问如何在egg中使用apns等推送呢

### ISSUE THREAD

**Issue by phper-chen** [eggjs/egg#1699]
我是半路跑去做nodejs的php程序员，想请教下egg中怎么使用apns这样的苹果推送呢
看了下其他框架的案例都是直接引入包，egg中如何做呢?agent里面做手脚？

**Comment by phper-chen** [comment]
谢谢你的回复 再请教下  挂载是在哪个文件里做呢  egg还是比较严格的  感觉一些包需要包装成egg形式的插件  可没时间去搞呢

**Comment by atian25** [comment]
看你的场景，我对 apn 不熟，简单看了那个库，应该只需要在 `app.js` 里面实例化下就好了。

egg 是渐进式的，不一定要一步到位封装为插件的，可以看下 https://eggjs.org/zh-cn/tutorials/progressive.html

**Comment by phper-chen** [comment]
主要是跟egg中的mqtt交互  需要实时获得mqtt推来的数据然后再推到可能有点乱  谢谢回复呃～

**Comment by orangebook** [comment]
@phper-chen 我也在做这个，之前是纯mosca实现的mqtt-server,现在想集成到egg.可以交流一下你的经验么
