### ISSUE TITLE
在 Master 启动的时候探测一个未被占用的 port 传递给 app/agent

### ISSUE THREAD

**Issue by gxcsoccer** [eggjs/egg#170]
- [x] 为了必要一台机器跑多个 egg 程序，导致 cluster 模式的端口冲突，需要在 Master 启动的时候探测一个未被占用的 port 传递给 app/agent
- [x] egg-mock 在 mm.app 的时候也要支持传递一个 port 给 cluster

**Comment by popomore** [comment]
egg-mock 也要支持？

**Comment by popomore** [comment]
@gxcsoccer mm.app 怎么做的，因为 agent 和 app 在同一个进程里

**Comment by popomore** [comment]
要不 cluster-client 处理下？mm.app 是同步的，也不太好处理。

**Comment by atian25** [comment]
这事在 egg-script  做就好了吧？

**Comment by popomore** [comment]
这个之后改好了，和 egg 本身没关系，涉及到 cluster-client 的测试会影响。
