### ISSUE TITLE
扩展schedule时，自定义的scheduleStrategy里 schedule 提示未定义？

### ISSUE THREAD

**Issue by sunguide** [eggjs/egg#1701]
* **Node Version**: 8.1.1
* **Egg Version**:1.11.0
* **Plugin Name**:egg
* **Plugin Version**:
* **Platform**:windows
* **Mini Showcase Repository**:
伪代码中  schedule 提示未定义；
`module.exports = agent => {

  class ClusterStrategy extends agent.ScheduleStrategy {

    start() {

      // 订阅其他的分布式调度服务发送的消息，收到消息后让一个进程执行定时任务
      // 用户在定时任务的 schedule 配置中来配置分布式调度的场景（scene）

      agent.mq.subscribe(schedule.scene, () => this.sendOne());

    }
  }
  agent.schedule.use('cluster', ClusterStrategy);
};`

**Comment by popomore** [comment]
因为是伪代码

**Comment by sunguide** [comment]
请使用 

this.schedule.scene

**Comment by atian25** [comment]
可以 PR 下
