### ISSUE TITLE
关于vue+egg的csrf问题

### ISSUE THREAD

**Issue by yangzichen987046** [eggjs/egg#1707]
是不是因为域不相同，所以只能把csrf关掉

**Comment by atian25** [comment]
所以你在问什么？

**Comment by solarhell** [comment]
不是 可以忽略JSON格式的请求
参考 https://eggjs.org/zh-cn/core/security.html#忽略-json-请求

**Comment by solarhell** [comment]
另外如果用`axios`需要注意请求头 参考 https://github.com/eggjs/egg/issues/1439#issuecomment-330410683

**Comment by yangzichen987046** [comment]
@atian25 我遇到问题是这样的：一开始页面是没有cookie的
![qq 20171123172921](https://user-images.githubusercontent.com/18715050/33166112-11ee1224-d074-11e7-89a6-dca344061804.png)；
然后我发起一个请求：
![qq 20171123173209](https://user-images.githubusercontent.com/18715050/33166164-4120fed0-d074-11e7-9e41-2b111a595e78.png)
失败了，但这时页面上有了cookie
![qq 20171123174009](https://user-images.githubusercontent.com/18715050/33166570-ac60d0ca-d075-11e7-830a-e1ec227ca3d6.png)
之后的请求就都ok了，
那一开始没有cookie的时候怎么解决啊

**Comment by atian25** [comment]
这种挤牙膏似的提问效率很低，请提供清晰的复现步骤。

**Comment by dead-horse** [comment]
csrf 校验是需要先访问页面，拿到 token 的，所以不是给 API 来校验的。
