### ISSUE TITLE
关于csrf 防刷问题疑惑

### ISSUE THREAD

**Issue by xiaotan0305** [eggjs/egg#1708]
* **Node Version**: 8.9.0
* **Egg Version**: 2.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

背景: 有个需求,进入页面填写信息,发送ajax请求(jquery的ajax请求,非form表单)提交,提交后要求在不刷新页面的情况下,不允许再次提交,请问我怎么配置csrf?
我的配置无法满足需求,每次请求后能够连续发送ajax请求.
![image](https://user-images.githubusercontent.com/12965330/33171811-af7c08d4-d088-11e7-9449-f0fb1c332fec.png)
ajax请求后,cookie中token 一直有效,所以在不刷新页面的情况下可以无限次点击按钮发送请求,起不到限制作用.
尝试1: 我尝试请求成功后删除cookie中的csrfToken,下次请求会返回403,但是会再次生成新的csrfToken,再次提交能提交,没有达到不刷新页面不能再次提交的限制作用
尝试2: 刷新页面生成csrfToken后,手动修改csrfToken的值,仍能成功提交,不清楚后台怎么做对比校验
尝试3: 我尝试把csrf配置中useSession设为true,然后无论如何都不能提交了,请问如果把useSession设为true后,前端ajax请求该如何操作?
前端代码如下:
![image](https://user-images.githubusercontent.com/12965330/33172121-c07563a0-d089-11e7-946a-b5c05ba3899e.png)

**Comment by Suixinlei** [comment]
security插件应该无法满足幂等操作的场景吧,egg的csrf token是为了防止跨域的。

**Comment by dead-horse** [comment]
如 @Suixinlei 所说，需要找其他的解决方案，例如通过幂等 id 等来实现，具体方案需要自行探索。

**Comment by xiaotan0305** [comment]
尝试1已经通过其他方案解决;
但尝试2总:"我尝试把csrf配置中useSession设为true,然后无论如何都不能提交了,请问如果把useSession设为true后,前端ajax请求该如何操作?" 哪位大神帮忙解决下.

**Comment by crazyjingling** [comment]
@xiaotan0305 请问尝试1是怎么解决的？
