### ISSUE TITLE
use strict 下函数中this的指向问题

### ISSUE THREAD

**Issue by Lin-shurui** [eggjs/egg#1710]
egg框架中，使用use strict模式，使用npm run dev运行系统时报错，错误定位：在函数fun中使用this.a = 'text'，this 为undefined。不过在外部调用这个函数时使用new, 按理说fun中this应该指向这个对象，不应该为undefined，望指点！不在egg中正常

**Comment by atian25** [comment]
提供最小可复现代码库

**Comment by Lin-shurui** [comment]
已上传代码库egg-example.zip。
拷贝项目后请先npm install 安装包
实例代码在app/service/tool下，直接node test 运行正常。
使用npm run dev无法正常启动，报TypeError错误，this undefined
使用的node版本8.1.0，npm 版本5.3.0
希望得到解答，谢谢！
[egg-example.zip](https://github.com/eggjs/egg/files/1500541/egg-example.zip)

**Comment by atian25** [comment]
直接提交到你的 github 即可。。。

发自我的 iPhone

**Comment by Lin-shurui** [comment]
我第一次使用github交流，还不太熟悉。
目前这样的方式无法满足吗？望指点

**Comment by Lin-shurui** [comment]
我还是github的小菜鸟，多包涵...

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/33196558-e94cd8a8-d11a-11e7-857d-871bb48a132d.png)

不是合法的 Service，建议从头看下文档，https://eggjs.org/zh-cn/basics/service.html

**Comment by Lin-shurui** [comment]
我可能没有说清楚，我的本意是在egg框架下引入外部的一个普通工具对象Constru，它并不是按egg的要求写的, 它在其他项目(不是egg)下运行正常，当把它引入到当前项目下报错。
难道egg下定义对象只能按照它的格式书写，类似Constru的自定义对象无法使用？

**Comment by atian25** [comment]
这种工具类你可以放到 lib 等目录去，service 等目录是已经约定好的了，loader 会加载它并做一定的处理。

**Comment by Lin-shurui** [comment]
谢谢，有点明白了！
