### ISSUE TITLE
egg-sequelize 如何支持 oracle?

### ISSUE THREAD

**Issue by VanquisherMe** [eggjs/egg#1714]
没找到用例和对应的 oracle包 ，有提示么？

**Comment by atian25** [comment]
如果 sequelize 官方支持，我们就能使用，不支持的话就没办法。

**Comment by VanquisherMe** [comment]
@atian25 那egg 我想连接 oracle 应该怎么做？

**Comment by atian25** [comment]
如果没有 sequelize 对应的 dialect 驱动的话，那只能自己找个 oracle 的 nodejs 类库，然后参考 egg-mysql 封装了。

**Comment by solarhell** [comment]
https://github.com/eggjs/egg-knex/blob/master/lib/knex.js 这个是支持 oracle 的

**Comment by VanquisherMe** [comment]
@solarhell 有经过项目使用？怕有坑 维护周期看上去并不活跃啊

**Comment by solarhell** [comment]
`kenx`只是个sql builder，最后的执行、数据库连接都是依赖 [strong-oracle](https://github.com/strongloop/strong-oracle) 或者 [oracle](https://github.com/joeferner/node-oracle) 所以稳定性都是由这些驱动来决定的。 (http://knexjs.org/ 详见oracle驱动)
