### ISSUE TITLE
如何在非请求上下文获得 helper 对象

### ISSUE THREAD

**Issue by musicode** [eggjs/egg#1715]
文档里说只有 `ctx.helper` 或模板中才能获取 `helper` 对象，但是我理解 helper 是一个工具库，这个东西应该是 app 级别的吧，为啥要放在 ctx 级别呢。

**Comment by atian25** [comment]
你的使用场景是？

**Comment by solarhell** [comment]
https://eggjs.org/zh-cn/basics/objects.html#获取方式-2

**Comment by atian25** [comment]
schedule 有 ctx 的。

没有 ctx 的只有在非用户请求的地方，如 `app.beforStart`。

**Comment by musicode** [comment]
我的场景是这样，user service 更新用户资料，发出一个类似 user update 的事件，然后在事件处理中心，去修改 redis 的用户信息

**Comment by solarhell** [comment]
感谢指正。 在这里看到了用例 https://eggjs.org/zh-cn/core/cluster-and-ipc.html#ipc-实战

**Comment by musicode** [comment]
构造匿名 context 的行为看起来比较奇怪，像是为了 ctx 而 ctx，但其实类似我说的场景，没有请求的概念，也可能是脚本触发的呢

**Comment by solarhell** [comment]
helper应该是简单的函数，“不应该”含有太多的业务逻辑。我感觉你这边emit出来的消息，要么直接在service处理掉，要么就是一个worker来pull这个持久化过的消息来消费队列？

**Comment by musicode** [comment]
@solarhell 你说的做法当然是可以的，你没理解我的意思，我在 helper 定义了一些常用工具方法，这些方法应该是系统任何地方可用的吧？如果不是，我不理解为 ctx 专门设计一个 helper 的初衷是啥

**Comment by solarhell** [comment]
我的理解就是方便使用，框架做了注入，不需要require了。 然后你在template等等地方也随处可用。

**Comment by musicode** [comment]
如果为了不要 require，直接 `app.helper` 也是可以的吧

**Comment by atian25** [comment]
helper 的初衷是为了解决 Controller 和 Template 里面的辅助方法功能，有需要读取 ctx 内容的场景。

如果只是为了在非 ctx 情况下用的话，可以 `app.Helper.prototype.xx()`。

如果你有自己的场景的话，完全可以通过 `loader.loadToApp` 注册一个自己的 `app.utils.xx()`

**Comment by musicode** [comment]
@atian25 谢谢，了解了

**Comment by ArvinSpace** [comment]
我也感觉可以把helper直接放到app里，ctx里再自己load或者增加相关的helper函数
我把自定义的一些utils回到helper了，然后感觉如果再loadToApp或loadExtend有些累赘
所以我现在用法是app.Helper.prototype.xx

**Comment by atian25** [comment]
定义一个 Loader 不就是一个配置么。。。

```js
  // custom spec
  config.customLoader = {
    utils: {
      directory: 'app/utils',
      inject: 'app',
    },
  };
```

https://github.com/atian25/egg-showcase/pull/13/files
