### ISSUE TITLE
请问如何调用插件中定义的中间件?

### ISSUE THREAD

**Issue by taotsky** [eggjs/egg#1718]
* **Node Version**:v8.90
* **Egg Version**:1.11.0
* **Plugin Name**:egg-auth
* **Plugin Version**:1.2.2
* **Platform**:mac os
* **Mini Showcase Repository**:

@iQoderi

问题:
 在使用egg-auth插件时,需要调用其中的decodedToken().
在eggjs的路由中直接使用app.auth.decodedToken(),提示request不存在,
自己新建一个auth的中间件,在其中调用app.auth.decodedToken(),则提示app未定义.
需要怎样才能使用这个中间件呢?

插件代码如下:
[egg-auth/lib/passport.js](https://github.com/iQoderi/egg-auth/blob/master/lib/passport.js)
第50行定义的decodedToken(ctx, next){}

另:在中间件中使用插件或service的需要怎样正确的姿势.

**Comment by atian25** [comment]
egg-auth 不是官方维护的插件，可以去那边给作者提 issue。

中间件之间应该是没有关系的，不能互相调用。
中间件中如何调用 service，参见文档：https://eggjs.org/zh-cn/basics/objects.html
