### ISSUE TITLE
Q:使用egg框架时数据库连接字符串放哪里比较好？

### ISSUE THREAD

**Issue by Rwing** [eggjs/egg#172]
我现在是这样，有个db.json里面放着连接字符串

但是我觉得这样没有和egg融为一体，理想应该是放到egg的config.default.js里，可是如果放到config.default.js，我又没办法require 了。

怎么办？或者我这个bookshelf.js能调用app.config吗？
```
bookshelf.js
const connectionString = require('./config/db.json');
const knex = require('knex')(connectionString);
bookshelf = require('bookshelf')(knex);
module.exports = bookshelf
```

最后，egg有个提问交流的地方吧，用issue提问总觉得怪怪的

**Comment by fengmk2** [comment]
你在 config.default.js 里面直接 `require('./config/db.json')` 不行？

**Comment by atian25** [comment]
@Rwing  egg 的 config 文件处理有比较复杂的逻辑, 有不同环境变量, 还有插件/框架 的合并

你的 `bookshelf.js` 是在 egg 里面的, 还是单独的 js 呢?

**Comment by Rwing** [comment]
@atian25 这个bookshelf.js的作用就是拿连接串来实例化一个bookshelf对象，然后其他service，require(“bookshelf.js”)，拿这个bookshelf来操作数据库。我看了下egg-mysql，那我就要做个plugin？

@fengmk2  您可能误会了，我是想在其他地方去调用config.default.js里的东西

**Comment by atian25** [comment]
如果这个 bookshelf.js 只是在 egg 里面的其他 service 用的, 那就不需要手动 require 了, 挂到 extend 去就好了. 举个例子:

```js
// app/extend/application.js
const BOOKSHELF = Symbol('Application#bookshelf');
const knex = require('knex');

module.exports = {
  get bookshelf() {
    if (!this[BOOKSHELF]) {
      const connectionString = this.config.bookshelf.connectionString;
      this[BOOKSHELF] = knex(connectionString);
    }
    return this[BOOKSHELF];
  }
}

// app/config/config.default.js
exports.bookshelf = {
  connectionString: ''
};
```

**Comment by fengmk2** [comment]
`app.config` 能拿到当前 app 的所有配置信息。
