### ISSUE TITLE
egg-sequelize如何获取全局sequelize实例

### ISSUE THREAD

**Issue by JohnnyMore** [eggjs/egg#1732]
* **Node Version**: v8.9.0
* **Egg Version**: 1.9.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.0
* **Platform**: windows 7
* **Mini Showcase Repository**:

请问，在egg-sequelize插件中，如何在全局获取到sequelize实例？看了https://github.com/eggjs/egg-sequelize 的实例，但文档不详细，举个文档中的例子
![qq 20171124190431](https://user-images.githubusercontent.com/17742436/33207864-56665e9e-d14a-11e7-8a08-fa5b67bce470.png)
请问app.Sequelize就是全局的sequelize实例吗，可是我测试，发现并不是。
关于egg-sequelize的文档太少了，去看sequelize文档：http://docs.sequelizejs.com/ ，但是用法上是有些差异的，最大区别在于全局的sequelize实例创建方式不同，egg貌似在config.default.js配好sequelize就会创建好全局的sequelize实例，但我不知道怎么获取到。
请赐教，谢谢。
或者是否有关于egg-sequelize更详细的文档提供参考？

**Comment by airyland** [comment]
`app.model`

看文档没有，以为没有暴露，还写了个 pr(https://github.com/eggjs/egg-sequelize/pull/23) 但是官方文档似乎无意说明一下。

**Comment by atian25** [comment]
这个插件后面 @XadillaX 会接手优化，重新理下
