### ISSUE TITLE
egg适合写网关吗？有人用吗？

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1738]
http://www.express-gateway.io/

如题

**Comment by atian25** [comment]
适合，Express 能做的，Koa 和 Egg 都能做到。

**Comment by longxianlin** [comment]
哈，非常谢谢。
纠结网关。
nginx生态的kong, nginx_lua, 
jvm生态的Netty。。。
nodejs生态的。。

**Comment by atian25** [comment]
加油~ 做完了可以开源出来回馈社区
