### ISSUE TITLE
关于路由的问题

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#1740]
/camera/:id会匹配到/camera/count

**Comment by atian25** [comment]
这是正常行为。自己调整路由注册顺序。可以再看看 koa-router 文档。

**Comment by fengmk2** [comment]
`/camera/:id` 会匹配到 `/camera/count`，不是很正常么？

**Comment by fengmk2** [comment]
如果你只想 id 是 Number，你需要改成正则。

```js
'/camera/:id' => /^\/camera\/(\d{1,1000})\/?$/
```

**Comment by atian25** [comment]
100 就好了吧，1000 位的 ID。。。

**Comment by fengmk2** [comment]
@atian25 举例而已。
