### ISSUE TITLE
具体怎么升级？执行升级命令提示找不到，bash: egg-bin: command not found

### ISSUE THREAD

**Issue by tmcyfy** [eggjs/egg#1742]
请问具体如何1.0 -》 2 升级

```
执行 egg-bin autod，会自动升级 egg 的依赖为 ^2.0.0，以及其他插件版本。

```

文档里只有这么一句

如果直接执行是找不到这个命令，到node里执行也不对

**Comment by atian25** [comment]
如果你是用骨架生成的，那 npm scripts 已经有了，执行 `npm run autod`，否则自己执行 `node ./node_modules/egg-bin autod`
