### ISSUE TITLE
master 进程管理

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#1743]
现在 master 只负责管理 worker 和 agent 的重启，近期出了几个问题：

- agent 进程被 kill 后未接收到 worker 进程 id 导致 `messenger.sendToRandom` 失效
- 磁盘空间不足，worker 进程异常突出，agent 和 master 由于监听了未捕获异常，并未退出，造成不一致

master 进程需要承担一定的进程管理职责，agent 和 worker 进程相互感知的逻辑上移到 master 上。

- master 进程维护 worker 和 agent 的列表，messenger 只负责发通知给 master，master 来根据参数决定转发给哪个子进程
- master 进程保证 agent 和 worker 的存活状态，当系统异常无法恢复时，避免 agent / worker / master 半存活状态的出现

**Comment by atian25** [comment]
@dead-horse 这个是 https://github.com/eggjs/egg-cluster/pull/54 搞完了？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/pull/54#issuecomment-349185822

还需要搞这个?

**Comment by dead-horse** [comment]
messenger 还需要改造

**Comment by dead-horse** [comment]
先关了吧，之前本来还想重构一下 messenger 相关的，不改也无所谓

**Comment by dead-horse** [comment]
issue 主贴里面有写
