### ISSUE TITLE
新手请教个路由和几个warn的问题

### ISSUE THREAD

**Issue by AloneWeb** [eggjs/egg#1744]
* **Node Version**:  8.9.1 or 9.2.0
* **Egg Version**: 2.0.0
* **Platform**: win 10 家庭版or专业版
* **Mini Showcase Repository**: https://github.com/AloneWeb/egg_test

请教几个问题：
问题1：
![image](https://user-images.githubusercontent.com/22211269/33252278-147b383a-d378-11e7-9f92-1207f884b25c.png)
如图这几个warn是什么问题？对项目有影响吗？

问题2 :
`app/root.js`
`module.exports = app => {`
  `const { router, controller } = app;`
  `router.get('/', controller.home.index);`
  `router.get('/user/:id', controller.user.info);`
 ` router.get('/user/show', controller.user.show);`
`};`
这段代码有问题吗？
为什么 http://localhost:7001/user/1  这个的结果是这样:
![image](https://user-images.githubusercontent.com/22211269/33252343-935bfb8a-d378-11e7-9658-a61ac696cbf7.png)
而 http://localhost:7001/user/show  结果是这样：
![image](https://user-images.githubusercontent.com/22211269/33252369-c2551ac0-d378-11e7-87c8-6a0cab3a8988.png)
第一次写issure，有错误的地方，还请谅解
还有，希望大神指点迷津....!!

**Comment by dead-horse** [comment]
`/user/show` 会被 `/user/:id` 匹配到，需要调整顺序，如果还有疑惑，请去搜索 koa-router 的文档。

**Comment by solarhell** [comment]
你的路由优先级问题 `:id` 同时匹配到了 `1` 和 `show` 你需要限定 `:id` 为数字

**Comment by fengmk2** [comment]
Same as https://github.com/eggjs/egg/issues/1740

**Comment by AloneWeb** [comment]
谢谢 那几个warn是什么问题呢

**Comment by atian25** [comment]
英文写的很明白了吧?

**Comment by fengmk2** [comment]
reload 问题应该是 windows 下有 bug @gxcsoccer

**Comment by atian25** [comment]
@fengmk2 https://github.com/eggjs/egg/issues/1325 这个也是 win 下的
