### ISSUE TITLE
egg-sequelize 定义model时get()无效

### ISSUE THREAD

**Issue by xzluofeng** [eggjs/egg#1746]
* **Node Version*8.4.0*:
* **Egg Version*1.9.0*:
* **Plugin Name*egg-sequelize*:
* **Plugin Version*3.1.0*:
* **Platform*windows 10*:
* **Mini Showcase Repository**:

请问，在egg-sequelize插件中定义model后对其中的属性进行get()、set()设置时，set()方法可以修改存入的数据，但获取数据时get()无效

![_20171127152013](https://user-images.githubusercontent.com/22496620/33255044-a4fb0f4e-d386-11e7-9104-2719488f3099.png)

完全是按照sequelize官方文档进行设置，请问是否egg-sequelize存在其他设置，想知道是否有解决办法

**Comment by solarhell** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/test/fixtures/apps/model-app/app/model/monkey.js 请看这里的写法

**Comment by xzluofeng** [comment]
好像后台直接渲染的话get不行，但如果数据输出到前台是可以的

**Comment by popomore** [comment]
提供可复现 demo

**Comment by huacnlee** [comment]
自己检查，这部分 egg-sequelize 不可能改动到的，egg-sequelize 仅仅只一个 loader 辅助 Egg.js 将 Sequelize 的 Model 载入进去，具体的工作还是完全由 Sequelize 来实现的。

可以检查一下版本和文档是否对应，或者是有没有其他的原因。
