### ISSUE TITLE
为什么egg-i18n不能取对象

### ISSUE THREAD

**Issue by yangzichen987046** [eggjs/egg#1747]
![image](https://user-images.githubusercontent.com/18715050/33257044-aa19905a-d38f-11e7-8bbf-479aaf0b2152.png)
ctx.__('public.head_list.search')         //“检索”

ctx.__('public.head_list')                    //“public.head_list”
而不是
{
      search: '检索',
      translate: '翻译',
      dict: '词典',
      dictionary: '撰写',
      topic: '专题'
}

**Comment by atian25** [comment]
设计如此，koa-locales 会扁平化所有的 key，参见 https://github.com/koajs/locales/blob/master/index.js#L59
