### ISSUE TITLE
[RFC] rethink egg-sequelize

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1749]
之前印象中收到的一些 issue，先记录下备忘，等 @XadillaX 有空了更新为 RFC。

1. 多数据库的方案
2. 和 mongoose, mysql 等共存时的方案
3. 和 mongoose, mysql 等的 API 风格一致性
4. migration / cli 的方案和建议
5. 多级子目录

https://github.com/eggjs/egg/issues?utf8=%E2%9C%93&q=is%3Aissue+sequelize+

**Comment by iyuq** [comment]
建议使用`app.sequelize`代替`app.model`,和`mongoose`一样都用`app.model`会增加两个插件一起使用兼容的难度。

**Comment by bqxu** [comment]
之前用过 loopback.io  基于express的，可以直接做成 egg-plugins，支持多数据库方案。自己封装了一个https://github.com/bqxu/egg-loopback。只使用它的loopback-datasource-juggler 功能，就是 loopback.io 有一点学习成本，只当数据库model 用比较简单。例子
https://github.com/bqxu/egg-loopback/blob/2eb84d8cda44bc29fdfd1d8a4ba85765ae697e53/test/loopback.test.js#L33

**Comment by popomore** [comment]
@bqxu 可以加到 awesome-egg

**Comment by atian25** [comment]
在 https://github.com/eggjs/egg/issues/1749 跟进
