### ISSUE TITLE
can't define multiple directory by use dir: [dir1, dir2, ...]

### ISSUE THREAD

**Issue by echopi** [eggjs/egg#1750]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:egg-static
* **Plugin Version**:2.0.0
* **Platform**:
* **Mini Showcase Repository**:

Since the static middleware assert that dir config should be a string, how can i set multiple directories for the static assets?
```
assert.strictEqual(typeof options.dir, 'string', 'Must set `app.config.static.dir` when static plugin enable');

```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-static/blob/master/test/fixtures/static-server-multiple-dist/config/config.default.js#L4
