### ISSUE TITLE
model可否也改为class的形式

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1751]
1. model可否也改为class的形式
2. eslint 的规则可否修改一下， const a = {a:1}; const b={...a} 会提示错误
3. 还有js模块的导出 能否使用 export 和 import 的形式

**Comment by atian25** [comment]
1. 在 #1749 跟踪
2. 自己在 `.eslinrc` 里面增加 rule 即可
3. ESM 在 Node 里面还是实验性质，目前的实现还是半残废状态，暂不考虑。
