### ISSUE TITLE
QueryString里的整型只能通过添加Rule来校验吗，有没有更好的方法

### ISSUE THREAD

**Issue by jerrydotlam** [eggjs/egg#1752]
现实场景：RESTFUL的查询列表接口，可以传递参数，如`/api/v1/task/?id=111&offset=10`，但是这样从`request.query`里解析出来的都是string类型，这样就不能使用默认的`int rule`来进行校验了，否则都是校验失败：
```
{"error":"Validation Failed","detail":[{"message":"should be an integer","code":"invalid","field":"id"}]}
```
除了自己添加rule校验，还有没有更优雅的方式吗？是否可以针对`int rule`添加一个扩展参数类似`autoParse`之类的，可以自动将字符串装成int再进行校验。

**Comment by freebyron** [comment]
可以使用基于ajv的validater, 在config里设置 [coerceTypes为true](https://github.com/epoberezkin/ajv#options), 欢迎使用 [egg-ajv](https://github.com/freebyron/egg-ajv)

**Comment by dead-horse** [comment]
可以使用正则： `{id: /\d+/}`，也可以使用 @freebyron 的 egg-ajv
