### ISSUE TITLE
多机部署的情况下，如何配置只在一台机器上的一个进程中执行某个定时任务？

### ISSUE THREAD

**Issue by 7-cat** [eggjs/egg#1753]
比如在主机A,B上分别部署了egg，但是有一个定时任务只能到点了全局只能执行一次，应该如何配置？
感谢~

**Comment by atian25** [comment]
这种属于 集群调度 问题，需要第三方系统介入，简单的话自己用 redis 啥的加个锁。

我们内部的实践是会有一个任务微服务来调度，egg 这边通过 https://eggjs.org/zh-cn/basics/schedule.html#扩展定时任务类型 接入

**Comment by 7-cat** [comment]
感谢回复~
我也看了这个链接，但是没有看懂其中用法，文档里的這個scene不知道是从哪里来的，要是这个链接的文档还能详细一些就好了。。

感谢你的建议，用redis加个锁挺好的，我也业务场景也很简单。
egg真的是一个很好用的框架。

**Comment by atian25** [comment]
简单的说:
- scene 是我们随便示意的，schedule 里面自定义的一个属性
- 简单的说，你的 worker 启动时会跟远端服务注册
- 然后在 agent 里面订阅一个远端的服务，它那边会有自己调度策略
- worker 收到这个事件后执行就是了。

```js
module.exports = agent => {
  class ClusterStrategy extends agent.ScheduleStrategy {
    start() {
      // 订阅其他的分布式调度服务发送的消息，收到消息后让一个进程执行定时任务
      // 用户在定时任务的 schedule 配置中来配置分布式调度的场景（scene）
      agent.mq.subscribe(schedule.scene, () => this.sendOne());
    }
  }
  agent.schedule.use('cluster', ClusterStrategy);
};
```

**Comment by 7-cat** [comment]
好的，有自己调度策略的远端的服务 这个功能是egg提供的还是要第三方系统介入？

**Comment by 7-cat** [comment]
// 订阅其他的分布式调度服务发送的消息，收到消息后让一个进程执行定时任务

这个定时任务的文件名字在哪里指定的？

**Comment by atian25** [comment]
自己写插件，上面示例写的很明白了。

```js
agent.mq.subscribe(schedule.scene, () => this.sendOne());

exports.schedule = {
  type: 'worker',
  scene: 'xxxx',
};

```

- 在启动的时候，对 mq 这个服务，发起一个订阅
- 订阅的关键词事件是 `schedule.scene` 这个取值
- 收到这个事件后，通过 `this.sendOne()` 随机通知这台机器的一个 worker 执行。

**Comment by acodercat** [comment]
当使用了AppBootHook的时候,agent.schedule.use应该放在哪个生命周期函数里面呢

**Comment by atian25** [comment]
@acodercat didLoad
