### ISSUE TITLE
egg升级为2.0.0后egg-socket.io插件运行错误

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1754]
* **Node Version**:v9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:3.0.0
* **Platform**:Mac OS
* **Mini Showcase Repository**:

错误提示：
> socket@1.0.0 start /Users/***/Documents/website/ke3/socket
> egg-bin dev --cluster --sticky --port 7010
.........
/Users/liudong/Documents/website/ke3/socket/node_modules/_egg@2.0.0@egg/lib/application.js:40
throw e;
      ^
AssertionError [ERR_ASSERTION]: **handler must be generatorFunction or asyncFunction!**
at Namespace.route (/Users/liudong/Documents/website/ke3/socket/node_modules/_egg-socket.io@3.0.0@egg-socket.io/lib/socket.io/namespace.js:12:3)

**Comment by atian25** [comment]
你的 handler 是啥类型的？

cc @ngot

**Comment by 89790094** [comment]
@atian25 官网的example通过 npm update升级后就出现这种错误提示了

**Comment by 89790094** [comment]
应该是egg2.0与socket.io3.0的插件不兼容造成的

**Comment by atian25** [comment]
@89790094 哪一个 example ? 是 egg-socket.io 自带的还是?

**Comment by 89790094** [comment]
@atian25 [https://github.com/eggjs/egg-socket.io/tree/master/example](egg-socket.io example)

**Comment by ngot** [comment]
duplicate https://github.com/eggjs/egg/issues/1382#issuecomment-347095913

**Comment by ngot** [comment]
@89790094 用egg1

**Comment by linxuanwei** [comment]
@atian25   +1  升级 egg 2.0.0 后遇到同样问题

nodejs.AssertionError [ERR_ASSERTION]: handler must be generatorFunction or asyncFunction!

![image](https://user-images.githubusercontent.com/10094722/33361239-393bc978-d512-11e7-969a-c85b607d93d4.png)

![image](https://user-images.githubusercontent.com/10094722/33361255-4cce749a-d512-11e7-8c60-981e61d2f6fd.png)

**Comment by atian25** [comment]
@linxuanwei  楼上已经回复了，问题已确认，等 @ngot 升级下插件即可。

**Comment by linxuanwei** [comment]
谢谢,  另外希望中间件支持 async/await

**Comment by thonatos** [comment]
这个应该可以关了（升级到4.x就没问题了） #1382
