### ISSUE TITLE
在app.js中自定义Controller基类的私有方法后，controller中无法使用

### ISSUE THREAD

**Issue by SAHX** [eggjs/egg#1755]
* **Node Version**: v8.0.0

* **Egg Version**: v2.0.0

* **Plugin Name**: 无
* **Plugin Version**: 无
* **Platform**: iMac
* **Mini Showcase Repository**: 无

#### 这是按照[文档](https://eggjs.org/zh-cn/basics/controller.html)中 **自定义 Controller 基类** 的代码写的：

// app.js
```javascript
module.exports = app => {
  class CustomController extends app.Controller {

    success(data) {
      this.ctx.body = {
        success: true,
        data,
      };
    }

    notFound(msg) {
      msg = msg || 'not found';
      this.ctx.throw(404, msg);
    }
  }
  app.Controller = CustomController;
}
```
// app/controller/home.js
```javascript
'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    this.success({msg: 'hi egg!'})
  }
}
```
访问 `http://127.0.0.1:7001/`
报错：`2017-11-28 21:25:04,471 ERROR 58662 [-/127.0.0.1/-/8ms GET /] nodejs.TypeError: this.success is not a function`

#### 但是这么写就可以：
// app/controller/home.js
```javascript
'use strict';

module.exports = app => {
  const Controller = app.Controller;

  class HomeController extends Controller {
    async index() {
      this.success({msg: 'hi egg!'})
    }
  }
  return HomeController
}
```

**Comment by popomore** [comment]
如果不想用函数的方式，可以直接 require 基类

这篇文档也要改下

**Comment by dead-horse** [comment]
同时需要 `require('egg').Controller = CustomController`

**Comment by dead-horse** [comment]
文档我等下看看怎么优化一下

**Comment by atian25** [comment]
先把我那些合并后再改吧。


发自我的 iPhone

**Comment by atian25** [comment]
@popomore @dead-horse 

https://github.com/eggjs/egg/blob/docs-2.x-async-function/lib/egg.js#L123

这几个是不是改为 setter 和 getter 好点?
