### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by longxianlin** [eggjs/egg#1759]
// app/controller/post.js
module.exports = function* post(ctx) {
  const result = yield ctx.curl('https://httpbin.org/post', {
    // 必须指定 method
    method: 'POST',
    // 通过 contentType 告诉 HttpClient 以 JSON 格式发送
    contentType: 'json',
    data: {
      hello: 'world',
      now: Date.now(),
    },
    // 明确告诉 HttpClient 以 JSON 格式处理返回的响应 body
    dataType: 'json',
  });
  ctx.body = result.data;
};

报ssl证书错误。
"Hostname/IP does not match certificate's altnames: Host: ts.visbody.lanrenyun.cn. is not in the cert's altnames: DNS:ts.pro.lanrenyun.cn (req "error"), POST https://ts.visbody.lanrenyun.cn/lazyVisbody/recordEntry -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"ts.visbody.lanrenyun.cn:443:::::::::":1},"requests":{}})
headers: {}"

**Comment by popomore** [comment]
你不能改成 http 的吗，那域名没配证书
