### ISSUE TITLE
如何控制中间件的嵌套顺序

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1760]
- config.middleware 中有中间件
- plugin 中也可能有中间件

那我如何管理这些中间件的顺序！！

**Comment by atian25** [comment]
- 作为开发者，只管自己的 config.middleware 即可。
- plugin 和 framework 都是插入到 coreMiddleware 的，顺序在应用层之前。

看下文档先。https://eggjs.org/zh-cn/basics/middleware.html#在框架和插件中使用中间件
