### ISSUE TITLE
egg-sequelize插件是否该升级了？

### ISSUE THREAD

**Issue by tmcyfy** [eggjs/egg#1762]
egg 2.0

安装了 egg-sequelize 在用 npm run dev启动后提示

```
String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

```

按照链接里的资料似乎是sequelize准备弃用原来的查询符，egg的sequelize是不是该更新了，还是我的版本问题？

**Comment by iyuq** [comment]
这个应该是[sequelize-cli](https://github.com/sequelize/cli)的锅，现在`sequelize-cli`还只支持到`sequelize 3.x`,要等这个包修了这个`warning`才能去掉。
详情见：[sequelize-support](https://github.com/sequelize/cli#sequelize-support)

**Comment by atian25** [comment]
@iyuq 那边修复了没?

**Comment by iyuq** [comment]
没有呀，可以看这个[v4.0 #441](https://github.com/sequelize/cli/issues/441)，感觉是没人在做

**Comment by farzer** [comment]
mark

**Comment by duncup** [comment]
sequelize-cli已更新

**Comment by atian25** [comment]
@duncup egg 这边需要改动啥么

**Comment by duncup** [comment]
@atian25 
这个issues不是说sequelize-cli有锅么？
现在sequelize-cli升级到4.0了，已经支持到sequelize 4了。egg-sequelize是不是可以跟进一下然后关掉这个issues？

**Comment by atian25** [comment]
@duncup PR 下?

**Comment by duncup** [comment]
好，这个我等下看看。

**Comment by iyuq** [comment]
看了下报错，应该是 sequelize 的 constructor 中加了个 operatorsAliases 的配置参数，默认是 true，只要这个是 true，调用构造函数就会报这个 desperate 的信息。

**Comment by iyuq** [comment]
要去掉这个错误可以在 config.local.js 中加
```
config.sequelize = {
    dialect: 'postgres', // support: mysql, mariadb, postgres, mssql
    database: 'example-dev',
    host: 'localhost',
    port: '5432',
    username: 'postgres',
    password: 'password',
    operatorsAliases: false,
  };
```

**Comment by atian25** [comment]
为啥在 local 加

**Comment by iyuq** [comment]
在 config 里加，那几个 config 都要加。

**Comment by atian25** [comment]
直接加到 default 就好了吧，会合并的

**Comment by iyuq** [comment]
@atian25 我修改了，看看是这样不

**Comment by atian25** [comment]
嗯。如果是必须的，那是不是直接在 egg-sequelize 里面配置默认值？

**Comment by iyuq** [comment]
@atian25 这样会影响以前使用了`$or`这类 `Op`的，为了兼容只能默认开启，不想看到这个`warning`的自己去配置关掉。
