### ISSUE TITLE
egg-validate 如何自定义校验失败的错误信息

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1764]
不好意思，天天在这里问问题，不过确实是因为新起的一个node项目，正在不断实践踩坑中。

**Comment by atian25** [comment]
i18n 的在这个 issue 跟进: https://github.com/eggjs/egg/issues/1672 ，最近还没时间搞。

临时解决方式可以是自己 addRule 的时候定义下对应的 msg 即可。

**Comment by zoulux** [comment]
@atian25 
```
 const rule = {
      type: 'string',
      data: { type: 'object|bool', required: true },
    };
```
有的字段可能是多种类型

**Comment by atian25** [comment]
这种就需要你自己写 rule 了
