### ISSUE TITLE
egg-cors, option  method not allowed

### ISSUE THREAD

**Issue by zhuni** [eggjs/egg#1767]
config/plugin.js
`exports.cors = {
  enable: true,
  package: 'egg-cors',
};`

config/config.default.js
`  config.cors = {
    enable: true,
    credentials: true,
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  };`

config/config.local.js
`exports.security = {
  domainWhiteList: [ 'http://localhost:4200/' ],
};`

如果这样配置的话会报option method not allowed， 如果把domainWhitelist的配置放到config.cors的前面就不会报这个错误。我的理解是每一个环境的domainWhitelist是不同的，不应该把他放到config.default里面，不知道设计的是不是就是这样。

**Comment by atian25** [comment]
配置是可以互相覆盖的，你 2 个里面都写不就行了

**Comment by zhuni** [comment]
感觉这样有点多余，可以小小的优化下（一点小建议，可以忽略）。之前用egg开发的一个项目不用没有把domainWhitelist放在config.default.js里面也是可以的。

**Comment by atian25** [comment]
这个你可以按你自己的需求写啊，不想写 default，那就只写在 local 和 prod 咯。

**Comment by zhennann** [comment]
@zhuni 看你的白名单配置，是否想要支持前端调试。如果前端用的webpack，可以直接设置proxy，不需要在后端设置cors。

**Comment by zhuni** [comment]
谢谢，明白了

**Comment by roc2539** [comment]
@zhennann 前端用的webpack ,设置proxy,返回
{
    "message": "missing csrf token"
}
需要设置什么？

**Comment by zhennann** [comment]
此问题与webpack proxy无关。建议参考[https://eggjs.org/zh-cn/core/security.html](https://eggjs.org/zh-cn/core/security.html)
如果是前后端分离的模式，建议禁用CSRF防范。
