### ISSUE TITLE
储存singleton

### ISSUE THREAD

**Issue by leiyanggz** [eggjs/egg#1768]
* **Node Version**:8.9
* **Egg Version**:1.10
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问该如何储存singleton对象，比如存储一个new WechatAPI(), 原先是存在某个service中的本地变量，现在发现多个worker的情况下每个worker中的同一个service下的本地变量是不同的，不是singleton

**Comment by atian25** [comment]
需要理解下 Node 的 Cluster 模型，每一个 worker 都是一个进程，进程间变量当然不可能复用。

解决方式：
- 通过外部存储，如 redis
- 使用 cluster-client 模式，用 agent 来进程间同步数据，https://eggjs.org/zh-cn/tutorials/index.html

**Comment by leiyanggz** [comment]
多谢指教
