### ISSUE TITLE
定时器不准时执行的问题

### ISSUE THREAD

**Issue by MaleDong** [eggjs/egg#1770]
这是我的后端定时代码：

```
/**
 * 定时器任务，每天临晨3点清楚11天前的全部记录
 */
module.exports = {

    schedule: {
        cron: '0 0 3 * * *',    //每天凌晨3点自动执行
        type: 'worker',         // 某个Worker执行一次，Egg随机选择一个Worker执行
    },

    /**
     * 执行定时任务
     */
    *task(ctx) {
        yield ctx.service.admin.logger.deleteLogs();
    }
}

```
这是Service，功能就是删除10天前的日志：
```
   *deleteLogs() {

        let error = null;

        try {
            let intervalDays = yield this.ctx.service.utility.fetchDataConf("cleardb_interval");

            if (intervalDays.length > 0) {
                intervalDays = intervalDays[0]["name"];
            }
            else {
                //默认保留10天的记录
                intervalDays = 10;
            }

            //清空日志
            const clearSQL = `DELETE FROM sys_log WHERE DATE(sys_log.sys_created) < DATE(DATE_ADD(Now(),INTERVAL -${intervalDays} DAY))`;
            yield this.app.mysql.query(clearSQL);

            //console.log(clearSQL);

        } catch (e) {
            //忽略此异常，不能让整个系统中断
            error = e;
        } finally {
            let result = `自动清除日志已经成功执行；PID：${process.pid}`;

            if (error) {
                result = `自动清除日志发生异常，错误：${error.message}；PID：${process.pid}`;
            }
            yield this.ctx.service.admin.logger.info(result);
        }
    }
```

每次删除执行之后，它自己会往数据库记录一下，表示是否成功。但是我看时间时差很大：

	INFO	自动清除日志已经执行。	2017-11-24 03:00:03
	INFO	自动清除日志已经执行。	2017-11-25 03:18:26
	INFO	自动清除日志已经执行。	2017-11-26 03:18:18
	INFO	自动清除日志已经执行。	2017-11-27 03:18:17
	INFO	自动清除日志已经执行。	2017-11-28 02:59:54

请问这是为何？是否我忽略了什么？还是应该做什么呢？谢谢各位了。
PS：凌晨3点无人访问服务器，服务器应该处于空闲状态。我们的项目尚未发布。

**Comment by atian25** [comment]
egg-schedule 是通过 cron-parser 来获取下一次时间，然后丢给 setTimeout 的，有可能会有一些偏差。 

https://github.com/eggjs/egg-schedule/blob/master/lib/timer.js

你的日志打点是在删除日志之后的吧，是不是 `yield this.app.mysql.query(clearSQL);` 太耗时了？在最前面也打下。

cc @JacksonTian 朴老师

**Comment by MaleDong** [comment]
好的，我先试试看。不过我就是删除10天前的记录，应该不会执行时间很长。

**Comment by atian25** [comment]
看下日志就知道了，如上面我贴的，第 2 条日志有 `cron.js excute succeed, used 2ms`

**Comment by MaleDong** [comment]
我看到你们把我这个帖子和另外一个“日志切割提前进行”，请问日志会自动切割吗？我们没有配任何显示的切割参数。

**Comment by atian25** [comment]
日志切割是通过定时去触发切割的。
你这个问题先确定下触发时间有没有问题先。

egg-schedule 自带的 timer 只能用来做一些不需要非常精确的定时，如果有需要可以自己扩展下，egg-schedule 有预留接口了

**Comment by atian25** [comment]
先关了，若你有进一步消息的时候再反馈和开启吧。

**Comment by EchoVie** [comment]
我也出现了这问题 没有解决

**Comment by LeoFengFromChina** [comment]
我也遇到同样的问题。egg的版本是2.37.0，egg-schedule的版本是3.7.0
