### ISSUE TITLE
想要集成kue

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1772]
这边想专门起一个`queue`去执行异步任务，看到`kue`的评价不错，请问egg这边该怎么集成比较合适

**Comment by buzai** [comment]
require kue , in some function add a task , in other project cost the task

**Comment by zoulux** [comment]
```
  kue.process('email', (job, ctx, done) => {
    done();
  });
```
主要是类似这样的任务`action`为`email`,想要创建一个单独email.js 去处理这个任务，还有这个任务在process的时候拿不到egg的ctx，这个ctx是kue的ctx，没有egg的ctx那么我就无法引用到sevice下的代码。`egg-kue`这个插件实现的内容并不是我想要的，我想要向定时任务那样，统一管理queue中的任务

**Comment by buzai** [comment]
你是想用你之前的写好的service吧？你把emails 搞成service ，想法把kue放在一个能拿到egg ctx的函数里，这样你就拿到了service也拿到了emails， 我记得我那时候放在了app.js

**Comment by zoulux** [comment]
@buzai 感觉还是不好，这样什么时候启动`emails`呢，`app.js` 中怎么拿到`ctx`呢

**Comment by popomore** [comment]
可以使用这种方法

https://github.com/eggjs/egg-schedule/blob/master/README.md

**Comment by popomore** [comment]
看自定义那部分

**Comment by popomore** [comment]
已经邮件沟通
