### ISSUE TITLE
【国际化】-提议-前端也参与多语言加载，与node一起配合体验应该更好。

### ISSUE THREAD

**Issue by diyao** [eggjs/egg#1774]
抱歉，还不熟悉用github，第一次提issues。有何打扰望体谅。

后端基于浏览器中的头部信息，拆解出语言关键字决定使用什么语言，靠cookie设置并保留用户设置的语言信息。那么，前端也可以。

## **在后端处理多语言**
好处：显示更快，页面出来，语言文案就有了。
缺点：切换语言，页面需要刷新。也无法通知其他页签，其他页签也必须刷新才行。

## **前端处理多语言：**
缺点：页面出来，前端再发请求加载文案，文案显示更慢了。
优点：切换语言，页面无刷新加载替换语言文案。可以通过localStorage的change事件通知到其他页签也修改文案。

前端的多语言加载器，让我彻底从php后台中解放了出来。
而如果是node，那完全可以结合前后端一起搞定多语言。
https://github.com/diyao/multi-lang-js 这是我的一个实现（限于水平有限，见笑了）。
思路是：从navigator.language || navigator.userLanguage拿取信息，翻译成需要的语言。初始化时，配好各个语言对应的语言包。设置语言通过localStorage，这样可以通知到其他页签。方便测试和特殊需要，允许带入lang参数，指定某个语言。

## **配合node：**
设置语言时候，前端除了设置localStorage（通知其他页签），也设置cookie（也让node知晓）。用户有多语言需求时，除了node做处理，也返回一段脚本给前端，让前端也可以直接处理。前端和node可以共用语言包。

https://diyao.github.io/multi-lang-js/index.html 在线预览，开多个页签试试。

以上一个提议。

感谢各位大神，我正在（昨晚开始）上手egg。

**Comment by atian25** [comment]
所以现在的问题是？如果是想把 i18n 传给前端，那应用自行处理就好了，读取那个文件即可。

发自我的 iPhone

**Comment by diyao** [comment]
不知官方会否提供一套把前端方案也解决。
现在就是使用者自行解决前端方案，也ok。
所以提个议哈~

**Comment by atian25** [comment]
Egg 主要聚焦在服务端领域，而且前端框架众多，Egg 本身不会去涉猎这一块。

社区的开发者可以自行开发类似的上层框架或插件，并开源回馈给社区。

**Comment by diyao** [comment]
好的，多谢！
才刚开始接触egg。
