### ISSUE TITLE
egg session 修改maxAge无效

### ISSUE THREAD

**Issue by ChenHaoNane** [eggjs/egg#1777]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

config/config.default.js
![image](https://user-images.githubusercontent.com/16717351/33542553-7aa50adc-d90e-11e7-9194-792ea290946a.png)

**Comment by atian25** [comment]
若已经解决，最好回复下具体原因再 close

**Comment by ChenHaoNane** [comment]
是有效的我自己弄错了 不好意思
