### ISSUE TITLE
使用egg-sequelize时获取app.Sequelize.Op为undefined

### ISSUE THREAD

**Issue by NightFarmer** [eggjs/egg#1780]
"egg": "^1.9.0",
    "egg-sequelize": "^3.1.0",

在controller中获取不到Op
```
module.exports = app => class extends require('egg').Controller {
    async test(){
        const Op = app.Sequelize.Op;
        console.log(Op);//undefined
    }
};
```
在Sequelize官方文档中指定是要用Op来进行where条件查询的, 但是通过插件拿不到这个属性, 是版本原因还是我的调用方式不正确?

**Comment by iyuq** [comment]
检查 sequelize 包的版本，不行的话删了node_modules目录和 package-lock.json 再重新安装。

**Comment by NightFarmer** [comment]
@iyuq 找到问题根源了 
删掉node_modules后
使用yarn安装,问题会出现
使用npm安装,没有问题
使用cnpm安装,没有问题

问题就出在使用yarn上, egg安装是不是不能用yarn?

**Comment by atian25** [comment]
yarn 锁版本的锅吧，这个 egg 不背

发自我的 iPhone

**Comment by NightFarmer** [comment]
@atian25 emmmm... 所以就是不能用yarn了 是吧?  我觉得这个应该写在文档里啊  在这个问题上纠结了两天 还特意去看了下egg-sequelize的源码  好闹心

**Comment by atian25** [comment]
并不是用 yarn 就会有问题，而是用 yarn 你就要理解它的限制和不同点，这个不是 egg 的职责。前面第一条就回复不要锁版本了吧。

发自我的 iPhone

**Comment by NightFarmer** [comment]
@atian25 明白了  感谢回复   看来要恶补一下yarn了 233333

**Comment by SugarTiger** [comment]
this.app
