### ISSUE TITLE
http://localhost:7001/socket.io/socket.io.js 找不到

### ISSUE THREAD

**Issue by hadwin2017** [eggjs/egg#1781]
* **Node Version**: v7.8.0
* **Egg Version**: v1.9
* **Plugin Name**: egg-socket.io
* **Plugin Version**: v3.0.0
* **Platform**: windows 7
* **Mini Showcase Repository**: 暂无

通过浏览器访问，http://localhost:7001/socket.io/socket.io.js。返回结果为
{"code":0,"message":"Transport unknown"}

**Comment by ngot** [comment]
看不懂问题。能不能说的清楚一些？

**Comment by pengkobe** [comment]
@hadwin2017  我是这么解决的: 直接拷贝 ```node_modules/egg-socket.io/node_modules/socket.io/node_modules/socket.io-client/dist/``` 下的 socket.io.slim.js 在前端进行引用，而不是直接 http://serverrul:port/socket.io/socket.io.js 的方式，不过报```{"code":0,"message":"Transport unknown"}```的原因还是没搞懂.

**Comment by ngot** [comment]
Need more information, feel free to reopen this issues.
