### ISSUE TITLE
egg-scripts 启动问题

### ISSUE THREAD

**Issue by liuguichi** [eggjs/egg#1783]
* **Node Version**: 8.9.1
* **Egg Version**:1.9.0
* **Egg-scripts Version**:2.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

同一台服务器上部署了3个egg构建的服务A，B，C：
 A启动成功后A的服务一切正常；
 B启动成功后的B的服务一切正常，但是A的服务被停掉了（有时又是正常的，但是被排挤掉当概率非常高）
如果这时候再启动C ，C正常了 ，A和B都挂了（概率问题概率非常大）
ABC分别监听  127.0.0.1:6001  127.0.0.1:7001 127.0.0.1:8001
以上情况 ，望大神抽空解答下，谢谢

**Comment by atian25** [comment]
看错误日志

发自我的 iPhone

**Comment by liuguichi** [comment]
log看不出啥，然后仔细看了文档，然后加了title,圆满解决。谢谢大神！！！
--title=egg-server 用于杀死指定的 egg 应用，未传递则会终止所有的 Egg 应用。
