### ISSUE TITLE
router 传递默认值

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#1785]
* **Node Version**:9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

``` js
// app/router.js
module.exports = app => {
  app.router.get('/user/', app.controller.user); 
  app.router.get('/user2/', app.controller.user); 
};
```

如上述代码，有2个路由均指向一个controller的action，希望定义路由的时候，能给action传递一个默认值。
目前可以通过婉转的路由内部跳转实现，但是本质上不想暴露出这个内部路由。
``` js
// app/router.js
module.exports = app => {
  app.router.get('/user/:type', app.controller.home.index);
  app.router.get('/user', '/user/用户', app.controller.home.index);
  app.router.redirect('/user2', '/user/顾客', app.controller.home.index);
};
```

**Comment by popomore** [comment]
redirect 不是内部路由，按你这些写就好了

**Comment by a304885433** [comment]
@popomore  感觉回复，其实我是不太想定义这个路由。
```
 app.router.get('/user/:type', app.controller.home.index);
```
这本来就是多余的，也不会对外开放。
期望的特性如下，伪代码表示一下
```
  app.router.get('/vipuser', app.controller.user.index, { type: 'vip' });
  app.router.get('/svipuser', app.controller.user.index, { type: 'svip' });
```
即在指定action来处理的时候，手动传递几个参数，这样action就可以获取到。

**Comment by popomore** [comment]
没看懂，这两个路由并没有关系。

**Comment by a304885433** [comment]
对，2个路由没有关系，但是背后处理实际上对应的是一个controller的一个action，期望是通过传值让action自身知道是谁在调用，这个传值不是从前端过来的。

**Comment by popomore** [comment]
其实你固定路径通过 ctx.path 就可以判断了。

**Comment by a304885433** [comment]
嗯，确实path可以处理，之前用其他语言的框架，定义路由的时候，是可以传递默认值的，所以就直接往这个方向考虑了。
谢谢。

**Comment by a304885433** [comment]
@popomore 
``` js
 app.router.get('s', '/vip', async function (ctx, next) {
    ctx.params.type = 'vip用户'
    await next();
  }, app.controller.user.get)
```
抉择了一下，最后采用中间件的方式处理了，这样更灵活。
这样的代码，还有优化或者简写的空间么。

**Comment by popomore** [comment]
抽一个 type 中间件

app.router.get('s', '/vip', type(‘vip’), app.controller.user.get)

**Comment by a304885433** [comment]
@popomore 
```
'use strict';

module.exports = (options, app) => {
    return async function (ctx, next) {
        await next();
    };
};

```
其实本来想写成中间件的，但是这里不知道怎么接收传递过来的参数，所以只好在路由那写死了，这里怎么接收呢。

**Comment by atian25** [comment]
看中间件文档，在 router 中使用中间件章节。

发自我的 iPhone

**Comment by a304885433** [comment]
嗯，是可以的，最早做的时候，主要参照的文档是 就是路由章节和中间件章节，之前调试的时候可能是写错了，以为无法从options获取到变量。现在再试了下，是可以的。

谢谢。这种方式给action处理，增加默认值，就完全能达到预期了，再次感谢。
