### ISSUE TITLE
egg-mongoose 警告 导致egg-scripts 无法正常启动

### ISSUE THREAD

**Issue by sasbsd** [eggjs/egg#1786]
* **Node 8.9.1**:
* **Egg 2.0**:
* **Platform mac**:
项目启用 egg-mongoose 按照文档部署 在 package.json 中添加 "start": "egg-scripts start --daemon", 使用 npm start 启动后 出现错误提示  
[egg-scripts] Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
启动失败，如果使用全局安装 egg-scripts 后运行 egg-scripts start --daemon 能正常启动
开发环境有该信息提示，但是一切正常，

**Comment by popomore** [comment]
authenticate 要改成 connect 了 @jtyjty99999

**Comment by sasbsd** [comment]
这种错误是否不应该中断运行

**Comment by jtyjty99999** [comment]
ok

**Comment by jtyjty99999** [comment]
这个是个warning啊，为啥会退出呢。。。。 @atian25 不应该退出吧

**Comment by atian25** [comment]
@jtyjty99999 https://github.com/eggjs/egg/issues/1644
