### ISSUE TITLE
egg-development

### ISSUE THREAD

**Issue by jasontsai1990** [eggjs/egg#1787]
修改文件不会重启服务器。egg-init egg-example --type=simple 安装这个套装的。

**Comment by atian25** [comment]
请提供可复现方式，这样信息不足矣进一步分析问题。

1. 修改什么文件
2. 什么操作系统和环境？ docker
3. 屏幕录屏

发自我的 iPhone

**Comment by jasontsai1990** [comment]
1. 修改 app/contorller/home.js 
2. macos 10.13.1

![](https://i.loli.net/2017/12/06/5a276e9127768.png)
![](https://i.loli.net/2017/12/06/5a276e912c7fe.png)

前两天还可以的，我修改之后，terminal 有黄色的提示进程被重启，今天发现不可以。
是按照下面步骤执行的
$ npm i egg-init -g
$ egg-init egg-example --type=simple
$ cd egg-example
$ npm i

$ npm run dev
$ open localhost:7001
--

**Comment by atian25** [comment]
touch 下排除编辑器问题

发自我的 iPhone

**Comment by jasontsai1990** [comment]
![Screen Shot 2017-12-06 at 12.50.13 PM.png](https://i.loli.net/2017/12/06/5a277743a37d8.png)

touch 也不可以。

**Comment by jasontsai1990** [comment]
我刚刚在一台ubuntu主机测试了一下，文件修改进程是会重启的。但我这台macos就不知道为什么了。我重启主机 尝试了多几次 也一样。

**Comment by jasontsai1990** [comment]
我发现原因了，是环境变量的原因
export NODE_ENV=test 设置这个变量之后
并且没有设置 EGG_SERVER_ENV=local

本地环境就会出现问题。

**Comment by atian25** [comment]
`NODE_ENV=test` 而没有 `EGG_SERVER_ENV` 时，会视为测试模式：
https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js#L109-L111

而 development 插件仅在 dev 下加载：
https://github.com/eggjs/egg-development/blob/master/package.json#L5-L9

cc @popomore `egg-bin dev` 是不是要加个 `env: local` 的默认值

**Comment by popomore** [comment]
为啥设 NODE_ENV 呢？
