### ISSUE TITLE
Cannot read property 'apply' of undefined   @koa/cors

### ISSUE THREAD

**Issue by zhuni** [eggjs/egg#1788]
**config.defualt.js**
`module.exports = appInfo => {
  const config = exports = {};
  config.keys = appInfo.name + '_1511926934724_1128';
  config.cors = {
    enable: true,
    credentials: true,
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  };

  return config;
};`

**config.local.js**
`exports.mongoose = {
  url: 'mongodb://127.0.0.1/index',
  options: {},
};

exports.security = {
  domainWhiteList: [ 'http://localhost:4200' ], 
};`

**plugin.js**
`exports.mongoose = {
  enable: true,
  package: 'egg-mongoose',
};

exports.cors = {
  enable: true,
  package: 'egg-cors',
};

exports.security = {
  enable: false,
};`

server有请求就报错。报错如下
`2017-12-06 11:37:05,133 ERROR 4444 [-/127.0.0.1/-/1ms OPTIONS /] nodejs.TypeError: Cannot read property 'apply' of undefined
    at Object.proto.(anonymous function) [as vary] (/Users/zhuni/work/index-server/node_modules/delegates/index.js:40:31)
    at cors (/Users/zhuni/work/index-server/node_modules/@koa/cors/index.js:50:9)
    at dispatch (/Users/zhuni/work/index-server/node_modules/koa-compose/index.js:42:32)
    at /Users/zhuni/work/index-server/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/zhuni/work/index-server/node_modules/koa/lib/application.js:150:12)
    at Server.handleRequest (/Users/zhuni/work/index-server/node_modules/koa/lib/application.js:132:19)
    at Server.emit (events.js:159:13)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
headerSent: true
pid: 4444`

根据报错找了node modules里面的文件，是 delegates/index.js 里面的一处地方。好像是@koa／cors里面的一处引起的。
![image](https://user-images.githubusercontent.com/11365592/33643455-284d4818-da7a-11e7-8928-1aed48e668cf.png)
koa/cors里面的地方应该是
`    ctx.vary('Origin');

    if (!requestOrigin) {
      return next();
    }`
请问下这个是哪里出了问题？

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by zhuni** [comment]
找到报错原因了，把公共的controller写在了app.js里面
`'use strict';

module.exports = app => {
  app.beforeStart(async () => {
    app.response = (returnCode, returnUserMessage, data) => {
      this.ctx.body = {
        error: {
          returnCode: returnCode || 0,
          returnMessage: returnUserMessage || 'success',
          returnUserMessage: returnUserMessage || '成功',
        },
        data: data || {},
      };
    }; // 报错

  });
};
`
按照之前的文档应该是写在一个继承app.controller的controller里面,然后挂载在app上面。其余的controller都继承自己定义的这个controller。这次错误是我直接把公共方法写在了app.beforeStart这个函数里面。我把app.js里面的代码改成了下面这种，是想在app上挂载一个公共方法，
`
module.exports = app => {
  app.beforeStart(async () => {
    app.response = (returnCode, returnUserMessage, data) => {
      return {
        error: {
          returnCode: returnCode || 0,
          returnMessage: returnUserMessage || 'success',
          returnUserMessage: returnUserMessage || '成功',
        },
        data: data || {},
      };
    };

  });
};
`
这样在controller 里面 this.ctx.body = this.app.response(0, 'xx','dd'); 也会报这个
` ERROR 26749 [-/127.0.0.1/-/0ms OPTIONS /collect] nodejs.TypeError: Cannot read property 'apply' of undefined`这个错误。

###app.beforeStart里面是不是完全不能在app上挂一些公共方法，只能做一些获取数据之类的？？

**Comment by atian25** [comment]
要学会 markdown 语法和基础排版，上面的内容阅读性很差。代码块是三个 `

**Comment by atian25** [comment]
`app.beforeStart` 挂方法就太晚了，一般在 app/extend/application.js 挂，其次直接在 app.js。
具体看文档 https://eggjs.org/zh-cn/basics/extend.html
