### ISSUE TITLE
egg-socket.io无法handle route

### ISSUE THREAD

**Issue by microud** [eggjs/egg#1789]
* **Node Version**: 8.7.0
* **Egg Version**: 2.0.0
* **Plugin Name**: egg-socket.io
* **Plugin Version**: 
* **Platform**: macOS
* **Mini Showcase Repository**:

使用egg-socket.io之后，middleware都可以正常工作，发送对应的消息，但是 **app/io/router.js** 中的“路由”并没有通过指定的controller进行处理。

调试了一下插件中的 **io.js** 发现：
```
if (nsp[RouterConfigSymbol]) {
        for (const [ event, handler ] of nsp[RouterConfigSymbol].entries()) {
          socket.on(event, (...args) => {
            const ctx = args.splice(-1)[0];
            ctx.args = ctx.req.args = args;
            handler.call(ctx)
              .then(() => ctx[CtxEventSymbol].emit('finshed'))
              .catch(e => {
                if (e instanceof Error) {
                  e.message = '[egg-socket.io] controller execute error: ' + e.message;
                } else /* istanbul ignore next */{
                  debug(e);
                }
                ctx[CtxEventSymbol].emit('finshed', e);
              });
          });
        }
      }
```
该段代码中的 **nsp[RouterConfigSymbol]** 一直为undefined，打印nsp得到
```
controller: { chat: [Object], test: [Object] },
controllers: [Getter],
```
测了一天多，傻了都。求帮忙，先谢过了。

**Comment by ngot** [comment]
并没有这个文件(`app/io/router.js`)的约定只有 `app/router.js`

**Comment by zengwe** [comment]
我发现我的也写在里面结果还是不能执行对应的controller，controller: { chat: [Object], test: [Object] },这个打印结果也相同

**Comment by microud** [comment]
@zengwe @NiBoTe 解决的方法就是上面ngot讲的——仔细看文档，这个issue关闭的原因也是没有跟着文档来。socket.io的路由是跟web路由写在一起的。有具体问题联系主页的邮箱吧。
