### ISSUE TITLE
请问egg router的resources方法，为何不支持`PATCH`来支持标准的restful更新部分字段

### ISSUE THREAD

**Issue by jerrydotlam** [eggjs/egg#1793]
请问egg router的resources方法，为何不支持`PATCH`来支持标准的restful更新部分字段

**Comment by atian25** [comment]
应该是没场景吧，欢迎 PR。

cc @dead-horse @jtyjty99999

**Comment by popomore** [comment]
这个确实是之前的设计问题，patch 是有场景的，只是用 put 误用了。

**Comment by dead-horse** [comment]
新增一个 PATCH -> patch 方法的映射吧，这样如果要完整遵循 http Method 语义的话，部分更新就实现 patch，全量更新就实现 update。

**Comment by mosaic101** [comment]
@dead-horse @atian25 @popomore  是否需要更改为 patch/put 都指向 update ？ #1938

**Comment by dead-horse** [comment]
改成 update 也可以，文档里面都用 PATCH 替换掉 PUT，从文档层面 deprecate 掉 PUT 方法吧。

**Comment by mosaic101** [comment]
@dead-horse 建议参考 [ Ruby on Rails 的 Router](http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions) 设计， 且向下兼容...  PUT也不用 deprecate
