### ISSUE TITLE
How could I use eggjs/egg-oss both STS mode and server site upload mode?

### ISSUE THREAD

**Issue by releasethecow** [eggjs/egg#1796]
As titled. 

thanks to @popomore we can use sts in our pj. but now I face another case that, I hv to use both type of mode that upload in browser and nodejs.

should I use ali-oss instead?

**Comment by popomore** [comment]
Yes, ali-oss can be used in browser.

**Comment by releasethecow** [comment]
OK, I will use ali-oss for my pj. thanks.
