### ISSUE TITLE
Set server port in config file

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1797]
* **Node Version**:  v9.x
* **Egg Version**:    v1.x
* **Plugin Name**:   
* **Plugin Version**:
* **Platform**:  Linux
* **Mini Showcase Repository**:

你好，请问如何把服务器启动端口写在 **配置文件** 中，我在官网上看到的是写在 `package.json` ，但是我希望能够写在 `config/config.default.js` 里面，请问应该怎么做？

还有，我有一些不太清楚 `debug` 和 `dev` 有什么区别，`dev` 是 `debug` 的子集吗？

希望能得到解答，谢谢～ :laughing:

**Comment by atian25** [comment]
- 第一个看 https://eggjs.org/zh-cn/core/deployment.html#启动配置项
- 第二个问题看源码即知，https://github.com/eggjs/egg-bin/blob/master/lib/cmd/debug.js

```js
const Command = require('./dev');
class DebugCommand extends Command {
}
```

**Comment by skyfore** [comment]
@atian25  OK , Thanks !
