### ISSUE TITLE
在写egg路由挂载插件遇见的问题

### ISSUE THREAD

**Issue by dahuahe** [eggjs/egg#1799]
* **Node Version**:
9.2.0
* **Egg Version**:
2.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

1. 插件是在plugin/app.js 中 `beforeStart` 中写 使用 loader加载路由文件方式
2. 保证在路由文件与标准写法不变的情况下构建.
![image](https://user-images.githubusercontent.com/16739083/33724627-e6d19a92-dbaa-11e7-8a1c-3ec76f6fcd05.png)
2. 挂载 以下是思路
   1.  router**单实例**.尝试在register中的参数path做文章...实力有限未能修改参数. 以后将继续尝试
   2.  没法,只能扩展app的方法(这个方法会影响性能吗???)
![image](https://user-images.githubusercontent.com/16739083/33724779-4d98e244-dbab-11e7-875a-8d8e4b8aeab0.png)
    于是路由文件也修改了一些
![image](https://user-images.githubusercontent.com/16739083/33724849-814b91cc-dbab-11e7-8479-3fd02b40b776.png)
 在文件加载处
....
![image](https://user-images.githubusercontent.com/16739083/33724878-9ac4e1bc-dbab-11e7-9928-56e48cffe6bc.png)
..
挂载成功.....

想问问还有更好的方法吗?毕竟2方法会有很多Router实例

**Comment by atian25** [comment]
先描述下你的插件解决哪些痛点问题？你期望用户如何使用？

发自我的 iPhone

**Comment by dahuahe** [comment]
**痛点:**以往router.js文件 太多路由代码，于是按模块分成多个js文件，但需要手动require 且不直观路由信息。
**用户使用:**自动加载router文件下的js文件，并用文件名给路由加上父级路由，比如  router/demo.js ,访问路由为   curl  get ip:7001/demo/..,可自定义正则加载文件。
路由文件的写法保持不变如上图，但是能力有限未能做到 导致需要返回一个新的router实例            
来自安卓手机:grinning:

**Comment by atian25** [comment]
ref: https://github.com/eggjs/egg/issues/882

你这个分两个问题：
1. 支持 sub router
2. 自动加载 router 文件然后自动挂载到 sub router

**Comment by dahuahe** [comment]
文件加载解决了，就是sub router 如果用app.router有点难搞定，所以只能new Router。请问还有别的思路吗？:grinning:

**Comment by atian25** [comment]
- Router 实例多没啥关系，也多不到哪去，一次性的，顶天算你一百个文件？
- 但你的实现方式中我觉得 `Router.get()` 看起来有点怪怪的，实例不应该大写

**Comment by atian25** [comment]
还有一种方式，但有一点 hack 的味道，我也没想好，你可以看看：

在 init 里面， 传递给 `app/router/**.js` 的并不是原来的 `app.router` 而是一个 Proxy 代理，然后 hook 掉它的所有 method，在前面注入 path。

**Comment by dahuahe** [comment]
我也是打算这样做的。哈哈   就是没有hook进去。   我多去查查这方面hook资料  哈哈 突然说到点上了:kissing_heart:

**Comment by atian25** [comment]
我会更倾向于类似 https://github.com/eggjs/egg/issues/882 的方案，给用户一个 `app.router.namespace('/admin')` 的方式，而自动路径这个，感觉未来可以通过 TypeScript 的装饰器来搞。

还有一种方式就是，你改变 router 的入参，改为：  `module.exports = (app, subRouter) => {}` 这样的，在 loader 里面注入第 2 个参数。

**Comment by dahuahe** [comment]
感谢。这些思路我都去试试:heart_eyes:

**Comment by dahuahe** [comment]
使用proxy方式完成app.router.namespace  #882 也放在github上egg-mount, 开发这个插件对egg有很多认识.

**Comment by atian25** [comment]
@dahuahe 我周末也写了一个 https://github.com/atian25/egg-router-plus/pull/1/files

你的那个，建议类似我这样的，用 MR 的方式，这样我们可以帮你 Review 提建议

**Comment by dahuahe** [comment]
嗯嗯 我使用了.不过还不是很熟悉.[谢谢指教](https://github.com/dahuahe/egg-mount/pull/3) 😍
