### ISSUE TITLE
egg-init无法通过系统代理

### ISSUE THREAD

**Issue by zhou5384** [eggjs/egg#1800]
* **Node Version**:8.9
* **Egg Version**:2.0

假如系统通过代理才能访问网络，而npm已经设置了代理，这时egg-init初始化工程，将提示连接超时。查看代码发现，egg-init调用的urllib时，默认不启用代理。

**Comment by atian25** [comment]
欢迎提个 PR 支持下，可以参考 https://github.com/eggjs/egg-development-proxyagent/blob/master/app.js

**Comment by atian25** [comment]
land at 1.13.0
