### ISSUE TITLE
egg-socket.io如何向指定用户推送消息？

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1801]
* **Node Version**:9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:4.0.1
* **Platform**:Mac OSX

服务器端向指定的在线用户推送消息：
```
this.ctx.socket.to(socketId).emit('private',data);
```
无效，是不可以使用吗？或者只能使用：
```
this.ctx.socket.emit(socketId,data);
```
插件文档也未说明可以用那些方法以及方法该如何使用，请指教！

**Comment by ngot** [comment]
socket.io 的文档具体的看官方文档：https://socket.io/docs egg-socket.io 只是对组件的一个包装，并不管具体的用法。

在服务端，每个socket对象本身就直接对应一个具体用户，并没有socketId这个概念。你可以自己设计来管理存储socket对象。

同时，还可以利用socket.io 自生的api来广播消息。

**Comment by 89790094** [comment]
就是想知道egg-socket.io如何向指定用户推送消息？
