### ISSUE TITLE
userservice.js增加isLogin属性

### ISSUE THREAD

**Issue by Julyyq** [eggjs/egg#1802]
是否应该给egg-userservice增加一个isLogin的方法？
现在只有user和userId,但是应用中往往很多地方会判断用户是否登录，增加一个isLogin会方便很多。

**Comment by atian25** [comment]
应用层自己加个 app/extend/context.js 扩展就好了。

发自我的 iPhone

**Comment by atian25** [comment]
现在更推荐用 https://github.com/eggjs/egg-passport 了。

另外，extend 命名推荐是 `ctx.isAuthenticated()`

**Comment by Julyyq** [comment]
OK
