### ISSUE TITLE
对于需要传入两个参数的 Koa 中间件，目前好像并不支持配置

### ISSUE THREAD

**Issue by zengwenfu** [eggjs/egg#1804]
目前 egg 的中间件配置使用只接受最多一个 {} 形式的 options 参数
module.exports = {
  // 配置需要的中间件，数组顺序即为中间件的加载顺序
  middleware: [ 'gzip' ],

  // 配置 gzip 中间件的配置
  gzip: {
    threshold: 1024, // 小于 1k 的响应体不压缩
  },
};

但是，有一些 koa 插件是接受两个参数的
module.exports = function(compiler, option) {
    var action = webpackHotMiddleware(compiler, option);
    return function* (next) {
        var nextStep = yield middleware(action, this.req,  this.res);
        if (nextStep && next) {
            yield* next;
        }
    };
};
这种时候第二个参数就没法传了

**Comment by atian25** [comment]
中间件是你自己初始化的，自己拿不出来不就行了。

```js
// config/config.default.js
module.exports = {
  webpack: {
     compiler: {},
     others: {},
  },
};

// app/middleware/webpack.js
module.exports = (options, app) => {
  const action  = webpackHotMiddleware(options.compiler, options.others);
  return async (ctx, next) => {
    // ...
  }
};
```

**Comment by zengwenfu** [comment]
中间件不是我的，我想用别人的，但是现在我不得不自己再封装下

**Comment by zengwenfu** [comment]
例如：https://www.npmjs.com/package/koa-webpack-dev-middleware 这个中间件，现成的

**Comment by zengwenfu** [comment]
那确实需要封装一个了，我的意思是，egg 能否在这上面做兼容

**Comment by atian25** [comment]
我的意思是：
1. 如果对方是 egg 插件，那他没遵循 egg 规范，肯定是插件那边要改。
2. 如果是 koa 插件，那他也没遵循 koa 常见的中间件方式，你这边自己 wrap 一下就可以了。你期望 egg 怎么兼容？如果哪天又有一个 3 个参数的呢？

**Comment by zengwenfu** [comment]
比如，配置传递数组，那么解析成多个参数传入
配置成 object，按照 option 的形式传入

**Comment by zengwenfu** [comment]
对方是 koa 插件

**Comment by atian25** [comment]
肯定不行啊，如果某个 koa 的插件，第一个参数就是一个 array 呢？

你直接写个 middleware wrap 下就可以了，框架层做这个没太大的必要性。

**Comment by zengwenfu** [comment]
数组的第一层只是多个参数的区分依据，如果第一个参数是array,那么形式就是，[[arg1], arg2, arg3]
如果框架层不做兼容，建议文档中，可以做一下简单的说明，提醒 wrap，或者按照规则写 koa 插件

**Comment by atian25** [comment]
> 数组的第一层只是多个参数的区分依据，如果第一个参数是array,那么形式就是，[[arg1], arg2, arg3]

这就复杂化了，Koa 官方推荐的中间件方式就是 `(options, app) => {}`

文档中，有几个地方已经提到了：

![image](https://user-images.githubusercontent.com/227713/33797185-887c8692-dd3e-11e7-88bd-5543de7fa413.png)

加了一个 PR：https://github.com/eggjs/egg/pull/1805

**Comment by zengwenfu** [comment]
OK
