### ISSUE TITLE
官方文档的异常处理部分有点问题

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#1807]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

自定义404响应处语法有点问题，少一个function声明。

**Comment by atian25** [comment]
具体？

**Comment by AkashiX** [comment]
@atian25 发现了几处问题，晚上我做个PR吧。
