### ISSUE TITLE
egg-bin autod

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1810]
since `egg-bin` had support `autod` at https://github.com/eggjs/egg-bin/blob/master/lib/cmd/autod.js

we need:

- remove `autod` from boilerplates
- `egg-bin autod` should detect `config/plugin.js` then autoload `autod-egg`.

**Comment by dead-horse** [comment]
autod 作为可选项吧，对应用层来说复杂起来了 autod 的可行性不高

**Comment by atian25** [comment]
嗯，先关了吧。

issue 的意思是，既然我们的 egg-bin 内置了 autod 了，那可以改下骨架，直接用。（但目前的 egg-bin autod 没有内置 autod-egg 的支持）
