### ISSUE TITLE
Who is using egg?

### ISSUE THREAD

**Issue by axetroy** [eggjs/egg#1812]
能否加个文档，标识谁在用egg。

一来给开发者增加信心，而来扩散知名度。

有线上应用就很有说服力，开发者可以PR增加自己基于egg的线上应用

**Comment by atian25** [comment]
感谢反馈，有个 awsome-egg

发自我的 iPhone

**Comment by axetroy** [comment]
@atian25 
这种东西，写在主项目的README里面更好

awsome系列更偏重于一些非常酷的插件，中间件，实现等等

**Comment by atian25** [comment]
@axetroy 可以考虑直接修改 Wiki:  https://github.com/eggjs/egg/wiki/Who's-using-Egg

README 那边加一个这个链接。

cc @eggjs/core

**Comment by dead-horse** [comment]
不用加了吧，没什么意义，大部分的框架也不会加这个信息

**Comment by okoala** [comment]
我觉得可以加到官网上，列一堆图标~

**Comment by atian25** [comment]
@okoala 先 WIKI 吧，现在都不知道有什么 level 的，加了也没啥用。
