### ISSUE TITLE
logger配置outputJSON为true，能否禁用原有的输出文件

### ISSUE THREAD

**Issue by walkerx** [eggjs/egg#1817]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

logger配置outputJSON为true，日志文件中仍然有原始格式的日志文件输出。能否给一个配置来禁用file？

**Comment by dead-horse** [comment]
不会禁用 file。 file 是给人看的，json 是给特定的监控系统用的。
