### ISSUE TITLE
WinOS 上npm i执行时出现fsevents模块错误的信息

### ISSUE THREAD

**Issue by woniu1983** [eggjs/egg#1820]
Error信息------------------------------------------------
E:\Projects\Nodejs\egg-example>npm i
npm ERR! path E:\Projects\Nodejs\egg-example\node_modules\fsevents\node_modules\getpass\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'E:\Projects\Nodejs\egg-example\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'E:\Projects\Nodejs\egg-example\node_modules\fsevents\node_modules\getpass\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\Projects\\Nodejs\\egg-example\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'E:\\Projects\\Nodejs\\egg-example\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }
npm ERR!
Error信息------------------------------------------------

发生情况：
   egg-init 执行时
   egg-example执行 npm install 时 

README指引里面注明Windows上使用时 npm i --no-optional  跳过fsevents模块

**Comment by atian25** [comment]
这个跟 egg 没啥关系，属于 fsevents 这个 node 模块在 win 的兼容性问题。
