### ISSUE TITLE
效仿Java的泛型+反射解决复用代码问题

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#1822]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

有个需求：想创建一个service基类，里边提供了一些通用的CRUD方法。子类继承只需要传入类型，声名当前的model类型即可。想请教下大神们有啥提议？

**Comment by atian25** [comment]
可以

**Comment by AkashiX** [comment]
@atian25 = =不知懂咋实现啊。

**Comment by atian25** [comment]
```js

class BaseSerice extends egg.Service {
  async get(id) {
    return this.model.get(id);
  }
}

class UserService extends BaseService {
  constructor(ctx) {
    super(ctx);
    this.model = this.ctx.model.User;
  }
}
```
