### ISSUE TITLE
httpclient的一个小疑问

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#1823]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

app.curl和ctx.curl用法相近，两者具体有啥区别吗？

**Comment by ZQun** [comment]
@atian25   httpclient  内直接传pfx，key，cert，passphrase等参数就可以使用证书了吗？
```
ctx.curl(url, {
  pfx: fs.readFileSync('./cert.p12'),
  passphrase: 'password'
});
```

**Comment by atian25** [comment]
curl 底层是 https://www.npmjs.com/package/urllib
