### ISSUE TITLE
请问有没办法在加载插件前执行初始化逻辑

### ISSUE THREAD

**Issue by AntSworD** [eggjs/egg#1826]
* **Node Version**: v8.6.0
* **Egg Version**:2.0.0
* **Platform**: MacOS

因为我的生产环境的限制，插件 egg-mongoose 启动前需要进行准备工作，我尝试在 app.js 里编写 beforeStart 的逻辑，实际没有效果，查了下 [Loader 加载顺序](https://eggjs.org/zh-cn/advanced/loader.html#文件顺序)，发现这个自定义初始化的限制还是蛮大的

请问有没什么优雅的方法可以在这个加载顺序中各个步骤之间执行初始化逻辑？

**Comment by atian25** [comment]
写一个上层框架，定制 Loader

**Comment by popomore** [comment]
问题可以转变成 egg-mongoose 是否支持准备工作，不过这个是要做什么

**Comment by atian25** [comment]
猜测是读取服务端的配置？

**Comment by atian25** [comment]
插件自己的依赖，应该是它才知道的，作为应用开发者不应该去干涉，因为这个干涉就像 hack 了，正确的做法应该是推动这个插件增加接口，支持定制。

**Comment by popomore** [comment]
这个应该是个通用方案，用 Singleton 可以动态创建实例

**Comment by AntSworD** [comment]
我表达错了，这里的依赖我想的是，我们使用者决定插件依次加载的顺序

**Comment by atian25** [comment]
没有理解错，我的观点是：应用开发者不应该去考虑插件的加载顺序。

**Comment by AntSworD** [comment]
也是，由插件提供扩展支持也对

**Comment by atian25** [comment]
egg-mongoose 现在好像是不支持动态创建的，cc @jtyjty99999

**Comment by jinasonlin** [comment]
egg-mongoose 通过 Singleton 实现的 pr 已经提交过，通过 createInstance 可以动态创建

**Comment by danielwii** [comment]
从目前的初始化顺序上看，自定义初始化后 service 才会被初始化。
我现在也面临应用初始化的问题，但需要调用一些 service，这该怎么处理？

**Comment by popomore** [comment]
在 beforeStart 里面做

**Comment by danielwii** [comment]
@popomore beforeStart 中 app.service 还没有被初始化吧，拿不到。

**Comment by popomore** [comment]
是创建一个匿名 ctx，然后 ctx.service

**Comment by lihaonanGY** [comment]
@jinasonlin 能够贴一下 通过 createInstance 动态创建 egg-mongoose的这一块的代码么？

**Comment by allenlongbaobao** [comment]
egg version: 2.23.0
在 beforeStart 环节使用匿名 ctx，调用 service，会报 
```
Cannot read property 'app' of undefined
```
的错误
另外，为什么自定义启动过程放在 service 前面，这个设计基于什么考虑？

**Comment by atian25** [comment]
提供最小可复现仓库单独提 issue 

@allenlongbaobao
