### ISSUE TITLE
请问egg可以增加渲染层这个概念吗

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1827]
* **Node Version**: 8.9.1
* **Egg Version**:2.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:linux
* **Mini Showcase Repository**:

因为我这边是这样的，譬如一个人喜欢吃是苹果和橘子，存入数据库里面放的是apple,orange，但是输出到前端的时候还是翻译成苹果和橘子，请问上面翻译的这个功能该怎么实现

**Comment by atian25** [comment]
没看懂，如果你说的是国际化的话，看 egg-i18n。

渲染层就是 Controller，自己处理文本转换即可。

**Comment by zoulux** [comment]
直接在Controller里面处理文本对吧，那我就这样做吧，谢谢
