### ISSUE TITLE
egg-passport memo

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1830]
- [ ] egg-passport
  - ~~`mount` should support custom by strategy, such as `passport-local` need `/post`~~
  - `errorhandler`, for now,  `passport-local` fail will not catch by `egg-onerror`
- [ ] docs
  - add convention rule for plugins, such as User must return `provider`
- [ ] example
  - add example for intercept user visit and redirect to login
  - redirect to origin url
- [x] plugin
  - [x] finish https://github.com/eggjs/egg-passport-local

cc @fengmk2

**Comment by OnedayLiu** [comment]
`mount` 增加 post 后，使用方式和直接使用 `app.post` 区别不大，讨论后确定不支持 `/post`
