### ISSUE TITLE
egg可以打包成一个包含node.js的包，直接部署到linux上运行吗？

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#1831]
egg可以打包成一个包含node.js的包，直接部署到linux上运行吗？

**Comment by atian25** [comment]
这里分为两个问题：

> 把 Node.js 打包到发布的代码去
这个有两种方式：
- 用 https://github.com/cnpm/nodeinstall 把 Node 安装到 node_modules 下，根据 npm 的规则，用 `npm start` 的时候会优先用它的。
- 直接 docker

> 把应用代码打包成单个文件

这个用 http://enclose.io/

**Comment by wucangeo** [comment]
@atian25 egg怎么做代码混淆呢？ 有推荐的工具吗。
项目需要部署在客户那里，是否是一个包没关系，但需要混淆代码。

**Comment by atian25** [comment]
前端代码从来就是裸的，也只能稍微加一点难度而已。
未来 WebAssembly 可能还有点可能。
Egg 没什么特殊的，JS 应该怎么混淆就怎么混淆，看看社区有什么方案吧。
上面提到的 http://enclose.io/ 也可以看看。

**Comment by wucangeo** [comment]
@atian25 好的，多谢！
