### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by guoweibo** [eggjs/egg#1832]
请问我想在定时任务里面写　socket定时执行，但是是未定义function,谢谢了
![11111111111111](https://user-images.githubusercontent.com/19238970/33981589-752c2fb8-e0e8-11e7-8ca5-6b84d4e4f58d.png)

**Comment by thonatos** [comment]
```
module.exports = {
  schedule: {
    interval: '1m', // 1 分钟间隔
    type: 'all', // 指定所有的 worker 都需要执行
  },
  async task(ctx) {
    const { app } = ctx;
    const nsp = app.io.of('/');
    nsp.emit('hi', 'hello world');
  },
};
```

**Comment by ngot** [comment]
截图的用法逻辑上不对。

socket 是一个相对概念，是相对于特定 client 的。在定时任务里面的 ctx 是匿名的，并不是任何客户端的指代，这里去调用 socket 没有意义。

楼上的代码，可以活动 io 对象对应的 namespace ，来做特定需求。

这个需求，可以考虑通过外部服务，比如 redis 来中转达到。

最根本的，还是这个需求的逻辑本身比较奇怪。

- 是每个用户，定时下发特定消息？(每个用户不同)
- 定时向所有用户下发消息？(广播)

**Comment by thonatos** [comment]
我没这需求，是给楼上演示一下如何在定时任务里调用发送消息~

**Comment by ngot** [comment]
@thonatos 我没遇到过这个。这个到 socket.io 那边提issue吧。

**Comment by guoweibo** [comment]
主要是以php做的系统，sokect.io做推送，所以才会做定时任务．我跑定时任务从数据库拿出来数据，推送给某个人 @ngot 希望能给一个好的想法，谢谢了

**Comment by ngot** [comment]
这个要分情况讨论：

- 如果是服务器单机单进程：用这个api https://socket.io/docs/server-api/#server-sockets 拿到所有的socket对象，去筛选需要的socket来推消息即可
- 如果服务器是多台或者多进程，那就复杂了。
    - 首先，定时任务 egg-schedule 是每台机器的某一个随机worker进程在执行，无法获取到全量的 socket 对象
   - 其次，因为是集群的每台机器都执行，所以就算拿到了 socket 对象，也会被执行多次。

如果是，不从部署架构上确保单机单进程，那么对于这个问题，需要一个分布式的定时器，并且需要有一个调度系统来获取所有的socket的对象，或者做一个单独的消息下发系统。

这个不是一个插件能够解决的问题，需要从系统架构上去设计。

**Comment by atian25** [comment]
@ngot 这里缺一篇 socket.io 文档~~

![image](https://user-images.githubusercontent.com/227713/34029458-b6eaa13a-e1a3-11e7-881b-ac51ead01dbc.png)

**Comment by atian25** [comment]
@thonatos 欢迎 PR 文档

**Comment by guoweibo** [comment]
明白了，多谢了 @thonatos @ngot

**Comment by thonatos** [comment]
@atian25 

文档是 `PR` 到哪个项目呢

**Comment by atian25** [comment]
egg，参考我最新写的那个 passport 文档

发自我的 iPhone

**Comment by Quinton** [comment]
#1285

**Comment by Quinton** [comment]
##1285
