### ISSUE TITLE
pm2部署再服务器时：Cannot read property 'watch' of undefined

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#1833]
* **Node Version**:9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

部署在服务器时，使用pm2报错。首先提示缺少各种模块包（已经根据提示安装过了），手动安装完提示缺少的包之后，报错如下：
/home/openapi/node_modules/_egg-development@2.1.0@egg-development/agent.js:28
agent.watcher.watch(watchDirs, debounce(reloadWorker, 200));
               ^
 TypeError: Cannot read property 'watch' of undefined
at module.exports.agent (/home/openapi/node_modules/_egg-development@2.1.0@egg-development/agent.js:28:17)

**Comment by atian25** [comment]
清除你的 node_modules 目录，删除 lock 文件，重新安装

发自我的 iPhone

**Comment by Cheese-Yu** [comment]
重装后报错如下：（我服务器上还有跑着另外一个egg项目，不知是否是这个原因）
at Master.onAppExit (/home/openapi/node_modules/_egg-cluster@1.12.6@egg-cluster/lib/master.js:367:21)
|     at Master.emit (events.js:159:13)
|     at Messenger.sendToMaster (/home/openapi/node_modules/_egg-cluster@1.12.6@egg-cluster/lib/utils/messenger.js:122:17)
|     at Messenger.send (/home/openapi/node_modules/_egg-cluster@1.12.6@egg-cluster/lib/utils/messenger.js:87:12)
|     at EventEmitter.cluster.on (/home/openapi/node_modules/_egg-cluster@1.12.6@egg-cluster/lib/master.js:246:22)
|     at EventEmitter.emit (events.js:164:20)
|     at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
|     at Object.onceWrapper (events.js:254:19)
|     at ChildProcess.emit (events.js:159:13)
|     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
| name: 'AppWorkerDiedError'
| pid: 18020
| hostname: iz8vb6r5az049nq9bnulekz
| 2017-12-14 22:55:44,842 ERROR 18020 [master] app_worker#1:18066 start fail, exiting with code:1

**Comment by Cheese-Yu** [comment]
解决了，因为7001端口被占用的问题。谢谢了~
