### ISSUE TITLE
Socket.io不能直接在Egg.js的App中运行？

### ISSUE THREAD

**Issue by MaleDong** [eggjs/egg#1834]
没有用Egg socket.io而是用了原生态的Socket.io（2.0.4）。就是服务端中在connection事件中用SetInterval每1秒给客户端发一个Hello。同样的代码写在App.js里（module.exports = app =>{……}的外边和里边的app.BeforeStatt方法里边），在Windows本地和远程，分别用调试和Prod两种当时部署都正常。但是部署到Linux上时断时续，就是400 Bad Request，WebSocket和轮询均有失败，在Chrome下Network面板下点进去看发展Session Id Unknown的错误，同时Linux存在一些TIme_Out连接。请问这是什么原因？是Egg里不能使用原生态的Sockei.io，还是需要做什么配置？
公司不能上Github，代码和错误信息将稍后设法给出。

**Comment by ngot** [comment]
egg.js 是多进程架构。看官方文档 https://socket.io/docs/using-multiple-nodes/ 多进程架构下，需要自己处理好 sticky 的连接问题。

egg-socket.io 就是在解决这个问题。如果不喜欢，也可以尝试自己来思考如何做。

**Comment by MaleDong** [comment]
但是Windows下本地和远程没有此问题？

**Comment by MaleDong** [comment]
Windows下多进程没有这个问题，远程也没有这个问题。只有在部署到Linux上才有。我想确认一下是否是SitckySession问题
