### ISSUE TITLE
请问如何访问根目录下面的静态文件

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#1838]
请问如何访问根目录下面的静态文件
谢谢！

**Comment by atian25** [comment]
为啥要放根目录

发自我的 iPhone

**Comment by xinnian1992** [comment]
微信开发,需要放一个文件在根目录，然后验证 @atian25

**Comment by xinnian1992** [comment]
现在文件无法被微信访问，所以无法验证

**Comment by atian25** [comment]
URL 路径跟文件没啥关系，你做个 router 即可

发自我的 iPhone

**Comment by xinnian1992** [comment]
请问如何在路由中指向根目录呢？现在好像都需要控制器方法，你能给个demo吗？@@atian25

**Comment by xinnian1992** [comment]
谢谢 @atian25

**Comment by atian25** [comment]
app.router.get('/xxxx', async (ctx) => ctx.body = '文件内容')

发自我的 iPhone

**Comment by airyland** [comment]
给个建议，直接在 nginx 配置就行了。如果是 txt 文件内容，直接在 nginx 返回字符就行了，环保高效。
