### ISSUE TITLE
使用next.js时，报Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by shzisg** [eggjs/egg#1840]
因为在使用next.js渲染前端的时候，需要next.js来处理/_next/的请求，这些请求会被next.js直接处理完成，然后在完成后，egg的中间件有的会设置header，导致Cannot set headers after they are sent to the client，比如koa就有ctx.respond=false就可以不处理后面的，有没有方式跳过后续的处理

**Comment by dead-horse** [comment]
koa 的 ctx.respond 也不能阻止这个错误的发生，由于 egg/koa 的中间件可能会在结束时写 header，而 next 在这之前就已经把 body 返回了，这不符合 egg/koa  的生命周期，导致 egg 的中间件全部失效。

如果你可以确定这些中间件不需要被 next.js 处理的路由用到，你可以将 next 的中间件加到最前面。

```js
// app.js
module.exports = app => {
  app.config.middleware.unshift('next');
}
```

**Comment by atian25** [comment]
next.js 和 nuxt.js 这类，感觉对 Koa 的兼容性不够。

@okoala 你做的那个框架好像是 hack 了 next.js 来结合 egg ？

**Comment by okoala** [comment]
@atian25  是 hack 进来的，本身 next 的实现算是优雅了，但是扩展性不足。
@shzisg  用 next 的话你可以考虑 [avet](https://github.com/avetjs/avet)，不过目前还是预发状态。

**Comment by shzisg** [comment]
@dead-horse 自定义middleware和核心的coreMiddleware不在一个数组，核心的插件会先执行
@atian25 这个不错，后面考虑切换下，eggjs有没有好的hack方式呢

**Comment by atian25** [comment]
avet 就是 @okoala 搞的一个基于 egg 的上层框架。

hack 的话，你看 Koa 社区怎么 hack 就怎么 hack 吧，主要问题是 next 这些直接接管了 response 而不走 Koa 的洋葱中间件。

**Comment by atian25** [comment]
先关了，有好的实践后，欢迎回来分享。
