### ISSUE TITLE
建议：验证以及代码即文档

### ISSUE THREAD

**Issue by jzlxiaohei** [eggjs/egg#1841]
微博上提到代码即文档，包括验证这块，我把我想象中的用法写一下。

```javascript
class PostController extends Controller {
  @validate({
      query: {
          offset : joi.number().integer().min(0).default(0).description('query offset'),
          limit: joi.number().integer().default(10).description('query limit'),
          order:joi.string().default('-created_at').description('query order')
       },
       // payload, path params ..
  })
  async list() {
    const { ctx, service } = this;
     // ...
  }
}
```
这样基本用比较文档化的代码完成`验证`。 集中路由那块，可以根据这些信息，`自动生成swagger文档`等（当然还要定义response）

可能的问题
1. `decorator` 尚不是定稿，可能需要 export.validate = { list: { ... config}} 这样的形式
2. 这里使用了`joi`。使用其他 validate 库都可以，不过目前看，joi的接受程度应该是最高的。

**Comment by atian25** [comment]
1. `decorator` 可以在 TS 中实践，它其实是语法糖而已
2. `joi` 这个是可以封装个 egg-validate-joi 的插件的，然后提供对应的 API
3. `decorator` 只是对 2 中的 API 提供一个语法糖调用而已，编译后的代码跟用户自己写区别不大。

感谢参与讨论。可以按你自己的想法写点插件，分享给社区。

**Comment by popomore** [comment]
期待贡献
