### ISSUE TITLE
安装egg模块出现异常。

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#1843]
操作流程如下：
```
$ npm i egg-init -g
$ egg-init egg-example --type=simple
$ cd egg-example
$ npm i
```

在`npm i`时，出现了如下错误`npm ERR! Unexpected end of JSON input while parsing near '...-plugin-puml":"^1.0.0'`

![image](https://user-images.githubusercontent.com/3679798/34093539-bce233b6-e403-11e7-9ce0-6a73e6f2c551.png)

* **Node Version**:
v8.9.3
* **Egg Version**:
v2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
无法复现，把你生成的 package.json 上传下

**Comment by atian25** [comment]
只有 egg 里面有个 `egg-plugin-puml` 的，我怀疑是你网络问题，导致安装的包有问题，删除缓存和依赖，还有 lock，重新安装下看看？

**Comment by kylezhang** [comment]
是的，只egg中有`egg-plugin-puml`.
- package.json内容
```
{
  "name": "conv-media-callback",
  "version": "1.0.0",
  "description": "conversion@jice media callback.",
  "private": true,
  "dependencies": {
    "egg": "^2.0.0",
    "egg-scripts": "^2.5.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.13.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^5.1.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon",
    "stop": "egg-scripts stop",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
  "ci": {
    "version": "8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "",
  "license": "MIT"
}
```

**Comment by atian25** [comment]
到这一步就跟 egg-init 没啥问题了，剩下的就是 `npm install` 的事了，我本地无法复现这问题。检查下是不是自己网络（被墙或太卡），或者 npm cache 之类的问题吧。

**Comment by kylezhang** [comment]
Thanks!
解决了，
是与`npm`有关系，我使用的是`npm config registry`如下：
![image](https://user-images.githubusercontent.com/3679798/34095342-05545fb8-e40c-11e7-8168-280a0cf1a512.png)
看来有时间还是有问题；
最后换成了`cnpm`解决了。
