### ISSUE TITLE
可以提供一个调试方法么

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1847]
* **Node Version**:8.9.1
* **Egg Version**:2.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问一下有形如PHP中的dd() 这个简便的调试方法吗？（打印，并终止后面所有的调用）

**Comment by atian25** [comment]
js 自带 `debugger;`
