### ISSUE TITLE
egg-socket.io 丢失客户端连接时的错误信息

### ISSUE THREAD

**Issue by leemove** [eggjs/egg#1848]
* **Node**:  8.9.0
* **Egg**:  2.0.0
* **Plugin**:  egg-socket.io
* **Plugin Verison**:  4.0.1
* **Platform**:  windows10 x64
* **Mini Showcase Repository**:

# egg-socket
我在网页端和egg-socket.io做连接,当网页关闭,在触发断开连接事件的同时,eggJs会记录一个错误.
![image](https://user-images.githubusercontent.com/11146494/34143714-14f0a982-e4c9-11e7-9c93-5fb6250348ca.png)
![image](https://user-images.githubusercontent.com/11146494/34143730-25b03558-e4c9-11e7-873f-86037b0b6cfc.png)
我尝试着捕捉这个错误,却找不到在哪里抛出的...

**Comment by leemove** [comment]
应该和事件没有关系,我只是按照插件的demo走了一遍,没有配置redis.

**Comment by ngot** [comment]
@leemove 把错误日志完整的贴一些

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/30

**Comment by leemove** [comment]
已更新到新版本
如果用火狐浏览器刷新页面服务器端没有报错,会显示 `disconnection!` 然后重新`connect`.

但是如果用chrome:会先报错
1. `2017-12-19 18:39:50,322 ERROR 20672 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET`
2.  然后断开连接 `disconnection`
3.  最后再重连`connect`

![default](https://user-images.githubusercontent.com/11146494/34153203-2b2dd4c2-e4ec-11e7-9926-193fbdc25b18.png)

错误日志也每次也只有一行 类似这三条
```
2017-12-19 18:35:25,534 ERROR 36316 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2017-12-19 18:35:31,149 ERROR 36316 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2017-12-19 18:39:50,322 ERROR 20672 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
```

**Comment by ngot** [comment]
@leemove 能复现的代码，完整的给我一份吧，我无法复现这个问题。

**Comment by Ailein** [comment]
@ngot  你好，想问下，如何在agent  上用 socket ？

**Comment by ngot** [comment]
@Ailein agent 目前无法使用，因为设计上适合http共用的，agent无法提供http服务，那么也就无法提供 websocket 服务。

**Comment by Ailein** [comment]
@ngot 好的，谢谢

**Comment by leemove** [comment]
@ngot  [复现代码仓库](https://github.com/leemove/egg-example)
这个问题只有在谷歌浏览器才会有,火狐浏览器就没有了.仓库下有gif截图.

**Comment by fx109138** [comment]
我也遇到这个问题了，目前只在chrome上发现

**Comment by magicknight** [comment]
A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
我也遇到了

**Comment by Annoak** [comment]
ERROR 2219 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET  

这个怎么解决的？

**Comment by thonatos** [comment]
> Chrome ws 请求异常，firefox 等正常

错误位置：

- [socket.js#L125](https://github.com/socketio/engine.io/blob/HEAD/lib/socket.js#L125)
- [transport.js#L86
](https://github.com/socketio/engine.io/blob/d93ef6aeb9b7a3f4a8571320684d40dbdacebc69/lib/transport.js#L86)

目前来看是 `engine.io` 的问题，可以通过更换 `wsEngine` 解决：

```js
exports.io = {
    init: { wsEngine: 'uws' },
};
```
