### ISSUE TITLE
通过 getFileStream 获取上传文件时获取其他域出现问题

### ISSUE THREAD

**Issue by troyeagle** [eggjs/egg#1849]
* **Node Version**: 8.1.3
* **Egg Version**: 1.4.0/2.0.0
* **Plugin Name**: egg-multipart
* **Plugin Version**: 1.4.0/2.0.0
* **Platform**: win10
* **Mini Showcase Repository**:  https://gist.github.com/troyeagle/749c717eab237e0901a76932dc214ee8

我希望获取上传文件时同时获得在 post 请求 multipart 中的其他字段。在通过 getFileStream 获取上传文件时，我可以通过 `stream.fields` 可以获得其他字段。但这些字段与文件流不一定相关。
https://github.com/eggjs/egg-multipart/blob/master/app/extend/context.js#L41

同时，通过该方法只能获得在文件之前被加入 post body 中的字段。之后的字段将无法获得。在复现仓库中提供了postman 请求模拟。

我希望在 getFileStream 时能够完整地获得请求中的其他字段，或者有什么更好的办法可以便捷地实现获取包括文件流在内的 post 请求的方式？

**Comment by popomore** [comment]
> 通过该方法只能获得在文件之前被加入 post body 中的字段

是这样的

可以使用底层接口 multipart https://github.com/eggjs/examples/blob/master/multipart/app/controller/multiple.js

**Comment by troyeagle** [comment]
但是 file 在字段中的位置挪一下，框架就异常了，这个不行的吧。

还有 stream.fields = part.fields 这个不好，那些非文件的字段应该在 body 里面才是合适的。

还有就是试了下你给的那个示例没解决我的问题。在文件后面的字段就没了啊！

**Comment by popomore** [comment]
你把那个例子起来，点 multipart 的试试。

multipart 的模式是 stream 的，只能按顺序解析，和单纯的 bodyparser 不一样。

**Comment by dead-horse** [comment]
文档中有说明

https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6
