### ISSUE TITLE
egg-passport代码错误

### ISSUE THREAD

**Issue by caiya** [eggjs/egg#1850]
如下，this应为ctx：
![image](https://user-images.githubusercontent.com/12036572/34147294-28850664-e4d8-11e7-9599-6b38f10010fb.png)

![image](https://user-images.githubusercontent.com/12036572/34147311-38f60ce6-e4d8-11e7-962a-263da816bf60.png)

egg-passport：v2.0.0

**Comment by atian25** [comment]
确实，来个 PR ？

**Comment by atian25** [comment]
land 2.0.1
