### ISSUE TITLE
post请求不生效，总是404

### ISSUE THREAD

**Issue by hudawen** [eggjs/egg#1851]
* **Node Version**: 8.9.0
* **Egg Version**: 2.0.0
* **Plugin Name**: egg-mysql, egg-view-nunjucks
* **Plugin Version**: 3.0.0, 2.1.4
* **Platform**: macOs

没有装egg-rest，用app.get或app.router.resources对get请求都能生效，但post请求一直是404。

```
// services/api.js
export async function addTest(params) {
  return request('/api/test', {
    method: 'POST',
    body: params,
  });
}

// router.js
module.exports = app => {
  app.get('/api/test', 'test.index');
  app.post('/api/test', 'test.add');
}

// controller/test.js
const Controller = require('egg').Controller;

class TestController extends Controller {
  async index() {
    const ctx = this.ctx;
    ctx.body = await this.service.test.getPage(ctx.request);
    ctx.status = 200;
  }

  async add() {
    const ctx = this.ctx;
    ctx.body = await this.service.test.add(ctx.request);
    ctx.status = 201;
  }
}

module.exports = TestController;

// service/test.js
module.exports = app => {
  class TestService extends app.Service {
    async add(req, res, u, b) {
      const body = (b && b.body) || req.body;
      const item = await this.app.mysql.insert('test', {
        ...
      });
     ...
    }
  }
  return TestService;
}
```

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by hudawen** [comment]
没装egg-rest的情况下app.post('...','...')这种写法是否可行呢，是的话那egg-rest的意义是？

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by hudawen** [comment]
@popomore @atian25 麻烦看看有什么问题~

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by atian25** [comment]
@hudawen 用 egg-init 提供最小可复现代码库

**Comment by popomore** [comment]
要不要加到 faq 里

**Comment by hudawen** [comment]
在抽离出demo时发现犯了个低级错误。。
从mock切换到服务端接口时没写 'POST /api/*': 'http://localhost:7001'

**Comment by BonderTam** [comment]
遇到404问题
// router.js
router.resources("users", `${baseUrl}/users`, controller.users);
// usersController.js
async index (){}  // 正常
async create() {}  // 404
async update() {} //正常
------------
async create () {
 // 函数内部就简单的这两句
 this.ctx.body = {  msg: 'ok' };
 this.ctx.status = 201;
}
