### ISSUE TITLE
间歇性发生接收到的文件长度和前端发送的长度不符

### ISSUE THREAD

**Issue by turnipwang** [eggjs/egg#1853]
const { ctx, service } = this;
    const stream = yield ctx.getFileStream();
    if (
      stream.fields.title === "mock-error" ||
      stream.fields.title === "mock-read-error"
    ) {
      yield sendToWormhole(stream);
      this.logger.warn("error " + stream.fields.index);
      ctx.body = "数据错误";
      return;
    }
    if (
      stream._readableState.buffer.head == null ||
      stream._readableState.buffer.head.data == null
    ) {
      ctx.body = "数据为空";
      return;
    }

if (stream.fields.length != stream._readableState.buffer.head.data.length) {
      ctx.body = "数据长度错误";
      return;
    }

因为本地无法复现，想问一下可能是什么原因造成的，或者少了什么判断或者设置吗？

**Comment by popomore** [comment]
写的有问题，看这个例子 https://github.com/eggjs/examples/tree/master/multipart

**Comment by turnipwang** [comment]
stream._readableState.buffer.head.data.length 这样取到的长度是不对的是吗？
因为我是要直接用传过来的二进制直接写到数据库里，所以之前没有加例子里的写到本地这一段，请问这一段要怎么改造？

**Comment by popomore** [comment]
看上面的例子，如果只需要 buffer，需要先收集完成。
