### ISSUE TITLE
egg-view-assets 插件

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#1855]
从内部迁出新 RFC

前端静态资源插件

1. 支持单页应用
1. 支持模板 + 多个静态资源
1. 支持本地调试（多工具）
1. 支持生产环境资源映射（map.json）

## 单页应用

单页面应用一般以 js 作为入口，html 只是一个简单模板（或静态），而且多个页面可以共用一个模板。

使用 egg-view 接口来渲染页面

```js
// config/config.default.js
exports.view = {
  mapping: {
    '.js': 'assets',
  },
};

// app/controller/home.js
const Controller = require('egg').Controller;
class HomeController extends Controller {
  async render() {
    await ctx.render('index.jsx');
  }
}
module.exports = HomeController;
```

这个 render 接口并不是在服务端渲染 js，而是会渲染一个默认的 html，页面渲染时会 script 请求指定的这个 js，如

```html
<html>
<body>
<script src="http://127.0.0.1:7001/index.js"></script>
</body>
</html>
```

render 的寻址逻辑和 egg-view 一致，所以如果要自定义文件夹（如 app/assets）需要添加文件路径

```js
module.exports = appInfo => {
  const baseDir = appInfo.baseDir;
  return {
    view: {
      root: `${baseDir}/app/view,${baseDir}/app/assets`
    }
  }
};
```

### 自定义模板

默认模板可能不满足需求，比如修改 title 等，可以自己来编辑

指定默认的模板路径和引擎，**指定引擎需要引入相关插件**

```js
exports.assets = {
  templatePath: path.join(app.config.baseDir, 'app/view/layout/template.html'),
  templateViewEngine: 'nunjucks',
};
```

模板

```html
<!doctype html>
<html>
  <head>
        {{ helper.getStyle() | safe }}
  </head>
  <body>
    <div id="root"></div>
    {{ helper.getScript() | safe }}
  </body>
</html>
```

使用 `helper.getScript` 方法可获取当前渲染的静态资源比如上面的 `index.js`，getStyle 同理。

### 传递变量

有时需要传递变量给前端，比如用户名等，可以使用 render 接口

```js
// app/controller/home.js
const Controller = require('egg').Controller;
class HomeController extends Controller {
  async render() {
    // 传递数据给前端
    await ctx.render('index.jsx', { foo: 'bar' });
  }
}
module.exports = HomeController;
```

模板

```html
<!doctype html>
<html>
  <head>
        {{ helper.getStyle() | safe }}
  </head>
  <body>
    <div id="root"></div>
    <script>window.context = {{ helper.getAssetsContext() | safe }};</script>
    {{ helper.getScript() | safe }}
  </body>
</html>
```

这时可以从 `window.context` 取到变量

## 模板 + 资源

传统的前端开发方式，在页面上引入多个前端资源，后端也使用传统模板渲染

```js
// config/config.default.js
exports.view = {
  mapping: {
    '.html': 'nunjucks',
  },
};

// app/controller/home.js
const Controller = require('egg').Controller;
class HomeController extends Controller {
  async render() {
    await ctx.render('index.html');
  }
}
module.exports = HomeController;
```

模板

```html
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <div id="root"></div>
    <script>window.context = {{ helper.getAssetsContext() | safe }};</script>
    {{ helper.getScript('common.js') | safe }}
    {{ helper.getScript('index.js') | safe }}
  </body>
</html>
```

这种模式必须传入文件路径，否则会报错。

## 本地调试

本地调试可集成现有工具，只需要指定端口。如使用 roadhog 只需配置 `roadhog server` 启动

```js
exports.assets = {
  devServer: 'roadhog server',
  devServerPort: '8000',
};
```

还需要指定 devServerPort（这里因为 roadhog 默认启动 8000 端口）确定静态服务启动在那个端口。本地开发会把 assets.url 切换到 `127.0.0.1:8000`（这里要保证使用的工具支持这种方式，比如 publicPath 也指向到新路径）。

## 资源映射

这点是在这个方案中比较复杂的，本地开发和最终上线的静态资源路径是不同的，但是调用代码不应该修改。

常见静态资源构建后会在末尾添加 hash 保证路径唯一，每次构建产物都必须不同（如果无修改可以一致）以保证 CDN 缓存，所以可以设计这样的映射关系（只要遵循上面的规则即可）

```json
{
  "index.jsx": "https://cdn.com/appname/index-fudjccuieuw1.js"
}
```

如果在生产环境，`helper.getScript()` 通过这个映射关系返回最终的 CDN 地址。

## 配置

```js
exports.assets = {
  url: 'http://127.0.0.1:7001',
  templatePath: path.join(__dirname, '../lib/template.html'),
  templateViewEngine: 'nunjucks',
  devServer: 'roadhog server',
  devServerPort: '8000',
};
```

**Comment by atian25** [comment]
- `map.json` 叫 `manifest.json` 更合适点？
- 配置改为多级？
```js
exports.assets = {
  url: 'http://127.0.0.1:7001',
  template: {
     layout: path.join(__dirname, '../lib/template.html'),
     engine: 'nunjucks',
  },
  dev: {
    cmd: 'roadhog server',
    port: '8000',
  },
};
```

- `资源映射` 是不是参考下 FIS 的作法，构建后的资源依赖表里面已经有 hash 了，如果 cdn 也只是构建期一个配置。

**Comment by popomore** [comment]
https://github.com/eggjs/examples/pull/52

**Comment by popomore** [comment]
devServer 的配置可以整合，templatePath 和 templateViewEngine 可以通过 render 传递，所以这个参数就不改了。

**Comment by fengmk2** [comment]
语雀的项目实际，window.context 会被各种 xss 攻击，最好输出的是 base64 字符串到页面，然后在 decode base64

```js
<script>window.context = base64Decode({{ helper.getAssetsContextBase64() }});</script>
```

**Comment by popomore** [comment]
> getScript 默认就返回 SafeString，就不需要加 safe filter 了。

非 nunjucks 就不行了，所以在模板层自己处理

**Comment by popomore** [comment]
> 语雀的项目实际，window.context 会被各种 xss 攻击，最好输出的是 base64 字符串到页面，然后在 decode base64

这个可以考虑，不过得提供一个前端的方法。

**Comment by yongbo000** [comment]
```js
class HomeController extends Controller {
  async render() {
    await ctx.render('index.jsx'); 
  }
 async render2() {
    await ctx.render('index2.jsx');
  }
}
```
上面的第一种单页的方式，是不是就只能指定一个模版（默认或是自定义）  
render想用模版1，render2想用模版2  是不是就不行了？

为啥要提供2种方式，其实我感觉 `模版+资源` 是可以满足所有需求了吧，对传统前端也更直观点。

**Comment by popomore** [comment]
> render想用模版1，render2想用模版2 是不是就不行了？

可以的，配置 templatePath 支持 config 和 viewOptions

```js
await ctx.render('index2.jsx', {}, { templatePath: 'xxx' });
```

> 为啥要提供2种方式

这个依赖于工具配置，比如 webpack 中自定义了 output 的 filename。这样原文件和生成的文件无法做出对应，如 index.js -> index.bundle.js。

其次可以兼容传统的模式，比如需要模板渲染加上 js。

**Comment by hubcarl** [comment]
- 从讨论来看，该插件是根据指定的 html模板，注入对应的 js 和 css依赖功能
- 在 `egg-view-vue-ssr` 和 ` egg-view-react-ssr` 的静态资源实现时，有很多相似的地方。我这边是通过 `webpack` 构建好 manifest.json 资源映射(包括publicPath支持）,  render后，根据文件名直接拿到依赖的 css和js，然后插入到 render后的html 中。 webpack 构建是单独的进程，所以也存在 proxy的过程。 目前支持 服务端渲染 和 前端渲染( 服务端渲染出html骨架和插入js，css依赖）

**Comment by hubcarl** [comment]
@popomore  @atian25  看了一下实现和相关讨论，目前该插件是根据指定的 html 模板，注入 initdata, 单个 js 和 单个css到html中,  适合 nunjucks 这类 前端渲染，manifest 可以考虑支持以下方式：

```js
 "category.js": {
      "js": [
        "/public/js/vendor.js",
        "/public/js/category.js"
      ],
      "css": []
    },
    "index.js": {
      "js": [
        "/public/js/vendor.js",
        "/public/js/index/index.js"
      ],
      "css": [
        "/public/css/common.css",
        "/public/css/index.css"
     ]
    }
}
``

**Comment by popomore** [comment]
这个 manifest.json 是源码和生产代码的映射，上面的这个文件感觉是给构建工具用的。
