### ISSUE TITLE
request.origin 为什么是服务的的详细url 而不是client的

### ISSUE THREAD

**Issue by daileimail** [eggjs/egg#1857]
如：
服务地址 localhost:7001
client: localhost:4200

request.origin 是localhost:7001 而不是localhost:4200 
求解答，这个坑很难过

**Comment by daileimail** [comment]
已解决 request.header.origin

**Comment by atian25** [comment]
ctx.href 还是 ctx.originUrl 应该就可以了，看下 koa 源码
