### ISSUE TITLE
Mock Model

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1863]
* **Node Version**:  v9.3.0
* **Egg Version**:  ^1.7.0
* **Plugin Name**:  egg-mock
* **Plugin Version**:  ^3.10.0
* **Platform**:  Ubuntu 16.04
* **Mini Showcase Repository**:

你好，我在做 `Service` 的单元测试的时候想到了一个问题，能不能 `mock model` 层

比如: 

```js
//  myservice.js
class MyService extends app.Service {
  find (filter) {
    //  do somethings
    return this.ctx.model.MyDb.find(filter);
  }
}
```

当我在测试这样一个service的时候，我自己使用的是 `egg-mongoose` ，我希望的是单元测试并不是实际的在数据库中写入数据，而是mock数据，所以我想问是否在 model 层有类似 `mock.mockService` 的 API能够实现我的需求，或者说我这种测试方式是不正确的，希望能得到解答，十分感谢。

**Comment by atian25** [comment]
自己加个 `app/extend/application.unittest.js` 然后在里面提供一个 `mockModel` 方法即可。
参考 https://github.com/eggjs/egg-passport/blob/master/app/extend/application.unittest.js

cc @XadillaX 在 model 那边也要考虑到这个。

**Comment by skyfore** [comment]
@atian25 OK，好的，我看看。谢谢

**Comment by atian25** [comment]
简单的话，也可以直接：

```js
const ctx = app.mockContext();
mock(ctx.model.MyDb, 'find', () => 'result');
```
就搞定了。

`mockModel` 只是对这个方法做了一次封装，语法糖而已。

**Comment by skyfore** [comment]
@atian25 OK , thanks!

**Comment by skyfore** [comment]
你好，请问假如我需要mock  service 应该怎么 mock，我发现我使用 `mock(ctx.service.test, 'get', 23333)` 然而并不会生效。

```js
//  app/controller/version.js
class VersionController extends Controller {
  async get() {
    const { ctx } = this;
    let versions;
    try {
      versions = await ctx.service.version.get();
    } catch (e) {
      ctx.errHandle(e);
      return;
    }

    ctx.body = versions;
  }
}

module.exports = VersionController;
```

```js
//  test
const { app, mock, assert } = require('egg-mock/bootstrap');

describe('#Test version', () => {
  it('#get()', async () => {
    const ctx = app.mockContext();
    mock(ctx.service.version, 'get', () => Promise.resolve(2333));
    const res = await app.httpRequest()
      .get('/version');
    assert(res.body === 2333);
  });
});
```

难道是不能mock ctx.service ?

**Comment by atian25** [comment]
`await ctx.service.version.get();`

`mock(ctx.service.test, 'get','xxx')`，`test` -> `version`

`app.mockService(service, methodName, fn)`
https://github.com/eggjs/egg-mock#appmockserviceservice-methodname-fn

**Comment by atian25** [comment]
喔，你是 `app.httpRequest` 的，这个不能 mock，因为 supertest 是一个端到端的请求。

**Comment by skyfore** [comment]
@atian25 那这个controller的单元测试应该怎么做呢？ 应该要把 serivce mock 掉才行的，要不然就相当于把 service 也给测了一遍了

**Comment by atian25** [comment]
被 @whxaxes 误导了，是可以 mock 的，看 https://github.com/atian25/egg-showcase/pull/5/files

**Comment by skyfore** [comment]
@atian25 确实是可以用了，多谢。这是不是意味着 mock('target', 'prop', value) 这个 API 不用了呢?

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mock/blob/master/app/extend/application.js#L74

自己看源码呗，只是多提供了一个语法糖而已。

**Comment by skyfore** [comment]
OK，thks !
