### ISSUE TITLE
app.js加载了多次，导致beforeStart执行了多次

### ISSUE THREAD

**Issue by dizhifeng** [eggjs/egg#1864]
npm run dev只会加载一次，而通过egg-scripts启动会加载多次，貌似固定8次

**Comment by atian25** [comment]
因为 `egg-bin dev` 是开发模式，只启动一个 worker。
而生产模式是 CPU 个数个 worker。

**Comment by Ailein** [comment]
@atian25 你好，能问下 如何在agent里面用Redis? 我是要在agent做 Redis的订阅

**Comment by atian25** [comment]
配置个 https://github.com/eggjs/egg-redis/blob/master/config/config.default.js#L7 就可以在 agent 上挂载 redis 了

**Comment by Ailein** [comment]
agent. redis ? 

谢谢！
