### ISSUE TITLE
egg-sequelize 的 migrate 文件必须自己手写吗?

### ISSUE THREAD

**Issue by justjoker** [eggjs/egg#1865]
* **Node Version**: 8.9.0
* **Egg Version**: 2.1.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.0
* **Platform**:
* **Mini Showcase Repository**:

我看了官方给的 examples ,里边的 package 里有下面三个命令
"migrate:new": "egg-sequelize migration:create"
"migrate:up": "egg-sequelize db:migrate"
"migrate:down": "egg-sequelize db:migrate:undo"

我在我的项目 app/model/ 下已经创建好了
```js
'use strict'

module.exports = (app) => {
  const { STRING, INTEGER, DATE } = app.Sequelize

  const TestModel = app.model.define('test', {
    uid: INTEGER,
    name: STRING,
    pay_type: INTEGER,
    card: STRING,
    mobile: STRING,
    type: INTEGER,
    city: STRING,
    address: STRING,
    created_at: DATE,
    updated_at: DATE
  }, {
    freezeTableName: true
  })

  return TestModel
}
```
这样的 model 
然后 我运行了
yarn run migrate:new
接着控制台输出了

$ egg-sequelize migration:create

Sequelize [Node: 8.9.0, CLI: 2.8.0, ORM: 4.28.6]

Successfully created migrations folder at "/Volumes/Mac/Projects/Node/***/migrations".
Error reading "node_modules/egg-sequelize/lib/database.js". Error: TypeError: Path must be a string. Received undefined

只生成了一个 migrations 文件夹 
里边没有任何文件.

**Comment by ZQun** [comment]
package.json改成这个就可以了
```
    "migrate:new": "node_modules/.bin/sequelize migration:create",
    "migrate:up": "node_modules/.bin/sequelize db:migrate",
    "migrate:down": "node_modules/.bin/sequelize db:migrate:undo",
```

**Comment by justjoker** [comment]
@ZQun 试了下 并不可行...

**Comment by justjoker** [comment]
config/config.default.js
内容类似下面这段
```js
module.exports = (appInfo) => {
 let config = {}
 config.sequelize = {
    dialect: 'mysql', // support: mysql, mariadb, postgres, mssql
    database: 'Test',
    host: 'localhost',
    port: '3306',
    username: 'root',
    password: '****'
  }

  return config
}

**Comment by justjoker** [comment]
我想我找到问题了...
const path = require('path')
我在 config.default.js 里引用 path 
```js
config.static = {
    prefix: '/public/',
    dir: path.join(appInfo.baseDir, 'app/public'),
    // support lazy load
    dynamic: true,
    preload: false,
    buffer: false,
    maxFiles: 1000
  }
```
还用了 appInfo
但是 在 egg-sequelize 的 lib/database.js 中 第 10行 和 第11行
```js
// FIXME: config init with function need send appInfo argument.
  if ((typeof config) === 'function') { config = config({}); }
```
config({}) 传了个空对象
导致我获取不到  appInfo.baseDir
所以报错..

**Comment by justjoker** [comment]
@atian25  这个问题可以解决吗?

**Comment by atian25** [comment]
这块 @XadillaX 统一看下吧，看是不是先 fix 下。

**Comment by popomore** [comment]
暂时改成 baseDir || ‘’

**Comment by acodercat** [comment]
@justjoker  我也出现了你的这个问题

**Comment by acodercat** [comment]
```js
  config.view = {
    defaultViewEngine: 'nunjucks',
    defaultExtension: '.html',
    root: [
      path.join(appInfo.baseDir, 'app/view'),
      // path.join(appInfo.baseDir, 'path/to/another'),
    ].join(',')
  }
```
我也在配置文件里面用了path，然后运行egg-sequelize 迁移的时候就报错

ERROR: Error reading "node_modules/egg-sequelize/lib/database.js". Error: TypeError: Path must be a string. Received undefined
