### ISSUE TITLE
使用egg-scripts部署应用时无法启动

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1866]
* **Node Version**:v9.2
* **Egg Version**:2.0.0
* **Plugin Name**:egg-scripts
* **Plugin Version**:2.5.0
* **Platform**:centOS
* **Mini Showcase Repository**:

**package.json**
```
"scripts": {
    "start":"egg-scripts start --daemon --sticky --port 7010",
    "stop": "egg-scripts stop"
  },
```
错误提示：
[egg-scripts] Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[egg-scripts]
[egg-scripts] Start got error, see /Users/liudong/logs/master-stderr.log（查看此文件时为空）

**Comment by atian25** [comment]
`egg-scripts start --ignore-stderr`

https://github.com/eggjs/egg-scripts#start

**Comment by atian25** [comment]
@popomore  `master-stderr.log` 为空？
