### ISSUE TITLE
service挂载问题，Ubuntu 16.04.3 LTS目录大小写敏感

### ISSUE THREAD

**Issue by 215566435** [eggjs/egg#1867]
* **Node Version**:v8.9.3
* **Egg Version**:2.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Ubuntu 16.04.3 LTS/Mac OS 10.12.6
* **Mini Showcase Repository**:

在```egg 2.1.0```的egg-core中，```service.js```
```javascript
directory: this.getLoadUnits().map(unit => path.join(unit.path, 'app/service')),
````
硬编码```app/service```在这里造成了一些问题，在我的```Mac OS 10.12.6```能够正确读取service并且挂载在```this.ctx.service.xxx```中，但是在服务器```Ubuntu 16.04.3 LTS```中，不能够正确挂载。

问题的原因就是因为**大小写问题**
下面是最小的问题实现代码

````javascript
const globby = require('globby')

const filepaths = globby.sync(['**/*.js'], { cwd: '/Users/***/Desktop/floveluy/build/app/service' });
console.log(filepaths);
````

- 我在Macos下的目录名是：app/Service，能够正确读取所有的service.
- 我在Ubuntu 16.04.3 LTS下目录名也是：app/Service，因为在那里是硬编码，所以就不能读取了。

**Comment by popomore** [comment]
请不要使用大写目录
