### ISSUE TITLE
egg-mysql where 语句的表达式支持的太差了

### ISSUE THREAD

**Issue by trelly** [eggjs/egg#1871]
egg-mysql 的query方法option中的where条件只支持=和in运算符，逻辑只支持and，连基本的where表达都没有支持到位，提供出来使用真的好吗~~,引用的rds库靠谱吗？？？ @huacnlee @yandongxu

**Comment by popomore** [comment]
查询建议自己写 sql

**Comment by trelly** [comment]
既然支持的不好，为什么不从文档里拿掉呢？文档还建议不要自己写SQL, 误导善男信女啊

**Comment by ngot** [comment]
@trelly 有想法，直接提PR

**Comment by fengmk2** [comment]
复杂查询想不懂为何要使用 where，即使是使用 ORM 方式，复杂查询都会直接手写 SQL 实现的。

**Comment by tiandaox** [comment]
@trelly rds内部也是用的npm/mysql库,只是封装了下.而且我在项目当中只对于=和in 这两种以及取自定义字段才使用option。其它的都是使用原生的参数化实现。
