### ISSUE TITLE
麻烦问下egg-sequlize的事务操作怎么写？

### ISSUE THREAD

**Issue by caiya** [eggjs/egg#1873]
看了下文档，讲的真是一笔带过啊，啥时候把插件的文档质量抓抓呗

**Comment by popomore** [comment]
官方文档很全 http://docs.sequelizejs.com/manual/tutorial/transactions.html

**Comment by caiya** [comment]
@popomore 官方文档有个sequlize.transaction，在eggjs里面怎么调用出sequlize而不是Sequlize呢

**Comment by popomore** [comment]
就是 app.model

**Comment by caiya** [comment]
了解了，建议写出来这些，要不新人找半天
