### ISSUE TITLE
egg-socket-io 的配置文档有误

### ISSUE THREAD

**Issue by zengwenfu** [eggjs/egg#1875]
文档对配置的说明：
exports.io = {
  init: { }, // passed to engine.io
  namespace: {
    '/': {
      connectionMiddleware: [],
      packetMiddleware: [],
    },
  },
  redis: {
    host: '127.0.0.1',
    port: 6379
  }
};

这其中 redis 恐怕不是必须，但是写在这里，很误导使用

**Comment by ngot** [comment]
具体哪一行文档？ 欢迎PR

**Comment by zengwenfu** [comment]
egg-socket-io 中的文档：https://github.com/eggjs/egg-socket.io 配置项：
其中 redis 的配置不是必须的，但是我也不是特别明白它的具体作用，不好提 pr

**Comment by liujinyang1994** [comment]
redis是用来做集群用的，这个可以具体查看socket.io的官网文档。这里面只是提供了配置方式，我个人觉得改不改都可以

**Comment by beeplin** [comment]
redis是socket.io的常用adapter，socket.io文档里有体现，只要懂socket.io就不会产生误导，应该不需要改吧。

**Comment by atian25** [comment]
https://github.com/eggjs/egg/pull/1913
