### ISSUE TITLE
egg-oss插件，请问上传如何判断文件是否已经存在了oss上面呢

### ISSUE THREAD

**Issue by phper-chen** [eggjs/egg#1878]
你好！
我看有个content-md5是做文件一致性校验的  但是egg-oss插件并未提到使用用法
求作者们解惑

**Comment by ngot** [comment]
具体用法应该到 sdk 提问：https://github.com/ali-sdk/ali-oss

**Comment by popomore** [comment]
内容和标题好像不是一个问题

**Comment by phper-chen** [comment]
我说的是egg-oss这个插件，不是ali-oss插件啊

**Comment by popomore** [comment]
作者很困惑，看不懂。如果只判断是否不在，发个 head 请求就好了
