### ISSUE TITLE
你们官网的指南写的很好，但是api写的也太残疾敷衍了

### ISSUE THREAD

**Issue by fuguohong** [eggjs/egg#1882]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by ngot** [comment]
能具体说一下，哪里不好吗，或者可以直接提PR来改进

**Comment by atian25** [comment]
jsdocs 这块吧，欢迎 PR 优化。

后面还是直接用 d.ts 就好了。
