### ISSUE TITLE
egg-socket.io的io.use()怎么使用？

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1883]
* **Node Version**: v9.3.0
* **Egg Version**: 2.0.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:4.0.2
* **Platform**:macOS
* **Mini Showcase Repository**:

socket的中间件(<code>io.use()</code>)怎么用，我想加入jwt的校验，能不能整合egg-jwt一起使用？

**Comment by ngot** [comment]
io.use 是 socket.io 的api不是 egg-socket.io 的，具体的去看 socket.io 的文档。

如果想使用中间件,看文档这里 https://github.com/eggjs/egg-socket.io#middleware
