### ISSUE TITLE
eggjs/examples/passport的示例没有账号密码登录吗

### ISSUE THREAD

**Issue by hudawen** [eggjs/egg#1884]

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/passport.html#%E4%BD%BF%E7%94%A8-passport-%E7%94%9F%E6%80%81

**Comment by atian25** [comment]
@OnedayLiu egg-passport-local 完成后顺便改下 example

**Comment by OnedayLiu** [comment]
@atian25 好的，我尽快改改

**Comment by 2015-lizaiyang** [comment]
1、egg-passport插件文档里没有这个app.passport.doVerify扩展方法，但是在**使用 Passport 生态**标题下的示例中有用到这个方法。
2、我有个建议，就是示例文档，能写的详细点吗? 对于小白看到上述文档直接会懵逼的，作者应该站在小白的立场上写文档，我按照**使用 Passport 生态**标题下的示例做，结果{name: 'AuthenticationError'
message: 'Unauthorized'}这种错误。
3、谢谢。

**Comment by 2015-lizaiyang** [comment]
1、egg-passport插件文档里没有这个app.passport.doVerify扩展方法，但是在使用 Passport 生态标题下的示例中有用到这个方法。
2、我有个建议，就是示例文档，能写的详细点吗? 对于小白看到上述文档直接会懵逼的，作者应该站在小白的立场上写文档，我按照使用 Passport 生态标题下的示例做，结果{name: 'AuthenticationError'
message: 'Unauthorized'}这种错误。文档的示例应用能独立运行的。而不是一下断断续续的代码。不然使用者会完全摸不着头脑。eggjs做的很棒，但是这个文档真是不敢恭维。
3、谢谢。

**Comment by w7699597** [comment]
用的一脸懵逼,这doVerify到底是干嘛的,我查了半天都没查到什么东西,文档能不能写的完整一点,至少注释一下吧

**Comment by atian25** [comment]
- 使用 egg-passport 的前提是需要熟悉 `passportjs` 的主要概念和流程
- `app.passport.verify` 这个是在第三方登陆返回的用户信息的处理上，如做第三方登陆绑定，譬如判断在你自己的数据库里面没有登记过该用户时，提醒他绑定手机号啥的，或者已经是你们的用户，则查询数据库返回你们自己的一些用户数据

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/passport.html#%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E5%A4%84%E7%90%86

这里不是文档写的很清楚么？ @w7699597

**Comment by HereSinceres** [comment]
@atian25  在controller中如何获取到经过app.passport.deserializeUser处理的用户信息
现象：在controller 中使用 ctx.user 获取到的是 app.passport.serializeUser（序列化存储到session中） 返回的信息【现在里面我放了一个用户id】。
期望：在controller中使用ctx.user获取到的是app.passport.deserializeUser返回的信息（在这里处理查询真实的userInfo【文档里是这样写的】）

**Comment by ShuBuShao** [comment]
> 1、egg-passport插件文档里没有这个app.passport.doVerify扩展方法，但是在使用 Passport 生态标题下的示例中有用到这个方法。
> 2、我有个建议，就是示例文档，能写的详细点吗? 对于小白看到上述文档直接会懵逼的，作者应该站在小白的立场上写文档，我按照使用 Passport 生态标题下的示例做，结果{name: 'AuthenticationError'
> message: 'Unauthorized'}这种错误。文档的示例应用能独立运行的。而不是一下断断续续的代码。不然使用者会完全摸不着头脑。eggjs做的很棒，但是这个文档真是不敢恭维。
> 3、谢谢。

请问 AuthenticationError 是什么原因, 我这边找了好久 找不到问题
