### ISSUE TITLE
egg-passport 中的verify()等钩子应该在哪里修改

### ISSUE THREAD

**Issue by xuzhanhh** [eggjs/egg#1886]
教程上写的是app.js。但是我们使用插件的时候并没有app.js

**Comment by atian25** [comment]
应用的 app.js 啊

**Comment by CHEN-DONG** [comment]
@atian25 想在verify()传入controller里面的方法怎么做啊

**Comment by atian25** [comment]
可复用的方法都在 service 里面

**Comment by CHEN-DONG** [comment]
@atian25 verify()的参数是个方法 可是传人verify()的方法必须是箭头函数 而service里面不能定义箭头函数 有什么办法解决么 比如说在类里面定义箭头函数

**Comment by CHEN-DONG** [comment]
@atian25  verify()只能写在app.js里面吗？

**Comment by thonatos** [comment]
```js
//  {ROOT}/app.s
app.passport.verify(async (ctx, user) => {
  ctx.logger.debug('passport.verify', user);
});
```

有了 `ctx`，就可以调用 `service` 了

参看链接： https://github.com/cnodejs/egg-cnode/blob/master/app.js
