### ISSUE TITLE
RESTful 风格的 URL 定义: 请问删除多个业务是没有设计自动对应的controller里方法的命名吗？

### ISSUE THREAD

**Issue by icxcat** [eggjs/egg#1887]
按照官网的RESTful URL约定，可以通过router.resources（）统一匹配到controller的方法
![image](https://user-images.githubusercontent.com/22029390/34367988-4a890652-eaeb-11e7-9aac-fd760c292f6a.png)
![image](https://user-images.githubusercontent.com/22029390/34368013-7ccdaeec-eaeb-11e7-80e5-b5aa736d5441.png)
现在我遇到的问题，比如删除多个，我设计的路由如下：
router.delete('/api/role', controller.role.removes) =>实现传入用户选中的要删掉的数组，一次性删除
Controller:
![image](https://user-images.githubusercontent.com/22029390/34368041-ce770298-eaeb-11e7-8b1c-092c6f3249e9.png)
Service:
![image](https://user-images.githubusercontent.com/22029390/34368053-e11f0422-eaeb-11e7-8c67-7111e674365b.png)

但接口测试  router.resources('role', '/api/role', controller.role)
http://localhost:7001/api/role DELETE  ID[]
无法自动对应到removes方法上。
![image](https://user-images.githubusercontent.com/22029390/34368073-15e128de-eaec-11e7-9da5-c70c9cd2fab2.png)

想知道是EGG没有设计删除多个这个业务所自动匹配的命名规则像图一表格中规定的那几个业务，还是我哪里写错啦！！！

**Comment by icxcat** [comment]
如果是没有设计如上传多个或删除多个 这样的匹配场景
路由共存也是可以的
router.delete('/api/role', controller.role.removes)
router.resources('role', '/api/role', controller.role)

**Comment by popomore** [comment]
这个没有特别标准的 api 设计，所以不做，你可以自己去扩展
