### ISSUE TITLE
有关agent.messenger.sendRandom(action, data)的问题

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1888]
* **Node Version**:9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:egg-redis
* **Plugin Version**:1.0.2
* **Platform**:CentOS
* **Mini Showcase Repository**:

**agent.js**
```
module.exports = agent => {
    agent.messenger.on('egg-ready', () => {
        agent.messenger.sendRandom('pullinfo', {event:'subscribe'});
    });
};
```
**app.js**
```
app.messenger.once('pullinfo', async (data) => {      
            const ctx = app.createAnonymousContext();
            await app.redis.get('c2').subscribe('systips');
            app.redis.get('c2').on('message', async (channel, data) => {
                if (channel === 'systips') {
                    ctx.runInBackground(async () => {
                        //调用往客户端推送信息
                       console.log(data);//服务器端只打印一条
                       ...................
                    })
                }
            })
        })
```
**package.js**
```
"scripts": {
    "dev":"egg-bin dev --sticky --port 7010"
}
```
我的理解是：agent.messenger.sendRandom对应是一个进程，那么订阅和监听也应该由同一个进程完成，当有发布事件时为啥客户端会收到多条同样的信息，不理，求指导〜

**Comment by popomore** [comment]
在 app 订阅 redis，那肯定每个 worker 都能收到。这个和 sendRandom 有啥关系？

**Comment by 89790094** [comment]
@popomore 明白了，如何在agent.js里订阅redis,也就是如何在agent.js里使用app和ctx?

**Comment by Ailein** [comment]
@89790094 配置个 https://github.com/eggjs/egg-redis/blob/master/config/config.default.js#L7 就可以在 agent 上挂载 redis 了

用agent.redis访问

**Comment by popomore** [comment]
这个感觉需要 redis 配置？如果多台服务器也会收多次？

**Comment by 89790094** [comment]
在agent.js下可以调用servcie服务吗？如果可以如何获取ctx?

**Comment by atian25** [comment]
`const ctx = app.createAnonymousContext();`

不要在 agent 里面做重操作，它只有一个进程。

**Comment by 89790094** [comment]
@atian25 在agent.js下可以调用servcie服务吗？

**Comment by 89790094** [comment]
@Ailein 谢谢，在agent.js下可以调用servcie服务吗？

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/34374455-2b8be22a-eb1c-11e7-8d89-34be85a0c1e3.png)
好像不可以

**Comment by atian25** [comment]
agent 上没有 service 的，不要在 agent 上做复杂的操作。

可以通过 messager 通知一个 worker 来做。

**Comment by 89790094** [comment]
@atian25 @Ailein 谢谢〜

**Comment by 89790094** [comment]
@atian25 可以通过 messager 通知一个 worker 来做:

**Comment by 89790094** [comment]
@Ailein 如何通过 messager 通知一个 worker 来做事？

**Comment by atian25** [comment]
agent 用 sendRandom， app 用 on

**Comment by Ailein** [comment]
文档有，https://eggjs.org/zh-cn/core/cluster-and-ipc.html，正如popomore 所说，集群就不行了，这个我也需求，不知道 有没什么好方案

**Comment by 89790094** [comment]
@atian25 @Ailein 十分谢谢〜〜
