### ISSUE TITLE
egg-socket-io插件next无法传入错误值

### ISSUE THREAD

**Issue by chenyulun** [eggjs/egg#1889]
* **Node Version**:9.1.0
* **Egg Version**:2.0.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:4.0.2
* **Platform**:macOS
* **Mini Showcase Repository**:
<code>io/middleware/jwt.js</code>
```javascript
const socketioJwt = require('socketio-jwt');
module.exports = () => {
  return async (ctx, next) => {
    // ctx.throw(401, 'No authentication token found\n');
    socketioJwt.authorize({
      secret: ctx.app.config.jwt.secret,
      handshake: true
    })(ctx, async (err, data) => {
      if (err) {
        // throw (err);
        next(new Error('Authentication error'));
        // ctx.socket.emit('res', `error:${err}`);
      } else {
        next();
        ctx.socket.emit('res', `connected succeed:${data}`);
      }
    });
  };
};
```

其实我想要执行官方的代码,试试能不能让ws链接失败：
```javascript
io.use((socket, next) => {
  if (socket.request.headers.cookie) return next();
  next(new Error('Authentication error'));
});
```
这里有一句很重要的代码就是<code>next(new Error('Authentication error'));</code>
初略的看了一下您的代码：<code>egg-socket.io/lib/connectionMiddlewareInit.js</code>
28行开始
```javascript
  composed(ctx)
    .then(next)
    .catch(e => {
      if (e instanceof Error) {
        e.message = '[egg-socket.io] connection middleware execute error: ' + e.message;
        debug('socket disconnect by: %s', e.message);
      } else /* istanbul ignore next */{
        debug('socket disconnect by: %s', e);
      }
      app.coreLogger.error(e);
    });
};
```
这里并没有传入io的next,而是传了一个<code>function next () {return dispatch(i + 1)}</code>
 也就是我代码里面执行<code>next(new Error('Authentication error'));</code>也是我没有机会执行io.use的next函数的
然后看到了then(next)是我最后的机会，我又发现我的middleware多添加了一个
```javascript
async () => {
    next();
    // after socket emit disconnect, resume middlewares
    await new Promise(resolve => {
      socket.once('disconnect', reason => {
        debug('socket disconnect by: %s', reason);
        resolve(reason);
      });
    });
  }
```
感觉没机会执行了next了，心凉了，有没有机会补救

**Comment by ngot** [comment]
中间件模型是按照 koa2 来设计的，建议去研究一下 koa2
然后，next 不是用来传值的，在 koa 中，ctx 是一切的核心，不管是往下传递值，还是响应请求，都要通过 ctx 来做。

**Comment by chenyulun** [comment]
就知道你用的是koa2的中间件方式，所以你为了兼容io.use加入了最后一个函数，手动执行了io.use的next,你并没有暴露出用户手动调用io.use的方法next，
我想知道我怎么给io.use报错

**Comment by ngot** [comment]
@chenyulun 我懂了。我觉得可以在中间件内部直接 throw Error ,然后，外部catch到，然后再把错误对象喂给原始的 next

**Comment by chenyulun** [comment]
你每次回答问题都是回复一句就直接关闭，不好，希望耐心点,谢谢！
看了你的代码，并没有机会执行原始 next
<img width="1193" alt="2017-12-27 1 10 25" src="https://user-images.githubusercontent.com/15979948/34371352-5ad1ba06-eb07-11e7-8c3c-7226a38305b7.png">

**Comment by chenyulun** [comment]
官方的io.use:：
```javascript
io.use((socket, next) => {
    console.log(socket.request.headers.cookie);
    return next(new Error('Authentication error'));
    // if (socket.request.headers.cookie) return next();
    // next(new Error('Authentication error'));
});
```
next抛出错误后前端websocket链接不会断开，io.origins就不会，

其实我想做的功能就是在io.use上面加个jwt的校验，校验过程中ws://一直挂起，校验成功通过，校验失败断开，类似io.origins功能

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/31

**Comment by chenyulun** [comment]
我去更新一下，测试一下

**Comment by ngot** [comment]
@bingqichen 能满足需求吗？我准备发版了、

**Comment by ngot** [comment]
@chenyulun 能满足需求吗？我准备发版了、

**Comment by chenyulun** [comment]
你先发吧，有问题再开新的issues，谢谢了

**Comment by ngot** [comment]
@chenyulun 已经可以跑了？

**Comment by chenyulun** [comment]
记得吧/egg-socket.io/lib/packetMiddlewareInit.js也处理一下

**Comment by chenyulun** [comment]
没发现可以捕捉错误的方法，现在只能通过链接之后同步判断是否登录，socket.isSuccess = !err;
校验失败：socket.emit('unauthorized', 'Authentication error');然后前端收到断开，后端也断开
校验成功：socket.emit('authenticated', 'Authentication isSuccess');

filter.js 通过 <code>ctx.socket.isSuccess</code>是否执行next进入路由
