### ISSUE TITLE
egg-doctools TODO list

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#1890]
- [x] 修复英语菜单的泰文问题
- [ ] 自动切换语言
- [ ] 支持「下一篇」
- [ ] 支持 TOC
- [x] 对应的语言的翻译不存在时，提供默认页，并显示默认语言的文档。

**Comment by popomore** [comment]
自动切换语言是指？

**Comment by atian25** [comment]
根据浏览器 `navigator.language` 自动切换

**Comment by popomore** [comment]
1. 当前文档的侧栏只展开父级
1. 侧栏选中项自动移到可见区域

**Comment by atian25** [comment]
侧栏是不是要支持三级好点，Controller 那章现在太长了

**Comment by popomore** [comment]
不是要加 TOC 了么

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/354

**Comment by atian25** [comment]
嗯，看 TOC 的样式是怎么样的吧，我看 nuxt.js 是直接分析出来显示在侧边栏的.

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/958

**Comment by popomore** [comment]
那侧栏就更长啦

**Comment by atian25** [comment]
『侧栏只展开当前文档所在的一级菜单』，仅在当前节点展开就好了

**Comment by fsiaonma** [comment]
或者参考云雀，侧栏只显示一级菜单，文章内的 TOC 放到右上方。但这个具体要看看 hexo 插件的 支持程度。

**Comment by popomore** [comment]
文档 TOC 就前端生成吧，遍历 H2

**Comment by popomore** [comment]
@atian25 我更新了下

**Comment by atian25** [comment]
改了啥？

**Comment by popomore** [comment]
上面有几个 check 了

**Comment by thonatos** [comment]
> https://antpress.eggjs.app/


@atian25 @popomore 

修了几个bug，各位大佬看看能切了没呗~

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/44790951-1c892800-abd3-11e8-90f3-801885d357dc.png)

https://antpress.eggjs.app/en/tutorials/index.html 里面的 url 不对

**Comment by fengmk2** [comment]
锚点信息没有出现 
![image](https://user-images.githubusercontent.com/156269/44791014-45a9b880-abd3-11e8-98cd-ecea2e8d5792.png)

**Comment by fengmk2** [comment]
代码语法高亮都没有了？

![image](https://user-images.githubusercontent.com/156269/44791071-670aa480-abd3-11e8-9f5d-5c670ee72767.png)

**Comment by fengmk2** [comment]
代码块里面的字体大小被修改成 12px了，按道理应该还是 14px 才对的。

![image](https://user-images.githubusercontent.com/156269/44791274-d41e3a00-abd3-11e8-8494-8a5f2e23f913.png)

**Comment by thonatos** [comment]
我记一下，晚上一起改了，

## TODO

- [ ] 代码高亮
- [ ] 锚点异常
- [ ] 样式异常
- [ ] 统计代码


## 资源

- https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css

**Comment by okoala** [comment]
我觉得样式可以在 vuepress 的基础上进行改进~

**Comment by Jeff-Tian** [comment]
自动切换语言的功能，我提了个 PR：https://github.com/eggjs/doctools/pull/43。请各位大佬帮忙看看哈。
