### ISSUE TITLE
egg-scripts start --sticky 启动工程，动态修改 public 目录下的 html 访问不会有更新

### ISSUE THREAD

**Issue by zengwenfu** [eggjs/egg#1891]
egg-scripts start --sticky 启动工程，
动态修改 public 目录下的 html 文件，再重新访问的时候不会有变化，应该是被缓存起来了，这个有办法破解么

**Comment by atian25** [comment]
跟 egg-scripts 关系不大，是 egg-static 插件，线上环境下，会默认 cache。

https://github.com/eggjs/egg-static/blob/master/config/config.prod.js#L5

不建议用 static 来做文件上传或更改啥的，因为去掉 buffer 后，每一次用户请求，都要读一次文件。

如果是动态文件，你应该放到 oss 或其他目录，自己管理。

**Comment by zengwenfu** [comment]
好的，先谢谢。
目前的需求是要根据用户的输入，动态的生成 html，相当于一次静态化的过程

**Comment by atian25** [comment]
如果你静态化后的内容有自己的缓存策略，那你可以不用 egg-static 的，存到其他目录或 oss 然后自己写个路由返回。

另外，存在本地目录，是无法支持集群多服务器的，这点要注意。

**Comment by zengwenfu** [comment]
这个提醒太关键了，非常感谢。
延伸一下，缓存在本机内存中的变量，在集群中是不是也不可靠，需要缓存到独立的redis中

**Comment by atian25** [comment]
另外还要注意一点，真实环境 prod 时，worker 是多进程的，cache 也会有问题。

**Comment by zengwenfu** [comment]
Egg的缓存方案一般是redis么？

**Comment by Fantasy9527** [comment]
还是想每次读取,每个进程都是访问最新的文件.我该怎么做呢?

**Comment by atian25** [comment]
自己读取 stream 返回给 ctx.body，不用放到 public 下。

**自己谨慎考虑这需求**

**Comment by Fantasy9527** [comment]
egg-static不管怎么配置,在生产环境下都会强制默认cache?

**Comment by atian25** [comment]
你可以在 config.prod.js 里面覆盖掉。
