### ISSUE TITLE
npm run test 的时候获取config信息的问题

### ISSUE THREAD

**Issue by nick-ma** [eggjs/egg#1892]
* **Node Version**: 8.0.0
* **Egg Version**: 2.2.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.0
* **Platform**: OSX
* **Mini Showcase Repository**: NULL

我在config目录下增加了 config.test.js 的配置文件，里面写上了连接postgreSQL数据库的dialect和服务器端口等信息。
由于不同的环境连接的数据库不同，所以这个配置没有在config.default.js里面写。
正常的开发和生产过程中是没有问题的，但是跑test case的时候就会报错，经过排查，就是跑test的时候没有读取到对应test环境的配置信息，导致sequelize默认去连接mysql数据库造成的。
我把数据库配置信息写到config.default.js里面，再跑test就能通过了。
我也尝试在跑test之前用环境变量来设定当前的运行环境为test，也是无效。
```sh
EGG_SERVER_ENV=test && npm run test-local
```

**Comment by atian25** [comment]
单元测试是 `config.unittest.js`

**Comment by nick-ma** [comment]
搞定，谢了！

**Comment by chenjianniu** [comment]
mark!
