### ISSUE TITLE
建议在 egg-init 后的工程目录中加入 .editorconfig 文件

### ISSUE THREAD

**Issue by huarse** [eggjs/egg#1893]
> 没有找到 egg-init 项目中 issue 入口，也没有找到模板文件，所以只能在这里提 issue 了

如题，由于经常在不同项目之间切换，不同项目之间的风格可能会有细微差别，但是目录所有主流IDE都支持 editorconfig 插件，所以希望 egg-init 在初始化时能在工程目录中加入 .editorconfig 文件

**Comment by popomore** [comment]
可以提 pr

**Comment by atian25** [comment]
`.editorconfig` 里面的内容写啥？跟 eslint 重复了么？

很多 IDE 不是可以根据 eslint 来格式化么？

**Comment by popomore** [comment]
是一个通用的配置，大部分编辑器都支持吧

**Comment by beeplin** [comment]
典型的.editorconfig:

```
[*]
charset = utf-8
indent_style = space
indent_size = 2
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
```

和eslint相比：editorconfig可以管理所有类型的文件，而不仅仅是eslint所能处理的特定类型文件；文字编码、行尾换行符等的设定好像也是eslint做不到的。一般来说团队项目肯定会扔一个.editorconfig进去的吧。即使框架不提供，倒是自己扔一个也不费事。

**Comment by atian25** [comment]
行尾换行符 eslint 支持的，编码不知道，但一般不都是 utf-8 么。

好像现在比较主流的是 prettier 根据 eslint 自动格式化，还有个把 eslint 转为 editorconfig 的 cli。
