### ISSUE TITLE
[RFC] 统计 egg 加载过程的各步骤的耗时

### ISSUE THREAD

**Issue by gxcsoccer** [eggjs/egg#1898]
* **Node Version**: N/A
* **Egg Version**: N/A
* **Plugin Name**: N/A
* **Plugin Version**: N/A
* **Platform**: N/A
* **Mini Showcase Repository**: N/A

**Comment by gxcsoccer** [comment]
可以考虑用 metrix 的思路来做

**Comment by gxcsoccer** [comment]
cc: @popomore

**Comment by atian25** [comment]
很早前有一个相关的：https://github.com/eggjs/egg/issues/421

**Comment by gxcsoccer** [comment]
- loader 的各大步可以统一加一下耗时
- 另外 loadFile 也可以加一下，这样有利于定位到具体的文件

**Comment by gxcsoccer** [comment]
然后可以设置一个性能基准，保证后续都控制在基准之下。 现在发现有些复杂的应用，启动加载的东西太多，可能导致超时

**Comment by ImHype** [comment]
我的理解是

**Comment by atian25** [comment]
@ImHype 可以直接开干的，实践后分享出来

**Comment by popomore** [comment]
如果只是加载过程不需要 metrix，不过到时可以把 loader 的数据给 metrix 来显示。

**Comment by ImHype** [comment]
@popomore metrics 主要还是统计系统运行时的状态，加载过程确实不太需要

**Comment by MiYogurt** [comment]
![image](https://user-images.githubusercontent.com/10082395/36834661-875080a0-1d6e-11e8-8080-addf2aa896c8.png)

`2018-03-01 16:32:18,552 INFO 40119 [master] agent_worker#1:40145 started (11056ms)`
`2018-03-01 16:32:47,560 INFO 40119 [master] egg started on http://127.0.0.1:7001 (40068ms)`

启动贼慢，难受啊。

**Comment by atian25** [comment]
@MiYogurt 做了啥... 你开下 loader 的 DEBUG 看看耗时在哪吧

**Comment by popomore** [comment]
在 egg-core 增加 app.timing API，主要给核心使用，但应用和插件也可以使用。

### API

```js
app.timing.start('name')
sleep(1000)
app.timing.end('name')
```

生成的数据

```json
[
  { "name": "name", "start": 1525542573797, "end": 1525542574797, "duration": 1000 }
]
```

### egg-core

- 新增 app.timing API
- 统计各类型 loader 时间，loadConfig/loadPlugin
- 统计加载文件时间，loadFile
- 统计异步完成时间，beforeStart

### egg

- dump 数据到 run 目录，每个进程单独 dump
  - run/agent_timing_pid
  - run/application_timing_pid

### egg-development

提供一个可视化页面，可以展现 trace 信息，如 http://jsfiddle.net/popomore/jbcggas6/12/embedded/result/

不过有个问题是，生产环境排查无法使用，这时可以使用工具将数据上报，单独平台做可视化。

**Comment by ImHype** [comment]
@popomore trace 日志收集吧，其实比较关心的是 koaContext 及后续 kcurl 的调用情况，不知道你们内部有做这块工作吗

**Comment by popomore** [comment]
这个后面会做 metrics 插件，和这个需求不一样。

**Comment by popomore** [comment]
opentracing 也会做 https://github.com/eggjs/egg/issues/39

**Comment by atian25** [comment]
@popomore 文档也加下吧？

- FAQ：为什么我的应用启动慢
- Plugin：为你的插件添加加载统计
