### ISSUE TITLE
egg用egg-scripts启动项目之后,会对静态目录进行缓存.

### ISSUE THREAD

**Issue by Fantasy9527** [eggjs/egg#1899]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

egg用egg-scripts启动项目之后,会对静态目录进行缓存.
我把spa页面的静态文件放在静态目录里.当在生产环境启动后,静态目录的页面更新.
浏览器刷新页面的时候,返回的页面有时候是新的,有时候是旧的.
但是在 dev环境下没有这样的问题.
请问是什么原因导致的,配置是否可以解决问题?

**Comment by Fantasy9527** [comment]
这是我view的配置.
```
    view: {
      defaultExt: '.html',
      cache: false,
      mapping: {
        '.ejs': 'ejs',
        '.html': 'ejs',
      },
    },
```

**Comment by atian25** [comment]
参见 https://github.com/eggjs/egg/issues/1891

有时旧有时新的原因是，prod 模式下，是多个 worker 的，先访问的被 cache 了。
