### ISSUE TITLE
关于开发插件有几个问题想请教

### ISSUE THREAD

**Issue by liujinyang1994** [eggjs/egg#1900]
* **Node Version**: v8.9.3
* **Egg Version**: v2+ 
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我目前需要基于几个第三方库开发一套egg的插件。
但是第三方库里面都是callback形式。
如果我想支持`async/await`。需要在每个方法外面套一层么？
有没有更好的办法或者参考的例子，谢谢。

**Comment by atian25** [comment]
没啥办法，只能实打实的把 callback 封装 promise 。

node8 有 `utils.promisify`

**Comment by liujinyang1994** [comment]
看来还是躲不过每个都要套一个层`promise`
