### ISSUE TITLE
请问蛋框架如何进行版本升级?

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#1902]
现在我们的系统已经部署很久了, 已经很旧了，想知道如何平滑的进行版本更新

**Comment by xinnian1992** [comment]
谢谢

**Comment by fsiaonma** [comment]
Egg@2 升级指南 http://www.eggjs.org/zh-cn/migration.html

FYI.

**Comment by atian25** [comment]
1. 用 `egg-init --type=simple` 看下最新推荐的结构
2. 看 http://www.eggjs.org/zh-cn/migration.html
