### ISSUE TITLE
this.app.mysql.literals.now没有被定义

### ISSUE THREAD

**Issue by whit15** [eggjs/egg#1905]
* **Node Version**: 9.2.1
* **Egg Version**: 2.0.0
* **Plugin Name**:  egg-mysql
* **Plugin Version**:  3.0.0
* **Platform**: MacOS 10.13.2
* **Mini Showcase Repository**: https://github.com/whit15/guess.git

<img width="938" alt="default" src="https://user-images.githubusercontent.com/9914116/34473544-32664b3e-efaf-11e7-9865-89f63eb06968.png">
如图，按照官网文档写法在使用this.app.mysql.literals.now时报错，显示now没有定义，请排查一下。
注释掉截图第35行代码可以正常更新数据库

**Comment by jtyjty99999** [comment]
没有重现 ，能否提供个代码仓库

**Comment by whit15** [comment]
仓库地址已更新到描述，拜托了

**Comment by atian25** [comment]
配置里面是 clients， 故 mysql 是多实例的。要 app.mysql.get 后才行吧

**Comment by atian25** [comment]
你都有 `app.db_guess = app.mysql.get('guess');` 了，对应的就是 `app.db_guess.literals` 咯

**Comment by whit15** [comment]
非常感谢
