### ISSUE TITLE
在config.default.js中配置Sequelize连接mysql，如何配置连接mysql的用户名密码是密文？

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#1907]
现在配置在config.default.js中的数据库连接，用户名密码是明文的。现在需要将用户名密码改成加密的。需要怎么配置？
 config.sequelize = {
        dialect: 'mysql', // support: mysql, mariadb, postgres, mssql
        database: 'test', 
        host: '127.0.0.1',
        // host: 'localhost',
        port: '3306',
        username: 'root',
        password: 'root',
    };

**Comment by atian25** [comment]
谁去解密？

如果只是单纯不想写着源码中，那用环境变量传递。

**Comment by jjackychen** [comment]
由程序新建数据库连接实例时解密，不可以？

**Comment by atian25** [comment]
关键是，你的目的是啥？你想保证什么的安全，你针对的是哪类人？

**Comment by jjackychen** [comment]
主要是配置文件中的用户名，密码会由其他人去配置，我们不想直接在配置文件中配置明文。我们想先加密好用户名密码，直接在配置文件上配置加密后的用户名和密码。

**Comment by atian25** [comment]
没明白，能看到加密后的密码的人，也能看到源码，也能启动源码，秒秒钟就能拿到解密后的密码。

**Comment by jjackychen** [comment]
客户有这个要求，配置文件不允许有明文密码

**Comment by atian25** [comment]
```js
const decrypt = require('../lib/your_fn');
config.sequelize = {
  password: decrypt('00aa23ss'),
};
```
