### ISSUE TITLE
从数据库读取的配置如何以key，value的形式保存到全局变量?

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#1908]
项目中原来一些写在config.default.js的配置现在要改成在数据库中配置。
程序要怎么才能在初始化的时候读取出来放在一个全局变量里？

**Comment by atian25** [comment]
beforeStart 里面读取后赋值给 `app.config` 即可。

不过要注意，多 worker 是多进程的，变量是不互通的，需要用 https://eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by DragWeb** [comment]
但是如果不改变变量的值，worker只做读取操作，就不影响了吧
