### ISSUE TITLE
有没有计划做rocketmq客户端的计划？

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#1909]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
目前没有，如果有对应的 koa 中间件的话，可以先用。

**Comment by luckydrq** [comment]
https://github.com/ali-sdk/ali-ons
