### ISSUE TITLE
npm run start启动egg项目给node传参数怎么弄呢？

### ISSUE THREAD

**Issue by ztiandan** [eggjs/egg#1910]
node --nouse-idle-notification--expose-gc--max-new-space-size=2048--max-old-space-size=8192

想用eggjs的npm run start启动项目，如何实现上面的参数来增加node可以使用的内存量呢？

**Comment by popomore** [comment]
node node_modules/.bin/eggctl start

**Comment by atian25** [comment]
dup: https://github.com/eggjs/egg/issues/1161 

现在可以先用 `NODE_OPTIONS` 或者 @popomore 的方式

**Comment by wuchuguang** [comment]
node: --expose-gc is not allowed in NODE_OPTIONS

**Comment by atian25** [comment]
try `--node-options--expose-gc`

https://github.com/node-modules/common-bin/blob/34cad2ad20781ec671bc8d7b846a1de1a1e3fc2a/lib/helper.js#L181

**Comment by minhthinhls** [comment]
> try `--node-options--expose-gc`
> 
> https://github.com/node-modules/common-bin/blob/34cad2ad20781ec671bc8d7b846a1de1a1e3fc2a/lib/helper.js#L181

This does not work when I use Node v14.16.0
My command:
> egg-bin --node-options--expose-gc dev

**Comment by atian25** [comment]
`egg-bin dev --node-options--expose-gc`

and you can check it by `console.log(process.execArgv)`
