### ISSUE TITLE
中间件中ctx调用不到service服务

### ISSUE THREAD

**Issue by 89790094** [eggjs/egg#1911]
* **Node Version**:9.2.0
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:CentOS
* **Mini Showcase Repository**:

```
module.exports = () => {
  return async function (ctx,next) {
    let data={...}
    await ctx.service.pub.add(data);
    await next();
  }
}
```
await ctx.service.pub.add(data);此名出错？
ctx.ip这些都是合适的

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by 89790094** [comment]
@atian25 https://github.com/89790094/middleware-ctx

**Comment by 89790094** [comment]
@atian25 仓库里是直接调用model,但也不可以

**Comment by atian25** [comment]
你不是在问 service 么?

**Comment by 89790094** [comment]
@atian25
都在用ctx去调用的，应该是一样的吧？

**Comment by 89790094** [comment]
model也无法调用a

**Comment by popomore** [comment]
首字母大写了

**Comment by 89790094** [comment]
@atian25 Cannot read property 'create' of undefined

**Comment by 89790094** [comment]
@atian25 
![image](https://user-images.githubusercontent.com/7735116/34511177-96974c44-f094-11e7-953d-2476f31db8ee.png)

**Comment by SunShinewyf** [comment]
拉了你的仓库，并在本地运行了一下，在中间件中使用model，没有报错呢？
我在你的代码基础上做了一些改动（因为运行时报错了）：
- install egg-cors(因为你在plugin.js中用到了，但是package.json中没有这个依赖)
- 添加路由
```js
'use strict';

module.exports = app => {
    app.get('/',app.controller.index.index);
}
```
- 修改了egg-moogoose 的配置（改为我本地的了）
- 修改了中间件中data的某个键值：

```js
module.exports = (options, app) => {
    return async function (ctx,next) {
        //访问日志
        let data = {
            uid: ctx.uid || '',
            uri: 'ddd',
            method: ctx.method,
            query: JSON.stringify(ctx.query) || '',
            params: JSON.stringify(ctx.params) || '',
            body: JSON.stringify(ctx.request.body) || '',
            agent: ctx.get('User-Agent'),
            ip: ctx.ip,
        }
        await ctx.model.MemberLog.create(data);
        await next();
    }
}

```
因为之前是ps,报错`ps is undefined`,所以我改为常量了

就上面几点运行的时候，没有报错信息，你本地的错误提示可以贴出来吗

**Comment by 89790094** [comment]
nodejs.TypeError: Cannot read property 'create' of undefined
at /Users/liudong/Dev/ke3/api/app/middleware/log.js:19:35

```await ctx.model.MemberLog.create(data);```
就是这行报错

**Comment by atian25** [comment]
@89790094 你新一个目录 clone 下你给的库试试能否复现。

**Comment by 89790094** [comment]
@atian25好的, 是不是npm i时模块安装的不对，，我再试下，谢谢

**Comment by 89790094** [comment]
![image](https://user-images.githubusercontent.com/7735116/34513968-e9312806-f0a5-11e7-8d04-c7892fbf6192.png)
还是一样的错误

**Comment by 89790094** [comment]
@atian25 把原来的模块删除又重新安装了一次，，还是一样的错误

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/34514291-add01c70-f0a7-11e7-9731-6c3b23146732.png)

无法复现，你自己找个干净的目录重新 clone，不要锁版本，不要用 yarn 试试。

**Comment by atian25** [comment]
你提供的代码库是无法运行的，缺少 `egg-cors` 依赖，而且多个 2 个 `,`。

**Comment by SunShinewyf** [comment]
哈哈，对，这是egg-eslint的问题，我忘记在上面提出来了

**Comment by 89790094** [comment]
@atian25 、@SunShinewyf谢谢，，还是太粗心了

**Comment by atian25** [comment]
@89790094 最后的问题是?

**Comment by 89790094** [comment]
@atian25 npm安装的模块不完全
