### ISSUE TITLE
egg-logger 是否有必要增加 category 以区分具体业务或模块

### ISSUE THREAD

**Issue by ImHype** [eggjs/egg#1912]
* **Node N/A**:
* **Egg N/A**:
* **Plugin egg-logger**:
* **Plugin N/A**:
* **Platform**:
* **Mini Showcase Repository**:

业务当中往往需要 category 字段做业务分类，而 log4j 也是支持这个设定的，我看到 egg 内有部分插件在 message 中人为通过 [egg-xxx] 做插件区分，是否有必要新增 `category` 设定，使用起来可以更优雅

**Comment by popomore** [comment]
logger 是比较通用的，你可以定义 format 来格式化输出，你也可以使用 write 方法完全自己来输出信息。
