### ISSUE TITLE
一个服务器跑多个egg程序有问题

### ISSUE THREAD

**Issue by Julyyq** [eggjs/egg#1918]
* **Node Version**:  v8.6.0
* **Egg Version**: v2.0.0
* **Platform**: ubuntu 16.04

同一个服务器上跑两个程序，一个用7001，另外一个用7002，然后我发现一个程序启动后，另外一个的进程就自动停掉了。

**Comment by atian25** [comment]
egg-scripts stop 会停止所有，需要加上过滤参数，具体看 https://github.com/eggjs/egg-scripts

建议通过 docker 来跑多个服务

**Comment by Julyyq** [comment]
thanks
