### ISSUE TITLE
关于egg-socket.io的sticky模式的疑问

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#1919]
我看到一个Issues(#1596 )说开启sticky 之后 socket请求都是同一个进程在处理，想确认下这部分是否如此，还是单纯的只在重连时采取粘性链接，正常的新链接会分摊到各个进程？

**Comment by thonatos** [comment]
可以看看下面两篇文章：

- https://socket.io/docs/using-multiple-nodes/
- https://github.com/indutny/sticky-session
