### ISSUE TITLE
egg-sequelize日志打印的问题

### ISSUE THREAD

**Issue by fuguohong** [eggjs/egg#1920]
原生的sequelize打印sql日志，输出中包含了事务的id。但是在egg-sequelize中使用的时候，仅仅输出的sql，没有输出事务id了。这样难以区分哪条sql属于哪个事务，做开发的时候也不方便排查相关问题。希望能够解决
  
因为没有显示事务的id。 开发的时候
model.create( entity , {transaction } )
写成了
model.create( entity ,transaction )

程序又不会报错，到时结果不对，找了两个小时的错。
如果输出的时候跟原生的sequelize一样的话，一眼就可以看到一条insert语句没有在事务中。 

原生sequelize输出格式如下
Executed ( default ): INSERT xxxxxxxxxxxxxxx
Executed ( asddksadj ): UPDATE xxxxxxxxxxxxxxx
egg-sequelize输出格式：
[model] INSERT xxxxxxxxxxxxxxx
[model] UPDATExxxxxxxxxxxxxxx

没有了Executed ( 事务id)。麻烦给个解决方案吧

**Comment by fuguohong** [comment]
我看了你们的源码，通过覆盖sequelize的log方法解决了这个问题。希望你们能把包做一定修改，修正没有事务id的问题。

**Comment by solarhell** [comment]
晒下解决方案？

**Comment by fuguohong** [comment]
@solarhell 
核心部分，就这么两行代码
  app.Sequelize.prototype.log = function() {
    if (this.options.logging === false) { return; }
    this.options.logging.info('[model]', chalk.magenta(arguments[0]), `(${arguments[1]}ms)`);
  };

**Comment by atian25** [comment]
欢迎 PR @fuguohong 

cc @XadillaX
