### ISSUE TITLE
动态创建多数据源问题

### ISSUE THREAD

**Issue by yumeiqiang** [eggjs/egg#1921]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

天猪老师你好，看了下底层createInstance的方法，貌似只接受一个mysqlconfig对象，现在我想动态创建两个mysql实例，mysql配置不写在config里面从远程加载，读写分离，这个具体用createInstance怎么处理

**Comment by yumeiqiang** [comment]
if (options.clients) {
      for (const id in options.clients) {
        this.clients.set(id, this.createInstance(options.clients[id]));
      }
      this.app[this.name] = this;
      return;
    }
createInstance(config) {
    // options.default will be merge in to options.clients[id]
    config = Object.assign({}, this.options.default, config);
    return this.create(config, this.app);
  }

**Comment by yumeiqiang** [comment]
`if (options.clients) {
for (const id in options.clients) {
this.clients.set(id, this.createInstance(options.clients[id]));
}
this.app[this.name] = this;
return;
}
createInstance(config) {
// options.default will be merge in to options.clients[id]
config = Object.assign({}, this.options.default, config);
return this.create(config, this.app);
}`

**Comment by yumeiqiang** [comment]
`
if (options.clients) {
      for (const id in options.clients) {
        this.clients.set(id, this.createInstance(options.clients[id]));
      }
      this.app[this.name] = this;
      return;
    }
`

**Comment by yumeiqiang** [comment]
```
if (options.clients) {
      for (const id in options.clients) {
        this.clients.set(id, this.createInstance(options.clients[id]));
      }
      this.app[this.name] = this;
      return;
    }
```

**Comment by yumeiqiang** [comment]
```
//这是在config里面配置clients字段
if (options.clients) {
      for (const id in options.clients) {
        this.clients.set(id, this.createInstance(options.clients[id]));
      }
      this.app[this.name] = this;
      return;
    }

createInstance(config) {
    // options.default will be merge in to options.clients[id]
    config = Object.assign({}, this.options.default, config);
    return this.create(config, this.app);
  }
```

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/mysql.html#%E5%8A%A8%E6%80%81%E5%88%9B%E5%BB%BA

**Comment by yumeiqiang** [comment]
这个例子是创建单个mysql数据源的吧

**Comment by yumeiqiang** [comment]
这个例子是创建单个mysql数据源的吧。

**Comment by yumeiqiang** [comment]
解决了，之前看这个动态写入文档陷入了死循环，执着于动态写入clientId,
其实只要在app上动态挂载两个mysql实例就可以，不需要在config.default.js配置什么clients

举个例子：
```
mysql1
app.database1 = app.mysql. createInstance(mysqlconfig1)
//在service中就用 
app.database1.query(sql)

mysql2
app.database2 = app.mysql. createInstance(mysqlconfig2)
//在service中就用 
app.database2query(sql)
```
