### ISSUE TITLE
配置中的自定义异常处理不起作用

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#1924]
* **Node Version**:  8.9.4
* **Egg Version**: 2.2.0
* **Plugin Name**: egg-onerror
* **Plugin Version**: 2.0.0
* **Platform**: Windows 10 X64
* **Mini Showcase Repository**:

// config/config.default.js
module.exports = appInfo => {
  const config = {};
  config.onerror =  {
    all(err, ctx) {
      ctx.body = 'error';
      ctx.status = 500;
    }
  };
  return config;
};

配置中的自定义异常处理不起作用，不管怎么设置还是会显示框架默认的500页面

plugin.js中开关onerror确认onerror插件是正常工作的

实在找不到什么原因？

**Comment by fsiaonma** [comment]
检查一下其他代码
重新 new 一个项目，把 config 改成你的配置，没问题的

![image](https://user-images.githubusercontent.com/1947494/34605266-ed8b97dc-f245-11e7-8024-eaa8687e2bf2.png)

![image](https://user-images.githubusercontent.com/1947494/34605328-23caea82-f246-11e7-8460-d630f3266309.png)

是否有 `config.local.js` 覆盖了，或者提供一下最小可复现代码。

**Comment by justinli0709** [comment]
@fsiaonma 

多谢回复。

没有config.local.js覆盖

有可能是低级错误导致，我再找一下原因。

**Comment by justinli0709** [comment]
其他所有配置都可以，就只有这个死活不生效

**Comment by dead-horse** [comment]
检查一下 `run/application_config.json` 和 `run/application_config_meta.json`，通过前者可以看到运行时的真实配置是什么，通过后者可以看到是从哪个文件中引入的，排查一下配置是否正确。

**Comment by justinli0709** [comment]
@dead-horse 好的，谢谢！ 我再排查看看

**Comment by justinli0709** [comment]
@dead-horse @fsiaonma 

多谢二位，问题已经解决，原因是我更新了egg到2.2版本，但是onerror插件还是1.5，

我重新更新到最新后正常了。

我想实现一个自定义的500页面，但是不希望使用errorPageUrl参数出错的时候URL发生跳转，
config/config.default.js中好像没办法像下面这么用
ctx.body = await ctx.renderView('/50x.nj')

**Comment by dead-horse** [comment]
此处不能调用异步了，如果要实现你的这个需求，实现一个中间件处理吧

**Comment by luoaz** [comment]
这块我也遇到了不起作用的情况了，我的情况是 环境变量【EGG_SERVER_ENV】是local，源代码里面有一句if (isProd(app)) {.....} ，isProd的源码如下
exports.isProd = function(app) {
  return app.config.env !== 'local' && app.config.env !== 'unittest';
};

所以如果想要自定义页面，那么首先环境变量不为local 和 unittest ，然后errorPageUrl 属性才会起作用。

我今天遇到了，在此分享下，有同样问题的就无需浪费时间了
