### ISSUE TITLE
Discussion： eggjs Agent进程允许访问数据库吗？

### ISSUE THREAD

**Issue by Genuifx** [eggjs/egg#1925]
这是一个功能讨论帖

agent进程理论上和一个worker进程没有差别？他应该具备其他worker的能力吧，包括已经挂载到mysql，但是从文档层面的确是看不出来怎么使用mysql（或者其他持续存储能力）

另外就是messenger的事件可以off掉吗？

![image](https://user-images.githubusercontent.com/10156994/34602922-b3c6cd4a-f23c-11e7-98ae-b508650c1b95.png)

具体场景： 有一个队列需要持久保存，同时因为有多个worker并发的读取队列，需要将这个队列处理逻辑放置到一个固定的进程执行，目前想放置到agent上面

不知道这个算不算issue，如果不好在issue提的话，又没有开发者论坛可以讨论呢？

**Comment by Genuifx** [comment]
@Ailein messenger的事件可以off掉吗？

**Comment by Ailein** [comment]
你是想messenger发出去要取消？

**Comment by fsiaonma** [comment]
首先，建议这种固定消费队列的都用第三方服务，例如 `kafka` `redis`。
因为一旦你把逻辑处理到 `agent` 上，就意味着你以后需要横向扩展机器会非常麻烦。

另外，`agent` 和 `worker` 都是 `master` 的一个子进程，但他们不完全相同，例如 `worker` 挂掉会重新 `fork` 一个出来， 而 `agent` 挂了就写下日志，整个应用停下了。 

如果一定要这样做，  建议先参考一下官网这2篇文章，整体了解一下  `master` 和 `agent` 和 `worker` 的关系 。
http://www.eggjs.org/zh-cn/core/cluster-and-ipc.html
http://www.eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by Genuifx** [comment]
@Ailein sry, 没有表达清晰，我的问题是messenger.on监听的事件是否有对应的messenger.off事件取消

**Comment by dead-horse** [comment]
> @Ailein sry, 没有表达清晰，我的问题是messenger.on监听的事件是否有对应的messenger.off事件取消

和 event 一样使用即可，removeListiner

**Comment by DragWeb** [comment]
hi, @fsiaonma ,你提到‘‘因为一旦你把逻辑处理到 agent 上，就意味着你以后需要`横向扩展机器会非常麻烦。`’’可以具体淡淡为什么吗？因为我也有类似的需求，对这里的坑不太了解。
