### ISSUE TITLE
获取上传的文件 在linux上要先获取文件才可以取到fields

### ISSUE THREAD

**Issue by chaoanweng** [eggjs/egg#1928]
* **Node Version**:8.9.4
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: 
* **Mini Showcase Repository**:

如题

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6
