### ISSUE TITLE
egg-static请求.mp3、.mp4文件异常

### ISSUE THREAD

**Issue by xiaocjin** [eggjs/egg#1932]
* **Node Version**:  8.9.3
* **Egg Version**:  2.2.0
* **Plugin Name**:  egg-static
* **Plugin Version**:  2.0.0
* **Platform**:  Mac
* **Mini Showcase Repository**:

用Chrome访问图片资源，显示正常
但是访问音频和视频文件的时候报错，“A client (undefined:NaN) error [EPIPE] occurred: write EPIPE”。
试了Express，访问资源是没有什么问题的，请问Egg的该怎么配置？

**Comment by dead-horse** [comment]
服务单断开了请求

**Comment by atian25** [comment]
https://github.com/eggjs/egg-static/pull/13
