### ISSUE TITLE
curl请求到nginx服务器，但目标的反向代理无法生效

### ISSUE THREAD

**Issue by HOTTIN** [eggjs/egg#1935]
* **Node Version**: v8.9.3
* **Egg Version**: v2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

 在使用eggjs框架时遇到如下的问题，
    我的测试环境
    /etc/hosts
    10.200.33.33 haha.ttt.com                        

    在代码中controller层向该地址请求数据
    ctx.curl('haha.ttt.com', opts);
    这里url是nginx服务器的域名，因为是测试环境，所以配置了hosts映射，但此时发出的请求，会返回404，
    感觉像是nginx反向代理无法生效

    直接在环境中使用curl命令去请求域名是可以代理成功的，
    但在代码中使用域名就会返回404，和curl直接请求IP是一样的情况，问题可能比较简单，望解答

**Comment by popomore** [comment]
用 http:// ？

**Comment by HOTTIN** [comment]
是的，http请求

**Comment by dead-horse** [comment]
@HOTTIN 让你用 curl 'htp://haha.ttt.com'

**Comment by HOTTIN** [comment]
额，是这样请求的ctx.curl('http://haha.ttt.com')，我前面没描述清楚

**Comment by HOTTIN** [comment]
代码里是这样用的，ctx.curl('http://haha.ttt.com', opts);
之前没有写完整
