### ISSUE TITLE
websocket连接数问题

### ISSUE THREAD

**Issue by ztiandan** [eggjs/egg#1936]
使用eggjs开发了个应用，创建大量websocket连接的目标server，但在建立连接打到1w左右，连接数就上不去了，优化了服务器的文件描述符数量，还是无效，请问大神node本身有这方面的限制吗？实在是找不到原因，程序也没用报错，我该如何排查呢？万分求回复。

CPU和内存使用率均低于30%

**Comment by JacksonTian** [comment]
请接入 https://node.console.aliyun.com/ 有数据才能继续解决问题。

**Comment by thonatos** [comment]
参考一下 issue：https://github.com/socketio/socket.io/issues/1393#issuecomment-32442188
