### ISSUE TITLE
使用typescript中拓展遇到问题

### ISSUE THREAD

**Issue by zengwe** [eggjs/egg#1940]
在egg的index.d.ts中interface Application 有可扩展的IController，在interface BaseContextClass中预留了IService，这个可以在app中什么controller和service，但是model却没有预留IModel接口，extend，middleware中还有些可能在全局app下挂载常量这个都没有可扩展的结构，所以要用typescript就要修改node_modules/egg/index.d.ts，很麻烦！

**Comment by okoala** [comment]
新的直接在你的 index.d.ts 声明不就可以了，为什么要跑到 node_modules 中~

**Comment by zengwe** [comment]
问题就是可以加上index.d.ts但是这个是（app: Application）=> {}这种 用的是app.mode，也就是添加在app这个全局变量了，而app的申明在egg/index.d.ts中 interface Application{}已经定死了，如果你在自己的文件夹下index.d.ts，
`import HomeController from './home';
declare module 'egg' {
  export interface Application{
    model: {
};
  }`
会覆盖egg/index.d.ts中的申明，也就是在别的地方用到app中会报错。
其实官方是考虑到了这个情况，但是只是留了controller、service，
`import HomeController from './home';
declare module 'egg' {
  export interface IController {
    home: HomeController;
  }
}`
在egg中的申明是这样的
`export interface Application extends EggApplication {
  /**
   * global locals for view
   * @see Context#locals
   */
  locals: any;

  /**
   * HTTP get method
   */
  get(path: string, fn: string): void;
  get(path: string, ...middleware: any[]): void;

  /**
   * HTTP post method
   */
  post(path: string, fn: string): void;
  post(path: string, ...middleware: any[]): void;

  /**
   * HTTP put method
   */
  put(path: string, fn: string): void;
  put(path: string, ...middleware: any[]): void;

  /**
   * HTTP delete method
   */
  delete(path: string, fn: string): void;
  delete(path: string, ...middleware: any[]): void;

  /**
   * restful router api
   */
  resources(name: string, prefix: string, fn: string): Router;

  redirect(path: string, redirectPath: string): void;

  controller: IController;

  Controller: Controller;
}`
现在知道为什么不能在自己的文件夹单独设置index.d.ts了吗，当然肯能我没找到好的解决办法，或者对typescript理解不够

**Comment by zengwe** [comment]
`export interface IController { } // tslint:disable-line`这是官方申明的IController接口，所以你在app/controller/index.d.ts申明的interface IController会出现在router中app.controller.home.index和别的地方用this.app.XXX时不会出现typescript报错

**Comment by okoala** [comment]
继承覆盖不行？ 你提供个示例仓库看看~

**Comment by shepherdwind** [comment]
感觉描述的不是很清楚，最好整理一下 markdown 文本格式。

**Comment by atian25** [comment]
@zengwe 不要挤牙膏似的交流，直接提供一个示例仓库。

**Comment by atian25** [comment]
feel free to reopen if more information is provided.

**Comment by Lizhooh** [comment]
@zengwe 先把 markdown 学好再说
