### ISSUE TITLE
egg中定时任务执行失败后会大量积压的问题

### ISSUE THREAD

**Issue by kobefaith** [eggjs/egg#1942]
前提：
1.定时任务中执行curl发请求。
2.程序运行中出现长时间断网。
现象：
1.网络恢复后，前面由于断网没有执行成功的定时任务会重新执行，导致短时间内发送大量请求（比如一分钟请求1万次）给其他服务器。对其他服务器造成较大负载压力。
期待的解决方案：
能不能设置定时任务，失败后直接结束本次执行，继续执行下一次。

**Comment by ZQun** [comment]
curl请求成功或失败，做个返回值，判断一下就好了

**Comment by atian25** [comment]
请提供可复现案例，当前的 egg-schedule 并没有重试机制的。

**Comment by atian25** [comment]
feel free to reopen if provided more information.
