### ISSUE TITLE
About an abstraction layer before Controller

### ISSUE THREAD

**Issue by fansenze** [eggjs/egg#1945]
does you have considered about `an abstraction layer` before `Controller`, like `Logic` in `Thinkjs`  
it can make code of validation in `Controller` decrease, and can make us write code for `sql query, deal with business logic, etc...` more comfortable, because the danger factor was intercepted before `Controller`

**Comment by atian25** [comment]
not any plan at Egg:
- **`Controller` is a layer which is used for parsing user input and send back the relative result after processing.**
- business logic is extract to `Service`
- Controller only do sth like: validation, view render, call services, it's simply enough.

if your validation code is too complex, you could consider to extract it to a special helper or validator.

and if you like, developer could extends your own layer by write a plugin to add your custom logic layer. (just using egg loader and middleware). to share with others.

btw, at some teams at alibaba, they're using `TypeScript Decorators` to simply the code, you maybe try it.

```js

class HomeController {
  @query(SOME_RULE)
  async index() {
    this.ctx.body = await this.user.get():
  }
}
```

**Comment by fansenze** [comment]
i think an layer for validation is better than `Decorator`, `Decorator` is also a an layer, but i think `Decorator` is suit for less validation in your project. if your have too much decorators, it would be an layer or a thing which is same to layer.
and i think an layer for validation only make the input more safety.
it doesn't matter that Egg not have any plan fo this. it is only a idea~
and i wonna know the some `plan` or `features` in Egg next, maybe i can make pr, because there is not any msg of project

**Comment by atian25** [comment]
@fansenze  as mentioned above,  you are welcome to write a plugin to provide this `validation layer rule`, then share with the community.

it maybe not to be a built-it layer of Egg,  cause it's not a common issue right now, **but surely to be a community layer**. just like `Decorator` which is also a validator layer practice of some team not a built-it.

can't wait to see your practice~
