### ISSUE TITLE
egg-redis 1.0.2不支持 set同时设置key的过期时间

### ISSUE THREAD

**Issue by albertyou2** [eggjs/egg#1948]
我去了ioredis github看到，目前ioredis 2.6.12 已经支持  set(lockName,'1','EX',1800);这样的语法了
但是egg-redis还不支持，因为貌似 egg-redis依赖是2.5.x的。请问什么时候egg-redis可以支持？

ps:setnx函数是否能也支持？

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-redis/blob/master/package.json#L16

会自动安装 2.x 的最新版本
