### ISSUE TITLE
为什么第二个定时任务执行特别慢，有demo案例吗？谢谢

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#1949]
为什么第二个定时任务执行特别慢，有demo案例吗？谢谢

**Comment by atian25** [comment]
应该是你提供可复现的代码库吧？

**Comment by xinnian1992** [comment]
原因我找到了，现在又出现新问题了，就是运行的时候定时器自动被killed，请问是什么原因？谢谢诶

**Comment by xinnian1992** [comment]
@atian25

**Comment by atian25** [comment]
我现在头很痛请问你能告诉我怎么了么？

请给出最小可复现仓库后，再开启。

**Comment by xinnian1992** [comment]
其实我也不知道怎么回事，本地测试正常，服务器上面定时任务就会挂掉，我先自己解决吧！ @atian25
