### ISSUE TITLE
egg中充满了各种delegate，想讨论一下这样的设计的优劣。

### ISSUE THREAD

**Issue by madinsect** [eggjs/egg#1950]
如题。
我其实不是很赞成有这么多的delegate，虽然某种程度上简化了代码，用起来灵活了。
但是也会一定程度上降低代码的一致性，对于egg本身而言，实现这些delegate似乎并没有什么意义。

**Comment by atian25** [comment]
具体指？

**Comment by madinsect** [comment]
例如 ctx.headers，ctx.request.headers；ctx.get()，ctx.request.get()

**Comment by okoala** [comment]
这是 koa 的啊~
