### ISSUE TITLE
 eggjs 是如何实现绑定域名的

### ISSUE THREAD

**Issue by lyh1091106900** [eggjs/egg#1951]
eggjs 是如何实现绑定域名的，求教，我在官网的文章中并没有看到相关描述，我想要把网站部署到windows服务器上

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/deployment.html#%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by ngot** [comment]
域名绑定，和egg框架没有任何关系 ，那是属于运维领域的事情，建议看看运维相关的资料。
