### ISSUE TITLE
egg-socket.io 请问如何在其他控制器中访问到socket对象？

### ISSUE THREAD

**Issue by xianglong111** [eggjs/egg#1952]
想实现推送功能，但是不知道怎么访问到socket对象？

**Comment by ngot** [comment]
什么是『其他控制器』，请按照模板提问，不然信息补全，无法解答的。

**Comment by xianglong111** [comment]
@ngot 您好！请问第三方调用链接，如何推送信息到客户端？通过route.js定义的get路由并不能访问到socket对象。麻烦了，这个困扰我两天了。谢谢

**Comment by ngot** [comment]
get 是 http 和 socket 完全是两个东西。不太明白你要做啥？

**Comment by ngot** [comment]
这个 issue 感觉漫无目的，也没有提供任何可判断信息，先关了。

**Comment by xianglong111** [comment]
应该是我描述不清楚，确实想实现推送功能，通过对外链接，推送信息到客户端，可是发现通过get路由的控制器不能访问到socket对象，也就没有推送信息给客户端

**Comment by duncup** [comment]
@xianglong111 
https://github.com/eggjs/egg-socket.io#controller
这个估计是你想要的

**Comment by xianglong111** [comment]
![tim 20180115090132](https://user-images.githubusercontent.com/9738743/34923057-17e6e880-f9d3-11e7-8cd8-0703c04bb2e0.png)
![tim 20180115090207](https://user-images.githubusercontent.com/9738743/34923058-18164224-f9d3-11e7-9a78-8fac1baa4288.png)
您好！是这样的，上面的图就是我这边想实现在route中配置一个GET，然后想通过HTTP访问到socket对象，推送相应的信息给客户端，但是确实是访问不到this.ctx.socket，这个问题确实一直困扰我，麻烦您了！

**Comment by ngot** [comment]
@xianglong111 http 和 socket 这两个概念搞混了。 这两个是完全不同的东西，这样可以使用『风马牛不相及』来形容。

建议，先补一下网络基础知识，然后再看看 socket.io 的文档，就知道怎么做了。

**Comment by xianglong111** [comment]
您好！这个是我使用express和socket.io搭建的一个小程序，就是按照这种方式实现的。我刚才也仔细看了所有的 Issues 发现很多人也都存在这个问题，指定客户端发送推送信息。

Express框架中路由使用Socket.io，以下三个步骤：
1、app.js文件添加
var io = require('socket.io')();
//事件监听
app.io = io;
io.on('connection', function (socket) {
console.log(socket.id);
    socket.emit('news', { hello: 'world',id:socket.id });
    socket.on('notifyNum', function (data) {
        console.log(data.msg_count);
    });
});
2、\bin\www文件中添加
var io = app.io;
io.attach( server ); 
 
3、路由中使用
var pushRouter = function(io) {
router.get('/:socketid', function(req, res, next) {
        //req.params.socketid 客户端socket唯一ID
        io.sockets.sockets[req.params.socketid].emit('message', {
        msg:'for your eyes only',
        id:req.params.socketid
                });
                res.end('success');
    });
return router;
};

**Comment by duncup** [comment]
@xianglong111 我这样理解对不对？
你希望暴露一个http接口，这个接口实现的是向指定socket.io客户端发起一次emit？

**Comment by xianglong111** [comment]
是的

**Comment by duncup** [comment]
那你的 `/chat/:id`的路由不要指向app.io.controller,你需要指向到app.controller下的控制器。
然后你看一下，io不出意外应该是挂载在app上了，看看能不能获取到socket.io对象。
如果获取到了，我想你知道怎么emit吧？

**Comment by xianglong111** [comment]
好的，谢谢

**Comment by duncup** [comment]
@xianglong111 最终结果如何？

**Comment by xianglong111** [comment]
@duncup 谢谢了，结果是能通过挂载io访问sockets， 这种方式 this.app.io.sockets.sockets[this.ctx.params.id].emit可以推送给指定id的客户端，但是还是访问不到socket对象，如果想做广播的话还是不行，我还没有找到方法。

**Comment by duncup** [comment]
你已经拿到io对象的话已经可以解决广播问题了啊，你可以去参考下socket.io的文档部分。
https://socket.io/docs/rooms-and-namespaces/#rooms

**Comment by xianglong111** [comment]
@duncup 好的，非常感谢！

**Comment by Mrlilili** [comment]
ts中直接调用app上的io会报错，app上面没有声明io，有什么解决方案可以解决？
![image](https://user-images.githubusercontent.com/8361655/63586536-122a2000-c5d4-11e9-9c0b-310469f7eefc.png)

**Comment by whxaxes** [comment]
@Mrlilili 看官方文档中的 ts 章节底部常见问题

**Comment by Mrlilili** [comment]
@whxaxes 项目中是有启用 egg-ts-helper ，但是还是会有这个报错的。

**Comment by whxaxes** [comment]
@Mrlilili  都说了让你看常见问题（ https://eggjs.org/zh-cn/tutorials/typescript.html#%E4%BD%BF%E7%94%A8%E4%BA%86-egg-%E6%8F%92%E4%BB%B6%E5%90%8E%E5%8F%91%E7%8E%B0%E6%B2%A1%E6%9C%89%E5%AF%B9%E5%BA%94%E6%8F%92%E4%BB%B6%E6%8C%82%E8%BD%BD%E7%9A%84%E5%AF%B9%E8%B1%A1 ）...

**Comment by Mrlilili** [comment]
@whxaxes 这个常见问题说明有看的。
egg-socket.io是有定义 d.ts 文件的。
ts常见说明问题文档中的说明是：
>egg 插件定义了 d.ts ，但是没有引入。 如果使用了 egg-ts-helper ，egg-ts-helper 会自动根据应用中开启了什么插件从而生成显式 import 插件的声明。


我的项目中就是开了egg-ts-helper还是会报错

**Comment by whxaxes** [comment]
@Mrlilili  给个能稳定复现的 repo 提 issue 吧

**Comment by Mrlilili** [comment]
@whxaxes  
问题复现仓库 https://github.com/Mrlilili/ts-error-demo

复现代码位置 https://github.com/Mrlilili/ts-error-demo/blob/b30bf05fef917431e30375d149e00bb3179569ff/app/service/Test.ts#L14

![image](https://user-images.githubusercontent.com/8361655/63631535-ab504980-c65b-11e9-9ae4-469057dfc656.png)

**Comment by whxaxes** [comment]
@Mrlilili  你现在这个截图就是另一个问题了 .... 不是已经有 io 这个属性了么 ...

**Comment by Mrlilili** [comment]
@whxaxes 这个问题是什么原因呢？

**Comment by Mrlilili** [comment]
@whxaxes 原先没有io属性的问题是没有声明app类型的原因造成的，改正了下，就报了这个错误

**Comment by Mrlilili** [comment]
> @Mrlilili 你现在这个截图就是另一个问题了 .... 不是已经有 io 这个属性了么 ...

io上好像是没有这个sockets属性

**Comment by ngot** [comment]
@Mrlilili socket对象是连接后才会创建的，每个连接对应一个。而 io 是服务器的全局对象，在服务器一启动，就存在了。他们是两个不同的概念。可以参考下 https://github.com/eggjs/egg-socket.io/blob/master/test/fixtures/apps/socket.io-async/app/io/controller/chatAsyncClass.js#L10 ，socket 对象在 egg-socket.io 里面被封装在了 ctx 里面，因为 ctx 是对请求的封装。

**Comment by ngot** [comment]
> @Mrlilili socket对象是连接后才会创建的，每个连接对应一个。而 io 是服务器的全局对象，在服务器一启动，就存在了。他们是两个不同的概念。可以参考下 https://github.com/eggjs/egg-socket.io/blob/master/test/fixtures/apps/socket.io-async/app/io/controller/chatAsyncClass.js#L10 ，socket 对象在 egg-socket.io 里面被封装在了 ctx 里面，因为 ctx 是对请求的封装。

仔细又看了一下，发现是要拿 `sockets` 对象。看了一下定义文件 https://github.com/eggjs/egg-socket.io/blob/master/index.d.ts#L21 ，发现 `sockets` 漏掉了，需要添加一下，才能在 ts 下获取到。

**Comment by Mrlilili** [comment]
@ngot 已解决。 egg-socket.io项目你们会发个版本更新下把依赖挪到dependencies中么？
