### ISSUE TITLE
plugin怎么区分prod和local

### ISSUE THREAD

**Issue by zoulux** [eggjs/egg#1953]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

有个plugin我想在线上环境启用，开发环境不启用

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/plugin.html#%E6%A0%B9%E6%8D%AE%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE

**Comment by zoulux** [comment]
@atian25 谢谢
