### ISSUE TITLE
写 egg 插件遇到 addSingleton的 creator 不执行的问题

### ISSUE THREAD

**Issue by onweer** [eggjs/egg#1955]
* **Node Version**: 8.9.3
* **egg Version**: 2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac OSX 10.12.3
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/11755669/34859076-08c5d816-f78f-11e7-8f71-a0ef62439d90.png)

**Comment by atian25** [comment]
你有调用 `app.nodemailer` 么？

**Comment by onweer** [comment]
找到了。
![image](https://user-images.githubusercontent.com/11755669/34862549-01844788-f7a6-11e7-81a6-a0e3af2d9db9.png)

直接调用 create 方法就可以了吗？

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/advanced/plugin.html#%E5%85%A8%E5%B1%80%E5%AE%9E%E4%BE%8B%E6%8F%92%E4%BB%B6%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

**Comment by ddzyan** [comment]
这个问题最终解决方案是在使用的时候创建，这是正常操作吗？文档中也没有具体说明如何解决这个问题吧
```
// app.js
module.exports = app => {
  app.transporter = app.nodemailer.create(app.config.nodemailer, app);
};
```
