### ISSUE TITLE
关于egg-redis如何进行对list、hash等其他数据类型的操作，目前只看到了set和sadd的方法。急求！

### ISSUE THREAD

**Issue by h-handy** [eggjs/egg#1956]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by solarhell** [comment]
https://github.com/luin/ioredis

**Comment by h-handy** [comment]
@solarhell 我自己的问题，自己对错误信息理解错了。已经解决了。
