### ISSUE TITLE
how to use epilogue with egg.js

### ISSUE THREAD

**Issue by anuxs** [eggjs/egg#1962]
epilogue is Create flexible REST endpoints and controllers from Sequelize models in your Express or Restify app.
https://github.com/dchester/epilogue

With Express , I can do like this

`// Initialize server
  const express = require('express'),
      bodyParser = require('body-parser');
  let app=express();
  app.use(bodyParser.json());
  app.use(bodyParser.urlencoded({extended:false}));
  let server=http.createServer(app);

  // Initialize epilogue
  epilogue.initialize({
    app: app,
    sequelize: database
  });

  // Create REST resource
  let userResource = epilogue.resource({
    model: User,
    endpoints: ['/googles', '/googles/:id']
  });

  // Create database and listen
  database
    .sync({ force: true })
    .then(function() {
      server.listen(function() {
        let host = server.address().address,
            port = server.address().port;
        console.log('listening at http://%s:%s', host, port);
      });
    });`

How to initialize epilogue and create REST resource in egg.js ?

**Comment by atian25** [comment]
if `epilogue` had koa plugin, then you could just use it.

https://github.com/dchester/epilogue/issues/100

or maybe you had to write one.

**Comment by anuxs** [comment]
i had try what your said with koa ,and also get an error info . this issue was created by me :
https://github.com/dchester/epilogue/issues/229
app[self.method] is not a function
