### ISSUE TITLE
使用egg-socket.io出现跨域的问题

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#1963]
使用egg-socket.io出现跨域的问题，但是其他的http请求都没有这样的问题，求解
这是socket涉及到的设置代码：

```
  config.io = {
    redis: {
      host: ipRedis,
      port: 7000,
      auth_pass: '',
      db: 15,
    },
  };

  config.cors = {
    credentials: true,
    origin: '192.168.5.222',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH',
  };

  config.security = {
    domainWhiteList: [
      // 'http://58.215.141.135:8080',
      'http://192.168.5.222:4200',
    ],
    csrf: {
      enable: false,
      ignoreJSON: true,
    },
  };

```
![image](https://user-images.githubusercontent.com/3679798/34929366-719003be-f9fe-11e7-84cd-a4982fb6d470.png)

* **Node Version**:
`v8.9.3`
* **Egg Version**:
`"egg": "^2.1.0"`
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by thonatos** [comment]
`socket.io` 默认不限制 `origins`，能否补充说明一下


- https://github.com/socketio/socket.io/blob/master/docs/API.md#serveroriginsvalue

**Comment by ngot** [comment]
看起来像是这个 https://github.com/eggjs/egg-socket.io#nginx-conf 没有配。

不过从已提供的很有限的信息中，还是无法确切判断。

**Comment by atian25** [comment]
先关了，补充信息后可以再次开启。
