### ISSUE TITLE
开发环境是否需要强制启用 eslint 检查代码风格

### ISSUE THREAD

**Issue by iaaronxie** [eggjs/egg#1971]
开发环境中执行 `npm run dev` 时，是否有选项可以启动 `eslint` 检测代码风格，如果检测不通过，不给继续运行代码。

在文档中好像只是说明 `npm run lint` 可以检测代码，希望 `npm run dev` 本身也可以启用。

**Comment by atian25** [comment]
自己修改 package.json 的 `npm scripts`

**Comment by iaaronxie** [comment]
自己修改 `npm scripts` 的意思是将 `egg-bin dev` 改成 `npm run lint && egg-bin dev` ? 其实我上面的意思是如果代码风格出错后不给继续运行代码，报错，但是能持续监听代码变动。

**Comment by atian25** [comment]
喔，持续的 eslint watch 啊，这个没计划支持。

一些思路：
- 继承 egg-bin 封装一个自己的上层工具，然后在 dev 的 run 方法里面，监听 reload 事件来调用 eslint
- 直接在 agent.js 里面，监听 reload 事件，判断 env 是 local 的时候，调用 eslint。（这段逻辑也可以封装为一个 egg 插件）
