### ISSUE TITLE
controller成员方法名和内部对象重名时会出现问题

### ISSUE THREAD

**Issue by hujiulong** [eggjs/egg#1972]
如果这么定义一个controller
```javascript
// app/controller/test.js
class TestController extends Controller {
  async config() {
    // ...
  }
}
```
然后定义router
```javascript
// app/router.js
module.exports = app => {
  const { router, controller } = app;
  router.get('/test', controller.test.config);
};
```
然后访问/test，结果是404

当Controller的方法名为`config`，`service`这些，就会出现这样的问题

如果在router.js里打印`controller.test.config`，看到的结果和其它方法也没有区别，开发者可能很难发现这个问题。

我建议在文档写明不能用这些方法名，或者在开发时，使用这些方法名就会报错。

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/controller.html

config / service / ctx / logger 这些都是 Controller 基类上挂载的成员属性，文档里面有提到。
