### ISSUE TITLE
d定时任务报错，下面是报错信息，我看不懂，求指点迷津！谢谢..

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#1975]
018-01-17 10:28:31,269 ERROR 17736 nodejs.JSONResponseFormatError: [egg-schedule] /root/crs/moho_crs/app/schedule/send_msg.js excute error. Unexpected token < in JSON at position 0 (data json format: "<html>\r\n<head><title>404 Not 

Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.2</center>\r\n</body>\r\n</html>\r\n"), GET http://127.0.0.1/notice/noticeSend 404 (connected: true, keepalive socket: 

false, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"127.0.0.1:80:":1},"requests":{}})
headers: {"server":"nginx/1.10.2","date":"Wed, 17 Jan 2018 02:28:31 GMT","content-type":"text/html","content-length":"169","connection":"keep-alive"}
headers: {"server":"nginx/1.10.2","date":"Wed, 17 Jan 2018 02:28:31 GMT","content-type":"text/html","content-length":"169","connection":"keep-alive"}
    at JSON.parse (<anonymous>)
    at parseJSON (/root/crs/moho_crs/node_modules/urllib/lib/urllib.js:913:24)
    at /root/crs/moho_crs/node_modules/urllib/lib/urllib.js:692:23
    at decodeContent (/root/crs/moho_crs/node_modules/urllib/lib/urllib.js:532:14)
    at IncomingMessage.<anonymous> (/root/crs/moho_crs/node_modules/urllib/lib/urllib.js:673:7)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'JSONResponseFormatError'
data: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.2</center>\r\n</body>\r\n</html>\r\n'
path: '/notice/noticeSend'
status: 404
headers: { server: 'nginx/1.10.2', date: 'Wed, 17 Jan 2018 02:28:31 GMT', 'content-type': 'text/html', 'content-length': '169', connection: 'keep-alive' }
res: { status: 404, statusCode: 404, headers:  { server: 'nginx/1.10.2', date: 'Wed, 17 Jan 2018 02:28:31 GMT', 'content-type': 'text/html', 'content-length': '169', connection: 'keep-alive' }, size: 169, aborted: false, rt: 8,

keepAliveSocket: false, data: '<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor="white">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.10.2</center>\r\n</body>\r\n</html>\r\n', requestUrls: [

'http://127.0.0.1/notice/noticeSend' ], timing: null, remoteAddress: '127.0.0.1', remotePort: 80 }
pid: 17736
hostname: iZwz9j5laf0esa5qp6wvpdZ

**Comment by popomore** [comment]
你请求返回 404，而且非 json
