### ISSUE TITLE
部署后请求图片404

### ISSUE THREAD

**Issue by hudawen** [eggjs/egg#1976]
报错 `GET http://localhost:7001/logo.png 404 (Not Found)`，如何配置能将图片请求路径改为`http://localhost:7001/public/logo.png`

**Comment by popomore** [comment]
图片路径要看你怎么引用吧，在你引用的地方改

**Comment by atian25** [comment]
跟部署不部署没哈啥关系。
自己写个 router 或看 egg-static 文档。
