### ISSUE TITLE
Middleware Unit Test

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#1981]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问官方有提供 middleware 的单元测试例子吗？我在官网文档上并未查找到相关的文档。
> https://eggjs.org/zh-cn/core/unittest.html

**Comment by atian25** [comment]
就正常那样测试咯，有什么问题么？

**Comment by skyfore** [comment]
比如我的业务是这样的

```js
//  app/router.js

const test = app.middleware.test(options);
router.get('/test', test, 'controller1', '...');
```

那假如我直接在测试中:

```js
//  test/app/middleware/test.test.js
app.httpRequest('/test');
```

这样不是就不仅测试middleware， 并且还涉及到 controller 层的逻辑了。
我以为会是像 Service 那样进行测试。

**Comment by skyfore** [comment]
或者说 middleware 的测试一直就是和 controller 结合在一起的吗？

**Comment by atian25** [comment]
真想测试的话，办法还是不少的：

关键问题在于 Controller 注册到 Router 后，要 mock
- mock controller （要看下 koa-router 源码，因为 Controller 注册到 Router 后，再 mock app.controller 已经晚了，可能要 mock router 对象里面的值）
- 在 test 里面声明额外的 router，特殊的 Controller 挂载这个 middleware 然后测试。
- 直接 app.middleware.xx(options, app) 这种方式来实例化，然后调用测试。

**Comment by skyfore** [comment]
@atian25  hello, 请问我的 router 是这样的，假如我想测 controller1 ， 我能 mock 掉 middleware test 吗？

```js
//  app/router.js

const test = app.middleware.test(options);
router.get('/test', test, 'controller1');
```

**Comment by atian25** [comment]
在 test 里面声明一个 `router.get('/testxxx', 'controller1');` 来测试咯

**Comment by skyfore** [comment]
@atian25 OK,thanks

**Comment by skyfore** [comment]
@atian25 好像不行，不知道我是否写得正确

```js
beforeEach(() => {
  const { router, controller } = app;
  router.get('/test/xxxx', async (ctx, next) => ctx.somekey = 2333, controller.index.get);
})
afterEach(mock.restore);

it('test', async () => {
  const res = app.httpRequest()
    .get('/test/xxxx');

  //  test controller
});
```

**Comment by atian25** [comment]
`async (ctx, next) => ctx.somekey = 2333` 没有 await next 啊

**Comment by skyfore** [comment]
@atian25  哦，对，我刚才写的时候忘记加上了，但是我在本地测的时候问题不是这个，是
```
Error: Can't find router:test/xxxx, please check your 'app/router.js'
```

**Comment by atian25** [comment]
https://github.com/atian25/egg-showcase/compare/test-controller?expand=1

自己多试试吧。

**Comment by skyfore** [comment]
@atian25 恩，我刚才把这个最小的例子放到我的测试里面发现不报错 :cry: . 十分感谢。
