### ISSUE TITLE
app.config中的字符串会自动转义？

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#1982]
* **Node Version**:9.2.1
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我在config.default.js中声明的一个配置:
config.shareUrl = 'http://qr.liantu.com/api.php?&w=280&text=';

输出时变成了'http://qr.liantu.com/api.php?&amp;w=280&amp;text='

请问该如何解决?谢谢~

**Comment by Cheese-Yu** [comment]
看了一下是egg-view-nunjucks渲染模板的时候对字符串进行了转义。请问有什么方法可以渲染模板的时候不对变量进行转义吗？

**Comment by Cheese-Yu** [comment]
在config.default.js中添加下面的配置，可以让模板不自动转义。
  config.nunjucks = {
    autoescape: false,
    throwOnUndefined: false,
    trimBlocks: false,
    lstripBlocks: false,
    cache: true,
  };

**Comment by atian25** [comment]
去看下 nunjucks 语法，用 `|safe`

关闭 `autoescape` 的话，自己承担风险。
