### ISSUE TITLE
egg.js怎么在捕获到异常的情况下重启egg服务

### ISSUE THREAD

**Issue by nlove518** [eggjs/egg#1983]
在中间件捕获异常后，怎么通过代码重启egg服务?启动egg服务的代码怎么写？

**Comment by atian25** [comment]
捕获异常后为啥要重启？

**Comment by nlove518** [comment]
@atian25 因为之前遇到timeout的问题 重启之后服务才能恢复正常。 所以想通过捕获timeout 错误，让服务重启。

**Comment by atian25** [comment]
关键还是那个问题，为啥 timeout 了，看那边的 issue，貌似官方也没法复现？

想重启就 `process.exit()` 杀掉自己。
