### ISSUE TITLE
egg-ons  阿里云ons  消息队列 HTTP 协议将于 2018.04.01 下线问题

### ISSUE THREAD

**Issue by Quinton** [eggjs/egg#1984]
https://help.aliyun.com/document_detail/61438.html?spm=5176.doc29532.6.604.D0uujO

请问，egg-ons 能兼容阿里云[mns](https://mns.console.aliyun.com)服务吗？  我看到你们一直维护。

**Comment by Quinton** [comment]
@gxcsoccer   @denghongcai

**Comment by JacksonTian** [comment]
你需要什么接口？我在维护 https://github.com/aliyun/mns-nodejs-sdk

**Comment by JacksonTian** [comment]
mns 跟 ons 基本上是两个东西。

**Comment by stonegithubs** [comment]
@JacksonTian  http://doxmate.cool/aliyun/mns-nodejs-sdk/api.html这个地址打不开，请问在egg里如何接收消息

**Comment by JacksonTian** [comment]
@stonegithubs 参见 https://github.com/aliyun/mns-nodejs-sdk/blob/master/test/client.test.js#L175
