### ISSUE TITLE
用anngular4改'Content-Type', 'application/json' 提交回返回图片这个参数 ，egg那边好像收不到请求，不改的话egg能收到，但是提交值为空

### ISSUE THREAD

**Issue by cswww** [eggjs/egg#1985]
![2018-01-18 5 55 08](https://user-images.githubusercontent.com/30970064/35091874-d09b6598-fc78-11e7-939f-89244cf93c52.png)
constructor(public http: HttpClient) { }
aaa() {
this.http.post(
      'http://localhost:7001/loginTwo',
      JSON.stringify(bbbbbbbb),
      {
        headers: new HttpHeaders().set('Content-Type', 'application/json')
      }
      )
      .subscribe((res) => {
        alert('ok' + JSON.stringify(res));
      }, err => {
        alert('err' + JSON.stringify(err));
      });
}

**Comment by cswww** [comment]
![2018-01-18 6 06 47](https://user-images.githubusercontent.com/30970064/35092446-617f6db0-fc7a-11e7-8e0a-33f5f96c5e32.png)
不改'Content-Type', 'application/json'egg的样子

**Comment by atian25** [comment]
自己检查下 devtools network

**Comment by cswww** [comment]
![2018-01-18 6 23 44](https://user-images.githubusercontent.com/30970064/35093247-ce4f61be-fc7c-11e7-8eeb-9d5a923954e0.png)
找到了 确实 头部'Content-Type', 'application/json'没加上来
![2018-01-18 6 25 31](https://user-images.githubusercontent.com/30970064/35093307-054fa386-fc7d-11e7-9672-a922d1985f6a.png)
但angular4的文档确实是写着这样加的 哎

**Comment by atian25** [comment]
你这个明明是 5.2.0 的文档。
另外不要看二贩子的中文版。

**Comment by cswww** [comment]
https://angular.io/guide/http#making-a-post-request
嗯 不好意思 装了翻译软件

**Comment by atian25** [comment]
这属于 Angular 使用的问题了，跟 Egg 关系不大，自己查下吧。

**Comment by cswww** [comment]
嗯 好的 谢谢

**Comment by cswww** [comment]
![2018-01-19 10 57 57](https://user-images.githubusercontent.com/30970064/35132760-bc367540-fd07-11e7-829e-aa5acb01aa2e.png)
我去查了一下这一段的问题 这个应该是请求头被修改 询问服务器是否允许
![2018-01-19 10 54 37](https://user-images.githubusercontent.com/30970064/35132788-ddeb3f40-fd07-11e7-915d-710681b55de5.png)
在Express里面可以这样配置允许请求头更改哪些字段
![2018-01-19 10 55 03](https://user-images.githubusercontent.com/30970064/35132868-4e2e407c-fd08-11e7-9ed7-7ff75750495f.png)
cors里面我只找到了怎么更改allowMethods
而Access-Control-Allow-Headers这个权限没找到在哪里
![2018-01-19 10 55 30](https://user-images.githubusercontent.com/30970064/35132841-2c3bf194-fd08-11e7-8464-6bec60e67b9e.png)

**Comment by atian25** [comment]
你现在不是 `Content-Type` 没传过去么，怎么扯到 CORS 跨域了？

**Comment by cswww** [comment]
感觉应该是传过去了 没有被允许 所以拒绝了 因为如果我不修改头的话是能传过去的 
![2018-01-19 11 07 57](https://user-images.githubusercontent.com/30970064/35133025-0d9849b2-fd09-11e7-9732-5d813bdc44b0.png)

**Comment by atian25** [comment]
你的 network 里面都没传过去啊

**Comment by cswww** [comment]
我想想

**Comment by cswww** [comment]
这是我用express框架做的 会请求两次
第一次询问改头行不行，如果框架给出可以的答复 就会发送第二次请求 带上可以的头 传过去
![2018-01-19 11 28 58](https://user-images.githubusercontent.com/30970064/35133626-3620e6e8-fd0c-11e7-8189-5a5cf7b71fbf.png)
这是第二次请求带上了'Content-Type', 'application/json'传过去的样子
![2018-01-19 11 29 20](https://user-images.githubusercontent.com/30970064/35133688-8768acd4-fd0c-11e7-9e97-b174ee04395e.png)

**Comment by cswww** [comment]
我觉得应该是cors没有配置
("Access-Control-Allow-Headers", "Content-Type,Content-Length, Authorization, Accept,X-Requested-With");
修改请求头规则 所以第一次就被拒了

**Comment by atian25** [comment]
你的 angular 和 egg 不是一起的？ 一个 4200 一个 7001

https://github.com/eggjs/egg-cors#configuration

支持 kcors 的其他参数的
![image](https://user-images.githubusercontent.com/227713/35133838-78468fa4-fd0d-11e7-8f54-468c8469c4f8.png)

**Comment by cswww** [comment]
对 我看了这个 这里面只有origin 和methods 就是缺少了Headers 这个 有这个应该就可以了
![2018-01-19 11 42 06](https://user-images.githubusercontent.com/30970064/35133891-ccc51d20-fd0d-11e7-9f42-677e9b9e0c1e.png)

**Comment by cswww** [comment]
我的angular 是netive 没办法和服务端放在一起

**Comment by atian25** [comment]
看 kcors 文档

**Comment by cswww** [comment]
可以了 太感谢了
