### ISSUE TITLE
egg-bin debug 启动断点调试方法

### ISSUE THREAD

**Issue by llsldwy** [eggjs/egg#1986]
* **Node Version**:8.4.0
* **Egg Version**:2.2.0
* **Plugin Name**:egg-bin
* **Plugin Version**:4.3.7
* **Platform**:sublime 

你好，我是刚刚开始 egg
咨询个问题，我在 egg-bin debug 模式下面启动，如何可以在egg启动是添加断点？我想调试一下 egg启动初始化的一些操作。

如下代码：
 "scripts": {
    "debug": "egg-bin debug --env=local --debug-port=9229 --proxy=9999"
  },

因为本身用 sublime开发，以前在用 DevTools调试node，只需要刷新一下，就可以重启服务，调试初始化代码。但是现在用到了 egg-bin debug方式，我不知如何 才能调试egg初始化代码。

**Comment by atian25** [comment]
你指的是启动期的代码？

**Comment by llsldwy** [comment]
@atian25 你好，这样我在描述详细一些，比如 我在写路由的操作。
router.js 文件中，例子的写法是 
module.exports = app => {
  const { router, controller } = app;
  router.get('/home', controller.home);
  router.get('/user/:id', controller.user.page);
};

由于项目中 路由需要配置api 和页面的，数量比较多，所以我想建一个 router文件夹，路由通过业务逻辑划分，然后在router.js 文件中用fs读取router下面路由配置，然后循环依次  router.get('XXX', controller.XXX);  但是这个时候 我想在router.js 里面打断点，调试代码，所以我才疑问如何在启动的时候打断点。像是这种情况都是在egg启动之后，需要初始化的操作，这些我如何打断点调试，还望告知，谢谢！

**Comment by Webjiacheng** [comment]
你是想断点调试吗？
你可以看看这个是不是你想要的
https://www.jianshu.com/p/219eda9fac07

**Comment by atian25** [comment]
@llsldwy 因为 Node 的机制问题，如果仅仅是 `egg-bin debug` 的话，你来不及设置断点，就已经执行过了。

如果想调试启动期的代码，就如我上面说的方式即可。需要依次 attach 3 个进程。
