### ISSUE TITLE
egg-socket.io 会出现间断性丢失客户端连接的情况

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#1987]
* **Node Version**:9.2.1
* **Egg Version**:2.0.0
* **Plugin Name**:egg-socket.io
* **Plugin Version**:4.0.6
* **Platform**:
* **Mini Showcase Repository**:

客户端一直保持连接中，没有出现过中断的情况。但是在查找app.io.sockets.sockets的时候，会出现有时候能查到，有时候为空的情况。

例如：客户端1和客户端2，一直保持连接中，我进行广播的时候查找app.io.sockets.sockets会出现以下几种情况：
-  查到所有socket (客户端1和客户端2)
-   app.io.sockets.sockets为空
-  只查到部分socket (客户端1和客户端2轮流查到)

第一次发消息查到了socket，过几秒再查就没有了，过几秒再查又有了。

有时候还会出现报错：
`
403 ERROR 32088 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
`

请问是什么原因？该如何解决？谢谢~

图：
![](http://oiiwwqiek.bkt.clouddn.com/img/github/1516333875618.jpg)
![](http://oiiwwqiek.bkt.clouddn.com/img/github/16EBA050-03E7-433E-9FCE-22B47FF673C1.png)

**Comment by Cheese-Yu** [comment]
我服务器上是用pm2部署的。本地测试不会有这种情况。刚刚服务器上换成了egg内置的部署方法，没有出现上述情况了。

**Comment by ngot** [comment]
不要用 pm2  吧，没测试过 pm2, 而且EGG也不需要pm2

**Comment by Cheese-Yu** [comment]
`ERROR 51170 A client (::ffff:127.0.0.1:58655) error [ECONNRESET] occurred: read ECONNRESET`
客户端刷新的时候报错，这个报错该如何解决？

**Comment by Cheese-Yu** [comment]
神奇地可以找到对象了！然而我没有改动什么。。。

**Comment by Cheese-Yu** [comment]
看了一下日志，好像是进程不同造成的。如果几个socket对象不在同一个进程，那么该如何获取到所有的socket对象呢？

**Comment by Cheese-Yu** [comment]
上面不同进程的问题解决了，通过redis的sub、pub进行订阅和广播。多进程直接要注意公共数据的同步。

**Comment by pengkobe** [comment]
@Cheese-Yu  为啥一定要用 pub/sub 呢，直接 get/set 不行？

**Comment by Cheese-Yu** [comment]
@pengkobe 因为我需要主动通知其他进程的socket对象，所以用了pub/sub

**Comment by Cheese-Yu** [comment]
还有一种报错是：ERROR 11644 A client (::ffff:59.58.125.74:54237) error [HPE_INVALID_METHOD] occurred: Parse Error

**Comment by thonatos** [comment]
问题都解决了吧，关了，有需要再开。

**Comment by Jerry-swat** [comment]
> 还有一种报错是：ERROR 11644 A client (::ffff:59.58.125.74:54237) error [HPE_INVALID_METHOD] occurred: Parse Error

我也遇到这问题了，你找到问题所在了不
