### ISSUE TITLE
请问，在egg-cluster的master文件里我打印处console.log(process.pid)

### ISSUE THREAD

**Issue by 1316346949** [eggjs/egg#1991]
请问各位大神，使用npm run dev 方式在window环境下启动 在egg-cluster的master文件里我打印处console.log(process.pid)为什么有3次不同的pid，而在window下npm run start   console.log(process.pid)打印无效，在egg/index文件里 打印console.log(process.pid)也是3次不同pid。

我之前设想，所有的文件一直到master文件里fork为止都是master进程运行，只有一个pid，app_worker.js属于work进程运行 有多个pid对应多个worker进程，agent_worker.js只属于agent进程运行，也只有一个pid

**Comment by atian25** [comment]
第一段没看懂你分别怎么打点的

**Comment by 1316346949** [comment]
@atian25 是这样的，我在egg-cluster的master.js的文件里打点的，并不是在里面
![qq 20180119165722](https://user-images.githubusercontent.com/24400797/35142691-ff69e5f4-fd39-11e7-96f5-ef1b61a3d474.png)

**Comment by 1316346949** [comment]
![image](https://user-images.githubusercontent.com/24400797/35142727-26582cc0-fd3a-11e7-9a80-59ecc3a71d29.png)

**Comment by 1316346949** [comment]
![image](https://user-images.githubusercontent.com/24400797/35142747-36cfd3d2-fd3a-11e7-8836-7d20cc64b32c.png)

**Comment by 1316346949** [comment]
![image](https://user-images.githubusercontent.com/24400797/35142788-59b581f8-fd3a-11e7-84ae-191ab88113c7.png)

**Comment by 1316346949** [comment]
难道是4个进程都运行了 master文件？

**Comment by 1316346949** [comment]
难道是 agent master woker 都运行了master文件

**Comment by 1316346949** [comment]
@ngot 是这样的我在https://github.com/eggjs/egg/blob/master/lib/application.js里打印onsole.log(process.pid)，为什么会出现3次不同的process.pid呢

**Comment by dead-horse** [comment]
因为 master 进程，agent 进程和 worker 进程都会加载该文件

**Comment by 1316346949** [comment]
谢谢@dead-horse
