### ISSUE TITLE
egg-sequelize 中文乱码问题

### ISSUE THREAD

**Issue by airingursb** [eggjs/egg#1992]
mysql数据库，配置如下：
```
config.sequelize = {
    dialect: 'mysql', // support: mysql, mariadb, postgres, mssql
    database: 'recyc-dev',
    host: 'localhost',
    port: '3306',
    username: 'root',
    password: '',
  };
```

数据库字符集 uft-8，数据库内中文正常显示。
获取数据时，中文打印为乱码。

获取数据时打印如下：
![image](https://user-images.githubusercontent.com/10513408/35143503-c299ffe4-fd3c-11e7-92f7-035bf76bbfd9.png)

可以看到`name`是乱码的，没找到原因。
数据库是正常的，且为 uft-8.

![image](https://user-images.githubusercontent.com/10513408/35143542-d98f7a1c-fd3c-11e7-8f69-dec52f064014.png)

![image](https://user-images.githubusercontent.com/10513408/35143554-de88fb24-fd3c-11e7-96ee-0234d4437c16.png)

**Comment by saighost** [comment]
这个应该跟插件没关系，你运行sql
`show variables like 'character%';`
就可以知道数据库哪里编码有问题

**Comment by airingursb** [comment]
@saighost 检查了下，字符集没问题，都是uft8，而且这个项目在windows的跑是可以拿到中文的，但是mac不行…

**Comment by saighost** [comment]
@airingursb 
不同平台下连的是同一个数据库出现的乱码问题？
你可以试试用egg-mysql插件查数据试试。
我之前遇到乱码之后参考的文章：
https://www.cnblogs.com/shootercheng/p/5836657.html

**Comment by dead-horse** [comment]
与 egg 和插件无关，排查数据库编码问题

**Comment by losymear** [comment]
可能是GUI的问题

**Comment by airingursb** [comment]
@losymear 已排查，是mysql版本的问题，我的这个版本太低了，然后编码会产生某种奇怪的bug。升级之后没问题了
