### ISSUE TITLE
egg vue ssr项目 在https地址访问下fb分享无法抓取信息

### ISSUE THREAD

**Issue by GoBrianGo** [eggjs/egg#1993]
使用egg vue ssr搭建了一个服务端渲染的项目，可是当部署到正式环境时（https），使用fb分享的时候，抓取不了信息，fb分享是需要抓取我们的分享页面的标签信息来进行分享，可是在http的域名访问下是没问题的。

**Comment by atian25** [comment]
跟 egg 没啥关系，属于前端脚本跨域执行问题吧

**Comment by GoBrianGo** [comment]
fb分享是会抓取我们的页面信息的（抓取html），可是现在是抓取不了任何信息的，可是抓取http的页面的时候就是可以的，我们的脚本什么的都是https的哦。

**Comment by GoBrianGo** [comment]
fb只是抓取静态页面，和脚本执行没什么关系的吧

**Comment by GoBrianGo** [comment]
而且我试过写一个简单的接口，返回一些简单文本，这样使用fb的工具抓取，也是抓取不到任何信息。用的是这个[工具](https://developers.facebook.com/tools/debug/echo/?q=https://www.baidu.com)

**Comment by atian25** [comment]
没看过 fb 的分享脚本，不确定，这属于 fb 的前端 js 脚本在浏览器里面执行的问题了，跟 egg 没啥关系。

你可以直接用 node 启动一个 https server 试下 fb 对 https 的支持。

**Comment by masonz** [comment]
我也遇到了类似的问题，后面通过 [开启gzip](https://eggjs.org/zh-cn/basics/middleware.html#%E4%BD%BF%E7%94%A8-koa-%E7%9A%84%E4%B8%AD%E9%97%B4%E4%BB%B6) 的方式解决了
