### ISSUE TITLE
egg-multipart表单提交获取到的数据不全？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#2003]
![image](https://user-images.githubusercontent.com/5345266/35203369-d7d6d44a-ff62-11e7-9348-6b7c2e74137f.png)
请求数据如上图
![image](https://user-images.githubusercontent.com/5345266/35203720-9b16f4b6-ff64-11e7-945f-761a125dcb78.png)
数据内容如上图
![image](https://user-images.githubusercontent.com/5345266/35203656-3fbbcc90-ff64-11e7-8db1-1f84d56757e1.png)
获取到的数据不一致

**Comment by SunShinewyf** [comment]
获取multipart类型的表单数据的时候，应该使用如下方式：
const fileStream = yield this.ctx.getFileStream()

你这里使用 `const fileStream = yield this.ctx.multipart()`，按照你的方式试了一下，fileStream 打印出是一个Function，对应egg-multipart插件里面的构造函数 [multipart](https://github.com/eggjs/egg-multipart/blob/master/app/extend/context.js#L12)

**Comment by atian25** [comment]
请仔细看文档，https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6
