### ISSUE TITLE
单元测试时如何临时的停用jwt

### ISSUE THREAD

**Issue by treemore** [eggjs/egg#2008]
* **Node Version**:
8.9.4
* **Egg Version**:
2.0
* **Plugin Name**:
egg-jwt
* **Plugin Version**:
egg-jwt@2.2.1
* **Platform**:
* **Mini Showcase Repository**:

尝试使用mock
 mm(app.config.jwt, "enable", false)
        console.info(JSON.stringify(app.config.jwt))
确实生效了。
但是nodejs.UnauthorizedError: No authentication token found

**Comment by okoala** [comment]
你试下在 plugin.unittest.js 中设置 

```
exports.jwt ={
  enable: false,
  package: 'egg-jwt'
};
```

**Comment by treemore** [comment]
可以。 还能这么操作，太爽了。
