### ISSUE TITLE
在程序中用了egg-redis、egg-session-redis插件，通过this.ctx.session设置了session之后，存在redis中是以set形式存储的，但是key是一个自动生成的编码。那么如何获取到存在redis中的session的key呢？求指教！！！

### ISSUE THREAD

**Issue by h-handy** [eggjs/egg#2010]
* **Node Version**:v8.9
* **Egg Version**:2.0
* **Plugin Name**:redis-session,redis-session-redis
* **Plugin Version**:1.0,1.0
* **Platform**:centos
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
为什么要获取？

**Comment by h-handy** [comment]
@dead-horse 想要在缓存总存取，验证单端登陆！

**Comment by DragWeb** [comment]
不需要通过key获取，直接在request 中获取session就可以了呀，会话未结果可以直接从session拿

**Comment by dead-horse** [comment]
如果是基于 ip 做限制，将 ip 写到 session 中即可，自行做校验。如果一定要获取到 key，可以通过 `opts. genid` 参数来自行控制 session id 的生成方式。文档地址：https://github.com/koajs/session

**Comment by wlfei0502** [comment]
> 如果是基于 ip 做限制，将 ip 写到 session 中即可，自行做校验。如果一定要获取到 key，可以通过 `opts. genid` 参数来自行控制 session id 的生成方式。文档地址：https://github.com/koajs/session

当使用CAS做单点登出的时候，是需要获取session id的。原因：

如果有A，B两个子系统。它们都处于登录状态，当B系统退出登录，A系统也需要自动退出，这样A系统之前存储在redis中的session就需要手动进行销毁。现在因为没有sessionId，无法销毁session，导致A系统刷新页面，仍然处于登录状态。

提到的配置opts.genid，我在config.default.js中:
config.session = { genid: () => return uuid;}

但存在的问题是，config.default.js中无法获取ctx，如何将该id传到middleware中进行使用呢？

我看了koa-session源码，不知道作者出于什么样的考虑，没有在context.js的create方法中将生成的externalKey挂载到session上

我现在的解决方案是：
1、修改源码，在create方法中，this.session.id = this.externalKey; 
2、从cookie中获取，this.session.id = ctx.cookies.get('EGG_SESS', ctx.sessionOptions);

这样做会有什么潜在的问题吗？

**Comment by wlfei0502** [comment]
@dead-horse 当使用CAS做单点登出的时候，是需要获取session id的。原因：

如果有A，B两个子系统。它们都处于登录状态，当B系统退出登录，A系统也需要自动退出，这样A系统之前存储在redis中的session就需要手动进行销毁。现在因为没有sessionId，无法销毁session，导致A系统刷新页面，仍然处于登录状态。

提到的配置opts.genid，我在config.default.js中:
config.session = { genid: () => return uuid;}

但存在的问题是，config.default.js中无法获取ctx，如何将该id传到middleware中进行使用呢？

我看了koa-session源码，不知道作者出于什么样的考虑，没有在context.js的create方法中将生成的externalKey挂载到session上

我现在的解决方案是：
1、修改源码，在create方法中，this.session.id = this.externalKey;
2、从cookie中获取，this.session.id = ctx.cookies.get('EGG_SESS', ctx.sessionOptions);

这样做会有什么潜在的问题吗？

**Comment by zheng199512** [comment]
我看egg-redis中有这样的代码（或扩展egg-session）：

```js
app.sessionStore = {
    async get(key) {
      const res = await redis.get(key);
      if (!res) return null;
      return JSON.parse(res);
    },

    async set(key, value, maxAge) {
      maxAge = typeof maxAge === 'number' ? maxAge : ONE_DAY;
      value = JSON.stringify(value);
      await redis.set(key, value, 'PX', maxAge);
    },

    async destroy(key) {
      await redis.del(key);
    },
  };
```

- 可以直接调用`app.sessionStore.get()`进行key的可控性和规则性，而不是自动生成的session id。

如果开启了session-redis，那就意味着session不会存在本地，也就是`ctx.session.user='hello'`这样原本存在cookie中也会存至redis，对吧？

**Comment by wlfei0502** [comment]
逻辑是这样的：

如果没有开启redis，即session没有配置store的情况下，egg-session会对session中的内容进行加密，然后以EGG_SESS（默认的）为key，将其存储在cookie里发送到浏览器。下次请求，再将cookie中的内容进行解密，恢复到服务器的session里。

如果开启redis，即session配置了store，egg-session会自动将session内容和配置选项（maxAge，expire等）存入redis中，期间会判断session是否配置了genid函数，如果没有配置，会生成一个随机的extenalKey作为session的key。接下来会将EGG_SESS作为key，externalKey作为value，存入cookie中，响应到前端。

app.sessionStore 只是对redis存取，销毁做的封装，跟sessionId没有关系。

总结：
如果session没有配置store选项，cookie中存的是session加密后的内容。如果session配置了store，cookie中存的是redis中的key（即sessionId）。

**Comment by zheng199512** [comment]
不是吧，随机生成的externalKey，和cookie中存储的externalKey，我根本连不起来啊，你是id设置成cookie中的值了吧，不是自动生成的吧？

**Comment by wlfei0502** [comment]
cookie中的externalKey是随机生成的key加密过的，你需要ctx.cookies.get('EGG_SESS', ctx.sessionOptions);
进行解密

**Comment by zheng199512** [comment]
哇，真的耶，多谢大佬指点~

**Comment by zheng199512** [comment]
还有一个小问题，如果公司项目的要求redis的key值规范，例如NGCS_SERVICEREQ:20161215001，怎么解决比较好呢？后面数字自定义，：前面的根据项目定义。

**Comment by wlfei0502** [comment]
config.defaut.js中配置session:

config.session = {
    genid: () => {
       return 'NGCS_SERVICEREQ:' + 数字；
    }
}

**Comment by CharlseW** [comment]
this.ctx.session._sessCtx.externalKey

不知是不是各位想要的。。。

**Comment by ruur** [comment]
> this.ctx.session._sessCtx.externalKey
> 
> 不知是不是各位想要的。。。

竟然藏这么深

**Comment by mingyard** [comment]
我的场景是 希望nestjs 项目能验证 eggjs 项目的 session。所以需要解析出eggjs session 中 对应的rediskey。通过查看源码找到了解决方法，下面是解密方法。自测能成功解出。

```
class EggCookiesDecryptor {
  constructor(keys) {
    this.keys = Array.isArray(keys) ? keys : [keys];
    this.cipher = 'aes-256-cbc';
  }

  /**
   * Base64url 解码
   */
  b64urlDecode(str) {
    if (!str || typeof str !== 'string') return Buffer.alloc(0);
    
    // 还原标准 Base64
    str = str.replace(/-/g, '+').replace(/_/g, '/');
    
    // 添加填充
    while (str.length % 4) {
      str += '=';
    }
    
    return Buffer.from(str, 'base64');
  }

  /**
   * 密钥派生 - 模拟 OpenSSL EVP_BytesToKey
   * 使用 MD5 迭代生成 32字节密钥 + 16字节IV
   */
  keyToPassword(key) {
    const KEY_LEN = 32;
    const IV_SIZE = 16;
    const bytes = Buffer.alloc(KEY_LEN + IV_SIZE); // 48 字节

    let lastHash = null;
    let nBytes = 0;

    // 迭代生成足够的字节
    while (nBytes < bytes.length) {
      const hash = crypto.createHash('md5');
      
      // 第二轮开始，将上一轮的哈希结果也加入
      if (lastHash) {
        hash.update(lastHash);
      }
      
      hash.update(key);
      lastHash = hash.digest(); // MD5 产生 16 字节
      
      // 复制到结果 buffer
      lastHash.copy(bytes, nBytes);
      nBytes += lastHash.length;
    }

    const password = {
      key: bytes.slice(0, KEY_LEN),   // 前 32 字节作为密钥
      iv: bytes.slice(KEY_LEN, KEY_LEN + IV_SIZE), // 后 16 字节作为 IV
    };

    return password;
  }

  /**
   * 解密单个密钥
   */
  decryptWithKey(data, key) {
    try {
      const password = this.keyToPassword(key);
      const decipher = crypto.createDecipheriv(this.cipher, password.key, password.iv);
      
      const decrypted = Buffer.concat([
        decipher.update(data),
        decipher.final()
      ]);
      
      return decrypted.toString('utf8');
    } catch (err) {
      console.error('Decrypt error:', err.message);
      return false;
    }
  }

  /**
   * 解密 - 尝试所有密钥
   */
  decrypt(cookieValue) {
    if (!cookieValue) return false;

    // Base64url 解码
    const data = this.b64urlDecode(cookieValue);
    if (data.length === 0) return false;

    // 尝试每个密钥
    for (let i = 0; i < this.keys.length; i++) {
      const value = this.decryptWithKey(data, this.keys[i]);
      if (value !== false) {
        return {
          value,
          index: i, // 返回使用的密钥索引
        };
      }
    }

    return false;
  }

}
```
