### ISSUE TITLE
npm run stop 会关闭所有项目的master进程

### ISSUE THREAD

**Issue by asiareal** [eggjs/egg#2011]
* **Node Version**: v8.9.4
* **Egg Version**: 2.0.0
* **Plugin Name**:  egg-scripts
* **Plugin Version**: 2.1.0
* **Platform**: mac

`egg-init egg-example --type=simple` 初始多个项目
在其中一个项目 npm run stop , 会把所有运行的egg项目都stop掉

**Comment by atian25** [comment]
文档里面有描述了，默认是杀全部的。

你可以在 start 和 stop 里面都加 `--title=`

**Comment by atian25** [comment]
https://github.com/eggjs/egg-boilerplate-simple/pull/41
