### ISSUE TITLE
nodejs性能平台看不到错误日志与模块依赖

### ISSUE THREAD

**Issue by wangguohao** [eggjs/egg#2013]
* **Node Version**: 8.9.4
* **Egg Version**: 2.0.0
* **Plugin Name**: egg-alinode
* **Plugin Version**: 2.5.0
* **Platform**: linux
* **Mini Showcase Repository**: 无

#### 步骤:
* 通过tnvm安装了与node版本（8.9.4）对应的aliyun-node（3.8.4）
* config如下（日志目录没有进行修改，根目录/logs）
```
//  config.default.js
exports.alinode = {
    server: 'wss://agentserver.node.aliyun.com:8080',
    appid: 'xxx',
    secret: 'xxx',
  }
```
```
//  plugin.js
exports.alinode = {
  enable: true,
  package: 'egg-alinode'
};
```
* 打开nodejs性能平台可以看到实例
* 主动通过程序生成错误日志（common-error.log有输出）

另外慢http日志多久不响应会生成？

**Comment by JacksonTian** [comment]
egg-alinode 默认是监控了 package.json 和 common-error.log 的。
```
    error_log: [
      path.join(appRoot, `logs/${appInfo.pkg.name}/common-error.log`),
      path.join(appRoot, 'logs/stderr.log'),
    ],
    packages: [
      path.join(appInfo.baseDir, 'package.json'),
    ],
```

package.json 的依赖检查频度是 1 小时，所以最长需要1小时才能看到数据。

慢日志默认是大于 400ms 的请求。

**Comment by wangguohao** [comment]
@JacksonTian 
谢谢，可以了，不过实例名称可以修改吗？

**Comment by JacksonTian** [comment]
我们选了 hostname 做为实例名。修改 hostname 会修改 实例名。

**Comment by JacksonTian** [comment]
@Gorden-Wang 请加我们的钉钉群 507028892 或者加我个人 钉钉 JacksonTian

**Comment by shiny** [comment]
我也出现一堆类似 `cat: can't open '/proc/17677/environ': No such file or directory` 的错误，使用的是 alinode 的 docker 环境
