### ISSUE TITLE
本地开发时，如何以不启用文件监视启动应用

### ISSUE THREAD

**Issue by fuguohong** [eggjs/egg#2016]
egg-bin dev启动应用，代码改变应用自动重启。多数情况下很方便。但是当前端连你的电脑调试接口，你又在继续编写代码修改程序的时候，就很不方便了
我没有找到相应的参数来禁用文件监视。
请问这个问题如何解决呢？

**Comment by atian25** [comment]
关闭 egg-development 插件，或者覆盖掉它监控的目录。

https://github.com/eggjs/egg-development#about-reload
