### ISSUE TITLE
egg-graphql add support for custom directive

### ISSUE THREAD

**Issue by foreleven** [eggjs/egg#2023]
graphql-tools 在 2.13.0 版本中添加对 directive resolver 的支持，希望 egg-graphql 也升级更新一下。

graphql-tools 
[issue212](https://github.com/apollographql/graphql-tools/issues/212)
[merge518](https://github.com/apollographql/graphql-tools/pull/518)  
[API文档](https://github.com/apollographql/graphql-tools/issues/530)

**Comment by jtyjty99999** [comment]
可以支持，需要改一些逻辑，下周三之前可以搞好，如果来不及的话，可以提一个pr 在这边
 https://github.com/eggjs/egg-graphql/blob/master/lib/load_schema.js#L30 加一个 directive resolver的loader即可

**Comment by foreleven** [comment]
好的，周末有空的话，我写一下。
```
const directiveResolverFile = path.join(basePath, type, 'directive.js');
// merge directive resolvers
```
这样默认合并所有 directive.js

**Comment by foreleven** [comment]
(PR)[https://github.com/eggjs/egg-graphql/pull/11] 已经提交，帮忙审核一下。 @jtyjty99999
