### ISSUE TITLE
文档单元测试部分，helper.js的路径写错了

### ISSUE THREAD

**Issue by hujiulong** [eggjs/egg#2029]
https://github.com/eggjs/egg/blob/1e3a4b35801e136dd4f1fbaf3c49b771a50c0f72/docs/source/zh-cn/core/unittest.md#L604

https://github.com/eggjs/egg/blob/1e3a4b35801e136dd4f1fbaf3c49b771a50c0f72/docs/source/en/core/unittest.md#L554

应该是 `app/extend/helper.js`

**Comment by dead-horse** [comment]
提 PR 吧

**Comment by hujiulong** [comment]
回复这么快的吗.. 我提个PR

**Comment by atian25** [comment]
close via https://github.com/eggjs/egg/pull/2030
