### ISSUE TITLE
egg  router  问题，望求解答

### ISSUE THREAD

**Issue by lazyyman** [eggjs/egg#2033]
// app/router.js
module.exports = app => {
  const { router, controller } = app;
  router.get('/user/:id', controller.user.info);
};

这是官网 router  的一段代码。我遇到一个无法理解的问题，这里  router 和 controller  是从 app  里面解构出来的，那么app  一定应该有这两个属性，app.contruller   和  app.router ; 我在debug  的时候，只找到app.controller ，却没有  app.router，我使用 JSON.stringfy(app)，也找到了controller属性，却没有找到router   ，但是我却发现  app.router  是有值的。这里我就很懵逼了，望求解答。
![Uploading @YBBFK7RD[C9JDOJRMMRX[C.png…]()

**Comment by atian25** [comment]
因为它只有 getter，看下 es5 的 defineProperties

**Comment by atian25** [comment]
不好意思，昨天手机上答错了。

stringify 没出来是因为 `toJSON` 里面覆盖掉了。

https://github.com/eggjs/egg/blob/master/lib/egg.js#L155

**Comment by lazyyman** [comment]
昨天晚上已经看到了，找到原因了，调用的是 EggCore 的  get  router(){}  方法，router 的值是 一个 Symbol，在源码跟踪的时候没有注意到这个Symbol  。十分感谢
