### ISSUE TITLE
这里给出  CSRF 的防范  如何关闭的方法。官方写的太模糊了，会关不掉

### ISSUE THREAD

**Issue by lazyyman** [eggjs/egg#2035]
以下两个操作均在 app/config/   目录下操作

方法一：
在 config.default.js 下

'user strict';

module.exports = appInfo => {
    const config = {
        view: {
            defaultViewEngine: 'nunjucks',
            mapping: {
                '.tpl': 'nunjucks',
            },
        },

        //关闭 csrfToken 验证
        security: {
            csrf: {
                enable: false,
            },
        },

        mysql: {
            client: {
                host: 'localhost',
                port: '3306',
                user: 'root',
                password: '123456',
                database: 'dev',
            },
            app: true,
            agent: false,
        }
    };

    config.keys = appInfo.name + '_luo19950105';

    return config;
};
这里 up主 直接把整个的 配置贴出来。up 主亲测，没有问题。

方法二：
还有一个是在  plugin.js   

plugin.js 

'user strict';

exports.security = false;

exports.nunjucks = {
    enable: true,
    package: 'egg-view-nunjucks',
};

exports.mysql = {
    enable: true,
    package: 'egg-mysql',
};

exports.ua = {
    enable: true,
    package: 'egg-ua'
}

这个配置  是不会关闭  security  楼主试了很多次；
原因是因为
exports.nunjucks = {
    enable: true,
    package: 'egg-view-nunjucks',
};
没有去掉，目前 up主 没有深入去看源码。所以方法二最终的配置为

plugin.js 

'user strict';

exports.security = false;

exports.mysql = {
    enable: true,
    package: 'egg-mysql',
};

exports.ua = {
    enable: true,
    package: 'egg-ua'
}

**Comment by dead-horse** [comment]
如果觉得文档不够清晰，可以提个 PR 改善一下。

**Comment by lazyyman** [comment]
@dead-horse 好的，感谢大佬们完善社区

**Comment by atian25** [comment]
你搞混了 config 和 plugin.js 的区别，去仔细看看配置和插件这 2 篇文档吧。

**Comment by lx3238443k** [comment]
楼主关闭了 csrf后  mysql 还可以用？？
