### ISSUE TITLE
请问socket.io如何监听connection事件？

### ISSUE THREAD

**Issue by whit15** [eggjs/egg#2037]
* **Node Version**:  8.9.3
* **Egg Version**:  2.0.0
* **Plugin Name**: egg-socket.io
* **Plugin Version**: 4.0.6
* **Platform**: MacOS
* **Mini Showcase Repository**:

文档上并没有提及到connection的监听
尝试了在router.js中定义
```
io.route('connect, io.controller.game.index);
io.route('connection', io.controller.game.index);
```
两种都无法触发控制器中的方法

又尝试了在middleware/auth.js中调用
```
ctx.app.io.controller.game.index();
app.io.controller.game.index();
```
报错Cannot read property 'config' of `undefined`

io.controller.game.index是测试使用，只有一句console.log('11')
其他事件测试调用时正常打印的

**Comment by ngot** [comment]
connection 监听在看它的文档：https://socket.io/docs/server-api/#event-connection

egg-socket.io 只是包装，socket.io 的api看socket.io文档即可。

另外，connection 和 controller 没有逻辑关系，这是两个关系的东西。

controller 只有和已经建立的连接上的消息有关，和连接建立没有一点关系。

**Comment by whit15** [comment]
@ngot 
您说的我都懂，只是我这里是用controller来作为响应这个事件的回调而已。
我想表达的其实是，我没办法用io.route('connect', callback)和io.route('connection', callback)来代替socket.io提供的io.on('connect', callback);，因为这并不会因为连接的建立而触发事件

**Comment by ngot** [comment]
- io.route 就 socket.on 的等价api
- io.route 是用来绑定路由和controller的映射关系的。
- controller 和 connection 之间没有关系

所以，io.route 无法用来替代 io.on 因为这两个之间没有功能上的逻辑关系，也就是不是一个东西。

connection 要用`connection  middleware` ，或者自己手动调用`io.on`,不过自己手动调用的话，egg 的体系的api将无法使用，除非自己再去包装。

**Comment by whit15** [comment]
@ngot
感谢，还是要继续提问。
connection middleware我用了，描述中有说到，在auth.js中调用了
```
ctx.app.io.controller.game.index();
app.io.controller.game.index();
```
报错Cannot read property 'config' of undefined，没办法正常调用controller里面的方法

**Comment by ngot** [comment]
@whit15 没看懂问题。auth.js 中文什么要调用 controller ？

auth 是connection阶段，
controller 是connectioned阶段的通讯，

这两个我上面已经反复解释了没有关系了。这个两个`不是一个东西`不要混在一起。

**Comment by whit15** [comment]
@ngot
抱歉，我确实是第一次用nodejs开发正式项目，大概我描述还是不够清楚。
我先说一下需求好了，在每一个socket连接上时保存它的socket.id到app.的全局变量中，更新全局变量的方法是写在了controller中，全局变量是在定时任务中需要用到的。所以我是需要通过触发connection事件来调用controller的方法实现更新全局变量。
但是目前我没有办法从路由的角度去触发“socket连接上”这个事件，所以又尝试了从middleware中直接调用controller的方法，但是依然失败。
我不知道是我的思路有问题还是确实没办法实现监听connection事件，请给我一个思路吧谢谢

**Comment by ngot** [comment]
@whit15 还是很晕没看懂。这个还是到 socket.io 社区讨论吧，和 egg 无关了。

**Comment by whit15** [comment]
@ngot 好的，感谢回答

**Comment by Kingsearch** [comment]
@ngot 
@whit15  指的应该是 connect、connection 这两个内置事件为什么不生效, 文档里也只例举了disconnecting 、disconnect 、error 这三个内置事件, 难道其余内置事件都不生效?
