### ISSUE TITLE
单元测试覆盖率

### ISSUE THREAD

**Issue by cswww** [eggjs/egg#2042]
不知道是不是我漏了哪个操作，导致三个接口通过和两个接口通过的覆盖率是一样的
![2018-01-27 8 59 14](https://user-images.githubusercontent.com/30970064/35466655-aa212cee-0340-11e8-88eb-d5790552624a.png)
![2018-01-27 8 59 32](https://user-images.githubusercontent.com/30970064/35466656-abbadcd0-0340-11e8-9f3b-7d9bf3f60154.png)

**Comment by atian25** [comment]
打开覆盖率报告看看就知道了

**Comment by atian25** [comment]
`open ./coverage/lcov-report/index.html`
