### ISSUE TITLE
schedule  cron 方式如何暂停任务？

### ISSUE THREAD

**Issue by lanewebchina** [eggjs/egg#2044]
请问schedule  cron 方式如何暂停任务？
业务场景是这样的，比如我有一个任务需要一个小时执行一次，但执行的时候，可能会因为数据量过大，本次还没执行完，就到了下次执行的时间，如果记时暂停等执行完了本次任务再执行应该可以解决问题。

**Comment by atian25** [comment]
1. 不能把任务拆分了去做？
2. 在数据库记个标识位做锁，每次任务启动前都去查询下
