### ISSUE TITLE
如何对error的类型进行判断，再返回自定义的message到前端。

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#2045]
controller层调用业务层时用try catch，会返回各种的错误，
如连接不到数据库，超时，业务错误等。
如果是自定义error，可以new 一个自定义的error出来。
如果是框架的异常，要怎么才能确定一个异常的类型？判断哪个字段？
在controller层如何判断？只if-else逐个判断返回不同的自定义message?

**Comment by atian25** [comment]
- 框架级的错误，一般也不会丢给用户的，egg-onerror 那边兜底统一回复个信息即可，主要还是看日志来修复。
- 某些在你们业务中并不视为框架级的错误，是可以在 Service 层统一封装抛出的错误类型。
- 通用的错误可以在 egg-onerror 或者 Controller 里面里面提供 `throwBizErr` 这类的方式去处理。

**Comment by jjackychen** [comment]
throwBizErr 不是api里面的东西？
要自己实现？

**Comment by atian25** [comment]
自己写 Controller 基类来提供。

**Comment by jjackychen** [comment]
像连不上数据库这种错误，error的name属性是SequelizeConnectionRefusedError，是不是可以根据这个name就可以判断出数据库连接失败？
if('SequelizeConnectionRefusedError' === error.name ){
      ctx.body='数据库连接失败'；
}

**Comment by scottming** [comment]
同样遇到自定义业务异常的情形，请问 `自定义 Controller 基类` 这种方式有没什么例子啊？

**Comment by atian25** [comment]
Controller 文档那有
