### ISSUE TITLE
请问是否有规范当Helper很多的时候, 使用多文件的方式编写代码

### ISSUE THREAD

**Issue by x22x22** [eggjs/egg#2046]
在关于[框架扩展.Helper](https://eggjs.org/zh-cn/basics/extend.html#helper)中介绍了Helper的使用.
但是当Helper很多的时候, 有没有规范说明怎么更合理的去存放Helper呢?
比如使用以下结构:
```
app
├── extend
├── helper.js
├── helper
|   ├── index.js
|   ├── url.js
|   ├── file.js
|   ├── money.js
|   ├── ....js
```

**Comment by atian25** [comment]
helper 一般就是简单的渲染辅助函数，用于格式化啥的。
如果你的逻辑很复杂，可以考虑抽象为 `ctx.service.utils.xx` 之类的。

当然，也可以定制自己的规范，如 `app.utils` 之类的，用 `app.loader.loadToContext/loadToApp` 来处理即可，具体看文档。
