### ISSUE TITLE
[egg-schedule] Handshake inactivity timeout

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#2047]
* **Node Version**:
8.9.1
* **Egg Version**:
2.1.0
* **Plugin Name**:
egg-schedule
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/3679798/35493251-bc118cde-04ec-11e8-93b6-fb1c2328aad7.png)

**Comment by atian25** [comment]
看你具体代码查下咯，不是写了 callCheatSpark 的 71 行抛错的么，自己跟下
