### ISSUE TITLE
npm start 出错 sh: egg-scripts: command not found

### ISSUE THREAD

**Issue by ylksty** [eggjs/egg#2048]
> egg-scripts start --daemon

sh: egg-scripts: command not found

  "dependencies": {
    "egg": "^2.3.0",
    "egg-scripts": "^2.1.0",
    "egg-view-nunjucks": "^2.1.4"
  },

这是什么原因，老版本都可以的

**Comment by atian25** [comment]
你确定你安装了么？ 然后要用 npm 启动。

可以去了解下 node 的命令行机制。

**Comment by ylksty** [comment]
![image](https://user-images.githubusercontent.com/16874050/35499130-1d9e0b84-050c-11e8-804d-843478a60421.png)

**Comment by atian25** [comment]
你如果是直接在命令行执行 `egg-scripts` 肯定是找不到的啦。
它只是一个局部依赖，bin 会安装到 `./node_modules/.bin/egg-scripts` 下。
如果你是执行 `npm start` 的话，npm 会自动把这个目录加入到 PATH，因此可以找到。

这属于 node scripts 这块的知识，可以看下 npm/node 官方文档。

**Comment by ylksty** [comment]
node_modules/egg-scripts/bin/egg-scripts.js start --daemon // 这样可以起来，好的多谢楼上

**Comment by atian25** [comment]
你没明白我的意思... 直接用 npm 启动。

**Comment by ylksty** [comment]
我发现./node_modules/.bin/egg-scripts 并没有这个文件，所以我 npm i egg-scripts --save了，然后npm start 正常了

**Comment by Bill0412** [comment]
> 我发现./node_modules/.bin/egg-scripts 并没有这个文件，所以我 npm i egg-scripts --save了，然后npm start 正常了

Yes, you have to `npm install` first.
