### ISSUE TITLE
没有任何监控数据，可能 alinode 没有正常启动或者没有设置环境变量ENABLE_NODE_LOG=YES来开启日志功能 

### ISSUE THREAD

**Issue by lifengzhai** [eggjs/egg#2049]
* **Node Version**:9.4.0
* **Egg Version**:^2.0.0
* **Plugin Name**:egg-alinode
* **Plugin Version**:2.0.1
* **Platform**:node:alpine
* **Mini Showcase Repository**:

### Dockerfile

```FROM node:alpine

ENV NODE_ENV=production EGG_SERVER_ENV=prod ENABLE_NODE_LOG=YES

COPY . /app
WORKDIR /app

RUN chmod 777 ./docker-entrypoint.sh
#RUN npm install --production --registry=https://registry.npm.taobao.org

# alinode
RUN npm i nodeinstall -g
RUN nodeinstall --install-alinode ^3

RUN npm install --production

ENTRYPOINT [ "./docker-entrypoint.sh" ]
EXPOSE 3021
```

### docker-entrypoint.sh
```
#!/bin/sh

NODE_ENV=production
ENABLE_NODE_LOG=YES

npm run migrate:up
npm run seed:down
npm run seed:up
npm start

```

### plugin.js
```
exports.alinode = {
  enable: true,
  package: 'egg-alinode'
};
```

### config.default.js

``` config.alinode = {
    server: 'wss://agentserver.node.aliyun.com:8080',
    appid: 'XX',
    secret: 'XX',
    // logdir: 'Node.js 性能平台日志输出地址绝对路径，与 NODE_LOG_DIR 保持一致。如：/tmp/',
    packages: [
      path.join(appInfo.baseDir, 'package.json'),
    ],
    error_log: [
      path.join(appInfo.baseDir, 'logs/' + appInfo.name + '/common-error.log'),
    ]
  };
```

## 遇到的问题

能正常看到内存和cpu信息，看不到进程监控信息（可以看到存在的进程）

>  没有任何监控数据，可能 alinode 没有正常启动或者没有设置环境变量ENABLE_NODE_LOG=YES来开启日志功能 
> 系统中存在以下 Node.js 进程（不一定由 alinode 启动） 

#### ps: 
1、试过用alinode的docker是可以看到进程监控信息
2、docker里项目的node_modules里的.bin文件夹里看过，有node文件
> lrwxrwxrwx    1 root     root            16 Jan 29 08:27 node -> ../node/bin/node

**Comment by lifengzhai** [comment]
现在看下来应该是 没有用 alinode 启动

**Comment by JacksonTian** [comment]
点击界面上的 查看系统信息。看看怎么说的。

**Comment by atian25** [comment]
@lifengzhai 看 master-stdout.log ，如果 alinode 的话，会有一条日志的输出版本的，文档里面有提到了。

**Comment by lifengzhai** [comment]
@JacksonTian  系统信息里面 memory load cpu 信息都是有的

**Comment by lifengzhai** [comment]
@atian25 
```
2018-01-29 08:41:47,910 INFO 118 [master] =================== egg start =====================
2018-01-29 08:41:47,912 INFO 118 [master] node version v9.4.0
2018-01-29 08:41:47,912 INFO 118 [master] egg version 2.3.0
```

**Comment by atian25** [comment]
没有 alinode 日志，看起来是环境变量不对。
你在 app.js 里面输出 process.versions 再确认下

PS：要更新下依赖看看，egg-cluster 最新版本才支持输出 alinode 版本的。

**Comment by lifengzhai** [comment]
@JacksonTian  
```
cat package-lock.json | grep egg-cluster
        "egg-cluster": "1.13.1",
        "egg-cluster": {
          "resolved": "https://registry.npmjs.org/egg-cluster/-/egg-cluster-1.13.1.tgz",
```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L107

这里其实已经处理过环境变量了，你现在要调试下，看为什么启动的 node 不是这个 alinode，跟后面的 egg 没啥关系了。

**Comment by lifengzhai** [comment]
其实问题是 alinode 在 alpine 或者 node:alpine 里是无法运行的。。。

**Comment by atian25** [comment]
啥叫无法运行

**Comment by JacksonTian** [comment]
无法运行 错误信息是什么？

**Comment by atian25** [comment]
重新描述下吧... 前面你反馈的信息不都是可以正常安装 alinode 并正常运行么？

现在定位到是 alinode 没安装成功？这个有可能，毕竟 alpine 是阉割版的，很多依赖不一定有。（具体还是要问 @JacksonTian ）

**Comment by lifengzhai** [comment]
恩是的，  问题 就是 alinode 没安装成功（无法启动）， 应该是缺少什么依赖，我本地试过是OK的，官方的 alinode 镜像有些太大（~800M）

**Comment by atian25** [comment]
那可以不用 alinode 的镜像的，随便找个 docker 的 centos 还是 node 的镜像就 OK 了。

**Comment by zhangzifa** [comment]
@lifengzhai  你需要alpine的alinode镜像？

**Comment by zhangzifa** [comment]
@lifengzhai  docker pull registry.cn-hangzhou.aliyuncs.com/aliyun-node/alinode:3.8.4-alpine 这个是基于alpine的alinode镜像  
相关信息
https://help.aliyun.com/document_detail/66027.html

**Comment by DuJiming** [comment]
我也遇到这个问题了。。后来发现是我改过项目名字，在node_mod。。里面一些地址还是改名字前的地址，所以出现了这个问题，一模一样
