### ISSUE TITLE
maybe the connection is close on other side.

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#2050]
* **Node Version**:
8.9.1
* **Egg Version**:
2.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

[cluster 超时](https://github.com/node-modules/cluster-client/blob/e32f0eff5fe5dfb4187386d928b2fa8cdc65cfa5/lib/leader.js#L72)

```
cluster-client
  "_from": "cluster-client@^1.7.1",
  "_id": "cluster-client@1.7.1",
```
![image](https://user-images.githubusercontent.com/3679798/35506577-b10b19f8-0524-11e8-88eb-4ab458914a86.png)

**Comment by atian25** [comment]
那个 issue 里面不是说了么

![image](https://user-images.githubusercontent.com/227713/35506854-ba558a9c-0525-11e8-9e2c-f3fe1b6960eb.png)

检查你这个函数里面是不是做了什么占用 CPU 的事

**Comment by atian25** [comment]
先关了，有进一步信息补充的时候再自行开启。
