### ISSUE TITLE
sequelize create and insert data into belongsToMany table

### ISSUE THREAD

**Issue by JohnnyMore** [eggjs/egg#2052]
* **Node Version**:v8.9.0
* **Egg Version**:1.9.0
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.1.0
* **Platform**:windows 7
* **Mini Showcase Repository**:

我的问题是这样的：在多对多（belongsToMany）关联中，创建表时需要初始化一些初始数据，根据sequelize文档提示，如下：
![qq 20180129204156](https://user-images.githubusercontent.com/17742436/35510891-e3cf01f0-0534-11e8-8e20-3b5f3985f758.png)
表都创建成功了，但是初始化的数据无法插入到表中。请问有人遇到过这个问题吗？在关联字段Tags的命名有讲究吗？

**Comment by dead-horse** [comment]
请去 sequelize 提问

**Comment by JohnnyMore** [comment]
在这是否有人遇到过这种需求？知道的帮忙指点一下

**Comment by JohnnyMore** [comment]
问题解决。

**Comment by lingxiaoyi** [comment]
你这个问题怎么解决的?求助

**Comment by JohnnyMore** [comment]
@lingxiaoyi 在利用关联关系创建关联表的时候，关联表必须是复数形式，比如上面的Tags，你去试试。
