### ISSUE TITLE
请问有办法扩展router.resources配置的方法吗?

### ISSUE THREAD

**Issue by x22x22** [eggjs/egg#2053]
eggjs教程中描述了[RESTful 风格的 URL 定义](https://eggjs.org/zh-cn/basics/router.html#restful-风格的-url-定义).
但是我希望对这个列表添加一些对应的项, 查看egg-core的源码, 是根据REST_MAP这个变量来做映射的.
有没有办法在什么地方, 调用app.resources的时候, 改写这个REST_MAP变量的映射关系吗(不动源码的情况下.)
谢谢!

**Comment by atian25** [comment]
你想加啥？

**Comment by x22x22** [comment]
仔细看了一下RESTful设计的文章, 感觉是我的误区, 所以不用加也可以了. 谢谢!
