### ISSUE TITLE
新需求： 添加支持 nuxt.js 的官方模板或者 demo

### ISSUE THREAD

**Issue by Hellowor1d** [eggjs/egg#2055]
最近在做新项目，了解到 egg.js 被吸引，项目前端使用 vue，需要支持 服务端渲染，想到使用 nuxt.js + egg.js 应该会是不错的搭配，由于对 egg.js 了解的还不够深入，所以来咨询下可行性。
另外已经了解到  @hubcarl  大大 easywebpack 在支持 vue + egg.js 服务端渲染方面的实现，
以及在多个issude 中看到 @atian25 天猪大大本身对于 nuxt.js 的了解，为什么没有直接 集成 nuxt 方案呢，是出于怎样的考量？

ps: 
在其他 issue 下看到过 nuxt-egg, 但是作者最近没更新，新安装项目有报错

这个issue 如果不适合按照这种方式提出的话，请回复，我可以搬移到 知乎 上再请作答，谢谢

**Comment by okoala** [comment]
@Hellowor1d  那个感觉是弃坑了，依赖的 Nuxt 的版本太新，Egg 太旧~ 所以就各种跑不起来~

**Comment by atian25** [comment]
我对 nuxt.js / next.js 现在的发展了解不多，上一次我们看的时候，它们对 Koa 的支持并不是很好，它的模型不支持 Koa 的中间件，所以强行耦合的话要做很多适配，而且效果不一定好。就没再关注了。

如果它们现在对 Koa 的支持完善了，那开发者直接作为一个 middleware 引入到 Egg 应该就可以了。

**Comment by atian25** [comment]
@okoala  你不是魔改了 next 么，还没搞完？

**Comment by okoala** [comment]
@atian25  目前已经完全是 egg 的同构上层框架了，现在在加各种特性，优化什么的~

**Comment by atian25** [comment]
写文档，分享

**Comment by Hellowor1d** [comment]
@okoala 💯 会不会 nuxt 也来一套？哈哈哈~~

**Comment by Hellowor1d** [comment]
@atian25
看到 nuxt.js 的介绍中说明，已经支持 [中间件](https://nuxtjs.org/guide) 了, 不过感觉它这个说的是页面切换之间进行处理的中间件，和 koa 中间件又不太一样？

**Comment by netputer** [comment]
https://github.com/nuxt-community/koa-template

**Comment by KkkkKernc** [comment]
@Hellowor1d 可以参考一下 https://github.com/aov2005/eggjs-ts-typeorm-nuxt-Boilerplate 这个项目，通过middleware的方式引入了Nuxt

**Comment by MR-BH** [comment]
@okoala avet 啥时候能开源？

**Comment by okoala** [comment]
@MR-BH  已经开了，不过之后有可能会迁移到 umi 为底层~

**Comment by aalenliang** [comment]
@KkkkKernc Can't open the repo, is it renamed to this one? https://github.com/aov2005/egg-boilerplate-nuxt

**Comment by KkkkKernc** [comment]
> @KkkkKernc Can't open the repo, is it renamed to this one? https://github.com/aov2005/egg-boilerplate-nuxt

It looks like fiddling with some details but this is it

**Comment by konglingwen94** [comment]
我现在用的是nuxt+koa 的服务端渲染，不过发现egg 这个封装的koa框架不错，但是在用nuxt 作为中间件的时候一直报错， Cannot set headers after they are sent to the client   ，有哪位大神遇到过这种问题吗？欢迎指导

**Comment by konglingwen94** [comment]
> 最近在做新项目，了解到 egg.js 被吸引，项目前端使用 vue，需要支持 服务端渲染，想到使用 nuxt.js + egg.js 应该会是不错的搭配，由于对 egg.js 了解的还不够深入，所以来咨询下可行性。
> 另外已经了解到 @hubcarl 大大 easywebpack 在支持 vue + egg.js 服务端渲染方面的实现，
> 以及在多个issude 中看到 @atian25 天猪大大本身对于 nuxt.js 的了解，为什么没有直接 集成 nuxt 方案呢，是出于怎样的考量？
> 
> ps:
> 在其他 issue 下看到过 nuxt-egg, 但是作者最近没更新，新安装项目有报错
> 
> 这个issue 如果不适合按照这种方式提出的话，请回复，我可以搬移到 知乎 上再请作答，谢谢

我也和你遇到了同样的需求，用了一个egg-nuxt 模板的时候，这个弃坑了，修改源代码也一直没填好，我也正在好其他的解决方案

**Comment by bymomo** [comment]
现在是什么进展呢？

**Comment by kunl** [comment]
马上 2022 了，目前能愉快的玩耍了吗
