### ISSUE TITLE
给 egg-development 的 watcher 添加排除规则

### ISSUE THREAD

**Issue by hjkcai** [eggjs/egg#2056]
在配合 TypeScript 开发时，通常会启动一个 `tsc -w` 来快速编译 TypeScript 文件。但由于 egg-development 默认 watcher 规则是监视文件夹内任何文件的变动，所以当 ts 文件变动时 egg 会重启一次 worker，此时 TypeScript 还没编译完成。等到 TypeScript 编译完成后，egg 发现 js 文件变动，则又会重启一次。

虽然重启一次不需要很长时间，但在开发机器配置不高的情况下其实也是挺慢的。而且如果是在调试模式下，调试器会重连两次，这就非常蛋疼了，所以希望改进一下。

我想的一个方案是在配置文件里面增加 `watcherIgnores` 数组，利用 glob 规则匹配不需要监视的文件。如 `**/*.ts`。

**Comment by atian25** [comment]
目前的 egg-development 是依赖 egg-watcher 的，后者默认的 wt 是不支持 glob 的。

我们目前这边也用 ts，但 egg-development 是有个 debounce 200ms 的，理论上你 tsc 不超过这个时间就不会重启两次的。

目前的解决方式可以是：引入 [egg-watcher-chokidar](https://github.com/eggjs/egg-watcher-chokidar) 这个插件，它支持配置 glob 的。

引入之后，watcher 的默认引擎就会换为 chokidar 了。

cc @eggjs/core @dead-horse 我们当时用 WT 是为了解决原生模块的兼容性问题么?

**Comment by hjkcai** [comment]
就是说在开发机器配置比较差的情况下，200ms实在是太短了。

看了下，egg-watcher-chokidar 里面似乎没有跟 glob 配置有关的内容？

我目前的做法是在私有 npm 里面发了个自定义的 egg-development，直接无视 ts 后缀的文件。

希望这个问题官网能有个好的解决方案而不是 Workaround。

**Comment by atian25** [comment]
chokidar 支持 glob 的。

**Comment by x22x22** [comment]
在项目的配置文件config/config.default.js里加上以下代码即可

```JavaScript
config.development = {
  watchDirs: [],
  ignoreDirs: ['app/db', 'app/public'],
  fastReady: false,
  reloadOnDebug: true,
  overrideDefault: false
};

```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-development/pull/14

**Comment by atian25** [comment]
@hjkcai 更新下依赖，最新版已经支持。

**Comment by hjkcai** [comment]
@atian25 好的！可以的

**Comment by hjkcai** [comment]
@x22x22 个人不是很想再分开 `src` 和 `dist` 文件夹了，这样文件夹结构偏复杂一点。谢谢你的建议。
