### ISSUE TITLE
egg-static 应该需要支持index参数吧?

### ISSUE THREAD

**Issue by x22x22** [eggjs/egg#2058]
egg-static封装的应该是koa的static-cache
但是koa同样有一个static的middleware.
koa/static-cache不支持index很好理解
而且可以由koa/static来弥补.
但是egg-static应该更像koa/static吧, 毕竟从名字上看是这样的.

或者有什么简单的方法实现index.html这种默认文档的功能呢?

**Comment by atian25** [comment]
底层是 `koa-static-cache`，https://github.com/eggjs/egg-static/blob/master/package.json#L26

egg 插件名并不是根据 koa 中间件来取的，在常规的企业应用中，静态文件目录输出这种不是常规需求，因此并不是 egg-static 的功能范围。

简单方式就是你直接引入 koa-static 替换掉原来的插件即可，几行代码搞定
