### ISSUE TITLE
egg-sequelize不能根据EGG_SERVER_ENV来使用对应的配置文件

### ISSUE THREAD

**Issue by qinshou** [eggjs/egg#2060]
我配置了`prod`, `daily`, `local`3个环境，分别对应不同的3个数据库，使用`egg-sequelize`做ORM。

当我执行
```
EGG_SERVER_ENV=daily npm run migrate:down
```
时候，发现生产库被端掉了，经过反复定位后发现，`npm run migrate:down(up)`不管`EGG_SERVER_ENV`指定什么环境，最终都会使用`config.prod.js`。

期望：
`EGG_SERVER_ENV=daily npm run migrate:down`能够使用`config.daily.js`配置文件

**Comment by atian25** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/bin/egg-sequelize.js

cc @huacnlee

**Comment by huacnlee** [comment]
你为何要用 `NODE_ENV=production` ?

**Comment by ngot** [comment]
`当 NODE_ENV 为 production 而 EGG_SERVER_ENV 未指定时，框架会将 EGG_SERVER_ENV 设置成 prod。`

**Comment by qinshou** [comment]
@huacnlee @ngot 

我发现问题是`npm run migrate:down(up)`不管EGG_SERVER_ENV指定什么环境，最终都会使用config.prod.js。

跟NODE_ENV没关系，这里提出来只是把完整命令发一下。

**Comment by atian25** [comment]
`migrate:down` 会跑哪个 cli ？ 估计那边没处理？
可以跟下源码，提个 PR。

**Comment by qinshou** [comment]
@atian25 所以发现bug了有计划修复吗？

**Comment by atian25** [comment]
cc @huacnlee @XadillaX 看看？

**Comment by atian25** [comment]
3.1.1

**Comment by runhwguo** [comment]
设置NODE_ENV即可，例如NODE_ENV=development npm run migrate:up

**Comment by fghpdf** [comment]
运行的时候加载的是 node_modules/egg-sequelize/lib/database.js 这个文件

代码入下：
```javascript
'use strict';
const path = require('path');
const fs = require('fs');

function requireConfig(name) {
  const configPath = path.resolve(`./config/config.${name}.js`);
  if (!fs.existsSync(configPath)) { return {}; }

  let config = require(configPath);
  // FIXME: config init with function need send appInfo argument.
  if ((typeof config) === 'function') { config = config({}); }
  return config.sequelize || {};
}
// EGG_SERVER_ENV=prepub npm run migrate:up
// When EGG_SERVER_ENV is not local or unittest, set it production by default.
const serverEnv = process.env.EGG_SERVER_ENV || 'local';

const defaultConfig = requireConfig('default');
const localConfig = requireConfig(serverEnv);
const unittestConfig = requireConfig('unittest');
const prodConfig = requireConfig('prod');

module.exports = {
  development: Object.assign({}, defaultConfig, localConfig),
  test: Object.assign({}, defaultConfig, unittestConfig),
  production: Object.assign({}, defaultConfig, prodConfig),
};
```

可以发现，如果是通过 EGG_SERVER_ENV  来控制配置的，始终是存在了 localConfig 这个变量里
而只有 development 才从 localConfig 获取配置，所以使用 EGG_SERVER_ENV 来区分环境的需要把
NODE_ENV 设置成 develpment 才行

**Comment by Talbot3** [comment]
@atian25 https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js 
108行 NODE_ENV=production 这个几个意思。一律使用EGG_SERVER_ENV来控制

**Comment by atian25** [comment]
by design.

**Comment by Talbot3** [comment]
> by design.

yeah, that ok.but there has docs, say that 
NODE_ENV map to EGG_SERVER_ENV
https://eggjs.org/en/basics/env.html#mobileAside
or see 
https://eggjs.org/zh-cn/basics/env.html.
are you really by design, i don't think so.that's bug.
