### ISSUE TITLE
Single worker

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#2061]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问假如我的业务逻辑对于多进程没有需求，或者说我需要一个简单的 egg 框架，我应该怎么启动，我尝试过使用 --workers=1 在启动的时候，但是egg还是会起一个 `master` , `agent`, `worker`

**Comment by atian25** [comment]
设计如此，多 2 个进程又没啥损耗。master 相当于守护进程了，省掉 PM2 。
真想定制的话，自己在 egg-core 上封装，定制你自己的 egg-cluster，但无法确保会不会有其他问题。
