### ISSUE TITLE
新需求：app messager 可否传多个参数？agent.messenger.sendRandom('event', 'msg1', 'msg2', 'msg3');

### ISSUE THREAD

**Issue by DragWeb** [eggjs/egg#2062]
```javascript
agent.messenger.sendRandom('event', 'msg1', 'msg2', 'msg3');
```
进程间通讯（IPC）可否支持？
从agent给workers的数据有时是多类型的消息，一般做法直接传递一个Object，但是这一来，就得需要处理数据了，比如agent给workers发送包含Buffer,json string，这时候就需要把Buffer toString()，再发过去，如果支持多参数传递把数据处理的操作交给workers操作岂不是更好？

也就是说IPC只做通讯的事，一点业务都不做，把小事儿交给小兵(workers)处理。

**Comment by atian25** [comment]
- IPC 通信本来就只能是 String ，Buffer 本来就该自己转。
- 多参数本来就应该是 Object，接收方那边用 es6 解构取下即可。
- 如果有需要，可以自己在这之上封装一个方法来封包解包呗。
- 注意，如果是大数据量的，要用 https://eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by atian25** [comment]
> 如果有需要，可以自己在这之上封装一个方法来封包解包呗。

举个例子，你自己封装一个 lib，挂载到 app 和 agent 上。

```js
// 这个方法内部自己处理封包，然后传递给 app.messenger.sendRandom
app.myMessage.send('event', 'msg1', 'msg2', 'msg3');

// 代理 messenger.on 方法，注册监听并处理解包
agent.myMessage.on('event', function('msg1', 'msg2', 'msg3') {});
```
