### ISSUE TITLE
如何使service继承其他load unit中的service类

### ISSUE THREAD

**Issue by Illyrix** [eggjs/egg#2065]
有插件a和插件b, b依赖于a
```javascript
// b/package.json
{
  "name": "token",
  "version": "1.0.0",
  "eggPlugin": {
    "name": "b"
  },
  "dependencies": [ "a" ]
}
```
a提供UserService,希望b能够继承这个service
```javascript
// a/app/service/user.js
module.exports = app => {
  class UserService extends app.Service {
    async getUserList() {
      return [
        { id: '1', name: 'user1' },
        { id: '2', name: 'user2' }
      ]
    }
  }
  return UserService
}
```
1. 通过`app.serviceClasses`取得`UserService`, [https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/service.js#L18](https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/service.js#L18)但是发现在load的时候`app.serviceClasses`是空对象:
```javascript
// b/app/service/token.js
module.exports = app => {
  console.log(app.serviceClasses)                            // 返回 {}
  class TokenService extends app.serviceClasses.user {
    getToken() {
      return '5134126412'
    }
  }

  return TokenService
}
```
2. 使用`app.plugins.a.path`获得a的路径,然后按照路径加载;
但是这种方法对于`module.exports = app => {}`定义service的方式比较难处理,而且插件之间就形成了比较强的耦合

除了两个插件之间service的继承关系外,其他load unit也有可能有service继承的情况;比如框架的继承,继承的框架需要改写被继承框架的service

**Comment by atian25** [comment]
一种实现方式：https://github.com/atian25/egg-showcase/compare/extend-plugin-service?expand=1

**Comment by popomore** [comment]
插件之间建议用组合而不是继承，即 b 调用 a. 的方法

**Comment by Illyrix** [comment]
@atian25 如果a通用性不是很强挂载到app的属性是不是有点混乱?另外
```javascript
module.exports = app => {
  // do something
  return class UserService extends app.Service {
    // ...
  }
}
```
这样`require`返回的是以app为参数的函数,可能还需要参考下`FileLoader`的实现[https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L192](https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L192)

-------------------------
@popomore 是的,组合可以实现,但可能需要额外的代理器隐藏实现; 原来的设想是通过`loadService({ override: true })`让b覆盖掉a(如果path是一样的), 这样对于外部无论有没有(可选的)b插件调用a的方式都是通过`ctx.service.user`

**Comment by atian25** [comment]
你可以挂到 app.xx.xx 都行。不想被别人访问的话，那就用 Symbol。

**Comment by popomore** [comment]
也可以抽一个类来 require，挂 app 有点麻烦。我觉得是抽象问题，这种依赖感觉不是两个插件

**Comment by Illyrix** [comment]
@popomore 这种依赖更像是功能模块(因为模块有依赖关系而插件正好有dependencies解决加载顺序就写成了插件23333),更好的做法是不是写个框架加上自己的loader去load模块?
