### ISSUE TITLE
egg-mysql 能够查询某个时间段或者大于某个时间的数据吗

### ISSUE THREAD

**Issue by crazyEggs** [eggjs/egg#2067]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by crazyEggs** [comment]
我现在使用egg-mysql 希望能够像sequelize一样可以查询某个时间段的数据
可是文档实在是太少了，不知道该怎么做

**Comment by dead-horse** [comment]
写 sql

**Comment by crazyEggs** [comment]
就是因为不清楚使用这个插件如何写sql，才问的，

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/mysql.html#%E7%9B%B4%E6%8E%A5%E6%89%A7%E8%A1%8C-sql-%E8%AF%AD%E5%8F%A5

**Comment by excel555** [comment]
这个只能写SQL吗？
