### ISSUE TITLE
请问egg-core的源码

### ISSUE THREAD

**Issue by 1316346949** [eggjs/egg#2071]
地址是：https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/config.js

第27行：const appConfig = this._preloadAppConfig();   改成 const appConfig = ‘’；也没有影响程序运行，npm run dev方式运行

第69行的参数：extraInject，好像没有作用。好像是在https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js  文件的286用ret(...inject)方式执行，extraInject并不会被传入ret函数里。

**Comment by atian25** [comment]
`_preloadAppConfig` 用于插件里面需要读取用于配置的地方。

如

```js
// app_root/config/config.default.js
exports.name = 'test';

// plugin_root/config/config.default.js
modules.exports = (appInfo, appConfig) => {
  return {
    someDir: `xxx_${appConfig.name}`,
  };
}
```

**Comment by atian25** [comment]
第 2 个没看懂，那个是自定义 loader 是配置 inject 用的。

**Comment by 1316346949** [comment]
@atian25 谢谢你啊，我以为是const appConfig = this._preloadAppConfig(); 是多次一举的。后来看到你发的代码里的appConfig参数就明白了，第二个问题就是问appConfig参数的问题，因为我在所以内置插件的config文件夹里没找到appConfig这个参数被使用的情况，所以以为是BUG

exports.name = 'test';
// plugin_root/config/config.default.js
modules.exports = (appInfo, appConfig) => {
  return {
    someDir: `xxx_${appConfig.name}`,
  };
}
