### ISSUE TITLE
egg-mysql update的问题

### ISSUE THREAD

**Issue by epsv4** [eggjs/egg#2076]
我的代码

```
await app.mysql.update('customer', { valid: '0', end_dt: date, updated_at: date }, {
                where: {
                    id: uid,
                    date: today,
                    valid: '1',
                },
            })
```
生成的sql语句更新字段里面是不包括valid字段的。
这是ali-rds里面的代码

```  
for (let i = 0; i < options.columns.length; i++) {
    const column = options.columns[i];
    if (column in options.where) {
        continue;
    }
    sets.push('?? = ?');
    values.push(column);
    values.push(row[column]);
  }```
为什么要将更新字段里面与where条件里面同名的字段过滤掉？？是有什么深意么。

**Comment by dead-horse** [comment]
如果需要 ORM 支持，使用 egg-sequelize 吧，egg-mysql 更推荐直接写 SQL 的方式

**Comment by stevenluoxiaohua** [comment]
这个问题确实我也遇到了，就比如update customer set valid=1 where valid=0，再平常不过的sql了，为什么要同名字段过滤掉，感觉是个bug

**Comment by Alexis374** [comment]
同遇到

**Comment by koibi2** [comment]
> 如果需要 ORM 支持，使用 egg-sequelize 吧，egg-mysql 更推荐直接写 SQL 的方式

楼主问：“为什么要将更新字段里面与where条件里面同名的字段过滤掉？？是有什么深意么。”
@dead-horse 你答非所问了。
文档推荐了“egg-mysql”这个插件。
居然不支持这么简单的语法。用户体验很不好。

而且看文档：
> https://eggjs.org/zh-cn/tutorials/mysql.html
> **注意！！我们极其不建议开发者拼接 sql 语句，这样很容易引起 sql 注入！！**
