### ISSUE TITLE
使用alinode没有进程数据，当前 node 为非 alinode 版本

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#2078]
* **Node Version**: 9.2.1
* **Egg Version**:2.0.0
* **Plugin Name**:egg-alinode
* **Plugin Version**:2.0.1
* **Platform**:
* **Mini Showcase Repository**:

我按照阿里云提供的[文档](https://help.aliyun.com/knowledge_detail/60907.html?spm=a2c4g.11186623.2.5.lYPUgw) 配置的alinode。
在后台只能看到系统数据，没有进程数据。查看实例信息，显示当前 node 为非 alinode 版本。
请问如何使用 alinode 启动 Egg 应用？

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/deployment.html#nodejs-%E6%80%A7%E8%83%BD%E5%B9%B3%E5%8F%B0alinode

**Comment by Cheese-Yu** [comment]
就是安装上面的流程来的，但是启动的日志里没有[master] alinode version v... egg版本已经升级到2.3.0了

**Comment by atian25** [comment]
跟 egg 版本没关系，https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L105
这里已经把相关目录加入到 PATH 中的，自己检查下看看。

**Comment by Cheese-Yu** [comment]
检查了一下项目下的node_modules里并没有alinode,但是安装的时候提示100%了，不知道安到哪里去了...

**Comment by lu592674374** [comment]
![image](https://user-images.githubusercontent.com/15523855/35778915-03ba36d6-0a00-11e8-8e92-4e466ec1167c.png)
![image](https://user-images.githubusercontent.com/15523855/35778919-1a14f25e-0a00-11e8-97f3-a21355d7165d.png)

**Comment by atian25** [comment]
可能没有打 win 版

**Comment by DuJiming** [comment]
> 检查了一下项目下的node_modules里并没有alinode,但是安装的时候提示100%了，不知道安到哪里去了...

每次npm i之后都会清理掉nodeinstall安装的node
