### ISSUE TITLE
restful api如何配置ignore资源的具体操作

### ISSUE THREAD

**Issue by x007xyz** [eggjs/egg#2081]
* **Plugin Name**:egg-jwt

使用egg-jwt，配置ingore: ‘api/users’可以针对api/users所有接口不做处理，如果我只想对api/users的删除操作不做处理应该怎么配置呢？

**Comment by thonatos** [comment]
请参考：

[Middleware 中间件 - 通用配置](https://eggjs.org/zh-cn/basics/middleware.html#%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE)
