### ISSUE TITLE
CORS 动态修改domainWhiteList

### ISSUE THREAD

**Issue by jinyang1994** [eggjs/egg#2083]
* **Node Version**:
* **Egg Version**: 2.0.0+
* **Plugin Name**: egg-cors
* **Plugin Version**: 2.0.0
* **Platform**:
* **Mini Showcase Repository**:

业务场景是这样的，我们为客户提供一段js进行嵌入，为了解决CORS的问题，我们需要客户提供他们的域名，但是我该如何动态的修改对应的domainWhiteList

**Comment by atian25** [comment]
https://github.com/koajs/cors/blob/master/index.js#L60
从源码来看，这个可以是函数。

**Comment by jinyang1994** [comment]
thx
