### ISSUE TITLE
应用运行后, 直接删除app目录下任意不相关目录会报错Error watching file for changes

### ISSUE THREAD

**Issue by x22x22** [eggjs/egg#2085]
* **Node Version**:v8.9.1
* **Egg Version**:2.3.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Windows 10
* **Mini Showcase Repository**:

1. 先在app目录下随意创建一个目录, 这里就叫test
1. 运行起程序
1. 在文件管理器中删除此test目录
1. 就会报错
报错信息如下:
```
2018-02-06 15:44:09,302 ERROR 12760 nodejs.EPERMError: Error watching file for changes: EPERM
    at _errnoException (util.js:1024:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1351:9)
code: 'EPERM'
errno: 'EPERM'
syscall: 'Error watching file for changes:'
filename: null
dir: 'D:\\xxx\\examples-master\\hackernews-async-ts\\dist\\app\\test'
name: 'EPERMError'
pid: 12760
hostname: xxx
```
EPERM从字面意思是权限问题, 但是我的cmd是管理员权限运行.
这个很明显是我删除了test, 它尝试查看test目录的变化时发现访问不了了.

那么我想知道, 这个东西是在eggjs哪里调用的, 怎么关闭相关的东西.

**Comment by atian25** [comment]
- 为什么你要删除一个目录，这不是常规操作吧，报错也只是这一次，无视就好了。
- 在 egg-development 里面 watcher 的，如果你不想开发期热重启的话，就关掉这个插件。

**Comment by x22x22** [comment]
@atian25 这是项目所需的, 因为我这边需要对静态资源文件夹里的文件做删除操作.
也就是这个目录:
D:\xxx\examples-master\hackernews-async-ts\dist\app\public\xxx

**Comment by atian25** [comment]
配置下 development 的 ignore

**Comment by x22x22** [comment]
@atian25 
没有的, 这个选项仅仅忽略文件的变动, 如果是删除文件夹的操作, 依然会报错的.

**Comment by x22x22** [comment]
不是egg-development的原因

**Comment by atian25** [comment]
静态目录下只有 egg-static 和 egg-development(里面是 egg-watcher) 这 2 个会涉及到，egg-development 只在开发期启动的。

提供下最小可复现仓库，或者自己断点分析下吧。

**Comment by x22x22** [comment]
解决了
首先说明, 在config.js里对development设置是没用的, 比如如下设置:
```JavaScript
development: {
    enable: false,
    watchDirs: [''],
    ignoreDirs: ['app/db', 'app/public', 'app/public/**/*', 'logs', 'app/uploads'],
    fastReady: false,
    reloadOnDebug: true,
    overrideDefault: false
}
```

需要在plugin.prod.js里加
```JavaScript
exports.development = false;
```

然后index.js里加上
```JavaScript
process.env.NODE_ENV = 'production';
process.env.EGG_SERVER_ENV = 'production';
```

index.js完整内容:
```JavaScript
'use strict';
process.env.NODE_ENV = 'production';
process.env.EGG_SERVER_ENV = 'production';
const path = require('path');

const startCluster = require('egg-cluster').startCluster;
startCluster({
  baseDir: path.join(__dirname, 'dist'),
  workers: 1
});
```

然后在生产环境中启动应用即可
```bash
node index.js
```

**Comment by atian25** [comment]
这群代码里面，唯一有用的就是 plugin 那个关闭插件。其他那些都没用的。线上启动直接用 egg-scripts

**Comment by x22x22** [comment]
谢谢

**Comment by atian25** [comment]
但其实 development 本来就不会在 prod 环境启动的。
我试了下你顶楼的步骤，无法复现。

另外，`ignoreDirs` 不支持 glob 表达式的。

**Comment by x22x22** [comment]
是的, prod环境下development不会启动.
之前我看了https://github.com/eggjs/egg-cluster的例子, 直接用的index.js
```JavaScript
const startCluster = require('egg-cluster').startCluster;
startCluster({
  baseDir: '/path/to/app',
  framework: '/path/to/framework',
});
```
 启动, 这个没带环境变量, 就会导致我说的问题. 现在已经知道怎么回事了, 谢谢!
另外按照你说的用egg-scripts, 会自动设置环境为prod, 这样能直接解决这个问题.

**Comment by atian25** [comment]
index.js 这种方式早不推荐了，那是因为你漏了环境变量，导致线上是用 local 启动的，这样的话发现异常是不会自动重启的。

**Comment by x22x22** [comment]
egg-scripts的stop是不是不支持windows?

**Comment by atian25** [comment]
start 和 stop 都不支持，因为没有好用的进程管理模块。
如果你必须部署到 win 的，那就自行看源码实现吧。
