### ISSUE TITLE
函数里面无法调用mysql函数，请指教！谢谢老大..

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#2087]
* editUrl() {
            http.get('http://crs.toyohu.com/user/login', function(req, res) {
                var result = '';
                req.on('data', function(data) {
                    result += data;
                });
                req.on('end', function() {
                    // var $ = cheerio.load(result);
                    // var title=$("title").text();
                    **var url=yield app.mysql.query("select * from images where imgId=1");**
                    console.log(url);
                });
            });
        }

**Comment by atian25** [comment]
1. 你这问题需要回去复习下 es6，yield 只能用在 generator function 里面
2. 用 ctx.curl
