### ISSUE TITLE
egg-sequelize  model:create failed

### ISSUE THREAD

**Issue by foolishchow** [eggjs/egg#2090]
* **Node Version**: 8.9.1
* **Egg Version**: 2.3.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.1
* **Platform**: Mac OSX 10.12.6
* **Mini Showcase Repository**: no

- run cli ` ./node_modules/.bin/egg-sequelize model:create --name sys_menus  --attributes name:string`   
goes into an error
```
Unable to find migrations path (/Users/*/egg/egg-admin/migrations). Did you run sequelize init?
```
 > can we create folder `migrations` auto when `migrations` dont exist?

- after create folder `migrations`
 run cli ` ./node_modules/.bin/egg-sequelize model:create --name sys_menus  --attributes name:string`
goes into an error 

```
Unable to find models path (/Users/*/egg/egg-admin/models). Did you run sequelize init?
```
as we known ,  egg-sequlize auto load folder `app/model` for models, so can we just config `app-path` default to `app/model`

**Comment by huacnlee** [comment]
不支持这个功能，手工创建 model 文件
