### ISSUE TITLE
有没有方案可以拿到所有 worker 的 registry-client 初始化完成的通知

### ISSUE THREAD

**Issue by ImHype** [eggjs/egg#2092]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
`registry-client` 是啥？

启动成功是 `egg-ready` 事件

**Comment by ImHype** [comment]
就是 在Leadewr/Follewer 模式下的 worker 与 agent 建立 tcp 通信，所有 worker 进程都初始化这个 ipc 通道之后，会有时间通知 agent 进程吗

**Comment by dead-horse** [comment]
```js
agent.messenger.once('egg-ready', () => {
  // egg all workers and agent get ready
})
```
