### ISSUE TITLE
nunjucks plugin how to Customize Syntax ?

### ISSUE THREAD

**Issue by salamander-mh** [eggjs/egg#2094]
```
var env = nunjucks.configure('/path/to/templates', {
  tags: {
    blockStart: '<%',
    blockEnd: '%>',
    variableStart: '<$',
    variableEnd: '$>',
    commentStart: '<#',
    commentEnd: '#>'
  }
});
```
don't know how to configure in eggjs

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view-nunjucks#more

try `app.nunjucks`, it's a nunjucks environment instance.

**Comment by salamander-mh** [comment]
it seems you can just add `tags`  to the config:
```
exports.nunjucks = {
    enable: true,
    package: 'egg-view-nunjucks',
    tags: {
        blockStart: '{%',
        blockEnd: '%}',
        variableStart: '<$',
        variableEnd: '$>',
        commentStart: '<#',
        commentEnd: '#>'
    }
};
```
I've tried, it works.

**Comment by atian25** [comment]
oh, thanks for remain me, yes, it support by https://github.com/eggjs/egg-view-nunjucks/blob/master/config/config.default.js

but @salamander-mh your code got a bit problem: `package` and `enable` should place in `plugin.js` not `config.default.js`, you confuse them.

**Comment by zhangwen9229** [comment]
> it seems you can just add `tags` to the config:
> 
> ```
> exports.nunjucks = {
>     enable: true,
>     package: 'egg-view-nunjucks',
>     tags: {
>         blockStart: '{%',
>         blockEnd: '%}',
>         variableStart: '<$',
>         variableEnd: '$>',
>         commentStart: '<#',
>         commentEnd: '#>'
>     }
> };
> ```
> I've tried, it works.

it doesn't work for me. any other answer?

**Comment by atian25** [comment]
@zhangwen9229 raise your own issue and submit with a mini project which could reproduce issue.
