### ISSUE TITLE
egg-scripts的options问题

### ISSUE THREAD

**Issue by andylei18** [eggjs/egg#2097]
egg-script 是部署用的命令有start和stop,其中如果我启动的是1个path的framework的应该是什么样的？
代码如下: 一直报错
"start": "eggctl start --port=7070 --daemon --framework=/fe-xxx-project/packages/xxx-node-new/package.json --env=prod --title=egg-server-fe-xxxx-project --ignore-stderr"

⚠️  AssertionError [ERR_ASSERTION]: /fe-era-project/packages/era-node-new/package.json should exist
⚠️  Command Error, enable `DEBUG=common-bin` for detail

**Comment by atian25** [comment]
包名

**Comment by andylei18** [comment]
@atian25 还没发成包就不行？

**Comment by atian25** [comment]
没发包的用 npm link 来测试

https://github.com/atian25/blog/issues/17
