### ISSUE TITLE
定时器怎样调用controller下home中的testTimer方法

### ISSUE THREAD

**Issue by yangliangbo** [eggjs/egg#2100]
#controller/home.js

'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    this.ctx.body = 'hi, egg'; 
  }

  async testTimer() {
  	console.log('======egg timer test=========');
  }

}

module.exports = HomeController;

**Comment by atian25** [comment]
把 `testTimer` 挪到 Service 中
