### ISSUE TITLE
请教egg-logger高级自定义日志的使用

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#2103]
* **Node Version**:8.9.4
* **Egg Version**:2.3.0
* **Plugin Name**:egg-logger
* **Plugin Version**:1.6.1
* **Platform**:linux
* **Mini Showcase Repository**:

使用egg-logger定义一个日志的 transport，例如[文档](https://eggjs.org/zh-cn/core/logger.html#%E9%AB%98%E7%BA%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%97%A5%E5%BF%97)中RemoteErrorTransport ，这个文件应该放在哪个目录，有约定吗？

**Comment by atian25** [comment]
没有强制约定，一般我们习惯放到 `lib/**`
