### ISSUE TITLE
don't load plugin.{env}.js at plugin/framework

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#2108]
from https://github.com/eggjs/egg-core/pull/153#issuecomment-364315091

仔细思考了下 @whxaxes 的场景，我觉得是可以避免的。

当时支持 `plugin.{env}.js` 的主要用途是：
**应用层的一些本地开发构建期的插件，期望放到 devdeps 依赖**

所以通过 `plugin.local.js` 可以支持。

但当时我们的实现，感觉有点过了：
- 在框架层面，插件肯定必须是 deps 而不是 devdeps，因此在框架层是只有 plugin.js 的
- 在应用层面，才有 `plugin.{env}.js`

因此，我们是不是需要优化下：
- 修改插件文档，注明只能在应用层用 local
- 修改 egg-core 只加载应用层的 `plugin.{env}.js`

cc @popomore @eggjs/core

**Comment by popomore** [comment]
这个还是不要改了，不然缺少一致性。

框架定义插件，在然后在某些环境可以关闭比如本地静态资源调试，框架可以集成这个功能，默认关闭，但在 local 开启，这种是很常见的用法。

**Comment by atian25** [comment]
这个场景我们这边有，我理解。
不过这类插件一般本身的 env 就会配置为 local 了，框架层我倾向于是在 plugin.js 去引入，而不是 plugin.local.js。

一致性是一个问题，那就文档提示即可。

**Comment by popomore** [comment]
引入都是 plugin.js，环境来控制开关

**Comment by atian25** [comment]
嗯，之前文档误导了。
