### ISSUE TITLE
中间件文档中的app.js在什么位置

### ISSUE THREAD

**Issue by honestxll** [eggjs/egg#2109]
现在使用的是 `2.2.1` 的 eggjs，实在没找到 `app.js` 的位置在哪，抱歉，文档应该不是最新的吧，比如 `config` 配置就和文档上的不一样😰

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/structure.html

**Comment by atian25** [comment]
> 比如 config 配置就和文档上的不一样
具体指?

**Comment by honestxll** [comment]
非常抱歉，自己捣鼓了一下解决了问题：）耽误了您的宝贵时间，真的很抱歉。

**Comment by atian25** [comment]
等等，放学别走，把问题说清楚先哈~~

是文档哪里没写清楚还是你看错？

**Comment by honestxll** [comment]
原因是因为我没有理解 `在框架和插件中使用中间件` 的 `框架和插件` 的意思，因为我读起来感觉有点奇怪，一开始没能理解，插件的意思应该是在 `node_modules` 下面，而框架应该就是项目的根目录下。当我看到了 `框架和插件不支持在 config.default.js 中匹配 middleware`，这句话的时候，我是懵逼的，纳尼，难到我用文档上面的方法创建中间件不行？于是搞错了方向，导致了项目 crash。

**Comment by honestxll** [comment]
另外
> 比如 config 配置就和文档上的不一样
指的是写法和文档不一样，现在直接是导出了一个对象，对于刚接触 nodejs 和 es6 时间不是很长的新人来说，你懂的😅

**Comment by atian25** [comment]
我很懂的... 看 https://github.com/eggjs/egg/issues/2088

**Comment by honestxll** [comment]
非常感谢：）
