### ISSUE TITLE
支持 app/init.js

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#211]
提供一个方法在 loader 同步加载完后执行

## 场景

应用自定义加载时，在 app.js 中需要调用 service，而 service 在之后加载。如果将 service 移到前面，如果 service 启动时需要使用 app.js 中初始化的客户端就会有问题。

所以提供一个统一的入口给应用初始化

## 实现

在 loader 增加一个方法 loadAppInit，虽然叫这个名字，但在框架和插件也可以使用。应用只推荐使用 init.js，插件推荐使用 app.js。

调用 loadAppInit 和 loadCustomApp 的实现基本相同。

https://github.com/eggjs/egg/blob/5e6fcf913b057607459a29f6ed90a2780d0e9bdf/docs/source/zh-cn/basics/app-start.md

**Comment by atian25** [comment]
直接加一个 hook ?

```js
// app/hook.js
module.exports = {
  beforeLoad() {}
  afterLoad () {}
};
```

**Comment by popomore** [comment]
加载时基本上只有这个场景了，beforeLoad 没啥用
TZ | 天猪 <notifications@github.com>于2017年1月10日 周二10:12写道：

**Comment by atian25** [comment]
整个 egg 的过程, 不仅仅是 loader 呢?

**Comment by popomore** [comment]
启动过程基本就是 loader
TZ | 天猪 <notifications@github.com>于2017年1月10日 周二10:18写道：

**Comment by atian25** [comment]
那换个角度, 我们现在有 `app.on('ready', () => {})` , 这个需求能不能转换为 `app.on('loaded', () => {})`

**Comment by fengmk2** [comment]
@atian25 我们想复杂了，app.js 默认不能支持 generator 的，会在 `app.beforeStart(function* () {})` 来做异步依赖等待。

**Comment by fengmk2** [comment]
app/init.js 方案会废弃掉。

**Comment by popomore** [comment]
换成这个方案 https://github.com/eggjs/egg/issues/227
