### ISSUE TITLE
报出413：Payload Too Large，如何设置bodyparser的limit？

### ISSUE THREAD

**Issue by sususususuke** [eggjs/egg#2112]
* **Node Version： 8.9.2**:
* **Egg Version：2.0.0**:
* **Platform：Window 7**:

Ajax提交的数据过大，而报出HTTP 413：Payload Too Large。egg后台显示当前限值为102400，在什么地方可以配置这个限值呢？

**Comment by duncup** [comment]
#1422

**Comment by sususususuke** [comment]
谢谢！

**Comment by weijiatan456** [comment]
一般来说，浏览器上都是通过 Multipart/form-data 格式发送文件的，egg框架通过内置 Multipart 插件来支持获取用户上传的文件
看官网：https://eggjs.org/zh-cn/basics/controller.html#body

可以到：config.default.js
`config.multipart = {
        fileSize: '30mb',  // 文件大小30MB
    }`
