### ISSUE TITLE
希望在onerror里能直接返回json

### ISSUE THREAD

**Issue by xiaosefengyun** [eggjs/egg#2113]
![image](https://user-images.githubusercontent.com/12832248/36084896-6057ef58-0ffc-11e8-9b83-d327a439a53a.png)

这样写会报The first argument must be one of type string or Buffer，能否在这里直接可以返回Object？

**Comment by duncup** [comment]
我的项目里就是直接对象进去的。你确定你的报错不是在其他地方？

**Comment by xiaosefengyun** [comment]
#1784 这里的用户和我提出的问题一致，猜测原因是我这边请求没指定json类型，所以会要求返回个string.

**Comment by duncup** [comment]
看起来你是在config里做的？我没在里面做。可能情况不一样。如果是这种情况你也可以自己加一行JSON.stringify来解决。
比如坑爹的写一行
```js
ctx.body = JSON.stringify(ctx.body);
```

**Comment by xiaosefengyun** [comment]
我知道这种方案，但是我不想这样，而且这样返回给前端也是个string不是json

**Comment by duncup** [comment]
前端拿到的json就是一个json string。json本身就是一个文本格式。

**Comment by duncup** [comment]
另外关于这部分我想起了点东西，https://github.com/eggjs/egg-onerror#usage。如果你不用all而改用accepts或者json似乎可以解决问题？

**Comment by xiaosefengyun** [comment]
谢谢我用accepts解决了这个问题。

**Comment by qq578023708** [comment]
虽然json确实是一个字符串，但是 用JSON.Stringify输出的和 直接输出的，结果是不一样的，用JSON.Stringify包装输出的，你前端必须使用 JSON.Parse 来格式化，才可以使用，但如果用 ctx.body={} 直接输出，前端不需要使用JSON.Parse来格式化就可直接用，并且使用 asccepts 来进行强制JSON，返回的也是HTML格式的错误。
采用中间件的方式，是可以直接输出json对象的，但不知道中间件是否可以捕获到所有的异常错误。
