### ISSUE TITLE
请问如何使用express插件？

### ISSUE THREAD

**Issue by sitting2002** [eggjs/egg#2114]
因项目需要用到以下插件express-ntlm
https://github.com/einfallstoll/express-ntlm

请问egg如何整合express的插件呢？
不胜感激

**Comment by duncup** [comment]
貌似你可以改用https://github.com/auth0/passport-windowsauth

**Comment by atian25** [comment]
找对应的 koa 版。

Koa 和 Express 模型是不兼容的。

**Comment by sitting2002** [comment]
@duncup 谢谢你的建议我尝试一下

**Comment by sitting2002** [comment]
@atian25 好的 我知道了。谢谢🙏
