### ISSUE TITLE
写插件的时候为什么给 app 上面挂载变量，或者 config 上面挂载变量，在 controller 拿不到？

### ISSUE THREAD

**Issue by MiYogurt** [eggjs/egg#2115]
无论是给 app 、context、config 好像都拿不到。

代֒码֒仓֒库֒在֒这֒里֒。

https://github.com/MiYogurt/egg-y-validator

**Comment by atian25** [comment]
你在哪里挂？没看到

**Comment by MiYogurt** [comment]
https://github.com/MiYogurt/egg-y-validator/blob/b5a68c424f99c9f8b72c690d144c2df53ea2ca42/lib/loader.js#L37

**Comment by MiYogurt** [comment]
@atian25  npm run test 在֒ loader.js 里֒面֒能֒打֒印֒出֒来֒，在֒ test 文֒件֒里֒面֒的֒测֒试֒文֒件֒打֒印֒不֒出֒来֒。

**Comment by popomore** [comment]
麻烦自己确认下是否挂载了

**Comment by atian25** [comment]
@MiYogurt 是解决了吧？新代码没看到有 loader 了。
