### ISSUE TITLE
单页面应用，直接输入URL404

### ISSUE THREAD

**Issue by lee84233** [eggjs/egg#2119]
vue的单页面应用，放在 `/app/view/` 下，直接浏览器输入某个URl报404.
路由是vue路由，egg-router只是 `/` 默认加载 `index.html`
示例: 浏览器直接访问 http://localhost:8000/user/id 就会返回 404

**Comment by atian25** [comment]
你如果用 vue html5 mode 的话，egg 这边肯定要配一个通配的路由
