### ISSUE TITLE
About The code sample in Quick Start, got 500 error

### ISSUE THREAD

**Issue by max8hine** [eggjs/egg#2120]
I've been following the Quick Start example code but running into the 500 Error Page
![image](https://user-images.githubusercontent.com/15165714/36451119-d580ec40-16f4-11e8-969d-d797799675b1.png)

and I could not open `https://hacker-news.firebase.com/v0` in the browser.

Is the link still available to access?

**Comment by atian25** [comment]
GFW

**Comment by max8hine** [comment]
@atian25 thank you for the prompt reply. T.T

**Comment by lei40251** [comment]
那这个要怎么办呢？翻墙了也不行啊。。。

**Comment by max8hine** [comment]
@lei40251 I don't think it is about the GFW, more likes a issues with API server

**Comment by lei40251** [comment]
https://hacker-news.firebaseio.com/v0/topstories.json

这个地址我放浏览器里面就可以。。。

**Comment by max8hine** [comment]
hacker-news.firebaseio.com/v0/topstories.json

the above URL works for me as well.

don't know why `hacker-news.firebaseio.com/v0/` not working.

access using latest Chrome from overseas

**Comment by atian25** [comment]
你 chrome 翻墙没用... 是 node 去 http 请求的，要整个系统翻墙

后面有时间改为 github trending 示例好了，欢迎 PR
