### ISSUE TITLE
修复 ci

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#2122]
- [x] https://travis-ci.org/eggjs/egg-logrotator @popomore
- [x] https://travis-ci.org/eggjs/egg-ci @popomore
- [x] https://travis-ci.org/eggjs/egg-view-nunjucks
- [x] https://travis-ci.org/eggjs/egg-boilerplate-empty
- [x] ~~https://travis-ci.org/eggjs/vscode-eggjs~~
- [ ] https://travis-ci.org/eggjs/egg-knex
- [x] ~~https://travis-ci.org/eggjs/autod-egg~~
- [x] [egg-cluster 覆盖率](https://github.com/eggjs/egg-cluster/pull/57#discussion_r163747677) @popomore

**Comment by atian25** [comment]
补一个，避免忘记了。
-[ ] [egg-cluster 覆盖率](https://github.com/eggjs/egg-cluster/pull/57#discussion_r163747677)

**Comment by popomore** [comment]
autod-egg 关闭

**Comment by popomore** [comment]
@sunfuze knex 要把 ci 搞过了

**Comment by popomore** [comment]
@atian25 剩下的给你了

**Comment by atian25** [comment]
- vscode-eggjs 没有单测的，我关掉 travis 服务了。
- egg-boilerplate-empty 是 autod 问题，重跑后 OK 了。
- nunjucks 那个好像 cache 挂了，我看看

**Comment by atian25** [comment]
nunjucks 的那个是 3.1.0 的 bug，先临时 `~` 等官方修复。

- https://github.com/eggjs/egg-view-nunjucks/pull/25
- https://github.com/mozilla/nunjucks/issues/1074

**Comment by atian25** [comment]
- nunjucks 的修复了 https://github.com/eggjs/egg-view-nunjucks/pull/26
- cluster 的也 ok 了 https://github.com/eggjs/egg-cluster/pull/58

只剩下 @sunfuze 的 egg-knex 了.

**Comment by popomore** [comment]
那先关了吧

**Comment by popomore** [comment]
egg-knex 移到个人仓库下

**Comment by atian25** [comment]
@okoala 跟进下迁移的事吧

**Comment by okoala** [comment]
如果 @sunfuze 今天没进行回复，那就先迁移到我的个人仓库里~

**Comment by atian25** [comment]
@okoala 你先 fix 下 ci 吧

**Comment by okoala** [comment]
我先签过来吧
