### ISSUE TITLE
感觉 nest.js 架构方面做的比 egg 好，可以学学 GraphQL  typeorm 支持

### ISSUE THREAD

**Issue by zuohuadong** [eggjs/egg#2124]
https://github.com/nestjs/nest

感觉这个框架从思想上很 spring ，完全解决了 node 架构问题～

可以向这个方向发展

**Comment by atian25** [comment]
这些都是插件里面解决的，有 egg-graphql 等。

至于装饰器这个，用 TS 写 egg 这边我们有实践，后面会分享出来。
