### ISSUE TITLE
hostname配置不生效

### ISSUE THREAD

**Issue by fyAgent** [eggjs/egg#2126]
Node Version:8.9.0
Egg Version: 1.8.0
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:

//app/config/config,default.js  //只有一个配置文件
module.exports = appInfo => {
const config = exports = {};
config.cluster = {
    listen: {
      port: 3000,
      hostname: "192.168.11.117"
    }
 }
 return config;
｝

这样hostname还是不生效 ，因为自己练着写个聊天室，有可能在手机上或者别的地方也想看看 所以hostname 设置成IPV4地址，但是不生效啊，去看了看egg-bin的文档也没说可以配置hostname。这个不科学啊 

 `2018-02-24 11:38:09,029 INFO 8232 [master] node version v8.9.0`
 ` 2018-02-24 11:38:09,031 INFO 8232 [master] egg version 2.3.0`
 ` 2018-02-24 11:38:10,210 INFO 8232 [master] agent_worker#1:10120 started (1173ms)`
 ` 2018-02-24 11:38:11,924 INFO 8232 [master] egg started on http://127.0.0.1:3000 (2892ms) with STICKY MODE!`

**Comment by fyAgent** [comment]
实在 --sticky 模式下运行的

**Comment by fyAgent** [comment]
是在 --sticky 模式下运行的

**Comment by popomore** [comment]
是说打印那条没生效？还是说不能用？

**Comment by popomore** [comment]
sticky 没支持 hostname

**Comment by fyAgent** [comment]
发现确实是像您说的那样 但是我把--sticky去掉了发现socket.io还是可以跑起来啊，那么官方文档说的 

> 框架是以 Cluster 方式启动的，而 socket.io 协议实现需要 sticky 特性支持，否则在多进程模式下无法正常工作。

> 由于socket.io 的设计，在多进程中服务器必须在 sticky 模式下工作，故需要给 startCluster 传递 sticky 参数。
这句话的意义是什么呢 如果不再--sticky下跑会有什么隐患吗

**Comment by popomore** [comment]
就是你启动多个 worker 会有问题

**Comment by ngot** [comment]
不加 --sticky 多进程下跑不起来

**Comment by shizhx** [comment]
> sticky 没支持 hostname

同样的问题，`sticky` 模式为何没有支持 `hostname`，直接监听在 `0.0.0.0` 上很危险
