### ISSUE TITLE
不确定是不是内存泄露，帮忙看下

### ISSUE THREAD

**Issue by acthtml** [eggjs/egg#2128]
简单的hello world请求，测试时内存上升，测试结束，内存没有回落。

# 用例 hello world
测试环境为docker，1cpu，2g，ssd。
测试代码和镜像见源码 https://github.com/acthtml/eggjs-stress-test
eggjs v2.x 和 v1.x都测试过，都有这个现象。
![0d72dabc-16fd-4e70-9b6a-597d853b4658](https://user-images.githubusercontent.com/1704913/36625332-86115558-1958-11e8-8ae7-b5db8482f0db.png)

**Comment by atian25** [comment]
朴老师原话：没有高于 500m 不要讨论内存泄漏

**Comment by acthtml** [comment]
@atian25  因为我在排查项目内存泄露的原因，所以，我逐渐添加模块看看。

那我这个问题大家先忽略。：）

**Comment by atian25** [comment]
你直接接入 alinode 然后压测就好了，已经全面免费开放了。
https://eggjs.org/zh-cn/core/deployment.html#nodejs-%E6%80%A7%E8%83%BD%E5%B9%B3%E5%8F%B0alinode

**Comment by tong3jie** [comment]
> 朴老师原话：没有高于 500m 不要讨论内存泄漏

那我撤了，正想问这个问题呢。
