### ISSUE TITLE
router 中的中间件无法获取 app 对象

### ISSUE THREAD

**Issue by romoo** [eggjs/egg#2131]
* **Node Version**:
8.9.4

* **Egg Version**:
2.3.0

* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:
https://github.com/romoo/egg-middleware-params-demo

应用中的中间件可以获取到 app 对象，router 中的中间件获取不到 app 对象。

**Comment by atian25** [comment]
你自己初始化的，肯定要自己传进去啊。。。

`const test = app.middleware.test({}, app);`

或者用 `ctx.app` 就可以了。
