### ISSUE TITLE
vscode安装eggjs插件失败(找不到与此代码版本兼容的eggjs版本)

### ISSUE THREAD

**Issue by BYmax1** [eggjs/egg#2132]
![1519612205 1](https://user-images.githubusercontent.com/17384794/36650811-56d068e0-1ae0-11e8-8819-433aadf3d7e5.jpg)

**Comment by atian25** [comment]
这是 vscode 本身的问题，跟 egg 没关系。
猜测是你的 vscode 版本太低。
