### ISSUE TITLE
egg ts ctx.request.body

### ISSUE THREAD

**Issue by dahuahe** [eggjs/egg#2137]
![image](https://user-images.githubusercontent.com/16739083/36660090-c61b501c-1b11-11e8-9ea7-9757b32be080.png)

在index.d.ts中 body 类型定义不妥当吧?
![image](https://user-images.githubusercontent.com/16739083/36660172-26feb72a-1b12-11e8-9ca5-eb70198377f9.png)

**Comment by whxaxes** [comment]
@shepherdwind 当初这里这样写的目的是？

我看到 koa-bodyparser 返回的类型就是 any，是否直接跟它保持一致使用 any 就可以了？

**Comment by shepherdwind** [comment]
可以改成 any ，现在这样的类型用起来会有些麻烦。

**Comment by whxaxes** [comment]
@dahuahe  欢迎提个 PR

**Comment by shepherdwind** [comment]
一开始这样写是从 jsdoc 里 copy 过来的，这样比较准确一些。写的话要这样

```js
if (typeof ctx.request.body === 'array') {
  throw 'xxx';
}
ctx.request.body.test;
```

**Comment by dahuahe** [comment]
直接any  不好吗?嘿嘿

**Comment by hellopao** [comment]
我都是这样用的 
```typescript
const {test} = ctx.request.body as any;
```

**Comment by tudou527** [comment]
新项目可以 `as any`，老项目文件太多就不好这么改了
