### ISSUE TITLE
结合typescript，本地开发环境遇到的问题

### ISSUE THREAD

**Issue by wuhw** [eggjs/egg#2140]
使用typescript进行开发，在本地开发阶段，是否都是需要先tsc下，将ts编译成js，然后才能通过egg-bin来启动服务。
是否可以结合ts-node来省略手动编译ts到磁盘的步骤

**Comment by atian25** [comment]
`"dev": "npm run tsc && concurrently -r \"npm run tsc:w\" \"egg-bin dev\"",`

目前我们有同学是这么用的。 `ts-node` 这个我看过，目前的问题在于 egg-core 只加载 js 文件。

cc @popomore 看看？如果能 ts-node 的话，能省不少事。

**Comment by popomore** [comment]
最好支持 `egg-bin dev --typescript`

不过要在 app_worker 和 agent_worker 添加 ts-node/register

**Comment by wuhw** [comment]
@atian25 @popomore 是否可以参考下nodemon

**Comment by atian25** [comment]
@popomore 问题在于 egg-core 不支持加载 ts 文件

**Comment by popomore** [comment]
ts-node 就行了吧

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L123

**Comment by wuhw** [comment]
@atian25 刚也看到这段代码，正想问是否能通过这个match来进行配置

**Comment by wuhw** [comment]
[https://github.com/eggjs/egg/blob/master/lib/loader/app_worker_loader.js#L24](https://github.com/eggjs/egg/blob/master/lib/loader/app_worker_loader.js#L24)
只有这里会去进行load吗，都是不带参数的。。

**Comment by atian25** [comment]
这里有一种情况就是插件开发者 loadFile 的时候，写了后缀名。

我之前想的有点过了，现在 service 之类的都是 directory，而没有后缀名。

@popomore

**Comment by popomore** [comment]
有 ts-node 应该增加 `require('xx.ts')` 就好了吧。

**Comment by popomore** [comment]
开发的时候测试下就知道了，思路应该没问题。

**Comment by wuhw** [comment]
看了下代码  很多loader在load的时候都限制了文件名或者扩展类型，都不支持ts。上层应用就很难做了

**Comment by atian25** [comment]
@popomore 不行了，如 `app/extends/context.ts` 就不会被 load 了。

**Comment by popomore** [comment]
所以要改啊

**Comment by wuhw** [comment]
有计划吗   ts友好支持  真的很需要啊

**Comment by popomore** [comment]
可能需要几个月，会陆续开始开发。

**Comment by atian25** [comment]
@wuhw TS 的 RFC 我们还在整理中，会陆续放出来。ts-node 这个并不是先决条件。

**Comment by popomore** [comment]
单独跟进
