### ISSUE TITLE
Extend Loader 支持子文件夹扩展

### ISSUE THREAD

**Issue by huacnlee** [eggjs/egg#2141]
随着业务量越来越复杂，应用里面的 Context, Application 扩展会写得越来越大，里面包含非常多的函数。

我在应用中自己剥离，按功能拆分分：

```
app
  extend
    application
      logger.js
    context
       ability.js
       response_format.js
       rate_limit.js
       admin.js
       error_handler.js
    context.js
    application.js
```

然后在 context.js 里面将他们合并：

```js
const Context = {
  requireUser() {
    if (!this.currentUser) return this.redirect('/login');
  }

 ... 可能还有好多个函数
}

require('./context/ability')(Context);
require('./context/rate_limit')(Context);
require('./context/response_format')(Context);
```

-----

我阅读了一下 egg-core，实际上只需要稍微修改就可以通过框架来支持这样的拆分写法，自动将 `app/extend/context.js` 和 `app/extend/context/*.js` 作为 `Context` 的扩展（同理 application.js 的扩展也是这样）。

只需要修改 https://github.com/eggjs/egg-core/blob/70b2dc6893e36778ef9390a9fbb5c40aa9ae6718/lib/loader/mixin/extend.js#L82 这行，让他可以读取 `app/extend/context/*.js` 就可以了。

这样以来，就可以很轻松的按业务才分成多个子文件，维护起来更清晰。

**Comment by fengmk2** [comment]
@huacnlee 既然连源代码都看了，直接 PR 起。

**Comment by dead-horse** [comment]
这个我来接手处理吧，确定两个细节，以 context 举例：

- 自动载入 `app/extend/context/` 目录或者 `app/extend/context.js` 文件（优先 context.js 文件以保证兼容性）
- 如果是目录，可以多层级，但是不允许任何的 key 重复，载入提示冲突

**Comment by popomore** [comment]
这个还改吗

**Comment by atian25** [comment]
@dead-horse how about this now ?
