### ISSUE TITLE
egg-mock: mock.cluster() should support the same api with mock.app()

### ISSUE THREAD

**Issue by ngot** [eggjs/egg#2142]
* **Node Version**: 8.9
* **Egg Version**: 2.0
* **Plugin Name**: null
* **Plugin Version**: null
* **Platform**: all
* **Mini Showcase Repository**:
null

mock.cluster() should support the same api with mock.app()

e.g:

- app.config
- app.createAnonymousContext
- more...

**Comment by fengmk2** [comment]
所有 api 都需要？具体是什么场景会需要所有 api？

**Comment by fengmk2** [comment]
createAnonymousContext 这个搞不定

**Comment by fengmk2** [comment]
app.config 返回的是只读数据，并且有可能出现 JSON 序列化异常，还是不行。

**Comment by popomore** [comment]
之前是想 js 如果可以搞的序列化还是可以解的。

**Comment by fengmk2** [comment]
@popomore 只读可以，但是想要实现修改 worker 的 config，实现成本太高，而且这样写单测没场景吧。

**Comment by popomore** [comment]
恩，所以之后就没花这个时间了

**Comment by ngot** [comment]
目前我就遇到这两个，不过都用其他方法先绕过了

**Comment by fengmk2** [comment]
const ctx = app.createAnonymousContext() 拿到的 ctx 其实无法使用的，它是只读的。

**Comment by atian25** [comment]
这个还做么？
