### ISSUE TITLE
如何扩展 RESTful 约定的 REST_MAP ？

### ISSUE THREAD

**Issue by my9074** [eggjs/egg#2147]
* **Node Version**:
8.9
* **Egg Version**:
2.3

我司定义的 RESTful API 风格和 ```egg-core``` 中 ``` REST_MAP``` 定义的不太一样。
例如 :
```js
posts/:id  POST  // REST_MAP 中就没有对应
posts/:id/xxx  GET // REST_MAP 中就没有对应
``` 
>
请问像这样非特别标准的 api 设计如何能扩展？？

**Comment by popomore** [comment]
用 app.resources

**Comment by my9074** [comment]
@popomore  嗯 ，这个我看到了。。
```js
router.resources('dbinstances', '/api/v1/regions/:regionName/dbinstances', controller.v1.dbInstances);
router.post('/api/v1/regions/:regionName/dbinstances/:id', controller.v1.dbInstances.action);
```
我目前是这么解决的，通过 ```router.[method]``` 去匹配 ```REST_MAP```匹配不到的。但是感觉这样不太优雅。

直接通过 ```app.resources``` 如何扩展？

**Comment by popomore** [comment]
这个没有，你可以再加个 action 实体，这样已经不是 rest 了。
