### ISSUE TITLE
vscode的 错误语法提示: [ts] 类型“SupplierController”上不存在属性“logger”。

### ISSUE THREAD

**Issue by songyazhao** [eggjs/egg#2148]
* **Node Version**: 8.4.0
* **Egg Version**:  2.1.0
* **Mini Showcase Repository**: NULL

### package.json
```js
{
  "dependencies": {
    ...
    "egg": "^2.1.0",
    "egg-cors": "^2.0.0",
    "egg-logger": "^1.5.0",
    "egg-validate": "^1.0.0",
    "egg-view-vue-ssr": "^3.0.2"
     ...
  },
  "devDependencies": {
    ...
    "typescript": "^2.6.2"
    ...
  }
}
```

我这个是用 `typescript` 写的一个项目,在 `controller` 和 `service` 里通过 `this.logger` 输出日志信息的时候都会得到这样的错误提示, 但实际上在控制台看到是可以正确的输出日志信息的

`[ts] 类型“SupplierController”上不存在属性“logger”。`

另外试过使用 `this.app.logger` 不会出现这个提示

![tim 20180228173453](https://user-images.githubusercontent.com/23444330/36780352-b61e75de-1cad-11e8-919f-ecf36a2d7c97.png)

### app/core/base-controller.ts
```ts
import { Controller } from 'egg';

export default class BaseController extends Controller {
  success(data = {}, msg = '操作成功') {
    this.ctx.body = {
      code: 50000,
      data,
      msg
    };
  }

  fail(data = {}, code = 50001, msg = '操作失败') {
    this.ctx.body = {
      code,
      data,
      msg
    };
  }
}
```

**Comment by whxaxes** [comment]
刚看了一下，描述文件里应该是漏了这个 logger ，我待会发个 PR 补上
