### ISSUE TITLE
egg.js似乎把前台JSON数据里的属性值都转成字符串了。

### ISSUE THREAD

**Issue by 2015-lizaiyang** [eggjs/egg#2152]
<img width="609" alt="qq20180302-111223 2x" src="https://user-images.githubusercontent.com/21666293/36881796-12dd4698-1e0b-11e8-9856-0f6c254cbc0b.png">
<img width="1435" alt="qq20180302-112435 2x" src="https://user-images.githubusercontent.com/21666293/36882010-55752100-1e0c-11e8-8571-1ec64d40bc67.png">
<img width="507" alt="qq20180302-111652 2x" src="https://user-images.githubusercontent.com/21666293/36881820-3b196498-1e0b-11e8-8920-c4d0c17df475.png">
上图是相关代码。
JSON属性值全转成了字符串，做数据验证那不是很麻烦。如何避免这个问题？？？

**Comment by atian25** [comment]
你前端提交的时候，明明是 String 类型。。。。

**Comment by 2015-lizaiyang** [comment]
我的锅，sorry！
