### ISSUE TITLE
egg-scripts进行应用部署的问题

### ISSUE THREAD

**Issue by wuhw** [eggjs/egg#2158]
egg-scripts 进行应用部署的问题：
1. 查看机器上运行着的egg服务
2. 查看某个egg服务的运行状态
3. 版本更新，如何重启

**Comment by atian25** [comment]
1. 自己 PS (建议 docker 化)
2. 接入 alinode 等监控平台
3. 前面挡个 LB 挡流量，重启

**Comment by wuhw** [comment]
加了负载均衡后，依次执行stop和start？
这有实际例子可以参考下吗

**Comment by atian25** [comment]
egg-scripts 你就理解为就是一个 kill，然后 egg-cluster 会负责优雅退出。

LB 负责前面的流量切走，然后执行 stop / start 再检测启动成功后切流量回来
