### ISSUE TITLE
pm2 开启多进程 导致数据重复插入，请问怎么处理？谢谢！

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#2168]
pm2 开启多进程 导致数据重复插入，请问怎么处理？谢谢！
module.exports = {
    schedule: {
        cron: '0 0 2 * * *',
        type: 'worker',
    },
    async task(ctx) {
        const res = await ctx.curl('http://**********', {
            dataType: 'json',
        });
        ctx.app.cache = res.data;
    },
};

**Comment by atian25** [comment]
怎么个重复法

**Comment by xinnian1992** [comment]
就是偶尔会重复,开启了多进程pm2,进行数据同步导入数据库，有些数据重复导入，而且我是做了重复性检测的，不知是什么原因

**Comment by xinnian1992** [comment]
@atian25

**Comment by atian25** [comment]
为什么要用 PM2 呢？ egg 本身是不需要 PM2 的。

从现有信息里面是无法判断出来的，schedule 也只是一个。

除非你是 PM2 导致运行了多个 egg， PS 下看有几个 master 吧。
