### ISSUE TITLE
app.passport.serializeUser(async (ctx, user) => {})怎么使用的 ？

### ISSUE THREAD

**Issue by zsbox** [eggjs/egg#2170]
app.passport.serializeUser(async (ctx, user) => {})怎么用 官方并没有说的很清楚
我看到别人用的都是passport.serializeUser((user, done) => done(null, user.username)) 
我自己用都时候并不知道里面该怎么写
希望有人能能指导一些 感觉教程太少了

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/38

**Comment by zsbox** [comment]
@atian25 里面应该怎么写呢 我在里面打印东西不执行啊

**Comment by atian25** [comment]
```js
  // 自行处理经过 verify 后的 verifiedUser 数据如何序列化到 session
  // 在 http 请求结束阶段，保存数据到 session 之前调用
  app.passport.serializeUser(function* (ctx, verifiedUser) {
    // you can store profile and handle token here
  });
```

`app.passport.serializeUser` 最终是在渲染给用户时， 序列化 user 写入 session

**Comment by zsbox** [comment]
@atian25 就这么执行一下就ok了么 this.app.passport.serializeUser();里面不用做任何处理么

**Comment by atian25** [comment]
`serializeUser` 的用途是序列化用户信息到 session，举个例子，服务端返回的 User 对象里面，包含了 password 等敏感信息或没用的信息，你整个塞到客户端的 session 肯定不好啦，所以这里只是精简序列化，然后通过 `deserializeUser` 来还原

**Comment by zsbox** [comment]
哥 我理解你的意思 之前没怎么接触过后台 我就是想知道这个方法怎么用 
比如我是这样么      
this.app.passport.serializeUser(async (ctx, user) => {
      this.ctx.login({ email: user.email });
});
还是怎么其他写法
多谢了 @atian25

**Comment by atian25** [comment]
没看懂你的 `this.ctx.login({ email: user.email });` 是干嘛用的

这个函数唯一的作用就是精简 User 对象

```js
app.passport.serializeUser(async function (ctx, user) {
    return { 
       userName: user.name,
       userId: user.id,
    };
});
```

**Comment by zsbox** [comment]
虽然我还是不知道怎么用 但是还是谢谢你 @atian25

**Comment by zsbox** [comment]
this.app.passport.serializeUser(async (ctx, user) => {
        return {
          userName: user.email,
          userId: user.id,
        };
          console.log('kkakkaka');
      });
      this.app.passport.deserializeUser(async (ctx, user) => {
        console.log(ctx.session.passport.user);
      });
因为我放进去的console都不打印的 所以确实很难理解其用法

**Comment by OnedayLiu** [comment]
你可以检查一下是否已经鉴权成功，成功才会进入 `serializeUser`，

**Comment by zsbox** [comment]
@OnedayLiu 没懂 这个serializeUser不是用来把用户信息序列化存在session中的么 在这之前不是还不能鉴权么 我怎么用呢 目前我是放在登陆后用的
`const user = await this.app.mysql.get('users', { email: _email });
    const dbpw = user.password;
    const fmpw = crypto.MD5(_password).toString();
    if (user && dbpw === fmpw) {
      console.log('登陆成功');
      // this.ctx.login({ email: user.email });
      this.app.passport.serializeUser(async (ctx, user) => {
        return {
          userName: user.email,
          userId: user.id,
        };
      });
      // this.app.passport.deserializeUser(async (ctx, user) => {
      //   console.log(ctx.session.passport.user);
      // });
      // console.log(this.ctx.session.passport.user);
      // console.log(this.ctx.session);
      // this.ctx.session.maxAge = 10000; //设置session过期时间
      this.ctx.redirect('/user');
    } else {
      console.log('登陆失败');
    }`

**Comment by zsbox** [comment]
const user = await this.app.mysql.get('users', { email: _email });
    const dbpw = user.password;
    const fmpw = crypto.MD5(_password).toString();
    if (user && dbpw === fmpw) {
      console.log('登陆成功');
      // this.ctx.login({ email: user.email });
      this.app.passport.serializeUser(async (ctx, user) => {
        return {
          userName: user.email,
          userId: user.id,
        };
      });
      // this.app.passport.deserializeUser(async (ctx, user) => {
      //   console.log(ctx.session.passport.user);
      // });
      // console.log(this.ctx.session.passport.user);
      // console.log(this.ctx.session);
      // this.ctx.session.maxAge = 10000; //设置session过期时间
      this.ctx.redirect('/user');
    } else {
      console.log('登陆失败');
    }
@OnedayLiu 没懂  serializeUser不是把用户信息储存在session时候用的么 这个操作之前还要鉴权么 通过什么鉴权呢

**Comment by OnedayLiu** [comment]
这个插件的用途不是这样的，建议你先看看教程
