### ISSUE TITLE
是否可以在Controller外结束请求？

### ISSUE THREAD

**Issue by soluteli** [eggjs/egg#2171]
## 需求
开发一个可扩展模块的 `myLib`, 可以加载指定目录下文件提供的扩展方法

## 我的做法
1. `beforeStart` 时，通过 `app.myLib = myLib`，将 `myLib` 的实例绑定到 `app`
2. controller.js   
   controller/myLib.js
    ```js
    async test() {
      // 挂载当前 ctx 到 myLib
      this.app.myLib.ctx = this.ctx
      // 触发 myLib 扩展事件
      this.app.myLib.receive(xxx)
    }
   ```
3. router.js    

    `router.get('/robot/test', controller.myLib.test);`

4. 扩展文件
    ```js
    module.exports = myLib => {
      myLib.hear(/help/, res => {
        myLib.ctx.body = "robot test";
      })
    }
    ```

## 问题
- 上文第4步：返回404 页面
- **扩展文件**断点调试 `myLib.ctx.body` 的截图
![image](https://user-images.githubusercontent.com/17362082/37028674-e1d15158-216f-11e8-9a5f-dd5877e8c833.png)

## 我的疑问
**困境**
`mylib` 使用的是 [hubot](https://github.com/hubotio/hubot)，需要在扩展文件中返回对应的请求数据。但是改造 `hubot` 的触发函数为 Promise 的代价比较大😓。
**疑问**   
1.我的在非 `Controller` 文件中 设置 `body` 返回数据的设想是否可行 ？
2. 如果不行，有没有其它的建议方案？

Thanks！

**Comment by atian25** [comment]
没看懂为啥要自己再实现一套路由 `myLib.hear`

**Comment by soluteli** [comment]
`myLib` 类似于一个 插件平台，按照一定规范 `loadScripts` 后，就可以 扩展一定的能力。   
这样目的是，分离 **插件平台** 和 **扩展能力** 的代码。后续不需要自己开发**扩展能力**，只要提供**规范**就可以。

**Comment by atian25** [comment]
这不就是 egg 的 loader 做的事么?

**Comment by soluteli** [comment]
嗯，的确很类似。   
我的项目是旧项目的二次开发，**扩展能力**的代码已经通用化了（所以全部重够不现实啊😅），所以只能复用原有的规范了。   
所以，回到原来的问题：       
`在非 Controller 文件中 设置 body 返回数据有哪些方式 ？`    
或者也可以给一些二次开发的建议啊🤝

**Comment by atian25** [comment]
- 可以用 jscodeshift 写旧代码迁移脚本
- Koa 是一个 HTTP 请求模型，只有在 middleware 中才能处理用户请求( Controller 只是一个特殊的 Middleware 而已）
- 所以在 `非 Controller` 必然不可能处理用户请求，因为用户根本没请求，你怎么回复？

**Comment by atian25** [comment]
那你这个 myLib 不就是一个类似 Service 的角色么？

> 触发后的逻辑方法不能改写为 Promise 形式

没看懂，你统一在上面封装一层 Promise 不就行了

**Comment by soluteli** [comment]
myLib（[hubot](https://github.com/hubotio/hubot)）可以类似于一个 EventEmitter

**beforeStart 阶段** 
```js
myLib.on('eventname',cb(ctx) {
   // 设置 body 返回
    ctx.body = "hello myLib"
})
```

**请求阶段**

```js
/* Controller */
async test() {
  myLib.emit('eventname', this.ctx)
}

```

这样的 `on-emit` 封装成 Promise，我真心没有思路啊。

**Comment by atian25** [comment]
找个 event to promise 的库看看吧

https://www.npmjs.com/package/promise-events

**Comment by popomore** [comment]
不推荐使用事件，会被 @fengmk2 骂

**Comment by popomore** [comment]
```
// app.js
myLib.register('helper', async ctx => {
   ctx.body = "robot test";
});

// controller
async test() {
  await myLib.invoke('helper');
}
```
