### ISSUE TITLE
修改默认端口号的问题

### ISSUE THREAD

**Issue by 270034480** [eggjs/egg#2175]
我搜索了我的整个工程，只有run/application_config.json里有7001端口的配置，但是修改成7331后，通过npm run dev启动服务，会自动将文件里的7331又改成了7001。请问是我找错位置了吗？正确的修改方式是什么？

**Comment by atian25** [comment]
看下文档吧，都有写的。

`run` 目录是运行期的 dump 文件，用于问题排查，非配置文件

修改 npm scripts 的 dev 为 egg-bin dev --port=7331

**Comment by BoizZ** [comment]
@atian25 config.cluster.port 无效的

**Comment by atian25** [comment]
提供最小可复现方式

**Comment by Ariskywi** [comment]
@BoizZ 
config.cluster = {
        listen: {
            port: 12345,
        }
    }

**Comment by xiongsongsong** [comment]
midwayjs中
```
"dev": "cross-env NODE_ENV=local midway-bin dev --port=3020 --ts",
```

**Comment by wayward-man** [comment]
config.cluster = {
    listen: {
      port: 8000
    }
  };   不行啊，一直都是7002
