### ISSUE TITLE
egg 是否兼容 pandora.js项目

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2176]
pandora 是类似 pm2 方式的启动

而 eggjs 使用 master 进行启动

所以想问下 eggjs 是否可以使用 pandora 进行监控

**Comment by atian25** [comment]
egg 的 master 已经有完备的进程管理了，所以无需 PM2 之类的工具。

如果你想用，就当普通的用法即可，FAQ 有写。只是我们还没发现有什么特殊的场景。

**Comment by JacksonTian** [comment]
egg 的进程管理是非常完备的。

**Comment by gxcsoccer** [comment]
这个问题其实有点奇怪：pandora.js 定位如果是 pm2，egg 为什么需要去兼容它？
