### ISSUE TITLE
[security] opener

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#2179]
https://juejin.im/post/5a9f8425f265da239a5f57f8?utm_source=gold_browser_extension

**Comment by atian25** [comment]
https://mathiasbynens.github.io/rel-noopener/

**Comment by paranoidjk** [comment]
lint 工具也可以做静态检测  https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
