### ISSUE TITLE
boilerplate 优化

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#218]
目前的 simple 太多内容了:

- [x] 精简  [simple](https://github.com/eggjs/egg-boilerplate-simple), 去掉 hacker news 相关内容, 精简到类似现在 [empty](https://github.com/eggjs/egg-boilerplate-empty) : https://github.com/eggjs/egg-boilerplate-simple/pull/18
- [x] empty 真正变为 empty, 只保留 eslint, npm scripts 等: https://github.com/eggjs/egg-boilerplate-simple/pull/18
- [x] simple 原来的 hacker news 由 example 承载, 或者改为 `egg-boilerplate-showcase` ? https://github.com/eggjs/examples/tree/master/hackernews

@fengmk2 @popomore 觉得呢?

**Comment by fengmk2** [comment]
可以的，交给你。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-boilerplate-empty/pull/5
