### ISSUE TITLE
[提議] webpack打包佈署

### ISSUE THREAD

**Issue by red010182** [eggjs/egg#2183]
不知能否引入適當的`webpack.config.js`讓整個project用webpack一鍵打包，並適當繞過native module，實現輕鬆佈署。

例如
```
npm run build //打包出dist/build.js跟dist/package.json
```

將`dist/*`上傳至server後
```
npm i; npm start
```
啟動服務器

靈感來自於[這篇文章](https://jlongster.com/Backend-Apps-with-Webpack--Part-I)，用webpack打包後台程式，以便佈署&隱藏代碼。

甚至或許可以將打包後的build.js用nexe轉為binary檔，完美封裝程式碼！

之後有空我再來寫個範例

**Comment by popomore** [comment]
服务端代码不要用 webpack 打包

**Comment by popomore** [comment]
二进程文件可以使用 https://github.com/pmq20/enclose-io

**Comment by popomore** [comment]
> 甚至或許可以將打包後的build.js用nexe轉為binary檔，完美封裝程式碼！

这个可以尝试下，如果可行可以添加到我们文档中，感谢

**Comment by atian25** [comment]
@popomore 不是用 http://enclose.io/ 么

**Comment by popomore** [comment]
不局限，都可以吧，有例子就可以加个链接。

**Comment by atian25** [comment]
喔，https://github.com/pmq20/node-packer/blob/master/README.md#compile-a-web-application
