### ISSUE TITLE
如果想在生产环境调试代码，该如何操作?

### ISSUE THREAD

**Issue by Tencent-Luis** [eggjs/egg#2184]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
不建议在生产环境调试代码，你的场景是?

**Comment by Tencent-Luis** [comment]
如果想在生产环境中，将请求的参数输出到${appInfo.name}-web.log中，该如何操作？

**Comment by atian25** [comment]
access log？ 自己写个中间件咯。

**Comment by Tencent-Luis** [comment]
假如我的egg项目名称是A，在线上部署后，他的默认日志会保存在/home/Owen/logs/A/目录下，该路径下日志文件有：common-error.log, egg-agent.log, egg-web.log, A-web.log，能否将请求传递的参数或访问接口返回的结果数据，打印在以上日志文件中？如果能，该如何操作？

**Comment by wsgfz** [comment]
写个中间件, 然后
```javascript
module.exports = () => {
  return async function printReqRes(ctx, next) {
    await next();

    ctx.logger.info('请求:%s | 回包:%s', JSON.stringify(ctx.request.body), JSON.stringify(ctx.body));
  };
};
```

**Comment by Tencent-Luis** [comment]
![image](https://user-images.githubusercontent.com/10045004/37143724-f363cdd2-22f6-11e8-8e01-f4770e4b6d39.png)
文章中介绍的这种方式，不能在线上使用?

**Comment by atian25** [comment]
@Tencent-Luis 可以啊。

你现在的问题到底是啥...

**Comment by Tencent-Luis** [comment]
`let post = this.ctx.request.body;
this.ctx.logger.debug(post);
`
发送请求时，在日志文件中，无任何信息输出。

**Comment by wsgfz** [comment]
日志级别！默认是INFO

**Comment by Tencent-Luis** [comment]
`let post = this.ctx.request.body; this.ctx.logger.info(post);`
调用方法写成info()，也是没有任何输出。是哪里有开关在控制吗？

**Comment by atian25** [comment]
看下 logger 的文档.
