### ISSUE TITLE
整理所有的环境变量

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#2185]
可以使用 .env 来配置提交到代码中

https://github.com/motdotla/dotenv

**Comment by atian25** [comment]
> Should I commit my .env file?
> No. We strongly recommend against committing your .env file to version control. It should only include environment-specific values such as database passwords or API keys. Your production database should have a different password than your development database.

**Comment by atian25** [comment]
不太明白 .env 文件的使用场景?

- 本地开发不会，我们有 config.local.js
- 服务端或 ci 的话，按理说也不会给你机会去编辑 .env 文件的，而是类似 travis env 那样的

**Comment by pacoyang** [comment]
@atian25 将一些环境变量写在 .env 文件中，可以避免一些涉密信息暴露在版本库。比如数据库用户名密码，如果写在 config 文件那不跟着提交到版本库了？eggjs 默认 .gitignore 也没有 exclude config 文件，eggjs 是如何考虑这类问题的？

**Comment by atian25** [comment]
- 那只是一个骨架，根据你们自己的需求去配置 `.gitignore`。
- 涉密信息你可以自己放一个文件，然后 require 即可。

这些都没有通用的处理方式，egg 是不会帮你手把手做完的。

**Comment by pacoyang** [comment]
@atian25 了解👌
