### ISSUE TITLE
官方源码vscode debugg便宜报错误

### ISSUE THREAD

**Issue by tear3333** [eggjs/egg#2189]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

PS D:\nodejs\egg-master> cd 'D:\nodejs\egg-master'; & 'D:\Program Files\nodejs\npm.cmd' 'run' 'debug' '--' '--inspect-brk'

> egg@2.4.1 debug D:\nodejs\egg-master
> egg-bin debug "--inspect-brk"

⚠️  Error: egg is not found in D:\nodejs\egg-master\node_modules
⚠️  Command Error, enable `DEBUG=common-bin` for detail
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg@2.4.1 debug: `egg-bin debug "--inspect-brk"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg@2.4.1 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

egg-bin也安装了，还是报错误

**Comment by popomore** [comment]
不是写了 egg 没找到吗，重新用脚手架初始化一个

**Comment by tear3333** [comment]
可以附加下代码吗，我npm install 好几遍了

**Comment by atian25** [comment]
`egg-init --type=simple showcase`
