### ISSUE TITLE
自动创建仓库流程

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#2193]
现在创建仓库有点烦，怕漏了什么，可以通过工具实现。

1. 通过一种方式发起创建仓库申请
1. 通过命令自动创建
    1. 创建仓库
    1. 关闭 issue
    1. 只保留 merge squash
    1. 添加 travis
    1. 添加 appveyor

**Comment by atian25** [comment]
印象中有一个服务可以做的，似乎是上次那个 bot

**Comment by popomore** [comment]
@afc163 你们有这种需求吗

**Comment by afc163** [comment]
目前没有。

**Comment by atian25** [comment]
这个 #3398 那边也可以考虑下。
