### ISSUE TITLE
egg-static 这个插件有bug

### ISSUE THREAD

**Issue by magicknight** [eggjs/egg#2194]
* **Node Version**: 9.8
* **Egg Version**: 2.4.1
* **Plugin Name**: egg-static
* **Plugin Version**: latest
* **Platform**:
* **Mini Showcase Repository**:

虽然不知道在哪，但我需要返回 partial content 的时候，这个插件似乎把返回的header改了
禁用这个插件以后就正常了。

**Comment by popomore** [comment]
https://github.com/eggjs/egg-static/pull/14
