### ISSUE TITLE
官网例子是不是有误，还是我看错了？请大神帮忙看一下

### ISSUE THREAD

**Issue by 270034480** [eggjs/egg#2196]
![image](https://user-images.githubusercontent.com/36993759/37241447-30dc1310-2494-11e8-9ef5-b89574eeee9e.png)

**Comment by atian25** [comment]
笔误，欢迎 PR，同时修改下对应的英文版

**Comment by 270034480** [comment]
我是新手，github不熟，eggjs是第一个在github关注的项目；PR怎么弄？

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/contributing.html#%E6%8F%90%E4%BA%A4-pull-request

**Comment by atian25** [comment]
fixed in https://github.com/eggjs/egg/pull/2198
