### ISSUE TITLE
官网无法访问

### ISSUE THREAD

**Issue by zsbox** [eggjs/egg#2199]
如题，官网无法访问了

**Comment by atian25** [comment]
我这边可以，你自己网络问题吧?

**Comment by zsbox** [comment]
不知道啊 我其他网站都能打开都

**Comment by zsbox** [comment]
用chrome无法访问 safari可以

**Comment by zsbox** [comment]
chrome访问其他网站均正常 未开代理

**Comment by zsbox** [comment]
![image](https://user-images.githubusercontent.com/20392882/37262061-b6757532-25db-11e8-9f46-366ad7710326.png)
@atian25

**Comment by okoala** [comment]
@zsbox  是 https://eggjs.org/

**Comment by okoala** [comment]
你这 com 的域名是从哪里找来的~

**Comment by zsbox** [comment]
抱歉这个是我输入错了  
![image](https://user-images.githubusercontent.com/20392882/37262301-4fc41058-25dd-11e8-8fe5-1ab0d04b80a8.png)
应该是这个 可能是我这里设置有问题

**Comment by liuyutao** [comment]
我也无法访问

**Comment by liuyutao** [comment]
http://eggjs.org可以， https://eggjs.org不可以。

**Comment by atzcl** [comment]
我这 http/https 都可以打开啊

**Comment by whxaxes** [comment]
域名输错了而已，我关掉了

**Comment by zsbox** [comment]
https确实不能访问都

**Comment by okoala** [comment]
@zsbox  访问不了的都是被墙了，现在苏总正在搞个国内镜像站，需要等待下~

**Comment by richartan** [comment]
这两天都20次中只有一次能访问正常https://eggjs.org

**Comment by okoala** [comment]
@zsbox  @richartan 镜像站点 http://mirror.eggjs.org/

**Comment by reducm** [comment]
mirror搜索功能也是调回到原站的, 之前全翻墙还是能访问的，现在换了几个地方都访问不了...

**Comment by atian25** [comment]
https://eggjs.app/
