### ISSUE TITLE
关于https协议

### ISSUE THREAD

**Issue by 15652768278** [eggjs/egg#2200]
请教个问题，由于是小程序项目，需要服务器使用域名+https协议
想问下如何使用https及设定key和cert路径
在官网文档里没有搜索到，求各位大神给个指点(egg版本:2.4.1)

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster#options

`egg-scripts start --https.key= --https.cert=`

**Comment by 15652768278** [comment]
哦哦，是在egg-scripts里啊，是我文档看的不仔细，谢谢大神指点

**Comment by PebblerWon** [comment]
@15652768278  请教一下 `https` 协议具体需要怎么操作啊
