### ISSUE TITLE
egg+react开发

### ISSUE THREAD

**Issue by gitrl** [eggjs/egg#2201]
基于egg.js用react发开h5页面，有大佬知道怎么弄的吗 ？弄了一周多了，环境还没打起，求助大神帮帮忙。。。

**Comment by hubcarl** [comment]
@gitrl  可以用这个 https://github.com/hubcarl/egg-react-webpack-boilerplate

**Comment by gitrl** [comment]
@hubcarl @hubcarl  我也看了这个，也用了一下，但是我都是没个组件都在服务端渲染的，我需要我的页面只有首页渲染在服务端，其他子页面用react的路由实现跳转可以吗？如果可以主要不知道怎么在egg里面配置react 的路由。能给我讲解一下吗，谢谢

**Comment by gitrl** [comment]
hubcarl  我也看了这个，也用了一下，但是我都是没个组件都在服务端渲染的，我需要我的页面只有首页渲染在服务端，其他子页面用react的路由实现跳转可以吗？如果可以主要不知道怎么在egg里面配置react 的路由。能给我讲解一下吗，谢谢

**Comment by hubcarl** [comment]
https://github.com/hubcarl/egg-react-webpack-boilerplate/blob/master/app/controller/spa/spa.js

**Comment by gitrl** [comment]
@hubcarl 你的意思都用renderClient渲染就可以了吗？不用单独在配置一个react路由文件是吧？？？

**Comment by gitrl** [comment]
@hubcarl ...render和renderClient一个服务端渲染一个前端渲染，不太知道他们有什么区别。。

**Comment by hubcarl** [comment]
@gitrl     渲染模式：http://hubcarl.github.io/easywebpack/react/egg-render/  自己运行一下，浏览器右键源代码看看就应该明白了

**Comment by hubcarl** [comment]
- render 表示当前访问页面全部由 Node 端渲染程完成的html，然后输出到页面
- renderClient 表示 node 端只 渲染一个 html，header，body 的一个简单 html 骨架， 具体内容有 react 在浏览器进行渲染

**Comment by gitrl** [comment]
那我是不是就出来首页都用renderClient 渲染就好了？？？不需要像做react那样做一个index.js路由组件是不？

**Comment by gitrl** [comment]
那我是不是就出来首页都用renderClient 渲染就好了？？？不需要像做react那样做一个index.js路由组件是不？

**Comment by hubcarl** [comment]
@gitrl  你自己决定了，如果你页面首次要进行服务端渲染，就用 render， 如果不需要用服务端渲染人可以用 renderClient

**Comment by gitrl** [comment]
@嗯嗯，好的，谢谢耐心解答哦，很少人会egg。。。加个微信好友吧。。希望还可以请教你问题rl14101010628

**Comment by hubcarl** [comment]
@gitrl  骨架项目 README 里面有 QQ 群你可以加一下

**Comment by gitrl** [comment]
哦哦。。。没有找到群呢。。

**Comment by gitrl** [comment]
@hubcarl .。。。。。5.1.3 多页面走前端渲染(后端路由)实现, 通过 egg-view-react-ssr 插件 renderClient 方法实现
他还是后端路由呢？

**Comment by gitrl** [comment]
@hubcarl 。。EASY_ENV_IS_DEV这个是怎么配置的呢？

**Comment by gitrl** [comment]
@hubcarl 
您好，能帮我看看qq邮箱发你的文件吗？
页面中用a标签可以正常显示，到那时不能实现跳转，
用link 页面显示不出来，
我想用route实现路由跳转，这样不对吗？

**Comment by hubcarl** [comment]
@gitrl  EASY_ENV_IS_DEV  http://hubcarl.github.io/easywebpack/webpack/env/  骨架项目里面也有使用

**Comment by hubcarl** [comment]
![image](https://user-images.githubusercontent.com/4983042/37276647-48c1b6c6-261d-11e8-942f-46867fd49831.png)

**Comment by popomore** [comment]
后面可以用 egg-view-assets 插件
