### ISSUE TITLE
[ 建议 ] 源码目录命名

### ISSUE THREAD

**Issue by atzcl** [eggjs/egg#2202]
` app ` 下的项目目录是否应该采取复数的形式呢：` controllers `、` services ` 等等会更加直观呢？
以及 ` egg-router-plus ` 插件默认导入的路由目录名 ：
```
directory: path.join(app.baseDir, 'app/router')
```
为 ` routes `

**Comment by atian25** [comment]
很早前我们就讨论过了，目录都用单数。
