### ISSUE TITLE
egg-mysql查询出来的数据格式错误

### ISSUE THREAD

**Issue by jakehu** [eggjs/egg#2203]
数据库格式：2018-03-12 14:46:31
通过egg-mysql查询出来的格式：2018-03-12T06:46:31.000Z
自动加上了时区而且还是错误的时区。
数据库字段类型为timestamp

**Comment by jakehu** [comment]
但是时区不对的嘛 我们是东八区 这个明显不是东八区啊 时差8个小时的嘛

**Comment by jakehu** [comment]
@sanshao

**Comment by popomore** [comment]
这是 iso 时间，始终是 utc，你用 Date 包一下就好了

**Comment by yecao007** [comment]
添加一个  dateStrings: true 就解决了

**Comment by fanky-c** [comment]
> 添加一个 dateStrings: true 就解决了

在哪里添加？
