### ISSUE TITLE
egg-passport  代码有错误 根本不能运行, eggjs文档中passport内容也是错的

### ISSUE THREAD

**Issue by wansheg** [eggjs/egg#2204]
egg-passport/lib/passport.js 
 
55   mount(strategy, options = {}) {
 56     options.loginURL = options.loginURL || `/passport/${strategy}`;
 57     options.callbackURL = options.callbackURL || `/passport/${strategy}/callback`;
 58     const auth = this.authenticate(strategy, options);
 **59     this.app.get(options.loginURL, auth);**
 **60     this.app.get(options.callbackURL, auth);**
 61   }
 62 
eggjs 只支持
app.get(  path, middleware, action ) 
明显少了一个action参数
mount函数从根本上说就是错的 ! 多余的

eggjs 文档 passport部分 也是错的

**Comment by fengmk2** [comment]
请按格式反馈问题

**Comment by atian25** [comment]
谁说 egg 只支持 `app.get(path, middleware, action)` ...

mount 有没有错，看下 egg-passport 的单元测试不就知道了...

**Comment by wansheg** [comment]
对不起 是我自己分析错了 
不过 我还想反抗下  
eggjs 用插件封装 koa/express的 中间件实在是太折腾了 !!!!!

**Comment by atian25** [comment]
1. eggjs 使用 koa 中间件就几行代码，在 Middleware 文档有写
2. 而 express 和 koa 的 编程模型 本来就是完全不一样的，你就不应该用 express 中间件，koa 生态基本都有了。

**Comment by wansheg** [comment]
谢谢 耐心回答 , 让我好受了些 :）

我没有想用express的中间件  egg-passport 用的,我也没有办法, （egg-passport代码现在巨复杂　）
关于passport, 目前 express 比koa支持的site 个数要多些，　
我会尽量不用　express中间件了　
谢谢
