### ISSUE TITLE
如何使用express中间件 

### ISSUE THREAD

**Issue by wansheg** [eggjs/egg#2205]
express中间件 函数参数为
express_mid_func(   req, res, next ) { 
... 
}

passport 是一个 express中间件, 我发现egg-passport 封装了passport 然后export出来的接口 app.passport.authenticate() {
 return function( req, res, next ) { 
}
}

所以eggjs是支持 express 的中间件的对吗 ?

**Comment by thonatos** [comment]
> Passport is authentication middleware for Node.js.

- [egg-passport](https://github.com/eggjs/egg-passport)
- [Passport 教程](https://eggjs.org/zh-cn/tutorials/passport.html)

**Comment by atian25** [comment]
- `egg-passport` 暴露出的并不是原始的 `app.passport.authenticate`，请仔细看下文档
- `express` 和 `koa` 是完全不同的编程模型，koa 无法简单的使用 express 的中间件
-  koa 的中间件生态也已经非常完善的，koa/egg 没必要用 express 的中间件
