### ISSUE TITLE
用typescript 重构　ｅｇｇｊｓ？

### ISSUE THREAD

**Issue by wansheg** [eggjs/egg#2206]
没有类型系统的　ｅｇｇｊｓ　根本不能谈的上是企业级开发　，　不知道作者是否考虑使用ｔｙｐｅｓｃｒｉｐｔ重写ｅｇｇｊｓ　？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/37315583-5c94fbcc-2695-11e8-965e-212553cab6c7.png)

- 企业级开发的要素很多，类型系统只是其中的一小点。
- TypeScript 并不能代表 JS，我们跟随的是 ES 规范。
- 有人可以用 JS 写出很强壮维护性很好的代码，也有人能用 TS 写出无法维护的代码。
- Egg 源码本身用不用 TS 编写，并不重要，我们有提供对应的 `d.ts` 和完备的单元测试。
- 开发者可以用 TS 来写应用，这个从来没有过任何限制：
 - 官方的 TS Guide 还在编写中，可以看看社区的实践：
 - https://github.com/whxaxes/blog/issues/11
 - https://cnodejs.org/topic/5a949c9c653c43b914685044
