### ISSUE TITLE
app.HTTPMETHOD  和 router.HTTPMETHOD 为什么在API 文档中没有说明？

### ISSUE THREAD

**Issue by wansheg** [eggjs/egg#2209]
不是太理解　router.js 中的写法，　为什么既可以写成　
app.get/post/put 的方式　
也可以写成
router.get/post/put 的方式
?
这些app  router 的方法是在哪里定义的？
为什么 在API 文档中不能找到 关于 application.get/post/put  router.get/post/put 的说明　？

**Comment by atian25** [comment]
`app.VERB` 是别名，现在已经不推荐，推荐直接使用 `app.router.VERB`

文档应该都已经改了，你在哪里还看到有 app.VERB ?

**Comment by wansheg** [comment]
谢谢, 我是在一个 第三方的应用中看到的 
router.VERB  这些东西 有具体的API 文档吗 ?
我只在教程里面找到了这些：
我希望找到 API 文档　的目的是为了搞清楚　action 和 middleware 的函数签名
router.verb('path-match', app.controller.action);
router.verb('router-name', 'path-match', app.controller.action);
router.verb('path-match', middleware1, ..., middlewareN, app.controller.action);
router.verb('router-name', 'path-match', middleware1, ..., middlewareN, app.controller.action);


之前您说　( https://github.com/eggjs/egg/issues/2204 )
的　router.ver( 'path-match',  middleware )也支持　，　我并没又看到　
我的分析　egg-passport源代码的理解是　　passport.authenticate( 'local' , options ) 返回的是一个　function( req, res, next ) { ... } 的函数，　难道　我代码分析的结果是错的　？
function( req, res, next ) { .... } 　是express 中间件接口，　所以　这到底是怎么回事？
