### ISSUE TITLE
egg-mock 缓存 server 引入的问题 

### ISSUE THREAD

**Issue by friskfly** [eggjs/egg#2210]
https://github.com/eggjs/egg-mock/commit/f1820d70f2e266d4b18fb7062976b4c14952a16f
这里对 server 做了缓存，在2个测试用例复用同一个app时会存在问题。 第一个用例中通过mm改变app状态会导致影响第二个用例，比如修改 app.middleware

**Comment by atian25** [comment]
`mm.app({ cache: false })`

**Comment by friskfly** [comment]
关掉cache可以绕过这个问题， 但是加这个server 缓存会导致 app 无法复用。

**Comment by popomore** [comment]
mm 没有 restore？

**Comment by fengmk2** [comment]
需要在第一个测试跑完之后，恢复环境，执行 app.mock.restore()

**Comment by sansroman** [comment]
sequelize-example的测试用例里after应该用afterEach吧，不然第二个测试用例将依然使用第一次的返回结果
