### ISSUE TITLE
https://eggjs.org 访问不了了？是挂了么？2018年03月13日

### ISSUE THREAD

**Issue by pancaiqiang** [eggjs/egg#2211]

**Comment by pancaiqiang** [comment]
我是北京联通用户，今天访问egg官网一直显示： 无法访问此网站，eggjs.org 的响应时间过长。我关掉vpn也访问不了

**Comment by pancaiqiang** [comment]
![image](https://user-images.githubusercontent.com/17923397/37340297-a2858292-26f8-11e8-859f-a9779d6f6a98.png)

**Comment by atian25** [comment]
最近有某些大会，你们懂得。

**Comment by okoala** [comment]
https://gist.github.com/okoala/71030ebb2b82a86321406073e2f22e19
@pancaiqiang  暂时你可以使用这个油猴脚本访问文档~

**Comment by atian25** [comment]
@okoala @popomore  hexo 构建的时候直接把地址配置为 github.io 的?

**Comment by popomore** [comment]
要改哪个配置

**Comment by atian25** [comment]
我是问 hexo 有没有一个参数，或者插件，可以配置静态资源的地址，如配置 cdn 地址啥的

**Comment by popomore** [comment]
想配应该可以吧，不过还要发一下 cdn

**Comment by atian25** [comment]
看 @okoala 那个脚本，直接改为 github.io 的资源也行

**Comment by popomore** [comment]
那 github.io 也墙了呢，那个应该慢吧

**Comment by liupeng110112** [comment]
访问量是不是急剧下降

**Comment by atian25** [comment]
并没有，PV 还是 1W 那样
