### ISSUE TITLE
middleware 文件名字有要求不能包含下划线　？　如果是　请在文档里面说明！！！！

### ISSUE THREAD

**Issue by wansheg** [eggjs/egg#2212]
被坑了　，　中间件名字包含下划线的话　在加载中间件的时候会出错！！！！

**Comment by atian25** [comment]
`app/middleware/test_abc.js` -> 'app.middleware.testAbc'

![image](https://user-images.githubusercontent.com/227713/37381313-6b15185c-2777-11e8-9d38-36e58c0bdd2b.png)

**Comment by whxaxes** [comment]
文件名是可以用下划线，只是 loader 在加载 middleware 的时候，会把下划线转换成驼峰，比如中间件命名为：test_mid ，在配置的时候，就要配置成 testMid

**Comment by fengmk2** [comment]
文件加载器章节也有相关说明 https://eggjs.org/zh-cn/advanced/loader.html#%E6%96%87%E4%BB%B6%E5%8A%A0%E8%BD%BD%E8%A7%84%E5%88%99

**Comment by popomore** [comment]
文档也要加叹号！！！
