### ISSUE TITLE
egg-mongoose查询结果问题

### ISSUE THREAD

**Issue by menkeydyvh** [eggjs/egg#2213]
* **Node Version**:  v8.9.3
* **Egg Version**: 2.4.1
* **Plugin Name**:
  mongoose: {
    enable: true,
    package: 'egg-mongoose',
  }

* **Plugin Version**:"egg-mongoose": "^2.2.0",

* **config.default.js**
 config.mongoose = {
    url: 'mongodb://user:password@localhost:27017/xxx',
    options: {},
  };

* **app/model/Bot,js**
'use strict';
module.exports = app => {
    const mongoose = app.mongoose;
    const BotSchema = new mongoose.Schema({
        _id: {type: String},
        bot_name: {type: String},
    });
    return mongoose.model('bot', BotSchema, null, {cache: false});
};

* **controller**
'use strict';
const Controller = require('egg').Controller;
class HomeController extends Controller {
    \* index() {
        let ctx = this.ctx;
        const query = yield  this.app.model.Bot.find({});    
        return ctx.render('home/index.html')
    }
}
module.exports = HomeController;

**问题**
const query = yield  this.app.model.Bot.find({});    
的结果都是  query = Array(0)

当然这个数据库肯定是有数据的因为之前用这个库开发过项目了
但是一直都是获取不到  是否哪里有写错？

**Comment by thonatos** [comment]
```
'use strict';
module.exports = app => {
  const mongoose = app.mongoose;
  const BotSchema = new mongoose.Schema({
    _id: { type: String },
    bot_name: { type: String },
  });
  // return mongoose.model('bot', BotSchema, null, { cache: false });
  return mongoose.model('Bot', BotSchema, null, { cache: false });
};

'use strict';
const Controller = require('egg').Controller;
class HomeController extends Controller {
  * index() {
    let ctx = this.ctx;
    const query = yield ctx.model.Bot.find({});
    return ctx.render('home/index.html')
  }
}
module.exports = HomeController;
```

可参考 [egg-cnode]，如果依然有问题，欢迎提交最小可复现仓库。

**Comment by luckymore** [comment]
握了棵草，，，建 collection 的时候，需要给名字后面加个"s" ....  你想叫 user 就得写成  users，然后代码里是写 User
