### ISSUE TITLE
URL后缀 如何配置

### ISSUE THREAD

**Issue by mwang0** [eggjs/egg#2214]
* **Egg Version**:2.2.1
如题

**Comment by atian25** [comment]
请补充问题描述

**Comment by mwang0** [comment]
url优化在url后面加上.html后缀. egg路由中如何配置
如：http://www.xxx.com/about  => http://www.xxx.com/about.html

**Comment by atian25** [comment]
自己写路由不就行了

**Comment by fengmk2** [comment]
```js
app.router.get('/about.html', 'about');
```

还说希望所有路由都支持 .html 后缀？但是现在互联网其实不太流行后缀了。。。

**Comment by mwang0** [comment]
tks @atian25  @fengmk2  

运营同学在这方面提的需求。
当然，如果能所有路由都支持那最好， 一个配置简单省事。

**Comment by atian25** [comment]
@mwang0 你自己按自己的规则，封装个函数即可。
