### ISSUE TITLE
socket.io中this.ctx.session为undefined

### ISSUE THREAD

**Issue by zengwe** [eggjs/egg#2215]
首先project/app.js中重写了session的get和set方法，在http访问的controller是没有问题，能get和set
然后在、app/io/controller中this.ctx.session为undefined，我查看了cookie是传上来了，但是this.ctx.session并没有调用app.js中重写的get方法

**Comment by ngot** [comment]
请按照模板，把详细信息提供一下。最重要的是附上代码仓库。

**Comment by Maledong** [comment]
已经在 https://github.com/eggjs/egg-socket.io/commit/c2b4f43bf43f1cffeba66f590c5283d2b99466d0 修复。

具体使用：this.session……

参考unit test部分的使用代码：https://github.com/eggjs/egg-socket.io/tree/master/test/fixtures/apps/socket.io-session

**Comment by ngot** [comment]
由于提供的信息过少，无法确定这个issue和 #1416 是否有关联。#1416 的问题是在开启 external session 的情况下，获取session失败。先关了，等提供了客服先浮现的案例，再打开。
