### ISSUE TITLE
egg 是否会考虑 module开发

### ISSUE THREAD

**Issue by menkeydyvh** [eggjs/egg#2216]
如题！我们公司在选nodejs框架  希望有php yii2的module功能

**Comment by atian25** [comment]
指的是 feature-base 的目录结构？

这个 @popomore 后面在 TS 里面会考虑应用层的这种模式

**Comment by okoala** [comment]
@menkeydyvh  egg 的几大 loader 都是支持自定义配置的，非常灵活，你想要怎样都行~ 然后还可以封装成插件给社区使用。

**Comment by atian25** [comment]
你指的是 render 的 tpl 相对路径要加 Controller 所在目录?

这块其实是可以通过自定义的 renderModuleTpl 函数去处理的

**Comment by popomore** [comment]
可以自己阅读源码来支持，或自己设计子应用方案，egg 推行微服务。

**Comment by menkeydyvh** [comment]
@atian25 并没有看到 renderModuleTpl函数在哪里？

**Comment by atian25** [comment]
自己写啊

**Comment by atzcl** [comment]
[https://github.com/yongbo000/egg-subapp/blob/master/config/config.default.js](https://github.com/yongbo000/egg-subapp/blob/master/config/config.default.js)
正在参考这位大佬写的，实现 modules 多模块应用

**Comment by JackGit** [comment]
我最近也是在研究能够有这种实现，在不使用微服务使用老式的方案时的一种更整块的集成方案，就像 j2ee 中那样

**Comment by atzcl** [comment]
@JackGit 可以使用 midway
