### ISSUE TITLE
egg中间件能否做路由的拦截？

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#2217]
我希望写一个基于`egg-passport`的中间件，当客户端请求api的时候，这个中间件能够根据session判断是否登录，如果未登录返回json数据信息给客户端。

但是我测试了一下，中间件死活return不出数据给客户端，客户端一直处在请求等待的状态。
是我return的方式有问题吗。

```
module.exports = () => {
  return async function (ctx, next) {
    let { req, res, app } = ctx;
    await next();

    await app.passport.authenticate('local', async function (err, user, info) {
     // 这里省略了条件判断的代码，希望不管是否登录都返回这个json给客户端，但是客户端死活获取不到。
      ctx.body = {
        code: '1',
        msg: '用户未登录',
        result: {

        },
      };
    })(ctx, next);
  };
}
```

不知道是因为**嵌套在`egg-passport`的回调函数中的原因**还是**对egg中间件的返回内容的方法使用不当**导致的。百思不得其解，求解惑。。。

**Comment by atian25** [comment]
为什么这么用....

把文档重新看一遍吧

`ctx.isAuthenticated()`

- https://github.com/eggjs/egg-passport
- https://eggjs.org/zh-cn/tutorials/passport

**Comment by xjchenhao** [comment]
因为是前后端分离的项目，它们内置的options方法里可以设置登录or未登录时跳转到指定url，但是我不需要跳转到指定url啊（直接返回json不是更省事吗），然后看它支持自定义函数，我就基于这个自定义函数写了...

**Comment by atian25** [comment]
egg-passport 就是对 passportjs 的上层封装。
你按 egg-passport 的方式去处理就好了。

passportjs 是 express 风格的，无法直接在 Koa 里面用，如果你不用我们封装好的，那就要自己处理了。

大概的代码就是

```js
module.exports = () => {
  return async function (ctx, next) {
    if (ctx.isAuthenticated()) return await next();
    ctx.body = {};
  };
}
```

具体的你要看文档实践

**Comment by xjchenhao** [comment]
好的哦，谢谢回复～

**Comment by zwb910615** [comment]
@xjchenhao 你是怎么解决的 我也遇到同样的问题

**Comment by xjchenhao** [comment]
@zwb910615 看下这里面的mongo分支哦，我现在是这么解决的，感觉很完美。

https://github.com/xjchenhao/egg-admin-server

**Comment by kchjxxgh** [comment]
为什么egg-passport要强制跳转呢？为什么要禁掉authenticate作为middleware的路子呢？
`  authenticate(strategy, options = {}) {
    // try to use successReturnToOrRedirect first
    if (!options.hasOwnProperty('successRedirect') && !options.hasOwnProperty('successReturnToOrRedirect')) {
      // app use set `ctx.session.returnTo = ctx.path` before auth redirect
      options.successReturnToOrRedirect = '/';
    }
    if (!options.hasOwnProperty('failWithError')) {
      options.failWithError = true;
    }
    return super.authenticate(strategy, options);
  }`
