### ISSUE TITLE
请问egg中多项目如何共用同一service

### ISSUE THREAD

**Issue by DerekYeung** [eggjs/egg#2219]
* **Node Version**: 8.10.0
* **Egg Version**: 2.4.1
* **Plugin Name**: none
* **Plugin Version**: none
* **Platform**: Windows
* **Mini Showcase Repository**: none

我们的项目目前分为多个端（如总部后端，分城市后端，用户端，商家端等），之前的框架是参照yii2开发出来的，模式上也是参考yii2的目录结构，目前的结构大致上是这样的：

|---- common
|-------- libs
|----------- model
|--------------- xxModel.js
|---- backend
|--------- app
|--------- model
|---- frontend...
|---- .....

其中common中的model属于公用部分，每个端也有自己私有的model，私有的model互相不通，但是公用的部分是都可以访问到的。
举例比如UserModel类，每个端都要用到，那么我们就会把这个类放到common中，AdminModel只在管理端用到，那我们就把这个类单独放在了backend当中

对egg还不是特别了解，翻阅了一下文档暂时还没发现直接实现的方法，但是看到有Loader可以进行扩展，所以想请问一下，egg中是否也支持或者通过别的方式可以实现这样的效果，还是说需要通过Loader进行扩展？

劳烦各位帮我解答一下，非常感谢

**Comment by atian25** [comment]
目前 service 可以作为插件引入。
model 可以自己 loader 扩展下

**Comment by DerekYeung** [comment]
@atian25 谢谢，还有一件事想请教一下，是关于router的
我们之前的项目是通过urlpath来自动定位controller，比如/user/view/edit会自动定位到/controller/user/view.js(UserViewController)，然后执行edit方法
看了一下文档目前多层级controller是可以完美解决的，但是自动定位这个出现了点问题
我预想的代码是这样的

```
function customLoader(ctx, next){
      这里进行path的解析，然后定位controller
      这里不清楚最后得到的controller该如何运行？
}

router.get('*', xxxMiddleware, customLoader);
```
目前这样的结果retrun以及直接调用的方式都无法使用，感觉上这里也不应该使用apply

还要麻烦您解答一下，谢谢

**Comment by DerekYeung** [comment]
@atian25 另外还有一个就是egg是不是每一个项目一个node_modules，因为我们之前的项目也是公用一个node_modules，现在我如果把package移到外面到也可以实现共用，但是这样的话好像就不能使用egg的命令运行，只能通过pm2运行了，不知道这个是我操作的不对还是在设计上egg推荐一个项目一个package

**Comment by DerekYeung** [comment]
@atian25 关于自动定位的问题现在是这样解决的，有效，但不知道这样做对不对...

`
module.exports = app => {
  const { router, controller } = app;
  const loader = function(ctx){
  	controller.home.index.apply(ctx);
  }
  router.get('*', loader);
};
`

**Comment by atian25** [comment]
- 任何 Node 项目都不推荐共用 node_modules，硬盘不值钱...
- router 那个可以参考 https://github.com/eggjs/egg-router-plus 自己写下
- `apply` 那个比较 hack

**Comment by DerekYeung** [comment]
@atian25 好的，受教了 非常感谢
