### ISSUE TITLE
router前匹配支持query参数问题

### ISSUE THREAD

**Issue by lijialing888** [eggjs/egg#2222]
* **Node Version**: 8.9
* **Egg Version**: 2.41
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Windows
* **Mini Showcase Repository**:

我希望通过http://ip/node/func/xxx..匹配到同一个方法中，我发现加星号*是支持的
```js
app.get("/node/func/*", controller.xController.xFunction);
```

http://ip/node/func/abc.html
http://ip/node/func/def/123.html
都支持。

~~但是加上参数?xxx=xxx，就返回404，找不到了。~~

http://ip/node/func/abc.html?xxx=xxx
http://ip/node/func/def/123.html?xxx=xxx
~~都不支持~~
都支持

~~请问有什么解决办法吗？~~
代码写的有问题。

**Comment by atian25** [comment]
- https://eggjs.org/zh-cn/basics/router.html#%E5%8F%82%E6%95%B0%E5%91%BD%E5%90%8D%E6%96%B9%E5%BC%8F
- https://github.com/alexmingoia/koa-router
