### ISSUE TITLE
为什么 const { router, controller}=app;  router会有值呢

### ISSUE THREAD

**Issue by newBird01** [eggjs/egg#2228]
module.exports = app => {
    console.log(app)
/*
{ env: 'local',
  name: 'caoegg',
  baseDir: 'E:\\node\\egg2\\egg2',
  subdomainOffset: 2,
  config: '<egg config>',
  controller: '<egg controller>',
  serviceClasses: '<egg serviceClasses>',
  middlewares: '<egg middlewares>',
  httpclient: '<egg httpclient>',
  loggers: '<egg loggers>' }
*/
    const { router,controller } = app;
    console.log(router) //app没有router
    router.get("/",controller.home.index)
    router.get("/news",controller.news.list)
    
}

**Comment by dead-horse** [comment]
app 定义了 inspect 方法，console 的时候只会打印少量字段。

**Comment by monkindey** [comment]
更多信息可以查看代码[egg.js#L134-L194](https://github.com/eggjs/egg/blob/2.4.1/lib/egg.js#L134-L194)，不过我有一个问题就是为什么不让开发者打印出来**router**呢？

**Comment by atian25** [comment]
@monkinadey 其实就是漏了而已，提个 PR 加上就好了。以前是用 `app.get` 的方式，现在推荐 `app.router.get`

**Comment by monkindey** [comment]
yeah, PR landed at https://github.com/eggjs/egg/pull/2230
