### ISSUE TITLE
请问egg框架，有什么插件能打印出执行的sql日志？

### ISSUE THREAD

**Issue by 270034480** [eggjs/egg#2229]
如题

**Comment by atzcl** [comment]
如果是使用 egg-sequelize，dev 的时候，终端可以看到执行的 sql 语句

**Comment by 270034480** [comment]
好的，谢谢，一般生产是不需要打印sql的？

**Comment by popomore** [comment]
肯定不能，太多敏感信息

**Comment by atzcl** [comment]
看了下文档，还有提供 debug 到日志的设置，会记录生成的 sql 语句，连接信息等等

**Comment by 270034480** [comment]
好的，谢谢。生产环境下如果不打印执行sql一般是通过什么方式来调试这一类的错误？
