### ISSUE TITLE
eggjs.org打不开

### ISSUE THREAD

**Issue by icepy** [eggjs/egg#2232]
不是程序的问题，是网站打不开，个人已经翻墙，发现eggjs.org网站是部署在新加坡的阿里云机上，不知道管理员有时间看一下这个问题么。

**Comment by zsbox** [comment]
不要用https 改用http应该可以的 我之前也是

**Comment by AloneWeb** [comment]
我的也是 最近一直是这样时好时坏
antd 也一样
我用shadowsocks开全局代理模式就可以访问

**Comment by thonatos** [comment]
某墙间断性屏蔽海外 https 流量，建议访问不了的同学们自行准备梯子。

**Comment by jakehu** [comment]
我也是shadowsocks + Proxy SwitchyOmega走代理就能打开

**Comment by atian25** [comment]
欢迎 PR 支持官网同步发布到国内的托管

**Comment by thonatos** [comment]
夹带私货系列 😜：[https://egg-docs.implements.io/](https://egg-docs.implements.io/)
