### ISSUE TITLE
eggjs中，如何使用global定义全局的变量?或者说，是否允许使用全局变量？

### ISSUE THREAD

**Issue by Tencent-Luis** [eggjs/egg#2234]
* **Node Version**: 9.8.0
* **Egg Version**:2.4.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
直接说场景

**Comment by Tencent-Luis** [comment]
比如：有一个公共的第三方模块目录路径：/home/owen/node_module/ ，现想在项目中，定义一个全局变量来保存路径地址，之后在controller中加载该目录下的模块，就像这样：const jwt = require(BASE_DIR + 'jsonwebtoken');     使用。不知是否可以？

**Comment by atian25** [comment]
在 node 里面最好不要共用 node_modules... 硬盘又不值钱... 你会踩坑的

**Comment by Tencent-Luis** [comment]
好吧。感谢大牛！

**Comment by Tencent-Luis** [comment]
再问一句，如果要这么搞的话，要如何声明？会遇到哪些问题？      劳烦大牛帮忙回答下，十分感谢！

**Comment by atian25** [comment]
全局变量放 app.config 不就行了。

共用的问题在于 A 项目更新了依赖，B 项目可能就挂了。
为什么 A 和 B 之前是要耦合的呢？

我们实践中基本是完全独立的，不仅仅是 node_modules 不相干，连每个项目用的 cli (都作为依赖)，甚至项目用的 Node 都是打包到 node_modules 下的。

完全不依赖于系统环境和配置。

**Comment by Tencent-Luis** [comment]
感谢！

**Comment by gavinwyf** [comment]
生产环境，动态改变app下变量赋值，在其他controller下获取一直undefined。而在egg-bin dev调试环境，app下变量赋值可以get到。这是为什么。 有没有可以在生产环境可以维护的全局变量。我需要动态写入内存中。
