### ISSUE TITLE
项目结构能否改为 packages形式

### ISSUE THREAD

**Issue by ych1** [eggjs/egg#2243]
类似于 [babel](https://github.com/babel/babel),[create-react-app ](https://github.com/facebook/create-react-app)这样的目录结构，开发起来更容易点
例如
```
├── CONTRIBUTING.md
├── CONTRIBUTING.zh-CN.md
├── History.md
├── LICENSE
├── README.md
├── README.zh-CN.md
├── appveyor.yml
├── lerna.json
├── package.json
├── packages
│   ├── egg
│   ├── egg-bin
│   ├── egg-core
│   └── egg-logger
├── scripts
│   ├── commits.sh
│   ├── deploy_key.enc
│   └── doc_travis.sh
├── yarn-error.log
└── yarn.lock
```

**Comment by atian25** [comment]
你指的是 egg 自己，还是你的 egg 应用?

前者的话，我们没计划合并仓库，现在这样分开挺好的。
后者的话，你自己处理就好了。

**Comment by iwege** [comment]
后者的话，在 lerna 3.4.0 (yarn + workspaces), 用 `lerna run dev --scope application` 的方式不能正常启动应用，因为yarn 将node_modules提升到了根目录下，而`egg-utils`寻找`framework`只在`packages/application/node_modules`下面寻找。

如果在`application/package.json` 里面给 `egg.framework`设置为相对路径，那么 egg 其他的插件无法找到。

目前只能用 npm 配合 lerna 来做。
