### ISSUE TITLE
2.4.1 匿名 Context 获取不了model对象

### ISSUE THREAD

**Issue by drunken005** [eggjs/egg#2245]
代码如下
let instance = null;
module.exports = app => {
    if (instance) return instance;
    const config = app.config.verifyCode || {};
    const {collection: conn} = config;
    const ctx = app.createAnonymousContext();

    collection = ctx.model[conn];
    initIndexes(collection);

    return new _VerificationCode(config, app);
};
经过多次测试在本地环境无问题，在测试及生产环境 egg版本为2.4.1后 ctx.model 为undefined 无法获取model对象

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by atian25** [comment]
没装插件吧

**Comment by drunken005** [comment]
@atian25 这个还需要什么插件

**Comment by atian25** [comment]
egg 自带没有 model，只有在 egg-sequelize 和 egg-mongoose 里面才有

**Comment by drunken005** [comment]
@atian25 egg-mongoose肯定有啊

**Comment by drunken005** [comment]
@atian25 我说的是在 2.4.1这个版本里面是拿不到 context的实列，在2.2.x中是可以的

**Comment by atian25** [comment]
> 请提供可复现 demo

**Comment by llh1187** [comment]
> 代码如下
> let instance = null;
> module.exports = app => {
> if (instance) return instance;
> const config = app.config.verifyCode || {};
> const {collection: conn} = config;
> const ctx = app.createAnonymousContext();
> 
> ```
> collection = ctx.model[conn];
> initIndexes(collection);
> 
> return new _VerificationCode(config, app);
> ```
> 
> };
> 经过多次测试在本地环境无问题，在测试及生产环境 egg版本为2.4.1后 ctx.model 为undefined 无法获取model对象

请问您解决这个问题了吗？
