### ISSUE TITLE
app.addSingleton 加异步支持

### ISSUE THREAD

**Issue by XadillaX** [eggjs/egg#2246]
* **Node Version**: -
* **Egg Version**: 2.x
* **Plugin Name**: -
* **Plugin Version**: -
* **Platform**: -
* **Mini Showcase Repository**:
  ```javascript
   app.addSingleton(async (...) => {
     // 从远端获取一些配置
     const conf = await foo.fetch(...);

     return new Instance(conf);
   });
   ```

是否能为 `app.addSingleton()` 增加异步（`async`）支持？

**Comment by popomore** [comment]
这个 @dead-horse 看看，内部 mysql 遇到这个问题

**Comment by popomore** [comment]
之前有个 https://github.com/eggjs/egg/issues/841

**Comment by popomore** [comment]
可以两个维度，在 config 那根据 client 配一个方法，可以让用户动态获取配置。在 handler 也支持 async，让插件也可以自己动态查询配置，比如我们自己就是要从 keycenter 取

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/2353#comment-379800676

**Comment by cuyl** [comment]
还是希望`app.addSingleton`能添加async支持，这样的话我就能直接把异步获取的对象直接挂在app下，而不是在外面封装一层

**Comment by XadillaX** [comment]
https://github.com/eggjs/egg/pull/2382
