### ISSUE TITLE
egg-redis插件报错

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2247]
Node Version:
v8.9.0
Egg Version:
v2.1.0
Plugin Name:
egg-redis
Plugin Version:
2.0.0
Platform:
osx 10.11.6

egg-redis插件报错:
 
**_AssertionError [ERR_ASSERTION]: [egg-redis] 'host: undefined', 'port: undefined', 'password: undefined', 'db: undefined' are required on config
    at Singleton.createClient [as create] (/Users/linxuanwei/Dropbox/wekids/wekids-main-server/node_modules/_egg-redis@2.0.0@egg-redis/lib/redis.js:32:5)_**

配置:
 ```
 redis: {
    client: {
      session: {
        port: 6379,
        host: '127.0.0.1',
        password: 'auth',
        db: 0,
      },
    },
  },
```

如果将配置改成下面的则正常:
```
  redis: {
    client: {
        port: 6379,
        host: '127.0.0.1',
        password: 'auth',
        db: 0,
    },
  },
```

**Comment by atian25** [comment]
请仔细看文档，多个服务的话是 `clients`

**Comment by linxuanwei** [comment]
sorry 看错了   另外问下  agent=true 是什么意思  文档里没说

**Comment by atian25** [comment]
是否要挂载到 agent 上
