### ISSUE TITLE
`egg-passport`无法使用`ctx. isAuthenticated()`校验是否登录

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#2248]
最小可复现demo地址：https://github.com/xjchenhao/passport-error-demo

ps：`app.js`中写了`TODO: 用来表示是否登录成功的开关变量`

**Comment by thonatos** [comment]
看看这个吧，https://github.com/ImplementsIO/dockerizer

**Comment by xjchenhao** [comment]
你好，我的问题解决了，用法不同可能是因为业务需求不一样。。 

关键问题在于**app.js中serializeUser和deserializeUser的回调函数是必填的**，代码我已经更新到demo上去了。
