### ISSUE TITLE
egg-sequelize 生成迁移的命令

### ISSUE THREAD

**Issue by atzcl** [eggjs/egg#2249]
在 [egg-sequelize 文档中](https://github.com/eggjs/egg-sequelize#usage--configuration)，关于在 ` package.json ` 中添加的迁移命令
```
 "migrate:new": "egg-sequelize migration:create"
```
应该为：
```
 "migrate:new": "egg-sequelize migration:create --name"
```
这样才能接收创建迁移文件的名字参数，如：
```
yarn migrate:new create_users_table
```
结果:
```
20180320145031-create_users_table.js
```

**Comment by atian25** [comment]
`yarn migrate:new -- --name=create_users_table`

**Comment by atian25** [comment]
可以看下 npm scripts 文档

**Comment by atzcl** [comment]
@atian25 居然忘了这个，，，尴尬😓
