### ISSUE TITLE
egg在post接口中重定向出现options，导致重定向失败

### ISSUE THREAD

**Issue by dmodaii** [eggjs/egg#2253]
- 在post请求的controller中准备重定向到这个url
   - 直接用postman发post请求可以正常重定向，在前端ajax不行
   - get请求都可以
```
      const setLoginState = await this.service.portal.portal.getLoginState()
      this.ctx.redirect(setLoginState);
```
- 前端的console
***重定向为什么会产生options请求方式***
![image.png](https://dn-cnode.qbox.me/FiRrdR1JAXypMHpgjjfdcZUPSVmR)

- 各位在egg.js中post请求中怎么重定向的啊，

**Comment by atian25** [comment]
如果是 cnode 那个问题的话，朴老师已经回答了，ajax 里面怎么 redirect

**Comment by dmodaii** [comment]
@atian25 请问能给个链接吗， 没搜到， 谢谢

**Comment by chjiyun** [comment]
为啥现在 redirect 不起作用了，header里有location，却没有跳转，以前是可以的啊
