### ISSUE TITLE
egg-sequelize 如何启用更多 DataTypes？

### ISSUE THREAD

**Issue by scottming** [eggjs/egg#2255]
如题，
我如何才能启用 DOUBLE、JSON 等 DataTypes 呢？发现例子都是这样写的：

```
 const { STRING, INTEGER, DATE } = app.Sequelize;
```
但是对于这个 `app.Sequelize` 却没有任何说明，`egg-sequelize` 的文档内容太少了，因为是 nodejs 新手，`egg-sequelize` 的源码看不太懂，望指教，谢谢。

另外能否再 egg 里面直接用 sequelize 而非 egg-sequelize 呢？如果可以，能否提供些例子，半天还没搜到。

**Comment by popomore** [comment]
直接看 sequelize 文档就可以了

**Comment by scottming** [comment]
@popomore 具体在哪里没搜到，还请明示下，谢谢。

**Comment by popomore** [comment]
http://docs.sequelizejs.com/

**Comment by scottming** [comment]
我现在直接用 

```js
const sequelize = require('Sequelize')
sequelize.DOUBLE
```
这样来使用更多的 datatypes 了。

另外要如何才能自动生成 init-migration 呢？如果都要重写一遍，对于从 Python 转到 nodejs 的我，好不习惯呀。参考了 #1538

**Comment by popomore** [comment]
migration 看文档啊

另外为何不用 app.Sequelize. DOUBLE

**Comment by scottming** [comment]
早就看过 sequelizejs 和 egg-sequelize 的文档了，关键是两者都写的不够清楚，另外查看了几个 issues，看来没有自动化的方案了，我手动写了。
