### ISSUE TITLE
测试的问题: 在service中调用第三方远程数据，如何mock request数据？

### ISSUE THREAD

**Issue by zhangming0305** [eggjs/egg#2257]
* **Node Version**: 8.9.4
* **Egg Version**: 2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

比如说写有service抓取支付宝汇率，现在需要对该方法测试，请问如何mock数据在测试时避免request。

**Comment by atian25** [comment]
多看文档 https://eggjs.org/zh-cn/core/unittest.html#mock-httpclient
