### ISSUE TITLE
egg-cluster: connection.close is not a function

### ISSUE THREAD

**Issue by marxy** [eggjs/egg#2258]
![bug1](https://user-images.githubusercontent.com/12171912/37808488-9cbda8f0-2e85-11e8-8c71-77ad5b38fcab.png)
![bug2](https://user-images.githubusercontent.com/12171912/37808499-a38ae378-2e85-11e8-8f75-cbb84823bdfd.png)
运行的时候报这个connection.close is not a function
我去查nodejs api，net.Socket没有找到对应的方法。

* **Node Version**: 8.9.4
* **Egg Version**: 2.3.0
* **Plugin Name**: egg-cluster
* **Plugin Version**: 1.1.14
* **Platform**: linux
* **Mini Showcase Repository**: https://nodejs.org/dist/v8.9.4/docs/api/net.html

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by atian25** [comment]
feel free to reopen if provided more info

**Comment by phper-chen** [comment]
The main reason is that the "sticky" policy in the "egg-cluster" mode, u should disbale it into "false".
