### ISSUE TITLE
 egg-mysql 如何多表联合查询呢？

### ISSUE THREAD

**Issue by devmsg** [eggjs/egg#2263]
如题

**Comment by rojer95** [comment]
使用 this.app.mysql.query(sql,[...])来查询

**Comment by devmsg** [comment]
@rojer95 可以具体给个例子么？ 不怎么会使用原生sql

**Comment by rojer95** [comment]
使用粗糙的例子如下（查询大于15岁的学生的科目）：
const data = await this.app.mysql.query('select subject.* from student right join subject user.id = subject.uid where user.age > ?', [15]);

但是如果你是原生sql语句不会写的话，
建议你自学一下sql的基础哦

**Comment by devmsg** [comment]
@rojer95 好的  但是这种不怕sql注入么？

**Comment by dmodaii** [comment]
@devmsg ? 这种本来就是sql 占位符写法了

**Comment by luogeng2017** [comment]
@rojer95 const data = await this.app.mysql.query('select subject.* from student right join subject user.id = subject.uid where user.age > ?', [15]);使用这种的话，数据库 点 字段(student.name)会报syntax 错误，它会变成 mr`.`id，这样。下面是报错详情，我在mysql中试了都可以查出来。
报错：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`path FROM okcrm`.`m_router mr WHERE mr`.`id IN (SELECT mrr`.`routerid FROM okc' at line 1
