### ISSUE TITLE
egg-view-assets 更多示例

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#2264]
现在示例主要是蚂蚁的产品，如果希望有你想使用的工具、框架，可**提交已开源的代码库**（包括构建和本地开发），Egg 会花时间添加示例。

**Comment by nianiaJR** [comment]
写了一个assets-with-webpack的版本：https://github.com/nianiaJR/assets-with-webpack

**Comment by popomore** [comment]
可以 pr 过来

**Comment by keenghost** [comment]
@nianiaJR 可以加个引入外部 `css` 的示范吗，例如引入 `antd` 的 `css`
