### ISSUE TITLE
运用egg写一个任务，任务停止node服务也停止

### ISSUE THREAD

**Issue by dmodaii** [eggjs/egg#2265]
# 通用需求
想要指定运行一个任务（不是定时任务， 人工可以重复任意时间执行， 但是需要用到egg相关的插件和service所以考虑使用egg； 就是运行一个脚本， 脚本结束node服务就结束

# 实际业务需求
现在的具体场景是， 我需要运行一个查询某个数据库数据， 并配合某个java后端实现一定的数据处理功能； 就是一个脚本

# 请问各路大神怎么设计

**Comment by popomore** [comment]
你是想做 aws 的 lamda？

**Comment by dmodaii** [comment]
@popomore 个人还没想那么复杂， 现在的具体场景是， 我需要运行一个查询某个数据库数据， 并配合某个java后端实现一定的数据处理功能； 就是一个脚本

**Comment by atian25** [comment]
做一个服务一直跑在那里有什么问题么？反正没请求也不消耗多少资源

**Comment by dmodaii** [comment]
@atian25 
- 如果我用定时器任务
那么我这个任务就需要间隔很长， 因为是要执行完一次如果有需要才要去执行第二次； 而且要执行第二次还得重启服务器开始出发定时任务， ***现在是想指定某个任务立即执行***  如果都放在定时任务里面， 无法决定执行哪个了

- 如果在appbefore直接执行service里面的任务
时间太长了， 官方也不建议这样用啊；

- 最主要就是 先指定某个任务任意时间像执行脚本一样执行
您说的服务器一直跑是没问题， 但是怎样指定任务任意时间执行呢

**Comment by atian25** [comment]
发一个 http 或一条消息通知，然后再执行一次即可。

**Comment by dmodaii** [comment]
@atian25 
- 这个应用我只打算进行某些事务处理， 不对外， 所以不搭建对外服务器
即使搭建了对外服务器，http请求过来这边我是需要做一个耗时长的脚本处理， 到时候都会超时，随意这样不对

- 您说的消息通知具体是怎样的

**Comment by thonatos** [comment]
所以使用场景是任务队列吧？

**Comment by dmodaii** [comment]
@thonatos 对的

**Comment by thonatos** [comment]
做过类似的场景是视频转码：

```
user(submit task) ---- http server (append to queue) ---- master ---- worker (pull task)
```

**Comment by atian25** [comment]
就是 egg-schedule 的一个扩展策略即可，收到 redis 或 mq 消息后触发一次 schedule

**Comment by popomore** [comment]
我们其实可以开发一个 redis 的插件作为示例

**Comment by atian25** [comment]
嗯， schedule 扩展那块的文档可以补补

**Comment by dmodaii** [comment]
@popomore @atian25 谢谢你们的建议， 但是任务时间原因， 我这次只能先应用启动时主动触发一次任务， 但是后续再来触发任务我只能暂时先不管了。。。（重启再来一次任务， 主要是这次任务是一次性的，下次也不知道何时才会再触发。。。）

**Comment by atian25** [comment]
你有用到 redis 什么的么

**Comment by dmodaii** [comment]
@atian25 主项目中用到了， 但是当前这个目前只作为任务处理的项目没用

**Comment by JacksonTian** [comment]
直接通过 redis list 就可以了。

Worker 体系跟 Egg 框架其实差距比较大的，可以考虑加强。

**Comment by dmodaii** [comment]
@popomore node egg可以直接运行一个service命令吗， 我一开始问的问题就是怎么直接运行一个脚本， 脚本结束就程序结束了

**Comment by zhennann** [comment]
可以考虑用test执行你的脚本。

-----------------------------------------------------------------
zhennann
zhen.nann@icloud.com
Github: https://github.com/zhennann/egg-born

**Comment by dmodaii** [comment]
@zhennann  这个可以有

**Comment by atian25** [comment]
1. 不建议用单元测试。
2. 实在要走歪路的话：
  - `egg-scripts start --workers=1`
  - 然后在你的那个处理的最后面，`process.kill(process.ppid, '-9')`
3. 我还是倾向于定时任务的扩展的方式，文档其实写的还算清楚了：https://eggjs.org/zh-cn/basics/schedule.html#%E6%89%A9%E5%B1%95%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1%E7%B1%BB%E5%9E%8B

**Comment by atian25** [comment]
简单手写了个

// agent.js

module.exports = agent => {
  agent.messenger.on('egg-ready', () => {
    agent.redis.subscribe('task');
  });

  class RedisStrategy extends agent.ScheduleStrategy {
    start() {
      // 订阅其他的分布式调度服务发送的消息，收到消息后让一个进程执行定时任务
      // 用户在定时任务的 schedule 配置中来配置分布式调度的场景（scene）
      agent.mq.subscribe(schedule.scene, () => this.sendOne());
      agent.redis.on('message', (channel, message) => {
        if (channel === 'task') {
          this.sendOne(message);
        }
      });
    }
  }
  agent.schedule.use('redis', RedisStrategy);
};


// config.default.js
config.redis = {
  client: {},
  agent: true,
};

// app/schedule/task.js
module.exports = {
  schedule: {
    type: 'redis',
  },
  async task(ctx, message) {
    console.log(message);
  }
}

**Comment by dmodaii** [comment]
@atian25 歪路方法中
```
2018-03-25 21:34:51,143 ERROR 10310 [app_worker] exit with code:1
internal/process.js:175
        throw new Error(`Unknown signal: ${sig}`);
        ^

Error: Unknown signal: -9
```

**Comment by atian25** [comment]
`process.kill(process.ppid, 'SIGKILL')`

**Comment by dmodaii** [comment]
@atian25 
```javascript
  async subscribe() {
    const res = await this.ctx.service.shell.test.find({ a: 'ss' });
    // this.app.messenger.sendToApp('test_action', {s: 'sss'});
    process.kill(process.pid, 'SIGKILL')
  }
```
```
2018-03-25 22:10:09,315 ERROR 10652 nodejs.AppWorkerDiedError: [master] app_worker#1:10654 died (code: null, signal: SIGKILL, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/d.hilter/code/node/egg/egg-example/node_modules/egg-cluster/lib/master.js:387:21)
    at emitOne (events.js:115:13)
    at Master.emit (events.js:210:7)
    at Messenger.sendToMaster (/Users/d.hilter/code/node/egg/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/Users/d.hilter/code/node/egg/egg-example/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at EventEmitter.cluster.on (/Users/d.hilter/code/node/egg/egg-example/node_modules/egg-cluster/lib/master.js:264:22)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:169:13)
    at Object.onceWrapper (events.js:318:30)
name: 'AppWorkerDiedError'
pid: 10652
```

**Comment by atian25** [comment]
*PPID*

**Comment by dmodaii** [comment]
@atian25 ppid 这个东西log出来就是没有。。。我还以为你打错了
改了照样不行

**Comment by atian25** [comment]
你需要的是多一点的时间来思考和 Debug。

https://github.com/atian25/egg-showcase/compare/kill?expand=1

**Comment by IEfucker** [comment]
> Worker 体系跟 Egg 框架其实差距比较大的

能分享下见解吗
