### ISSUE TITLE
curl请求超时的时候，如何不返回500错误

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#2266]
* **Node Version**:9.2.1
* **Egg Version**:2.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

使用curl发送post请求的时候，有的时候会超时报错，返回给前台是500错误。
```
nodejs.ResponseTimeoutError: Response timeout for 5000ms
```
请问如何忽略这种curl请求的错误，不返回500给前台？谢谢。

**Comment by atian25** [comment]
自己 try catch 啊

**Comment by popomore** [comment]
你也可以设置 timeout 延长超时时间。

**Comment by superlbr** [comment]
设置timeout好，万一try catch过程中proxy server或者node request超时
