### ISSUE TITLE
单元测试只能获取config.default.js 中配置

### ISSUE THREAD

**Issue by dmodaii** [eggjs/egg#2267]
- 单元测试只能获取config.default.js 中配置
在正常项目中能够获取到其他环境配置， 但是单元测试中只有default 的配置， 最起码要有local吧， 不然最基本的配置都不完全; 
> 这个不是需求， 是bug

- 如何指定使用哪个环境的配置进行跑测试
加上  
```
npm run test-local  --env=sit  
```
用测试也不行

```javascript
'use strict';
describe('test/service/shell.test.js', () => {
  let app;
  before(() => {
    // 创建当前应用的 app 实例
    app = mock.app();
    // 等待 app 启动成功，才能执行测试用例
    return app.ready();
  });
  afterEach(mock.restore);

  describe('service test', () => {
    it('service should start task test', async () => {
      console.log(app.config.mysql)
      
      const ctx = app.mockContext();
      const user = await ctx.service.shell.test.find({ test: 'a' });
      console.log(user);
      assert(user);
      assert(user === 'aa');
    });
  });
});
```

**Comment by atian25** [comment]
再去看一遍文档？

config.unittest.js

**Comment by atian25** [comment]
npm run test-local 自带 env unittest 不要自己指定

**Comment by dmodaii** [comment]
@atian25 只有一份配置。。。。

**Comment by atian25** [comment]
没看懂你想干嘛

**Comment by dmodaii** [comment]
@atian25 虽然这个有点鸡肋， 但是请问可以使用根据传入不同的环境env进行覆盖测试配置吗， 就像是普通的的default.config被其他环境配置覆盖一样

**Comment by atian25** [comment]
配置这块，肯定是 `config.{env}.js` 覆盖 `config.default.js` 的。

BTW，用单元测试来实现你 #2265 这个需求我觉得是歪路。 在那边讨论吧。

**Comment by xjchenhao** [comment]
你好。我想问下，为什么我本地执行单元测试会经过`config.unittest.js`文件，在阿里云的“云效”中的自动化构建环境中，永远只经过`config.default.js`。

在线上服务器中进行单元测试是否要配置什么？

@atian25

**Comment by atian25** [comment]
@xjchenhao 没用过云效，如果你跑的是 `npm test` + `egg-mock` 的话，按理对应的 `app.config.env` 就是 `unittest` 了。除非你有 EGG_SERVER_ENV 等环境变量，导致 egg-mock 和 egg 变为别的 env 了。可以自行检查下日志和 run 里面的 dump，看看 env 是啥。

**Comment by xjchenhao** [comment]
> @xjchenhao 没用过云效，如果你跑的是 `npm test` + `egg-mock` 的话，按理对应的 `app.config.env` 就是 `unittest` 了。除非你有 EGG_SERVER_ENV 等环境变量，导致 egg-mock 和 egg 变为别的 env 了。可以自行检查下日志和 run 里面的 dump，看看 env 是啥。

嗯嗯，人工在服务器环境执行` EGG_SERVER_ENV=test npm run start`同样不生效，应该是哪里配置的问题。

我再看下吧，谢谢～

**Comment by atian25** [comment]
unittest，不是 test
