### ISSUE TITLE
Question: 接收到post请求后触发指定的客户端event发送消息

### ISSUE THREAD

**Issue by DragWeb** [eggjs/egg#2268]
* **Node Version**: "8.9.3"
* **Egg Version**: "2.0.0"
* **Plugin Name**: "egg-socket.io"
* **Plugin Version**: "^4.0.7"

第三方服务器post请求到egg服务器接口`/api/post`，此接口收到数据到触发客户端连接的socket event，
现在客户端与egg服务器socket已经连接成功，但不知如何在post接口中触发event。
请教大神！

**Comment by DragWeb** [comment]
知道了，可以直接访问app.io

**Comment by Faynman-Dragon** [comment]
@z253573760 我也遇到同样的问题，你解决了吗？
