### ISSUE TITLE
实现  app.beforeStart

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#227]
## 背景

应用自定义加载时，在 app.js 中需要调用 service，而 service 在之后加载。如果将 service 移到前面，如果 service 启动时需要使用 app.js 中初始化的客户端就会有问题。所以提供一个 API 在 Loader 同步执行之后再执行。

同时，现在 `app.js` 实现的 generator function 的实现存在一定问题。co 包裹后 promise 会在 nextTick 运行代码，这样如果存在插件依赖那么无法获取被依赖插件的 API。

```js
// a 的 app.js
module.exports = function* () {
  // 在 nextTick 执行
  app.a = 1;
};

// b 依赖 a
// b 的 app.js
module.exports = function() {
  // 这里是同步加载，无法获取 app.a
  console.log(app.a);
};
```

## 实现

```js
app.beforeStart(function*() {
  // 可以处理异步逻辑
});
```

客户端场景请看 https://github.com/eggjs/egg/issues/175#issuecomment-271129653

beforeStart 时用 co 包裹 generator function 注册到 readyCallback，name 传文件路径。

**Comment by dead-horse** [comment]
我先做这个吧

**Comment by xuyuanxiang** [comment]
`app.serviceClasses.yourService.prototype.someMethod()`

我是这么搞的...

**Comment by atian25** [comment]
@xuyuanxiang  ??

**Comment by danielwii** [comment]
请问在 beforeStart 中可以访问 service 吗？

**Comment by dahuahe** [comment]
请问在 beforeStart 中可以访问 service 吗？

**Comment by atian25** [comment]
@dahuahe @danielwii

```js
// app.js
module.exports = app => {
  app.beforeStart(async () => {
    const ctx = app.createAnonymousContext();
    // preload before app start
    await ctx.service.posts.load();
  });
}
```
