### ISSUE TITLE
[RFC] TypeScript tool support

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#2272]
## 背景

当前使用 TypeScript 开发 Egg ，会面临的影响开发者体验问题：

- Egg 最精髓的 Loader 自动加载机制，导致 TS 无法静态分析出部分依赖，譬如 `app/service/news.ts` 会自动挂载为 `ctx.service.news` 。
- Egg 的 Config 自动合并机制下，如何在 `config.{env}.js` 里面修改插件提供的配置时，能校验并智能提示？
- 开发期需要独立开一个 `tsc -w` 独立进程来构建代码，带来临时文件位置纠结以及 `npm scripts` 复杂化。
- 单元测试，覆盖率测试，线上错误堆栈如何指向 TS 源文件，而不是编译后的 js 文件。

## 思路
- 约束
  - Egg 目前没有计划使用 TS 重写。
  - Egg 以及它对应的插件，提供对应的 index.d.ts 文件方便开发者使用。
- 通过 TS 的 [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) 编写 d.ts 来辅助定位。
- 使用 TS 2.8 提供的 [Conditional Types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html) 黑魔法。
- 通过工具链方面的支持，在开发期无需编译 TS
  - egg loader 支持开发期加载 ts 文件
  - egg-bin 等工具支持 sourcemap 和 ts-node
- 同样需引入工具链映射 sourcemap

## 事项

- [x] egg-core loader : https://github.com/eggjs/egg-core/pull/156
- [x] egg-cluster : https://github.com/eggjs/egg-cluster/pull/61
- [x] egg-bin : https://github.com/eggjs/egg-bin/pull/89
  - [x] common-bin : https://github.com/node-modules/common-bin/pull/20
  - [x] `--require`: https://github.com/node-modules/common-bin/pull/21
  - [x] nyc cov 覆盖率: https://github.com/eggjs/egg-bin/pull/91
  - [x] 支持读取 `egg.typescript`: https://github.com/eggjs/egg-bin/pull/92
  - ~~ts-node 的 tsc 版本~~
- [x] egg-mock
  - [x] https://github.com/eggjs/egg-mock/pull/70
  - [x] https://github.com/eggjs/egg-mock/pull/71
- [x] egg-view-nunjucks: https://github.com/eggjs/egg-view-nunjucks/pull/27
- [x] egg-scripts
  - [x] support sourcemap error stack https://github.com/eggjs/egg-scripts/pull/19
- [x] 自动生成 `d.ts` - egg-ts-helper : https://github.com/whxaxes/egg-ts-helper
- [ ] docs
  - [x] guide docs https://github.com/eggjs/egg/pull/2324
  - [x] 语雀 https://yuque.com/egg/nodejs/ts-egg
  - [x] 知乎 https://zhuanlan.zhihu.com/p/35334932
  - [x] 折腾史 https://github.com/whxaxes/blog/issues/12
- [x] example
   - [x] https://github.com/eggjs/examples/pull/63
  - [x] https://github.com/eggjs/examples/pull/66
- [x] d.ts https://github.com/eggjs/egg/pull/2306
- [x] boilerplate https://github.com/eggjs/egg-boilerplate-ts

## 后续

以下内容不属于本期内容，仅做备忘，后续跟进

- [ ] autod
- [ ] pkgfiles
- [ ] egg-di : https://github.com/shepherdwind/egg-di
- [ ] tegg

**Comment by atian25** [comment]
cov 有问题，要看看

https://github.com/istanbuljs/istanbuljs.github.io/blob/development/content/docs/tutorials/typescript.md

**Comment by atian25** [comment]
ts-node 锁版本的，tsc 版本不匹配，可能有坑。。。

**Comment by popomore** [comment]
egg-bin 提供一个使用 ts-node 的 tsc？我还不清楚具体差异。

**Comment by atian25** [comment]
> egg-bin 提供一个使用 ts-node 的 tsc？我还不清楚具体差异。

@popomore 具体指？

我想的是，fork 一个 ts-node 然后去掉它的 lock，这样可以直接用 tsc 的最新版

**Comment by whxaxes** [comment]
我在想，ts 的那些拓展能力没有写到官方文档里的，只是写在了 wiki 中，是不是意味着不是稳定的，我觉得 ts-node 的作者是不是担心 ts 某个版本突然把某个 api 改掉了，就 break 了，所以才把版本给锁了

**Comment by atian25** [comment]
但起码要更新吧。 或者提个 PR 帮他把 lock 更新到最新吧

**Comment by atian25** [comment]
看错了。。。 ts-node 没有带 tsc 的，那是 dev dep。

**Comment by atian25** [comment]
- `egg-scripts` - support sourcemap error stack https://github.com/eggjs/egg-scripts/pull/19
- `example` https://github.com/eggjs/examples/pull/63
- `d.ts` https://github.com/eggjs/egg/pull/2306

**Comment by atian25** [comment]
更新正文，补充背景和思路

**Comment by atian25** [comment]
1. PowerPartial，EggPlugin，EnvType 下沉到 egg，合并到那个 PR
2. ets 支持 import plugin
3. 编写 插件开发指南
4. 更新 example
5. 编写 TS 踩坑折腾史
6. Middleware Options
7. ets 支持检查同名文件并提醒

**Comment by waitingsong** [comment]
- test 用例是否支持直接运行 .ts 文件。如果用 ts-node 直接跑用例，那么就无法使用不同类型的参数来测试接口了

**Comment by atian25** [comment]
@waitingsong 没看懂

**Comment by waitingsong** [comment]
@atian25   `egg-bin test --grep=` 这个没看懂

我的意思是假如有模块函数
```ts
function add(a: number, b: number): number {
  return a + b;
}
```
如果基于 TS 开发，那么不用检查 a/b 的类型。并且在用 TS 写的测试用例里面也无法测试非数字类型参数情况
```ts
it('shoud add workds', () => {
  assert(add('1', 2) === 3)
})
```
VSC 直接报类型错误。
但是假如调用模块的开发语言不是 TS 的情况，那么就需要在 add() 函数内做类型检查或者转换。那么产生 if/else 分支在跑 cov 里面就会有 missing 。于是又只有加上忽略注释
```
/* istanbul ignore next */
/* istanbul ignore if  */
/* istanbul ignore else  */
```
挺头疼的……

**Comment by waitingsong** [comment]
有个问题：
如果 `tsconfig.json` 中设置  `"declaration": true` 那么提示错误
>config/config.prod.ts:3:1 - error TS4082: Default export of the module has or is using private name 'PowerPartial'.
  3 export default () => {
    ~~~~~~~~~~~~~~~~~~~~~~
  4   const config = <DefaultConfig> {}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 10   return config
    ~~~~~~~~~~~~~~~
 11 }
    ~

貌似是 `PowerPartial` 引发，设置 declaration 为 false 就不报错。
看起来貌似 PowerPartial 这个接口没有 export  导致的，不过我已经修改了  `node_modules/egg/index.d.ts` 导出了的啊？

**Comment by waitingsong** [comment]
如果把  `config.default.ts` 文件的
```ts
// for config.{env}.ts
export type DefaultConfig = PowerPartial<EggAppConfig & BizConfig>
```
改成 
```ts
export type DefaultConfig = EggAppConfig & BizConfig
```
就不会有上面的错误。

**Comment by whxaxes** [comment]
@waitingsong 感觉不像是 declaration 的问题？我本机试了一下设置 declaretion 为 true，没有出现你所述的错误，提供个稳定复现的项目看看？

**Comment by waitingsong** [comment]
我是在 egg-example/hacknews-async-ts 这个目录里面遇到这个问题的

**Comment by waitingsong** [comment]
@whxaxes 
https://github.com/eggjs/examples 目录 `hackernews-async-ts` ， 修改 `tsconfig.json` 添加  `"declaration": true,` 就能复现了

**Comment by waitingsong** [comment]
最小复现代码

config.default.ts
```ts
export interface Config {
  keys: string
  news: {
    pageSize: number;
  };
}

export type PowerPartial<T> = {
  [U in keyof T]?: T[U] extends {}
  ? PowerPartial<T[U]>
  : T[U]
}

// for config.{env}.ts
export type DefaultConfig = PowerPartial<Config>;
```

config.local.ts
```ts
import { DefaultConfig } from './config.default';

export default () => {
  const config: DefaultConfig = {};

  config.keys = 'foo'

  return config;
};

```

**Comment by waitingsong** [comment]
如果把
```ts
export interface Config {
  keys: string
  news: {
    pageSize: number;
  };
}
```
删除 news 对象为
```ts
export interface Config {
  keys: string
 // news: {
  //  pageSize: number;
  // };
}
```
就没问题

**Comment by waitingsong** [comment]
如果把 config.local.ts 的内容复制到 config.default.ts 然后删除，也不会报错

**Comment by lindraco** [comment]
@atian25 ts模板的schedule无法使用啊

**Comment by duncup** [comment]
@lindraco 可以用，我已经在用了。
先安装`@types/sequelize`
```ts
//typings/index.d.ts
import Sequelize from 'sequelize';

declare module 'egg' {

  // 扩展 app
  interface Application {
    Sequelize: Sequelize;
    model: Sequelize.Sequelize;
  }

  // 扩展 context
  interface Context {
    Sequelize: Sequelize;
    model: Sequelize.Sequelize;
  }

  // 扩展你的配置
  interface EggAppConfig {
    sequelize: {
      dialect: string;
      database: string;
      host: string;
      port: string;
      username: string;
      password: string;
    };
  }

}

```
简单点的话也可以用any

**Comment by atian25** [comment]
这个 RFC 可以关了， tegg 那边回头 @popomore 另起

**Comment by popomore** [comment]
OK
TZ | 天猪 <notifications@github.com>于2018年4月12日 周四下午3:25写道：

**Comment by qinshou** [comment]
@shangyu95 sequelize、mongo也无法使用，egg-ts-helper只监听了固定的4个目录 🤥

**Comment by isLishude** [comment]
上次看到死马的采访说egg不会使用ts重写，tegg 使用 ts 重写版本么？

**Comment by ngot** [comment]
不会用Ts重写egg内核，没有意义。

**Comment by atian25** [comment]
不会，tegg 只是一个上层框架。

Egg 至少一年内没有重写的计划，没有什么特别的好处。

**Comment by yaonote** [comment]
ts 版本的入口文件在哪里 啊???

**Comment by whxaxes** [comment]
@yaonote  入口文件？说说你遇到的问题吧

**Comment by yaonote** [comment]
> @yaonote 入口文件？说说你遇到的问题吧

我想在 app.js 的文件中先做一些权限验证? 但是在 ts 版中不清除该写到哪里? 多谢回复.

**Comment by yaonote** [comment]
> > @yaonote 入口文件？说说你遇到的问题吧
> 
> 我想在 app.js 的文件中先做一些权限验证? 但是在 ts 版中不清除该写到哪里? 多谢回复.

知道了,我找到了

**Comment by yaonote** [comment]
> @yaonote 入口文件？说说你遇到的问题吧

理解了,打扰了~~~~~~

**Comment by whxaxes** [comment]
@unclexiao  没有搁浅，目前 egg 已经可以使用 ts 了，tegg 只是一个依赖注入方案的 egg 上层封装框架，目前还没空做而已。
