### ISSUE TITLE
文件上传限制为5mb，上传15mb的文件不报错，保存时把文件截取了5mb存到磁盘了

### ISSUE THREAD

**Issue by longjxchina** [eggjs/egg#2277]
* **Node Version**:8.9.0
* **Egg Version**:2.2.1
* **Plugin Name**:egg-multipart
* **Plugin Version**:
* **Platform**:windows 10
* **Mini Showcase Repository**:

文件上传限制为5mb，上传15mb的文件不报错，保存时把文件截取了5mb存到磁盘了。
配置：
  config.multipart = {
    fileSize: '5mb',
    fileExtensions: [ '.doc', '.xls', '.ppt', '.pdf', '.docx', '.xlsx', '.pptx' ],
  };

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by atian25** [comment]
提供复现方式后，再自行开启
