### ISSUE TITLE
npm start 会自动开启多个 node 窗口而且不能关闭

### ISSUE THREAD

**Issue by newBird01** [eggjs/egg#2280]
$ npm i egg-init -g
$ egg-init *** --type=simple
$ cd ***
$ npm i
**_# npm start 会自动开启多个 node 窗口而且不能关闭_**
以下是package.json配置 
` "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-shop",
    "stop": "egg-scripts stop --title=egg-server-shop",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },`

**_下面是执行npm  start 命令后的信息_**

`E:\外包\商城后端\jj_site\shop>npm start

> shop@1.0.0 start E:\外包\商城后端\jj_site\shop
> egg-scripts start --daemon --title=egg-server-shop

[egg-scripts] Starting egg application at E:\外包\商城后端\jj_site\sho
p
[egg-scripts] Run node E:\外包\商城后端\jj_site\shop\node_modules\egg-
scripts\lib\start-cluster {"title":"egg-server-shop","framework":"E:\\
外包\\商城后端\\jj_site\\shop\\node_modules\\egg","baseDir":"E:\\外包\
\商城后端\\jj_site\\shop"} --title=egg-server-shop
[egg-scripts] Save log file to C:\Users\Administrator\logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] Wait Start: 6...
[egg-scripts] Wait Start: 7...
[egg-scripts] Wait Start: 8...
[egg-scripts] Wait Start: 9...
[egg-scripts] Wait Start: 10...
[egg-scripts] Wait Start: 11...
[egg-scripts] egg started on http://127.0.0.1:7001`

服务可以运行，但是node 窗口启用了多个

怎么解决这个问题呢

**Comment by atian25** [comment]
多个进程肯定是多个窗口的。
你找下 win 下如何配置后台运行服务吧。
