### ISSUE TITLE
egg-init定制化开发

### ISSUE THREAD

**Issue by Webjiacheng** [eggjs/egg#2281]
针对egg-init这个插件，想知道能不能定制化自己独特的模板，比如我的模板初始化后就具有增删改查基本业务逻辑，但不知怎么弄，求指教

**Comment by atian25** [comment]
可以定制的，参考 https://github.com/eggjs/egg-boilerplate-simple 写一个然后发布到 npm。
然后可以通过 egg-init --package=xxx 的方式使用
