### ISSUE TITLE
egg-mysql 中事务自动控制无法响应多次提交请求？

### ISSUE THREAD

**Issue by 2015-lizaiyang** [eggjs/egg#2282]
<img width="1426" alt="qq" src="https://user-images.githubusercontent.com/21666293/38006783-0197b1b6-3279-11e8-9d54-04331d549bd3.png">

**Comment by polk6** [comment]
也遇到这种情况，某个请求里的sql事务要进行 4个表的修改操作，若此请求量超过1秒6次，那么eggjs内的所有业务的数据库操作都无法执行。重新启动eggjs，又可以进行数据库操作，但只要请求数一次超过1秒6次，就会出现相同的问题。

**Comment by polk6** [comment]
我这找到原因了，事务中返回响应前需要调用 conn.rollback()
`
        const conn = await super.mysql.beginTransaction(); // 初始化事务
        try {
            let rs = await query(Y);
            if(rs){
                 this.ctx.body = {
                        code: -1,
                        message:XXX
                 };
                 return;
            }

            await this.ctx.service.business.edit(en, conn);
            await conn.commit(); // 提交事务
        } catch (err) {
            await conn.rollback(); // 一定记得捕获异常后回滚事务！！
            throw err;
        }
        super.success('操作成功');`

修改为：
`
        const conn = await super.mysql.beginTransaction(); // 初始化事务
        try {
            let rs = await query(Y);
            if(rs){
                 await conn.rollback(); 
                 this.ctx.body = {
                        code: -1,
                        message:XXX
                 };
                 return;
            }

            await this.ctx.service.business.edit(en, conn);
            await conn.commit(); // 提交事务
        } catch (err) {
            await conn.rollback(); // 一定记得捕获异常后回滚事务！！
            throw err;
        }
        super.success('操作成功');`

**Comment by popomore** [comment]
看你是开了两个事务。
