### ISSUE TITLE
[egg-graphql] update graphql dependency to 0.13

### ISSUE THREAD

**Issue by Carrotzpc** [eggjs/egg#2286]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**: egg-graphql
* **Plugin Version**: 
* **Platform**:
* **Mini Showcase Repository**:

apollo-server 's peer dependency range for graphql has been expanded to include `graphql@0.13.x`:

> As of apollo-server-*@1.3.3 (released this past Monday, as noted in https://github.com/apollographql/apollo-server/issues/812#issuecomment-376260520 above), the peer dependency range for graphql has been expanded to include `graphql@0.13.x` (including the latest graphql@0.13.2 which came out a couple weeks ago).

https://github.com/apollographql/apollo-server/issues/812

**Comment by Maledong** [comment]
@atian25：
The latest versions is v2.X (Ref：https://github.com/eggjs/egg-graphql/pull/18). And we've upgraded it to 1.x as the lastest version. So this can be closed.
