### ISSUE TITLE
请问在Controller里面调用其他的controller应当如何实现？

### ISSUE THREAD

**Issue by g1mi** [eggjs/egg#2287]
* **Node Version**:
v8.10.0
* **Egg Version**:
v2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
windows 10
* **Mini Showcase Repository**:
[eggjs-controllerCalling](https://github.com/g1mi/bugReport/tree/master/eggjs-controllerCalling)
* **Refer**:
 https://github.com/eggjs/egg/issues/2252

controller   之间的调用应当如何实现呢，用类似于调用service的方法会报错
![1](https://user-images.githubusercontent.com/12378287/38067709-5498f588-3340-11e8-9f4b-ae84829b11d4.PNG)
![default](https://user-images.githubusercontent.com/12378287/38067721-60f4c7ee-3340-11e8-85b1-d58ee78f1486.PNG)
debug看了一下，貌似这里传进来的并不是ctx
![default](https://user-images.githubusercontent.com/12378287/38067792-a30bf6ca-3340-11e8-9b9e-fdc86c5ae321.png)

抱歉未看过源码，为了方便查看这是复现代码截图，望相助！
![2](https://user-images.githubusercontent.com/12378287/38067851-c2b654d4-3340-11e8-99e0-1b54380c2012.PNG)
![3](https://user-images.githubusercontent.com/12378287/38067856-ca80f26e-3340-11e8-9628-119e42c87c19.PNG)

**Comment by atian25** [comment]
Controller 不应该互相调用，可复用逻辑放到 Service 层
