### ISSUE TITLE
官网什么时候能好，怎么一直挂着

### ISSUE THREAD

**Issue by jerrydotlam** [eggjs/egg#2288]
* **Node Version**: v8.1.3
* **Egg Version**: latest
* **Plugin Name**: eggjs.org
* **Plugin Version**: 
* **Platform**: all
* **Mini Showcase Repository**:

官网什么时候能好，怎么一直挂着

**Comment by atian25** [comment]
https://zhuanlan.zhihu.com/p/34846386
