### ISSUE TITLE
[ egg-sequelize ] 可以挂载 app/model 子级目录，而不是排除么

### ISSUE THREAD

**Issue by atzcl** [eggjs/egg#2295]
` egg-sequelize/lib/loader.js ` 的源码：
```

if ('sequelize' in klass) {
      app.model[name] = klass;
      ....
}
```
因为一张表如果有多张副表的话，把它们归类到一个目录里面会比较清晰、容易查找，而且项目大了之后，整个 ` model ` 都是表文件，这样看着很乱，而根据模块、主副关系来存放到相应的文件目录中会比较好吧。
例子：
```
// app/model/article

articles.ts
article_images.ts
article_extends.ts
article_categories.ts
article_attachments.ts
....
```

**Comment by 215566435** [comment]
这个可以有

**Comment by atian25** [comment]
欢迎提 RFC 和 PR

**Comment by atzcl** [comment]
@215566435 
对于第一点，我是增加了一个 `repository` 层来辅助 `model` ，`model` 只负责定义字段还有查询作用域啥的，然后所有对 `model` 的操作都通过对应的 `repository` 来使用，然后在 `repository` 里面定义一个
```
get model () {
    return this.ctx.model.xxx.xxx.xxx.xx
}
```
来变相地缩短调用方法的长度，，，关于 `repository` 的调用方法的长度问题，因为我是自己拓展成了 `modules` 模块目录开发，所以不算太长，，
对于第四点的增加依赖注入，非常同意，，最好还能增加一个 IoC 容器、Facade 模式，这样使用起来会更加方便，，

**Comment by atzcl** [comment]
@atian25 我没有太好的想法，目前想到的只是参照 `egg-core/lib/loader/file_loader.js` 的 ` load ` 方法，来循环挂载，，

**Comment by 215566435** [comment]
@atzcl 多说几个一起讨论，然后就有RFC了...

**Comment by roy2an** [comment]
项目中也出于这样的考量，使用子目录的形式。遇到的问题是数据表虽然同步了，但其实model没有被注册到app.model中，associate方法也没有被调用。
之后自己修改了一下loader.js
`function loadModel(app) {
  const modelDir = path.join(app.baseDir, 'app/model');
  app.loader.loadToApp(modelDir, MODELS, {
    inject: app,
    caseStyle: 'upper',
    ignore: 'index.js',
  });
//   for (const name of Object.keys(app[MODELS])) {
//     const klass = app[MODELS][name];
//     // only this Sequelize Model class
//     if ('sequelize' in klass) {
//       app.model[name] = klass;
//       if ('classMethods' in klass.options || 'instanceMethods' in klass.options) {
//         app.logger.error(`${name} model has classMethods/instanceMethods, but it was removed supports in Sequelize V4.\
// see: http://docs.sequelizejs.com/manual/tutorial/models-definition.html#expansion-of-models`);
//       }
//     }
//   }
  // for (const name of Object.keys(app[MODELS])) {
  //   const klass = app[MODELS][name];

  //   if ('associate' in klass) {
  //     klass.associate();
  //   }
  // }
  recursionModel(app[MODELS], app);
  recursionAssociate(app[MODELS]);
}
function recursionModel(values, app) {
  for (const name of Object.keys(values)) {
    const klass = values[name];
    if ('sequelize' in klass) {
      app.model[name] = klass;
      if ('classMethods' in klass.options || 'instanceMethods' in klass.options) {
        app.logger.error(`${name} model has classMethods/instanceMethods, but it was removed supports in Sequelize V4.\
see: http://docs.sequelizejs.com/manual/tutorial/models-definition.html#expansion-of-models`);
      }
    } else if(klass){
      recursionModel(klass, app);
    }
  }
}
function recursionAssociate(values) {
  for (const name of Object.keys(values)) {
    const kclass = values[name];
    if ('sequelize' in kclass) {
      if ('associate' in kclass)
        kclass.associate();
    } else {
      recursionAssociate(kclass);
    }
  }
}`

**Comment by atzcl** [comment]
@roy2an 你可以提交 PR~
