### ISSUE TITLE
关于egg插件内中间件报错的问题

### ISSUE THREAD

**Issue by BertieGo** [eggjs/egg#2298]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

一下是文件的内容和路径:

<--app.js-->
app.middleware.push('makeUpRealPathHandler');

<-- app/middleware/make_up_real_path_handler.js -->
module.exports = (options, app) => {
  return () => {
    console.log(this);
  };
};

error:
2018-03-30 10:31:03,779 ERROR 12090 [-/127.0.0.1/-/3ms GET /app/hotel/home] nodejs.TypeError: middleware[i].call is not a function

我看了官方的关于做插件内的中间件的方法，但是那种方式对我并不适用，是否是我的写法有问题还是什么情况？哦，我的egg版本是1.11.0.

如能解决，十分感谢。

**Comment by atian25** [comment]
`app.middleware.push` 的入参是函数，不是字符串。

为什么官方的推荐方式不适合？

**Comment by BertieGo** [comment]
不好意思我应该补充一下各个的版本。
Node Version: 8.9.1
Egg Version: 1.11.0
Plugin Name: 自定义
Plugin Version: 自定义
Platform:  未知
Mini Showcase Repository:  未知

**Comment by BertieGo** [comment]
首先是因为官方文档中描述的是app.config.coreMiddleware，但是在我的项目中并没有出现coreMiddleware，而仅仅是出现了middleware，其次就是plugin内使用Middleware的方式跟根项目使用Middleware的差别还是很大的

**Comment by atian25** [comment]
没看懂你的问题。。。 直接给仓库吧

**Comment by BertieGo** [comment]
由于这个项目是本公司的项目且假如我再弄一个仓库出来的确是耗时太长了，不过这也是一个最后的解决方式，刚刚你所提示我的push进一个function的用法在我这边已经奏效了，谢谢你

**Comment by atian25** [comment]
你直接用 `egg-init --type=simple` 新建一个，加上你的逻辑就够了，没那么复杂。

或者可以再去看看中间件那块的文档，我感觉是你的一些地方的理解有偏差
