### ISSUE TITLE
用sequelize的query方法去查会出现两条数据，用自定义模型去查正常

### ISSUE THREAD

**Issue by yumeiqiang** [eggjs/egg#2299]
* **Node Version**: 8.9.3
* **Egg Version**: 2.0.0
* **Plugin Name**: sequelize
* **Plugin Version**: 3.1.2
* **Platform**: mac
* **Mini Showcase Repository**:

是我写法的问题吗
![55](https://user-images.githubusercontent.com/16550302/38126188-84e69c0e-3421-11e8-9cdf-b2beddebb1bf.jpeg)
![66](https://user-images.githubusercontent.com/16550302/38126187-84996ea2-3421-11e8-88a7-0e369c92283d.jpeg)

**Comment by 215566435** [comment]
应该不是插件问题，有问题也很可能是seqeulize本身的问题。请查阅一下你的数据库是不是你多插入了一条

**Comment by yumeiqiang** [comment]
id是唯一的

**Comment by yumeiqiang** [comment]
id是自增唯一的，确实奇怪，用findById()又是正常的

**Comment by 215566435** [comment]
@yumeiqiang 尝试升级一下seqeulize。

**Comment by awhlmycn** [comment]
我也是这样的问题，不知道是不是必须用sequelize这个对象？而不是model的 我再express上面测试的是正确的，这个问题不知道你解决没有了

**Comment by awhlmycn** [comment]
解决了,再sequelize的配置文件里面加入 query : { raw : true, type:'select' };
这样就可以解决了，或者你再查询的后面进行加入 eg: this.app.model.query( 'select * from user ', {
row: true,
type :'select'
})

**Comment by awhlmycn** [comment]
解决了,再sequelize的配置文件里面加入 query : { raw : true, type:'select' };
这样就可以解决了，或者你再查询的后面进行加入 eg: this.app.model.query( 'select * from user ', {
     row: true,
     type :'select'
})

**Comment by awhlmycn** [comment]
解决了,再sequelize的配置文件里面加入 query : { raw : true, type:'SELECT' };
这样就可以解决了，或者你再查询的后面进行加入 eg: this.app.model.query( 'select * from user ', {
row: true,
type :'SELECT'
})
试验了，小写的select不行，具体你也可以试试

**Comment by Solomonqoo** [comment]
好糟糕的問是啊
