### ISSUE TITLE
定时任务传参

### ISSUE THREAD

**Issue by GSBL** [eggjs/egg#2300]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

如何给定时任务传参,看了下代码  runSchedule 只会传入ctx
```
app.runSchedule = schedulePath => {
 
    return schedule.task(ctx);
  };

```

**Comment by atian25** [comment]
`runSchedule` 只是测试使用的。 不建议手动调用

**Comment by GSBL** [comment]
ok

**Comment by yuu2lee4** [comment]
我觉得传参还是很有必要的，有一些定时任务跟时间有关，比如今天去数据库拉取昨天的数据进行一些计算，假如某一天发现几天前的定时任务有问题，想重跑，就必须手动调用定时任务，并且传一个时间去指定需要跑的数据的日期

**Comment by atian25** [comment]
把需要重跑的任务存数据库，定时任务读出来就可以了。或者自己扩展下定义 cluster 的定时任务策略

**Comment by yuu2lee4** [comment]
这个定时任务是获取昨天的数据进行一些计算，如果我要重新计算前天的，这个时间就需要穿进去，虽然说也可以通过数据库去做，但是如果本身就支持传参就很方便了

**Comment by atian25** [comment]
我可以提个 https://github.com/eggjs/egg-schedule/pull/47 支持传参。

但还是需要声明下： `runSchedule` 仅提供给测试使用的，你需要的是自定义一个  Strategy 去传递 args，该存的还是要存的，要考虑下集群和异常重启的场景。
