### ISSUE TITLE
socket.io -upgrade socks

### ISSUE THREAD

**Issue by vosonwang** [eggjs/egg#2301]
安装依赖提示：
warning egg > urllib > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

这个是要egg 升级自身依赖吗？

**Comment by popomore** [comment]
看提示 1.x 没问题
