### ISSUE TITLE
如何自定义一个目录文件

### ISSUE THREAD

**Issue by csm0912** [eggjs/egg#2302]
可以通过  /public/**  的形式访问到app/public目录下的文件
如果想要自定义一个目录（如tpl），和public同级，怎样才能做到，可以直接通过  /文件名/*** （如/tpl/**）的形式访问到该目录下的文件

**Comment by atian25** [comment]
egg-static 配置下即可

**Comment by csm0912** [comment]
egg-static插件，线上环境下，会默认 cache。
现在希望设置的是，静态资源还是默认查找public下文件，允许cache。但是还有一些静态文件希望放在其他目录下
