### ISSUE TITLE
A confusing logger config for production env

### ISSUE THREAD

**Issue by dsonet** [eggjs/egg#2310]
* **Egg Version**:2.5.0
When I want to enable the DEBUG level in production env,somehow I have to set `allowDebugAtProd = false` to turn the DEBUG level on, that's made me really confusing.

```javascript
  if (app.config.env === 'prod' && loggerConfig.level === 'DEBUG' && loggerConfig.allowDebugAtProd === true) {
    loggerConfig.level = 'INFO';
  }
```
Since it's `allowDebugAtProd` , so here should be `!loggerConfig.allowDebugAtProd` instead of `loggerConfig.allowDebugAtProd === true`

**Comment by atian25** [comment]
yes, pr is welcome
