### ISSUE TITLE
app.js没有加载

### ISSUE THREAD

**Issue by jakehu** [eggjs/egg#2312]
* **Node Version**:8.11.0
* **Egg Version**:2.5.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

app.js没有加载

// app.js
```
module.exports = app => {
  console.log('11111111');
  app.beforeStart(async () => {
    await console.log('222222222');
  });
};
```
终端输出
```
jakehu@jakehu:~/Web/siege$ npm run dev

> siege@1.0.0 dev /home/jakehu/Web/siege
> egg-bin dev

2018-04-03 16:34:04,514 INFO 7994 [master] node version v8.11.0
2018-04-03 16:34:04,516 INFO 7994 [master] egg version 2.5.0
2018-04-03 16:34:04,860 INFO 7994 [master] agent_worker#1:8000 started (342ms)
2018-04-03 16:34:05,482 INFO 7994 [master] egg started on http://127.0.0.1:7001 (966ms)
```

**Comment by atian25** [comment]
提供最小可复现代码库

**Comment by jakehu** [comment]
这个跟整体代码库有关系？app.js不是应该会最先加载么？

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

因为我们本地不能复现。

**Comment by jakehu** [comment]
@atian25  已解决，略坑，我们同事把app.js放在了app目录下

**Comment by atian25** [comment]
感觉可以给 https://github.com/eggjs/eslint-plugin-eggache 提个 PR 检查文件在错误的目录

**Comment by shiqinghui** [comment]
app.js 到底怎么回事，在哪里？或者添加到哪里？

**Comment by tiodot** [comment]
> app

这个好有歧义，我也放app目录下面了。。看了好大一会。。

**Comment by tiodot** [comment]
> @atian25 已解决，略坑，我们同事把app.js放在了app目录下

这个好有歧义，我也放app目录下面了。。看了好大一会。

**Comment by athlan20** [comment]
还好搜到这里。。我也放在app目录下了。。
