### ISSUE TITLE
egg.js基类 函数调用 是不是做拦截处理？

### ISSUE THREAD

**Issue by yecao007** [eggjs/egg#2314]
我在egg.js 框架创建一个基类控制器BaseController ，有个检测函数checkAuth,主要是获取jwt的token 并解密，存到全局变量的globalToken，（如果token不正确，我直接设置ctx.body的错误信息，然后return;），在子类UserController 的方法调用checkAuth，起不来拦截作用，直接往下执行,不会打印我的错误信息。。。。

不过试着获取他的返回值，来子控制器做判断，就可以，但是这样基类控制器的拦截器起不到什么拦截作用了

感谢您向我们反馈问题。

1. 提交问题前，请先阅读 https://eggjs.org/zh-cn/faq.html
2. 我们推荐如果是小问题（错别字修改，小的 bug fix）直接提交 PR。
3. 如果是一个新需求，请提供：详细需求描述，最好是有伪代码实现。
4. 如果是一个 BUG，请提供：复现步骤，错误日志以及相关配置，并尽量填写下面的模板中的条目。
5. 如果可以，请使用 `egg-init --type=simple bug` 提供一个最小可复现的代码仓库，方便我们排查问题。
6. 扩展阅读：[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)
-->

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
为什么不直接放到 Middleware ？

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by popomore** [comment]
长时间未回复，如有问题再自行开启。
