### ISSUE TITLE
[egg-bin] test 执行参数 --require babel-register与egg-bin内部依赖intelli-espower-loader冲突

### ISSUE THREAD

**Issue by kurten** [eggjs/egg#2315]
* 执行 ```egg-bin test --require babel-register```时与内部 intelli-espower-loader冲突了，导致没有预先执行babel-register的编译
* 复现分支代码 https://github.com/kurten/sdk-base/tree/egg-bin-bug

**Comment by atian25** [comment]
babel-register 要先于 intelli-espower-loader 加载？

**Comment by kurten** [comment]
预期是 babel-register 先于 intelli-espower-loader。

当然现在通过 .setup.js 解决了这个问题。

**Comment by atian25** [comment]
`.setup.js` 能解决？ 按我的理解，requireArr 应该优先级更高才对

**Comment by atian25** [comment]
反了吧， https://github.com/eggjs/egg-bin/blob/master/lib/cmd/test.js#L77

这里的源码来看，优先顺序是：

`--require` > `built-int require` > `files`

`intelli-espower-loader` 是 push 进去的，晚于 `--require`

**Comment by kurten** [comment]
看了下intelli-espower-loader的源码，应该是修改了 require.extensions 的逻辑导致的。这里有点坑。。。

**Comment by atian25** [comment]
他肯定要改的。不确定你这里是遇到什么坑，我们用 ts 的时候，也是一样的做法，但两者没冲突

**Comment by popomore** [comment]
两天没回复，有问题再开启

**Comment by rushairer** [comment]
问题依然存在

**Comment by rushairer** [comment]
https://github.com/eggjs/egg-bin/pull/135

**Comment by atian25** [comment]
@rushairer 你的意思是需要 `-r babel-plugin-espower -r babel-register` ？
