### ISSUE TITLE
如何处理前端history模式？

### ISSUE THREAD

**Issue by six-666** [eggjs/egg#2319]
新需求：
如何处理前端history模式的问题？类似[connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback)

**Comment by popomore** [comment]
找一个 koa 中间件

**Comment by six-666** [comment]
@popomore [koa2-connect-history-api-fallback](https://github.com/ishen7/koa2-connect-history-api-fallback)  在egg里加载koa中间件不管用。
