### ISSUE TITLE
egg-mysql支持where like查询吗

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#232]
egg-mysql支持where like查询吗？支持的话，有没有例子

**Comment by dead-horse** [comment]
支持你写任意 sql 语法。例子直接去看 mysql 的例子就好了。

**Comment by TDiDa** [comment]
@dead-horse 不直接写sql语句呢，下面这种
`
app.mysql.select('file', 
{ 
    where: { name: 'test'} 
})
`

**Comment by fengmk2** [comment]
@TDiDa 使用 app.mysql.query(sql)
