### ISSUE TITLE
关于egg启动报错的原因分析

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#2320]
昨天部署的服务器时发现使用npm start时报
AssertionError [ERR_ASSERTION]: F:\nodeProject\turing\interface\interface\package.json should exist
之后在interface目录下增加一个interface目录，可正常启动，但是进行接口请求的时候发现继续报错,
keys should set first
进过分析，是因为packege.json的start命令后面增加了argv 即当前程序的目录名称，将interface删除可正常启动。

**Comment by atian25** [comment]
你不按目录规范来，错误很正常吧。

不要提牙膏的提问啦，直接提交一个最小可复现代码库到你的 GitHub

**Comment by tong3jie** [comment]
目录都是egg-init自动生成的

**Comment by atian25** [comment]
提交最小可复现代码库
