### ISSUE TITLE
最新版vscode，vscode-eggjs调试报错

### ISSUE THREAD

**Issue by whwnow** [eggjs/egg#2325]
* **Node Version**: 9.2.0
* **Egg Version**: 2.5.0
* **Vscode Version**: 1.22.1
* **Plugin Name**: vscode-eggjs
* **Plugin Version**: 0.3.1
* **Platform**: windows

安装了最新的vscode的版本1.22.1。发现eggjs的插件不能调试了。每次调试出错误弹窗。提示this socket has been ended by other party

**Comment by atian25** [comment]
你开了 auto attach 吧，把这个关掉吧。

**Comment by atian25** [comment]
可以复现，@whxaxes 看看

**Comment by whwnow** [comment]
@atian25 auto attach 这个设置在哪里？但是我的场景是升级前还在调试，看到vscode有升级提示，顺手就升级了，然后就出错了。现在退回旧版正常使用。

**Comment by atian25** [comment]
F1 后可以找到，可能是 vscode 新版的 bug，要看看。

**Comment by whwnow** [comment]
@atian25 F1也没找到这个命令，等你们排除了再升级vs吧，我先用旧版。谢谢回复

**Comment by atian25** [comment]
目前看起来是 vscode 的 bug，先降级等官方吧。

**Comment by yulaughing** [comment]
@whwnow ，能问一下vscode ，是怎么退回旧版的么？

**Comment by whwnow** [comment]
我之前本地留有旧版的安装包，重新装的……

**Comment by dmodaii** [comment]
@whwnow  我昨天还是好的， 今天就出现和你一样的问题了 ```this socket has been ended by other party了。```  请问你安装的是哪个版本

**Comment by whwnow** [comment]
出问题版本之前的版本都可以的

**Comment by dmodaii** [comment]
@whwnow 对的， 主要是我的居然自动更新了， 坑！现在回退解决了

**Comment by jeffwcx** [comment]
macbook上新版vscode 
如果配置为
```
"runtimeArgs": [
  "run",
  "debug"
]
```
虽然会报错，但是可以调试诶，断点也可以debug @dmodaii

**Comment by Ttou** [comment]
@jeffwcx 亲测有效

**Comment by atian25** [comment]
那有可能是 vscode 对 `--inspect-brk` 支持有问题，去掉后可以调试，但就断点不了启动期。
先这样用吧，暂时没时间搞，有兴趣的 可以研究下，欢迎 PR

**Comment by dmodaii** [comment]
@jeffwcx @Ttou 启动期你们不需要调试吗 
···
--inspect-brk
···

**Comment by xjchenhao** [comment]
尴尬vscode升级了 竟然还是有问题，诶` 先去掉--inspect-brk用着吧

**Comment by wxfred** [comment]
我也遇到这个问题了，--inspect-brk去掉依然有错，但是好在能调试……

**Comment by wenjiasen** [comment]
已经一个多月了，为何还没有任何进展呢？
