### ISSUE TITLE
 "{{ helper.assets.getContext(__context__) }}"

### ISSUE THREAD

**Issue by yangchongduo** [eggjs/egg#2328]
"{{ helper.assets.getContext(__context__) }}" 
使用其他模板 ，无法拿到数据

**Comment by popomore** [comment]
请提供可复现 demo

**Comment by popomore** [comment]
看上一个 issue，应该填 `{{ helper.assets.getContext(context) }}`

**Comment by yangchongduo** [comment]
``` {{ helper.assets.getContext(__context__) | safe }}```

这样才可以拿到

**Comment by popomore** [comment]
对，需要加 safe
