### ISSUE TITLE
请问定时任务如何能够设置成任务间隔么？

### ISSUE THREAD

**Issue by whwnow** [eggjs/egg#2331]
需求：
我想写一个任务，可以一直循环跑下去。执行完当前任务，然后再间隔一定时间执行下一次。一定时间是两次任务中间的间隔，而不是启动时间的间隔。

当前：
使用定时任务，用间隔模式，但是时间短了有可能会有并发，我并不希望这样。我现在的做法是设置一个很长的时间，防止并发。

想请教一下，有什么更好的方案实现这个功能？

**Comment by popomore** [comment]
好像没见过，这就不叫定时任务了

**Comment by whwnow** [comment]
额，名字不重要，这种需求如果用eggjs，有什么好的实现方案么？

**Comment by popomore** [comment]
单进程的话启动就开始执行，然后执行结束自己 setTimeout 继续执行。

如果是集群，你需要一个分布式的定时任务系统

**Comment by whwnow** [comment]
我记得文档里说过。beforeStart里不能跑太耗时的操作，框架会有启动的超时检测。这个问题怎么绕开啊？

**Comment by atian25** [comment]
这种需求要在 schedule 做也不是不可以做，https://github.com/eggjs/egg-schedule/blob/master/app.js#L71

自定义一个 strategy，在上一个任务执行完后，发一个消息给 agent，触发下一条

**Comment by atian25** [comment]
一般的方案还是通过外部的定时系统来触发

**Comment by popomore** [comment]
他那个不是定时，我都不知道有没有这种的东西。redis 好像也是用 crontab 做的？

**Comment by thonatos** [comment]
唔，做过类似的（独立使用），订阅方式，有长连接不用说，没长连接的轮训+延时。

**Comment by atian25** [comment]
外部的系统，只是一个消息下发而已，你看下 egg-schedule 自定义策略那块

**Comment by popomore** [comment]
这个调度系统其实也挺麻烦的，需要等这个任务回执后再设置下次投递时间，并不是简单的 cron，因为任务的时间本身就有长有短。

**Comment by atian25** [comment]
简单的调度可以做：

1. [app.js `task`](https://github.com/eggjs/egg-schedule/blob/master/app.js#L71) 支持下执行完毕后，发一条消息给 agent
2. 自定义策略那边，收到消息后，才触发 setTimeout 启动下一次计时。
3. 局限性就是 worker 还行， all 的话就不要了，算起来麻烦

**Comment by popomore** [comment]
关闭了，延长时间是比较好的选择。

**Comment by whwnow** [comment]
谢谢各位，涨了不少姿势
