### ISSUE TITLE
optimize watcher logic, should ignore node_modules

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#2337]
## Background

currently `egg-development` will watch dirs, if some one add `app/public` and has `app/public/node_modules`, it will suck even with `ignore` config.

## What happen
`egg-development` use `egg-watcher` which use `wt` to monitor file change even.

`wt` will watch dirs, and `ignore` means `ignore to trigger change event`, not `ignore watching dir`.

so if `node_modules` is inside watching dirs, it will suck.

## Optimize

add options `ignoreNodeModules` to `wt`, default to ignore `node_modules`

https://github.com/node-modules/wt/blob/master/index.js#L175

**Comment by atian25** [comment]
it will add too much watcher to node_modules's deeeeeeeep dirs and  throw boring error

**Comment by 215566435** [comment]
@atian25 PRed

**Comment by atian25** [comment]
ci is failed
