### ISSUE TITLE
关于官方socket.io文档的纠错

### ISSUE THREAD

**Issue by jingmingji** [eggjs/egg#2338]
egg官方文档socket.io部分纠错 *实例*部分(p2p聊天)，中间件auth.js里面socket.join(room)放到了nsp.adapter.clients()里面有问题，导致clients返回到前端无法正常携带当前的socket信息，应该把socket.join(room)放到nsp.adapter.clients()外面先执行，亲测如此可以正常返回clients数据。另外clients[id] = query，这个操作和插件本身的操作有冲突，因为socket.join(room)调用成功后，会自动将socketid放入到clients数组里面。如果想添加多余的信息可以通过其他字段来返回，没必要对这个插件会调用的属性进行操作。

**Comment by ngot** [comment]
@jingmingji 提个 PR 来修复一下吧

**Comment by jingmingji** [comment]
@ngot 已经提交了PR，Review一下吧

**Comment by thonatos** [comment]
唔，这应用是使用方式的差异，可能不算错误。

- p2p 场景中，用户只需要知道对方信息就足够了
  - `nsp.adapter.clients(...)` 即可满足需求
  - `clients[id] = query` 是临时的需求变更
- 鉴于上面的原因，“此外” 也就不存在了~

**Comment by jingmingji** [comment]
@thonatos 
- p2p场景中，用户只需要知道对方信息就足够了
新用户加入，推送到之前其他客户端的clients内容，仔细测试会发现，并不是如你所说每次返回的都是对方信息，也会出现返回了自己的信息，而没有返回某个用户的信息，[这个是我测试的截图](https://raw.githubusercontent.com/jingmingji/gallery-for-you/jingmingji-patch-1/20180408184538.png)

**Comment by thonatos** [comment]
@jingmingji 

1. 明白你说的意思，我建议删掉 `clients[id] = query` 或者 调整顺序来减少误解；
2. 截图部分，不清楚你代码，没法判断，贴一下？

> `socket.id` 表单次连接的序号，可变。使用中通常会采用如 **用户Id** 来保持一致性

**Comment by thonatos** [comment]
测试过了，又是一个可能不算问题的问题，🤣，demo 这边我改一下。

**Comment by jingmingji** [comment]
@thonatos 
嗯嗯，你能来修复时最好的。我可能太较真儿了，不过也是想让egg这么好的东东能够更加完善。
你测试的结论意思是：默认的`wsEngine`在chrome下测试有问题，而换成`uwsEngine`就正常了？

**Comment by thonatos** [comment]
@jingmingji 

文档部分我 PR 了；使用 `uws` 解决的是另一个问题： #1848
较真很好哇，😉， 原本示例部分是为了用部分代码演示使用，现在抽成一个可运行项目也好。

**Comment by thonatos** [comment]
#2354

已合并，这边关了
