### ISSUE TITLE
egg-sequelize 的 migrate 怎么写 Associations - 关联？

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#2341]
egg-sequelize 的 migrate 怎么写 Associations - 关联？
希望有个列子，谢谢各位大大

**Comment by duncup** [comment]
migrate 是由 sequelize-cli 执行的，如果 sequelize 本身支持的话，可以按原来写法写。

**Comment by callmesoul** [comment]
@duncup 不知道怎么关联其他模型啊，读取不了其他模型。

**Comment by duncup** [comment]
说真的，翻了下 sequelize 的一份翻译手册，没找到。英文的懒得看了 migrate 我个人没有在用。我都是走Navicat同步上去。写两份感觉略蛋疼。

**Comment by callmesoul** [comment]
@duncup 嗯嗯，我也找过，感觉migrate和model不知道怎么配合使用好。

**Comment by duncup** [comment]
感觉你需要去 sequelize 找答案。先关闭了。
