### ISSUE TITLE
茶叶蛋运行一段时间后,报Cannot find module 'egg-sequelize'

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#2342]
* **Node Version**: 8.4.0
* **Egg Version**: 2.6.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.2
* **Platform**: osx
* **Mini Showcase Repository**:

![1523179801170](https://user-images.githubusercontent.com/7284558/38465773-9d75160a-3b52-11e8-9989-c425ccfcc222.jpg)

**Comment by whxaxes** [comment]
提供一下最小可复现案例

**Comment by duncup** [comment]
暂时没有再发生，也无法重现。怀疑被iCloud同步坑了一手，我再观察下。

**Comment by duncup** [comment]
没有再发生 @whxaxes
多谢帮忙关闭 @atian25
