### ISSUE TITLE
How to ignore plugin's error during bootstrap?

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#2345]
I use a plugin called egg-mongoose, it throws connection error sometimes when the program bootstrap, then the entire app start failed. It throws because the remote mongodb may be dead, how can i ignore these errors and just start my web server? Is there any config I can set in the config file?

here is my config:
`
mongoose: {
    enable: true,
    package: 'egg-mongoose',
    env: ['local', 'prod', 'stage']
  }
`

`
 mongoose: {
      url: "mongodb://xxx"
    }
`

I prefer other services could start normally no matter the mongo is dead or not

**Comment by atian25** [comment]
you could :

- don't config it
- use `app.xx = app.mongoose.createInstance({ ... });` to create at where you want. (recommand at `app.js`)

**Comment by miaojiuchen** [comment]
emmm...  You really mean it? 

I read the egg-mongoose source code, this plugin wait a `heartEvent.emit('connected')` event in beforeStart,  I supposed that if you guys can take full advantage of the retry functionality in mongoose, ignore the connection status in the beforeStart hook and leave it alone

I think this is a general requirement, low priority plugin shouldn't block the main app bootstrap

**Comment by atian25** [comment]
I'm seriously, if you don't want to init connection at startup, then don't provide any config, and init at anytime you want.

**Comment by miaojiuchen** [comment]
@atian25 Oh I got it, use `createInstance` to initialize the singleton property `mongoose`, thanks a lot, my missunderstanding.
