### ISSUE TITLE
Create base service extends from Service

### ISSUE THREAD

**Issue by zhq3k** [eggjs/egg#2346]
* **Node Version**:8.9
* **Egg Version**:2.5
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

I want to create a base service extends from Service, another all services extends from this base service. But will throw error : class extends value undefined is not a constructor or null.

Services must extends Service? cannot extends customer service?

//BaseService.js

import {Service } from 'egg';
export class BaseService extends Service{
    test(){
       return "test";
    }
}

//TestSevice.js
import {BaseService} from './baseservice";

export class TestService extends BaseService{

}

Thanks in advance.

**Comment by popomore** [comment]
`import BaseService from './baseservice";`

**Comment by zhq3k** [comment]
@popomore ,Working fine. Thanks your support.

This is root reason: Recyle reference.

**Comment by atian25** [comment]
put `baseservice` to `lib`

```bash
project_root
|-- app
   |-- serivce
       |-- news.js
|-- config
|-- lib
     |-- base_serivice.js
```
