### ISSUE TITLE
egg-mysql如何建立连接池呢？

### ISSUE THREAD

**Issue by lanbinghang** [eggjs/egg#2348]
egg-mysql作为官方推荐的插件，文档太少了。
目前的问题就是：
按照官方教程写一遍api服务，发布到linux服务器上，发现，当过一段时间前端请求api时，数据库的连接时间太久了，10s左右的样子。所以这个问题想请教下如何解决呢？在app.js里写个连接数据库还是怎么的？要是能够提供点思路也很感激啦。

**Comment by duncup** [comment]
egg-mysql 是 https://github.com/ali-sdk/ali-rds 的封装，看了下 https://github.com/ali-sdk/ali-rds 的文档，是支持连接池的，而且默认也建立了。

**Comment by popomore** [comment]
其实就是 mysql 库，一个 client 一个 pool。不太明白连接太久是什么意思

**Comment by lanbinghang** [comment]
@popomore 不好意思，可能表述有误，连接太久就是请求api的响应时间太久了。我对比了下，使用c#和egg这个框架，请求同一个数据同一张表的数据，发现egg第一次请求时间太久了，所以我觉得可能是我写的代码有问题。目前我按照官方教程，egg-mysql在config内配置了，连接池如果默认配置了，那为何过个十分钟再去请求api时，还是很慢呢？目前部署在linux服务器上，但app.js agent.js没有写东西的。我现在比较迫切知道自己问题出在哪里

**Comment by lanbinghang** [comment]
@duncup 如果默认建立了，那么是否可以这么理解，当应用启动之后，连接池也存在了，那么应该不会过一段时间自己断开连接的，那为什么过10分钟再去请求api，就是会变慢呢，请求过后又恢复正常速度了。

**Comment by duncup** [comment]
个人感觉有没有可能是服务器侧断开了？换言之链接本质上已经断开了，但没有移除，变慢是在等超时？纯属猜测。

**Comment by TyrSnow** [comment]
按照我的理解，连接池并不一定会始终维护可用的连接吧，如果池子里的连接都超时关掉了，没有新的连接请求的话连接池也许不会主动建立空闲的连接

**Comment by duncup** [comment]
也有这种可能吧

**Comment by TyrSnow** [comment]
研究了一下源码，https://github.com/mysqljs/mysql/blob/master/lib/Pool.js，81行开始，貌似是当你试图从连接池里拿连接的时候要先ping一下，连接不可用的时候destroy连接，然后进队列排队重新拿，所以，如果长时间没连接的话，会把所有队列里的connect依次ping一遍然后依次destroy，最后才会给你一个新的连接……

**Comment by duncup** [comment]
@TyrSnow 冒昧的帮你在链接后加了个空格。

**Comment by dead-horse** [comment]
可以去 https://github.com/mysqljs/mysql 咨询
