### ISSUE TITLE
在service里extend之后，使用super(),报错Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by sourth-rain** [eggjs/egg#2349]
'use strict';

const Service = require('egg').Service;
const util = require('../../../lib/util');
const User = util.loadModel('user');

class UsersService extends Service {
    constructor(params){
        super();
        this.model = params.model;
        this.options = params.options;
    }
    async create() {
        let ctx = this.ctx;
        let users = await User.find(this.options);
        return users;
    }

}

module.exports = UsersService;

继承的service没有app么，应该怎么加进去呢。如果不用构造函数，又达不到封装orm的目的了，麻烦回答下，谢谢了

**Comment by atian25** [comment]
没看懂，你是要自己初始化 Service 么？

**Comment by sourth-rain** [comment]
打算基于model，在service封装orm，就是我在controller调用这个文件的create方法的时候就报错。问题就出在super那里

**Comment by atian25** [comment]
1. 首先，不要自己 create，看下 loader 的机制，你可以直接定义一个 ctx.orm 的规范，用 loadToContext 来实现即可
2. 你不能放到 Service 下，因为 Service 是已有规范了，轮不到你来初始化，自动 loader 的时候你没传递 app 进去

**Comment by popomore** [comment]
实例化参数要透传

**Comment by popomore** [comment]
可以先看完文档，如果自己造的话可以不用基类。f

**Comment by sourth-rain** [comment]
但是为什么我去掉construct那部分又正常了呢，同样是使用了基类的

**Comment by sourth-rain** [comment]
对了，现在 egg-mogoose和egg-sequelize还没办法共存是么，就是model里面分级目录放各自的model文件

**Comment by popomore** [comment]
去掉就是基类的 constructor
