### ISSUE TITLE
egg-mysql 等需要实现 tracelog 日志打印的，都需要触发约定的日志事件

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#235]
## 流程

```bash
    init options
        |
        V
    emit `request` event
        |
        V
    send request and receive response
        |
        V
    emit `response` event
        |
        V
       end
```

## `request` 事件：发生在网络操作发生之前

```js
app.httpclient.on('request', req => {
  req.options 请求参数等
  req.ctx 是发起这次请求的当前上下文

  // 可以在这里设置一些 trace headers，方便全链路跟踪
});
```

mysql 就可以类似实现了

```js
app.mysql.on('request', req => {
  req.sql
  req.ctx 是发起这次请求的当前上下文
});
```

## `response` 事件：发生在网络操作结束之后

类似 httpclient 那样，请求结束之后会触发一个 response 事件，这样外部就可以订阅这个事件打印日志。

```js
// tracelog
app.httpclient.on('response', res => {
  res.status
  res.ctx 是发起这次请求的当前上下文
  res.req 对应的 req 对象，即 request 事件里面那个 req
});
```

mysql 就可以类似实现了

```js
app.mysql.on('response', res => {
  res.sql
  res.ctx 是发起这次请求的当前上下文
  res.req 对应的 req 对象，即 request 事件里面那个 req
});
```

## 进一步统一

将 app.httpclient 访问的时候，也动态生成一个 context_httpclient，只是 ctx 是匿名 ctx。
这样 app 和 ctx 访问 httpclient 和 mysql 都是行为一致了，tracelog 也能统一收集。

**Comment by gxcsoccer** [comment]
光靠 `response` 可能不完全满足需求，比如 response timeout, error 等场景，

**Comment by fengmk2** [comment]
response 里面包含所有的 meta 信息的，如果是 error，也是 response 里面的一个属性，可以看看 urllib 的实现。

**Comment by popomore** [comment]
前后都加事件吧，像 instrument 这种也可以使用 https://github.com/eggjs/egg/issues/280

**Comment by fengmk2** [comment]
@popomore request 事件描述加了

**Comment by popomore** [comment]
好，这样的话其实 service 之类的都可以加。

**Comment by fengmk2** [comment]
@popomore 还不太好加，需要一个全局单例才能支持，ctx scope 下的对象实例搞不定。

**Comment by popomore** [comment]
tracelog 也可以单独加篇文章。

**Comment by fengmk2** [comment]
我先给 egg-mysql 改改看

**Comment by popomore** [comment]
ctx 级别的就不好加，比如 view，要不用 app 的事件吧，全局监听。

**Comment by fengmk2** [comment]
ctx 的 client 不需要加 event 接口吧

**Comment by popomore** [comment]
不一定是 client，比如 proxy 是在 ctx 实例化的，这个就不好加了

**Comment by fengmk2** [comment]
@popomore proxy 跟这种没有关联吧

**Comment by popomore** [comment]
如果想 trace service 的调用呢？

**Comment by fengmk2** [comment]
Service 本身没有 io 的，trace 它没意义吧。

**Comment by popomore** [comment]
我只是举个例子，他本身没 io，但调用的可能又 io。

**Comment by fengmk2** [comment]
很麻烦的，不可能对 Service 类的每个方法都入注 hook 的，如果有需求，service 自己调用 tracelog 接口来打印吧

**Comment by jtyjty99999** [comment]
@fengmk2 现在有例子吗，还是要等tracelog实现

**Comment by fengmk2** [comment]
我写一个 @jtyjty99999 httpclient 的例子吧

**Comment by fengmk2** [comment]
@jtyjty99999 https://github.com/eggjs/egg/pull/313 httpclient tracer 的示例

**Comment by popomore** [comment]
@fengmk2 这个就别在开源写了吧？

**Comment by fengmk2** [comment]
嗯，只需要插件触发这些事件即可
