### ISSUE TITLE
yarn start 启动报错

### ISSUE THREAD

**Issue by SuJunming** [eggjs/egg#2350]
node:8.9.4
egg-init:1.13.0

yarn
yarn start
之后出现以下报错

**Comment by SuJunming** [comment]
<img width="1299" alt="qq20180409-172314 2x" src="https://user-images.githubusercontent.com/13981432/38490299-4a4972f4-3c1b-11e8-99fe-1beae028d8b1.png">

**Comment by SuJunming** [comment]
<img width="1311" alt="qq20180409-172424 2x" src="https://user-images.githubusercontent.com/13981432/38490310-54b16ecc-3c1b-11e8-9cb8-ec9d72e205c2.png">

**Comment by atian25** [comment]
报错不是写很清楚了么，你引入的 Controller 不存在。

另外，重新安装下依赖，不要锁版本（是的，我说的就是 yarn 这货）

**Comment by SuJunming** [comment]
我没引入controller,代码无任何改动。

**Comment by atian25** [comment]
删除依赖重新安装下看看，不要锁版本。

`rm -rf node-modules && npm i`

**Comment by SuJunming** [comment]
谢谢，删除node-modules后，重新 npm install解决了
不过貌似cnpm installl 和yarn同样的问题
可能是需要多次去install

**Comment by atian25** [comment]
跟多次没关系，就是不要锁版本，遇到问题先重新安装依赖看看。

**Comment by SuJunming** [comment]
前面用yarn安装过多次，没解决，锁版本真坑。

**Comment by atian25** [comment]
永远永远不要锁版本。

**Comment by SuJunming** [comment]
😁谢谢

**Comment by fengmk2** [comment]
@atian25 我们的错误提示也应该改善一下，提示一下 controller 的名称也好

![image](https://user-images.githubusercontent.com/156269/38491274-0086a7ba-3c1e-11e8-98be-94e68c757bbc.png)

**Comment by SuJunming** [comment]
第一眼看的先是红的报错，再接着是这个，不是太明显，容易忽略。

**Comment by atian25** [comment]
@fengmk2 看了下，是个问题，当前只有 `router.get('/', 'home.index')` 字符串格式才会提示

**Comment by atian25** [comment]
`router.get('/', controller.home.index1);` 这样的，传递进去就是 undefined 了，无法知道路径，除非 Controller 这里做个 Proxy 来监控 unknown prop

**Comment by atian25** [comment]
@popomore 除非用 Proxy 黑魔法

**Comment by SuJunming** [comment]
换一种思路，指出他在哪里报错的这样不是也行嘛？不一定非得暴露出文件名。

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/38493206-f0ed5a96-3c23-11e8-870a-340c4df19eaa.png)

堆栈里面本来就指出了啊

**Comment by atian25** [comment]
记起来了，之前我想优化这里的，没什么好办法，然后看到堆栈有，就懒得搞了。

**Comment by SuJunming** [comment]
在具体一点，比如: (...router.json:1:10)
router.post('/api/getUserInfo', controller.userInfo.index)
controller undefined

**Comment by atian25** [comment]
这属于堆栈定制了，不考虑了。正常的研发应该都会看堆栈。

**Comment by fengmk2** [comment]
哦，对哦，有堆栈，忽略我的提议。

**Comment by muzi131313** [comment]
感觉提示有点误导，`controller not exsits`，然后跑去controller中去找问题了，要是改成`you have configed an unexisted router`会不会好一点

**Comment by WangShuXian6** [comment]
egg 的很多报错语义都无法理解！有时候猜都猜不到！
