### ISSUE TITLE
请问如何获取单元测试的名字？或者如何用单元测试生成文档？

### ISSUE THREAD

**Issue by YeungKC** [eggjs/egg#2351]
我想用单元测试来生成文档，但是不知道如何获取单元测试名字…因为有些判断可能可以直接通过单元测试的约定名字来判断。

或者，egg 有什么方案用单元测试生成 API 文档吗？

**Comment by duncup** [comment]
https://cnodejs.org/topic/59295623d371b6372a8afeb3

**Comment by YeungKC** [comment]
@duncup 感谢，我看过类似的设计，但是我觉得更好的方案是约束的单元测试名字来判断，就不用手工输入 title group 等相关参数，将这些参数传到 ctx，然后中间键去整理这些和入参出参等元素。
那之后就可以将本需要写的单元测试名字，顺便变成文档~

**Comment by YeungKC** [comment]
@popomore 你好…我不是想要网上的一些单元测试生成文档方案，我想要获取单元测试的名字…………请可否不要关闭本 issue？

**Comment by popomore** [comment]
自己写个工具吧，没有适合自己的就自己撸，为何处处伸手。

**Comment by popomore** [comment]
回答下题主的问题就是官方没有。

**Comment by atian25** [comment]
```js
  describe('some test', function()  {
    console.log(this);
  });
```

如果是箭头函数，就获取不到。

其实你可以自己提供一个函数来做的，对 `describe` 包裹下就好了。

**Comment by YeungKC** [comment]
@atian25 感谢，在中午睡醒的时候我 debug 跑也发现 this 有一个 test，test 里面有 title，但是可能脑抽了…一直想不到T_T。
@popomore 由于我使用 egg 之前也是通过类似的方式去打做单元测试，生成文档，所以看了一下代码确信 egg 也是能做到，只是我找不到方法如何获取单元测试 title，所以来问。

**Comment by atian25** [comment]
其实跟 egg 关系不大，就是 mocha 而已，它怎么样就怎么样。

不一定需要获取名字的，你可以看下 mocha 的 reportor 这块，自定义一个应该就可以了。

**Comment by YeungKC** [comment]
@atian25 感谢，虽然我这边已经达到我的目的，不过我还是会去了解这一块的，谢谢你
