### ISSUE TITLE
passport local有demo么？

### ISSUE THREAD

**Issue by shenqidebaozi** [eggjs/egg#2352]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by thonatos** [comment]
> [https://github.com/cnodejs/egg-cnode](https://github.com/cnodejs/egg-cnode)

**Comment by shenqidebaozi** [comment]
爱你呦！
