### ISSUE TITLE
无法使用 egg-passport-local 进行鉴权

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2355]
* **Node Version**: 8.9.1
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-passport-local
* **Plugin Version**: 1.2.1
* **Platform**: MacOS
* **Mini Showcase Repository**:  [https://github.com/JZLeung/egg-issue-demo](https://github.com/JZLeung/egg-issue-demo)

使用了 `egg-passport-local` 的插件，在 [`app.js`](https://github.com/JZLeung/egg-issue-demo/blob/master/app.js) 中配置了相应的设置，但是却无法进入 passport 的 `use` `verify` 函数，因而无法进行相关操作。

**Comment by thonatos** [comment]
先看看下面的示例: [egg-cnode](https://github.com/cnodejs/egg-cnode)

**Comment by JZLeung** [comment]
@thonatos 
看了，还是不行，我另一个 demo，一模一样的代码，却可以。

**Comment by thonatos** [comment]
@JZLeung 

这样的话，建议你先检查代码，发现问题的过程也是学习过程，💪

**Comment by JZLeung** [comment]
终于找到原因了：插件默认的表单提交的字段是 `name` 和 `pass`， 如果实际项目中并非这俩字段的话，需要在 `app.js` 中自行配置：
```js
app.passport.use(new LocalStrategy({
    // 配置你的表单字段
    usernameField: 'loginname',
    passwordField: 'password',
    passReqToCallback: true,
  }, (req, username, password, done) => {
    // format user
    const user = {
      provider: 'local',
      username,
      password,
    };
    console.log('%s %s get user: %j', req.method, req.url, user);
    app.passport.doVerify(req, user, done);
  }));
```
或者在 `config.js` 中配置：
```js
module.exports = appInfo => {
  config.passportLocal = {
    usernameField: 'name',
    passwordField: 'pass',
  };
};
```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-passport-local#configuration

文档有写的
