### ISSUE TITLE
多进程的情况 mysql 的连接池是共享的么

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#2356]
因为项目很大，用的数据库很多，达到了几百个。

每个线程的mysql 的连接池 是共享的么。如果不是共享的 话，要启动上万个 链接每个服务器上面。

感觉会很有压力对数据库。

**Comment by popomore** [comment]
Node 是单线程，一个 client 会有一个连接池，不清楚你说的几百个数据库是什么意思？

**Comment by buzai** [comment]
@popomore 恩，因为这个后台需要链接许多的数据库。那么每个 cluster 就要创建这些这些数据库的实例，这样每个 cluster 就有好多数据库链接。一台服务器跑多个 cluster， 每个cluster 就要自己创建一堆的链接。这样 服务器一多连接数就太多了。

**Comment by dead-horse** [comment]
是的，每个 worker 进程都会独立创建连接，所以一些以连接数为重要资源的服务，可以考虑通过 agent 进程来转发以降低资源消耗，但是 mysql 这类不合适，还是只能放在 worker 进程中。

**Comment by wanghsinche** [comment]
对于这种问题，是不是用教程说到的这种 【多进程研发模式增强
】 https://eggjs.org/zh-cn/advanced/cluster-client.html  比较合适呢？

**Comment by buzai** [comment]
@waitingsong 我最后运行了一个单独的进程执行数据库方法，每个服务器有一个进程专门执行sql并且进行了一些统计。但是会有一些性能损失，而且这个进程不能挂，等于有一个热点问题。但是已经是没办法的办法了
