### ISSUE TITLE
使用Typescript开发，在路由上挂载中间件，tslint会提示：Property 'middlewareName' does not exist on type 'Middleware<Context>[]

### ISSUE THREAD

**Issue by bluehymn** [eggjs/egg#2358]
使用Typescript开发，在路由上挂载中间件，tslint会提示Property 'middlewareName' does not exist on type 'Middleware<Context>[]

module.exports = app => { 
    const middlewareName= app.middleware.middlewareName();  
    app.router.get('/', middlewareName, app.controller.handler);
};

**Comment by whxaxes** [comment]
嗯，目前由于 Application 是直接 extend KoaApplication 的，其中的 middleware 类型是继承自 KoaApplication，所以类型推断会出问题，暂时先 `as any` 吧，这个正在想办法解

```typescript
const middleware = app.middleware as any;
const middlewareName= app.middleware.middlewareName();
app.router.get('/', middlewareName, app.controller.handler);
```

**Comment by bluehymn** [comment]
@whxaxes 
嗯。明白了，谢谢回复
