### ISSUE TITLE
egg有一键生成controller或service的脚手架吗

### ISSUE THREAD

**Issue by Webjiacheng** [eggjs/egg#2361]
由于控制器和服务需要频繁的新建，新建后又要手动修改类名，所以想问下有木有在egg-init初始化后一键生成controller或service的神操作

**Comment by atian25** [comment]
目前没精力做，自己写 snippet 或 yo 骨架吧。欢迎社区贡献。

**Comment by wangxiangyao** [comment]
借楼说一句，首页文档，少个run

![image](https://user-images.githubusercontent.com/23569474/38549428-9139a852-3ce6-11e8-9941-593eb302950c.png)

今天刚开始研究Egg，要做一个公司的后台管理系统。之前写node都是自己拿koa2直接写的，基本的组织都有，但是配置这一块一直都是拷贝来拷贝去的。看了Egg就很心动。

打算把之前写的GraphQL整个搬过来，然后整合一下前台项目，后台项目，都用Egg做中间层。

因为经历的项目还不多，目前项目也不大，对复用和扩展这一块怎么设计思路还很模糊。刚好看看先行者前辈们的想法。真的很棒

**Comment by thonatos** [comment]
@waitingsong 

这里你得看下文档喽：https://docs.npmjs.com/cli/test

```
  npm test [-- <args>]

  aliases: t, tst
```

> This runs a package's "test" script, if one was provided.

**Comment by waitingsong** [comment]
@thonatos  没看懂哇

**Comment by waitingsong** [comment]
另， generator-eggjs 这个东东只能生成项目框架。能像 ng-cli 那样生成控制器、服务么

**Comment by thonatos** [comment]
@Webjiacheng 

当然可以了，因为这个优先级不高所以没加，有需要的话动手撸吧，加了 PR 呗

**Comment by thonatos** [comment]
@Webjiacheng 

如果使用 vscode 可以考虑这个插件：[vscode-eggjs](https://github.com/eggjs/vscode-eggjs)

**Comment by wangxiangyao** [comment]
@thonatos  学到了，我还以为少了呢!
