### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by hrh94** [eggjs/egg#2364]
想要实现的步骤：
1.react通过 input type=‘file’ 上传data.json文件到egg
2.egg获取并解析data.json文件里面的数据，将解析出来的数据写入到数据库

以下是部分代码：
前端：
PrivilegeMenuPage.js
```
    let fileObj = document.querySelector('input[type=file]').files[0];
    let formData = new FormData();
    formData.append('file', fileObj);
    let { data } = await this.props.dispatch({
      type: 'privilegeMenus/upload',
      data: formData,
    });
    if (data.code === 1) {
      message.success(data.msg, 2);
    }
```
privilegeMenus.js（service）
```
export function upload({ data }) {
  return axios.post('/operate/privileges/menu/upload', data, { headers: { 'Content-Type': 'multipart/form-data' } });
}
```

后端：
controller.js：
```
  async upload() {
    const stream = await this.ctx.getFileStream();
    this.ctx.body = await this.service.upload(stream);
  }
```
service.js：
```
  async upload(stream) {
    console.log(stream);
    return { code: 1, msg: '权限菜单导入成功' };
  }
```

问题：
上传data.json时，报错：
2018-04-10 16:31:08,331 WARN 1204 [-/192.168.1.99/-/10ms POST /operate/privileges/menu/upload] nodejs.BadRequestError: Content-Type must be multipart/*

**Comment by atian25** [comment]
post json 的话直接 `ctx.request.body` 不就完了。。。 `this.ctx.getFileStream();` 是文件上传。

多看文档

**Comment by hrh94** [comment]
我的数据是存在一个data.json文件里面，我就是想上传data.json文件，然后现在上传data.json文件的时候出错了

**Comment by TyrSnow** [comment]
报错信息既然说头不对，就看下f12里面请求的content-type是真的设置成功了吗

**Comment by hrh94** [comment]
不好意思，已经解决了，我被误导了，其实并不是content-type的错误

**Comment by stevenluoxiaohua** [comment]
我也遇到了，怎么解决的 @hrh94

**Comment by plunjoin** [comment]
> 我也遇到了，怎么解决的 @hrh94

我也遇到了，哭o(╥﹏╥)o
