### ISSUE TITLE
线上部署，静态资源被缓存

### ISSUE THREAD

**Issue by csm0912** [eggjs/egg#2367]
* **Node Version**:6.6.0
* **Egg Version**:1.9.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

config.prod.js文件：
module.exports = appInfo => {
    return {
        static : {
            prefix: '/public/',
            dir: path.join(appInfo.baseDir, '/dist'),
            maxAge: 0,
            buffer: false
        },
        view : {
            root: path.join(appInfo.baseDir, '/dist/view')
        }
    }
}

渲染模版用的ejs，js模版引擎用的arttemplate，tmod编译，部署上线后，arttemplate模版获取不到最新代码。
开发环境下，使用npm run prod启动测试，不存在缓存。
线上环境和开发环境启动npm run prod命令有什么区别，线上环境为什么会导致缓存呢？cdn清除了，缓存仍然存在。

**Comment by atian25** [comment]
你指的是什么东西的缓存

**Comment by csm0912** [comment]
arttemplate模版被缓存了，模版改变后重新编译了，但是浏览器中获取到的还是改变前的内容。css、image和js文件加了版本后，所以不存在缓存

**Comment by atian25** [comment]
在 public 下的都会被强缓存，跟 maxAge 配置没关系。

- https://github.com/eggjs/egg-static
- https://github.com/koajs/static-cache/blob/master/index.js

**Comment by popomore** [comment]
你如果路径不变，浏览器缓存是必然的，推荐 https://zhuanlan.zhihu.com/p/34874264

**Comment by csm0912** [comment]
有点不明白，开发环境下，静态资源也是在public下，为什么浏览器没有缓存

**Comment by JacksonTian** [comment]
线上如果不缓存，性能肯定很差。

**Comment by popomore** [comment]
这个还是自学一下吧。
