### ISSUE TITLE
egg-websocket跟egg-socket.io的区别

### ISSUE THREAD

**Issue by liuzhenji** [eggjs/egg#2369]
看到 @atian25 有一个egg-websocket库，然后还有一个 @ngot 的egg-socket.io库，所以有个疑问：
egg-socket.io是建立在socket.io项目上的，那egg-websocket是原生的websocket吗？
他们俩有什么区别吗？

**Comment by atian25** [comment]
egg-websocket 只是一个空的占位的库

**Comment by Azard** [comment]
egg-websocket 还有后续计划吗

**Comment by Azard** [comment]
@atian25 我觉得这个需求挺基础的，得搞一下

**Comment by ngot** [comment]
@Azard PR is welcome.
