### ISSUE TITLE
egg-bin 增加 --framework 的参数

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#237]
使用这个参数可以从 node_modules 找到框架，不用通过 customEgg 指定了。

**Comment by fengmk2** [comment]
做起

**Comment by fengmk2** [comment]
`egg-bin test --framework=${framework}` 会设置 `EGG_FRAMEWORK=${PWD}/node_modules/${framework}` ，egg-bin，egg-mock 都需要修改才能支持。

**Comment by fengmk2** [comment]
`"start": "egg-script start --framework=${framework}"`

**Comment by fengmk2** [comment]
或者在 package.json 里面指定好了。

```js
{
  "egg": {
    "framework": "${framework}"
  }
}
```
