### ISSUE TITLE
大家觉得用GraphQL替换Controller层怎么样？

### ISSUE THREAD

**Issue by wangxiangyao** [eggjs/egg#2370]
仔细想象，我觉得，从处理的内容来看，这俩其实差不多，都是接收参数，调用业务处理，然后返回数据。

GraphQL优势在于，从前端到服务不需要api约束。也就是，服务端专注于数据，而如何使用数据，则是前端的事情。就像一盒子的颜料，我想要用哪个画画，就去拿哪个，而不是我的爸妈管着盒子，我和爸妈要有约定，用哪个要告诉他们，然后他们再拿给我。

这样才是一种更自然的模式嘛。

基于这一点，需要的数据都精准定位，不会造成流量上的浪费。

我看到Egg也有GraphQL的插件，[egg-graphql](https://github.com/eggjs/egg-graphql)，配合[graphql-tools](https://github.com/apollographql/graphql-tools)，[graphql-voyager](https://github.com/APIs-guru/graphql-voyager)这样的工具，写起来也很爽快

不知道大家怎么看？

（eggjs.org怎么打不开了？吃一半的肉夹馍被抢走了~~）

**Comment by duncup** [comment]
GraphQL 不是银弹，从业务选型角度来说就不适合替换。并不是任何时候任何项目都会选择 GraphQL。

**Comment by wangxiangyao** [comment]
从业务选型角度，可以具体说说么？

说起来，GraphQL我目前只做了一个内容管理的业务。其他的业务没怎么思考过。

**Comment by duncup** [comment]
选型不光看业务类型，有时候也需要考虑团队。最简单的情况，当团队成员都是RestAPI经验，且完全没有用过GraphQL时，是不可能选GraphQL的。需要搞open API的，至少个人看，也不适合用 GraphQL 。
如果你非常希望用GraphQL替换Controller，你可以考虑自己基于egg封装个上层框架。

**Comment by popomore** [comment]
难度在于建模，业务扩大后如何保证模型按预想的发展。如果这块发展不好就会出现各种重复的模型，对前端也很痛苦。

**Comment by sunheartGH** [comment]
能不能做到混合使用？通过配置Controller到Graphql的resolves来实现。

**Comment by wangxiangyao** [comment]
我觉得建模的难度问题，是一个一直存在的问题。引入GraphQL后，建模的难度问题对前端的影响就是，相对于RestAPI形式，现在前端也要维护一套模型系统。

但是对于GraphQL的模型，我觉得并不是一个完整建模过程的产出。仅仅只是概念到逻辑之间的产物，包含一些业务变量，而其他的存储过程，主外键，表结构，约束都不用关心。

像这样针对业务抽象出的模型，包含各个实体，我觉得在维护方面，并没有增加难度。或者说，这种业务模型的维护难度是一直存在的，引入GraphQL并没有让难度增加。

不过从业务角度，学习成本上来看，确实有时候也不是很好。

写这个服务时候试试抽象一个框架。

混合使用等于就是RestAPI和GraphQL混用，当然也可以了，其实我对于GraphQL的Mutations就不是很爽，之前写的这部分有的就还是RestAPI形式。

**Comment by dead-horse** [comment]
讨论请到 cnode 社区等地方进行
