### ISSUE TITLE
issue 机器人

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#2372]
使用 https://github.com/eggjs/ant-bot 来帮助我们处理 issue，现在已经部署，但是需要根据我们的需求修改规则，可以在这个 issue 讨论下。

ant-design 的规则如下

https://github.com/eggjs/ant-bot/tree/master/app/actions

感谢 @yesmeck

**Comment by dead-horse** [comment]
好高级，测试一下翻译

**Comment by popomore** [comment]
看规则是创建 issue 的时候

https://github.com/eggjs/ant-bot/blob/master/app/actions/replyTranslate.js

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/33#issuecomment-380485910 另一个例子

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/2374

**Comment by popomore** [comment]
通过静态页面创建 issue https://xuexb.github.io/github-bot/create-issue.html

**Comment by thonatos** [comment]
666

**Comment by 215566435** [comment]
这玩意厉害了

**Comment by okoala** [comment]
行云流水~

**Comment by atian25** [comment]
## Rule 1

if `title` or `body` contains chinese, should: 
- tell user to use english
- auto transalate to  english
- redirect to cnode if they don't familiar with english

**Comment by popomore** [comment]
if tag is published, update release from History.md

**Comment by atian25** [comment]
这个后面改为 GitHub Action 来做吧。 #3398
