### ISSUE TITLE
egg测试的时候可以正常打印日志，发布版本的时候打印不了日志

### ISSUE THREAD

**Issue by entrehuihui** [eggjs/egg#2377]
egg测试的时候可以正常打印日志，发布版本的时候打印不了日志
Node Version: 9.9
Egg Version:
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
正式环境默认会关闭 console 的 info 级别的，配置下 consoleLevel 即可
