### ISSUE TITLE
使用egg-assets-view渲染Vue时,devServer配置问题

### ISSUE THREAD

**Issue by sansroman** [eggjs/egg#2378]
* **Node Version**:
v9.11.1
* **Egg Version**:
2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
Linux

使用vue serve启动开发服务器时出现问题，应该是子进程执行目录不对，有什么配置可以修改运行这个命令的目录么

**Comment by sansroman** [comment]
```javascript
// app/config/config.default.js
'use strict';
const path = require('path');
module.exports = appInfo => {
  const config = exports = {
    sequelize: {
      dialect: 'mysql', // support: mysql, mariadb, postgres, mssql
      database: 'elearning',
      host: 'localhost',
      port: '3306',
      username: 'elearning',
      password: '123456',
    },
    io: {
      init: { }, // passed to engine.io
      namespace: {
        '/': {
          connectionMiddleware: [ 'auth' ],
          packetMiddleware: [],
        },
        '/chat': {
          connectionMiddleware: [],
          packetMiddleware: [],
        },
      },
    },
    view:{
      root: path.join(appInfo.baseDir, 'app/assets/src'),
      mapping: {
        '.js': 'assets',
      },
    },
    assets:{
      publicPath: '/public/',
      devServer: {
        debug: false,
        command: 'vue serve',
        port: 8000,
        env: {
          BROWSER: 'none',
          ESLINT: 'none',
          SOCKET_SERVER: 'http://127.0.0.1:8080',
          PUBLIC_PATH: 'http://127.0.0.1:8080',
        },
      },
    }
  };

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1523509508086_5913';

  // add your config here
  config.middleware = [];

  return config;


};




```
错误信息如下:
>  2018-04-13 12:57:43,249 ERROR 11604 nodejs.ENOENTError: spawn vue ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ENOENT'
errno: 'ENOENT'
syscall: 'spawn vue'
path: 'vue'
spawnargs: [ 'serve' ]
name: 'ENOENTError'
pid: 11604
hostname: Tboevil

**Comment by popomore** [comment]
Maybe it’s same as https://github.com/eggjs/egg/issues/2384, it doesn’t work on Windows now.

**Comment by popomore** [comment]
https://github.com/eggjs/egg-view-assets/pull/13

**Comment by popomore** [comment]
egg-view-assets has use cross-spawn instead of spawn, you can have a try.
