### ISSUE TITLE
Deploy single minified js file to prod?

### ISSUE THREAD

**Issue by cemremengu** [eggjs/egg#2379]
Is there a built-in way to deploy a single minified js file to prod env with all dependencies included? `Deploy` tutorial does not contain any information about this.

**Comment by popomore** [comment]
Have you check egg-view-assets?

**Comment by cemremengu** [comment]
I am only using `egg` as a backend API service so do not need frontend minification.

**Comment by atian25** [comment]
try http://enclose.io/

**Comment by cemremengu** [comment]
Thanks! I will check it out
