### ISSUE TITLE
http client 增加抓包介绍

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#238]
https://github.com/eggjs/egg/blob/master/docs/source/zh-cn/core/httpclient.md

增加抓包介绍

**Comment by fengmk2** [comment]
抓什么包？

**Comment by atian25** [comment]
就是对 httpclient 服务端请求进行抓包，方便调试。内网有个插件 ucweb/egg-proxyagent。

发自我的 iPhone

**Comment by atian25** [comment]
close by https://github.com/eggjs/egg/pull/265
