### ISSUE TITLE
请问有好点的项目demo吗 想系统学习一下

### ISSUE THREAD

**Issue by Messilimeng** [eggjs/egg#2380]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
- https://github.com/cnodejs/egg-cnode
- https://github.com/eggjs/awesome-egg

@okoala 把 cnode 的加到 awesome 吧
