### ISSUE TITLE
schedule 不识别 ts 文件

### ISSUE THREAD

**Issue by Rockcookies** [eggjs/egg#2383]
使用官方示例 hackernews-async-ts-di 在 schedule 新建文件

```ts
// app/schedule/test.ts

exports.schedule = {
  interval: '3s',
  type: 'worker'
};

exports.task = async () => {
  console.log('executed');
};
```
DEV模式下没有执行该定时器。

Node: 8.9.0
Egg: 2.6.0
Platform: windows10

**Comment by whxaxes** [comment]
这个确实是个 bug，egg-schedule 中的 loader 没有去加载 ts ，我提个 PR 修复一下

**Comment by atian25** [comment]
@whxaxes 
https://github.com/eggjs/egg-schedule/blob/master/lib/load_schedule.js

are you sure? I don't see any filename extension filter.

**Comment by whxaxes** [comment]
@atian25  https://github.com/eggjs/egg-schedule/blob/master/lib/load_schedule.js#L11  create Loader instance without typescript option

**Comment by tong3jie** [comment]
@atian25 TS模式下使用egg-redis，提示[ts] 类型“Application”上不存在属性“redis”。

**Comment by atian25** [comment]
@tong3jie just write `d.ts` and PR to `egg-redis`

**Comment by tong3jie** [comment]
@atian25 有木有其他插件已经写好的例子？

**Comment by duncup** [comment]
@tong3jie you can see egg-sequelize

**Comment by tong3jie** [comment]
@atian25 schedule不能执行TS的问题有计划修复吗？

**Comment by atian25** [comment]
@tong3jie just after https://github.com/eggjs/egg-core/pull/158 merged

**Comment by atian25** [comment]
@tong3jie reinstall deps and retry.

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules
$ rm -rf package-lock.json
$ rm -rf yarn.lock
$ npm i --no-package-lock
```

**Comment by tong3jie** [comment]
ok,thanks

**Comment by whxaxes** [comment]
@tong3jie  你先这么写

```typescript
export default {
  schedule: {
    interval: '2s',
    type: 'all',
  },
  async task() {
    console.info('>>>>>>>>>>>>>>> lalalala');
  },
};
```

egg 的 d.ts 中没有声明 Subscription

**Comment by yanguoyu** [comment]
这个问题解决了吗？我也碰到这个问题了。

**Comment by dengnan123** [comment]
老哥，你这最后怎么弄的，我也遇到这个问题了
