### ISSUE TITLE
大型项目router写法的疑问？

### ISSUE THREAD

**Issue by kylehuangfff** [eggjs/egg#2386]
背景：
最近公司一个大型项目，准备基于eggjs做前后端分离，项目包含超过20多个模块，每个模块下面还有数十个子模块，总的接口数量超过500个。

问题：
根据官方文档，以及像CNode 的egg版，都把需要用到的路由地址，写在router里面，那么如果有几百个url地址，岂不是要注册几百个路由呢？
更严重的是，极端情况下，某些用户请求，需要经过几百次路径检测，才能匹配到相应的控制器。

我的解决方法：
1、router里面只有类似这样一行路由 
router.get(/^\/(.*?)$/, controller.base.entry);

2、创建一个BaseController，继承egg Controller。在BaseController里再做路径处理，进行请求分发。

3、BaseController以外的其他控制器，不继承egg Controller。仅export数个方法。

// app/controller/home.js
module.exports = {
    async index() {
    }
}

当访问路径为 '/home/index'时，由BaseController主动进行调用，controller.home.index.call(this)，传入BaseController所持有的this对象。

疑问：
1、这样的写法有没有潜在的问题？
2、官方是否有更好的解决方案？

谢谢！

**Comment by dead-horse** [comment]
> 创建一个BaseController，继承egg Controller。在BaseController里再做路径处理，进行请求分发。

你确定不是同样自己实现了一个 router？现在 egg 的 router 性能足够了，不用纠结。

**Comment by atian25** [comment]
1. 你这种写法，不就是重新实现了一个 koa-router，意义何在？
2. 如果你只是解决一大堆东西写在一个文件，那就自己分文件 require 咯，或者用 egg-router-plus

**Comment by kylehuangfff** [comment]
@dead-horse @atian25 初衷是避免在上层框架注册大量路由。如果egg能内置路径自动匹配控制器的特性就好了，谢谢二位～

**Comment by atian25** [comment]
`路径自动匹配控制器` 这个特性并不是通用特性，只适合在插件里面做，根据你们自己的需求做就好了，参考 egg-router-plus

**Comment by kylehuangfff** [comment]
@atian25 明白了，谢谢指点～
