### ISSUE TITLE
访问放在pubilc文件夹下面的图片资源时，超过一定时间，服务端便会自动切断链接。导致无法读取完整的图片。

### ISSUE THREAD

**Issue by zlwlogo** [eggjs/egg#2387]
* **Node Version**: 8.7.0
* **Egg Version**: 2.0.0
* **Plugin Name**: egg-mysql，egg-cors
* **Plugin Version**:3.0.0，2.0.0
* **Platform**: CentOS release 6.5
* **Mini Showcase Repository**:

返回错误信息：net::ERR_CONTENT_LENGTH_MISMATCH
每次拿资源超过6000毫秒，请求则被切断，导致到一点的资源都无法获取。
试过几次修改配置文件的timeout，尝试过后没起作用。

还希望指教一下是否有解决方案。

暂定解决方案是静态资源用ngiax指过去访问。如果可能的话，希望在egg里解决。

![default](https://user-images.githubusercontent.com/30715115/38727843-b561c5d2-3f40-11e8-9971-520c8c26c58a.png)
![default](https://user-images.githubusercontent.com/30715115/38727905-e51f6388-3f40-11e8-8471-3a6a7272998e.png)

**Comment by popomore** [comment]
It’s better to use nginx instead of egg-static for performance.
