### ISSUE TITLE
[BUG] typescript项目，使用egg-script 启动项目时优先加载ts文件而不是js文件

### ISSUE THREAD

**Issue by Cody2333** [eggjs/egg#2388]
egg-script 启动时优先加载ts文件而不是js文件导致项目启动失败

* **Node Version**: 9.6.1
* **Egg Version**: 2.6.0
* **egg-scripts**: 2.6.0
* **typescript**: 2.8.1
* **Platform**: Mac OS High Sierra
* **Mini Showcase Repository**: https://github.com/Cody2333/egg-test

### 问题描述
执行`npm run dev`,结果与预期一致。
项目在本地开发阶段可以正常运行，测试用例可以正常运行。
执行`npm run ci`，结果与预期一致，生成了ts文件对应的js文件，测试用例可通过。
然后执行`npm run start` 项目报错如下：
```
(function (exports, require, module, __filename, __dirname) { import { Controller } from 'egg';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
```

当**删除app目录下的所有ts文件**`rm -rf app/**/*.ts` ,然后再次运行`npm run start` 可以正常启动项目。

项目使用 `npx egg-init --type=ts showcase` 初始化
同时做了一些小修改,加了一个wrapper的方法，修改如下：
```
// router.js
import { Application } from 'egg';
import wrapper from './swag/wrapper';
export default (app: Application) => {
  wrapper(app, {
    title: 'aa'
  });

  // const { router, controller } = app;
  // router.get('/', controller.home.index);
};

```
### 复现步骤
```
git clone https://github.com/Cody2333/egg-test
cd egg-test
cnpm install
npm run ci
npm run start // 此处项目启动报错
rm -rf app/**/*.ts
npm run start // 此时项目正常启动
```
[详细错误日志](https://github.com/Cody2333/egg-test/blob/master/error.log)

**Comment by whxaxes** [comment]
https://github.com/Cody2333/egg-test/blob/master/app/swag/wrapper.ts#L105

请注意出错的地方，是你自己的代码，做了文件遍历并且 require
