### ISSUE TITLE
GIT 没有 v2.6.1 的标签

### ISSUE THREAD

**Issue by waitingsong** [eggjs/egg#2389]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
https://github.com/eggjs/egg/tree/2.6.1

**Comment by waitingsong** [comment]
这个自动翻译干嘛用的？以前没发现出来过
