### ISSUE TITLE
使用egg-socket.io时，在io/middleware下使用ts文件，egg无法加载中间件文件。

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#2398]
如题。

**Comment by tong3jie** [comment]
同时，在router.ts中，引入io时，提示Application没有io属性。

**Comment by atian25** [comment]
egg-socket.io miss d.ts, PR is welcome

**Comment by atzcl** [comment]
自己拓展下 `.d.ts` 文件就好了，例如：
```
import * as SocketIO from 'socket.io';

declare module 'egg' {
  export interface Application {
    io: SocketIO.Server & EggSocketIO & Namespace;
  }

  export interface Context {
    socket: any
  }
  
  interface EggSocketIO {
    middleware: xxx;
    controller: xxxx;
  }

  interface Namespace {
    route(event: string, handler: Function): any
  }
}
```

**Comment by atian25** [comment]
@atzcl could you PR  to egg-socket.io?

**Comment by atzcl** [comment]
@atian25 好的，我稍后提交 PR :smiley:

**Comment by atzcl** [comment]
请查看 [PR](https://github.com/eggjs/egg-socket.io/pull/37)

**Comment by linchinghao** [comment]
The ts file used in the io/middleware  didn't work. 
egg-socket.io/lib/loader.js:
```js
new app.loader.FileLoader({
    directory: dirs,
    target: app.io.middleware,
    inject: app,
  }).load();
```

i add the new option:
```js
new app.loader.FileLoader({
    directory: dirs,
    target: app.io.middleware,
    inject: app,
    typescript: true // add new option
  }).load();
```

so it does work.

**Comment by ngot** [comment]
@linchinghao PR is Welcome

**Comment by xifengyema** [comment]
@linchinghao  PR is Welcome

**Comment by Maledong** [comment]
@linchinghao：I'd like to help to submit a PR for all the fixtures……But before doing that, I saw you've added typescript = true. What does this mean? And why we should add that? Is 'FileLoader' including this prop?

**Comment by ngot** [comment]
Have been fixed. Feel free to reopen if there is any problem.
