### ISSUE TITLE
use vuepress to refactor egg site

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#2399]
https://vuepress.vuejs.org/guide/

**Comment by atzcl** [comment]
跟 [](https://github.com/QingWei-Li/docsify) 很像~

**Comment by atian25** [comment]
在 guide 里面有提到跟其他几个的区别

**Comment by atzcl** [comment]
打开看着眼熟，没仔细看说明，，，:sweat_smile:，认真看完，的确很好~算是集成了其他几个的优点了

**Comment by thonatos** [comment]
前面写了个测试，打算用这种目录结构：

```
- zh-CN/
- en-US/ 
- README.md 首页
```

- https://github.com/eggjs-community/eggjs-community

**Comment by cuyl** [comment]
看样子得写个 vuepress-theme-egg 代替 eggjs/doctools 里面的 themes

**Comment by thonatos** [comment]
之前群里讨论是不搞了吧，要不要关了？

**Comment by dead-horse** [comment]
我估计没有什么动力来迁移吧，有兴趣的直接 MR 吧，先关了
