### ISSUE TITLE
ctx.render的转译问题

### ISSUE THREAD

**Issue by jasontsai1990** [eggjs/egg#2400]
渲染变量
`ctx.render( ,{var: '<h1>xxx</h1>'})`

模版获取
{var: `&lt;h1&gt;xxxx&lt;/h1&gt;`}

也就是说，**render默认执行escape**，请问怎么关闭这个功能？

**Comment by solarhell** [comment]
check https://eggjs.org/zh-cn/core/security.html

**Comment by jasontsai1990** [comment]
安全那章我有看过了，但是还是不知道怎么关闭

**Comment by atian25** [comment]
check your view engine, use `safe` filter

**Comment by jasontsai1990** [comment]
I tried a lot, but I still don't know how to **colse default escape**

```
    // default view engine config.js
    // set this up？
    config.view = {
        defaultViewEngine: 'nunjucks',
        mapping: {
            '.tpl': 'nunjucks',
        },
    }
```

**Comment by popomore** [comment]
{{ var | safe }}
