### ISSUE TITLE
egg-mongoose: no timeout or retry if mongoose failed to connect on start

### ISSUE THREAD

**Issue by legendecas** [eggjs/egg#2403]
* **Node Version**: 9.11.1
* **Egg Version**: 2.6.1
* **Plugin Name**: egg-mongoose
* **Plugin Version**: 2.2.0
* **Platform**: macOS
* **Mini Showcase Repository**: 

while using default config like
```js
module.exports = {
 mongoose: {
    clients: {
      db: {
        url: 'mongodb://localhost:27017/notebook',
        options: {}
      }
    }
  }
}
```

and run `egg-scripts start` without a valid mongodb running on locallost, egg would not run web workers since egg-mongoose did not connect to mongodb instance yet. And there is no timeout for egg-mongoose's start connect, `egg-scripts` will not *exit* with non-zero code yet web workers did not run, and egg stuck.

Now if we start the mongodb instance, egg will not recover to start web workers.

Referring to issue [No retries are made after "failed to connect on first connect"](https://github.com/Automattic/mongoose/issues/5169#issuecomment-304370617), errors on first connection shall be re-thrown so that egg will exit with the error in time.

**Comment by zhangming0305** [comment]
mongodb://127.0.0.1:27017/databaseName

**Comment by zhangming0305** [comment]
@legendecas i suggest you create minimal runnable github project that we can reproduce the same error.

**Comment by legendecas** [comment]
@zhangming0305 Hi, check out this repo https://github.com/legendecas/egg-mongoose-reproduce
