### ISSUE TITLE
生成环境jenkins部署问题

### ISSUE THREAD

**Issue by llsldwy** [eggjs/egg#2408]
* **Node Version**:8.4
* **Egg Version**:2.2.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在进行生产环境 jenkins 打包过程时候，遇到一个报错，没看懂是什么原因，可否帮忙看下，谢谢

在git 中，一版本 我把package-lock.json上传 后报错（如下图）
![image](https://user-images.githubusercontent.com/6800117/38788008-e8807574-4163-11e8-8b7c-8f924a3c2e6e.png)

第二种  我把package-lock.json 删除后 报错（如下图）
![image](https://user-images.githubusercontent.com/6800117/38788026-0f956764-4164-11e8-96ac-ee4b5d43b837.png)

备注：
本地、测试环境开发都没问题！

**Comment by atian25** [comment]
it seems your `package.json` is invalid.

try  these at local:

```bash
rm -rf package-lock.json
rm -rf node_modules
npm i
rm -rf package-lock.json
```
