### ISSUE TITLE
在 .d.ts 中使用默认导入的方式导入可调用/可实例化对象

### ISSUE THREAD

**Issue by maroon1** [eggjs/egg#2409]
[TypeScript 2.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html) 引入了 `esModuleInterop` 编译选项用以区分命名空间导入和默认导入的行为，使得模块的导入行为更符合 ES6 模块的规范，同时与 Babel 的转译行为保持一致：

例如：

命名空间的导入方式：

```typescript
import * as foo from 'foo';`
```

默认导入的导入方式：

```typescript
import b from 'bar';
```

开启 `esModuleInterop` 编译选项后，当使用命名空间的导入方式时，导入对象不可调用/不可实例化。当使用默认导入的导入方式时，导入对象应当可调用/可实例化。

例如：

开启 `esModuleInterop` 前

```typescript
import * as  express from 'express';

express();
```

开始 esModuleInterop 后，导入应改为

```typescript
import express from 'express';

express();
```

目前 egg 的 .d.ts 文件中使用 `import * as KoaApplication from 'koa';` 的导入方式，导致开启 `esModuleInterop` 后编译报错。建议使用 `esModuleInterop` 的导入规则规范模块的导入方式，以避免该问题。同时，当没有开启 `esModuleInterop` 时，仍然可以通过开启 `allowSyntheticDefaultImports` 选项来避免编译报错的问题。

**Comment by whxaxes** [comment]
如果按照这么改，就产生 breakchange 了，必须得在 tsconfig 中开启 `esModuleInterop` 才能让声明生效了，而且我看其他服务端框架的声明文件，包括 express 、koa 都还是用命名空间的导入方式，所以我没 get 到你说的这种改法的优点？

**Comment by Maroon1** [comment]
@duncup 差不多是这个意思，但是不知道开启 `allowSyntheticDefaultImports` 选项是否也算一个 breakchange。
@whxaxes 更符合 ES6 模块的导入行为算是一个无法拒绝的优点吧。在早前 ES6 模块还没正式落地的时候，模块的导入规则五花八门，所以 TS 之前的做法做了一些的兼容手段。2.7 开始 TS 建议使用 `esModuleInterop` 来规范模块导入行为，使其更符合 ES6 模块的规则，在项目中是推荐打开的。即使不开启 `esModuleInterop`，那么开启 `allowSyntheticDefaultImports` 也可以，仍然可以兼容之前代码中的命名空间导入方式。

**Comment by Maroon1** [comment]
这里有一个 [Demo](https://github.com/Maroon1/es-module-interop)，可以看到未开启 `esModuleInterop` 但开启 `allowSyntheticDefaultImports` 的情况下，两种导入方式都可以正常工作，但是开启 `esModuleInterop` 后，命名空间的导入方式将会报错。

同时需要补充的一点是，一般情况下，使用默认导入来导入可调用和可实例化的模块有一个好处。

例如，从 `moment` 模块中导入一个 `moment` 函数，同时又需要导入其 `Moment` 接口来定义一个参数类型，使用默认导入可以这样做

```typescript
import moment, { Moment } from 'moment';

function foo(date: Moment) { }
```

而使用命名空间导入的时候，需要这样做

```typescript
import * as moment form 'moment';

function bar(date: moment.Moment) { }
```

第二种方式需要每一次从 `moment` 命名空间中取得 `Moment` 接口

**Comment by whxaxes** [comment]
@Maroon1  我在我自己的项目测试了一下，在 egg 的 d.ts 中使用命名空间导入，跟在 tsconfig.json 配置 `"esModuleInterop": true` 并不会冲突，也不会报错。只是需要你自己写业务的 ts 的时候使用 es module 的方式引入。

你那里会报错？提供个稳定可复现的给看看？如果会报错的话，感觉更可能是你业务代码写的有问题吧，而且如果真的是因为这个问题，那改的就不仅仅是 egg 了，egg 依赖的 koa、koa-router 这些全部都得去改了...

**Comment by Maroon1** [comment]
1. 用 `egg-init` 生成 TS 模板。
1. 在任意一个可以调用 `this.app` 的文件中，输入 `this.app.middleware` 。此时一切正常。
1. 在 tsconfig.json 中开启 `esModuleInterop` ，此时会提示 `middleware` 属性不存在。
1. 进入 eggjs 的 .d.ts 文件查看 app 对象对应的 Application 接口，修改其父类 `KoaApplication` 的导入方式为默认导入，即修改 `import * as KoaApplication from 'koa';` 为 `import KoaApplication from 'koa';`。
1. `this.app.middleware` 代码恢复正常。

目前项目中开启 `esModuleInterop` 后暂时只碰到 app 对象的接口有问题。导致这个问题的直接原因就是 KoaApplication 的导入方式与 `esModuleInterop` 规格不相符。其他地方还有待验证。

**Comment by whxaxes** [comment]
@Maroon1  但是 koa 以及 koa-router 的声明文件中的声明的导入方式也是命名空间导入哦，你确定只影响了这个？验证一下其他？

**Comment by shepherdwind** [comment]
这个似乎没法解决吧，只能发一个 pr 给 https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/koa ，这里改下 export 方式，不要现在这样 export = xxx 这样。

**Comment by shepherdwind** [comment]
`"esModuleInterop": true` 这个参数，我也有开启，实践中有没有遇到什么问题。感觉很少会需要直接读取 koa 里面的一些数据的。

**Comment by Maroon1** [comment]
这是我之前所说的那个问题的 [Demo](https://github.com/Maroon1/egg-dts)。可以看到 router 中使用 app.middleware 出现问题。

@whxaxes 开启 `esModuleInterop` 后，目前从 egg 的定义文件中报错信息上来看，受影响的只有 `Application` 接口，`Application` 接口继承了 `KoaApplication`，但 `KoaApplication` 是命名空间，不可继承，所以相当于继承失败，所以原本应当从 `KoaApplication` 上继承的属性全部丢失，因此导致了上述问题。

@shepherdwind `export = xxx` 是 CommonJS 模块特有的导出形式。它与 default 导出行为类似，区别在于 default 导出实际导出了一个名为 `default` 成员，而 `export = xxx` 并没有导出具名成员。所以 CommonJS 模块只能写成 `export = xxx`。

例如：

使用 CommonJS 模块导入语法导入一个 default 导出的 ES6 foo 模块，应该写成

```typescript
// foo.ts
export default 'foo';
```

```javascript
// bar.js
const foo = require('foo').default
```

而使用 CommonJS 模块导入语法导入一个使用 `export = foo` 导出模块，则是写成
```typescript
// foo.ts
export = 'foo';
```

```javascript
const foo = require('foo');
```

所以，使用 ES6 默认导入来导入一个 CommonJS 模块的时候必须开启 `allowSyntheticDefaultImports` 来让 TypeScript 可以正确的解析没有默认导出的 CommonJS 模块

```typescript
// foo.ts
export = 'foo';
```

```typescript
// 必须开启 allowSyntheticDefaultImports，否则会报 `模块 xxx 没有默认导出` 的错误
// 开启 esModuleInterop 后默认自动开启 allowSyntheticDefaultImports
import foo from 'foo'
```

PR 很简单，我回头提一个

**Comment by beliefgp** [comment]
@whxaxes   你那没报错，估计你是开了 `"skipDefaultLibCheck": true, // 忽略库的默认声明文件的类型检查 `，就是不检测 egg 声明文件的类型，检测的话，确实有上面的问题。

**Comment by whxaxes** [comment]
@beliefgp  原来如此，确实是开了这个

**Comment by whxaxes** [comment]
这个问题应该已经解决了，也加了对应的单测（ https://github.com/eggjs/egg/blob/master/test/fixtures/apps/app-ts-esm ）。先关了
