### ISSUE TITLE
regarding egg-di

### ISSUE THREAD

**Issue by zhq3k** [eggjs/egg#2411]
* **Node Version**:8.9
* **Egg Version**:2.5
* **Plugin Name**:egg-di
* **Plugin Version**:1.0
* **Platform**:windows
* **Mini Showcase Repository**:

Hi team,

As your document describe, service is a request level object. That means system will create new service instance when request an controller action right? If I using DI inject service, this service is a singleton right? But i testting using inject/getComponent, all return new instance service.

could you help how i can use one service instance?

thanks in advance.

**Comment by popomore** [comment]
It will create a instance in every request, same as ctx.service

**Comment by zhq3k** [comment]
@popomore ,thanks, i got it.

**Comment by popomore** [comment]
In egg, we only have global level (Application) and Request level (Context)
