### ISSUE TITLE
Egg中写的API能直接读到访问API的域用户名吗?

### ISSUE THREAD

**Issue by zhq3k** [eggjs/egg#2414]
* **Node Version**:8.9
* **Egg Version**:2.5
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:windows
* **Mini Showcase Repository**:

问个问题，Egg中写的API能直接读到访问API的域用户名吗？就象IIS，当用Windows认证时，在Service端可以直接读到用户名。如果能，该如何做呢？

谢谢。

**Comment by ZQun** [comment]
ctx.request    https://eggjs.org/zh-cn/basics/objects.html#context

**Comment by atian25** [comment]
as far as I known,  it's not a built-in feature. maybe you need to find if any koa middleware for window auth.
