### ISSUE TITLE
请问项目中该怎样得到自定义框架的config

### ISSUE THREAD

**Issue by DerekYeung** [eggjs/egg#2416]
我目前的情况是在自定义框架中设置了一个config.xxx，这个配置项是一个数组，里面配置的是一些目录信息，我想达到的效果是在项目中可以继承这些目录信息，然后如果有项目自己的目录就push一下。
我看了一下egg的实现，貌似是没有对自定义框架的config有进行一个继承，想来确认一下
https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/config.js#L77

我目前临时的解决方案是这样的
```
const frame = require('自定义框架/config');
module.exports = appInfo => {
	const config = exports = frame(appInfo) || {};
	config.xxx.push('custom dir');
	return config;
};
```
这样现在是可以实现效果，但是也会执行两次框架的config，感觉不是最佳的方案

**Comment by atian25** [comment]
egg use `extend2` to merge `config`,  if `array` will override, not merge, cause you can't describe 
whether you want to `replace the same index` or  `concat array`  or `replace all item`

```js
config.test = [ 1, 2, 3 ];
config.test = [ 2, 3, 4 ];
```

**Comment by DerekYeung** [comment]
@atian25 ok 主要是想在项目中也取到框架的config 咋合并其实到好说 我在想是不是可以考虑一下调整一下加载的机制，在框架中的一些配置可以直接拿来引用，这样在项目中不管是合并还是继承都可以根据自己的情况去实现

**Comment by atian25** [comment]
you can't get **merging** config when a plugin is still loading config. only at another step such as `app.js`.

or 


```js
// config/config.default.js
module.export = (appInfo, appConfig) => {
  const config = {};
  config.dir = [ 'a', 'b' ].concat(appConfig.dir || []);
  return config;
}
```
