### ISSUE TITLE
How does Egg uses archiver to zip some files ,and the client will download the zip file?

### ISSUE THREAD

**Issue by Jayanzhou** [eggjs/egg#2418]
# How does Egg uses archiver to zip some files ,and the client will download the zip file?

**Comment by atian25** [comment]
- https://github.com/eggjs/examples/tree/master/download
- https://github.com/node-modules/compressing

**Comment by Jayanzhou** [comment]
@atian25 现在问题是：在egg的controller中，调用了其他api返回了几个图片stream，想在controller中组成一个zip文件，然后返回给客户端下载。目前是用node-archiver  zip后写入文件，在读取内容返回给ctx.body,不知道有没有不写入文件的方法，可以压缩多个stream然后返回给客户端呢，谢谢

**Comment by popomore** [comment]
用 tar-stream

**Comment by atian25** [comment]
https://zhuanlan.zhihu.com/p/33783583
