### ISSUE TITLE
egg-socket.io的跨域问题

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#2419]
* **Node Version**:8.10.0
* **Egg Version**:2.2.1
* **Plugin Name**:egg-socket.io
* **Plugin Version**:4.0.7
* **Platform**:Windows
* **Mini Showcase Repository**:

在本机上不同端口的io服务访问可以传到`filter`中如下
```
// io消息的预处理
module.exports = app => {
  return async (ctx, next) => {
    console.log('IO消息来了');
    console.log(ctx);
    await next();
    console.log('packet response!');
  };
};
```
但是无法访问到在router中的回调，直接就返回了
```
module.exports = app => {
  const { router, controller, io } = app;
  router.get('/', app.controller.home.index);
  io.of('/').route('add user', app.io.controller.chat.addUser);
  io.of('/').route('new message', app.io.controller.chat.newMessage);
};
```
使用相同端口的测试文件是可以执行到回调的，所以应该是和跨域安全有关，但是在安全那没找到关于socket的说明

**Comment by thonatos** [comment]
请先参考文档检查是否使用方法有误；无法确认情况下建议提供一下最小可复现仓库。

- [egg-socket.io](https://github.com/eggjs/egg-socket.io)
- [Socket.IO](https://eggjs.org/zh-cn/tutorials/socketio.html)

**Comment by hezhongfeng** [comment]
莫名其妙的ok了，我先关闭
