### ISSUE TITLE
在约定下可使用的构建工具，如 webpack、能否也在examples给个例程？

### ISSUE THREAD

**Issue by terenceyhj** [eggjs/egg#2424]
在约定下可使用的构建工具，如 webpack、能否也在examples给个例程？
 好像按照官方那套约定的目录结构，使用的构建工具webpack来统一的约定进行应用开发，有点无从下手？ 最好是webpack+vue2.x的。

* **Node Version**:8.11.1
* **Egg Version**:2.7.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/assets.html
