### ISSUE TITLE
After modify code and worker reload, The app.cache set by schedule was missing

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#2425]
when the worker reload, the app.js code need to be invoked, I initialize the app.cache = {} in app.js,
but the schedules can't be excuted immediately, so I lost my app.cache

**Comment by atian25** [comment]
act as expected, worker is a process, when reload is fork another process.

if you want to share, use sth like redis

**Comment by miaojiuchen** [comment]
@atian25 Hello! I understand, but why the schedules not being excuted after the work reload?
I have set the `immediate: true` option

**Comment by miaojiuchen** [comment]
I pefer that the schedules should be excuted after the hot reload

**Comment by miaojiuchen** [comment]
How can i restart my shchedules after hot reload?
I do some data fetching in them

**Comment by atian25** [comment]
- recommend use `redis` store
- listen to `app-start` event at agent, when find worker start, send a message with cache to it.
- see also https://eggjs.org/zh-cn/advanced/cluster-client.html
