### ISSUE TITLE
egg-session-redis 插件保存session报错

### ISSUE THREAD

**Issue by haichang** [eggjs/egg#2435]
* **Node Version**: v8.11.1
* **Egg Version**:  2.2.1
* **Plugin Name**: egg-session-redis
* **Plugin Version**: ^1.0.0
* **Platform**: windows
* **Mini Showcase Repository**:

`'use strict';

const assert = require('assert');

const ONE_DAY = 1000 * 60 * 60 * 24;

module.exports = app => {
  const name = app.config.sessionRedis.name;
  const redis = name ? app.redis.get(name) : app.redis;
  assert(redis, `redis instance [${name}] not exists`);

  app.sessionStore = {
    * get(key) {
      const res = yield redis.get(key);
      if (!res) return null;
      return JSON.parse(res);
    },

    * set(key, value, maxAge) {
      maxAge = maxAge || ONE_DAY;
      value = JSON.stringify(value);
      yield redis.set(key, value, 'PX', maxAge); //set只接收前2个参数，4个参数会报错
    },

    * destroy(key) {
      yield redis.del(key);
    },
  };
};
`

name: 'ReplyError'
message: 'ERR wrong number of arguments for \'set\' command'
command: { name: 'set', args: [ '1524136046822-YEVqSRMo8Suo5seK2ZxTJyRJULsg-EuI', '{"user_id":782,"_expire":1524222447029,"_maxAge":86400000}', 'PX', '86410000' ] }

**Comment by popomore** [comment]
Maybe it's a problem of https://github.com/luin/ioredis

**Comment by luin** [comment]
The error message `ERR wrong number of arguments for 'set' command` indicates that you were using an outdated version of Redis. Redis prior to v2.6.12 don't support modifiers like `PX`/`NX`.
