### ISSUE TITLE
egg-mysql 关于 query 模糊查询  between  and 如何使用问题 文档 没有响应的demo

### ISSUE THREAD

**Issue by colourhand** [eggjs/egg#2437]
* **Node Version**:8.9.3
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by colourhand** [comment]
刚开始入门后端开发 @fengmk2  哪里有基础教程 O(∩_∩)O~

**Comment by popomore** [comment]
这里不负责培训，google 应该能搜到。
