### ISSUE TITLE
使用egg构建的网站facebook分享报错PARTIAL_FILE transfer closed with 456853 bytes remaining to read

### ISSUE THREAD

**Issue by gsgtzq** [eggjs/egg#2439]
* **Node Version**:8.11.1
* **Egg Version**:2.2.1
* **Plugin Name**:egg-view-ejs等模板引擎
* **Plugin Version**:2.0.0
* **Platform**:all

egg渲染html，页面中包含facebook的分享功能，调用分享功能发现fb不能获取到任何meta标签中的信息，使用facebook开发图谱调试，发现facebook报错**Curl 错误：PARTIAL_FILE transfer closed with 456853 bytes remaining to read**，更换模板引擎无果，甚至直接使用static插件均不能解决这个问题。

controller的代码非常简单，如下：

```javascript
'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    const { ctx } = this;
    return await ctx.render('pc/index.html');
  }
  async mobileIndex() {
    const { ctx } = this;
    return await ctx.render('mobile/index.html');
  }
}

module.exports = HomeController;

```

**Comment by gsgtzq** [comment]
新的结果：
fb的share debugger结果确实如上，真正分享的时候并不会出问题。

我的想法：
虽说真正使用时不会有问题，但是egg本身的渲染上可能也是有问题的，毕竟debugger的报错信息一直没有变，我从[stackoverflow](https://stackoverflow.com/questions/36579391/facebook-open-graph-debugger-returning-partial-file-or-operation-timeouted "facebook-open-graph-debugger-returning-partial-file-or-operation-timeouted")找到了这篇文章，与我所述症状相似，也希望官方能抽空检查下相关的模块。

**Comment by atian25** [comment]
which line report `PARTIAL_FILE transfer closed with 456853 bytes remaining to read` ?
