### ISSUE TITLE
中间件，对于静态资源.html文件，页面请求访问静态资源下的某一个html文件，中间件不执行

### ISSUE THREAD

**Issue by 184609680** [eggjs/egg#2444]
我现在有一个需求是一些静态页面
然后我把他放在静态资源下
但是
当我在用中间件处理这部分静态页面时，发现
页面访问这些静态页面（.html文件）
并未执行中间件中的代码
但是像（其它的任何请求都会进入中间件）
问下有没有什么办法

**Comment by atian25** [comment]
insert your middleware to `app.coreMiddleware` before `static` middleware
