### ISSUE TITLE
关于Servie实例化构造函数传参的问题

### ISSUE THREAD

**Issue by 7-cat** [eggjs/egg#2445]
有一个需求就是需要像Java的类和对象那样，每创建一个Servie对象，可以在构造函数中传参，生成一个唯一的Service对象。

egg 的service貌似没有构造函数传参的地方，如果手写一个方法到Service中，比如：

const Service = require('egg').Service

class BaseService extends Service {
      setUserId (userId) {
           this.userId = userId
      }
      
      getUserId (){
          return this.userId
      }
}

module.exports = BaseService

从egg的文档中得知，实例化Servie有两个途径：

1. Service 不是单例，是 **请求级别** 的对象，框架在每次请求中首次访问 ctx.service.xx 时延迟实例化，所以 Service 中可以通过 this.ctx 获取到当前请求的上下文。
    如果采取这种方式，一个请求范围内，只有一个BaseService对象，如果调用了setUserId()，那所有用到这个service的地方都被修改了。

2.创建匿名Context并从匿名Context对象中获取Servie对象：
const ctx = app.createAnonymousContext();
ctx.service.baseService.setUserId();
采取这种方式每次都要实例化一个ctx，是不是开销太大。。

**Comment by atian25** [comment]
the question is, why do you need a singleton instance?  why not use `app.addSingleton()`?

**Comment by 7-cat** [comment]
I  need a singleton service instance dynamically, not predefined in the app.
like:
UserService s1 = new UserService(userId)
s1.getUserName()

Does it possible ?

**Comment by atian25** [comment]
```js
// app/extend/application.js

const INSTANCE = Symbol('Application#instance');

module.exports = {
  get MyService() {
    if (!this[INSTANCE]) {
      this[INSTANCE] = new SomeClass(this.config.xx);
    }
    return this[INSTANCE]
  }
};
```

**Comment by 7-cat** [comment]
额，英文不太好，还是用中文表达一下，还请谅解。
可能我上面没表达清楚需求，导致有些误会。。
我想要的是一个非请求级别的service，而是一个可以随时在代码中New出来的service，这个service就像new出来的普通对象一样，只是一个普通的变量，而不是请求级别或者app级别的单例。

**Comment by atian25** [comment]
- `app.someService` is a global instance, not context-base.
- you could just place your class into `lib/my_class.js` and `require` it like normal node way

**Comment by 7-cat** [comment]
@atian25 but in the my_class.js, I also need reference other service.
If I extract all my business logic from services to lib/my_XXX_class.js
then the services layer seems redundant for my situation

**Comment by atian25** [comment]
if your class is a global instance, it can't refer to context-base service, you had to pass `ctx` to every methods.

**Comment by 7-cat** [comment]
@atian25 
Actrually, what I need is:
const ctx = app.createAnonymousContext();
ctx.service.baseService.setUserId();

does this method has any downside?

**Comment by atian25** [comment]
yes,  `AnonymousContext` so you can't get the real user context such as cookie, session, ip etc.

I still don't know why you need this, you could describe your sense in chinese, with some pseudo code

**Comment by atian25** [comment]
it look like a model level, sth like `redis_model`.

`需要在service初始化的时候就动态地设置redis中存取数据的key值` what is the `key` used for? where is it come from?

**Comment by 7-cat** [comment]
key用在redis中定位数据，比如一个id为12的User，在reids中存储如下：
类型:Hash
key : 'user:12'
value: {id:12, name:'user12'}

class UserService extends Service {
  constructor(ctx) {
    super(ctx)

    this.name = 'user'
  }

  setId(id) {
    this.id = id
    this.key = `${this.name}:${this.id}`
  }

  async update(data) {
    this.redisClient.update(this.key, data)
  }
}

使用：
const ctx1 = app.createAnonymousContext()
const userService1 = ctx1.service.user
userService1.setId(1)
userService1.update({ name: 'user1' })

const ctx2 = app.createAnonymousContext()
const userService2 = ctx2.service.user
userService2.setId(2)
userService2.update({ name: 'user2' })

**Comment by atian25** [comment]
`userService1` and `userService2` will be used in the same request?  or just one request one service?

**Comment by 7-cat** [comment]
会在一个请求中同时使用

**Comment by atian25** [comment]
```js
const INSTANCE_MAP = Symbol('INSTANCE_MAP');
const INSTANCE = Symbol('Context#instance');
const My_Class = require('../../lib/my_class');

module.exports = {

  get [INSTANCE_MAP]() {
    if (!this[INSTANCE_MAP]) {
      this[INSTANCE_MAP] = new Map();
    }
    return this[INSTANCE_MAP];
  },

  getUserModel(id) {
    let model = this[INSTANCE_MAP].get(id);
    if (!model) {
      // `this` is ctx
      model = new My_Class(this, id);
      this[INSTANCE_MAP].put(id, model);
    }
    return model
  }
}
```

**Comment by 7-cat** [comment]
getUserModel（id）可不可以是function级别的作用域？即在function中定义，走完function就销毁实例？

can getUserModel(id) scoped by function not by ctx?

**Comment by atian25** [comment]
sure, you just need to init it by `const model = new My_Class(ctx, id)`.

forgot `service`, it is not what you need.

**Comment by 7-cat** [comment]
So what I need is a redis model layer..

**Comment by 7-cat** [comment]
```
class UserService extends Service {
  constructor(ctx) {
    super(ctx)

    this.name = 'user'
  }
  
getInstance(id) {
    return new Proxy(this, {
      id,
      key : `${this.name}:${this.id}`
    })
  }

  async update(data) {
    return this.redisClient.update(this.key, data)
  }
}
```
使用：

```
const userService1 = this.ctx.service.user.getInstance(1)
userService1.update({ name: 'user1' })

const userService2 =this.ctx.service.user.getInstance(2)
userService2.update({ name: 'user2' })
```

Do you mean this.. I don't know about Proxy..

**Comment by atian25** [comment]
just learn, it's an ES6 feature.

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by 7-cat** [comment]
Thanks very much！
