### ISSUE TITLE
源码贡献

### ISSUE THREAD

**Issue by lyh1091106900** [eggjs/egg#2449]
我想要参与源码贡献，但是我不是很清楚eggjs框架是怎样的，有哪一方面资料可以提供，让我更清楚的了解框架内代码是如何工作的，不是使用手册

**Comment by atian25** [comment]
egg is just a load over koa, and provide plugin/framework system, maybe you could read https://eggjs.org/zh-cn/advanced/loader.html

**Comment by dead-horse** [comment]
read the source code is the best way to understand a project

**Comment by atian25** [comment]
@lyh1091106900 I don't understand what you mean.

just deploy to multiple container, and use SLB / Nginx in front of them.
