### ISSUE TITLE
定时任务 class 写法缺少 app 的获取方法？

### ISSUE THREAD

**Issue by JasinYip** [eggjs/egg#2451]
* **Node Version**: v9.4.0
* **Egg Version**: 4.7.0
* **Plugin Name**: egg-schedule
* **Plugin Version**:
* **Platform**: macOS v10.13.4 (17E199
* **Mini Showcase Repository**:

官方文档上的定时任务的 class 写法：

```js
const Subscription = require('egg').Subscription;

class UpdateCache extends Subscription {
  static get schedule() {
    return {
      interval: '1m',
      type: 'all'
    };
  }

  // subscribe 是真正定时任务执行时被运行的函数
  async subscribe() {
    const res = await this.ctx.curl('http://www.api.com/cache', {
      dataType: 'json',
    });
    this.ctx.app.cache = res.data;
  }
}

module.exports = UpdateCache;
```

文档中还提到我们还可以这样写，以达到在开发环境不执行定时任务的需求：

```js
disable: app.config.env === 'local', // 本地开发环境不执行
```

但是这里的 `app` 是用「简化模式」`module.exports = app =>` 获取的，在 class 写法中怎么获取文档中没有提到。我尝试过用 `this.app` 或 `this.ctx.app` 都是无法获取的。

请问这里获取 `app` 的办法是什么？

**Comment by popomore** [comment]
```
module.exorts = app => {
  return class UpdateCache extends Subscription {};
}
```

**Comment by JasinYip** [comment]
> module.exorts = app => {
>   return class UpdateCache extends Subscription {};
> }

这种写法不符合框架的 [代码风格指南](https://eggjs.org/zh-cn/style-guide.html#classify) 吧？

**Comment by atian25** [comment]
那只是一个风格。看了下 Schedule 这块的配置， classify 的话，那个是一个静态属性，所以没办法获取到 app，这块暂时没太多想法，可以提 PR 优化下。（我个人其实 schedule 这块还是喜欢 exports 风格）
