### ISSUE TITLE
关于Service的一点点思考

### ISSUE THREAD

**Issue by 7-cat** [eggjs/egg#2453]
如果理解的没错的话，Egg的Service是请求级别的单例，而且是由框架自动实例化和延迟加载，不能自己new实例，比如new UserService()
这种模式有时候感觉用起来不那么方便，也许是我的使用姿势不对，下面说说我的使用感受，不当之处还请多多指正：
1.首先感觉最不自由的就是用户无法使用new关键词来new出一个Service实例并在构造函数中自定义参数。
2.其次 很多service其实并不需要request级别，只要app级别就可以了。
3.Controller作为请求级别是无可厚非的，但是Service是否真的有必要强制为请求级别并且不允许用户自己实例化？

究竟什么是Service？
是否可以理解为给Controller调用的 易于测试的代码封装？避免在Controller中写重复代码，并且易于测试。
如果是这样的话，个人感觉Servie这一层没必要也强制为请求级别，框架可以把service实例化到app这个层面，比如egg-mysql的model，而不是request这个层面，然后给更多用户的主动权，比如允许用户new一个service,尽量减少框架对Serive的侵入，把Service还原为普通的Class，这样会不会增加使用的灵活性。。

当然上面说的那些new一个service实例并且挂载到app级别上的需求完全可以不用框架的service自己实现一套，但是这样service的地位就显得很尴尬，感觉成了多余的了，直接在Controller中调用自己实现的“service”就可以完全不用框架的service了。。

**Comment by atian25** [comment]
you could just use `app.loader.loadToApp` to mount your BizService

**Comment by popomore** [comment]
可能你对这个有误解，隐式传递上下文是 egg 的特性之一，在大规模链路分析有奇效。如果你对这个不理解，可以看看 opentracing 并仔细想一下如何在 node 应用中实现。还有你上面提到的 mysql 这也必须是请求级别的。

Egg 并没有做任何限制一定要使用请求级别的，反而是高度自定义的，你可以根据自己的需求来定制。

**Comment by 7-cat** [comment]
@atian25 
感谢回复，我去看看文档，学习一下app.loader.loadToApp的使用。

@popomore 
感谢回复，如果有些Service基本跟ctx没关系，大部分跟reques相关的操作都放在Controller中的话，这个隐试的传递上下文到Service在这种情况下感觉不太适合。。可能只是我这一个需求所遇到的情况，用自定义的方法是可以解决的，Egg非常灵活，目前我还只是出于简单傻瓜方式的使用，没有深入了解，以后要慢慢去多多学习Egg框架的实现。

**Comment by atian25** [comment]
本来 Service 定位就是`处理用户请求中的可复用逻辑`，因此 `隐式传递上下文` 是很有必要的，因为你做 opentracing 或者记录日志，或者获取用户信息的时候，context 就非常有必要。

而你所需要的那些全局静态的类，更类似于 app.xx 这样的，只需要一句简单的加载：

```js
// app.js
// 把 app/utils 下的所有文件加载并挂载到 app.utils
module.exports = app => {
  const directory = path.join(app.config.baseDir, 'app/utils');
  app.loader.loadToApp(directory, 'utils');
};
```

为什么内置 Service 不这样呢：
- 你所担心的反复 new 性能问题，微乎其微，不要担心性能。
- 上面提到的，Service 本身就是跟用户请求强相关的。
- 你需要的全局，并不是共性需求，egg 已经提供方便的方式给你自己去扩展

**Comment by 7-cat** [comment]
好的，了解清楚了Service的定位，我就一点都不纠结了，感觉框架的Service是很有必要存在的。
我的需求可以自己扩展，感谢各位的释疑~非常感谢。

**Comment by musicode** [comment]
我在 service 封装了很多 CRUD 的操作，按照各位的交流记录来看，似乎 service 只是跟请求上下文相关的，那么似乎 CRUD 应该在 service 下一层，这样的分层是不是太多了一些，如果我确信用 service 的地方不涉及任何请求上下文，为啥不能 new 一个 service 实例来用呢？

**Comment by wurining** [comment]
@musicode 我也是这么用的，不过我觉得业务逻辑的分层灵活度挺高的，对于不同复杂度的项目，可以自己扩展。上面几位讨论了框架的共性，service的初衷可能是为了简化包含上下文的重复过程来用的，可以在service层之后model之间加一个modelService层，我觉得只要我们用着合理，就可以了，分层主要是为开发者的开发和理解更方便而设计的。
