### ISSUE TITLE
请为egg-graphql插件提供ts支持，谢谢

### ISSUE THREAD

**Issue by BubbleBear** [eggjs/egg#2456]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
PR is welcome

**Comment by ShuaiShuaiguo** [comment]
最近也折腾一个插件，参考egg-graphql,使用egg-loader实现文件加载，默认支持ts。支持*.graphql文件加载，以及apollo官方文档关于模块化的方案。对于ts，有一定的目录约定，配置请参考参考 [run-books](https://github.com/ShuaiShuaiguo/run-books)。  [egg-gql](https://github.com/ShuaiShuaiguo/egg-gql)

**Comment by nigelvon** [comment]
有什么进展么？另外apollo server已经升级到版本2了。
