### ISSUE TITLE
如何实现定时删除日志

### ISSUE THREAD

**Issue by leizhao92** [eggjs/egg#2457]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

日志模块目前可以实现按天切割，按大小切割，但是如果项目长时间运行会产生很多日志，如何能做到对日志进行自动的或定时的清理删除？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-logrotator

```js
// if any files need rotate by file size, config here
exports.logrotator = {
  maxFiles: 10,                    // pieces rotate by size
  maxDays: 31,                     // keep max days log files, default is `31`. Set `0` to keep all logs
};
```

@popomore it seems need to add some description to https://eggjs.org/zh-cn/core/logger.html

**Comment by leizhao92** [comment]
感谢回复！

**Comment by leizhao92** [comment]
@atian25 感谢回复！
