### ISSUE TITLE
egg-sequelize@3.1.3 index.d.ts 文件疑似发布时丢失

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#2462]
egg-sequelize@3.1.3 项目内已经加了 index.d.ts 但是发布出来的版本找不到 index.d.ts 文件。是不是发布时运行了什么清理脚本给误删了？

**Comment by popomore** [comment]
Should add index.d.ts to pkg.files

https://github.com/eggjs/egg-sequelize/blob/master/package.json#L48

**Comment by duncup** [comment]
@popomore please review at sometime.
