### ISSUE TITLE
使用typescript写egg，无法使用路由中间件的方式挂载中间件

### ISSUE THREAD

**Issue by wython** [eggjs/egg#2463]
![image](https://user-images.githubusercontent.com/15258919/39283781-7a8a0fb2-4942-11e8-99fe-e0cb3983cdac.png)
egg支持如上方式挂载中间件，但是如果用typescript。
则会报如下错误:
Property 'session' does not exist on type 'Middleware<Context>[]'

**Comment by whxaxes** [comment]
目前的 middleware 属性是继承自 koa application 对象的，暂时先 `(middleware as any).session()` 处理一下，我尽量在这两天提个 PR 修复一下
