### ISSUE TITLE
Is there a way swtich to urllib.HttpClient2 in egg?

### ISSUE THREAD

**Issue by dsonet** [eggjs/egg#2467]
I need the retry ability which is available in HttpClient2, but seems egg-core still use HttpClient, what's the best way to figure it out?
Maybe we should just use the HtttpClient2 since it's completely compatible with HtttpClient and introduce some very useful abilities.

**Comment by popomore** [comment]
https://github.com/eggjs/egg-cluster/pull/66

**Comment by atian25** [comment]
ping @dead-horse

**Comment by fghpdf** [comment]
How about this?

I used content to realize retry feature.

**Comment by popomore** [comment]
Can we enable it by default, it's a compatible feature. cc @fengmk2
