### ISSUE TITLE
CORS，跨域问题，CSRF 的防范的问题。

### ISSUE THREAD

**Issue by roc2539** [eggjs/egg#2470]
情况是这样的。
前端用的的是antd pro，后端egg。前后端跨域。
前端在.webpackrc.js设置了 proxy，请求后端egg，返回"message": "missing csrf token"。请求thinkjs正常。
然后再egg中设置了 cors
config.default.js中设置
 config.security = {
        // xframe: {
        //     enable: false,
        // },
        // csrf: {
        //     // enable: true,
        //     ignoreJSON: false, // 默认为 false，当设置为 true 时，将会放过所有 content-type 为 `application/json` 的请求
        //     useSession: true, // 默认为 false，当设置为 true 时，将会把 csrf token 保存到 Session 中
        //     cookieName: 'csrfToken', // Cookie 中的字段名，默认为 csrfToken
        //     sessionName: 'csrfToken', // Session 中的字段名，默认为 csrfToken
        //     headerName: 'x-csrf-token', // 通过 header 传递 CSRF token 的默认字段为 x-csrf-token
        // },
        // 白名单
        domainWhiteList: ['http://localhost:8000'],
    };
    config.cors = {
        origin:'http://localhost:8000',
        allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
        domainWhiteList: ['http://localhost:8000'],
    };

plugin.js，依然有问题。
exports.cors = {
    enable: true,
    package: 'egg-cors',
};
// exports.security = {
//     domainWhiteList: [ 'http://localhost:8000' ],
// };

最后尝试走crsf，参考
https://eggjs.org/zh-cn/core/security.html#ajax-请求
https://github.com/eggjs/egg-security#using-csrf-when-request-by-ajax
客户端读取到了cookie，然后设置到Header中
Request 返回。
POST /api2/login HTTP/1.1
Host: localhost:8000
Connection: keep-alive
Content-Length: 0
accept: application/json
Origin: http://localhost:8000
x-csrf-token: D5Usnww2sbu4V-BN9QRrtlfI
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
content-type: application/json; charset=utf-8
Referer: http://localhost:8000/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
Cookie: csrfToken=D5Usnww2sbu4V-BN9QRrtlfI
这种情况下没有问题了。

但是，前后端交互的时候。第一次交互，后端没有写cookie的时候。就还是会出现"message": "missing csrf token"。怎么处理？

另外，如果配置到csrfToken在session中，前端用， const csrfToken = sessionStorage.getItem('csrfToken');获取不到数据。要怎么获取？配置了session的  httpOnly: false,还是不行。

**Comment by roc2539** [comment]
https://eggjs.org/zh-cn/basics/controller.html#referrer-校验  ?
jsonp 配置？
@dead-horse

**Comment by roc2539** [comment]
那我现在就是，关闭csrf，
      srf: {
            enable: false,
        },

然后配置了，
exports.jsonp = {
        whiteList: /^http?:\/\/localhost:8000\//,
    };

目前来说是OK的

**Comment by 750973092** [comment]
![1553070497(1)](https://user-images.githubusercontent.com/22766860/54669788-31a4b480-4b2d-11e9-8205-03635580d41e.png)
那是这样设置吗

**Comment by 750973092** [comment]
怎么我没有效果呢
