### ISSUE TITLE
清除cookie失败

### ISSUE THREAD

**Issue by leoDreamer** [eggjs/egg#2474]
* **Node Version**:  8.4.0
* **Egg Version**:  2.2.1
* **Plugin Name**: egg-cookie
* **Plugin Version**: 内置
* **Platform**:
* **Mini Showcase Repository**: https://github.com/leoDreamer/egg_issue_repo_2474.git

问题描述:
   在中间件中清除cookie后立即抛出一个错误,清除response中cookie失败
```javascript
    ctx.cookies.set('access-token', null, {
      overwrite: true
    })

    throw Error(`[access-token]已过期,请重新登录`)
```
repo 重现步骤
- 使用setcookie中间键添加cookie
- 使用removecookie移除cookie（问题所在，移除失败）

**Comment by dead-horse** [comment]
默认的错误处理函数不会写入响应头，不要随便抛异常来处理。
