### ISSUE TITLE
npm run dev没有错误 , npm start时报错数据库的一张表不存在

### ISSUE THREAD

**Issue by yupeilin123** [eggjs/egg#2477]
这个要如何解决？

* **Node Version**:
node 8.11.1
* **Egg Version**:
egg 2.7.1
* **Plugin Name**:
egg-scripts 2.6.0
egg-cors 2.0.0 
egg-sequelize  3.1.3 
mysql2 1.5.3
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

 ## npm start时错误如下

![image](https://user-images.githubusercontent.com/28672197/39394328-9723f7f6-4b03-11e8-9cfa-d1b053c5f1ba.png)

npm run dev的时候，一切顺利，表的建立都能顺利进行，代码如下
![image](https://user-images.githubusercontent.com/28672197/39394358-fd96e0de-4b03-11e8-87b5-021b2fd337dc.png)

注：
在服务器上跑的时候 npm start没有报错
在本地上跑的时候就报错了

**Comment by dead-horse** [comment]
检查你的数据库表结构
