### ISSUE TITLE
install found  Unexpected end of JSON input while parsing near 

### ISSUE THREAD

**Issue by cqllang** [eggjs/egg#2478]
When I run：
npm i egg --save
return a error:
npm ERR! Unexpected end of JSON input while parsing near '...3f0ac2c7ad7c73f07afbf'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lance/.npm/_logs/2018-04-28T17_33_20_370Z-debug.log

my node version:v8.11.1
npm version:5.6.0
registry: https://registry.npm.taobao.org

a debug.log detail error log:

290 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...3f0ac2c7ad7c73f07afbf'
290 verbose stack     at JSON.parse (<anonymous>)
290 verbose stack     at parseJson (/Users/lance/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
290 verbose stack     at consumeBody.call.then.buffer (/Users/lance/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
290 verbose stack     at <anonymous>
290 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
291 verbose cwd /Users/lance/work/node/egg-example
292 verbose Darwin 17.3.0
293 verbose argv "/Users/lance/.nvm/versions/node/v8.11.1/bin/node" "/Users/lance/.nvm/versions/node/v8.11.1/bin/npm" "i" "egg" "--save"
294 verbose node v8.11.1
295 verbose npm  v5.6.0
296 error Unexpected end of JSON input while parsing near '...3f0ac2c7ad7c73f07afbf'
297 verbose exit [ 1, true ]

Can you give me some help?

**Comment by atian25** [comment]
it seems your package.json is invalid, could you show it ?

**Comment by dead-horse** [comment]
npm 的异常，可能是网络原因，重试吧
