### ISSUE TITLE
querystring重复字段为何不直接解析成数组而是忽略？

### ISSUE THREAD

**Issue by isLishude** [eggjs/egg#2482]
在 nodejs 标准库中的 [querystring 模块](https://nodejs.org/dist/latest-v10.x/docs/api/querystring.html#querystring_querystring_parse_str_sep_eq_options) 就是将重复字段解析成数组，并且在很流行的包 qs 也是这样的处理。

官方文档说明只能使用 queries 来获取，但是这样子字段都变成数组了。

GET 是幂等操作，如果不修改内容，按照规范就得使用 GET 而不是 POST，日常使用中那就避免不了使用 GET 传递数组，一种是类似 PHP 的处理，将字段设置 `field[]` 的形式；另一种就是如果重复就变成数组。而 eggjs 是这样很奇怪的处理，不知道官方是如何考虑的。

**Comment by tong3jie** [comment]
请仔细看官方文档。

有时候我们的系统会设计成让用户传递相同的 key，例如 GET /posts?category=egg&id=1&id=2&id=3。针对此类情况，框架提供了 ctx.queries 对象，这个对象也解析了 Query String，但是它不会丢弃任何一个重复的数据，而是将他们都放到一个数组中：

**Comment by isLishude** [comment]
@tong3jie 文档我看了，queries 我也知道

> 官方文档说明只能使用 queries 来获取，但是这样子字段都变成数组了。

**Comment by popomore** [comment]
保证参数的类型一致，不然应用很容易被攻击。

**Comment by isLishude** [comment]
很容易被攻击？不理解，况且像qs这样的包就是把重复的字段解析成数组的。

换一种方案，只提供一个field[]字段形式解析成数组会不会更好一些？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/39501805-87d62ece-4def-11e8-8880-23126c649c52.png)

**Comment by isLishude** [comment]
文档我是看了的，我是没明白是如何会引发系统异常的，其它框架包括 thinkjs restify 框架都是把重复字段处理为数组的。

**Comment by isLishude** [comment]
框架替开发者做这个决定是不是不太好？validate 的时候判断是不是需要数组会不会更好？

下面是 thinkjs 的做 validate 的时候。

```js
module.exports = class extends think.Logic {
  indexAction(){
    let rules = {
      address: {
        array: true,       // 字段类型为 array 类型
        method: 'GET'       // 从 querystring 活得
      }
    }
    let flag = this.validate(rules);
  }
}
```

这里就把 address 从 querystring 获得，而且是数组。

这样子会不会更好？

**Comment by atian25** [comment]
这是我们推荐的风格，如果你有自己的习惯，可以通过 extend 提供自己的逻辑实现。

从我们的角度来看，从长期维护的角度来看，开发者本身的意图应该表达的尽量清晰，既然你是数组，你应该明确的使用 queries 来使用。

**Comment by popomore** [comment]
所以说为什么称为企业级，因为很多这类问题都已经通过解决方案的方式提供了，不然很多开发者不会考虑这些问题。

比如文档的例子，开发者认为 ctx.query.key 为字符串，那么调用 ctx.query.key.replace 来做处理，那么攻击者可以伪造两个 key 让这字段变成数组，这样调用 replace 就报错了。现在的实现方式就是当开发者明确使用数组的形式时，就使用 ctx.queries.key

**Comment by alsotang** [comment]
这一块感觉还可以把撕逼留给标准化组织，比如提供 https://nodejs.org/api/url.html#url_class_urlsearchparams 。至于想取第一个参数还是取出数组，就分别用其中的 `.get` 和 `.getAll`

**Comment by kasora** [comment]
@atian25 请问如何做 extend 呢？似乎 `ctx.query` 字段直接赋值是无效的。会被强制转换成字符串。
有没有什么无痛的方案？因为这样写 `query` 的数据校验真的很麻烦。。

**Comment by atian25** [comment]
看文档 https://eggjs.app/zh-cn/basics/extend.html#request

**Comment by fengmk2** [comment]
ctx.queries
