### ISSUE TITLE
启动时如何打印error

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#2483]
* **Node Version**: v9.11.1
* **Egg Version**:2.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

应用在启动的时候，如果有错误日志，会提示 `save log file to xxxx`

场景：启动错误去文件夹查找日志不方便
期望在启动发生错误的时候，终端也能及时输出日志，不需要从logs文件夹里查找，是否可行。

**Comment by atian25** [comment]
remove `--daemon`
