### ISSUE TITLE
How to serve react based UI in public folder?

### ISSUE THREAD

**Issue by cemremengu** [eggjs/egg#2486]
I have a react front-end that I would like to serve in public folder but it does not serve it for some reason. Could not see anything related in docs.

Is there a way to do this?

**Comment by atian25** [comment]
- does not serve ? could you provide more details?
- https://github.com/eggjs/egg-view-assets
- https://eggjs.org/en/tutorials/assets.html (only Chinese version now)

**Comment by cemremengu** [comment]
Apparently `create-react-app` puts `<noscript>` tags to the prod build so that was the problem
