### ISSUE TITLE
[egg-static] redirect code 206 when request header including range

### ISSUE THREAD

**Issue by Azard** [eggjs/egg#2488]
* **Node Version**: 8.11.1
* **Egg Version**: ALL
* **Plugin Name**: egg-static
* **Plugin Version**: 2.1.0
* **Platform**: MacOS 10.13.3

egg-static adds `koa-range` in middleware, that make our project has some problems.

https://github.com/eggjs/egg-static/pull/13/files#diff-9503e73c6bc0d752ce229b11a8132115

[koa-range](https://github.com/koajs/koa-range/blob/master/index.js) will force modify response status code to `206` in any situations. Before egg-static adds koa-range, the project could response `302` code when redirect. But now it return `206` when redirecting a request that has `range` in headers, the behavior is conflict to [protocols](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).

A simple example to the bug:

```javascript
router.get('/', controller.home.index);
router.get('/redirect', controller.home.redirect);

async index() {
  this.ctx.success('https://somevideo.mp4');
}

async redirect() {
  this.ctx.redirect('/');
}
```

`<video src="localhost:7001/redirect">` gets status code `206` and fail to redirect to the video.

**Comment by fengmk2** [comment]
egg-static 的 perfix 没有生效 https://github.com/eggjs/egg-static/blob/master/config/config.default.js#L18

**Comment by fengmk2** [comment]
得看看是否让 koa-range 支持 prefix 参数 https://github.com/koajs/koa-range/blob/master/index.js#L10，还是 https://github.com/koajs/compose/blob/master/index.js 统一支持一些特殊功能。

**Comment by dead-horse** [comment]
closed by https://github.com/eggjs/egg-static/pull/15
