### ISSUE TITLE
模版如何公用数据

### ISSUE THREAD

**Issue by zsbox** [eggjs/egg#2489]
nunjucks模版
公共头部模版header.tpl 其他页面都引用header.tpl
在header.tpl有一个公共数据 要从数据库中获取的 
问题来了 不管访问哪个页面都要请求一次header中都数据，这样的话每一个controller里都要写同一个数据请求了，无法复用
有什么其他都好版本么？？？？

**Comment by atian25** [comment]
- don't use async render
- read and cache your data to some place such as `app.globalData`
