### ISSUE TITLE
插件文档增加插件名约定规范

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#249]
- [ ] 为何不做唯一限制，view 的实践。目的是为了保障 API 一致可以随便切换
- [ ] plugin.{env}.js

**Comment by atian25** [comment]
这个做了么?

https://eggjs.org/zh-cn/advanced/plugin.html#插件规范

**Comment by popomore** [comment]
还没写

**Comment by atian25** [comment]
plugin.{env}.js 的那个也记录在这里吧
