### ISSUE TITLE
我想在静态资源前在加一层权限判断，但是在设置static插件时发生了错误

### ISSUE THREAD

**Issue by sanriqing** [eggjs/egg#2493]
当我在默认配置中将static中间件放在我的中间件之后，发生了重复的错误。请问有什么解决方法吗

**Comment by sanriqing** [comment]
所以解决方式是我自己在引用下koa的相关插件来完成这件事吗（主要我是想知道如何设置自带插件的顺序）

**Comment by atian25** [comment]
if you want to insert your own middleware before `coreMiddleware`, just unshift to `app.coreMiddleware`, see https://github.com/eggjs/egg-static/blob/master/app.js#L3

warning: only do this when you known what it is.

**Comment by sanriqing** [comment]
3q
