### ISSUE TITLE
eggjs.org site issue

### ISSUE THREAD

**Issue by zhq3k** [eggjs/egg#2497]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

I found a issue in eggjs.org site. 

The site language menu not matched when my browser  default language is en.

please take a look at below image:

![image](https://user-images.githubusercontent.com/34853664/39609009-209a1d80-4f78-11e8-886c-2d39a738c00c.png)

**Comment by atian25** [comment]
it meet you could click it then change to other langs
