### ISSUE TITLE
[vscode plugin] Can not debug with vscode 1.22。Tips `this socket has been ended by other party`

### ISSUE THREAD

**Issue by rccoder** [eggjs/egg#2500]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

VScode 1.22 can not debug with egg plugin，Tips: `this socket has been ended by other party`

Such as: https://cnodejs.org/topic/5acdaa53f474e907e6f7b483

@atian25

**Comment by Jokcy** [comment]
Version 1.23.1 got the same error message. 

Also I update egg-cluster to 1.16.1 and still got the same message

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by Jokcy** [comment]
sorry，I have made a mistake, I was using npm link to debug my own framework and I only update the dep in my app project not the framework, but egg-bin use egg-cluster in framework project.

So it's ok to me now.

**Comment by rccoder** [comment]
@atian25 Good Job
