### ISSUE TITLE
通过调用appLogger的.error()能不能把错误日志输出到appLogger

### ISSUE THREAD

**Issue by leizhao92** [eggjs/egg#2507]
* **Node Version**:8.10.0
* **Egg Version**: 1.4.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

想请教一个问题，目前对于错误日志有这样一个需求：
生产环境下，在代码执行过程中如果有可预见的错误，我会调用.error()输出错误日志，但同时想要日志的有序性便于排查问题。现在的情况是在APPLogger中输出错误日志都直接重定向到errorLogger，和APPLogger里的日志分开了，这样不利于查看追踪日志输出的顺序。有没有什么方法可以自定义把错误日志即重定向到errorlogger又同时输出在APPLogger中便于根据日志的输出顺序排查问题。非常感谢！

**Comment by popomore** [comment]
You can disable this feature by using `redirect` method of the logger, [detail](https://github.com/eggjs/egg-logger/blob/master/lib/logger.js#L94). But don't recommend to do it.
