### ISSUE TITLE
如何获取 worker 的数量

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2508]
是否有办法在 agent 或 app 里获取到 workers 的实际数量?

我尝试在 agent.messager.opids 里获取  但里面拿到的是空数组

**Comment by popomore** [comment]
You can set worker number when start which is equals to cpu number by default.

**Comment by AmazingCaddy** [comment]
> You can set worker number when start which is equals to cpu number by default.

但是启动的时候是可以通过 --workers 来覆盖掉默认的worker个数的，请问，怎么在代码中获取当前的egg cluster的worker总数呢？

**Comment by Mobiusor** [comment]
> > You can set worker number when start which is equals to cpu number by default.
> 
> 但是启动的时候是可以通过 --workers 来覆盖掉默认的worker个数的，请问，怎么在代码中获取当前的egg cluster的worker总数呢？

可以从agent发一条广播，每个worker收到后回一条消息，然后在agent里统计数量😉 @AmazingCaddy

**Comment by AmazingCaddy** [comment]
> > > You can set worker number when start which is equals to cpu number by default.
> > 
> > 
> > 但是启动的时候是可以通过 --workers 来覆盖掉默认的worker个数的，请问，怎么在代码中获取当前的egg cluster的worker总数呢？
> 
> 可以从agent发一条广播，每个worker收到后回一条消息，然后在agent里统计数量😉 @AmazingCaddy

我找到了另外一个比较好的方法，可以从 agent.options.workers 获取
