### ISSUE TITLE
线上项目 egg-passport-github 总是提示redirect_uri_mismatch

### ISSUE THREAD

**Issue by noprom** [eggjs/egg#2509]
* **Node Version**:
8.9.4-alpine
* **Egg Version**:
^2.2.1
* **Plugin Name**:
egg-passport-github
* **Plugin Version**:
^1.0.0
* **Platform**:
ubuntu
* **Mini Showcase Repository**:
egg-passport-github作如下配置:
```
  config.passportGithub = {
    key: process.env.EGG_PASSPORT_GITHUB_CLIENT_ID,
    secret: process.env.EGG_PASSPORT_GITHUB_CLIENT_SECRET,
    callbackURL: 'https://eosdevs.io/passport/github/callback',
  };
```
这里保证`key`和`secret`没有问题, `callbackURL`在github中配置如下:
![image](https://user-images.githubusercontent.com/8455444/39663123-dec55130-509f-11e8-8334-0f8183aaae85.png)
即`https://eosdevs.io/passport/github/callback`,
但是线上项目`https://eosdevs.io`的使用github登陆总是提示`redirect_uri_mismatch`。
经过抓包发现,
![image](https://user-images.githubusercontent.com/8455444/39663143-5961e476-50a0-11e8-86b3-45c9820c4a6e.png)
期望能得到解答。

**Comment by popomore** [comment]
@thonatos

**Comment by thonatos** [comment]
可以参考下面的配置。

## github

<img width="566" alt="2018-05-06 10 22 03" src="https://user-images.githubusercontent.com/958063/39674279-051d0922-517c-11e8-99a3-8b55c00f26ec.png">

## egg.js

```
// passport
config.passportGithub = {
    key: process.env.EGG_PASSPORT_GITHUB_CLIENT_ID || 'test',
    secret: process.env.EGG_PASSPORT_GITHUB_CLIENT_SECRET || 'test',
    callbackURL: process.env.EGG_PASSPORT_GITHUB_CALLBACK_URL || '/passport/github/callback',
    proxy: process.env.EGG_PROXY === 'proxy',
};
```

- [config.default.js#L34](https://github.com/ImplementsIO/dockerizer/blob/930b5ca34bab77589f60541e33fe10be1d6f1641/config/config.default.js#L34)

**Comment by noprom** [comment]
@thonatos 
现在的配置是这样:
### config.default.js
```
  // passport
  config.passportGithub = {
    key: process.env.EGG_PASSPORT_GITHUB_CLIENT_ID || 'test',
    secret: process.env.EGG_PASSPORT_GITHUB_CLIENT_SECRET || 'test',
    callbackURL: '/passport/github/callback',
  };
```
### Github
![image](https://user-images.githubusercontent.com/8455444/39680618-412131f6-51d5-11e8-828b-af9b10e64bbb.png)

更新之后，从egg发出的请求仍然是http而不是https:
![image](https://user-images.githubusercontent.com/8455444/39680631-6de63632-51d5-11e8-8aca-61a88910a9a5.png)
您可以在线体验一下: `https://eosdevs.io`。

**Comment by thonatos** [comment]
项目前面是不是有反向代理？如果有的话，添加一下：

```js
proxy = true;
```

> 如果 lb 后端用 http，插件在判断前缀时候则可能一直得到是 http

回调地址可以写固定：

```js
callbackURL = 'https://dockerizer.implements.io/passport/github/callback';
```

- [passport-oauth2 utils.js](https://github.com/jaredhanson/passport-oauth2/blob/a9480960be04ac5312f9eae2a6d06d0e8d0e5dda/lib/utils.js)

**Comment by noprom** [comment]
@thonatos 
现在的配置是这样:
### config.default.js
```
  // passport
  config.passportGithub = {
    key: process.env.EGG_PASSPORT_GITHUB_CLIENT_ID || 'test',
    secret: process.env.EGG_PASSPORT_GITHUB_CLIENT_SECRET || 'test',
    callbackURL: 'https://eosdevs.io/passport/github/callback',
    proxy: true
  };
```

### Github
![image](https://user-images.githubusercontent.com/8455444/39733748-c633d1d8-52a6-11e8-9d64-ee94717f06bf.png)
仍然不能解决问题。
我的项目在node前面加了gce的负载均衡，采用kubernetes部署，不知道您能否帮我看看缺少了哪些需要传递的参数导致插件一直判断得到的是http?

**Comment by thonatos** [comment]
我上面给出的地址里有写如何判断，你打印日志看看获取到的 header 是否正确，那段代码里有判断方法的。

**Comment by noprom** [comment]
@thonatos
下面这个仍然是访问的`http`, 能加一个联系方式具体帮忙看一下吗？
![image](https://user-images.githubusercontent.com/8455444/39812445-4d6c2ad8-53bf-11e8-9554-f342f3920b17.png)

**Comment by thonatos** [comment]
下面有我微信。

- https://github.com/eggjs-community/README

**Comment by noprom** [comment]
加了，请通过一下吧 @thonatos
