### ISSUE TITLE
ERROR 75082 nodejs.ClusterClientNoResponseError: client no response

### ISSUE THREAD

**Issue by runhwguo** [eggjs/egg#2510]
* **Node Version**:v10.0.0
* **Egg Version**:2.7.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:
看了所有关于这个问题的issue，好像都没有解决。我这边就是一个定时任务，然后去执行一个耗时任务。程序启动大约4个小时左右，就会复现这个问题。

**Comment by runhwguo** [comment]
最后发现是自己逻辑里有死循环。

**Comment by atian25** [comment]
这个问题绝大部分情况都是 cpu 占用太高导致没时间发心跳
