### ISSUE TITLE
路由命中多个app.router.get对应controller间怎样交互

### ISSUE THREAD

**Issue by fuufuuf** [eggjs/egg#2511]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

如果一个请求/test, 命中多个router app.router.get('/*', c1) and app.router.get('/test', c2), 由于controller对应方法没有next参数，无法await next(), 导致c1和c2之间无法交互。请问是这样的么

**Comment by popomore** [comment]
Yes, only one route will be matched, You need write a middleware.
