### ISSUE TITLE
ctx.body未及时返回，response超时

### ISSUE THREAD

**Issue by vosonwang** [eggjs/egg#2512]
我想了下我目前的问题和执行环境并没有关联，所以就不提供执行环境信息了。

我翻看了一些issue，网上也查了很久，没想到问题所在，麻烦看下

```

// 我预想程序按顺序执行，到此处，直接返回响应，下面的查重工作让程序继续执行，但实际上，一直要等到for循环结束之后，才会返回response

ctx.body={status:'开始表格内查重...'}

// 开始一个会耗时很久的表格内查重
for(){
...
}

````

具体代码：https://coding.net/u/voson/p/messeinfor-import-wizard/git/blob/dev/app/controller/task.js?public=true

**Comment by killagu** [comment]
It work as expected, response will write after the controller and middlewares executed. If you wish to not block the response, you can use [runInBackground](https://eggjs.org/api/Application.html#runInBackground).
