### ISSUE TITLE
[egg-mongoose] Update mongoose

### ISSUE THREAD

**Issue by leaves4j** [eggjs/egg#2514]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**: egg-mongoose
* **Plugin Version**:2.2.0
* **Platform**:
* **Mini Showcase Repository**:

Can we update mongoose to 5.0 or change mongoose to `peerDependencies`?

**Comment by thonatos** [comment]
- https://github.com/eggjs/egg-mongoose/pull/20
