### ISSUE TITLE
egg-passport-local，how to set response body?

### ISSUE THREAD

**Issue by luruidan** [eggjs/egg#2515]
Egg，我是用来做RESTful，api服务器，所以返回成功或失败跳转，意义不大

```
 app.passport.verify(async (ctx, user) => {
    ctx.logger.debug('passport.verify', user)

    // 我试过下面的方案，不行
    if (true) {
      ctx.body = { status: 'success' }
    } else {
      ctx.body = { status: 'error' }
    }

    // 下面这样的写法，也不行
    const err = new Error('错误了');
    err.code = 'error_code';
    throw err

    // return existUser
    return user
  })
```
我是配合 ant design pro用的。登录成功后，跳转页面，也是由ant design pro判断status来处理的。如果status === 'error'，我会返回额外信息，由ant design pro页面提示错误，比如密码不正确

**Comment by luruidan** [comment]
我是配合 ant design pro用的。登录成功后，跳转页面，也是有ant design pro判断status来处理的。如果status === 'error'，我会返回额外信息，有ant design pro页面提示错误，比如密码不正确

**Comment by chengnuo** [comment]
i have same problem。

**Comment by luruidan** [comment]
还有一个疑问，这个验证，无论成功或者失败，都是返回302。我可以修改为，返回200吗？

**Comment by chengnuo** [comment]
// 鉴权
  const localStrategy = app.passport.authenticate('local', {
    successRedirect: '/',
    failureRedirect: '/api/signIn'
  });

跳到相应的（api）页面应该可以处理，verify里面只是校验。这种方式虽然可以。但是好像开发思路有点不直观。

**Comment by luruidan** [comment]
我设计的流程是，如果验证失败，return null，body={ status: 'error', type: 'password' }。
我前端接收到返回的body，就可以渲染页面，提示密码错误，不需要跳转

**Comment by chengnuo** [comment]
http://www.passportjs.org/docs/login/ 可以看看这个，看看有没有解决方案了。

**Comment by luruidan** [comment]
好的，我看看去

**Comment by luruidan** [comment]
@fengmk2 @popomore 大神，求助哈

**Comment by luruidan** [comment]
谢谢，egg-cnode这个我之前看过了。刚粗略看了下passport和passport-local的源码，想实现我设想的功能，需要改源码，默认是实现不了的

**Comment by luruidan** [comment]
仔细看了下源码，如果直接用passport和passport-local，可以通过callback来实现。但是，egg-passport不支持传递callback，下面代码摘自egg-passport/lib/framework.js

```
function authenticate(passport, name, options) {
  // Don't support authenticate with callback

  // function authenticate(req, res, next)
  const connectMiddleware = connectFramework.authenticate(passport, name, options);

  debug('use authenticate:%s, options: %j', name, options);
```
要想增加支持callback，还是有难度的，主要是callback里需要用到next函数，而这个不好传递。passport是通过闭包来实现传递的

@fengmk2 @popomore 大神给点建议哈

**Comment by dd0754** [comment]
没登陆直接抛出可以参考egg-cnode的user_required中间件

[user_required.js](https://github.com/cnodejs/egg-cnode/blob/ac01b489a2e1b4837cbc3ecb9cb512f2e1a3e255/app/middleware/user_required.js)

**Comment by atian25** [comment]
其实如果只是账号登陆的话，都没必要用 passport-local，自己做一个 post 就完事了。

Passport 是设计来给第三方登陆用的。

**Comment by luruidan** [comment]
我在node_modules\_passport@0.3.2@passport\lib\middleware\authenticate.js手工硬加入下面代码，就可以了。先凑合着用，后面再想办法，第三方登录是需要的，想统一登录，所以想用passport
```
  return function authenticate(req, res, next) {
    if (http.IncomingMessage.prototype.logIn
        && http.IncomingMessage.prototype.logIn !== IncomingMessageExt.logIn) {
      require('../framework/connect').__monkeypatchNode();
    }
    
    **callback = function(err, user, info) {
      if (err) { return next(err) }

      if (user.error) {
        return res.end(user.body)
      }

      req.logIn(user, function(err) {
        if (err) { return next(err) }
        return res.end(user.body)
      })
    }**

    // accumulator for failures from each strategy in the chain
    var failures = [];

```

**Comment by atian25** [comment]
node_modules 一般不要动，npm update 一下就没了。

**Comment by atian25** [comment]
没啥必要统一

**Comment by luruidan** [comment]
明白了，那我不用了，还是直接单独写个post吧，谢谢

**Comment by DoranYun** [comment]
其实可以给 app.passport.authenticate 包成一个 promise，通过中间件的方式在 route 中使用，就可以直接返回 json 了。

```
// middleware/auth.js

'use strict';

module.exports = () => {
  return async function(ctx, next) {
    const app = ctx.app;
    if (app.passport) {
      const localStrategy = new Promise(resolve => {
        app.passport.authenticate('local', (err, user) => {
          if (err) {
            resolve({ success: false, message: err });
          }

          if (!user) {
            resolve({ success: false, message: 'current user not exit.' });
          }

          resolve(user);
        })(ctx);
      });

      ctx.body = await localStrategy.then(res => res);
      await next();
    }
  };
};
```

**Comment by whlsxl** [comment]
@atian25 我觉得对于passport来说，这个密码登录的功能可能没特别的必要。不过保持koa插件功能完整还是很有必要的。不过我看以现在egg把插件功能打散这种方式，可能有些功能实现起来有些麻烦。

**Comment by whlsxl** [comment]
现在我的解决方法是，
```
const localStrategy = app.passport.authenticate('local', { successRedirect: '/login', failureRedirect: '/login' })
  router.post('/login', localStrategy);
  router.get('/login', controller.user.login);
```
然后在get login 里返回用户信息，或者401
其实这样的接口非常不restful，不过暂时先这么解决吧

**Comment by mywei1989** [comment]
我的做法是 自己判断登录 然后
ctx.login(user); 传给passport(用于利用 sessiong 和 登录验证方法ctx.isAuthenticated)
`
async login() {
  if(true){
    ctx.login(user)
  }
}

 async currentUser() {
    const { ctx } = this;
    if (ctx.isAuthenticated()) {
      ctx.body= {username:'aaa'}; 
  }else{
    ctx.response.status = 401;
  }
}

`
