### ISSUE TITLE
配置 graylog2 后删除配置，之后重新下载模版npm run start均 报此错误。项目本地 dev 能正确运行。

### ISSUE THREAD

**Issue by ranyue** [eggjs/egg#2517]
egg-scripts] 2018-05-07 15:41:50,935 ERROR 4643 [app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE
[egg-scripts] 2018-05-07 15:41:50,935 ERROR 4643 [app_worker] exit with code:1
[egg-scripts] 2018-05-07 15:41:50,936 ERROR 4642 [app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE
[egg-scripts] 2018-05-07 15:41:50,936 ERROR 4642 [app_worker] exit with code:1
[egg-scripts] 2018-05-07 15:41:50,947 ERROR 4639 nodejs.AppWorkerDiedError: [master] app_worker#1:4642 died (code: 1, signal: null, suicide: false,state: dead), current workers: ["2","3","4"]
[egg-scripts]     at Master.onAppExit (/Users/liyong/node/egg-example/node_modules/_egg-cluster@1.16.0@egg-cluster/lib/master.js:387:21)
[egg-scripts]     at Master.emit (events.js:180:13)
[egg-scripts]     at Messenger.sendToMaster (/Users/liyong/node/egg-example/node_modules/_egg-cluster@1.16.0@egg-cluster/lib/utils/messenger.js:122:17)
[egg-scripts]     at Messenger.send (/Users/liyong/node/egg-example/node_modules/_egg-cluster@1.16.0@egg-cluster/lib/utils/messenger.js:87:12)
[egg-scripts]     at EventEmitter.cluster.on (/Users/liyong/node/egg-example/node_modules/_egg-cluster@1.16.0@egg-cluster/lib/master.js:264:22)
[egg-scripts]     at EventEmitter.emit (events.js:185:15)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:194:13)
[egg-scripts]     at Object.onceWrapper (events.js:272:13)
[egg-scripts]     at ChildProcess.emit (events.js:180:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
[egg-scripts] name: 'AppWorkerDiedError'
[egg-scripts] pid: 4639
[egg-scripts] hostname: liyongdeMacBook-Pro.local
[egg-scripts]
[egg-scripts] 2018-05-07 15:41:50,948 ERROR 4639 [master] app_worker#1:4642 start fail, exiting with code:1
[egg-scripts] 2018-05-07 15:41:50,948 ERROR 4639 [master] exit with code:1
[egg-scripts] 2018-05-07 15:41:50,952 ERROR 4641 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2018-05-07 15:41:50,952 ERROR 4645 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts] 2018-05-07 15:41:50,956 ERROR 4641 [agent_worker] exit with code:110
[egg-scripts] 2018-05-07 15:41:50,960 ERROR 4644 [app_worker] receive disconnect event in cluster fork mode, exitedAfterDisconnect:false
[egg-scripts]
[egg-scripts] Start got error, see /Users/liyong/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@1.0.0 start: `egg-scripts start --daemon --title=egg-server-example`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liyong/.npm/_logs/2018-05-07T07_41_52_329Z-debug.log

**Comment by ranyue** [comment]
未 修改任何 官方 simple 模版配置。

**Comment by atian25** [comment]
`server got error: bind EADDRINUSE null:7001, code: EADDRINUSE`

**Comment by ranyue** [comment]
非常感谢
