### ISSUE TITLE
Cluster在egg 中的使用

### ISSUE THREAD

**Issue by vosonwang** [eggjs/egg#2518]
我用egg做数据库的查重，运算量有些大，一旦开始查重，直接导致CPU 100%。程序的其他接口都没有响应。我想应该是可以通过Cluster开启多个CPU来应付这种情况。我的想法是，在任务队列中同一时间可以开2个worker，在它们跑满CPU的同时，用户能够正常访问其他接口。

我查看了“多进程模型和进程间通讯”，“多进程研发模式增强”，自己也写了测试做了试验，对如何在egg中使用Cluster，还是有点不解。我是需要在根目录下新建app.js这样的文件独立写查重的方法，然后在worker中调用吗？有这方面的实例可以参考吗？

我查了一整天，还是没有能够找到解决方法。这个问题困扰了我很久，如果能给些指引真是太感谢了。

**Comment by vosonwang** [comment]
code:
https://coding.net/u/voson/p/messeinfor-import-wizard/git/blob/dev/app/controller/task.js?public=true

**Comment by popomore** [comment]
cpu 100% 在哪里都是不可以接受的，你需要离线计算。

**Comment by vosonwang** [comment]
我描述没准确，场景是：用户导入10万条数据（多用户导入需要排队），与mysql中20万条数据，比较查重，整个查重过程 egg大约用了15分钟，稍后服务恢复正常，请问这样也需要离线计算吗？这是所有语言框架不能避免的吗？

**Comment by liuqipeng417** [comment]
服务器上的多核，与 worker 并不是一一对应的，例如 worker A 可能同时再使用 CPU 1、2、3、4，无法控制 某个 worker 跑满某个 cpu。
一般这类排重服务跟接口服务可以分开来

**Comment by vosonwang** [comment]
谢谢你们的回复。我会考虑分离排重服务。
