### ISSUE TITLE
日志给第三方服务 目前不支持 agentLogger,  appLogger

### ISSUE THREAD

**Issue by ranyue** [eggjs/egg#2519]
app.getLogger('appLogger')  打印显示 为null。
app.getLogger('agentLogger')  打印显示 为null。

**Comment by dead-horse** [comment]
egg don't provider these logger by default.

**Comment by wv1124** [comment]
郁闷半天，发现真是没办法把agent的日志写到kafka，我现发消息到master进程去写
  private log() {
    return {
      info: (msg) => {
        this.agent.messenger.sendRandom('AgentLog_Info', msg);
      },
      error: (msg) => {
        this.agent.messenger.sendRandom('AgentLog_Error', msg);
      },
      debug: (msg) => {
        this.agent.messenger.sendRandom('AgentLog_Debug', msg);
      },
      warn: (msg) => {
        this.agent.messenger.sendRandom('AgentLog_Warn', msg);
      },
    };
  }
