### ISSUE TITLE
egg-static-plugin conflict with egg-passport

### ISSUE THREAD

**Issue by fuufuuf** [eggjs/egg#2523]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

使用egg-static-plugin后，静态html文件请求不能被中间见拿到，从而不能实现passport鉴权。有办法在现有framework中拿到静态文件请求而后处理判断吗

**Comment by popomore** [comment]
You can use egg-view to host your html.
