### ISSUE TITLE
egg项目自动化版本控制

### ISSUE THREAD

**Issue by jjackychen** [eggjs/egg#2524]
项目页面上需要显示当前项目的版本号，每次更新都要手动写一个，egg有插件可以自动生成项目的版本号吗？

**Comment by jjackychen** [comment]
I mean my project each release has a release version number like V1.0.0(2018050901), but my project must show this version number in the html file. Now, each release I must be manually written the release version number in the html file. If a egg plug-in can help me automatically generate the release version number in the html file instead of  manually written the release version number.

**Comment by atian25** [comment]
it's not a responsibility of egg, you can write your own logic to do this as your wish.

why not just use `package.json` 's `version` ? you could bump version by `npm version` at release
