### ISSUE TITLE
egg环境变量配置问题

### ISSUE THREAD

**Issue by yuany24** [eggjs/egg#2526]
您好：
是直接使用命令：npx egg-init --type=ts showcase 集成的项目，这个集成的项目默认的启动路径为：127.0.0.1:7001   想用config里的文件配置修改启动路径和端口，config里的文件配置如下：
//config.default.ts
import {EggAppConfig, PowerPartial} from 'egg';
export type DefaultConfig = PowerPartial<EggAppConfig & BizConfig>;
export interface BizConfig {
    sourceUrl: string;
}
export default (appInfo: EggAppConfig) => {
    const config = {} as PowerPartial<EggAppConfig> & BizConfig;
    config.sourceUrl = `https://github.com/eggjs/examples/tree/master/${appInfo.name}`;
    config.keys = appInfo.name +'1525415192797_1826'; //'_1525233401890_8434';
    config.middleware = [];
    appInfo.env = 'dev';
    return config;
};
//config.local.ts
import {DefaultConfig} from './config.default';
export default () => {
    const config: DefaultConfig = {
        listen:{
            mongodb: 'mongodb://192.168.3.248:27017/rsc_main',
            hostname: '192.168.3.248',
            port: 18080,
            port_https: 17080,
            is_sms: true,
        },
    };
    return config;
};
//config.prod.ts
import { DefaultConfig } from './config.default';
export default () => {
  const config: DefaultConfig = {
      listen:{
          mongodb: 'mongodb://rscdba:a11111@localhost:27033/rsc_main',
          hostname: '60.205.146.196',
          port: 18010,
          port_https: 17010,
          is_sms: true ,
    },
  };
  return config;
};
//plugin.ts
import { EggPlugin } from 'egg';
const plugin: EggPlugin = {
  // static: true,
  // nunjucks: {
  //   enable: true,
  //   package: 'egg-view-nunjucks',
  // },
};
export default plugin;

**Comment by popomore** [comment]
You can't change on local.

**Comment by yuany24** [comment]
好的，明白了，谢谢
