### ISSUE TITLE
请问单独的模块放在哪里进行处理

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#2528]
有一组数据，想在service层去维护它，几个service都想使用和修改
那么在egg中，这组数据和它的方法要放在哪里？
目前是放在service 目录下，但是感觉不合理

**Comment by popomore** [comment]
和 egg 无关，都可以处理

**Comment by hezhongfeng** [comment]
好吧，感谢

**Comment by atian25** [comment]
you could place it at `lib/**`

**Comment by hezhongfeng** [comment]
@atian25 
好的
