### ISSUE TITLE
线上运行中，日志被移动到其他路径下了，请问是什么原因？

### ISSUE THREAD

**Issue by Cheese-Yu** [eggjs/egg#2530]
* **Node Version**:v8.11.0
* **Egg Version**:v2.0.0
* **Plugin Name**:egg-logger
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

项目在15:35:53启动的项目，日志文件夹是/root/logs/下。17:56左右的时候，整个日志文件被移动到了/etc/下，而且仍然在正常记录。

这个服务器上我同时部署了两个项目，另一个项目的日志文件夹没有移动。区别是被移动日志的项目部署了alinode,其他是一样的。

这期间，我添加了两个监控端口的脚本。
查看了master的日志没有任何更新，不清楚是什么原因造成的。请各位大佬赐教，谢谢~

**Comment by atian25** [comment]
check your machine.
egg wont do these by default

**Comment by Cheese-Yu** [comment]
如果是人为的移动或者服务器的移动，egg-logger应该是不会跟随到移动了的位置继续记录的吧？

**Comment by Cheese-Yu** [comment]
我把/etc/下的日志文件夹复制了一份在之前的路径，新的一天又重新在之前的路径记录了。这期间没再动过其他东西了。

**Comment by atian25** [comment]
用 egg-init 初始化一个空项目，加 alinode，那是否复现

**Comment by iamgaohui** [comment]
官方：所有日志文件默认都放在 ${appInfo.root}/logs/${appInfo.name} 路径下，我看了下config.default.js AppInfo里是没有root这个选项的，所以可能导致路径出错。我建议用他们日志路径配置一下。

// config/config.${env}.js
exports.logger = {  dir: '/path/to/your/custom/log/dir',};

**Comment by atian25** [comment]
不可能没有 appInfo

**Comment by dead-horse** [comment]
检查一下 `run/application_config.json` 中真实使用的 logger 配置. https://eggjs.org/zh-cn/faq.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by Cheese-Yu** [comment]
```run/application_config.json``` 里的配置。这种情况也没有复现。可以先关了，有状况我会再更新。
``` 
"logger": {
      "dir": "/root/logs/payTest",
      "encoding": "utf8",
      "env": "prod",
      "level": "INFO",
      "consoleLevel": "INFO",
      "disableConsoleAfterReady": true,
      "outputJSON": false,
      "buffer": true,
      "appLogName": "payTest-web.log",
      "coreLogName": "egg-web.log",
      "agentLogName": "egg-agent.log",
      "errorLogName": "common-error.log",
      "coreLogger": {},
      "allowDebugAtProd": true,
      "type": "application"
    }
```
