### ISSUE TITLE
如何在一个 worker 里获得其他 worker 的进程 id

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2534]
app.messenger.sendTo(pid, action, data)

这个方法需要知道对方worker 的 pid
如何知道其他进程的 pid ?

agent 里能拿到所有 worker 的进程 id 吗

**Comment by atian25** [comment]
workers should not know each other.

**Comment by dead-horse** [comment]
应用层不建议直接使用这个方法
