### ISSUE TITLE
有没有 typescript 写 framework 的相关例子？

### ISSUE THREAD

**Issue by seekcx** [eggjs/egg#2536]
最初想直接用 ts 来写框架，没有找到模板，也不太清楚怎么配置类似于 `dev` 的 watch。
所以放弃了，暂时打算用js来写 framework。但是业务层是使用ts写的。

业务层添加了框架之后，`egg-ts-helper` 能够识别框架：

```js
// typings/app/service/index.d.ts

declare module 'framework' {
  interface IService {
  }
}
```

所以 service 的声明变成了这样。

所有 service 都报错了，
![image](https://user-images.githubusercontent.com/8244814/39863841-636c52e8-547a-11e8-84a0-caf729baf379.png)

更改 service 文件

```js
import { Service } from 'framework';
```

service 里的引用也随即报错：
![image](https://user-images.githubusercontent.com/8244814/39863929-b034fe4a-547a-11e8-801d-378a645f3117.png)

不知道有没有类似例子可以借鉴一下

**Comment by whxaxes** [comment]
https://github.com/whxaxes/egg-boilerplate-d-ts

**Comment by whxaxes** [comment]
https://github.com/eggjs/examples/tree/master/hackernews-async-ts
