### ISSUE TITLE
请问手动启动egg时如何才能得到application对象?

### ISSUE THREAD

**Issue by xingyuzhe** [eggjs/egg#2538]
### bin/run.ts:
```
const masterInstance = new Master({
  workers: 1,
  baseDir
})

masterInstance.ready(async () => {
  // 这里可以得到master, agent, app进程
  // ... 但是如何得到创建的application对象呢?
  await app.doSomething()
  app.close()
})
```

### package.json
```
cmd-xxx:  "ts-node bin/run.ts" 
```

是这样,  我想在application环境下处理一些任务, 但是只是作为package.json里的一条命令执行, 不对其它地方造成影响。所以我需要手动启动egg。之前我移除了cluster模块直接启动application是可以的。 但是直接使用egg的话, 只能通过cluster启动；但是我不知如何才能得到application对象。

如果有别的独立运行egg的方式也请赐教

## 补充1:
我想达到这样的目的:

```
yarn cmd-xxx
```
然后bin/run.ts里就会调用egg application下的方法。这样我就能使用当前egg项目的API去完成一些任务。我想到的是另行启动一个egg实例, 任务运行完毕后退出app。 这些能帮我省不少事。

**Comment by atian25** [comment]
> 我想在application环境下处理一些任务, 但是只是作为package.json里的一条命令执行, 不对其它地方造成影响。

没看懂

**Comment by dead-horse** [comment]
命令行工具不建议用此种方式实现
