### ISSUE TITLE
指定日志路径，默认路径还会出现master的日志

### ISSUE THREAD

**Issue by hearAllParties** [eggjs/egg#2539]
* **Node Version**:  v7.6.0
* **Egg Version**:  egg@1.15.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

服务器生产环境配置：
```javascript
config.logger = {
    outputJSON: true,
    dir: '/var/log/xxxx',
  };
```
日志文件的确生成到服务器`/var/log/xxxx`路径下，此路径下的内容都是logger的日志；
但是服务器默认路径下`/root/logs/xxxx`也会生成日志文件，此路径下的文件名为`master-stdout.log`和`master-stderr.log`，内容都是console.log的日志。
各位大佬，请问怎么移除默认路径下的日志，或者把master下的日志也可以生成到默认的地址

**Comment by atian25** [comment]
see [egg-scripts](https://github.com/eggjs/egg-scripts) README, `--stdout= --stderr=`

**Comment by hearAllParties** [comment]
感谢天猪 @atian25 。另外，看了script代码，好像stdout和stderr一定会生成，可以不生成这两个文件吗？

**Comment by atian25** [comment]
unless you remove `--daemon` which will let your process run at background, and that's why you need master log file otherwise you will lost the startup message.

**Comment by hearAllParties** [comment]
i see. thx~

**Comment by zhump** [comment]
```
线上的日志打印去哪里了？
默认配置下，本地开发环境的日志都会打印在应用根目录的 logs 文件夹下(${baseDir}/logs) ，但是在非开发期的环境（非 local 和 unittest 环境），所有的日志都会打印到 $HOME/logs 文件夹下（例如 /home/admin/logs）。这样可以让本地开发时应用日志互不影响，服务器运行时又有统一的日志输出目录。
```
意思就是说不支持配置生产环境日志地址是吗？ @atian25

**Comment by atian25** [comment]
可以配，那只是默认值。

**Comment by xiaoshieefocus** [comment]
所以说 在daemon情况下 没有办法让master日志不出现是么？  我尝试把--stdout和--stderr指向/dev/null，但是他直接把/dev/null当成文件路径，尝试去把/dev/null rotate成/dev/null.xxxx.xxx 了 自然就失败了。 看来是不行的。

**Comment by atian25** [comment]
daemon 方式为什么要把日志干掉呢？出了问题就没法排查。

**Comment by xiaoshieefocus** [comment]
因为我把所有日志放一起然后禁用了egg里的rotate，跟其他项目日志统一用logrotate了，但是master日志没有办法禁止他的自动rorate，造成一丢丢混乱。目前我是在rotate脚本里删除egg自己生成的rotate副本然后再开始logrotate的工作。也是可以接受啦。。。
