### ISSUE TITLE
egg-ant-design-pro 编译问题

### ISSUE THREAD

**Issue by lu592674374** [eggjs/egg#2540]
* **Node Version**: 8.9.4
* **Egg Version**: 2.8.1
* **Plugin Name**: egg-ant-design-pro
* **Plugin Version**: 1.0.0
* **Platform**: win10
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/15523855/39824729-9d94ebf8-53e2-11e8-96dc-2c741ed1fe4c.png)

https://github.com/eggjs/egg-ant-design-pro  在npm run dev时候报上面的错误

**Comment by popomore** [comment]
You should report error to ant-desigon-pro

**Comment by zhangzhaoaaa** [comment]
@popomore 这个问题ant-design-pro 已经解决了

https://github.com/ant-design/ant-design-pro/pull/1345

egg-ant-design-pro里，需要在.webpackrc中删掉"transform-decorators-legacy"这个配置，在项目编译过程中，才不会报上面那个错

所以，建议在项目里去除这个配置，对使用本项目的人来说或许更友好

**Comment by atian25** [comment]
@zhangzhaoaaa  来个 PR~
