### ISSUE TITLE
关于egg插件详细文档的问题

### ISSUE THREAD

**Issue by 15652768278** [eggjs/egg#2541]
项目中用到了egg-jwt插件，看readme还有些疑惑，比如：
app.get("/success", "success.index"); // is setting in config.jwt.match
其中的config.jwt.match完整配置和参数想了解下，不知道哪里有文档，求各位大神指点一下

**Comment by okoala** [comment]
@15652768278 看 Middleware 中间件这一章
https://eggjs.org/zh-cn/basics/middleware.html#%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE

**Comment by 15652768278** [comment]
谢谢指点

**Comment by 15652768278** [comment]
谢谢
