### ISSUE TITLE
egg项目布到内网服务器后访问接口404

### ISSUE THREAD

**Issue by yuany24** [eggjs/egg#2543]
您好，请问egg项目布到内网服务器后，访问接口出错404错误，但是看服务器的日志显示已经启动服务成功，服务器的日志： 2018-05-11 12:55:38,778 INFO 10616 [master] egg started on http://127.0.0.1:3089 (1694ms)，使用pm2 start index.js启动，麻烦大神看下，具体代码如下：
1.index.js
require('egg').startCluster({
    baseDir: __dirname,
    port: 3089,
    workers: 1, // default to cpu count
    hostHeaders:'x-forwarded-host',
    proxy:true
});
2.package.json
{
  "name": "egg-init",
  "version": "1.0.0",
  "description": "1.0.0",
  "private": true,
  "egg": {
    "typescript": true
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-egg-init",
    "stop": "egg-scripts stop --title=egg-server-egg-init",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug -r egg-ts-helper/register",
    "cov": "egg-bin cov -r egg-ts-helper/register",
    "tsc": "ets && tsc -p tsconfig.json",
    "ci": "npm run lint && npm run cov && npm run tsc",
    "autod": "autod",
    "lint": "tslint .",
    "clean": "ets clean"
  },
  "dependencies": {
    "@types/body-parser": "^1.17.0",
    "@types/jsonwebtoken": "^7.2.7",
    "@types/mongoose": "^5.0.12",
    "@types/morgan": "^1.7.35",
    "@types/underscore": "^1.8.8",
    "egg": "^2.6.1",
    "egg-logger": "^1.6.2",
    "egg-mongoose": "^2.2.1",
    "egg-scripts": "^2.6.0",
    "fs": "0.0.1-security",
    "jsonwebtoken": "^8.2.1",
    "morgan": "^1.9.0",
    "underscore": "^1.9.0"
  },
  "devDependencies": {
    "@types/mocha": "^2.2.40",
    "@types/node": "^7.0.12",
    "@types/supertest": "^2.0.0",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-ci": "^1.8.0",
    "egg-bin": "^4.6.2",
    "egg-mock": "^3.16.0",
    "egg-ts-helper": "^1.4.2",
    "tslib": "^1.9.0",
    "tslint": "^4.0.0",
    "typescript": "^2.8.1"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "ci": {
    "version": "8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "eslintIgnore": [
    "coverage"
  ],
  "author": "driver",
  "license": "MIT"
}

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by popomore** [comment]
这个自己排查下吧，应该没有关系，有更具体信息再开。

**Comment by yuany24** [comment]
项目已提交，地址：https://github.com/yuany24/egg-example.git

**Comment by atian25** [comment]
ts 的话，直接用 egg-scripts 启动，为啥要用 index.js 这个早就废弃的东西。
PM2 没有任何必要使用。

**Comment by yuany24** [comment]
谢谢，明白了，因为之前是使用pm2，因为要使用pm2所以才写了一个启动文件index.js。
