### ISSUE TITLE
设置nyc coverage格式

### ISSUE THREAD

**Issue by wangxuepeng** [eggjs/egg#2549]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

文档里讲到可以使用npm run cov生成单元测试覆盖率报告。但是默认的格式是HTML。

nyc支持多种报告格式：
clover, cobertura, html, json-summary, json, lcov, lcovonly, none, teamcity, text-lcov, text-summary, text

请问npm run cov如何指定报告格式？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js#L105

默认有生成这几个了

**Comment by wangxuepeng** [comment]
Saw it. Thanks very much!

**Comment by atian25** [comment]
also, you could config `package.json`

https://github.com/istanbuljs/nyc#configuring-nyc

**Comment by wangxuepeng** [comment]
Hi,
I tried this but it does not work. 

I placed a `.nycrc` file under root and run `yarn cov`, none of the settings work. 

I checked file [https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js](https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js) and see all settings seems are fixed.

**Comment by wangxuepeng** [comment]
OK, after further tests, I found that only the settings not set in [https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js](https://github.com/eggjs/egg-bin/blob/master/lib/cmd/cov.js ) work. e.g., for below configuration:

  ```
{
    "reporter": [
      "text"
    ],
    "report-dir": "./alternative"
  }
```

`report-dir` dose take affect, but `reporter` format dose not work, it still generate 4 reports under 'alternative' folder.

**Comment by atian25** [comment]
well, so could you check `nyc` resource to find if there is any way to adjust `egg-bin cov` ?
PR is welcome

**Comment by wangxuepeng** [comment]
The default configuration is good enough for production use, I will look this if further needs raise.
