### ISSUE TITLE
ejs 模板引擎错误

### ISSUE THREAD

**Issue by spitWind** [eggjs/egg#2552]
* **Node Version**: 9.5
* **Egg Version**:2.8
* **Plugin Name**:egg-view-ejs
* **Plugin Version**:2.0.0
* **Platform**:win7
* **Mini Showcase Repository**:d

我在ejs 模板引擎渲染 遇到 404 Not Found
其中
`exports.ejs = {
  enable: true,
  package: 'egg-view-ejs'
};

  config.view = {
    defaultViewEngine: '.ejs',
    mapping: {
      '.ejs': 'ejs'
    }
  };

this.ctx.render("./test")`

模板文件:

`<% for(var i=0;i<10;i++ ){%>
你好世界;!
<%
}
%>`
`
  async render(filename, locals, viewOptions) {
    const config = Object.assign({}, this.config, viewOptions, { filename });
    const html = await this[RENDER](filename, locals, config);
    if (!config.layout) {
      return html;
    }
    locals.body = html;
    const layout = await this.app.view.resolve(config.layout);
    return this[RENDER](layout, locals, config);
  }
`
html值是正常输出的.. 后面还是没有渲染到 bodY 
渲染后结果是 404 no fouund
帮忙看看?

**Comment by atian25** [comment]
await this.ctx.render
