### ISSUE TITLE
egg-init安装成功，但项目初始化失败

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#2554]
* **Node Version**:8.11.1
* **Egg Version**:2.8.1
* **Plugin Name**:none
* **Plugin Version**:none
* **Platform**:win7
* **Mini Showcase Repository**:
`gg-init egg-example --type=simple`
初始化失败：
![image](https://user-images.githubusercontent.com/15070379/39989415-6f31df4c-579c-11e8-9063-1623be337fa9.png)
我本地连的是淘宝的npm源，公司内cmd方式可能连不上npmjs.org，在eggjs里能设置访问淘宝源么？

**Comment by atian25** [comment]
`egg-init -r`

**Comment by bi-kai** [comment]
@atian25 
![image](https://user-images.githubusercontent.com/15070379/39996007-be3d8db6-57b0-11e8-85a9-15702cc0be39.png)
会有什么不同么？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/39998960-3e6a1078-57ba-11e8-98da-4ff9a4227ee4.png)


what I means it you could use `-r` to a special register url.

**Comment by bi-kai** [comment]
`egg-init cc --type=simple --registry=http://registry.npm.taobao.org/`
`egg-init -r http://registry.npm.taobao.org/`
我上边截图里标注了，这两个都是：
![image](https://user-images.githubusercontent.com/15070379/40030679-8fceab4a-581e-11e8-9b23-52f21e4e3de6.png)

**Comment by atian25** [comment]
是你的网络问题了，回家试试吧。
npm 的估计你被墙，至于 taobao 的，你公司网络是不是禁止淘宝购物了？

@JacksonTian 阿里云的源搞好了么？

**Comment by bi-kai** [comment]
我在公司内分四种场景做了测试，结果汇总如下。

# 使用taobao源
## 不带-r参数
**win7, node 8.11.1**, 由于node未使用本地的proxy代理，下载[https://registry.npmjs.org/egg-boilerplate-simple/-/egg-boilerplate-simple-3.1.2.tgz](https://registry.npmjs.org/egg-boilerplate-simple/-/egg-boilerplate-simple-3.1.2.tgz)失败，**项目初始化失败**。
**Linux node 6.9.3(低版本只是为了做测试)和node8.11.1**, 使用了/etc/profile中的http_proxy，下载上述包成功，**项目初始化成功**。

**linux with node 6.9.3** `npm i`报错：
![image](https://user-images.githubusercontent.com/15070379/40035159-01e471ec-5833-11e8-8cd0-da1b8ce4b1ba.png)
![image](https://user-images.githubusercontent.com/15070379/40035165-10ca56fe-5833-11e8-8785-bff1e0c1826f.png)
并且启动失败（应该是node版本低的原因）：
![image](https://user-images.githubusercontent.com/15070379/40035195-3b190d4c-5833-11e8-913d-22eb1d5622f6.png)

**Linux with node 8.11.1** `npm i`报错：
![image](https://user-images.githubusercontent.com/15070379/40035270-89849604-5833-11e8-87b8-690c3e97bc05.png)
不过，`npm run dev` **启动成功**。


`npm i`时都提示`EACCES: permission denied, open '/starlab/www/test/node/egg-example/.travis.yml'`，这个文件确实是不存在的。

**Comment by bi-kai** [comment]
# 使用taobao源
## 带-r参数
`egg-init egg-example1 --type=simple -r https://registry.npm.taobao.org/`

**win7, node 8.11.1**，下载[https://registry.npmjs.org/egg-boilerplate-simple/-/egg-boilerplate-simple-3.1.2.tgz](https://registry.npmjs.org/egg-boilerplate-simple/-/egg-boilerplate-simple-3.1.2.tgz)依然失败，**项目初始化失败**。
**Linux node 6.9.3(低版本只是为了做测试)和node8.11.1**, 使用了/etc/profile中的http_proxy，下载上述包依然成功，**项目初始化成功**。

目前看`-r`影响不到`egg-boilerplate-simple-3.1.2.tgz`从npm还是taobao下载。

**测试结果与第一个场景一致**，这种情况能不能调整下依赖模块的下载策略呢？

**Comment by bi-kai** [comment]
# 使用公司源
## 带-r参数

**Comment by bi-kai** [comment]
# 使用公司源
## 带-r参数

**Comment by atian25** [comment]
使用代理的话按标准配置环境变量即可

https://github.com/eggjs/egg-init/blob/master/lib/init_command.js#L50

**Comment by shiny** [comment]
```
> egg-ci@1.8.0 postinstall /data/master/node_modules/egg-ci
> node install.js

fs.js:145
    throw err;
    ^

Error: EACCES: permission denied, open '/data/master/.travis.yml'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at Object.<anonymous> (/data/master/node_modules/egg-ci/install.js:87:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
```
我也遇到了同样的问题，使用的是 root 帐号，不应该存在权限问题
node 版本`v10.4.0`

**Comment by suchcl** [comment]
项目初始化的时候设置egg-init源
egg-init egg-project -r=https://registry.npm.taobao.org
