### ISSUE TITLE
docs(logger): need add deacription unit of maxFileSize.

### ISSUE THREAD

**Issue by lidianhao123** [eggjs/egg#2555]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

### In Logger document [Size Sharding](https://github.com/eggjs/egg/blob/master/docs/source/en/core/logger.md#size-sharding) part. I do not which unit when set maxFileSize value.

```js
module.exports = appInfo => {
  return {
    logrotator: {
      filesRotateBySize: [
        path.join(appInfo.root, 'logs', appInfo.name, 'egg-web.log'),
      ],
      maxFileSize: 2 * 1024 * 1024,
    },
  };
};
```
maxFileSize: 2 * 1024 * 1024  -> 2G?

### Plugin defulat [config](https://github.com/eggjs/egg-logrotator/blob/master/config/config.default.js#L20)
```js
exports.logrotator = {
  maxFileSize: 50 * 1024 * 1024,
};
```
maxFileSize: 50 * 1024 * 1024  -> 50G?

### My idea
2 * 1024 * 1024 -> 2Mb
50 * 1024 * 1024 -> 50Mb
**The unit maxFileSize is Byte！**

**Comment by popomore** [comment]
Why not make a PR?

**Comment by lidianhao123** [comment]
Thx!
