### ISSUE TITLE
[egg-bin cov] 支持覆盖率阈值, 低于阈值报错

### ISSUE THREAD

**Issue by Stupidism** [eggjs/egg#2559]
* **Node Version**: 8
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-bin

[样例代码](https://github.com/kunagpal/express-boilerplate/blob/develop/scripts/test/run.js#L102-L106):
```
			nyc.checkCoverage({ // Enforces code coverage thresholds
				statements: 95,
				branches: 75,
				functions: 95,
				lines: 95
			});
```

**Comment by atian25** [comment]
try add that to `package.json`

```json
"nyc": {
    "check-coverage": true,
    "per-file": true,
    "lines": 99,
    "statements": 99,
    "functions": 99,
    "branches": 99
}
```

**Comment by Stupidism** [comment]
Thanks! Found the [docs](https://github.com/istanbuljs/nyc/#configuring-nyc)
