### ISSUE TITLE
config.logger 的 consoleLevel 直接配置没用，会被覆盖

### ISSUE THREAD

**Issue by huacnlee** [eggjs/egg#2560]
config/config.test.js

```js
'use strict';

module.exports = appInfo => {
  const config = exports = {};

  config.logger = {
    consoleLevel: 'DEBUG',
  };

  return config;
};
```

当这样配置 `consoleLevel: 'DEBUG'` 在 `local` 环境是有效果的。

但到了其他环境，例如 `test`，如果有期望要将日志在 Stdout 里面输出，就不行了，查看了一下 run 里面生成的结果，发现有个 `disableConsoleAfterReady: true`，看起来是 Ready 以后就禁用了。

不管处于什么考虑，这样设计不符合用户需求。配置 `consoleLevel` 无法生效。除非额外再配置一下 `disableConsoleAfterReady: false`

---

实际需求是在 Docker 部署的环境下，我们可能需要将所有的日志 stdout 输出，以便于统一收集，而不用一个一个文件的关注。

**Comment by popomore** [comment]
开启 disableConsoleAfterReady 即可
