### ISSUE TITLE
关于egg-socket.io 的问题 

### ISSUE THREAD

**Issue by z253573760** [eggjs/egg#2563]
代码如图  在本地win 下都是可以的  部署到线上 就不行 socket消息没发送出去
![image](https://user-images.githubusercontent.com/25268362/40097443-b7985ab4-5908-11e8-9070-c3f27e961dc8.png)

![qq 20180516125941](https://user-images.githubusercontent.com/25268362/40097556-5c8e9376-5909-11e8-9319-f780fd30a9d1.png)

**Comment by ngot** [comment]
Close it now. When got the necessary information, feel free to reopen it.
