### ISSUE TITLE
Egg 怎么无痛直接复用 koa 的中间件呢 ? 

### ISSUE THREAD

**Issue by iShawnWang** [eggjs/egg#2565]
比如 : https://github.com/koajs/response-time/blob/master/index.js 这个倒是很简单
复杂一些的也要自己撸成 egg 插件的形式么 ?

**Comment by whxaxes** [comment]
请看文档：https://eggjs.org/zh-cn/basics/middleware.html#%E4%BD%BF%E7%94%A8-koa-%E7%9A%84%E4%B8%AD%E9%97%B4%E4%BB%B6
