### ISSUE TITLE
egg-sequelize在db:migrate的时候，对使用环境提示出错

### ISSUE THREAD

**Issue by reducm** [eggjs/egg#2566]
* **Node Version**: 8,11,1
* **Egg Version**: 2.1.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.4
* **Platform**: mac os
* **Mini Showcase Repository**:

```bash
$ yarn run egg-sequelize db:migrate && EGG_SERVER_ENV=unitest yarn run egg-sequelize db:migrate
```
同时跑local和unitest环境的migrate，但是两个环境提示都是'using development'，但unitiest的库又创建成功了

![561526457738_ pic_hd](https://user-images.githubusercontent.com/1086830/40104725-a9b93754-5923-11e8-95f0-d907e2352051.jpg)

![581526457758_ pic_hd](https://user-images.githubusercontent.com/1086830/40104738-b0c2c04c-5923-11e8-97e9-bb3a3f22f236.jpg)

**Comment by reducm** [comment]
@wurining 我没有用typescript，的确官方的egg-sequelize基本没考虑环境的问题，在测试环境下遇到问题多多，基本自己不fork一份的话会有很多问题

**Comment by wurining** [comment]
@reducm 
了解，我去改改轮子。

**Comment by THaGKI9** [comment]
I run migration with this command and it works well 

for ``unittest`` environment: 
```shell 
$ NODE_ENV=test egg-sequelize db:migrate
```

**Comment by dead-horse** [comment]
egg-sequelize don't contains `sequelize-cli` now, you can import sequelize-cli by your self and create migrations and config follow the docs here http://docs.sequelizejs.com/manual/tutorial/migrations.html
