### ISSUE TITLE
egg-init初始化项目遇到的几个问题

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#2567]
* **Node Version**: 8.11.1
* **Egg Version**: 2.8.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:win linux
* **Mini Showcase Repository**:

## 问题1
全局registry用的是taobao源，初始化项目：
`egg-init egg-example1 --type=simple -r https://registry.npm.taobao.org/`
或者不用-r，set http_proxy，仍然有错误：
![image](https://user-images.githubusercontent.com/15070379/40108022-6c00ca54-592c-11e8-8db4-154706219fc1.png)
虽然不影响使用，但是如何消除呢？我切换到公司的内网源，就没有这个错误提示。

## 问题2
`egg-init`初始化时，-r与set process.env取http_proxy是否是一样的？

## 问题3
`egg-init`的不带-r即使全局设置了taobao源，也仍然use npmjs源，为什么不取局配置的源呢？

**Comment by atian25** [comment]
1. 第一个是你公司网络问题导致，我们默认是淘宝源
2. 两者不是一回事，前者用于判断去哪里下载，后者是 curl 的下载代理

https://github.com/eggjs/egg-init/blob/master/lib/init_command.js#L293

源码一共不到 400 行，可以看下就知道了。

**Comment by bi-kai** [comment]
@atian25 好的，我最近接触egg，公司内网有两个源，都有些问题，使用上造成了一些困扰，我在黑盒测各种组合场景，虽然意义可能不大，但是看到error还是很不舒服，等我梳理一下，就看源码

**Comment by suchcl** [comment]
npm-init egg-project -r=https://registry.npm.tabao.org
或者
npm init egg -r=https://registry.npm.taobao.org
