### ISSUE TITLE
ajax提交上传文件如何解决payload的方式

### ISSUE THREAD

**Issue by feifeimao666** [eggjs/egg#2568]
我用ajax提交数据，使用payload这种方式，但是后台报错说不是multipart，无法处理，该怎么办呢？

![1](https://user-images.githubusercontent.com/18097924/40111627-003c0a4a-5936-11e8-9424-a17e28a0e66c.png)
![2](https://user-images.githubusercontent.com/18097924/40111629-006d1de2-5936-11e8-81f5-28567604c9dc.png)
![3](https://user-images.githubusercontent.com/18097924/40111630-009c1bc4-5936-11e8-92fe-384f9645114b.png)
![4](https://user-images.githubusercontent.com/18097924/40111631-00d15668-5936-11e8-9786-27928eff83a6.png)

**Comment by popomore** [comment]
It seems content-type is wrong.
