### ISSUE TITLE
egg(服务端) + Vue.js(前端) 现在有跨域访问的问题，前后端分离架构下CSRF防护机制

### ISSUE THREAD

**Issue by tear3333** [eggjs/egg#2569]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

egg(服务端) + Vue.js(前端) 现在有跨域访问的问题，有没有获取token csrf防御的方法
比如说：
token防御的整体思路是：

第一步：后端随机产生一个token，把这个token保存在SESSION状态中；同时，后端把这个token交给前端页面；
第二步：下次前端需要发起请求（比如发帖）的时候把这个token加入到请求数据或者头信息中，一起传给后端；
第三步：后端校验前端请求带过来的token和SESSION里的token是否一致；
上文提到过，前后端分离状态下，Nodejs是不具备SESSION功能的。那这种token防御机制是不是就无法实现了呢？
贵公司有没有安全防御的具体例子

**Comment by killagu** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Requests_with_credentials

You can use cookie with CORS, so you can use session.

And you can deploy egg vue in the same domain.

**Comment by popomore** [comment]
Boilerplate for vue  https://github.com/eggjs/egg/issues/2492
