### ISSUE TITLE
ctx.app.curl 请求，为何偶尔会出现请求中断的情况

### ISSUE THREAD

**Issue by lanbinghang** [eggjs/egg#2571]
目前，使用ctx.app.curl 请求.net写的接口，偶尔出现500的错误，然后根据对方的日志查询，发现，我这边发出去的请求，然后自己中断了，这种情况常常会出现，写了try catch 这部分的请求代码，但是偶尔还是会出现500的错误，这是为什么呢？

**Comment by killagu** [comment]
[如何高效的反馈问题？](https://eggjs.org/zh-cn/faq.html#%E5%A6%82%E4%BD%95%E9%AB%98%E6%95%88%E7%9A%84%E5%8F%8D%E9%A6%88%E9%97%AE%E9%A2%98)

[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)

**Comment by popomore** [comment]
Maybe nginx or other proxy server return 500, you should check by yourself.
