### ISSUE TITLE
egg-sequelize在多database下的实现方式

### ISSUE THREAD

**Issue by WuStardust** [eggjs/egg#2572]
* **Node Version**: v8.4.0
* **Egg Version**: 1.7.0
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.1.0
* **Platform**:
* **Mini Showcase Repository**:

`egg-sequelize`在需要处理MySQL的多个database中数据的场景下有什么好的实现方式？
如果是原生的sequelize，可以直接建立多个连接，但是`egg-sequelize`并没有这样的方式。
我在项目中想到的是用```ctx.model.query(`use database`)```的方法，这样会不会影响高并发下的性能？

**Comment by sansroman** [comment]
你想要的是这种么
https://eggjs.org/zh-cn/advanced/plugin.html#%E5%A4%9A%E5%AE%9E%E4%BE%8B

**Comment by WuStardust** [comment]
对，是需要这样的功能，但这个是使用egg-mysql实现的，如果用egg-sequelize呢？
> 注：后面还是自己另外new了一个新的原生sequelize实例来做另一个database的连接orz

**Comment by yushen7** [comment]
顺着issue找过来，竟然没人pr，伤心了
