### ISSUE TITLE
官网文档疏漏，导致egg-scripts stop不能按照title去关闭进程，建议加入egg-scripts的版本说明

### ISSUE THREAD

**Issue by lynx1986** [eggjs/egg#2576]
升级到 egg@2.0.0时，附带安装的egg-scripts版本是^2.1.0。

按照官方文档，在egg-scripts的start和stop时，只要加入--title就可以杀掉指定egg应用。但是很遗憾，2.1.0版本中还没有加入按title筛选pid杀掉指定进程的特性。

而官方文档中，似乎没有指出这一点。（如果是我看漏了请原谅(⊙﹏⊙)b）

**Comment by atian25** [comment]
没看懂你想表达啥，既然文档里面写了，就必然是支持的。如果怀疑是 bug， 提交最小可复现案例。

https://github.com/eggjs/egg-scripts/blob/master/test/stop.test.js#L125

我们的 nightly ci 是有测试到这段逻辑的。

**Comment by xiejunfeng** [comment]
讲道理 这个功能我也用不了
