### ISSUE TITLE
middleware 一些不解

### ISSUE THREAD

**Issue by spitWind** [eggjs/egg#2577]
* **Node Version**:10.1
* **Egg Version**:2.8
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:win7
* **Mini Showcase Repository**:

话说路由的 函数 为何要加 with 来改变作用域, 这是干嘛? \
比如 

`
var  a=1;
async function login(ctx, next) {
  a===undefined//true
    }`
第一 每个模块都是 函数
exports = function (options) {
    /**
     * 
     * 
     * @param {Context} req 
     * @param {any} next 
     */
  return  async function login(req, next) {

    }
};

为什么要这种写法 ,谁能解释下 ?

**Comment by atian25** [comment]
1. 哪来的 `with` ？
2. `module.export = (options, app) => {}` 这本来就是 Koa 社区的中间件规范
3. 不要操心什么重复 new 的资源浪费，这里只会实例化一次
4. 变为函数的另一个原因是需要单独在 router 里面引入，再看下 Middleware 的文档吧
