### ISSUE TITLE
只执行一次的逻辑写在哪？

### ISSUE THREAD

**Issue by musicode** [eggjs/egg#2582]
举个简单的例子。

在 MQ 场景中，我希望在项目启动时，执行一次监听逻辑，在这个监听逻辑里，当收到消息时，我希望能调用一些 service 来完成工作，但是我发现 egg 目前的设计是，每次请求都会重新创建 service 实例。

之前看文档发现 agent 貌似是执行一次的，但是我怕写在 agent 之后，万一有什么错误，把网站搞挂。

此外，因为 service 是跟请求相关的，所以类似上面说的异步任务，是不是取不到 service？

**Comment by atian25** [comment]
> 执行一次监听逻辑

具体要做些什么？是全局一次，还是每个 worker 一次？集群情况下呢？

> 每次请求都会重新创建 service 实例

不要去操心不存在的 new 内存问题

> 因为 service 是跟请求相关的，所以类似上面说的异步任务，是不是取不到 service？

`const ctx = app.createAnonymousContext();` 可以看下文档

**Comment by musicode** [comment]
全局一次应该是写到 agent 里吧？我的需求是每个 worker 执行一次就行了，能否告知写在哪最合适呢？

最后一条，我看了下文档，应该是下面这样吧：

```js
const ctx = app.createAnonymousContext();
ctx.service
```

谢谢

**Comment by atian25** [comment]
```js
module.exports = app => {
  app.ready(() => {
    console.log('this worker is ready', process.pid);
  });
  app.messenger.on('egg-ready', () => {
    console.log('all worker is ready', process.pid);
  });
};
```

**Comment by musicode** [comment]
谢谢，这个答案很全

**Comment by guozefei** [comment]
全局只执行一次的 只有一个worker执行一次 分布式部署情况下 也只有一台机器的 一个worker执行一次应该是怎么实现？

**Comment by atian25** [comment]
你需要一个第三方服务，如 redis 之类的来做分布式锁

**Comment by guozefei** [comment]
如果是全局只执行一次 只有一个worker执行一次  但是不考虑分布式部署的情况 那可以用 agent来实现逻辑吗？ 这种实现方式是不是不合理 因为agent最好不要用来实现业务逻辑 
我这边的需求是我要去实现一个 数据库的某一个表的全表查询 其中有一列是 文章的内容 我要用 正则表达式把这个文章的内容全部替换一下  只需替换一次就行

**Comment by atian25** [comment]
最好不要对 『不考虑分布式部署』下结论，很多时候我们需要做平衡重启，至少都要两台机器。

**Comment by guozefei** [comment]
恩 我们现在生产环境确实是有两台机器 做的话 是准备用redis来做  只是在想 单台机器的时候agent是否可以做到我的需求

**Comment by atian25** [comment]
临时方案爱怎么玩都可以，但这种方案没必要搞，给自己留坑。
