### ISSUE TITLE
为什么agent.js没有执行？

### ISSUE THREAD

**Issue by laoliang330** [eggjs/egg#2584]
今天看到了多进程模型和进程间通讯一节，遇到如下问题：
1、将agent.js和app.js放在同一层目录，
app.js中的app.messenger.on可以监听执行，
但agent.js 中的代码并未执行，代码内容为：
module.exports = agent => {
    agent.logger.info('init agent');
};

运行时，log中未写入此内容

2、将agent.js放到./extend/目录下，npm run dev的时候报错
/Users/lm/webSite/test/eggjs/demo/node_modules/egg-core/lib/loader/mixin/extend.js:114
      const properties = Object.getOwnPropertyNames(ext)
                                ^

TypeError: Cannot convert undefined or null to object

请问为什么？

**Comment by atian25** [comment]
try `agent.logger.error('init agent');`

**Comment by atian25** [comment]
请给出最小可复现仓库

**Comment by laoliang330** [comment]
@atian25 
2018-05-22 12:21:39,393 INFO 13698 [master] node version v10.0.0
2018-05-22 12:21:39,395 INFO 13698 [master] egg version 2.8.1
2018-05-22 12:21:41,123 INFO 13698 [master] agent_worker#1:13699 started (1724ms)
2018-05-22 12:21:44,876 INFO 13698 [master] egg started on http://127.0.0.1:7001 (5481ms)
以上为启动信息

agent.js //和app.js同一层目录
exports.agent = (agent) => {
    agent.logger.info('init agent');
    agent.logger.error('init agent');
    
};
未执行，log未写入文件

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by laoliang330** [comment]
@atian25 https://github.com/laoliang330/eggjs.git

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/40362423-16b409e4-5dff-11e8-8d7a-8170686bf02f.png)

where is your `agent.js` ?

**Comment by laoliang330** [comment]
@atian25 真是抱歉，请见谅。agent.js的内容就是前面发的内容，现在补上了。抱歉

**Comment by luicfer** [comment]
@laoliang330 
https://github.com/laoliang330/eggjs/blob/master/agent.js#L1
``exports.agent `` ``module.exports``
typo =.=

**Comment by laoliang330** [comment]
@atian25 @luicfer 
都没注意，记得是copy的官方文档啊！
实在是不好意思。。。。。。。。。。。，O(∩_∩)O谢谢！！
