### ISSUE TITLE
typescript + egg 初始化项目出现 egg 这个module无法被ts识别，

### ISSUE THREAD

**Issue by LiJoah** [eggjs/egg#2586]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by whxaxes** [comment]
麻烦给个稳定复现的案例

**Comment by LiJoah** [comment]
import * as Egg from 'egg; 在ts中这样import egg 会出现egg不是一个module ；《[ts] Cannot find module 'egg'.》
如果使用官方的方式来初始化话项目，会出现文件权限的错误
在Linux上，使用官方的npx egg-init --type=ts showcase 这样来构建项目，需要root的权限，是因为我发现在初始化过程中，需要向 /opt/ 中写文件，所以需要root 权限，那么我使用sudo 来初始化，那么构建出来的项目中 config 和service 等文件就是root权限，普通用户无法操作，也没有读写的权限。
我是否需要更改 /opt/ 文件的权限，就可以解决问题。
我看了 egg 的index.d.ts 文件，不知道为什么 ts 无法识别出 egg 是module。

**Comment by whxaxes** [comment]
@LiJoah 所以说提供个能稳定复现的 repo，我帮你看一下

**Comment by LiJoah** [comment]
我怎么给您看会方便点，我把我初始化的项目截图给您，还是我直接fork一份我的项目，然后给您， 您帮忙看看

**Comment by LiJoah** [comment]
![image](https://user-images.githubusercontent.com/25709222/40341254-a416ca22-5db6-11e8-9560-9de5dec240c9.png)

**Comment by LiJoah** [comment]
其实我并没有干什么事情，在我这边ts 版本是 2.8.3 
项目刚刚开始，那个 egg.d.ts 是我从官方拷贝出来的，

**Comment by whxaxes** [comment]
@LiJoah  你创建一个稳定复现的 repo，然后把 git 地址发出来，我 clone 下来帮你看

**Comment by whxaxes** [comment]
等等......你项目怎么这么奇怪？为什么要拷贝 egg.d.ts ？

**Comment by whxaxes** [comment]
@LiJoah  你对比一下两个项目的区别，但是还是尽量用官方提供的骨架来初始化可以让你少走一些弯路

**Comment by LiJoah** [comment]
好的，谢谢您这边的及时回复，我这边又莫名其妙的可以导入了，估计是vscode 编辑器内置的 ts 有问题吧

**Comment by LiJoah** [comment]
@whxaxes  请问一下： 使用官方的 egg-ts-helper 来编译项目的话，如果 ts 文件中 有 warn 或者的 error 的话， 是不是就会直接退出编译，不会watch 文件了，需要重新运行编译？

**Comment by whxaxes** [comment]
@LiJoah 会 watch，但是如果你出错，过了好一段时间还没修复，egg 就会自动退出
