### ISSUE TITLE
为什么一直报error [HPE_INVALID_METHOD] occurred: Parse Error

### ISSUE THREAD

**Issue by wgyixin** [eggjs/egg#2589]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

代码未做任何修改，重新运行后就报下面的错误：
> egg-bin dev

2018-05-22 19:23:41,824 INFO 1844 [master] node version v8.11.0
2018-05-22 19:23:41,825 INFO 1844 [master] alinode version v3.11.0
2018-05-22 19:23:41,826 INFO 1844 [master] @ali/begg version 3.6.2
2018-05-22 19:23:42,339 INFO 1844 [master] agent_worker#1:1845 started (511ms)
2018-05-22 19:23:43,451 INFO 1844 [master] @ali/begg started on http://127.0.0.1:7001 (1625ms)
2018-05-22 19:24:27,593 ERROR 1846 A client (::ffff:127.0.0.1:50211) error [HPE_INVALID_METHOD] occurred: Parse Error
2018-05-22 19:24:27,595 ERROR 1846 A client (::ffff:127.0.0.1:50211) error [HPE_INVALID_METHOD] occurred: Parse Error

**Comment by atian25** [comment]
https://github.com/nodejs/node/issues/19914

收到了一些错误的请求包，你本地有什么扫描工具还是啥的？

**Comment by wgyixin** [comment]
没有开任何扫描工具，访问本地网址就会一直报错

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by XadillaX** [comment]
https://eggjs.org/api/Config.html#onClientError

根据文档你写一个配置，里面输出 `err.raw` 看看。

**Comment by Julyyq** [comment]
同样遇到了这个错误，因为用[mkcert](https://github.com/FiloSottile/mkcert)给本地装了https证书，然后通过https://localhost:7001 访问就会出现这个错误。

**Comment by gx761** [comment]
本地有安全扫描，日志文件疯长，怎么解决？

**Comment by atian25** [comment]
@gx761 

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by DougLee** [comment]
@Julyyq  您好 我也是因为发起https请求出现的这个错误, 请问该怎么解决呢

**Comment by atian25** [comment]
看上一条回复

**Comment by marbleqi** [comment]
我也出现过这个问题，如果egg本身配置的是http协议的服务，那么强制使用https协议请求服务，egg后端就会报这个错。

**Comment by atian25** [comment]
删除整个 node_modules，重新安装下依赖，不要锁版本，应该就没了。

**Comment by chjiyun** [comment]
@atian25  为啥不能锁版本？

**Comment by atian25** [comment]
> @atian25 为啥不能锁版本？

https://zhuanlan.zhihu.com/p/22934066

我们每个大版本下只维护一个版本，并保证严格遵循 semver 规则。
如果锁了版本，那你们就要自己承担更新和排查的责任。

**Comment by biluochun** [comment]
> 我也出现过这个问题，如果egg本身配置的是http协议的服务，那么强制使用https协议请求服务，egg后端就会报这个错。

怎么设置成 https 解决这个问题。这个问题没出解决方案吗。

**Comment by dancingCode-zx** [comment]
还没解决吗？

**Comment by Lizhooh** [comment]
@atian25 最新版，坑还在依然 occurred: Parse Error

**Comment by whxaxes** [comment]
egg 启动的是 http 服务，你用 https 访问肯定不行啦。。。建议起个 nginx 做反代

**Comment by jenvyxu** [comment]
是不是使用了类似Charles那样的代理软件
