### ISSUE TITLE
egg.js如何与java服务端通信

### ISSUE THREAD

**Issue by iamgaohui** [eggjs/egg#2592]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

想要用eggjs做一个服务端的模块给java用，java是用的dubbo框架，除了webservice以外还有没有别的跟java端的通信方式？或者有没有办法支持dubbo服务的协议？

用node-zookeeper-dubbo已经实现了调用java端的Services,除了webservice如何让Java调用nodejs的服务？

**Comment by gxcsoccer** [comment]
大概 6月中旬 会提供相关的插件。目前实现是蚂蚁开源的 bolt 协议，dubbo 协议的对接也在计划中

**Comment by dead-horse** [comment]
先关了，后面楼主持续关注就好

**Comment by SailorF** [comment]
@gxcsoccer 请问java跟egg进行通讯了，long，bigDecimal这些数据类型怎么进行转换？还是用json形式进行通讯，不过感觉对后端很不友好.

**Comment by gxcsoccer** [comment]
- [使用 egg-cloud 调用 dubbo 服务](https://www.yuque.com/egg/nodejs/kril24)
- [使用 egg-cloud 发布 dubbo 服务](https://www.yuque.com/egg/nodejs/dm2l7o)
