### ISSUE TITLE
您好，请问如何清除cookie,     session的清除方法不行，有cookie清除的方法吗

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2593]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by thonatos** [comment]
如果文档不能解决问题，请提供更详细的说明或最小可复现仓库。

- https://eggjs.app/zh-cn/core/cookie-and-session.html
