### ISSUE TITLE
如何清除cookie

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2595]
ctx.cookies.set('logname',user.username, {
							   maxAge: 10000,
							   signed: true,
							   httpOnly: true,
							   encrypt: true
						 });
你好，这样设置cookie,使用ctx.xxx.cookie = null 请除不了，请问该如何解决

**Comment by killagu** [comment]
https://eggjs.app/zh-cn/core/cookie-and-session.html

```javascript
ctx.cookies.set('logname', null);
```

**Comment by xiaobenSB** [comment]
Thank you

**Comment by leehomeok** [comment]
> Translation of this issue:
> 
> ## How to clear cookies
>  Ctx.cookies.set('logname',user.username, { maxAge: 10000, Signed: true, httpOnly: true, Encrypt: true }); Hello, so set the cookie, use ctx.xxx.cookie = null Please do not remove it, how can I solve it?

maxAge: 0
