### ISSUE TITLE
egg-mysql 如何打印出最终执行的sql

### ISSUE THREAD

**Issue by GitHubForQiuKai** [eggjs/egg#2596]
egg-mysql 如何打印出最终执行的sql 以方便调试
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by x-cold** [comment]
正在支持中……

https://github.com/eggjs/egg/issues/648
https://github.com/ali-sdk/ali-rds/pull/18

**Comment by zxmajunhong** [comment]
我本地启动的时候是直接在mysql的模块中的/lib/Connection.js文件中的Connection.prototype.query方法中打印出来的最终执行sql
```js
...
if (query.sql) {
    query.sql = this.format(query.sql, query.values);
  }
  console.log('sql', query.sql);
...
```

**Comment by zouzhenxing** [comment]
由于egg-mysql最终还是调用mysql库，如果只是想查看调试可打开mysql debug
`config.mysql = {
    // 单数据库信息配置
    client: {
      host: '',
      port: '',
      user: '',
      password: '',
      database: '',
      dateStrings: 'DATETIME',
      debug: true,
    },
    app: true,
    agent: false,
  };`

**Comment by popomore** [comment]
直接透传 mysql 的 debug 参数？

**Comment by ccys** [comment]
> 由于egg-mysql最终还是调用mysql库，如果只是想查看调试可打开mysql debug
> `config.mysql = { // 单数据库信息配置 client: { host: '', port: '', user: '', password: '', database: '', dateStrings: 'DATETIME', debug: true, }, app: true, agent: false, };`

配置里的dateStrings是怎么用的

**Comment by zouzhenxing** [comment]
dateString是表示mysql返回时间按DATETIME格式返回。我可以自行查看mysql库的文档说明。

**Comment by myhlcb** [comment]
var sql = "SELECT * FROM ?? WHERE ?? = ?";
var inserts = ['users', 'id', userId];
sql = mysql.format(sql, inserts);
