### ISSUE TITLE
无法初始化egg项目

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#2597]
* **Node Version**:8.11.2
* **Egg Version**:2.8.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:ubuntu 16.04
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/26592729/40464560-7e14218c-5f4e-11e8-9512-88402c851bc4.png)

**Comment by atian25** [comment]
from the log show, `egg-init` run success and copy all the files.

then it seems something is wrong with `npm install in vagrant env`, you need to google for this or raise issue to `npm` or `vagrant`.

btw, what version is your `npm` ?  have you  try to remove old `node_modules` and retry?

**Comment by Ailein** [comment]
@atian25 npm version is  5.6.0  , have you try to remove old node_modules and retry?  yes i have ,but still the same

**Comment by atian25** [comment]
try `npm install nyc`

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/40465204-0f67fc00-5f52-11e8-81c3-aa2f1a408a2c.png)

May be a nyc bug?

**Comment by atian25** [comment]
maybe `vagrant + npm`

**Comment by Ailein** [comment]
Tks, I was trying to upgrade npm to 5.10.0 and least 6.0.1 ,The error is still the same，

Finally I solved using `cnpm,` and it worked great!

I don't understand what's different between them

![image](https://user-images.githubusercontent.com/26592729/40468471-1d2c2132-5f60-11e8-8ff2-23a4a6c2c585.png)
