### ISSUE TITLE
egg-sequelize在npm6.0.0下 npm audit 的安全报告，建议升级依赖 sequelize-cli

### ISSUE THREAD

**Issue by XiangDeMei** [eggjs/egg#2599]
* **Node Version**: 9.8.0
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.4
* **Platform**: Ubuntu 17.10
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/16175984/40522094-aad123ba-6001-11e8-843e-44e3de54eeb4.png)

**Comment by qingdengyue** [comment]
[(sequelize-cli): upgrade to 4.0.0](https://github.com/eggjs/egg-sequelize/pull/52)
