### ISSUE TITLE
socket.io这一章的前端实例写法错误，导致断开重连会收到多个消息！

### ISSUE THREAD

**Issue by wucl05** [eggjs/egg#2601]
重连几次就会收到几次消息！
事件注册不应该写到coooect里面！

正确的写法如下：
const id = socket.id;
socket.on('connect', () => {
    log('#connect,', id, socket);
 });
// 接收在线用户信息
 socket.on('online', msg => {
      log('#online,', msg);
    });

    // 监听自身 id 以实现 p2p 通讯
    socket.on(id, msg => {
      log('#receive,', msg);
    });

    // 系统事件
    socket.on('disconnect', msg => {
      log('#disconnect', msg);
    });

    socket.on('disconnecting', () => {
      log('#disconnecting');
    });

    socket.on('error', () => {
      log('#error');
    });

**Comment by thonatos** [comment]
> 备注一下，这个并不是什么错误，当初这些代码提取自内部项目，有每次连接都更新信息的需求。

已合并，关闭了
