### ISSUE TITLE
以 Multipart 方式上传文件 报错

### ISSUE THREAD

**Issue by itlijinpeng** [eggjs/egg#2607]
* **Node Version**:
v10.1.0
* **Egg Version**:
2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

以 Multipart 方式上传文件时, 纯表单不含文件时,后台能正常接收,包含文件时,后台收到的表单为空

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6
