### ISSUE TITLE
runInBackground 捕获不到 错误 

### ISSUE THREAD

**Issue by robert7git** [eggjs/egg#2609]
* **Node Version**:  v8.9.3
* **Egg Version**: ^2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

之前在 文档里看到，如果用 try **catch** 捕获异常 多个 await 串 ，中的 错误不会被捕获。
文档里说     ctx.runInBackground(async ()  可以捕获。
但是，根本没报错。
是我用错了吗。
```
service code:
    ctx.runInBackground(async () => {
      return await this.ctx.model.Article.findAll({
        order: [[ 'id', sortStr ]],
        offset: (page - 1) * pageSize,
        limit: pageSize,
        include: [
          { model: ctx.model.User, as: 'user', attributes: [ 'id', 'name', 'sex' ] },
          { model: ctx.model.Tag, as: 'tags', through: { attributes: [] } },
          { model: ctx.model.Cate, attributes: [ 'id', 'name' ] },
          { model: ctx.model.Comment, as: 'comments' },
        ],
      }).then(function(docs) {
        return { rows: docs.length !== 0 ? docs : [] };
      });
    });
```

**Comment by robert7git** [comment]
好高级啊，自动翻译成英文了。

**Comment by ngot** [comment]
只使用了 then ，而没有 catch，错误被吃掉了，这个是 Promise 场景的基础踩坑点。建议先学看一下 Promise 的文档。https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by robert7git** [comment]
嗯，仓库暂时发不了呢。
就是说我用的对吧？
按我的理解 ctx.runInBackground 是 可替代 try catch 的 try catch 能力提升版本(捕获 所有 串联 await 中的 错误)。
是这样吗。

**Comment by dead-horse** [comment]
抛错后会捕获并打印日志。
