### ISSUE TITLE
服务器没有外网连接的情况下如何发布程序？

### ISSUE THREAD

**Issue by heocaf** [eggjs/egg#2610]
在个人开发机器上写好程序后，将整个文件夹(包括node_moudules文件夹) 拷贝到服务器上，并在服务器上安装好了Node，使用npm run dev时报错sh: egg-bin: command not found

请问要如何操作才可以在无网络的服务器上运行？

刚接触Nodejs不久， 选了eggjs来做公司项目，问题比较基础， 见谅！

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/core/deployment.html
