### ISSUE TITLE
关于在插件中使用中间件的问题

### ISSUE THREAD

**Issue by 15652768278** [eggjs/egg#2611]
之前使用egg-jwt的插件，发现token前缀是固定的，自己写了一个，发现egg的插件貌似没法挂载中间件，需要在项目里手动挂载才行，请问下是这么设计的还是我的使用方法不对？谢谢

**Comment by killagu** [comment]
```javascript
app.config.coreMiddleware.push('your middleware');
```

https://eggjs.org/en/basics/middleware.html#using-middleware-in-framework-and-plugin

**Comment by 15652768278** [comment]
thank you
