### ISSUE TITLE
this.ctx.cookies.get('username') is undefined, but this.ctx.header.cookie include "username=123456"

### ISSUE THREAD

**Issue by xingyesh** [eggjs/egg#2612]
* **Node Version**: 8.94
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/16128175/40702835-e46b595c-6415-11e8-8ec9-6bf63001b37f.png)

**Comment by atian25** [comment]
`signed: false`

https://eggjs.app/zh-cn/core/cookie-and-session.html

**Comment by xingyesh** [comment]
多谢。刚看到这个，加上就ok了。

**Comment by assmdx** [comment]
@xingyesh 这是什么IDE？

**Comment by atian25** [comment]
@assmdx vscode
