### ISSUE TITLE
egg-socket.io 打开网页时出现问题

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2616]
网页控制台可以显示这个：#connect, /io#fiAf2hkLkTClNqzKAAAD r {io: r, nsp: "/io", json: r, ids: 0, acks: {…}, …}

但报错：2018-05-30 19:02:02,607 ERROR 4712 A client (::ffff:127.0.0.1:52309) error [ECON
NRESET] occurred: read ECONNRESET

**Comment by xiaobenSB** [comment]
你好，这个问题解决不了吗

**Comment by xiaobenSB** [comment]
![qq 20180531121511](https://user-images.githubusercontent.com/34466113/40761105-9c398174-64cc-11e8-91cc-6d799041078f.png)



我是按照git里的egg-socket.iopei配的，除了没有配置redis和uws

**Comment by xiaobenSB** [comment]
![image](https://user-images.githubusercontent.com/34466113/40765773-29cc4d10-64e0-11e8-9137-8315258dfd97.png)
![image](https://user-images.githubusercontent.com/34466113/40765795-3e3cdf1c-64e0-11e8-8b20-f1af6ba52452.png)
![image](https://user-images.githubusercontent.com/34466113/40765821-50dddf5e-64e0-11e8-801d-32593b56c625.png)
![image](https://user-images.githubusercontent.com/34466113/40765875-760cb606-64e0-11e8-9779-1e766bdaa761.png)
![image](https://user-images.githubusercontent.com/34466113/40765930-9baecbe2-64e0-11e8-901e-ad4c22ce34e6.png)
![image](https://user-images.githubusercontent.com/34466113/40765996-b8a056a8-64e0-11e8-95c5-0328ada162d5.png)

**Comment by xiaobenSB** [comment]
![image](https://user-images.githubusercontent.com/34466113/40768612-71466af6-64e8-11e8-904e-bb5a21da9bc7.png)

**Comment by xiaobenSB** [comment]
你好，我有点蠢，可以示例下吗

**Comment by xiaobenSB** [comment]
![image](https://user-images.githubusercontent.com/34466113/40769661-26714070-64eb-11e8-84c5-1af3ff098a28.png)

**Comment by xiaobenSB** [comment]
![image](https://user-images.githubusercontent.com/34466113/40769705-3dfc2c0a-64eb-11e8-9dd2-1f1f0aef71fe.png)
还是会出现这个

**Comment by xiaobenSB** [comment]
please help me

**Comment by thonatos** [comment]
> https://github.com/eggjs-community/demo-egg-socket.io
