### ISSUE TITLE
egg-dotenv with egg-sequelize

### ISSUE THREAD

**Issue by lgertel** [eggjs/egg#2618]
I'm not able to make egg-dotenv work with egg-sequelize. Here is my config:

`config.default.ts

config.dotenv = {}

  config.sequelize = {
    dialect: 'mysql',
    database: 'nomikos',
    host: process.env.DB_HOST,
    port: '3306',
    username: process.env.DB_USER,
    password: process.env.DB_PASS,
  }

plugin.ts

const plugin: EggPlugin = {
  dotenv: {
    enable: true,
    package: 'egg-dotenv'
  },

  sequelize: {
    enable: true,
    package: 'egg-sequelize'
  }
};`

the config of sequelize are not getting the vars on .env!
Someone can help me?

**Comment by popomore** [comment]
egg-dotenv is not maintained by us.

**Comment by lgertel** [comment]
No problem. What is the recommended way to extract sensitive variables?
