### ISSUE TITLE
egg-sequelize + egg-mongoose

### ISSUE THREAD

**Issue by lgertel** [eggjs/egg#2619]
It's possible to create an app with nosql and sql databases at same time with eggjs?

I'm getting errors when activating both plugins at same time.

**Comment by 15652768278** [comment]
遇到了类似的问题，可能是“egg-sequelize 初始化过程中触发了 loadModel，这个时候 egg-mongoose 插件还没有加载好”，造成的

**Comment by z5614036** [comment]
给个代码，看看如何解决？
