### ISSUE TITLE
官方文档打不开了

### ISSUE THREAD

**Issue by yesvods** [eggjs/egg#2622]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/4458848/40775518-dcbfad1c-64fa-11e8-8a71-bf0f9a71e19e.png)

**Comment by atian25** [comment]
https://eggjs.app/

**Comment by popomore** [comment]
居然没匹配到
