### ISSUE TITLE
Question: Egg Cluster NODE_OPTIONS

### ISSUE THREAD

**Issue by cemremengu** [eggjs/egg#2623]
Is there a way to specify NODE_OPTIONS for workers other than using env?

**Comment by atian25** [comment]
what's your origin sense ?

**Comment by atian25** [comment]
what do you want to specify NODE_OPTIONS, why

**Comment by cemremengu** [comment]
I want to specify `--max-old-space-size` for workers. I am on windows so I cannot use egg scripts and looks like using `env` does not work. :/

**Comment by ngot** [comment]
Have a look at this issue https://github.com/npm/npm/issues/12238#issuecomment-312109166, maybe it helps.

**Comment by atian25** [comment]
@cemremengu  it's not about win, just pass `env` and node will use it.
you could just write your own `index.js` at win.
