### ISSUE TITLE
egg-bin --project customLocation/tsconfig.json支持

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#2628]
* **Node Version**: v8
* **Egg Version**: v2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问egg-bin集成 ts-node 是否支持在启动时传入自定义tsconfig.json路径？
比如像这样：
egg-bin dev -r --project customLocation/tsconfig.json egg-ts-helper/register

**Comment by jamesliauw** [comment]
前后端同构工程，需要读到不同的tsconfig.json配置

**Comment by whxaxes** [comment]
@jamesliauw  你们的目录结构是怎样的？我们这边的项目也是同构，我们的结构是这样的

```
.
├── app
│   └── web
│       └── tsconfig.json
├── config
│   └── tsconfig.base.json
└── tsconfig.json
```

node 部分的 tsconfig.json 放在项目根目录下， web 部分的 tsconfig.json 放在 `app/web` 下，然后两者公用的 ts 配置放在 config/tsconfig.base.json ，通过 extends 引入。

ts 解析是以找到的 tsconfig.json 那个目录开始往下处理的，看一下对你是否有参考价值？

**Comment by whxaxes** [comment]
还有一个办法就是，因为我们用的是 ts-node ，而 ts-node 是支持通过 env 来进行配置的。详细配置请看https://github.com/TypeStrong/ts-node#cli-and-programmatic-options  

比如你要更改 tsconfig.json 的配置，就配置一下 TS_NODE_PROJECT 的 env 即可
