### ISSUE TITLE
how to achieve  a ajax login by using egg-passport and egg-passport-local?

### ISSUE THREAD

**Issue by farzer** [eggjs/egg#2631]
* **Node Version**: 8.10.0
* **Egg Version**: 2.6.1
* **Plugin Name**: egg-passport egg-passport-local
* **Plugin Version**: 2.0.1   1.0.1
* **Platform**:
* **Mini Showcase Repository**:

how to achieve  a ajax login by using egg-passport and egg-passport-local?

I have been seen the passport authenticate api like

```js
app.post('/login',
  passport.authenticate('local'),
  function(req, res) {
    // If this function gets called, authentication was successful.
    // `req.user` contains the authenticated user.
    console.log(req, res)
  });
```

but the callback function has never run.

**Comment by farzer** [comment]
#2570

**Comment by farzer** [comment]
#2570

**Comment by farzer** [comment]
发现passport 的 authenticate 有一个callback参数，但是egg-passport没有加上这个

**Comment by farzer** [comment]
https://github.com/jaredhanson/passport/blob/2327a36e7c005ccc7134ad157b2f258b57aa0912/lib/middleware/authenticate.js#L64-L70

**Comment by Cheonsoon** [comment]
@atian25 @fengmk2

**Comment by atian25** [comment]
用 egg-passport-local  其实还不如直接自己写一个 POST 的 Controller
