### ISSUE TITLE
hackernews-async-ts样板工程,配置自定义静态资源目录不生效

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#2632]
* **Node Version**:v8
* **Egg Version**:2+
* **Plugin Name**:egg-static
* **Plugin Version**:
* **Platform**:windows
* **Mini Showcase Repository**:

请问 ts样式工程hackernews-async-ts, 需要配置自定义静态资源目录是否在config.default.ts中，按如下配置?
现在问题是不生效，npm run dev时生成的始终是默认public目录。

config.static = {
    buffer: false,
    dir: path.join(appInfo.baseDir, `app/${staticDirectory}`),
    dynamic: true,
    maxFiles: 1000,
    prefix: `/${staticDirectory}/`,
    preload: false,
  };

注: staticDirectory为目录变量

测过npm run tsc 然后 npm start是会生成自定义目录的，那么是npm run dev读的是默认的配置？

**Comment by popomore** [comment]
You should run tsc first
