### ISSUE TITLE
eggjs处理多个并发请求的问题

### ISSUE THREAD

**Issue by Jv-Juven** [eggjs/egg#2636]
* **Node Version**: v9.2.1
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-mysql
* **Plugin Version**: 3.0.0
* **Platform**: linux
* **Mini Showcase Repository**:

最近做一个需求：基于eggjs处理多个并发的异步请求，异步请求是使用egg-mysql在特定情况下，更新数据库里同一个字段值，请问，eggjs里面有没有处理这些类并发的异步请求为同步进行的？也即修改数据库数据时为同步进行。

**Comment by killagu** [comment]
It's not a egg question.
You can read the mysql manual.

https://dev.mysql.com/doc/refman/8.0/en/update.html
https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html
https://dev.mysql.com/doc/refman/8.0/en/commit.html

**Comment by buzai** [comment]
你需要队列

**Comment by Jv-Juven** [comment]
打算写个队列。
