### ISSUE TITLE
egg-socket.io 需要安装什么环境才能使用uws

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2637]
我 npm i uws -S 然后运行报错

            throw new Error('Compilation of µWebSockets has failed and there is
no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary
 available for your system. Please install a supported C++11 compiler and reinst
all the module 'uws'.

**Comment by killagu** [comment]
> __Please install a supported C++11 compiler and reinstall the module 'uws'.__

**Comment by xiaobenSB** [comment]
模块关编译器什么事来的？我只是想使用uws的，一般不是配环境的吗，我是在cmd下运行的，不是在编译器里

**Comment by xiaobenSB** [comment]
你好，有没有window cmd下  配置什么就可以编译了的

**Comment by atian25** [comment]
`npm i uws -S` 这个属于 `uws` 这个库在 win 下的兼容性问题，跟 egg 无关。

它给出的提示里面应该也有了： `Please install a supported C++11 compiler and reinst
all the module 'uws'.`

如果你还有问题，可以去 google 下，或者去 uws 那边提问。

**Comment by xiaobenSB** [comment]
好的，谢谢你
