### ISSUE TITLE
egg-socket.io app.io.of('/')里面的方法没有响应

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2638]
我没有配置redis和uws

![image](https://user-images.githubusercontent.com/34466113/40908981-eefb47d4-681a-11e8-84e7-8c5459b62f0d.png)

**Comment by xiaobenSB** [comment]
![image](https://user-images.githubusercontent.com/34466113/40956078-d4c9bcdc-68c0-11e8-9e2a-f860e91e3156.png)
你好，需要配置这三个文件的吗

**Comment by thonatos** [comment]
参考 #2616 里回复的示例。

**Comment by thonatos** [comment]
建议在使用过程中的问题可以放在一个 `issue` 内。
文档和示例已经比较清晰了，配置问题请仔细查看文档。
