### ISSUE TITLE
How to get the matched route in Controller

### ISSUE THREAD

**Issue by Penggggg** [eggjs/egg#2641]
* **Node Version**: v8.11.1
* **Egg Version**: v2.8.1
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: MacOS
* **Mini Showcase Repository**:

> code
router config
``
router.get(`/animal/detail/:id`, controller.moduleX.index.render );
``

> doubt

how to get the current matched route's message in Controller just like
``
{
  matched: '/animal/detail/:id'
}
``

**Comment by killagu** [comment]
You can use `DEBUG=koa-router`.

https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L8

**Comment by atian25** [comment]
`DEBUG=koa-router` can't use in prod.

when using SSR, usually egg router is degenerate into `*` as entry point.

see practice at easywebpack or egg-view-assets
