### ISSUE TITLE
vscode-eggjs进行调试的时候，不能通过IP进行访问

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#2642]
* **Node Version**: 8.11.1
* **Egg Version**:2.2.1
* **Plugin Name**:vscode-eggjs
* **Plugin Version**:
* **Platform**:windows
* **Mini Showcase Repository**:

1. 使用`npm run dev`即`egg-bin dev --sticky`启动的时候，可以通过`127.0.0.1`或者本机`192.168.25.52`访问
2. 使用vscode上面的插件启动的时候只可以通过`127.0.0.1`访问，不能通过`192.168.25.52`访问
防火墙是没问题的，否则在第一种情况下也不可能访问

**Comment by atian25** [comment]
connect to socket ?

did you forgot to config the `--sticky` to vscode scripts?

**Comment by hezhongfeng** [comment]
@atian25 
It work now.
I use the config copy from egg's doc.
`"runtimeArgs": ["run", "debug", "--", "--sticky"]`
without `--inspect-brk`.

**Comment by atian25** [comment]
you could just add `--sticky` to package.json

**Comment by hezhongfeng** [comment]
@atian25 
ok 
I add `--sticky` to debug like this
```
  "scripts": {
    "debug": "egg-bin debug --sticky"
  },
```
