### ISSUE TITLE
使用egg-sequelize链接多数据源的问题

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#2646]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

#1293
#1775 
请问使用`egg-sequelize`connect多数据源的问题现在能用了？谢谢~~~

**Comment by cuitianze** [comment]
同问，还不支持吗？

still not support ?

**Comment by dead-horse** [comment]
已支持
