### ISSUE TITLE
How to build a Singleton Service in egg

### ISSUE THREAD

**Issue by Penggggg** [eggjs/egg#2647]
* **Node Version**: 8.11.1
* **Egg Version**: 2.8.1

> My confus

I found that Egg will create Controllers and Services for every Request. So what is the best practise to build a Singleton Class Service in egg, just like **LruCacheService** ?

> 我的疑惑

我发现，egg对每次请求，都会实例化对应的Controller、Service。那在egg上创建一个对单例服务的最佳实践是怎么样的呢？正如单例的缓存服务 **LruCacheService** 一样

**Comment by atian25** [comment]
1. egg 是多进程的，多进程不存在共享， cache 这种用 redis 来做。
2. 每次请求都实例化的损耗可以忽略不计
3. 看下 https://eggjs.app/zh-cn/advanced/plugin.html#%E5%85%A8%E5%B1%80%E5%AE%9E%E4%BE%8B%E6%8F%92%E4%BB%B6%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

**Comment by xiekw2010** [comment]
https://eggjs.org/zh-cn/advanced/plugin.html#%E5%85%A8%E5%B1%80%E5%AE%9E%E4%BE%8B%E6%8F%92%E4%BB%B6%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5

现在是这个了
