### ISSUE TITLE
egg里有类似multer的插件吗

### ISSUE THREAD

**Issue by xiaobenSB** [eggjs/egg#2649]
你好

**Comment by popomore** [comment]
https://eggjs.org/en/basics/controller.html#acquire-uploaded-files

**Comment by xiaobenSB** [comment]
或者说是这个文件的文件流，希望你能指教指教下我这个菜鸟

**Comment by xiaobenSB** [comment]
还有就是为什么要清除文件流，一般没有数据不是为空吗，怎么还会连续响应的
