### ISSUE TITLE
socket.io [HPE_INVALID_METHOD] occurred: Parse Error

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#2651]
* **Node Version**:v8
* **Egg Version**:v2
* **Plugin Name**:egg-socket.io
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

错误：
2018-06-05 19:06:33,882 ERROR 10112 A client (::ffff:127.0.0.1:56344) error [HPE_INVALID_METHOD] occurred: Parse Error
2018-06-05 19:06:33,889 ERROR 10112 A client (::ffff:127.0.0.1:56344) error [HPE_INVALID_METHOD] occurred: Parse Error
2018-06-05 19:06:33,891 ERROR 10112 A client (::ffff:127.0.0.1:56345) error [HPE_INVALID_METHOD] occurred: Parse Error

原因:
依据SOCKET.IO示例，前端连接，使用以下代码:
<html lang="en" class=" ">
<head>
	<meta charset="utf-8">
</head>
<body>sdafffafasff</body>
<script src="/public/assets/socket.io.js"></script>
<script>
		var socket = io('http://localhost:7001');
		socket.on('connect', function(){ console.log('连接成功')});
		socket.on('event', function(data){ console.log('event', data); });
		socket.on('res', function(data){ console.log('res', data); });
		socket.on('disconnect', function(){ console.log('断开') });
</script>
</html>

重现方式:
1.运行npm run serve
2.http://127.0.0.1:7001/public/test.html

重现简化代码:
https://github.com/jamesliauw/egg-socket.io-isomorphism

**Comment by initial-wu** [comment]
没能重现，正常连接
![image](https://user-images.githubusercontent.com/17722900/41015571-7b770294-697d-11e8-8482-9f0b847c22a8.png)
![image](https://user-images.githubusercontent.com/17722900/41015583-8bb8b846-697d-11e8-9de8-d8c31565de26.png)

**Comment by killagu** [comment]
You can use [`onClientError`](https://eggjs.org/api/Config.html#onClientError) to print `err.rawPacket `.
