### ISSUE TITLE
Egg 有什么方法可以获取当前应用的端口？

### ISSUE THREAD

**Issue by Matthew1994** [eggjs/egg#2652]
**场景**： 想在应用的一个逻辑的实现中请求应用自身已经实现的另外一个路由

问：为什么不把可复用的逻辑写入 service 中？
答：旧项目的代码，不希望改变原有功能的代码。

问：为什么不自己指定启动端口？
答：提出这个 issue 当然是想动态获取当前应用的端口。（比如插件的开发，怎么可能要求插件的使用方按照你指定的端口启动应用）

``` javascript
const urlObj = {
    protocol: 'http',
    host: ctx.host,
    // port: '????',
    pathname: 'api/data',
    query: {
        type: 'all'
    }
};
yield axios.get(url.format(urlObj));
```

**Comment by killagu** [comment]
https://eggjs.org/api/Config.html#cluster

**Comment by Matthew1994** [comment]
@killagu  这个相当于自己指定启动端口或者读取默认的端口。但是事实上从这里获取的 port 不一定是真实的 port。egg-cluster 中定义了一个事件来修改 port 的值。

``` javascript
//  egg-cluster/lib/master.js
// get the real port from options and app.config
// app worker will send after loading
this.on('realport', port => {
   if (port) this[REALPORT] = port;
});
```
当选择的端口被占用时，会选择另外一个端口，但是 config 中的 port 的值并没有更新
![image](https://user-images.githubusercontent.com/11374030/41020691-6ae5ea58-6996-11e8-84f7-6a6ee8c262ca.png)
![image](https://user-images.githubusercontent.com/11374030/41020723-84997622-6996-11e8-86f5-1cf5358f7fa3.png)

**Comment by killagu** [comment]
It's `egg-bin dev` logic, will not occurred in prod env.

**Comment by atian25** [comment]
@ngot `app.config.cluster.port` will not work when `egg-bin dev --port=8000` 

`app.options.port` will work when you pass `--port` by not work when default.

**Comment by Matthew1994** [comment]
@atian25 Got it!
In conclusion, there is no perfect solution for this problem now. I hope that I can get the port in the way of <code>ctx.app.port</code> or <code>ctx.app.address().port</code> in following version of Egg. Just like what [supertest](https://github.com/visionmedia/supertest/blob/master/lib/test.js#L54) did.
``` javascript
// supertest/lib/test.js
Test.prototype.serverAddress = function(app, path){
  var addr = app.address();
  if (!addr) this._server = app.listen(0);
  var port = app.address().port;
  var protocol = app instanceof https.Server ? 'https' : 'http';
  return protocol + '://127.0.0.1:' + port + path;
};

```

**Comment by whxaxes** [comment]
@Matthew1994  

```js
// app.js

module.exports = app => {
  app.messenger.on('egg-ready', info => {
    console.info(info.port);
  });
};
```

**Comment by lihuaye** [comment]
@whxaxes 
```javascript
module.exports = app => {
  app.messenger.on('egg-ready', info => {
    console.info(info.port);
  });
};
```
在egg-ready事件中获取不到port
![9a5ae5b2-6f32-4f5c-a4d9-7691fc8b015c](https://user-images.githubusercontent.com/7691792/46247832-a717ae00-c443-11e8-8ccf-b31fbc8d1e62.png)

**Comment by atian25** [comment]
如果启动参数没传的话，port 这样可能拿不到。

可以换个方式：

```js
module.exports = app => {
  app.messenger.on('egg-ready', info => {
    console.log(info, app.server.address().port);
  });
};
```

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L88

看源码，给到 app 的是 options，里面如果入参没有传递，就不会有。

欢迎 PR 优化下。

cc @killagu @Maledong

**Comment by lihuaye** [comment]
@atian25 万分感谢，可以了
