### ISSUE TITLE
egg graphql plugin

### ISSUE THREAD

**Issue by ShuaiShuaiguo** [eggjs/egg#2653]
最近折腾了一个graphql插件[egg-gql](https://github.com/ShuaiShuaiguo/egg-gql)，支持apollo-tools最新api，参考[egg-graphql](https://github.com/eggjs/egg-graphql), [graphql-tools](https://www.apollographql.com/docs/graphql-tools/generate-schema.html) ,  使用egg-loader加载文件，具体加载逻辑详见 [egg-gql/lib/grpahql-loader.js](https://github.com/ShuaiShuaiguo/egg-gql/blob/master/lib/loader/graphql-loader.js),  默认支持ts。在ts下目录有一些约定，详见[run-books](https://github.com/ShuaiShuaiguo/run-books)。

问题是：egg中grpahql有没有更好的目录划分和加载逻辑？

**Comment by popomore** [comment]
如果你不喜欢 egg-graphql，那官方应该无法回答你

**Comment by ShuaiShuaiguo** [comment]
@popomore 明白了，我的也是参考实现。

**Comment by ShuaiShuaiguo** [comment]
@popomore 仔细看了下eggjs,官方库有一定的道理。
