### ISSUE TITLE
egg忽略Linux信号(how can i ignore linux singal?)

### ISSUE THREAD

**Issue by hellojukay** [eggjs/egg#2657]
# description
```js
module.exports = app => {
  app.beforeStart(async () => {
    process.on('SIGQUIT', function () {
      app.logger.info('Got SIGINT.  Press Control-D to exit.');
    });
  });
};
```
我在app.js文件里面写上如上代码，我希望程序启动以后能够忽略SIGQUIT信号，但是没有生效。
```txt
2018-06-07 15:51:06,603 INFO 25003 [master] receive signal SIGQUIT, closing
2018-06-07 15:51:06,604 INFO 25003 [master] kill agent worker with signal SIGTERM
2018-06-07 15:51:06,605 INFO 25003 [master] send kill SIGTERM to app workers and agent worker, will exit with code:0 after 5000ms
2018-06-07 15:51:06,605 INFO 25003 [master] wait 5000ms
```

# question 
正确的处理信号的方式应该是怎么样子的?

**Comment by popomore** [comment]
use `app.beforeClose`

**Comment by atian25** [comment]
@popomore `app.beforeClose` is updated? I Suppose it's only valid at unittest

**Comment by popomore** [comment]
It’s not a mature feature, the register function will be triggered when
application is stopping, but master will only wait 5 seconds and kill
worker.
TZ | 天猪 <notifications@github.com>于2018年6月8日 周五上午8:49写道：

**Comment by atian25** [comment]
so there is no way to disable close on SIGQUIT.

**Comment by popomore** [comment]
it will be triggered but not waited.

**Comment by atian25** [comment]
@popomore but what he want is `NOT EXIST EGG`, prevent egg close itself, not just listen to an event.

**Comment by popomore** [comment]
it's handled by egg

https://github.com/eggjs/egg-cluster/blob/master/lib/app_worker.js#L84

**Comment by atian25** [comment]
yes, but it's not  configurable.

@hellojukay what's your purpose? maybe you need `egg-scripts start --daemon` ?

**Comment by hellojukay** [comment]
@popomore Yes,i fount this source code by grep comand, i think singal handler should be register by user ,but not egg framework!

**Comment by hellojukay** [comment]
@atian25 no, i try it , i send SIGQUIT to master process ,it also can`t work.
```shell
kill -SIGQUIT {master-pid}
```
the master process will send 15 signal to work-process,finally mater exit itself!

**Comment by popomore** [comment]
> i think singal handler should be register by user ,but not egg framework!

worker should be managed by master

> I send SIGQUIT to master process ,it also can`t work.

Why not use `egg-scripts stop`

**Comment by atian25** [comment]
> I send SIGQUIT to master process ,it also can't work.

I cant catch your meaning, what do you want?

If you want to close app, just use `egg-scripts stop` or simply `kill ${master-pid}` then wait for it exit graceful

**Comment by hellojukay** [comment]
项目部署不起来呢，因为我使用的ansible来部署我的项目使用egg-scripts  start启动我的程序，部署退出以后，egg会自动收到一个SIGQUIT信号，然后自己退出了，我现在的问题是，我需要手动的屏蔽这个信号，让我的egg进程不要退出，但是egg无法做到。但别的框架，express,koa都能做到。

难道你每次部署程序都是手动在服务器上执行命令吗

**Comment by hellojukay** [comment]
我认为egg处理信号处理的逻辑应该允许用户来hook，而不是写死在代码里面。

**Comment by popomore** [comment]
You should check your ansible script.

**Comment by hellojukay** [comment]
ansible确实有问题，但是我无法解直接找ansible脚本的的问题，所以只能在egg上找另一种解决方法，如果没有办法ignore SIGQUIT那就算了吧。我再想想别的办法。
