### ISSUE TITLE
关于启动自定义

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#2659]
启动自定义只能定义在 app.beforeStart 里写需要执行的逻辑吗？现在有一个需求是程序启动就要在服务端与另一个服务建立长连接，而且长连接之前还需要批量做几个请求获取一些配置数据，但是文档里说了beforeStart  中不建议做太耗时的操作，框架会有启动的超时检测。请问这种情况有什么比较好的解决方案？

**Comment by popomore** [comment]
`beforeStart` is the best choice in this case

**Comment by Leungkingman** [comment]
@popomore 个人认为这不是最后的方法，假设我要在前端发送一个请求去停止这个服务端与其他服务建立的长连接的话，在 beforeStart 应该怎么处理？

**Comment by popomore** [comment]
You can not receive requests until the application is started.

**Comment by Leungkingman** [comment]
我的意思是，我的应用启动了，启动的时候在 beforeStart 建立一个长连接。然后突然间我想断开这个长连接，我需要在前端发送一个请求，后端接收到这个请求之后去关闭这个长连接。这种情况有没有什么比较好的解决方案？

**Comment by popomore** [comment]
Get the socket in the controller, and destroy it.
