### ISSUE TITLE
长时间未响应，请求端报错了

### ISSUE THREAD

**Issue by aiyadingya** [eggjs/egg#2661]
* **Node Version**:
8.9.1
* **Egg Version**:
2.3.0
* **Platform**:
OS X、centos

使用egg作为框架，部署了服务，暴露出接口供java端调用，egg这边作为中间服务，会请求别的数据，但耗时很长。 偶尔egg长时间未返回响应的时候，java的请求直接抛出了，但egg这边我还没有返回响应，而且egg也没有抛出错误。不知道问题出在哪里，已确认不是超时的问题，使用postman测试也是同样的问题。
以下是java的错误
`````
 Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
``````

抱歉我无法提供更加详细的错误，因为实在没有

**Comment by popomore** [comment]
Maybe socket is timeout in java side, but egg is continuously requesting.

**Comment by yecao007** [comment]
微信小程序 的 
WebSocket connection to 'ws://192.168.5.105:7002/' failed: Connection closed before receiving a handshake response
