### ISSUE TITLE
npm i egg-init -g 报错

### ISSUE THREAD

**Issue by blockmood** [eggjs/egg#2663]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

**Comment by atian25** [comment]
just a npm WARN
