### ISSUE TITLE
helper内部调用方法时,无法读取this.app.config

### ISSUE THREAD

**Issue by wpbeio** [eggjs/egg#2664]
* **Node Version**:v8.11.2
* **Egg Version**:2.8.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

有时会在helper内部调用方法,这时候被调用方法使用了this,app.config,或者使用this.config就报错了.因为helper和service内部this指向的是他们本身.不知道这个问题有没有其他办法解决呢?

**Comment by popomore** [comment]
This.ctx.app

**Comment by wpbeio** [comment]
谢谢

**Comment by wpbeio** [comment]
这几天没有写egg的项目,今天按照你的说的this.ctx.app.config这种方式试了一下,发现还是不可以.
可能是我问题没有描述清楚,在helper里面调用helper内部的方法,这时没办法访问config.我记得你们文档说了这种情况,但是没有说如何解决.

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧
