### ISSUE TITLE
app.beforeStart引入自定义工具类失效

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#2665]
在app.beforeStart需要执行比较复杂的逻辑。
想在根目录建立一个utils的文件夹，里面放置一些封装好的方法类，以便在 app.js 里require，使用，但是执行却报错：

// app.js
const calculate = require('./utils/calculate')
module.exports = app => {
  app.beforeStart(function* () {
     calculate.test()
  })
}

// calculate.js
function calculate() {}

calculate.prototype.test = function() {
  console.log('calculate test')
}
module.exports = calculate

运行却报错：
<img width="828" alt="wx20180608-180353 2x" src="https://user-images.githubusercontent.com/16955472/41152506-5a1392fa-6b46-11e8-8656-4b3f5b4602cc.png">

**Comment by popomore** [comment]
It's your problem.

**Comment by Leungkingman** [comment]
could you tell me what's the problem please??

**Comment by atian25** [comment]
because what you defined is `calculate.prototype.test`,  but what you call is `calculate.test()`

maybe you need to review javascript language tutorial.
