### ISSUE TITLE
egg-cors 的白名单和ctx.redirect 共用config.security.domainWhiteList 有点不科学

### ISSUE THREAD

**Issue by wsgfz** [eggjs/egg#2666]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

今天就遇到了这么一个问题
比如我需要跳转 api.weixin.qq.com 去进行微信授权登录相关的操作，但是我并不是要让这个域名进行跨域访问，最后却不得不在白名单里加上这个域名。
感觉这样很容易留个坑，刚开始我可能只是想开一些CORS的白名单, 后来需要redirect到其他域名的时候, 居然是去设置CORS白名单的地方加... 万一我就只是想跳转但是不想让他跨域访问呢

**Comment by atian25** [comment]
if you only want to config cors, use `origin`, see https://github.com/eggjs/egg-cors#configuration
