### ISSUE TITLE
async/await 操作mysql失败

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#2668]
如图所示，执行insert之后返回的是一个空对象{}，正确的应该是返回写入成功后的id。而且最重要的是数据表根本就没有这条数据，请问这个是什么原因？
<img width="539" alt="wx20180609-230003 2x" src="https://user-images.githubusercontent.com/16955472/41192997-5cb1f51c-6c39-11e8-85ff-145076c8cdbd.png">
<img width="172" alt="wx20180609-230040 2x" src="https://user-images.githubusercontent.com/16955472/41192998-5d1ce7dc-6c39-11e8-930a-8549a4960f89.png">

**Comment by luneice** [comment]
mysql 插件使用的是否是 egg 中推荐的？如果是[请参考这里](https://eggjs.org/en/tutorials/mysql.html#create)

insert 语句的返回值似乎不支持您描述的那个，一般返回值是影响了多少条记录等。

**Comment by BaffinLee** [comment]
设置一下环境变量，再运行看一下日志输出

```bash
# windows cmd
set DEBUG=ali-rds:*

# unix
DEBUG=ali-rds:*
```

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
