### ISSUE TITLE
Question: Plugin app.end function?

### ISSUE THREAD

**Issue by cemremengu** [eggjs/egg#2672]
For plugins (and in general) you can do:

```
app.beforeStart(function*() {
    app.coreLogger.info(`status OK`);
});
```

Is there a function for running a logic (cleanup etc.) before the app closes (i.e. receives a SIGINT) ?

**Comment by atian25** [comment]
`app.beforeClose` will exec but only wait for 3s

**Comment by cemremengu** [comment]
Thanks, it should be enough I think
