### ISSUE TITLE
egg-security whitelist 不能拦截到错误的origin和referer

### ISSUE THREAD

**Issue by mymickey** [eggjs/egg#2674]
请求头
```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 26
Content-Type: application/x-www-form-urlencoded
Cookie: csrfToken=6ZuwqSPJGRSrHOUhHsbAb8o9
Host: 0.0.0.0:7003
Origin: http://aaa.com
Pragma: no-cache
Referer: http://aaa.com/index.html
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
```

```
config.security = {
    csrf: {
      enable: false,
    },
    domainWhiteList: ['http://127.0.0.1:3000'],
  };
```

以下是我断点调试的结果

![image](https://user-images.githubusercontent.com/572102/41210843-8368847c-6d66-11e8-81fc-ff2cc1c4cbb8.png)

第一张图片里会验证我的白名单，之后会返回false （egg-security/lib/util.js）

![image](https://user-images.githubusercontent.com/572102/41210897-c2dd05ba-6d66-11e8-9e0c-a53b4db8b8be.png)

第二张图片是单步后往下走到的结果。(koa/cros/index.js)
问题：为什么图1中验证为false了图2里还要走到其他的中间件里呢？而且还会走到自己的controller中去？如果请求的域名不在白名单里不是直接返回5xx之类的错误消息了？我理解的是白名单列表之外的域名是无法请求这个服务的；或者说我要如何做才能达到想要的呢。感谢

**Comment by BaffinLee** [comment]
这个域名白名单 `domainWhiteList ` ，应该是用来跨域请求时判断要不要设置 `Access-Control-Allow-Origin` 等 `CORS` 响应头的依据，不会直接拒绝请求的。

**Comment by atian25** [comment]
@Brian175 `domainWhiteList` 主要用于 egg-security 的 redirect 限制。

cors 是顺便的，有需要可以定制 cors.origin

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
