### ISSUE TITLE
egg-sequelize 在单元测试的时候 可以选择性地不连接数据库吗?

### ISSUE THREAD

**Issue by Stupidism** [eggjs/egg#2675]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

现在 egg-sequelize 插件只要启用了, 是会不管 env 或者有无 config 都去尝试连接数据库的, 这给我的单元测试带来了一些困难. 

在本地还可以起一个 mysql 数据库, 然后在 config.local.js 里面配置上去, (实际上, 所有model 的方法在用到的时候都会被 mock 掉)

然而到了 CI 环境, 问题就又变复杂了.

**Comment by Stupidism** [comment]
Anybody interested?

**Comment by THaGKI9** [comment]
disable `egg-sequelize` in `plugin.unittest.ts` maybe a solution

**Comment by Stupidism** [comment]
@THaGKI9 I tried that, but egg automatically loads model folder, and in the model definition, it uses app.Sequelize

**Comment by atian25** [comment]
the load logic is in egg-sequelize, so if you disable it correctly, it will not load models

**Comment by Stupidism** [comment]
@atian25 Sorry, I misremembered. Model definitions are called because I wanted to test functions in model definition, so I got that error. I can import sequelize myself for app mock.
```
const ActivitiesModelFactory = require('../../../app/model/activities');
//...
    const ActivitiesModel = ActivitiesModelFactory(app);
```

**Comment by atian25** [comment]
recommended to start a db for these,  if you are using travis, try it's `service`

https://github.com/eggjs/egg-sequelize/blob/master/.travis.yml#L13
