### ISSUE TITLE
egg-master process received SIGTERM signal and process exit

### ISSUE THREAD

**Issue by alex-zhang** [eggjs/egg#2676]
* **Node Version v8.10.0 **:
* **Egg Version 2.5.0:
* **Plugin Name**:
* **Plugin Version**:
* **Platform Linux xxxxx 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**:
* **Mini Showcase Repository**:

node master(cluster) process, random receive SIGTERM signal (the system men is enough)

the node process's parent process is the system init process. why the system send the kill SIGTERM signal to the node process

![image](https://user-images.githubusercontent.com/4457451/41225226-f37c042a-6da0-11e8-88a2-df1d49a4d6c9.png)

**Comment by atian25** [comment]
had you using `egg-scripts` ? see egg guide docs deploying chapter

**Comment by popomore** [comment]
Why do you use initd? You should check that first

**Comment by alex-zhang** [comment]
the master process is a daemon process and it's parent process pid is 1. it's a initd process.

**Comment by atian25** [comment]
did you use it at docker?
could you please provide your start command?
please provide more information.

**Comment by LiuXiao89** [comment]
when i user eggjs for alibaba/beidou , i also met this issue...
like this:
![image](https://user-images.githubusercontent.com/29245046/42011471-27433de6-7ac6-11e8-9709-b1742771dee7.png)

**Comment by popomore** [comment]
If you use `--no-daemon`, it could be a OS problem. Or can you reproduce it in docker.

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by kekobin** [comment]
hi, did you fix it ? i also encounted the same problem:

![image](https://user-images.githubusercontent.com/4536310/62998680-ddfd8380-be9e-11e9-8dc5-7e80bb0137b7.png)
