### ISSUE TITLE
watcher failed的问题，eggjs是2.9.0

### ISSUE THREAD

**Issue by zhouyuping09** [eggjs/egg#2677]
watcher failed的问题，eggjs是2.9.0，agent上没跑任何东西，中间5点多common.error报错好就不报错了，但是egg-web一直在刷错误，没三秒两个。访问日志是正常的。
![image](https://user-images.githubusercontent.com/28697408/41228618-922bbe3a-6dab-11e8-9158-d419e87113f8.png)

![image](https://user-images.githubusercontent.com/28697408/41228683-c3a441c6-6dab-11e8-8478-4158db9b5447.png)

**Comment by zhouyuping09** [comment]
eggjs自从上线后就没正常过，刚开始是close_wait太多把服务器堵了，但是进程都还在，现在升到2.9.0，这个问题冒死是没有了，但是这种报错就经常遇到，让人提心吊胆；
![image](https://user-images.githubusercontent.com/28697408/41229378-5f7244e8-6dae-11e8-8ea4-4a5a8e25d534.png)
如图，有个进程中间断了好几次

**Comment by atian25** [comment]
如果无法提供可复现的方式，谁也无法帮你解决问题。

**Comment by zhouyuping09** [comment]
我想知道这个报错是指什么意思，一般是谁出了问题，有人能告诉我吗？

**Comment by zhouyuping09** [comment]
使用了alinode监控，是不是它会影响agent?

**Comment by atian25** [comment]
> 使用了alinode监控，是不是它会影响agent?

如果它能影响到，那阿里的全部线上 Node 应用都会被影响到。既然我们推荐这 2 者搭配，就肯定是久经考验的。

问题还是在于你的业务代码。这个报错看起来像是有耗时的操作导致 CPU 占用太久，心跳超时。

**Comment by zhouyuping09** [comment]
好的，谢谢，我回去看看代码里，都有哪些操作会占用cpu太久。

**Comment by gxcsoccer** [comment]
用 alinode 抓一个 CPUProfile 看看呢？

**Comment by zhouyuping09** [comment]
确实有很多毛刺，不知道是不是它们影响的

![qq 20180612084020](https://user-images.githubusercontent.com/28697408/41263886-470fb836-6e1c-11e8-8c79-649da84a4362.png)

**Comment by zhouyuping09** [comment]
cpu平均占用率还是很低的，只有百分之一点多
安装alinode后，会造成成千上万了LAST_ACK
![image](https://user-images.githubusercontent.com/28697408/41265236-d716493e-6e23-11e8-9327-0a4e0e85afd7.png)

**Comment by JacksonTian** [comment]
你可以通过 tnvm 把 runtime 切换为等价版本的官方 Node，如果还出现上面的问题，那就是业务或者框架的问题，如果问题消失，那么就确认是 alinode 的问题。

但根据你反馈的问题，跟 alinode 应该是没关系的。你看看 39680 这个端口跟什么应用相关？

**Comment by gxcsoccer** [comment]
39680 这个是 cluster 的 leader 监听的，看下 39680 这个端口还在监听没有

**Comment by gxcsoccer** [comment]
netstat -an | grep 39680

**Comment by gxcsoccer** [comment]
另外如果没有用到 watcher 可以把它关了

```js
// config/plugin.js

exports.watcher = false;
```

**Comment by zhouyuping09** [comment]
好的。

**Comment by gxcsoccer** [comment]
https://github.com/node-modules/cluster-client/blob/master/lib/follower.js#L221

这里有点问题

**Comment by gxcsoccer** [comment]
@zhouyuping09 

你启动了几个 app worker ?

**Comment by zhouyuping09** [comment]
![image](https://user-images.githubusercontent.com/28697408/41267313-a603f562-6e2d-11e8-828c-d8fbec429b84.png)
是直接用的配置文件，没有修改

**Comment by zhouyuping09** [comment]
根据alinode上的显示，应该是2个，4条有颜色的线条，一条是node.js,一条没有http请求，两条有请求进入

**Comment by atian25** [comment]
@zhouyuping09 你这启动有问题，为啥不用 egg-scripts，看下我们的部署文档

**Comment by zhouyuping09** [comment]
![image](https://user-images.githubusercontent.com/28697408/41267686-056f4848-6e2f-11e8-8a22-6c36ddb03192.png)
用的是nohup npm run start-prod &,这样有问题吗？我去看看egg-scripts.

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/deployment.html

**Comment by atian25** [comment]
@hubcarl 你的骨架最好升级下

**Comment by gxcsoccer** [comment]
https://github.com/node-modules/cluster-client/pull/43

**Comment by gxcsoccer** [comment]
@zhouyuping09 我发布了，你再试试

**Comment by zhouyuping09** [comment]
好的，万分感谢！
