### ISSUE TITLE
生产环境80端口启动，无法打印日志

### ISSUE THREAD

**Issue by inmWang** [eggjs/egg#2678]
controller文件打印日志：
ctx.logger.error('test logger error');

config.default.js 配置：
config.logger = {
    level: 'DEBUG',
  };

package.json配置：
"start": "egg-scripts start --port=80 --daemon --title=egg-server-cp-h5"

执行sudo npm run start后，日志文件没有内容。日志文件的权限为-rw-rw-r--

**Comment by atian25** [comment]
please provide the full path of log files you had check.

**Comment by inmWang** [comment]
@atian25 项目路径/home/portal/application/release 日志路径 /home/portal/logs/cp-h5

**Comment by inmWang** [comment]
已解决 默认路径是/root/logs 路径找错了
