### ISSUE TITLE
egg-logview强制7001端口能否加载cluster: {listen: {port: 80}}端口配置

### ISSUE THREAD

**Issue by chinacoolboyzz** [eggjs/egg#2679]
容器部署负载均衡只能转发80端口
```
 cluster: {
    listen: {
      port: 80
    }
  }
```
希望egg-logview插件能够读取服务器端口配置不强制绑定7001端口

**Comment by atian25** [comment]
it will serve at the port which egg serve, what you see is just a log.

PR is welcome.

https://github.com/eggjs/egg-logview/blob/master/app/middleware/logview.js#L14

**Comment by chinacoolboyzz** [comment]
测试了确实只是日志显示问题，建议更新下日志输出

**Comment by atian25** [comment]
PR is welcome
