### ISSUE TITLE
egg-sequelize的疑问

### ISSUE THREAD

**Issue by wython** [eggjs/egg#2681]
* **Node Version**: 8.0 
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 3.1.4
* **Platform**: window
* **Mini Showcase Repository**:

这是一个关于egg-sequelize的小问题。我在extend文件夹中扩展了application对象。填了了属性ENUM。
```javascript
// in app/extend/application.js
module.exports = {
  get ENUM() {
    return // 这不是重点;
  }
};
```
然后我希望在model中使用这个属性:
```javascript
'use strict';
// in /model/someModel.js
module.exports = app => {
 // some order
  const sequelize = app.Sequelize;
  const { OrderStatus } = app.ENUM; // 报错点
  return Order;
};
```
启动时候回发现此时app.ENUM为undifine。
当然，调试时原因很简单。
egg-sequelize 启动时会在app扩展前加载model代码。此时为执行extend.
我可以先注释掉代码，启动项目，然后在打开代码，此时的加载顺序是正常的。。
也就是说load model -->(报错时机)
load app-->
load model ---> (define model)

我在想，这一块是不是可以优化一下

**Comment by dead-horse** [comment]
与 egg 加载顺序有关，如果遇到类似问题，enum 常量可以通过 require 的形式引入
