### ISSUE TITLE
[BUG] 中间件 和 egg-mongoose 一起使用 返回404

### ISSUE THREAD

**Issue by djfos** [eggjs/egg#2684]
* **Node Version: v8.9.4**:
* **Egg Version: ^2.6.1**:
* **Plugin Name: egg-mongoose**:
* **Plugin Version: ^2.2.1**:
* **Platform: win10**:
* **Mini Showcase Repository: https://github.com/djfos/egg-bug-replay-middleware-mongoose**

### router
![router](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/router.jpg)

### controller
![controller](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/controller.jpg)

### middleware
![mw](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/mw.jpg)

### config
![config](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/config.jpg)

### plugin
![plugin](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/plugin.jpg)

##  问题

1.  中间件 和 mongoose 一起用，返回404
  ![plugin](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/404.jpg)

1. 中间件 和 mongoose 只用其中一个，返回 hi eeg
![plugin](https://raw.githubusercontent.com/djfos/egg-bug-replay-middleware-mongoose/master/imgs/ok.jpg)

## 补充
- 工具 postman
- 本地数据库是空的

**Comment by popomore** [comment]
`await next()` in middleware

**Comment by pf135145** [comment]
楼上正解，我也碰到了这个问题
