### ISSUE TITLE
helper内部调用函数,this无法读取,导致无法读取config

### ISSUE THREAD

**Issue by wpbeio** [eggjs/egg#2686]
Node Version:v8.11.2
Egg Version:2.8.1
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:

有时会在helper内部调用方法,这时候被调用方法使用了this,app.config,或者使用this.config就报错了.因为helper和service内部this指向的是他们本身.不知道这个问题有没有其他办法解决呢?
复现 仓库地址https://github.com/wpbeio/eggtest.git

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/41328657-d52dfdb4-6efb-11e8-980e-e9bbe2886170.png)

需要理解下 JS 的作用域

**Comment by wpbeio** [comment]
那如果我想在setredis1里面调用config,应该怎么调用呢?

**Comment by atian25** [comment]
`Function.prototype.call` 了解下

**Comment by wpbeio** [comment]
好的谢谢
