### ISSUE TITLE
定时日志问题，定时轮询出错又没发觉是否会一直写下去

### ISSUE THREAD

**Issue by failIsShit** [eggjs/egg#2687]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

比如我2ms的轮询，如果除了错又没发现是否会把磁盘写爆，egg日志是否有保护措施呢？

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/logger.html#%E6%97%A5%E5%BF%97%E5%88%87%E5%89%B2
