### ISSUE TITLE
how to save logs in baseDir?

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#2689]
* **Node Version**: 8.11.1
* **Egg Version**:2.2.1
* **Plugin Name**:egg-logger
* **Plugin Version**:1.6.2
* **Platform**: centos
* **Mini Showcase Repository**:

I use just a config.default.js to config my app. And I want to save logs in baseDir when  run `npm start` cmd.But the config is not work below. It still save logs in `/root/logs`.
```
    logger: {
      dir: path.join(appInfo.baseDir, 'logs', appInfo.name)
    },
```

**Comment by atian25** [comment]
https://eggjs.app/zh-cn/faq.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by hezhongfeng** [comment]
@atian25 

I have read this.And I use `dir: path.join(appInfo.baseDir, 'logs', appInfo.name)` to config app.
Then I delete `/root/logs/` and baseDir's logs
I run `npm start` ,the console will show below
```
[egg-scripts] Starting egg application at /data/node/20180614
[egg-scripts] Run node /data/node/20180614/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-20180614","framework":"/data/node/20180614/node_modules/egg","baseDir":"/data/node/20180614"} --title=egg-server-20180614
[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] egg started on http://127.0.0.1:7001
```
## check run's config
application_config.json
```
    "logger": {
      "dir": "/data/node/20180614/logs/20180614",
```
application_config_meta.json
```
  "logger": {
    "dir": "/data/node/20180614/config/config.default.js",
```

I check `/root/logs`,below is result.
```
├─ 20180416
│    ├─egg-schedule.log
├── alinode
```
Then check baseDir,below is result.
```
├─ 20180416
│    ├─20180614-web.log
│    ├─common-error.log
│    ├─egg-agent.log
│    ├─egg-web.log
```
So I find `egg-schedule.log` and `alinode` will still cvreate in `root`. Is it ok?

**Comment by hezhongfeng** [comment]
Thank you.I will use different app name to distinguish logs.

**Comment by atian25** [comment]
recommended to use docker then you don't had to care about the log dir

**Comment by hezhongfeng** [comment]
@atian25 
I will use it.Thank you for your answer.
