### ISSUE TITLE
egg-mongoose 没有提供 index.d.ts

### ISSUE THREAD

**Issue by Abreto** [eggjs/egg#2691]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
PR is welcome

**Comment by BaffinLee** [comment]
PR: [eggjs/egg-mongoose/pull/22](https://github.com/eggjs/egg-mongoose/pull/22)
