### ISSUE TITLE
站点favicon.ico读取不到？

### ISSUE THREAD

**Issue by aqtata** [eggjs/egg#2692]
* **Node Version**:10.4.0
* **Egg Version**:2.9.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:windows
* **Mini Showcase Repository**:

将egg-static插件的prefix设置为'/'，然后访问"http://127.0.0.1:7001/favicon.ico"
显示的是egg默认的图标，而不是我自己的favicon.ico文件，我本以为是路径问题，所以我在图标文件同目录下放置一个其他文件，都能正常访问。请问是怎么回事。

**Comment by atian25** [comment]
not recommended to set prefix to `/`

https://github.com/eggjs/egg/blob/master/config/config.default.js#L168

**Comment by ggd543** [comment]
> not recommended to set prefix to `/`
> 
> https://github.com/eggjs/egg/blob/master/config/config.default.js#L168

please give an example
