### ISSUE TITLE
生产环境下怎么优化（减少）内存占用

### ISSUE THREAD

**Issue by lkspc** [eggjs/egg#2696]
* **Node Version**: 8.x
* **Egg Version**: 2.4.1

目前在一个 BaaS 平台上部署 node 项目，经测试，一个 express-generator 生成的项目启动大概占用 60-80M 内存， 类似的 koa 项目占用 100M 左右， egg-init 初始项目直接超过 256M。

这个平台上基础配置就是 0.5CPU 和 256M 内存，所以 egg 部署上去内存就爆了，有没有什么办法可以优化下内存？ 日志文件这块在这个平台上是无用的，阉掉这部分有没可能减少内存？

**Comment by atian25** [comment]
只开 1 个 worker

**Comment by lkspc** [comment]
@atian25 目前就是只开了一个 worker 的

**Comment by atian25** [comment]
我本地空项目 100 内。
