### ISSUE TITLE
httpclient如何以formdata的方式传输数据

### ISSUE THREAD

**Issue by RenShine** [eggjs/egg#2705]
按官方文档的做法做了没有加content Type : json
但是从anyProxy的请求头里可以看到还是把数据放到了body中
![image](https://user-images.githubusercontent.com/6385962/41590970-f96c1a3c-73ea-11e8-9b2f-895a6f4abbdb.png)

我想要浏览器上这样的效果
![image](https://user-images.githubusercontent.com/6385962/41590988-0acfc238-73eb-11e8-9868-50a62225de56.png)

我有尝试过用request-promise-native  它有提供一个formData的选项  使用之后在anyproxy中是能看到一个类似于上传文件的那种数据格式

**Comment by RenShine** [comment]
origin里面多加了个http  打扰了

**Comment by oliviazhangjuan** [comment]
> origin里面多加了个http 打扰了

请问是怎么实现的呢

**Comment by fengmk2** [comment]
默认 POST 请求传递的 data 参数就是以 `application/x-www-form-urlencoded` 传输的。
