### ISSUE TITLE
与 Elastic APM 集成的问题

### ISSUE THREAD

**Issue by cuiweiqiang** [eggjs/egg#2706]
请问如何与elastic apm集成？
目前使用了两种方式，均无法实现。
1. 使用`require('egg').startCluster`的方式，在项目根目录创建`index.js`文件，启动项目，APM没有收到数据；
2. 在`router.js`文件中加入
```javascript
var apm = require('elastic-apm-node').start({
  // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
  serviceName: 'xxxx-local',
  // Use if APM Server requires a token
  // secretToken: '',
  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: 'http://localhost:8200'
})
```
依然无法使用，项目运行正常。

在独立非eggjs 项目中启动入口加入上述代码，可实现apm的正常监控。

**Comment by atian25** [comment]
没用过 `Elastic APM` 不确定，它为何必须要求在第一行执行？

你的第一种方式，只是在 master 进程挂载了，因此 worker 和 agent 进程估计就没采集到。
第二种方式，router 的执行有点晚，不确定是不是这个原因。

目前要在所有进程的第一行执行的话，只能通过 NODE_OPTIONS 这个环境变量去注入 `--require` 的方式，可以看下 Node 文档

**Comment by cuiweiqiang** [comment]
@atian25 十分感谢回复。我这就去尝试一下。

**Comment by cuiweiqiang** [comment]
@atian25 `--require` 没有成功，不过找到了一种不优雅的解决方案。
通过`app.js` 在 `app.beforeStart` 中注入 apm ：
```javascript
require('elastic-apm-node').start({
  // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
  serviceName: 'xxxx-local',
  // Use if APM Server requires a token
  // secretToken: '',
  // Set custom APM Server URL (default: http://localhost:8200)
  serverUrl: 'http://localhost:8200'
})
```
光注入上述代码会出现在apm控制台无法解析path的情况，所以 hack 了 `elastic-apm-node` 这个模块，在其中 `lib/instrumentation/express-util.js` 的 `getPathFromRequest` 方法加入如下代码，
```javascript
else if (req._parsedUrl) {
    path = req._parsedUrl.pathname
  }
```
这样就会将项目中请求按照path分类，与非egg项目展示相似。

另，这种方法并没有经过严格测试。

**Comment by popomore** [comment]
@atian25 startCluster 加一个 require 参数？

**Comment by atian25** [comment]
@popomore 在每一个进程包括 master 的第一行执行？

**Comment by atian25** [comment]
@popomore https://github.com/eggjs/egg-cluster/pull/73
