### ISSUE TITLE
单元测试时，提示 * not a function

### ISSUE THREAD

**Issue by luneice** [eggjs/egg#2711]
* **Node Version**:  8.0 以上
* **Egg Version**: 2.0.0
* **Plugin Name**: undefined
* **Plugin Version**: undefined
* **Platform**: ubuntu 17.10
* **Mini Showcase Repository**:
您好，在阅读官方测试文档后，我尝试写了如何去测试 Service，但一直提示我 *** not a function
TypeError: ctx.service.random.random.generateAuthCode is not a function

其中：
generateAuthCode 方法在 app/service/random/random.js

**Comment by luneice** [comment]
您好，我想测试的地方[上传到这里了](https://github.com/luneice/egg-issues)
错误提示：
  1) test/service/random.test.js
       generateAuthCode()
         send AuthCode:
     TypeError: ctx.service.random.random.generateAuthCode is not a function
      at Context.<anonymous> (test/app/service/random/random.test.js:23:54)
      at new Promise (<anonymous>)
      [use `--full-trace` to display the full stack trace]

**Comment by popomore** [comment]
You defined a static function

**Comment by luneice** [comment]
thanks
