### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by aqtata** [eggjs/egg#2712]
* **Node Version**:10.4.0
* **Egg Version**:2.9.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

文档里[路由定义](https://eggjs.org/zh-cn/basics/router.html#router-详细定义说明)这一节，用的verb方法，但是我发现最新版本中应该是用all，文档没更新吧？

**Comment by dead-horse** [comment]
verb 指的是下面提到的这些方法
![image](https://user-images.githubusercontent.com/985607/41646595-d2b1c560-74a6-11e8-82a1-1962362c0983.png)
