### ISSUE TITLE
egg-mysql 动态创建连接，根本不能用，官方回复一下

### ISSUE THREAD

**Issue by richard1015** [eggjs/egg#2716]
我用eggjs 框架写着一个爬虫逻辑，当本地有数据库时 请求回来的数据 存入mysql中，当服务器没有mysql数据库时，选择不存入 ， 面对这个场景  我想使用动态 创建mysql 连接，但是现在框架中是不可以的，如果本地没有mysql 数据库   调试时  项目直接保存停止了 ，无法进行 调试 而且
// {app_root}/app.js
module.exports = app => {
  app.beforeStart(async () => {
    // 从配置中心获取 MySQL 的配置
    // { host: 'mysql.com', port: '3306', user: 'test_user', password: 'test_password', database: 'test' }
    const mysqlConfig = await app.configCenter.fetch('mysql');
    app.database = app.mysql.createInstance(mysqlConfig);
  });
};

代码中的 mysql .createInstance 根本找不到这个方法啊

**Comment by richard1015** [comment]
感谢您的回答   https://github.com/richard1015/egg-example   代码我已刚刚提交

**Comment by richard1015** [comment]
![image](https://user-images.githubusercontent.com/13060263/41645198-d15aebdc-74a2-11e8-8b67-4a7dd2be0597.png)
项目启动时 ，我故意把mysql server 关闭掉， 项目启动时会报错，我想跳过这个错误，代码继续运行，如何 解决现在这种场景，求解     
谢谢您的回答 :)

**Comment by atian25** [comment]
by design, use `try catch` or `if (app.config.env)` or `getter for lazy init` according to your demand.

**Comment by atian25** [comment]
设计如此，你为何想故意关掉。

**Comment by richard1015** [comment]
我这个程序是这样设计的 ，数据库如果意外宕机，我的主程序 其它代理机制还是要继续运行的，所以想在这个地方  加一个 错误机制来处理 这个场景， 我原本想采用你们 框架中动态创建连接  那个机制，但是动态创建 mysql  你们提供的那个  createInstance 又找不到 ，这个地方不是说故意关掉，是为了模拟 数据库宕机的场景，还是希望官方能够修复一下， 看看有没有其他的解决方案 ，谢谢！！！

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

`app.mysql.createInstance` 是存在的。

**Comment by richard1015** [comment]
其实，我更想在程序beforeStart时， 如果当前数据库服务未启动，采用不加载 egg-mysql 插件，但是这个入口，又不知道，如何来实现，现在框架的逻辑是项目一旦启动config 已经被加载到缓存中，此时在beforeStart 这个入口修改应该已经来不及时了
![image](https://user-images.githubusercontent.com/13060263/41646323-0a87c508-74a6-11e8-8f6b-d2dce2fd65b3.png)

**Comment by atian25** [comment]
不用的，有兴趣的话，可以参与并回馈开源项目，如写点分享文章啥的，就是对我们最大的帮助。

BTW，你那段代码有 bug，在 forEach 里面去 insert 是异步的，没有 await，那 saveDB 这个函数返回的时候，其实是没入库完成的。
