### ISSUE TITLE
How to avoid 403 forbidden when it requset first.

### ISSUE THREAD

**Issue by luneice** [eggjs/egg#2718]
* **Node Version**: >= 6.0.0
* **Egg Version**: 2.21
* **Plugin Name**: undefined
* **Plugin Version**: undefined
* **Platform**: undefined
* **Mini Showcase Repository**: undefined
when i enable csrf check in egg, console got 403 error when it  first requset , but request again it was ok, because cookie was set  first time, so when i requset it again there is no error. how can i avoid 403 error when it firt requset?

**Comment by luneice** [comment]
I use vue for front-end and egg for back-end, when i clear cookies, any cookies are deleted in browser. So when javascript initiates ajax request for back-end resource,  i got the 403 error .And egg will set cookies, so when javascript initiates ajax again, there was no error.

**Comment by BaffinLee** [comment]
`csrf token` 就是这样工作的，先给你一个 `token` ，你请求的时候带上，不然就拒绝请求。

一般是后端渲染页面时把 token 写在页面隐藏表单域里。

**Comment by luneice** [comment]
@BaffinLee 是的，```csrf token```的工作原理是这样的，如果第一次不请求那么```csrf token```就无法设置。因为使用其他框架作为前端，使用```egg```作为后端，异步获取数据时，由于第一次请求没有```csrf token```发给```egg```后端，就导致第一获取结果没有响应，第二次请求才有结果。所以想知道有什么方法避免这种问题。

**Comment by dead-horse** [comment]
给其他系统调用的 API 接口不要加 csrf 校验

**Comment by jxDeveloper** [comment]
我也是遇到这个问题，前端也用了vue，打开登录页面，第一次点击登录按钮时，接口就报403错误，返回missing csrf token，此时的cookie上就会写入csrfToken，第二次点击登录时，就成功了，不会报错了。（我的请求头设置了拿cookie的csrfToken，因为第一次cookie上没有，报错了。点第二次的时候，因为cookie上有了，就没报错，但是怎样解决第一次cookie没有csrftoken的问题呢）
