### ISSUE TITLE
系统跑着跑着会直接宕机，请问如何查看日志？

### ISSUE THREAD

**Issue by BYmax1** [eggjs/egg#2719]
查了日志目录，看不到日志或者有我看不懂。 跪求各位帮助。

**Comment by atian25** [comment]
https://eggjs.app/zh-cn/faq.html#%E7%BA%BF%E4%B8%8A%E7%9A%84%E6%97%A5%E5%BF%97%E6%89%93%E5%8D%B0%E5%8E%BB%E5%93%AA%E9%87%8C%E4%BA%86

**Comment by BYmax1** [comment]
@atian25  你好，我知道看日志的目录。但是我把egg-agent和master-stderr.log,master-stdout.log都看了，并没有看到宕机的日志。

**Comment by atian25** [comment]
https://eggjs.app/zh-cn/core/logger.html#%E6%97%A5%E5%BF%97%E5%88%86%E7%B1%BB

common-error.log
