### ISSUE TITLE
针对egg在做更深层次的开发，做一套如django的框架

### ISSUE THREAD

**Issue by gzhappysky** [eggjs/egg#272]
python有django,ruby 有rails。期待node也出类似的框架，节省开发时间。。。

**Comment by atian25** [comment]
这块计划交给社区来做, 欢迎贡献.

**Comment by popomore** [comment]
如果要参考 django 做一套完全是可以的，egg 定制性很强。我们也希望从 python 转到 node 的开发者来提供这样的框架。

**Comment by gzhappysky** [comment]
是的，想像一下 egg+dva+antd 整合起来，这可是一个多刺激的事情

**Comment by popomore** [comment]
@gzhappysky 这个之后会有例子的

**Comment by gzhappysky** [comment]
期待。。。

**Comment by dead-horse** [comment]
先关掉了

**Comment by yi-ge** [comment]
我正在写这样的框架。

**Comment by yi-ge** [comment]
基于Koa2，同时提供基于vue2的同构解决方案。目前已经完成过半了。

**Comment by gzhappysky** [comment]
开源吧

**Comment by soulmachine** [comment]
@yi-ge 我们要的是  egg+dva+antd  整合起来的，不要Vue

**Comment by soulmachine** [comment]
egg+dva+antd + MongoDB 整合成一个类似于 Meteor 的方案，更加适合初创企业和小团队
