### ISSUE TITLE
如何解析content-type为JSON的数据

### ISSUE THREAD

**Issue by alanerzhao** [eggjs/egg#2722]
如题，因特殊需求，同事POST我的方式必须为content-type:'text/plain'
![image](https://user-images.githubusercontent.com/1327263/41772958-1a071468-764d-11e8-923c-997cb8efae9e.png)

**Comment by alanerzhao** [comment]
aa

**Comment by ShareQiu1994** [comment]
大佬 我也遇到同样问题了 如何解决的？
