### ISSUE TITLE
启动配置未生效

### ISSUE THREAD

**Issue by csm0912** [eggjs/egg#2728]
* **Node Version**: 6.6.0
* **Egg Version**:1.9.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在config.default.js文件中配置了自定义端口：
config.cluster = {
    listen: {
      port: 3303,
      hostname: '127.0.0.1',
    }
 }
当7001端口不被占用时，npm run dev启动项目，3303端口生效；但是当有另一个项目占用了7001端口，改项目启动时就默认启用7002作为端口。但是npm run prod不会出现这种情况，这是设计的目的是什么？如果想要在生产环境中也使用自定义端口应该如果配置

**Comment by atian25** [comment]
https://github.com/eggjs/egg-bin/blob/master/lib/cmd/dev.js#L102

在 egg-bin 里面做了自动适配端口。

**Comment by atian25** [comment]
启动顺序： egg-bin dev -> egg startCluster -> start worker

- 如果端口占用了，egg-bin dev 就会传递一个可用的 port 给后面（方便本地开发）
- 如果端口不占用，就不会传递 port，这样 egg 里面就会读取配置。

只有本地开发的时候，端口才可能会冲突，线上一般都是 docker 或者指定好配置的端口的。
而本地开发的时候，随机选择一个端口其实就可以了。

如果你确实是都指定，那在 npm scripts 里面都指定就好了， `egg-bin dev --port=` / `egg-scripts start ---port=`
