### ISSUE TITLE
如何知道单个worker启动或重启了

### ISSUE THREAD

**Issue by LzxHahaha** [eggjs/egg#2729]
假设给单个worker执行了一个耗时较长的定时任务，执行一半时worker因为意外情况挂掉了，如何在新的worker启动时执行一些检查操作

**Comment by atian25** [comment]
1. 不应该让 worker 挂掉。
2. 用外部存储的方式来记录你的任务状态。
3. 两次定时任务之间是没关系的，2 个 worker 之间也是无感知的。
