### ISSUE TITLE
关于mysql 的 Schema的问题

### ISSUE THREAD

**Issue by luoyjx** [eggjs/egg#273]
* **Node Version**: 6.9.1
* **Egg Version**: 0.7.0
* **Plugin Name**: egg-mysql
* **Plugin Version**: 1.0.1
* **Platform**: win32

在边看文档边写的过程中发现mysql插件未提供schema功能，是为了让mysql更加灵活的适用于不同数据库吗？
如果一个应用是从没有数据表开始，我暂时想到以下两个思路：
1. 在应用初始化时，执行sql脚本创建。
2. 另外做一个插件来完成这件事情。

那么我应该从哪个思路着手解决这个需求呢？

**Comment by jtyjty99999** [comment]
不是应该开发之前先建好表吗

**Comment by luoyjx** [comment]
我可以理解为使用第一种方案么？
