### ISSUE TITLE
EGG _SERVER _ENV指定环境重启存在缓存问题

### ISSUE THREAD

**Issue by Mr-try** [eggjs/egg#2731]
> 场景
config配置如下
![image](https://user-images.githubusercontent.com/7222172/41851831-cd9be2b8-78bb-11e8-987c-fb90db1b888c.png)
其中prd和default中设置不同的代理url，在中间件中使用。

> 问题描述
执行 EGG _SERVER _ENV=dev npm  run start时候是正确的，代理url也是正确的。但是当执行npm run stop&& EGG _SERVER _ENV=prod npm  run start 时候浏览器需要情况缓存才能走正确的代理url

 > 相关配置
package.json
```
   "start": "npm run stop && egg-scripts start --port=8000 --daemon",
   "stop": "egg-scripts stop"
```

**Comment by popomore** [comment]
浏览器缓存应该跟 egg 没关系

**Comment by Mr-try** [comment]
嗯 对的，忘记了 get缓存问题
