### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by lilly-lining** [eggjs/egg#2733]
* **Node Version**: 8.9.1
* **Egg Version**: 2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我们近期做了一个并发测试，发现并发数大于3的时候就会出现一下error，请给以建议，我们应该做些什么处理来解决呢？

ERROR 50 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET

**Comment by lilly-lining** [comment]
我就是简单加载了一个页面而已，没有做其他操作。模拟了3个并发。

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by lilly-lining** [comment]
没明白，我提交到GitHub要做什么呢？

**Comment by atian25** [comment]
提交一个最小可复现的代码库，否则怎么帮你分析问题？ 空对空？

**Comment by atian25** [comment]
feel free to reopen if provided more information
