### ISSUE TITLE
官方文档错误：单元测试

### ISSUE THREAD

**Issue by hjaurum** [eggjs/egg#2735]
页面：http://eggjs.org/zh-cn/core/unittest.html
在：测试执行顺序那一小节，最后一行文字，写的是：**每个用例会按 before -> beforeEach -> it -> afterEach -> after 的顺序执行，而且可以定义多个。**
然而经过测试，并不是，应该是before和after只在整个describe的生命周期执行一次，只有beforeEach和afterEach才会在每个用例中执行，因此描述有误，容易误导。

**Comment by atian25** [comment]
没感觉有什么毛病，熟悉 mocha 或 node 单元测试的应该都能理解吧，从 before 和 beforeEach 的语义上来讲也很清晰。

或者你觉得改成怎么样更合理？ 欢迎直接 PR 修改。

**Comment by dead-horse** [comment]
问题不大，有兴趣优化提 PR 吧
