### ISSUE TITLE
国际化不支持typescript, config/locale/zh-CN.ts取不到值

### ISSUE THREAD

**Issue by wv1124** [eggjs/egg#2736]
koa-locales:index.js强校验.js, .json, .properties

` for (let i = 0; i < localeDirs.length; i++) {
    const dir = localeDirs[i];

    if (!fs.existsSync(dir)) {
      continue;
    }

    const names = fs.readdirSync(dir);
    for (let j = 0; j < names.length; j++) {
      const name = names[j];
      const filepath = path.join(dir, name);
      // support en_US.js => en-US.js
      const locale = formatLocale(name.split('.')[0]);
      let resource = {};

      if (name.endsWith('.js') || name.endsWith('.json')) {
        resource = flattening(require(filepath));
      } else if (name.endsWith('.properties')) {
        resource = ini.parse(fs.readFileSync(filepath, 'utf8'));
      }

      resources[locale] = resources[locale] || {};
      assign(resources[locale], resource);
    }
  }`

**Comment by whxaxes** [comment]
这个是由于 `koa-locales` 做了 `js` 及 `json` 强校验，但是 locales 属于配置文件，我觉得直接用 js/json 问题也不大，这个似乎没必要用 ts 来写吧？

**Comment by wv1124** [comment]
主要是看到js不爽，代码全部ts突然来一个js。不知道的人肯定还会碰到这个问题。全部代码都是ts会越来越多

**Comment by whxaxes** [comment]
@wv1124  你可以用 json ...毕竟只是配置文件
