### ISSUE TITLE
egg-ons 错误刷屏

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#2737]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在 MQ 异常时，输出了太多错误日志

**Comment by gxcsoccer** [comment]
主要是什么异常？

**Comment by dead-horse** [comment]
先关了，之前没保留错误信息，后面出现了再开吧。线下沟通。
