### ISSUE TITLE
How can i run server in daemon mode in Windows ?

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#2738]
* **Node Version**: v8.1.4
* **Egg Version**: v2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Windows 10
* **Mini Showcase Repository**:

你好，我在 Windows 下直接使用 egg-init 生成的一个 Egg 项目，然后使用 `npm start` 跑，会弹出很多个  `CMD` 界面。

但是，我期望的结果是，`npm start`  然后，控制台提示创建服务器成功后就可以关闭这个 `cmd` 窗口，而不是还会自动创建很多个 `cmd` 窗口。

望解答，感谢！

**Comment by atian25** [comment]
跟 egg 关系不大，找下对应的 window service 相关资料，或者 docker

**Comment by skyfore** [comment]
@atian25 我网上搜索发现这个应该需要增加一个 `windowsHide` 的参数,然而 `npm script` 是由 `egg-bin` 来进行控制的, 所以我才会认为这个与 `egg` 有关联.

> 相关资料: 
https://github.com/Unitech/pm2/issues/1749
https://github.com/nodejs/node/pull/15380

**Comment by atian25** [comment]
1. egg-scripts 目前没有计划支持 Windows，有需要的话自己写个 index.js 调用 startCluster 几行代码就搞定了，不过要自己配置下环境变量，具体看下 egg-scripts 源码，就几十行。
2. win 上推荐用 docker 来部署
3. 不推荐用 win 来做服务器

**Comment by skyfore** [comment]
@atian25  OK,十分感谢!

**Comment by cao-sir** [comment]
使用这个参数可以解决这个问题[windowsHide](https://github.com/nodejs/node/pull/15380)
分别在下面两个位置添加上这个参数：
1. 
```
//egg-cluster\lib\master.js
......
forkAgentWorker() {
    this.agentStartTime = Date.now();

    const args = [ JSON.stringify(this.options) ];
    const opt = {
      windowsHide: true 
    };
.......
`
2. 
```
//cfork\index.js
....
  /**
   * fork worker with certain settings
   */
  function forkWorker(settings) {
    if (settings) {
      settings.windowsHide = true;
      cluster.settings = settings;
      cluster.setupMaster();
    } else {
      cluster.setupMaster({ windowsHide: true });
    }
    return cluster.fork(attachedEnv);
  }
....
``` 
@skyfore 
@atian25

**Comment by qingdengyue** [comment]
> v9.4.0 ： The windowsHide option is supported now.




Node 上已经有这个问题了。这个参数不起作用。[windowsHide](https://github.com/nodejs/node/issues/21825)

**Comment by qingdengyue** [comment]
child_process 也有这个参数
![image](https://user-images.githubusercontent.com/3230673/58443811-050daa00-8127-11e9-9498-69974ef3be15.png)
