### ISSUE TITLE
controller 改成类的方式

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#274]
## 背景

现在 controller 的使用方式和中间件是一样的，只是是洋葱圈的核心，不需要调用 next。

```js
// app/controller/home.js
module.exports = function* () {
  this.body = 'done';
}
```

当升级到 koa2，使用 async/await 又会又一些变化。 generator function 会变成 async function

```js
// app/controller/home.js
module.exports = async function (ctx) {
  ctx.body = 'done';
}
```

ctx 会作为参数传入，因为 async function 可以被写成 arrow function，this 的指向会有问题。

## 方案

controller 不使用中间件的方式，而使用类的方式，和 service 一致。

```js
// app/controller/home.js
module.exports = class HomeController {
  * index() {
    this.ctx.body = 'home';
  }
}

// app/router.js
module.exports = app => {
  app.get('/', 'home.index');
};
```

路由是指向 HomeController 的实例方法 index，每次请求都会实例化这个类。类方法应该也支持 ctx

```js
// app/controller/home.js
module.exports = class HomeController {
  * index(ctx) {
    // yield xxx
    ctx.body = 'home';
  }
}
```

之后使用 async/await，egg 会兼容两种写法，所以如果想把 controller 改成 async/await，那么只要修改方法

```js
// app/controller/home.js
module.exports = class HomeController {
  async index(ctx) {
    // await xxx
    ctx.body = 'home';
  }
}
```

使用面向对象有很多好处

1. 写法统一，升级成本低，并和 service 保持一致。
2. ctx 的认知一致，中间件去除 this 的概念，升级到 async await 无痛
3. 类可继承，自由度更好，比如基类提供检验

**Comment by atian25** [comment]
async  就好了，不需要 class  形式吧？ controller  应该不需要 this  去调用其他方法吧？

另外如果改，直接 ctx  不用支持 this  了吧？

**Comment by popomore** [comment]
上面更新了下好处

**Comment by atian25** [comment]
嗯，认同。在 1.0 版本就做了吧？

**Comment by atian25** [comment]
嗯，认同。在 1.0 版本就做了吧？

**Comment by popomore** [comment]
推荐使用哪种方式呢？

## this.ctx

```js
module.exports = app => class HomeController extends app.Controller {
  * index() {
    this.ctx.body = 'home';
  }
}
```

这种方式需要在构造函数里面赋值 `this.ctx = ctx`，和 service 一样需要提供一个 BaseController。

使用 `this.ctx.xxx` 稍微有点长

## 参数 ctx

```js
module.exports = class HomeController {
  * index(ctx) {
    ctx.body = 'home';
  }
}
```

使用参数传入，和以前的使用习惯不同，其他感觉没啥缺点，我比较倾向这种方式。

**Comment by atian25** [comment]
两种方式都支持吧, 前者和 service 统一了.

后者主要是为了适配 koa2

**Comment by popomore** [comment]
对，但是文档里写的时候应该要又推荐的方式

**Comment by atian25** [comment]
文档里面就这样?

```js
module.exports = app => {
  class HomeController extends app.Controller {
    * index(ctx) {
      ctx.body = 'home';
    }
  }
  return HomeController;
};
```
}
```

**Comment by dead-horse** [comment]
```js
module.exports = class HomeController {
  * index(ctx) {
    ctx.body = 'home';
  }
}
```

这个形式和不用类没有什么区别吧，要么就是用类的方式，要么就是直接:

```js
exports.index = function*(ctx) {
  ctx.body = 'home';
};
```

这样？

**Comment by fengmk2** [comment]
```js
module.exports = class HomeController {
  async index(ctx) {
    ctx.body = 'home';
  }
}

module.exports = class HomeController {
  * index(ctx) {
    ctx.body = 'home';
  }
}

module.exports = class HomeController {
  async index() {
    this.ctx.body = 'home';
  }
}

module.exports = class HomeController {
  * index() {
    this.ctx.body = 'home';
  }
}

module.exports = function* index(ctx) {
  ctx.body = 'home';
}

module.exports = async function index(ctx) {
  ctx.body = 'home';
}
```

看上面讨论下来，有6种方式。。

**Comment by dead-horse** [comment]
希望简化为两类，每一类都可以是 `generator function` 或者 `async function`

- 类模式（推荐写法）

```js
module.exports = app => {
  return class HomeController extends app.Controller {
    *index() {
      this.logger.info('hello');  // 可以和 service 一样自动加上所在的 scope
      this.ctx.body = 'hello';
    },
  };
}
```

- 方法模式（兼容写法）

```js
exports.index = async ctx => {
  ctx.body = 'hello';
};

exports.list = function*(ctx) {
  ctx.body = 'hello';
  // 兼容老的代码
  this.body = 'hello';
};
```

**Comment by atian25** [comment]
类的写法后面应该推荐 async 吧?

**Comment by popomore** [comment]
async 的单独写一篇好了，文档里面暂时可以保留 generator function 的写法，async function 要注明使用 node7 以上版本，等 node7 把 flag 去掉吧。

**Comment by popomore** [comment]
我现在只实现了类的方式，现在 object 是完全向下兼容的，现在要考虑下 object 的使用方式。

**Comment by popomore** [comment]
不支持直接返回 async function，如

```js
module.exports = async ctx => {
  ctx.body = 'done';
};
```

**Comment by popomore** [comment]
文档需要改成推荐的写法。

**Comment by dead-horse** [comment]
改成类模式后有许多可以好玩的黑科技可以做了。例如做一个 `egg-rails` 插件，插件中覆盖默认的 controller 基类：

- egg-rails

```js
// app.js
module.exports = app => {
  app.Controller = class RailsController extends app.Controller {
    constructor(ctx) {
      super(ctx);
      this.params = Object.assign(this.ctx.param, this.ctx.query);
      // other helpers
    },

    success(body) {
      this.ctx.body = {
        success: true,
        body,
      };
    }
  };
};
```

- application

```js
// app/controller/user.js

module.exports = app => {
  return class User extends app.Controller {
    * get() {
      const result = yield this.service.user.get(this.params);
      this.success(result);
    }
  };
};
```

可以给 controller 和 service 的 this 上挂各种方法，而不用担心污染到 context 上的东西。 

@huacnlee

**Comment by dickson** [comment]
@dead-horse 定义基类的场景很常见，我也是从app.js做的挂接，但总觉的“时机”不太对，而且必须要持有app引用才能得到基础类型（Controller、Service）。不知是否有计划将 Controller、Service 类型从模块导出方便扩展呢？

`const Service = require('egg').Service;
class BaseService extends Service { ... }

// service/user
module.exports = class User extends BaseService { ... }
`

**Comment by atian25** [comment]
这个之前讨论过的，直接导出的话，不妥：
举个例子，我们有一个上层框架叫 yadan，继承于 egg，在 yadan 里面自定义了 BaseService，那如果我们导出了 egg.service 会让用户用错的：

```js
// {app_root}/app/service/user.js

// 错误的用法
const egg = require('egg');
module.exports = class User extends egg.Service { ... }

// 正确的用法是
const yadan = require('yadan');
module.exports = class User extends yadan.Service { ... }

// 或者现在的用法
module.exports = app => class User extends app.Service { ... }
```

基于这一点，为防止用户错用，还是倾向于现在的写法。

cc @popomore @dead-horse @fengmk2

**Comment by dead-horse** [comment]
@dickson 或者你将扩展写在其他文件里面，require 进来？

```js
// base_controller.js
module.exports = app => {
  return class BaseController extends app.Controller {

  };
}

// app.js
const baseController = require('./base_controller');
module.exports = app => {
  app.Controller = baseController(app);
};
```

**Comment by fengmk2** [comment]
> 但总觉的“时机”不太对

怎样时间不对，请说明

**Comment by atian25** [comment]
觉得 app.js 是`运行期`？  其实执行 app.js 的时候， 属于`加载期`，这么一想是不是就舒坦了 ^_^

**Comment by dickson** [comment]
@dead-horse @fengmk2 
^_^ 可能和自己之前使用强类型语言较多的关系，的确如 @atian25 所说，感觉 app.js 是在运行时。不过这个到不重要。

个人觉的稍显不便的地方是我在扩展 Controller 时，必须要持有app的引用，所以限制了只可以在 app.js(可以获得app引用) 里去处理。如果能在框架层面上(形如 extend/application.js )提供一个注入点，可能会更加清晰一些。 (个人拙见^_^ )

**Comment by atian25** [comment]
你可以把 app.js 理解为一个 main() 入口咯，按 @dead-horse 那种方式应该也能达到的你的需求了。

注入的那个方式，我感觉跟现在没啥区别，只是语法看起来稍微好看一点，但带来的问题如我上面说的那样，所以我个人倾向于不加。

**Comment by coolcao** [comment]
在egg文档中controller部分，有这样的描述：定义的 Controller 类，会在每一个请求访问到 server 时实例化一个全新的对象，而项目中的 Controller 类继承于 app.Controller，会有下面几个属性挂在 this 上。
这种方式和直接导出{list,detail}这种模块的方式相比，有和优劣？

**Comment by atian25** [comment]
@coolcao 没啥区别，看个人喜好，推荐用 class 的方式。

**Comment by popomore** [comment]
可以往下看，类的特点就是可以继承，自定义基类共享代码，其他没什么差异。

**Comment by coolcao** [comment]
@atian25 所有的回复我也看了一下，导出模块就如 @dead-horse 所说两种方式嘛，如果导出class的话，每次请求都会实例化一个对象，这样请求多了，controller对象，service对象会不会占用太多资源？如果导出的是模块对象，那么，所有的请求调用的其实是同一个函数引用，对吧？

**Comment by dead-horse** [comment]
创建类的消耗非常小，这个我们做过 benchmark 了，不要有疑虑。

**Comment by popomore** [comment]
如果 constructor 里做了大内存操作，是会有问题的。
