### ISSUE TITLE
国际化参数通过header 传递 会被默认的cookie 拦截 导致无法达到效果

### ISSUE THREAD

**Issue by shuxuezhang** [eggjs/egg#2746]
国际化参数通过header 传递 会被默认的cookie 拦截 导致无法达到效果 能不能 忽略cookie 中的locale

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by chaoningx** [comment]
@shuxuezhang 如果你不想用cookie生效的话，那就可以在i18n的配置中添加一项：writeCookie: false,
config.i18n = {
    writeCookie: false, // 不使用cookie 
  };
官方文档里边没有，但是可以看一下koa-locales中的实现。
这样你的header就可以生效了。
