### ISSUE TITLE
About egg-watche with middleware load logic

### ISSUE THREAD

**Issue by my9074** [eggjs/egg#2747]
* **Node Version**:8.9.*
* **Egg Version**: 2.*
* **Plugin Name**: -
* **Plugin Version**: -
* **Platform**: mac OS
* **Mini Showcase Repository**: -

egg-watcher 监听文件变动会自动重启，导致重新走 egg 的加载流程等步骤。
我使用了 [koa-webpack](https://github.com/shellscape/koa-webpack) 中间件想监听 client 文件的变动去触发 HMR。但这样导致每次更新 server 文件都会重新触发 webpack compiler 。
期望的是 koa-webpack 这类中间件，只关心自己想关心的文件变动去触发 HMR 。 而不是每次自动重启都走这样的流程。

**Comment by atian25** [comment]
client 的代码监控不应该加入到 egg-development 的监控目录，可以自己用 egg-watcher 独立监控和处理事件，或者去看下 @hubcarl 做的 easywebpack 的相关 egg 插件，可以参考下。
