### ISSUE TITLE
Egg 是否提供了一些关于阿里云产品的使用例子？

### ISSUE THREAD

**Issue by luneice** [eggjs/egg#2749]
* **Node Version**: 8.9.0
* **Egg Version**: 2.2.1
* **Plugin Name**: 阿里云产品插件
* **Plugin Version**: undefined
* **Platform**: undefined
* **Mini Showcase Repository**:
  在 npm 官网搜到了一些关于阿里云的库，但是里面的使用方法太简洁，不太会使用，我在哪里可以找到 
  更详细的示例？

**Comment by JacksonTian** [comment]
你可以描述下应用场景，我可以帮忙提供这个例子

**Comment by luneice** [comment]
@JacksonTian 您好，我想使用 egg 实现 OSS 的 STS 授权，请问怎么实现？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-oss

**Comment by luneice** [comment]
@popomore 这个看过，里面的例子是如何操作 OSS，关于具体 STS 授权没有提到，所以不知道怎么进行 STS授权。

**Comment by popomore** [comment]
if you set sts to true, it will return a STS client, the usage can be found in [this document](https://github.com/ali-sdk/ali-oss#wrapper-usage)

**Comment by luneice** [comment]
@popomore 我是希望 egg 将授权的临时密钥发给前端，给前端二次授权。返回一个 STS 前端我不知道怎么使用。

**Comment by atian25** [comment]
@luneice https://github.com/ali-sdk/ali-oss#wrapper-usage 这文档里面不是写了么。

ali-sdk 这个 SDK 本身是可以在 browser 里面使用的，初始化的时候有一个 stsToken 的入参。
你服务端拿到 STS 后，给到前端，然后前端用 SDK 去交互
