### ISSUE TITLE
【Feature】希望可以写一个 Atom 编辑器的调试插件

### ISSUE THREAD

**Issue by youngjuning** [eggjs/egg#2751]
[Feature] I hope you can write a debugging plugin for the Atom editor.

**Comment by popomore** [comment]
We won't provide this.

**Comment by youngjuning** [comment]
Thanks，The atom-ide-ui maybe can help me.I will try that.我是中国人。。。

**Comment by youngjuning** [comment]
I will publish a atom snippets plugin for eggjs.  : )
