### ISSUE TITLE
controller 如何调用 model

### ISSUE THREAD

**Issue by tolerance-go** [eggjs/egg#2754]
小型的项目里面，并没有太多请求级别的复用逻辑，我在想 controller 里直接调用 model 的方法可以非常节省开发时间，但是发现不知道如何拿到 model 的实例在 controller 内部，请问如何获取呢

**Comment by atian25** [comment]
this.ctx.model

please read egg guide docs

**Comment by tolerance-go** [comment]
@atian25 感谢解答 `this.ctx.model.models.regex.xxx`
