### ISSUE TITLE
全局错误在哪捕获？

### ISSUE THREAD

**Issue by musicode** [eggjs/egg#2756]
我看了 [异常处理](https://eggjs.org/zh-cn/core/error-handling.html) 的文档，但没找到一个想要的捕获全局错误的方法。

安装 `egg-onerror` 之后，在 `config.default.js` 里加了 `onerror` 也没调用，很无奈。

文档是否可以写的更清楚些？

**Comment by atian25** [comment]
我也很无奈，issue 能否写的更清楚一些呢？不是有 template 提示必须的内容么？

**Comment by musicode** [comment]
这个 issue 不是具体的 bug，我觉得应该没必要写环境版本之类的吧？

我处理错误的方式是 `ctx.app.emit('error', err, ctx)`，这样 egg 会自动写到 error 日志里，但是我希望能拦截处理下，比如发个报警短信啥的，但我没在文档里找到应该怎么实现。

**Comment by atian25** [comment]
> 5. 如果可以，请使用 `egg-init --type=simple bug` 提供一个最小可复现的代码仓库，方便我们排查问题。

**Comment by musicode** [comment]
多谢了，首先抱歉的是，我确实不太愿意去新建一个仓库，当然从你们的角度，这样做是最友好的。

我的配置其实很简单，在 `config/plugin.js` 加了一段

```js
exports.onerror = {
    enable: true,
    package: 'egg-onerror',
}
```

然后在 `config.default.js` 加了一段：

```js
config.onerror = {
    all(err, ctx) {
        console.log(err)
    }
}
```

然后抛一个错误：

```js
throw new Error()
```

发现并没有打印。

现在我改了一种方式，用 `app.on('error', function)` 可以正常拦截。

最后，我现在实现比较简单，用了一个第三方的推送服务，只需要拦截错误发个 http 请求即可，所以我暂时先这么处理了，如有不妥，还烦请告知，谢谢了

**Comment by atian25** [comment]
[『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)

这是节省双方的时间，最高效的交流方式。

像现在我们在 issue 上挤牙膏的交流了快 15 分钟，还是不知道问题是什么。

我猜测是应该是你应该还是配置错误了，最常见的那个错误估计：https://github.com/eggjs/egg/issues/2088

1. 不需要配置 plugin.js
2. config 的那个配置，你看看 https://github.com/eggjs/egg/issues/2088 是不是你配错了，我又花了 2 分钟本地试了下是没问题的。

**Comment by musicode** [comment]
好的，下次我新建项目再提 issue，这次麻烦了

**Comment by trhuo** [comment]
如果你在业务代码中写了try catch，那么你配置的onerror就不会执行了

**Comment by zwmmm** [comment]
我也遇到这个问题了 并且检查了上面说的并没有错 @musicode
