### ISSUE TITLE
eslint 工作方式及 .eslintignore 初始化问题

### ISSUE THREAD

**Issue by Aysnine** [eggjs/egg#2759]
* **Node Version**: 8.9.4
* **Egg Version**: 1.14.0
* **Plugin Name**: none
* **Plugin Version**: none
* **Platform**: Linux & Windows
* **Mini Showcase Repository**: none

启动 `npm run lint`，eslint 检测了非源码文件，（将前端项目打包在 app/public 下导致）大量报错，查看 .eslintignore 如下：

![image](https://user-images.githubusercontent.com/10137653/42169680-f9a63b0c-7e46-11e8-9f72-96575a4be4ef.png)

EggJS 首次安装与创建项目如下：

![image](https://user-images.githubusercontent.com/10137653/42169620-d99d0534-7e46-11e8-8f35-14054789ae55.png)

手动修改 .eslintignore 文件：
```javascriptcoverage
test/fixtures
app/public
logs
run
```
 eslint 检测可用，但是立即退出：

![image](https://user-images.githubusercontent.com/10137653/42170442-15f5764a-7e49-11e8-8622-a73f24973742.png)

此处 eslint 工作正常吗？
.eslintignore 文件在初始化时没有添加主要项吗？

**Comment by atian25** [comment]
feel free to reopen this issue if provided more information.
