### ISSUE TITLE
egg-mns 如何禁止消息被自动删除

### ISSUE THREAD

**Issue by stonegithubs** [eggjs/egg#2760]
* **Node Version**:v8.9.3
* **Egg Version**:2.9.1
* **Plugin Name**:egg-mns
* **Plugin Version**:0.0.13
* **Platform**:Centos7
* **Mini Showcase Repository**:https://github.com/Quinton/egg-mns/blob/master/lib/mq.js

关于egg-mns的问题，拉取消息后会自动删除
```js
// https://github.com/Quinton/egg-mns/blob/master/lib/mq.js
mq.notifyRecv(async function (err, message) {
        if (err) {
          app.coreLogger.error(`[egg-mns] handle notifyRecv error`, err);
          return false;
        }
        const ctx = app.createAnonymousContext();
        const subscriber = new Subscriber(ctx);
        try {
          return await subscriber.subscribe(message);
          // return false;
        } catch(err) {
          return false;
        }
});
```

**想禁止消息被自动删除，希望处理完消息后程序控制删除**
以上代码改成这样也不行还是会自动删除，请教下如何修改，谢谢！！！
```js
 mq.notifyRecv(async function (err, message) {
        if (err) {
          app.coreLogger.error(`[egg-mns] handle notifyRecv error`, err);
          return false;
        }
        const ctx = app.createAnonymousContext();
        const subscriber = new Subscriber(ctx);
        try {
          await subscriber.subscribe(message);
          return false;
        } catch(err) {
          return false;
        }
});
```
notifyRecvs文档说明：
http://armclr.incars.com.cn/Links/AliMNS?lang=zh-Hans
mq.notifyRecv(cb:(ex:Error, msg:any)=>Boolean, waitSeconds?:number)
注册一个回调函数来接收消息.
cb: 每收到一条消息，注册的回调函数就会被调用一次；如果回调函数返回true，收到的消息会被自动删除；如果你想自己执行删除操作，那么让回调函数返回false。

**Comment by BaffinLee** [comment]
`async` 函数无论你 `return` 什么，返回的都是 `Promise`，在这里会被当做返回 `true`。

**Comment by stonegithubs** [comment]
@BaffinLee 明白了，谢谢！
