### ISSUE TITLE
egg-bin 的依赖包 intelli-espower-loader

### ISSUE THREAD

**Issue by peterlevel1** [eggjs/egg#2761]
* **Node Version**: v8.9.4
* **Egg Version**: v2.2.1
* **Plugin Name**: egg-bin
* **Plugin Version**: ^4.3.5
* **Platform**: mac_os
* **Mini Showcase Repository**: https://github.com/power-assert-js/intelli-espower-loader/pull/19

包名: intelli-espower-loader

egg-bin 有一个依赖包 intelli-espower-loader，有一行代码有问题
这是我提交的PR https://github.com/power-assert-js/intelli-espower-loader/pull/19

如果说这行代码有问题的话，egg-bin的测试是跑不起来的，我现在好奇的是你们的测试代码是怎么跑起来的

**Comment by peterlevel1** [comment]
aha, thanks to @egg-bot , translate my codes into English.
@atian25 https://github.com/peterlevel1/egg-test-local
the detail has been written on the README.md

**Comment by peterlevel1** [comment]
@atian25 the egg-bin version is 1.13.0

**Comment by atian25** [comment]
为啥。。。 egg-bin 是项目依赖，你装为全局依赖了？

我本地跑了无法复现。

**Comment by atian25** [comment]
@peterlevel1  try the shell I paste and see whether it works at your pc ?

**Comment by peterlevel1** [comment]
![image](https://user-images.githubusercontent.com/8144592/42202817-6570e76e-7ecf-11e8-9b0a-869796afe724.png)

**Comment by peterlevel1** [comment]
![image](https://user-images.githubusercontent.com/8144592/42202852-861d73ba-7ecf-11e8-9e21-1e5a6d46701b.png)

**Comment by popomore** [comment]
Need reproduce

**Comment by darkmirrors** [comment]
> 为啥。。。 egg-bin 是项目依赖，你装为全局依赖了？
> 
> 我本地跑了无法复现。
> 
> ```shell
> $ egg-init --type=simple egg-test-xx
> $ cd egg-test-xx
> $ cnpm i
> $ npm run test-local
> 
> ➜  egg-test-xx npm run test-local
> 
> > test-xx@1.0.0 test-local /Users/tz/Workspaces/tmp/egg-test-xx
> > egg-bin test
> 
>   test/app/controller/home.test.js
>     ✓ should assert
>     ✓ should GET /
> 
> ➜  egg-test-xx more node_modules/egg-bin/package.json
> {
>   "name": "egg-bin",
>   "version": "4.7.1",
> ```

用的是你发的命令，但还是报错

**Comment by atian25** [comment]
@darkmirrors 没有可复现方式，是没法跟进的。

**Comment by darkmirrors** [comment]
> @darkmirrors 没有可复现方式，是没法跟进的。

## 环境
Node Version: v8.12.0
Egg Version: v2.2.1
Plugin Name: egg-bin
Plugin Version: ^4.3.5
Platform: mac_os

## 执行下列命令
``` bash
$ egg-init --type=simple egg-test-xx
$ cd egg-test-xx
$ cnpm i
$ npm run test-local
```
## 报错
![Uploading image.png…](https://user-images.githubusercontent.com/8144592/42202852-861d73ba-7ecf-11e8-9e21-1e5a6d46701b.png)

**Comment by popomore** [comment]
cnpm 更新下
