### ISSUE TITLE
agent 可以暴露接口给 app 调用吗

### ISSUE THREAD

**Issue by AlphaCodeZero** [eggjs/egg#2762]
* **Node Version**: v9.1.0
* **Egg Version**: v2.7.1

我注意到文档中有提到相似的场景：https://eggjs.org/zh-cn/advanced/cluster-client.html ，其中有提到调用类(invoke)，但我没完全看懂。
目前我的业务是这样的，agent 上维护了一个 sequelize 的长连接，而 workers 上没有，我希望的是所有的 workers 共用这个长连接。也就是说 agent 上写了一些增删改查的接口，在 service 里我就可以直接类似于这样调用：
await this.agent.findAndCountAll();
重要的是不仅调用，还把调用的结果返回给 workers，不知道是否能够实现。
Thank you!

**Comment by atian25** [comment]
为什么要在 agent 里面，直接在 app 就好了。

agent 里面不推荐做复杂的业务，而且 IPC 通信的话损耗不少。

**Comment by AlphaCodeZero** [comment]
在 app 里做也可以，但好像也有别的问题。

出于某些原因，我们的业务需要用到 MySQL 的临时表，这种东西是与连接相关的，假如有40个 workers，就会创建40个临时表。
假如一个请求过来了，我在 worker A 的临时表上增加一些数据，则需要在所有的临时表上同步这种增加（否则下一个请求很可能就查询不到刚刚新增的数据了）
egg 有提供 sendToApp 方法，但是我希望它像 Promise.all() 一样。每个 worker 接收到消息，做了异步操作之后，返回一个成功的信号。当所有 workers 都返回成功信号之后，sendToApp 才 resolve。
因为我希望在所有临时表上都成功同步了这种新增之后，才继续下一步操作并最终返回给前端 200 状态。
@atian25

**Comment by atian25** [comment]
自己封装就好了。

或者看 https://eggjs.org/zh-cn/advanced/cluster-client.html 哪里不懂的，直接交流就好了。 cc @gxcsoccer

**Comment by AlphaCodeZero** [comment]
封装的大体思路不是很清楚，可以稍微描述一下吗？
感谢~

**Comment by waitingsong** [comment]
lz 可以在agent上监听连接，然后把消息通过  [doc](https://eggjs.org/zh-cn/core/cluster-and-ipc.html) 转发给 app，由app执行具体逻辑。

我们有个业务需求是ocr识别，大致实现是一个app worker监听某个目录，发现有新增文件就读取然后做ocr识别。而ocr服务的查询、启停是由agent发出消息，在启动了ocr服务的worker上绑定 menssger.on() 事件处理。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-watcher 是一个实现的示例，可以参考下。
