### ISSUE TITLE
controller 下有tsx文件怎么配置？

### ISSUE THREAD

**Issue by zhangking** [eggjs/egg#2765]
* **Node Version**: 9
* **Egg Version**: 2.*
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

一个 ts 工程, 使用 `egg-bin dev -r egg-ts-helper/register` 启动，controller下的 tsx 文件没有被读取，请问需要如何配置？

**Comment by whxaxes** [comment]
为什么 controller 要写成 tsx ？目前 egg 的 loader 在 ts 开启下只会去加载 .ts 文件，不会去加载 .tsx

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
