### ISSUE TITLE
centos 下，this.service的指向问题

### ISSUE THREAD

**Issue by luogeng2017** [eggjs/egg#2768]
* **Node Version**:v10.5.0
* **Egg Version**:^2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:centos7
* **Mini Showcase Repository**:

Controller 中this.service的未指向Service下的文件,打印出来是这个样子
```
ClassLoader {
  _cache: Map {},
  _ctx:
   { request: { method: 'POST', url: '/api/user/login', header: [Object] },
     response: { status: 404, message: 'Not Found', header: [Object] },
     app:
      { env: 'local',
        name: 'meetingServer',
        baseDir: '/home/luo/work/meetingServer',
        subdomainOffset: 2,
        config: '<egg config>',
        controller: '<egg controller>',
        httpclient: '<egg httpclient>',
        loggers: '<egg loggers>',
        middlewares: '<egg middlewares>',
        router: '<egg router>',
        serviceClasses: '<egg serviceClasses>' },
     originalUrl: '/api/user/login',
     req: '<original node req>',
     res: '<original node res>',
     socket: '<original node socket>' } }
```
我调的是`const rslt = await this.service.user.user.getAuthByRoleid(res.roleid)`,报的是`Cannot read property 'user' of undefined`，在Windows里什么都正常

**Comment by atian25** [comment]
跟操作系统没啥关系，你确定你打包发布后， `app/service/user/user.js` 这个文件有在么

用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by luogeng2017** [comment]
@atian25 并没有用命令打包，在contos7上直接将项目拷过去了，npm 安装好依赖运行的。run dev也会报`Cannot read property 'user' of undefined`

**Comment by atian25** [comment]
你先检查在 centos 上有没有这个文件吧，提供可复现方式，否则没法帮你查。

**Comment by luogeng2017** [comment]
这个是仓库https://github.com/luogeng2017/test.git

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/42306722-aa91818e-8062-11e8-9954-7bc173de5034.png)

目录名大写了。。。。

**Comment by luogeng2017** [comment]
@atian25 我嘞去  在windows下毫不报错

**Comment by atian25** [comment]
Win 系统是不区分大小写的

**Comment by luogeng2017** [comment]
@atian25 嗯，谢谢，点赞

**Comment by luogeng2017** [comment]
问下。Windows server下应该怎么部署生产版本。 @atian25

**Comment by atian25** [comment]
写个入口文件即可。

不过好像最近有同学 PR，egg-scripts 支持 win 了

**Comment by Jialufeng** [comment]
遇到同样问题，大佬怎么解决的？
![image](https://user-images.githubusercontent.com/16443142/44461304-da943b00-a642-11e8-8d87-47b122047aee.png)

**Comment by luogeng2017** [comment]
@Jialufeng 将文件及文件夹名字统一换成小写

**Comment by Jialufeng** [comment]
@luogeng2017 
都是小写的
![image](https://user-images.githubusercontent.com/16443142/44511980-b9d3f000-a6eb-11e8-8813-f3ebf85f1e7b.png)

**Comment by atian25** [comment]
哪来的 db ？这样交流效率太低了，
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by Jialufeng** [comment]
@atian25  好的

**Comment by Jialufeng** [comment]
@atian25   天猪哥哥  我现在127.0.0.1:7001/api/xxx  的接口地址，访问端口是3000   ，
session 获取为空
 场景：   本地起的服务端口3000，接口127.0.0.1:7001/api/login 种下的session ，刷新的时候请求127.0.0.1:7001/api/list 获取session是空的 。麻烦问下是有跨域问题吗?
![image](https://user-images.githubusercontent.com/16443142/44778838-91973600-abb0-11e8-918b-f9c31c0ce264.png)
request：
![image](https://user-images.githubusercontent.com/16443142/44778922-b68ba900-abb0-11e8-9829-9b1ff53203ef.png)
