### ISSUE TITLE
自定义日志怎么打印出日志呢

### ISSUE THREAD

**Issue by gd-ldj** [eggjs/egg#2769]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by gd-ldj** [comment]
1

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
