### ISSUE TITLE
validate 规则中 int 类型是否支持字符串形式的数字

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#277]
@fengmk2 按照egg-rest的文档，我可以直接写如下代码

```
exports.createRule = {
  username: 'email',
  password: {
    type: 'password',
    compare: 're-password'
  },
  age: {
    type: 'int',
    required: false
  }
};
```
来检查create时的参数，并且可以检查age类型int。
但实际中是接收到的数字参数无法通过该判断。
不确定是文档错误还是模块错误，确认后我可以提交PR。

**Comment by duncup** [comment]
如果视为bug，增加类似代码到int判断逻辑内修复可否？
```
var age =  parseInt(this.query.age);
this.query.age = age == this.query.age ? age : this.query.age ;

```

**Comment by dead-horse** [comment]
没看懂。但是参数肯定是在 post 上，不然 query 上不可能存在 int 类型的参数。

**Comment by duncup** [comment]
首先我说的是get请求。
你可以理解我的逻辑如下：
所有验证是否为int类型的值都尝试做一次类型转换，然后和原值进行值等于判断。
如果值相等则用数字类型的值覆盖原值。

PS: 所谓值相等说的是  1 == '1' 之类的相等判断。我实在不知道叫什么合适了。

**Comment by duncup** [comment]
我实际尝试的情况是类似
```
exports.indexRule = {
  p : { type: 'int' , required: false},
  size: { type: 'int', required: false},
};
```
结果就是这个一直不生效。我也没有办法在这个操作上使用post传参。

**Comment by fengmk2** [comment]
默认使用 this.request.body 来进行验证的。

**Comment by dead-horse** [comment]
@duncup rest 的 create 方法用 GET？

**Comment by duncup** [comment]
不是create方法，是index方法。我用这个方法显示一个列表，如果用错了的话请指正。
有一个0和1的值在数据库，并且属于列表的过滤条件，可以理解为男女并且在某些时候需要单独取男或者女。使用的是mysql的enum类型或整形(当前是整形)
个人觉得如果过滤条件已经设置为整形的话一个字符串的数字转成数字类型的数字然后验证并直接使用转换后的值是不会导致意外情况并且符合类似需求的。
当然我在我在处理的项目上直接转换类型已经解决，但还是想提议一下。

**Comment by dead-horse** [comment]
https://github.com/node-modules/parameter#rule 看这个里面的规则， 每一条规则都有他具体的应用场景。

1. query 里面的参数一定是 string 类型，所以你不应该用 `int` 作为校验规则。
2. 你描述的这种类型的有 `enum` 校验规则：`p: { type: 'enum', values: [ '0', '1' ], required: false }`
3. 如果想要校验一个字符串类型的数字，可以使用 `id` 这条规则，如果觉得不满足需求，可以[自定义一个其他的校验规则](https://eggjs.org/zh-cn/basics/controller.html#自定义校验规则)。

int 类型的规则很明确，**必须是 number 类型，且是整数**。

**Comment by duncup** [comment]
明白，似乎我把不是这个东西的活考虑交给这个东西了。但是建议doc上注释一下关于get请求的问题，不知道你们怎么认为？

**Comment by xiongsongsong** [comment]
我也遇到了，例如分页时的当前页和第几页，在query中是字符串，但使用时还需要转换为数字，略显麻烦。不知道框架是不是可以考虑处理下。

**Comment by atian25** [comment]
自定义个规则就好了
