### ISSUE TITLE
egg-scripts启动报错，debug后发现execArgvObj的问题

### ISSUE THREAD

**Issue by alivelee** [eggjs/egg#2770]
* **Node Version**: 8.11.3
* **Egg Version**: 2.6.1
* **Plugin Name**: egg-mongodb, validate
* **Plugin Version**:2.2.0 1.1.0
* **Platform**: archlinux

环境为typescript 和egg-init ts exapmle中的showcase一样

使用DEBUG=common-bin定位到问题，发现egg-scripts/command.js中的execArgvObj始终是没有defined
package.json中的配置和egg-init 后的ts项目一致。目前不清楚问题出在哪里

**Comment by alivelee** [comment]
报错日志没有什么有价值的 我已经用我自己的话说了一遍报错日志
TZ | 天猪 <notifications@github.com>于2018年7月5日 周四18:26写道：

**Comment by atian25** [comment]
请提供可复现方式后再开启
