### ISSUE TITLE
怎么得到axios post的数据

### ISSUE THREAD

**Issue by 934751285** [eggjs/egg#2771]
我用axios 发送了一个post 请求
![image](https://user-images.githubusercontent.com/6916647/42356644-35627112-8106-11e8-8c67-9ef976065ac5.png)

![image](https://user-images.githubusercontent.com/6916647/42356668-5258d612-8106-11e8-8721-17393dd1e20c.png)
后端打印this.ctx.request.body得到
![image](https://user-images.githubusercontent.com/6916647/42356728-b2023b9e-8106-11e8-90bc-23da27277298.png)
这里面却没有request.body,是那里写错了

**Comment by atian25** [comment]
没看懂，请提供最小可复现仓库

**Comment by BaffinLee** [comment]
你是打印了 `this.ctx.request` 吧，`request` 有自定义的 `toJSON` 方法，不会展示 `body` 的。

直接打印  `this.ctx.request.body` 看看是什么？是 `undefined` 的话提供一下复现问题的代码库

**Comment by KimYangOfCat** [comment]
@934751285  Hello,你好，我遇到了和你一样的问题， 关于您说的热更新的问题，我将前后端都重启过一次，但是依旧获取不到axios传递过来的值，请问还有其他办法吗？或者是我理解错了热更新问题吗？
@BaffinLee 我打印出来的body是一个空对象，请问我应该怎么处理？感谢～
### 前端代码
```js
login:function(){
                let reqData={
                    obj:"user",
                    data:{
                        email:this.input,
                        password:this.password,
                    }
                }
                console.log(reqData)
                this.axios.post(`http://localhost:7001/query`,reqData)
            .then(res => {
                console.log(res)
            })
            .catch(err => {
                console.log(err)
            });
            }
```
### egg 输出代码
```js
 async query() {
    const { ctx } = this;
    let params = ctx.request.body;
    console.log(params);//输出 {}
}
```
如果以上描述，没有提供有效信息，请回复我，我可以尝试提供最小可复现仓库。非常感谢～

**Comment by KimYangOfCat** [comment]
已解决，问题是axios的全局请求头设置错误，导致egg的bodyParser解析数据的过程出错～
正常情况下不设置也没有问题，但是一旦设置错误就容易导致后端解析出错，不同的数据需要设置的请求头的内容不一样，
或者说不同数据需要设置的请求头中的 Content-Type 值不一样，建议根据自己的数据类型设置合适的值。
打扰了，谢谢～
