### ISSUE TITLE
 A client (undefined:NaN) error [undefined] oc curred: 101057795:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown pro tocol:openssl\ssl\s23_srvr.c:643:

### ISSUE THREAD

**Issue by albertyou2** [eggjs/egg#2775]
有人见过这个错误么？配置了HTTPS出来的，但不是每次请求都报这个错
2018-07-07 09:36:38,888 ERROR 2120 A client (undefined:NaN) error [undefined] oc
curred: 101057795:error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown pro
tocol:openssl\ssl\s23_srvr.c:643:

**Comment by atian25** [comment]
没遇到过，可以自己 GOOGLE 看看。
一般不在 Node 做 HTTPS，在前面的 nginx 或 LSB 做

**Comment by albertyou2** [comment]
好的，谢谢，
