### ISSUE TITLE
eggjs源代码挂载到node docker上执行，修改源码后不会自动重启

### ISSUE THREAD

**Issue by chanmufeng** [eggjs/egg#2776]
前提：用vmware做的虚拟机，与wondows共享文件夹，虚拟机系统为centos7

windows上用vscode开发修改源码可以自动重启，但是同样的源码挂在到node8.11.3的docker上，
`docker run --name op -itp 7001:7001 -d --link some-mysql:mysql -v /mnt/hgfs/admin:/app  node:8.11.3  `
然后进入到docker容器中的/app
`docker exec -it '容器id' bash`
`cd /app`
`npm run dev`
后端代码
* **Node Version**:8.11.3
* **Egg Version**:2.9.1
* **Plugin Name**:
'use strict';

const path = require('path');

exports.nunjucks = {
    enable: true,
    package: 'egg-view-nunjucks',
};

exports.mysql = {
    enable: true,
    package: 'egg-mysql',
};

//参数校验
exports.validate = {
    package: 'egg-validate',
};
exports.session = true; // enable by default
* **Plugin Version**:
    "egg-mysql": "^3.0.0",
    "egg-scripts": "^2.5.0",
    "egg-validate": "^1.0.0",
    "egg-view-nunjucks": "^2.2.0"
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
https://github.com/eggjs/egg-watcher-chokidar
