### ISSUE TITLE
插件依赖插件    仍需要在当前插件手动 enable 的问题沉淀 及 discussion

### ISSUE THREAD

**Issue by linxuanwei** [eggjs/egg#2777]
场景：
开发者需要依赖 pluginA 这个插件去做开发，而 pluginA 依赖了各种其他插件，如下：
```
  "eggPlugin": {
    "name": "pluginA",
    "dependencies": [
      "cisCommonMongoose",
      "cisCommonAws",
      "cisBaseUtils",
      "cisServiceGridfs",
      "cisServiceCmsThirdparty",
      "cisServiceFlow",
      "cisBaseAgenda"
    ]
  },
```

在 pluginA 的 plugin.js  里 已经显示启用了这些插件：
```
  cisCommonMongoose: {
    enable: true,
    package: '@dr/cis-common-mongoose',
  },
  cisCommonAws: {
    enable: true,
    package: '@dr/cis-common-aws',
  },
  cisBaseUtils: {
    enable: true,
    package: '@dr/cis-base-utils',
  },
  cisServiceGridfs: {
    enable: true,
    package: '@dr/cis-service-gridfs',
  },
  cisBaseAgenda: {
    enable: true,
    package: '@dr/cis-base-agenda',
  },
  cisServiceCmsThirdparty: {
    enable: true,
    package: '@dr/cis-service-cms-thirdparty',
  },

```

但是在使用 pluginA 或者有别的插件依赖于 pluginA 的时候， 仍然需要再启用一遍上述pluginA 依赖的插件

对于使用 pluginA 这个插件/包的开发者其实他们并不关心 pluginA 依赖了哪些插件的，但是他们写代码的时候却无法避免地要去翻看 pluinA 依赖了哪些插件，然后再在自己的代码里（应用 or plugin）显示 enable 这些自己并不关心的插件

另，问下插件里的 plugin.js 是无效的？

**Comment by atian25** [comment]
- 插件是没有 plugin.js 这个东西的
- 插件就只负责插件自己的事，它只能简单的声明自己依赖哪个插件。
- 它 **不能** 帮开发者决定，某个插件是否开启
- 你的场景
  - 如果这个配置不是共性的，那开发者自行在 应用层 配置即可。
  - 如果是共性的，那就下沉到框架。

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/808

`egg-bin plugin install egg-view-nunjucks`

 然后自动会把依赖的插件，都配置到 plugin.js ，这样的话，对开发者就无感知了，这也是一种思路。

**Comment by popomore** [comment]
关联 issue 跟进
