### ISSUE TITLE
如何在 helper 中使用 config 定义的字段？

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2778]
* **Node Version**: v8.11.3
* **Egg Version**: 2.9.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOX
* **Mini Showcase Repository**:

如何在 helper 中使用 config 定义的字段？

如：需要用 config 中的随机字符串对密码进行加密：
`extend/helper.js`
```js
const aes256 = require('aes256');
modules.export = app => {
  const cipher = aes256.createCipher(app.config.pass_key);
  return {
    hashpass: pass => cipher.encrypt(pass),
  }
}
```

### What is Expected?
`app/controller/hash.js`
```js
const hash = this.ctx.helper.hashpass('123456')
// return hash
```

### What is actually happening?
helper.hashpass is not a function.

**Comment by atian25** [comment]
helper 是挂载在 ctx 上的，它的 this 就是 ctx，可以通过 `this.app.config`

**Comment by popomore** [comment]
extend/helper.js only support Class and Object.

**Comment by JZLeung** [comment]
@atian25 
难道我需要每次 hashpass 的时候都要 `aes256.createCipher(app.config.pass_key);` 一遍吗？

@popomore 
but it work well in the old version.

**Comment by atian25** [comment]
`createCipher` 这个是不能复用的吧？印象中。
如果可以的话，做一个判断是否已经初始化的逻辑吧。

或者你这类的方式，可以作为一个 service 的，不用做 helper

**Comment by JZLeung** [comment]
@atian25 
好的，感谢您的建议。

**Comment by spitWind** [comment]
依赖性太强了 每个文件模块的都可以自执行.的特性都没有
