### ISSUE TITLE
是否可以使用router 中间件解密入参

### ISSUE THREAD

**Issue by nxycdl** [eggjs/egg#2779]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

发起的post参数是加密的，我想在路由方法里面增加一个中间件专门去解密 ，发现好像在使用中间件的时候app.ctx 是undefined， 还有一种方法是放在Helper 类里面。每次都调用helper即可。不知道使用哪个方法最优。谢谢了。

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/basics/router.html#%E4%B8%AD%E9%97%B4%E4%BB%B6%E7%9A%84%E4%BD%BF%E7%94%A8

**Comment by atian25** [comment]
用中间件即可，要不就是如上的单个 router 加，要不就全局加，然后用 match 来过滤

`app.ctx` 没这玩意。。。 只有 `ctx.app`

https://eggjs.app/zh-cn/basics/objects.html

**Comment by nxycdl** [comment]
@atian25  谢谢发现是在写中间件的时候原来是
```
return  async function  decrypt (next) {};
```
改成
```
return  async function  decrypt (ctx,next) {}；
```
忘了传ctx了.
