### ISSUE TITLE
去除 worker_client

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#278]

**Comment by popomore** [comment]
https://github.com/eggjs/egg/blob/master/lib/core/agent_worker_client.js

https://github.com/eggjs/egg/blob/master/lib/core/app_worker_client.js

**Comment by fengmk2** [comment]
还有插件依赖么？没有就去掉吧，内部加速做兼容

**Comment by popomore** [comment]
watcher 在用 cc @shaoshuai0102

**Comment by luckydrq** [comment]
新的方式推荐使用啥？

**Comment by shaoshuai0102** [comment]
@luckydrq https://eggjs.org/zh-cn/advanced/cluster.html#cluster-client

**Comment by luckydrq** [comment]
👍
