### ISSUE TITLE
mysql 数据加密问题

### ISSUE THREAD

**Issue by zxmajunhong** [eggjs/egg#2783]
egg-mysql 支持直接执行mysql自带的加密函数吗？为什么查询的解密操作不能正确返回解密之后的值。
比如我直接使用db.query(`select DECODE(a, 'aaa') as a from B`) 返回的字段a的结果貌似不是解密之后的，我直接在mysql的可视化工具上比如navicat上执行上述的sql语句，可以正确返回解密之后的结果。这是为什么？

**Comment by popomore** [comment]
去 mysql 问
