### ISSUE TITLE
egg-view-ejs 关于layout模板报错TypeError path must be a string or Buffer

### ISSUE THREAD

**Issue by ruizhengyun** [eggjs/egg#2784]
=> config.default.js文件：
module.exports = appInfo => {
  const config = {};
  ...
  config.view = {
    defaultViewEngine: "ejs",
    mapping: {
      ".html": "ejs"
    }
  };

  config.ejs = {
    layout: "layout.html"
  };

  return config;
}

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by ruizhengyun** [comment]
用 `egg-init` 初始化最小仓库没有问题了，需要配置那几个文件都一样，问题估计出在自己搭建环节出了问题，谢谢方案。 @atian25 @popomore

**Comment by ruizhengyun** [comment]
用 egg-init 初始化最小仓库没有问题了，需要配置那几个文件都一样，问题估计出在自己搭建环节出了问题，谢谢方案。 @atian25 @popomore
