### ISSUE TITLE
官网最近常打不开

### ISSUE THREAD

**Issue by heytex** [eggjs/egg#2785]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

最近几天egg.js官网(eggjs.org)常常打不开(同事也是这样)，不知道是什么问题。
若有需要维护超过一定时间建议能出个公告预知一下，毕竟开发中需要常常查阅文档。

**Comment by fengmk2** [comment]
https://eggjs.app/

**Comment by heytex** [comment]
@fengmk2 感谢！
