### ISSUE TITLE
mysql 保存 emoji 表情数据时出错

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#2787]
先来看个报错信息：
<img width="906" alt="1" src="https://user-images.githubusercontent.com/16955472/42520523-04c0f9c0-8499-11e8-98d0-c13c93185e9d.png">
<img width="1047" alt="2" src="https://user-images.githubusercontent.com/16955472/42520524-04f6d89c-8499-11e8-9abe-2bb299119591.png">

执行 insert sql语句的时候由于username字段保存的数据包含emoji的表情（那个狗头），导致保存失败。查阅了很多资料，都说是数据库的字符集问题，数据库及数据表的字符及字符集已经从原来的utf8\utf8_general_ci改为utf8mb4/utf8mb4_general_ci

不知道为什么还是不行，请问下这种问题有解决方案吗？有想过在保存之前用base64转码，解析的时候再解码，但觉得这样处理很麻烦，很不优雅。

**Comment by BaffinLee** [comment]
`mysql` 连接的字符集`charset` 设对了吗？

```javascript
var connection = mysql.createConnection({
    host : 'host',
    user : 'user',
    password : 'password',
    database : 'database',
    charset : 'utf8mb4'
});
```

**Comment by Leungkingman** [comment]
@BaffinLee 果然解决了，谢谢
