### ISSUE TITLE
不使用 passport-local 如何进行鉴权？

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2789]
* **Node Version**: 8.11.3
* **Egg Version**: 2.9.1
* **Plugin Name**: egg-passport-local
* **Plugin Version**: ^1.2.1
* **Platform**:mac os
* **Mini Showcase Repository**:

---

因为写的是 api 接口，所以没有使用 `egg-passport-local` 进行用户账号密码的校验，也没有使用它来进行鉴权。

目前的问题是：
- 如果使用了 `egg-passport-local` 进行鉴权的话，目前无法返回正确的错误信息给前端。
- 如果不使用该插件，无法操作 `ctx.user`
  ```bash
  Cannot set property user of #<Object> which has only a getter
  ```

针对这俩问题：
- 能否使用 `egg-passport-local` 进行鉴权，并且可以手动处理具体的错误信息？
- 能否不使用 `egg-passport-local` 鉴权，但是依旧可以往 `ctx.user` 中写数据？

**Comment by BaffinLee** [comment]
提供一下最小复现代码？

**Comment by JZLeung** [comment]
@BaffinLee 
repo: https://github.com/JZLeung/egg-issue-2789

## 复现步骤
- 当我的后台只需要写 API 的时候：
  post to `/login`
  登陆失败，只返回一个已经被重定向到 `/login` 的页面。而我想输出的是**具体的失败信息**。
![image](https://user-images.githubusercontent.com/7995232/42583039-e47299ec-8562-11e8-96e5-463d6f995055.png)

- 当不使用 `egg-passport-local` 进行鉴权时：
  post to `/login2` 成功登陆，并写入 cookie 时。
  
![image](https://user-images.githubusercontent.com/7995232/42584022-d2a168ae-8564-11e8-8b3c-df9088db261f.png)
  访问需要鉴权的 `/auth2` 并且通过自主手动鉴权的中间件，发现无法修改 user。
![image](https://user-images.githubusercontent.com/7995232/42584080-f772c434-8564-11e8-9256-71cc0dfcf228.png)


## 暂时解决办法

使用其他字段，如 `login_user` 去代替原有的 `user` 对象。

**Comment by thonatos** [comment]
- 能否使用 `egg-passport-local` 进行鉴权，并且可以手动处理具体的错误信息？

  使用 `passport-local` 不能返回错误信息给前端，这个问题其实是 `flashMessage` 传递问题，其中一个 `可考虑` 的做法是在 `verify()` 捕获后 `redirect` 并带上参数，在那边就处理（比如继续跳回去并带上错误信息，前端就可以拿到错误信息了）；另一种是统一的异常处理。

- 能否不使用 `egg-passport-local` 鉴权，但是依旧可以往 `ctx.user` 中写数据？

  [Code #L5](https://github.com/eggjs/egg-passport/blob/0afce5b0d5fbc107730e10dad6aff915c03cf079/app/extend/context.js#L5)

```js
module.exports = {
  get user() {
    return this.req[this.app.passport._userProperty];
  },
}
```

如果同时已经开启了 `passport`，这里去设置显然是不合理的，不推荐这么做；可以考虑换 `ctx.account` 对象（仅示例），在中间件处理后设置，`passport` 对 `api` 路径忽略一下即可。其实上面的做法就是 `jwt` 在做的事情了。

- [JWT authentication plugin for egg](https://github.com/okoala/egg-jwt)
