### ISSUE TITLE
如何优雅的退出程序？

### ISSUE THREAD

**Issue by zhigangcao** [eggjs/egg#2794]
hi， deer egg-team
经常遇到这种case，在beforeStart中对一些配置做一些基本的检查验证，验证完后如果不通过，直接退出程序。例如：
` app.beforeStart(async () => {
   if(config有错误){
   app.close();
   }
  });
`

但这无法结束进程，如果使用process.exit()；则会报错，请问在启动阶段如何优雅的退出程序？

**Comment by killagu** [comment]
Throw error in beforeStart, if check not passed. App will close.

**Comment by atian25** [comment]
please provide more information, better to upload a github repo

**Comment by wangxuepeng** [comment]
Throw an error dose cause app exit, I made a mistake which incorrectly swallowed in one of my function.

Thanks for the quick response 👍
