### ISSUE TITLE
ts 模式下，egg-mongoose 创建的 model 不能在 ctx.model 下成功获取到代码提示

### ISSUE THREAD

**Issue by gu-xionghong** [eggjs/egg#2796]
[示例](https://github.com/gu-xionghong/egg-example)

按照官方文档 `npx egg-init --type=ts showcase` 创建的项目，引入 `egg-mongoose`的文档示例，在 `Controller` 下使用 `ctx.model` 不能够获取到对应的 `User model` 的提示，`typeings/app/model/index.d.ts` 有成功创建，参考如图:
![image](https://user-images.githubusercontent.com/12096816/42618671-59ef4d34-85e8-11e8-8ee4-540dc48d7ff6.png)

**Comment by BaffinLee** [comment]
`egg-mongoose` 的 `index.d.ts` 是我加上去的，但是有个失误，我提了个新 PR [#24](https://github.com/eggjs/egg-mongoose/pull/24)，合并之后你重新安装一下依赖应该就可以了。

但是支持程度只是说你写出 `ctx.model.User` 之后，能知道 `User` 是一个 `mongoose.Model`。

关于联想出 `ctx.model` 下面有哪些 `model`，需要 `egg-ts-helper` 支持，目前应该是只支持 `sequelize`，没支持 `mongoose` 的，需要 PR。

**Comment by gu-xionghong** [comment]
@BaffinLee 谢谢解答

**Comment by vagusX** [comment]
@BaffinLee 借助新的 egg-ts-helper 本身会生成 model 目录对应的 *.d.ts

可以在 typings 下, 新建一个 `index.d.ts`, 自行覆盖类型

```ts
import * as mongoose from 'mongoose';

declare module 'egg' {
  // extend app
  interface Application {
    model: IModel;
  }

  // extend context
  interface Context {
    model: IModel;
  }
}
```

这样就会有 `this.ctx.model` 下的提示了

**Comment by atian25** [comment]
@vagusX 应该需要配置一个文件的好像， cc @whxaxes 

https://github.com/eggjs/egg/issues/3480 完成后，应该就不需要配置就可以自动分析插件的

**Comment by atian25** [comment]
@vagusX 应该需要配置一个文件的好像， cc @whxaxes 

https://github.com/eggjs/egg/issues/3480 完成后，应该就不需要配置就可以自动分析插件的

**Comment by vagusX** [comment]
@atian25 @gu-xionghong 确实 `egg-ts-helper` 通过配置下即可完成 
* 配置文档 https://github.com/whxaxes/egg-ts-helper#configuration

```js
// tshelper.js
module.exports = {
  watchDirs: {
    model: {
      path: 'app/model',
      generator: 'class',
      interface: 'IModel',
      declareTo: 'Context.model',
    }
  }
}
```

**Comment by gu-xionghong** [comment]
@vagusX @atian25 感谢两位的解答，在此之前我都是手动书写每个 `model` 的 `interface` 的~

**Comment by whxaxes** [comment]
@vagusX  

```js
module.exports = {
  watchDirs: {
    model: {
      path: 'app/model',
      generator: 'function',
      interface: 'IModel',
      declareTo: 'Context.model',
    }
  }
}
```

function 这个 generator 就是 `ReturnType<typeof ${val}>` 的，可以去掉

**Comment by vagusX** [comment]
@whxaxes 你说的这种我试了 不加 
```ts
interfaceHandle: val => `ReturnType<typeof ${val}>`,
```
的话，只有 `this.ctx.model` 的提示，`this.ctx.model.User.create` 就 any 了...

**Comment by whxaxes** [comment]
@vagusX  function 的 generator 就是给 interfaceHandle 一个默认值，就是 `ReturnType<typeof ${val}>` ，https://github.com/whxaxes/egg-ts-helper/blob/master/src/generators/function.ts#L5

**Comment by vagusX** [comment]
@whxaxes 你说的是对的 我又试了一下 确实是不需要写 `interfaceHandle`
