### ISSUE TITLE
如何动态创建定时任务？

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#2797]
* **Node Version**:
* **Egg Version**:2.9.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

想要实现的是后台可以管理员添加定时任务，修改定时任务。。，类似这样的egg 的定时任务 可以做？

**Comment by atian25** [comment]
需要扩展 egg-schedule，看它对应的 README，集群扩展那里，需要配合外部的系统或存储来做。

**Comment by Ailein** [comment]
好的，谢谢

**Comment by Ailein** [comment]
看了几遍还是不知道 怎么集成到egg的定时任务那里，还是说我需要另外弄一个借助 第三方 弄一个队列处理？

**Comment by atian25** [comment]
简单的说， 不通过 egg schedule 自带的 Timer 来调度，而是通过一个事件来触发（如 redis 还是其他的消息系统），收到事件后就 sendOne 给 egg 的 worker 去执行，这样的好处是 worker 是可以水平扩展的。

而这个事件怎么触发，就按你自己的策略来做了。

**Comment by Ailein** [comment]
嗯，大概了解你说的，策略这里，我可能需要第三方模块（cron）？，比如我要加的定时任务是类似CronJob，
`var CronJob = require('cron').CronJob;
new CronJob
`

这样new 一个CronJob？这个CronJob 到时间执行的内容 就通过redis 发布 ，egg的agent 订阅这个任务，接着sendOne 通知worker 去执行?如果我需要修改这个任务，就是需要保存这个任务可能到数据库，然后停掉 这个 CronJob，重新动态new 一个，接着就又是通知 egg 那块了，是这样做不

**Comment by atzcl** [comment]
或者可以将 `定时任务` 操作成 `队列任务` 么？

**Comment by zhaoxiaobao** [comment]
@Ailein  最后实现了吗？

**Comment by beautycss** [comment]
@Ailein 最后实现了吗？

**Comment by CaoJ20132014** [comment]
@Ailein 动态定时任务实现了吗？

**Comment by BingruLin** [comment]
我以前为了不用消息队列，用数据库+定时任务实现了一版

# 动态定时任务方案

## 一句话总结

**运行时写文件 + DB 持久化 + Agent/Worker 双端注册 + DB 行锁单点执行 + 启动全量恢复。**

---

## 1. 整体架构

```mermaid
graph LR
    subgraph 业务调用方
        B[业务 Service 等]
    end

    subgraph 动态定时任务服务
        S[Schedule Service]
        DB[(schedule 表)]
        F[任务文件目录]
    end

    subgraph Egg 进程模型
        W[Worker 进程]
        A[Agent 进程]
    end

    B -->|创建 / 删除任务| S
    S -->|读写| DB
    S -->|写 / 删| F
    S -.->|messenger 事件| W
    S -.->|messenger 事件| A
    W -->|registerSchedule| SW[scheduleWorker]
    A -->|registerSchedule + start| SA[agent.schedule]
```

---

## 2. 创建任务链路

```mermaid
sequenceDiagram
    autonumber
    participant C as 业务调用方
    participant S as Schedule Service
    participant DB as DB
    participant F as 任务文件目录
    participant W as Worker(s)
    participant A as Agent

    C->>S: 创建任务({scheduleKey, scheduleTask})
    S->>DB: 行锁查重
    alt 已存在有效任务
        DB-->>S: 冲突
        S-->>C: 报错
    else 可写入
        S->>DB: insert 任务记录
        S->>F: writeFile(scheduleKey.js)
        S->>W: 注册任务事件
        W->>W: loadSchedule + registerSchedule
        W-->>S: CALLBACK
        S->>A: 注册任务事件
        A->>A: loadSchedule + registerSchedule + start
        A-->>S: CALLBACK
        S-->>C: 成功
    end
```

---

## 3. 删除任务链路

```mermaid
sequenceDiagram
    autonumber
    participant C as 业务调用方
    participant S as Schedule Service
    participant DB as DB
    participant F as 任务文件目录
    participant W as Worker(s)
    participant A as Agent

    C->>S: 删除任务({scheduleKey, byTrigger})
    alt byTrigger=true
        S->>DB: 软删除 disable=1
        Note right of S: 仅真正执行的 Worker 删 DB
    end
    S->>W: 取消注册任务事件
    W->>W: unregisterSchedule
    W-->>S: CALLBACK
    S->>A: 取消注册任务事件
    A->>A: unregisterSchedule
    A-->>S: CALLBACK
    S->>F: unlink(scheduleKey.js)
    S->>S: 清除 Node.js require 缓存
    S-->>C: 成功
```

---

## 4. 任务执行与 DB 锁

```mermaid
sequenceDiagram
    autonumber
    participant A as Agent cron 触发
    participant W as Worker
    participant S as Schedule Service
    participant DB as DB
    participant Biz as 业务逻辑

    A->>W: 触发任务
    W->>S: 对任务加锁
    S->>DB: FOR UPDATE + processing=1
    alt 抢到锁
        DB-->>S: needProcess=true
        S-->>W: true
        W->>Biz: 执行业务
        Biz-->>W: 完成
        W->>S: 释放任务锁
        S->>DB: processing=0
        W->>S: 删除任务(byTrigger=true)
        S->>DB: disable=1
    else 未抢到锁
        DB-->>S: needProcess=false
        S-->>W: false
        W->>W: 直接结束
    end
```

---

## 5. 启动恢复

```mermaid
sequenceDiagram
    autonumber
    participant A as Agent
    participant W as Worker
    participant S as Schedule Service
    participant DB as DB
    participant F as 任务文件目录

    A->>W: 应用就绪后发送初始化事件
    W->>S: 从数据库恢复任务
    S->>DB: SELECT * WHERE disable=0
    loop 每条记录
        S->>F: writeFile(scheduleKey.js)
        S->>W: 注册任务事件
        S->>A: 注册任务事件
    end
```

---

## 6. 关键事件与组件

| 组件/事件 | 所属层级 | 职责 |
|---|---|---|
| Schedule Service | Service 层 | 增删查锁任务、协调 Worker/Agent |
| 事件定义模块 | 公共定义 | messenger 事件名、表名 |
| schedule 表 | 数据层 | 任务持久化：任务标识 / 任务内容 / 执行状态 / 软删标记 |
| 注册/取消注册任务事件 | Agent 层 | Agent 真正注册/启动/取消 cron |
| 注册/取消注册任务事件 | Worker 层 | Worker 端注册/取消 schedule |
| 初始化动态任务事件 | Agent / Worker 层 | 启动时随机触发一个 Worker 恢复任务 |
| 获取 Worker 数量事件 | Agent / Worker 层 | 获取 Worker 数量，等待全量回调 |

---

## 7. 核心注意点

1. **任务即文件**：必须先把 JS 内容落到任务文件目录，`egg-schedule` 才能 `loadSchedule`。
2. **双端注册**：Agent 负责 cron 调度，Worker 负责业务上下文，缺一不可。
3. **DB 行锁**：执行状态字段 + `FOR UPDATE` 保证同一任务只被一个 Worker 执行。
4. **缓存清理**：`loadSchedule` 底层用 `require()` 把任务文件函数化，而 `require` 对同一文件只加载一次；因此在取消注册（Worker 和 Agent 两端）时要清除 Node.js require 缓存，避免后续同名任务创建时拿到旧的 cronJob。
5. **启动恢复**：数据库任务恢复只在应用就绪后由单个 Worker 触发一次。
