### ISSUE TITLE
如何自定义favicon.ico

### ISSUE THREAD

**Issue by laizhenhai88** [eggjs/egg#2798]
* **Node Version**:v8.11.1
* **Egg Version**:2.8.1
* **Plugin Name**:egg-static
* **Plugin Version**:egg默认自带
* **Platform**:centos7
* **Mini Showcase Repository**:

目的：希望通过egg-static插件，提供静态网页服务
1、配置config.default.js
```javascript
  config.static = {
    prefix: '/',
    dir: path.join(appInfo.baseDir, 'dist')
  };
```

2、dist文件夹下放置图片 favicon.ico
3、npm run dev或者npm start启动
4、访问http://ip/favicon.ico 得到的图标始终是egg默认的图标

好像是并没有经过egg-static插件处理，请问如何配置可以实现自定义ico？

**Comment by atian25** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L168
