### ISSUE TITLE
docker logs如何查看业务日志？

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#2799]
当前已设置
```
    logger: {
      level: 'INFO',
      consoleLevel: 'INFO',
      dir: '/usr/local/logs',
    },
```
本地的日志文件显示是没有问题的，但是我们有这样的需求，**希望可以通过`docker logs xxx`看到业务的日志**，但是目前只能看到启动日志。

>egg版本2.5

**Comment by BaffinLee** [comment]
参见 [https://docs.docker.com/config/containers/logging](https://docs.docker.com/config/containers/logging/)

![image](https://user-images.githubusercontent.com/17738556/42627604-134a04f6-8600-11e8-8274-da01ba1f7fac.png)

**Comment by xjchenhao** [comment]
> By default, docker logs or docker service logs shows the command’s output just as it would appear if you ran the command interactively in a terminal. 

谢谢回复，学习了。

我这个问题的解决方案我找到了：https://github.com/eggjs/egg/issues/1593

> 是eggjs禁用了线上环境的console输出，需要在config中设置一下。
    logger: {
      level: 'DEBUG',
      consoleLevel: 'DEBUG',
      disableConsoleAfterReady: false,   // 设置为false，docker logs就可以看见日志了
    },
> Ps: atian25说：不推荐用。线上服务关闭 console 好点。
