### ISSUE TITLE
使用egg-init生成ts版本的项目，安装依赖后启动服务，返回500

### ISSUE THREAD

**Issue by cutpictureboy** [eggjs/egg#2800]
* **Node Version**: 8.11.3
* **Egg Version**: 2.9.1
* **Platform**: macOS 10.13..5
* **Typescript version**: 2.9.2

使用`egg-init --type=ts showcase`生成项目，然后使用cnpm安装依赖，执行`npm run start`运行项目，页面打开是500
![image](https://user-images.githubusercontent.com/21117504/42632550-2067519c-8610-11e8-8458-073446ec8408.png)

**Comment by atian25** [comment]
please read the egg ts guide, need to run tsc before deploy
