### ISSUE TITLE
为什么每个js都要使用严格模式呢？

### ISSUE THREAD

**Issue by Erchoc** [eggjs/egg#2806]
js严格模式在es6中是默认使用的，为什么还需要重新声明使用严格模式？

**Comment by JacksonTian** [comment]
你是如何确认 ES6 中 use strict 是默认使用的？

**Comment by popomore** [comment]
和 egg 无关

**Comment by Erchoc** [comment]
sa

**Comment by Erchoc** [comment]
在eslint中配置使用es6 module语法就可以确定默认使用了啊，继续使用 `use strict`会提示在es6中不是必要的。

**Comment by atian25** [comment]
Node 中 ESM 还只是实验阶段，非正式特性。

该问题跟 egg 没关系，自行配置 eslint 即可。
