### ISSUE TITLE
升级egg-mongoose内置的mongoose至v5.2.1

### ISSUE THREAD

**Issue by LEAFERx** [eggjs/egg#2809]
* **Node Version**: v10.4.1
* **Egg Version**: v2.9.1
* **Plugin Name**: egg-mongoose
* **Plugin Version**: v3.1.0
* **Platform**: win
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
MR's welcome

**Comment by LEAFERx** [comment]
@dead-horse 我看到egg-mongoose有升级的pr 但是没有maintainer响应 egg-mongoose仍在维护中吗？

**Comment by dead-horse** [comment]
现在就是 5.x

**Comment by LEAFERx** [comment]
是5.0.x 希望能升级到5.2.x 5.2.x支持transaction

**Comment by dead-horse** [comment]
https://semver.org/ 去理解一下 semver
