### ISSUE TITLE
before all hook failed 

### ISSUE THREAD

**Issue by zhaojunlike** [eggjs/egg#2810]
我想测试单个文件中的单个方法测试，但是在只用了makecontext的方法中总是测试不成功，在测试utils这样的工具类的时候，不适用系统的bootstrap的时候就不会。请教一下我应该如何去解决这个问题。
![image](https://user-images.githubusercontent.com/13638996/42746671-8f1d93dc-890b-11e8-977c-4d5a13c7f549.png)
![image](https://user-images.githubusercontent.com/13638996/42746674-96015ff8-890b-11e8-8dd6-d71e94688673.png)
异常在before中抛出
![image](https://user-images.githubusercontent.com/13638996/42746860-72cfef4e-890c-11e8-8437-c89c58b63863.png)

![image](https://user-images.githubusercontent.com/13638996/42746849-609bc5e6-890c-11e8-9f25-f6206697cd02.png)

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

**Comment by zhaojunlike** [comment]
@atian25 First of all, thank you.    Maybe there is something wrong with my operation. I directly use the mocha use case of webstorm running. Maybe I should use yarn testing-local-ts file.js to execute a single file. Can you teach me how to perform tests individually? For example in mocha directly test ` ` ` it (...). ` ` `

**Comment by zhaojunlike** [comment]
it's the mocha runner settings
![image](https://user-images.githubusercontent.com/13638996/42792664-1700b1c4-89a9-11e8-812e-fb6ba80055e6.png)
