### ISSUE TITLE
loadToContext加载的模块在单元测试中获取不到

### ISSUE THREAD

**Issue by lijax** [eggjs/egg#2811]
* **Node Version: 9.1.0**:
* **Egg Version: 2.8.1**:
* **Platform: mac os 10.13.1**:

app.js
```
  app.loader.loadToContext(dataSourceDir, 'dataSources', {
    call: true,
    match: './*/*.js',
    caseStyle: 'lower',
    fieldClass: 'dataSourceClasses',
    directory: dataSourceDir,
  });
```

单元测试中`app.dataSourceClasses`和`ctx.dataSources`都是undefined

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

**Comment by lijax** [comment]
没问题了，是单元测试时一个消息没有触发的问题
