### ISSUE TITLE
Is it necessary to md5 your tracer.id in egg-opentracing-zipkin convert funciton ?

### ISSUE THREAD

**Issue by orangemi** [eggjs/egg#2812]
This is Problem about the source code.
https://github.com/eggjs/egg-opentracing-zipkin/blob/master/lib/zipkin_collector.js#L42
code above shows that use md5() from `utility` to convert opentracing tracer id to zipkin tracer id. I have no idea why doing this. Any explain?

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
You can see discussion here https://github.com/eggjs/egg-opentracing-zipkin/pull/2#discussion_r198491285

But we can support customizing traceIdGenerator.

**Comment by orangemi** [comment]
Aha. Thank you for your answer.
