### ISSUE TITLE
怎样在代码中退出程序（所有进程）？

### ISSUE THREAD

**Issue by yulidai** [eggjs/egg#2813]
需求原因：
为减少代码复杂度，所以遇到某些异常时将主动退出程序，然后由操作系统监控到后自动重启

目前尝试
1、process.exit 似乎不能完全退出（mac下看到还有3个node进程，ctrl+c后才可全部退出）。
2、google了很久，类似issues也都看过了，但都不符合我的需求

**Comment by atian25** [comment]
这样做是不合理的，遇到问题应该解决问题。

master 会自动监控 worker 挂掉然后重启。

如果你真的想终止，杀掉 master，虽然我非常不推荐逃避问题

**Comment by yulidai** [comment]
“杀掉Master”的eggjs代码应该怎么写？

PS：虽然有点不合理，但某些异常为第三方包引起的，所以只能这么处理

**Comment by atian25** [comment]
这些有问题的第三方包，不考虑更换掉？毕竟不靠谱的包，肯定会有其他更严重的问题。

**Comment by whxaxes** [comment]
@yulidai  master 本身要求健壮性，是不会提供任何可以被 worker 干掉的方法的，如果你硬是要实现这种，那么你可以基于 eggjs 封装一个上层框架，然后在 startCluster 的时候自己实例化 master ，然后监听 worker 的某个事件然后把自己干掉。但是强烈不建议这么做，这么做了，就相当于你引入任何一个插件都有机会把你的 master 给杀掉

**Comment by whxaxes** [comment]
哦...egg-scripts 也行 .... 反正都是不推荐

**Comment by yulidai** [comment]
好  谢谢了！
