### ISSUE TITLE
egg 怎么在处理文件前，提前获取到multipart 请求的fields?

### ISSUE THREAD

**Issue by ahuigo** [eggjs/egg#2814]
我查阅了文档, 分为单个文件, 以及多文件两种情况。都特别复杂，需要先处理了文件才能得到fields.
https://github.com/eggjs/examples/blob/master/multipart/app/controller/multiple.js

        const sendToWormhole = require('stream-wormhole');
        const parts = this.ctx.multipart({ autoFields: true });
        while ((part= await parts()) != null) {
          await sendToWormhole(part);
        }
        fields = parts.field; //貌似egg-multiparts 太复杂了

koa-better-body 使用起来就很simple， egg 可以在处理文件前直接获取到fields 吗？

   ```
    var body = require('koa-better-body')
    var app = koa()

    app
    .use(body())
    .use(function * () {
        console.log(this.request.body)    // if buffer or text
        console.log(this.request.files)   // if multipart
        console.log(this.request.fields)  // if json or _POST
        console.log(this.request.query)  
    }).listen(8080, function () {
        console.log('koa server start listening on port 8080')
    })

```
* **Node Version**: 10.0.0
* **Egg Version**: 4.7.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: MacOSX 10.12
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
看文档 https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6

**Comment by ahuigo** [comment]
@dead-horse 文档的例子是流式处理，并不能解决，**在处理文件files前**，拿到**其他的fields 字段**

**Comment by Currencywy** [comment]
@ahuigo 在在自定义control类封装multipart后，while无法循环，还需要其他配置？

**Comment by ahuigo** [comment]
@Currencywy 我更新了一下代码。流式处理后，就不能再获取数据了。while 当然不行。
所以我这个 multipart() 把files/fields 一并返回了

**Comment by Currencywy** [comment]
@ahuigo 之前表达错误。是multipart()内部的while 无法循环，无法返回files/fields

**Comment by atian25** [comment]
直接用 file mode 吧，别玩 stream 了
