### ISSUE TITLE
[feature]egg-bin cov support nyc params

### ISSUE THREAD

**Issue by yinseny** [eggjs/egg#2815]
* **Node Version**: 8.11.2
* **Egg Version**:  2.9.1
* **Plugin Name**: egg-bin
* **Plugin Version**: 4.7.1
* **Platform**: win64
* **Mini Showcase Repository**:

We want to enable mocha & nyc's teamcity reporter to show test cases & coverage in our teamcity build server.
We've added teamcity support for mocha using:
```json
  "scripts": {
    "cov": "egg-bin cov --reporter=mocha-teamcity-reporter"
  }
```

But for nyc, we found nyc's params are fixed in egg-bin, we are not able to pass anything to it.
```javascript
  getCovArgs(context) {
    let covArgs = [
      // '--show-process-tree',
      '--temp-directory', './node_modules/.nyc_output',
      '-r', 'text-summary',
      '-r', 'json-summary',
      '-r', 'json',
      '-r', 'lcov',
    ];
    ...
    return covArgs;
  }
```
We've tried add additional reporter in .nycrc or package.json files, but they all got overwritten by the fixed params.
Please help check if there's any way we can enable teamcity reporter for nyc.

**Comment by atian25** [comment]
config it by package.json

https://github.com/istanbuljs/nyc#configuring-nyc

**Comment by yinseny** [comment]
> We've tried add additional reporter in .nycrc or package.json files, but they all got overwritten by the fixed params.

doesn't work, it will be force overwrite by the params provided by egg-bin

**Comment by atian25** [comment]
right now, all args pass to `egg-bin test/cov` is passthrough to `mocha`.

maybe we could add some logic at `getCovArgs` to read `package.json`.

PR is welcome

**Comment by atian25** [comment]
or check whether `.nyc` is exists, then `getCovArgs` do nth

**Comment by yinseny** [comment]
seems when same key exists in both `.nycrc` & command line instruments, nyc will prefer the instruments.

This makes "reporter" & "exclude" keys in `.nycrc` being ignored because egg-bin always call nyc with -r & -x.

For `-x`, since egg-bin already support passing `-x` to nyc, i don't see the point for changing logic for it.

For `-r`, i'm considering a more generic approach:
maybe we can make `cov` support passing args to nyc as well. we can define an arg format like `--nyc-xxx`. then in `cov.js` we just remove the `--nyc` and pass `-xxx` to nyc. this could also make the experience consistent as we are controlling mocha & nyc args together in `cov` command.
I'll try create a pr for this, let me know your thoughts on this.

> check whether .nyc is exists, then getCovArgs do nth.

this might break all the '-x' logic currently implemented in `test/cov`

**Comment by atian25** [comment]
sure, PR is welcome.

**Comment by yinseny** [comment]
pr is done, please help review. thx.
[feat(cov): add nyc instrument passthrough](https://github.com/eggjs/egg-bin/pull/103)
