### ISSUE TITLE
如何在中间件中使用其他的中间件...?

### ISSUE THREAD

**Issue by assmdx** [eggjs/egg#2817]
`module.exports = (options,app) =>{
    return async function verifyToken(ctx,next)
    {
        const token = ctx.get("X-WaterExquisite-Token");
        const log = ctx.logger;
        const secret = options.tokensecret;
        const jsonwebtoken = app.jsonwebtoken;

        try
        {
            const parseRes = jsonwebtoken.verify(token,secret);
            if(null !== parseRes)
            {
                await next();
            }
            else{
                ctx.body = {
                    errno:401,
                    errMes:"session failed",
                    data:null
                };
            }
        }
        catch(e)
        {
            ctx.body = {
                errno:401,
                errMes:e.message,
                data:null
            };
        }
    }
}`

当我调试的时候，得到的jsonwebtoken值为undefined

我使用的jsonwebtoken："jsonwebtoken": "^8.3.0"

plugin.js中已经声明了：
`exports.jsonwebtoken = {
  enable: true,
  package: 'jsonwebtoken'
};`

**Comment by BaffinLee** [comment]
插件的 `package` 应该是 `egg-jwt` 吧？

**Comment by assmdx** [comment]
找到问题了，可以直接用
`const jsonwebtoken = require(‘jsonwebtoken’)`
