### ISSUE TITLE
如何设置多个静态资源路径的prefix 

### ISSUE THREAD

**Issue by xiangcs** [eggjs/egg#2823]
config.static = {
    prefix: '/public/',
    dir: path.join(appInfo.baseDir, 'app/public'),
    dynamic: true,
    preload: false,
    maxAge: 0,
  };
请问这个框架是否支持多个prefix, 我想再增加一个prefix路径。谢谢

**Comment by atian25** [comment]
不支持，静态资源尽量放 CDN，不要在 Node 侧搞。。

实在需要，自己写个 middleware 插入到 coreMiddleware 的 static 前面，篡改下 ctx.path

**Comment by xiangcs** [comment]
多谢！已解决
