### ISSUE TITLE
使用 egg-scripts 部署遇到问题

### ISSUE THREAD

**Issue by BoizZ** [eggjs/egg#2825]
* **Node Version**: 8.9.0
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-scripts
* **Plugin Version**: 2.5.0
* **Platform**: CentOS

我用 egg 线上部署遇到一个问题，线上部署的时候在项目目录运行 `npm stop & npm start`，5555 端口的进程没有完全退出，同时又在启动另外一个，启动的时候虽然做了延迟重试，但是最后会超时。

package.json
``` json
{
    "scripts": {
        "start": "egg-scripts start --daemon --title=xxx --port=5555", 
        "stop": "egg-scripts stop --title=xxx",
    }
}
```

**Comment by atian25** [comment]
`npm stop && npm start`

了解下 shell 的 `&`
