### ISSUE TITLE
eggjs生产环境可以热更新吗？

### ISSUE THREAD

**Issue by Webjiacheng** [eggjs/egg#2826]
需求：我作为一个公共的代理商，有很多下游来调用我的接口，同时我又要对接很多上游接口，所以每当有新上游需要对接时，我怎么在不影响下游的情况下添加新的接口或者更新一些文件让代码生效呢？谢谢各位大神的指教

**Comment by atian25** [comment]
不建议热更新，部署几台实例，前面挡个 SLB 切流量逐个重启即可

**Comment by Webjiacheng** [comment]
@atian25 你好，上游限制了IP白名单，负载过不去，而且还不能立马切，还有个对列，里面要排队处理订单，这有解决方案吗

**Comment by Webjiacheng** [comment]
不对啊，我不同的主机上的服务请求上游，ip怎么会是一个呢，不是多个吗


| |
嘉成备份
邮箱：13539995474@163.com
|

签名由 网易邮箱大师 定制

在2018年07月20日 21:29，TZ | 天猪 写道：

跟白名单没关系，对上游来说只知道你这个 slb/nginx 的 ip，后面有几台 Node 无感知。

队列这些肯定是用外部存储的。

难道你们不考虑横向扩容？

**Comment by popomore** [comment]
搜一下什么是 slb
