### ISSUE TITLE
这egg-mysql连接不上是什么问题？

### ISSUE THREAD

**Issue by chenxianqi** [eggjs/egg#2828]
![image](https://user-images.githubusercontent.com/27764334/43031638-37d299f8-8cd8-11e8-9bba-c38a4086f569.png)
![image](https://user-images.githubusercontent.com/27764334/43031641-40901016-8cd8-11e8-9c86-308e51af1ec1.png)
![image](https://user-images.githubusercontent.com/27764334/43031645-65689d0e-8cd8-11e8-89f8-f8a6668f9745.png)
![image](https://user-images.githubusercontent.com/27764334/43031649-6a165828-8cd8-11e8-9e96-8006d5ef8a6b.png)

**Comment by chenxianqi** [comment]
@egg-bot The configuration is correct

**Comment by BaffinLee** [comment]
命令行能登陆吗？

`mysql -hlocalhost -P8889  -uroot -proot --protocol=tcp smart_chat`

**Comment by chenxianqi** [comment]
@BaffinLee 其他应用都在用本地测试的

**Comment by popomore** [comment]
Mysql 服务的问题
