### ISSUE TITLE
部署后图片路径错误

### ISSUE THREAD

**Issue by hllhui** [eggjs/egg#2829]
我引入图片的方式是这样的：
<js>import logo from '../assets/logo.png';</js>
<js>  logo={logo} </js>

当我build之后，在public/static 生成了一张图片 ‘logo.bde1a9a9.png’
网页引用图片的路了变成了`http://localhost:7001/app/public/static/logo.bde1a9a9.png`，但正确的路径应该是`http://localhost:7001/public/static/logo.bde1a9a9.png`，我是哪里错了？

**Comment by atian25** [comment]
你的构建配置问题，跟 egg 无关。
