### ISSUE TITLE
egg-sequelize 中order参数问题

### ISSUE THREAD

**Issue by bupt1018wang** [eggjs/egg#2830]
model层查询代码如下：
    File.getFiles = async function(option, offset, limit, t) {
        let sqlOption = getSqlOption(option);
        return await this.findAll({
            where: sqlOption,
            offset: offset,
            limit: limit,
            order:  ['end_time','DESC']
        }, t);
    };

实际执行的sql语句如下：
sql: 'SELECT `id`, `md5`, `pid`, `uid`, `originname`, `filename`, `is_hash`, `status`, `path`, `start_time`, `end_time` FROM `file` AS `file` WHERE ((`file`.`status` = \'1\') AND `file`.`pid` = 3) ORDER BY `file`.`end_time`, `file`.`DESC` LIMIT 0, 20;' }
sql: 'SELECT `id`, `md5`, `pid`, `uid`, `originname`, `filename`, `is_hash`, `status`, `path`, `start_time`, `end_time` FROM `file` AS `file` WHERE ((`file`.`status` = \'1\') AND `file`.`pid` = 3) ORDER BY `file`.`end_time`, `file`.`DESC` LIMIT 0, 20;'

将order参数中的order 和DESC当成了两个参数

另外我将order改为order: 'end_time desc'时会报错：
nodejs.Error: Order must be type of array or instance of a valid sequelize method.

**Comment by BaffinLee** [comment]
```
order: [
  ['end_time','DESC']
]
```

参见 [sequelize 文档](http://docs.sequelizejs.com/manual/tutorial/querying.html#ordering)
