### ISSUE TITLE
module `uws` is no longer available

### ISSUE THREAD

**Issue by kevinaskin** [eggjs/egg#2832]
when I use socket.io in egg
`uws` engine is recomanded
but [uws](https://www.npmjs.com/package/uws) is no longer available at npm

may I have a question that in which way can I get it,
for I didn't find it at a trusted way.
Thx a lot

**Comment by thonatos** [comment]
As `µWS` engine has been deprecated, maybe you should consider the default engine.

if you still want to use `µWS` engine, get it by:
```bash
npm install --save uws
```

We will update the document later.

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/43

**Comment by thonatos** [comment]
#2884
