### ISSUE TITLE
eggjs中ctx.status如何设置自定义http status？

### ISSUE THREAD

**Issue by chanmufeng** [eggjs/egg#2833]
有特殊需求，需要自定义http status，然后前端进行这种status的确认，做出不同反应
但是现在使用
`ctx.status=209//一个不存在的http status`

会报错，请问如何处理？
invalid status code: 209
at Object.set status [as status] (E:\node\op-new\op-new-admin\node_modules\koa\lib\response.js:86:5)

**Comment by atian25** [comment]
这是 Koa 的限制 https://github.com/koajs/koa/blob/master/lib/response.js#L87

一般来说，不要去定制 http status，通过返回的 json 里面加字段来做。
因为日常我们访问会经过很多代理服务器，有可能会出问题。

实在需要覆盖的话，试试在 `app/extends/response.js` 里面去覆盖掉这个 setter 。（不建议）
