### ISSUE TITLE
Why the domain was block by the kungfunet?

### ISSUE THREAD

**Issue by wellenzhong** [eggjs/egg#2836]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

Egg.js is an amazing framework,but while I visit the document from China,I can't get access to the document page,cause the domain was block by the GFW.
i must open my shadowsocks in global mode,which will cause my API can not access. 
There is my question:
1.Do you guys consider to build a mirror inside China?
2.Any ideas can help me visit the document in PAC mode?

**Comment by atian25** [comment]
https://eggjs.app

**Comment by okoala** [comment]
you can visit https://eggjs.app
