### ISSUE TITLE
eggjs中间件如何获取到eggjs-jwt的ctx.state的值？

### ISSUE THREAD

**Issue by chanmufeng** [eggjs/egg#2841]
前提：

1. 中间件是自己编写的

2.router中我加入了app.jwt,并且controller中能正常获取到ctx.state中的值

但是，在中间件中获取ctx.state的值为undefined，请问如何解决？

**Comment by atian25** [comment]
贴下你中间件的代码，估计写错入参了

另外，建议用 ctx.locals，它是 state 的别名

**Comment by chanmufeng** [comment]
`'use strict';

const MODULE_TABLE = 'module';
const TABLE_NAME = 'verification';
module.exports = () => {
    return async function verify(ctx, next) {
        const { app } = ctx;
        const url = ctx.request.url;
        const method = ctx.request.method;
        if (method === 'POST' || method === 'PUT' || method === 'DELETE') {
            const token = ctx.request.header.authorization;
            console.log('token'+JSON.stringify(ctx.locals));//打印为{}
            console.log(token);
            const modulePath = filterModulePath(url);
          
            const post = await app.mysql.get(MODULE_TABLE, { path: modulePath });
            // 检测模块是否需要审核
          ***处理逻辑**                
                if (处理成功) {
                    ctx.body = ctx.ResultUtil.success('applied');
                    ctx.status = 200;
                    return;
                }

                // 操作申请提交失败
                ctx.body = ctx.ResultUtil.error(app.config.werror.ERR_OPERATION_APPLY);
                ctx.status = 200;
                return;
            }
        }
        await next();
    };
};`

**Comment by chanmufeng** [comment]
我知道在`next()`直接后是能获得的，如何在`next()`之前获得呢？

**Comment by chanmufeng** [comment]
`// verify a token symmetric - synchronous
var decoded = jwt.verify(token, 'shhhhh');
console.log(decoded.foo) // bar`
