### ISSUE TITLE
文件上传限制为2mb，上传3mb的 xlsx 文件不报错，保存时把文件截取了2mb存到磁盘了。 

### ISSUE THREAD

**Issue by avilang** [eggjs/egg#2842]
`exports.multipart = {
  whitelist: [
    '.xlsx',
    '.xls'
  ],
  fileSize: '2mb'
};
`
例子可用官方的多文件上传的例子，加上上面配置
[https://github.com/eggjs/examples/tree/master/multipart](https://github.com/eggjs/examples/tree/master/multipart)

**Comment by killagu** [comment]
Can not reproduce with your config.

**Comment by killagu** [comment]
@avilang You should listen `limit` event of stream in [line 19](https://github.com/avilang/test-egg-multipart/blob/master/app/controller/multiple.js#L19) like [here](https://github.com/eggjs/egg-multipart/blob/master/app/extend/context.js#L42).
