### ISSUE TITLE
vue + history-api-fallback + egg 导致页面请求时无法种上 csrfToken

### ISSUE THREAD

**Issue by my9074** [eggjs/egg#2843]
* **Node Version**: 8.*
* **Egg Version**: 2.*
* **Plugin Name**:  -
* **Plugin Version**: -
* **Platform**: mac
* **Mini Showcase Repository**: https://github.com/my9074/eggCsrfDemo

vue 的静态页面通过 webpack 打包到 ```app/public ``` 下。同时引入 ```history-api-fallback``` 中间件。将 html 请求 ***rewrite*** 到 ***index.html*** ，会导致无法种上 ***csrfToken***。

我大概看了下源码，猜测可能是由于中间件流程从 ```koa-static-cache```  直接出去了。导致没有进入到 ```csrf ``` 的中间件。

请问有什么解决方案吗？ 或者是我们的做法有问题？

**Comment by atian25** [comment]
既然是静态页面，html 入口一般都是极简的，直接通过 view 渲染就好了。

**Comment by my9074** [comment]
😊  @atian25  没太明白，能再 demo  的 repo 里发个 PR 借鉴下么？

**Comment by atian25** [comment]
你就用 egg-view-nunjucks 插件，把 index.html 改为 app/view/index.tpl

**Comment by my9074** [comment]
@atian25   如果没有 history-api-fallback 中间件，那如何解决 rewrite 的问题呢？比如我在别的路径 ```127.0.0.1:3001/other 刷新 就会 404 了。

**Comment by atian25** [comment]
写个通配的 router 啊

**Comment by my9074** [comment]
@atian25  哈哈~忘记了 😊 。 还有个问题，通过 ```controller render index.html ```  ，会经过所有的中间件。但是这种静态资源的请求不需要过某些中间件的情况，该如何解决呢？总不能每个中间件都忽略吧

**Comment by atian25** [comment]
index.html 不会被视为静态资源，js 和 css 才是

**Comment by my9074** [comment]
@atian25  这个可以接受，但是这就会导致经过所有中间件。比如有个检查权限的中间件需要调用后端的接口检查是否符合。但是 html 请求经过中间件就不合适了，而且会 401 导致无法获取 index.html 。我也不能在每个中间件设置个白名单吧~  这种场景我觉得还是比较常见的。尤其是 node 不负责页面跳转的只提供 API 的前后端分离 SPA 场景

**Comment by atian25** [comment]
检查权限的一般也就一两个中间件，全局配置下 match 或 ignore 不就好了。

你把入口文件放到 public 下，难道没考虑到更新问题么？ static 一般是 maxAge 一年的，你怎么更新入口文件？
