### ISSUE TITLE
Skywalking intend to support trace eggjs framework

### ISSUE THREAD

**Issue by ascrutae** [eggjs/egg#2844]
I come from Skywalking community and I'm the Skywalking-node agent author. we intend to support  trace the eggjs framework in next version, Ref issue https://github.com/OpenSkywalking/skywalking-nodejs/issues/18 . And we need help to check that intercept method is in right way after we finished this feature.

**Comment by atian25** [comment]
anything we could help ?

**Comment by atian25** [comment]
we had support `options.require` at https://github.com/eggjs/egg-cluster/pull/73

**Comment by ascrutae** [comment]
Thanks for your response. 

That's fine. but Skywalking want to tracing more detail, e.g. the cost about the controller method , the cost about each middleware method and so on. so we want to that someone can help me to check the method that we intercept in eggjs plugin is in the right way.

**Comment by ascrutae** [comment]
Hmm... almost.

Skywalking is a distributed tracing system, and APM. and it support three language(Java, NodeJs and .Net Core).

**Comment by atian25** [comment]
got, so maybe we could write a `egg-tracing-skywalking` plugin which provide a `Collector` to collect the data you want

**Comment by ascrutae** [comment]
@atian25 which version has support `options.require`?

**Comment by atian25** [comment]
we use '^' to import deps, so just reinstall deps, then you got it

**Comment by ascrutae** [comment]
Sorry for my mislead.

I had ask which version of egg-cluster had support the `options.require`, because I found that the date of laster version  is 12 Jun. and the date of this PR had merged is  8 Jul.

**Comment by atian25** [comment]
ha... it seams we forgot to publish,  done.

1.19.0

**Comment by ascrutae** [comment]
Thanks.

BTW, I had an question about the `options.require`? How can I make this configuration effective? add an new framework and write it in the `index.js` file or something else? @atian25

**Comment by atian25** [comment]
currently, developer need to start application with `egg-scripts start --require=` / `egg-bin dev --require`, all args will pass to egg startCluster options.

not recommended to write a framework cause it will limit your user's choose.

anther question: do we really need to hook everything at the first line ?
if it just about measure, I think it's more better to write a plugin for egg-tracing to collect / send data.

**Comment by ascrutae** [comment]
@atian25  Yes. The agent enhance the method by the module is loading. see [more detail](https://github.com/OpenSkywalking/skywalking-nodejs/blob/master/lib/require-module-hook.js#L34-L61). if this Agent isn't the first module that nodejs  load, it maybe miss some framework to enhance.

**Comment by ascrutae** [comment]
@atian25  Is there some way to override `start-cluster`?

**Comment by atian25** [comment]
- write your own `index.js` or custom framework (not recommended)

why did you need to override ? need to inject require without developer notify ?

recommended to provide user a guide to init start shell, or just write a `my-egg-scripts` to extends `egg-scripts` to inject require file by default.

**Comment by ascrutae** [comment]
Yes, because I want to that the developer don't know about the Agent, just add it and it works. I found that `start-cluster` is the entry point of egg framework.  So I want to override the `start-cluster` and Could you tell me more about how to extends `egg-scripts` to inject require file ?

**Comment by atian25** [comment]
just extends `egg-scripts` to provide a `CustomStartCommand` witch extends origin StartCommand to provide default value of `startCluster options.require`

https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/start.js#L18

**Comment by atian25** [comment]
or maybe we could add feature to `egg-scripts` to read require config from package.json

**Comment by ascrutae** [comment]
Thanks, I will try it and I will post the result when I finished.

**Comment by ascrutae** [comment]
[Skywalking Node.js Agent] has support tracing egg framework in 0.3.1 version, and here is the [screen snapshot](https://www.oschina.net/news/99456/skywalking-support-egg-framework)

**Comment by ascrutae** [comment]
Close this issue
