### ISSUE TITLE
router.redirect的一个问题

### ISSUE THREAD

**Issue by Myu1533** [eggjs/egg#2846]
* **Node Version**:8.11.2
* **Egg Version**:2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

 router.redirect('/cms/wealth/assets/news', '/cms/wealth/assets/news/1', 301);
router.get(/cms/wealth/assets/news/:page, controller.wealth.assets.news);
在重定向的时候，输出的连接地址为/cms/wealth/assets/news/:page

将news修改为其他命名后，重定向正常。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

**Comment by Myu1533** [comment]
cant reproduce today, even in the old project.i will close thie issue, if the problem come out again,i will reopen and provide detailed information.Thanks a lot.
