### ISSUE TITLE
如何使用sequelzie做关联数据表的分页查询

### ISSUE THREAD

**Issue by xiangcs** [eggjs/egg#2849]
想根据QuestionCategory表中的id查询，关联Question表的数据，因为数据太多，想对数量做个限制
，但好像不支持limit字段，请问有没有解决方案。

谢谢！

QuestionCategory.getQuestionsList = async function (catId, pn, pageSize) {
    let result = await QuestionCategory.findOne({
      include: [{
        model: app.model.Question,    //被关联的问题表
        through: {},
      }],
      order: [[app.model.Question, 'id']],
      where: {
        id: [catId], //定义获取分类列表的ID
      },
    });

**Comment by BaffinLee** [comment]
`findOne` 的 limit 不就是 1 吗，用 `findAll`

**Comment by xiangcs** [comment]
这里findOne, findAll都可以,但他们是相对QuestionCategory表的；我的意思是针对被关联的Question表做limit限制

**Comment by BaffinLee** [comment]
不支持，[sequelize#1897](https://github.com/sequelize/sequelize/issues/1897).

这个不是 egg 的问题，关掉吧。

**Comment by xiangcs** [comment]
好的，多谢
