### ISSUE TITLE
文档转换gitbook工具

### ISSUE THREAD

**Issue by ngot** [eggjs/egg#285]
用途：用于到内网begg文档去，同时能够增加内网文档

感觉需要写个转化器来搞

**Comment by ngot** [comment]
@fengmk2 提在这里了

**Comment by atian25** [comment]
我会比较倾向于用 nuxt.js 来搞, 把之前的 hexo 替换掉.

nuxt.js 是对 webpack 的 wrap, 针对 vue 项目的, 它的官网就是一个 vue 项目静态编译出来的.

https://nuxtjs.org/guide/#static-generated

**Comment by popomore** [comment]
他是前端渲染？

**Comment by atian25** [comment]
不是, 它是做同构渲染的.

但站点这里, 有 generate 指令, 把指定的 router param 执行后, 生成完整的静态页面.

https://nuxtjs.org/guide/installation/

可以看下 network.

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/22141251/1b2b6614-df2c-11e6-80e9-6c3afd19a74f.png)

**Comment by ngot** [comment]
nuxt.js 看起来不错。

**Comment by atian25** [comment]
嗯, 用 vue 的方式来做官网, 可以有很多想象空间, 包括应用市场那边, 可以比较舒服的写查询逻辑之类的交互.

**Comment by dead-horse** [comment]
相较于 nuxt，不如 next 呢。

**Comment by atian25** [comment]
@dead-horse  next 是 react 的, 我是 vue 系的, 哈哈....

**Comment by popomore** [comment]
1. 不要前端渲染
1. 不要服务端托管

其实我们现在只需要生成器

**Comment by atian25** [comment]
是的,  nuxt.js 的 generate 就是干这个的

**Comment by dead-horse** [comment]
没必要这么复杂，我们做文档合并只需要合并 summary 和文章的 md 文件，其他的 generator 随便用哪个都行的。

**Comment by atian25** [comment]
确实是离题了.  那个只是我这边有同学想练手搞搞, 回头让他们折腾, 搞得好再评估要不要换.

**Comment by popomore** [comment]
还有很多细节，比如 i18n，每个页面的链接都是相对的，这个其实有点麻烦。

**Comment by atian25** [comment]
除了 i18n 外, 未来可能还有多版本的需求吧.

我看好 nuxt.js 这类 generate 的原因就是可以很方便的做逻辑判断, 构建期其实可以分析到有没有对应的 i18n 然后做处理的.

**Comment by popomore** [comment]
没精力做还是用 hexo 吧。
