### ISSUE TITLE
egg-mongoose 如何使用中间件呢?

### ISSUE THREAD

**Issue by wpbeio** [eggjs/egg#2851]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在mongoose里有中间件,可针对query或者doc操作进行拦截处理,但是在egg里面如何使用这种中间件呢.
我在model里面写了一个basemodel,里面对update和remove这些操作进行了拦截处理.如何才能让同目录下的basemodel被引用到其他model里面呢?

之所以使用这个mongoose中间件,是因为要写一个操作日志,记录系统每次的修改新增等操作日志.或者大佬有什么其他比较好的方法可以实现这个功能.

**Comment by wpbeio** [comment]
另外在在model里面直接这样为什么不可以这样写呢?
const app = require('egg');
const mongoose = app.mongoose;

**Comment by BaffinLee** [comment]
```
// {app_root}/app/model/user.js
module.exports = app => {
  const mongoose = app.mongoose;
  const Schema = mongoose.Schema;
  const conn = app.mongooseDB.get('db1'); 

  const UserSchema = new Schema({
    userName: { type: String  },
    password: { type: String  },
  });

  // 中间件
  UserSchema.pre('find', (next) => {
    next();
  });
  UserSchema.post('find', (result, next) => {
    console.log(result);
    next();
 });

  return conn.model('User', UserSchema);
}
```

**Comment by wpbeio** [comment]
这个我知道,但是那么多的model 不能一个个加进去吧.可不可以写一个,然后其他model去引用呢?

**Comment by BaffinLee** [comment]
你应该需要 mogoose 的全局插件，看 [mogoose文档](http://mongoosejs.com/docs/plugins.html#global)

**Comment by wpbeio** [comment]
谢谢,我去试一下
