### ISSUE TITLE
egg-sequelize 能否配置自定义 model 路径？

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2855]
项目中主要用上的数据是 `mongodb`， model 文件夹下的都是提供给 `mongodb` 使用的。

但是现在项目有部分功能需要访问 `mysql` 则需要借助插件 `egg-sequelize` 来实现访问数据库功能。但是通过翻查代码发现，model 的路径是写死的，那么如果在一个项目中需要访问两种类型的数据库，model 应该也可以分开。

[`egg-sequelize/libb/loader.js`](https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L73)
```js
function loadModel(app) {
  const modelDir = path.join(app.baseDir, 'app/model');
  app.loader.loadToApp(modelDir, MODELS, {
    inject: app,
    caseStyle: 'upper',
    ignore: 'index.js',
  });

  for (const name of Object.keys(app[MODELS])) {
    const klass = app[MODELS][name];

    // only this Sequelize Model class
    if ('sequelize' in klass) {
      app.model[name] = klass;

      if ('classMethods' in klass.options || 'instanceMethods' in klass.options) {
        app.logger.error(`${name} model has classMethods/instanceMethods, but it was removed supports in Sequelize V4.\
see: http://docs.sequelizejs.com/manual/tutorial/models-definition.html#expansion-of-models`);
      }
    }
  }

  for (const name of Object.keys(app[MODELS])) {
    const klass = app[MODELS][name];

    if ('associate' in klass) {
      klass.associate();
    }
  }
}
```

能否在 `config.default.js` 中，增加一个配置项： `dir`，其默认值为 `model`。

直接提了个 [PR](https://github.com/eggjs/egg-sequelize/pull/59) 不知道是否能过。

谢谢各位大神。

* **Node Version**: 8.11.3
* **Egg Version**: 2.9.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**:  3.1.5
* **Platform**: mac
* **Mini Showcase Repository**: none

**Comment by dead-horse** [comment]
4.x 支持自定义 baseDir
