### ISSUE TITLE
【eslint】不支持扩展运算符(...)吗？还是说和Object.assign()有什么区别，会导致问题？

### ISSUE THREAD

**Issue by zuosamu** [eggjs/egg#2856]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
it's a es2019 feature which is not support by Node LTS.

BTW, it's an eslint configuration problem, not egg
