### ISSUE TITLE
this.ctx.service.otherService如何使用啊？

### ISSUE THREAD

**Issue by 982991084** [eggjs/egg#2858]
service里如何调用其他service

**Comment by atian25** [comment]
https://eggjs.app/zh-cn/basics/service.html#%E5%B1%9E%E6%80%A7

**Comment by 982991084** [comment]
@atian25 
`await ctx.service.otherService.v1.weChat.suite.access_token();`
err:Cannot read property 'v1' of undefined

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

**Comment by 982991084** [comment]
@atian25 https://github.com/982991084/issue-model

**Comment by atian25** [comment]
....

just use `await ctx.service.b.get();`

**Comment by 982991084** [comment]
I see , Thank you ！
