### ISSUE TITLE
curl request api response 301 

### ISSUE THREAD

**Issue by richard1015** [eggjs/egg#2859]
问题描述： 
  this.ctx.curl('https://api.readhub.cn/topic?lastCursor=&pageSize=20',{ dataType: 'text' });
result.status =301 
地址被301 了 但是浏览器中 输入地址就没问题，请问这种情况如何处理

**Comment by atian25** [comment]
被防刷了吧，自己研究下对方的防刷方式吧

**Comment by richard1015** [comment]
我使用 vue 中的axios 调用没问题，但是使用egg 的 curl就会301，我待会看看axios 中原理是如何处理这种调用

**Comment by atian25** [comment]
你 vue 试试隐身模式啥的，有可能是 axios 带上了 cookie 或 ua 啥的。

**Comment by richard1015** [comment]
followRedirect {Boolean} - 将HTTP 3xx响应作为重定向。默认为false。
改为true 即可， 已解决   :)
