### ISSUE TITLE
egg-watcher 去除 worker client 的依赖

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#286]
需要去除 worker client https://github.com/eggjs/egg/issues/278

**Comment by shaoshuai0102** [comment]
实现时遇到的问题：

- 缺乏 unsub 支持
- 如果想实现同步的获取数据的方法是不是只有用 override？并且 app worker 重新实现一遍缓存逻辑？
- egg-mock 需要改造 加入 detectPort 逻辑才能支持 cluster-client 模式，但是加到哪里是一个问题。目前想到的办法是同时拓展 egg.Application 和 egg.Agent，以便有机会注入 detectPort 逻辑。

**Comment by shaoshuai0102** [comment]
cc @gxcsoccer @popomore @fengmk2 

现在的使用感受是好像和之前一毛一样呢。。

**Comment by popomore** [comment]
代码提交上来看看

**Comment by popomore** [comment]
egg-mock 是在这里处理的 https://github.com/eggjs/egg/issues/170
