### ISSUE TITLE
[建议]让FileStream 支持bytesRead

### ISSUE THREAD

**Issue by ahuigo** [eggjs/egg#2860]
根据 [getFileStream 示例](http://mirror.eggjs.org/zh-cn/basics/controller.html)
我们在使用egg 上传文件时，使用的是busboy 的FileStream(ReadableStream) 而不是fs 的ReadStream.
所以FileStream 缺少bytesRead.

bytesRead 访问示例：
```
       // app/controller/test.js
        const rs = await this.ctx.getFileStream()
        const ws = fs.createWriteStream(uploadPath, { flags: 'a' })
        const bytesRead = await new Promise((resolve, reject) => {
          const ps = rs.pipe(ws);
          ps.on('finish', () => {
             resolve(ws.bytesWritten);
             console.log(ws.bytesWritten); //有值
             console.log(rs.bytesRead); //undefined
          })
          ps.on('error', reject)
        })
```
虽然通过ws/ps 的bytesWritten 可以得到rs.bytesRead, 
**但是对象属性不完整会给用户带来困惑**。（比如我误用FileStream.bytesRead 而调试了很久）

**Comment by popomore** [comment]
这个本来就不是文件 io，为何以 FileStream 为准，可以去 https://github.com/nodejs/node 问是否支持。

**Comment by atian25** [comment]
直接给那边提个 PR 吧

**Comment by fengmk2** [comment]
其实不需要也行的，你可以监听 data 时间，就知道了。

**Comment by ahuigo** [comment]
其实这个属性可有可无吧。只是有则完备一些吧。

我上面的实例应该是目前最简单的方案了吧。
监听data 也需要要自己计算bytesSize 吧
