### ISSUE TITLE
一次请求多次执行接口函数

### ISSUE THREAD

**Issue by kyleCodein** [eggjs/egg#2861]
起初在多个业务相关的数据表中发现了重复数据，逐个排查到请求日志，发现同样的请求打印出了两次，导致重复请求了接口函数。请问是因为koa并发请求阻塞造成的吗？在测试环境中还没能复现，在生产中也是偶发。

**Comment by atian25** [comment]
跟 Koa 没啥关系，检查下你的前端代码逻辑。
既然有 2 个请求日志，说明前端发了 2 次请求。
