### ISSUE TITLE
mockServiceError

### ISSUE THREAD

**Issue by 184609680** [eggjs/egg#2865]
单元测试的时候使用mockServiceError给一个service，mock了一个error，
在另一个单例上，执行了这个service，报了mock的那个错。
有木有移除这个error方式。
或者互不干扰的mock环境。

**Comment by fengmk2** [comment]
在 afterEach 加上 mock restore

**Comment by atian25** [comment]
https://github.com/eggjs/examples/blob/master/hackernews/test/app/controller/news.test.js#L16
