### ISSUE TITLE
security 插件的 methodnoallow 中间件 屏蔽 OPTIONS 请求的原因

### ISSUE THREAD

**Issue by Onlylonger** [eggjs/egg#2866]
![image](https://user-images.githubusercontent.com/19505200/43576710-8de24b4c-967c-11e8-88cd-5a02b962c1d7.png)

代码的地址: https://github.com/eggjs/egg-security/blob/master/lib/middlewares/methodnoallow.js#L7

**Comment by Maledong** [comment]
Just remove 'options' should be OK with you.

BTW：According to the document, it seems we've forbidden the requst in the way of `Options` on purpose!

![image](https://user-images.githubusercontent.com/40081831/43674592-1054dfc6-9809-11e8-86be-1e450fa1ed45.png)

https://github.com/Maledong/egg-security

**Comment by dead-horse** [comment]
@jtyjty99999 禁止 options 的原因是什么？我看 https://www.owasp.org/index.php/Cross_Site_Tracing 这里没有说 options 方法也不允许？

**Comment by Maledong** [comment]
@dead-horse：Fixed at https://github.com/eggjs/egg-security/commit/57bc4d9bb1334e699f87306820a0e6bb42d6aed8. So maybe this can be closed.

**Comment by fengmk2** [comment]
@Maledong Thanks a lot!

**Comment by Maledong** [comment]
@Onlylonger：Fixed and you can upgrate to the latest version to have a try.
