### ISSUE TITLE
自定义的增删改操作方法在egg-mysql中的遇到的事务支持的问题

### ISSUE THREAD

**Issue by chanmufeng** [eggjs/egg#2867]
`const conn = await app.mysql.beginTransaction(); // 初始化事务

try {
  await conn.insert(table, row1);  // 第一步操作
  await conn.update(table, row2);  // 第二步操作
  await conn.commit(); // 提交事务
} catch (err) {
  // error, rollback
  await conn.rollback(); // 一定记得捕获异常后回滚事务！！
  throw err;
}
`

以上为官网资料，可是实际开发中，针对事务的操作不可能只是调用egg-mysql中封装的增删改函数，更多的可能是结合业务逻辑进行一些封装，比如`bindTag()`，这种情况下`conn.xxx`便无法使用

总不能给每个函数都传递一个conn函数吧，求优雅的解决思路

**Comment by dead-horse** [comment]
可以自行封装一个 ctx.startTransaction，然后将 conn 挂到 ctx 上

**Comment by GracefulTing** [comment]
报错conn.rollback is not a function应该如何解决?
