### ISSUE TITLE
egg-sequelize的options.logging.info报错怎么解决？

### ISSUE THREAD

**Issue by dryqiao** [eggjs/egg#2869]
-->

* **Node Version**:8.11.2
* **Egg Version**:2.2.1
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.1.5
* **Mini Showcase Repository**:
创建一个sequelize实例，调用query方法去执行sql语句，结果报错
我的代码：
 `let db = new Sequelize(database, username, password, query.config)`
`db.query('select * from kanban_case',{})`
报错：`this.options.logging.info is not a function
    at Sequelize.log (E:\projects\Server\node_modules\_egg-sequelize@3.1.5@egg-sequelize\lib\loader.js:14:24)
 at Query._run (E:\projects\Server\node_modules\_sequelize@4.38.0@sequelize\lib\dialects\mssql\query.js:56:22)`

打断点看到sequelize的query方法进去了两次，第一次也就是我想查的sql是ok的，第二次传进去的sql语句是：`DECLARE @ms_ver NVARCHAR(20); SET @ms_ver = REVERSE(CONVERT(NVARCHAR(20), SERVERPROPERTY('ProductVersion'))); SELECT REVERSE(SUBSTRING(@ms_ver, CHARINDEX('.', @ms_ver)+1, 20)) AS 'version'`，然后options.logging.info就被覆盖掉了，请问怎么解决？

**Comment by solarhell** [comment]
https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js#L33

参考这里

另外为什么要自己显式 `new Sequelize`?
`plugin`会帮你做这件事，而且你的`package.json`里也没有`sequelize`，只有`egg-sequelize`。

**Comment by dryqiao** [comment]
@solarhell 需要动态地连接数据库，而且egg-sequelize不支持多数据源，package.json里我安装了sequelize

**Comment by popomore** [comment]
那是否去 sequelize 问
