### ISSUE TITLE
sequelize SQL日志输出顺序

### ISSUE THREAD

**Issue by yuedun** [eggjs/egg#2870]
* **Node Version**:8.11.3
* **Egg Version**:2.9.1
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.1.5
* **Platform**:win
* **Mini Showcase Repository**:

原生的sequelize是先在控制台输出SQL日志，等待数据返回，而在egg中是需要等待数据库返回数据才在控制台打印SQL日志。这个顺序的差异导致的一点问题是如果SQL查询较慢时，很难及时获取到SQL进行优化，只能等待输出后才能获取SQL进行优化

**Comment by popomore** [comment]
不在后面打你怎么知道慢呢

**Comment by yuedun** [comment]
@popomore 我的目的不是知道慢，我是想快速的得到这条SQL去explain一下慢的原因，而不是等待几分钟才得到SQL

**Comment by dead-horse** [comment]
有一个 benchmark 配置项，关闭后就不会打印时间，应该就会打印在 sql 执行前
