### ISSUE TITLE
 select now() as currentTime  报错

### ISSUE THREAD

**Issue by shiningshang** [eggjs/egg#2873]
* **Node Version**:6.3.0
* **Egg Version**:2.2.1
* **Plugin Name**:egg-mysql
* **Plugin Version**:3.0.0
* **Platform**:
* **Mini Showcase Repository**:

使用egg-mysql链接sls的时候报错了，sls也有一个jdbc协议的链接方式，但是他没有  select now() as currentTime； 这个语句，所以启动的时候就报错了

app.beforeStart(function* () {
    const rows = yield client.query('select now() as currentTime;');
    const index = count++;
    app.coreLogger.info(`[egg-mysql] instance[${index}] status OK, rds currentTime: ${rows[0].currentTime}`);
  });

注释掉就正常启动了

**Comment by popomore** [comment]
sls?
