### ISSUE TITLE
[Question] 单元测试中如何通过依赖注入的方式注入Test Double?

### ISSUE THREAD

**Issue by billwang1990** [eggjs/egg#2876]
问题描述： 才开始使用EggJS不久，有个疑问就是在写测试的时候。比如Service A会调用Model B（Controller调用Service同样道理），我想测试A是否正确调用到了B上的某个方法，这个时候我期望将B的测试替身注入到A中，然后验证B是否被正确调用。但是我发现使用了eggjs之后，我没有办法通过依赖注入的方式去使用测试替身了。egg提供的mock框架也比较弱，如下面代码，我也尝试通过去stub掉mockContext中的model，但是并没有什么用。
```
    it('should call mongoose', async () => {
        const ctx = app.mockContext();
        const modelStub = sinon.stub(ctx.model.accountModel, 'find')
        modelStub.returns(Promise.resolve([]));

        ctx.service.account.find('a');
        assert(modelStub.calledWith(a));
    });
```

请问官方使用eggjs后正确的打开方式是怎样？

**Comment by popomore** [comment]
你可以 spy 那个类的 prototype
