### ISSUE TITLE
engine使用ws chrome中会断开，而uws这个npm包已经找不到了

### ISSUE THREAD

**Issue by cheerego** [eggjs/egg#2877]
https://www.npmjs.com/package/uws

![image](https://user-images.githubusercontent.com/13394349/43713398-103c821a-99ac-11e8-9252-7419b8535e19.png)

查看之前的issue说chrome确实会有问题，换成uws就ok了。

**Comment by BaffinLee** [comment]
提供一下能复现问题的代码仓库？

**Comment by thonatos** [comment]
#2884

**Comment by dead-horse** [comment]
uws 还可以找到老版本的，这是 socket.io 的问题，这里先关了
