### ISSUE TITLE
关于 socket.id 的问题

### ISSUE THREAD

**Issue by gaoyangy** [eggjs/egg#2878]
请问 socket.id 是唯一的吗？还是说socket.id 可以自定义呢？

**Comment by gaoyangy** [comment]
我看了官方文档描述是 
注意： 每一个 socket 连接都会拥有一个随机且不可预测的唯一 id Socket#id，并且会自动加入到以这个 id 命名的 room 中

不知道有没有可以自定义的地方



------------------------------------------------------------------
发件人：I Robot <notifications@github.com>
发送时间：2018年8月6日(星期一) 19:30
收件人：eggjs/egg <egg@noreply.github.com>
抄　送：高阳阳 <gaoyangyang@hfjy.com>; Author <author@noreply.github.com>
主　题：Re: [eggjs/egg] 关于 socket.id 的问题 (#2878)

Translation of this issue:  About socket.id
Is socket.id unique? Or is socket.id customizable?

**Comment by x-cold** [comment]
id 是不能自定义的，如果你需要建立一个聊天室，应该创建一个 Room / Namespace

https://socket.io/docs/rooms-and-namespaces/

**Comment by BaffinLee** [comment]
是唯一的，`socket.io` 支持自定义 id ，不过 egg 的插件没有暴露出来。一般没必要自定义

**Comment by Maledong** [comment]
@dead-horse：Considering that more than one have requested for this, so I did to expose this interface for their usage.

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/44

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/42
