### ISSUE TITLE
redis存储session,如何设置过期时间

### ISSUE THREAD

**Issue by Tencent-Luis** [eggjs/egg#2879]
大神！redis存储session,如何设置过期时间？？
`config.redis = {
		client: {
			host: 127.0.0.1,
			port: 6379,
			password: ‘123456’，
			db: 0
		},
		maxAge: 120
	};`
是这样设置吗？

**Comment by BaffinLee** [comment]
```javascript
exports.session = {
  maxAge: 24 * 3600 * 1000, // 1 天
};
```
[文档](https://eggjs.org/zh-cn/core/cookie-and-session.html#session)
