### ISSUE TITLE
jsonp 重构

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#288]
## 现状

通过 `this.jsonp=` 来支持应用响应 jsonp 内容，并支持 [jsonp xss 过滤](https://eggjs.org/zh-cn/core/security.html#jsonp-xss)。

## 缺陷

只做了 jsonp xss 过滤，由于实际项目中，很可能会用 jsonp 来获取用户的敏感信息，甚至是直接进行修改数据库等操作，如果我们不默认进行防范，项目中使用可能会很容易的被人跨站。

## 期望

1. 对于同一个主域名下的 jsonp 跨站请求，支持 double commit cookie 形式的跨站校验。
2. 对于跨主域名的 jsonp 请求，支持 referer 校验。
3. 过滤 jsonp xss。

## 实现方案

通过 router 中引入 `app.enableJsonp()` 中间件来开启一个路由的 jsonp 支持，暂时不考虑支持全局引入。controller 中只需要正常编写业务逻辑。

```js
app.get('/api/cross/user/create', app.enableJsonp(), 'user.create');
```

`enableJsonp` 中实现逻辑：
  
```js
function* enableJsonp(next) {
  // 跨站校验
  if (options.assertCsrf) this.assertCsrf();
  // referer 校验
  if (options.referer) checkReferer(this, options.referer);
  yield next;
  // xss 过滤
  this.body = jsonpBody(this.body, options);
}
```

## Check Lists

- [ ] [egg-jsonp](https://github.com/eggjs/egg-jsonp) 实现
- [ ] 去除 egg 中的 `ctx.jsonp`
- [ ] 修正文档

**Comment by atian25** [comment]
`this.body = jsonpBody(this.body, options);` 这个支持一个 router 同时支持 json 和 jsonp 么?

**Comment by dead-horse** [comment]
支持的，这句要和现在的 `this.jsonp = ` 实现逻辑一致

**Comment by dead-horse** [comment]
考虑到 jsonp 会变复杂，抽成一个 egg-jsonp 插件来实现。 @popomore

**Comment by popomore** [comment]
提供 api 给 ctx.jsonp 做兼容，内部实现会简单。主要是 enableJsonp 中 res 处理的

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-jsonp/commit/ffcd53d50fb4309369c560ff29d71cab6fa76723

@fengmk2 @popomore @atian25  没有提 PR，review 一下吧，没问题再发版本

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-jsonp/pull/1

**Comment by popomore** [comment]
egg 里的还没改
