### ISSUE TITLE
Router 配置优化或省去？

### ISSUE THREAD

**Issue by xilutian** [eggjs/egg#2883]
您好 ：
 egg 现在有Router ，也有Controller ,但是java ，.net 等语言的mvc 框架 对于开发者来说都不需要单独配置router，根据请求的参数，自动去匹配Controller中的action。
  那是不是egg 也可以省去router配置，对于router 那配置的方法 Post ，Get 这些 是不是可以通过 在action上加注释来实现(默认是Get)，当然也包括 router中配置的中间件 。
  现在Router是基础Koa-Router  来实现路由的，那是不是可以基于controller 自动生成 对应的router呢，就类似现在restfull呢 
 我是刚开始接触egg的新手，如有理解不对的，请谅解

**Comment by atian25** [comment]
因为映射规则并不是通用的，你有需要可以自己写个插件来做这个事，或者写装饰器

**Comment by xilutian** [comment]
我做项目比较少，您方便具体说 映射规则不通用是在哪吗？举例说一下 也可以 ，麻烦了

**Comment by atian25** [comment]
并不是所有的项目都 restful 的。

restful 的话也有提供 https://eggjs.app/zh-cn/tutorials/restful.html

**Comment by xilutian** [comment]
restful 只是正常路由的特例或者说一种特殊的形式，如果把controller中的方法 都弄成 映射成路由的话，那不仅仅是restful 可以使用 ，那其他的路由也是访问的吧， 这个只是我比较懒的想法，不想去配置的单独router的想法 ，java .net  也都没有配置 ，那项目也是正常支持吧

**Comment by atian25** [comment]
所以说这不是通用需求啊，所以不会集成到 egg 内置里面。
写个插件就可以解决了，不会太难。

**Comment by xilutian** [comment]
嗯嗯，麻烦了

**Comment by hyj1991** [comment]
其实我一直不明白自动路由映射好在哪...思考怎么映射的功夫一行 router 都写完了。而且这东西对后面代码维护很不友好，一段时候后再看还要根据 url 思考下映射到哪个文件了

**Comment by yuedun** [comment]
@hyj1991 自动路由映射也不是没好处，比如大型项目会有很多接口，每次新增接口都需要修改路由映射，每个人写路由风格也可能不一样，多人修改一个文件容易冲突。项目小的话直接写比较方便，项目大了这是项重复劳动，可以考虑使用自动映射路由一劳永逸。装饰器其实能很好的解决这一问题，直接通过文件名，类名和方法名映射成路由。

**Comment by atian25** [comment]
@yuedun @xilutian 你们举几个自动映射路由的框架来看看，其他语言的都行。

**Comment by popomore** [comment]
rails 咯

**Comment by atian25** [comment]
只是自动映射 restful 的好像，用 app.resource 是不是也行？

**Comment by yuedun** [comment]
```
@route({})
static catalog(req: Request, res: Response): Promise.Thenable<any> {
    
};
```

详细可以看源码`@route({})` 
https://github.com/yuedun/yuedun_ts/blob/master/routes/article.ts
https://github.com/yuedun/yuedun_ts/blob/master/utils/route.ts
https://github.com/yuedun/yuedun_ts/blob/master/utils/route-register.ts
只能提供个方案，还需由大佬来实现

**Comment by atian25** [comment]
可以搜下社区有没有实现。

**Comment by yuedun** [comment]
@hyj1991 不自动路由也没什么关系，写路由本身不会费多少事，主要的目的是规范路由，可以直接从路由就可以看出方法在哪个目录，哪个文件里面。要知道，多人维护的项目中也会写出相同路由的问题。
