### ISSUE TITLE
docker host 模式  报AppWorkerDiedError错误

### ISSUE THREAD

**Issue by wufangjian** [eggjs/egg#2886]

**Comment by wufangjian** [comment]
![image](https://user-images.githubusercontent.com/6982055/43882198-68877a9c-9be1-11e8-84c9-d98c40492d7d.png)
![image](https://user-images.githubusercontent.com/6982055/43882230-8dab8886-9be1-11e8-9c6e-ac3bcdad8112.png)

**Comment by atian25** [comment]
docker 里面 Node 的 os.cpu 的 API 检测有问题，自己指定下启动参数 worker 数

**Comment by popomore** [comment]
好有钱

**Comment by wufangjian** [comment]
@atian25 但是并没有用，感觉是端口没启起来。

我的启动配置 端口 `7001`
```
./node_modules/egg-scripts/bin/egg-scripts.js start --port=7001 --workers=8
```

![image](https://user-images.githubusercontent.com/6982055/43887671-1cccb232-9bf2-11e8-8076-82e8950a1205.png)

```
xxxxxxx  2018-08-09 +16:33:49 test-demo port 9388 connection refused!
```

**Comment by atian25** [comment]
`server got error: bind EADDRINUSE null:7001`

端口占用啊

**Comment by wufangjian** [comment]
感谢~

`部署之前确认过端口未被占用`

咨询了公司运维，是和这边运维有关，Auto Host 模式下，应用动态分配端口

**Comment by atian25** [comment]
一般是通过环境变量传递给 EGG 启动
