### ISSUE TITLE
egg是否可以维护动态的全局变量

### ISSUE THREAD

**Issue by gavinwyf** [eggjs/egg#2887]
生产环境，动态改变内置对象app下变量赋值，在其他controller下获取一直undefined。而在egg-bin dev调试环境，内置对象app下变量赋值是可以get到的。这是为什么。 有没有可以在生产环境可以维护的全局变量。我需要动态写入内存中。内存中变量内容随业务变化，可以动态回收掉。

node 8.9.4
npm 6.1.0
egg 2.2.1

**Comment by gavinwyf** [comment]
找到答案了，原来生成环境默认开启了多个进程，不同controller之间不能简单的共享同一块内存。看来得研究一下进程间通信。agent玩法了。https://eggjs.org/zh-cn/core/cluster-and-ipc.html

**Comment by atian25** [comment]
redis

**Comment by popomore** [comment]
那服务重启不就没了。

**Comment by atian25** [comment]
内存的话你就只能单机了，不能水平扩展

**Comment by webVictor** [comment]
> 找到答案了，原来生产环境默认开启了多个进程，不同controller之间不能简单的共享同一块内存。看来得研究一下进程间通信。agent玩法了。https://eggjs.org/zh-cn/core/cluster-and-ipc.html
请问解决了么

**Comment by coldrainc** [comment]
hello，请问你解决这个问题了吗
