### ISSUE TITLE
 --https.key=server.key --https.cert=server.crt 导致  cluster listen 配置失效 ？

### ISSUE THREAD

**Issue by wufangjian** [eggjs/egg#2889]
刚接触egg 框架，源码里面未看到 https 的配置相关源码，请教一下~~   

是发生了覆盖了~？ 源码里面没看到相关代码....

一、端口配置 `config.local.js`
```
cluster: {
    listen: {
      port:  7002
    }
  }
```

二、运行`npm run dev` 

说明：本地配置 https 配置正确

2.1 失效的`package.json` 配置，启动端口`非7002`
```
env: egg-bin dev --daemon --https.key=server.key --https.cert=server.crt
```

2.2 有效的`package.json` 配置， 启动端口为 `7002` 
```
env: egg-bin dev --daemon
```

**Comment by popomore** [comment]
dev 有自己的默认值，通过参数指定 port

**Comment by atian25** [comment]
https 最好用 nginx 做

**Comment by wufangjian** [comment]
@popomore   两种方式都是  dev 模式下。  只是其中一个为了方便本地调试 做了个 https相关配置.
