### ISSUE TITLE
插件市场设想

### ISSUE THREAD

**Issue by ngot** [eggjs/egg#289]
目前寻找egg插件是一个比较困难的事情，我设想可以搞个市场方便搜索展示egg的插件。

几点考量：

- 插件分级([参考](https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/)) 
    - 官方
    - 社区
- 插件建立一个准入机制
    - package.json中配置了 eggPlugin 即可进入插件库
    - 同时也可以屏蔽掉一些已经废弃的插件，比如配置 
    ```
       eggPlugin{
           deprecate: true
       }
    ```
- 包从npm同步，比如以 egg-* 来匹配
- 内网也可以类似机制实现一套

**Comment by atian25** [comment]
http://yeoman.io/generators/

http://fis.baidu.com/fis3/plugins.html

的做法是直接 npm search key

**Comment by atian25** [comment]
- key 为 `eggPlugin` , `egg-plugin`, `egg-framework` 的都可以检索
- deprecate 这个是不是直接通过 npm deprecate 来区分就好了

**Comment by popomore** [comment]
gulp 也是用的 npm http://gulpjs.com/plugins/

**Comment by popomore** [comment]
如果要做可以取代这个页面 https://eggjs.org/badgeboard/

**Comment by dead-horse** [comment]
先关掉了，没有进一步的跟进需求
