### ISSUE TITLE
[Feature] Auto multiple-lang supported

### ISSUE THREAD

**Issue by Maledong** [eggjs/egg#2891]
Ref：https://github.com/eggjs/egg/pull/2885

Hi,
I wanna ask all of you guys two questions：

1）From the ref you got to know that I wanna add auto redirection according to browser's default lang setting. So Is it good to add in `egg-docTools`? Is it only a package wrapper tool? I prepare to add this support at `base.js`'s `hexoServer()` method? Or any better suggestions?

2）Are you uing Nginx? If you are using that, maybe you can use something like https://www.nginx.com/resources/wiki/modules/accept_language/ instead of coding directly?

/cc：@popomore

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/1890

**Comment by dead-horse** [comment]
trace this issue in #1890
