### ISSUE TITLE
自定义统一异常处理，不能够自定义，或者说达不到自定义的效果

### ISSUE THREAD

**Issue by Trinyoung** [eggjs/egg#2894]
项目是用typescript 编写的，`./config.default.ts`中配置自定义统一异常处理时，有如下问题：
```
config.onerror = {
        all(err, ctx){
            ctx.body = 'error';
            ctx.status = 200
        }
    }
```
如上代码中，`ctx.body` 的值被强类型只能设定为`string` 或者`buffer`，而我想用`json`！`ctx.body` 的值不能设定为`json`，这是其一；
其二是我想 `ctx.body `返回的是方法中参数err的值，不是普通的字符串`error`！
当发现`all `方法不行时，看到了还有一个`json`方法；
如下：
```
config.onerror = {
     json(err, ctx){
            ctx.body = {err：‘error’};
            ctx.status = 200
        }
}
```
`json`方法没有效果，返回的依然是默认的异常处理结果，除了`all()`方法外，其他方法不起作用，这是其三；

万望各位尊神给个回复！

**Comment by BaffinLee** [comment]
1. 试试 `JSON.stringify`
2. `ctx.body = err.message`, `ctx.body = JSON.strinify({ stack: err.stack, message: err.message })`
3. 有 all 方法的时候其它方法不会调用，json 方法只有在有 `Accept: application/json`  请求头是才有用

**Comment by Trinyoung** [comment]
1.JSON.stringify 返回的结果依然是字符串结果；客户端想要接收的格式是json；；
2.没有设置all方法的时候，json方法依然不会被调用；egg 框架下如何设置Accept？

**Comment by BaffinLee** [comment]
1. http 返回的数据不是字符串就是二进制啊，你要json就 `JSON.parse` 一下，有些 ajax 封装库会在返回 `Content-Type: application/json` 的时候自动尝试 `JSON.parse`。能用 `ctx.body = {}` 只是框架帮你调用了 `JSON.stringify` 而已。不过这个 typescript 限制 body 只能是 string 和 buffer 还是有点坑，可以尝试提个 PR
2. 客户端请求的时候设置 header

**Comment by yyh1102** [comment]
为何关了issuer？客户端请求的时候已明确指出header还是遇到相同的问题。另外用application/json的contentType请求服务，全局抛出的错误只有用onerror.html能收到，懵逼了，隔了一年这问题还没解决么？

**Comment by AaronW-BE** [comment]
> 为何关了issue？客户端请求的时候已明确指出header还是遇到相同的问题。用application/json的contentType请求服务，全局抛出的错误只有用onerror.html能收到，懵逼了

Set header to Accept: application/json

**Comment by atian25** [comment]
@yyh1102  `content-type` is response header, not request header, see `Accept` headers spec at MDN for more detail.
