### ISSUE TITLE
ps -eo "pid,command" | grep "--type=egg-server" 有误

### ISSUE THREAD

**Issue by yuu2lee4** [eggjs/egg#2896]
1、-o 参数里没有command 只有comm
2、gre的时候也提示： grep: unrecognized option: type=egg-server

**Comment by BaffinLee** [comment]
1. 有的，是 `args` 的别名
2. `grep "\-\-title=egg-server"` 或者 `grep -- "--title=egg-server"`，推荐用 `egg-scripts`

**Comment by yuu2lee4** [comment]
@BaffinLee  npm stop就是用的egg-scripts吧？ 然后执行的脚本里就是不对的

**Comment by BaffinLee** [comment]
`egg-scripts stop`  只用到 `ps`，没有用到 `grep` 的，过滤是在代码里实现的

**Comment by yuu2lee4** [comment]
但是也会报错 就是 -o那个

**Comment by BaffinLee** [comment]
你的系统版本是什么，ps 版本是什么？可能是软件版本问题

**Comment by popomore** [comment]
用 docker 就不要 stop 了吧

**Comment by BaffinLee** [comment]
@yuu2lee4 Alpine Linux 里的 ps 命令确实没 command 参数，参考一下这个 [#173](https://github.com/gliderlabs/docker-alpine/issues/173#issuecomment-218620191)

**Comment by atian25** [comment]
@BaffinLee 可以补下文档说明下，好像不少新人都用 Alpine

**Comment by BaffinLee** [comment]
@atian25 考虑把 `command` 换成 `args` ? 兼容性可能好点，不过可读性差一点。

**Comment by atian25** [comment]
可以吧，有注释还好

**Comment by atian25** [comment]
land 2.9.1
