### ISSUE TITLE
controller 部分文档优化

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#290]
controller 支持新的写法了，也推荐用新的写法，需要优化文档。

1. 修改 controller 的写法部分。
2. 增加自定义 controller 基类的方式。

**Comment by atian25** [comment]
配套的 quickstart,  boilerplate 也得跟着改

**Comment by dead-horse** [comment]
#314

**Comment by popomore** [comment]
写完了？

**Comment by dead-horse** [comment]
quickstart 是不是也改成 class 形式

**Comment by popomore** [comment]
quickstart @atian25 看看？
