### ISSUE TITLE
egg-sequelize log问题

### ISSUE THREAD

**Issue by Lpmvb** [eggjs/egg#2900]
* **Node Version**: v8.11.3
* **Egg Version**: v2.10.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: v4.0.2
* **Platform**: mac
* **Mini Showcase Repository**:

在新版本的egg-sequelize中，日志打印时是这样的
```
[egg-sequelize][38ms[39m] Executed (default): SELECT 1+1 AS result
```
源码中日志打印相关部分为
```js
    logging(...args) {
      // if benchmark enabled, log used
      const used = typeof args[1] === 'number' ? `[${args[1]}ms]` : '';
      app.logger.info('[egg-sequelize]%s %s', used, args[0]);
    },
```
按照代码来看，打印出来的结果不是应该是：
```
[egg-sequelize][38ms] Executed (default): SELECT 1+1 AS result
```
另外试着直接打印
```
app.logger.info('[100ms]');
// 结果是[100ms[39m]
```

**Comment by Lpmvb** [comment]
嗯  文件中是正常的 不过 bash 和 zsh 下都会有这样的问题

**Comment by dead-horse** [comment]
这应该是你系统终端的问题..可以去 google 一下看看有没有解决方案
