### ISSUE TITLE
egg-schedule  的日志全部输出到到  egg-schedule.log

### ISSUE THREAD

**Issue by paranoidjk** [eggjs/egg#2901]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

## 问题

- 文档写的定时任务日志在 egg-schedule.log https://github.com/eggjs/egg-schedule#logging
- 事实上大部分都输出在 egg-web.log https://github.com/eggjs/egg-schedule/search?q=coreLogger&unscoped_q=coreLogger

##  提议
将 schedule 的内置日志全部输出到自己的 customLogger 单独文件里面，更方便排查定时任务问题 https://github.com/eggjs/egg-schedule/blob/master/config/config.default.js#L9

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by willerce** [comment]
@atian25 这里应该是期望将 schedule 目录中（继承自 Subscription ）的类中的 logger.info() 保存到  egg-schedule.log 中。
目前 egg-schedule.log 中大多数日志只能看任务的开始结束，价值不大。

**Comment by atian25** [comment]
ctx.getLogger('scheduleLogger')

**Comment by popomore** [comment]
业务日志统一到一起没毛病，如有需要自定义日志
