### ISSUE TITLE
ResponseError, HPE_INVALID_CONSTANT

### ISSUE THREAD

**Issue by tomczhang** [eggjs/egg#2904]
问题：业务中有一个请求，返回的数据量是100K，把请求和返回部署在同一台服务器上用curl访问能正常返回，部署在不同服务器间返回就会报错，报错如下：

![123](https://user-images.githubusercontent.com/7392781/44151631-b9734a28-a0d5-11e8-902f-98c70a2fac19.png)

另外还有几个最大36K的请求，可以正常返回成功。请求和返回部署在同一台服务器上的请求也能成功，返回如下：

![image](https://user-images.githubusercontent.com/7392781/44151873-6c4266ac-a0d6-11e8-840a-02c972759559.png)

尝试了设置httpAgent和gzip均没有效果。看了文档keepAlive默认是为true的，而且超时时间是30s。

有几个疑问：
1. 看第一张图是存在KeepAlive的，建立了三个socket，其中有一个超时了。但是socket的超时时间不是30s吗？但是实际上是1s内就报错了。
2. 看第二张图，成功的那个请求是不是把请求中几个socket求和统计出的结果？
3. 这个问题有什么处理思路或者方案吗？在不减少返回数据传输量的情况下

**Comment by tomczhang** [comment]
100K的buffer数据，Content-type和datatype均没做特殊处理

**Comment by popomore** [comment]
上代码

**Comment by XadillaX** [comment]
你的数据有没有什么特殊的字符，两台服务器之间有没有 Nginx？

**Comment by tomczhang** [comment]
其实可以从两个点看这个问题，抛转引玉
1是这个报错，HPE_INVALID_CONSTANT。我查了一下文档，没查到这个错误，看这个错误的意思是XX的非法常量
2是为什么socket会在极短时间的时间内超时

**Comment by tomczhang** [comment]
问题的第四天，使用了原生的HTTP库，发现返回较长的请求chunk相加得到的数据和contentLength不相等，但是较短的相等。已经开始怀疑是C++后台的问题

**Comment by fengmk2** [comment]
HPE_INVALID_CONSTANT，请求异常了。

**Comment by tomczhang** [comment]
问题昨天下午查出来了，后台服务器代码错误。长链接时，他们再发送一个大的数据包时，会先尝试用一个socket发送，若是不能一次放入，就把剩余的部分放到一个队列中，然后每当socket有空余的时候，就队列中拿出一部分来发送，但是，他们忘了把队列中后来被发送的这部分数据减掉了，导致队列中的永远都会有数据，一直尝试着发送给我。而Node端当收到contentLength长度的数据时，再收到更多的数据就会主动断开连接，并报错callback twice的错。以上

**Comment by XadillaX** [comment]
@fengmk2 是 Response 的消息有問題。我之前在 Node.js 那邊的 Request 解析的時候拿到了 rawPacket，Response 忘了改，暫時看不到 rawPacket。
