### ISSUE TITLE
使用egg-multipart时，设置multipart/form-data方式进行发送，如果没有文件加入，会报Can\'t found upload file错误

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#2905]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by tong3jie** [comment]
ctx.getFileStream 加上｛requireFile: false｝的option，报错消失。

**Comment by fengmk2** [comment]
@tong3jie 对，这是新建的功能，允许空文件。
