### ISSUE TITLE
请问 runInBackground 中如何编写单元测试？

### ISSUE THREAD

**Issue by seekcx** [eggjs/egg#2906]
* **Node Version**: 8.11.3
* **Egg Version**: 2.9.1
* **Platform**: osx

在 app.runInBackground 中执行异步动作，如何编写单元测试呢。

比如同步任务 A 执行完毕之后，会在 runInBackground 执行异步任务 B，一般来说，为了测试 A，会对 B 进行 mock。但是由于 B 在 runInBackground 中执行，是异步的，当 B 真正执行的时候，mock 已经失效了。这种情况会导致 B 方法被真正的执行，造成数据污染。

**Comment by Maledong** [comment]
你可以使用Promise+async（await）方式处理：
把RunInBackground放入一个Promise里边，处理完毕后resolve一个结果，外部await等待结果判断。

**Comment by dead-horse** [comment]
`await app. backgroundTasksFinished()`

https://github.com/eggjs/egg-mock/blob/master/app/extend/application.js#L429

**Comment by nightmareT** [comment]
顺便问一句，egg这边能集成代码测试报告的工具吗，想在jenkins上面体现测试报告，目前没找到相关的工具

**Comment by atian25** [comment]
`egg-bin cov`
