### ISSUE TITLE
egg-passport的登出方法ctx.logout为什么没有自动清除ctx.session

### ISSUE THREAD

**Issue by IEfucker** [eggjs/egg#2907]
cnode上发的帖子没有回复，来这里请教下吧
https://cnodejs.org/topic/5b7399bc792f59ae501bf9a1

看egg-cnode源码发现logut同时要清一下ctx.session
很疑惑debug了一下发现确实如标题

请问这样是刻意设计的吗

![](https://dn-cnode.qbox.me/FtjLdsImxrHYwcgFFNkvwD0Hc6C8)

**Comment by atian25** [comment]
ping @thonatos

**Comment by thonatos** [comment]
```js
SessionManager.prototype.logOut = function(req, cb) {
  if (req._passport && req._passport.session) {
    delete req._passport.session.user;
  }
  cb && cb();
}
```

看代码在这里，晚点我验证一下。

## LInks

- [request.js#L64](https://github.com/jaredhanson/passport/blob/2327a36e7c005ccc7134ad157b2f258b57aa0912/lib/http/request.js#L64)
- [sessionmanager.js#L30)](https://github.com/jaredhanson/passport/blob/2327a36e7c005ccc7134ad157b2f258b57aa0912/lib/sessionmanager.js#L30)

**Comment by IEfucker** [comment]
@thonatos 给大神添乱了，这么看处理是对的，再次debug查看ctx.session下的user属性确实清掉了

是我理解错误，以为session整个属性要清掉。

可以关闭这issue了
