### ISSUE TITLE
egg-schedule的env配置不生效

### ISSUE THREAD

**Issue by lixiaolihua** [eggjs/egg#2910]
定时任务中的`env`配置不生效，我只想是prod环境中执行这个定时任务，但配置后发现在本地环境启动后也会执行。
后来发现不论把`env`设置成什么值，所有环境都会执行；

```javascript
class MockHeartbeat extends Subscription {
  static get schedule() {
    return {
      type: 'worker',
      interval: '20s',
      env: [ 'prod' ],
    };
  }

  async subscribe() {
    await this.ctx.curl(heartbeatUrl, {
        dataType: 'json',
      });
  }
}

module.exports = MockHeartbeat;
```

**Comment by BaffinLee** [comment]
`disable: this.ctx.app.config.env !== 'prod'`

[看文档](https://eggjs.app/zh-cn/basics/schedule.html#%E5%85%B6%E4%BB%96%E5%8F%82%E6%95%B0)

**Comment by lixiaolihua** [comment]
@BaffinLee 我知道可以这么实现，主要想确认scheduler配置里面`evn`这个配置能不能用;
我是看`egg-schedule`文档里面有这么用的 [看文档](https://github.com/eggjs/egg-schedule#dynamic-schedule)

![GitHub](https://raw.githubusercontent.com/lixiaolihua/images/master/images/Snip20180820_1.png)

**Comment by dead-horse** [comment]
看一下 egg-schedule 的版本是不是最新的，或者自己尝试根据这个 commit debug 一下试试看为什么咩有生效 https://github.com/eggjs/egg-schedule/commit/417a7643807e56a432703e64f76923b60e1053ba

**Comment by lixiaolihua** [comment]
@dead-horse 
npm上的版本最新就是3.3.0，安装不了3.4.0

![github](https://raw.githubusercontent.com/lixiaolihua/images/master/images/Snip20180820_2.png)

**Comment by dead-horse** [comment]
@lixiaolihua 已发布，重新安装一下试试

**Comment by atian25** [comment]
忘记发布了？尴尬
