### ISSUE TITLE
eggjs 如何获取当前程序跑的域名？

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2912]
* **Node Version**:  v8.11.1
* **Egg Version**: 2.8.1
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: ubuntu 16.04
* **Mini Showcase Repository**:

目前无论在本地开发还是线上部署，通过 `this.ctx.helper.urlFor('test')` 获取得到的 url 均为 `http://127.0.0.1:7001/test/` 无法获取到真是的域名地址。应返回 `https://demo.example.com/test/`，`https://demo.example.com` 为 egg 程序跑的域名。

附上 nginx 配置：
```
server
{
    server_name demo.example.com;
    location / {
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:7001;
    }
    access_log /var/log/nginx/blog_access.log;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/demo.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/demo.example.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server
{
    if ($host = demo.example.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name demo.example.com;
    return 404; # managed by Certbot


}
```

不知道有没有好的方法可以直接获取到真实的 url 地址？

**Comment by JZLeung** [comment]
@popomore 
请问一下，如何获取？

**Comment by atian25** [comment]
就是读取 header 啊

**Comment by okoala** [comment]
https://eggjs.org/api/Request.html#host

**Comment by wayou** [comment]
虽然有点晚，

_app/extend/request.js_

```js
const DOMAIN = Symbol('Request#domain');
module.exports = {
/**
     * 返回一级域名 foo.bar.baz.com => baz.com
     */
    get domain() {
        if (!this[DOMAIN]) {
            const host = this.ctx.host.indexOf(':') ? this.ctx.host.split(':')[0] : this.ctx.host;
            this[DOMAIN] =
                host.split('.').length > 1
                    ? host
                          .split('.')
                          .slice(-2)
                          .join('.')
                    : host;
        }
        return this[DOMAIN];
    },
};
```

**Comment by atian25** [comment]
koa 本身就有个 hostname 的 getter 了

**Comment by wayou** [comment]
嗯，hostname 包含的是整个域名，这里分享**一级域名**的获取，方便有需要的同学。

**Comment by FollowTrend** [comment]
朋友，解决了吗，我也遇到这个问题，用ctx.header.host获取一直是127.0.0.1，如何获取到NGINX代理的域名或者前端路由

**Comment by YBFJ** [comment]
> 朋友，解决了吗，我也遇到这个问题，用ctx.header.host获取一直是127.0.0.1，如何获取到NGINX代理的域名或者前端路由

@FollowTrend 请问您找到解决办法了吗？我也是，一直获取的是127.0.0.1，用ctx.header.host，没拿到NGINX代理的域名

**Comment by YBFJ** [comment]
> > 朋友，解决了吗，我也遇到这个问题，用ctx.header.host获取一直是127.0.0.1，如何获取到NGINX代理的域名或者前端路由
> 
> @FollowTrend 请问您找到解决办法了吗？我也是，一直获取的是127.0.0.1，用ctx.header.host，没拿到NGINX代理的域名
 我解决了我的问题，通过以上回答以及 @atian25 在别处的回答
![image](https://user-images.githubusercontent.com/30866639/108473186-ab6cec00-72c8-11eb-87b0-97432740f957.png)

nginx 那边要配 X-Forwarded-For，egg 这边开启 config.proxy，config直接在config.default.js中配置 exports.proxy = true即可，nginx的 [X-Forwarded-For参考另外一位大佬的回答[HTTP 请求头中的 X-Forwarded-For](https://imququ.com/post/x-forwarded-for-header-in-http.html)
