### ISSUE TITLE
请问如何在helper.js中调用app,ctx上挂载的方法和属性?

### ISSUE THREAD

**Issue by Erchoc** [eggjs/egg#2918]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
`helper` is mount at `ctx`,  so you could try `this.xx` as ctx scope.

but it's not recommended, `helper` is designed to be template render helper, if you want to share some logic, just use `app/service/utils.js`
