### ISSUE TITLE
egg-sequelize bulkInsert is not a function

### ISSUE THREAD

**Issue by pandasjw** [eggjs/egg#2919]
```js
 this.model.Article.bulkInsert(arr);
```
```js
 error: this.ctx.model.Article.bulkInsert is not a function
```

* **Node Version**:v10.7.0
* **Egg Version**:2.2.1
* **Plugin Name**:egg-sequelize
* **Plugin Version**:3.1.5
* **Platform**: macOS 10.13
* **Mini Showcase Repository**:

**Comment by dead-horse** [comment]
http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate

**Comment by pandasjw** [comment]
OK. Thx.
