### ISSUE TITLE
被废弃的api如何更新替换

### ISSUE THREAD

**Issue by CWTgithub** [eggjs/egg#2922]
timers.enroll() is deprecated. Please use setTimeout instead.
timers.unenroll() is deprecated. Please use clearTimeout instead.
这两个警告说要替换这两个api，但是我是刚用脚手架init的项目，全局没搜到这个api，请问如何替换。。。

**Comment by killagu** [comment]
`Timers.enroll` and `Timers.unenroll` is node API. It's not need to worry about it.

**Comment by ximendatie** [comment]
> timers.enroll() is deprecated. Please use setTimeout instead.
> timers.unenroll() is deprecated. Please use clearTimeout instead.
> 这两个警告说要替换这两个api，但是我是刚用脚手架init的项目，全局没搜到这个api，请问如何替换。。。

npm install mysql 
升级到2.16.0即可解决
