### ISSUE TITLE
egg-validate中判断前端参数问题

### ISSUE THREAD

**Issue by Erchoc** [eggjs/egg#2925]
构造函数规则如下:
constructor(ctx) {
    super(ctx);

    this.validateTeacherComment = {
      userid: { type: 'int', required: true },
      childid: { type: 'int', required: true },
      pageIndex: { type: 'int', required: true },
      pageSize: { type: 'int', required: true },
    };
  }

这样的话我使用了postman和apizza测试均发现传递整数无法通过验证，如图：

![image](https://user-images.githubusercontent.com/19908809/44436797-be17e480-a5e9-11e8-8016-5a4eaf86528c.png)

**Comment by popomore** [comment]
querystring 是字符串
