### ISSUE TITLE
新的权限验证模块

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#293]
https://github.com/CanCanCommunity/cancancan

**Comment by jtyjty99999** [comment]
https://github.com/vadimdemedes/cancan

**Comment by coolicer** [comment]
什么时候能加入权限模块

**Comment by atian25** [comment]
@coolicer 你的需求场景是?  
目前的 userrole 不能满足?

cc @jtyjty99999

**Comment by coolicer** [comment]
@atian25 你是说内置有还是说写死的那种？

**Comment by atian25** [comment]
内置有 egg-userrole 插件

**Comment by coolicer** [comment]
@atian25 好的，我刚看这个egg，不知道还有这个。

**Comment by atian25** [comment]
文档在 https://github.com/eggjs/egg-userrole

后面可能会基于 cancancan 做另一套吧，暂时没计划

**Comment by phper-chen** [comment]
请问有那种可以配置的权限管理吗？ 比如基于路由资源的权限管理   路由参数映射成对应的权限功能  比如 localhost:8000/user/find/:id    /user/delete/   /user/update/   /user/create/    这样的基于资源的权限管理   我们的项目目前是这么做的  但是觉得不够自动化

**Comment by atian25** [comment]
目前没有，你可以看看上面提的模块，有需要自己封装下，回馈给社区

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-cancan
