### ISSUE TITLE
[Discussion] How to do a compatible interface?

### ISSUE THREAD

**Issue by Maledong** [eggjs/egg#2931]
The typical problem [here](https://github.com/eggjs/egg-core/pull/178)  means there's a function called `toAsyncFunction` , and in fact since the function is exposed to the public, so we cannot decide parameter types and we have to do a validation check, but it didn't do that before. And in order to make a compatible function according to @popomore's idea, I used an optional parameter and I wanna let users set it to `true` for validation.

Now my questions are:
1) What's your way of writing a compatible interface? Are you also using optional parameters? Or any better ways?
2) Even if we've met a BUG (or something bad) but in order to be compatible with what it was before, we should ignore the BUG or fix it in the next version?

Nothing but I just wanna know your rules of programming and follow them, thanks anyway!

/cc：@popomore, @fengmk2, @dead-horse, @atian25

**Comment by Maledong** [comment]
>so the question is whether strictMode is necessary? does plugin developer really need it at most of the situation? if not, maybe developer could detect the args itself due to the Occam's Razor rule.

OK. I understand :) I'll remove the `strictMode` and keep the original.

**Comment by Maledong** [comment]
@atian25 ：

IMO：If possible, maybe we can arrange some refactoring rules and write them into another file to force submitters to manage codes easily :D

**Comment by atian25** [comment]
for myself, take a neutral stance on this PR. so decision to @dead-horse ~

> IMO：If possible, maybe we can arrange some refactoring rules and write them into another file to force submitters to manage codes easily :D

did you mean codemod ?

**Comment by Maledong** [comment]
@atian25：This is out of box, it doesn't have anything to do with this PR……What I want is that if we have a series of rules and we can follow the rules to make codes more stable, stylish and easy to manage. Because as you know, that different people will have different ideas on PR.

**Comment by atian25** [comment]
got,  could improve the https://eggjs.app/en/contributing.html , add some design patten rule.

**Comment by Maledong** [comment]
I'll first think it over and list here for your review if free.
