### ISSUE TITLE
Sequelize执行多个sql语句报错

### ISSUE THREAD

**Issue by cnchenhao** [eggjs/egg#2932]
`let ctx = this.ctx;
 let sql = "SELECT * FROM `Project`;  SELECT * FROM `User`; ";
 let ret = ctx.model.query(sql, { raw: true, model: ctx.model.UserModel });`
使用Sequelize执行sql语句，如果包含2个或以上的语句会报错，SQL语句本身是没有问题的，请指点下，谢谢。报错信息：
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

**Comment by fengmk2** [comment]
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near

查看完整的 SQL 报错信息。

**Comment by cnchenhao** [comment]
非常简单的两个查询语句，不太可能是语法错误，很纳闷呐

**Comment by popomore** [comment]
去 Sequelize 咨询
