### ISSUE TITLE
无法渲染路由视图

### ISSUE THREAD

**Issue by zhangshichuan** [eggjs/egg#2934]
> Node Version:  10.0.0
> Egg Version:  2.2.1
> Plugin Name:  egg-view-nunjucks
> Plugin Version:  2.2.0
> Platform: win10 x64
> Repository:  https://github.com/zhangshichuan/me

我按照官方文档快速入门, 通过egg-init --simple 生成了一个项目.

其中的配置如下:

  **视图目录**
![image](https://user-images.githubusercontent.com/8280832/44629604-5b756e80-a984-11e8-8ffa-32561a7e52ad.png)
  **插件配置**:
![image](https://user-images.githubusercontent.com/8280832/44629616-8233a500-a984-11e8-9d67-9e50707fe28c.png)
  **默认的配置文件**
![image](https://user-images.githubusercontent.com/8280832/44629621-a0010a00-a984-11e8-8c20-ecd30dc0ff6b.png)
  **路由**
![image](https://user-images.githubusercontent.com/8280832/44629626-b4450700-a984-11e8-9793-189ffc10fd95.png)
  **控制器**
![image](https://user-images.githubusercontent.com/8280832/44629765-371a9180-a986-11e8-9430-0460b9ddb42f.png)

**访问结果**
![image](https://user-images.githubusercontent.com/8280832/44629692-92984f80-a985-11e8-98d3-5307e9fd9c39.png)

  **日志输出**
![image](https://user-images.githubusercontent.com/8280832/44629700-a2179880-a985-11e8-8da3-1fc4da7fae08.png)

- 我是小白, 我在论坛问过, 但是没有得到解决. 我也担心是一个很低级的错误. 也尝试通过搜索引擎, 但是没有发现类似的问题. 所以才在这里提这个issues. 惊扰各位同学了!

**Comment by popomore** [comment]
缺少后缀

**Comment by popomore** [comment]
而且你写了两个 view 配置

**Comment by zhangshichuan** [comment]
配置了默认后缀为.html

**Comment by zhangshichuan** [comment]
明白了, 谢谢
