### ISSUE TITLE
同一个api线上和线下的返回值不同

### ISSUE THREAD

**Issue by williamnie** [eggjs/egg#2936]
* **Node Version**: v10.9.0
* **Egg Version**: v2.9.1
* **遇到的问题**:  同一个api线上和线下的返回值不同，逻辑为查询mongodb后返回数据，返回之前经过一个方法，将mongodb的_id 转换为id
* **转换方法为**:
`
exports.transform = (data, config) => {
  if (!data) {
    return null;
  }
  const trans = (obj) => {
    if (config && config.rename) {
      config.rename.forEach((item) => {
        obj[item.new] = obj[item.old];
        delete obj[item.old];
      });
    }
    if (config && config.remove) {
      config.remove.forEach((item) => {
        delete obj[item];
      });
    }
    if (config && config.add) {
      config.add.forEach((item) => {
        obj[item.key] = item.value;
      });
    }
  };

  let obj = null;
  if (Array.isArray(data)) {
    obj = data.map((item) => {
      return item.toJSON();
    });
    obj.forEach((item) => {
      trans(item);
    });

  } else {
    try {
      obj = data.toJSON();
    } catch (error) {
      obj = data;
    }
    trans(obj);
  }
  return obj;
};

`
* **调用方式和接收参数**:
`
// 调用方式
const data = await ctx.model.Source.find({ name: { $regex: query }, key }, 'checked name key');
return ctx.helper.transform(data, config.transformConfig);
// 接收参数
data 为mongodb查询出的数据，config配置如下 
 config.transformConfig = {
    rename: [{ new: 'id', old: '_id' }],
  };
`
* **调用api返回值为**:
`
线上：{
    "code": 0,
    "data": [
        {
            "checked": true,
            "name": "IEEE Workshop on Automatic Speech Recognition and Understanding",
            "key": "paper",
            "user_id": "5b7642601c3e28453d57f6cd"
        },
    ],
    "success": true
}
线下：{
    "code": 0,
    "data": [
        {
            "checked": true,
            "name": "IEEE Workshop on Automatic Speech Recognition and Understanding",
            "key": "paper",
            "id": "5b7642601c3e28453d57f6cd"
        },
    ],
    "success": true
}
`
线上与线下返回以后，线上为user_id 字段，线下为id，线下没问题，不知道为什么线上会变成user_id,重启后会消失，但不一会又会出现。
有人遇到过这个问题么？还有就是每次上线都需要把node_module的文件夹删除，重新yarn安装才可以。

**Comment by atian25** [comment]
你确认 `config.transformConfig` 没有写到 local 去？

提供最小可复现仓库。

**Comment by williamnie** [comment]
@atian25  我写在config.default.js 里面了， config文件夹内有 default和local和plugin三个文件，并没有写prod，这样在线上应该走的是default吧，还是说必须要写个prod文件才不会被覆盖

**Comment by williamnie** [comment]
@atian25  我查看了线上的run/application_config.json 里面，和config是一样的，

`
 "transformConfig": {
      "rename": [
        {
          "new": "id",
          "old": "_id"
        }
      ]
    },
`
我现在把线上的run目录全部删除，重启了，再试试，我看看能不能做个最小实现，传上来，不过很难做。

**Comment by atian25** [comment]
run 目录是启动时自动生成的。

提供最小可复现方式吧。

**Comment by atian25** [comment]
找到原因了？

**Comment by williamnie** [comment]
@atian25  找到了，有个api会生命一个全局变量，config.transformConfig.rename:[{new:'user_id',old:'_id'}],把这里改了就好了，但是还是有点不明白，当调用这个api以后，config文件内的config.tansformConfig 被改变，理论上所有的请求回来的都应该是user_id了，但是，一直刷新同一个api，有时候就会正确（id），有时候就会错误（user_id），不知道是什么原因，时好时坏的

**Comment by atian25** [comment]
没太看懂。

至于时好时坏，多进程的原因吧

**Comment by williamnie** [comment]
有可能吧，egg交流群么？方便告诉下么？

**Comment by atian25** [comment]
https://github.com/eggjs-community/README
