### ISSUE TITLE
egg-squelize中nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by zhangguijian** [eggjs/egg#2937]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/41320802/44698360-2ebf7500-aab2-11e8-86eb-141bd5bdbd87.png)

目录结构
![image](https://user-images.githubusercontent.com/41320802/44698215-91fcd780-aab1-11e8-8af4-45989f1c3007.png)
//config//config.default.js
![image](https://user-images.githubusercontent.com/41320802/44698234-a7720180-aab1-11e8-9975-25232bc54946.png)
```
//config//config.unittest.js
'use strict';
exports.sequelize = {
    dialect:'mysql',
    host:'127.0.0.1',
    port:3306,
    database:'egg-sequelize-doc-unittest',
  };
```
//config//plugin.js
```
'use strict';
exports.sequelize = {
  enable: true,
  package: 'egg-sequelize',
};
```

**Comment by dead-horse** [comment]
数据库连接报错没权限，自查
