### ISSUE TITLE
请问在 egg 中，如何对 sequelize 进行合理配置？

### ISSUE THREAD

**Issue by monkeym4ster** [eggjs/egg#2938]
* **Node Version**: v8.11.1
* **Egg Version**: 2.10.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 4.0.7
* **Platform**: MacOS
* **Mini Showcase Repository**: null

我是参考 [示例项目](https://github.com/eggjs/examples/tree/master/sequelize) 中对数据库的配置。

在示例项目中有两处数据库相关的配置：

* ./database/config.json
* ./config/config.default.js

而两处的配置内容之中 **都有存在** `数据库名`、`服务器地址`、`帐号`和`密码`的配置，那么如何才是合理的配置呢？
难道是在 config.default.js 中直接 require 吗？

``` javascript
// ./config/config.default.js
require('../database/config.json').development
```

**Comment by denghongcai** [comment]
bingo. and if you do not need migrate, you will not need `database/config.json` at all.

**Comment by dead-horse** [comment]
两者目的不一样，如果你需要 migration 就去配置 database/config.json，至于要不要这样 require 进来，看你的心情，因为 config/config.default.js 中的配置项可以多过于 database/config.json
