### ISSUE TITLE
egg-view-nunjucks如何获取session？

### ISSUE THREAD

**Issue by Janking** [eggjs/egg#2944]
* **Node Version**: v8.11.3
* **Egg Version**:2.2.1
* **Plugin Name**:egg-view-nunjucks
* **Plugin Version**:2.2.0
* **Platform**:macos
* **Mini Showcase Repository**:none

**Comment by atian25** [comment]
Controller 获取

[『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)
