### ISSUE TITLE
How to resolve egg-mysql and egg-mongoose model conflicts??

### ISSUE THREAD

**Issue by StevenWung** [eggjs/egg#2945]
"egg": "^2.6.1",
 "egg-mongoose": "^3.1.0",
"egg-scripts": "^2.6.0",
"egg-sequelize": "^4.0.7",
"mysql2": "^1.6.1"

**Comment by dead-horse** [comment]
please use `egg-sequelize`'s delegate options. see https://github.com/eggjs/egg-sequelize#multiple-datasources
