### ISSUE TITLE
egg-passport/egg-passport-local登录失败怎么获取错误信息？

### ISSUE THREAD

**Issue by lijinshanmx** [eggjs/egg#2948]
` const localStrategy = app.passport.authenticate('local', {
    successRedirect: '/',
    failureRedirect: '/signin',
  });
`
怎么在登录失败的时候，传递错误信息，比如说用户名不存在或者密码错误等等，翻了好多issue和文档都找不到啊，egg-cnode里面的处理就是直接再次跳转登录页了，没办法给用户一直观的提示。。。failureRedirect回调只是一个简单的url地址，没办法获取到错误信息

**Comment by lijinshanmx** [comment]
@atian25

**Comment by lijinshanmx** [comment]
现在我这边的解决是在passport校验user的时候，如果校验不通过，直接throw(401, errormsg),然后在中间件中catch(next())，然后判断code，再把error信息render到view上去。不知道这样是不是符合规范。。。但是好像能解决问题。

**Comment by lijinshanmx** [comment]
@thonatos 能帮我看一下吗？这个怎么解决比较好？

**Comment by thonatos** [comment]
还没处理吧？我们把这类问题汇总一下，统一处理。

**Comment by lijinshanmx** [comment]
嗯嗯，希望有更好的解决方法。 @thonatos ，真是麻烦你们了。十分感谢~

**Comment by coderwow** [comment]
这个有解决方案吗

**Comment by atian25** [comment]
egg-passport-local 不要用了，直接自己写个 POST 的 Controller 处理
