### ISSUE TITLE
[Bug] ts 中想给 cookie 设置 `encrypt` 失败

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#2949]
* **Node Version**: 8.11.3
* **Egg Version**: 2.10.0
* **Plugin Name**: x
* **Plugin Version**:x
* **Platform**: macOS
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/7995232/44863548-f7b6b280-acaf-11e8-9057-411797996c81.png)
ts 中想给 cookie 设置 `encrypt` 失败，提示入上图。
```js
this.ctx.cookies.set('xxx', 'fff', {
  maxAge: expires_in - 60,
  signed: true,
  encrypt: true,
  httpOnly: true,
});
```

**Comment by BaffinLee** [comment]
这个参数是 [egg-cookies](https://github.com/eggjs/egg-cookies) 提供的，但是 ts 类型提示用的是 [cookies](https://github.com/pillarjs/cookies) 的，所以不行。要给 egg-cookies 加个 `index.d.ts`，欢迎 PR

**Comment by whxaxes** [comment]
这个不仅仅是给 egg-cookies 提个 PR 那么简单了，egg 中的 Context 里的 cookies 用的是 egg-cookies 的模块，是个独立的模块，但是 egg 的 context 的声明中却是 extend KoaApplication.Context ，这样就导致拿到 cookies 的声明是 koa 中的 cookies 声明，也就是 cookies 这个模块的。

所以得这么来做，第一步

1. 给 egg-cookies 添加个声明。
2. 在 egg 的声明中把 Context 的 cookies 这个属性的类型，复写为 egg-cookies 的实例类型。

不过这样又会带来另一个问题，就是 egg-cookies 的类型会跟 koa 中本来定义的 cookies 类型不兼容，因为少了些 cookies 中有的类型，然后就得用类型 overwrite 了，所以还得把 ts 中 Context 的定义从

```typescript
export interface Context extends KoaApplication.Context {
  ...
}
```

改成

```typescript
type KoaContext = Pick<KoaApplication.Context, Exclude<keyof KoaApplication.Context, 'cookies'>>
export interface Context extends KoaContext {
  ...

  cookies: EggCookies;
}
```

就是得先把 KoaApplication.Context 中的 cookie 剔除掉，才能够在 egg 的声明中复写。

**Comment by Maledong** [comment]
有必要那么麻烦吗？你加我QQ吧：424148000，我们详细描述，谢谢。

**Comment by whxaxes** [comment]
@Maledong  提示的同时，你要保证能正常编译，还有编译出来的代码不出错

**Comment by Maledong** [comment]
可以加我QQ和你细说吗？我有些问题需要问你，谢谢

**Comment by Maledong** [comment]
424148000

**Comment by whxaxes** [comment]
@Maledong  有问题你邮件我吧

**Comment by Maledong** [comment]
@whxaxes：谢谢，方便起见还是线上找你吧。
有几个问题：

1）我现在已经写了index.d.ts，问题是怎么让我的index.d.ts和egg-cookies实际关联起来？
2）目前的index.d.ts实际上是否只要公开一个EggContext即可（因为暴漏出来的只是this.ctx.cookies.XXX）：

```
import { SetOption, GetOption } from 'cookies';
import { Context as KoaContext } from 'koa'

//#region EggCookies
interface CookieGetOptions extends GetOption {
    /**
     * Encrypt the cookie's value or not (The default value is true).
     */
    encrypt?: boolean
}
interface CookieSetOptions extends SetOption {
    /**
     * Encrypt the cookie's value or not (The default value is true).
     */
    encrypt?: boolean
}

interface EggCookies {
    /**
     * Get the Egg's cookies by name with optional options.
     * @param name The Egg's cookie's unique name.
     * @param opts Optional options for cookie's setting.
     */
    get(name: string, opts?: CookieGetOptions): string;
    /**
     * Set the Egg's cookies by name with optional options.
     * @param name The Egg's cookie's unique name.
     * @param opts Optional options for cookie's setting.
     */
    set(name: string, value?: string, opts?: CookieSetOptions): this;
}

//#endregion

//#region EggContext

// Remove `U` from `T`
type Filter<T, U> = Pick<T, Exclude<keyof T, U>>;

export interface Context extends Filter<KoaContext, 'cookies'> {
    cookies: EggCookies
}
//#endregion

```
3）怎么写单元测试，有实际参考的例子吗？
谢谢了。

**Comment by Maledong** [comment]
@whatwewant：Fixed all, please have a review. Thanks!
