### ISSUE TITLE
egg-router 根据路由前缀设置中间件

### ISSUE THREAD

**Issue by Janking** [eggjs/egg#2950]
* **Node Version**: v8.11.3
* **Egg Version**:2.2.1
* **Plugin Name**:egg-router
* **Plugin Version**:2.2.0
* **Platform**:macos
* **Mini Showcase Repository**:none

我之前使用koa-router的时候，可以设置前缀中间件，如下代码所示：
```
const router = new Router({
  prefix : '/report'
})

router.use(async (ctx, next) => {
  // 但凡跳转的路径前缀是/report的，都先进行一些权限判断
})
```

但是在egg-router上没找到有这样的功能，如果没有的话，像这种权限拦截的只能按照文档上的这种方式做吗？

```
  router.post('/user', isLoginUser, hasAdminPermission, controller.user.create);
```

**Comment by atian25** [comment]
use global middleware with `match` config
