### ISSUE TITLE
egg-view-nunjucks 模板上读取app.locals的值显示不出来

### ISSUE THREAD

**Issue by Janking** [eggjs/egg#2951]
* **Node Version**: v8.11.3
* **Egg Version**:2.2.1
* **Plugin Name**:egg-view-nunjucks
* **Plugin Version**:2.2.0
* **Platform**:macos
* **Mini Showcase Repository**:none

我在中间件里将请求的query值传递给`ctx.app.locals`中
```
/*  app/middleware/xx.js */
module.exports = () => {
  return async function templateVariable(ctx, next) {
    ctx.app.locals.query = ctx.request.query;
    await next();
  };
};

```
然后在模板页上输出，但显示为空
```
/* app/view/index.html */

<form method="GET">
    <input type="text" name="keyword" value="{{query.keyword}}" maxlength="50" class="form-control">
</form>
```
换一种方式写就可以

```
<form method="GET">
    <input type="text" name="keyword" value="{{'hello' if query.keyword === 'hello' else 'world' }}" >
</form>
```

**Comment by atian25** [comment]
仔细看文档。 `app.locals` 是全局的，`ctx.locals` 才是你要的

**Comment by Janking** [comment]
@atian25  你好，文档中这句话不理解，能否引申说明一下？
> ctx.locals 有缓存，只在第一次访问 ctx.locals 时合并 app.locals。

另外，`ctx.app.locals` 只能在`app.js`中设置才有效吗？

> app.locals 为全局的，一般在 app.js 里面配置全局变量。

既然`ctx.locals`会合并到`app.locals`上，我直接在中间件上把值都传给`app.locals`不就行了？为什么设计上要做两个区分呢？

**Comment by BaffinLee** [comment]
缓存的意思是第一次get `ctx.locals` 的时候会合并 app.locals，之后不会
nodejs 是常驻内存的，每个请求用的都是同一个 app，但是 ctx 是请求级别的，每个请求都有一个新的 ctx。你用 app.locals 会影响所有请求。

**Comment by atian25** [comment]
> 既然 ctx.locals 会合并到 app.locals 上

你理解反了，这里面你可以理解为：

```js
render(tpl, locals) {
  locals = Object.assign({}, app.locals, ctx.locals, locals);
  // ...
}
```
