### ISSUE TITLE
egg+vue 无法通过egg-scripts启动

### ISSUE THREAD

**Issue by lv-jie** [eggjs/egg#2953]
我通过egg-init --type=simple 创建了一个骨架，然后通过easywebpack添加了vue作为渲染引擎，再使用egg-scripts就无法启动了。
  ##package.json
<pre>
{
  "name": "egg-vue",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "axios": "^0.18.0",
    "egg": "^2.2.1",
    "egg-scripts": "^2.5.0",
    "egg-view-vue-ssr": "^3.1.2",
    "vue": "^2.5.17",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "autoprefixer": "^9.1.3",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "cross-env": "^5.2.0",
    "easywebpack-vue": "^4.1.2",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.14.0",
    "egg-webpack": "^4.1.2",
    "egg-webpack-vue": "^2.0.1",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "eslint-plugin-vue": "^4.7.1",
    "imagemin-webpack-plugin": "^2.2.0",
    "uglifyjs-webpack-plugin": "^1.3.0",
    "vue-template-compiler": "^2.5.17",
    "webpack-manifest-resource-plugin": "^4.2.4",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=8.9.0"
  },
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-egg-vue",
    "start-easy":"cross-env EGG_SERVER_ENV=prod NODE_ENV=production node index.js",
    "stop": "egg-scripts stop --title=egg-server-egg-vue",
    "dev": "egg-bin dev",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod",
    "build": "cross-env easy clean && easy build prod",
    "build:dev": "cross-env easy clean && easy build dev",
    "build:test": "cross-env easy clean && easy build test",
    "build:prod": "cross-env easy clean && easy build prod"
  },
  "ci": {
    "version": "8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "lvjie",
  "license": "MIT"
}

<pre>

**Comment by hubcarl** [comment]
@lv-jie  请贴一下具体错误， 自己添加相关依赖后，还有一些配置需要配置的，你看一下这个  https://github.com/hubcarl/egg-vue-webpack-boilerplate 是否可以启动 或者通过 easywebpack-ci 初始化项目看看
