### ISSUE TITLE
egg httpClient 如何设置全局配置？

### ISSUE THREAD

**Issue by Janking** [eggjs/egg#2954]
* **Node Version**: v8.11.3
* **Egg Version**:2.2.1
* **Plugin Name**:egg-httpClient
* **Plugin Version**:2.2.0
* **Platform**:macos
* **Mini Showcase Repository**:none

第一个问题：HttpClient 默认全局配置能否设置options呢？

因为有很多接口需要使用`ctx.curl(url,options)`，而options中有很多参数是一样的，如：`content-type`,`method`，每个接口都写一遍的话很麻烦。

第二个问题：`ctx.curl(url)`中的`url`能否设置`baseUrl`？如果接口域名有变，只要修改baseUrl就可以了

**Comment by atian25** [comment]
没有什么是看源码解决不了的

https://github.com/eggjs/egg/blob/master/lib/core/httpclient.js#L15
