### ISSUE TITLE
上传图片，图片不全问题

### ISSUE THREAD

**Issue by Sunshop** [eggjs/egg#2955]
ctx.getFileStream() 返回的 FileStream 中的__readableState 字段中的buffer中的BufferList head及tail 这两个的区别是什么？如果上传到第三方云服务器使用哪个字段呢 ？

**Comment by Sunshop** [comment]
@egg-bot  great

**Comment by popomore** [comment]
You can see this example https://github.com/eggjs/examples/tree/master/multipart
