### ISSUE TITLE
Property 'xxModel' does not exist on type 'Sequelize'

### ISSUE THREAD

**Issue by superlbr** [eggjs/egg#2956]
* **Node Version**: 8.11.3
* **Egg Version**: 2.10.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 4.1.0
* **Platform**: mac

error location: ctx.model.xxModel
what happened? npm run tsc just after upgrade npm packages

got sth. in git log for typings/app/model/index.d.ts

```
-declare module 'sequelize' {
-  interface Sequelize {
+declare module 'egg' {
+  interface IModel {
```

copy an old yarn.lock for temp fix

**Comment by StevenWung** [comment]
I met the same issue.
Upgrading **egg-ts-helper** does not work for me.
Any other way out?

**Comment by whxaxes** [comment]
https://github.com/eggjs/examples/tree/master/sequelize-ts

@StevenWung  see the example

**Comment by StevenWung** [comment]
@whatwewant Thanks.
But I tried the given example, it's still not working.
Mine is new-created project. 
```
{
    "egg": "^2.6.1",
    "egg-scripts": "^2.6.0",
    "egg-sequelize": "^4.3.1",
    "mysql2": "^1.6.5"
}
```

```
{
    {
    "@types/mocha": "^2.2.40",
    "@types/node": "^7.0.12",
    "@types/supertest": "^2.0.0",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-ci": "^1.8.0",
    "egg-bin": "^4.6.2",
    "egg-mock": "^3.16.0",
    "tslib": "^1.9.0",
    "tslint": "^5.0.0",
    "egg-ts-helper": "^1.11.1",
    "tslint-config-egg": "^1.0.0",
    "typescript": "^3.0.0"
  }
```

Error :
error TS2339: Property 'X' does not exist on type 'Sequelize'.

**Comment by whxaxes** [comment]
@StevenWung  Upgrade `egg-sequelize` to `^5.0.0`

**Comment by StevenWung** [comment]
It's working now. 
Thanks a lot @whxaxes
