### ISSUE TITLE
使用 egg-init 初始化 sequelize 模板失败

### ISSUE THREAD

**Issue by schinvendy** [eggjs/egg#2959]
* **Node Version**:  v10.9.0
* **Egg-init Version**: 1.14.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows 10
* **Mini Showcase Repository**:

使用 egg-init 初始化 sequelize 模板失败。

直接使用 egg-init 会一直停留在fetching npm info of egg-boilerplate-sequelize
![x0qq4_ck 4 t 5enz5hg0wn](https://user-images.githubusercontent.com/17189558/44963629-733d8b80-af5e-11e8-87c9-6e1eedf573e9.png)

使用 egg-init --type sequelizelai 来初始化，会停留在 write to \test\factories.js，然后就没有动静了。
![9_a 5if t twy2g 04lxgl](https://user-images.githubusercontent.com/17189558/44963765-4a69c600-af5f-11e8-9747-a5fda8a5ba82.png)

npm的registry默认是淘宝源，但init时是npm源。也尝试init时加上-r换成淘宝源，不过也是一样的问题。

请问是什么原因？

**Comment by dead-horse** [comment]
多重试几次呢？看起来执行卡住了，或者这时候你直接中断进程好了，应该已经执行完了

**Comment by xudaosong** [comment]
我也遇到同样的问题，求解决

**Comment by dead-horse** [comment]
@atian25 看看 egg-init 是不是有可能会卡住？或者加个 debug 的模式帮忙排查问题？

**Comment by RookieHao** [comment]
我也遇到同样的问题，卡在这里下载模板这里不动了。重启电脑，重新npm i egg-init  -g。都解决不了

**Comment by fuiyu** [comment]
同样的问题。。。没人解决？

**Comment by whxaxes** [comment]
更新 egg-init 到 1.15.1 试一下
