### ISSUE TITLE
examples中assets-width-roadhog例子中,如何修改html模板

### ISSUE THREAD

**Issue by kstar11** [eggjs/egg#2960]
down了examples中的assets-with-roadhog这个例子工程,从install到dev,build,start,stop都是ok的
就是找不到地方修改html模板,修改一下html的title,引入一下favicon,又或者增加meta标签
试过egg-view-assets中提供templatePath,title设置成功了,但是不会引入js文件
求解!

**Comment by BaffinLee** [comment]
`roadhog` 的文档 [https://github.com/sorrycc/roadhog#html](https://github.com/sorrycc/roadhog#html) 应该能解决你的问题

**Comment by popomore** [comment]
看下文档，有多种使用方式，定义模版是要按照规范 https://eggjs.org/zh-cn/tutorials/assets.html
