### ISSUE TITLE
[Discussion] 分布式爬虫数据收集与处理方案

### ISSUE THREAD

**Issue by thonatos** [eggjs/egg#2962]
## 背景

一个分布式爬虫系统，工作流程是n个小型阿里云ecs爬虫拿到数据后socket.io发回到中小型阿里云ecs主控，主控做数据运算后将数据放入到阿里云rds，数据量很大，egg里用了async/await库的queue队列。

## 问题

爬虫返回给主控的数量量比主控运算的速度还快，十来分钟队列就会积了几十万导致主控的node进程崩了

## 方案

> TODO

**Comment by ColorfulPang** [comment]
我们现在的处理有
1、中心是rabbitmq集群

分布式调度服务：
2、调度的server会先把任务发到队列中。

分布式爬虫：
3、分布式爬虫去消费这个队列。
4、然后把处理结果再返回到另外的结果队列中

分布式解析服务：
5、会有专门的解析服务去解析结果队列。
6、如果处理不完，会把解析服务拆分成若干个，形成一个pipeline，这些都是微服务。
7、最后才入库。数据库，我们现在用的是分布式的elasticsearch。

**Comment by liujiusheng** [comment]
如果是运算性能问题的话，WebAssembly不知道能不能从一定程度上解决问题。感觉计算性能大概可以提高10倍唉。

**Comment by dead-horse** [comment]
issue 用于反馈框架问题，这些讨论可以移步合适的社区。

**Comment by thonatos** [comment]
@dead-horse 好的
