### ISSUE TITLE
 定时任务持续执行约 24 天后停止

### ISSUE THREAD

**Issue by ziyunfei** [eggjs/egg#2964]
* **Node Version**: alinode-4.1.0
* **Egg Version**: @ali/egg-4.2.1

每十秒执行一次的定时任务：
```
exports.schedule = {
  interval: '10s',
  type: 'worker',
}

exports.task = async ctx => {
...
```
从 8 月 9 号执行到 9 月 3 号中午自动停止，直到我 9 月 4 号晚上重启服务后继续开始执行：
![image](https://user-images.githubusercontent.com/1276859/45030917-fdc9dc00-b07f-11e8-8e9f-731dbcd78843.png)

看起来像是超过了 `(2**31-1)/1000/3600/24` ≈ 24.85 天后就停止了，是我哪里用法搞错了吗？

**Comment by BaffinLee** [comment]
alinode 有监控到异常吗

**Comment by atian25** [comment]
好像最近看到谁在群里面发过，一个 Node 的 bug 修复，依稀记得就是长时间循环 setTimeout 的。

**Comment by atian25** [comment]
@ngot https://github.com/nodejs/node/issues/22149

**Comment by Maledong** [comment]
@ziyunfei：Make sure that your actual execution time MUST BE smaller than your delay time defined in 'setInterval'. Just a notify for you.
For more details, please see：https://www.thecodeship.com/web-development/alternative-to-javascript-evil-setinterval/

**Comment by BaffinLee** [comment]
症状和 node 的那个 bug 差不多，影响了 10.0 ~ 10.8 。如果是这个原因的话，升级 alinode 到 v4.3.0，对应 Node 10.9 ，可解决。

**Comment by ziyunfei** [comment]
貌似的确已经修复了 https://github.com/nodejs/node/pull/22214，我更新 alinode 试试。

**Comment by shiny** [comment]
我也遇到类似问题，每隔个把月左右定时器意外不更新，重启后恢复。更新下 node 版本看看会不会恢复正常。
