### ISSUE TITLE
eslint 配置和编译报错TypeError问题

### ISSUE THREAD

**Issue by attraction11** [eggjs/egg#2965]
前辈 关于egg-ant-design-pro想和你交流两点
1、config.default.js文件中的 DISABLE_ESLINT: true, 可以替换为 ESLINT: 'none'。
2、项目npm install、npm run dev 后报 “TypeError: Property right of Assignment Expression expected node to be of a type ["Expression"] but instead got null” 的问题。
清楚报错意思但没找到原因，不知前辈可否指点一二？

**Comment by attraction11** [comment]
我尝试了最新的版本10.9.0 仍然报同样问题。请问你下载后可以正常启动？

**Comment by okoala** [comment]
@attraction11  提供下可重现的 demo
