### ISSUE TITLE
环境变量不生效

### ISSUE THREAD

**Issue by kasora** [eggjs/egg#2968]
如果运行 `egg-scripts start` 的话，无论 `NODE_ENV` 如何设置，都会显示成 `production`
同时 `isProduction` 也会被置 `true` 

请问这是显示问题还是说 `egg-scripts` 会手动置位 `NODE_ENV` ？

![screenshot_20180906_115131](https://user-images.githubusercontent.com/13925549/45134065-33c7a700-b1cb-11e8-80cc-020052195737.png)

**Comment by atian25** [comment]
服务器环境必须是 production，不管是正式，测试，开发。

如果是你的代码需要判断，尽量通过 `config.{env}.js` 或 `app.config.env` 的方式
