### ISSUE TITLE
如何在命令行输出 console.log 的详细信息(哪个文件在哪一行输出的)????

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [eggjs/egg#2971]
* **Node Version**: 10.7.0
* **Egg Version**: ^2.10.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

### 怎样才能输出`console`的信息(哪个文件在哪一行输出的此`console`)

**Comment by atian25** [comment]
非 egg 相关问题，自己搜索下。

只能通过抛 error 的方式获取 stack 来分析，线上不要使用。

**Comment by atian25** [comment]
印象中你如果在 vscode 里面的话，IDE 自带支持了
