### ISSUE TITLE
mysql select where 如何设置不等于‘<>’

### ISSUE THREAD

**Issue by luogeng2017** [eggjs/egg#2975]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

遇到个想查找不为空的。这个在select 的where怎么设置

**Comment by killagu** [comment]
与 egg 无关

**Comment by roc2539** [comment]
.....那与谁有关？ @killagu

**Comment by LDXu** [comment]
666
