### ISSUE TITLE
 'Subscription' was also declared here. typescript项目,两个定时文件的时候会报错.

### ISSUE THREAD

**Issue by Fantasy9527** [eggjs/egg#2976]
* **Node Version**: v10.7.0
* **Egg Version**:2.6.1
* **Platform**: mac

 typescript项目,两个定时文件的时候会报错.
当定时任务有多个的时候lint会提示:
```
 'Subscription' was also declared here.
```

并且编译报错:
```
app/schedule/Collect.ts(1,7): error TS2451: Cannot redeclare block-scoped variable 'Subscription'.

app/schedule/Collect.ts(1,7): error TS2451: Cannot redeclare block-scoped variable 'Subscription'.
```

**Comment by Fantasy9527** [comment]
普通js版本的egg没有这样的问题

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
