### ISSUE TITLE
如何调度CPU执行运算量比较大的任务

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#2977]
现在有个场景是需要根据某个表的数据去请求某个接口获取数据回来更新。但是这个表一共有3000多条数据，遍历3000多条数据去请求接口然后拿到数据回来还要执行更新的sql语句。整个运算下来差不多要好几分钟，甚至更久。目前需要在30秒内完成，想到的解决方案就是调度多个CPU去执行，打算把服务器升级到8核，然后8个cpu去执行这个任务，平均每个CPU运算300多条数据。不知道这样可不可行，关键是不知道怎么从代码上去写调度cpu的业务逻辑，egg有提供这类场景的解决方案或者插件吗？

**Comment by Leungkingman** [comment]
@tong3jie 我的思路就是这样，可是我不知道该怎么写这个多线程的代码。一个cpu对应一个线程，那如何让多核的计算机开启多线程的任务

**Comment by zhq3k** [comment]
个人感觉你想复杂了，批量更新应该就能实现，不要一条一条更新。

**Comment by atian25** [comment]
你这 3000 个股票又不是需要原子操作。做个定时任务，慢慢做就好了

**Comment by Leungkingman** [comment]
@atian25 这只是一个很简单的业务场景例子而已，实际上的逻辑会复杂一些，而且这3000多个股票需要在30秒内完成

**Comment by atian25** [comment]
一般来说，这类的交互，都会丢到任务队列去处理，至于处理时限那就看你的 consumer workers 的数量了。

**Comment by Leungkingman** [comment]
@atian25 还是没太懂，意思是只要扩展服务器的CPU就可以了吗？

**Comment by atian25** [comment]
可以看下 https://zhuanlan.zhihu.com/p/44439782

**Comment by wanghsinche** [comment]
我也遇到类似问题，由于某种原因，我们需要对一大批数据在egg用js计算，然后输出，不准用addone。一开始想法是用threads.js这个库来做。但考虑IPC传递大量数据性能很差，最终也许会变成任务拆分+德拉雅函数来做。  目前还没最终方案。

**Comment by wanghsinche** [comment]
> @wanghsinche 这种场景适合用 云函数 https://help.aliyun.com/document_detail/52895.html?spm=a2c4g.11186623.6.541.7bed265a4MGZEp

thk  我去看看
