### ISSUE TITLE
docker run 启动egg项目成功后无法退出到编辑linux的状态

### ISSUE THREAD

**Issue by menkeydyvh** [eggjs/egg#2978]
问题：如标题
docker run 启动egg项目成功后无法退出到编辑linux的状态

···  图片上可以看到 一只保留这个状态  
![image](https://user-images.githubusercontent.com/20472494/45249551-bd56b080-b354-11e8-9384-477514f41cde.png)

---  docker 命令
docker run -t -i -p 8099:7001  xxxx  

--- package.json  npm start 命令执行行
"start": "egg-scripts start --port=7001",

当然 打开一个新的操作端是可以的  但是总感觉是个bug 

希望能解决一下！

**Comment by menkeydyvh** [comment]
有人提出  docker run -d 命令
-d后是可以继续编辑linux  但是看不到启动的过程  会导致有些东西是否加载我看不到

**Comment by sunfuze** [comment]
docker logs ${containerId}，docker 设计就不是为了让你在前台运行

**Comment by popomore** [comment]
Ctrl c 看看

**Comment by menkeydyvh** [comment]
@popomore  ctrl +c 会把启动的egg项目也一起退出了

**Comment by popomore** [comment]
肯定的啊，你在 linux 前台起个进程也不能关闭 terminal 的。所以你的需求就是用 -d
