### ISSUE TITLE
pump 上传问题

### ISSUE THREAD

**Issue by Jialufeng** [eggjs/egg#2991]
await pump(stream, writeStream);  await pump  oss上传图片是空的，本地没问题。去掉pump 就没问题了，需要 把 pump 传过去吗？await ctx.oss.put('xianrenbar/' + filename, stream)

![image](https://user-images.githubusercontent.com/16443142/45346898-39fbc000-b5dd-11e8-8b85-b1b4538f1011.png)

**Comment by fengmk2** [comment]
stream has been consumed by writeStream.

**Comment by Maledong** [comment]
@Jialufeng：
Try to comment out：
```js
const writeStream = ……;
await pump (……);
```
These two statements are for your local testing, and the 2nd will consume your stream to writeStream. Then your stream will be empty. So your uploaded file is empty.
