### ISSUE TITLE
framework router question

### ISSUE THREAD

**Issue by Jayanzhou** [eggjs/egg#2993]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

新建了一个framework，里面配了router，前端发出的api请求没有经过framework 的router处理，而且外部的app 路由里面也没有配置相应api 路由处理信息，但是该api请求返回200 成功，请问怎么让framework配置的router生效呢，看官网说framewrok支持router配置的，谢谢。

**Comment by Jayanzhou** [comment]
涉及的模块有点多，不好附上code哈，抱歉

**Comment by atian25** [comment]
看反了吧，插件和框架都不支持 router
