### ISSUE TITLE
egg-session 无法设置_下划线开头的名称

### ISSUE THREAD

**Issue by shenjianzch** [eggjs/egg#2999]
* **Node Version**:8.9.3
* **Egg Version**:2.2.1
* **Plugin Name**:egg-session
* **Plugin Version**:
* **Platform**:mac
* **Mini Showcase Repository**:

我在尝试往session中插入以_开头的名称(例：_x_y_)这样的名称写进session的时候不能成功写入 只要不是以_开头的 都是Ok的 我想知道 是我用的不对还是egg 做了特殊处理 因为我发现session中默认会有两个_开头的对象名称 只是不显示 
我想知道我怎么样能成功写入 因为我现在的去求 必须是_开头 所以来问问
例：
![image](https://user-images.githubusercontent.com/7286498/45461757-675c8100-b737-11e8-8011-604f3b4a1628.png)
这样的 只有_下划线开头的无法写入
![image](https://user-images.githubusercontent.com/7286498/45461802-8c50f400-b737-11e8-8937-2091ca58301f.png)

**Comment by atian25** [comment]
https://github.com/koajs/session/blob/master/lib/session.js#L42

https://github.com/expressjs/express/issues/1459

**Comment by shenjianzch** [comment]
@atian25 感谢知道原因了

**Comment by Runrioter** [comment]
@atian25  @shenjianzch expressjs/express#1459 这个是ie domain中存在`_`的怪异行为。

此处原因是`_`为内部属性的标识，因此排出了。

还是建议用非`_`prefix的key值

**Comment by fengmk2** [comment]
RFC 规范不允许下划线作为 cookie name https://github.com/expressjs/express/issues/1459#issuecomment-11909889
