### ISSUE TITLE
npm start 启动报错

### ISSUE THREAD

**Issue by thisWangKun** [eggjs/egg#3000]
我在测试服上是可以npm stop之后再npm start的，但是重启正式服之后第一次是可以npm start 的，但是npm stop之后，再npm start 之后就会报错，错误log如下
![f3463dfeac9cde4309e8671af1604cd](https://user-images.githubusercontent.com/36184443/45469319-971d8000-b75b-11e8-9f87-7327e32392f5.png)
    /root/logs/master-stderr.log的错误如下
![image](https://user-images.githubusercontent.com/36184443/45469473-49edde00-b75c-11e8-855d-8ca152b4d761.png)
   /root/.npm/_logs/2018-09-13T05_53_08_247Z-debug.log的错误如下
![image](https://user-images.githubusercontent.com/36184443/45469534-76095f00-b75c-11e8-9323-a81fc3b243ed.png)
希望能解答一下

**Comment by atian25** [comment]
你先解决下第二张图中这个报错问题吧，过时的 API 跟第一次第二次没关系

**Comment by hyj1991** [comment]
你的测试服务器上的 node 版本和线上不一样吧

Node 8 里面还没有：[Node 8#Deprecated APIs](https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html)
Node 10 里面把这个 api 废弃了：[Node 10#Deprecated APIs#deprecations_dep0095_timers_enroll](https://nodejs.org/dist/latest-v10.x/docs/api/deprecations.html#deprecations_dep0095_timers_enroll)

**Comment by thisWangKun** [comment]
> 你先解决下第二张图中这个报错问题吧，过时的 API 跟第一次第二次没关系
> 
> 或者临时加个 egg-scripts 的 `--ignore-stderr` 参数看看是否正常

**Comment by thisWangKun** [comment]
> 你的测试服务器上的 node 版本和线上不一样吧
> 
> Node 8 里面还没有：[Node 8#Deprecated APIs](https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html)
> Node 10 里面把这个 api 废弃了：[Node 10#Deprecated APIs#deprecations_dep0095_timers_enroll](https://nodejs.org/dist/latest-v10.x/docs/api/deprecations.html#deprecations_dep0095_timers_enroll)
> 
> 因为使用了废弃的 api，内核会把 warning 输出到 stderr 里面，框架判定启动出错

跟你这么一说，那为什么启动第一次能正常启动呢？而且npm run dev也可以正常启动，所以我就有点纳闷了。

**Comment by atian25** [comment]
> 而且npm run dev也可以正常启动

`npm run dev` 是开发期的，调用 egg-bin，自然不会去检测这些错误。

`npm start` 是调用 egg-scripts 的。

> 那为什么启动第一次能正常启动呢？ 

所以才让你查下，提供可复现方式。

**Comment by thisWangKun** [comment]
> > 而且npm run dev也可以正常启动
> 
> `npm run dev` 是开发期的，调用 egg-bin，自然不会去检测这些错误。
> 
> `npm start` 是调用 egg-scripts 的。
> 
> > 那为什么启动第一次能正常启动呢？
> 
> 所以才让你查下，提供可复现方式。

OK,我试下降到Node 8版本看行不行。

**Comment by thisWangKun** [comment]
> 你先解决下第二张图中这个报错问题吧，过时的 API 跟第一次第二次没关系
> 
> 或者临时加个 egg-scripts 的 `--ignore-stderr` 参数看看是否正常

过时的api 应该不会造成应用启动不了吧？我先加个--ignore-stderr参数看下

**Comment by atian25** [comment]
那是 egg-scripts 本身的机制，启动的时候会检查，如果有 error 日志，就会失败，这样就能快速发现问题。

**Comment by thisWangKun** [comment]
> 那是 egg-scripts 本身的机制，启动的时候会检查，如果有 error 日志，就会失败，这样就能快速发现问题。

我知道什么原因了，我猜是启动时api过时报的Warning，node误以为有error,加一个--ignore-stderr参数就解决了，不过还是感谢你给的启发，我要在本地测试测试下是不是版本不一致导致的问题。现在生产环境能正常启动了。

**Comment by atian25** [comment]
但还是不能解释你说的第一次能启动这个点

**Comment by thisWangKun** [comment]
> 说的第一次能启动这

所以我要在本地建个环境查看一下是不是这个原因导致的。线上环境能不动就不动吧。
