### ISSUE TITLE
eslint-config-egg不支持spread operator

### ISSUE THREAD

**Issue by wushanchao** [eggjs/egg#3002]
* **Node Version**: 8.9
* **Egg Version**:  2.10
* **Plugin Name**: eslint-config-egg
* **Plugin Version**: 6.0.0
* **Platform**: win10
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
1. eslint 自己配置下 rule 就好了
2. object spread operator 目前还不是正式版本支持的。

**Comment by popomore** [comment]
请升级版本
