### ISSUE TITLE
關於客製錯誤擴展 Custom Error Extend

### ISSUE THREAD

**Issue by kkshyu** [eggjs/egg#3007]
目前主要使用 `onerror` 來處理錯誤，但有些錯誤想自行定義，如下
```
class CustomError extend Error {
    constructor(message) {
        super('custom error: ' + message)
    }
}
```
想請問這樣的定義放在 `app/extend/error.ts`, `app/extend/context.ts` 還是 `app/extend/application.ts` 比較好呢？ 或是在 egg.js 是否有 Best practice 可以參考？

----

So far, I have used `onerror` for error handling, but i would like to define my own Error like this
```
class CustomError extend Error {
    constructor(message) {
        super('custom error: ' + message)
    }
}
```
is there any suggestion about where to put this file in egg application?
`app/extend/error.ts`, `app/extend/context.ts`, or `app/extend/application.ts`?
or any best practice to take?

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/1086
