### ISSUE TITLE
egg-logger性能问题

### ISSUE THREAD

**Issue by hearAllParties** [eggjs/egg#3012]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问一下egg日志模块的性能问题如何，比如多大的量写日志文件的时候会影响到服务器性能，或者说压垮服务器。
看源码，主要是写内存，再写到文件。
![image](https://user-images.githubusercontent.com/14330629/45660062-c2241d00-bb29-11e8-86d8-54a4253812e5.png)

另外默认了maxBufferLength = 1000，flushInterval = 1000是否能对外开放这两个配置。

附上node各日志库的测试报告：https://www.loggly.com/blog/a-benchmark-of-five-node-js-logging-libraries/

**Comment by dead-horse** [comment]
有兴趣可以做个 benchmark，从实践来看还达不到特别影响线上应用性能的程度，但是肯定还有优化空间。

**Comment by hearAllParties** [comment]
10分钟压测，用2核4g的机器，cpu100%，写日志和不写日志，吞吐量相差100+/s；4核4G，cpu75%，基本没差了。
