### ISSUE TITLE
nunjucks plugin Customize Syntax not working

### ISSUE THREAD

**Issue by zhangwen9229** [eggjs/egg#3013]
* **Node Version**:8.11.2
* **Egg Version**:2.2.1
* **Plugin Name**:egg-view-nunjucks
* **Plugin Version**:2.2.0
* **Platform**:Linux
* **Mini Showcase Repository**:

I put code in config/plugins.js,but tags config not work.
Please help me to resolve it.
```
exports.nunjucks = {
    enable: true,
    package: 'egg-view-nunjucks',
    tags: {
        blockStart: '{%',
        blockEnd: '%}',
        variableStart: '<$',
        variableEnd: '$>',
        commentStart: '<#',
        commentEnd: '#>'
    }
};
```

**Comment by atian25** [comment]
it's a config of config... not plugin .....

**Comment by zhangwen9229** [comment]
(∩_∩)
