### ISSUE TITLE
egg-alinode不支持Node.js 性能平台的trace功能

### ISSUE THREAD

**Issue by yun77op** [eggjs/egg#3022]
文档里有说使用tracing分支的agenthub，但没提及Egg 集成部署的如何操作

所以

1. egg-alinode目前应该是不支持Node.js 性能平台的trace功能的吧？
2. 有计划支持吗？

**Comment by hyj1991** [comment]
tracing 功能目前的流程是用户使用 [@alicloud/opentracing](https://www.npmjs.com/package/@alicloud/opentracing) 模块进行自主打点后用 @tracing tag 的 agentx 收集而已。
所以如果想在 egg 上体验也很简单，不要用默认的 egg-alinode 启动 agentx 就好了，直接使用 [agenthub@tracing](https://help.aliyun.com/document_detail/72715.html?spm=a2c4g.11186623.6.567.7a1b3e54aoFUFi)  部署 agentx 连接，然后按照 [Node.js 性能平台 - 慢链路追踪](https://www.npmjs.com/package/@alicloud/opentracing) 文档打点即可。

**Comment by atian25** [comment]
@hyj1991 这个功能未来会集成到 agentx 么？ 如果会的话，是不是发布一个 egg-alinode@next ？

**Comment by hyj1991** [comment]
@atian25 肯定是打算合入 agentx 的 master 的，如果合入就不用发布新的版本了，直接现在的 egg-alinode 用法用就好

**Comment by atian25** [comment]
@hyj1991 就看你们啥时候了，如果会比较久的话，可以考虑发一个 `egg-alinode@next` 给用户尝鲜

**Comment by hyj1991** [comment]
@atian25 嗯，我也是这么想的

**Comment by yun77op** [comment]
ok，辛苦各位

**Comment by JacksonTian** [comment]
@hyj1991 功能稳定的话，可以merge 到 master 并发布。

**Comment by xuezier** [comment]
所以能用了吗

**Comment by hyj1991** [comment]
> 所以能用了吗

能
