### ISSUE TITLE
egg-view-nunjucks 动态模版问题

### ISSUE THREAD

**Issue by Jialufeng** [eggjs/egg#3026]
path: view/history/history.html

await this.ctx.render('/history/:id', {a:1}) ?
怎么渲染动态路由? 需要nginx代理吗？

**Comment by Jialufeng** [comment]
没有看到 我找了一下 好像没有动态渲染的例子，我试了一下 那样写不行，有没有好的办法？

**Comment by atian25** [comment]
你是不是理解错什么了？ render 是渲染模板文件，不是路由

**Comment by Jialufeng** [comment]
确实是，理解错了，已经解决了，感谢！
