### ISSUE TITLE
无法安装egg-mysql

### ISSUE THREAD

**Issue by rise0chen** [eggjs/egg#3027]
* **Node Version**: v10.4.0
* **Egg Version**: 2.11.2
* **Plugin Name**: egg-mysql
* **Plugin Version**: 3.0
* **Platform**: windows

执行`npm i --save egg-mysql`后，无法出现404错误，如图所示  
![_20180920203839](https://user-images.githubusercontent.com/12853908/45818759-3ff84c00-bd15-11e8-8a68-2d98e74d113f.png)  
在npm官网上可以搜索到co-wrap-all，但是无法安装。

**Comment by dead-horse** [comment]
确认一下你的 registry 地址是否是官方源，或者换用 cnpm 试试。
