### ISSUE TITLE
egg-cors index.d.ts 缺少设置

### ISSUE THREAD

**Issue by callmez** [eggjs/egg#3036]
```js
export interface EggAppConfig {
    cors: {
      origin: string | (() => string);
      allowMethods: string | string[];
      credentials: boolean; // 缺少
    };
  }
```

在使用egg-ts时总是有些不顺畅部分,
像egg-cors这种缺少设置的总是, 不管在`typings/index.d.ts`中设置还是在`config.default.ts`中设置都不能实现declaration-merging. 
`typings/index.d.ts`
```js
declare module 'egg' {
  export interface EggAppConfig {
    cors: {
      origin: string | (() => string);
      allowMethods: string | string[];
      credentials: boolean;
    };
  }
}

```

**Comment by Maledong** [comment]
不清楚你那边是如何做的？我这里是可以的：
![cors](https://user-images.githubusercontent.com/40081831/45925058-a319f680-bf40-11e8-82e2-52c0396fe6d8.png)

**Comment by callmez** [comment]
![image](https://user-images.githubusercontent.com/1625891/45927095-46c6cf00-bf60-11e8-85e7-cefa5662576e.png)
![image](https://user-images.githubusercontent.com/1625891/45927116-c5237100-bf60-11e8-8270-d529e5da9413.png)

`npm run tsc` 过不去

**Comment by Maledong** [comment]
你把你的项目打包上传一下，删除node_modules，我们看看，谢谢。

**Comment by callmez** [comment]
这里重新注明下, 

egg-ts之前 config.default.ts中有BizConfig设定的时候会有问题.后来去掉BizConfig设定的版本中不会有这个问题了...

文档中没有说明  去掉BizConfig之后 config的设置 如何申明?

**Comment by Maledong** [comment]
你要不先上传一下项目，我得看看然后设法修复。

**Comment by Maledong** [comment]
```js
import {EggAppConfig,Context} from 'egg';

declare module 'egg' {
    export interface EggAppConfig {
     //……
   }
}

export default function robotMiddleware(options: EggAppConfig, app:Application): any {
  return async (ctx: Context, next: () => Promise<any>) => {
    await next();
  };
}
```

**Comment by Maledong** [comment]
@callmez ：谢谢你，我这里注明了。准备把文档写清楚。

**Comment by Maledong** [comment]
请问问题解决了吗？

**Comment by callmez** [comment]
我最后不是回复了么,新的版本里 不会有这个问题.. 因为egg-ts调整了declaration-merging写法

**Comment by atian25** [comment]
所以这个 issue 可以 close 了？

**Comment by callmez** [comment]
可以的
