### ISSUE TITLE
希望添加sequelize中间件，可以使得查询tree结构更容易

### ISSUE THREAD

**Issue by z5614036** [eggjs/egg#3038]
本人利用此插件sequelize-hierarchy，在app.js中
const Hierarchy = require('sequelize-hierarchy');
    app.beforeStart(async () => {
            Hierarchy(app.Sequelize)
        });
在model 中定义模型
   const Folder = app.model.define('folder', {
        folder_id: {
            type:UUID,
            primaryKey: true,
            defaultValue: app.Sequelize.UUIDV1
        },
        name:STRING
    },{
        hierarchy: true
    });
结果 用不了插件的树结构，请问如何为egg-sequelize 添加sequelize-hierarchy

**Comment by okoala** [comment]
你可以 sequelize 配置中 config.Sequelize 传入 Hierarchy(Sequelize) 看看，例如：
```javascript
const Sequelize = require('sequelize');

exports.sequelize = {
  dialect: 'mysql',
  database: '',
  host: 'localhost',
  port: 3306,
  username: 'root',
  password: '',

  // support customize your own Squelize
  Sequelize: require('sequelize-hierarchy')(Sequelize),
};
```

**Comment by okoala** [comment]
有问题再 reopen 吧
