### ISSUE TITLE
定时任务schedule在多个docker如何限制？ 

### ISSUE THREAD

**Issue by jakehu** [eggjs/egg#3040]
经测试发现，如果部署多个容器，定时任务就会多次执行；有何解？

**Comment by Runrioter** [comment]
把 job 和项目本身拆开 单独部署即可

当然如果觉得没必要也可以通过环境变量来控制（水平扩展时主要注意环境变量）

**Comment by jakehu** [comment]
@Runrioter  job 分开这个我懂起了的，不过通过环境变量没懂起，因为一个应用多个容器，环境变量也用的是一套啊

**Comment by Runrioter** [comment]
容器镜像是一个 但是运行的环境变量可以不一样的

比如你用k8s做调度，根据环境变量 在k8s的管理下 既可以运行dev的一套 也可以运行prod一套

环境变量的本质其实还是分两套

**Comment by olivewind** [comment]
1. 如果是直接部署容器的话，建议将 job 单独拉出来
2. 如果使用 k8s 来管理容器集群的话，建议使用 k8s 的 CronJob 功能

**Comment by Runrioter** [comment]
我说的水平扩展 是指无状态的服务 非job
job原则上就只有一个 无法多实例

**Comment by jakehu** [comment]
@Runrioter @olivewind 感谢，准备job单独一个容器部署，目前用的是swarm

**Comment by atian25** [comment]
必须通过第三方的消息机制来控制，单纯把 worker 作为消费者，注册上去。

https://github.com/eggjs/egg-schedule#schedule-type

自定义一个 Strategy，收到消息的 worker 才处理。
