### ISSUE TITLE
http://alinode.aliyun.com/dist/new-alinode/v3.12.0/alinode-v3.12.0-darwin-x64.tar.gz 404

### ISSUE THREAD

**Issue by LWH2017** [eggjs/egg#3041]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by hyj1991** [comment]
你直接浏览器打开你发的 url 都能正常下载- -

**Comment by hyj1991** [comment]
看看是不是网络问题呢
