### ISSUE TITLE
生产环境下的日志

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#3042]
在测试环境下调试的log怎么即时输出到控制台？由于dev的环境无法测试某些代码，所以测试环境是用egg-scripts start --daemon启动的，业务代码上无论是console.log还是ctx.logger.info等等都无法即时打印到控制台，要等到一天过后生成的日志才能看到，尽管切割成小时还是要等，这样调试的效率太低了。有什么方法可以把代码上的log即时在生产环境上打印出来？或者有什么方法可以即时生成当天到目前的日志

**Comment by atian25** [comment]
- 日志是实时写入文件的，你再检查下。
- 默认线上是关闭 info 级别的，看下 logger 文档

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
