### ISSUE TITLE
请求把egg-graphql的最新版本发布到npm

### ISSUE THREAD

**Issue by nigelvon** [eggjs/egg#3045]
想用apollo-server2，看到项目里已经升级了，但是没有发布到npm库里。
如果已经准备好能否发布到npm

**Comment by jtyjty99999** [comment]
sorry 当时发失败了，没看到 

+ egg-graphql@2.2.0

**Comment by nigelvon** [comment]
这个项目没有issue，能否请求加入GraphQL Playground呢。可选项也行。

**Comment by atian25** [comment]
我们 issue 是统一在这个仓库

**Comment by nigelvon** [comment]
> 我们 issue 是统一在这个仓库

是的主要是后半句，能否在egg-graphql中加入GraphQL Playground的支持

**Comment by atian25** [comment]
我对 GraphQL 不熟，可以直接提 PR 给其他同学看看
