### ISSUE TITLE
workers pend each other

### ISSUE THREAD

**Issue by JackGit** [eggjs/egg#3046]
* **Node Version**: 8.11.4
* **Egg Version**: 2.10.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows 10 x64
* **Mini Showcase Repository**:

It's about handle CPU intensive task in egg, the minimized code would like:

```js
const cluster = require('cluster')
const asyncBusy = async () => {
  return new Promise(resolve => {
    setTimeout(() => {
      const s = Date.now()
      let loop = true
      while (loop) {
        if (Date.now() - s > 1000 * 10) {
          loop = false
        }
      }
      resolve()
    })
  })
}

class MyController extends Controller {
  // GET /busy
  async busyTask () {
    await asyncBusy() // busy for 10s
    this.ctx.body = `busy done by ${cluster.worker.id}`
  }
}
```

And I am running egg server in prod, which starts 8 workers in my machine.
When I fired two request `/busy` at the same time, the 1st request responded with `busy done by 1` in 10s, and the 2nd one responded with `busy done by 2` in about 20s, which means the 2nd one was pended by the 1st request.

But these two requests were handled by two workers, why they would pend each other?

**Comment by atian25** [comment]
1. make sure you really start multi workers
2. how to share cpu to process is depend to the OS, not us.

**Comment by JackGit** [comment]
Response content already concat the `cluster.worker.id`, and these two responses returns different ids, is this not enough to proof that I really started multi workers? 

And I tested in linux as well, it shows the same result with RoundRobin policy.

**Comment by hyj1991** [comment]
you can try sending request by nodejs instead of browser like this:

```js
'use strict';

const http = require('http');

function request(key) {
  console.time(key);
  const req = http.request({
    host: '127.0.0.1',
    port: 7000,
    path: '/busy'
  }, res => {
    res.on('data', chunk => console.log(key, chunk.toString()));
    res.on('end', () => {
      console.timeEnd(key);
    })
  });

  req.on('error', err => console.error(err));
  req.end();
}

request('first');
request('second');
```

**Comment by hyj1991** [comment]
Actually, in browser the waterfall of the second request which cost 20s maybe like this:

![image](https://user-images.githubusercontent.com/19908330/46135017-d2996d80-c276-11e8-90aa-61a095d6b3e3.png)

> Time the request spent waiting before it could be sent. This time is inclusive of any time spent in proxy negotiation.Additionally, this time will include when the browser is waiting for an already established connection to become available for re-use, obeying Chrome’s maximum six TCP connection per origin rule.

**Comment by atian25** [comment]
try `curl`

**Comment by hyj1991** [comment]
http://fex.baidu.com/blog/2015/01/chrome-stalled-problem-resolving-process/

**Comment by JackGit** [comment]
Got it, it's not an egg issue nor a node issue, and workers do work independently, thanks.
