### ISSUE TITLE
[TS] 为 helper 增加提醒

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#3048]
- [x] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的 ts 模板中，在 `extend/helper.ts` 中导出的函数，在 controller 中 `this.ctx.helper` 不会有代码提醒。
如：
`extend/helper.ts`
![image](https://user-images.githubusercontent.com/7995232/46133145-66b50600-c272-11e8-9d33-f4ea73ca7fe8.png)
`controller/index.ts`
![image](https://user-images.githubusercontent.com/7995232/46134075-9bc25800-c274-11e8-9628-4d4e4759f316.png)

### What does the proposed API look like?
None

**Comment by whxaxes** [comment]
这个需要声明合并才可以加载进去，为此我们提供了一个声明自动生成合并工具，详情看文档：https://eggjs.app/zh-cn/tutorials/typescript.html#egg-ts-helper
