### ISSUE TITLE
提供 close 注册

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#305]
## 背景

一个应用做到优雅退出，每个插件应该自己来负责关闭本插件的生成的，比如创建的连接、占用的端口都需要关闭。

尤其在测试用例中，应用会启动多次，如果出现占用就会报错。

## 方法

提供 `app.beforeClose(fn)` 注册关闭的任务，当调用 app.close 时会等待关闭所有的任务。

**Comment by atian25** [comment]
app.beforeStart, app.onClose, app.on('ready')

感觉都是不同生命周期的 hook，但命名方式不统一。

**Comment by popomore** [comment]
app.on('ready') 这个是啥？

要不改成 beforeClose?

**Comment by atian25** [comment]
- 不是有个 egg-ready 么。
- beforeClose +1

**Comment by popomore** [comment]
egg-ready 是 messenger 的

**Comment by popomore** [comment]
改成 beforeClose 吧，避免和消息混了
