### ISSUE TITLE
为什么postman发送的请求x-csrf-token可以被解析，axios发送的请求返回missing csrf token？

### ISSUE THREAD

**Issue by assmdx** [eggjs/egg#3050]
![qq 20180927190217](https://user-images.githubusercontent.com/19722693/46141919-e7cac800-c287-11e8-93db-0de3615576b3.png)
![qq 20180927190220](https://user-images.githubusercontent.com/19722693/46141920-e7cac800-c287-11e8-99aa-409e03445519.png)

**Comment by atian25** [comment]
自己检查下 devtools network

**Comment by assmdx** [comment]
@atian25  我在atom中运行也不行，
![image](https://user-images.githubusercontent.com/19722693/46159605-45c0d500-c2b3-11e8-8903-7e2d0338d597.png)

**Comment by popomore** [comment]
因为你 cookie 里没有

**Comment by assmdx** [comment]
cookie不是保存在本地么，server应该是解析header中的x-csrf-token吧，我发的请求里已经加了x-csrf-token了，但是为什么提示missing csrf token呢？

**Comment by assmdx** [comment]
@popomore  cookie不是保存在本地么，server应该是解析header中的x-csrf-token吧，我发的请求里已经加了x-csrf-token了，但是为什么提示missing csrf token呢？

**Comment by Runrioter** [comment]
* `axios`  无法获取你的cookie的 除非你显示的设置到header里
* `x-csrf-token`的校验是基于那个cookie的

**Comment by assmdx** [comment]
@Runrioter 是的，我先用Postman拿到x-csrf-token，然后用这个x-csrf-token在axios代码中测试，结果跟上图一样，missing csrf token

**Comment by assmdx** [comment]
@Runrioter 我这么做按说server应该可以解析的，为什么报missing csrf token呢

**Comment by Runrioter** [comment]
@assmdx  已经解释的很清楚了 
postman发送请求的时候携带的header不仅仅是你设置的那些 你点开底部的那个`headers(5)`看一下 把缺的(尤其是Cookie Header)补到`axios`里 再试试

**Comment by assmdx** [comment]
@Runrioter  谢谢，你解决了我的问题~

**Comment by assmdx** [comment]
axios发请求只设置x-csrf-token是不可以的，还需要设置cookie
```
let options = {
    url:'http://localhost:7001/mail/login',
    method:'POST',
    headers:{
        'Content-type': 'application/json',
        'x-csrf-token':'glorCqj9pLmEijRrlKtRG_Qp',
        'Cookie':'csrfToken=glorCqj9pLmEijRrlKtRG_Qp; EGG_SESS=wzGXljZxTuJQvmQRK_97jRKsidpJ_P1r4ki4OF33djhFyb7TxOeKQKMfzzM9cxaSxTMicNxpV0wOVlcMwRYXKjSsqvH4nc-3Bd0RW5qUU7m0R2irmxGfQT0Y_QS6NkjeigcuV6YPtNOBZtLz-go-ug=='
    },
    data:JSON.stringify({
        "username":"admin",
        "password":"123"
    })
}
axios(options)
    .then((data)=>{
        console.log(data);
    })
    .catch((err)=>{
        console.log(err)
    })
```

**Comment by jpgaus** [comment]
> axios发请求只设置x-csrf-token是不可以的，还需要设置cookie
> 
> ```
> let options = {
>     url:'http://localhost:7001/mail/login',
>     method:'POST',
>     headers:{
>         'Content-type': 'application/json',
>         'x-csrf-token':'glorCqj9pLmEijRrlKtRG_Qp',
>         'Cookie':'csrfToken=glorCqj9pLmEijRrlKtRG_Qp; EGG_SESS=wzGXljZxTuJQvmQRK_97jRKsidpJ_P1r4ki4OF33djhFyb7TxOeKQKMfzzM9cxaSxTMicNxpV0wOVlcMwRYXKjSsqvH4nc-3Bd0RW5qUU7m0R2irmxGfQT0Y_QS6NkjeigcuV6YPtNOBZtLz-go-ug=='
>     },
>     data:JSON.stringify({
>         "username":"admin",
>         "password":"123"
>     })
> }
> axios(options)
>     .then((data)=>{
>         console.log(data);
>     })
>     .catch((err)=>{
>         console.log(err)
>     })
> ```

多谢，帮我个大忙!
关于x-csrf-token，官方文档可以再补充一下细节，需要同时上传x-csrf-token + cookie，这点对于api，尤其是小程序这类不带cookie的应用很有帮助

**Comment by atian25** [comment]
可以考虑

```js
axios.defaults.headers.common['x-csrf-token'] = Cookies.get('csrfToken');
axios.defaults.headers.post['Content-Type'] = 'application/json';
``

cookie 应该不需要手动带上。
