### ISSUE TITLE
如何忽略rest resources 定义出来的url中的content type后缀？

### ISSUE THREAD

**Issue by jetspeed** [eggjs/egg#3053]
比如 GET /posts/1.json
我发现params.id 得到的是 1.json， 而不是1

如何忽略这个.json？

**Comment by killagu** [comment]
`router.get('/:foo(.+).json', controller.foo.bar);`

https://github.com/pillarjs/path-to-regexp#custom-matching-parameters

**Comment by jetspeed** [comment]
egg中rest resources定义出来的url

    router.resources('posts', '/posts', controller.posts);

没机会写正则啊。。

**Comment by killagu** [comment]
`router.resources('posts', '/posts/:index(.+).json', controller.posts)`

**Comment by jetspeed** [comment]
thx. @killagu
好像不好使，
 router.resources定义出来的 index show create update 等方法各自对应的url，都可能有.json 也可能没有， 我希望都能统一支持。
