### ISSUE TITLE
egg-socket.io插件功能缺失

### ISSUE THREAD

**Issue by cainiaokan** [eggjs/egg#3055]
socket.io在attch的时候是可以设置path参数的。默认是path是/socket.io，但由于egg-socket.io的二次封装，但却没有提供应用响应设置的地方，导致没有机会指定socket.io在attch的时候设置path的能力了。

**Comment by ngot** [comment]
PR is welcome.

**Comment by ngot** [comment]
attach 支持的参数，全部都可以在 `init` 里面设置, e.g:

```js
// {app_root} / config / config. $ {env} .js
exports.io = {
  init: {
    path: '/xyz'
  }, // passed to engine.io
};
```

参考： https://eggjs.org/en/tutorials/socketio.html#configuration

**Comment by SongLin123** [comment]
建议在文档里写明，以免新手踩坑
