### ISSUE TITLE
官网文档提供页内导航(目录) 

### ISSUE THREAD

**Issue by MartinsYong** [eggjs/egg#3061]
## Provide in-page index(catalog) at official website documentation

**issue:**

Considering that some documents are too long, like [controller](https://eggjs.org/en/basics/controller.html), we should provide in-page index(catalog) to improve reading experience.

有些文档太长（如[controller](https://eggjs.org/en/basics/controller.html)），建议提供页内导航提高阅读体验。

**example:**

[antd documentation](https://ant.design/docs/react/introduce) right side of the page(available when vision width greater than 768px)

[antd文档](https://ant.design/docs/react/introduce)右侧目录（视宽大于768px情况下）

**Comment by ahuigo** [comment]
@killagu 我打算提交个这个TOC PR, 不过我在contribute 介绍里面并没有找到关于文档的事宜。
1. 然后我去 egg/docs/_config.yml 里面我看了下是hexo `theme:egg` 生成的.
2. 应该是修改 egg-theme 就可以支持TOC了吧. 
不过我没有找到egg-theme 这个repository. 盼回

**Comment by atian25** [comment]
https://github.com/eggjs/doctools
