### ISSUE TITLE
根据插件开关自动生产一个 package.json 配置将框架中的 dependencies 精简

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#3062]
随着 ServerLess 的流行，我们需要考虑将 egg 应用通过 Function 模式来部署。而 Function 通常要求代码包很小，如阿里云的 FC [不允许超过 50MB](https://help.aliyun.com/document_detail/51907.html?spm=a2c4g.11186623.6.658.1c786d77tnaEQe)

而 egg 的框架继承模式，注定 dependencies 中会安装上很多应用真实用不上的模块。如果不想办法精简，那么 egg 将无法适应 ServerLess 的世界。

**Comment by fengmk2** [comment]
忘记将 node 删除，删除后 cnpmjs.org 的源代码看起来还好，目前在 25 MB 内。

**Comment by fengmk2** [comment]
先忽略，还有一半包大小可以随便玩。

**Comment by yuantongkang** [comment]
使用webpack打包 生存一个index.js 这样就不用担心大小了
