### ISSUE TITLE
希望能给egg-graphql增加schemaDirectives的支持

### ISSUE THREAD

**Issue by nigelvon** [eggjs/egg#3063]
Apollo Server 有个非常强大实用的schemaDirectives实现，非常适合用来实现权限验证等业务。
https://www.apollographql.com/docs/graphql-tools/schema-directives.html

看了下egg-graphql的代码，在调用makeExecutableSchema并没有传入schemaDirectives对象。
请求更新支持。

**Comment by Maledong** [comment]
This is landed at：https://github.com/eggjs/egg-graphql/pull/19.
Thanks for your suggestions!
