### ISSUE TITLE
Question about Socket.io

### ISSUE THREAD

**Issue by mhdizade** [eggjs/egg#3069]
* **Node Version**: v8.11.1
* **Egg Version**: 2.6.1
* **Plugin Name**: egg-socket.io
* **Plugin Version**: 4.1.4
* **Platform**: windows
* **Mini Showcase Repository**: --

is there any way to emit a socket event to clients after http request?
i want to send `socket event` to my clients after a `rest` request. how can i do that?
i try to use `ctx.socket.emit` in my rest controller but it is not working.

This is my router code:
``` 
export default (app) => {
  const { controller, router, io } = app;
  router.get('/', controller.home.index);

 io.route('chat', io.controller.default.index);
 app.io.of('/chat').route('chat', io.controller.default.index);
};
```
This is my  `controller.home.index`, i want to send socket event from here, but it is not working:
```
import {Controller} from 'egg';

export default class HomeController extends Controller {
  public async index() {
    const {ctx} = this;
    const result = await ctx.socket.emit('res', 'message from http');
    ctx.body = {result};
  }
}
```

`ctx.socket.emit` from `io.controller.default.index` is fine, i want to use it from `controller.home.index`. is that possible?

**Comment by dead-horse** [comment]
you should find a way to find which clients you want to send. it's more an architecture problem.

**Comment by whlsxl** [comment]
I have the same question, maybe because just don't familiar with eggjs. 
Finally I figure it out, use `app.io.of('/').to("room").emit('res', "ttttt");`
Just in case of anyone have the same question.
