### ISSUE TITLE
egg的日志有没有很方便的查看工具

### ISSUE THREAD

**Issue by gzhappysky** [eggjs/egg#307]
现有日志排查不方便，是否有必要增加一个日志查看工具，如用网页实现chainsaw

要求: 
1. 日志查看友好，很清晰的显示日志内容，不要密密麻麻，让用户难以查看
2. 可以快速根据关键字查找，如根据关键字进行查找
3. 日志分类查看，如不同级别的日志
5. 可以把多台机器或多个进程的日志在一个地方查看，最好也可以分进程来查看，如egg是有多个worker进程

**Comment by atian25** [comment]
egg 的 logger 支持自定义 transport 

https://eggjs.org/zh-cn/core/logger.html

可以写一个对应的插件来收集日志并上报。

而分析查看这块，并不属于 egg 的范畴，可以用很多现有的系统，如 logstash 等等之类的。

**Comment by dead-horse** [comment]
@gzhappysky 使用 `grep` 命令，可以实现你想要的关键字查找、分类查看、分进程查看等各种需求。集群的日志采集上报、分析和报警可以通过 logger 的 transport 功能上报到类似 [sentry](https://sentry.io/welcome/) 之类的平台。
