### ISSUE TITLE
为啥上层无法把配置项传递给下层。

### ISSUE THREAD

**Issue by MiYogurt** [eggjs/egg#3070]
比如我要添加注入 coffee，就无法修改 file_loader 的 match 配置项，在 start-cluster 层面根本就没有传递参数到 egg-core。这样就无法通过 egg-dev 启动。

而且我通过这样方式启动，ts 无法载入 typeings 里面的东西，直接报错。参数我都是看 egg-bin debug 的，没啥改变，为啥就无法载入呢。

```
EGG_SERVER_ENV=local NODE_ENV=local EGG_TYPESCRIPT=true node www.js
```

```
const Egg = require('egg');
const path = require('path');

Egg.startCluster({
  baseDir: path.resolve(__dirname),
  typescript: true,
  workers: 1,
  require: ['ts-node/register', 'egg-ts-helper/register']
});
```

底层的配置项是否可以通过一个 json 环境变量进行注入会更好呢？

**Comment by MiYogurt** [comment]
coffeescript register 注入。

**Comment by whxaxes** [comment]
@MiYogurt  

目前是不支持通过 json 的环境变量注入的，如果要实现你的想法更改 Loader 的 match ，可以在上层封装框架中自定义 Loader 。

如何实现可以看官方文档：https://eggjs.org/zh-cn/advanced/framework.html#%E8%87%AA%E5%AE%9A%E4%B9%89-loader 

在自定义 Loader 中重载 `loadToApp` 以及 `loadToContext` 方法，更改 match 的入参。

```js
const AppWorkerLoader = require('egg').AppWorkerLoader;

class YourAppWorkerLoader extends AppWorkerLoader {
  loadToApp(directory, property, opt) {
     opt.match = '**/*.coffee';
     super.loadToApp(directory, property, opt)
  }

  loadToContext(directory, property, opt) {
     opt.match = '**/*.coffee';
     super.loadToContext(directory, property, opt)
  }
}
```

AgentWorkerLoader 也一样

**Comment by whxaxes** [comment]
> 而且我通过这样方式启动，ts 无法载入 typeings 里面的东西，直接报错。参数我都是看 egg-bin debug 的，没啥改变，为啥就无法载入呢。

这是因为 ts-node 7.0 默认不会去读 tsconfig 里的 files、includes、exludes  （ https://github.com/TypeStrong/ts-node#help-my-types-are-missing ），所以就不会自动去加载 typings 里的声明了。egg-bin 启动的话，是加了 `TS_NODE_FILES` 这个环境变量强制开启的。

建议用 egg-bin 来启动，因为 ts-node 下还会有一些 sourcemap 的映射问题或者其他问题，这些问题我们都在 egg-bin 中帮你们摆平了。如果你自己通过 node 来启动就得重新做很多 egg-bin 中做过的事了
