### ISSUE TITLE
关于egg-oss 的STS 无法使用

### ISSUE THREAD

**Issue by bulolo** [eggjs/egg#3071]
不知是版本问题还是egg-oss无法支持STS，但是看文档是有支持的。

```
async assume_role() {
  const {
    ctx,
    service,
    app
  } = this;

  const {
    roleArn,
    tokenExpireTime
  } = app.config.oss
  let policy = {
    "Statement": [{
      "Action": [
        "oss:*"
      ],
      "Effect": "Allow",
      "Resource": ["acs:oss:*:*:*"]
    }],
    "Version": "1"
  }

  const token = await app.oss.assumeRole(roleArn, policy, tokenExpireTime, 'appointment')
  console.log('token', token)

  //最后只输出:  token:{}
}
```

也参照了例子 https://help.aliyun.com/document_detail/32077.html
通知看了最近ali-oss的example:https://github.com/ali-sdk/ali-oss/blob/master/example/server/app.js

是否现在应该使用ali-oss, 而无法使用egg-oss,看了issue相似的sts授权方式均无法得到解答

**Comment by popomore** [comment]
你是什么版本

**Comment by bulolo** [comment]
@popomore 最新 egg-oss  1.10

**Comment by bulolo** [comment]
@popomore 最后无奈，把egg-oss，更换为 ali-oss，没问题了。感觉 现版本的egg-oss sts有问题

**Comment by bulolo** [comment]
@popomore  配了，ali-oss 正常跑了 sts模式。  egg-oss没办法跑

**Comment by popomore** [comment]
能否给个你代码的例子，我验证下看看，插件也是有测试的

https://github.com/eggjs/egg-oss/blob/master/test/fixtures/apps/oss-sts/app/router.js#L21

**Comment by popomore** [comment]
我知道了，4.x 的 sts 没有 wrapper，所以是 generator function。

**Comment by popomore** [comment]
已经发布了新版本

**Comment by atian25** [comment]
升级到 egg-oss 大版本，重新安装依赖看看

**Comment by bulolo** [comment]
感谢，使用正常，但遇到新的问题
https://github.com/eggjs/egg/issues/3184
