### ISSUE TITLE
why the async methods in my registryClient are pending forever?[Multi-Process Development Model]

### ISSUE THREAD

**Issue by wanghsinche** [eggjs/egg#3072]
* **Node Version**:  v8.9.4
* **Egg Version**:    "^2.2.1",
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows 10
* **Mini Showcase Repository**:

Hi, When I built my app with [this example](https://eggjs.org/en/advanced/cluster-client.html), I found the console always warns "[egg:core:ready_timeout] 10 seconds later". And I can't make my app works with the example.

It seems that the app is hanging up when it executes to `await agent.registryClient.ready()`.
```javascript
agent.beforeStart(async () => {
    await agent.registryClient.ready();  // here
    agent.coreLogger.info('registry client is ready');
  });
```
I used the following code to print the Promise object and found it is pending forever.
```javascript
agent.beforeStart(async () => {
  	console.log(123)
    const p = agent.registryClient.ready()
    console.dir(p)
    await delay(1000)
    console.dir(p)
  });
```
```console
123
Promise { <pending> }

Promise { <pending> } --- 1s later
```
But the ready method in my base class resolves immediately. 
```javascript
	async ready(state){
		return 'ok'
	}
```
So why those promises are pending forever? I'm really confused.

**Comment by okoala** [comment]
async function return a promise object

**Comment by wanghsinche** [comment]
oh, I found out the reason. The `const Base = require('base-sdk');` is a specific node module(https://github.com/node-modules/sdk-base), not an abstract module.  When I required the right module, it worked.
