### ISSUE TITLE
 Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by chuchur** [eggjs/egg#3079]
使用的是最新版本一直报错
![image](https://user-images.githubusercontent.com/4814173/46657205-57bf4380-cbe2-11e8-9a1d-e4a792c4cf45.png)
什么原因zao c造成的呢。

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

如果还有问题，用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧
