### ISSUE TITLE
egg-mongoose提示 To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

### ISSUE THREAD

**Issue by nodeper** [eggjs/egg#3081]
egg-mongoose提示下面错误。

(node:14220) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.

最新的mongodb4.x要求连接数据库的时候加上  { useNewUrlParser: true }

**Comment by treemore** [comment]
you can add the config by yourself
```js
{
client:{
 options: {
                useNewUrlParser: true,
            },
url:"xxx"
}
}
```

**Comment by atian25** [comment]
@treemore 可以 PR 做为默认值

**Comment by zdingfeng** [comment]
我也遇到了  可以用 谢谢

**Comment by Maledong** [comment]
@atian25：原来打算直接在config.default.js中加入此属性。后来加了发现测试中仍然会报此警告。所以在lib内加了，等同于config.default.js的效果，请审阅！

**Comment by Maledong** [comment]
Already loaded at: https://github.com/eggjs/egg-mongoose/pull/29/commits/54ca687febb8a24486ed97175bb2427c5825f983
