### ISSUE TITLE
单元测试环境下本地日志被覆盖重写

### ISSUE THREAD

**Issue by wpchou** [eggjs/egg#3083]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

开发环境下，日志能够不断 append，重启服务并不会覆盖原日志。但一跑单元测试，旧的日志数据就没了。有办法保留吗？

**Comment by atian25** [comment]
单元测试为什么要保留日志？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mock/blob/master/lib/app.js#L167

配置下 `options.clean`
