### ISSUE TITLE
ts 下无法使用 egg-jwt。报「类型“Application”上不存在属性“jwt”」

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#3089]
* **Node Version**: 8.11.4
* **Egg Version**: 2.10.0
* **Plugin Name**: egg-jwt
* **Plugin Version**: 3.12
* **Platform**: macos
* **Mini Showcase Repository**: https://github.com/JZLeung/egg-jwt-issue-demo

如图所示：
![](https://ws2.sinaimg.cn/large/006tNbRwgy1fw5h1xn72bj30yq0aqmys.jpg)

**Comment by atian25** [comment]
通知下对应的作者补下插件的 d.ts 吧

cc @okoala

**Comment by JZLeung** [comment]
@atian25 具体在哪里写？

**Comment by JZLeung** [comment]
临时解决方案：
在 `typings/index.d.ts` 中加入：
```js
declare module 'egg' {
    interface Application {
        jwt: {
            sign(payload: any, secret: string, options?:any, callback?:function): string;
            verify(token: any, secret: string, options?:any, callback?:function): string;
        }
    }
}
```

**Comment by atian25** [comment]
@JZLeung 直接 PR 给对方的插件吧。

**Comment by JZLeung** [comment]
临时解决：
`typings/index.d.ts`:
```js
interface Application {
        jwt: {
            sign(payload: any, secret: string, options?:any, callback?:function): string;
            verify(token: any, secret: string, options?:any, callback?:function): string;
        }
}
```

after:

![](https://ws1.sinaimg.cn/large/006tNbRwgy1fw5hirfvryj3104058jsf.jpg)

**Comment by JZLeung** [comment]
@atian25 好。

**Comment by JZLeung** [comment]
related PR: https://github.com/eggjs/egg/issues/3089
