### ISSUE TITLE
修复不稳定测试

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#309]
现在 travis 会定时跑，确保 master 的测试能稳定跑过 https://travis-ci.org/eggjs/

- [x] egg-dingtalk @atian25 
- [x] egg-schedule @popomore
- [x] egg-tracer @popomore
- [x] egg-host @ngot 
- [x] egg-logrotator @popomore
- [x] egg-alinode @popomore
- [x] egg-oss @popomore
- [x] egg-mysql @popomore
- [x] egg-multipart @popomore
- [x] egg-view-nunjucks @atian25 
- [ ] ~~egg-development~~

**Comment by popomore** [comment]
egg-development 是 travis ENOSPC 了

**Comment by popomore** [comment]
@ngot egg-host 你来升？

**Comment by atian25** [comment]
nunjucks 的那个 PR 合并了就 OK 了吧？ review 下

**Comment by popomore** [comment]
@atian25 合了

**Comment by popomore** [comment]
oss 的 key 没了，ci 是过不了了

**Comment by fengmk2** [comment]
oss那个我今天修复一下，找人要个新key
