### ISSUE TITLE
写了下面的中间件包装返回结果，postman测试返回结果为空？？

### ISSUE THREAD

**Issue by JarvisQJ** [eggjs/egg#3097]
````
module.exports = (option, app) => {
  // 中间件的配置项，框架会将 app.config[${middlewareName}] 传递进来
  return async function (ctx, next) {
    try {
      console.log('22222')
      await next();
      ctx.body = null;//这里直接赋值用于模拟controller返回数据为null的情况
      console.log('11111', ctx.body);
      ctx.body = Object.assign({code: 1, message: '执行成功'}, {data: ctx.body || null});
      console.log('4444', ctx.body);
    } catch (err) {
      // 所有的异常都在 app 上触发一个 error 事件，框架会记录一条错误日志
      app.emit('error', err, this);
      const status = err.status || 500;
      // 生产环境时 500 错误的详细错误内容不返回给客户端，因为可能包含敏感信息
      const error_msg = status === 500 && app.config.env === 'prod'
        ? 'Internal Server Error'
        : err.message;
      // 从 error 对象上读出各个属性，设置到响应中
      console.log('3333')
      ctx.body = {
        code: 0,
        message: error_msg
      };
      ctx.status = status;
    }
  };
};
````
ctx.body有值时postman可以正常接收到正常数据。
最小复现代码地址
https://github.com/JarvisQJ/egg-res-issue.git
@atian25 

补充：
这个中间件加了ctx.body = Object.assign({code: 1, message: '执行成功'}, {data: ctx.body || null});这个逻辑，用于包装返回结果。
正常情况下，postman测试会得到{code: 1, message: '执行成功',data: xxx}
现在当赋给ctx.body的值为null的情况下，希望得到{code: 1, message: '执行成功',data: null}；但结果是，没有得到任何数据。

**Comment by atian25** [comment]
有复现代码了，但还需要补充下 `问题描述`，从上文没太看明白现在遇到什么问题

**Comment by JarvisQJ** [comment]
@atian25 补充了，你看下

**Comment by JarvisQJ** [comment]
> 有复现代码了，但：
> 
> * 还需要补充下 `问题描述`，从上文没太看明白现在遇到什么问题
> * 代码有点多了，下次最好精简下，提炼最小可复现

和其他地方其实没多大关系，主要在这个中间件里面，console.log('4444', ctx.body);这一句控制台打印值为{code: 1, message: '执行成功',data: null}。但是不知道为什么，postman消息体里面没有数据。

**Comment by atian25** [comment]
在 middleware 里面加一个 `ctx.status = 200;` 试试

**Comment by atian25** [comment]
https://github.com/koajs/koa/blob/master/lib/application.js#L210

是 Koa 这段逻辑导致的，因为你前面是 null，所以被配置了 204 的状态码，所以需要你的中间件重置下。

**Comment by JarvisQJ** [comment]
解决了，非常感谢！
