### ISSUE TITLE
egg-ant-design-pro。执行build、dev、start都出错。。

### ISSUE THREAD

**Issue by lazyfish88** [eggjs/egg#3104]
执行npm run dev命令后，提示出下

![image](https://user-images.githubusercontent.com/3926898/47203135-dfab0780-d3b1-11e8-9da3-79537a5947bc.png)

run build
![image](https://user-images.githubusercontent.com/3926898/47203195-1719b400-d3b2-11e8-93f3-96a14a6b521d.png)

获取下来直接输入命令的。是有哪里没配置好？

**Comment by okoala** [comment]
怎么还 roadhog，pro 不是直接 umi 了吗~

**Comment by popomore** [comment]
这里没改呢

**Comment by okoala** [comment]
要不把 ant-deisgn-pro 单独抽出吧，直接用 lerna 前后端完全分离，这样就好维护了。不过这个仓库貌似是配合 egg-view-assets。

**Comment by popomore** [comment]
是啊，不然就不需要这个 example 了

**Comment by lazyfish88** [comment]
意思是这个直接不用了？做个新的？？我是比较想egg怎么跟pro配合。。如果直接pro开发好前端。。然后发布。。再放到egg里用。。我是懂。。我是想不用发布。。直接前后同时开发。。

**Comment by popomore** [comment]
用的，在升级到 umi

**Comment by lazyfish88** [comment]
> 用的，在升级到 umi

大概什么时候升级好哈。。能给个大概时间不

**Comment by popomore** [comment]
见 PR
