### ISSUE TITLE
pm2 提供了reload 功能，可以每个线程逐个启动，egg-srcipt 能否提供woker的逐个启动

### ISSUE THREAD

**Issue by WeiweiCootek** [eggjs/egg#3109]
0-seconds downtime reload
When you use restart, pm2 kills and restarts all the processes at the same time. There is a short period of time during which the service is unavailable.

With reload, pm2 restarts all processes one by one, always keeping at least one process running:

pm2 reload <app_name>

egg-script 是否可以提供类型的功能

**Comment by atian25** [comment]
单机热重启没啥意义

**Comment by atian25** [comment]
单机热重启没啥意义。一般是在 LBS 层搞。

或者你简单的场景可以看下 https://zhuanlan.zhihu.com/p/36439661
