### ISSUE TITLE
egg-view-assets对修改过的public路径不生效

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#3110]
## 先发几张关于**前因**截图

工程的静态资源的目录配置：
![image](https://user-images.githubusercontent.com/5373111/47282729-ef755680-d612-11e8-88e0-c7e2853b7d18.png)

umi发布路径配置：
![image](https://user-images.githubusercontent.com/5373111/47282798-2186b880-d613-11e8-8957-24168329bf67.png)

`npm run build`以后的public文件夹：
![image](https://user-images.githubusercontent.com/5373111/47282820-3b280000-d613-11e8-8ce8-4a699823ca16.png)

`egg-view-assets`的资源路径配置：
![image](https://user-images.githubusercontent.com/5373111/47282785-12a00600-d613-11e8-8f64-db446c3e66e9.png)

## 出现的问题是，服务跑起来页面没办法展示

正常显示应该是这样的：
![image](https://user-images.githubusercontent.com/5373111/47282957-bdb0bf80-d613-11e8-90c9-760d2771a07f.png)

现在是这样的：
![image](https://user-images.githubusercontent.com/5373111/47282927-9ce86a00-d613-11e8-91da-9967e43e221a.png)

但是通过路径访问，可以看到静态资源：
![image](https://user-images.githubusercontent.com/5373111/47282894-74f90680-d613-11e8-8298-9bfc5cd59765.png)

理论上解决这个问题，是在egg的config中配置 `config.assets.publicPath`进行调整的吧。我已经尝试过各种值，都不行：
1. /
2. /pages
3. /public/pages

ps：不好意思，用这样的方式描述问题。。 看不懂的话，我去整个demo...

**Comment by popomore** [comment]
能给个 demo 吗

**Comment by xjchenhao** [comment]
@popomore 谢谢回复，已上传demo，问题能够复现

https://github.com/xjchenhao/egg-issues-demo-3110

***

如前面的问题描述，开发环境下，直接运行`npm run dev`是没有问题的。

但是如果是线上环境，依次执行
1. npm run build
2. npm run start

展示出了**空白**页面，静态资源加载不出来。

**Comment by popomore** [comment]
好的，我看一下

**Comment by popomore** [comment]
提了 PR https://github.com/xjchenhao/egg-issues-demo-3110/pull/1/files

**Comment by xjchenhao** [comment]
@popomore 你好，PR这样的修改跟官网的是一样的，我也尝试过是ok的。

但是我这里有特殊需求。。。

![image](https://user-images.githubusercontent.com/5373111/47401649-c8cf3100-d774-11e8-999f-ddbdba2e903d.png)

`/app/public`中有个`deviceWhite`文件夹，这个存放了业务中需要的excel文件。

如果通过PR这样，简单粗暴的更新public文件夹，`/app/public/deviceWhite`也丢失了。
