### ISSUE TITLE
生产环境静态资源被缓存了？

### ISSUE THREAD

**Issue by jonathang4** [eggjs/egg#3112]
最近使用egg开发过程中发现切换成生产环境(npm start)运行之后，public目录下的静态资源好像是被缓存了。无论是js还是css文件，提交后刷新不到最新文件，必须重启一下egg服务才能获取到最新文件。想问一下是不是我的配置有问题？怎么才能取消这种缓存？或者修改缓存时间。
下面是我的配置文件代码:
config.default.js
`  config.security = {
    domainWhiteList: [ '.xxx.com' ],
    xframe: {
      enable: false,
    },
    csrf: {
        enable: false,
    },
  };
  config.multipart = {
    fileSize: '50mb',
    fileExtensions: [
      '.jpg',
      '.jpeg',
      '.png',
      '.bmp'
    ]
  };
  config.bodyParser = {
    jsonLimit: '10mb',
    formLimit: '10mb',
  };

  config.cors = {
    origin:"*",
    allowMethods:"GET",
  };`

plugin.js
`exports.mongoose = {
  enable: true,
  package: 'egg-mongoose',
};

exports.session = {
  key: 'EGG_SESS',
  maxAge: 24 * 3600 * 1000, // 1 天
  httpOnly: true,
  encrypt: true,
};

exports.cors = {
  enable: true,
  package: 'egg-cors',
};`

**Comment by atian25** [comment]
- 生产环境最好是放 CDN 或 缓存，这样性能才好
- 上传文件啥的，用 OSS，最好不要丢 public
- 配置在 https://github.com/eggjs/egg-static/blob/master/config/config.prod.js 要写在 prod 里面

**Comment by jonathang4** [comment]
谢谢~

**Comment by liangShengSen** [comment]
关键是设置了没用啊

**Comment by atian25** [comment]
配置要改 config.prod.js
