### ISSUE TITLE
如何在 CI 中为单元测试配置环境

### ISSUE THREAD

**Issue by kasora** [eggjs/egg#3114]
目前我们有两个环境。

一个环境是开发人员本地测试，直接运行 `npm run test`，会采用 `config.local` 作为配置，会连接开发人员本地的数据库。
另一个环境是 CI 中的构建环境，构建环境所使用的测试数据库不在 localhost，所以`npm run ci`会报错。

根据文档中的描述。我们将构建环境的数据库信息写入了 `config.dev`，在 CI 的脚本中将 `dev` 写入了` ./config/env`。随后在日志中我们看到了这样的报错 `dump config after load`。

请问我们有什么办法指定 `npm run ci` 的运行环境，或者如何自定义 `npm run ci` 所使用的数据库配置？

**Comment by popomore** [comment]
egg-bin test 应该是加载 config.unittest.js，CI 跑的是 egg-bin cov 也是这个文件，不知道你自己写的脚本是什么。

**Comment by kasora** [comment]
谢谢。

**Comment by kasora** [comment]
那有什么方法可以手动指定`egg-bin test`的运行环境么。因为本地开发还是希望使用localhost的。如果增加`config.unittest.js`的话本地就没法跑测试了。

**Comment by ngot** [comment]
`EGG_SERVER_ENV` is a good choice for your situation. https://eggjs.org/en/basics/env.html#configure-runtime-environment

You can add `config.test-local.js`, and run the test like `EGG_SERVER_ENV=test-local egg-bin test`

package.json
```json
{
  "scripts": {
    "test-local": "EGG_SERVER_ENV=test-local egg-bin test"
  }
}

```

**Comment by atian25** [comment]
你可以在 config.unittest.js 里面判断环境变量是否是 CI 环境，然后赋值即可
