### ISSUE TITLE
想请问一下，是否有考虑过后面加入装饰器路由

### ISSUE THREAD

**Issue by ruioslr** [eggjs/egg#3115]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
会的

**Comment by atian25** [comment]
装饰器路由你现在就可以使用，只要遵循 egg 的 TypeScript 文档，你就能自行实现了。
现在也有一些社区开源的 egg 装饰器路由轮子，直接使用即可。
