### ISSUE TITLE
demo 跑不起来

### ISSUE THREAD

**Issue by acccco** [eggjs/egg#3117]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

跟着文档写 DEMO ，快速入门里面用到了 https://hacker-news.firebaseio.com/v0/topstories.json 这个网址，但在天朝根本访问不了

建议换个 DEMO 。。。

不然快速入门里有一半的东西，只能靠大脑主动翻译代码成网页了。

**Comment by zdingfeng** [comment]
https://cnodejs.org/topic/5b8de66137b3005a0b0e6b3f   教程看看

**Comment by houmao** [comment]
手册给的这个serverUrl地址访问超时
![官网给的url](https://user-images.githubusercontent.com/20122487/63836579-65bdb480-c9ac-11e9-9d83-1d60c6761034.png)
然后我换了一个serverUrl
![image](https://user-images.githubusercontent.com/20122487/63836550-58082f00-c9ac-11e9-8426-7e9dd7a49dbc.png)
请求结果
![image](https://user-images.githubusercontent.com/20122487/63836802-d664d100-c9ac-11e9-81de-448d176b0f39.png)
我想知道改变serverUrl不能改变请求地址么，还是用的https://hacker-news.firebaseio.com/v0， 这什么情况？另外想吐槽https://eggjs.org/ 这个手册的指导还是有很多坑的。
