### ISSUE TITLE
egg-schedule 调度完成时，如 cron 结束时，打印一条日志.

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#312]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by jtyjty99999** [comment]
目前这个貌似是任务里自己写的

**Comment by atian25** [comment]
不是, 我指的是 cron 表达式, 没有下次计划时, 打印一条计划完成的日志.

https://github.com/eggjs/egg-schedule/blob/master/agent.js#L98

**Comment by popomore** [comment]
cron 应该不会没有下一次吧

**Comment by atian25** [comment]
确实
