### ISSUE TITLE
egg如何记录单次请求的数据？

### ISSUE THREAD

**Issue by yaphetszmn** [eggjs/egg#3122]
* **Node Version**: 8.10.0
* **Egg Version**: 2.11.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: MacOS
* **Mini Showcase Repository**:

我想要在记录单次请求的时候，记录这一次请求的一些数据存在日志中，需要类似如下的写法：

ctx.request.aaa = []

ctx.request.aaa.push({})

这个是做在  app/extend/request.ts里吗？ 求指导

**Comment by atian25** [comment]
写个 Middleware，然后随便找个地方存吧。

参考 https://github.com/eggjs/egg-instrument

**Comment by atian25** [comment]
对接？你是想统计单次请求还是对多个请求做统计？
