### ISSUE TITLE
egg-redis能否支持hash存储？

### ISSUE THREAD

**Issue by jpgaus** [eggjs/egg#3123]
1、redis.set存储字符串，能否支持set('key', {id:1, name:'ll' }这种样式？
2、示例代码有resis.expire(xxx)，但参考手册未发现该api，不知为何？
3、egg-redis安装之后，为什么redis不能跟随egg应用自动启动，还需要手工工启动？

**Comment by atian25** [comment]
- redis 支持就支持
- egg-redis 只是一个 redis 的 client，肯定是不能控制 redis 这个 server 的启动啦。。

**Comment by jpgaus** [comment]
谢谢回复 !
