### ISSUE TITLE
我想请问如果我的controller和路游不写在app/下我该如何在项目启动时正常的执行他们，并且可以使用类似app.controller.home的方法

### ISSUE THREAD

**Issue by JKJKJKQ** [eggjs/egg#3130]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
需要按照约定，最少先把文档看一遍吧
