### ISSUE TITLE
问题：请问如何设置 egg-logger 输出为 json 格式？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3132]
如题。 egg-logger 项目本身没有提问题的入口。可否给个简单示例，多谢了！

**Comment by popomore** [comment]
egg 上可以使用配置 `config.logger.outputJSON = true`，egg-logger 不知道你使用的哪个 logger。

**Comment by Jeff-Tian** [comment]
@popomore 谢谢！成功了，用的 [egg-logger](https://github.com/eggjs/egg-logger) 就是官方文档上说的那个 [egg-logger](https://github.com/eggjs/egg-logger):

![image](https://user-images.githubusercontent.com/3367820/47830145-99986f80-ddc5-11e8-8a23-8a287516f003.png)

**Comment by Jeff-Tian** [comment]
@popomore 另外，可以请教一下哪里可以得到更详细的文档吗？比如设置了 `config.logger.outputJSON = true` 之后，在 logs 文件夹下，每一个 log 文件都有一个同名的 .json.log 文件了，也就是一个 log 文件同时输出了两份，有办法可以只保留 json 格式的文件吗？

![image](https://user-images.githubusercontent.com/3367820/47831976-f13ad900-ddcd-11e8-8bf2-2b78844101c4.png)

**Comment by Gorden-Wang** [comment]
#1817

**Comment by Jeff-Tian** [comment]
@Gorden-Wang 谢谢！

**Comment by menkeydyvh** [comment]
@Jeff-Tian  你是怎么关闭掉这个多出来的另一份log文件 我也只想保留json.log文件

**Comment by atian25** [comment]
> 不会禁用 file。 file 是给人看的，json 是给特定的监控系统用的。

如果真想关闭，看 egg-logger 源码，通过 api 把对应的 file transport 的 level 改掉。

**Comment by menkeydyvh** [comment]
@atian25  有木有栗子  举一个，看源码处理比较不明显

**Comment by atian25** [comment]
没有，通过 logger 找到 transport，再设置它的 level

**Comment by Jeff-Tian** [comment]
> @Jeff-Tian 你是怎么关闭掉这个多出来的另一份log文件 我也只想保留json.log文件

@menkeydyvh 目前我并没有关闭掉原有 log 文件。我有空了试试 @atian25 说的方法。

## 我们为什么要关掉原有 log 文件？
- 节省磁盘空间（优先级不高）
- 因为对接了阿里云日志平台，阿里云日志平台读的是 json，展现得很易读了，所以不需要给人看的 raw 格式了。

**Comment by atian25** [comment]
还有种方法就是不用 `outputJSON`，直接修改 `formatter` 和 `contextFormatter` 把原来的 file 日志输出为 JSON 格式。

**Comment by yuanyazhen** [comment]
直接修改 formatter 和 contextFormatter ...
---------
这个怎么做？有例子吗？

**Comment by atian25** [comment]
看下 formatter 的用法呗。

**Comment by Jeff-Tian** [comment]
> ## 直接修改 formatter 和 contextFormatter ...
> 这个怎么做？有例子吗？

```js
config.logger = {
  formatter: meta => ({yourCustomizedField: 'here', ...meta}),
  contextFormatter: meta => ({yourCustomizedContextField: 'here', ...meta})
}
```

**Comment by Jeff-Tian** [comment]
> @Jeff-Tian 你是怎么关闭掉这个多出来的另一份log文件 我也只想保留json.log文件

可以类似这样子关掉：

```js
const shutup = 'dev/null'
config.logger = {
  appLogName: shutup,
  coreLogName: shutup,
  agentLogName: shutup,
  errorLogName: shutup
}
```
