### ISSUE TITLE
pm2 start server.js 生产环境 无限重启，开发模式都没问题

### ISSUE THREAD

**Issue by Jasonlin00** [eggjs/egg#3135]
* **Node Version**:8.9.3
* **Egg Version**:2.2.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

0|server   | 2018-10-30 13:48:48,474 WARN 3648 [egg:core:ready_timeout] 10 seconds later /www/server/egg-server/node_modules/egg-watcher/app.js:15:7 was still unable to finish.
就这么一个警告，望指导一下

**Comment by atian25** [comment]
某个插件初始化没完成，导致超时。
很大可能是数据库连接之类的。

还可以看下服务端 run 目录下 timing 数据

**Comment by Jasonlin00** [comment]
> 某个插件初始化没完成，导致超时。
> 很大可能是数据库连接之类的。
> 
> 还可以看下服务端 run 目录下 timing 数据

数据库连接成功的
出现这个 [ClusterClient] leader does not be active in 60000ms on port:45990。

我新建的egg项目在我的服务器也运行不起来

**Comment by atian25** [comment]
> leader does not be active in 60000ms on port:45990。

这句话一般是有某个进程占用 CPU 过高，导致 cluster 心跳无法发送。

你先用 `egg-init --type=simple` 初始化个最小可复现仓库，然后发服务器看看。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by tsloveme** [comment]
可能在配置文件传入了PORT环境变量，配置项需要这么写： config.cluster.listen.port: Number(process.env.PORT) || 7000

这是我遇到的问题
