### ISSUE TITLE
使用egg-proxy后，代理的接口不会进行csrf校验

### ISSUE THREAD

**Issue by shixiangting** [eggjs/egg#3138]
如：当前node服务接口为127.0.0.1:6001/data/userinfo ,当我把该接口通过proxy配置转发到java后端后。该接口就不会进行csrf校验。我定位的原因是egg-proxy的优先级高于csrf导致，先执行了egg-proxy后就直接结束了，但是即使我配置了egg-proxy中的ooptions.yieldNext为真也不会进行csrf校验失败返回。

**Comment by popomore** [comment]
这个不是官方插件

**Comment by atian25** [comment]
没有。

你可以调整下中间件的执行顺序
