### ISSUE TITLE
httpclient request timeout 大于 agent timeout 的时候需要以 request timeout 为准

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#3140]
bug 发现来自 https://github.com/eggjs/egg/issues/3137#issuecomment-434398691 的反馈讨论。

**Comment by popomore** [comment]
这个有点麻烦，keepalive 的 socket 是共享的吧，还回去还要设回来

**Comment by tong3jie** [comment]
httpclient现在还不支持Http2.0吧。

**Comment by chjiyun** [comment]
请问是哪个版本修复了啊，跟egg版本有关吗

**Comment by atian25** [comment]
看上面几个 PR 的 link，只要你不锁版本，重新安装下依赖就 OK 了。
