### ISSUE TITLE
Typescript 时 npm test 的 tslint 问题

### ISSUE THREAD

**Issue by kasora** [eggjs/egg#3141]
`egg-bin test -r egg-ts-helper/register` 命令似乎也会调用 `tslint` 进行代码格式检查。但是它似乎不像 `tslint --project . -c tslint.json` 命令一样使用主目录下的 `tslint.json`。
请问 `egg-bin test -r egg-ts-helper/register` 命令所使用的 `tslint` 配置在哪里？能否让其统一使用主目录下的 `tslint.json`?

**Comment by whxaxes** [comment]
`egg-bin test` 是不会调用 `tslint` 的 ，你是怎么觉得它有执行 tslint 的？

**Comment by kasora** [comment]
@whxaxes 因为我单独运行 `tslint` 的时候没有报错提示，然后运行 `egg-bin test` 的时候提示
`TSError: [egg-core] load file: /home/kasora/code/cf-funcassess/app/controller/problem.ts, error: ⨯ Unable to compile TypeScript:
app/controller/problem.ts(9,16): error TS1009: Trailing comma not allowed.`
因为 lint 开了 auto-fix。所以他会自动加上行尾逗号。
然后跑 `egg-bin test` 的时候就是个稳定报错。
`Trailing comma not allowed` 看起来像是个 lint 配置问题。。是我哪里理解不对吗。。？

**Comment by whxaxes** [comment]
@kasora  这个是 ts 类型检查 ...

**Comment by whxaxes** [comment]
错误不都写着了么，TSError
