### ISSUE TITLE
API汉化

### ISSUE THREAD

**Issue by baiej214** [eggjs/egg#3148]
各位阿里的大神，能不能把Egg的[API](https://eggjs.org/api/)也搞个中文版的出来？
不能让语言成为国内广大二三四线城市非主流程序员成长的壁垒啊，是不是？

**Comment by atian25** [comment]
暂无计划，其实也没啥 API 了，都是各个插件的扩展，看对应的 README 或 指南 就差不多了。
再进一步就是看插件底层包裹的社区模块的文档了。
