### ISSUE TITLE
使用vscode-egg进行调试报错

### ISSUE THREAD

**Issue by huangyanyang** [eggjs/egg#3149]
![image](https://user-images.githubusercontent.com/19208961/47844744-265f1f80-ddfe-11e8-9895-25963343afe4.png)

**Comment by atian25** [comment]
贴下 launch 的配置

**Comment by huangyanyang** [comment]
![image](https://user-images.githubusercontent.com/19208961/47845672-98d0ff00-de00-11e8-9f10-d72c13b89791.png)
 好像还是不行

**Comment by huangyanyang** [comment]
vscode-egg 生成了三个configuration,我删了下面两个，因为有一个egg test好像也是9229的端口。这样做对不对，还是要原来三个原封不动

**Comment by popomore** [comment]
应该不用加 --inspect-brk

**Comment by huangyanyang** [comment]
@popomore 不是说现在可以不用attach,json了吗

**Comment by huangyanyang** [comment]
![image](https://user-images.githubusercontent.com/19208961/47846304-590b1700-de02-11e8-97b6-f303d9b661bf.png)
 我把那个报错点取消然后再f5运行一次，就可以连上，不过好像没有像运行npm run dev那样跑sequelize那样啊
