### ISSUE TITLE
Feature request: Route Groups

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3150]
Route groups allow you to share route attributes, such as middleware or namespaces, across a large number of routes without needing to define those attributes on each individual route

See more details at https://laravel.com/docs/5.7/routing#route-groups

```php
Route::prefix('admin')->group(function () {
    Route::get('users', function () {
        // Matches The "/admin/users" URL
    });
});
```

**Comment by atian25** [comment]
try https://github.com/eggjs/egg-router-plus
