### ISSUE TITLE
application.HttpClient 声明的问题

### ISSUE THREAD

**Issue by kwoktung** [eggjs/egg#3151]
egg  index.d.ts 中 application.HttpClient 是继承urllib 的HttpClient2 来实现的 

https://github.com/eggjs/egg/blob/master/index.d.ts#L504

https://github.com/eggjs/egg/blob/master/index.d.ts#L30

但是 js源码中  application.HttpClient   确实应该是继承 urllib.HttpClient 来实现的, 而不是  urllib.HttpClient2

https://github.com/eggjs/egg/blob/master/lib/egg.js#L48

https://github.com/eggjs/egg/blob/master/lib/core/httpclient.js#L9

我想不明白为什么会有以上这样差异

**Comment by whxaxes** [comment]
因为`urllib` 里的声明中 `HttpClient2` 里的方法的返回类型才是 `Promise`
