### ISSUE TITLE
egg断点调试还是有问题

### ISSUE THREAD

**Issue by huangyanyang** [eggjs/egg#3155]
![image](https://user-images.githubusercontent.com/19208961/47900496-228fd380-deb8-11e8-9f95-6d9c4dd2cb30.png)
![image](https://user-images.githubusercontent.com/19208961/47900522-33404980-deb8-11e8-815d-8c27529284a0.png)
那个报错出来过几秒能连上但是egg的api、sequelize那些全部都没有跑

**Comment by atian25** [comment]
https://github.com/atian25/blog/issues/25

**Comment by atian25** [comment]
在上面贴的那个链接里面的正文底部，有提到的：

> Egg 的调试，跟 Node 没啥区别，因此一定要了解 Node 的基础调试知识。
> 
> 其中，--inspect-brk 是指在进程第一行就暂停，等待 attach，因此：
> 
> master 先启动，在第一行会停住，需要你 attach master，才会往下走
> 接着 master 启动 agent，也是在第一行停住，需要 attach agent 才会往下走
> 最后 agent 启动完成后，worker 才开始启动，一样也是在第一行停住，需要 attach agent 才会往下走
> 上面这几个 attach，由于上面我们提到的 VSCode 的支持，只需要开启配置，即可无感知的一键 attach。
> 虽然如此，但作为开发者，大家还是需要理解 Node 的调试原理。
