### ISSUE TITLE
使用nginx代理后无法访问带有passport鉴权的接口

### ISSUE THREAD

**Issue by lvao813** [eggjs/egg#3156]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

node:v10.11.0
"egg": "^2.6.1",
 "egg-grpc": "^1.0.3",
 "egg-passport": "^2.0.1",
 "egg-passport-local": "^1.2.1",
我自己用ts+egg来写接口，当设置nginx的时候，发现别的接口都通，但只有设置了passport-local的接口无法调用，返回404的错误，这个是我的代码
add.ts
`
    app.passport.use(new LocalStrategy({
        passReqToCallback: true,
      }, (ctx, _name, _password, done) => {
            let pass_md5 = MD5(_password);
            console.log('passmd5==========>', pass_md5);
            console.log('ctx.body:', ctx);
            console.log('name', _name);
            console.log('password', _password);
            UserModel.findOne({name: _name}, (err, request) => {
                if (err){ return done(err); }
                if (!request){

                    // return done(new Error('用户不存在，请重新输入'));

                }
                // let passmd5 = MD5(_password);
                // console.log('passmd5==========>', passmd5);
                UserModel.findOne({name: _name, password: pass_md5}, (error, user) => {
                    if (err){ return done(error); }
                    if (!request){
                        console.log('密码错误');
                        // return done(new Error('密码错误，请重新输入'));
                    }
                    console.log('passport======>', user);
                    return done(undefined, user);
                    });
            });
        // format user
      }));
    app.passport.serializeUser(async (ctx, user) => {
        console.log('serializeUser');
        console.log(ctx.user);
        console.log('uuuuu');
        console.log(user);
        if (user) {
          return {
            _id: user._id,
          };
        }
      });
    app.passport.deserializeUser(async (ctx, user) => {
        console.log('deserializeUser');
        console.log(user);
        console.log(ctx.user);
        if (user && user._id) {
        //   const exist = await UserModel.findById(mongoose.Types.ObjectId());
          console.log('exist');
        //   console.log(exist);
        //   return exist;
          return user;
        }
        return user;
      });`

router.ts
`import { Application } from 'egg';

export default (app: Application) => {
  const { controller, router } = app;

  router.get('/', controller.home.index);
  router.get('/pass/login', controller.home.login);
  router.get('/pass/success', controller.home.success);
  router.post('/login', app.passport.authenticate('local', { successRedirect: '/getuser',
  failureRedirect: '/pass/login' }));
  router.post('/register', controller.pass.register);
  router.get('/logout', controller.pass.logout);
  router.get('/getuser', controller.login.out);
};
`
只有/login无法连接，别的都是正常，login在我本地调用，不经过nginx是正常的，但只要经过nginx就会失败返回404错误

附上nginx配置：

`
    server {
        listen       8080;
        server_name  localhost;

        #charset koi8-r;

        access_log  logs/host.access.log ;
        error_log logs/error.log;

        location / {
            root   html;
            index  index.html index.htm;
        }
        location /test {
            rewrite ^/test/(.+?)$ /$1 break;
            proxy_pass http://127.0.0.1:7002;
       }
	}`
求救，请问如何来做这一步呢，感觉最大的原因是因为鉴权里面再次跳转的问题，但却不知道如何解决

[附上demo：](https://github.com/lvao813/TS-egg-passport-local-mongo-demo)

**Comment by lvao813** [comment]
问题暂时得到了解决，我在authenticate的方法中，两个跳转都加上了'/test',所以就变成了这样：
`router.post('/login', app.passport.authenticate('local', { successRedirect: '/test/getuser',
  failureRedirect: '/test/pass/login'})); // 用户鉴权`
但这个不是长久的解决方法，还是想知道有没有方法可以避免这样写

**Comment by thonatos** [comment]
```sh
location / {
  proxy_pass        http://127.0.0.1:7001;
}
```

`nginx` 配置问题，建议查阅 `nginx` 文档。
