### ISSUE TITLE
egg-passport-local中间件使用问题

### ISSUE THREAD

**Issue by coolicer** [eggjs/egg#3159]
* **Node Version**:
v8.10.0
* **Egg Version**:
2.2.1
* **Plugin Name**:
egg-passport-local
* **Plugin Version**:
1.2.1
* **Platform**:
Mac
* **Mini Showcase Repository**:

这样跑得了
```js
router.get('/authCallback', controller.users.authenticate);
router.post('/authenticate', app.passport.authenticate('local', { successRedirect: '/authCallback' }));
```

但是改成

```js
router.post('/authenticate', app.passport.authenticate('local'), controller.users.authenticate);
```
就不行了，不能作为中间件使用吗？

**Comment by coolicer** [comment]
curl 测试，返回

Redirecting to <a href="/">/</a>.

**Comment by thonatos** [comment]
`app.passport.authenticate('local')` 默认配置：

```js
# egg-passport:framework use authenticate:local, options: 

{
  "successReturnToOrRedirect":"/",
  "failWithError":true
} 
```

根据 response 测试结果也是先跳转了，所以不会执行后面的逻辑。

```js

➜ export DEBUG=egg-passport:response
egg-passport-local on  master [!] is 📦 v1.2.1 via ⬢ v10.6.0

➜ npm run test
> egg-bin test
  test/passport-local.test.js
[AsyncFunction: passportAuthenticate]
    ✓ should GET / (41ms)
    ✓ should show login tip
  egg-passport:response redirect -> / +0ms
    ✓ login
  3 passing (714ms)
```



- [#L63](https://github.com/eggjs/egg-passport/blob/0afce5b0d5fbc107730e10dad6aff915c03cf079/lib/framework.js)
- [#L23](https://github.com/eggjs/egg-passport/blob/0afce5b0d5fbc107730e10dad6aff915c03cf079/lib/response.js#L23)
