### ISSUE TITLE
[RFC] egg-healthy

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#3161]
标准化应用健康检查，支持两个接口 readiness 和 liveness

参考 https://www.npmjs.com/package/@cloudnative/health

Cloud Health Status | Readiness Status Code | Liveness Status Code
-- | -- | --
STARTING | 503 UNAVAILABLE | 200 OK
UP | 200 OK | 200 OK
DOWN | 503 UNAVAILABLE | 503 UNAVAILABLE
STOPPING | 503 UNAVAILABLE | 503 UNAVAILABLE
STOPPED | 503 UNAVAILABLE | 503 UNAVAILABLE
-- | 500 SERVER ERROR | 500 SERVER ERROR

**Comment by fengmk2** [comment]
找出它的约定规范文档出来？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-healthy/pull/1
