### ISSUE TITLE
默认egg是通过cpu数量来构建对应数量的worker线程，如果自定义对性能有何影响？

### ISSUE THREAD

**Issue by crixusshen** [eggjs/egg#3162]
如果我加大了这个worker线程数量，影响一定会有，但是对服务器的性能是否有很大的影响？由于公司生产环境几乎都是虚拟机，并非实体机，为了充分使用服务器的性能，是否可以加大这个worker数量，如何增加这个数量是最合理的？

**Comment by atian25** [comment]
看你的 docker 给了几个核就几个核
