### ISSUE TITLE
背景图使用多个url时，会导致请求多请求一次

### ISSUE THREAD

**Issue by lear-cash** [eggjs/egg#3163]
![image](https://user-images.githubusercontent.com/18576721/47983717-26696300-e10f-11e8-860e-de81c9b15df9.png)
item.image.url为后台请求来的图片地址，为空时背景图将使用no-news.png,发生这种情况时会使得该页面中所有的数据接口重新请求，相当于页面被重新渲染了一次，这个问题应该怎么解决呢。

**Comment by lear-cash** [comment]
想到了一些处理的方式但是不清楚为何机制是这样的

**Comment by atian25** [comment]
模板渲染语法问题，跟 egg 关系不大，自行排查下。
