### ISSUE TITLE
多服务器部署egg，前面是否只能使用Nginx来做负载均衡，还有其它更优的方案吗?

### ISSUE THREAD

**Issue by crixusshen** [eggjs/egg#3166]
如题

**Comment by atian25** [comment]
负载均衡属于 SLB 层，通用的，跟 Node 没有强关联，可以自行去看这一层的技术选型。

**Comment by fengmk2** [comment]
这个不是 egg 才会有的问题，这个是一个非常基础的 web 应用多机部署基本知识。
可以看看阿里云的 slb 了解一下负载均衡方面的知识。 https://www.aliyun.com/product/slb?spm=5176.10695662.1112700.1.15525e43nXJjVx
