### ISSUE TITLE
egg 开启alinode插件报错

### ISSUE THREAD

**Issue by qiuzhis** [eggjs/egg#3167]
0 info it worked if it ends with ok
1 verbose cli [ '/home/forge/.nvm/versions/node/v8.12.0/bin/node',
1 verbose cli   '/home/forge/.nvm/versions/node/v8.12.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle auto-assign@1.0.0~prestart: auto-assign@1.0.0
6 info lifecycle auto-assign@1.0.0~start: auto-assign@1.0.0
7 verbose lifecycle auto-assign@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle auto-assign@1.0.0~start: PATH: /home/forge/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/forge/auto-assign/node_modules/.bin:/home/forge/.nvm/versions/node/v8.12.0/bin:/sbin:/bin:/usr/sbin:/usr/bin
9 verbose lifecycle auto-assign@1.0.0~start: CWD: /data/forge/auto-assign
10 silly lifecycle auto-assign@1.0.0~start: Args: [ '-c',
10 silly lifecycle   'egg-scripts start --daemon --title=egg-server-auto-assign' ]
11 silly lifecycle auto-assign@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle auto-assign@1.0.0~start: Failed to exec start script
13 verbose stack Error: auto-assign@1.0.0 start: `egg-scripts start --daemon --title=egg-server-auto-assign`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/forge/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/forge/.nvm/versions/node/v8.12.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid auto-assign@1.0.0
15 verbose cwd /data/forge/auto-assign
16 verbose Linux 3.10.0-514.21.1.el7.x86_64
17 verbose argv "/home/forge/.nvm/versions/node/v8.12.0/bin/node" "/home/forge/.nvm/versions/node/v8.12.0/bin/npm" "run" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error auto-assign@1.0.0 start: `egg-scripts start --daemon --title=egg-server-auto-assign`
22 error Exit status 1
23 error Failed at the auto-assign@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

关掉aliNode插件
alinode: {
    enable: false,
    package: 'egg-alinode',
  }
启动正常，置成true时，就会报上面的错误。求解

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

then we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

**Comment by qiuzhis** [comment]
起因大概是有一些过时的api，然后egg-scripts启动不了，但是alinode置成false之后，确能够成功启动起来，或者加了ignore-error参数之后也可以成功启动。谢谢
