### ISSUE TITLE
每次 ci 自动跑一下 benchmark 

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#317]
https://github.com/eggjs/egg/tree/master/benchmarks

可以看看性能趋势

**Comment by popomore** [comment]
没上报的地方？

**Comment by fengmk2** [comment]
先去 log 里面看。

**Comment by atian25** [comment]
有没有类似 cov 那个的 github service? 可以方便的 update 一个 wiki 或 issue ?

**Comment by fengmk2** [comment]
先做了，最终那里收集，都可以写脚本实现。放 firebase 也是可以的

**Comment by atian25** [comment]
独立一个库, 每天跑会不会更好一点?

toa 这些放到 egg 里面感觉怪怪的.

**Comment by popomore** [comment]
@atian25 没见到有这样的服务

**Comment by fengmk2** [comment]
@atian25 有道理，我单独放一个benchmark 库好了。
