### ISSUE TITLE
don't fork new work

### ISSUE THREAD

**Issue by lzxyz** [eggjs/egg#3170]
* **Node Version**: v10.12.0
* **Egg Version**: 2.12.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Windows10 企业版
* **Mini Showcase Repository**:

![image](https://user-images.githubusercontent.com/7233994/48105136-3305cc80-e271-11e8-98ec-8ee06e5dc37d.png)

修改文件后 刷新不变

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by lzxyz** [comment]
https://github.com/lzxyz/eggtest.git
webstorm 修改文件不生效

**Comment by lzxyz** [comment]
WebStorm Safe write 问题。
虽然还会出现don't fork new work (refork: false) 但是修改文件后能生效，不影响开发
