### ISSUE TITLE
get the result of await next() in packetMiddleware

### ISSUE THREAD

**Issue by mhdizade** [eggjs/egg#3174]
* **Node Version**: 8.11.1
* **Egg Version**:2.2.1
* **Plugin Name**: egg-socket.io
* **Plugin Version**: 4.1.5
* **Platform**: windows
* **Mini Showcase Repository**:

i need the result of the handler in packetMiddleware. when i use `const result = await next()` in packetMiddleware, the result is undefined. how to get the result of handler()?

sample code:
``` js
// app/io/middleware/packet.js
module.exports = () => {
  return async (ctx, next) => {
    try {
      const result = await next();// result is undefined :(
      // i need result here. what do i do?
    } catch (e) {
      // e is fine, i see the e
    }
  };
};

// app/io/controller/default.js
const Controller = require('egg').Controller;

class DefaultController extends Controller {
  async index() {
   // do some work and
    return someThing;
  }
}
module.exports = DefaultController;


// config/config.default.js
  exports.io = {
    namespace: {
      '/': {
        connectionMiddleware: [],
        packetMiddleware: [ 'packet' ],
      },
    },
  };

``

**Comment by ngot** [comment]
The middleware philosophy of egg-socket.io is borrowed from koa. If I understand koa correctly, `await next()` is just a middleware invocation without any specific `result value`.

Under this philosophy, we should always pass any data through `context` rather than `result value`.

**Comment by mhdizade** [comment]
@ngot `await next()` for rest actions return the `result value`, i think it is be better if we have the result of io actions too.
