### ISSUE TITLE
framework extend 在使用这个framework的app中会附加在app的app对象上吗?

### ISSUE THREAD

**Issue by ZhouBox** [eggjs/egg#3178]
RT

**Comment by atian25** [comment]
**问题表达不清。**

- 尽可能的减少沟通成本，避免 [『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)
- 绝大部分情况下，通过 `egg-init --type=simple` 来初始化个最小可复现仓库，这个过程中你就会自己发现问题了，这是一种非常高效的问题定位方式。
- 如果还不能解决，此时直接提交到你的 GitHub ，我们来跟进，就会非常的高效，避免挤药膏似的交流。
- 问题解决后，及时关闭 issue，并把解决方式同步进来，方便后来人。issue 本身就是一种非常好的可沉淀的交流方式。

**Comment by ZhouBox** [comment]
node version：v8.12.0
egg version：2.13.0
1.使用了egg-init新建了一个framework类型的项目，然后通过扩展机制，在app上添加了一个errorstring的属性
2.egg-init建立了一个egg-example项目， 引用了这个框架。但是在controll中使用时，errorstring为undefined。

![image](https://user-images.githubusercontent.com/10395321/48183377-688de100-e369-11e8-849a-43016a37eed6.png)

我也看了一些framework，比如nuxt-egg。

**Comment by ZhouBox** [comment]
1.我用你给我的例子里面的代码，例子里面使用的是service， 然后我添加了自定义的代码
```js
module.exports = {

  test(w) {
    return w + 'test';
  },

};
```
然后再app中调用
```js
   const data1 = this.app.test('egg-');
```
![image](https://user-images.githubusercontent.com/10395321/48184877-45b1fb80-e36e-11e8-9e49-3dcc85e151b8.png)


还是undefined的，而且nuxt-egg代码是两年前的，当时应该是有用的，现在我也没试。
请帮忙看下extend机制在framework设计时是否可以使用。

**Comment by atian25** [comment]
肯定是支持的，你提交最小可复现仓库，这样我 clone 下来就直接能看你哪里写错了，而不是局部代码贴了，我再去试，因为有可能是你其他地方配置错了。

**Comment by ZhouBox** [comment]
https://github.com/ZhouBox/eggtest
代码都在这个目录

docker-compose up 运行就行

**Comment by ZhouBox** [comment]
我找到原因了
weihong@weihong-OptiPlex-3046:~/testegg/egg-example/node_modules/_ncmsframework@1.0.0@ncmsframework/app/extend$ cat application.js 
'use strict';

module.exports = {

};
那就是在使用framework时，修改了framework，需要清理node_module?

**Comment by ZhouBox** [comment]
我删除了目录还是不行啊

**Comment by ZhouBox** [comment]
解决了，node_modules删除，重新link就行了。

**Comment by atian25** [comment]
你是 npm install 过去的吧？本地开发可以用 npm link 测试。

**Comment by ZhouBox** [comment]
就是用的link
