### ISSUE TITLE
egg-scripts stop时，执行到一半的定时任务能否优雅的退出

### ISSUE THREAD

**Issue by guchenhui** [eggjs/egg#3182]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
不会，只等待三秒。

**Comment by 779022431** [comment]
如果希望定时任务退出，可否给个实现的思路 @atian25

**Comment by 779022431** [comment]
@atian25 关于定时任务优雅退出 可否提供一个思路？

**Comment by atian25** [comment]
常规任务的做法就可以了，持久化在数据库，如果被干掉了，下次启动检测到重新做就好了。

做优雅退出没法解决问题，因为有可能服务器直接断电啥的，你还是要做上面的事。
