### ISSUE TITLE
solve my Q about serverDidReady function

### ISSUE THREAD

**Issue by WynnLin** [eggjs/egg#3183]
* **Node Version**: 10.7.0
* **Egg Version**: 2.1.0

I want to do my timed task after the egg app started. As far as i can see, i can find the function `serverDidReady` in app.js.
In this function , i request a url which is started by this egg app, it seemed the egg App doesn't start.

here is my code:
```javascript
async serverDidReady() {
    console.log('serverDidReady')
    const ctx = this.app.createAnonymousContext()
    const res = await ctx.service.task.find()
    console.log('res', res)
    res.forEach(task => {
      ctx.curl('http://localhost:7000/api/publish', {
        method: 'POST',
        contentType: 'json',
        data: {
          id: task._id
        },
        dataType: 'json',
      })
    });
  }
```

so is there any other function like afterServerStarted?

**Comment by atian25** [comment]
see egg lifecyle guide docs

https://eggjs.app/zh-cn/advanced/loader.html#ready
