### ISSUE TITLE
egg-logrotator 产生大量无用日志

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#3187]
* **Node Version**: 8.11.3
* **Egg Version**: 2.12.0
* **Plugin Name**: egg-logrotator
* **Plugin Version**:3.0.4
* **Platform**: ubuntu server
* **Mini Showcase Repository**:

logger 配置
config.prod.ts
```ts
import * as path from 'path';
import { DefaultConfig } from './config.default';

export default () => {
    const config: DefaultConfig = {};

    config.logger = {
        dir: path.resolve(__dirname, '../logs'),
    };

    config.logrotator = {
        filesRotateBySize: [
            path.join(__dirname, '../logs/', 'egg-web.log'),
        ],
        maxFileSize: 5 * 1024 * 1024,
    };

    return config;
};

```

一分钟执行一次，每天写大量的无用的日志，都是如下图这种：

<img width="1581" alt="xnip2018-11-12_16-23-41" src="https://user-images.githubusercontent.com/7995232/48335036-83c55d00-e697-11e8-9eab-cfe4f9169459.png">
<img width="1581" alt="xnip2018-11-12_16-23-30" src="https://user-images.githubusercontent.com/7995232/48335037-845df380-e697-11e8-9496-b57e10380987.png">
<img width="549" alt="xnip2018-11-12_16-22-06" src="https://user-images.githubusercontent.com/7995232/48335038-845df380-e697-11e8-9df6-66e19e2bf901.png">

**Comment by atian25** [comment]
如果你不想关注 Schedule 的日志，那把 scheduleLogger 的 log level 调为 Warn 吧。

```js
  config.customLogger = {
    scheduleLogger: {
      level: 'WARN',
      file: path.join(appInfo.root, 'logs', appInfo.name, 'egg-schedule.log'),
    },
  };
```

**Comment by atian25** [comment]
或者把 scheduleLogger 配置到 file size rotator
