### ISSUE TITLE
eggjs.org 文档目录显示出来？

### ISSUE THREAD

**Issue by Ailein** [eggjs/egg#3188]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

现在无法找到目录了，查下内容不方便

**Comment by thonatos** [comment]
屏幕宽度在1136-1366时隐藏文章目录，请调整窗口大小。

**Comment by thonatos** [comment]
#3186

**Comment by Ailein** [comment]
我的是MacBook Pro (Retina, 13-inch, Early 2015) 浏览器全屏了，显示不出来，调整不了大小了 lol

**Comment by thonatos** [comment]
@Ailein 稍等，重新部署。
