### ISSUE TITLE
请问egg支持断点下载吗？

### ISSUE THREAD

**Issue by baiej214** [eggjs/egg#3194]
请问egg支持断点下载吗？我需要下载的文件在public里面放，通过浏览器可以正常下载，但是同事用Android开发的APP一直下载失败，但是他的APP从七牛上下载文件是没问题的，怎么解？

**Comment by brucecodezone** [comment]
服务端生成的文件最好都上传到七牛，最好把地址返回给客户端，再让客户端从七牛下载

**Comment by popomore** [comment]
我看已经支持 range 了，你确定下 android 的具体实现

https://github.com/eggjs/egg-static/pull/13

**Comment by baiej214** [comment]
@brucecodezone 之前就是这样搞的，不过后来方案变了，东西都存储到本地。。。

**Comment by baiej214** [comment]
@popomore 
我后来也看了range，确实支持。但是有个很奇怪的情况，假设我的zip是1000k，服务器返回客户端的contentlength也是1000k，我用Android 8.0原生浏览器下载，接收到的range是0~length-1，下载没问题，但是我们的app是0~length，下载就错误；如果app改成length-1就没问题，能够正常下载。app使用的是okhttp。koa-static或者说是koa-range是依据什么来进行减1操作的？我在koa-range里没找到依据。。。会不会是在断点下载开始前的请求中，返回了已经操作过的contentLength了呢？

但是同样的zip放七牛，app端不做-1操作，或者-1都是开源正常下载的。但是-2就不行了，不知道七牛是不是做了什么兼容的优化？

**Comment by popomore** [comment]
@baiej214 如果还有问题，请提供一下 egg-static 的测试用例，我们会跟进排查。
