### ISSUE TITLE
AppWorkerLoader.loadMiddleware 把所有中间件都加载了

### ISSUE THREAD

**Issue by wellingfine** [eggjs/egg#3202]
我的中间件只在测试环境下跑，所以在config根据不同环境给了不同的中间件列表。

但是egg在启动之后就把 app/middleware 下的所有js加载了一遍，导致线上环境根本没有安装对应的依赖而出错。这是feature 还是bug？

* **Node Version**:v8.11.1
* **Egg Version**:2.12.0
* **Platform**:win7

**Comment by atian25** [comment]
Feature，会加载，但不会挂载。

即使你是不同环境加载不同，你的依赖肯定是要有的啊，否则你怎么在某些环境才安装某些依赖？

不需要为了节省一点体积而做这种处理。

**Comment by wellingfine** [comment]
@atian25 感谢回复

**Comment by atian25** [comment]
仅在测试环境的话，可以考虑：
- 把 require 放到中间件构造函数里面，延迟加载。
- 或者是在单元测试代码里面，手动调用 app.use()。
- 或者是在 test/fixture 里面写一个插件，来插入这个中间件，然后通过 `mm.app({ plugin })` 或 plugin.unitest.js 的方式来加载这个插件。
