### ISSUE TITLE
提示：“DeprecationWarning: crypto.createDecipher is de precated.”，可能跟egg-cookies有关

### ISSUE THREAD

**Issue by lushisang** [eggjs/egg#3203]
运行环境：

* **Node Version**: 11.1.0
* **Egg Version**: 2.2.1
* **Plugin Name**: egg-cookies
* **Plugin Version**: 2.2.6
* **Platform**: Window 10
* **Mini Showcase Repository**: 暂无

重现步骤：

1. 运行 egg-bin dev。
2. 提示：“DeprecationWarning: crypto.createDecipher is de precated.”。
3. 搜索后，egg-cookies 里的 bin/keygrip.js 文件里有 crypto.createCipher。

**Comment by popomore** [comment]
DeprecationWarning 影响使用吗？node 11 目前看还有性能问题，没细看。

**Comment by atian25** [comment]
用 LTS 版本吧

**Comment by lushisang** [comment]
> DeprecationWarning 影响使用吗？node 11 目前看还有性能问题，没细看。

暂时不影响使用。

**Comment by shiny** [comment]
> DeprecationWarning 影响使用吗？node 11 目前看还有性能问题，没细看。

不影响使用，只是安全上打了折扣。根据changelog[1], node 10 也受影响。 
看了下 deprecated 的原因，Node 此 API 使用了 openssl 的 EVP_BytesToKey [2]来根据 password 生成 key 和 iv, 由于固定了以下参数[3]：salt: null、iterations: 1、hash algorithm： md5，三者导致每次生成同一个 key，容易被爆破。
文档里建议使用 crypto.scrypt() 来生成 key 和 iv，然后再使用 crypto.createDecipheriv。
我在尝试在其他语言中实现此 cookie 的解码，也没有 crypto.createDecipheriv 易实现。

1. https://nodejs.org/en/blog/release/v10.0.0/#notable-changes
2. https://github.com/nodejs/node/blob/8c9aaacb333a0223243eda9b3551dbf26fdb260a/deps/openssl/openssl/crypto/evp/evp_key.c#L74
3.  https://github.com/nodejs/node/blob/69140bc7f8f0449e1cf87af8fb24233726acd16e/src/node_crypto.cc#L3861
