### ISSUE TITLE
Client does not support authentication protocol requested by server;

### ISSUE THREAD

**Issue by Luomusha** [eggjs/egg#3204]
本地环境好好的，mac os，mysql8，用sequelize的sync能更新数据库。
到线上环境了，数据库连接不上了，线上环境是
mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
尝试了网上说的mysql_native_password方法，说语法错误。
尝试了直接更新mysql表的方法，oldpassword，不好用。

* **Node Version**:v10.13.0
* **Egg Version**:"egg": "^2.13.0",
* **Plugin Name**:"egg-sequelize": "^4.2.0",
* **Plugin Version**:4.2.0
* **Platform**:debian 9
* **Mini Showcase Repository**:

[egg-scripts] Starting egg application at /home/lossa/family
[egg-scripts] Run node /home/lossa/family/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-family","baseDir":"/home/lossa/family","framework":"/home/lossa/family/node_modules/egg"} --title=egg-server-family
[egg-scripts] Save log file to /home/lossa/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] tail -n 100 /home/lossa/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] 2018-11-16 10:40:07,926 ERROR 5704 nodejs.SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
[egg-scripts]     at Utils.Promise.tap.then.catch.err (/home/lossa/family/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
[egg-scripts]     at tryCatcher (/home/lossa/family/node_modules/bluebird/js/release/util.js:16:23)
[egg-scripts]     at Promise._settlePromiseFromHandler (/home/lossa/family/node_modules/bluebird/js/release/promise.js:512:31)
[egg-scripts]     at Promise._settlePromise (/home/lossa/family/node_modules/bluebird/js/release/promise.js:569:18)
[egg-scripts]     at Promise._settlePromise0 (/home/lossa/family/node_modules/bluebird/js/release/promise.js:614:10)
[egg-scripts]     at Promise._settlePromises (/home/lossa/family/node_modules/bluebird/js/release/promise.js:690:18)
[egg-scripts]     at _drainQueueStep (/home/lossa/family/node_modules/bluebird/js/release/async.js:138:12)
[egg-scripts]     at _drainQueue (/home/lossa/family/node_modules/bluebird/js/release/async.js:131:9)
[egg-scripts]     at Async._drainQueues (/home/lossa/family/node_modules/bluebird/js/release/async.js:147:5)
[egg-scripts]     at Immediate.Async.drainQueues [as _onImmediate] (/home/lossa/family/node_modules/bluebird/js/release/async.js:17:14)
[egg-scripts]     at runCallback (timers.js:705:18)
[egg-scripts]     at tryOnImmediate (timers.js:676:5)
[egg-scripts]     at processImmediate (timers.js:658:5)
[egg-scripts] name: "SequelizeConnectionError"
[egg-scripts] parent: {"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlState":"08004","sqlMessage":"Client does not support authentication protocol requested by server; consider upgrading MariaDB client"}
[egg-scripts] original: {"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlState":"08004","sqlMessage":"Client does not support authentication protocol requested by server; consider upgrading MariaDB client"}
[egg-scripts] pid: 5704
[egg-scripts] hostname: lossa-server
[egg-scripts] 
[egg-scripts] 2018-11-16 10:40:07,927 ERROR 5704 nodejs.SequelizeConnectionError: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
[egg-scripts]     at Utils.Promise.tap.then.catch.err (/home/lossa/family/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
[egg-scripts]     at tryCatcher (/home/lossa/family/node_modules/bluebird/js/release/util.js:16:23)
[egg-scripts]     at Promise._settlePromiseFromHandler (/home/lossa/family/node_modules/bluebird/js/release/promise.js:512:31)
[egg-scripts]     at Promise._settlePromise (/home/lossa/family/node_modules/bluebird/js/release/promise.js:569:18)
[egg-scripts]     at Promise._settlePromise0 (/home/lossa/family/node_modules/bluebird/js/release/promise.js:614:10)
[egg-scripts]     at Promise._settlePromises (/home/lossa/family/node_modules/bluebird/js/release/promise.js:690:18)
[egg-scripts]     at _drainQueueStep (/home/lossa/family/node_modules/bluebird/js/release/async.js:138:12)
[egg-scripts]     at _drainQueue (/home/lossa/family/node_modules/bluebird/js/release/async.js:131:9)
[egg-scripts]     at Async._drainQueues (/home/lossa/family/node_modules/bluebird/js/release/async.js:147:5)
[egg-scripts]     at Immediate.Async.drainQueues [as _onImmediate] (/home/lossa/family/node_modules/bluebird/js/release/async.js:17:14)
[egg-scripts]     at runCallback (timers.js:705:18)
[egg-scripts]     at tryOnImmediate (timers.js:676:5)
[egg-scripts]     at processImmediate (timers.js:658:5)
[egg-scripts] name: "SequelizeConnectionError"
[egg-scripts] parent: {"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlState":"08004","sqlMessage":"Client does not support authentication protocol requested by server; consider upgrading MariaDB client"}
[egg-scripts] original: {"code":"ER_NOT_SUPPORTED_AUTH_MODE","errno":1251,"sqlState":"08004","sqlMessage":"Client does not support authentication protocol requested by server; consider upgrading MariaDB client"}
[egg-scripts] pid: 5704
[egg-scripts] hostname: lossa-server
[egg-scripts] 
[egg-scripts] 2018-11-16 10:40:07,927 ERROR 5704 [agent_worker] start error, exiting with code:1
[egg-scripts] 2018-11-16 10:40:07,940 ERROR 5696 nodejs.AgentWorkerDiedError: [master] agent_worker#1:5704 died (code: 0, signal: null)
[egg-scripts]     at Master.onAgentExit (/home/lossa/family/node_modules/egg-cluster/lib/master.js:328:17)
[egg-scripts]     at Master.emit (events.js:182:13)
[egg-scripts]     at Messenger.sendToMaster (/home/lossa/family/node_modules/egg-cluster/lib/utils/messenger.js:133:17)
[egg-scripts]     at Messenger.send (/home/lossa/family/node_modules/egg-cluster/lib/utils/messenger.js:98:12)
[egg-scripts]     at ChildProcess.agentWorker.once (/home/lossa/family/node_modules/egg-cluster/lib/master.js:219:22)
[egg-scripts]     at Object.onceWrapper (events.js:273:13)
[egg-scripts]     at ChildProcess.emit (events.js:182:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
[egg-scripts] name: "AgentWorkerDiedError"
[egg-scripts] pid: 5696
[egg-scripts] hostname: lossa-server
[egg-scripts] 
[egg-scripts] 2018-11-16 10:40:07,941 ERROR 5696 [master] agent_worker#1:5704 start fail, exiting with code:1
[egg-scripts] 2018-11-16 10:40:07,941 ERROR 5696 [master] exit with code:1
[egg-scripts] 
[egg-scripts] Start got error, see /home/lossa/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.

**Comment by popomore** [comment]
这个去 sequelize 问吧

**Comment by wxingheng** [comment]
@Luomusha 
你好 我使用  egg/example   

![image](https://user-images.githubusercontent.com/20256886/56455161-c51c1000-638d-11e9-91bc-22f340ea5ffb.png)
可以知道一下吗，非常感谢    1228678518

**Comment by atian25** [comment]
这就是个 seq 的 cli，跟 egg 应该没啥关系，看看报错信息自己搜索下，或者去官方看看
