### ISSUE TITLE
egg-sequelize的版本问题建议

### ISSUE THREAD

**Issue by lyh2668** [eggjs/egg#3208]
从自身需求出发，然后发现了一些问题
- 需求：
定义model的字段希望采用的是驼峰式，存到数据库的field希望变成小写字母加下划线的方式（规范）
- 探究过程
定义model的字段必需指名field才可以且开启underscored: true才可以变成下划线的形式，但其实这样很不方便，本身只需要定义underscored应该就可以完成转换，不需要在指名field。所以在[issues 6423](https://github.com/sequelize/sequelize/issues/6423)中有很多人讨论这个问题，然后这个问题在[v5-beta3](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md#500-beta3)版本中得到修复。但是这个问题就算指明了field仍然存在BUG，就是当字段更新的时候，官方有提供Model.sync({ alter: true })的方式更新，在4.x版本这个方法将会忽略field，这个问题在[v5-beta8](https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md#500-beta8)中得到修复。然后我就开始更新我的sequelize到beta版本，但是始终无法是最新版本生效，最后阅读egg-sequelize的[源码](https://github.com/eggjs/egg-sequelize/blob/master/config/config.default.js)才发现一段被注释的话
```
  // support customize your own Squelize
  // Sequelize: require('sequelize'), // v5 or v3
```
- 期望
我希望可以在文档中体现我遇到的这个问题，并且把可以使用自定义版本的sequelize告诉用户，这样可以更容易解决问题。

**Comment by dead-horse** [comment]
请提 PR

**Comment by dead-horse** [comment]
本质上这是 sequelize 的问题

**Comment by lyh2668** [comment]
> 本质上这是 sequelize 的问题

@dead-horse 对的，本质这个是sequelize的问题，但是由于现在还是beta版本，所以不会直接从v4版本升级到v5-beta版，但是这个问题应该还会有其他的人碰到，我觉得在sequelize的那块文档中至少要体现可以自定义sequelize的版本。

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-sequelize#customize-sequelize

**Comment by lyh2668** [comment]
@dead-horse 谢谢，是我阅读不仔细
