### ISSUE TITLE
一台服务器部署多少个egg服务适合，大家有最佳实践吗？

### ISSUE THREAD

**Issue by CNYeFeng** [eggjs/egg#3210]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

比如有20个独立的egg服务，我将这个 20个服务开启 20个端口，部署在一个服务器上，再用nginx反向代理到这个服务器上。这样做 合适吗？ 哪位 大牛 有 类似的 最佳实践

**Comment by atian25** [comment]
脱离业务谈压力没意义。。。
如果你一个服务用户量很大，都能占用 80% 的内存和 CPU，自然只能独占。
如果你每个服务都才 1% 不到的资源占用，那就随意吧。

PS：docker 化
