### ISSUE TITLE
大家都在用 那个 egg版本？

### ISSUE THREAD

**Issue by CNYeFeng** [eggjs/egg#3212]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

之前 我的 egg 版本 用的是 最新版本。接入阿里性能平台alinode 后，提升 我的 egg版本是不稳定版本。我改成了建议的 2.1.0 版本。 大家有什么意见？ 大家都在用 那个版本？

**Comment by atian25** [comment]
把提示截图看看？

egg 永远是推荐用 `^2` 引入，我们遵循 Semver 规则，保证同个大版本下的兼容性。

**Comment by CNYeFeng** [comment]
[https://github.com/CNYeFeng/helloword/blob/master/1542613113108.jpg](url)

图片如上~  我之前用的版本。不是2.1.0 是更高的版本。我按提示换成 2.1.0 了。

**Comment by CNYeFeng** [comment]
怎么给我 close 了？

**Comment by atian25** [comment]
答案是：永远使用当前大版本下的最新版本。

至于那个提示，是 alinode 的版本推荐吧，cc @hyj1991

**Comment by CNYeFeng** [comment]
@atian25   @hyj1991  对的，是alnode 推荐的。所以我有点敲不定。该用 alinode推荐的最新版本？还是 egg 目前release的最新版本。  我选择 版本应该遵循的规则是什么？请 大牛 指教

**Comment by CNYeFeng** [comment]
@atian25 多谢~
