### ISSUE TITLE
Feature request : egg-scripts restart after crash

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3213]
Please add an option to fork new process when a child process is killed due to crashes

**Comment by dead-horse** [comment]
egg-scripts use https://github.com/eggjs/egg-cluster to manage egg's workers, it will fork new worker when worker is killed.

**Comment by sm2017** [comment]
I test that when in application startup , I loose database , and having a connection timeout error , my app craches and it dont fork again

**Comment by atian25** [comment]
because it's a startup check fails.

if you don't need to connect database on startups, don't config it at config.default.js, instead createInstance by yourself.
