### ISSUE TITLE
为何模板渲染的时候找不到view目录下的.tpl文件

### ISSUE THREAD

**Issue by viyoung** [eggjs/egg#3214]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by atian25** [comment]
- 尽可能的减少沟通成本，避免 [『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)
- 绝大部分情况下，通过 `egg-init --type=simple` 来初始化个最小可复现仓库，这个过程中你就会自己发现问题了，这是一种非常高效的问题定位方式。
- 如果还不能解决，此时直接提交到你的 GitHub ，我们来跟进，就会非常的高效，避免挤药膏似的交流。
- 问题解决后，及时关闭 issue，并把解决方式同步进来，方便后来人。issue 本身就是一种非常好的可沉淀的交流方式。
