### ISSUE TITLE
[typescript] app.beforeStart 不起作用

### ISSUE THREAD

**Issue by lynzz** [eggjs/egg#3215]
* **Node Version**: v8.9.1
* **Egg Version**: 2.14.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS Mojave 10.14.2
* **Mini Showcase Repository**: https://github.com/lynzz/cqb-report-serve

用 puppeteer 做网页转 pdf 功能，想在服务启动时，执行 app.browser = await puppeteer.launch() ，把 browser 注入 app 里，调试时发现走不到 beforeStart，奇怪是哪里用不对，求解，如下：

```
import * as puppeteer from 'puppeteer';
import {Browser} from 'puppeteer'
import { Application } from 'egg';

export default function (app: Application) {
  console.log('app....')
  app.beforeStart(async () => {
    try {
      console.log('before start...')
      app.browser = await puppeteer.launch();
      console.log('app start:', app.browser)
    } catch (error) {
      console.log(error)
    }
  })
}

declare module 'egg' {
  interface Application {
    browser: Browser
  }
}
```

**Comment by popomore** [comment]
你的 app.ts 呢

**Comment by lynzz** [comment]
直接用 egg-init 生成出来的，还得有一个 app.ts 才能生效了？，我去试试

**Comment by lynzz** [comment]
可以了，启动自定义要在 app.ts 里的，我原写在 extend 里了，文档还是没仔细看，egg-init type=ts 也建议能生成一个 app.ts 的文件
