### ISSUE TITLE
egg-init 初始化 sequelize 模板项目后, package.json 中没有 script:dev

### ISSUE THREAD

**Issue by zen-li** [eggjs/egg#3217]
* **Node Version**: 10.13.0
* **Egg-init Version**: 1.12.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: macOS 10.14
* **Mini Showcase Repository**:

使用 egg-init 初始化 sequelize 模板项目:

```
  simple - Simple egg app boilerplate
  microservice - Microservice app boilerplate based on egg
❯ sequelize - egg app with sequelize
  ts - Simple egg && typescript app boilerplate
  empty - Empty egg app boilerplate
  plugin - egg plugin boilerplate
  framework - egg framework boilerplate
```

完成后提示:

```
[egg-init] usage:
      - cd /Users/zen/Work/Test/egg-example
      - npm install
      - npm start / npm run dev / npm test
```

安装完依赖后执行 `npm start` 或 `npm run dev` 报错 `missing script: start/dev`.

查看 `package.json` 的 script 部分:

```
"scripts": {
    "autod": "autod",
    "lint": "eslint .",
    "test": "egg-bin test",
    "cov": "egg-bin cov",
    "ci": "npm run lint && NODE_ENV=test npx sequelize db:migrate && npm run cov"
  },
```

没有 `script:test` 和 `script:dev`.

项目中有如下文件/文件夹:

- README.md
- config
- database
- node_modules
- package-lock.json
- package.json
- test

**Comment by atian25** [comment]
可以自己加下。就是 `egg-bin xx`
同时欢迎 PR 给骨架增加下。
