### ISSUE TITLE
生产环境可不可以通过env来读取不同config?

### ISSUE THREAD

**Issue by luckyxutao** [eggjs/egg#3218]
我们的部署的方式是 dev、beta、production 
想在dev、beta服务器上都采用生产环境模式运行 egg-script start --env prod， 在dev读取config.dev.js、beta读取config.beta.js，
我们的dev  beta 都是通过jenkins远程部署的和本地local不一样，只是想通过环境变量来启动不同config
不知道可不可以?
生产环境运行，通过环境变量来读取不同config，非prod环境还带着egg-watcher，我们在服务器上不需要
`javascript`
    "start": "NODE_ENV=production egg-scripts start --env prod --daemon --title=egg-server-travel-node --port=7001",
    "start:beta": "NODE_ENV=production egg-scripts start --env beta --daemon --title=egg-server-travel-node --port=7001",
    "start:dev": "NODE_ENV=production start --env dev egg-scripts start --title=egg-server-travel-node --port=7001",
```

**Comment by luckyxutao** [comment]
找到原因了，和egg无关

**Comment by atian25** [comment]
支持 config.beta.js 等，中间的 env 可以自行定义。
可以看下文档。
