### ISSUE TITLE
egg-rpc-generator抛错

### ISSUE THREAD

**Issue by hupengfoot** [eggjs/egg#3219]
已安装egg-sofa-rpc，执行egg-rpc-generator时抛如下错误
![image](https://user-images.githubusercontent.com/2427715/48827868-40f73980-eda9-11e8-95b8-49ecf9f37b2b.png)

**Comment by atian25** [comment]
看起来是缺了 rpc 插件没开启。

**Comment by gxcsoccer** [comment]
```bash
$ npm i egg-rpc-base --save
```

```js
exports.rpc = {
  enable: true,
  package: 'egg-rpc-base',
};
```

**Comment by gxcsoccer** [comment]
egg-rpc 模块被抢占了，所以只能用 egg-rpc-base

**Comment by hupengfoot** [comment]
> egg-rpc 模块被抢占了，所以只能用 egg-rpc-base

这个问题解决了，但是执行egg-rpc-generate后并未产生app/proxy/ProtoService.js文件，日志报如下错误
![image](https://user-images.githubusercontent.com/2427715/48829868-499e3e80-edae-11e8-8071-b0e66d8a364f.png)

**Comment by gxcsoccer** [comment]
@hupengfoot 

你的 jar 包里有 com.alipay.sofa.rpc.test.ProtoService 这接口吗？

你是走的 pb 还是 hessian 序列化？

**Comment by hupengfoot** [comment]
> @hupengfoot
> 
> 你的 jar 包里有 com.alipay.sofa.rpc.test.ProtoService 这接口吗？
> 
> 你是走的 pb 还是 hessian 序列化？

我这边注册的服务端也是node，proto配置如下
![image](https://user-images.githubusercontent.com/2427715/48878365-0b525f00-ee42-11e8-9d30-c4889a8ab42d.png)
我想使用node client rpc调用node server，这样可以吗？

**Comment by gxcsoccer** [comment]
com.alipay.sofa.rpc.test.ProtoService => com.alipay.sofa.rpc.protobuf.ProtoService

**Comment by hupengfoot** [comment]
> com.alipay.sofa.rpc.test.ProtoService => com.alipay.sofa.rpc.protobuf.ProtoService

已解决👍

**Comment by CoCoyh** [comment]
<img width="716" alt="2019-01-21 10 45 07" src="https://user-images.githubusercontent.com/24558814/51449973-b19ae200-1d69-11e9-87f4-71ae93e6a96d.png">
碰到和楼主一样的问题了，@gxcsoccer帮忙看一下？

**Comment by CoCoyh** [comment]
解决了，谢谢！但是还有个请教一下，
<img width="702" alt="2019-01-21 11 33 57" src="https://user-images.githubusercontent.com/24558814/51451477-77810e80-1d70-11e9-8310-19a7c6a82eb8.png">

proto文件报错，是一行引起的问题，这是为什么，应该怎么写？我把它删了，就好了

**Comment by gxcsoccer** [comment]
@CoCoyh protobuf 里面的注释是 // 或 /* ... */

https://developers.google.com/protocol-buffers/docs/proto#adding-comments

**Comment by CoCoyh** [comment]
好的，谢谢，刚开始接触这个，有点懵～～

**Comment by CoCoyh** [comment]
<img width="867" alt="2019-01-21 1 38 41" src="https://user-images.githubusercontent.com/24558814/51454873-ee72d300-1d81-11e9-85ed-277ebb59e140.png">
```
npm run dev
```
报错了，是生成的proxy文件里的错误，但这个文件提示不要改动，再帮忙看下@gxcsoccer

**Comment by CoCoyh** [comment]
我在执行npm run dev 报错了，是生成的proxy文件里的错误，但这个文件提示不要改动，再帮忙看下@gxcsoccer
<img width="867" alt="2019-01-21 1 38 41" src="https://user-images.githubusercontent.com/24558814/51454953-4b6e8900-1d82-11e9-86c4-72a045bc9f62.png">

**Comment by CoCoyh** [comment]
我在执行npm run dev 报错了，是生成的proxy文件里的错误，但这个文件提示不要改动，再帮忙看下@gxcsoccer
<img width="867" alt="2019-01-21 1 38 41" src="https://user-images.githubusercontent.com/24558814/51454968-650fd080-1d82-11e9-97f4-a43bf5682763.png">

**Comment by gxcsoccer** [comment]
@CoCoyh 你需要配置 rpc 的 registry 或指定直连的地址

## registry 配置
registry 你可以选择 zookeeper 或 nacos 

```js
exports.rpc = {
  registry: {
    type: 'nacos', // 如果是 zookeeper，这里填 zookeeper
    address: '127.0.0.1:8848', // 换成你实际的地址
  },
};
```

## 直连配置

```js
exports.rpc = {
  client: {
    'sofarpc.rpc.service.url': '127.0.0.1:12200', // 换成实际的地址
  },
};
```

**Comment by CoCoyh** [comment]
java rpc是下载的你的demo

**Comment by CoCoyh** [comment]
@gxcsoccer java rpc是下载的你的demo

**Comment by gxcsoccer** [comment]
> @gxcsoccer java rpc是下载的你的demo

地址发我下

**Comment by CoCoyh** [comment]
@gxcsoccer https://github.com/gxcsoccer/sofa-rpc-java-demo

**Comment by gxcsoccer** [comment]
> @gxcsoccer https://github.com/gxcsoccer/sofa-rpc-java-demo

@CoCoyh 我更新了下 sofa-rpc-java-demo 这个 java 代码，你 git pull 一下

**Comment by gxcsoccer** [comment]
如果走直连的话，url 需要加一个参数 serialization=protobuf
```js
exports.rpc = {
  client: {
    'sofarpc.rpc.service.url': '127.0.0.1:12200?serialization=protobuf', // 换成实际的地址
  },
};
```
