### ISSUE TITLE
使用egg-passport 小程序如何获取 EGG_SESS 

### ISSUE THREAD

**Issue by XiaoYaoDaddy** [eggjs/egg#3220]
由于小程序不支持cookies, 所以只有手动存, 在登录成功后，egg-passport 好像是通过一条长连接的redirect消息， 跟客户端同步EGG_SESS, 但，这条消息不能在小程序中获取， 现在有什么办法可以让小程序收到cookies;

**Comment by XiaoYaoDaddy** [comment]
没有人知道怎么解决吗？还是不在讨论范围内？

**Comment by XiaoYaoDaddy** [comment]
无计可施，只能通过httpclient 转发cookies 
`
async loginWithProxy() {
    const result = await this.ctx.curl('http://127.0.0.1:7001/auth/wechat_login?code=' + this.ctx.query.code);
    this.ctx.status = 200;
    this.ctx.body = result.data;
    this.ctx.set(result.headers);
 }
`

**Comment by thonatos** [comment]
小程序不大熟悉，如果页面和程序是分离的，或者你需要`jwt`而不是`session`?

**Comment by popomore** [comment]
小程序问题不要在这里问题，如果 egg 有问题给出重现代码。
