### ISSUE TITLE
使用egg-init之后就不动了

### ISSUE THREAD

**Issue by zm592565** [eggjs/egg#3221]
![image](https://user-images.githubusercontent.com/23302142/48879975-41471180-ee49-11e8-8fad-7b92b66672c9.png)
只有一次是成功的其他时间就是这样 每次就不动了。。不知道什么原因 请问能帮我分析下是什么原因吗

**Comment by zm592565** [comment]
egg-init testdemo -r -china? 依然不动  这是咋回事呢？

**Comment by atian25** [comment]
-r china

**Comment by zm592565** [comment]
加了还是老样子

**Comment by popomore** [comment]
npm 安装这个库可以吗

**Comment by martin-yin** [comment]
确定这个问题不解决一下吗？

**Comment by zm592565** [comment]
已经不用egg了·····改用koa

**Comment by atian25** [comment]
@martin-yin 无法复现，没法跟进。

egg-init 还在重构中。
