### ISSUE TITLE
egg-scripts start --deamon 不断重启

### ISSUE THREAD

**Issue by CNYeFeng** [eggjs/egg#3223]
* **Node Version**: 8.12
* **Egg Version**: 2.14.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

在测试环境  下面的命令来起来egg服务。发现 在不断的重启。有人遇到过吗？ 是什么原因？
EGG_SERVER_ENV=test ENABLE_NODE_LOG=YES egg-scripts start --daemon --title=egg-server-xinche-platform-api

**Comment by CNYeFeng** [comment]
@popomore  感谢回答。问题解决了。是docker的问题

**Comment by shenlq** [comment]
@CNYeFeng docker什么问题引起的，我也出现了

**Comment by atian25** [comment]
docker 不能加 daemon

**Comment by WinjayYu** [comment]
> docker 不能加 daemon

花了2小时才发现是这个问题😭
