### ISSUE TITLE
egg-redis 一直重新连

### ISSUE THREAD

**Issue by liutao** [eggjs/egg#3226]
您好，我现在遇到一个一直输出问题。在生产环境的机器上，一直往复打印以下log，看了一下egg-redis的源码，输出这个是在redis connent成功的时候。

2018-11-22 20:49:57,741 INFO 47789 [egg-redis] connect success on redis://:xxx@xxxx:xxx/1

但是一直没有触发app.beforeStart，没有打出。

[egg-redis] instance[${index}] status OK, redis currentTime: ${result[0]}

请问这个可能是什么导致的？是redis连接成功之后立马又断开导致的吗？还是说个worker之间互相影响了？

在测试环境的机器上是没问题的。

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by liutao** [comment]
找到原因了。我们的线上redis禁止了很多command，比如info。。。egg-redis在beforeStart执行了client.info()。翻了一下ioredis的源码，会发送一个info 的command。然后就导致断了连接重连了。

**Comment by popomore** [comment]
这个探测是不是不要重连

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-redis/pull/20/files#diff-29082f5e41ec25b946c4be3903c9cf39R41 提供可配置项目，如果 server 不支持 TIME 命令，关闭它。

**Comment by zheng199512** [comment]
您好，楼主 @liutao ，想问您一下：
1、`supportTimeCommand`默认是开启的，也就是说默认就是探测redis是否准备好么？我看在源码中`app.beforeStart`有这个操作了。
2、在java方法中有封装一个及时发现redis集群宕机返回错误消息，无需等待TCP超时和重试机制。`egg-redis`有这样的操作么？`supportTimeCommand`是为了及时发现错误的么？
3、我对redis还不是很熟悉，在企业中应用会让redis一直进行连接重试么？我刚才试了一下会一直进行redis的重连。
请需要请大佬指导，谢谢

**Comment by Erchoc** [comment]
遇到同样的问题，redis 频繁重连。日志一直打印 [egg-redis] client connect success，但在其他部署环境中又正常
