### ISSUE TITLE
大家有没有遇到过egg 服务api , 在本地测试没问题，发布到docker里就 503

### ISSUE THREAD

**Issue by CNYeFeng** [eggjs/egg#3228]
* **Node Version**:8.12
* **Egg Version**:2.14.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

大家有没有遇到过egg 服务api , 在本地测试没问题，发布到docker里就 503

**Comment by popomore** [comment]
估计 docker 写的有问题，没 export 端口之类的

**Comment by CNYeFeng** [comment]
upstream connect error or disconnect/reset before headers  返回接口出现这个错。可能是什么原因呢？

**Comment by popomore** [comment]
就是连不上你的应用
