### ISSUE TITLE
clinic启动egg进行代码性能分析报错

### ISSUE THREAD

**Issue by JsonMa** [eggjs/egg#3230]
如题，clinic如何启动egg进行代码性能分析？
clinic官方的示例为：
```javascript
clinic doctor --on-port 'autocannon localhost:$PORT' -- node app.js
```
在egg项目使用node node_modules/.bin/eggctl dev启动，在windows下会提示错误，内容为:
```javascript
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

* **Node Version**: 10.13.0
* **Egg Version**: 2.14.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: windows7
* **Mini Showcase Repository**:
package.json配置为：
```javascript
 "dev": "clinic doctor -- node node_modules/.bin/eggctl dev",
```
如果是因为windows导致的eggctl dev无法正常启动，是否还有其它的解决办法？

**Comment by RoseFang** [comment]
请问楼主解决了吗？
我是这样启动的，创建一个server.js，调用egg.startCluster来启动
server.js 如下：
`const egg = require('egg');

const workers = Number(process.argv[2] || require('os').cpus().length);
egg.startCluster({
    workers,
    baseDir: __dirname,
});`

clinic命令如下：
clinic doctor -- node server.js

但是启动后总是报错 clinic doctor does not support clustering：
![image](https://user-images.githubusercontent.com/12082231/48965765-5add8a00-effe-11e8-8307-0d3cd415d572.png)

**Comment by JsonMa** [comment]
从错误信息看是clinic不支持集群，我想接下来尝试，看看能否从worker进程入手。

**Comment by atian25** [comment]
如果要求是在第一行运行的话，通过 `egg-scripts` 启动的时候，加下 `-r` 参数即可。
https://github.com/eggjs/egg-cluster/blob/master/lib/app_worker.js#L4

对 clinic 不了解，这种工具居然会不支持 cluster ？去官方 GitHub 看看？

cc @hyj1991

**Comment by hyj1991** [comment]
提个 issue 给 [0x](https://github.com/davidmarkclements/0x) 问问吧，看起来这个问题和 egg 本身没什么关系，而且一般本地压测都是单进程模式

**Comment by advence-liz** [comment]
我是这么解决的额外写一个单进程启动文件
singleProcess.js
`const path = require('path')
const egg = require('egg')

const singleProcessApp = async (options = {}) => {
    options.env = options.env || 'local'
    options.baseDir = path.resolve('./')
    const app = await egg.start(options)
    app.listen(7001)
    return app
}

singleProcessApp()
`

"clinic":"clinic doctor --on-port 'autocannon -c 100 -d 10 -p 10 localhost:$PORT' -- node  singleProcess.js",
