### ISSUE TITLE
[http_server] A request timeout

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3232]
* **Node Version**: v10.13.0
* **Egg Version**:v10.13.0
* **Platform**: Windows 10

Today I upgrade node from 8 to 10 and upgrade eggjs from 2.2.1 to 2.14.0 by yarn
I have too many `[http_server] A request timeout` warning , in dev mode each time I send request I have a timeout warn but I can see the response successfully and fast

**Comment by atian25** [comment]
land 2.14.1
