### ISSUE TITLE
使用系统环境变量传递配置

### ISSUE THREAD

**Issue by whlsxl** [eggjs/egg#3234]
* **Node Version**: 10.13.0
* **Egg Version**:2.14.1
* **Platform**:centOS 7.4
* **Mini Showcase Repository**:
我是在`docker`中部署`egg`的。在`docker`中，可以通过环境变量指定数据库密码之类的信息。如果这个配置能直接在`egg`的`config`中解析，那就不用二次输入。
或者通过别的方式，把配置传递到`egg`。

**Comment by atian25** [comment]
when you are using egg, it doesn't mean you should not use base Node.js logic.

just read `process.env` at `config.default.js`.

**Comment by whlsxl** [comment]
额。。 我说的是关于定义的系统环境变量传递到`egg` 的`config`啊。输出看了下`app.config` 里面没有关于系统环境变量的定义。
我的需求是，比如在`Dockerfile`里定义的`ENV MYSQL_PASSWORD xxxx` 会传递到`container`的系统变量里的，这时候，如果能直接在`egg`里读取到这个系统变量，那就非常方便了！

**Comment by atian25** [comment]
我的意思是，docker 怎么传递给 container，那属于 docker 那块的。
然后传递进去后，Node 这边通过 process.env.XXX 就可以拿到了。
至于你想在 app.config 里面拿，那你自己在 config.default.js 里面配啊。

譬如 `app.config.mysql.password = process.env.XXX` 或者犯懒直接 `app.config.systemEnv = process.env`
