### ISSUE TITLE
this.ctx.URL.href在什么情况下为undefined

### ISSUE THREAD

**Issue by SSoLMan** [eggjs/egg#3235]
我在middleware中，使用this.ctx.URL.href.indexOf 时报错 Cannot read property 'indexOf' of undefined;

- 此问题本地无法复现，线上单台服务器（6核）每1分钟会进行5次同样报错（很规律）。
- 业务代码并无定时任务。 
- node性能配平台显示，单台服务器qps稳定在0.2；

目前怀疑，是持续异常请求导致ctx.URL.href不存在；那么在egg中什么情况下ctx.URL.href为undefined?。

**Comment by SSoLMan** [comment]
sorry，刚看了ctx.URL是koa 提供的，但是URL异常的情况确定很费解

**Comment by atian25** [comment]
Koa 也没有 ctx.URL 。

你还是说你的原始需求吧。。。

**Comment by atian25** [comment]
参考下源码，try catch 下看看 `ctx.href` 是啥。

这个 URL 是 Node 7 后才出来的，为什么要绕着使用呢？直接 `ctx.href` 不行？

**Comment by SSoLMan** [comment]
好的，感谢。我改成ctx.href排查一下
