### ISSUE TITLE
egg-antd-design-pro umi版本run dev,run build失败

### ISSUE THREAD

**Issue by kstar11** [eggjs/egg#3236]
egg-antd-design-pro最新的umi版本,down下来之后,npm run dev会在编译到95%时卡住不动
![image](https://user-images.githubusercontent.com/25189126/49014214-5d84de80-f1ba-11e8-9ce8-5b83c4426a4e.png)

npm run build会因为scripts中的APP_ROOT这一段无法执行

**Comment by kstar11** [comment]
大约是系统的问题吧,试了很多次,始终不可行,找了其他的替代方案,先close掉了

**Comment by okoala** [comment]
你在项目根目录下 umi -v --verbose 看看

**Comment by popomore** [comment]
umi 本身是好的？

**Comment by popomore** [comment]
有问题再看吧，本地无法复现。

**Comment by JoinGz** [comment]
> 大约是系统的问题吧,试了很多次,始终不可行,找了其他的替代方案,先close掉了

我也遇到了这个问题，能讲讲最后怎么解决的吗？
