### ISSUE TITLE
关于event-stream后门egg处理了么？

### ISSUE THREAD

**Issue by jakehu** [eggjs/egg#3238]
`event-stream ` 爆出后门。

[Issues](https://github.com/dominictarr/event-stream/issues/116)

![15432982893731](https://user-images.githubusercontent.com/2782883/49061884-0b40cd80-f24d-11e8-9499-383b2c5f26e3.png)

**Comment by justjavac** [comment]
不需要处理吧，event-stream 处理完就行了

**Comment by justjavac** [comment]
重新 install 就行了，猪哥不锁包

**Comment by atian25** [comment]
只要不锁版本就没事

**Comment by dead-horse** [comment]
这个问题不影响 egg

**Comment by imakan** [comment]
不是搞比特币的，应该没有影响

**Comment by chaoningx** [comment]
> 删掉之前的 `package-lock.json` 和 `node_modules` 然后再 `npm install` 一次就OK了

一样的，不会升级到最新的版本。

**Comment by Runrioter** [comment]
把你主项目的package.json deps那块的json贴一下 @chaoningx

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by chaoningx** [comment]
> 把你主项目的package.json deps那块的json贴一下 @chaoningx

"dependencies": {
    "egg": "^2.14.1",
    "egg-cors": "^2.1.1",
    "egg-mongoose": "^3.1.1",
    "egg-scripts": "^2.5.0",
    "egg-validate": "^2.0.2",
    "egg-view-nunjucks": "^2.2.0",
    "i": "^0.3.6",
    "mime": "^2.4.0",
    "oceans-helper": "^1.4.0"
  },

**Comment by Runrioter** [comment]
@chaoningx  按照 @atian25  的方式操作一下 应该没有问题

**Comment by chaoningx** [comment]
请问一下之后的版本会处理吗？

**Comment by dead-horse** [comment]
社区已经统一处理了，并且这个问题不影响 egg。

**Comment by atian25** [comment]
最后统一回复下：
- 该问题经过我们的安全分析和解读源码，对 Egg 没有任何影响。
- 依赖包的问题，egg 是通过 semver 引入依赖的，而 event-stream 昨天就已经修复了。
- 因此，只要你没有锁版本，直接按上面的执行，重新安装下依赖，就没问题了。
- 如果依赖安装有问题，大概率是你锁了版本，或者是 CLI 使用问题，可以了解下 Node 模块依赖的相关基础知识，或者看下相关的 npm / yarn 相关文档。
