### ISSUE TITLE
worker监听agent发送的消息有最大时间限制吗？

### ISSUE THREAD

**Issue by leizhao92** [eggjs/egg#3240]
* **Node Version**:v8.9.0
* **Egg Version**:1.4.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Centos 7
* **Mini Showcase Repository**:

您好，现在项目中有一个管理定时器的需求。针对每次新增定时任务，我们目前的做法是从worker发送消息到agent（app.messenger.sendToAgent）并开始监听agent返回的消息（app.messenger.on），agent接收到消息后在agent端创建setTimeout定时器，并且把定时器放入临时缓存文件中（便于对定时器进行增删改查等操作）。定时器内部的业务是到setTimeout设定的时间后向worker发送消息，通知worker时间到了该处理具体业务了（agent.messenger.sendTo）。

简而言之就是：worker监听agent发送的消息会有时间限制吗？比如worker在当前开始监听agent端发送的消息（app.messenger.on("xxx")）,agent在此后的任何时间点给worker发送消息（agent.messenger.sendTo("xxx",data)）,worker都能够接收到吗？ 非常感谢！

**Comment by popomore** [comment]
没限制

但是你水平扩容怎么做。
