### ISSUE TITLE
event-stream模块安全问题

### ISSUE THREAD

**Issue by hupengfoot** [eggjs/egg#3242]
npm官方event-stream前端框架依赖库被植入恶意代码，安装后可能导致服务器上敏感数据被窃取，
egg依赖了改模块，egg这边会如何处理？
![image](https://user-images.githubusercontent.com/2427715/49078915-460d2a80-f27a-11e8-9aa4-90b3d7c3b695.png)

**Comment by dead-horse** [comment]
没有影响，不用特殊处理

**Comment by atian25** [comment]
dup https://github.com/eggjs/egg/issues/3238
