### ISSUE TITLE
因为flatmap-stream导致安装失败

### ISSUE THREAD

**Issue by weihongyu12** [eggjs/egg#3243]
* **Node Version**: 10.13.0
* **Egg Version**: 2.14.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: CentOS 7.4 64bit
* **Mini Showcase Repository**:

![default](https://user-images.githubusercontent.com/19792747/49083158-cb96d780-f286-11e8-8ccb-576352a7d9bf.png)

flatmap-stream的事件相信已经听说了，目前这个包已经被npm删除了，并因此导致安装失败

**Comment by whxaxes** [comment]
是因为你锁版本了，把 yarn.lock 或者 package-lock.json 删掉重装依赖即可
