### ISSUE TITLE
模型定义mysql  comment 表注释无效。

### ISSUE THREAD

**Issue by chu-han** [eggjs/egg#3244]
```
module.exports = app => {
    const Model = app.model.define('demo', {}, {
        tableName: 'demo'
    }, {
        comment: 'demo'

    })
    return Model
}
```

**Comment by spitWind** [comment]
你走错地方了.   应该区 sequelize git 提

**Comment by thonatos** [comment]
@spitWind 

`sequelize` 最新的正式版本是 `v4.41.2`，引入 `beta` 版本是非常不负责任的做法。

**Comment by chu-han** [comment]
表注释这里是我自己写错了，重新看文档后发现正确写法是这样的。字段注释，只能自己改sequelize代码了。
module.exports = app => {
    const Model = app.model.define('demo', {}, {
        tableName: 'demo'，
        comment: 'demo'
    })
    return Model
}

**Comment by dead-horse** [comment]
> 感觉他们这样子 强依赖核心好滑稽~.~

https://github.com/eggjs/egg-sequelize#customize-sequelize

看文档
