### ISSUE TITLE
11月26日爆出的event-stream 加密货币漏洞是否有影响?

### ISSUE THREAD

**Issue by Songkunda** [eggjs/egg#3245]
- event-stream 原作者回应
`https://github.com/dominictarr/event-stream/issues/116`
发现egg 和 nodemon在使用flatmap-stream
https://www.npmjs.com/advisories/737
- 检测是否有引用
```bash
$ npm ls event-stream flatmap-stream -g
/usr/local/lib
├─┬ egg@2.14.1
│ └─┬ egg-cluster@1.22.1
│   └─┬ ps-tree@1.1.0
│     └─┬ event-stream@3.3.6 
│       └── flatmap-stream@0.1.2 
└─┬ nodemon@1.18.6
  └─┬ pstree.remy@1.1.0
    └─┬ ps-tree@1.1.0
      └─┬ event-stream@3.3.6 
        └── flatmap-stream@0.1.2 
```
- 用户目录下检测
```bash
find ~/ -path */node_modules/flatmap-stream/package.json
/// 如果发现yarn下有使用建议清空缓存再升级依赖包
```
- egg 使用了受影响的npm库 是否考虑升级或者替换(3.3.4版本)呢?
  * nodemon 在1.18.7中移除了ps-tree
https://github.com/remy/nodemon/issues/1451
https://github.com/remy/pstree/commit/6d8ac2be9b232386731dba62c87fe861a285448d

**Comment by atian25** [comment]
dup https://github.com/eggjs/egg/issues/3238
