### ISSUE TITLE
前后端分离情况下，开启CORS后的csrf防护办法

### ISSUE THREAD

**Issue by wanghsinche** [eggjs/egg#3246]
hi，谢谢开发者带来egg这个框架，真的很好用！

  但是我在用egg-security时还是遇到了一些问题。根据egg-security的说明，在没有跨域的情况下，csrf token可以用`cookie.get('x-csrf-token')`的方式获取。前端页面发起ajax时，需要把该token添加到请求头部或者query中，发送给后端。后端获取到token后，与存储在cookie或者session中的csrf-token比对，验证请求的有效性。
  
  跨域的时候，虽然设置了withCredentials，请求可以带上cookie发送到后端，但是前端js仍然不能通过`cookie.get('x-csrf-token')`拿到token。 这导致最终csrf验证失败。 此类问题在之前已有多个讨论，如@guzuomuse @tong3jie 和 @roc2539 的issue：[#2470](https://github.com/eggjs/egg/issues/2470)，[#2470](https://github.com/eggjs/egg/issues/2569)，[#1058](https://github.com/eggjs/egg/issues/1058)，[#1000](https://github.com/eggjs/egg/issues/1000)。

  对此，egg给出的意见是在cors场景下关闭csrf，理由是
  > CSRF的所有的校验机制都是为了防止收到不信任的域名页面发出的请求，如果你明确的知道这个域名是可信任的，是不需要走 CSRF 的。例如上面提到的，通过 cors 和 jsonp 方式都可以通过配置校验 referrer 白名单来保证只允许信任域名访问。
  
  > 如果是做 API 服务，建议配置csrf 忽略 json 请求，要求服务调用方必须通过 JSON 格式发起 POST / PUT 等请求。

  然而这样做不能解决csrf问题，原因如下：
  1. cors如果是简单请求，那么只是浏览器会拦截返回的内容，请求还是会被服务器处理。
  2. 检测referrer的办法不可信。负载均衡器，代理都有可能导致服务器获取不到referrer。如果referrer可信我们也就不需要csrf token了。
  3. 不合理的检测方式可能会导致不合法的referrer或者origin被通过。
  4. 利用指定content-type为application/json强制浏览器发起pre-flight请求来防护csrf，相当于依赖浏览器一个并非为了安全原因的特性来实现安全性。而且万一后端同学允许了application/x-www-form-urlencoded的content-type，就会出现问题。

  详细参见owasp的描述： 
[1. Content-Type_Header_Validation](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Content-Type_Header_Validation)
[2. Identifying_the_Target_Origin](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Identifying_the_Target_Origin) 

  结合owas的说法和cors的特性：
  - cors决定了浏览器获取不到恶意域名下发出的跨域请求的内容
  - cors决定了js获取不到不同域下的cookie

  我觉得是不是可以这样处理：
  1. egg同时开启cors和crsf防护
  2. 留出一个接口绕过crsf，比如api/getToken，用于获取token，其他接口都需要通过csrf检验
  3. 前端先用api/getToken获取token，然后接下来的请求header或者query都带上这个token，并设置withCredentials
  
  这样，不在白名单的域名虽然可以请求api/getToken，但获取不到内容，所以也无法得知token，无法通过csrf检测

不知这个思路合不合理呢？

**Comment by popomore** [comment]
你可以关闭 csrf 用 referer 检验。一般大型企业会每个应用都写入这个 token 到 cookie。

**Comment by ZQun** [comment]
@popomore token有办法在 controller 中 ctx.body = token 返回给用户端吗？

**Comment by popomore** [comment]
这样防不了 csrf

**Comment by wanghsinche** [comment]
为什么这样防不了，有场景么

**Comment by dead-horse** [comment]
csrf 的目的是防止跨域请求。cors 的需求是进行跨域请求，所以不要用 csrf 去防开启 cors 的路由。cors 请按照 cors 的方案进行校验（cors origin 设置）

**Comment by ycjcl868** [comment]
cors 的方案进行校验无法防住其它服务端调用服务
