### ISSUE TITLE
sessionid获取不到

### ISSUE THREAD

**Issue by Vcgoyo** [eggjs/egg#3248]
使用egg-redis，egg-session-redis 将session存储在redis中，目前场景需要获取sessionid  ，如果将session的encrypt设置为false后getcookie才能拿到sessionid，encrypt设置为true后getcookie就拿不到了，请问这个有解决方案吗~

**Comment by atian25** [comment]
前端读取 cookie ？

**Comment by Vcgoyo** [comment]
@atian25   不是  在node端  使用ctx.cookies.get(sessionKey)   获取sessionid

**Comment by atian25** [comment]
`ctx.cookies.get(sessionKey, { encrypt: true })`

**Comment by Vcgoyo** [comment]
谢谢  提供session过期事件监听吗 我看 app.on('session:expired') 这些好像没有效果

**Comment by Vcgoyo** [comment]
@atian25

**Comment by atian25** [comment]
看 https://github.com/koajs/session 这里的文档是支持的。你可以研究下它的 test fixture
