### ISSUE TITLE
egg-graphql安装后需要设置app\graphql,否则报错

### ISSUE THREAD

**Issue by huang12zheng** [eggjs/egg#3258]
Node Version: 10
Egg Version: 2
Plugin Name: egg-graphql
Plugin Version:
Platform: windows
info:
Error: ENOENT: no such file or directory, scandir 'C:\Users\80510\eggjs\meng\app\graphql'
    at Object.fs.readdirSync (fs.js:928:18)
    at module.exports.app (C:\Users\80510\eggjs\meng\node_modules\egg-graphql\lib\load_schema.js:14:20)
    at module.exports.app (C:\Users\80510\eggjs\meng\node_modules\egg-graphql\app.js:4:31)
.......
Mini Showcase Repository:
//config\config.default.js
module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + 'a';

  // add your config here
config.middleware = [ 'graphql' ];

  return config;
};

exports.graphql = {
  router: '/graphql',
  // 是否加载到 app 上，默认开启
  app: true,
  // 是否加载到 agent 上，默认关闭
  agent: false,
};

//config\plugin.js
exports.graphql = {
  enable: true,
  package: 'egg-graphql',
};

**Comment by thonatos** [comment]
不配置对应的加载目录，显式抛出异常更容易发现问题。
