### ISSUE TITLE
日志的输出问题

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#3261]
如果没有使用内置的 logger ，而使用 node 自带的 console.log 日志会输入到  master-xxx上面对的吧。
有方法 直接将 console.log 输出到 对应的 logs/xxxx/master-xxx 文件下么？
我想通过 拿到文件 fd 直接 时时查看 线上环境的 日志。观察 pm2 的 实现是 有一个 bus 截获了 文件句柄。
是否可以通过 改造 egg-scrip 实现，但是我观察 里面只能拿到 master-xxx 的句柄，是否意味着我想实现 类似于  pm2 logs 的功能只能 hook eggjs 框架的  logger 了呢。

**Comment by thonatos** [comment]
## Console

> A global console instance configured to write to process.stdout and process.stderr. The global console can be used without calling require('console').

- https://nodejs.org/api/console.html

## process.stdout

> The process.stdout property returns a stream connected to stdout (fd 1). It is a net.Socket (which is a Duplex stream) unless fd 1 refers to a file, in which case it is a Writable stream.

- https://nodejs.org/api/process.html#process_process_stdout

综上，重定向 `console.log` 输出可选方案：

```js
const access = fs.createWriteStream('/var/log/node/api.access.log');
process.stdout.write = process.stderr.write = access.write.bind(access);
```

**Comment by buzai** [comment]
@thonatos thank u
