### ISSUE TITLE
RFC: cluster-client 支持多 subscribe 方法

### ISSUE THREAD

**Issue by killagu** [eggjs/egg#3263]
在某些环境下，可能需要订阅不同类型的数据，举个例子：
注册中心客户端需要订阅服务的地址和配置。

有两种方法实现:
1. 实现两个不同的订阅方法
   * subscribeAddress({ dataId })
   * subscribeConfig({ dataId })
1. 实现一个订阅方法，通过不同的类型来区分
   * subscribe({ dataId, type})

方法 1 需要修改 cluster-client 支持定义多个 subscribe 方法。

方法 2 需要 dataClient 在实现中通过 type 来区分订阅的到底是什么信息。这样可以不用修改 cluster-client，在新增订阅信息时，也不用新增接口。

我比较倾向于方法 1
* 这样的方法定义可以明确的知道这个方法究竟订阅的是什么信息
* subscribe， invoke，oneway 都是调用类型的一种，调用类型的抽象应该保持在 cluster-client 这一层，而不应在 APIClient 这一层上透出，APIClient 上暴露的接口应该有明确的含义。
* 在 cluster-client 中，invoke，oneway 都是可以定义多个方法的，subscribe 只能定义一个，不免有些奇怪。

**Comment by popomore** [comment]
感觉这个属于 api client 的封装，这里只实现订阅模式的通讯，具体怎么实现是由自己决定的。

如果按  1 实现，那 invoke 是否也会有多种？

**Comment by gxcsoccer** [comment]
> 感觉这个属于 api client 的封装，这里只实现订阅模式的通讯，具体怎么实现是由自己决定的。

+1

**Comment by gxcsoccer** [comment]
主要是方案1 开了这个口子，以后遇到类似的需求还要再加方法，对于 dataclient 来说 api 还是尽量收敛点会比较好

**Comment by gxcsoccer** [comment]
apiclient 可以根据各个 sdk 的具体需求封装更友好的 api

**Comment by popomore** [comment]
@killagu 这样可以在 dataclient 的基类做个约定，比如按照 type 来分方法，那就在基类里面定义 subscribe 会根据 type 来分别调用对应的方法，不一定需要修改 cluster-client。
