### ISSUE TITLE
Egg plugin , migration from Single Instance to Multiple Instances

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3273]
As you know , according to https://eggjs.org/en/advanced/plugin.html#application-layer-usage-case

I we have Single Instance we can access database through `app.mysql` directly , for Multiple Instances we use `app.mysql.get('db1')` 

What it we heavily uses **Single Instance** approach and after month of development we need another instance , for just a line!!! Must we change all  `app.mysql` directly usage?

**Comment by dead-horse** [comment]
```js
// app.js
app.anotherMysql = app.mysql.get('another');

// replace all app.mysql to app.defaultMysql
app.defaultMysql = app.mysql.get('default');

// no need to change your code
app.mysql = app.mysql.get('default');
```
