### ISSUE TITLE
How to send buffer to frontend?

### ISSUE THREAD

**Issue by JarvisQJ** [eggjs/egg#3274]
使用ctx.body=bufferdata，发送数据到前端时，buffer被转成了这样的结构
{type:buffer,data:[80,
            75,
            3,
            4,
            10,
            0,
            0,
            0,
            8,
            0,
            53,
            65,
            132,
            77,
            251,
            249,
            115,
            115,
            76,.....]}
前端使用new Blob(bufferdata)时，无法转换。
想知道到怎么解决。
场景是，使用exceljs包做Excel导出

**Comment by JarvisQJ** [comment]
`//config/excel.js
  exports.buildExcel = (data, columns) => {
  const workbook = new Excel.Workbook();
  const worksheet = workbook.addWorksheet();
  worksheet.columns = columns;
  worksheet.addRows(data);
  // 这里workbook.xlsx.writeBuffer()返回promise对象，所以外部调用需要await
  return workbook.xlsx.writeBuffer();
};
`
`//controller/operate.js
async purchaseSelect() {
    const {ctx, service} = this;

    ctx.validate({
      is_export: 'int',
      id_string: {type: 'string', required: false},
      day_num: {type: 'int', required: false},
      max_times: {type: 'int', required: false},
      min_times: {type: 'int', required: false},
      max_purchase: {type: 'int', required: false},
      min_purchase: {type: 'int', required: false},
      product_type_code: {type: 'int', required: false},
      orderBy: ['username', 'order_moneys', 'order_counts', 'order_date'],
      order: ['DESC', 'ASC'],
      pageIndex: 'int',
      pageSize: 'int'
    }, ctx.query);

    const result = await service.operate.purchaseSelect(ctx.query);
    if (ctx.query.is_export) {
      // ctx.set('Content-Type', 'application/vnd.openxmlformats');
      // ctx.set('Content-Disposition', "attachment;filename*=UTF-8' '" + encodeURIComponent('afile666') + '.xlsx');
      const fileStream = await ctx.helper.buildExcel(result.rows, excelInfo.purchaseSelect.columns);
      console.log('fileStream', fileStream)
      ctx.body = fileStream;
    } else {
      ctx.body = result;
    }
  }`

**Comment by JarvisQJ** [comment]
https://github.com/JarvisQJ/buffer-demo.git
这是最小可复现代码

**Comment by killagu** [comment]
@JarvisQJ  提供的代码跑不起来。不能复线所说的问题。

**Comment by dead-horse** [comment]
http 是基于字符串的协议，不支持直接传递 buffer，buffer 会被 JSON 序列化成你看到的内容

**Comment by whxaxes** [comment]
@JarvisQJ  你可以将 buffer 转成 base64 的字符输出到前端，前端再将 base64 字符转成 arraybuffer 再塞到 Blob 中。

buffer to base64 in node

```js
buf.toString('base64')
```

convert base64 to arraybuffer

```js
function _base64ToArrayBuffer(base64) {
    var binary_string =  window.atob(base64);
    var len = binary_string.length;
    var bytes = new Uint8Array( len );
    for (var i = 0; i < len; i++)        {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}
```

**Comment by atian25** [comment]
https://blog.csdn.net/youyouwoxing1991/article/details/83000530

自己参考下吧。你是 header 没配置对，需要去了解下 HTTP 协议。

**Comment by JarvisQJ** [comment]
> https://blog.csdn.net/youyouwoxing1991/article/details/83000530
> 
> 自己参考下吧。你是 header 没配置对，需要去了解下 HTTP 协议。

这篇文章看过了，也试过按照他的设置header，还是走不通

**Comment by atian25** [comment]
你给的最小可复现代码库，根本没有这段 header 的配置。

**Comment by whxaxes** [comment]
@atian25  他的 demo 里是异步拿 excel 放到前端用 FileSaver 来下载的...怎么设 header 都没用的...

**Comment by whxaxes** [comment]
@JarvisQJ 如果你要按照你 demo 里用异步来下载，就用我上面说的 base64 的方法，否则就不要用异步

**Comment by atian25** [comment]
。。。

那就是另一个问题了，跟 egg 关系不大，要学会二分排除法。

可以直接手动生成一个 excel 文件，放到 public 目录下，然后研究清楚前端如何对一个 excel 的 url 实现前端 FileSaver 保存。

**Comment by JarvisQJ** [comment]
> 你给的最小可复现代码库，根本没有这段 header 的配置。

因为这个试过，还是不行，所以就把最原始的代码发上去了

**Comment by JarvisQJ** [comment]
```
      const Excel = require('exceljs');
      const workbook = new Excel.Workbook();
      const worksheet = workbook.addWorksheet('report');
      worksheet.columns = excelInfo.purchaseSelect.columns;
      worksheet.addRows(result.rows);
      ctx.response.attachment(excelInfo.purchaseSelect.filename);
      ctx.status = 200;
      await workbook.xlsx.write(ctx.res);
      ctx.res.end();const Excel = require('exceljs');
      const workbook = new Excel.Workbook();
      const worksheet = workbook.addWorksheet('report');
      worksheet.columns = excelInfo.purchaseSelect.columns;
      worksheet.addRows(result.rows);
      ctx.response.attachment(excelInfo.purchaseSelect.filename);
      ctx.status = 200;
      await workbook.xlsx.write(ctx.res);
      ctx.res.end();
```
后端这样，然后前端直接打开新窗口，文件会自动下载下来
@whxaxes 最后这样做的
谢谢大家帮忙
