### ISSUE TITLE
tar包软连接丢失

### ISSUE THREAD

**Issue by XaviLv** [eggjs/egg#3275]
你好，我们准备部署到docker上，在本地测试（安装 - 编译 - 打包 - 解压 - 运行服务）都通过，但是部署到生产环境是就一直无法启动。后来查出来，可能是node_modules/.bin/里的软连接丢失导致的，请问这个该怎么处理啊~~~~~ 

本地测试：
![image](https://user-images.githubusercontent.com/11363902/49433110-22069780-f7ec-11e8-9ea0-dfc76609d875.png)

部署的tar包解压后：
![image](https://user-images.githubusercontent.com/11363902/49433155-3f3b6600-f7ec-11e8-8113-fe82e992037e.png)

**Comment by atian25** [comment]
tar 打包参数问题，看下 tar 文档。

**Comment by XaviLv** [comment]
难道不是 tar czvf xxxx.tar.gz .   ??

**Comment by atian25** [comment]
你现在是软链被打包为硬链接了。这跟 egg 关系不大，或者是跟 Node 也关系不大。
可以自己搜下 tar 的文档。
