### ISSUE TITLE
Support server-rendered React

### ISSUE THREAD

**Issue by afc163** [eggjs/egg#328]
like https://github.com/zeit/next.js/

**Comment by popomore** [comment]
现在搞的是这个 https://github.com/eggjs/egg-view-react

**Comment by shepherdwind** [comment]
这个还用 babel-registry 了，https://github.com/eggjs/egg-view-react/blob/master/test/fixtures/apps/view-react-test/app/controller/test.js ，这样不好吧

**Comment by popomore** [comment]
额，单元测试，不然没法跑
Eward Song <notifications@github.com>于2017年2月11日 周六20:28写道：

**Comment by wangking873** [comment]
建议出个egg-view-next

**Comment by Tomatoo** [comment]
egg-next看到有人写了一个`egg-next`来做这个事情

**Comment by MinJieLiu** [comment]
强烈建议使用 `next.js` 作为 `react` 渲染方案😘，是因为作为 `view` 使用 `react` 没有如 `ejs` 那样简单。

前端构建都是一个复杂的过程。而 `next.js` 已经把相应的坑踩遍，两者搭配起来应该更好。

如果单独写一个 `egg-view-react`。那又有什么意义呢？那样又要重新踩一遍坑，不容易适应各种需求，而且迟迟不能稳定。

**Comment by atian25** [comment]
之前 next.js 1.x 的时候，好像对 koa 的支持不好，要 hack 的方式，现在不知道怎么样了。

可以单独写个 `egg-nextjs`

**Comment by dead-horse** [comment]
我前一阵子研究 next.js 的时候还是不支持 koa 的，现在 koa 接入 next 都是通过设置 `ctx.responed = false` 后交由 next.js 处理响应，这个模式在 koa（egg） 下会导致很多中间件失效。

**Comment by hubcarl** [comment]
基于Egg + React + Webpack3/Webpack2 多页面和单页面服务端渲染同构工程骨架项目: https://github.com/hubcarl/egg-react-webpack-boilerplate

**Comment by likeswinds** [comment]
https://github.com/nuxt-community/koa-template
墙裂建议

**Comment by djyde** [comment]
Hi, I am working on https://github.com/djyde/serlina and it Egg binding https://github.com/serlina-community/egg-serlina I think this is the best serverside-rendering solution for Egg application!

**Comment by atian25** [comment]
@djyde  cool~ could add it to https://github.com/eggjs/awesome-egg ?

**Comment by fengmk2** [comment]
@djyde serlina look beautiful!

**Comment by akshayKrSingh** [comment]
Hi,

I've been working on a **_EggJS plugin_** that integrates **_NextJS_**. [egg-frost](https://github.com/akshayKrSingh/egg-frost)

I have been able to set this plugin and render pages using **NextJS** render engine (in development mode).

I hope it helps. Feedback is always welcome 😄

**Comment by RluLee** [comment]
> Hi,
> 
> I've been working on a **_EggJS plugin_** that integrates **_NextJS_**. [egg-frost](https://github.com/akshayKrSingh/egg-frost)
> 
> I have been able to set this plugin and render pages using **NextJS** render engine (in development mode).
> 
> I hope it helps. Feedback is always welcome 😄

Read the document but don't use

**Comment by yangchongduo** [comment]
@dead-horse 给个导致很多中间件失败的demo ，如果导致了你怎么处理的？
