### ISSUE TITLE
eggjs项目部署centos后，打开的时候特别慢，我服务器上面还部署一个禅道，禅道基本是秒开的

### ISSUE THREAD

**Issue by wxbing1207** [eggjs/egg#3280]
我在/root/logs  tail -f 输出的这句话

2018-12-06 05:07:03,112 WARN 30487 A client (**.***.***.***:32996) error [HPE_INVALID_METHOD] occurred: Parse Error

**Comment by atian25** [comment]
『慢』具体指啥？ 一条 Request 慢？通过 Alinode 分析下慢请求看看。

至于你那个报错，不要锁版本重新升级下依赖即可。

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by atian25** [comment]
不要挤牙膏的交流。

怎么个慢，学会分析和描述问题，否则没法解答。

**Comment by wxbing1207** [comment]
> 不要挤牙膏的交流。
> 
> 怎么个慢，学会分析和描述问题，否则没法解答。

可以打开进去，但是需要长达1分钟才能打开主页，我的项目也是安装egg的目录规范建的

**Comment by wxbing1207** [comment]
> > 不要挤牙膏的交流。
> > 怎么个慢，学会分析和描述问题，否则没法解答。
> 
> 可以打开进去，但是需要长达1分钟才能打开主页，我的项目也是安装egg的目录规范建的

您可以试试打开http://140.143.228.135

**Comment by okoala** [comment]
![image](https://user-images.githubusercontent.com/2127199/49583331-cc202400-f992-11e8-84c8-9faff21fa7ac.png)
你这资源也太大了吧，还不开 gzip

**Comment by okoala** [comment]
![image](https://user-images.githubusercontent.com/2127199/49583486-549ec480-f993-11e8-9ba1-6eb56cf53b95.png)

可以说很惨烈了~

**Comment by atian25** [comment]
性能问题，自己分析吧。

- 尽可能的减少沟通成本，避免 [『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)
- 绝大部分情况下，通过 `egg-init --type=simple` 来初始化个最小可复现仓库，这个过程中你就会自己发现问题了，这是一种非常高效的问题定位方式。
- 如果还不能解决，此时直接提交到你的 GitHub ，我们来跟进，就会非常的高效，避免挤药膏似的交流。
- 问题解决后，及时关闭 issue，并把解决方式同步进来，方便后来人。issue 本身就是一种非常好的可沉淀的交流方式。
