### ISSUE TITLE
修改文件后 work reload 但请求pendding，类似#1325

### ISSUE THREAD

**Issue by sourth-rain** [eggjs/egg#3281]
执行定时任务的过程中报了这个错
![image](https://user-images.githubusercontent.com/19897779/49570459-9f0f4980-f971-11e8-8158-9e46c514d012.png)
之后an zhao按照#1325的方法，解决了new work fork的问题
![image](https://user-images.githubusercontent.com/19897779/49570518-cfef7e80-f971-11e8-9733-b9ed612f70f0.png)
下面时reload成功的截图
![image](https://user-images.githubusercontent.com/19897779/49570575-fca39600-f971-11e8-9854-d8878ee71d74.png)

但是，定时任务却不能恢复继续执行了，中断了，请问该怎么解决呢

**Comment by atian25** [comment]
提供可复现代码库和操作步骤？

重启的是 worker，调度是在 agent 的，后者没重启，不应该会有问题的

**Comment by sourth-rain** [comment]
复现，就是使用schedule跑一个写文件到项目目录的定时任务，就会出现work重启的情况了

**Comment by sourth-rain** [comment]
@atian25

**Comment by atian25** [comment]
你的问题到底是什么？是写入文件后，任务还没完全执行完成，就重启？ 那是因为 egg-development 监控到本地开发文件变更，就重启了啊。这个你不需要可以配置 ignore。

**Comment by sourth-rain** [comment]
是的，任务还没完全执行完成，就重启。重启结束后，任务没有再继续了，我说的是如果我不ignore，还有什么方式可以解决呢

**Comment by atian25** [comment]
肯定不行啦，本地开发肯定是监控到文件变更就重启了。

你这问题跟 schedule 没关系，是你代码的逻辑设计问题。

**Comment by sourth-rain** [comment]
不好意思，可能我没表述清楚。我的意思是定时任务执行过程中，按需求会不断的生成新的文件，再不ignore的情况下，生成第一个文件的时候就重启了，后续的还没得生成，任务就中断了。

**Comment by atian25** [comment]
1. 自动重启是开发期行为，线上不存在的
2. 为什么不 ignore，写入文件后要重启？

**Comment by sourth-rain** [comment]
其实ignore就解决了。。。我只是想看看，开发期不ignore的情况下是否还有其他途径。。。，你忙吧，可以不回答了，老乡
