### ISSUE TITLE
关于egg在不同系统的调试问题

### ISSUE THREAD

**Issue by 4176244** [eggjs/egg#3283]
我用了egg的例子,发现基本上在Window环境调试,打断点没有问题,但是在centos下,有些可以,有些就不行.不知道为什么'

我用的是vscode,用的就是vscode-egg插件.

**Comment by 4176244** [comment]
我说的是在vscode里面,不是用浏览器调试.

**Comment by atian25** [comment]
先学习下 Node 断点调试的知识吧，Egg 跟 Node 的调试没啥区别，只是多了几个进程而已，需要一个个 attach 。

**Comment by 4176244** [comment]
> 先学习下 Node 断点调试的知识吧，Egg 跟 Node 的调试没啥区别，只是多了几个进程而已，需要一个个 attach 。

我写了3年node.js.我要的不是普通的浏览器调试.我的服务器框架30多个子进程.你没有明白我的意思.

**Comment by 4176244** [comment]
> 先学习下 Node 断点调试的知识吧，Egg 跟 Node 的调试没啥区别，只是多了几个进程而已，需要一个个 attach 。

你没有明白我的意思.我要表达的意思是同一个程序调试,在Window下可以,在centos下不可以,用的都是阿里的例子.

**Comment by atian25** [comment]
就是因为是同一份代码，所以才更可能是操作问题或系统问题，需要自己根据 Node Debug 的知识去排查下。

Egg 断点这块没有做什么事的，就是传递了 --inspect 给各个进程而已。跟普通的 Node 没有任何区别。

如果你 Attach 不上的时候，就需要看下进程输出的信息，如 Debuging at xxx 之类的，然后去分析为何 attach 不上。

**Comment by 4176244** [comment]
![egg](https://user-images.githubusercontent.com/13817239/49629130-cffb8700-fa22-11e8-9060-07f248442e83.jpg)
![egg](https://user-images.githubusercontent.com/13817239/49629133-d1c54a80-fa22-11e8-99be-cd42b75d4007.jpg)

**Comment by 4176244** [comment]
我晕,又起来了,好了.这是什么鬼?什么也没有改.

**Comment by atian25** [comment]
停住很正常啊，因为你是 `--inspect-brk` 啊：
- master 先启动，在第一行会停住，需要你 attach master，才会往下走
- 接着 master 启动 agent，也是在第一行停住，需要 attach agent 才会往下走
- 最后 agent 启动完成后，worker 才开始启动，一样也是在第一行停住，需要 attach agent 才会往下走

如上，就是我说的：『先学习下 Node 断点调试的知识吧』

至于为什么文档和大部分时间你都没感知到要 attach 这么多次？那是因为 VSCode 帮你搞定了啊，要不就是开启了 autoAttachChildProcesses 要不就是开了 auto attach 。
