### ISSUE TITLE
egg-sequelize 手动建立中间表无法关联问题

### ISSUE THREAD

**Issue by xumjs8623** [eggjs/egg#3284]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我有一个文章表 一个标签表 还有一个文章标签中间表，我知道sequelize可以建立多对多关系，但是我想手动建立这张中间表，可是创建完model之后，sequelize的方法都不能用。但是其他的表操作起来没有任何问题

**Comment by xumjs8623** [comment]
![image](https://user-images.githubusercontent.com/12467615/49682938-c55ef180-faf7-11e8-8854-ba7fed431cf8.png)
还是要耐心看文档

**Comment by Richard-Choooou** [comment]
@xumjs8623 请问你后来是怎么解决的？
