### ISSUE TITLE
RFC: Guardian 

### ISSUE THREAD

**Issue by killagu** [eggjs/egg#3286]
# Guard RFC

### Validator
验证请求是否应该通过，比如限流，安全验证等。

```ts
interface IValidator {
  async validate(ctx): boolean;
}
```

基于不同的守护模式，可以有不同的validator

例如基于 QPS 的 validator
```ts
abstract class AbstractQPSValidator implements IValidator {
  // convert request to counter map key
  abstract convertRequest(ctx): string;
  counterMap: Map<string, number>; // <key, requestCount>
  thresholdMap: Map<string, number>; // <key, threshold>
  async validate(ctx): boolean {
    const key = this.convertRequest(ctx);
    if (!this.thresholdMap.has(key)) {
      return false;
    }
    const count = this.counterMap[key] || 0;
    const threshold = this.thresholdMap.get(key);
    this.counterMap[key] = ++count;
    return count > threshold;
  }
}
```

基于外部安全服务的 validator
```ts
abstract class SecurityValidator implements IValidator {
  assembly(ctx): Request;
  doRequest(req: Request);
  async validate(ctx) {
    const req = this.assembly(ctx);
    return this.doRequest(req);
  }
}
```

### Interrupter
对需要拦截的请求进行处理，比如对 ajax 请求，抛出 JSON，对 RPC 请求，抛出错误。或者新的守卫模型上线时只做日志处理。

```ts
interface IInterrupter {
  interrupt(ctx, next);
}
```

可以实现 LogInterrupter, JSONInterrupter, ErrorInterrupter 等。

### Rule
rule 是 validator 和 interrupter 的聚合。执行具体的验证和中断。

```ts
interface IRule {
  private validator: IValidator;
  private interrupter: IInterrupter;
  private type: Type;

  /**
   * @params {Context} ctx
   * @return {Promise<Boolean>} should interrupt request
   */
  async validate(ctx): Boolean;

  /**
   * @params {Context} ctx
   * @params {Function} next
   * @return {Promise}
   */
  async interrupt(ctx, next);
}

enum Type {
  pre; // 请求处理前执行
  suf; // 请求处理后执行
}
```

### Guardian
guardian 是一组 rule 的集合。
```
interface IGuardian {
  addRule(rule: IRule);
  guard(ctx, next);
}
```

#### Guard 流程
![image](https://user-images.githubusercontent.com/6897780/49693734-306efd80-fbb6-11e8-9ba4-3a4d0f387d84.png)

#### 是否中断流程
![image](https://user-images.githubusercontent.com/6897780/49693721-ae7ed480-fbb5-11e8-8dcc-430c69eaf307.png)

## Plugin: egg-guardian
基础插件
* app.guardian
* ruleLoader
* guardianMw

不同的请求模型可能需要不同的中间件实现，可以在独立的插件实现，然后注入到中间件配置中。
比如 sofa-node-rpc, 实现了一个 rpcGuardianMw, 在 config.rpcMws 中注入这个中间件即可。

**Comment by popomore** [comment]
1. Interrupter 只需要做处理的话，应该不需要 next 了？也改成 context class？
1. 关系可能还要理一下，现在除了 egg-guardian 还有拦截方和 rule 的提供方
   - 拦截方是中间件的开发者，比如 http 中间件（框架默认）、rpc、socketio 等等，他们会调用 guard 来判断是否需要拦截。
   - rule 的提供方是有拦截需求的插件，比如限流、安全等等，他们通过 rule 的形式来告知拦截方是否需要拦截。
   从上面的关系看是多对多的，比如限流要在 http 和 rpc 拦截，那么限流的 rule 需要指定要在哪个拦截者，从 RFC 看应该是 type 这个字段。
1. app.guard 需要保证拦截方都使用洋葱圈模型。
1. 前置后置是不是做个区分，让 rule 的提供方明确是前置还是后置。

**Comment by killagu** [comment]
> Interrupter 只需要做处理的话，应该不需要 next 了？也改成 context class？

考虑到 LogInterrupter 这种只打日志的，next 由 LogInterrupter 来执行。

> 关系可能还要理一下，现在除了 egg-guardian 还有拦截方和 rule 的提供方
拦截方是中间件的开发者，比如 http 中间件（框架默认）、rpc、socketio 等等，他们会调用 guard 来判断是否需要拦截。
rule 的提供方是有拦截需求的插件，比如限流、安全等等，他们通过 rule 的形式来告知拦截方是否需要拦截。

* egg-guardian 中可以提供一些 interrupter。
* rule 的提供方应该指的是 rule 的 validator 这一部分，这个应该在 core 中做，比如说一个 qps-guardian，实现了基于 QPS 的 validator。
* 在 egg 插件，例如 egg-qps-guardian 中可以将 validator 和 guardian 组合称一条 rule，注入到 app.guardian 中。

> 从上面的关系看是多对多的，比如限流要在 http 和 rpc 拦截，那么限流的 rule 需要指定要在哪个拦截者，从 RFC 看应该是 type 这个字段。不过看如何通过声明式的方式，可以查到框架里具体有哪些拦截方。

type 这个字段指的是 rule 是前置还是后置。
提供给不同的拦截方式，应该使用多实例模式，例如在 egg-qps-guardian 可以
```js
const httpGuardian = app.guardian.get('http');
if (httpGuardian)
  httpGuardian.addRule(qpsHTTPRule);
const rpcGuardian = app.guardian.get('rpc');
if (rpcGuardian)
  rpcGuardian.addRule(qpsRPCRule);
```

> app.guard 需要保证拦截方都使用洋葱圈模型。

HTTP，RPC 这块没啥问题。如果有其他的模型需要接入，实现不同模型的中间件即可。

**Comment by popomore** [comment]
> 考虑到 LogInterrupter 这种只打日志的，next 由 LogInterrupter 来执行。

这里是说 validate 拦截后，interrupter 还可以继续吗？我觉得可以在 rule 上加一个字段表明非拦截模式，这样可以不调用 validate 直接进入 interrupter。

> 实现不同模型的中间件即可。

比如 express 的前置和后置就需要 monkey patch 的方式，而洋葱圈才有 next()

**Comment by popomore** [comment]
我想了下，这个和 middleware 其实是一个东西。

**Comment by killagu** [comment]
考虑了一下中间件模式，设计上进行了一些改造。

validator 设计为有两个方法，分为前置校验和后置校验。
```ts
interface IValidator {
  /**
   * 前置校验
   * @params {Context} ctx -
   * @return {Boolean} 请求是否可以通过
   */
  preValidate(ctx): boolean;
  /**
   * 后置校验
   * @params {Context} ctx -
   * @return {Boolean} 请求是否可以通过
   */
  sufValidate(ctx): boolean;
}
```

interrupter 的 interrupt 方法增加返回值，代表请求是否应该中断还是继续执行
```ts
interface IInterrupter {
  /**
   * 进行中断请求的一些操作
   * @return {boolean} 请求是否中断
   */
  interrupt(ctx): boolean
}
```

rule 更贴近中间件设计，将 interrupt 和 validate 方法组合为 ruleMw。如果有非洋葱圈模型的请求方式，需要直接使用 validator 和 interrupter 进行组合。
```ts
interface IRule {
  name: string;
  private validator: IValidator;
  private interrupter: IInterrupter;
  ruleMw(ctx, next);
}
```

![image](https://user-images.githubusercontent.com/6897780/49710197-016a9180-fc73-11e8-935b-be9da2426af6.png)

guard 仍然透出的是一个中间件方法，只是内部实现换为使用 compose 拼接 rule 提供的 ruleMw。
加上前插入和后插入。

```ts
interface IGuardian {
  addRule(rule: IRule);
  insertRuleBefore(rule: IRule, before: string);
  insertRuleAfter(rule: IRule, before: string);
  guardMw(ctx, next);
}
```

**Comment by killagu** [comment]
https://github.com/eggjs/egg-guardian
