### ISSUE TITLE
中间件重复使用的问题

### ISSUE THREAD

**Issue by xuezier** [eggjs/egg#3287]
看了下egg-core的loader
https://github.com/eggjs/egg-core/blob/df1cc5bd5b0764491e15a31932b357115371cf00/lib/loader/mixin/middleware.js#L63
![image](https://user-images.githubusercontent.com/7692708/49715026-19014480-fc8a-11e8-8e4d-c1f030450673.png)
似乎作者的想法是一个全局中间件只能被挂载一次，如果我一个中间件想多次挂载的话怎么做？
这里考虑的出发点是什么？能否周知学习一下？

**Comment by atian25** [comment]
什么场景下需要多次挂载？

**Comment by xuezier** [comment]
比如我有一个多层的策略检测
```js
// policy.js
module.exports = ({ policy = '', match = '*' }) => {
    if(match === '*') {
        return async(ctx, next) => {
            await ctx.authoricate(policy);
            await next();
        };
    }
    else {
        return async(ctx, next) => {
            if(ctx.match(ctx.request.url, match)) {
                await ctx.authoricate(policy);
            }

            await next();
        };
    }
};
```
我们希望不同的policy能在不同的match下实现。
```js
// config.default.js
config.middleware = ['policy', 'policy'];
config.policy = multiConfig([
    {policy: 'base'},
    {policy: 'user', match: '/user'}
])
```
这里能够提供一个数组实现就棒棒了，考虑到传入的参数可能是数组，所以如果是多个配置，可以提供一个multiConfig方法来实现

**Comment by atian25** [comment]
- 你把你的这个类，放到 lib 下，然后 app/middleware 里面放置多个文件，都引入它，这是一种方式。
- 另一种方式，不通过 config 去挂载它，而是在 app.js 里面读取某个配置，再自动插入到 coreMiddleware 中
- 可以参考下 egg-security 有类似的做法。

**Comment by xuezier** [comment]
我有时在想，同一种功能提供多种实现，会不会造成项目解构太过混乱。
我们会约束开发者按照一定的规范去实现项目
但如果有一个开发者忽略了规范，在config挂载了一个middleware，
app.js里面挂载了几个middleware，
router.js里面挂载了几个middleware
balabala。。。。。。
真让人头大。。。。。

**Comment by atian25** [comment]
其实还是不太看明白你们的 policy 为什么会不同的 match，完全是可以只挂载一个，然后你提供插件本身的配置来让他们配置就好了，如 
```js
config.policy = {
  rule: {
    base: { match: '*' },
    user: { match: '/user' }
  }
}
```

不过说到底，还是看你具体的场景吧，一般的原则是『如无必要，勿增实体』，如果没看到很清晰的场景，就不要给用户提供太多的选择，扩展性要适当，没有一次到位的银弹。

**Comment by atian25** [comment]
还有一种方法，通用的开发者直接挂在 config 上
其他的，他们自行在 router 注册：https://eggjs.app/zh-cn/basics/middleware.html#router-%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%B8%AD%E9%97%B4%E4%BB%B6
