### ISSUE TITLE
[RFC] egg error log 默认双写

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#3288]
## 背景

之前默认的 egg logger，错误日志都是统一写入到 common-error 。

初衷是好的，但有点反直觉，很多时候，其实开发者期望的是日志双写：

- 写入到 common-error 是为了统一监控和处理错误
- 原日志期望保留，为了保持正确的日志时序，而且可能需要单独分析日志

## ~~进展~~

首先在 https://github.com/eggjs/egg-logger/pull/35 里面把 `redirect(level, logger)` 改为 `redirect(level, logger, { duplicate: true })` 使得可以支持双写。

但因为在 Egg 里面是默认全部 redirect 的，所以如果开发者自定义日志，还需要在 app.js 里面：

```js
  // app.js
  // don't redirect scheduleLogger
  const logger = app.getLogger('scheduleLogger');
  const errorLogger = app.getLogger('errorLogger');
  logger.unredirect('error', errorLogger, { duplicate: true });
```

这样显然不是很友好，因此又在 https://github.com/eggjs/egg-logger/pull/36 （还未合并）里面支持了全局的配置：

```js
config.logger = {
  retainOnRedirect: true,
};

config.customLogger = {
  scheduleLogger: {
    retainOnRedirect: true,
  }
}
```

## ~~需讨论的内容：~~

- Egg 里面默认开启日志双写，按我的理解是不算 breakchange 的，只是多写了一份。
- API 的修改与否：
  - ~~`redirect(level, logger, { duplicate: true })` 改为 `redirect(level, logger, { retain: true })`~~ 干掉，恢复原样。
  - 或者直接支持 `duplicate(level, logger)` 代替上面这个 options，这种方案还要看上一条，是否需要默认开启双写？

## 最终定稿方案

参见 2 楼

- egg-logger 提供 redirect / duplicate 两个方法
- egg 改成默认将 error 级别的错误 duplicate 到 common-error
- 给 logger 增加一个配置项（concentrateError : 'ignore' / 'duplicate' / 'redirect'）用于控制错误日志的集中写入方式，上层框架可以用此配置来保证兼容性。

land at https://github.com/eggjs/egg-logger/pull/38

**Comment by dead-horse** [comment]
我也觉得最开始的需求是为了监控更方便，错误日志全部打印到 common-error ，没有保留在用户期望的日志文件中是有点反直觉的，应该是复制一份到 common-error 并保留一份在原始文件中，也就是 duplicate 的功能。

可以考虑：

1. egg-logger 提供 redirect / duplicate 两个方法
2. egg 改成默认将 error 级别的错误 duplicate 到 common-error
3. 给 logger 增加一个配置项（`concentrateError : null / 'duplicate' / 'redirect'`）用于控制错误日志的集中写入方式，上层框架可以用此配置来保证兼容性。

**Comment by atian25** [comment]
`concentrateError` 这个名字好长。

cc @fengmk2 @popomore 看看 RFC，没啥问题我今天就撸掉它。

**Comment by fengmk2** [comment]
嗯，默认双写吧。应该说是默认同步一份到 common-error。

**Comment by atian25** [comment]
Transport 也不好，只能 duplicate 不能改 redirect，因为 add Transport 是没 LEVEL 的。

另一种解法是：

`logger.duplicate(level, logger, { exclude: [ 'console' ]}`

**Comment by atian25** [comment]
land https://github.com/eggjs/egg-logger/pull/45
