### ISSUE TITLE
egg线上新能监控大家有什么推荐吗?公司不准用alinode这样的第三方服务

### ISSUE THREAD

**Issue by CNYeFeng** [eggjs/egg#3289]
* **Node Version**:8.12.0
* **Egg Version**:2.14.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

如题，egg线上新能监控大家有什么推荐吗?公司不准用alinode这样的第三方服务，有没有什么好用的开源的

**Comment by popomore** [comment]
你要监控什么

**Comment by popomore** [comment]
看看这个 https://prometheus.io/

**Comment by CNYeFeng** [comment]
我要监控 性能， 内存， cpu,  log 等等

**Comment by fengmk2** [comment]
不准用 alinode，然后线上应用出现了 cpu 和内存泄漏，然后怎么办？

**Comment by atian25** [comment]
估计想找个凑合用的，反正老板觉得没价值

**Comment by CNYeFeng** [comment]
正因为是主线业务，老板觉得有价值 才不让用 服务在第三方的 监控。 只允许用 自己搭建的监控 服务

**Comment by CNYeFeng** [comment]
@atian25 并没有，我们公司很重视每一个员工的价值。 因为 业务的特殊性，不方便用 服务在第三方的监控。  我也 很惆怅啊~~~ alinode很好用。
