### ISSUE TITLE
egg-redis 在 ts 中的 interface 不正确

### ISSUE THREAD

**Issue by kasora** [eggjs/egg#3290]
根据 [demo](https://github.com/eggjs/egg-redis/commit/f062dd571ce17f569a65066a95f600e64b3d15c2#diff-060536ad54c4e032fdc50ed80700b8e8R8) 中的配置格式，
例如：
```js
  config.redis = {
    client: {
      port: 6379,          // Redis port
      host: '127.0.0.1',   // Redis host
      password: '',
      db: 0,
    },
  };
```
可以正确加载数据库。
但是在升级到 `egg-redis 2.2.0`后，同样的配置下，虽然数据库连接正常，测试也可以跑过，但是 `npm run tsc` 时会报错卡住 CI。
错误为 
```
  Type '{ client: { port: number; host: string; password: string; db: number; }; }' is not assignable to type 'PowerPartial<EggRedisOptions> | undefined'.

  Type '{ client: { port: number; host: string; password: string; db: number; }; }' is not assignable to type 'PowerPartial<EggRedisOptions>'.
  
  Types of property 'client' are incompatible.
  
  Type '{ port: number; host: string; password: string; db: number; }' is not assignable to type 'ClusterOptions | undefined'.
  
  Object literal may only specify known properties, and 'port' does not exist in type 'ClusterOptions | undefined'.
```

因为在 `egg-redis 2.0.0` 版本中这个配置是可以运行的，所以查看了最新的 commit。

在最新的 [commit](https://github.com/eggjs/egg-redis/commit/f062dd571ce17f569a65066a95f600e64b3d15c2#diff-b52768974e6bc0faccb7d4b75b162c99R8) 里 interface 中 `RedisOption` 是存放在 `config.redis.client.nodes` 中的
根据 interface 填写后，
例如：
```js
  config.redis = {
    client: {
      nodes: [
        {
          port: 6379,          // Redis port
          host: '127.0.0.1',   // Redis host
          password: '',
          db: 0,
        },
      ],
    },
  };
```
显示报错信息
`[egg-redis] 'host: undefined', 'port: undefined', 'password: undefined', 'db: undefined' are required on config`

请问是接口有调整还是我的 `redis` 配置哪里出了问题？

**Comment by whxaxes** [comment]
给个能复现的 repo ，我帮你看一下

**Comment by whxaxes** [comment]
我找到原因了，你在项目下安装一下 `@types/ioredis` 即可解决该问题，这个可以加到 egg-redis 的 deps 中，我晚点提个 PR
