### ISSUE TITLE
我添加了一个中间件代理Proxy请求，前端POST无法响应net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by baiyuze** [eggjs/egg#3291]
我添加了一个中间件代理`Proxy`请求，前端POST无法响应**net::ERR_EMPTY_RESPONSE**。
我关闭了`CSRF`访问，正常GET请求前端可以收到返回，但是POST可以拿到数据。但是culr()收到数据之后，前端就不等待数据响应了报**net::ERR_EMPTY_RESPONSE**

```javascript

      let curlOptions = {};

      curlOptions.method = req.method;
      curlOptions.headers = req.headers; 
      if(req.method.toUpperCase() !== "GET") {
        curlOptions.data = req.body;
        curlOptions.stream = req;
        curlOptions.contentType = 'json';
        curlOptions.dataType = 'json'; 
        curlOptions.timeout = 15000;
      } 
      let testCookie = fs.readFileSync(path.join(process.cwd(), 'app/mocks/cookie.txt'));
      
      if(!curlOptions.headers.cookie) {
        curlOptions.headers.cookie = testCookie;
      }
      try {
        let res = await ctx.curl(reqPath,curlOptions)
        if(res.status == 200) {
          res.data = req.method.toUpperCase() === 'GET' ? res.data.toString("utf8") : res.data;
          // if(reqPath.indexOf('user_info') !== -1) {
          ctx.body = res.data;
        } else {
          ctx.body = res.data.toString("utf8") == '[object Object]' ? res.data : res.data.toString("utf8")
        }

      } catch (error) {
        ctx.body = {
          code: 500, 
          data: null,
          msg: "error",
          success: false
        }
      }

```

查了一天了，也不知道具体是什么问题。。。
请求没有走到`ctx.body`时，用postMan请求就已经停止响应了。

**Comment by baiyuze** [comment]
但是通过`postman`就无法响应
![1fa98edd-5d9c-4f21-99ba-f1be81cd9a07](https://user-images.githubusercontent.com/27543832/49794633-fc8d0700-fd72-11e8-92ce-2eea0098045e.png)

**Comment by popomore** [comment]
代理还是不好写的，可以找个 koa 来用。

**Comment by popomore** [comment]
Egg 支持 koa 中间件的，你可以 fork 一份，或者参考他的写法。

**Comment by atian25** [comment]
我并不是说这 2 个会导致你的这个问题，只是顺手提下。

返回正不正常这个，你只能自己断点跟踪，因为代码是你自己的。或者提供最小可复现仓库

**Comment by atian25** [comment]
你断点都看不出来了，我们远程看不完整的代码片段也没法看啊，除非你给最小可复现仓库。

---
- 尽可能的减少沟通成本，避免 [『如何向开源项目提交无法解答的问题』](https://zhuanlan.zhihu.com/p/25795393)
- 绝大部分情况下，通过 `egg-init --type=simple` 来初始化个最小可复现仓库，这个过程中你就会自己发现问题了，这是一种非常高效的问题定位方式。
- 如果还不能解决，此时直接提交到你的 GitHub ，我们来跟进，就会非常的高效，避免挤药膏似的交流。
- 问题解决后，及时关闭 issue，并把解决方式同步进来，方便后来人。issue 本身就是一种非常好的可沉淀的交流方式。

**Comment by baiyuze** [comment]
嗯嗯，我在看看，如果还是不行，再最小复现试试
