### ISSUE TITLE
egg-mysql 匹配 null 字段

### ISSUE THREAD

**Issue by sskyy** [eggjs/egg#3293]
* **Node Version**:
10.0.0
* **Egg Version**:
2.14.0
* **Plugin Name**:
egg-mysql
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

使用 `this.app.mysql.get`方法时，如果有字段 a 是 null，生成的 sql 代码是：

```
"SELECT * FROM `page` WHERE `a` = NULL"
```

这会导致匹配不到正确的数据，需要生成：

```
"SELECT * FROM `page` WHERE `a` is NULL"
```

**Comment by hacke2** [comment]
我看已经实现了 https://github.com/ali-sdk/ali-rds/commit/0d4d4ab99a7cd655180f22d4d95e3cfef8c8714b
