### ISSUE TITLE
求助：如何使用账号/密码配合egg-passport-local登录？

### ISSUE THREAD

**Issue by futabachan** [eggjs/egg#3294]
项目是使用 egg-init . --type=simple 建立的，没有 app.js 这个文件。
按照eggjs官网的说明安装和启用了 egg-passport 和 egg-passport-local 插件。
看过 https://github.com/eggjs/egg-passport-local 的README，可惜没有理解账号/密码验证这一步应该插到什么位置。
希望能有一个简单的示例。

**Comment by atian25** [comment]
- https://github.com/eggjs/examples/blob/master/passport/README.md
- https://github.com/eggjs/egg-passport-local/blob/master/test/fixtures/apps/passport-local-test/app.js

账号的其实可以不用这个插件，直接自己写个 Controller 就完了，没必要绕一圈

**Comment by thonatos** [comment]
1. `egg-passport-local` 是按照`Passport.js` 规范实现的一个插件
2. 使用中，@atian25 已经讲过了，可以不走这一套，添加一个`controller`直接处理`POST`过来的表单数据就可以了；当然了，你可以遵循标准，示例里不明白的地方具体指什么？

**Comment by futabachan** [comment]
> 
> 
>     1. `egg-passport-local` 是按照`Passport.js` 规范实现的一个插件
> 
>     2. 使用中，@atian25 已经讲过了，可以不走这一套，添加一个`controller`直接处理`POST`过来的表单数据就可以了；当然了，你可以遵循标准，示例里不明白的地方具体指什么？

感谢您的解答！

因为没有使用过Passport.js，加之egg-passport的例子中没有看到 egg-passport-local的部分。
既然目前用不上……暂且关闭这个了。

**Comment by hongz1125** [comment]
passport这个教程写的。。。 没看懂

**Comment by hengkx** [comment]
的确看不懂

**Comment by jiengsad** [comment]
文档和demo真垃圾

**Comment by kurilee** [comment]
因为看不懂文档过来的 +1

**Comment by faithleysath** [comment]
难绷，2025回来考古，文档确实不行
