### ISSUE TITLE
egg ctx.cookies.set 后浏览器返回的response header中看不到set-cookie，但是postman模拟请求却可以

### ISSUE THREAD

**Issue by asiainfoliwei** [eggjs/egg#3296]
* **Node Version**:v9.0.0
* **Egg Version**:2.2.1
* **Plugin Name**:cors, security
* **Plugin Version**: 2.1.1

 我post请求之后调用egg的内置cookie设置cookie，代码如下：
![image](https://user-images.githubusercontent.com/24582028/49866367-89eb5c80-fe42-11e8-9dd3-c17674bc8764.png)

浏览器中查看返回的response中没有setcookie，但是postman模拟请求的时候返回的response却有setcookie，是不是因为跨域的原因导致浏览器没有返回set-cookie

![image](https://user-images.githubusercontent.com/24582028/49866341-70e2ab80-fe42-11e8-94f2-9aea17e0d8ea.png)
跨域和cookie的配置如上

浏览器返回的response header和postman 模拟请求返回的response header分别如下
![image](https://user-images.githubusercontent.com/24582028/49866519-f8c8b580-fe42-11e8-8100-ddb6f99345c6.png)
![image](https://user-images.githubusercontent.com/24582028/49866587-24e43680-fe43-11e8-9633-ae3feef0f8f6.png)
如何能让浏览器返回的请求中也有set-cookie？ 真心求解

**Comment by fengmk2** [comment]
请提交最小可以复现问题的代码。

**Comment by asiainfoliwei** [comment]
> 请提交最小可以复现问题的代码。

config.default.js

`
    config.cookie_config = { // cookie 配置
        path: '/',
        maxAge: 1000 * 60 * 60 * 24 * 1,
        signed: true,
        httpOnly: true,
        encrypt: true,
        overwrite: true
    }

    config.security = {
        csrf: {
            enable: false,
            ignoreJSON: true,
        },
    };
    
    config.cors = {
        origin: 'http://localhost:8080',
        allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,',
        credentials: true,
    };

    config.auth_cookie_name = 'key'; 
`

登录成功设置cookie

`
const auth_token = User.id + '@@@@@' + User.password;

const { config: { auth_cookie_name, cookie_config } } = app;

ctx.cookies.set(auth_cookie_name, auth_token, cookie_config); // 设置cookie

 ctx.body = { result: true };
`
前端地址是本地地址即origin为http://localhost:8080

**Comment by popomore** [comment]
可能 cookie 已经有了

**Comment by asiainfoliwei** [comment]
> 可能 cookie 已经有了

真的是cookie有了，但是超级奇怪的是为什么在浏览器中application cookies 中看不到cookie是为什么？

**Comment by asiainfoliwei** [comment]
> 可能 cookie 已经有了

重新发送请求头中确实有cookie

**Comment by popomore** [comment]
你本地绑一个 host 试一下
