### ISSUE TITLE
请问大神，egg在阿里内部用到生产环境了吗？

### ISSUE THREAD

**Issue by yale8848** [eggjs/egg#330]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by popomore** [comment]
http://www.zhihu.com/question/50526101/answer/144952130

> 据不完全统计，目前阿里 Node.js 的开发者几百号人，线上的应用也非常之多，仅次于 Java 应用，光对外服务的进程数就超过 1w+。
Yale <notifications@github.com>于2017年2月8日 周三09:45写道：

**Comment by atian25** [comment]
@yale8848 基本上你能看到的阿里系的页面，淘宝，天猫，支付宝的后面都是 egg。已经稳定运行一年多了，经历过双 11 的考验，不用担心。

虽然你看到的社区版还是 0.x （马上要发布 1.0 了），但它其实对应于内网的 3.x 版本了，稳定性方面不用担心。

**Comment by yale8848** [comment]
谢谢了，回答的这么快。可以放心用了:)

**Comment by atian25** [comment]
@yale8848 可以先看看文档和源码, 预研下.

我们本月会发布 1.0, 遵循严格的 semver 规则, 可以放心使用.
