### ISSUE TITLE
ts 模式下在 vscode 中调试问题

### ISSUE THREAD

**Issue by treadpit** [eggjs/egg#3300]
launch.json 为eggjs 插件自动生成的

启动 debuger 后，控制台输出到这里就不会往下面走了，断点不可用

![image](https://user-images.githubusercontent.com/10692855/49913826-f3627e00-fec9-11e8-872f-fb2145a84120.png)

**Comment by atian25** [comment]
@whxaxes 你里面是不是也 fork 进程了？ brk 的话就卡住了吧？

**Comment by treadpit** [comment]
没有做其他操作，vscode 打开项目后直接启动调试，就卡住了

**Comment by atian25** [comment]
我是问 @whxaxes 的 egg-ts-helper

**Comment by whxaxes** [comment]
@whxaxes  嗯，有 fork ，我改一下

**Comment by whxaxes** [comment]
我本地试了一下，egg-ts-helper 不会卡住 ... 他所谓的卡住，是指卡在 egg 起进程的时候吧？点一下继续不就行了么 ... inpect-brk 本身就是会 break 住的，如果不想 break 的话，干嘛要加 inspect-brk

**Comment by atian25** [comment]
inspect-brk 的时候，vscode 我们之前的配置会 auto attach  master/worker/agent 

如果你在 agent 里面 fork 个进程的话，也会默认继承 execArgv 然后被 brk 住，但没有被 attach ，就卡住了吧。 你可以在 fork 的地方传递自己的 execArgv

**Comment by treadpit** [comment]
项目是 egg-init 初始化的项目，我重新初始化了一个项目还是不行，是我本地环境的问题？

另外请教一下，@whxaxes  *"点一下继续不就行了么"* 是指点击哪里呢？

![image](https://user-images.githubusercontent.com/10692855/49923468-91683f80-feee-11e8-8ef5-e64bd2121a99.png)

**Comment by whxaxes** [comment]
@treadpit 能给个稳定复现的 repo 吗？我帮你看看，btw ，你可以试一下把 `runtimeArgs` 里的 --inspect-brk 去掉跑一下看一下是不是正常的

**Comment by treadpit** [comment]
@whxaxes 谢谢，我刚才重启了电脑后能正常跑了，之前怎样都不行 💔，现在不能复现了，不知道之前是什么原因造成的

**Comment by whxaxes** [comment]
@treadpit  ok，那我先 close 掉这个 issue 了

**Comment by LuoShiXi** [comment]
遇到同样问题，回退vscode版本后可以了，应该是vscode版本问题
