### ISSUE TITLE
egg-session 使用问题，重启server，仍然可以通过ctx.session获取重启前设置的值

### ISSUE THREAD

**Issue by thinkive** [eggjs/egg#3301]
我测试发现一个问题，我登录成功后，通过
ctx.session.user = {username: 'abc'} //设置session数据
然后我重启服务器，我让人可以通过
console.log(ctx.session.user) 输出{username: 'abc'} 
我没使用第三方存储session数据的情况下，为什么重启服务，还能取到上一次存储的session数据

**Comment by atian25** [comment]
session 默认是用 cookie 的

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/core/cookie-and-session.html#session

**Comment by thinkive** [comment]
> 『服务端内存』这个传统好像有点太传统了。。。 集群情况下，内存就出问题了。
> 服务端存储的情况，用 redis，看文档，用 egg-session-redis

我指的就是在没使用第三方存储数据库来存session情况下，最传统就是存储在服务器内存中，eggjs这种session机制感觉和jwt机制一样了，数据都存储在客户端。

**Comment by atian25** [comment]
存储内存没意义吧，多进程，多集群情况下，内存是不共享的。
这种『传统』模式已经不适合现在的时代了。

**Comment by dayinji** [comment]
> 存储内存没意义吧，在 Node 的世界里面，多进程，多集群情况下，内存是没法共享的。
> 这种『传统』模式已经不适合现在的时代了。

egg的文档里写：“用户级别的缓存不要存储在 Session 中”。
请教一下，如果需要缓存用户级别或者权限相关的信息，除了使用seesion-redis等外部存储吗，有其他方式吗？

**Comment by atian25** [comment]
cookie 只放用户唯一标识，其他信息放外部存储，你可以不用 redis，按 sessionStore 的接口自行接入第三方

**Comment by dayinji** [comment]
> cookie 只放用户唯一标识，其他信息放外部存储，你可以不用 redis，按 sessionStore 的接口自行接入第三方
嗯嗯好的，感谢这么快的回复。谢谢你！
