### ISSUE TITLE
app.model.define is not a function

### ISSUE THREAD

**Issue by Jasonellen** [eggjs/egg#3306]
app/modal/user.js

module.exports = app => {
  const { STRING, INTEGER, DATE } = app.Sequelize;
  console.log("app.model",app.model)
  console.log("app.model.define",app.model.define)
  const User = app.model.define('user', {
    id: { type: INTEGER, primaryKey: true, autoIncrement: true },
    name: STRING(30),
    age: INTEGER,
    created_at: DATE,
    updated_at: DATE,
  });
  return User;
};

运行是报错
![image](https://user-images.githubusercontent.com/20942896/49932829-05154700-ff05-11e8-94e3-863bbe1f068b.png)

can you help u, tks

**Comment by whxaxes** [comment]
请提供可复现案例

**Comment by Jasonellen** [comment]
关了吧，这个问题是我之前按照教程中
![image](https://user-images.githubusercontent.com/20942896/50410374-7fae6280-0833-11e9-86b1-ca8e8d6bda2d.png) 执行这个操作并不会生成 app/model，所以我 自己执行了 npx sequelize init:models 导致 生成的文件夹model文件夹 里会自带一个 index.js，这个删掉就好了

然后下面的 单元测试例子 也有点问题
![image](https://user-images.githubusercontent.com/20942896/50410489-3b6f9200-0834-11e9-9037-d5f66fe19a43.png)

这里 Post 也是没有的，也删掉，好像就可以了
@hf1120@whxaxes

**Comment by whxaxes** [comment]
@thonatos  改改文档？

**Comment by lesiyu129** [comment]
你的app/model 在运行初始化的时候是不是被注入了index.js 如果有，请把他删掉，就可以了

**Comment by spwm0429** [comment]
按文档走，遇到了同样的问题

**Comment by spwm0429** [comment]
> 你的app/model 在运行初始化的时候是不是被注入了index.js 如果有，请把他删掉，就可以了

我按照文档走，
npx sequelize db:migrate
这一步生成了带有index.js的model文件夹，把index.js删除后链接不上数据库

**Comment by HeWenKe** [comment]
按照官网的例子，我以为我流程有问题，结果按照官网走了几边，都是这个app.model.define报错，第一次使用这个egg，有点坑的，看上面的答复，都是什么好像可以解决，到底怎么解决。

**Comment by HeWenKe** [comment]
> > 你的app/model 在运行初始化的时候是不是被注入了index.js 如果有，请把他删掉，就可以了
> 
> 我按照文档走，
> npx sequelize db:migrate
> 这一步生成了带有index.js的model文件夹，把index.js删除后链接不上数据库

可以连接，我把那个index.js删除了

**Comment by feleventh** [comment]
按照官网教程走的，就会报这个错，居然被关了

**Comment by Kinice** [comment]
> > > 你的app/model 在运行初始化的时候是不是被注入了index.js 如果有，请把他删掉，就可以了
> > 
> > 
> > 我按照文档走，
> > npx sequelize db:migrate
> > 这一步生成了带有index.js的model文件夹，把index.js删除后链接不上数据库
> 
> 我也是，删了model/index.js数据库就连不上了

连不上数据库的，在config.default.js里的config.sequelize内加上数据库的username和password就好了。
