### ISSUE TITLE
初始化错误使用 app.ready

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#331]
## 背景

在单元测试时，错误都是使用 `.on('error')` 监听的，可以写成

```js
before(done => {
  app = mm.app();
  app.once('error', done);
  app.ready(done);
});
```

但其实很少人会监听 error 事件，而且初始化时 error 和 ready 是互斥的，所以一旦出现了错误都是超时。

其次，egg-mock 重新实现了 mm.app，[整个初始化都是异步的](https://github.com/eggjs/egg-mock/blob/6ce834f7cb9808a7c64978f814226ffd8dd5f339/lib/app.js#L44)。所以原来在 loader 中 throw 的错误也需要监听 error 事件。

## 方案

合并初始化的 error 和 ready，如果在初始化过程中报错，ready 的 callback 会返回错误。

- 保留初始化时 error 事件的错误
- 在初始化时，将 error 事件转到 ready，error 事件都来自 ready-callback，同步错误时直接抛出去的。
- egg-mock 初始化因为是异步的，也需要将错误转到 ready

## Action

- [x] get-ready https://github.com/node-modules/ready/issues/2
- [x] ready-callback https://github.com/node-modules/ready-callback/pull/98
- [x] egg-core https://github.com/eggjs/egg-core/pull/53
- [x] egg-mock https://github.com/eggjs/egg-mock/pull/27
- [x] egg

**Comment by fengmk2** [comment]
确实真遇到了，之前 egg-oss 就是。。。然后我直接 skip 了 https://github.com/eggjs/egg-oss/pull/2/files#diff-51ef6f22ca961fa136b8cfc217e6fb31R52

**Comment by popomore** [comment]
ready-callback 使用了 get-ready，所以还不能直接使用 sdk-base，我觉得还是得 get-ready 来实现 ready(err)。

**Comment by popomore** [comment]
cc @gxcsoccer

**Comment by popomore** [comment]
@fengmk2 现在 oss 那个应该可以跑过了吧？
