### ISSUE TITLE
typescript egg-redis配置

### ISSUE THREAD

**Issue by ming2020** [eggjs/egg#3311]
egg-redis\index.d.ts
![image](https://user-images.githubusercontent.com/15954271/49983747-799cc400-ff9f-11e8-9e9b-b8fa3a752c4b.png)
按这样配置使用报错
app.redis.set is not a function in typescript

typings\index.d.ts
![image](https://user-images.githubusercontent.com/15954271/49983772-a355eb00-ff9f-11e8-9d1a-c73d65d34791.png)
![image](https://user-images.githubusercontent.com/15954271/49983821-e1eba580-ff9f-11e8-91ef-6464832c50b7.png)
修改后正常

typescript使用egg-redis正确方法是？

* **Node Version**: v8.10.0
* **Egg Version**: 2.14.1
* **Plugin Name**: egg-userrole
* **Plugin Version**: 2.0.0
* **Platform**: win10
* **Mini Showcase Repository**:

**Comment by whxaxes** [comment]
给个详细的错误截图看一下？

**Comment by whxaxes** [comment]
应该是因为没有安装 `@types/ioredis` 导致的，这个我已经提了 PR 并且已经 merged 了，不过貌似还没发版本：https://github.com/eggjs/egg-redis/pull/25  ，你可以手动装一下 `@types/ioredis` 临时解决

**Comment by whyour** [comment]
报这个错，如果在配置文件中直接在client声明port、host、password
```
TSError: [egg-core] load file: /Users/wangpeng/resp/wt-hulk/back-end/config/config.local.ts, error: ⨯ Unable to compile TypeScript:
config/config.local.ts(15,5): error TS2322: Type '{ client: { port: string; host: string; password: string; db: number; }; }' is not assignable to type 'PowerPartial<EggRedisOptions>'.
  Types of property 'client' are incompatible.
    Type '{ port: string; host: string; password: string; db: number; }' is not assignable to type 'PowerPartial<ClusterOptions>'.
      Types of property 'port' are incompatible.
        Type 'string' is not assignable to type 'number'.
```
建议接口EggRedisOptions 中的client 加个类型
```
interface EggRedisOptions {
  Redis?: Redis;
  default?: object;
  app?: boolean;
  agent?: boolean;
  client?: ClusterOptions | RedisOptions;
  clients?: Record<string, RedisOptions>;
}
```
