### ISSUE TITLE
[egg-scripts] [PR] stop process only if the title matches exactly

### ISSUE THREAD

**Issue by plusmancn** [eggjs/egg#3313]
* **Node Version**: 10.14.1
* **Egg Version**: 1.11.0
* **Plugin Name**: egg-scripts
* **Plugin Version**: 2.10.0
* **Platform**: mac/ubuntu 16.04
* **Mini Showcase Repository**:

Because of'exmaple'.inclues('exmap') === true，if egg-scripts <= 2.1.0 and you run `.. stop --title=exmap`，the process with 'title:example' will also be killed unexpectedly，see below
1. [/lib/cmd/stop.js#L40](https://github.com/eggjs/egg-scripts/blob/1a8ad1f3baab7f9a1238d239bb5189ab26572be2/lib/cmd/stop.js#L40),
2. [/lib/cmd/stop.js#L60](https://github.com/eggjs/egg-scripts/blob/1a8ad1f3baab7f9a1238d239bb5189ab26572be2/lib/cmd/stop.js#L60)

This [PR](https://github.com/eggjs/egg-scripts/pull/35) make egg-scripts stop process only if the title matches exactly.

**Comment by atian25** [comment]
if PR is sent, not need to raise an issue here.

but if an issue is raised first, recommend to add `close https://github.com/eggjs/egg/issues/3313` to the PR body, so if PR is merged, this issue will auto close by GitHub.
