### ISSUE TITLE
egg-multipart question

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3314]
In the following code (from egg-multipart README)

```js
const path = require('path');
const Controller = require('egg').Controller;

module.exports = class extends Controller {
  async upload() {
    const { ctx } = this;
    const stream = await ctx.getFileStream();
    const name = 'egg-multipart-test/' + path.basename(stream.filename);

    const result = await ctx.oss.put(name, stream);

    ctx.body = {
      url: result.url,
      fields: stream.fields,
    };
  }
};
```

What happens if we have an exception in the `const result = await ctx.oss.put(name, stream);` line? Assume we have a network issue

What happens for stream? Is there a memory leakage as we don't consume stream
What is the solution to prevent memory leakage?

**Comment by x-cold** [comment]
egg-oss depends on [ali-oss](https://github.com/ali-sdk/ali-oss)

It supports to use async/await,  therefore we can catch exceptions via `try ... catch ...`.
For more details, please browser the document.

**Comment by sm2017** [comment]
@x-cold my question id not about egg-oss
My question is about stream , What happens ti stream in the following code?


```js
const path = require('path');
const Controller = require('egg').Controller;

module.exports = class extends Controller {
  async upload() {
    const { ctx } = this;
    const stream = await ctx.getFileStream();
    ctx.body = {
      url: result.url,
      fields: stream.fields,
    };
  }
};
```

Is there memory leakage or not?
