### ISSUE TITLE
loadFile 函数文档

### ISSUE THREAD

**Issue by whlsxl** [eggjs/egg#3316]
Node Version: v8.11.1
Egg Version: 2.14.1
Platform: macOS

`loadFile` 的[文档](https://eggjs.org/zh-cn/advanced/loader.html#loadfile)，

> 如果文件 export 一个函数会被调用，并将 app 作为参数，否则直接使用这个值。

和`egg-core`的[文档](https://github.com/eggjs/egg-core#loadfilefilepath) 不一致

> To load a single file. Note: The file must export as a function.

请问这两个哪个是正确的？

另：`loadToApp`可不可以 load 单独文件到 `app` ，或者有别的方法 load。

**Comment by thonatos** [comment]
> 看文档有疑惑的时候，不妨直接看代码。

## loadFile

```js
// https://eggjs.app/api/node_modules_egg-core_lib_loader_egg_loader.js.html#line293
loadFile(filepath, ...inject) {
  if (!filepath || !fs.existsSync(filepath)) {
    return null;
  }
  // function(arg1, args, ...) {}
  if (inject.length === 0) inject = [ this.app ];
  let ret = this.requireFile(filepath);
  if (is.function(ret) && !is.class(ret)) {
    ret = ret(...inject);
  }
  return ret;
}
```

代码其实更清晰：

1.当文件`export`是函数，且未传参数（`inject.length === 0`）时，将使用`app`作为参数
2.当文件不为函数时，直接返回

所以看文件`export`的类型而定了。

## loadToApp

用什么方法`load`取决于要加载的文件类型

https://eggjs.app/api/EggLoader.html

**Comment by atian25** [comment]
> To load a single file. Note: The file must export as a function.

这句确实有点旧了，最早 egg 支持的都是 `exports` 的方式，后面 1.0 才支持的 class 方式。

欢迎 PR。

**Comment by whlsxl** [comment]
@atian25 感谢回答 随后PR

这个我没测出来是因为另一个问题，麻烦您看下
https://github.com/eggjs/egg/issues/423#issuecomment-447645916

**Comment by atian25** [comment]
挂载要在 `app.js` 里面，而不是 `app/extend/application.js`，后者并不支持 `module.exports = app => {}` 的方式。

**Comment by whlsxl** [comment]
抱歉 大意了……
