### ISSUE TITLE
如果数据传输方式改成websocket，是不是会避免很多安全问题？

### ISSUE THREAD

**Issue by 4176244** [eggjs/egg#3317]
这两天在看egg.js，看到安全这一篇，有个思考，如果采用websocket作为数据传输方式，并且再嵌入一些加密方法，前端网页根据websocket接收的数据进行变化，这样，是不是会减少很多的攻击？或者说，会减少很多风险？

**Comment by fengmk2** [comment]
安全问题跟传输方式没有绝对的因果关系，还是不要泛泛而谈。
