### ISSUE TITLE
egg-ant-design-pro 编译出错。Without `from` option PostCSS could generate。。。

### ISSUE THREAD

**Issue by lazyfish88** [eggjs/egg#3325]
* **Node Version**:v10.14.2
* **Egg Version**: 2.14.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Win 10
* **Mini Showcase Repository**:

我在新机上重新复制源码安装。。执行dev时，提示如下
![image](https://user-images.githubusercontent.com/3926898/50163039-8d875380-031a-11e9-94ef-5e4032f35ce6.png)
运行build时，提示
![image](https://user-images.githubusercontent.com/3926898/50163071-a1cb5080-031a-11e9-8a47-ede89a9c38e4.png)

之前在mac上执行是没问题的，刚把源码删了重新配置。dev也出问题了。。不过mac上出错后不影响编译，
![image](https://user-images.githubusercontent.com/3926898/50163428-60877080-031b-11e9-992e-4d3208a0e22f.png)

build也会提示warning。不过编译可成功。
![image](https://user-images.githubusercontent.com/3926898/50163443-667d5180-031b-11e9-8c76-45784cdb0f15.png)

在window上会卡在这个warning

**Comment by popomore** [comment]
嗯，因为用的不是 windows 语法，可以改成 crossenv

**Comment by lazyfish88** [comment]
呃。。怎么改？能告知下吗？我这边刚接触还不是太懂哈 。

**Comment by lazyfish88** [comment]
cross-env是不是废了？？
我刚安装了几次都是提示404
![image](https://user-images.githubusercontent.com/3926898/50194757-3499d880-0377-11e9-95ce-c64cb67a9db2.png)

**Comment by atian25** [comment]
你需要去学习下命令行的基础，Window 下的环境变量不是 `$PWD` 而是 `%PWD%`

去看下 cross-env 吧。

**Comment by kchjxxgh** [comment]
那如楼主第一张图那样，在win10上执行，npm run dev的时候，并没有看到windows特有的脚本啊，为什么也失败呢？
