### ISSUE TITLE
连接redis，当redis没有设置password的时候，出错（正确使用d.ts）

### ISSUE THREAD

**Issue by zheng199512** [eggjs/egg#3330]
> If you want to access redis with no password, use password: null.

@atian25  天猪大佬您好，我看您添加了d.ts，应该改下readme，password：‘’，设置成null会被ts检测出来添加配置时报错。

以及在使用时怎么用？
![image](https://user-images.githubusercontent.com/29241175/50204311-4a22f880-039f-11e9-8b8e-7cd23abd4e27.png)
会显示没有redis属性

![image](https://user-images.githubusercontent.com/29241175/50204336-61fa7c80-039f-11e9-85fd-6c4b2d432b28.png)
引入了egg-redis，后续调用封装好的方法会报错

不知道要怎么正确使用提示？？

## 相关环境信息
- **操作系统:win10**：
- **Node 版本:node8.12.0**

**Comment by zheng199512** [comment]
呵，被自己蠢哭了，在项目的d.ts中引一下就好了，千万不要在代码之中引

**Comment by thonatos** [comment]
关了，😀

**Comment by zheng199512** [comment]
mua~

**Comment by atian25** [comment]
都不需要自己引， egg-ts-helper 会自动生成

**Comment by zheng199512** [comment]
在项目中可以不写， egg-ts-helper 会自动生成，自动import到对应的位置，一般是plugin.d.ts，貌似做业务框架开发的时候不会生成，不能执行egg-bin的命令，需要手动import下

**Comment by atian25** [comment]
执行一次 egg-bin dev 或者 ets 就生成了。
