### ISSUE TITLE
继承egg-logger的自定义日志，会产生大量同文件的文件句柄

### ISSUE THREAD

**Issue by bymaxchen** [eggjs/egg#3331]
logger/index.js
```
'use strict';

const Logger = require('egg-logger').Logger;
const CustomTransport = require('./custom-transport');

module.exports = (ctx, name) => {
  const logger = new Logger();
  const { config } = ctx.app;

  logger.set(
    'file',
    new CustomTransport(
      {
        file: config.yiLogger[name].file,
      },
      ctx
    )
  );

  return logger;
};
```
logger/custom-transport.js
```
'use strict';

const FileTransport = require('egg-logger').FileTransport;

function contextFormatter(meta) {
  return `${meta.date} ${meta.level} ${meta.pid} ${meta.paddingMessage} ${meta.message}`;
}

class CoustomTransport extends FileTransport {
  constructor(options, ctx) {
    super(options);
    this.ctx = ctx;
  }

  paddingMessage() {
    const ctx = this.ctx;
    const appID = ctx.appID || 0;
    const userId = ctx.userId || 0;
    const traceId = ctx.traceId || 0;
    const use = ctx.starttime ? Date.now() - ctx.starttime : 0;
    const SERVICE_NAME =
      (ctx.app.config.yiLogger && ctx.app.config.yiLogger.serviceName) || ctx.serviceName || 'UNKNOWN';
    return `[${SERVICE_NAME}/${appID}/${userId}/${ctx.ip} ${traceId} ${use}ms ${ctx.method} ${ctx.url}]`;
  }

  log(level, args) {
    const meta = {
      formatter: contextFormatter,
      paddingMessage: this.paddingMessage(),
    };
    super.log(level, args, meta);
  }
}

module.exports = CoustomTransport;

```
app/extend/context.js
```
const yiLogger = require('../logger');

module.exports = {
  getYiLogger(name) {
    return yiLogger(this, name);
  },
};
```

example
```
ctx.getYiLogger("infoLogger").info("hello");
```

现象:
1.当有海量请求时，机器直接会挂掉，原因：open too many files
用lsof命令查看会有对同一个日志文件的大量文件句柄。
2.改回ctx.logger.info就正常了。

**Comment by atian25** [comment]
既然是 Context 肯定是 `request-base` 的，一个请求创建一个对象的。
你的 Transport 要共享。

看下原来的源码吧， ctx logger 其实是 delegate 给 app logger 的

**Comment by bymaxchen** [comment]
@atian25 我看egg的源码好像是做了缓存？ 你说的是一次请求创建一次日志对象，然后Transport要所有的日志对象共享对吧？

**Comment by bymaxchen** [comment]
@atian25  但是Transport中必须传入ctx；好像没有set方法吧？ 如果共享要怎么实现呢？

**Comment by atian25** [comment]
缓存只是 ctx 级别啊，只是说你在同一次请求中，调用两次 ctx.logger 是同一个对象。
但如果并发 1000 个请求，那肯定是同时有 1000 个。

**Comment by atian25** [comment]
你可以参考 egg-logger 的 contextLogger 的声明，自己写一个，然后初始化的时候，不要传递 app.logger，而是你自己定义的一个 logger 。

参考源码：
- https://github.com/eggjs/egg/blob/master/app/extend/context.js#L100
- https://github.com/eggjs/egg-logger/blob/master/lib/egg/context_logger.js

说到底，ContextLogger 其实就是 ctx 上的一个 extend，对某个 logger 进行包装，你完全可以自定义一个的

**Comment by bymaxchen** [comment]
@atian25  我是这么写的。 同一个请求缓存我知道怎么做了； 但是你说的多个请求共享transport我还不知道咋搞。

**Comment by popomore** [comment]
为啥不用 customLogger，在这个 logger 上加 transport 就好了

**Comment by bymaxchen** [comment]
@popomore  我要自定义格式。

**Comment by bymaxchen** [comment]
@atian25   我把源码看懂了，谢谢。

**Comment by popomore** [comment]
格式最终都在 transport 处理的

**Comment by atian25** [comment]
> @atian25 我是这么写的。 同一个请求缓存我知道怎么做了； 但是你说的多个请求共享transport我还不知道咋搞。

不是说了么，custom logger 里面配置 transport，它是一个 app 级别的 logger

**Comment by atian25** [comment]
https://github.com/atian25/egg-showcase/pull/11
