### ISSUE TITLE
[Feature Request] file_loader.js 支持 载入 将路径actor/social/follow.js => follow,

### ISSUE THREAD

**Issue by huang12zheng** [eggjs/egg#3333]
file_loader.js 支持 载入 将路径actor/social/follow.js => follow,,去掉目录名
File_loader. js loading the path actor/social/follow.js => follow

## Background
I'm always frustrated when I need a object like actor,have all instances of class Actor in app or ctx.
but it is like to be app.actor.social.follow. In other word, I just want to be app.actor.follow.

## Proposal
Describe the solution you'd like, better to provide some pseudo code.

function loadSimple() {
 const items = this.parse();
 const target = this.options.target;
 for (const item of items) {
   debug('loading item %j', item);
   // item { properties: [ 'a', 'b', 'c'], exports }
   // => target.c = exports
   const property = item.properties[item.properties.length-1];
   if (property in target) {
	 if (!this.options.override) throw new Error(`can't overwrite property '$properties}' from ${target[property][FULLPATH]} by ${item.fullpath}`);
   }
   obj = item.exports;
   if (obj && !is.primitive(obj)) {
	 obj[FULLPATH] = item.fullpath;
	 obj[EXPORTS] = true;
   }
   target[property] = obj;
   debug('loaded %s', properties);
 }
 return target;
 }
;
## Additional context
.

**Comment by popomore** [comment]
You can use FileLoad directly, directory is `actor/social` and target is `app.actor`. So `actor/social/flow.js` will be loaded to `app.actor.flow`

**Comment by huang12zheng** [comment]
Sorry, there is a more info.
I just use loadToApp.  so, If I use FileLoad directly, it may be a lot of code.

app.loader.loadToApp(dir, 'actor', {
    inject: app,
    caseStyle: 'upper',
    filter(actor) {
      return typeof actor === 'function' && actor.prototype instanceof Actor;
    },
  });

**Comment by popomore** [comment]
Actually, loadToApp  also use FileLoader, you can see the code https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js

**Comment by huang12zheng** [comment]
oh, I am stupid.
but directories are many like [
actor/Social/.....
actor/User/....
actor/Excavate/...
actor/Info/....
]

**Comment by popomore** [comment]
Read the code, and do youeself.

**Comment by huang12zheng** [comment]
I had do it myself.And,It maybe someone need this feature.So,I make a "Feature Request".
But ,thank you all the same.

**Comment by atian25** [comment]
you could update the issue to show us what's the input and what's expected
