### ISSUE TITLE
egg mysql使用query拼接sql时order by语法无效

### ISSUE THREAD

**Issue by huskarlee** [eggjs/egg#3335]
<p>参数值</p>
<p>start = '2018-12-01'</p>
<p>end = '2018-12-30'</p>
<p>orderName = 'date'</p>
<p>order = 'desc'</p>
<p>offset = 0</p>
<p>pageSize = 10</p>

<p>sql拼接如下:</p>

```typescript

const res = await db.query(`SELECT * FROM statistical_totals
        WHERE date >= ? AND date <= ? ORDER BY ? ? LIMIT ?, ?`,
    [start, end, orderName, order, offset, pageSize]);

```

<p>代码执行成功,但是排序结果不对</p>

<p>sql拼接如下:</p>

```typescript

const res = await db.query(`SELECT * FROM statistical_totals
        WHERE date >= ? AND date <= ? ORDER BY date desc LIMIT ?, ?`,
    [start, end, offset, pageSize]);

```

<p>代码执行成功,排序正确</p>

<p>order by语法后面的? ?是否无效?还是说我使用的方式不对?</p>

**Comment by huskarlee** [comment]
完整代码:
`
    public async getWhile(start: string, end: string, orderName: string,
        order: string, offset: number, pageSize: number) {
        const db = this.app.mysql.get('logdb');

        const countRes = await db.query(`SELECT COUNT(*) AS count FROM statistical_totals
         WHERE date >= ? AND date <= ?`,
            [start, end]);
        const count = countRes[0].count;

        const res = await db.query(`SELECT * FROM statistical_totals
                WHERE date >= ? AND date <= ? ORDER BY ? ? LIMIT ?, ?`,
            [start, end, orderName, order, offset, pageSize]);

        const rows = res.map((row) => {
            return {
                id: row.id,
                date: row.date,
                newCount: row.new_count,
                proxyNewCount: row.proxy_new_count,

                loginCount: row.login_count,
                proxyLoginCount: row.proxy_login_count,

                betGoldBeans: row.bet_gold_beans,
                proxyBetGoldBeans: row.proxy_bet_gold_beans,

                winGoldBeans: row.win_gold_beans,
                proxyWinGoldBeans: row.proxy_win_gold_beans,

                winDiamonds: row.win_diamonds,
                proxyWinDiamonds: row.proxy_win_diamonds,

                shopCostDiamonds: row.shop_cost_diamonds,
                proxyShopCostDiamonds: row.proxy_shop_cost_diamonds,

                proxyRecycleGoldBeans: row.proxy_recycle_gold_beans,
                proxyRecycleDiamonds: row.proxy_recycle_diamonds,
            };
        });

        return { data: rows, count, totalPage: Math.ceil(count / pageSize) };
    }
`

**Comment by huskarlee** [comment]
自己使用另一种方式解决排序问题:

```typescript

const res = await db.query(`SELECT * FROM statistical_totals
        WHERE date >= ? AND date <= ? ORDER BY ${orderName} ${order} LIMIT ?, ?`,
    [start, end, offset, pageSize]);

```

**Comment by Ailln** [comment]
I have the same problem!
