### ISSUE TITLE
Get a app.actor undefined in unittest? while this.app.actor is ok when run dev;

### ISSUE THREAD

**Issue by huang12zheng** [eggjs/egg#3336]
## What happens?

问题:
单元测试时,app.actor不存在.

已知情况:
1.项目正常执行(run dev), 检查变量 this.app.actor 存在
2.单元测试 断点处,检查变量app.actor 不存在

1. this.app.actor is ok when run dev;
2. Get a app.actor undefined in unittest

## 最小可复现仓库
https://github.com/huang12zheng/issue

## 复现步骤，错误日志以及相关配置
1.npm run test-local
// 结果: 报错.
2.npm run dev
3.打开127.0.0.1:7001
// 结果 [object Object]

// plugin.js
'use strict';

exports.cqrs = {
  enable: true,
  package: 'egg-cqrs',
};

## 相关环境信息
Node Version: 10
Egg Version: 2
Platform: windows

moreover :https://cnodejs.org/topic/5c1b893476c4964062a1bf9c

**Comment by popomore** [comment]
应用不需要指定 baseDir

**Comment by atian25** [comment]
测试应用的话，不需要 fixtures，你的应用目录就是你本身的。

你那个示例，`test-local` 的时候，跑的是 `test/fixtures/apps/meng` 这个应用，`dev` 的时候，跑的是根目录的应用，自然表现不一样。

测试代码改为：

```js
const assert = require('assert');
const { Domain } = require('cqrs'); // not egg-cqrs
const { app, mock } = require('egg-mock/bootstrap');

describe('test/app/actor/social.test.js', async () => {
  it('should have actor?', async () => {
    assert(app.actor);
    console.log(app.actor.Social)
  });
});
```

**Comment by huang12zheng** [comment]
Thank you very much.
