### ISSUE TITLE
上传文件时，stream.filename的值为undefined

### ISSUE THREAD

**Issue by 14glwu** [eggjs/egg#3341]
## What happens?
上传代码：
![image](https://user-images.githubusercontent.com/26249572/50443486-a0171380-093e-11e9-9ec4-8cfa54ca8ef6.png)
后台代码：
![image](https://user-images.githubusercontent.com/26249572/50443280-82957a00-093d-11e9-9591-3dd01020ce86.png)
我只上传了一个文件，但是为什么while循环了两次，并且第二次stream的值为`[ '_csrf', 'zqjLXxZW-Cq8L6oLn-sw3RFu0o-DHfy0dyYM', false, false ]`

**Comment by fengmk2** [comment]
如果你对 stream 模式不熟悉，还是建议使用 file 模式。

**Comment by 14glwu** [comment]
> 如果你对 stream 模式不熟悉，还是建议使用 file 模式。

请问能解释下吗，我想使用stream模式

**Comment by 14glwu** [comment]
懂了，真是抱歉
