### ISSUE TITLE
egg-cors 如何设置全局跨域解决方案

### ISSUE THREAD

**Issue by moyuanhua** [eggjs/egg#3342]
今天在issue中发现了大家和我有一样的疑问  而且大家好像都没有较为妥帖的解决方案， 在仔细阅读egg-cors 和 egg-secure 这两个库的文档之后，， 发现很简单 ，分享给大家， 主要是这句egg-cors中有一个notice大家一定是没有注意到
```
Security
Only in safe domain list support CORS when security plugin enabled.
```
所以正确的设置方式是
// plugin.js 
![image](https://user-images.githubusercontent.com/7417755/50448575-0874ed80-095d-11e9-8b7c-628019230f65.png)
// config.evn.js
![image](https://user-images.githubusercontent.com/7417755/50448595-1aef2700-095d-11e9-9642-7c6fda5eaacc.png)
这样就能正确的设置全局跨域请求了。 阿里戈多

**Comment by popomore** [comment]
安全插件关闭可能会带来安全问题。

**Comment by atian25** [comment]
你的原因应该是因为写错了吧。。。 `cors` 而不是 `cos`

**Comment by moyuanhua** [comment]
> 你的原因应该是因为写错了吧。。。 `cors` 而不是 `cos`
> 
> 不建议直接关闭 security，而是要去搞明白 CORS 到底是啥。

你说的好像有点道理。。。
