### ISSUE TITLE
Get a app.model undefined in unittest?

### ISSUE THREAD

**Issue by huang12zheng** [eggjs/egg#3343]
## What happens?

问题:
单元测试时,app.model不存在.

## 最小可复现仓库
https://github.com/huang12zheng/issue

## 复现步骤，错误日志以及相关配置
1.npm run dev
* 控制台结果:underfined {}

2.npm run test-local
* 控制台结果:underfined underfined  {}

* 我的疑问:
* 单元测试时 app.js 里为什么require('mongoose')不会正常处理?{即单元测试时第二个结果为什么是underfined.}

// plugin.js
'use strict';

exports.cqrs = {
  enable: true,
  package: 'egg-mongoose',
};

* ps:

'use strict';

// app.js
module.exports = async app => {
  // 加载对应该数据库, 要在opt._app之前,且需要await
  // if (opt._db !== 'mock') await require(opt._db);
  console.log(app.model);
  await require('mongoose');
  console.log(app.model);
};

## 相关环境信息
Node Version: 10
Egg Version: 2
Platform: windows

**Comment by whxaxes** [comment]
在 egg-mongose 中创建 `app.model` 这个实例是在 beforeStart 中创建的（ see https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L43 ），而这个 beforeStart 里的回调执行时机是比 app.js 的执行时机慢的（ 有兴趣可以看 [egg-core](https://github.com/eggjs/egg-core) 中的源码了解 ），所以你在 app.js 打印 `app.model` 是 undefined ，是因为此时还没执行到 egg-mongoose 里的创建 app.model 的逻辑呢。

而你加了 await 之后第二个打印的逻辑成了异步了，因此在跑 npm run dev 的时候，当执行到后面的异步逻辑的时候恰巧已经 ready 了，所以 app.model 就有了，单测里又没有仅仅是因为单测里实例化 app 不是走 cluster 的，启动速度更快，因此等执行到第二个打印的时候 app.model 也还没 ready 罢了。

如果你想在 app.js 中获得 app.model ，建议在 egg-ready 之后再使用。

```js
  app.messenger.on('egg-ready', () => {
    console.log('>>>', app.model);
  });
```

**Comment by huang12zheng** [comment]
我觉得不是应该await require('mongoose'); 执行完,才会执行console.log(app.model);
为什么运行到一半,就去运行console.log(app.model)了?

**Comment by whxaxes** [comment]
@huang12zheng  什么叫运行到一半？而且本来你这个 `await require('mongoose')` 就不合理，require 又不是异步的

**Comment by huang12zheng** [comment]
* 运行到一半, 
是因为我在app.js里运行了一个比较慢的处理.{ await app.MemoryLoad(app).}. 这导致了MemoryLoad没有执行完,就去执行unittest.     
另,"就去运行console.log(app.model)了"  这个当时是控制台输出underfined. 后来我没去复现. 可以先不管了.
* await require('mongoose')
这个想是等待egg-mongoose处理完, 再往跑下面的. 也可能是瞎猫碰到了死耗子. 

* 后续
想了几天,觉得不应该将这种比较慢的处理(MemoryLoad)写在app.js里.
就写了一个Subscription,启动时跑一下. 
单元测试加上 await app.runSchedule('MemoryLoad'); 
算了解决了,我单元测试 执行的问题.

* 最后总结一下..
最开始单测试执行出错, 定位到是app.model 不存在. 
解决之后. 发现单测还是有问题, 因为处理太多了 (去数据库中取数据).
最后 用定时任务+单测await app.runSchedule('MemoryLoad');

**Comment by huang12zheng** [comment]
app.js 调用是这么写的.
app.messenger.on('egg-ready',async ()=>{
    await require('./lib/MemoryLoad')(app);
}
