### ISSUE TITLE
egg-socket.io 自定义path应该怎么写

### ISSUE THREAD

**Issue by pengchangjiang** [eggjs/egg#3345]
![image](https://user-images.githubusercontent.com/23370585/50500642-aff13d80-0a8d-11e9-94ea-9d2a31951f6c.png)

如上图配置之后，没有成功
客户端情况
![image](https://user-images.githubusercontent.com/23370585/50500673-ddd68200-0a8d-11e9-8e4c-738ee7ee0c7e.png)
![image](https://user-images.githubusercontent.com/23370585/50500741-360d8400-0a8e-11e9-8896-260b5fe60453.png)

**Comment by ngot** [comment]
According to the [official document](https://socket.io/docs/server-api/), there are two ways to set the server path:

- passing the path parameter through the constroutor which means the init config in egg-socket.io:

```js
exports.io = {
  init: {
      path: 'geoc',
  },
  namespace: {
    '/': {
      connectionMiddleware: [],
      packetMiddleware: [],
    },
  },
};
```

- Another method is to manually invoke the path interface to change to path property:

```js
app.io.path('geoc')
```

**Comment by pengchangjiang** [comment]
@ngot 感谢！已经成功。查阅同学请注意：path:"/geoc"，“/”不能少。
