### ISSUE TITLE
sequelize-auto 生成的model 在ctx中加载不到

### ISSUE THREAD

**Issue by yijiaqingilm** [eggjs/egg#3347]
## What happens?
我正在使用sequelize-auto 自动生成model，与egg-sequelize生成model/index.js 配合使用，但发现无论如何ctx都加载不到 model。

目录结构如下：
![image](https://user-images.githubusercontent.com/18654185/50504655-09676580-0aaa-11e9-9a8d-eab443191dc5.png)

**Comment by yijiaqingilm** [comment]
model/index.js 修改部分：
![image](https://user-images.githubusercontent.com/18654185/50504692-4b90a700-0aaa-11e9-8671-eb462873357b.png)

**Comment by yijiaqingilm** [comment]
debug   ctx.model 对象是一个空的 sequelize对象。

**Comment by dead-horse** [comment]
麻烦提交一个可复现的 case。感觉生成的 model 形式与 egg-sequelize 要求的 model 形式不一样，建议这一步手动编写。

**Comment by Sirormy** [comment]
没有按照 egg-sequelize 的规范写的 model 是不会加载到 model 对象上的，建议先看一下文档。
