### ISSUE TITLE
egg-prometheus 怎么获取 eggjs 应用的 metrics？

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#3359]
egg-prometheus 插件现在能用到生产环境吗？

参考prom-client.js文档，目前 egg-prometheus 是不是只能每次获取其中一个worker的metrics ?
https://github.com/eggjs/egg-prometheus/blob/master/app.js#L13
```
register.setDefaultLabels(Object.assign({
    app: app.config.name,
    pid: process.pid,
  }, config.defaultLabels));
```

## prom-client.js 文档
prom-client [usage-with-nodejs-cluster-module](https://github.com/siimon/prom-client#usage-with-nodejss-cluster-module)

Node.js's cluster module spawns multiple processes and hands off socket connections to those workers. Returning metrics from a worker's local registry will only reveal that individual worker's metrics, which is generally undesirable. To solve this, you can aggregate all of the workers' metrics in the master process. See [example/cluster.js](https://github.com/siimon/prom-client/blob/master/example/cluster.js) for an example

## Context
- **Node Version**:  8.12.0
- **Egg Version**: 2.12.0
- **Plugin Name**: egg-prometheus
- **Plugin Version**: 1.0.3
- **Platform**: *

**Comment by gxcsoccer** [comment]
@logzh 

1. 问题一：我们内部没有用 prometheus 在生产环境，所以我个人觉得暂时达不到生成的要求
2. 问题二：是的，目前只实现了单个 worker 的模式（prometheus 主动来拉数据），如果要支持多 worker 的话，我建议是实现主动推模式，配合 https://github.com/prometheus/pushgateway
