### ISSUE TITLE
resources 路由进不去update方法

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#3360]
路由注册：
`
router.resources('express', '/api/express', controller.express);
`
`controller->express`:
```
const Controller = require('egg').Controller;

class HomeController extends Controller {
    async index(ctx) {
        ctx.body='dasd';

    }

    async create(ctx) {
        ctx.body='dasd';
    }

    async show(ctx) {
        ctx.body='dasd';
    }

    async update(ctx) {
        ctx.body='dasd';
    }

    async destroy(ctx) {
        ctx.body='dasd';
    }
}

module.exports = HomeController;
```

```
Request URL:http://127.0.0.1:7001/api/pets/1
Request Method:POST
Status Code:404 Not Found
Remote Address:127.0.0.1:7001
Referrer Policy:no-referrer-when-downgrade
```
其他方法都可以，就update 404，也打印不了

其他resources试了也是一样，都行就update 404 进不去

**Comment by callmesoul** [comment]
@egg-bot 
直接用` egg-init egg-example --type=simple`
添加路由` router.resources('pets', '/api/pets', controller.pets);`
添加pets controller：
```
'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    this.ctx.body = '416546546';
  }
  async update(ctx) {
    ctx.body = 123456;
  }
}

module.exports = HomeController;
```
config.default.js 关闭csrf：
```
config.security= {
        csrf: {
            enable: false,
        }
    };
```

再使用postman
post http://127.0.0.1:7001/api/pets/1  
结果404

**Comment by callmesoul** [comment]
@atian25 https://github.com/callmesoul/egg-example

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/utils/router.js#L123

post 对应的是 create 方法

**Comment by callmesoul** [comment]
看错了不好意思，
我记得以前好像也是post的啊

**Comment by atian25** [comment]
这个一直没改过。

**Comment by callmesoul** [comment]
好吧...

**Comment by yangjindong** [comment]
目前也碰到进不了update方法的问题。使用Form表单更新数据的时候，设置method="PATCH"，但直接跳转到show方法了。
https://github.com/yangjindong/egg-example

**Comment by yangjindong** [comment]
经过查看Rails的form_for文档，发现需要在form表单里，添加
`<input type="hidden" name="_method" value="patch" />`
原method还是直接按照method="post"设置
