### ISSUE TITLE
并发请求疑惑

### ISSUE THREAD

**Issue by guchenhui** [eggjs/egg#3371]
当--workers=1时，http接口我故意设置每个请求await sleep 60秒再返回res。然后我多次请求接口，发现第七次请求，会在第一次请求返回res后才能进到controller及service代码里。也就是同时可处理的请求数为6。不知道这是node本身机制还是egg的设置？希望有大佬解答一下

**Comment by atian25** [comment]
跟 egg 没啥关系，看起来是你对 Node eventloop 这块了解不多。
提供一个最小可复现的仓库吧。

**Comment by guchenhui** [comment]
@atian25 是我错了。如果用postman调用接口，就不存在我上述问题。但如果是浏览器里调用，post或get同一个地址。超过6个，浏览器自己似乎有安全机制，等待第一个返回。再继续调用。
