### ISSUE TITLE
Lifecycle in app.ts don't work

### ISSUE THREAD

**Issue by treadpit** [eggjs/egg#3377]
项目是egg 初始化的 ts 项目。

在 `app` 文件夹下新建 `app.ts` 文件，执行 `npm run dev`，生命周期均未执行。

![image](https://user-images.githubusercontent.com/10692855/50818453-f5511d00-1361-11e9-8ff0-8a486a391024.png)

**Comment by whxaxes** [comment]
app.ts 放错目录了，应该在项目根目录下

**Comment by treadpit** [comment]
（￣▽￣）不好意思，我理解成了在app文件夹下面了，谢谢

**Comment by trylovetom** [comment]
@treadpit 不是你搞錯，是他寫錯了
![2019-02-19 12 20 11](https://user-images.githubusercontent.com/13268073/52989949-be7e2480-3440-11e9-88b3-a3c120cfb2b3.png)
