### ISSUE TITLE
[Feature Request] replace default method name `new` with RESTful style URL definition

### ISSUE THREAD

**Issue by felixpy** [eggjs/egg#3379]
## Background

I found the RESTful style URL definition using the `new` reserved word as the method name. Can you consider replacing it with another name?

https://eggjs.org/en/basics/router.html#restful-style-url-definition

Method | Path            | Route Name     | Controller.Action
-------|-----------------|----------------|-----------------------------
GET    | /posts          | posts          | app.controllers.posts.index
GET    | /posts/new      | new_post       | app.controllers.posts.**new**

## Proposal

Replace the method name with other word, such as `add`.

**Comment by dead-horse** [comment]
I think it is ok when using `new` in a class as a field

**Comment by felixpy** [comment]
Indeed, it just seems a bit weird. It doesn't matter if it is not replaced. Thanks.

**Comment by dead-horse** [comment]
Let's keep the same with https://guides.rubyonrails.org/routing.html , thanks for your suggestion!
