### ISSUE TITLE
生产环境下无法输出DEBUG等级到控制台

### ISSUE THREAD

**Issue by mackwan84** [eggjs/egg#3380]
## What happens?
我们希望在生产环境下日志文件只记录INFO等级以上的日志，DEBUG等级的日志输出到控制台，但是在代码里使用app.logger.debug却一直无法实现，DEBUG等级的日志就是无法输出。

## 复现步骤，错误日志以及相关配置
```
// config/config.prod.js
exports.logger = {
  level: 'INFO',
  consoleLevel: 'DEBUG',
  allowDebugAtProd: true,
};
```

## 相关环境信息
- **操作系统**：WIN 10
- **Node 版本**：8.x
- **Egg 版本**：2.14

**Comment by atian25** [comment]
为什么要输出到控制台？生产环境不应该去开启这些 debug 日志。

**Comment by whxaxes** [comment]
我看了一下源码，要在生产环境的 console 中输出日志得加个 `disableConsoleAfterReady` 的配置，也就是改成

```js
// config/config.prod.js
exports.logger = {
  level: 'INFO',
  disableConsoleAfterReady: false,
  consoleLevel: 'DEBUG',
  allowDebugAtProd: true,
};
``` 

这个配置貌似在文档里写漏了，我们补一下

**Comment by mackwan84** [comment]
打个比方，例如我们有个消息队列的消费者，我们会用INFO记录开始消费，结束消费，然后会尝试把消息用DEBUG记录，因为假如不记录呢生产环境真实报错的时候就无法重现问题了，假如用文件记录呢，数据量好像又有点大，所以才想到用控制台输出 T_T

**Comment by whxaxes** [comment]
@mackwan84  日志量大的话可以通过 egg-logrotator 来控制日志保存天数

**Comment by mackwan84** [comment]
@whxaxes 我也尝试用egg-logrotator去解决，但是蛋疼的是日志按天保存的同时不能按文件大小分割保存，然后控制每天最多保存多少MB或者GB的日志……

**Comment by whxaxes** [comment]
@mackwan84  如果有这么定制化的切割需求，可以参考 egg-logrotator 里的实现自己写个 schedule 来处理

**Comment by mackwan84** [comment]
@whxaxes 那我觉得假如设计初衷就是限制生产模式不输出DEBUG日志到控制台，那么得描述清楚或者logger的配置这一块得设计得减少歧义

**Comment by whxaxes** [comment]
@mackwan84 是的，这个我们已经发现了，今天刚提了 PR ：https://github.com/eggjs/egg/pull/3384

**Comment by whxaxes** [comment]
这种感觉会让配置更加复杂化，而且大部分应用都是不需要用到这些的配置，我个人是觉得不适合放到 egg 中，如果你们有定制化的日志需求，完全可以通过自定义 logger 来实现，想玩出花来都行。

**Comment by atian25** [comment]
可以自己扩展 logger 的，可以参考下 egg-logger-sls

**Comment by hyj1991** [comment]
日志输出到控制台和输出到文件性能上没什么差别吧，有 benchmark 测试标明两者性能差别很大么？

**Comment by atian25** [comment]
> 打个比方，例如我们有个消息队列的消费者，我们会用INFO记录开始消费，结束消费，然后会尝试把消息用DEBUG记录，因为假如不记录呢生产环境真实报错的时候就无法重现问题了，假如用文件记录呢，数据量好像又有点大，所以才想到用控制台输出 T_T

没太看明白，控制台输出的话，出问题了你怎么查？
至于数据量问题，如果你的诉求就是要 log 所有的消费记录，那必不可少啊。只能通过切割，转存等方式解决。

先关闭了，如果有其他疑问，欢迎 reopen。
