### ISSUE TITLE
官方没出 egg-ratelimit 吗

### ISSUE THREAD

**Issue by musicode** [eggjs/egg#3382]
我找了一些第三方的库，包括死马写的，都不是很合适，为啥都不支持内存存储呢？

我的需求很简单，大概就以下几个：

1. 内存存储
2. 可配置 ip 或别的字段（比如 session id）进行限制
3. 可配置接口的调用频率，比如 a 接口一分钟几次，b 接口一分钟几次

不是很理解为啥官方为啥没出这个库，难道这个需求不常见吗

**Comment by musicode** [comment]
[ratelimit](https://github.com/koajs/ratelimit) 这个库需要实例话一个 redis，`egg-redis` 本身有一个实例，这里又新建一个，感觉不是很好...

**Comment by whxaxes** [comment]
@musicode 你直接把 egg-redis 里的实例传进去不就行了

**Comment by popomore** [comment]
看看能否基于这个扩展 https://github.com/eggjs/egg-guardian

**Comment by ZQun** [comment]
@musicode https://github.com/ZQun/egg-ratelimiter   基于[ratelimiter](https://github.com/tj/node-ratelimiter)

**Comment by windmemory** [comment]
> https://github.com/ZQun/egg-ratelimiter 基于ratelimiter

这个东西我试了，没用明白。。。有人提issue，也没人理。。。
