### ISSUE TITLE
egg-static 如何在生产环境禁止html文件缓存

### ISSUE THREAD

**Issue by Tomatoo** [eggjs/egg#3383]
## What happens?

我们有一个单页应用，前端编译之后把index.html，static/.js .css 放到public下面发布。js和css都有一年的缓存这个是OK的，但是我们不想把index.html也加了一年的缓存。这个要如何做到呢？

我阅读了egg-static的文档和源码，没有找到实现方式，所以问一下大家这个问题如何处理，谢谢～

## 相关环境信息
- **操作系统**：Linux
- **Node 版本**：8.X.X
- **Egg 版本**：2.6.1

**Comment by whxaxes** [comment]
static 下放静态资源文件，主文档这种不要放到静态资源目录吧

**Comment by atian25** [comment]
既然是编译的，可以配置下，把  html 编译到 app/view 目录下，作为模板。

**Comment by atian25** [comment]
如果有其他问题，欢迎重新开启。

**Comment by asiareal** [comment]
可是app/view 需要写router，还需要重启

**Comment by atian25** [comment]
你可以看下 egg-static 源码，或许可以自定义 files 那个 cache，然后做清理 cache 的处理。
