### ISSUE TITLE
Internal Server Error, real status: 500

### ISSUE THREAD

**Issue by nianiaJR** [eggjs/egg#3385]
## What happens?
通过 egg-init 初始化了一个typescript 的项目，根据README进行本机部署：
```
npm run tsc
npm start
```
服务器启动成功，但是访问地址后报错：Internal Server Error, real status: 500
PS: npm run dev 开发环境访问正常

## 最小可复现仓库
https://github.com/nianiaJR/assets-with-webpack

## 复现步骤，错误日志以及相关配置
```
git clone https://github.com/nianiaJR/assets-with-webpack.git
npm install
npm run tsc
npm start
访问: http://127.0.0.1:7001
```

## 相关环境信息
- **系统：macOS 10.13.4**：
- **node：v11.4.0**：
- **Egg 版本: 2.14.1**：

**Comment by whxaxes** [comment]
看一下 common-error.log 里有没有错误日志

**Comment by nianiaJR** [comment]
自己的锅，模板写的有问题。。

**Comment by nianiaJR** [comment]
> 看一下 common-error.log 里有没有错误日志

日志是空的，我把--deamon去掉后，开启了 disableConsoleAfterReady: false 后，在控制台能看见具体错误了。

**Comment by whxaxes** [comment]
egg-scripts start 的日志不在项目下，在 ~/logs/{your app name}/ 里

**Comment by nianiaJR** [comment]
> egg-scripts start 的日志不在项目下，在 ~/logs/{your app name}/ 里

这样...那 app/logs 这个目录下的日志是谁的？

**Comment by whxaxes** [comment]
@nianiaJR  egg-bin dev 的话，会在 app/logs 下生成

**Comment by nianiaJR** [comment]
@whxaxes 明白了，感谢。（再看了一遍文档，确实有描述，当时没get到。。）

**Comment by alabihula** [comment]
@nianiaJR ni 我也是用tpl模板发布到docker后 访问500 接口可以，请问你是怎么解决的
