### ISSUE TITLE
[Feature Request] egg-core可以增加“.”作为文件命名吗？

### ISSUE THREAD

**Issue by ZQun** [eggjs/egg#3387]
## Proposal
``` javascript
    // 可以加入 . 作为文件命名方式吗？  如：alinode.user.js
    if (!/^[a-z][a-z0-9_.-]*$/i.test(property)) {
        throw new Error(`${property} is not match 'a-z0-9_.-' in ${filepath}`);
    }
```

https://github.com/eggjs/egg-core/blob/ec8f904140865e624130904fffbe512971e7fdaa/lib/loader/file_loader.js#L233

## Additional context
https://github.com/eggjs/egg/issues/4

**Comment by atian25** [comment]
啥场景？

**Comment by ZQun** [comment]
@atian25 在项目目录app/controller或app/service下创建 alinode.user.js 方式命名文件时会有报错，不知道可不可以支持以符号“ . ”作为命名连接符，config配置目录下的命名也是 config.default.js 和 config.local.js 方式～

在egg-core/lib/loader/file_loader.js 正则判断中加入“ . ”会有其他影响吗？
``` node.js
if (!/^[a-z][a-z0-9_.-]*$/i.test(property)) {
    throw new Error(`${property} is not match 'a-z0-9_.-' in ${filepath}`);
}
```

![wx20190110-183040](https://user-images.githubusercontent.com/12726554/50962821-0aff4780-1506-11e9-8857-c13f6d813261.png)

**Comment by atian25** [comment]
这种感觉用 `alinode/user.js` 或 alinode_user.js 更好

**Comment by popomore** [comment]
增加也可以，不过这个规则比较复杂

**Comment by atian25** [comment]
这样的话。从一个 service.alinode.user.echo() 上就无法直观的知道对应对应哪个文件了。我建议是能用目录就目录吧

**Comment by ZQun** [comment]
嗯嗯，那我还是用回“ _ ”好了

**Comment by atian25** [comment]
看你想怎么用：

- `app/service/alinode/user.js` -> `ctx.service.alinode.user.METHOD()`
- `app/service/alinode_user.js` -> `ctx.service.alinodeUser.METHOD()`
