### ISSUE TITLE
egg中使用graphql，Mutation请求怎么进行单元测试？

### ISSUE THREAD

**Issue by Surile** [eggjs/egg#3389]
![image](https://user-images.githubusercontent.com/28652894/50967590-7dc2ef80-1513-11e9-8b42-1da59fa6e20f.png)

```javascript
/graphql?query=query+foods($page:Int!,$per_page:Int!){foods(page:$page,per_page:$per_page){id}}&variables={"page":1,"per_page":1}
```
以上Query测试

附带Query测试成功图

![image](https://user-images.githubusercontent.com/28652894/50967659-b8c52300-1513-11e9-963b-d0a706888308.png)

但如果是mutation怎么进行单元测试呢？

**Comment by Meriky** [comment]
mutation和query本质上没区别吧？

**Comment by Surile** [comment]
@Meriky  有的。mutation出现500

**Comment by thonatos** [comment]
query 与 mutation 只是参数不一样，检查一下代码逻辑。

**Comment by Meriky** [comment]
@Surile  你具体代码我不清楚，但是mutation出现500意味着这个test case失败了吧？ check一下自己的逻辑为什么导致失败吧。

**Comment by Surile** [comment]
嗯。行。

**Comment by jtyjty99999** [comment]
mutation 这种，你做测试可以用mysql或者sequlize去读一下数据库看看是否生效

**Comment by Surile** [comment]
@jtyjty99999 嗯，是可以的。
