### ISSUE TITLE
请问一下egg如何接入next呢

### ISSUE THREAD

**Issue by LLLLLamHo** [eggjs/egg#3393]
在使用egg的过程中如何正确接入next呢？

**Comment by LLLLLamHo** [comment]
NextJS

**Comment by thonatos** [comment]
> 不建议在 Egg.js 中配置 Next.js
> Koa 与 Express 部分实现不一致，如有需求，请自行探索或使用其他方案

**链接:**

- https://github.com/easy-team/easywebpack
- https://github.com/alibaba/beidou

**Comment by thonatos** [comment]
看到在知乎的帖子用了`既然`，貌似我在 issue 下面的回复有点让你有点误解？

- 首先，高度封装的 `Next.js` 出现问题很难排查，个人尝试过之后放弃了，所以我不建议
- 其次 `Egg.js` 作为框架本身提供的是扩展能力，自行探索也是回馈社区、参与开源的方式
- 最后，最佳实践因人而异，请勿贴标签，这样很容易被带节奏的

Anyway，本人回复的一贯原则是不带情绪的，如果有疑问请直说，在能力范围内会尽力解答。
