### ISSUE TITLE
set cookie疑问

### ISSUE THREAD

**Issue by wuyugege** [eggjs/egg#3399]
controller里代码

ctx.cookies.set('0o','008')

postman得到的响应 ：

set-cookie →0o=008; path=/; httponly
set-cookie →0o.sig=BKz_FtEld6gVjNwSzdNZAXZCq3n2Vf7VcHISiEBp7oc; path=/; httponly

为什么会多一个？

**Comment by atian25** [comment]
sign 是加签，避免伪造。
不需要的话在 option 里面加参数，具体看egg cookie 文档 和 egg-cookie
