### ISSUE TITLE
egg的curl方法不支持await调用

### ISSUE THREAD

**Issue by 14glwu** [eggjs/egg#3406]
## What happens?
插件里的代码用到了ctx.curl()方法，并且是await方式调用的，但是项目里的代码使用的是egg@1.7，导致ctx.curl方法不能通过await调用，只能通过yield方式调用。
想问下，除了给插件写两个版本（yield方式调用与await方式调用）和升级egg版本，还有其他解决办法吗

## 相关环境信息
- **操作系统**：windows
- **Node 版本**：8.9
- **Egg 版本**：1.7

**Comment by atian25** [comment]
自己 wrap 个 co

**Comment by popomore** [comment]
如果不想升级，其实用 yield 没差，wrap 还影响性能。
