### ISSUE TITLE
部署在Docker后，日志中没有任何新的输出

### ISSUE THREAD

**Issue by huowenxuan** [eggjs/egg#3407]
## What happens?
在部署到Docker之前是好的，logs下有正常的log，部署Docker之后再也没有新的log了，请问还需要什么设置吗

## 复现步骤，错误日志以及相关配置

```
config.logger = {
  consoleLevel: 'INFO'
}
```

## 相关环境信息
- **操作系统**：Mac
- **Node 版本**：10.10.0
- **Egg 版本**：2.13.0

**Comment by houxiaofei123** [comment]
代码中 调用ctx.logger  才会有日志输出吧

**Comment by huowenxuan** [comment]
@houxiaofei123 当然调用过了，我的日志停留在半个月前

**Comment by kennylbj** [comment]
docker exec -it /bin/bash 上去
然后看看 ```/root/logs```目录
建议挂在到主机

**Comment by guoshencheng** [comment]
先docker exec -it container-id bash 进入到容器内查看一下日志文件是否真实存在
确认存在后 docker inspect container-id 查看一下你的volume

**Comment by huowenxuan** [comment]
感谢大家，解决了
1. 先docker exec -it container-id bash 进入到容器内，/root/logs中有日志
2. 在docker-compose.yml中添加`volumes: - /root/logs:/root/logs`挂载到主机

**Comment by zhaoxiaobao** [comment]
坑
