### ISSUE TITLE
flow 转向ts了

### ISSUE THREAD

**Issue by mymickey** [eggjs/egg#3409]
egg计划什么时候推送正式的ts重写版本呢，包括vscode等开发套件支持。

**Comment by YiQieSuiYuan** [comment]
> egg计划什么时候推送正式的ts重写版本呢，包括vscode等开发套件支持。

https://midwayjs.org/midway/
阿里基于egg-core+TS

**Comment by mymickey** [comment]
> > egg计划什么时候推送正式的ts重写版本呢，包括vscode等开发套件支持。
> 
> https://midwayjs.org/midway/
> 阿里基于egg-core+TS

egg不在维护了？

**Comment by popomore** [comment]
为何这么问，midway 是 egg 上层框架

**Comment by lky5230** [comment]
鄙人还没用过flow、ts呢

**Comment by atian25** [comment]
egg 目前没有计划使用 TS 重写底层。

作为应用开发者，也不需要太关心底层是用什么语言写的。

更多应该关系的是，应用开发这一层，怎么用 TS 编写，这块目前我们是有支持的，可以看下对应的文档。

年后会再小优化一波：
- egg-ts-helper 内置集成
- js 项目也能享受到 d.ts 的智能提示
