### ISSUE TITLE
egg-sequelize 需要支持的其他功能

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#341]
参考内网egg-model:

- sql执行时间
- associations
- Migration
- ctx bind ctx.User => app/models/user.js

**Comment by fengmk2** [comment]
2个合并成一个吧

**Comment by atian25** [comment]
https://github.com/eggjs/egg-sequelize/pull/2

**Comment by jtyjty99999** [comment]
@atian25  这个issue里提到的几个feature不是在这个mr里做的，应该要另外开一个了

**Comment by atian25** [comment]
嗯, 所以相关的 MR 都 link 到这里.

**Comment by jtyjty99999** [comment]
ok

**Comment by popomore** [comment]
这个建表是分离的吧？ 不需要调用 sync？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-sequelize/pull/3

**Comment by cycgit** [comment]
考虑支持 驼峰 <=>下划线 吗
数据库一般下划线字段。应用代码都驼峰

**Comment by popomore** [comment]
@cycgit 你是想默认支持吗？

**Comment by cycgit** [comment]
@popomore 默认关闭 再加一个参数 `camelCase ` 加载 model 的时候统一处理

**Comment by popomore** [comment]
这个可以支持的，我原来做过
chenyancheng <notifications@github.com>于2017年2月18日 周六21:07写道：

**Comment by atian25** [comment]
@cycgit 可以直接 PR

**Comment by yuzukwok** [comment]
egg-sequelize 中 sequelize 构造子除了预定义的options，其他如timezone等 无法从config 配置中读取，只能通过代码设置，希望能够改进下

**Comment by atian25** [comment]
@jtyjty99999 @huacnlee 有空补下 guide doc

**Comment by a304885433** [comment]
@cycgit  camelCase  这个参数，最新的egg框架里有了吗，请问在哪里配置，旨在支撑  
``` 数据库一般下划线字段。应用代码都驼峰 ```

**Comment by yeomanyang** [comment]
> @cycgit @popomore camelCase 这个参数，最新的egg框架里有了吗，请问在哪里配置，旨在支撑
> `数据库一般下划线字段。应用代码都驼峰`

同问
