### ISSUE TITLE
重启服务

### ISSUE THREAD

**Issue by fabin5** [eggjs/egg#3410]
我们现在有个场景是前端依赖于后端，所以没有在发现服务中获取到后端的地址就不启动，那么我是在app.js中一直等待后端启动完毕，还是说egg有提供类似自杀重启的功能？   注：之前使用express的时候是直接自杀，然后自动重启。

**Comment by popomore** [comment]
那个时候就不应该发布，应用都已经接收流量了。

**Comment by fabin5** [comment]
> 那个时候就不应该发布，应用都已经接收流量了。

@popomore  我们redis的地址也是要从发现服务中获取啊。而node应用比较快启动，必须等等待啊。egg又会等待超时。所以想知道怎么处理？

**Comment by popomore** [comment]
超时默认应该30s 吧，取个链接应该很快吧。

**Comment by fabin5** [comment]
> 超时默认应该30s 吧，取个链接应该很快吧。

@popomore  不是啊。。有个等待的过程啊。就是大家的应用一起启动，node应用启动的明显比后端的服务快很多啊。

**Comment by popomore** [comment]
这是 paas 的问题，这里不讨论了，你可以把超时时间设长一点。
