### ISSUE TITLE
How can i get the current controller name

### ISSUE THREAD

**Issue by merize1336912093** [eggjs/egg#3411]
## What happens?
my program is many channels.I want to get the current controller name

**Comment by popomore** [comment]
If you are in middleware, you can’t. If you are in controller, you can use this.contructor.name

**Comment by merize1336912093** [comment]
> If you are in middleware, you can’t. If you are in controller, you can use this.contructor.name

【Property 'contructor' does not exist on type 'IndexController'.】I get this.
sorry,I don't understand your meaning..I want to get the current controller name and the current method name.But,this.contructor.name can't get.

**Comment by popomore** [comment]
```js
class IndexController {}
const i = new IndexController()
i.constructor.name
```

**Comment by Jeff-Tian** [comment]
> If you are in middleware, you can’t. If you are in controller, you can use this.contructor.name

有个场景，是在每个请求后打印请求日志，记录一些信息，如耗费了多长时间，处理这个请求的 controller 是哪个等等。

目前我们是通过一个中间件来完成这个请求日志的打印，请求时间解决了。但是打印 controller 的名字，没想到办法。看这个回复，是没有可能吗？对于这个需求，如果不能在中间件中打印出来，能给点其他思路吗？不太想在每个 controller 里去写代码记录，有没有办法在一个地方集中处理？

**Comment by atian25** [comment]
@Jeff-Tian `ctx.routerPath` and `ctx.routerName`

https://github.com/eggjs/egg-router/pull/2/files

**Comment by Jeff-Tian** [comment]
@atian25 谢谢。不过这个和 `ctx.url` 类似，能拿到路由，但是拿不到相关的 controller 信息？

**Comment by atian25** [comment]
自己获取呗。

`router.get('home.index', '/', controller.home.index)`

你获取到前面的 name 了，自己根据规则不就能获取到 controller 了。

**Comment by Jeff-Tian** [comment]
理解了，谢谢！
