### ISSUE TITLE
【内存泄漏】egg-core的timing对属性占用未释放造成内存泄漏

### ISSUE THREAD

**Issue by eternaltreesnow** [eggjs/egg#3412]
## What happens?
使用[TSW](https://github.com/Tencent/TSW)配合egg-core搭建node服务，发现egg-core的`timing`特性对属性存在引用，且在整个`Application`生命周期内未释放，导致内存泄漏

## 最小可复现仓库
[egg-memoryleak-demo](https://github.com/eternaltreesnow/egg-memoryleak-demo)

由于引用了TSW，因此未用egg-init进行初始化，在仓库中已提供启动和复现方式。

## 复现步骤
 1. 安装TSW
 2. 安装egg-memoryleak-demo
 3. 启动demo后，进行正常访问和压测，发现MEM占用逐渐升高，且在请求量下降后未恢复正常状态
 4. 本地验证的snapshot日志提供在仓库的 `heapdump` 目录

## 错误截图
 1. heapsnapshot截图
![heapsnapshot](https://raw.githubusercontent.com/eternaltreesnow/egg-memoryleak-demo/master/img/snapshot%E6%88%AA%E5%9B%BE.png)

 2. 修复前后的MEM曲线
![mem曲线](https://raw.githubusercontent.com/eternaltreesnow/egg-memoryleak-demo/master/img/MEM%E6%9B%B2%E7%BA%BF%20-%20%E4%BF%AE%E5%A4%8D%E5%89%8D%E5%90%8E.png)

## 相关环境信息
- **操作系统**：
  * macos 10.13.6
- **Node 版本**：
  * v10.7.0
- **Egg 版本**：
  * egg-core@4.13.1

**Comment by atian25** [comment]
为什么直接用 egg-core

**Comment by fengmk2** [comment]
timing 只在启动加载阶段会使用，请求响应阶段不会进去才对的。

**Comment by popomore** [comment]
不用 tsw 启动试试，排除他的可能

**Comment by atian25** [comment]
TSW 的这个示例用法是不正确的，https://github.com/eternaltreesnow/egg-memoryleak-demo/blob/master/app.js

**Comment by Jeff-Tian** [comment]
不清楚是不是同样的原因，我的 egg 项目在本地存在内存占用不断变高的问题：

我在 macOS 机器上开发 egg 项目，并没有 `npm start`，只是 `npm run test-local`，测试都是按照文档来的，对 controller 和 service 进行了测试。

连续几天的开发（差不多一个星期左右，具体运行了多少次 `npm run test-local` 没有统计过）之后，发现内存占用变得特别高。用 Activity Monitor 查看下来，是这样的情况：

![image](https://user-images.githubusercontent.com/3367820/51588127-231b9180-1f1e-11e9-8619-a7a85a471055.png)

![image](https://user-images.githubusercontent.com/3367820/51588152-362e6180-1f1e-11e9-9fd2-53f2ff6b6e55.png)

**Comment by popomore** [comment]
dev 本地开了几天？本地不会做优化，有些做法也比较粗暴，建议部署到服务器配合 alinode 来确认是否内存泄漏。

**Comment by Jeff-Tian** [comment]
没有开本地 `npm run dev`，只是 `npm run test-local`，感觉 `npm run test-local` 之后，并没有完全退出，有东西驻留，所以内存占用一直增长。

本地我先通过杀掉进程解决吧。谢谢啦

**Comment by popomore** [comment]
单测跑完就推出的，估计用法有问题。

**Comment by eternaltreesnow** [comment]
> 为什么直接用 egg-core

因为服务本身是由TSW管理的，只是引入egg-core来使用egg本身的一些能力

**Comment by Jeff-Tian** [comment]
单测完全照文档来的，用法没什么问题。

我能快速重现这个问题了，我怀疑问题出在 egg-bin。

1. 写一个单测，故意弄一个死循环。
```
const a= [];

app.mockService('xxx', 'yyy', ()=>{
    while (true) {
         a.push('xxx');
    }
});
it('xxx', async () => {
      await ctx.service.xxx.yyy();
    });
```
2. `npm run test-local`  跑起来测试，测试卡死在这里
3. 按 `ctrl + c` 强行退出测试，命令行正常退出。但是实际上 node 进程没有被杀死，会导致机器变慢，内存不停增长。

有空了我创建一个重现这个问题的代码库出来。

**Comment by Jeff-Tian** [comment]
内存泄漏问题演示代码仓库：https://github.com/Jeff-Tian/egg-memory-leak

重现步骤：
- git clone 到本地,
- npm run test-local
- ctrl + c 强制退出测试

不到 10 分钟，node 进程的内存占用就跑到了 8 G 以上……

![image](https://user-images.githubusercontent.com/3367820/51955444-ea7c3a80-247e-11e9-8623-0436a65ea88f.png)

为什么 ctrl+c 强制退出测试后，node 进程不退出？而且随着 npm run test-local 的重复执行， node 进程会越来越多……

**Comment by hyj1991** [comment]
https://github.com/Jeff-Tian/egg-memory-leak/blob/master/app/controller/home.js#L17

egg/koa 不支持自己去操作原始的 res 吧

**Comment by hyj1991** [comment]
https://github.com/Jeff-Tian/egg-memory-leak/blob/master/app/controller/home.js#L16

这个泄漏看起来是你的 while 循环一直没结束导致的，你可以在里面加一行日志就知道了

**Comment by hyj1991** [comment]
起码你给出来的最小复现仓库本身业务代码就是问题的，而且似乎和 issue 的描述并没有什么关系，事实上一个无限 wirte 而不去 end 的可写流怎么写都会泄漏的。。。

**Comment by hyj1991** [comment]
node 不会退出，那是因为测试进程是用子进程的方式启动的，ctrl + c 只是退出了主进程，并且主进程会向子进程发一个 signal 来让其退出

但是因为此时你写了一个死循环，事件循环机制下子进程根本没有机会去处理这个 signal，当然就无法退出了

**Comment by Jeff-Tian** [comment]
OK 了解了，谢谢。

> node 不会退出，那是因为测试进程是用子进程的方式启动的，ctrl + c 只是退出了主进程，并且主进程会向子进程发一个 signal 来让其退出
> 
> 但是因为此时你写了一个死循环，事件循环机制下子进程根本没有机会去处理这个 signal，当然就无法退出了
