### ISSUE TITLE
路由 resources 模式下无法访问到destroy

### ISSUE THREAD

**Issue by yioMe** [eggjs/egg#3413]
router 路由设置

`router.resources('qrcode', '/api/qrcode', controller.qrcode);`

controller 控制器设置

`'use strict';

const Controller = require('egg').Controller;

class QrcodeController extends Controller {
  async index() {
    const { ctx } = this;
    const { page } = ctx.request.query;
    ctx.boyd = '这里可以使用';
  }
  async destroy() {
    const { ctx } = this;
    ctx.body = 1;
  }
}

module.exports = QrcodeController;
`

我在前台使用这个路由的时候
通过get 可以访问到 index
通过 DELETE 访问不到 destroy
如果将路由改为
` router.del('qrcode', '/api/qrcode', controller.qrcode.destroy); `
可以访问，有点搞不清楚问题在哪，好像put也有这个问题，有人能告诉我哪里错了吗？

> 具体的 router.resources 的使用文档看这里：https://eggjs.org/zh-cn/basics/router.html#restful-%E9%A3%8E%E6%A0%BC%E7%9A%84-url-%E5%AE%9A%E4%B9%89

我确定已经参考文档使用了但还是存在问题
路由设置
![image](https://user-images.githubusercontent.com/24558416/51421300-50430980-1bd7-11e9-96e3-cece18650baa.png)

控制器设置

![image](https://user-images.githubusercontent.com/24558416/51421297-47523800-1bd7-11e9-8b15-18b8c7e5a224.png)

postman请求结果

![image](https://user-images.githubusercontent.com/24558416/51421307-60f37f80-1bd7-11e9-905e-bfaa78e4afdc.png)

但是同路由下的index可以访问

![image](https://user-images.githubusercontent.com/24558416/51421311-78326d00-1bd7-11e9-84b3-e8b4a15f79db.png)

**Comment by popomore** [comment]
Delete 后面要带 id

**Comment by okoala** [comment]
具体的 router.resources 的使用文档看这里：https://eggjs.org/zh-cn/basics/router.html#restful-%E9%A3%8E%E6%A0%BC%E7%9A%84-url-%E5%AE%9A%E4%B9%89

**Comment by okoala** [comment]
@yioMe  要这么调
DELETE: `api/qrcode/1`
