### ISSUE TITLE
egg-cluter connection.clsoe is not a function

### ISSUE THREAD

**Issue by kiddnoke** [eggjs/egg#3414]
## What happens?
same as #2258 
在线上生产环境中，eggjs服务实例处在负债均衡后端。由于产品需要使用egg-websockets的功能。负载均衡器需要使用长链接维持机制。负载均衡器的探测方式为tcp三次握手后立即发送RST包。
以上因此egg吐出如下报错

![_20190118205912](https://user-images.githubusercontent.com/5365363/51388327-05d47500-1b64-11e9-9a7c-9736e89fff1a.png)

服务器的文件句柄被耗尽
![image](https://user-images.githubusercontent.com/5365363/51388432-5ba91d00-1b64-11e9-89cc-450ac7218859.png)

后来在线上紧急修改这段代码，病就治好了
![image](https://user-images.githubusercontent.com/5365363/51388994-03731a80-1b66-11e9-957e-c04b3688690a.png)

Node官方文档net模块中也没有socket.close的方法
[https://nodejs.org/dist/latest-v10.x/docs/api/net.html](url)

## Mini Showcase Repository 
 
抱歉确实没法提供可复现的例子，但是提供的材料已经足够说明这个bug
## How To Reproduce

**Steps to reproduce the behavior:**
1.
![image](https://user-images.githubusercontent.com/5365363/51388570-d4a87480-1b64-11e9-99b8-0eea2bae740e.png)

2.

**Expected behavior**
1.抛出异常
![image](https://user-images.githubusercontent.com/5365363/51388573-da05bf00-1b64-11e9-951b-3a2b343c47d5.png)

2.文件句柄耗尽，监听端口无法接受新的连接
![image](https://user-images.githubusercontent.com/5365363/51388587-e1c56380-1b64-11e9-90f4-926f66f262f3.png)

## Context
- **Node Version**:
v10.13.0
- **Egg Version**:
2.2.1
- **Plugin Name**:
egg-cluster
- **Plugin Version**:
1.22.2
- **Platform**:
CentOS *

**Comment by atian25** [comment]
egg-websockets 这个不是官方维护的包

**Comment by hyj1991** [comment]
@kiddnoke egg-cluster 的版本？

**Comment by ngot** [comment]
https://github.com/eggjs/egg-cluster/pull/89

**Comment by ngot** [comment]
fixed at egg-cluster@1.23.2
