### ISSUE TITLE
一段sql，在工具里不报错，用egg-mysql报错

### ISSUE THREAD

**Issue by yuu2lee4** [eggjs/egg#3415]
````sql
SELECT @g7tv_car_day_stat_security_rank_number:=-1,@g7tv_car_day_stat_security_rank_row:=0;INSERT INTO g7tv_car_day_stat (carnum,driverid,truckid,ymd,orgroot, stat_level, stat_orgcode, security_rank)
      SELECT carnum,driverid,truckid,ymd,orgroot, 0 AS stat_level, '' AS stat_orgcode,security_rank FROM (SELECT
          carnum,driverid,truckid,ymd,orgroot, (CASE WHEN security_km_time = @g7tv_car_day_stat_security_rank_number THEN
                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row
              ELSE
                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row + 1
      END) AS security_rank, (SELECT @g7tv_car_day_stat_security_rank_number:= security_km_time)
      FROM
          g7tv_car_day_basic
      WHERE ymd = 20190118 AND risk_mile > 0
      ORDER BY
        security_km_time ASC
      LIMIT 0, 500) sortTable where sortTable.orgroot in ('20013X', '2015BO', '2000BG', '201MZO', '201IAD', '201H10', '201MBJ', '200QUS', '20147J', '201IE7', '201JSD', '201M1H', '201L57', '201K6T', '201G3R', '200ROX', '2014PB', '201JJE', '200P6E', '201LAW', '201L9S', '200QBB', '201EX9','200OXI', '2007YF', '200RCA', '201FI5', '200YE3', '201MAO', '200G82', '201CB6', '201MWK', '200EXO', '20102N', '20078K', '201LGJ', '201D11', '200098', '201CBV', '201EZ8', '200J90', '200TYW', '20007K', '20152G', '200OXY', '20008D', '20009D', '200J6A', '201FO7', '200GPP', '2019U8', '200096', '200LJA', '201DUC', '201R3T', '201KQ2', '201MNI', '201QGX', '2018XM', '200LRH', '200LCX', '201IMG', '201N7Y', '2002FB', '201SEB', '2001LF', '200LS1', '20100D', '201170', '200PZU', '200V18', '20168H', '200OYR', '2008K4', '201TUE', '2017SC', '200D5U', '201IYK', '201HKB', '200X64', '201WI3', '201WPG', '200UK2', '201XEE', '200GYM', '200CLX', '201KCR', '201KAN', '201O05', '201OCX', '201I3D', '201NY7', '201URQ', '200059', '200K61','201Z7C', '201PUY', '200028', '200CGK', '201KBK', '2001EP', '200A4L', '201FOU', '201FRL', '201N65', '2007V4', '201Q3B', '201IZH', '201UGW', '200000', '20005E', '201VM6', '2017B6', '201VST', '201VJ5', '201WPR', '201LHE', '201SAD', '201DPU', '201P31', '201YV3', '201JJF', '201XDC', '20089X', '201Y9F', '201Y3L', '20135P', '201K7G', '2020WT', '200YP0') ON DUPLICATE KEY UPDATE security_rank = VALUES(security_rank);SELECT @g7tv_car_day_stat_security_rank_number, @g7tv_car_day_stat_security_rank_row LIMIT 1
````
在navicat、tableplus都不报错，能成功执行，但是用this.database.query执行报错，报错信息如下:

2019-01-19 18:34:08,414 ERROR 21408 nodejs.unhandledRejectionError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual thatcorresponds to your MySQL server version for the right syntax to use near 'INSERT INTO g7tv_car_day_stat (carnum,driverid,truckid,ymd,orgroot, stat_level, ' at line 1
    at Query.Sequence._packetToError (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Pool.query (/Users/yuri/work/tv-node-schedule/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/yuri/work/tv-node-schedule/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/yuri/work/tv-node-schedule/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/yuri/work/tv-node-schedule/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/yuri/work/tv-node-schedule/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/yuri/work/tv-node-schedule/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/yuri/work/tv-node-schedule/node_modules/co/index.js:65:19)
    at /Users/yuri/work/tv-node-schedule/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at RDSClient.co (/Users/yuri/work/tv-node-schedule/node_modules/co/index.js:50:10)
    at RDSClient.createPromise [as query] (/Users/yuri/work/tv-node-schedule/node_modules/co/index.js:30:15)
    at ScheduleTaskService.calcRankForLevel (/Users/yuri/work/tv-node-schedule/app/service/scheduleTask.ts:108:28)
    at batchExec (/Users/yuri/work/tv-node-schedule/app/service/scheduleTask.ts:85:30)
    at ScheduleTaskService.batchExec (/Users/yuri/work/tv-node-schedule/app/service/scheduleTask.ts:164:13)
    sql: SELECT @g7tv_car_day_stat_security_rank_number:=-1,@g7tv_car_day_stat_security_rank_row:=0;INSERT INTO g7tv_car_day_stat (carnum,driverid,truckid,ymd,orgroot, stat_level, stat_orgcode, security_rank)
      SELECT carnum,driverid,truckid,ymd,orgroot, 0 AS stat_level, '' AS stat_orgcode,security_rank FROM (SELECT
          carnum,driverid,truckid,ymd,orgroot, (CASE WHEN security_km_time = @g7tv_car_day_stat_security_rank_number THEN
                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row
              ELSE
                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row + 1
      END) AS security_rank, (SELECT @g7tv_car_day_stat_security_rank_number:= security_km_time)
      FROM
          g7tv_car_day_basic
      WHERE ymd = 20190118 AND risk_mile > 0
      ORDER BY
        security_km_time ASC
      LIMIT 0, 500) sortTable where sortTable.orgroot in ('20013X', '2015BO', '2000BG', '201MZO', '201IAD', '201H10', '201MBJ', '200QUS', '20147J', '201IE7', '201JSD', '201M1H', '201L57', '201K6T', '201G3R', '200ROX', '2014PB', '201JJE', '200P6E', '201LAW', '201L9S', '200QBB', '201EX9','200OXI', '2007YF', '200RCA', '201FI5', '200YE3', '201MAO', '200G82', '201CB6', '201MWK', '200EXO', '20102N', '20078K', '201LGJ', '201D11', '200098', '201CBV', '201EZ8', '200J90', '200TYW', '20007K', '20152G', '200OXY', '20008D', '20009D', '200J6A', '201FO7', '200GPP', '2019U8', '200096', '200LJA', '201DUC', '201R3T', '201KQ2', '201MNI', '201QGX', '2018XM', '200LRH', '200LCX', '201IMG', '201N7Y', '2002FB', '201SEB', '2001LF', '200LS1', '20100D', '201170', '200PZU', '200V18', '20168H', '200OYR', '2008K4', '201TUE', '2017SC', '200D5U', '201IYK', '201HKB', '200X64', '201WI3', '201WPG', '200UK2', '201XEE', '200GYM', '200CLX', '201KCR', '201KAN', '201O05', '201OCX', '201I3D', '201NY7', '201URQ', '200059', '200K61','201Z7C', '201PUY', '200028', '200CGK', '201KBK', '2001EP', '200A4L', '201FOU', '201FRL', '201N65', '2007V4', '201Q3B', '201IZH', '201UGW', '200000', '20005E', '201VM6', '2017B6', '201VST', '201VJ5', '201WPR', '201LHE', '201SAD', '201DPU', '201P31', '201YV3', '201JJF', '201XDC', '20089X', '201Y9F', '201Y3L', '20135P', '201K7G', '2020WT', '200YP0') ON DUPLICATE KEY UPDATE security_rank = VALUES(security_rank);SELECT @g7tv_car_day_stat_security_rank_number, @g7tv_car_day_stat_security_rank_row LIMIT 1
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO g7tv_car_day_stat (carnum,driverid,truckid,ymd,orgroot, stat_level, ' at line 1"
sqlState: "42000"
index: 0
sql: "SELECT @g7tv_car_day_stat_security_rank_number:=-1,@g7tv_car_day_stat_security_rank_row:=0;INSERT INTO g7tv_car_day_stat (carnum,driverid,truckid,ymd,orgroot, stat_level, stat_orgcode, security_rank)\n      SELECT carnum,driverid,truckid,ymd,orgroot, 0 AS stat_level, '' AS stat_orgcode,security_rank FROM (SELECT\n          carnum,driverid,truckid,ymd,orgroot, (CASE WHEN security_km_time = @g7tv_car_day_stat_security_rank_number THEN\n                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row\n              ELSE\n                @g7tv_car_day_stat_security_rank_row:= @g7tv_car_day_stat_security_rank_row + 1\n      END) AS security_rank, (SELECT @g7tv_car_day_stat_security_rank_number:= security_km_time)\n      FROM\n          g7tv_car_day_basic\n      WHERE ymd = 20190118 AND risk_mile > 0\n      ORDER BY\nsecurity_km_time ASC\n      LIMIT 0, 500) sortTable where sortTable.orgroot in ('20013X', '2015BO', '2000BG', '201MZO', '201IAD', '201H10', '201MBJ', '200QUS', '20147J', '201IE7', '201JSD', '201M1H', '201L57', '201K6T', '201G3R', '200ROX', '2014PB', '201JJE', '200P6E', '201LAW', '201L9S', '200QBB', '201EX9', '200OXI', '2007YF', '200RCA', '201FI5', '200YE3', '201MAO', '200G82', '201CB6', '201MWK', '200EXO', '20102N', '20078K', '201LGJ', '201D11', '200098', '201CBV', '201EZ8', '200J90', '200TYW', '20007K', '20152G', '200OXY', '20008D', '20009D', '200J6A', '201FO7', '200GPP', '2019U8', '200096', '200LJA', '201DUC', '201R3T', '201KQ2', '201MNI', '201QGX', '2018XM', '200LRH', '200LCX', '201IMG', '201N7Y', '2002FB','201SEB', '2001LF', '200LS1', '20100D', '201170', '200PZU', '200V18', '20168H', '200OYR', '2008K4', '201TUE', '2017SC', '200D5U', '201IYK', '201HKB', '200X64', '201WI3', '201WPG', '200UK2', '201XEE', '200GYM', '200CLX', '201KCR', '201KAN', '201O05', '201OCX', '201I3D', '201NY7', '201URQ', '200059', '200K61', '201Z7C', '201PUY', '200028', '200CGK', '201KBK', '2001EP', '200A4L', '201FOU', '201FRL', '201N65', '2007V4', '201Q3B', '201IZH', '201UGW', '200000', '20005E', '201VM6', '2017B6', '201VST', '201VJ5', '201WPR', '201LHE', '201SAD', '201DPU', '201P31', '201YV3', '201JJF', '201XDC', '20089X', '201Y9F', '201Y3L', '20135P', '201K7G', '2020WT', '200YP0') ON DUPLICATE KEY UPDATE security_rank = VALUES(security_rank);SELECT @g7tv_car_day_stat_security_rank_number, @g7tv_car_day_stat_security_rank_row LIMIT 1"
name: "unhandledRejectionError"
pid: 21408
hostname: yurideMacBook-Pro.local

但是单独执行中间那段insert的sql又不会报错

**Comment by popomore** [comment]
抱歉无法帮你排查，可以到 mysql 模块提交 issue

**Comment by yuu2lee4** [comment]
#https://github.com/mysqljs/mysql/issues/2167

**Comment by yuu2lee4** [comment]
mysql那边说创建链接加个参数就行了，这个在egg-mysql里怎么配置呢？
问个额外问题，怎么让多次sql执行复用同一个链接？

**Comment by popomore** [comment]
底层有交接池的

**Comment by yuu2lee4** [comment]
解决 用事务来做
