### ISSUE TITLE
[Feature Request] best way to get ctx in controller from an egg-plugin

### ISSUE THREAD

**Issue by chiaweilee** [eggjs/egg#3420]
## Background
I have a egg-plugin repo..
which require to get `this` from controller.

My solution is using `call(this)`,
is there any better way to do this?
Thanks!

## Proposal
...

## Additional context

```JavaScript
// app/controller/home.js
class HomeController extends Controller {
  async index() {
    await this.app.myPlugin.call(this); // 👈
  }
}
```

```JavaScript
// egg-myPlugin
module.exports = function (app) {
  app.myPlugin = function () {
    // this.app.curl('...', { headers: this.ctx.request.headers }) // 👈
    // this.ctx.content // 👈
  }
}
```

**Comment by popomore** [comment]
You can write a service such as application, it will be loaded to ctx.

**Comment by chiaweilee** [comment]
> You can write a service such as application, it will be loaded to ctx.

It may help..
I didn't find any docs or repo(`topic:egg-plugin`) abt writing service in an egg-plugin.

**Comment by atian25** [comment]
why don't you just add a Service at `your_plugin/app/service/Test.js` then you could use `this.ctx.test`

**Comment by chiaweilee** [comment]
> why don't you just add a Service at `your_plugin/app/service/Test.js` then you could use `this.ctx.test`

It's a `plugin` for all repo.
I've refactored it into service.
How should I build `app.js` to hook it on `ctx.service`?
