### ISSUE TITLE
[Feature Request] Graceful stop

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3424]
## Background
When we stop egg, we lost some jobs, it's good egg stop listening to port and accepting new request, response all waiting request, done all jobs and exit

## Proposal
We can have `App.beforeStop` method that returns a promise, We have 2 build in function `stopListening` and `responseAllRequest`

default behavior of `App.beforeStop` is

```js
async beforeStop(){
    await stopListening();
    await responseAllRequest();
}
```

If we need to custom default behavior or extend it it is easy to for instant we can `await waitScheduleDone()`

**Comment by popomore** [comment]
Try to set EGG_MASTER_CLOSE_TIMEOUT to wait app close, default is 5s.

Ref: https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L549

**Comment by sm2017** [comment]
@popomore How it can help?
Assume I set timeout 60 seconds? How it can help me?

**Comment by popomore** [comment]
You can define `beforeClose` in app.js

https://eggjs.org/en/advanced/loader.html#beforeclose

**Comment by sm2017** [comment]
If I implement before close, is stop accepting new requests and stop listening on port handled by egg?
What about pending requests??

**Comment by popomore** [comment]
No, you should stop the request from ingress, and wait a second, then stop the application.

**Comment by sm2017** [comment]
> you should stop the request from ingress

How exactly?

**Comment by popomore** [comment]
I depend on which platform you use, Not the framework do.

**Comment by sm2017** [comment]
@popomore Can you explain , What is the default behavior of eggjs once a worker receive `SIGTERM` ?
Assume the time out is 5 sec

**Comment by atian25** [comment]
see https://github.com/eggjs/egg-cluster and `graceful-process`

**Comment by sm2017** [comment]
@atian25 I see both , and have no idea?
Can you explain a little

**Comment by atian25** [comment]
worker receive `SIGTERM` then will kill itself and do nth, nodejs will handler rest for us.

the master will wait worker and agent to exit for 5s, after that master will kill itself which will trigger worker/agent to force kill itself(at graceful-process)

**Comment by sang4lv** [comment]
@sm2017 You can implement task clean up by setting up a function to listen to `beforeClose` event emitted by egg.js app instance. By default, listeners to `beforeClose` event will timeout and be killed after 5 seconds, which you can adjust with `EGG_MASTER_CLOSE_TIMEOUT` env value. If you have further customization to make, could you kindly state your use case? Thanks.

**Comment by sm2017** [comment]
@atian25 @sang4lv I want to

A. stop accepting new http request
B. waiting for all pending request to get responses 

for `B` I can create counter and once have new request increase it , once responded decrease it, in `beforeClose` wait for zero counter
What about `A`?

**Comment by atian25** [comment]
A and B is a built-in feature of Node.js cluster.

and for A, you may need https://github.com/eggjs/egg-healthy to interaction with ahead Nginx or k8s
