### ISSUE TITLE
[Feature Request] 在eggjs上添加了一个MVC模式的定义模块，怎么样才能挂载Context？

### ISSUE THREAD

**Issue by wscart** [eggjs/egg#3429]
问题描述
1、建了app/modules,modules都是mvc模式的，modeules里面有对应业务逻辑的文件，比如登录，用户管理，权限管理，角色管理。。。等，每个文件都有对应的路由配置，基于egg-router-plus的实现方法。

2、举例在app/modules/users，users里面分别有controllers文件夹，services文件夹，router配置文件。在controllers上请求访问到ctx.modules.users.services.index(),但是访问这个ctx.modules结果是undefined。

操作问题：
eggjs如何将这个定义模块挂载在context上，让任何一个模块里的controllers上请求访问services，services即是ctx.modules.users.services。

**Comment by atian25** [comment]
这算是很深度的定制了，建议你先看下 egg loader 文档，以及研读下 egg-core 的源码

**Comment by wscart** [comment]
@atian25 恩，我研究一下
