### ISSUE TITLE
[Feature Request] modelDir configuration for egg-mongoose

### ISSUE THREAD

**Issue by Songkeys** [eggjs/egg#3433]
## Background
Since egg-sequelize has got `modelDir` supported, could this feature be implemented in egg-mongoose as well? The context is that I want to use mongodb and mysql together in a single project, while sequelize only supports relational databases. So I need another driver like mongoose to handle with mongodb.

## Proposal
Please enable `modelDir` field in egg-mongoose's config.

Thanks.

## 背景
由于 egg-sequelize 已经得到了 modelDir 的支持，这个功能是否也可以在 egg-mongoose 中实现？ 上下文是我想在一个项目中一起使用 mongodb 和 mysql，而 sequelize 只支持关系数据库。 所以我需要另一个像 mongoose 一样的驱动程序来处理 mongodb。

## 提案
请在 egg-mongoose 的配置中启用 modelDir 字段。

谢谢。

**Comment by whxaxes** [comment]
欢迎 PR
