### ISSUE TITLE
[egg-mongoose] cursor?

### ISSUE THREAD

**Issue by liees** [eggjs/egg#3435]
请问目前egg-mongoose是否实现了游标？
如果有可否指点一下在哪里配置或者其他

thanks~

**Comment by whxaxes** [comment]
egg-mongoose 就是对 [mongoose](https://github.com/Automattic/mongoose) 的简易封装，用游标就跟用 mongoose 一样，直接看 mongoose 的文档即可 https://mongoosejs.com/docs/api.html#query_Query-cursor
