### ISSUE TITLE
socket.io  io路由对应的controller层不执行

### ISSUE THREAD

**Issue by lxiaoixi** [eggjs/egg#3438]
## What happens?
> egg-socket.io  io路由对应的controller层代码不执行，middleware 层正常执行

## Mini Showcase Repository(REQUIRED)

https://github.com/lxiaoixi/egg-practice.git

## Context
* Node Version:
  v8.9.0
* Egg Version:
   2.14.2
* Platform:
  win10

**Comment by whlsxl** [comment]
@lxiaoixi 目前代码看不出问题，请问是怎么调用不能执行？

**Comment by ngot** [comment]
@lxiaoixi 具体怎么复现你的问题呢？

**Comment by lxiaoixi** [comment]
@ngot  没问题了，刚开始没弄懂controller层的作用，谢谢了

**Comment by lxiaoixi** [comment]
@ngot 
大神打扰了，想问下
egg-socket.io  使用redis 进行sub/pub时，pub一条消息时，该消息会重复收到两次，这个是怎么回事呢？

相关代码：

[订阅](https://github.com/lxiaoixi/egg-practice/blob/master/app/io/middleware/message.js#L19)
[发布](https://github.com/lxiaoixi/egg-practice/blob/master/app/controller/users.js#L17)

复现：
http://127.0.0.1:7001/ceshi    客户端连接，进行订阅
http://127.0.0.1:7001/api/users   发布消息
