### ISSUE TITLE
egg中使用自定义错误码 报错

### ISSUE THREAD

**Issue by shenqidebaozi** [eggjs/egg#3440]
您好,不知道我的问题是不是耽误你们工作, 我现在在使用中 如果返回自定义错误码.例如520 框架就会报error,但是我有希望使用http状态码,请问可以在哪可以设置?

**Comment by shenqidebaozi** [comment]
看了一下源码.koa有个status json文件,但是如果手动改这个, 协作部署不方便,

**Comment by dead-horse** [comment]
可以看一下你的 koa 是什么版本，最新版 2.7.0 已经去除了这个限制

**Comment by shenqidebaozi** [comment]
是吗??? 我去看一下

**Comment by shenqidebaozi** [comment]
egg这边依赖也升级到2.7.0 了么

**Comment by shenqidebaozi** [comment]
2019-01-31 15:55:38,675 ERROR 25888 [-/127.0.0.1/-/52ms POST /api/v1/service-grades] nodejs.AssertionError [ERR_ASSERTION]: invalid status code: 521
    at Object.set status [as status] (/Users/baozhecheng/test/JSYOEMP/node_modules/_koa@2.6.2@koa/lib/response.js:87:5)
    at Object.status (/Users/baozhecheng/test/JSYOEMP/node_modules/_delegates@1.0.0@delegates/index.js:92:31)
    at Helper.exports.error (/Users/baozhecheng/test/JSYOEMP/app/extend/helper.js:61:14)
    at ServiceGradeService.create (/Users/baozhecheng/test/JSYOEMP/app/service/serviceGrade.js:12:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
generatedMessage: false
name: "AssertionError [ERR_ASSERTION]"
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 25888
hostname: baozhechengdeMacBook-Pro.local

升级了,2.7.0 还是报错

**Comment by shenqidebaozi** [comment]
发下问题了,cnpm安装会有个_koaXXXX

**Comment by shenqidebaozi** [comment]
原来是 cnpm有问题, 会搞出来一个_koa@2,6,x

**Comment by dead-horse** [comment]
重新安装所有依赖就好了

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by shenqidebaozi** [comment]
> hey, please retry after reinstall dependencies and please **never lock** it.
> 
> ```shell
> $ # reinstall deps and never lock it.
> $ rm -rf node_modules yarn.lock package-lock.json
> $ npm i --no-package-lock
> ```

天猪大佬你好,我想问一下,为什么统一错误处理用的http error这个模块,而不是 koa的response

**Comment by dearpeach** [comment]
大佬好
我也碰到了这个问题
用的是koa@2.7.0版本
![image](https://user-images.githubusercontent.com/8085417/59814045-6e5b9400-9346-11e9-970c-7beae8cfa7d2.png)
我看还是会走到这里，自定义错误码 超过999 就会报错，请问该怎么处理？
![image](https://user-images.githubusercontent.com/8085417/59814035-64399580-9346-11e9-8a2a-47436f489804.png)

![image](https://user-images.githubusercontent.com/8085417/59814224-1ec99800-9347-11e9-8b97-1aa871aded8b.png)
@atian25  @shenqidebaozi @dead-horse

**Comment by atian25** [comment]
😓。。。 因为 HTTP 协议规定了 status code 只能是三位数。

```bash
The Status-Code element is a 3-digit integer result code of the
   attempt to understand and satisfy the request. These codes are fully
   defined in section 10. 
```

https://tools.ietf.org/html/rfc2616#section-6.1.1

**Comment by dearpeach** [comment]
那自定义业务错误码 有什么建议么？
@atian25

**Comment by shenqidebaozi** [comment]
> 那自定义业务错误码 有什么建议么？
> @atian25

建议 status 500 然后{errcode:自定义错误码},外部http状态用500,具体错误信息在response里面传递

**Comment by ngot** [comment]
状态吗 RFC 写的很清楚，按照规范定就可以 https://tools.ietf.org/html/rfc2616#section-6.1.1
