### ISSUE TITLE
[Feature Request] 是否可以考虑支持 框架层的 sequelize model

### ISSUE THREAD

**Issue by ColinLeo** [eggjs/egg#3441]
## Background
为了方便代码 复用，我们希望做一个包含 前台、后台、API 的多应用项目，思路是将 model, service 等可能复用的内容放在框架中。
项目结构如下：其中 base 为 Framework；api, www, admin 为3个 Application （InnerApp）。

``` bash
.
├── base
│   ├── app
│   │   ├── extend
│   │   ├── lib
│   │   ├── middleware
│   │   ├── model
│   │   └── service
│   ├── config
├── api
│   ├── app
│   ├── config
│   └── test
├── www
├── admin
```

## Problem

无法在 api 中调用 base 中 model。

## Solution for now

在 InnerApp 中添加 model，直接引用 `base/app/model`，如下：

``` js
// api/app/model/user.js
module.exports = require('../../../base/app/model/user');
```

虽然能够解决问题，但是仅仅相当于复用了文件，而不是复用 models。

## Additional context

有在一个 Issue 中看到说 [sequelize model 只支持应用层，不支持框架层](https://github.com/eggjs/egg/issues/1454#issuecomment-416437053)。请问这个是出于什么考虑呢？或者对于我们这个案例，是否有更优解？

另外在目前的文档中关于 loadunit 的比较，似乎也没有讨论 app/model。app/model 对于 loadunit 的定位到底是怎样的呢？
![image](https://user-images.githubusercontent.com/22308897/52111346-67094780-263e-11e9-8ca7-26fcace2fc3d.png)

## Proposal

理论上是否可以这样做一下支持？

1. sequelize 支持 framework 中的 app/model。

2. Egg.js loadunit 关于 app/model 的继承和 app/service 类似，可以支持 application 调用 framework 中的 model。

**Comment by ColinLeo** [comment]
> 官方插件不会支持框架加载 model，你可以参考这个插件进行实现，loadToApp 的时候可以传入一个数组。

请问是哪个插件？谢谢

**Comment by whxaxes** [comment]
@ColinLeo  egg-sequelize

**Comment by ColinLeo** [comment]
> @ColinLeo [egg-sequelize](https://github.com/eggjs/egg-sequelize)

@whxaxes 
谢谢

**Comment by ColinLeo** [comment]
> 官方插件不会支持框架加载 model，你可以参考这个插件进行实现，loadToApp 的时候可以传入一个数组。

@popomore 
请问官方插件是出于什么考虑，不会做这样的支持呢？
如果我们自己实现的话，是不是需要注意这类问题。

**Comment by atian25** [comment]
因为 Egg 是 框架的框架，它不能把所有的东西都集成进去。

model 这类目前是没有统一的规范的，大家的业务模型都不一样。

这种一般就是在插件里面去挂载即可。

自己实现的话，看下 Loader 文档即可，也可以参考下其他插件的实现。

**Comment by ColinLeo** [comment]
> 因为 Egg 是 框架的框架，它不能把所有的东西都集成进去。
> 
> model 这类目前是没有统一的规范的，大家的业务模型都不一样。
> 
> 这种一般就是在插件里面去挂载即可。
> 
> 自己实现的话，看下 Loader 文档即可，也可以参考下其他插件的实现。

@atian25 
好的，谢谢！
