### ISSUE TITLE
egg-socket.io的ctx上下文不一致的问题

### ISSUE THREAD

**Issue by rojer95** [eggjs/egg#3449]
## What happens?

当使用extend扩展context时，使用egg-socket.io会出现上下文扩展的内容丢失的问题

## 复现DEMO
`app/extend/context.js`主要用于在上下文中存储用户的id, 代码如下:
```javascript
'use strict';
const UID = Symbol('Context#uid');

module.exports = {
  set uid(uid) {
    this[UID] = uid;
  },

  get uid() {
    return this[UID];
  }
};
```

`app/io/middleware/auth.js`在中间件中获取用户认证信息用于获取用户id 设置到ctx上下文中, 代码如下:
```javascript
'use strict';
module.exports = () => {
  return async (ctx, next) => {
    const { socket } = ctx;
    const id = socket.id;
    const query = socket.handshake.query;

    // 获取用户authorization
    const { authorization = null } = query;

    // 用户未提供认证参数, disconnect掉
    if (!authorization) {
      return socket.disconnect();
    }

    try {
      // 认证用户 把uid存到ctx上下文中
      const userInfo = ctx.app.jwt.verify(authorization);
      ctx.uid = userInfo.uid;
    } catch (error) {
      // 用户认证失败, disconnect掉
      return socket.disconnect();
    }

    await next();
  };
};

```
`app/io/controller/event.js`中处理事件, 代码如下:

```javascript
'use strict';

const Controller = require('egg').Controller;

class NspController extends Controller {
  async hello() {
    const { ctx } = this;
    const socket = ctx.socket;
    socket.emit('hello', { user: ctx.uid }); // 这里的ctx.uid 是undefined 
  }
}

module.exports = NspController;


```

## 源码

egg-socket.io插件 在`connectionMiddlewareInit.js`([代码L10](https://github.com/eggjs/egg-socket.io/blob/9e7f71d835930d3a63c69635488737066f779661/lib/connectionMiddlewareInit.js#L10))中进行了`createContext`创建上下文

之后又在socket的事件处理流程中([代码L92](https://github.com/eggjs/egg-socket.io/blob/9e7f71d835930d3a63c69635488737066f779661/lib/io.js#L92))又再一次`createContext`创建上下文

导致了ctx.uid在中间件中设置的数据不能传到Controller中

不知道这样和egg的extend设计有否冲突？还是说egg-socket.io本身就是这样的呢？

**Comment by ngot** [comment]
上面例子中的 `auth.js` 是连接中间件吧。

在 egg-socket.io 的设计中，有两种不同的上下文

- 连接上下文: 用户处理连接请求，此时只有连接本身的相关信息。
- 包上下文: 在已经建立的连接上的通讯请求包。这个上下文不同于连接上下文，它只有此次通讯包所携带的信息。

目前的实现中，没有很好的办法在 controller(其实就是事件处理器，包中间件的最后一个) 中再去获取连接上下文。

一个变通办法就是把 uid 携带在packet中，传递给服务器。

**Comment by ngot** [comment]
If you have more questions, feel free to reopen this issue.
