### ISSUE TITLE
egg-session-redis的index.d.ts

### ISSUE THREAD

**Issue by zheng199512** [eggjs/egg#3450]
## What happens?

数据类型不符~

## index.d.ts

```ts
sessionStore: {
      get: (key: string) => Promise<any>;
      set: (key: string, value: any, maxAge?: number | string) => Promise<void>;
      destroy: (key: string) => Promise<void>;
    };
```

我看到set方法中的maxAge是undefined，string，number。
对于string我有点不理解，在`app.js`中使用了typeof鉴别数据类型

```ts
async set(key, value, maxAge) {
      maxAge = typeof maxAge === 'number' ? maxAge : ONE_DAY;
      value = JSON.stringify(value);
      await redis.set(key, value, 'PX', maxAge);
    },
```

所以我认为string是没有必要的，也可能是我有些情况没有考虑到，望大佬解答~

## Context
- **node：8.12.0**:
- **egg：2.14.1**:
- **Plugin Name：egg-session-redis**:
- **Plugin Version：2.1.0**:
- **Platform：win**:

**Comment by dead-horse** [comment]
maxAge 可能传递为 `session`，代表当前浏览器生命周期生效。在传递到 redis 中设置的失效时间为 ONE_DAY。

**Comment by zheng199512** [comment]
谢谢~
