### ISSUE TITLE
egg-mock上的plugins是什么东西？

### ISSUE THREAD

**Issue by zheng199512** [eggjs/egg#3452]
## What happens?

```ts
app = mock.app({
        baseDir: 'apps/multiple-view-engine',
        //plugins:????
      });
```

您好，我想问一下plugins是要怎么使用的？

遇到的问题：
我进行插件开发的时候更改了插件的目录结构，在最外层运行命令，导致egg-mock不能自动的找到插件，所以需要进行插件位置的自定义。
想请问一下有没有解决方案呢？

![image](https://user-images.githubusercontent.com/29241175/52682596-fbe33d80-2f7a-11e9-8e85-c3f499b82ca3.png)

@atian25 作者，感谢~么么哒

并找到了一个书写错误：
egg-mock/index.js--32行  Tustom you plugins 

## 相关环境信息
- **操作系统：win10**：
- **Node 版本：8.12.0**：
- **Egg 版本：2.14.1**：

**Comment by atian25** [comment]
> 我进行插件开发的时候更改了插件的目录结构

你是一个 Git 仓库里面多个插件？

每一个插件目录下单独 package 吧，这样好点。

egg-mock plugin 那个是指定插件目录的，看下 egg-mock 源码就知道了。

**Comment by zheng199512** [comment]
感谢天猪大佬抽出时间进行回答：

是的，在最外层的package.json中进行运行`npm run test`脚本，将packages文件夹中的插件全部进行测试，每个插件有各自的package.json，我有尝试plugin，仍旧找不到目录。


![image](https://user-images.githubusercontent.com/29241175/52684355-f4269780-2f80-11e9-9eb4-85f41d5206d1.png)

这样仍旧找不对路径，如果设置eggPlugin就自动将外层作为插件目录了，并且也不应该补充eggPlugin。。。

> 每一个插件目录下单独 package 吧，这样好点。

您这句话的意思是每个插件单独测试么？也就是进入到插件的package.json进行测试，不要使用一条命令全部测试？

谢谢

**Comment by atian25** [comment]
> 您这句话的意思是每个插件单独测试么？也就是进入到插件的package.json进行测试，不要使用一条命令全部测试？

可以参考下 eggjs/examples 的做法。

不过老实说，真的有必要放在同一个源码库下管理么？我觉得没必要。我维护的插件也有近百个，直接一个个独立 Git 仓库挺好的。

**Comment by zheng199512** [comment]
谢谢

**Comment by zheng199512** [comment]
谢谢
