### ISSUE TITLE
ts下extend/application.js 使用app属性时，ts检查不通过。

### ISSUE THREAD

**Issue by zhump** [eggjs/egg#3453]
在使用typescript时，extend文件下新建application.js。挂载一下全局对象xx。直接使用app.xx时，ts检查过不去，编译报错，其实app.xx此时是有值的。

extend文件下新建context.js，挂载请求上下文对象yy。直接使用ctx.yy，ts检查通过。

查看 egg源码下index.d.ts，发现
![image](https://user-images.githubusercontent.com/7962067/52683642-66e24380-2f7e-11e9-9727-51dcf6de7a6e.png)
`interface Context `下声明了 ` [key: string]: any;`

但 Application 下不具备。
![image](https://user-images.githubusercontent.com/7962067/52683685-91340100-2f7e-11e9-846e-ca7231675524.png)

在其下 也加上  ` [key: string]: any;`

ts检查通过。

之后的版本中是否可以把这行加上？

## 相关环境信息
- **操作系统**：
mac 10.14.2 
- **Node 版本**：
v8.13.0
- **Egg 版本**：
2.14.2
---
额、刚将这行代码写到了typings/index.d.ts，问题也可以解决。就当帮后面的朋友踩坑把。
```
declare module 'egg' {
  interface Application {
    [key: string]: any;
  }
}
```

**Comment by whxaxes** [comment]
请仔细阅读官方 ts 文档

**Comment by 1961pjx** [comment]
跪谢楼主！
