### ISSUE TITLE
TypeError: Cannot set property router of #<Object> which has only a getter

### ISSUE THREAD

**Issue by ThomasLiu** [eggjs/egg#3457]
## What happens?

今天使用`nom run autod` 更新了项目的依赖后，所有的controller层的单元测试都不能通过了，连最基础的test/app/controller/home.test.js 也是。
然后新开了一个项, run test 也是一样的错误。
报错 `TypeError: Cannot set property router of #<Object> which has only a getter`

## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

```
$ npm i egg-init -g
$ egg-init egg-example --type=simple
$ cd egg-example
$ npm I
$ npm run test
```
![image](https://user-images.githubusercontent.com/3435615/52761451-674a0f80-304e-11e9-858d-4742b4ef99d6.png)

## 相关环境信息
- **操作系统**：Mac
- **Node 版本**：9.11.2
- **Egg 版本**：2.15.1

**Comment by killagu** [comment]
已经回滚了，重新安装依赖重试一下。

**Comment by ThomasLiu** [comment]
是同样用* 2.15.1 还是 2.14.1 ？

**Comment by ThomasLiu** [comment]
我现在用 
```
"dependencies": {
    "egg": "^2.14.2",
    "egg-alinode": "^2.0.1",
    "egg-cors": "^2.1.2",
    "egg-jwt": "^3.1.5",
    "egg-redis": "^2.3.0",
    "egg-scripts": "^2.11.0",
    "egg-sequelize": "^4.3.1",
    "egg-validate": "^2.0.2",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "mysql2": "^1.6.4",
    "u_egg_db_base": "^1.0.18"
  },
  "devDependencies": {
    "assert-extends": "^1.0.1",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "babel-register": "^6.26.0",
    "co-mocha": "^1.2.2",
    "egg-bin": "^4.10.0",
    "egg-mock": "^3.21.0",
    "eslint": "^5.12.1",
    "eslint-config-egg": "^7.1.0",
    "factory-girl": "^5.0.4",
    "qs": "^6.6.0",
    "sequelize-cli": "^5.4.0"
  },
```
然后用 `npm I` 后 test 或者 dev 请求都还是 `Cannot set property router of #<Object> which has only a getter`

**Comment by ThomasLiu** [comment]
egg-example的 是
```
"dependencies": {
    "egg": "^2.2.1",
    "egg-scripts": "^2.5.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.0.0",
    "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.14.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "webstorm-disable-index": "^1.2.0"
  },
```

我的项目还成 
```
 "dependencies": {
    "egg": "2.2.1",
    "egg-alinode": "2.0.1",
    "egg-cors": "2.1.2",
    "egg-jwt": "3.1.5",
    "egg-redis": "2.3.0",
    "egg-scripts": "^2.5.0",
    "egg-sequelize": "4.3.1",
    "egg-validate": "2.0.2",
    "lodash": "4.17.11",
    "moment": "2.24.0",
    "mysql2": "1.6.4",
    "u_egg_db_base": "1.0.19"
  },
  "devDependencies": {
    "assert-extends": "1.0.1",
    "autod": "3.0.1",
    "autod-egg": "1.1.0",
    "babel-register": "6.26.0",
    "co-mocha": "1.2.2",
    "egg-bin": "4.3.5",
    "egg-ci": "1.8.0",
    "egg-mock": "3.14.0",
    "eslint": "5.12.1",
    "eslint-config-egg": "7.1.0",
    "factory-girl": "5.0.4",
    "qs": "6.6.0",
    "sequelize-cli": "5.4.0"
  },
```
也是一样不可以，node_modules 已经是整个删除，再`npm i` 的都是一样`Cannot set property router of #<Object> which has only a getter`

**Comment by KeithZhang** [comment]
请问是哪个包，哪个版本的问题？我也遇到了同样的问题
`"egg": "2.0.0"`
`"egg-alinode": "^2.0.1"`

`alinoe: 4.4.2`
`node: 10.5.0`

**Comment by atian25** [comment]
不要锁版本，删除整个依赖目录重装即可

**Comment by KeithZhang** [comment]
好的，确实是锁版本了

**Comment by JackChius** [comment]
Cannot set property router of #<Object> which has only a getter  删除依赖，没锁版本后还是出现这个，所有路由都是这样，请问是怎样解决？

**Comment by whxaxes** [comment]
@JackChius 把 yarn.lock 删掉，如果没有 yarn.lock，查一下你 package.json 里的 egg 依赖版本是不是写死了

**Comment by JackChius** [comment]
@whxaxes  还原package.json 的"^"后问题得到解决，感谢大侠

**Comment by atian25** [comment]
Egg 的依赖，请坚持用 `^`，我们保证会严格遵循 Semver 规则。

**Comment by mosicong** [comment]
这个是啥问题，我这边也遇到了

**Comment by mosicong** [comment]
以上操作全试了，均无效

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by mosicong** [comment]
提供最小可复现仓库是指？

**Comment by mosicong** [comment]
node version v10.16.3

**Comment by mosicong** [comment]
egg version 2.9.0

**Comment by mosicong** [comment]
rm -rf node_modules
npm i --no-package-lock

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/3310

**Comment by mosicong** [comment]
> rm -rf node_modules
> npm i --no-package-lock

删掉package-lock.json或执行以上命令可以正常运行了

**Comment by David-Sam** [comment]
解决了，先看package.json egg的依赖是否都是 ^ ，然后不要锁定依赖，重新安装即可
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
