### ISSUE TITLE
配合umi使用时，如何更新manifest.json而不用重启

### ISSUE THREAD

**Issue by miaojiuchen** [eggjs/egg#3458]
背景：
服务端是常驻的进程，功能比较稳定，不经常发布 || 更新，我用了 egg-view-asset 来渲染umi构建的单页app，umi构建时候会有一个manifest.json，egg启动时候需要依赖这个文件，

我现在的做法是每次发布前端更新到cdn的时候，同时提交一次后端git的修改，然后发布，重启进程，我想把后端进程重启的这个步骤去掉，请问有什么最佳实践吗？

**Comment by popomore** [comment]
可以写个插件，获取更新后的 manifest 动态更新 app.config.assets.manifest

**Comment by miaojiuchen** [comment]
@popomore 感谢提供思路
