### ISSUE TITLE
nodejs.TypeError: Cannot set property router of #<Object> 

### ISSUE THREAD

**Issue by hsuehic** [eggjs/egg#3459]
## What happens?
![image](https://user-images.githubusercontent.com/7324648/52771589-3d561480-3071-11e9-9bc8-bac9e114904e.png)

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `egg-init --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
"dependencies": {
    "axios": "^0.18.0",
    "chalk": "^2.4.1",
    "egg": "2.14.2",
    "egg-jwt": "^3.1.4",
    "egg-mongoose": "latest",
    "egg-rewriter": "^1.0.4",
    "egg-scripts": "^2.5.0",
    "egg-static": "^2.1.1",
    "handlebars": "^4.0.12",
    "jenkins-api": "^0.3.1",
    "js-md5": "^0.7.3",
    "koa": "^2.6.2",
    "koa-compose": "^4.0.0",
    "koa-range": "^0.3.0",
    "koa-static-cache": "^5.1.2",
    "mkdirp": "^0.5.1"
  },
  "devDependencies": {
    "@types/mocha": "^2.2.40",
    "@types/mongodb": "^3.1.14",
    "@types/mongoose": "^5.3.1",
    "@types/node": "^7.10.2",
    "@types/supertest": "^2.0.0",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-bin": "^4.6.2",
    "egg-ci": "^1.8.0",
    "egg-mock": "^3.16.0",
    "egg-ts-helper": "1.11.0",
    "eslint": "^4.11.0",
    "eslint-config-egg": "^6.0.0",
    "tslib": "^1.9.3",
    "tslint": "^5.11.0",
    "typescript": "^3.1.6"
  },
  "engines": {
    "node": ">=8.9.0"
  },

Mac OS

**Comment by whxaxes** [comment]
Reinstall deps can fix ( Don't forget to remove lock file )

**Comment by atian25** [comment]
hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by hsuehic** [comment]
> hey, please retry after reinstall dependencies and please **never lock** it.
> 
> ```shell
> $ # reinstall deps and never lock it.
> $ rm -rf node_modules yarn.lock package-lock.json
> $ npm i --no-package-lock
> ```



> hey, please retry after reinstall dependencies and please **never lock** it.
> 
> ```shell
> $ # reinstall deps and never lock it.
> $ rm -rf node_modules yarn.lock package-lock.json
> $ npm i --no-package-lock
> ```

I tried this, but unexpectedly it didn't work. I also tried to run the app in a new Docker container, it didn't work also.

**Comment by atian25** [comment]
check `node_modules/@eggjs/router` version.

then lastest is set to 1.2.0  (which 1.3.0 is rollback)

**Comment by hsuehic** [comment]
![image](https://user-images.githubusercontent.com/7324648/52773702-8bb9e200-3076-11e9-8ed4-b36f00e03de7.png)
Thanks, it was 1.3.0.

**Comment by hsuehic** [comment]
Could you kindly tell me how could I install 1.2.0?

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/master/package.json#L75

we use `Semver`, so it will install to lastest(which is 1.2.0 now)

check you `npm/yarn` and don't lock version.

**Comment by hsuehic** [comment]
![image](https://user-images.githubusercontent.com/7324648/52774749-f409c300-3078-11e9-9eb8-9364a7d3db68.png)
I am so sorry. I view the package information. It indicated that the latest version is 1.3.0

**Comment by atian25** [comment]
```bash
npm info @eggjs/router dist-tags
{ latest: '1.2.0' }
```

it's 1.2.0 for me.

did you use any custom npm register?

**Comment by hsuehic** [comment]
yes, I am using a private NPM registry. Thank you.
