### ISSUE TITLE
关于文档中介绍环境变量的疑惑？

### ISSUE THREAD

**Issue by liyanlong** [eggjs/egg#346]
## 如下图
![image](https://cloud.githubusercontent.com/assets/8005864/22786033/da6c7000-ef11-11e6-973a-0a7f10b2b76c.png)

## 问题
- 是使用什么构建工具生成 **config/env** 文件 ?
- 具体生成的这个文件的格式是如何?

> 由于我手动添加config/env 文件，并填写了各种格式后，会出现500错误，所以想问下 @atian25 

[文档地址](https://github.com/eggjs/egg/blob/gh-pages/zh-cn/basics/env.html#L34-L47)

---------------

* **Node Version**: v6.9.1
* **Egg Version**:  v0.10.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: MacOS

**Comment by popomore** [comment]
请问出现什么具体的错误？

1. 整体部署的方案在这里讨论 https://github.com/eggjs/egg/issues/241
1. 文件内就写环境变量，比如 `prod`，EGG_SERVER_ENV 写的值 https://github.com/eggjs/egg/blob/master/docs/source/zh-cn/basics/env.md#与-node_env-的区别

**Comment by dead-horse** [comment]
> 是使用什么构建工具生成 config/env 文件

egg 运行时不关心如何构建，你的应用打包流程中判断好环境，生成 `config/env` 这个文件就好了，这个文件的内容见 @popomore 的回复。

如果希望一次构建多环境运行（我们也推荐这样），可以通过环境变量(`EGG_SERVER_ENV`)来设置环境。

**Comment by liyanlong** [comment]
@popomore  
谢谢回答.  另外第一个超链接有点问题. 
另外, 是我对env文件的了解有误, 之前认为对env的写法是这样的.
```shell
EGG_SERVER_ENV=prod
```
原来只要这样
```shell
prod
```

**Comment by huangyanxiong01** [comment]
@liyanlong 
```js
process.env.prod  
```
这样取得环境变量？

**Comment by liyanlong** [comment]
@huangyangxiong01  我是采用了 `app.config.env`. 主要还是对env文件的理解失误.

**Comment by dead-horse** [comment]
@huangyanxiong01 通过 `EGG_SERVER_ENV` 设置的环境变量通过 `process.env.EGG_SERVER_ENV` 来获取。但是在 egg 的代码中不再推荐通过环境变量获取，而是通过 @liyanlong 说的 `app.config.env` 来获取。因为通过环境变量只是设置 egg 运行环境的一种方式，通过 `app.config.env` 是最准确的。

**Comment by atian25** [comment]
https://github.com/eggjs/egg/pull/348

**Comment by csjiabin** [comment]
`app.env`

**Comment by atian25** [comment]
用 app.config.env
