### ISSUE TITLE
无法正常返回数据，请帮忙看一下！谢谢

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#3462]
// save workbook to disk
            const ctx=this.ctx;
            workbook.xlsx.writeFile("./app/public/excel/first.xlsx").then(function () {
                console.log("saved");

               //这个地方谢谢，可否帮我修正，谢谢了
                ctx.body=1;

            });

**Comment by xinnian1992** [comment]
//这是一个数据导出的功能，我需要数据导出保存为excel的时候，返回文件的路径-----谢谢

var Excel = require('exceljs');

* excelOut() {
            var workbook = new Excel.Workbook();
            // 基本的创建信息
            workbook.creator = "Me";
            workbook.lastModifiedBy = "Her";
            workbook.created = new Date(1985, 8, 30);
            workbook.modified = new Date();
            workbook.lastPrinted = new Date(2016, 9, 27);

            // 视图大小， 打开Excel时，整个框的位置，大小
            workbook.views = [
                {
                    x: 0,
                    y: 0,
                    width: 1000,
                    height: 2000,
                    firstSheet: 0,
                    activeTab: 1,
                    visibility: "visible"
                }
            ];

            // 标签创建
            var worksheet = workbook.addWorksheet("第一个标签");
            // 带颜色的
            var worksheet2 = workbook.addWorksheet("第二个标签", {properties: {tabColor: {argb: "FFC0000"}}});

            // 遍历标签
            workbook.eachSheet((worksheet, sheetId) => {
                console.log("标签ID：", sheetId)
            })
            // console.log(worksheet);
            // 删除一个标签
            workbook.removeWorksheet(2)

            var firstSheet = workbook.getWorksheet(1);
            console.log("标签信息-id", firstSheet.id);
            console.log("获取总的：行/实际行 /列/实际列 个数： ", firstSheet.rowCount, firstSheet.actualColumnCount, firstSheet.columnCount, firstSheet.actualColumnCount);

            // 添加那个筛选箭头
            // worksheet.autoFilter = 'A1:C1';

            worksheet.getRow(5).font = {size: 14, bold: true};
            var letter = ["A", "B", "C"];
            worksheet.getCell("A1").value = "校区";
            worksheet.getCell("B1").value = "电话";
            worksheet.getCell("C1").value = "姓名";

            for (var a = 0; a < letter.length; a++) {
                worksheet.getCell(letter[a] + "1").font = {
                    name: "Arial Black",
                    // color: {argb: "FF00FF00"},
                    family: 2,
                    size: 14,
                    // italic: true,
                    bold: true
                };
            }

            for (var b = 2; b < 10; b++) {
                for (var c = 0; c < letter.length; c++) {
                    console.log(letter[c] + b);
                    worksheet.getCell(letter[c] + b).value = b;
                }
            }

            // save workbook to disk
            const ctx=this.ctx;
            workbook.xlsx.writeFile("./app/public/excel/first.xlsx").then(function () {
                console.log("saved");


               //**此处返回json**
                ctx.body=1;
            });

        }

**Comment by xinnian1992** [comment]
谢谢大神

**Comment by atian25** [comment]
`await workbook.xlsx.writeFile("./app/public/excel/first.xlsx")`

。。。 去学下 ES6 Async 等基础先吧
