### ISSUE TITLE
egg-ant-design-pro。执行dev出错

### ISSUE THREAD

**Issue by Currencywy** [eggjs/egg#3463]
* **Node Version**:v8.11.2
* **Egg Version**: 2.14.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Win 10
* **Mini Showcase Repository**:

执行dev时，提示如下
![_20190215114928](https://user-images.githubusercontent.com/39109415/52833473-ccb60300-3117-11e9-89bc-5020e7f37957.png)

**Comment by thonatos** [comment]
看提示信息，`devServer.port is required` ，参考配置：

```js
exports.assets = {
  devServer: {
    command: 'roadhog dev',
    port: 8000,
  },
};
```


- https://github.com/eggjs/egg-view-assets

**Comment by Currencywy** [comment]
> 看提示信息，`devServer.port is required` ，参考配置：
> 
> ```js
> exports.assets = {
>   devServer: {
>     command: 'roadhog dev',
>     port: 8000,
>   },
> };
> ```
> 
> * https://github.com/eggjs/egg-view-assets

`config.assets = {
    publicPath: '/public',
    devServer: {
      autoPort: true,
      command: 'umi dev --port={port}',
      env: {
        APP_ROOT: path.join(__dirname, '../app/web'),
        BROWSER: 'none',
        SOCKET_SERVER: 'http://127.0.0.1:{port}',
      },
      debug: true,
    },
  };`
配置没问题吧？

**Comment by thonatos** [comment]
自动端口配置也可以，还是以文档为准，如果依然有问题建议提供最小可复现仓库。

**Comment by Currencywy** [comment]
> 自动端口配置也可以，还是以文档为准，如果依然有问题建议提供最小可复现仓库。

依然有问题，代码是今天下载的，没有做任何修改，还需要提供最小可复现仓库？

**Comment by thonatos** [comment]
OSX 环境已测试没有问题，你的环境是？尝试一下删除依赖重试。

**Comment by Currencywy** [comment]
> OSX 环境已测试没有问题，你的环境是？尝试一下删除依赖重试。

Win10

**Comment by thonatos** [comment]
Windows 环境没测试，回头找电脑测试一下，你可以在程序启动后打印一下配置，根据提示去修改。

**Comment by Currencywy** [comment]
> Windows 环境没测试，回头找电脑测试一下，你可以在程序启动后打印一下配置，根据提示去修改。

**Comment by Currencywy** [comment]
@thonatos  帅锅，在Windows环境测试了吗？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-view-assets/blob/master/agent.js#L12

看你不是最新版本
