### ISSUE TITLE
单元测试如何确保agent完全初始化后实行后续单测

### ISSUE THREAD

**Issue by miser** [eggjs/egg#3465]
我的单测是连eureka注册中心调用其它服务完成的（测试颗粒大了点）

## What happens?
我使用了 egg-eureka-plugin 这个插件。npm run dev情况下，都是能注册和获取服务器。
但是当我通过npm run test，就没办法了。因为agent 里面去连eureka还没注册和获取完成就执行了后续的单测，导致无法正常获取无法而报错。

```
 // test.js
describe('test/xxx.test.js', () => {
  let app
  before(async () => {
    app = mm.app()
    await app.ready()
  })
  
  describe('save', () => {
    it('success', async () => {
      await app.httpRequest()
        .post('/api/xxxx')
        .expect(res => { })
    })
  })
})
// controller 
class xxxxxController extends Controller {
  async list (ctx) {
    ctx.body = {}
  }
  async save (ctx) {
    // const { body: {} } = ctx
    await this.service.xxxx.getServerUrl()
}
// service 
module.exports = app => {
  class xxxxxService extends app.Service {
    constructor (ctx) {
      super(ctx)
      this.appId = 'filesystem'
    }
    getServerUrl () {
      const eurekaUtil = this.ctx.app.eurekaUtil
      const instances = this.ctx.app.apiClient.get(this.appId)
      if (!Array.isArray(instances) || instances.length === 0) {
        this.ctx.throw('get 0 instances!!')
      }
      const ins = eurekaUtil.getOneInstanceFromAll(instances)
      const serverUrl = eurekaUtil.getServerPath(ins)

      return serverUrl
    }
}
```

每次单测都报 get 0 instances 错误。
请问在egg-mock 里面能确保agent相关都初始化完成在执行后续单测吗？

## Context
- **Node Version**: v10.9.0
- **Egg Version**: 2.2.1
- **Plugin Name**:  egg-eureka-plugin
- **Plugin Version**: 1.0.3
- **Platform**: mac

**Comment by atian25** [comment]
打日志看看，我看那个插件里面是有 `beforeStart` 的，会等待执行完毕后的

https://github.com/HOTTIN/egg-eureka/blob/master/agent.js#L9

**Comment by atian25** [comment]
hey, we need more information to follow up this issue.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
