### ISSUE TITLE
程序启动主线程master后fork多个work ,workers 收到信号后egg 如何处理用户请求

### ISSUE THREAD

**Issue by Messilimeng** [eggjs/egg#3467]
if (options.sticky) {
    server.listen(0, '127.0.0.1');
    // Listen to messages sent from the master. Ignore everything else.
    process.on('message', (message, connection) => {
      if (message !== 'sticky-session:connection') {
        return;
      }

      // Emulate a connection event on the server by emitting the
      // event with the connection the master sent us.
      server.emit('connection', connection);
      connection.resume();
    });

关于  server.emit('connection', connection)后程序是如何响应用户请求？

**Comment by dead-horse** [comment]
能够描述清楚一点具体的问题么？

**Comment by Messilimeng** [comment]
源码哪个地方开始 处理了 koa2的 用户请求 ctx

**Comment by ngot** [comment]
没太看懂问题。如果是问 `server.emit('connection', connection)` 这行代码的作用，请查看 Node.js 官方文档关于网络的章节。

https://nodejs.org/dist/latest-v11.x/docs/api/net.html

**Comment by Messilimeng** [comment]
koa 是 app.callback() 回调处理用户请求的  那egg 是在哪处理 koa 里面的 app.callback()的

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/blob/3bac979cbe2ee54fc2ea264cd8d3562c2866b4a5/lib/app_worker.js#L57

源码就自己看吧
