### ISSUE TITLE
egg-ant-design-pro run dev, build error

### ISSUE THREAD

**Issue by TranDucBlog** [eggjs/egg#3470]
1. RUN
npm run dev or npm run build
![screenshot from 2019-02-17 15-00-39](https://user-images.githubusercontent.com/26267956/52910087-0ed07780-32c5-11e9-8c3a-61e0d6b5eca0.png)

2. eslint error message
![screenshot from 2019-02-17 15-01-16](https://user-images.githubusercontent.com/26267956/52910099-30316380-32c5-11e9-8753-abb17b19e76c.png)

**Comment by popomore** [comment]
lint has been fixed. I don't reproduce the first problem, can you pull the latest commit and reinstall node_modules.
