### ISSUE TITLE
egg-session-redis，获取 redis 存储的session所对应的key值

### ISSUE THREAD

**Issue by wlfei0502** [eggjs/egg#3471]
我看了源码，这个key是通过genid生成的，自身应用中怎么获取该值

**Comment by zheng199512** [comment]
@wlfei0502  请问一下这个key应该怎么获取啊？

**Comment by wlfei0502** [comment]
@zheng199512 我在issue 2010做了回答，请参照https://github.com/eggjs/egg/issues/2010

**Comment by CharlseW** [comment]
看看这个能不能解决
 this.ctx.session._sessCtx.externalKey
