### ISSUE TITLE
[Feature Request] 在集群前提下，消息队列消费者代码应该写在哪里？

### ISSUE THREAD

**Issue by zhb127** [eggjs/egg#3473]
## Background
由于项目中需要借助消息队列，来解耦生产者和消费者的代码逻辑，但是看了 egg-ons 等插件，基本上都是项目一启动，同时也注册了消费者，这样项目跟消息队列任务都是在同一台机器跑了。如果希望在另外一台机器上运行消费者，同时希望针对不同的消费者可以启动不同数量的进程，那么应该怎么做更好呢。

**Comment by dead-horse** [comment]
具体的消息由哪个消费者消费与消息队列服务的推送策略有关。尽管你每个进程都注册了消费者，但是它消费哪里投递过来的数据，怎么消费（集群广播还是单个 worker 消费）都是由自己控制的。
