### ISSUE TITLE
curl下,passport鉴权后跳转后,ctx.user未定义.

### ISSUE THREAD

**Issue by huang12zheng** [eggjs/egg#3479]
## What happens?

两个不相关的问题:
a.请问ctx.login(user)做了什么?(是否会跑defaultVerify呢?)
b.passport鉴权后跳转后,ctx.user会未定义.
## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/huang12zheng/issue-passport-userlosee

## 复现步骤，错误日志以及相关配置
终端下 curl -L "http://localhost:7001/passport/UMA?mobile=17682318150&password=wowowo", (ps:浏览器下会有)

## 相关环境信息
- **操作系统**：window10
- **Node 版本**：9.9

**Comment by atian25** [comment]
ping @thonatos

**Comment by geekdada** [comment]
egg-passport 默认情况下会在登录成功后（不论你使用那种 Strategy），把 User 相关信息混淆写入用户的 Cookie，这样后面的请求就能够正确识别出 `ctx.user` 的内容。Curl 请求中不包含 Cookie，就没有 `ctx.user` 了。
