### ISSUE TITLE
[RFC] customLoader

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#3480]
## 背景

Egg 支持自定义 loader，通过 app.loader 的 API 可以自定义加载某个目录的文件到 app 或 ctx。

但是通过 API 调用比较麻烦

1. 非声明式的，使用不友好
1. loader 属于内部 API，透出重构成本高
1. 如果使用 ts 还得重新定义一遍

## 思路

在 `config.default.js` 增加 customLoader 的配置，不需要再使用 API

```js
exports.customLoader = {
  service: {
    directory: 'app/service',
    inject: 'ctx', // or app
    loadunit: false, // 是否加载框架和插件目录
    // other loads options
  },
};
```

egg-ts-helper 也可以读这个配置来生成 typing

在 didLoad 加载自定义 loader

## 跟进

- [x] egg-core https://github.com/eggjs/egg-core/pull/202
- [x] egg https://github.com/eggjs/egg/pull/3484
- [x] egg-ts-helper https://github.com/whxaxes/egg-ts-helper/pull/41
- [x] egg-mock 自动生成 mock API https://github.com/eggjs/egg-mock/pull/95
- [ ] 插件改造
  - [ ] egg-mongoose
  - [ ] egg-sequelize

**Comment by atian25** [comment]
在哪个生命周期加载？

**Comment by popomore** [comment]
didLoad 吧

**Comment by popomore** [comment]
有个问题，需要区分 app/agent 吗，一般都在 app 里面

**Comment by whxaxes** [comment]
可以区分一下吧，inject 里可以填 app 或者 agent ？

**Comment by whxaxes** [comment]
存不存在这种场景，需要同时 load 到 app 和 agent 上？那这样 inject 是否也可以支持传个数组？

**Comment by popomore** [comment]
inject 只有 app/ctx，如果要支持可以加个 type

**Comment by popomore** [comment]
https://github.com/eggjs/egg-mock/pull/95

**Comment by whxaxes** [comment]
https://github.com/whxaxes/egg-ts-helper/pull/41

**Comment by skyitachi** [comment]
great work
