### ISSUE TITLE
egg-init 无法安装模板

### ISSUE THREAD

**Issue by whwnow** [eggjs/egg#3482]
## What happens?
在执行 `egg-init egg-example --type=simple`时
卡在`write to D:\Git\egg-example\test\app\controller\home.test.js`不动，重新安装，多次尝试问题依然存在

## Context
- **Node Version**:  10.15.0
- **egg-init Version**: 1.15.0
- **Platform**: windows

**Comment by whxaxes** [comment]
我修复一下

**Comment by whxaxes** [comment]
目前在 windows 下由于依赖的 mem-fs 有点问题导致安装不了

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-init/pull/48

**Comment by whxaxes** [comment]
更新 egg-init 到 1.15.1 试一下

**Comment by whwnow** [comment]
更新后ok了，成功下载模板，感谢

**Comment by whxaxes** [comment]
好的，那我关掉这个 issue 了

**Comment by atian25** [comment]
@whxaxes 更新下文档，用 `npm init egg` 吧，不介绍 egg-init 了。

**Comment by bi-kai** [comment]
@atian25 `npm init egg`这是只是创建了一个空的package.json文件哪，怎么初始化的egg？

**Comment by atian25** [comment]
@bi-kai 猜测是你的 npm 版本太低了，更新下吧

**Comment by bi-kai** [comment]
@atian25 
![image](https://user-images.githubusercontent.com/15070379/56951668-05884480-6b6b-11e9-8577-3425249569fa.png)
这应该是主流配置吧？文档中并未看到对npm版本的要求呀

**Comment by atian25** [comment]
提供下你执行命令的控制台日志

**Comment by bi-kai** [comment]
@atian25 
![image](https://user-images.githubusercontent.com/15070379/56951855-72034380-6b6b-11e9-9196-ceea729b0c5b.png)
这直接创建普通的package.json了

**Comment by atian25** [comment]
又是 win 这玩意。。。

下面不是有个 package name 的提示让你输入么？怎么提前 ctrl+c 了？

**Comment by bi-kai** [comment]
@atian25 不兼容win？

**Comment by bi-kai** [comment]
@atian25 
![image](https://user-images.githubusercontent.com/15070379/56952507-12a63300-6b6d-11e9-94fd-fe43a4669b32.png)
linux上也这样呀。

**Comment by bi-kai** [comment]
确定不需要提前安装`egg-init`么？这整得我都不会了~

**Comment by atian25** [comment]
看起来是你的 npm 版本问题，没支持 `npm init <initializer>` 这个特性。

https://docs.npmjs.com/cli/init#description

你升级到 npm@5.10 或者 npm@6 的 npm 吧，https://github.com/npm/cli/blob/v5.10.0/lib/init.js

**Comment by bi-kai** [comment]
@atian25 确实是这个问题
![image](https://user-images.githubusercontent.com/15070379/56954738-1d16fb80-6b72-11e9-9765-f7258854c07a.png)
这样就好了。
![image](https://user-images.githubusercontent.com/15070379/56954730-14262a00-6b72-11e9-9619-f9e7768c897a.png)
话说为啥用的npm官方源，我本地配的是淘宝源。

**Comment by atian25** [comment]
`npm init egg -r=china`

从 issue 咨询来看，你是第一个遇到的。我印象中 Node 8 自带的 npm 好像应该不低了吧？回头看看。

**Comment by bi-kai** [comment]
我确定没有改过npm的版本。
![image](https://user-images.githubusercontent.com/15070379/56955417-e5a94e80-6b73-11e9-8d3e-42ef6c8919e3.png)
我回家再试试，不知道是不是公司防火墙拦截了什么。

**Comment by gebin** [comment]
> @atian25 确实是这个问题
> ![image](https://user-images.githubusercontent.com/15070379/56954738-1d16fb80-6b72-11e9-9765-f7258854c07a.png)
> 这样就好了。
> ![image](https://user-images.githubusercontent.com/15070379/56954730-14262a00-6b72-11e9-9619-f9e7768c897a.png)
> 话说为啥用的npm官方源，我本地配的是淘宝源。
> 
> egg-init不推荐用，npm又要比较高的版本，在官方文档中补充下说明吧，不然很多人卡在这里。

现在官方文档还是没有更新，刚刚就卡在这里了  @atian25
