### ISSUE TITLE
当7001端口被其他应用占用时，Egg设置的自定义绑定端口不生效

### ISSUE THREAD

**Issue by shujunz** [eggjs/egg#3485]
## What happens?
当系统中有其他应用把7001端口占用，例如先启动一个默认的Egg实例。此时再运行一个端口绑定配置为以下内容的Egg实例，此时启动的Egg并不会绑定到用户设置的端口（20000）上，而是会绑定到7002或7003上。
```
  config.cluster = {
    listen:  {
      port: 20000,
      hostname: '0.0.0.0',
      path: '',
    },
  };
```

## How To Reproduce

**Steps to reproduce the behavior:**
1. 启动一个Egg实例，保持绑定端口为默认端口（7001）
2. 启动自定义端口的Egg实例，观察端口是否绑定到自定义的端口上
3. 关闭绑定默认端口的实例，再启动自定义端口的Egg实例，观察端口是否绑定到自定义端口上

## Context
- **Node Version**: 8.10.0
- **Egg Version**: 2.6.1
- **Plugin Name**: 
- **Plugin Version**:
- **Platform**: Windows 7

```
FYI

"dependencies": {
    "egg": "^2.6.1",
    "egg-jwt": "^3.1.4",
    "egg-logrotator": "^3.0.5",
    "egg-redis": "^2.3.0",
    "egg-router-plus": "^1.3.0",
    "egg-scripts": "^2.11.0",
    "egg-sequelize": "^4.2.0",
    "fs": "0.0.1-security",
    "mysql2": "^1.6.4",
    "require-dir": "^1.2.0",
    "rxjs": "^6.3.3",
    "shortid": "^2.2.14",
    "ws": "^6.1.2"
  },
```

**Comment by popomore** [comment]
本地通过命令行指定 egg-bin dev —port 20000

**Comment by shujunz** [comment]
好的，建议还是修复一下，虽然只是在dev模式下有影响，但是始终不太方便。

**Comment by popomore** [comment]
因为工具默认就是 7001，工具优先级会高于框架

**Comment by monkindey** [comment]
[egg-bin](https://github.com/eggjs/egg-bin/blob/master/lib/cmd/dev.js#L104) 能否先读取 用户配置的 port，如果没有的话再随机找一个port ?

**Comment by atian25** [comment]
后续可以支持下，egg-bin 可以通过 egg-utils 读取下配置。
