### ISSUE TITLE
How to disable CSRF on certain routes?

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [eggjs/egg#3486]
Hello.

I have created router with controllers that starts with this address:

    /api/*

I want to disable all CSRF protections in these routes.

I know that it is possible to disable CSRF globally like this:

    security: {
      csrf: {
         enable: false
      },
    }

However, it is not really good idea. I wanted to disable CSRF by using CSP like this:

    security: {
      csp: {
        enable: true,
        match: '/api',
        policy: {
          csrf: {
            enable: false
          }
        }
      }
    }

But it is not working.

Is it possible to disable CSRF protection on certain routes?

    Node 9.2.0
    Egg JS 2.2.1

**Comment by popomore** [comment]
You can use ignore and it can be regexp

**Comment by SuperMasterBlasterLaser** [comment]
@popomore 

You mean like that?

    security: {
      csp: {
        enable: true,
        ignore: '/api/',
        policy: {
          csrf: {
            enable: false
          }
        }
      }
    }

**Comment by popomore** [comment]
security: {
  csrf: {
    enable: true,
    ignore: '/api/',
  }
}

**Comment by unclexiao** [comment]
Here is the [Manual](https://eggjs.org/zh-cn/plugins/security.html#match-ignore).

I think @SuperMasterBlasterLaser is right , and you can also use function like this: 
```javascript
 config.security = {
    methodnoallow: {
      enable: false
    },
    domainWhiteList: [
      "" // some urls
    ],
    csrf: {
      enable: true,
      ignore: ctx => {
        return ctx.path == "/pay/notify" ? true : false; // path or ip
      }
    }
  };
```

**Comment by SuperMasterBlasterLaser** [comment]
@popomore  and @unclexiao Thank you!
