### ISSUE TITLE
[Feature Request] Add an auto package upgration

### ISSUE THREAD

**Issue by Maledong** [eggjs/egg#3489]
## Background
Since egg and all of its 3-rd party packages should be updated manually, why not update automatically to avoid security problems or something else?

## Proposal
Use `https://dependabot.com/` instead.

**Comment by atian25** [comment]
- we use `^`, so if it's not a break change, we do not need to update package.json
- if it's a break change, then when we got synk alert, then update it

**Comment by Maledong** [comment]
OK, thanks!
