### ISSUE TITLE
[RFC] `eslint-config-egg` support typescript

### ISSUE THREAD

**Issue by whxaxes** [eggjs/egg#3490]
## 背景

https://medium.com/palantir/tslint-in-2019-1a144c2317a9

> The developers of TSLint, the TypeScript linter, have decided to deprecate it and focus on improving TypeScript support in the popular ESLint linter instead. This will greatly help existing ESLint users who are picking up TypeScript.

如文中所说，tslint 将被废弃，取而代之的是支持 Typescript 的 eslint plugin: [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint)。

而 [eslint-config-egg](https://github.com/eggjs/eslint-config-egg) 作为 egg 的最佳实践规范，自然也需要跟随脚步支持 Typescript 。

## 思路

将 typescript-eslint 的规则配置加到 [eslint-config-egg](https://github.com/eggjs/eslint-config-egg) 中。

Typescript 的相关规则参考现有的 [tslint-config-egg](https://github.com/eggjs/tslint-config-egg) 。

## 跟进

- [x] eslint-config-egg
- [x] 文档调整

**Comment by whxaxes** [comment]
https://github.com/eggjs/eslint-config-egg/pull/46

**Comment by whxaxes** [comment]
7.5.0

**Comment by Jeff-Tian** [comment]
```
npx egg-init --type=ts showcase
```

这个生成的脚手架还是在用 `tslint`，是不是需要更新？

**Comment by whxaxes** [comment]
@Jeff-Tian  需要，我晚点改一下

**Comment by jasonBH** [comment]
请问eslint改好了吗？我现在拉下来还是用的tslint.

**Comment by whxaxes** [comment]
@jasonBH  还没。。。最近太忙，我今晚弄好

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-boilerplate-ts/pull/17   PR 已经提了

**Comment by jasonBH** [comment]
@whxaxes 非常感谢.
