### ISSUE TITLE
typescript redis使用多连接下不能获取到Redis实例

### ISSUE THREAD

**Issue by shujunz** [eggjs/egg#3491]
在typescript初始化的Egg框架中，我需要使用两个redis连接来读取数据，其中一个正常的get，另一个做订阅用。配置文件如下：
```
 config.redis = {
    clients: {
      c1: {
        port: 6379,
        host: '127.0.0.1',
        password: '',
        db: 0,
      },
      c2: {
        port: 6379,
        host: '127.0.0.1',
        password: '',
        db: 0,
      },
    },
  };
```
此时在，在代码中使用
```
const stringBuff = await this.ctx.redis.get('c1').get(KEY1);
        if (!stringBuff) {
            ret.success = false;
            ret.errorCode = ErrorCode.INIT_ERROR;

            return ret;
        }
```
编译器直接报错：
```
error TS2339: Property 'get' does not exist on type 'Promise<string | null>'.
```

如果直接使用redis.get(KEY1)会报找不到数据，请问在Typescript，正确的调用方式应该是什么样的？

## Context
- **Node Version**: v8.10.0
- **Egg Version**: 2.17.0
- **Plugin Name**: egg-redis
- **Plugin Version**: 2.3.0
- **Platform**: Windows 7

![image](https://user-images.githubusercontent.com/11557994/53313200-4659a800-38f3-11e9-8dfc-6de2edea7508.png)

![image](https://user-images.githubusercontent.com/11557994/53313223-5a9da500-38f3-11e9-98bb-ec865e8ff66c.png)

![image](https://user-images.githubusercontent.com/11557994/53313292-b23c1080-38f3-11e9-8d87-46eb11bfb4ea.png)

**Comment by whxaxes** [comment]
已经有人提 PR 了 https://github.com/eggjs/egg-redis/pull/27

**Comment by tong3jie** [comment]
临时解决参考如下：
```
eclare module 'egg' {
  interface Application {
    redis: redis;
  }
}
```
