### ISSUE TITLE
在容器中部署的问题

### ISSUE THREAD

**Issue by 17dun** [eggjs/egg#3493]
在小程序业务中需要服务支持https，看了相关介绍，egg官方推荐的是使用nginx反向代理。我们是使用容器化部署的，nginx和node服务都包进一个容器是可以满足需求，不过不清楚这样上线后会不会有什么问题？ 如果nginx和node分开部署的话，仅仅因为一个https需要，就要多启一个部署组又有点太占资源了。

**Comment by 17dun** [comment]
1，如果有不依赖nginx的https方案更好了
2，如果需要依赖，有没有相关线上同一个容器部署两个服务的先例，会有什么问题吗？

**Comment by dead-horse** [comment]
将 https 部署在前置的 SLB 负载均衡上，不要部署到具体的容器服务上。

**Comment by 17dun** [comment]
> 将 https 部署在前置的 SLB 负载均衡上，不要部署到具体的容器服务上。

我们这边平台支持的负载均衡是根据配置组自动分配的，且本身不支持选择http还是https，但是可以做tcp协议的端口绑定。

如果部署到具体的容器服务上除了不解耦，问题定位会麻烦点，还会有什么其他的问题吗？

**Comment by dead-horse** [comment]
一般来说不要把证书等敏感信息放在容器上，统一在前置的 SLB 接入层做 https 卸载是更通用的做法。当然如果你们只能在容器中实现 https，也可以不需要 nginx，直接用 egg-cluster 启动 https 服务。
