### ISSUE TITLE
schedule 文件中使用 setTimeout 不能正确延时

### ISSUE THREAD

**Issue by youngchou1997** [eggjs/egg#3494]
## What happens?
当我在 schedule 文件中使用 cron 方式设置定时器，然后再使用 setTimeout 在 for　循环中进行延时，发现打印出来的时间有问题，没有达到我预期的延时效果
实际打印出来的结果是

{ taskId: '81955',
  _id: 5c74f27e18869039dc8d09a8,
  message: '数据查询中' }
16:14:43 ***查询延时20s-- 81951
{ taskId: '1',
  _id: 1,
  message: '数据查询中' }
16:14:43 ***查询延时20s-- 81951
16:14:43 ***查询延时20s-- 81955
{ taskId: '2',
  _id: 2,
  message: '数据查询中' }
{ taskId: '3',
  _id: 3,
  message: '数据查询中' }
16:14:44 ***查询延时20s-- 81951
{ taskId: '4',
  _id: 4,
  message: '数据查询中' }
16:14:44 ***查询延时20s-- 81951
16:14:44 ***查询延时20s-- 81955
{ taskId: '5',
  _id: 5,
  message: '数据查询中' }

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `egg-init --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.新建一个定时器 如
/**
 * @file syncData.js
 */
const Subscription = require('egg').Subscription;
const moment = require('moment')
class syncQEData extends Subscription {
    static get schedule() {
        return {
            immediate: true,
            cron: '* */2 * * * *',
            type: 'worker',
        };
    }

    async subscribe() {
        const sleep = (timeountMS) => new Promise((resolve) => {
            setTimeout(resolve, timeountMS);
          });
        try {
            const taskList = [1,2,3,4,5,6]
            for(let item of taskList) {
                try {
                    await sleep(20000)
                    console.log(moment().format('HH:mm:ss'), '***查询延时20s--', item.taskId)
                    // console.log(await this.ctx.service.performance.getData(item))
                } catch(e) {
                    // console.log(e)
                }  
            }
        } catch (error) {
     
        }
    }
}

module.exports = syncQEData;

**Expected behavior**
1. 每一次同步操作都会间隔20s进行

## Context
- **Node Version**:v10.13.0
- **Egg Version**:v2.2.1
- **Plugin Name**:moment
- **Plugin Version**:v2.23.0
- **Platform**:windows10

**Comment by youngchou1997** [comment]
```
/**
 * @file syncQEData.js
 * @author zhouyang02
 * @date 2019/2/22
 */
const Subscription = require('egg').Subscription;
const moment = require('moment')
const ewx = require('@qtt/node-ewx-sdk');

class syncQEData extends Subscription {
    // 通过 schedule 属性来设置定时任务的执行间隔等配置
    static get schedule() {
        return {
            immediate: true,
            cron: '* */2 * * * *',
            type: 'worker',
        };
    }

    // subscribe 是真正定时任务执行时被运行的函数
    async subscribe() {
        const sleep = (timeountMS) => new Promise((resolve) => {
            setTimeout(resolve, timeountMS);
          });
        try {
            // this.ctx.logger.info('*****【报表服务同步通知】QE数据同步任务启动*****', moment().format('HH:mm:ss'));
            // ewx.notify({
            //     names: ['周洋'],
            //     content: '【报表服务同步通知】\n*****QE数据同步任务启动！***** \n'+ moment().format('HH:mm:ss')
            // })

            const taskList = [{
    taskId: '1'
},
{
    taskId: '2'
},
{
    taskId: '3'
},
{
    taskId: '4'
}
]
            for(let item of taskList) {
                try {
                    await sleep(20000)
                    console.log(moment().format('HH:mm:ss'), '***查询延时20s--', item.taskId)
                    console.log(await this.ctx.service.performance.getData(item))
                } catch(e) {
     
                }  
            }

        
            // })
        } catch (error) {
            
        }
    }
}

module.exports = syncQEData;
```

**Comment by atian25** [comment]
schedule 文档有注明了，当前的 Timer 策略，是固定频率的，而不是固定间隔，不支持等待前一个任务完成后再继续下一个任务。

**Comment by youngchou1997** [comment]
了解了，那么想有延时效果，有什么解决方案吗

**Comment by atian25** [comment]
自己实现一个策略，可以看下 egg-schedule 源码。

不过这种，最好是自己加个分布式锁，在任务里面判断
