### ISSUE TITLE
egg x typescript, new Application(options):  error TS2554: Expected 0 arguments, but got 1.

### ISSUE THREAD

**Issue by shinux** [eggjs/egg#3495]
## What happens?

typescript 下 egg  Application typing 不能被正确的识别

## 复现步骤，错误日志以及相关配置

```
import { Appplication } from 'egg';

const app = new Application({
  baseDir: path.join(__dirname, '../'),
})
```

```
error: ⨯ Unable to compile TypeScript:
pic.ts(72,21): error TS2554: Expected 0 arguments, but got 1.
```

## 最小复现仓库

repo:    https://github.com/shinux/egg-ts-showcase-for-reporting-issue
file：https://github.com/shinux/egg-ts-showcase-for-reporting-issue/blob/master/app/service/Test.ts

## 相关环境信息
- **操作系统**：Mac Mojave 10.14.2 (18C54)
- **Node 版本**：v8.12.0
- **Egg 版本**：2.14.2
- **TypeScript版本**: 3.2.4

**Comment by whxaxes** [comment]
为什么要实例化 Application ？

**Comment by whxaxes** [comment]
https://github.com/shinux/egg-ts-showcase-for-reporting-issue/blob/master/app/service/Test.ts#L15

在这里 `this.app` 就是 app 实例了

**Comment by shinux** [comment]
> https://github.com/shinux/egg-ts-showcase-for-reporting-issue/blob/master/app/service/Test.ts#L15
> 
> 在这里 `this.app` 就是 app 实例了

问题来源于这里 https://github.com/eggjs/egg/issues/3262

给一个外部的 consumer 中传入的 handler 有依赖于 egg service 的时候，怎么能够主动构造一个 anonymous ctx 让 handle function 的能感知到其他的  service/helper

**Comment by whxaxes** [comment]
可以创建一个匿名 Context 对象 https://eggjs.org/zh-cn/basics/objects.html#%E8%8E%B7%E5%8F%96%E6%96%B9%E5%BC%8F-2

![image](https://user-images.githubusercontent.com/5856440/53400316-8cdcfe80-39e8-11e9-812d-3e2d75e33527.png)

**Comment by shinux** [comment]
> 可以创建一个匿名 Context 对象 https://eggjs.org/zh-cn/basics/objects.html#%E8%8E%B7%E5%8F%96%E6%96%B9%E5%BC%8F-2
> 
> ![image](https://user-images.githubusercontent.com/5856440/53400316-8cdcfe80-39e8-11e9-812d-3e2d75e33527.png)

您这个 app 也是实例化过的 Application 吧，这样直接拿 app 用的场景要么需要 `this.app` 要么是写在 AppBootHook 里面的，似乎没办法直接用一个单独的 function 中。

经过指点，helper function 传递给外部 package 的时候，显式 .bind(this)，function 里里面拿到 this 就是有调用时的一切了。

感谢🙏
