### ISSUE TITLE
webstorm无法代码提示

### ISSUE THREAD

**Issue by yvissy** [eggjs/egg#3496]
![image](https://user-images.githubusercontent.com/31500815/53398707-aa767d80-3980-11e9-8acf-a92dbcc4b6db.png)

**Comment by whxaxes** [comment]
已知问题，webstorm 对 ts 的支持度不够，egg 由于要支持多层级的声明合并，所以采用了 `declare module "egg"` 的方式来写声明，但是 webstorm 在 js 项目下不认这种声明，目前还没想到好的解决方案。

暂时你可以考虑

-  用 webstorm 来写 ts egg 应用（ 如果是 ts 应用，webstorm 支持良好 ）
-  使用 vscode 来开发 egg 应用（ 一劳永逸 ）

**Comment by zhangciwu** [comment]
我的解决办法：
https://github.com/whxaxes/egg-ts-helper/issues/55#issuecomment-588149713

**Comment by chengfeng12138** [comment]
> 我的解决办法： [whxaxes/egg-ts-helper#55 (comment)](https://github.com/whxaxes/egg-ts-helper/issues/55#issuecomment-588149713)

小白不是很懂这个是怎么操作的呢, 能教我一下吗
