### ISSUE TITLE
egg 的 .d.ts 中的 getFileStream 方法缺少 options 参数声明

### ISSUE THREAD

**Issue by atzcl** [eggjs/egg#3499]
## What happens?
egg 的 .d.ts 中的 getFileStream 方法缺少 options 参数声明，分别所在的代码：

[egg: index.d.ts](https://github.com/eggjs/egg/blob/40ae443429ba956c83c813ad17ea180cb3d01b3a/index.d.ts#L899)

[egg-multipart: context.js](https://github.com/eggjs/egg-multipart/blob/f266d348abb96dd38352bdd855f1b288da09d877/app/extend/context.js#L83)

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg/pull/3500  已经有人提 PR 了

**Comment by atzcl** [comment]
好嘞
