### ISSUE TITLE
使用 nyc

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#35]
使用 https://github.com/istanbuljs/nyc 替换 istanbul

**Comment by fengmk2** [comment]
nyc 的复杂度比较大，先不用了，插件可以先尝试起。

**Comment by popomore** [comment]
nyc is slower than istanbul@0.x https://github.com/popomore/istanbul-instrument

**Comment by popomore** [comment]
coffee 也需要将 istanbul 缓存 nyc

**Comment by atian25** [comment]
@popomore 这个可以关了吧?

**Comment by popomore** [comment]
@atian25 都改完了
