### ISSUE TITLE
egg 是否对 json对象进行处理了

### ISSUE THREAD

**Issue by shenqidebaozi** [eggjs/egg#3504]
在使用aliyun-sdk的时候,使用egg框架 报错,key 不能为object 但是我输入的是string类型,同样的代码在express下正常
![image](https://user-images.githubusercontent.com/35397691/53549069-3699c800-3b6e-11e9-8627-7b8324064597.png)
![image](https://user-images.githubusercontent.com/35397691/53549099-4a452e80-3b6e-11e9-9d74-cf6b95272b94.png)
![image](https://user-images.githubusercontent.com/35397691/53549118-5af5a480-3b6e-11e9-92a0-657606a36bcc.png)

**Comment by atian25** [comment]
你指的是 `sls.putLogs()` 那个 JSON？

egg 没有做任何处理，断点看看吧

**Comment by shenqidebaozi** [comment]
> 你指的是 `sls.putLogs()` 那个 JSON？
> 
> egg 没有做任何处理，断点看看吧

不过,我测试别的框架没问题,不知道啥原因,我一会断点一下试试

**Comment by shenqidebaozi** [comment]
已解决,不知道是不是因为是egg里面对函数方法处理的问题,现在的解决办法是,写了一个外部模块,然后egg里面引用,可以正常使用阿里云日志服务了

**Comment by atian25** [comment]
提供最小可复现仓库我们可以看看

**Comment by shenqidebaozi** [comment]
https://github.com/shenqidebaozi/bug
不知道需不需要给您我的阿里云 秘钥之类的

**Comment by hyj1991** [comment]
@shenqidebaozi 是这个 https://github.com/aliyun-UED/aliyun-sdk-js 包么？

**Comment by shenqidebaozi** [comment]
> @shenqidebaozi 是这个 https://github.com/aliyun-UED/aliyun-sdk-js 包么？

是 阿里云 ued事业部搞得

**Comment by JacksonTian** [comment]
去把 issue 提到那边吧

**Comment by shenqidebaozi** [comment]
> 去把 issue 提到那边吧

提了,没人理我.

**Comment by shenqidebaozi** [comment]
> 去把 issue 提到那边吧

现在解决办法就是 脱离egg,写了个模块

**Comment by atian25** [comment]
> 已解决,不知道是不是因为是egg里面对函数方法处理的问题,现在的解决办法是,写了一个外部模块,然后egg里面引用,可以正常使用阿里云日志服务了

Egg 就是原生的 Node，没有做什么特殊的处理，你断点看看具体问题出在哪吧。

https://github.com/shenqidebaozi/bug 这个没法看啊，怎么是压缩包

**Comment by shenqidebaozi** [comment]
> > 已解决,不知道是不是因为是egg里面对函数方法处理的问题,现在的解决办法是,写了一个外部模块,然后egg里面引用,可以正常使用阿里云日志服务了
> 
> Egg 就是原生的 Node，没有做什么特殊的处理，你断点看看具体问题出在哪吧。
> 
> https://github.com/shenqidebaozi/bug 这个没法看啊，怎么是压缩包

我重新提交一下吧

**Comment by shenqidebaozi** [comment]
> > 已解决,不知道是不是因为是egg里面对函数方法处理的问题,现在的解决办法是,写了一个外部模块,然后egg里面引用,可以正常使用阿里云日志服务了
> 
> Egg 就是原生的 Node，没有做什么特殊的处理，你断点看看具体问题出在哪吧。
> 
> https://github.com/shenqidebaozi/bug 这个没法看啊，怎么是压缩包

https://github.com/shenqidebaozi/bug1

**Comment by shenqidebaozi** [comment]
现在是egg内部用会报错不知道啥原因,断点也没整明白

**Comment by atian25** [comment]
感觉你的代码有问题，https://github.com/shenqidebaozi/bug1/blob/master/app/extend/application.js#L6 这里是每一次调用都会重新 new 一个。

https://github.com/shenqidebaozi/bug1/blob/master/logs/bug/common-error.log 这里的报错跟你截图也不一样。

参考下 https://github.com/eggjs/egg-logger-sls

**Comment by shenqidebaozi** [comment]
> 感觉你的代码有问题，https://github.com/shenqidebaozi/bug1/blob/master/app/extend/application.js#L6 这里是每一次调用都会重新 new 一个。
> 
> https://github.com/shenqidebaozi/bug1/blob/master/logs/bug/common-error.log 这里的报错跟你截图也不一样。
> 
> 参考下 https://github.com/eggjs/egg-logger-sls

那个错误可能是没记录下来,我自己再研究研究吧,麻烦几位大佬了,另外用那个egg插件也是一样错误

**Comment by shenqidebaozi** [comment]
> 感觉你的代码有问题，https://github.com/shenqidebaozi/bug1/blob/master/app/extend/application.js#L6 这里是每一次调用都会重新 new 一个。
> 
> https://github.com/shenqidebaozi/bug1/blob/master/logs/bug/common-error.log 这里的报错跟你截图也不一样。
> 
> 参考下 https://github.com/eggjs/egg-logger-sls

可能我这边用的一些依赖有冲突之类的

**Comment by shenqidebaozi** [comment]
我先把issue关闭了吧
