### ISSUE TITLE
egg-scripts --host

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3509]
In egg-scripts we have `--port` option , but `--host` is missing , How can I just listen to `127.0.0.1:7000` not `0.0.0.0:7000`

**Comment by atian25** [comment]
how about just set `config.cluster.listen.hostname`

https://github.com/eggjs/egg-cluster/blob/master/lib/app_worker.js#L91

**Comment by sm2017** [comment]
Thanks a lot
