### ISSUE TITLE
PIDFile

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3511]
Related to https://github.com/eggjs/egg/issues/3508

>PIDFile=
Takes a path referring to the PID file of the service. Usage of this option is recommended for services where Type= is set to forking. The path specified typically points to a file below /run/. If a relative path is specified it is hence prefixed with /run/. The service manager will read the PID of the main process of the service from this file after start-up of the service. The service manager will not write to the file configured here, although it will remove the file after the service has shut down if it still exists. The PID file does not need to be owned by a privileged user, but if it is owned by an unprivileged user additional safety restrictions are enforced: the file may not be a symlink to a file owned by a different user (neither directly nor indirectly), and the PID file must refer to a process already belonging to the service.

It's good reason to have a PIDFile

**Comment by atian25** [comment]
landed

**Comment by sm2017** [comment]
@atian25 How can I pass pid file to `egg-scripts start`?

**Comment by atian25** [comment]
--pid-file

**Comment by sm2017** [comment]
@atian25 , I tried
`egg-scripts start --daemon --title=egg-server --pid-file=/run/egg.pid`
And
`egg-scripts start --daemon --title=egg-server --pid-file=egg.pid`
And
`egg-scripts start --daemon --title=egg-server --pid-file='/run/egg.pid'`

Not worked , there is no egg.pid generated

**Comment by atian25** [comment]
@sm2017  oh, egg-scripts will remove all argv alias(which egg-bin dev won't), so should pass `--pidFile`
