### ISSUE TITLE
如何获取当前启动的服务 是http 还是https

### ISSUE THREAD

**Issue by shenqidebaozi** [eggjs/egg#3512]
如何获取当前启动的服务 是http 还是https

**Comment by atian25** [comment]
如果是在 Nginx 后面的话，Nginx 那边一般会配置 headers 传递过来

https://eggjs.org/zh-cn/basics/controller.html#ctxprotocol

**Comment by shenqidebaozi** [comment]
> 如果是在 Nginx 后面的话，Nginx 那边一般会配置 headers 传递过来
> 
> https://eggjs.org/zh-cn/basics/controller.html#ctxprotocol

但是我现在是想在程序内获取这个,比如说我要curl请求本身

**Comment by atian25** [comment]
给的链接不是写的很清楚了么，`ctx.protocol`

**Comment by shenqidebaozi** [comment]
> ctx.protocol



> 给的链接不是写的很清楚了么，`ctx.protocol`

然而启动的https 获取到的是http

**Comment by atian25** [comment]
是直接 egg 启动的 https 还是 Nginx 做的 https 卸载？

**Comment by shenqidebaozi** [comment]
> 是直接 egg 启动的 https 还是 Nginx 做的 https 卸载？

直接启动的https

**Comment by shenqidebaozi** [comment]
![image](https://user-images.githubusercontent.com/35397691/53716821-2a28ae80-3e91-11e9-8d9c-f2133462af7b.png)

**Comment by atian25** [comment]
有没有配置 `config.proxy = true`？

**Comment by atian25** [comment]
https://github.com/koajs/koa/blob/master/lib/request.js#L403

参考 Koa 源码，Egg 里面做了一层封装，`config.proxy` 会赋值给 `app.proxy`

**Comment by shenqidebaozi** [comment]
> https://github.com/koajs/koa/blob/master/lib/request.js#L403
> 
> 参考 Koa 源码，Egg 里面做了一层封装，`config.proxy` 会赋值给 `app.proxy`

好的大佬

**Comment by guohuihot** [comment]
这个确实有问题，我也是拿不到https

**Comment by guohuihot** [comment]
![image](https://user-images.githubusercontent.com/3119995/85170084-7292f800-b29f-11ea-82e6-182ddfb248b7.png)
![image](https://user-images.githubusercontent.com/3119995/85170183-9f470f80-b29f-11ea-900d-784b816e1fbf.png)
nginx配置，但是ctx.protocol 拿到的是http

**Comment by atian25** [comment]
检查下 egg 侧收到的 headers 是啥呗
