### ISSUE TITLE
npm ERR! standard@1.0.0 start: `egg-scripts start --port=7001 --daemon`

### ISSUE THREAD

**Issue by fronzen-qin** [eggjs/egg#3515]
C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin>cnpm start

> standard@1.0.0 start C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin
> egg-scripts start --port=7001 --daemon

[egg-scripts] Starting egg application at C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin
[egg-scripts] Run node C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin\node_modules\_egg-scripts@2.11.0@egg-scripts\lib\start-cluster {"port":7001,"baseDir":"C:\\Users\\qinshi007\\Desktop\\qidou-doujin-master\\doujin","framework":"C:\\Users\\qinshi007\\Desktop\\qidou-doujin-master\\doujin\\node_modules\\egg","title":"egg-server-standard"} --title=egg-server-standard
[egg-scripts] Save log file to C:\Users\qinshi007\logs
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! standard@1.0.0 start: `egg-scripts start --port=7001 --daemon`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the standard@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qinshi007\AppData\Roaming\npm-cache\_logs\2019-03-06T04_04_14_123Z-debug.log

**Comment by atian25** [comment]
看下 `C:\Users\qinshi007\logs` 里面的具体报错。

有可能是因为 egg-scripts 不支持 win

**Comment by fronzen-qin** [comment]
@-----------------------这样的----------------------
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--userconfig=C:\\Users\\qinshi007\\.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://registry.npm.taobao.org',
1 verbose cli   'start' ]
2 info using npm@6.8.0
3 info using node@v8.9.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle standard@1.0.0~prestart: standard@1.0.0
6 info lifecycle standard@1.0.0~start: standard@1.0.0
7 verbose lifecycle standard@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle standard@1.0.0~start: PATH: D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin\node_modules\.bin;D:\app\qinshi007\product\11.2.0\dbhome_1\bin;D:\Program Files\Java\jdk1.8.0_102\bin;D:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs\node_global;D:\Program Files\nodejs\;D:\Program Files\Microsoft VS Code\bin;C:\Users\qinshi007\AppData\Roaming\npm
9 verbose lifecycle standard@1.0.0~start: CWD: C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin
10 silly lifecycle standard@1.0.0~start: Args: [ '/d /s /c', 'egg-scripts start --port=7001 --daemon' ]
11 silly lifecycle standard@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle standard@1.0.0~start: Failed to exec start script
13 verbose stack Error: standard@1.0.0 start: `egg-scripts start --port=7001 --daemon`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid standard@1.0.0
15 verbose cwd C:\Users\qinshi007\Desktop\qidou-doujin-master\doujin
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\qinshi007\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "start"
18 verbose node v8.9.0
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error standard@1.0.0 start: `egg-scripts start --port=7001 --daemon`
22 error Exit status 1
23 error Failed at the standard@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


> 看下`C:\Users\qinshi007\logs`里面的具体报错。
> 
> 有可能是因为egg-scripts不支持win

**Comment by atian25** [comment]
看 common-error..

**Comment by popomore** [comment]
应该是在 path 里面找不到 node，看看是不是 egg-scripts 的 path 不兼容 win

**Comment by qingdengyue** [comment]
npm版本**6.8.0**，对应的Node版本是**11**。错误信息里的Node版本是 **8.9.0**。两个Node版本不一致？

**Comment by fronzen-qin** [comment]
我之前安装的是11，又来老板说可能是node的问题，让我装8.9 ，但还是没能跑起来，我重找了个代码能跑，这个不管了，应该是环境问题，谢谢你哈发自我的华为手机

**Comment by fronzen-qin** [comment]
应该是环境问题，别的电脑能跑，谢谢你，我用线上的就行，发自我的华为手机
