### ISSUE TITLE
egg-ant-design-pro。执行dev出错

### ISSUE THREAD

**Issue by lzuwen** [eggjs/egg#3516]
Node Version:v11.30
Egg Version: 2.14.2
Plugin Name:
Plugin Version:
Platform:Win 7
Mini Showcase Repository:
执行dev时，提示如下:
![image](https://user-images.githubusercontent.com/44759266/53870683-a956e780-4035-11e9-886c-81086279b3e4.png)

2019-03-06 17:21:12,734 INFO 3772 [master] node version v11.3.0
2019-03-06 17:21:12,736 INFO 3772 [master] egg version 2.14.2
2019-03-06 17:21:13,879 INFO 3772 [master] agent_worker#1:3940 started (1139ms)
2019-03-06 17:21:15,189 INFO 3772 [master] egg started on http://127.0.0.1:7001 (2452ms)

* Webpack █████████████████████████ emitting (95%) unnamed compat plugin

(node:10876) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Starting the development server...

Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.

**Comment by popomore** [comment]
我能正常启动，这个提示是个 warning 信息

**Comment by lzuwen** [comment]
启动都一值卡在这里：
Demo地址：https://github.com/lzuwen/egg-ant-design-demo

**Comment by qingdengyue** [comment]
Windows 版本：Windows 10   10.0.17134
临时解决方案:
去掉: app/web/config/plugin.config.js 中的图中所示配置:
![image](https://user-images.githubusercontent.com/3230673/53952619-39676080-410c-11e9-9edc-6d2b09f15d1a.png)
