### ISSUE TITLE
egg-security-csrf support config cookie secure

### ISSUE THREAD

**Issue by daifee** [eggjs/egg#3517]
## Background
I found a bug when meet the following conditions：
- web server both supports HTTPS and HTTP.
- enable egg-security-csrf.
- > Chrome 58

**Reproduce the bug:**

1. user visits HTTPS page.
    - web server response the cookie set-cookie: csrf_token=val; secure.
    - Chrome set cookie.
2. user visits new page(HTTP) in the same session.
    - browser does not send the cookie(expected).
    - web server response new cookie set-cookie: csrf_token=val;(expected).
    - Chrome can not overwrite the cookie csrf_token(not my expected, but it is Specification)

## Proposal

**support config cookie secure**

```js
const cookieOpts = {
  domain: cookieDomain && cookieDomain(this),
  signed: false,
  httpOnly: false,
  overwrite: true,
  secure: this.app.config.security.csrf.cookieSecure
};
this.cookies.set(cookieName, secret, cookieOpts);
```

## Additional context

[Koa auto detects cookie secure](https://github.com/koajs/koa/pull/1313)

**Comment by popomore** [comment]
According to the issue you referred to koa, the proposal is rejected. Maybe you can redirect 80 to 443, and always use https.

**Comment by daifee** [comment]
I think expose the config is better. 
Koa can be configured, but egg-security hides it.
