### ISSUE TITLE
mac/egg/webstorm 断点无效

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3518]
## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v10.12.0
- **Egg 版本**：v2.2.1
- **Webstorm 版本**：2018.2

1.根据官网配置
<img width="626" alt="2019-03-07 12 30 36" src="https://user-images.githubusercontent.com/23513805/53932549-0b1a5e80-40d5-11e9-8f18-6c2238d934de.png">
2.浏览器访问7001 进行get请求
<img width="857" alt="2019-03-07 12 33 07" src="https://user-images.githubusercontent.com/23513805/53932587-41f07480-40d5-11e9-9819-291999291bad.png">
3.断点没有效果

ps：devtools 可以正常断点

**Comment by atian25** [comment]
如果 devtools 可以断点，那说明是 WebStorm 的 Bug，我们做不了什么

**Comment by atian25** [comment]
你确定你是用 WebStorm 启动么？ 第二张截图里面的端口是 9229，WebStorm 会传递一个更大的端口的。

你试试重新安装依赖看看，不行的话就没办法了。

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by MJingv** [comment]
> 你确定你是用 WebStorm 启动么？有没有点击那个 Debug 按钮？
> 从第二张截图来看，里面的端口是 9229，而 WebStorm 会通过环境变量传递一个更大的端口的。
> 
> 你试试重新安装依赖看看，不行的话就没办法了。
> 
> hey, please retry after reinstall dependencies and please **never lock** it.
> 
> ```shell
> $ # reinstall deps and never lock it.
> $ rm -rf node_modules yarn.lock package-lock.json
> $ npm i --no-package-lock

> ```

- 1. 重新安装
- 2.debug信息
<img width="579" alt="2019-03-07 14 09 09" src="https://user-images.githubusercontent.com/23513805/53935849-db725300-40e2-11e9-8896-39df8e6b2c40.png">
- 3.npm run debug
<img width="948" alt="2019-03-07 14 08 57" src="https://user-images.githubusercontent.com/23513805/53935874-ed53f600-40e2-11e9-91a9-066d02aa6f07.png">
- 4. postman请求
<img width="546" alt="2019-03-07 14 09 32" src="https://user-images.githubusercontent.com/23513805/53935900-0492e380-40e3-11e9-8846-522932d32b2b.png">
麻烦再看看
ps：是请求端口错误吗？

**Comment by atian25** [comment]
。。。 WebStorm 是点击上面的调试按钮。。。 而不是在终端里面手动执行 npm run debug....

**Comment by MJingv** [comment]
不好意思，刚开始用webstorm 感谢🙏
