### ISSUE TITLE
路由未匹配，如何统一返回404页面

### ISSUE THREAD

**Issue by axetroy** [eggjs/egg#352]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

看了[异常处理 - 为企业级框架和应用而生](https://eggjs.org/zh-cn/core/error-handling.html)

引入egg-onerror插件，页面异常的时候，还是返回404 not Found，并没有返回设置的页面？

```javascript
// config/plugin.js
exports.onerror = {
  enable: true,
  package: 'egg-onerror'
};
```

```javascript
// config/config.default.js
'use strict';

const path = require('path');

module.exports = appInfo => {
  const config = {};

  config.view = {
    dir: [
      path.join(appInfo.baseDir, 'app/view')
    ].join(',')
  };

  config.onerror = {
    errorPageUrl: '/public/404.html',
  };

  config.middleware = ["errorHandler"];
  config.errorHandler = {
    match: '/api',
  };

  return config;
};
```

**Comment by dead-horse** [comment]
这个配置的是 errorPage，也就是返回服务器异常的时候，404 不是服务器异常。你可以在配置里面配一下:

```js
// config/config.default.js
module.exports = {
  notfound: {
    pageUrl: '/public/404.html',
  },
};
```

这样会设置默认的 404 页面，如果是生产环境 404 的话就会跳转到这个页面。

具体的实现代码可以参考：https://github.com/eggjs/egg/blob/master/app/middleware/notfound.js#L21

后面我会在文档里面补上。

**Comment by axetroy** [comment]
@dead-horse 

文档是这样描述的，好吧，是我没理解。
怎么感觉有点慌(逃

> onerror 插件的配置中支持 errorPageUrl 属性，当配置了 errorPageUrl 时，一旦用户请求线上应用的 html 页面异常，就会重定向到这个地址。

**Comment by dead-horse** [comment]
划重点：**这个配置的是 errorPage，也就是服务器异常的时候，404 不是服务器异常。**

**Comment by atian25** [comment]
还有，onerror 插件已经内置了，不用自己引入。

另外，你 config 里面的那几项配置，如 view 啥的，跟默认配置一样的，可以干掉
