### ISSUE TITLE
Zero length body

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3520]
How can I have `zero length` body?
My `ctx.status` is `202` =  `Accepted` , I don't set ctx.body but egg  set it as empty object , for 204 egg has no body , but I want to set status 202 as the task is just accepted and will done later

@see https://greenbytes.de/tech/webdav/rfc7230.html#message.body

**Comment by atian25** [comment]
https://github.com/koajs/koa/blob/master/lib/response.js#L140

try:

```js
    this.ctx.status = 202;
    this.ctx.body = '';
```

**Comment by sm2017** [comment]
@atian25 see https://github.com/koajs/koa/issues/1314#issuecomment-470594686

What you think?

**Comment by denghongcai** [comment]
try

```js
this.ctx.status = 202;
this.ctx.body = new Buffer(0);
```

**Comment by atian25** [comment]
```js
    this.ctx.status = 202;
    this.ctx.body = Buffer.from('');
```
