### ISSUE TITLE
egg-logrotator 是否支持按天切割自定义日期形式

### ISSUE THREAD

**Issue by llsldwy** [eggjs/egg#3521]
咨询一下， egg-logrotator  是否支持 按天切割自定义日期格式，我看了一眼说明，按天格式是在每日 00:00 按照 .log.YYYY-MM-DD 文件名进行切割，也就是 是否能把文件命名为 .log-YYYY-MM-DD ？ 我看了一下egg-logrotator源码，貌似是 固定写成了  .log.YYYY-MM-DD 这个到格式，我想咨询一下，是否向我观察到那种情况，目前不支持 自定义日期名后缀。因为公司有统一到文件生产规则，所以才有此疑问，忘各位大佬，帮忙解答下。谢谢

**Comment by atian25** [comment]
egg-logrotator 预留了扩展接口，你可以自定义一个策略即可。

**Comment by llsldwy** [comment]
@atian25  好的，谢谢
