### ISSUE TITLE
如何在static捕获路由之前，通过router来提前捕获一个静态资源路由

### ISSUE THREAD

**Issue by bookyo** [eggjs/egg#3523]
很多情况下，我们需要在static静态资源捕获一个文件之前，通过router捕获这个文件，然后再进行一些认证处理，比如说/public/1.jpg，我需要在static内置插件捕获这个路由之前，通过router来捕获/public/1.jpg这个路由，并且在其中处理一些逻辑，之后再next()或者直接返回处理后的逻辑。

在expressjs中实现还是比较简单，就直接app.use(express.static(path.join(__dirname, "public")))之前调用app.use()来提前捕获路由。但是在eggjs中因为约束问题，自然无法这样处理。

请问，在eggjs中有能实现这个需求的方法吗？

**Comment by popomore** [comment]
写一个中间件，插到 static 前面

**Comment by bookyo** [comment]
我的解决方案如下：
创建一个middleware：
test.js
```
'use strict';
module.exports = () => {
  return async function test(ctx, next) {
    if (/^\/public\/[0-9]\.txt$/.test(ctx.request.url)) {
      return (ctx.body = {
        message: '对不起，您的访问不符合要求',
      });
    }
    return await next();

  };
};
```
然后在router.js中匹配到static中间价，并且将test中间件插入到static前面去：
```
const index = app.config.coreMiddleware.indexOf('static');
const test = app.middleware.test();
app.middleware.splice(index, 0, test);
```
多次尝试之后，发现这样可以实现在static捕获静态文件之前利用中间价先捕获到然后再进行处理。
