### ISSUE TITLE
在单元测试中，无法关闭【一个测试用例】的console日志

### ISSUE THREAD

**Issue by csr632** [eggjs/egg#3524]
## What happens?

`mock.consoleLevel('NONE');`语句，如果放在顶层会关闭**所有**测试用例的console日志（但这不是一个好的实践）；如果放在一个测试用例中则没有任何效果（没有关闭任何console日志）。
然而很多时候**我希望精确地控制console日志的输出级别（以测试用例为粒度）**。因为在有一些测试用例中，我是**期望抛出的错误被egg-onerror处理的**，而egg-onerror会打印错误日志，让测试的输出非常难看。如下图
![image](https://user-images.githubusercontent.com/18747423/54066356-772dcb80-4269-11e9-87ec-4e277492a883.png)
如图，测试表现符合预期的情况下，依然打印出了错误日志。

另外，mock.consoleLevel的效果似乎不会因为mock.restore而取消。因为在`require('egg-mock/bootstrap')`的时候会注册`afterEach(mock.restore)`的钩子，而顶层`mock.consoleLevel`的效果会一直持续。

## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/csr632/egg-logger-issue

## 复现步骤，错误日志以及相关配置

yarn install
yarn test

可以发现，虽然在运行`should GET /`测试用例之前调用了`mock.consoleLevel('NONE');`，但是还是会输出错误日志。如果这种情况比较多，测试的输出会非常冗长，查看测试日志需要不断向上滚动。

## 相关环境信息
见复现repo

**Comment by popomore** [comment]
要知道这个 consoleLevel 是在应用启动的时候加载的，所以只能启动前定义，在单测里面定义是没用的。

**Comment by csr632** [comment]
谢谢解答。那么这个场景下应该怎么做呢？毕竟按照egg团队的建议（[2262](https://github.com/eggjs/egg/issues/2262), [2181](https://github.com/eggjs/egg/issues/2181)），关闭所有日志是不好的。

能否让logger在打印之前判断一下`process.env.EGG_LOG`?

**Comment by csr632** [comment]
还有一种简单的办法，能否让egg-mock提供一个方法，允许用户mock掉ctx.logger?
我不知道目前如何在[使用app.httpRequest()](https://github.com/csr632/egg-logger-issue/blob/d4fda4bf1b2996d3eb36cb40856a0c19cef7ed53/test/app/controller/home.test.js#L21)的时候获得这个请求产生的ctx。如果能拿到这个ctx的话，问题就好解决了

**Comment by atian25** [comment]
单元测试时不都是 assert 的么，你把 level 不要那么高就好了。

egg-mock 有个 mockLog 和 expectLog 来基于日志文件测试的。

**Comment by csr632** [comment]
1. 单元测试代码中确实是通过assert来断言的。但是这个issue中的Error log是由于**应用代码**抛出的错误而产生的。所以问题与是否使用assert没有多大关系。
2. 如果要通过降低log level来阻止Error log打印到终端，那么只能将log level设置成none（因为egg-onerror打印的日志是ERROR级别的），而如3楼所说，这是很不好的实践。这等价于“**为了不打印意料之内的错误，用户必须同时忽略掉意料之外的错误**”。
3. httpRequest 是黑盒测试，但是egg还是允许用户`mockService`, `mockHttpclient`呀！
4. 我提出的方案类似这样：
```js
before(()=> {
  app.mockMiddleware(async (ctx) => {/*这里可以做各种事情，包括修改ctx上的属性、mock掉ctx上的方法*/});
})
it('test case', ...)
after(mock.restore) // 取消mockMiddleware的效果
```
mockMiddleware能够给测试者提供非常多的灵活性，不仅限于解决当前的issue。而且不会破坏任何已有的代码。

**Comment by lkiarest** [comment]
有同样的需求，在测试结果里打印了太多太多没有必要展示的，已经在 onerror 里处理过的错误信息了。最好在 onerror 插件加一个设置，可以指定不打印已经处理的错误。

**Comment by atian25** [comment]
@lkiarest 你可以把 errorLogger 的 level 设置下。

@csr632 你可以写个 app/extend/application.unittest.js 里面来自行扩展这个方法。

**Comment by lkiarest** [comment]
全部关掉遇到需要处理的异常就跪了~~目前只能加一个环境变量来控制开关了：
package.json:
```
    "test": "egg-bin test",
    "test:debug": "EGG_TEST_DEBUG=true yarn test",
```

**Comment by popomore** [comment]
应该所有错误都是 logger 打的，未捕获异常应该打到 stderr 的，还是会显示的，你要调试的时候打开 consoleLevel 即可。

**Comment by atian25** [comment]
feel free to reopen this issue if provided more information.
