### ISSUE TITLE
在QQ手机浏览器中请求.ts文件异常 提示nodejs.EPIPEError: write EPIPE

### ISSUE THREAD

**Issue by bookyo** [eggjs/egg#3527]
## What happens?
在我测试中，在QQ手机浏览器中请求m3u8文件会直接出错，直接无法播放，再次测试请求TS文件，则控制行报错。
猜测就是因为请求M3U8文件的时候，请求其中的ts文件报错，直接无法播放。

2019-03-11 00:27:59,755 ERROR 23862 [-/undefined/-/353ms GET /public/videos/5c813168bbcd123f02662a6c/index1.ts] nodejs.EPIPEError: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
errno: "EPIPE"
code: "EPIPE"
syscall: "write"
headerSent: true
name: "EPIPEError"
pid: 23862

![image](https://user-images.githubusercontent.com/20472717/54088096-0257b000-4395-11e9-9109-dfab75416dde.png)

**Comment by atian25** [comment]
这是视频文件吧？ 放在 static 下的？不要这么玩，static 只用于放置一些简单的静态文件（实际上大部分静态文件应该在构建期丢到 CDN 去）

更何况这种比较大的视频文件，static 是有 cache 的，每个进程都有，会爆内存的。丢 CDN 去吧。

**Comment by bookyo** [comment]
@atian25 我是使用ffmpeg生成的m3u8和大量的ts，必须提供一个静态地址给用户访问，丢CDN貌似暂时没办法，这情况如何是好，或者用一个文件夹存在m3u8和生成的ts，然后用nginx处理静态文件？

**Comment by popomore** [comment]
用 nginx 吧，你这个问题需要提供一个可重现的例子
