### ISSUE TITLE
怎么将session保存到redis、mongo、mysql中，是不是要写egg-session-redis、egg-session-mongo、...插件

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#353]
怎么将session保存到redis、mongo、mysql中，是不是要写egg-session-redis、egg-session-mongo、egg-session-mysql插件呢？

**Comment by dead-horse** [comment]
可以直接引入 https://github.com/koajs/generic-session 中间件即可

**Comment by jtyjty99999** [comment]
目前内置的session插件只是cookie store，可以使用其他的session组件

**Comment by atian25** [comment]
加个 example ？

**Comment by sunshinexb** [comment]
@atian25  这个可以有

**Comment by dead-horse** [comment]
最简单的使用方法：

- 关闭 egg-session 插件

```js
// config/plugin.js
exports.session = false;
```

- 自己引入 koa-generic-session 中间件，可以参考 [middleware](https://eggjs.org/zh-cn/basics/middleware)章节。

后续我有改造 [koa/session](https://github.com/koajs/session) 来支持多种存储的计划，所以暂时不在文档里面推荐上面说的使用方式了。

另外，我觉得99%的情况下都不需要将 session 存放到其他存储中，相较来说更推荐：

1. 精简 session 中的内容，存放到 cookie 中。
2. 实在有需要按照用户缓存的内容，可以根据 cookie 中的 token 或者用户 ID 来自己从缓存中读取。

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/core/cookie-and-session.html#session
