### ISSUE TITLE
Dependency upgrade needed

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3530]
It's seems needed to upgrade dependencies

```
warning egg > egg-cluster > egg-logger > circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
warning egg > urllib > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
warning "egg-bin > espower-typescript@9.0.1" has unmet peer dependency "typescript@>= 2.4.2".
```

**Comment by atian25** [comment]
> warning egg > urllib > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0

@dead-horse upgrade a major urllib to drop 4.x ?

**Comment by popomore** [comment]
Depend on urllib https://github.com/node-modules/urllib/issues/316
