### ISSUE TITLE
在node-v8.15.0以上版本，egg-socket.io与node存在变量冲突

### ISSUE THREAD

**Issue by zhangshichun** [eggjs/egg#3531]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `egg-init --type=simple bug` then upload to your GitHub
看下面这个仓库
https://github.com/hyj1991/egg-socket.io-error-demo

## How To Reproduce

**Steps to reproduce the behavior:**
1.使用egg-socket.io 在centos 7.66 上部署，使用版本为v8.15.1 到 v10.xx
2.前端发起长链接

**Expected behavior**
1.正常链接

## Context
- **Node Version**:v8.15.1 到 v10.xx
- **Egg Version**:^2.2.1
- **Plugin Name**:egg-socket.io
- **Plugin Version**:^4.1.5
- **Platform**:https://github.com/nodejs/node/issues/26366 错误和这个如出一辙。

node切换到v8.15.0可解决此问题，受此困扰的通报，请尝试降低node版本到v8.15.0

**Comment by lvsenlin** [comment]
同样遇到，10.15.1可以

**Comment by ngot** [comment]
这个是 Node.js 本身的变更导致的，关注官方 issue ，在解决之前不要升级 https://github.com/nodejs/node/issues/26366

**Comment by An0313** [comment]
就是这个问题 让我痛苦了两个星期 我都要怀疑人生了 -----node -v   10.15.3

**Comment by iguxiaobei** [comment]
10.15.3不可以，10.15.1可以。
