### ISSUE TITLE
egg-validate default不起作用

### ISSUE THREAD

**Issue by Gitforxuyang** [eggjs/egg#3532]
## What happens?

使用egg-validate，设置了default，当发起一个get请求时，如果没有传任何参数。则default不会起任何作用。
经过查看源码发现，egg->app->extend->request文件_customQuery方法中，如果http请求没有传递任何参数，则会直接返回{}。所以这段代码应该就是导致egg-validate的default不起作用的原因。因为每次get query都会重新执行_customQuery函数，所以每次都会返回一个{}。

关键源代码如下：
// How to read query safely
  // https://github.com/koajs/qs/issues/5
  _customQuery(cacheName, filter) {
    const str = this.querystring;
    **if (!str) {
      return {};
    }**
    let c = this[cacheName];
    if (!c) {
      c = this[cacheName] = {};
    }
    let cacheQuery = c[str];

## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/Gitforxuyang/egg-validate-bug

## 复现步骤，错误日志以及相关配置
执行egg示例
请求 127.0.0.1:7001/

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：8.15.0
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
https://github.com/Gitforxuyang/egg-validate-bug

里面没有看到你说的代码。

**Comment by Gitforxuyang** [comment]
@atian25  node_modules我重新上传了。在这儿 https://github.com/Gitforxuyang/egg-validate-bug/blob/master/node_modules/egg/app/extend/request.js

**Comment by dead-horse** [comment]
@Gitforxuyang 感谢反馈， #3535 这里修复

**Comment by Gitforxuyang** [comment]
@dead-horse 谢谢
