### ISSUE TITLE
上传图片，获取formdata里面的参数问题

### ISSUE THREAD

**Issue by wxw1314** [eggjs/egg#3538]
上传图片时，用ctx.getFileStream()获取流信息。
前端如果传递下列参数
![image](https://user-images.githubusercontent.com/20658834/54191413-d5201480-44f0-11e9-9754-74d9c3667f7e.png)
用stream.fields可以拿到isOverSea参数
但是如果两个参数传递顺序转换一下，如下
![image](https://user-images.githubusercontent.com/20658834/54191607-3516bb00-44f1-11e9-85b7-3484cd0ee472.png)
是取不到isOverSea参数
不知道是什么原因导致的
## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
文档里面写了，file 要放在最后。

因为解析是顺序执行的，当你 file 在前面的时候，`await ctx.getFileStream()` 时，后面的 field 还没来得及解析。

**Comment by wxw1314** [comment]
> 文档里面写了，file 要放在最后。
> 
> 因为解析是顺序执行的，当你 file 在前面的时候，`await ctx.getFileStream()` 时，后面的 field 还没来得及解析。

那你知道怎么解决吗，用了ctx.multipart({ autoFields: true })好像也没法解决

**Comment by atian25** [comment]
调整前端的顺序

**Comment by atian25** [comment]
如果你对 stream 不熟悉，可以直接用 file 模式
