### ISSUE TITLE
最新版本是Version 2.20.1，怎么我下载的时候还是2.15.1

### ISSUE THREAD

**Issue by 750973092** [eggjs/egg#3539]
## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

npm i egg-init -g
egg-init egg-example --type=simple 
执行这两条命令后不是最新版本

## 相关环境信息
- **操作系统**：win8
- **Node 版本**：v10.10.0
- **Egg 版本**：

**Comment by atian25** [comment]
`"egg": "^2.15.1",` 不代表你安装的就是 2.15.1，里面有个 `^`。

可以去学习下 Semver 和 npm install 的相关知识。

**Comment by unclexiao** [comment]
我猜你是查看了[egg-init](https://github.com/eggjs/egg-init)的版本对吧？

执行的命令是否这个：
```
egg-init  --version
```

如果是的话那你打错字了，因为这个包的版本是1.15.1而不是2.15.1
```json
{
  "name": "egg-init",
  "version": "1.15.1",
  "description": "Init egg app helper tools.",
}

```


如果要查egg的本地版本，应该是才对：
```
npm list egg
```

如果要查egg的远程（最新发布）的版本，那就应该这样：
```
npm view egg 
```

除了以上天猪大佬的回复，还有一点需要注意，就是下载的版本最终有[npm](https://www.npmjs.com/)仓库决定，而不是Github。当然规范的项目（集成了CI），一般都会保持同步的。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-boilerplate-simple/blob/master/boilerplate/_package.json#L10

@unclexiao 不是的，他应该是安装后，看了 package.json 里面的描述，对 `^` 这个 npm 的安装机制不太熟悉。

**Comment by 750973092** [comment]
谢谢各位大佬了，我的问题，我是看了package.json里面的描述，

**Comment by atian25** [comment]
`^2.0.0` 的意思就是：帮我安装 `[2.0.0, 3.0.0)` 区间里面的最大的那个版本。
