### ISSUE TITLE
egg.js 如何输出(render)一个base64的图片

### ISSUE THREAD

**Issue by shipfi** [eggjs/egg#3541]
有一个base64编码的二维码PNG图片，如下代码所示：
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKQAAACkCAYAAAAZtYVBAAAAAklEQVR4AewaftIAAAYXSURBVO3BQY4cy5LAQDLQ978yR0tfJZCoain+GzezP1jrEoe1LnJY6yKHtS5yWOsih7UucljrIoe1LnJY6yKHtS5yWOsih7UucljrIoe1LnJY6yKHtS7yw4dU/qa......Jggg==`

那么我如何将图片render到页面，不是通过html+image的方式，而是直接在浏览器中输出图片，以便html可以直接在<img src>中可以引用此URL链接。

试了一些方法不行。我本来想的方式如下，但图片出不来。
```
let imageData = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKQ....";
this.ctx.set("Content-Type","image/png");
this.ctx.body = imageData;
```

**Comment by popomore** [comment]
套个外套 img 标签

**Comment by zozowind** [comment]
```
    //去掉base64的头部分, 转成buffer
    const base64 = 'iVBORw0KGgo...==';
    const imageBufferData = Buffer.from(base64, 'base64');
    ctx.body = imageBufferData;
    ctx.response.type = 'image/png';
```
