### ISSUE TITLE
关于在微信客户端上有部分 csrftoken 的 cookies 丢失问题

### ISSUE THREAD

**Issue by kamilic** [eggjs/egg#3543]
## Background
在微信客户端中用户发起 post 请求，返回 missing csrf token
在日志中发现 cookie 没有带上 csrfToken 导致 egg-security 中的 csrfToken 校验报错
https://github.com/eggjs/egg-security/blob/189064406befc7e284f67eb22d95aa1d13079ee9/app/extend/context.js#L147

在除微信的多个端以外都能够正常运行，这应该不是框架的问题，而是微信客户端的问题。

在 egg-security 中的校验方法中，有个这样的条件
https://github.com/eggjs/egg-security/blob/189064406befc7e284f67eb22d95aa1d13079ee9/app/extend/context.js#L140

能否通过修改 egg-security 的配置，让调用方传入一个自定义的 matching 根据 context 来控制是否启用 csrfToken 的校验呢？
https://github.com/eggjs/egg-security/blob/189064406befc7e284f67eb22d95aa1d13079ee9/lib/utils.js#L53

考虑到直接去动内部的 opt 对象比较容易留坑，而且不好维护，看看能否通过框架方面解决这个问题。
谢谢

**Comment by popomore** [comment]
支持的，match/ignore 都支持

**Comment by kamilic** [comment]
> 支持的，match/ignore 都支持

这两个配置都支持可以直接传入函数？

**Comment by unclexiao** [comment]
首先小程序不支持Set-Cookies，需要手动设置Header，所以很有可能是你没管理好Cookies和Token（由于生命周期复杂性）。

其次，在这里强烈推荐一下[flyio](https://github.com/wendux/fly)的拦截器，如果没有或者过期就重新获取。

它完全兼容前端主流的[axios](https://github.com/axios/axios)库，并且还支持lock，登录未完成之前，其它请求会进入等待队列，非常赞的设计👍

再次，配合楼上说的match/ignore，能很好兼容小程序场景。

最后推荐一下我在做的一个插件：[egg-mp](https://github.com/unclexiao/egg-mp)，希望帮助大家迅速解决微信小程序问题。

**Comment by kamilic** [comment]
> 首先小程序不支持Set-Cookies，需要手动设置Header，所以很有可能是你没管理好Cookies和Token（由于生命周期复杂性）。
> 
> 其次，在这里强烈推荐一下[flyio](https://github.com/wendux/fly)的拦截器，如果没有或者过期就重新获取。
> 
> 它完全兼容前端主流的[axios](https://github.com/axios/axios)库，并且还支持lock，登录未完成之前，其它请求会进入等待队列，非常赞的设计👍
> 
> 再次，配合楼上说的match/ignore，能很好兼容小程序场景。
> 
> 最后推荐一下我在做的一个插件：[egg-mp](https://github.com/unclexiao/egg-mp)，希望帮助大家迅速解决微信小程序问题。

这个不是小程序的问题，谢谢回复
