### ISSUE TITLE
用ngrok代理的域名拿不到csrf

### ISSUE THREAD

**Issue by 750973092** [eggjs/egg#3546]
## What happens?

用ngrok做本地穿透生成域名代理访问的时候csrf没有获取到值，但用本地127.0.0.1:7001可以直接访问获取；
补充下：ngrok域名直接在浏览器访问拿不到csrf，但在nuxt上可以用axios请求拿到
## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：win64
- **Node 版本**：10.10.0
- **Egg 版本**：^2.15.1

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
