### ISSUE TITLE
config.default.js自定义customLoader异常

### ISSUE THREAD

**Issue by hojit** [eggjs/egg#3547]
Node Version: 10.15.1
Egg Version: 2.20.1
Plugin Name:
Plugin Version:
Platform:
Mini Showcase Repository:
在config.default.js文件中配置了自定义端口：
`customLoader: {
            // 定义在 app 上的属性名 app.api
            api: {
                // 相对于 app.config.baseDir
                directory: 'app/api',
                // 如果是 ctx 则使用 loadToContext
                inject: 'app',
                // 是否加载框架和插件的目录
                loadunit: false
            }
}`
这样配置无法加载api目录下文件，出现以下异常：
![ssssss](https://user-images.githubusercontent.com/24590630/54472538-a6fa4780-4804-11e9-8f0e-6cdb24cdb8a2.png)

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by hojit** [comment]
@atian25 https://github.com/hojit/egg-bug/blob/6eb656a907605d91911786d12bdd211708450833/config/config.default.js#L21 
配置customLoader时，项目启动报异常

**Comment by atian25** [comment]
你的 api 目录下的文件都不是 class 啊，需要自己覆盖 initiazie

**Comment by hojit** [comment]
@atian25 我本来是想扩展一个目录，专门放一些API请求之类的纯方法，就跟extend helper.js一样，可以获取到app,ctx等，虽然我看了文档，但还不是很理解，(^_^)

**Comment by atian25** [comment]
initializer

https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/custom_loader.js

**Comment by hojit** [comment]
@atian25 谢谢

**Comment by atian25** [comment]
@hojit 最新版支持了 exports 的形式了。
