### ISSUE TITLE
agent logger的初始化在configWillLoad之前进行了

### ISSUE THREAD

**Issue by sinalvee** [eggjs/egg#3548]
## What happens?

`agent` `logger`的初始化在`configWillLoad`之前进行了，导致无法在`agent.js`的`configWillLoad`钩子更改日志的配置

## 最小可复现仓库
> 请使用 `egg-init --type=simple bug` 创建，并上传到你的 GitHub 仓库

https://github.com/sinalvee/eggjs-agent-logger-init-issue

## 复现步骤，错误日志以及相关配置

1. config/config.default.js中设置日志目录

```js
  config.logger = {
    dir: path.join(appInfo.root, 'logs/configDir'),
  };
```

2. `agent.js` `configWillLoad`钩子修改日志目录

```js
const path = require('path');

class AgentBootHook {
  constructor(agent) {
    this.agent = agent;
  }

  configWillLoad() {
    this.agent.config.logger.dir = path.join(this.agent.baseDir, 'logs/agentDir');
  }
}


module.exports = AgentBootHook;
```

3. `app.js` `configWillLoad`钩子修改日志目录

```js
const path = require('path');

class AppBootHook {
  constructor(app) {
    this.app = app;
  }

  configWillLoad() {
    this.app.config.logger.dir = path.join(this.app.baseDir, 'logs/appDir');
  }
}

module.exports = AppBootHook;
```

4. 启动服务，`app`的日志被写到了`logs/appDir`中，而`agent`的日志目录并没有被更改

## 问题分析

`egg`源码中，`egg/lib/agent.js`文件`_wrapMessenger`方法中使用了`this.coreLogger.warn`，因此`logger`在`configWillLoad`之前就初始化了

```js
  _wrapMessenger() {
    for (const methodName of [ 'broadcast', 'sendTo', 'sendToApp', 'sendToAgent', 'sendRandom' ]) {
      wrapMethod(methodName, this.messenger, this.coreLogger);
    }

    function wrapMethod(methodName, messenger, logger) {
      const originMethod = messenger[methodName];
      messenger[methodName] = function() {
        const stack = new Error().stack.split('\n').slice(1).join('\n');
        logger.warn('agent can\'t call %s before server started\n%s',
          methodName, stack);
        originMethod.apply(this, arguments);
      };
      messenger.once('egg-ready', () => {
        messenger[methodName] = originMethod;
      });
    }
  }
```

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v10.13.0
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
logger 的配置，直接在 config 里面修改就好了，没必要到 boot 这里改

**Comment by sinalvee** [comment]
我们这边日志目录的规则是`/data/logs/版本号-项目名-端口`，并行的版本多了的话，就需要把日志的配置都复制粘贴一遍到新的conig.{env}.js里，想在boot这里设置是想省掉一些复制粘贴的操作，config.{env}.js里只需要修改版本信息，日志目录在一个地方处理就好
