### ISSUE TITLE
egg-redis 

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#355]
we need cache plugin: https://github.com/eggjs/egg/issues/353#issuecomment-279150550

maybe we can choose https://github.com/luin/ioredis

**Comment by jtyjty99999** [comment]
pit https://github.com/eggjs/egg-redis

**Comment by dead-horse** [comment]
if the plugin's name is `egg-redis`, maybe we should use `app.redis` instead of `app.ioredis`? 

https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L7

**Comment by fengmk2** [comment]
@jtyjty99999 should add a remote ping to do the ready check https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L14

**Comment by jtyjty99999** [comment]
@dead-horse @fengmk2 still in progress, I will start up a new pr for ready release
