### ISSUE TITLE
session 值获取失败

### ISSUE THREAD

**Issue by ChunrunHan** [eggjs/egg#3550]
- [ ] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**:
- **node version**:
- **egg version**: 2.20.1
- **plugin name**:
- **plugin version**:
- **platform**:
- **git repo**: https://github.com/ChunrunHan/eggjs-server

### Reproduction
# 第一步：用户获取验证码
```javascript
// 1.router.js
  router.get('/captcha',controller.user.getCaptcha)
// 2.controller/user.js
  // 获取验证码
  async getCaptcha(){
    const {ctx} = this;
    var captcha = ctx.service.user.getCaptcha();
    ctx.session.code = captcha.text; // session 存储
    console.log('session 存储',ctx.session.code)
    ctx.body = captcha.data;
  }
//3.登录获取session.code undefined
  router.post('/login',controller.user.userLogin)
  // 登录
  async userLogin(){
    const {ctx} = this;
    console.log(ctx.request.body)
    let body = ctx.request.body;
    const { username, password, code } = ctx.request.body
    let resMsg = {
      code: 0,
      data: {},
      msg: '登录成功'
    }
    let isCaptchaVali = ctx.service.user.checkCaptcha(code)
    if (!isCaptchaVali) {
      resMsg.code = 1
      resMsg.msg = '验证码错误'
      ctx.body = resMsg
      return
    }
}

 // 检查验证码是否正确
  checkCaptcha(code){
    const {ctx} = this;
    code = code.toLowerCase()
    console.log("sessionCode",ctx.session.code)  // undefined?????????????
    let sessCode = ctx.session.code? ctx.session.code.toLowerCase():null
    console.log("sesscode",sessCode)
    //验证
    if(code === sessCode){
      // 成功之后验证码作废
      ctx.session.code = null
    }
    return code === sessCode;
  }
```

**Comment by ngot** [comment]
Duplicated with https://github.com/eggjs/egg/issues/3549

**Comment by ChunrunHan** [comment]
`  // 检查验证码是否正确
  checkCaptcha(code){
    const {ctx} = this;
    code = code.toLowerCase()
    console.log("sessionCode",ctx.session.code) // ctx.session.code undefined?????????
    let sessCode = ctx.session.code? ctx.session.code.toLowerCase():null
    console.log("sesscode",sessCode)
    //验证
    if(code === sessCode){
      // 成功之后验证码作废
      ctx.session.code = null
    }
    return code === sessCode;
  }`

**Comment by atian25** [comment]
我试了下，在 home 里面是可以 print 出来的，自己检查下代码吧。

PS：你这不叫最小可复现了，一大堆干扰代码。另，你的秘钥都发出来了。

**Comment by ChunrunHan** [comment]
To https://github.com/ChunrunHan/eggjs-server.git
   8f4731e..683b395  dev -> dev
请切换到开发分支谢谢。

**Comment by atian25** [comment]
一样的，你不要弄那么多复杂的，直接 `npm init egg` 初始化一个干净的项目，然后在 a 路由里面写入，在 b 路由里面直接读取出来看看，我试了是没问题的。

**Comment by ChunrunHan** [comment]
但是我在sevice里获取session还是undefined

**Comment by ChunrunHan** [comment]
我格式化一下代码。。突然好使了。。。

**Comment by atian25** [comment]
`最小化可复现仓库`的意思就是：从最干净的仓库开始复现问题，它能帮你排除掉不必要的干扰，往往在这过程中你就已经可以定位到问题，并快速解决了。

**Comment by ChunrunHan** [comment]
我有个问题，egg解决跨域后，session 有冲突吗？

**Comment by atian25** [comment]
> 我有个问题，egg解决跨域后，session 有冲突吗？

什么叫解决跨域后的 session 冲突？你就可以 egg 视为是一个 Web 服务器，按 HTTP 标准该怎么样就怎么样的。

**Comment by ChunrunHan** [comment]
我现在安装完egg-cors 以后，session 就获取不到了。

**Comment by atian25** [comment]
跨域肯定是拿不到 cookie 的。

请提供最小可复现方式。

**Comment by ImPigerla** [comment]
有种可能是：页面开了CDN缓存
