### ISSUE TITLE
session丢失

### ISSUE THREAD

**Issue by lzq920** [eggjs/egg#3554]
## What happens?
nuxt+eggjs服务端渲染，正常情况页面可以获取到数据，在about使用F5页面刷新的时候，服务端session丢失

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `egg-init --type=simple bug` then upload to your GitHub

[https://github.com/lzq920/nuxt-eggjs-ssr-template.git](https://github.com/lzq920/nuxt-eggjs-ssr-template.git)

## How To Reproduce

**Steps to reproduce the behavior:**
1.点击hello word登录可以正常获取session并跳转到about页面，能正常返回session内容
2.在about页面F5刷新，服务端丢失session，出现401错误

**Expected behavior**
1.一旦用户登录，在session未过期之前，要一直保持登录

## Context
- **Node Version**:10.15.3
- **Egg Version**:2.20.0
- **Plugin Name**:egg
- **Plugin Version**:egg
- **Platform**:osx

**Comment by atian25** [comment]
刷新的时候是服务端请求，你的 axios 在服务端侧时，要把 cookie 带过去。

PS：想玩转 SSR，先把请求链路和 HTTP 这套搞明白。

```js
export default {
  asyncData({ params, req }) {
    if(process.server){
      Object.keys(req.headers).map((key)=>{
        axios.defaults.headers.common[key] = req.headers[key];
      });
    }
    return axios.get("http://127.0.0.1:7001/api/info", { withCredentials: true }).then(res => {
      return { info: res.data };
    });
  }
};
```
