### ISSUE TITLE
egg怎么添加 css,js gzip

### ISSUE THREAD

**Issue by lemondreamtobe** [eggjs/egg#3555]
根据文档中-中间件那一章节。gzip中间件貌似不起作用啊。请求还报err_content_ecodeing_failed

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend to use `egg-init --type=simple` to provide a mini project and upload to your github.

for now it will close due to lack of activity, feel free to reopen this issue if provided more information.
