### ISSUE TITLE
私有云部署报错

### ISSUE THREAD

**Issue by 13349253469** [eggjs/egg#3557]
+ npm stop

> egg-catalogbuy@1.0.0 stop /app/project/egg-catalogbuy
> egg-scripts stop --title=egg-catalogbuy

[egg-scripts] stopping egg application with --title=egg-catalogbuy
[egg-scripts] can't detect any running egg process
[egg-scripts] stopped
+ npm start

> egg-catalogbuy@1.0.0 start /app/project/egg-catalogbuy
> egg-scripts start --daemon --title=egg-catalogbuy

[egg-scripts] Starting egg application at /app/project/egg-catalogbuy
[egg-scripts] Run node /app/project/egg-catalogbuy/node_modules/egg-scripts/lib/start-cluster {"title":"egg-catalogbuy","baseDir":"/app/project/egg-catalogbuy","framework":"/app/project/egg-catalogbuy/node_modules/egg"} --title=egg-catalogbuy
[egg-scripts] Save log file to /home/appuser/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] tail -n 100 /home/appuser/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] Trace
[egg-scripts]     at Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:226:13)
[egg-scripts]     at Packet.readLengthCodedNumber (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:188:17)
[egg-scripts]     at Packet.readLengthCodedString (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:355:22)
[egg-scripts]     at new ResultSetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/resultset_header.js:71:52)
[egg-scripts]     at Query.resultsetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/query.js:104:16)
[egg-scripts]     at Query.execute (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/command.js:39:22)
[egg-scripts]     at Connection.handlePacket (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:449:32)
[egg-scripts]     at PacketParser.Connection.packetParser.p [as onPacket] (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:72:12)
[egg-scripts]     at PacketParser.executeStart (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packet_parser.js:75:16)
[egg-scripts]     at Socket.Connection.stream.on.data (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:79:25)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Socket.emit (events.js:211:7)
[egg-scripts]     at addChunk (_stream_readable.js:263:12)
[egg-scripts]     at readableAddChunk (_stream_readable.js:250:11)
[egg-scripts]     at Socket.Readable.push (_stream_readable.js:208:10)
[egg-scripts]     at TCP.onread (net.js:594:20)
[egg-scripts] 2019-03-19 23:38:45,527 ERROR 23733 nodejs.unhandledExceptionError: Should not reach here: undefined
[egg-scripts]     at Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:227:11)
[egg-scripts]     at Packet.readLengthCodedNumber (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:188:17)
[egg-scripts]     at Packet.readLengthCodedString (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:355:22)
[egg-scripts]     at new ResultSetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/resultset_header.js:71:52)
[egg-scripts]     at Query.resultsetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/query.js:104:16)
[egg-scripts]     at Query.execute (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/command.js:39:22)
[egg-scripts]     at Connection.handlePacket (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:449:32)
[egg-scripts]     at PacketParser.Connection.packetParser.p [as onPacket] (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:72:12)
[egg-scripts]     at PacketParser.executeStart (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packet_parser.js:75:16)
[egg-scripts]     at Socket.Connection.stream.on.data (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:79:25)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Socket.emit (events.js:211:7)
[egg-scripts]     at addChunk (_stream_readable.js:263:12)
[egg-scripts]     at readableAddChunk (_stream_readable.js:250:11)
[egg-scripts]     at Socket.Readable.push (_stream_readable.js:208:10)
[egg-scripts]     at TCP.onread (net.js:594:20)
[egg-scripts] name: "unhandledExceptionError"
[egg-scripts] pid: 23733
[egg-scripts] hostname: lhqcdz-uaes-ecom-nodejs0-ebaeef1e.novalocal

**Comment by atian25** [comment]
> at Packet.readLengthCodedNumberExt (/app/project/eggcatalogbuy/node_modules/mysql2/lib/packets/packet.js:226:13)

**Comment by 13349253469** [comment]
这是什么错误

**Comment by atian25** [comment]
不确定，根据这个关键词 google 看看。

另，请提供复现方式和你的一些经过分析对比的更具体的描述。

**Comment by 13349253469** [comment]
我在谷歌上搜了没有找到具体的问题

**Comment by 13349253469** [comment]
我在公有云上部署是没有问题的，都是通过jenkins自动部署的

**Comment by atian25** [comment]
> Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:226:13

翻翻这个库的源码，然后跟那边的维护者沟通看看吧。

会不会是你私有化部署对应的 mysql 后端协议对不上。

**Comment by 13349253469** [comment]
好的

**Comment by 13349253469** [comment]
这个问题还是没有搞定，和老外沟通好困难

**Comment by 13349253469** [comment]
google 了应该是协议的问题，但不知道怎么弄

**Comment by 13349253469** [comment]
https://github.com/sidorares/node-mysql2/issues/655 google到的

**Comment by 13349253469** [comment]
谁能帮忙一下

**Comment by Jamy325** [comment]
换个mysql库吧

**Comment by 13349253469** [comment]
> 换个mysql库吧
没法换，这个mysql是云提供的

**Comment by 13349253469** [comment]
> 换个mysql库吧
我现在找不到根本原因，是不是可以通过修改mysql的相关参数就可以解决这样的问题

**Comment by 13349253469** [comment]
byte1 0
byte1 0
byte1 0
len 0
byte1 22
byte1 17
byte1 9
len 9
byte1 6
len 6
byte1 1
byte1 49
len 49
byte1 undefined
Trace
at Packet.readLengthCodedNumberExt (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:227:13)
at Packet.readLengthCodedNumber (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:189:17)
at Packet.readLengthCodedString (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/packet.js:356:22)
at new ResultSetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packets/resultset_header.js:71:52)
at Query.resultsetHeader (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/query.js:104:16)
at Query.execute (/app/project/egg-catalogbuy/node_modules/mysql2/lib/commands/command.js:39:22)
at Connection.handlePacket (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:449:32)
at PacketParser.Connection.packetParser.p [as onPacket] (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:72:12)
at PacketParser.executeStart (/app/project/egg-catalogbuy/node_modules/mysql2/lib/packet_parser.js:75:16)
at Socket.Connection.stream.on.data (/app/project/egg-catalogbuy/node_modules/mysql2/lib/connection.js:79:25)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:594:20)

![image](https://user-images.githubusercontent.com/19915590/54900951-0ac0f680-4f10-11e9-8443-f2e9cc3560c1.png)
为什么这里出现了undefined

**Comment by atian25** [comment]
这个别人没法帮你，相当于用了一个 mysql2 的 client 端，这个库是支持标注的 mysql server 的，但你用的私有云的 mysql server 做了定制，使得 client 接入过程中报错了，这种情况下：

1. 如果是 mysql2 client sdk 的 BUG，那找到最小可复现的方式，提供给那边的开发者去修复，或者你直接 PR。
2. 如果是私有云 server 的 bug，那一样，反馈给他们去修正，要不就是看看能不能用他们推荐的 client。

**Comment by Jamy325** [comment]
> > 换个mysql库吧
> > 我现在找不到根本原因，是不是可以通过修改mysql的相关参数就可以解决这样的问题

不确定是不是mysql2的bug的话, 可以把mysql2换成mysql试试,如果 两个都报错的话 就是你的私有云提供的mysql server有问题了.

**Comment by 13349253469** [comment]
> > > 换个mysql库吧
> > > 我现在找不到根本原因，是不是可以通过修改mysql的相关参数就可以解决这样的问题
> 
> 不确定是不是mysql2的bug的话, 可以把mysql2换成mysql试试,如果 两个都报错的话 就是你的私有云提供的mysql server有问题了.

我用的egg-sequelize模块怎么切换到mysql，已经写了很多代码了

**Comment by 13349253469** [comment]
> 这个别人没法帮你，相当于用了一个 mysql2 的 client 端，这个库是支持标注的 mysql server 的，但你用的私有云的 mysql server 做了定制，使得 client 接入过程中报错了，这种情况下：
> 
> 1. 如果是 mysql2 client sdk 的 BUG，那找到最小可复现的方式，提供给那边的开发者去修复，或者你直接 PR。
> 2. 如果是私有云 server 的 bug，那一样，反馈给他们去修正，要不就是看看能不能用他们推荐的 client。

谢谢你的意见，我再想办法

**Comment by revanli** [comment]
@13349253469 大佬有解决这个问题么，我也遇到了

**Comment by liqigit** [comment]
@13349253469 大佬有解决这个问题么，我也遇到了这个问题。。阿里云上两个相同版本的rds，都是5.7版本，一个正常，另一个就会出这个问题

**Comment by liqigit** [comment]
> @13349253469 大佬有解决这个问题么，我也遇到了。。阿里云上两个相同版本的rds，都是5.7版本，一个正常，另一个就会出这个问题

将mysql2升级到1.7.0后解决了问题，大家可以参考下

**Comment by dotNetDR** [comment]
> > @13349253469 大佬有解决这个问题么，我也遇到了。。阿里云上两个相同版本的rds，都是5.7版本，一个正常，另一个就会出这个问题
> 
> 将mysql2升级到1.7.0后解决了问题，大家可以参考下

升级mysql2到当前版本2.1.0，就不报了。~感谢~

**Comment by amanda94** [comment]
我们迁移到阿里云的rds也碰到此问题，尝试调试一番发现跟数据库的connection 的 serverEncoding 变成了很奇怪的值 并不是我们配置的utf8，再向上溯源是 connection 建立之后发包解析返回值的时候得到的，正好同事搜到此issue 同样通过升级解决 感谢
反向查找mysql2 相关issue 应该是[这个](https://github.com/sidorares/node-mysql2/issues/989)
它项目的[changelog](https://github.com/sidorares/node-mysql2/blob/master/Changelog.md) 中显示1.7 修复了此问题

**Comment by wenghaoping** [comment]
我也碰到这个问题了，把mysql2升级到2.1.0，就不报了。
这个问题是真的瞎了。

**Comment by zlyyyy** [comment]
+1...找到DBA还被DBA diss
