### ISSUE TITLE
怎么配置egg支持bigint类型数据

### ISSUE THREAD

**Issue by meicx** [eggjs/egg#3561]
1、在写node服务时引用第三方api，api中返回的useid为int64位，怎么配置egg支持接收该userid？
2、由于该userid获取成功之后还要发给另外一个api接口做有效校验，javascript变量最大值不支持该类型，怎么将获取到的userid正确的发送给另一个接口呢？

**Comment by atian25** [comment]
跟 Egg 关系不大，对方返回的如果是 JSON，那你就自己用对应的支持 bigint 的库来解析，不要用 JSON.parse

**Comment by popomore** [comment]
用 string
