### ISSUE TITLE
路由，正则匹配问题

### ISSUE THREAD

**Issue by zfhslfgit** [eggjs/egg#3563]
## Background
Antd Pro 用的是browserHistory模式,另外一个路由需要不受中间件的影响，正则怎么匹配？

## Proposal
module.exports = app => {
  const { router, controller, middleware } = app;
  const authority = middleware.authority();
  
  router.get('/old-browser', controller.home.browser);
  router.get('\*', authority, controller.home.index);
};
'\*'这里的正则应该怎么写，就是不匹配/old-browser,因为/old-browser不想受 '*'里的 authority（中间件）影响
简单来说：路由怎么匹配/old-browser以外的路由？

**Comment by popomore** [comment]
你这样配置就可以了吧

**Comment by lengband** [comment]
@zfhslfgit hi，请问最后是怎么解决的呢
