### ISSUE TITLE
egg项目运行报错

### ISSUE THREAD

**Issue by fozero** [eggjs/egg#3565]
当使用npm start命令时报如下错误：

[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] Wait Start: 5...
[egg-scripts] tail -n 100 /root/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] 2019-03-24 11:43:38,574 ERROR 6203 [app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE
[egg-scripts] 2019-03-24 11:43:38,596 ERROR 6182 nodejs.AppWorkerDiedError: [master] app_worker#1:6203 died (code: 0, signal: null, suicide: false, state: dead), current workers: []
[egg-scripts]     at Master.onAppExit (/home/www/nodejs-lo/node_modules/egg-cluster/lib/master.js:398:21)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Master.emit (events.js:211:7)
[egg-scripts]     at Messenger.sendToMaster (/home/www/nodejs-lo/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/home/www/nodejs-lo/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.cluster.on (/home/www/nodejs-lo/node_modules/egg-cluster/lib/master.js:267:22)
[egg-scripts]     at emitThree (events.js:141:20)
[egg-scripts]     at EventEmitter.emit (events.js:217:7)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:185:13)
[egg-scripts]     at Object.onceWrapper (events.js:317:30)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 6182
[egg-scripts] hostname: VM_129_145_centos
[egg-scripts] 
[egg-scripts] 2019-03-24 11:43:38,596 ERROR 6182 [master] app_worker#1:6203 start fail, exiting with code:1
[egg-scripts] 2019-03-24 11:43:38,597 ERROR 6182 [master] exit with code:1
[egg-scripts] 2019-03-24 11:43:38,602 ERROR 6188 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2019-03-24 11:43:38,605 ERROR 6188 [agent_worker] exit with code:110
[egg-scripts] 
[egg-scripts] Start got error, see /root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.

本以为是端口被占用问题

但是使用npm stop停止时提示：

[egg-scripts] stopping egg application with --title=egg-server-nodejs-lo
[egg-scripts] can't detect any running egg process
[egg-scripts] stopped

通过ps查看node进程
[root@VM_129_145_centos nodejs-lo]# ps -ef|grep node
root      6874  4763  0  2020 pts/0    00:00:00 grep --color=auto node

不太明白上面啥意思，但是使用kill命令也没有用

莫名的问题出现，只是因为在项目里加了定时任务，其他代码没做什么改变

想请教下大家这个问题该如何解决？

非常感激！

**Comment by atian25** [comment]
>  [app_worker] server got error: bind EADDRINUSE null:7001, code: EADDRINUSE

端口被占用了。是其他应用占用的，因为默认的 `npm stop` 是有个 `--title=egg-server-nodejs-lo` 的参数，所以自然不会检测到。可以用 `lsof -i:7001` 检测是什么在占用。如果还不行，可以去了解下 Linux 的一些操作。

**Comment by fozero** [comment]
@atian25 
我线上项目可以正常运行，这说明端口应该是被占用了，但是使用lsof -i:7001查看的时候什么也没有
[root@VM_129_145_centos nodejs-lo]# lsof -i:7001
[root@VM_129_145_centos nodejs-lo]# 

也试过这个命令查看netstat -tln | grep 7001 ，没有看到任何pid 
[root@VM_129_145_centos nodejs-lo]# netstat -tln | grep 7001
tcp6       0      0 :::7001                 :::*                    LISTEN

**Comment by atian25** [comment]
端口占用，这个就跟 Egg 本身没什么关系了，可以自己排查下吧

**Comment by fozero** [comment]
端口占用还是当前egg项目，但是使用npm stop并不能关闭停止运行
使用netstat -tlnp查看全部进程，其他都有pid，但唯独7001端口没有，很奇怪 ，没有pid的话也就无法使用kill清理到进程 了 。
[root@VM_129_145_centos nodejs-lo]# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      12218/./redis-serve 
tcp        0      0 127.0.0.1:35854         0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd           
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1831/java           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1747/nginx: master  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      704/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      1747/nginx: master  
tcp        0      0 127.0.0.1:8005          0.0.0.0:*               LISTEN      1831/java           
tcp        0      0 0.0.0.0:8009            0.0.0.0:*               LISTEN      1831/java           
tcp6       0      0 :::3306                 :::*                    LISTEN      14014/mysqld        
tcp6       0      0 :::6379                 :::*                    LISTEN      12218/./redis-serve 
tcp6       0      0 :::111                  :::*                    LISTEN      6694/rpcbind        
tcp6       0      0 :::22                   :::*                    LISTEN      704/sshd            
tcp6       0      0 :::7001                 :::*                    LISTEN      -

**Comment by popomore** [comment]
grep 下 node 进程就好了

**Comment by fozero** [comment]
@popomore 貌似没有用，我已经试过了┑(￣Д ￣)┍
[root@VM_129_145_centos nodejs-lo]#  ps -ef|grep node
root      3112 32380  0  2020 pts/1    00:00:00 grep --color=auto node

**Comment by geekdada** [comment]
试试 `sudo lsof -i:7001`，可能被其他 user 的进程占用了。

**Comment by fozero** [comment]
@geekdada 好像是和防火墙有关系，不太确定

**Comment by peterzhai** [comment]
我也遇到一样的问题~lsof -i:7001 找不到进程号

**Comment by nanshenjiang** [comment]
@fozero 你好，我也遇到同样的问题，请问你解决了吗

**Comment by nanshenjiang** [comment]
> @fozero 你好，我也遇到同样的问题，请问你解决了吗

解决了，关闭服务器防火墙就可以了

**Comment by yudioll** [comment]
npm stop 命令指定 title名 要在前面加上egg-server
