### ISSUE TITLE
egg-logrotator 定时切割日志

### ISSUE THREAD

**Issue by SimpleJoeie** [eggjs/egg#3566]
问题：
高级自定义的log目录做日志切割时，发现日志文件会形成一个比较大的文件，按天分割并不生效。

## demo仓库
> https://github.com/SimpleJoeie/egg-logger-demo.git

****
1. 高级自定义日志，当日志写入对应目录文件的时候，凌晨定时任务切割不生效
****
1. 按照官方demo方式
https://github.com/eggjs/egg-logrotator
https://github.com/eggjs/egg-logger
发现一直读写access.log，不会发生切割
2. 查看egg-logrotator源码，尝试把自定义目录rotateLogDirs配置对应目录结构，把new logger实例挂载到app.loggers上，发现日志rename成功，但是一条日志却同时向不同的日志文件里写入
3. 尝试接管egg-logrotator里面的app.messenger.on('log-reload'），手动reload日志，发现有的自定义目录下生效，有的依旧有问题。
## Context
- **Node Version v8.12.0**:
- **Egg Version ** 2.12.0:
- **Plugin Name** egg-logrotator:
- **Plugin Version** 3.0.4:
- **Platform**:

**Comment by atian25** [comment]
https://github.com/atian25/egg-showcase/pull/14
