### ISSUE TITLE
Webstorm: Attach to Node.js/Chrome 的调试方法修改代码后无法自动重连

### ISSUE THREAD

**Issue by Jiazhi-Wong** [eggjs/egg#3570]
## 复现步骤

1. 在docker容器里用`egg-bin debug`跑egg-init的simple项目

启动时的输出：
![启动时的输出](https://user-images.githubusercontent.com/19643491/54971462-78792b00-4fc1-11e9-8e6d-f65dd29c1a00.png)

2. 配置Webstorm: Attach to Node.js/Chrome调试方法

配置，开启了 auto reconnect：
![配置](https://user-images.githubusercontent.com/19643491/54975215-54bde100-4fd1-11e9-92cd-8a4962bc5fe6.jpg)

3. 启动webstrom的debug，打断点，访问页面，断点可进入webstorm

启动debug后，命令行打印：
![启动debug后，命令行打印](https://user-images.githubusercontent.com/19643491/54975251-76b76380-4fd1-11e9-9c87-23c79648256d.jpg)

断点可进入：
![断点可进入](https://user-images.githubusercontent.com/19643491/54975262-820a8f00-4fd1-11e9-8a8a-ab5cb3073990.jpg)

4. 在webstorm内修改代码，保存文件，再访问页面，断点就进不来webstorm了

代码修改后，命令行打印：
![4](https://user-images.githubusercontent.com/19643491/54975336-bc742c00-4fd1-11e9-90eb-015d94397db1.jpg)

访问页面，断点不可进入：
![断点不可进入](https://user-images.githubusercontent.com/19643491/54975340-bed68600-4fd1-11e9-8d47-dd0b0bc6051e.jpg)

5. 如果stop掉webstorm的debug，重新启动debug，断点又可以进入。但是我想要的效果是自动重连，不需要手动再重启。

## 相关环境信息
- **操作系统**：MacOs
- **Node 版本**：8.11.1
- **Egg 版本**：2.20.2
- **WebStorm 版本**：2018.3.5

**Comment by atian25** [comment]
9999 是我们启动的一个代理，源码在 https://github.com/eggjs/egg-bin/blob/master/lib/cmd/debug.js#L69 ，基本原理就是监听 worker 重启事件，然后代理到新的 debug port 上（9229 自增）

不确定 WebStorm 的这个 auto reconnect 机制是怎么样的，需要你自己研究下。也可以试试配为 9229 看看 WebStorm 会不会自动处理自增。
