### ISSUE TITLE
egg-socket.io 问题

### ISSUE THREAD

**Issue by fabin5** [eggjs/egg#3571]
想要配置 socket.io-redis ，但是redis的地址是从发现服务获取的，这时候没有类似createInstanceAsync 这样的方法让我在启动的时候配置。

**Comment by fabin5** [comment]
或者能不能直接使用 redis插件，再内部处理。 外部不要再处理。

**Comment by fabin5** [comment]
这个问题什么时候看一下啊？ @thonatos @ngot

**Comment by ngot** [comment]
目前有个变通的办法来实现：

app.js

```js
const redis = require("socket.io-redis");

module.exports = app => {
  app.beforeStart(async () => {
    const redisConfig = await fetchRedisConfig();
    app.io.adapter(redis(redisConfig));
  });
};
```

要注意的是， io config 里面就不要再配置 Redis 了

**Comment by ngot** [comment]
之前研究过， egg-redis 使用的是 io-redis 与 socket.io-redis 不是100%的兼容，无法直接使用。不知道现在有没有改进。
