### ISSUE TITLE
egg-mongoose支持事务了吗

### ISSUE THREAD

**Issue by lijicheng123** [eggjs/egg#3572]
## Background
mongodb4.0后支持事务了，我想使用一下，但是无从用起
## Proposal
我希望能在service里边使用上事务

## Additional context
希望能给个小demo，这样就能快速使用了，谢谢

**Comment by popomore** [comment]
如果 mongoose 支持了就能支持

**Comment by lijicheng123** [comment]
> 如果 mongoose 支持了就能支持

谢谢，卸载了mongoose，安装最新版就可以了，但是需要在复制集上才行，准备做复制集

**Comment by albertyou2** [comment]
@lijicheng123 你好，能能否给一个 EGG-MONGOOSE使用事务的例子？找了好久都没找到，谢谢！

**Comment by li305263** [comment]
> > 如果 mongoose 支持了就能支持
> 
> 谢谢，卸载了mongoose，安装最新版就可以了，但是需要在复制集上才行，准备做复制集

你好. 怎么在现有的数据库上配置副本集呢?..研究了一下午了没搞定

**Comment by lijicheng123** [comment]
> @lijicheng123 你好，能能否给一个 EGG-MONGOOSE使用事务的例子？找了好久都没找到，谢谢！

代码好像是有的，但是也没跑过，之前因为复制集不好安装就暂停了

**Comment by lijicheng123** [comment]
> > > 如果 mongoose 支持了就能支持
> > 
> > 
> > 谢谢，卸载了mongoose，安装最新版就可以了，但是需要在复制集上才行，准备做复制集
> 
> 你好. 怎么在现有的数据库上配置副本集呢?..研究了一下午了没搞定

我也没空搞复制集

**Comment by albertyou2** [comment]
搞定了一个例子，资料太少了。其实复制集很简单（至少搞个Demo比较简单。。。）

**Comment by atian25** [comment]
欢迎分享对应的 demo 仓库或文档给后来人

**Comment by albertyou2** [comment]
1 . 配置方法 （MAC 测试可行）

**Comment by albertyou2** [comment]
这几天整理了一个egg的例子希望更多的高手能够丰富这个例子，因为这个例子仅仅是能跑，可能有很多坑。

async testTransaction() {

    const { ctx, app, config } = this;
    const tool = new Tool();
    const statusCode = new StatusCode();
    const session = await app.mongoose.startSession({
        readPreference: { mode: 'primary' },
    });

    try{
      // 启动 事务
      await session.startTransaction({
         readConcern: { level: 'snapshot' },
         writeConcern: { w: 'majority' },
      });

     let m = app.model.Test;

      //await m.save([{name:'1',content :'c1'}],{session:session});  
      await app.model.Test.create([{name:'2',content :'c2'}],{session:session}); 
      await app.model.Test.create([{name:'3',content :'c3'}],{session:session});  

      //let a = un.abc; //excetion
      await session.commitTransaction(); // 提交事务
     
      ctx.body = '1111';
      return;

    } catch (err) {
      console.log(err)
      await session.abortTransaction(); // 回滚，注意如果这里commit成功了， 在回滚会报错！！！
      await session.endSession(); // 结束 不知道干什么用
      ctx.body = '2222';
      return;
    } 
  }

**Comment by albertyou2** [comment]
另外盼赐教，mongo的事务启动是否已经相当于枷锁了，不需要自己额外在加分布式锁？

**Comment by rainyulei** [comment]
//let a = un.abc; //excetion
  await session.commitTransaction(); // 提交事务 
// 这里再加一句
session.endSession();

**Comment by frankgo81** [comment]
> 另外盼赐教，mongo的事务启动是否已经相当于枷锁了，不需要自己额外在加分布式锁？

这个锁是数据库的原子锁； 具体business 逻辑需要你添加redis lock； 两者不是一回事儿。

**Comment by frankgo81** [comment]
> 这几天整理了一个egg的例子希望更多的高手能够丰富这个例子，因为这个例子仅仅是能跑，可能有很多坑。
> 
> async testTransaction() {
> 
> ```
> const { ctx, app, config } = this;
> const tool = new Tool();
> const statusCode = new StatusCode();
> const session = await app.mongoose.startSession({
>     readPreference: { mode: 'primary' },
> });
> 
> try{
>   // 启动 事务
>   await session.startTransaction({
>      readConcern: { level: 'snapshot' },
>      writeConcern: { w: 'majority' },
>   });
> 
>  let m = app.model.Test;
> 
>   //await m.save([{name:'1',content :'c1'}],{session:session});  
>   await app.model.Test.create([{name:'2',content :'c2'}],{session:session}); 
>   await app.model.Test.create([{name:'3',content :'c3'}],{session:session});  
> 
>   //let a = un.abc; //excetion
>   await session.commitTransaction(); // 提交事务
>  
>   ctx.body = '1111';
>   return;
> 
> } catch (err) {
>   console.log(err)
>   await session.abortTransaction(); // 回滚，注意如果这里commit成功了， 在回滚会报错！！！
>   await session.endSession(); // 结束 不知道干什么用
>   ctx.body = '2222';
>   return;
> } 
> ```
> 
> }

     
    {
try{  await session.commitTransaction();
      session.endSession();
    } catch (err) {
      await session.abortTransaction();
      throw err;
}

**Comment by frankgo81** [comment]
或者使用
https://juejin.cn/post/6844903919915630605
egg-tx
