### ISSUE TITLE
egg-ts-helper不能配置彻底忽略项目中的指定目录

### ISSUE THREAD

**Issue by StephenSeraph** [eggjs/egg#3573]
## What happens?

我写了一个TS的egg服务，用于管理其他的egg项目。
被管理的各个项目放在管理服务的主目录下的`data`文件夹下，每次管理服务编译或调试时都会清理掉`data`文件夹下各项目中已经编译好的JS文件。

data文件夹位于项目目录里面，被认为了是该项目的一部分，而其中的文件结构又恰恰是满足Egg项目生成的文件特征的，于是被[egg-ts-helper]管理起来了。
这个流程本身是没有问题的，但却不是我所期望的。
我是想把data文件夹就作为一个普通的数据存放目录，不要被框架干涉，但是目前没找到相关配置项。

当前我的处理办法是，在`data`目录下再建一个名为`node_modules`的目录，其他被管理的项目放在`data/node_modules`目录下。原因是我发现目前[egg-ts-helper]各个函数逻辑里会忽略掉`node_modules`目录，所以借了这个壳，暂时先这么用着。但总觉得别扭，所以特来询问一下有没有更官方一点的做法。

## 相关环境信息
- **操作系统**：Ubuntu18.04
- **Node 版本**：10.15.3
- **Egg 版本**：2.20.2

**Comment by whxaxes** [comment]
egg-ts-helper 清理 js 只会清理有同名 ts 文件 + 使用 ts-node 的情况下才会清理，目前这个不支持配置，你这种场景有点特殊，把这些项目当成 npm 包弄到 node_modules 下我觉得问题也不大

**Comment by StephenSeraph** [comment]
@whxaxes 嗯，谢谢！那就先这样用吧，回头再加个这个路径的配置项，部署时除了可以用这个默认的，也可以自定义目录。
不过想到另一个问题，比如，我在项目的某个目录下存放几万张图片，虽然我们不处理图片，但在启动时总归也是会扫描一遍的吧，会不会有点浪费呢……
就先这样吧，关掉吧，再次感谢！

**Comment by whxaxes** [comment]
@StephenSeraph  开发期为啥会有几万张图片，这个情况本身就不太合理了额
