### ISSUE TITLE
egg-init 或npm init egg在windows10环境下安装都会卡住，无法执行安装

### ISSUE THREAD

**Issue by sys234** [eggjs/egg#3574]
- [ ] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**: v6.7.0
- **node version**: v11.10.0 x64
- **egg version**: 2.20.2
- **plugin name**:
- **plugin version**:
- **platform**: Microsoft Windows [Version 10.0.16299.19]
- **git repo**: https://example.com

### Reproduction
附加环境 : 

Cmder : 1.3.6.678

egg-init Version : 1.6.1

执行命令是否有管理员权限 ：是

是否启用SS代理 : 是(但非全局)

GitHub/npmjs.com是否可以正常访问 : 是

npm config 配置过:
```
registry=https://registry.npm.taobao.org/
```
`egg-init`已经默认全局安装
执行`egg-init`或`npm init egg` 会卡住，无法正常安装。另外在Window7下结果也是一样卡住

```
λ egg-init
[egg-init] use registry: https://registry.npmjs.org
[egg-init] target dir is F:\server1
[egg-init] fetching npm info of egg-init-config
? Please select a boilerplate type sequelize - egg app with sequelize
[egg-init] use boilerplate: sequelize(egg-boilerplate-sequelize)
[egg-init] fetching npm info of egg-boilerplate-sequelize
```

**Comment by CoderKwong** [comment]
I have the same problem
egg-init Version: 1.6.1
platform: windows 10

**Comment by CoderKwong** [comment]
I solved this problem.Dont use `egg-init  {your directory}`.
Use this command `egg-init --type {type} {your directory}`
