### ISSUE TITLE
文档：教程/sequelize --> homebrew 启动mysql的文档有误

### ISSUE THREAD

**Issue by Le-Fu** [eggjs/egg#3575]
- [x] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**:
- **node version**:
- **egg version**: 2.20.2
- **plugin name**:
- **plugin version**:
- **platform**:
- **git repo**: https://eggjs.org/zh-cn/tutorials/sequelize.html

## 准备工作
brew **service** start mysql
应该为
brew **services** start mysql

**Comment by atian25** [comment]
thanks for reports, next time how about just raise a PR?

will fix at https://github.com/eggjs/egg/pull/3588
