### ISSUE TITLE
我在win10上使用定时让每个works都打印，但是似乎看上去只运行了一个进程

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3577]
"dev": "egg-bin dev --workers=7",

const Subscription = require('egg').Subscription;

class UpdateCache extends Subscription {
  // 通过 schedule 属性来设置定时任务的执行间隔等配置
  static get schedule() {
    return {
      interval: '5000', // 1 分钟间隔
      type: 'all', // 指定所有的 worker 都需要执行
    };
  }

  // subscribe 是真正定时任务执行时被运行的函数
  async subscribe() {
//这里有问题
    console.log(process.pid);
  }
}

module.exports = UpdateCache;

看上去就打印出了一个进程的id，但是看上去7个进程都起来了，不知道在干什么

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by huyu1** [comment]
> 提供最小可复现仓库
什么意思？可以具体说说吗，没有理解，这现象是正常的吗

**Comment by huyu1** [comment]
我好像什么也没有做，按官网快速生成项目，加了一个上述我写的定时器

**Comment by atian25** [comment]
对问题补充即可，不需要重开 https://github.com/eggjs/egg/issues/3578
