### ISSUE TITLE
egg做项目似乎有效的work只有一个

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3578]
- [ ] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**:
- **node version**:
- **egg version**: 2.20.2
- **plugin name**:
- **plugin version**:
- **platform**:
- **git repo**: https://github.com/huyu1/egg-work

### Reproduction
使用egg-init egg-example --type=simple快速构建项目
在package.json修改"dev": "egg-bin dev --workers=7",
设置all的定时器，schedule/consoleDate.js,
理论上应该所有的work都打印这个，但是似乎就一个work打印，其他work处于不工作状态
只打印出了一个进程pid

**Comment by atian25** [comment]
不需要重新开一个的，下次直接在原来 issue 回复即可。

看了下，目前 `egg-bin dev` 不支持 `--workers`，你可以用 `-c=7`。

具体参见源码： https://github.com/eggjs/egg-bin/blob/master/lib/cmd/dev.js

我等会加个 workers 的支持。

**Comment by huyu1** [comment]
但是不加works=7的时候，还是只打印出了一个work的pid，我的电脑是4核

**Comment by atian25** [comment]
dev 是本地开发，只会默认开一个 worker。正式使用你应该用 egg-scripts，请阅读相关部署文档。

**Comment by huyu1** [comment]
好的，谢谢，我明白了

**Comment by huyu1** [comment]
我想问一下，启动自定义的app.js和多进程的app.js是同一个吗，看上去是同一个，但是这会不会有点怪异

**Comment by atian25** [comment]
没看懂

**Comment by huyu1** [comment]
在教程中，框架提供了统一的入口文件（app.js）进行启动过程自定义，这个文件返回一个 Boot 类，我们可以通过定义 Boot 类中的生命周期方法来执行启动应用过程中的初始化工作。。。。。然后多进程中的work的入口也是app.js，都在跟目录下，是同一个吗

**Comment by atian25** [comment]
当然是同一个啦，每一个进程都有自己的生命周期。

**Comment by huyu1** [comment]
我在学习egg-Sequelize的时候创建完.sequelizerc.js之后:::
:'use strict';

const path = require('path');

module.exports = {
  config: path.join(__dirname, 'database/config.json'),
  'migrations-path': path.join(__dirname, 'database/migrations'),
  'seeders-path': path.join(__dirname, 'database/seeders'),
  'models-path': path.join(__dirname, 'app/model'),
};

在执行npx sequelize init:config的时候，报错：
Unable to resolve sequelize package in F:\HBuilderProjects\cloubox_07\sequelize-project是怎么回事额

**Comment by atian25** [comment]
不是写的很清楚么，没安装 sequelize 吧

**Comment by huyu1** [comment]
装了egg-sequelize，我跟着教程一步一步走，linux过了，win10下报错Unable to resolve sequelize package in F:\HBuilderProjects\cloubox_07\sequelize-project

**Comment by huyu1** [comment]
安装了cnpm install sequelize过了，egg-sequelize和sequelize不是一个东西吗，为什么linux下只安装sequelize也不会报错

**Comment by atian25** [comment]
> egg-sequelize和sequelize不是一个东西吗

当然不是同一个类库啦。。。你是不是需要先去熟悉下 Node 和 NPM ？

那可能是因为扁平化安装后，根目录就有了子依赖。

**Comment by huyu1** [comment]
好吧，我以为egg-sequelize是你们把sequelize封装的版本

**Comment by atian25** [comment]
跟主题不是一个问题了，如果你 sequelize 这个按教程走不通，那就重新发个 issue，提供最小化可复现仓库，以及对应的复现操作。
