### ISSUE TITLE
egg-mock 创建app异常

### ISSUE THREAD

**Issue by XueRainey** [eggjs/egg#3582]
## What happens?
test调用
```
require('egg-mock/bootstrap');
```
app.js如下
```
'use strict';

class AppBootHook {
  constructor(app) {
    this.app = app;
  }

  async serverDidReady() {
    this.app.server.on('upgrade');
  }
}

module.exports = AppBootHook;

```
在serverDidReady时，app未正常包含server对象

## Mini Showcase Repository(REQUIRED)

https://github.com/XueRainey/egg-mock-bug

## How To Reproduce

**Steps to reproduce the behavior:**
1.npm i
2.npm run test-local

## Context
- **Node Version**: v11.9.0
- **Egg Version**:2.15.1
- **Platform**:MacOS

**Comment by popomore** [comment]
我不记得 app 有这个，是哪个文档看到的？

**Comment by atian25** [comment]
@popomore 有的，https://github.com/eggjs/egg/blob/master/lib/application.js#L160

**Comment by atian25** [comment]
看了下，egg-mock 没有创建 server，只有在 httpRequest 调用的时候，才延迟创建

**Comment by atian25** [comment]
@XueRainey 你可以先在构造函数里面监听 `app.on('server', server => {})`;

**Comment by XueRainey** [comment]
@atian25 好的，感谢

**Comment by atian25** [comment]
@XueRainey 3.22.2

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```
