### ISSUE TITLE
请问一下怎么把一个egg项目打成一个包发布

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3583]
## 背景
用egg，但是不想暴露源代码，需要用什么工具解决

> 描述你希望解决的问题的现状，附上相关的 issue 地址

## 思路

> 描述大概的解决思路，可以包含 API 设计和伪代码等

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by atian25** [comment]
参考对应的 Node 社区方案摸索下吧，如 pkg 啥的。

只要源码是放在别人那里，就没太多安全可言，总是可以破出来的。尽可能考虑云化吧。

**Comment by huyu1** [comment]
但是没办法，一般我们都是内网下的，云连不到额

**Comment by popomore** [comment]
pkg

**Comment by GitHubWuYi** [comment]
> pkg

用PKG根本打包不了，Egg的结构太恶心了

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/3752
