### ISSUE TITLE
development无法指定监视的目录的子目录

### ISSUE THREAD

**Issue by leon776** [eggjs/egg#3584]
egg-development/agent.js的第64行：
   
if (isAssetsDir(info.path) || info.isDirectory) {
      return;
}

windows下子目录的文件修改会造成info.isDirectory为true，从而无法重启

**Comment by atian25** [comment]
修改目录是小概率事件吧，自己重启下就好了。

**Comment by atian25** [comment]
feel free to reopen this issue if any more information.
