### ISSUE TITLE
Sequelize的问题，使用的pgsql，必须表格名字结尾带s才不会报错

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3585]
- [ ] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**:
- **node version**:
- **egg version**: 2.20.2
- **plugin name**:
- **plugin version**:
- **platform**:
- **git repo**: https://github.com/huyu1/egg-work

### Reproduction
1.cnpm install --save egg-sequelize pg
2.生成数据库   npx sequelize db:migrate
3.运行
结果，以s为结尾的表格比如users正常查询，post直接报错，报错说找不到posts，是什么回事，还有，所有数据库必须带created_at属性，如果外来数据库没有这种属性，我们应该怎么查询

**Comment by huyu1** [comment]
算了，大不了我直接query吧。。。

**Comment by popomore** [comment]
你用 sequelize 得先看下他的文档
