### ISSUE TITLE
ts项目测试导入模块不支持ts的@paths

### ISSUE THREAD

**Issue by maweimaweima** [eggjs/egg#3592]
`
import { trimChapterName } from '@schedule_core/geChapters';
...
`
首先在开发模式中该功能正常，但在测试命令运行后出现如下错误
```
Error: Cannot find module '@schedule_core/geChapters'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
如果不使用该快捷引入则正常运行，是否可以支持ts @导入模块，感谢回复

- **Node Version**: v10.15.1
- **Egg Version**:  2.14.2
- **EggScripts Version**:  2.11.0
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: MacBook Pro 10.11.6 (15G21013)

**Comment by whxaxes** [comment]
https://eggjs.org/zh-cn/tutorials/typescript.html#%E5%9C%A8-tsconfigjson-%E4%B8%AD%E9%85%8D%E7%BD%AE%E4%BA%86-paths-%E6%97%A0%E6%95%88

**Comment by whxaxes** [comment]
请自行引入 `tsconfig-paths/register`

**Comment by maweimaweima** [comment]
我说的是单元测试ts导入使用@paths功能，该问题目前已解决。
解决方案是 在测试单元模块顶部引入 `import 'tsconfig-paths/register';`。
很奇怪加入引入tsconfig-paths/register之后，竟然触发 config/plugin.ts文件的加载。
_（单元测试中去掉tsconfig-paths/register是不加载config/plugin.ts文件的，所以应该是不支持@paths的元凶）_

**Comment by maweimaweima** [comment]
感谢 @whxaxes的提示，做一下尝试后发现这个问题
