### ISSUE TITLE
egg-sequelize +mssql 总是提示空的用户名登陆失败,如 用户 '' 登录失败

### ISSUE THREAD

**Issue by yyguan** [eggjs/egg#3595]
查阅了egg的官方教程,其中介绍的全部都是使用mysql数据库进行开发,由于我们之前用的是sqlserver,所以现在想使用egg-sequelize  + mssql进行项目开发,但在前面的尝试过程中始终报错。不能连接到数据库,并始终提示如下错误，_用户 '' 登录失败。_配置文件中已配置用户名和密码,为什么会提示空用户名呢?

config/plugin.js

sequelize:{
    enable: true,
    package: 'egg-sequelize',
  }

config/config.default.js

config.sequelize= {
    dialect: 'mssql',
    database: 'db_Name',
    host: '192.168.1.1',
    port: '1433',
    username: 'sa',
    password: 'aaa'
  }

## 相关环境信息
- **操作系统**：win10 
- **Node 版本**：11.13.0
- **Egg 版本**：2.20.2

**Comment by atian25** [comment]
https://eggjs.app/zh-cn/faq.html#为什么我的配置不生效

**Comment by yyguan** [comment]
> [https://eggjs.app/zh-cn/faq.html#为什么我的配置不生效](https://eggjs.app/zh-cn/faq.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88)

请教下 如果在Egg-sequelize中使用mssql的话 应该如何配置?我上面列出来的代码应该是有遗漏的。

**Comment by atian25** [comment]
可以看 sequelize  文档 https://github.com/sequelize/sequelize

**Comment by duncup** [comment]
@yyguan 目前这个问题还存在么？

**Comment by lesinliu** [comment]
是不是database文件夹下面的config.json文件忘记配置用户名密码了？

**Comment by yyguan** [comment]
> @yyguan 目前这个问题还存在么？

后来没有使用egg了 换了一个框架

**Comment by TomorrowCat** [comment]
egg-sequelize和sequelize版本不一致的情况， 会出现这种问题，因为sequelize配置文件处理格式有变化，导致传入tedious的配置有问题。安装最新的egg-sequelize和sequelize就好了
