### ISSUE TITLE
egg-multipart

### ISSUE THREAD

**Issue by southorange1228** [eggjs/egg#3596]
使用egg内置的egg-multipart进行上传文件接收，主要问题有这几个，使用file模式，上传的文件默认存储位置是哪里？如何对其进行修改（比如修改文件名，修改上传位置），因为官网上面都是上传oss，所以不太清楚。并且file模式下面会有一个定时任务，每天4点半删除文件，是指删除上传的文件，那么可以理解为假如不上传OSS，那么上传的文件将会被删除吗？这个定时任务是可以关闭的吗？

![image](https://user-images.githubusercontent.com/32590310/55716789-720b9a00-5a2a-11e9-91b0-217d098e12d8.png)

**Comment by fengmk2** [comment]
你拿到文件需要自己保存。定时任务是确保临时文件都被自动清理

**Comment by southorange1228** [comment]
> 你拿到文件需要自己保存。定时任务是确保临时文件都被自动清理

好的
