### ISSUE TITLE
中文名图片打不开

### ISSUE THREAD

**Issue by cassiewang01** [eggjs/egg#3597]
你好，我想问下，上传的中文名的图片，在预览的打不开，是需要什么配置么？
正常打开图片是没问题的，但在egg服务下打开就无返回，报类似如下错误：
![image](https://user-images.githubusercontent.com/22312427/55722420-d6cdf100-5a38-11e9-8463-9d4c985d5253.png)

**Comment by chengnuo** [comment]
用Unicode编码转换。

**Comment by cassiewang01** [comment]
自己搭建的egg服务器 ，上传test-measure zip包并解压，解压后的目录如下：
![image](https://user-images.githubusercontent.com/22312427/55768355-2a7b2180-5aaf-11e9-8a21-a8c9c5053002.png)


在node服务下http://ip:port/ 打开test-measure 下的 index.html，index.html文件中引入含中文名图片： 404-2-1-3-测试-2测试-1.png    打不开。。

**Comment by atian25** [comment]
学习下 HTTP URL 的知识吧

**Comment by cassiewang01** [comment]
@atian25 打开的时候不是用的中文，是转义后的

**Comment by atian25** [comment]
按 https://github.com/eggjs/egg/issues/3310 这个说明，通过 `npm init egg --type=simple` 来初始化并上传到你的 GitHub 仓库。然后发地址我们看看。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
