### ISSUE TITLE
English documentation ?

### ISSUE THREAD

**Issue by Nihaux** [eggjs/egg#360]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

Would be great to have english docs, or did i missed a link ?

**Comment by atian25** [comment]
hey, all the source && plugin README is english-first.

and the guide document at eggjs.org is still working.

now you can take a look at https://github.com/eggjs/egg/tree/master/docs/source/en

cc @mattma

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/363

**Comment by mattma** [comment]
Cool. I will try to find some time to translate documentation.

**Comment by dead-horse** [comment]
close this issue now, you can trace #363 to know the progress of translation.
