### ISSUE TITLE
egg-logger 可以将日志记录到logstash吗

### ISSUE THREAD

**Issue by 13349253469** [eggjs/egg#3602]

**Comment by atian25** [comment]
可以写个插件来提供对应的 Transport 即可。

https://eggjs.org/zh-cn/core/logger.html#%E9%AB%98%E7%BA%A7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%97%A5%E5%BF%97

**Comment by 13349253469** [comment]
好的

**Comment by atian25** [comment]
或者安装个对应的 agent 直接采集文件即可。

**Comment by 13349253469** [comment]
> 或者安装个对应的 agent 直接采集文件即可。

安装个对应的 agent 这个我不怎么明白，有相关文档吗
