### ISSUE TITLE
如何在http server启动之前获取到server实例

### ISSUE THREAD

**Issue by skyitachi** [eggjs/egg#3605]
## 如何在http server启动之前获取到server实例

egg 如何在http server启动之前获取到这个server的实例，有一个场景是websocket的server需要attach到httpserver上，但是由于前面有nginx，所以希望在websocket整个初始化完成之后，再接受新的连接，如果httpserver 先启动的话，那么有可能有的连接已经进来了

**Comment by skyitachi** [comment]
我看到了`serverDidReady`之后app.server才会有实例，是否应该添加`serverBeforeReady`呢

**Comment by atian25** [comment]
把初始化的地方放到 `willReady` 里面，这样的话，应用的 HTTP 服务会等待它。
然后 Nginx 那边搞个 check status 来检测是否放入流量。

**Comment by skyitachi** [comment]
恩，这样也是可以的，但是感觉有点繁琐，server应该可以尽早暴露的

**Comment by atian25** [comment]
你可以自己监听 `app.on('server', server => {})` 来提早拿到示例，但你还是需要上述钩子来阻塞放流量。
