### ISSUE TITLE
使用alinode就启动报错了，设置成false就没有这个问题

### ISSUE THREAD

**Issue by 13349253469** [eggjs/egg#3608]
+ npm start

> egg-jiucaiyun@1.0.0 start /app/project/egg-jiucaiyun
> egg-scripts start --daemon --title=egg-server-egg-jiucaiyun

[egg-scripts] Starting egg application at /app/project/egg-jiucaiyun
[egg-scripts] Run node /app/project/egg-jiucaiyun/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-egg-jiucaiyun","baseDir":"/app/project/egg-jiucaiyun","framework":"/app/project/egg-jiucaiyun/node_modules/egg"} --title=egg-server-egg-jiucaiyun
[egg-scripts] Save log file to /home/admin/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] tail -n 100 /home/admin/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] module.js:602
[egg-scripts]     throw err;
[egg-scripts]     ^
[egg-scripts] 
[egg-scripts] Error: Cannot find module '/app/project/egg-jiucaiyun/node_modules/agentx/lib/orders/.svn'
[egg-scripts]     at Function.Module._resolveFilename (module.js:600:15)
[egg-scripts]     at Function.Module._load (module.js:527:25)
[egg-scripts]     at Module.require (module.js:649:17)
[egg-scripts]     at require (internal/module.js:11:18)
[egg-scripts]     at /app/project/egg-jiucaiyun/node_modules/agentx/lib/agent.js:355:17
[egg-scripts]     at Array.forEach (<anonymous>)
[egg-scripts]     at Agent.handleMonitor (/app/project/egg-jiucaiyun/node_modules/agentx/lib/agent.js:354:10)
[egg-scripts]     at new Agent (/app/project/egg-jiucaiyun/node_modules/agentx/lib/agent.js:47:8)
[egg-scripts]     at module.exports.agent (/app/project/egg-jiucaiyun/node_modules/egg-alinode/agent.js:24:3)
[egg-scripts]     at Hook.configDidLoad (/app/project/egg-jiucaiyun/node_modules/egg-core/lib/lifecycle.js:92:9)
[egg-scripts]     at Lifecycle.triggerConfigDidLoad (/app/project/egg-jiucaiyun/node_modules/egg-core/lib/lifecycle.js:143:14)
[egg-scripts]     at Lifecycle.triggerConfigWillLoad (/app/project/egg-jiucaiyun/node_modules/egg-core/lib/lifecycle.js:137:10)
[egg-scripts]     at AgentWorkerLoader.loadCustomAgent (/app/project/egg-jiucaiyun/node_modules/egg-core/lib/loader/mixin/custom.js:45:20)
[egg-scripts]     at AgentWorkerLoader.load (/app/project/egg-jiucaiyun/node_modules/egg/lib/loader/agent_worker_loader.js:23:10)
[egg-scripts]     at new Agent (/app/project/egg-jiucaiyun/node_modules/egg/lib/agent.js:26:17)
[egg-scripts]     at Object.<anonymous> (/app/project/egg-jiucaiyun/node_modules/egg-cluster/lib/agent_worker.js:28:15)
[egg-scripts]     at Module._compile (module.js:705:30)
[egg-scripts]     at Object.Module._extensions..js (module.js:717:10)
[egg-scripts]     at Module.load (module.js:618:32)
[egg-scripts]     at tryModuleLoad (module.js:558:12)
[egg-scripts]     at Function.Module._load (module.js:550:3)
[egg-scripts]     at Function.Module.runMain (module.js:748:10)
[egg-scripts] 2019-04-10 12:51:20,643 ERROR 30859 nodejs.AgentWorkerDiedError: [master] agent_worker#1:30866 died (code: 1, signal: null)
[egg-scripts]     at Master.onAgentExit (/app/project/egg-jiucaiyun/node_modules/egg-cluster/lib/master.js:338:17)
[egg-scripts]     at emitOne (events.js:116:13)
[egg-scripts]     at Master.emit (events.js:211:7)
[egg-scripts]     at Messenger.sendToMaster (/app/project/egg-jiucaiyun/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/app/project/egg-jiucaiyun/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at ChildProcess.agentWorker.once (/app/project/egg-jiucaiyun/node_modules/egg-cluster/lib/master.js:229:22)
[egg-scripts]     at Object.onceWrapper (events.js:317:30)
[egg-scripts]     at emitTwo (events.js:126:13)
[egg-scripts]     at ChildProcess.emit (events.js:214:7)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
[egg-scripts] name: "AgentWorkerDiedError"
[egg-scripts] pid: 30859
[egg-scripts] hostname: ekingwintest2
[egg-scripts] 
[egg-scripts] 2019-04-10 12:51:20,644 ERROR 30859 [master] agent_worker#1:30866 start fail, exiting with code:1
[egg-scripts] 2019-04-10 12:51:20,644 ERROR 30859 [master] exit with code:1
[egg-scripts] 
[egg-scripts] Start got error, see /home/admin/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-jiucaiyun@1.0.0 start: `egg-scripts start --daemon --title=egg-server-egg-jiucaiyun`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-jiucaiyun@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/admin/.npm/_logs/2019-04-10T04_51_21_762Z-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by hyj1991** [comment]
> Error: Cannot find module '/app/project/egg-jiucaiyun/node_modules/agentx/lib/orders/.svn'

这里的 .svn 是怎么来的。。。

**Comment by 13349253469** [comment]
> > Error: Cannot find module '/app/project/egg-jiucaiyun/node_modules/agentx/lib/orders/.svn'
> 
> 这里的 .svn 是怎么来的。。。
我通过jenkins部署的不太清楚这个.svn怎么来的，但是我觉得不应该是jenkins导致这个错误的，我把alinode设置成false就部署成功了

**Comment by hyj1991** [comment]
问题就是 https://github.com/aliyun-node/agentx/blob/master/lib/agent.js#L355 这一行里面，会去遍历 `lib/orders` 下的内容加载导致的错误

但是正常你安装的 agentx 是不会有这个 .svn 的。。。

**Comment by atian25** [comment]
额，难道是 svn 把 node_modules 都加进去了，然后修改了源码

**Comment by hyj1991** [comment]
你是否是通过 `npm install` 的方式部署，还是其它的方法安装依赖的？

**Comment by 13349253469** [comment]
> 你是否是通过 `npm install` 的方式部署，还是其它的方法安装依赖的？

我为了省事直接上传node_modules的没有进行重新npm install

**Comment by atian25** [comment]
自己打包处理多余的文件。

**Comment by hyj1991** [comment]
> > 你是否是通过 `npm install` 的方式部署，还是其它的方法安装依赖的？
> 
> 我为了省事直接上传node_modules的没有进行重新npm install

那就是你上传的时候，本地的 node_modules 带上了 .svn 这个异常文件。

**Comment by 13349253469** [comment]
> > > 你是否是通过 `npm install` 的方式部署，还是其它的方法安装依赖的？
> > 
> > 
> > 我为了省事直接上传node_modules的没有进行重新npm install
> 
> 那就是你上传的时候，本地的 node_modules 带上了 .svn 这个异常文件。

解决了这个问题，还是jenkins的问题，
tar zcf deploy.tar.gz  * --exclude deploy.tar.gz --exclude=*.svn
排除.svn就好了
