### ISSUE TITLE
[egg-ons]: 按插件中给出的方式订阅消息，接收不到消息

### ISSUE THREAD

**Issue by CoCoyh** [eggjs/egg#3610]
@dead-horse  @denghongcai @gxcsoccer   帮忙看下问题
## What happens?
使用插件egg-ons，订阅消息，消费不到消息

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

https://github.com/CoCoyh/egg-ons-test/

## How To Reproduce

**Steps to reproduce the behavior:**
1. 在阿里云控制台添加了group和topic
2. 通过该topic发布消息

**Expected behavior**
1. 启动egg服务订阅消息
2. 在该topic文件夹下消费不到消息

## Context
- **Node Version**:
v10.15.0
- **Egg Version**:
^2.15.1
- **Plugin Name**:
egg-ons
- **Plugin Version**:
^2.0.0
- **Platform**:
阿里云平台

**Comment by gxcsoccer** [comment]
估计是因为你加了 namespace

**Comment by gxcsoccer** [comment]
https://github.com/ali-sdk/ali-ons/pull/68

**Comment by CoCoyh** [comment]
@gxcsoccer 删了namespace试了一下，结果是一样的，还是订阅不到消息，服务起来，有警告
![10_15_26__04_15_2019](https://user-images.githubusercontent.com/24558814/56103873-8fc78a80-5f67-11e9-8a8d-fa692942e58b.jpg)

**Comment by gxcsoccer** [comment]
你那个 MQ_INST_20772019_BagzDII4% 这个是什么？

**Comment by CoCoyh** [comment]
@gxcsoccer 我们用的阿里云rocketmq，MQ_INST_20772019_BagzDII4% 是实例ID

**Comment by gxcsoccer** [comment]
把 MQ_INST_20772019_BagzDII4% 去掉呢

**Comment by CoCoyh** [comment]
@gxcsoccer 报错，topic找不到
![11_12_33__04_15_2019](https://user-images.githubusercontent.com/24558814/56105550-71fe2380-5f6f-11e9-96c8-e2cb7bc784ee.jpg)

**Comment by gxcsoccer** [comment]
![image](https://user-images.githubusercontent.com/1207064/56105804-b938e400-5f70-11e9-93d9-4ae3e9892e03.png)

有钉钉吗？ 我需要你把信息给我本地试试

**Comment by gxcsoccer** [comment]
https://github.com/ali-sdk/ali-ons/pull/78

**Comment by liuhuanhui** [comment]
解决了吗 hello

**Comment by liuhuanhui** [comment]
> @gxcsoccer 报错，topic找不到
> ![11_12_33__04_15_2019](https://user-images.githubusercontent.com/24558814/56105550-71fe2380-5f6f-11e9-96c8-e2cb7bc784ee.jpg)
你好 你解决了吗
