### ISSUE TITLE
关于socket.io的一个问题

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3611]
## What happens?
如果在开多进程的时候，socket的工作原理是怎么样的？当多用户连接ws的时候，是会连接到各个进程上，每个用户一个线程处理，还是用户都会连接到一个进程上，再把消息分发到其他进程上？
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by huyu1** [comment]
我在window上处理多进程的时候，发现连接和处理都只打印了一个进程的id，所以有点迷

**Comment by ngot** [comment]
多进程必须使用 sticky 模式来保持连接到同一个进程
https://eggjs.org/zh-cn/tutorials/socketio.html#%E9%83%A8%E7%BD%B2

**Comment by huyu1** [comment]
使用sticky 模式连接到同一个进程，那我是不是可以理解为所有的用户都是连接到一个进程的websocket的，任务分发需要自己用多进程分发到各个进程，处理完再发回ws进程发给客户端吗？

**Comment by canvs** [comment]
有没有人解释下的，文档上这段的解释看不明白，到底使用了sticky模式 所有的用户是不是连接到一个进程的websocket
我本地测试的时候的确连接的websocket 进程都是同一个，但是放到服务器后第一次和第二次发送消息都不是统一的pid 导致发送消息不成功
@ngot

**Comment by ngot** [comment]
@canvs 正确的开启 sticky 后 （没那么容易，要仔细读文档，还有要好好理解它是怎么工作的才行），同一个用户能够成功建立连接，如果 sticky 开启失败，在多进程下很有可能建立连接阶段就直接失败了。

要注意的是，本地开发环境下默认是单进程的，并不会遇到这个问题。但是生产环境 egg 默认是用 Node.js 内置的 cluster 模块来负载均衡的（好好理解这个模块，否则就无法理解 egg-socket.io 是怎么工作的），cluster 默认是 RR 来负载流量的，这个 RR 模式和 socket.io 协议冲突，导致 socket.io 无法正常建立连接。目前唯一的解决办法就是抛弃 cluster 的 RR 模式，自己实现一套 sticky 的负载确保**同一个**用户的请求永远落在同一个进程上。 

"所有的用户是不是连接到一个进程的websocket" 这个说法是不可能发生的，如果发生了，就是重大 bug 了。如果所有用户都连接到一个进程，那么意味着其他的进程将无法承担工作，那么也就无法利用服务器的多核心，就失去了起多进程多意义。

**Comment by canvs** [comment]
> @canvs 正确的开启 sticky 后 （没那么容易，要仔细读文档，还有要好好理解它是怎么工作的才行），同一个用户能够成功建立连接，如果 sticky 开启失败，在多进程下很有可能建立连接阶段就直接失败了。
> 
> 要注意的是，本地开发环境下默认是单进程的，并不会遇到这个问题。但是生产环境 egg 默认是用 Node.js 内置的 cluster 模块来负载均衡的（好好理解这个模块，否则就无法理解 egg-socket.io 是怎么工作的），cluster 默认是 RR 来负载流量的，这个 RR 模式和 socket.io 协议冲突，导致 socket.io 无法正常建立连接。目前唯一的解决办法就是抛弃 cluster 的 RR 模式，自己实现一套 sticky 的负载确保**同一个**用户的请求永远落在同一个进程上。
> 
> "所有的用户是不是连接到一个进程的websocket" 这个说法是不可能发生的，如果发生了，就是重大 bug 了。如果所有用户都连接到一个进程，那么意味着其他的进程将无法承担工作，那么也就无法利用服务器的多核心，就失去了起多进程多意义。

感谢回复！
看了一圈源码终于解决了现在的问题

**Comment by tingtingtinghuang** [comment]
@ngot 如果部署到多个机器上，如何保证同一个用户的请求永远落在同一个进程上。

**Comment by uyoufu** [comment]
> > @canvs 正确的开启 sticky 后 （没那么容易，要仔细读文档，还有要好好理解它是怎么工作的才行），同一个用户能够成功建立连接，如果 sticky 开启失败，在多进程下很有可能建立连接阶段就直接失败了。
> > 要注意的是，本地开发环境下默认是单进程的，并不会遇到这个问题。但是生产环境 egg 默认是用 Node.js 内置的 cluster 模块来负载均衡的（好好理解这个模块，否则就无法理解 egg-socket.io 是怎么工作的），cluster 默认是 RR 来负载流量的，这个 RR 模式和 socket.io 协议冲突，导致 socket.io 无法正常建立连接。目前唯一的解决办法就是抛弃 cluster 的 RR 模式，自己实现一套 sticky 的负载确保**同一个**用户的请求永远落在同一个进程上。
> > "所有的用户是不是连接到一个进程的websocket" 这个说法是不可能发生的，如果发生了，就是重大 bug 了。如果所有用户都连接到一个进程，那么意味着其他的进程将无法承担工作，那么也就无法利用服务器的多核心，就失去了起多进程多意义。
> 
> 感谢回复！ 看了一圈源码终于解决了现在的问题

请教一下，最终原理是什么呢，对 egg 了解不深，看源码实在头大。
eggjs 是不是不适合进行 ws 开发呢，感觉多进程部署很麻烦
