### ISSUE TITLE
[ts]app.loader.loadToApp 的 FileLoaderOption 的 caseStyle 返回类型定义不对

### ISSUE THREAD

**Issue by JimmyDaddy** [eggjs/egg#3618]
## What happens?
TypeScript 版本中，egg-core 的 app.loader.loadToApp 的 FileLoaderOption 中的 caseStyle 返回类型定义不对

本来是：
```javascript
  /** set property's case when converting a filepath to property list. */
  caseStyle?: string | ((str: string) => string);
```
应该是
```javascript
  caseStyle?: string | ((str: string) => string[]);
```

## 相关环境信息
- **操作系统**：MAC OSX
- **Node 版本**：v11.6.0
- **Egg 版本**：2.6.1

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-core/blob/master/index.d.ts#L294   可以提个 PR

**Comment by JimmyDaddy** [comment]
好的，[已提](https://github.com/eggjs/egg-core/pull/209)

**Comment by atian25** [comment]
4.16.2
