### ISSUE TITLE
[Feature Request] Controller级别的中间件

### ISSUE THREAD

**Issue by ghostoy** [eggjs/egg#3629]
## Background
Controller中的方法经常需要执行一些类似业务逻辑，比如Restful的API中常常要通过Router中的ID获取实例，如果找不到则拒绝后续操作，并返回404错误。

### 实现方法1： 中间件
在Egg.js中，现在可以通过Router定义中添加额外的中间件代码，如下：
```javascript
router.get('/posts/:postId', async (ctx, next) => {
  const { service, params } = ctx;
  ctx.post = await service.find(params.postId);
  await next();
}, app.controller.post.show);
```
但是，这样会把部分业务逻辑放在路由定义中。一个更好的实现是把中间件的实现放在`app/middleware/post`中，在路由定义中只需：
```javascript
router.get('/posts/:postId', app.middleware.post, app.controller.post.show);
```
然而，这样部分业务逻辑会分散在中间件的实现中。

### 实现方法2：手动调用

在Controller中把通用代码实现在一个方法中，然后在每个函数中手动调用这个方法，这样可以把业务逻辑都统一在Controller中，但是非常繁琐，而且一旦忘记调用，则可能会出现意外的bug。

## Proposal

建议提供Controller级别的中间件，例如：
```javascript
class PostController extends Controller {
  static async middleware(ctx, next) {
    const { service, params } = ctx;
    if (params.postId) {
      ctx.post = await service.find(params.postId);
    }
    await next();
  }
}
```
在执行其他方法时加载Controller级别的中间件，这样做不仅简化了共用的业务逻辑的执行，也能把相关的业务逻辑统一地实现在Controller中。

**Comment by ghostoy** [comment]
现在有一种Workaround的方式，就是在路由定义中手动`require`定义的Controller，并注入到路由定义中，比如：
```javascript

const PostController = require('./controller/post.js');

module.exports = app => {
  const { router, controller } = app;

  router.get('/posts/:postId', PostController.middleware, controller.post.show);
};
```

这个手动注入的方式依然可能会出现忘记而漏掉这个中间件的可能，用`egg-router-plus`的`namespace`可以部分避免这样的问题。

另外，这样的注入的实现方式需要手动查找Controller的相对路径，并指定middleware的方法，足够灵活但不够优雅。

**Comment by atian25** [comment]
1. 用全局 middleware 加 match？
2. 自己定义一个 Controller 基类，然后在构造函数里面对自己设置一个 Proxy 拦截调用，自行处理。

该场景不是通用需求，egg 不会内置实现，可以按上面的思路自己写个插件

**Comment by ghostoy** [comment]
@atian25 通过static的静态函数在Controller里实现Middleware比Proxy或全局middleware的方式更加直观。

现在框架可以通过`app.controller`获取实例化的controller，但是不能通过`controller.constructor.staticMethod`得到它的静态函数，只能使用上面提到的直接`require`的凡是实现，希望egg框架能够提供对Controller静态函数访问。

**Comment by atian25** [comment]
非通用场景。如果你有需求，可以看下 loader 自己覆盖实现 loadController。
