### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#363]
We have got some requirement for english document, so we should make some schedule to do it.

## List of Document

- [x] Intro:
  - [x] What is egg: /intro/index.md @davidnotes
  - [x] egg and koa: /intro/egg-and-koa.md @davidnotes
  - [x] Get Start: /intro/quickstart.md
  - [ ] migration: /migration.md
- [x] Basics:
  - [x] Environment: /basics/env.md
  - [x] Object: /basics/objects.md @Azard
  - [x] Config: /basics/config.md @jwssdwed @Brian175 
  - [x] Middleware: /basics/middleware.md @lslxdx 
  - [x] Router: /basics/router.md @lslxdx 
  - [x] Controller: /basics/controller.md @lslxdx 
  - [x] Service: /basics/service.md @lslxdx
  - [x] Plugin: /basics/plugin.md
  - [x] Schedule: /basics/schedule.md @Azard
  - [x] Structure: /basics/structure.md @Azard
  - [x] Extend: /basics/extend.md @DanielWLam
  - [x] Custom init: /basics/app-start.md @atian25  
- [x] Tutorials:
  - [x] Index: /tutorials/index.md @DarrenWong 
  - [x] MySQL: /tutorials/mysql.md @DarrenWong
  - [x] RESTful API: /tutorials/restful.md @DarrenWong 
  - [x] Progressive: /tutorials/progressive.md @DarrenWong
  - [x] Async Function: /tutorials/async-function.md @DarrenWong 
  - [x] Socket.IO: /tutorials/socketio.md
  - [x] passport: /tutorials/passport.md
- [x] Core:
  - [x] Cluster and Ipc: /core/cluster-and-ipc.md @lslxdx
  - [x] Cookie and Session: /core/cookie-and-session.md @zhang-z 
  - [ ] Development: /core/development.md @gztchan
  - [x] Deployment: /core/deployment.md
  - [x] Security: /core/security.md @lslxdx
  - [x] HttpClient: /core/httpclient.md @DarrenWong
  - [x] Logger: /core/logger.md @gztchan 
  - [x] Error Handling: /core/error-handling.md @gztchan 
  - [x] i18n: /core/i18n.md @DarrenWong
  - [x] View: /core/view.md @zhang-z 
  - [x] Unit Testing: /core/unittest.md
- [x] Advanced:
  - [x] Loader: /advanced/loader.md @Azard
  - [x] Plugin Development: /advanced/plugin.md
  - [x] Framework: /advanced/framework.md @freebyron
  - [x] Cluster: /advanced/cluster.md
  - [x] View Plugin: /advanced/view-plugin.md
- [x] Community:
  - [x] style guide: /style-guide.html
  - [x] Resource: /resource.md
  - [x] Faq: /faq.md

## Where is the document

Now you can see all available English document in https://github.com/eggjs/egg/tree/master/docs/source/en

## How to translate

1. If you want to pick one to translate, you can create a PR first. Then I will know it has been taken.
1. Any one can proofread it,  and finalized by Egg core member and SwiftGG member.
1. you can update this PR until merged

## Contribute

Welcome to join us to translate egg document, We are glad to see that.

**Comment by fengmk2** [comment]
@mattma 'What is egg' is the important document.

@dead-horse 'egg and koa' write again with your good English.

**Comment by mattma** [comment]
@fengmk2 I will work on `what is egg` next. thanks

**Comment by popomore** [comment]
Thx https://github.com/eggjs/egg/pull/462

**Comment by davidnotes** [comment]
Hi all, I have almost finished 'egg and koa' english doc and I will give the pull request tonight. Hope it will help @fengmk2 @dead-horse @popomore .

**Comment by popomore** [comment]
@davidnotes good work, we will at someone after the document if he picked it.

**Comment by Brian175** [comment]
If you guys can still help the translation, welcome to join SwiftGG qq group: 624448959. We are now trying to translate the remaining articles.

**Comment by popomore** [comment]
https://github.com/eggjs/egg/pull/783

**Comment by lslxdx** [comment]
Hi all,


2 things: 
1. the "Router: /basics/router.md" HAS BEEN TRANSLATED by me and waiting to be proofread.
2. the "Controller: /basics/controller.md" IS BEING TRANSLATED(about 50% is done)


在2017年04月20 15时57分, "Haoliang Gao"<notifications@github.com>写道:



We have got some requirement for english document, so we should make some schedule to do it.

List of Document
Intro:
What is egg: /intro/index.md @davidnotes
egg and koa: /intro/egg-and-koa.md @davidnotes
Get Start: /intro/quickstart.md
Basics:
Environment: /basics/env.md
Config: /basics/config.md
Middleware: /basics/middleware.md @lslxdx
Router: /basics/router.md
Controller: /basics/controller.md
Service: /basics/service.md
Schedule: /basics/schedule.md
Structure: /basics/structure.md
Extend: /basics/extend.md
Custom init: /basics/app-start.md
Tutorials:
Index: /tutorials/index.md
MySQL: /tutorials/mysql.md
RESTful API: /tutorials/restful.md
Progressive: /tutorials/progressive.md
Async Function: /tutorials/async-function.md
Core:
Cluster and Ipc: /core/cluster-and-ipc.md
Cookie and Session: /core/cookie-and-session.md
Development: /core/development.md
Deployment: /core/deployment.md
Security: /core/security.md
HttpClient: /core/httpclient.md
Logger: /core/logger.md
Error Handling: /core/error-handling.md
i18n: /core/i18n.md
View: /core/view.md
Unit Testing: /core/unittest.md
Advanced:
Loader: /advanced/loader.md
Plugin: /advanced/plugin.md
Framework: /advanced/framework.md
Cluster: /advanced/cluster.md
View Plugin: /advanced/view-plugin.md
Community:
Resource: /resource.md
Faq: /faq.md
Where is the document

Now you can see all available English document in https://github.com/eggjs/egg/tree/master/docs/source/en

Contribute

Welcome to join us to translate egg document, We are glad to see that.

**Comment by popomore** [comment]
@lslxdx marked for you

**Comment by DanielWLam** [comment]
Hi, I would like to help to tranlate ```Service: /basics/service.md```, thanks @fengmk2

**Comment by Hiufan** [comment]
Hi, I think I can help to translate this page: `Config: /basics/config.md`.

**Comment by zacks223** [comment]
Hi, I would like to translate `Env: /basics/env.md`, thanks.

**Comment by popomore** [comment]
@DanielWLam @Hiufan @zacks223 Thx, you can do it now, I have added you to the list.

**Comment by popomore** [comment]
@zacks223 Sorry, [env.md](https://github.com/eggjs/egg/blob/master/docs/source/en/basics/env.md) has been translated, would you choose another one?

**Comment by popomore** [comment]
@lslxdx Do you have time to write the uncomplete document you choose?

**Comment by Brian175** [comment]
@DanielWLam @Hiufan @zacks223 Hey, guys! Will you have interest in joining our group in the document translation?
https://github.com/SwiftGGFETeam/

**Comment by popomore** [comment]
Hi @Brian175 , would you like check the document which has been taken in this issue before translating.

**Comment by lslxdx** [comment]
Hi @DanielWLam, @fengmk2, the `basics/service.md` has been translated by me days ago.

https://github.com/SwiftGGFETeam/egg/blob/basics.service/docs/source/en/basics/service.md

**Comment by lslxdx** [comment]
Hi @popomore, the `basics/controller.md` and `basics/middleware.md` have been completed.

https://github.com/SwiftGGFETeam/egg/blob/basics.controller/docs/source/en/basics/controller.md

https://github.com/SwiftGGFETeam/egg/blob/basics.middleware/docs/source/en/basics/middleware.md

**Comment by lslxdx** [comment]
Hi @popomore, the `basics/router.md` was translated, BUT was not commited in Github. I will commit it tomorrow. Sigh ~

I'm working on `basics/schedule.md` and finding a new job now...

**Comment by DanielWLam** [comment]
@Brian175 Sounds good to me. I am in! And since @lslxdx  has finished those tasks, maybe i should work on ```/basics/extend.md``` @popomore

**Comment by popomore** [comment]
@lslxdx @Brian175 @DanielWLam Could you create PR first when you are starting translation? All of us will know which one is be taken.

**Comment by lslxdx** [comment]
@popomore That sounds good to me.

Up to now, my work process is: 
1. git clone https://github.com/SwiftGGFETeam/egg;
2. create 1 new branch for each doc and begin to translate it; 
3. commit, push and waiting for other guys to proofread and finalize the doc on the branch. 
4. After the doc is finalized, the branch is merged to master and a PR to `https://github.com/eggjs/egg` is created then.

Is it a proper work process?

**Comment by popomore** [comment]
@lslxdx I think you can do it on egg directly, SwiftGG Team and Egg core member can review it on it.

cc @Brian175

**Comment by popomore** [comment]
> And since @lslxdx has finished those tasks, maybe i should work on /basics/extend.md

@DanielWLam OK

**Comment by popomore** [comment]
And I have updated the rule for translating, is it suitable for you? @lslxdx @Brian175

**Comment by Brian175** [comment]
@popomore Can you tell more details? I am a little in confusion.

**Comment by popomore** [comment]
@Brian175 you can see "How to translate" above

**Comment by Brian175** [comment]
@popomore I've got it, it's okay.Thanks.

**Comment by fengmk2** [comment]
@DarrenWong Great jobs!

**Comment by DarrenWong** [comment]
@fengmk2  thx, I will keep it up and study Egg O(∩_∩)O

**Comment by gztchan** [comment]
Could you assign following parts to me?
- Logger: /core/logger.md
- Error Handling: /core/error-handling.md

**Comment by popomore** [comment]
@gztchan Sure

**Comment by zhang-z** [comment]
Volunteer to /core/cookie-and-session.md
WIP PR: https://github.com/eggjs/egg/pull/1562

**Comment by Azard** [comment]
`Basics/Object` should be checked: https://github.com/eggjs/egg/blob/master/docs/source/en/basics/objects.md

And `schedule` is still be translated by @lslxdx ?
Maybe I can do this.

**Comment by popomore** [comment]
@Azard It's yours now.

**Comment by lslxdx** [comment]
Count you please assign `Cluster and Ipc: /core/cluster-and-ipc.md` to me? Thanks!

**Comment by atian25** [comment]
@lslxdx done.

**Comment by zhang-z** [comment]
Volunteer to /core/view.md
WIP PR: #1577

**Comment by lslxdx** [comment]
@popomore 

core/cluster-and-ipc.md translated & please have a check.

https://github.com/eggjs/egg/pull/1594

**Comment by lslxdx** [comment]
Please assign `Deployment: /core/deployment.md` to me, thanks!

**Comment by popomore** [comment]
@zhang-z @lslxdx done

**Comment by lslxdx** [comment]
I notice that `Deployment: /core/deployment.md` has been translated, could anybody make the `List of Document` be updated?

**Comment by hotNoder** [comment]
Hi, @popomore I would like to translate  Advanced:  Cluster: /advanced/cluster-client.md.  Seems like the list should be updated, thanks.

**Comment by cemremengu** [comment]
Looks like this issue will be closed after the current PRs are closed

**Comment by cemremengu** [comment]
Done ? 👀

**Comment by popomore** [comment]
This issue can be closed, thanks to

- @hotNoder 
- @freebyron 
- @Azard 
- @rccoder 
- @cemremengu 
- @SunShinewyf
- @lslxdx 
- @zhang-z
- @gztchan
- @DarrenWong
- @freebyron
- @davidnotes

We have some new document that have not be translated.

- [development](https://github.com/eggjs/egg/blob/master/docs/source/en/core/development.md)
- [assets](https://github.com/eggjs/egg/blob/master/docs/source/en/tutorials/assets.md)
- [typescript](https://github.com/eggjs/egg/blob/master/docs/source/en/tutorials/typescript.md)
- [migration](https://github.com/eggjs/egg/blob/master/docs/source/en/migration.md)

**Comment by popomore** [comment]
cc @atian25
