### ISSUE TITLE
教程-快速入门-逐步搭建

### ISSUE THREAD

**Issue by xiaoaq** [eggjs/egg#3630]
按照教程来，遇到一个问题
open 127.0.0.1:7001 是404。没路由到，都是按教程来的，不知道哪边有问题？需要额外配置什么吗？

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by xiaoaq** [comment]
https://github.com/xiaoaq/HackerNews

**Comment by atian25** [comment]
`app/router.js` 而不是 `app/route.js`
