### ISSUE TITLE
如何获取用户的请求IP后，再使用用户的请求IP对一个新地址重新发起请求？

### ISSUE THREAD

**Issue by wuyugege** [eggjs/egg#3633]
如题

**Comment by atian25** [comment]
学习下 http 的原理吧。

如果你只是后端需要判断这个 IP 的话，看下 x-forward-for 的相关知识。

https://zhuanlan.zhihu.com/p/62265144

**Comment by wuyugege** [comment]
我的问题应该是属于代理这块，服务器获取用户请求IP，然后使用用户的请求IP而不是服务器的IP再发起请求，这个在egg里应该怎么操作 @atian25

**Comment by atian25** [comment]
上面不是提了么，通过 x-forwarded-for
