### ISSUE TITLE
controller中promise-resolve设置body结果404

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3637]
controller.js
```js
	preview() {
		let {ctx} = this;
		webpackCompile({
//一个function return promise
			name: 'jehol',
		}).then((res) => {
	console.log('compiled successfully', res);
			return ctx.body = '<html><h1>hello </h1></html>'; 
		}).catch((err) => {
			// console.log(err);
		});
	}
```

router.js
```js
	router.get('/preview', controller.page.preview);
```
请求 /preview 返回404
不经过promise 正常

为什么加了promise结果会404？
---

**Comment by atian25** [comment]
你要 await 这个 promise 啊。。。 

先回去再看看 Promise 和 Koa 这块的知识吧。

**Comment by MJingv** [comment]
> 你要 await 这个 promise 啊。。。
> 
> ```js
> async preview() {
>   this.ctx.body = await webpackCompile();
> }
> ```
> 
> 先回去再看看 Promise 和 Koa 这块的知识吧。

？？ 我这个webpackCompile 是个promise 不是async-function

**Comment by atian25** [comment]
所以让你回去看看 Promise 的知识

http://es6.ruanyifeng.com/#docs/promise
http://es6.ruanyifeng.com/#docs/async

**Comment by MJingv** [comment]
> 所以让你回去看看 Promise 的知识
> 
> http://es6.ruanyifeng.com/#docs/promise
> http://es6.ruanyifeng.com/#docs/async



我这个webpackCompile 是个promise 里面是同步的，不是异步的

**Comment by MJingv** [comment]
> 所以让你回去看看 Promise 的知识
> 
> http://es6.ruanyifeng.com/#docs/promise
> http://es6.ruanyifeng.com/#docs/async

好的
