### ISSUE TITLE
[egg-sequelize]对动态表的支持

### ISSUE THREAD

**Issue by luoxiaoji** [eggjs/egg#3639]
- [x] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
动态生成表的支持

### What does the proposed API look like?
当前项目是在一个库中，有多个产品，以及可增加新产品，想根据产品名进行分表：xxx_tabel1

查询貌似 egg-sequelize 不支持这种做法，所以我的目前的做法是：

* 新建一个文件夹存放动态表，表名为基础表名。
* 获取所有产品名，遍历将名字拼接好新表名赋值给文件夹的model，导入ctx/app.model补齐。
* sync生成新的表，执行新表关联模型。
* 写一个自定义启动脚本 执行。

貌似耗时稍稍有点长，有更合适的方案吗？

**Comment by popomore** [comment]
这是业务的做法，如有更多 sequelize 疑问可以去官网咨询。
