### ISSUE TITLE
问题：egg 请求提前返回 500 ？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3640]
我们生产项目碰到一个棘手的问题：

我们一个 egg 接口需要访问 grpc service，从 log 可以看到，这个接口收到一个请求时，会先返回一个 grpc 连接失败的 response 给到客户端。然后一秒后，拿到了 grpc service 的结果，再返回一个 200 响应到客户端。

可是第一次返回的 500 就已经让客户端报错了，请问各位大佬有没有在使用 egg js 时碰到类似的问题？

**Comment by Jeff-Tian** [comment]
最后发现是某一个 grpc service 连接不上造成的。

**Comment by mmdapl** [comment]
请问，你们正式环境下，是如何在app.js里面启动grpc服务端的？会存在多个worker导致端口被占用的问题嘛？ @Jeff-Tian

**Comment by Jeff-Tian** [comment]
Grpc服务是在单独的service里，egg只是作为客户端去连接它们。具体是使用了egg-grpc-client-ts插件。
