### ISSUE TITLE
service 自定义一个构造函数，在controller里面New的话直接报错，如何处理？

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#3642]

**Comment by atian25** [comment]
service 是框架来初始化的，不要自己 new

**Comment by tong3jie** [comment]
在调用定义的service内的方法之前，需要做一些初始化的处理？但又并不是每次都需要初始化，只需在第一次调用的时候需要。

**Comment by atian25** [comment]
- 定制一个 Service 的基类，但要传递原来的参数给 super
- 不要在 Controller 里面 new，还是按原来的方式直接调用
- Service 初始化需要的一些内容，通过 config 的方式去获取。

**Comment by tong3jie** [comment]
好的，感谢

**Comment by ruur** [comment]
@atian25 我有相同的疑问，请问当前的egg一般怎么处理类中的这些参数呢？是通过注入全局的对象还是必须在每一个类的函数里传递这几个参数呢？
问题描述：
1. 对于一个继承Service的类；
2. 这个类有一些需要在每一次实例化类时用到的参数，可能类里面大部分的函数都可能用到；
3. 当然可以每次调用函数时都传递进去，有没有更友好的使用方式呢；

首次在项目中使用eggjs，请帮忙解释下，谢谢。

**Comment by atian25** [comment]
具体情况具体分析，就是普通的代码复用方式

**Comment by ruur** [comment]
@atian25
本来复用的方式是这样的
`
class A {
   constructor(a:string, b:string) {
       this.a = a;
       this.b = b;
   }
   async m(){}
   async n() {}
   async p() {}
   ......
}
` 
m、n、p等函数都有可能用到this.a  this.b，那么a/b相当于在实例化类A的时候传进去的
那么在egg里使用重复的a/b这些变量时，除了在每个m/n/p等函数里传入a/b, 还有没有更好的方式呢？
因为在egg框架里，使用service时实际上已经实例化了。
a/b可能因具体的哪次实例化传值的不同而不同，所以不适合放在配置里。

**Comment by atian25** [comment]
这些数据的来源是哪里呢？是请求相关的还是全局的呢？ 前者可以在 ctx，后者在 config

**Comment by ruur** [comment]
@atian25 如果来源于数据库呢？实例化类的时候从数据库取到最新的数据传到类里面。
比如这个场景：系统里有很多用户，每个用户注册了一个key/secret，类里面很多函数会直接用到这两个参数，类实例化的时候可以把这两个参数传进去。

**Comment by atian25** [comment]
js 不支持 AOP

**Comment by ruur** [comment]
@atian25 我这个问题应该只是OOP吧，没有做横向扩展

**Comment by atian25** [comment]
类似的啊，你这明显是多个 fn 都要有同一个 before，这种要不就是中间件，要不就是装饰器来实现 AOP
