### ISSUE TITLE
egg-redis连接数上升导致报错

### ISSUE THREAD

**Issue by RonnieDuck** [eggjs/egg#3646]
## What happens?
![image](https://user-images.githubusercontent.com/19317133/56638458-d5d7c900-66a0-11e9-923a-95b3ebb90162.png)

## 最小可复现仓库
缺少

## 复现步骤，错误日志以及相关配置

线上系统经过一段时间后会出现该报错，具体重现方法大概是清理redis的连接然后再使用一段时间。提供redis的阿里云服务有建议说使用连接池？

## 相关环境信息
- **操作系统**：linux
- **Node 版本**：≥8
- **Egg 版本**：2.2.1

**Comment by killagu** [comment]
> 清理redis的连接然后再使用一段时间

**Comment by killagu** [comment]
> 清理redis的连接然后再使用一段时间

没看明白这个是什么意思
