### ISSUE TITLE
egg中间件not found

### ISSUE THREAD

**Issue by tujiaw** [eggjs/egg#3647]
## 问题
新增了一个名字为mid_hit的中间件，按照官网步骤设置好配置，执行npm run dev命令的时候启动失败，错误是：TypeError: Middleware mid_hit not found

## 解决
后来我将中间件名字改为midhit就可以了。

## egg版本
```
    "egg": "^2.15.1",
    "egg-scripts": "^2.11.0",
    "egg-view-nunjucks": "^2.2.0",
```

**Comment by atian25** [comment]
文档里面写的很清楚了，loader 加载后，会转换为驼峰格式。

`mid_hit` -> `midHit`

**Comment by liufengsoft** [comment]
这种变来变去的 就跟狗屎一样， 全部统一约定不好么。

**Comment by atian25** [comment]
> 这种变来变去的 就跟狗屎一样， 全部统一约定不好么。

这就是我们的统一约定。谢谢。

**Comment by atian25** [comment]
鉴于不文明发言，禁言 3 天。
