### ISSUE TITLE
[Feature Request] app.addSingleton(name, creator)的creator参数能否增加一个key参数

### ISSUE THREAD

**Issue by loveonelong** [eggjs/egg#3648]
现在app.addSingleton(name, creator)的creator有两个参数，config和app。但是config对应的在app.config[pluginName].clients的key没有办法获取到。

client内部打印logs希望能获得到当前config的key来标记错误出现自哪个client

**Comment by loveonelong** [comment]
creator(config,app,key)

key: 如果是clients就是clients对应的key，如果是client就是插件自己的name

**Comment by popomore** [comment]
感觉可以

**Comment by atian25** [comment]
欢迎 PR。

临时解决方式是你在 config 里面自己加个 key。

**Comment by loveonelong** [comment]
恩，谢谢。我大概看了源码，五一放假提个pr。

**Comment by atian25** [comment]
@loveonelong 放完假啦~
