### ISSUE TITLE
更好的配置实现方式

### ISSUE THREAD

**Issue by yuu2lee4** [eggjs/egg#3649]
egg的目前配置的使用方式有诸多不便之处，必须得传入app或者ctx才能使用，但是很多时候却无法获取到app或者ctx，比如使用decrator的时候：
````javascript
export class TestController {
 @foo()
  async test(ctx) {
    ....
  }
````
foo如何得到ctx或者app呢，如果能这样引用就好了
````javascript
import config from 'egg/config'

export class TestController {
 @foo(config.get('fooConfig'))
  async test(ctx) {
    ....
  }
````
所有的配置都可以用config.get('foo')去获取，类似于[config](https://www.npmjs.com/package/config)模块，当然为了兼容app和ctx上也可以取到配置，但是配置的来源都是统一的一个地方

**Comment by whxaxes** [comment]
为什么使用 decorator 的时候无法使用？你写 decorator 的目的是为了劫持对应的 class method 做包装，那你写成封装后的 method，跟你的 controller 的方法不是一样的？例子如下

```typescript
function validate() {
  return function(_target: HomeController, _propertyKey: string, descriptor: PropertyDescriptor) {
    const oldAsyncFunc = descriptor.value;
    descriptor.value = async function(ctx: Context) {
      console.info(ctx.app.config);
      await oldAsyncFunc.call(this, ctx);
    };
  };
}

export default class HomeController extends Controller {
  @validate()
  public async index() {
      ...
  }
}
```

**Comment by yuu2lee4** [comment]
有可能是我写的decorator 也可能是第三方的decorator啊

**Comment by whxaxes** [comment]
那你按照我的例子包一层不就行了？

**Comment by yuu2lee4** [comment]
额。。框架层面就不能提供更便利的方式  。。每个decorator都包一层   。。 那还要框架干啥。。看你们在准备3.0，我建议就是保证配置的独立性，可以单独获取，其它环境上的配置可通过构建注入

**Comment by whxaxes** [comment]
- 如果直接可以通过 `import` 获取，那跟你直接本地写个 js 来放配置没什么区别
- 多环境的配置通过构建注入，就有点本末倒置了，我用个 node 框架还得跑个 webpack 构建一番不成？

**Comment by yuu2lee4** [comment]
1、import的包肯定要处理不同环境有不同配置
2、我说的构建注入不是这个意思，我的意思是配置是独立正在一个地方，ctx、app上的配置都是从那个地方来的

**Comment by atian25** [comment]
egg 本身不会提供装饰器相关能力，除非哪天它正式进入 ES 规范并发布 LTS。

可以自己封装一个包共享出来，或者去 midway 提需求。

**Comment by yuu2lee4** [comment]
这个跟装饰器没什么关系，这是一个例子而已

**Comment by atian25** [comment]
那更新下正文？你期望有怎么样的配置？

我猜你是说 config 的 appInfo 入参？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-aop

可以参考这个或 midway

**Comment by popomore** [comment]
config 本身肯定不会给 ctx/app 的，例子不太好

**Comment by whxaxes** [comment]
他期望的是，config 不跟 app 和 ctx 绑在一块，而是单独存在一个模块上，然后可以通过 import 引入拿到配置

**Comment by atian25** [comment]
如果只是应用层使用的话，你的 config.default.js 不要写成 `appInfo => {}` 方式（`appInfo` 和 `app` 是两个东西），然后自己就可以 require 了。至于插件的，那肯定不行啦，不加入 loader 流程，我们怎么可能知道有哪些插件。

**Comment by yuu2lee4** [comment]
如果要我目前在业务实现，会引入一个config模块，来管理和获取不同环境的配置，并且注入到config.default.js里

**Comment by atian25** [comment]
这个是你的自由。回到主题，你觉得怎么样的是更好的，把正文更新下我们再来讨论吧

**Comment by whxaxes** [comment]
我觉得这个讨论可以先打住了

@yuu2lee4 期望能够在任何模块里都能通过 require 的方式拿到 egg 的配置，也就是 egg 得把所有配置都写到某个模块供业务方 require，这个设计对于 egg 来说是不太合理的，也会存在很多问题，比如 require 的时机和 egg 的 loader 加载时机问题，可能会让更多人困扰，再者也跟 egg 的设计理念不匹配。

如果你需要这种功能，可以自己封装一个类似于 `injectConfig` 的装饰器来包一层，如果你觉得好用开源出来都可以，但是不太可能在 egg 中支持这种特性。这种实现不利于 egg 的统一管控。
