### ISSUE TITLE
egg+react 服务器跑不起来，本地 npm run dev 可以

### ISSUE THREAD

**Issue by wuqiaoli** [eggjs/egg#3650]
npm start 一直报这个错：
 Got error when startup: 
[egg-scripts] /home/admin/egg-admin-service/node_modules/egg/lib/application.js:70
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] AssertionError [ERR_ASSERTION]: /home/admin/egg-admin-service/config/manifest.json is required
[egg-scripts]     at module.exports.app (/home/admin/egg-admin-service/node_modules/egg-view-assets/app.js:28:5)
[egg-scripts]     at Hook.configDidLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:92:9)
[egg-scripts]     at Lifecycle.triggerConfigDidLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:143:14)
[egg-scripts]     at Lifecycle.triggerConfigWillLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:137:10)
[egg-scripts]     at AppWorkerLoader.loadCustomApp (/home/admin/egg-admin-service/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
[egg-scripts]     at AppWorkerLoader.load (/home/admin/egg-admin-service/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
[egg-scripts]     at new Application (/home/admin/egg-admin-service/node_modules/egg/lib/application.js:66:19)
[egg-scripts]     at Object.<anonymous> (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/app_worker.js:19:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[egg-scripts] /home/admin/egg-admin-service/node_modules/egg/lib/application.js:70
[egg-scripts]       throw e;
[egg-scripts]       ^
[egg-scripts] 
[egg-scripts] AssertionError [ERR_ASSERTION]: /home/admin/egg-admin-service/config/manifest.json is required
[egg-scripts]     at module.exports.app (/home/admin/egg-admin-service/node_modules/egg-view-assets/app.js:28:5)
[egg-scripts]     at Hook.configDidLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:92:9)
[egg-scripts]     at Lifecycle.triggerConfigDidLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:143:14)
[egg-scripts]     at Lifecycle.triggerConfigWillLoad (/home/admin/egg-admin-service/node_modules/egg-core/lib/lifecycle.js:137:10)
[egg-scripts]     at AppWorkerLoader.loadCustomApp (/home/admin/egg-admin-service/node_modules/egg-core/lib/loader/mixin/custom.js:37:20)
[egg-scripts]     at AppWorkerLoader.load (/home/admin/egg-admin-service/node_modules/egg/lib/loader/app_worker_loader.js:33:10)
[egg-scripts]     at new Application (/home/admin/egg-admin-service/node_modules/egg/lib/application.js:66:19)
[egg-scripts]     at Object.<anonymous> (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/app_worker.js:19:13)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:701:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[egg-scripts] 2019-04-26 16:47:18,745 ERROR 28916 nodejs.AppWorkerDiedError: [master] app_worker#2:28936 died (code: 1, signal: null, suicide: false, state: dead), current workers: ["1"]
[egg-scripts]     at Master.onAppExit (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/master.js:411:21)
[egg-scripts]     at Master.emit (events.js:189:13)
[egg-scripts]     at Messenger.sendToMaster (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.cluster.on (/home/admin/egg-admin-service/node_modules/egg-cluster/lib/master.js:280:22)
[egg-scripts]     at EventEmitter.emit (events.js:194:15)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:193:13)
[egg-scripts]     at Object.onceWrapper (events.js:277:13)
[egg-scripts]     at ChildProcess.emit (events.js:189:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 28916
[egg-scripts] hostname: izbp1bqngpatbwumgthp4rz

**Comment by atian25** [comment]
```bash
AssertionError [ERR_ASSERTION]: /home/admin/egg-admin-service/config/manifest.json is required
[egg-scripts] at module.exports.app (/home/admin/egg-admin-service/node_modules/egg-view-assets/app.js:28:5)
```

写的很清楚了，线上是需要提前构建的。看下对应的文档吧

**Comment by wuqiaoli** [comment]
看过了，是提前构建的呀

**Comment by atian25** [comment]
那就按错误提示排查下为什么没这个文件咯

**Comment by wuqiaoli** [comment]
我用的是roadhog 完全满足这个映射关系使用 assets 模板引擎。而 umi 不满足文件映射，因为他只有一个入口 umi.js 文件，所以选择其他模板引擎的方案。我用的umi

**Comment by wuqiaoli** [comment]
我用的umi 就是按照静态资源部署文档来的

**Comment by popomore** [comment]
可能你构建没指定 NODE_ENV

https://github.com/eggjs/examples/blob/master/assets-with-umi/app/web/config/config.prod.js#L6
