### ISSUE TITLE
egg 什么导致的这段提示

### ISSUE THREAD

**Issue by wuqiaoli** [eggjs/egg#3651]
2019-04-26 17:43:21,165 ERROR 3024 nodejs.ENOENTError: spawn D:\项目\egg-admin-service\node_modules\commandx\get_processes_count ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
errno: "ENOENT"
code: "ENOENT"
syscall: "spawn D:\\项目\\egg-admin-service\\node_modules\\commandx\\get_processes_count"
path: "D:\\项目\\egg-admin-service\\node_modules\\commandx\\get_processes_count"
spawnargs: ["node"]
cmd: "D:\\项目\\egg-admin-service\\node_modules\\commandx\\get_processes_count node"
name: "ENOENTError"
pid: 3024
hostname: PC-20170905CGYU

**Comment by atian25** [comment]
看起来像是 AliNode 的一个组件，但 Egg 是不需要手动安装这个的，再看下部署文档。

如有问题，提供最小可复现仓库。

**Comment by wuqiaoli** [comment]
嗯嗯，我试试谢谢

**Comment by wuqiaoli** [comment]
我注释掉就没有这个提示了，谢谢

**Comment by hyj1991** [comment]
看不太懂，commandx 没有安装成功？

**Comment by Songkeys** [comment]
@wuqiaoli 同样的问题，我发现好像是 alinode 导致的。我把 alinode 升级到 5.15 后就有这个报错了。请问你是如何解决的？

**Comment by frankgo81** [comment]
解决方案
那么既然知道了Windows下不支持这个监控，我这就十分有必要在egg.js中的alinode配置修改为enable: false了，大致如下：

exports.alinode = {
  enable: false,
  server: 'wss://agentserver.node.aliyun.com:8080',
  appid: '66666',
  secret: 'itisasecrectsoicannottellyougays',
};
但是，项目维护要适应不同环境。。。总不能一不小心提交到正式环境，就关了监控吧。于是解决方案有二：

修改git忽略列表，不提交该文件，使本地和正式线不一致。（不推荐）
修改配置如下：

exports.alinode = {
  enable: process.platform !== 'win32',
  server: 'wss://agentserver.node.aliyun.com:8080',
  appid: '66666',
  secret: 'itisasecrectsoicannottellyougays',
};
其实一般项目都是运行在linux主机上的，所以这行process.platform !== 'win32'真的仅限于本地开发了。如果有朋友遇到这种情况不妨试试这样修改配置哦~

不支持windows： 原文  
![image](https://user-images.githubusercontent.com/33563058/150718650-c45dc2a4-f2f5-4f57-9c9a-2baeb089e845.png)

**Comment by atian25** [comment]
一般这个在 prod 环境开启就好了，本地不用开。

或者换 easy-monitor，支持 win
