### ISSUE TITLE
RESTful 

### ISSUE THREAD

**Issue by xiaoaq** [eggjs/egg#3657]
![image](https://user-images.githubusercontent.com/33898493/56864072-bc13ea00-69f0-11e9-9d33-8cab06a62b85.png)
请教下，RESTful风格的url几个path对应的controller api名是固定那几个的吗？还有:id也都是规定的吗？

**Comment by atian25** [comment]
这是规范来着，如果你有自己的需求，可以自己实现对应的插件。
可以参考下 https://github.com/eggjs/egg-router
