### ISSUE TITLE
pkg="egg-sequelize"  location="index.d.ts"  line=9  errorCode= TS1169

### ISSUE THREAD

**Issue by o-w-o** [eggjs/egg#3659]
## What happens?

如图：
![image](https://user-images.githubusercontent.com/12809186/56875722-35552080-6a75-11e9-8381-59076c1cc4d9.png)

## 备注
如果只是个例情况，请关闭此 Issues

解决方法：
````typescript
interface DataSources {
  datasources: EggSequelizeOptions[];
}
````

修改前的代码：
````typescript
interface DataSources {
  [datasources]: EggSequelizeOptions;
}
````

**Comment by dead-horse** [comment]
@whxaxes 看看

**Comment by whxaxes** [comment]
估计是个声明的 bug ，我抽空修复一下

**Comment by Richard-Choooou** [comment]
啥时候解决啊？我也是因为这个ci跑不过

**Comment by whxaxes** [comment]
eggjs/egg-sequelize#73

抱歉，最近比较忙，现在才抽出时间发了 PR

**Comment by whxaxes** [comment]
egg-squelize 已合并发布 5.0.1 ，重装一下依赖即可
