### ISSUE TITLE
egg-mongoose

### ISSUE THREAD

**Issue by Ben-zl** [eggjs/egg#366]
是否有Mongoose的插件？

**Comment by fengmk2** [comment]
Right now we don't have any mongodb plugins. And we need helps.

**Comment by atian25** [comment]
feel free to wrap a plugin for this,  raise a PR, then we can help to review.

**Comment by zhangming0305** [comment]
+1

**Comment by villins** [comment]
@atian25 这样可以？ https://github.com/villins/egg-mongoose

**Comment by atian25** [comment]
最好能以 PR 的方式来做, 这样我们好 review.  回头我写个教程吧.

简单 review 了下:

- package 是 npm 包名, 不是 egg 插件名

```
exports.mongoose = {
  enable: true,
  package: 'mongoose',
};
```

- config.default.js 里面的 jsdoc

- `app.coreLogger.info(app.model.user);` 要干掉


- 这个插件也用 app/model 目录, 跟其他插件是互斥关系么? 

cc @popomore @jtyjty99999 也看看

**Comment by jtyjty99999** [comment]
@villins 赞，可以这样搞方便review：  1.  提交到master一个readme文件 2 新开一个分支，提交代码， 发起一个mr merge到master
 
@atian25  orm框架应该都是互斥的，感觉可以出个orm框架约定了，就跟view约定似的

**Comment by atian25** [comment]
是可以, egg-sequelize 那个 PR 中有提过, 看能否沉淀一个 model 的约定规范. 可以开个 issue 脑暴下

**Comment by villins** [comment]
@jtyjty99999 需要在 eggjs 新开一个 egg-mongoose git 仓库吧？

**Comment by jtyjty99999** [comment]
@villins https://github.com/eggjs/egg-mongoose  开好啦，可以fork到你那边，提交后发起pr了
