### ISSUE TITLE
egg-bin test --watch not work

### ISSUE THREAD

**Issue by DiamondYuan** [eggjs/egg#3661]
repo https://github.com/DiamondYuan/dva-helper

git clone,yarn && yarn test-local --watch

**Comment by atian25** [comment]
目前不支持，欢迎研究下反馈回来。

**Comment by DiamondYuan** [comment]
等会儿提交 pr

**Comment by DiamondYuan** [comment]
https://github.com/TypeStrong/ts-node/issues/266#issuecomment-276650415


需要 `--watch-extensions ts --watch`

**Comment by DiamondYuan** [comment]
@atian25  有必要在 ts + watch 的情况下，自动添加 watch-extensions 吗？没必要的就算了，

**Comment by atian25** [comment]
这种自己加就好了。

可以 PR 在 README 里面说明下。

不过这问题应该不是只有 ts 的问题吧，js 的也应该类似
