### ISSUE TITLE
egg-socket.io配置了redis能起什么作用

### ISSUE THREAD

**Issue by superglg738** [eggjs/egg#3664]
egg-socket.io 配置了redis，

但是我们没有使用home这个，只用了namespace。

例子demo-egg-socket.io中是将rome保存在了redis，但也是手工保存的。

我就想了解下，socket.io这个了redis后，聊天记录、事件、或者socket等会保存在redis中吗？
因为我在redis没有看到有多余的key出来。

后者有什么参考文档？

谢谢

**Comment by ngot** [comment]
这个和 egg-socket.io 无关，建议去 socket.io 官方提问。

**Comment by jishaofeng89** [comment]
我个人觉得应该是使用在离线消息，求相互介绍

**Comment by thonatos** [comment]
- https://github.com/socketio/socket.io-redis

> Adapter to enable broadcasting of events to multiple separate socket.io server nodes.

**Comment by tingtingtinghuang** [comment]
讲下我的理解吧：）

socket.io-redis的作用和egg cluster的sticky mode类似。都是为了在多进程的时候socket.io能够正常工作。

只不过egg cluster自己实现了一套sticky，使得消息能够正确地落在同一个进程。

socket.io-redis是借助redis的[pub/sub](https://redis.io/topics/pubsub)来实现passing messages between processes 。

>有错轻拍。。
