### ISSUE TITLE
socket.io的 sticky 模式

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3669]
## What happens?
经过测试发现，egg-scripts start --daemon --title=egg-server --sticky不能使所有连接都保持到一个进程上，只能说大部分可以保持在一个进程上，不做damo了，只描述一下：在每个进程上设置定时器往前端发送process.pid,如果说所有前端得到的pid一样，才说明保持在同一进程上，但是可惜，经过测试，收到的pid不完全相同，连接根本不在一个进程上
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by thonatos** [comment]
#3653

**Comment by dearpeach** [comment]
用egg框架的服务中 启动命令加上了 --sticky，项目中还需要sticky-session吗？@thonatos
