### ISSUE TITLE
cookie死活设置不上是什么原因？

### ISSUE THREAD

**Issue by Richard-Choooou** [eggjs/egg#3670]
## What happens?
![image](https://user-images.githubusercontent.com/23492006/56962988-6a06cc00-6b8a-11e9-87ae-1e5e231f7ef6.png)
![image](https://user-images.githubusercontent.com/23492006/56963009-7d199c00-6b8a-11e9-92c9-01e1dce6b0d7.png)

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by fengmk2** [comment]
domain 设置错误了，你可以不填这个选项。

**Comment by popomore** [comment]
本地绑个域名试试

**Comment by Richard-Choooou** [comment]
@fengmk2 不填写也不行

**Comment by Richard-Choooou** [comment]
加个这玩意就好了

![image](https://user-images.githubusercontent.com/23492006/57126805-d703a700-6dc0-11e9-9e19-dc76fce1ace9.png)

**Comment by nightmareT** [comment]
是不是跨域请求的cookie无效啊？
