### ISSUE TITLE
egg-graphql 中 schemaDirectives 没有正确加载

### ISSUE THREAD

**Issue by Vincedream** [eggjs/egg#3672]
## What happens?
按照 egg-graphql 中的示例 [demo](https://github.com/eggjs/egg-graphql/tree/master/test/fixtures/apps/graphql-app/app/graphql/schemaDirectives) ，发现其schemaDirectives没有正确加载。

## Mini Showcase Repository(REQUIRED)

[showCase](https://github.com/Vincedream/schemaDirectives)

## How To Reproduce

**Steps to reproduce the behavior:**
1.设定schema
```
type User {
  id: String!
  password: String!
  name: String!
  upperName: String @upper
  lowerName: String @lowerCase
  projects: [Project!]
}
```
2.返回数据
```
return Promise.resolve(ids.map(id => ({
      id,
      name: `name${id}`,
      upperName: `name${id}`,
      lowerName: `nAme${id}`,
      password: `password${id}`,
      projects: [],
    })));
```
3. 在graphql调试页面 http://localhost:7001/graphql 中，发送
```
{ user(id: 1) { lowerName } }
```
4. 得到结果为：
```
{
  "data": {
    "user": {
      "lowerName": "nAme1"
    }
  }
}
```

**Expected behavior**
1.期待schemaDirectives其作用，得到的结果应该是：
```
{
  "data": {
    "user": {
      "lowerName": "name1"
    }
  }
}
```

## Context
- **Node Version**: 10.0.0
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by JasinYip** [comment]
我看了一下源码，应该是这段 [代码实现](https://github.com/eggjs/egg-graphql/blob/3d89ee540a09bb783a3c48b86945f68ac8ddd1cc/lib/load_schema.js#L51-L56) 的，在 `master` 分支上有这段代码，但是 [release v2.3.0](https://github.com/eggjs/egg-graphql/releases/tag/2.3.0) 中的代码不包含这段代码，owner 可以看一下是否发布出了问题。 @atian25

**Comment by JasinYip** [comment]
我细看了一下 git log，是 `2.3.0` 版本后才实现的，commit 是这个 https://github.com/eggjs/egg-graphql/commit/d4b5c655deaf28c4e7db9201a45925a76af007db ，现在应该是还没有发布，猜测会在下一版本发 @Vincedream

**Comment by atian25** [comment]
cc @jtyjty99999

**Comment by jtyjty99999** [comment]
不好意思 版本有冲突 已经解决

+ egg-graphql@2.4.0

升级之后可以

**Comment by Vincedream** [comment]
感谢！
