### ISSUE TITLE
Egg Typescript 无法解析 typings 中自定义的 .d.ts 文件

### ISSUE THREAD

**Issue by ShiningDan** [eggjs/egg#3673]
## What happens?

在项目中，希望定义一些全局的类型，所以在 typings/ 目录下创建 global.d.ts 文件
然后在 service 中通过 import { balaba } from '../../typings/global' 来引入全局类型

但是在 yarn run dev 的时候，会报错

```
Error: [egg-core] load file: /Users/xxx/Documents/project/egg-ts-simple/app/service/Test.ts, error: Cannot find module '../../typings/global'
```

想请教一下，全局的类型定义是推荐放在 typings 下面吗？这是否是一个 bug

## Mini Showcase Repository(REQUIRED)

https://github.com/ShiningDan/egg-ts-simple

## How To Reproduce

安装依赖，yarn run dev 即可复现。

## Context
- **Node Version**:8.14.0
- **Egg Version**: 2.6.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: Mac

**Comment by whxaxes** [comment]
声明文件不可以直接引入，因为它根本不会编译成 js ，这是 ts 的基础，先系统学一下 ts 把
