### ISSUE TITLE
如何设置代理IP

### ISSUE THREAD

**Issue by wuyugege** [eggjs/egg#3674]
我打算爬一个网站的数据，防止被封，要用代理IP，现在已经有一批IP地址了，请问怎么在访问对方网站时使用这些IP呢？

**Comment by atian25** [comment]
- https://eggjs.org/zh-cn/core/httpclient.html#%E8%B0%83%E8%AF%95%E8%BE%85%E5%8A%A9
- https://github.com/node-modules/urllib seach `proxy`
