### ISSUE TITLE
egg-mongoose 如何使用 mongoose 全局插件

### ISSUE THREAD

**Issue by lkspc** [eggjs/egg#3676]
全局插件需要在 Schema 定义之前就插入，目前 egg-mongoose 似乎没有提供入口。
```js
mongoose.plugin(somePlugin);
new Schema();
```

**Comment by atian25** [comment]
可以提个 PR 支持下，如可以配置 `config.mongoose.plugins = []`

临时的方案是参考 https://github.com/eggjs/egg-mongoose/blob/22d134bc4eac19f26911ce53cfb41d608a24a7e6/test/fixtures/apps/mongoose-loadModel/app.js#L5 配置 `loadModel: false` 然后自己处理

**Comment by unclexiao** [comment]
请问下使用mongoose全局插件，主要解决什么场景的问题呢。按照egg现有规范，也可以实现plugin的所有功能呀。

比如常用的时间戳，可以在Model层定义Schema时就带参数：
```javascript
  const RecordSchema = new Schema(
    {
      creator: {
        type: ObjectId,
        ref: 'User',
      },
      type: {
        // 用户使用日志
        type: String,
        enum: ['LOGIN', 'FORM',  'STAMP', 'TICKET'],
      },
      list: Array,
    },
    {
      timestamps: {
        createdAt: 'createdAt',
        updateAt: 'updateAt',
      },
    }
  );
```

再比如时间戳不满足业务，如相对复杂的数据校验，也可继续在Model层后声明钩子，比如：
```javascript
  RecordSchema.pre('save', next => {
    // 做一些事
    next();
  });

  RecordSchema.pre('updateOne', function(next) {
    // 做另外一些事
    next();
  });

```

**Comment by lkspc** [comment]
`timestamps` 其实就类似一个全局插件，目前我想实现一个 paranoid 插件，就是 deletedAt 软删除。就框架而言，这个全局插件的入口还是需要提供的

**Comment by unclexiao** [comment]
软删除确实也是刚需，不过这还是属于偏上的服务（业务）层吧？ 如果确定要写到Model底层的话，那就等待你的PR ^_^
