### ISSUE TITLE
如何在npm script构建过程中载入didLoad后的配置项目

### ISSUE THREAD

**Issue by Fnxxxxo** [eggjs/egg#3684]
给团队封装了一个模板预处理插件，支持用户自定义配置项。
现在要在项目通过npm script执行编译，需要拿到didLoad周期的配置，有什么办法读一下这部分配置？

**Comment by atian25** [comment]
静态的 config 合并分析可以用 https://github.com/eggjs/egg-utils
动态的没办法，有一种方式是用单进程的方式启动一次 egg 然后获取，但其实不妥。

你们这个问题应该是考虑把这部分配置独立出来为一个 js 文件，然后 egg 的 config 去 require 它

**Comment by atian25** [comment]
https://github.com/eggjs/egg/pull/4468
