### ISSUE TITLE
egg-redis支持模糊查询吗，或者怎样才能模糊查询？

### ISSUE THREAD

**Issue by morning-sir** [eggjs/egg#3687]
我使用 redis.get('author:*') 返回null，在命令行是正常的

抱歉没有使用模板，因为我觉得这是和环境无关的

**Comment by salamander-mh** [comment]
keys 才支持模糊查询

**Comment by morning-sir** [comment]
> keys 才支持模糊查询

原来是这样，谢谢～

**Comment by shinygang** [comment]
@morning-sir  @salamander-mh  老兄，有模糊查询的实例吗？

**Comment by unclexiao** [comment]
支持的，与终端的命令一样支持通配符，比如以下命令查询所有`user_`开头的值：
```javascript
 const keys = await redis.keys('user_*');
```
