### ISSUE TITLE
egg-ons 错误刷屏复现

### ISSUE THREAD

**Issue by qiuzhis** [eggjs/egg#3688]
@gxcsoccer 当队列消息堆积，消费的地方出现异常时，就会无限刷屏这个异常
![image](https://user-images.githubusercontent.com/9213386/57376672-3273d180-71d3-11e9-8ad5-4ba541d5f881.png)

**Comment by gxcsoccer** [comment]
```js
export default Class MsgSubscriber { ... }
```

**Comment by gxcsoccer** [comment]
> 弱弱问一句如果这个消费方法中出现异常，堆积的消息会不会造成这个异常无限打印？

如果是广播消息，会丢掉，如果是集群模式消息，重试多次以后会进入死信队列

**Comment by qiuzhis** [comment]
多谢

**Comment by qiuzhis** [comment]
谢谢。
