### ISSUE TITLE
[Feature Request] egg-sequelize 的 model

### ISSUE THREAD

**Issue by s79** [eggjs/egg#3691]
eggjs 用的挺爽的，框架本身没有做过多的事情，没有被束缚住的感觉。

## 背景
egg-sequelize 的实现是把 egg 里的 model 属性，关联到了 sequelize 对象，这样可以通过
`app.model.define(modelName)`
来定义模型，然后还会把所有的模型也附加在 model 属性上，以便通过
` app.model.ModelName`
使用它们。

这里 define 的 modelName 并不是后边大驼峰的 ModelName 的来源，ModelName 的来源是根据 model 文件的存储路径生成的，这不是主要问题，虽然我觉得二者应该有一个关联的校验或者限制，避免程序员在这上边犯错误。

我关注的问题：
app.model（即 sequelize 对象）本身是有很多属性和方法的，虽然大都是小驼峰开头不会和大驼峰的 ModelName 冲突，但也有特殊情况出现，比如我遇到的
`app.model.Model`
无法获取到预期的模型对象，而是获取到了 sequelize 的 Model 构造器。
这导致我只能更改模型名为 DataModel 以使程序正常运行，当然找原因也花了一些时间……

## 思路
将 model 设计的再纯净一些，比如只提供必要的 define 方法，然后将所有大驼峰形式的 ModelName 挂在这个对象上。

**Comment by dead-horse** [comment]
欢迎提 PR 来优化。

**Comment by s79** [comment]
以上问题出现的版本是：
egg: 2.15.1
egg-sequelize: 4.3.1

前几天升级了框架版本，发现上述问题已经不存在了，目前的版本是：
egg: 2.22.2
egg-sequelize: 5.1.0
