### ISSUE TITLE
egg-js 如何加载es6的improt/export  

### ISSUE THREAD

**Issue by wujianling** [eggjs/egg#3692]
我在编写egg项目的时候，由于之前koa2的项目都是采用babel来兼容es6的import/export的特性 在egg里面使用 require很不适应 但是布置到在哪里处理这个问题

**Comment by atian25** [comment]
1. 不要用这种非标准的特性，没啥收益
2. 可以考虑用 TS
3. 试试 `egg-bin dev --require=bable/register`

**Comment by wujianling** [comment]
谢谢  我试试 只要是TS还没来得及学习

**Comment by mtsee** [comment]
> 1. 不要用这种非标准的特性，没啥收益
> 2. 可以考虑用 TS
> 3. 试试 `egg-bin dev --require=bable/register`

import/export 不是标准特性？

**Comment by pxim** [comment]
现在怎么解决的

**Comment by atian25** [comment]
在 egg 3 之前，无法完美解决，因为 esm 无法同步加载，只能 `await import(url)`，而 egg loader 现在加载文件那块是同步过程，不发大版本改造为异步加载就没法兼容。

**Comment by pxim** [comment]
> 在 egg 3 之前，无法完美解决，因为 esm 无法同步加载，只能 `await import(url)`，而 egg loader 现在加载文件那块是同步过程，不发大版本改造为异步加载就没法兼容。

const { Low, JSONFile } = await import('lowdb');
这样写，可以了，谢谢
