### ISSUE TITLE
官网Sequelize示例代码未更新

### ISSUE THREAD

**Issue by Mavericker-1996** [eggjs/egg#3695]
## What happens?

在最新版本egg-sequelize(5.0.0)中使用findByPk代替了findById方法，而在官网的[示例](https://eggjs.org/zh-cn/tutorials/sequelize.html#%E7%BC%96%E5%86%99%E4%BB%A3%E7%A0%81)中没有更新：
![image](https://user-images.githubusercontent.com/30346283/57643541-8b38d500-75ec-11e9-816d-77c0c6bde7ef.png)
希望能够尽快修改~

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by superlbr** [comment]
sequelize更新V5，没有upgrade提示，有点坑。
transaction，query 已经不在this.ctx.model上面了

**Comment by dead-horse** [comment]
可否提 PR 帮忙修改一下？

**Comment by superlbr** [comment]
是不是因为v5自带typings？@whxaxes

**Comment by Mavericker-1996** [comment]
> 可否提 PR 帮忙修改一下？

完整实例代码用的[egg-sequelize](https://github.com/eggjs/examples/tree/master/sequelize)是4.0.1版本的，所以不会报错。
只是希望将官网文档中的findById替换为findByPk，我就是装了egg-sequelize最新版又复制了官网文档上的代码才发现报错的....

**Comment by dead-horse** [comment]
> 只是希望将官网文档中的findById替换为findByPk，我就是装了egg-sequelize最新版又复制了官网文档上的代码才发现报错的....

帮忙提个 PR 改一下有问题的地方？

**Comment by solarhell** [comment]
https://github.com/eggjs/examples/pull/106
