### ISSUE TITLE
eggsocket支持long-pulling的问题

### ISSUE THREAD

**Issue by lhc069** [eggjs/egg#3696]
在项目中使用egg-socket进行信息推送，以socketio的transport：websocket作为主要的通信模式，transport：polling 作为降级方案，我们将一次websocket的连接加上socketid作为一次有效的前后端通信，每一次的API访问都会在这一个连接（socketid）上进行消息推送，
但是在使用polling的时候Socketio出现断连并重新连的问题，主要是连接通信的时候带的socketid改变了，我猜想这个socketid在polling的条件下egg-socket没有把socketid放入redis，导致每次请求又重新生成了一个socketid。请麻烦验证下是不是这个原因？
`
 (window as any).socket = io({
      transports: ['polling'],
    });
`

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/7886114/57678206-4dbf6080-765b-11e9-892c-71522d5022d9.png)

**Comment by lhc069** [comment]
please run this below repo with npm run dev, you will see the 2 worker socket connect 404 problem
https://github.com/lhc069/egg-socket-issue

**Comment by ngot** [comment]
@lhc069 There is no code about  Socket.IO at all. It's just an empty project.

**Comment by lhc069** [comment]
sorry, the front end code is in this html file: https://github.com/lhc069/egg-socket-issue/blob/master/app/public/index.html, and for the server code is in https://github.com/lhc069/egg-socket-issue/blob/master/app/schedule/test.js, please check

**Comment by qingdengyue** [comment]
![image](https://user-images.githubusercontent.com/3230673/58061028-daf83d00-7ba6-11e9-80a9-f8678383fae7.png)
你的这个工程运行的没问题啊。

**Comment by lhc069** [comment]
@qingdengyue 你使用npm run dev 么？

**Comment by qingdengyue** [comment]
> @qingdengyue 你使用npm run dev 么？

是的,你升级一下你Node版本试试。

**Comment by LambChen** [comment]
![image](https://user-images.githubusercontent.com/12426691/58074409-c84a2c00-7bd7-11e9-8b75-9d55016097ef.png)
![image](https://user-images.githubusercontent.com/12426691/58074520-08a9aa00-7bd8-11e9-9a5c-dffd7d62f57f.png)
![image](https://user-images.githubusercontent.com/12426691/58074674-69d17d80-7bd8-11e9-810b-7db8f20a11e6.png)


node 版本为 v10.14.2，可以稳定重现～

控制台中打印的 id 为进程 id，当 polling 请求到不同进程时，会发生 Session ID unknown 的报错。

@qingdengyue

**Comment by qingdengyue** [comment]
![image](https://user-images.githubusercontent.com/3230673/58075384-2ed04980-7bda-11e9-8c2c-54e676b1a498.png)
![image](https://user-images.githubusercontent.com/3230673/58075412-44457380-7bda-11e9-9f5e-a95e3730d019.png)

复现不了~额~

**Comment by LambChen** [comment]
看起来，你的 polling 请求都到一个 worker 进程，进程编号 164128，能不能确认下你是不是启动了两个 
worker 进程？

参考：ps aux | grep egg-bin

另外，生产环境，多机部署情况下，很难保证每次 polling 请求到同一个进程，涉及到跨进程的情况，就会 Session ID unknown

**Comment by qingdengyue** [comment]
[ socket.io 协议实现需要 sticky 特性支持](https://eggjs.org/zh-cn/tutorials/socketio.html#%E9%83%A8%E7%BD%B2)

加上这个就可以了。

**Comment by lhc069** [comment]
@qingdengyue 在https域名上还是会出现polling连接失败的问题，http的域名不会出现这个问题, 请验证下？

**Comment by lhc069** [comment]
@qingdengyue 都已经配置了sticky参数

**Comment by qingdengyue** [comment]
1.HTTPS部署的启动命令是什么?
应该类似如下:
> egg-scripts start --port=443 --https.key=F:\LZ\Source\egg-testcase\egg-socket-io-case\server.key --https.cert=F:\LZ\Source\egg-testcase\egg-socket-io-case\server.crt --sticky --title=egg-server-socket-io-case

2.HTTPS环境部署之后的日志发一下


正确启动后会有这么一句:
> 2019-05-23 11:58:11,459 INFO 6356 [master] egg started on https://127.0.0.1:443 (2668ms) with STICKY MODE!

3.egg-schedule 插件的插件名是schedule,不是egg-schedule。

**Comment by lhc069** [comment]
@qingdengyue 
1. 我们这边没有用eggscript进行部署，用的是docker的自定义server.js启动的
2. ![image](https://user-images.githubusercontent.com/7886114/58243214-cf616d80-7d82-11e9-8b0e-b9b8f808190a.png)

**Comment by qingdengyue** [comment]
1.哦~   我贴的那个命令是，npm run start执行后对应的命令。Docker的server,js 也是用了egg的那个启动吧？
2.日志里看，HTTPS不是在Docker的server.js这边配置得？如果不是就得看，配置那边是怎么中转socket的了。

**Comment by lhc069** [comment]
@qingdengyue 
1. 嗯是的
2. HTTPS是在阿里云slb里配置的
![image](https://user-images.githubusercontent.com/7886114/58295950-265b5700-7e04-11e9-996f-701f0deb71dc.png)

**Comment by qingdengyue** [comment]
这个SLB的HTTPS对WebSocket支持，我只找到一篇文档：[SLB WebSocket FAQ](https://help.aliyun.com/document_detail/63421.html?spm=a2c4g.11186623.4.2.24214ee0RTwH6C)，
已经不属于egg的范畴了，建议你在阿里云提工单。

**Comment by lhc069** [comment]
@qingdengyue 为了验证不是阿里云的问题 我们在公司内部也部署了一套HTTPS，结果都一样的：直接访问ip socket连接没有问题；访问https域名socket连接连接失败...

**Comment by qingdengyue** [comment]
使用Nginx 配置节参考：[Socket Nginx ](https://eggjs.org/zh-cn/tutorials/socketio.html)，跟上面你的复现仓库，放一起。提供HTTPS配置得。因为我本地始终复现不了。配置得部分比较多，所以建议你根据你们的环境提供一份复现。
