### ISSUE TITLE
错误模板: Cannot POST  代表什么错误？

### ISSUE THREAD

**Issue by luckymore** [eggjs/egg#3698]
## What happens?
框架中会默认返回的这个模板，它代表什么错误？error_handler.js中间件也没有错误日志记录
eggjs框架中也只发现一个[notFound](https://github.com/eggjs/egg/blob/master/app/middleware/notfound.js#L25)的模板

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /v1/index/list</pre>
</body>
```

## 复现步骤，错误日志以及相关配置
压测时，暴露出来的错误。我本地请求正常

## 相关环境信息
- **操作系统**：centos70
- **Node 版本**：v8.9.2
- **Egg 版本**：2.22.2

**Comment by atian25** [comment]
你没配置这个路由吧。

请提供最小可复现仓库

**Comment by luckymore** [comment]
@atian25  没配置路由的话，返回这个404的，不会是上面个错误

```
<html>
<head></head>
<body>
  <h1>404 Not Found</h1>
</body>
</html>
```

**Comment by atian25** [comment]
请提供最小可复现仓库
