### ISSUE TITLE
egg中使用Sequelize,想要修改字段名,但是不管怎么修改,还是会使用原来第一次定义时的字段名字,如下图

### ISSUE THREAD

**Issue by 1134506391** [eggjs/egg#3705]
## What happens?
egg中使用Sequelize,想要修改字段名,但是不管怎么修改,还是会使用原来第一次定义时的字段名字,如下图

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

最开始定义的时候
![image](https://user-images.githubusercontent.com/30287598/57751917-c8e74c00-7719-11e9-9f29-c0574de67c34.png)

把tel修改成phone
![image](https://user-images.githubusercontent.com/30287598/57751924-d0a6f080-7719-11e9-8bff-845e51ba343f.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by dead-horse** [comment]
确认一下是不是传的参数没有 phone，然后这里的报错信息提示是数据库的表结构中没有 created_at 字段

**Comment by 1134506391** [comment]
已经自己解决

**Comment by LaoHu97** [comment]
@1134506391 我也遇到这个问题，怎么解决的？
