### ISSUE TITLE
关于EggJS打包的问题 

### ISSUE THREAD

**Issue by wujianling** [eggjs/egg#3707]
想询问下   egg服务端有没有关于后端代码加密打包的相关内容，类似 zeit/pkg 之类的

**Comment by atian25** [comment]
直接用它们就好了，需要根据它们的文档配置下，因为 egg 是动态 load 的，不是直接 require 的，所以它们默认不一定识别的到，需要配置下。

**Comment by wujianling** [comment]
好的  谢谢

**Comment by VincentWuShiChao** [comment]
有相应的大致配置代码吗

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/3752
