### ISSUE TITLE
开始sticky后，接口请求变得很慢

### ISSUE THREAD

**Issue by apgzs** [eggjs/egg#3709]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by apgzs** [comment]
复现
按照官网教程
 mkdir egg-example && cd egg-example
 npm init egg --type=simple
 npm i
然后以egg-scripts start --sticky 启动
问题：
开始时接口请求挺快
然后越变越慢


相关环境信息
操作系统：centos7
Node 版本：10.15.1
Egg 版本：2.15.1

**Comment by ngot** [comment]
@apgzs 提供一下可复现的代码，和具体工具步骤。我无法复现你说的wen't问题。
