### ISSUE TITLE
use method to extend egg not getter/setter

### ISSUE THREAD

**Issue by GeniusBrother** [eggjs/egg#3710]
// app/extend/context.js
const BAR = Symbol('Context#bar');

module.exports = {
  get bar() {
    // this 就是 ctx 对象，在其中可以调用 ctx 上的其他方法，或访问属性
    if (!this[BAR]) {
      // 例如，从 header 中获取，实际情况肯定更复杂
      this[BAR] = this.get('x-bar');
    }
    return this[BAR];
  },
};

This is a guide from egg. I think we should replace ‘get bar()’ with ‘getBar()’ . Because ‘cxt’ also has the same attribute ‘bar’, which can lead to conflicts

**Comment by atian25** [comment]
it just a showcase for recommended getter usage.

**Comment by GeniusBrother** [comment]
@atian25 i know, But don't you think this code is better?

**Comment by atian25** [comment]
it depends at the special sense. you could use as your wish at your project.

in this place, we just use it to show how to cache a getter, such as ctx.ip
