### ISSUE TITLE
[Feature Request] specify agent inspect port when debug

### ISSUE THREAD

**Issue by daxingplay** [eggjs/egg#3711]
## Background

I need to debug multiple Node.js App at the same time. I can use `--inspect-brk` to change App's debug port but I found that all Node.js Apps' agent process will listen to 5800 which cannot be changed, so I will get the following error and cannot debug those apps together:

```
Starting inspector on 127.0.0.1:5800 failed: address already in use
```
## Proposal

Add an option to change agent debug port.

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L204

you can use `process.env.EGG_AGENT_DEBUG_PORT`
