### ISSUE TITLE
我想要项目中连接多个数据库

### ISSUE THREAD

**Issue by 854770857** [eggjs/egg#3717]
你好  我想要项目中连接多个数据库 但是我没有连接成功 我应该怎么去配置

**Comment by codeliling** [comment]
mysql 配置：  
config.mysql = {
    clients: {
      // clientId, 获取client实例，需要通过 app.mysql.get('clientId') 获取
      db1: {
        // host
        host: '192.168.3.110',
        // 端口号
        port: '3306',
        // 用户名
        user: 'root',
        // 密码
        password: 'root',
        // 数据库名
        database: 'db1',
      },
      db2: {
        // host
        host: '192.168.3.110',
        // 端口号
        port: '3306',
        // 用户名
        user: 'root',
        // 密码
        password: 'root',
        // 数据库名
        database: 'db2',
      },
      db3: {
        // host
        host: '192.168.3.110',
        // 端口号
        port: '3306',
        // 用户名
        user: 'root',
        // 密码
        password: 'root',
        // 数据库名
        database: 'db3',
      },
      db4: {
        // host
        host: '192.168.3.110',
        // 端口号
        port: '3306',
        // 用户名
        user: 'root',
        // 密码
        password: 'root',
        // 数据库名
        database: 'db4',
      },
    },
    // 所有数据库配置的默认值
    default: {

    },

    // 是否加载到 app 上，默认开启
    app: true,
    // 是否加载到 agent 上，默认关闭
    agent: false,
  };
参考：https://eggjs.org/zh-cn/tutorials/mysql.html

**Comment by 854770857** [comment]
@codeliling 我想连接mysql和sql server这两个数据库

**Comment by 854770857** [comment]
@egg-bot 我现在单独连接mssql
报错 sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
(sequelize) Warning: MSSQL does not support INTEGER with options. Plain `INTEGER` will be used instead., '
>> Check:', https://msdn.microsoft.com/en-us/library/ms187752%28v=sql.110%29.aspx
agent.config.env = local
2019-05-21 16:05:11,291 ERROR 1409 nodejs.SequelizeAccessDeniedError: 用户 '' 登录失败。
    at Connection.connection.on.err (/Users/zhaoxiaogang/reconsitution/citic-press-marketing-cms-service/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:107:20)

**Comment by qingdengyue** [comment]
> @egg-bot 我现在单独连接mssql
> 报错 sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13
> (sequelize) Warning: MSSQL does not support INTEGER with options. Plain `INTEGER` will be used instead., '
> 
> > > Check:', https://msdn.microsoft.com/en-us/library/ms187752%28v=sql.110%29.aspx
> > > agent.config.env = local
> > > 2019-05-21 16:05:11,291 ERROR 1409 nodejs.SequelizeAccessDeniedError: 用户 '' 登录失败。
> > > at Connection.connection.on.err (/Users/zhaoxiaogang/reconsitution/citic-press-marketing-cms-service/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:107:20)

提现复现的repos. 这个错误是连接mssql的错误，不是egg的错误。

**Comment by 854770857** [comment]
@qingdengyue 谢谢问题已解决 是tedious的版本问题
