### ISSUE TITLE
egg-sequelize中如何给表名前统一加上前缀？

### ISSUE THREAD

**Issue by DizzyWu** [eggjs/egg#3719]
![image](https://user-images.githubusercontent.com/48267075/58091606-a020f400-7bfc-11e9-81bc-5790959739a3.png)
上面的图是thinkjs，egg-sequelize如何统一配置表前缀

**Comment by qingdengyue** [comment]
这个是sequelize的功能，egg-sequelize也是使用的sequelize的配置选项。所以看看sequelize本身是否支持这个功能吧。可以参考下这个： [Sequelize Hooks](http://docs.sequelizejs.com/manual/hooks.html)

**Comment by dead-horse** [comment]
如 @qingdengyue 所说，需要去看 sequelize 是否支持。

**Comment by weijiatan456** [comment]
支持chema

`config.sequelize = {
        dialect: 'mysql',
        host: '192.168.6.57',
	schema: 'solux',
};`

**Comment by hxqcc** [comment]
加了前缀之后 一直报错
