### ISSUE TITLE
前后端分离项目中，ctx.redirect跨域问题

### ISSUE THREAD

**Issue by Gong-Elory** [eggjs/egg#3721]
## Background
起因是我想在前后端分离项目中实现一个后端鉴权的功能
client: localhost:8000
server: localhost:7000
oauth:  https://example.gitlab.com/oauth/authorize

利用egg-passport和egg-passport-oauth2插件来实现鉴权

期望结果：当没有权限时，跳转到https://example.gitlab.com/oauth/authorize
现实结果：
![image](https://user-images.githubusercontent.com/22674497/58224763-88a74f80-7d51-11e9-885f-fe36b3b475c7.png)
![image](https://user-images.githubusercontent.com/22674497/58224787-a1176a00-7d51-11e9-945b-ca34aef7d481.png)
跳转到outh服务时会出现跨域问题，Origin为null.我有按照egg-security设置domain白名单，仍然无效。

我查到是redirect的问题，于是我在controller里使用

ctx.redirect('https://example.gitlab.com/oauth/authorize')直接进行跳转(没设置状态码)，发现也会存在这样的跨域问题。

如果我设置了状态码
```
// controller.js
getTest() {
    this.ctx.unsafeRedirect('http://localhost:8000/spartan_dashboard/miniprogram/template')
   this.ctx.status = 200
 }
```
此时可以前端来操作跳转，但是与我的想法相悖

请问我这样使用ctx.redirect是否有误？在这种前后端分离的场景应该怎么使用？

**Comment by qingdengyue** [comment]
请提供最小复现repos

**Comment by aaron-lb** [comment]
我也遇到了这个问题，目前也是采用设置状态码由前端来操作跳转的方式进行跳转，目前还未找到好的解决方案，请问你找到解决方案了吗

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.

**Comment by atian25** [comment]
@arron-lb 需要提供复现方式，你不会是期望通过 ajax 来 redirect 吧？

**Comment by chjiyun** [comment]
@atian25 @Gong-Elory  要设置 config 白名单和 service  this.ctx.redirect(url)，控制器 中设置 302 状态

**Comment by Notexistboy** [comment]
@Gong-Elory 请问问题解决了吗？ 我也遇到了重定向报跨域的问题
