### ISSUE TITLE
日志文件没有按天切割的问题 from egg-logrotator  release v3.1.0

### ISSUE THREAD

**Issue by festyle** [eggjs/egg#3723]
## What happens?
日志文件没有按天分割.  

## Mini Showcase Repository(REQUIRED)
1.egg-logger  

> lib/egg/logger.js

```js
constructor(options) {
    super(options);
    _**if (!path.isAbsolute(this.options.file)) this.options.file = path.join(this.options.dir, this.options.file);**_
    if (this.options.outputJSON === true && this.options.file) {
      this.options.jsonFile = this.options.file.replace(/\.log$/, '.json.log');
    }
....

```

2. egg-logrotator   v3.1.0  commit cd3969726998482df451da01eee759c883bf1552

>  app/lib/days_rotator.js

```js
async getRotateFiles() {
    const files = new Map();
    const logDir = this.app.config.logger.dir;
    const loggers = this.app.loggers;
    const loggerFiles = utils.walkLoggerFile(loggers);
    loggerFiles.forEach(file => {
      // support relative path
      **_if (!path.isAbsolute(file)) file = path.join(logDir, file);
      this._setFile(file, files);_**
    });

```

因为logger, logrotator均对相对路径的log file进行的path.join(logDir, file), 导致文件路径错误

eg: 日志配置如下
//config.default.js
config.logger={dir: "../logs", appLogName:"app.log"}

最终分割日志文件时会拼接成  ../logs/logs/app.log  ( 错误的日志文件路径)；

## Context
- node version v8.11.4
- egg version 2.22.2
- egg-logger version 2.4.1
- egg-logrotator version 3.1.0
- OS X EI Capitan 10.11.4

**Comment by festyle** [comment]
## How To Reproduce

**Steps to reproduce the behavior:**
1.配置config.default.js
`config.logger={
dir: "../logs", 
appLogName:"app.log",
coreLogName:"app.core.log",
errorLogName:"app.error.log"
}`

**Expected behavior**
1. 日志保存目录../logs下应该能看到
app.log
agent.log
agent.log.2019-05-23
app.core.log
app.error.log

只agent会按天分割.

**Comment by atian25** [comment]
config.logger.dir 应该配置为绝对路径，因为配置文件你可能是配置在应用的 config 中，可能是框架中，这时候 egg 根本不知道如何处理为绝对路径：

- 根据定义文件的 __filename 去处理？
- 根据当前启动的 cwd 去处理？
- 根据应用的 baseDir 去处理？

config 的入参有 appInfo.baseDir ，自己拼下就完了
