### ISSUE TITLE
安装项目依赖出现文件缺失

### ISSUE THREAD

**Issue by webHelang** [eggjs/egg#3724]
- [ ] I have searched the [issues](https://github.com/eggjs/egg/issues) of this repository and believe that this is not a duplicate.

### Environment
- **tnpm version**:
- **node version**:
- **egg version**: 2.22.2
- **plugin name**:
- **plugin version**:
- **platform**:
- **git repo**: http://x

### Reproduction
从2019-5-24上午开始
安装项目依赖 cnpm install

出现错误提示：Error: GET https://registry.npm.taobao.org/electron-to-chromium/download/electro
n-to-chromium-1.3.137.tgz?cache=0&other_urls=https%3A%2F%2Fregistry.npm.taobao.o
rg%2Felectron-to-chromium%2Fdownload%2Felectron-to-chromium-1.3.137.tgz response
 404 status
    at get (C:\Users\admin\AppData\Roaming\npm\node_modules\cnpm\node_modules\np
minstall\lib\get.js:57:17)
    at get.next (<anonymous>)
    at onFulfilled (C:\Users\admin\AppData\Roaming\npm\node_modules\cnpm\node_mo
dules\co\index.js:65:19)
    at <anonymous>

node:v8.9.4
npm:v6.9.0

**Comment by atian25** [comment]
跟 egg 没关系。

淘宝的源 registry.npm.taobao.org 挂了，处理中，你可以先用 npm

**Comment by webHelang** [comment]
不行，npm一样错误，早试过了。不信你试试

**Comment by webHelang** [comment]
> 跟 egg 没关系。
> 
> 淘宝的源 registry.npm.taobao.org 挂了，处理中，你可以先用 npm

npm一样错误，不信你试试。都2天了，一直安装失败

**Comment by atian25** [comment]
不是信不信的问题，这还是在 Node 依赖安装的阶段，肯定跟 egg 没关系啊。

你 Android 还没安装好的时候，你会去问腾讯为啥微信用不了么？

**Comment by webHelang** [comment]
> 不是信不信的问题，这还是在 Node 依赖安装的阶段，肯定跟 egg 没关系啊。
> 
> 你 Android 还没安装好的时候，你会去问腾讯为啥微信用不了么？

大佬，那现在是只能等是么？我在安装依赖不应该是下载文件么，这个阶段不应该就是下载路径的问题么？

**Comment by atian25** [comment]
- 要不用 npm、yarn （你试了不行的原因估计是你设置了它的 registry）
- cnpm 好像已经修复了。

我的意思是要理解问题出在哪里。

**Comment by webHelang** [comment]
> * 要不用 npm、yarn （你试了不行的原因估计是你设置了它的 registry）
> * cnpm 好像已经修复了。
> 
> 我的意思是要理解问题出在哪里。

我刚用 npm init 项目，然后安装是可以的。registry不懂哦，工作中还是传统模式，基本不接触node相关的。

**Comment by fengmk2** [comment]
重试，已经修复。

**Comment by webHelang** [comment]
> 重试，已经修复。

现在可以啦，谢谢！人生第一次遇见这事
