### ISSUE TITLE
init控制台报错

### ISSUE THREAD

**Issue by MakerGYT** [eggjs/egg#3725]
## What happens?
browser console:
``contentscript.js:1 Uncaught Error
    at contentscript.js:1``

## How To Reproduce

**Steps to reproduce the behavior:**
1.npm init egg --type=simple

## Context
- **Node Version**:10.15.3
- **Egg Version**:2.15.1
- **Platform**:ubuntu 16.04 chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by atian25** [comment]
浏览器控制台？ 检查下你的浏览器插件做了啥。这个跟 egg 没啥关系
