### ISSUE TITLE
使用egg-sequelize 的相关疑问希望得到答复

### ISSUE THREAD

**Issue by yclnycl** [eggjs/egg#3726]
1.官网上的文档写道

[这个 Model 就可以在 Controller 和 Service 中通过 app.model.User 或者 ctx.model.User 访问到了，例如我们编写 app/controller/users.js：](https://eggjs.org/zh-cn/tutorials/sequelize.html)实际上必须是ctx.model.models.xxx才可以访问到

2我的数据库没有外键约束,查阅sequelize官方文档 [如何对没有外键约束的模型创建关联关系](http://docs.sequelizejs.com/manual/associations.html#enforcing-a-foreign-key-reference-without-constraints) 然后移植到egg-sequelize上发现不起作用

**Comment by qingdengyue** [comment]
提供最小复现仓库~  方便排查~

**Comment by Jeff-Tian** [comment]
> 1.官网上的文档写道
> 
> [这个 Model 就可以在 Controller 和 Service 中通过 app.model.User 或者 ctx.model.User 访问到了，例如我们编写 app/controller/users.js：](https://eggjs.org/zh-cn/tutorials/sequelize.html)实际上必须是ctx.model.models.xxx才可以访问到
> 

第一个问题：官网文档应该没有问题，我最近也在用 `egg-sequelize`，直接用 `ctx.model.xxx` 的确可以访问到。

源代码：https://github.com/Jeff-Tian/alpha/blob/master/app/controller/users.ts
