### ISSUE TITLE
egg-ant-design-pro。build执行完后，执行 npm start报错

### ISSUE THREAD

**Issue by Johnsstt** [eggjs/egg#3727]
![图片](https://user-images.githubusercontent.com/3023129/58407981-7570e880-809f-11e9-890a-412b0e3ee478.png)

**Comment by qingdengyue** [comment]
![image](https://user-images.githubusercontent.com/3230673/58414187-419cbf80-80ad-11e9-846f-1bbc56895ea8.png)
端口被占用
