### ISSUE TITLE
[Feature Request] umi + egg + typescrip example

### ISSUE THREAD

**Issue by zhangking** [eggjs/egg#3738]
## Background

I try to create an app with umi, egg & typescript. But there are many problems. Can you provide one example?

**Comment by qingdengyue** [comment]
https://github.com/eggjs/examples/tree/master/assets-with-umi 这个？

**Comment by zhangking** [comment]
I need typescript

**Comment by popomore** [comment]
https://github.com/eggjs/examples//master/hackernews-async-ts

**Comment by zhangking** [comment]
I need umi

**Comment by qingdengyue** [comment]
> I need umi

https://github.com/eggjs/examples/pull/108

**Comment by zhangking** [comment]
@qingdengyue  你这个例子 antd的样式没有按需载进来
