### ISSUE TITLE
egg-sequelize 的d.ts有点问题，可以修复一波么 

### ISSUE THREAD

**Issue by Easy-Martin** [eggjs/egg#3741]
sequelize版本5.8.6

**Comment by Easy-Martin** [comment]
![image](https://user-images.githubusercontent.com/12482868/58929259-c0b68580-8788-11e9-990d-8fac5ea64ee1.png)

**Comment by wbget** [comment]
+1，要是有个ts的使用说明就更好了，感谢大佬。

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-sequelize/pull/73

PR 已发，使用可以参考单测中的 fixtures

**Comment by whxaxes** [comment]
@wbget  我下午弄个 example 到 egg-example，到时候直接参考那就行了

**Comment by wbget** [comment]
> @wbget 我下午弄个 example 到 egg-example，到时候直接参考那就行了

感谢啊，最近在用ts重构业务，这样的画帮了大忙了。

**Comment by wbget** [comment]
@whxaxes 感谢啊，最近在用ts重构业务，这样的画帮了大忙了。

**Comment by Easy-Martin** [comment]
@whxaxes 是不是要加一段
![image](https://user-images.githubusercontent.com/12482868/59170863-0f8e6180-8b73-11e9-8f01-be5a7303fc00.png)

**Comment by whxaxes** [comment]
@Easy-Martin  我倒不是很建议加这种通配的，你可以通过 declaration merging 的方式将 model 合并到 IModel 下：https://github.com/eggjs/egg-sequelize/pull/73/files#diff-89def924f47444da5b96487f91fea468R12

当然，这个也可以通过 egg-ts-helper 自动生成

**Comment by whxaxes** [comment]
看了一下其他用于 slot 的 interface 也有这种通配的，那我加一下保持一致

**Comment by Easy-Martin** [comment]
@whxaxes 好的多谢！

**Comment by whxaxes** [comment]
试了一下，加通配的不行，因为 Sequelize 里本身有很多属性有类型了，除非加 `[name: string]: any` ，不然都会出现类型不兼容，还是用上面我说的那种 declaration merging 的方式吧

**Comment by whxaxes** [comment]
```
interface IModel extends sequelize.Sequelize, PlainObject { }
```

跟其他 slot 一样改成这样先

**Comment by whxaxes** [comment]
example 的 PR 也提了：https://github.com/eggjs/examples/pull/109

**Comment by whxaxes** [comment]
egg-squelize 已合并发布 5.0.1 ，重装一下依赖即可
