### ISSUE TITLE
npm run tsc 时报错，导致ci构建无法通过

### ISSUE THREAD

**Issue by Richard-Choooou** [eggjs/egg#3742]
## What happens?

npm run tsc 时报以下错误导致ci无法通过，请问如何解决
![image](https://user-images.githubusercontent.com/23492006/58965713-9cd45d80-87e3-11e9-9360-ff89002efb79.png)

## 相关环境信息
- **操作系统**：mac os 10.13.6
- **Node 版本**：8.11.4
- **Egg 版本**：2.22.2

**Comment by whxaxes** [comment]
看上去是 egg-sequelize 和 urllib 的声明有点问题，还有就是 node 的声明问题（这个我们也无解了，不是我们维护的），你可以先在 `tsconfig.json` 上配置一下 `"skipLibCheck": true` 先跳过 d.ts 的类型检查，我们维护的插件的声明问题我们会尽快修复

**Comment by Richard-Choooou** [comment]
好的，感谢

**Comment by guojinchao** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/22298505/217420136-b99c6829-5426-43c7-876c-d8430d3eb334.png">
我配置了"skipLibCheck": true 依然出现 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/22298505/217420198-fbfc5896-57fe-4782-9936-888b6b6a4bda.png">

**Comment by fengmk2** [comment]
@guojinchao typescript 依赖升级到 v4 版本
