### ISSUE TITLE
npm i遇到的高危问题

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#3744]
## What happens?

npm i提示高危问题：
![image](https://user-images.githubusercontent.com/15070379/59092756-e4262f80-8944-11e9-82b9-4f0c7cfd92c9.png)

![image](https://user-images.githubusercontent.com/15070379/59092842-159efb00-8945-11e9-95a5-0f9b123fddc3.png)

![image](https://user-images.githubusercontent.com/15070379/59092863-20f22680-8945-11e9-86f4-6d1bcf12f713.png)

提示是egg-bin的问题，头一次见这种修复过程，官方是否需要做处理？

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：10.15.3
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
egg-bin 开发期，nyc 单测覆盖率，可以无视
