### ISSUE TITLE
npm start为什么启动了8各node进程

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#3745]
## What happens?

npm start为什么启动了8各独立进程？
![image](https://user-images.githubusercontent.com/15070379/59093185-e341cd80-8945-11e9-83b6-46c2ee8e6be6.png)
默认就是集群模式？

npm start是不是生产模式？开发应该用npm run dev吧？

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：10.15.3
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
对
