### ISSUE TITLE
egg-redis startup

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3748]
Here https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L55

we wait for redis in `app.beforeStart` , So when we start app but redis failed , app craches

I want to have a rate limit implementation with redis , But I want my app works event when redis is down (Just rate limit disabled)

**Comment by jtyjty99999** [comment]
I think redis is a strong dependence, so when redis failed will lead to app crash

**Comment by dead-horse** [comment]
@sm2017 maybe we can add an option like `weakDependent`, when it set to `ture`, egg-redis will not wait redis ready.

**Comment by jtyjty99999** [comment]
@dead-horse +1 we can discuss

**Comment by jtyjty99999** [comment]
may be it's a common feature for plugin..

**Comment by qingdengyue** [comment]
> @sm2017 maybe we can add an option like `weakDependent`, when it set to `ture`, egg-redis will not wait redis ready.

Maybe **,weakDependent**, default is true? when plugin failed,egg will go on. like a dependency inject, If the plugin MUST BE inject, egg failed when plugin failed.


Another problem, plugin failed,but egg start up. so the plugin should have a retry or reconnection strategy?
