### ISSUE TITLE
egg-session在service中使用出错

### ISSUE THREAD

**Issue by lijinchao2007** [eggjs/egg#375]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
详细用法和错误描述

**Comment by lijinchao2007** [comment]
this.ctx.session = {userId:user.id}

改变session，但是并没有触发保存

**Comment by dead-horse** [comment]
controller，service 和路由都写一下是怎么用的，或者你加上`DEBUG=koa-session` 这个环境变量运行一下。

**Comment by dead-horse** [comment]
看看有没有输出 session 相关的日志，另外，你用 `curl -i` 请求一下也提供一下，看看返回头是什么

**Comment by fengmk2** [comment]
直接 `this.ctx.session = {userId:user.id}` 这样好像有问题的，没有触发 getter，导致 _prevjson 没生成。https://github.com/koajs/session/blob/master/index.js#L102

应该 `this.ctx.session.userId = user.id` 这样使用

**Comment by dead-horse** [comment]
@fengmk2 不需要触发 getter 的，没有 _prevjson 也会保存：https://github.com/koajs/session/blob/master/index.js#L159

**Comment by lijinchao2007** [comment]
我的场景是：
先访问：http://localhost:7001/v1/user/info.json
返回：{"data":{"id":9,"name":"maysa1","updated":null,"logined":"2017-02-14 03:44:57","created":"2017-02-14 01:38:58"},"status":1,"desc":"success"}

再访问登录接口，更换用户：http://localhost:7001/v1/user/login.json?name=maysa&pswd=fj389ubydteg
返回的{"data":{"id":8,"name":"maysa","updated":null,"logined":"2017-02-14 12:33:30","created":"2017-02-14 01:26:03"},"status":1,"desc":"success"}

但是cookie并没有改变，我服务端的log为console.log("commit %j=>%j=>%j", prevjson, sess, opts);：commit {"userId":9,"b":2,"_expire":1489638812280,"_maxAge":2592000000}=>{"userId":9}=>{"maxAge":2592000000,"key":"EGG_SESS","httpOnly":true,"encrypt":true,"overwrite":true,"signed":false}
保存的还是上一次的cookie

**Comment by lijinchao2007** [comment]
我改了一下koa-session的中间件：
把app.context.__defineSetter__('session', function(val){
      console.log("session set json :" + JSON.stringify(val));
    if (null == val) return this._sess = false;
    if ('object' == typeof val) {
      this._sess = new Session(this, val);
        console.log("session set this %j=>%j", this, val);
      return;
    }
    throw new Error('this.session can only be set as null or an object.');
  });

移动到function* session(next)中改为this.__defineSetter__('session', function(val)就可以解决了

**Comment by lijinchao2007** [comment]
app.context.__defineGetter__定义的app的context的方法，而不是controller中的context的方法，二者不是同一个对象吧。

**Comment by lijinchao2007** [comment]
@fengmk2 this.ctx.session.userId = user.id 跟this.ctx.session = {userId:user.id}没有差别。

**Comment by lijinchao2007** [comment]
我看了generic-session的中间件，发现它们是在generator中定义session方法的
 this.__defineGetter__('session', function *()
跟我解决问题的方式是一致的。

难道是koa-session的问题？

**Comment by lijinchao2007** [comment]
上午好及时，下午怎么没动静了，大神们？

**Comment by lijinchao2007** [comment]
@fengmk2 dead-horse 上午好及时，下午怎么没动静了，大神们？

**Comment by fengmk2** [comment]
@lijinchao2007 来个可以复现的示例代码，我们跑跑看。

**Comment by atian25** [comment]
@lijinchao2007 最好是能通过 egg-init 生成一个 simple 的 showcase, 然后在上面做最小的可复现的代码, 上传到 github, 这样我们来看, 效率会更高

**Comment by lijinchao2007** [comment]
https://github.com/lijinchao2007/egg-session-exam

具体的执行步骤，例子中有说明

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-core/pull/54

**Comment by dead-horse** [comment]
感谢 @lijinchao2007 反馈

**Comment by lijinchao2007** [comment]
bug怎么产生的，能不能简单解释一下？

**Comment by dead-horse** [comment]
> bug怎么产生的，能不能简单解释一下？

创建 service 对象的时候本来应该是请求级别的，但是因为缓存问题，导致第一次请求和第二次请求共享了同一个 service 对象，导致第二次请求在 service 中调用的 `ctx` 还是第一次请求的，所以第二次请求对 session 的修改就无法生效。

**Comment by dead-horse** [comment]
@lijinchao2007 你删除依赖重新安装一下试试，应该已经修复了

**Comment by lijinchao2007** [comment]
解决了，效率很高。
