### ISSUE TITLE
如何自定义Model

### ISSUE THREAD

**Issue by kuangyanit** [eggjs/egg#3750]
egg如何自定义Model，即Model的相关配置可能是由一个配置中心下发的，而不是一个个手写？退而求其次的话该如何调用一个尚未在model文件夹中定义的model ？

**Comment by atian25** [comment]
Egg 不支持动态代码，你这类需求应该是写个泛型的 Model 里面自己想办法处理。

另，这种下发的，一旦出问题很难排查，而且无法快速回滚止血。
