### ISSUE TITLE
pkg 打包工具怎么打包eggjs

### ISSUE THREAD

**Issue by VincentWuShiChao** [eggjs/egg#3752]
## 关于eggjs使用pkg打包的问题
有相关有用的参考资源吗

**Comment by atian25** [comment]
https://github.com/atian25/egg-showcase/pull/15

egg 是动态 require 来 load 对应的 js 的，而 pkg 是分析静态 require 来找到文件列表的。

一个简单的修改，但还跑不起来，现在的问题是：

1. node_modules 和 package.json 没法打进去
2. 启动的时候，请求会报 500，原因是 config/config.default.js 也没加载到

不太确定 pkg 的 require 寻址是怎么玩的，你可以继续研究下。

PS：我们一般都是打 docker，没有这种发布到别人的场景，你可以自己研究下，或者给 pkg 那边提需求。

**Comment by atian25** [comment]
可以参考下 https://blog.csdn.net/qq_35241223/article/details/97306900
