### ISSUE TITLE
egg如何分文件记录api请求日志、sql请求日志

### ISSUE THREAD

**Issue by meicx** [eggjs/egg#3754]
不太明白分文件记录日志的实现方案，求教各位大神

**Comment by atian25** [comment]
看日志文档，customLogger

**Comment by meicx** [comment]
> customLogger

文档看了不是很清楚，定义了自定义logger之后，怎么将指定的日志信息写入该文件？

**Comment by atian25** [comment]
你 customLogger 本身就配置了对应的文件了啊，然后你代码那边调用这个 logger 来记录日志的时候，就自动写过去了。

**Comment by meicx** [comment]
> 你 customLogger 本身就配置了对应的文件了啊，然后你代码那边调用这个 logger 来记录日志的时候，就自动写过去了。

“调用这个 logger 来记录日志” 这个的代码怎么写啊，我看文档里只有获取ctx.getLogger('xxLogger') 获取之后的写入呢

**Comment by meicx** [comment]
还是说ctx.getLogger('xxLogger')返回的对象和ctx.logger对象类似，都有debug/info/warn/error等方法

**Comment by atian25** [comment]
just try
