### ISSUE TITLE
egg怎么调SqlServer数据库存储过程

### ISSUE THREAD

**Issue by pfzz** [eggjs/egg#3759]
let data = await this.service.database.RYTreasureDB("NET_PW_RejectWithdraw",obj);

nodejs.RequestError: Procedure or function 'NET_PW_RejectWithdraw' expects parameter '@strOrderID', which was not supplied.

**Comment by qingdengyue** [comment]
你用的啥库？这个没在egg的范围里面吧。

**Comment by atian25** [comment]
请找对应的插件开发者，这个不是官方支持的。
