### ISSUE TITLE
在ts环境下，麻烦 支持下 Mocha sidebar这个vscode的插件

### ISSUE THREAD

**Issue by qinyang1980** [eggjs/egg#3760]
## Background
在ts环境下，Mocha sidebar无法支持

## Proposal
跟egg-bin的配置有关，也许配置就能搞定

## Additional context
无

**Comment by atian25** [comment]
Mocha sidebar 不支持自定义启动命令。

你可以参考 egg-bin test 里面 --require 的处理，自己写个 mocha.opts 然后应该就能用它启动了。
