### ISSUE TITLE
'this.packet' maybe 'ctx.packet' in egg-io middleware packetMiddleware

### ISSUE THREAD

**Issue by axolo** [eggjs/egg#3761]
```js
module.exports = app => {
    return async (ctx, next) => {
        ctx.socket.emit('res', 'packet received!');
        // console.log('packet:', this.packet);
        consoel.log('packet:', ctx.packet);
        await next();
    };
};
```

**Comment by ngot** [comment]
I'm assuming that you were reading the document for generator style?  Essentially, we usually use `this` to represent the context of koa in Egg.js when you choose to use the generator async style. However, if you prefer the async/await style, just use the `ctx` argument instead of `this`.
