### ISSUE TITLE
[Feature Request] 定時任務需要提供參數，限定單次執行或是執行固定次數，

### ISSUE THREAD

**Issue by trylovetom** [eggjs/egg#3762]
## Background
在某些業務場景下，定時任務在 App 啟動後只需要執行一次或是固定次數，例如為期十天的資料收集、資料庫初始化等。目前是透過在資料庫層鎖來實現，希望可以在框架層的定時任務參數中提供相關設定。

## Proposal
**Proposal A**
```
module.exports = {
  schedule: {
    type: 'worker',
    interval: '10s',
    once: true // 第十秒時執行單次
  },
}
```

**Proposal B**
```
module.exports = {
  schedule: {
    type: 'worker',
    immediate: true,
    interval: '1d',
    times: 10 // 次數，從當天開始算起到第十天停止執行，共執行十次
  },
}
```

**Comment by qingdengyue** [comment]
整合一下可以加一个delay参数和times参数
delay：egg ready后多长时间触发第一次任务执行
times：总执行次数
比如应用程序启动后，多长时间开始执行第一次任务，示例如下：
```javascript
module.exports={
    schedule:{
          delay: '10m'
          times: 1
    }
}
```

**Comment by atian25** [comment]
这些指标只是单机的，感觉意义不大。

可以考虑单独写一个 egg-schedule-advanced 来自定义你们需要的 Strategy

https://github.com/eggjs/egg-schedule#schedule-type

甚至什么都不改的话，都可以自己在 task 里面计数然后 return
