### ISSUE TITLE
EGG项目如果端口不是7001，启动后用浏览器访问不到接口

### ISSUE THREAD

**Issue by ArvinSpace** [eggjs/egg#3763]
## What happens?
EGG项目如果端口不是7001，启动后用浏览器访问接口报错：
无法访问此网站 网址为 http://localhost:6666/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_UNSAFE_PORT

但是用Postman可以访问到接口
如果以7001端口启动则可以用浏览器访问到接口

## 最小可复现仓库
https://github.com/ArvinSpace/egg-shoot.git

## 复现步骤，错误日志以及相关配置
1、npm run debug，端口指定了6666
2、浏览器访问http://localhost:6666/

## 相关环境信息
- **操作系统**：Windows 10
- **Node 版本**：v8.12.0
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
可以 Google 下这个报错就知道了。

> 6666-6669这几个端口是IRC协议使用的缺省端口，存在很大的安全风险，很容易被木马程序利用，出于安全方面chrome禁止了对6666端口的访问，同样使用webkit内核的chrome缺省状态下也是禁止访问这几个端口的。
