### ISSUE TITLE
egg 项目运行时报错

### ISSUE THREAD

**Issue by chaohony** [eggjs/egg#3764]
## What happens?
![image](https://user-images.githubusercontent.com/29838799/59558405-1b22d200-9024-11e9-94eb-b24131d9b92e.png)

egg运行时首先报了一条警告
`[egg:core:ready_timeout] 10 seconds later /Users/chaohony/Desktop/mmall_egg/node_modules/_egg-watcher@3.1.0@egg-watcher/lib/init.js:15:14 was still unable to finish.`
好像是说 egg-watcher下面的lib/init.js 的某个服务无法被关闭, 但具体是什么原因也没告知

然后报了一个错误
`nodejs.Error: [ClusterClient] leader does not be active in 60000ms on port:undefined
    at Function.waitFor (/Users/chaohony/Desktop/mmall_egg/node_modules/_cluster-client@3.0.1@cluster-client/lib/server.js:238:15)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

pid: 44177
hostname: 192.168.0.103`

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
> leader does not be active in 60000ms

这个一般是你代码里面有重 CPU 的操作，导致 60s 里面连一次发心跳的机会都没有。

用 alinode 分析下 cpu 占用吧。

**Comment by chaohony** [comment]
你好   我想问下这个报错会导致什么问题呢?
因为现在虽然一直在报错,  但服务还是在正常地跑着

**Comment by atian25** [comment]
上面不是说了么，用 alinode profile 看看具体是啥函数执行比较耗时。

譬如你用了很多 Sync 的方法啥的。
