### ISSUE TITLE
在 7001 端口占用时，config.app.cluster.listen.port 参数不生效

### ISSUE THREAD

**Issue by mapleincode** [eggjs/egg#3767]
## What happens?

在 7001 端口被占用时，再启动 egg 框架，`app.config.cluster.listen.port` 参数不生效，转而监听 7002 端口。

尤其只有在 egg-bin 启动参数加入 port 参数才能改变端口。

## 最小可复现仓库

> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

```js
null
```

## 复现步骤，错误日志以及相关配置

1. 配置 config

```js
config.cluster = {
  listen: {
    port: 3000,
  },
};
```

2. 本地端口 7001 端口占用
3. `npm run dev` or `npm run start`
4. 项目启动 7002 端口监听

> 配置信息
>
> - "egg": "^2.22.2"
> - "egg-bin": "^4.13.0"

## 相关环境信息

- **操作系统**：mac os
- **Node 版本**：v8
- **Egg 版本**：2.22.2

## BUG 原因

1. egg-bin 启动时检测 7001 端口占用
2. 如果端口占用，则会添加一个 7002 端口加到启动参数中
3. egg-cluster port 默认选择 egg-bin 传入的启动参数 而不是 app.cluster.listen.port
4. 最终 egg-cluster 中的 `app_worker.js` 监听了 7002 端口

## 解决方案

在 egg-bin 检测端口占用之后，除了添加一个 port = 7002 参数之外，额外再添加一个新的参数用于声明该端口是自动生成。在自动生成端口的前提下，使用 app.config 中的监听端口。

**Comment by atian25** [comment]
已知问题，我觉得这不是一个很常见的需求，不太想对 egg-cluster 加个参数。

**Comment by mapleincode** [comment]
那能否在`config.cluster.listen` 加个参数来强制使用 config 配置的 port 作为参数呢？

**Comment by atian25** [comment]
什么情况下本地会经常启动多个项目呢？启动的时候手动传递下参数不行么？ `npm run dev -- --port=xxx`

**Comment by mapleincode** [comment]
不经影响 `npm run dev` 也影响 `npm run start` 。
我们这边的情况是测试环境有多个多个项目，一旦有人不小心启用 7001 端口就会出现如上问题。
除非在启动命令加入 port 参数。

但是发布情况下我们最好只修改 config 来实现端口切换。

**Comment by atian25** [comment]
start 不是用 egg-bin 的。

话说，你们难道是 ssh 上去启动的么？不考虑搞搞 docker 么 @_@

**Comment by mapleincode** [comment]
嗯嗯  不行就走 docker 就好了
