### ISSUE TITLE
app worker 莫名卡死？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3769]
## What happens?
在 k8s pod 里，egg js 的 worker 进程会卡死？杀掉后自动新生成的 worker 进程正常服务。

## 最小可复现仓库
抱歉，这个问题一旦重启了 app worker，就不能重现了。还没有找到 100% 重现的方法。

## 复现步骤，错误日志以及相关配置

1. k8s 里正常运行的 egg js restful 接口，过了个周末，突然发现接口超时不响应
2. `kubectl exec -it xxxx sh` 登录到 pod，用 `curl http://localhost:7001` 卡死
3. `ctrl + c` 强行退出 curl，`ps -eefw` 返回如下进程信息：
```
sh-4.2# ps -efww
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Jun14 ?        00:00:00 /bin/sh -c until curl -s localhost:15000 > /dev/null; do echo '>>> Waiting for sidecar'; sleep 2 ; done ; echo '>>> Sidecar available';     node ./backend-deploy/config-gen.js && sh startup.sh $ENTRY_FILE
root        24     1  0 Jun14 ?        00:00:00 sh startup.sh ./app.js
root        32    24  0 Jun14 ?        00:00:00 node /usr/bin/egg-scripts start --title=user-c-bff
root        43    32  0 Jun14 ?        00:00:03 node --require /usr/lib/node_modules/egg-scripts/node_modules/source-map-support/register.js /usr/lib/node_modules/egg-scripts/lib/start-cluster {"title":"user-c-bff","workers":"2","baseDir":"/app","framework":"/app/node_modules/egg"} --title=user-c-bff
root        50    43  0 Jun14 ?        00:00:25 /usr/bin/node --require /usr/lib/node_modules/egg-scripts/node_modules/source-map-support/register.js /app/node_modules/egg-cluster/lib/agent_worker.js {"framework":"/app/node_modules/egg","baseDir":"/app","workers":2,"plugins":null,"https":false,"title":"user-c-bff","clusterPort":38681}
root        61    43  0 Jun14 ?        00:00:28 /usr/bin/node --require /usr/lib/node_modules/egg-scripts/node_modules/source-map-support/register.js /app/node_modules/egg-cluster/lib/app_worker.js {"framework":"/app/node_modules/egg","baseDir":"/app","workers":2,"plugins":null,"https":false,"title":"user-c-bff","clusterPort":38681}
root        67    43  0 Jun14 ?        00:00:28 /usr/bin/node --require /usr/lib/node_modules/egg-scripts/node_modules/source-map-support/register.js /app/node_modules/egg-cluster/lib/app_worker.js {"framework":"/app/node_modules/egg","baseDir":"/app","workers":2,"plugins":null,"https":false,"title":"user-c-bff","clusterPort":38681}
root       374     0  0 14:15 pts/0    00:00:00 sh
root       384   374  0 14:16 pts/0    00:00:00 ps -efww
```
4. 从上面可以看到，母进程 43 分别启动了3个子进程：50(agent worker)，61(app worker) 和 67(app worker)。
5. `kill 50` 后 curl 仍然不通
6. `kill 61` 后 curl 仍然不通
7. `kill 67` 后 curl 通了！

```shell
sh-4.2# kill 50
sh-4.2# curl 'http://localhost:7001' -H 'Content-Type: application/json' --data-binary '{"userType":"normal","loginType":"phone","phone":{"countryCode":"86","number":"1369xxxx594"},"password":"60d3c4acc1e57fd8830b45cc16803cab4b13535d20788f1b235d2c01b17b7db0"}' --compressed
^C
sh-4.2# kill 61
sh-4.2# curl 'http: //localhost:7001' -H 'Content-Type: application/json' --data-binary '{"userType":"normal","loginType":"phone","phone":{"countryCode":"86","number":"1369xxxx594"},"password":"60d3c4acc1e57fd8830b45cc16803cab4b13535d20788f1b235d2c01b17b7db0"}' --compressed
^C
sh-4.2# kill 67
sh-4.2# curl 'http: //localhost:7001' -H 'Content-Type: application/json' --data-binary '{"userType":"normal","loginType":"phone","phone":{"countryCode":"86","number":"1369xxxx594"},"password":"60d3c4acc1e57fd8830b45cc16803cab4b13535d20788f1b235d2c01b17b7db0"}' --compressed
{"success":true,"data":{"hasBindPhone":true}}
```

## 相关环境信息
- **操作系统**：k8s pod 里执行 `uname -a` 显示： Linux xxx-94f459fc-gpcsr 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Node 版本**：v10.15.0
- **Egg 版本**：2.22.2

## 求助：
有没有什么思路，有什么好的方法查出 eggjs 的 worker 为什么卡死，以及有没有办法在碰到问题后自动重启以继续提供服务？

从日志上看，当 worker 处于卡死状态时，即使发请求，日志也不会有任何更新（可能日志也是 worker 写的，因为 worker 死了所以日志写不上？）

当 kill 掉所有的 worker 进程后，发请求会得到服务，并且日志也会打印出来。

**Comment by atian25** [comment]
接 AliNode Profile 下 CPU

**Comment by Jeff-Tian** [comment]
谢谢 @atian25 我试试看

**Comment by Jeff-Tian** [comment]
在接入 AliNode 前，在 worker 卡死的情况下，用 `top` 看的话，CPU 并不是忙碌状态：

```shell
Mem: 15451308K used, 816404K free, 276720K shrd, 1071888K buff, 5170328K cached
CPU:   0% usr   0% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 0.59 1.04 1.64 2/5774 99
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   56    38 root     S     592m   3%   2   0% /usr/local/bin/node --require /usr/local/lib/node_modules/egg-s
   57    38 root     S     591m   3%   2   0% /usr/local/bin/node --require /usr/local/lib/node_modules/egg-s
   45    38 root     S     562m   3%   1   0% /usr/local/bin/node --require /usr/local/lib/node_modules/egg-s
   38    27 root     S     522m   3%   2   0% node --require /usr/local/lib/node_modules/egg-scripts/node_mod
   27     1 root     S     283m   2%   1   0% node /usr/local/bin/egg-scripts start --title=uni-account-bff
   88     0 root     S     1608   0%   3   0% sh
    1     0 root     S     1596   0%   2   0% sh startup.sh ./app.js
   99    88 root     R     1524   0%   0   0% top
```

**Comment by Jeff-Tian** [comment]
参照 [文档](https://help.aliyun.com/knowledge_detail/60907.html?spm=a2c4g.11186623.2.11.7a1b3e54ALT04A) 部署了应用，不过在 [Node.js 性能平台] 查看，仍然显示 
" 您的应用没有实例，请参照部署向导进行部署。"

我确认部署了，是错过了什么吗？

唯一的区别是在启动时没有应用 `--daemon` 选项，因为是在 pod 里。

```
egg-scripts start 
```

另外调查发现一个问题：
![image](https://user-images.githubusercontent.com/3367820/59596965-4b08cd00-912b-11e9-98ea-fc40eefe5934.png)

实际上运行之后，结果并没有在 `node_modules`目录下找到 `alinode` 包
```
➜ nodeinstall --install-alinode ^3
[nodeinstall] downloading [====================] 100% 0.0s/2.1s 15341752/15341752 7.01MB/s

➜ ls node_modules | grep ali
agentkeepalive
egg-alinode
normalize-package-data
normalize-path
serialize-json
universalify
validate-npm-package-license

➜ node -v
v8.11.3
```

**Comment by atian25** [comment]
安装后应该是到 `node_modules/.bin/node` 下

**Comment by Jeff-Tian** [comment]
我的[个人项目](https://github.com/Jeff-Tian/alpha)部署到 heroku 上对接 alinode 成功了。

但是公司项目使用一样的方法接入。部署到 k8s pod 里，报这个错：
```
[Mon Jun 17 2019 18:45:58 GMT+0800 (China Standard Time)] Connecting to wss://agentserver.node.aliyun.com:8080...
[Mon Jun 17 2019 18:45:58 GMT+0800 (China Standard Time)] get an error: Error: write EPROTO 139895677757312:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

看上去好像是 ssl 相关的问题？

**Comment by atian25** [comment]
这是你的基础镜像的依赖问题吧

**Comment by miser** [comment]
@Jeff-Tian  看描述我们用的是类似的技术栈，我这边也会出现类似的情况，请问你那边解决了吗？

**Comment by Jeff-Tian** [comment]
@miser 我们的基础镜像是 alpine，接入 AliNode 碰到问题。https://github.com/aliyun-node/agentx/issues/108

hyj1991 推荐用 AliNode 镜像，但是 AliNode 镜像有 900 多兆。目前还是在尝试解决 alpine 镜像的问题，待这个问题解决后，我也打算生成一个火焰图看看……

@miser 你现在还能重现这个问题吗？可以生成一个 core dump 共享一下吗？我这边重启了子进程后，问题已经不能复现了……

**Comment by miser** [comment]
@Jeff-Tian 抱歉 我这边也无法重现，一阵一阵时间不确定，为了暂时不影响线上业务，我们只能检测服务心跳，有问题运维程序临时自动重启它 :(

不过这个问题还是比较大的，也在想办法积极排查，有进展和你说。

**Comment by youksi** [comment]
检查一下output文件，是否存在 open too many files？

**Comment by hyj1991** [comment]
@Jeff-Tian  这个问题还有后续么？

**Comment by Jeff-Tian** [comment]
@hyj1991 谢谢关心，目前还没有复现，现在还在排查 AliNode 接入不成功的问题……

如果以后 AliNode 接入成功了，并且复现这个问题的话，我再提交更多信息。谢谢！

**Comment by Jeff-Tian** [comment]
> 检查一下output文件，是否存在 open too many files？

请问从哪里检查 `open too many files` 信息？

**Comment by Jeff-Tian** [comment]
> 检查一下output文件，是否存在 open too many files？

@youksi

**Comment by taoWcode** [comment]
这个问题还有在跟进吗？
遇到类似都问题，上线一段时间后就会遇到有时works不响应请求情况，而且比较特殊只有详情页有这种情况（我们是SSR），首页是正常的。
经过使用jmeter500并发访问发现，首页请求不会出现超时情况，详情页请求如果出现超时情况访问详情页就会出现无响应情况，类似假死。把请求超时时间设置长一些，假死情况就会晚些出现，不够即使设置为无限长，也只能坚持10分钟左右，所以我们目前的方法就是定时重启服务。

**Comment by miser** [comment]
之前我们这边也存在类似问题，通过监控 或者 请运维同事登录的docker里生成CPU火焰图查看那个方法占用了大量的计算，或者看看网络状态是否有大量close_wait存在导致列队堵塞了

**Comment by taoWcode** [comment]
> 这个问题还有在跟进吗？
> 遇到类似都问题，上线一段时间后就会遇到有时works不响应请求情况，而且比较特殊只有详情页有这种情况（我们是SSR），首页是正常的。
> 经过使用jmeter500并发访问发现，首页请求不会出现超时情况，详情页请求如果出现超时情况访问详情页就会出现无响应情况，类似假死。把请求超时时间设置长一些，假死情况就会晚些出现，不够即使设置为无限长，也只能坚持10分钟左右，所以我们目前的方法就是定时重启服务。

*********************
找到了问题，记录下希望对后面看到的人也可以从这个方向排查。
我这块是在SSR使用的egg，如果接口请求回来没有做异常处理，当出现请求超时这种情况，就会把进程阻塞，请求还是会往这个进程发不过一直不会有回应，类似假死，现在只是把异常处理弄好，不让其堵塞。
然后使用alinode监测，cpu和内存没多大问题，我是一块块代码进行注释，然后自己压测，一直到触发点。

**Comment by miser** [comment]
> > 这个问题还有在跟进吗？
> > 遇到类似都问题，上线一段时间后就会遇到有时works不响应请求情况，而且比较特殊只有详情页有这种情况（我们是SSR），首页是正常的。
> > 经过使用jmeter500并发访问发现，首页请求不会出现超时情况，详情页请求如果出现超时情况访问详情页就会出现无响应情况，类似假死。把请求超时时间设置长一些，假死情况就会晚些出现，不够即使设置为无限长，也只能坚持10分钟左右，所以我们目前的方法就是定时重启服务。
> 
> 找到了问题，记录下希望对后面看到的人也可以从这个方向排查。
> 我这块是在SSR使用的egg，如果接口请求回来没有做异常处理，当出现请求超时这种情况，就会把进程阻塞，请求还是会往这个进程发不过一直不会有回应，类似假死，现在只是把异常处理弄好，不让其堵塞。
> 然后使用alinode监测，cpu和内存没多大问题，我是一块块代码进行注释，然后自己压测，一直到触发点。

确定Cluster模式下还是会往这个这个“假死”的进程里发送新请求吗？

我是蛮好奇你在出问题那个时间段Docker上网络列队的状态的

为什么SSR在某个API超时会把进程阻塞住

CPU一直在做计算，如果不计算怎么会“卡主”，CPU火焰图为什么看不出

我只是有很多问题探讨和好奇

**Comment by taoWcode** [comment]
> > > 这个问题还有在跟进吗？
> > > 遇到类似都问题，上线一段时间后就会遇到有时works不响应请求情况，而且比较特殊只有详情页有这种情况（我们是SSR），首页是正常的。
> > > 经过使用jmeter500并发访问发现，首页请求不会出现超时情况，详情页请求如果出现超时情况访问详情页就会出现无响应情况，类似假死。把请求超时时间设置长一些，假死情况就会晚些出现，不够即使设置为无限长，也只能坚持10分钟左右，所以我们目前的方法就是定时重启服务。
> > 
> > 
> > 找到了问题，记录下希望对后面看到的人也可以从这个方向排查。
> > 我这块是在SSR使用的egg，如果接口请求回来没有做异常处理，当出现请求超时这种情况，就会把进程阻塞，请求还是会往这个进程发不过一直不会有回应，类似假死，现在只是把异常处理弄好，不让其堵塞。
> > 然后使用alinode监测，cpu和内存没多大问题，我是一块块代码进行注释，然后自己压测，一直到触发点。
> 
> 确定Cluster模式下还是会往这个这个“假死”的进程里发送新请求吗？
> 
> 我是蛮好奇你在出问题那个时间段Docker上网络列队的状态的
> 
> 为什么SSR在某个API超时会把进程阻塞住
> 
> CPU一直在做计算，如果不计算怎么会“卡主”，CPU火焰图为什么看不出
> 
> 我只是有很多问题探讨和好奇

*************
很抱歉，其实大部分是我们开发这边的猜测，更多因为是我们对node不是很熟，所以也没太多对术语。
因为我们是做SSR的，用的是umi的SSR，会生成一个umi.server.js的文件，这是背景。
我们查看过火焰图，是有高CPU的情况，但是定位到umi.server.js这个文件函数名就是A,B,C这些，尝试去寻找这些函数太难了，然后我们发现关掉压测（我们使用jmeter来进行500并发压测），CPU恢复正常状态。但是我们手动刷新页面时页面没响应（线上环境是有时候没有反应）。但是我们通过alinode查看所有进程都是存活的，且内存和cpu都很低.
后面我们还发现
同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问（这里我们猜测的是还有走堵塞的进程，所以没有响应）。因为我们的逻辑非常简单，就是拿到数据渲染数据没有什么计算，不能往复杂的情况想。最后发现有问题的代码
```（res.data.code && res.data.code === 1）{ 请求成功 }```,当这个请求超时时，res.data是undefined会报异常，修改为```(res.data && res.data.code === 1)```就没有问题，首页没有问题就是这么写的，修改后就解决了我详情页请求无响应问题。
所以以上结果都是猜测，如果存在误导我会删除掉。

**Comment by atian25** [comment]
> 但是定位到umi.server.js这个文件函数名就是A,B,C这些

umi 的使用问题吧，编译后没 sourcemap 就定位不到具体代码。

SSR 本身就挺耗 CPU 的，主要都是在计算渲染内容。

**Comment by miser** [comment]
> > > > 这个问题还有在跟进吗？
> > > > 遇到类似都问题，上线一段时间后就会遇到有时works不响应请求情况，而且比较特殊只有详情页有这种情况（我们是SSR），首页是正常的。
> > > > 经过使用jmeter500并发访问发现，首页请求不会出现超时情况，详情页请求如果出现超时情况访问详情页就会出现无响应情况，类似假死。把请求超时时间设置长一些，假死情况就会晚些出现，不够即使设置为无限长，也只能坚持10分钟左右，所以我们目前的方法就是定时重启服务。
> > > 
> > > 
> > > 找到了问题，记录下希望对后面看到的人也可以从这个方向排查。
> > > 我这块是在SSR使用的egg，如果接口请求回来没有做异常处理，当出现请求超时这种情况，就会把进程阻塞，请求还是会往这个进程发不过一直不会有回应，类似假死，现在只是把异常处理弄好，不让其堵塞。
> > > 然后使用alinode监测，cpu和内存没多大问题，我是一块块代码进行注释，然后自己压测，一直到触发点。
> > 
> > 
> > 确定Cluster模式下还是会往这个这个“假死”的进程里发送新请求吗？
> > 我是蛮好奇你在出问题那个时间段Docker上网络列队的状态的
> > 为什么SSR在某个API超时会把进程阻塞住
> > CPU一直在做计算，如果不计算怎么会“卡主”，CPU火焰图为什么看不出
> > 我只是有很多问题探讨和好奇
> 
> 很抱歉，其实大部分是我们开发这边的猜测，更多因为是我们对node不是很熟，所以也没太多对术语。
> 因为我们是做SSR的，用的是umi的SSR，会生成一个umi.server.js的文件，这是背景。
> 我们查看过火焰图，是有高CPU的情况，但是定位到umi.server.js这个文件函数名就是A,B,C这些，尝试去寻找这些函数太难了，然后我们发现关掉压测（我们使用jmeter来进行500并发压测），CPU恢复正常状态。但是我们手动刷新页面时页面没响应（线上环境是有时候没有反应）。但是我们通过alinode查看所有进程都是存活的，且内存和cpu都很低.
> 后面我们还发现
> 同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问（这里我们猜测的是还有走堵塞的进程，所以没有响应）。因为我们的逻辑非常简单，就是拿到数据渲染数据没有什么计算，不能往复杂的情况想。最后发现有问题的代码
> `（res.data.code && res.data.code === 1）{ 请求成功 }`,当这个请求超时时，res.data是undefined会报异常，修改为`(res.data && res.data.code === 1)`就没有问题，首页没有问题就是这么写的，修改后就解决了我详情页请求无响应问题。
> 所以以上结果都是猜测，如果存在误导我会删除掉。

不不不，不需要删除，我不是来抬扛，只是讨论，因为我们的卡死问题一开始是CAT监控引起，后来从AWS切换到阿里云后，CAT也不出这个错误了。当时自己C++能力不行，没有对CAT node.js client做一些debug错过了研究机会。
看了你的描述 我在考虑是不是也和请求报错有关，当然只是思路。目前没有AWS服务器 所以我也验证不了什么。看到你出错，我是”兴奋“的，因为有验证场景的感觉。

留着蛮好 给他人提供思路，不同的问题可能引起相同的现象。

**Comment by hyj1991** [comment]
> 同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问

首页还能访问就不是阻塞，Node.js 是单工作主线程的模式，如果进程阻塞现象是 CPU 100% 且任何页面都没有响应

**Comment by miser** [comment]
> > 同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问
> 
> 首页还能访问就不是阻塞，Node.js 是单工作主线程的模式，如果进程阻塞现象是 CPU 100% 且任何页面都没有响应

我之前的问题CPU什么都是正常的，所有请求却无法处理，哪怕是主线程里的setTimeout也没有继续执行，服务器大量的Close_Wait

[火焰图](https://mlib.wang/images/summary-2019/1.png)

**Comment by hyj1991** [comment]
> 我之前的问题CPU什么都是正常的，所有请求却无法处理，哪怕是主线程里的setTimeout也没有继续执行，服务器大量的Close_Wait

查看下进程的 fd 句柄是不是打满了

**Comment by miser** [comment]
@hyj1991 好，收到。
因为之前的集群场景做了调整没办法重现了，如果在遇到按照你提供的方法查下。

当时运维帮忙看了，句柄并没有多少，就是网络Close_Wait厉害。

**Comment by taoWcode** [comment]
> > 同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问
> 
> 首页还能访问就不是阻塞，Node.js 是单工作主线程的模式，如果进程阻塞现象是 CPU 100% 且任何页面都没有响应

> > 同样是SSR，首页压测一个小时都没什么问题，详情页并发压测不到三分钟就会无响应，但这时首页依然可以正常访问
> 
> 首页还能访问就不是阻塞，Node.js 是单工作主线程的模式，如果进程阻塞现象是 CPU 100% 且任何页面都没有响应

*****
我这个是比较奇怪，首页访问畅通无阻，详情页只要报过异常的商品id偶尔就会无响应，随着时间变化发生过异常的商品id越来越多就会导致基本访问详情页就会无响应。
之前还会有一种情况，本来一个不存在的商品id，没有处理异常，server会返回来之前正常加载过的商品详情页面，通过刷新返回来的商品还不一样就像感觉访问不同的进程拿到不同的页面。
说的都是业务场景。
宜鑫大佬，这会跟我的umiSSR版本有关吗，我用的是之前的测试版，新项目用了3.0之后就没这种无响应的情况，还有测试版页面初次加载会有闪一下，像页面加载了两次一样，我没有用分包，最近常被老大提起，想升级又是大项目测试很麻烦，有解决的办法吗？

**Comment by uyoufu** [comment]
我也遇到差不多一样的问题：

``` javascript
async testCpuOccupation() {
    // 占用 CPU 10 秒钟
    const timeout = 10000
    const start = Date.now()
    while (Date.now() - start < timeout) {
      // Busy wait
      Math.sqrt(Math.random())
    }

    // 进程 id
    return { pid: process.pid }
  }
```

当调用它将该进程堵塞后，若请求正常的接口，就有概率会被转发到堵塞的进程上，导致假死。
目前还在找解决办法。
