### ISSUE TITLE
[Feature Request] change egg-prometheus http_server metrics label from `path` to `route`

### ISSUE THREAD

**Issue by dgthomugo** [eggjs/egg#3770]
## Background
When we scrape metrics from some restful api applications by egg-prometheus, we will get  thousands of useless metrics. 
For example: when I request to a route named `/areas/:id`, I will get http_response_time_ms with a label `path="areas/a1"`,  I don't want thousands of "/areas/a1, areas/a2, areas/a3 ..." metrics, that is useless. I just want the latency of route `/areas/:id`, it is more helpful to display all the metrics on grafana dashboard.

## Proposal
Change the http_server metrics label from `path` to `route`.
We can use  ctx._matchedRoute to collect the route latency instead of ctx.path.

**Comment by gxcsoccer** [comment]
> For example: when I request to a route named /areas/:id, I will get http_response_time_ms with a label path="areas/a1", I don't want thousands of "/areas/a1, areas/a2, areas/a3 ..." metrics, that is useless. I just want the latency of route /areas/:id

I feel confused, you can query by `path` label

```
http_request_total{method="GET", path="/areas/a1"}
```

**Comment by atian25** [comment]
it seems he needs to query by `ctx.pathName`

**Comment by jasine** [comment]
他要的应该是path只带match的路由，不要带上用户实际传入的参数，用户的路径参数Prometheus收集到没有意义，但是会变成很多不同的label，现有的插件上把路径参数也收集到label里了

**Comment by thomugo** [comment]
@gxcsoccer  egg-prometheus插件默认为采集的监控数据添加了`path=ctx.path`的label，但是这对rest api并不友好，因为很多同一个路由下的监控数据会因为用户传入的路径参数的不同被分散开，这些请求本来就是被同一个controller和service处理的，应该被打成一样的label。所以建议egg-prometheus中的默认label把`path=ctx.path`替换为`path=ctx._matchedRoute`

**Comment by gxcsoccer** [comment]
@thomugo 大概明白了

**Comment by gxcsoccer** [comment]
我新加一个 label => matchedRoute 吧

https://github.com/eggjs/egg-prometheus/pull/8

**Comment by atian25** [comment]
landed

**Comment by gxcsoccer** [comment]
\+ egg-prometheus@1.3.0
