### ISSUE TITLE
nunjucks模板引擎和Vue的渲染语法冲突

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#3771]
nunjucks模板引擎渲染服务端的数据时是用{{ }}语法去渲染，而Vue刚好也是用{{ }}去渲染组件内的data，在页面中使用cdn引入Vue使用时就会出现无法渲染Vue组件数据的问题，请问这种情况有没有解决方案？别叫我写spa了，整个项目就一个页面需要用Vue，不可能开多一个git仓库和端口去部署

**Comment by Leungkingman** [comment]
基础不扎实，修改下Vue的delimiters属性就好

**Comment by guohuihot** [comment]
raw
