### ISSUE TITLE
程序运行前只执行一次的操作放在那里比较合适

### ISSUE THREAD

**Issue by cckowin** [eggjs/egg#3773]
想要实现一个这样的功能，程序运行前检查程序目录下是否有install.lock这个文件，没有的话进行数据库的初始化操作，然后创建install.lock这个文件，这样的操作放在哪里比较合适啊,app.js中的beforeStart多个worker会多次执行,是不是放在agent中，这是个推荐的做法吗

**Comment by qingdengyue** [comment]
数据库不是有addSingleton嘛

**Comment by atian25** [comment]
你们都不考虑集群多机的情况么。。。

**Comment by StephenSeraph** [comment]
我都是把启动参数改为了 `"start": "egg-scripts start --workers=1 --title=egg-server-xxx"`，然后部署到容器里。
期待3.0的单进程模式…

**Comment by atian25** [comment]
你这个单进程跟他的问题不是一回事啊，他是需要全局唯一的一次初始化，这个可以用分布式锁之类的东西了。

**Comment by NicknameID** [comment]
在多机集群部署的话，目前仅仅依靠程序好像无法做到，可以使用Redis全局锁，多个实例同时去竞争同一个锁，只有竞争到锁的实例才会做具体的逻辑。不过要记得锁要设置最大TTL，防止出现意外，长时间被锁。我一般用redlock这个工具
