### ISSUE TITLE
用egg-sequelize 的migrate为什么创建不了字段的注释

### ISSUE THREAD

**Issue by jasonLaw1015** [eggjs/egg#3775]
## 用egg-sequelize 的migrate为什么创建不了字段的注释?
以下是我的迁移代码
其中role字段是有注释的，结果迁移到数据库时却没有注释？
`module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('User_tests', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER,
      },
      role: { type: Sequelize.STRING, comment: '角色名称' },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE,
      },
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('User_tests');
  },
};`

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：8.9.4
- **Egg 版本**：2.15.1
- **egg-sequelize**:4.3.1

**Comment by whxaxes** [comment]
跟 egg 无关，自行阅读 sequelize-cli 的文档：http://docs.sequelizejs.com/manual/migrations.html

**Comment by jasonLaw1015** [comment]
> 跟 egg 无关，自行阅读 sequelize-cli 的文档：http://docs.sequelizejs.com/manual/migrations.html

它好像没有那个字段注释的接口，有没有解决办法呢

**Comment by whxaxes** [comment]
@jasonLaw1015   我本机验证了一下，是支持 comment 的

![image](https://user-images.githubusercontent.com/5856440/59698144-a87f4580-9221-11e9-8ea5-d95d2717d307.png)

![image](https://user-images.githubusercontent.com/5856440/59698165-b208ad80-9221-11e9-9004-92db5ae9ef57.png)

你自己排查一下是不是哪里写错了吧

**Comment by jasonLaw1015** [comment]
@whxaxes 解决了，我把egg-sequelize@4.3.1升级到 egg-sequelize@5.1.0就好了。其他的没变

**Comment by whxaxes** [comment]
OK
