### ISSUE TITLE
Egg-cors multiple origin

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#3776]
How can I set multiple origin in egg-cors?

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-cors#usage

![image](https://user-images.githubusercontent.com/5856440/59761793-4decf480-92c8-11e9-9969-2894aac721fa.png)

Setting origin to `domainWhiteList`

**Comment by sm2017** [comment]
@whxaxes I do this but OPTIONS method return 404

**Comment by whxaxes** [comment]
show me your config

**Comment by sm2017** [comment]
```
exports.security = {
  domainWhiteList: [ 'https://server1.com' ,'https://server2.com'],
};
_```

If I send request from server1 or server2 origin everything is ok

But if I send request from anotherDomain.com origin , OPTION method return 404 , is it ok?

**Comment by whxaxes** [comment]
If you want to send request from anthoerDomain.com, you also need to add anthoerDomain.com origin to domainWhiteList like server1 or server2.

**Comment by whxaxes** [comment]
If you want to allow all request from other any domain, just set `origin: '*'`

**Comment by atian25** [comment]
recommended to config `cors.origin` instead of `domainWhiteList`

and `origin` support fn style, see https://github.com/eggjs/egg-cors/blob/master/app.js#L8

**Comment by sm2017** [comment]
@whxaxes I khow it
I talk about 404 status code, is it okay that unallowed origin get 404 statues reaponse to OPTION method?

**Comment by atian25** [comment]
@sm2017 please using `npm init egg --type=simple` to provide a mini project and upload to your GitHub, it will be more efficient.

**Comment by sm2017** [comment]
@atian25 I will send you a project to reproduce issue 

> origin support fn style

How it can be used for multiple origin?

**Comment by whxaxes** [comment]
@sm2017   try

```js
exports.cors = {
  async origin(ctx) {
    if (['http://server1', 'http://server2'].includes(ctx.url)) {
      return '*';
    }
    return false;
  },
};
```

**Comment by whxaxes** [comment]
@sm2017  Does this issue has been resolved?

**Comment by sm2017** [comment]
@whxaxes no , unfortunately I'm too busy
Wait please

**Comment by sm2017** [comment]
@whxaxes 

```
git clone https://github.com/sm2017/eggjs-issue-3776
cd eggjs-issue-3776
yarn install
yarn run dev
```

As you can see all changes is here https://github.com/sm2017/eggjs-issue-3776/commit/28dd4451b28d962bb99ab39b7e039a0a9fba3417

And we have https://github.com/sm2017/eggjs-issue-3776/blob/master/config/config.default.js#L23-L25

```
 domainWhiteList: [
      'http://localhost:7001',
      'http://localhost:7002',
      'http://localhost:7003',
    ],
```
If you GET http://localhost:7001 from domainWhiteList origin , everything is ok
![image](https://user-images.githubusercontent.com/19644997/60412095-1d208f80-9be5-11e9-86e3-d79ff3b32d1d.png)

As you can see there is no `Access-Control-Allow-Origin: <origin>` header , but I think it is ok

when you are requesting from another origin , for instance 'http://localhost:5000' , you get 404 error

Here I send request from another origin
![image](https://user-images.githubusercontent.com/19644997/60412286-c36c9500-9be5-11e9-84e5-c6cea316e403.png)

Is it okay to get 404 ??

**Comment by whxaxes** [comment]
@sm2017  You need to enable cors plugin in plugin.js ( https://github.com/sm2017/eggjs-issue-3776/blob/master/config/plugin.js )

```js
// {app_root}/config/plugin.js
exports.cors = {
  enable: true,
  package: 'egg-cors',
};
```

**Comment by sm2017** [comment]
After adding egg-cors
![image](https://user-images.githubusercontent.com/19644997/60413732-20b71500-9beb-11e9-8f51-b03b5e58f27e.png)

Still 404

**Comment by whxaxes** [comment]
If your request is sent from `http://localhost:5000`, you should add `http://localhost:5000` to domainWhiteList instead of `localhost:7001`

**Comment by sm2017** [comment]
@whxaxes , my domainWhiteList is 

```
 domainWhiteList: [
      'http://localhost:7001',
      'http://localhost:7002',
      'http://localhost:7003',
    ],
```

I don't want allow `http://localhost:5000` , no request must be send from `http://localhost:5000` origin
My problem is Why eggjs responses with 404? is it standard recommendation?

**Comment by whxaxes** [comment]
The response should not be 404.

@sm2017  I just run your repo in my computer, and I request `localhost:7001` from `localhost:33750` but the response code is 200 instead of 404.

![image](https://user-images.githubusercontent.com/5856440/60415673-5f11fb80-9c0e-11e9-8774-c54d5e6ce5cc.png)

**Comment by sm2017** [comment]
@whxaxes in your screen shot , you have 200 response from **GET** request , it is totally wrong!! as your origin is nor white listed , my screen shot is **OPTION** request and browser don't send **GET**

![image](https://user-images.githubusercontent.com/19644997/60416004-02a0e300-9bf2-11e9-93e1-ab7fc4fce8d2.png)
![image](https://user-images.githubusercontent.com/19644997/60416034-164c4980-9bf2-11e9-8d34-1a9b58bc2183.png)

**Comment by whxaxes** [comment]
@sm2017 Oh, I know... Because your request is not a simple request( see [preflight request](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests)  ), browser will send a OPTIONS request to check whether the cors request can be allowed. And eggjs only accept OPTIONS request while origin has listed in domainWhiteList, so the 404 is right.

**Comment by sm2017** [comment]
> ~The response should not be 404.~
> 
> @sm2017 I just run your repo in my computer, and I request `localhost:7001` from `localhost:33750` but the response code is 200 instead of 404.
> 
> ![image](https://user-images.githubusercontent.com/5856440/60415673-5f11fb80-9c0e-11e9-8774-c54d5e6ce5cc.png)

Why from `localhost:33750` works?

**Comment by whxaxes** [comment]
@sm2017  Because it's a simple request, it has no following condition

![image](https://user-images.githubusercontent.com/5856440/60418794-6937f800-9c16-11e9-9042-c6e860f1b844.png)

This is my code, it does not send OPTIONS request.

```js
    const xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://localhost:7001/');
    xhr.send();
    xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {
        console.info(xhr.responseText);
      }
    }
```

But if I change the code to 

```js
const xhr = new XMLHttpRequest();
    xhr.open('GET', 'http://localhost:7001/');
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send();
    xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {
        console.info(xhr.responseText);
      }
    }
```

It will send OPTIONS request because `xhr.setRequestHeader('Content-Type', 'application/json');`

You can have a try.

**Comment by whxaxes** [comment]
I think this issue can be closed, reopen if need.
