### ISSUE TITLE
linux里www用户启动失败， permission denied

### ISSUE THREAD

**Issue by GZWZC** [eggjs/egg#3779]
项目基本情况：
linux部署egg项目，是jenkins执行发布脚本，是用里www的用户start egg服务。
log日志是写在'/data/logs/eggjs'。

正常启动下，以下这5个文件权限都是www:www
/data/logs/eggjs/apiLogger.log
/data/logs/eggjs/common-error.log
data/logs/eggjs/egg-agent.log
/data/logs/eggjs/egg-schedule.log
/data/logs/eggjs/egg-web.log

正常情况下都可以正常启动，但是隔天或者隔更久的时候偶尔会报。
`Error: EACCES: permission denied, open '/data/logs/eggjs/egg-schedule.log'`
`Error: EACCES: permission denied, open '/data/logs/eggjs/apiLogger.log'`
`Error: EACCES: permission denied, open '/data/logs/eggjs/common-error.log‘`
`Error: EACCES: permission denied, open '/data/logs/eggjs/egg-agent.log'`
`Error: EACCES: permission denied, open '/data/logs/eggjs/egg-web.log'`

因为’/data/logs/eggjs/egg-schedule.log‘这些文件权限已经是root:root，所以启动报错.

虽然`chown -R www:www /data/logs/eggs`可以解决问题，但是根本问题还是没有解决。

为什么本来文件权限是www:www的，但是突然间变成root:root？是跟文件分割有关系吗？

**Comment by atian25** [comment]
egg-logrotator 会创建文件，你需要检查下为啥是 root 启动的

**Comment by GZWZC** [comment]
@atian25 好的，我ps aux检查了，的确是有root启动的egg服务，已经stop掉了。
我检查下为什么会root启动和留意下还会不会存在这个问题。谢谢
