### ISSUE TITLE
部署npm start启动后 hostname还是默认的127.0.0.1

### ISSUE THREAD

**Issue by liuhaofei** [eggjs/egg#3781]
## What happens?

部署启动后hostname还是默认的127.0.0.1，外网访问不到

## 复现步骤，错误日志以及相关配置
![微信图片_20190627121057](https://user-images.githubusercontent.com/30107153/60233965-f86ea400-98d4-11e9-8b28-bdf6fa2d9411.png)

## 相关环境信息
- **操作系统**：Ubuntu  18.04 64位
- **Node 版本**：v10.15.3
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
啥叫外网访问不到
