### ISSUE TITLE
[Feature Request] 能支持 apollographql subscriptions 吗?

### ISSUE THREAD

**Issue by imhazige** [eggjs/egg#3783]
grapgql插件是否支持?
https://www.apollographql.com/docs/react/advanced/subscriptions/

**Comment by JasinYip** [comment]
换成 apollo-graphql-koa 实现是不是就能支持了？

https://github.com/eggjs/egg/issues/3668

**Comment by Quinton** [comment]
这个 egg-graphql 的 subscription 能实现吗？

**Comment by Quinton** [comment]
https://github.com/supperchong/egg-apollo-server
