### ISSUE TITLE
egg-mysql add debug mode

### ISSUE THREAD

**Issue by yuu2lee4** [eggjs/egg#3784]
## Background
在开发的时候经常需要看输出的sql

## Proposal
egg-mysql增加debug模式，该模式下，会自动输出所有执行的sql语句

**Comment by qingdengyue** [comment]
启动命令增加: DEBUG=ali-rds:operator  就是设置这个环境变量

**Comment by koibi2** [comment]
> 启动命令增加：DEBUG = ali-rds：operator就是设置这个环境变量

不是很懂你说的怎么用，我加了也没有效果。
看了下，应该是 `EGG` 官方还没有支持：
[https://github.com/eggjs/egg/issues/2596](https://github.com/eggjs/egg/issues/2596)
~~这个功能好像鸽了~~
