### ISSUE TITLE
【新人求助】服务挂了后不能重启

### ISSUE THREAD

**Issue by newBird01** [eggjs/egg#3785]
服务昨天还能用，今天突然挂了，然后不能启动，以下是报错信息。

这是启动的报错：
![image](https://user-images.githubusercontent.com/25924193/60329216-807ea780-99c2-11e9-8482-6fcfed401f21.png)
这是marter-stderr.log
![image](https://user-images.githubusercontent.com/25924193/60329305-aefc8280-99c2-11e9-8550-09a81231b2c9.png)

**Comment by whxaxes** [comment]
看一下 common-error.log

**Comment by newBird01** [comment]
@whxaxes 这个项目没有生成common-error.log文件。

**Comment by whxaxes** [comment]
能给个能复现的案例不，这日志看不出原因

**Comment by whxaxes** [comment]
看上去是 master 进程被 kill 掉了

**Comment by newBird01** [comment]
![image](https://user-images.githubusercontent.com/25924193/60330862-f3d5e880-99c5-11e9-9e13-02c122dfb7cf.png)

**Comment by newBird01** [comment]
@whxaxes 这是我刚启动生成的日志

**Comment by newBird01** [comment]
![image](https://user-images.githubusercontent.com/25924193/60331486-5da2c200-99c7-11e9-8196-0960f659ce19.png)
我刚看了服务器系统日志，是不是内存不足引起的

**Comment by whxaxes** [comment]
这错误很明显了，内存占用超了限制。master 被 kill 掉了

**Comment by newBird01** [comment]
嗯，谢谢您哦。
