### ISSUE TITLE
有没有打包egg的方法啊，试了pkg什么的，都只能把egg的库打进去，自己的代码不行

### ISSUE THREAD

**Issue by huyu1** [eggjs/egg#3792]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by huyu1** [comment]
真不行混淆代码也行，存不存在

**Comment by MrSmallLiu** [comment]
pkg 是可以打包egg的了，我已经测通流程，你可以把你的pkg配置发一下 我帮你看一下，或者你私信联系我qq 1016817543

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/3752
