### ISSUE TITLE
egg-alinode 能不能排除无效实例？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#3793]
## What happens?

使用 egg-alinode 插件把 egg 项目接入 alinode，项目是发布到 k8s 的，每次项目发布，都会删除老的 pod，创建新的 pod。这时通过阿里云控制台的 nodejs 性能平台查看项目，就会有越来越多的实例产生。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

为了演示这个问题，我创建了一个 egg 项目，不过是发布 heroku 平台的，但也能重现这个问题：https://github.com/Jeff-Tian/alpha

![image](https://user-images.githubusercontent.com/3367820/60481812-a6a58f80-9cc1-11e9-8f02-33ea1d3ca932.png)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by hyj1991** [comment]
数据保留 24h，然后无上报信息的实例会自动消息
