### ISSUE TITLE
集成egg-graphql后 运行127.0.0.1:7001/graphql报错 Type \"Query\" was defined more than once.

### ISSUE THREAD

**Issue by chenfd99** [eggjs/egg#3795]
![报错](https://user-images.githubusercontent.com/16187185/60562263-70cbde00-9d89-11e9-8410-c251c3713c84.PNG)
![结构](https://user-images.githubusercontent.com/16187185/60562269-79bcaf80-9d89-11e9-8518-c94f15b762b7.PNG)

graphql文件夹是从 egg-graphql/test/fixtures/apps/graphql-app/app/graphql 拷贝过来的

 "dependencies": {
    "dataloader": "^1.4.0",
    "egg": "^2.15.1",
    "egg-cors": "^2.2.0",
    "egg-graphql": "^2.6.0",
    "egg-mongoose": "^3.1.3",
    "egg-scripts": "^2.11.0",
    "mongoose": "^5.5.8"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-bin": "^4.11.0",
    "egg-ci": "^1.11.0",
    "egg-mock": "^3.21.0",
    "eslint": "^5.13.0",
    "eslint-config-egg": "^7.1.0"
  },

**Comment by supperchong** [comment]
config里defaultEmptySchema设置成true了，这样就不需要再定义`type Query{}`了
```js
//config.default.js
 config.graphql = {
      defaultEmptySchema: true,
 }
```
两种解决方案
1 . graphql改成
```graphql
extend type Query{
  
}
```
2 . defaultEmptySchema设置为false
```js
//config.default.js
 config.graphql = {
      defaultEmptySchema: false,
 }
```

**Comment by chenfd99** [comment]
3k
