### ISSUE TITLE
egg-userrole设置role无效

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3797]
按照guide配置了config和router后，
请求/user，显示如下

```js
Forbidden, required role: user
```

debug发现config文件的user是undefined

如何解决？？？

**Comment by qingdengyue** [comment]
提供最小复现～

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
