### ISSUE TITLE
定时任务设置 `env: ['prod']` 时，本地 runSchedule 无法执行

### ISSUE THREAD

**Issue by masquevil** [eggjs/egg#3798]
## What happens?
app/schedule 下面的定时任务，如果设置了 `env: ['prod']`，则在手动调用 `app.runSchedule` 的时候会提示 Cannot find schedule 因而无法执行。去掉 env 则可以执行。
这对于本地调试很不方便，我们希望的只是本地不要定时跑，但是功能是否可用，还是希望可以手动跑出结果的。希望在本地环境允许手动跑。

## 最小可复现仓库
> 懒得创建仓库了…

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
> 懒得创建仓库了…

请提供复现方式，不然我们也懒得排查了。。。

**Comment by atian25** [comment]
应该是 loader 加载的时候，把不必要的文件不加载了。
你这需求，可以考虑直接在任务里面判断 env 然后 return

**Comment by masquevil** [comment]
> 应该是 loader 加载的时候，把不必要的文件不加载了。
> https://github.com/eggjs/egg-schedule/blob/bce393f66f70add9151155d16b90942bab75e89b/lib/load_schedule.js#L45
> 
> 你这需求，可以考虑直接在任务里面判断 env 然后 return
> 
> 或者单测的时候，应该 `mm.env('prod')`

感谢口嫌体正直~

我的场景是这样：

- 开发环境：给群聊机器人A发消息测试是否跑通
- 生产环境：定时任务，给群聊机器人B发消息直接使用

所以，改成 prod 应该不行，因为会直接发到正式群里。而如果在任务里判断 env 然后 return，理论上我手动 runSchedule 也会被忽略吧？

我现在的做法是，调试的时候，注释掉 env，调试完了再改回来。这种蛮容易不小心忘了…

或者也可以本地不管，也跑着这个定时任务，但是就会不停地发不必要的消息到测试群。

**Comment by atian25** [comment]
你手动 runSchedule 不也一样会发消息给群机器人。。。

在任务里面判断当前 env，来决定发给哪个机器人呗，纯业务逻辑问题。
