### ISSUE TITLE
官方模板 sequelize-ts 中的 model 类型提示为 any

### ISSUE THREAD

**Issue by Jesonhu** [eggjs/egg#3799]
## What happens?
官方模板 `sequelize-ts` 中的 model 类型提示为 `any`, 希望有正确的类型提示

## 复现步骤，错误日志以及相关配置
+ 1. 鼠标放上去 提示为 `any` 
![image](https://user-images.githubusercontent.com/18684575/60695937-40657a80-9f16-11e9-9659-cec83b4c2b76.png)
+ 2. `app.Sequelize` `app.model` 报错
![image](https://user-images.githubusercontent.com/18684575/60695992-68ed7480-9f16-11e9-97b8-aa204a574ad2.png)

## 补充说明
已执行 `npm i` 安装了相关依赖

**Comment by whxaxes** [comment]
跑了 npm dev 没

**Comment by Jesonhu** [comment]
跑了下，mysql 语法报错了，我先解决下这个问题，然后再看看类型的问题。

**Comment by Jesonhu** [comment]
@whxaxes 跑了后类型有提示了， 谢谢你的帮助。， `npm run dev` 后发现运行了 `egg-ts-helper` , 那我在自己的项目里面应该不需要再装 `egg-ts-helper` 了吧

**Comment by whxaxes** [comment]
@Jesonhu  不需要再装了，egg-bin 里内置了

**Comment by Jesonhu** [comment]
好的，再次谢谢你的帮助
