### ISSUE TITLE
can't reload worker when file change, use vagrant

### ISSUE THREAD

**Issue by alphatr** [eggjs/egg#380]
* **Node Version**: 6.9.5
* **Egg Version**: 0.11.0
* **Plugin Name**: egg-watcher
* **Plugin Version**: 2.0.0
* **Platform**: host: macOS  10.12.3 server linux

如题，在 vagrant 或者其他环境（docker，samba 等）中，容器内启动开发环境，编辑器通过共享文件的方式（或 samba 网络）的方式修改文件，`egg-watcher` 无法监听到文件改变；

看了下 `egg-watcher` 的源文件，是通过 `fs.watch` 的方式来监听文件改变的，`fs.watch` 对前面提到的几种情形无法支持，所以希望添加对应功能支持 `fs.watchFile` 这样通过轮询来监听文件改变的方式，提供给类似于 `chokidar` 的形式（综合环境和用户配置，或者更好的方式）

PS：看到代码中有 `fuzzy-change` 事件，是不是类似的功能正在完善~

**Comment by atian25** [comment]
not sure if this can help: https://github.com/adrienkohlbecker/vagrant-fsnotify

**Comment by alphatr** [comment]
@atian25 thanks;  this is a solution, but doesn't used, because it use `touch -a $file` to trigger file change in guest, and `fs.watch` doesn't detected it. I modify it to `touch -m $file`and It's works.

but I means doesn't in vagrant this specific environment, such as on network file systems or other virtualization software, because `fs.watch` has some limitation factor in some environment, so I suggest like `nodemon` still allow config to use polling when `fs.watch` not available for some reason.

**Comment by atian25** [comment]
cc @shaoshuai0102 @popomore

**Comment by atian25** [comment]
@alphatr  同时也欢迎直接用 PR 砸~  https://github.com/eggjs/egg-watcher

**Comment by shaoshuai0102** [comment]
`egg-watcher` is designed to work with different kind of developing environments. I added docs about how to add custom watching mode. Here is the pull request: https://github.com/eggjs/egg-watcher/pull/3/files

In alipay, we developed a custom watcher plugin defining our custom way of watching, and use it in production.


@alphatr Could u build such a plugin supporting vagrant(`egg-watcher-vagrant`) to solve your problem? It will be very great if so.

**Comment by alphatr** [comment]
@shaoshuai0102  I add the plugin: https://github.com/alphatr/egg-watcher-vagrant

**Comment by atian25** [comment]
@alphatr 最好是 master 只初始化一个 README, 然后 PR 来让大家 review 下. 类似 https://github.com/eggjs/egg-mongoose/pull/2

**Comment by alphatr** [comment]
@atian25 那是不是需要在 eggjs 群组下建立一个 `egg-watcher-vagrant` 仓库，然后我来发 PR？

**Comment by atian25** [comment]
可以的, 稍等

**Comment by atian25** [comment]
https://github.com/eggjs/egg-watcher-vagrant

**Comment by shaoshuai0102** [comment]
@alphatr 👍

**Comment by jtyjty99999** [comment]
赞 @alphatr

**Comment by musicode** [comment]
最新版 egg.js 在 docker 里 `npm run dev` 还是无法监听变化
