### ISSUE TITLE
一个egg-sequelize使用中的问题，

### ISSUE THREAD

**Issue by sanxiansheng** [eggjs/egg#3801]
当我在egg项目中直接使用query(sql,{model:Model})，这样去指定model的时候，他并没有按照model去构建数据

**Comment by supperchong** [comment]
你是这么写的嘛
```js
const query=this.app.model.query
query(sql,{model})
```
那可能要换成

```js
this.app.model.query(sql,{model})
```

**Comment by sanxiansheng** [comment]
现在有若干个一样的表，只是表名不同，我用this.ctx.model.XXX.findAll(),他是正常的，按照我写的构建的，然后我用this.ctx,model.query("",{...this.ctx.model.XXX.})，他就只返回查询的结果，没有按照后面的model构建

**Comment by sanxiansheng** [comment]
> 你是这么写的嘛
> 
> ```js
> const  query = this。app。模特。查询
> 查询（sql，{model}）
> ```
> 
> 那可能要换成
> 
> ```js
> 这个。app。模特。查询（sql，{model}）
> ```

现在有若干个一样的表，只是表名不同，我用this.ctx.model.XXX.findAll（），他是正常的，按照我写的构建的，然后我用this.ctx，model.query（ “”，{... this.ctx.model.XXX}），他就只返回查询的结果，没有按照后面的模型构建

**Comment by supperchong** [comment]
我这边试了下是可以的

**Comment by sanxiansheng** [comment]
> 我这边试了下是可以的
在define的时候，只取个别几个字段，可以吗，大佬可以给个例子吗，2635343666@qq.com

**Comment by sanxiansheng** [comment]
> 我这边试了下是可以的

在model里只添加了个别字段，然后用mode.query（“select * from XXX”,{model:ctx.model.Xxx}） ,得到的结果是sql查到的结果，没有按照model构建啊。。

**Comment by sanxiansheng** [comment]
> 我这边试了下是可以的

![1562390186(1)](https://user-images.githubusercontent.com/32129295/60751939-eb4a6700-9ff0-11e9-8719-7d604539d089.jpg)
![1562390223(1)](https://user-images.githubusercontent.com/32129295/60751940-ef768480-9ff0-11e9-8836-23074351e5e6.jpg)
![1562390254(1)](https://user-images.githubusercontent.com/32129295/60751942-f2717500-9ff0-11e9-88c1-b951654aacf1.jpg)

**Comment by supperchong** [comment]
按model构建的意思是指，会将结果转化成对应表的model的实例,你可以用`console.log(result)`打印看一下，这样的用话就可以调用实例的方法,比如`instance.save()`来更新数据，我猜你想的是过滤字段？

**Comment by sanxiansheng** [comment]
> instance.save()

emmm，算是吧

**Comment by sanxiansheng** [comment]
> 按model构建的意思是指，会将结果转化成对应表的model的实例,你可以用`console.log(result)`打印看一下，这样的用话就可以调用实例的方法,比如`instance.save()`来更新数据，我猜你想的是过滤字段？

emm,算是吧，可能是我的理解有问题

**Comment by sanxiansheng** [comment]
------------------ 原始邮件 ------------------
发件人: "supperchong"<notifications@github.com>;
发送时间: 2019年7月6日(星期六) 下午2:24
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "张永飞"<2635343666@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [eggjs/egg] 一个egg-sequelize使用中的问题， (#3801)




按model构建的意思是指，会将结果转化成对应表的model的实例,你可以用console.log(result)打印看一下，这样的用话就可以调用实例的方法,比如instance.save()来更新数据，我猜你想的是过滤字段？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.







你好,是这样的，有一张表比如有十个字段，我在model里写的时候，define的时候只填了五个字段，在直接使用的时候，去打印this.ctx.model.Xxx.findAll()的结果，会按照model里的字段构建数据，但是我在用this.ctx.model.query("查询另一张字段完全相同的表",{model:this.ctx.model.Xxx})的结果打印,还是他查到的是个字段，不是五个。我这样不知道是不是说清楚了，也不知道我这样做是不是对的做法

**Comment by supperchong** [comment]
最好的做法是，一个表的字段都写在model里，然后使用orm的方法[findAll,findOne,findByPk,update,destroy](http://docs.sequelizejs.com/manual/querying.html)，直接写sql不方便维护，如果想自定义字段可以添加attributes
```js
this.ctx.model.User.findAll({
   where:{},
  attributes:['field',''field2']
})
```
如果想排除字段
```js
this.ctx.model.User.findAll({
   where:{},
  attributes:{
     exclude: ['field',''field2']
  }
})
```

**Comment by sanxiansheng** [comment]
！！！第一次用，还没了解到这么多，非常感谢~~~

**Comment by sanxiansheng** [comment]
> 最好的做法是，一个表的字段都写在model里，然后使用orm的方法[findAll,findOne,findByPk,update,destroy](http://docs.sequelizejs.com/manual/querying.html)，直接写sql不方便维护，如果想自定义字段可以添加attributes
> 
> ```js
> this.ctx.model.User.findAll({
>    where:{},
>   attributes:['field',''field2']
> })
> ```
> 
> 如果想排除字段
> 
> ```js
> this.ctx.model.User.findAll({
>    where:{},
>   attributes:{
>      exclude: ['field',''field2']
>   }
> })
> ```

！！！第一次用，还没了解到这么多，非常感谢~~~
