### ISSUE TITLE
egg-static需要定制gzip等配置

### ISSUE THREAD

**Issue by maweimaweima** [eggjs/egg#3804]
国外的每台服务器都有流量的限制，且较贵。
只有egg内部gzip才能节流。
但发现static开发人员是完全不可配置，是个问题。
导致现在只能重新写个middleware或者插件。
希望能增加以下配置的扩展
```
// config.prod.ts 
exports.static = {
    gzip: true,
   ...
  };
```

**Comment by atian25** [comment]
- 静态资源为啥不放到 CDN 去？
- 你说的这个配置是支持的，[egg-static](https://github.com/eggjs/egg-static) 都写了内部使用的是 [static-cache](https://github.com/koajs/static-cache)
