### ISSUE TITLE
error [HPE_HEADER_OVERFLOW] occurred: Parse Error

### ISSUE THREAD

**Issue by JimmyDaddy** [eggjs/egg#3807]
## What happens?
GET 请求参数过长时会报
```
error [HPE_HEADER_OVERFLOW] occurred: Parse Error
```
## Context
- **Node Version**: v12.0.0
- **Egg Version**: 2.21.0
- **Platform**:  CentOS Linux release 7.6.1810 (Core)

egg-scripts 能不能支持 `--max-http-header-size` 参数或者其他 Nodejs 的参数设定？

**Comment by atian25** [comment]
1. 不要过长，即使你 Node 这层过了，你也可能在某个运营商的路由器那一层被截断了。
2. 可以试下 `--node-options--max-http-header-size` 或 NODE_OPTIONS 这个环境变量。
  - https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L175
  - https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by PossibleMaybe** [comment]
上面方法确实可行，本地调试用法是这样的npm run dev -- --node-options--max-http-header-size=1048576
