### ISSUE TITLE
[Feature Request] 增加对 annotation 的支持

### ISSUE THREAD

**Issue by ninozhang** [eggjs/egg#3808]
## Background
在很多业务开发的场景下，接口可能会用到很多通用的功能，比如缓存、权限控制、请求追踪等等。
以往的做法是在业务代码里面插入相应的逻辑，比如读写缓存、权限判断等等，增加了这些代码又进一步的让业务代码更加冗长。
因此我们参照了 annotation 的方式，将这类既通用又有接口级别差异的逻辑通过 annotation 的方式进行配置。

## Proposal
目前我们的实现是自己做了个中间件，如果能集成到框架或者官方提供 annotation 的插件就更好了。

## Additional context
举几个例子。
还有更多使用场景的，欢迎讨论。

### 接口增加缓存
```
/**
 * @Method(search);
 * @cache.enable(true);
 * @cache.expire(600);
 * @cache.key.strategy(rest_api_with_query);
 */
```
### 更新或删除的时候清空缓存
```
/**
 * @Method(delete);
 * @cache.clear(true);
 * @cache.enable(true);
 * @cache.key.strategy(rest_api);
 */
```
### 指定接口应用的鉴权规则
```
/**
 * @Method(search);
 * @guard.permission('base:dict:manage');
 */
```
### 抽样追踪接口请求
```
/**
 * @Method(create);
 * @trace.enable(true);
 * @trace.sampling.rate(0.2);
 */
```

**Comment by atian25** [comment]
1. 目前 JS 没有 Annotation，只有一个 Decorators，但目前还只是 Stage 2，且还大变过 2 次。我们不会考虑把非 LTS 的能力集成进来。
2. 这个功能不是 egg 的核心，完全是可以通过插件和单独的类库来支持的，没必要强求集成到 egg 里面。

**Comment by ninozhang** [comment]
1. 是呀，所以我们目前的实现是自己去解析的，哈哈。
1. 目前我们的实现也是做了个 annotation 插件正在用着。

这里提出来是写一下我们这边的用法，如果觉得有意思的话可以参考下，
实际使用中带来非侵入的效果挺爽的，哈哈~

**Comment by atian25** [comment]
挺好的，可以写点文章分享下你们的实践经验。这个先关了。
