### ISSUE TITLE
请问如何关闭cluster 模式，希望有一份整体配置文档参考

### ISSUE THREAD

**Issue by ckken** [eggjs/egg#381]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by atian25** [comment]
为何要关闭 cluster 模式？

**Comment by ckken** [comment]
比较适合小项目使用，很多都是跑单线程，还有核数的设定，还有定时任务，队列等

**Comment by dead-horse** [comment]
1. egg 的进程模型决定了它一定是 cluster 模式运行的，但是你可以限制它只有一个 worker： https://eggjs.org/zh-cn/advanced/cluster.html
2. egg 的 cluster 模式下也支持定时任务：https://eggjs.org/zh-cn/basics/schedule.html
3. 项目大小于是否用 cluster 模式没有关系，最终的资源占用是与业务量有关的。

**Comment by atian25** [comment]
egg 的多进程模型，最小开启一个 master，一个 agent，一个 worker。

虽然不推荐，但你要真想配置，写个启动文件，传递 worker 数量即可。

https://github.com/eggjs/egg/issues/345#issuecomment-278644596

**Comment by ckken** [comment]
涉及到多进程与 监听队列会出现重复执行，我看了worker all 是所有执行，是否有考虑到同时执行的解决方案？

**Comment by dead-horse** [comment]
`type: 'worker'` 是单进程执行的定时任务，如果考虑到队列推送，也可以做到 agent 进程监听队列推送，然后下发给一个 worker 进程执行，我们内部大量这类用法。

**Comment by atian25** [comment]
可以看下 egg-schedule 文档和源码，很容易可以扩展自己的调度策略

**Comment by ckken** [comment]
666666

**Comment by kyleCodein** [comment]
是否可以用agent监听队列，然后跟随机一个worker通信，去执行，就不会有重复执行的情况 @ckken
