### ISSUE TITLE
使用socket.io时如何在恰当的时间获取房间中的客户端列表呢?

### ISSUE THREAD

**Issue by coolucifer** [eggjs/egg#3810]
## What happens?
按照官方文档的方式获取房间中的客户端列表时无法获取当前用户

## Mini Showcase Repository(REQUIRED)
![image](https://user-images.githubusercontent.com/23123540/60948814-60d27200-a326-11e9-808f-48a2d4cd9888.png)

复现项目链接
https://github.com/coolucifer/egg_bug_report

**Expected behavior**
1.可以获取当前房间的所有用户

## Context
- **Node Version**:10.15.3
- **Egg Version**:2.22.2
- **Plugin Name**:egg-socket.io
- **Plugin Version**:4.1.6
- **Platform**:windows10

**Comment by coolucifer** [comment]
![image](https://user-images.githubusercontent.com/23123540/61270504-789d7080-a7d4-11e9-9d18-0579894e057d.png)
按照socket.io官网的例子调用api的话是没有问题的

**Comment by coolucifer** [comment]
![image](https://user-images.githubusercontent.com/23123540/61356393-d3080100-a8a8-11e9-9602-f5f05bdf5591.png)
看样子是在connect触发之前就进到了auth.js里, 卡在了箭头指的地方, nsp.connected[id]为undefined

**Comment by ngot** [comment]
按照 socket.io 官方的用法， 也是不可以的，因为：

- auth 中间件是连接中间件，是在连接建立前执行的逻辑，用户处理一些建立连接过程中初始化工作。此时连接尚未建立，数据都还是不存在的。https://github.com/coolucifer/egg_bug_report/blob/master/config/config.default.js#L8 你配置成了连接中间件。
- 你的那个例子并不是连接中间件，而是 onconnetion 之后的 event handler ，连包中间件都不是。在 event handler 中，连接已经建立完毕，初始化工作已经完成了，所以没有问题。

针对这个场景，有多种解决办法，比如你的例子当中，把代码放到event handler或者包中间件，缺点是回到导致 join 多次。

另一种方法，还是种连接中间件做：

```js
module.exports = () => async (ctx, next) => {
  const { app, socket } = ctx;
  const nsp = app.io.of('/');
  const room = 'default';

  // 在连接之前，注册一个一次性的连接成功监听器，连接成功再去 join
  nsp.once('connection', () => {
    socket.join(room, () => {
      nsp.in(room).clients((err, clients) => {
        console.log('1.join callback: ', clients);
      });
    });
  });

  await next();

  console.log('user left');
};
```

**Comment by coolucifer** [comment]
@ngot 谢谢回复. 既然这样的话官网的socket.io示例是不是需要改动一下, 还是说因为某些地方的不同导致官网示例和我的代码中join之后直接获取clients的结果会不一样呢?
