### ISSUE TITLE
[Feature Request] egg-logger的文档希望更全面和及时更新，谢谢

### ISSUE THREAD

**Issue by ArvinSpace** [eggjs/egg#3812]
看代码和history已经支持挺多功能，但是没有在文档中体现，导致很多配置和功能要看代码才能发现，但是始终是不方便的，egg-logger的github页更是相当于空白，内容不全更新不到位，希望官方能完善这部分文档，谢谢。

**Comment by atian25** [comment]
具体指哪一块？

**Comment by ArvinSpace** [comment]
> 具体指哪一块？

比如我看egg-logger的customFormatter和formatter就没有文档，还有其他的一些配置和使用也没有文档，不放文档出来可能大家都不知道有这些功能

**Comment by atian25** [comment]
好像是漏了，可以提 PR 优化下。
