### ISSUE TITLE
[Feature Request] stdout.log.20190710.115056这种启动就自动生成的日志可以删除或者配置不生成吗

### ISSUE THREAD

**Issue by ArvinSpace** [eggjs/egg#3813]
stderr.log.20190710.115056
stdout.log.20190710.115056
请问这种启动时就自动出来的日志怎么删除呢
或者怎么配置可以不出来这些文件，且日志内容一直append到stderr.log和stdout.log

**Comment by atian25** [comment]
如果在 daemon 模式，会有 master-stdout 这样的日志，便于启动时的问题分析。

https://github.com/eggjs/egg-scripts

**Comment by popomore** [comment]
这个是为了保留之前部署的日志，否则不好排查，可以使用 crontab 来删除日志
