### ISSUE TITLE
是否会考虑引入类似fastify的json schema机制？

### ISSUE THREAD

**Issue by xland** [eggjs/egg#3817]
## Proposal
一方面是为了提升性能吧，fastify文档里说靠这个能提升1~4倍的吞吐量；

再一个就是方便的校验请求提交的数据是否合法，
我也不清楚egg在这方面有没啥最佳实践，想来想去要做统一的校验机制也是得实现json schema
下面补充两个fastify文档的截图

## Additional context
![image](https://user-images.githubusercontent.com/2980915/61177652-3d047a00-a60d-11e9-8ad0-663969837e9c.png)
https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#serialization

![image](https://user-images.githubusercontent.com/2980915/61177692-c2882a00-a60d-11e9-8991-971f879e916c.png)
https://github.com/fastify/fastify/blob/master/docs/Validation-and-Serialization.md#error-handling

**Comment by dead-horse** [comment]
可以自行引入 https://github.com/fastify/fast-json-stringify 来输出响应。

**Comment by xland** [comment]
@dead-horse ,
哦，谢谢！

那么说不打算在eggjs里提供这一块的支持啦？
提升性能什么的，到无所谓啦
如果能提供一个方便的数据合法性校验机制，最好了。
毕竟所有项目都会用到。
感觉普适性的功能如果框架能提供最好了，不用每次都自己搞一遍。

个人的建议...

**Comment by atian25** [comment]
它的机制就是要提供一个 scheme。校验跟序列化不是很强关联。

你可以写个插件分享出来就好了。
