### ISSUE TITLE
自定义traceId无效

### ISSUE THREAD

**Issue by meicx** [eggjs/egg#3822]
自定义tracer无效
my_tracer.js
![image](https://user-images.githubusercontent.com/19547619/61212097-d6c64700-a733-11e9-8451-c710fd676301.png)
config.default.js
![image](https://user-images.githubusercontent.com/19547619/61212137-f0678e80-a733-11e9-8ec1-e0926cee931f.png)
plugin
![image](https://user-images.githubusercontent.com/19547619/61212148-f8273300-a733-11e9-9b7a-a23e98da7f6f.png)
但是在middleware中通过ctx.traceId;获取traceId仍为原有的traceId。我想要自定义这个traceId应该怎么修改？

**Comment by qingdengyue** [comment]
config.default.js
![image](https://user-images.githubusercontent.com/3230673/61607570-eb4d9680-ac81-11e9-84f6-bee208d6a086.png)
plugin.js
![image](https://user-images.githubusercontent.com/3230673/61607577-f86a8580-ac81-11e9-9220-3a6079c66b44.png)
middleware/traceid.js
![image](https://user-images.githubusercontent.com/3230673/61607596-0fa97300-ac82-11e9-8e21-ad80061cc305.png)


可以正常获取到traceId 😄

**Comment by qingdengyue** [comment]
config.default.js
![image](https://user-images.githubusercontent.com/3230673/61607570-eb4d9680-ac81-11e9-84f6-bee208d6a086.png)
plugin.js
![image](https://user-images.githubusercontent.com/3230673/61607577-f86a8580-ac81-11e9-9220-3a6079c66b44.png)
middleware/traceid.js
![image](https://user-images.githubusercontent.com/3230673/61607596-0fa97300-ac82-11e9-8e21-ad80061cc305.png)


可以正常获取到traceId 😄

**Comment by meicx** [comment]
> config.default.js
> ![image](https://user-images.githubusercontent.com/3230673/61607570-eb4d9680-ac81-11e9-84f6-bee208d6a086.png)
> plugin.js
> ![image](https://user-images.githubusercontent.com/3230673/61607577-f86a8580-ac81-11e9-9220-3a6079c66b44.png)
> middleware/traceid.js
> ![image](https://user-images.githubusercontent.com/3230673/61607596-0fa97300-ac82-11e9-8e21-ad80061cc305.png)
> 
> 可以正常获取到traceId 😄

能贴一下你的my_tracer.js文件怎么写的不

**Comment by meicx** [comment]
我也能通过ctx.traceId获取到 但不是我自定义的traceId

**Comment by qingdengyue** [comment]
你文件里写错了是：**get traceId**

**Comment by yeongjet** [comment]
[官方例子](https://www.npmjs.com/package/egg-tracer)是不是写错了
```js
class MyTracer extends Tracer {
  get tracerId() { // 应该是traceId
    return `${counter++}-${Date.now()}-${process.pid}`;
  }
}
```
@fengmk2
