### ISSUE TITLE
post请求携带参数时404

### ISSUE THREAD

**Issue by nightmareT** [eggjs/egg#3824]
背景： 本人使用vue做了个前端应用，egg做后端，调试时关闭CSRF，启动本地服务器调试，中间件默认设置CORS *，利用axios和fetch做post请求时发现，不携带参数时，请求成功，
下图为前端代码
![image](https://user-images.githubusercontent.com/11377022/61262896-9a3d2e80-a7b9-11e9-9beb-43cff70a564e.png)
携带参数时直接返404，且后端断点发现没有到达路由 只在中间件处理时就已经404，下图为前端代码，两个过程后端代码无变化
![image](https://user-images.githubusercontent.com/11377022/61262952-cbb5fa00-a7b9-11e9-8388-661a5544fee5.png)
请问这是什么原因
## Context
- **Node Version**:8.2.0
- **Egg Version**: 2.15.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
withCredentials
