### ISSUE TITLE
如何异步获取配置后再启动应用？

### ISSUE THREAD

**Issue by forzalianjunting** [eggjs/egg#3828]
目前我们的逻辑是启动前需连接 zookeeper 获取配置信息（比如端口号、下游服务地址等），成功后再启动应用，如何实现呢？

**Comment by gaoyangy** [comment]
我这边也遇到过类似，采用的是脚本读取后，启动应用

**Comment by ngot** [comment]
参考 https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L53 ， 用 beforeStart 来实现。
