### ISSUE TITLE
eggjs只需要抓取数据和处理逻辑，请问要怎么关闭ws 监听 以及 http 端口监听呢？

### ISSUE THREAD

**Issue by hbin001** [eggjs/egg#3830]
Debugger listening on ws://127.0.0.1:9229/92aec8d6-744d-43bf-8903-a3e635cfdc5f
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2019-07-19 15:48:47,493 INFO 4936 [master] node version v11.2.0
2019-07-19 15:48:47,495 INFO 4936 [master] egg version 2.22.2
Debugger listening on ws://127.0.0.1:5800/d2fc7c78-c3bd-4c1a-8e61-bedfdf86747b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
2019-07-19 15:48:48,607 INFO 4936 [master] agent_worker#1:4937 started (1108ms)
Debugger listening on ws://127.0.0.1:9230/036a61fc-6a3b-4701-b0a0-e833b0888d32
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
2019-07-19 15:48:50,025 INFO 4936 [master] egg started on http://127.0.0.1:7007 (2530ms)

如上所示，请问如何不监听 listening on ws://127.0.0.1:9229/、 listening on ws://127.0.0.1:5800/、http://127.0.0.1:7007？

**Comment by atian25** [comment]
ws 是 Node 的 debug，你不开启 inspect 就可以了。

http 的开着不对外服务是没有任何影响的。
