### ISSUE TITLE
HttpClient发起数组请求时的接口拼接问题

### ISSUE THREAD

**Issue by web-kubor** [eggjs/egg#3832]
## What happens?
**内部接入关于数组查询的接口，
希望的拼接格式如下（可测试地址）**
http://test.api.dev.catone-vip.com/inner/api/v1/product/products/get-by-ids-new?ids[]=234&ids[]=235

**目前提供的方式，url拼接为**
http://test.api.dev.catone-vip.com/inner/api/v1/product/products/get-by-ids-new?ids=234,346

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：>=8.0.0
- **Egg 版本**：^2.15.1

**Comment by popomore** [comment]
应该是 ctx.queries
