### ISSUE TITLE
动态创建定时任务无效？

### ISSUE THREAD

**Issue by Yukyi** [eggjs/egg#3837]
我要根据数据库中的某个时间更改数据库的某个数据
module.exports = app => {
  return {
    schedule: {
      interval: app.config.cacheTick,
      type: 'all',
    },
    async task(ctx) {
      const res = await ctx.curl('http://www.api.com/cache', {
        contentType: 'json',
      });
      ctx.app.cache = res.data;
    },
  };
};
我在app.js中写了
async willReady() {
        this.app.config.cacheTick = await this.app.mysql.get('update', {id:1});
}
从数据库中动态获取这个定时任务的时间，但是interval取不到值，好像是初始化的很早

按api文档中这么动态创建好像不行，只能在task中正确获取app.config.cacheTick,
如何才能实现我的需求

**Comment by atian25** [comment]
调度是在 agent 的 beforeStart 里面做的，这时候 app 还没启动呢。

https://github.com/eggjs/egg-schedule/blob/master/agent.js

动态时间的这个，可能需要自己写调度策略了。

**Comment by Yukyi** [comment]
嗯嗯 谢谢了  https://github.com/node-schedule/node-schedule 安装这个能解决吗 刚学 看api就两句话，搞了好久了 官网api是写的不全吗 还是我理解错了

**Comment by atian25** [comment]
我指的是你自己写一个 egg-schedule 的 timer 策略。

**Comment by Yukyi** [comment]
好的 谢谢
