### ISSUE TITLE
手动执行定时任务在多进程模式下无法控制单个 worker 执行

### ISSUE THREAD

**Issue by shinux** [eggjs/egg#3839]
如文档所述[手动执行定时任务](https://eggjs.org/zh-cn/basics/schedule.html#%E6%89%8B%E5%8A%A8%E6%89%A7%E8%A1%8C%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1)
的第二种方法，将定时任务的执行放到 `beforeStart` 中，然而每一个 worker 都会执行一遍对应的生命周期函数，导致定时任务被执行了 **worker 数量的次数**，即便这个 schedule 的类型是 **worker** 而不是 **all**

请问手动执行定时任务的原始设计就是这样的吗？
如果不是的话，有什么办法解决这个问题吗？

**Comment by atian25** [comment]
因为 beforeStart 是每个 worker 都有的啊。

你的原始需求是啥？

**Comment by shinux** [comment]
> 因为 beforeStart 是每个 worker 都有的啊。
> 
> 你的原始需求是啥？

我想既然 schedule 的设计区分了  worker 和 all，为什么手动执行的时候没有做对应的设计。

我的需求和使用 worker type 的 schedule 一样。只不过我希望在启动的时候先执行一次。

**Comment by atian25** [comment]
schedule 默认的策略很简单的，就用来做日志清理啥的，多集群的都需要额外扩展才行。

你这需求，可以是在 agent 做的。可以看下文档多进程那 2 章。

**Comment by shinux** [comment]
kk
