### ISSUE TITLE
Provisional headers are shown

### ISSUE THREAD

**Issue by fabin5** [eggjs/egg#3841]
我们把前端静态资源放在egg.js的public目录下，有部分用户无法访问index.html 提示 Provisional headers are shown  ，重启egg.js服务之后就可以了。

**Comment by atian25** [comment]
跟 egg 关系不大，自行搜索下这个关键词，或者提供可复现方式。

**Comment by fabin5** [comment]
@atian25 这个没有例子啊。就是公司的项目，突然有些人访问不了了。昨天都能访问的。今天访问不了，然后我尝试重启服务器之后发现可以了。

**Comment by atian25** [comment]
你觉得这样的信息量，能帮助彼此快速分析问题么？
