### ISSUE TITLE
Nginx 开启https反向代理eggjs服务端，游览器地址栏打开api正常，axiosPOST请求500Internal Server Error

### ISSUE THREAD

**Issue by JCqiu** [eggjs/egg#3842]
下图是直接请求api ip地址访问http请求信息
![QQ图片20190724120117](https://user-images.githubusercontent.com/16211027/61764630-76f32e80-ae0c-11e9-92ac-6629d0f7b4d6.png)
-----------------------------------------
下图是访问Nginx https代理后的api 域名地址http请求信息
![QQ图片20190724120334](https://user-images.githubusercontent.com/16211027/61764653-8c685880-ae0c-11e9-9793-b90e60fb5579.png)
-----------------------------------------
游览器地址栏打开状态
![QQ图片20190724120251](https://user-images.githubusercontent.com/16211027/61764716-a99d2700-ae0c-11e9-85ab-22f973d7eb33.png)
-----------------------------------------
Nginx配置
![QQ图片20190724120206](https://user-images.githubusercontent.com/16211027/61764722-aefa7180-ae0c-11e9-9768-58f04bbead73.png)

**Comment by popomore** [comment]
分别看下 nginx 和应用的错误日志

**Comment by JCqiu** [comment]
@popomore 应用没有产生日志，Nginx也没有500的日志生成

**Comment by atian25** [comment]
你调试下自己的代码呗，那个签名错误的逻辑不是你自己的代码么，看看为啥进了这个分支呗，一般是 HTTP 代理的某些信息丢失了。

**Comment by JCqiu** [comment]
@atian25 找到原因了，是因为代理的二级目录也被路由读取到了
![image](https://user-images.githubusercontent.com/16211027/61773834-2ab5e780-ae28-11e9-9fbe-89071c065c22.png)

**Comment by atian25** [comment]
那就是你的 Nginx 配置问题。

**Comment by JCqiu** [comment]
@atian25 我也没怎么配过Nginx呀，大佬发个教程呗

**Comment by atian25** [comment]
自己 google，不属于 egg 的职责。

**Comment by popomore** [comment]
nginx 没有日志是因为你没有配
