### ISSUE TITLE
使用egg遇到的一些疑问：业务上的（希望有老鸟看到帮忙一下谢谢啊==）

### ISSUE THREAD

**Issue by M1178475702** [eggjs/egg#3852]
在项目刚开始的时候，比较小，所以在service里，一个一个实体类，一个文件就搞定了
但是随着项目的扩张，业务及需求变得越来越多，一个文件显然不够，遂想着如何拆分service
在这里想请教下，如何拆分service（虽然这好像不是框架的问题，抱歉==）

假设我的service是按实体分的，如文章，轮播图。现在有个首页，是获取文章和轮播图。
我可以
1. 再开一个首页service，组装文章和轮播图。
但是首页作为sercice去划分，好像与文章，轮播图这样的实体不同
2. 在该接口的controller组装两个service，但是这样就会让controller侵入业务逻辑
请问这个时候哪种方案会更好？或者有其他方案？

另在egg中的service中，service间使用继承会不会出现一定的问题？
在使用了sequelize后，DAO层如何封装

**Comment by atian25** [comment]
Service 是支持子目录的。然后你 Service 之间可以互调的。

如果想明确加一层的话，可以配置下 customLoader
