### ISSUE TITLE
egg-redis插件无法连接redis？

### ISSUE THREAD

**Issue by salamander-mh** [eggjs/egg#3853]
## What happens?
`egg-redis`插件提示
```
 ERROR 118 nodejs.ETIMEDOUTError: connect ETIMEDOUT
```
只是这个插件还是可以连上的，我看到ioredis发布了新版本，然后这个插件就有问题了
我已经自定义了ioredis版本（用的4.9），但是我看到egg-redis还是使用的ioredis@4.11.2版本
依赖是使用cnpm装的，不过直接使用`npm install`是没有这个问题的

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**: 10.15
- **Egg Version**: 2.23
- **Plugin Name**: egg-redis
- **Plugin Version**: 2.4.0
- **Platform**:Linux/Ubuntu 18.05

**Comment by thonatos** [comment]
CI / Local 测试都通过，请检查一下配置。

> https://travis-ci.org/eggjs/egg-redis/builds/545169856

**Comment by salamander-mh** [comment]
@thonatos  我是说用cnpm装的时候就有问题，用npm装启动是没问题的
