### ISSUE TITLE
如何正确加载socket.io 客户端

### ISSUE THREAD

**Issue by zguuo** [eggjs/egg#3854]
## What happens?
在egg中如何介入一个socket.io 客户端，尝试将客户端编写至中间件，然而并没有运行，写入io/middleware，同现象。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：windows 10
- **Node 版本**：v10.6.0
- **Egg 版本**：2.10.0
- **Egg-socket.io 版本**：4.1.6

**Comment by ngot** [comment]
egg 和 egg-socket.io 都是服务端，不负责客户端。没太看懂你的问题。你是说加载 socket.io 的前端 js 文件，还是什么？请按照上面的说明，提供复现代码。
