### ISSUE TITLE
egg-ant-design-pro 部署到centos，config的assets配置url为机器IP地址，静态资源访问不到

### ISSUE THREAD

**Issue by CoCoyh** [eggjs/egg#3860]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
问题复现仓库：https://github.com/CoCoyh/egg-assets-deploy

## 复现步骤，错误日志以及相关配置

1. 克隆https://github.com/eggjs/egg-ant-design-pro
2. 在config/config.default.js文件的assets增加
```
url: '1.1.1.1',    // centos机器IP地址，这个是示例，不可用
```
3. 打包上传到centos， 执行
```
yarn
```
```
yarn build
```

```
yarn dev
```
4. 本机访问1.1.1.1: 7001，静态资源无法加载，查看静态资源的IP地址未生效，还是127.0.0.1
<img width="687" alt="23_25_01__08_01_2019" src="https://user-images.githubusercontent.com/24558814/62306423-6ef25900-b4b4-11e9-8ae8-5dfe1f476ec1.png">

## 相关环境信息
- **操作系统**：
centos
- **Node 版本**：
10.16.0
- **Egg 版本**：
^2.4.1
@popomore @okoala

**Comment by CoCoyh** [comment]
暂时解决了，egg-scripts代替egg-bin dev启动方式，但不清楚是什么原因

**Comment by thonatos** [comment]
原因：启动方式不对，dev 用于启动开发服务器，资源默认对应到本地。
