### ISSUE TITLE
[Feature Request] 最新版本的生命周期函数configWillLoad为什么只能支持同步调用？

### ISSUE THREAD

**Issue by satancp** [eggjs/egg#3861]
使用egg的时候遇到一个场景，所有配置是放在一个线上服务里面的，在egg服务启动的时候需要去拉取配置然后和本地的配置合并，所以这个过程一定是异步的，但是configWillLoad只支持同步调用，会导致配置在didReady这个周期结束之后才能全部拿到，请问一下configWillLoad只支持同步的原因是啥？

**Comment by atian25** [comment]
因为兼容性问题，Egg 之前的 Load 不支持配置的动态加载。我们会在下一个版本才支持。

目前的临时方案是可以在这里执行一个 execSync 来绕过。
