### ISSUE TITLE
[Feature Request] say something

### ISSUE THREAD

**Issue by kaihekaihe** [eggjs/egg#3863]
我用的是egg redis插件
在代码里用app.redis.get(key)这种方式，但是发现我们的redis挂了，但是程序一直卡在那。有没有办法设置超时，在卡住的情况下自动超时，然后走下面的逻辑？

或者有么有app.redis.isreachable这样的变量，我可以先判断再进行set get？

**Comment by thonatos** [comment]
使用文档请查看 redis 文档。

- https://github.com/luin/ioredis/blob/master/API.md
