### ISSUE TITLE
EGG怎样使用AES

### ISSUE THREAD

**Issue by pfzz** [eggjs/egg#3864]
使用EGG一段时间了，现在在遇到一个问题，AES加密解密不能得以解决，请求高手帮助，感谢不尽！

**Comment by whxaxes** [comment]
这个跟 egg 无关，属于 node 基础，可以自行查询

**Comment by ZQun** [comment]
@pfzz crypto-js试试
```typescript
// app/extend/helper.ts

import * as CryptoJS from 'crypto-js';

//  encrypt
let ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data.data), key);
DATA = ciphertext.toString();

// decrypt
let bytes  = CryptoJS.AES.decrypt(data.data.toString(), key);
DATA = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));
```

**Comment by pfzz** [comment]
谢谢  问题解决了  十分感谢你的答复





At 2019-08-08 22:49:24, "ZQun" <notifications@github.com> wrote:


@pfzz crypto-js试试

// app/extend/helper.tsimport*asCryptoJSfrom'crypto-js';



//  encryptlet ciphertext =CryptoJS.AES.encrypt(JSON.stringify(data.data), key);

DATA=ciphertext.toString();



// decryptlet bytes  =CryptoJS.AES.decrypt(data.data.toString(), key);

DATA=JSON.parse(bytes.toString(CryptoJS.enc.Utf8));
