### ISSUE TITLE
v8-compile-cache 这种 package 如何在 eggjs中引入？

### ISSUE THREAD

**Issue by flyingfz** [eggjs/egg#3865]
## 背景
eggjs 启动的时间比较长，在虚拟机里(4c 4G)大概测试了下，大约在10s以上.
[v8-compile-cache](https://github.com/zertosh/v8-compile-cache) 是用来缓存 js 编译结果并加速启动的一个 package 。原理就是在把编译结果缓存到磁盘，启动时不用再编译js代码。但是这个包的使用方式是在 入口的js文件里 第一行引入 
```
require('v8-compile-cache')
```

## 问题
eggjs 是使用 egg-script 来管理worker进程，那如何在 eggjs里 引入v8-compile-cache 模块，实现代码缓存？

**Comment by hyj1991** [comment]
`egg-scripts --require v8-compile-cache` 試下？

**Comment by flyingfz** [comment]
多谢， 我来试试看。
