### ISSUE TITLE
egg aws s3凭证问题

### ISSUE THREAD

**Issue by Dilmoon2016** [eggjs/egg#3871]
window10版本 
node：10.15.1
egg：2.23.0
aws-sdk：2.493.0
加载不到文件
var AWS = require('aws-sdk');
AWS.config.loadFromPath('./config.json');

启动系统会报错
Error: [egg-core] load file: E:\HLWechat-API\app\controller\uploadimg.js, error: ENOENT: no such file or directory, open './config.json'。
用了中间件的写法也不行

**Comment by thonatos** [comment]
已经回复过了，重复问题就不要多开 issue 了

**Comment by Dilmoon2016** [comment]
> 已经回复过了，重复问题就不要多开 issue 了

中间件的方式还是不能加载文件报的错是一样的，是不是egg对AWS.config.loadFromPath('./config.json')这个方法有拦截

**Comment by thonatos** [comment]
> > 已经回复过了，重复问题就不要多开 issue 了
> 
> 中间件的方式还是不能加载文件报的错是一样的，是不是egg对AWS.config.loadFromPath('./config.json')这个方法有拦截

原因回复多次了，基础知识 & 错误提示请自补。
