### ISSUE TITLE
mongoose insertMany导致ClusterClientNoResponseError

### ISSUE THREAD

**Issue by dythbj** [eggjs/egg#3872]
## What happens?
mongoose insertMany每次插入1000条数据会导致ClusterClientNoResponseError，并且导致大量请求处于pending状态。
将每次插入的数据量降到100，其他API接口响应时间变长（正常10ms以内，执行insertMany时，响应时间1S）。

## 复现步骤，错误日志以及相关配置
await ctx.model.Test.insertMany([datas])

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：8.14.1
- **Egg 版本**：2.15.1

**Comment by dythbj** [comment]
Any buddy home?

**Comment by dythbj** [comment]
Hello?

**Comment by whxaxes** [comment]
egg-mongoose 只是在 mongoose 上简单包了一层，你这个问题属于 mongoose 的，不属于 egg 的，可以去 mongoose 的 issue 里翻翻有没有类似的情况

**Comment by dythbj** [comment]
> egg-mongoose 只是在 mongoose 上简单包了一层，你这个问题属于 mongoose 的，不属于 egg 的，可以去 mongoose 的 issue 里翻翻有没有类似的情况

😄，明白，我的核心问题是为egg什么会报ClusterClientNoResponseError，就一个数据库插入，没有block啊？

**Comment by whxaxes** [comment]
把错误完整的贴出来，最好能提供一个稳定复现的 repo

**Comment by dythbj** [comment]
> 把错误完整的贴出来，最好能提供一个稳定复现的 repo

看过最近很火的《哪吒》吗？想把哪吒的招牌动作回复给你。。。。

**Comment by dythbj** [comment]
> Hello @dythbj. Please provide a reproducible example following the [instruction](https://github.com/eggjs/egg/issues/3310).
> 
> Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> @dythbj，请根据[这个说明](https://github.com/eggjs/egg/issues/3310)提供最小可复现代码。
> 
> 如果在 7 天内没有进展会被自动关闭。

![image](https://user-images.githubusercontent.com/41282663/62935197-0f237880-bdf9-11e9-9fd2-b6d232e4ab81.png)
