### ISSUE TITLE
extend 扩展 application  this 为 undefined

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [eggjs/egg#3876]
## What happens?
extend 扩展 application  this 为 undefined
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

`app/extend/application.js`:
```#!/usr/bin/env node
'use strict';

module.exports = {
  getAlias(path, controller) {
    this.router.get(path, controller);
    this.router.get(`${path}/`, controller);
    this.router.get(`${path}/index.html`, controller);
  },
};
```
throw:
`TypeError: Cannot read property 'router' of undefined`

仓库：https://github.com/Mr-jiangzhiguo/repo-bugs

**Comment by atian25** [comment]
```js
  const { router, getAlias, controller } = app;
  getAlias('/cnn/share/:id', controller.cnn.shareArticle.getData);
```

改为 

```js
  app.getAlias('/cnn/share/:id', controller.cnn.shareArticle.getData);
```

基础的 JS 作用域问题。
