### ISSUE TITLE
typescript 关联两张表

### ISSUE THREAD

**Issue by daiyang123456** [eggjs/egg#3877]
## What happens?

![image](https://user-images.githubusercontent.com/29270422/62625989-ed3d7800-b958-11e9-9e82-b5d9ecc95a1b.png)
const { STRING, INTEGER } = app.Sequelize;
    const model = {
      id: { type: INTEGER, primaryKey: true, autoIncrement: true },
      fileName: STRING(30),
      fileId: {
          type: INTEGER,
          unique: true,
          allowNull: false,
          references: {
              model: 'article',
              key: 'id',
          },
      },
      fileUrl: STRING,
    };
 const Article = app.model.define('article', model);
    app.model.Article.hasOne(app.model.File, { foreignKey: 'fileId' });
    return class extends Article { };

 const model = {
      id: { type: INTEGER, primaryKey: true, autoIncrement: true },
      creator: STRING(30),
      content: TEXT,
      text: TEXT,
      title: STRING(40),
      created_at: DATE,
      updated_at: DATE,
      isShow: BOOLEAN,
    };
 const File = app.model.define('file', model);
    app.model.File.belongsTo(app.model.Article, { foreignKey: 'id', targetKey: 'fileId' });
    return class extends File {};
``
## 相关环境信息
- **操作系统**：
- **Node 版本**：8.11.3
- **Egg 版本**：2.23.0
- **Egg-sequelize 版本**：5.2.0
- **Typescript版本**：3.5.0

**Comment by daiyang123456** [comment]
@atian25

**Comment by supperchong** [comment]
定义表关系放在associate 函数里面，因为执行app.model.define之后 Article还没有被绑定到app.model上面
```js  
Article.associate = function() {
  app.model.Article.hasOne(app.model.File, { foreignKey: 'fileId' });
}
```

**Comment by whxaxes** [comment]
问题已有回答，我关掉先

**Comment by daiyang123456** [comment]
> 定义表关系放在associate 函数里面，因为执行app.model.define时, Article还没有被绑定到app.model上面
> 
> ```js
> Article.associate = function() {
>   app.model.Article.hasOne(app.model.File, { foreignKey: 'fileId' });
> }
> ```

![image](https://user-images.githubusercontent.com/29270422/62675786-ff5ffa80-b9da-11e9-9511-7cf6c88dec28.png)
但是hui'y会有这个报错呢

**Comment by daiyang123456** [comment]
const Article: any = app.model.define('article', model); 这样就不报错了

**Comment by hengkx** [comment]
@daiyang123456 我也报这个错 解决了吗？

**Comment by LimonSea** [comment]
> > 定义表关系放在associate 函数里面，因为执行app.model.define时, Article还没有被绑定到app.model上面
> > ```js
> > Article.associate = function() {
> >   app.model.Article.hasOne(app.model.File, { foreignKey: 'fileId' });
> > }
> > ```
> 
> ![image](https://user-images.githubusercontent.com/29270422/62675786-ff5ffa80-b9da-11e9-9511-7cf6c88dec28.png)
> 但是会有这个报错呢

我也报这个错。。请问解决了吗

**Comment by LimonSea** [comment]
> @daiyang123456 我也报这个错 解决了吗？

请问您解决了吗？

**Comment by daiyang123456** [comment]
> > @daiyang123456 我也报这个错 解决了吗？
> 
> 请问您解决了吗？

Article: any = .....就可以了
