### ISSUE TITLE
formdata提交的参数带html时，controller中ctx.request.body获取的参数格式有误

### ISSUE THREAD

**Issue by xcs-shadow** [eggjs/egg#3878]
在controller中获取的body格式跟request中提交的不一样，具体看下面的代码
### 这是request信息
![QQ截图20190808111147](https://user-images.githubusercontent.com/28973432/62679419-ff65f780-b9e6-11e9-8eb9-72483a3566a9.png)
### 这是提交的表单数据
![QQ截图20190808111207](https://user-images.githubusercontent.com/28973432/62679420-fffe8e00-b9e6-11e9-8d79-405e565ce154.png)
### 这是后台接收到的body
![QQ截图20190808111314](https://user-images.githubusercontent.com/28973432/62679422-fffe8e00-b9e6-11e9-90b5-98afbfcb55e0.png)

**Comment by supperchong** [comment]
egg用的koa-bodyparser解析body,然后koa-bodyparser用co-body来解析,然后在
[co-body](https://github.com/cojs/co-body/blob/master/lib/form.js#L29-L30)
```js
 // keep compatibility with qs@4
  if (queryString.allowDots === undefined) queryString.allowDots = true;
```
所以可以显示设置allowDots:false
```js
config.bodyParser = {
    enable: true,
    encoding: 'utf8',
    formLimit: '100kb',
    jsonLimit: '100kb',
    strict: true,
    // @see https://github.com/hapijs/qs/blob/master/lib/parse.js#L8 for more options
    queryString: {
      arrayLimit: 100,
      depth: 5,
      allowDots: false,
      parameterLimit: 1000,
    },
  }
```

**Comment by xcs-shadow** [comment]
解决了，谢谢 @supperchong
