### ISSUE TITLE
egg-security csrf support referer typ cause bug

### ISSUE THREAD

**Issue by kuluo** [eggjs/egg#3879]
egg-security 一个小时前发布了一个版本，新增了feat: csrf support referer type (#56) 特性
其中可选配置项  type: 'ctoken',     // can be ctoken or referer or all, default to ctoken
实际行为和文档不一样，使用csrf: {} 方式进行配置时如果不传type会导致应用启动失败
所有使用eggjs自定义csrf配置的都会受影响。

**Comment by whxaxes** [comment]
已经改了 dist-tag ，重新装一下依赖即可，也已经发了 patch 了 https://github.com/eggjs/egg-security/pull/58/files
