### ISSUE TITLE
eggjs orm plugin specification

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#388]
Now there are more and more orm framework requirements, most orm framework are Active-record-pattern-like(https://en.wikipedia.org/wiki/Active_record_pattern), similar to the view plugin(https://eggjs.org/zh-cn/advanced/view-plugin.html), we need a specification for egg orm plugin.

Orm framework generally has the following features:

- transform table to object, and use files under app/models to define.
- Relationship between several tables.
- Syntactic sugar for query, update, delete etc.
...

So let us discuss whether a specification is needed or not?

**Comment by atian25** [comment]
@popomore  should we need `proposal` label?

**Comment by popomore** [comment]
@atian25 maybe RFC

**Comment by popomore** [comment]
Current we have  https://github.com/eggjs/egg-labels/blob/master/labels.json

**Comment by jtyjty99999** [comment]
Now we see some points in specification:

- Directory for defining data models   like  `app/model` or `app/models`
- File name specification for data model
- How to access data model, by `ctx`/`app`
- plugin pattern
  - config
  - heartbeat request
  - tracelog
  - event handle like onerror, ondisconnect, onconnect

**Comment by atian25** [comment]
only use `app/model`, not `s`

**Comment by popomore** [comment]
https://github.com/tgriesser/bookshelf

**Comment by StoneRen** [comment]
https://github.com/balderdashy/waterline
Waterline is a next-generation storage and retrieval engine, and the default ORM used in the Sails framework
It provides a uniform API for accessing stuff from different kinds of databases, protocols, and 3rd party APIs. That means you write the same code to get and store things like users, whether they live in Redis, MySQL, MongoDB, or Postgres.

**Comment by guzuomuse** [comment]
how is going about this topci?
we need an offical orm.
is there a roadmap or timeline for this?

**Comment by popomore** [comment]
We recommend use [egg-sequelize](https://github.com/eggjs/egg-sequelize), see https://github.com/eggjs/egg/issues/388

**Comment by Hyurl** [comment]
I have developed an ORM, Modelar, I recommend have a look at it, may satisfy egg needs, support MySQL/MariaDB, PostgreSQL, SQLite, MsSQL, OracleDB and DB2, similar to TypeORM, but written in pure JavaScript.
https://github.com/hyurl/modelar
Give me notice if you'd like it or have any suggests.

**Comment by wineforyou** [comment]
我也想问下egg的orm...怎么样了

**Comment by lizeyue326** [comment]
我也想问下egg的orm...怎么样了+1

**Comment by sefier** [comment]
设计了三年还没设计出来，这个项目算是死了，大家别用了。

**Comment by darrenliuwei** [comment]
> 设计了三年还没设计出来，这个项目算是死了，大家别用了。

不是还有`egg-sequelize`么？

**Comment by xgqfrms** [comment]
# ORM & ODM

> (SQL) mysql & (NoSQL) mongodb

**Comment by qq578023708** [comment]
这个轮子看来是没精力造了

**Comment by juukee** [comment]
不造ORM?

**Comment by Shijf** [comment]
> 设计了三年还没设计出来，这个项目算是死了，大家别用了。
https://github.com/eggjs/egg-orm#readme 有了

**Comment by topstop3416** [comment]
也许这就是生态吧

**Comment by islittlezhou** [comment]
我希望这个 orm 能像  mybatis中写 xml 一样， 不然又得学一遍 这个  orm 中的各种语法 使用方法。
最好能像  mybatis 一样， 组装sql

**Comment by islittlezhou** [comment]
为什么一点音信都没有啊  快点出来啊

**Comment by cc2937** [comment]
https://github.com/eggjs/egg-orm/blob/master/Readme.zh-CN.md 感谢贡献者！终于出来了！Leoric 文档很赞！👍

**Comment by bakenray** [comment]
2022年了，官方ORM模型还在设计中，加油啊~~
