### ISSUE TITLE
eggTs项目目前引入了egg-sequelize, 现在想接入sequelize-typescript，如何配合使用

### ISSUE THREAD

**Issue by jiaotashidi** [eggjs/egg#3882]

**Comment by whxaxes** [comment]
我们目前没有这样的实践，你可以自己试一下，如果实践后能提供方案反哺到社区就更好了

**Comment by ZQun** [comment]
@jiaotashidi https://github.com/midwayjs/midway-examples/tree/master/demo-sequelize-typescript

**Comment by jiaotashidi** [comment]
@ZQun  非常感谢

**Comment by whxaxes** [comment]
看似已解决，那我关了哈
