### ISSUE TITLE
在centos上部署egg.js，外网访问404

### ISSUE THREAD

**Issue by flexmodule** [eggjs/egg#3883]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.centos跑在http://127.0.0.1:7001,nginx配置了loccation代理
2.

**Expected behavior**
1.正常访问
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
Nginx 配置之类的自行排查。

可以 ssh 上去 curl 内网 ip，如果没问题就不是 egg 的问题。

**Comment by flexmodule** [comment]
> Nginx 配置之类的自行排查。
> 
> 可以 ssh 上去 curl 内网 ip，如果没问题就不是 egg 的问题。

内网访问没问题，nginx配置了location /egg  {proxy_pass：http://127.0.0.1:7001}     ；外网访问404，ngnix配置需要额外什么配置吗

**Comment by unclexiao** [comment]
不需要额外配置，改完之后重启nginx了么

**Comment by zhaoxiaobao** [comment]
@flexmodule 最后解决了吗？
