### ISSUE TITLE
egg-scripts: receive signal SIGTERM, closing and exit process

### ISSUE THREAD

**Issue by kekobin** [eggjs/egg#3885]
最近使用egg-init --type=simple开发了个项目，本地开发没问题，使用npm start (egg-scripts start --daemon)部署到linux机上随机出现如下问题：   

![image](https://user-images.githubusercontent.com/4536310/62998928-8ad80080-be9f-11e9-84c4-785f73fc91c0.png)

太难受了，为什么感觉跟pm2比难用很多呢？

**Comment by atian25** [comment]
看起来像是，你的容器之类的管理进程主动杀掉了 egg。就算用 pm2 它要被人杀也一样

**Comment by popomore** [comment]
这个 master 被子kill 了

**Comment by TomorrowCat** [comment]
请问，这个问题解决了吗，我也遇到了相同的问题

**Comment by atian25** [comment]
检查你的容器或者其他进程，为啥要杀死 egg 进程。

另外，如果是容器里面的话，尽量自己指定下 --workers=xx

**Comment by TomorrowCat** [comment]
这个服务并没有使用容器，启动参数设置了--workers=8。现在很难受，我并不知道是谁、是什么原因、是什么场景，把egg进程给干死了，时间也不固定，有时候几个小时，有时候一天。。

**Comment by atian25** [comment]
这个服务器上有没有其他 egg 进程，如果是默认的 egg-scripts stop 是会杀掉所有 egg 进程的，需要指定 --title 或者使用 npm stop 才行。

**Comment by TomorrowCat** [comment]
撩gay！的确有其他egg服务，但是所有stop命令，都指定了--tilte，这个问题我在研究下

**Comment by atian25** [comment]
容器化才是正确的道路，都 2019 年了。

**Comment by TomorrowCat** [comment]
可以，紧跟时代发展，上容器！

**Comment by canvasT** [comment]
> 这个服务并没有使用容器，启动参数设置了--workers=8。现在很难受，我并不知道是谁、是什么原因、是什么场景，把egg进程给干死了，时间也不固定，有时候几个小时，有时候一天。。

你好，这个问题有解决吗？最近我也遇到类似问题，没有用容器，没有其他egg服务
