### ISSUE TITLE
如何使用socket.io来进行消息通知

### ISSUE THREAD

**Issue by liangwenzhu** [eggjs/egg#3886]
## What happens?
场景：用egg作为一个http服务器，用户点赞时，被点赞用户收到被点赞的消息。
网页端使用 socket.io-client 来发起socket请求，请求的controller是在app/io/controller目录下的。（连接成功，并返回消息）
点赞接口是写在app/controller上。用户点赞被controller捕获并处理。

在查阅了资料后发现在非io目录下，是没有io对象的，因此也就无法在点赞的controller里发起emit。（事实上我在io下的controller进行emit，客户端也没有实时收到后续消息，不知道是不是使用方式有问题）

这种情况下如何使用socket.io来实现点赞通知功能？

`
//egg:
//点赞接口
app.router.resources('behaviorLike', '/api/behaviorLike', 'behaviorLike');
//消息通知接口
io.of('/').route('message', io.controller.message.index);

//web连接
test = () => {
        var socket = io('ws://localhost:3008/');
        socket.on('connect', function() {
            console.log('连接');
            socket.emit('message', '发出一条信息');
        });
        socket.on('res', function(data) {
            console.log(`res from ${data}`);
        });
        socket.on('disconnect', function() {
            console.log('断开');
        });
    };
`

**Comment by unclexiao** [comment]
> 在查阅了资料后发现在非io目录下

io是一个虚拟路径，底层做了自动转发，而不是实际存在的文件目录。

如果你做了反向代理，那可以自定义**path**来指定路径（[官方文档](https://socket.io/docs/client-api/)）：
```javascript
const socket = io('http://localhost', {  path: '/myownpath'});
```

但是你这个例子是直接访问的，所以不存在这个问题。

---

> 因此也就无法在点赞的controller里发起emit

当然可以，通过**app**就可以拿到全局的[io](https://eggjs.org/zh-cn/tutorials/socketio.html)

```javascript
const {  io } = app;
var nsp = io.of('/my-namespace');
nsp.on('connection', function(socket){
  console.log('someone connected');
});
nsp.emit('like', 'everyone!');
```


--- 
> 客户端也没有实时收到后续消息

1. 建立连接成功，且命名空间正确
2. 确保发布/订阅的是同一个事件
3. 如果单播/组播有问题，试试全体广播
4. 打开浏览器调试工具，抓包查看WS通信数据：

**Comment by liangwenzhu** [comment]
@unclexiao 万分感谢！ 我发现是我第二步的问题。

> 当然可以，通过app就可以拿到全局的io

这个步骤一开始我也试过的，但是当时前端订阅的是`res`而不是`message`才导致一直收不到（改成res就可以了）。


再次感谢您的答案。
