### ISSUE TITLE
定时任务为啥不执行？不输出呢？

### ISSUE THREAD

**Issue by lkkunheiheihei** [eggjs/egg#3889]
const Subscription = require('egg').Subscription;

class updateOrderStatus extends Subscription {
  static get schedule() {
    return {
      type: 'all',
      interval: '2s',
      immediate: true,
    };
  }

  async schedule() {
    console.log("定时任务执行");
  }
}

module.exports = updateOrderStatus;

**Comment by lkkunheiheihei** [comment]
![image](https://user-images.githubusercontent.com/26806088/63155146-9f093280-c044-11e9-9818-7fe04a4cfc86.png)

**Comment by lkkunheiheihei** [comment]
他应该是这个样子的啊？定时任务console.log()为什么不能这样的输出呢？
![image](https://user-images.githubusercontent.com/26806088/63155353-f4454400-c044-11e9-815b-18b38bffe433.png)

**Comment by atian25** [comment]
async schedule 写错，看下文档

**Comment by lkkunheiheihei** [comment]
这是官网的例子啊，不知道为啥我这就是不输出啊，是因为不能输出console.log()吗？
`const Subscription = require('egg').Subscription;

class UpdateCache extends Subscription {
  // 通过 schedule 属性来设置定时任务的执行间隔等配置
  static get schedule() {
    return {
      interval: '1m', // 1 分钟间隔
      type: 'all', // 指定所有的 worker 都需要执行
    };
  }

  // subscribe 是真正定时任务执行时被运行的函数
  async subscribe() {
console.log('11111')
  }
}

module.exports = UpdateCache;`

**Comment by atian25** [comment]
你上面写的是 async schedule，不是 async subscribe
