### ISSUE TITLE
config.{env}.js & plugin.{env}.js

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#389]
see discussion at https://github.com/eggjs/egg/pull/383#discussion_r101243240

will this is necessary and **should it include in 1.0** ?

cc @eggjs/core 

landed at https://github.com/eggjs/egg-core/issues/57

if `plugin.default.js` exist, load it, rather than `plugin.js`

**Comment by dead-horse** [comment]
我建议保持和 config 的一致，并且将 config.js 和 plugin.js 作为 xx.default.js 的别名。起码我感受到在写文档的时候每次都写  `config.default.js` 有点蛋疼。

**Comment by atian25** [comment]
别名的话, 哪个为主?

之前最早就是  config.js, 后面改为 config.js 和 config.default.js, 优先且只加载一个.

开源的时候就干掉 config.js 了

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/config.js#L76

没有干掉吧，不过文档里面都没写了。

**Comment by popomore** [comment]
现在还是保留原来的逻辑

**Comment by atian25** [comment]
也就是有 default 的时候用 default, 没有的时候用 .js.

这个要在 1.0 改不?

**Comment by popomore** [comment]
那 plugin 按这个逻辑改改看

**Comment by atian25** [comment]
好, 我改改看

**Comment by atian25** [comment]
改了, 可以看看
