### ISSUE TITLE
koa版本更新导致egg启动报错

### ISSUE THREAD

**Issue by FanWJ1108** [eggjs/egg#3892]
![image](https://user-images.githubusercontent.com/20589814/63238125-79b03a80-c277-11e9-873e-1123d1932209.png)
一小时前koa更新了新版本。egg中没有setter导致报错。

**Comment by acodercat** [comment]
同问

**Comment by dstyxy** [comment]
是的，我刚才也遇到这个问题，第一次用egg就踩上坑了。。。

把这行删掉倒是能启动。

**Comment by menggong** [comment]
同问，从报错来看是koa有更新

**Comment by kuluo** [comment]
https://github.com/koajs/koa/commit/287e589ac773d3738b2aa7d40e0b6d43dde5261b

**Comment by guozefei** [comment]
恩 同出现了这个问题 应该如何解决？

**Comment by acodercat** [comment]
@dead-horse

**Comment by gaoyuan-mountain** [comment]
> 恩 同出现了这个问题 应该如何解决？

I block the version of koa in package.json. This will resolve the error.
`"koa": "2.7.0",`

**Comment by dead-horse** [comment]
升级到最新版本的 koa 即可。
