### ISSUE TITLE
set cookie 在safari不能得到

### ISSUE THREAD

**Issue by goplaygo** [eggjs/egg#3894]
## What happens?
我们是基于cookie的单点登录，a.com通过另一个服务器b.com来进行注册登录，然后返回到a.com；
我们在chrome是可以获取到b.com返回的token，但是在Safari浏览器并不能得到返回的token

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

### 相关配置如下 
```javascript
config.default.js下：
config.cors = {
    origin:'*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH',
    credentials:true,
  };
config.security = {
    xframe: {
      enable: false,
    },
    // 关闭csrf
    csrf: {
      enable: false,
      ignoreJson: true,
    },
    domainWhiteList:['*']
  };
```
## 用来存储cookie的接口配置
```
ctx.cookies.set("token", token,{
   httpOnly:false,signed: false,domain:'.a.com',path:'/'
});
```
我们可以在Chrome里看到cookie里可以看到token值，然而在safari的cookie里，并不能找到应该存储的token值
请问是什么原因呢？

## 相关环境信息
- **操作系统**：Linux ubuntu16.4
- **Node 版本**：v10.15.3
- **Egg 版本**：v2.15.1

**Comment by atian25** [comment]
看下 network 的 response 里面有没有返回 cookie

**Comment by Jeff-Tian** [comment]
> 我们是基于cookie的单点登录，a.com通过另一个服务器b.com来进行注册登录，然后返回到a.com；
> 我们在chrome是可以获取到b.com返回的token，但是在Safari浏览器并不能得到返回的token

应该是跨域造成的，b.com 写的 cookie，在 a.com 的页面看不到。你在 Chrome 中看到写成功了，是不是因为在页面跳转前看到的？

**Comment by fengmk2** [comment]
不可能在 b.com 下改写 a.com 的 cookie 的。

**Comment by onepiecelyk** [comment]
> 看下 network 的 response 里面有没有返回 cookie

在chrome里看到是可以的，在safari下得不到，我搜索了一下，别人说的是safari是把三方cookie给禁止了，但是chrome不禁止

**Comment by onepiecelyk** [comment]
> 不可能在 b.com 下改写 a.com 的 cookie 的。

我们做的思路是a.com产生了cookie，我们把他存储到浏览器local storage下，然后b.com去里去拿

**Comment by onepiecelyk** [comment]
> 不可能在 b.com 下改写 a.com 的 cookie 的。

是的，是因为跨域，但是我们通过存储到本地，拿到了
