### ISSUE TITLE
unit test 中如何 hack middleware

### ISSUE THREAD

**Issue by chenzeZzz** [eggjs/egg#3896]
## What happens?

hack middleware 失败

## 最小可复现仓库
> https://github.com/chenzeZzz/egg-showcase

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：v8.9.4
- **Egg 版本**：2.21.1

**Comment by atian25** [comment]
没太看懂

**Comment by chenzeZzz** [comment]
测试 controller 层的时候，其实是接口测试，怎么跳过中间件，比如鉴权



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TZ | 天猪 <notifications@github.com>
发送时间: 2019年8月26日 10:22
收件人: eggjs/egg <egg@noreply.github.com>
抄送: 天堂鸟丶网吧 <836851807@qq.com>, Author <author@noreply.github.com>
主题: 回复：[eggjs/egg] unit test 中如何 hack middleware (#3896)




没太看懂

**Comment by atian25** [comment]
一般来说是 httpRequest 的时候带上 cookie 之类的，去模拟登陆过程，而不是跳过。
如果想跳过的话，自己在 middleware 里面判断当前的 env

**Comment by chenzeZzz** [comment]
明白了，谢谢

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: TZ | 天猪 <notifications@github.com>
发送时间: 2019年8月26日 10:29
收件人: eggjs/egg <egg@noreply.github.com>
抄送: 天堂鸟丶网吧 <836851807@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[eggjs/egg] unit test 中如何 hack middleware (#3896)




一般来说是 httpRequest 的时候带上 cookie 之类的，去模拟登陆过程，而不是跳过。
 如果想跳过的话，自己在 middleware 里面判断当前的 env
