### ISSUE TITLE
[Feature Request] egg-scripts能否支持--max-old-space-size

### ISSUE THREAD

**Issue by pakinguoJS** [eggjs/egg#3899]
## Background
有业务需要服务运行时，占用较大的内存，故希望能在用egg-scripts启动时调整应用的最大内存。

## Proposal
用node启动应用时，可以--max-old-space-size参数来设置最大内存：
node --max-old-space-size=2000 app.js // 单位为MB

对应egg-scripts，能否支持egg-scripts --max-old-space-size=xxx
（PS：node启动时有较多常用的参数来灵活按需设置，这里是否能使egg-scripts更灵活地去应用多样化的参数）

## Additional context
-

**Comment by atian25** [comment]
`--node-options--trace-warnings`

https://github.com/node-modules/common-bin/blob/master/lib/helper.js
