### ISSUE TITLE
[RFC] egg-opentracing

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#39]
分布式链路追踪是当今微服务架构中必不可少的组成部分，一个请求穿插于各个应用系统、中间件、数据库之间，通过 tracing 就能知道整个请求的链路以及各部分的耗时。Egg 会基于开放的 [opentracing](http://opentracing.io/) 来实现这个功能。

## 概念

Trace：一个 Trace 代表在微服务架构中的一次链路请求，可能经过一个或多个微服务应用。

Span：一个 span 代表系统中具有开始时间和执行时长的逻辑运行单元，一个 Trace 会包含多个 Span。

SpanContext：代表一个 Span 的信息，比如 TraceId，spanId，以及该 Span 的相关信息。注意：这个和 egg 的 ctx 没有关系。

Baggage：还有一些信息也在 SpanContext 中，我们称之为 Baggage，这些信息会在整个 Trace 中传递。

Tag：Span 中用来识别 span 的一些信息，比如

- error
- component: httplib, jdbc, mongoose
- span.kind: client, server
- http.url
- http.method
- http.status_code
- framework
- peer.hostname

Carrier：在微服务架构中，两个应用之前会通过不同的协议进行通讯，但是 opentracing 是无法感知的，所以定义了 Carrier 这个概念，他通过 Inject 和 Extract 和 SpanContext 之前进行互相转换，然后 Carrier 可以在协议中传递。比如 HTTP 请求，SpanContext 通过 Inject 设置 HTTPCarrier（转换成请求头），在请求接收方通过 Extract 将 HTTPCarrier 提取成 SpanContext。

Collector：我们通过 Collector 收集每个 span 的具体信息，然后记录，可以通过日志的方式或请求上报的方式。

## 实现方案

Egg 提供 `ctx.tracer` 实例作为一次 Trace，下面按照一个微服务应用整个请求周期描述各个 API

### 接收请求

比如收到了一个 HTTP 请求，在 server 入口应该

```js
// app/middleware/meta.js
module.exports = () => {
  return async function meta(ctx, next) {
    // 从 http header 获取 span 上下文
    const spanContext = ctx.tracer.extract('HTTP', ctx.header);
    // 创建 span 时指定父级 span
    const span = ctx.tracer.startSpan('http_server', { childOf: spanContext });
    await next();
    span.finish();
  };
}
```

### 发送请求

比如发起一个 RPC 请求，需要在 RPC 客户端

```js
const span = ctx.tracer.startSpan('rpcclient');
const rpcCarrier = {};
ctx.tracer.inject(span.context, 'RPC', rpcCarrier);
ctx.rpcclient.invoke(data, rpcCarrier);
span.finish();
```

### 定义 Carrier

上面使用到了 inject 和 extract 其实是需要这里提前定义的

```js
// lib/http_carrier.js
module.exports = class HttpCarrier {
    
  inject(spanContext) {
    // 转换
    return header;
  }
  
  extract(header) {
    // 转换
    return spanContext;
  }
  
}

// config/config.default.js
exports.opentracing = {
  carrier: {
    'HTTP': require('../lib/http_carrier'),
  },
};
```

### 定义 Collector

还需要定义一个收集器

```Js
// lib/log_collector.js
module.exports = class LogColletor {
    
  collect(spanContext) {
    this.ctx.logger.write(this.format(spanContext));
  }

}

// config/config.default.js
exports.opentracing = {
  collector: {
    log: require('../lib/log_collector'),
  },
};
```

### 覆盖默认实现

Egg 的 Tracer 和 Span 对象都是 [opentracing](https://github.com/opentracing/opentracing-javascript) 的一个实现，但你也可以通过覆盖的方式来实现。

```js
// config/config.default.js
exports.opentracing = {
  globalTracer: YourTracer,
};
```

## 分布式跟踪系统

Zipkin, Dapper, HTrace, X-Trace

**Comment by popomore** [comment]
这个实现 tracer 就好了？

**Comment by fengmk2** [comment]
https://github.com/opentracing-contrib/opentracing-specification-zh

有一个开放的规范

> OpenTracing是一个跨编程语言的标准，此文档会避免具有语言特性的概念。比如，我们在文档中使用"interface"，因为所有的语言都包含"interface"这种概念。

**Comment by fengmk2** [comment]
https://wu-sheng.gitbooks.io/opentracing-io/content/

**Comment by fengmk2** [comment]
opentracing 有官方 npm 模块 https://github.com/opentracing/opentracing-javascript

**Comment by fengmk2** [comment]
基于阿里云 sls + opentracing 封装一个插件实现 https://github.com/opentracing-contrib/opentracing-specification-zh/blob/master/semantic_conventions.md

opentracing 插件支持切换日常存储引擎，默认是文件存储，支持 sls 等云存储。

**Comment by fengmk2** [comment]
实现在 https://github.com/eggjs/egg-opentracing/pull/1 跟进

**Comment by wangcloudyun** [comment]
请问tracer的分布式跟踪有最佳实践的案例分享吗？谢谢。

**Comment by popomore** [comment]
sls 还是不要支持在 opentracing 里面比较好

**Comment by wangcloudyun** [comment]
主要是想了解egg-tracer是如何实现前后端全链路跟踪的，由于官方文档中没有任何案例提及这一块，让使用者没有方向，不知道怎么使用

**Comment by popomore** [comment]
一般是系统间调用的时候传递 tracer 信息，然后打印日志的时候要包含 tracer 信息，平台收集日志后就可以有整个链路的信息了。opentracing 就是实现如何建立链路关系，egg-tracer 是每个应用的 tracer 信息，包括上下游。

**Comment by popomore** [comment]
https://github.com/openzipkin/zipkin-js

**Comment by fengmk2** [comment]
默认内置了 opentracing，各个企业框架，根据企业内部需求，将 opentracing 转换成企业需要的格式，再打印日志，或者上报到自己的 apm，都是可行的方式。

**Comment by popomore** [comment]
我们用 egg-opentracing 来替换 egg-tracelog？

**Comment by popomore** [comment]
更新了 RFC

**Comment by popomore** [comment]
opentracing 是否默认集成在 egg 中 @gxcsoccer @fengmk2

**Comment by popomore** [comment]
## egg-opentracing 插件的功能

1. 基础的 opentracing 能力
1. 默认支持 httpclient/httpserver 的打点及常用 tag
1. 默认的 collector 为日志模式，不区分文件
1. 每个 span 包含默认的 tag
   1. appname
   1. workerid
   1. process id
   1. 

## egg-zipkin 插件的功能

1. 支持 zipkin 作为 collector

## sofa-tracer-node

1. 对接 carrier，http/rpc 调用传递（后面还有消息等组件）
1. 对接日志格式

**Comment by popomore** [comment]
cd /Users/popomore/projj/github.com/eggjs/egg-sofa-tracer

**Comment by NickNameWolf** [comment]
@popomore  我们PHP服务现有的trace框架是zipKin.那我如果用egg建立一个新的服务,trace使用egg-opentracing-zipkin 可以和PHP服务现有的zipKin兼容吗
