### ISSUE TITLE
egg-socket.io如何编写单元测试

### ISSUE THREAD

**Issue by asuka-yuuki** [eggjs/egg#3900]
想把单元测试覆盖率弄高点，结果发现egg-socket.io有关的死活覆盖不到，老哥们有啥方法吗

**Comment by ngot** [comment]
可以参考下 egg-socket.io 的测试 https://github.com/eggjs/egg-socket.io/blob/master/test/io.test.js

**Comment by asuka-yuuki** [comment]
这种写法是覆盖到了egg-socket.io/test/fixtures/apps/文件夹吧，我想覆盖本身，试着写了下
```
const mm=require('egg-mock');
const app=mm.cluster({ worker: 1, sticky: true });
await app.ready();
```
会刷屏，显示logs文件夹不能访问，插件似乎也没有正确加载，不太懂这个怎么弄。

**Comment by yyh1102** [comment]
同问。。按照 @ngot 给的方式也不太行。

**Comment by AshinWu** [comment]
官方没有给答复吗？这个问题就这样挂着？
关于egg socket-io单元测试怎么覆盖app/io目录的问题都没有标准答案。
socketio中的controller怎么测才能cov到?

**Comment by atian25** [comment]
> 这种写法是覆盖到了egg-socket.io/test/fixtures/apps/文件夹吧，我想覆盖本身，试着写了下
> 
> ```
> const mm=require('egg-mock');
> const app=mm.cluster({ worker: 1, sticky: true });
> await app.ready();
> ```
> 
> 会刷屏，显示logs文件夹不能访问，插件似乎也没有正确加载，不太懂这个怎么弄。

/test/fixtures 是指定 baseDir 的时候才需要的，app 测试会自动识别的，可以去看下 egg-mock 的文档。

刷屏是其他问题吧，提交最小可复现仓库，我们才能跟进。

**Comment by AshinWu** [comment]
> /test/fixtures 是指定 baseDir 的时候才需要的，app 测试会自动识别的，可以去看下 egg-mock 的文档。
> 
> 刷屏是其他问题吧，提交最小可复现仓库，我们才能跟进。

我想请教一下egg单元测试怎么覆盖io目录?现在我能在测试用来中新建一个socket-client，然后只能够与"/"下的controller通讯(只能靠emit通讯，在io/controller/xx中console不出任何东西) , 而且测试也覆盖不了io目录，怎么解决？

**Comment by atian25** [comment]
提供一个最小可复现的仓库，我们来看看

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/4119
