### ISSUE TITLE
egg-opentracing插件的日志输出路径无法配置

### ISSUE THREAD

**Issue by Linjovi** [eggjs/egg#3907]
我发现egg-opentracing插件输出的日志路径是在插件的config中写死的，路径为‘root/logs/appname/opentracing.log'。当我由于业务需要，将egg的日志路径改为’./eggLogs'时，我发现opentracing的日志仍然输出在‘./logs’下。我也没有找到日志路径的配制方法，我认为也许添加添加一个配置项会更好，或者是我没找到配置的方法吗？

**Comment by Linjovi** [comment]
目前我是这样做的
```
  config.opentracing = {
    collector: {
      zipkin: require('../src/lib/zipkin_collector'),
      log:false
    },
    customLogger:{
      opentracingLogger: {
        file: path.join(appInfo.root, 'eggLogs', appInfo.name, 'opentracing.log'),
        consoleLevel: 'NONE',
      },
    }
  };
```
但是总感觉这种方法很怪异，而且不清楚会不会有后续问题。

**Comment by popomore** [comment]
可以调整成相对路径了

**Comment by atian25** [comment]
这是日志本身的设计，线上指定到 home 目录。

你也可以自行覆盖掉 root https://github.com/eggjs/egg/pull/4468
