### ISSUE TITLE
ctx.curl不同步

### ISSUE THREAD

**Issue by albertyou2** [eggjs/egg#3908]
egg@2.21.1 
node v11.14.0
centos 7
偶尔发现 Ctx.curl不是同步执行的

这个是在小程序登录时发现的现象
代码大致如下：

    const wechatRes = await ctx.curl(wechatUrl, {
      dataType: 'json',
      method: 'GET'
    });
    console.log(wechatRes);  //    11111    打印微信返回结果

    // 22222  打印返回的值具体长
    console.log("encryptedData.    length "  + body.encryptedData.length);
    console.log("iv.    length "  + body.iv.length);
    console.log("code.    length "  + body.code.length);

按照正常同步的逻辑，这里应该是 微信的返回结果全部打印完了才会印 22222的内容吧？

但是实际打印结果如下：

encryptedData.    length 536  //  ！！！ 先打印了

{ data:
   { session_key: '6R3v+wEr85EG8ONVSFn95w==',
     openid: 'ovbCQ4oqWZR9JP6AsF1-w0k1CDQs' },
  status: 200,
  headers:
   { connection: 'keep-alive',
     'content-type': 'text/plain',
     date: 'Wed, 28 Aug 2019 02:38:02 GMT',
     'content-length': '82' },
  res:
   { status: 200,
     statusCode: 200,
     statusMessage: 'OK',
     headers:
      { connection: 'keep-alive',
        'content-type': 'text/plain',
        date: 'Wed, 28 Aug 2019 02:38:02 GMT',
        'content-length': '82' },
     size: 82,
     aborted: false,
     rt: 183,
     keepAliveSocket: true,
     data:
      { session_key: '6R3v+wEr85EG8ONVSFn95w==',
        openid: 'ovbCQ4oqWZR9JP6AsF1-w0k1CDQs' },
     requestUrls:
      [ 'https://api.weixin.qq.com/sns/jscode2session?appid=wx6ce3f2a2162a4019&secret=4d1a3b75474359952933b7f86614eb7e&js_code=023vJaBu0PAvhj1fMWBu0r4aBu0vJaBZ&grant_type=authorization_code' ],
     timing: null,
     remoteAddress: '140.207.119.12',
     remotePort: 443,
     socketHandledRequests: 2,
     socketHandledResponses: 2 } }
encryptedData.    length 536   // ！！！
iv.    length 24       // ！！！
code.    length 32 //！！！

**Comment by atian25** [comment]
跟 egg 没啥关系，这是 Node 的 await 机制，如果真有这么问题，那就是 V8 的超级 bug 了。

你不用 console 看看，自己排查下。

如有问题，提供最小可复现方式

**Comment by fengmk2** [comment]
@albertyou2 你的 issue 里面有密钥，我先将你的内容修改了。
