### ISSUE TITLE
egg-multipart 如何自定义错误返回呢

### ISSUE THREAD

**Issue by kekobin** [eggjs/egg#3910]
使用egg-multipart时，对于不支持的文件后缀，出现过两种返回，
一种是很容易就超时了：
![image](https://user-images.githubusercontent.com/4536310/63829566-7ebe6980-c99c-11e9-8c96-0ca40ad1b4f4.png)

一种是400：
![image](https://user-images.githubusercontent.com/4536310/63829641-b2998f00-c99c-11e9-8907-6d3229c90d5a.png)

而且都是egg-multipart插件层直接返回的，想问下这个返回不能自定义么？比如 想返回自定义的code和msg？

**Comment by x-cold** [comment]
全局的错误捕获看下相关文档：https://github.com/eggjs/egg-onerror

**Comment by kekobin** [comment]
> 全局的错误捕获看下相关文档：https://github.com/eggjs/egg-onerror

那想问下对于总是超时这种，全局捕获不到的错误有什么好的处理方式么？只在传大文件的时候会这样，但是在允许上传的大小范围内的

**Comment by x-cold** [comment]
建议贴上最小可复现代码，busboy 似乎没有提供一个超时机制，如有必要可以直接实现一个。

**Comment by kekobin** [comment]
> 建议贴上最小可复现代码，busboy 似乎没有提供一个超时机制，如有必要可以直接实现一个。

其实就是使用的官方示例的方式实现的上传: [文件方式](https://eggjs.org/zh-cn/core/httpclient.html#%E4%BB%A5-multipart-%E6%96%B9%E5%BC%8F%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6).    
但是对于不支持的文件后缀，总是超时且没有任何返回：    
![image](https://user-images.githubusercontent.com/4536310/64089380-5d80c300-cd78-11e9-8ac0-a1b86eafea4b.png)

**Comment by atian25** [comment]
之前好像底层库有个小 bug，可能已经 ok 了，可以再试试，有问题的话带可复现仓库提个 issue 我们再看下。
