### ISSUE TITLE
router.url 方法的疑问

### ISSUE THREAD

**Issue by cyp178** [eggjs/egg#3915]
按照官方的用法是：
router.get('routerName', '/xxx/:id/:name', controller.index.xxx );
app.router.url('routerName', { id: 1, name: 'egg' }) ;
=> '/xxx/1/egg'  这是没问题的
但是当路由下面类似的：
router.get('routerName', '/xxx/:id(\\d+)/:name', controller.index.xxx );
app.router.url('routerName', { id: 1, name: 'egg' }) ;
=> '/xxx/1(\d+)/egg'  这个就没法用了；

我看了源码 url 方法， 只有这句：
url = url.replace(/:([a-zA-Z_]\w*)/g, function($0, key) {
        if (utility.has(args, key)) {
          const values = args[key];
          replacedParams.push(key);
          return utility.encodeURIComponent(Array.isArray(values) ? values[0] : values);
        }
        return $0;
      });
请问这种路由如何正确的生成 url ?

**Comment by atian25** [comment]
这块可以考虑用 https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp 来实现
