### ISSUE TITLE
npm init egg --type=simple初始化失败（提示：安装 create-egg@latest 失败，错误代码：1），想问下这个问题怎么解决？

### ISSUE THREAD

**Issue by mosicong** [eggjs/egg#3916]
## What happens?

按照官方文档初始化egg项目失败
$ npm init egg --type=simple bug

npm ERR! code ENOLOCAL
npm ERR! Could not install from "Files\nodejs\node_cache\_npx\14516" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2019-08-29T06_34_38_294Z-debug.log
安装 create-egg@latest 失败，错误代码：1

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
错误日志
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-egg@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Program',
1 verbose cli   'Files\\nodejs\\node_cache\\_npx\\14516',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session e3854aec37858c34
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for file:Files\nodejs\node_cache\_npx\14516 Could not install from "Files\nodejs\node_cache\_npx\14516" as it does not contain a package.json file.
8 http fetch GET 304 https://registry.npmjs.org/create-egg 1527ms (from cache)
9 silly pacote tag manifest for create-egg@latest fetched in 1548ms
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 1559ms
12 verbose stack Error: ENOENT: no such file or directory, open 'D:\mosc\30days\MyProject\egg-example1\Files\nodejs\node_cache\_npx\14516\package.json'
13 verbose cwd D:\mosc\30days\MyProject\egg-example1
14 verbose Windows_NT 10.0.17134
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-egg@latest" "--global" "--prefix" "C:\\Program" "Files\\nodejs\\node_cache\\_npx\\14516" "--loglevel" "error" "--json"
16 verbose node v10.16.3
17 verbose npm  v6.9.0
18 error code ENOLOCAL
19 error Could not install from "Files\nodejs\node_cache\_npx\14516" as it does not contain a package.json file.
20 verbose exit [ 1, true ]

## 相关环境信息
- **操作系统**：win 10
- **Node 版本**：v10.16.3
-** Npm版本：6.9.0
- **Egg 版本**：

**Comment by mosicong** [comment]
![image](https://user-images.githubusercontent.com/19772525/63916800-bb0ccb00-ca6b-11e9-96d0-ab96f27bc311.png)
![image](https://user-images.githubusercontent.com/19772525/63916882-e68fb580-ca6b-11e9-8d77-8583931a312f.png)

**Comment by atian25** [comment]
感觉是你的 npm 的问题，试着删除 node_cache_npx 目录，然后升级下 npm 版本看看吧

**Comment by mosicong** [comment]
有试过完全卸载nodejs和npm,之后重装，不过好像没有作用

**Comment by mosicong** [comment]
![image](https://user-images.githubusercontent.com/19772525/63997855-52d4ec80-cb32-11e9-8883-a914d36bac30.png)
这个是我的node_cache目录路径，是不是因为路径有空格？

**Comment by atian25** [comment]
> 7 silly fetchPackageMetaData error for file:Files\nodejs\node_cache_npx\14516 Could not install 

这里来看是 Files 前面被截断了，这一块是 npm 的内部逻辑了，不确定是不是 win 的 bug。

你可以先用：

```bash
npm install egg-init -g
egg-init --type=simple 
```

**Comment by mosicong** [comment]
嗯嗯，目前用的是这种方式，谢谢解答

**Comment by xygzyf2008** [comment]
我跟你遇到同样的问题了：
![image](https://user-images.githubusercontent.com/4231482/80269419-4c5b3c80-86e2-11ea-9d91-9e80b435b6a1.png)
看了下log，原因是node安装的路径下有空格导致的：
![image](https://user-images.githubusercontent.com/4231482/80269407-fedecf80-86e1-11ea-8080-f3b0124cbc37.png)
执行下面2条命令，指定下路径就行了：
npm config set prefix "D:\nodejs\node_global"
npm config set cache "D:\nodejs\node_cache"
![image](https://user-images.githubusercontent.com/4231482/80269784-55014200-86e5-11ea-8bdc-875bf6d6e181.png)

**Comment by liugezhou** [comment]
![image](https://user-images.githubusercontent.com/29797703/108933168-a66fba00-7685-11eb-9337-5d60984c63c7.png)
我这是等待了五分钟，控制台没有蠕动

**Comment by mosicong** [comment]
> ![image](https://user-images.githubusercontent.com/29797703/108933168-a66fba00-7685-11eb-9337-5d60984c63c7.png)
> 我这是等待了五分钟，控制台没有蠕动

npm install egg-init -g
egg-init --type=simple
试下这样的初始化方式

**Comment by ruibaby** [comment]
同样的问题，使用 yarn 可以成功：

```
yarn create egg --type=simple
```

**Comment by atian25** [comment]
> ![image](https://user-images.githubusercontent.com/29797703/108933168-a66fba00-7685-11eb-9337-5d60984c63c7.png)
> 我这是等待了五分钟，控制台没有蠕动

很明显你连接 npm 太慢了，要切源。

`npm init egg -r china`
