### ISSUE TITLE
egg-redis 目前没有incr、decr、mget、hDel、hIncrBy、hIncrByFloat等操作的么？

### ISSUE THREAD

**Issue by kekobin** [eggjs/egg#3917]
hi，egg-redis 目前没有incr、decr、mget、hDel、hIncrBy、hIncrByFloat等操作的么？看了里面引用的ioredis也是没找到。

**Comment by thonatos** [comment]
`egg-redis` 包装了 `ioredis`，不支持的命令可以参考其文档自行拓展。

> getBuiltinCommands
> https://github.com/luin/ioredis/blob/master/API.md#redisgetbuiltincommands--arraystring

**Comment by kekobin** [comment]
> `egg-redis` 包装了 `ioredis`，不支持的命令可以参考其文档自行拓展。
> 
> > getBuiltinCommands
> > https://github.com/luin/ioredis/blob/master/API.md#redisgetbuiltincommands--arraystring

哦，好的，thx！
