### ISSUE TITLE
egg官网是挂掉了吗？

### ISSUE THREAD

**Issue by JingLMalan** [eggjs/egg#3918]
如题

**Comment by JasinYip** [comment]
我这边看起来一切正常

**Comment by JingLMalan** [comment]
为啥我这边开不开代理都打不开，ping也不通

**Comment by JasinYip** [comment]
> 为啥我这边开不开代理都打不开，ping也不通

换个网络试试？需要先排除一下网络的问题

**Comment by JingLMalan** [comment]
> > 为啥我这边开不开代理都打不开，ping也不通
> 
> 换个网络试试？需要先排除一下网络的问题

可以肯定的是，我这边的网络没有问题，中午再试试吧。
