### ISSUE TITLE
怎么给egg服务添加https访问？

### ISSUE THREAD

**Issue by FIWE2030** [eggjs/egg#3919]
## Background
网上找了很多教程，还是不明白怎么用egg将http请求变为https的请求，求教下解决方案

## Proposal
我在网上看，很多都是ngix服务器配置https证书，然后再通过代理请求egg服务，但是不知道怎么做代理，还有，可以直接在egg里配置吗，很苦恼

**Comment by Jeff-Tian** [comment]
不用到 egg 这层，直接 nginx 可以配置。如果嫌麻烦，可以直接使用 cloudflare 的方案，把域名解析交给他们，启动他们自带的 https 就可以了。

**Comment by FIWE2030** [comment]
可以，很方便，但是我看网上，那个设置应该是
![image](https://user-images.githubusercontent.com/21697518/64097977-36d28480-cd98-11e9-861a-74e747c17019.png)

**Comment by FIWE2030** [comment]
回复速度超快，点赞
