### ISSUE TITLE
 Cannot read property 'mysql' of undefined

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#3920]
可能是我知识储备不足，请大佬指正，谢谢
报错: Cannot read property 'mysql' of undefined

aArr.each(async function(index) {
          let httpUrl=host+$(this).attr("href");
          let  objOne={
            type:typeArr[a],
            url:httpUrl,
          };
          console.log(objOne);
          let checkSpider=await meme.app.mysql.query("select * from spider where url=?",[httpUrl]);
          if(checkSpider.length>0){
            return false;
          }

**Comment by atian25** [comment]
谁知道 meme.app 是哪来的啊，undefined 就自己检查下咯
