### ISSUE TITLE
如何使用egg-jwt 解密不同的secret生成的token

### ISSUE THREAD

**Issue by haobingG** [eggjs/egg#3923]
web前端和后台管理系统共用一个egg的服务，想要在路由层面做 管理系统和web前端的token认证，目前用egg-jwt 只能设置一个secret 解密也只能是用这个 ，如何操作可以设置多个 secret 验证不同的系统，需要自己写中间件 还是 egg-wjt可以解决？

**Comment by atian25** [comment]
egg-jwt 不是官方维护的插件，可以去看下对应的仓库和作者
