### ISSUE TITLE
egg+ts 根据官网文档尝试骨架生成项目npm run start 启动访问不了

### ISSUE THREAD

**Issue by jiaotashidi** [eggjs/egg#3927]
根据官方快速入门提示进行操作如下
```
mkdir showcase && cd showcase
npm init egg --type=ts
npm i
npm run dev
```
npm run dev正常启动访问
npm run start启动控制台无异常
但是浏览器访问提示：Internal Server Error, real status: 500

**Comment by jiaotashidi** [comment]
npm run start 启动后，浏览器访问http://127.0.0.1:7001/ 提示 Internal Server Error, real status: 500

**Comment by jiaotashidi** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙或访问[国内镜像站点](https://eggjs.app)。

npm run start 启动后，浏览器访问http://127.0.0.1:7001/ 提示 Internal Server Error, real status: 500

**Comment by Jeff-Tian** [comment]
用 `EGG_SERVER_ENV=local npm run dev` 运行，页面上会显示具体的错误信息。`npm run start` 会认为在生产环境，不显示具体错误信息。

**Comment by Jeff-Tian** [comment]
https://github.com/eggjs/egg-onerror/pull/30
