### ISSUE TITLE
onerror配置all时ctx.body是否必须为string？

### ISSUE THREAD

**Issue by iloook** [eggjs/egg#3928]
## 遇到的情况

当config中设置onerror为如下时：
```js
    onerror: {
      all(err, ctx) {
        ctx.body = { message: 'error' };
        ctx.status = 500;
      },
    },
```
并且此时请求的header里没有`Accept: application/json`；
那当程序在出现exception时，控制台会报错：
```
nodejs.TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
```
如果ctx.body为string（或用JSON.stringify）就没有这个问题；

## 引出的疑问

如果想要实现不论请求header的accept怎样，报错时总是返回json，应该如何用框架实现呢？

**Comment by Jeff-Tian** [comment]
那就

```
ctx.body = JSON.string(err)
```
?

或者不想每次都 JSON.stringify，可以在 all() 里判断一下 ctx.headers，再看是直接返回对象还是 stringify 的结果。

**Comment by Liqiankun** [comment]
```
{
   Accept: 'application/json'
}
```

**Comment by shuidian** [comment]
> ## 遇到的情况
> 当config中设置onerror为如下时：
> 
> ```js
>     onerror: {
>       all(err, ctx) {
>         ctx.body = { message: 'error' };
>         ctx.status = 500;
>       },
>     },
> ```
> 
> 并且此时请求的header里没有`Accept: application/json`； 那当程序在出现exception时，控制台会报错：
> 
> ```
> nodejs.TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
> ```
> 
> 如果ctx.body为string（或用JSON.stringify）就没有这个问题；
> 
> ## 引出的疑问
> 如果想要实现不论请求header的accept怎样，报错时总是返回json，应该如何用框架实现呢？

遇到了同样的问题，这块后续有找到解决方案吗？body都用字符串肯定是不合适的，业务上即使是错误信息一般也是一个包含错误码和错误信息的对象的。

**Comment by atian25** [comment]
onerror 不是有 json 等配置么，既然不是 accept json，自然是 string 啦，你非要在 all 里面就自己 stringify 呗

瞅一眼 egg-onerror 源码或 README 其实就懂了
