### ISSUE TITLE
Typescript + egg-mock cluster 報錯

### ISSUE THREAD

**Issue by alickmail** [eggjs/egg#3930]
## What happens?

使用 Typescript + egg-mock 的 mm.cluster 起动後，出现 `nodejs.Error: Please set config.keys first` 错误

我知道 `npm start` 前需要 `npm tsc`，这样起动是没问题的。但 mm.cluster 跑测试就会出现问题。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/alickmail/typescript-eggjs-mm-cluster-error

## 复现步骤，错误日志以及相关配置
1. git clone https://github.com/alickmail/typescript-eggjs-mm-cluster-error
1. `npm install`
1. `npm run 'test-cluster'`
2. 在 chrome 访问 localhost:17001
3. 出现 `nodejs.Error: Please set config.keys first` 错误

使用 egg-mock cluster 的原因是 egg-socket.io 必须使用 cluster 模式才能成功测试

### 參考：
https://github.com/eggjs/egg-socket.io/blob/master/test/io.test.js

## 相关环境信息
- **操作系统**：macOS Mojave (Mac Pro)
- **Node 版本**：v10.13.0
- **Egg 版本**：
```
 "egg": "^2.6.1",
 "egg-scripts": "^2.6.0"
 "egg-ci": "^1.8.0",
 "egg-bin": "^4.11.0",
 "egg-mock": "^3.16.0",
 "tslib": "^1.9.0",
 "tslint": "^5.0.0",
 "tslint-config-egg": "^1.0.0",
 "typescript": "^3.0.0"
```

謝謝

**Comment by alickmail** [comment]
这是 egg-mock/lib/start-cluster 文件，只要加入这句就能解决找不到 `config.default.js` 的问题
```
#!/usr/bin/env node

'use strict';

if (process.env.EGG_BIN_PREREQUIRE) require('./prerequire');

const options = JSON.parse(process.argv.slice(2));
if(!options.require) {
  options.require = [];
}

options.require.push(require.resolve('ts-node/register')); // 加入这句
require(options.framework).startCluster(options);
```

期待更好的解决方案，谢谢！

**Comment by atian25** [comment]
cluster 里面是不可能去加 ts-node 的，我印象中 egg-bin 已经会判断然后注入 ts-node 的了。

cc @whxaxes

**Comment by alickmail** [comment]
我明白在生产环境是不用加载 ts-node ，因为生产环境是是用 tsc 生成好的 js。

但是如果我要跑 socketio 的测试，我必须使用 egg-mock 的 mm.cluster。这里是例子：
https://github.com/eggjs/egg-socket.io/blob/master/test/io.test.js

当我调用 
```
app = mm.cluster({
      baseDir: '../../',
      coverage: false,
    });
```

cluster.js 会使用 start-cluster 的 script，fork 一个 process 出来，我估计就是 fork 出来的这个 process 没有支持 ts

```
#!/usr/bin/env node

'use strict';

if (process.env.EGG_BIN_PREREQUIRE) require('./prerequire');

const options = JSON.parse(process.argv.slice(2));

require(options.framework).startCluster(options); <- 这里是在没有 ts 支持

```

谢谢

**Comment by atian25** [comment]
```js
mm.cluster({
   baseDir: '../../',
   coverage: false,
   opt: {
     execArgv: [ '--require', require.resolve('ts-node/register') ]
   }
});
```

可以试下这样，cluster 是继承 coffee 的，我记得有个 opt 的参数的。

**Comment by ahungrynoob** [comment]
遇到相同的问题 加了opt就报了另外的错误:

```bash
/Users/xudading/work/lazada/iris-proxy/node_modules/_typescript@3.5.3@typescript/lib/typescript.js:122217
                throw new Error("Could not find sourceFile: '" + fileName + "' in " + (program && JSON.stringify(program.getSourceFiles().map(function (f) { return f.fileName; }))) + ".");
                      ^
Error: Could not find sourceFile: '/Users/xudading/.node-spawn-wrap-75420-68ff7c5550db/node'
```

**Comment by ahungrynoob** [comment]
egg-bin test 没有问题 egg-bin cov 会有上面的问题

**Comment by ahungrynoob** [comment]
查了一天 解决了。
方案如下：
https://github.com/istanbuljs/istanbuljs/tree/master/packages/nyc-config-typescript
```typescript
beforeEach(() => {
      app = mm.cluster({
        opt: {
          execArgv: [
            '--require',
            require.resolve('ts-node/register/transpile-only'),
            '--require',
            require.resolve('source-map-support/register'),
            '--recursive',
          ],
        },
      } as MockOption);
      return app.ready();
    });
```

**Comment by ahungrynoob** [comment]
找到根本原因了 https://github.com/istanbuljs/spawn-wrap/blob/master/lib/mungers/node.js#L60
这里加了shim 却没有添加 --require ts直接报错了

**Comment by ahungrynoob** [comment]
最终解决方案:
package.json中修改为:
```
"cov": "SPAWN_WRAP_SHIM_ROOT=\"node_modules\" egg-bin cov --ts"
```

**Comment by atian25** [comment]
看起来是没权限写入 HOME，为啥？

可以提个 PR 给 mm.cluster 把这个 env 内置进去

**Comment by ahungrynoob** [comment]
@atian25 没权限写入HOME是那个人的情况，我这边是因为这个shim的路径在HOME，导致typescript报`Could not find sourceFile`，我把source file都打印出来了，都是一些单测覆盖到的源文件和.d.ts文件，我理解应该HOME不在typescript的file文件查找范围，cwd/node_modules就可以 ，忙完这阵 我pr 一个～

**Comment by atian25** [comment]
land egg-bin@4.13.2

**Comment by whlsxl** [comment]
> egg-bin 的 ts-node 应该会继承下去吧，可能没放 env 里面。
> 
> 可以先：
> 
> ```js
> mm.cluster({
>    baseDir: '../../',
>    coverage: false,
>    opt: {
>      execArgv: [ '--require', require.resolve('ts-node/register') ]
>    }
> });
> ```
> 
> 可以试下这样，cluster 是继承 coffee 的，我记得有个 opt 的参数的。

看了下，`mm.app`不支持`opt`
```
mm.app(
   baseDir: '../../',
   coverage: false,
   opt: {
     execArgv: [ '--require', require.resolve('ts-node/register') ]
   }
)
```

**Comment by atian25** [comment]
因为 cluster 是继承 Coffee 的，而 app 是为了单测速度在单进程里面做。

**Comment by whlsxl** [comment]
> 因为 cluster 是继承 Coffee 的，而 app 是为了单测速度在单进程里面做。

遇到个尴尬的问题，在`js`项目里，测试加载`ts`的apps。

难道只能分开两个命令？

**Comment by atian25** [comment]
这不是命令啊，你一个单测不是有个 case 么，一个用 mm.app，一个用 mm.cluster 啊

**Comment by whlsxl** [comment]
[最小版本](https://github.com/whlsxl/egg-mock/tree/2f084cf27fa4007506b939e1ef36ca8d3dafa539)
这个需求比较特殊，在`js`项目里运行`ts`测试，
`npx egg-bin test --ts=true test/app/run.test.js` 的话，提示`TypeError: Class constructor BaseContextClass cannot be invoked without 'new'`。
直接`test`，`ts`文件没编译，还是会报错。
麻烦 @atian25 帮忙看下。

**Comment by whlsxl** [comment]
@atian25 是这个写test的需求
https://github.com/eggjs/egg-graphql/pull/30#issuecomment-589149141
