### ISSUE TITLE
passport-github 授权之后跳到/passport/github/callback?code=def1a7e 出现401未授权

### ISSUE THREAD

**Issue by Chasen-Zhang** [eggjs/egg#3931]
![image](https://user-images.githubusercontent.com/15354455/64588860-38bec800-d3d6-11e9-874b-ae6b62ecdd95.png)

是缺少什么配置吗？

node：v10.16.1
egg：v2.15.1
系统：win7

**Comment by Jeff-Tian** [comment]
是不是因为在本地调试的缘故？我也对接了一下 passport github，没这个问题。
