### ISSUE TITLE
关于egg-socket.io的扩展问题

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#3932]
我使用咱们的egg-socket.io进行即时通讯的管理工作，现在遇到了一个比较头疼的问题。

我的项目结构是严格按照咱们egg的推荐完成的，IM消息的处理顺序是`route->io/controller->service`，由于需要处理一些在线用户的业务方面的问题，所以需要存储一些信息（闭包），我把这个比较大的信息，暂时存在了service里面。目前遇到的问题就是，业务越来越多，我想把service进行拆分，否则太难管理了，但是没想好这个闭包（暂时是内存存储，以后可能改为Redis）放在哪里？libs里面？

咱们没有钉钉群之类的吗？我这个问题发在这里感觉不合适

**Comment by weiyunpeng** [comment]
同问

**Comment by ngot** [comment]
具体是什么数据？ service 设计上是 context 级别的，是无状态的，无法存储数据的，因为用完就丢弃了实例。 如果是是 context 级别的数据，那么就直接放到 context 上就好了，符合 koa 的设计原则。

**Comment by hezhongfeng** [comment]
@ngot 
我说说实际情况：
我这边需要保存用户的连接状态，所以我在service层后面维护了一个大的map，用来存储连接用户的基本信息。
越来越多的需求来临的时候，这个大map就越来越复杂，导致这个service很难维护，所以我就想把这个map和service拆分一下，现在遇到的问题就是我不确定拆分完毕的map和service是一种什么关系，map放在哪里比较合适。

**Comment by looksgood** [comment]
连接用户数据放到redis里面维护好了，可以根据client id进行key存储

**Comment by hezhongfeng** [comment]
谢谢，我也是这么想的，先关闭了
