### ISSUE TITLE
egg 开发一个框架，框架里的中间件放到最后执行

### ISSUE THREAD

**Issue by kekobin** [eggjs/egg#3934]
hi，我现在在开发一个框架，框架里面有个中间件midA，在业务代码继承这个框架进行开发时，业务代码有个中间件midB，按照目前中间件加载顺序是 midA -> midB, 有什么方式可以让midA一直在app.middleware最后么？

**Comment by atian25** [comment]
可以回去看下 koa 的洋葱模型
