### ISSUE TITLE
关于错误状态码的放置问题

### ISSUE THREAD

**Issue by LiZhouYang5612** [eggjs/egg#3935]
我们现在所有项目的错误状态码是集成在一个插件里的，补充错误状态码不是很方便。打算一些公共的错误状态码放到插件里，各项目特有的错误状态码归项目自身管理。egg项目错误状态码放在哪里合适呢？

**Comment by atian25** [comment]
配置个 customLoader，加个 loadunit 参数，挂载到 app.ErrorCode 上
