### ISSUE TITLE
扩展校验模块，添加严格校验，当请求中出现额外参数时，返回异常

### ISSUE THREAD

**Issue by chenxingli1** [eggjs/egg#3936]
## Background
对于部分请求，可能接收到额外参数，比如某个数据插入接口，会校验指定参数类型，但是出现多余传参，额外的参数列也会进入SQL语句，导致执行sql报错。

## Proposal
Describe the solution you'd like, better to provide some pseudo code.
try {
      ctx.validate({
        // 校验rules
        id: { type: 'int', required: true },
        name: { type: 'int', required: true },
      }
      // 需要校验的对象
      , { id: 'ertyu', age: '1' }
     // 是否严格校验
      , true);
    } catch (error) {
     // 校验报错
      return this.paraError(error.errors);
    }
## Additional context
![image](https://user-images.githubusercontent.com/26812703/65104357-bf415e00-da03-11e9-9637-d199de04deb3.png)

**Comment by atian25** [comment]
自己扩展 rule 即可。可以参考下 https://www.yuque.com/egg/nodejs/controller-and-params-validator

**Comment by chenxingli1** [comment]
> 自己扩展 rule 即可。可以参考下 https://www.yuque.com/egg/nodejs/controller-and-params-validator

这个可以判断是否有多余的参数传入吗？
![image](https://user-images.githubusercontent.com/26812703/65104764-35929000-da05-11e9-8ace-7ffd9ebbd06b.png)
比如说这个age是多传参数

**Comment by huangyingzheng** [comment]
请问你后来是怎么处理多余的参数呢？

**Comment by chenxingli1** [comment]
最后我拉取自己的分支作为module，其他方式没有再去想了，我也就用了一次node. js做项目，见谅。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月26日(周五) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [eggjs/egg] 扩展校验模块，添加严格校验，当请求中出现额外参数时，返回异常 (#3936)




 
请问你后来是怎么处理多余的参数呢？
