### ISSUE TITLE
使用postman上传binary数据会报Content-Type  must be multipart/*

### ISSUE THREAD

**Issue by bymaxchen** [eggjs/egg#3937]
请问这是功能缺陷还是处于什么目的不允许直接接受二进制数据呢？

## 相关环境信息
- **操作系统**：
windows 10
- **Node 版本**：
8.9.4
- **Egg 版本**：
1.7.0

**Comment by bymaxchen** [comment]
![image](https://user-images.githubusercontent.com/40656194/65140989-52998400-da42-11e9-8651-b178c5e787d6.png)

**Comment by atian25** [comment]
这是要求你加上对应的 header，可以看下 HTTP 协议

**Comment by bymaxchen** [comment]
> 这是要求你加上对应的 header，可以看下 HTTP 协议

我想要的请求头是：
application/octet-stream

这个不可以支持吗？

**Comment by supperchong** [comment]
用的`this.ctx.getFileStream()`? 二进制文件的话直接 `this.ctx.req.pipe(fs.createWriteStream('./filename'))`

**Comment by atian25** [comment]
`getFileStream` 只支持 mulitipart

如果你是自己的 header 的话，自己操作 req 的 stream，注意要做好 stream 的异常处理。

**Comment by supperchong** [comment]
```js
if (this.ctx.header['content-type'] === 'application/octet-stream') {
      const stream = this.ctx.req
      try {
        const destStream = fs.createWriteStream(filePath)
        await awaitWriteStream(stream.pipe(destStream))
      } catch (err) {
        await sendToWormhole(stream)
        throw err
      }
    }
```
或者
```js
const { pipeline } = require('stream')
try {
      const stream = this.ctx.req
      const destStream = fs.createWriteStream(filePath)
      await pipeline(
        stream,
        destStream,
      );
      console.log('Pipeline succeeded');
    } catch (err) {
      console.error('Pipeline failed', err);
    }
```

**Comment by atian25** [comment]
https://github.com/mafintosh/pump 可以关注下

**Comment by supperchong** [comment]
@atian25  https://nodejs.org/en/docs/guides/backpressuring-in-streams/ .pump is only necessary for Nodejs 8.x or earlier, as for Node 10.x or later version, pipeline is introduced to replace for pump. This is a module method to pipe between streams forwarding errors and properly cleaning up and provide a callback when the pipeline is complete.

**Comment by atian25** [comment]
> @atian25 https://nodejs.org/en/docs/guides/backpressuring-in-streams/ .pump is only necessary for Nodejs 8.x or earlier, as for Node 10.x or later version, pipeline is introduced to replace for pump. This is a module method to pipe between streams forwarding errors and properly cleaning up and provide a callback when the pipeline is complete.

cc @fengmk2
