### ISSUE TITLE
为什么在 .gitignore 里忽略掉 package-lock.json

### ISSUE THREAD

**Issue by xuxu7** [eggjs/egg#3939]
## What happens?
通过 `npm init egg --type=simple` 生成的项目，为什么把 `package-lock.json` 加入到 .gitignore?

通常情况下不是建议提交`package-lock.json` 么?

## 最小可复现仓库
https://github.com/eggjs/examples/blob/master/todomvc/.gitignore

**Comment by atian25** [comment]
[为什么我不使用 shrinkwrap（lock）](https://zhuanlan.zhihu.com/p/22934066)

有需要自己删掉。
