### ISSUE TITLE
egg如何搭建OAuth2认证

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#394]
egg如何搭建OAuth2认证

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg/issues/38

**Comment by TDiDa** [comment]
请问下egg如何搭建自己的OAuth2登录认证

**Comment by atian25** [comment]
@TDiDa 参见: https://github.com/eggjs/egg/issues/38 等这个插件做完, 会有对应的文档说明

**Comment by atian25** [comment]
@TDiDa 你是想做 OAuth2 的服务方?

**Comment by TDiDa** [comment]
@atian25 是的

**Comment by fengmk2** [comment]
我这边目前还没需求，也没时间去实现，npm 上已经有很多中间件了，可以参考实现 https://www.npmjs.com/package/oauth2orize-koa

**Comment by TDiDa** [comment]
好的

**Comment by Azard** [comment]
我做了个插件：https://github.com/Azard/egg-oauth2-server

**Comment by atian25** [comment]
@Azard 赞
