### ISSUE TITLE
ts报错"类型“CustomController”上不存在属性“chat”"，找不到controller

### ISSUE THREAD

**Issue by zsfbest** [eggjs/egg#3940]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by GongJS** [comment]
请问这问题解决了吗？我也碰到这个问题。。。。在 typescript中，按照官方给的demo，

```
TSError: [egg-core] load file: /root/development/frontend/wecircle-server/app/router.ts, error: ⨯ Unable to compile TypeScript:
app/router.ts(22,47): error TS2339: Property 'nsp' does not exist on type 'CustomController'.
```
github地址：[https://github.com/GongJS/wecircle-server](url)

**Comment by zsfbest** [comment]
> 请问这问题解决了吗？我也碰到这个问题。。。。在typescript中，按照官方给的demo，
> 
> ```
> TSError: [egg-core] load file: /root/development/frontend/wecircle-server/app/router.ts, error: ⨯ Unable to compile TypeScript:
> app/router.ts(22,47): error TS2339: Property 'nsp' does not exist on type 'CustomController'.
> ```
> 
> github地址：[https](url) : [//github.com/GongJS/wecircle-server](url)

感觉是和typescript不支持,我打印io下的controller是有这个键的

**Comment by atian25** [comment]
因为 egg-ts-helper 没有帮你生成这个映射，需要看下 egg-ts-helper 的文档，或者自己手写 d.ts

**Comment by whxaxes** [comment]
也可以配置 egg-ts-helper 的配置，来支持生成

```json
// {cwd}/package.json

{
  "egg": {
    "framework": "egg",
    "tsHelper": {
      "watchDirs": {
        "socketio": {
          "enabled": true,
          "directory": "app/io",
          "declareTo": "Application.io",
          "generator": "auto"
        }
      }
    }
  }
}
```

试一下这么配置后，再跑一下 dev

**Comment by whxaxes** [comment]
https://github.com/whxaxes/egg-ts-helper/blob/master/README.zh-CN.md#custom-loader

**Comment by KaneOne** [comment]
我有遇到同样的问题，是按照egg-socket.io的说明在创建app\io\controll\chat.ts后，router.ts里进行路由注册的时候找不到controll下面的chat类

![image](https://user-images.githubusercontent.com/1954595/65587519-8f242d00-dfb8-11e9-9d34-0c8f6c5e19d7.png)

**Comment by KaneOne** [comment]
> 也可以配置 egg-ts-helper 的配置，来支持生成
> 
> ```json
> // {cwd}/package.json
> 
> {
>   "egg": {
>     "framework": "egg",
>     "tsHelper": {
>       "watchDirs": {
>         "socketio": {
>           "enabled": true,
>           "directory": "app/io",
>           "declareTo": "Application.io",
>           "generator": "auto"
>         }
>       }
>     }
>   }
> }
> ```
> 
> 试一下这么配置后，再跑一下 dev

试了，还是无法解析，感觉是ts-help没有生成

**Comment by whxaxes** [comment]
@KaneOne  看一下 typings 目录下有没有生成对应的声明文件，没有的话再检查一下配置对不对

**Comment by KaneOne** [comment]
> @KaneOne 看一下 typings 目录下有没有生成对应的声明文件，没有的话再检查一下配置对不对

@whxaxes 我在运行 npm run tsc 生成声明文件时就报错了，另外您说的检查配置应该是是检查哪里，感谢。
![image](https://user-images.githubusercontent.com/1954595/65815042-9ba8bf80-e21c-11e9-9888-3dc145236af3.png)

**Comment by KaneOne** [comment]
> @KaneOne 看一下 typings 目录下有没有生成对应的声明文件，没有的话再检查一下配置对不对

@whxaxes 在package.json中加入了配置信息，声明文件已经生成
![image](https://user-images.githubusercontent.com/1954595/65815118-9f891180-e21d-11e9-9eab-24f90394b637.png)
![image](https://user-images.githubusercontent.com/1954595/65815146-df4ff900-e21d-11e9-9903-b90cbb5a7902.png)

但是在运行 npm run dev时 出现新的错误
![image](https://user-images.githubusercontent.com/1954595/65815149-f1319c00-e21d-11e9-8aac-86ef823cad38.png)

**Comment by KaneOne** [comment]
嗨，@whxaxes 
这个问题可以再帮忙解答下嘛，感谢。

**Comment by whxaxes** [comment]
@KangOne 给个可以稳定复现的 repo

**Comment by KaneOne** [comment]
@whxaxes  repo地址：
https://github.com/KaneOne/eggjssocketio
npm run dev 就报错 麻烦看下 多写

**Comment by darlk** [comment]
在node_modules/egg-socket.io/index.d.ts中看到这个使用文档
![image](https://user-images.githubusercontent.com/650112/79245341-8dfe1300-7eaa-11ea-990a-59e9f5bbb4e4.png)
1. 在package.json加入
```
{
  "egg": {
    "framework": "egg",
    "tsHelper": {
      "watchDirs": {
        "socketio": {
          "enabled": true,
          "directory": "app/io",
          "declareTo": "Application.io",
          "generator": "auto"
        }
      }
    }
  }
}
```

2. 在app/io.controller/index.ts加入
```
import NspController from './nsp';

declare module 'egg' {
  interface CustomController {
    nsp: NspController;
  }
}
```

再次运行后至少能认出来了

**Comment by IndexXuan** [comment]
[我找到办法了](https://github.com/eggjs/egg/issues/3944#issuecomment-971436837)
