### ISSUE TITLE
npm run tsc 报错 Sequelize错误

### ISSUE THREAD

**Issue by fengluhome** [eggjs/egg#3941]
npm run tsc 报错 Sequelize错误 

`> ets && tsc -p tsconfig.json

[egg-ts-helper] create typings/app/extend/helper.d.ts (7ms)
[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/app/middleware/index.d.ts (0ms)
[egg-ts-helper] create typings/app/model/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (20ms)
[egg-ts-helper] create typings/config/plugin.d.ts (9ms)
[egg-ts-helper] create typings/app/service/index.d.ts (4ms)
[egg-ts-helper] create typings/app/index.d.ts (1ms)
app/service/article.ts:7:27 - error TS2339: Property 'Article' does not exist on type 'Sequelize'.

7     return this.ctx.model.Article.create(article);
                            ~~~~~~~

app/service/article.ts:11:42 - error TS2339: Property 'Article' does not exist on type 'Sequelize'.

11     const article = await this.ctx.model.Article.find({
                                            ~~~~~~~
`
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
V8.9
- **Egg 版本**：
V5.5.1

**Comment by whxaxes** [comment]
升级一下 egg-sequelize
