### ISSUE TITLE
关于getFileStream里面白名单的问题

### ISSUE THREAD

**Issue by HelloAny** [eggjs/egg#3947]
今天用`getFileStream`函数的时候发现docx和txt文件上传不了，于是去`_egg-multipart@2.9.0@egg-multipart`里翻源码，一开始以为是函数的问题，之后看到白名单里没有`.txt`和`.docx`，本人是小白，不知道为什么开发者不把这两个加入白名单，希望知道的同学能帮忙解答一下。

**Comment by HelloAny** [comment]
<img width="379" alt="1" src="https://user-images.githubusercontent.com/44696899/65416980-9e29a480-de2b-11e9-98b3-2b63c1a6ba23.png">

**Comment by atian25** [comment]
有需要就配置下 fileExtensions

**Comment by hyj1991** [comment]
这个本来就要你自己控制的，每个人允许上传文件的后缀需求都不一样，不符合公共组件 `default to good` 的设计

**Comment by HelloAny** [comment]
> 有需要就配置下fileExtensions。
> 
> whiteList是覆盖内置的，fileExtensions是添加。具体看文档https://github.com/eggjs/egg-multipart#custom-config

谢谢，了解了

**Comment by 854770857** [comment]
@atian25 您好，可以动态配置fileExtensions列表内容吗？现在不能确定要上传哪种类型的文件。需要做一个配置后缀的需求。

**Comment by atian25** [comment]
> https://github.com/eggjs/egg-multipart#custom-config

你用 whitelist 可以写函数
