### ISSUE TITLE
egg-sequelize 5.2 created_at 不能自动添加时间了是什么情况？需要手动去在插入数据的时候自己去添加吗？

### ISSUE THREAD

**Issue by JayenLee** [eggjs/egg#3948]
egg-sequelize 5.2 created_at 不能自动添加时间了是什么情况？需要手动去在插入数据的时候自己去添加吗？

**Comment by whxaxes** [comment]
自行看 sequelize5 的文档吧，egg-sequelize 就只是简单包了一层
