### ISSUE TITLE
[Feature Request] schedule定时任务在集群环境多实例会重复执行

### ISSUE THREAD

**Issue by TomorrowCat** [eggjs/egg#3949]
## Background
现在的schedule定时任务是在agent进程中不断递归调用setTimeout方法，在多服务器多实例的环境下，schedule定时任务就会同时执行多次，这种情况可能就需要换成其他第三方库，比如kue。
## Proposal
以后会不会考虑集成这种集群环境的定时任务，再就是目前不换成其他第三方库，有没有什么简单的好办法

**Comment by atian25** [comment]
集群环境的定时任务，需要有第三方服务支持，egg-schedule 预留了扩展接口，看下文档自己扩展下即可。

https://github.com/eggjs/egg-schedule#schedule-type

**Comment by TomorrowCat** [comment]
了解，感谢！

**Comment by atian25** [comment]
可以封装为一个单独插件，回馈给社区。
