### ISSUE TITLE
类型于多模块开发是怎样一个思路？

### ISSUE THREAD

**Issue by guohuihot** [eggjs/egg#3951]
## What happens?
现在有个需求是这样的，比如我开发了一个新闻系统（主系统），另外又想开发一个留言系统，后面可能还会有问答系统，这些系统间是独立的，也可以聚合到一起，可以随时拔插的那种（类似于多模块），但是系统间服务service可能会共享(需要通信)，我想知道这样一个需求egg能满足吗？谁给个思路

我大概看了下文档，貌似只能在一个系统里转

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by JasinYip** [comment]
controller、service 都是可以加文件夹的，不同的领域可以用文件夹区分即可；

如果领域比较复杂，或是说每个领域的请求量不一样希望能分开处理机子数量或流量的话，也可以分成多个不同的微服务，每个服务独立写，然后可以通过 RPC 的方式实现多服务间的通讯。

**Comment by zhennann** [comment]
CabloyJS是在EggJS的基础上做的上层框架，实现了模块化处理，以及模块之间的隔离。
可参考这篇文章：[https://cabloy.com/zh-cn/articles/eggborn-introduce.html](https://cabloy.com/zh-cn/articles/eggborn-introduce.html)

**Comment by guohuihot** [comment]
感谢你们的回复，谢谢
