### ISSUE TITLE
TS模式下 curl自定义heades头，编译不通过咋办？

### ISSUE THREAD

**Issue by zhentaoo** [eggjs/egg#3953]
TS模式下 curl自定义heades头，编译不通过咋办？
![image](https://user-images.githubusercontent.com/8733239/65591987-3b1d4680-dfc0-11e9-8499-8eb3e62b7b4d.png)

**Comment by whxaxes** [comment]
@zhentaoo  看 ts 错误... 都这么清晰告诉你 headers 里要 string 了 ...

**Comment by atian25** [comment]
仔细看报错，认真打 TS 基础。

**Comment by zhentaoo** [comment]
😂，打扰了
