### ISSUE TITLE
Doc bug report

### ISSUE THREAD

**Issue by sally2015** [eggjs/egg#3955]
## What happens?
In [security#man-in-middle attack with HTTP / HTTPS](https://eggjs.org/en/core/security.html#man-in-middle-attack)
> Framework provides HSTS Strict-Transport-security, this header will be opened by default, then let the HTTPS site not redirect to HTTP

But in `egg-security@2.5.0 config.default.js `,the hsts options enable is false.

**Comment by thonatos** [comment]
done.
