### ISSUE TITLE
开发环境中socket通信正常，生产环境中通信失效

### ISSUE THREAD

**Issue by GongJS** [eggjs/egg#3957]
我在`app/extend/helper.js`里定义里一个全局变量socketPoll，在io的中间件middleware里，根据不同的登录用户的id,存储不同的socket对象，
```
 socket.on('login', async (obj) => {
      console.log('用户' + obj._id + '进入聊天页面')
      //将用户id和当前用户的socket存起来
      ctx.helper.socketPoll[obj._id] = socket;
    });
```
到时候根据id，通过对应的socket来和指定的对象通信；
这个在本地开发环境中测试是正常，但是到来开发环境，就没法正常通信，是因为线上环境是多进程模式，导致helper.js里定义的全局对象，没法共享吗？

**Comment by duncup** [comment]
印象里并不是同用户访问时同进程应答。而且不同进程的用户按这个方式也没办通信吧。可以参考下

**Comment by GongJS** [comment]
> 印象里并不是同用户访问时同进程应答。而且不同进程的用户按这个方式也没办通信吧。可以参考下
> https://github.com/eggjs/egg-socket.io#cluster

已解决，多谢
