### ISSUE TITLE
请问在egg-socketio里实现了acknowledgements了吗，如何调用

### ISSUE THREAD

**Issue by KaneOne** [eggjs/egg#3959]
在原生socket.io里可以在服务器端callback客户的一个方法确认消息执行情况，如下面的代码：

var io = require('socket.io')(80);

io.on('connection', function (socket) {
  socket.on('ferret', function (name, fn) {
    fn('woot');
  });
});

egg-socketio已经封装到ctx.socket里面，请问在egg-socketio里应该调用哪个方法实现这个功能，谢谢。

**Comment by ngot** [comment]
可以参考这个 https://github.com/eggjs/egg-socket.io/blob/master/example/app/io/middleware/auth.js ，在 connection 中间件里面拿到 socket 对象，api 和 原声的 socket.io 没有区别。

**Comment by KaneOne** [comment]
谢谢，可以在egg-socketio的controller里直接拿到这个callback函数进行回调吗，感觉在auth里面再写socket.on破坏了原有的controller结构。

**Comment by KaneOne** [comment]
> 谢谢，可以在egg-socketio的controller里直接拿到这个callback函数进行回调吗，感觉在auth里面再写socket.on破坏了原有的controller结构。

我在controller里直接使用判断ctx最后一位参数是否是函数，来执行回调了，可以达到 相同效果
this.ctx.args[1]('hello');
