### ISSUE TITLE
egg.js 在vscode中调试启动不了

### ISSUE THREAD

**Issue by MrSmallLiu** [eggjs/egg#3960]
egg版本为2.15.1 node版本为8.11.4.开发过程中使用vscode调试，启动过程中会卡住。
vscode配置如下：
![image](https://user-images.githubusercontent.com/26038018/65829817-edfce580-e2db-11e9-9e8f-bda52d623bb9.png)

**Comment by atian25** [comment]
去掉 --inspect-brk 吧，如果你不理解它是什么含义的话

**Comment by MrSmallLiu** [comment]
如果不加该参数可以启动，但是不能调试，断点为灰色
加了该参数是项目没有启动起来，不是每次启动会卡住断点问题。
开发环境为centos7


------------------ 原始邮件 ------------------
发件人: "TZ | 天猪"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午5:11
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "栗子哥哥@"<1016817543@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eggjs/egg] egg.js 在vscode中调试启动不了 (#3960)




去掉 --inspect-brk 吧，如果你不理解它是什么含义的话

**Comment by MrSmallLiu** [comment]
去掉后vscode调试不了。断点为灰色。




------------------ 原始邮件 ------------------
发件人: "TZ | 天猪"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午5:11
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "栗子哥哥@"<1016817543@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eggjs/egg] egg.js 在vscode中调试启动不了 (#3960)




Closed #3960.

**Comment by MrSmallLiu** [comment]
vscode 1.38.1。之前版本是没问题的，升级后发现不行，而且只有该项目时不时的不好使，而不是全部情况不可以


------------------ 原始邮件 ------------------
发件人: "TZ | 天猪"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 下午5:11
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "栗子哥哥@"<1016817543@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eggjs/egg] egg.js 在vscode中调试启动不了 (#3960)




Closed #3960.

**Comment by atian25** [comment]
可以看下 https://github.com/atian25/blog/issues/25 正文的最后一段补充。

或者你可以直接不用这个，把 vscode 的 auto attach 配置打开就好了。
然后直接命令行 egg-bin debug 即可。

**Comment by MrSmallLiu** [comment]
是的，我看到过您的这个介绍，在之前确实是像您补充说的一样，我也知道这个是正常的，现在问题是到我刚刚截图后，程序不在运行，master进程都没有启动。如果仅仅是 auto attach，也确实有调试进程的时候。


------------------ 原始邮件 ------------------
发件人: "TZ | 天猪"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 晚上6:00
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "栗子哥哥@"<1016817543@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eggjs/egg] egg.js 在vscode中调试启动不了 (#3960)




可以看下 atian25/blog#25 正文的最后一段补充。
 
或者你可以直接不用这个，把 vscode 的 auto attach 配置打开就好了。
 然后直接命令行 egg-bin debug 即可。

**Comment by atian25** [comment]
> Egg 的调试，跟 Node 没啥区别，因此一定要了解 Node 的基础调试知识。  
> 其中，--inspect-brk 是指在进程第一行就暂停，等待 attach，因此：
> 1. master 先启动，在第一行会停住，需要你 attach master，才会往下走
> 2. 接着 master 启动 agent，也是在第一行停住，需要 attach agent 才会往下走
> 3. 最后 agent 启动完成后，worker 才开始启动，一样也是在第一行停住，需要 attach agent 才会往下走

从你的截图来看，就是运行到了我说的第二步，但 vscode 这时候没有自动 attach 导致的，估计是某些版本的 `autoAttachChildProcesses: true` 有 BUG。

**Comment by MrSmallLiu** [comment]
目前我觉得启动的时候连master都没有启动，因为没有进master进程让我attach，而且奇怪的是其它项目是好使的，只有该项目之前也是可以的，在我升级完vscode后时而好使时而不好使。而且这个问题不只是我碰见了，我只是今天给您提了一下，之前也看到过好多人遇见过。例如https://blog.csdn.net/weixin_39907636/article/details/90672775。以及我身边朋友也有问过我该问题。


------------------ 原始邮件 ------------------
发件人: "TZ | 天猪"<notifications@github.com>;
发送时间: 2019年9月29日(星期天) 晚上6:12
收件人: "eggjs/egg"<egg@noreply.github.com>;
抄送: "栗子哥哥@"<1016817543@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [eggjs/egg] egg.js 在vscode中调试启动不了 (#3960)



 
Egg 的调试，跟 Node 没啥区别，因此一定要了解 Node 的基础调试知识。
 其中，--inspect-brk 是指在进程第一行就暂停，等待 attach，因此：
  
master 先启动，在第一行会停住，需要你 attach master，才会往下走
 
接着 master 启动 agent，也是在第一行停住，需要 attach agent 才会往下走
 
最后 agent 启动完成后，worker 才开始启动，一样也是在第一行停住，需要 attach agent 才会往下走
   
从你的截图来看，就是运行到了我说的第二步，但 vscode 这时候没有自动 attach 导致的，估计是某些版本的 autoAttachChildProcesses: true 有 BUG。

**Comment by atian25** [comment]
你仔细看你截图里面的日志，master 和 agent 都启动了
