### ISSUE TITLE
centos部署umi项目，路由不带参数是正常的，只要带上参数就会404

### ISSUE THREAD

**Issue by innocces** [eggjs/egg#3965]
## What happens?
http://xx.com/aa
http://xx.com/bb
以上是ok的

http://xx.com/aa?aa=123
这样就会导向404

本地开发是ok的，但是部署到测试环境上就404

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
router.js
```
module.exports = app => {
  const { router, controller } = app;
  
  app.httpclient.on('request', requestInterceptors)

  router.all('/proxy/*', controller.proxy.request)
  router.get('*', controller.home.index);
};
```

## 相关环境信息
- **操作系统**：macos
- **Node 版本**：12.7.0
- **Egg 版本**：2.12.0

**Comment by innocces** [comment]
补充: 服务端渲染的框架用的是egg

**Comment by atian25** [comment]
> 本地开发是ok的，但是部署到测试环境上就404

这种一般要检查下你的服务器环境是不是有 Nginx 之类的作怪

**Comment by popomore** [comment]
请这个单测重现
