### ISSUE TITLE
路由参数的使用

### ISSUE THREAD

**Issue by snailuncle** [eggjs/egg#3966]
路由中捕获了companyName和personName两个参数
怎么直接在controller使用? 比如这样:
  router.get('/company/:companyName/:personName/index', controller[companyName][personName]
不然, 三个公司, 我得写三个路由.

module.exports = app => {
  const { router, controller } = app;
  router.get('/', controller.home.index);
  router.get('/company/:companyName/:personName/index', controller.苹果.乔布斯);
  router.get('/company/:companyName/:personName/index', controller.小米.雷军);
  router.get('/company/:companyName/:personName/index', controller.华为.任正飞);

  router.get('/company/:companyName/:personName/index', controller[companyName][personName]);
};

**Comment by atian25** [comment]
一个 Controller，多个 Service
