### ISSUE TITLE
日志路径问题

### ISSUE THREAD

**Issue by snailuncle** [eggjs/egg#3967]
在手机上运行egg
使用termux报错, 如图:
![QQ图片20191009100639](https://user-images.githubusercontent.com/24560326/66446351-c268c080-ea7c-11e9-98b0-c5b1cbe88c64.jpg)
翻了一遍issue, 有人提过同样的问题, 就是日志文件的权限问题, 
当前解决办法是启动时指定日志路径
"start": "MOCK_HOME_DIR=/storage/emulated/0/Alarms egg-scripts start --daemon",
手机不root的话, 无法创建mkdir '/data/logs', 安卓手机一般也没人root, 容易变砖.

还有就是启动时有检查cpu核数的报错,
安卓平台的cpu核数没有吗?
![QQ图片20191009101430](https://user-images.githubusercontent.com/24560326/66446551-9b5ebe80-ea7d-11e9-8477-1c99c5200c64.jpg)
这里改成数字就能运行了.
![QQ图片20191009101556](https://user-images.githubusercontent.com/24560326/66446595-ce08b700-ea7d-11e9-80af-62b2c9d2d945.jpg)

希望把这两个bug处理了:
1. 日志权限
2. 检查cpu核数

**Comment by atian25** [comment]
手机端跑 egg。。。

你的 Node 运行时是啥？

**Comment by snailuncle** [comment]
termux啊, 有人包装了一下  封装了nodejs  npm 进去  就直接能在termux终端使用了,
github上并没有公开源码, 这是作者  https://github.com/hyb1996

**Comment by hyj1991** [comment]
你在 Android 下执行下 `node -e "console.log(os.cpus().length)"` 看看呢

**Comment by hyj1991** [comment]
第二个问题主要看 Node.js Runtime 本身对 Android 的支持了

**Comment by snailuncle** [comment]
> 你在 Android 下执行下 `node -e "console.log(os.cpus().length)"` 看看呢

![QQ图片20191009102800](https://user-images.githubusercontent.com/24560326/66447037-7ec38600-ea7f-11e9-816c-b89bdb059f2c.jpg)

**Comment by hyj1991** [comment]
那可以给 Node.js 提个 issue 吧，runtime 本身的 api 没有对 Android 做好支持。

**Comment by snailuncle** [comment]
> 那可以给 Node.js 提个 issue 吧，runtime 本身的 api 没有对 Android 做好支持。
好的

**Comment by hyj1991** [comment]
日志的问题 #3912 正在解决，先关闭了

**Comment by atian25** [comment]
日志的 @hyj1991 可以来个 PR 搞搞。

CPU 那个，是你用的 runtime 的 bug，提 issue 给他们吧，临时可以在启动脚本传参来解决， `--workers=2`

**Comment by XeroAlpha** [comment]
已经有人提交过类似的issue了
https://github.com/libuv/libuv/issues/1459
