### ISSUE TITLE
plugin config naming convention

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#397]
Currently, we got more and more plugin to provide difference strategy, such as :

- `egg-passport / egg-watcher / egg-view / egg-model` define the specification, and provide interfaces for sub plugin to implement. 
- sub plugin like `egg-passport-github / egg-passport-weibo / egg-view-nunjucks / egg-watcher-vagrant / ...`  implement the specification and provide specific strategy.

so should we discuss:

- what is the `config` style:  `config.passport.github` or `config.watcherVagrant` ?
- how to hook these sub strategy plugin?
- `eggPlugin.name` style for these sub strategy plugin
- any other rule for them?

@shaoshuai0102 help to correct my proposal.

**Comment by shaoshuai0102** [comment]
Since a plugin is called `egg-passport`, its config should be `config.passport`. Every configuration exposed by this plugin should be in it.

If there's a another plugin, say `egg-passport-github`, config should be named after `config.passportGithub` according to plugin naming convention.

**Comment by popomore** [comment]
+1 for @shaoshuai0102 said.

Just using plugin dependency, sub plugin should depend on plugin which export the method to be called or implemented.

**Comment by atian25** [comment]
@shaoshuai0102 not just about naming:

- config key naming
- plugin naming
- how to hook these sub strategy plugin? such as #398 mention `app.view.register`

**Comment by atian25** [comment]
or hook rule is defined by their proposal just like view specification

**Comment by popomore** [comment]
I think this is no normal rule for all plugin. we can document for these plugin in tutorials.

**Comment by atian25** [comment]
> @fengmk2 :  
>英文不知道怎么说。。。但是从用户体验来说，我都是 passport 的配置，为何还要分开写？而且 egg-passport-github 是强依赖 egg-passport 的，它没法单独使用。config.passport.github 肯定比 config.passportGithub 自然容易理解。还是看 readme 吧，没有完美的规则。这2个插件直接的关系是非常紧密的，应该当作一个整体插件来看待。

这就是我的疑问，这类策略类的二级插件，该不该视为一个整体， egg-watcher-xx 和 egg-view-xx 都是同样的场景，它们的配置 key 命名规则，它们的策略挂载规则，是不是要统一

**Comment by shaoshuai0102** [comment]
- The first approach, `config.watcherXX` over `config.github.xx`, follows the plugin naming conventions.
- The second approach `config.watcher.xx`, brings in another custom naming convention by the `watcher` plugin.

It seems like it's more elegant to avoid more rules.

**Comment by popomore** [comment]
We just recommend, it depends on the author who define the config name and document it.

**Comment by shaoshuai0102** [comment]
Fine. Reopen this when there are new feedbacks from community.
