### ISSUE TITLE
[Feature Request] 全局状态码应该放在哪里？

### ISSUE THREAD

**Issue by wh521518** [eggjs/egg#3975]
## Background
我想问下，如果要定义全局的状态码，类似用枚举来表示业务状态，比如0表示完成，1表示进行中。应该定义在哪里？config中吗？感觉访问起来好长一串？

**Comment by hyj1991** [comment]
放在 config 中可以用解构直接获取到你的状态码配置:  `const { ctx: { app: { config: statusCode } } } = this;`

**Comment by atian25** [comment]
extend your own Controller base class, provide `this.throwXXError()` or `this.XX.cc`(as alias of app.config.xx).

and you could also use `config.customLoader` to autoload custom error code from files.

**Comment by wh521518** [comment]
好的，谢谢！
