### ISSUE TITLE
Cann't get the real client ip?

### ISSUE THREAD

**Issue by dythbj** [eggjs/egg#3976]
## What happens?
egg部署后，由nginx代理，后台获取客户端的IP要么返回空，要么返回127.0.0.1。
IP获取方式：
ip: this.request.get('X-Real-IP') || this.request.get('X-Forwarded-For') || this.request.ip.replace(/::ffff:/, '')

**Comment by hyj1991** [comment]
`X-Forwarded-For` 已经是事实标准了，nginx 设置下 proxy_set_header，默认是不处理的
