### ISSUE TITLE
如何正确修改内置日志格式

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#3979]
> config.logger. formatter

https://eggjs.org/api/Config.html#logger 

```js
	config.logger = {
		formatter(meta) {
			console.log(meta)
			return `[ERROR][${meta.date}]||_msg=[${meta.message}]`;
		},
	};
```

formatter没有生效，请问具体该如何配置？

**Comment by MJingv** [comment]
按照这个格式加入formatter，最后打出来的还是最开始的格式
`2019-10-15 15:02:39,991 ERROR 96127 [-/127.0.0.1/-/1ms GET /log/test] [controller.home] test_log--- 2019-10-15T07:02:39.991Z
`

**Comment by atian25** [comment]
Controller 里面的 this.logger 是 contextLogger，你要配置 contextFormatter

**Comment by MJingv** [comment]
> Controller 里面的 this.logger 是 contextLogger，你要配置 contextFormatter

嗯呢，需要把 contextFormatter 和 formatter都改了，感谢大佬～
