### ISSUE TITLE
ts 下不会自动生成 helper 的 index.d.ts 文件

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#3983]
## What happens?
在文件 `app/extend/helper.ts` 中定义的函数，不会在其他地方通过 `ctx.helper.xxx` 提示。

## Mini Showcase Repository(REQUIRED)
None

## How To Reproduce

**Steps to reproduce the behavior:**
1. 创建 `app/extend/helper.ts` 文件
2. 新建函数
```ts
/**
 * 生成 Pager
 * @param count 总数
 * @param page 当前页数
 * @param limit 每页条数
 */
export const getPager = (count: number, page: number = 1, limit: number = 10) => {
  const max = Math.ceil(count / limit);
  return {
    max,
    min: 1,
    total: count,
    cur: page,
    per: limit,
    next: page + 1 >= max ? max : (page + 1),
    prev: page - 1 <= 1 ? 1 : (page - 1),
  };
};
```

3. 在 controller 中使用该函数，无提醒。
![image](https://user-images.githubusercontent.com/7995232/66932843-cf804380-f06a-11e9-9e45-7d932cfa70a3.png)

**Expected behavior**
1. 在 controller 中使用该函数，出现相对应的提醒（如下图）。
![image](https://user-images.githubusercontent.com/7995232/66932984-fb9bc480-f06a-11e9-9ea8-9a337da50e14.png)

## Context
- **Node Version**: v10.15.3
- **Egg Version**: 2.24.0
- **Plugin Name**: None
- **Plugin Version**: None
- **Platform**: macOS

**Comment by StephenSeraph** [comment]
是不是没有刷新typings？执行一下`npm run tsc`刷新了ts的声明文件之后，在`typings/app/extend/helper.d.ts`就会有相关声明了。另外，每次创建一个新的ts文件，最好都刷新一下

**Comment by atian25** [comment]
`npm run tsc` 是构建 js，执行 egg-ts-helper  的 ets 才是生成声明（dev 的时候会自动生成的）。

**Comment by JZLeung** [comment]
> 是不是没有刷新typings？执行一下`npm run tsc`刷新了ts的声明文件之后，在`typings/app/extend/helper.d.ts`就会有相关声明了。另外，每次创建一个新的ts文件，最好都刷新一下

`npm run tsc` 相当于打包转译吧。。。



> `npm run tsc` 是构建 js，执行 egg-ts-helper 的 ets 才是生成声明（dev 的时候会自动生成的）。

重新 `yarn dev` 还是没有噢。

**Comment by whxaxes** [comment]
extend 里的代码改成

```typescript
export default {
  getPager(count: number, page: number = 1, limit: number = 10) {
    const max = Math.ceil(count / limit);
    return {
      max,
      min: 1,
      total: count,
      cur: page,
      per: limit,
      next: page + 1 >= max ? max : (page + 1),
      prev: page - 1 <= 1 ? 1 : (page - 1),
    };
  },
};
```

**Comment by JZLeung** [comment]
> extend 里的代码改成
> 
> ```ts
> export default {
>   getPager(count: number, page: number = 1, limit: number = 10) {
>     const max = Math.ceil(count / limit);
>     return {
>       max,
>       min: 1,
>       total: count,
>       cur: page,
>       per: limit,
>       next: page + 1 >= max ? max : (page + 1),
>       prev: page - 1 <= 1 ? 1 : (page - 1),
>     };
>   },
> };
> ```

好了，感谢。
