### ISSUE TITLE
docker run fail

### ISSUE THREAD

**Issue by GZWZC** [eggjs/egg#3984]
自己写了个Dockerfile生成了image，启动的是8080端口服务。

docker run -d -p 9999:8080 eggImage:v1.0

进入docker容器，curl localhost:8080/127.0.0.1:8080是可以的
但是在宿主机里访问localhost:9999却访问不了，知道是啥原因吗

**Comment by StephenSeraph** [comment]
把Dockerfile贴出来

**Comment by GZWZC** [comment]
重启docker后可以了
