### ISSUE TITLE
database/config.json配置不生效

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#3986]
1. 在根目录有`.sequelizerc`文件
2. 在`database/config.json`配置了`development`等环境
3. 运行`egg-bin dev` 或者`egg-bin dev NODE_ENV=development`都是报错，并且和我配置的信息不一致，我的用户名都不是root，报错信息是`Access denied for user 'root'@'localhost' (using password: NO)`
4.  在`config/config.default.js`填写相关信息生效OK
```
  config.sequelize = {
    dialect: 'mysql',
    host: '127.0.0.1',
    port: 3306,
    database: 'im-db',
    username: 'test',
    password: 'test',
  };
```
现在问题很明确了，到底怎么做才能使`database/config.json`配置的生效？[eggjs/examples/sequelize](https://github.com/eggjs/examples/tree/master/sequelize)也是一样的问题

**Comment by atian25** [comment]
你在 config 里面自己 require 这个 json 呗

**Comment by hezhongfeng** [comment]
我是可以这么做的，就是感觉文档写的不清不楚的，很混乱，不知道应该怎么做。

**Comment by atian25** [comment]
egg 没有 json 这个配置规范

**Comment by hezhongfeng** [comment]
就是说实际上database/config.json里面的config其实是sequelize自己的规范？
那我直接看看怎么解决吧

**Comment by eviler007** [comment]
我是这样处理的，在config/config.default,js中修改
`
const sequelizeConfig = require('../database/config.json');
exports.sequelize = sequelizeConfig[process.env.NODE_ENV];
`
