### ISSUE TITLE
Cannot read property 'put' of undefined

### ISSUE THREAD

**Issue by DarksKnight** [eggjs/egg#399]
请问，ctx.oss.put调用put方法，提示Cannot read property 'put' of undefined。。是什么原因导致的。。

**Comment by dead-horse** [comment]
你开启 oss 插件了没

**Comment by DarksKnight** [comment]
怎么开启。。。我exports.oss = true 直接报错。。throw new Error(`Can not find plugin ${name} in "${lookupDirs.join(', ')}"`);

**Comment by atian25** [comment]
@DarksKnight 最好能提供一个最小可复现的代码库给我们看看.

egg-init 生成一个 simple 的, 然后配置你的插件, 提交到 github

**Comment by atian25** [comment]
```js
exports.oss = {
  package: 'egg-oss'
}
```

**Comment by DarksKnight** [comment]
@atian25 加了，然而提示了这个
ctx.oss.put is not a function。。。
是什么原因。

**Comment by jtyjty99999** [comment]
@DarksKnight 提交下代码我们可以帮你看下

**Comment by DarksKnight** [comment]
提交好了，地址：
https://github.com/DarksKnight/eggdemo.git
帮忙看看，谢谢了。

**Comment by jtyjty99999** [comment]
你oss都没配啊，oss是要申请 accesskey的

**Comment by DarksKnight** [comment]
好吧。。。我瞅瞅。第一次弄。没弄过这种。
