### ISSUE TITLE
VSCode 无法提示插件中扩展的 ctx 属性（VSCode IntelliSense not recognize extended ctx properties in plugin）

### ISSUE THREAD

**Issue by shizhx** [eggjs/egg#3991]
#3587  What happens?
诉求：
一个 npm package 既是 egg-plugin，又可供 `require` 使用其中的功能。
问题：
1. VSCode 无法提示插件中扩展的 ctx 属性
2. 前述问题通过 `index.d.ts` 解决后又发现 VSCode 无法提示 require 进来的内容

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
随便

## 复现步骤，错误日志以及相关配置
1. 开发插件，扩展 ctx 属性
2. 工程中引入插件并启用
3. npm run dev
4. 查看 VSCode 是否能自动提示 ctx 扩展的属性

结果：不能

## 尝试的解决方案
在插件根目录写一个 index.d.ts 描述扩展的属性

结果：可以提示

## 解决方案的不足
1. `require` 这个插件 VSCode 会使用 index.d.ts，而不是使用 index.js 来提示，而 index.d.ts 是不全的

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
index.d.ts  怎么写的？
