### ISSUE TITLE
egg打印日志错误，实际监听ipv6(::)+ipv4(0.0.0.0)，打印显示127.0.0.1

### ISSUE THREAD

**Issue by fuxingZhang** [eggjs/egg#3993]
## What happens?
- egg 默认监听ipv6(::)+ipv4(0.0.0.0)，打印日志却显示http://127.0.0.1:7001 
- egg 文档描述hostname 为 '0.0.0.0'不安全，实际却监听ipv4(0.0.0.0)和ipv6(::)

## How To Reproduce

1. init egg
``` bash
$ mkdir egg-example && cd egg-example
$ npm init egg --type=simple
$ npm i  
$ npm start 
```

2.  check port listening

* in Linux
```bash
netstat -an | grep 7001
```
print
```bash
tcp6       0      0 :::7001       :::*       LISTEN 
```
* in Windows
```sh
netstat -aon | findstr "7001"
```
print
```bash
  TCP    0.0.0.0:7001           0.0.0.0:0              LISTENING       704
  TCP    [::]:7001              [::]:0                 LISTENING       704
```

## Context
- Node Version: v12.13.1
- Egg Version: 2.15.1
- Platform: CentOS 7.6.1810 64bit 
- Platform: Windows 10.0.18362 64bit

**Comment by fuxingZhang** [comment]
通过指令 
``` bash
$ netstat -an | grep 7001
``` 
上述的1，2的打印信息分别为
1. tcp6       0      0 :::7001                 :::*                    LISTEN  
2. tcp        0      0 127.0.0.1:7001          0.0.0.0:*               LISTEN

**Comment by fuxingZhang** [comment]
感觉问题是这样的：
https://github.com/eggjs/egg-cluster/blob/d6b61027549fd5d63550a924e749830948aa51c7/lib/app_worker.js#L105
egg-cluster lib/ app_worker.js
```  
      const args = [ port ];
      if (listenConfig.hostname) args.push(listenConfig.hostname);
      debug('listen options %s', args);
      server.listen(...args);
```
如果外部没传hostname，server.listen执行的时候是没有传递host参数的  
在nodejs文档内描述如下：
https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_port_host_backlog_callback

If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.

In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).

如果省略host参数，会监听  IPv6 地址 (::），大多数系统还会监听 IPv4 地址 (0.0.0.0)
跟使用 "netstat -an | grep 7001" 获取到的信息一致

**Comment by popomore** [comment]
hostname 可以不填，所以取不到就用默认的了，这里你说的是对的。但操作系统其实都监听了，所以打印哪个都是不对的，这里只是表示已经启动了。

那篇文章是告诉你怎么配置 listen，所以是面向有需求的开发者，一般都不需要配置

**Comment by fuxingZhang** [comment]
> hostname 可以不填，所以取不到就用默认的了，这里你说的是对的。但操作系统其实都监听了，所以打印哪个都是不对的，这里只是表示已经启动了。
> 
> 那篇文章是告诉你怎么配置 listen，所以是面向有需求的开发者，一般都不需要配置

嗯嗯，感觉不太严谨

**Comment by fuxingZhang** [comment]
不是什么大问题，如果没有修改的必要我就把这个issue关掉

**Comment by fuxingZhang** [comment]
> hostname 可以不填，所以取不到就用默认的了，这里你说的是对的。但操作系统其实都监听了，所以打印哪个都是不对的，这里只是表示已经启动了。
> 
> 那篇文章是告诉你怎么配置 listen，所以是面向有需求的开发者，一般都不需要配置



> 感觉问题是这样的：
> egg-cluster lib/ app_worker.js 105至108行
> https://github.com/eggjs/egg-cluster/blob/d6b61027549fd5d63550a924e749830948aa51c7/lib/app_worker.js#L105
> 
> ```js
> const args = [ port ];
> if (listenConfig.hostname) args.push(listenConfig.hostname);
> debug('listen options %s', args);
> server.listen(...args);
> ```
> 
> 如果外部没传hostname，server.listen执行的时候是没有传递host参数的
> 在nodejs文档内描述如下：
> https://nodejs.org/dist/latest-v12.x/docs/api/net.html#net_server_listen_port_host_backlog_callback
> 
> > If host is omitted, the server will accept connections on the unspecified IPv6 address (::) when IPv6 is available, or the unspecified IPv4 address (0.0.0.0) otherwise.
> 
> > In most operating systems, listening to the unspecified IPv6 address (::) may cause the net.Server to also listen on the unspecified IPv4 address (0.0.0.0).
> 
> 如果省略host参数，会监听 IPv6 地址 (::），大多数系统还会监听 IPv4 地址 (0.0.0.0)
> 跟使用 "netstat -an | grep 7001" 获取到的信息一致
> 
> 那么在部署文档内所描述的内容：
> https://eggjs.org/zh-cn/core/deployment.html#%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9
> 
> > 你也可以在 config.{env}.js 中配置指定启动配置。
> 
> ```js
> // config/config.default.js
> exports.cluster = {
>   listen: {
>     port: 7001,
>     hostname: 'x.x.x.x',
>     // path: '/var/run/egg.sock',
>   }
> }
> ```
> 
> 在config/config.default.js如文档所述进行配置与不在config/config.default.js内配置是不等价的
> 
> 1. 不在config/config.default.js配置cluster ：监听的是ipv6端口(::)和ipv4端口(0.0.0.0)
> 2. 在config/config.default.js配置cluster ：监听的是ipv4端口(x.x.x.x)
> 
> 结论：
> 
> 1. BUG： egg打印日志是错误的，实际监听地址是ipv6 (::)+ipv4(0.0.0.0)，但是打印却显示127.0.0.1
> 2. 建议： 在部署文档内以 “//” 注释掉hostname，这样才和不在config/config.default.js配置cluster 表现一致
