### ISSUE TITLE
[Feature Request] egg-security 期望增加命令执行过滤方法

### ISSUE THREAD

**Issue by p0sec** [eggjs/egg#3997]
已有cliFilter过滤所有非`a-zA-Z0-9.-_`之外的字符，但无法完全满足修漏洞需求，修漏洞成本较高。

## escapeShellArg

说明：命令行参数转义。给字符串增加一对单引号并且能引用或者转码任何已经存在的单引号， 这样以确保能够直接将一个字符串传入 shell 函数，并且还是确保安全的。

参考：php中的`escapeshellarg`函数实现：http://php.net/manual/en/function.escapeshellarg.php

Parameters: string — 需要被转义的参数
Returns: 转换之后字符串

demo:

```js
'use strict';

function escapeShellArg(string) {

  const str = '' + string;
  return '\'' + str.replace(/\'/g, '\\\'').replace(/\\/g, '\\\\') + '\''

}
module.exports = escapeShellArg;

```

## escapeShellCmd

说明：命令行转义，从输入的命令行中删除下列字符: ```#&;`|*?~<>^()[]{}$;'", 0x0A 和 0xFF```
参考：php中的`escapeshellcmd`函数实现：https://www.php.net/manual/en/function.escapeshellcmd.php

Parameters: string — 需要被转义的命令
Returns: 转义之后字符串

demo:

```js
'use strict';


const BASIC_ALPHABETS = new Set('#&;`|*?~<>^()[]{}$;\'",\x0A\xFF'.split(''));

function escapeShellCmd(string) {

    const str = '' + string;
    let res = '';
    let ascii;
  
    for (let index = 0; index < str.length; index++) {
      ascii = str[index];
      if (!BASIC_ALPHABETS.has(ascii)) {
        res += ascii;
      }
    }
  
    return res;
}
module.exports = escapeShellCmd;

```

**Comment by atian25** [comment]
> 已有cliFilter 

这个指哪个？

你这个需求是接受开发者传递的 shell 指令然后执行？自己扩展下 helper 就好了吧？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-security/pull/60
