### ISSUE TITLE
文档中应该说明egg默认开了哪些中间件

### ISSUE THREAD

**Issue by Jokcy** [eggjs/egg#3999]
现在需要关闭默认中间件没有文档，根本不知道egg默认开启了哪些中间件以及其作用

**Comment by klren0312** [comment]
https://github.com/eggjs/egg/tree/master/app/middleware
https://eggjs.org/zh-cn/basics/middleware.html#%E6%A1%86%E6%9E%B6%E9%BB%98%E8%AE%A4%E4%B8%AD%E9%97%B4%E4%BB%B6

**Comment by Jokcy** [comment]
@klren0312 这里不全吧，security就没在这里

**Comment by klren0312** [comment]
那是插件带的 https://github.com/eggjs/egg/blob/master/config/plugin.js

**Comment by Jokcy** [comment]
好的

**Comment by atian25** [comment]
可以看下 run/application_meta.json 里面的 config.middleware 和 coreMiddleware

一般不需要关。

**Comment by Jokcy** [comment]
@atian25 就是因为服务特殊所以想要关，很多中间件都用不到。找半天文档里没找到

**Comment by atian25** [comment]
egg-security 的是有单独的开关的，看它的文档。
其他的内置的中间件就那几个。
