### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#40]
刚看了 Singleton 的文档, 有几点疑问, 讨论下:

- 我们之前的实现里面, 有很多用 `Symbol + this[HELPER]` 之类的方式去实现只实例化一次的对象, 这个是不是可以类似提供下简化方法?
- 是否要考虑 loader singleton 的约定?
- Singleton 其实是支持多实例的,那这个命名是不是不太准确?
- 示例里面的 DataService 这个命名感觉有点问题,  会认为是放在 app/service 下, 但这个就是每个请求一个实例了.

**Comment by fengmk2** [comment]
后头 @dead-horse 写好文档即可。
