### ISSUE TITLE
请问权限角色管理还是推荐使用egg-userole吗？

### ISSUE THREAD

**Issue by hezhongfeng** [eggjs/egg#4002]
文档已经没有关于`egg-userole`的介绍了，只有一个关于插件升级的说明。

**Comment by atian25** [comment]
egg-userole 只是一个很简单的 api 约定，看下源码就知道了。

权限角色管理跟具体业务逻辑有关的，你可以在 egg-userole 基础上去定义各个角色，然后使用预订的 API，也可以自行封装下。

**Comment by hezhongfeng** [comment]
好的，我明白了
