### ISSUE TITLE
[Feature Request]想给egg-mysql提交一个PR

### ISSUE THREAD

**Issue by zhennann** [eggjs/egg#4003]
我想给`egg-mysql`提交一个PR，但对实现方案有疑问，想先征求一下大佬的意见

## 背景问题

我在`CabloyJS`中，需要将MySQL的“事物隔离”变量改为`READ COMMITTED`。改变MySQL的变量有两个可选的作用域：`GLOBAL、SESSION`

如果使用`GLOBAL`，只需执行一次，但必须使用系统账号。如果使用`SESSION`，则必须在每次建立数据库连接时，执行修改MySQL变量的SQL语句

## CabloyJS中的做法

`CabloyJS`通过重写模块`ali-rds`的`RDSClient.prototype.getConnection`，实现了在建立数据库连接时，执行自定义的SQL语句

具体源代码，请参见链接：[https://github.com/zhennann/egg-born-backend/blob/e32c7f4faca6c689f17be89c9fb0bde9f25f0767/lib/module/version/database.js](https://github.com/zhennann/egg-born-backend/blob/e32c7f4faca6c689f17be89c9fb0bde9f25f0767/lib/module/version/database.js)

## 目标

我想把CabloyJS中的解决方案，提炼出更通用的形式，并向`egg-mysql`提交PR。但转念一想，这个解决方案是通过重写模块`ali-rds`的方法实现的，而模块`ali-rds`也是阿里的开源项目。因此，如果让`ali-rds`提供类似的机制（在建立数据库连接时可以执行自定义SQL语句），是否会更优雅？

## 可选方案

因此，暂有以下两个思路，请大佬帮忙定夺：
1）不修改`ali-rds`，只在`egg-mysql`中提供`RDSClient.prototype.getConnection`重写功能
2）先由`ali-rds`提供执行自定义SQL语句机制，再在`egg-mysql`中使用此机制

**Comment by hyj1991** [comment]
我建议是给 ali-rds 提供此机制，然后在 egg-mysql 中可配置开启

**Comment by zhennann** [comment]
ok，let me try

**Comment by zhennann** [comment]
给ali-rds提交了pr，至今没有反馈，不知有其他途径否？

**Comment by popomore** [comment]
可以 @fengmk2

**Comment by zhennann** [comment]
thanks

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/pull/104
