### ISSUE TITLE
app.js无效

### ISSUE THREAD

**Issue by dante3406** [eggjs/egg#4004]
## What happens?
使用egg-cluster启动应用，app.js未加载
## 最小可复现仓库
https://github.com/dante3406/testEgg.git

## 复现步骤，错误日志以及相关配置
拉下代码 装依赖 然后EGG_SERVER_ENV=prod npm start

## 相关环境信息
- **操作系统**：centos7
- **Node 版本**：10.15.0
- **Egg 版本**：2.24.0

**Comment by atian25** [comment]
无法复现，你如何观察说它没执行？我这边看到是执行了

daemon 的情况下，你 console log 的日志肯定不会输出到日志啊，你要用 this.app.logger

然后看 `~/logs/` 下的日志。

**Comment by dante3406** [comment]
是我自己的问题 不好意思添麻烦了
