### ISSUE TITLE
在项目中，需要egg服务提供支持长时间保持连接，不想使用socket，是否可以让http请求保持比较长的时间比如（10分钟，20分钟）而且性能也比较好？

### ISSUE THREAD

**Issue by bhb4157** [eggjs/egg#4009]

**Comment by atian25** [comment]
不用 socket 就用传统的 longpull 轮询就好了，没必要保持长连接。

**Comment by bhb4157** [comment]
长轮询我们也考虑过，但第三方调用有点麻烦，太多第三方的话就会增加对接调试成本！

**Comment by atian25** [comment]
HTTP 本身就不应该太长连接的，你真的需要的话，看看 https://github.com/eggjs/egg/blob/master/config/config.default.js#L326 这个配置。

建议还是重新考虑下架构问题。

**Comment by zhaowei-plus** [comment]
大佬，请问下egg是如何实现长轮询，需要怎么配置呢
