### ISSUE TITLE
egg-redis能不能有个例子

### ISSUE THREAD

**Issue by kunzhijia** [eggjs/egg#401]
请问，能不能有个egg-redis的例子

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-redis

**Comment by atian25** [comment]
@jtyjty99999 这个插件的 README 少了 example, 看完都不知道是不是挂在 app.redis

**Comment by jtyjty99999** [comment]
我加一下，可以先看下测试用例   https://github.com/eggjs/egg-redis/tree/master/test/fixtures/apps/redisapp

**Comment by kunzhijia** [comment]
好的，谢谢了！！

**Comment by dead-horse** [comment]
用例有点问题， @jtyjty99999 我在改了

**Comment by dead-horse** [comment]
@kunzhijia 可以去看 egg-redis 的 README 或者测试用例

**Comment by nlove518** [comment]
egg-redis怎么设置过期时间？

**Comment by kunKun-tx** [comment]
@nlove518 
`await redis.set('liveData', JSON.stringify(result), 'EX', 60)`

**Comment by Go-loneliness-of-man** [comment]
有没有支持直接执行 redis 命令的方法，再套一层 api 怪麻烦的 。。。

**Comment by isaacduane** [comment]
This plugin based on ioredis, if you want to know specific usage, you should refer to the document of ioredis.
