### ISSUE TITLE
启动报错 

### ISSUE THREAD

**Issue by nodecaiBird** [eggjs/egg#4010]
verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by nodecaiBird** [comment]
大佬， 看下 ，时而启动成功，时而失败

**Comment by atian25** [comment]
need more information, check common-error.log

**Comment by nodecaiBird** [comment]
那是能提供唯一报错信息了，又启动成功了  我啥事都没做

**Comment by atian25** [comment]
这种信息是没有价值的，要提供错误日志文件或最小可复现仓库。

至于错误日志文件在哪里，可以去看下文档

**Comment by nodecaiBird** [comment]
好的  我先研究下，大佬  ，谢谢
