### ISSUE TITLE
使用sequelize对两张表重复定义多对多，修改中间表数据时使用自带的set方法会重复

### ISSUE THREAD

**Issue by tivonn** [eggjs/egg#4011]
## What happens?
已知有两张表 - task表和user表。task.principals和user建立了多对多的关系，此时会自动给task添加setUsers等方法。如果还需要将task.ccers和user建立多对多的关系，setUsers方法就会重复，应该如何处理，是否应该可以自定义setUsers的方法名。

## 最小可复现仓库

> // task model的关联关系
Task.associate = () => {
 　sequelize.Task.belongsToMany(sequelize.User, {
 　　through: {
 　　　model: sequelize.TaskPrincipal,  // 中间表 task_principal
　 　　unique: false,
　 　},
　 　foreignKey: 'taskId',
　 　constraints: false
　 })
　 sequelize.Task.belongsToMany(sequelize.User, {
　 　through: {
　　 　model: sequelize.TaskCcer,  // 中间表 task_ccer
　　　 unique: false,
　　 },
　　 foreignKey: 'taskId',
　　 constraints: false
　 })
 }

> // user model的关联关系
User.associate = () => {
　sequelize.User.belongsToMany(sequelize.Task, {
　　through: {
　　　model: sequelize.TaskPrincipal,  // 中间表 task_principal
　　　unique: false,
　},
　foreignKey: 'principalId',
　constraints: false
})
　sequelize.User.belongsToMany(sequelize.Task, {
　　through: {
　　　model: sequelize.TaskCcer,  // 中间表 task_ccer
　　　unique: false,
　　},
　　foreignKey: 'ccerId',
　　constraints: false
　　})
}

## 复现步骤，错误日志以及相关配置

> // 只定义task.principal和user的多对多关系时可以正常使用，但是如果还需要给task.ccer和user建立多对多关系，setUsers就会重复。
let newTask = await ctx.app.model.Task.create({ name: 'testTask' }); //返回创建的task对象
let principals = await ctx.app.model.User.findAll({ where: { id: 1 } })//找到对应的user对象
await newTask.setUsers(principals)

## 相关环境信息

- Egg Version: 2.23.0

**Comment by atian25** [comment]
这个应该是 sequelize 相关问题了，egg 只是做了简单的加载器。

可以看看 sequelize 社区那边有没有对应的讨论。
