### ISSUE TITLE
egg-mysql 类型“Application”上不存在属性“mysql"

### ISSUE THREAD

**Issue by liuhuanhui** [eggjs/egg#4016]
typescript:
egg 版本：2.24.0
egg-mysql版本：3.0.0

![image](https://user-images.githubusercontent.com/10370625/67669321-9c17b000-f9ac-11e9-908d-691db1b280b0.png)

**Comment by 544751779** [comment]
跪求 解决这个问题  这个插件最常见了

**Comment by atian25** [comment]
> 跪求 解决这个问题 这个插件最常见了

请仔细看上一条回复

**Comment by liuhuanhui** [comment]
> 跪求 解决这个问题 这个插件最常见了

自己添加index.d.ts

**Comment by atian25** [comment]
可以给 egg-mysql 提下 PR 增加下 d.ts

**Comment by darrenliuwei** [comment]
在 typings 文件夹下的 index.d.ts 文件里加入下图里的代码就可以解决了。

![WeChat Screenshot_20200324102320](https://user-images.githubusercontent.com/10508248/77382794-3e04c280-6dbc-11ea-8415-42833a121054.png)

**Comment by ykmind** [comment]
厉害了

**Comment by cheogo** [comment]
> 在 typings 文件夹下的 index.d.ts 文件里加入下图里的代码就可以解决了。
> 
> ![WeChat Screenshot_20200324102320](https://user-images.githubusercontent.com/10508248/77382794-3e04c280-6dbc-11ea-8415-42833a121054.png)

哈哈哈，虽然知道你是开玩笑的，但是新手可以学一下别人的 d.ts 定义，在上面去补充完善
https://www.typescriptlang.org/dt/search?search=egg-mysql
