### ISSUE TITLE
【egg-graphql】报错 { GraphQLError: Syntax Error: Expected Name, found }

### ISSUE THREAD

**Issue by duenyang** [eggjs/egg#4018]
## 使用egg-graphql插件时报错 GraphQLError: Syntax Error: Expected Name, found
在使用egg-graphql插件时，通过打log发现没有 `app.schema`，
导致执行graphql中间件时报错
![image](https://user-images.githubusercontent.com/17849639/67681978-59b09c00-f9c9-11e9-91d6-ff941a8f849a.png)

当前使用版本egg-graphql版本2.6.0

我该怎么解决这个问题

**Comment by supperchong** [comment]
graphql文件 语法有问题，如果用vscode的话，可以下个插件[GraphQL for VSCode
](https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode#review-details)自动检测语法和格式化，只是这个插件不支持"""注释

**Comment by duenyang** [comment]
好像是我的`GraphQL Schema` 语法有问题,已解决，谢谢
