### ISSUE TITLE
如何扩展ctx.redirect

### ISSUE THREAD

**Issue by xcs-shadow** [eggjs/egg#4020]
如题，我在控制器中使用ctx.redirct跳转时，如果url连接中有中文汉字就会报错，所以我想扩展ctx.redirect，处理一下url参数。各位大神，我应该怎么扩展？

**Comment by atian25** [comment]
url 需要 encode

**Comment by xcs-shadow** [comment]
> url 需要 encode

是的，但是我想扩展ctx.redirect，自动对所有的跳转链接进行url处理

**Comment by atian25** [comment]
你直接扩展一个 ctx.myRedirect 不就行了？

**Comment by xcs-shadow** [comment]
> 你直接扩展一个ctx.myRedirect不就行了？

是的，但是怎么扩展？我在extends/context.js 试了几次都没成功

**Comment by atian25** [comment]
提供最小可复现方式，或者看下文档。

目录是 `app/extend/context.js` 没有 s

**Comment by xcs-shadow** [comment]
> 提供最小可复现方式，或者看下文档。
> 
> 目录是`app/extend/context.js`没有s
去掉s成功了，竟然犯这样低级的错误 😓😓
看来晚上吃饭要多加个鸡腿补补了😂😂

**Comment by xcs-shadow** [comment]
> 提供最小可复现方式，或者看下文档。
> 
> 目录是`app/extend/context.js`没有的

去掉S扩展成功了，但是现在出现了新问题
这是url参数拼接的代码
` var quer = ctx.query;
                let $url = '/u/codeair?';
                for (var i in quer){
                    if(quer[i]){
                        $url += i+'='+quer[i]+'&';
                    }
                }
                if(typeof quer.needinit =="undefined"){
                    $url +='needinit=1&';
                }
                if(typeof quer.common =="undefined"){
                    $url +='common=0&';
                }
                if(typeof quer.board =="undefined"){
                    $url +='board=Arduino&';
                }
                ctx.redirect($url);`
这是我扩展的redirect
`redirect(url){
    if(/[\u3220-\uFA29]/.test(url)){
        this[REDIRECT]=this.redirect(url);
    }
    return this[REDIRECT];
}`
现在是拼接成功，扩展url编码也成功了，但是增加的url参数没有在浏览器地址栏体现出来
输入地址：`http://a.shinelab.cn:8000/u/codeair`，
扩展控制台打印地址：`/u/codeair?needinit=1&common=0&board=Arduino`,
浏览器地址栏显示：
![1572349182(1)](https://user-images.githubusercontent.com/28973432/67764856-c9845c80-fa85-11e9-830d-71d2ab67d6df.png)

**Comment by atian25** [comment]
这是 HTTP 协议了，自己看下 network 排查下自己哪里错了。

话说，`encodeURI(decodeURI(url)` 是什么鬼

**Comment by xcs-shadow** [comment]
> 这是 HTTP 协议了，自己看下 network 排查下自己哪里错了。
> 
> 话说，`encodeURI(decodeURI(url)` 是什么鬼

没找到啊，页面实际上是跳了的，但就是浏览器地址栏没变，这是请求的信息，求大神指点
![QQ截图20191030114328](https://user-images.githubusercontent.com/28973432/67827301-8fa96980-fb0a-11e9-9b1f-375bb09001fb.png)

**Comment by atian25** [comment]
提供最小可复现代码库再讨论。

**Comment by xcs-shadow** [comment]
> 提供最小可复现代码库再讨论。

这是我提取的项目，放在egg框架里就可以了
[https://github.com/xcs-shadow/test.git](url)

**Comment by atian25** [comment]
几个问题：

1. `return ctx.redirect()` 你少了 return。。。
2. 你 context 里面的覆盖 redirect 的方式是错的，不要去覆盖内置的方法。
3. 即使可以覆盖，你覆盖的方式也是错的。。。

**Comment by atian25** [comment]
这才是正确的覆盖方式**（但我非常不建议覆盖内置的方法，这种做法就跟当年 mootools 直接覆盖 Object.toString 等内置原型方法一样，早已经被业界当做不推荐的实践）。**

```js
module.exports ={
   redirect(...args){
      console.log(args);
      return this.response.redirect(...args);
  }
}
```

你之前的方式，最大的错误是，在一个 redirect 的方法里面， 返回的是一个函数体，而不是函数执行的结果。
