### ISSUE TITLE
config中的serverTimeout配置在qps高的时候不生效

### ISSUE THREAD

**Issue by guozefei** [eggjs/egg#4023]
- **Node Version**: 8.11.2
- **Egg Version**: 2.25.0
- **Plugin Name**: 无
- **Plugin Version**: 无
- **Platform**: docker

我在config.default.js中设置 serverTimeout为 10000既10s，在本地调试的时候这个配置是生效的，当请求10s没有响应的时候会502掉
但是部署在测试环境压测的时候发现，压力较小的时候这个配置也是生效的，请求10s没有响应会502，但是当qps高压力大的时候这个配置就失效了，请求可能30s后请求成功，而我期望的结果是10s后就应该响应失败502

**Comment by atian25** [comment]
跟这个配置无关，这就是 Node 的一个内置配置而已。

你那丢失的 20s 应该是 CPU 太高了，导致 node 的代码执行抢占不到时间片。

**Comment by guozefei** [comment]
就是说这个问题和eggjs的框架无关，是nodejs的问题，当cpu高的时候 nodejs 自身的这个 https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_server_settimeout_msecs_callback 配置在其他框架下也会有问题 是这样吗
