### ISSUE TITLE
设置了 cors 后，Access-Control-Allow-Origin 有两个值

### ISSUE THREAD

**Issue by JZLeung** [eggjs/egg#4025]
## What happens?
配置了 cors 和 security.domainWhiteList 后，Access-Control-Allow-Origin 中有两个一样的值

![image](https://user-images.githubusercontent.com/7995232/68073439-33c13800-fdcb-11e9-87eb-54136f049c67.png)

## Mini Showcase Repository(REQUIRED)
None。

Egg.js config 代码
```js
config.security = {
        csrf: false,
        // 加上这句话，则出现两个值。
        // domainWhiteList: [ 'http://xxx.leungjz.top' ],
};

config.cors = {
        credentials: true,
        // 加上这句话，则出现两个值。不加，则报错： 'Access-Control-Allow-Credentials' header in the response is ''
        // origin: ctx => ctx.get('origin'), 
}
```

axios 配置：
```js
const axios = _axios.create({
  withCredentials: true,
});
```

## Context
- **Node Version**: 8.11.1
- **Egg Version**: 2.23.0
- **Plugin Name**: cors
- **Plugin Version**: 2.2.0
- **Platform**: Linux VM-0-8-ubuntu 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cors/blob/30a1b8c8cf58cacd208f86905d334588db523b8e/test/cors.origin-function.test.js#L30

https://github.com/eggjs/egg-cors/blob/30a1b8c8cf58cacd208f86905d334588db523b8e/test/fixtures/apps/cors.origin-function/config/config.default.js#L5

从这个单测来看，你提到的问题，有覆盖到了。请提交下最小可复现方式。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
