### ISSUE TITLE
脚手架初始化时报错

### ISSUE THREAD

**Issue by zhangjunlin6666** [eggjs/egg#4026]
## What happens?
在使用脚手架npm init egg --type=simple初始化或者逐步搭建运行npm i egg --save命令时，报如下错误信息：
notarget No matching version found for pac-proxy-agent@^3.0.1

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：11.4.0
- **Egg 版本**：2.0

**Comment by atian25** [comment]
提供完整的错误信息。

**Comment by hyj1991** [comment]
我试了下 11.4.0 mac 下 `npm init egg --type=simple` 没啥问题，你可以清理下 npm 缓存再试下？`npm cache clean --force`

**Comment by zhangjunlin6666** [comment]
嗯 不好意思哈，我的镜像源不对，如果给你们造成困扰在此表示抱歉！！！
