### ISSUE TITLE
定时任务worker一直被kill掉

### ISSUE THREAD

**Issue by a58571443** [eggjs/egg#4027]
<img width="1440" alt="BA01FFCF-4A65-4CF0-A0DB-6741913EB0EE" src="https://user-images.githubusercontent.com/32952449/68134745-84689a80-ff5d-11e9-939b-222538f6be1c.png">

之前一直好的，突然从某个时间点worker一直会被kill掉，请问这是什么原因导致的呢？

**Comment by atian25** [comment]
检查你的环境，是被外部程序 kill 的。如果是容器里面，检查是不是内存等原因

**Comment by a58571443** [comment]
> 检查你的环境，是被外部程序 kill 的。如果是容器里面，检查是不是内存等原因

![image](https://user-images.githubusercontent.com/32952449/68174668-c4f60180-ffb9-11e9-9e18-7d3a86d703ed.png)

我看worker进程好像在的呀，但是日志里说woker还是被kill掉了。。

![image](https://user-images.githubusercontent.com/32952449/68174704-e1923980-ffb9-11e9-9078-3c47bc0eba21.png)

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/68174758-0b4b6080-ffba-11e9-99d7-757af9a8f3d8.png)

从这个提示来看，是 master 收到了外部发的 kill 指令。

至于你 PS 出来的那些，你可以手动 kill 一次再看看能否复现

**Comment by a58571443** [comment]
手动kill掉以后，服务就停掉了。
日志里面提示定时任务woker被kill掉了，但是ps出来仍旧存在4个worker，而且服务也没停掉，只是定时任务不起作用了😭

**Comment by atian25** [comment]
提供最小可复现方式

**Comment by Sirormy** [comment]
@atian25 
天哥，我这里也遇到一个 worker 中断的问题，具体体现是中途毫无征兆的 word 重启，schedule 重新注册，没有任何的错误日志打印。中间的逻辑比较复杂，会有几十万次的循环 MySQL 事务提交，推测是内存问题，但是从 alinode 的图表也没有看出问题在哪。服务器是 2 核 4 G，只跑定时任务。

<img width="1329" alt="WX20191119-224555@2x" src="https://user-images.githubusercontent.com/6128447/69156580-99792800-0b1e-11ea-8e0c-74254a72e54c.png">

内存的 30% 是 4G 的 30%，还是 node 1G 的 30%？

**Comment by atian25** [comment]
找 Alinode 钉钉群相关同学看看吧。

worker 挂后的日志肯定会有的，看下 egg-scripts 的 master-xx 日志。

**Comment by Sirormy** [comment]
@atian25 劳烦天哥引个路，阿里云上的钉钉群加不进去，多谢。

**Comment by peze** [comment]
> @atian25 劳烦天哥引个路，阿里云上的钉钉群加不进去，多谢。

钉钉群，11794270

**Comment by hyj1991** [comment]
没有后续先关闭了，如果还有疑问可以继续回复此 issue
