### ISSUE TITLE
egg-socket.io controller  无法 console.log 输出内容

### ISSUE THREAD

**Issue by jxZhangLi** [eggjs/egg#4029]
/app/io/controller/notify.js
```
'use strict';

const Controller = require('egg').Controller;

class NotifyController extends Controller {
  async index() {
    const { ctx, app } = this;
    const nsp = app.io.of('/notify');
    const message = ctx.args[0] || {};
    console.log('message: ',  message);
  }
}

module.exports = NotifyController;

```
在控制台中没有输出 log 这条信息，但是页面连接成功了呀

**Comment by jxZhangLi** [comment]
@atian25    大佬有没有回复下的呀

**Comment by thonatos** [comment]
提供一个最小可复现仓库吧

**Comment by jxZhangLi** [comment]
@thonatos  我是直接在你们文档中的 demo 案例中，加上 log 。https://github.com/eggjs-community/demo-egg-socket.io

**Comment by ngot** [comment]
我们无法复现，提供一下具体的步骤。

**Comment by jxZhangLi** [comment]
![image](https://user-images.githubusercontent.com/16809535/68352557-c4887280-0141-11ea-8f56-4836991d6eb0.png)
@ngot  就是下载 https://github.com/eggjs-community/demo-egg-socket.io  这个demo 。run 一下，在 io/controller/nsp.js  下里面 console.log(message); 。在上图所示，访问 http://localhost:7001/  在控制台没有输出内容呀。

**Comment by klren0312** [comment]
> ![image](https://user-images.githubusercontent.com/16809535/68352557-c4887280-0141-11ea-8f56-4836991d6eb0.png)
> @ngot 就是下载 https://github.com/eggjs-community/demo-egg-socket.io 这个demo 。run 一下，在 io/controller/nsp.js 下里面 console.log(message); 。在上图所示，访问 http://localhost:7001/ 在控制台没有输出内容呀。

没看到 console.log啊https://github.com/eggjs-community/demo-egg-socket.io/blob/master/app/io/controller/nsp.js#L12

**Comment by jxZhangLi** [comment]
@thonatos  这个是你们文档中参考链接的 demo，我只是下载下来，在本地加上的 log。

**Comment by keminshu** [comment]
@jxZhangLi 官方文档和 demo 跟 egg 版本不一定协同，遇到此类问题，最好先看下 socket.io 官方文档和 egg-socket.io 源码。

**Comment by ngot** [comment]
我仔细看了即便，没有看出任何问题。这个 Demo https://github.com/eggjs-community/demo-egg-socket.io， 前端只做了连接，和监听服务端时间，其他什么事情也没有。 Controller 是前端发起了事件调用，才会被调用。而这个例子里面，并没有这个代码。

所以，我还是无法理解问题出在哪里。 是理解有问题，还是你本地修改什么代码，我不知道？提供一个你完成的代码，否则我们无法知道问题在哪里。

**Comment by jxZhangLi** [comment]
@ngot  这个demo， 我自己就加了个  console.log，就没了。就不明白为什么没有在控制台输出

**Comment by ngot** [comment]
不输出是对的。要是输出了，才是出了 bug 了。

**Comment by ngot** [comment]
先关了吧，到目前任何有价值的问题提出来。等有具体的问题再重新开。

**Comment by atian25** [comment]
看楼主的意思应该是想在每次用户登入的时候，打印个消息。

**Comment by jxZhangLi** [comment]
@ngot   我的意思是 socket.io controller  写的 console.log 任何内容输出不出来。你们叫我提供步骤，我就用这个 demo 做为案例说明，1、下载到本地运行，2、只加了一行代码 log，没什么输出。
@atian25  是这个意思

**Comment by ngot** [comment]
"1、下载到本地运行，2、只加了一行代码 log，没什么输出" 这个行为，是对的。代码并没有仍和问题。

前端没有调用，服务端怎么可能调用 controller 。

**Comment by jxZhangLi** [comment]
@ngot  大哥，我肯定是访问页面的啊。

**Comment by ngot** [comment]
如果你想看到 controller 被调用，那么，就要修改前端代码，主动调用 `socket.emit('exchange', 'message')` 来给服务端发送请求. 

"访问页面" 不等于发送请求。看起来还是代码没理解。

**Comment by ngot** [comment]
`socket.on('connect' ` 修改成这样，
```js
      socket.on('connect', () => {
        const id = socket.id;

        log('#connect,', id, socket);

        // 监听自身 id 以实现 p2p 通讯
        socket.on(id, msg => {
          log('#receive,', msg);
        });

        socket.emit('exchange', "some message");
      });
```

或者，直接浏览器控制执行：

```js
socket.emit('exchange', "some message")
```

都可以调用 controller

**Comment by jxZhangLi** [comment]
@ngot  好的，谢谢你。我去尝试下。
我开始以为控制器下的方法和路由绑定在一起的。
![image](https://user-images.githubusercontent.com/16809535/68366017-31653200-016d-11ea-96cf-231bdf780aca.png)
