### ISSUE TITLE
[Feature Request] egg-bin test 可以传入配置

### ISSUE THREAD

**Issue by 974806047** [eggjs/egg#4030]
## Background
单元测试里面要使用单独的配置的话都得 
const mm = require('egg-mock');
mm.env('test');
const app = mm.app();
app.ready();
话比较繁琐

## Proposal
可不可以直接在命令行 egg-bin test --env=test ...js
然后测试页面 直接 const { app } = require('egg-mock/bootstrap') ;

**Comment by atian25** [comment]
你自己封装一个 `test/utils.js` 里面加上你那段逻辑，然后测试用例里面 require 一次就行了。
