### ISSUE TITLE
Error: EACCES: permission denied, open '/root/eggma/appveyor.yml'

### ISSUE THREAD

**Issue by snailuncle** [eggjs/egg#4031]
我在win10测试正常 npm run dev  或者  npm start  都正常
我就放到阿里云学生机了  centos7 64
然后npm i 报错, 但是 centos7  npm run dev  或者  npm start  都正常.

![无标题](https://user-images.githubusercontent.com/24560326/68330095-9852fe80-010d-11ea-8507-c55d0f34ed62.png)

**Comment by atian25** [comment]
跟 egg 没啥关系，不要在服务器上 npm i
https://zhuanlan.zhihu.com/p/39209596
临时解决方案，去掉 egg-ci 这个依赖。
