### ISSUE TITLE
eggjs/egg-schedule 定时器配置可以读取config

### ISSUE THREAD

**Issue by xueerfei** [eggjs/egg#4033]
目前schedule 插件的代码 配置定时器如下：

    static get schedule() {
        return {
            interval: '30m',
            type: 'worker',
        };
    }
这个方法无法读取config，有需求在不同环境下配置不同时间，期望可以直接读取config

**Comment by atian25** [comment]
https://github.com/eggjs/egg-schedule#dynamic-schedule
