### ISSUE TITLE
中间件里使用mysql使用不了

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#4035]
中间件:
const user = await this.app.mysql.get({
                    id: decode.id
                });
请问是调用错误吗

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by js1121302139** [comment]
中间件 
![image](https://user-images.githubusercontent.com/24861005/71507426-711fde80-28bf-11ea-8571-8bbacd2f1898.png)

**Comment by js1121302139** [comment]
router 
![image](https://user-images.githubusercontent.com/24861005/71507465-944a8e00-28bf-11ea-8856-54afd398e6c0.png)

**Comment by js1121302139** [comment]
可以将app传入中间件

**Comment by atian25** [comment]
不用传，ctx.app 即可。

hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
