### ISSUE TITLE
egg 怎么通过docker , docker-compose.yml 部署到nginx

### ISSUE THREAD

**Issue by websmallrabbit** [eggjs/egg#4036]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
docker 基础请到相关社区交流

**Comment by weijiatan456** [comment]
大概思路是先起一个node容器，再起一个nginx做域名映射，看docker-compose.yml配置如下：
`version: '3'
services:
    api:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: api-staging
        ports:
            - '7001:7001'
    admin:
        image: nginx:1.10-alpine
        container_name: admin-staging
        volumes:
            - ../nginx/prod.conf:/etc/nginx/nginx.conf
        ports:
            - '80:8001'`
