### ISSUE TITLE
ctx.model.User.findAll()怎么转成数组

### ISSUE THREAD

**Issue by websmallrabbit** [eggjs/egg#4037]
我需要从User表中获取所有数据，然后组成一个对象数组，
const row = await ctx.model.User.findAll() 
取到的是一个数组，但不是标准的数组，
row.map(val => {

})
怎么转成标准的数组呢

**Comment by atian25** [comment]
js 基础请自行解决

**Comment by Jeff-Tian** [comment]
@websmallrabbit 你的意思是得到的数组，里面的元素不是 POJO 吗？这样行不？

假设是 `egg-sequelize + mysql`:
```
const row = await ctx.model.User.findAll()
row.map(val => val.get())
```

通过 `get()` 方法转换一下
