### ISSUE TITLE
logger的debug level，无法开启？

### ISSUE THREAD

**Issue by ruofeng086** [eggjs/egg#4038]
config.local.js
![image](https://user-images.githubusercontent.com/14192308/68538387-4e3c7800-03ae-11ea-9c5a-e528dc24c99f.png)

甚至把config.default.js都改为debug了
![image](https://user-images.githubusercontent.com/14192308/68538393-6f9d6400-03ae-11ea-96ac-7d8891cd72fb.png)

执行 EGG_SERVER_ENV=local npm start 后

![image](https://user-images.githubusercontent.com/14192308/68538402-8d6ac900-03ae-11ea-8fae-e75695af9366.png)

跑起来的，依然是INFO....

港真，这种框架+文档，真不知道该怎么用...

**Comment by atian25** [comment]
![Screenshot_2019-11-10-11-56-54-494_com android chrome](https://user-images.githubusercontent.com/227713/68538544-39151880-03b1-11ea-9973-da5d5c7f17d0.jpg)

冈本，不仔细看文档我们也很无奈

**Comment by hyj1991** [comment]
我试了下配置里这么写就可以开启 debug level：

```
logger: {
  level: 'DEBUG',
  consoleLevel: 'DEBUG',
},
```

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
