### ISSUE TITLE
Testcase 'should load app.js' in 'test/lib/core/loader/load_boot.test.js' fails

### ISSUE THREAD

**Issue by wangxinalex** [eggjs/egg#4040]
## What happens?
Testcase 'should load app.js' in 'test/lib/core/loader/load_boot.test.js' fails. The error message is 'Can't find String:"app is ready" ...'.
       
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

https://github.com/wangxinalex/fix-expect-log-test-error

## How To Reproduce

**Steps to reproduce the behavior:**
1. npm install
2. npm test

**Expected behavior**
1. All testcases pass.
2. Testcase 'should load app.js' in 'test/lib/core/loader/load_boot.test.js' fails with error message 'AssertionError [ERR_ASSERTION]: Can't find String:"app is ready" in ...'

## Context
- **Node Version**: v10.15.3
- **Egg Version**: commit 6c55a436bf2afb7bb99810401a6f92b3a58471ff
- **Plugin Name**: N/A
- **Plugin Version**: N/A
- **Platform**: MacOS 10.15.1

**Comment by atian25** [comment]
your repository confuse me, why do you copy egg source to lib dir ?

**Comment by wangxinalex** [comment]
That repo is nothing but a snapshot of commit 6c55a43
