### ISSUE TITLE
npm run debug异常，无法启动，但是npm run dev又是正常的。

### ISSUE THREAD

**Issue by weijiatan456** [eggjs/egg#4044]
## What happens?
最近npm run debug异常，见下图，但是npm run dev 和 npm run start又是正常的。
![2](https://user-images.githubusercontent.com/12267829/68648396-3d7d3500-055b-11ea-973c-b08274fa9b45.png)

## Mini Showcase Repository(REQUIRED)
> 测试仓库地址我已经提交：https://github.com/weijiatan456/egg-debug

## How To Reproduce

**Steps to reproduce the behavior:**
1.先安装依赖npm i
2.再执行npm run debug即可复现

## Context

- **Node Version**: 8.11.3
- **Egg Version**:2.25.0
- **Platform**:window 7

**Comment by JasinYip** [comment]
看报错信息是没有权限占用 5800 端口，换个端口试试？

**Comment by weijiatan456** [comment]
> 看报错信息是没有权限占用 5800 端口，可以看看是否有别的进程占用 5800 端口

`netstat  -aon  |  findstr  "5800"`
查了下，果然是端口被占用了，是公司的监控程序，我无法删除。
如果想让npm run debug正常使用，怎么改这个5800端口号呢？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L248
