### ISSUE TITLE
怎么在egg-sequelize中将为key的列通过四则运算进行转换，比如created_at,我需要得到的是created_at/1000作为新队列

### ISSUE THREAD

**Issue by oneWalker** [eggjs/egg#4050]
## What happens?
现在我想使用执行一个SQL查询操作，将时间戳时间转换为标准时间进行基础的统计,但是当我使用sequelize.col(‘column’)的时候，column只支持原来存在的列如 created_at. 因为原始数据是存入的毫秒时间，但是函数FROM_UNIXTIME()只支持秒时间,但是sequelize.col()并不支持转换为created_at/1000.

##Attempt REQUIRED)
我尝试了使用两种方法来写如下，但是都没有成功。
```js
let query1=await ctx.model.User.findAll(

{
attributes:[
[fn('FROM_UNIXTIME',col('created_at'/1000,"%y%m%d")),'days'],
[fn('COUNT',col('name')),'counts'],
[fn('COUNT',col('username')),'count1'],
[fn('AVG',col('created_at')),'average'],
],
}
);
```

```js
 let query1=await ctx.model.User.findAll(

{
attributes:[
[fn('FROM_UNIXTIME',col('created_at' mod 1000,"%Y%m%d")),'days'],
[fn('COUNT',col('name')),'counts'],
[fn('COUNT',col('username')),'count1'],
[fn('AVG',col('created_at')),'average'],
],
}
);
```

上面两种写法都显示列表不支持数学运算，但是使用:
```js 
let query1=await ctx.model.User.findAll(

{
attributes:[
[fn('FROM_UNIXTIME','created_at' mod 1000,"%Y%m%d"),'days'],
[fn('COUNT',col('name')),'counts'],
[fn('COUNT',col('username')),'count1'],
[fn('AVG',col('created_at')),'average'],
],
}
);
```

这个语法会自动将created_at转换成字符串的“created_at”。
所以有什么好的解决办法吗？还是说我

## Context
- **Node Version**:v12.13.0
- **Egg Version**:,V2.15.1,
- **Plugin Name**:"egg-sequelize"
- **Plugin Version**:: 5.2.0
- **Platform**:windows 10  x64 professional

**Comment by supperchong** [comment]
可以用literal
```js
[[literal(`created_at/1000`),'newcreated_at'],[literal(`AVG('created_at')`),'average']]
```

**Comment by oneWalker** [comment]
> 可以用literal
> 
> ```js
> [[literal('`created_at`/1000'),'newcreated_at'],[literal('AVG(`created_at`)'),'average']]
> ```

嗯嗯，谢谢 今天在用DISTINCT的时候发现了可以这样用。
可以问一下，但是在使用联表的时候，会自动在distinct之前加一个id这样会导致报错。可以问一下知道怎么解决吗；
比如用这个的时候，ORM生成的SQL会自动在主表DISTINCT前加一个id，这样就报错了：
`attributes:[
            [this.literal(`DISTINCT dict_value`),'visitDetail'],
        ],
include:[
{
    attributes:['id'],
    model:this.app.model.Record
}
]`

**Comment by thonatos** [comment]
setter 不满足需求么？

```js
class Employee extends Model {}
Employee.init({  
  title: {
    type: Sequelize.STRING,
    allowNull: false,
    set(val) {
      this.setDataValue('title', val.toUpperCase());
    }
  }
}, { sequelize, modelName: 'employee' });
```

**Comment by oneWalker** [comment]
> setter 不满足需求么？
> 
> ```js
> class Employee extends Model {}
> Employee.init({  
>   title: {
>     type: Sequelize.STRING,
>     allowNull: false,
>     set(val) {
>       this.setDataValue('title', val.toUpperCase());
>     }
>   }
> }, { sequelize, modelName: 'employee' });
> ```

model里面就写死了，后面逻辑怎么改；最好的还是model用公共的，需要进行修改使用的话通过逻辑代码来实现。
