### ISSUE TITLE
请教：如何获得 response stream？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#4052]
请问一下，在 egg 的 controller 里调用第三方 https 接口拿到了一个图片 buffer，如何将它返回给客户端呢？

尝试把获取到的 buffer 写到了一个 stream 里，但是不知道该如何 pipe 到 ctx.response.stream：

![image](https://user-images.githubusercontent.com/3367820/68987127-aa494580-0861-11ea-8f2b-d763dfefcc9b.png)

试过 bufferStream.pipe(ctx.body)，以及 bufferStream.pipe(ctx.response)，都会出现

```
dest.on is not defined 
```

这样的错误。

多谢指导！

**Comment by atian25** [comment]
https://github.com/eggjs/examples/blob/master/download/app/controller/index.js#L23
