### ISSUE TITLE
CSRF问题：Request Headers里面x-csrf-token = null

### ISSUE THREAD

**Issue by rfw** [eggjs/egg#4053]
## What happens?
 ajax请求api  Request Headers里面x-csrf-token = null , response headers里面x-csrf-token有值，
cookie拿不到

前端：纯静态 html + js   (nginx 反向代理 到 接口)

**Comment by Shen120** [comment]
请问如何解决的

**Comment by atian25** [comment]
Nginx 纯静态 html + js 肯定做不了啊，是跨站点了，而 csrf 防的跨站点攻击
