### ISSUE TITLE
多进程的疑惑，多个 worker 访问到的 app 对象是唯一的么？

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#4054]
1. 我做了一个 service 统计定时任务执行情况，把定时任务执行情况信息放到 app 对象下面，定时任务worker模式的话会随机选择一个worker执行task函数，执行定时函数的时候 通过 函数往app对象下面写信息，我想确定不同worker访问的app 对象 是唯一的么？

2. 我还有一个service 统计api访问信息

我在中间件调用下面这个service
service 返回一个 类，类引用了局部变量 linksCount，links 作为信息存储。
我疑惑的是多进程下面每个worker都会有单独的 linksCount，links 么？
统计信息会发到另外一个服务存储，通过 A: complete里的 if (links.length >= config.sendCount）判断和 B: 定时发送统计信息出发。 我的理解是 A 和 B都是发送的这个对应的worker 的统计信息，也就是每个worker 的统计信息是分离的 不知道对不对？

```

module.exports = app => {
    const config = app.config.xxConfig;

    let linksCount = 0; //
    let links = [];     //

    class apiStatistics extends app.Service {
        constructor(ctx) {
            super(ctx);
        };
        get linksCount() {
            return linksCount;
        }
        start() {
            linksCount++;
        }
        async complete(result) {
            links.push(result);
            linksCount--;
            if (links.length >= config.sendCount) {
                await this.sendStatistics(this.ctx);
            }
        }
        async sendStatistics(ctx) {
            if (links.length == 0 || !config.url) {
                return;
            }
            const data = {
                name: config.name,
                pid: process.pid,
                records: links
            };
            links = [];
            let options = {
                method: 'POST',
                uri: config.url,
                body: data,
                json: true // Automatically stringifies the body to JSON
            };
            let result = await rp(options);
            return result;
        }
    }

    return apiStatistics;
}



```

其实问题还是我对多进程理解不太清晰

**Comment by JasinYip** [comment]
@buzai 

进程是资源分配的最小单位，不同进程间不能共享同一片内存，所以是的，如果你这个类是放在 Worker 进程的话，每个 Worker 进程都会有单独的计数器。

egg 提供了 Agent 进程，可以将你的计数器计到 Agent 进程里，Worker 和 Agent 通过 IPC 通讯。

**Comment by atian25** [comment]
不是唯一，如果需要共享，请用 redis 之类的服务。

**Comment by buzai** [comment]
@jasine @atian25 谢谢，那文档里 

Application 是全局应用对象，在一个应用中，只会实例化一个，它继承自 Koa.Application，在它上面我们可以挂载一些全局的方法和对象。我们可以轻松的在插件或者应用中扩展 Application 对象。

这个是不是说的有些问题
