### ISSUE TITLE
[Feature Request] About unit test and typescript support

### ISSUE THREAD

**Issue by frank-zsy** [eggjs/egg#4055]
## Background
For unit test which uses `agent` and `app` IPC mechanism, there is no document to guide us, but we find a proper way to do this. The solution is like below:

## Proposal
For unit test with IPC support, `npm run test-local` will only launch one process which `app` and `agent` are both in this process, so the IPC will break for test. In our case, we need IPC in core plugin unit tests, so we find a way to init `app` and `agent`, the code is

```javascript
beforeEach(async () => {
  app = mock.app({
    cache: false,
  });
  await app.ready();
  // open the env to make sure 'egg-pids' can be properly processed
  process.env.SENDMESSAGE_ONE_PROCESS = 'true';
  // bind app and agent to each other, add self pid to opids in messenger
  app.messenger.sendTo(process.pid, 'egg-pids', [ process.pid ]);
  agent = app.agent;
});
```

With the code above, we can run unit test with IPC correctly, but with multiple unit tests, we will receive more and more events. With deep look into `messenger`, we discover the underlying IPC mechanism uses [`process.emit` and `process.on`](https://github.com/eggjs/egg/blob/master/lib/core/messenger/ipc.js#L24), which means although every `mock.app` returns a new app, but the process message listener will increase every time.

Fortunately, `messenger` provided [`close` function](https://github.com/eggjs/egg/blob/master/lib/core/messenger/ipc.js#L120) to unregister the listener, so with the code below, the unit test works like a charm:

```javascript
afterEach(() => {
  app.messenger.close();
  agent.messenger.close();
});
```

So here comes the typescript support part, because the type declaration does not contain the `close` function, and even more, the [API doc](https://eggjs.org/api/Messenger.html) does not contain `close` function too, which means we can only know it by reading the source code.

Here is what I propose:
* Add `messenger.close` in API Doc.
* Add `messenger.close` type in typescript type file.
* Add unit test with IPC document for other developers.

## Additional context

**Comment by atian25** [comment]
how about fix egg-mock for:
- process.env.SENDMESSAGE_ONE_PROCESS = 'true';
- add pids

agent && worker run at the same process, but we could inject it, make it  compatibility

**Comment by Frankzhaopku** [comment]
Yes, that could not be better, but this doesn't fix the `messenger.close` issue, we still need to call it manually, right?

**Comment by atian25** [comment]
could try to override it at https://github.com/eggjs/egg-mock/blob/master/lib/app.js#L246

otherwise, raise a PR to https://github.com/eggjs/egg-cluster/blob/master/lib/utils/messenger.js

**Comment by atian25** [comment]
could try to override it at https://github.com/eggjs/egg-mock/blob/master/lib/app.js#L246

otherwise, raise a PR to https://github.com/eggjs/egg-cluster/blob/master/lib/utils/messenger.js

**Comment by Frankzhaopku** [comment]
OK，will do.

**Comment by frank-zsy** [comment]
Solved by https://github.com/eggjs/egg-mock/pull/114
