### ISSUE TITLE
redis配置Sentinel哨兵模式正常启动，但是egg无法连接到redis

### ISSUE THREAD

**Issue by wsdqr001** [eggjs/egg#4056]
我在一台服务器上配置好了redis Sentinel。启动正常，并且能正常连接到redis：
![image](https://user-images.githubusercontent.com/6917707/69354313-dd089900-0cba-11ea-8a61-862a8815490e.png)
此时，启动同一台服务器上的egg服务报错，无法连接到redis：
![image](https://user-images.githubusercontent.com/6917707/69354379-fad5fe00-0cba-11ea-80ae-20adf6f3cfc6.png)
egg-redis配置如下：
![image](https://user-images.githubusercontent.com/6917707/69354413-088b8380-0cbb-11ea-8089-0060fb24ac72.png)
请大佬看下是何原因，谢谢。
@huacnlee @pmq20 @fengmk2

**Comment by scott-leung** [comment]
一般这种问题自己通过工具检查连接 redis 是否有误，排除 redis 服务本身问题后，检查连接的端口，请求的账号和密码就可以解决了。

我看上面的端口好像没对上，你再看看吧。

**Comment by addedjacky** [comment]
同样连不上
