### ISSUE TITLE
eggjs是否无法自定义io的middleware的名称？

### ISSUE THREAD

**Issue by CHANCCCZQ** [eggjs/egg#4057]
## What happens?

![image](https://user-images.githubusercontent.com/22274839/69471995-2dc5e200-0de0-11ea-9377-455f3285ac3b.png)

如图，我自定义了一个business-connection的中间件，然后重启服务后，直接报错

![image](https://user-images.githubusercontent.com/22274839/69472022-6d8cc980-0de0-11ea-9626-1740a60c44b1.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：macOS
- **Node 版本**：12.6.0
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
常见问题，文件名加载后会变为驼峰。可以看下文档
