### ISSUE TITLE
npm init egg --type=xxx 是否可以支持 生成 ts 版的plugin？ 

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4058]
需要写一个egg插件，但是脚手架初始化type只支持一个参数

要不就是生成 npm init egg --type=ts TS的项目模版
要不就是生成 npm init egg --type=plugin 插件模版

有什么方法可以生成 ts版本的插件模版吗？

**Comment by atian25** [comment]
目前官方没提供，既然开发 TS 插件的话，你肯定很熟悉 TS 了，自己加上构建脚本配置即可。
反正最终发布到 npm 的都是编译后的 js

**Comment by ycvcb123** [comment]
@atian25 有demo可以参考吗？

**Comment by Jeff-Tian** [comment]
> @atian25 有demo可以参考吗？

我写过几个，供你参考：

- https://github.com/Jeff-Tian/egg-aliyun-openapi
- https://github.com/Jeff-Tian/egg-error-display
- https://github.com/Jeff-Tian/egg-passport-weapp
