### ISSUE TITLE
service 层如何相互调用呢？嘻嘻，谢谢

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#4059]
service 层如何相互调用呢？嘻嘻，谢谢

**Comment by JasinYip** [comment]
建议仔细阅读 [Service 文档](https://eggjs.org/zh-cn/basics/service.html)

> this.service：应用定义的 Service，通过它我们可以访问到其他业务层，等价于 this.ctx.service 。

**Comment by xinnian1992** [comment]
谢谢
