### ISSUE TITLE
请问如何通过ctx获取当前的模块,控制器，和方法名，谢谢

### ISSUE THREAD

**Issue by xinnian1992** [eggjs/egg#4060]
请问如何通过ctx获取当前的模块,控制器，和方法名，谢谢

**Comment by 467057463** [comment]
同问

**Comment by 467057463** [comment]
请问一下egg，有没有类似ruby on rails的方法获取当前的controller_name、action_name
```pug
body.skin-blue data={page: controller_name + '_' + action_name}
```
这样就可以在view中区分不同的文件

**Comment by unclexiao** [comment]
使用过内置的[egg-logger](https://eggjs.org/zh-cn/core/logger.html)就知道，可以获取完整路径和模块名：`this.fullPath`和`this.pathName`，它们好像绑在了`BaseContextClass`的原型链，理论上来说能在任何模块拿到。

至于**action_name**是对应着某个控制器的函数么？ 早期可以通过[arguments.callee](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Functions/arguments/callee)来动态获取函数名，不过ES5开始就废弃了。现在一般直接是通过[Function.name](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/name)

最后，不清楚你获取这些的意义在哪，能明确一下具体场景么？

**Comment by unclexiao** [comment]
为什么**controller**要和**view**强关联，不应该是对应着**router**吗？
如果不满足于**RESTful API**需要加[模板渲染](https://eggjs.org/zh-cn/core/view.html)，那也应该是对应请求路径而不是模块名不对吗？

**Comment by atian25** [comment]
`router.get('some_path_name', '/xxx', controller.xx)`

`ctx.routerName/ ctx.routerPath`

**Comment by 467057463** [comment]
@unclexiao    首先表示感谢~~~
action_name就你说的控制器函数。
我公司项目用的是ruby on rails，我们一般用controller_name和action_name来标示页面。
例如在layout 的body标签上加：
```html
<body class=`${controller_name}_${action_name}`></body>
```
当访问 `articles/new` 和 `articles/1/edit` 时，动态的生成body的class分别为：
```html
<body class="articles_new"></body>
<body class="articles_edit"></body>
```
通常`articles/new（新建）` 和 `article/edit（编辑）`大部分逻辑是公用的。
这样css、js 就可以通过：
```css
.articles_new, .article_edit{
  // css
}
```
```javascript
App.Page.on('article_new, article_edit', fun(){
 // js
})
```
编写通用的部分代码。

最后，谢谢大佬，刚入egg，还在学习当中，祝egg越来越好

**Comment by unclexiao** [comment]
你举例这部分应该也是某个RoR框架的吧，Egg定位是框架的框架，它只是约定了[目录结构](https://eggjs.org/zh-cn/basics/structure.html)另加一些[内置插件](https://eggjs.org/zh-cn/basics/plugin.html)。

所以暂时没做这么细致的分工，要实现这个特性也是可以的，需要自己封装。

一般来说，`controller`作为业务模块，只处理来自`router`的请求，它和视图（的样式）没有任何关系。

**Comment by zhaoxiaobao** [comment]
@unclexiao   eggjs 有方法能获取所有路由的方法嘛，把route.js所有注册的路由给返回个array出来。

**Comment by atian25** [comment]
你自己封装个方法不就得了

**Comment by guohuihot** [comment]
> 你自己封装个方法不就得了

能提供个思路吗？

**Comment by guohuihot** [comment]
> Function.name

Function.name这个怎么拿？

**Comment by atian25** [comment]
> > 你自己封装个方法不就得了
> 
> 能提供个思路吗？

纯代码层面，你封装一个 app.registerRouter 给开发者用，里面就可以自己记录了。或者 Proxy 下 router 的方法。
