### ISSUE TITLE
插件开发中，需要在插件用引入另一个插件如：egg-mysql，该如何引入？

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4061]
## Proposal
Describe the solution you'd like, better to provide some pseudo code.

**Comment by atian25** [comment]
插件不能包含插件，只能在上层框架来集成。

插件里面只可以声明对某个插件的依赖。

https://eggjs.org/zh-cn/advanced/plugin.html#%E6%8F%92%E4%BB%B6%E7%9A%84%E4%BE%9D%E8%B5%96%E7%AE%A1%E7%90%86

**Comment by ycvcb123** [comment]
@atian25 我没说清楚问题，https://github.com/eggjs/egg/issues/4064 老哥看下这个issues
