### ISSUE TITLE
求助，每次yarn run start或者npm run dev启动项目都会报错,重新安装依赖才能启动

### ISSUE THREAD

**Issue by yangtongsen** [eggjs/egg#4062]
## What happens?
每次yarn run start或者npm run dev启动项目都会报错,重新安装依赖才能启动，而且“感觉是有失效时间的样子”，隔一段时间重启项目的话就会报错

求大佬指点可能出现问题的地方

## Context
报错：
![image](https://user-images.githubusercontent.com/49089290/69611747-70e6b600-1069-11ea-97e3-6744d60f6548.png)

**Comment by atian25** [comment]
你有个文件叫 `clean_tmpdir 3.js` 为啥有个空格

**Comment by yangtongsen** [comment]
> 错误原因不是写的很清楚了，仔细看看英文报错啊。
> 
> 你有个文件叫 `clean_tmpdir 3.js` 为啥有个空格

可是这个文件是node_module自己生成的

**Comment by atian25** [comment]
内置只有 https://github.com/eggjs/egg-multipart/blob/master/app/schedule/clean_tmpdir.js

没有 3 的，检查你的 yarn 是不是有问题，导致安装依赖的时候，生成的文件出问题了。这个跟 egg 关系不大了。

**Comment by yangtongsen** [comment]
> 内置只有 https://github.com/eggjs/egg-multipart/blob/master/app/schedule/clean_tmpdir.js
> 
> 没有 3 的，检查你的 yarn 是不是有问题，导致安装依赖的时候，生成的文件出问题了。这个跟 egg 关系不大了。

好的，谢谢啦
