### ISSUE TITLE
插件开发中,强依赖egg-mysql，配置要放在上层框架处理，但是我所有的model都在我开发的插件里呀！

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4064]
插件中依赖的插件上层框架才能做配置，但是我的model都放在开发的插件里，

上层框架写配置的时候，实体我没法写呀，这怎么办？

![image](https://user-images.githubusercontent.com/15381888/69613314-55c97580-106c-11ea-91bf-a42ef1a8a8c7.png)

**Comment by atian25** [comment]
没看懂，请提供最小可复现代码库

**Comment by atian25** [comment]
？

**Comment by unclexiao** [comment]
你是否是想[开发上层框架](https://eggjs.org/zh-cn/advanced/framework.html)对吧？

自己建立一个[boilerplate](https://github.com/eggjs/egg-boilerplate-framework)，把包依赖写到`package.json`，把插件依赖加到**config/plugin.js**，以后每次创建项目都基于这个脚手架。

新版[npm](https://github.com/npm/npm/releases/tag/v5.2.0)已经内置了[npx](https://www.npmjs.com/package/npx)命令，可以一键[create](https://github.com/eggjs/create-egg)。
