### ISSUE TITLE
`${this.name}.hasMany called with something that's not a subclass of Sequelize.Model`

### ISSUE THREAD

**Issue by BonderTam** [eggjs/egg#4065]
//app/model/contact.js
```
module.exports = (app) => {
  const { BOOLEAN，INTEGER,  STRING  } = app.Sequelize
  const Contact = app.model.define('Contact', {
    isSupplier: BOOLEAN
  }, {})
  Contact.associate = function () {
    app.model.Contact.hasMany(app.model.ContactProduct)
  }
  return Contact
}

//app/model/contactproduct.js
module.exports = (app) => {
  const { DECIMAL  } = app.Sequelize
  const ContactProduct = app.model.define('ContactProduct', {
    tradePrice: DECIMAL
  }, {})
  ContactProduct.associate = function () {
    app.model.ContactProduct.belongsTo(app.model.Product)
    app.model.ContactProduct.belongsTo(app.model.User, {
      as: 'creator'
    })
  }
  return ContactProduct
}

//app.js
app.beforeStart(async () => {
      await app.model.sync({force: true})
    })

//plugin.js
sequelize: {
    enable: true,
    package: 'egg-sequelize'
  },


node version v10.16.3
egg version 2.25
win10

```

> Associate
Define all your associations in Model.associate() and egg-sequelize will execute it after all models loaded. See example below.

**throw new Error(`${this.name}.hasMany called with something that's not a subclass of Sequelize.Model`);

error:Contact.hasMany called with something that's not a subclass of Sequelize.Model**

**Comment by supperchong** [comment]
contactproduct.js文件名改为ContactProduct.js 试试

**Comment by BonderTam** [comment]
没试了，弃用这个插件了

**Comment by BonderTam** [comment]
开发完， 部署时， 问题又出现，，， 绕了一大圈回来， google 出来还是只有这个链接； 这么大一个坑， 看来只有我这个非专职的才踩到。 码点东西， 希望有用。
首先是当时弃用了插件， plugin.js 里没有加上  egg-sequelize.  
继续开发， model 定义也是用的 sequelize.define .   
model 加载是通过  model/index.js  :
const db = require('model')
app.model = db
在npm run dev 的情况下， 一切能跑，   app.model.Contact 等代码也能工作；
==================================================

但是部署的时候， app.model   undefinded，  sequelize undefined  等问题就出来了。
google 一下， 发现很明显是 plugin.js 里没有这玩意， 
再次在 plugin 里架上 egg-sequelize,  model 的代码也改回用  app.model.define
然后就再次出现：
`${this.name}.hasMany called with something that's not a subclass of Sequelize.Model`

觉得没道理啊，  于是 console.log(app.model)  才发现，，，
真是wtf 了
因为我的代码是：
const ContactProduct = app.model.define('ContactProduct'    
app.model 出来的是  Contractproduct: ContactProduct
所以。。。。。
应该是 app.model.Contractproduct 
而不是  app.model.ContractProduct
------------------------------
不是专职的哈， 看了文档也不入心啊。。。。。。
码完， 回头去改 ctx.service 里的代码去了。。。 泪泪

**Comment by JasinYip** [comment]
So it looks not about egg.js but the usage of other module. Closing this issue.
