### ISSUE TITLE
如何在开发插件的时候，拦截curl发出的请求，通过代理转发到本地服务器上

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4066]
### 我在本地起了一个mockserver，然后在开发的插件中写了一个middleware，如下：
![image](https://user-images.githubusercontent.com/15381888/69717923-ffca0000-1147-11ea-8f90-ed094da6e232.png)
#### 然后在app.js中初始化了该中间件，如下：
![image](https://user-images.githubusercontent.com/15381888/69717999-2be58100-1148-11ea-934f-310b8e9e4ca7.png)
###  访问页面可以走到中间件
![image](https://user-images.githubusercontent.com/15381888/69718342-0f961400-1149-11ea-952b-b7dd7c9d0679.png)

### curl发请求就不行

![image](https://user-images.githubusercontent.com/15381888/69718415-4704c080-1149-11ea-9c02-4fbdde123b2a.png)

**Comment by atian25** [comment]
ctx.curl 是服务端去请求第三方服务，middleware 是处理前端的请求，这两者没关系啊。。。

**Comment by ycvcb123** [comment]
### 我在插件的config.default.js 加了上面这一段
![image](https://user-images.githubusercontent.com/15381888/69719670-f2167980-114b-11ea-90fa-48f8bb828ec9.png)

### 然后在启动命令的时候直接这样，把http_proxy换成我本地mockserver的地址不行呀
怎么写代理的匹配规则呢？
![image](https://user-images.githubusercontent.com/15381888/69719726-12decf00-114c-11ea-9db5-f4f4928f7a22.png)

**Comment by atian25** [comment]
文档写的很清楚了，就这样，你可以启动一个 Charles 试试。是可以代理的。
可能是你的 mock server 的问题。

**Comment by ycvcb123** [comment]
### 代理成功了，现在有个新问题，我验证完想把这个代理去了，就在config把配置注释了，而且npm run start 的时候前面也没有加 http_proxy=http://xxx.xxx.xx 这坨东西了，但是启动日志还是可以看到代理到了8081上？这个代理要如何关闭呢？

enableProxy 改成 false重启也不行
```js
exports.httpclient = {
    request: {
        enableProxy: false,
        rejectUnauthorized: false,
        proxy: process.env.http_proxy,
    }
}
```


![image](https://user-images.githubusercontent.com/15381888/69776107-e374a480-11d5-11ea-9c82-8f9023e864ce.png)

**Comment by atian25** [comment]
HPM 这个不是我们搞的，检查下你的代码和插件，看看是哪里引入的。

**Comment by ycvcb123** [comment]
看到了，是另一个代理中间件的问题，多谢解答
