### ISSUE TITLE
如何判断请求是否被客户端关闭？

### ISSUE THREAD

**Issue by yyh1102** [eggjs/egg#4068]
## What happens?

在egg下如何判断一个请求是否已被客户端cancel了？我在service中使用`this.ctx.req.on（’close',callback)`，在跑单测的时候会报`this.ctx.req.on is not a function`

![image](https://user-images.githubusercontent.com/10328169/69793413-53e5ea80-1203-11ea-817e-11b166016053.png)

## 相关环境信息
- **操作系统**： MacOS Mojava
- **Node 版本**：v12.10.0
- **Egg 版本**：v2.6.1

**Comment by atian25** [comment]
egg-mock 里面的 req 是一个 mockContext，没有挂上这些方法。

啥场景下需要判断客户端 cancel ？

**Comment by yyh1102** [comment]
> egg-mock 里面的 req 是一个 mockContext，没有挂上这些方法。
> 
> 啥场景下需要判断客户端 cancel ？

**Comment by atian25** [comment]
用 mm.cluster 的方式测试吧

**Comment by yyh1102** [comment]
> 用 mm.cluster 的方式测试吧

emm，具体应该如何操作？

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mock#mmclusteroptions

**Comment by yyh1102** [comment]
@atian25 需要在生产环境中 而非 测试环境中检测。

**Comment by atian25** [comment]
你不是写单测么？

**Comment by yyh1102** [comment]
@atian25  实际跑时也需要通过后端service来检测并执行相应代码逻辑呀。

**Comment by atian25** [comment]
this.ctx.req 是 Node 自带的 req 实例， egg 没做什么修改。

**Comment by yyh1102** [comment]
@atian25 嗷，所以只是 在单元测试时的ctx是mock的，线上环境还是Node自带的req实例是么

**Comment by atian25** [comment]
https://github.com/eggjs/egg-mock/blob/master/app/extend/application.js#L50

**Comment by yyh1102** [comment]
好的，谢谢
