### ISSUE TITLE
使用 curl localhost:7001/news -A "Baiduspider" 没有效果

### ISSUE THREAD

**Issue by next2014** [eggjs/egg#407]
![jietu20170218-021653](https://cloud.githubusercontent.com/assets/7641722/23077655/79313774-f580-11e6-84de-d98c2224821f.jpg)

**Comment by atian25** [comment]
启动了么？ `npm run dev`

**Comment by ngot** [comment]
服务没启动了吧

**Comment by popomore** [comment]
@next2014 如果你还有其他问题可以再开启。

**Comment by next2014** [comment]
![jietu20170218-230817](https://cloud.githubusercontent.com/assets/7641722/23095214/1c45fa24-f641-11e6-9ed0-e197e764ba69.jpg)
是这样的效果吗？

**Comment by popomore** [comment]
看起来对的
