### ISSUE TITLE
官方有没有对egg curl请求的二次封装？找到了一些感觉都不太好

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4070]

**Comment by atian25** [comment]
为啥要二次封装，不同场景不同需求。
官方没有需要维护的二次封装需求。

**Comment by JasinYip** [comment]
用不习惯可以考虑用 [axios](https://www.npmjs.com/package/axios)

**Comment by atian25** [comment]
> axios

urllib 可是承受住了超大规模的请求考验的，里面的很多 socket 超时时间等的配置都是最佳实践。

服务端侧还是要慎重选型。
