### ISSUE TITLE
[Feature Request] egg-mysql select查询不够灵活，可不以定制升级下

### ISSUE THREAD

**Issue by ifuner** [eggjs/egg#4072]
模糊查询，多字段查询，columns列的格式转换，目前除了自定义query能实现，select也只能完成简单的定制。可以增强下select方法的功能吗？

比如以下columns where 可以增加类似这种功能吗

 const microSql = this.ctx.app.mysql.get(MICRO);
      const result = await microSql.select(TB_USER_LIST, {
        //字符自定义查询 where: `phone=${account}`, 
        //OR查询 where: {`phone||user_name||email`:account}, 
       //字符包含 where: {`phone`: {include:"186"}}, 
      //最大最小区间查询 where: {`age`: {max:"100",min:10}}, 
        columns: ["id",  "user_name", date_format(create_time,'%Y-%m-%d %H:%i:%s') as create_time],
        orders: [['id', 'desc']], // 排序方式
        limit: 10, // 返回数据量
        offset: 0, // 数据偏移量
      });

**Comment by js1121302139** [comment]
app/extend/application.ts
```
export interface QueryData {
    where?: {
        [type: string]: any;
    };
    columns?: Array<string>;
    limit?: number;
    offset?: number;
}

module.exports = {
    mysqlGet(tabName: string, queryData: QueryData) {
        const { offset, limit } = queryData;
        let whereArr: Array<string> = [];
        const where = queryData.where
            ? `where ${Object.keys(queryData.where).map(item => {
                  if (queryData.where) {
                      whereArr.push(queryData.where[item]);
                      return `${item}=?`;
                  }
              })}`
            : '';
        const columns = queryData.columns ? queryData.columns.join(',') : '*';
        return this.mysql.query(
            `select ${columns} from ${tabName} ${where} LIMIT ?, ?`,
            [...whereArr, offset || 0, limit || 1]
        );
    }
};
```


使用 
```
 await this.app.mysqlGet(TABNAME, {
                columns: ['idxxx as IDxxx']
            }),
```

**Comment by atian25** [comment]
自己扩展即可。

**Comment by fuxingZhang** [comment]
可以使用star最多的https://github.com/mysqljs/mysql，功能是最强大和完善的，没有使用egg之前一直用这个库，现在还是用这个。
然后自己分装成egg插件就行。
这个还是callback的形式，不是promise化的。

## 你可以参考我封装的写一个。
1. 第一步：promise化，包名”@node-mysql/mysql “，源码地址：https://github.com/fuxingZhang/mysql-promise
2. 第二部：封装成egg插件，参考包名”@eggplugin/mysql”，源码地址 ：https://github.com/fuxingZhang/egg-mysql

## 当然你也可以直接使用我的
我没有引入任何额外的依赖，进行了promise化和简化事务的使用，流式API没必要promise化，提供了可以拿到原始connect的方法，支持mysqljs/mysql的所有API

**Comment by fuxingZhang** [comment]
你这个需求跟sequelize很像，你可以直接使用sequelize，没必要再单独封装

**Comment by popomore** [comment]
可以直接用 query
