### ISSUE TITLE
单元测试中如何测试 expect(someFunc).toBeCalled() 的功能？

### ISSUE THREAD

**Issue by JohnSmith0602** [eggjs/egg#4075]
egg.js 文档中推荐的测试工具组合是 mocha + power-assert + node-modules/mm，我看了各个工具的文档和示例后，没能找到类似 expect(someFunc).toBeCalled() 的功能，请问是否支持呢？

谢谢。

**Comment by atian25** [comment]
再看下单测文档。
如果你还有需要自行引入 chai 之类的库

**Comment by paradite** [comment]
我之前也被这个问题困扰过，后来用一个比较简单的方法实现了：

```js
let triggered;

beforeEach(async () => {
  triggered = false;
  app.mockService('abc', 'get', async () => {
    triggered = true;
  });
});

it('xxx', async () => {
  // ...
  assert(triggered === true);
});
```

**Comment by JohnSmith0602** [comment]
@paradite 谢谢分享，我也是因为正好要判断 service 是否被调用，所以还不好用其它的库来 mock。
我目前实践中是假设调用 service 应该有副作用发生，所以直接去 assert 副作用。不过你这个建议也很好，谢谢～
