### ISSUE TITLE
使用egg-sequelize的问题，sql语句中的问号

### ISSUE THREAD

**Issue by YNestA** [eggjs/egg#4079]
[egg-sequelize](13ms) Executed (default): INSERT INTO `t_opt_record` (`fid`,`fproject`,`frtx`,`fpage_id`,`fsql`,`fopt`,`fcreate_time`) VALUES (DEFAULT,?,?,?,?,?,?);

想把关键操作的sql语句保存记录下来，log回调参数的sql语句中具体的值都变成了问号，有办法得到具体的值吗？

**Comment by supperchong** [comment]
sequelize配置里添加
```js
logQueryParameters:true
```
