### ISSUE TITLE
[Feature Request] 请问为什么不考虑写一个 egg-sequelize-auto 的功能？

### ISSUE THREAD

**Issue by skyweaver213** [eggjs/egg#4082]
## Background
如果是一个现存的项目，想用egg写对应的子项目或者重构，那么数据库是用以前的，请问这时候如何生成model? 我搜了一下发现 egg-sequelize-auto 这个模块没有官方的，建议官方加上这个模块。不可能使用egg的同学都是没有依赖已有的数据库吧？
By the way, example写得太简单了 & sequelize-auto已经定义了一种model格式，设计的时候出于何考虑要创造一种新的egg 独有的model格式？

**Comment by atian25** [comment]
不一定要依赖官方的，就像 Koa 和 Express 的中间件生态也不都是官方的。

我们日常工作中很少用到 sequelize，没信心能维护好。

欢迎自己写一个然后贡献出来。

**Comment by darrenliuwei** [comment]
> 不一定要依赖官方的，就像 Koa 和 Express 的中间件生态也不都是官方的。
> 
> 我们日常工作中很少用到 sequelize，没信心能维护好。
> 
> 欢迎自己写一个然后贡献出来。

那是用`egg-mysql`直接操作数据库吗？
