### ISSUE TITLE
egg-multipart的file模式下设置不删除缓存

### ISSUE THREAD

**Issue by Dobility** [eggjs/egg#4083]
## Background
egg-multipart设置mode='file'后，其实已经拿到并写入文件了，花了一次 IO，实际上已经完成了最初的目的，可以提前结束了。但由于这些文件会被清理，所以还要开发者再自己保存，则需要读取和写入，再花两次 IO，造成非常可观的时间空间浪费。
在 [index.d.ts](https://github.com/eggjs/egg-multipart/blob/master/index.d.ts) 中发现 cleanSchedule 有个 disable 的字段，但是在实现代码中并没有使用到。感觉是有打算增加不清理缓存的功能？

## Proposal
希望能够激活 egg-multipart 的 config 中 cleanSchedule 的 disable 设置，实现不清理已经辛苦读取写入的缓存但可用的文件。

## Additional context
另外，还希望能提供自定义存缓存文件的路径，而不是只能按日期～

**Comment by atian25** [comment]
单机放文件没意义，如果集群情况或磁盘损耗就没了，文件建议存到 [OSS](https://cn.aliyun.com/product/oss)

> 但由于这些文件会被清理，所以还要开发者再自己保存，则需要读取和写入，再花两次 IO，造成非常可观的时间空间浪费。

一个 mv 操作而已，没有什么时间空间的浪费。

**Comment by JasinYip** [comment]
如果确实有这样的需求，可以在调用 `ctx.cleanupRequestFiles()` 前，先 copy 或 move 文件，路径在 `ctx.files[i].filepath`
