### ISSUE TITLE
有没有考虑 typescript 呢

### ISSUE THREAD

**Issue by kunl** [eggjs/egg#409]
官方会考虑推出 type.d.ts 吗？
ts 用来写后台应用很方便。

**Comment by popomore** [comment]
暂时不会维护 .d.ts，这个优先级不会很高，尤其 egg 这种插件体系是很难去定义的。

但是我们完全支持使用 ts，希望社区热爱 ts 的同学一起来共建
忆年 <notifications@github.com>于2017年2月18日 周六21:35写道：

**Comment by xcwen** [comment]
怎么集成  typescript ?! 有文档吗?!^)^

**Comment by atian25** [comment]
已经有 d.ts 了，https://github.com/eggjs/egg/blob/master/index.d.ts

只能部分支持。

**Comment by atian25** [comment]
当 Egg 遇到 TypeScript，收获茶叶蛋一枚

https://zhuanlan.zhihu.com/p/35334932
