### ISSUE TITLE
curl 如何设置 headers ？

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4091]
如下图，headers 为 ，这个值已经从ctx.csrf中取到了
```js
{'x-csrf-token': 'xxxxx'}
```
![image](https://user-images.githubusercontent.com/15381888/70428030-c59a2000-1ab0-11ea-81b5-212eb21ea1f4.png)

结果跑起来还是

![image](https://user-images.githubusercontent.com/15381888/70428250-2b86a780-1ab1-11ea-996b-10e5b993821f.png)

请求头里也没有，求解

**Comment by ycvcb123** [comment]
我在options中已经把x-csrf-token 带过来了

![image](https://user-images.githubusercontent.com/15381888/70434500-54159e00-1abf-11ea-9396-f54568e01a96.png)

但还是跟我说 missing csrf token

![image](https://user-images.githubusercontent.com/15381888/70434530-6abbf500-1abf-11ea-84b8-3270dedfd510.png)

**Comment by ycvcb123** [comment]
@atian25 大神帮忙看下？

**Comment by atian25** [comment]
没看懂你想干嘛。 curl 是服务器的 http 不是前端的

**Comment by ycvcb123** [comment]
我晕了，我在前端这样配置已经可以了，还老想着往curl里封装，这里已经到过服务端了，哎。

![image](https://user-images.githubusercontent.com/15381888/70435270-61338c80-1ac1-11ea-98ad-7c2bbcc31755.png)
