### ISSUE TITLE
webstorm中debug无效

### ISSUE THREAD

**Issue by MJingv** [eggjs/egg#4095]
## What happens?
webstorm中debug无效

## Mini Showcase Repository(REQUIRED)
   "debug": "egg-bin debug ",

## 配置文件如下
![Image of Yaktocat](https://pt-starimg.didistatic.com/static/starimg/img/bRid2TdL8U1576031873496.png)

![Image of Yaktocat](https://pt-starimg.didistatic.com/static/starimg/img/pGw9vTEixw1576031872533.png)
## Context
- **Node Version**:v10.12.0
- **Egg Version**:"^2.2.1"
- **Webstorm Version**:2019.3
- **Platform**:macOS Mojava 10.14.6

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/70587438-dbb8f500-1c04-11ea-9357-389b99d4bf83.png)

我试了是没问题的。

**Comment by MJingv** [comment]
> ![image](https://user-images.githubusercontent.com/227713/70587438-dbb8f500-1c04-11ea-9357-389b99d4bf83.png)
> 
> 我试了是没问题的。

Debugger attached.

但是不停

**Comment by atian25** [comment]
啥叫不停，启动期的代码，你没有 inspect-brk 肯定停不了，因为一直执行完了。
如果是 Controller 里面的代码，是可以停的。

已经 attach 上了，就属于 WebStorm 调试 Node.js 的问题了，跟 egg 关系不大了，egg 就是一个标准的 Node 应用。

**Comment by MJingv** [comment]
打开 DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__ 
可以debug，webstorm不行，是什么问题呢？

**Comment by atian25** [comment]
不确定，我本地是可以的，可能是你的 WebStorm 问题。

可以去看看 WebStorm 调试 Node 的相关文档学习下。

![xx](https://user-images.githubusercontent.com/227713/70590601-330f9300-1c0e-11ea-9e41-f7d5f61b912d.gif)

**Comment by MJingv** [comment]
装回2018版本就可以了
不要升级啊😭

**Comment by atian25** [comment]
我是 WebStorm 2019.1.4 的没问题

**Comment by PrideChung** [comment]
升到 WebStorm 2019.3 之后发现Debugger的确不能用了。的时候用env命令打印了一下 WebStorm 附带的环境变量（` "debug": "env && egg-bin debug",`），发现环境变量里面没有`NODE_DEBUG_OPTION`，只有`NODE_OPTIONS=--require /private/var/folders/m9/n7j95kxd3r58t003jn4nkw100000gn/T/debugConnector.193.5233.80.js`。是因为环境变量改名了么？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/70694034-ab9f4e00-1cf9-11ea-9eb7-0039a31db75a.png)

试了下，确实 WebStorm 2019.3  不行。

从截图来看，WebStorm 只 attach 了 master 和 egg-ts-helper，后面的 agent 和 worker 都没 attach，感觉是 WebStorm 的 Bug，可以给 WebStorm 提下 Issue。

**Comment by MJingv** [comment]
> ![image](https://user-images.githubusercontent.com/227713/70694034-ab9f4e00-1cf9-11ea-9eb7-0039a31db75a.png)
> 
> 试了下，确实 WebStorm 2019.3 不行。
> 
> 从截图来看，WebStorm 只 attach 了 master 和 egg-ts-helper，后面的 agent 和 worker 都没 attach，感觉是 WebStorm 的 Bug，可以给 WebStorm 提下 Issue。

🤧

**Comment by atian25** [comment]
VSCode 它不香么

**Comment by PrideChung** [comment]
> VSCode 它不香么

我就是馋WebStorm的重构功能啊。

确认是WebStorm 2019.3 的问题，已经有人报Bug了，等JB去fix吧。暂时回退到 WebStorm 2019.2.4 版。

**Comment by kookob** [comment]
升到 WebStorm 2019.3 之后Debugger确实不能用了！
折腾了各种方式，配置都不行，无奈只能回到 2019.2
今天刚升级的2019.3.1还是没有修复，继续等修复版本。

**Comment by atian25** [comment]
习惯就好，WebStorm 的升级经常会破坏 Node 的多进程调试，已经无数次了

**Comment by PrideChung** [comment]
@kookob 我在YouTrack上看到这个Bug已经在2019.3.2版修复了，再等等吧。

**Comment by PrideChung** [comment]
WebStorm 2019.3.2 Preview 已经修复了这个bug， @atian25 可以close了吧？

**Comment by kookob** [comment]
@PrideChung @atian25 
刚满怀期待的更新了2019.3.2的版本，更新后，发现debug还是时不时不生效。
有点失望，又得换回旧版本。

**Comment by atian25** [comment]
这我们也没办法，WebStorm 的 bug。
VSCode 它不香么？

3.0 切单进程后应该能规避下

**Comment by kookob** [comment]
@atian25 嗯，我知道是WebStorm的bug，只是分享一下3.2的情况，依然是没解决。

**Comment by pxim** [comment]
WebStorm 2020.3 还是不能直接在编辑器里debug，只能chrome 里debug
