### ISSUE TITLE
cluster配置监听端口不生效

### ISSUE THREAD

**Issue by letheliu** [eggjs/egg#4096]
## What happens?
我检查了最终配置application_config.json和agent_config.json两个文件，cluster配置都成功了，但应用启动时仍然使用7001端口

## 相关环境信息
- **操作系统**：centos 7.0
- **Node 版本**：11.13.0
- **Egg 版本**：2.0.0

**Comment by scott-leung** [comment]
本地开发：
```json
{
  "scripts": {
    "dev": "egg-bin dev --port 7001"
  }
}
```

应用部署时：
```shell
$ egg-scripts start --port=7001 --daemon --title=egg-server-showcase
```

**Comment by niuernihao** [comment]
我也这里也是,config.cluster里配置了的端口7005,有时候无效 有时候有效,启动有时候仍然使用的默认7001,
config.cluster = {
    listen: {
      path: '',
      port: 7005,

    }

**Comment by scott-leung** [comment]
> 我也这里也是,config.cluster里配置了的端口7005,有时候无效 有时候有效,启动有时候仍然使用的默认7001,
> config.cluster = {
> listen: {
> path: '',
> port: 7005,
> 
> ```
> }
> ```

那就要检查你启动时应用的是哪个配置表文件，主要检查启动时环境参数。
