### ISSUE TITLE
跟着官方Demo运行总是提示我要用密钥加密Cookie,页面500错误（入门阶段）

### ISSUE THREAD

**Issue by XdyGoGo** [eggjs/egg#4100]
## What happens?
跟着官方Demo运行总是提示我要用密钥加密Cookie,页面500错误（入门阶段）

## Mini Showcase Repository(REQUIRED)
无

## How To Reproduce

**Steps to reproduce the behavior:**
1. mkdir egg-test && cd egg-test
2.npm init --yes

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by scott-leung** [comment]
请注意运行命令，开发应使用 `npm run dev` ，如果是使用 `egg-scripts start` 运行时，注意环境变量是否正确，还有注意有没有 `npm run tsc` （大概率是没有运行这个），导致的。
