### ISSUE TITLE
如何实现原样转发

### ISSUE THREAD

**Issue by liuwensa** [eggjs/egg#4103]
服务实现请求的原样转发功能，该如何实现？
前端请求project.xxx.com/api/datas，后端直接转发到api.xxx.com下，参数不做处理或者只加上签名

**Comment by mmdapl** [comment]
http-proxy了解一下

**Comment by Jeff-Tian** [comment]
前端如果用 webpack，可以配置 devServer.proxy。

如果是问 egg 如何转发请求，可以用 `ctx.curl`：
示例：https://uniheart.pa-ca.me/proxy/?url=https://www.google.com

代码：https://github.com/Jeff-Tian/alpha/blob/ade7735723ff2bca7e3e5ba400e58cc53c11e84d/app/controller/proxy/proxy.ts#L7

**Comment by atian25** [comment]
curl 有一个需要注意的地方，就是 post 情况下，前面有 bodyparser 和 multipart，所以在不同的请求下，要透传过去的地方处理有点不一样。

**Comment by dark-tone** [comment]
如果前面有一层nginx的话，用nginx也能实现转发功能。

**Comment by fengcaian** [comment]
用ng代理，我现在项目就是这样的，用egg转发请求到真的后端
