### ISSUE TITLE
egg-mysql表达式between and问题

### ISSUE THREAD

**Issue by WongYuYe** [eggjs/egg#4104]
## 相关环境信息
- **操作系统**：win10
- **Node 版本**：12.13
- **Egg 版本**：2.6.1
- **Egg-mysql版本**：3.0.0

这是官网MySQL 内置函数使用教程
https://eggjs.org/zh-cn/tutorials/mysql.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E8%BE%BE%E5%BC%8F

以下是使用between and的情况，代码如下
```
await this.app.mysql.select('code', {
    where: {
      phone: phone,
      create_time: new Literal(`between ${beforeTime} and ${now}`)
   }
});
```
控制台打印出的sql为
```
SELECT * FROM `code` WHERE `phone` = '15990125345' AND `create_time` = between 2019-12-16T22:49:23+08:00 and 2019-12-16T22:54:23+08:00
```
### 可以看到create_time后多了个“=“导致sql报错，是egg-mysql还不支持between and这个内置函数吗？或是其他写法？

**Comment by dark-tone** [comment]
看了一下转换规则，对于where条件，ali-rds的转换规则是这样的（https://github.com/ali-sdk/ali-rds/blob/9db39e6aa4e49fc9708a8f3b3aa666e56e635589/lib/operator.js#L308）
`proto._where = function(where) {
  if (!where) {
    return '';
  }
  const wheres = [];
  const values = [];
  for (const key in where) {
    const value = where[key];
    if (Array.isArray(value)) {
      wheres.push('?? IN (?)');
    } else {
      if (value === null || value === undefined) {
        wheres.push('?? IS ?');
      } else {
        wheres.push('?? = ?');
      }
    }
    values.push(key);
    values.push(value);
  }
  if (wheres.length > 0) {
    return this.format(' WHERE ' + wheres.join(' AND '), values);
  }
  return '';
};`
可以看到，转换的符号只会转成“IN”或“IS”或“=”，bewteen个人感觉是不支持的，然后另外的实现方法暂时没研究过，平时我用的都是sequelize，有空的话再看看

**Comment by WongYuYe** [comment]
好的多谢
