### ISSUE TITLE
单点退出如果通过可获取其他用户的session然后清除

### ISSUE THREAD

**Issue by sweetehs** [eggjs/egg#4107]
单点退出如果通过可获取其他用户的session然后清除

**Comment by atian25** [comment]
这是业务自己的实现。如果是 cookie session，显然不可能

**Comment by sweetehs** [comment]
我的意思是 通过方法获取所有session信息，然后根据ID删除 session信息中的某一个用户信息

**Comment by atian25** [comment]
如果你 session 是存在每个电脑上的，显然没办法。你这种可以考虑 jwt 的失效机制，或者 redis session
