### ISSUE TITLE
egg egg-bin prod or egg-bin dev

### ISSUE THREAD

**Issue by wuchuguang** [eggjs/egg#4110]
egg的配置和启动方式，有点乱。
 egg-scripts
 egg-bin
有什么区别？

config/config.prod.js
config/config.dev.js
有什么区别？

正常设计的角度是：

egg-bin是执行器，
egg-script是绑手架

egg-bin prod就加载所有   config/config.default.js  | config.prod.js
egg-bin dev就加载所有   config/config.default.js  | config.dev.js
egg-bin test 就加载所有  config/config.default.js | config.test.js

一些的启动项，都配在：package.json script上。就很自然了。

而egg-script可以生成一些相关js基础文件，
如：egg-script controller new xxxx.js
会在app/controller/xxx.js生成这个文件。

egg-script router add post=/post/test  controller=xxxx  action=test
会在app/router.js添加一行
router.post('/post/test, controller.xxxx.test)

**Comment by atian25** [comment]
文档写的很清楚吧：
- egg-bin 是开发期辅助工具
- egg-scripts 是服务器环境启动脚本
- 你说的脚手架是 egg-init，目前还不支持 sub generator

至于 config 的不同类型，可以去看下文档的配置章节。

**Comment by wuchuguang** [comment]
"prod": "set EGG_SERVER_ENV =prod && egg-bin dev",

没有加载：config/config.prod.js文件。
我把sequelize的配置分在config.prod.js  config.test.js  config.dev.js上来配时，发生：sequelize取的是Sequelize Error: connect ECONNREFUSED 127.0.0.1:3306, sleep 2 seconds to retry

**Comment by wuchuguang** [comment]
cross-env EGG_SERVER_ENV=prod && egg-bin dev

**Comment by atian25** [comment]
本地开发为啥要 prod 呢？

绝大部分情况下，你应该用单测来保证质量。

如果真想使用，直接 `egg-bin dev --env=prod` 可以看下 egg-bin 源码。

**Comment by wuchuguang** [comment]
处理了。
cross-env EGG_SERVER_ENV=prod && egg-bin dev 有问题
cross-env EGG_SERVER_ENV=prod  egg-bin dev 正常了
要花时间看看egg-bin

**Comment by atian25** [comment]
这 2 句之类的区别就是操作系统环境变量的配置问题而已。。。 跟 egg-bin 啥关系都没有。
