### ISSUE TITLE
关于egg中加载器（Loader）问题

### ISSUE THREAD

**Issue by ddzyan** [eggjs/egg#4113]
现在 egg 插件中实现如下功能：
1. 异步获取动态配置信息，并且添加到 egg 的 config 对象中
2. 必须可以在 egg-sequlize 等插件之前添加，使数据库连接配置可以动态配置

预期实现步骤为：
1. 在egg-apollo-ddz插件的agent.js获取配置信息
2. 添加到config/apollo-config.json中
3. 在 config/config.*.js文件中获取配置，并且返回

现有问题;
1. 项目启动直接报错：Cannot find module './apollo-config.json'
2. agent.js 中的生命周期函数，无法在 config 加载之前运行

代码仓库中采用延迟计时器读取本地配置，模拟动态加载配置信息，地址为：https://github.com/ddzyan/apollo-loader-test

**Comment by ddzyan** [comment]
大佬们有啥解决方案吗？现在的想法是修改启动命令，类似如下：
```shell
node getApollo.js && egg-bin debug
```
node getApollo.js 负责第一次获取apollo配置，并且写入json文件中，再在 config.*.js 中读取json配置添加配置，解决config提早加载的问题

**Comment by hyj1991** [comment]
插件里 agent 里面异步获取，然后用 `agent.messenger.sendToApp` 广播到所有的 App，这样子会有什么问题么？

**Comment by ddzyan** [comment]
> 插件里 agent 里面异步获取，然后用 `agent.messenger.sendToApp` 广播到所有的 App，这样子会有什么问题么？

我还没尝试，但是觉得是不可以的。因为现在config文件的加载，在我测试中是比agent里的代码更早运行，所以我认为再agent里面加任何代码都是没有用的

**Comment by ddzyan** [comment]
![image](https://user-images.githubusercontent.com/9130123/71431226-602e6c00-270b-11ea-8722-e8c617f54de9.png)
这是文档中的loader的顺序图

**Comment by hyj1991** [comment]
图例不是先 fork agent 么，我试过上述方法是 ok 的，agent 在 `egg-ready` 事件后开始从远端获取配置，设置一个配置的广播 ID，用 `sendToApp` 广播到所有的 app worker，你可以把这个 app worker 需要使用到的 configClient 理解为一个 client，写一个 `app.addSingleton(`configClient`, createOneClient)`，最后在 `createOneClient` 里面进行真正配置内容的侦听就好了，最多加一个 `app.beforeStart` 校验判断启动前是否真的拉到必要的配置了

**Comment by hyj1991** [comment]
egg 自身的配置我理解都是静态的配置，异步获取的配置就单独写一个 client plugin 获取好了，不需要强行绑定到一起

**Comment by ddzyan** [comment]
> client plugin
现在我的插件中的agent.js的代码如下，根据打印信息，事件监听中的代码比config加载晚执行，这是为什么呢？或者方便发下您的测试代码吗？
```js'use strict';

// agent.js
const sleep = timeout => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve();
    }, timeout);
  });
};

module.exports = agent => {
  agent.messenger.on('egg-ready', async () => {
    console.log('模拟异步获取config配置');
    // 模拟异步获取配置
    await sleep(2);
    const config = require('./test.json');

    agent.messenger.sendToApp('configClient', config);
  });
};

```

输出
```
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
configWillLoad config : undefined
configDidLoad config : undefined
2019-12-25 12:21:27,255 INFO 11020 [master] egg started on http://127.0.0.1:7001 (1594ms)
模拟异步获取config配置
```

**Comment by ddzyan** [comment]
> egg 自身的配置我理解都是静态的配置，异步获取的配置就单独写一个 client plugin 获取好了，不需要强行绑定到一起

由于项目中使用到了egg-sequlize插件，而这个插件的数据库配置是直接到config中去获取sequlize配置，所以我需要将异步获取到的sequlize，绑定到config中去，以实现根据不同环境连接不同的数据库

**Comment by ddzyan** [comment]
测试代码仓库已经更新

**Comment by killagu** [comment]
@ddzyan 可以在 app.js 里面的 configWillLoad 去读取 agent 进程写好的文件，然后修改到 app.config 上去。agent 也是会加载 config 文件的，这个是符合预期的。

**Comment by hyj1991** [comment]
给你的测试仓库提了个 pr，可以看下

**Comment by ddzyan** [comment]
> 给你的测试仓库提了个 pr，可以看下

你好，首先我查看了你提交的代码，发现如下问题：
1. 你的单元测试代码的意义，我暂时不了解，我认为只能判断clientConfig对象是否创建成功，而不能判断异步动态信息是否添加，以及添加的时机是否准确。
2 在 plugin/egg-apollo-ddz 的 app.beforeStart 获取的 config 为默认的config对象，并未添加异步获取的配置信息，这段代码的意义不明。
3. app.messenger.once 事件触发是在 app.beforeStart 之后，而在此时 egg-sequelize 已经完成了初始化，所以设置的config没有作用。

打印信息如下
```
configWillLoad config : undefined
configDidLoad config : undefined
didLoad config : undefined
egg-apollo-ddz beforeStart 获取配置 {
  env: 'local',
  name: 'apollo-loader-test',
  baseDir: 'D:\\codeWork\\workspace\\temp\\egg-apollo-loader-test',
  subdomainOffset: 2,
  config: '<egg config>',
  controller: '<egg controller>',
  httpclient: '<egg httpclient>',
  loggers: '<egg loggers>',
  middlewares: '<egg middlewares>',
  router: '<egg router>',
  serviceClasses: '<egg serviceClasses>'
}
2019-12-26 12:01:38,552 INFO 14356 [egg-sequelize](1ms) Executed (default): SELECT 1+1 AS result
didReady config : undefined
2019-12-26 12:01:38,564 INFO 20348 [master] egg started on http://127.0.0.1:7001 (2166ms)
serverDidReady config : undefined
egg-apollo-ddz 模拟异步获取动态配置
egg-apollo-ddz app.messenger.once 设置配置
```
其中  SELECT 1+1 AS result 为 egg-sequelize 已经完成连接

最新的代码中，我添加了如下信息：
1. 添加 egg-sequelize 插件
2. 添加关于异步获取数据库配置，实例化 egg-sequelize 插件，modal的数据插入单元测试，用来验证是否异步动态配置config成功

如有理解错误，麻烦指出，非常感谢

**Comment by ddzyan** [comment]
> @ddzyan 可以在 app.js 里面的 configWillLoad 去读取 agent 进程写好的文件，然后修改到 app.config 上去。agent 也是会加载 config 文件的，这个是符合预期的。

首先您说的结果并不准确，我在上面的回复的打印信息中，已经说明。或者您可以看下我提交的代码仓库，提下您的代码。

**Comment by ddzyan** [comment]
这个问题在EGG中是不是无解的呢？只能采用下面的方法吗？
```
node getApollo.js && egg-bin debug
```
node getApollo.js 负责第一次获取apollo配置，并且写入json文件中，再在 config.*.js 中读取json配置添加配置，解决config提早加载的问题

**Comment by atian25** [comment]
3.0 会支持异步加载配置，在这之前只能在 agent 里面去获取。

不过一般我们都是在 k8s 那层通过 configmap 注入的，而不是框架层做。

**Comment by ddzyan** [comment]
好的，感谢回复

**Comment by SugarTiger** [comment]
2202年了，问一下题主最后是怎么解决这个需求了？
