### ISSUE TITLE
超时问题

### ISSUE THREAD

**Issue by Dilmoon2016** [eggjs/egg#4116]
系统报错：client no response in 73222ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.    
config.clusterClient = {
    maxWaitTime: 120000,
    responseTimeout: 120000,
  };
这样设置不起作用

**Comment by atian25** [comment]
从来没有支持过这个配置。

你应该去检查你的代码，为啥会用重 CPU 操作，导致 60s 都没有空隙时间来发一个心跳。

**Comment by Dilmoon2016** [comment]
比如类似统计功能需要大量耗时，egg有没有超时时间。

**Comment by Dilmoon2016** [comment]
比如类似统计功能需要大量耗时，egg有没有超时时间。

**Comment by Dilmoon2016** [comment]
> 从来没有支持过这个配置。
> 
> 你应该去检查你的代码，为啥会用重 CPU 操作，导致 60s 都没有空隙时间来发一个心跳。

如果是统计的功能需要大量耗时，egg有超时时间的概念吗

**Comment by atian25** [comment]
这种不应该在 Web 来做，应该用 阿里云函数计算 等。

如果你有重 CPU 的话，会影响到其他请求的。

**Comment by Dilmoon2016** [comment]
> 这种不应该在 Web 来做，应该用 阿里云函数计算 等。
> 
> 如果你有重 CPU 的话，会影响到其他请求的。
明白了，谢谢

**Comment by chjiyun** [comment]
maxIdleTime 能不能改长点呢，我有个26万个元素的数组操作，也是报错了

**Comment by Dilmoon2016** [comment]
> 
可以改长

**Comment by bi-kai** [comment]
debug很容易超过60s啊，没等调完就超时，这怎么玩？
