### ISSUE TITLE
egg-sequelize 不能正确的读取到 table model create 之后的返回实例的类型

### ISSUE THREAD

**Issue by WuHanMuMu** [eggjs/egg#4117]
![image](https://user-images.githubusercontent.com/16523103/71456140-fe393980-27d2-11ea-996c-5188ad8283a3.png)

## 相关环境信息
- **操作系统**： win 10 
- **Node 版本**：10
- **Egg 版本**：2.6.1

**Comment by WuHanMuMu** [comment]
`   const user = await ctx.service.user.create();
        ctx.logger.debug(user.get());
        ctx.logger.debug('1234');
        ctx.logger.info('1234');
        // @ts-ignore
        ctx.body = {
            name,
            id: user.id,
        };` 
property id does not exit on type of 'Model<unknown, unknown>'

**Comment by WuHanMuMu** [comment]
这个--没有大佬出来 说一下嘛

**Comment by whxaxes** [comment]
给个稳定复现的项目

**Comment by WuHanMuMu** [comment]
https://gitee.com/wangyong1/cash.git

**Comment by WuHanMuMu** [comment]
大佬，这个问题咋样了

**Comment by whxaxes** [comment]
现在看一下

**Comment by whxaxes** [comment]
这个是运行时创建的模型，ts 是分析不出来的。
