### ISSUE TITLE
【无解?】egg socket.io单元测试怎么覆盖app/io目录?

### ISSUE THREAD

**Issue by AshinWu** [eggjs/egg#4119]
**如题，egg socket单元测试该怎么测才能覆盖app/io/目录？**
### 详细
参考了egg-socket的test, 试了很多遍了、
![image](https://user-images.githubusercontent.com/27222274/71538372-b64a1c00-2964-11ea-93d0-2dad4a55facf.png)
`npn run test`
![image](https://user-images.githubusercontent.com/27222274/71538384-db3e8f00-2964-11ea-84ad-85288c776480.png)
可见，控制台打印不出io/controller/nsp exchange中的`console.log('into exchange()...');`
`npm run cov`
![image](https://user-images.githubusercontent.com/27222274/71538405-4a1be800-2965-11ea-9efa-0ce12ff15a67.png)
覆盖报告：
![image](https://user-images.githubusercontent.com/27222274/71538411-6455c600-2965-11ea-88f4-35f016ea9d21.png)
【问题】可见测试无法覆盖io目录。

demol链接：[egg-socket.io-test](https://github.com/AshinWu/egg-socket.io-test)
### 现状
单侧能进行socket通讯，但在controller中打印不出任何东西，也无法覆盖io目录
### 期望
单元测试覆盖app/io目录，controller能否打印东西，因为在io/conroller有很多业务。

**Comment by AshinWu** [comment]
希望有个标准答复，网上许多都直接说去看egg-socket的test，我也看过了，现在实例demo也给出来了，有什么解决方案不?

**Comment by AshinWu** [comment]
@atian25 感觉凉了，你们也不会

**Comment by ngot** [comment]
我刚刚写了一个完整例子：https://github.com/ngot/egg-socket.io-example 可以参照这个。这里例子种，测试覆盖率 100%，能够完全覆盖到。可以对比一下，是不是哪里写的和你的不一样的地方。

console.log 无法出结果，主要是因为 egg-cluster 的机制，导致 log 无法输出到 stdout, 换 stderr(console.error) 就可以。 @atian25 这个是不是一个 bug？

**Comment by atian25** [comment]
@ngot 是 worker 打印的日志没有输出到 terminal ？ 有复现方式么

**Comment by AshinWu** [comment]
> 我刚刚写了一个完整例子：https://github.com/ngot/egg-socket.io-example 可以参照这个。这里例子种，测试覆盖率 100%，能够完全覆盖到。可以对比一下，是不是哪里写的和你的不一样的地方。
> 
> console.log 无法出结果，主要是因为 egg-cluster 的机制，导致 log 无法输出到 stdout, 换 stderr(console.error) 就可以。 @atian25 这个是不是一个 bug？

我下载了您的例子简单运行了一下，貌似有一些问题：
![image](https://user-images.githubusercontent.com/27222274/72316538-765b9680-36d1-11ea-9351-a223999c61e1.png)
