### ISSUE TITLE
egg打印日志与实际不符，依文档描述默认监听存在安全问题

### ISSUE THREAD

**Issue by fuxingZhang** [eggjs/egg#4121]
#### egg打印日志与实际不符，依[文档描述][doc]默认监听存在安全问题

```
exports.cluster = {
  listen: {
    port: 7001,
    hostname: '127.0.0.1', // 不建议设置 hostname 为 '0.0.0.0'，它将允许来自外部网络和来源的连接，请在知晓风险的情况下使用
    // path: '/var/run/egg.sock',
  }
}
```

## What happens?
- egg 默认监听ipv6(::)+ipv4(0.0.0.0)，打印日志却显示http://127.0.0.1:7001 
- egg [文档描述][doc] “***不建议设置 hostname 为 '0.0.0.0'，它将允许来自外部网络和来源的连接，请在知晓风险的情况下使用*** ”，实际却监听ipv4(0.0.0.0)和ipv6(::)，默认监听存在安全问题

## How To Reproduce

1. init egg
``` bash
$ mkdir egg-example && cd egg-example
$ npm init egg --type=simple
$ npm i  
$ npm start 
```
egg print
```bash
[egg-scripts] egg started on http://127.0.0.1:7001
```

2.  check port listening

* in Linux
```bash
netstat -an | grep 7001
```
print
```bash
tcp6       0      0 :::7001       :::*       LISTEN 
```
* in Windows
```sh
netstat -aon | findstr "7001"
```
print
```bash
  TCP    0.0.0.0:7001           0.0.0.0:0              LISTENING       704
  TCP    [::]:7001              [::]:0                 LISTENING       704
```

## Context
- Node Version: v12.13.1
- Egg Version: 2.15.1
- Platform: CentOS 7.6.1810 64bit 
- Platform: Windows 10.0.18362 64bit 

[doc]: https://eggjs.org/zh-cn/core/deployment.html#%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by popomore** [comment]
你说的对，默认是不填 hostname 的，这时情况比较多，打哪个都不好。你有什么建议

**Comment by fuxingZhang** [comment]
> 你说的对，默认是不填 hostname 的，这时情况比较多，打哪个都不好。你有什么建议

### 问题
文档描述“hostname 为 '0.0.0.0'不安全”，实际却监听'0.0.0.0'。
框架认为这样做不对，然后框架又这样做。
这是相互矛盾的，不是吗！

### 建议（谈不上建议）
以下仅仅是举两个‘文档描述’、‘实际情况’、‘日志打印’三者相互统一例子

#### 处理方式一
egg由“默认不传hostname” 改为 “默认传递hostname，并且hostname的值为127.0.0.1”
- 实际监听改为与文档描述一致
- 实际监听改为与egg日志打印一致

#### 处理方式二
egg仍然默认不填hostname
egg日志打印由 
```bash
[egg-scripts] egg started on http://127.0.0.1:7001
```
改为 
```bash
[egg-scripts] egg started on http://0.0.0.0:7001 and http://:::7001
```
egg文档描述改为
```js
exports.cluster = {
  listen: {
    port: 7001,
    // hostname: '0.0.0.0', // 这里注释掉，因为实际情况没有传入hostname参数
    // path: '/var/run/egg.sock',
  }
}
```
- 文档描述改为与实际监听一致
- 日志打印改为与实际监听一致

**Comment by fuxingZhang** [comment]
国内开源的果然不行，没有一个严谨的态度，连阿里这样的都这么随意
