### ISSUE TITLE
egg-cors 相关问题

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4123]
我在本地配置了 egg-cors 插件，配置如下

#### plugin.ts
![image](https://user-images.githubusercontent.com/15381888/71556323-12e72d00-2a72-11ea-897d-d32fe37d75b4.png)
#### config.default.js 
![image](https://user-images.githubusercontent.com/15381888/71556325-21cddf80-2a72-11ea-9b39-55651a124296.png)

### 然后我在本地又起了一个服务为127.0.0.1:7002
访问发现报错

![image](https://user-images.githubusercontent.com/15381888/71556331-475ae900-2a72-11ea-8cb3-eb6fe07c3fd4.png)

这是为啥？

**Comment by atian25** [comment]
跟 cors 没啥关系，你这个某个地方写了 redirect 的逻辑，没有命中 domainWhiteList。

cors 不需要配置 domainWhiteList
