### ISSUE TITLE
【请问】怎么结合create-react-app使用？

### ISSUE THREAD

**Issue by saifeiLee** [eggjs/egg#4124]
开发环境下，egg层无法拿到CRA的dev-server里的`bundled html`。请问该怎么解决呢？

**Comment by Elliottssu** [comment]
开发环境的话可以在create-react-app 配置代理
生产环境这个可以用nginx 做 比较简单。

可以看我刚开源的一个项目，用create-react-app + egg做的
https://github.com/Elliottssu/insight

**Comment by i5ting** [comment]
参见 https://github.com/ykfe/egg-react-ssr，同时支持csr和ssr的解决方案。

里面对webpack-dev-server做了集成。
