### ISSUE TITLE
Why don't we support to customize caseStyle property within LoaderOptions?

### ISSUE THREAD

**Issue by meteortent** [eggjs/egg#4127]
## Background
In some special casese, we have to face some existing database, if they have some special tables which cannot match the rules of the default caseStyle, then we'd better keep the raw style of them.

## Proposal
It's easy to add this supporting code in app.loader.loadToApp method. Just use a config's property instead of the default string 'upper'. 

Keep this option: 
@param {String|Function} options.caseStyle - set property's case when converting a filepath to property list.

## Additional context
Nothing else.

**Comment by atian25** [comment]
try this:

```js
app.loader.loadToApp({
  caseStyle(filePath) {
     return filePath.substring(0, filePath.lastIndexOf('.')).split('/');
  }
})
```

**Comment by meteortent** [comment]
I know, but the source code was not like this. In fact, it was written like this 
`
    app.loader.loadToApp(modelDir, target, {
      caseStyle: 'upper',
      ignore: config.exclude,
      ... ...

    });
`

quote to : https://github.com/eggjs/egg-sequelize/blob/master/lib/loader.js

**Comment by atian25** [comment]
it's not a problem of egg loader.

it just the practice and code style choice of egg-sequelize 's developer.

since the usage is `await this.ctx.model.User.findAll();`, the `User` is a Class, not an instance, so I
 think that's why the developer force it to `upper`
