### ISSUE TITLE
怎么才能在egg 启动时候运行 --tls-min-v1.0 这个？V12的Node 一直报错， routines:ssl_choose_client_version:unsupported protocol

### ISSUE THREAD

**Issue by MonsterRHD** [eggjs/egg#4128]
## What happens?

腾讯的CMQ node估计是需要tlsV1.0，但是 更新node版本V12之后，运行就报错了

怎么才能让egg 运行时指定这个  --tls-min-v1.0  试了好几次都不行。比如在package.json里添加
  "scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-example --tls-min-v1.0",
    "stop": "egg-scripts stop --title=egg-server-example",
    "dev": "egg-bin dev --tls-min-v1.0",
}
或者在 npm run dev --tls-min-v1.0 都无法指定这个。

## 复现步骤，错误日志以及相关配置
以下是报错信息：
2020-01-01 07:20:49,293 ERROR 1096 nodejs.RequestError: write EPROTO 4596456896:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1929:

## 相关环境信息
- **操作系统**：mac 10.15.2
- **Node 版本**：v12.14.0
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
try `egg-scripts start --node-options--tls-min-v1.0`

https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L176

or use Node.js built-in env: https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_node_options_options

**Comment by MonsterRHD** [comment]
> 尝试 `egg-scripts start --node-options--tls-min-v1.0`
> 
> https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L176
> 
> 或使用Node.js内置环境：[https](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_node_options_options)：[//nodejs.org/dist/latest-v12.x/​​docs/api/cli.html#cli_node_options_options](https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_node_options_options)

大佬还是不OK
"scripts": {
    "start": "egg-scripts start --daemon --title=egg-server-egghoutai --sticky --node-options--tls-min-v1.0",
    "stop": "egg-scripts stop --title=egg-server-egghoutai",
    "dev": "egg-bin dev --node-options--tls-min-v1.0 --sticky",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },

**Comment by atian25** [comment]
看了下，好像是 yarg 的 bug，

`--node-options--tls-min-v1.0` 被解析为：`node-options--tls-min-v1 { '0': true }` 

是有问题的。

**Comment by MonsterRHD** [comment]
> 看了下，好像是 yarg 的 bug，
> 
> `--node-options--tls-min-v1.0` 被解析为：`node-options--tls-min-v1 { '0': true }`
> 
> 是有问题的。

这个咋整大佬，我用回了node V10了

**Comment by atian25** [comment]
知道原因了，https://github.com/yargs/yargs-parser#dot-notation 这个参数。

不过 egg-bin 不能改为 true，因为之前支持了 `https.cert` 这样的参数。

你用 `NODE_OPTIONS='--tls-min-v1.0' ./node_modules/.bin/egg-bin dev` 的方式吧

**Comment by MonsterRHD** [comment]
> 知道原因了，https://github.com/yargs/yargs-parser#dot-notation 这个参数。
> 
> 不过 egg-bin 不能改为 false，因为之前支持了 `https.cert` 这样的参数。
> 
> 你用 `NODE_OPTIONS='--tls-min-v1.0' egg-bin dev` 的方式吧

大佬 我这样写 成了 ，非常感谢大佬。谢谢。 感觉也是可以帮助到其他人吧 哈哈
 "scripts": {
    "start": "NODE_OPTIONS='--tls-min-v1.0' egg-scripts start --daemon --title=egg-server-egghoutai --sticky",
    "stop": "egg-scripts stop --title=egg-server-egghoutai",
    "dev": "NODE_OPTIONS='--tls-min-v1.0' egg-bin dev  --sticky",
    "debug": "egg-bin debug",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
