### ISSUE TITLE
运行中修改代码，服务失败，无法热更新。

### ISSUE THREAD

**Issue by HDAES** [eggjs/egg#4130]
## What happens?
使用eggjs官方脚手架搭建的环境，通过 npm run dev 能够正常的运行，但是运行中，修改app/controller中的代码，再保存 服务就会报错。
安装：
$ mkdir egg-example && cd egg-example
$ npm init egg --type=simple
$ npm i
$ npm run dev
$ open http://localhost:7001

报错图片
[点击查看图片](https://qiniu.xl686.com/egg_Issue_01.png)
报错代码
`2020-01-02 14:54:34,802 WARN 22392 [agent:development] reload worker because F:\HADES\egg-example\app\controller\home.js change
2020-01-02 14:54:35,785 WARN 22392 [ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer
[2020-01-02 14:54:35.785] [cfork:master:22264] worker:21684 disconnect (exitedAfterDisconnect: true, state: disconnected, isDead: false, worker.disableRefork: false)
[2020-01-02 14:54:35.786] [cfork:master:22264] don't fork new work (refork: false)
2020-01-02 14:54:35,786 INFO 22264 [master] app_worker#1:21684 disconnect, suicide: true, state: disconnected, current workers: ["2"]
[2020-01-02 14:54:35.791] [cfork:master:22264] worker:21684 exit (code: null, exitedAfterDisconnect: true, state: dead, isDead: true, isExpected: true, worker.disableRefork: false)`

eggjs的环境
`
 "dependencies": {
    "egg": "^2.15.1",
    "egg-scripts": "^2.11.0"
  },
  "devDependencies": {
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "egg-bin": "^4.11.0",
    "egg-ci": "^1.11.0",
    "egg-mock": "^3.21.0",
    "eslint": "^5.13.0",
    "eslint-config-egg": "^7.1.0"
  },
`
系统环境：
windows 10 
node  v12.14.0
vscode 1.40.2

**Comment by HDAES** [comment]
最小可复现代码：https://github.com/HDAES/eggIssue；
运行状态中，修改代码，就会停止服务。

**Comment by hyj1991** [comment]
我在 win10 试了下，虽然会有 warning ，但是并不影响 hot reload 结果

**Comment by hyj1991** [comment]
你看下代码的修改应该实际上是生效了吧

**Comment by HDAES** [comment]
嗯。我在运行中修改代码，然后保存，就会出现我上面 图片里的错误，服务也不可以用，只有重新启动服务才能够正常的访问，重启后 访问的就是我修改后的数据了。

**Comment by hyj1991** [comment]
上图的那个不是错误，只有 warning

**Comment by HDAES** [comment]
嗯， warning 后，我的服务就不能访问了。

**Comment by hyj1991** [comment]
![image](https://user-images.githubusercontent.com/19908330/71659383-58fa0480-2d82-11ea-81fc-220c7d7d5d1a.png)

**Comment by hyj1991** [comment]
这是我在 win10 下尝试的，有一样的 warning，服务并没有无法访问。

**Comment by hyj1991** [comment]
看你的截图和 reproduce 没法复现这个问题，看你的截图日志，这个进程的退出是预期之内的，也没有 reload 失败的信息。

**Comment by atian25** [comment]
@gxcsoccer ClusterClient 那个 warning 可能是什么原因？

**Comment by HDAES** [comment]
我发现，我 npm run dev 命令运行可以访问服务，用 npm start 命令运行 无法访问服务。

**Comment by hyj1991** [comment]
start 是生产 deploy 了，启动后有错误信息？

**Comment by HDAES** [comment]
![QQ截图20200102174358](https://user-images.githubusercontent.com/32095797/71660918-7f6e6e80-2d87-11ea-8e6c-9ba066557b3c.png)
没有报错，就是不能访问。

**Comment by hyj1991** [comment]
到你的 `C:\Users\xxxxx\logs` 下面看下错误日志文件里有没有信息，`xxxxx` 替换成你的 windows user 名称

**Comment by HDAES** [comment]
![QQ截图20200102174925](https://user-images.githubusercontent.com/32095797/71661139-41be1580-2d88-11ea-951c-e973b66288a7.png)

**Comment by HDAES** [comment]
错误日志  https://github.com/HDAES/eggIssue/tree/master/user-logs

**Comment by hyj1991** [comment]
> https://github.com/HDAES/eggIssue/blob/master/user-logs/master-stderr.log#L4

这个是你启动失败的时间么？

**Comment by hyj1991** [comment]
试下把 start 命令改成 `egg-scripts start --daemon --title=egg-server-example --workers=4` 看看能不能正常启动

**Comment by hyj1991** [comment]
没有其它问题先关闭了

**Comment by HDAES** [comment]
![QQ截图20200103094609](https://user-images.githubusercontent.com/32095797/71703095-f2bac380-2e0d-11ea-86e7-0f519c3e7858.png)
更改后还是不能访问。
https://github.com/HDAES/eggIssue/tree/master/user-logs

**Comment by hyj1991** [comment]
`wmic process get processid,commandline| findstr /C:"node.exe"`

看下 app_worker 是不是起来了

**Comment by HDAES** [comment]
![QQ截图20200103102145](https://user-images.githubusercontent.com/32095797/71704030-e4bb7180-2e12-11ea-9460-d3c3e4501f6a.png)

**Comment by hyj1991** [comment]
这个图看起来 agent_worker 和 app_worker 都在，这个时候你访问 127.0.0.1:7001 没有响应？

**Comment by HDAES** [comment]
嗯，没有响应。

**Comment by hyj1991** [comment]
这就很神奇了。。。 `wmic process` 看到启动的四个 app_worker 和一个 agent_worker 都在，却没有响应看的话看起来像是负责 cluster 调度的 master 挂了，可惜我本地没法复现，我整理下，你现在遇到的现象是 `npm run dev` 访问 ok，但是执行 `npm start 就不行对吧`

**Comment by HDAES** [comment]
你那边可以远程 帮我看下吗？还有就是 npm run dev 后 。修改代码后 ，保存后，服务也没响应。

**Comment by hyj1991** [comment]
你的 windows 版本是啥

**Comment by hyj1991** [comment]
再执行下 `wmic process get processid,commandline| findstr /C:"start-cluster"` 看下 master 到底还在不在呢

**Comment by HDAES** [comment]
![QQ截图20200103104719](https://user-images.githubusercontent.com/32095797/71704684-b50e6880-2e16-11ea-974f-0868d30e28d7.png)
![QQ截图20200103104831](https://user-images.githubusercontent.com/32095797/71704685-b50e6880-2e16-11ea-836c-49c4ab86d4b9.png)

**Comment by hyj1991** [comment]
最后再执行下 `netstat -ano |findstr 7001` 看看 7001 端口在不在监听吧。。。

**Comment by HDAES** [comment]
![QQ截图20200103105505](https://user-images.githubusercontent.com/32095797/71704828-893fb280-2e17-11ea-9e65-884daf793f83.png)

**Comment by hyj1991** [comment]
你访问的是 `http://127.0.0.1:7001` 么，看你截图 7001 端口在侦听啊，而且 pid 也是 8340 就是你上面查到的那个 master 进程

**Comment by hyj1991** [comment]
不行就换个端口试下看看，加上参数 `--port=7010`，访问下 `http://127.0.0.1:7010`

**Comment by HDAES** [comment]
![hello](https://user-images.githubusercontent.com/32095797/71705377-68c52780-2e1a-11ea-93a8-69459ba08abb.gif)
这是我所有的操作的过程。

**Comment by hyj1991** [comment]
留个钉钉？你这个问题太奇怪了，钉钉上看下能不能远程

**Comment by HDAES** [comment]
钉钉号：xiaolei96

**Comment by jiashuai1002** [comment]
我也遇到了 一模一样的问题。  
我在修改代码后，terminal上的warnning和楼主一模一样。
同时页面没有刷新， 但是页面可以访问，刷一次后就更新上去了。
求助。。

**Comment by jiashuai1002** [comment]
@hyj1991 @atian25

**Comment by atian25** [comment]
都是 Node 自带的 watcher，大概率是 bash 或 win 兼容性问题。

装个 https://github.com/eggjs/egg-watcher-chokidar 看看。

如果还不行的话，切 git bash 或 WLS 之类的命令行。

再不行就换 mac 吧，Windows 是浪费程序猿生命。

**Comment by jiashuai1002** [comment]
> 都是 Node 自带的 watcher，大概率是 bash 或 win 兼容性问题。
> 
> 装个 https://github.com/eggjs/egg-watcher-chokidar 看看。
> 
> 如果还不行的话，切 git bash 或 WLS 之类的命令行。
> 
> 再不行就换 mac 吧，Windows 是浪费程序猿生命。

我就是用的mac  10.15.6
node版本号 v14.4.0
npm版本号 6.14.7

**Comment by atian25** [comment]
那带最小可复现仓库提 issue 吧。

PS： 14 还是不稳定版，最好不要用。

**Comment by YanPengyu** [comment]
记录一下，window vscode cmd执行netsh winsock reset解决问题

**Comment by 532777032** [comment]
我写了解决方案[eggjs 报错socket is closed by other side while there were still unhandled data in the解决方案](https://blog.csdn.net/xuelang532777032/article/details/134224887?spm=1001.2014.3001.5501)
