### ISSUE TITLE
egg 存值问题

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4131]
如下图，刚设置过cookies和ctx.sessionToken的值，再取就取不到了

![image](https://user-images.githubusercontent.com/15381888/71656633-ee8f9700-2d76-11ea-9c79-84acb4802cde.png)
![image](https://user-images.githubusercontent.com/15381888/71656646-fe0ee000-2d76-11ea-804c-00dd2bc1eca9.png)

@atian25

**Comment by dark-tone** [comment]
模拟了一下发觉报错了，查了一下，ctx.setCookie不是2年前就被移除了么，可能是setCookie这个方法的问题？
![image](https://user-images.githubusercontent.com/41288382/71658382-c99f2200-2d7e-11ea-8f13-3dc8d43ac634.png)

**Comment by ycvcb123** [comment]
不是这个是我封装的方法，我现在改成下面这样也不行
![image](https://user-images.githubusercontent.com/15381888/71659209-b772b300-2d81-11ea-92fb-111c6491fd56.png)

@dark-tone @atian25

**Comment by atian25** [comment]
可以看下 egg-cookies 源码，自行分析检查下 headers 和对应的 cookie 处理

**Comment by hyj1991** [comment]
cookie 不是这么用的吧。。。 ctx.cookies.set 是把 cookie 写在 response headers 里面，浏览器下次访问同一个域下会带上来，而 ctx.cookies.get 是解析本次请求 request headers，把 cookies 解析成 kv，你这个在一次请求里 set/get 怎么可能拿到数据- -

**Comment by hyj1991** [comment]
实际上如果你的 cookie key 不变的话，再请求一次应该能拿到数据了
