### ISSUE TITLE
ctx.model调用mongoose对象 未定义

### ISSUE THREAD

**Issue by mistery-li** [eggjs/egg#4132]
![image](https://user-images.githubusercontent.com/19723639/71671022-c753bc80-2dac-11ea-894e-b9106d9e2c5c.png)
![image](https://user-images.githubusercontent.com/19723639/71671030-cd499d80-2dac-11ea-95ae-4439e20f6150.png)
![image](https://user-images.githubusercontent.com/19723639/71671040-d470ab80-2dac-11ea-93a7-94978d8bb539.png)
![image](https://user-images.githubusercontent.com/19723639/71671046-dc305000-2dac-11ea-8ae3-eed2bc2cfb19.png)
![image](https://user-images.githubusercontent.com/19723639/71671058-e18d9a80-2dac-11ea-8816-68b5ec19adc3.png)

**Comment by mistery-li** [comment]
漏发了几个
系统环境：
windows 10
node v12.14.0
vscode 1.40.2

![image](https://user-images.githubusercontent.com/19723639/71671189-519c2080-2dad-11ea-8145-65546c550055.png)

**Comment by mistery-li** [comment]
已找到原因。

**Comment by shinji3887** [comment]
我也碰到了这个问题，能说说是怎么解决的吗？

**Comment by llh1187** [comment]
> 我也碰到了这个问题，能说说是怎么解决的吗？

您好，请问是怎么解决的吗？

**Comment by llh1187** [comment]
您好，请问是怎么解决的吗？

> 已找到原因。

您好，请问是怎么解决的吗？
