### ISSUE TITLE
httpclient 文件上传问题

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4133]
文档中：：
![image](https://user-images.githubusercontent.com/15381888/71675474-c9237d00-2db8-11ea-92ed-918ae10fc521.png)

实际代码中：
![image](https://user-images.githubusercontent.com/15381888/71675450-bb6df780-2db8-11ea-929e-d300e2525bf8.png)

**Comment by atian25** [comment]
我看 https://github.com/node-modules/urllib/blob/master/lib/index.d.ts#L19 是没问题的。

可以帮忙分析下是哪里的定义有问题。

另外，你有没有锁版本？干掉重新安装全部依赖再试试看。

**Comment by whxaxes** [comment]
@atian25  https://github.com/node-modules/urllib/pull/334/files  是这个 MR 修复的，不过貌似忘记发版本了

**Comment by atian25** [comment]
那估计是没更新依赖吧。

hey, please retry after reinstall dependencies and please **never lock** it.

```bash
$ # reinstall deps and never lock it.
$ rm -rf node_modules yarn.lock package-lock.json
$ npm i --no-package-lock
```

**Comment by ycvcb123** [comment]
版本问题
