### ISSUE TITLE
提交表单问题

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4134]
背景是我需要向企业微信api提交表单获取media_id

官方提交文档如下：
![image](https://user-images.githubusercontent.com/15381888/71677249-5537a380-2dbd-11ea-8448-84eb2cfefc8a.png)

实现如下：

前端：
![image](https://user-images.githubusercontent.com/15381888/71677169-11449e80-2dbd-11ea-8214-cdeab783dc09.png)
后台：
![image](https://user-images.githubusercontent.com/15381888/71678256-b2345900-2dbf-11ea-9f9c-5327adf0c750.png)

结果是有问题的：
![image](https://user-images.githubusercontent.com/15381888/71678273-c2e4cf00-2dbf-11ea-88b3-35089082c088.png)

看了如下文档不是很明白：
https://eggjs.org/zh-cn/core/httpclient.html#%E4%BB%A5-stream-%E6%96%B9%E5%BC%8F%E4%B8%8A%E4%BC%A0%E6%96%87%E4%BB%B6

https://eggjs.org/zh-cn/basics/controller.html#stream-%E6%A8%A1%E5%BC%8F

想请教一下如何在后台实现和下面一样的效果，下面这种方式是ok的，但是因为iframe跨域问题，取不到值：

![image](https://user-images.githubusercontent.com/15381888/71678465-2ec73780-2dc0-11ea-8977-e00cf821e6c9.png)

多谢各位大神！！！！

**Comment by popomore** [comment]
https://www.npmjs.com/package/form-data
用这个试试

**Comment by atian25** [comment]
files 的底层就是 form-data ：https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L368

你这个接口，要求的是 type 等参数作为 query，而不是 form-data，你 `data` 里面的参数，直接用  querystring 拼到 url 上就好了。

**Comment by ycvcb123** [comment]
@atian25 再麻烦问下，我的要怎么media要怎么post呢？ 下面这两种方式都不行
![image](https://user-images.githubusercontent.com/15381888/71706048-8e9ffb80-2e1d-11ea-961b-45b34cf33d2c.png)

![image](https://user-images.githubusercontent.com/15381888/71706098-da52a500-2e1d-11ea-85e3-5e65b30f53ce.png)

错误信息：
![image](https://user-images.githubusercontent.com/15381888/71706056-a2e3f880-2e1d-11ea-9e69-1be7235677d8.png)

**Comment by ycvcb123** [comment]
@popomore 试了一下
![image](https://user-images.githubusercontent.com/15381888/71706376-75984a00-2e1f-11ea-8eaf-000c7f6e795d.png)

我的参数打出来都没有啥问题的，但是还是报错
![image](https://user-images.githubusercontent.com/15381888/71706388-83e66600-2e1f-11ea-9aa9-a6c0bd0aa9d4.png)

**Comment by ycvcb123** [comment]
这个问题哪位大神方便回答一下吗？

**Comment by ycvcb123** [comment]
通过如下方式解决，还好在urllib.js源码里看到了formstream @atian25 @popomore 多谢二位指导！！！

```js
const media = ctx.request.files[0];
        const access_token = await ctx.service.common.wx.getAccessToken();

        const form = new FormStream();
        form.file('media', path.resolve(media.filepath));
        const result = await ctx.curl(`https://qyapi.weixin.qq.com/cgi-bin/media/upload?type=image&access_token=${access_token}`, {
            method: 'POST',
            headers: form.headers(),
            stream: form,
            dataType: 'json'
        });
console.log('result.data::::::::::::::::::', result.data);
```

结果：
![image](https://user-images.githubusercontent.com/15381888/71711546-7ee3df80-2e3c-11ea-978b-3a16d8e06409.png)

**Comment by atian25** [comment]
喔，看了下源码， https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L353

微信是要求文件的 field 是 media，而 urllib 是默认自增的 file1

那你直接用 form stream 即可。
