### ISSUE TITLE
session如何存储所有登录信息？

### ISSUE THREAD

**Issue by zhangxp426** [eggjs/egg#4142]
当前egg.js的session是 ctx.session.user=user;这样存储的
假如每个用户登录后，都通过key-value的形式存储用户登录状态
key为用户名  vaue为登录信息 
例如 这样的形式 session[username]={"status":1,"token":""}; username是用户名
每次我要获取这个用户登录的session时可以用session.username方式获取。
应该如何实现？

**Comment by hyj1991** [comment]
不太理解你的问题，直接 `ctx.session[username] = { 用户信息 }` 不就行了么？

**Comment by hyj1991** [comment]
前提是设置好 `app.sessionStore` 的 `get`, `set`, `del` 方法，用户信息的值 encode 和 decode 以及过期时间都可以自定义，存到 redis/mysql 的话就能共享这些信息了
