### ISSUE TITLE
egg.js 修改了数据库的模型, npm run dev会重新注入实体，npm run start 不会重新注入，数据库对应字段没有更新

### ISSUE THREAD

**Issue by ycvcb123** [eggjs/egg#4143]
## What happens?
egg.js 修改了数据库的模型, npm run dev会重新注入实体，npm run start 不会重新注入，数据库对应字段没有更新

**Comment by ycvcb123** [comment]
我在数据库里删除了一个表，

重新npm run dev 的时候，查看数据库，这个表重新生成了。
再把这个表删除，重新npm run start 的时候，这个表没有重新生成。

如何在npm run start的情况下，把删除的表重新注入？

**Comment by ycvcb123** [comment]
@atian25 @dead-horse 两位大神方便解答下吗？

**Comment by okoala** [comment]
不要自动更新，所有的数据库变更都单独记录下来。如果你用 sequelize，可以看这篇文档 https://sequelize.org/master/manual/migrations.html
