### ISSUE TITLE
[Feature Request] egg的启动命令新加内存大小的控制

### ISSUE THREAD

**Issue by yomie123** [eggjs/egg#4144]
## Background
目前启动时控制内存的参数只有设置workers，如果本来服务器内存就很大，那么即使设置1个workers，那占用了太多的内存，希望能像java那样设置xms，xmx这些

## Proposal
在启动命令加设置内存的参数，比如
```js
egg-scripts start --max_semi_space_size=256 --min_semi_space_size=32
```

**Comment by atian25** [comment]
--node-options--xx

**Comment by yomie123** [comment]
> --node-options--xx

这个不行啊，我试了下，加上 --node-options--max_semi_space_size=128，不加workers的话，内存就是最大的，加了workers的时候，原来是150+M，加了这个参数之后变成370+M了

**Comment by atian25** [comment]
一个 worker 150 没毛病
