### ISSUE TITLE
eggjs-ts 使用egg-sequelize的datasources 抛出：Property 'appOneModel' does not exist on type 'Application'.

### ISSUE THREAD

**Issue by smallos** [eggjs/egg#4146]
## What happens?
eggjs-ts 使用egg-sequelize的datasources 抛出：Property 'appOneModel' does not exist on type 'Application'.
查询了相关问题但是没有结局。目前是静态类检查出现错误，所以请教一下。我看egg-sequelize已经有index.d.ts，也没有相关的讨论，所以上来请教下

## Mini Showcase Repository(REQUIRED)

https://github.com/smallos/eggjs-ts-sequelize

启动npm run dev 会出现

`/Users/nico/Documents/work/Learn/eggjs/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: [egg-core] load file: /Users/nico/Documents/work/Learn/eggjs/app/model/app_one/one.ts, error: ⨯ Unable to compile TypeScript:
app/model/app_one/one.ts(6,19): error TS2339: Property 'appOneModel' does not exist on type 'Application'.
`
## How To Reproduce

**Steps to reproduce the behavior:**
1.npm i
2.npm run dev

**Expected behavior**
1.正常可以启动

## Context
- **Node Version**:v12.1.0
- **Egg Version**:egg@2.26.0 
- **Plugin Name**:egg-sequelize
- **Plugin Version**:egg-sequelize@5.2.1 
- **Platform**:mac

**Comment by whxaxes** [comment]
参考 https://github.com/eggjs/examples/tree/master/sequelize-ts

**Comment by smallos** [comment]
> 参考 https://github.com/eggjs/examples/tree/master/sequelize-ts

这个我看过，一个的时候是可以的。但是使用datasources，两个库的时候出现的异常

**Comment by whxaxes** [comment]
![image](https://user-images.githubusercontent.com/5856440/72249869-4959a600-3635-11ea-9c31-632e88e85753.png)

datasources 的话，需要用 as

**Comment by smallos** [comment]
可以给一个例子吗？这个是自己学习ts的项目，不是很清楚具体怎么实施

**Comment by whxaxes** [comment]
那你需要先对着 ts 官方文档系统学习一下，不要一下子步子跨的太大

**Comment by smallos** [comment]
目前的实践是
`  const two = (app as any).appOneModel.define('two', {
    id: { type: INTEGER, primaryKey: true, autoIncrement: true},
    created_at: DATE,
    updated_at: DATE,
  }, {
    freezeTableName: true,
  });`
但不清楚是不是最佳实践

**Comment by ci0n** [comment]
两种方式

1. `((app as any).dbRegion as IModel).define`。（IModel 要从egg中引入）

2. 在typings/model/ 新增一个 sequelize.d.ts， 添加：
```typescript
declare module 'egg' {

  interface Application {
    appOneModel: IModel;
  }

}

```

**Comment by love477** [comment]
sequelize.d.ts建议使用如下的配置：
```
 import 'egg';
 import ExportOneModel from '../../../app/one_model/ResetRecord';

 declare module 'egg' {
    interface IModel {
        OneModel: ReturnType<typeof ExportOneModel>;
    }

    interface Application {
       oneModel: IModel;
    }
}
```
这样可以拿到sequelize model相关的定义
