### ISSUE TITLE
router.resources中没有delete路由 egg 版本2.26.0

### ISSUE THREAD

**Issue by PromptClouds** [eggjs/egg#4147]
路由
`module.exports = app => {
  const { router, controller } = app;
  router.get('/', controller.home.index);
  router.resources('/users', controller.users);
};`
user.test.js
`  describe('DELETE /users/:id', () => {
    it('should word', async () => {
      app.mockCsrf();
      const user = await app.factory.create('user');
      const res = await app.httpRequest().delete(`/users/${user.id}`);
      assert(res.status === 200);
    });
  });`
assert 错误
` 
AssertionError [ERR_ASSERTION]:   # test/app/controller/users.test.js:46  
 assert(res.status === 200)
         |   |      |       
         |   404    false   
         Response{_events:#Object#,_events
`

**Comment by atian25** [comment]
`DELETE | /posts/:id      | post           | app.controller.posts.destroy`

https://github.com/eggjs/egg-router/blob/master/lib/egg_router.js#L125

你写错 action 了吧？

**Comment by PromptClouds** [comment]
> `DELETE | /posts/:id | post | app.controller.posts.destroy`
> 
> https://github.com/eggjs/egg-router/blob/master/lib/egg_router.js#L125
> 
> 你写错 action 了吧？

` async destory() {
    const id = toInt(this.ctx.params.id);
    const user = await this.ctx.model.User.findByPk(id);
    if (!user) {
      this.ctx.status = 405;
      return;
    }
    await user.destory();
    this.ctx.status = 200;
  }`
没有错吧？

**Comment by PromptClouds** [comment]
github 仓库git@github.com:PromptClouds/egg-test.git






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "I Robot"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 中午1:13
收件人: "eggjs/egg"<egg@noreply.github.com&gt;; 
抄送: "落§月-风"<514479881@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [eggjs/egg] router.resources中没有delete路由 egg 版本2.26.0 (#4147)




Hello @PromptClouds. Please provide a reproducible example following the instruction.
 
Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
 
@PromptClouds，请根据这个说明提供最小可复现代码。
 
如果在 7 天内没有进展会被自动关闭。

**Comment by atian25** [comment]
你没设置 body，肯定是 404，如果不需要返回，应该是 204

**Comment by PromptClouds** [comment]
我改成204还是 404，添加路由
router.delete('/users/:id', controller.users.destory);

则可以运行。
但是会有另外错误。
demo地址：git@github.com:PromptClouds/egg-test.git


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TZ | 天猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 中午1:26
收件人:&nbsp;"eggjs/egg"<egg@noreply.github.com&gt;;
抄送:&nbsp;"落§月-风"<514479881@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [eggjs/egg] router.resources中没有delete路由 egg 版本2.26.0 (#4147)




你没设置 body，肯定是 404，如果不需要返回，应该是 204

**Comment by atian25** [comment]
你拼错了。。。 是 `destroy`

**Comment by PromptClouds** [comment]
....好尴尬。对不起，打扰了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TZ | 天猪"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 下午3:54
收件人: "eggjs/egg"<egg@noreply.github.com&gt;; 
抄送: "落§月-风"<514479881@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [eggjs/egg] router.resources中没有delete路由 egg 版本2.26.0 (#4147)




你拼错了。。。 是 destroy
