### ISSUE TITLE
获取不到model的sequelize对象

### ISSUE THREAD

**Issue by Topthinking** [eggjs/egg#4150]
## What happens?
![image](https://user-images.githubusercontent.com/13382821/72406867-b043a000-3798-11ea-89c9-2769ade2eada.png)

## Context
- **Node Version**: v12.13.1
- **Egg Version**: latest
- **Platform**: mac os

## 示例代码
[https://github.com/Topthinking/egg-examples/tree/master/examples/example-1](https://github.com/Topthinking/egg-examples/tree/master/examples/example-1)

**Comment by Topthinking** [comment]
egg-sequelize < 5.0时，是正常的

**Comment by okoala** [comment]
没有 .find 这个方法，用 findById、findOne、findAll
