### ISSUE TITLE
windows 环境 运行特定test文件命令要怎么写 

### ISSUE THREAD

**Issue by jiagoumengxiang** [eggjs/egg#4152]
文档中  $ TESTS=test/x.test.js npm test  这个是linux环境

windows 下要怎么写?

**Comment by jiagoumengxiang** [comment]
可以用wsl 的vscode.
不过要是能写一个windows版的命令,会对使用windows的用户们友好一点.

**Comment by atian25** [comment]
`TESTS=test/x.test.js` 这是 环境变量 的意思。属于操作系统的相关知识，不属于 Egg 的范畴，开发者应该具备这块的基础能力。
