### ISSUE TITLE
如何忽略TSLINT规则：expected a 'break' before 'case'

### ISSUE THREAD

**Issue by yyh1102** [eggjs/egg#4153]
## What happens?
根据tslint官网通过加注释的方式忽略tslint错误：

![image](https://user-images.githubusercontent.com/10328169/72495637-3841ac80-3862-11ea-9148-d995458158de.png)

or

![image](https://user-images.githubusercontent.com/10328169/72495752-8787dd00-3862-11ea-9e79-6093da1a0c77.png)

在运行`npm run test`后检查`tslint`仍然会报错：

![image](https://user-images.githubusercontent.com/10328169/72495661-4db6d680-3862-11ea-9e8f-81a3f0d1cbad.png)

## 相关环境信息
- **操作系统**： Mac OS Mojava
- **Node 版本**： v12.10.0
- **Egg 版本**：2.6.1

**Comment by atian25** [comment]
这属于 tslint 和 eslint 的问题，看下他们对应的文档即可，跟 egg 关系不大

**Comment by yyh1102** [comment]
`tslint.json`默认用的是egg提供的lint配置文件:

![image](https://user-images.githubusercontent.com/10328169/72497180-d20b5880-3866-11ea-875f-21eeba34e532.png)

这个`tslint-config-egg`在哪？

**Comment by atian25** [comment]
egg 这里只是骨架里面提供了一个默认的配置而已。
你加一条 rule 来覆盖就可以了，或者直接换为你自己需要的 extends

**Comment by atian25** [comment]
或者你看下最新的 ts 骨架，已经换为 eslint-config-egg  8.x 了，因为 tslint 他们已经不维护了。

**Comment by yyh1102** [comment]
好的，了解了，谢谢 @atian25

**Comment by yyh1102** [comment]
切换成eslint后，运行`npm run dev`仍然会报错。加rule无法覆盖掉。
