### ISSUE TITLE
使用npm start启动后CPU占用达到100%

### ISSUE THREAD

**Issue by FeiFanLiang** [eggjs/egg#4155]
## 问题表现?
在服务器部署时,使用npm start启动项目,过了一段时间发现CPU负载到达100%,在本地进行同样代码的测试,在十分钟左右CPU突然达到100%,部署服务后没有进行服务访问,查看日志没有发现异常输出,没有定时任务

## 日志内容
![image](https://user-images.githubusercontent.com/30872365/72637515-77741880-399c-11ea-9637-18ac126714a6.png)
![image](https://user-images.githubusercontent.com/30872365/72637790-08e38a80-399d-11ea-8d85-9c2af427f8aa.png)

## Context
- **Node Version**:v11.0.0
- **Egg Version**:2.26.0
- **Plugin **Name**:egg-cors,*egg-cors*,*egg-session-redis*,*moment*
- **Plugin Version**:
- **Platform**:windows 64

**Comment by atian25** [comment]
用 alinode 分析

**Comment by hyj1991** [comment]
这个问题和框架本身关系不大，有其他疑问可以加 alinode 官方钉钉群寻求支持，先关闭了
