### ISSUE TITLE
_matchedRouteName 能否一个restful请求得到同一个值 或者有其他参数得到这个值

### ISSUE THREAD

**Issue by nightmareT** [eggjs/egg#4159]
背景：
最近准备做一个简单的后端权限管理，路由是用egg的restful写法实现的，期望在router前过滤掉对于这个restful没有权限的请求，希望是利用_matchedRouteName过滤。但是我发现_matchedRouteName这个参数的单复数很难处理，比如我用companies，使用put的时候变成了company（我很好奇这个转化单复数 难道还根据英语单独实现的） 然后delete的时候 也不是文档里写到的单数  变成了destroy_company 这样我就没得玩了。  我想请问下这个
router.resources('companies', '/api/v1/companies', controller.companies);设置，收到请求的时候有一个字段固定告诉我是匹配的companies这个参数吗？

**Comment by qingdengyue** [comment]
然而不是，路由名称是有单复数的变化:
https://eggjs.org/zh-cn/basics/router.html

![QQ图片20200120154322](https://user-images.githubusercontent.com/3230673/72707546-9d1b4080-3b9b-11ea-9897-21d519c8d59b.png)

**Comment by nightmareT** [comment]
谢谢  你说的这个我知道。 暂时也是用这种方式的。 我只是想知道会不会有一个统一的字段，这样我可以省去很多工作。 我想的是在注册resource的时候传的第一个参数是统一的比如companies 如果获取也是统一这样就可以归类处理

**Comment by guohuihot** [comment]
我想控制到controller里的action, 不知道怎么拆route对象

**Comment by atian25** [comment]
https://github.com/eggjs/egg-router/blob/f0b29ec34df32ba9d872f6318f4febd2b4ef9359/lib/egg_router.js#L165

命名转换逻辑是固定的，你可以自行转换下，或者提 PR 优化
