### ISSUE TITLE
Generate LICENSE automatically

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#416]
Add a config to egg-ci, generating when every installation. And LICENSE should contain date.

**Comment by popomore** [comment]
@atian25 we should check why github hadn't detected the LICENSE.

<img width="1034" alt="screenshot 2017-02-20 11 49 05" src="https://cloud.githubusercontent.com/assets/360661/23111306/a71ec49c-f762-11e6-9126-cd7bfcd1d58a.png">

**Comment by atian25** [comment]
had sent feedback to GitHub, wait for response

**Comment by atian25** [comment]
It looks like your LICENSE file has a couple of differences to the MIT license we use for comparison here:

https://choosealicense.com/licenses/mit/

Please could you update your license to match that to see if that helps?

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/23296768/89db416a-fab1-11e6-90ad-816950df5ca2.png)
