### ISSUE TITLE
插件开发中使用addSingleton,打印插件,为什么方法外面包裹了一层 create

### ISSUE THREAD

**Issue by shenqidebaozi** [eggjs/egg#4161]
打印 app 下面的插件信息,方法外面多了个 create,ctx 下面没有,这是为什么呢?
这是 app 下
![image](https://user-images.githubusercontent.com/35397691/72694051-7561b380-3b6e-11ea-868a-d1f9913821a5.png)
这是 ctx 下
![image](https://user-images.githubusercontent.com/35397691/72694069-84e0fc80-3b6e-11ea-9905-ee0345c7349d.png)

**Comment by hyj1991** [comment]
因为这个方法本来就是 App/ Agent 的成员方法啊，ctx 当然没有了
