### ISSUE TITLE
关于 dev环境app目录里面的文件监听问题

### ISSUE THREAD

**Issue by lz7git** [eggjs/egg#4162]
![1579506406(1)](https://user-images.githubusercontent.com/33478936/72707757-292d6800-3b9c-11ea-9806-360c31ce52d2.png)

在 开发环境(dev) 中， 对 app 里面的文件目录进行 rmdir 操作的时候，抛出 operation not permitted 问题

实验步骤
  1. 执行mkdir操作，在app里面新建一个目录
  2.执行rmdir操作，移除app里面的目录

**Comment by atian25** [comment]
请提供最小可复现仓库

**Comment by lz7git** [comment]
仓库：https://github.com/lz7git/dev_dir

**Comment by atian25** [comment]
看了下，是 Node fs 内部的报错，这个报错平时在 Win CI 不时也能看到，应该是文件句柄还没释放的时候，就操作文件啥的，属于 Node 这块的 Win 兼容性问题了，这个我们没办法解决，尽量用 Win 那个 Linux 子系统，或者 Git 自带的那个 bash 吧

**Comment by lz7git** [comment]
@atian25 app目录下的所有文件都是被监听到的吗

**Comment by atian25** [comment]
可以看下 egg-development 配置。
