### ISSUE TITLE
源码中的require('..')在linux下的node无法识别，会报Cannot find module '..'

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4164]
## What happens?
在运行npm run start时，报错：Cannot find module '..'

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
运行npm run start即可复现

错误信息：
Error: Cannot find module '..'

现在可以通过修改/node_modules/egg-scripts/bin/egg-scripts.js中的代码：
把const Command = require('..');
改成
const Command = require('egg-scripts');
可以正常运行。

## 相关环境信息
- **操作系统**：CentOS Linux release 7.6.1810 (Core)
- **Node 版本**：v12.4.0
- **Egg 版本**：2.24.0

**Comment by atian25** [comment]
是你的打包问题，把软连接变为硬链接了，检查你的 tar 打包脚本参数
