### ISSUE TITLE
extend context 并发请求间相互污染

### ISSUE THREAD

**Issue by zhengchaogao** [eggjs/egg#4165]
## What happens?
extend context 上一个属性，该属性为对象。并发请求时，后面的请求会覆盖前一条请求的值。context请求级别对象，不该相互覆盖。

## 最小可复现仓库
https://github.com/zhengchaogao/egg-issue

## 复现步骤，错误日志以及相关配置
node script.js

日志
{"name":"abc1","nameType":"abc1Type"}
{"name":"abc1","nameType":"abc2Type"}
{"name":"abc1","nameType":"abc3Type"}

## 相关环境信息
- **操作系统**：mac High Sierra
- **Node 版本**：v8.12.0
- **Egg 版本**：^2.15.1

**Comment by hyj1991** [comment]
你的代码里的 `ctx.userInfo.name = ctx.params.name;` 相当于直接改了 `app/extend/context.js` 里面的对象值了。

这样当然就算每次都 `new KoaContext` 再把 `app/extend/context.js` 里面的内容合并进来都一样会变成你赋值后的咯。

你可以做个简单的测试，在你的 controller 代码里加上以下逻辑，相当于直接打印 `require` 后的值，就会发现 `app/extend/context.js` 里面的内容本身就被你的赋值改掉了
```
console.log(require('../extend/context'));
```

**Comment by hyj1991** [comment]
> https://github.com/demopark/koa-docs-Zh-CN/blob/master/api/context.md#ctxstate

你要每次在 ctx 上共享 userinfo，正确的做法是直接赋值给 `ctx.state`，这是 koa context 上自带的一个共享内容的命名空间

**Comment by zhengchaogao** [comment]
> 这样当然就算每次都 new KoaContext 再把 app/extend/context.js 里面的内容合并进来都一样会变成你赋值后的咯。

多谢🙏。就是这里，有个提议能否app/extend/context.js通过export出来function的方式，让每个请求拿到不同的对象，这样可以保持context请求级别对象的定义？

**Comment by zhengchaogao** [comment]
或者在文档中建议通过`ctx.state` 的方式传递值。查并发的问题有点费劲，app/extend/context.js使用mixin的方式确实挺让人困惑。 @hyj1991

**Comment by atian25** [comment]
> > 这样当然就算每次都 new KoaContext 再把 app/extend/context.js 里面的内容合并进来都一样会变成你赋值后的咯。
> 
> 多谢🙏。就是这里，有个提议能否app/extend/context.js通过export出来function的方式，让每个请求拿到不同的对象，这样可以保持context请求级别对象的定义？

用 getter 就好了。
