### ISSUE TITLE
安装eggjs 脚手架为什么会Warn

### ISSUE THREAD

**Issue by allenlinc** [eggjs/egg#4166]
ssh:
npm init egg --type=simple
$ npm i
警告如下：

npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.

npm 和node版本都是最新的

**Comment by atian25** [comment]
仔细阅读下英文，搜索下对应关键词就可以了

可以不用太理会。
