### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#4167]
How can I increase memory limit to 8GB with `egg-scripts`?

**Comment by hyj1991** [comment]
> https://github.com/node-modules/common-bin/blob/master/lib/helper.js#L176

```--node-options--max-old-space-size=8192``` may be useful, but I'm not sure. 
Ping @atian25

**Comment by atian25** [comment]
yes, use `--node-options--` or `NODE_OPTIPONS`env
