### ISSUE TITLE
egg是否支持router接口分别由不同port监听

### ISSUE THREAD

**Issue by scnu13216** [eggjs/egg#4169]
在koa2里面，app.js中是需要开发者自己配置port及对应的router，而且可以同时开启多个port，不同的port可以配置所需的router。
也就说，某些router定义的接口只会在部分配置了这个router接口的端口上被访问到，没有配置这个router的端口将会返回404。
![image](https://user-images.githubusercontent.com/18018680/73590128-a13f4a80-4519-11ea-838a-c46af9e3615b.png)

想知道egg中是否也有同样的操作

**Comment by atian25** [comment]
不支持，这不应该是框架层做的事。合理划分你的应用，如实在是有需求，在 nginx 或开多个应用。

**Comment by scnu13216** [comment]
对不支持这个功能表示失望，但还是非常感谢您的回复

**Comment by atian25** [comment]
因为这个功能不应该这样做，你的方案是不合理的。

你应该在 nginx 做多端口的接入，都转发到同个 egg 应用的不同 prefix 的 router。
