### ISSUE TITLE
egg-thrift

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#417]
thrift是一个非常常见普遍的rpc框架和代码生成器，考虑egg支持.

eg: https://cnodejs.org/topic/501280dcf767cc9a51419013

官网： http://thrift.apache.org/tutorial/nodejs

**Comment by huacnlee** [comment]
要搞这个，得搞 TCP 的 Server，挺复杂的。而 Egg 做的事情是 HTTP 服务。

况且，实际上 Thrift 也不是一个太好的方案。

**Comment by dead-horse** [comment]
这一类的需求交给社区吧，我们只实现 dubbo

**Comment by jtyjty99999** [comment]
ok ，那先关了，等社区的人pr吧 @huacnlee @dead-horse
