### ISSUE TITLE
想给egg-view-ejs包提一点点建议，有两个链接有问题。

### ISSUE THREAD

**Issue by darrenliuwei** [eggjs/egg#4170]
想给`egg-view-ejs`包提一点点建议

首先打开这个链接：https://www.npmjs.com/package/egg-view-ejs

然后发现右边的两个链接里多写了`egg-`
![WeChat Screenshot_20200202152946](https://user-images.githubusercontent.com/10508248/73604767-f8542680-45d0-11ea-9d52-8b7e63ce23b4.png)

**Comment by atian25** [comment]
奇怪，是 npm 的 bug？

https://github.com/eggjs/egg-view-ejs/blob/master/package.json#L60

这里是没问题的

**Comment by atian25** [comment]
可能是发包问题，我发个 patch 看看，感谢反馈
