### ISSUE TITLE
编译调试一条龙

### ISSUE THREAD

**Issue by jasonjiflyer** [eggjs/egg#4171]
## What happens?
当我使用ES6开发时，需要使用babel进行编译，将代码生成到另一个目录，eggjs是否能提供编译调试的一条龙服务，或者是否提供一些最佳实践与例子出来。

现在我要使用ES6的话，我必须自己去调用babeljs去编译，然后调用egg-bin dev去执行新编译出来的代码。还不如egg-bin dev把这些事情都做了。

另外顺便说一下：https://issue.eggjs.app/  这个打不开。钉钉的二维码也已经过期。微信号一个加了没有回复，一个搜索不到。

**Comment by atian25** [comment]
egg 本身的定位不会考虑提供这块的支持，你可以参考我们 ts 的做法，在启动的时候通过 --require 的方式引入 babel register 的方式来实现。

eggjs.app 的域名没法备案，要等 @thonatos 处理。
