### ISSUE TITLE
无法调用自定义的插件

### ISSUE THREAD

**Issue by tyisme614** [eggjs/egg#4172]
## What happens?

按照 egg-mysql 的写法，在插件初始化时调用 addSingleton方法添加单例'dataCache'，但是在主程序的服务location.ts里却无法通过this.app来调用自定义的插件'dataCache'。控制台提示 dataCache is not a property of 'Application'。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/tyisme614/temp_mini_repo.git

## 复现步骤，错误日志以及相关配置

可以直接运行命令 npm test 就可以看到报错。

重新部署过环境，没有任何效果。

## 相关环境信息
- **操作系统**：MacOS X 10.15.3
- **Node 版本**：Node 12.8.0
- **Egg 版本**：2.6.1

**Comment by tyisme614** [comment]
使用 this.ctx.dataCache 调用插件就直接报 undefined。 另外用egg-mysql 也是报一样的错误

**Comment by tyisme614** [comment]
已经解决了，需要自己补充index.d.ts的声明。 希望贵司能补充官方文档。

**Comment by atian25** [comment]
d.ts 引起 undefined ？你指的是代码编辑器提示 undefined 而不是运行期 undefined？

d.ts 是 TS 相关的知识，在我们的 TS 文档里面提到需要自己处理 merge declear
