### ISSUE TITLE
nodejs.AppWorkerDiedError

### ISSUE THREAD

**Issue by WernerWu5** [eggjs/egg#4175]
linux服务器上，使用pm2启动egg项目。
错误如下：
![image](https://user-images.githubusercontent.com/48075998/74097497-a028a180-4b47-11ea-8745-fe63b665d527.png)

**Comment by atian25** [comment]
看 common-error 日志以及上面一点的日志。

另外， pm2 没有使用的价值，没必要用

**Comment by xixichensh** [comment]
监控体系都是pm2，真是搞不懂，出了这种问题居然让别人换部署方式
