### ISSUE TITLE
【文档】请问这个例子里的 `safe` 是指什么？有参考的实现方式吗？

### ISSUE THREAD

**Issue by Jeff-Tian** [eggjs/egg#4177]
![image](https://user-images.githubusercontent.com/3367820/74212981-f3c6f680-4cd1-11ea-87c4-c55f4200edc7.png)

`ctx.csrf` 是 `config` 里配置的，这个 `safe` 有什么方法生成么？可否给个例子？

谢谢！

**Comment by atian25** [comment]
是 nunjucks 的 filter，代表前面的字符串不会被 escape
