### ISSUE TITLE
关于中间件执行顺序问题

### ISSUE THREAD

**Issue by southorange1228** [eggjs/egg#4178]
## Background
egg使用中间件通过config配置中间件数组实现，目前了解到的是中间件一定是在router之前执行的，这里有一个场景就是中间件如果需要在router之后执行如何实现。``
```javascript
const koa = require("koa");
const koarouter = require("koa-router")();

const app = new koa();

koarouter.get("/", async (ctx, next) => {
  console.log(1)
  ctx.body = "hello world";
});

app.use(koarouter.routes());
app.use(koarouter.allowedMethods());

app.use(async(ctx,next) => {
  console.log(2)
  await next();
})

app.listen(3000);
```
这里有个例子，比如我有个中间件console.log(2)需要在router之后执行，也就是说我全局中间件需要在controller之后执行，这部分的中间件是如何区分的呢？

## Proposal
Describe the solution you'd like, better to provide some pseudo code.

**Comment by hyj1991** [comment]
```js
async function middleware(ctx, next) {
  await next();
  // 编写你再 router 执行完成之后的逻辑
}
```

Egg.js 是基于 Koa 封装的，你可以去了解下 Koa 的洋葱圈中间件模型

**Comment by southorange1228** [comment]
我理清楚了，之前没理清楚，总觉得是有区别的。谢谢解答
