### ISSUE TITLE
从egg下载excel,或者图片无法打开

### ISSUE THREAD

**Issue by NickLee380** [eggjs/egg#4179]
下载txt文件，打开正常，但是下载excel, 图片等，无法正常显示。
前端：
Axios({
        url: '/api/download',
        method: 'post',
        data: { filename },
        responseType: 'blob'
      }).then((response) => {
        console.dir(response)
        let blob = new Blob([response.data])
        const url = window.URL.createObjectURL(blob)
        const link = document.createElement('a')
        link.href = url
        link.setAttribute('download', filename)
        document.body.appendChild(link)
        link.click()
      })

后端：
        ctx.attachment(query.filename);
        ctx.set('Content-Type', 'application/octet-stream');
        ctx.body = fs.createReadStream(query.filename);

**Comment by atian25** [comment]
直接浏览器访问后端的 URL 看下载的是否正常

**Comment by NickLee380** [comment]
直接打开时正常的
尝试了好几天，找到了一个替代的办法：
后端：
ctx.attachment(query.filename);
ctx.set('Content-Type', 'application/octet-stream');
ctx.body = fs.readFileSync(tempFile, { encoding: 'binary' });

前端：
let buf = Buffer.from(response.data, 'binary')
 jsfiledownload(buf, filename)

我怀疑，在前端设置的 responseType: 'blob',对egg来说根本不起作用。

**Comment by atian25** [comment]
如果直接下载是正常的，说明这问题跟 egg 没啥关系，就是你的前端逻辑的问题。

> 我怀疑，在前端设置的 responseType: 'blob',对egg来说根本不起作用。

不是不起作用，而是根本没有任何关系，这是你前端的处理逻辑，egg 那边只是扮演一个标准的 HTTP 服务而已。

PS：不要用 `readFileSync` 同步方法会验证影响你的并发性能。
