### ISSUE TITLE
如何在进程退出的时候执行资源回收操作？

### ISSUE THREAD

**Issue by guohaoyun** [eggjs/egg#4181]
启动命令：``` egg-scripts start --title=egg-server-example ```
停止命令：``` egg-scripts stop --title=egg-server-example```

我希望在进程收到停止信号后，执行一个异步操作，并等待它返回之后再退出。
目前我是这么做的，请看 app.js 代码
```
const Logger = require('egg-logger').Logger;
const FileTransport = require('egg-logger').FileTransport;

class AppBootHook {
  constructor(app) {
    this.app = app;
  }
  async serverDidReady() {
    const logger = new Logger();
    logger.set('file', new FileTransport({
      file: './log',
      level: 'INFO',
    }));
	
    // 注意，SIGTERM 不支持 windows 系统
    process.on('SIGTERM', async () => {
      logger.info('异步开始');
      await require('bluebird').delay(3000); // 模拟异步操作
      logger.info('异步结束');
    });
  }
}

module.exports = AppBootHook
```

但是我发现”异步结束“这句并没有打印出来，所以我有两个问题想请教一下。
1. 为什么进程没有等待异步操作完成就退出了。
2. egg如何在进程退出前，进行资源回收？（回收操作是异步的，且必须完成后才退出进程）

我看文档写了 **beforeClose这个方法不建议在生产环境使用, 可能遇到未执行完就结束进程的问题。** 所以不太考虑这个方案。

这是最小复现的[仓库地址](https://github.com/guohaoyun/egg_example_SIGTERM)

**Comment by atian25** [comment]
beforeClose 会等，但最多等 5s，不会无限制等下去。

如果你的时间较长，可以设置环境变量 https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L680

但一定要谨慎评估为啥会这么长时间。

**Comment by guohaoyun** [comment]
感谢回复！考虑之后，感觉用 beforeClose 足矣。
