### ISSUE TITLE
Log rotate in egg-mock

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#4183]
I am using egg as library in a project
https://github.com/eggjs/egg/issues/3262#issuecomment-444483287

```js
const mm = require('egg-mock');

const app = mm.app({
    baseDir: path.join(__dirname, '../../'),
    cache: false,
    coverage: false,
    clean: false,
  });
  await app.ready();

  const ctx = app.mockContext();

// My codes has access to egg services
```

I have a problem with log rotation , I see that I have a 100GB log file (after 3 months) and there is no rotation
How can I enable log rotation in egg-mock

**Comment by atian25** [comment]
egg-mock is a lib for unit test, it has some hacky(make agent and worker run at one process) , I don't think it's a good start point for prod.

egg-logrotator is driven by egg-schedule, I'm not sure whether egg-mock affect the agent schedule, you may need to check the egg-schedule.log

if you need single process, could try the [single mode](https://github.com/eggjs/egg/blob/18efac152dd5cf789d1e79b1c1fb1fb4ec2013a1/lib/start.js#L11), then the log rotation will be the duty of k8s infrastructure.

**Comment by popomore** [comment]
Don't use it in production.
