### ISSUE TITLE
[Question] Some questions about the official documentation

### ISSUE THREAD

**Issue by screetBloom** [eggjs/egg#4184]
## Background
官方中有如下这样的描述：
``` sh
我们在使用 Koa 中间件过程中发现了下面一些问题：

1. 中间件加载其实是有先后顺序的，但是中间件自身却无法管理这种顺序，只能交给使用者。这样其实非常不友好，一旦顺序不对，结果可能有天壤之别。
2. xxx
3. xxx
综上所述，我们需要一套更加强大的机制，来管理、编排那些相对独立的业务逻辑。
```

## Question
官网中其实并未看到具体是如何解决中间件顺序问题的
想了解一下具体场景，比如出现多个中间件都扩展了同一个Request 类，甚至是初始化时多个中间件对同一个文件进行了写入或者删除操作
这种情况下执行顺序是严重影响最终呈现的结果的，请问egg中是如何避免此类加载顺序问题的呢

**Comment by atian25** [comment]
- 中间件通过 config.middleware 去配置的，区分了框架中间件和应用中间件，前者由框架维护者维护，后者是应用开发者自己维护，就已经解决了冲突问题
- `初始化时多个中间件对同一个文件进行了写入或者删除操作` --- 不应该这么做

**Comment by screetBloom** [comment]
> 中间件通过 config.middleware 去配置的，区分了框架中间件和应用中间件，前者由框架维护者维护，后者是应用开发者自己维护，就已经解决了冲突问题

对应用中间件来说，应用的维护者可能并不是十分清楚引入的每一个中间件都做了哪些事情，针对“中间件顺序”导致的问题还是需要使用者自己去管理
这样去处理的话，是不是官网中提到的场景「1. 中间件加载其实是有先后顺序的，但是中间件自身却无法管理这种顺序，只能交给使用者。这样其实非常不友好，一旦顺序不对，结果可能有天壤之别。」还是没有得到解决

**Comment by hyj1991** [comment]
这是当你的项目需要引入存在依赖关系的一组中间件时，egg 框架提供了这样的手段来让你自己管理这些中间件的依赖顺序 —— 这是相对与直接使用 koa 开发者是没办法控制顺序来阐述的。

这段话并不是说开发者引入的中间件会自己知道自己该处于项目的哪个位置，实际上也没办法做到，除非所有的中间件都像 egg 插件一样通过某种方式来申明自己依赖（没办法成为标准）

**Comment by screetBloom** [comment]
> 这是当你的项目需要引入存在依赖关系的一组中间件时，egg 框架提供了这样的手段来让你自己管理这些中间件的依赖顺序 —— 这是相对与直接使用 koa 开发者是没办法控制顺序来阐述的。
@hyj1991  上诉写的「提供了这样的手段」是指哪些手段，是指config.default.js中middleware数组顺序吗？
相比koa开发时根据逻辑控制next有什么明显的优势吗

**Comment by hyj1991** [comment]
项目引入的中间件又不是一个两个，插件里你申明好引入的中间件自己的依赖，最终加载顺序是计算出来的，Koa 全靠人肉啊，而且插件发布成独立的包后，其他使用的人就不需要管顺序问题了，纯 koa 中间件你排出加载顺序了下一个使用的人还得自己来算啊
