### ISSUE TITLE
中间件能不能获取service函数中的返回值

### ISSUE THREAD

**Issue by nuonuonuonuoyan** [eggjs/egg#4186]
中间件中如何获取service,我在service中声明了一个函数，该函数为读取数据库中的值，中间件中需要用到这个值；
ctx.session赋值完成后，再次取值为undefined,所以想到了使用数据库来做持久化存储

**Comment by atian25** [comment]
> 中间件中如何获取service

ctx.service

> ctx.session赋值完成后，再次取值为undefined

不要拿 ctx.session 来当一个中间存储器，你可以放其他字段，最后才设置到 session 的。
