### ISSUE TITLE
egg-logger：使用util.format不会产生性能问题？

### ISSUE THREAD

**Issue by fuxingZhang** [eggjs/egg#4188]
https://github.com/eggjs/egg-logger/blob/a1b6c85ad13f7fa39dc3fc72029c39604b05cd69/lib/utils.js#L89

https://github.com/eggjs/egg-logger/blob/a1b6c85ad13f7fa39dc3fc72029c39604b05cd69/lib/utils.js#L148

**Comment by atian25** [comment]
如果你遇到性能问题，可以先用 alinode 分析下是不是它的问题。

发自我的iPhone

**Comment by fuxingZhang** [comment]
nodejs官网指出
https://nodejs.org/dist/latest-v12.x/docs/api/util.html#util_util_format_format_args
> util.format() is a synchronous method that is intended as a debugging tool. Some input values can have a significant performance overhead that can block the event loop. Use this function with care and never in a hot code path.

>官网指出util.format() 是用作调试工具的同步方法，某些输入值可能产生严重的性能开销，从而阻止事件循环。 请谨慎使用此功能，切勿在热代码路径中使用。

尽然官网明确指出，这里难度没有问题码

**Comment by fuxingZhang** [comment]
> 如果你遇到性能问题，可以先用 alinode 分析下是不是它的问题。 发自我的iPhone
> […](#)
> 在 2020年2月23日，11:14，zfx ***@***.***> 写道： ﻿ https://github.com/eggjs/egg-logger/blob/a1b6c85ad13f7fa39dc3fc72029c39604b05cd69/lib/utils.js#L89 https://github.com/eggjs/egg-logger/blob/a1b6c85ad13f7fa39dc3fc72029c39604b05cd69/lib/utils.js#L148 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

作为一个普通开发者

**Comment by fuxingZhang** [comment]
操作失误，把issue关了

**Comment by fengmk2** [comment]
文档写的时候应该是 N 年前吧，现在字符串操作对于 node 来说是非常高性能的。如果真的 format 影响到你的应用性能的时候，请将这个案例提供给我们，我们会去努力提供 format 的性能。

**Comment by fuxingZhang** [comment]
> 文档写的时候应该是 N 年前吧，现在字符串操作对于 node 来说是非常高性能的。如果真的 format 影响到你的应用性能的时候，请将这个案例提供给我们，我们会去努力提供 format 的性能。

好
