### ISSUE TITLE
egg-swagger2无法在ts中使用

### ISSUE THREAD

**Issue by szptWangrs** [eggjs/egg#4189]
## What happens?

用egg.js官方给的骨架快速初始化的TS模板 无法实例化swagger对象
![image](https://user-images.githubusercontent.com/26304597/75110571-9a17e200-566a-11ea-9eea-9d4e324cd085.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by hyj1991** [comment]
[egg-swagger2](https://github.com/CaanDoll/egg-swagger2) 不是官方维护的，找这个包的作者去提 issue 吧
