### ISSUE TITLE
httpclient urllib 接口发送大量请求

### ISSUE THREAD

**Issue by meicx** [eggjs/egg#4193]
hi~最近我们的web端服务发现有大量接口调用（千万级），但是页面访问量只有几千，查找日志发现，调用接口的agent信息为本机node-urllib/2.34.0（占总接口请求数的90%），不是正常的接口调用，这可能是什么原因导致的？

**Comment by atian25** [comment]
检查你的代码呗，看是不是被攻击了。

另外也可以对 httpclient 加下日志。

**Comment by meicx** [comment]
> 检查你的代码呗，看是不是被攻击了。Egg 不会主动调用 httpclient。
> 
> 另外也可以对 httpclient 加下日志。

看着不是被攻击了，agent信息里的版本和本机环境完全一致，应该是本机发出的，但是代码里面只是curl了这个请求，开始的日志里有一些接口访问超时的日志，后面就有大量的urllib访问的日志了

**Comment by atian25** [comment]
我的意思是，检查你代码，哪里有 httpclient 的请求逻辑，检查是不是有问题。（Egg 没有主动调用 httpclient 发任何请求的内置逻辑）

然后也可以通过 httpclient 提供的 hook，打下日志看看是否正常。
