### ISSUE TITLE
ctx.curl 可以模拟客户端发送get、post请求，但是发送带文件的请求不成功

### ISSUE THREAD

**Issue by xiaopenggithub** [eggjs/egg#4195]
## What happens?

场景：在服务端发送请求

ctx.curl 可以模拟客户端发送get、post请求，但是发送带文件的请求不成功，
后改用request-promise可以模拟发送文件成功

request-promise可以发送form-data数据

ctx.curl是否也支持呢？

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
可以看 urllib 这个 npm 包的文档。

另，可以参考 https://eggjs.github.io/zh/guide/httpclient.html#%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0-multipart
