### ISSUE TITLE
ctrl-C应用退出后才打印日志

### ISSUE THREAD

**Issue by ZYSzys** [eggjs/egg#4197]
## What happens?

终端接收到`ctrl-C`，先是打印`app_worker exit`，然后应用退出，然后再打印`send kill SIGTERM to agent worker`，看着就很别扭...

![Kapture 2020-02-29 at 18 23 41](https://user-images.githubusercontent.com/23313266/75605824-5f59f200-5b21-11ea-8f60-2db4463a185b.gif)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

```
npm init egg --type=simple bug
cd bug

npm run dev

应用启动后 <ctrl>-C 退出
```

## 相关环境信息
- **操作系统**：macOS X 10.14.4
- **Node 版本**：v12.14.0
- **Egg 版本**：v2.26.0

**Comment by atian25** [comment]
系统的正常现象
