### ISSUE TITLE
egg-logrotator 分割日志存储位置设置

### ISSUE THREAD

**Issue by junieHF** [eggjs/egg#4199]
## What happens?
当在linux操作系统中，使用生产环境（npm start）启动，日志分割后存放在了
`
/root/logs/app_name/
`
下，不是在项目部署的路径下，怎么配置自定义的分割后日志文件保存地址

## 相关环境信息
- **操作系统**：centos
- **Node 版本**：11
- **Egg 版本**：2.15

**Comment by atian25** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L254

配置下这个

**Comment by Henry-WHY** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L254
已经按照此处进行配置，但是生产环境的日志依旧写入到了  /root/logs 文件夹下，可以通过配置文件修改，直接放在项目根目录的 logs 中吗？

**Comment by atian25** [comment]
可能是你改的不对，或者是你问的是 stdout.log ？ 这个看 egg-scripts 文档

**Comment by Henry-WHY** [comment]
> 可能是你改的不对，或者是你问的是 stdout.log ？ 这个看 egg-scripts 文档

我再去排查一下，谢谢！
