### ISSUE TITLE
Add prefix to encoded data in serialize-json for buf detection

### ISSUE THREAD

**Issue by shaoshuai0102** [eggjs/egg#420]
Now:

``` js
[1, 2, 3, 5]

// =>

'1|2|4^3^^^@0|1|3|2]'
```

I want to add wrap header string, so that we can detect if a buffer is a valid buffer encoded by `serialize-json` via `JSON.valid(buf)` in order to fail fast. For example:

```js
[1, 2, 3, 5]

// =>

'__serialize-json__1|2|4^3^^^@0|1|3|2]'
```

This idea originated from zookeeper plugin development, where I want to use `serialize-json` to encode and decode data. But when zookeeper is shared by different kinds of applications, data stored in it is not always encoded by `serialize-json`. So maybe I will write like this:

```js
const JSON = require('serialize-json');

exports.decode(buf) {
  if (JSON.valid(buf)) {
    return JSON.decode(buf);
  }

  return buf;
}
```

What do u think of this? @gxcsoccer

**Comment by pmq20** [comment]
Interesting, like a magic number. Another approach could be recording them in a global map.

**Comment by shaoshuai0102** [comment]
> Interesting, like a magic number. Another approach could be recording them in a global map.

If not destroyed properly, this approach could easily lead to memory leak.

**Comment by popomore** [comment]
Is the prefix too long?

**Comment by fengmk2** [comment]
How about define a binary protocol?

```
  1 byte | N bytes |
| type | content |
```

type maybe

- `1`: Buffer
- `2`: String
- `3`: Date
- and so on

**Comment by gxcsoccer** [comment]
加个 magic ?

**Comment by shaoshuai0102** [comment]
> 加个 magic ?

What do u mean?

**Comment by fengmk2** [comment]
@gxcsoccer 嗯，但是在这个场景下的数据肯定是这个 magic header 的，好像也没必要加。

**Comment by shaoshuai0102** [comment]
> How about define a binary protocol?

Yeh, binary magic bit is more efficient, thus `valid()` can return result in absence of `buf.toString()`

But not with that protocol, the design of `serialize-json` is based on string recogination. Maybe magic prefix buf is more likely to be adopted because it brings little challenge to current design.

**Comment by gxcsoccer** [comment]
```js 
0               2               4                               8
+-------+-------+-------+-------+-------------------------------+
|      magic    | packet length |           content             |
+-------+---------------+-------+                               +
|                                                               |
+---------------------------------------------------------------+
```

**Comment by gxcsoccer** [comment]
@fengmk2 对哈，`serialize-json` 外边还包了一层 `cluster-client` 的协议

**Comment by gxcsoccer** [comment]
@shaoshuai0102 `serialize-json` 算是应用层协议（类似 hessian）， `cluster-client` 协议类似 tr，所以你说的场景，需要在 serialize-json 外边再包一层

**Comment by shaoshuai0102** [comment]
Fair enough! I will implement my own magic header in plugin.
