### ISSUE TITLE
文件上传在stream模式的情况下时，获取到的stream的数据丢失？

### ISSUE THREAD

**Issue by oneWalker** [eggjs/egg#4201]
## What happens?
[最近在利用eggjs进行后端开发，结合官方参考文档](https://eggjs.org/zh-cn/basics/controller.html#%E8%8E%B7%E5%8F%96%E4%B8%8A%E4%BC%A0%E7%9A%84%E6%96%87%E4%BB%B6)进行一系列文件上传的操作时发现；
通过stream模式上传文件时：
       在本地开发运行时，正常运行；
       放置在服务器，单个stream的文件大小会一定情况下小于stream的正常大小；
例如：我上传一个51.2kb的文件，得到的大小在服务器可能只有11.2kb。

**Comment by atian25** [comment]
检查你的 nginx 配置

**Comment by Huaxink** [comment]
multipart配置里，是不是没加文件格式白名单？

**Comment by atian25** [comment]
不加白名单就直接报错了。

如果你不熟悉 Stream 的话，直接用 File 模式吧。

**Comment by Huaxink** [comment]
哦， 对，不加白名单直接报400错，我之前遇到过，测试的时候，local模式正常，prod模式丢失数据的情况，domain加白名单就好了

**Comment by atian25** [comment]
或看下报错， 是不是有 multipart 和 nginx 的大小配置限制了。

看下新文档吧：https://eggjs.github.io/zh/guide/upload.html

**Comment by oneWalker** [comment]
K8s里面设置的代理缓存大小是200mb，我设置的单个文件大小是在100mb，照理来说应该不会存在这个问题。暂时还不清楚，先全部改成file了。

**Comment by atian25** [comment]
这个没问题了？

**Comment by oneWalker** [comment]
> 这个没问题了？
还是没有解决，在排查到问题之前还是先改用其他方式吧。

**Comment by atian25** [comment]
意思是什么都没配置都没改，改为 file 就没问题？

**Comment by atian25** [comment]
提供下最小可复现的代码库吧

**Comment by oneWalker** [comment]
> 意思是什么都没配置都没改，改为 file 就没问题？

是的，用file模式就没有问题。而且我问了同事，说egg upload会出现这个问题；
```js
'use strict';

const Controller = require('egg').Controller;
const path =require('path');
const sendToWormhole = require('stream-wormhole');
const prepath='ysxbdms';
//filepath=ysxbdms/projects/record
class UploadController extends Controller {
    constructor(ctx)
    {
        super(ctx);
       //腾讯cos存储相关方法
        this.cos=ctx.utility.cos;
    }

    // //stream模式下进行多张上传，因为数据丢失问题放弃
    async upload()
    {
        const {ctx} = this;
        let data=await ctx.params;
        const filepath=data.prepath?data.prepath:'';//定义传入图片的目录
        const parts = ctx.multipart();
        let part,results=[];
        while ((part = await parts()) != null) {
            if (part.length) {
                ctx.logger.info('arrays are busboy fields');
            } else {
                if (!part.filename) {
                    return;
                }
                let filename=await ctx.helper.MD5encode(part.filename+String(Date.now()));
                let ext = path.extname(part.filename).toLocaleLowerCase();
                filename=filename+ext;
                const pathSrc=prepath+filepath+filename;
                let result=await this.cos.stream_uploader(part,pathSrc);
                console.log(result);
                if (result.statusCode==200) {
                    results.push({
                        filename:filename,
                        mime:part.mime,
                        pathsrc:pathSrc,
                        url:result.Location?result.Location:null,
                    });
                }
                else{
                    ctx.body=await ctx.helper.error(String(result),result.msg?result.msg:"上传失败",result.code?result.code:500);
                    return;
                }
            }
        }
        ctx.body=await ctx.helper.success(results);
    }

    // //stream模式下进行单张上传
    async uploadOne()
    {
        const { ctx } = this;
        let data=await ctx.params;
        const filepath=data.prepath?data.prepath:'';
       //stream获取到的大小不对
        const stream = await ctx.getFileStream();
        const filename = await ctx.helper.MD5encode(stream.filename+String(Date.now())) + path.extname(stream.filename).toLocaleLowerCase();
        const pathSrc= prepath+filepath+filename;
        let res;
        let result=await this.cos.stream_uploader(stream,pathSrc);
        //console.log(result);
        if(result.statusCode==200)
        {
            res= await ctx.helper.success(
                {
                    filename:filename,
                    mime:stream.mime,
                    pathsrc:pathSrc,
                    url:result.Location?result.Location:null,
                }
            );
        }
        else{
            res=await ctx.helper.error(String(result),result.msg?result.msg:"上传失败",result.code?result.code:500);
        }
        ctx.body= res;
    }
}

module.exports = UploadController;
```

**Comment by atian25** [comment]
那就直接用 file 的吧，如果不熟悉 stream 用法的话。

**Comment by oneWalker** [comment]
> 那就直接用 file 的吧，如果不熟悉 stream 用法的话。

大哥 这不是不熟悉stream模式的问题。我怀疑这是一个系统性的问题，因为是获取到的整个stream的流大小就小于等于文件原始大小，而不是流在分片过程中造成的丢失。

**Comment by hyj1991** [comment]
本地开发下不管上传多大的图片都是 OK 的，但是部署到服务器上就出问题了？

**Comment by oneWalker** [comment]
> 本地开发下不管上传多大的图片都是 OK 的，但是部署到服务器上就出问题了？

是的。在本地没有任何问题，但是在服务器的话取决于网络状况。一般是小于等于文件大小

**Comment by hyj1991** [comment]
> > 本地开发下不管上传多大的图片都是 OK 的，但是部署到服务器上就出问题了？
> 
> 是的。在本地没有任何问题，但是在服务器的话取决于网络状况。一般是小于等于文件大小

一个办法是你尝试下在服务器部署的时候不走 nginx 转发，直接走 egg server 的端口上传看下，我感觉看描述比较像是 nginx 转发的时候出了什么问题

**Comment by oneWalker** [comment]
> > > 本地开发下不管上传多大的图片都是 OK 的，但是部署到服务器上就出问题了？
> > 
> > 
> > 是的。在本地没有任何问题，但是在服务器的话取决于网络状况。一般是小于等于文件大小
> 
> 一个办法是你尝试下在服务器部署的时候不走 nginx 转发，直接走 egg server 的端口上传看下，我感觉看描述比较像是 nginx 转发的时候出了什么问题
已经测试过了，不是nginx转发的问题。

**Comment by pxim** [comment]
> > 意思是什么都没配置都没改，改为 file 就没问题？
> 
> 是的，用file模式就没有问题。而且我问了同事，说egg upload会出现这个问题以下是相关代码，一个完整的controller；
> 
> ```js
> 'use strict';
> 
> const Controller = require('egg').Controller;
> const path =require('path');
> const sendToWormhole = require('stream-wormhole');
> class UploadController extends Controller {
>     constructor(ctx)
>     {
>         super(ctx);
>        //腾讯cos存储相关方法
>         this.cos=ctx.utility.cos;
>     }
> 
>     // //stream模式下进行多张上传，因为数据丢失问题放弃
>     async upload()
>     {
>         const {ctx} = this;
>         let data=await ctx.params;
>         const filepath=data.prepath?data.prepath:'';//定义传入图片的目录
>         const parts = ctx.multipart();
>         let part,results=[];
>         while ((part = await parts()) != null) {
>             if (part.length) {
>                 ctx.logger.info('arrays are busboy fields');
>             } else {
>                 if (!part.filename) {
>                     return;
>                 }
>                 let filename=await ctx.helper.MD5encode(part.filename+String(Date.now()));
>                 let ext = path.extname(part.filename).toLocaleLowerCase();
>                 filename=filename+ext;
>                 const pathSrc=prepath+filepath+filename;
>                 let result=await this.cos.stream_uploader(part,pathSrc);
>                 console.log(result);
>                 if (result.statusCode==200) {
>                     results.push({
>                         filename:filename,
>                         mime:part.mime,
>                         pathsrc:pathSrc,
>                         url:result.Location?result.Location:null,
>                     });
>                 }
>                 else{
>                     ctx.body=await ctx.helper.error(String(result),result.msg?result.msg:"上传失败",result.code?result.code:500);
>                     return;
>                 }
>             }
>         }
>         ctx.body=await ctx.helper.success(results);
>     }
> 
>     // //stream模式下进行单张上传
>     async uploadOne()
>     {
>         const { ctx } = this;
>         let data=await ctx.params;
>         const filepath=data.prepath?data.prepath:'';
>        //stream获取到的大小不对
>         const stream = await ctx.getFileStream();
>         const filename = await ctx.helper.MD5encode(stream.filename+String(Date.now())) + path.extname(stream.filename).toLocaleLowerCase();
>         const pathSrc= prepath+filepath+filename;
>         let res;
>         let result=await this.cos.stream_uploader(stream,pathSrc);
>         //console.log(result);
>         if(result.statusCode==200)
>         {
>             res= await ctx.helper.success(
>                 {
>                     filename:filename,
>                     mime:stream.mime,
>                     pathsrc:pathSrc,
>                     url:result.Location?result.Location:null,
>                 }
>             );
>         }
>         else{
>             res=await ctx.helper.error(String(result),result.msg?result.msg:"上传失败",result.code?result.code:500);
>         }
>         ctx.body= res;
>     }
> }
> 
> module.exports = UploadController;
> ```

请问 这个file模式，怎么获取文件的size，有代码可以看一下么

**Comment by atian25** [comment]
别那么玻璃心，觉得问题没解决就再 reopen 呗，多大的事呢。
有问题就提供最小可复现仓库我们直接跑下就知道了，按过去答疑的经验，贴代码和真实本地运行的代码往往有差异。

**Comment by atian25** [comment]
@pxim 直接 await fs.stat() 下对应的文件。

**Comment by YOOYY** [comment]
我也出现了这种情况,最后发现是在文件流还没有写入完成的时候就提前在controller里返回了值造成的

**Comment by fengmk2** [comment]
> 我也出现了这种情况,最后发现是在文件流还没有写入完成的时候就提前在controller里返回了值造成的

感谢经验分享，stream 模式真的很难，建议后续看到 issue 的开发者尽量走本地文件模式，先将文件写入磁盘，然后再操作，现代磁盘已经足够快。
