### ISSUE TITLE
egg中同一个项目，如何实现多个域名互不影响

### ISSUE THREAD

**Issue by oliveying** [eggjs/egg#4202]
egg项目，想实现多个二级域名的切换，并且二级域名后的子路由各不影响，需要使用什么方式做

**Comment by atian25** [comment]
nginx

**Comment by oliveying** [comment]
但是这是同一个项目里不同的域名

**Comment by atian25** [comment]
你用 nginx 的 location 映射到不同的 egg  router path 即可

**Comment by oliveying** [comment]
> 你用 nginx 的 location 映射到不同的 egg router path 即可
egg里的router里不能直接判断吗

**Comment by atian25** [comment]
一般是 nginx 做这事的。

如果实在需要在 egg，自己写个 Middleware 放在最前面，根据 host headers 去修改 href 和 url 啥的，可以看下 egg-router 的逻辑。

**Comment by oliveying** [comment]
> 一般是 nginx 做这事的。
> 
> 如果实在需要在 egg，自己写个 Middleware 放在最前面，根据 host headers 去修改 href 和 url 啥的，可以看下 egg-router 的逻辑。



> 一般是 nginx 做这事的。
> 
> 如果实在需要在 egg，自己写个 Middleware 放在最前面，根据 host headers 去修改 href 和 url 啥的，可以看下 egg-router 的逻辑。

非常感谢，我试试

**Comment by oliveying** [comment]
写好之后发现router中的路由会被缓存，在router怎么清除缓存

**Comment by atian25** [comment]
说明代码写的有问题
