### ISSUE TITLE
项目的日志切割没有能配置切割后文件存储的目录

### ISSUE THREAD

**Issue by junieHF** [eggjs/egg#4206]
## What happens?

项目在centos 系统环境中，生产模式启动，项目的常规日志是在当前项目的更路径下（/var/www/项目目录/logs）
日志按日期自动切割，切割后的日志并没有存在项目的logs目录下，而是存在的系统根路径下的logs目录中，和常规的日志没有放在一起，这样很不方便维护，这个切割后日志中存储路径怎么配置

## 相关环境信息
- **操作系统**：centos
- **Node 版本**：11
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
dup: https://github.com/eggjs/egg/issues/4199
