### ISSUE TITLE
Metrics机制提供

### ISSUE THREAD

**Issue by luicfer** [eggjs/egg#421]
参考spring boot
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html

1. 统计信息配合详细日志能更好的调错
2. 统计信息上做应用监控比写具体日志再清洗处理转化要消耗小的多
3. 提供这么一个机制后，用户能收集自己想要的数据

暂时想法做成类似egg-schedule的插件。
求讨论下这个东西的必要性

**Comment by popomore** [comment]
用 http://alinode.alibaba-inc.com/ ？

**Comment by luicfer** [comment]
这和alinode不是一个完全一个类型的东西。
只是系统信息的话可以通过alinode来解决。
但是如egg-redis get几次 set几次 qps
egg-schedule哪几个job跑了几次，平均耗时多少等都可以通过这种机制透出出来。
各个插件开发者，用户自己的app有需求都可以做一些这种数据的透出。
数据出来后是用来做监控，还是展示图表都可以自行决定。
这种比较个性化的数据是不可能都交给alinode解决的。

**Comment by popomore** [comment]
https://github.com/eggjs/egg/issues/235

感觉跟这个有点关系，但这个范围太广了。

**Comment by luicfer** [comment]
应该说日志系统是系统行为的一种记录
Metrics这个就是系统当前状态的一个快照
虽然行为记录的够详细的话，能推到任意时刻的状态，但是消耗就比较大。
类比的话应该是  redis 恢复机制里面 snapshot 和 AOF 差别

**Comment by atian25** [comment]
如果做的话, 是不是可以包含掉 https://github.com/eggjs/egg-instrument 的功能了?

**Comment by luicfer** [comment]
@atian25 看使用方法，应该是不包含。这个目标不是输出每一次的结果。而是这两个点执行100次后。avg消耗的时间，总消耗的时间这种

**Comment by jtyjty99999** [comment]
感觉是定期生成系统状态的快照

**Comment by luicfer** [comment]
@jtyjty99999 有点像吧。不过是实时的快照，请求看就给，过程中avg什么的计算还是一直在进行的

**Comment by huangyanxiong01** [comment]
```
而是这两个点执行100次后
```

这个100次是自己可以配置的吗？

**Comment by luicfer** [comment]
应该是每一次后在内存中都会更新均值 总和等。当你请求查看的时候，就把你当前状态拿出来。
主要统计值能在不断迭代计算后保留最后一个值然后给你，怎么迭代应该会给使用者控制的余地，可以做出类似 cpu指标 load1/load5这种。
主要其实就是你打了log也不可能一眼通过1G日志判断现在egg-redis是一个什么状态。
日志采集再接了spark之类处理分析后就另说=。=

**Comment by ImHype** [comment]
@luicfer 
我理解，你关注的是应用或是业务级监控，而非系统性能监控吧。alinode 属于后者

**Comment by fsiaonma** [comment]
mark 一下
