### ISSUE TITLE
egg prod环境不能自定义日志吗

### ISSUE THREAD

**Issue by jasontsai1990** [eggjs/egg#4212]
// config/config.${env}.js
const path = require('path');

module.exports = appInfo => {
  return {
    customLogger: {
      xxLogger: {
        file: path.join(appInfo.root, 'logs/xx.log'),
      },
    },
  };
};

ctx.getLogger('xxLogger').info('xxx')

用该方法自定义日志，在 local环境，unittest环境都能正确写入日志，唯独在prod环境怎么尝试都不能写入，想问框架不支持。

感谢答疑。

**Comment by atian25** [comment]
提供最小可复现方式，以及如何判断没有写入成功？

**Comment by jasontsai1990** [comment]
问题已解决，appInfo.root 生产环境的目录是/home/admin/logs，跟其他环境有区别
