### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lvgg3271** [eggjs/egg#4215]
logs/egg-agent.log中的log有单词拼写错误: Recieved 
`020-03-09 17:50:42,934 INFO 3168 [egg-watcher] Recieved a change event from eventSource: `

**Comment by atian25** [comment]
来个 PR~

在 egg-watcher 那里

**Comment by fireairforce** [comment]
https://github.com/eggjs/egg-watcher/pull/13 @atian25 
done了

**Comment by fireairforce** [comment]
https://github.com/eggjs/egg/pull/4234 egg主库里面也有个，一起修了
