### ISSUE TITLE
谷歌浏览器无法使用中间件获取cookies,但是火狐可以

### ISSUE THREAD

**Issue by ElementEvent** [eggjs/egg#4216]
`javascript`
config.default.js 中
 config.security = {
    csrf: {
      enable: false
    },
    domainWhiteList: ['http://localhost:3000']
  };

  config.cors = {
    origin: 'http://localhost:3000',
    credentials: true,
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS'
  };

plugin.js中
cors: {
		enable: true,
		package: 'egg-cors',
	}

火狐的请求头Cookie的信息, 但是谷歌却没有, 在中间件
`javascript`
module.exports = options =>{
	return async function adminauth(ctx,next){
		console.log(ctx.session)
		if(ctx.session.openId){
			await next()
		}else{
			ctx.body={data:'没有登录'}
		}
	}
}
火狐浏览器的ctx.session 可以获取到数据;
谷歌浏览器的ctx.session 为 null;
请问这个问题是什么原因呢

**Comment by atian25** [comment]
搜下 cookie samesite

**Comment by ElementEvent** [comment]
> 搜下 cookie samesite，看看是不是这个的问题

搜了一下,大概是这个原因, 但是我按照搜索的博客上面的操作, 还是不行, 不知道是不是我设置得有问题

**Comment by atian25** [comment]
https://github.com/eggjs/egg-cookies/pull/18/files#diff-b52768974e6bc0faccb7d4b75b162c99L35

**Comment by ElementEvent** [comment]
> https://github.com/eggjs/egg-cookies/pull/18/files#diff-b52768974e6bc0faccb7d4b75b162c99L35

大神，我找到问题了，config.default.js中 不能写localhost， 得写精确ip地址就好

**Comment by lizhongzhen11** [comment]
擦，同样的问题，困扰了我接近三小时，我就说怎么一直拿不到 `csrf` 值呢
