### ISSUE TITLE
egg-cors开发和生产差异

### ISSUE THREAD

**Issue by this-spring** [eggjs/egg#4219]
## What happens?
我用egg-cors中间件开发时，设置了跨域，在开发环境response的header能正确返回Access-Control-Allow-Origin: *, 但是我按照官网tar -zcvf ./release.tgz .  打包后，部署时候却没有返回：Access-Control-Allow-Origin这个

## 最小可复现仓库
代码不上传了，我把配置给出来

### plugin.ts

```
import { EggPlugin } from 'egg';

const plugin: EggPlugin = {
  cors: {
    enable: true,
    package: 'egg-cors',
  },
};
export default plugin;
```

### config.default.ts

```
import { EggAppConfig, EggAppInfo, PowerPartial } from 'egg';

export default (appInfo: EggAppInfo) => {
  const config = {} as PowerPartial<EggAppConfig>;

  // override config from framework / plugin
  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_1583908912130_7305';

  // add your egg config in here
  config.middleware = [ ];
  config.cors = {
    origin: '*',
  };

  config.security = {
    csrf: {
      enable: false,
    },
  };

  config.bodyParser = {
    enable: true,
    jsonLimit: '10mb',
    formLimit: '10mb',
  };

  // fileExtensions解除文件拓展，否则前端通过upload上传不带后缀的文件名上传不上来
  config.multipart = {
    mode: 'file',
    fileExtensions: [ '' ],
  };

  config.cluster = {
    listen: {
      port: 3000,
    },
  };

  // add your special config in here
  const bizConfig = {
    sourceUrl: `https://github.com/eggjs/examples/tree/master/${appInfo.name}`,
  };

  // the return config will combines to EggAppConfig
  return {
    ...config,
    ...bizConfig,
  };
};
```

### package.json

```
  "dependencies": {
    "ali-oss": "^6.5.1",
    "egg": "^2.6.1",
    "egg-cors": "^2.2.3",
    "egg-scripts": "^2.6.0"
  },
```
这个配置在开发环境可以，build之后会出问题。

## 相关环境信息
- **操作系统**：Mac OS 10.14.6
- **Node 版本**：v8.12.0
- **Egg 版本**："^2.6.1"

**Comment by atian25** [comment]
egg-cors 源码一共就几行，可以看下，没有生产和开发的区别。

1. 看你的 run 配置里面是否合并成功，插件也开启了
2. ssh 到你的机器上，curl 看看 headers 是否 正确
3. 检查你服务器的前置服务，如 nginx 啥的是不是拦截了

**Comment by this-spring** [comment]
npm run dev是可以正常开发，npm run start后就不可以了，我怀疑是执行npm run start的时候没有把egg-cros打进去，但是不是不知道为什么没有打进去

**Comment by this-spring** [comment]
> egg-cors 源码一共就几行，可以看下，没有生产和开发的区别。
> 
> 1. 看你的 run 配置里面是否合并成功，插件也开启了
> 2. ssh 到你的机器上，curl 看看 headers 是否 正确
> 3. 检查你服务器的前置服务，如 nginx 啥的是不是拦截了

npm run dev是可以正常开发，npm run start后就不可以了，我怀疑是执行npm run start的时候没有把egg-cros打进去，但是不是不知道为什么没有打进去

**Comment by atian25** [comment]
你是 ts 的，没有 tsc 再 start 的原因吧

**Comment by 1312543912** [comment]
> 你是 ts 的，没有 tsc 再 start 的原因吧

感谢天猪大佬，确实是这个原因，首次用🥚有点生疏，不过egg的ts的文档没有提到这个命令😭，建议补充一下。

**Comment by this-spring** [comment]
> 你是 ts 的，没有 tsc 再 start 的原因吧

感谢天猪大佬，确实是这个原因，首次用🥚有点生疏，不过egg的ts的文档没有提到这个命令😭，官网建议补充一下。

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/76674225-e4480f80-65e7-11ea-97f7-ef02336b9fd2.png)
