### ISSUE TITLE
How to get ctx.params and ctx.routerPath before next() in global middleware?

### ISSUE THREAD

**Issue by axolo** [eggjs/egg#4220]
## What happens?

`ctx.params` and `ctx.routerPath` is `undefined` in global middleware before `next()`.

## app/middleware/acl.js

```js
module.exports = () => {
  return async (ctx, next) => {
    const { params, routerPath } = ctx;
    console.log(params, routerPath); // undefined
    await next();
    const { params, routerPath } = ctx;
    console.log(params, routerPath); // work good
  };
};
```

## ENV
- **OS**：Windows 10 x64 version 1909
- **Node**：v13.5.0
- **Egg**：2.26.0

**Comment by atian25** [comment]
read https://github.com/eggjs/egg/issues/4112#issuecomment-568385218
