### ISSUE TITLE
Should egg-bin and egg-script support multiple .env files by dotenv?

### ISSUE THREAD

**Issue by axolo** [eggjs/egg#4223]
## What happens?

only support single .env file in config.default.js by `require('dotenv').config()`.

need support multiple .env and auto merge.

as: https://github.com/motdotla/dotenv#should-i-have-multiple-env-files

## Code

```js
// config/config.default.js
const env = require('dotenv').config();
console.log(env); // .env only
```

## ENV
- **OS**：Windows 10
- **Node**：13.5.0
- **Egg**：2.26.0

#3958

**Comment by atian25** [comment]
you could write a plugin to hook lifecycle

**Comment by axolo** [comment]
egg built-in config is nice enough. env config can auto merge to default config.
