### ISSUE TITLE
egg的最新文档网站的仓库是哪个？

### ISSUE THREAD

**Issue by shinji3887** [eggjs/egg#4224]
想在内网搭建一个文档网站，方便开发查阅
eggjs.github.io拉下来看了下，好像不是最新的

**Comment by atian25** [comment]
eggjs.github.io 是新的，但还没上线，源码在 eggjs/eggjs.github.io。

现有 eggjs.org 的就在 eggjs/egg 的 docs 目录。

**Comment by shinji3887** [comment]
明白了，谢谢。
感觉新版网站内容好像比老的少了

**Comment by atian25** [comment]
所以才没上线。新的主要是针对应用开发者进行重写了，插件开发者等高阶内容还没重写。

**Comment by shinji3887** [comment]
> 所以才没上线。新的主要是针对应用开发者进行重写了，插件开发者等高阶内容还没重写。

谢谢回复。顺便问下，docker的单进程模型还有规划做吗？

**Comment by atian25** [comment]
单进程其实现在已经有了，只是没有配套的 cli。目前在内部还在实践中。

在 3.0 里面会开出来，应该在年中的时候。

**Comment by shinji3887** [comment]
> 单进程其实现在已经有了，只是没有配套的 cli。目前在内部还在实践中。
> 
> 在 3.0 里面会开出来，应该在年中的时候。

太好了，还有健康监测端口也考虑一下哈
都是k8中不可缺少的。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-healthy

**Comment by shinji3887** [comment]
> eggjs.github.io 是新的，但还没上线，源码在 eggjs/eggjs.github.io。
> 
> 现有 eggjs.org 的就在 eggjs/egg 的 docs 目录。

docs里面的文档是hexo写的吗？有没有具体如何启动的说明
试了下hexo server好像不行

**Comment by atian25** [comment]
https://github.com/eggjs/egg/blob/master/package.json#L102

egg-doctool，继承 hexo 的
