### ISSUE TITLE
[Feature Request] eggjs中增加健康监测端口

### ISSUE THREAD

**Issue by shinji3887** [eggjs/egg#4225]
## Background
在云原生环境下，k8内纳管的应用均应该提供健康监测端口，以供readiness和liveness探针进行探活，保障应用状态的准确性，使得k8更好的去管理pod应用的生命周期。

## Proposal
在eggjs中添加健康监测端点，类似spring boot中的actuator设计
```bash
/actuator
/actuator/health
/actuator/health/{component}
/actuator/health/{component}/{instance}
/actuator/info
```
可以提供健康探活及暴露各类运行时指标的能力（各类运行时的metrics）

## Additional context

**Comment by atian25** [comment]
https://github.com/eggjs/egg-healthy
