### ISSUE TITLE
type:bug;scope:[plugin:egg-socket.io]

### ISSUE THREAD

**Issue by zhenmang** [eggjs/egg#4226]
按照官方示例写了个demo，收发消息正常，但connection.js和auth.js的内部函数，完全并没有触发，感觉中间件加载了，但并未执行。
-**操作系统**：macOS Mojave 10.14.6 (18G3020)
- **Node Version**: v12.15.0
- **Egg Version**: 2.26.0
- **Plugin Name**:egg-socket.io
- **Plugin Version**:4.1.6
- **Platform**:macOS
- **Mini Showcase Repository**: https://github.com/zhenmang/egg-socket.git

**Comment by ngot** [comment]
你的一中间件没有配置，按照文档配一下 https://github.com/eggjs/egg-socket.io#middleware

**Comment by zhenmang** [comment]
您好，刚更新了代码，辛苦看下， 本地起的服务，socket请求时，没有触发connection.js
