### ISSUE TITLE
使用readdirSync读取目录的问题

### ISSUE THREAD

**Issue by schizobulia** [eggjs/egg#4228]
```javascript
let arr = await fs.readdirSync(this.config.baseDir + '/app/public/', { withFileTypes: true });
arr.map(function (ele) {
    console.log(ele); //此处获取到的本应是对象,实际返回的是字符串
})
```
[node关于withFileTypes的文档](http://nodejs.cn/api/fs.html#fs_fs_readdirsync_path_options)

## 相关环境信息
- **系统：ubuntu14.04**：
- **Node 版本：v12.13.1**：
- **Egg 版本：2.15.1**：

**Comment by popomore** [comment]
这个和 egg 没关系吧

**Comment by schizobulia** [comment]
- 在 ubuntu14.04 下 egg 中 使用 withFileTypes 返回的结果不包含 fs.Dirent 对象。    (win10下没问题  node版本都大于v10.10.0)

- 在ubuntu14.04 下创建单个文件去执行 fs.readdirSync  返回的结果包含 fs.Dirent 对象
