### ISSUE TITLE
how to access helper in egg-sequelize model file

### ISSUE THREAD

**Issue by alphatr** [eggjs/egg#423]
* **Node Version**: v6.9.5
* **Egg Version**: 0.11.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 1.0.0
* **Platform**:

如题，在使用 `egg-sequelize` 插件中，有如下 Model 文件定义

```javascript
module.exports = function (sequelize) {
  return sequelize.define('test', {
    name: {
      type: sequelize.Sequelize.STRING(30),
    }
  }, {
    classMethods: {
      someMethod() {
       // access helper
      }
    }
  })
}
```

但是在自定义的 classMethods 里面调不到 helper 或者 app，除了 require 进来外有其他方式么？如果没有，后期会添加么？

**Comment by atian25** [comment]
里面没有注入 ctx ?
可以考虑把 app 作为第二个参数 inject 进来

发自我的 iPhone

**Comment by alphatr** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L192

file_loader 里面现在只支持 inject 一个变量，可以考虑修改成 `exports(...inject, app)` 方式，支持插件调用传入多个参数，并且默认也将 app 传入？

**Comment by atian25** [comment]
helper 是在 ctx 上的吧

**Comment by popomore** [comment]
这个是设计问题，当时讨论的时候就不给 app。我不太建议在 model 定义方法，可以在 service 封装。

**Comment by atian25** [comment]
一个题外话，当然不统一传 app，觉得有点别扭。现在想想，其实可以解决的解构就完了。

```js
module.exports = function ({ sequelize }) {
  return sequelize.define('test', {
    name: {
      type: sequelize.Sequelize.STRING(30),
    }
  }, {
    classMethods: {
      someMethod() {
       // access helper
      }
    }
  })
}
```

**Comment by huacnlee** [comment]
你不应该在 Model 里面用 ctx 的东西，更别说 Helper。

Model 应当保持逻辑独立，单一，和请求无关

----

app 将会有，现在的实现还在改进

**Comment by huacnlee** [comment]
https://github.com/eggjs/egg-sequelize/pull/4#issuecomment-281333318

**Comment by jtyjty99999** [comment]
个人感觉model是静态的，不应该引用ctx上的helper，建议还是在service层用吧

**Comment by alphatr** [comment]
同意 model 是静态的，不应该引入 context；之前 helper 可能更多的理解是类似 lodash 的和请求无关的工具函数；那这样的话，项目的工具函数就自己按需要扩展？

**Comment by atian25** [comment]
举个栗子? 譬如会在里面用工具函数处理怎么样的问题?

**Comment by alphatr** [comment]
@atian25  比较小的来说 hash,  camelcase 这样的工具函数处理入库的数据，大的 markdownToHtml 这样的入库或者出库进行处理数据

**Comment by huacnlee** [comment]
@alphatr 这类函数自己创建一个 app/lib 或 app/utils 目录，用 require 的方式使用。

**Comment by alphatr** [comment]
我可能更期望的方式是有 `extend/utils.js` 这样一个文件来供扩展，我在 model, service, controller 等通过 `app.utils.markdown` 这样来使用。

行，我先通过 require 来使用，谢谢各位的解答！

**Comment by popomore** [comment]
@alphatr 可以自己挂一下

```js
// app/extend/application.js
exports.utils. = require('../../lib/utils');
```

**Comment by atian25** [comment]
@alphatr
```js
  const direcotry = path.join(app.baseDir, 'app/util');
  app.loader.loadToApp(direcotry, 'util', {});
```

**Comment by atian25** [comment]
不过这里还要等 egg-sequelize 把 app 传递进去, 等 @huacnlee 改吧

**Comment by whlsxl** [comment]
@atian25 @popomore @huacnlee 感谢你们的回答！

我有个需求，是想把一些通用处理的函数放到一个特定的文件夹，比如`/app/lib`，直接挂在到`app`下。

如果用`app.loader.loadToApp(direcotry, 'util', {});`，理论上会把对象都挂载到`app.util`下，不过我没有成功，`loadExtend`也是同样的情况，不知道是不是使用方法有误。附最小复现[代码](https://github.com/whlsxl/egg-mock/tree/0516634ac43ba2423cf35b95484c9162d2fd9179)

不过以上两个函数不是我的确切需求。

用`exports.utils = require('../../lib/utils');`的方法挂载之后，虽然可以访问，也挂载到`app`下，但是不能注入`app`到`this`里（我把`app`当成挂载点，使用一些其他的挂载）。

最终我想达到的是，一个函数可以 load 文件夹下的所有的文件或者指定单个文件挂载到不限于`app`下，比如把`app/lib/defs.js`下的文件挂载到`app.defs`上，也可以把任何位置的文件，或文件夹挂载，并传递对象到文件，包括`contents`，`service`，`request`，`response`里。

**Comment by whlsxl** [comment]
应该在`app.js`中挂载，感谢！
