### ISSUE TITLE
linux服务器上npm run start报错

### ISSUE THREAD

**Issue by 305371179** [eggjs/egg#4231]
[guose@Mainxx app]$ npm run start --ignore-stderr

> rank@1.0.0 start /home/guose/app
> egg-scripts start --daemon --title=egg-server-rank

[egg-scripts] Starting egg application at /home/guose/app
[egg-scripts] Run node /home/guose/app/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-rank","baseDir":"/home/guose/app","framework":"/home/guose/app/node_modules/egg"} --title=egg-server-rank
[egg-scripts] Save log file to /home/guose/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] tail -n 100 /home/guose/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] 2020-03-24 20:38:20,616 ERROR 26576 [app_worker] server got error: bind EADDRINUSE 0.0.0.0:7888, code: EADDRINUSE
[egg-scripts] 2020-03-24 20:38:20,629 ERROR 26482 nodejs.AppWorkerDiedError: [master] app_worker#1:26576 died (code: 0, signal: null, suicide: false, state: dead), current workers: []
[egg-scripts]     at Master.onAppExit (/home/guose/app/node_modules/egg-cluster/lib/master.js:510:21)
[egg-scripts]     at Master.emit (events.js:198:13)
[egg-scripts]     at Messenger.sendToMaster (/home/guose/app/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/home/guose/app/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at EventEmitter.cluster.on (/home/guose/app/node_modules/egg-cluster/lib/master.js:353:22)
[egg-scripts]     at EventEmitter.emit (events.js:203:15)
[egg-scripts]     at ChildProcess.worker.process.once (internal/cluster/master.js:190:13)
[egg-scripts]     at Object.onceWrapper (events.js:286:20)
[egg-scripts]     at ChildProcess.emit (events.js:198:13)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[egg-scripts] name: "AppWorkerDiedError"
[egg-scripts] pid: 26482
[egg-scripts] hostname: Mainxx
[egg-scripts] 
[egg-scripts] 2020-03-24 20:38:20,630 ERROR 26482 [master] app_worker#1:26576 start fail, exiting with code:1
[egg-scripts] 2020-03-24 20:38:20,631 ERROR 26482 [master] exit with code:1
[egg-scripts] 2020-03-24 20:38:20,636 ERROR 26509 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
[egg-scripts] 2020-03-24 20:38:20,638 ERROR 26509 [agent_worker] exit with code:110
[egg-scripts] 
[egg-scripts] Start got error, see /home/guose/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rank@1.0.0 start: `egg-scripts start --daemon --title=egg-server-rank`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rank@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/guose/.npm/_logs/2020-03-24T12_38_21_721Z-debug.log

这个问题找不到方法解决。本地npm run dev和npm start都没问题的。

**Comment by atian25** [comment]
```bash
[app_worker] server got error: bind EADDRINUSE 0.0.0.0:7888, code: EADDRINUSE
```

**Comment by aaa123123999** [comment]
我也遇到了 大神解决了嘛

**Comment by rmlzy** [comment]
我遇到了同样的报错, 原因是路由映射到控制器的时候, 控制器的方法不存在:

```javascript
router.get(link + '/api/salesmanCenter/statement/demo', login, controller.api.salesmanCenter.statement.demo); // demo 方法不存在
```

**Comment by guozhenqianga** [comment]
我也遇到了 大神解决了嘛

**Comment by atian25** [comment]
> 我遇到了同样的报错, 原因是路由映射到控制器的时候, 控制器的方法不存在:
> 
> ```js
> router.get(link + '/api/salesmanCenter/statement/demo', login, controller.api.salesmanCenter.statement.demo); // demo 方法不存在
> ```

明显不是一个错，你这个肯定是文件名大小写问题。

有问题就看错误日志分析就完了
