### ISSUE TITLE
根据文档构建egg-ts出现bug

### ISSUE THREAD

**Issue by EasonQwQ** [eggjs/egg#4237]
## What happens?
根据文档安装egg-ts 出现bug
`
Error: EACCES: permission denied, open '/home/manage_material/.travis.yml'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/home/manage_material/node_modules/egg-ci/install.js:119:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/nunjucks/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-ci@1.14.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-ci@1.14.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
`

**Comment by EasonQwQ** [comment]
我的node -v： v10.16.0
npm -v : v6.9.0

**Comment by blackmatch** [comment]
提示没有权限，应该是你电脑环境的问题，修改一下目录权限吧。

**Comment by EasonQwQ** [comment]
> 提示没有权限，应该是你电脑环境的问题，修改一下目录权限吧。

我换了云服务器都出现这个问题。 用midway 也是报这个错。但是试了一下，不影响程序的运行

**Comment by blackmatch** [comment]
我看你这有2个问题：

1.权限问题，无法打开`.travis.yml`这个文件，这是持续集成相关的文件，运行的时候不会用到这个文件，所以不影响运行。你可以用`ls -lh`看看你目录和文件的权限，看你的账号是否有权限。

2.模块平台不兼容问题，建议把node_modules目录删掉重新安装试试。

**Comment by atian25** [comment]
这是 egg-ci 写入 travis 文件用的。

问题是你本机的权限问题，自行检查下。如果不需要就把它从 devdep 里面干掉。

跟 ts 还有 egg 没啥关系。

**Comment by haiifeng** [comment]
https://juejin.im/post/6894137042163204110/
我也遇到了一样得问题，总结了下，可以参考这个文字得问题二得解决方法。
