### ISSUE TITLE
DeprecationWarning: crypto.createDecipher is deprecated.

### ISSUE THREAD

**Issue by Chongsaid** [eggjs/egg#4240]
## 发生了 Node 错误提示 crypto.createDecipher is deprecated.
[DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
因为调用了 eggjs 的 session 写入了一个变量（变量是按照官方网站的正确写法写的），之后我拿取此变量，控制台就打印了这段信息
官方的 Node 已经弃用这个方法，而 eggjs 可能仍在使用（我只是看官网文档，不知道源码中是否使用了这个方法）。

**Comment by hyj1991** [comment]
上最小复现仓库

**Comment by Chongsaid** [comment]
如果 eggjs 源码中**使用**了 **crypto.createDecipher** 这个方法，就**一定会出现这个错误**的
因为项目中也仅使用了以下包：

"egg": "^2.26.0",
"egg-mysql": "^3.0.0",
"egg-scripts": "^2.13.0",
"egg-view": "^2.1.2",
"egg-view-nunjucks": "^2.2.0"

并且项目代码没有使用 **crypto.createDecipher** 这个方法
所以我才来这里提交这个 bug
因为 **Node v10.0.0** 已经弃用了它，如果 eggjs 真的使用了这个方法，请修改为  **crypto.createDecipheriv**

以上，如果没有我的提问没有价值，请关闭此回答

**Comment by hyj1991** [comment]
我本地试了下没有出现这个提示，你是执行了什么？

**Comment by Chongsaid** [comment]
你这么一提问，我看了看编辑器，才发现 vscode 没有**本地历史**的功能....我现在安装了相关插件了。
如果这几天我遇到了，就发给你，这样好吗？
谢谢你维护了 Egg.js，它真的很不错！

**Comment by hyj1991** [comment]
可以，那我先关闭这个 issue 了，如果你复现了这个现象，再打开在这里贴吧 :)

**Comment by Chongsaid** [comment]
我找到了引发异常的地方了.
应该是 Egg.js 所依赖的一个包：
包的 Github 地址是：[https://github.com/crypto-utils/keygrip](https://github.com/crypto-utils/keygrip)

组件为 **egg-cookies**，其中的 js 名称为 **keygrip**，而出现此异常的方法为 **encrypt** ，它**使用**了 **crypto.createDecipher**

**Comment by Chongsaid** [comment]
希望尽快修复它，因为这个方法被废弃了，而 egg-cookies 却仍在使用。

**Comment by Chongsaid** [comment]
看错了，不是 **encrypt** 而是 **decrypt** 方法，你使用检索查查  createDecipher 关键字就能快速定位了

**Comment by Chongsaid** [comment]
这个问题我刚修复，却出现了另外的错误：
**(node:12236) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.**

在同一个文件（**egg-cookies/lib/keygrip.js**）内的 **encrypt** 使用的是弃用的 **createCipher** 方法

当然跟 createDecipher 引发的错误一样，只需要改为新的API就行了

分别是 createCipheriv 以及 createDecipheriv，望修复

**Comment by dead-horse** [comment]
这个应该不影响正常的使用，后续会重构成新的方法，要看看如何更好的保持兼容性。

**Comment by Chongsaid** [comment]
我临时修改了 egg-cookies 的源码，等待更新。
另外再次感谢你们维护着 Egg.js ，非常感谢！

**Comment by atian25** [comment]
没必要改吧，你是启动不了？ egg-scripts 有个 ignore 的参数

**Comment by Chongsaid** [comment]
是 Egg.js 底层的 Cookie 组件，而 Cookie 又是跟浏览器打交道的，加解密是必须的，也不能关掉。
同样的，如果使用了加解密服务，如果 Node 版本是最新的，那么会触发这个错误。
关键是：即便是触发了这个错误，控制台也不会抛出异常，只是提示你这个方法已被弃用。

所以，高版本 Node 要使用 Egg 的 Cookie **加解密**服务，就必然需要改动了。
之后等待你们的更新。

以上

**Comment by atian25** [comment]
这不是  DeprecationWarning 么？仅仅是提示而已，不影响。无法推导出 `高版本 Node 要使用 Egg 的 Cookie 加解密服务，就必然需要改动了。`。

如果你的问题是因为这个 warning 导致无法启动，加下  egg-scripts 的那个参数即可

**Comment by hyj1991** [comment]
> 无法推导出 `高版本 Node 要使用 Egg 的 Cookie 加解密服务，就必然需要改动了。`。

一般来说 node.js 对 deprecated api 会经历以下三个阶段：

* Documentation-only
* Runtime
* End-of-Life

输出 warning 到控制台说明已经到第二个阶段了，后面就会被从 runtime 里面直接移除掉。

@Chongsaid 的意思应该是现在不 fix 掉这个 warning，等 14 什么的就会直接挂了（当然 deprecated api 也可能被上游评估后 revoke），不过目前确实没什么影响

**Comment by atian25** [comment]
如果已经移除了，DeprecationWarning 其实都已经看不到了，直接报错了，我们肯定是第一时间会修复的。我的意思是现在他没必要魔改 cookie 代码。

**Comment by Chongsaid** [comment]
没魔改，我只是把加解密方式换了而已。。
改动两行。因为我写了一个扫描参数的方法，如果不改动，都是莫名其妙的被自己写的安全扫描拦截
而参数的传递是基于 Cookie 的，希望理解，我真没四处改 Egg 源码，它已经很棒了

`注：改动后的 egg-cookie 安全性一致，但是不再被 安全扫描 拦截`

**Comment by leon776** [comment]
> 我临时修改了 egg-cookies 的源码，等待更新。
> 另外再次感谢你们维护着 Egg.js ，非常感谢！

我也改了，目前正常使用
![image](https://user-images.githubusercontent.com/5228834/83478800-5df5e800-a4c9-11ea-8343-62d1659c3078.png)

**Comment by FollowTrend** [comment]
> 这个问题我刚修复，却出现了另外的错误：
> **(node:12236) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.**
> 
> 在同一个文件（**egg-cookies/lib/keygrip.js**）内的 **encrypt** 使用的是弃用的 **createCipher** 方法
> 
> 当然跟 createDecipher 引发的错误一样，只需要改为新的API就行了
> 
> 分别是 createCipheriv 以及 createDecipheriv，望修复
你好，楼主能分享一下keygrip.js修改后的源码吗，我修改老是会报错

**Comment by FollowTrend** [comment]
> > 我临时修改了 egg-cookies 的源码，等待更新。
> > 另外再次感谢你们维护着 Egg.js ，非常感谢！
> 
> 遇到了同样的问题，目前也是改了egg-cookies源码，目前正常使用
> ![image](https://user-images.githubusercontent.com/5228834/83478800-5df5e800-a4c9-11ea-8343-62d1659c3078.png)

你好，兄弟能分享一下keygrip.js修改后的源码吗，我修改老是会报错

**Comment by hoythan** [comment]
建议用户手动修改,有一定概率会出现 Body 直接返回报错的问题,导致接口不按预期效果.
