### ISSUE TITLE
extend/helper.ts 在函数中使用 this.app 操作

### ISSUE THREAD

**Issue by bluescurry** [eggjs/egg#4241]
## What happens?

使用 ts 时，在extend/helper.ts的定义一个函数，函数中使用 `this.app`，会报错说 this 上不存在 app 属性，请问如何进行 ts 类型定义？

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
![image](https://user-images.githubusercontent.com/19237129/77984474-3ad17f80-7344-11ea-9458-e977813ddf5e.png)

## 相关环境信息
- **操作系统**：macOS 10.14.2
- **Node 版本**：10.14.0
- **Egg 版本**：2.26.0

**Comment by atian25** [comment]
TS 基础知识。

```js
export default {
  getConfigFileName(this: Application, env) {
  },
}
```

**Comment by bluescurry** [comment]
> TS 基础知识。
> 
> ```js
> export default {
>   getConfigFileName(this: Application, env) {
>   },
> }
> ```

确实是 TS 知识，献丑了，已解决

**Comment by atian25** [comment]
helper 的 this 是 Context，不是 Application，刚才写错了。

**Comment by bluescurry** [comment]
> helper 的 this 是 Context，不是 Application，刚才写错了。

this 的类型可以定义为 IHelper 吗

**Comment by atian25** [comment]
你打印看看，我记不清了，应该是 IHelper

**Comment by bluescurry** [comment]
> 你打印看看，我记不清了，应该是 IHelper

好的

**Comment by qiurenbo** [comment]
@atian25 Hi，为什么不考虑把 Helper 也像 Controller Service 一样封装，通过自定义继承让我能直接拿到 this 呢?

**Comment by atian25** [comment]
helper 没必要那么复杂吧，它的定位就是给模板渲染用的。

如果你需要的话，自己通过 app.loader.loadToContext 来加载自定义的 app/utils 目录到 app.utils 这样，自定义规则

**Comment by qiurenbo** [comment]
@atian25 模板渲染···怪不得用起来感觉怪怪的··我这边之间写个 HelperService 来把一些常用的逻辑放在里面，这样可以用到 Context。应该符合你们的设计初衷吧。

**Comment by atian25** [comment]
可以的，如果你这块比较多，那也可以独立出一个 app.utils 之类的规范的。

可以参考下
https://github.com/atian25/egg-showcase/pull/13

**Comment by qiurenbo** [comment]
@atian25 谢谢！

**Comment by atian25** [comment]
https://zhuanlan.zhihu.com/p/153322661
