### ISSUE TITLE
don't fork new work

### ISSUE THREAD

**Issue by vivilauge** [eggjs/egg#4244]
业务逻辑
前台发送数据，后台直接在服务端处理，处理完了一次性返回结果。

处理逻辑
接收到数据， 会在服务端开启多个线程处理业务（注：不是进程）

以下是相关work代码截图， 
<img width="807" alt="截屏2020-04-02 下午6 30 35" src="https://user-images.githubusercontent.com/16894834/78239241-0f02f500-7510-11ea-9847-60889c8e3c15.png">

以下是执行结果截图
<img width="1018" alt="截屏2020-04-02 下午6 32 18" src="https://user-images.githubusercontent.com/16894834/78239453-4b365580-7510-11ea-862b-cac35dd2c855.png">

如上： 第4个子线程开启， 并没有执行任务，直接退出了， 第5个线程，，，，还没开启。
提示：don't fork new work

**Comment by vivilauge** [comment]
不知道我的这样处理的思路正不正确， 或者有更优雅的方式？

**Comment by atian25** [comment]
- 直接退出要检查你的代码逻辑，有未捕获异常。
- 没有 refork 难道是你没用 egg-scripts 启动？
- 这种任务一般要丢到阿里云函数计算 fc 这样的服务去做，不要在 web 服务里面做。

**Comment by vivilauge** [comment]
> * 直接退出要检查你的代码逻辑，有未捕获异常。
> * 没有 refork 难道是你没用 egg-scripts 启动？
> * 这种任务一般要丢到阿里云函数计算 fc 这样的服务去做，不要在 web 服务里面做。

还在开发阶段， 用的run dev
就是把N个单独的工具呀， 重新写成一个web的集合，也就几个人用
确实代码不够严谨，我再检查检查

**Comment by atian25** [comment]
dev 的异常不会自动重启的，避免开发期错过隐患
