### ISSUE TITLE
流模式下文件大小获取有误

### ISSUE THREAD

**Issue by zhenmang** [eggjs/egg#4246]
## What happens?
前端上传文件，后端接收时，获取不到正确的文件大小值。

## Mini Showcase Repository(REQUIRED)
const stream = await ctx.getFileStream();
console.log(stream.length);
当文件很小，length值是准确的，当文件稍微大点，length值不正确，显示的会是一个固定的数字64556。
例如上传下图http://t8.baidu.com/it/u=1484500186,1503043093&fm=79&app=86&f=JPEG?w=1280&h=853

## Context
Node Version: v12.15.0
Egg Version:@2.26.0
Plugin Name:egg-multipart
Plugin Version:2.10.1
Platform:macOS Mojave

备注：希望可以有牛人真正解决此问题

**Comment by zhenmang** [comment]
自己解决了，建议官方暴漏个优雅的接口，因为这是个常规需求

**Comment by atian25** [comment]
不是不处理，而是没看到你具体的问题如何复现，请按规则提供最小可复现代码仓库。

另外，如果你都自己解决了，不如回复出来给其他后来人看看，而不是默默关闭。

**Comment by oneWalker** [comment]
> 不是不处理，而是没看到你具体的问题如何复现，请按规则提供最小可复现代码仓库。
> 
> 另外，如果你都自己解决了，不如回复出来给其他后来人看看，而不是默默关闭。

很明显就是换成file模式呗。我觉得他即使提供了，你应该还是会说你对stream不熟悉.........
