### ISSUE TITLE
Can't install via NPM - error with egg-ci

### ISSUE THREAD

**Issue by rodriguezartav** [eggjs/egg#4247]
## What happens?
I can't install via NPM , Node v12

npm ERR! Unexpected end of JSON input while parsing near '...gg-ci":"^1.1.0","esli'

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1. npm I egg --save 
2.

**Expected behavior**
1. Install 
2.

## Context
- **Node Version**: 12.x
- **Egg Version**: All ^ 2.16.x
- **Plugin Name**:
- **Plugin Version**:
- **Platform: MAc

**Comment by atian25** [comment]
it's not egg problem, check your npm, maybe you need to reinstall npm
