### ISSUE TITLE
【egg-multipart】stream回调中设置响应体无效

### ISSUE THREAD

**Issue by zhenmang** [eggjs/egg#4249]
## What happens?
前端上传图片，stream回调中，设置响应体是无效的。前端收到的总是404.
代码如下：
const stream = await ctx.getFileStream();
stream.on('end', function() {
   ctx.status = 200;
       ctx.body = {
          code: '0000',
          msg: '图片发送成功',
       };
})
备注：若将ctx.status和body设置在stream外，则会生效。

## 相关环境信息
Node Version: v12.15.0
Egg Version:@2.26.0
Plugin Name:egg-multipart
Plugin Version:2.10.1
Platform:macOS Mojave

**Comment by jh-pu** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_event_end

> The 'end' event will not be emitted unless the data is completely consumed.

stream都没有消费必然不会触发'end'，给你一个demo
``let result;
    let chunk;
    while (null !== (chunk = stream.read())) {
      result += chunk;
    }
    stream.on('end', () => {
      console.log('end here');
    });
    // operate result here
    ctx.status = 200;
    ctx.body = {
      result,
      code: '0000',
      msg: '图片发送成功',
    };

**Comment by atian25** [comment]
```js
const stream = await ctx.getFileStream();
ctx.body = xxx;
```

不就完了，你都 await 了，肯定是消费完了。
