### ISSUE TITLE
Application deployment best practice

### ISSUE THREAD

**Issue by shaoshuai0102** [eggjs/egg#425]
There're different ways of deploying an egg application. The deployment solutions vary in respect of our infrastructures. The best one is the approach best fitting it. 

Here is the procedure of our deployment:

1. Cut off traffic into servers of group A. 
2. Wait for several seconds, for ongoing requests processing.
3. Deploy servers of group A.
4. Let traffic back into servers of group A.
5. Cut off traffic into servers of group B.
6. Wait for several seconds, for ongoing requests processing.
7. Deploy servers of group B.
8. Let traffic back into servers of group B.
9. Done.

Surely you can divide your servers into more than two groups as you need(C, D..). The key point is not deploy all your servers at once to keep your application always online.(availability)

For asynchronous job processing(OLAP compared to OLTP), waiting for several seconds may be not enough time before finishing. If not handled correctly, there's a consistency loss. It is highly recommended to use some `mq` service. Here is the thing:

1. When you have a job to processing, dispatch it with `mq`.
2. One of servers receive the job and start to processing it.
3. Once it's done, report it to `mq`.
4. Once the server is shut down, restarting, or something worse happened, the `mq` will know it. Therefore `mq` could dispatch it to another server alive.

This is just one of all of different solutions, put yours here, others would benefit.

**Comment by dead-horse** [comment]
close for now, better to write a blog or article for this topic.
