### ISSUE TITLE
egg-static alias 选项不生效

### ISSUE THREAD

**Issue by cckowin** [eggjs/egg#4252]
```
mkdir test_egg
cd test_egg
npm init egg --type=simple
npm install
npm run dev
```
然后修改config.default.js
增加
```
  config.static = {
  	prefix: '/',
	alias: {
		'/test': 'test.html',
	},
  }
```
在public目录下新建一个文件test.html
内容为
```
hello
```
然后访问/test.html有内容为hello
访问/test没有内容为404

**Comment by 232650413** [comment]
`config.static = {
    dir: [
      { prefix: '/', dir: path.join(appInfo.baseDir, 'app/public/root_static') },
      { prefix: '/public/', dir: path.join(appInfo.baseDir, 'app/public') },
    ],
    dynamic: true,
    preload: false,
  };`

**Comment by atian25** [comment]
https://github.com/koajs/static-cache/blob/fcd89c3ac7937a185abebae0297069efefe25f9e/index.js#L41

这个地方有 bug，没有 preload 的时候，就无法 alias

**Comment by atian25** [comment]
https://github.com/koajs/static-cache/pull/84

**Comment by atian25** [comment]
@cckowin reinstall deps
