### ISSUE TITLE
Stream传输视频流的时候用某些路由地址会报错

### ISSUE THREAD

**Issue by lizeyue326** [eggjs/egg#4253]
## What happens?

在使用Stream传输视频流的时候,如果方法路由到"/video/admin"就返回不了视频流并且报错
"nodejs.ERR_STREAM_CANNOT_PIPEError: Cannot pipe, not readable"
如果把路由换成"/public/admin"虽然也会报错,但会返回视频流,并且功能正常 错误信息如下
"nodejs.TypeError: Converting circular structure to JSON"

我也是近期才学习的egg.js,还看不太懂源码,所以不知道是不是一个BUG
但总觉得好像有点问题,怎么会因为路由地址的定义而产生不同的结果呢?
耽误各位大佬时间麻烦帮忙看下是什么问题,感谢!

## Mini Showcase Repository(REQUIRED)

https://gitee.com/lizeyue/eggjs_video.git

## How To Reproduce

1.克隆仓库,dev运行
2.打开根目录的index.html查看

## Context
- **Node Version**:12.16.1
- **Egg Version**:2.15.1

**Comment by atian25** [comment]
建议视频放到 cdn 等地方去，不要放在服务器硬盘 or static 目录，尤其后者，会撑爆内存的。
