### ISSUE TITLE
Class constructor BaseContextClass cannot be invoked without 'new'

### ISSUE THREAD

**Issue by ghostxbh** [eggjs/egg#4254]
Class constructor BaseContextClass cannot be invoked without 'new'
告诉我加载需要new

**Comment by ghostxbh** [comment]
Thank you! 已经自己解决了，感谢🙏

**Comment by parkeeers** [comment]
> Thank you! 已经自己解决了，感谢🙏

啥原因啊...

**Comment by caoweiju** [comment]
不小心遇到了这个问题，原因是我把tsconfig.json里面的target修改了，从es2017 变成了es5，然后controller里面写的class都失败了，改成es5是因为我的工程其他的代码需要，只好换成了babel去处理。
