### ISSUE TITLE
使用egg-cors如何根据路由更改跨域白名单

### ISSUE THREAD

**Issue by PGYangel** [eggjs/egg#4258]
官方和网上的解答都是在配置中直接写死一套白名单。这样确实是可以跨域。但是这样有一个问题，就是所有路由都允许这些白名单进行访问。
目前我的系统是这样的：后端、管理后台、用户页面。后端使用egg搭建，设置跨域提供给管理后台和用户页面使用接口。如果使用配置里面的白名单设置，那么就会造成用户页面可以调用管理后台的删除修改的接口。而真正的需求是要用户页面只允许读取对外的接口，至于管理后台的接口不允许用户页面的域名进行访问。
目前没有搜索到相关的资料去根据路由使用对应白名单。所以我在配置完egg-cors后再自己写了一个中间件进行判断：

module.exports = (app, type = 0) => {
  return async function sysCors(ctx, next) {
    let whiteList = [];
    whiteList = whiteList.concat(app.config.sysWhiteList);
    if (type) {
      whiteList = whiteList.concat(app.config.webWhiteList);
    }
    if (ctx.header.origin && whiteList.length > 0) {
      const origin = ctx.header.origin;
      const corsHost = whiteList.find(val => val === origin);
      if (corsHost) {
        ctx.set('Access-Control-Allow-Origin', corsHost);
      } else {
        ctx.remove('Access-Control-Allow-Origin');
      }
    }
    ctx.set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, token');
    await next();
  };
};

然后在路由中使用：
const { router, controller } = app;
const sysCors = app.middleware.sysCors(app);
const sysCors2 = app.middleware.sysCors(app, 1);

router.post('/doc/add', sysCors, controller.doc.add);
router.get('/doc/getDetail/:id', sysCors2, controller.doc.getDetailForId);

这样/doc/add就只允许管理后台的域名访问，用户页面的域名就无法访问，而/doc/getDetail/:id就能在用户页面访问。

虽然这种方式可行，但是这等于第二次修改Access-Control-Allow-Origin。希望有更合理的解决方式。

**Comment by atian25** [comment]
1. 跨域只是浏览器的限制，不能用做权限限制，这点要注意。
2. 看下 cors 文档，origin 这个配置是可以为一个 function 的。

**Comment by PGYangel** [comment]
> 1. 跨域只是浏览器的限制，不能用做权限限制，这点要注意。
> 2. 看下 cors 文档，origin 这个配置是可以为一个 function 的。

**Comment by PGYangel** [comment]
> 1. 跨域只是浏览器的限制，不能用做权限限制，这点要注意。
> 2. 看下 cors 文档，origin 这个配置是可以为一个 function 的。

**Comment by PGYangel** [comment]
> 1. 跨域只是浏览器的限制，不能用做权限限制，这点要注意。
> 2. 看下 cors 文档，origin 这个配置是可以为一个 function 的。

没办法了，目前只能这样用中间件去过滤了。配置虽然是可以是一个function，但是不针对路由做function，他在中间件和路由之前执行，后续不会进行请求判断执行。

**Comment by atian25** [comment]
> 只允许管理后台的域名访问

一个 POSTMAN 就绕过了，你确定要这种方案么？

**Comment by PGYangel** [comment]
> > 只允许管理后台的域名访问
> 
> 一个 POSTMAN 就绕过了，你确定要这种方案么？
> 
> 你的需求根本不是 CORS 的应用场景，可以看下 egg-userrole 等这些。

管理后台允许访问的接口都有token进行验证，用户页面的接口是纯get数据，不会有token给用户存储。所以软件改header头去简单绕过这个还是能避免。好的，我抽空看下。
