### ISSUE TITLE
multipart如何分开单独限制文件上传大小

### ISSUE THREAD

**Issue by stoneWeb** [eggjs/egg#4259]
现在的方式都是统一配置
`  exports.multipart = {
    fileSize: '10mb',
    mode: 'stream',
  };`

如何实现不同的router限制不同的size?
尝试stream模式获取length不准，file模式下面file对象根本没有size属性。这个上传很多缺陷啊

**Comment by atian25** [comment]
`app.router.get('/xx', app.middleware.multipart({ ... }), controller.xx.xx)`

**Comment by stoneWeb** [comment]
@atian25 这种方式会出现另外一个错误：
the multipart request can't be consumed twice
config.default.js:
`  exports.multipart = {
    fileSize: '10mb',
    mode: 'stream',
  };`
router.js:
`router.post('/xx', middleware.multipart({ fileSize: '1mb', mode: 'stream' }), controller.xx.xx)`

**Comment by atian25** [comment]
你全局那个要配置  ignore 过滤掉对应的

**Comment by stoneWeb** [comment]
@atian25 建议你试一试

**Comment by atian25** [comment]
看了下源码，记错了， `app.middleware.multipart` 是 filemode 的处理。

https://github.com/eggjs/egg-multipart/blob/master/app/extend/context.js#L198

应该直接 `getFileStream({ limits })` 就好了。晚点我写个 demo 看看。

**Comment by atian25** [comment]
这里有 2 个问题：

1.  `limits` 的取值不支持 `1kb` 这样的配置，要修复下
2. limit 事件触发在 await 里面，监听却在下面，@hyj1991 在看怎么修复。
3. file mode 里面有单独处理了 limit

**Comment by atian25** [comment]
@stoneWeb 重新安装依赖再试试
