### ISSUE TITLE
使用prefix tree方式进行路由匹配

### ISSUE THREAD

**Issue by GeniusBrother** [eggjs/egg#4261]
看了下源码 egg的路由时基于koa-router的 koa-router在进行路由匹配的时候会对已注册的layer(路由)进行遍历看是否匹配，如果路由数量多起来之后 这个性能会有点差吧 为啥不选用前缀树算法进行路由匹配

**Comment by atian25** [comment]
来个 PR 吧~

egg-router 是 fork koa-router 的，这个 prefix tree 会有 break 么？

**Comment by GeniusBrother** [comment]
目前我不好提PR 因为对egg的整个架构还不是很熟悉 想问下你们后续会规划使用前缀树算法进行路由匹配吗？

**Comment by dead-horse** [comment]
从具体的项目实践来看，就算是几千条的路由匹配也很难成为项目中的热点代码，相较于这个优化而言，项目复杂度的提升导致性价比不高。

**Comment by GeniusBrother** [comment]
这样会导致项目复杂度提升吗？按照我的理解 路由只是个完全独立的模块，只要对外的接口不变 里面的具体实现完全可以替换 而且前缀树算法匹配又不是个复杂的算法 其它平台早就应用了

**Comment by GeniusBrother** [comment]
var Koa = require('koa');
var Router = require('@eggjs/router');

var app = new Koa();
var router = new Router();

for(let idx = 0; idx< 2000; idx++) {
  router.get(`/api/test${idx}`, async (ctx) => {
    let now = Date.now();
    ctx.body = now - ctx.startTime;
    console.log(now, idx);
  });
}

app.use(async (ctx, next) => {
  ctx.startTime = Date.now();
  console.log(ctx.startTime);
  await next();
}).use(router.routes())
  .use(router.allowedMethods());
app.listen(3001);

不过我测了下 就算有2000条路由 除了第一次请求 需要100毫秒左右的匹配时间 后续都需要10毫秒左右就可以。这样的话的确不优化也没事，不过我有个疑问 为啥第一次请求要100毫秒左右？
