### ISSUE TITLE
app.router.namespace无法使用自定义的全局中间件及配置？

### ISSUE THREAD

**Issue by Vibing** [eggjs/egg#4262]
我使用 `namespace` 定义路由：
```js
const apiRouter = app.router.namespace(
    '/api',
    app.middleware.jwtverify(undefined, app)
);

apiRouter.post('/login', controller.loginController.login);
// ...其他路由
```
在该`namespace`下使用自定义的`jwtverify`中间件。

#### 问题来了： 这会导致该 `namespace` 下所有路由都会走这个中间件，而在`config/config.default.js`中配置的 `ignore` 无效。

jwtverify 的 ignore 配置如下：
```js
jwtverify: {
      ignore: [
        '/api/login',
        '/api/store_version'
      ]
}
```
#### 我该如何解决这个问题？

**Comment by atian25** [comment]
`app.middleware.jwtverify(undefined, app)` 你自己初始化的 middleware，当然不会读配置啊，你传了 undefined。

两种方式：

1. 不要在 namespace 传 middleware，直接 config.middleware 配置一个全局的
2. namespace 初始化的时候传第一个参数

**Comment by Vibing** [comment]
> `app.middleware.jwtverify(undefined, app)` 你自己初始化的 middleware，当然不会读配置啊，你传了 undefined。
> 
> 两种方式：
> 
> 1. 不要在 namespace 传 middleware，直接 config.middleware 配置一个全局的
> 2. namespace 初始化的时候传第一个参数

@atian25 感谢回答！

我用了第一种方式，发现没有效果才在`namespace`里传的：
```js
  config.middleware = ['jwtverify'];
```
```js
jwtverify: {
      ignore: [
        '/api/login',
        '/api/store_version'
      ]
    }
```

我希望能用第一种方式解决，但我检查了好像没有写错

**Comment by atian25** [comment]
提供下最小可复现仓库
