### ISSUE TITLE
egg-logview 资源加载出错

### ISSUE THREAD

**Issue by luasy** [eggjs/egg#4263]
## What happens?

使用了 egg-logview：2.0.0 插件。目前，就是远程资源问题。
![image](https://user-images.githubusercontent.com/40572453/79557715-9a19e880-80d5-11ea-93b5-7f1cb98b5f7f.png)

目前也没有新版本，看源是否能换一下。

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
MacOS
- **Node 版本**：
Node: 10.16.0
- **Egg 版本**：
egg: "^2.2.1"
egg-logview: "^2.0.0"

**Comment by atian25** [comment]
来个 PR 修复下吧

**Comment by szy0syz** [comment]
我太懒了，手动改了下cdn 😂

**Comment by atian25** [comment]
已经发布过了，直接更新依赖即可
