### ISSUE TITLE
如何做到在生产环境部署过程中不中断服务？

### ISSUE THREAD

**Issue by bhgx** [eggjs/egg#4266]
根据egg官方文档，在生产环境通过npm start 来启动服务，npm stop 来停止服务，但这过程中服务会中断，请问有没有什么办法或机制避免部署过程中的服务中断？

**Comment by hyj1991** [comment]
发布的机器把自己摘出负载均衡集群，然后 stop -> start，启动后检测下端口通了再把自己加入回负载均衡集群，分批这样依此发就行了
