### ISSUE TITLE
egg-session 的session 可以重复利用吗

### ISSUE THREAD

**Issue by notomorow** [eggjs/egg#4267]
## What happens?
我原先对session的理解是每次登录后会产生一个唯一的session值，当退出登录后之前的session是无效了的，但是通过charles抓包，再重新请求，发现退出登录后，带有老session的请求还是能获取到登录状态下的信息。这让我有点疑惑，如果是这样，那我知道了某人某次登录的session值，那我之后随时可以利用这个session值登录到他的账户了，这样是不是不够安全(应该不是egg-session的问题，而是koa-session的行为)？

## 相关环境信息
- **操作系统**：MacOs
- **Node 版本**：v10.13.0
- **Egg 版本**：2.26.0

**Comment by atian25** [comment]
> 那我知道了某人某次登录的session值

没那么容易拿到的，这属于 cookie security 的范畴， http: only 等就是干这个的。（不要想如果拿到电脑后看 devtools 怎么办，拿到电脑还有啥干不了）

sessionid 只是一个唯一标识，这些跟 egg 没啥关系，都是通用的鉴权逻辑，看下业界通用方案即可。譬如你在做登录态的时候，往 session user 里面存个 token，这个 token 是加密过的，只有在服务端可以解开，且可以包含下有效期啥的。或者加个中间件去校验下（再加个 redis 缓存下）

**Comment by notomorow** [comment]
嗯，基本同意你说的。不过既然会加有效期，感觉还是为了避免同一个session不能使用过长的问题。所以假设每次生成的session值都包含了某些随机的因子，这样安全级别是不是又增强了一些。

**Comment by atian25** [comment]
看你自己的处理，你可以往 ctx.session 里面自行写个值

**Comment by notomorow** [comment]
嗯，但是这样做我就得自己单独维护session对象(或者说和session有关的对象)了，这部分工感觉也属于session中间件工作的范畴。

**Comment by atian25** [comment]
session 就是一个 存储 而已，它可不管你存什么。https://eggjs.github.io/zh/guide/session.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by notomorow** [comment]
嗯，我的问题通过三方存储(egg-redis)解决了。
