### ISSUE TITLE
egg的config.static 配置 maxAge 不生效

### ISSUE THREAD

**Issue by 15837225836** [eggjs/egg#4268]
## What happens?

如题，静态资源文件缓存时间，不管如何配置 config.static 的 maxAge配置项，最终在生产环境下，都会固化为 cache-control: public, max-age=31536000
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
config.prod.js
