### ISSUE TITLE
插件中如果正确使用中间件

### ISSUE THREAD

**Issue by notomorow** [eggjs/egg#4271]
## What happens?

![image](https://user-images.githubusercontent.com/12589944/79959092-441eb980-84b6-11ea-856d-9ee8d6e17f03.png)
官网”插件开发“一篇给出的是这种方式，可是好像这种方式不能随便自定义插件的名称，不然就会报如下错误：
`TypeError: Middleware undefined not found
    at AppWorkerLoader.loadMiddleware (/work/programs/nodejs-image/node_modules/egg-core/lib/loader/mixin/middleware.js:67:15)`
所以，插件中正确使用中间件的方式是什么样的

## 相关环境信息
- **操作系统**macOs
- **Node 版本**：10.13.0
- **Egg 版本**：2.21.1

**Comment by atian25** [comment]
看下 egg-static 源码

**Comment by notomorow** [comment]
不好意思，是我使用不当，在config.deault.js 里写的有问题
`config.middleware= [ undefined, 'appCollection', 'auth' ],`
把 undefined去掉就成了
