### ISSUE TITLE
生成的路由与代码中的不一样

### ISSUE THREAD

**Issue by HowGraceU** [eggjs/egg#4273]
## What happens?
曾经写过路由 router.get('/product/order/get', function(){});
后来将路由中的 product 删掉后，代码为 router.get('/order/get', function(){});，但是生成的路由还是 /product/order/get。

测试1：将路由改为 router.get('/order/getd', function(){});，生成的路由为 /order/getd 表现正常。
测试2：将代码 router.get('/order/get', function(){}); 放到下一行，生成的路由为 /order/get 表现正常。
测试3：另一台机器 clone 下一样的代码起的路由为 /order/get 表现正常。

问题：唯独那一行的路由 router.get('/order/get', function(){}); 生成了 /product/order/get 的路由。

## Mini Showcase Repository(REQUIRED)
无

## How To Reproduce

**Steps to reproduce the behavior:**
1.写过路由 router.get('/product/order/get', function(){});
2.将路由中的 product 删掉后，代码为 router.get('/order/get', function(){});，但是生成的路由还是 /product/order/get。

## Context
- **Node Version**: 13.11.0
- **Egg Version**:2.26.0
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:win10 1909
![1587608219(1)](https://user-images.githubusercontent.com/19248531/80051794-a1b11580-854b-11ea-9261-341a323c9e56.jpg)
![1587608199(1)](https://user-images.githubusercontent.com/19248531/80051806-a83f8d00-854b-11ea-863b-ffd1161bd806.jpg)

**Comment by HowGraceU** [comment]
- **Mini Showcase Repository**: [偶现bug，一台电脑出现，无可复现代码，希望提供排除思路](https://github.com/eggjs/egg/issues/4273)

**Comment by atian25** [comment]
无法复现的没法排查。排查思路就是你断点 egg-router 来查。还有 dump 生成是在 egg 里面的。

**Comment by HowGraceU** [comment]
我使用 npm run debug 进去看了 sourcemap，加载的 router.js 里面的代码就是 router.get('/product/order/get', controller.order.get);
![1587629675(1)](https://user-images.githubusercontent.com/19248531/80075630-94ad1a00-857d-11ea-9381-713cf1bbf276.jpg)

尽管我的代码写的是 router.get('/order/get', controller.order.get);

难道有什么缓存？

**Comment by atian25** [comment]
sourcemap ？ 用了 ts ？开发期应该是 ts-node 不落盘的。

**Comment by HowGraceU** [comment]
是的，ts。
**开发期应该是 ts-node 不落盘的。**的意思是？

**Comment by HowGraceU** [comment]
用的是egg的ts模板构建的，开发期应该都是ts文件，但是控制台打开后像是有 sourcemap 的效果。
用 npm run tsc 跑出来的 js 文件内容是正常的

**Comment by atian25** [comment]
调试 egg-core 的 loader 加载 router 和 Controller 是不是最新的内容。

@whxaxes ts-node cache 有没有问题？看到 2 天前发了 8.9

**Comment by HowGraceU** [comment]
我在代码上面加一个换行（代码写到61行），代码就正常了
![1587630711(1)](https://user-images.githubusercontent.com/19248531/80077425-130abb80-8580-11ea-85a7-eb90a696a54a.png)

把换行去掉（代码写到60行），就变成了 '/product/order/get'

**Comment by atian25** [comment]
不确定，你先定位是不是 ts-node 编译 cache 问题。

**Comment by HowGraceU** [comment]
清空了 ts-node 的缓存文件就正常了，ts-node 的版本 7.0.1

**Comment by chobits4** [comment]
> 清空了 ts-node 的缓存文件就正常了，ts-node 的版本 7.0.1

麻烦问下，如何清空ts-node的缓存文件
