### ISSUE TITLE
[文档错误] logger.consoleLevel 的默认值应该是 WARN

### ISSUE THREAD

**Issue by xuxucode** [eggjs/egg#4275]
文档 https://eggjs.org/zh-cn/core/logger.html#终端日志级别 提到 `logger.consoleLevel` 默认值是 **INFO**，但实际上应该是 **WARN** 。

参考代码 https://github.com/eggjs/egg/blob/master/config/config.local.js#L5:
```js
module.exports = {
  logger: {
    consoleLevel: 'WARN',
  },
};
```

**Comment by atian25** [comment]
默认(default) 是 INFO，本地开发(local) 是 WARN

**Comment by xuxucode** [comment]
看文档的时候感觉容易糊涂:
> 默认只会输出 INFO 及以上（WARN 和 ERROR）的日志到终端中。这些日志默认只在 local 和 unittest 环境下会打印到终端

config.default.js 默认 INFO，但文档中没有提到 local 和 unittest 默认值 WARN

**Comment by atian25** [comment]
可以来个 PR 优化下

**Comment by xuxucode** [comment]
RP https://github.com/eggjs/egg/pull/4276
