### ISSUE TITLE
idea, webstorm 修改后端代码后，不会自动重启 worker 进程

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#428]
idea, webstorm 修改后端代码后，不会自动重启 worker 进程，
用记事本或其它工具修改，会自动重启

**Comment by atian25** [comment]
我这边本地测试是没问题的

**Comment by huangyanxiong01** [comment]
把你的启动命令贴出看看

**Comment by zlab** [comment]
npm run dev

**Comment by atian25** [comment]
系统环境啥的呢?  有用 vagrant 么?

**Comment by zlab** [comment]
![图片](http://t3.qpic.cn/mblogpic/1ddd3980beddb045116a/2000)

**Comment by atian25** [comment]
正常启动会有个 watcher 的日志的:
```bash
2017-02-22 15:28:44,577 INFO 72081 [egg:watcher:agent] watcher start success
2017-02-22 15:28:44,584 INFO 72077 [master] Agent Worker started (559ms)
```

你试下重新安装依赖, 还有 egg-bin 不要装全局的.

```bash
$ rm -rf node_modules
$ npm i
$ npm run dev
```

**Comment by atian25** [comment]
cc @shaoshuai0102

**Comment by shaoshuai0102** [comment]
idea, webstorm 修改文件有啥特殊机制么。。

**Comment by zlab** [comment]
![图片](http://t3.qpic.cn/mblogpic/873edcc3530b30ee6e7c/2000)
### 在webstorm里面改不会重启，我在外面用记事本改，就会重启

**Comment by zlab** [comment]
idea, webstorm 我都试过了，不行， vs code， atom，记事本可以

**Comment by jtyjty99999** [comment]
可能与这个有关系 http://stackoverflow.com/questions/34213253/webpack-watch-not-working-on-webstorm-on-windows  配置下使用 safe write 试试

**Comment by shaoshuai0102** [comment]
![image](https://cloud.githubusercontent.com/assets/456108/23202673/06590e50-f91a-11e6-8139-ebd69e9d07e8.png)

确实是这个原因。

试试解决办法：

1. 关掉 safe write
2. 尝试下  [egg-watcher-chokidar](http://web.npm.alibaba-inc.com/package/egg-watcher-chokidar) 替换默认 watcher

**Comment by zlab** [comment]
ok了，谢谢各位，就是重启还是报一堆的错
```
2017-02-22 16:23:25,923 ERROR 186360 nodejs.ECONNRESETError: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
code: 'ECONNRESET'
errno: 'ECONNRESET'
syscall: 'read'
name: 'ECONNRESETError'
pid: 186360
hostname: zhanqi-pc
```

**Comment by shaoshuai0102** [comment]
重启报错在这里跟进 https://github.com/eggjs/egg/issues/432

**Comment by atian25** [comment]
@zlab 你的解决方案是选择了哪一种

**Comment by zlab** [comment]
关掉 safe write

**Comment by naffan2014** [comment]
sublime 编写egg。iterm2 运行的npm run dev 也是不自动重启

**Comment by Ailein** [comment]
修改了文件 自动重启了 ，页面打不开了，一直在等待，卡住了。

**Comment by Ailein** [comment]
![image](https://user-images.githubusercontent.com/26592729/27719481-29221f74-5d85-11e7-8534-ecbb3f62b811.png)
![image](https://user-images.githubusercontent.com/26592729/27719495-3b780116-5d85-11e7-8a62-30472669f2fb.png)
新建的一个项目，没有动什么只是改了下hi, egg3,
环境 win10
node v6.10.2
