### ISSUE TITLE
egg-mysql插入语句，用事务中途返回404

### ISSUE THREAD

**Issue by Guxiaobai21** [eggjs/egg#4281]
## What happens?
为什么用egg-mysql进行三条插入语句时，第一条返回后，前端便收到了404，后续两条插入语句也照常执行，最后查看数据库，也插入成功。
开始时是在事务中进行，结果一样，后面通过每插入一条后，判断返回结果再继续插入，也是在第一条完成插入时，便自动返回前端404。请问这是什么问题？应该怎么解决！

**Comment by hyj1991** [comment]
这是你编写的业务逻辑的问题吧
