### ISSUE TITLE
请问下eggjs 的 HttpClient 如何强制使用 form-data 发送请求呢？

### ISSUE THREAD

**Issue by geesmart** [eggjs/egg#4282]
请问下eggjs 的 HttpClient 不上传文件的情况下如何强制使用 form-data 发送请求呢？

我看了下文档 contentType

" contentType 设置请求数据格式，默认是 undefined，HttpClient 会自动根据 data 和 content 参数自动设置。 data 是 object 的时候默认设置的是 form。支持 json 格式。"

我是不是可以设置 contentType 为 form-data 就可以发送 form-data 格式的数据呢？

**Comment by atian25** [comment]
https://github.com/node-modules/urllib#options-optionsstream
