### ISSUE TITLE
更新静态文件 需要重启服务？

### ISSUE THREAD

**Issue by 232650413** [eggjs/egg#4283]
更新静态文件 需要重启服务？
eggjs项目里的静态文件，若更新样式表，需要npm stop ... start 重启？

**Comment by atian25** [comment]
- 静态资源一般打 hash 非覆盖式部署到 cdn，不要依赖 static
- 增量更新服务器内容是不安全的，出了问题没法回滚
- 你实在想要，看下 egg-static 依赖的底层包，配置下 buffer

**Comment by 232650413** [comment]
静态资源一般打 hash 非覆盖式部署到 cdn是什么意思？是我重新开个非项目的文件目录，然后调？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TZ | 天猪"<notifications@github.com&gt;; 
发送时间: 2020年4月28日(星期二) 晚上11:34
收件人: "eggjs/egg"<egg@noreply.github.com&gt;; 
抄送: "DeathGhost"<232650413@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [eggjs/egg] 更新静态文件 需要重启服务？ (#4283)





  
静态资源一般打 hash 非覆盖式部署到 cdn，不要依赖 static
 
增量更新服务器内容是不安全的，出了问题没法回滚
 
你实在想要，看下 egg-static 依赖的底层包，配置下 buffer

**Comment by atian25** [comment]
了解下前端工程化相关的理念吧，可以去看看张云龙的 blog

**Comment by 232650413** [comment]
🤣😘
