### ISSUE TITLE
rename schedule.disable to schedule.disabled

### ISSUE THREAD

**Issue by airyland** [eggjs/egg#4284]
## What happens?

定时任务的禁用属性一直是 disable，但是在表示状态时应该是使用 disabled 比较合适。
这一点导致在使用时会有一点强迫症，并不是一个 bug。
国际推广的话这一点可能会让人感觉奇怪。
期望是可以支持 disabled，避免出 bug 可以兼容原来的 disable。

同理还有 plugin.enable => plugin.enabled

## 最小可复现仓库
无

## 复现步骤，错误日志以及相关配置
无

## 相关环境信息
无

**Comment by atian25** [comment]
我理解 `enabled` 是一个状态， `enable` 是一个开关。如无必要，勿增实体。

**Comment by airyland** [comment]
enabled 既是状态也是开关，开关的表达应该是一种状态。从各个开源项目

**Comment by atian25** [comment]
这个改动有点大了，目前没看到必要性
