### ISSUE TITLE
现在文件目录名(app)能不能支持自定义名字?

### ISSUE THREAD

**Issue by menglinlun** [eggjs/egg#4285]
## Background
我之前用egg1.0的时候对ts支持不好,于是建了一个其他的文件夹app-xx放在同级目录下,每次本地开发执行tsc-w编译到app目录下
## Proposal
现在egg升级了,希望同时把以前的ts编译进程去掉,但是不希望app-xx文件夹目录 直接=> app目录,会丢失大量git提交信息,所以希望自定义目录名字

## Additional context
![image](https://user-images.githubusercontent.com/26383439/81036324-4bd85800-8ed1-11ea-872c-25d73c805d53.png)

**Comment by menglinlun** [comment]
已经解决

**Comment by atian25** [comment]
git 改名不会丢历史吧

**Comment by menglinlun** [comment]
> git 改名不会丢历史吧

不会,不过目前有很多人在开发,改一个文件夹名字也不轻松

**Comment by quanru** [comment]
求问：可不可以自定义 app 为 server，因为同级目录放了 client 目录 @atian25

**Comment by atian25** [comment]
需要自己定义 loader，可以看下 egg-core 源码
