### ISSUE TITLE
[egg-schedule]定时任务在到点触发后没有立即执行

### ISSUE THREAD

**Issue by EasonYou** [eggjs/egg#4287]
## What happens?
定时任务触发后，并没有立即执行，而是延迟过了两小时左右一起执行

## Mini Showcase Repository(REQUIRED)
还真不好复现，这个很偶发，不知道是不是node版本的问题。因为挺老的了，v8.12.0的

下图中，2点触发的定时任务，一起到了4点零3分才执行，中间几个定时任务也一起卡在4点零3分执行
![image](https://user-images.githubusercontent.com/16911502/81262973-65180a80-9071-11ea-9d22-0a4c30b44098.png)

## How To Reproduce

**Steps to reproduce the behavior:**
1. 整点触发定时任务

**Expected behavior**
1. 立即执行而不是延后执行

## Context
- **Node Version**: v8.12.0
- **Egg Version**: v2.26.0
- **Plugin Name**: egg-schedule
- **Plugin Version**: 3.6.4
- **Platform**: centos6/docker

**Comment by atian25** [comment]
感觉可能这段时间你们有什么重 CPU 的操作吧，egg-schedule 就是一个 setTimeout

**Comment by EasonYou** [comment]
@atian25 好的谢谢~我看看schedule源码再定位问题，这个issue先关闭
