### ISSUE TITLE
请问一下RESTful API自定义日志记录每次api请求的输入和输出参数

### ISSUE THREAD

**Issue by leo2022** [eggjs/egg#4290]
config.default.js
return {
    ...config,
    ...userConfig,
    customLogger: {
      xxLogger: {
        file: path.join(appInfo.root, 'logs/api.log'),
        formatter(meta) {
          return `[${meta.date}] ${meta.message}`;
        },
        // ctx logger
        contextFormatter(meta) {
          return `[${meta.date}] [${meta.ctx.method} ${meta.ctx.url}] ${meta.message}`;
        },
      },
    },
    logrotator: {
      filesRotateBySize: [
        path.join(appInfo.root, 'logs', appInfo.name, 'api.log'),
      ],
      maxFileSize: 2 * 1024 * 1024 * 1024,
    },
  };
具体配置是这样的，请问如何记录每次api请求的输入和输出参数

**Comment by biubiukevin** [comment]
写个中间件，记录一下就好了呗

**Comment by leo2022** [comment]
> 写个中间件，记录一下就好了呗

ctx.coreLogger.info(ctx.request.body) 我是这样记录的输入参数，请问一下在中间价里如何写如何应用

**Comment by atian25** [comment]
中间件里面不是有 ctx 么，调用 ctx.logger 即可
