### ISSUE TITLE
egg-bin dev build卡在95%

### ISSUE THREAD

**Issue by WJS1101** [eggjs/egg#4293]
![image](https://user-images.githubusercontent.com/61043184/81549866-007ee780-93b2-11ea-8e72-8e1056b47804.png)

**Comment by atian25** [comment]
看起来跟 egg 没啥关系，这是 umi 构建卡住了

**Comment by WJS1101** [comment]
已在umi issue中找到处理方案
编辑 config/config.js，搜索 chainWebpack 并注释掉。
