### ISSUE TITLE
egg-soft-rpc ts 项目不能用生成的.js文件吗？运行一直报错！案例文件也有错误！请不要让问题石沉大海 

### ISSUE THREAD

**Issue by fuxiaowo** [eggjs/egg#4302]
我是用 -ts 文件模式， 调用 egg-rpc-generator 生成 ProtoService.js 文件，作为客户端， run dev 后启动报错， options.registry or options.serverHost at least set one 这句话什么意思？在package.json里面设置rpc吗？如果是，已经设置了

```
config.sofaRpc = {   // 此处案例中是config.rpc 严重错误
    registry: {
      address: '127.0.0.1:2181', // 根据实际情况配置
    },
    client: {
      responseTimeout: 3000,
    },
  };

```
```
/Users/admin/Documents/Projects/moogrid-server-egg/puppeter/node_modules/_sofa-rpc-node@1.18.0@sofa-rpc-node/lib/client/consumer.js:25
    assert(options.allowMock || options.serverHost || options.registry, '[RpcConsumer] options.registry or options.serverHost at least set one');
```
    请问是什么导致了这样的错误呢？需要怎么操作呢？

**Comment by gxcsoccer** [comment]
@fuxiaowo 最好能提供一个复现的仓库

**Comment by naxiaoguang** [comment]
@gxcsoccer   https://github.com/naxiaoguang/rpc-test.git 这是我写的代码。分server与client,都是用egg写的。
## server端 ### 
`npm run test `
`**报错 Error: not found service: ProtoService:1.0**`

### client
`npm run dev`
[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (10ms)
[egg-ts-helper] create typings/config/plugin.d.ts (2ms)
[egg-ts-helper] create typings/app/service/index.d.ts (2ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2020-05-14 13:07:18,924 INFO 50278 [master] node version v10.16.3
2020-05-14 13:07:18,925 INFO 50278 [master] sofa-node version 1.0.1
2020-05-14 13:07:19,849 INFO 50278 [master] agent_worker#1:50283 started (921ms)

/Users/dd/Documents/test/rpc/client/node_modules/_sofa-rpc-node@1.18.0@sofa-rpc-node/lib/client/consumer.js:25
    assert(options.allowMock || options.serverHost || options.registry, '[RpcConsumer] options.registry or options.serverHost at least set one');

**Comment by naxiaoguang** [comment]
> @fuxiaowo 最好能提供一个复现的仓库

@gxcsoccer 这是我的代码问题还是我的环境问题？能给一个答复吗？非常感谢！

**Comment by gxcsoccer** [comment]
@naxiaoguang 

收到，我晚点看

**Comment by gxcsoccer** [comment]
@atian25 这个好像是 ts 的问题，为啥我用 egg-bin 启动 ts 应用 config.ts 这些都没生效？

**Comment by fuxiaowo** [comment]
> @atian25 这个好像是 ts 的问题，为啥我用 egg-bin 启动 ts 应用 config.ts 这些都没生效？
生成代理文件所用的proxy.js必须是.js后缀，不然generater生成不了文件。
最终生成的也是.js文件。
我用egg example js版本， run test 也会报这个错
`ERROR 87571 nodejs.Error: not found service: ProtoService:1.0`

**Comment by naxiaoguang** [comment]
@gxcsoccer   我能配合着做些什么吗？找出问题，让程序能正常运行。现在就卡在这个rpc了。心急的感受你不了解呀。或者有没有替代方案？

**Comment by naxiaoguang** [comment]
@gxcsoccer 传奇的阿里大神，这个问题有眉目了吗？

**Comment by gxcsoccer** [comment]
https://github.com/naxiaoguang/rpc-test/pull/1/files

参考这个 pr

**Comment by gxcsoccer** [comment]
cc: @fuxiaowo 

sofaRpc 改成 rpc 了，参考上面的 pr

**Comment by naxiaoguang** [comment]
> cc: @fuxiaowo
> 
> sofaRpc 改成 rpc 了，参考上面的 pr

非常感谢，都可以正常跑起来了。我自己还是有马虎的地方！
