### ISSUE TITLE
vscode-eggjs在vscode中没有代码块提示

### ISSUE THREAD

**Issue by webVictor** [eggjs/egg#4303]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **VSCode版本**：版本: 1.45.0
- **eggjs插件版本**：版本: 0.3.1
- **Node 版本**：
- **Egg 版本**："egg": "^2.15.1",

**Comment by atian25** [comment]
vscode-eggjs 不提供代码提示能力。

按骨架启动后，egg-ts-helper 会自动生成对应的 d.ts 就可以了

**Comment by webVictor** [comment]
> vscode-eggjs 不提供代码提示能力，它只是早期的试验产物，现在随着 vscode 和 ts 的成熟，不需要用这个插件了。
> 
> 按骨架启动后，egg-ts-helper 会自动生成对应的 d.ts 就可以了

没有用ts,egg-ts-helper岂不是对我没有用了

**Comment by atian25** [comment]
内置到 egg-bin 的，会自动生成，有用到的，解决 loader 导致的声明问题
