### ISSUE TITLE
How to share context between different 'it' in one describe?

### ISSUE THREAD

**Issue by dragooncjw** [eggjs/egg#4304]
I'm using egg-mock, and here's my code:
```
import { Context } from 'egg'
describe('this is a describe', () => {
  let ctx: Context
  beforeEach(async () => {
  })
  afterEach(async () => {
    app.close()
  })
  it('first it', async () => {
    ctx = app.mockContext({xxxx})
  })

  it('second it', async () => {
    ctx = app.mockContext({xxxx})
  })
})
```
If I define ctx in before, in the second 'it', what I defined in mockContext can not be accessed.
There are some deprecation in my ctx. I want to know if I can share one context to decrease the amount of code.

**Comment by atian25** [comment]
why don't you move `app.mockContext` to `before` ?

**Comment by dragooncjw** [comment]
I've tried. I wrote like below.
```
before(async () => {
    ctx = app.mockContext({
      session: {user:{username: 'dragooncjw'}}
    })
})
```
both of my it used ctx.service.checkUser function. Here's my servicefunction: 
```
 public async checkUser(xxxx) {
    const { ctx, app } = this;
    const username: string = ctx.session.user.username; //error line
}
```
 In that function in the second `it`, ctx.session.user is undefined. Cannot read property 'username' of undefined.

**Comment by atian25** [comment]
@dragooncjw please provide a mini GitHub repository to help us to check

**Comment by dragooncjw** [comment]
I think maybe I found the reason. I'm trying to modify the project `egg-mongoose` to prevent leakage of private code, when I use js instead of ts, it throw out new error:`throw new Error('DO NOT USE bootstrap to test plugin');`. I will try egg-mock instead of egg-mock/bootstrap.

**Comment by dragooncjw** [comment]
It's not what I thought before. Just initialize `ctx` in `beforeEach`.  It can't get `mockContext` before `ready`. For some reason under my configuration, it didn't report this error.
