### ISSUE TITLE
如何确定单元测试文件运行顺序

### ISSUE THREAD

**Issue by dragooncjw** [eggjs/egg#4306]
我正在使用egg-mock进行测试。
我在app/service下定义了对几个数据库的操作，下面是我的问题环境：
我拥有两个数据库——Namespace和Component，在我对其进行测试的时候，Component相关的操作需要Namespace对应数据存在才可以进行测试，操作顺序如下：
> Namespace create
> Component create
> Component delete
> Namespace delete

目前我想到两个解决方法：
1、将测试代码放在一个文件内，按照上面的顺序进行编写，但是这样的方法会导致一个文件内的代码量变多，如果我有很多个关联的数据库，这个文件会变得很大。
2、ws监控数据库变化，对应测试Namespace数据出现的时候再进行Component操作，但是这样显然减慢了测试速度。
目前test文件执行顺序是按照文件名排序执行，我想了解是否提供相关顺序配置，或者有什么其他的规范写法。

**Comment by atian25** [comment]
这块就是 mocha 自己的逻辑，而且不保证会顺序执行。

单测测试一般不要去依赖 it 的顺序，每个 it 自己 mock 准备自己的数据。

**Comment by dragooncjw** [comment]
了解了。谢谢。
