### ISSUE TITLE
egg是不维护了吗？

### ISSUE THREAD

**Issue by bluelifeleer** [eggjs/egg#4307]
egg是不维护了吗？
好多依赖包都提示弃用，具体应该怎么解决？求给个方法

**Comment by atian25** [comment]
放心，想放弃维护的话，阿里几千个 Node Owner 会先打死我们。

什么依赖包？有问题就带可复现方式提 issue。

**Comment by hyj1991** [comment]
依赖包也分为官方维护的是三方作者自己维护的。
三方作者自己编写的依赖包维护与否取决于他们自己，不是所有 egg-xxx 的包都是由官方维护的
如果你遇到提示弃用的库，可以先看下属于哪边 :)
