### ISSUE TITLE
egg-view-nunjucks 无法加载

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#431]
### egg-view-nunjucks 升级到 2.0 报错，1.2 没有问题
> \node_modules\egg-core\lib\loader\mixin\plugin.js:274
      throw err;
      ^
   PluginSequencifyError: sequencify plugins has problem, missing: [], recursive: [view,view]

### 版本
``` 
egg-view-nunjucks 2.0
```

### eggjs.org  配置代码
```
// config/plugin.js
exports.view = {
  enable: true,
  package: 'egg-view-nunjucks',
};
```

### egg-view-nunjucks readme.md 配置代码
```
Usage

// {app_root}/config/plugin.js
exports.nunjucks = {
  enable: true,
  package: 'egg-view-nunjucks',
};
Set mapping

exports.view = {
  defaultViewEngine: 'nunjucks',
  mapping: {
    '.nj': 'nunjucks',
  },
};
```

# 为什么两个配置不一样了

**Comment by popomore** [comment]
因为这个还没改完，文档也在更新 https://github.com/eggjs/egg/issues/398

**Comment by dead-horse** [comment]
@popomore 先将 latest 指定到 1.x 吧

**Comment by popomore** [comment]
```
```

**Comment by zlab** [comment]
ok
