### ISSUE TITLE
service 层没有代码提示，请问如何处理？

### ISSUE THREAD

**Issue by caihaibin1991** [eggjs/egg#4314]
service 层没有代码提示，请问如何处理？

**Comment by caihaibin1991** [comment]
是否建议走typescript版本？最近折腾下来。就卡着这块。主要两个问题，就算用vsc开发，在控制器部分，代码提示也有一定的延迟。

**Comment by atian25** [comment]
如果按模板生成的，会自动生成 d.ts 的。可以自己分析下看看啥原因。

**Comment by caihaibin1991** [comment]
请问有没有比较合适的typescript写法的开源项目推荐？

**Comment by caihaibin1991** [comment]
eggjs开源的有好些不错的。但是目前搜索不到typescript版本的。

**Comment by atian25** [comment]
官方文档就有一篇 TS 。用 TS 写的前提是：你的团队要有最基本的 TS 经验，最基础的 d.ts 问题要知道怎么解决。

**Comment by caihaibin1991** [comment]
好的。谢谢

**Comment by darrenliuwei** [comment]
> eggjs开源的有好些不错的。但是目前搜索不到typescript版本的。

https://cool-admin.com

这个是用typescript版的egg.js开发的，不过是付费的，有兴趣你可以去咨询下。

之前作者还在cnode论坛上做过推广：https://cnodejs.org/user/cool-admin

**Comment by caihaibin1991** [comment]
@darrenliuwei 谢谢

**Comment by atian25** [comment]
midway 也可以看下，基于 egg 的上层框架，淘宝那边维护的。

**Comment by caihaibin1991** [comment]
@atian25 谢谢
