### ISSUE TITLE
适合TCP开发吗？

### ISSUE THREAD

**Issue by microCloudCode** [eggjs/egg#4315]
egg适合开发tcp吗？

**Comment by atian25** [comment]
egg 底层是 koa，底层是 node http server

理论上你是可以自行启动 net 的，但 koa 那些东西就没法用了。

像 socket.io 啥的是在 agent 自行启动一个然后糅合过去，虽然能用，但还是有点怪。

后面如果我们把 Context 这块抽象下，不仅仅支持 Koa 就可以了。
