### ISSUE TITLE
[Feature Request] egg.js中，插件、中间件、扩展三者的关系和大致使用场景是什么？

### ISSUE THREAD

**Issue by LeoFengFromChina** [eggjs/egg#4319]
## Background
不好意思，把这个问题提到了次类别。还望帮忙解答一下。

**Comment by atian25** [comment]
插件是最小复用单元，中间件和扩展是一种扩展逻辑，可以在 app 也可以在 plugin 也可以在 framework。

可以先看下文档里面 渐进式研发 那章

**Comment by hyj1991** [comment]
插件和中间件的区别是，中间件一定是处理请求相关上下文的，但是插件不一定

**Comment by hyj1991** [comment]
推荐看下这个 https://eggjs.org/zh-cn/tutorials/progressive.html
