### ISSUE TITLE
egg 自定义框架开发 运行测试对时候 test/fixtures/example 代码不完整 直接运行会报错

### ISSUE THREAD

**Issue by 498184609** [eggjs/egg#4321]
![image](https://user-images.githubusercontent.com/37179320/82695016-dae9bc00-9c96-11ea-819f-2a0076fd8043.png)

## What happens?

直接根据官方文档
npm init egg --type=framework
拉下来对自定义框架骨架 在test里面对example对代码里面 controller里面调用了service但是其实拉下来对代码里面并没有service

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
mac os :10.15.4 (19E287)
- **Node 版本**：
node : v12.4.0
- **Egg 版本**：
egg : ^2.3.0

**Comment by ngot** [comment]
欢迎提个 PR 来修复一下

**Comment by 498184609** [comment]
好的 其实我本地已经处理了

**Comment by 498184609** [comment]
我发现这个bug是我自己整出来的，因为在默认的模版app目录下面有定义service 我本地修改的时候，直接吧app目录删除了，替换了我自己的代码 才导致test的时候报错。所以这个 问题其实可以关闭了，但是个人觉得test的代码还是保持完整比较好。否则还是会有许多人会遇到和我一样的问题 。还的自己debug

**Comment by 498184609** [comment]
实际上 直接拉下来的代码 运行是不会报错的。我很纠结要不要pr 要不开发团队顺手改了吧

**Comment by atian25** [comment]
这不是 bug，本来这个骨架就是演示，你在 framework 里面定义一个 service，然后怎么在单测里面验证它。。。

**Comment by 498184609** [comment]
感谢您的回复，骨架里面的代码确实是这样的，service在framework里面的 测试里面的代码是没有service的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TZ | 天猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 上午10:31
收件人:&nbsp;"eggjs/egg"<egg@noreply.github.com&gt;;
抄送:&nbsp;"小新"<498184609@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [eggjs/egg] egg 自定义框架开发 运行测试对时候 test/fixtures/example 代码不完整 直接运行会报错 (#4321)





 
这不是 bug，本来这个骨架就是演示，你在 framework 里面定义一个 service，然后怎么在单测里面验证它。。。

**Comment by atian25** [comment]
fixture 里面肯定不能有啊。这个测试就是演示，你在 framework 里面提供一个 service，然后用户在应用里面可以直接调用，不需要自己写。
