### ISSUE TITLE
egg 自定义框架 运行test 报错 

### ISSUE THREAD

**Issue by 498184609** [eggjs/egg#4322]
## What happens?
egg 自定义框架 运行test 报错，但是看test的结果已经出来了，但是有个报错很奇怪！
egg-boilerplate-framework 没有提交issues的入口就职能在这了

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://gitee.com/t-bwa/egg-bwa-framework.git
因为是打算自己开发一个框架。刚刚开始所以没什么代

## 复现步骤，错误日志以及相关配置
npm run test

错误堆栈如下：
1) should GET /
  0 passing (465ms)
  1 failing
  1) test/framework.test.js
       should GET /:
     Error: expected 'framework-example_123456' response body, got '我是测试'
      at processTicksAndRejections (internal/process/task_queues.js:84:9)
      [use `--full-trace` to display the full stack trace]
Error: /Users/huangqi/bwa/egg-bwa-framework/node_modules/egg-bin/node_modules/mocha/bin/_mocha --timeout=60000,--exit,--require=/Users/huangqi/bwa/egg-bwa-framework/node_modules/egg-bin/lib/mocha-clean.js,--require=/Users/huangqi/bwa/egg-bwa-framework/node_modules/co-mocha/lib/co-mocha.js,--require=/Users/huangqi/bwa/egg-bwa-framework/node_modules/intelli-espower-loader/intelli-espower-loader.js,test/framework.test.js exit with code 1
    at ChildProcess.<anonymous> (/Users/huangqi/bwa/egg-bwa-framework/node_modules/common-bin/lib/helper.js:56:21)
    at Object.onceWrapper (events.js:288:20)
    at ChildProcess.emit (events.js:200:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 1
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-bwa-framework@1.0.0 test-local: `egg-bin test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-bwa-framework@1.0.0 test-local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangqi/.npm-cache/_logs/2020-05-22T17_57_43_438Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-bwa-framework@1.0.0 test: `npm run lint -- --fix && egg-bin pkgfiles && npm run test-local`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the egg-bwa-framework@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huangqi/.npm-cache/_logs/2020-05-22T17_57_43_456Z-debug.log
终端进程已终止，退出代码: 1

## 相关环境信息
- **操作系统**：mac OS 10.15.4 (19E287)
- **Node 版本**：v12.4.0
- **Egg 版本**：^2.3.0

**Comment by atian25** [comment]
https://gitee.com/t-bwa/egg-bwa-framework/blob/master/test/framework.test.js#L22

你自己 expect 的 result 啊。。。 先去学下 supertest 的语法吧

**Comment by 498184609** [comment]
感谢您的回复，我确实看到了我expect 的 result，但是只是没太想明白为什么会有error，关于supertest我确实没怎么了解，感谢您的告知。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TZ | 天猪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 上午10:46
收件人:&nbsp;"eggjs/egg"<egg@noreply.github.com&gt;;
抄送:&nbsp;"小新"<498184609@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [eggjs/egg] egg 自定义框架 运行test 报错  (#4322)





 
https://gitee.com/t-bwa/egg-bwa-framework/blob/master/test/framework.test.js#L22
 
你自己 expect 的 result 啊。。。 先去学下 supertest 的语法吧

**Comment by atian25** [comment]
你的 Controller 把响应结果改了，https://gitee.com/t-bwa/egg-bwa-framework/blob/master/test/fixtures/example/app/controller/home.js#L8

但你用原有的 expect 来测试这个 Controller 的响应，肯定有问题拉。

`.expect('framework-example_123456')`
