### ISSUE TITLE
关于自动重启有没有一个完整的解决方案

### ISSUE THREAD

**Issue by guohuihot** [eggjs/egg#4323]
最近看了不少资料，关于生产模式下自动重启依然没有头绪，没有人有这种需求吗
1. webhooks http://www.abc.com/git-pull-reload  git pull后重启项目
1. 更新config, 动态的在线更新一些配置后重启项目
需求关键点都是要重启，能不能介绍下怎么操作，实在是找不到方向了，卡了几天了

**Comment by guohuihot** [comment]
看了源码找到了个方法，附上代码，供有遇到问题的朋友参考
```js
// controller/home.js
async reload() {
    if (shelljs.exec('git pull').code !== 0) {
        shelljs.echo('Error: Git pull failed')
    }
    process.send({
        to: 'master',
        action: 'reload-worker',
    })
}
```
代码不知道有没有副作用，如果有，请指正

**Comment by atian25** [comment]
单机重启没啥意义，一般都是通过前面的 SLB 来切流重启。

**Comment by guohuihot** [comment]
你说的单机是指的一台服务器，还是多核？
这个需求应该有人有的，除了我上面的例子，还有例如：一个网站，管理希望自己配置一下网站，而这些往往需要yarn stop, yarn start, 而且需要上服务器操作，管理员只会在后台点来点去，这时在后台有一个自动重启就方便很多

**Comment by atian25** [comment]
指 多个 pod。这是运维平台的职责，现在都 2020 年了，都是标配能力了吧。

框架这块不打算提供 worker 层面的重启能力。

如果你实在需要，看下其他同学的实践：

- https://zhuanlan.zhihu.com/p/84632879
- https://zhuanlan.zhihu.com/p/36439661

**Comment by guohuihot** [comment]
这两篇我上周翻了n次，没明白是怎么干的，能力有限

**Comment by atian25** [comment]
加油。
