### ISSUE TITLE
[Feature Request] 如何在自己工具类中获取app？

### ISSUE THREAD

**Issue by 510846** [eggjs/egg#4325]
## Background
自己写一个工具类
app/wework.js
在这个文件里面如何可以获取到 app 实例？比如希望使用 app.redis.set()

**Comment by darrenliuwei** [comment]
> ## Background
> 自己写一个工具类
> app/wework.js
> 在这个文件里面如何可以获取到 app 实例？比如希望使用 app.redis.set()

看一下这一章节？
https://eggjs.org/zh-cn/basics/extend.html

**Comment by atian25** [comment]
工具类可以定义为：

```js
// app/wework.js
module.exports = class MyTool {
   constructor(app) {
      this.app = app;
   }
}
```

如果只是单个文件，直接挂载

```js
// app/extend/application.js
const MyTool = require('../wework');
const MYTOOL = Symbol('Application#myTool');
module.exports = {
  if (!this[MYTOOL]) {
    this[MYTOOL] = new MyTool(this);
  } 
  return this[MYTOOL];
}
```

如果一个目录的话，可以在 app.js 里面用 `app.loader.loadToApp()`
