### ISSUE TITLE
路由前缀如何设置？

### ISSUE THREAD

**Issue by kkjj-kj** [eggjs/egg#4326]
就是koa2有那个{prefix:'/api/v1'}这种在egg.js里有么

**Comment by atian25** [comment]
https://github.com/eggjs/egg-router-plus

你说的那个功能也不是 koa2 自带的，是 koa-router 提供的

**Comment by kkjj-kj** [comment]
谢谢大哥

**Comment by kkjj-kj** [comment]
谢谢大哥
