### ISSUE TITLE
egg-redis 类型错误

### ISSUE THREAD

**Issue by microCloudCode** [eggjs/egg#4330]
当我使用egg-redis配置多客户端时，通过官方文档的方式引用客户端，出现类型错误！
![image](https://user-images.githubusercontent.com/46712199/82857450-9898d700-9f43-11ea-9ce2-3a7f2058f712.png)

**Comment by whxaxes** [comment]
这个目前只能通过 as 来解

```typescript
import { Redis } from "ioredis";

const client = await app.redis.get('xxx') as Redis;
client.set('xxx', 'xxx')
```
因为 redis 这个类型可能是 Redis 也可能是 Singleton<Redis>，为了尽量兼容所以是将类型设置成了 `Redis & Singleton<Redis>` （ [code](https://github.com/eggjs/egg-redis/blob/master/index.d.ts#L19) ）目前也没想到其他什么更好的方案

**Comment by microCloudCode** [comment]
> 这个目前只能通过 as 来解
> 
> ```ts
> import { Redis } from "ioredis";
> 
> const client = await app.redis.get('xxx') as Redis;
> client.set('xxx', 'xxx')
> ```
> 
> 因为 redis 这个类型可能是 Redis 也可能是 Singleton，为了尽量兼容所以是将类型设置成了 `Redis & Singleton<Redis>` （ [code](https://github.com/eggjs/egg-redis/blob/master/index.d.ts#L19) ）目前也没想到其他什么更好的方案

好的，谢谢！我试着使用as Redis 出现了新的错误！
![image](https://user-images.githubusercontent.com/46712199/82858280-00502180-9f46-11ea-9808-ff5651f5f31b.png)

**Comment by microCloudCode** [comment]
已使用as unknown as Redis 解决！
