### ISSUE TITLE
多核下egg schedule任务随机选择worker执行问题

### ISSUE THREAD

**Issue by cici-admin** [eggjs/egg#4331]
多个worker环境中，schedule间隔10秒执行，第一个10秒workerA执行，第二个10秒workerB也执行了，不是应该workerA执行本次任务结束后，再随机B来执行下一次么，没有参数设定。schedule中配置单worker方式执行，还不是一般理解上的A就一直是A，而是每次执行随机选择一个worker执行。

**Comment by atian25** [comment]
schedule 的 worker 指的是每次只找一个 worker 来执行，all 指的是每次触发时所有 woker 都执行。

随机就是随机发送，worker 无状态。

看下 egg-schedule 源码就知道了。如果有需要就实现自定义调度策略即可。
