### ISSUE TITLE
快速入门例子中“https://hacker-news.firebaseio.com/v0”接口现在访问不了了

### ISSUE THREAD

**Issue by w609544721** [eggjs/egg#4333]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
翻墙

**Comment by atian25** [comment]
或者看 https://eggjs.github.io/zh/quickstart/egg.html 吧

**Comment by w609544721** [comment]
已翻墙，仍无法访问，这对于想学习egg框架新手是个亟需解决的问题，如果您能成功访问此接口请截图并回复，不胜感激。另文档中并未提示用户此接口需翻墙操作，对用户体验不佳，望考量。
以上。


| |
17602671715
|
|
17602671715@163.com
|
签名由网易邮箱大师定制


在2020年05月27日 11:32，TZ | 天猪<notifications@github.com> 写道：

翻墙

**Comment by atian25** [comment]
系统翻墙 !== 你的终端翻墙，你需要设置环境变量。

或者手动强制 curl 翻墙：https://eggjs.github.io/zh/guide/httpclient.html#%E6%8A%93%E5%8C%85%E8%B0%83%E8%AF%95
