### ISSUE TITLE
升级ubuntu20后，使用vscode-eggjs生成的launch.json无法debug运行，一直卡在这里

### ISSUE THREAD

**Issue by 820465323** [eggjs/egg#4338]
> cc-server-in-api@1.0.0 debug /home/zzw/7moor/GitLab/cc-server-in-api
> egg-bin debug -r egg-ts-helper/register "--inspect-brk"

Debugger listening on ws://127.0.0.1:9229/791511f6-087f-4275-b642-9c48da4ea360
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[egg-ts-helper] create typings/app/extend/application.d.ts (3ms)
[egg-ts-helper] create typings/app/extend/context.d.ts (4ms)
[egg-ts-helper] create typings/app/extend/helper.d.ts (5ms)
[egg-ts-helper] create typings/app/controller/index.d.ts (12ms)
[egg-ts-helper] create typings/app/middleware/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (11ms)
[egg-ts-helper] create typings/config/plugin.d.ts (2ms)
[egg-ts-helper] create typings/app/service/index.d.ts (6ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2020-06-02 10:08:46,720 INFO 46913 [master] node version v12.17.0
2020-06-02 10:08:46,721 INFO 46913 [master] egg version 2.19.0
Debugger listening on ws://127.0.0.1:5800/9a108353-2285-4353-bc3f-9d92611fb7fd
For help, see: https://nodejs.org/en/docs/inspector

**Comment by 820465323** [comment]
但使用npm run dev是直接可以运行的

**Comment by atian25** [comment]
--inspect-brk 改为 --inspect 吧，如果你对 Node 本身的断点没了解的话。

**Comment by 820465323** [comment]
去掉-brk后，在vscode中打断点不生效，提示
Breakpoint ignored because generated code not found(srouce map problem?)

**Comment by atian25** [comment]
可以提供个最小可复现仓库给我们看看。

**Comment by 820465323** [comment]
... 可能和我当前ubunt 20的系统有关系？
以往能正常运行的所有egg ts项目全部不能使用原launch.json配置启动
并且就在刚刚，使用了egg官网提供的npm init egg --type=ts生成的项目也无法debug运行
看了您分享的相关issue后，尝试了方案，能启动，但断点为灰色，不生效

**Comment by 820465323** [comment]
以JS入口文件启动的老项目debug是正常的
`{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "启动程序",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/app.js"
    }
  ]
}`

但使用vscode-eggjs生成的launch.json无法正常启动，可能是和其他的配置有关系吗

**Comment by atian25** [comment]
在那个 issue 里面也提到了，这个跟 egg 其实没啥关系，就是 VSCode 断点 Node 多进程。

![image](https://user-images.githubusercontent.com/227713/83492466-e3879100-a4e5-11ea-9a46-179144421dd0.png)

重要的点我都注释说明了。

你也可以试下 auto attach，不用 launch 的方式。

> Breakpoint ignored because generated code not found(srouce map problem?)

这句看起来像是 TS 的映射问题，不确定。

如果还有问题的话，只能提供下最小可复现方式了，可能需要提交给 vscode 那边。

**Comment by 820465323** [comment]
刚用了这种配置就可以启动
1. 先启动Egg Debug
2. 再启动Egg Attach
**{
  // 使用 IntelliSense 了解相关属性。 
  // 悬停以查看现有属性的描述。
  // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Egg Debug",
      "runtimeExecutable": "npm",
      "runtimeArgs": [
        "run",
        "debug"
      ],
      "console": "integratedTerminal",
      "restart": true,
      "protocol": "inspector",
      "port": 9229,
      "autoAttachChildProcesses": true
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Egg Attach",
      "localRoot": "${workspaceRoot}",
      "remoteRoot": "${workspaceRoot}",
      "address": "localhost",
      "protocol": "auto",
      "port": 9999
    }
  ]
}**

**Comment by 820465323** [comment]
@atian25  昨天给vscode提了issue，但不明白的是为什么带上--inspect-brk就一直挂起，是在等待附加子进程吗？我开启了auto attach后也无济于事.....

**Comment by atian25** [comment]
我在 issue 那边有分析了，估计是 vscode 的 launch 的时序问题。

auto attach 开了后应该没问题的。如果你不需要调试类库的代码，没必要开 brk
