### ISSUE TITLE
项目部署一段时间后，worker进程出现假死

### ISSUE THREAD

**Issue by gshunj** [eggjs/egg#4341]
问题：
项目部署一段时间后，worker进程出现假死。

异常表现：
部署一段时间后，服务器cup、内存等都很低的情况下leader会重新fork一个新的worker进程出来。但旧的worker进程不会退出，新的fork进程不能工作。如下图：

![C8900DAE-0209-4E8B-8F44-8053DCFB1A57](https://user-images.githubusercontent.com/17870355/83602501-3d9b5b80-a5a5-11ea-81a4-1d1fd74af569.png)

当手动kill掉旧的worker进程（直接kill不掉，只能使用kill -9才能杀掉旧进程），会重新fork新的worker进程，这个新的worker就是正常的，如下图：

![EA0D9D49-CEB5-41CA-9C16-F416604B3BC2](https://user-images.githubusercontent.com/17870355/83603330-d5e61000-a5a6-11ea-970e-573e3ea88460.png)

下图是服务器监控：
![D12EE809-6A78-4078-A73B-CD553ED0595B](https://user-images.githubusercontent.com/17870355/83603447-06c64500-a5a7-11ea-940f-2cd58815d9c3.png)

**Comment by atian25** [comment]
检查下日志，fork 新进程的必然会有日志的，看看为啥会 fork 新的。
可以看下 egg-cluster 的逻辑。

**Comment by gshunj** [comment]
这个问题，日志中没有任何可用的信息。我们排查下来应该是点评的CatClient组件问题，
提供一下我们模拟的复现场景，供以后的同学参考：
  首先 CatServer 要保证活着但是响应要特别慢，通过把CatServer JVM 内存调成128m，可以满足场景要求；
  然后我们加入wtfnode，会输出一些Node停滞原因日志，帮助我们分析。
弄好后，在Eggjs提供接口访问一段时间后，就会复现Node程序假死的问题（而CPU没有任何波动也无相关日志）。wtfnode 最后一条输出中有Cat Child Process...的相关信息（当时忘了截图）。目前把Cat插件从Node项目中移除后，Node项目一直稳定运行。
以上就是我们排查下来，复现的过程。至于为什么点评的CatClient会导致这个问题，还要再继续排查才能知道。。。毕竟断了我们的调用链路。。。
希望对后来的同学有帮助。

**Comment by miser** [comment]
@gshunj Hi 之前我们这边也是用的Cat监控，一直会出问题，然后移除后也是正常了。

出现问题的症状，所有的基础性能指标都很低，CPU、内存等，但是外部请求无法被相应和处理，Docker里的网络状态存在大量Close_wait。通过CPU火焰图发现cat的send message方法占据大量CPU。
