### ISSUE TITLE
egg-schedule没有日志输出关闭选项配置

### ISSUE THREAD

**Issue by yk200842135** [eggjs/egg#4342]
egg定时任务支持间隔interval设置，例如设置2s，一天的egg-schedule.log 光打印此定时任务executing by app/execute succeed,日志有20M，不能对定时任务配置日志输出关闭容易产生大量日志数据

**Comment by atian25** [comment]
https://github.com/eggjs/egg-schedule/blob/master/config/config.default.js#L7

可以设置下 level (不是 consoleLevel)，具体看 egg 日志文档
