### ISSUE TITLE
配置 egg-jwt 出现内部错误

### ISSUE THREAD

**Issue by lvqi0724** [eggjs/egg#4346]
path: ''config/config.default.js''
![image](https://user-images.githubusercontent.com/50160159/84357963-065a2980-abf9-11ea-84a2-d37dcbf85717.png)
path: "config/plugin.js"
![image](https://user-images.githubusercontent.com/50160159/84358007-140faf00-abf9-11ea-8f55-27326dab048d.png)

错误内容:
/Users/byteborder/Desktop/egg/node_modules/egg/lib/application.js:70
      throw e;
TypeError: mw is not a function
![image](https://user-images.githubusercontent.com/50160159/84358065-2b4e9c80-abf9-11ea-90ff-33d85e23c3f6.png)

**Comment by lvqi0724** [comment]
官方大大看到麻烦解答一下呀

**Comment by lvqi0724** [comment]
新项目配置 就没问题 这个项目就不行

**Comment by atian25** [comment]
检查你代码呗，看起来是某个 middleware 写错

**Comment by lvqi0724** [comment]
楼上大佬大
我有个middlewart 创建了文件 没写内容  这也报错

**Comment by lvqi0724** [comment]
呜呜呜 提示不给力呀
