### ISSUE TITLE
配置自定义环境无效

### ISSUE THREAD

**Issue by yyh1102** [eggjs/egg#4347]
## What happens?
按照文档使用`EGG_SERVER_ENV=release npm start`启动，并未读取config.release.ts文件。在 CI上跑的时候报了如下错误：
![image](https://user-images.githubusercontent.com/10328169/84416306-996d8080-ac46-11ea-92e5-92a455386a25.png)

连接的是本地的redis，即为开发环境的配置文件。config.release.ts中链接的是阿里云redis数据库的endpoint。

而使用`EGG_SERVER_ENV=release npm run dev`启动时则读取到config.release.ts，会报错连远端redis timeou了。

![image](https://user-images.githubusercontent.com/10328169/84416601-041ebc00-ac47-11ea-9841-3032462693c5.png)

## Context
- **Node V12.18.0**:
- **Egg 2.26.1**:
- **Mac OSX**:

**Comment by atian25** [comment]
为什么不直接用 prod ？

**Comment by yyh1102** [comment]
prod环境也有配置，业务需要有多个生产环境。另外这个本身应该是egg的bug

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/77e11f5fb38b3646fb20deb78bbc239b06bf8349/lib/loader/mixin/plugin.js#L157

可以考虑用 scope 这个特性（未正式 document，但我们内部都这么用，跟你场景一样）

**Comment by atian25** [comment]
我本地试了下，是可以加载的，是不是 tsc 没编译啥的？

提供下最小可复现仓库。

**Comment by yyh1102** [comment]
有可能，但我这边tsc编译后会报很多类型错误。这个在之前的版本是没有的。。
![image](https://user-images.githubusercontent.com/10328169/84461124-43c4c280-ac9e-11ea-891c-6161256ae3da.png)

**Comment by yyh1102** [comment]
没太看懂，这个scope与EGG_SERVER_ENV是相关联的么

**Comment by atian25** [comment]
这么多报错，你先检查下是不是 config.relase.js 没生成吧。

**Comment by atian25** [comment]
> 没太看懂，这个scope与EGG_SERVER_ENV是相关联的么

是它的补充，看 https://github.com/eggjs/egg-core/blob/afa89c1b2ce89a2f8994943905172ee1bab6f77e/test/loader/mixin/load_config.test.js#L169 这个用例

**Comment by yyh1102** [comment]
![image](https://user-images.githubusercontent.com/10328169/84462696-41fcfe00-aca2-11ea-8c91-83d28eb76102.png)

生成倒是生成了。那些报错是在tsc出现的，直接运行npm start就没问题。。另外tsc在原先的版本是可以的，更新 了最新版egg后就出了这问题。

**Comment by atian25** [comment]
提供最小可复现仓库吧。

**Comment by yyh1102** [comment]
经检验是 typescript和全局tsc版本不一致导致，升级依赖包里的typescript版本即可。tsc成功后 使用`EGG_SERVER_SCOPE`成功读取`config.release_prod.js`配置文件。

**Comment by yyh1102** [comment]
也是醉了，之后出现新的bug。
![image](https://user-images.githubusercontent.com/10328169/84481595-e2feaf80-acc8-11ea-880a-8911cde6615a.png)

![image](https://user-images.githubusercontent.com/10328169/84481608-e7c36380-acc8-11ea-8585-53805a7d9e24.png)

**Comment by atian25** [comment]
这不是 bug，是你写错。

extend/context 里面的 this 就是 ctx，为啥还有 `const { ctx } = this`。

ci 的看下前面的启动日志咯，这种问题，可以自己看看日志，分析下报错堆栈的。

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/config.html#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by yyh1102** [comment]
本地用相同命令跑是可以的，依赖包也都是一样的。会不会是ubuntu16.04 环境下 那样传环境变量 有问题？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/84482662-b350a700-acca-11ea-9a5f-c116d6d25839.png)

看下日志不就得了。。。

**Comment by yyh1102** [comment]
我这里npm start后并没有打出上面的环境变量的相关日志。。

**Comment by atian25** [comment]
start 是正式环境，直接写文件了。

https://eggjs.github.io/zh/guide/logger.html#%E6%97%A5%E5%BF%97%E6%96%87%E4%BB%B6%E8%BE%93%E5%87%BA%E4%BD%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/227713/84483076-63261480-accb-11ea-8aa1-71b11a41c2b8.png)

都写的清清楚楚的

**Comment by yyh1102** [comment]
![image](https://user-images.githubusercontent.com/10328169/84483861-830a0800-accc-11ea-8951-4d04973b9a40.png)

环境变量确实读到了。确认下 是用`config.release_prod.ts`这样命名么？

**Comment by atian25** [comment]
> > 没太看懂，这个scope与EGG_SERVER_ENV是相关联的么
> 
> 是它的补充，看 https://github.com/eggjs/egg-core/blob/afa89c1b2ce89a2f8994943905172ee1bab6f77e/test/loader/mixin/load_config.test.js#L169 这个用例

![image](https://user-images.githubusercontent.com/227713/84484110-e2681800-accc-11ea-8b71-fd4898c06ba0.png)

**Comment by yyh1102** [comment]
是啊，tsc得到config.release_prod.js。 `EGG_SERVER_ENV=prod EGG_SERVER_SCOPE=release`。这样应该没错吧。

![image](https://user-images.githubusercontent.com/10328169/84484767-c9139b80-accd-11ea-8bfc-f98f3f0eceab.png)

**Comment by atian25** [comment]
当然会，你跑下那个 fixtures 或写个最小可复现仓库试试就知道了。

**Comment by yyh1102** [comment]
服务器环境还是不行。我换成了`EGG_NODE_ENV=release`和`config.release.ts`，这回不加载config.prod.ts了。本地OK但服务器还是不行。node是12.18的。

**Comment by itenl** [comment]
@yyh1102 

推荐在./config/config.prod.js 导入所需要的多环境(stag / preprod / ...)配置文件进行合并，在package.json添加以下命令按需启动：

`"stag": "egg-scripts start --daemon --title=egg-server-egg-example",`

`"preprod": "egg-scripts start --daemon --title=egg-server-egg-example",`

./config/config.prod.js 判断依据为：

`process.env.npm_lifecycle_event == 'stag'`

`process.env.npm_lifecycle_event == 'preprod'`

自动化上线按环境运行不同的启动脚本予以区分开配置信息 `npm run stag` /  `npm run preprod`
