### ISSUE TITLE
egg-cluster的unix sock支持

### ISSUE THREAD

**Issue by jiuhuan** [eggjs/egg#435]
使用场景：当一台物理机没有docker的情况下跑多个app，app前面挂一层nginx-proxy，这个时候多个app的监听端口管理很麻烦，所以期望使用unix sock来解决。

翻阅egg-cluster的代码：
https://github.com/eggjs/egg-cluster/blob/master/lib/app_worker.js - 60行

```javascript
if (options.sticky) {
    ......
} else {
    server.listen(options.port);
}
```
修改后：
```javascript
if (options.sticky) {
    ......
} else {
    if(options.path){
         if(!options.isCluster){
               try{
                     fs.unlinkSync(options.path);
               }catch(e){}
         }
         const oldUmask = process.umask(0o00);
         server.listen(options.path, ()=> process.umask(oldUmask) );
    }else{
         server.listen(options.port);
    }
}
```

以上修改后的代码为思路，没实测，希望可以起到一点帮助作用。

**Comment by popomore** [comment]
感觉端口比 fd 管理更简单？多个 app 也需要多个 sock 吧。

**Comment by fengmk2** [comment]
nginx-proxy 通过 upstream 到 egg app 端口即可，跟 unix sock 稳定性无差别吧

**Comment by wsw0108** [comment]
1. 可能是强迫症 :)，看到多个端口被占用有点别扭；
2. 用unix socket，path里可以包含一些说明性的文字，port是全数字做不到；

**Comment by atian25** [comment]
@wsw0108 https://github.com/eggjs/egg/issues/484

**Comment by atian25** [comment]
@jiuhuan @wsw0108 这个功能已经支持了。
