### ISSUE TITLE
[RFC] http请求，header过长返回400错误，求解

### ISSUE THREAD

**Issue by nfjBill** [eggjs/egg#4351]
## 背景

> 目前由于请求header过长返回400错误，命令行里具体错误为
```
 error [HPE_HEADER_OVERFLOW] occurred: Parse Error: Header overflow
```

## 思路

> 网上查到说，需要使用`--max-http-header-size=80000`，在scripts中添加
```
...
"scripts": {
  "dev": "egg-bin dev -r egg-ts-helper/register --sticky --max-http-header-size=160000",
},
...
```
使用后无效果，求解

## 跟进

- [ ] some task
- [ ] PR URL

**Comment by atian25** [comment]
`--node-options--max-http-header-size=160000`

**Comment by nfjBill** [comment]
> --node-options--max-http-header-size=160000

感谢大神 在进一步问下 egg中能通过配置达到这个效果吗 例如在config.default.js中加些配置

**Comment by atian25** [comment]
这是 Node 的启动参数，只能通过启动命令或环境变量。
到 egg 这一步就已经晚了。

**Comment by nfjBill** [comment]
> 这是 Node 的启动参数，只能通过启动命令或环境变量。
> 到 egg 这一步就已经晚了。

请问环境变量如何设置

**Comment by atian25** [comment]
https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_node_options_options

看下 Node 文档呗

**Comment by nfjBill** [comment]
> https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_node_options_options
> 
> 看下 Node 文档呗

已成功 多谢大佬帮助
