### ISSUE TITLE
window下npm run autod报错

### ISSUE THREAD

**Issue by juukee** [eggjs/egg#4352]
## What happens?

window下npm run autod报错：
`[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".`

## 相关环境信息
- **操作系统**：Window
- **Node 版本**：v10.19.0
- **Egg 版本**：4.11.0

**Comment by hyj1991** [comment]
.autod.conf.js 里加个 `exclude` 字段，把比较大的无需扫描的文件夹忽略掉

**Comment by juukee** [comment]
不起作用，我全部把当前文件目录都加进去了，linux下面没有这个兼容问题。我是按照官网文档脚手架搭的启动，没有大文件啊，第一步就死了，，，

**Comment by atian25** [comment]
直接用 npm-check-updates 这些工具吧
