### ISSUE TITLE
egg-sequelize 8小时问题

### ISSUE THREAD

**Issue by xiaopenggithub** [eggjs/egg#4356]
## What happens?

直接保存数据，日期会少8小时，
在config.sequelize中配置timezone: '+08:00', 问题得以解决

在查询条件中根据日期between查询时，日期会多8小时（通过sql日志观察到），此时把timezone: '+08:00',去除，在sql日志看到between日期范围就是传递的原样日期（但不配置timezone: '+08:00'，会影响入库时间少8小时）

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
你的服务器时区问题吧，设置下 TZ 环境变量看看

**Comment by xiaopenggithub** [comment]
经检查，确如大佬所料，服务器时间有问题，同步时间后，正常了

**Comment by yaeSakuras** [comment]
请问如何设置，我也遇到了这个问题
