### ISSUE TITLE
如何非cluster启动

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#436]
看了下文档目前存在两种部署：https://eggjs.org/zh-cn/intro/quickstart.html

1. https://github.com/eggjs/examples/tree/master/hackernews 脚手架
2. egg-bin dev

两种默认都是`egg-cluster`启动， 请问如何非cluster如`express()` 直接启用一个egg服务器。

-------------------
需求场景：

由于机器资源紧缺，只有一套应用集群（2台机器），需要在同一个应用部署两个端口应用，一个对内服务，一个对外(80)。目前对外应用是egg 80端口，想在此机器上部署另外一套对内的service应用（也打算用egg）。

有两种部署方式：

1. 对内、对外egg均由`egg-cluster`启动
2. 对外egg由`egg-cluster`启动，其中在对外egg的一个进程中，再启动一个对内的egg的service服务（非cluster启动）

目前选择了第二种，但不清楚如何非cluster启动。

**Comment by popomore** [comment]
这个和 cluster 没关系吧，指定两个不同的端口就可以在一台服务器上部署了。

**Comment by atian25** [comment]
用不同的端口启动就好了，多几个进程，但没请求量的话，对服务器没啥损耗的。实在介意的话，内部的那个可以用 workers 参数开 2 个就好了

发自我的 iPhone

**Comment by johnnychen** [comment]
@atian25 嗯啊，就按您说的建议好了，独立均由egg-cluster启动，谢谢
