### ISSUE TITLE
egg官网 helper 文档更新

### ISSUE THREAD

**Issue by EasonQwQ** [eggjs/egg#4361]
## What happens?

想在ctx.helper下封装方法。在
https://eggjs.org/zh-cn/basics/app-start.html 中搜索 helper 
https://eggjs.org/api/Helper.html#main 
 Files from ${baseDir}/app/helper will be loaded to the prototype of Helper, then you can use all method on ctx.helper that is a instance of Helper. 
可是 最新的文档 是在app/extend下建立，没有更新，最新的文档也在官网上找不到。

**Comment by atian25** [comment]
`${baseDir}/app/helper` 这个是 API 文档吧，自动从源码分析出来的。

注释里面想表达的应该是 `${baseDir}/app/helper.js` 或 `${baseDir}/app/helper.ts`

来个 PR 吧~
