### ISSUE TITLE
egg.js启动时，使用mongoose创建数据出现重复

### ISSUE THREAD

**Issue by nightmareT** [eggjs/egg#4364]
```
export default async (app: Application) => {
    app.beforeStart(async () => {
        await createDefaultUser(app);
        await updateAreacode(app)
    });
};
```
代码如下，在beforeStart的时候为数据库创建了一些数据，出现了重复，用不同的服务器测试，虚拟机不会出现，物理机多核出现，初步怀疑是cluster执行问题，但是我已经在代码里把mongoose的model设置了unique， 实测下来，100组数组，每组大概被创建1-6次不等。请问下如何规避这个问题，比如有不使用cluster的生命周期函数，或者agent？ 大佬有什么官方推荐吗

**Comment by atian25** [comment]
因为 beforeStart 是每个进程执行一次的。用 Agent 也没用，因为如果你部署集群多机的话也会有这问题。

这种问题是框架层无法解决的，需要配合一些外部的服务。一般来说，数据库的初始化操作应该是在运维平台人工操作。

**Comment by nightmareT** [comment]
感觉大佬，明白这个意思了。  目前来看运维操作可能性不大，我初步考虑了两个方案，一是看看moogoose那边有没有什么方法规避重复数据，二是服务端给api 然后前端写脚本刷一下
