### ISSUE TITLE
如何在egg中使用log4js

### ISSUE THREAD

**Issue by xiaoaq** [eggjs/egg#4366]
如题，发现getLogger后，打印log根本无效

**Comment by atian25** [comment]
说明你大概率是用错了，提供最小可复现仓库，把问题解决了就好了。

**Comment by xiaoaq** [comment]
> 说明你大概率是用错了，提供最小可复现仓库，把问题解决了就好了。

https://github.com/xiaoaq/log4js_demo.git
最小demo

**Comment by atian25** [comment]
我的意思是直接 egg logger 的方式。

log4js 的用法我记得比较麻烦的，它需要在 master 进程里面做协调（也是 PM2 + log4js 经常问的一个问题好像）

在 egg 里面就直接用 egg logger 即可。

**Comment by xiaoaq** [comment]
> 我的意思是直接 egg logger 的方式。
> 
> log4js 的用法我记得比较麻烦的，它需要在 master 进程里面做协调（也是 PM2 + log4js 经常问的一个问题好像）
> 
> 在 egg 里面就直接用 egg logger 即可。

直接用egglogger,有办法设置我自己输出的日志都集中到一个文件中吗，而且不含系统日志。

**Comment by atian25** [comment]
你定义一个 bizLogger，所有的代码都调用它不就行了

**Comment by xiaoaq** [comment]
> 你定义一个 bizLogger，所有的代码都调用它不就行了

明白。还有一点，可以设置自动增加调用地方的文件吗名及接口名或行数信息吗？

**Comment by atian25** [comment]
js 做不到，除非你在每个调用的地方 new Error 来拿堆栈，很浪费性能。

打印行数没有任何意义啊，只有在出错的时候才需要，那时候有堆栈的。平时要行数干嘛
