### ISSUE TITLE
官网网站 快速入门 示例代码有误

### ISSUE THREAD

**Issue by jjeejj** [eggjs/egg#4369]
官网网站 快速入门 **编写 service** 小结 示例代码有点笔误， 该处应该是 **,** 用于定义两个变量

![image](https://user-images.githubusercontent.com/15176971/86464480-2a290f00-bd62-11ea-9717-d857a817b4e4.png)

**Comment by atian25** [comment]
没错，这里是解构取值

**Comment by jjeejj** [comment]
我知道是解构取值。 我没有打开那个链接，我以为是取了对象的2个属性，刚才打开那个链接 看了一下返回的值，才反应过来是 给返回值重新命名的，有点想当然了
