### ISSUE TITLE
sofa-rpc在阿里内部有实现吗

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#437]
文档地址：https://www.cloud.alipay.com/docs/content/AntCloud/46826 （需要蚂蚁金融云账号）

sofa-rpc是蚂蚁java内部的rpc实现，其中sofa对应蚂蚁nodejs框架chair，chair基于egg，那么sofa-rpc在阿里内部（egg/chair）有实现吗？

**Comment by fengmk2** [comment]
@johnnychen 这个目前蚂蚁内部是支持的，还没有开放出来。

**Comment by dead-horse** [comment]
sofa rpc 这一套是基于内部的 rpc 框架，其他环境无法使用

**Comment by johnnychen** [comment]
这个明白，sofa-rpc也没有开放的，只提供给使用金融云服务的人。我们是国泰产险，蚂蚁占51%股份，可否有什么方式进行支持呢？谢谢

**Comment by johnnychen** [comment]
我们部署的环境是蚂蚁金融云，也算是内部环境把-_-

**Comment by fengmk2** [comment]
@johnnychen 能否加我钉钉 18668079069

**Comment by fengmk2** [comment]
我来跟进。

**Comment by unique5945** [comment]
已经在实现 gRPC 协议了，后面会跟 chair 打通。
