### ISSUE TITLE
loadToApp 的 initializer 不符合预期

### ISSUE THREAD

**Issue by pengtikui** [eggjs/egg#4371]
## What happens?

loadToApp 这样用：

```javascript
app.loader.loadToApp(dir, target, {
  initializer(export) {
    if (typeof export === 'function') {
      return export(app);
    }
  },
});
```

然后加载的文件格式为：

```javascript
module.exports = (app) => {
  return () => {
    // do something
  }
}
```

这样就不会把返回的函数挂载到 app[target] 上，看了一下 [file_loader 的源码](https://github.com/eggjs/egg-core/blob/master/lib/loader/file_loader.js#L198)，是因为 call 默认为 true，initializer 的返回值还会重新赋值给 exports：`exports = initializer(exports, { path: fullpath, pathName });`，然后 exports 又被重新执行了一遍。

这样的结果并不符合预期，我想要的是把 initializer 返回的函数挂载到 app[target] 上，是不是 initializer 和 call 这两个选项有冲突，还是刻意这么设计的？

## Context
- **Node Version**: v12.17.0
- **Egg Version**: 2.26.1

**Comment by atian25** [comment]
没太看懂问题，如果你加载格式是一个 app 初始化的话，直接 call 就可以了，不需要再自定义 init。

可以提供下最小可复现仓库

**Comment by pengtikui** [comment]
我又想了想，可能是我对 initializer 这个方法理解有误，这个逻辑没什么问题，就先 Close 了
