### ISSUE TITLE
No valid exports main found for '/home/hhp/www/neau-back1/node_modules/koa'

### ISSUE THREAD

**Issue by Hhpon** [eggjs/egg#4372]
npm start 启动的时候提示这个问题？

今天服务器更新了代码，启动的时候报这个问题，然后我删除了node_modules，重新安装还是这个问题；我猜测是代码的问题，所以我把代码回滚到更新之前的，还是启动不了

![image](https://user-images.githubusercontent.com/33001067/86553383-2e7d4400-bf7d-11ea-89ee-3830a7120fbe.png)

**Comment by Hhpon** [comment]
难道是LF的问题？
##[error]   1:45   error  Expected linebreaks to be 'CRLF' but found 'LF'  linebreak-style
我把代码提到github上，github提示我这个问题

**Comment by Hhpon** [comment]
是node的版本问题，我原来的版本是13.x；我把版本改到14.x就解决啦

**Comment by bolingsun** [comment]
是哪个依赖导致的吗？egg官方文档说只需要8.x就可以了。我的也是13.x版本的node,部署服务器，同样报这个错。无奈只能升级到14.0.0就没问题。
