### ISSUE TITLE
不支持history单页应用模式？用koa的Middleware中间件koa-connect-history-api-fallback不管用。

### ISSUE THREAD

**Issue by au1996** [eggjs/egg#4373]
如题，
用vue写的单页应用路由方面使用history模式，
打包放到egg里，访问时从egg的路由入口进入是成功的，但是只要用了location.reload()刷新就会找不到页面。
需要从egg配置的路由入口重新进入才能找到页面。
看官网说是支持koa生态的中间件的，入参规范我也修改了下还是没用，
求大神解惑一下，谢谢~

**Comment by miser** [comment]
nginx 怎么配，同样的思路在egg上配置下就好了

**Comment by au1996** [comment]
> nginx 怎么配，同样的思路在egg上配置下就好了

才疏学浅，可以直接上代码吗？

**Comment by atian25** [comment]
配个 * 路由把所有的路径映射到入口页

**Comment by au1996** [comment]
感谢天猪老哥，一行代码解决；也感谢miser~谢谢二位

**Comment by BiscuitCoder** [comment]
> 感谢天猪老哥，一行代码解决；也感谢miser~谢谢二位

请问是怎么解决的呢？

**Comment by au1996** [comment]
> > 感谢天猪老哥，一行代码解决；也感谢miser~谢谢二位
> 
> 请问是怎么解决的呢？

```js
// project/app/router.js

/**
 * @param {Egg.Application} app - egg application
 */
module.exports = (app) => {
  const { router, controller } = app

  router.get('/xueyue', controller.xueyue.index) // 假设这是你的前端项目路由入口
  router.get('*', controller.xueyue.index) // 加上这行就行了
}
```
