### ISSUE TITLE
master-stdout.log日志会记录console.log内容

### ISSUE THREAD

**Issue by VincentWuShiChao** [eggjs/egg#4375]
## What happens?

看框架介绍说master-stdout.log日志是记录项目启动的内容，但是我这出现的是在项目运行期间，项目的打印日志其中console.log这种打印的全输入到了master-stdout.log里面。

想问下是哪里可以配置吗，还是怎么处理

## 相关环境信息
- **Egg 版本**：2.22.2

**Comment by atian25** [comment]
console 日志会自动输出到 process.stdout，而 egg-scripts 会收集所有的 stdout 写入文件。

你应该看看为啥应用里面用 console log 而不是 logger

**Comment by VincentWuShiChao** [comment]
@atian25  谢谢了解了
