### ISSUE TITLE
设置schedule的disable为`false`之后，在ubuntu生产环境`npm start`会报错

### ISSUE THREAD

**Issue by yyh1102** [eggjs/egg#4376]
## What happens?
![image](https://user-images.githubusercontent.com/10328169/86732404-f7815e00-c062-11ea-8b27-59c1a873f28b.png)

![image](https://user-images.githubusercontent.com/10328169/86732228-d3258180-c062-11ea-8791-97d974b8a1b1.png)

本地mac环境npm start是正常的。

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**: v12.13.0
- **Egg Version**: v2.26.1
- **Plugin Name**: egg-schedule
- **Plugin Version**:
- **Platform**:

**Comment by atian25** [comment]
https://github.com/eggjs/egg-schedule/blob/bce393f66f70add9151155d16b90942bab75e89b/lib/load_schedule.js#L9

提供下最小可复现仓库，从报错来看，跟 disabled 没啥关系

**Comment by yyh1102** [comment]
嗯，找到问题了。。`schedule`默认带了一个config.schedule的配置，我误把它覆盖掉了。
