### ISSUE TITLE
egg-socket.io 如何配合国际化

### ISSUE THREAD

**Issue by yyh1102** [eggjs/egg#4378]
## What happens?
浏览器端websocket不支持带header和cookie，在ws://连接的url里带?locale=zh-CN 也没效果。请问是否需要后端手动解析？

## 相关环境信息
- **操作系统**：Mac OS
- **Node 版本**：v12.14
- **Egg 版本**：最新

**Comment by ngot** [comment]
这个和 egg-socket.io 无关，可以到 https://github.com/socketio/socket.io/issues 提问
