### ISSUE TITLE
请问是否可以增加手动控制一个定时任务的开启和关闭

### ISSUE THREAD

**Issue by tuohuang** [eggjs/egg#4379]
## Background
有些时候不想要服务运行的时候就开启某个定时任务，而是需要手动的开始一个定时任务，并在某个时间停止掉这个定时任务，这种情况文档中没有提及这个功能。或者是否有其他办法来达到这种需求呢？

## Proposal
希望可以增加手动控制一个定时任务的开启和关闭

**Comment by atian25** [comment]
一个定时任务的调度系统，这属于业务功能，不是框架可以实现的。

实际情况下，你会有集群等多个机器，光靠单机上的框架是没法调度的。

egg-schedule 内置的 Timer 策略只是用来做一些日志清理的。 它提供了扩展能力，你的场景需要你自行扩展和调度。

**Comment by tuohuang** [comment]
明白了，谢谢解答
