### ISSUE TITLE
Eggjs 官网 css 文件 404 了

### ISSUE THREAD

**Issue by Sirormy** [eggjs/egg#4380]
<img width="933" alt="WX20200713-105643@2x" src="https://user-images.githubusercontent.com/6128447/87266338-91c82280-c4f7-11ea-957e-3ac6545fb708.png">

<img width="421" alt="WX20200713-105721@2x" src="https://user-images.githubusercontent.com/6128447/87266367-a4daf280-c4f7-11ea-927a-ddca0432745b.png">

**Comment by Sirormy** [comment]
看样子是不小心解析到 eggjs.github.io 去了

**Comment by darrenliuwei** [comment]
https://eggjs.github.io

https://eggjs.org

刚刚看了下，这两个网站的CSS样式文件都没有任何问题，都显示正常。

**Comment by Sirormy** [comment]
> https://eggjs.github.io
> 
> https://eggjs.org
> 
> 刚刚看了下，这两个网站的CSS样式文件都没有任何问题，都显示正常。

https://eggjs.github.io/css/index.css

你访问这个资源不是 404 吗，有点奇怪啊，我这边访问 eggjs.github.io 是个空壳，之前访问官网看控制台是显示解析到 gitpage 去了。

**Comment by darrenliuwei** [comment]
> > https://eggjs.github.io
> > https://eggjs.org
> > 刚刚看了下，这两个网站的CSS样式文件都没有任何问题，都显示正常。
> 
> https://eggjs.github.io/css/index.css
> 
> 你访问这个资源不是 404 吗，有点奇怪啊，我这边访问 eggjs.github.io 是个空壳，之前访问官网看控制台是显示解析到 gitpage 去了。

https://eggjs.github.io/css/index.css   这个网址确实是404，但是egg官网的样式没有受到任何影响，可以正常显示。

![WeChat Screenshot_20200713201624](https://user-images.githubusercontent.com/10508248/87303521-e72b2080-c545-11ea-84ab-4c80d31c0409.png)

**Comment by darrenliuwei** [comment]
![111](https://user-images.githubusercontent.com/10508248/87303705-2b1e2580-c546-11ea-8bbb-e77841f18627.png)
