### ISSUE TITLE
egg示例使用VSCode debug 启动过程中断点框消失

### ISSUE THREAD

**Issue by BresterWang** [eggjs/egg#4382]
## What happens?
debug 启动过程中断点框消失

## 最小可复现仓库
无

## 复现步骤，错误日志以及相关配置
新电脑，安装完环境后，使用官网的 快速初始化 语句生成了一个示例项目，使用eggjs扩展生成launch.json文件.
按F5启动debug，debug可以启动，启动过程中断点框消失.

## 相关环境信息
- **操作系统**：WIN10
- **Node 版本**：V12.18.2
- **Egg 版本**：V2.27.0
>PS D:\Code\FindMe>  ${env:NODE_OPTIONS}='--require "c:/Program Files/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.1608-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\Brester\\AppData\\Local\\Temp\\node-debug-callback-3205ddfc3b47e587"}'; & 'C:\Program Files\nodejs\npm.cmd' 'run' 'debug' '--'
Debugger listening on ws://127.0.0.1:50431/04f965d0-722b-41c9-bcaf-79b5dec236c2
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:50431/04f965d0-722b-41c9-Debugger listening on ws://127.0.0.1:50435/9698cb98-4c06-41f9-9f68-864d4468eef3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

> FindMe@1.0.0 debug D:\Code\FindMe
> egg-bin debug

>Debugger listening
PS D:\Code\FindMe> Debugger listening on ws://127.0.0.1:9229/f4a7b55e-79c7-439e-9a59-4eb14a4c4e41
For help, see: https://nodejs.org/en/docs/inspector
[egg-ts-helper] create typings\app\controller\index.d.ts (6ms)
[egg-ts-helper] create typings\config\index.d.ts (16ms)
[egg-ts-helper] create typings\config\plugin.d.ts (5ms)
[egg-ts-helper] create typings\app\index.d.ts (1ms)
2020-07-15 20:27:16,223 INFO 3540 [master] node version v12.18.2
2020-07-15 20:27:16,224 INFO 3540 [master] egg version 2.27.0
Debugger listening on ws://127.0.0.1:5800/03ab85d3-c9af-436a-95b8-e0dfdefb3318
For help, see: https://nodejs.org/en/docs/inspector
2020-07-15 20:27:17,515 INFO 3540 [master] agent_worker#1:2140 started (1287ms)
Debugger listening on ws://127.0.0.1:9230/957d248a-436a-4a1f-8359-46ca0b7e4fe1
For help, see: https://nodejs.org/en/docs/inspector
9230 opened
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
2020-07-15 20:27:18,989 INFO 3540 [master] egg started on http://127.0.0.1:7001 (2764ms)`

**Comment by atian25** [comment]
贴下 launch

**Comment by BresterWang** [comment]
> 贴下 launch

>{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Debug",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug",
                "--",
                "--inspect-brk"
            ],
            "console": "integratedTerminal",
            "restart": true,
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Test",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "test-local",
                "--",
                "--inspect-brk"
            ],
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Egg Attach to remote",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/usr/src/app",
            "address": "localhost",
            "protocol": "auto",
            "port": 9999
        }
    ]
}

>

**Comment by atian25** [comment]
从日志看不出问题，三个端口都已经 attach 上了。

修改代码后新的端口，也有配置 autoAttachChildProcesses 了。

我本地试了下是没问题的。你删除所有依赖再重新安装试试，不要锁版本。

**Comment by BresterWang** [comment]
> 从日志看不出问题，三个端口都已经 attach 上了。
> 
> 修改代码后新的端口，也有配置 autoAttachChildProcesses 了。
> 
> 我本地试了下是没问题的。你删除所有依赖再重新安装试试，不要锁版本。

谢谢！在其他电脑测试了，没有问题，我把开发环境重新安装一遍在试试吧

**Comment by BresterWang** [comment]
@atian25 我把电脑重置了，还是Egg示例，还是默认的Launch.json,现在按F5不能启动Debug了

Launch.json
>{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Debug",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "debug",
                "--",
                "--inspect-brk"
            ],
            "console": "integratedTerminal",
            "restart": true,
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "launch",
            "name": "Egg Test",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run",
                "test-local",
                "--",
                "--inspect-brk"
            ],
            "protocol": "auto",
            "port": 9229,
            "autoAttachChildProcesses": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Egg Attach to remote",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/usr/src/app",
            "address": "localhost",
            "protocol": "auto",
            "port": 9999
        }
    ]
}

输出：
>PS D:\Code\eggSimple>  ${env:NODE_OPTIONS}='--require "c:/Users/Curre/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.10824-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\Curre\\AppData\\Local\\Temp\\node-debug-callback-602ffaa75dccfff8"}'; & 'C:\Program Files\nodejs\npm.cmd' 'run' 'debug' '--'
Debugger listening on ws://127.0.0.1:49934/3e4c6ea9-9ee6-489a-a98f-799fc06082ce
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Debugger listening on ws://127.0.0.1:49934/3e4c6ea9-9ee6Debugger listening on ws://127.0.0.1:49941/3c48a8ef-ad27-41dc-b5ad-602ead9bf88b
For help, see: https://nodejs.org/en/docs/inspector
PS D:\Code\eggSimple>

问个其他问题: 为什么会输出这一段环境配置？
>>PS D:\Code\eggSimple>  ${env:NODE_OPTIONS}='--require "c:/Users/Curre/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" '; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.10824-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Users\\Curre\\AppData\\Local\\Temp\\node-debug-callback-602ffaa75dccfff8"}';

**Comment by BresterWang** [comment]
已解决，解决方法同 #4385
