### ISSUE TITLE
egg-session设置secure失败

### ISSUE THREAD

**Issue by 7kms** [eggjs/egg#4383]
## What happens?
为了满足最新chrome对cookies的处理.  在egg-session配置中加上`sameSite=none`,`secure=ture`.
`egg-cookies`插件中限制了只有https协议的请求才能加`secure=ture`, 否则直接报错.

## Mini Showcase Repository(REQUIRED)

体现bug的代码如下: 

https://github.com/eggjs/egg-cookies/blob/master/lib/cookies.js#L96

其中直接抛出了错误

## How To Reproduce

**Steps to reproduce the behavior:**
1. http方式启动egg服务
2. 配置egg-session如下, 其中`secure: true`:
    ```js
     exports.session = {
        maxAge: 7 * 24 * 3600 * 1000,
        key: 'xxxxxxx',
        httpOnly: true,
        encrypt: true,
        domain: 'xxx',
        signed: true,
        sameSite: 'none',
        secure: true,
    }
    ```
3. 设置session会失败

**Expected behavior**
1. 不应该直接`throw Error`, 给个警告代替
2. 因为egg应用一般都部署在内网中,  公网https请求到达网关后, 反向代理到内网. 而内网服务之间的通信很少采用https
3. 所以即使request不是https协议,  也应该放开对secure设置的限制

## Context
- **Node Version**:14.5.0
- **Egg Version**:^2.10.0
- **Plugin Name**:egg-cookies
- **Plugin Version**:2.4.2
- **Platform**:

**Comment by atian25** [comment]
> 因为egg应用一般都部署在内网中, 公网https请求到达网关后, 反向代理到内网. 而内网服务之间的通信很少采用https

你们反代那里是不是没传 x-forward-protocol 这个 header

**Comment by 7kms** [comment]
是的,  设置x-forward-protocol 之后能解决一部分场景.  

但是内网之间总有场景是直接使用http请求的,  还是希望能取消这个限制.

因为服务端设置secure的cookie本身没有什么错,  只是浏览器会去验证是否安全.

只要cookie设置是合法的, 即使不满足浏览器的安全策略, 提示一下就可以了, 报错级别是不是太高了.

另外在本地开发和测试的时候也不方便,  本地或者测试用http去访问该服务, 就直接报错.  或者给开发者一个选项也好

**Comment by atian25** [comment]
这不是 Egg 的限制，而是 HTTP 规范来着：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by 7kms** [comment]
好吧.  MDN上是说客户端代理要遵守规范. 并没有说服务端不让这样设置.  我暂时也没有找到关于服务端设置的规范.

要是确实没有必要改,  这个issue差不多就close掉吧

**Comment by atian25** [comment]
> 另外在本地开发和测试的时候也不方便, 本地或者测试用http去访问该服务, 就直接报错. 或者给开发者一个选项也好

你可以写个中间件处理下，本地欺骗下 koa， 让 ctx.secure 为 true
