### ISSUE TITLE
vscode 按f5不能调试egg

### ISSUE THREAD

**Issue by developeryvan** [eggjs/egg#4385]
## What happens?
vscode 按f5不能调试egg

## 最小可复现仓库
拉取最新的 npm init egg --type=simple 代码

## 复现步骤，错误日志以及相关配置

npm run dev 正常启动
![image](https://user-images.githubusercontent.com/47513562/87650151-ca7c2c00-c783-11ea-8926-afac413a5e5c.png)

f5 错误
![image](https://user-images.githubusercontent.com/47513562/87650285-fb5c6100-c783-11ea-86c7-65a50909b288.png)

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：12.18.2
- **Egg 版本**：2.27

**Comment by atian25** [comment]
跟 egg 其实关系不大，就是 Node 的多进程调试。
从你截图来看，只 attach 了 master 和 agent 就挂住了。
可能跟你的操作系统之类的环境有关，这块我们无能为力。egg-bin 就是帮你把 --inspect 传给了进程，如何 attach 都是 Node 和 VSCode 本身的能力，egg 没做任何事。

你可以试下里面提到的 https://github.com/atian25/blog/issues/25 的 autoattach 方式。

**Comment by developeryvan** [comment]
我这2台电脑都这样,也是最近2天才出现,怀疑跟vscode 有关,
我这用原生的调试配置可以启动,但不确定有没有副作用.
![image](https://user-images.githubusercontent.com/47513562/87652747-30b67e00-c787-11ea-94a1-8a73ef85a753.png)
![image](https://user-images.githubusercontent.com/47513562/87652873-56dc1e00-c787-11ea-9d95-1636d538efd2.png)

**Comment by atian25** [comment]
"autoAttachChildProcesses": true,
"restart": true,

这两个配置需要的，一个是自动 attach 子进程（否则你只 attach 到 master），一个是修改代码后重启的 worker 也会被 attach 上。

**Comment by developeryvan** [comment]
> 跟 egg 其实关系不大，就是 Node 的多进程调试。
> 从你截图来看，只 attach 了 master 和 agent 就挂住了。
> 可能跟你的操作系统之类的环境有关，这块我们无能为力。egg-bin 就是帮你把 --inspect 传给了进程，如何 attach 都是 Node 和 VSCode 本身的能力，egg 没做任何事。
> 
> 你可以试下里面提到的 [atian25/blog#25](https://github.com/atian25/blog/issues/25) 的 autoattach 方式。

找到原因了,是因为win10 vscode更新debug,不使用这个新模式就好了.
![image](https://user-images.githubusercontent.com/47513562/87675678-44271080-c7aa-11ea-9bb4-c008d8cf4c65.png)

**Comment by David-Sam** [comment]
![image](https://user-images.githubusercontent.com/14285875/88249989-b2069700-ccd8-11ea-82bc-fa0e7a4965c0.png)
vscode把这去掉即可,真坑

**Comment by chenbingchang** [comment]
太感谢了！

**Comment by leo2022** [comment]
太感谢了
