### ISSUE TITLE
【Discuss】 About DNSCacheHttpClient

### ISSUE THREAD

**Issue by Gcaufy** [eggjs/egg#4389]
1. `dnsCacheLookupInterval` and `dnsCacheMaxLength`
https://github.com/eggjs/egg/blob/333d7b8f540a413c3d253a21a079113165065036/lib/core/dnscache_httpclient.js#L73-L80

When cache expired, do dns look.
When now is greater than interval time, do dns look.
Actually they are the same logic. then why not to keep just one config.

2. logger.info
https://github.com/eggjs/egg/blob/333d7b8f540a413c3d253a21a079113165065036/lib/core/dnscache_httpclient.js#L13
What's your expect interval time? 10sec? That means print this log every 10 sec.
It's really unnecessary to show use I did a dns lookup in `INFO` level, suggest to change it to `DEBUG`

3.  Throw Error
https://github.com/eggjs/egg/blob/333d7b8f540a413c3d253a21a079113165065036/lib/core/dnscache_httpclient.js#L97
When doing a dns lookup, it throw an error if lookup failed.
The main point here is to send a http request, if dns lookup failed, we still can use cache dns, or just use system dns lookup. and if the http request failed, then we can throw an error. 
So I think dns lookup failed should only gives an warning, and user can continue on the http request sending.

**Comment by jjeejj** [comment]
1：`dnsCacheLookupInterval` and `dnsCacheMaxLength`

the two config items represent different meanings

`dnsCacheMaxLength`:  `LRU` queue length,  Indicates whether the  dns record exists
`dnsCacheLookupInterval`: Indicates whether the dns record valid， the time interval

through the code, we can know :
if dns record exist and time interval exceeded（`dnsCacheLookupInterval config value`）, exec **UPDA_DNS** function but not **await**,  it return the old dns record.


if dns record not exist, await **UPDA_DNS** function completed and then return.

2: logger.info

I agree with you . In production env , i dno't care dns lookup log . Only in development env , verify whether is it correct.

3：Throw Error

use `dns.lookup` query dns record. dns.lookup() use the operating system facilities . 

If the DNS resolve at the operating system level still fails, I think there is a problem in most cases. Throw the error as soon as possible, pay attention to it as soon as possible, and handle it as soon as possible

**Comment by dead-horse** [comment]
I think @jjeejj already explained it very well. But I think keep the info log can help us better troubleshoot possible anomalies in our production environment. It write to the core logger so it won't bother you if you do not in trouble.

**Comment by dead-horse** [comment]
The logger logic will only log one line in 10s with different domains, I think it shouldn't be too much.
