### ISSUE TITLE
重新打开浏览器，session还在

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#439]
重新打开浏览器，session怎么还在

**Comment by atian25** [comment]
存 cookie 了啊

**Comment by atian25** [comment]
看了egg-session 源码，https://github.com/eggjs/egg-session

**Comment by zlab** [comment]
java session在关闭浏览器，再重新打开，就是一个新的session了

**Comment by zlab** [comment]
@atian25

**Comment by whxaxes** [comment]
```javascript
exports.session = {
  maxAge: 24 * 3600 * 1000, // ms
  key: 'EGG_SESS',
  httpOnly: true,
  encrypt: true,
}
```
默认配置里，cookie 是会存 1 天的，所以sessionId在你关掉浏览器再打开后还会存在。

你 java session 在关闭浏览器就再打开就没session是因为你设置 sessionId 到 cookie 的时候没有设 expired time 吧？所以关掉浏览器后 sessionId 就被清掉了，自然就会重新创建一个 sessionId ，那么就是一个新的 session 了

**Comment by zlab** [comment]
> cookie.setMaxAge(0);//不记录cookie
 cookie.setMaxAge(-1);//会话级cookie，关闭浏览器失效
 cookie.setMaxAge(60*60);//过期时间为1小时

### 能否达到以上效果
