### ISSUE TITLE
代理转发

### ISSUE THREAD

**Issue by caojiahui123** [eggjs/egg#4391]
程序需要在iframe嵌入一个别的网站页面，这个页面由于设置了X-Frame-Options，导致无法加载；现在是想通过egg，在转发的时候进行处理headers，但是这个egg.js转发不成功；代码如下
![image](https://user-images.githubusercontent.com/32897279/88157032-d14fe680-cc3c-11ea-87dc-3a637af9ff7e.png)

**Comment by atian25** [comment]
因为你代码写错了呗，报错不是有么。 http-proxy 没用好，看起来是初始化很多个了。

**Comment by atian25** [comment]
可以参考下 https://github.com/eggjs/egg-http-proxy 的实现

**Comment by caojiahui123** [comment]
> 可以参考下 https://github.com/eggjs/egg-http-proxy 的实现

![image](https://user-images.githubusercontent.com/32897279/88245171-bd51c680-ccc8-11ea-8a44-bcfd546dfbb6.png)
感谢指点，根据你的描述，修改之后，找不到这个地址

**Comment by atian25** [comment]
自己 debug 调试吧，源码都在那了。看看是为啥 404 呗，是请求侧还是响应侧。
