### ISSUE TITLE
两个插件如何定义初始化前后顺序

### ISSUE THREAD

**Issue by xiaozhongliu** [eggjs/egg#4392]
## What happens?
两个插件有依赖关系, 一个插件必须初始化之后, 再初始化另一个插件.
现在的顺序不对, 如何明确定义这个顺序?

## 最小可复现仓库
两个插件初始化逻辑都在各自app.ts的以下代码块中:
```js
export default async (app: Application) => {
    ...
}
```

## 复现步骤，错误日志以及相关配置
无需提供

## 相关环境信息
- **操作系统**：MacOS Catalina
- **Node 版本**：10.15.3
- **Egg 版本**：2.27.0

**Comment by jjeejj** [comment]
插件不是有依赖管理的机制吗？  可以控制加载顺序的
![image](https://user-images.githubusercontent.com/15176971/88246278-99907f80-cccc-11ea-952f-2c90b64e5205.png)

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/lifecycle.html#async-didload

其实用声明周期就可以了，在插件 B 里面 await 插件 A 的某个对象的 ready。

可以继承下 sdk-base 这个库

**Comment by xiaozhongliu** [comment]
@jjeejj 这个文档找到了, 试了不起作用, 或许是因为内部是非异步逻辑?

@atian25 嗯现在用的你说的第三个开始支持异步的前两个事件来控制先后了, 已经ok了. 🤝
