### ISSUE TITLE
Egg里怎么使用sqlite，请问有example么？

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4394]
## Background
我现在想用一个不需要安装的数据库，目前选定的sqlite，
目前在example里找了下，没有这方面的example，
并且npm上sqlite包也特别多，不知道用哪个好？
并且直接在egg程序里npm install使用是有问题的，想具体了解下，怎么用

**Comment by atian25** [comment]
sqlite 是基于文件的，你集群多机部署就会有问题了。

具体用起来没啥区别，自行处理。注意下 egg 正式启动是多进程的就好了。
