### ISSUE TITLE
egg里安装lowdb，然后运行后，根目录下会出现一大批文件？

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4395]
## What happens?

egg里安装lowdb，然后运行后，根目录下会出现一大批文件？
![image](https://user-images.githubusercontent.com/5111701/88373580-abf0e300-cdca-11ea-87ea-783c3bef260b.png)
![image](https://user-images.githubusercontent.com/5111701/88373733-f2ded880-cdca-11ea-9874-c1e9b3820c0c.png)
在electron里，就没有这种情况

## 使用方式
npm i lowdb

## Context
- **Node Version**:  v12.14.0
- **Egg Version**:  ^1.10.1
- **Plugin Name**: lowdb         https://github.com/typicode/lowdb
- **Plugin Version**: 1.0.0
- **Platform**: win7

**Comment by atian25** [comment]
跟 egg 没啥关系

**Comment by pxim** [comment]
确实没关系，我知道原因了
