### ISSUE TITLE
如何设置静态页面的启动链接为跟目录，而不是public？

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4396]
## What happens?

比如我现在用egg server启动了一个服务，并且服务地址是 http://127.0.0.1:9010

我现在用antd pro v5做了个后台管理系统页面，因为这个框架里  build后 ，api访问方式是 默认的url+api接口的形式，比如当前打开页面的服务是http://127.0.0.1:3000 ，我在这个框架里和后端链接的接口就是 http://127.0.0.1:3000/api/currentUser 。 既然这样我就访问不到 9010下的接口，因此我想把  antd pro v5 build后的页面，放在egg里，作为静态页面启动。但是目前egg里的静态路径对我来说，存在问题，因为他，多套一层public，导致我的资源路径错误。如下图

![image](https://user-images.githubusercontent.com/5111701/88607535-139c7c00-d0b2-11ea-8030-81ba9ff85afd.png)

![image](https://user-images.githubusercontent.com/5111701/88607515-05e6f680-d0b2-11ea-914c-e0465ce3224e.png)
我想通过http://127.0.0.1:9010/ 直接访问我的静态页面，而不是 http://127.0.0.1:9010/public/index.html 

下图是我 egg程序目录
![image](https://user-images.githubusercontent.com/5111701/88607897-f916d280-d0b2-11ea-8463-f854712337fd.png)
![image](https://user-images.githubusercontent.com/5111701/88607908-016f0d80-d0b3-11ea-9c18-44e960784fbc.png)

antd pro里关于这个问题的iuuse
https://github.com/ant-design/ant-design-pro/issues/7092

## 相关环境信息
- **操作系统**：win7
- **Node 版本**：v12.14.0
- **Egg 版本**：^1.10.1

**Comment by atian25** [comment]
文件放置的目录和最终 url 的 prefix 是两回事。

看下 egg-static 的配置即可。

**Comment by pxim** [comment]
> 文件放置的目录和最终 url 的 prefix 是两回事。
> 
> 看下 egg-static 的配置即可。

![image](https://user-images.githubusercontent.com/5111701/88610194-9d4f4800-d0b8-11ea-9053-17d7d3ef8508.png)
![image](https://user-images.githubusercontent.com/5111701/88610231-b2c47200-d0b8-11ea-86b5-1d23e34ab2f2.png)
看了配置，并且设置了，但是还是必须  http://127.0.0.1:9010/index.html 访问才行，不能 http://127.0.0.1:9010  =   http://127.0.0.1:9010/index.html  ，但是这样 antd pro的路由会有问题

**Comment by atian25** [comment]
自己加个路由映射就好了。

**Comment by pxim** [comment]
> 自己加个路由映射就好了。

加载哪个里面？egg里？

**Comment by pxim** [comment]
> 自己加个路由映射就好了。

egg-example有这个案例么，我对这个不太熟，不是主方面

**Comment by atian25** [comment]
看下 Router 文档就知道了。

**Comment by JasinYip** [comment]
https://eggjs.org/zh-cn/basics/router.html#%E9%87%8D%E5%AE%9A%E5%90%91

**Comment by pxim** [comment]
> 看下 Router 文档，都是一个一个设置的，不能通配设置么，因为我也不知道antd pro里一共有多少个路由页面。

**Comment by JasinYip** [comment]
> 看下 Router 文档，都是一个一个设置的，不能通配设置么，因为我也不知道antd pro里一共有多少个路由页面。

用通配符 `*`，比如

```
// router.js
app.get('*', controller.home.test);
```

**Comment by atian25** [comment]
@JasinYip 改 prefix 后其实已经都是 / 了，他这里只是想 index.html 也映射到 / 而已，来个 redirect 之类的就好了。

**Comment by pxim** [comment]
> @JasinYip 改 prefix 后其实已经都是 / 了，他这里只是想 index.html 也映射到 / 而已，来个 redirect 之类的就好了。

请问大佬，这个该怎么通配设置，不会有bug，

**Comment by atian25** [comment]
这是你不会用，不是 bug。类似 `app.router.redirect('/index.html', '/')` 之类的，自己补下看 Router 文档搞吧。

**Comment by pxim** [comment]
> app.router.redirect('/index.html', '/')

确实是我不会用这个, 谢谢大佬指点。

` app.router.redirect('/', '/index.html'); ` 这样，暂时可以了。
