### ISSUE TITLE
封装的 framework 里面的 app.js 消失了

### ISSUE THREAD

**Issue by vmaki** [eggjs/egg#4397]
前提：我自己封装了一个 framework egg-maki-framework，并在其中写了一些全局中间件跟基础的controller 和 service，然后通过 framework 的 app.js 继承；

现在：通过 npm init egg --type=simple 新建了一个应用使用并安装了我自己封装的 framework ；但是成功安装后发现 framework 中的 app.js 消失了；

问题：因为是第一次接触 node 的，所以不知道这是 node 的限制，还是 egg 的限制，还是出bug?

Node Version: v 12.18.0
Egg Version: 2.15.1
Platform: windows 10

**Comment by atian25** [comment]
跟 egg 没啥关系，大概率是你发 npm 包的时候，没把 app.js 发上去。 检查下 package.json 里面的 files，然后看下 npm 对应文档学习下。
