### ISSUE TITLE
希望可以改进开发者体验，控制台报错改进一下，报错信息不友好，无法精准定位

### ISSUE THREAD

**Issue by Seovos** [eggjs/egg#4401]
希望可以改进开发者体验，控制台报错改进一下，报错信息不友好，无法精准定位

**Comment by JasinYip** [comment]
可以更具体地说一下是什么样的报错不好定位吗？

**Comment by atian25** [comment]
希望反馈 issue 的时候，改进下反馈信息，这样的反馈信息不友好，我们无法精准定位你想问啥
