### ISSUE TITLE
egg-bin dev在离线脱网环境下，运行会报错！

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4402]
## What happens?

我的客户，他们实验室是脱离外网环境，只用局域网，现在egg-bin没有外网的话，会引起请求 egg lastet错误。
我该怎么解决？

## 复现步骤，错误日志以及相关配置

1. 关闭外网
2. 运行 `npm run dev`

![image](https://user-images.githubusercontent.com/5111701/88875796-86ddf380-d254-11ea-8bde-073887c6ab81.png)
![image](https://user-images.githubusercontent.com/5111701/88875842-98bf9680-d254-11ea-91bc-6379d7b167ca.png)
![image](https://user-images.githubusercontent.com/5111701/88875871-a412c200-d254-11ea-89d1-338c182cbea3.png)

## 相关环境信息
- **操作系统**：win7
- **Node 版本**：v14.x
- **Egg 版本**：v1.10.1

**Comment by atian25** [comment]
跟 egg-bin 没关系，你这个看起来是有一个 `/` 的路由，里面调用了 curl 请求一个 npm 的地址吧，检查下你们的业务逻辑。

**Comment by pxim** [comment]
> 跟 egg-bin 没关系，你这个看起来是有一个 `/` 的路由，里面调用了 curl 请求一个 npm 的地址吧，检查下你们的业务逻辑。

找到了，确实是这个原因，谢谢
