### ISSUE TITLE
HttpClient 方法能否设置请求的代理地址

### ISSUE THREAD

**Issue by chenjie-cnooc** [eggjs/egg#4404]
类似于在命令行中使用curl命令

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/httpclient.html#%E6%8A%93%E5%8C%85%E8%B0%83%E8%AF%95

**Comment by chenjie-cnooc** [comment]
非常感谢，如果是部分接口使用道理如下的设置可以么？
 let response=await this.ctx.curl(url,{                
                method:"get",
                contentType:"json",
                timeout:20000,         
                dataType:"json",
                request: {
                    enableProxy: true,
                    rejectUnauthorized: false,
                    proxy: "http://<ip>:<port>",
                } 
            });

**Comment by atian25** [comment]
部分不需要加 request 这个节点，直接放出来。
去看下 urllib 这个库就知道了。

**Comment by chenjie-cnooc** [comment]
https://github.com/node-modules/urllib#api-doc  ，非常感谢。
