### ISSUE TITLE
typescript 的配置控制存在一词多意

### ISSUE THREAD

**Issue by suntopo** [eggjs/egg#4405]
## Background
egg-script 启动的时候读取了项目目录下的 egg.typescript 来作为是否开启sourcemap的控制项，这个地方存在一词多用的情况。

## Proposal
建议把 sourcemap 和 typescript 控制分开，更语义化。

**Comment by atian25** [comment]
我理解，应该是包含关系，用 Typescript 的时候，必然要隐含 sourcemap 的意思，否则堆栈就不对了。
不存在开启了 ts 但不开 sourcemap 的情况。
