### ISSUE TITLE
虚拟机环境，egg-bin dev热更新失效

### ISSUE THREAD

**Issue by jiangfengfz** [eggjs/egg#4408]
#4279  What happens?
Mac本地环境下，用vagrant+virtualbox安装centos7虚拟机，
在虚拟机中docker部署eggjs开发模式，并做了目录映射，发现热更新失效。
1、vscode 修改代码，进入docker eggjs容器内确认代码文件已修改，但eggjs无法自动更新。
2、直接进入docker eggjs容器内确修改代码文件并保存，发现eggjs可以自动更新

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置

 "dev": "egg-bin dev",

## 相关环境信息
- **操作系统**：
Mac 10.15.5
- **Node 版本**：
Dockerfile：
FROM node:alpine
- **Egg 版本**：
 "egg": "^2.27.0",

**Comment by atian25** [comment]
Node 的自带 FS API 对 vagrant 的方式兼容性不好，可以装个 https://github.com/eggjs/egg-watcher-chokidar 插件试试
