### ISSUE TITLE
上传文件流报错 missing csrf token

### ISSUE THREAD

**Issue by hunanzhoujielun** [eggjs/egg#4416]
## What happens?

在network上看x-csrf-token请求头已经携带上了，服务端一直报错没有x-csrf-token 。

![image](https://user-images.githubusercontent.com/48546899/89703675-6c57f880-d97f-11ea-9eae-bcf2a4dfadce.png)
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**： 14.4.0
- **Egg 版本**：2.27.0

**Comment by atian25** [comment]
自行调试下 https://github.com/eggjs/egg-security/blob/master/lib/middlewares/csrf.js

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
