### ISSUE TITLE
[Feature Request] egg-logger 自定义默认的 egg-logger paddingMessage

### ISSUE THREAD

**Issue by kamilic** [eggjs/egg#4417]
## Background
我想增加一写自定义的全局 paddingMessage 到框架自带的 logger 上。 
但是看源码这些 paddingMessage 已经写死了 (https://github.com/eggjs/egg-logger/blob/master/lib/egg/context_logger.js#L18)。
能否在配置项中让用户配置希望增加的 paddingMessage 或者是覆盖掉默认的 paddingMessage 呢？

我知道可以通过自定义 CustomLogger 来处理，但是我这边希望官方的日志插件能够支持这个功能，如果有需要我可以帮忙提交代码。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-logger/blob/master/lib/egg/logger.js#L46

**Comment by jjeejj** [comment]
@kamilic  你说的应该是这个参数  `contextFormatter`
```js
contextFormatter(meta) {
     return `[${meta.date}] [${meta.ctx.method} ${meta.ctx.url}] ${meta.message}`;
},
```

可以看到 `contextFormatter`  是在 `egg-logger` 中这个位置起的作用

https://github.com/eggjs/egg-logger/blob/a539ffebfb2171927fb18d70ee44ffe0f46db2af/lib/utils.js#L79

**Comment by kamilic** [comment]
@atian25 你发的链接表达的意思是通过配置 `contextFormatter` 来替代掉传入` contextFormatter` 的参数 `meta.paddingMessage ` 吗？
我的想法是能否提供个 paddingMessage 的配置来让我更换掉内部的默认行为。

大概是这个样子吧
```javascript
exports.logger = {
     paddingMessage: (ctx) => JSON.stringify({ ip: ctx.ip })
}
```

**Comment by kamilic** [comment]
@jjeejj 我看了下代码知道了，这个方式也能达到我的需求，谢谢！

**Comment by atian25** [comment]
直接用 contextFormatter 吧，paddingMessage 提供出来也省不了两行代码。
