### ISSUE TITLE
Docker部署scripts启动失败

### ISSUE THREAD

**Issue by xiaoaq** [eggjs/egg#4419]
![image](https://user-images.githubusercontent.com/33898493/90083734-e99bb880-dd45-11ea-974b-4cadf4bd28f2.png)

**Comment by xiaoaq** [comment]
win10本地启动正常

**Comment by hyj1991** [comment]
你使用了 v13.x  的 node 版本吧

**Comment by hyj1991** [comment]
实际上 v13.0.0 - v13.7.0 之间的版本对 package.json 里的 exports 字段处理有问题导致的这个问题，上游已经修复了，你可以试试看

**Comment by xiaoaq** [comment]
![image](https://user-images.githubusercontent.com/33898493/90084397-cf62da00-dd47-11ea-8922-49ea12d1e9be.png)
调整成14+也还是一样

**Comment by hyj1991** [comment]
你改 engines 线上会自己安装 v14 的 runtime？

**Comment by hyj1991** [comment]
启动命令前加一个 `node -v && ` 这种，查看你线上实际跑的 runtime 版本

**Comment by atian25** [comment]
> 启动命令前加一个 `node -v && ` 这种，查看你线上实际跑的 runtime 版本

stdout 日志里面有打印的。如果有 pre-project 的 node runtime 的话，node -v 是全局的

**Comment by xiaoaq** [comment]
![Uploading image.png…]()

**Comment by xiaoaq** [comment]
这样吗

**Comment by atian25** [comment]
这种问题，自行排查吧，先检查自己的线上使用的 node 版本。
