### ISSUE TITLE
[Feature Request] egg-multipart插件，上传文件，文件名中文乱码

### ISSUE THREAD

**Issue by shanzemin** [eggjs/egg#4420]
比如我上传一个文件名为`测试.txt`的文件，返回内容如下
```
{
  field: 'file',
  filename: 'K�.txt',
  encoding: '7bit',
  mime: 'text/plain',
  fieldname: 'file',
  transferEncoding: '7bit',
  mimeType: 'text/plain',
  filepath: '/tmp/egg-multipart-tmp/manage/2020/08/13/14/04478617-6e3a-40a3-8291-32280d1a906e.txt'
}
```
filename为乱码，请问这个有处理方案吗？谢谢

**Comment by shanzemin** [comment]
https://github.com/shanzemin/upload-tmp
您好，这个是可复现的最小仓库地址

**Comment by atian25** [comment]
复现步骤？

**Comment by shanzemin** [comment]
> 复现步骤？

您好，复现步骤如下：
1. 启动项目
2. post请求调用api：http://localhost:7001/upload，form-data协议，上传文件，文件名为中文，比如：测试.txt
3. 查看返回结果中的name字段
谢谢！

**Comment by shanzemin** [comment]
![JUY6XQ5V3DCNCNYCM2FOJ@Q](https://user-images.githubusercontent.com/32158058/90114983-0fe14880-dd86-11ea-85b6-ac4055382cdf.png)

**Comment by atian25** [comment]
你先确认下是不是 POSTMAN 的问题，抓包看下

**Comment by shanzemin** [comment]
> 你先确认下是不是 POSTMAN 的问题，抓包看下

![2](https://user-images.githubusercontent.com/32158058/90118468-d8c16600-dd8a-11ea-9943-cec1fb5acfdb.png)
这个是抓包的截图；
另外我问下您，您复现的时候，是不会出现中文乱码是吗？采用的什么方式调用的？

**Comment by atian25** [comment]
从单测和 CURL 来看是没问题的，应该是你 POSTMAN 的问题，发送的时候就乱码了。

```js
  it('should POST /', async () => {
    const result = await app.httpRequest()
      .post('/upload')
      .attach('file', __dirname + '/测试.gif');

    assert(result.body[0].name === '测试.gif');
  });
```


```bash
curl -F "data=@/Users/tz/Desktop/测试.gif" localhost:7001/upload
```

**Comment by atian25** [comment]
PS： 你的 file 中间件是没啥意义的，要抽象代码也是写到 service，然后 Controller 直接调用。

还有 `readFileSync` 和 `statSync` 这些 Sync 的方法，是绝对不能用的，都换为 promise 的方式吧。

当然这两个跟你的问题没关系。

**Comment by shanzemin** [comment]
好的，非常感谢您的解答和帮助！

**Comment by shanzemin** [comment]
> PS： 你的 file 中间件是没啥意义的，要抽象代码也是写到 service，然后 Controller 直接调用。
> 
> 还有 `readFileSync` 和 `statSync` 这些 Sync 的方法，是绝对不能用的，都换为 promise 的方式吧。
> 
> 当然这两个跟你的问题没关系。

大佬，再冒昧的问一句，这两个方法为啥不能用？是有什么隐患吗？因为有部分生产环境已经使用这些方法很久了，暂时没发现有什么问题，期待回复。

**Comment by atian25** [comment]
Sync 是同步方法，会阻塞其他请求

**Comment by atian25** [comment]
这标题很特殊。。。 有可能是 co-busbusy 等基础库处理的时候没处理好。

为什么会有这种头呢，前端最好处理下。

**Comment by gensir** [comment]
问题出在 `busboy` 库，对`filename`进行了两次 `decode`，因为出现了 两次 `filename`。下面贴出我的修改
```git
diff --git a/node_modules/busboy/lib/types/multipart.js b/node_modules/busboy/lib/types/multipart.js
index b6d8e8b..d415020 100644
--- a/node_modules/busboy/lib/types/multipart.js
+++ b/node_modules/busboy/lib/types/multipart.js
@@ -156,6 +156,7 @@ function Multipart(boy, cfg) {
           if (RE_NAME.test(parsed[i][0])) {
             fieldname = decodeText(parsed[i][1], 'binary', 'utf8');
           } else if (RE_FILENAME.test(parsed[i][0])) {
+            if (filename !== undefined) continue;
             filename = decodeText(parsed[i][1], 'binary', 'utf8');
             if (!preservePath)
               filename = basename(filename);

```
