### ISSUE TITLE
schedule如何平滑重启？

### ISSUE THREAD

**Issue by KevinJay** [eggjs/egg#4422]
## What happens?
大佬们好， 我有个问题咨询一下，麻请指点。
假设我写了一个schedule，里面需要处理1000个数据（大约耗时5分钟）。脚本正好在运行时，我运行了egg-scripts  stop命令，此时schedule会立即暂停对数据的处理，导致没有处理完的数据就丢失了。  

请教一下，schedule如何才能平滑重启呢？

## 相关环境信息
- **操作系统**：centos7.6 
- **Node 版本**：V12.0.0
- **Egg 版本**：^2.15.1

**Comment by atian25** [comment]
这属于业务逻辑，需自行做持久化
