### ISSUE TITLE
this.app.config中的值只能被一个WORKER读取

### ISSUE THREAD

**Issue by KaneOne** [eggjs/egg#4425]
## What happens?
在定时器内获取一个Token，保存在app.config.token中，定时器模式为单WORKER，应用启动后，有两个WORKER，通过Controller读取config.token，一次可以正常读取，一次为空，交错出现。config内的值不同的WORKER是独立保存的吗，请问如何解决。

## 相关环境信息
- **操作系统**：CentOS Linux release 7.8.2003 (Core)
- **Node 版本**：v12.16.1
- **Egg 版本**：2.6.1

**Comment by popomore** [comment]
用 app.messenger 广播

**Comment by atian25** [comment]
Node 是 多进程 的，进程变量不能共享。

如果要共享，使用 redis 等即可。因为即使你单机共享了，集群情况下也一样有问题。

**Comment by KaneOne** [comment]
> Node 是 多进程 的，进程变量不能共享。
> 
> 如果要共享，使用 redis 等即可。因为即使你单机共享了，集群情况下也一样有问题。

感谢，是我对NODE底层了解不够，以为APP对象是全局共享的。

**Comment by KaneOne** [comment]
> app.messenger

感谢，我来试下:)
