### ISSUE TITLE
egg是否支持历史日志文件自动清理

### ISSUE THREAD

**Issue by xiaoaq** [eggjs/egg#4427]
如题,是否可配置只保留最近N天的日志文件?

**Comment by atian25** [comment]
看文档

**Comment by xiaoaq** [comment]
看了文档有分割相关，但貌似没找到我上述描述的自动清理的功能，所以过来确认下嘛，以防是我看漏了？
有的话就图个方便，没有就自行实现了

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/90458674-9c4a8d00-e131-11ea-8751-e45b0ebe679d.png)
