### ISSUE TITLE
老问题 cros 开启后无法ctx.body 为空

### ISSUE THREAD

**Issue by Hareis** [eggjs/egg#4428]
``plugin.js``开启
```
cors: {
		enable: true,
		package: 'egg-cors',
	}
```
``config.default.js``开启
```
 configObj.security = {
    csrf: {
      ignore:ctx=>ctx.request.url.indexOf('/dataCenter')>-1?true:false,
      // domainWhiteList: ["localhost:8000","127.0.0.1:8000"], //白名单
    },
  };
  configObj.cors = {
    origin: '*',
    // origin: 'http://localhost:8000,http://127.0.0.1:8000',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  };
```

这几个参数打开后 
![image](https://user-images.githubusercontent.com/11290701/90377878-3adfdb00-e0ab-11ea-9cb5-77e6b3a530b8.png)

![image](https://user-images.githubusercontent.com/11290701/90377929-4f23d800-e0ab-11ea-8e19-dbde0a65e015.png)

不能获取到ctx.body 的值

**Comment by JasinYip** [comment]
`this.ctx.body` 是用来设置返回 body 的，`this.ctx.request.body` 才是请求的 body。

顺带提一句，你那句 `?true:false` 是多余的……

**Comment by atian25** [comment]
实际上， indexOf 也是多余的，用 includes 即可。
