### ISSUE TITLE
封装容器，前面用letsencrypt三件套做https反向代理，OAuth2的redirect_uri却是http的，怎么办？

### ISSUE THREAD

**Issue by rushairer** [eggjs/egg#4430]
封装容器 ，启动方式npm run start，端口 7001，前面用letsencrypt三件套做https反向代理，OAuth2的redirect_uri却是http的，怎么办？
谢谢

config 里加  
```
        proxy: true,
        protocol: 'https',
```
也没效果。

**Comment by atian25** [comment]
https://github.com/koajs/koa/blob/master/lib/request.js#L404

**Comment by rushairer** [comment]
@atian25 谢谢
