### ISSUE TITLE
egg-sse，typescript版本

### ISSUE THREAD

**Issue by nightmareT** [eggjs/egg#4431]
最近考虑用sse实现几个需求，在使用egg-sse的时候，发现没有typescript版本 没有定义.d.ts文件，所以我这边ts版本的egg用不起来。不知道为啥这个模块没有更新，是大家都不太使用sse这种技术了呢，还是说有其他模块可以实现这个功能，想请教下各位，如果这东西好用的话，我也可以自己来把这个.d.ts文件封装下

**Comment by atian25** [comment]
https://github.com/garygchai/egg-sse#readme

非官方插件，可以找下作者，或者直接提 PR
