### ISSUE TITLE
how to use helper in app.js

### ISSUE THREAD

**Issue by koalaylj** [eggjs/egg#4437]
can i use helper in app.js file? 
how to access the helper module.

**Comment by atian25** [comment]
```js
const ctx = app.createAnonymousContext();
ctx.helper.xx();

// or

app.Helper.prototype.xx();
```

PS: `helper` is used for template render, maybe you need to custom your `app.utils`, see https://zhuanlan.zhihu.com/p/153322661 for more detail.
