### ISSUE TITLE
在agent中监听了process.on('SIGINT')事件后，spawn的detached模式失效

### ISSUE THREAD

**Issue by bigfactory** [eggjs/egg#4438]
## What happens?

在agent.js里面监听了process.on('SIGINT')事件，会造成spawn的deteched模式失效，这时候退出egg，spawn出来的子进程也会被kill掉

## 最小可复现仓库
https://github.com/bigfactory/egg-detached-bug

## 复现步骤，错误日志以及相关配置
运行 npm run dev

运行 ps aux | grep realtr 可以查看到 fork 出来的子进程

ctrl+c 结束 egg 进程，ps aux | grep realtr 发现 fork 出来的子进程也被kill掉了

去掉 agent.js 中的
```
    process.on('SIGINT', ()=>{
        console.log('SIGINT');
    });
```
则在 egg进程结束后，realtr 子进程不会被kill掉

## 相关环境信息
- **操作系统**：mac os 
- **Node 版本**：v10 or v12 
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
无法复现

**Comment by atian25** [comment]
hey, we need more information to follow up this issue.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
