### ISSUE TITLE
【egg】egg json obj 末尾逗号问题

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#444]
为什么egg的源码，demo，json obj 末尾都有逗号，而且不报错呢

**Comment by atian25** [comment]
js 语法里面默认逗号本来就是允许的语法啊。

至于为什么我们的 eslint 要求默认逗号，是因为这是我们的最佳实践：
- 末尾逗号，新增一个属性时，git diff 的 change 就只是一行
- git blame 的时候也能找到正确的修改者

**Comment by zlab** [comment]
谢谢
