### ISSUE TITLE
node-zone 通过引入该模块，解决了这边用nodejs开发的一个痛点。参数嵌套传递。

### ISSUE THREAD

**Issue by caihaibin1991** [eggjs/egg#4443]
https://www.npmjs.com/package/node-zone
通过该模块，实现了变量保存到"线程作用域"中，js在任意嵌套的情况下，可以通过简单的current.data.xx形式读取变量。
这边测试目前没发现什么问题，想了解下，这块东西是否会出现什么其它的冲突问题？该模块使用了 async_hooks.

**Comment by caihaibin1991** [comment]
```



// import { current } from 'node-zone'
const {current} = require('node-zone');
// a zone has a name, a parent, and data
console.log(
    current.name,   // "<root>"
    current.parent, // null
    current.data    // { __proto__: null }
)

// create a new child zone
const myZone = current.fork('my zone')

console.log(
    myZone.name,   // "my zone"
    myZone.parent, // current
    myZone.data    // { __proto__: current.data }
)

// run some code in it
myZone.run(() => {
    console.log(current.name) // "my zone"

    // zone is preserved in async functions
    process.nextTick(() => {
        console.log(current.name) // "my zone"
    })
});

(async function () {

    // return;
// run some code in it
     myZone.run(async () => {
        const {current} = require('node-zone');
        console.log(current.name) // "my zone"

        // zone is preserved in async functions
        process.nextTick(() => {
            console.log(current.name) // "my zone"
        })
    })
})();
console.log(current.name) // "<root>"
```

**Comment by atian25** [comment]
跟 egg 关系不大。

对于一个 Web 框架，不应该有太多线程之间交互的事，你应该通过 redis 等外部存储来解决。

不然你部署多集群的时候怎么办？

**Comment by caihaibin1991** [comment]
不是egg, 是nodejs. 比如，一个场景。原来开发的是针对一个商铺的功能，现在调整成多店铺。就多了shop_id，这样。要么提前约束好，全部函数调用时，要求传一个类型ctx的上下文变量。不然的话。突然一改，所有相关函数，都需要扩展这个参数。。这个对node来说相当痛苦。还有session里的用户信息等，如果某个类库需要读取某个用户信息，这样，从上往下，都得去扩展这个函数。如果引入node-zone,这个就好处理多了，变量放这个“域”里，需要的地方都去读。

**Comment by atian25** [comment]
如果是请求相关的，本来所有的类就会有 ctx 这个对象的，参考 https://zhuanlan.zhihu.com/p/153322661

一些工具类，才需要传进来，一般会约定一个 options。

你这个『域』其实就是全局变量，比起隐式的全局变量，我个人更倾向于显式的传递，只是代码层面如何简化而已（我们的做法就是请求链路的都通过 loader 去初始化，自然就有 ctx 了）

**Comment by caihaibin1991** [comment]
嗯。现在代码搬迁过来，原来封装的东西太多，全部去扩展ctx。时间不够，也担心，会导致不可预期的影响。标准做法确实是ctx处理。时间不太够。。。当做快速搬迁框架的一个应急处理哈。
