### ISSUE TITLE
[Feature Request] 有没有可能，把model、公共service拆分出去，以依赖方式加载？

### ISSUE THREAD

**Issue by ilaipi** [eggjs/egg#4445]
## Background
现在公司平台分为小程序、app、管理后台3个用户端口。不同的用户端口希望用不同的仓库来开发，但是同一个平台，所有的模型不能每个仓库都复制一遍。

## Proposal
希望能把模型和service，甚至一些公共的controller，都支持拆分到独立的仓库，然后通过依赖的方式，加入node_modules，然后egg可以完成node_modules内的加载

## Additional context
或者这样的场景目前的解决方案是？

**Comment by atian25** [comment]
service 支持放到插件， Controller 这些不支持，需要自己扩展 loader

**Comment by ilaipi** [comment]
> service 支持放到插件， Controller 这些不支持，需要自己扩展 loader

大佬们都不拆分的吗？这个场景是我想多啦？

**Comment by atian25** [comment]
没有什么公共 Controller 的场景，有的话可以用 Middleware，一样可以在插件里面吃掉。

**Comment by ilaipi** [comment]
公共controller的场景，比如基础数据的。每个用户端口可以用不同的路由，但是指向同一个方法。

我先研究一下插件吧
