### ISSUE TITLE
大佬们 希望对typescript的支持更加友好

### ISSUE THREAD

**Issue by MilesEmmm** [eggjs/egg#4447]
使用插件的时候 没有api提示稍微有点难受

**Comment by atian25** [comment]
希望 issue 的反馈更友好一点，宽泛的提问并无法解决实际问题。

1. 想用 TS 写 egg 的前提是，你的团队有能力基础的 TS 知识，能看懂 typings 问题，并能解决。
2. 遇到没有 dts 的插件，可以直接提 PR。或者自己业务里面写 declare merging 即可。
