### ISSUE TITLE
如何获取session_id？

### ISSUE THREAD

**Issue by cz1314520** [eggjs/egg#4449]
遇到一个问题，如何在第一次存储session后立即获取session_id。
`ctx.session.uid = 111;
 console.log('333333333',ctx.headers.cookie);`
这么获取的话第一次请求接口拿不到session_id,只有在之后的请求中才能获取到，所以不知道怎么获取。

然后还遇到一个问题，如下
`
ctx.session.uid = 111;
ctx.cookies.set("status","true");
`
这么做为什么会把**ctx.headers.cookie**中的session_id覆盖掉？？？

**Comment by atian25** [comment]
第一个问题，你请求都没返回，这时候 `ctx.headers.cookie` 是请求带来的 cookie，当然没写入啦。你在同一段逻辑里面都有要写入的值，直接用不就行了。

第二个问题，可以看下对应的 koa 插件源码，我不太记得了。

一般情况下，你应该是用 ctx.user 这样的东西的，不要依赖于 session，可以看下 egg-userservice
