### ISSUE TITLE
when EADDRINUSE, egg will restart again and again at prod mode

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#445]
* **Node Version**: v6.10.0
* **Egg Version**: 1.0.0-rc1
* **Platform**: mac

```bash
$ egg-init showcase --type=simple --silent
$ cd showcase && npm i
$ # start first
$ EGG_SERVER_ENV=prod node index.js &
$ # start second
$ EGG_SERVER_ENV=prod node index.js
```

**Comment by dead-horse** [comment]
生产环境本来就会不断重试，cfork 有一个重试上限的

**Comment by dead-horse** [comment]
监听端口已经超出了启动阶段，所以此时报错 master 进程不会退出，而是会重新 fork 一个 Worker

**Comment by popomore** [comment]
我试试，感觉 EADDRINUSE 之后不应该响应 listening 吧？

**Comment by popomore** [comment]
因为走的 disconnect，而 master 没做处理。cfork 会默认 refork。

https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L190

可以在 app worker 监听 error，然后 exit 退出。

PS: 还有个问题，就是一个 worker 退出时 master 就退出了，应该做到优雅退出。

**Comment by popomore** [comment]
这个可以晚点处理
