### ISSUE TITLE
mysql数据查询的数据时间字段格式不正确

### ISSUE THREAD

**Issue by kaqiinono** [eggjs/egg#4450]
## What happens?
![image](https://user-images.githubusercontent.com/11257690/92103611-caf38380-ee12-11ea-8bad-ae9f989840b7.png)

数据库的数据如下：
![image](https://user-images.githubusercontent.com/11257690/92103691-e199da80-ee12-11ea-9f58-89ab3604b7a8.png)

是否需要设置时区，如何设置。
数据库配置如下：
```
  config.mysql = {
    client: {
      host: 'xxx',
      port: '3306',
      user: 'xxx',
      password: 'xxx',
      database: 'xxx',
      debug: true,
    },
    app: true,
    agent: false,
  }

```

**Comment by atian25** [comment]
跟 egg 关系不大， env.TZ
