### ISSUE TITLE
配置自定义本地环境，但是无法监听文件更改

### ISSUE THREAD

**Issue by yulishuta** [eggjs/egg#4451]
## What happens?
我想配置一个自定义本地开发环境， 配置文件是 config.devlocal.js 

![image](https://user-images.githubusercontent.com/23233424/92124968-056c1900-ee31-11ea-9c86-206421e47bf1.png)

其中启动命令是：
    "dev_local": " EGG_SERVER_ENV=devlocal  DEBUG=anchor-server:* egg-bin dev"
可以正常启动，但是无法监测文件更改，请问我还需要配置什么信息 

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
mac 10.14.6
- **Node 版本**：
v10.16.0 
- **Egg 版本**：
2.6.1

**Comment by atian25** [comment]
为啥要自定义本地类型，很多插件都是约定了它的

**Comment by atian25** [comment]
egg-development 插件的 package.json 的 eggPlugin.env 声明了只会在 local 启动。

除非你在 plugin.js 覆盖掉，但不建议你这么干
