### ISSUE TITLE
创建新的service以后报错

### ISSUE THREAD

**Issue by kaqiinono** [eggjs/egg#4454]
## What happens?

创建新的service并重启项目后，调用新service的地方返回undefined，输出this.ctx.service，返回的只有旧的service类并没有新的。是有缓存吗？还是需要更新引用关系。
另外在service里新增方法也不能马上调用，也返回undefined
另外，想问一下，service类里只能定义async函数，不能定义普通函数吗？！

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
