### ISSUE TITLE
controller方法名不能用config这个名称，不然找不到路由

### ISSUE THREAD

**Issue by kookob** [eggjs/egg#4456]
router.get('/config', controller.home.config);

  async config() {
    const { ctx, app } = this;
    ctx.body = {};
  }

会报404，这是特性吗？

**Comment by atian25** [comment]
提供最小可复现仓库

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/utils/base_context_class.js

Controller 基类有这几个属性，估计是冲突了。
