### ISSUE TITLE
schedule定时任务执行异常

### ISSUE THREAD

**Issue by whenevery** [eggjs/egg#4458]
![image](https://user-images.githubusercontent.com/3378198/92355740-72283180-f117-11ea-8727-26c7de17c1f4.png)
近期生产环境遇到几个问题：
1、计划在00:00:00执行的日志分割任务 被推迟了几个小时， 晚上12点服务器没有特别的操作-后端的定时任务还没有开启。
2、在16核的服务器上看到定时任务的日志 注册了16次？- 日志里打印了16次register， 这个是正常的吗、
3、异常出现的socket closed 会导致内存泄漏且降不下去？- 看之前的issues定时任务会出现该异常， 16核的egg内存显示4g合适吗?
4、服务本身在线上已经运行接近2年，之前负载增加出现一些特别的问题

**Comment by JasinYip** [comment]
定时任务被推迟一般是由于线程阻塞了，可以沿这个思路检查一下是否有 CPU 密集型的计算正在执行，或者一些 sync 函数一直阻塞

**Comment by whenevery** [comment]
> 定时任务被推迟一般是由于线程阻塞了，可以沿这个思路检查一下是否有 CPU 密集型的计算正在执行，或者一些 sync 函数一直阻塞

本身egg项目没做什么业务功能，主要就是一些后端多接口整合一起返回，12点后端也没进行定时任务处理、 还有想问下16核的服务器里，docker限制多少内存比较合适 4G够吗？ 有时候负载高了自己降不下去

**Comment by atian25** [comment]
内存够不够要看你业务情况，用 alinode 分析就知道了。

**Comment by JasinYip** [comment]
> 本身egg项目没做什么业务功能，主要就是一些后端多接口整合一起返回，12点后端也没进行定时任务处理

你需要自己排查业务代码，如果确信是 egg 的问题请提供最小可复现代码
