### ISSUE TITLE
[Feature Request] architecture pictures

### ISSUE THREAD

**Issue by WJayWJay** [eggjs/egg#4459]
## Proposal
could you add some architecture pictures in docs?? for example, how to organize the modules?

**Comment by ChangedenCZD** [comment]
官网有的吧
[https://eggjs.org/zh-cn/basics/structure.html](https://eggjs.org/zh-cn/basics/structure.html)

**Comment by atian25** [comment]
need more information for the request

**Comment by WJayWJay** [comment]
> need more information for the request

How a request goes through the application ? let's know it's core modules relation in a minute

**Comment by atian25** [comment]
just as simple as Koa middleware, it's the only way to interact with request/response.

the rest such as controller/service is just some code organize struct.

`request --> middleware(pre) --> router --> controller --> service --> middleware(post) ---> response`
