### ISSUE TITLE
请问是否有完整的 egg 应用开发实例?

### ISSUE THREAD

**Issue by hsxiaoma** [eggjs/egg#446]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

对于 egg  的应用, 能否提供一个或更多的应用开发实例, 这样便于能更好的学习和使用 egg.

**Comment by atian25** [comment]
cnpm 官网的正在改造，但没那么快。

先看看 https://github.com/eggjs/examples 那边的示例吧

**Comment by hsxiaoma** [comment]
https://github.com/eggjs/examples 我已经看过了，过于单一，只能作为入门学习使用， 但要以实际开发过程中的使用， 需要对各种应用功能进行组合，如果有这样的综合实例， 对学习者会更有帮助。 也建议你们要为大家提供一个使用 EGG 开发项目实例的分享页面或者平台。

**Comment by atian25** [comment]
这块目前还没时间搞, cnpm 官网的那个 https://github.com/cnpm/web.cnpmjs.org 还没那么快.

欢迎社区贡献示例, 譬如改改 cnode, blog 啥的

**Comment by atian25** [comment]
@hacke2 
https://github.com/eggjs/egg-showcase-aliyun-blog 进度怎么样了?

**Comment by hacke2** [comment]
@hsxiaoma  https://github.com/eggjs/egg-showcase-aliyun-blog/tree/markdown-editor 这边是一个博客例子，如果你没有阿里云oss（上传图片需要用到），你可以先把 `oss` 开关关掉。 @atian25 阿里云的配置和申请这一套我觉得最好找一个阿里云的同学搞搞

**Comment by popomore** [comment]
egg 刚开源，真正 real world 的应用还比较少，过段时间应该能看到一些，比如上面提到的  https://github.com/cnpm/web.cnpmjs.org

**Comment by atian25** [comment]
应该说外部的 real world 的应用还比较少，阿里内部都已经是基于 egg 的上层框架的了。

**Comment by popomore** [comment]
但是他看不到
