### ISSUE TITLE
模板中的script标签中怎么使用controller传进来的数据？

### ISSUE THREAD

**Issue by bhgx** [eggjs/egg#4461]
我想在模板的script标签中把某些数据绑定到window的某个属性上，但一直报错，请问这种场景应该怎么解决？
或者是有没有其它方式可以把数据绑定到window对象上？

我的代码demo如下
```
<script type="text/javascript">
    window.aaa = {{helper.info}}
</script>
```

**Comment by JasinYip** [comment]
文档中有模板渲染说明
https://eggjs.org/zh-cn/core/view.html
