### ISSUE TITLE
这个egg.js项目不会像antd一样到圣诞节那天搞个彩蛋吧！

### ISSUE THREAD

**Issue by jcomey** [eggjs/egg#4470]
## Background
这个egg.js项目不会像antd一样到圣诞节那天搞个彩蛋吧！

## Proposal
这个egg.js项目不会像antd一样到圣诞节那天搞个彩蛋吧！

## Additional context
这个egg.js项目不会像antd一样到圣诞节那天搞个彩蛋吧！

**Comment by atian25** [comment]
Egg 至今已经开源了 3 年了（2016.09），我自认对得起这个项目了。

2019 年的数据：
![image](https://user-images.githubusercontent.com/227713/93032757-c5ddd200-f665-11ea-94cf-2b20250f7d0a.png)

**Comment by atian25** [comment]
不过鉴于不友善行为，先 block 三天。

![image](https://user-images.githubusercontent.com/227713/93032782-e6a62780-f665-11ea-9eee-a053ad7676d5.png)
