### ISSUE TITLE
egg在windows server2008r2上启动后。注销或关闭远程桌面，egg进程就自动退出了

### ISSUE THREAD

**Issue by jcomey** [eggjs/egg#4472]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by atian25** [comment]
跟 egg 没啥关系，前台进程被杀了，试下 daemon 模式，可以自行查下 windows 相关知识
