### ISSUE TITLE
关于eggjs名字的疑问

### ISSUE THREAD

**Issue by kingov** [eggjs/egg#4475]
## 尴尬
每次其他项目组的同事问我们后台用的什么框架的时候 , 我都无比尴尬 , 当我说出是eggjs的时候 , 引来无尽的嘲笑 , 本来js在他们眼里就不怎么样 , 还来个 '蛋js' 这个名字 . 这要不是接手的上任同事的项目 , 我是绝对不会用什么 蛋框架的 !

## 疑问
你们为什么会想到取一个名字叫eggjs呢 ? 怎么思考的 ? 难道是不满上司对你们的KPI要求, 就取一个这个名字来恶心你们上司吗 ?  你们当初为什么不叫 puss***yjs 呢 ?

**Comment by atian25** [comment]
为什么叫 egg 在文档和官网开篇就有，只能说不看文档，且不友善行为，永久加入黑名单，再见。

PS：你可以忽悠你老大，把你们的代码重构为纯净的 Node Http 代码，或者推荐你用 vig 这个框架，这种你的 KPI 以及无尽的加班就都有了，再见。

**Comment by JasinYip** [comment]
在社区群看到还想进来点个 funny，结果发现竟然是在认真说这个事，还做恶意揣测。

技术选型应该是严肃认真的，不是看名字、鄙视语言，而应该是从性能、团队学习成本、稳定性等各方面来衡量，如果你们 团队一直保持这种肤浅的做法，我建议你还是离开这个团队吧。
