### ISSUE TITLE
egg router 写restful api的时候，访问不到路由是怎么回事？

### ISSUE THREAD

**Issue by TinchyChing** [eggjs/egg#4476]
路由上写了restful的路由，但是postman访问接口一直是{}，啥都没有  

router.js
![image](https://user-images.githubusercontent.com/13182485/93712987-cad1e280-fb8b-11ea-83ea-35ac17e5023f.png)

控制器
![image](https://user-images.githubusercontent.com/13182485/93713013-dc1aef00-fb8b-11ea-8841-82febb4d67ea.png)

postman返回
![image](https://user-images.githubusercontent.com/13182485/93713021-ee952880-fb8b-11ea-8660-3d04ef7fa9db.png)

**Comment by atian25** [comment]
请提供最小可复现仓库

**Comment by TinchyChing** [comment]
> 请提供最小可复现仓库

https://gitee.com/ti-technology/osgr_net_backend.git

这个是我的项目，可以直接拿去测试，mongodb数据库的

**Comment by atian25** [comment]
去掉数据库啥的吧，最小可复现方式

**Comment by atian25** [comment]
而且你这个明明都访问到了路由，至于为什么返回空对象，可以自己断点查下业务逻辑

**Comment by fengmk2** [comment]
少了 await

![image](https://user-images.githubusercontent.com/156269/93726765-5bd7a680-fbea-11ea-96dc-832a36720863.png)
