### ISSUE TITLE
egg-Sequelize start with errors about  'database engine version is not supported', but run dev works well

### ISSUE THREAD

**Issue by kaqiinono** [eggjs/egg#4477]
## What happens?
```
[egg-scripts] Got error when startup: 
[egg-scripts] (node:5395) [SEQUELIZE0006] DeprecationWarning: This database engine version is not supported, please update your database server. More information https://github.com/sequelize/sequelize/blob/master/ENGINE.md
```

  "egg-sequelize": "^6.0.0",
    "mysql2": "^2.2.1",

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by kaqiinono** [comment]
need myself upgrade the database engine

**Comment by caowanjing-code** [comment]
I think u meet same problem like mine,maybe you should change sequelize version,or update mysql version to 5.7.
