### ISSUE TITLE
ts 版本运行出错

### ISSUE THREAD

**Issue by JeromeLin** [eggjs/egg#4478]
按照官方文档初始化安装完ts版本，
npm start，运行正常。
```
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] Wait Start: 3...
[egg-scripts] Wait Start: 4...
[egg-scripts] egg started on http://127.0.0.1:7001
```
打开 http://127.0.0.1:7001，显示服务器500错误。
js版本是可以的。
```
Internal Server Error, real status: 500
```

## Context
- **Node Version**: v12.13.0
- **Egg Version**: 2.28.0
- **Platform**: Mac

**Comment by atian25** [comment]
再回去看下 egg ts 文档

**Comment by atian25** [comment]
tsc

**Comment by Alex-Li2018** [comment]
[here]([here](https://www.eggjs.org/zh-CN/tutorials/typescript#%E8%BF%90%E8%A1%8C-npm-start-%E4%B8%8D%E4%BC%9A%E5%8A%A0%E8%BD%BD-ts))

**Comment by Alex-Li2018** [comment]
[here](https://www.eggjs.org/zh-CN/tutorials/typescript#%E8%BF%90%E8%A1%8C-npm-start-%E4%B8%8D%E4%BC%9A%E5%8A%A0%E8%BD%BD-ts)
