### ISSUE TITLE
eggs为什么没有model层，很多学rails的，rails强大的就是数据层，eggs竟然没有

### ISSUE THREAD

**Issue by igigi** [eggjs/egg#4479]
## Proposal
Describe the solution you'd like, better to provide some pseudo code.

**Comment by atian25** [comment]
node 有两个 orm 直接用即可，也有封装好的插件

**Comment by igigi** [comment]
集成进来会更好，像rails那样强大

**Comment by atian25** [comment]
那不是 egg 这层的定位，egg 本身的定位是一套约定 + 插件 + 框架机制。

集成的事在上层框架，如 midway 等，你可以看下 https://zhuanlan.zhihu.com/p/154643011

**Comment by qxchen6** [comment]
rails 也是吧 ActiveRecord 这个库集成进去了而已
