### ISSUE TITLE
关于多应用对controller/router的复用的问题

### ISSUE THREAD

**Issue by lianxuify** [eggjs/egg#4483]
## 背景
我这边有个业务场景：一个BU的公共服务代码，希望提供出一个npm模块的“框架"，但又期望包含controller/router的复用和统一维护。其他BU使用该公共服务代码，独立部署，承担成本，同时保留对该服务的一定自定义扩展能力，如配置等

## 期望
目前egg好像不提供controller/router的复用，面对这样的场景，有什么好的实践和方法解决不？谢谢！

## egg的加载
文件 | 应用 | 框架 | 插件
-- | -- | -- | --
package.json | ✔︎ | ✔︎ | ✔︎
config/plugin.{env}.js | ✔︎ | ✔︎ |  
config/config.{env}.js | ✔︎ | ✔︎ | ✔︎
app/extend/application.js | ✔︎ | ✔︎ | ✔︎
app/extend/request.js | ✔︎ | ✔︎ | ✔︎
app/extend/response.js | ✔︎ | ✔︎ | ✔︎
app/extend/context.js | ✔︎ | ✔︎ | ✔︎
app/extend/helper.js | ✔︎ | ✔︎ | ✔︎
agent.js | ✔︎ | ✔︎ | ✔︎
app.js | ✔︎ | ✔︎ | ✔︎
app/service | ✔︎ | ✔︎ | ✔︎
app/middleware | ✔︎ | ✔︎ | ✔︎
app/controller | ✔︎ |   |  
app/router.js| ✔︎ |   |

**Comment by atian25** [comment]
可以定制上层框架的时候，把 Controller 和 router 的 loader 覆盖掉。
具体可以看下 egg-core 的源码。

https://zhuanlan.zhihu.com/p/154643011

**Comment by lianxuify** [comment]
感谢，两种方式，可以了~
