### ISSUE TITLE
egg安全之csp如何正确开启

### ISSUE THREAD

**Issue by FIWE2030** [eggjs/egg#4484]
看了文档，理解了好久，还是没法正确开启csp
config里配置了，但是页面一访问，所有静态资源js\css\图片都报错了。。，本站的资源都报错了

**Comment by FIWE2030** [comment]
我的页面是通过render出来的，不是模板，是单页面应用，所以静态资源都是放在 public下，自动获取的，csp一打开，都没法访问了

**Comment by atian25** [comment]
请提供最小可复现仓库和详细的复现方式

**Comment by popomore** [comment]
是不是应该配一个 ignore？
