### ISSUE TITLE
egg index.d.ts 定义遗漏属性

### ISSUE THREAD

**Issue by kotot** [eggjs/egg#4486]
## What happens?
egg-development 中 config 可以  配置  overrideIgnore: boolean;
但是egg index.d.ts 中缺少此属性的定义，希望可以补上

![image](https://user-images.githubusercontent.com/7607540/94901764-b49c1e80-04c9-11eb-91dc-d4a6d3a367eb.png)

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by jjeejj** [comment]
你贡献 PR 的时候到了
