### ISSUE TITLE
请教关于egg-ant-design-pro的路由配置问题

### ISSUE THREAD

**Issue by flyuuo9** [eggjs/egg#4488]
我是java开发者，看到egg-ant-design-pro有一些不理解的地方：

1.eggjs的app/route.js，这类似java spring的controller匹配对吗？
2.app/web/config/route.js，web类似java spring下的静态目录对吗？
3.1和2哪个优先处理请求？就是说，在浏览器里面打开web下的index页面的这个网络请求，会先经过1，1不处理再到2吗？
4.app/web/config/config.js中并未配置proxy。页面中发的api请求是如何转发给eggjs响应的？(demo里面web/mock提供了mock返回数据。如果未提供网络请求怎么路由的呢)

**Comment by popomore** [comment]
一个是服务端的，一个是前端的。前端路由不发起请求，除非用户手动刷新。

所以如果路由不一致就会有问题。前端可以切换，但是当手动刷新，服务端路由不匹配就挂了。
