### ISSUE TITLE
生产环境如何用脚本关闭egg服务器

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#449]
* 开发环境关闭terminal即可
* 测试环境因为守护进程问题，目前用forever start, forever stop的，但不严谨
* 生产环境用标准方式`node index.js`启动的

其中, index.js的代码内容为：

```
'use strict';

const isLocal = process.env.NODE_ENV !== 'production' && !process.env.EGG_SERVER_ENV;

require('egg').startCluster({
    baseDir: __dirname,
    port: process.env.PORT || 7001, // default to 7001
    workers: isLocal ? 1 : undefined, // default to cpu count
});
```

请问，`node index.js`后，如何关闭这个cluster

**Comment by johnnychen** [comment]
这个问题其实跟nodejs没关系，是linux下如何后台启动并关闭的问题，我自己研究下，再发答案-_-

**Comment by atian25** [comment]
https://github.com/eggjs/egg-scripts/pull/1/files 还在 PR 中.

目前而言，可以 ps 找到 master 进程， kill 掉它即可。

**Comment by johnnychen** [comment]
嚓，ps进程太多了-_-

**Comment by atian25** [comment]
用 `--customEgg`` 做关键词就好了

**Comment by huangyanxiong01** [comment]
Linux下最好用的进程管理器
`RedHat/CentOS`
```bash
yum install htop -y
```
`Debian/Ubuntu`

```bash
sudo apt-get install htop 
```

**Comment by onion214** [comment]
启动的时候没有设置 customEgg ，怎么用ps找到master进程？@johnnychen

**Comment by atian25** [comment]
启动是不需要设置的，最新的 egg 的关键词不是 customEgg 了，需要用 `"baseDir"... 目录名` 和 `framework` 来判断，我下周会把 egg-scripts 完成，回头看能否加一个特殊的关键词。

```bash
{"baseDir":"/Users/tz/Workspaces/eggjs/test/showcase","framework":"/Users/tz/Workspaces/eggjs/test/showcase/node_modules/egg","workers":1}
```

**Comment by onion214** [comment]
现在用 ps -eo "pid,command"拿到的列表是这样的
3683 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseD
 3694 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseD
 3705 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node
 3716 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseD
 3727 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseD
 3738 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node


所有的进程都kill了一遍，但是再看ps还是这样的

**Comment by atian25** [comment]
你用什么 grep 的， `app_worker` 和 `agent_worker` 分别是 worker 和 agent，肯定不是 master，杀这几个没用， 会自动重启。

**Comment by onion214** [comment]
ps -eo "pid,command" | grep 'walrus'

上面的copy 更新了下

**Comment by onion214** [comment]
那是不是master进程没有了，还有什么方法可以kill吗

**Comment by johnnychen** [comment]
我们运维帮我们写了一个脚本`nodejs`放在`/etc/init.d/`中，最后通过两条命令即可完成node多进程的启动或关闭, 最后的命令是

*`service nodejs start`
* `service nodejs stop`
* `service nodejs restart`

----------------

其中, `/etc/init.d/nodejs`脚本

```
#!/bin/bash
#set -x
# chkconfig: 2345 80 20
# description: Nodejs AS
# Source function library.
# this script created by Jason Ding on 2017/02/27
. /etc/rc.d/init.d/functions
export NODE_HOME="/opt/node-v6.9.2-linux-x64"
export JAVA_HOME="/usr/local/jdk1.6.0_45"
export CLASS_PATH="$JAVA_HOME/lib:$JAVA_HOME/jre/lib"
export PATH=".:$PATH:$NODE_HOME/bin:$JAVA_HOME/bin"
PRIVATE_PATH=/home/cxinscn_cathay_portal/private
PUBLIC_PATH=/home/cxinscn_cathay_portal/public
STOPNODEJS=`killall node`
RETVAL=0
#start nodejs
start() {
          echo -n "starting nodejs !!!!!"
          cd "${PRIVATE_PATH}" && EGG_SERVER_ENV=test node index.js  & > /dev/null
          cd "${PUBLIC_PATH}" && EGG_SERVER_ENV=test node index.js  & > /dev/null
               RETVAL=$?
               return $RETVAL
}

#stop jboss
stop() {
          echo -n "stopping nodejs !!!!! "
          ${STOPNODEJS}
          RETVAL=$?
         return $RETVAL
}

restart() {

echo -n "Restart Nodejs!!!!!  "

stop

start

echo

}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
 restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
```

其中`/etc/init.d/killall`

```
#! /bin/bash

# Bring down all unneeded services that are still running (there shouldn't
# be any, so this is just a sanity check)

case "$1" in
   *start)
        ;;
   *)
        echo $"Usage: $0 {start}"
        exit 1
        ;;
esac


for i in /var/lock/subsys/* ; do
        # Check if the script is there.
        [ -f "$i" ] || continue

        # Get the subsystem name.
        subsys=${i#/var/lock/subsys/}

        # Networking could be needed for NFS root.
        [ $subsys = network ] && continue

        # Bring the subsystem down.
        if [ -f /etc/init.d/$subsys.init ]; then
                /etc/init.d/$subsys.init stop
        elif [ -f /etc/init.d/$subsys ]; then
                /etc/init.d/$subsys stop
        else
                rm -f "$i"
        fi
done
```

**Comment by atian25** [comment]
你的输出很奇怪，没有 master，试下`ps -eo "pid,ppid,command" | grep 'walrus'` 看下他们的 parent id  master 是哪个了.

**Comment by johnnychen** [comment]
PS: 我们做过多轮测试，发现即使kill master, agent进程也不会关闭的,不知道为什么, worker会关闭。

**Comment by atian25** [comment]
@johnnychen 能提供最小的复现代码么?

**Comment by onion214** [comment]
ps -eo "pid,ppid,command" | grep 'walrus'

3911 30001 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":41202}
 3923 31655 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":34197}
 3929 31655 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":34197}
 3939 31655 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":34197}
 3970 30001 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":41202}
 3981 30001 /home/node/.tnvm/versions/node/v6.9.5/bin/node /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/app_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":41202}

**Comment by onion214** [comment]
是的，执行了
kill -9 30001  
kill -9 31655
还有两个agent_worker

3911     1 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":41202}
 3939     1 /home/node/.tnvm/versions/node/v6.9.5/bin/node --debug-port=5856 /app/nodeapp/walrus/node_modules/.1.6.2@egg-cluster/lib/agent_worker.js {"framework":"/app/nodeapp/walrus/node_modules/egg","baseDir":"/app/nodeapp/walrus","port":7001,"workers":2,"plugins":null,"https":false,"key":"","cert":"","clusterPort":34197}

**Comment by johnnychen** [comment]
## 1. 初始化：ps aux | grep node 
![image](https://cloud.githubusercontent.com/assets/1297278/24434885/d06e38fe-1464-11e7-8868-dbcd2c2f4a4b.png)

## 2. 启动: cd NODE_PROJECT, GG_SERVER_ENV=default node index.js(我电脑8个worker进程）
![image](https://cloud.githubusercontent.com/assets/1297278/24434966/263ffca4-1465-11e7-83f1-d662ccdbdb88.png)

## 3. 关闭主进程：`kill -9 79989`

## 4. 查看关闭后的进程

![image](https://cloud.githubusercontent.com/assets/1297278/24435008/6b21073c-1465-11e7-8058-785ab1d6148f.png)

-------

@atian25 最后多了agent进程-_-

**Comment by atian25** [comment]
不要 `kill -9` ...  这是强杀，强杀 master 是立即退出的，它肯定没机会让 worker 和 agent 优雅退出啊。。。

**Comment by atian25** [comment]
@onion214 `ps -eo "pid,ppid,command" | grep 'walrus'` 后， 再 ps 下 第二列的那个 id，如你上面的是 30001， 那就 `ps -eo "pid,ppid,command" | grep '30001'`

**Comment by johnnychen** [comment]
请提供一个SIGNAL, 我之前随便试了几个，也一样。

另外如何解释，每次8个worker都’优雅'退出，单单agent不行呢？

**Comment by atian25** [comment]
@johnnychen 给出可复现的最小 showcase，我们业务中都是可以优雅退出的。
不需要 SIGNAL，默认的即可

**Comment by onion214** [comment]
@atian25 @johnnychen 
谢谢两位的解答，已经都kill掉了

**Comment by johnnychen** [comment]
@atian25 @onion214  试了 kill [PROCESS_ID], agent也退出了

**Comment by atian25** [comment]
@johnnychen 所以 kill 是没问题的了? 之前是 `kill -9` 的问题

**Comment by johnnychen** [comment]
@atian25 对的

**Comment by mdluo** [comment]
@atian25 @johnnychen 

```
ps -o "ppid,command" | grep "egg-cluster" | grep "7001" | awk {'print $1'} | xargs kill
```
