### ISSUE TITLE
EGG_SERVER_ENV not change with NODE_ENV

### ISSUE THREAD

**Issue by Talbot3** [eggjs/egg#4492]
> by design.

yeah, that's ok.but there has docs, say that 
NODE_ENV map to EGG_SERVER_ENV
https://eggjs.org/en/basics/env.html#mobileAside
or see 
https://eggjs.org/zh-cn/basics/env.html.
are you really by design, i don't think so.that's bug.of course, this is great node framework, i just want report it .

_Originally posted by @Talbot3 in https://github.com/eggjs/egg/issues/2060#issuecomment-706922506_

**Comment by Talbot3** [comment]
![截屏2020-10-12 下午2 30 25](https://user-images.githubusercontent.com/7347198/95718911-ac9a6680-0ca1-11eb-960d-1041a0b4e522.png)

**Comment by Talbot3** [comment]
![Uploading 截屏2020-10-12 下午2.30.25.png…]()

**Comment by Talbot3** [comment]
![截屏2020-10-12 下午2 30 25](https://user-images.githubusercontent.com/7347198/95719187-10bd2a80-0ca2-11eb-9bf6-10ba18c68eac.png)

**Comment by Talbot3** [comment]
![Uploading 截屏2020-10-12 下午3.45.22.png…]()

**Comment by atian25** [comment]
这个设置是知道的，我们的最佳实践是线上强制用 NODE_ENV prod。

你现在的场景是什么？

**Comment by Talbot3** [comment]
场景就是 将egg打包docker镜像，使用egg-scripts启动的容器，需要根据NODE_ENV的不同来匹配不同的配置。没有使用egg-sequelize,而是自己写的扩展。因为model有多个，以及有对应的自动migration\init.sh相关的自动初始化脚本工程，都根据NODE_ENV来配置的。导致在上线在变更环境的时候，NODE_ENV在egg执行中不生效，而其他工程使用的是相应的NODE_ENV,链接卡死，排查了很多，太费时间。关系是强制的话，开放度会不够，甚到没有显示说明，这是个炸弹。

**Comment by atian25** [comment]
> 使用egg-scripts作为启动命令，需要根据NODE_ENV的不同来匹配不同的配置

egg-scripts start --env=[prod]

egg 体系里面是用 EGG_SERVER_ENV 的，建议正式环境的 NODE_ENV 都是 prod，避免不必要的坑。

`migration\init.sh` 应该是单独的 shell 吧，跟 egg 的环境变量没关系。

**Comment by Talbot3** [comment]
> > 使用egg-scripts作为启动命令，需要根据NODE_ENV的不同来匹配不同的配置
> 
> egg-scripts start --env=[prod]
> 
> egg 体系里面是用 EGG_SERVER_ENV 的，建议正式环境的 NODE_ENV 都是 prod，避免不必要的坑。
> 
> `migration\init.sh` 应该是单独的 shell 吧，跟 egg 的环境变量没关系。

是的。这在应用编排的时候都使用一个环境变量，有利于变更。

**Comment by Talbot3** [comment]
![截屏2020-10-12 下午3 45 22](https://user-images.githubusercontent.com/7347198/95726618-bc1ead00-0cab-11eb-9ab8-1e9836850609.png)

**Comment by atian25** [comment]
我的意思是，EGG 体系里面我们的实践，都是强制 NODE_ENV 为 prod，相关判断都用 EGG_SERVER_ENV。
避免不必要的坑，如果改为 `NODE_ENV = NODE_ENV || 'prod'` 的话，很可能因为外部的环境变量来覆盖掉，而我们不希望被覆盖掉。

> 是的。这在应用编排的时候都使用一个环境变量，有利于变更。

要不就换个环境变量，要不就提个 PR 支持 --node_env= 这样的参数来强制设置。
