### ISSUE TITLE
egg启动如何设置多进程  -c=4 和--workers=1

### ISSUE THREAD

**Issue by liuhuanhui** [eggjs/egg#4493]
本地开发为何只启动了一个进程，启动egg-bin dev --workers=4 设置无效，-c=4 有效？

**Comment by atian25** [comment]
本地开发为啥要多进程

**Comment by liuhuanhui** [comment]
> 本地开发为啥要多进程

本地想要测试下多进程

**Comment by atian25** [comment]
https://github.com/eggjs/egg-bin/blob/dcc9b256843815b6b4f1e505bfd1bf3aeffa4db0/lib/cmd/dev.js#L22

从文档来看是支持的，也有对应的单测。

**Comment by liuhuanhui** [comment]
> https://github.com/eggjs/egg-bin/blob/dcc9b256843815b6b4f1e505bfd1bf3aeffa4db0/lib/cmd/dev.js#L22

从我的实践上来看是不支持的，还有请问下，agent.js是不是不能调用service呢？

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/96072706-747c6900-0ed7-11eb-91c3-a11fafaf463e.png)

我验证是没问题的，自行检查下。

> 还有请问下，agent.js是不是不能调用service呢？

agent 没有加载 service，文档里面有写。
