### ISSUE TITLE
请问有无办法在 service 得到 caller，或设置 caller 黑白名单

### ISSUE THREAD

**Issue by hdwong** [eggjs/egg#4494]
需求是这样，我们项目中的 Controller 和 Service 来自多方开发，我希望 Service 只能被某些 Controller 或 Service 调用，这个有什么方法可以实现，我在 this.ctx 中好像没发现线索。
谢谢。

**Comment by atian25** [comment]
需自行实现， 就是个函数调用，JS 本身就没有 caller 的
