### ISSUE TITLE
egg-http-proxy rewrite 例子有问题

### ISSUE THREAD

**Issue by ohalex** [eggjs/egg#4496]
## What happens?
https://github.com/eggjs/egg-http-proxy
文档中rewrite例子有误，
这是例子
![image](https://user-images.githubusercontent.com/10094606/96228023-93f2bf00-0fc7-11eb-9870-af0d59b51deb.png)
通过调试源码发现，实际得到的rewrite后的urlObj为undefined
![image](https://user-images.githubusercontent.com/10094606/96228047-9bb26380-0fc7-11eb-844d-70bc67672f00.png)
应该返回urlObj的，容易误导别人

**Comment by jjeejj** [comment]
rewrite 内部操作的是 urlObj 对象的引用，这里是不是可以不接收 rewrite 函数的返回值并且把 assert 这个断言去掉？
这样可以避免用户的误操作，返回了一个不是 url 类型的值

**Comment by atian25** [comment]
那样改会 break

**Comment by jjeejj** [comment]
这个改的话会 break 什么？

> 那样改会 break

**Comment by atian25** [comment]
如果有个开发者写了类似的：

```js
rewrite(urlObj) {
  return {
     path: '/api/' + urlObj.path
  }
}
```

它返回的是一个新的 obj，而不是修改原有的，那我们那样改了就会 break 他的代码了。

**Comment by jjeejj** [comment]
明白了，这样做也可以给用户更大的灵活性。 

那现在的问题就是：把文档那 返回 urlObj 就可以了
