### ISSUE TITLE
(node:2184) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.

### ISSUE THREAD

**Issue by FollowTrend** [eggjs/egg#4500]
(node:2184) [DEP0106] DeprecationWarning: crypto.createCipher is deprecated.

**Comment by FollowTrend** [comment]
用egg.js保存session的时候包这个错，请问这个怎么解决

**Comment by FollowTrend** [comment]
"egg": "^2.15.1",
    "egg-cors": "^2.2.3",
    "egg-mysql": "^3.0.0",

**Comment by jjeejj** [comment]
这只是警告  `crypto.createCipher` 被废弃了，但是还是可以使用的。 要想去掉这个警告就要 `egg` 官方 使用 `crypto.createCipheriv` 来替换它。

**Comment by atian25** [comment]
dup: https://github.com/eggjs/egg/issues/4240
