### ISSUE TITLE
我想知道能使用第三方插件吗？就是npm市场npm install xxx --save那种

### ISSUE THREAD

**Issue by hohnworld** [eggjs/egg#4502]
最近在想使用egg.js定时发送钉钉机器人，但是没有egg-开头的npm插件，
请问我能使用npm install dingding-robot-sdk --save这个插件吗，怎么用，谢谢

**Comment by atian25** [comment]
可以先看下文档，把 Egg 的 Middleware 和 Plugin 文档看下先
