### ISSUE TITLE
如何给ctx.state定义类型？

### ISSUE THREAD

**Issue by microCloudCode** [eggjs/egg#4504]
如何在egg为ctx.state定义类型?

**Comment by jjeejj** [comment]
没有明白你要问的是什么？ 你再使用 TS 为 ctx.state 赋值的时候，指定类型不就可以了么？

**Comment by microCloudCode** [comment]
@jjeejj 我是想在Context的整个生命周期都可以得知state的类型，如果只是使用的时候给ctx.state指定类型，那后续的中间件访问state一样还是any

**Comment by popomore** [comment]
最好单独挂一个对象，state 和 body 一样，每个请求的数据类型可能都不一样。

**Comment by microCloudCode** [comment]
@popomore state不就是官方推荐的命名空间吗?

**Comment by jjeejj** [comment]
对于每一个请求的 state 的类型可能都是不一样的，我认为是没有办法做到统一的。

**Comment by atian25** [comment]
看下 Egg TS 教程，写个 typing 就好了。

**Comment by microCloudCode** [comment]
已解决
