### ISSUE TITLE
ts版 引用自定义框架 设置 "declarations": true ，启动后报 AssertionError [ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application

### ISSUE THREAD

**Issue by huyumo** [eggjs/egg#4505]
## What happens?
ts版 引用自定义框架 设置 "declarations": true ，启动后报
 AssertionError [ERR_ASSERTION]: Symbol.for('egg#eggPath') is required on Application

![image](https://user-images.githubusercontent.com/10991856/97385686-2cb10500-190d-11eb-8d4c-f101b898f6fc.png)

![image](https://user-images.githubusercontent.com/10991856/97385655-12772700-190d-11eb-9faf-dbf7acfb632f.png)

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.使用 npm init egg --type=ts 搭建demo
2.npm link examples/framework/yadan
3.npm run debug

**Expected behavior**
1.
2.

## Context
- **Node Version**:v10.16.3
- **Egg Version**: ^2.6.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by popomore** [comment]
一般是有多个版本的 egg 造成的，需要能重现的 demo

**Comment by huyumo** [comment]
代码地址就是官方实例 https://github.com/eggjs/examples/tree/master/framework，只是将app 更换为ts 版本 ，ts demo也是使用的官方脚手架搭建  npm init egg --type=ts，然后将默认框架 egg 换为 [yadan](https://github.com/eggjs/examples/tree/master/framework/yadan) 
![image](https://user-images.githubusercontent.com/10991856/97558504-2b6bff00-1a17-11eb-9ac6-2eeaef3d01ea.png)

**Comment by atian25** [comment]
提交下完成后的仓库

**Comment by huyumo** [comment]
https://gitee.com/ymoo/myNode/tree/moyanTs-v0.1.7/moyan3.0/demo

**Comment by huyumo** [comment]
另外 如果 service/test.ts 存在，会报以下错误

**Comment by huyumo** [comment]
![image](https://user-images.githubusercontent.com/10991856/97704949-3ba2dd80-1aee-11eb-9125-20b99993e305.png)

**Comment by atian25** [comment]
没权限。

看报错应该是 js 和 ts 同时存在了，本地开发直接内置 ts-node 了。

看过这篇么了？https://zhuanlan.zhihu.com/p/154643011

**Comment by huyumo** [comment]
好的 ，我在检查下  ，谢谢您的帮助
