### ISSUE TITLE
上传图片功能不会使用

### ISSUE THREAD

**Issue by Dilmoon2016** [eggjs/egg#4506]
node 12.13.0
egg：2.28.0
前端代码：
var formData = new FormData();       
formData.append("file",file.raw);
$.ajax({
        url: _baseURL+url,
        data:formData,
        type: 'POST',
        dataType:'json',
        processData:false,
        contentType:false,
        success: successBack,
        fail: fail
    });
node代码 上传文件到aws s3上
var stream = await ctx.getFileStream();
var avs = await this.ctx.curl(params, {
            headers:{
                "Content-Type":"application/octet-stream",
            },
            data:stream,
            method: 'PUT',
            timeout: 60000,
          })
配置代码：config.multipart= {
    fieldSize: '50mb',
    fields: 10,
    fileSize: '50mb',
    files: 10,
    fileExtensions: [ '.txt','.rar','.zip','.bin' ], // 增加对 txt 扩展名的文件支持
    mode: 'stream',
  }
上传的文件只有几百b，如果改为var streams=stream._readableState.buffer.head.data;上传小文件可以，文件只有60多kb

**Comment by JasinYip** [comment]
如果不了解 stream 的使用，建议改为 file 模式

**Comment by Dilmoon2016** [comment]
虽然file模式很容易解决问题，但是stream之前用aws sdk是成功的但是这次用put上传，就是文件显示不全

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/upload.html#%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF

看文档，然后理解下你这个操作的过程，`前端 --> Egg --> 存储服务`，每一步对应于什么，理解下它们的含义。
