### ISSUE TITLE
nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Liqiankun** [eggjs/egg#4509]
## What happens?
我请求一个API如果直接在浏览器请求返回的就是JSON格式。如果是用curl请求返回的就是HTML。而且提示错误`nodejs.JSONResponseFormatError: Unexpected token < in JSON at position 0`。
![WechatIMG2035](https://user-images.githubusercontent.com/11532418/97545175-8e549a80-1a05-11eb-9506-162034d734f6.jpeg)

![截屏2020-10-29 16 43 42](https://user-images.githubusercontent.com/11532418/97545414-f1dec800-1a05-11eb-82b1-dc1b7a5dcf09.png)

![截屏2020-10-29 16 44 28](https://user-images.githubusercontent.com/11532418/97545796-76c9e180-1a06-11eb-9586-211654e10152.png)

## Context
- **Node Version**: v12.18.3
- **Egg Version**: ^2.15.1

**Comment by atian25** [comment]
你截图上已经写的很清楚了， 301

**Comment by jjeejj** [comment]
你看你的那个截图，你的响应头：`Content-Type: text/html`

**Comment by Liqiankun** [comment]
@atian25 @jjeejj 我应该怎么做呢？我写的是`application/json`。

**Comment by atian25** [comment]
你 curl 一个后端服务，这个服务把你拦截了， 301 到一个 HTML 页面了。可能是防刷，如判断了 user-agent 啥的。

**Comment by Liqiankun** [comment]
@atian25 这我请求的这个API可能有这个机制是吧？那请问`followRedirect options`具体怎么设置？

**Comment by atian25** [comment]
看 urllib 文档，这个参数只是帮你把 302 后的页面继续请求了下而已，如果后面的页面还是 HTML 那也不行的。

![image](https://user-images.githubusercontent.com/227713/97546806-e8565f80-1a07-11eb-85f6-be728a2fbb54.png)

这个错误信息其实很明显了，可以去了解下 HTTP 协议的重定向这块。

**Comment by Liqiankun** [comment]
@atian25 API技术方说是没有ua，那请问curl怎么添加ua呢？

**Comment by atian25** [comment]
先看文档再来问吧
