### ISSUE TITLE
在开发egg的handlebarjs插件，自定义的helper,Partials应该存放在哪里好

### ISSUE THREAD

**Issue by huangyanxiong01** [eggjs/egg#451]
* **Node Version**: 6.10.0
* **Egg Version**:  1.0.0-rc.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Linux

完成开发后打算贡献给egg社区:smile:

**Comment by dead-horse** [comment]
helper 定义在 `app/extend/helper.js` 中，详情参考文档 https://eggjs.org/zh-cn/basics/extend.html#helper

**Comment by dead-horse** [comment]
partials 并不是所有 view 都有支持的，所以 egg 并没有做约定和处理

**Comment by atian25** [comment]
@huangyanxiong01 非常感谢，不过要注意下， View 的规范刚刚变更了，但文档那边还没更新。
参考下 https://github.com/eggjs/egg/issues/398

**Comment by atian25** [comment]
@huangyanxiong01 有兴趣迁移进 eggjs 不

**Comment by 280455936** [comment]
handlebarjs的helper
Handlebars.registerHelper('link', function(text, url) 
如何使用？
