### ISSUE TITLE
curl如何添加User-Agent

### ISSUE THREAD

**Issue by Liqiankun** [eggjs/egg#4510]
![截屏2020-10-29 17 39 26](https://user-images.githubusercontent.com/11532418/97551243-b21bde80-1a0d-11eb-8458-5c91ab4230a9.png)

**Comment by atian25** [comment]
你有真验证过这段代码么？ 请提供可复现的方式。

**Comment by Liqiankun** [comment]
@atian25 我怎么提供呢因为里边包含了我们的Appkey。

**Comment by atian25** [comment]
提供最小可复现方式，而不是让你把代码库整个搬上来。看上面的文档。

**Comment by Liqiankun** [comment]
@atian25 [dl_curl_ua](https://github.com/Liqiankun/dl_curl_ua.git) 请麻烦帮忙查看。

**Comment by atian25** [comment]
你怎么确定 ua 没设置成功？

**Comment by Liqiankun** [comment]
```
const reuslt = await ctx.curl(url, {
      dataType: 'json',
      headers: {
        'User-Agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36',
      },
    });
```

**Comment by atian25** [comment]
你贴这段代码没意义啊，这只是代表你设置了，但不代表有没有发出去，你要验证我们这里是有 bug 的，并提供复现方式，我才能帮你跟进。

上面我不是给了验证方式了么

**Comment by Liqiankun** [comment]
@atian25 我提供了我的最小代码呀。

> @atian25 [dl_curl_ua](https://github.com/Liqiankun/dl_curl_ua.git) 请麻烦帮忙查看。

**Comment by atian25** [comment]
你的代码里面没有验证逻辑啊，我们怎么知道是你们 API 服务那边的处理 bug，还是这边的发送侧没发出去？

**Comment by Liqiankun** [comment]
@atian25 需要我验证什么呢？

**Comment by Liqiankun** [comment]
@atian25 那边加上UA请求就是真确的
![A5F2FFDA429632CF1F86C80FB63CB6AC](https://user-images.githubusercontent.com/11532418/97556063-e4303f00-1a13-11eb-91ba-6eed2a624b19.png)

**Comment by atian25** [comment]
看我上面回复提供的方式自己验证下

**Comment by Liqiankun** [comment]
怎么验证呢？因为我问这个问题就是不知道问题的所在呀。

**Comment by atian25** [comment]
> 你怎么确定 ua 没设置成功？
> 
> 
> 
> 可以自己[抓包](https://eggjs.github.io/zh/guide/httpclient.html#%E6%8A%93%E5%8C%85%E8%B0%83%E8%AF%95)，或者用 [nock](https://github.com/nock/nock) 来单测看看，或 https://requestbin.com/

这不是跟你说了这么多方式么

**Comment by atian25** [comment]
> 你怎么确定 ua 没设置成功？
> 
> 
> 
> 可以自己[抓包](https://eggjs.github.io/zh/guide/httpclient.html#%E6%8A%93%E5%8C%85%E8%B0%83%E8%AF%95)，或者用 [nock](https://github.com/nock/nock) 来单测看看，或 https://requestbin.com/

这不是跟你说了这么多方式么

**Comment by Liqiankun** [comment]
@atian25 我用这个抓包怎么验证呢？怎么设置呢？

**Comment by hyj1991** [comment]
用 wireshark 可以抓包看下 request 出去的报文里的 header 有没有 ua 标识，正常你的写法接收方肯定是能拿到 UA 信息的

**Comment by Liqiankun** [comment]
好我试试

**Comment by Liqiankun** [comment]
@hyj1991 我试试request包

**Comment by Liqiankun** [comment]
时间紧，我现在的问题就是这个API在浏览器中直接请求是正确的，在egg中用curl请求就是错误的。问题就是这个呀。
