### ISSUE TITLE
onerror无法设定返回状态和body

### ISSUE THREAD

**Issue by chucklai92** [eggjs/egg#4511]
## What happens?
按照文档：
https://eggjs.org/zh-cn/core/...

写了统一处理错误：
`onerror: {
      all(err, ctx) {
        console.log(111199, err);
        ctx.status = 500;
        ctx.body = { status: 'error', msg: err.message };
      },
    },`
111199和err都能打印出来，说明错误被捕捉到了
但是一直没有返回500状态和body给前端

## 相关环境信息
- **操作系统**：macOS 15
- **Node 版本**：v10.14.1
- **Egg 版本**：2.15.1

**Comment by HongJiyu** [comment]
好像是因为get请求，我其他类型的请求都没问题，get请求的话，没有数据返回给前端，前端一直在loading。
