### ISSUE TITLE
framework替换controller基类

### ISSUE THREAD

**Issue by GeniusBrother** [eggjs/egg#4512]
'use strict';

const path = require('path');
const egg = require('egg');
const Controller = require('./core/base_controller');
const Service = require('./core/base_service');

const EGG_PATH = Symbol.for('egg#eggPath');

class Application extends egg.Application {
get EGG_PATH {
return path.dirname(__dirname);
}
}

class Agent extends egg.Agent {
get EGG_PATH {
return path.dirname(__dirname);
}
}

module.exports = Object.assign(egg, {
Application,
Agent,
Controller,
Service
});

如果使用framework的方式替换controller基类 可以吗，我再上层业务里requrie('egg').Controller的时候发现还是BaseContextClass

**Comment by atian25** [comment]
先检测下你的上层应用有没有正确的使用了这个 Framework 先。

看下 https://zhuanlan.zhihu.com/p/154643011 最后面

**Comment by GeniusBrother** [comment]
已经正确的配置了egg.framework 不是这个原因

现在定位到是由于我使用npm link的原因 framework 和上层 requrie的node_modules egg的路径不一样 所以导致返回不一样的对象，因此framework里的require('egg')的controller基类实现确实被替换掉了 但是上层却没有

看了你们写的[渐进式开发](https://eggjs.org/zh-cn/tutorials/progressive.html)才决定先使用npm link的方式，但目前来看 这个方式有问题，您有什么建议吗 @atian25

**Comment by atian25** [comment]
不要太依赖 link 吧，一般我们都是用单测来验证。 启动命令好像可以指定 framework 物理路径的，不太记得了

**Comment by GeniusBrother** [comment]
嗯嗯 感谢您的解答
