### ISSUE TITLE
use easywebpack cli to initialize a application which use egg@2.19.1 , start node server by npm run dev, all static resouces 404

### ISSUE THREAD

**Issue by xiaoyanzheng** [eggjs/egg#4514]
## What happens?
egg 2.19.1 use easywebpack cli init application , start node server by npm run dev, all static resouces 404
![image](https://user-images.githubusercontent.com/7248432/98068835-2cc67d00-1e98-11eb-85d9-ddfb92e6b5a1.png)

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1. npm i @easy-team/easywebpack-cli -g
2. init Egg + Vue + TypeScript Server Side Render Application (application name: demo)
easy init  
![image](https://user-images.githubusercontent.com/7248432/98068577-634fc800-1e97-11eb-848c-630424b36b93.png)
3. cd demo
npm install
4. npm run dev

**Expected behavior**
1.  all static resources requests  are responded by 200 status

## Context
- **Node Version**: v12.6.0
- **Egg Version**: 2.19.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: mac

**Comment by xiaoyanzheng** [comment]
downgrade egg from 2.19.1 to 2.17.0 can resolve problem，why？

**Comment by hubcarl** [comment]
@xiaoyanzheng It can work by your step. `http://127.0.0.1:7001/public/js/runtime.js` will be proxied to  `http://127.0.0.1:9000/public/js/runtime.js` by `egg-webpack` plugin. You can check the static resource by 
`http://127.0.0.1:9000/public/js/runtime.js`。

**Comment by xiaoyanzheng** [comment]
> @xiaoyanzheng It can work by your step. `http://127.0.0.1:7001/public/js/runtime.js` will be proxied to `http://127.0.0.1:9000/public/js/runtime.js` by `egg-webpack` plugin. You can check the static resource by
> `http://127.0.0.1:9000/public/js/runtime.js`。

**Comment by xiaoyanzheng** [comment]
@hubcarl  it is correct by http://127.0.0.1:9000/public/js/runtime.js , it is fail by http://127.0.0.1:7001/public/js/runtime.js
![image](https://user-images.githubusercontent.com/7248432/98076683-b763a800-1ea9-11eb-9a97-53d5c0f096da.png)
![image](https://user-images.githubusercontent.com/7248432/98076698-c0547980-1ea9-11eb-8504-2737f60b6a63.png)

**Comment by xiaoyanzheng** [comment]
@hubcarl The problem has been identified.  koa-compose@4.2.0 has been maintained by our internal registry. In fact, this version has been abandoned, so using "npm install --registry=https://registry.npm.taobao.org" can solve the problem
