### ISSUE TITLE
Cannot read property 'endsWith' of null

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#4518]
## 复现步骤，错误日志以及相关配置

隔几天就有sentry告警，目前没有办法复现

![image](https://user-images.githubusercontent.com/9158889/98884796-c5c64b00-24cb-11eb-9d76-2eb5a36343e0.png)

## 相关环境信息
- **操作系统**：node:12.17.0-alpine
- **Node 版本**：12.17.0
- **Egg 版本**：2.26.1

**Comment by atian25** [comment]
没有可复现方式的没法查。

`ctx.path` 不应该有为空的情况的，除非你某个插件篡改了它

**Comment by changzhiwin** [comment]
可以跟踪一下源码，这个[parseurl](https://github.com/pillarjs/parseurl/blob/master/index.js#38)库里面解析的返回，有可能是undefined

**Comment by no7wan7** [comment]
@logzh 大佬，这里之后有解决这个问题吗，我这边也遇到一样的问题了，也没有复现

**Comment by logzh** [comment]
@no7wan7 没有解决，线上问题，不知道怎么复现
