### ISSUE TITLE
egg在windows server 2012R2中无法部署？

### ISSUE THREAD

**Issue by zhangluzhanglu** [eggjs/egg#4519]
## 背景

   我使用egg开发的一个web程序，开发完毕后，在本地的window10系统额mac系统上都能正常部署
即npm run start 部署命令执行成功，但是当我把代码放在windows server 2012R2上时，就只能以开发模式允许，即只能执行npm run dev，当我执行npm run start时就会报错。

报错如下： 
(node:544) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time（实际上此报错在npm run dev时也会出现，但是最终程序是能运行的，而start命令确无法执行）

## 思路
   对于这个报错，大致意思为【警告：条件导出是一个实验特性。此功能随时可能更改】，意思是不怎么支持某些功能？可是我在windows server 2012R2按照的node版本非常新，为13.9，不可能不支持基本的语法吧？难道是windows server 2012R2的问题？
   后来我直接创建了个基本的egg-demo，然后随便写了代码放在windows server 2012R2上，start命令仍然报同样的错误，难道是windows server 2012R2不支持某些东西？给如何解决呢？

**Comment by atian25** [comment]
这是 Node 本身的报错，跟 Egg 没啥关系。

**Comment by hyj1991** [comment]
用偶数版本，奇数版本就不是长期支持的版本，这也是 13.x 的一个 bug，升级到 v14 最新的版本应该就行了

**Comment by atian25** [comment]
exports 是 package.json 里面的一个新特性，有兴趣可以去看下 npm 的更新日志。

**Comment by zhangluzhanglu** [comment]
> 用偶数版本，奇数版本就不是长期支持的版本，这也是 13.x 的一个 bug，升级到 v14 最新的版本应该就行了

     非常感谢，的确是这个原因，我在windows server 2012R2上更新了下node版本为14之后，就可以正常部署了
