### ISSUE TITLE
[Feature Request] 插件推荐：egg-apigw-tracer

### ISSUE THREAD

**Issue by inlym** [eggjs/egg#4520]
## 背景介绍
在对外提供 Web 服务时，可能在线上环境出现偶发性的错误，为了方便排查问题，给所有的请求都提供一个唯一请求ID是一个不错的实践，开发者可以根据这个请求ID去相关日志中找寻对应的错误内容。

这个「唯一请求ID」（Unique Request ID）有的时候也叫「示踪ID」（trace ID），一个通俗的做法是使用 UUID 生成一个字符串，并在响应中附带该字符串。另外一些 Web 服务，会使用云厂商的 API 网关作为接入层，然后将请求转发到开发者自己的服务器上。此时我们往往希望使用 API 网关自带的请求ID作为示踪ID，本插件就是为了解决这个问题诞生的。

本插件完美适配 Egg.js 框架，只需要按照框架要求启用插件，可以零配置使用。

## 项目地址
插件项目地址：https://github.com/inlym/egg-apigw-tracer

恳请收录！

**Comment by hyj1991** [comment]
文档写的不错，提一点意见，缺少单元测试和覆盖率报告，可以集成下 git actions

**Comment by atian25** [comment]
赞，不过我们目前 GitHub 没有收录的地方。可以考虑写篇介绍文投稿到我们的知乎专栏：https://zhuanlan.zhihu.com/eggjs


PS：之前有个 RFC：https://github.com/eggjs/egg/issues/39 以及对应的底层实现，如 https://github.com/eggjs/egg-opentracing

**Comment by inlym** [comment]
> 赞，不过我们目前 GitHub 没有收录的地方。可以考虑写篇介绍文投稿到我们的知乎专栏：https://zhuanlan.zhihu.com/eggjs
> 
> PS：之前有个 RFC：#39 以及对应的底层实现，如 https://github.com/eggjs/egg-opentracing

可以收录到这个推荐列表吗？
https://github.com/eggjs/awesome-egg#plugins

**Comment by atian25** [comment]
可以提 PR

**Comment by inlym** [comment]
> 可以提 PR

OK

**Comment by atian25** [comment]
land https://github.com/eggjs/awesome-egg/pull/34
