### ISSUE TITLE
webstorm里debug模式下，保存代码后，debug页面不更新

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#4523]
## What happens?
egg ^2.15.1，webstorm里debug模式下，保存代码后，debug页面不更新。
但是我旧的egg项目，"egg": "^1.10.1", webstorm里debug是正常的。

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1. webstorm里启动debug
![image](https://user-images.githubusercontent.com/5111701/99632579-6e4e4f00-2a78-11eb-8498-4df9f5f839a8.png)
2. 打开chrome debug界面
![image](https://user-images.githubusercontent.com/5111701/99632696-98077600-2a78-11eb-996f-e22c09066632.png)
3. 修改webstorm里代码，保存后，chrome debug界面里代码不更新

**Expected behavior**
1. 修改webstorm里代码，保存后，chrome debug界面里代码更新
2.

## Context
- **Node Version**: v8.11.3
- **Egg Version**: ^2.15.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:win10
![image](https://user-images.githubusercontent.com/5111701/99632399-1e6f8800-2a78-11eb-90cf-a774ff10c573.png)

**Comment by atian25** [comment]
跟 egg 关系不大，属于 Node 调试 + devtools 的使用问题，请自行解决。

**Comment by atian25** [comment]
提示：
1. 既然用 WebStorm 调试，为啥用 devtools attach？
2. 重启后，Node 的调试端口是会变的，你可以检测下 devtools attach 的是不是正确的那个新进场

**Comment by pxim** [comment]
> 提示：
> 
> 1. 既然用 WebStorm 调试，为啥用 devtools attach？
> 2. 重启后，Node 的调试端口是会变的，你可以检测下 devtools attach 的是不是正确的那个新进场

1. 因为我最新的webstorm，webstorm的debug好像有问题，都不能用，提示什么32位平台错误，但是我系统和软件都是64位的，没解决，就先用chrome debug开发了。
2. 端口没变，修改代码后，webstorm里保存，webstrom的控制台也没信息输出，是不是我webpack dev相关热更新出问题了

**Comment by pxim** [comment]
> 跟 egg 关系不大，属于 Node 调试 + devtools 的使用问题，请自行解决。

好的，谢谢

**Comment by atian25** [comment]
> > 提示：
> > 
> > 1. 既然用 WebStorm 调试，为啥用 devtools attach？
> > 2. 重启后，Node 的调试端口是会变的，你可以检测下 devtools attach 的是不是正确的那个新进场
> 
> 1. 因为我最新的webstorm，webstorm的debug好像有问题，都不能用，提示什么32位平台错误，但是我系统和软件都是64位的，没解决，就先用chrome debug开发了。
> 2. 端口没变，修改代码后，webstorm里保存，webstrom的控制台也没信息输出，是不是我webpack dev相关热更新出问题了

如果 PID 没变的话，那肯定是不对的，说明你的 devtool 连接到的还是旧的进程。

devtools 没那么智能切换 debug port 的。

**Comment by pxim** [comment]
> > > 提示：
> > > 
> > > 1. 既然用 WebStorm 调试，为啥用 devtools attach？
> > > 2. 重启后，Node 的调试端口是会变的，你可以检测下 devtools attach 的是不是正确的那个新进场
> > 
> > 
> > 
> > 1. 因为我最新的webstorm，webstorm的debug好像有问题，都不能用，提示什么32位平台错误，但是我系统和软件都是64位的，没解决，就先用chrome debug开发了。
> > 2. 端口没变，修改代码后，webstorm里保存，webstrom的控制台也没信息输出，是不是我webpack dev相关热更新出问题了
> 
> 如果 PID 没变的话，那肯定是不对的，说明你的 devtool 连接到的还是旧的进程。
> 
> devtools 没那么智能切换 debug port 的。

我知道原因了，确实和egg没关系，是我config文件夹里多个dev，里面指定了 prod。 删了这个文件就可以了。
