### ISSUE TITLE
egg生产环境静态资源路径怎么配置

### ISSUE THREAD

**Issue by munitioner** [eggjs/egg#4525]
项目vue+egg，前后端分离
**问题描述:**
前端vue上传的图片我会放在后端egg的app/public/details/目录下，
在本地环境下，后端返回给前端的图片地址是http://localhost:7001/public/details/xxx.png，这个路径在浏览器可以访问到，
部署到正式服务器后。后端返回给前端的图片地址是http://xx.xx.xx.xx/public/details/xxx.png, 这个路径在浏览器访问不到。必须在public前加api才能访问到。例如这样的路径http://xx.xx.xx.xx/api/public/details/xxx.png才能访问到图片。

**Comment by shyser** [comment]
这跟Egg没关，/api/应该是你的反向代理(如Nginx)加的前缀吧？
