### ISSUE TITLE
文件上传502

### ISSUE THREAD

**Issue by wuyugege** [eggjs/egg#4526]
我使用的是file模式

//文件上传配置
  config.multipart = {
    mode: "file",
    fields: 100,
    fileSize: "5mb",
  };

我试了小文件是没有问题的，超过1M的就不行，不是NGINX的问题，NGINX的配置我改了
keepalive_timeout 200;
client_max_body_size 5M;

最后报这个错误：upstream prematurely closed connection while reading response header from upstream,

麻烦大佬帮忙看一下

**Comment by atian25** [comment]
先排除下 nginx 干扰呗，ssh 到机器上，本机用 curl 上传大文件试试

**Comment by Liqiankun** [comment]
@wuyugege 怎么解决的？
