### ISSUE TITLE
生产环境  定时任务无法执行 

### ISSUE THREAD

**Issue by shen-lan** [eggjs/egg#4528]
```
module.exports = {
  schedule: {
    immediate: true,
    cron: '0 0 1 * * ?', //每天凌晨执行一次
    type: 'all', // 指定所有的 worker 都需要执行
  },
  async task(ctx) {
    await ctx.service.tapd.initTaskList()
    console.log('定时请求tapd生成json文件')
  },
};
```

`npm run dev` 可以执行，
npm start 就没有任何反应了 

`egg-schedule`也没有记录

**Comment by atian25** [comment]
看下 egg-schedule 源码，理解下调度过程。
然后看 `{appname}-web.log` / `egg-schedule.log` 的日志自行分析下。

**Comment by shen-lan** [comment]
> 看下 egg-schedule 源码，理解下调度过程。
> 然后看 `{appname}-web.log` / `egg-schedule.log` 的日志自行分析下。
> 
> BTW：你 console log 的日志必然不会写到日志里面。（有可能会输出到 master-stdout）
我好像定位到原因了。。。。生产环境的日志默认会写到系统目录？
`C:\Users\Administrator\logs\`
开发环境的日志是到当前项目的logs目录？

**Comment by atian25** [comment]
看下文档，写的很清楚的。

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/logger.html#%E6%96%87%E4%BB%B6%E6%97%A5%E5%BF%97

**Comment by guojinkun** [comment]
请问这个问题有解决吗 我也遇到了同样的问题
