### ISSUE TITLE
https://eggjs.org is broken

### ISSUE THREAD

**Issue by liuxing** [eggjs/egg#4532]
https://eggjs.org is broken
![image](https://user-images.githubusercontent.com/17724186/100845067-9fd30b80-34b7-11eb-841a-2d9262356aab.png)

**Comment by fomenyesu** [comment]
same problem

**Comment by blackmatch** [comment]
same problem

**Comment by blackmatch** [comment]
it's ok now

**Comment by atian25** [comment]
GFW

**Comment by JasinYip** [comment]
> GFW

不考虑搞到国内吗……

**Comment by atian25** [comment]
> > GFW
> 
> 不考虑搞到国内吗……

新文档直接在 https://eggjs.github.io/ 了，还没时间搞

**Comment by JasinYip** [comment]
👌soga
