### ISSUE TITLE
请问如何使用 egg-bin test 来测试一个指定的测试文档

### ISSUE THREAD

**Issue by hsxiaoma** [eggjs/egg#454]
请问如何使用 egg-bin test 来测试一个指定的测试文档, 如: 

/-- test
      |-- user.test.js
      |-- site.test.js

需求: 只测试 user.test.js 请都如何运行?

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/core/development.html#运行特定用例文件

**Comment by hsxiaoma** [comment]
测试用例执行时，应用是以 env: unittest 启动的,  如何操作?

F:\dev\nodejs\egg\egg-mhsq-app>set TESTS=test/service/user.test.js npm test

F:\dev\nodejs\egg\egg-mhsq-app>npm test

> egg-mhsq-app@1.0.0 test F:\dev\nodejs\egg\egg-mhsq-app
> egg-bin test

No test files found
[common-bin] run test with [] at F:\dev\nodejs\egg\egg-mhsq-app error:
Error: F:\dev\nodejs\egg\egg-mhsq-app\node_modules\egg-bin\node_modules\mocha\bin\_mocha --timeout,30000,--require,F:\dev\nodejs\egg\egg-mhsq-app\node_modules\egg-bin\node_modules\thunk-mocha\index.j
s,--require,F:\dev\nodejs\egg\egg-mhsq-app\node_modules\egg-bin\node_modules\intelli-espower-loader\intelli-espower-loader.js exit with code 1
    at ChildProcess.<anonymous> (F:\dev\nodejs\egg\egg-mhsq-app\node_modules\egg-bin\node_modules\common-bin\lib\helper.js:31:21)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Test failed.  See above for more details.

**Comment by hsxiaoma** [comment]
set TESTS=test/service/user.test.js && npm test
自己解决了.

**Comment by dead-horse** [comment]
good，可以提一个 PR 在文档里面标明一下 windows 是如何使用的

**Comment by hsxiaoma** [comment]
@dead-horse  #弱弱的请教一下，请都如何提交 PR

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/contributing.html

发自我的 iPhone
