### ISSUE TITLE
[Feature Request] Does egg will support specific NODE_OPTIONS params in the future?

### ISSUE THREAD

**Issue by netbeen** [eggjs/egg#4542]
## Background
I want to specify some NODE_OPTIONS params like --max-http-header-size to adapt large size cookie, larger than 8KB. But I cannot find anything help in the document, will egg support this feature?

## Additional context
I know it is un-normal that our site has such a large cookie, but it has run more than 5 years and no one can change this situation. for now, other App powered by express and koa has already finish the update(via --max-http-header-size), and my egg.js app seems cannot do this, pls help :(

**Comment by netbeen** [comment]
it seems other guys has the same question already, but they haven't got a clear answer. https://github.com/eggjs/egg/issues/2623  https://github.com/midwayjs/midway/issues/199

**Comment by atian25** [comment]
Of course support, `NODE_OPTIONS` is a built-in rule of Node.js.

egg-cluster will fork the workers and agent with default opts, so the parent env will be use as default.
