### ISSUE TITLE
[问题]k8s中部署eggjs应用服务可以graceful结束吗？ 处理完当前请求再退出。

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#4544]
k8s中部署，使用滚动发布时增加了egg-healthy健康探针，新pod还没ready前，流量不会到新pod上。
但如何做到让上个版本的服务优雅退出呢？
是设置环境变量EGG_MASTER_CLOSE_TIMEOUT吗？

**Comment by avtpas** [comment]
有人看吗？

**Comment by atian25** [comment]
直接 kill，会主动优雅退出。

然后也有 beforeClose 的生命周期给你去做一些处理，不过 Node 这种没状态的，其实一般也不需要。
