### ISSUE TITLE
官网dns跳转菠菜网站

### ISSUE THREAD

**Issue by Xiaofufufu** [eggjs/egg#4545]
起因是我要去官网看文档
时间是12月14日 14:10
访问 eggjs.org 第一次跳转到 **https://cksd943.com/?a0** 这个链接
谷歌浏览器访问
第二次访问正常
我的电脑已经设置dns地址
dns 223.5.5.5 223.6.6.6 
ipv6dns 2400:3200::1
谷歌浏览器插件 谷歌访问助手(http://googlehelper.net/)  CSDN开发助手
暂时只有发现eggjs.org 这个网址被跳转到菠菜网站，所以怀疑网页有挂马或者网页被劫持

哦对了，我访问的时候没有带https

**Comment by darrenliuwei** [comment]
试了几次，都是正常访问，没有复现出和楼主一样的问题。

是不是你自己的电脑出问题了？

**Comment by Xiaofufufu** [comment]
> 试了几次，都是正常访问，没有复现出和楼主一样的问题。
> 
> 是不是你自己的电脑出问题了？

不是的，我十分确定不是我的问题，我也是偶发，之前遇到过一次，没记录，这次的发Issues了，在其他网站没遇到过这种情况，要不就是只劫持了http://eggjs.org

**Comment by darrenliuwei** [comment]
> > 试了几次，都是正常访问，没有复现出和楼主一样的问题。
> > 是不是你自己的电脑出问题了？
> 
> 不是的，我十分确定不是我的问题，我也是偶发，之前遇到过一次，没记录，这次的发Issues了，在其他网站没遇到过这种情况，要不就是只劫持了http://eggjs.org

好吧，我这里试了好多遍，都没有出现你说的那种情况。
应该是个例吧，你说的这种情况我从来没有遇到过。
我也经常打开这个官网，并且打开http或自动跳转到https

**Comment by darrenliuwei** [comment]
![dns](https://user-images.githubusercontent.com/10508248/102057437-e1a17180-3e28-11eb-8d4f-ea41fb7bfef7.png)

还有，DNS推荐用：8.8.8.8 和 8.8.4.4

**Comment by atian25** [comment]
应该是你自己的问题。

**Comment by sdtm1016** [comment]
现在官网打不开了

**Comment by sdtm1016** [comment]
https://eggjs.org/

**Comment by Quekie** [comment]
官页经常挂， 是不是被攻击了啊

**Comment by Quekie** [comment]
今天挂了好多次了

**Comment by darrenliuwei** [comment]
> 现在官网打不开了

刚刚试了下，可以正常打开，没有问题。
