### ISSUE TITLE
egg-logger使用上的一些疑问

### ISSUE THREAD

**Issue by xuliuzhu1834** [eggjs/egg#4548]
很不好意思利用issue来问这个问题,但是我现在确实找不到好的或者说更优雅的方法.

### 问题:  
我想日志以 `名称.时间.log` 格式来命名.

### 痛点:
 现在只会在服务启动加载一次egg-logger插件,这样就无法做到日志文件名中时间部分的变化.

### 我现在的解决方式: 

我现在是自己定义了一个这种格式的文件

>  // logs
  common-error.log 
名称.log
....
名称.时间.log

然后将 正常log的变化全部写入`名称.时间.log`.

请问有更好的解决方式吗?

**Comment by JasinYip** [comment]
我路过看到，但我也不是特别了解，你看看 https://github.com/eggjs/egg-logrotator 这个文档里的办法是否能用？

**Comment by xuliuzhu1834** [comment]
> 我路过看到，但我也不是特别了解，你看看 https://github.com/eggjs/egg-logrotator 这个文档里的办法是否能用？

并没有找到合适的方法,这是属于日志归档了,我是想直接在`名称.日期.log`的文件里面写日志....

**Comment by atian25** [comment]
最简单的方法，你做一个 cron 任务，每天 0 点 5 分的时候，做一个软链： `名称.日期.log -> 名称.log`，就可以满足强迫症了。

**Comment by xuliuzhu1834** [comment]
> 最简单的方法，你做一个 cron 任务，每天 0 点 5 分的时候，做一个软链： `名称.日期.log -> 名称.log`，就可以满足强迫症了。

我现在就是这么做的🤣

**Comment by xuliuzhu1834** [comment]
先关闭吧,不在issue里面做讨论了,后面有谁找到优雅的方式,希望能来告诉我下😳

**Comment by atian25** [comment]
优雅是相对的，绝大部分场景，都是在日志平台消费日志的，配置好规则采集上去就好了，名字格式没啥意义的，没必要纠结。

ssh 上去看的场景，不觉得直接 tail 日志名看当前最新日志，而不需要考虑今天几号，会更优雅么？

**Comment by xuliuzhu1834** [comment]
> 优雅是相对的，绝大部分场景，都是在日志平台消费日志的，配置好规则采集上去就好了，名字格式没啥意义的，没必要纠结。
> 
> ssh 上去看的场景，不觉得直接 tail 日志名看当前最新日志，而不需要考虑今天几号，会更优雅么？

主要是为了给内部系统采集用的,采集系统按照这样的文件规则来采集的🤣
