### ISSUE TITLE
[Feature Request] 加载static目录下的html，如何传递变量参数？

### ISSUE THREAD

**Issue by quicklearning123** [eggjs/egg#4549]
## Background
我有一个前端项目，是用eggis起的server加载静态资源目录下的antdpro，是静态html，没有走视图模板。
想做多客户定制打包，想在eggjs server的环境变量增加定制参数，传给静态html。
看了官方文档https://eggjs.org/zh-cn/tutorials/assets.html 只看到模板引擎加载的传参。

## Proposal
如何传参给静态html

**Comment by hubcarl** [comment]
传参数的话，需要用模板引擎处理

**Comment by atian25** [comment]
既然是静态 HTML，自然没法。你有几种方案选择：

1. 既然是定制打包，你在构建层面直接替换掉不就行了？
2. 页面入门渲染切换为 egg 的模板引擎
