### ISSUE TITLE
service中存在文件和文件夹重名时的异常

### ISSUE THREAD

**Issue by chaorenzeng** [eggjs/egg#4555]
## 问题描述
service中存在文件和文件夹重名时，controller访问该service会报500异常

## 最小可复现仓库
https://github.com/chaorenzeng/egg-service-issue

## 复现步骤，错误日志以及相关配置
1.  添加应用文件
```js
├─controller
│      order-detail.js
│
├─extend
│      helper.js
│
├─service
│  │  order.js
│  │
│  └─order
│          detail.js
│
└─view
        orderdetail.html
```
2. 在`controller/order-detail` 里访问
```js
'use strict';

const Controller = require('egg').Controller;

class HomeController extends Controller {
  async index() {
    const { ctx } = this;
    const order = this.service.order.getOrder(); // 报错500
    const orderDetail = this.service.order.detail.getOrderDetail();
    const msg = {
      order,
      orderDetail,
    };
    await ctx.render('orderdetail', {
      ...msg,
    });
  }
}

module.exports = HomeController;
```
3. 访问http://127.0.0.1:7001/orderDetail 报500异常

## 相关环境信息
- **操作系统**：win10 64bit
- **Node 版本**：14.15.1
- **Egg 版本**：2.15.1

## 个人方案 
- 分析：service中文件和文件夹作为类存在，同属于目录对象中的属性。当文件夹与文件同级且同名时，该对象里有两个相同的属性从而报异常。
- 解决：同级且同名的文件加前缀/后缀，在访问该重名文件时加前缀/后缀

**Comment by atian25** [comment]
不支持同名，前缀你可以自己加。

`ctx.service.order.xx` 没法判断是目录里面的 xx.js 还是 order.js 里面的 xx()
