### ISSUE TITLE
egg项目部署服务器报错

### ISSUE THREAD

**Issue by NarutoKobe** [eggjs/egg#4560]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by darrenliuwei** [comment]
具体是什么报错呢？

**Comment by bulolo** [comment]
官网都挂了

**Comment by darrenliuwei** [comment]
> 官网都挂了

刚刚看了，可以正常访问。

**Comment by atian25** [comment]
hey, we need more information to follow up this issue, recommend using `npm init egg --type=simple` to provide a mini project and upload to your GitHub.

for now, it will close due to lack of activity, feel free to reopen this issue if provided more information.
