### ISSUE TITLE
初始化项目时node版本老出问题

### ISSUE THREAD

**Issue by Brolly0204** [eggjs/egg#4562]
## What happens?
运行yarn create egg --type=simple
node为8.x时 报如下错误
![image](https://user-images.githubusercontent.com/16096724/103664456-41fd7c00-4fad-11eb-970a-bec6db10964a.png)

node为12.x报如下错误
![image](https://user-images.githubusercontent.com/16096724/103664548-5ccff080-4fad-11eb-8c4b-ead9a1be3388.png)

## How To Reproduce

**Steps to reproduce the behavior:**
1.yarn create egg --type=simple

**Expected behavior**
1.成功创建egg项目

## Context
- **Node Version**: 8.x 10.x 12.x
- **Egg Version**: 2.29.1
- **Platform**: macOS 10.15.7

**Comment by Brolly0204** [comment]
暂时这样解决了 不知道是否正确
```shell
 yarn config set ignore-engines true
```

**Comment by bulolo** [comment]
官网挂了

**Comment by Brolly0204** [comment]
> 官网挂了

是的

**Comment by darrenliuwei** [comment]
> > 官网挂了
> 
> 是的

现在应该是恢复了，可以正常访问。

**Comment by atian25** [comment]
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

https://github.com/eggjs/egg-init/blob/master/package.json#L63
