### ISSUE TITLE
eggjs 官网挂了 ，乌鸦飞

### ISSUE THREAD

**Issue by skylence** [eggjs/egg#4565]
https://eggjs.org/  打不开官网

**Comment by skylence** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙访问。

已经翻墙了，还是打不开

**Comment by darrenliuwei** [comment]
> > 由于某些众所周知的原因无法访问，建议翻墙访问。
> 
> 已经翻墙了，还是打不开

可以正常打开呀！

**Comment by xuliuzhu1834** [comment]
翻墙也打不开了

**Comment by wuyeguangming** [comment]
+1

**Comment by darrenliuwei** [comment]
> 翻墙也打不开了

刚刚试了下，可以正常打开，应该是你翻墙姿势不对。
