### ISSUE TITLE
eggjs.org 文档网站打不开，实在找不到反馈的地方

### ISSUE THREAD

**Issue by pkjy** [eggjs/egg#4566]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:
- **Egg Version**:
- **Plugin Name**:
- **Plugin Version**:
- **Platform**:

**Comment by pkjy** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙访问。

我是翻墙的，刚才恢复了一会，现在又访问不了了。

**Comment by darrenliuwei** [comment]
> > 由于某些众所周知的原因无法访问，建议翻墙访问。
> 
> 我是翻墙的，刚才恢复了一会，现在又访问不了了。

刚刚看了，可以正常访问！
