### ISSUE TITLE
按照教程部署到服务器（Ubuntu  20.04 64位） 但是一直报下面错误 

### ISSUE THREAD

**Issue by wujianling** [eggjs/egg#4571]
verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/var/www/robot-egg/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 4ms
19 verbose npm-session 8645e634cc8a607c
20 timing npm:load Completed in 10ms
21 timing command:run-script Completed in 146ms
22 timing command:start Completed in 148ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
24 verbose pkgid robot-egg@1.0.0
25 verbose cwd /var/www/robot-egg
26 verbose Linux 5.4.0-54-generic
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v15.5.1
29 verbose npm  v7.3.0
30 error code 1
31 error path /var/www/robot-egg
32 error command failed
33 error command sh -c egg-scripts start --port=6009 --daemon --title=robot-egg --ignore-stderr
34 verbose exit 1

**Comment by atian25** [comment]
这是 NPM 报错。

看下文档，找 home 目录的 common-error 日志看。
