### ISSUE TITLE
Service 抓取 Hacker News 的接口数据超时

### ISSUE THREAD

**Issue by xiaoxiao0203** [eggjs/egg#4572]
// app/service/news.js
const Service = require('egg').Service;

class NewsService extends Service {
  async list(page = 1) {
    // read config
    const { serverUrl, pageSize } = this.config.news;

    // use build-in http client to GET hacker-news api
    const { data: idList } = await this.ctx.curl(`${serverUrl}/topstories.json`, {
      data: {
        orderBy: '"$key"',
        startAt: `"${pageSize * (page - 1)}"`,
        endAt: `"${pageSize * page - 1}"`,
      },
      dataType: 'json',
    });

    // parallel GET detail
    const newsList = await Promise.all(
      Object.keys(idList).map(key => {
        const url = `${serverUrl}/item/${idList[key]}.json`;
        return this.ctx.curl(url, { dataType: 'json' });
      })
    );
    return newsList.map(res => res.data);
  }
}

module.exports = NewsService;

- 
![image](https://user-images.githubusercontent.com/25219989/104283082-f84fec80-54ea-11eb-9241-b3782e6ed0aa.png)

**Comment by atian25** [comment]
Hacker News 接口被墙了。

**Comment by xiaoxiao0203** [comment]
有什么其他的接口可以访问吗？求大佬告知

**Comment by atian25** [comment]
这只是 HTTP 请求的示例代码。你自己找个国内的类似实现下即可，如 cnode 啥的。
或者 terminal 翻墙后访问。

**Comment by xiaoxiao0203** [comment]
好的，谢谢
