### ISSUE TITLE
执行 ctx.rotateCsrfSecret(),http response中没有 x-csrf-Token

### ISSUE THREAD

**Issue by sinceseason** [eggjs/egg#4574]
```
 // config.default.ts
  config.security = {
    csrf: {
	headerName: "x-csrf-token", // 自定义请求头
	ignore: ['/api/user/login']
    },
  }
```
 ```
 // userController /api/user/login
    async login() {
        const ctx = this.ctx;
        ctx.rotateCsrfSecret()
        ctx.body = {
            name: 'test'
        };
    }
```

**Comment by sinceseason** [comment]
![image](https://user-images.githubusercontent.com/14029440/104396924-9644c500-5586-11eb-8745-fb65b8044bfe.png)

**Comment by atian25** [comment]
response headers 本来就不会返回 x-csrf-Token 啊，这个 key 是 request header 校验用的。

https://github.com/eggjs/egg-security/blob/79c38e001b431466361c711680d975eb0cfcb301/app/extend/context.js#L140

**Comment by sinceseason** [comment]
> response headers 本来就不会返回 x-csrf-Token 啊，这个 key 是 request header 校验用的。
> 
> 遇事不决看源码：https://github.com/eggjs/egg-security/blob/79c38e001b431466361c711680d975eb0cfcb301/app/extend/context.js#L140

问错了，是前端访问接口时，request header中带上 x-csrf-token。但是登录接口是没有这个的，所以调用 rorateCsrfToken()，理论上讲返回的http中，cookie应该带上 csrfToken, 前端获取后在接下来每个请求头带上这个。 但是目前情况是cookie中没有返回该信息？

**Comment by atian25** [comment]
可以跟下那段代码的执行过程
