### ISSUE TITLE
不走自定义配置文件环境的配置,

### ISSUE THREAD

**Issue by niuernihao** [eggjs/egg#4576]
自定义了一个config.mange.js的配置文件,命令:NODE_ENV=production EGG_SERVER_ENV=mange  npm start 启动,为什么还是使用的config.prod.js配置文件环境的配置

**Comment by atian25** [comment]
一般正式环境就是 prod，自定义环境指的是开发周期中的自定义环境，如 sit 啥的。

这种场景可以通过 scope 的方式来解决：

`config.mange_prod.js` + `EGG_SERVER_SCOPE= mange`

可以看下 egg-core 对应的逻辑：https://github.com/eggjs/egg-core/blob/99ef7541b80f73ec4f616628454afde717495f9f/test/loader/mixin/load_plugin.test.js#L547

**Comment by niuernihao** [comment]
好的,可以了
