### ISSUE TITLE
DevTools 地址的协议名称需要修改： chrome-devtools 改为 devtools

### ISSUE THREAD

**Issue by xuchaobei** [eggjs/egg#4577]
npm run debug 启动程序时，控制台输出的 DevTools 地址的协议名称，如下所示，应该由 chrome-devtools 改为 devtools，chromium 2020年3月已经做了[修改](https://chromium.googlesource.com/chromium/src/+/6700d12448f76712c62a6d2372a95b97a26d4779)。

```
Debug Proxy online, now you could attach to 9999 without worry about reload.
DevTools → chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9999/__ws_proxy__
```

现在在chrome浏览器中直接使用  chrome-devtools 作为协议名，将会被视为搜索关键词，无法打开正确的调试页面。

**Comment by saitoChen** [comment]
same question

**Comment by saitoChen** [comment]
same issuse

**Comment by atian25** [comment]
来个 PR 吧，egg-bin 那边

**Comment by xuchaobei** [comment]
> 来个 PR 吧，egg-bin 那边
追了一下，是 egg-bin 依赖的包 inspector-proxy 的问题。已经有人提了 [PR](https://github.com/whxaxes/inspector-proxy/pull/3) 了，但是貌似这个项目已经很久没更新了。

**Comment by whxaxes** [comment]
@xuchaobei  之前没留意，我来合一下

**Comment by whxaxes** [comment]
已经合了，发版本了 1.2.2 ...
