### ISSUE TITLE
官网挂了？

### ISSUE THREAD

**Issue by wuyeguangming** [eggjs/egg#4581]
## What happens?
官网挂了？

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by wuyeguangming** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙访问。

翻墙也挂..

**Comment by darrenliuwei** [comment]
> > 由于某些众所周知的原因无法访问，建议翻墙访问。
> 
> 翻墙也挂..

说明你翻墙姿势有问题，可以正常打开。
