### ISSUE TITLE
egg项目使用socket.io-client无法正常连接到socket服务

### ISSUE THREAD

**Issue by iamsea** [eggjs/egg#4588]
## What happens?
egg项目A使用socket.io-client去连接另一个egg socket.io项目B，B能收到连接请求，但A一直连接不上反复重试。注：B项目的socket服务测试正常。

**Comment by iamsea** [comment]
是socket.io-client使用的socket.io版本太高了，问题已经解决谢谢

**Comment by aisriver** [comment]
我也遇到了这个问题，egg-socket.io是不是需要升级一下，或者readme写一下socket.io-client支持的版本

**Comment by ruandao** [comment]
我也遇到这个问题了。。。一样是版本太低的原因

**Comment by doornot** [comment]
参考 https://www.npmjs.com/package/@bonetm/egg-socket.io

"dependencies": {
  "socket.io-client": "^4.2.0",
  "@bonetm/egg-socket.io": "^4.2.7"
}

**Comment by doornot** [comment]
可以参考 https://www.npmjs.com/package/@bonetm/egg-socket.io

“基于作者最后 4.1.6 一版更新 egg 框架的 socket.io 插件 原作者许久未更新， 将 socket.io 升级到了 3.0。packet 的 middleware 去掉了”
