### ISSUE TITLE
sameSite 设置无效

### ISSUE THREAD

**Issue by ssshooter** [eggjs/egg#4595]
sameSite 设置无效

```javascript
module.exports = {
  cookies: {
    sameSite: 'none',
  },
};
```

## 复现步骤，错误日志以及相关配置

cookies 成功写入，但没遇 sameSite none

## 相关环境信息
- **操作系统**：windows10
- **Node 版本**：v12.18.0
- **Egg 版本**：2.29.1

是否需要配置其他参数？或者引入插件？

**Comment by ssshooter** [comment]
或者是因为版本升级操作有问题？顺便问一下如何进行版本升级

**Comment by gemwuu** [comment]
给下最小复现代码仓库

**Comment by ssshooter** [comment]
解决了，session 的  sameSite 属性不归 cookies 配置管，这样就行了：

```javascript
config.session = {
    key: 'EGG_SESS',
    maxAge: 24 * 3600 * 1000 * 30, 
    httpOnly: true,
    encrypt: true,
    secure: true,
    sameSite: 'None',
  }
```

**Comment by AntiMoron** [comment]
![image](https://user-images.githubusercontent.com/6587734/234863467-7a9bbb1f-1007-4653-bd94-1e0ac0ea8bbc.png)

![image](https://user-images.githubusercontent.com/6587734/234863824-6743b473-0edd-4bfb-86c6-c612f47de3c8.png)

（sameSite: "None"我也试过了）
这当初issue咋关的？

**Comment by woaixiangbao** [comment]
> session
我个你一样，也是设置了都无效

**Comment by yisibl** [comment]
如果是本地环境，需要确保是 https，另外只有在 `secure` 为 true 时才能设置 sameSite。详见：https://web.dev/articles/samesite-cookies-explained?hl=zh-cn#samesitenone_must_be_secure
