### ISSUE TITLE
egg-oss下载文件

### ISSUE THREAD

**Issue by brucewar** [eggjs/egg#4601]
`ali-oss`官方提供的例子是下载到本地(验证通过)，我的需求是通过egg.js转发到前端，通过如下代码，发现前端报错“网页可能暂时无法连接，或者它已永久性地移动到了新网址。”，后台nginx报404.
```js
const result = await this.ctx.oss.getStream('object-name');
this.ctx.body = result.stream;
```

**Comment by atian25** [comment]
为啥不直接给对应的 cdn 地址给前端？

**Comment by brucewar** [comment]
> 为啥不直接给对应的 cdn 地址给前端？

因为我的那个bucket是私有的，不想让前端直接访问

**Comment by atian25** [comment]
可以根据报错自行排查下，或者提供可复现的最小仓库。

getStream 我没怎么用过，一般就直接用 cdn 的地址，代理的话也可以是 curl 这个 cdn 地址来代理一层。
