### ISSUE TITLE
路由动态参数不支持正则表达式限定

### ISSUE THREAD

**Issue by momouwei** [eggjs/egg#4604]

**Comment by momouwei** [comment]
不能像react-router那样支持用正则表达式来限定动态参数
比如:
    /test/:id(\d+)，限定id为数字

**Comment by zhangxh1023** [comment]
```js
router.get(/test\/(\d+)/, controller.xxxxx);
```

感觉这样也能满足需求的吧.

**Comment by sinkhaha** [comment]
这样也可以实现`router.get('/test/:id(\\d+)',  xxxxxx);` egg的路由匹配用的是`path-to-regexp`库

**Comment by atian25** [comment]
如上，可以看下文档 https://github.com/pillarjs/path-to-regexp#custom-matching-parameters
