### ISSUE TITLE
疑似插件egg-prometheus引起的egg-agent日志超大问题

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#4606]
## 背景

项目使用eggjs三年多，最近使用了egg-prometheus插件

## 现象

生产环境 Pod 里的 xxx-egg-agent.log 竟然达到了1T

![image](https://user-images.githubusercontent.com/9158889/107162180-68fc0300-69dc-11eb-9eae-2bd840f7dc58.png)

日志太大，使用tail -n 10  xxx-egg-agent.log >> a.txt ，日志如下，几乎全部都是数字，最后有点信息是`"packetId":15764}, maybe it's timeout. `，怀疑是egg-prometheus引起的，但不确定，在egg-prometheus仓库中可以搜索到关键字 [packetId](https://github.com/eggjs/egg-prometheus/search?q=packetId)。 

## 日志截图
![image](https://user-images.githubusercontent.com/9158889/107162089-d196b000-69db-11eb-8bb9-d05179d15852.png)

## 其他

测试环境没有重现这个问题，已经关闭了这个插件

**Comment by jgchenu** [comment]
@logzh 这个问题本地debug看了下，感觉跟超时有关，你们后续有解决这个问题嘛

**Comment by jgchenu** [comment]
@gxcsoccer 提了一个PR，有空麻烦看看，目前按照新的修改已经在项目中投入使用并且日志膨胀问题得到解决

**Comment by xjzsq** [comment]
我在测试环境也遇到了这个问题，egg-agent.log和common-error.log文件大小分别暴增到了125G，把我C盘直接吃满了
![屏幕截图 2022-11-05 182808](https://user-images.githubusercontent.com/13806783/200115984-c27aab24-526e-4b2e-9067-7c102c90d9ae.jpg)

**Comment by LeeKaWai** [comment]
我刚做了一个小demo, 也发现了egg-agent.log和common-error.log文件大小 1天不到就达到了每个文件27G，不知为何缘故

![WX20221116-093227](https://user-images.githubusercontent.com/12006703/202061332-66e09688-e4b1-4852-9937-c5f403405b08.png)
