### ISSUE TITLE
您好，咨询个东西，这边走多核，但是发现，如果控制器中出现计算量大的处理(如死循环)，会导致别的请求完全停止

### ISSUE THREAD

**Issue by caihaibin1991** [eggjs/egg#4615]
场景重现:
单电脑
控制器:
一个死循环.
咨询个东西，这边走多核，但是发现，如果控制器中出现计算量大的处理(如死循环)，会导致服务完全停止. 请问这边有没有办法怎么处理？如果走多核，一个执行中，是否可以走另一个？

**Comment by caihaibin1991** [comment]
测试下来，发现 --sticky 模式就会. 不走--sticky 就不会。但是这样又会导致程序数据乱了

**Comment by gemwuu** [comment]
请提供下最小复现代码仓库

**Comment by caihaibin1991** [comment]
已解决，取消--sticky，缓存和相关集中到redis
socket.io改成egg-websocket-plugin 走redis.
