### ISSUE TITLE
请问下各位，cdn静态资源大家是如何做的呢？

### ISSUE THREAD

**Issue by XIONGchanghu** [eggjs/egg#4618]
我现在把前端用到的所有img.css.js都放在public，发布代码的时候一起放cdn上面，那么问题来了，我本地开发和正式环境的模板页面比如引入/public/test.css，我应该需要在这个前面加一个cdn的域名，那么我本地开发的时候，如果加了这个域名这个时候cdn上面暂时是没有这些文件的 怎么处理呢？

**Comment by klren0312** [comment]
本地代理一下

**Comment by XIONGchanghu** [comment]
@klren0312 大佬怎么弄的呢 求指导

**Comment by klren0312** [comment]
最简单的 你本地配host把cdn域名指向你本地资源服务的ip

**Comment by klren0312** [comment]
刚好看到了个例子 
https://lightproxy.org/zh-CN/doc/use-with-umi-antd-pro#%E8%BD%AC%E5%8F%91%E6%96%87%E4%BB%B6

**Comment by fengmk2** [comment]
非 egg 相关问题。

**Comment by XIONGchanghu** [comment]
3q
