### ISSUE TITLE
启用egg-alinode插件，应用运行成功，但是每隔一段时间会报错

### ISSUE THREAD

**Issue by jc1144096387** [eggjs/egg#4621]
本地运行错误信息
![image](https://user-images.githubusercontent.com/32624612/109131846-24b78380-778e-11eb-985c-453f3b041118.png)

线上部署错误日志
![image](https://user-images.githubusercontent.com/32624612/109131894-31d47280-778e-11eb-9a98-5ea6fbed5e5e.png)

![image](https://user-images.githubusercontent.com/32624612/109131918-3a2cad80-778e-11eb-966b-0170d2fc191d.png)

**Comment by gemwuu** [comment]
alinode 暂时不支持 Windows，需要将 egg-alinode 插件去掉。
