### ISSUE TITLE
http 响应状态码格式 

### ISSUE THREAD

**Issue by binbobo** [eggjs/egg#4622]
响应状态码格式可以只返回数字么
比如 status code: 200
现在返回的是字符串  status code: '200 OK'

这个问题如何设置呢

**Comment by zhangxh1023** [comment]
你指的是 statusMessage 么。

如果是这个的话，你设置为空：
```
    ctx.response.status = 200;
    ctx.response.message = '';
```
Nodejs 会自动给它加上的。最后还是会变成 `200 OK`。

不过 http 客户端不是应该会自动解析成 200 的吗

**Comment by binbobo** [comment]
> 你指的是 statusMessage 么。
> 
> 如果是这个的话，你设置为空：
> 
> ```
>     ctx.response.status = 200;
>     ctx.response.message = '';
> ```
> 
> Nodejs 会自动给它加上的。最后还是会变成 `200 OK`。
> 
> 不过 http 客户端不是应该会自动解析成 200 的吗

我用chrome和postman都解析成了 '200 OK'，这是原生NodeJS决定的么,我用原生Nodejs起了个服务，返回的也是字符串格式的  能不能在哪里修改一下啊，我看Java写的接口返回的是数字200，不是字符串

**Comment by zhangxh1023** [comment]
> > 你指的是 statusMessage 么。
> > 如果是这个的话，你设置为空：
> > ```
> >     ctx.response.status = 200;
> >     ctx.response.message = '';
> > ```
> > 
> > 
> > Nodejs 会自动给它加上的。最后还是会变成 `200 OK`。
> > 不过 http 客户端不是应该会自动解析成 200 的吗
> 
> 我用chrome和postman都解析成了 '200 OK'，这是原生NodeJS决定的么,我用原生Nodejs起了个服务，返回的也是字符串格式的 能不能在哪里修改一下啊，我看Java写的接口返回的是数字200，不是字符串

这个是 Nodejs 返回的。而且似乎不能为空，除非你传一个空格。
但是。。。 我还是觉得这个没影响呀。只要是 200，就可以了呀。

**Comment by binbobo** [comment]
> > > 你指的是 statusMessage 么。
> > > 如果是这个的话，你设置为空：
> > > ```
> > >     ctx.response.status = 200;
> > >     ctx.response.message = '';
> > > ```
> > > 
> > > 
> > > Nodejs 会自动给它加上的。最后还是会变成 `200 OK`。
> > > 不过 http 客户端不是应该会自动解析成 200 的吗
> > 
> > 
> > 我用chrome和postman都解析成了 '200 OK'，这是原生NodeJS决定的么,我用原生Nodejs起了个服务，返回的也是字符串格式的 能不能在哪里修改一下啊，我看Java写的接口返回的是数字200，不是字符串
> 
> 这个是 Nodejs 返回的。而且似乎不能为空，除非你传一个空格。
> 但是。。。 我还是觉得这个没影响呀。只要是 200，就可以了呀。

是 字符串格式的也是标准的，都是按照rfc标准来的  只是我们这边有个客户端封装的http请求，对http状态码做了统一判断，来执行不同处理。他们判断的逻辑是就判断标准的数字类型的状态码，现在nodejs是字符串，他们得做兼容。基于这个问题，我也产生了好奇，为什么有的后端返回的是数字，有的却是字符串，这个到底是基于什么来设计的

**Comment by zhangxh1023** [comment]
Nodejs 的话，就是这里，没传 statusMessage ，[给一个默认值](https://github.com/nodejs/node/blob/master/lib/_http_server.js#L281)，然后 [拼接](https://github.com/nodejs/node/blob/master/lib/_http_server.js#L322)

**Comment by atian25** [comment]
https://tools.ietf.org/html/rfc2616#section-6.1

HTTP 规范来着，让你们客户端改吧，他们实现的不好，没遵循规范。按理说这些都是标准类库来着，难道他们自己解析 HTTP 响应体？
