### ISSUE TITLE
使用egg-socket.io中socket.emit(object)时遇到bug

### ISSUE THREAD

**Issue by tmkmk** [eggjs/egg#4624]
## What happens?

在 app/io/middleware/auth.ts中如下代码
const { app, socket, logger, helper, service } = ctx;
此时使用 socket.emit(msg)时.
msg不能有成员 ret.如果存在了.则无法发送消息.
想要完整的发送消息出去.必须将数据结构改为
`
obj={data:{action:"deny",payload:obj}} ;
`
这种形式才可

## 最小可复现仓库
> 暂时没有.问题比较清楚

## 复现步骤，错误日志以及相关配置
参照问题描述

## 相关环境信息
- **操作系统**：windows10 20h2
- **Node 版本**：14.15.3
- **Egg 版本**：^2.2.1
- **egg-socket.io版本**: ^4.0.7

**Comment by gemwuu** [comment]
看下项目中是不是加了 helper 之类的格式化函数

**Comment by tmkmk** [comment]
> 看下项目中是不是加了 helper 之类的格式化函数

怪我没有说清楚.使用的就是官方提供的demo-egg-socket.io这个项目.里面有个helper 是吧要发送的数据给格式化成
`
{
  meta: { timestamp: xxx },
  data: {
    action: "deny",
    payload: "需要发送的数据",
  }
}
`
这种形式

**Comment by gemwuu** [comment]
> > 看下项目中是不是加了 helper 之类的格式化函数
> 
> 怪我没有说清楚.使用的就是官方提供的demo-egg-socket.io这个项目.里面有个helper 是吧要发送的数据给格式化成
> `{ meta: { timestamp: xxx }, data: { action: "deny", payload: "需要发送的数据", } }`
> 这种形式

demo 也仅是示例，可以按照这个实践来。如果想自己定制，可以去掉 helper，参照 [example](https://github.com/eggjs/egg-socket.io/blob/master/example/package.json)
