### ISSUE TITLE
nodejs.SequelizeDatabaseError: Column 'userId' specified twice

### ISSUE THREAD

**Issue by huberystyle** [eggjs/egg#4625]
nodejs.SequelizeDatabaseError: Column 'userId' specified twice

//  创建关联数据的时候报这个错是啥意思？
await ctx.model.UserRole.create({
        userId,
        roleId,
      }, {
        transaction,
      });

**Comment by gemwuu** [comment]
这是 Sequelize 的报错跟 eggjs 无关，请 google 解决。

**Comment by huberystyle** [comment]
哦 用的是 egg-sequelize  这个插件，按官方demo写的，搞不懂哪个地方出问题了！ @gemwuu

**Comment by gemwuu** [comment]
egg-sequelize 只是 Sequelize 的适配，没有具体的实现的。这里的报错是 `SequelizeDatabaseError` 类型，是 Sequelize 抛出的错误，搜索一下很容易解决的。
