### ISSUE TITLE
eggjs不支持pnpm

### ISSUE THREAD

**Issue by ilyp** [eggjs/egg#4627]
## What happens?

eggjs不支持**pnpm**

## 复现步骤，错误日志以及相关配置

1. 使用pnpm安装依赖
2. 启动后在加载plugin时报错：
`Error: Can not find plugin egg-onerror in "projectDir/node_modules, projectDir/node_modules/.pnpm/egg@2.29.3/node_modules/egg/node_modules, projectDir/node_modules"`

## 相关环境信息
- **操作系统**：macOS Big Sur 11.2.1
- **Node 版本**：v14.16.0
- **Egg 版本**：2.29.3

**Comment by gemwuu** [comment]
[L349](https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/plugin.js#L349)，pnpm 子依赖没有 node_modules，这里需要额外支持下。

**Comment by gemwuu** [comment]
@ilyp 欢迎 PR。

**Comment by qingdengyue** [comment]
感觉好复杂的样子。
https://pnpm.js.org/installation#compatibility
不同版本的pnpm对node版本的要求不一样，而且没有向下兼容,版本也挺多的。
![image](https://user-images.githubusercontent.com/3230673/110280601-1121dd80-8016-11eb-92a9-b84f59d31e87.png)

@atian25 这种的有啥比较好的办法可以，走CI？

**Comment by fengmk2** [comment]
@ilyp 你是 pnpm 那个版本？

**Comment by ilyp** [comment]
> @ilyp 你是 pnpm 那个版本？

nodejs版本是12、14，pnpm 是 5

**Comment by fengmk2** [comment]
> @fengmk2
> nodejs版本是12、14，pnpm 是 5

pnpm6 也是一样的问题吗？

**Comment by ilyp** [comment]
> > @fengmk2
> > nodejs版本是12、14，pnpm 是 5
> 
> pnpm6 也是一样的问题吗？

**Comment by ilyp** [comment]
@fengmk2 目前使用`pnpm install --shamefully-hoist`, 解决了插件不能加载的问题，可以运行项目。顺便我在本地运行了egg、egg-core的单元测试，发现 https://github.com/power-assert-js/intelli-espower-loader 这个包不支持pnpm。我改了一下相关代码 https://github.com/power-assert-js/intelli-espower-loader/pull/22，就可以运行单元测试了。

**Comment by aidening** [comment]
哈喽，我运行了这串代码，但是还是有同样的问题出现

**Comment by Riunshow** [comment]
> 哈喽，我运行了这串代码，但是还是有同样的问题出现

pnpm 6.23.6 
运行 `pnpm install --shamefully-hoist` 解决了

**Comment by Riunshow** [comment]
> 哈喽，我运行了这串代码，但是还是有同样的问题出现

pnpm 6.23.6 
运行 `pnpm install --shamefully-hoist` 解决了
