### ISSUE TITLE
使用模板引擎，怎样将数据渲染到js中？

### ISSUE THREAD

**Issue by jiaicon** [eggjs/egg#4629]
async home() {
    await this.ctx.render('dist/index.html', {
      context: {
        // user: this.ctx.session.userInfo,
        user: {
          id: 1,
          name: 'abc',
        },
      },
    });
  }
比如使用egg-view-nunjucks，有没有什么方法，将context值写进前端window中

**Comment by jiaicon** [comment]
![image](https://user-images.githubusercontent.com/34124517/109947038-db2de200-7d13-11eb-9e6f-d97bd57d452c.png)

PHP中有这样写法，不知道这里支持不？

**Comment by gemwuu** [comment]
是支持的，请参照 [nunjucks 文档](https://mozilla.github.io/nunjucks/cn/templating.html)。

**Comment by jiaicon** [comment]
> 是支持的，请参照 [nunjucks 文档](https://mozilla.github.io/nunjucks/cn/templating.html)。

你好  我查了下文档   貌似没有那种写法   能给个例子吗？

**Comment by atian25** [comment]
```html
<script>
  windows.xx == {{ someVar | json | safe }};
</script>
```

类似这样，其实就是拼字符串而已，可以查下 nunjucks 文档

**Comment by jiaicon** [comment]
> ```
> someVar | dump | safe
> ```

嗯嗯  看到了   感谢!!!
