### ISSUE TITLE
> 是支持的，请参照 [nunjucks 文档](https://mozilla.github.io/nunjucks/cn/templating.html)。

### ISSUE THREAD

**Issue by jiaicon** [eggjs/egg#4631]
> 是支持的，请参照 [nunjucks 文档](https://mozilla.github.io/nunjucks/cn/templating.html)。

你好  我查了下文档   貌似没有那种写法   能给个例子吗？

_Originally posted by @jiaicon in https://github.com/eggjs/egg/issues/4629#issuecomment-791083924_

**Comment by atian25** [comment]
在那边已经回答
