### ISSUE TITLE
安卓系统下运行 npm start 出错

### ISSUE THREAD

**Issue by conkyliu** [eggjs/egg#4633]
使用了react-native引进[nodejs-mobile-react-native包](https://github.com/JaneaSystems/nodejs-mobile-react-native) ，运行npm start 时报错
![image](https://user-images.githubusercontent.com/26617741/110911341-8a3e6f00-834d-11eb-9e8f-17cccbebd396.png)
![image](https://user-images.githubusercontent.com/26617741/110911442-af32e200-834d-11eb-8399-f239bc623e57.png)

**Comment by gemwuu** [comment]
参照下 nodejs-mobile-react-native 的文档，子进程在移动端是不允许 fork/spawn 的。
[链接 1](https://code.janeasystems.com/nodejs-mobile/nodejs-apis-differences#child_process-cluster-modules)，[链接 2](https://code.janeasystems.com/nodejs-mobile/faq#are-all-nodejs-apis-supported-on-mobile)，
