### ISSUE TITLE
一直显示这样，应该怎么改？

### ISSUE THREAD

**Issue by Eings** [eggjs/egg#4636]
![image](https://user-images.githubusercontent.com/48080567/111880270-692cec80-89e5-11eb-85c6-68ad3df03394.png)
![image](https://user-images.githubusercontent.com/48080567/111880288-882b7e80-89e5-11eb-9a78-7eb5d6779fec.png)

**Comment by gemwuu** [comment]
错误已经提示的很明显了，`config.keys` 没有配置，对比你的截图，应该能看出问题的。
