### ISSUE TITLE
[Feature Request] 事务对象挂载到ctx上，是安全的吗？

### ISSUE THREAD

**Issue by Hill1126** [eggjs/egg#4637]
## Background
我想在egg中使用mysql的事务，但是create数据的方法分散在各个封装的方法中，我不想每一个方法都传入一个事务对象。

## Proposal
如果在创建开始前，我将该事务对象挂载到ctx上，然后在各个方法中使用，这个想法可以做吗？

**Comment by hyj1991** [comment]
ctx 生命周期 = 请求的生命周期，挂载到 ctx 上的对象生灭自身应当也遵循请求生命周期，否则不需要这么做
