### ISSUE TITLE
多进程研发模式增强问题的一些请教

### ISSUE THREAD

**Issue by yxw13141618** [eggjs/egg#4638]
请问如果我希望代码只运行在一个进程，当收到数据后，再通知其他的进程，例如：监听数据库的通知等等，这种情况我该什么地方来写只运行在一个进程上的代码呢？现在是写在了schedule定时器的目录下，但我觉得这并不是最好的选择，请问大家有什么好的办法吗？谢谢。

**Comment by JasinYip** [comment]
使用 Agent 进程

**Comment by yxw13141618** [comment]
@JasinYip  非常感谢您的回复  嗯嗯 我最开始也是用的Agent进程，但是因为我需要只在一个进程中运行的代码还挺多的  不知道这样污染和占用Agent进程是否合适，

**Comment by JasinYip** [comment]
Agent 本身就是被设计为可以执行少量业务代码的，如果你确实有大量需要进行的计算，应该通过 IPC 转交给 Worker 来进行。Agent 应该就是做一些像你提到的监听数据库通知等操作。

**Comment by JasinYip** [comment]
看你自己的业务场景判断吧

**Comment by JasinYip** [comment]
> pub\sub可以只通知一个工作进程吗？

我理解是不可以

**Comment by yxw13141618** [comment]
好的 那还是先用IPC吧 我也觉得在JSON上做手脚不太好。
