### ISSUE TITLE
[Feature Request] 想了解下然后设置 资源的预加载

### ISSUE THREAD

**Issue by nichangchun** [eggjs/egg#4640]
## Background
egg+vue+ssr ，想让资源在服务端渲染的时候，自动加上 preload，一直不生效，不知道如何设置？

期望 js 、css、字体 相关 <link rel=preload> 
## Proposal

已经设置了 shouldPreload，但是貌似不行，

  exports.vuessr = {
    doctype: '',
    layout: path.join(app.baseDir, 'app/web/view/layout.html'),
    // inject: false,
    renderOptions: {
      basedir: path.join(app.baseDir, 'app/view'),
      shouldPreload: (file, type) => {
          return true  
      }
    },
}

**Comment by atian25** [comment]
找下对应的插件作者问问
