### ISSUE TITLE
[RFC] egg-scripts proposals

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#465]
https://github.com/eggjs/egg/issues/241 太长了，重开一个，讨论第一期的实现方案。

仅提供 `egg-scripts start` 和 `egg-scripts stop` 几条最基础的线上指令。
而看了下原内网的实现，会比较依赖于环境变量，本方案更倾向于用 cli options 的方式

原提案[点击此处](https://gist.github.com/atian25/17ed254f73268abd38d6a1d0102d5eb3),  以下正文更新为讨论后的：

## start

```bash
$ egg-scripts start [baseDir] --port=7001 --env=prod --workers=2 --no-daemon
```

**description ：**

- master 进程上提供 `egg-server` 之类的关键词，用于 grep

** arguments: **
- `baseDir` 为应用的根目录，可选，默认为 `process.cwd()`，支持相对路径

**options ：**
- `port` 为端口，可选，默认为 7001，不做冲突自动更换端口。
- `env` 为运行环境，可选，默认为 `prod` 
  - ~~大小写不敏感，内部会统一转换为小写~~
  - 环境变量取值顺序  env 传值  -> EGG_SERVER_ENV 环境变量 -> 默认值 prod
- `workers` 配置 workers 个数
- `no-daemon` 配置该参数则在前台运行
- `framework` 框架名，一般不需要填，自动检测
- `title` 关键词，用于 grep，默认为 `egg-server-APPNAME`

## stop

```bash
$ egg-scripts stop [baseDir]
```

**description ：**
  - 找到指定目录下的 egg master 进程，并 kill 掉
  - 在 5s 后，寻找没有被 egg master 优雅退出的 worker/agent 进程，`kill -9`(虽然 egg-cluster 已经有处理了)

**arguments ：**
- `baseDir` 为应用的根目录，可选，默认为 `process.cwd()`

**Comment by popomore** [comment]
+1

List 感觉有点鸡肋

**Comment by fengmk2** [comment]
> 会读取 EGG_SERVER_ENV，优先级高于该 options

这个应该是 cli options 优先

**Comment by fengmk2** [comment]
`--customEgg=<EGG_PATH>` 不要了

**Comment by jtyjty99999** [comment]
list我觉得还是需要的，在服务器上ps -ef | grep node是我经常打的几个命令之一。。

另外加一个  SINGALS的支持

**Comment by atian25** [comment]
@fengmk2 ok, 我改过来, 之前考虑到的是这种场景:

npm scripts:  `"start": "egg-scripts start --prod=env"` 但临时用 `EGG_SERVER_ENV=test npm start`

**Comment by atian25** [comment]
`进程的 process title 是否需要包含特殊关键词，用于 stop 脚本判断？` 这个也讨论下, 记得以前是有设置 title 的, 后面干掉了, 主要考虑点是啥? @popomore 

目前判断 master 的方式是: `ps -eo "pid,command" ` 包含 `--customEgg` 和 `--baseDir`

判断 worker/agent 的方式是 : `ps -eo "pid,command" ` 包含 `"customEgg":` 和 `"baseDir":""`

感觉有点怪怪的

**Comment by jtyjty99999** [comment]
chair以前支持的那个进程信号我觉得就挺好的

**Comment by fengmk2** [comment]
> npm scripts: "start": "egg-scripts start --prod=env" 但临时用 EGG_SERVER_ENV=test npm start

加一个 `start-test: "egg-scripts start --env=test"`

**Comment by atian25** [comment]
@jtyjty99999 信号量那个我加上了，不过有个问题，取值用 node 那套还是 kill 那套？

前者是 SIGTERM 后者是 TERM

**Comment by popomore** [comment]
不要太多命令吧，这是用于部署的不是用于管理进程的，我不太喜欢给人这是“全局安装”的感觉。

@jtyjty99999 如果自己有这个习惯，可以自己提供这样的工具。

**Comment by atian25** [comment]
如果 https://github.com/eggjs/egg/issues/465#issuecomment-282613814 这个有特殊的关键词来标示 master, 那 list 就没啥必要了, 自己 ps

**Comment by popomore** [comment]
egg-scripts fork 的时候可以自己加参数的，这样 master 就会带了

**Comment by atian25** [comment]
@popomore 这个知道, 只是印象中早期 egg 似乎是有的, 后面干掉了, 就问问.

那我们统一加一个 `--egg` 来做关键词?

**Comment by atian25** [comment]
> --customEgg=<EGG_PATH> 不要了

@fengmk2 只是不支持这个命令行参数，但内部寻址规则不变吧？

**Comment by popomore** [comment]
按道理应用应该配置了 egg.framework 或默认为 egg，不然其他工具也不匹配了？

**Comment by atian25** [comment]
现在也没强制要求配置这个, 需要强制么?

**Comment by popomore** [comment]
egg-bin, egg-script, egg-mock 的配置要保持一致，最近好像 egg-bin 要支持 framework？

**Comment by atian25** [comment]
感觉这个写完后, egg-bin dev 都可以直接调用这个了, 只是默认入参不同吧?

**Comment by jtyjty99999** [comment]
我改个说法，没说自己有需要，事实上我这边了解的绝大部分同学都有list这样的需求

**Comment by popomore** [comment]
@jtyjty99999 为了杀进程？

**Comment by jtyjty99999** [comment]
@popomore 它们主要是想了解下node运行的情况 ，类似 
![image](https://cloud.githubusercontent.com/assets/893152/23347848/29f6ea0c-fce0-11e6-9973-5284d3e295fb.png)

**Comment by popomore** [comment]
@jtyjty99999 单独做个工具吧，egg-scripts 是非常轻量的，不想做成 pm2.

**Comment by dead-horse** [comment]
搞这么麻烦，不如推荐他们 pm start

**Comment by atian25** [comment]
@dead-horse 你指 list 这个还是全部?

**Comment by atian25** [comment]
还有一个问题，日志那个，我看到之前都是：
- 启动日志放到 `{home_dir}/logs/stdout.log`
- alinode 放到 `{home_dir}/logs/alinode/`
- egg 本身的日志是在 `{home_dir}/logs/{app_name}/**`

前面 2 个的路径需要改变下么? @popomore

**Comment by jtyjty99999** [comment]
好的，那就简单化吧

**Comment by dead-horse** [comment]
我们还是可以提供一个简单的启动、关闭脚本，同时我们也看看怎么更好的用 pm2 来管理，这样提供两个方案：

1. 如果用户不需要 pm2 的状态监控功能，直接用 egg-scripts 就可以了，甚至可以自己 nohup 运行
2. 如果用户想要 pm2 的功能，就按照 pm2 启动的文档就好了

**Comment by atian25** [comment]
`--customEgg` 按上面讨论会干掉，另外按 https://github.com/eggjs/egg/issues/467 的讨论，框架寻址这个也不在 egg-scripts 做了，直接在 egg-cluster 里面做掉。

@popomore 日志的那个再看看 https://github.com/eggjs/egg/issues/465#issuecomment-282621021

**Comment by fengmk2** [comment]
@atian25 日志问题也不是 scripts 处理的，它是应用配置的。

**Comment by atian25** [comment]
不是 egg 的日志，是 egg-scripts 和 master 的日志，前面列举的第一条，看 chair-script 是放到 home 下

**Comment by fengmk2** [comment]
参数可修改即可

**Comment by fengmk2** [comment]
都stop了，还加signal是否画蛇添足

**Comment by fengmk2** [comment]
--cluster 不加了吧，必然是cluster模式的，不允许非cluster模式

**Comment by fengmk2** [comment]
stop 支持 master pid 来kill

**Comment by atian25** [comment]
`--cluster=2` 之前是这个用法, 配置 workers 的, 这个应该还需要保留, 我之前的 PR 是做了别名, `--cluster` 和 `--workers` 等价

**Comment by atian25** [comment]
stop signal 这个, @jtyjty99999 看看, 除了 TERM 的话, 还有传递其他 signal 的场景

**Comment by atian25** [comment]
> stop 支持 master pid 来kill

都知道 pid 了为何不直接 `kill pid` ?

**Comment by atian25** [comment]
> 参数可修改即可

日志参数可修改这个, 用什么参数名好呢? 因为这个参数只是 egg-scripts 和 master std 的日志, 改变不了 egg 本身的日志,  怕有误解

**Comment by fengmk2** [comment]
TERM 必然是进程退出了，要不然都不加stop了。真的不要做这么复杂，这里只做2件事情。其它都不是它负责的。

cluster兼容没必要做，有workers参数足够了

**Comment by fengmk2** [comment]
这个工具完全没有历史包袱，不要被自己禁锢了

**Comment by popomore** [comment]
默认前端启动，--daemon 后台启动吧。
