### ISSUE TITLE
创建egg ts项目后.无法安装依赖

### ISSUE THREAD

**Issue by tmkmk** [eggjs/egg#4660]
## What happens?
新建一个ts项目 后.使用npm i 失败.

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：node-v15.14.0-x64
- **Egg 版本**：2.29.4

使用 node-v15.14.0-x64版本的node无法安装依赖.退回到 node-v14.16.1-x64后,可成功安装依赖.
个人呢,有点强迫症.啥玩意都想用新的.
另外再提一句,安装完依赖后,会显示几个红色的,提示有的包过期,有漏洞了.麻烦把这些也更新一下啊.

**Comment by atian25** [comment]
安装依赖跟 egg 没啥关系。

可以去了解下 Node 的版本发布规则， 单数版本是不稳定版本，不要用
