### ISSUE TITLE
multipart如何分开单独限制文件上传大小

### ISSUE THREAD

**Issue by nanhupatar** [eggjs/egg#4662]
相同issue[multipart如何分开单独限制文件上传大小](https://github.com/eggjs/egg/issues/4259)

我这边使用的是file模式，我想在一个单独的路由限制上传文件的大小，按照上面issuse提示的写
```js
router.post('/multiple-file', app.middleware.multipart({ fileSize: '10kb' }), controller.home.upload);
```

上传时提示
```json
{
    "error_msg": "the multipart request can't be consumed twice",
    "success": false
}
```

请问这个需要怎么处理呢

**Comment by nanhupatar** [comment]
因为 egg-multipart 只提供一个单独的fileSize配置，而不能进行定制化，比如图片限制5m，视频限制100m,file模式下没有size，

**Comment by nanhupatar** [comment]
@atian25

**Comment by nanhupatar** [comment]
请问这个在框架内可以实现吗，即不引入第三方中间件的情况下

**Comment by atian25** [comment]
> the multipart request can't be consumed twice

因为内置的中间件已经处理过了，你要配置下 `config.multipart.ignore/match` 来跳过它

**Comment by fengmk2** [comment]
我将文件上传的文档完善一下，增加按路由来区分文件大小限制的示例。

**Comment by fengmk2** [comment]
@nanhupatar 目前确实实现起来比较不符合直觉，我先写了一个测试用例，你可以参考 https://github.com/eggjs/egg-multipart/pull/51

后续是否做得更加简单，我还需要想想怎样实现比较符合一般人的直觉。
@dead-horse 也可以看看。
