### ISSUE TITLE
生产环境 已缓存的静态文件如何重新设置缓存时间

### ISSUE THREAD

**Issue by tomDogwow** [eggjs/egg#4665]
生产环境下maxage太大了 一年 第一次部署时没有改  后来发现新更新的html文件一直不生效才发现max-age是整整一年 现在无论是重新设置为0还是重启整个服务都不能生效 一直也都是一年 ....清除浏览器缓存 重下了另一个浏览器 仍然是一年

**Comment by atian25** [comment]
入口文件不应该直接用 static 的，应该用 router 来渲染 HTML。

maxage 是浏览器侧的缓存处理，不经过服务端。

PS：HTTP 协议里面关于缓存这块的知识，可以去复习下。

**Comment by tomDogwow** [comment]
> 
> 
> 入口文件不应该直接用 static 的，应该用 router 来渲染 HTML。
> 
> maxage 是浏览器侧的缓存处理，不经过服务端。
> 
> PS：HTTP 协议里面关于缓存这块的知识，可以去复习下。


感谢大佬的回复；
对于你回复的入口文件不应该直接用 static 的，应该用 router 来渲染 HTML。不太理解是什么意思，可能我没有描述清除 是所有的 静态文件 包括css js这些都在替换了后不生效 即便是重启了服务也仍然是旧的配置 在配置文件里吧maxAge设置为200  可是重启服务后响应头里的仍然是一年  只有在dev模式下才是设置的200，

maxage 是浏览器侧的缓存处理，不经过服务端。  我明白你的意思 我想说的是配置maxAge设置为200貌似以start模式启动并不会生效 响应头里的仍然是一年0.0

**Comment by atian25** [comment]
因为 egg-static 是在 config.prod.js 里面设置的 maxAge，你要覆盖的话也要类似，不能在 config.default.js


> 对于你回复的入口文件不应该直接用 static 的，应该用 router 来渲染 HTML。不太理解是什么意思

意思是，你不应该直接给用户访问 `http://host/public/xx.html` 而应该用 egg-view-xx 插件，写个 router 来渲染一个入口文件。

**Comment by tomDogwow** [comment]
> 
> 
> 因为 egg-static 是在 config.prod.js 里面设置的 maxAge，你要覆盖的话也要类似，不能在 config.default.js
> 
> > 对于你回复的入口文件不应该直接用 static 的，应该用 router 来渲染 HTML。不太理解是什么意思
> 
> 意思是，你不应该直接给用户访问 `http://host/public/xx.html` 而应该用 egg-view-xx 插件，写个 router 来渲染一个入口文件。

感谢大佬
