### ISSUE TITLE
file模式下的文件上传，curl是不是写死了全部转换成multipart/form-data，不能使用binary/octet-stream吗

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4668]
## What happens?
file模式下的上传文件，我对接的对方的接口要求用binary/octet-stream数据类型，但是当我指定了content-type为binary/octet-stream发送请求时，curl还是会把我本次请求的content-type转换为multipart/form-data.这里内部是还有什么注意事项需要处理吗？

**Comment by atian25** [comment]
请提供可复现代码库，或者看下 urllib 这个 npm 包的文档

**Comment by shuidian** [comment]
就随便一个上传文件的接口调用，然后抓包出来发现，请求的content-type就是multipart/form-data。
我不太清楚，是不是curl的contentType能支持类似像‘binary’这样的配置，以达到我预期的效果。目前在能查到的文档中，我都找不到相关的说明。
```javascript
const res = await this.ctx.curl(`/upload`, {
      method: 'PUT',
      files: objFile,
      headers: {
        'content-type': 'binary/octet-stream'
      }
    })
```

**Comment by shuidian** [comment]
我看到java中的实现是这样的，直接通过HttpURLConnection的实例，获取一个输出流，然后往这个输出流里面写读进来的文件流即可。但是我比较好奇，node中有类似的实现吗？作者是否清楚curl是否也提供了这种以输出流的形式发送请求的能力呢？

**Comment by atian25** [comment]
因为你用了 `files`，https://github.com/node-modules/urllib/blob/15c4170beab4404b0576caa01e199f445c476b7d/lib/urllib.js#L393

它用 formstream 里面默认是文件上传的，你这个相当于自定义协议，可以试着自己传 `options.stream`，不要用 files

**Comment by shuidian** [comment]
嗯，是对的，通过stream去传输文件流即可，感谢！
示例代码供后面同学参考：
```javascript
const res = await this.ctx.curl(`/upload`, {
      method: 'PUT',
      stream: fileStream,
      headers: {
        'content-type': 'binary/octet-stream'
      }
    })
```
