### ISSUE TITLE
customEgg > framework

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#467]
https://github.com/eggjs/egg/pull/448#discussion_r102932930

改成 framework 后可能更好理解，逐渐取代 customEgg

### egg-cluster

参数支持 framework，使用 egg-utils

```
// 模块名，从 node_modules 查找
startCluster({
  framework: 'yadan',
});

// 绝对路径
startCluster({
  framework: path.join(baseDir, 'node_modules/yadan'),
});

// 不传
// 1. 默认从 pkg.framework 查找
// 2. 使用 egg
// 3. 否则报错
startCluster();
```

### egg-bin

修改 https://github.com/eggjs/egg-bin/blob/master/lib/start-cluster

- 支持 framework 参数
- deprecate eggPath

### egg-mock

修改 https://github.com/eggjs/egg-mock/blob/master/lib/format_options.js#L37

- 支持 framework 参数
- 去除 getFrameworkOrEggPath 逻辑，使用 egg-cluster 默认逻辑
- deprecate customEgg

### egg-scripts

透传 framework

## 调用链

egg-bin: egg-bin dev -> dev_command.js -> (fork) start-cluster -> egg.startCluster -> egg-cluster

egg-mock: mock.cluster -> (fork) start-cluster -> egg.startCluster -> egg-cluster

## Action

- [x] egg-mock https://github.com/eggjs/egg-mock/pull/31
- [x] egg-bin https://github.com/eggjs/egg-bin/pull/39
- [ ] egg-scripts
- [x] egg-cluster https://github.com/eggjs/egg-cluster/issues/17
- [x] egg-utils https://github.com/eggjs/egg-utils/pull/2

**Comment by popomore** [comment]
修改点已更新

**Comment by atian25** [comment]
egg-utils 里面的逻辑也要看看是否需要简化

**Comment by popomore** [comment]
@fengmk2 看看这个是否需要支持 https://github.com/eggjs/egg-utils/blob/master/index.js#L33

**Comment by popomore** [comment]
看了下，单独实现好了，不用 egg-utils 了

**Comment by atian25** [comment]
那  egg-utils  这个代码在哪些地方会用上?

**Comment by dead-horse** [comment]
寻找 framework 的逻辑已经被 egg-cluster 包掉了，先发 rc2 再改 egg-bin 和 egg-mock 吧

**Comment by popomore** [comment]
看来还是要把 getFramework 的提到 egg-utils https://github.com/eggjs/egg-bin/pull/39#discussion_r103619947

**Comment by popomore** [comment]
我先抽到 egg-utils， @dead-horse 再改吧

**Comment by dead-horse** [comment]
恩，你抽出去我替换一下就好了
