### ISSUE TITLE
[Feature Request] Change the egg-redis connected ip when egg.js running?

### ISSUE THREAD

**Issue by gerryhjs** [eggjs/egg#4674]
## Background
change the egg-redis connected ip when egg.js running

## Proposal
I need to change the redis connect ip when running egg.js.
Something like this:
const redis = app.redis;
redis.ip=xxx；

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-redis/blob/master/lib/redis.js#L23 egg-redis using ioredis, you need to send the feature request on ioredis or impl your own Redis client.
