### ISSUE TITLE
this.ctx.cookies.set

### ISSUE THREAD

**Issue by ranxiaoli** [eggjs/egg#4675]
我在接口A中去设置cookie，在接口B中去取cookie， 取出的却是上一次的cookie值？这个是怎么回事？

**Comment by fengmk2** [comment]
这个不是作为应用请求数据存储的，这是服务端跟客户端的 cookie 数据交换。
如果你想在应用请求过程中在服务端多处逻辑交换数据，建议使用 session 或者缓存来实现，Cookie 不是用来做这个事情的。
