### ISSUE TITLE
[Feature Request] 如何根据 ctx.session._sessCtx.externalKey 手动更新 redis 的过期时间 

### ISSUE THREAD

**Issue by jsbay** [eggjs/egg#4677]
我计划做一个单点登录的尝试，已经部署了一个 redis 服务，并且通过 SSO 服务将加密后的 `ctx.session._sessCtx.externalKey` 传递给客户端，客户端将 加密后的 `externalKey` 传递至 应用 A 时，应用 A 将 `externalKey` 解密后，查看公共 redis 服务中的信息是否有效，若过期时间小于设定的过期时间的一半，重新设置过期时间，实现类似 [session.renew](https://eggjs.org/zh-cn/core/cookie-and-session.html#session-%E5%AE%9E%E8%B7%B5) 的功能。

我查阅了 `egg-session` 、`egg-session-redis`， 并未发现暴露出来根据 `session`，`externalKey` 直接更新 redis 数据及过期时间的方法。

是否有一个内置方法可以根据 `externalKey` 直接更新 redis 数据及过期时间的方法？

**Comment by fengmk2** [comment]
_sessCtx 这个是私有 api，不应该去依赖它。
你要重置 session 过期时间，你可以看看 SessionStore 的实现。
