### ISSUE TITLE
[schedule] How to manually execute a schedule task only once

### ISSUE THREAD

**Issue by wang1212** [eggjs/egg#4679]
# My business needs

I created a schedule task, and `type = worker`, and every day I regularly request some data from other servers to insert into the database.

**Every time I deploy the application, I hope to automatically execute the scheduled task immediately.**

I searched the document and found that I can [manually perform scheduled tasks](https://eggjs.org/zh-cn/basics/schedule.html#%E6%89%8B%E5%8A%A8%E6%89%A7%E8%A1%8C%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1). I created the *app.ts* file and manually executed the scheduled task (`app.runSchedule`) in the **didReady** life cycle of `AppBootHook`.

**But I found that the scheduled task was executed twice（The number of workers is specified as 2）. What I expected is that it should only be executed once, because `type = worker`.**

---

What should I do?

**Comment by atian25** [comment]
> I hope to automatically execute the scheduled task immediately.

```js
exports.schedule = {
  type: 'worker',
  cron: '0 0 3 * * *',
  // interval: '1h',
  // immediate: true,
};
```

**Comment by wang1212** [comment]
Thank you, I didn't read the document carefully!
