### ISSUE TITLE
全局request事件设置的header没有同步到curl的header上

### ISSUE THREAD

**Issue by fayeah** [eggjs/egg#4682]
## What happens?
egg服务需要使用curl调用外部的API，然而在全局request事件设置header之后，没有自动添加到curl的header上。

## Mini Showcase Repository(REQUIRED)
https://github.com/fayeah/egg-use

## How To Reproduce

**Steps to reproduce the behavior:**
1. start the egg server with `npm run dev` based on the Showcase Repository
2. open `http://127.0.0.1:7001/` on browser, and check the log info

**Expected behavior**
1. the header `traceId` is attached to curl request

## Context
- **Node Version**: v14.16.0
- **Egg Version**: 2.15.1
- **Platform**: Mac

另，如果没有自动attach，那如何实现全局的curl header设置？

**Comment by atian25** [comment]
因为你写错地方了，`req.ctx.request` 是 Koa 的 Context Request，不是 curl，它是两条链来着。

改成这样就行了：

```js
  app.httpclient.on('request', reqMeta => {
    reqMeta.args.headers.traceId = 'xxx';
  });
```

相关参考：

- https://github.com/node-modules/urllib/blob/15c4170beab4404b0576caa01e199f445c476b7d/lib/urllib.js#L247

另外，建议直接用 tracer，相关指引：

- https://github.com/eggjs/egg-opentracing
- https://github.com/eggjs/egg/blob/e7fbd68f32054041b74bc860f11aca05c025c0a9/lib/core/httpclient.js#L32

**Comment by fayeah** [comment]
> 因为你写错地方了，`req.ctx.request` 是 Koa 的 Context Request，不是 curl，它是两条链来着。
> 
> 改成这样就行了：
> 
> ```js
>   app.httpclient.on('request', reqMeta => {
>     reqMeta.args.headers.traceId = 'xxx';
>   });
> ```
> 
> 相关源码：https://github.com/node-modules/urllib/blob/master/lib/urllib.js#L247
> 
> 另外，建议直接用 tracer，相关指引：
> 
> * https://github.com/eggjs/egg-opentracing
> * https://github.com/eggjs/egg/blob/e7fbd68f32054041b74bc860f11aca05c025c0a9/lib/core/httpclient.js#L32

非常感谢～解决啦，但是headers可能要这么写：
```
reqMeta.args.headers = {
    traceId: 'xxx'
}
```

**Comment by atian25** [comment]
那样写就覆盖掉了用户传递的 headers 了啊

**Comment by fayeah** [comment]
> 那样写就覆盖掉了用户传递的 headers 了啊

```
reqMeta.args.headers = {
    ...otherHeaders,
    traceId: 'xxx'
}
```
这样？因为我用 `reqMeta.args.headers.traceId = 'xxx';` 会说headers是undefined。
