### ISSUE TITLE
serverDidReady 钩子Timeout超时问题

### ISSUE THREAD

**Issue by fayeah** [eggjs/egg#4684]
## What happens?
`app.js`使用`serverDidReady`hook，但是不论哪一个API，调用之后5000ms会出现Timeout Error.

## Mini Showcase Repository(REQUIRED)
> https://github.com/fayeah/egg-use

## How To Reproduce

**Steps to reproduce the behavior:**
1.start the egg server with npm run dev based on the Showcase Repository
2.open http://127.0.0.1:7001/ on browser, and check the log info

**Expected behavior**
1. 不会出现TimeoutError

## Context
- **Node Version**: v14.16.0
- **Egg Version**: 2.15.1
- **Platform**: Mac

![image](https://user-images.githubusercontent.com/29644978/119955855-0f433700-bfd3-11eb-8327-5b6c8b93c9db.png)

**Comment by atian25** [comment]
无法复现

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/119956613-dbb4dc80-bfd3-11eb-9523-ef89b79ebd75.png)

浏览器访问后的第二个请求导致的，自己处理

**Comment by fayeah** [comment]
我是用postman调用的，是有这个问题的

**Comment by fayeah** [comment]
> ![image](https://user-images.githubusercontent.com/227713/119956613-dbb4dc80-bfd3-11eb-9523-ef89b79ebd75.png)
> 
> 浏览器访问后的第二个请求导致的，自己处理

并且浏览器访问，也能在控制台看到这个error log，为啥你看不到 :(

**Comment by fayeah** [comment]
> 我这边试了下， curl 是没问题的，postman 和浏览器会有，具体原因不知道，可以自己分析下看看。怀疑是他们多请求了什么。

OK

**Comment by hyj1991** [comment]
浏览器的和 https://github.com/eggjs/egg/issues/3046 这个应该是同一个问题
