### ISSUE TITLE
添加middleware，启动服务报错。

### ISSUE THREAD

**Issue by fayeah** [eggjs/egg#4688]
## What happens?
添加middleware，启动服务报错。

## Mini Showcase Repository(REQUIRED)
> https://github.com/fayeah/egg-use

## How To Reproduce

**Steps to reproduce the behavior:**
1.start the egg server with npm run dev based on the Showcase Repository
2. check the server log

**Expected behavior**
1. 不会出现Error

## Context
- **Node Version**: v14.16.0
- **Egg Version**: 2.15.1
- **Platform**: Mac

![image](https://user-images.githubusercontent.com/29644978/120324951-c6b0b400-c319-11eb-87f2-c3bda5592a11.png)

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/120326463-53a83d00-c31b-11eb-8258-5da5472358ac.png)

注意看文档。

**Comment by fayeah** [comment]
马虎了..
