### ISSUE TITLE
ctx.request.body

### ISSUE THREAD

**Issue by aluckyqingchun1** [eggjs/egg#4689]
post请求之后 会返回这样的错误信息 request aborted, check bodyParser config
如果把bodyParser配置成false的话  ctx.request.body 拿到的值undefined

**Comment by atian25** [comment]
它叫你检测配置，不是叫你关闭配置。。。

**Comment by aluckyqingchun1** [comment]
找到问题啦 是前端哪里webpack配置 admin有一个mock数据 devserver 的一个before参数应该给转发掉了一些参数信息
