### ISSUE TITLE
如何进行host绑定

### ISSUE THREAD

**Issue by hackboy** [eggjs/egg#469]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

在nodejs的http模块，可以通过httpServer.listen([port][, hostname][, backlog][, callback])进行hostname的绑定，但是在egg中好像不能进行绑定，请问是否可以绑定，若能，怎么样进行绑定，谢谢

**Comment by popomore** [comment]
目的是什么呢？

**Comment by hackboy** [comment]
@popomore 现在我使用egg开发了一个日志管理系统，其中的服务端在启动时运维人员需要进行host绑定，考虑过进行通过ng进行反向代理，但是因为一些原因此方法有些不适合的地方，所以需要直接进行host绑定，但是未找到绑定方法，在koa源码里是可以进行的

**Comment by dead-horse** [comment]
egg-cluster 加参数支持吧

**Comment by hackboy** [comment]
@dead-horse 
  if (options.sticky) {
    server.listen(0, '127.0.0.1');
    // Listen to messages sent from the master. Ignore everything else.
    process.on('message', (message, connection) => {
      if (message !== 'sticky-session:connection') {
        return;
      }

      // Emulate a connection event on the server by emitting the
      // event with the connection the master sent us.
      server.emit('connection', connection);
      connection.resume();
    });
  } else {
    server.listen(options.port);
  }

这是他们的启动代码，里面好像直接把host等参数给忽略了，只能进行端口的指定

**Comment by popomore** [comment]
和这个是一个需求 https://github.com/eggjs/egg/issues/435

**Comment by rorivers** [comment]
刚好调查过这个问题。
我的解决方式如下：
node_modules/egg-cluster/lib/app_worker.js里
 if (options.sticky) {
    server.listen(0, '127.0.0.1');
    // Listen to messages sent from the master. Ignore everything else.
    process.on('message', (message, connection) => {
      if (message !== 'sticky-session:connection') {
        return;
      }

      // Emulate a connection event on the server by emitting the
      // event with the connection the master sent us.
      server.emit('connection', connection);
      connection.resume();
    });
  } else {
    server.listen(options.port, options.address);
  }
在server.listen()里传入address参数。
主目录下package.json里
"scripts": {
    "test": "egg-bin test",
    "dev": "egg-bin dev --port 80 --address 10.18.10.134 --cluster 2",
    "debug": "egg-bin debug"
  }
dev命令上，添加--address参数。

**Comment by atian25** [comment]
然而修改 node_modules 里面的代码是非常不推荐的行为，我们刚发了 1.0，等 @popomore 在 https://github.com/eggjs/egg/issues/484 解决吧

**Comment by rorivers** [comment]
了解了，期待你们的解决方案。

**Comment by 285858315** [comment]
这个问题解决了么？怎么配置的呢？我怎么没找到？

**Comment by 285858315** [comment]
@dead-horse 大神，请教下这个 host 怎么配置呢，官方文档找了半天没找到。
