### ISSUE TITLE
确定 Release 规则

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#47]
## 背景

Egg 参与人员过多，仓库过多，经常会遇到某个人没有某仓库的发布权限。

Release 时会修改版本和更新 changelog，这个也需要 review。

## 目标

1. Changelog 可 review
2. npm 自动发布
3. 锁定 master 目录不允许提交

## 方案

锁定 master 目录不允许任何人提交，并添加合并检测（review+2，travis 和 codecov 通过）。

Release 时本地修改版本和 changelog 后提交 PR，review 后合并。

Travis 根据 commit 信息判断是否 release（非 PR，master 分支，切 commit 匹配），通过 eggjs 账号 发布到 npm。

## Action

- [ ] 支持 travis 发布 npm 包，还需要自动 push tag
- [ ] “本地生成 changelog 和版本”有工具支持，保证生成格式一致
- [ ] 文档更新
- [ ] 确定 commit 信息 `chore(release): release 1.0.0`
- [ ] 自动更新 github release

_Updated at 2017-02-09_

---

<img width="769" alt="screenshot 2016-08-16 8 25 51" src="https://cloud.githubusercontent.com/assets/360661/17698804/b078fc08-63ef-11e6-86d3-fbbf83cf2e73.png">

以后所有的仓库都需要这样配置，不允许直接 push 到 master。但是 release 的时候还有一步需要 push，这个规则需要明确下。

**Comment by fengmk2** [comment]
就继续按之前的做法，手动写 release histroy 和版本号，然后提交 pr ，确认没问题后合并到 master，然后打 tag，执行 npm publish。

**Comment by popomore** [comment]
1.0  后的 release 规则要不要按原先的来？

**Comment by fengmk2** [comment]
@popomore 写一个 release 流程说明

**Comment by popomore** [comment]
那我写个 RFC 吧，然后再讨论

**Comment by atian25** [comment]
新仓库的配置也写一个说明? 包括 branch, service 之类的

**Comment by atian25** [comment]
vue 的 release note 会在 github release 那里:  https://github.com/vuejs/vue/releases

这个我们也可以搞搞, 不知道是不是读取 commit message body

**Comment by popomore** [comment]
嗯，可以搞搞
TZ | 天猪 <notifications@github.com>于2017年2月8日 周三09:13写道：

**Comment by popomore** [comment]
更新了

**Comment by atian25** [comment]
+1

这几点要不要补充?
- [ ] 自动跑 benchmark

正文中那些点:
- 如何可以让每个仓库都配置一样? 避免新库的时候配置遗漏
- release 的 pr, 只能 core 成员才能点击 merge, 避免误操作导致的版本发布.

**Comment by dead-horse** [comment]
其他的模块是否不做这个强约定了？保证 egg 就好，因为 egg 要做的工作可能多一点。

**Comment by popomore** [comment]
先做 egg 吧，如果工具都有了足够简单的话再看其他库吧。

**Comment by fengmk2** [comment]
@dead-horse 只需要 egg 吧，其他模块使用最简单的 release 模式

**Comment by fengmk2** [comment]
+1

**Comment by popomore** [comment]
这个还没做完

**Comment by dead-horse** [comment]
感觉现在的发布模式也够用了，这个 issue 关掉吧？

**Comment by atian25** [comment]
加到 Project: maybe 里面待跟踪吧。可以先关掉。
