### ISSUE TITLE
egg-init 初始化的plugin项目WARN

### ISSUE THREAD

**Issue by askie** [eggjs/egg#470]
使用egg-init 初始化创建的plugin项目：
`2017-02-27 17:11:23,780 WARN 31367 [egg:loader] pkg.eggPlugin is missing in /egg/app/plugins/egg-camo/package.json`

**Comment by atian25** [comment]
egg-camo 这个插件哪来的? 提示写的很清楚了, 缺少 eggPlugin 的配置

**Comment by askie** [comment]
这个是我们自己写的插件，正在开发。
eggPlugin  这个参数没有说明如何配置？求文档！

**Comment by askie** [comment]
找到了，不用回了

**Comment by askie** [comment]
还是有问题，egg-init 时，package.json文件中包含了：
`"eggPlugin": {
    "name": "camo"
  },`
但是，依然报错：
`[egg:loader] pkg.eggPlugin is missing in /egg/app/plugins/egg-camo/package.json`

**Comment by askie** [comment]
找到问题了，项目启用时指定的目录不是局对目录，所以找不到/egg/app/plugins/egg-camo/package.json这个文件。

这个错误表达的不正确，应该是文件不存在才对，并不是找不到pkg.eggPlugin

**Comment by atian25** [comment]
@popomore 看看有没有必要加一个报错 https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/plugin.js#L220

**Comment by shaoman1126** [comment]
那怎么办呢，我也遇到这个问题，
