### ISSUE TITLE
生产环境node进程crash

### ISSUE THREAD

**Issue by superdangdang** [eggjs/egg#4702]
## What happens?

生产环境eggjs进程无预兆crash，此前已经稳定运行半个月

## 最小可复现仓库

无

## 复现步骤，错误日志以及相关配置

crash时刻server-web.log和schedule.log日志出现乱码,长这样

schedule.log
![](https://i.imgur.com/sYIftIZ.png)

server-web.log
![](https://i.imgur.com/7hY73vS.png)

没有发现其他异常的日志

## 相关环境信息
- **操作系统**：Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux
- **Node 版本**：14.17.1
- **Egg 版本**：2.29.4

**Comment by atian25** [comment]
用 alinode 监控和分析吧，看看是不是 OOM 了。

**Comment by DragonCat1** [comment]
> 用 alinode 监控和分析吧，看看是不是 OOM 了。

![](https://i.imgur.com/uxuQbEa.png)



我发现aws的ec2有10分钟的异常，正常好13点的时间，可能与此有关。（不过亚马逊并没有给我任何故障通知..）
而其他服务nginx、redis没有崩

**Comment by superdangdang** [comment]
> 用 alinode 监控和分析吧，看看是不是 OOM 了。


![](https://i.imgur.com/uxuQbEa.png)
我发现aws的ec2有10分钟的异常，正常好13点的时间，可能与此有关。（不过亚马逊并没有给我任何故障通知..）
而其他服务nginx、redis没有崩

**Comment by atian25** [comment]
ec2 这个是主机监控，太粗了。 Node 的话要不用 Alinode，要不自己部署 EasyMonitor，一直挂着监控
