### ISSUE TITLE
请问egg的单进程模式部署内部验证得怎么样了，建议生产环境使用了吗

### ISSUE THREAD

**Issue by bolin-L** [eggjs/egg#4704]
```
 if (!options.ignoreWarning) {
    console.warn('single process mode is still in experiment, please don\'t use it in production environment');
  }
```

**Comment by atian25** [comment]
一般用户可以直接用，不会有啥问题，主要是要看你用的那些插件，如果用到 Agent 和 Worker 通讯的，他们需要看下是否有优化空间，因为单进程后，为了兼容性，还是会初始化这 2 个对象，但他们是在同个进程里面初始化的。

**Comment by bolin-L** [comment]
感谢解答  的确   我们部署的是内部应用，多进程模式下多了Master跟Agent进程所占的资源也没多大影响，就是理论上觉得k8s的负载均衡跟守护跟egg多进程启动模式有点冗余，还有就是健康检查也可能不太准确

我先实践看看，有问题再来反馈
