### ISSUE TITLE
[RFC] common-bin refactor

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#471]
## 背景

目前的 [common-bin](https://github.com/node-modules/common-bin) 有点简陋，缺少：
- 参数的处理和校验
- help 的自动输出

## 方案

基于 [yargs](https://github.com/yargs/yargs) 进行改造，干掉 commander.js

### Program

- `Program` 这概念没了，就是一个 `Command` 的子类而已，可以叫它 `Main Command`。
- `start()` 为 bin 的启动入口
- `loadCommand(...args)` 用于加载子命令，其中会被 `path.join` 拼起来
- `addCommand(...args)` 用于加载子命令

```js
// index.js
const BaseCommand = require('common-bin');
const pkg = require('../package.json';

class Command extends BaseCommand {
  constructor() {
    super();
    this.name = pkg.name;
    this.usage = `Usage: ${this.name} <command> [options]`;

    // load entire command directory
    this.loadCommand(__dirname, 'command');

    // or load special command file
    // this.addCommand(__dirname, 'test_command.js');

    // more custom with `yargs` api, such as you can use `my-git -V`
    this.yargs.alias('V', 'version');
  }
}
```

在 bin 里面调用方式修改为：

```js
// bin/my-bin.js
const Command = require('..');
new Command().start();
```

### Command

- `run`
 - 入参变为 object 形式，**要注意是 argv 而不是原来的 args**
 - 支持 generator / async function / normal function which return promise
- `name` 为命令名称
  - 支持 `clone <repository> [directory]` 的形式
- `description` 是命令描述，**不提供的话则为隐藏命令**
-  `options` 属性来配置命令行的约束，参见[yargs#options](http://yargs.js.org/docs/#methods-optionskey-opt)
- `aliases` 为命令别名，支持字符串或数组
- `help()` 方法不再需要
- `loadCommand(...args)` 用于加载子命令目录，其中会被 `path.join` 拼起来
- `addCommand(filePath)` 用于加载子命令

```js
const Command = require('common-bin');

class CloneCommand extends Command {
  constructor() {
    super();
    this.name = 'clone <repository> [directory]';
    this.description = 'Clone a repository into a new directory';

    this.options = {
      depth: {
        type: 'number',
        description: 'Create a shallow clone with a history truncated to the specified number of commits',
      },
    };
  }

  * run({ argv }) {
    console.log('git clone %s to %s with depth %d', argv.repository, argv.directory, argv.depth);
  }
}

module.exports = CloneCommand;
```

## Sub Command

- 如 `my-git remote add <name> <url> --tags`

```js
// test/fixtures/my-git/command/remote.js
class RemoteCommand extends Command {
  constructor() {
    super();
    this.name = 'remote';
    this.description = 'Manage set of tracked repositories';
    // load sub command for directory
    this.loadCommand(path.join(__dirname, 'remote'));
  }

  * run({ argv }) {
    // will exec when not sub command match first argument
    console.log('run remote command with %j', argv._);
  }
}

// test/fixtures/my-git/command/remote/add.js
class AddCommand extends Command {
  constructor() {
    super();
    this.name = 'add <name> <url>';
    this.description = 'Adds a remote named <name> for the repository at <url>';

    this.options = {
      tags: {
        type: 'boolean',
        default: false,
        description: 'imports every tag from the remote repository',
      },
    };
  }

  * run({ argv }) {
    console.log('git remote add %s to %s with tags=%s', argv.name, argv.url, argv.tags);
  }
}
```

## Single Command

直接实现 `options` 和 `run()` 即可

```js
class Command extends BaseCommand {
  constructor() {
    super();
    this.name = pkg.name;
    this.version = pkg.version;

    this.options = {
      baseDir: {
        description: 'target directory',
      },
    };
  }

  * run(context) {
    console.log('run default command at %s', context.argv.baseDir);
    yield super.run(context);
  }
}
```

### helper

- `getIronNodeBin` 不再需要，干掉
-  `kill child` 支持信号量

## 兼容性

- 发布 2.0 版本，不考虑兼容性问题
- 提供升级指南。

## 进度
- [ ] common-bin https://github.com/node-modules/common-bin/pull/4
- [ ] egg-bin https://github.com/eggjs/egg-bin/pull/40
- [ ] egg-init
- [ ] egg-scripts

**Comment by fengmk2** [comment]
比原来的最大亮点是什么呢？举个例子使用新版来写的代码跟老版写的代码有什么差异呢？

**Comment by popomore** [comment]
感觉要改就不要考虑兼容性问题了，最大的好处就是参数已经处理好了

**Comment by popomore** [comment]
1. Run 的参数可以改成 obj，传 cwd，解析好的 args，yargs 应该会保留原来参
1. Program 改动较大，主要考虑 program 的参数是否还要给 commnd，比如 egg-bin --inspect test。

**Comment by fengmk2** [comment]
`* run(data)` 参数改成 obj 好了，这样解析好的 args 和原始的 rawArgs 都在里面

- data.args
- data.cwd
- data.rawArgs

**Comment by fengmk2** [comment]
@popomore command 的参数合并 program 的全局参数，这个应该可以实现

**Comment by atian25** [comment]
```js
const helper = require('./helper');
const co = require('co');

class StartCommand extends Command {
  constructor(name) {
    super(name);
    this.name = name || 'start';
    this.description = 'start egg project at production mode';
    this.options = this.getOptions();
    this.helper = helper;
  }

  * run({ cwd, argv, rawArgv}) {
    console.log(argv);
  }

  getOptions() {
    return {
      baseDir: {
        alias: 'b',
        describe: 'directory of application',
        demandOption: true,
      },
      port: {
        type: 'number',
        desc: 'listening port, default to 7001(http) or 8443(https)',
      },
      daemon: {
        type: 'boolean',
        default: true,
        desc: 'whether run as daemon mode, default to true',
      },
    };
  }
}

module.exports = StartCommand;


class EggScriptsProgram extends Program {
  constructor() {
    super();
    this.version = require('../package.json').version;
    this.addCommand('start', path.join(__dirname, 'start_command.js'));
  }
}
```

```bash
$ egg-scripts start --baseDir=simple
{ _: [ 'start' ], '$0': '/usr/local/bin/egg-scripts', baseDir: 'simple', port: undefined, daemon: true }
```

**Comment by atian25** [comment]
> Program 改动较大，主要考虑 program 的参数是否还要给 commnd，比如 egg-bin --inspect test。

@popomore Program 和 Command 是一个 process 的, 之前的做法也只是简单的传递 `process.argv.slice(3)` ，这里应该没啥区别吧

**Comment by atian25** [comment]
顶楼更新了，再看看

**Comment by fengmk2** [comment]
@atian25 👍

**Comment by popomore** [comment]
应该给每个 Command 一个 yargs，比如 egg-bin test -h

**Comment by atian25** [comment]
@popomore 没看懂

**Comment by popomore** [comment]
Command 也需要定义自己的参数

**Comment by atian25** [comment]
@fengmk2 研究了下 commandDir, 可以支持的， Program 增加一个 commandDir 方法即可。

`this.commandDir(path.join(__dirname, 'command'));`

**Comment by fengmk2** [comment]
约定一个目录就好了，不需要上层 bin 去开发，跟 egg controller 目录约定一个思路。

**Comment by popomore** [comment]
addCommand 还是要支持的，只是支持默认目录，还是可以使用这个 api 添加的。

**Comment by atian25** [comment]
我看看，egg-bin 那个把 cov 替换为 test 要怎么处理，这个比较特殊。

话说，自动加载目录，这个是在基类自动做的，但它怎么知道上层子类的目录绝对路径？

**Comment by fengmk2** [comment]
@atian25  program 有 __file 啊

**Comment by atian25** [comment]
__filename 是基类自己的路径，需要获取的是上层子类的路径，用 yargs 提供的 $0 不知道行不行，等会再试试。

**Comment by popomore** [comment]
仔细想了下 Command 和 Program 应该是一个东西，只是需要一个引导器，但 Program 本身就是一个 Command，command 是 sub command。

```js
class Program extends Command {}
```

参数应该是要抢占，比如 `egg-bin dev --inspect` 如果在 program 定义了，那么 command 应该不接收这个参数。

```js
class Program {
  constructor() {
    this.yargs
      .option('inspect')
  }
}

```

Program 覆盖 Command 的 run，主要做自己参数处理和调用子命令。_现在还想的不是很清楚，Program 是自己处理 yargs.argv 还是使用 yargs.command_。

Program 增加 start 方法作为引导器，因为 Command 的 run 是 generator function，所以需要提供一个 promise 方法。**主要 run 方法不要直接 exit，要在 start 里面 exit**。

**Comment by atian25** [comment]
我认为 Program 只是很薄的一层，只做几件事：

- 配置 yargs 的全局属性，如 `.help()`, `.version()`
- 加载 Commands，注册到 yargs
- 提供启动入口，代理给 yargs 启动

本身 Program 在上层应该没有太多需要自定义的逻辑， 就是给几个配置即可，所以不应该继承 Command。

你的场景是多级子命令么？ yargs 是通过 commandDir 来支持的，`myapp remote add base http://yargs.js.org`

`egg-bin dev --inspect` 是想调试 egg-bin 自己？

**Comment by popomore** [comment]
不一定吧，我可能没有子命令，那直接用 program 的 run 就可以了。

**Comment by popomore** [comment]
最早的命令行工具都是安装 TJ 这样写的 https://github.com/componentjs/component/blob/master/bin/component

子命令就是 component-xx 但和主命令写法是一样的，功能也是一致的。

**Comment by atian25** [comment]
明白你的意思了，类似 `egg-init --type=simple` 这样的，没有子命令了。 

看了下 yargs 有支持 https://github.com/yargs/yargs#default-commands

不过貌似还没发布，三天前进主干了

**Comment by popomore** [comment]
所以我说 program 和 command 很像，差异就是 sub command 拿到的原始 argv 是进过处理的。如果  yargs 支持，其实就是扔一个 sub yargs 给 command

**Comment by atian25** [comment]
按 yargs 的支持方式，Program 这边都不需要处理 sub yargs。
还是之前的方式，只是在某个 Command 上声明下它是默认命令即可，Program 这边还是上面我列的职责，不用继承 Command

**Comment by popomore** [comment]
谢谢看，再 review

**Comment by atian25** [comment]
@popomore 

昨晚在考虑 `egg-init add controller` 这类指令时，又看了一次讨论，确实可以统一 `Program` 和 `Command`，具体做法：

- `common-bin` 简化了，只 exports 了 `Common`
- `Program` 其实是 `egg-init` 里面定义的，它继承于 `Common`，并作为其他命令的基类
- 对应的 RFC 已经更新到顶楼
- 对应的 PR 也已经提交：https://github.com/node-modules/common-bin/pull/3

@fengmk2  不好意思要再重新 review 下了。

**Comment by fengmk2** [comment]
`* run({ cwd, argv, rawArgv }) {` 应该是 exec 了

**Comment by fengmk2** [comment]
`egg-init add controller` 和 `egg-init --type simple` 这2种你是如何实现？只需要给 Program 加上 run 即可？

**Comment by fengmk2** [comment]
```bash
egg-init add controller
egg-init add service
egg-init add xxx
```

还真是很常见的脚手架功能

**Comment by atian25** [comment]
上面 Sub Command 那里有示例代码。

晚上有跟 @popomore 交流了下，上面的接口定义都差不多，但内部实现应该还可以简化下，明天找时间再优化下看看。

**Comment by atian25** [comment]
@fengmk2 @popomore 

`egg-init add controller` 这个，目录结构有什么建议不？

- 二级命令的目录应该是怎么样的？
- 二级命令是在对应的一级命令里面自动加载， 开发者自己在构造函数里面 load ？

```bash
lib
|- command
    |- add.js
    |- add
        |- controller.js
        |- service.js
    |- update.js
    |- update
        |- controller.js
        |- service.js
```

**Comment by popomore** [comment]
load 一层就够了吧，controller 是参数

**Comment by fengmk2** [comment]
我说看着别扭，原来是多层了，cli 最多就2层，root and sub 就好了，sub sub 没有的吧。。。

**Comment by atian25** [comment]
嗯，已经理清思路了，测试还没改完，明天提交

**Comment by popomore** [comment]
有是有的，比如 git ，这里 load 没必要支持，可以自己加 addCommand
TZ | 天猪 <notifications@github.com>于2017年3月6日 周一00:35写道：

**Comment by atian25** [comment]
顶楼 RFC 已经更新，对应的新 PR 在 https://github.com/node-modules/common-bin/pull/5

遗留问题：
- [ ] 更新检测
- [ ] @ali/egg-bin 命令覆盖的示例

**Comment by atian25** [comment]
要考虑 async 的支持么

**Comment by fengmk2** [comment]
支持吧

**Comment by atian25** [comment]
@fengmk2 已经支持完了，在那个 PR 里面有了。

**Comment by atian25** [comment]
最终的 API 跟 RFC 稍有不同，以 `common-bin` README 为准。
