### ISSUE TITLE
为何agent里收到的消息次数与app里发送的次数不一致？

### ISSUE THREAD

**Issue by nononoyeah** [eggjs/egg#4711]
![image](https://user-images.githubusercontent.com/26819107/125045695-d9b06400-e0cf-11eb-859d-f6ec174d3fd4.png)

请教一下，app向agent 发送了3次消息，实际agent收到了9次消息，这是为何？

**Comment by atian25** [comment]
启动了几个 worker ？

**Comment by nononoyeah** [comment]
1个worker 打印agent.options.workers是1

> 启动了几个 worker ？

**Comment by atian25** [comment]
你可以打印 PID 看看。

消息发送的，有个环境变量，可以打印日志来排查，你可以看下 egg-cluster 对应的 DEBUG 环境变量

**Comment by nononoyeah** [comment]
好的，我试试。谢谢

**Comment by atian25** [comment]
肯定不会被覆盖啦，不仅仅是 Node，大部分语言的 event emitter 就是这么设计的。
