### ISSUE TITLE
[RFC] egg能否在龙芯系统（mips）中生产部署

### ISSUE THREAD

**Issue by NicolaCage** [eggjs/egg#4714]
**我们用源码编译完node 14.17.3之后，发现我们的egg项目无法执行npm run build,npm run start等命令**
报错截图：
![image](https://user-images.githubusercontent.com/37568394/125759810-cdf3dea3-04e6-4168-931a-875e1f6adad5.png)
**请问下，egg有想过当前系统的生产部署记录嘛？可以借鉴下吗？**
目前考虑mips的node环境可能和其他系统的不一样影响到egg的一些指令调用，但不肯定

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/125888608-fa509685-c909-4e56-a1b4-99983164f2a1.png)

**Comment by atian25** [comment]
检查下你是否真的有这个文件 `app/middleware/proxy.js`

**Comment by NicolaCage** [comment]
![image](https://user-images.githubusercontent.com/37568394/125888863-dd8ba92d-a32b-4146-a96d-29e5eadd2e6c.png)
没有jswe文件，有ts文件

**Comment by NicolaCage** [comment]
如果直接用开发模式启动，npm run de 也还是会报错
信息如图
![image](https://user-images.githubusercontent.com/37568394/125889151-b3cee694-ffdf-409b-8542-bb89e7289c75.png)

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/125892957-4e61524b-6f46-4de7-bf69-fee80fa20570.png)

这是 webpack 的报错

**Comment by atian25** [comment]
> ![image](https://user-images.githubusercontent.com/37568394/125888863-dd8ba92d-a32b-4146-a96d-29e5eadd2e6c.png)
> 没有js文件，有ts文件

再看下 egg ts 文档？线上是要编译后才能执行的，只有开发期才是 ts-node。

**Comment by NicolaCage** [comment]
> ![image](https://user-images.githubusercontent.com/227713/125892957-4e61524b-6f46-4de7-bf69-fee80fa20570.png)
> 
> 这是 webpack 的报错

是的，npm run builld，dev 都会报这种错误，我理解应该是当前龙芯系统上的node环境有异常不支持webpack调用这个api，我是想确认下，egg框架有过此类系统的部署先例吗？当时的node版本是多少？

**Comment by atian25** [comment]
没遇到过，报错路径都在那了，你就看下源码，看下对应的 API 提炼出来最小案例看看咯，估计是 Node 本身的 bug

**Comment by NicolaCage** [comment]
好的，谢谢回答
