### ISSUE TITLE
npm scripts dev脚本添加cross_env  EGG_SERVER_ENV=dev后热更新失效

### ISSUE THREAD

**Issue by JoeyYoung1997** [eggjs/egg#4719]
## What happens?
egg初始化后的npm scripts dev脚本为dev: egg-bin dev，由于分环境配置需要且兼容windows，改成dev: cross-env EGG_SERVER_ENV=dev egg-bin dev，启动后热更新失效了

**Comment by tumobi** [comment]
改成 EGG_SERVER_ENV=local 看看

**Comment by JoeyYoung1997** [comment]
> 改成 EGG_SERVER_ENV=local 看看
有效了，非常感谢
