### ISSUE TITLE
[Feature Request] 插件支持router定义和声明controller

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4731]
## Background
看了下egg的插件开发文档，不支持路由和controller的理由是怕路由冲突。
那么如果通过约定等其他方案，可以确保路由不冲突的话，是否可以让插件支持路由和controller声明呢？
这样，在开发一个插件的时候，基本上就跟开发应用是一致的体验了（此时的插件基本上就是一个可以灵活挂载的应用）。
而且，这样的话，配合插件的path绝对路径声明，就可以实现不动主框架代码前提下，进行功能扩展了，这样可以让服务的可扩展性进一步提升。

文档中建议的中间件来处理路由确实可行，但是这种方式破坏了正常的应用的开发体验，controller这一层就是没有了，那么本来应该在controller中处理的逻辑又要跟service写在一起了。此外，一些基于controller扩展的其他插件功能也无法生效，比如egg-egg-swagger-doc、egg-validate-plus、egg-shell-decorators等插件。

## Proposal
希望插件能够支持router和controller。或者有什么好的实现方式也可以指导一下。

## Additional context
可能想法不够成熟，个人在想，是否可以优化一下loadController方法，让其可以遍历每个插件的controller目录呢？这样应该是成本比较低的改动。

**Comment by hyj1991** [comment]
如果确实有需要的话，你可以绕过这个限制，app.js 里可以获取到 app，继续调用 app.router 即可

**Comment by shuidian** [comment]
> 如果确实有需要的话，你可以绕过这个限制，app.js 里可以获取到 app，继续调用 app.router 即可

这个方案的话，有个疑问，就是插件里的controller怎么挂载到app上呢？

**Comment by hyj1991** [comment]
> 这个方案的话，有个疑问，就是插件里的controller怎么挂载到app上呢？

`app.router.get('/', async ()=>{})`
