### ISSUE TITLE
router断点无法断住

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#4735]
## 相关环境信息
- **操作系统**：wwin10
- **Node 版本**：14.17.4
- **Egg 版本**：2.15.1

debug命令配置成了：
`"debug": "egg-bin debug --break",`

无法断住router的代码：
![image](https://user-images.githubusercontent.com/15070379/129282877-4751bc18-4d2a-4a89-b169-9685edb83729.png)

用express ，koa都正常。

**Comment by atian25** [comment]
--inspect-brk

**Comment by bi-kai** [comment]
@atian25 最开始用--inspect-bark发现卡住不动，看控制台需要监听5800：
![image](https://user-images.githubusercontent.com/15070379/129383083-ac4aea45-5b4d-4dcf-8cb3-d067d49cd01e.png)
这样是可以断住了：
![image](https://user-images.githubusercontent.com/15070379/129382595-4b207dbf-763b-491c-ab5d-a4f599589541.png)

不过跳转好几次，左侧树上加载了三次：
![image](https://user-images.githubusercontent.com/15070379/129383279-c765c9f4-ae69-4ee8-bbe2-eaf272f34f1b.png)

我的问题是一个应用，为什么需要在chrome inspect中配置多个端口呢：
![image](https://user-images.githubusercontent.com/15070379/129383370-a8f96a09-75c5-46c6-803d-a2cab418ab8c.png)
bu'n不能够复用么？

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/development.html#%E4%BD%BF%E7%94%A8-egg-bin-%E8%B0%83%E8%AF%95

https://github.com/atian25/blog/issues/25

其实文档里面写的很清楚了，可以看下。
