### ISSUE TITLE
官网缺少model开发说明

### ISSUE THREAD

**Issue by askie** [eggjs/egg#474]
求model开发的说明文档！

**Comment by atian25** [comment]
哪一个 model ? 用哪一个插件的?

cc @jtyjty99999

**Comment by jtyjty99999** [comment]
@atian25 我们现在确实没有类 Active-record-pattern 开发方式的指导，不知道是不是说的这个意思， @askie 你可以使用 https://github.com/eggjs/egg-mongoose  https://github.com/eggjs/egg-sequelize 之类都可以

**Comment by askie** [comment]
@jtyjty99999  已参考egg-mongoose开发，多谢！

**Comment by atian25** [comment]
@jtyjty99999  回头可以在 tutorial 里面写写这些的用法
