### ISSUE TITLE
Protect source code

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#4746]
How can I protect source code of my egg application?
I want to minify and obfuscate my app, but I don't know how it's possible with egg loader?

**Comment by atian25** [comment]
egg loader is just using `require` and `fs.readFile`, so just do what it does like other Node.js applications, nothing special.

**Comment by sm2017** [comment]
@atian25 but is scan directories, like `controller` directory
Can you please tell me how can I minify my app?

**Comment by atian25** [comment]
maybe you could use something like pkg which will hack fs, I'm not familiar with this.

**Comment by sm2017** [comment]
Ok, thank you
