### ISSUE TITLE
docker-compose运行egg.js和MySQL5.7报错, 无法正常链接

### ISSUE THREAD

**Issue by liaohui5** [eggjs/egg#4753]
## 当我用docker-compose打包镜像然后up的时候无法真确链接MySQL数据库
1. 我用的是 egg-sequelize 这个插件, 不知道是否是插件的问题
2. 我不打包, 本地直接运行, 可以正常链接数据库
3. 我的配置是这样的
```js
"use strict";
module.exports = {
  sequelize: {
    dialect: "mysql",
    host: "det_mysql", // docker container name
    port: 3306,
    database: "docker_egg_test",
    username: "root",
    password: "root",
  },
};
```
4. 这是报错信息截图
![image](https://user-images.githubusercontent.com/29266093/132952488-be4523b9-627b-4f47-8d91-5044ea37f150.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

这是可以复现的代码:
https://gitee.com/liaohui5/docker-egg-test

## 复现步骤，错误日志以及相关配置
1. 需要安装 docker 和 docker-compose
2. 下载代码 && 安装依赖
3. docker-compose up

## 相关环境信息
- **操作系统**: macos big sur
- **Node 版本**：14.17.5
- **Egg 版本**：`"egg": "^2.15.1",`

**Comment by hyj1991** [comment]
本地能连的话和 sequelize 无关，你的 docker-compose 配置问题吧，比如看看 mysql 的端口和宿主机做了映射没。

**Comment by liaohui5** [comment]
在 2021年9月12日 ***@***.***> 写道：


本地能连的话和 sequelize 无关，你的 docker-compose 配置问题吧，比如看看 mysql 的端口和宿主机做了映射没。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


docker-compose 端口映射做了, 那个线上的代码里有docker-compose
如果是端口映射没有做的话: 报错信息应该是这样的: Connection refused
那个报错信息中的图片中的信息不是这样的, 我百度过了, 但是我看不懂 
https://www.shangmayuan.com/a/0997033632b240c280a2937d.html
