### ISSUE TITLE
url中#(hash)过滤问题

### ISSUE THREAD

**Issue by ugvgylkm** [eggjs/egg#4758]
前台访问url：http://www.xxx.com/test/229/profile/#profile到后台获取url是http://www.xxx.com/test/229/profile/
是哪个安全策略把url中的#hash给过滤了么？

**Comment by atian25** [comment]
hash 本身就不会被发给服务端，这是 HTTP 知识。

如果你想发服务端，可以去了解下 h5mode

**Comment by CalmDownJ** [comment]
服务端不能获取到hash部分，但是：前端访问带有hash的url，服务端只是做重定向的话，url重定向时会带上hash哦
