### ISSUE TITLE
会话级session 关闭浏览器，不会过期

### ISSUE THREAD

**Issue by zlab** [eggjs/egg#476]
> cookie.setMaxAge(0);//不记录cookie
 cookie.setMaxAge(-1);//会话级cookie，关闭浏览器失效
 cookie.setMaxAge(60*60);//过期时间为1小时

### 能否达到以上效果

@atian25

**Comment by dead-horse** [comment]
```js
// config/config.default.js
export.session = {
  maxAge: 0, // 关闭浏览器就失效
  maxAge: 60 * 60 * 1000, // 1 个小时
};
```
