### ISSUE TITLE
process.env.EGG_READY_TIMEOUT_ENV具体如何修改

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4762]
## What happens?
我在项目中引入egg-sequelize，然后在node12.x环境下都正常运行，没有问题。
但是当我把node升级到14.x之后，egg启动时就会报：
WARN 40836 [egg:core:ready_timeout] 10 seconds later \node_modules\egg-sequelize\lib\loader.js:39:7 was still unable to finish.

这里猜测是egg-sequelize启动时可能比较慢导致egg-core这边超时了，所以我想试图修改egg-core的超时时间，看看能否解决问题。
同时想问一下，之前是否遇到过sequelize类似的问题。

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：14.15.4
- **Egg 版本**：2.30.0

**Comment by atian25** [comment]
连接数据库超时了吧，超过 10s 这个不正常，改超时时间不解决根本问题。检查下数据库链路是否通畅。

**Comment by shuidian** [comment]
嗯，确实还是sequelize的问题。这边看了下sequelize的issue，从里面找到了一个解决方案，就是把pg升级到8以上，这个问题就解决掉了。
https://github.com/sequelize/sequelize/issues/12364
