### ISSUE TITLE
在 schedule 中执行 controller 的 this.ctx.renderView 提示 renderView is undefined

### ISSUE THREAD

**Issue by dailijian** [eggjs/egg#4763]
## What happens?
在 schedule 中执行 controller 的 this.ctx.renderView 提示 renderView is undefined

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1. 在 schedule 中 代码如下：
```js
'use strict';

const Subscription = require('egg').Subscription;

class SendWeekly extends Subscription {
  static get schedule() {
    return {
      cron: '0 38 14 * * ?',
      type: 'all',
    };
  }
  async subscribe() {
    console.log('任务执行 : ' + new Date().toString()); let index = 0;
    const data = await this.app.controller.sendProjectWeekly.sendWeekly.call(this);
  }
}

module.exports = SendWeekly;
```

2. controller 代码
```js
'use strict';

const Controller = require('egg').Controller;

class SendProjectWeekly extends Controller {

  async sendWeekly() {
    // 生成模版
    const ctx = this.ctx;
    const html = await this.ctx.renderView('email/weekly.tpl',[]);
  }
}

module.exports = SendProjectWeekly;

```

## Context
- **Node v16.4.0**:
- **Egg v2.15.1**:
- **Platform mac**:

**Comment by dailijian** [comment]
在 config.default.js 已配置 view

**Comment by dailijian** [comment]
在 controller 中返回数据，在 schedule 中生成 renderView，即可。

**Comment by atian25** [comment]
Schedule 不要调用 Controller，放到 Service 去。
