### ISSUE TITLE
webstorm下方法无法跳转,没有提示

### ISSUE THREAD

**Issue by chengfeng12138** [eggjs/egg#4769]
![image](https://user-images.githubusercontent.com/43948017/135213375-22edd262-66bd-4e9f-9b2a-dd47ce328fbf.png)
webstorm编写Egg代码时, service下的方法无法通过鼠标点击跳转而且方法没有提示.

**Comment by atian25** [comment]
参考 https://zhuanlan.zhihu.com/p/56780733

我们只考虑生成 d.ts，根据 typings 跳转应该是 IDE 的职责。 WebStorm 我很久没用了，你可以看下它如何支持（理论上现代 IDE 都会支持的），搞明白后欢迎回来分享回馈。
