### ISSUE TITLE
如何执行独立的运维脚本，类似于集成测试，需要插件加载后执行特定文件，最后退出

### ISSUE THREAD

**Issue by xiaozzz** [eggjs/egg#4774]
需求：
1. 线上项目需要运行运维脚本，例如redis同步到mongo、dump数据等
2. 已有`schedule`任务搞定了脚本，但现在需要支持手动调用
3. 不想操心写2份代码、以及起环境（例如单独起数据库），如何单独调用该脚本？

**Comment by xiaozzz** [comment]
> 你指的是需要手动执行定时任务吧？看下这个：https://eggjs.org/zh-cn/basics/schedule.html#%E6%89%8B%E5%8A%A8%E6%89%A7%E8%A1%8C%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1

不全是，运维脚本希望可以是独立的一堆函数，只是我目前正好`schedule`也有同样的脚本。

即使是链接的这个方法，也仅限于`应用启动时`或者`单元测试`，这种能拿到`app`的情况。我现在更希望
`起一个真实线上环境，执行一段脚本，然后退出`

**Comment by 779022431** [comment]
@xiaozzz 我也有此类需求，egg的schedule不能优雅重启，所以这部分需要自己实现，但又想复用service，请问有解决方案了吗
