### ISSUE TITLE
【请教】egg在做分机集群时需要注意哪些事情？

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4780]
## What happens?
目前的业务是基于egg的，部署在单机服务器上，运行比较平稳。但是最近突然有了一个大型客户，全国上千家分店使用一套平台，对并发要求比较高，需要我们的服务可以分机集群，以提高并发性能。由于对集群的各种细节了解不多，希望能得到一些建议和注意事项上的指导。

目前了解到的点：
1、集群下mq的处理需要做改造，主节点统一负责mq的接收和发送，从节点的mq都从主节点获取。
2、缓存需要统一用redis，避免本地缓存。

其他还有什么需要注意的点吗？求指导。

**Comment by zzy7584** [comment]
想问下，egg 有分机集群的方案，可以借鉴吗？谢谢

**Comment by shuidian** [comment]
我先来总结一下自己遇到的情况吧：
1、全局变量从app移动到redis上，因为分机集群时，这种全局变量会出现各个机器上的值不一致的问题。
2、消息队列的处理，如果之前有用queue的，应该改为topic，因为queue的消息被某一个分机获取到之后，其他分机将无法获取。topic则没有这个限制，但是如果涉及到服务重启的场景，要考虑好在重启期间，topic信息将会丢失。同时，由于是分机部署，topic的方式需要避免重复执行的场景，这里我用的方案也是redis，基于redis锁，最先获取到锁的分机进行业务逻辑处理，其他分机在获取锁失败时，放弃本次操作即可（当然这里还需要考虑锁的超时和解除等细节，主流方案也都有现成的，参考一下即可。有一个现成的npm包，封装了redis锁机制：npm搜redlock）。这里我看redis好像有相关的订阅发布api，个人感觉消息队列切换到redis应该也可以，但是redis的消息队列个人没有实际使用过，不知道是否会有问题。
3、定时器的处理，定时器跟消息队列的处理思路类似，如果需要避免重复逻辑，考虑用redis锁即可。
以上就是在自己的业务场景中遇到的问题和处理方案，供大家参考。

**Comment by frankgo81** [comment]
考虑阿里的k8ns的serverless部署

**Comment by shuidian** [comment]
这边针对自己的业务场景，集群部署基本没啥问题了，先关闭这个issue了。
