### ISSUE TITLE
egg-scripts 2.14版本添加的--no-deprecation问题

### ISSUE THREAD

**Issue by dingiyan** [eggjs/egg#4784]
我使用pkg打包egg应用，升级egg-scripts之后无法正常启动。

启动时log参数不同：

升级前：
`Run node C:\snapshot\myapp\node_modules\egg-scripts\lib\start-cluster`

升级后：
`Run node --no-deprecation  C:\snapshot\myapp\node_modules\egg-scripts\lib\start-cluster`

我翻阅了源码，发现egg-scripts的2.14版本添加了该参数，并硬编码为false。但由于pkg内部的执行原理，所以参数位置发生变化就导致了pkg无法启动。（执行错误：不能找到/appDir/--no-deprecation模块。可判定pkg是取的node后的参数作为启动脚本）

问题：
外部是否可控制该参数？
如果目前不可控制，是否可添加一个可选的选项由外部控制该参数？

**Comment by hyj1991** [comment]
你的 `egg-scripts` 启动脚本是怎么写的？

node args 传递要这样写 `--node-options--no-deprecation`

**Comment by dingiyan** [comment]
@hyj1991 
我的pkg启动引导文件代码如下：
`
function setEggStartDir() {
  const baseDir = pkgInfo.pkg.eggDir || "C:/snapshot/myapp";
  const startIndex = process.argv.indexOf("start");
  if (startIndex > -1) {
    process.argv.splice(startIndex + 1, 0, baseDir);
  }
}
setEggStartDir();

// 拉取egg-script 开始启动egg程序
require(__dirname + "/node_modules/egg-scripts/bin/egg-scripts.js");
`
在require egg-scripts之前修改了一下process的argv。没有做其他任何事。

我猜测问题出在egg-scripts的execArgv参数传递给spawn时，可能是由于对象中key的排序问题，使--no-deprecation出现在前面，在正常使用egg-scripts时由于是普通node命令执行可以正常使用。而使用pkg则可能其内部是将紧跟node命令的第二个参数视为执行脚本的路径，因而出现 未找到模块 的错误。

--node-options--no-deprecation 这个参数是什么含义呢？望不吝赐教。是在程序启动的进程上提供的命令用于穿透提供给spawn执行egg的cluster启动时提供给它的进程的吗？

**Comment by caroline73** [comment]
那请问有什么解决方法吗

**Comment by yylink0208** [comment]
@dingiyan 请问除了降低egg-scripts的版本还有其他的解决方案吗
