### ISSUE TITLE
[问题] 请问eggjs日志怎么做到切换默认日志实例？

### ISSUE THREAD

**Issue by logzh** [eggjs/egg#4785]
大致的场景是：
1、配置文件中新增自定义日志，例如日志级别是DEBUG
2、请求发现是白名单用户，则切换默认日志实例为自定义的日志
3、打印日志的地方都是使用默认日志实例`ctx.logger`，这样输出更多debug信息

**Comment by hyj1991** [comment]
这个逻辑你只能自己根据 [自定义日志](https://eggjs.org/zh-cn/core/logger.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%97%A5%E5%BF%97) 能力进行扩展吧？

**Comment by hyj1991** [comment]
比如定义一个 debugLogger，写一个顶部中间件：
```js
async function changeLogger(ctx, next) {
  const defaultLogger = ctx.logger;
   if(/xxxxx/).test(ctx.url)) {
     ctx.logger = ctx.getLogger(`debugLogger`);
  }
  await next();
  ctx.logger = defaultLogger;
}
```

类似这种，示例是大概的逻辑组织方式

**Comment by atian25** [comment]
切换啥的都是代码上的技巧了，上面一君也提到了。

我想聊的是，背后的诉求，我猜你是想快速提取特定用户的链路日志啥的，这种其实在采集分析链路会更好一点。

**Comment by logzh** [comment]
@atian25 诉求就是特定用户会多打一些日志（通过不同日志级别），定位问题。采集分析链路，能稍微多提示一点吗？
