### ISSUE TITLE
请问curl的dataType如何同时支持json和text？

### ISSUE THREAD

**Issue by kiddkyd1412** [eggjs/egg#4787]
有一个第三方接口，正常情况下，会返回json数据。但是如果授权不对，就会返回一个html页面。
在使用this.ctx.curl的时候，dataType配置为json，或者text，都会导致无法支持另外一种情况的问题。
如果不配置dataType，那么返回的data好像是byte，这个怎么解析回字符串？

**Comment by atian25** [comment]
统一为 text，结果自己根据情况 parse
