### ISSUE TITLE
想问下，Egg.js的官网是用什么框架实现的？[Feature Request] say something

### ISSUE THREAD

**Issue by qq1120637483** [eggjs/egg#4788]
想问下，Egg.js的官网是用什么框架实现的？

**Comment by atian25** [comment]
hexo

建议用 vitepress

**Comment by qq1120637483** [comment]
> hexo
> 
> 建议用 vitepress

什么主题呢？我怎么没见过这个主题？

**Comment by atian25** [comment]
https://github.com/eggjs/doctools

自己做的主题。

**Comment by qq1120637483** [comment]
> https://github.com/eggjs/doctools
> 
> 自己做的主题。

强啊，我的哥，这效率，不愧是阿里大佬，吾等膜拜！
