### ISSUE TITLE
ctx.curl请求第三方服务时遇到的问题

### ISSUE THREAD

**Issue by chengfeng12138** [eggjs/egg#4790]
我在用 ctx.curl 请求第三方服务时报错了, 错误信息为 Content-Length can't be present with chunked encoding.
看起来像是响应头里的Content-length 和 Transfer-encoding: chunked冲突了，但是之前有用过0.12版本的node来请求同样的服务是没有这样的问题的。
我不知道egg是做了什么调整吗. 求大佬指点迷津.

![image](https://user-images.githubusercontent.com/43948017/140646676-d871b11d-177b-4dd3-9403-e019cfd62e4f.png)

**Comment by fengmk2** [comment]
这是 node http 模块的处理，Transfer-encoding: chunked 和 Content-length 不要同时设置。可以联系这个三方服务的开发者，告诉他们这个异常。
