### ISSUE TITLE
egg日志在服务器上显示问题

### ISSUE THREAD

**Issue by chengfeng12138** [eggjs/egg#4794]
发现个问题, 用egg自带的日志打印, 在服务器上查看时没有颜色. WARN 和 ERROR两个级别的日志都没有颜色, 有点不好看日志呢. 是设计成这样的吗还是说有什么配置呢? (正常来说 error的日志应该是红色的吧.) 

![image](https://user-images.githubusercontent.com/43948017/141061045-75fb4e29-d274-4607-9cab-f2a400fedff8.png)

**Comment by atian25** [comment]
可能是你的终端不支持着色吧，或者是 ContextLogger。

PS：线上日志一般是通过日志文件采集到日志平台看的，颜色没啥用处，善用 Grep 即可。
