### ISSUE TITLE
[Feature Request] 请问下agent如何运行定时任务

### ISSUE THREAD

**Issue by waltbest2** [eggjs/egg#4799]
## Background
当前如果让agent定时执行任务，都是在schedule中通知agent，agent监听消息通知，但是听说真正定时触发是由agent做的，所以这样相当于agent->worker->agent，多此一举。

## Proposal
请问如何优雅的给agent添加定时任务。

**Comment by atian25** [comment]
既然是定时任务，其实就不存在什么 agent 添加定时任务了，定时任务实际上就是一个 trigger，你的核心逻辑还是会写在一个 Service 里面的。

你这个需求，有几种可能的解法：

- 看 egg-schedule 源码，自定义一个策略，要满足你的调度需求（推荐）
- 看 egg-schedule 源码，在你需要的时机，发下对应的 messager 给 worker 即可。
- 自行约定一个 message，在你的 agent 里面发给 worker，woker 那边再注册对应的 hook 执行 service。
