### ISSUE TITLE
config里可以获取到ctx对像吗？

### ISSUE THREAD

**Issue by male110** [eggjs/egg#4802]
在egg-socket.io配置generateId我本想用用户的id来做为socketid的，这里需用到jwt，要用到ctx。不知道如何在config.default.js里取到ctx

**Comment by hyj1991** [comment]
如果只是调用纯方法，没有真实的上下文，用 mock 方法可以

```js
const { app } = require('egg-mock/bootstrap');
const ctx = app.mockContext();

ctx.ssss
```

**Comment by male110** [comment]
> ```js
> const { app } = require('egg-mock/bootstrap');
> const ctx = app.mockContext();
> ```

试了，报错了。
ERROR 21312 nodejs.ReferenceError: before is not defined (uncaughtException throw 1 times on pid:21312)
    at Object.<anonymous> (E:\activity\wanka-node\node_modules\egg-mock\bootstrap.js:21:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
在这个位置const { app } = require('egg-mock/bootstrap');

**Comment by male110** [comment]
parseJWT(token) {
    const { ctx } = this;
    try {
      const decoded = ctx.app.jwt.verify(token, ctx.app.config.jwt.secret);
      const timestamp = Date.parse(new Date()) / 1000;
      if (decoded.exp <= timestamp) {
        return null;
      }
      return decoded;
    } catch (error) {
      return null;
    }
  }
因为用到了token,jwt所以要ctx

**Comment by hyj1991** [comment]
> 试了，报错了。 

`await app.ready()`;
