### ISSUE TITLE
customLoader生成的app下的挂载，在schedule中动态配置定时任务的app参数下获取不到

### ISSUE THREAD

**Issue by guchenhui** [eggjs/egg#4804]
是生命周期的原因吗，有什么解决办法吗

**Comment by hyj1991** [comment]
提交一个代码仓库的例子看看

**Comment by guchenhui** [comment]
> 提交一个代码仓库的例子看看

https://github.com/guchenhui/testegg

**Comment by hyj1991** [comment]
文档里没说过 schedule 是这么写的吧？，加载文件的时候只有配置读取完毕了

**Comment by guchenhui** [comment]
https://github.com/eggjs/egg/blob/master/docs/source/zh-cn/basics/schedule.md#%E5%8A%A8%E6%80%81%E9%85%8D%E7%BD%AE%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1
有这个写法。所以奇怪为什么这里的app下没有挂载customLoader生成的东西。
算了，因为不涉及状态也不涉及ctx。我直接require文件了

**Comment by hyj1991** [comment]
> https://github.com/guchenhui/testegg

这是 app.config 已经合并完毕了，loader 挂载到 app 下的动作都没开始进行

**Comment by guchenhui** [comment]
> > https://github.com/guchenhui/testegg
> 
> 这是 app.config 已经合并完毕了，loader 挂载到 app 下的动作都没开始进行

所以有比较方便的办法调整customLoader挂载到app下的时机吗？

**Comment by hyj1991** [comment]
> 所以有比较方便的办法调整customLoader挂载到app下的时机吗？

这不是调整的问题，配置是配置，loader 是 loader，本来就不应该这么干
