### ISSUE TITLE
如何在生产模式以 xvfb-run -s "-ac -screen 0 1280x1024x24" 运行

### ISSUE THREAD

**Issue by hjane** [eggjs/egg#4811]
## What happens?

我项目中用到了FFcreator，在没有显示设备的情况下需要加上以下前缀来运行项目
xvfb-run -s "-ac -screen 0 1280x1024x24"  egg-bin dev 
当我以开发模式运行时，程序可以正常执行

xvfb-run -s "-ac -screen 0 1280x1024x24"  egg-scripts start --port=7001 --daemon --title=egg-server-showcase
当我以生产模式运行时，程序报错

ERROR 25182 nodejs.TypeError: Cannot read property 'ARRAY_BUFFER' of null
    at FFTransition.createBuffer (/www/wwwroot/zhipianxing/zhipianxing-node/node_modules/ffcreator/lib/animate/transition.js:73:45)

## 相关环境信息
- **操作系统**：
- centos 7
- **Node 版本**：
- v14.17.4
- **Egg 版本**：
- 2.15.1
- egg-scripts:
-  ^2.11.0"

**Comment by atian25** [comment]
跟 egg 没啥关系，你用的 ffcreator 的包的抛错。

可以试试去掉 daemon 模式看看

**Comment by hjane** [comment]
> 跟 egg 没啥关系，你用的 ffcreator 的包的抛错。
> 
> 可以试试去掉 daemon 模式看看

非常感谢，我去掉了daemon后可以正常执行了。
我开发模式能够正常执行，所以我一直觉得环境和包安装应该都没有问题。觉得是xvfb-run -s "-ac -screen  这个命令在生产环境中丢失了。因为直接yarn dev也报一样的错误。必须 xvfb-run -s "-ac -screen  0 1280x1024x24“ yarn dev，才能正常执行。
这样的话我接下来会尝试用pm2看能不能跑起来。
如果您有其他的想法和建议，请告诉我一下，非常感谢！
