### ISSUE TITLE
egg-mysql太好用了，能不能移植其他数据库

### ISSUE THREAD

**Issue by houxieyu** [eggjs/egg#4812]
个人感觉egg-mysql做快速开发太好了，既有orm的方便，不用拼接sql，还免去了生成一堆model，好喜欢，请求移植pg mssql这些数据库

**Comment by hyj1991** [comment]
egg-mysql 就是一个单纯的 mysql 客户端（在 ali-rds 外包了一层为 egg-plugin），如果你需要其他的 db client 支持，可以参考 egg-mysql 在对应的 db client sdk 之上进行封装
