### ISSUE TITLE
pkg打包后，无法正确读取prod配置

### ISSUE THREAD

**Issue by daoshenjay** [eggjs/egg#4815]
使用pkg打包项目后，prod配置无法正确读取，从而导致config.prod.js里面的配置都无法生效：
env配置为prod后，\node_modules\egg-core\lib\loader\getServerEnv()方法中：
`serverEnv = fs.readFileSync(envPath, 'utf8').trim();`
得到的结果serverEnv 为 “source-code-not-available”

最小可复现项目： [demo](https://github.com/daoshenjay/DemoEggPkg)
（1）npm install
（2）npm run pkg-win
（3）cd dist
（4）DemoEgg.exe start --daemon

程序跑起来后，可以在 项目\logs\master-stdout.log中看到相关日志输出：
getServerEnv() envPath :  c:\snapshot\DemoEggPkg\config\env
getServerEnv() fs.existsSync(envPath) :  true
getServerEnv() serverEnv :  source-code-not-available

**Comment by atian25** [comment]
那不是应该找找 pkg 的问题么，为啥 Node 正常的 `fs.readFileSync` 这个 API 拿到的响应是非预期的结果么？

**Comment by daoshenjay** [comment]
那你关了吧

**Comment by atian25** [comment]
`source-code-not-available` 这个提示应该也很明显了，估计是打包问题。

可以自己断点进去看看，或者看看 pkg 社区的讨论。
