### ISSUE TITLE
egg 生产环境通过spawn 执行一次webpack构建任务，终端输出webpack不存在

### ISSUE THREAD

**Issue by yunlzhang** [eggjs/egg#4816]
egg 生产环境通过spawn 执行一次webpack构建任务，终端输出webpack不存在

npm run dev 访问127.0.0.1:7001执行webpack构建任务OK

npm run start 后访问127.0.0.1:7001执行webpack构建任务 日志提示webpack不存在

日志记录如下：

```
sh: webpack: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! test@1.0.0 build: `yarn && webpack`
npm ERR! spawn ENOENT
```

测试代码：[https://github.com/yunlzhang/bug](https://github.com/yunlzhang/bug)

## Context
- **Node Version 10.18.0:
- **Egg Version ^2.15.1:
- **Platform:  macOS or linux

**Comment by atian25** [comment]
跟 egg 没啥关系

**Comment by yunlzhang** [comment]
跟egg没关，为啥 egg-dev模式下是OK的，生产环境就出错了

怀疑是egg-scripts上处理多进程worker有问题，未执行完毕或执行安装过程出错

**Comment by atian25** [comment]
![image](https://user-images.githubusercontent.com/227713/143973278-e3aed2be-1981-43e9-a6f2-c8edd40bb563.png)

1. 永远永远不要用 Sync 方法，去学习下 FS Promise API
2. spawn 不是这样用的，它是异步的，你也没有做异常处理等，去看看 execa 那个库吧
3. 你 webpack 都不在 dependencies 或服务端没全局，怎么找得到

先去把 Node 相关的基础 API 学习下，会更好理解一点。

**Comment by yunlzhang** [comment]
> ![image](https://user-images.githubusercontent.com/227713/143973278-e3aed2be-1981-43e9-a6f2-c8edd40bb563.png)
> 
> 1. 永远永远不要用 Sync 方法，去学习下 FS Promise API
> 2. spawn 不是这样用的，它是异步的，你也没有做异常处理等，去看看 execa 那个库吧
> 3. 你 Webpack 都不在 dependencies 或服务端没全局，怎么找得到
> 4. 多进程情况下跑 Webpack 这类重 CPU 操作对服务器压力很大的，做构建服务考虑用 fc 这类 `函数计算` 基础设施
> 
> 先去把 Node 相关的基础 API 学习下，会更好理解一点。

谢谢解答。明白其中的缘由了
egge-script 默认启动项目会修改 NODE_ENV为production ，在production环境下运行yarn 不会安装devDependencies依赖，所有会报webpack不存在错误。

**Comment by atian25** [comment]
看第 4 点吧，这类构建任务，不要用 web 服务来承载，要分到构建任务集群去，用阿里云函数计算。
