### ISSUE TITLE
[Feature Request] 请问egg.js如何实现html的热更新？

### ISSUE THREAD

**Issue by qq1120637483** [eggjs/egg#4821]
请问egg.js如何实现html的热更新？

**Comment by atian25** [comment]
不要放 static，作为 view 模板去渲染，更新后调用 view 对应的 api 去清除 cache

**Comment by qq1120637483** [comment]
> 不要放 static，作为 view 模板去渲染，更新后调用 view 对应的 api 去清除 cache

关键是如何调用api?清除cache?

**Comment by atian25** [comment]
看对应的 egg-view 和 egg-view-xx 插件文档和源码

**Comment by qq1120637483** [comment]
> 看对应的 egg-view 和 egg-view-xx 插件文档和源码

好嘞，谢谢了！每次回复都很及时，666
