### ISSUE TITLE
求助大神，我在全局的配置里面设置了onerror的html，但是我想输出数据库的东西，用了await，就是输出不了

### ISSUE THREAD

**Issue by leosj** [eggjs/egg#4823]
求助大神，我在全局的配置里面设置了onerror的html，但是我想输出数据库的东西，用了await，就是输出不了

exports.onerror = {
async all(err, ctx) {
	ctx.body = await ctx.service.data.getText();
	ctx.status = 500;
  }
}

这样就不会输出内容，去掉async，输出静态的就可以，求教怎么让他输出我查询的内容呢？就是要用async await，救救孩子

**Comment by atian25** [comment]
自己加个 Middleware 放到前面来全局 try catch
