### ISSUE TITLE
求助： 如何调试自定义模板

### ISSUE THREAD

**Issue by Tannnnnnnks** [eggjs/egg#4828]
我fork了一份  egg-boilerplate-simple的代码   想在里面定制了一些功能 但我发现没法直接运行调试  只能每次build   进dist安装依赖再run 非常不方便  刚用没多久还请赐教

**Comment by atian25** [comment]
用 https://github.com/node-modules/common-boilerplate 吧，egg-init 那块在 3.0 会重构为它。

**Comment by Tannnnnnnks** [comment]
能够给个简单的创建步骤或示例

**Comment by atian25** [comment]
那边有 README，也有对应的 test/fixtures 可以看看
