### ISSUE TITLE
小白求助~   public文件夹下的资源访问如何做权限验证

### ISSUE THREAD

**Issue by xkkkA** [eggjs/egg#4829]
我现在需要对public文件夹下的文件访问做权限验证，接口权限都是通过中间件实现，但是Public访问时不会经过中间件，请求有什么办法？

**Comment by atian25** [comment]
1. 文件放到服务器单机文件目录是不推荐的，这类文件尽量放到 阿里云 oss 这些云存储去吧，然后通过防盗链来生成临时链接。
2. public 更多是方便本地调试啥的，静态资源啥的前端工程化一般会在构建时发到 cdn 去。
3. 实在要做的话（不建议），要么自定义一个目录，自己写 router 去返回这些文件，要么把中间件加到 coreMiddleware 的 static 前面。

**Comment by xkkkA** [comment]
感谢大佬指导， 我下来调研调研存储方案
