### ISSUE TITLE
求助：

### ISSUE THREAD

**Issue by lswd** [eggjs/egg#4830]
Egg部署服务器，npm run dev是ok的，但是用PM管理工具PM使用命令npm start报错这个是啥原因呢，下边是服务器信息和报错信息
服务器信息：
![QQ图片20211208090009](https://user-images.githubusercontent.com/24218775/145129684-e7e91c21-a0cd-4c07-8053-173d49b8e200.png)

报错信息：

![QQ图片20211208090017](https://user-images.githubusercontent.com/24218775/145129701-934cf38e-546b-4120-b5a2-b05c386e7c6c.png)

**Comment by atian25** [comment]
1. egg-scripts 会检测启动日志有没有 error 或 warning 信息，从而退出，你可以用 --ignore-stderr 参数忽略（你仔细看看错误信息嘛，最后面都写的很清楚了）
2. 那条 Deprecation Warning 信息其实描述的很清楚了，是新版 Node 导致的，如果是单数的 Node 版本不要用，然后再重新安装最新的依赖。
3. egg 不需要用 PM2，具体看官方文档 FAQ 有写。

**Comment by lswd** [comment]
@atian25 感谢大佬 已解决
