### ISSUE TITLE
如何使用egg实现数据的流式下载

### ISSUE THREAD

**Issue by InCodingNowLiu** [eggjs/egg#4831]
例如我有100w条数据, 我不可能一次性从数据库读出来, 写入文件
目标: 每次读取1000条数据, 然后流式返回, 这样可以避免1.不用写入文件 2.内存占用小

![image](https://user-images.githubusercontent.com/31758568/145350006-ea74e228-8e5a-482c-bc63-5b5800e9ada8.png)

**Comment by atian25** [comment]
stream.PassThrough
