### ISSUE TITLE
egg-script的readme里面停止命令的title参数有歧义

### ISSUE THREAD

**Issue by shuidian** [eggjs/egg#4832]
我的理解，stop指令应该是可以跟--title=app_name，但是示例中加了一个中括号，一般来讲这个中括号应该是代表可选参数的意思吧？而不是真的需要在命令后面加中括号吧？

实际使用应该是：eggctl stop --title=app_name

而不是：eggctl stop [--title=app_name]

不知道我理解的是否正确

![image](https://user-images.githubusercontent.com/19830601/145750133-036903f5-c2f1-4505-84bd-3b502d72693a.png)

**Comment by hyj1991** [comment]
> https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/stop.js#L40-L42

**Comment by shuidian** [comment]
> > https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/stop.js#L40-L42
> 
> 文档写的并没错，`title` 本来就是可选参数，参见上面的 stop 实现，不带 `title` 参数会干掉所有的 start-cluster 起来的 egg 进程，带上 `title` 只会干掉对应的 egg 进程。
> 
> 源码面前无奥秘，其实 egg 框架的很多实现并不复杂，遇到觉得奇怪的地方不妨去对应的库看看具体实现，如果确实有问题，给 egg 提 pr 做贡献的机会就来了 :)

道理是这么个道理，但我要表达的意思是，能用文档写清楚的事，就尽量别靠翻源码，我们总不能要求每个使用者都去翻看源码不是？egg-scripts的readme里面的stop示例确实是容易误解，尤其readme上面的start示例又没加中括号，这种文档层面上的内容，如果写的清晰一些，可以降低使用者的疑惑，也会提升egg的体验，不是挺好的嘛。

**Comment by darrenliuwei** [comment]
> > > https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/stop.js#L40-L42
> > 
> > 
> > 文档写的并没错，`title` 本来就是可选参数，参见上面的 stop 实现，不带 `title` 参数会干掉所有的 start-cluster 起来的 egg 进程，带上 `title` 只会干掉对应的 egg 进程。
> > 源码面前无奥秘，其实 egg 框架的很多实现并不复杂，遇到觉得奇怪的地方不妨去对应的库看看具体实现，如果确实有问题，给 egg 提 pr 做贡献的机会就来了 :)
> 
> 道理是这么个道理，但我要表达的意思是，能用文档写清楚的事，就尽量别靠翻源码，我们总不能要求每个使用者都去翻看源码不是？egg-scripts的readme里面的stop示例确实是容易误解，尤其readme上面的start示例又没加中括号，这种文档层面上的内容，如果写的清晰一些，可以降低使用者的疑惑，也会提升egg的体验，不是挺好的嘛。

他已经回答你了“文档写的并没有错，title 本来就是可选参数。。。”，后面说可以翻源码，只是给你多一个可选项而已。

我看了下你发的截图，start 是有中括号的：
![image](https://user-images.githubusercontent.com/10508248/146946302-66ac8a2b-9a2e-4a75-a3bb-6d6fc14da5da.png)

**Comment by shuidian** [comment]
> > > > https://github.com/eggjs/egg-scripts/blob/master/lib/cmd/stop.js#L40-L42
> > > 
> > > 
> > > 文档写的并没错，`title` 本来就是可选参数，参见上面的 stop 实现，不带 `title` 参数会干掉所有的 start-cluster 起来的 egg 进程，带上 `title` 只会干掉对应的 egg 进程。
> > > 源码面前无奥秘，其实 egg 框架的很多实现并不复杂，遇到觉得奇怪的地方不妨去对应的库看看具体实现，如果确实有问题，给 egg 提 pr 做贡献的机会就来了 :)
> > 
> > 
> > 道理是这么个道理，但我要表达的意思是，能用文档写清楚的事，就尽量别靠翻源码，我们总不能要求每个使用者都去翻看源码不是？egg-scripts的readme里面的stop示例确实是容易误解，尤其readme上面的start示例又没加中括号，这种文档层面上的内容，如果写的清晰一些，可以降低使用者的疑惑，也会提升egg的体验，不是挺好的嘛。
> 
> 他已经回答你了“文档写的并没有错，title 本来就是可选参数。。。”，后面说可以翻源码，只是给你多一个可选项而已。
> 
> 我看了下你发的截图，start 是有中括号的： ![image](https://user-images.githubusercontent.com/10508248/146946302-66ac8a2b-9a2e-4a75-a3bb-6d6fc14da5da.png)

不知道你看过egg-script的redeme没，建议你亲自去看下，感受下。我说的从来不是文档错不错的问题，我说的是清晰易懂的问题。如果还是不理解，我再给你截张图，如果还不理解，那我也没办法了。。。
![image](https://user-images.githubusercontent.com/19830601/147032478-ffd02de0-1bc6-4f93-967d-473a6e28e6dd.png)

**Comment by darrenliuwei** [comment]
看你的截图，是有一点点不一样，你可以去提一个PR。

个人建议可以改成下面这样：

```bash
$ eggctl stop [options]
# Usage
# eggctl stop --title=example
```

**Comment by shuidian** [comment]
> 看你的截图，是有一点点不一样，你可以去提一个PR。
> 
> 个人建议可以改成下面这样：
> 
> ```shell
> $ eggctl stop [options]
> # Usage
> # eggctl stop --title=example
> ```

已提，https://github.com/eggjs/egg-scripts/pull/51

**Comment by atian25** [comment]
这个跟背景可能有关系，熟悉 linux 和命令行的，会很容易理解 `[]` 代表可选参数的意思，其他的同学可能会有一定的疑惑
