### ISSUE TITLE
listen options

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#484]
listen 参数支持

```js
module.exports = {
  listen: {
    path: '',
    port: '',
    backlog: '',
    hostname: '',
  }
}
```

listen 的时候可以获取 `app.config`，所以参数加到 config 比 startCluster 更好。

- config.listen.port 的优先级高于 startCluster 传入的。
- 如果指定了 path 则优先级更高。

解决 https://github.com/eggjs/egg/issues/469 和 https://github.com/eggjs/egg/issues/435

**Comment by atian25** [comment]
> config.listen.port 的优先级高于 startCluster 传入的。

应该是命令行传参大于配置吧?

其他参数需要支持 startCluster 传参么?

**Comment by dead-horse** [comment]
startCluster 优于配置比较符合直观一点

**Comment by dead-horse** [comment]
这些参数是否都是可以通过 startCluster 传递的？还是只能传 port？

**Comment by popomore** [comment]
我倾向放配置，不用穿参数。主要是 startCluster 优先，port 永远不会生效，所以如果这样的话要把 port 的默认值设为空，透传到 app_worker

**Comment by fengmk2** [comment]
挺好的，将 cli 的 port 传空吧，按常理理解 cli 参数比配置高优先级。

**Comment by fengmk2** [comment]
统一到 start 配置项？这样起多少个进程都可以配置了。而且也可以给后续扩展留好路子。

```js
module.exports = {
  start: {
    listen: {},
    fork: {},
  }
}
```

**Comment by fengmk2** [comment]
其实通过配置方式真的比较方便，这样我作为上层应用 chair，需要约定chair 自己的环境变量，也能够实现了。

CHAIR_SERVER_PORT = 8080 startCluster.js

```js
module.exports = {
  start: {
    listen: { port: process.env.CHAIR_SERVER_PORT || 7001 }
  }
};
```

这样就实现了应用框架自己的环境变量了。

**Comment by popomore** [comment]
fork 不行，master 不读 config 的。

**Comment by popomore** [comment]
这个要不放 1.0 之后再做

**Comment by atian25** [comment]
这个不是 break 的吧，感觉可以不急在 1.0 做。

**Comment by LiShiSangZi** [comment]
这个近期有计划吗？我们也遇到这个坑了。
运维希望我们能够配置端口和IP。

**Comment by popomore** [comment]
好的，我支持一下

**Comment by LiShiSangZi** [comment]
@popomore 希望尽快推出。如果有需要我们可以帮忙upstream。
