### ISSUE TITLE
[RFC] Better http lib: undici

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#4847]
## 背景

undici 已经被大规模使用，当初做 urllib 是 node 的基础 http 库太弱，现在 node 官方在支持 undici 快速迭代，并且性能非常好，没理由不去升级的。
![image](https://user-images.githubusercontent.com/156269/147727365-f257bd71-0386-437a-acf0-827413b7867c.png)

## 思路

- 基于 undici 做一个 egg httpclient 实现，api 遵循 undici 的开发者习惯。
- 基于这个 undici 实现的 httpclient 封装一个兼容 urllib 接口的过渡性 httpclient，在当前 egg 版本通过配置可以选择是 urllib 还是 undici 作为基础 http 库，默认是 urllib。在下一个 egg 大版本默认改成 undici，下下个 egg 大版本将 urllib 设置为 deprecated，只保留安全更新不再新增新功能。

## 跟进

- [x] 基于 undici 做一个 egg httpclient 实现 https://github.com/node-modules/urllib/pull/382
- [x] 基于这个 undici 实现的 httpclient 封装一个兼容 urllib 接口的过渡性 httpclient https://github.com/node-modules/urllib/pull/382
- [ ] ~~文档默认推荐 fetch 接口，支持 httpclient 一样的 tracing 能力~~
- [x]  默认还是 urllib request 接口，通过 https://github.com/nodejs/undici/blob/main/docs/api/DiagnosticsChannel.md 实现 tracing

**Comment by fengmk2** [comment]
https://zhuanlan.zhihu.com/p/450088312

**Comment by hyj1991** [comment]
和目前基于 urllib 的 httpclient 的 api 要保持兼容么，还是直接 break 掉

**Comment by fengmk2** [comment]
ùn·di·ci

**Comment by fengmk2** [comment]
> * 基于这个 undici 实现的 httpclient 封装一个兼容 urllib 接口的过渡性 httpclient，在当前 egg 版本通过配置可以选择是 urllib 还是 undici 作为基础 http 库，默认是 urllib。在下一个 egg 大版本默认改成 undici，下下个 egg 大版本将 urllib 设置为 deprecated，只保留安全更新不再新增新功能。

基于这个 undici 实现的 httpclient 封装一个兼容 urllib 接口的过渡性 httpclient，在当前 egg 版本通过配置可以选择是 urllib 还是 undici 作为基础 http 库，默认是 urllib。在下一个 egg 大版本默认改成 undici，下下个 egg 大版本将 urllib 设置为 deprecated，只保留安全更新不再新增新功能。

**Comment by fengmk2** [comment]
> 和目前基于 urllib 的 httpclient 的 api 要保持兼容么，还是直接 break 掉

基于这个 undici 实现的 httpclient 封装一个兼容 urllib 接口的过渡性 httpclient，在当前 egg 版本通过配置可以选择是 urllib 还是 undici 作为基础 http 库，默认是 urllib。在下一个 egg 大版本默认改成 undici，下下个 egg 大版本将 urllib 设置为 deprecated，只保留安全更新不再新增新功能。

**Comment by fengmk2** [comment]
https://github.com/nodejs/undici

**Comment by fengmk2** [comment]
mock 都想得很完善 https://github.com/nodejs/undici/blob/main/docs/best-practices/mocking-request.md

**Comment by fengmk2** [comment]
https://github.com/nodejs/node/pull/41749/files 直接 fetch api 即可统一前后端。

**Comment by fengmk2** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by fengmk2** [comment]
使用 Fetch 的话得将 tracing 上下文带进去，需要看看这块怎么实现。

**Comment by fengmk2** [comment]
https://github.com/nodejs/undici/blob/main/docs/api/DiagnosticsChannel.md 好完善。

**Comment by fengmk2** [comment]
fetch api 不太适合服务端编程，继续使用 urllib request 的 api 作为标准接口。

**Comment by liuhanqu** [comment]
> fetch api 不太适合服务端编程，继续使用 urllib request 的 api 作为标准接口。

想问下为什么说 fetch api 不太适合服务端编程呢

**Comment by fengmk2** [comment]
@liuhanqu 核心的是性能损耗太多。
另外一个考虑是已有的代码都依赖了 urllib 的 request api 接口兼容性，改不掉。

**Comment by fengmk2** [comment]
性能已经是 urllib2 的 2.7 倍

![image](https://user-images.githubusercontent.com/156269/179361265-09ff71fc-c8ab-4772-8b00-ee1d620c7a2d.png)

**Comment by fengmk2** [comment]
SAMPLES=50 npm run bench 

https://github.com/fengmk2/undici/blob/urllib-benchmark/benchmarks/benchmark.js

![image](https://user-images.githubusercontent.com/156269/179361425-7dcaca96-bf60-4c55-aaf5-1cd2361663fe.png)

**Comment by fengmk2** [comment]
npminstall 升级之后性能提升 https://github.com/cnpm/npminstall/pull/407#issuecomment-1187507752

**Comment by atian25** [comment]
API 上有啥 break change 不？

**Comment by fengmk2** [comment]
@atian25 有，不过都是古老的，只能 break
