### ISSUE TITLE
content.js takes time

### ISSUE THREAD

**Issue by DanaCoding** [eggjs/egg#4849]
## What happens?
![image](https://user-images.githubusercontent.com/93444868/147879075-32dac758-2691-4f8b-bfa2-cf72c0474267.png)

这个 content.js 具体是什么，它占用的时间很多，随着项目的增长，是否会继续增加，有优化手段吗？

## 复现步骤，错误日志以及相关配置

`npm init egg --type=simple` 初始化的项目

## 相关环境信息
- **操作系统**：Window 10 pro
- **Node 版本**：16.13.1
- **Egg 版本**：2.15.1

**Comment by atian25** [comment]
跟 egg 没啥关系…… 这是浏览器侧吧

**Comment by DanaCoding** [comment]
> 跟 egg 没啥关系…… 这是浏览器侧吧

是的，B端
