### ISSUE TITLE
某一接口阻塞时影响该接口后续请求时间

### ISSUE THREAD

**Issue by lilililee** [eggjs/egg#4854]
## 最小可复现仓库
npm init egg --type=simple 创建

## 复现步骤，错误日志以及相关配置
1. 修改` /app/controller/home.js`，并` yarn dev `启动
```
'use strict';

const Controller = require('egg').Controller;

const delay = t => new Promise(resolve => setTimeout(resolve, t));

class HomeController extends Controller {
  async index() {
    const { ctx } = this;

    await delay(5000); // 增加接口响应延时
    
    ctx.body = 'hi, egg';
  }
}

module.exports = HomeController;
```

2. 在浏览器两个标签页同时访问 `http://127.0.0.1:7001/`

![image](https://user-images.githubusercontent.com/24242242/148493683-6a5f1f67-afc8-4818-b2af-5152a87e8424.png)
![image](https://user-images.githubusercontent.com/24242242/148493709-9a687e98-73a6-444f-b9f2-5c63ffb6b648.png)
如图所示，第一个接口响应正常 5s，第二个接口需要等第一个接口处理完后才开始处理，结果是 9.2s，期望结果是 5s

## 相关环境信息
- **操作系统**：windows 10
- **Node 版本**：14.16.0
- **Egg 版本**：2.33.1

**Comment by atian25** [comment]
1. 不要用浏览器来测试，它本身就同个 host 有连接数的限制，自己用 curl 测试就知道了。
2. 另外，你这不是真阻塞， 重 CPU 的那种阻塞，也不是 Web 服务的职责，应该放到函数计算去。
