### ISSUE TITLE
egg-core更新版本的时候没有对eggjs/router 的semver进行同步更新          eggjs/router@2.0.0有bug

### ISSUE THREAD

**Issue by shayulajiaoten** [eggjs/egg#4855]
egg对egg-core的引用的semver也同样没有更新

eggjs/router@2.0.0----->koa-router的bug为ctx._matchedRoute无法拿到正确的值

**Comment by atian25** [comment]
egg-core 是 ^ 引入的，不可能没更新，清空 node_modules 重新安装试试。

**Comment by shayulajiaoten** [comment]
> 



> egg-core 是 ^ 引入的，不可能没更新，清空 node_modules 重新安装试试。

"egg": {
        "egg-core": "^4.18.0"
}
这是package-lock.json


我未升级的时候安装了的版本是egg-core: 4.20------------>该版本引入的eggjs/route有bug
这个时候我即使执行npm i egg@2.x去升级版本，npm不会去更新package-lock.json的版本，因为它在^4.18的范围
所以egg在升级的时候，是否应该把egg-core的semver变为^4.21

**Comment by atian25** [comment]
你自己 lock 了能怪谁。。。

我们遵循 Semver 规则，不鼓励锁版本，锁版本后自行解决依赖更新问题。

**Comment by shayulajiaoten** [comment]
> 你自己 lock 了能怪谁。。。
> 
> 我们遵循 Semver 规则，不鼓励锁版本，锁版本后自行解决依赖更新问题。
> 
> 而且由于包管理器的依赖安装问题，建议每次更新依赖都是删除目录后全量更新，不要单个更新。

好的感谢回复，这回复效率有点高哈。。。
