### ISSUE TITLE
npm  init egg 出错

### ISSUE THREAD

**Issue by xydwhaha** [eggjs/egg#4858]
## What happens?

npm init egg --type=simple 出错
输入命令后一直显示乱码
![1641733991(1)](https://user-images.githubusercontent.com/32017553/148683665-13dbeadb-8a01-4868-befe-3637bff5ef94.png)
像这样 ，
感觉跟上一个issue有点像，应该就是同一个

## 相关环境信息
- **操作系统**：win10
- **Node 版本**：v16.13.1.
- **Egg 版本**：最新的吧

**Comment by atian25** [comment]
dup https://github.com/eggjs/egg/issues/4857
