### ISSUE TITLE
How to mock host in UT

### ISSUE THREAD

**Issue by YangLG-7** [eggjs/egg#4859]
I want to test the controller;

the code like：
```
in controller.js

 if (ctx.request.header.host !== 'xxxx:port') {
      return this.error({ msg: 'host is invalid' });
}

```

but in UT；I try to use `mockHeaders` API to mock host ； 
the code like：
```
app.mockService('xxx', 'xxx', (param) => param);
app.mockHeaders({host: 'xxxx:port'});

 app
.httpRequest()
.post('/innerCommon/resetRedis')
.type('json')
.send(xxx)
.expect(200)
.expect({data:{msg: 'host is invalid' }});
```
It doesn't work

**Comment by atian25** [comment]
`httpRequest` is just a wrap of `supertest`, see docs of it how to send host header

`.set('host', '')`

**Comment by YangLG-7** [comment]
Thank you for your reply. I actually thought of this, but I didn't find this API on your official website。Could you tell me where your API documents can be viewed? @atian25

**Comment by atian25** [comment]
just in right there of supertest 's README: https://github.com/visionmedia/supertest

**Comment by YangLG-7** [comment]
Thanks! I really appreciate it!
