### ISSUE TITLE
启动日志如何查看问题

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#486]
默认有四类日志：https://eggjs.org/zh-cn/core/logger.html

但好像都没有启动日志，下图是我terminal中的启动日志，因为mysql配置导致链接报错，不会出现在上述4种日志中。

![image](https://cloud.githubusercontent.com/assets/1297278/23458241/5ece62b4-feb6-11e6-94f4-49e525f7fcf1.png)

**Comment by dead-horse** [comment]
你下面截图上面一段好像有个一个 TIMEOUT 的错误？

**Comment by atian25** [comment]
close due to not more detail, feel free to reopen.

**Comment by johnnychen** [comment]
@dead-horse 那个timeout是连接数据库错误，请教下打印在控制台中的错误信息为什么没有记录到`common-error.log`文件中呢？

**Comment by dead-horse** [comment]
worker died error 是只会打印到 console 的，因为 logger 对象在 worker 进程中才有，worker 已经挂了，这个日志是 master 进程打印的。

**Comment by johnnychen** [comment]
worker died error 不应该是先在app_worker.js连接数据库的时候报错捕获, agent_woker记录，其中app_worker捕获后又抛给master进程，最后才挂掉呢？
