### ISSUE TITLE
egg-bin dev使用了非local配置后，自动重启无效

### ISSUE THREAD

**Issue by yexiaodong** [eggjs/egg#4862]
以下四个配置，只有第一个的自动重启有效，其他的都无效
`
    "dev": "egg-bin dev --port 8080",
    "dev:unittest": "egg-bin dev --port 8080 --env=unittest",
    "dev:test": "cross-env EGG_SERVER_ENV=test egg-bin dev --port 8080",
    "dev:prod": "egg-bin dev --port 8080 --env=prod",
`
通过Issues查看，eggd的设计是开发环境只有一个（local）。
但实际开发过程中，经常需要切换为后端接口同事的环境，进行联调，只有一个开发环境会很不方便。

**Comment by atian25** [comment]
你为啥不都放在 local 配置里面，然后通过环境变量来切联调环境咯：

```js
// config/config.local.js
if (process.env.backend === 'xxx') {
  exports.host = 'xxx+xx';
}
```

```bash
$ backend=xxx npm run dev
```

**Comment by yexiaodong** [comment]
这样相同配置就要写多次了

**Comment by atian25** [comment]
怎么会呢，这不就是你代码自己的组织问题么

```js
const xx = {
  a: '1',
  b: '2',
}

if(process.env.xx) {
  xx.a = 'aaaaaaaaa'
}
```

**Comment by bingyang519** [comment]
1 、package.json
"dev": "EGG_SERVER_ENV=dev egg-bin dev",

2、config.dev.js
config.watcher = {
        type: 'development',
    };

3、plugin.js
exports.development = {
    env: ['dev'],
};
