### ISSUE TITLE
阿里node性能平台看不了进程数据

### ISSUE THREAD

**Issue by xbw187** [eggjs/egg#4864]
![Snipaste_2022-01-15_22-09-50](https://user-images.githubusercontent.com/55755493/149624683-b74b768d-10ad-46e4-9c8d-1591e29512fc.png)

之前的项目接入过这个 是可以正常查看的 最近的这个接入了查看不了 完全安装官网的步骤装的 node版本为14.18.1 [https://help.aliyun.com/document_detail/60811.html](url) 官网也有对应的版本 可是就是看不了进程数据

**Comment by hyj1991** [comment]
这不是提示了么，你现在启动使用的 runtime 不是 alinode

**Comment by xbw187** [comment]
> 这不是提示了么，你现在启动使用的 runtime 不是 alinode 
可问题是我每一步都是按照步骤来的啊
