### ISSUE TITLE
怎么在中间件中动态调用控制器中的异步方法？

### ISSUE THREAD

**Issue by kkxunguan** [eggjs/egg#4865]
怎么在中间件 service 中动态调用控制器 ServiceController 中的异步方法 index，请求url：http://127.0.0.1:7001/public?s=index&b=2

我用的这个方法好像 会报错

![1642257985](https://user-images.githubusercontent.com/23550074/149626032-7438a913-e8a0-4176-8e4f-4e3839ce0869.jpg)

![5](https://user-images.githubusercontent.com/23550074/149626251-848d63e1-b27f-44e4-acfa-ba0b6d1f47fc.png)

报错信息：

![4](https://user-images.githubusercontent.com/23550074/149626174-6cd33e7f-8289-4f7f-b3b8-3e2d048d9bec.png)

难道框架默认不支持动态调用？？？？

**Comment by atian25** [comment]
逻辑复用放到 Service，不要 Controller 调用 Controller
