### ISSUE TITLE
service中连着调用了一个函数两次（传入参数不同），在单元测试中需要app.mockService两次吗

### ISSUE THREAD

**Issue by KIngCrzy** [eggjs/egg#4871]
## What happens?
service中连着调用了一个函数两次（传入参数不同），在单元测试中app.mockService一次就能通过测试 且 后面断言该函数的传参必是第二次调用的传参，请问这是正常的吗？

## 相关环境信息
- **操作系统**：mac
- **Node 版本**：14.17.4
- **Egg 版本**：^2.26.1

**Comment by atian25** [comment]
你想问啥？

**Comment by KIngCrzy** [comment]
> 你想问啥？

想了解一下为什么不需要mockService两次（因为service中调用了两次，并且不Mock一定会报错）

**Comment by atian25** [comment]
mock 的本质不就是把某个函数替换为另一个函数了，只要不被重新 new 或者 restore，当然一直存在

**Comment by atian25** [comment]
空谈其实没啥用，直接给出可复现的代码库，我们就代码讨论

**Comment by KIngCrzy** [comment]
> mock 的本质不就是把某个函数替换为另一个函数了，只要不被重新 new 或者 restore，当然一直存在

明白
