### ISSUE TITLE
无法访问官网及文档 Couldn't open websites

### ISSUE THREAD

**Issue by bollnh** [eggjs/egg#4876]
## What happens?
Couldn't open websites and documents.
无法访问官网及文档

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub
Not relative to repository, it's the website: https://eggjs.org/

## How To Reproduce
Here is the [screenshot](https://imgur.com/a/rP85dBK.png)

**Steps to reproduce the behavior:**
1. open https://eggjs.org/

**Expected behavior**
1. normal website

## Context
- **Node Version**: latest
- **Egg Version**: latest
- **Plugin Name**: None
- **Plugin Version**: None
- **Platform**: Windows 10, Chrome Version 97.0.4692.99

**Comment by bollnh** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙访问。

My current location is in Los Angeles, not in China. This problem does not exist.

**Comment by fengmk2** [comment]
源站出了问题，今天会修复域名解析。

**Comment by bollnh** [comment]
> 源站出了问题，今天会修复域名解析。

了解，感谢回复！

**Comment by bi-kai** [comment]
凌晨1点左右断的，静态网站，尽快修复下呗。

**Comment by zhangzhaoaaa** [comment]
加油

**Comment by soupor** [comment]
辛苦,等待中

**Comment by mengbo-ji** [comment]
辛苦，等待中，我也无法访问官网

**Comment by kybetter** [comment]
哈哈，大家都来报道啦，点着点着就 404 了

**Comment by beesprite** [comment]
证书的问题吧 ，老板加油

**Comment by ocylib** [comment]
> 由于某些众所周知的原因无法访问，建议翻墙访问。

@egg-bot

**Comment by darrenliuwei** [comment]
![image](https://user-images.githubusercontent.com/10508248/153125901-2fc1585a-f083-4b7e-80b4-b3d5dab0a16d.png)

**Comment by fengmk2** [comment]
https://eggjs.org/zh-cn/ 恢复了。

**Comment by darrenliuwei** [comment]
> https://eggjs.org/zh-cn/ 恢复了。

好像又挂了。。
