### ISSUE TITLE
使用alinode没有进程数据，当前 node 为非 alinode 版本

### ISSUE THREAD

**Issue by zhangbianyu** [eggjs/egg#4877]
按照egg官网文档配置egg-alinode，启动时也提示 agent register ok.  但是在性能平台上查看实例信息的时候说 当前node为非alinode版本。 之前也有大佬提过，但是好像没解决。  https://github.com/eggjs/egg/issues/2078 

Node Version: 14.18.3
Egg Version: 2.33.1
Plugin Name: egg-alinode
Plugin Version: 2.0.1

以下是我的配置

<img width="596" alt="截屏2022-02-09 上午9 37 47" src="https://user-images.githubusercontent.com/28701677/153105395-6073c8a4-410f-4dfc-95a6-bbaa97e6d038.png">

<img width="677" alt="截屏2022-02-09 上午9 42 22" src="https://user-images.githubusercontent.com/28701677/153105812-d528e9e7-56e3-4c74-946c-cab62bafe1ae.png">

<img width="659" alt="截屏2022-02-09 上午9 43 04" src="https://user-images.githubusercontent.com/28701677/153105874-7c966c40-c4b3-4156-967f-d13ac0620c4c.png">

启动之后也有agent register ok.
<img width="961" alt="截屏2022-02-09 上午9 43 59" src="https://user-images.githubusercontent.com/28701677/153105963-8615b29b-d23a-4c07-847f-2cc9e18fe55b.png">

但是在实例信息里说node版本不对

<img width="1668" alt="截屏2022-02-09 上午9 47 26" src="https://user-images.githubusercontent.com/28701677/153106562-346bdc4a-7288-470c-b494-afe458d1fe39.png">

但是也能监测到异常

<img width="1611" alt="截屏2022-02-09 上午9 51 50" src="https://user-images.githubusercontent.com/28701677/153106779-d3558d90-8650-4a11-aa6c-8b0547ea34a5.png">

有大佬知道怎么才能有进程数据么？ 急~

**Comment by hyj1991** [comment]
你要先去确认启动 egg 进程的 node 是不是 alinode，egg-alinode 这个 plugin 只是帮你自动接入了采集数据的 agent 而已。

**Comment by zhangbianyu** [comment]
> 你要先去确认启动 egg 进程的 node 是不是 alinode，egg-alinode 这个 plugin 只是帮你自动接入了采集数据的 agent 而已。

原来是这样，我再去研究下，感谢！

**Comment by hyj1991** [comment]
官方也有答疑钉钉群：11794270，你可以去那边咨询使用问题:)

**Comment by zhangbianyu** [comment]
> 官方也有答疑钉钉群：11794270，你可以去那边咨询使用问题:)

好嘞，多谢多谢！

**Comment by zhangbianyu** [comment]
> 官方也有答疑钉钉群：11794270，你可以去那边咨询使用问题:)

加群有什么条件么？我申请了没通过

**Comment by hyj1991** [comment]
等管理员审批吧，他们不一定能实时看到

**Comment by zhangbianyu** [comment]
> 等管理员审批吧，他们不一定能实时看到

好的好的，我以为未通过是拒绝了，应该是还没审核😂，多谢
