### ISSUE TITLE
easyswoole验证器快速验证增加inArray、notInArray

### ISSUE THREAD

**Issue by Nr-zhang** [eggjs/egg#4887]
## 背景
验证中使用快速验证，但是in相关的验证无法使用，这会变得很麻烦

## 提议
vendor\easyswoole\validate\src\Validate.php中的make方法236~237行改为：
if(in_array($action,['inArray','notInArray'])){
    //重写inArray和notInArray
    $validateRule->{$action}($actionArgs,false,$errMsg);
}else{
    $actionArgs[] = $errMsg;
    $validateRule->{$action}(...$actionArgs);
}

## Additional context
无

**Comment by atian25** [comment]
easyswoole 是一个 php 的框架吧？跟 egg 没关系
