### ISSUE TITLE
egg官网无法打开，国内ip

### ISSUE THREAD

**Issue by annasmile2015** [eggjs/egg#4889]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by thonatos** [comment]
https://www.eggjs.org/

这个地址打不开吗？

**Comment by huanlirui** [comment]
中国移动网络，同打不开

**Comment by darrenliuwei** [comment]
> 中国移动网络，同打不开

我把代理关了，重新刷新也可以正常打开，是不是中国移动把这个网站给屏蔽了？

**Comment by mumuHE2002** [comment]
官网打不开：
服务器:  wifi.cmcc
Address:  fe80::10

非权威应答:
名称:    cname.vercel-dns.com
Addresses:  76.76.21.164
          76.76.21.22
Aliases:  www.eggjs.org
