### ISSUE TITLE
请教下关于日志输出的问题

### ISSUE THREAD

**Issue by mexhfl** [eggjs/egg#4892]
egg-logger日志输出可以通过ctx，app，agent调用，但是如果在工具类js中，没有ctx，app，agent情况下，该如何调用？

**Comment by hyj1991** [comment]
如果在工具中使用  egg-logger，可以参考 https://www.npmjs.com/package/egg-mock 这里才生成 mock app context 等

**Comment by atian25** [comment]
一般是把工具类设计为一个 class，初始化的时候，构造函数支持 options.logger。
然后挂到 app 或 ctx 上，或者 customloader 挂到 app.utils 上，可以自动初始化，避免每次使用都要传 logger

**Comment by mexhfl** [comment]
> 如果在工具中使用 egg-logger，可以参考 https://www.npmjs.com/package/egg-mock 这里才生成 mock app context 等

**Comment by mexhfl** [comment]
[](url)

> 如果在工具中使用 egg-logger，可以参考 https://www.npmjs.com/package/egg-mock 这里才生成 mock app context 等

这个方案是否可以在生产环境中使用？

**Comment by mexhfl** [comment]
> 一般是把工具类设计为一个 class，初始化的时候，构造函数支持 options.logger。 然后挂到 app 或 ctx 上，或者 customloader 挂到 app.utils 上，可以自动初始化，避免每次使用都要传 logger

谢谢，这个方案很合理，以后就按这样的方式做工具库
