### ISSUE TITLE
新手关于使用egg-scoket.io的疑问

### ISSUE THREAD

**Issue by nasagps** [eggjs/egg#4896]
使用服务端使用了egg-scoket.io，客户端是否必须使用socket.io.js来进行连接？用js原生的webscoket能连接吗？

**Comment by JasinYip** [comment]
Socket.io 本质上是对原生 WebSocket 进行封装，自己定义了一套关于保活、函数调用标志传递、房间等协议。所以理论上来说你可以用 JS 原生连接，但你要实现 Socket.io 那套协议，这没什么意义。所以是的，你服务端用 Socket.io，客户端也必须使用 Socket.io。
