### ISSUE TITLE
egg 启动的时候添加模块依赖的script命令不生效。

### ISSUE THREAD

**Issue by Qxiaobei** [eggjs/egg#4897]
## 具体问题如下：
egg的启动命令为npm run dev
其执行的是"dev": "egg-bin dev"
当我使用第三方依赖@ffmpeg/ffmpeg的时候，在node版本低于16的时候他的启动命令需要加上如下参数：
--experimental-wasm-threads --experimental-wasm-bulk-memory
于是命令变成"dev": "egg-bin dev -- --experimental-wasm-threads --experimental-wasm-bulk-memory"
但是最终命名并没有在依赖中生效，在我不使用egg框架的时候用上面的命令执行ffmpeg/ffmpeg是没问题的

求问怎么解决？

**Comment by atian25** [comment]
--node-options--xxx

**Comment by Qxiaobei** [comment]
> --node-options--xxx

感谢大佬回复，应该变成这样？egg-bin --node-options=--experimental-wasm-threads --experimental-wasm-bulk-memory

求问在生产环境一样是这样配置嘛？

**Comment by atian25** [comment]
--node-options--experimental-wasm-threads

**Comment by Qxiaobei** [comment]
> --node-options--experimental-wasm-threads

谢谢，下周一上班去公司试试

**Comment by Qxiaobei** [comment]
> --node-options--experimental-wasm-threads

实际测试如下，还是走了一点小弯路，看了源码才知道如果有两个参数要这么用：
egg-bin dev --node-options--experimental-wasm-threads --node-options--experimental-wasm-bulk-memory

如果有两个参数需要加两个options，并且options和参数之间不能有空格。
建议更新下文档吧，找了好多资料好像除了githup这里其他地方没有关于传node参数这方面的说明，会给人造成一点困惑。

**Comment by atian25** [comment]
可以给 egg-bin ，egg-scripts 提个 PR 更新下 README
