### ISSUE TITLE
file 模式多文件上传时请求一直 pending

### ISSUE THREAD

**Issue by henryybai** [eggjs/egg#4910]
## 最小可复现仓库
https://github.com/henryybai/egg-test

## 复现步骤
npm run test

## 相关环境信息
- **操作系统：mac11.6**
- **Node 版本：16.14.2**
- **Egg 版本：2.34.0**

**Comment by shuidian** [comment]
co-busboy升级到1.5.0可以吗？
我这边是升级之后可以了，参考：https://github.com/eggjs/egg/issues/4820

**Comment by henryybai** [comment]
> 

co-busboy 已经是 1.5.0 了，问题没有解决

**Comment by henryybai** [comment]
egg 现在还有维护吗？

**Comment by yysx** [comment]
降低node版本至12.x可以解决

**Comment by henryybai** [comment]
已尝试降低至 12.0.0，问题没有解决
> 降低node版本至12.x可以解决

**Comment by henryybai** [comment]
找到问题了，更新下 busboy 版本即可，https://github.com/cojs/busboy/pull/45

**Comment by vistwang** [comment]
我这边单文件上传也发现问题
现象：第一次可以成功，此时页面不刷新，再上传一次，接口一直 padding

**Comment by atian25** [comment]
https://github.com/eggjs/egg/pull/5034 等这个发布后再试试
