### ISSUE TITLE
"Content-Type": "application/x-www-form-urlencoded" ,获取数据异常

### ISSUE THREAD

**Issue by jiangkaifree** [eggjs/egg#4914]
## What happens?
当使用 axios 指定 `"Content-Type": "application/x-www-form-urlencoded",` 。 `ctx.request.body` 并不能获取到数据, 

1. 当前端使用 `new FormData`  传递该种数据，打印 `{}`
2. 当前端不使用 `new FormData`  使用对象形式， 打印 `{ '{"aa":232}': '' }` 

## 最小可复现仓库
[github demo](https://github.com/2462870727/egg-demo)
## 复现步骤，错误日志以及相关配置

1. 安装依赖 
4. 访问 public 文件夹下 index.html ， `http://localhost:7001/public/index.html`
5. 点击页面请求按钮
6. 查看 controller 文件下 20 行  console 代码。

## 相关环境信息
- **操作系统**：window10
- **Node 版本**：16.14.2
- **Egg 版本**：package.json 中 是 "egg": "^2.15.1",

**Comment by 2462870727** [comment]
你好 ，找到问题了 ， 前端应当使用 下面代码请求， `ctx.request.body` 中能获取到 数据，

```js
axios({
				url: BASEURL,
				method: "post",
				data: `id=121&name=jack`,
				headers: {
					"Content-Type": "application/x-www-form-urlencoded",
				},
			}).then(res => {
				console.log(`axios request`);
				console.log(res.data);
			});
```

不知是我理解错误，还是文档涵盖的不够准确

**Comment by 2462870727** [comment]
当使用 `new FormData()` , 需要在  config.default.js 文件中配置：
```js
 config.multipart = {
		mode: 'file',
	};
```

**Comment by 2462870727** [comment]
#4919

**Comment by atian25** [comment]
标准 HTTP 格式来着
