### ISSUE TITLE
application/json;charset=utf-8 的body非json如何接受参数

### ISSUE THREAD

**Issue by long23333** [eggjs/egg#4915]
## What happens?

post请求，content_type 为 application/json;charset=utf-8 ，但是body内容非json

![image](https://user-images.githubusercontent.com/30925432/160591406-5d334081-c57e-4255-b48a-4328589531ff.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：window11
- **Node 版本**：v8.11.3
- **Egg 版本**： 2.24.0

**Comment by long23333** [comment]
bodyParser 要如何配置才能接收非json的参数呢

**Comment by atian25** [comment]
不是 json 为啥要 application/json
