### ISSUE TITLE
ctx.body 赋值为null后，后面再赋值返回给前端依然失效，中间件拦截也是

### ISSUE THREAD

**Issue by oneplusonecy** [eggjs/egg#4916]
ctx.body 赋值为null后，后面再赋值返回给前端依然失效，中间件拦截也是

ctx.body = null;
ctx.body = "hello world";

api返回的结果依然是null；

**Comment by darrenliuwei** [comment]
一次请求，应该只能返回一次结果给前端吧？

**Comment by atian25** [comment]
提供最小可复现仓库
