### ISSUE TITLE
Exchange recommended link with ant.design

### ISSUE THREAD

**Issue by afc163** [eggjs/egg#492]

**Comment by fengmk2** [comment]
@hi-caicai 来接单

**Comment by popomore** [comment]
Can you write an example using egg with antd in https://github.com/eggjs/examples, we can add it to [tutorials](https://eggjs.org/zh-cn/tutorials/index.html)

**Comment by afc163** [comment]
There is a sample: https://github.com/tvrcgo/egg-react-mobx-ts-antd

**Comment by popomore** [comment]
I don't know how to develop in local environment from this example cc @tvrcgo

**Comment by hi-caicai** [comment]
@afc163 @fengmk2 ok

**Comment by tvrcgo** [comment]
@popomore  some rules for my project:

- Each folder in `front/view/` is an entry corresponding to server side view in `app/view/`. 
- `front/view/<entry>/index.ts` is entry point including react router path rules and handler components ( `front/view/<entry>/<router component>` ) configuration.
- Public components in `front/component/` and libraries in `front/lib/`

It's simple and lightweight.
https://github.com/tvrcgo/egg-react-mobx-ts-antd

**Comment by popomore** [comment]
ping @hi-caicai

**Comment by afc163** [comment]
什么效率....

**Comment by dead-horse** [comment]
下周带刀去找 @hi-caicai

**Comment by hi-caicai** [comment]
反 Ping @popomore 设计稿已经更新

**Comment by atian25** [comment]
https://github.com/eggjs/egg/issues/958 ?

**Comment by okoala** [comment]
我觉得把 Ant 全家桶都加进去吧，反正迟早都要加的  :smile:
