### ISSUE TITLE
Found vulnerabilities

### ISSUE THREAD

**Issue by sm2017** [eggjs/egg#4929]
@atian25 we have some vulnerabilities in fresh eggjs installation

```
found 29 vulnerabilities (10 moderate, 13 high, 6 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by atian25** [comment]
some vulnerabilities are imported from egg-bin cli, only in dev mode. and egg2 is still support 8+, so some dep can't be update.

when egg3 will only support 14+
