### ISSUE TITLE
生产环境mysql账号密码如何存储保密问题

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#493]
![image](https://cloud.githubusercontent.com/assets/1297278/23498692/c3853e96-ff63-11e6-9b95-6f3b8879e220.png)

如果明文存储账号密码的话，那么所有人都知道生产环境mysql的连接方式了，非常不安全。

主要会涉及3部分人：

* 程序员
* 系统管理员
* DBA

最终生产环境的账号密码应该只有DBA知道，请问有方案或思路吗？我们是金融公司，对这方面要求特别严格。

---------------

目前我们Java是用JBOSS容器提供的标准解决方案做的：

1. `DBA`通过`JBOSS jar`包加密字符串给到java程序员
2. java程序员将加密的账号密码放到自己的配置文件里
3. 生产环境JBOSS用加密的jar包进行解密并replace配置文件中的账号密码，`jdbc`直接读取明文账号密码

上述过程只有DBA、jar包、jdbc知道明文的账号密码

**Comment by jtyjty99999** [comment]
有类似密钥服务的平台吗，发布的时候可以写到项目目录里，然后config fs.readfile 然后 require 他即可。

**Comment by popomore** [comment]
这个 jar 包支持加解密，那这个 jar 能拿到么？

你也可以用 jar 加密，在生产环境启动时调用这个 jar 解密动态创建 mysql 实例。

egg-mysql 支持动态创建么 @fengmk2

**Comment by jtyjty99999** [comment]
egg-mysql也是使用Singleton做的，所以支持动态创建吧

**Comment by fengmk2** [comment]
支持动态创建的

**Comment by popomore** [comment]
https://eggjs.org/zh-cn/advanced/plugin.html#动态创建实例

**Comment by johnnychen** [comment]
@popomore 这个jar包是jboss提供的，但只提供加密的jar，解密的算法是封装的jboss内部的，解密后就直接丢给jdbc了，不会经过业务代码处理。

@jtyjty99999 密钥服务平台有的，但仅提供RPC。

@popomore @jtyjty99999  @fengmk2 用egg动态mysql创建，由于解密动作由程序员进行，仍旧有泄露风险。即使调用密钥服务中心，最后代码里仍能拿到明文密码。

达到jboss这种安全级别有点困难。

关于DBA规避具有登陆生产环境的系统运维和开发人员获得生产mysql密码的要求是否过于苛刻？

**Comment by popomore** [comment]
> 关于DBA规避具有登陆生产环境的系统运维和开发人员获得生产mysql密码的要求是否过于苛刻？

这个也是正常要求，不过就算框架实现也能通过代码知道具体的算法，安全就是提高成本，最终还是要看你们自己的方案。可以搞个非对称加密密钥，私钥由运维保管，公钥用来加密你们的密码，部署的时候可以让运维通过一种方式把密钥给拿到解。（开发人员无法拿到）。

以上纯属个人建议。

> 用egg动态mysql创建，由于解密动作由程序员进行

不是程序员进行，是程序进行。密钥是进内存的，除非你自己打到日志里。

ps: 你们支持密钥平台的 RPC 也不是不可以。

**Comment by popomore** [comment]
关了，因为这个和 egg 关系不大。
