### ISSUE TITLE
egg-script 部署参数不生效

### ISSUE THREAD

**Issue by eijil** [eggjs/egg#4936]
## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.  egg-script 参数 `stdout` 和 `stderr` 配置后被没有覆盖

**Expected behavior**
1. 配置路径后日志路径能生效

## Context
- **Node Version**:  16
- **Egg Version**: 2.35.0
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: mac linux

**Comment by atian25** [comment]
提供最小可复现仓库后 reopen
