### ISSUE TITLE
定时任务schedule设置正确的，为什么work执行的时候时间错误呢

### ISSUE THREAD

**Issue by mizhdi** [eggjs/egg#4938]
`schedule: {
    cron: '0 30 07 * * *',
    type: 'worker',
    immediate: false,
  },`

设置时间和日志触发事件都是正确的
<img width="826" alt="image" src="https://user-images.githubusercontent.com/3582887/165074205-6a66eac7-09aa-4999-8e10-9a2eb5f1e706.png">

但是`async task(ctx) => {}` 里的代码执行差8个小时，是哪个时区设置有问题？

**Comment by mizhdi** [comment]
用docker部署的，时区设置和服务器都是正确的，以前都是没问题的，最近好像就升级了一下docker 容器的node版本！

**Comment by atian25** [comment]
process.env.TZ

**Comment by mizhdi** [comment]
> 

好像没有用

**Comment by atian25** [comment]
你要在启动程序的时候指定这个环境变量，而不是在 Node 里面来设置。

这个跟 Node 其实关系不大的，你可以自己写个 Node 在服务器跑下 new Date() 就知道了。

**Comment by mizhdi** [comment]
好的，我再试试！
