### ISSUE TITLE
文档加上版本号

### ISSUE THREAD

**Issue by monkindey** [eggjs/egg#494]
谢谢Egg, 不过我有一点小小的建议就是在文档上可否添加下版本号，因为感觉egg跟egg插件的API有时候变化还挺大的, 导致之前用的是0.9版本去看文档里面的一些配置并不能配置成功。如果注明下版本可能能让开发者少走一些弯路。

可以参考

* https://yarnpkg.com/en/
* https://facebook.github.io/react/
* https://vuejs.org/v2/guide/

**Comment by popomore** [comment]
1.0 即将发布，在 0.x 版本是会稍有变化，现在还不考虑文档做多版本，等到 2.x 可以考虑。

顺便说下 api 文档还未开放，那里是有版本号的 https://eggjs.org/api/

**Comment by atian25** [comment]
@monkindey 抱歉，因为 0.x 是 unstable 的，所以会有一些不兼容变更，现在已经 rc 了，放心。
