### ISSUE TITLE
设置中间件的权重

### ISSUE THREAD

**Issue by tomDogwow** [eggjs/egg#4950]
## Background
想在全局中间件中捕获一些移除 但是在router中写的中间件会先捕获到(2个中间件不是同一个)  

目前可以通过把全局注册的中间件也放到router中 然后手动在router中设置顺序达到效果 但是那样每个接口都要写一遍....

**Comment by atian25** [comment]
没看懂

**Comment by atian25** [comment]
- 全局 middleware 是可以配置 ignore 和 match 的
- 也可以通过 app.router.use(path, mw) 方式来批量挂

**Comment by tomDogwow** [comment]
> 

抱歉我可能没讲清楚，目前遇到的问题是全局的middleware会在  app.router.use(path, mw) 方式挂载的middleware之后运行 ； 但是这个全局的希望是注册到所有router上（这样挂载到全局middleware上肯定最好） 但是设置成全局了之后 middleware会优先执行挂载在router上的 最后才会执行全局的； 疑问就是有没有什么方法可以设置中间件的权重 让全局的放在router之前

**Comment by ruanjiayou** [comment]
> > 
> 
> 抱歉我可能没讲清楚，目前遇到的问题是全局的middleware会在 app.router.use(path, mw) 方式挂载的middleware之后运行 ； 但是这个全局的希望是注册到所有router上（这样挂载到全局middleware上肯定最好） 但是设置成全局了之后 middleware会优先执行挂载在router上的 最后才会执行全局的； 疑问就是有没有什么方法可以设置中间件的权重 让全局的放在router之前

全局中间件在路由之前注册,请求过来时当然是先调用全局中间件.你这个是注册位置在路由后面了吧.
