### ISSUE TITLE
umi转eggjs 前后端同构后,出现Cannot add property 0, object is not extensible

### ISSUE THREAD

**Issue by C0602** [eggjs/egg#4952]
## What happens?

在未同构前，umi项目这段代码可以正常执行，将umi同构成eggjs后无法兼容这段代码
如下是同构后eggjs的代码，此位置无法正常执行
![image](https://user-images.githubusercontent.com/39021307/168535445-9e33c180-26fc-403b-9daf-4bfc80567639.png)
![image](https://user-images.githubusercontent.com/39021307/168535513-a62286ad-1d2d-4194-afa1-378cbfb77cdd.png)
如下是未同构的umi项目代码，此位置正常执行
![image](https://user-images.githubusercontent.com/39021307/168535755-7edc71d7-d0ad-46e9-8812-9fe320aa9323.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- v14.17.0
- **Egg 版本**：
- 2.12.0

**Comment by atian25** [comment]
提供最小可复现仓库，然后找 umi 的同学看看吧

**Comment by C0602** [comment]
这是我最小复现的仓库地址https://github.com/C0602/umi-ssr-demo.git

**Comment by atian25** [comment]
这是前端报错，你应该找 umi 的同学
