### ISSUE TITLE
yarn run dev 或者 npm run dev 无法启动项目

### ISSUE THREAD

**Issue by C0602** [eggjs/egg#4953]
## What happens?

yarn run dev 或者 npm run dev 无法启动项目，删除依赖包重新构建也没有用
![image](https://user-images.githubusercontent.com/39021307/168729989-52a8c578-ce7a-4b0d-9023-a093c65f3df1.png)

## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库
https://github.com/C0602/umi-ssr-demo.git

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by zhangzhaoaaa** [comment]
我试了下Mac下你的demo是可以run起来的，这个异常看起来不是egg的问题，你可以看下umi文档，看下是否能够解决你的问题，https://umijs.org/zh-CN/docs/faq#umi-%E4%B8%8D%E6%98%AF%E5%86%85%E9%83%A8%E6%88%96%E5%A4%96%E9%83%A8%E5%91%BD%E4%BB%A4

**Comment by C0602** [comment]
> 我试了下Mac下你的demo是可以run起来的，这个异常看起来不是egg的问题，你可以看下umi文档，看下是否能够解决你的问题，https://umijs.org/zh-CN/docs/faq#umi-%E4%B8%8D%E6%98%AF%E5%86%85%E9%83%A8%E6%88%96%E5%A4%96%E9%83%A8%E5%91%BD%E4%BB%A4

**Comment by C0602** [comment]
> 

你好，你可以试一下输入一个值后回车，发现会报错，但是同样代码下纯Umi 不会

**Comment by C0602** [comment]
> 我试了下Mac下你的demo是可以run起来的，这个异常看起来不是egg的问题，你可以看下umi文档，看下是否能够解决你的问题，https://umijs.org/zh-CN/docs/faq#umi-%E4%B8%8D%E6%98%AF%E5%86%85%E9%83%A8%E6%88%96%E5%A4%96%E9%83%A8%E5%91%BD%E4%BB%A4

你好，你可以试一下输入一个值后回车，发现会报错，但是同样代码下纯Umi 不会

**Comment by atian25** [comment]
你 yarn 安装后，umi 的 bin 找不到，跟 egg 没关系。
参考 https://www.zhihu.com/question/333901187/answer/744807871 自行排查

**Comment by Charl0tter** [comment]
> 你 yarn 安装后，umi 的 bin 找不到，跟 egg 没关系。 参考 https://www.zhihu.com/question/333901187/answer/744807871 自行排查

在命令行中umi可以执行的啊，我把command换成任何一句命令都提示不是内部或外部命令，也不是可运行的程序，比如‘node -v’

**Comment by byteHulk** [comment]
> > 你 yarn 安装后，umi 的 bin 找不到，跟 egg 没关系。 参考 https://www.zhihu.com/question/333901187/answer/744807871 自行排查
> 
> 在命令行中umi可以执行的啊，我把command换成任何一句命令都提示不是内部或外部命令，也不是可运行的程序，比如‘node -v’

我新的 win 也有这个问题， mac 下没问题

**Comment by byteHulk** [comment]
我看了下, 问题在于 linux 下是 PATH 区分大小写(可以正常运行), windows 下的系统变量是不区分大小写的, 一般是 Path, 但 egg devServer 里面写死了 PATH, 所以会导致 not recognized as an internal or external command 错误, 这个是在预期内的吗

**Comment by atian25** [comment]
egg-view-assets 插件那边？ 可以贴下地址，能直接 PR 最好～

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/issues/5129 已经修复。
