### ISSUE TITLE
windows下的controller文件命名中使用下划线会导致无法加载controller

### ISSUE THREAD

**Issue by hongfu** [eggjs/egg#4954]
## Background
我原来用linux环境没有使用带有下划线的文件命名方式，但今天换到windows开发环境碰到这样的问题，耽误了很久才解决

## Proposal
Win10 环境 + vscode + node16.14.2
我把    baseDir/app/conroller/xcx/ 路径下的文件命名为'"link_code.js"，然后在router.js文件进行路由加载时使用代码

router.post('/xcx/get-link-code-info', controller.api.xcx.link_code.test);

结果无法启动调试
提示controller不存在
后修改文件名为 “linkcode.js”
代码更改为
router.post('/xcx/get-link-code-info', controller.api.xcx.linkcode.test);
启动成功
## Additional context
期望能解决bug，或在文档中清除说明文件命名的要求

**Comment by atian25** [comment]
文档里面一直写的很清楚，会转为驼峰，你 link_code.js 是会被加载为 linkCode 的
