### ISSUE TITLE
[eggjs 3.0版本] eggjs 3.0版本什么时候发布呢

### ISSUE THREAD

**Issue by HZ-ZY** [eggjs/egg#4955]
eggjs 3.0版本什么时候发布呢，坐等。还会有3.0版本不,没有考虑用nestjs了呢

**Comment by atian25** [comment]
看你自己选择即可。

Egg 3.0 是回归初心，做框架的框架，现在在 Artus 那个库实现中。

上层框架也会保留一套，尽量兼容之前的，用户编程界面的语法是 TS 的，就是 https://github.com/eggjs/tegg ，只不过 3 的时候会默认集成，然后底层会完全重写掉，基于 Artus。

现在选什么框架看你自己的团队偏好，如果想选 Egg 系的话，直接基于 tegg 即可。 cnpm/cnpmcore 是一个真实的案例。

**Comment by fengmk2** [comment]
@HZ-ZY 如果 nestjs 更加合适，我建议你直接选择它就多了。
egg 说实在话，它的初始化理解成本比较高，更适合面向应用框架场景切入。
