### ISSUE TITLE
npm init egg --type=simpleJSONResponseFormatError: Unexpected token

### ISSUE THREAD

**Issue by jonnyshao** [eggjs/egg#4963]
<img width="995" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/18613989/171658523-662beb38-331d-4af7-9ee2-288845d7b4ea.png">
<img width="988" alt="WX20220602-225709@2x" src="https://user-images.githubusercontent.com/18613989/171658808-6d471ba8-171a-42a4-96d5-2646bc34b46a.png">

### Node version
> v16.13.0

### Mac os Big Sur
> 11.6.1

有朋友遇到过这个问题吗？连init都失败。看上去像是模板问题

**Comment by jonnyshao** [comment]
egg 还有在维护吗

**Comment by atian25** [comment]
多重试下看看，看报错是 华为云 的 registry 响应出差
