### ISSUE TITLE
不能连接上clickHouse数据库，总是报错

### ISSUE THREAD

**Issue by congYvon** [eggjs/egg#4966]
## 最小可复现仓库
> 请使用 `npm init egg --type=simple bug` 创建，并上传到你的 GitHub 仓库

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **Egg 版本**：

**Comment by hyj1991** [comment]
看看错误信息是否和 egg 相关，如果使用的是非官方维护的 egg-plugin 可以去对应作者的仓库提问

**Comment by hyj1991** [comment]
egg-mysql 也没说支持 clickHouse 吧

**Comment by congYvon** [comment]
现在官方维护的egg-plugin有支持连接clickHouse的吗，还是只能引入第三方的包
