### ISSUE TITLE
react 同构 demo 地址挂了

### ISSUE THREAD

**Issue by xwillmadeit** [eggjs/egg#497]
react 同构文档中 demo 地址挂了，能否帮忙修复一下，需要这个样例～ 感谢！
https://github.com/eggjs/examples/tree/master/react-isomorphic

**Comment by jtyjty99999** [comment]
这个我从来没有提交过吧？你是在哪里看到的这个地址

**Comment by atian25** [comment]
难道是在这看到的?

https://github.com/eggjs/egg/pull/413

这个还是 WIP 状态呢, work in progress

**Comment by xwillmadeit** [comment]
在文档这里呀
https://github.com/eggjs/egg/blob/react/docs/source/zh-cn/tutorials/react.md

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/23537733/2061f01e-0009-11e7-8ee7-42aee1331124.png)

这个是一个还在 WIP 的 branch 上的

**Comment by atian25** [comment]
可以关注下 https://github.com/eggjs/egg/issues/492#issuecomment-283568512
