### ISSUE TITLE
写了一些eggjs的demo降低新手入门难度。

### ISSUE THREAD

**Issue by 532777032** [eggjs/egg#4974]
https://blog.csdn.net/xuelang532777032?type=blog
后续会多更新一些应用场景demo。帮新手朋友少走一些弯路
![image](https://user-images.githubusercontent.com/20221241/176573820-4809882f-7444-4e09-a749-d7c21b22efa7.png)

**Comment by MaledongGit** [comment]
@532777032 : Thanks for your torturials, and you can post it here: https://github.com/eggjs/examples
