### ISSUE TITLE
使用egg-socket.io，客户端有时收不到消息

### ISSUE THREAD

**Issue by fujinting** [eggjs/egg#4975]
## What happens?

只有线上环境存在问题，确定socket没有断开连接，网络一切正常。客户端使用多个不同版本的socket.io-client(均是v2大版本且能与egg-socket.io建立连接，没有任何报错)，在某段时间内只有相同版本的socket.io-client可以收到消息，过一段时间，另一版本的又会收到消息。**若客户端只有一个socket.io-client版本进行连接，这个socket连接也是会在某段时间内(几秒钟到几分钟不等)收不到消息，有时也会收到消息**
使用的是在http请求时 controller层进行客户端消息推送。

## 最小可复现仓库

https://github.com/fujinting/bug-code/tree/main/app

## 复现步骤，错误日志以及相关配置
线上及本地没有任何报错

## 相关环境信息
- **操作系统**：linux centos7.7
- **Node 版本**：14.18.2
- **Egg 版本**：2.35.0
- **Egg-socket.io版本**：4.1.6
- **Socket.io-client版本**：2.1.1

**Comment by fujinting** [comment]
已解决~

**Comment by Feebasylh** [comment]
大佬怎么解决的
