### ISSUE TITLE
【egg-script】 想问下如何过滤stdout.log的日志信息

### ISSUE THREAD

**Issue by RAGGA-TIME** [eggjs/egg#4976]
## 背景
对于process输出的一些无用log信息。如何控制不写入到master-stdout.log中

项目中使用了ffi连接dll动态库。但是动态库有时候会输出很多无用的信息。
我想不让这些内容写入master-stdout.log中。我该怎么实现

或者有没有办法关闭stdout的日志

**Comment by atian25** [comment]
框架层没法判断，你要么把它放到独立进程，要么是它有参数可以定义 process，要么有特定前缀过滤

**Comment by RAGGA-TIME** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RAGGA-TIME** [comment]
> 框架层没法判断，你要么把它放到独立进程，要么是它有参数可以定义 process，要么有特定前缀过滤

那有办法关闭stdout日志嘛？

**Comment by atian25** [comment]
linux 该怎么样就怎么样，`> /dev/null`
