### ISSUE TITLE
请问怎么开启多应用的模式，目录结构是什么样的？

### ISSUE THREAD

**Issue by wtwei** [eggjs/egg#498]
在文档Loader那一章节说的`egg 将应用、框架和插件都称为加载单元（loadUnit）`，我理解的应该是每个应用都是一个加载单元，现在就是不知道怎么开启这个多应用，目录应该怎么划分，还有就是多应用的路由怎么访问的

### 这是我理解的多应用目录结构
![qq 20170303102818](https://cloud.githubusercontent.com/assets/685615/23535888/3ba0d3c0-fffc-11e6-8d97-249853d8e5a4.png)

**Comment by atian25** [comment]
`加载单元` 指的是 `应用`、`框架`和`插件`，而不是多应用。

为什么要多个应用放在一个项目里面呢？你应该在前面用 nginx 来做分发就好了。

**Comment by wtwei** [comment]
@atian25 好的，明白了，谢谢！
