### ISSUE TITLE
报egg-scripts:permission denied

### ISSUE THREAD

**Issue by chunjiu** [eggjs/egg#4984]
ubuntu中部署报没有权限，给了文件权限也不行，这是为啥

**Comment by chunjiu** [comment]
解决了

**Comment by jincheny** [comment]
@chunjiu 请问您是如何解决这个问题的？
我这边mac电脑使用命令行 zip 压缩或者 node-zip 压缩都会产生这个问题。
![image](https://user-images.githubusercontent.com/54785820/183411963-2a17a28b-e41a-4219-95ca-053ca375e0fb.png)

使用鼠标右键压缩就正常，没有这个问题。
![image](https://user-images.githubusercontent.com/54785820/183412099-32392497-512c-414e-a944-8960fe37a5b5.png)

**Comment by chunjiu** [comment]
在生产环境 npm install --production

> @chunjiu 请问您是如何解决这个问题的？ 我这边mac电脑使用命令行 zip 压缩或者 node-zip 压缩都会产生这个问题。 ![image](https://user-images.githubusercontent.com/54785820/183411963-2a17a28b-e41a-4219-95ca-053ca375e0fb.png)
> 
> 使用鼠标右键压缩就正常，没有这个问题。 ![image](https://user-images.githubusercontent.com/54785820/183412099-32392497-512c-414e-a944-8960fe37a5b5.png)

在生产环境npm install --production
另外egg的文档严重过时了，我下次应该不会用这个框架了。
