### ISSUE TITLE
请教如何统计网站文件访问流量？

### ISSUE THREAD

**Issue by star7th** [eggjs/egg#4987]
我目前使用框架内置的egg-static来将 app/public 目录的静态资源文件暴露出来，其中主要是图片文件。现在出于某种需求，我需要统计下图片被外部访问的流量情况。请问在统计流量方面有什么方案推荐吗？
我想的是，如果有个中间件能在egg-static之前对文件路径做前置处理，那我就能统计某个路径的访问次数，从而起一个异步任务把访问次数乘以文件体积粗略得出访问流量了。但是翻了下配置文档，似乎无法配置中间件？那有什么统计流量的方案思路可以推荐吗

**Comment by star7th** [comment]
我找到了方法把某个中间件插入到全局，然后统计。附上自己的结果以便后人查询。另外如果有更好的流量统计方案，望eggjs官方人员可通知我。

附上简单代码。

在app/middleware/下新建statistics.js ，写入
```
module.exports = () => {
  return async function (ctx, next) {
    console.log("请求前执行");
    await next();
    console.log("请求后执行");
    const filePath = ctx.originalUrl;
    console.log("请求的路径是：" + filePath);
  };
};


```

在项目目录下新建app.js，写入代码(如果已经存在则自己追加）
```
module.exports = (app) => {
  // 插入中间件最前面
  app.config.coreMiddleware.unshift("statistics");
};


```

**Comment by huihuicn** [comment]
用中间件是最方便的，可以把统计数据通过rabbitmq这样可以异步统计，方便解耦

**Comment by atian25** [comment]
一般的做法是打访问日志，然后 SLS 采集上去分析即可。
