### ISSUE TITLE
mac电脑使用命令行 zip 压缩或者 node-zip 压缩后生产环境无法执行

### ISSUE THREAD

**Issue by jincheny** [eggjs/egg#4993]
我这边mac电脑使用命令行 zip 压缩或者 node-zip 压缩都会产生这个问题。
![image](https://user-images.githubusercontent.com/54785820/183411963-2a17a28b-e41a-4219-95ca-053ca375e0fb.png)

使用鼠标右键压缩就正常，没有这个问题。
![image](https://user-images.githubusercontent.com/54785820/183412099-32392497-512c-414e-a944-8960fe37a5b5.png)

_Originally posted by @jincheny in https://github.com/eggjs/egg/issues/4984#issuecomment-1208029016_

**Comment by atian25** [comment]
压缩后 bin 下的软链出问题了，这是操作系统问题，自己用 tar 指令吧。
