### ISSUE TITLE
merge config need to support array

### ISSUE THREAD

**Issue by dead-horse** [eggjs/egg#500]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

https://github.com/koajs/bodyparser 有许多配置项是数组，还是要能够支持数组直接覆盖，否则用起来肯定会有不方便。

**Comment by atian25** [comment]
要先讨论下怎么样的覆盖规则：
- 整个数组覆盖
- 针对 index 覆盖
- 不同长度如何覆盖

**Comment by popomore** [comment]
先讨论覆盖还是合并
TZ | 天猪 <notifications@github.com>于2017年3月3日 周五14:31写道：

**Comment by dead-horse** [comment]
直接整个数组覆盖吧，和现在的 string 是统一的

**Comment by popomore** [comment]
那 fork 一个 extend 吧，主要是不兼容很麻烦。
Yiyu He <notifications@github.com>于2017年3月3日 周五14:38写道：

**Comment by fengmk2** [comment]
覆盖 +1，就当作 string 看待。node-extend forked https://github.com/eggjs/node-extend

**Comment by popomore** [comment]
叫 extend2 么

**Comment by ljharb** [comment]
I don't understand, why is node-extend forked?

**Comment by atian25** [comment]
@lihard  the array merge strategy, see https://github.com/eggjs/node-extend/issues/1

**Comment by ljharb** [comment]
It's pretty hard to tell since the diff includes reformatting the entire project.

**Comment by popomore** [comment]
@ljharb you can see the first commit 71b2983e2578b0af272af7f30c3796f9914f1748 that is only changed for reason.

**Comment by ljharb** [comment]
ah, you want arrays overridden instead of merged.

`Object.assign` (natively in the language) does that on its shallow copy, so if you want that behavior, i'd make your own function that wraps `Object.assign`.

**Comment by popomore** [comment]
@ljharb not really, Object.assign will copy all properties to the target object including null and undifined, but extend not. We don't want to override properties if it's null or undefined.

Can you explain how to define the function? It's better for us to define a function resolving the property whether copy or not, or just call another extend recursively.
