### ISSUE TITLE
[curl headers]  key 别强制为小写

### ISSUE THREAD

**Issue by hellobq** [eggjs/egg#5002]
现在从 curl 发送请求携带自定义 headers 里的 key 全部转为小写了，能维持原样吗？谢谢

![image](https://user-images.githubusercontent.com/29953650/187060614-010c360a-14ec-426e-96bd-31f2add7836d.png)

**Comment by atian25** [comment]
看你截图的第一句话。

另外，https://nodejs.org/dist/latest/docs/api/http.html#requestgetheadername Node.js 官方底层 API 就已经转了。

当你需要考虑保持大小写时，大概率你的方案设计有问题，可以再看看。

**Comment by atian25** [comment]
但你截图和标题不是一件事吧， curl 那个是请求，跟 ctx 没关系。如果你要保持，可以用这个参数，https://github.com/node-modules/urllib/pull/344/files

不过还是那句话，当你需要考虑 header 大小写时，建议重新回顾下方案设计是否合理。

**Comment by hellobq** [comment]
恩，谢谢
