### ISSUE TITLE
multipart file模式下接收的file，没有file size！

### ISSUE THREAD

**Issue by pxim** [eggjs/egg#5007]
## What happens?
web端 antd组件：
![image](https://user-images.githubusercontent.com/5111701/187817113-d6aad646-97f4-4e51-815c-48a250c2b6bb.png)

![40a882190b2b1aa9feadee9d1ebee32](https://user-images.githubusercontent.com/5111701/187817032-db3065a7-29a2-44a5-aea5-3ee584a191a3.png)

server端 egg：
![61d0784a4574cb5fdd856bff7de7a1e](https://user-images.githubusercontent.com/5111701/187817229-2539efcd-b7d7-423c-9ca7-8b427247f65f.png)
![ec36b583b282b3734bb31b5dc363302](https://user-images.githubusercontent.com/5111701/187817245-8016c908-97b8-4eea-93a3-5e92a14f2ca2.png)
![image](https://user-images.githubusercontent.com/5111701/187817468-21370ae3-85cc-4285-8dbc-6f6a301256d3.png)

server端接收的file，没有file size，我该如何获取这个 file size

## Mini Showcase Repository(REQUIRED)
> Provide a mini GitHub repository which can reproduce the issue.
> Use `npm init egg --type=simple bug` then upload to your GitHub

## How To Reproduce

**Steps to reproduce the behavior:**
1.
2.

**Expected behavior**
1.
2.

## Context
- **Node Version**:  v16.17.0.
- **Egg Version**: ^2.15.1
- **Plugin Name**:
- **Plugin Version**:
- **Platform**: win10

**Comment by atian25** [comment]
文件路径都有了，你直接 `fs.stat` 啊

**Comment by atian25** [comment]
feel to reopen if any other question
