### ISSUE TITLE
在官方文档中，使用 HttpClient 是否应该提示开发者要记得取捕获错误

### ISSUE THREAD

**Issue by 2681137811** [eggjs/egg#5008]
官方文档内的示例中使用 `const result = await ctx.curl('https://httpbin.org/post')` 去创建 http 请求
文档中好像并没有提示开发者遇到错误会 throw Error ，如果开发者没有捕获错误的话会直接导致后续代码无法执行

**Comment by fengmk2** [comment]
这是网络 io 编程，跟语言无关，不属于 egg 需要去培训的知识。
