### ISSUE TITLE
appInfo.scope 为 undefined 的疑问

### ISSUE THREAD

**Issue by answord** [eggjs/egg#5011]
从这里 https://github.com/eggjs/egg-core/pull/120 看到了 serverScope 的用法，虽然没给出文档，但是从源码的意图看，应该是提供了 appInfo.scope 的访问方式。

但在使用中发现 appInfo.scope 取不到值，一直都是 undefined，从 egg-core/lib/loader/egg_loader.js 源码看：
![image](https://user-images.githubusercontent.com/4627927/188828477-eb05ff5b-b3d7-487f-9aaa-3225bc8547b1.png)

请教一下为什么是先赋值 this.appInfo，再赋值 this.serverScope，这会导致 appInfo.scope  取不到值的

**Comment by atian25** [comment]
这个的用法是，从外部传 ENV：https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js#L137

然后会加载 `config_${scope}_${env}.js`

**Comment by answord** [comment]
EGG_SERVER_SCOPE 有传进来，对应的 config_${scope}_${env}.js 也能顺利加载，但是 appInfo.scope 是undefined。
你可以看看getAppInfo函数的实现，里面用到了 this.serverScope，但是 this.serverScope 是在getAppInfo 后面才会赋值的。

https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js#L173
