### ISSUE TITLE
【求助】定时任务生产环境不执行

### ISSUE THREAD

**Issue by ls57765867** [eggjs/egg#5014]
使用docker-compose启动任务但定时任务不会执行

**Comment by ls57765867** [comment]
小白求助，[#4528](https://github.com/eggjs/egg/issues/4528) 里面的远吗看不懂- -，
这个网站也不能访问更推荐新手开发者通过：https://issue.eggjs.app/ 来提交 Issue。 这个网站进不去
https://cnodejs.org/ 这个网站的检索功能也不好用

**Comment by ls57765867** [comment]
小白求助，https://github.com/eggjs/egg/issues/4528 里面的远吗看不懂- -，
这个网站也不能访问更推荐新手开发者通过：https://issue.eggjs.app/ 来提交 Issue。 这个网站进不去
https://cnodejs.org/ 这个网站的检索功能也不好用...

**Comment by ls57765867** [comment]
小白求助，https://github.com/eggjs/egg/issues/4528 里面的远吗看不懂- -，
这个网站也不能访问更推荐新手开发者通过：https://issue.eggjs.app/ 来提交 Issue。 这个网站进不去
https://cnodejs.org/ 这个网站的检索功能也不好用...

**Comment by ls57765867** [comment]
小白求助，https://github.com/eggjs/egg/issues/4528 里面的远吗看不懂- -，
更推荐新手开发者通过：https://issue.eggjs.app/ 来提交 Issue。 这个网站不能访问
https://cnodejs.org/ 这个网站的检索功能也不好用...

**Comment by ls57765867** [comment]
小白求助，https://github.com/eggjs/egg/issues/4528 里面的远吗看不懂- -，
更推荐新手开发者通过：https://issue.eggjs.app/ 来提交 Issue。 这个网站不能访问
https://cnodejs.org/ 这个网站的检索功能也不好用...实在没办法了😭😭

**Comment by atian25** [comment]
你再怎么急，这样的反馈是没人能帮你的。

就好像你如果吃错东西了，直接一个电话 120 只说了一句『我肚子疼』，那边医生也只能说：『先生，请告诉我你的详细地址和身体相关情况』。

建议：看下 egg-schedule 的源码，或者本地开发环境自己看看 logs 下的 schedule 相关日志，试着去分析下你要的 job 是否被触发，我们的日志已经写的很清楚了，小学英语就够看懂了。

先冷静下，先主动试着分析一些症状，我们才有可能远程问诊。

![image](https://user-images.githubusercontent.com/227713/189773558-3c24f300-6b78-44e4-b925-144a6548bbcb.png)

**Comment by atian25** [comment]
如果分析出进一步的信息，可以 reopen 这个 issue 补充下。 good luck~

**Comment by shilucus** [comment]
> 使用docker-compose启动任务但定时任务不会执行

这个问题解决了么
