### ISSUE TITLE
egg外层的controller中如何调用egg-socket.io方法，比如emit? 

### ISSUE THREAD

**Issue by linweiWork** [eggjs/egg#5015]
egg外层的controller中如何调用egg-socket.io方法，比如emit?

**Comment by atian25** [comment]
试下 https://github.com/eggjs/egg-socket.io/blob/master/app/extend/application.js#L9

**Comment by linweiWork** [comment]
使用app.io.of('nsp').emit()  坑的地方是ts中IO接口缺少of方法，需要额外声明
