### ISSUE TITLE
[Feature Request] 自定义的local env

### ISSUE THREAD

**Issue by LasyIsLazy** [eggjs/egg#5016]
## Background
场景是这样的：

我需要在local环境下模拟两种不同的环境，加载不同的配置，因此只有一个 `local` 的 env 显然不够，于是自定义了一个类似于 `local-B` 的 env。运行起来没有什么问题，但是却失去了 `local` 的一些特性，比如说当文件变更时自动重新build、控制台输出等等。

## Proposal
希望增加一个配置，可以让自定义的 env 表现的和 `local` 一致。

**Comment by atian25** [comment]
你可以在 config.local.js 里面：

```js
if (process.env.XXX === 'AAA') {
  module.exports = require('./xxx.js');
}
```

或者看下 egg-core，用 scope：https://github.com/eggjs/egg/issues/5011

**Comment by LasyIsLazy** [comment]
> 你可以在 config.local.js 里面：
> 
> ```js
> if (process.env.XXX === 'AAA') {
>   module.exports = require('./xxx.js');
> }
> ```
> 
> 或者看下 egg-core，用 scope：#5011


刚刚试了下，scope 可以解决我的问题，十分感谢。

这个功能还是挺有用的，建议放到文档里。
