### ISSUE TITLE
npm run start报错    uv_os_get_passwd returned ENOENT

### ISSUE THREAD

**Issue by linweiWork** [eggjs/egg#5017]
![1663249060005](https://user-images.githubusercontent.com/25841388/190419763-3b41ff77-2840-4d99-bca1-26125aa1b353.jpg)

报错uv_os_get_passwd returned ENOENT

**Comment by atian25** [comment]
跟 egg 没啥关系，自己 google 下类似的错误码看看。有可能是镜像配置问题。

**Comment by linweiWork** [comment]
使用node版本过高导致（v16.10） 切换成v10.+可以了

**Comment by atian25** [comment]
> 使用node版本过高导致（v16.10） 切换成v10.+可以了

不建议降级，要去直面问题和解决问题，你这个应该是 Node 高版本依赖的操作系统问题，从 google 来看应该是依赖缺少，你可以升级下你的 docker 配置啥的。

Node 10.x 版本早已经过了维护期，我们很多插件也开始最小支持 14+ 了。
