### ISSUE TITLE
egg ts版本部署后不能访问Model，导致数据库访问失败

### ISSUE THREAD

**Issue by Shen120** [eggjs/egg#5022]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

1. 写了一个用户模型
2. 在本地开发时service中checkHasAdminUserService方法能够正常使用，输出时能有正常的Model模型
3. 但是部署到stg测试时发现，checkHasAdminUserService中ctx.model.AdminUser为null，导致不能正常访问数据库
### 如图
图1是开发环境的输出，是正常的
![image](https://user-images.githubusercontent.com/33613409/191273801-bad73903-efd5-4263-b7b9-5f33239ffdea.png)
图2是线上stg环境，是错误的
![image](https://user-images.githubusercontent.com/33613409/191274084-1b274ca5-bf43-4bad-a794-435c38d1d657.png)

#### 我是通过CI来部署的，主要部署流程及命令如下：
```
rm -rf node_modules/
npm install
npm run tsc
touch release.tgz
tar --exclude=release.tgz -zcf ./release.tgz .
cp -rf ./release.tgz /www/wwwroot/stg.server.dir/
cd /www/wwwroot/stg.server.dir/
tar -xzf release.tgz
npm run stopstg
rm -rf ./release.tgz .git/ .github/
npm run stg
```

### 可复现问题的仓库地址（Reproduction Repo）

https://github.com/Shen120/egg-prod-bug

### Node 版本号：

v14.17.5

### Eggjs 版本号：

v2.6.1

### 相关插件名称与版本号（PlugIn and Name）：

"egg-sequelize": "^6.0.0",

### 操作平台与版本号（Platform and Version）：

Win10专业版

**Comment by mansonchor** [comment]
https://github.com/Shen120/egg-prod-bug/blob/master/config/config.stg.ts  这个 config 没有被加载，egg 不知道 stg 这个 serverScope

**Comment by Shen120** [comment]
> https://github.com/Shen120/egg-prod-bug/blob/master/config/config.stg.ts 这个 config 没有被加载，egg 不知道 stg 这个 serverScope

我启动时加了env环境变量了呀，还是说有其它的加载方式？求教

**Comment by Shen120** [comment]
找到问题了，数据库配置的baseDir目录不正确导致
![image](https://user-images.githubusercontent.com/33613409/191289133-a03aa147-c72f-4f4d-8944-4d76bbd1f77b.png)
