### ISSUE TITLE
couldn't find the config "eslint-config-egg/typescript" to extend from.

### ISSUE THREAD

**Issue by wjyzhixing** [eggjs/egg#5039]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

![image](https://user-images.githubusercontent.com/36620969/195035554-f331d5d3-d38a-4773-9a6f-9f35e3d5455b.png)
运行npm run lint报错，npm start失败

### 可复现问题的仓库地址（Reproduction Repo）

暂无

### Node 版本号：

v16.14.2

### Eggjs 版本号：

2.6.1

### 相关插件名称与版本号（PlugIn and Name）：

    "egg": "^2.6.1",     "egg-mongoose": "^3.3.1",     "egg-scripts": "^2.6.0"

### 操作平台与版本号（Platform and Version）：

mac

**Comment by atian25** [comment]
eslint 问题自行处理，如果不需要我们的 config 可以自己改对应的 eslintrc
