### ISSUE TITLE
api返回莫名耗时

### ISSUE THREAD

**Issue by linger1216** [eggjs/egg#504]
我写了一个test, 从数据库中查询一条信息, 在service层, 我打印的时间戳, 查询大概耗时5ms左右, 在controller里面就直接返回值赋值this.body返回, 没有任何逻辑.

但奇怪的是, 接口返回时间, 有时候时间特别长, 但不是必现, 大概10几次发生一次.

![wwwwwwwww](https://cloud.githubusercontent.com/assets/1551488/23549487/75b61746-0047-11e7-9323-acb188b8c8a7.png)

大部分是正常..

![wwwwwwwww](https://cloud.githubusercontent.com/assets/1551488/23549431/3e721d2a-0047-11e7-85b1-02b572f51779.png)

我对框架不太熟, 不知道从何入手, 请问碰到这个问题, 应该怎样, 查log, 发现耗时操作.

谢谢.

**Comment by okoala** [comment]
@linger1216  提issue是要有格式要求的，建议多看看，提供有效并且有意义的信息~

**Comment by atian25** [comment]
先排查下你数据库的查询耗时

**Comment by popomore** [comment]
提供可重现代码？
TZ | 天猪 <notifications@github.com>于2017年3月3日 周五20:39写道：

**Comment by atian25** [comment]
mysql 这插件有没有打印时间到 runtime 中？

**Comment by popomore** [comment]
是要自己打的，插件不会主动打
TZ | 天猪 <notifications@github.com>于2017年3月3日 周五21:30写道：

**Comment by atian25** [comment]
curl 包 httpclient 时都有打了，mysql 的 query 等方法可以考虑打下

发自我的 iPhone

**Comment by popomore** [comment]
Instrument 没有内置吧？
TZ | 天猪 <notifications@github.com>于2017年3月3日 周五21:50写道：

**Comment by popomore** [comment]
@linger1216 不知道你是否还有问题，如果没回复，晚上会关闭这个 issue

**Comment by atian25** [comment]
@linger1216 反馈下怎么解决的？

**Comment by linger1216** [comment]
我放弃了, 自己写了自己用的框架, 没有这问题.

**Comment by fengmk2** [comment]
呃，不提供必要的信息，我们想帮忙排查都没办法啊。

**Comment by linger1216** [comment]
@fengmk2 我已经给出我能给的信息了, 我就是因为不知道怎么排查, 才需要一些关键tag提示等, 我给出了
1. service层我打印的时间, 5ms
2. controller层我没有逻辑, 直接返回.
3. 相关的postman截图.

没给出的是egg的version信息...

**Comment by atian25** [comment]
@linger1216 service 的代码贴下看看, 或者把之前的最简化可复现代码上传一份到你的仓库

**Comment by fengmk2** [comment]
将service和controller代码贴一下
