### ISSUE TITLE
请问下微信小程序请求post携带了x-csrf-token，为什么eggjs还是会报 missing csrf token？

### ISSUE THREAD

**Issue by 983796605** [eggjs/egg#5042]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

在请求头header里携带了x-csrf-token
![image](https://user-images.githubusercontent.com/59547510/196659997-64bc0077-a629-49dc-aebe-73f73170219d.png)
还是会报错。

### 可复现问题的仓库地址（Reproduction Repo）

Temporarily no

### Node 版本号：

14.19.1

### Eggjs 版本号：

3

### 相关插件名称与版本号（PlugIn and Name）：

"egg-jwt": "^3.1.7","egg-mysql": "^3.1.1","egg-scripts": "^2","egg-sequelize": "^6.0.0","mysql2": "^2.3.3"

### 操作平台与版本号（Platform and Version）：

Windows 10

**Comment by atian25** [comment]
可以断点对应的代码排查下

**Comment by 983796605** [comment]
> 可以断点对应的代码排查下

请问，您的不会吗？

**Comment by Shen120** [comment]
小程序用不了csrf，这个已经跨域了，同域才使用csrf

**Comment by Shen120** [comment]
小程序用不了csrf，这个已经跨域了，同域才建议使用csrf

**Comment by 983796605** [comment]
> 小程序用不了csrf，这个已经跨域了，同域才建议使用csrf

那就只能关闭csrf了？

**Comment by Shen120** [comment]
> > 小程序用不了csrf，这个已经跨域了，同域才建议使用csrf
> 
> 那就只能关闭csrf了？

我是关了的，用其它方式验证身份

**Comment by 983796605** [comment]
> > > 小程序用不了csrf，这个已经跨域了，同域才建议使用csrf
> > 
> > 
> > 那就只能关闭csrf了？
> 
> 我是关了的，用其它方式验证身份

好的谢谢您

**Comment by atian25** [comment]
csrf 是 跨站请求伪造防护，你小程序是端侧渲染，肯定拿不到 csrf 来上传。
直接用其他验证方式即可。
