### ISSUE TITLE
自定义 Controller 基类  this 拿不到上下文

### ISSUE THREAD

**Issue by dengshicheng1996** [eggjs/egg#5043]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

1. 自定义Controller设置对应的方法
2. 继承自定义Controller 编写业务逻辑
3. this 可以在 路由关联的Controller 中拿到，而而定义的Controller 拿不到this

### 可复现问题的仓库地址（Reproduction Repo）

[auth_platforms_serve.zip](https://github.com/eggjs/egg/files/9835202/auth_platforms_serve.zip)

### Node 版本号：

v16.14.0

### Eggjs 版本号：

2.x. 3.x. 都存在

### 相关插件名称与版本号（PlugIn and Name）：

egg-router-plus: ^2.0.0

### 操作平台与版本号（Platform and Version）：

macos

**Comment by atian25** [comment]
提交到你的 GitHub 仓库，不用上传 zip

**Comment by dengshicheng1996** [comment]
>
