### ISSUE TITLE
service和middleware中的方法在vscode中无法下钻进去，方法类型为any

### ISSUE THREAD

**Issue by bi-kai** [eggjs/egg#5047]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

安装了node模块，服务可以正常启动，功能也正常。
在控制器中访问service方法无法通过.关联出来，并且也无法按ctrl进入相应方法。

![image](https://user-images.githubusercontent.com/15070379/198070892-c44a8a14-5091-490f-b493-d7abf286384f.png)

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

16.13.2

### Eggjs 版本号：

2.33.1

### 相关插件名称与版本号（PlugIn and Name）：

无

### 操作平台与版本号（Platform and Version）：

win10 21H2

**Comment by atian25** [comment]
启动过 egg-bin 生成 d.ts 没

**Comment by bi-kai** [comment]
重装了系统，启动一次后，确实就能关联了，多谢
