### ISSUE TITLE
日志文件名无法是动态的！！！

### ISSUE THREAD

**Issue by ZHENGFANNN** [eggjs/egg#5053]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

<img width="597" alt="image" src="https://user-images.githubusercontent.com/53977416/199039569-55a55b22-e84e-401f-a74b-fe9ae03818d1.png">

日志文件名无法是动态的！！！

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

v16.10.0

### Eggjs 版本号：

3.1.0

### 相关插件名称与版本号（PlugIn and Name）：

3.1.0

### 操作平台与版本号（Platform and Version）：

3.1.0

**Comment by atian25** [comment]
在 JS 语法里面，你的 string template 在定义好后就立即运算为一个固定值了。

**Comment by ZHENGFANNN** [comment]
> 在 JS 里面，你的字符串模板定义好后 JS 就立即为一个固定值了。

好吧，我更希望是一个动态可变，我找一下其他解决方案。
感谢回复！！！

**Comment by atian25** [comment]
其实你要的不就是 logrotator 么，这个自带了

**Comment by ZHENGFANNN** [comment]
> 其实你要的不就是 logrotator 么，这个自带了

是的，有logrotator，但是我更希望：
1、能够按照对应的文件夹存储2022/11/01，认为这样比较方便管理
2、我想自定义输出日志，输出一些有用的日志，如果用egg自带的日志，好像都统一输入到同一个文件了，感觉不太好管理

所以我才自定义日志，但是文件名又不能是按照动态的，如果没办法的话我就尝试用logrotator，看怎么处理

**Comment by atian25** [comment]
1. 你可以看下 egg-logger 和 egg-logrotator 源码，可以扩展的。

2. 有 cutstomLogger 配置可以加 logger 的

**Comment by ZHENGFANNN** [comment]
> 1. 你可以看下 egg-logger 和 egg-logrotator 源码，可以扩展的。
> 2. 有 cutstomLogger 配置可以加 logger 的

那我看下源码，那我看看感谢！！！

**Comment by atian25** [comment]
其实自定义目录结构那个实际生产环境下不一定有必要，能有一定规则区分出来就可以了，然后 sls 采集规则配置下即可
