### ISSUE TITLE
不懂就问

### ISSUE THREAD

**Issue by LiuXIn011** [eggjs/egg#5054]
### 请详细告知你的新点子（Nice Ideas）：

为什么egg的官方文档中没有关于DAO层的描述，而是都将SQL写在的service层

**Comment by cvpv** [comment]
egg只是阿里约定的封装规范，你可以不遵守。阿里没有约定DAO层规范，你可以照搬java里的概念。

**Comment by cvpv** [comment]
无语子，egg的确是不维护了。issues变论坛了属于是，管理员不清吗（262个issues）
