### ISSUE TITLE
一直显示这样，应该怎么改？

### ISSUE THREAD

**Issue by TIANXfafe** [eggjs/egg#5058]
1.在config.default.ts中配置了keys，运行后提示先配置keys，看了run文件夹下的application_config.json发现keys未加载进去。
![image](https://user-images.githubusercontent.com/52117098/201618064-0c1358e3-da80-4788-9dbf-4ab765997ba6.png)
![image](https://user-images.githubusercontent.com/52117098/201618214-535dbc71-48b5-4b06-9475-5243e780702a.png)
![image](https://user-images.githubusercontent.com/52117098/201618475-1004ecdd-53bf-4439-890f-e51e19d47a27.png)
2.nodejs版本 v14.19.3
eggjs版本 2.6.1
系统 ubuntu 20.04

**Comment by atian25** [comment]
请提交最小可复现仓库。

PA: 按过往经验来看，你检查下 config 里面是不是后面有 module.exports 覆盖了

**Comment by TIANXfafe** [comment]
![image](https://user-images.githubusercontent.com/52117098/201620700-1c8944ac-8c8b-4026-a33f-e09192d83325.png)
![image](https://user-images.githubusercontent.com/52117098/201620932-07563f6a-f5f2-4065-9c57-1321f71445bb.png)
config里面没有配置其他环境的，在config.default.ts文件里也没有其他exports

**Comment by atian25** [comment]
请提交最小可复现仓库。

**Comment by TIANXfafe** [comment]
https://github.com/TIANXfafe/problem

**Comment by TIANXfafe** [comment]
直接使用npm init egg --type=ts命令创建一个项目，然后在prod环境运行就会出这个问题

**Comment by atian25** [comment]
ts 的在 prod 场景要先要 tsc 构建啊

**Comment by TIANXfafe** [comment]
好的。谢谢
