### ISSUE TITLE
pkg打包提示 Cannot find module 'nanoid/non-secure' 

### ISSUE THREAD

**Issue by xkkkA** [eggjs/egg#5063]
### Your detail info about the Bug:

使用pkg打包egg程序，始终报错找不到nanoid/non-secure模块，我在package.json里也配置了，但就是找不到。

### Reproduction Repo

11

### Node Version

14.18.2

### Eggjs Version

2.31.0

### Plugin Name and its version

pkg: 5.5.2

### Platform and its version

win10

**Comment by atian25** [comment]
这个跟 egg 关系不大吧，属于 pkg 的使用问题
