### ISSUE TITLE
egg 单元测试，是否可以针对不同的请求域名进行测试

### ISSUE THREAD

**Issue by Topthinking** [eggjs/egg#5067]
### Enter your suggestions in details:

1. 业务会根据host进行逻辑处理
2. 单元测试需要针对该场景进行测试，目前未找到针对此的示例

**Comment by atian25** [comment]
host 其实就是一个 header，你 `app.httpRequest()` 加下参数就可以了，看下 supertest 文档

**Comment by Topthinking** [comment]
![image](https://user-images.githubusercontent.com/13382821/203501073-1a2eb957-dd61-4f75-a7e3-b480ba1dcea0.png)

@atian25 可以了，谢谢

**Comment by atian25** [comment]
PS：你不用手动引入 supertest，直接 `app.httpRequest().get('/')` 即可，可以看下 egg-mock 的文档
