### ISSUE TITLE
Egg数据传输到前端的数据是否可以支持一个自定义加密操作：ctx.body。

### ISSUE THREAD

**Issue by ljj0915** [eggjs/egg#5070]
### 请详细告知你的新点子（Nice Ideas）：

先说下背景：
1.我的项目是Egg+UmiJs，会把前端打包好的js文件引入到ejs模板里面，达到页面的加载效果。
2.因为项目是给外网使用的。想了想希望在后端把返回数据进行加密，前端拿到的就是密文（F12或者爬接口就有一定的保障）。只不过对于程序而言会进行解密操作然后完成数据加载。
3.虽然可以给每个Controller自定义一个加密的操作。但是接口数量多的时候，这个操作就显得繁琐了。
如果能有一个功能支持全局开启配置，让ctx.body这块内容可以自动进行加密就好了。

或者有无大佬们有类似的做法或者建议？

**Comment by ljj0915** [comment]
> 1. 解密也是前端解密的，都是明文逻辑，其实非常容易破解的。
> 2. 看下 Middleware 文档，写个 Middleware 就可以批量操作。

中间件还可以对返回值ctx.body做操作吗？我理解下来中间件都是在运行对应Controller之前执行的诶

**Comment by atian25** [comment]
可以去了解下 koa 的洋葱模型，它的中间件跟 Express 的中间件模型不一样

**Comment by ljj0915** [comment]
谢谢，目前还是用Middleware来完成这个功能。
