### ISSUE TITLE
eggjs npm run start 怎么取消启动日志的输出

### ISSUE THREAD

**Issue by 3338606790** [eggjs/egg#5075]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

npm run start 命令执行， 在云函数里每次冷启动会输出启动日志到日志服务里， 影响日志查找，也浪费存储空间

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

无

### Eggjs 版本号：

无

### 相关插件名称与版本号（PlugIn and Name）：

无

### 操作平台与版本号（Platform and Version）：

无

**Comment by atian25** [comment]
不输出启动日志，如果启动失败了怎么排查问题？

`egg-scripts start -c=1 >/dev/null`，可以看下 egg-scripts 源码。
