### ISSUE TITLE
官网快速开始报错

### ISSUE THREAD

**Issue by xumingjie1658** [eggjs/egg#508]
按照官网中快速开始的逐步搭建，到第一次启动访问就报错了。
Please set config.keys first
这是什么原因？重新试了好几次了

**Comment by xumingjie1658** [comment]
好吧。加入config配置就好了。官网要更新了！！

**Comment by atian25** [comment]
@xumingjie1658 你做到哪一步失败？

Quickstart 里面有
![image](https://cloud.githubusercontent.com/assets/227713/23578769/39af1298-0119-11e7-9d1b-f6c61849e0d2.png)

**Comment by xumingjie1658** [comment]
我知道，但是那是后面了啊。在编写controller的那一节就让我用npm run dev启动了。那个时候还没说要配置config

**Comment by fengmk2** [comment]
@atian25 脚手架自动生成一个随机的 keys 吧

**Comment by xumingjie1658** [comment]
@fengmk2 是的。但是我当时是按照官网上第二种方式逐步搭建操作的

**Comment by fengmk2** [comment]
@xumingjie1658 我们知道你说的是什么问题。。。

**Comment by xumingjie1658** [comment]
@fengmk2 ^_^

**Comment by atian25** [comment]
@xumingjie1658 明天有时间我再看看，那个 keys 我印象中是写 cookie 时才会读的，今天试过是可以的，明天再看看。

@fengmk2 好，可以在 simple 里面加个 scope

**Comment by atian25** [comment]
@xumingjie1658 fixed at https://github.com/eggjs/egg/pull/511

**Comment by aiyadingya** [comment]
我也是这个错误，不过我的原因是我把config目录放在app目录下面，写出了，当给大家提个醒

**Comment by jiufengdadi** [comment]
这个keys是哪里生成的呢？还是说可以任意填写？

**Comment by atian25** [comment]
随便填写一个随机字符串即可，上线后就不要改了。

**Comment by popomore** [comment]
@dead-horse 这个问题加到 faq 吧

**Comment by jiufengdadi** [comment]
@atian25  我随便写了一串，但是始终报错，完全不起作用呢

Error in /
Please set config.keys first

**Comment by ngot** [comment]
请提供代码仓库

**Comment by jiufengdadi** [comment]
[keys配置](https://github.com/jiufengdadi/jiufengdadi.github.io/blob/master/server/config/config.default.js)

**Comment by jiufengdadi** [comment]
@ngot 在吗

**Comment by ngot** [comment]
@jiufengdadi  https://eggjs.org/zh-cn/basics/structure.html  Please read the manual first！

**Comment by jiufengdadi** [comment]
@ngot 好吧，谢谢

**Comment by chennh** [comment]
我也碰上了这个错误，根据官网快速入门搭建起来的项目
egg-ts
  --app
     --controller
         --home.ts
     --service
         --Test.ts
     --router.ts
  --config
     --config.default.ts
     --config.local.ts
     --config.prod.ts
     --plugin.ts

npm run dev 开发环境运行正常访问不报错
npm run start 正式环境运行访问时就报这个错误: Please set config.keys first
config.default.ts中有包含了config.keys = appInfo.name + '_1538214457654_2035'
但是在运行生成的run/application_config.json 中config.keys = "<String len: 0>"

**Comment by atian25** [comment]
你的问题在于没注意到 TS 文档中一句话：正式环境需要 tsc 编译后才运行。

npm start 不支持直接跑 ts

**Comment by chennh** [comment]
@atian25 
我明白了，egg-bin内置了ts-node编译所以开发环境可以正常运行，正式环境要人工编译一次。
我有个小疑问，就是我想把tsc统一编译到dist目录下，避免跟文件同一个位置，那怎么运行egg呢？

**Comment by atian25** [comment]
你 tsc 编译后的目录，就跟 src 没关系，在那个目录单独安装依赖，原来 js 的项目该怎么跑就怎么跑了。

**Comment by lkdghzh** [comment]
> 我也是这个错误，不过我的原因是我把config目录放在app目录下面，写出了，当给大家提个醒

我也是

**Comment by wustzhaohui** [comment]
哈哈哈大家都是遇到一样的问题 ... 把config文件放到了app目录下，不好好看文档的下场

**Comment by lcoder** [comment]
> 我也是这个错误，不过我的原因是我把config目录放在app目录下面，写出了，当给大家提个醒

妈呀，我也疏忽了，不好好看文档
