### ISSUE TITLE
[egg-static]如何配置egg-static，达到不同文件夹的静态资源有不同的缓存策略

### ISSUE THREAD

**Issue by duckduck10** [eggjs/egg#5083]
比如/public/dist文件夹下的资源使用max-age:31536000，public/images下的资源使用max-age:0？

**Comment by atian25** [comment]
1. egg-static 只建议在开发环境或对内的小系统使用，正常的业务最好之间用 cdn 托管静态文件
2. 实在要用，你可以把 images 放到另一个目录，不在 public 下，然后自己 router 对应的路径，手动实例化和挂载这个 static middeware 到 router middleware 上
