### ISSUE TITLE
Egg启动时出现 stream/web 错误

### ISSUE THREAD

**Issue by Mr-huangyh** [eggjs/egg#5084]
(node:19180) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time

**Comment by fengmk2** [comment]
请升级到 noejs 14 最新版本

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/206836078-7e752a52-7ac5-4980-9672-0117ff9cc9c9.png)
