### ISSUE TITLE
如何让egg不进行心跳检查

### ISSUE THREAD

**Issue by imborntowin** [eggjs/egg#5095]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

做了个类似爬虫的工具运行在服务器上
发现在爬取大文件时会出现
`app_worker#2:6892 disconnect, suicide: false, state: disconnected`
然后就重启中断了任务
好像是超时了？
有没有什么解决方案能不让它超时
本地运行时好像没有超时的概念

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

12.18.0

### Eggjs 版本号：

^2

### 相关插件名称与版本号（PlugIn and Name）：

"axios":"^0.27.2"

### 操作平台与版本号（Platform and Version）：

centos7

**Comment by atian25** [comment]
爬虫最好直接跑在 fc 这些函数计算去，不要在 web 服务器里面跑。

心跳是受害者之一，你关了它也无法解决 CPU 耗尽问题。

**Comment by imborntowin** [comment]
可是，只是用请求获取`arraybuffer`然后压缩上传OSS，也会造成CPU耗尽么
我这里的大文件指的是，可能5M以上就不行了
带宽不够，down的时间长了点
没有办法调整心跳时间么
或者说我这个问题应该是阻塞没有发送心跳的问题吧？

**Comment by imborntowin** [comment]
> 爬虫最好直接跑在 fc 这些函数计算去，不要在 web 服务器里面跑。
> 
> 心跳是受害者之一，你关了它也无法解决 CPU 耗尽问题。

大佬带带我

**Comment by atian25** [comment]
> app_worker#2:6892 disconnect, suicide: false, state: disconnected

从这个只能看出是进程挂掉了，至于为什么挂掉不知道，需要你自己检查错误日志之类的。

如果你不是做重 CPU 的操作的话，只是文件上传，那需要检查下 stream 这块的操作，是不是有未处理的异常。

PS： stream 的 pipe 方法是常见的忘记错误处理的地方，尽量换为 pipeline 方法，具体看文档。

**Comment by imborntowin** [comment]
谢谢给的思路
我回头再试试
主要是本地跑的时候是没啥问题的，所以会怀疑是不是心跳的问题

**Comment by atian25** [comment]
病人在 ICU 病房告警快挂了，这时候应该检查身体，而不是怀疑心率监控设备 😂😇🤣
