### ISSUE TITLE
`npm init egg` 如何指定创建 egg 2.x 的模板？

### ISSUE THREAD

**Issue by ks4na** [eggjs/egg#5096]
现在 `npm init egg` 将会默认创建 egg 3.x 的模板，低版本的 node 无法运行，如何创建 2.x 的模板？

**Comment by atian25** [comment]
试试用 egg-init --package=egg-boilerplate-simple@3.4.0 之类的

**Comment by ks4na** [comment]
@atian25 有两个小问题：
1. 代码里面模板下载地址始终会添加 `/latest`，如图;
2.  无法使用 `--package=egg-boilerplate-simple@3.4.0` 这种以 `@` 符号指定版本的形式，得把 `@` 换成 `/`。

<img width="632" alt="截屏2022-12-16 12 37 10" src="https://user-images.githubusercontent.com/28475898/208024065-fb82e855-9e90-45b9-afbd-c8483c9e82f1.png">

**Comment by atian25** [comment]
用 --template 吧，或者提 PR 优化下

**Comment by jokey-boring** [comment]
@ks4na  你解决了吗？我也有这个需求，我试了上面的回答没有什么作用
