### ISSUE TITLE
Node.js 性能平台（alinode）文档优化

### ISSUE THREAD

**Issue by LiuXIn011** [eggjs/egg#5099]
## 这是现有文档

![image](https://user-images.githubusercontent.com/48080203/208053853-45d2b14b-c459-4600-9281-72ce0d178d0d.png)

## 这是阿里云的文档

![image](https://user-images.githubusercontent.com/48080203/208053997-bb23a58b-c07a-4228-8618-4f53edbad7a3.png)
少了server地址配置好像控制台加载不了实例，调试了半天，劳烦修改一下

**Comment by fengmk2** [comment]
欢迎贡献文档优化。
