### ISSUE TITLE
egg-mysql: node 老版本不支持 #pool;

### ISSUE THREAD

**Issue by chiaweilee** [eggjs/egg#5106]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

nodejs 12.12版本 不支持，由于 egg-mysql  引用了最新 ali-rds 引发报错

### 可复现问题的仓库地址（Reproduction Repo）

null

### Node 版本号：

12.12

### Eggjs 版本号：

^2.25.0

### 相关插件名称与版本号（PlugIn and Name）：

egg-mysql@3.3.0

### 操作平台与版本号（Platform and Version）：

mac

**Comment by hyj1991** [comment]
3.x 最低版本要求 `node-v14.x` 了，参见：https://github.com/eggjs/egg/blob/master/package.json#L119

你可以继续使用 2.x
