### ISSUE TITLE
yarn run dev 或者 npm run dev 无法启动项目

### ISSUE THREAD

**Issue by Charl0tter** [eggjs/egg#5129]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

run dev跑不起来，windows11
![image](https://user-images.githubusercontent.com/23480626/212944935-23a65c15-39df-4dc6-a264-7af8614dd11e.png)

### 可复现问题的仓库地址（Reproduction Repo）

https://github.com/eggjs/egg-ant-design-pro.git

### Node 版本号：

16.19.0

### Eggjs 版本号：

4.8.1

### 相关插件名称与版本号（PlugIn and Name）：

egg-view-assets

### 操作平台与版本号（Platform and Version）：

windows 11

**Comment by Charl0tter** [comment]
egg-view-assets/lib/dev_server.js

**Comment by Charl0tter** [comment]
`egg-view-assets/lib/dev_server.js`第四十九行

**Comment by Charl0tter** [comment]
`egg-view-assets/lib/dev_server.js`第四十九行
env.PATH换成Path可以正常运行

**Comment by fengmk2** [comment]
> egg-view-assets

https://github.com/eggjs/egg-view-assets/blob/master/lib/dev_server.js#L49 可以来个 pr 修复

**Comment by BoboCactus** [comment]
> `egg-view-assets/lib/dev_server.js`第四十九行 env.PATH换成Path可以正常运行

@Charl0tter  我也遇到了这个问题。你解决了吗？
我测试了一下，发现：我的项目\config\config.default.js
` config.assets = {
    publicPath: '/public/',
    devServer: {
      debug: true,
      command: 'umi dev',
    },
  };`
  这个配置文件中的 command中无论给什么字符串XXX，都会报
  'XXX' is not recognized as an internal or external command
  
  
  @Charl0tter (*❦ω❦)期待你的回复~

**Comment by byteHulk** [comment]
> is not recognized as an internal or external command



> > egg-view-assets
> 
> https://github.com/eggjs/egg-view-assets/blob/master/lib/dev_server.js#L49 可以来个 pr 修复

我可以试试吗? 目前有两个想法, 一个是直接加一个 || env.Path, 一个是先检查这两个属性, 没有就抛个 PATH environment variable not found 错给用户 @fengmk2
