### ISSUE TITLE
koa2升级计划？

### ISSUE THREAD

**Issue by elover** [eggjs/egg#513]
看到官网中提到的“当 node 的 LTS 版本开始支持 async function 时，egg 核心将会迁移到 koa 2.x”，想了解下，这里的升级时间是指node8发布时候的今年4月份，还是指今年的10月份？

从目前的趋势来讲，generator function用在处理异步的情况，本身就有些hack成分，如果能早日切换到标准的async上，也是一大进步（IDE中调试generator相比调试async会麻烦很多）。

**Comment by popomore** [comment]
LTS 是指 10月份

egg 已经支持了 async function，支持底层未使用 async function 开发，所以未升级到 koa2.

**Comment by atian25** [comment]
@elover 你现在就可以在应用层用 koa2 和 async 的风格写了，至于 egg 内部的实现不用担心，只要你都是 async 的， 后面是无缝升级的。

**Comment by fengmk2** [comment]
V8 对 async await 支持也是靠generator 的，如果它hack 那么aa也是hack。

**Comment by kylezhang** [comment]
@atian25 也就是说现在用`eggjs`开发，可以直接使用`async await`了？

**Comment by atian25** [comment]
一直都可以，从 1.0 版本就可以。

**Comment by ngot** [comment]
https://eggjs.org/zh-cn/tutorials/async-function.html
