### ISSUE TITLE
[Bug] Getting Error while uploading file "Unexpected end of form at Multipart._final"

### ISSUE THREAD

**Issue by MissNanLan** [eggjs/egg#5135]
### 问题描述

- 问题：busboy 抛出 **"Unexpected end of form at Multipart._final"** 错误， 我看了下依赖关系 egg-muitipart ->co-busboy->busboy，点击[issue](https://github.com/mscdex/busboy/issues/296)，根据作者回应

![image](https://user-images.githubusercontent.com/22790863/215312283-c7c1e063-005f-4a84-b300-fa3e8575f658.png)

- 解决办法： 只要将req.pipe 换成 bb.end 即可

- 报错截图： 
![image](https://user-images.githubusercontent.com/22790863/215312356-0baf0566-88bb-4ed9-9c32-69b7ba372704.png)

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

v16.14.2

### Eggjs 版本号：

3.3.3

### 相关插件名称与版本号（PlugIn and Name）：

egg-multipart@^3.1.0    co-busboy "^2.0.0"    busboy "^1.6.0"

### 操作平台与版本号（Platform and Version）：

macOS Monterey 12.3.1

**Comment by fengmk2** [comment]
@MissNanLan 能否提供一下可复现的代码库，这样可以快速修复。

**Comment by MissNanLan** [comment]
@fengmk2  很抱歉，无法复现。我们生产日志的告警，另外又发现

![image](https://user-images.githubusercontent.com/22790863/215320851-193a90f4-f8c8-4a9e-91dc-0e35a03dd675.png)，点击[issue](https://github.com/mscdex/busboy/issues/321)

看上去，是egg的间接依赖busboy导致的问题

**Comment by fengmk2** [comment]
这种是 multipart 上传数据不正确，你的代码应该要做异常捕获处理。

**Comment by WinfredWang** [comment]
### 同样问题

构造一个非法文件http请求（比如，换行符），就会报`Unexpected end of form` 错误，然后worker重启，实例代码如下

```
var http = require('follow-redirects').http;
var fs = require('fs');

var options = {
   'method': 'POST',
   'hostname': '127.0.0.1',
   'port': 7001,
   'path': '/fileupload',
   'headers': {
      'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
   },
};

var req = http.request(options, function (res) {
   var chunks = [];

   res.on("data", function (chunk) {
      chunks.push(chunk);
   });

   res.on("end", function (chunk) {
      var body = Buffer.concat(chunks);
      console.log(body.toString());
   });

   res.on("error", function (error) {
      console.error(error);
   });
});

// http换行符是\r\n，为了构造异常场景，可以去掉\r
var postData = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"files\"; filename=\"test.txt\"\r\nContent-Type: \"text/plain\"\r\n\r\n123456789\n------WebKitFormBoundary7MA4YWxkTrZu0gW--";

req.setHeader('content-type', 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW');

req.write(postData);

req.end();
```

**Comment by fengmk2** [comment]
@WinfredWang 我明天重现一下

**Comment by fengmk2** [comment]
复现成功了，我们会尽快修复。

**Comment by fengmk2** [comment]
https://github.com/cojs/busboy/issues/49

**Comment by fengmk2** [comment]
will close by https://github.com/cojs/busboy/pull/31

**Comment by fengmk2** [comment]
@WinfredWang @MissNanLan 重新安装依赖，已经修复。

**Comment by fengmk2** [comment]
@atian25 stream 超难得一个真实案例。
