### ISSUE TITLE
egg-mysql3.3.0打包报错提示Unexpected tkoen '('

### ISSUE THREAD

**Issue by chulingji** [eggjs/egg#5138]
问题：
egg-mysql多数据源打包出错
错误提示：
node.js SyntaxError:[egg-core] load file:/app/node_modules/egg-mysql/agent.js, error: Unexpected token '('
错误截图：
![d8b79ccba142621ed18d4bf7a19e56d](https://user-images.githubusercontent.com/26785685/216564895-8781dacd-bb39-4cb7-b25b-2f6de019c419.jpg)

egg-mysql版本及依赖树：
![image](https://user-images.githubusercontent.com/26785685/216565043-aa83d2ab-32b6-4b4e-b33c-2ecad32e1c36.png)

**Comment by fengmk2** [comment]
@chulingji node 版本升级到 16+

**Comment by chulingji** [comment]
非常感谢，我受你的启发，把mysql的版本降低到3.0一样解决了问题
