### ISSUE TITLE
使用egg-bin 无法启动调试的问题

### ISSUE THREAD

**Issue by whisperfairy** [eggjs/egg#514]
* **Node Version**:7.6.0
* **Egg Version**:0.9.0
* **Plugin Name**:egg-bin
* **Plugin Version**:
* **Platform**:MAC
* **IDE**:WebStorm2017.1

按照https://github.com/atian25/blog/issues/15 方法进行调试，使用方法A
![image](https://cloud.githubusercontent.com/assets/7280653/23586677/e08f9ae0-01d4-11e7-91dc-a7968a3ac3c7.png)

![image](https://cloud.githubusercontent.com/assets/7280653/23586674/c89e74ec-01d4-11e7-8eea-789516b332cc.png)
能正常进行调试，
使用方法B使用egg-bin dev $NODE_DEBUG_OPTION的方法
仍然无法进行调试
![image](https://cloud.githubusercontent.com/assets/7280653/23586689/4d8ce2f6-01d5-11e7-9450-111264210e54.png)

**Comment by popomore** [comment]
命令行调试的话要加 `egg-bin dev --inspect` 或者直接用 `egg-bin debug`

**Comment by atian25** [comment]
晚点我试试看

**Comment by atian25** [comment]
@whisperfairy 抱歉，之前写错了，是 `"dev": "egg-bin dev -- $NODE_DEBUG_OPTION",`

**Comment by johnnychen** [comment]
是`egg-bin dev $NODE_DEBUG_OPTION` 把？ 中间`--`多余的哦？

**Comment by atian25** [comment]
不是多余的，必须的

**Comment by m31271n** [comment]
@atian25 I'm using egg-bin 3.4.2

```
 ./node_modules/.bin/egg-bin  dev -- --inspect 
⚠️  AssertionError [ERR_ASSERTION]:  <procject_name>/--inspect/package.json should exist
⚠️  Command Error, enable `DEBUG=common-bin` for detail
```
`npm run dev -- --inspect ` is ok. 

`--` is necessary in npm script with argument. But egg-bin's behavior is different from what you describe.

egg-bin is changed  during this time?

**Comment by atian25** [comment]
- `--` means `don't parse, just pass to argv._`.
- `npm run dev -- --inspect` means: `npm you should not parse this argv, just pass to inside script which is egg-bin dev`, so `npm run dev -- --inspect` is equals `egg-bin dev --inspect`

**Comment by m31271n** [comment]
@atian25 So, what johnnychen said is right ?

>  是`egg-bin dev $NODE_DEBUG_OPTION` 把？ 中间`--`多余的哦？

**Comment by m31271n** [comment]
@atian25 Got it. Thanks.

**Comment by assmdx** [comment]
我遇到了相同的错误 https://github.com/assmdx/WaterExquisite_server
