### ISSUE TITLE
按照官网快速入门教程步骤手动创建项目启动报错

### ISSUE THREAD

**Issue by sweet-watermelone** [eggjs/egg#5146]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

按照官网：https://www.eggjs.org/zh-CN/intro/quickstart 快速入门教程的 “初始化项目”、“编写controller”步骤新建好项目之后启动，发现有启动报错信息：（绿色部分的输出是我在egg-bin/scripts/start-cluster.js里面自己打的日志）
![image](https://user-images.githubusercontent.com/31037179/219309327-50e5b785-ef67-4cd1-ab72-21dbe2e6061d.png)

### 可复现问题的仓库地址（Reproduction Repo）

[egg-example.zip](https://github.com/eggjs/egg/files/10753738/egg-example.zip)

### Node 版本号：

v18.14.0

### Eggjs 版本号：

3.15.0

### 相关插件名称与版本号（PlugIn and Name）：

无

### 操作平台与版本号（Platform and Version）：

Windows 11 家庭中文版 22H2

**Comment by fengmk2** [comment]
等 https://github.com/eggjs/egg-bin/pull/223 合并发布之后就可以了。

**Comment by fengmk2** [comment]
重新安装依赖即可
