### ISSUE TITLE
请问下tsconfig中设置了paths，为什么test时提示找不到模块

### ISSUE THREAD

**Issue by waltbest2** [eggjs/egg#5156]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

tsconfig中，我设置了
"baseUrl": ".",
"paths": {
        "@test/infrastructure/*": ["app/lib/infrastructure/*"],
      }

build没问题，为什么执行单元测试时，提示找不到模块呢

egg-bin test -r egg-ts-helper/register

Error: Cannot find module '@test/infrastructure/RdsRepoImpl'

### 可复现问题的仓库地址（Reproduction Repo）

本地代码

### Node 版本号：

14.20

### Eggjs 版本号：

2.34.0

### 相关插件名称与版本号（PlugIn and Name）：

egg-bin": "4.15.0",

### 操作平台与版本号（Platform and Version）：

window 10

**Comment by kaikaibenkai** [comment]
`tsconfig.json` 的 `paths` 不会影响运行时的路径查找，所以运行时导入的路径仍然是 `@test/infrastructure/RdsRepoImpl` 这整个，而不是 `app/lib/infrastructure/RdsRepoImp`

考虑使用 `tsconfig-paths/register`

**Comment by waltbest2** [comment]
> `tsconfig.json` 的 `paths` 不会影响运行时的路径查找，所以运行时导入的路径仍然是 `@test/infrastructure/RdsRepoImpl` 这整个，而不是 `app/lib/infrastructure/RdsRepoImp`
> 
> 考虑使用 `tsconfig-paths/register`

感谢。
试了一下，在test文件开头直接import 'tsconfig-paths/register' 可以解决。
