### ISSUE TITLE
怎么产生访问日志？

### ISSUE THREAD

**Issue by guolianghu** [eggjs/egg#516]
发现logger没有跟access_log有关的东西，都没有这个需求吗？

**Comment by popomore** [comment]
这个使用上差异太大，自己在中间件打个日志就好了

**Comment by fengmk2** [comment]
基本都会前置一个 nginx 反向代理的，默认使用 nginx 的 access log 足够了。

**Comment by atian25** [comment]
可以通过 https://eggjs.org/zh-cn/core/logger.html#自定义日志 配置个 `accessLogger`，然后挂一个 Middleware 按你的业务需求打印下即可，也可以写一个 egg-logger-accesslog 的插件。

**Comment by guolianghu** [comment]
谢谢各位，一般都是按 @fengmk2 的做法，只是一个HTTP服务不默认支持access_log，总觉得有点怪怪的。。

**Comment by fengmk2** [comment]
不是不支持，只是默认没提供这样不被真实使用的中间件而已，你完全可以自行实现这样的中间件。

**Comment by atian25** [comment]
你可以写个插件开源出来，就有了~
我们只是觉得没有内置的必要，又没需求就不写。

发自我的 iPhone
