### ISSUE TITLE
centos egg-alinode undefind

### ISSUE THREAD

**Issue by zhengybo** [eggjs/egg#5167]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

我配置了
![image](https://user-images.githubusercontent.com/22511317/229276123-efa78bec-043e-4483-9668-1345f2dbac1b.png)
![image](https://user-images.githubusercontent.com/22511317/229276174-f89c940d-46df-4a80-98b8-10c6725b4c54.png)
![image](https://user-images.githubusercontent.com/22511317/229276211-e11e2bce-f732-469f-94da-fee612329632.png)

但是 
![image](https://user-images.githubusercontent.com/22511317/229276249-558e8605-4493-4c6d-bfd8-14d47065fe80.png)

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

16.5.0

### Eggjs 版本号：

3.15.0

### 相关插件名称与版本号（PlugIn and Name）：

egg-alinode 2.0.1

### 操作平台与版本号（Platform and Version）：

centos 7

**Comment by zhengybo** [comment]
请问可以反馈一下吗， 我直接用的egg init 的ts模板
![image](https://user-images.githubusercontent.com/22511317/230404703-829d707d-af8c-4839-91d8-3df2800d23b9.png)
这个直接作为例子都不行

**Comment by zhengybo** [comment]
解决了， 文档写的直接安装egg-alinode 就可以了， 结果  自助式部署 runtime 的alinode 还是要安装

**Comment by fengmk2** [comment]
egg-alinode 已经不在维护，建议使用 https://github.com/hyj1991/easy-monitor
