### ISSUE TITLE
对egg 插件有个疑问

### ISSUE THREAD

**Issue by leehomeok** [eggjs/egg#5185]
egg 插件或者中间件 集成在业务项目中时，业务项目已经接了  promethues，egg插件还能接promethues吗？

**Comment by leehomeok** [comment]
> 

@fengmk2   大佬， 我现在用的是egg-prometheus这个插件， 我的意思是，主应用已经配了这个egg-prometheus，
  可以在插件这个项目里面再次配置 这个egg-prometheus么？
  因为插件其实也算是个应用嘛 《一个插件其实就是一个『迷你的应用』》

**Comment by killagu** [comment]
> > 
> 
> @fengmk2 大佬， 我现在用的是egg-prometheus这个插件， 我的意思是，主应用已经配了这个egg-prometheus， 可以在插件这个项目里面再次配置 这个egg-prometheus么？ 因为插件其实也算是个应用嘛 《一个插件其实就是一个『迷你的应用』》

插件配置在应用中，如果插件本身需要开发，依赖的插件配置在 devDependencies 中就可以。插件的 dependencies 中不应该有其他插件。
