### ISSUE TITLE
egg-mongoose 里面的 mongoose 版本太低啦

### ISSUE THREAD

**Issue by user-hope** [eggjs/egg#5190]
### Enter your suggestions in details:

如题, egg-mongoose 里面 mongoose 版本太低啦，能不能升级版本呀； 在 typescript 下面不好用,  没办法使用 @typegoose/typegoose typescript 的插件

**Comment by git9am** [comment]
Any update?

**Comment by WilliamTungInGit** [comment]
> git9am

Not sure, waiting for Eggjs's approval

**Comment by Wai-Dung** [comment]
@user-hope：It's been fixed now and you can have a play with it.
