### ISSUE TITLE
npm run start在centos7下报错，项目无法启动

### ISSUE THREAD

**Issue by lovelyJason** [eggjs/egg#5209]
### bug信息：

1.create-egg创建的项目，本地windows电脑运行正常，npm run dev和npm run start命令都没有异常

2.放到linux centos7服务器下， npm i --production，然后npm run start就一直不让我启动
每个nodejs版本一个大报错也是神奇

nodejs v12.16.0
![image](https://github.com/eggjs/egg/assets/50656459/d5abab3a-a034-4c41-b022-55fa6bc95fa0)

nodejs v15.8.0
![image](https://github.com/eggjs/egg/assets/50656459/53fcfa0f-9268-44b1-a143-2376949d51e9)

nodejs v17.7.0
![image](https://github.com/eggjs/egg/assets/50656459/216dbe91-9ce4-4989-ab8c-fe8279f745d1)

### 可复现问题的仓库地址（Reproduction Repo）

暂无

### Node 版本号：

v10.0到v18.16.0之间的所有版本我大部分全试过了

### Eggjs 版本号：

3.16.0

### 相关插件名称与版本号（PlugIn and Name）：

egg-mongoose， 3.3.1；egg-scripts， 2.17.0

### 操作平台与版本号（Platform and Version）：

centos7

**Comment by fengmk2** [comment]
请使用 node 16/18 最新版本。

**Comment by luxiahongyi** [comment]
我用的v16.19.1可以解决报错：
Cannot find module 'node:events'
