### ISSUE TITLE
egg-logger deprecated EggContextLogger is deprecated, use the EggLogger directly

### ISSUE THREAD

**Issue by lovelyJason** [eggjs/egg#5213]
### Your detail info about the Bug:

这不是egg官方的日志打印示例吗

![image](https://github.com/eggjs/egg/assets/50656459/e4e27fcd-7545-41e9-82a7-c0349fa0ed47)

eggjs中有Context Logger， App Logger， Agent Logger

是这么玩的，没问题啊， 

```javascirpt
ctx.logger.info("收到上层推送", ctx.request.body);
```

为毛报警告？

![image](https://github.com/eggjs/egg/assets/50656459/7a09288d-7be6-431c-a902-c61f9016f27a)

我看天猪说egg3.x发布，换掉了contextLogger

![image](https://github.com/eggjs/egg/assets/50656459/f0067866-d683-4264-8472-8a58d16c2838)

我也试了
```javascript
    this.app.currentContext.logger.info("收到上层推送", ctx.request.body);
```

还是抛警告？ 即将废弃？为毛我不知道

![image](https://github.com/eggjs/egg/assets/50656459/8e32ba33-9082-457d-a183-ccf75ba5ecd9)

### Reproduction Repo

无

### Node Version

v18.12.0

### Eggjs Version

3.16.0

### Plugin Name and its version

无

### Platform and its version

windows10

**Comment by davidchen27** [comment]
@fengmk2 我原本是使用this.logger.info('xxx')  这样的方式, 它能够在日志中打印当前日志产出所在的Controller以及函数名称, 可是如果使用this.app.logger.info('xxx')的话, 它并不会打印这个信息, 请问有其他办法吗😂

**Comment by fengmk2** [comment]
@davidchen27 你使用的 egg 版本是多少？按道理是一样的，ctx.logger 是 app.logger 的别名

**Comment by davidchen27** [comment]
好的, 版本如下:  "3.17.3"
目前我测试了三种logger使用方法:
1. this.ctx.logger
2. this.logger
3. this.app.logger
仅第二种能够自带产出位置的Controller与函数名称

**Comment by davidchen27** [comment]
logger.info('this logger')
ctx.logger.info('ctx logger')
app.logger.info('app logger')

如上三种方式结果如下:

2023-07-31 14:49:33,813 INFO 3420 [controller.home] this logger
2023-07-31 14:49:33,815 INFO 3420 ctx logger
2023-07-31 14:49:33,815 INFO 3420 app logger

**Comment by fengmk2** [comment]
能提供一下可复现的最小 git repo 吗？

**Comment by davidchen27** [comment]
好的, 以下是最小示例代码仓库地址
https://gitee.com/davidchen27/egg-logger-repo

**Comment by fengmk2** [comment]
@davidchen27 定位到问题所在了，https://github.com/eggjs/egg/blob/master/lib/core/base_context_logger.js#L24 我今晚会修复掉

**Comment by davidchen27** [comment]
好的, 辛苦了!
