### ISSUE TITLE
官网挂了 ？

### ISSUE THREAD

**Issue by leehomeok** [eggjs/egg#5220]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

![image](https://github.com/eggjs/egg/assets/13464485/171328e4-61ef-420a-ba13-06bc7741d731)

### 可复现问题的仓库地址（Reproduction Repo）

https://eggjs.org

### Node 版本号：

v14.0.0

### Eggjs 版本号：

3.1

### 相关插件名称与版本号（PlugIn and Name）：

no

### 操作平台与版本号（Platform and Version）：

N/A

**Comment by luxiahongyi** [comment]
加个后缀可以访问：https://www.eggjs.org/zh-CN/intro

**Comment by xuemengfei** [comment]
dumi-theme-egg@1.2.4 已经更新了 @fengmk2 帮忙再部署一下吧 🙏
