### ISSUE TITLE
是否可以在生产环境下取消使用inspector

### ISSUE THREAD

**Issue by dingiyan** [eggjs/egg#5226]
### 问题
egg 3.0，在lib/egg.js文件中引用了inspector模块。我使用vercel的pkg打包整个app为单个可执行文件后，执行将会报错，因为pkg的自定义node二进制文件默认在生产环境中移除了inspector模块。
### 建议
由于大多数情况下不建议在生产环境中使用inspector模块，是否可以在egg生产环境中禁用此模块，伪代码示意：
`
// egg.js第118行
 isCheckHeartbeat:this.config.env !== 'prod' ? require('inspector').url() === undefined || true,

`

**Comment by fengmk2** [comment]
可以来一个 pr 贡献一下。
