### ISSUE TITLE
如何在model里面的hooks获取非匿名的`context`呢？

### ISSUE THREAD

**Issue by syymo** [eggjs/egg#5245]
目前使用的是`egg-sequelize`自动引入的model，但是里面只有一个app，`app.createAnonymousContext()`获取的是匿名的`context`。

想用hook在model里面做一些`creator、opeartor`的记录，但是没找到办法

**Comment by fengmk2** [comment]
可以从 app.ctxStorage 里面获取当前 ctx，甚至直接访问 app.currentContext 就获得了。

**Comment by fengmk2** [comment]
`global[Symbol.for('egg#ctxStorage')]` 可以获取到 als
