### ISSUE TITLE
dump config优化

### ISSUE THREAD

**Issue by dingiyan** [eggjs/egg#5253]
### 请详细告知你的新点子（Nice Ideas）：

1. dump config 可否支持配置控制启用或禁用。（上线稳定后，可以不用dump，避免密码之类信息泄露）
2. 敏感信息值转换时，递归遍历时，建议添加数组遍历。比如sequelize多数据源配置，是一个对象数组，可以遍历每个对象隐藏其密码配置

**Comment by killagu** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L150 这里可以增加需要忽略的 key。
