### ISSUE TITLE
npm i error 

### ISSUE THREAD

**Issue by icebryant** [eggjs/egg#5255]
node version 14.17.2 
npm version 6.14.18
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! egg-bin@6.4.2 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the egg-bin@6.4.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by labixiong** [comment]
I also encountered this error, I upgraded the node version to 16.15.1 and it was able to install

**Comment by Wai-Dung** [comment]
This issue is now with no resp, so I closed it and if any reason, please re-open it for free.
