### ISSUE TITLE
multipart多文件上传

### ISSUE THREAD

**Issue by htt828** [eggjs/egg#5263]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

multipart 多文件上传最多只能上传10个文件吗，可以取消这个限制吗

### 可复现问题的仓库地址（Reproduction Repo）

22

### Node 版本号：

16.18.0

### Eggjs 版本号：

2.15.1

### 相关插件名称与版本号（PlugIn and Name）：

egg-multipart

### 操作平台与版本号（Platform and Version）：

windows 10

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-multipart/blob/master/config/config.default.js#L38 请自行修改。
