### ISSUE TITLE
七牛云拉取文件始终返回404

### ISSUE THREAD

**Issue by A-birdFlyHigner** [eggjs/egg#5266]
### Your detail info about the Bug:

1、在使用qiniu SDK 拉取文件时，始终返回404，考虑异步回调的原因，也加了Promise包裹，但是结果并不如意：
<img width="642" alt="image" src="https://github.com/eggjs/egg/assets/23764742/7280010f-58c7-4e9d-ab6b-528431e2f0d5">

版本信息：
<img width="425" alt="image" src="https://github.com/eggjs/egg/assets/23764742/12903df4-1d95-4fba-abae-b6e9935c5306">

### Reproduction Repo

[bug.zip](https://github.com/eggjs/egg/files/13235150/bug.zip)

始终返回：
<img width="1375" alt="image" src="https://github.com/eggjs/egg/assets/23764742/fdad9c65-fa52-4ef4-b961-6c00e67cf041">

### Node Version

v16.20.2

### Eggjs Version

^3

### Plugin Name and its version

egg-ci,2

### Platform and its version

mac os

**Comment by atian25** [comment]
提交到你的 GitHub 仓库，给在线地址，不要给 ZIP 包。
另外，你的 ZIP 包里面的代码是空的

**Comment by atian25** [comment]
另外，这里好像有一些封装好的：https://npms.io/search?q=qiniu

**Comment by A-birdFlyHigner** [comment]
> 提交到你的 GitHub 仓库，给在线地址，不要给 ZIP 包。 另外，你的 ZIP 包里面的代码是空的

提交了一下

**Comment by A-birdFlyHigner** [comment]
> 另外，这里好像有一些封装好的：https://npms.io/search?q=qiniu

库我试了两个了，都是类似的问题

**Comment by atian25** [comment]
> https://github.com/A-birdFlyHigner/test-egg

你再确认下，真的有么？

![image](https://github.com/eggjs/egg/assets/227713/63f0c666-cd73-4e34-a59a-f829106e4ce8)

**Comment by A-birdFlyHigner** [comment]
> > https://github.com/A-birdFlyHigner/test-egg
> 
> 你再确认下，真的有么？
> 
> ![image](https://user-images.githubusercontent.com/227713/279928709-63f0c666-cd73-4e34-a59a-f829106e4ce8.png)
不好意思，我重新提交了一下

**Comment by atian25** [comment]
要 await 吧。这种查询不可能是同步的。

这个其实跟 egg 没啥关系了，就是 qiniu 的 sdk 是 callback 的，如何包成 promise。

**Comment by A-birdFlyHigner** [comment]
> 要 await 吧。这种查询不可能是同步的。
> 
> 这个其实跟 egg 没啥关系了，就是 qiniu 的 sdk 是 callback 的，如何包成 promise。

看起来是这样的，现在就卡在这里了

**Comment by A-birdFlyHigner** [comment]
> 要 await 吧。这种查询不可能是同步的。
> 
> 这个其实跟 egg 没啥关系了，就是 qiniu 的 sdk 是 callback 的，如何包成 promise。

**Comment by atian25** [comment]
找下 qiniu 那边的人问问，看他们有没有提供 promise 的 api。

从你最顶上的源码截图来看，promise 包装似乎没问题的。你可以试下，不用 egg，直接写个 index.js 里面跑下这段代码，调试通了再放 egg 一点点来。

**Comment by A-birdFlyHigner** [comment]
> 找下 qiniu 那边的人问问，看他们有没有提供 promise 的 api。
> 
> 从你最顶上的源码截图来看，promise 包装似乎没问题的。你可以试下，不用 egg，直接写个 index.js 里面跑下这段代码，调试通了再放 egg 一点点来。

好的，谢谢天猪。
