### ISSUE TITLE
传闻Eggjs不再维护了，是真的吗？

### ISSUE THREAD

**Issue by JarvisQJ** [eggjs/egg#5277]
Egg面世也比较久了，没有人维护，是件恐怖的事。。。

**Comment by fengmk2** [comment]
那里看到的谣言？

**Comment by JarvisQJ** [comment]
我也不清楚源头，但传闻是真的有

**Comment by fengmk2** [comment]
开源项目，从来也没有固定的 egg 团队，不存在解散一说。
谣言止于 commits。

**Comment by atian25** [comment]
eggjs 从诞生之初就是一个虚拟小组，从来没有过一个实体的 EggJS 维护团队和对应的 KPI，初始团队有来自蚂蚁、淘宝、ICBU、UC 等 BU 的相关同学一起共建的。

从 2015 年至今已经快 10 年了，作为一个开源项目，有新人加入，有老人因精力等问题降低投入是正常的行为。

作为一个开源项目的**维护者**，参与开源更多是权利，而不是义务。
作为一个开源项目的**使用者**，在力所能及的情况下，欢迎参与社区贡献。
