### ISSUE TITLE
new version available: 2.3.1 → 3.0.0, not compatible, you must update to use this.

### ISSUE THREAD

**Issue by JUNHAN12138** [eggjs/egg#5278]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

new version available: 2.3.1 → 3.0.0, not compatible, you must update to use this.

### 可复现问题的仓库地址（Reproduction Repo）

https://github.com/eggjs

### Node 版本号：

v20.10.0

### Eggjs 版本号：

项目初始化

### 相关插件名称与版本号（PlugIn and Name）：

无

### 操作平台与版本号（Platform and Version）：

macbook pro

**Comment by JUNHAN12138** [comment]
tnpm装不了3.0.1

**Comment by fengmk2** [comment]
怎样复现的？执行了什么命令？

**Comment by zhoushan1** [comment]
同样出现这个报错，在初始化项目执行npm init egg --type=simple
node版本: v16.20.0

**Comment by yinhaixiang** [comment]
同样出现这个报错，在初始化项目执行npm init egg --type=simple
node版本: v18.17.1

**Comment by fengmk2** [comment]
估计是安装了 egg-init，可以看看版本 egg-init --version

如果是老版本，请先重新安装它，执行 npm i -g egg-init

**Comment by Chef5** [comment]
node v16.20.0
npm初始化，同样报这个错：

``` sh
jj@MBP egg-example % npm init egg --type=simple
[egg-init] use registry: https://registry.npmmirror.com
[egg-init] new version available: 2.3.1 → 3.1.0, not compatible, you must update to use this.
npm ERR! code 1
npm ERR! path /Users/jj/Examples/egg-example
npm ERR! command failed
npm ERR! command sh -c -- create-egg

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jj/.npm/_logs/2024-03-24T11_13_24_507Z-debug-0.log
jj@MBP egg-example % egg-init --version
zsh: command not found: egg-init
jj@MBP egg-example % npm i -g egg-init
```

**Comment by a-painting** [comment]
> 估计是安装了 egg-init，可以看看版本 egg-init --version
> 
> 如果是老版本，请先重新安装它，执行 npm i -g egg-init

没有啊，还是报这个错
