### ISSUE TITLE
v3的文档多会更新，EggLogger 怎么用？？？？？

### ISSUE THREAD

**Issue by hiscc** [eggjs/egg#5281]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

升级了v3，logger 不打印关键信息了。。。。。。提示直接用 EggLogger，而官方文档还是2.0的，到底怎么用？？？？？
文档多会儿能更新下？不会是年底搞波绩效又不管了吧？？
咱这开源企业级框架也是服了。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

`egg-logger deprecated EggContextLogger is deprecated, use the EggLogger directly node_modules/egg/app/extend/context.js:114:19`

### 可复现问题的仓库地址（Reproduction Repo）

*

### Node 版本号：

*

### Eggjs 版本号：

3

### 相关插件名称与版本号（PlugIn and Name）：

*

### 操作平台与版本号（Platform and Version）：

*

**Comment by hiscc** [comment]
日志在logs会生成，但是不在终端显示了

**Comment by hiscc** [comment]
找了半天终于找到了，v3在终端日志级别调高了，文档里也不说。。。。
`
 config.logger = {
    outputJSON: false,
    consoleLevel: 'INFO',
    level: 'DEBUG',
`
直接使用 egg-logger，无效，不知道咋用。。。。全黑盒操作。
`const Logger = require('egg-logger').Logger
const logger = new Logger()
logger.info('userAuth logData: %j')
`

**Comment by hiscc** [comment]
v3后的终端日志和写到log文件中的还不一样，少了请求ip、请求方法、请求路径。。。。。。。。。。。。。。

**Comment by ranwawa** [comment]
现在是25年了，文档上描述的是ctx.logger，运行时却要报警告~

**Comment by yuuk** [comment]
同

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）
