### ISSUE TITLE
side menu scroll position jumps

### ISSUE THREAD

**Issue by afc163** [eggjs/egg#529]
![xx](https://cloud.githubusercontent.com/assets/507615/23655527/4699e88a-0370-11e7-8604-a7919ce417f5.gif)

**Comment by popomore** [comment]
我以为帮我们改了

**Comment by afc163** [comment]
想多了。

**Comment by fengmk2** [comment]
@afc163 求 PR

**Comment by atian25** [comment]
我也以为 @afc163 发了 PR... 想进来感谢下.

跪求 +1
