### ISSUE TITLE
aliyun-egg需要的能力

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#53]
通用安全插件、阿里云各服务插件（oss、cdn、等等常用的） @fishbar 
- [x] egg-oss
- [x] egg-rds -> egg-mysql
- [x] egg-security
- [ ] mts
- [x] ots
- [ ] mc
- [ ] ons

待补充

**Comment by hacke2** [comment]
@atian25 我之前写的例子还用吗。。

**Comment by jtyjty99999** [comment]
+ egg-oss@0.0.2

**Comment by ZhangHarvey** [comment]
ons赶快支持吧，目前node 的sdk是不继续开发了？

**Comment by atian25** [comment]
@hacke2 要的, 不过最好等这个做完了, 基于这个来写.

ping @jtyjty99999

**Comment by jtyjty99999** [comment]
@atian25 什么例子？

**Comment by hacke2** [comment]
内网上写了个blog的showcase @jtyjty99999

**Comment by atian25** [comment]
@hacke2 之前在内网做的一个基于阿里云的 blog 的例子.

我们的 aliyun-egg 还差哪些组件? 啥时能发个框架 0.1.0?

**Comment by jtyjty99999** [comment]
@atian25 博客那个目前的能力正好够跑起来啦， 但是oss的用例是内网的，需要 @fengmk2 改一下，然后就可以release了

**Comment by jtyjty99999** [comment]
@atian25 刚要了个外网的配置，我改一下试试

**Comment by popomore** [comment]
这个继续搞么

**Comment by jtyjty99999** [comment]
@popomore 目前支持了oss/mysql/alinode  用例也跑通，还没有release

**Comment by popomore** [comment]
https://github.com/eggjs/egg-showcase-aliyun-blog

全部做完后，再看下这个例子是否需要优化

**Comment by atian25** [comment]
1. 文档
2. 配套的示例
3. 骨架

**Comment by atian25** [comment]
示例里面的 editor 我觉得太复杂了, 一个简单的 markdown editor 就好了吧?

另外, 不需要引入太多静态资源, 直接用一个外部的 cdn 链接?

**Comment by hacke2** [comment]
@atian25 文档和换 editor 我来搞吧

**Comment by jtyjty99999** [comment]
ots插件也完工，晚上提个pr集成

**Comment by hacke2** [comment]
@jtyjty99999 先提了一个WIP的PR

**Comment by hacke2** [comment]
@jtyjty99999 我这边不太清楚阿里云配置维护的整个流程，这一块你写一下吧？

**Comment by popomore** [comment]
https://github.com/eggjs/egg-ons/pull/1
