### ISSUE TITLE
现在微服务这么流行，有没有考滤做一个senecajs的插件？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#530]
我看egg框架本身没有数据层，是我比较喜欢的架构类型，因为项目到一定规模后，数据层或业务层基本通过RPC来调用，前端只要承担Api路由的功能方可。
在nodejs的世界里有一个叫senecajs的微服务框架，有没有计划做一个基于此的plugin？
https://github.com/senecajs/seneca

**Comment by dead-horse** [comment]
有兴趣可以自己实现一个，我们没有使用场景，不会提供这个框架的 plugin

**Comment by chengnuo** [comment]
支持，撒花。

**Comment by Hlianfa** [comment]
> 支持，撒花。

支持了吗？求问
