### ISSUE TITLE
index.d.ts关于xframe.value的声明中“ALLOW-FROM”有问题

### ISSUE THREAD

**Issue by woaixiangbao** [eggjs/egg#5306]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

如果value的值等于“ALLOW-FROM”是没问题的，不过xframe.value应该设置为“ALLOW-FROM http//:xxx.com”这种形式才对。这里的ALLOW-FROM后面跟任何字符都会被ts判定失败从而报错。

### 可复现问题的仓库地址（Reproduction Repo）

一直都有

### Node 版本号：

最新版

### Eggjs 版本号：

最新版

### 相关插件名称与版本号（PlugIn and Name）：

最新版

### 操作平台与版本号（Platform and Version）：

最新版

**Comment by fengmk2** [comment]
可以来个 pr 修复一下。

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/pull/5336
