### ISSUE TITLE
Better error page on development

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#531]
Like Phoenix error page

![image](https://cloud.githubusercontent.com/assets/156269/23664894/de61540c-0391-11e7-845f-4edda9a2c043.png)

cc @huacnlee

**Comment by atian25** [comment]
cool~

**Comment by yuzukwok** [comment]
可以考虑加https://github.com/ElemeFE/restc   

在网页直接POST请求，分享URL网址（网址中包含请求的全部信息）这样连POST请求也能在对方机器上还原

**Comment by popomore** [comment]
https://restc.faas.ele.me/

**Comment by atian25** [comment]
restc 这个曾经想做到插件去，后面觉得太简单了就没封

**Comment by okoala** [comment]
这个我这边顺手做了，准备提PR~

**Comment by popomore** [comment]
https://github.com/eggjs/egg-onerror/pull/12
