### ISSUE TITLE
eggjs处理服务端请求有超时时间吗

### ISSUE THREAD

**Issue by sunxin18** [eggjs/egg#5321]
### 请详细告知你的新点子（Nice Ideas）：

配置

**Comment by sinkhaha** [comment]
egg服务处理调用方所发请求的超时时间吗，这个没有，可以自己写个中间件处理一下

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L369

通过 serverTimeout 配置可以设置，目前 nodejs http server 是默认不超时的。

**Comment by fengmk2** [comment]
![image](https://github.com/eggjs/egg/assets/156269/2be4fc2d-8ec0-4893-b1ec-e6327aba504a)
https://nodejs.org/docs/latest/api/http.html#serverrequesttimeout
