### ISSUE TITLE
能否将依赖的urllib升级为3.25的系列，而不是现在的2.41.0

### ISSUE THREAD

**Issue by Harvey1976** [eggjs/egg#5326]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

能否将依赖的urllib升级为3.25的系列，而不是现在的2.41.0。
2.41.0的urllib依赖IP包，这个包现在有CVE，但是owner似乎放弃了维护，这引起我们使用了egg的框架的产品有cve的问题。

这个问题也存在于egg-security这个插件中。

### 可复现问题的仓库地址（Reproduction Repo）

能否将依赖的urllib升级为3.25的系列，而不是现在的2.41.0。
2.41.0的urllib依赖IP包，这个包现在有CVE，但是owner似乎放弃了维护，这引起我们使用了egg的框架的产品有cve的问题。

这个问题也存在于egg-security这个插件中。

### Node 版本号：

18.17

### Eggjs 版本号：

3.24.1

### 相关插件名称与版本号（PlugIn and Name）：

egg-security 3.30

### 操作平台与版本号（Platform and Version）：

redhat linux ubi 8

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg/blob/master/config/config.default.js#L306 配置 useHttpClientNext = true 就会默认使用 urllib v3

**Comment by fengmk2** [comment]
https://github.com/node-modules/urllib/pull/512
