### ISSUE TITLE
使用 oxlint 代替 eslint

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#5329]
https://oxc.rs/docs/guide/usage/linter.html

**Comment by fengmk2** [comment]
https://github.com/node-modules/urllib/pull/519

**Comment by fengmk2** [comment]
零规则，只依赖 oxlint 的默认规则。

**Comment by fengmk2** [comment]
我们对 eslint 订正太多，无法使用 oxlint 代替。

**Comment by atian25** [comment]
长痛不如短痛，用 oxlint 然后按它的规则 autofix 不行？

**Comment by fengmk2** [comment]
> 长痛不如短痛，用 oxlint 然后按它的规则 autofix 不行？

oxlint 还有一大堆规则没有支持，而 eslint 出问题随便一搜索都有资料，搜索 oxlint 连关键词都匹配不上。还是不折腾了。
