### ISSUE TITLE
关于egg-rest模块OPTIONS请求

### ISSUE THREAD

**Issue by duncup** [eggjs/egg#534]
浏览器发送put等请求时如果跨域则会发送OPTIONS预请求，目前使用egg-rest的结果是非浏览器环境正常，跨域也可以调通。但OPTIONS请求报404 。目前对egg-rest模块了解还不够。处理不了。
非跨域环境或get请求无异常。

**Comment by jtyjty99999** [comment]
感觉是egg-security插件的问题？

config里配置一下：

  exports.security = {

    /**
     * 禁用methodnoallow，对OPTIONS放行
     */
    methodnoallow: {
      enable: false
    },  
  };

**Comment by duncup** [comment]
我大概看了看egg-rest的代码，似乎没有对OPTIONS做处理。

**Comment by duncup** [comment]
嗯，正准备去试。

**Comment by dead-horse** [comment]
rest 应该没有注册 OPTIONS 的路由，需要自己实现

**Comment by duncup** [comment]
查看结果是和security模块完全无关。。。。。。已经被我关掉了

**Comment by duncup** [comment]
egg-rest项目全局搜索OPTIONS找不到，应该是没处理。

**Comment by dead-horse** [comment]
如果需要的话可以自己加，不属于 egg-rest 的职责范围，而且我们也不太推荐用 egg-rest 来封装，可以参考这篇文档 https://eggjs.org/zh-cn/tutorials/restful.htm

**Comment by duncup** [comment]
@dead-horse 我不太理解你的意思，完全重写一个插件来处理？而且不基于egg-rest封装？那么egg-rest存在的意义是什么？另外链接404了。
实际链接[实现 RESTful API](https://eggjs.org/zh-cn/tutorials/restful.html)
## egg-rest的定义
> RESTful API plugin for Egg.
> Developing RESTful API with egg-rest is very simple. You may read JSON API spec first.
我不是很理解你的意思，是指一个做了路由映射的插件不应该处理跨域时的预请求还是指RESTful API的开发不应该使用这个插件？

**Comment by duncup** [comment]
补充一下，我不是在撕，而是确实对阿里的风格了解不足。至于问题，实际部署是非跨域环境，所以影响并不大。

**Comment by dead-horse** [comment]
跨域你需要的是这个 https://github.com/eggjs/egg-cors ，与 rest 没关系，egg-rest 灵活度不高，真实项目没什么意义。你仔细读一下我之前贴出来的文档吧。

**Comment by duncup** [comment]
@dead-horse 好的，那我明白了。谢～

**Comment by Webjiacheng** [comment]
egg真的不太好用

**Comment by duncup** [comment]
@Webjiacheng 虽然我不是很想问，但是既然你借我的issues这么说我还是要问一下，你觉得哪里不好用？

**Comment by Webjiacheng** [comment]
请问支持微信公众号开发吗？


| |
嘉成备份
邮箱：13539995474@163.com
|

签名由 网易邮箱大师 定制

在2018年01月17日 10:13，duncup 写道：

@Webjiacheng 虽然我不是很想问，但是既然你借我的issues这么说我还是要问一下，你觉得哪里不好用？

**Comment by solarhell** [comment]
神经病 还没用过就开喷了

**Comment by Webjiacheng** [comment]
其他的不多说，你真有礼貌


| |
嘉成备份
邮箱：13539995474@163.com
|

签名由 网易邮箱大师 定制

在2018年01月17日 10:56，jiaxin 写道：

神经病 还没用过就开喷了
