### ISSUE TITLE
eggjs返回的响应头为什么是使用小写？

### ISSUE THREAD

**Issue by ymsh** [eggjs/egg#5343]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

无轮是之前的eggjs项目，还是新创建的项目，请求返回的响应头content-type和content-length都是小写的。标准的响应头不是应该Content-Type和Content-Length这样吗？
<img width="729" alt="header" src="https://github.com/user-attachments/assets/335f385c-8907-4a4e-be8a-d51f498eefcf">

### 可复现问题的仓库地址（Reproduction Repo）

无

### Node 版本号：

v18.0.0

### Eggjs 版本号：

3.17.5

### 相关插件名称与版本号（PlugIn and Name）：

与插件无关

### 操作平台与版本号（Platform and Version）：

MacBook Pro  13.6.3

**Comment by fengmk2** [comment]
http 标准是不区分大小写的。

**Comment by ymsh** [comment]
> http 标准是不区分大小写的。

但我的项目要求响应头必须类似Content-Length这样的大小写风格，框架没有提供可自定义的入口，因些无法满足项目需求。
虽然通过Nginx可以转换。但项目是直接访问的，没有通过Nginx层

**Comment by ymsh** [comment]
通过后置中间件方式，可以重定义Content-Type，但 Content-Length重定义却无效，不明白为什么？
请大佬指教

**Comment by killagu** [comment]
> 通过后置中间件方式，可以重定义Content-Type，但 Content-Length重定义却无效，不明白为什么？ 请大佬指教

https://github.com/koajs/koa/blob/master/lib/application.js#L314 看看是不是这里覆盖了。
