### ISSUE TITLE
为什么在服务启动命令中添加参数在服务生命周期中获取不到？

### ISSUE THREAD

**Issue by zhangvj** [eggjs/egg#5346]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

1. 我做了什么    

- 启动参数添加一些自定义参数（"dev": "egg-bin dev -- --load=test"）

2. 我的预期

- 在app.js的生命周期中或者config.local.js中能够拿到这个参数

3. 我实际得到的

- 没有拿到这个自定义参数
- **在app.js中分别将启动命令参数打印出来，发现app.js中完全获取不到。config.local.js内部的逻辑执行了4次，而且只有第一次获取到正确的启动命令，后面的都不对，这是为什么？**

<img width="540" alt="image" src="https://github.com/user-attachments/assets/f5c21b23-aac3-4b3d-af52-d691523ee2ba">
<img width="649" alt="image" src="https://github.com/user-attachments/assets/36289935-9d43-43d0-af36-db8d8abf748a">
<img width="1074" alt="image" src="https://github.com/user-attachments/assets/72224a0f-ed63-45c4-9640-32876f0b9cf5">

### 可复现问题的仓库地址（Reproduction Repo）

[bug.zip](https://github.com/user-attachments/files/16264551/bug.zip)

### Node 版本号：

v20.10.0

### Eggjs 版本号：

3.27.1

### 相关插件名称与版本号（PlugIn and Name）：

 "devDependencies": {     "egg-bin": "6",     "egg-mock": "5",     "eslint": "8",     "eslint-config-egg": "13"   },

### 操作平台与版本号（Platform and Version）：

macOS 14.5 (23F79)

**Comment by killagu** [comment]
建议用环境变量，node 的启动参数没有从 master 进程传给 worker 进程。

**Comment by zhangvj** [comment]
> 建议用环境变量，node 的启动参数没有从 master 进程传给 worker 进程。

感谢回复，已经使用环境变量解决我的需求了
