### ISSUE TITLE
对于eggjs处理的咨询

### ISSUE THREAD

**Issue by sunxin18** [eggjs/egg#5350]
- 背景
对于处理请求成功率要求比较高

- 问题
1. eggjs对于并发请求如何处理，是有请求队列吗，请求队列的大小上限以及等待上限是多久呢
2. eggjs对于已处理的请求，处理的时间时间上限是多久呢
3. 对于有丢弃的情况，有没有日志 or metrics监控

**Comment by killagu** [comment]
egg 的 HTTP 处理就是 Node.js 的 HTTP 机制，是基于事件循环，没有队列。

没有默认的超时中间件。
