### ISSUE TITLE
egg-schedule启动失败

### ISSUE THREAD

**Issue by yqwertb** [eggjs/egg#5352]
### 在此输入你需要反馈的 Bug 具体信息（Bug in Detail）：

**任务代码**
已经确保插件开启，在plugin.js和config.default.js都已经设置
![image](https://github.com/user-attachments/assets/6c924943-331d-4ec4-a998-6f14f989c74c)

**报错信息**
![image](https://github.com/user-attachments/assets/53e9627f-1ba6-49bc-a691-fe883016be8d)

**报错定位到的插件代码**
![image](https://github.com/user-attachments/assets/2f5e5c4c-0469-4bd3-81dc-9a242639c5c4)

### 可复现问题的仓库地址（Reproduction Repo）

![image](https://github.com/user-attachments/assets/6c924943-331d-4ec4-a998-6f14f989c74c)

### Node 版本号：

16.20.0

### Eggjs 版本号：

2.15.1

### 相关插件名称与版本号（PlugIn and Name）：

egg-schedule  4.0.1

### 操作平台与版本号（Platform and Version）：

win11

**Comment by killagu** [comment]
把 egg 升级到最新版本 3.27.1 可以解决。
