### ISSUE TITLE
关于 extend 的疑问

### ISSUE THREAD

**Issue by hsxiaoma** [eggjs/egg#536]
目前我们是允许 extend 机制的，就目前而言，是指定的几个固定名称的 js ， 如果是其他名称的 js 如：`demoExtend.js` 能否顺利的加载？

我在写应用时， 在 extend/filter.js 这个可用于模板方法注入， 这个是否是在 egg-view-nunjucks 挂载的？

**Comment by atian25** [comment]
嗯， 我们的 [Loader API](https://eggjs.org/zh-cn/advanced/loader.html) 提供了定制化能力。

如 egg-sequelize 对 `app/model` 的扩展，如 egg-view-nunjucks 对 `app/filter` 的扩展

实现起来很简单，参见示例： https://github.com/eggjs/egg-view-nunjucks/blob/master/lib/environment.js#L55

**Comment by gxcsoccer** [comment]
其他名字 `demoExtend.js` 默认不行，但是可以自定义 loader

**Comment by hsxiaoma** [comment]
OK, 知道了.
