### ISSUE TITLE
egg-mongoose动态连接其它mongo数据库

### ISSUE THREAD

**Issue by daoshenjay** [eggjs/egg#5360]
### 请详细告知你的新点子（Nice Ideas）：

我在配置文件中配置了默认使用的mongo数据库A，但是同时，因业务需要，我想在业务逻辑中动态去连接其他mongo数据库B，请问现在可以实现这个需求吗？
数据库A和数据库B中存在同名的表格，比如都有User表，在获取数据时是否会有冲突？

我做过的尝试：
我在代码中做了如下尝试，可以连接数据库B成功，但是不知道怎么获取数据
const db = mongoose.createConnection(urlB, options)
db.on('connected', async () => {
  db.model.User.fineOne() // 这种方式不行
})

**Comment by svenjia** [comment]
不是可以配置多个clients么？
