### ISSUE TITLE
请问用egg-multipart上传文件，最大只能上传60多KB，怎么设置最大值

### ISSUE THREAD

**Issue by DarksKnight** [eggjs/egg#537]
![image](https://cloud.githubusercontent.com/assets/10780467/23734961/a8c673b8-04bd-11e7-8864-a3e97c0cea8a.png)
请问怎么设置。。

**Comment by atian25** [comment]
https://github.com/eggjs/egg-multipart/blob/master/config/config.default.js

**Comment by atian25** [comment]
@gxcsoccer 这个库得补充下文档，还有英文注释？

**Comment by DarksKnight** [comment]
![image](https://cloud.githubusercontent.com/assets/10780467/23735683/1631b878-04c2-11e7-9942-dcc2ddc96377.png)
我实际这么写。但是上传的大小，原本200多KB。。实际还是
![image](https://cloud.githubusercontent.com/assets/10780467/23735700/31a2ebe0-04c2-11e7-87bf-eca96d44a0d9.png)
这是为什么。。。

**Comment by gxcsoccer** [comment]
@DarksKnight 你看下上传的文件实际大小，而不是看 FileStream 的 ReadableState

**Comment by DarksKnight** [comment]
我实际上传了一张288KB的图片，但是服务器只接受到了60多KB的内容。。。 @gxcsoccer

**Comment by gxcsoccer** [comment]
我自己测试下

**Comment by DarksKnight** [comment]
我的nodejs版本是6.10.0，7.X也试过，也是一样的 @gxcsoccer

**Comment by gxcsoccer** [comment]
我本地测试是 ok 的，上传了1.7m 的图片

app/controller/home.js
```js
'use strict';

const fs = require('fs');
const path = require('path');
const sendToWormhole = require('stream-wormhole');

module.exports = app => {
  class HomeController extends app.Controller {

    * index() {
      yield this.ctx.render('index.html');
    }

    * upload() {
      const parts = this.ctx.multipart();
      let part;
      while ((part = yield parts) != null) {
        if (Array.isArray(part)) {
          continue;
        } else {
          break;
        }
      }

      if (!part || !part.filename) {
        this.ctx.body = {
          message: 'no file',
        };
        return;
      }
      const filepath = path.join(__dirname, '../../upload', part.filename);
      yield saveStream(part, filepath);
      this.ctx.body = {
        filename: part.filename,
      };
    }
  }
  return HomeController;
};

function saveStream(stream, filepath) {
  return new Promise((resolve, reject) => {
    const ws = fs.createWriteStream(filepath);
    stream.pipe(ws);
    ws.on('error', reject);
    ws.on('finish', resolve);
  });
}
```

app/router.js
```js
'use strict';

module.exports = app => {
  app.get('/', 'home.index');
  app.post('/upload', 'home.upload');
};
```

**Comment by gxcsoccer** [comment]
@DarksKnight 你检查下你的代码，或者帖一下你的代码

**Comment by gxcsoccer** [comment]
![image](https://cloud.githubusercontent.com/assets/1207064/23738121/1d0066ee-04d2-11e7-9c15-01f39c95a75a.png)

**Comment by gxcsoccer** [comment]
@atian25 这个放到 example 里吧，或者 egg-init 里面加一个这个 boilerplate

**Comment by atian25** [comment]
@gxcsoccer https://github.com/eggjs/examples/tree/master/multipart 这个有了吧

**Comment by DarksKnight** [comment]
可以了，谢谢了。 @gxcsoccer

**Comment by atian25** [comment]
@DarksKnight  你之前漏了啥?

**Comment by DarksKnight** [comment]
之前应该是不知道怎么合并stream。。。应该是接受到全部的数据，只是不知道怎么保存。

**Comment by jamesliauw** [comment]
https://github.com/eggjs/examples/tree/master/multipart 
这个示例，支持多文件上传吗？
设置了
<p>Image: <input type="file" multiple="multiple" name="image" /></p>
不生效
