### ISSUE TITLE
这是什么原因？

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#538]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev shopManage@1.0.0
6 info dev shopManage@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info shopManage@1.0.0 Failed to exec dev script
9 verbose stack Error: shopManage@1.0.0 dev: `egg-bin dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid shopManage@1.0.0
11 verbose cwd F:\egg\egg-example
12 error Windows_NT 6.1.7601
13 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.4.7
15 error npm  v2.15.8
16 error code ELIFECYCLE
17 error shopManage@1.0.0 dev: `egg-bin dev`
17 error Exit status 1
18 error Failed at the shopManage@1.0.0 dev script 'egg-bin dev'.
18 error This is most likely a problem with the shopManage package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     egg-bin dev
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs shopManage
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls shopManage
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by atian25** [comment]
> 2 info using npm@2.15.8
> 3 info using node@v4.4.7

egg 现在只支持 6.x +

**Comment by gxcsoccer** [comment]
问题描述清楚点 @a526672351

**Comment by dead-horse** [comment]
先关了，升级 node 如果不行请贴出详细的错误信息

**Comment by a526672351** [comment]
版本问题，上面atian25 已经回答
