### ISSUE TITLE
打包部署时 报错了 请问是什么原因呢？

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#541]
[root@iZbp12o440hd7lm0u6oobtZ common]# npm install --prod

> hiredis@0.5.0 install /web/node/common/node_modules/hiredis
> node-gyp rebuild

make: Entering directory `/web/node/common/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis-c/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis-c.a
  COPY Release/hiredis-c.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory `/web/node/common/node_modules/hiredis/build'
shop@1.0.0 /web/node/common
└─┬ koa-redis@2.1.3
  └─┬ hiredis@0.5.0 
    ├── bindings@1.2.1 
    └── nan@2.5.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by sunshinexb** [comment]
并没有生成release.tgz

**Comment by atian25** [comment]
是你自己安装的第三方原生依赖库有问题吧

发自我的 iPhone

**Comment by atian25** [comment]
上面写了，`hiredis` 安装失败。这个跟 egg 没关系，属于 window 上 Node.js 原生插件的兼容性问题，看下node-gyp 官网的 README 文档说明看看能否解决。

**Comment by popomore** [comment]
egg 有 redis 插件 https://github.com/eggjs/egg-redis
