### ISSUE TITLE
egg-view-react 这个插件什么时候能有更新呀

### ISSUE THREAD

**Issue by xwillmadeit** [eggjs/egg#543]
egg-view-react 这个插件什么时候能有更新呀? 极其需要有一个服务端渲染 react 的例子...

**Comment by popomore** [comment]
恩，这个还在开发中 

ping @jtyjty99999

**Comment by jtyjty99999** [comment]
ok，这个优先级提高

**Comment by xwillmadeit** [comment]
感谢啊@。@

**Comment by monkindey** [comment]
@jtyjty99999  可以提供下egg-view-react的开发计划么?

**Comment by dead-horse** [comment]
合并到 https://github.com/eggjs/egg/issues/328

**Comment by jtyjty99999** [comment]
下周完成，可以在https://github.com/eggjs/egg-view-react/pull/2 跟进
