### ISSUE TITLE
node 7.7.2 can not get mysql db

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#544]
node = 7.7.2
use egg.js egg-mysql
use * yield no problem
but use async await can not get db data

**Comment by popomore** [comment]
Which method do you invoke? can you give some code and error stack?

**Comment by grubed** [comment]
module.exports = app => {
  return class db extends app.Service {
    * find() {
      const data= yield app.mysql.get('db');
      return data;
    }
  }
};
table name is db
log has data
when i modify : 
module.exports = app => {
  return class db extends app.Service {
    async find() {
      // 假如 我们拿到用户 id 从数据库获取用户详细信息
      const data= await app.mysql.get('db');
      return data;
    }
  }
};
no data

**Comment by popomore** [comment]
it seems ali-rds don't support promise @fengmk2

**Comment by popomore** [comment]
Should we wrap pormise in egg-mysql?

**Comment by dead-horse** [comment]
@grubed https://eggjs.org/zh-cn/tutorials/async-function.html#调用-generator-function-api

看文档自行用 co 将 mysql 提供的方法包装成 promise 吧。现阶段这些插件不一定会改造成 async function 形式的。

**Comment by grubed** [comment]
thank you everyone
use co.wrap Perfect solution
