### ISSUE TITLE
在app.js中如何调用controller方法

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#548]
* **Node Version**: 7.7.2
* **Egg Version**: 1.0.0-rc.2

`
在app.js中可以
const ctx = app.createAnonymousContext();
ctx.service.device.pass()
调用service中的方法，
ctx.controller.device.pass()
调用不到controller方法
`

**Comment by dead-horse** [comment]
什么场景需要调用到 controller 上的代码？

**Comment by TDiDa** [comment]
@dead-horse 我在app.js中启动一个TCP客户端接收传输数据，egg本身建立一个websocket服务器，websocket通过这个TCP与第三方的TCP服务器通讯。新人入手，不知道如何构建，或许应该把方法写在service，从而调用service吧

**Comment by ngot** [comment]
controller是设计给请求处理使用的，请求纬度。app.js是在应用启动时执行一些初始化工作的。

两个东西，没什么交集，不搭边。

**Comment by ngot** [comment]
@TDiDa 你看看 egg-socket.io 符不符合需求

**Comment by TDiDa** [comment]
@ngot 我是用net建立的TCP客户端，egg-socket.io 可以当TCP客户端吗？
