### ISSUE TITLE
egg-mongoose 普通库dbowner权限，连接的时候报错not authorized on xxx to execute command { serverStatus: 1 }

### ISSUE THREAD

**Issue by nalantianyi** [eggjs/egg#550]
@huacnlee 
egg团队你们好，环境信息如下
mongodb版本2.6 
账户权限dbOwner
连接url   mongodb://xxx:xxx@yyyy/xx
**使用egg-mongoose连接报错not authorized on xxx to execute command { serverStatus: 1 }**

**使用原生mongodb驱动或者mongoose均正常**

连接日志：**先显示连接成功，后执行失败**
egg-agent.log中：
2017-03-10 22:38:28,417 INFO 98529 [egg-mongoose] mongodb://xxx:xxx@yyyy/xx  connected successfully
common-error.log中：
2017-03-10 22:38:28,453 ERROR 98529 nodejs.MongoError: not authorized on veleco to execute command { serverStatus: 1 }

查阅egg-mongoose代码发现如下代码
  app.beforeStart(function* () {
    app.coreLogger.info('[egg-mongoose] starting...');
    yield heartEvent.await('connected');
  /*  const serverStatus = yield db.db.command({
      serverStatus: 1,
    });
assert(serverStatus.ok === 1, '[egg-mongoose] server status is not ok, please check mongodb service!');
    */
    app.coreLogger.info('[egg-mongoose] start successfully and server status is ok');
**_注释掉命令serverStatus: 1后能正常连接和操作_**
**账户权限dbOwner时失败，改成admin后成功！！所以猜测dbowner用户并没有db.serverStatus()权限，望egg查阅下，因为对这块东西不是特别熟悉，如果是我配置数据库等问题导致的，还望指点**

**Comment by nalantianyi** [comment]
@huacnlee @atian25 帮忙看下。多谢

**Comment by popomore** [comment]
这个好像 @jtyjty99999 在处理

**Comment by jtyjty99999** [comment]
心跳的问题，@popomore 我没找到不带权限的心跳，能先去掉吗

**Comment by atian25** [comment]
做个开关？

**Comment by atian25** [comment]
上次那个 PR 也是为了解决权限问题吧？

**Comment by popomore** [comment]
暂时去掉吧
TZ | 天猪 <notifications@github.com>于2017年3月10日 周五23:49写道：

**Comment by nalantianyi** [comment]
@popomore @atian25 @jtyjty99999 我看到https://github.com/fzaninotto/uptime/pull/288里面也是这个问题

**Comment by jtyjty99999** [comment]
@atian 来pr吧？我在火车上。。 我后来yield了connect事件，理论上我觉得触发了connect事件就可以保证连接上了

**Comment by atian25** [comment]
没带电脑回来。。。

发自我的 iPhone

**Comment by jtyjty99999** [comment]
那我明早解决哈 @nalantianyi

**Comment by nalantianyi** [comment]
@jtyjty99999 辛苦你了。也让我学到了很多

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-mongoose/pull/4

试试 egg-mongoose 的最新版本（1.1.1）
