### ISSUE TITLE
怎么在一个service 里面调用另一个service？

### ISSUE THREAD

**Issue by miaosun009** [eggjs/egg#554]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

请问
怎么在一个service 里面调用另一个service？

**Comment by gxcsoccer** [comment]
```js
this.ctx.service.xxxSerivce.yyyMethod(...)
```

**Comment by johnnychen** [comment]
![image](https://cloud.githubusercontent.com/assets/1297278/23823639/99bf87a2-06a1-11e7-9a01-47b83febb033.png)

可以先看文档哈~
https://eggjs.org/zh-cn/basics/service.html
