### ISSUE TITLE
有针对egg的生产环境部署监控方案吗？

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#555]
基于pm2的开源方案是有一些的，如keymetrics：[Node-js生产环境部署监控方案-pm2-keymetrics](http://www.kivixv.com/2016/08/22/Node-js%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2%E7%9B%91%E6%8E%A7%E6%96%B9%E6%A1%88-pm2-keymetrics/)

egg的生产部署监控方案有标准方案或推荐方案吗？谢谢

**Comment by dead-horse** [comment]
通过日志进行监控。或者可以尝试 https://sentry.io/welcome/

**Comment by johnnychen** [comment]
好像都是收费的，开源的有推荐吗

**Comment by dead-horse** [comment]
通用的基于日志的监控方案和系统都可以的，与 egg 没有关系。先关掉了。

**Comment by johnnychen** [comment]
另外，我问题描述的不清楚，应该是包括`错误监控`和`性能监控`的，错误监控通过日志分析，那性能监控呢？

**Comment by dead-horse** [comment]
cpu 、内存、网络这些性能监控也是通用的，qps、rt 等信息也是可以通过日志采集的。 node 的性能监控如果是阿里云的话可以用 http://alinode.aliyun.com/

**Comment by wuhw** [comment]
@dead-horse 
除了接入阿里云和 alinode  egg有没有提供方式  收集cpu、内存等资源使用情况的信息  用户自己去分析

**Comment by atian25** [comment]
@dead-horse 地址错了，这个是收费的，要下线了

**Comment by atian25** [comment]
https://node.console.aliyun.com/

这个才对

**Comment by atian25** [comment]
@wuhw alinode 并没要求你必须部署到阿里云

**Comment by wuhw** [comment]
@atian25  刚贴的地址是免费的吗？  部署方案会有开源吗

**Comment by atian25** [comment]
啥部署方案？你之前怎么部署就怎么部署。

看下 egg 的部署文档

**Comment by wuhw** [comment]
文档上对于性能监控部署只是简单的说明了下接入阿里性能分析平台   
现在如果是我们自己去部署一个性能分析平台  基于egg的日志进行性能监控和分析  
这部分的方案说明文档中并没有体现

**Comment by atian25** [comment]
@wuhw 你自建的性能分析平台，肯定是你自己要写 egg 插件... 这个我怎么说明....
