### ISSUE TITLE
egg cors 跨域问题

### ISSUE THREAD

**Issue by miaosun009** [eggjs/egg#560]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

我用egg 作为了个api服务端， 前端需要跨域访问， 我使用的cors方式进行跨域，我在 相应数据的时候设置了响应头 如下：

ajaxReturn(code, msg, info) {this.ctx.set('Access-Control-Allow-Origin', 'http://127.0.0.1:7001');            this.ctx.set('Access-Control-Expose-Headers','Set-Cookie')
            this.ctx.set('Access-Control-Allow-Methods','GET, POST, PUT,OPTIONS')
            this.ctx.set('Access-Control-Allow-Credentials',true)
            this.ctx.set('Access-Control-Allow-Headers', 'Accept,x-csrf-token,X-Custom-Header,X-Requested-With,Origin, Content-Type, Authorization');
            this.ctx.body = {
                code: code,
                msg: msg,
                info: info
            }
            return 
}

前端请求如下：
axios.post(this.url, 'x-csrf-token='+this.getCookie('csrfToken')).then(function (response) {
          console.log(response);
        }).catch(function (error) {
          console.log(error);
        });

为什么发送POST请求后返回的是 403的错误，服务器的记录提示

2017-03-13 13:21:44,177 WARN 20572 [-/127.0.0.1/-/24ms POST /api/user/register] missing csrf token. See https://eggjs.org/zh-cn/core/security.html#安全威胁csrf的防范
2017-03-13 13:21:44,180 WARN 20572 [-/127.0.0.1/-/28ms POST /api/user/register] nodejs.ForbiddenError: missing csrf token

但是我已经已经按照文档所说的加了 csrftoken

请问这问题该如何解决？

**Comment by miaosun009** [comment]
get 请求是没有问题的，就是post 会出现这样的问题

**Comment by jtyjty99999** [comment]
通过 body 传递 CSRF token 的默认字段为 _csrf，不是 x-csrf-token

**Comment by jtyjty99999** [comment]
axios 使用 header 方式传递 token 的方式是 config 中指定
`headers: {'x-csrf-token': csrfToken},`

**Comment by miaosun009** [comment]
设置完了headers: {'x-csrf-token': csrfToken} 就报405错误了 
浏览器返回如下
Request URL:http://127.0.0.1:7001/api/user/register
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:127.0.0.1:7001

**Comment by miaosun009** [comment]
@jtyjty99999 
设置完了headers: {'x-csrf-token': csrfToken} 就报405错误了
浏览器返回如下
Request URL:http://127.0.0.1:7001/api/user/register
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:127.0.0.1:7001

**Comment by jtyjty99999** [comment]
@miaosun009 你的应用没有注册options请求的路由吧。而且跨域你可以直接使用这个插件 https://github.com/eggjs/egg-cors

**Comment by miaosun009** [comment]
@jtyjty99999 
谢谢您， 虽然我用了插件， 
我还在axios 的配置里面加了withCredentials:true

但是我的post请求还是有问题：

Request URL:http://127.0.0.1:7001/api/user/register
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:127.0.0.1:7001
Response Headers
view source
Access-Control-Allow-Headers:x-csrf-token
Access-Control-Allow-Methods:GET,HEAD,PUT,POST,DELETE,PATCH
Access-Control-Allow-Origin:http://localhost:8080
Connection:keep-alive
Date:Mon, 13 Mar 2017 06:24:49 GMT
Vary:Origin
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:x-csrf-token
Access-Control-Request-Method:POST
Connection:keep-alive
Host:127.0.0.1:7001
Origin:http://localhost:8080
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by miaosun009** [comment]
我在egg的配置里面加了withCredentials:true
终于报无效的csrf-token了，证明是没有传递正确的csrf-token， 我在试试把
谢谢你不耐烦的指导 @jtyjty99999
