### ISSUE TITLE
关于jsonp

### ISSUE THREAD

**Issue by wildboy850** [eggjs/egg#561]
假如要在controller直接访问获取jsonp该怎样进行,client似乎不支持jsonp，这样会报nodejs.JSONResponseFormatError:

// app/router.js
module.exports = app => {
    const jsonp = app.jsonp();
    app.get('/test',jsonp, 'home.index');    
};

// app/controller/home.js
module.exports = app => {
    class HomeController extends app.Controller {
        * index() {
            const ctx = this.ctx;
            const result = yield app.curl('http://xxx.com/promotion/index?titleID=3326', {
                method: 'get'，
                dataType:'json'
            });
            console.log(result.data);
        }
    }
    return HomeController;
};

**Comment by dead-horse** [comment]
你返回的格式是 jsonp，但是传 dataType 会强制当做 json 解析，所以报错。 jsonp 本来是给前端跨域使用的，后端调用接口本来就不应该使用 jsonp。这个只能你自己想办法解析。建议你请求 json 接口而不是 jsonp 接口。
