### ISSUE TITLE
支持robots.txt吗？

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#564]
## 支持robots.txt吗？
- 我试了下不支持。

**Comment by atian25** [comment]
自己写个 controller 即可.

```js
app.get('/robots.txt', function* () {
  this.body = ``;
});
```

**Comment by jtyjty99999** [comment]
siteFile插件我记得支持的。。现在去掉了吗

**Comment by atian25** [comment]
也行，加一个配置即可。

- https://github.com/eggjs/egg/blob/master/app/middleware/site_file.js
- https://github.com/eggjs/egg/blob/master/config/config.default.js#L147
