### ISSUE TITLE
有关 Controller 里 ctx 与 this 的讨论

### ISSUE THREAD

**Issue by zbinlin** [eggjs/egg#566]
刚开始看 egg 的文档，对于在 Contoller 里的 ctx 与 this 有些疑问。

首先在 [controller](http://eggjs.org/zh-cn/basics/controller.html) 一章里明确了使用 controller 有两种方式：一种是 controller 类，还有一种是 controller 方法。但我发现在 controller 类里 generator 方法的 `this` 指向 controller 类的实例（这可以理解），但 controller 方法的 `this` 指向了 Context 的实例（这好像有点不妥吧）。我建议这里是否当使用 controller 方法时自动使用一个匿名的 controller 类，从而对 this 统一指向 controller 类的实例？

还有一个问题，在 controller 类的示例代码里，使用 `this` 里的 `ctx`，而在 controller 方法的示例代码里，使用的是传进来的 `ctx`，这里的示例是否统一改成使用传进来的 `ctx` 呢？这对新手来说或许更友好些 :)

还有在 [框架扩展](http://eggjs.org/zh-cn/basics/extend.html#%E8%AE%BF%E9%97%AE%E6%96%B9%E5%BC%8F-2) 里的 Context 的访问方式一小节：

> controller，middleware 中 this 就是 ctx，例如 this.cookies.get('foo')。

这里 controller 的 `this` 只有在 controller 方法里才是 `ctx` 吧

**Comment by popomore** [comment]
主要是两种风格，本身就存在差异。类写法是 egg 风格的，函数是 koa 中间件风格的。

在 egg 应用中建议统一使用类写法，这样和 service 等等都可以统一，从 this.ctx 上拿实例。

纯函数的方式是底层的运行，原来使用 koa 的人可能更习惯那种用法。而且 koa2 的写法也会有一些差异，类的兼容性会更好一些。

**Comment by fengmk2** [comment]
generator 方法主要是保留koa1的兼容性写法，如果你是全新的项目，可以按照egg推荐的类写法写即可。
中间件是特殊的，建议你按koa2的中间件写法来写，这样就不需要学koa1的写法了。

**Comment by atian25** [comment]
@zbinlin 感谢反馈，我们支持 controller class 比文档晚一点，所以文档里面有些地方就不太统一，欢迎直接给我们 PR~

@fengmk2 这些地方确实有点旧了

![image](https://cloud.githubusercontent.com/assets/227713/23881230/18c7487a-0894-11e7-827f-037c8056d01c.png)

**Comment by atian25** [comment]
我们文档里面，现在应该都可以统一用 class 或 ctx.xxx 的方式，不再用 this.xxx 的方式了，@dead-horse @fengmk2

**Comment by popomore** [comment]
看怎么写吧？如果只写个调用可以直接写 `ctx.xxx`，只要能保证运行，有时候觉得写类太长了。

**Comment by atian25** [comment]
嗯，文档里面尽量都写 `ctx.xxx` 的形式，不要 this 了


> 首先在 controller 一章里明确了使用 controller 有两种方式：一种是 controller 类，还有一种是 controller 方法。但我发现在 controller 类里 generator 方法的 this 指向 controller 类的实例（这可以理解），但 controller 方法的 this 指向了 Context 的实例（这好像有点不妥吧）。我建议这里是否当使用 controller 方法时自动使用一个匿名的 controller 类，从而对 this 统一指向 controller 类的实例？

@popomore  这个你看看？

**Comment by popomore** [comment]
纯函数转成类，里面的 this 更难理解，不管是面向新的 egg 开发者还是原来 koa 的开发者。

**Comment by atian25** [comment]
> 但我发现在 controller 类里 generator 方法的 this 指向 controller 类的实例（这可以理解），但 controller 方法的 this 指向了 Context 的实例（这好像有点不妥吧）

@zbinlin this 

```
module.exports = app => {
  class PostController extends app.Controller {
    * create() {
      const { ctx, service } = this;
    }
  }
}
```

**Comment by zbinlin** [comment]
@popomore

> 纯函数转成类，里面的 this 更难理解，不管是面向新的 egg 开发者还是原来 koa 的开发者。

在 koa 的 generator 函数里的 this 也不好理解呀。不知道你们是否理解我的意思，我主要是想把 contoller 里 exports 出来的函数（generator）统一再使用一个匿名的 Controller 封装起来，例如有一个 controller 文件为 foo.js，里面内容为：

```javascript
exports.index = function* () {
    console.log(this);
};
exports.about = function* () {
};
```

它导出两个 generator 函数，然后我们可以在初始化时，将这两个函数挂载到一个匿名的 Controller 里，然后再直接初始化这个匿名的 Controller。这样，这两个函数里的 this 就与 controller 类实例里的 this 一致了。

初始化的工作可以在 https://github.com/eggjs/egg-core/blob/master/lib/loader/mixin/controller.js#L37 这里处理：

```javascript
const anon = class AnonymousController extends BaseContextClass {};
Object.assign(anon.prototype, obj, {
    pathName: opt.pathName
});
return wrapObject(anon);
```

**Comment by popomore** [comment]
> 在 koa 的 generator 函数里的 this 也不好理解呀

对 koa 不熟悉的建议使用类的方式，如果使用 koa 写过代码的应该能够理解这个 this 的意义。

> 不知道你们是否理解我的意思

我理解你的意思，但是一个纯函数的 this 指向一个不存在的类，会让人更加疑惑。如果你有这样的想法，你可以在自己的应用覆盖 loadController 实现。
