### ISSUE TITLE
Service 的继承怎么写

### ISSUE THREAD

**Issue by itmuse** [eggjs/egg#567]
Service中有继承的设计需求，怎么编写Service的继承类(class)？

**Comment by atian25** [comment]
如果是全局的基类，可以参考 https://eggjs.org/zh-cn/basics/controller.html#自定义-controller-基类，在 app.js 里面覆盖掉 `app.Service` 即可。

如果不是全局的，把你的类放到 `lib/service.js` 然后按 node 那样 require 进去即可

**Comment by itmuse** [comment]
发现其实可以自定义一个别名Service，代码如下：

```javascript
// app.js

'use strict';
module.exports = app => {
  class CustomService extends app.Service {
    // some common functions
  };
  app.CustomService = CustomService;
}
```
编辑继承自定义Service类：

```javascript
// service/custom.js

'use strict';

module.exports = app => {
    class Custom extends app.CustomService {
        // do something and call supper common functions.
    }

    return Custom;
}
```

**Comment by atian25** [comment]
当然可以，`app.js` 就是用来做自定义的，当然用 `app/extend/application.js` 更适合，具体看你的场景。

**Comment by itmuse** [comment]
谢谢提点，刚刚用egg，发现相当强大和可自定义化，继续研究：）

**Comment by atian25** [comment]
^_^  egg 就是设计来帮助架构师搭建上层框架的，自定义这块可以看 Loader API 文档
