### ISSUE TITLE
关于日志的问题

### ISSUE THREAD

**Issue by ysstech** [eggjs/egg#569]
* **Node Version**: 7.6
* **Egg Version**: 1.0.0-rc2
* **Plugin Name**:
* **Plugin Version**: 
* **Platform**: darwin os el 10.11

请问在多进程模式下，日志记录是由worker完成，还是agent？如果由worker完成，那么如何保证多进程对同一个应用日志文件的写问题？

**Comment by popomore** [comment]
- agent worker 和 app worker 都会打
- 用的是 append，不会有问题。可以看看 fs 的 flag https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_open_path_flags_mode_callback

**Comment by ysstech** [comment]
恩 确实是的，多谢
另外关于logrotator，从代码来看是在分割完日志的时候，发出消息，worker/agent接收消息后reloadStream，再这段期间内日志流对象依然保持输出在分割之前的log文件上。这种做法会有时间差，为何不考虑使用filelock的方式？在rotator分割时加锁，等待分割结束后释放。worker/agent可以等待锁释放后进行reloadStream。

**Comment by dead-horse** [comment]
这一瞬间的日志即使打印在老的文件也没有什么大问题，没必要那么复杂。

**Comment by ysstech** [comment]
确实复杂性降低了，但logrotator与logger紧耦合在agent\worker的这种架构模式下，无法作为一个单独的日志插件独立使用了。
当然这属于另一个话题。

**Comment by popomore** [comment]
logrotator 支持自定义切割的，只是我们不建议使用第三方 logger 库，喜欢折腾的可以玩玩。
