### ISSUE TITLE
文档说词有待讨论

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#572]
- 如下图红圈所指，不一定是` generator function`吧？
![snip20170314_11](https://cloud.githubusercontent.com/assets/3679798/23901806/cee94cb0-08f9-11e7-9bde-a7e8dc5bed3d.png)

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/tutorials/async-function.html 所有可以用 generator function 的地方都可以用 async function 替代，我们统一在 async function 章节提了，不会每个地方都说明。
