### ISSUE TITLE
egg-redis app.redis.set is not a function

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#573]
windows 7 install and use
![ic f9sur0g 6 ee0j dee8](https://cloud.githubusercontent.com/assets/21269645/23929836/993ef73a-0963-11e7-8275-5e94041dea72.png)
code:
config.default.js:
![1q ej3 849v9im7bh1_q84o](https://cloud.githubusercontent.com/assets/21269645/23929869/bd716408-0963-11e7-8612-f119084f0477.png)
plugin.js:
![m 1 5tccmucd7yl3tglg_o7](https://cloud.githubusercontent.com/assets/21269645/23929881/cba7d4c6-0963-11e7-9341-4593e164f70f.png)
app.controller.home.js:
![3zo9dya9ku tnoho 8ahzd](https://cloud.githubusercontent.com/assets/21269645/23929920/02bf7310-0964-11e7-9c50-e74205e1e03f.png)
then request:
![in_khl jzdkn9uvgt 5xd5](https://cloud.githubusercontent.com/assets/21269645/23929947/2cfdde14-0964-11e7-8f79-b1ab5c13c5ec.png)

node 7.7.2
![bi w1 xxg a5kzrwtq4ytc](https://cloud.githubusercontent.com/assets/21269645/23930063/f1dc02a6-0964-11e7-8473-5239d0d631f0.png)

**Comment by jtyjty99999** [comment]
不使用cluster模式不要配置到node里，而且要配置到client下。请参考 https://github.com/eggjs/egg-redis/blob/master/config/config.default.js

**Comment by grubed** [comment]
![4a7u3qbp w u2xkbdh k](https://cloud.githubusercontent.com/assets/21269645/23930286/5553d380-0966-11e7-8102-523e9f1747b2.png)
改成这样还是不行

**Comment by grubed** [comment]
'use strict';
const path = require('path');
module.exports = appInfo => {
  const config = {
      view: {
          defaultViewEngine: 'nunjucks',
          mapping: {
              '.tpl': 'nunjucks',
          },
          root: [
              path.join(appInfo.baseDir, 'app/view'),
              path.join(appInfo.baseDir, 'path/to/another'),
          ].join(',')
      },
      security: {
        xframe: {
          enable: false,
        },
        csrf: {
          queryName: '_csrf', // 通过 query 传递 CSRF token 的默认字段为 _csrf
          bodyName: '_csrf', // 通过 body 传递 CSRF token 的默认字段为 _csrf
          headerName: 'x-csrf-token',
        },
      },
      mysql : {
      // database configuration
          client: {
              // host
              host: 'localhost',
              // port
              port: '3306',
              // username
              user: 'root',
              // password
              password: 'root',
              // database
              database: 'test',
          },
          // load into app, default is open
          app: true,
          // load into agent, default is close
          agent: false,
      },  
      redis : {
      // database configuration
          default: {
              // host
              host: '127.0.0.1',
              // port
              port: '6379',
          },
          // load into app, default is open
          app: true,
          // load into agent, default is close
          agent: false,
      },
  };

  // should change to your own
  config.keys = appInfo.name + '_1489048554806_6546';

  return config;
};
mysql都没问题

**Comment by grubed** [comment]
add 
              password: '',
              db: '0',
success

**Comment by grubed** [comment]
@jtyjty99999 thx

**Comment by nlove518** [comment]
egg-redis app.redis.set is not a function　还是有这个问题，请问是怎么解决的？

**Comment by hello2dj** [comment]
我也遇到了，按照文档走的，也没改啥，egg-redis app.redis.set is not a function

**Comment by hello2dj** [comment]
Singleton {
  clients: Map {},
  app:
   { env: 'local',
     name: 'example',
     baseDir: '/Users/sensoro/Study/node/egg-example',
     subdomainOffset: 2,
     config: '<egg config>',
     controller: '<egg controller>',
     serviceClasses: '<egg serviceClasses>',
     middlewares: '<egg middlewares>',
     httpclient: '<egg httpclient>',
     loggers: '<egg loggers>' },
  name: 'redis',
  create: [Function: createClient],
  options:
   { default: {},
     app: true,
     agent: false,
     host: '127.0.0.1',
     port: '6379',
     db: 0,
     password: '' } }
我把app.redis打印出来了，这是对的么？

**Comment by hello2dj** [comment]
Singleton {
  clients: Map {},
  app: {
    env: 'local',
    name: 'example',
    baseDir: '/Users/sensoro/Study/node/egg-example',
    subdomainOffset: 2,
    config: '<egg config>',
    controller: '<egg controller>',
    serviceClasses: '<egg serviceClasses>',
    middlewares: '<egg middlewares>',
    httpclient: '<egg httpclient>',
    loggers: '<egg loggers>'
  },
  name: 'redis',
  create: [Function: createClient],
  options: { 
    default: { },
    app: true,
    agent: false,
    host: '127.0.0.1',
    port: '6379',
    db: 0,
    password: ''
  }
}
这是我打印出来的app.redis？是正常的么

**Comment by hello2dj** [comment]
配置问题吧，一定得有client or clients

**Comment by alexsunxl** [comment]
要把 sessionRedis的name配置为空或者不配置
```
config.sessionRedis = {
    name: '', // 
  }
```


因为 egg-session-redis/app.js 里的头两行代码是这样的
```
  const name = app.config.sessionRedis.name;      
  const redis = name ? app.redis.get(name) : app.redis;
```

**Comment by guoqing2015** [comment]
一个redis实例， sessionRedis配置中不需要指定实例名，即
`
config.redis = {
    client: {
      host: '127.0.0.1',
      port: 6379,
      password: '',
      db: '0',
    },
  };
  config.sessionRedis = {
    // name: 'session', // 这里不要指定name
  };
`

如果redis有多个实例，sessionRedis配置中的name需要指定一个实例名
`
config.redis = {
  clients: {
    foo: {                 // instanceName. See below
      port: 6379,          // Redis port
      host: '127.0.0.1',   // Redis host
      password: 'auth',
      db: 0,
    },
    bar: {
      port: 6379,
      host: '127.0.0.1',
      password: 'auth',
      db: 1,
    },
  }
  config.sessionRedis = {
    name: 'foo', 
  };
`
