### ISSUE TITLE
可以在Visual Studio Code直接debug吗？

### ISSUE THREAD

**Issue by j4dream** [eggjs/egg#574]
无法在 vscode debug， 能否直接在 vscode 打断点调试，不用跳到浏览器 debug ?

**Comment by bishanshan** [comment]
参看 @atian25 的[研究结果]( https://github.com/atian25/blog/issues/15)

**Comment by atian25** [comment]
那个研究并没有得到最终的答案，主要问题在于 vscode 的 cluster debug 体验不是很好，1.9 版本出了新特性，但暂时没时间研究，有兴趣的同学可以研究下，写篇科普文，感谢~
