### ISSUE TITLE
egg是不是需要一个专门的论坛让用户交流？

### ISSUE THREAD

**Issue by coolicer** [eggjs/egg#576]
如题，希望官方考虑一下。期待bbs.eggjs.org

**Comment by atian25** [comment]
目前而言：

- eggjs 团队答疑和跟进问题仅采用 GitHub Issues 的方式。
- 用户间交流的，可以根据自己的喜好，譬如在 CNode 等社区。
- 微信群，QQ 群不考虑。

**Comment by coolicer** [comment]
@atian25 issues关了就看不到

**Comment by atian25** [comment]
我理解你的意思，如果 issue 里面有价值的答疑，应该流向是：`纳入到文档，或者 FAQ`。

其他的，Google 搜索应该有索引 GitHub Issue 的吧？

eggjs 团队暂时不会考虑搭建一个论坛来交流，因为很难维护，而且团队成员不一定会关注到论坛。

当然，我们欢迎社区的用户自发组织在某个社区进行交流，我们可以加上友情链接。

**Comment by coolicer** [comment]
差不多是这样 @atian25

**Comment by dead-horse** [comment]
https://gitter.im/eggjs/egg

**Comment by jeremy16601** [comment]
虽然可以去cnode社区讨论，也可以issues里讨论，但是issues 也不是特别方便，而且不能所有的小白问题都在这提吧。所以感觉还是qq群适合那些入门的，欢迎大家加入：295378978  一起学习egg
