### ISSUE TITLE
中间件匹配 RESTful路由

### ISSUE THREAD

**Issue by bing1021** [eggjs/egg#577]
我使用app.resources('posts', '/posts', 'posts'); 方法创建RESTful路由。

我想为其中的post、put、delete匹配一个中间件，而get请求不会匹配到。

要如何做呢？

中间件的match和ignore似乎不能匹配请求方式。

在router.js中去写 app.post('/posts', 中间件, 'posts'); 的话，app.resources();这个快捷方法也就没意义了。

我想的办法是在中间件判断请求方式。

还是问问吧，是不是有什么配置可以做到

**Comment by popomore** [comment]
`app.resources` 也支持中间件的，然后在中间件里面过滤下 get 请求。

**Comment by dead-horse** [comment]
```js
// app/middleware/auth.js
module.exports = () => {
  return function* (next) {
    if (this.method === 'GET') return yield next;
    // do something
    yield next;
  }
}

// app/router.js
module.exports = app => {
  app.resources('posts', '/posts', app.middlewares.auth(), 'posts');
}
```

**Comment by bing1021** [comment]
thanks
