### ISSUE TITLE
egg-i18n 可以支持下 template string 的语法

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#58]
- http://jaysoo.ca/2014/03/20/i18n-with-es6-template-strings/
- https://www.npmjs.com/package/common-tags

``{{ i18n`Hello ${user.name}, how are you today?`}}``

**Comment by dead-horse** [comment]
这种太慢了，还是不要提供吧，如果要我们来实现的话要 replace

**Comment by atian25** [comment]
ok
