### ISSUE TITLE
egg有没有一个专门查看api方法的地方

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#581]
egg有没有一个专门查看api方法的地方，比如我想查看Helper下框架默认提供了什么方法，应该在什么地方看。

**Comment by atian25** [comment]
https://eggjs.org/api/

但这块还没整理好，我个人是断点来看的。。。

**Comment by sunshinexb** [comment]
能方便透露下你是使用什么工具来开发，打断点的么？

**Comment by atian25** [comment]
webstorm

发自我的 iPhone

**Comment by huacnlee** [comment]
导航栏应该增加 API 的链接，这个对于深入开发很重要的

**Comment by atian25** [comment]
这个 @popomore 之前搞了一部分，还没搞完

发自我的 iPhone

**Comment by popomore** [comment]
先开放出来吧，有问题再改
