### ISSUE TITLE
单元测试的路径层次整个文档中不统一

### ISSUE THREAD

**Issue by kylezhang** [eggjs/egg#582]
### 问题：单元测试的路径层次整个文档中不统一，主要差别是`test下面要不要app目录？`
- [快速入门文档中](https://eggjs.org/zh-cn/intro/quickstart.html#单元测试)
![image](https://cloud.githubusercontent.com/assets/3679798/23980160/0c23c340-0a39-11e7-8ce3-85ed056bc8e2.png)

- [单元测试文档中](https://eggjs.org/zh-cn/core/unittest.html#测试约定)
![image](https://cloud.githubusercontent.com/assets/3679798/23980235/7a73be40-0a39-11e7-972b-c5c4db4f0bc6.png)

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
我一般省略 app 目录，因为一般很少代码会出现在非 app 目录下，但是保留 app 目录也无所谓，路径更统一。这个没有强制要求，都可以。

**Comment by atian25** [comment]
@kylezhang 看的很细，👍 ，之前写文档的时候，我有看到这个差别，不过当时觉得关系不大。
