### ISSUE TITLE
寻求 WebStorm, VSCode 下的调试方法

### ISSUE THREAD

**Issue by seansh** [eggjs/egg#584]
egg的项目在IDE工具下如何调试呢？，是不是可以在文档里描述一下？

**Comment by atian25** [comment]
先看下 https://github.com/atian25/blog/issues/15

我晚点补到 FAQ 吧。

**Comment by seansh** [comment]
通过npm script的方法，在node6.10，webstorm2016.3.4下可以正常调试了，过程中遇到node7.6不能正常调试的坑

**Comment by atian25** [comment]
这个是 webstorm 的 bug，没办法~ 我印象中即使用 `index.js` 也会被卡住，要去官方提 issue

**Comment by seansh** [comment]
测试了下上面的环境中index.js也可以正常调试

**Comment by atian25** [comment]
喔，但也还是 webstorm 的 bug~ （逃。。。

**Comment by elover** [comment]
@atian25 这个问题还是需要多关注一下，我在node 7.7.2 ,PhpStorm 2017.1 EAP 上其他的node项目下面可以调试，但是egg-demo的不行

**Comment by atian25** [comment]
@elover 你起一个 cluster 的 node 项目试试，我印象中这个 BUG 是 webstorm 在 7.x 下调试 cluster 的问题

**Comment by atian25** [comment]
不行

**Comment by atian25** [comment]
刚试了下，可以正常调试，
- Mac 
- WebStorm 2016.3.4Build #WS-163.13906.20, built on March 7, 2017
- Node.js 7.7.1 x64


![image](https://cloud.githubusercontent.com/assets/227713/24027466/c322f83a-0b02-11e7-9508-b22266db1789.png)

![image](https://cloud.githubusercontent.com/assets/227713/24027459/b7d81f5a-0b02-11e7-89a0-59bd583450c6.png)

**Comment by elover** [comment]
npm run dev 这条命令有加什么参数吗？

启动的时候log能发下看看吗？

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/24027566/6af37148-0b03-11e7-96a4-de92f8ef3529.png)

`"dev": "egg-bin dev -- $NODE_DEBUG_OPTION"` 和 `"dev": "egg-bin dev -$NODE_DEBUG_OPTION",` 貌似都行，我今天正在重构 egg-bin，会确定并统一一种格式。

**Comment by atian25** [comment]
如果你是卡在前面，没有 `egg start` 那行的话，有可能跟之前这个问题有关，但应该解决了才对：

https://youtrack.jetbrains.com/issue/WEB-22466

**Comment by yuzukwok** [comment]
WebStorm 调试体验如何，各种支持？

**Comment by atian25** [comment]
WebStorm 目前应该是前端 IDE 里面调试体验最好的了吧，尤其是 cluster 这块，能全部断点，并且 worker 重启后还能自动 attach 新端口。

**Comment by yuzukwok** [comment]
插件更新了下：支持自动附加到调试进程，优化egg调试体验（实验,待egg 或vscode优化后会移除） 
    先在集成控制台中使用npm run dev -- --inspect 开启调试后 
    命令面板 选择“egg自动附加调试进程(实验)”（默认快捷建为ctrl+1/ cmd+1） vscode 将自动附加一个node调试进程，规则如下  
    mac： 以--inspect= 启动的进程  
    windows：以调试端口>9230的调试进程

**Comment by rorivers** [comment]
要不要来跟踪下egg框架的启动过程。
环境：
1）window7
2）Node.js7.7.4 (可以使用--inspect-brk；和--inspect的区别请查看文档里debugger模块)
3）chrome canary版（内置chrome-devtools，专门来调试Node应用的。再也不用node-inspector啦）
另，需要开vpn。用来下载canary版，carney里第一次打开调试页面，需要从google下载一些html等。

准备好环境之后，
修改
node_modules\egg-bin\lib\debug_command.js
里：
`      execArgv: this.helper.formatExecArgv(args).concat([ '--inspect-brk' ]),`
将--inspect改为--inspect-brk。

再用npm run dev启动我们demo项目，就会发现，控制台上，打到类似下面的语句停住了，
`chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/71537bce-5e47-4492-add7-cb38cd3e1b0d`

在chrome canary版里，打开上面的链接（一定要挂vpn），可以调试啦。好运！

**Comment by atian25** [comment]
@rorivers 不需要修改了，昨天发布了[egg-bin@3.0](https://github.com/eggjs/egg-bin)，直接支持 
```bash
$ egg-bin debug --debug-brk
```

**Comment by elover** [comment]
WebStorm 2017.1 目前可以debug吗？node 7的版本

**Comment by atian25** [comment]
刚测试了下，是可以的

- WebStorm 2017.1
- Node.js v7.7.4
- "debug": "egg-bin dev $NODE_DEBUG_OPTION",

不过要用 `egg-bin dev` 而不是 `egg-bin debug`，貌似 WebStorm 还不支持 `--inspect`，所以没法用后者，有兴趣的同学可以研究下怎么改。

**Comment by gcyStar** [comment]
关于调试没有通用性方案，WebStrome版本不对，node版本不对，就无法调试成功。
一定要选择特定相应的版本才行，如果egg能屏蔽这些差异就好了。

**Comment by atian25** [comment]
@gcyStar 这个是 IDE 的 BUG...  臣妾不能啊
