### ISSUE TITLE
有需求的插件记录

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#586]
记录下之前混迹一些群收集的egg插件需求

- [ ] egg-rate-limiter
- [ ] egg-sentry
- [ ] egg-dubbo
- [ ] egg-graphql
- [ ] egg同构插件
- [ ] egg-swagger
- [ ] egg-rabbit
- [ ] egg-kafka
- [ ] egg-sse
- [ ] egg-dust
- [ ] egg-waterline
- [ ] egg-paginate
- [ ] egg-webpack-dev-server

**Comment by dead-horse** [comment]
我建议这些都交给社区，可以搞个悬赏。
