### ISSUE TITLE
egg 团队底层协作开发环境？

### ISSUE THREAD

**Issue by elover** [eggjs/egg#592]
团队协作开发一般会用vagrant 等工具保证各个成员的开发环境和线上生成环境一致，在这块egg有什么推荐方式没有或者阿里内部一般怎么解决这样的问题？

**Comment by atian25** [comment]
这块没有强制，只确保 ci 环境和线上一致，一般就够了。

**Comment by ngot** [comment]
阿里里面环境只要有node，和npm就够了，其他都不用

**Comment by elover** [comment]
但是一些npm包在不同环境下会有区别吗？
或者比如说大家都要依赖redis、nginx、mysql这些东西需要每个人都装一次吗？

**Comment by elover** [comment]
想了下，我觉得不用vagrant也可以，重点保障ci

**Comment by atian25** [comment]
redis、nginx、mysql 这些是外部环境了，根据自己团队的情况选择即可： `vagrant `，`docker`，`直连测试机` 之类的。

> 顺便补充一点：@ngot 提到的  `只要有 node，和 npm 就够了`

我们的 Node.js 也是跟随应用的，用 [nodeinstall](https://www.npmjs.com/package/nodeinstall) 把需要的版本安装到 node_modules 下。
