### ISSUE TITLE
Agent 作用？

### ISSUE THREAD

**Issue by elover** [eggjs/egg#593]
我看了下官方文档，对agent在实际情况中的用途还不是很清楚。

想了解下，阿里一般怎么使用agent，不知道有什么实际场景没？

比如：
连接数据库？
写日志？
连接zookeeper等吗？

**Comment by atian25** [comment]
做脏活苦活的，https://eggjs.org/zh-cn/core/cluster-and-ipc.html#agent-机制

如：
- `egg-development` 里面监控文件变动重启
- `egg-schedule` 里面做 job 调度
- agent 里面定时读取服务端的配置，并同步给 workers

**Comment by zhangming0305** [comment]
我有这方面的问题，如果物理机器是1个cpu内核的，我们应该怎么设置worker的数量？

**Comment by atian25** [comment]
默认开启的 workers 个数是 cpu 个数。

你们线上服务器不会是 1 cpu 的吧。。。 一个 worker 的话，挂掉了都不能平衡重启，随便配置个几个吧。

**Comment by zhangming0305** [comment]
多谢指点，我去配置一下，多谢egg框架，的确灵活，严谨，考虑周全

**Comment by junyuz** [comment]
@atian25 请教一个问题，如果我服务是4核，想要配置成只启动一个work该如何配置
看到文档里面有提到
`// dispatch.js
const egg = require('egg');
const workers = Number(process.argv[2] || require('os').cpus().length);
egg.startCluster({
  workers,
  baseDir: __dirname,
});`
不知道使用的时候该如何配置

**Comment by atian25** [comment]
传递 `workers: 1` 不就行了。

不过我们现在不推荐用 `dispatch.js` 了，直接用 `egg-bin dev --workers=1` 和 `egg-scripts start --workers=1`

这段文档你在哪里看的？地址发下

**Comment by junyuz** [comment]
https://eggjs.org/zh-cn/core/cluster-and-ipc.html
Master VS Agent VS Worker这一节中有提到

**Comment by junyuz** [comment]
@atian25 
https://eggjs.org/zh-cn/core/cluster-and-ipc.html
Master VS Agent VS Worker这一节中有提到

**Comment by mongs** [comment]
agent 里可以调用service里的方法吗, 可以获取到ctx吗
