### ISSUE TITLE
Leancloud部署Egg代码时出错

### ISSUE THREAD

**Issue by chenmingjia** [eggjs/egg#596]
* **Node Version**:Node.js v6.10.0
* **Egg Version**:    "egg": "^1.0.0-rc.2"
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

1.本地开发没有问题，看了文档，写了dispatch.js，本地敲EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log & 没有问题，能运行。
2.在Leancloud上写了自定义的环境变量，EGG_SERVER_ENV=prod，然而部署上去就出现下面的错误日志，项目使用的是示例项目！想了解一下如何能解决？

错误日志如下:

✓ 准备部署应用到生产环境: web
 ✓ 正在检测运行时
 ✓ 检测到 node.js 运行时
 ✓ 压缩项目文件
 ✓ 上传应用文件 45.50 KB / 45.50 KB [===============================] 100.00% 1s
 ✓ 开始构建 20170319-152101
 ✓ 正在下载应用代码 ...
 ✓ 正在解压缩应用代码 ...
 ✓ 运行环境: nodejs (leanengine/nodejs-base)
 ✓ 正在下载和安装依赖项 ...
 ✓ 存储镜像到仓库（0B）...
 ✓ 镜像构建完成：20170319-152101
 ✓ 开始部署 20170319-152101 到 web1
 ✓ 正在创建新实例 ...
 ✓ [Node.js] 使用 Node.js v6.10.0
 ✓ 正在启动新实例 ...
   实例日志：[INFO] 2017-03-19 15:21:34,479 INFO 34 [egg-static] starting static serve /public/ -> /home/leanengine/app/app/public
[INFO] 2017-03-19 15:21:34,480 INFO 34 [egg:loader] Use middleware: static
[INFO] 2017-03-19 15:21:34,480 INFO 52 [egg:loader] Controller loaded: /home/leanengine/app/app/controller
[INFO] 2017-03-19 15:21:34,480 INFO 34 [egg:loader] Use middleware: bodyParser
[INFO] 2017-03-19 15:21:34,569 INFO 34 [egg:loader] Use middleware: session
[INFO] 2017-03-19 15:21:34,570 INFO 34 [egg:loader] Use middleware: i18n
[INFO] 2017-03-19 15:21:34,570 INFO 64 [egg:loader] Use middleware: session
[INFO] 2017-03-19 15:21:34,570 INFO 64 [egg:loader] Use middleware: i18n
[INFO] 2017-03-19 15:21:34,571 INFO 34 [egg-security] use csrf middleware
[INFO] 2017-03-19 15:21:34,572 INFO 64 [egg-security] use csrf middleware
[INFO] 2017-03-19 15:21:34,572 INFO 34 [egg-security] use methodnoallow middleware
[INFO] 2017-03-19 15:21:34,573 INFO 34 [egg-security] use noopen middleware
[INFO] 2017-03-19 15:21:34,573 INFO 64 [egg-security] use methodnoallow middleware
[INFO] 2017-03-19 15:21:34,573 INFO 34 [egg-security] use nosniff middleware
[INFO] 2017-03-19 15:21:34,574 INFO 64 [egg-security] use noopen middleware
[INFO] 2017-03-19 15:21:34,574 INFO 53 [Follower#Watcher] register to channel: Watcher success
[INFO] 2017-03-19 15:21:34,574 INFO 34 [egg-security] use xssProtection middleware
[INFO] 2017-03-19 15:21:34,574 INFO 64 [egg-security] use nosniff middleware
[INFO] 2017-03-19 15:21:34,574 INFO 53 [egg-watcher:app] watcher start success
[INFO] 2017-03-19 15:21:34,575 INFO 34 [egg-security] use xframe middleware
[INFO] 2017-03-19 15:21:34,575 INFO 34 [egg-security] compose 6 middlewares into one security middleware
[INFO] 2017-03-19 15:21:34,575 INFO 64 [egg-security] use xssProtection middleware
[INFO] 2017-03-19 15:21:34,575 INFO 34 [egg:loader] Use middleware: securities
[INFO] 2017-03-19 15:21:34,575 INFO 34 [egg:loader] Loaded middleware from ["/home/leanengine/app/node_modules/egg-onerror/app/middleware","/home/leanengine/app/node_modules/egg-session/app/middleware","/home/leanengine/app/node_modules/egg-i18n/app/middleware","/home/leanengine/app/node_modules/egg-watcher/app/middleware","/home/leanengine/app/node_modules/egg-multipart/app/middleware","/home/leanengine/app/node_modules/egg-security/app/middleware","/home/leanengine/app/node_modules/egg-schedule/app/middleware","/home/leanengine/app/node_modules/egg-logrotator/app/middleware","/home/leanengine/app/node_modules/egg-static/app/middleware","/home/leanengine/app/node_modules/egg-jsonp/app/middleware","/home/leanengine/app/node_modules/egg-view/app/middleware","/home/leanengine/app/node_modules/egg/app/middleware","/home/leanengine/app/app/middleware"]
[INFO] 2017-03-19 15:21:34,575 INFO 53 [egg:core:ready_stat] end ready task /home/leanengine/app/node_modules/egg-watcher/app.js:15:7, remain []
[INFO] 2017-03-19 15:21:34,576 INFO 64 [egg-security] use xframe middleware
[INFO] 2017-03-19 15:21:34,576 INFO 64 [egg-security] compose 6 middlewares into one security middleware
[INFO] 2017-03-19 15:21:34,576 INFO 64 [egg:loader] Use middleware: securities
[INFO] 2017-03-19 15:21:34,576 INFO 64 [egg:loader] Loaded middleware from ["/home/leanengine/app/node_modules/egg-onerror/app/middleware","/home/leanengine/app/node_modules/egg-session/app/middleware","/home/leanengine/app/node_modules/egg-i18n/app/middleware","/home/leanengine/app/node_modules/egg-watcher/app/middleware","/home/leanengine/app/node_modules/egg-multipart/app/middleware","/home/leanengine/app/node_modules/egg-security/app/middleware","/home/leanengine/app/node_modules/egg-schedule/app/middleware","/home/leanengine/app/node_modules/egg-logrotator/app/middleware","/home/leanengine/app/node_modules/egg-static/app/middleware","/home/leanengine/app/node_modules/egg-jsonp/app/middleware","/home/leanengine/app/node_modules/egg-view/app/middleware","/home/leanengine/app/node_modules/egg/app/middleware","/home/leanengine/app/app/middleware"]
[INFO] 2017-03-19 15:21:34,670 INFO 34 [egg:loader] Controller loaded: /home/leanengine/app/app/controller
[INFO] 2017-03-19 15:21:34,675 INFO 64 [egg:loader] Controller loaded: /home/leanengine/app/app/controller
[INFO] 2017-03-19 15:21:34,776 INFO 46 Use coreMiddleware order: ["meta","siteFile","notfound","static","bodyParser","session","i18n","securities"]
[INFO] 2017-03-19 15:21:34,777 INFO 46 Use appMiddleware order: []
[INFO] 2017-03-19 15:21:34,871 INFO 52 [ClusterClient#Watcher] gives up seizing port 57087, and serves as follower client.
[INFO] 2017-03-19 15:21:34,871 INFO 46 [egg:loader] Use middleware: meta
[INFO] 2017-03-19 15:21:34,871 INFO 46 [egg:loader] Use middleware: siteFile
[INFO] 2017-03-19 15:21:34,871 INFO 46 [egg:loader] Use middleware: notfound
[INFO] 2017-03-19 15:21:34,872 INFO 46 [egg-static] starting static serve /public/ -> /home/leanengine/app/app/public
[INFO] 2017-03-19 15:21:34,873 INFO 46 [egg:loader] Use middleware: static
[INFO] 2017-03-19 15:21:34,873 INFO 46 [egg:loader] Use middleware: bodyParser
[INFO] 2017-03-19 15:21:34,874 INFO 46 [egg:loader] Use middleware: session
[INFO] 2017-03-19 15:21:34,874 INFO 46 [egg:loader] Use middleware: i18n
[INFO] 2017-03-19 15:21:34,876 INFO 46 [egg-security] use csrf middleware
[INFO] 2017-03-19 15:21:34,879 INFO 52 [Follower#Watcher] register to channel: Watcher success
[INFO] 2017-03-19 15:21:34,880 INFO 52 [egg-watcher:app] watcher start success
[INFO] 2017-03-19 15:21:34,881 INFO 52 [egg:core:ready_stat] end ready task /home/leanengine/app/node_modules/egg-watcher/app.js:15:7, remain []
[INFO] 2017-03-19 15:21:34,969 INFO 46 [egg-security] use methodnoallow middleware
[INFO] 2017-03-19 15:21:34,971 INFO 46 [egg-security] use noopen middleware
[INFO] 2017-03-19 15:21:34,972 INFO 46 [egg-security] use nosniff middleware
[INFO] 2017-03-19 15:21:34,973 INFO 46 [egg-security] use xssProtection middleware
[INFO] 2017-03-19 15:21:34,974 INFO 46 [egg-security] use xframe middleware
[INFO] 2017-03-19 15:21:34,974 INFO 46 [egg-security] compose 6 middlewares into one security middleware
[INFO] 2017-03-19 15:21:34,975 INFO 46 [egg:loader] Use middleware: securities
[INFO] 2017-03-19 15:21:34,975 INFO 46 [egg:loader] Loaded middleware from ["/home/leanengine/app/node_modules/egg-onerror/app/middleware","/home/leanengine/app/node_modules/egg-session/app/middleware","/home/leanengine/app/node_modules/egg-i18n/app/middleware","/home/leanengine/app/node_modules/egg-watcher/app/middleware","/home/leanengine/app/node_modules/egg-multipart/app/middleware","/home/leanengine/app/node_modules/egg-security/app/middleware","/home/leanengine/app/node_modules/egg-schedule/app/middleware","/home/leanengine/app/node_modules/egg-logrotator/app/middleware","/home/leanengine/app/node_modules/egg-static/app/middleware","/home/leanengine/app/node_modules/egg-jsonp/app/middleware","/home/leanengine/app/node_modules/egg-view/app/middleware","/home/leanengine/app/node_modules/egg/app/middleware","/home/leanengine/app/app/middleware"]
[INFO] 2017-03-19 15:21:34,978 INFO 46 [egg:loader] Controller loaded: /home/leanengine/app/app/controller
[INFO] 2017-03-19 15:21:35,073 INFO 34 [ClusterClient#Watcher] gives up seizing port 57087, and serves as follower client.
[INFO] 2017-03-19 15:21:35,074 INFO 64 [ClusterClient#Watcher] gives up seizing port 57087, and serves as follower client.
[INFO] 2017-03-19 15:21:35,177 INFO 34 [Follower#Watcher] register to channel: Watcher success
[INFO] 2017-03-19 15:21:35,177 INFO 34 [egg-watcher:app] watcher start success
[INFO] 2017-03-19 15:21:35,179 INFO 34 [egg:core:ready_stat] end ready task /home/leanengine/app/node_modules/egg-watcher/app.js:15:7, remain []
[INFO] 2017-03-19 15:21:35,271 INFO 64 [Follower#Watcher] register to channel: Watcher success
[INFO] 2017-03-19 15:21:35,272 INFO 64 [egg-watcher:app] watcher start success
[INFO] 2017-03-19 15:21:35,273 INFO 64 [egg:core:ready_stat] end ready task /home/leanengine/app/node_modules/egg-watcher/app.js:15:7, remain []
[INFO] 2017-03-19 15:21:35,471 INFO 46 [ClusterClient#Watcher] gives up seizing port 57087, and serves as follower client.
[INFO] 2017-03-19 15:21:35,479 INFO 40 Use coreMiddleware order: ["meta","siteFile","notfound","static","bodyParser","session","i18n","securities"]
[INFO] 2017-03-19 15:21:35,479 INFO 40 Use appMiddleware order: []
[INFO] 2017-03-19 15:21:35,481 INFO 40 [egg:loader] Use middleware: meta
[INFO] 2017-03-19 15:21:35,481 INFO 40 [egg:loader] Use middleware: siteFile
[INFO] 2017-03-19 15:21:35,569 INFO 40 [egg:loader] Use middleware: notfound
[INFO] 2017-03-19 15:21:35,570 INFO 40 [egg-static] starting static serve /public/ -> /home/leanengine/app/app/public
[INFO] 2017-03-19 15:21:35,571 INFO 40 [egg:loader] Use middleware: static
[INFO] 2017-03-19 15:21:35,572 INFO 40 [egg:loader] Use middleware: bodyParser
[INFO] 2017-03-19 15:21:35,573 INFO 40 [egg:loader] Use middleware: session
[INFO] 2017-03-19 15:21:35,573 INFO 40 [egg:loader] Use middleware: i18n
[INFO] 2017-03-19 15:21:35,575 INFO 40 [egg-security] use csrf middleware
[INFO] 2017-03-19 15:21:35,576 INFO 40 [egg-security] use methodnoallow middleware
[INFO] 2017-03-19 15:21:35,576 INFO 40 [egg-security] use noopen middleware
[INFO] 2017-03-19 15:21:35,577 INFO 40 [egg-security] use nosniff middleware
[INFO] 2017-03-19 15:21:35,578 INFO 40 [egg-security] use xssProtection middleware
[INFO] 2017-03-19 15:21:35,579 INFO 40 [egg-security] use xframe middleware
[INFO] 2017-03-19 15:21:35,579 INFO 40 [egg-security] compose 6 middlewares into one security middleware
[INFO] 2017-03-19 15:21:35,579 INFO 40 [egg:loader] Use middleware: securities
[INFO] 2017-03-19 15:21:35,579 INFO 40 [egg:loader] Loaded middleware from ["/home/leanengine/app/node_modules/egg-onerror/app/middleware","/home/leanengine/app/node_modules/egg-session/app/middleware","/home/leanengine/app/node_modules/egg-i18n/app/middleware","/home/leanengine/app/node_modules/egg-watcher/app/middleware","/home/leanengine/app/node_modules/egg-multipart/app/middleware","/home/leanengine/app/node_modules/egg-securi ✗ app/middleware","/home/leanengine/app/node_modules/egg-schedule/app/middleware","/home/leanengine/app/node_mod
 ✗ 应用启动失败: 无法访问应用的 Web 端口（connect ECONNREFUSED 10.10.227.131:54583），请确保程序正确启动了 HTTP 服务
 ✗ 新建实例已被移除
 ✗ 应用启动失败: 无法访问应用的 Web 端口（connect ECONNREFUSED 10.10.227.131:54583），请确保程序正确启动了 HTTP 服务
 ✓ 部署完成：发生了 1 个错误

**Comment by jtyjty99999** [comment]
错误日志里 端口为什么是54583，是leancloud的约定吗？

**Comment by chenmingjia** [comment]
应该不是约定，这个端口，每次部署都会改变，之前没用框架好像没有这问题

**Comment by jtyjty99999** [comment]
https://leancloud.cn/docs/leanengine_webhosting_guide-node.html#Express  仔细看下文档。 leancloud需要你的框架启动端口依赖leancloud的环境变量的启动端口。把egg的启动端口指向 process.env.LEANCLOUD_APP_PORT 这个环境变量。

**Comment by popomore** [comment]
去看看 leancloud 文档吧，他健康检查是怎么做的。是不是可以指定端口？

PeterChen <notifications@github.com>于2017年3月19日 周日16:33写道：

**Comment by chenmingjia** [comment]
哦，多谢，是我没仔细看

**Comment by atian25** [comment]
要指定端口的

```js
require('egg').startCluster({
   port: process.env.LEANCLOUD_APP_PORT || process.env.POST || 7001,
})
```

**Comment by atian25** [comment]
另外，还需要做下 EGG_SERVER_ENV 的适配，leancloud 有自己的一个 ENV 来表达线上服务器类型
