### ISSUE TITLE
egg-sequelize的信息配置好了连不上。

### ISSUE THREAD

**Issue by liuliangjia** [eggjs/egg#600]
config.default.js内容如下：

```js
exports.sequelize = {
  dialect: 'mysql',
  host: '192.168.0.132',
  port: '3306',
  database: 'mp3',
  username: 'root',
  password: '123456'
};
```

plugin.js内容如下：

```js
exports.sequelize = {
  enable: true,
  package: 'egg-sequelize'
}
```

错误如下：
```bash
2017-03-20 14:08:44,524 ERROR 1172 nodejs.SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
```

我配置的192.168.0.132好像没起作用？

**Comment by huacnlee** [comment]
我记得合并配置有测试覆盖验证过的呀

**Comment by liuliangjia** [comment]
如果是egg-mysql就可以正确连接，是不是sequelize的配置连接信息有不同写法？

**Comment by huacnlee** [comment]
我测试了一下，配置是有效的：

config.default.js

如下，我故意改成一个错误的地址

```js
'use strict';

module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1489992261949_206';

  config.sequelize = {
    dialect: 'mysql',
    host: '192.168.0.132',
    port: '3306',
    database: 'mp3',
    username: 'root',
    password: '123456'
  };


  return config;
};
```



<img width="1184" alt="2017-03-20 2 56 39" src="https://cloud.githubusercontent.com/assets/5518/24090701/a22c737c-0d7d-11e7-80cb-def63cbc36d4.png">

**Comment by liuliangjia** [comment]
这个没问题了，是我把这一段代码写在 config外边了：

按您写配置的位置就没问题了，不过您的项目egg-sequelize好像是另外一种配置方法？即我原来贴的那样。

有时候我会用sequelize的原始查询功能，直接执行SQL语句，请问应该如何调用？

var query=yield app.Sequelize.query('SELECT * FROM mp3');   //返回查询数据
