### ISSUE TITLE
运行一段时间后就worker就会一个个的死掉

### ISSUE THREAD

**Issue by beginnor** [eggjs/egg#602]
运行一段时间后就worker就会一个个的死掉，麻烦请问下如何排查和解决，谢谢
worker:9056 exit (code: 1, suicide: true, state:
dead, isDead: true, isExpected: true)
2017-03-20 15:00:30,303 ERROR 5468 nodejs.AppWorkerDiedError: [master] App Worker#2:9056 died (code: 1, signal: 1, suici
de: true, state: dead), current workers: []

**Comment by dead-horse** [comment]
有没有其他的错误日志以及复现代码

**Comment by atian25** [comment]
提供一个最小化可复现代码上传到 GitHub 吧

**Comment by beginnor** [comment]
公司的代码，没法上传，就是在win下执行一些定时任务

**Comment by atian25** [comment]
定时任务里面是不是有未捕获异常

**Comment by beginnor** [comment]
那到是经常会有错误，
是不是需要在
`* task(ctx) {
         console.log("定时任务 test 执行");
    },` 这里边try catch 就可以

**Comment by atian25** [comment]
那肯定...

**Comment by beginnor** [comment]
多谢，我试下

**Comment by dead-horse** [comment]
@atian25 task 默认会做 try catch，不会退出进程的， @beginnor 给详细的错误信息吧，这里只看到了 worker 退出，没有看到真正异常的日志。

**Comment by beginnor** [comment]
问题解决了，是定时任务调用的自己封装的promise方法中 ,在 reject 外部抛了异常而没有捕获，已经在 promise 最外层加了try catch 。 谢谢 你们 @dead-horse  @atian25
