### ISSUE TITLE
egg-mysql 打印sql语句

### ISSUE THREAD

**Issue by luyongfugx** [eggjs/egg#603]
如何配置让 egg-mysql 打印出sql语句，现在比较难调试

**Comment by atian25** [comment]
配置里面加一个 `debug: true` 试试

```js
client: {
  host: 'host',
  debug: true,
}
```

**Comment by okoala** [comment]
如果是开发环境也可以通过设置 DEBUG 环境变量来打开插件debug日志信息~
Mac：export DEBUG=ali-rds*
Win： set DEBUG=ali-rds*

**Comment by luyongfugx** [comment]
client: {
  host: 'host',
  debug: true,
}

**Comment by luyongfugx** [comment]
client: {
  host: 'host',
  debug: true,
}

**Comment by luyongfugx** [comment]
client: {
  host: 'host',
  debug: true,
}  

这种方式打的日志太多了，先直接在 ali-rds里console.log出来先了，在ali-rds里的lib/client.js里面加个
proto._query = function (sql) {
  console.log('ali-rds exec sql:'+sql);
  let pool = this.pool;
  return function (callback) {
    pool.query(sql, function (err, rows) {
      callback(err, rows);
    });
  };
};

**Comment by atian25** [comment]
@luyongfugx 可以去分析下 https://github.com/mysqljs/mysql 的源码，看看那那里有没有对应的 DEBUG 的输出，如 @okoala 说的，开下具体的环境变量就 OK 了。

**Comment by luyongfugx** [comment]
@atian25  好的，多谢
