### ISSUE TITLE
关于默认命名规范的问题

### ISSUE THREAD

**Issue by beginnor** [eggjs/egg#606]
Controller 和 service 中 文件名中如果带 _  程序中无法取到，请问这是框架约定的吗？有没有其它约定的编码规范，3ks

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/advanced/loader.html#文件加载规则

**Comment by atian25** [comment]
`news_list -> newsList`

**Comment by beginnor** [comment]
感谢，看来得抽空把doc详细看一遍了，哈哈
