### ISSUE TITLE
gzip 中间件,编写那里出错了。

### ISSUE THREAD

**Issue by next2014** [eggjs/egg#610]
![jietu20170321-181730](https://cloud.githubusercontent.com/assets/7641722/24142846/d41f01c0-0e62-11e7-936d-e1c631a25eb9.jpg)

**Comment by LeoYuan** [comment]
虽然个人很不赞成这种不加{}的写法，但是上边的代码应该是正常的~

**Comment by atian25** [comment]
你这个是 eslint 的提示吧?

如果是报错, 麻烦把报错信息贴出来

**Comment by next2014** [comment]
已经知道那里错误了，就是if后面的“(”是中文的
