### ISSUE TITLE
egg-bin dev出了什么问题？

### ISSUE THREAD

**Issue by next2014** [eggjs/egg#611]
![jietu20170321-222419](https://cloud.githubusercontent.com/assets/7641722/24152228/ff18a142-0e85-11e7-88ce-d74dbd25ce8c.jpg)

**Comment by atian25** [comment]
复现步骤？
删除 node module 再安装看看？

**Comment by dead-horse** [comment]
需要进到具体的某个 example 子目录下，然后先安装依赖，再执行 npm run dev 或者  npm run start

**Comment by atian25** [comment]
@dead-horse 可以在根目录的 `npm run dev` 加一个 echo~

**Comment by halower** [comment]
我也出现了这个问题，跑不起来，显然不是具体子目录的问题

**Comment by atian25** [comment]
去到子目录执行。 examples 项目是一个合集，要单个看

**Comment by dead-horse** [comment]
```bash
$ git clone git@github.com:eggjs/examples.git && cd examples
$ cd hackernews
$ npm install
$ npm run dev
```
