### ISSUE TITLE
egg agent 需要考虑添加 error 事件

### ISSUE THREAD

**Issue by nightink** [eggjs/egg#612]
本地 agent 一直启动失败，并且无具体错误信息，只是 `exit 1` 提示。
经过排查发现项目引入未 install 模块导致触发 agent.js 异常

https://github.com/node-modules/ready-callback/blob/master/lib/ready.js#L63
https://github.com/eggjs/egg/blob/master/lib/agent.js#L34

会向外 emit 触发 error 但是目前 agent.js 并没有去监听该事件，导致错误信息并没有被打出

**Comment by popomore** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/agent_worker.js#L23

已经解决了

**Comment by nightink** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/agent_worker.js#L23

**Comment by nightink** [comment]
https://github.com/eggjs/egg-cluster/blob/master/lib/agent_worker.js#L25

并没有把错误打印出来呢。也不知道是哪个 agent 弄错了
