### ISSUE TITLE
关于debug的文档？

### ISSUE THREAD

**Issue by elover** [eggjs/egg#616]
提一个小小的建议，关于debug这一块可以在官网上总结一篇文档，毕竟，每个开发者肯定都需要debug的，感觉目前这一块还比较麻烦，尤其是怎么集成到WebStorm的debug？

**Comment by atian25** [comment]
刚重构完 egg-bin，晚点我再写下，其实就几个截图

**Comment by elover** [comment]
chrome的调试已经ok了，但是2017.1的WebStorm （node 7.7.2）好像没办法debug

**Comment by atian25** [comment]
刚测试了下，是可以的

- WebStorm 2017.1
- Node.js v7.7.4
- "debug": "egg-bin dev $NODE_DEBUG_OPTION",

不过要用 `egg-bin dev` 而不是 `egg-bin debug`，貌似 WebStorm 还不支持 `--inspect`，所以没法用后者，有兴趣的同学可以研究下怎么改。

**Comment by joyeecheung** [comment]
Web Storm 支持 `--inspect` 的……https://github.com/nodejs/nodejs.org/pull/1131#issuecomment-277961029

**Comment by atian25** [comment]
然而我试了没连 inspect
