### ISSUE TITLE
egg怎么做vue的服务端渲染 有案例吗

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#618]
* **Node Version**:
7.4
* **Egg Version**:
1.0.0
* **Plugin Name**:
vue
* **Plugin Version**:
2.0
* **Platform**:

**Comment by atian25** [comment]
内网有个插件，等迁移出来吧

**Comment by WangCao** [comment]
试试nuxt-egg

**Comment by wangking873** [comment]
https://github.com/wangking873/egg-next
仿照nuxt-egg(vue2同构,基于nuxt)  写了 egg-next(react同构，基于next)
demo https://github.com/wangking873/egg-next-demo

**Comment by popomore** [comment]
https://github.com/eggjs/egg-view-vue/pull/3

**Comment by hubcarl** [comment]
有工程示例：https://github.com/hubcarl/egg-vue-webpack-boilerplate
