### ISSUE TITLE
兼容 config.bodyparser 写法

### ISSUE THREAD

**Issue by maxming2333** [eggjs/egg#620]
* **Node Version**: 6.10.0
* **Egg Version**: undefined
* **Plugin Name**: koa-bodyparser
* **Plugin Version**: 2.4.0
* **Platform**: osx

In `config.js`

错误 :

```
exports.bodyparser = {
  formLimit: '1000mb',
  jsonLimit: '1000mb',
  textLimit: '1000mb',
};
```

正确 :

```
exports.bodyParser = {
  formLimit: '1000mb',
  jsonLimit: '1000mb',
  textLimit: '1000mb',
};
```

但是 [koa-bodyparser](https://github.com/koajs/bodyparser) 插件名是小写，能否做兼容？

**Comment by fengmk2** [comment]
支持，应该兼容一下

**Comment by dead-horse** [comment]
我会写一篇文档把内置的中间件和插件的配置都列一下

**Comment by dead-horse** [comment]
这个我在考虑，可能打一个 warning 会比较好一点，做这个兼容意义不大，增加后期维护成本（因为 egg 默认的配置写在了 bodyParser，所以要合并 bodyParser 和 bodyparser 的配置项）

**Comment by maxming2333** [comment]
我觉得把 默认中间件，默认中间件配置，默认插件，默认插件配置，全部列出来，比较好一点，比如在官网上建一个列表页面，专门陈列这些默认组件滴，这样用户可以一清二楚
