### ISSUE TITLE
doc: 页面配置写错了

### ISSUE THREAD

**Issue by maxming2333** [eggjs/egg#630]
* **Node Version**: 6.10.0
* **Egg Version**: undefined
* **Plugin Name**: koa-bodyparser
* **Plugin Version**: 2.4.0
* **Platform**: osx

页面：https://eggjs.org/zh-cn/basics/controller.html#body

bodyParser  配置 应该是 `mb` 而不是 `m`

![image](https://cloud.githubusercontent.com/assets/8816730/24245020/2ae344e0-0ffc-11e7-8d67-6e5327b269e9.png)

**Comment by rccoder** [comment]
刚想提来着 😂

**Comment by atian25** [comment]
@maxming2333 next time, just raise a PR~

**Comment by maxming2333** [comment]
好滴
