### ISSUE TITLE
ctx.respond is undefined  无法使用node 原生res

### ISSUE THREAD

**Issue by hdfs010** [eggjs/egg#631]
关闭只是想测试原生nodejs  res.write(); res.end();感谢各位热心解答。

**Comment by popomore** [comment]
请问你想达到什么目的

**Comment by ngot** [comment]
看起来是陈述句，并不是问句。是要提意见吗？

**Comment by atian25** [comment]
我感觉是想用旧时代 express 类的中间件，然后在哪里看到的 Koa 教程教怎么兼容？

**Comment by hdfs010** [comment]
就是想用原生的  分段输出数据流！不过现在 可以了 但是 通过下面的方式！但是有出现一个问题，感觉这个问题不应该出现。

// app/controller/home.js
/*
http://koa.bootcss.com/#context
ctx.respond

为了避免使用 Koa 的内置响应处理功能，您可以直接赋值 this.respond = false;。如果您不想让 Koa 来帮助您处理 reponse，而是直接操作原生 res 对象，那么请使用这种方法。

注意： 这种方式是不被 Koa 支持的。其可能会破坏 Koa 中间件和 Koa 本身的一些功能。其只作为一种 hack 的方式，并只对那些想要在 Koa 方法和中间件中使用传统 fn(req, res) 方法的人来说会带来便利。
*/
module.exports = app => {

  class HomeController extends app.Controller {
    * index() {

        //this.ctx.body = 'Hello world';
        /*
      	this.respond = false;
      	var req     = this.req;
      	var res     = this.res;*/


	    this.ctx.res.writeHead(200, {'Content-Type': 'text/html;charset=UTF-8'});
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.write('content1</br>');
	    this.ctx.res.end('');
	    
    



    }
  }


  return HomeController;
};


以上方式可以解决，但是一个这样的错误 ，我觉得不因该出现才是 ，这是一个正常的输出方式。

7-03-23 23:13:30,800 INFO 12410 [master] egg started on http://127.0.0.1:7001 (834ms)
{ '0': 'x-frame-options', '1': 'SAMEORIGIN' }
x-frame-options
SAMEORIGIN
2017-03-23 23:17:48,919 ERROR 12412 [-/127.0.0.1/-/11ms GET /] nodejs.Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at Object.set (/Users/miSter/SpringBootShop/coreapp/node_modules/koa/lib/response.js:439:16)
    at Object.proto.(anonymous function) [as set] (/Users/miSter/SpringBootShop/coreapp/node_modules/delegates/index.js:40:31)
    at Object.xframe (/Users/miSter/SpringBootShop/coreapp/node_modules/egg-security/lib/middlewares/xframe.js:16:10)
    at xframe.next (<anonymous>)
    at onFulfilled (/Users/miSter/SpringBootShop/coreapp/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:109:7)
headerSent: true
pid: 12412
hostname: bogon
输出完在设置头感觉不靠谱，这 是一个很正的异步输出方式。


  /**
   * Set header `field` to `val`, or pass
   * an object of header fields.
   *
   * Examples:
   *
   *    this.set('Foo', ['bar', 'baz']);
   *    this.set('Accept', 'application/json');
   *    this.set({ Accept: 'text/plain', 'X-API-Key': 'tobi' });
   *
   * @param {String|Object|Array} field
   * @param {String} val
   * @api public
   */

  set: function(field, val){
    if (2 == arguments.length) {
      if (Array.isArray(val)) val = val.map(String);
      else val = String(val);

      **this.res.setHeader(field, val);**
    } else {
      for (var key in field) {
        this.set(key, field[key]);
      }
    }
  },

**Comment by ngot** [comment]
你把语言整理一下，到底什么问题？

**Comment by popomore** [comment]
给 body 传一个 stream 就好了。

**Comment by thonatos** [comment]
next.js 的 render 调用了ctx.res.end()，如果想兼容貌似需要 ctx.respond 支持
