### ISSUE TITLE
apache反向代理静态资源找不到

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#639]
* **Node Version**:
v7.4
* **Egg Version**:
1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
apache

因为就项目原因 使用作为apache反向代理 
<virtualHost *:80>
 <Location /study>
    ProxyPass http://127.0.0.1:7001
 </Location>
</virtualHost>
页面能出来 但是静态资源文件如js找不到 静态资源已使用相对路径 public/xx.js

**Comment by qietujiang** [comment]
你好！请问你这问题解决了吗？我也遇到了同样的问题？
