### ISSUE TITLE
apache反向代理 404不能跳转

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#640]
* **Node Version**:
v7.4
* **Egg Version**:
v1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
apache

config.notfound = {
  pageUrl : 'public/404.html'
}
如果写绝对路径 可以跳转https://xxx.com/public/404.html 但不符合需求
如果写相对路径 就直接跳转到https://xxx.com 求帮助

**Comment by jinchaoxiang** [comment]
刚刚又测了一下 貌似必须要用绝对路径 才能生效
如果用了反向代理 是不是错误配置页面资源就要放在代理服务器上了

**Comment by popomore** [comment]
是否希望这样 https://xxx.com/404.html -> localhost/public/404.html 

应该是你反向代理的问题，pageUrl 设为想跳转的绝对路径就好了。

**Comment by jinchaoxiang** [comment]
你是说我要为https://xxx.com/404.html额外设反向代理？
