### ISSUE TITLE
egg-mysql 执行任何查询都不返回结果，日志里也不报错

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#647]
* **Node Version**: 7.7.4
* **Egg Version**: 1.0.0
* **Plugin Name**: egg-mysql
* **Plugin Version**: 2.0.0
* **Platform**: windows 7 sp1 x64

**Comment by Andiedie** [comment]
请给出具体代码

**Comment by justinli0709** [comment]
async getUserByName(username) {
            const user = await app.mysql.get('admin_user', {
                user_id: 1,
            });
            console.log(username);
            console.log(user);
            return user;
        }

let test = await app.mysql.query('select * from admin_user where user_id = ?', [username]);

**Comment by justinli0709** [comment]
我发现不管SQL语句是对的还是错的，都不报错，实际上没有执行？

另外如果把MYSQL配置文件注释掉，会报错

host改成一个不存在的地址，也不报错

控制台看不到任何信息

**Comment by justinli0709** [comment]
请问如何开始trace？

**Comment by justinli0709** [comment]
一个新项目准备使用egg。。。

打算试试egg-mysql 但是卡在这里动不了，好尴尬。

**Comment by Andiedie** [comment]
#544 
参考这个问题
原因是: egg-mysql包装了ali-rds
后者不支持promise所以不能使用async/await

一个解决方法是 用co包装
```js
// app.js
const co = require('co');
module.exports = app => {
  app.beforeStart(async () => {
      ['insert', 'get', 'select', 'update', 'delete', 'query'].forEach(func => {
        app.mysql[func] = co.wrap(app.mysql[func]);
      });
    });
};

```

**Comment by justinli0709** [comment]
好的，明白了。

多谢！

**Comment by atian25** [comment]
@dead-horse should we wrap promise or add description at README?

**Comment by WangCao** [comment]
我也是怎么也调不到mysql，原来是用了async/await的原因，这问题应该在文档中特别强调或者修正下！！

**Comment by dead-horse** [comment]
@WangCao https://eggjs.org/zh-cn/tutorials/async-function.html#调用-generator-function-api

**Comment by dead-horse** [comment]
mysql 的文档我也加一下

**Comment by dead-horse** [comment]
已经在 ali-rds 层做了改造，支持直接 await 调用了

**Comment by dead-horse** [comment]
重新安装依赖即可

**Comment by atian25** [comment]
上面那个文档要干掉么

**Comment by WangCao** [comment]
@dead-horse 效率真高！

**Comment by dead-horse** [comment]
文档先别干掉，肯定还有其他插件有 generator function 的接口的，看到再改吧

**Comment by justinli0709** [comment]
@dead-horse 更新ali-rds@2.7.0 还是不行 暂时用@Andiedie的办法用co包装解决的

**Comment by dead-horse** [comment]
报错信息或者可复现代码提供一下。 @justinli0709

**Comment by dead-horse** [comment]
@justinli0709 知道了，稍等我修复一下

**Comment by whwnow** [comment]
我也遇到这个问题了，egg-mysql@3.0.0 ali-rds@3.0.0，await返回值是undefined。不是已经修复了么？
