### ISSUE TITLE
egg-mysql 如何像sequelize一样打印执行的SQL日志?

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#648]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by jtyjty99999** [comment]
这个feature我来弄一下吧

**Comment by justinli0709** [comment]
多谢

**Comment by 270034480** [comment]
@jtyjty99999 请问这个功能搞定了吗？

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-rds/pull/104
