### ISSUE TITLE
egg-sequelize 如何使用 sequelize-cli?

### ISSUE THREAD

**Issue by seasonstar** [eggjs/egg#651]
我定义好了一些model，想让sequelize在数据库里自动生成表，该怎么做？
看到sequelize上有个cli命令行接口，但是初次使用sequelize，还是基于egg的，没经验不会用啊~
似乎ctx.model.XXX.sync({force:true})也无效，没有看到同步创建模型到数据库了

求出一个教程

**Comment by dead-horse** [comment]
这个求助 sequelize 社区会比较快
