### ISSUE TITLE
因为要自己的内部服务 要调用系统的接口 但是出于csrf的安全机制 无法请求 有没有办法按ip做过滤限制的？

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#652]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
后续会将 security 插件的 ignore 和 match 改造成可以支持 function 来做动态判断。

**Comment by jtyjty99999** [comment]
现在可以写到middleware里，插入到securities中间件之前，覆盖配置就好了

**Comment by dead-horse** [comment]
egg-security 已经改好了， @zackCzy 重新安装 egg 就可以了

```js
// config/config.default.js

exports.security = {
  csrf: {
    // ignore 可以设置为一个方法，接受的第一个参数为请求的上下文
    ignore: ctx => isInnerIps(ctx.ip),
  }
}
```
