### ISSUE TITLE
关于egg-logger一个改进建议

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#653]
有人邮件问的

> eggjs的官方插件egg-logger在github上没有issues功能，所以就直接给你发邮件了。
>
> 测试了一下，用egg-logger写日志文件，15MB共100万条数据花了7s多，还有改进空间。具体措施是修改file.js（\lib\transports\file.js）中的_write方法，你们的源代码仅仅是调用了this._stream.write方法，并没有检测这个调用的返回值，当这个函数返回false的时候，表示缓存用光，后续不能再调用write方法，直到drain事件触发，所以建议你们自己维护一个缓存，当write返回false之后，调用_write不是调用write而是写在缓存里，drain事件触发后将缓存的内容一次写入并清空缓存。
>
> 按照上面的方案改写你们的代码后，写入15MB共100万条数据只用了1.7s，当然我自己写的logger程序可以在1s内完成，所以我想如果可以的话你们的性能还能继续提高。

**Comment by atian25** [comment]
cool

**Comment by shaoshuai0102** [comment]
cool 有空我搞一下

**Comment by fengmk2** [comment]
我们默认不是有缓存么？

**Comment by shaoshuai0102** [comment]
你说的是 fileBuffer 吧  他好像用了 file

**Comment by shaoshuai0102** [comment]
@popomore 发邮件的同学有 github 么，at 一下。

**Comment by popomore** [comment]
@shaoshuai0102 不知道是谁

**Comment by shaoshuai0102** [comment]
写入完成时间对比：

```bash
➜  egg-logger git:(perf) ✗ node benchmark/perf/file.js - 直接 write
16910
➜  egg-logger git:(perf) ✗ node benchmark/perf/file_improve.js - 等待 drain
9427
➜  egg-logger git:(perf) ✗ node benchmark/perf/file_buffer.js - 定时写入
7062
➜  egg-logger git:(perf) ✗ node benchmark/perf/file_buffer_improve.js - 定时写入，且等待 drain
6908
```

确实等待 drain 是有性能提升的。


猜测原因是如果生产者产生日志的速度大于写入磁盘速度的时候，writable stream 会把数据先放到 internal buffer。而 internal buffer 是一个链表类似的结构，操作速度上不如我们自己维护一个 array，且我们堆积的数据写入时使用了，arr.join() 一次写入，无需挨个处理。

https://github.com/nodejs/node/blob/master/lib/_stream_writable.js#L327

**Comment by popomore** [comment]
这个不搞了，统一到 https://github.com/eggjs/egg/issues/57
