### ISSUE TITLE
EGG 的httpclient 模块 支持使用代理ip 请求的吗？ 找不到相关的参数设置

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#655]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
https://github.com/node-modules/urllib/pull/226

**Comment by atian25** [comment]
httpclient 的底层是 https://www.npmjs.com/package/urllib

如果是本地调试的话，可以用下这个插件 https://github.com/eggjs/egg-development-proxyagent/blob/master/app.js

或者参考插件里面 app.js 的处理方式配置 agent
