### ISSUE TITLE
Egg-seuqlize 如何做 migration? (最好有结合或不结合 seuqlize-cli 的例子)

### ISSUE THREAD

**Issue by yandongxu** [eggjs/egg#656]
sequelize-cli 会依赖一些配置, 生成之后会把目录结构搞的很丑，虽然 .sequelizerc 可以修改配置的路径，但想知道有没有什么其它更优雅的方式

**Comment by popomore** [comment]
现在 egg 还没有 migration 方案，如果你有什么建议可以在这里提一下。

cc @huacnlee 是不是有做过

**Comment by huacnlee** [comment]
我们内部用 sequelize-cli 的方式可以参考一下:

1. package.json 增加 sequelize-cli 的依赖；
2. 新建 Makefile 用于准备 Migration 的几个命令；
3. 数据库配置信息，用户 ENV 的方式传递给 sequelize-cli
4. 目前仅在开发环境用它，两个原因：我们的公司流程只能在开发环境动数据结构， sequelize-cli 还存在一些 Bug，不敢在生产环境用

Makefile 文件参考:

```makefile
SEQUELIZE = node_modules/sequelize-cli/bin/sequelize
DATABASE_DEV_URL = "mysql://root:@127.0.0.1/lark2-dev"
DATABASE_TEST_URL = "mysql://root:@127.0.0.1/lark2-test"
NODE_ENV = $(shell echo $$NODE_ENV)

migrate:
ifeq ($(NODE_ENV),test)
	$(SEQUELIZE) db:migrate --url $(DATABASE_TEST_URL)
else
	@$(SEQUELIZE) db:migrate --url $(DATABASE_DEV_URL)
	$(SEQUELIZE) db:migrate --url $(DATABASE_TEST_URL)
endif
rollback:
ifeq ($(NODE_ENV),test)
	@$(SEQUELIZE) db:migrate:undo --url $(DATABASE_TEST_URL)
else
	@$(SEQUELIZE) db:migrate:undo --url $(DATABASE_DEV_URL)
	@$(SEQUELIZE) db:migrate:undo --url $(DATABASE_TEST_URL)
endif
migrate_new:
	@$(SEQUELIZE) migration:create --url $(DATABASE_URL)
```

**Comment by limichange** [comment]
@huacnlee 谢谢你的回复。所以不提倡使用sequelize-cli是吗？那么维护数据结构可以用什么其他的工具呢，或者是直接手动维护？

**Comment by yandongxu** [comment]
@huacnlee 十分感谢, 思路理清了. 手写 model 和 migration, 用 cli 执行 migrate.

然后遇到另一个问题, seuqlieze-cli 读取的配置是包含不同环境的, 如下:
```
'development': { ... },
'production': { ... }
```

有没有办法让他直接读取 config.default.js 中 sequelize 的配置? 我就不需要再单独给 sequelize 写一个配置了.

我尝试在 .sequelizerc 中修改, 但没有任何效果, 其中的 config 读取的是文件路径, 求大神解答.

**Comment by huacnlee** [comment]
@yandongxu 结构不同，暂时没有

我的 Makefile 的例子就有了解决方法，用 ENV

**Comment by yandongxu** [comment]
我做了个例子，不怎么优雅 @huacnlee @popomore 
https://github.com/yandongxu/egg-sequelize-demo

**Comment by huacnlee** [comment]
@yandongxu 来，给 egg-sequelize 提交 PR

**Comment by yandongxu** [comment]
@huacnlee 主要是依赖不同环境的配置文件，不知道怎么能做到独立一点才放到插件里

**Comment by callmesoul** [comment]
@yandongxu @huacnlee 我也在用egg-sequelize，目前手动管理，希望能尽快pr到egg-sequelize，方便管理，谢谢。

**Comment by atian25** [comment]
@yandongxu 提出你的方案，写点伪代码，参考之前我们的 RFC，大家一起脑爆

**Comment by huacnlee** [comment]
@atian25 需要往 egg-init 增加 sequelize 的模版才好解决，因为 package.json 需要增加内容，也需要几个默认文件

**Comment by atian25** [comment]
写个单独的 boilerplate 就好了?

**Comment by huacnlee** [comment]
是可以这么干
-- 
李华顺 (Jason Lee) <http://huacnlee.com>
----------------------------------------
http://huacnlee.com
http://twitter.com/huacnlee
http://github.com/huacnlee

**Comment by jtyjty99999** [comment]
使用cli的方式可以先加到文档里，配置一下 package.json ，安装一个 devdependence 应该就可以搞定了，附带的make文件可以在安装 cli 工具的时候写到项目目录上

**Comment by popomore** [comment]
@huacnlee 你来跟新下 egg-sequelize 文档关掉这个 issue 吧。

**Comment by huacnlee** [comment]
已解决，egg-sequelize@2.1.0 

并参阅 https://github.com/eggjs/egg-sequelize 的说明文档
