### ISSUE TITLE
生产环境下启动程序，报 app.mysql.select is not a function的错误

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#657]
我在生产环境配置好了数据库信息，然后访问本机ip+7001地址，报了一个app.mysql.select is not a function的错误。在本地开发模式下是不存在这个问题的，为什么呢？

* **Node Version**:>=6.0.0
* **Egg Version**:1.0.0
* **Plugin Name**: "egg-mysql": 
* **Plugin Version**:"^2.0.0",

配置 config.prod.js
     module.exports.mysql = {
 
  client: {
   
    host: '本机IP',
    
    port: '3306',

    user: 'root',
  
    password: '123456',
  
    database: 'world',
  },
  // 是否加载到 app 上，默认开启
  app: true,
  // 是否加载到 agent 上，默认关闭
  agent: false,
};
插件：
module.exports = {
  mysql: {
    enable: true,
    package: 'egg-mysql',
  },
};

service 层代码
find() {
				// 假如 我们拿到用户 id 从数据库获取用户详细信息
				const user = yield this.app.mysql.select('city', {});
				return {
					user,
				};
controller层
   exports.info = function*(ctx) {
	const user = yield ctx.service.selectall.find();
	ctx.body = user;
 };

**Comment by dead-horse** [comment]
错误堆栈回复一下，另外可以试试打印出来 app.mysql 看看是什么对象，app.config.mysql 运行时的配置是什么。

**Comment by leonardodream** [comment]
@dead-horse  您好？这个是错误堆栈么？？errorlog文件
 2017-03-27 14:24:22,463 ERROR 3352 [-/127.0.0.1/-/6ms GET /user/selall] nodejs.TypeError: this.app.mysql.select is not a function
    at User.find (E:\eggprod\my-egg\app\service\selectall.js:6:39)
    at next (native)
    at onFulfilled (E:\eggprod\my-egg\node_modules\co\index.js:65:19)
    at E:\eggprod\my-egg\node_modules\co\index.js:54:5
    at Object.co (E:\eggprod\my-egg\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\eggprod\my-egg\node_modules\co\index.js:118:63)
    at next (E:\eggprod\my-egg\node_modules\co\index.js:99:29)
    at onFulfilled (E:\eggprod\my-egg\node_modules\co\index.js:69:7)
    at E:\eggprod\my-egg\node_modules\co\index.js:54:5
    at Object.co (E:\eggprod\my-egg\node_modules\co\index.js:50:10)

pid: 3352
hostname: DESKTOP-5MUS3N3

**Comment by leonardodream** [comment]
{
  "clients": {},
  "app": {
    "env": "local",
    "name": "my-egg",
    "baseDir": "E:\\eggprod\\my-egg",
    "subdomainOffset": 2,
    "config": "<egg config>",
    "controller": "<egg controller>",
    "serviceClasses": "<egg serviceClasses>",
    "middlewares": "<egg middlewares>",
    "httpclient": "<egg httpclient>",
    "loggers": "<egg loggers>"
  },
  "name": "mysql",
  "options": {
    "default": {
      "database": null,
      "connectionLimit": 5
    },
    "app": true,
    "agent": false
  }
}

**Comment by dead-horse** [comment]
从你打的 options 看，并没有设置对 mysql.client 这个选项，你的 env 是  `local`，但是配置写的是`config.prod.js` ，你需要启动时设置环境变量 `EGG_SERVER_ENV=prod npm start`

```js
"options": {
  "default": {
    "database": null,
    "connectionLimit": 5
  },
  "app": true,
  "agent": false
}
```

**Comment by itmuse** [comment]
我也遇到该问题了，是怎么解决的呢？

**Comment by atian25** [comment]
检查你的 config
