### ISSUE TITLE
配置mongo的方法，官方文档写的不明白

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#659]
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_lixue';

  config.mongoose = {
    url: 'mongodb://127.0.0.1/blockdb',
    options: {}
  };

  return config;
};

**Comment by popomore** [comment]
哪里不明白呢？

**Comment by buzai** [comment]
@popomore 
官方直接写的是：
exports.mongoose = {
  enable: true,
  package: 'egg-mongoose',
};
代码粘帖上去是会报错的，我写的这个是我自己猜出来的这么写。

而且应该是 yield this.ctx.model  ，你们写成了 yield this.model 。。。
我觉得是不对的，希望你们更新一下说明部分

**Comment by popomore** [comment]
文档上的注释有提示路径，你上面写的是 plugin.js 的，配置在 https://github.com/eggjs/egg-mongoose#configuration

**Comment by popomore** [comment]
controller 有两种写法，都可以的 https://eggjs.org/zh-cn/basics/controller.html#如何编写-controller

**Comment by buzai** [comment]
～～～～
config/config.default.js ：这里我是

module.exports = appInfo => {
const config = {};

// should change to your own
config.keys = appInfo.name + '_lixue';

config.mongoose = {
url: 'mongodb://127.0.0.1/blockdb',
options: {}
};

return config;
};

～～～～～
config/plugin.js：这里我是

exports.mongoose = {
  enable: true,
  package: 'egg-mongoose',
};


然后可以了。
但是：config/config.default.js ：如下的话就不对。
'use strict';
.mongoose = {
  url: 'mongodb://127.0.0.1/blockdb',
  options: {}
};
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_lixue';

  return config;
};
可能是我比较笨没看懂你们的意思。。。

**Comment by dead-horse** [comment]
先理解一下 node 的模块机制，exports 和 module.exports 分别是什么含义就知道了。

**Comment by buzai** [comment]
但是你们就是那么写的。。

**Comment by buzai** [comment]
而且 ctx里面绑定了model，这个不论你们controller是怎么写的，你们都没说明model在ctx里面。

**Comment by fengmk2** [comment]
> http://new-issue.vuejs.org:  最重要的是，请明白一件事：开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，不要期待我们单方面地为你服务。

**Comment by buzai** [comment]
@fengmk2 我是看教程遇到坑了，希望你们写明白这个东西，没有希望你们为我服务，希望后来的人不继续出错了啊

**Comment by atian25** [comment]
@buzai 在 QuickStart 那里我加一下说明，提醒开发者注意下 Controller 的写法，并阅读 Controller 文档。

其他插件的文档，我们还是倾向于写 exports 的方式，比较简单。

**Comment by dead-horse** [comment]
@buzai 你先去了解一些前置知识再来看这个文档就不会看不懂了，我们没有办法从零开始将所有知识都在一个文档里面全部说一遍。

**Comment by fengmk2** [comment]
好无语，如果你觉得没问题，没必要删除回复。

**Comment by buzai** [comment]
@fengmk2 感觉我又给祖国丢人了。。。还是删了的好

**Comment by okoala** [comment]
没必要删啊，不然完全看不懂上下文，下次有人过来查相同的信息都一脸懵逼~
