### ISSUE TITLE
如何在应用启动的时候指定环境变量

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#662]
在应用启动的时候指定环境变量，这句话写在哪啊？ 实在不该问这么弱的问题，但是我迷了很久了。大哥赏我一句指点吧    EGG_SERVER_ENV=prod npm start

**Comment by atian25** [comment]
启动命令行...

linux 和 mac 用 `EGG_SERVER_ENV=prod npm start`

win 的话, 好像是 `set EGG_SERVER_ENV=prod && npm start` 啥的，自己研究吧。。。 线上都是 linux。

**Comment by leonardodream** [comment]
谢大哥谢大哥
