### ISSUE TITLE
egg-validate 不能验证表单提交上来的整数

### ISSUE THREAD

**Issue by sunshinexb** [eggjs/egg#663]
当使用 this.validate(rule); 验证从表单提交上来的整数时由于表单提交的整数的是一个字符串，所以验证出错。
eg:
```javascript
const rule = {
    number: {type: 'int'}
};

this.validate(rule);
```
而表单提交的数据是

```javascript
{
number: '1111'
}
```
看了下 parameter的源码 
```javascript
function checkInt(rule, value) {
  if (typeof value !== 'number' || value % 1 !== 0) {
    return this.t('should be an integer');
  }

  if (rule.hasOwnProperty('max') && value > rule.max) {
    return this.t('should smaller than %s', rule.max);
  }

  if (rule.hasOwnProperty('min') && value < rule.min) {
    return this.t('should bigger than %s', rule.min);
  }
}
```
所有当从表单提交数据验证时验证不通过。
@fengmk2

**Comment by atian25** [comment]
你可以自定义一个  rule  type

发自我的 iPhone

**Comment by sunshinexb** [comment]
我就是这么干了 ,用了下面的正则。
```javascript
/^-?\d+$/.test(number)
```

**Comment by popomore** [comment]
所以解决了？

**Comment by dead-horse** [comment]
int 只检查 number 类型，你的数据是 string，所以要用正则

**Comment by sunshinexb** [comment]
我知道我的数据是string类型，但是在使用this.validate(rule);的时候this.request.query, this.request.body获取的数据不都是string类型吗？这样在使用下面的 type: 'int', type: 'number' ....还有什么意义呢？validate的意义不就是为了校验我前台传到后台数据的吗，如果我前台传了一个1, 框架认为他是一个字符串而不去校验，那type:'int'完全没有意义了 。
```
const rule = {
    number: {type: 'int'}
};

this.validate(rule);
```

**Comment by atian25** [comment]
你可以自定义一个 formInt

```js
app.validator.addRule('jsonString', (rule, value) => {
  try {
    JSON.parse(value);
  } catch (err) {
    return 'must be json string';
  }
});
```

**Comment by atian25** [comment]
this.request.body 是 post 上来的，当然可能是 int 啦

**Comment by sunshinexb** [comment]
我也是自定义了一个validate（如下） ,但是this.quest.body获取到数字被框架认为是一个string了，就像下面获取到的数据中sort一样。

```
{ id: '93bffd1ea717485f829a24b06c920bfa',
  name: '3424',
  image: a3.jpg',
  sort: '12' }
```

```
/**
     * 判断是否是数字
     */
    app.validator.addRule('intString', (rule, value) => {
        if (!/^-?\d+$/.test(value)) {
            return `必须输入一个整数`;
        }

        if (rule.hasOwnProperty('max') && value > rule.max) {
            return `不能大于${rule.max}`;
        }

        if (rule.hasOwnProperty('min') && value < rule.min) {
            return `不能小于${rule.min}`;
        }
    });
```

**Comment by dead-horse** [comment]
@sunshinexb 请让客户端通过 JSON 格式传递 body，这样才能保留原始的数据类型。

**Comment by xjchenhao** [comment]
```
$.ajax({
            type: "post",
            url: "CreateMall",
            data: { data: JSON.stringify(mall) },//非常重要的一步
            datatype: "json",
            success: function (data) {}
});
```

你好，请问是这个意思吗？感觉不是很方便啊，用类似postman之类工具做请求测试也不是很方便。
@dead-horse

**Comment by atian25** [comment]
你不需要自己 stringify，只需要你的  `mall` 这个对象里面的那个属性是 number 类型。

至于 POSTMAN
![image](https://user-images.githubusercontent.com/227713/29304521-09262dcc-81c6-11e7-9b94-221b57e466fa.png)

**Comment by xjchenhao** [comment]
谢谢，postman的请求能够提交成功了。

![image](https://user-images.githubusercontent.com/5373111/29304928-848138f2-81c8-11e7-9bf0-ed1eb9688ca7.png)

![image](https://user-images.githubusercontent.com/5373111/29305005-dba8ab06-81c8-11e7-9887-7b70c5c2f767.png)
![image](https://user-images.githubusercontent.com/5373111/29305020-ecd48c24-81c8-11e7-90a5-5678defbcc9f.png)

控制台打印`mall`，是区分string、namber的，但是通过ajax去提交数据，就不行了。

**Comment by atian25** [comment]
`$.ajax({ dataType: 'json' })` 

此类问题属于 http 基础知识和具体类库 API 问题.

**Comment by atian25** [comment]
`dataType: "json",`

**Comment by xjchenhao** [comment]
写了。。。

**Comment by atian25** [comment]
你写了全小写，此类问题属于 http 的基础知识，不属于 egg 的答疑范围。

**Comment by xjchenhao** [comment]
嗯嗯 谢谢答复～
