### ISSUE TITLE
egg-view-xtpl view path 不支持多级目录?

### ISSUE THREAD

**Issue by elover** [eggjs/egg#664]
egg-view-xtpl 按照官方配置，可以跑通。但是路径如果是2级的话就会报错。

```
yield this.ctx.render('hello/hello.xtpl', {
          data: 'world'
 })
```

报错信息：
![image](https://cloud.githubusercontent.com/assets/4330913/24367496/709ea744-134f-11e7-80f0-4ad1f123962f.png)

**Comment by dead-horse** [comment]
看起来有点像 `hello/hello.xtpl` 这个模板里面的错误，贴一下吧

**Comment by elover** [comment]
hello.xtpl 内容：

```
hello {{data}}
```

**Comment by elover** [comment]
想了解下，确认这块存在bug吗？

**Comment by atian25** [comment]
有可能，@ngot 看看

**Comment by ngot** [comment]
看保存信息，还没到xtpl逻辑，还在 egg-view那里就报错了。提供复现代码，我看下。

**Comment by ngot** [comment]
https://github.com/eggjs/egg-view-xtpl/pull/5

**Comment by ngot** [comment]
+ egg-view-xtpl@1.1.2
