### ISSUE TITLE
ant-design 不也是阿里巴巴的? 为啥看起来和egg不是很近呢?

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#665]
egg作为后端框架非常牛
ant.design 解决了管理端的标准和统一
mobile.design 解决了移动端的视觉统一

如果这三个东东结合起来是那么的完美!
可是感觉在egg的view里为啥没体现呢?
有谁用这种技术选型做过, 分享下吧朋友们

**Comment by atian25** [comment]
一个前端，一个后端，ant.design 支持 SSR 了？ 即使支持，直接用 egg-view-react 也可以了吧？

感觉就差一个 showcase example，cc @afc163 @jtyjty99999

**Comment by junmaqiang** [comment]
就是没有案例, 无法着手!   
官方有example的话就很棒了!
在ant.design底部还看到egg的链接呢, 官方出个案例吧!  非常期待!

**Comment by popomore** [comment]
可以看看这个 https://github.com/tvrcgo/egg-react-mobx-ts-antd

**Comment by afc163** [comment]
antd 是支持 ssr 的。

**Comment by junmaqiang** [comment]
![wx20170328-120500](https://cloud.githubusercontent.com/assets/1819457/24388673/d0505124-13ae-11e7-98ce-e2cad151647a.png)

嗯呢, 若是我自行研究出来的话,也会分享给大伙

@afc163   @atian25

**Comment by soulmachine** [comment]
@atian25 egg-view-react为啥一直是 work in progress 啊？现在写页面不想用模板引擎了，很想用react来写页面

**Comment by atian25** [comment]
@jtyjty99999 那边还在搞。

建议根据自己的业务场景去选型，不要盲目追新。在我们内部的实践中， SSR 一不小心还是非常容易内存泄露的。
