### ISSUE TITLE
egg-development 不支持自定义watch 目录

### ISSUE THREAD

**Issue by tangp1n** [eggjs/egg#669]
* **Node Version**: 6.10.0
* **Egg Version**: 0.7.0
* **Plugin Name**: egg-development
* **Plugin Version**: 1.2.0
* **Platform**: Mac OS X Sierra

egg-development 插件开启后，会默认watch /app 目录，但是我的应用在/app/public 下有大量的前端代码，node_modules 里文件过多导致watch 报错。这个错误来自egg-watch 插件里使用的'wt'，在文件过多时会触发这个错误。

```shell
2017-03-28 15:46 node[8835] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-03-28 15:46:57,715 ERROR 8835 nodejs.EMFILEError: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
code: 'EMFILE'
errno: 'EMFILE'
syscall: 'Error watching file for changes:'
filename: null
dir: '/Users/pin/work/projects/ubanner-portal/app/public/node_modules/.1.1.11@element-resize-detector/dist'
name: 'EMFILEError'
pid: 8835
hostname: tangpin-laptop.local
```

尽管这个插件提供了ignoreDirs 的配置，但是实际上仅是在ignoreDirs 目录下内容变化时不触发reload，如果内置的默认watch 目录中包含了它们（如app），插件仍然会watch 这些目录。

希望能够提供覆盖内置的watchDirs 目录的配置选项，让我手工指定watch app 目录下的哪些目录
```javascript
  const watchDirs = [
    'app',
    'config',
    'mocks',
    'mocks_proxy',
  ].concat(config.watchDirs).map(dir => path.join(baseDir, dir));
```

**Comment by atian25** [comment]
欢迎直接 PR~

**Comment by atian25** [comment]
研究了下，在 development 和 watcher 这层处理不了，需要修改 [wt.watchDir](https://github.com/node-modules/wt/blob/master/index.js#L174) 来支持 ignore。

又因 watcher 有两种实现：
- https://github.com/eggjs/egg-watcher
- https://github.com/eggjs/egg-watcher-chokidar

需要考虑到 ignore 参数的支持格式，然后分别兼容。

@fengmk2 怎么看?

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-development/blob/master/config/config.default.js#L10 watchDirs 不是有配置吗？

**Comment by atian25** [comment]
看 issue 正文。现在的实现方式是 watch 后 ignore，而不是直接不 watch

发自我的 iPhone

**Comment by fengmk2** [comment]
改成默认不watch `app` 目录，而是 watch 我们已知的 app 下的子目录。

**Comment by atian25** [comment]
@fengmk2 这样不好吧，插件扩展的 app/model , app/filter 之类的，没注意的话都会踩坑。

**Comment by okoala** [comment]
egg-development 添加文件过滤吧？  比如说现在 app 下有 ts 和 js 的文件，每次写 ts 的时候都会刷新两次, 有点不合理~ 要不要考虑 glob？

**Comment by atian25** [comment]
@okoala 目前 wt 那一层不支持 glob，要看看怎么搞。

https://github.com/eggjs/egg-watcher-chokidar 是支持，不过 egg-development 是依赖于 egg-watcher 的。

**Comment by popomore** [comment]
```
  const watchDirs = [
    'app',
    'config',
    'mocks',
    'mocks_proxy',
  ].concat(config.watchDirs).map(dir => path.join(baseDir, dir));
```

把默认的也作为 watchDirs 参数，这样就可以覆盖默认的了。

**Comment by popomore** [comment]
@tangp1n 是这个意思么

**Comment by young-cowboy** [comment]
现在有办法解决这个问题，我也遇到了这个问题。app/public 目录下有很多前端工程依赖的node_modules，但是在本地开发环境中，开启watch后一开始就去监听文件，然后报错。我现在的做法时强行改掉egg应用依赖里的egg-development配置，只监听想要被监听的文件夹，如下：

`  const watchDirs = [
    'app/controller',
    'app/router',
    'app/service',
    'config',
    'mocks',
    'mocks_proxy',
  ].concat(config.watchDirs).map(dir => path.join(baseDir, dir));
`

**Comment by atian25** [comment]
https://github.com/eggjs/egg-development/pull/13

**Comment by muzi131313** [comment]
[aitan25的default.config.js](https://github.com/eggjs/egg-development/pull/13/files#diff-8):
````
exports.development = {
    overrideDefault: true,
    watchDirs: [
      'app/controller',
      'app/service',
      'app/view',
    ],
  };
````
