### ISSUE TITLE
RESTful 风格的路由定义，如何确定是请求动作的类别？

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#670]
* **Node Version**:>=6.0.0
* **Egg Version**:1.0.0
* **Plugin Name**:egg-mysql
* **Plugin Version**:^2.0.0
 
我现在在用RESTful风格定义路由，用 app.resources('posts', '/posts', 'posts'); 这句语句注册了一组CRUD，实现数据库增删查改，我困惑的是，service层或者是controller层是怎么进行post,put,del等请求的判断的呢？比如说我以前可以写app.post注册post事件，然后可以指定controller.action，现在用 app.resources该怎么操作？ app.resources('posts', '/posts', 'posts');这句话里并没有给出action，只是给了controller-name

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/tutorials/restful.html

**Comment by atian25** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/utils/router.js#L112

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/basics/router.html#restful-风格的-url-定义
