### ISSUE TITLE
关于调试

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#671]
开发时，如果想在Webstorm里调试Controller内容，有相应的NODE设置介绍文档之类的吗？
还有一个是能不能集成proxy_agent之类的插件，以及相关的设置方式。
谢谢!

* **Node Version**:6
* **Egg Version**:latest
* **Plugin Name**:ProxyAgent
* **Plugin Version**:latest
* **Platform**:Win

**Comment by atian25** [comment]
duplicate https://github.com/eggjs/egg/issues/616

**Comment by atian25** [comment]
proxy_agent?  指的是 curl 的时候的抓包么?
