### ISSUE TITLE
请问egg-init初始化的simple 项目，在 home.js 的index方法中，打印到控制台多次，是为什么？

### ISSUE THREAD

**Issue by dingyiming** [eggjs/egg#673]
请问egg-init初始化的simple 项目，在 home.js 的index方法中，我简单用 `console.log(1)` 打印一下，会在控制台出现两次（有的会三次），这是什么原因呢？

 我尝试写 数据库，也是会多次执行，需要怎么做，就只会执行一次？

谢谢。

**Comment by popomore** [comment]
能提供下能重现的代码么

**Comment by dingyiming** [comment]
大概原因，我知道应该是 因为 koa 的 洋葱圈，会在请求和响应时候，做两次执行，主要想知道如何才能只执行一次呢？

```js
'use strict';

module.exports = app => {
  class HomeController extends app.Controller {
    * index() {
    	console.log(1);
      this.ctx.body = 'hi, egg';
    }
  }
  return HomeController;
};
```

结果就是 一次请求打印了 两次 1 

谢谢

**Comment by atian25** [comment]
跟洋葱圈没关系，Controller 只会执行一次。
把你的最小化可复现代码上传一份到你的 GitHub 仓库，然后发下地址。

**Comment by dingyiming** [comment]
哦哦，好的，我准备下，谢谢

**Comment by dingyiming** [comment]
https://github.com/dingyiming/egg-demo  已备好，请查验，直接访问 `localhost:7001` 默认地址即可

**Comment by atian25** [comment]
试了，无法复现，只会输出一次。

![image](https://cloud.githubusercontent.com/assets/227713/24442278/04eaf880-1490-11e7-8ef7-2bc7df81e4a9.png)

**Comment by dingyiming** [comment]
的确，我用 curl 也只跑一次，但chrome访问下，就出现两次，是我什么地方有问题么
![](https://dn-shimo-image.qbox.me/aXU1y3Alc5Ux0Q6p/image.png!thumbnail)

![](https://dn-shimo-image.qbox.me/vw3BzjAUwRwWmgNi/image.png!thumbnail)

**Comment by atian25** [comment]
检查你自己 chrome 的插件问题，为何导致两次刷新，这个跟 egg 没关系。

**Comment by dingyiming** [comment]
哦哦，好的，感谢，劳烦了

**Comment by ngot** [comment]
浏览器在发请求是会同时 发送一个 favicon 请求。这是浏览器特性。

**Comment by atian25** [comment]
@ngot controller 的路由是 `/`，`favicon` 映射不到这个 controller 的

**Comment by popomore** [comment]
favicon 也不应该进到 controller

**Comment by dingyiming** [comment]
找到原因了，抱歉，原来是 Gitlab tree 这个插件造成的，两次请求，是我大意了，感谢大家
![](http://note.youdao.com/yws/public/resource/a45210a5cd0d464078058c4ff1316e0f/xmlnote/F5BC100FCD824F4898F02A75E2D6A5E2/120)

![](http://note.youdao.com/yws/public/resource/a45210a5cd0d464078058c4ff1316e0f/xmlnote/64D8CE14544F42EB86096D9B4C98498C/122)
