### ISSUE TITLE
测试环境启动egg，redis报错问题

### ISSUE THREAD

**Issue by onion214** [eggjs/egg#675]
* **Node Version**:
node-6.9.5
* **Egg Version**:
egg-1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

用以下命令启动egg服务报错
EGG_SERVER_ENV=test npm start

[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

是连redis服务的问题，但是config/config.test.js中的redis配置并不是这个
config/config.test.js

/**
 * redis组件
 */
exports.redis = {
    default: {
    },
    app: true,
    agent: false,

    //Single Redis
    client: {
        port: 6379,
        host: "隐去部分。。.kvstore.aliyuncs.com",
        options: {},
        password: "隐去部分。。edisat2016",
        db: '0'
    }
}

**Comment by onion214** [comment]
另外关闭插件也不生效

//config/plugin.js
exports.redis = {
    enable: false,
    package: 'egg-redis',
};

**Comment by dead-horse** [comment]
贴一下 ./run/application_config.json  文件，看看运行时生成的配置

**Comment by onion214** [comment]
{
  "config": {
    "onerror": {
      "errorPageUrl": "",
      "appErrorFilter": null
    },
    "session": {
      "maxAge": 86400000,
      "key": "EGG_SESS",
      "httpOnly": true,
      "encrypt": true,
      "overwrite": true,
      "signed": true,
      "encode": "<Function encode>",
      "decode": "<Function decode>"
    },
    "i18n": {
      "defaultLocale": "en_US",
      "dir": "/app/nodeapp/walrus/config/locales",
      "queryField": "locale",
      "cookieField": "locale",
      "cookieMaxAge": "1y",
      "functionName": "__",
      "dirs": [
        "/app/nodeapp/walrus/node_modules/.1.3.0@egg-onerror/config/locales",
        "/app/nodeapp/walrus/node_modules/.2.1.0@egg-session/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.1.0@egg-i18n/config/locales",
        "/app/nodeapp/walrus/node_modules/.2.1.0@egg-watcher/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.2.0@egg-multipart/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.9.0@egg-security/config/locales",
        "/app/nodeapp/walrus/node_modules/.2.3.0@egg-schedule/config/locales",
        "/app/nodeapp/walrus/node_modules/.2.2.2@egg-logrotator/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.3.0@egg-static/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.0.0@egg-jsonp/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.0.1@egg-view/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.1.0@egg-jwt/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.1.1@egg-mongoose/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.0.1@egg-redis/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.0.0@egg-validate/config/locales",
        "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/locales",
        "/app/nodeapp/walrus/config/locales"
      ]
    },
    "watcher": {
      "type": "default",
      "eventSources": {
        "default": "/app/nodeapp/walrus/node_modules/.2.1.0@egg-watcher/lib/event-sources/default",
        "development": "/app/nodeapp/walrus/node_modules/.2.1.0@egg-watcher/lib/event-sources/development"
      }
    },
    "multipart": {
      "autoFields": false,
      "defaultCharset": "utf8",
      "fieldNameSize": 100,
      "fieldSize": 102400,
      "fields": 10,
      "fileSize": 10485760,
      "files": 10,
      "fileExtensions": [],
      "whitelist": null
    },
    "security": {
      "domainWhiteList": [],
      "protocolWhiteList": [],
      "defaultMiddleware": "csrf,hsts,methodnoallow,noopen,nosniff,csp,xssProtection,xframe",
      "csrf": {
        "enable": true,
        "useSession": false,
        "ignoreJSON": true,
        "cookieName": "csrfToken",
        "sessionName": "csrfToken",
        "headerName": "x-csrf-token",
        "bodyName": "_csrf",
        "queryName": "_csrf",
        "matching": "<Function anonymous>"
      },
      "xframe": {
        "enable": true,
        "value": "SAMEORIGIN",
        "matching": "<Function anonymous>"
      },
      "hsts": {
        "enable": false,
        "maxAge": 31536000,
        "includeSubdomains": false
      },
      "methodnoallow": {
        "enable": true,
        "matching": "<Function anonymous>"
      },
      "noopen": {
        "enable": true,
        "matching": "<Function anonymous>"
      },
      "nosniff": {
        "enable": true,
        "matching": "<Function anonymous>"
      },
      "xssProtection": {
        "enable": true,
        "value": "1; mode=block",
        "matching": "<Function anonymous>"
      },
      "csp": {
        "enable": false,
        "policy": {},
        "ignore": "/api",
        "xframe": {
          "enable": false
        }
      }
    },
    "helper": {
      "shtml": {}
    },
    "logrotator": {
      "filesRotateByHour": null,
      "filesRotateBySize": null,
      "maxFileSize": 52428800,
      "maxFiles": 10,
      "rotateDuration": 60000,
      "maxDays": 31
    },
    "static": {
      "prefix": "/public/",
      "dir": "/app/nodeapp/walrus/app/public",
      "dynamic": true,
      "preload": false,
      "buffer": false
    },
    "jsonp": {
      "limit": 50,
      "callback": "_callback",
      "csrf": false
    },
    "view": {
      "root": "/app/nodeapp/walrus/app/view",
      "cache": true,
      "defaultExtension": ".html",
      "defaultViewEngine": "",
      "mapping": {}
    },
    "jwt": {
      "secret": "<String len: 6>",
      "key": "user",
      "tokenKey": "token"
    },
    "mongoose": {
      "url": "mongodb://121.40.82.99/huibaoDB",
      "options": {
        "user": "huibao",
        "pass": "<String len: 8>",
        "db": {
          "forceServerObjectId": false,
          "w": 1
        },
        "auth": {},
        "server": {
          "socketOptions": {},
          "auto_reconnect": true
        },
        "replset": {
          "socketOptions": {}
        }
      }
    },
    "redis": {
      "default": {},
      "app": true,
      "agent": true,
      "client": {
        "port": 6379,
        "host": "780fdbad2df545ae.m.cnhza.kvstore.aliyuncs.com",
        "password": "<String len: 28>",
        "db": "0",
        "options": {}
      }
    },
    "env": "test",
    "name": "walrus",
    "keys": "<String len: 21>",
    "proxy": false,
    "protocolHeaders": "x-forwarded-proto",
    "ipHeaders": "x-forwarded-for",
    "hostHeaders": "x-forwarded-host",
    "pkg": {
      "name": "walrus",
      "version": "1.0.0",
      "description": "walrus RESTful API",
      "private": true,
      "dependencies": {
        "egg": "^1.0.0",
        "egg-jwt": "^1.1.0",
        "egg-mongoose": "^1.1.1",
        "egg-redis": "^1.0.1",
        "egg-validate": "^1.0.0",
        "ioredis": "^2.5.0",
        "koa-ratelimit": "^3.0.0"
      },
      "devDependencies": {
        "autod": "^2.8.0",
        "egg-bin": "^3.1.0",
        "egg-ci": "^1.6.0",
        "egg-mock": "^3.2.0",
        "eslint": "^3.18.0",
        "eslint-config-egg": "^3.2.0",
        "ioredis": "^2.5.0",
        "supertest": "^3.0.0",
        "webstorm-disable-index": "^1.1.2"
      },
      "engines": {
        "node": ">=4.0.0"
      },
      "scripts": {
        "start": "node index.js",
        "dev": "egg-bin dev",
        "test": "npm run lint -- --fix && npm run test-local",
        "test-local": "egg-bin test",
        "cov": "egg-bin cov",
        "lint": "eslint .",
        "ci": "npm run lint && npm run cov",
        "autod": "autod"
      },
      "repository": {
        "type": "git",
        "url": ""
      },
      "author": "dead-horse",
      "license": "MIT",
      "boilerplate": {
        "name": "egg-boilerplate-empty",
        "version": "1.0.2",
        "description": "empty boilerplate for egg simple project",
        "repository": {
          "type": "git",
          "url": "git@github.com:eggjs/egg-boilerplate-empty.git"
        },
        "homepage": "https://github.com/eggjs/egg-boilerplate-empty"
      }
    },
    "baseDir": "/app/nodeapp/walrus",
    "HOME": "/home/node",
    "rundir": "/app/nodeapp/walrus/run",
    "dump": {
      "ignore": "<Set>"
    },
    "notfound": {
      "pageUrl": ""
    },
    "siteFile": {
      "/favicon.ico": "<Buffer len: 14191>"
    },
    "bodyParser": {
      "enable": true,
      "encoding": "utf8",
      "formLimit": "100kb",
      "jsonLimit": "100kb",
      "strict": true,
      "queryString": {
        "arrayLimit": 100,
        "depth": 5,
        "parameterLimit": 1000
      },
      "returnRawBody": true
    },
    "logger": {
      "dir": "/home/node/logs/walrus",
      "encoding": "utf8",
      "env": "test",
      "level": "INFO",
      "consoleLevel": "INFO",
      "outputJSON": false,
      "buffer": true,
      "appLogName": "walrus-web.log",
      "coreLogName": "egg-web.log",
      "agentLogName": "egg-agent.log",
      "errorLogName": "common-error.log",
      "coreLogger": {},
      "type": "application"
    },
    "httpclient": {
      "keepAlive": true,
      "freeSocketKeepAliveTimeout": 4000,
      "timeout": 30000,
      "maxSockets": null,
      "maxFreeSockets": 256,
      "enableDNSCache": false
    },
    "coreMiddleware": [
      "meta",
      "siteFile",
      "notfound",
      "static",
      "bodyParser",
      "session",
      "i18n",
      "securities"
    ],
    "workerStartTimeout": 600000,
    "middleware": [
      "errorHandler",
      "ratelimit"
    ],
    "errorHandler": {
      "match": "/api"
    },
    "ratelimit": {
      "db": "<Redis>",
      "duration": 60000,
      "errorMessage": "Sometimes You Just Have to Slow Down.",
      "id": "<Function id>",
      "headers": {
        "remaining": "Rate-Limit-Remaining",
        "reset": "Rate-Limit-Reset",
        "total": "Rate-Limit-Total"
      },
      "max": 100
    },
    "restapi": {
      "um": "http://121.40.121.237:4400",
      "opr": "http://121.40.121.237:8080",
      "tiger": "https://testpay.99bx.cn",
      "racoon": "http://120.55.89.17:8838",
      "bluewhale": "http://121.40.121.237:8866"
    },
    "coreMiddlewares": [
      "meta",
      "siteFile",
      "notfound",
      "static",
      "bodyParser",
      "session",
      "i18n",
      "securities"
    ],
    "appMiddlewares": [
      "errorHandler",
      "ratelimit"
    ],
    "appMiddleware": [
      "errorHandler",
      "ratelimit"
    ],
    "multipartParseOptions": {
      "autoFields": false,
      "defCharset": "utf8",
      "limits": {
        "fieldNameSize": 100,
        "fieldSize": 102400,
        "fields": 10,
        "fileSize": 10485760,
        "files": 10
      },
      "checkFile": "<Function checkFile>"
    }
  },
  "plugins": {
    "onerror": {
      "enable": true,
      "package": "egg-onerror",
      "name": "onerror",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.3.0@egg-onerror",
      "version": "1.3.0"
    },
    "session": {
      "enable": true,
      "package": "egg-session",
      "name": "session",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.2.1.0@egg-session",
      "version": "2.1.0"
    },
    "i18n": {
      "enable": true,
      "package": "egg-i18n",
      "name": "i18n",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.1.0@egg-i18n",
      "version": "1.1.0"
    },
    "watcher": {
      "enable": true,
      "package": "egg-watcher",
      "name": "watcher",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.2.1.0@egg-watcher",
      "version": "2.1.0"
    },
    "multipart": {
      "enable": true,
      "package": "egg-multipart",
      "name": "multipart",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.2.0@egg-multipart",
      "version": "1.2.0"
    },
    "security": {
      "enable": true,
      "package": "egg-security",
      "name": "security",
      "dependencies": [
        "session"
      ],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.9.0@egg-security",
      "version": "1.9.0"
    },
    "schedule": {
      "enable": true,
      "package": "egg-schedule",
      "name": "schedule",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.2.3.0@egg-schedule",
      "version": "2.3.0"
    },
    "logrotator": {
      "enable": true,
      "package": "egg-logrotator",
      "name": "logrotator",
      "dependencies": [
        "schedule"
      ],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.2.2.2@egg-logrotator",
      "version": "2.2.2"
    },
    "static": {
      "enable": true,
      "package": "egg-static",
      "name": "static",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.3.0@egg-static",
      "version": "1.3.0"
    },
    "jsonp": {
      "enable": true,
      "package": "egg-jsonp",
      "name": "jsonp",
      "dependencies": [],
      "optionalDependencies": [
        "security"
      ],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.0.0@egg-jsonp",
      "version": "1.0.0"
    },
    "view": {
      "enable": true,
      "package": "egg-view",
      "name": "view",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/node_modules/.1.0.0@egg/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.0.1@egg-view",
      "version": "1.0.1"
    },
    "jwt": {
      "enable": true,
      "package": "egg-jwt",
      "name": "jwt",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.1.0@egg-jwt",
      "version": "1.1.0"
    },
    "mongoose": {
      "enable": true,
      "package": "egg-mongoose",
      "name": "mongoose",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.1.1@egg-mongoose",
      "version": "1.1.1"
    },
    "redis": {
      "enable": true,
      "package": "egg-redis",
      "name": "redis",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.0.1@egg-redis",
      "version": "1.0.1"
    },
    "validate": {
      "enable": true,
      "package": "egg-validate",
      "name": "validate",
      "dependencies": [],
      "optionalDependencies": [],
      "env": [],
      "from": "/app/nodeapp/walrus/config/plugin.js",
      "path": "/app/nodeapp/walrus/node_modules/.1.0.0@egg-validate",
      "version": "1.0.0"
    }
  }
}

**Comment by dead-horse** [comment]
![image](https://cloud.githubusercontent.com/assets/985607/24440938/afcb920c-1489-11e7-9c60-82c583d8f4d5.png)

看起来配置是没问题的，你再检查一下你的运行时代码和日志，如果还是觉得有问题，可以提交一个最小复现的代码仓库到 git 上发出来。

**Comment by onion214** [comment]
@dead-horse 
不好意思，找到原因了，程序中还有一个使用redis的地方

/**
 * 引入koa的中间件
 * 接口调用频率限制
 */
exports.ratelimit = {
    db: new Redis(),
    duration: 60000,
    errorMessage: 'Sometimes You Just Have to Slow Down.',
    id: (ctx) => ctx.ip,
    headers: {
        //X-Rate-Limit-Total：特定时间段内允许的最多请求次数；
        //X-Rate-Limit-Remaining：特定时间段内剩余的请求次数；
        //X-Rate-Limit-Reset：什么时候请求频率限制次数会重置；
        remaining: 'Rate-Limit-Remaining',
        reset: 'Rate-Limit-Reset',
        total: 'Rate-Limit-Total'
    },
    max: 100
};

**Comment by dumuchenglin123** [comment]
这个问题也发生在redis服务没跑起来时的情况
