### ISSUE TITLE
egg-logger 配置不起作用

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#677]
* **Node Version**: 7.7.4
* **Egg Version**: 1.0.0
* **Plugin Name**: egg-logger
* **Plugin Version**:
* **Platform**: win 7 sp1 x64

配置不起作用，永远都只会根据默认配置，只会输出 INFO 及以上（WARN 和 ERROR）的日志到终端中。

//config.default.js
exports.logger = {
    level: 'DEBUG',
    consoleLevel: 'DEBUG',
};

**Comment by luckydrq** [comment]
配置到 `config.local.js`里

**Comment by popomore** [comment]
搞个最小化的可重现的例子放到 github 看看

**Comment by justinli0709** [comment]
写到config.local.js里生效了

写在config.default.js里不生效

**Comment by atian25** [comment]
https://github.com/eggjs/egg/blob/master/config/config.local.js#L6

这个原因导致的， @popomore

**Comment by popomore** [comment]
是的，@luckydrq 这都能猜到，感觉被坑过。

**Comment by atian25** [comment]
要干掉么

**Comment by fengmk2** [comment]
框架还是只设置 default 配置好了，local 等环境相关的都去掉

**Comment by luckydrq** [comment]
@popomore 之前用内网版本遇到过  :D

**Comment by justinli0709** [comment]
@luckydrq 难怪....... 哈哈

**Comment by atian25** [comment]
- `consoleLevel: INFO` 两边是一样的，可以干掉
- 但 `level: 'INFO',` 如果不在 local 配置为 DEBUG 的话，在开发期会错过一些信息的。

**Comment by popomore** [comment]
还好很少人会去看文件的。

**Comment by ngot** [comment]
框架和插件应该都不要和 env 相关

**Comment by atian25** [comment]
egg 的 config.local.js 干掉好了，里面的内容，放到 egg-development 的 config.default.js 里面，这样用户在 app 的 config.default.js 里面就可以覆盖掉。

**Comment by popomore** [comment]
放 development 无法覆盖框架吧
TZ | 天猪 <notifications@github.com>于2017年3月31日 周五11:46写道：

**Comment by dead-horse** [comment]
development 动态改？

**Comment by atian25** [comment]
在 app.js 动态改 config 还是调用 logger 的接口?
