### ISSUE TITLE
如何自定义文件上传地址

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#679]
* **Node Version**:>=6.0.0
* **Egg Version**:1.0.0
官方文档描写了如何将文件上传到阿里云oss。   yield ctx.oss.put(name, stream);  请问我如何自定义这块的上传位置呢？比如说上传到我自己的存储位置（非阿里云平台）

**Comment by atian25** [comment]
用你自己平台的 SDK 不就好了? 反正你都拿到 steam 了.

或者用我们提供的 httpclient
https://eggjs.org/zh-cn/core/httpclient.html#以-stream-方式上传文件

**Comment by leonardodream** [comment]
谢谢大哥指明方向，小弟又进了一步

**Comment by yulaughing** [comment]
不是太懂，可以再讲一下么？

**Comment by duncup** [comment]
@yulaughing  简单说就是你可以把 egg-oss 换成你所需要的其他 SDK 来上传到其他位置。

**Comment by yulaughing** [comment]
@duncup 那我想把文件放在我自己的本地的一个文件夹里，该怎么搞呢

**Comment by popomore** [comment]
用 fs

**Comment by atian25** [comment]
stream 都拿到了，如何存文件就是 node 的知识了。

**Comment by yulaughing** [comment]
ok，得到了，谢谢

**Comment by atian25** [comment]
建议用 pump

**Comment by Jialufeng** [comment]
@atian25   猪哥    pump  好像是一个函数   需要传到oss吗？现在保存到oss 后 图片是空的。
![image](https://user-images.githubusercontent.com/16443142/45345945-63ffb300-b5da-11e8-8aee-13b04e0ee55c.png)

**Comment by atian25** [comment]
oss 就不需要 pump，它是用来帮你更好的处理 stream 的异常

**Comment by Jialufeng** [comment]
好的
