### ISSUE TITLE
上传数据 content-type 设置问题

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#681]
* **Node Version**:>=6.0.0
* **Egg Version**:1.0.0

各位大哥下午好！我上传数据的时候，如果在curl里设置了content-type，上传的时候就会报一个boundary not found 的错，如果把'content-type'设为false或者直接不写，就会报一个Content-Type must be multipart/* 的错。这是为什么呢？
const result = yield ctx.curl(url, {
		method: 'POST',
		stream: fileStream,
		dataType: 'json',
 		headers: {
 			'content-type': 'multipart/form-data',
 		},
	});

**Comment by dead-horse** [comment]
https://eggjs.org/zh-cn/core/httpclient.html#以-multipart-方式上传文件

**Comment by zxq08** [comment]
@leonardodream  嗨我遇到了同样的问题。。一模一样，不知怎么解决。。
