### ISSUE TITLE
请问vue或者angular 怎么配合egg最好？

### ISSUE THREAD

**Issue by buzai** [eggjs/egg#683]
我是这么做的，静态dist目录里放了我build出的前端文件。  
config.static = {
    prefix: '/',
    dir: path.join(appInfo.baseDir, 'dist/')
  }

但是我浏览的时候 http://127.0.0.1:7001/index.html#/login ， url很怪异
请问怎么解决最好呢？有类似koa-static一样的东西么

**Comment by atian25** [comment]
你指的是后面的 hash？请出门右转去 vue router 文档学习下 html5 mode

**Comment by buzai** [comment]
@atian25 不是，有没有koa-static，你用过么？
app.use(serve(path.resolve('dist'))); // 将webpack打包好的项目目录作为Koa静态文件服务的目录
原先在koa里我不用带 index.html

**Comment by buzai** [comment]
但是egg。我得带上index.html

**Comment by atian25** [comment]
egg-static 是基于 [koa-static-cache](https://github.com/koajs/static-cache) 而不是 [koa-static](https://github.com/koajs/static)，不支持后者的 `index` 配置。

自己写一个 router 做映射就 ok 了。

**Comment by buzai** [comment]
@atian25 谢谢

**Comment by buzai** [comment]
1. 经过测试插件设置：
exports.ejs = {
  enable: true,
  package: 'egg-view-ejs',
};

2.配置设置：

a：静态文件css js等
  config.static = {
    prefix: '/',
    dir: path.join(appInfo.baseDir, 'app/public/')
  }
b：模板设置
  config.view = {
    defaultExt: '.html',
    mapping: {
      '.ejs': 'ejs',
      '.html': 'ejs',
    }
  }

3.路由控制器设置：
     //将 index.html 放在app/view里，静态文件放在public里

      const { ctx } = this;
      // render user.html
      yield ctx.render('index');

**Comment by gatspy** [comment]
我也不知道现在前端用这种服务器渲染的mvc优势在哪里？都前后端分离了，还要整服务端渲染。
我就喜欢vue或angular做spa。node层只做api服务。

**Comment by atian25** [comment]
跟业务场景有关，有些时候 SEO 和首屏时间是强需求，如 UC 在两印的一些业务。

发自我的 iPhone

**Comment by hualife123** [comment]
路由控制器设置：
     //将 index.html 放在app/view里，静态文件放在public里

      const { ctx } = this;
      // render user.html
      yield ctx.render('index');

请问这个是要在哪里进行配置？

**Comment by atian25** [comment]
啥

发自我的 iPhone

**Comment by buzai** [comment]
@hualife123 不用配置，render 函数自动在view文件夹里找到index文件渲染

**Comment by hualife123** [comment]
我理解的是render应该是写在Controller中，那请问router中要怎么写？是router.get('/login', controller.login.index); 是这样吗？

**Comment by atian25** [comment]
看下模板渲染那章文档

**Comment by hualife123** [comment]
@atian25 搞定了  多谢

**Comment by yugasun** [comment]
可以借鉴下我的方案，因为我的前端项目是用 `vue-cli` 初始化的，所以 `npm run build` 后生成的 `dist` 文件夹结构如下：

```
dist
├── index.html
└── static
    ├── css
    │   ├── app.css
    │   └── app.css.map
    ├── fonts
    │   └── element-icons.6f0a763.ttf
    └── js
        ├── app.js
        ├── app.js.map
        ├── manifest.js
        ├── manifest.js.map
        ├── vendor.js
        └── vendor.js.map
```
复制步骤分为两步：
 1. 然后我将 `index.html` 移动到 `app/view` 目录下，
 2. 将 `static` 目录文件移动到 `app/public` 目录下

但是有个问题出现了，就是 `index.html` 文件中的静态文件请求路径是 `/static/js/app.js` 这样的，对于 eggjs 的 `public` 中静态资源请求应该是 `/public/xx/x`，所以我对 `webpack` 项目的配置做了修改，将编译输出的静态文件目录改为 `dist/public`，这样再次重复复制步骤就没问题了。可以参考我的项目模板
[egg-vue-starter](https://github.com/yugasun/egg-vue-starter)，希望能够帮助到大家。

**Comment by buzai** [comment]
@yugasun 66666
