### ISSUE TITLE
请问如何配置代码修改后重启进程？

### ISSUE THREAD

**Issue by guzuomuse** [eggjs/egg#684]
为什么修改代码后不能自动重启；我试过了各种编辑器都不行；也查看了issues找不到答案；
配置了egg-development插件也不行？
难道必须修改一次代码就必须ctr+c,然后再运行一次 npm run dev?
没有livereload的功能么？

**Comment by atian25** [comment]
第一个问题请提交最小可复现代码。另外你确定修改的是后端代码吧？

第二个问题，livereload 是刷新前端，原来 koa 怎么弄现在就怎么弄

**Comment by atian25** [comment]
对这两个项目做下 diff？

**Comment by atian25** [comment]
cc @eggjs/core

**Comment by whxaxes** [comment]
# 复现流程

刚才在 @atian25  的配合下重现了一次出问题的步骤。

**Comment by whxaxes** [comment]
复现步骤；

刚才在 @atian25 的协助下重现了一下：

1. 启动应用：

![image](https://cloud.githubusercontent.com/assets/5856440/24535420/8e0c8b02-1606-11e7-91e5-a8bcf0477472.png)

显示启动了 98249、98250、98251、98252 四个 worker。

2. 浏览器访问：

![image](https://cloud.githubusercontent.com/assets/5856440/24535401/5e47669e-1606-11e7-81ff-a71736aabaa2.png)

接收请求的是 98252 这个 worker

3. 更改内容引发重启，发现重启的就只有 98250、98251、98249：

![image](https://cloud.githubusercontent.com/assets/5856440/24535408/6e5b9d98-1606-11e7-8a66-01830529b024.png)

4. 刷新浏览器返回的还是 98252 ，用 `ps aux | grep 98252` 发现这个进程还活着：

![image](https://cloud.githubusercontent.com/assets/5856440/24535443/bd2c19b6-1606-11e7-9448-0f3d2ccea34a.png)

5. 把浏览器 kill 掉之后，这个进程才 disconnect 。

整理一下：

复现步骤:
1. egg-init --type=simple showcase 初始化项目，在controller 里面返回 pid
2. node index.js 启动多个 worker
3. 用浏览器(chrome, Safari, chrome 隐身模式) 访问页面
4. 修改 controller 的输出，在控制台看到重启了，workers 列表中已经没有它，但这个 pid 没有 disconnect 信息
5. 此时刷新浏览器，显示的内容还是原来的 pid
6. 同时刻用 curl 请求，显示是新的 pid
7. ps 这个 pid，一直存在

**Comment by dingyiming** [comment]
我也是用 `egg-init`  的 simple 的确，很容易出现无法自动更新的情况，目前只能手动关闭，再重启

**Comment by whxaxes** [comment]
@dingyiming  开发的时候建议用 npm run dev，或者在 index.js 中的参数加上 workers: 1，单个 worker 就不会出现这个问题。

**Comment by dingyiming** [comment]
哦哦，不过，我就是用的 npm run dev， index.js 在dev的命令下，有用到吗？

**Comment by whxaxes** [comment]
@dingyiming run dev不会用到 index.js，不过 run dev 也是只会启动一个 worker，你那里单个 worker 也会出现？windows系统？

**Comment by dingyiming** [comment]
恩恩，是的 windows 系统，会出现无法自动更新的情况，而且后面请求发出来，控制台已经不打印任何东西了

**Comment by AkashiX** [comment]
```js 
// watcher配置
config.watcher = {
  type: 'development'
};
```
这样试试看能不能解决无法自动更新问题？

**Comment by atian25** [comment]
@whxaxes 删除重装下依赖，再看看能否复现

**Comment by popomore** [comment]
既然一个 work 无法重现那就忽略这个问题吧，本地开发用的 cluster-reload 本身就是用比较暴力的方式重启，一直想把这个给去掉。

**Comment by popomore** [comment]
如果还是其他讨论的可以再打开。

**Comment by popomore** [comment]
可以再看下 cluster-reload 的实现，先保留第一个 worker 响应请求，然后 fork 一个 worker，当这个 worker 完成启动后（listening）再 kill 原来的第一个 worker，所以还是有时间差的。

**Comment by callmeyahui** [comment]
> @popomore
> @guzuomuse
> 放弃egg的reload，定义一个启动文件，使用nodemon启动，
> 需要做如下代码处理：
> cluster-client/lib/connection.js
> 
> ```
> _handleSocketError(err) {  
>     // 返回true，不触发任何错误  
>     return true;  
>     this._lastError = err;  
>     if (err.code === 'ECONNRESET') {
>       this.logger.warn('[ClusterClient:Connection] socket is closed by other side while there were still unhandled data in the socket buffer');
>     } else {
>       this.emit('error', err);
>     }
>   }
> ```
> cluster-client/lib/client.js
> 
> ```
> function reloadWorker(info) {
>     if (!config.reloadOnDebug) {
>       return;
>     }
>     if (isAssetsDir(info.path) || info.isDirectory) {
>       return;
>     }
>     // don't reload if don't match
>     if (config.reloadPattern && multimatch(info.path, config.reloadPattern).length === 0) {
>       return;
>     }
>     logger.warn(`[agent:development] reload worker because ${info.path} ${info.event}`);
>     // 注释掉这部分代码，不刷新worker
>     // process.send({
>     //   to: 'master',
>     //   action: 'reload-worker',
>     // });
>   }
> ```

请问能详细解释一下吗？
