### ISSUE TITLE
请问leancloud-storage应该配置在什么地方？

### ISSUE THREAD

**Issue by dingyiming** [eggjs/egg#687]
- 我在 router.js 开头配置了 AV.init， 后发现，`npm run dev` 开启开发调试时，修改文件的热重载失效，请问我该把leancloud 配置在什么地方,同时使开发热重载有效？ 

-  然后在 controller 中 写 Leancloud 操作数据时，如果没有 加上 yield 会出现404 ，但没有明确说明原因，很无厘头的感觉，这块错误处理该怎么改善？

- 如何支持 `Content-type = text/plain` 请求的数据的解析？ 在 Express 中的 bodyParse 比较方便的添加一下 `txt`的支持，自己再 JSON.parse()下 即可，这边不知道要怎么配置呢？ 

- 也希望 egg的日志显示可以规整一些，简练些，最好像 thinkjs 配置成多彩的，好排查，

- 谢谢

**Comment by atian25** [comment]
- 第一个问题，提供下最小的代码仓库？
- 没有 yield 会 404 这个是 Koa 本身的规则
- 加一个配置即可，参见
  - https://github.com/eggjs/egg/blob/master/config/config.default.js
  - https://github.com/koajs/bodyparser
- 能举下具体的例子么?

**Comment by dingyiming** [comment]
-  好，我准备下代码仓库
- 哦哦，好，我加上
-  从 koajs/bodyparser 中看到是要修改 `enableTypes` ,但从 egg 的 bodyParse 中，没有配置该项，是否可以直接通过  `enableTypes =  ['json', 'form', 'txt'] `实现？

![image](https://cloud.githubusercontent.com/assets/12537013/24485953/04530354-153a-11e7-831a-e65450dbf4fe.png)

![](http://note.youdao.com/yws/public/resource/a45210a5cd0d464078058c4ff1316e0f/xmlnote/46C4566113FE4206BC6BFAA3BB7CCD4F/166)


- 主要对比了 egg 和 thinkjs 日志显示，希望 egg 借鉴下， 清晰很多

![image](https://cloud.githubusercontent.com/assets/12537013/24485884/a42dd076-1539-11e7-9c62-5fa5cab6f739.png)

- 谢谢

**Comment by atian25** [comment]
嗯，你在 config.default.js 里面配置一个 `config.bodyParser` 即可，会和默认的配置合并，并传给插件。

日志的那个在 #688 跟踪

**Comment by dingyiming** [comment]
好的，谢谢，添加了demo  https://github.com/dingyiming/egg-demo, 发现其实是在进行一次请求后，再修改 controller/home.js 中 内容，就不会出现热加载了，后面再请求还是之前的内容

**Comment by atian25** [comment]
![image](https://cloud.githubusercontent.com/assets/227713/24486576/57ce189a-153d-11e7-8493-aa454150f352.png)

@dingyiming 本地无法复现，我们是用 [egg-development](https://github.com/eggjs/egg-development) 来做变更监控的，或者你本地跑下这个库的单测看看？

PS：你在用 vagrant 么？

**Comment by dingyiming** [comment]
我把这个 写在这里是不是不合适？

- 在 router.js 里写加 的 AV配置
```
'use strict';

const AV = require('leancloud-storage');
const appId = 'Hu3riuJhm1BopDbH2DGe472U-gzGzoHsz';
const appKey = 'weBjsqduBxOrmcno0RgnsfJG';
AV.init({ appId, appKey });

module.exports = app => {
  app.get('/', 'home.index');
};

```

- 哦哦，好的，我试试，没有再用vagrant ,是 windows 环境，
- 谢谢

**Comment by atian25** [comment]
leancloud 这块可以考虑写成一个插件。

你这段 init 现在可以考虑放到 `{app_root}/app.js` 中

**Comment by dingyiming** [comment]
好，谢谢

**Comment by atian25** [comment]
重启问题 OK 了？

发自我的 iPhone
