### ISSUE TITLE
Cleanup stdout log, AGAIN!

### ISSUE THREAD

**Issue by huacnlee** [eggjs/egg#688]
<img width="1072" alt="2017-03-30 10 37 05" src="https://cloud.githubusercontent.com/assets/5518/24485133/daab935e-1534-11e7-9868-7ccb4f68ef13.png">

一般情况下，作为使用者：

- 没人在意 `start with options` 的内容，更别说它永远都是相同内容；
- `start with env: isProduction: false, isDebug: false, EGG_SERVER_ENV: undefined, NODE_ENV: development` 这里或许 ENV 显示有用，但 `undefined` ` isDebug isProduction` 似乎永远都是这样的值，那换个角度，仅在开启的时候显示出来呢？
- `Agent Worker`  这 4 段完全没必要存在
-  =================== egg start ===================== 可以去掉了，好多余

**Comment by atian25** [comment]
- 这些都是 master 的日志，如果我没记错的话，只是打印到 console 的，如果这里不打印的话，出问题没法排查吧。
- isDebug isProduction 之前是因为遇过一个坑，自定义 env 转换时，如果通过 loader 的方式，实际上 master 是不会执行这段逻辑的，所以加上的。也没啥影响吧？去不去都行。

**Comment by huacnlee** [comment]
不是时刻的出问题的，按你第一条的说法，这些都属于 Debug 信息，所以应该用 DEBUG 而不是 INFO

这样多好：
<img width="441" alt="2017-03-30 10 50 24" src="https://cloud.githubusercontent.com/assets/5518/24485386/b2ffabae-1536-11e7-9f18-4e44095df82d.png">

**Comment by atian25** [comment]
感觉可以优化下

**Comment by dingyiming** [comment]
- thinkjs 很规整，可以借鉴下

![](https://cloud.githubusercontent.com/assets/12537013/24485884/a42dd076-1539-11e7-9c62-5fa5cab6f739.png)

**Comment by fengmk2** [comment]
确实丑了点，我们改进改进

**Comment by popomore** [comment]
master 在 NODE_ENV 非 production 的时候可以优化下。

**Comment by okoala** [comment]
我觉得不是信息量的多少问题，而且是信息展示是否美观，整齐，重点是否突出的问题。

**Comment by atian25** [comment]
verbose模式下，可以输出下 loader 加载的文件总数

**Comment by atian25** [comment]
```
- master
- agent
  - start
  - loader step
    - loading config
    - loading 
  - beforeStart step
  - started
- worker
  - start
  - worker1
    - start
    - loader step
    - beforeStart step
    - started
  - worker2
    - start
    - loader step
    - beforeStart step
    - started
  - worker3
  - ...
- egg started
- print useful info
  - server url
  - env
  - log dir
  - some status
  - warning count during startup
```

**Comment by popomore** [comment]
可以在 egg-development 来覆盖 console 的 format
