### ISSUE TITLE
 AssertionError: Must set `app.config.static.dir` when static plugin enable

### ISSUE THREAD

**Issue by limichange** [eggjs/egg#690]
* **Node Version**:
6.10.1
* **Egg Version**:
1.0.0
* **Plugin Name**:
egg-static
* **Plugin Version**:
1.3.0
* **Platform**:
ubuntu

不是有默认的路由吗？

**Comment by dead-horse** [comment]
https://github.com/eggjs/egg-static/blob/master/config/config.default.js#L19 默认有配置，你看看你是不是在哪里把它覆盖了。 https://eggjs.org/zh-cn/faq.html#为什么我的配置不生效

**Comment by limichange** [comment]
thx, 的确是这样。
