### ISSUE TITLE
请问如何用nodemon 启动egg 项目进行开发？

### ISSUE THREAD

**Issue by dingyiming** [eggjs/egg#691]
请问如何用nodemon 启动egg 项目进行开发？

**Comment by atian25** [comment]
`egg-bin dev` 本身已经支持自动重启了，没必要用 nodemon。

实在要用的话，参考 https://eggjs.org/zh-cn/core/deployment.html#创建启动文件

建议传递 `workers:1` 进去

**Comment by dingyiming** [comment]
好的，谢谢，就是现在自带的自动重启总会失效，需要手动重启，比较奇怪，所以想换个试试看
