### ISSUE TITLE
how to configure router with 2 params. like app.get('/router','controller')

### ISSUE THREAD

**Issue by guzuomuse** [eggjs/egg#692]
here is bellow what i want:
MyController--->with some actions:     action_1*(){}, action_2*(){},action_3*(){}...etc.
in app>>router.js:
app.verb('/my','my');
i want the routes maps: 
```
http://domain/my/action_1=>MyController.action_1;
http://domain/my/action_2=>MyController.action_2;
http://domain/my/action_2=>MyController.action_3;
```

......
but, the configure `app.verb('/my','my');` could not achieve this. #201;
looks like  you can't configure routes with two params one is for router while another is controller name

is it a bug? if not ,how could i satisfy this demand(says:router auto mapping)? 
maybe a suugestion is that: we don't need to declare the route configure in the router.js file if we have some controller,it should  shape the mappings  **router/action =>controller/action**  automaticly like [sails](http://sailsjs.com/) does.
thanks

**Comment by atian25** [comment]
currently we don't support this, you can extends it at `{app}`

```js
// {project_root}/app.js
module.exports = app => {
   app.verb = (path, key) => {
       // 实际场景下可能需要考虑递归，具体可以看下 https://github.com/eggjs/egg-core/blob/master/lib/utils/router.js
       const ctrl = app.controller[key];
       for(const name of Object.keys(ctrl)) {
          // do real router mapping
         app.get('/xx', 'xxx')
       }
   }
}
```

**Comment by guzuomuse** [comment]
got it, i'll try
maybe ,merging this feature into the core would be better.
thank u

**Comment by atian25** [comment]
for now, I don't think it's not a common usage feature.
you can write it as a plugin.

btw, these is some scene:
- how to describe method?
- if auto mount is only for `get`, should we split `no-get` actions to another controller? how should we named it ?

**Comment by guzuomuse** [comment]
here is an referrence：extract from sailsjs document:

> Note that action routes respond to all HTTP verbs (GET, PUT, POST, etc.). You can use req.method inside an action to determine which method was used.

[#](http://sailsjs.com/documentation/reference/blueprint-api)

**Comment by atian25** [comment]
but in the real world, it's better to split different actions.

and usually we need to add  different auth to actions, such as

`app.post('/user/create', app.role.can('admin'), 'user.create')`

so I still think this feature is not common usage.

**Comment by guzuomuse** [comment]
all right.we'll see.
:)

**Comment by dead-horse** [comment]
close for now.
