### ISSUE TITLE
关于如何于webpack和gulp配合

### ISSUE THREAD

**Issue by limichange** [eggjs/egg#693]
现在的demo都是提供了js和css直接引用，但实际上在生产环境中要复杂的多。
通常情况是，开发的时候less样式和引入页面做调试。
要上线的时候，less编译后传到CDN上，view里的文件地址也转到CDN上。
不知eggjs要实现这样的工程化需要怎么做，也就是希望有一个和webpack gulp配合的demo，这样更贴近实际的情况。

**Comment by atian25** [comment]
koa + webpack 该怎么做就这么做吧，这块属于工程化，跟 egg 关系不是太大。

我这边的一种实践是，写一个 egg-webpack 的插件，但也没做什么事，就是在 agent 里面启动一个 static server 提供静态资源地址而已。

cc @geekdada 来讲讲

**Comment by mansonchor** [comment]
感觉可以围绕 egg、webpack、vue、react 做 egg 工程方案生态建设

其实就是 脚手架 + 最佳实践 = 开箱即用的工程方案

**Comment by limichange** [comment]
@mansonchor 其实我这边的感受就是，eggjs没法开箱即用，css和js和img这些静态资源不好处理。似乎eggjs只能做API服务器，并不适合做大型的多页应用。

**Comment by limichange** [comment]
先关死了，慢慢摸索。

**Comment by atian25** [comment]
@limichange 那是因为你之前用的那些都是已经帮你搞好的 boilerplate, 而不是原生的 koa 或 express.

有兴趣的话可以搞个对应的 boilerplate

**Comment by atian25** [comment]
@mansonchor 这块每个团队都可能有自己的实践，目前并没有太多的共识，这块可以有，但不会在 egg 里面，如果你们现在业务中有用到，完全可以做一个 boilerplate 然后分享出来。

**Comment by mansonchor** [comment]
@atian25 对，本身和 egg 无关，团队实践不一样所以也不可能做到 100% 适用

有时间我可以把目前团队的 工程方案做成 `boilerplate` 分享出来，算是补充 egg 在工程方案方面内容

这些 boilerplate 或多或少有价值的，社区很多人还是习惯拿来开箱即用，如果不行，或者就会放弃使用这个框架

**Comment by atian25** [comment]
@mansonchor 加油~  早点出来~
