### ISSUE TITLE
What is the best way to scale egg horizontally with sticky session?

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#697]
* **Node Version**: 6
* **Egg Version**: 1.0.0
* **Plugin Name**: NONE
* **Plugin Version**: NONE
* **Platform**: Mac OS

The scaling method described in [link](https://eggjs.org/zh-cn/advanced/cluster-client.html) looks like suitable for a single server. How can we use egg in multiple servers (scaling horizontally)? Especially when dealing with something like websocket. When having multiple servers behind a reverse proxy (nginx, HAProxy, etc), we need to have some sort of data persistence in memory. 

There are some solutions like [Primus](https://github.com/primus/primus), but in it's  [FAQ: Can I use cluster](https://github.com/primus/primus#can-i-use-cluster), it says the node's cluster module is flawed, is egg safe to use? does egg support primus? Or if using egg's APIClient, ClusterClient, and RegistryClient, there is no need for primus?

**Comment by ngot** [comment]
Maybe, these can help ?

- https://github.com/eggjs/egg-socket.io#node-conf 
- https://github.com/eggjs/egg-cluster/blob/master/README.md

You can start your server like this way:

```js
startCluster({
  sticky: true,
  ...
});
```

and then your can use `egg-session-redis` or something like this

**Comment by ngot** [comment]
Is it necessary to add `sticky` content to [here](https://eggjs.org/zh-cn/advanced/cluster-client.html) ? @fengmk2

**Comment by caoer** [comment]
looks promising! 👍 

If there is any documentation explaining how it works will be even better.

**Comment by ngot** [comment]
Yes.
Currently, this part is poorly documented.I'll add this soon.

**Comment by atian25** [comment]
@ngot also need a document `tutorials/socket.io`
