### ISSUE TITLE
How to automatically re-run test when file changes? 

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#698]
* **Node Version**: 6
* **Egg Version**: 1.0.0
* **Plugin Name**: NONE
* **Plugin Version**: NONE
* **Platform**: NONE

I think this issue should belong to egg-bin repo, but that repo is no abled to create any issue now. So I posted it here. 

- How to automatically re-run test when file changes? 
- facebook's [jest](https://github.com/facebook/jest) library is really neat, like the ability to run a single test in watch mode, or run tests with mach reg expression. Personally I found it much better than running mocha. Is it possible for me to integrate jest in egg dev environment?

**Comment by atian25** [comment]
`egg-bin test` support all argv of mocha.

try `egg-bin test --watch` or `npm run test-local -- --watch`

**Comment by atian25** [comment]
currently `egg-bin test` is only support `mocha`, you can extend `egg-bin` to `my-egg-bin` and replace `test` with your own implementation to use others like `jest`.

see https://github.com/eggjs/egg-bin#custom-egg-bin-for-your-team

**Comment by popomore** [comment]
egg-bin won't support jest, but you can write test using jest with egg-mock.

**Comment by caoer** [comment]
cool. I can try to integrate jest when I have time. 
`egg-bin test --watch` and `npm run test-local -- --watch` works. 👍

**Comment by chungchi300** [comment]
```
npx egg-bin test --watch
```
won't restart in **typescript version** although it runs at the first time

**Comment by atian25** [comment]
maybe `mocha` don't watch `**/*.ts` by default, see mocha docs for  `--watch`
