### ISSUE TITLE
Running tests with false-positive result.

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#699]
* **Node Version**: 6
* **Egg Version**: 1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

```
// const assert = require('power-assert');

describe('test/showcase.test.js', () => {
  const arr = [ 1, 2, 3 ];

  it('power-assert', () => {
    assert(arr[1] === 10);
  });
});
```

For above tests, it won't throw any error. It only works when power-assert is required. 
Do we have to include 'power-assert'? I think the global assert is `power-assert` by default?

**Comment by atian25** [comment]
- `test/.setup.js` will auto load by `egg-bin test`, see https://github.com/eggjs/egg-bin/blob/master/lib/cmd/test.js#L91
- the boilerplate `simple` contains `test/.setup.js` https://github.com/eggjs/egg-boilerplate-simple/blob/master/boilerplate/test/.setup.js
- and `intelli-espower-loader` is also auto required, which play a magic trick to replace all `require('assert')` to `require('power-assert')`

**Comment by caoer** [comment]
I see. well-explained. I replaced https://github.com/eggjs/egg-boilerplate-simple/blob/master/boilerplate/test/.setup.js#L7 with `const assert = require('power-assert');`, the false-positive issue gone away. 

but I'm still curious why there is such issue.

**Comment by atian25** [comment]
sorry, did not notice your real question.

yes, it seems to be a bug, I will take a look.

**Comment by atian25** [comment]
it's seems to be a problem of `power-assert-js/espower-source`

https://github.com/power-assert-js/power-assert/issues/83

**Comment by coolzilj** [comment]
+1 same issue

**Comment by atian25** [comment]
for now, just modify `test/.setup.js`:

```
// test/.setup.js
global.assert = require(assert');
// TO 
global.assert = require('power-assert');
```

**Comment by dead-horse** [comment]
@atian25 I'd like to remove `global.assert` in boilerplate, it is anti-pattern.

**Comment by atian25** [comment]
that's @fengmk2 's idea, let ping him
