### ISSUE TITLE
egg-cors 白名单 怎么允许所有访问

### ISSUE THREAD

**Issue by leonardodream** [eggjs/egg#701]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
egg-cors works internally with egg-security. By defining the property of domainWhiteList on object security, you have successfully informed the framework to whitelist the passed domains.
白名单配置语句如下：
exports.security = {
  domainWhiteList: [ 'http://localhost:8080' ],
};
我可不可以把白名单里的参数写成 允许 所有呢？因为我不写白名单发现前端访问会报跨域问题。

**Comment by bshy522** [comment]
domainWhiteList: [ '*' ]

**Comment by leonardodream** [comment]
@bshy522 试过了，并不成功

**Comment by bshy522** [comment]
我看了下源码，可以传一个
```js
exports.security = {
  origin: () => '*'
}
```

你可以试下。

**Comment by leonardodream** [comment]
@bshy522 security: {
    csrf: false,
     origin: () => '*'
},
那这个开关还要么？这样试了一下还是不成功

**Comment by bshy522** [comment]
```js
exports.cors = {
  origin: () => '*'
}
```

写错了，你试下。

**Comment by leonardodream** [comment]
我加到了plugin.js里，还是不行

**Comment by bshy522** [comment]
你等等他们看看吧。。

cors 内置到 security 里面 感觉很牵强。。

**Comment by atian25** [comment]
配置文件怎么会在 plugin.js

发自我的 iPhone

**Comment by leonardodream** [comment]
@atian25 大哥早上好。一开始在plugin.js里写的，没成功，后来我把他写到plugin.js的egg-cors插件开关里了，就是上边那样。
这是现在的写法，在plugin.js里，还是不成功 
 module.exports = {
	security: {
    csrf: false,
},
bodyParser: {
    jsonLimit: '100Mb',
    formLimit: '100Mb',
},
cors : {
  origin: () => '*'
},

**Comment by leonardodream** [comment]
@atian25 大哥早上好。一开始在config.default.js里写的，没成功，后来我把他写到plugin.js的egg-cors插件开关里了，就是上边那样。
这是现在的写法，在config.default.js里，还是不成功
module.exports = {
security: {
csrf: false,
},
bodyParser: {
jsonLimit: '100Mb',
formLimit: '100Mb',
},
cors : {
origin: () => '*'
},

**Comment by atian25** [comment]
所有的配置都在 config.{env}.js 而不在 plugin.js，后者只负责插件的挂载

发自我的 iPhone

**Comment by leonardodream** [comment]
我这个问题，大哥有什么建议么？ @atian25

**Comment by atian25** [comment]
egg-cors 默认是要检测安全域名的。

如果你不想检测的话，可以不用这个插件，直接自己写一个 middleware 即可。

```js
// app/middleware/cors.js
module.exports = require('kcors');

// app/config/config.default.js
config.middleware = [ 'cors' ];
```

plugin 那边不要挂载，并卸载掉 `egg-cors` ，安装 `kcors`。

cc @jtyjty99999 看看 `egg-cors` 要不要加个开关，或者支持通配？

**Comment by leonardodream** [comment]
//app/config/config.default.js
@atian25    哥，我卸载了egg-cors,安装了kcors，照着你说的方法做了，还是报跨域。
module.exports = appInfo => {
  const config = {};
  config.keys = appInfo.name + '_1490148888387_1184';
  config.middleware = [ 'cors' ];
  return config;
};

**Comment by atian25** [comment]
`curl -H ` 看看回来的 headers, 或者提供最小可复现代码.

**Comment by leonardodream** [comment]
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
Cache-Control:no-cache
Connection:keep-alive
DNT:1
Host:192.168.1.111:7001
Origin:http://localhost:3000
Pragma:no-cache
Referer:http://localhost:3000/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by leonardodream** [comment]
request 的 
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-readtime: 1
content-length: 607
Date: Sat, 01 Apr 2017 08:14:08 GMT
Connection: keep-alive

**Comment by leonardodream** [comment]
config.default.js 部分
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1490148888387_1184';
  config.middleware = [ 'cors' ];
  return config;
};
//module.exports.security = {
//csrf: false
//};

module.exports = {
	security: {
    csrf: false,
},

middle/cors.js
module.exports = require('kcors');

**Comment by popomore** [comment]
@leonardodream 后面 security 配置覆盖了前面，建议学习下 node 的只是

**Comment by buzai** [comment]
@popomore 这个问题是要说怎么关掉那个鬼东西，你上来就让人家学习一下搞笑。。。到头也没说咋关掉

**Comment by atian25** [comment]
@buzai 你仔细看下最后贴的那段代码，提问者写了两个 module.exports 互相覆盖了，@popomore 的回答也很准确的回答了。

**Comment by okoala** [comment]
@buzai  每个人时间都是很宝贵的，应该尽量避免一些低级错误。
