### ISSUE TITLE
请问在哪里可以配置一些固定参数，供应用内部使用？

### ISSUE THREAD

**Issue by dingyiming** [eggjs/egg#702]
请问在哪里可以配置一些固定参数，供应用内部使用？ 比如我要配置的 一些 key 或者 一些状态所对应的常量，字符串之类的，是放 config 吗？

**Comment by atian25** [comment]
app.confg.xx 或直接 app.xx 都行，看你们的业务定义。

发自我的 iPhone

**Comment by ngot** [comment]
放哪都行，随便建个 xxx.js 随便放个地方，最后require他就好了。

主要看你的定义了

**Comment by dingyiming** [comment]
好的，谢谢
