### ISSUE TITLE
请问下 dev 和 start有什么区别？

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#703]
真的很抱歉问了个比较弱智的问题，但我实在有点不懂

1.dev 和 start有什么区别？start是执行根目录的index.js文件，那dev是执行哪个？
2.本地开发的话应该执行哪个指令？
3.如果我要在入口文件进行一些初始化工作，如教程上的配置mysql方法
```
// 
{app_root}/app.js
module.exports = function(app) {
  app.beforeStart(function* () {
    // 从配置中心获取 MySQL 的配置
    // { host: 'mysql.com', port: '3306', user: 'test_user', password: 'test_password', database: 'test' }
    const mysqlConfig = yield app.configCenter.fetch('mysql');
    app.database = app.mysql.createInstance(mysqlConfig);
  });
};
```

应该在哪个文件上写？是不是执行start指令在index.js上面写这个？

**Comment by atian25** [comment]
- 本地开发用 `npm run dev`，线上用 index.js，后者看下文档中部署那一章，等 egg-scripts 写完后，后者也不需要写 index.js 了
- 第三个问题，你看第一行注释写着啥？

**Comment by Leungkingman** [comment]
@atian25 您好，首先谢谢您为我解答，但看了文档上的部署和本地开发那两章，还是有点不明白。
我知道第一行的注释是指根目录的app.js，但是我是通过 egg-init 来搭建项目的，项目生成之后根目录并没有app.js这个文件。
我有以下几个疑问：
1.这个app.js需要手动创建吗？
2.上面那段代码写在app.js之后，执行npm run dev指令是不是就可以执行app.js这个文件了？还是需要再额外配置一些东西？

对不起，我是后端的小白，谢谢。

**Comment by atian25** [comment]
app.js 自己创建就行了。 egg 运行起来后，所有文件都会加载的。就是 index.js 这个入口文件是用来启动 egg 的，dev 的时候用了自己的 start-cluster，所以不执行 index。

建议你先把官网文档看一遍，至少看完基础功能章节。

发自我的 iPhone

**Comment by ngot** [comment]
这种问题建议去gitter或者cnode，issue使用提交框架问题的。
