### ISSUE TITLE
Is there an API documentation? 

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#704]
* **Node Version**: 6
* **Egg Version**: 1.0.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

Hi, is there any API documentation available? I found it a bit hard to development without a clear API documentation. I am all onboard with the convention egg has, looks very reasonable and fine tuned. However, it does take a while to get used to. For example, in a helper class, how can I get access to app/ctx/config object? in a service class, how can I get access to app/ctx/logger class? If there is an API doc, it can be extremely helpful.

**Comment by caoer** [comment]
seems like a duplication of #581

**Comment by atian25** [comment]
for now, could take a look at https://eggjs.org/zh-cn/basics/extend.html

the API had generated, but still in progress to adjust jsdocs, PR is welcome

**Comment by atian25** [comment]
https://eggjs.org/api/

**Comment by atian25** [comment]
one simple rule, try `this.app.config/controller/loggers`, `this.ctx.service/helper/loggers`

**Comment by caoer** [comment]
👍  @atian25   simple and very useful explanation. 

I think there is missing documentation about 'Agent' class. I can only found it [here](https://eggjs.org/zh-cn/core/cluster-and-ipc.html) about how to use it. 

I do have a question for Agent class. Correct me if I'm wrong..
 Agent is quite independent from App or Context, communication is done via messager. What if I want to use things in the helper class? Can I do that? 

For example, I have a helper method which convert relative path to absolute path in a helper class. I'd like to reuse that as well in an agent implementation.

**Comment by atian25** [comment]
- `helper` is designed to use in template render.
- `agent` is a labor to do some dirty job. It will not restart when die, so be careful to use it.
- guide docs:
  - https://eggjs.org/zh-cn/core/cluster-and-ipc.html
  - https://eggjs.org/zh-cn/advanced/cluster-client.html

**Comment by caoer** [comment]
gotcha, then it is not suitable for the example I mentioned. It's good to put it into config. 

thanks for the help! 
btw, I think this issue should be good to close.
