### ISSUE TITLE
关闭session报错

### ISSUE THREAD

**Issue by xiangle** [eggjs/egg#705]
* **Node Version**:7.8.0
* **Egg Version**:1.0.0
* **Plugin Name**:Session
* **Plugin Version**:2.1.0
* **Platform**:windows

项目中不需要使用Session，配置{enable: false}会报错，static、view、i18n可以正常关闭

**Comment by atian25** [comment]
开着又不影响什么。。。不使用不会有损耗

发自我的 iPhone

**Comment by xiangle** [comment]
行，那就开着吧

**Comment by wsw0108** [comment]
middleware之间有依赖的，比如security依赖session。
