### ISSUE TITLE
请教：关于egg-mongoose使用的两个问题

### ISSUE THREAD

**Issue by feidianbo** [eggjs/egg#706]
* **Node Version**: 7.8.0
* **Egg Version**: 1.0.0
* **Plugin Name**: egg-mongoose
* **Plugin Version**:  1.1.1
* **Platform**: macOS

在用egg-mongoose的时，遇到了两个问题：

一个是，如何将一个schema中的一个属性类型设置为另外一个schema类型，例如：
```javascript
const PostSchema = new mongoose.Schema({
    // 标题
    title: {
      type: String,
      required: true,
      unique: false,
    },
    // 阅读者
    readers: [ UserSchema ],
....
```
上面的写法在运行时会直接报错。在egg中应该如何编写此类代码？

另外一个问题是，通过下面的代码，
```javascript
const users = this.ctx.model.user.find({});
```
可以获取mongodb中的Users集合中的数据，那保存用egg-mongoose是如何写法的呢？

**Comment by asmh1989** [comment]
我这两天尝试下来直接使用[Models](http://mongoosejs.com/docs/models.html)可以
而在[Schemas](http://mongoosejs.com/docs/guide.html)加方法不行

**Comment by TennyZhuang** [comment]
this.model 是 undefined

**Comment by jtyjty99999** [comment]
保存是 model.xxx.save().then() 

另外一个schema类型，是指的关联吗？

  var Schema = mongoose.Schema;
  var ObjectId = Schema.Types.ObjectId;

  var backupSchema = new Schema({
      user_id: {
        type: ObjectId,
        ref: 'User'
      },
  });

**Comment by feidianbo** [comment]
@jtyjty99999 
```javascript
this.ctx.model.user.save()...
```
像上面写保存数据时提示 this.ctx.model.user.save is not a function。

另外，如何将数据赋值到user对象中。

多谢。

**Comment by BoizZ** [comment]
有个疑问，`app/model/`下的文件怎么使用service里的方法？

**Comment by BoizZ** [comment]
对了， @feidianbo ，mongoose需要new一下才保存的，e.g. 
```
const userModel = new this.ctx.model.user(body)
userModel.save()...
```

**Comment by sasbsd** [comment]
app/model/下的文件怎么使用service里的方法，有人解决吗

**Comment by atian25** [comment]
app/model 不应该使用 service.

这个 issue 还有什么问题么?

**Comment by assmdx** [comment]
@BoizZ 为什么我new 之后 还是没有create方法呢
```
const userModel = new this.ctx.model.user()
userModel.create(data)...
```

**Comment by assmdx** [comment]
@jtyjty99999 有create方法吗？

**Comment by gu-xionghong** [comment]
我在 `app/model` 下遇到一种情况可能需要使用到 `service`
数据库使用 `egg-mongoose`，需要使用 `mongoose middleware`，在 `pre save` 的时候进行一系列的数据更新操作
```javascript
  schema.pre('save', async function(){
    await service.xx.method()
  })
```

**Comment by g8up** [comment]
@guohuihot 怪不得示例里没有 service 调用 model 的代码
