### ISSUE TITLE
关于egg-view插件root属性和render方法第一个参数的两个问题

### ISSUE THREAD

**Issue by hubcarl** [eggjs/egg#708]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

### 两个疑问：

- 社区egg1.0版本，在根据egg-view规范进行view插件开发时， 发现view的目录配置属性由内网版本path属性(string)改成了root属性（数组). 因为是数组，现在想获取view的根目录不好获取，不好界定取哪一个。

- 自定义egg－view插件实现render方法时， egg-view 插件会从root数组遍历查询文件，直到找到文件，render方法的第一个参数(文件名)在底层自动转成了文件的绝对路径.  因为root是数组，此时需要获取业务传进来的最初文件名就不好获取了。比如传进去的文件名为：video/detail.tpl  结果render里面拿到的 /Users/sky/dev/github/eggjs/egg-view-pagelet/test/fixtures/apps/pagelet/app/view/video/detail.tpl 

### 实际业务场景需求：

获取view的根目录和文件名主要是用来扩展view的解析逻辑：

1. 比如第三方view库需要一个基准根目录， 然后渲染时，只需要传递文件名即可， 在解析时，会自动转换成绝对路径或者根据文件名解析css/js资源依赖等等
2. 获取view的根目录做一些业务的处理逻辑。

现在想咨询一下，view的root属性设计成数组是出于什么目的？ 能不能在底层把当前文件名和文件名所在的目录透传到上层来？

**Comment by popomore** [comment]
这个有计划做，将 root 和原始文件名都传过来

```
render(name, locals, options) {
  // name 是全路径
  // options.root 是根目录
  // options.name 是文件名
}
```

**Comment by popomore** [comment]
> view的root属性设计成数组是出于什么目的

数组是为了支持多目录，还是有这种需求的。

**Comment by atian25** [comment]
chair 那边有多目录的场景？ 感觉更多场景应该是多引擎时，一个引擎放置一个目录

**Comment by popomore** [comment]
对，而且不止两个

**Comment by atian25** [comment]
这种情况下，其实每个引擎就用一个目录的，很少会有一个引擎多个目录的吧，寻址有点浪费了。不过有 cache 还好。

**Comment by popomore** [comment]
就是一个引擎要多目录，这个跟发布有关，我们有代码片段是单独发布到某个目录。

**Comment by atian25** [comment]
喔.
