### ISSUE TITLE
egg-schedule: 超过一定范围无效

### ISSUE THREAD

**Issue by strawberry224** [eggjs/egg#709]
* **Node Version**: 7.7.4
* **Egg Version**: 1.0
* **Plugin Name**: egg-schedule
* **Plugin Version**: 2.3.0
* **Platform**: ubuntu 14

egg-schedule通过setTimeout来控制程序运行的间隔时间，但是其参数有限制不能超过int的范围，因此当我执行如每月执行一次的定时任务时就不会按照预期运行。

**Comment by atian25** [comment]
你不是用egg-schedule 的 cron 方式？

**Comment by dead-horse** [comment]
@strawberry224 这类的定时任务确定不是你设计有问题？你的服务会超过一个月都不重启么？用 cron 类型的 schedule 吧

**Comment by atian25** [comment]
好像是有问题，cron 也是转 setTimeout 
@dead-horse

**Comment by dead-horse** [comment]
一年的毫秒数：365 * 24 * 60 * 60 * 1000 = 31536000000，你需要一个多长的定时任务会放不下？

**Comment by dead-horse** [comment]
https://github.com/nodejs/node/blob/master/lib/timers.js#L32 node 有做这个限制，大概是 24 天，egg-schedule 不支持设置超过这个长度的定时任务，我会去加 egg-schedule 加一下报错提示

**Comment by atian25** [comment]
应该是不支持两次间隔超过 24 天，只能设置小一点。自己判断了

**Comment by strawberry224** [comment]
谢谢大家的解答，因为我们的业务量不太大，我当时想一个月清理一次图片缓存文件夹，这个设计的间隔可能真的有点太大了，不过其实非要实现也不是不可以，比如大致可以这样：
```
  const max = 2 ** 31 - 1;
  nextTick -= now;
  while (nextTick > max) {
    nextTick -= max;
    setTimeout(() => {}, nextTick);
  }

  if (nextTick) {
    setTimeout(() => {
      listener();
      startCron(interval, listener);
    }, nextTick);
  }
```

**Comment by strawberry224** [comment]
谢谢大家的解答，由于业务量不大，我本想一个月清除一次临时图片文件，这个设计确实存在问题。如果不支持的话，我改小一点时间也是OK的 :)
不过其实非要实现应该也是可以的，比如循环执行setTimeout这种馊主意……：
```
function wait(nextTick, max) {
  return new Promise((resolve, reject) => {
    if (nextTick < max) {
      return resolve(nextTick);
    }

    setTimeout(() => {
      wait(nextTick - max, max);
    }, max);
  })
}
```
```
const TIMEOUT_MAX = 2147483647;
wait(nextTick - now, TIMEOUT_MAX).then(result => {
  setTimeout(() => {
    ... ...
  }, result);
});

```

**Comment by atian25** [comment]
@strawberry224 忘记说了，在 https://github.com/eggjs/egg-schedule/pull/19 已经解决这个问题了。
