### ISSUE TITLE
Controller目录中可加子目录分组吗

### ISSUE THREAD

**Issue by xiangle** [eggjs/egg#714]
将所有的Controller文件都放在同一层，感觉结构不清晰，甚至会产生命名冲突。尝试在路由中指定Controller路径，但是不行

**Comment by xiangle** [comment]
其实用驼峰感觉还行

**Comment by xiangle** [comment]
我在Service中找的了用点分割目录，router中测试正常，希望在文档中注明一下

**Comment by atian25** [comment]
支持目录的

**Comment by atian25** [comment]
app/controller/admin/user.js -> app.controller.admin.user.xx

service 也一样

**Comment by duncup** [comment]
目录结构
文件中所有约定目录结尾为`/**`的均可使用子目录
