### ISSUE TITLE
关于使用 egg-sequelize 的一些问题

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#715]
* **Node Version**: v7.7.2
* **Egg Version**: 1.0.0
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 
* **Platform**: Ubuntu 16

这是我使用sequelize 的一些 问题
当我定义了一个数据库连接
```js
// config/config.default.js
exports.sequelize = { 
  dialect: 'mysql',
  database: 'dev',
  host: '127.0.0.1',
  port: '3306',
  username: 'dev',
  password: '123',
};

```
并且也在pulgin 中 写入 了
```js
// config/plugin.js
exports.sequelize = { 
  enable: true,
  package: 'egg-sequelize'
};

```
当我在运行的时候

然后就报错了。
```bash
2017-04-01 17:27:55,015 ERROR 18296 nodejs.SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
```

然后我到 `/node_modules/egg-sequelize/config/config.default.js` 中去修改
```js
exports.sequelize = { 
  dialect: 'mysql',
  database: 'dev',
  host: '127.0.0.1',
  port: '3306',
  username: 'dev',
  password: '123',
};
```

发现就可以用了。

**Comment by atian25** [comment]
去掉你最后一步，然后按 https://eggjs.org/zh-cn/faq.html#为什么我的配置不生效 看看最终的配置是什么

**Comment by skyfore** [comment]
已经解决了，主要就是 在 `config`文件中
```js
//文件  config/config.default.js
module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1491354330722_7';

  return config;
};
```
> 主要就是使用 egg-init 初始化的config 文件中已经存在这一行了，所以就后面的 exports 没有用。

后面我换种方式然后就可以了 
```js
//文件  config/config.default.js
exports.sequelize = { 
  dialect: 'mysql',
  database: 'dev',
  host: 'localhost',
  port: 3306,
  username: 'dev',
  password: '123'
};

exports.keys = appInfo => {
  return appInfo.name + '_1491354330722_7';
};
```

这样就不会报错了。

**Comment by atian25** [comment]
... 别告诉我你之前的代码是：

```js
module.exports = appInfo => {
  const config = {};
  // ...
  return config;
}

exports. sequelize = {
  // ...
}
```

**Comment by skyfore** [comment]
...貌似是这样的。。。

**Comment by ngot** [comment]
这种 Node.js 基础问题,多看些书吧

**Comment by skyfore** [comment]
谢谢。

**Comment by sjyMystery** [comment]
不是nodejs的基础问题，斯以为egg-sequelize的github首页的文档比较欠妥，容易误导新手，望加以改进。

**Comment by lhwu** [comment]
> 去掉你最后一步，然后按 [https://eggjs.org/zh-cn/faq.html#为什么我的配置不生效](https://eggjs.org/zh-cn/faq.html#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E7%9A%84%E9%85%8D%E7%BD%AE%E4%B8%8D%E7%94%9F%E6%95%88) 看看最终的配置是什么

按照这个看到配置的 password，为 `<String len: 4>`，这个是正常的吗？

**Comment by lhwu** [comment]
创建的数据库名字中带有 `-`，通过 egg-sequeliz 就报这个错了...

**Comment by lijicheng123** [comment]
我也是同样的现象，但是我npm run dev是OK的，连上数据库后能正常处理业务，
当我准备上线构建的时候执行npm run ci就报了这个错误

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/15669871/170677200-61d15b47-ff6d-477c-ba0e-ed4c915e0582.png">
