### ISSUE TITLE
support router config

### ISSUE THREAD

**Issue by cuyl** [eggjs/egg#716]
* **Egg Version**: 1.0.0

希望加入router的config配置
[/eggjs/egg-core/blob/master/lib/egg.js#L304](https://github.com/eggjs/egg-core/blob/master/lib/egg.js#L304)
```javascript
  /**
   * get router
   * @member {Router} EggCore#router
   * @since 1.0.0
   */
  get router() {
    if (this[ROUTER]) {
      return this[ROUTER];
    }
    const router = this[ROUTER] = new Router({ sensitive: true }, this);
    // register router middleware
    this.use(router.middleware());
    return router;
  }
```

我观察到router在这里载入的时候吧option写死了，这样我想在config里面给router加上prefix貌似是不能实现的。能不能在这里传一个config进来，貌似在这里所有配置还没完全载入？
thanks

**Comment by popomore** [comment]
暂不考虑开放配置，可以尝试下用 app.router.prefix 来设置，但不知道需要设置 prefix 的场景。

**Comment by cuyl** [comment]
在config里面加的确是太麻烦了，看了下应该是用app.router.opts.prefix
我是这么用的
```javascript
// app/ router.js

module.exports = app => {
  // prefix
  app.router.opts.prefix = '/prefix';
  app.get('/','home.index'); // router to /prefix
};
```
希望加到文档里吧

**Comment by cuyl** [comment]
上面那个方法设置prefix只能在最前面写，
看了一下koa-router的文档，发现里面有设置prefix的方法。
[/alexmingoia/koa-router#routerprefixprefix--router](https://github.com/alexmingoia/koa-router#routerprefixprefix--router)
```javascript
// app/router.js

module.exports = app => {
  app.get('/','home.index'); // router to /prefix
  app.router.prefix('/prefix');
};

```

**Comment by atian25** [comment]
如果按 koa-router 的用法，是可以实例化多个 router，然后分别配置的，如果仅仅是全局配置，感觉没啥区别，就是所有的都省了几个字母而已。

**Comment by atian25** [comment]
```js
module.exports = app => {
  app.get('/','home.index'); // router to /prefix
  const adminRouter = app.router({ prefix: '/admin', controllerPrefix: 'admin' });
  // mount /admin/user/auth to app.controller.admin.user.auth
  adminRouter.get('/user/auth', 'user.auth');
};
```
真的要搞的话，可以考虑这样的实现。

但目前感觉场景不是很强烈吧，可以自己写插件来做做。

**Comment by cuyl** [comment]
考虑到有可能以后要改prefix，
直接查找替换的话不太好

**Comment by atian25** [comment]
`app.get(`/${prefix}/news/list`,'news.list');`

**Comment by cuyl** [comment]
这样做我都有考虑到，git diff好多不太好看，而且以后的都得这样写
我的解决方案是我上面写的那样，这在egg里面我都测试通过了。

**Comment by cuyl** [comment]
谢谢，问题已经解决了，使用`app.router.prefix('/prefix');`来设置全局prefix
