### ISSUE TITLE
egg有没有可能支持ES6的一些新特性语法

### ISSUE THREAD

**Issue by ztxcydzz** [eggjs/egg#718]
* **Node Version**: v7.8.0
* **Egg Version**: v1.0.0
* **Platform**: MacOS 10.12.4

在用egg构建后端项目的时候，有很多地方需要ES6的新特性，例如对象展开符、变量解构赋值等特性，有没有办法在egg中添加支持ES6写法的编译支持？

**Comment by JacksonTian** [comment]
已经可以用了。新特性与v8版本有关。跟Egg版本无关。
