### ISSUE TITLE
如何给nunjucks添加nunjucks-date-filter？

### ISSUE THREAD

**Issue by justinli0709** [eggjs/egg#722]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

var dateFilter = require('nunjucks-date-filter');

var env = new nunjucks.Environment();

env.addFilter('date', dateFilter);

这些代码应该写在什么地方？

或者egg-view-nunjucks插件是否有自带类似的helper?

**Comment by popomore** [comment]
支持 filter https://github.com/eggjs/egg-view-nunjucks/#filter

**Comment by justinli0709** [comment]
好的，谢谢
