### ISSUE TITLE
如何调整内置插件和自定义插件间的顺序

### ISSUE THREAD

**Issue by strawberry224** [eggjs/egg#723]
* **Node Version**: 7.7.4
* **Egg Version**: 1.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: ubuntu 14

{ session: [Function],
  i18n: [Function],
  static: [Function],
  bodyParser: [Function],
  meta: [Function],
  notfound: [Function],
  siteFile: [Function],
  middleware1: [Function],
  middleware2: [Function],
  middleware3: [Function] }

这是现在的插件顺序，我想把middleware1放在内置插件之前或中间的位置，可以设置吗？
比如变成这样：
{ middleware1: [Function],
  middleware2: [Function],
  session: [Function],
  i18n: [Function],
  middleware3: [Function],
  static: [Function],
  bodyParser: [Function],
  meta: [Function],
  notfound: [Function],
  siteFile: [Function],
 }

**Comment by popomore** [comment]
中间件顺序可修改 `app.config.coreMiddleware` 改变顺序。

**Comment by atian25** [comment]
可以调，但为什么要调？场景是？

发自我的 iPhone

**Comment by strawberry224** [comment]
谢谢解答，我明白了，场景的话确实不是很恰当，因为资源访问的时候要求先通过自己写的身份验证中间件才能访问，所以我就想直接通过调换static和token中间件的方式先试试，目前好像可以了。

**Comment by atian25** [comment]
这样的话，可以看上面那个 PR，在 app.js 里面，操作 coreMiddleware

**Comment by WormGirl** [comment]
如果插件都是第三方的，插件内有一些中间件，因为某些原因我需要调整中间件顺序，我可以在didLoad生命周期的时候直接修改app.middleware的顺序么 我试了下是有效的 会有啥隐患么  我测试了下在configWillLoad中插件的中间件还未加载到app.config.coreMiddleware中  所以无法调整顺序，除非我自己写个插件放在最后加载，这个插件专门修改app.config.coreMiddleware的顺序，还有其他方法么

**Comment by WormGirl** [comment]
为啥没有一个生命周期可以在app.config.coreMiddleware和app.config.appMiddleware合并成app.middleware之前修改coreMiddleware顺序的生命周期，在configWillLoad中插件的中间件还未加载，didLoad中插件的中间件加载了但是app.middleware已经合并完成，这时候修改coreMiddleware顺序无效

**Comment by atian25** [comment]
为什么要在这个时机点去修改呢？ 只要你请求没进来之前，你把合并后的 middleware 修改了不就行？

configWillLoad 那里也不是加载中间件， app.middleware 在这时候应该还只是一个 key array

**Comment by WormGirl** [comment]
一些三方插件有点问题  一时半会无法立即修改  需要在项目里先修复下  是想在所有插件的中间件加载完之后在有一次调整的机会，app.middleware在configWillLoad中是空数组，如果直接改app.middleware还不太好找，这里面存的都是函数，不是字符串，可能自定义个插件放最后去修改简单点

**Comment by atian25** [comment]
函数也没关系吧，你在 ready 前把那个数组给 splice 换下顺序就好了。

**Comment by WormGirl** [comment]
理论上没啥问题  就是我要先找到那个中间件的索引  只能通过Function.name去获取中间件名称，Function.name的取值又是一个比较复杂的规则，通常情况下根据这个判断是没问题的

**Comment by WormGirl** [comment]
> 为啥没有一个生命周期可以在app.config.coreMiddleware和app.config.appMiddleware合并成app.middleware之前修改coreMiddleware顺序的生命周期，在configWillLoad中插件的中间件还未加载，didLoad中插件的中间件加载了但是app.middleware已经合并完成，这时候修改coreMiddleware顺序无效

忽略了还有个configDidLoad钩子，这个钩子满足这个需求，没有问题了， 感谢回答
