### ISSUE TITLE
RESTful 风格的路由怎么给单个加中间件？

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#726]
RESTful 风格的路由怎么给单个加中间件？
`module.exports = app => {
  app.resources('posts', '/posts', 'posts');
};`

**Comment by atian25** [comment]
试试 `app.resources('posts', '/posts', middleware, 'posts');`

**Comment by callmesoul** [comment]
@atian25 我是说只加给其中一个或几个，不如get不用，post，delete要经过中间件这样。

**Comment by popomore** [comment]
在中间件加个过滤就好了

**Comment by callmesoul** [comment]
@popomore  那不是每个resources都要写一个中间件，如果有些post需要中间而有些🈶️不用的话

**Comment by atian25** [comment]
有需要的就自己挂上啊，你都描述了有不同的应用场景了，这个框架层肯定没法搞。

`app.resources('posts', '/posts', middleware, 'posts');`

自己挂载，自己在 Middleware 里面做处理

**Comment by callmesoul** [comment]
@atian25 这种需求一般都有的啊，应该会有考虑到的把

**Comment by atian25** [comment]
现在没有做不到啊，你就可以写个中间件来处理，
如果有一定规律的，你可以抽成插件。

只是目前没有感觉通用性很强需要内置到框架中。

发自我的 iPhone

**Comment by atian25** [comment]
你看下 egg-userrole ，在 role 定义里面判断下 method 就好了，一般就是 get 放过，其他需要授权

发自我的 iPhone

**Comment by popomore** [comment]
是的，如何使用都看你怎么设计。
