### ISSUE TITLE
源码学习疑惑, egg加载plugins 的入口文件在哪里啊？

### ISSUE THREAD

**Issue by kwoktung** [eggjs/egg#727]
学习看了 egg-core 和 egg 的源码，只发现egg-core有loadPlugin 的用来加载插件的配置，但是没发现 Plugin 实例化的地方。 我的功力不够，请问大家Plugin 是在什么什么地方被实例化的。

**Comment by popomore** [comment]
不会实例化，搜一下 loadunit，所有的文件会根据 loadunit 的顺序加载，插件是 loadunit 的一部分，Loader 有整个加载过程 https://eggjs.org/zh-cn/advanced/loader.html#loadunit
