### ISSUE TITLE
远程服务器启动项目

### ISSUE THREAD

**Issue by pandashuai** [eggjs/egg#728]
系统环境： ubuntu

当我使用  
```
EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &   
```
在远程服务器启动时访问可以，但我一关闭控制远程服务器的控制台就访问不了了

**Comment by SF-Zhou** [comment]
如果不是 root 权限，可以再执行一条 disown 把 node 进程放给系统管理。推荐使用 [pm2](https://github.com/Unitech/pm2) 去启动和管理 Node 应用。

**Comment by popomore** [comment]
用 nohup 应该不会退出吧

**Comment by SF-Zhou** [comment]
我测试是这样的，环境是 OS X + ZSH。
<img width="1440" alt="image" src="https://cloud.githubusercontent.com/assets/7477599/24826458/5437af1a-1c69-11e7-9769-a95ce2d269e0.png">

可以参考 [Difference between nohup, disown and &](http://unix.stackexchange.com/questions/3886/difference-between-nohup-disown-and) 和 [Why is chromium-browser killed when I close the terminal despite nohup?](http://unix.stackexchange.com/questions/162749/why-is-chromium-browser-killed-when-i-close-the-terminal-despite-nohup)。

> When you close a GNOME Terminal window, a SIGHUP is sent to the shell that it was running. The shell will typically send a SIGHUP to every process group that it knows it created - even ones started with nohup - and then exit. If the shell is bash, it will skip sending a SIGHUP to any process group that the user marked with disown.

> Running a command with nohup makes it ignore SIGHUP, but the process can change that. When the disposition of SIGHUP for a process is the default, then if it receives a SIGHUP, the process will be terminated.

**Comment by dead-horse** [comment]
先通过 exit 退出远程终端再关闭

**Comment by ngot** [comment]
还有一招，用 screen

**Comment by popomore** [comment]
可以看看上面的建议。
