### ISSUE TITLE
为什么Controller 不支持多级目录？

### ISSUE THREAD

**Issue by miaosun009** [eggjs/egg#731]
为什么service 支持多级目录，而Controller不支持多级目录？

**Comment by popomore** [comment]
支持的

**Comment by chinahsj** [comment]
我也是同样的问题，api明明写的是支持，但在controller下创建一个新的文件夹之后再到router.js 配置，发现是报错状态

**Comment by atian25** [comment]
用 `egg-init --type=simple` 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by chinahsj** [comment]
好的

2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 16:45
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

用 egg-init --type=simple 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by chinahsj** [comment]
OK了，60m 有点大
2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 16:45
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

用 egg-init --type=simple 初始化个最小可复现仓库，然后提交到你的 GitHub 吧

**Comment by atian25** [comment]
提交 GitHub，不要 node_modules 。

**Comment by atian25** [comment]
提交到你自己的 GitHub 仓库，不要 node_modules，不要 zip 。

**Comment by chinahsj** [comment]
好吧 没发过几次 

2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 17:07
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

提交 GitHub，不要 node_modules 。

**Comment by chinahsj** [comment]
你看上传的对吗

2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 17:07
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

提交 GitHub，不要 node_modules 。

**Comment by atian25** [comment]
`controller.child_controller.index.sayHi` -> `controller.childController.index.sayHi`

可以再回去看看 egg 文档，文件名会转为驼峰的。

**Comment by chinahsj** [comment]
哦哦，好的，马上去看。

2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 17:29
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

controller.child_controller.index.sayHi -> controller.childController.index.sayHi
可以再回去看看 egg 文档，文件名会转为驼峰的。

**Comment by chinahsj** [comment]
哇哦，看到了 api中说：“若需自定义自己的目录规范，参见 Loader API”，结果我就给略过，先看实例去了

2018-08-23 

m18210870360 



发件人：TZ | 天猪 <notifications@github.com>
发送时间：2018-08-23 17:29
主题：Re: [eggjs/egg] 为什么Controller 不支持多级目录？ (#731)
收件人："eggjs/egg"<egg@noreply.github.com>
抄送："calligrapherAndProgrammer"<m18210870360@163.com>,"Comment"<comment@noreply.github.com>

controller.child_controller.index.sayHi -> controller.childController.index.sayHi
可以再回去看看 egg 文档，文件名会转为驼峰的。
