### ISSUE TITLE
app.resources 如何绑定到多级控制器？

### ISSUE THREAD

**Issue by miaosun009** [eggjs/egg#733]
我用egg做restful api，

app/controller/v1/hello.js
上面是我的控制器位置

 用app.resources去绑定路由
app.resources('hello', '/api/v1/hello', 'v1/hello');

这样就无法通过编译， 提示Error: controller 'v1/hello' not exists , 说明找不到控制器，怎么回事? 0 0~~~

**Comment by dead-horse** [comment]
`v1.hello`
