### ISSUE TITLE
如何建立多个模块，比如frontend backend，前端后台 的代码我想放在不同的目录下

### ISSUE THREAD

**Issue by hpze2000** [eggjs/egg#735]
我发现 基础的service，数据model等这些可以用framework 来实现共用，但是类似 前端，后台，API接口， 如果我想用  类似 app_frontend, app_backend, app_api 这样分不同目录， 并且用不同的域名或二级域名指向到 这几个目录， 试了下， 不知道如何实现， 求助

**Comment by hpze2000** [comment]
附上我的方案， 反正凑合可用，  不懂对不对，具体实现是按framework的方式来的， 重写load的相关
`'use strict';

const AppWorkerLoader = require('egg').AppWorkerLoader;
const path = require('path');
const is = require('is-type-of');
const utility = require('utility');

function wrapClass(Controller) {
  const keys = Object.getOwnPropertyNames(Controller.prototype);
  const ret = {};
  for (const key of keys) {
    // getOwnPropertyNames will return constructor
    // that should be ignored
    if (key === 'constructor') {
      continue;
    }
    if (is.function(Controller.prototype[key])) {
      ret[key] = methodToMiddleware(Controller, key);
    }
  }
  return ret;

  function methodToMiddleware(Controller, key) {
    return function* classControllerMiddleware() {
      const controller = new Controller(this);
      const r = controller[key](this);
      // TODO: if we can check async function, then we can check it out of the middleware
      if (is.generator(r) || is.promise(r)) {
        yield r;
      }
    };
  }
}

function wrapObject(obj, path) {
  const keys = Object.keys(obj);
  const ret = {};
  for (const key of keys) {
    if (is.function(obj[key])) {
      const names = utility.getParamNames(obj[key]);
      if (names[0] === 'next') {
        throw new Error(`controller \`${key}\` should not use next as argument from file ${path}`);
      }
      ret[key] = functionToMiddleware(obj[key]);
    }
  }
  return ret;

  function functionToMiddleware(func) {
    return function* objectControllerMiddleware() {
      const r = func.call(this, this);
      if (is.generator(r) || is.promise(r)) {
        yield r;
      }
    };
  }
}

class YadanAppWorkerLoader extends AppWorkerLoader {
  load() {
    // 自己扩展
    const opt = Object.assign({
      caseStyle: 'lower',
      initializer: (obj, opt) => {
        // return class if it exports a function
        // ```js
        // module.exports = app => {
        //   return class HomeController extends app.Controller {};
        // }
        // ```
        if (is.function(obj) && !is.generatorFunction(obj) && !is.class(obj)) {
          obj = obj(this.app);
        }
        if (is.promise(obj)) {
          // module.exports = async ctx => ctx.body = 'hello';
          const displayPath = path.relative(this.app.baseDir, opt.path);
          throw new Error(`${displayPath} cannot be async function`);
        }
        if (is.class(obj)) {
          obj.prototype.pathName = opt.pathName;
          return wrapClass(obj);
        }
        if (is.object(obj)) {
          return wrapObject(obj, opt.path);
        }
        return obj;
      },
    }, null);

//   这里加载 你的目录包括controller，router，比如app1， app2，backend,  frontend，admin等 
//   目录这块 考虑配置到config 中就好了
    let directory = path.join(this.config.baseDir, 'app2/controller');
    this.loadToApp(directory, 'controller', opt);
    this.loadFile(path.join(this.config.baseDir, 'app2/router.js'));

    directory = path.join(this.config.baseDir, 'app1/controller');
    this.loadToApp(directory, 'controller', opt);
    this.loadFile(path.join(this.config.baseDir, 'app1/router.js'));


    super.load();
  }
}
module.exports = YadanAppWorkerLoader;
`

**Comment by popomore** [comment]
就自己写挺好的

**Comment by uedkx** [comment]
所以没有官方给出的方案么

**Comment by atian25** [comment]
推荐的方案是微服务，即多应用方式。

service 这些共用的通过 plugin 或 framework 方式去复用。

**Comment by andylei18** [comment]
function methodToMiddleware(Controller, key) {

    return function* classControllerMiddleware(...args) {
      const controller = new Controller(this);
      if (!this.app.config.controller || !this.app.config.controller.supportParams) {
        args = [ this ];
      }
      return yield callController(controller[key], controller, args);
    };
  }

这段代码什么意思。我看源码没看懂，而且走不通

**Comment by andylei18** [comment]
`function methodToMiddleware(Controller, key) {

    return function* classControllerMiddleware(...args) {
      const controller = new Controller(this);
      if (!this.app.config.controller || !this.app.config.controller.supportParams) {
        args = [ this ];
      }
      return yield callController(controller[key], controller, args);
    };
  }` 
这段代码什么意思。我看源码没看懂，而且走不通
