### ISSUE TITLE
power-assert in ES7 such as async

### ISSUE THREAD

**Issue by skyfore** [eggjs/egg#744]
* **Node Version**: v7.72
* **Egg Version**: v1.0.0
* **Plugin Name**: egg-bin
* **Plugin Version**:  v3.2.1
* **Platform**: Ubuntu 16

当我在测试一个异步的测试时，使用的是
```js
//eg

it('can use power-assert with ES7', async function() {
  let a = 1;
  assert(`${a}` === 1);
});

//这里应该是会报错的。
//但是报错的结果却并不是一般的显示出 `{a}`的值，然后对比，显示结果却是 ?
```

但是假如不使用 `async` 这种关键字就会和预想中的一样。
我初步猜测是 power-assert 不支持 ES7 的语法，
然后google搜到的解决方案是 使用 babel-plugin-espower 这个插件，但是我没有测试是否可行。 
所以提一个issues, 想问一下是否是这样的情况。当然，在正确的情况还是提示正常，不会报错。

**Comment by dead-horse** [comment]
报错截图看一下，async 的测试是支持的，可以看 https://github.com/eggjs/egg/blob/master/test/async/_async.js

**Comment by atian25** [comment]
@dead-horse 我这边可以复现

![image](https://cloud.githubusercontent.com/assets/227713/24943841/fe2cc70c-1f8a-11e7-88a7-4ac30d4017e9.png)

**Comment by skyfore** [comment]
@dead-horse async 是支持的，只是 power-assert 这个库可能不支持 async

**Comment by popomore** [comment]
好像我说的就是这个问题

**Comment by popomore** [comment]
我来跟吧

**Comment by skyfore** [comment]
@popomore  我要不要关闭这个issue

**Comment by atian25** [comment]
不用关。

**Comment by popomore** [comment]
https://github.com/twada/power-assert-runtime/pull/17

**Comment by popomore** [comment]
应该修复了

**Comment by skyfore** [comment]
好的，等会去看看。
