### ISSUE TITLE
希望可以增加一些配置项,可以配置插件内部的socket.io实例

### ISSUE THREAD

**Issue by bugss** [eggjs/egg#745]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
1.1.0
* **Platform**:

```javascript
///egg-socket.io/lib/io.js
app.on('server', server => {
// 希望能给attach 方法传些socket.io 的启动参数.如wsEngine:'uws' .这样就可以试下uWebSockets
// socket.io已经支持了
    app.io.attach(server);
    debug('[egg-socket.io] init ready!');
  });

```
就是内部socket.io的初始化配置能够通过egg的配置系统透过去.现在想到的就是wsEngine.这个貌似
必须要插件加代码才能透进去.

还有一个是serveClient,这个egg-socket.io 插件现在直接关闭了.不过在应用里面的app.js
里面加上app.io.serveClient(true)  可以重新打开. 虽然真实用的时候这个配置项关掉更好吧,打开的主要作用是更容易直接用页面熟悉这个插件的用法,而不是用单元测试

**Comment by ngot** [comment]
wsEngine 这个我加个配置来支持吧

**Comment by ngot** [comment]
+ egg-socket.io@1.2.0
