### ISSUE TITLE
egg-mysql添加字符串数据是报错

### ISSUE THREAD

**Issue by Leungkingman** [eggjs/egg#748]
* **Node Version**:7.7.1
* **Egg Version**:1.0.0
* **Plugin Name**:egg-mysql
* **Plugin Version**:2.0.0
* **Platform**:mac

添加数据时，数据为字符串的话会出现这个报错：
nodejs.ER_TRUNCATED_WRONG_VALUE_FOR_FIELDError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE8\x91\xAB\xE8\x8A\xA6...' for column 'name' at row 1
```
var row = {
   code: '000000',
   name: '葫芦娃',
   price: '14.67',
   swing: '8.43%',
   deal_price: '1.37亿',
   buy_in: '3442.22万',
   date: 1489507200
}
let addRes = yield db.insert(table, row)
```
报错显示是name字段出错，我name字段是varchar类型的。
一开始我还以为是我的数据有问题，后来我把它写死了还是报同样的错。查了一下相关错误，sequelize也有人遇到过这样的情况：
https://github.com/sequelize/sequelize/issues/1220

但是我把我mysql的配置试过改成 utf8\utf8mb4\gbk 都不行，请问这个是什么报错？应该怎么解决？
mysql的配置与文档上的教程无异，没有什么特殊配置。查询数据库和插入int类型的数据都是没问题的。

**Comment by popomore** [comment]
是不是配置成这个

```
     charset: 'utf8',
     dialectOptions: {
        collate: 'utf8_general_ci'
     },
```

**Comment by Leungkingman** [comment]
config.local.js 没有做这个配置，下面是config.local.js的配置代码：
```
module.exports = appInfo => {
  return {
    // 单数据库信息配置
    mysql: {
      client: {
        // host
        host: 'localhost',
        // 端口号
        port: '3900000',
        // 用户名
        user: 'root',
        // 密码
        password: '可能是个假密码',
        // 数据库名
        database: '葫芦娃',
      },
      // 是否加载到 app 上，默认开启
      app: true,
      // 是否加载到 agent 上，默认关闭
      agent: false
    },
    //请求地址
    HOST: 'http://localhost:7001/'
  }
}
```
我本地数据库是用navicat来手动创建的

**Comment by Leungkingman** [comment]
已经解决了，光是数据库设置成utf8没有用，要数据表也要设置成utf8才行。我是设置了数据库，没有设置数据表

**Comment by fangxu864** [comment]
我是数据库设置了，表也设置了，字段没设置，导致存不了，搞了半天；
后来改了下字段的字符集就好了
