### ISSUE TITLE
egg-mongoose  使用问题

### ISSUE THREAD

**Issue by sasbsd** [eggjs/egg#753]
请问，使用egg-mongoose 在app/model/下的定义model文件中怎么使用service里的方法

**Comment by zhangming0305** [comment]
如果你在model里调用service，多半是使用方法不对，model里是不应该调用service的。应该是从反方向使用的。或者你详细说一下你这么做的情景。

**Comment by dead-horse** [comment]
恩，这个是禁止的，不然分层就没有意义了

**Comment by sasbsd** [comment]
egg-mongoose  中使用 mongoose的 middleware 比如 定义完model后，在
`UserSchema.post('save', function (doc) {
 console.log('%s has been saved', doc._id);
//调用 框架的 service 进行日志登记，消息发送等
 });
`

**Comment by popomore** [comment]
把他当成 model 就好了，不要使用的这么复杂。
