### ISSUE TITLE
[疑问] Service支持使用exports的编写方式吗？

### ISSUE THREAD

**Issue by nolanctt** [eggjs/egg#754]
Service是否支持使用exports的编写方式？

**Comment by atian25** [comment]
支持.

**Comment by nolanctt** [comment]
那要如何获取到**ctx**和**app**对象呢？ @atian25

**Comment by atian25** [comment]
```js
module.exports = app => {
  return {
     * test() {}
  };
}
```

可以拿到 app，但 ctx 目前应该拿不到， https://github.com/eggjs/egg-core/blob/master/lib/loader/context_loader.js

**Comment by atian25** [comment]
cc @popomore

**Comment by popomore** [comment]
为什么不用 class 呢，不推荐用其他方式。

**Comment by LiShiSangZi** [comment]
请问如果出现service之间的互相调用该如何处理呢？

**Comment by atian25** [comment]
用 class 方式，然后 ctx.service.xxx.yyy()

发自我的 iPhone

**Comment by tong3jie** [comment]
在ctx.service.xxx.yyy中调用ctx.service.aaa.bbb()不成功。

**Comment by atian25** [comment]
提供最小可复现代码库
