### ISSUE TITLE
egg-async-validator

### ISSUE THREAD

**Issue by LiShiSangZi** [eggjs/egg#757]
这个插件egg-async-validator在npm上找不到。
https://www.npmjs.com/search?q=egg-async-validator&page=1&ranking=optimal

但是版本号是1.0.0。

这是什么原因啊？

@fengmk2

**Comment by popomore** [comment]
没发版本

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-async-validator 是空的，都没有做

**Comment by dead-horse** [comment]
现在的 validate 插件是这个 https://github.com/eggjs/egg-validate

**Comment by LiShiSangZi** [comment]
刚刚试了一下 https://github.com/eggjs/egg-validate
index的这个方法并灭有调用到 :(
我是错过了什么东西吗？
