### ISSUE TITLE
How to specify a custom folder for common files under middle ware   

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#758]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
please give some more informations

**Comment by atian25** [comment]
```js
egg-example
├── lib
│   └── utils.js
├── app
│   └──  middleware
│       └── robot.js
├── config
└── package.json
```

**Comment by AkashiX** [comment]
```
egg-example
├── lib
│   └── utils.js
├── app
│   └──  middleware
│       └── handler
│           └── ExceptionHandler.js
│       └── filter
├── config
└── package.json
```
Such like this. What is the way I can use it in exports.middleware on config files.

**Comment by dead-horse** [comment]
middleware don't support sub directory now, please put all your middlewares in `app/middleware`, you can require other files just like @atian25 said.

**Comment by atian25** [comment]
feel free to reopen if any message about this issue.
