### ISSUE TITLE
关于 egg-mongoose 插件的问题

### ISSUE THREAD

**Issue by looneyren** [eggjs/egg#761]
1. 根据 egg 文档，提倡通过 service 来实现 model 的相应功能，为何 egg-mongoose 没有遵循此规则呢？
2.根据 egg-mongoose 插件的例子，export 出的是 mongoose 的 model ，这样的做法也没有将业务逻辑很好的包装，会导致 controller 承担业务层面的很多内容，是不是不太合理。

感觉此插件比 egg 的规则慢了几个层次啊，求正确姿势。

**Comment by looneyren** [comment]
看来只是在 model 中封装 mongoose 的各类 schema 后，再创建 service 调用 model 实现业务逻辑是可行的，不过略显麻烦啊。

**Comment by zhangming0305** [comment]
业务逻辑写入service层, service层再被controller调用

**Comment by popomore** [comment]
分层就是这个意思
