### ISSUE TITLE
DEBUG模式下修改代码无法刷新的问题

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#762]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by ngot** [comment]
Node Version: ?
Egg Version: ?
Plugin Name:?
Plugin Version:?
Platform:?

**Comment by popomore** [comment]
这里的 debug 模式是指 `egg-bin debug` 吗

**Comment by AkashiX** [comment]
@popomore 是的

**Comment by atian25** [comment]
目前 egg-development 中，禁止了自动重启。

https://github.com/eggjs/egg-development/blob/master/agent.js#L41

当时应该是为了防止断点中断？ @shaoshuai0102

**Comment by shaoshuai0102** [comment]
这儿我不太清楚历史原因哎，猜测是的，这样貌似也合理

**Comment by popomore** [comment]
好像是说重启会修改 debug 端口

**Comment by atian25** [comment]
嗯，端口会变，用 devtool 的话估计会有问题。

但 WebStorm 的会自动 attach。

不过，现在如果配合上 https://github.com/eggjs/egg-development-proxyworker 的话，应该就不用担心端口变的问题了。

**Comment by popomore** [comment]
那可以改下

**Comment by atian25** [comment]
@AkashiX 删除 node_modules 重新安装依赖即可

**Comment by AkashiX** [comment]
@atian25 还需要做什么配置没

**Comment by atian25** [comment]
不需要，默认开启了。

**Comment by AkashiX** [comment]
@atian25 刚测试可以了，还有个问题就是刷新之后端口会变，这个有什么办法可以解决。

**Comment by AkashiX** [comment]
@atian25 使用proxyworker能否解决。

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/core/development.html#使用-vscode-进行调试

**Comment by AkashiX** [comment]
Solved. Thux more.
