### ISSUE TITLE
如何读取逐行读取文件？

### ISSUE THREAD

**Issue by proshuai** [eggjs/egg#764]
如何利用egg逐行读取日志文件

**Comment by bshy522** [comment]
这跟egg没关系。
逐行读文件 可以用 node内建的模块 readline。

https://nodejs.org/dist/latest-v6.x/docs/api/readline.html

**Comment by proshuai** [comment]
ok，我以为里面有集成的方法呢，想把自己之前写的读取监控日志改造一下。
