### ISSUE TITLE
在egg上用typescript来开发是非常好的一个方式，不知什么时候官方能提供egg及相关组件的type定义？

### ISSUE THREAD

**Issue by lnngle** [eggjs/egg#766]

**Comment by popomore** [comment]
https://github.com/eggjs/egg/pull/760

**Comment by Rwing** [comment]
呃 刚想说我准备来做这个事情，发现原来已经有了#760，那太好了

**Comment by cuyl** [comment]
赞，我也想问这个问题，看来早就有人想到了

**Comment by dead-horse** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15971

已经发布到 @types/egg 和 @types/egg-mock

**Comment by atian25** [comment]
当 Egg 遇到 TypeScript，收获茶叶蛋一枚

https://zhuanlan.zhihu.com/p/35334932
