### ISSUE TITLE
使用egg-view-vue直接报错

### ISSUE THREAD

**Issue by Paul88** [eggjs/egg#768]
官方的使用：
// {app_root}/config/plugin.js
exports.view-vue = {
  enable: true,
  package: 'egg-view-vue',
};

但结果直接报错，开始也觉得有这种“view-vue”的变量，结果一跑果然出错了，蛋疼！！

**Comment by dead-horse** [comment]
这个模块还有问题， @atian25 还没改完吧

**Comment by atian25** [comment]
@hubcarl 那边正在开发中

**Comment by acodercat** [comment]
exports['view-vue'] = {

};

**Comment by atian25** [comment]
那边已经开发完了，等这几天我找时间 review 下合并发版本

**Comment by xjchenhao** [comment]
@atian25 `egg-view-vue`还不能发布使用吗

**Comment by ZQun** [comment]
egg-view-vue 上线了吗？  @atian25

**Comment by atian25** [comment]
还没，我本周内找时间搞搞。

**Comment by callmesoul** [comment]
同求啊！！都等了很久了。 @atian25

**Comment by atian25** [comment]
https://github.com/eggjs/egg-view-vue/pull/4

**Comment by atian25** [comment]
已经发布 1.0.0，久等了，各位可以试用下。

但仅仅是 vue 的服务端渲染，实际业务一般是需要和 webpack 配合的，那块 @hubcarl 正在搞。

**Comment by acodercat** [comment]
nice！辛苦

**Comment by xjchenhao** [comment]
辛苦🙏🏻

**Comment by SteveCruise** [comment]
我想要vue spa的，仅仅进行数据通信，靠post

**Comment by atian25** [comment]
那你不需要用这个插件啊，直接放到 public

发自我的 iPhone

**Comment by hubcarl** [comment]
egg + vue + webpack server side render:  https://github.com/hubcarl/egg-vue-webpack-boilerplate
