### ISSUE TITLE
关于 egg-mongoose 插件通过 _id 进行查询的性能问题

### ISSUE THREAD

**Issue by looneyren** [eggjs/egg#769]
在使用 egg-mongoose 插件进行 _id 检索时，发现性能下降的很厉害，测试环境： imac i5(2.8G) + 8G + SSD ，mongo 的 collection 中有2条数据，在控制器中执行下面的测试：

测试 1：
`
let id = 'xxxxx';
const doc = yield this.ctx.model.xxxxx.find({ });
this.ctx.body = doc
`
查询全部，耗时 18-30ms 左右；

测试 2：
`
let id = 'xxxxx';
const doc = yield this.ctx.model.xxxxx.find({ _id:id });
this.ctx.body = doc
`
通过 _id 查询，耗时 120-140ms 左右，注：_id 是默认索引

测试 3：
`
let name = 'xxxxx';
const doc = yield this.ctx.model.xxxxx.find({ name:name });
this.ctx.body = doc
`
通过 name 查询，耗时 18-30ms 左右，注：name 并非索引

方法1和3的测试结果相同，与方法2就差在是否加入 _id 条件，测试差 100ms 左右，但使用测试2的查询方法，直接引用 mongoose 进行测试则没有此延迟问题，各位是否有相似的问题出现？

**Comment by atian25** [comment]
索引问题?

**Comment by looneyren** [comment]
_id 是 collection 的默认索引，经查实确实如此

**Comment by dead-horse** [comment]
mongoose 相关的问题，最好去 mongoose 社区提问，egg-mongoose 只是链接了 mongoose 和 egg

**Comment by looneyren** [comment]
问题是直接用 mongoose 问题是不存在的啊，用 egg-mongoose 去连接才有这个问题的。。。

**Comment by atian25** [comment]
cc @jtyjty99999

**Comment by jtyjty99999** [comment]
可以使用 mongodb profiler (docs.mongodb.org/manual/tutorial/manage-the-database-profil‌​er) 来看看到底出现了什么问题

**Comment by jtyjty99999** [comment]
确认下egg-mongoose依赖的mongodb/mongoose版本跟你使用的mongoose版本一样吗？ 之前 java 那边有过类似的这个问题  http://stackoverflow.com/questions/22603694/mongodb-slow-query-by-id

**Comment by looneyren** [comment]
是一样的，在同一个项目中 mongodb:2.2.25  mongoose:4.9.5
