### ISSUE TITLE
example with dva

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#77]
https://github.com/dvajs/dva-knowledgemap

**Comment by zhoudaqing** [comment]
这个太赞，整理的比较全，辛苦了fengmk2团队，es6 新特性不了解的看过来

**Comment by soulmachine** [comment]
Still, in the link above I don't see any example with both eggjs and dva working together

**Comment by atian25** [comment]
@xufei ^_^

**Comment by Kunoky** [comment]
这个就是那个DVA知识地图，跟egg好像没什么关系啊

**Comment by dead-horse** [comment]
先关了
