### ISSUE TITLE
egg里多表联合查询怎么做，我看你们那个教程没写

### ISSUE THREAD

**Issue by cokeknight** [eggjs/egg#770]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by dead-horse** [comment]
这是 mysql 的基础知识，与 egg 无关

**Comment by cokeknight** [comment]
@dead-horse 那我们就只能手写sql去联合查询了吧？

**Comment by atian25** [comment]
你指的是 egg-mysql 插件还是?

**Comment by cokeknight** [comment]
@atian25 是egg-mysql插件。

**Comment by jtyjty99999** [comment]
可以用 egg-sequelize  等 orm 框架，比如 sequelize 就支持联查： http://docs.sequelizejs.com/en/latest/docs/querying/#relations-associations

**Comment by cokeknight** [comment]
@jtyjty99999 谢谢。
