### ISSUE TITLE
请问，使用了egg-socket.io，等待的时间长了会提示WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by DarksKnight** [eggjs/egg#771]
请问，哪里可以设置这个时间。。

**Comment by ngot** [comment]
@DarksKnight 
https://github.com/primus/primus/commit/c34d2812b016abf10240567d13ce2acebbc481bd 这个原因？

**Comment by ngot** [comment]
另外请提供：
Node Version:
Egg Version:
Plugin Name:
Plugin Version:
Platform:

还有最小可复现代码

**Comment by atian25** [comment]
? 关闭问题的时候最好提下缘由

**Comment by DarksKnight** [comment]
发现是因为没有在socket连接回调中就发送请求了。
