### ISSUE TITLE
[egg-mysql] 如何打印sql语句执行日志

### ISSUE THREAD

**Issue by nolanctt** [eggjs/egg#773]
是否有配置或者方法可以打印出每一次执行的sql语句？

**Comment by buzai** [comment]
@HSunboy 你找到办法了么

**Comment by atian25** [comment]
egg-mysql 底层是 https://github.com/ali-sdk/ali-rds 可以去翻翻源码

**Comment by buzai** [comment]
@atian25 嗯。我现在就是在那里面加上了log，但是感觉不太好啊

**Comment by atian25** [comment]
肯定不能直接修改源码，是让你看源码有没有接口可以配置，没有的话可以往那边提需求或者直接 PR

**Comment by buzai** [comment]
@atian25 那个项目貌似是个kpi项目下面的问题都没人回答

**Comment by solarhell** [comment]
`DEBUG=ali-rds* egg-bin dev
另外不要张嘴闭嘴kpi项目。开源项目 不喜欢就自己写

**Comment by buzai** [comment]
@solarhell 行那我删了，谢谢

**Comment by loky555** [comment]
正解：由于egg-mysql最终还是调用mysql库，如果只是想查看调试可打开mysql debug
config.mysql = { 
    // 单数据库信息配置
    client: { 
        host: '', port: '',
        user: '', password: '',
        database: '',
        dateStrings: 'DATETIME',
        debug: true
    }, 
    app: true,
    agent: false
};
