### ISSUE TITLE
线上prod环境下，/:id类的接口会报500错误

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#775]
* **Node Version**: 7.9
* **Egg Version**: 1.1

线上部署EGG_SERVER_ENV=prod npm start，这类app.get('/api/order/:id',  controller)接口，请求会报500错误，开发环境npm run dev和npm start能正常访问

**Comment by AkashiX** [comment]
异常贴出来看看

**Comment by ngot** [comment]
提供下最小复现代码

**Comment by TDiDa** [comment]
`'use strict';

module.exports = app => {
  app.get('/api/order/:id', 'order.queryId');
};
`
`EGG_SERVER_ENV=prod npm start 启动`

访问http://127.0.0.1/api/order/123， 报500错误

**Comment by atian25** [comment]
@TDiDa 提供具体报错日志啊

**Comment by TDiDa** [comment]
我这边的错误，线上数据库出问题了
