### ISSUE TITLE
egg-oss 插件无法找到

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#777]
c:\Users\Akashi\Desktop\_my_case\oss-case\node_modules\egg-core\lib\loader\mixin\plugin.js:340
    throw new Error(`Can not find plugin ${name} in "${lookupDirs.join(', ')}"`);
    ^
Error: Can not find plugin oss in "c:\Users\Akashi\Desktop\_my_case\oss-case\node_modules, c:\Users\Akashi\Desktop\_my_case\oss-case\node_modules\egg\node_modules, c:\Users\Akashi\Desktop\_my_case\oss-case\node_modules"

I got an error when I installed and tried to run.

**Comment by atian25** [comment]
plz show up your `plugin.js`, and check whether egg-oss exists at these paths

发自我的 iPhone

**Comment by AkashiX** [comment]
```js
// config/plugin.js
// had enabled by egg
// exports.static = true;
exports.oss = true;

exports.proxyworker = {
  enable: true,
  package: 'egg-development-proxyworker',
};
```
I'm sure there it is.

**Comment by atian25** [comment]
I'm sure you should read docs again 😂.

```js
exports.oss = { 
 enable: true, 
 package: 'egg-oss',
 };
```

发自我的 iPhone

> 在 2017年4月20日，08:48，M.Y.Akashi <notifications@github.com> 写道：
> 
> exports.oss = true; exports.proxyworker = { enable: true, package: 'egg-development-proxyworker', };

**Comment by AkashiX** [comment]
= = ...it's a stupid mistake, I feel terribly sorry about it..
