### ISSUE TITLE
用form发请求，egg的ctx.request.body为空

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#779]
我用postman发post请求
![image](https://cloud.githubusercontent.com/assets/21269645/25210850/80959d66-25b4-11e7-9da6-680f35a298a7.png)
egg.js 里面代码
'use strict';

module.exports = app => {
  class HomeController extends app.Controller {
    * index() {
      console.log(this.ctx.request.body);
      this.ctx.body = 'hi, egg';
    }
  }
  return HomeController;
};

log出来是｛｝
如何能取到表单数据？
node v7.8 "egg": "^1.1.0"

**Comment by dead-horse** [comment]
```
* index() {
  console.log(this.headers);
  console.log(this.ctx.request.body);
  this.ctx.body = 'hi, egg';
}
```
看看打出的请求头是什么

**Comment by AkashiX** [comment]
form-data请求改为x-www-form-urlencoded，立即生效。

**Comment by grubed** [comment]
@dead-horse
        console.log(this.headers);
        console.log(this.ctx.request.body);
结果是
undefined
{}

@AkashiX form-data请求改为x-www-form-urlencoded，可以！

**Comment by dead-horse** [comment]
刚才写错，应该是：

```js
 console.log(this.ctx.headers);
```

@grubed 这个情况要排查你客户端请求的时候带的请求头中的 content-type 是什么，egg 只会解析 x-www-form-urlencoded 和 json 格式的数据。
