### ISSUE TITLE
egg-oss能不能增加对获取sts的相关逻辑实现

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#781]
* **Node Version**:">=6.0.0"
* **Egg Version**:"^1.0.0",
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:Windows 10

**Comment by AkashiX** [comment]
Solved.

**Comment by atian25** [comment]
close 也要遵循基本法啊，描述下如何 solved 的，方便后人。
