### ISSUE TITLE
egg-leancloud 插件如何读取登录用户信息？

### ISSUE THREAD

**Issue by kainy** [eggjs/egg#782]
* **Node Version**: v6.4.0
* **Egg Version**: latest
* **Plugin Name**:  egg-leancloud
* **Plugin Version**: 1.0.0
* **Platform**: OS X

leancloud 官方的示例代码：

> ``` javascript
> // 查看个人资料
> app.get('/profile', function(req, res) {
>   // 判断用户是否已经登录
>   if (req.currentUser) {
>     // 如果已经登录，发送当前登录用户信息。
>     res.send(req.currentUser);
>   } else {
>     // 没有登录，跳转到登录页面。
>     res.redirect('/login');
>   }
> });
> ```

在 controller 里这样写：

``` javascript
class HomeController extends app.Controller {
    * index(ctx) {
      console.log(ctx.request.currentUser);   // undefined
    }
  }
```
好些访问不到，求教是否调用方式有问题。

**Comment by atian25** [comment]
leancloud 没怎么用过，还没想好怎么和 egg-passport 结合。

现在可以考虑直接挂载下他们提供的 Middleware：

https://leancloud.cn/docs/leanengine_webhosting_guide-node.html#用户状态管理

伪代码如下：

```js
// app/middleware/leancloud-session.js
module.exports = (options, app) => {
  const config = Object.assign({
    framework: 'koa', 
    // secret: 'my secret', 
    // maxAge: 3600000, 
    // fetchUser: true,
  }, options)
  return app.AV.Cloud.CookieSession(config);
}
```

**Comment by atian25** [comment]
cc @fengmk2 有什么建议不?

**Comment by popomore** [comment]
建议就是别搞这么，没精力

**Comment by atian25** [comment]
@popomore 这个我们这边业务中用不到，肯定只能交给社区支撑了。

**Comment by popomore** [comment]
文档上可以加个 `MAINTAINER REQUIRED`

**Comment by atian25** [comment]
https://github.com/eggjs/egg-leancloud/pull/2

**Comment by kainy** [comment]
好吧，等偶消化消化这颗 egg 后再回来研究研究。
