### ISSUE TITLE
controller直接暴露为一个函数时，请求总是404

### ISSUE THREAD

**Issue by aiyadingya** [eggjs/egg#785]
* **Node Version**:
6.10.2
* **Egg Version**:
├── egg@1.1.0
├── egg-bin@3.3.0
├── egg-view-nunjucks@2.0.0
├── koa-is-json@1.0.0
└── moment@2.18.1
* **Platform**:
mac 10.12.4

我是在看文文档：
https://eggjs.org/zh-cn/basics/router.html
里面的“destroy 实战”-“Query String 方式”的例子的时候遇到的，

 ![image](http://gh2.oss-cn-hangzhou.aliyuncs.com/static/Jietu20170421-135701.jpg)

上面的search.js 这个controller直接暴露成一个函数，结果怎么访问返回 “404 Not Found”，

但我把search.js 改成：

`exports.search = ...`  
同时 router里面也做修改就可以访问到页面，

所以把controller直接暴露为一个函数应该是bug

**Comment by dead-horse** [comment]
我看看吧
