### ISSUE TITLE
在开发模式下修改controller下的文件不会自动加载。

### ISSUE THREAD

**Issue by arden** [eggjs/egg#788]
我在开发模式下修改controller下的文件不会自动加载，只有修改config目录下的文件才会自动加载，这是什么情况？

**Comment by atian25** [comment]
删除 node_modules 重新安装依赖再试试。

你是用 `npm run dev` 启动的吧?

**Comment by arden** [comment]
现在用的就是npm run dev，我重新安装下依赖看看吧。

**Comment by atian25** [comment]
没用 vagrant 吧？

发自我的 iPhone

**Comment by arden** [comment]
删除了node_modules，再重新安装还是不行，但是我用egg-init初始化一个simple的项目，就可以加载。但是我对比了一下我的工程都一样的，没啥区别。
没有用vagrant.

**Comment by arden** [comment]
@atian25 我刚又试了一下，app目录下的文件可以自动加载，但是app目录下的子目录下的文件不会自动加载。包括controller、service下的文件都不会。

**Comment by arden** [comment]
@atian25 我刚又测试了一下，原来在webstorm开发工具里直接修改文件后不会自动加载，但是在editplus里修改文件后会自动加载，奇怪。但是在webstorm里直接修改config目录下的文件，又会自动加载。

**Comment by atian25** [comment]
关闭 webstorm 的 safe save。文档中有提过。

发自我的 iPhone
