### ISSUE TITLE
如何在Middleware获取Session

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#795]

**Comment by atian25** [comment]
koa2 style: ctx.session
koa1 style: this.session

发自我的 iPhone

**Comment by AkashiX** [comment]
结果：{}
附加一下说明，这里我用了egg-session插件，session在登陆后存在memory。我的想法是在middleware做一个session filter，用于校验session是否存在。

**Comment by AkashiX** [comment]
Solved.

**Comment by ngot** [comment]
session默认存于客户端cookie，而不是内存

**Comment by AkashiX** [comment]
@ngot 我表述不完整，我参考egg-session把session存到memory里边。

**Comment by atian25** [comment]
多进程的时候，存内存没意义啊。你应该用 https://github.com/eggjs/egg-session-redis 这类的插件。

**Comment by dead-horse** [comment]
多进程将 session 存内存就会导致你上面说的，session 找不到，真实线上运行的时候就懵逼了。

**Comment by dead-horse** [comment]
session 小存 cookie， session 很大存 redis，可以看看  egg-session-redis 插件
