### ISSUE TITLE
请求STS通过增加Callback参数以达成客户端请求触发回调的目的，请问有没有对应的简单实现？

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#796]
As above.

**Comment by atian25** [comment]
没看懂

**Comment by AkashiX** [comment]
https://help.aliyun.com/document_detail/31989.html?spm=5176.product31815.6.870.FR5KGy

**Comment by popomore** [comment]
这要看 [ali-oss](https://github.com/ali-sdk/ali-oss) 支不支持

**Comment by popomore** [comment]
研究下 https://github.com/ali-sdk/ali-oss 好了，没使用过这个功能。
