### ISSUE TITLE
本地以"dev": "EGG_SERVER_ENV=local egg-bin dev",的方式启动为什么会缓存模板

### ISSUE THREAD

**Issue by cokeknight** [eggjs/egg#798]
如题，我在本地的package.json把原来的dev命令改成了EGG_SERVER_ENV=local egg-bin dev，结果就缓存模板了，去掉即可，但是文档里EGG_SERVER_ENV设置为local就是本地开发环境，不知道为什么不能这么设置

**Comment by atian25** [comment]
- `egg-bin dev` 的时候，不需要手动配置 EGG_SERVER_ENV 为 local。
- 是哪一个模板插件?
- 看下 run/application_config.json 里面的对应的模板的配置是什么

**Comment by cokeknight** [comment]
@atian25 模板引擎是nunjucks，就是想了解为什么手动配置了 EGG_SERVER_ENV 为 local 就不行了，你们文档说那个是本地开发环境的，是我理解错了吗

**Comment by atian25** [comment]
你先看下 `run/application_config.json` 里面 config.nunjucks 和 config.env 的取值，贴上来

**Comment by cokeknight** [comment]
@atian25 
"nunjucks": {
      "autoescape": true,
      "throwOnUndefined": false,
      "trimBlocks": false,
      "lstripBlocks": false,
      "cache": false
    },
"env": "local",

**Comment by cokeknight** [comment]
刚才贴的是不加环境的配置，
    "nunjucks": {
      "enable": true,
      "package": "egg-view-nunjucks",
      "name": "nunjucks",
      "dependencies": [
        "security",
        "view"
      ],
      "optionalDependencies": [],
      "env": [],
      "from": "H:\\cat_admin\\config\\plugin.js",
      "path": "H:\\cat_admin\\node_modules\\egg-view-nunjucks",
      "version": "2.0.0"
    },
这个是加了环境的配置，不好意思贴错了 @atian25

**Comment by dead-horse** [comment]
@cokeknight windows 还是 mac？

**Comment by dead-horse** [comment]
看 path 是 windows，windows 设置环境变量的方式错了导致的

**Comment by atian25** [comment]
@cokeknight 你给的第二个是 plugin.nunjucks 了, 不是 config.nunjucks

**Comment by cokeknight** [comment]
"nunjucks": {
      "autoescape": true,
      "throwOnUndefined": false,
      "trimBlocks": false,
      "lstripBlocks": false,
      "cache": true
    },
@atian25  这个吧，我执行的命令是"devwindow": "set EGG_SERVER_ENV=local && egg-bin dev",，是window环境，这个cache还很是true。

**Comment by atian25** [comment]
config.env 呢

**Comment by cokeknight** [comment]
"nunjucks": {
  "autoescape": true,
  "throwOnUndefined": false,
  "trimBlocks": false,
  "lstripBlocks": false,
  "cache": true
},
"env": "local ", @atian25

**Comment by atian25** [comment]
贴下  config.local.js

发自我的 iPhone

**Comment by popomore** [comment]
给个能重现的仓库看看？

**Comment by atian25** [comment]
ping @cokeknight

**Comment by popomore** [comment]
是解决了么

**Comment by popomore** [comment]
关了，如又问题可以继续回复。
