### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#799]
使用angular请求egg.js
Headers({ 'Content-Type': 'application/json' });
post /login
报跨域错误
XMLHttpRequest cannot load http://127.0.0.1:7001/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.

egg用了
exports.cors = {
    enable: true,
    package: 'egg-cors',
};
 security: {

        domainWhiteList: [ '127.0.0.1:7000', '127.0.0.1:7001','127.0.0.1:8081','127.0.0.1:4200'],
        methodnoallow: {
              enable: false
        },
｝

// router.js
  app.options('/login', 'home.allow');
  app.post('/login', 'user.login');

//home.js
    * allow() {
        this.ctx.set('Access-Control-Allow-Origin:*');
        this.ctx.status = 200;
        this.ctx.body = {};
      }
home.allow可以收到请求，user.login没收到

**Comment by AkashiX** [comment]
有插件可以解决


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：grubed <notifications@github.com>
时间：周一 4月24日 14:50
收件人：eggjs/egg <egg@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[eggjs/egg] 跨域问题 (#799)

**Comment by grubed** [comment]
@AkashiX 什么插件？怎么使用？

**Comment by grubed** [comment]
改成这样好像还是不行
//plugin.js
exports.cors = {
    enable: true,
    package: 'egg-cors',
};
// config.js
      security: {

        domainWhiteList: ['http://127.0.0.1:4200'],
        // methodnoallow: {
        //       enable: false
        // },
        xframe: {
          enable: false,
        },
        csrf: {
          enable: false,
          headerName: 'x-csrf-token',
          cookieName: 'csrfToken',
        },
      },

**Comment by grubed** [comment]
解决了，原来是白名单写错了，不能写127.0.0.1,要写成localhost

**Comment by AkashiX** [comment]
egg cors


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：grubed <notifications@github.com>
时间：周一 4月24日 14:55
收件人：eggjs/egg <egg@noreply.github.com>
抄送："M.Y.Akashi" <yanzhi.mo@aliyun.com>,Mention <mention@noreply.github.com>
主题：Re: [eggjs/egg] 跨域问题 (#799)

**Comment by atian25** [comment]
@jtyjty99999 egg-security 那边要不要对 domainWhiteList 做下检测，这些明显不合法的值，给报错

**Comment by jtyjty99999** [comment]
@atian25 以前有工具方法判断，现在是直接读的，不知道怎么做检测比较好

**Comment by atian25** [comment]
插件的 app.js 在启动时判断一次?
