### ISSUE TITLE
socket.io中的一个疑问

### ISSUE THREAD

**Issue by bugss** [eggjs/egg#803]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

假如我配置了一个connection中间件 conn.
```javascript
io:{
namespace: {
      '/': {
        connectionMiddleware: [ 'conn' ],
        packetMiddleware: ['auth'],
      }
}
```
其中conn 里面这么写
```javascript
 this.socket.on('myNameIs', function (name) {})
```

然后我在路由里面加上
```javascript
  app.io.route('chat.sendMsg', app.io.controllers.chat.sendMsg)
```

但是我在前端我不断的,
socket.emit('myNameIs','1111')
就是不
socket.emit('chat.sendMsg','1111')

那对于
packetMiddleware: ['auth'], 这个中间件,由于没有ctx.emit('finshed') 发生,
packetMiddlewareInit.js 里面的compose 会一直挂起,会不会内存泄漏?

**Comment by ngot** [comment]
不会的，你看这里 https://github.com/eggjs/egg-socket.io/blob/master/lib/packetMiddlewareInit.js#L25 自己手动on的时间，不会添加钩子去hold连接的。每个请求都是单个事务级别的，请求只要能正常返回，就不会造成内存泄露。

**Comment by bugss** [comment]
问题就在这个判断:if (nsp[RouterConfigSymbol])   .
自己手工在connectionMiddleware 中间件里面on 如myNameIs,同时在router.js 里面 
```javascript
 app.io.route('chat.sendMsg', app.io.controllers.chat.sendMsg) 
```
 无论如何下面的判断都会是true吧
```javascript
// 只要调用过 app.io.route('chat.sendMsg')注册过,不管发过来的事件是不是在nsp中存在,都会为TRUE
if (nsp[RouterConfigSymbol])   
```

**Comment by ngot** [comment]
貌似是这样的...

**Comment by ngot** [comment]
@bugss 求来个PR修复下

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/13

**Comment by ngot** [comment]
+ egg-socket.io@1.2.1
