### ISSUE TITLE
application/octet-stream 想问下这个类型的请求怎么接收二进制数据呢

### ISSUE THREAD

**Issue by zackCzy** [eggjs/egg#804]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by popomore** [comment]
是 client 接收还是 server 接收？

**Comment by zackCzy** [comment]
client

**Comment by zackCzy** [comment]
找不到对应的方法

**Comment by popomore** [comment]
你如果自己实现就拿到 res `on('data')` 就好了，或者用 [urllib](https://github.com/node-modules/urllib) 指定 content 是 buffer。

**Comment by popomore** [comment]
好像跟 egg 没关系
