### ISSUE TITLE
egg-sequelize和egg-mongoose两个插件怎么样才同时使用？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#805]
egg-sequelize和egg-mongoose两个插件怎么样才同时使用？
我现在发现egg-mongoose会去自动加载非mongodb的model，从而造成报错。

**Comment by dead-horse** [comment]
什么场景会同时使用两个？

**Comment by arden** [comment]
有时候一些日志数据啥的，或者用户session啥的可能用的就是mongoose，其它重要的数据用的就是mysql了。

**Comment by popomore** [comment]
看来没有 model 插件之前都放在 model 目录下不是很好，暂时支持自定义目录吧?

**Comment by jtyjty99999** [comment]
可以支持的啊，可以配置

**Comment by jtyjty99999** [comment]
两个插件都可以配置 modelDir的，但是主要的问题是 app.model 可能会冲突，如果真的要用的话，model名字不要起一样的

**Comment by popomore** [comment]
@jtyjty99999 现在不支持，你来接单吧

**Comment by arden** [comment]
这两个插件，如果app/model下面建了子目录，子目录下面有mode类，会不会加载？

**Comment by popomore** [comment]
应该默认支持的

**Comment by denghongcai** [comment]
`egg-sequelize` 的 `modelDir` 和 `app.model` 都不可自定义，我来改下

**Comment by jtyjty99999** [comment]
@denghongcai 👍  我记错了，以为以前还支持的

**Comment by arden** [comment]
@jtyjty99999 这个什么时候能调好，还准备自己fork一份代码调了。

**Comment by dead-horse** [comment]
@arden 着急你就直接发 PR 来改嘛

**Comment by jtyjty99999** [comment]
@arden 你现在直接配置 egg-mongoose 的 modelDir 就能跑起来啊，我们只是在支持 egg-sequelize

**Comment by popomore** [comment]
egg-mongoose 也发布了

**Comment by shanzemin** [comment]
请问这个问题最终的解决方案是怎样的？

**Comment by Q-Angelo** [comment]
问题现在还存在 今天在使用的被坑了一次 半天没找到原因

**Comment by shanzemin** [comment]
> 问题现在还存在 今天在使用的被坑了一次 半天没找到原因

这个是我写的一个测试例子，两个插件可以共存，可以参考看看
https://github.com/shanzemin/egg-test

**Comment by LeoFengFromChina** [comment]
### 关于多类型数据源支持（sequelize和mongoose）
> 一个egg项目要同时支持sequelize和mongoose，需要做特殊的配置。</br>

- 由于mongoose支持的默认加载model的路径无法修改（`app/model`),所以只能修改sequelize的model加载路径；

- 修改配置：
```
config.sequelize = {
    dialect: 'mysql',
    host: '...',
    port: 3306,
    database: '...',
    username: 'root',
    password: '...',
    delegate: 'sequelizeModel', //挂载到app上的model名称，此配置后可以通过app.sequelizeModel访问
    baseDir: 'model/sequelize', //由于mongoose已占用了默认的model路径，所以新增一个sequelize文件夹来存储sequelize要检测的model文件
  };    
```
- 调用方式：`ctx.sequelizeModel.User.findAll()`

**Comment by Hareis** [comment]
> ### 关于多类型数据源支持（sequelize和mongoose）
> > 一个egg项目要同时支持sequelize和mongoose，需要做特殊的配置。
> 
> * 由于mongoose支持的默认加载model的路径无法修改（`app/model`),所以只能修改sequelize的model加载路径；
> * 修改配置：
> 
> ```
> config.sequelize = {
>     dialect: 'mysql',
>     host: '...',
>     port: 3306,
>     database: '...',
>     username: 'root',
>     password: '...',
>     delegate: 'sequelizeModel', //挂载到app上的model名称，此配置后可以通过app.sequelizeModel访问
>     baseDir: 'model/sequelize', //由于mongoose已占用了默认的model路径，所以新增一个sequelize文件夹来存储sequelize要检测的model文件
>   };    
> ```
> 
> * 调用方式：`ctx.sequelizeModel.User.findAll()`

我也试着像你这样写了 ，但是好像没什么用

**Comment by oneWalker** [comment]
> > ### 关于多类型数据源支持（sequelize和mongoose）
> > > 一个egg项目要同时支持sequelize和mongoose，需要做特殊的配置。
> > 
> > 
> > 
> > * 由于mongoose支持的默认加载model的路径无法修改（`app/model`),所以只能修改sequelize的model加载路径；
> > * 修改配置：
> > 
> > ```
> > config.sequelize = {
> >     dialect: 'mysql',
> >     host: '...',
> >     port: 3306,
> >     database: '...',
> >     username: 'root',
> >     password: '...',
> >     delegate: 'sequelizeModel', //挂载到app上的model名称，此配置后可以通过app.sequelizeModel访问
> >     baseDir: 'model/sequelize', //由于mongoose已占用了默认的model路径，所以新增一个sequelize文件夹来存储sequelize要检测的model文件
> >   };    
> > ```
> > 
> > 
> > 
> > * 调用方式：`ctx.sequelizeModel.User.findAll()`
> 
> 我也试着像你这样写了 ，但是好像没什么用

baseDir里面不是“model/sequelize”，直接用`baseDir:sequelize` 就应该在model下。

**Comment by shanzemin** [comment]
> > 问题现在还存在 今天在使用的被坑了一次 半天没找到原因
> 
> 这个是我写的一个测试例子，两个插件可以共存，可以参考看看
> https://github.com/shanzemin/mongo-mysql

很尴尬，我贴错仓库地址了，上面的地址已经更正了，具体可以看下：mysql默认是在/app/model下，mongo默认是在app/mongo下
mongo是挂载到app对象下了，具体调用方法是`app.mongo.User.find()`
mysql还是原来的调用：`ctx.model.Student.find()`

**Comment by oneWalker** [comment]
> https://github.com/shanzemin/mongo-mysql

egg-mongoose不支持目录自定义
所以只能自定义egg-sequelize//定义sequelize的配置文件
```js
  config.sequelize = {
    dialect:'mysql',//支持多个sql类的
    database:"how2java",
    host:"localhost",
    port:3306,
    username:"root",
    password:'root',
    delegate:'sqlModel',//定义挂载到框架上为ctx.sqlModel
    baseDir:'sqlModel',//定义model文件目录 model/`${sqlModel}`
    define:{ //定义表时的相关的设置，也可在表中单独定义 
      //timestamps:false,  //是否支持自动生产created_at，updated_at.,deleted_at,自动生成的时间为标准时间
      underscored: true, //是否支持驼峰转为表的下划线
      freezeTableName:true, //不自动将表名转换为复数形式
      //paranoid:false, //删除是否自动插入时间
    }
  }
```

**Comment by tyhyly** [comment]
只有楼上老兄的管用，mongo-mysql那个不管用，看了下egg-mongoose的源码，请看
`version: 3.3.1`

```js
function loadModelToApp(app) {
  const dir = path.join(app.config.baseDir, 'app/model');
  app.loader.loadToApp(dir, 'model', {
    inject: app,
    caseStyle: 'upper',
    filter(model) {
      return typeof model === 'function' && model.prototype instanceof app.mongoose.Model;
    },
  });
}
```

**Comment by oneWalker** [comment]
正好看到有邮件通知；
我将原来的egg-mongoose进行了修改，使得能够支持和egg-sequelize一样的自定义目录存放位置和引用方式。并提交到了Pull reuqests里面。
但是，egg-mongoose好像没有人维护了，所以进行了重新发布。
[npm发布地址](https://www.npmjs.com/package/@onewalker/egg-mongoose)

**Comment by ZQun** [comment]
本邮件是邮箱系统自动回复邮件！已成功收到您的邮件。

另注：请复制以下代码即可查看，
<xq>q_un<un07>

**Comment by bigmgreen** [comment]
> > https://github.com/shanzemin/mongo-mysql
> 
> egg-mongoose不支持目录自定义 所以只能自定义egg-sequelize//定义sequelize的配置文件
> 
> ```js
>   config.sequelize = {
>     dialect:'mysql',//支持多个sql类的
>     database:"test",
>     host:"localhost",
>     port:3306,
>     username:"root",
>     password:'root',
>     delegate:'sqlModel',//定义挂载到框架上为ctx.sqlModel
>     baseDir:'sqlModel',//定义model文件目录app/`${sqlModel}`
>     define:{ //定义表时的相关的设置，也可在表中单独定义 
>       //timestamps:false,  //是否支持自动生产created_at，updated_at.,deleted_at,自动生成的时间为标准时间
>       underscored: true, //是否支持驼峰转为表的下划线
>       freezeTableName:true, //不自动将表名转换为复数形式
>       //paranoid:false, //删除是否自动插入时间
>     }
>   }
> ```

实测有效
