### ISSUE TITLE
使用 egg-bin 进行测试时设置 NODE_ENV 环境变量未生效

### ISSUE THREAD

**Issue by Carrotzpc** [eggjs/egg#806]
在使用 egg-bin 测试生产环境配置时，需要设置 `NODE_ENV` 环境变量：
```
NODE_ENV=prod egg-bin test test\config\config.test.js
```
运行命令后发现 `NODE_ENV` 未生效，测试了其他环境变量时可以的，于是翻了下源码，原来是写死了`NODE_ENV` 为 `test`，还好可以通过指定 `EGG_SERVER_ENV=prod `来解决这个问题。

[egg-bin 源码 `blob/master/lib/cmd/test.js#L37`：](https://github.com/eggjs/egg-bin/blob/master/lib/cmd/test.js#L37)
```js
  * run(context) {
    process.env.NODE_ENV = 'test';
    const testArgs = this.formatTestArgs(context);
    const opt = {
      env: Object.assign({}, process.env),
      execArgv: context.execArgv,
    };
    const mochaFile = require.resolve('mocha/bin/_mocha');
    debug('run test: %s %s', mochaFile, testArgs.join(' '));
    yield this.helper.forkNode(mochaFile, testArgs, opt);
  }
```

**就是想问下这么写是有什么特殊的用意吗？如果没有的话，建议不要写死，可以改成 `NODE_ENV` 默认为 `test`。**

**Comment by atian25** [comment]
问题是，你配置 `NODE_ENV` 用途是？  egg 的环境变量是用 `EGG_SERVER_ENV` 而不是 `NODE_ENV`

**Comment by Carrotzpc** [comment]
用意就是指定 egg 的环境变量，egg 文档里面有相关描述：
> 例如，当 `NODE_ENV` 为 `production` 而 `EGG_SERVER_ENV` 未指定时，框架会将 `EGG_SERVER_ENV` 设置成 `prod`。https://eggjs.org/zh-cn/basics/env.html 

我感觉写死不是很合理

**Comment by atian25** [comment]
egg 的环境变量就是制定 `EGG_SERVER_ENV` 就好了啊.

本身 `egg-bin dev` 就是开发期用的，想线上运行的命令来测试的话，应该用 index.js 启动方式，或者等 egg-scripts。

**Comment by atian25** [comment]
@popomore `process.env.NODE_ENV = 'test';` 改为 `process.env.NODE_ENV = process.env.NODE_ENV || 'test';` ?

**Comment by popomore** [comment]
`NODE_ENV = test` 不等于 `EGG_SERVER_ENV=test`，因为你在运行 `egg-bin test`，所以 `NODE_ENV` 肯定是 test，而对应的 `EGG_SERVER_ENV` 为 unittest。

如果你想在测试用例里面测试各种环境可以这么写

```js
before(() => {
  mm.env('prod');
  app = mm.app({
    cache: false,
  });
  return app.ready();
})
```

**Comment by Carrotzpc** [comment]
在测试用例里面用 `mm` 设置环境变量倒是个好办法，谢谢两位 @atian25 @popomore
