### ISSUE TITLE
curl如何设置jwt的token

### ISSUE THREAD

**Issue by xxwade** [eggjs/egg#807]
两个egg之间通过 jwt 来交互，设置了相同的secret，尝试用cookie和header两种方法传递token，均返回未授权，想问下应该怎么将token带过去

![image](https://cloud.githubusercontent.com/assets/1948312/25367889/60ee89b4-29ab-11e7-9e07-9f2cca04a23d.png)

**Comment by dead-horse** [comment]
你是要传递请求中带过来的 jwt token 么？第一句 `this.ctx.cookies.set` 没看懂在做什么

**Comment by atian25** [comment]
this.ctx.cookies 是丢给用户侧的，不会丢给 curl 那边，这是两个不同的东西。

curl 的底层是 https://www.npmjs.com/package/urllib，你通过 header 传递过去 cookie 即可。

`ctx.culr(url, {  headers }`

**Comment by xxwade** [comment]
@atian25 恩，this.ctx.cookies.set 的理解有问题，已放headers中，成功取到值了，3q

**Comment by xxwade** [comment]
@atian25 恩， 对 this.ctx.cookies 的理解有问题
改为下图写法，还是401
<img width="579" alt="1" src="https://cloud.githubusercontent.com/assets/1948312/25370110/1343a4f0-29bb-11e7-9f81-10456601d3ba.png">

接收端未使用 app.jwt  是能够接收到 set-cookie 的字段的

**Comment by atian25** [comment]
先把问题定位好，先确认从协议层面，curl 过去对面收到的 headers 是否符合规范，然后是那边解析是否正确。

app.jwt 是你自己写的插件吧？

**Comment by xxwade** [comment]
app.jwt 是 egg-jwt
找到问题了，原来不是当cookie传过去的， 3q
<img width="622" alt="3" src="https://cloud.githubusercontent.com/assets/1948312/25370667/cc930dc6-29be-11e7-9420-6ae4c6c14b01.png">

**Comment by atian25** [comment]
egg-jwt 好像不是我们写的

**Comment by okoala** [comment]
@xxwade  egg-jwt 是我这边集成进来的，仔细看 koa-jwt 和 jwt 的文档就行了~
