### ISSUE TITLE
Win7 下 VScode 调试问题：按照文档配置，不能正常启动

### ISSUE THREAD

**Issue by xiaosansiji** [eggjs/egg#809]
* **Node Version**: v6.9.3
* **Egg Version**: 1.1.0
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: Windows 7, VScode

Hi~ 我参照官方文档[这里](https://eggjs.org/zh-cn/core/development.html#使用-egg-bin-调试)配置了VScode 调试，已增加 egg-development-proxyworker 依赖，已按照
**启动插件**
**在 .vscode/launch.json 添加调试配置**
所示增加配置。
启动Debug Egg后会有如下报错信息：
![error](https://cloud.githubusercontent.com/assets/7600149/25377454/354a368a-29da-11e7-8713-44a4e14e80c6.png)

这里是因为控制台中，无法确定 node 的版本号所以没能启用 inspector 新协议导致的问题吗？
我的 launch.json 配置如下：

```
"version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Egg",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "npm",
      "windows": {
        "runtimeExecutable": "npm.cmd"
      },
      "runtimeArgs": ["run", "debug"],
      "port": 5858
    },
    {
      "name": "Attach Agent",
      "type": "node",
      "request": "attach",
      "port": 5856
    },
    {
      "name": "Attach Worker",
      "type": "node",
      "request": "attach",
      "restart": true,
      "port": 10086,
      "protocol": "inspector"
    }
  ],
  "compounds": [
    {
      "name": "Debug Egg",
      "configurations": ["Launch Egg", "Attach Agent", "Attach Worker"]
    }
  ]
```

**Comment by okoala** [comment]
@xiaosansiji  你把控制台的日志完整的贴下～

**Comment by popomore** [comment]
`run debug` 和 `run -- --debug` 的差异，这个在 vscode 有区别么

**Comment by atian25** [comment]
run debug 是默认 --inspect

发自我的 iPhone

**Comment by okoala** [comment]
@popomore  有的啊~使用的调试协议不一样

**Comment by atian25** [comment]
node 版本多少？ 我怀疑是 process.debugPort 问题，6.x 用 inspect，拿到的 debugPort 有问题

**Comment by popomore** [comment]
但用了 vscode 为啥要 inspect 啊，已经有了客户端了。

**Comment by atian25** [comment]
vscode 跟 inspect 不冲突吧，debug 协议要干掉了。

发自我的 iPhone

**Comment by atian25** [comment]
`Node Version: v6.9.3` 果然， @okoala ，在 6.x 下用 `process.debugPort` 是不准确的。

**Comment by atian25** [comment]
@xiaosansiji 你按文档，先换回第一种用法，不要用 inspect

**Comment by xiaosansiji** [comment]
好滴，谢谢各位大神的帮助，不过看起来我应该升级下node版本了:)

**Comment by Rwing** [comment]
呃，之前没试过，刚按照文档试了下，我也报错了
Node: v7.6

> 正在使用旧版协议调试，因为设置了运行时可执行文件。
Debugging with legacy protocol because Node.js version could not be determined: Error: connect ECONNREFUSED 127.0.0.1:5856
Debugging with legacy protocol because Node.js version could not be determined: Error: connect ECONNREFUSED 127.0.0.1:10086
npm run dev -- --debug 
> ats-exam-center@1.0.0 dev /Users/Rwing/Project/test
> egg-bin dev --debug "--debug"
Error: getaddrinfo ENOTFOUND true
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by Rwing** [comment]
好像文档里缺少了 package.json 中 script/dev 的写法

**Comment by atian25** [comment]
@Rwing 这些在本地开发，在测试很多地方的文档里面都会有提到，另外如果你用 egg-init 生成的项目都已经会有了。
