### ISSUE TITLE
上传200多M的视频最后才10M

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#815]
* **Node Version**:
v7.3
* **Egg Version**:
v1.01
* **Plugin Name**:

* **Plugin Version**:
* **Platform**:
使用      const ws = fs.createWriteStream(‘/path/to/myvedio’);
      stream.pipe(ws);
      ws.on("error", function() {
        reject(false);
      });
      ws.on("finish", function() {
})
是否需要更改什么配置

**Comment by jinchaoxiang** [comment]
用了multipart

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-multipart/blob/master/config/config.default.js#L12 fileSize 参数需要调整。

**Comment by fengmk2** [comment]
你将 fileSize 参数改成你最大允许的文件大小即可。

**Comment by chenyulun** [comment]
为什么不能捕捉错误，是因为你们引用了`http://github.com/mscdex/busboy.git`,这个组件都没完善，无法捕捉错误，写了一个node_modules/busboy/lib/types/multipart.js
```javascript
        onData = function(data) {
          if ((nsize += data.length) > fileSizeLimit) {
            var extralen = (fileSizeLimit - (nsize - data.length));
            if (extralen > 0)
              file.push(data.slice(0, extralen));
            file.emit('limit');
            file.truncated = true;
            part.removeAllListeners('data');
          } else if (!file.push(data))
            self._pause = true;
        };


然而并没有file.on('limit',function() {});
```javascript
onData = function(data) {
          if ((nsize += data.length) > fieldSizeLimit) {
            var extralen = (fieldSizeLimit - (nsize - data.length));
            buffer += data.toString('binary', 0, extralen);
            truncated = true;
            part.removeAllListeners('data');
          } else
            buffer += data.toString('binary');
        };
```
fieldSize设置了直接截取，什么错误都不发出来
我怎么友好提示用户我后台存储截断了，和他上传的不一样啊？
自定义的方法都没提供？

**Comment by 14glwu** [comment]
> 为什么不能捕捉错误，是因为你们引用了`http://github.com/mscdex/busboy.git`,这个组件都没完善，无法捕捉错误，写了一个node_modules/busboy/lib/types/multipart.js
> 
> ```js
>         onData = function(data) {
>           if ((nsize += data.length) > fileSizeLimit) {
>             var extralen = (fileSizeLimit - (nsize - data.length));
>             if (extralen > 0)
>               file.push(data.slice(0, extralen));
>             file.emit('limit');
>             file.truncated = true;
>             part.removeAllListeners('data');
>           } else if (!file.push(data))
>             self._pause = true;
>         };
> 
> 
> 然而并没有file.on('limit',function() {});
> ```javascript
> onData = function(data) {
>           if ((nsize += data.length) > fieldSizeLimit) {
>             var extralen = (fieldSizeLimit - (nsize - data.length));
>             buffer += data.toString('binary', 0, extralen);
>             truncated = true;
>             part.removeAllListeners('data');
>           } else
>             buffer += data.toString('binary');
>         };
> ```
> 
> fieldSize设置了直接截取，什么错误都不发出来
> 我怎么友好提示用户我后台存储截断了，和他上传的不一样啊？
> 自定义的方法都没提供？

老哥，我和你一样的问题，现在正为这个问题发愁，我自己去监听了limit的方法，但是抛出的错误，egg框架捕获不了。
