### ISSUE TITLE
需求: 中间件获取下一层中间件的返回值

### ISSUE THREAD

**Issue by cycgit** [eggjs/egg#817]
```
// app/controller/home.js
exports.index = function* () {
  return 'hello world';
}
// app/middleare/mm.js
module.exports = function() {
  return function*(next) {
    const res = yield next;
    this.body = res;   // hello world
  }
}
```
### 好处

1.  业务逻辑更加简练，return返回后，不必担心`this.body`被覆盖。

2. 更加符合JSDoc的书写规范，定义返回值。

**Comment by ngot** [comment]
这是spring的类似写法。中间件的话，应该去koa开issue。如果只改controller，整体风格又不统一了。

**Comment by dead-horse** [comment]
不建议这样使用有三个原因：

1. 中间件基本上只能保证顺序先后，很难保证绝对按照顺序，例如可以通过配置加载全局的中间件，也可以在路由中使用中间件，这样你通过配置加载的处理 body 的中间件很可能并不会紧跟 controller，而且也有可能会有插件强行插入中间件的情况。
2. 不论是 egg 还是 koa，想要实现获取 controller 的返回值都依赖于路由库，如果路由库实现逻辑有变化或者切换了路由库，可能这个功能就失效了。
3. koa 生态都是通过 this.body 来设置响应，因为你通常还需要设置 status、设置 headers，只有一个返回值是不够用的。

**Comment by bshy522** [comment]
middleware需要返回什么？这是关键。最后你会发现 你想要返回给下个middleware或controller的值最终还是要放到context里面，因为你a middleware返回的值 可能 b middleware用不到 但是 controller会用到。

还有就是这是 koa-compose的问题，如果做这种级别的改动，可能影响整个koa生态现有的东西。

**Comment by cycgit** [comment]
@bshy522 
1.  koa目前是支持的next返回值。只是没有说明有这个特性，存在随时取消的可能性。
2. 是否目前koa生态插件都没有用到next的返回值，如果取消了。会有多少插件不可用？
3. 如果已经有koa插件使用这个特性，那么egg也应该支持把。

**Comment by dead-horse** [comment]
这不是一个功能，所以 egg 不会考虑去支持它，如果现在 egg 的实现 **恰好**支持了那就支持了，如果现在的实现没有支持，我们也不会考虑去实现它。

**Comment by atian25** [comment]
@cycgit 既然不是 koa 声明的功能，而且也不符合生态圈的约定，达不到「公认的约定」，故我们是不会考虑为了几个 koa 插件来支持这个的。你真的有需要的话，可以自己写个 egg 插件来支持这个约定，应该不会太难。
