### ISSUE TITLE
egg与微信sdk集成

### ISSUE THREAD

**Issue by zhoudaqing** [eggjs/egg#82]
egg与微信集成有plugin么？ 希望提供，感谢

**Comment by atian25** [comment]
有钉钉的，还没有微信的，后面会补一个。

**Comment by fengmk2** [comment]
@jacksontian 写过一个微信模块

**Comment by atian25** [comment]
https://github.com/node-webot

这是很早前写的了, 还没有 egg 插件

**Comment by popomore** [comment]
有客户端写插件就简单了

**Comment by zhoudaqing** [comment]
@jacksontian 微信模块插件什么时候提供呢？ 多谢

**Comment by zhoudaqing** [comment]
@fengmk2  你上次说@jacksontian 写过一个微信模块， 请发一下链接 谢谢

**Comment by atian25** [comment]
@zhoudaqing 上面我发的那个

**Comment by lzq920** [comment]
@atian25 @popomore [https://github.com/JKshare/egg-wechat ](https://github.com/JKshare/egg-wechat )

这个插件符合不？我在github上搜到的，但是没找到相关的文档和示例

**Comment by udbmnm** [comment]
可以直接使用https://github.com/node-webot/co-wechat

**Comment by xxmyjk** [comment]
直接用朴大[](https://github.com/node-webot) 下面co开头的相关包, co-wechat目前已经更新了使用文档

**Comment by thonatos** [comment]
好像我包过一个。

https://github.com/thonatos/egg-wechat-api
