### ISSUE TITLE
有人在sae上部署egg么？

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#822]
有人在sae上部署egg么？
研究了很久没弄懂啊。
有的话写个教程呗。

**Comment by okoala** [comment]
@callmesoul  看看是不是这个地址？ [sae-nodejs-getting-started](https://www.sinacloud.com/doc/sae/docker/nodejs-getting-started.html)

**Comment by callmesoul** [comment]
@okoala 就是跟着这个来的，一只跑不了，502

**Comment by popomore** [comment]
port 有指定 process.env.PORT 吗

**Comment by atian25** [comment]
如果是 egg-init 生成的，应该有 process.env.PORT 在 index.js 里面

**Comment by okoala** [comment]
看来我们还是需要这块的文档~

**Comment by callmesoul** [comment]
不是端口问题

**Comment by popomore** [comment]
这个跟 egg 没啥关系，自己试下怎么部署吧。

@okoala 谁有实践就更新文档吧，我们没用没办法写的很详细，容易误导别人。

**Comment by atian25** [comment]
@callmesoul 试了下，是 workers 个数的问题，leancloud 也是一样的限制。

```js
// index.js
require('egg').startCluster({
  baseDir: __dirname,
  workers: 1,
  port: process.env.PORT || 7001,
});
```

配置下你购买的服务端的 cpu 数即可

**Comment by atian25** [comment]
原来 SAE 里面用的是 heroku 啊

**Comment by atian25** [comment]
@okoala 这文档肯定不是 egg 的，最多就是以个人身份，写几篇博客，拿实例来讲解 egg 开发，然后可以包括在具体平台的部署流程。

举个例子：「Egg + LeanCloud 打造番号查询网站」

**Comment by atian25** [comment]
同步下，sina 官方已经支持 `workers:  process.env.SINACLOUD_CONTAINER_CPU || 1,`

**Comment by callmesoul** [comment]
已经不用sae了，发现sae，还没什么人访问，1天一元都不够，还不如直接买阿里云ecs呢。想用百度云的bae，比较便宜，但是发现bae的是node最高只有4.*的，大家有bae的配置部署方法的更新下。

**Comment by atian25** [comment]
我个人是用 leancloud 或 腾讯TAB

**Comment by callmesoul** [comment]
我在用aws，免费试用一年

**Comment by XenoJiang** [comment]
菜鸟问一下  egg v2 怎么改 workers 数量啊 ,  怎么在 SAE 部署

**Comment by FreemanJiangX** [comment]
SAE上 试了一下  启动参数 egg-scripts start --port=5050   --workers=1     (不要 --demon)  就可以了

**Comment by IOriens** [comment]
我是这么做的
1. 添加一个`EGG_WORKERS` 环境变量，值为机器的核心数，大小和 `SINACLOUD_CONTAINER_CPU` 保持一致
2. 修改 `package.json` 文件内 `scripts` 项中的 `start` 属性为
```sh
egg-scripts start --port=5050
``` 
3. 发布后可在容器日志中搜索 `workers` 来检查设置是否成功

![image](https://user-images.githubusercontent.com/8137136/66741143-600e2680-eea7-11e9-9b2b-16dbb39b2df7.png)
