### ISSUE TITLE
部署上线后怎么停了进程啊？

### ISSUE THREAD

**Issue by callmesoul** [eggjs/egg#823]
EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &
想问下部署后怎么停了，或者重启服务啊，怎么都停不了的？哭死

**Comment by popomore** [comment]
ps node 进程，kill 掉

**Comment by callmesoul** [comment]
@popomore 我把所有进程kiil掉了，可是还在跑啊。

**Comment by atian25** [comment]
kill master 进程即可，不要 kill -9 强杀

发自我的 iPhone
