### ISSUE TITLE
model 是否能引用 app.js 的资源

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#824]
As above.

**Comment by atian25** [comment]
什么资源，使用场景是？

**Comment by AkashiX** [comment]
定义全局属性，方便在 controller、service、model 这些层调用。

**Comment by atian25** [comment]
哪一个插件提供的 model 支持？`model/**.js` 的入口参数不就是 app 么？

egg-mongoose 的下一个版本会支持

**Comment by AkashiX** [comment]
用的 sequelize 。入口参数的确是 app ，但跟 controller 的 app 并不是同一个对象。

**Comment by atian25** [comment]
肯定是同一个

发自我的 iPhone

**Comment by AkashiX** [comment]
那么怎么引用？比如我在 app.js 定义了一个 errMsg 用于统一定义异常信息。
```js
// app.js
app.errMsg = { ... }
```
如果直接在 model 中用 app.errMsg 会得到 null or undefined 错误信息。debug 断点查看过
app 对象属性，是存在的。如果肯定同一个 app 对象，那么如何引用呢？

**Comment by atian25** [comment]
有可能是加载顺序问题，@popomore

你把属性定义放在 app/extend/application.js 试试

发自我的 iPhone

**Comment by popomore** [comment]
是啊，顺序问题，刚开始就这样说我们就明白了。
TZ | 天猪 <notifications@github.com>于2017年4月30日 周日20:55写道：

**Comment by AkashiX** [comment]
My fault...好了的话麻烦通知一下，我更新依赖。

**Comment by atian25** [comment]
你直接写到我说的地方即可

发自我的 iPhone

**Comment by AkashiX** [comment]
Solved.

**Comment by atian25** [comment]
其实放到 config 定义更好

发自我的 iPhone

**Comment by whlsxl** [comment]
@atian25 
好像是放到`application.js`也是不行的，https://github.com/eggjs/egg/issues/2681
正常`model`的加载直觉上应该放到`config` `extend`之后

**Comment by atian25** [comment]
@whlsxl 你的问题是啥？提供最小可复现仓库提新 issue

**Comment by whlsxl** [comment]
仓库：https://github.com/whlsxl/egg-mock/tree/04b664f5871ba4b1c5ec59f7ce85294cf8a47384
我的问题就是这个`issue`，

> 有可能是加载顺序问题，@popomore 你把属性定义放在 app/extend/application.js 试试 发自我的 iPhone
> […](#)
> 在 2017年4月30日，20:23，M.Y.Akashi ***@***.***> 写道： 那么怎么引用？比如我在 app.js 定义了一个 errMsg 用于统一定义异常信息。 // app.js app.errMsg = { ... } 如果直接在 model 中用 app.errMsg 会得到 null or undefined 错误信息。debug 断点查看过 app 对象属性，是存在的。如果肯定同一个 app 对象，那么如何引用呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

放到`app/extend/application.js`也是不行的，`model`的加载顺序会先于`application.js`，但是直觉上应该是`application.js`优先。

**Comment by whlsxl** [comment]
@atian25 觉得这是个问题么？

**Comment by atian25** [comment]
application.js 是优先于 model 的。

@whlsxl 我跑了下，是可以复现的。

分析了下，问题出在 https://github.com/eggjs/egg-sequelize/blob/master/agent.js

egg-sequelize 当前的实现里面，是 app 和 agent 都会挂载的，因此在 agent 加载的时候，挂了。

你需要在 `app/extend/agent.js` 里面也加一个同名的 doSomething 方法。

**Comment by whlsxl** [comment]
@atian25 辛苦啦！
刚才试了下，在`agent.js`加就可以了。
