### ISSUE TITLE
我使用ajax进行跨域请求，浏览器会发送一个options请求进行试探，试探的结果是404，请问这个如何解决？

### ISSUE THREAD

**Issue by lisniuse** [eggjs/egg#826]
* **Node Version**:7.9.0
* **Egg Version**:1.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:window10

我使用ajax进行跨域请求，浏览器会发送一个options请求进行试探，试探的结果是404，请问这个如何解决。

一开始提示的是 由于安全设置，不允许请求 options ，然后我关闭了安全模块，再尝试请求，直接就返回了404，控制器里面也没有捕获到 options 请求。

请问如何解决，急。

**Comment by popomore** [comment]
能给个重现的例子呢
陈治兵 <notifications@github.com>于2017年4月30日 周日21:39写道：

**Comment by lisniuse** [comment]
某个控制器：
```
'use strict';
module.exports = app => {
  class PostsController extends app.Controller {

    * index() {
      //this.ctx.body = 'hey, man';
      this.ctx.body = this.ctx.request.method;
    }
...
...
```
无论如何，这里的  this.ctx.request.method 都不输出 options 。是不是某一层禁止给控制器传输 options 请求，直接先返回404了？

**Comment by johnnychen** [comment]
可以参见：https://github.com/eggjs/egg-cors

如何开启cors支持

**Comment by jtyjty99999** [comment]
配置一下白名单就行了，请求被拦截了

**Comment by AkashiX** [comment]
这是CORS的问题，不是CSRF。

**Comment by popomore** [comment]
看来问题已经很清楚了，按照上面的配置一下。
