### ISSUE TITLE
custom logger formatter

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#827]
因为要接入xflush，xflush日志有自己的格式，所以需要配置 formatter，结构如下：

![image](https://cloud.githubusercontent.com/assets/1297278/25610336/761ff106-2f55-11e7-8446-63404d6b3d0b.png)

在config.default.js配置了`customLogger`及formatter，但formatter并未生效

![image](https://cloud.githubusercontent.com/assets/1297278/25610489/0155feb4-2f56-11e7-938b-7359276dceed.png)

**Comment by johnnychen** [comment]
翻了下源码，formatter被context_logger中的formatter覆盖掉了

**Comment by jtyjty99999** [comment]
可以自己格式化好了然后调用logger输出，比如

app.loggers.xflush.write(xflushFormat({
      time: Date.now()
}));

**Comment by popomore** [comment]
如果自己 format 了就没必要使用 ctx 了，使用也会被覆盖的。
