### ISSUE TITLE
egg-i18n双下划线函数在view模板下不能运行

### ISSUE THREAD

**Issue by Hiufan** [eggjs/egg#828]
egg-i18n这个插件的__()这个函数不能正常解析，但是它的别名gettext()可以。

![image](https://cloud.githubusercontent.com/assets/5506237/25618279/f15a28dc-2f78-11e7-8f74-c1fc7ddb7595.png)

* **Node Version**: 6.10.2
* **Egg Version**: 
* **Plugin Name**: egg-i18n
* **Plugin Version**: 1.1.0
* **Platform**: Mac OS

**Comment by popomore** [comment]
应该是可以的，能否给个例子

**Comment by popomore** [comment]
关闭了，如果还有问题请提供能重现的示例。

**Comment by robin1liu** [comment]
在service的单元测试中报错：
 Error: Unable to call `__`, which is undefined or falsey

**Comment by atian25** [comment]
提供可复现代码库
