### ISSUE TITLE
router一次性拦截多个请求的方法

### ISSUE THREAD

**Issue by leiyanggz** [eggjs/egg#829]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

比如我在router中有多个格式为'/auth/...' 的请求，如下
```
module.exports = app => {
    app.get('/auth/index', app.middlewares.logged(), 'adminCtrl.index');
    app.get('/auth/check', app.middlewares.logged(), 'adminCtrl.check');
    app.get('/auth/userInfo', app.middlewares.logged(),'adminCtrl.userInfo');
};
```

请问是否有统一的方法将这些请求一次性拦截，例如
```
app.get('/auth', app.middlewares.logged());
```

**Comment by atian25** [comment]
看下 middleware 文档的 match 属性，无需在 router 配

发自我的 iPhone

**Comment by atian25** [comment]
https://eggjs.org/zh-cn/basics/middleware.html#match-和-ignore
