### ISSUE TITLE
是否能在controller 的 mixin 中对 执行结果 进行 return？

### ISSUE THREAD

**Issue by cloudbeer** [eggjs/egg#831]
## 改进需求：
methodToMiddleware 和 functionToMiddleware 这两个方法 进行结果进行 return 。修改后的代码如下：

```
if (is.generator(r) || is.promise(r)) {
  return yield r;
 }else{
  return r;
 }
```

## 为什么要这么做？

我想在我的框架中对 controller 的方法进行统一 json 协议封装。所以会要求 controller 中的方法按照如下的方式实现：

```js
function (){
  return {a: "hello"};
}
```

这样我就可以在我的框架中使用如下的代码进行结果封装了。

```
//router 就是 app.controller 映射出来的方法。
app.get(path_match, ...middlewares, function*() {
  try {
    let res = yield router;
    if (res) {
      this.body = tools.wrapBody(res);
    }
  } catch (err) {
     this.body = tools.wrapBody(err);
  }
 });
```

这样修改也不会影响 egg 中原有的 `this.body={}`

**Comment by popomore** [comment]
见 https://github.com/eggjs/egg/issues/817 的讨论

自己封装可以覆盖 loadController 方法。

**Comment by atian25** [comment]
`this.body = {}`  和 `return {}` 差别不大吧？

**Comment by cloudbeer** [comment]
@atian25 
this.body = {} 之后，请求就结束了，没有办法搞了。
return {}  这个直接写在 controller 里是 404 呀。

@popomore 
我现在就是把 controller.js 这个文件完全拷贝一遍自己写的 WorkerLoader。

但感觉这个需求是合理的呀。

**Comment by atian25** [comment]
@cloudbeer 怎么会结束呢，加一个 Middleware 在后面处理就好了啊

```js
// app/middleware/api.js
module.exports = options => {
  return function* (next) {
    yield next;
    this.body = {
      status: 200,
      result: this.body,
    };
  };
};
```

**Comment by atian25** [comment]
更建议是提供自己的方法，如 `ctx.rpc({})`，参见： https://eggjs.org/zh-cn/basics/controller.html#自定义-controller-基类

**Comment by cloudbeer** [comment]
@atian25 
```
//app/controller/post.js
module.exports = app => {
  return class PostController extends app.Controller {
    * list() {
      return yield this.service.listByUser(this.user);
    }
   err(){
     throw error;
   }
  };
};
```

不封装方法，感觉这样写更爽。

那个加一个中间键的方法倒是之前没有想到。我一会儿试试。
