### ISSUE TITLE
egg-mysql能否链接mariadb数据库

### ISSUE THREAD

**Issue by Jv-Juven** [eggjs/egg#832]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

你好，请问下egg-mysql能否链接mariadb数据库？我使用egg-mysql的时候，连接的是我本地的mariadb数据库，可是查询出来的却是：{}，期间也没有报错。是不是egg-mysql不支持链接mariadb数据库的？

**Comment by popomore** [comment]
egg-sequelize 是支持的，你用 egg-mysql 的话不保证能支持，能跑的话就可以用。
