### ISSUE TITLE
＝＝

### ISSUE THREAD

**Issue by jtyjty99999** [eggjs/egg#834]
＝＝

**Comment by shaoshuai0102** [comment]
你右边的代码是哪里的  不是 egg 的吧

**Comment by jtyjty99999** [comment]
嗯，不是，举个例子

**Comment by shaoshuai0102** [comment]
这个也算是防住了吧，surl 是防止被 x，主要是过滤 protocol 以及防止写 `/a><scirpt>` 这样的代码。

**Comment by shaoshuai0102** [comment]
没看懂 你为啥说攻击成功了

**Comment by jtyjty99999** [comment]
那个资源加载并执行了

**Comment by jtyjty99999** [comment]
理论上surl应该不能让这种资源加载的，应该返回空

**Comment by haozi** [comment]
![image](https://cloud.githubusercontent.com/assets/4150641/25654422/7ce47830-3023-11e7-99c9-f369662ef2bb.png)

再提供一个示例，二次操作造成的 dom-based xss, 但这不能完全责怪 surl()，xss 需要在最终输出的地方防御。

url 的转译应该使用 encodeURI 和 encodeURIComponent，html 实体字符的转译会造成后端语义不符合预期。

比如
`/s?q=1<2` 后端希望得到的是 `1<2`，而不是 `1&gt;2`

**Comment by shaoshuai0102** [comment]
@jtyjty99999 你说的这个 `https://www.segmentfault.com@xss.haozi.me/j.js` 并没有风险呀，surl 是过滤 xss，不是过滤域名。

**Comment by jtyjty99999** [comment]
怎么没风险啊，这个js执行了。你看一下那个js的内容

如果你写一个返回401登录框的请求也会加载从而造成401攻击

没有强调过滤域名

**Comment by shaoshuai0102** [comment]
你是说 `https://www.segmentfault.com@xss.haozi.me/j.js` 里面的 alert 么？如果显示的引入 script，说明你信任他呀。

**Comment by jtyjty99999** [comment]
script是举例子啊，换成图片url也加载了，这个图片可能是店铺装修的时候填的商品图呢

**Comment by shaoshuai0102** [comment]
那你的意思是把这个 url 过滤掉？依据是什么呢

**Comment by jtyjty99999** [comment]
@shuaishao0102 我也在查防范方案，现在还没有一个结论，所以邀请你们来一起想想，哈哈

**Comment by JacksonTian** [comment]
如果真有漏洞 还是先不要公开讨论。。

**Comment by dotnil** [comment]
第一个例子里，漏洞的锅应该给 domainRe 来背，写成 `/^https?:\/\/www\.segmentfault\.com\/` 就可以了

**Comment by dotnil** [comment]
第二个例子有点奇怪，感觉不像是 egg-security 的处理范围，是前端在执行 `text.html()` 没有对用户输入作 escape

**Comment by jtyjty99999** [comment]
@dotnil 之前的例子还限制了domain，实际实现domain都是不限制的。

**Comment by dotnil** [comment]
所以第一个例子是想说明啥…… 我有些糊涂了

**Comment by shaoshuai0102** [comment]
- 对于主动 script 引入的脚本，本身就是可信的。不属于 surl 的防范范围。issue 中的例子并不是 xss， surl 是放 xss 的。
- 如果想防范，是把这个 url 使用 ctx.isSafeDomain 过滤一遍。

**Comment by shaoshuai0102** [comment]
@jtyjty99999 安全这边的东西比较敏感，后面如果有问题，内部先解决掉再披露哈。

**Comment by jtyjty99999** [comment]
暂时先关闭掉
