### ISSUE TITLE
为什么要强制prod下的logger等级不能为debug

### ISSUE THREAD

**Issue by AnzerWall** [eggjs/egg#835]
https://github.com/eggjs/egg/blob/5900c1ba64f9300f6ac6e45a2d7d2d161ed7f477/lib/core/logger.js#L9

是出于什么考虑？

**Comment by popomore** [comment]
这个我觉得可以去掉，主要是因为日志量大小和敏感数据。

**Comment by atian25** [comment]
当时出发点是防止开发人员做死

发自我的 iPhone

**Comment by fengmk2** [comment]
@popomore @atian25 这个可以做到企业内部，不是所有企业都不允许生产环境开启 DEBUG 日志的。

**Comment by popomore** [comment]
那发个 PR 删掉吧

**Comment by runhwguo** [comment]
我觉得如果在prod开启了，提示warn提示，不能强制吧 @atian25

**Comment by popomore** [comment]
看上面的 pr

**Comment by runhwguo** [comment]
@popomore 实测还是不行。

**Comment by runhwguo** [comment]
if (app.config.env === 'prod' && loggerConfig.level === 'DEBUG' && loggerConfig.allowDebugAtProd === true) {
    loggerConfig.level = 'INFO';
}
      这里不应该是loggerConfig.allowDebugAtProd === false么？ @atian25 @popomore

**Comment by runhwguo** [comment]
big乌龙
