### ISSUE TITLE
关于 ESLint 对使用 async 声明报错

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#843]
建议 .eslintrc 文件默认继承 babel-eslint 或者其他支持ES7语法的检测系统，因为 eslint-config-egg 似乎不支持 async/await 或者其他某些ES7的语法。

**Comment by AkashiX** [comment]
看了 eslint config egg 的源码，应该是支持到最新版本的 es。但是当我使用 async 声明方法时为何报 parsing error: expected token 这样的错误？

**Comment by popomore** [comment]
还没发 4.0

**Comment by popomore** [comment]
https://github.com/eggjs/examples/blob/master/hackernews-async/.eslintrc 3.0 要这样配

**Comment by AkashiX** [comment]
🤔大概什么时候发布啊。

**Comment by AkashiX** [comment]
okay.

**Comment by a304885433** [comment]
@popomore  配置过了sync，await关键字检测过不了。下面2种配置锚地对await都没有效果，能告知下怎么配置吗
```
{
  "extends": "eslint-config-egg",
  "parserOptions": {
    "ecmaVersion": 2017
  }
}
```
```
{
  "parserOptions": {
    "ecmaVersion": 2017
  }
}
```

**Comment by popomore** [comment]
已经更新了，4.0
冲动 <notifications@github.com>于2017年5月12日 周五09:43写道：
