### ISSUE TITLE
有什么方法固定npm run dev启动的端口号，不断变成7002，7003

### ISSUE THREAD

**Issue by humanchen** [eggjs/egg#846]
有什么方法固定npm run dev启动的端口号，不断变成7002，7003

* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

**Comment by humanchen** [comment]
还有怎么安全退出npm run dev

**Comment by 89790094** [comment]
package.json:
"scripts": {
    "dev": "egg-bin dev --port $PORT"
  },
