### ISSUE TITLE
egg-sequelize的事务Transaction怎么使用

### ISSUE THREAD

**Issue by TDiDa** [eggjs/egg#848]
请教下egg-sequelize的事务Transaction怎么使用，egg-sequelize例子里面没有相关事务这块的

试着这样写
```
const result = yield this.ctx.model.Sequelize.Transaction(function* (t) {
 
});
```

报错
`Cannot read property 'QueryGenerator' of undefined`

**Comment by AkashiX** [comment]
去sequelize官网，有对应的介绍


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：TDiDa <notifications@github.com>
时间：周五 5月5日 17:39
收件人：eggjs/egg <egg@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：[eggjs/egg] egg-sequelize的事务Transaction怎么使用 (#848)

**Comment by TDiDa** [comment]
@AkashiX 官网我有去看，只是使用egg-sequelize，报错

```
const result = yield this.ctx.model.Sequelize.Transaction(function* (t) {
});
```
报错
`Cannot read property 'QueryGenerator' of undefined`

问一下在egg内这样使用对吗

**Comment by superlbr** [comment]
@TDiDa this.ctx.model.Transaction
