### ISSUE TITLE
Config 支持 local prod 同时存在的情况吗

### ISSUE THREAD

**Issue by netputer** [eggjs/egg#851]
* **Node Version**: 6.10.0
* **Egg Version**: 1.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

项目的数据库处于内网，办公网无法直接访问，而办公网有一个端口转发服务。同样是生产环境，本地和服务器对应的数据库地址是不一样的，请问这个需求如何使用 Egg 的配置实现呢？ 

此前用 Express 时，我用了 `config` 这个库，支持按 `local.js` `local-production.js` `production.js` 这种顺序加载配置，可以很好地解决我这个需求。

**Comment by popomore** [comment]
所有的环境都会加载 config.default.js, local 和 prod 分别在不同环境覆盖 default，如果共享配置就放在 default 里面。

- local.js > config.local.js
- local-production.js > config.default.js
- production.js > config.prod.js

**Comment by okoala** [comment]
@netputer 建议多看看文档吧~ https://eggjs.org/zh-cn/basics/config.html

**Comment by netputer** [comment]
抱歉，是我没有把问题表达完全…

如 @popomore 所说，对于只有一种环境的，是可以很好支持。

但是如果有多个环境，比如 test 和 prod 俩环境，内网以及办公网的数据库地址分别是：

- prod.internal.com -> prod.office.com
- test.internal.com -> test.office.com

此时 `config.default.js` 应该怎么描述呢？

**Comment by popomore** [comment]
test 可以使用 config.test.js ，文档查看 https://eggjs.org/zh-cn/basics/env.html#自定义环境

**Comment by netputer** [comment]
是的，按照文档意思，内网环境配置不是问题，但是本地开发我还没想清楚…

- `config.test.js` 写的是 `test.internal.com`
- `config.prod.js` 写的是 `prod.internal.com`

但是只有一个 `config.local.js`，如何对应 `test.office.com` 和 `prod.office.com` 呢？

**Comment by popomore** [comment]
为何 local 需要链接多个数据库呢？一般是通过环境变量来区分 `EGG_SERVER_ENV=test npm run dev` 访问，但是一般本地是无法访问生成环境的，而且不只是数据库，大部分网络调用都是只有内网的，就算数据库代理了，其他也可能会连不上。

还有一种方式是自定义一个环境变量在 local 配置，比如 DATABASE=test.office.com，然后在 local 里读取这个环境变量，在 scripts 里定义两个 local 的命令。

**Comment by netputer** [comment]
严格来说，本地确实不应该访问生产环境，但就这个问题而言，是存在本地可以访问生产环境这种可能性的…

环境变量基本可以解决配置文件的任何问题，但我还是想采用「配置即代码」这个方案。

以 [config](https://www.npmjs.com/package/config) 那种做法，`local` 不与 `prod` `test` 互斥，因此可以很简单地实现这个需求。不知道 Egg 后续有无打算改进？

**Comment by popomore** [comment]
我还是没有理解你的需求，你上面说的就是要在 local 环境切换两个数据库源，一个环境最终肯定只能生成一份配置，所以只能借助环境变量。

**Comment by netputer** [comment]
我觉得是因为我们对 `local` 的定义不一致。你的（或者 Egg 的） `local` 其实是和 `unittest` `prod` 并列的一种环境，对应开发、测试、上线的过程。

而我对 `local` 定义可能更多是网络环境层面的（如果我能直连生产环境数据库也就不用改配置了 🙄️），假设所有环境的数据库都在内网，那有多少种环境就有多少种 `local-` 的环境。

**Comment by popomore** [comment]
你没理解我的意思，就算你的 local 有多个环境，你在本地连的话肯定需要环境变量控制的，你不可能什么都不改，敲同样的命令，就发生变化了吧。

只是这里在讨论的是如何切换，比如

- 在本地设置 alias，执行 dbtest 切换到环境变量
- 在 pkg.scripts 增加两个命令 `npm run dev:dbtest` 切换环境

我不太建议本地调试修改 EGG_SERVER_ENV，因为非 local 环境享受不到本地调试代理的便利。

**Comment by netputer** [comment]
了解，关于这个需求我打算这么做：

- 本地开发测试环境：EGG_SERVER_ENV=local NODE_ENV=testing npm run dev
- 内网部署测试环境：EGG_SERVER_ENV=prod NODE_ENV=testing npm start
- 本地开发生产环境：EGG_SERVER_ENV=local NODE_ENV=production npm run dev
- 内网部署生产环境：EGG_SERVER_ENV=prod NODE_ENV=production npm start

配合 `config` 再实现切换数据库地址。

**Comment by fengmk2** [comment]
@netputer 为何不直接使用一个环境变量呢？

- 本地开发测试环境：EGG_SERVER_ENV=local npm run dev
- 本地开发生产环境：EGG_SERVER_ENV=default npm run dev
- 内网部署测试环境：EGG_SERVER_ENV=test npm start
- 内网部署生产环境：EGG_SERVER_ENV=prod npm start

**Comment by netputer** [comment]
@fengmk2 这种是可以达到目的啦，但是感觉维护性一般吧… 假如又有了一个 staging 环境，就不好组合了。而前面提的方法，只要再加一个 `NODE_ENV=staging` 的配置就可以满足了，清晰易懂。

**Comment by fengmk2** [comment]
staging 的话就直接加

- EGG_SERVER_ENV=staging npm start => config.staging.js + config.defualt.js

**Comment by fengmk2** [comment]
关键的是忘记掉 NODE_ENV

**Comment by netputer** [comment]
嗯，如果只是环境区分，用 Egg 现有的方法确实可以支持，环境相关写到 `config-${EGG_SERVER_ENV}.js` 里，而通用的写到 `config-default.js` 里。

但以刚才 staging 为例，本地 + staging 应该怎么写呢？以我的理解，local 是和 test staging prod 并列的环境，这种复合情况，不太好写配置的样子…

**Comment by popomore** [comment]
主要是切了环境，本地开发就不一样了，比如 development 插件不会开启。

**Comment by atian25** [comment]
我们目前只会合并两个  `config.default.js + config.{env}.js`

如果你有 2 个 env 想共享，但又不能全局，放不到 default，那就自己写一个 xx.js，然后那 2 个 `config.{env}.js` 里面自己 require 咯

**Comment by netputer** [comment]
我觉得 local 应该独立于 test prod 之类的环境，满足利用 development 插件调试 prod 这种需求，只在 `npm run dev` 时加载 local 配置，`npm start` 跳过 local 配置…

以 [node-config](https://github.com/lorenwest/node-config/wiki/Configuration-Files) 处理 staging
环境为例，他会按优先级从高到低依次加载以下配置：

0. local-staging：写本地访问 staging 数据库的地址
0. local：写其它本地配置
0. staging：写服务器访问 staging 数据库的地址
0. default：写其它服务器配置

**Comment by dead-horse** [comment]
@netputer 不要这样理解 local，local 和 staging 一样是一个环境，只是我们默认认为它是本地开发环境，所以有些插件在本地开发环境有一些特殊的处理。不存在同时开启两个环境这种用法的。否则就变的更加复杂化了。

**Comment by imshenyz** [comment]
刚好配置继承上也遇到了类似的问题，推送到Git库中的配置是这样的：
```
// config.default.js
config.sequelize = {
  database: 'demo', // 正式环境使用 demo 数据库
  host: 'localhost',
  port: '3306',
  username: 'root',
  password: 'root',
};
```

```
// config.unittest.js
config.sequelize = {
  database: 'demo_test', // 执行单元测试使用 demo_test 数据库
  host: 'localhost',
  port: '3306',
  username: 'root',
  password: 'root',
};
```
团队成员A拉下项目后可以新建一个本地配置文件：

```
// config.local.js
config.sequelize = {
  database: 'demo',
  host: 'localhost',
  port: '3306',
  username: 'root',
  password: 'rootA', // 连接本地数据库，有自己的密码A
};
```

团队成员B拉下项目后同样可以新建一个本地配置文件：

```
// config.local.js
config.sequelize = {
  database: 'demo',
  host: 'localhost',
  port: '3306',
  username: 'root',
  password: 'rootB', // 连接本地数据库，有自己的密码B
};
```

目前配置对于团队成员来说，执行 `npm run dev` 是没问题的，可以使用各自的数据库密码连接数据库。

但是对于执行 `npm test` 单元测试时，由于把 local 和 unittest 一样都当做是一种环境来的，所以只会加载 unittest 和 default 配置文件，此时如何让成员各自配置数据库连接。

如果把 local 作为本地配置而不是一种环境，拥有最高优先级，即 `local > {env} > default` 是不是可以更灵活一些。

**Comment by atian25** [comment]
既然是本地测试用数据库，是不是可以不设置密码，或者一样的密码呢？

**Comment by imshenyz** [comment]
@atian25 感谢答复，都设置一样的密码的确也是一种解决方法。其实主要的需求还是和这个issue一样，想要针对类似 unittest 环境本地还可以根据各自环境单独配置，目前暂时在 `config.unittest.js` 中自己 `require` 来实现的。
