### ISSUE TITLE
egg-view-react

### ISSUE THREAD

**Issue by zenjava** [eggjs/egg#852]
* **Node Version**:
v6.9.1
* **Egg Version**:
1.1.0
* **Plugin Name**:
egg-view-react
* **Plugin Version**:
github master
* **Platform**:
osx 

配置文件如下：
config/plugins.js
```
exports.view = {
  enable: true,
  package: 'egg-view-react',
};
```
config/config.default.js
```

config.view = {
  };
```

controller代码
```
module.exports = app => {
  class HomeController extends app.Controller {

    * index() {
      const dataList = {
        list: [
          { id: 1, title: 'this is news 1', url: '/news/1' },
          { id: 2, title: 'this is news 2', url: '/news/2' },
        ],
      };
      yield this.ctx.render('hello.js', dataList);
    }
  }
  return HomeController;
};
```
出现错误：
TypeError: this.ctx.render is not a function

**Comment by popomore** [comment]
你这样问无法理解

**Comment by popomore** [comment]
https://zhuanlan.zhihu.com/p/25795393

**Comment by zenjava** [comment]
我改了下，这样能理解了吗

**Comment by ngot** [comment]
https://github.com/eggjs/egg/issues/543

https://github.com/eggjs/egg/issues/328

**Comment by popomore** [comment]
好像还没完成

**Comment by zenjava** [comment]
我发现egg-view-react-dom这个组件可以用，有人搞了一个。
