### ISSUE TITLE
[eslint] Parsing error: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#855]
使用 import Eslint 提示改错误信息，想请问下是否可以使用 import 导入 json 文件中的某些 json 对象？

**Comment by popomore** [comment]
Node 不支持，你可以使用 ts 或 babel 编译，eslint 怎么配去 eslint 官网查下吧

**Comment by IEfucker** [comment]
https://www.npmjs.com/package/babel-eslint
