### ISSUE TITLE
egg-mock 支持 cluster 模式 mock function 的方案

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#858]
## 背景

在写单元测试的时候，通过 `mm.app()` 创建拿到的 app 是可以非常方便地进行 mock，如 [`app.mockSession(data)`](https://github.com/eggjs/egg-mock/blob/master/app/extend/application.js#L55)，就可以模拟请求带上特定的 session 数据。

```js
const app = mm.app();

app.mockSession({ user: { name: 'mockuser' } });
return app.httpRequest()
  .get('/user')
  .expect(200)
  .expect({ name: 'mockuser' });
```

但是通过 `mm.cluster()` 创建的 app 缺没法使用相同的方式 mock 数据。因为它是多进程模型，没法简单地修改当前进程的内存数据。

```js
const app = mm.cluster();

app.mockSession({ user: { name: 'mockuser' } });
return app.httpRequest()
  .get('/user')
  .expect(200)
  .expect({ name: 'mockuser' });
```

## 可行的方案

是否可以让测试进程给 cluster app 发送一个特殊请求，让处理请求的 worker 进程自动执行 `mock function` 呢？

结合 [JavaScript Proxy](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) 和 [child_process.execFileSync](https://npm.taobao.org/mirrors/node/latest/docs/api/child_process.html#child_process_child_process_execfilesync_file_args_options) 两个功能的帮助，完全可以实现上面的设想。

## 最终效果

这样不管是单进程 app 还是 cluster 多进程 app 模式，在单元测试代码里面的各种 mock function 对于编写单元测试的开发者来说都是一模一样的  API，完全对于他们透明。甚至 `mm.restore()` 都能实现。

```js
const mm = require('egg-mock');
const app = mm.cluster();
afterEach(mm.restore);

// ...

app.mockSession({ user: { name: 'mockuser' } });
return app.httpRequest()
  .get('/user')
  .expect(200)
  .expect({ name: 'mockuser' });
```

**Comment by fengmk2** [comment]
cc @popomore

**Comment by bugss** [comment]
有了mock对cluster单元测试肯定方便多了.
要是能够支持这样那就更好了.
```javascript
app.mockContext({
    *weiboUser(){
// 这里不能用变量应该也没有关系
      return {
        username: 'test'
      }
    }
  })
```
JSON.stringify 把function吃了.  

直接用下面的方法也不行,回来了就变成字符串了.
```javascript
var json = JSON.stringify(obj, function(key, value) {
  if (typeof value === 'function') {
    return value.toString();
  } else {
    return value;
  }
});
```

**Comment by fengmk2** [comment]
@bugss 支持 mock 参数里面带 function 的，可以参考 https://github.com/eggjs/egg-mock/pull/44/files#diff-2eb0ba94fa2bb885260aea20f7ff91a5R60

**Comment by bugss** [comment]
嗯.那个带function我试过,mock时候给的是function,但是调用还原成参数的时候还是个function,并不是我预期的返回值.
我本地安装了你的那个分支,然后在上面的代码上做了点粗暴的修改,可以满足我目前的需求.
```javascript
const child = childProcess.spawnSync(process.execPath, [
      requestCallFunctionFile,
// function直接变字符串
      JSONfn.stringify(data),
    ], {
      stdio: 'pipe',
    });
```

然后app.js里面
```javascript
else{
// 因为koa转给一次json了,这里转一次在转回来.... 直接识别function字符认作Function.. 写法不太es6能识别
        args[i]=JSONfn.parse(JSONfn.stringify(arg))
      }
```
