### ISSUE TITLE
MehtodNotAllowError

### ISSUE THREAD

**Issue by jamesliauw** [eggjs/egg#862]
* **Node Version**:6.9
* **Egg Version**:1.2
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:win

'
在config.default.js设置了public静态目录之后
config.static = {
      prefix: '/',
      maxAge: 31536000,
      dir: path.join(appInfo.baseDir, 'app/public/')
    }

静态目录设置成功了，但发现EGG对外服务的接口只支持get了，不支持POST，
用POST请求的话，返回MethodNotAllow,
问题：
这种现像是否可以通过配置来解决？

搜了一下ISSUE，貌似没有人遇到过，唯一个有可能有相关的是这个
https://github.com/eggjs/egg/issues/683,但好像无关。

**Comment by atian25** [comment]
see egg-security

发自我的 iPhone

**Comment by dead-horse** [comment]
静态文件不支持通过 POST 访问
