### ISSUE TITLE
logger 和 meta 中获得的信息太少

### ISSUE THREAD

**Issue by hbrls** [eggjs/egg#863]
* **Node Version**:
6.9
* **Egg Version**:
1.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:

```
class MyTransport extends Transport {
    log(level, args, meta) {
        // 这里的 args 和 meta 的信息太少
    }
}
```

我想得到比如
1. 当前写这个日志的文件 view.js
2. 行数
3. 等等比如 stack

**Comment by popomore** [comment]
@dead-horse logger.debug 你是不是优化过？

**Comment by popomore** [comment]
@hbrls 这个不能都获取，会影响性能。

**Comment by dead-horse** [comment]
应该没有在 egg-logger 上改过，最好不要加，容易引发性能问题

**Comment by popomore** [comment]
debug 应该没事吧？

**Comment by dead-horse** [comment]
没什么意义吧，debug 加了其他不加又容易引发不一致，debug 的使用率也偏低。

**Comment by hbrls** [comment]
我要 info 以上，不要 debug，目前在尝试迁一些 java 项目，以前是有的，现在没有了就缺乏说服力

**Comment by dead-horse** [comment]
@hbrls 如果是在 controller 和 service 中，可以用类形式，通过 `this.logger.info()` 记录的日志都会带上打印日志的文件标识。

see：https://github.com/eggjs/egg/blob/master/lib/core/base_context_logger.js

**Comment by hbrls** [comment]
一年过去了，我灵机一动想出了一个办法，请大家帮我一起看看。

用 gulp 把文件和行号补上去，细节就不贴了，主要看思路：

```javascript
gulp
    .src(['app/**/*'])
    .pipe(lineno(PATTERN))
    .pipe(replace(PATTERN, function (match, p1, p2, p3, p4, p5) {
        const ln = p5.match(LINENO)[1];
          return `${p1}${p2}('${p3}'${p4 || ''}, '[${ln}]');`;
    }))
    .pipe(gulp.dest('app/'));
```
Diff：

```javascript
ctx.logger.info('你好, 蛋!');
->
ctx.logger.info('你好, 蛋!', '[c.home:7]');
```
