### ISSUE TITLE
egg-socket.io信道主动抛异常的情况下应该处理一下

### ISSUE THREAD

**Issue by bugss** [eggjs/egg#865]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
egg-socket.io
* **Plugin Version**:
  "version": "1.2.1"
* **Platform**:

egg-socket.io/lib/io.js  71行这里的信号
```javascript
            co.wrap(handlr).call(ctx)
              .then(() => ctx[CtxEventSymbol].emit('finshed'))
              .catch(e => {
                e.message = '[egg-socket.io] controller execute error: ' + e.message;
                logger.error(e);
              });
```
如果app.io.route注册的信道里面的代码发生了异常,应该也要发信号给packetMiddlewareInit.js中间件处理吧?
现在不处理所有的中间件只走了yield *next 之前的那一半,后面那一半应该是挂在那里一直占内存的.

但是具体异常发生了不知道怎么处理好. 
1. 直接发完成信号让中间件走yield *next  后面的代码,但是用个标记标出来发生异常了.
1. 直接给个抛异常的信号给packetMiddlewareInit这里,yield *next后面的代码直接不走了.
1. 其他的方法?

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/blob/master/lib/io.js#L73 这里加一行，把错误emit出来，
然后这里接收一下，抛出去 https://github.com/eggjs/egg-socket.io/blob/master/lib/packetMiddlewareInit.js#L32 

@bugss 来个PR吧

**Comment by bugss** [comment]
https://github.com/eggjs/egg-socket.io/pull/14
感觉有点熟悉git了...

**Comment by ngot** [comment]
https://github.com/eggjs/egg-socket.io/pull/14 fixed egg-socket.io@1.2.2
