### ISSUE TITLE
egg-security/lib/middlewares/methdnoallow.js里把options排除了

### ISSUE THREAD

**Issue by dangyanglim** [eggjs/egg#866]
* **Node Version**:
v7.9.0
* **Egg Version**:
^1.1.0
* **Plugin Name**:
egg-security
* **Plugin Version**:
1.9.0
* **Platform**:
centos6.8

但是cors跨域不是一定要用到opions吗？

![image](https://cloud.githubusercontent.com/assets/16640185/25803459/902aaa04-3429-11e7-9ca1-24a3ab3cd5a4.png)

**Comment by dangyanglim** [comment]
我注释掉了原来的代码，

**Comment by ngot** [comment]
https://eggjs.org/zh-cn/core/security.html#防范方式-4

**Comment by ngot** [comment]
https://github.com/eggjs/egg-security/tree/master/test/fixtures/apps/csrf 参考这个例子写吧

**Comment by dangyanglim** [comment]
@ngot 好的，谢谢
