### ISSUE TITLE
导航栏怎么实现判断router则为active按钮？

### ISSUE THREAD

**Issue by wscart** [eggjs/egg#877]
导航栏怎么实现判断router则为active按钮？

                  <li class="parent"><a href="#"><i class="icon mdi mdi-settings"></i><span>站点配置</span></a>
                    <ul class="sub-menu">
                      <li><a href="/setbasic">基本配置</a>
                      </li>
                      <li><a href="/setmail">邮箱配置</a>
                      </li>
                      <li><a href="/setattachment">附件配置</a>
                      </li>
                    </ul>
                  </li>
                  <li class="parent"><a href="#"><i class="icon mdi mdi-tab"></i><span>栏目管理</span></a>
                    <ul class="sub-menu">
                      <li><a href="/columnclassify">栏目管理</a>
                      </li>
                      <li><a href="/columnclassify/add">添加分类</a>
                      </li>
                    </ul>
                  </li>

**Comment by ngot** [comment]
前端问题和egg无关
