### ISSUE TITLE
单元测试mm.cluster 调试

### ISSUE THREAD

**Issue by bugss** [eggjs/egg#878]
* **Node Version**:
v7.6.0 -> v7.10.0
* **Egg Version**:
egg@1.2.1
* **Plugin Name**:
* **Plugin Version**:
egg-bin@3.3.2
egg-cluster@1.6.2
* **Platform**:
macos 
* **Mini Showcase Repository**:

package.json
```javascript
scripts:{
"test-local": "egg-bin test --timeout=10000",
}
```

### 命令行执行
npm run test-local -- --inspect
或者
npm run test-local -- --inspect=9999

控制台报错
Starting inspector on 127.0.0.1:9229 failed: address already in use
或者
Starting inspector on 127.0.0.1:9999 failed: address already in use

最小化代码
下面的代码测试会过,但是提示
Starting inspector on 127.0.0.1:9229 failed: address already in use
真实的例子里面就会失败,并且没有办法进调试

```javascript
const mm = require('egg-mock')
describe('测试ws', () => {
  before(function* () {
    let options = {
      workers: 1,
      coverage: false,
      sticky: false,
    }
    const app = mm.cluster(options)
    yield app.ready()
  })
  it.only('测试', (done) => {
    done()
  })
})
```
 
在webstorm 里面通过npm run 启动, 报同样的错误

npm run test-local $NODE_DEBUG_OPTION

不知道还有谁遇到过没有.

**Comment by popomore** [comment]
不支持多进程吧， @atian25 你有试过吗

**Comment by atian25** [comment]
cluster 的话，要修改测试代码里面的

```js
let options = {
  opt: { execArgv: ['--debug=xxxx']}
}
```

来指定端口，而且还要对这个 `it.only` 单独调试。

**Comment by bugss** [comment]
能不能再这里开个配置,可以从外部传进入execArgv. 
egg-cluster/lib/master.js 166行
cfork({
      exec: appWorkerFile,
      args,
// 调试的时候需要加上这行,加了就能用webstorm的远程调试调试cluster了
      execArgv:["--debug-brk"],
      silent: false,
      count: this.options.workers,
      // don't refork in local env
      refork: this.isProduction,
    });

### 为什么一定要改那里
mm.cluster下面 webstorm不能自动attach master进程 app进程 agent进程. 貌似只attach了mocha的那个进程,就那个进程跑的代码能够设置断点.

> 貌似 project/index.js 那个文件webstorm是可以自动attach的,mm.cluster里面内部又起了个进程,可能就不认识了

###  遇到的问题
使用chrome 自带的工具,或者按个插件自动attach, 但是单元测试跑太快,基本attach不上
开始想这样
let options = {
  opt: { execArgv: ['--debug-brk=xxxx']}
}
这样理论是可以,但是mm.cluster启动的时候开了很多进程,得一个一个的attach,然后放行.太麻烦,感觉没有意义了

### 想到的一个解决办法

```javascript
 let options = {
    // baseDir: '../../',
    workers: 1,
    opt: {execArgv: ['--debug=9228']},
    // port,
    coverage: false,
    sticky: false,
  }
  
  const app = mm.cluster(options)
```
然后在egg-cluster的master.js里面
```javascript
 cfork({
      exec: appWorkerFile,
      args,
      execArgv:["--debug-brk"],
      silent: false,
      count: this.options.workers,
      // don't refork in local env
      refork: this.isProduction,
    });
```
然后起个webstorm的远程调试,9229 是app进程.
chrome-devtool调试也可以,attch 9229 端口就可以了.

一般我们用框架的人调试的多的也是app进程.   
我用webstorm,看起来挺麻烦,其实配置好了很方便. 
现在我是直接改了代码, 折腾了半天,终于能直接用webstorm调试cluster了,哈哈.

**Comment by bugss** [comment]
package.json里面
"debug": "npm run test-local --timeout=1000000",
timeout一定要弄长一些.
先用命令行执行 npm run debug .然后手工执行webstorm的远程调试,端口填9229.

**Comment by bugss** [comment]
https://github.com/eggjs/egg-cluster/pull/23

**Comment by atian25** [comment]
不应该在 cluster 做的，应该在 egg-mock 做更好，这个我之前曾经写过一半，后面觉得场景不是很多就没做下去了。

**Comment by bugss** [comment]
@atian25   egg-mock 做除非mm.cluster不起进程了.  不然webstorm完全不认后起的app agent 进程....

**Comment by atian25** [comment]
我印象中，之前测试过 WebStorm 只要 debug 端口 +1， 都能自动 attach 上的，记不太清了。

**Comment by bugss** [comment]
@atian25   确实可以...  要看准时机,太快了就过去了.  不过我现在用快捷键操作了,基本都能attach上,跟你们添麻烦了..
