### ISSUE TITLE
[RFC] sub router

### ISSUE THREAD

**Issue by atian25** [eggjs/egg#882]
## Background

currently `egg` don't support sub router, but `koa-router` provide `prefix()` feature.

## Proposal

- provide `app.namespace([prefix], [middlewares]).verb()`
- `app.url()` will traverse all the router, return the first one

example:

```js
// app/router.js
module.exports = app => {
  app.get('/', 'home.index');

  const adminRouter = app.namespace('/admin');
  // GET /admin
  adminRouter.get('/', 'admin.index');
  // GET /admin/user
  adminRouter.get('/user', 'admin.user');
}
```

**Comment by popomore** [comment]
prefix change to routerPrefix?

**Comment by atian25** [comment]
or just `getRouter` ？

发自我的 iPhone

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-core/blob/master/lib/utils/router.js#L191 没考虑 `router.url(name)` 怎么还原的问题？

**Comment by atian25** [comment]
@fengmk2  traverse all the router, return the first one?

**Comment by atian25** [comment]
@popomore @fengmk2 RFC and PR is updated, check again

**Comment by fengmk2** [comment]
邀请最有经验的 @huacnlee 来看看

**Comment by dead-horse** [comment]
1. 不想在 egg-core 里面提供这个功能，希望是一个扩展的 router 插件，这样也便于大家选择自己喜欢的 router 使用方式，egg-core 只提供基础的 `app.verb()`。
2. 需要考虑中间件的支持

```js
const router = app.getRouter('/sub', middleware);
router.get('/test1', 'test1');
router.get('/test2', 'test2');

// or

app.namespace('/sub', middleware, router => {
  router.get('/test1', 'test1');
  router.get('/test2', 'test2');
});
```

**Comment by popomore** [comment]
我考虑之后单独做个 router 插件，实现一个 rails 实用的特性。

**Comment by jtyjty99999** [comment]
我建议加一个advace-router这一类的插件来实现这个需求

**Comment by brucewar** [comment]
作为插件在Application上扩展呢？

**Comment by atian25** [comment]
- standalone plugin
- api name: `app.namespace()`
- support middleware

**Comment by acodercat** [comment]
如果更新了，麻烦通知下，很期待这个小功能

**Comment by atian25** [comment]
https://github.com/atian25/egg-router-plus/pull/1

写了个插件，下周再完善下

**Comment by atian25** [comment]
land at https://github.com/atian25/egg-router-plus

**Comment by shiyun** [comment]
@atian25 你好，我用用TS写router时，提示app.router上不存在namespace这个属性。

**Comment by atian25** [comment]
自己写 d.ts merge 进去。
