### ISSUE TITLE
npm i --save egg-sequelize安装不了（win10和ubuntu）

### ISSUE THREAD

**Issue by stonegithubs** [eggjs/egg#886]
* **Node Version**:
v7.10.0
* **Egg Version**:
v1.2.1
* **Plugin Name**:
egg-sequelize
* **Plugin Version**:
2.1.0
* **Platform**:
win10 and  ubuntu bash
* **win10 安装出现以下错误**:
npm i --save egg-sequelize OR npm i --save egg-sequelize  --unsafe-perm=true

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'D:\egg\egg-example\node_modules\_@types_geojson@1.0.2@@types\package.json'
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\Nodejs\\nvm\\nodejs\\node.exe" "D:\\Nodejs\\nvm\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "egg-sequelize" "--unsafe-perm=true"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path D:\\egg\egg-example\node_modules\egg-sequelize
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'D:\egg\egg-example\node_modules\egg-sequelize'
npm ERR! enoent ENOENT: no such file or directory, access 'D:\egg\egg-example\node_modules\egg-sequelize'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

* **win10 Ubuntu Bash**:
npm ERR! Linux 3.4.0+
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.10.0/bin/npm" "i" "--save" "egg-sequelize"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! path /mnt/d/egg/egg-example/node_modules/egg-sequelize/bin/egg-sequelize
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/mnt/d/egg/egg-example/node_modules/egg-sequelize/bin/egg-sequelize'
npm ERR! enoent ENOENT: no such file or directory, chmod '/mnt/d/egg/egg-example/node_modules/egg-sequelize/bin/egg-sequelize'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
请教以上错误有什么解决办法，谢谢！
都在win10下安装的（1：管理员身份打开CMD，2：ubuntu子系统），其他插件安装没问题，就egg-sequelize安装一直出错

**Comment by okoala** [comment]
@atian25   怎么 egg-sequelize 的版本号与 package.json 里的不一致？
https://github.com/eggjs/egg-sequelize/blob/master/package.json#L3

**Comment by atian25** [comment]
@popomore changelog 和 release 没执行，https://github.com/eggjs/egg-sequelize/pull/12

**Comment by atian25** [comment]
但跟这个问题应该没关系吧，像 `win10 Ubuntu Bash` 的问题?  @okoala 你 win 上能复现么?

**Comment by vance-liu** [comment]
mac + 1

**Comment by atian25** [comment]
我这边也复现了，@huacnlee 看看

**Comment by huacnlee** [comment]
@atian25 昨天的修正还没发布 npm 呀

**Comment by huacnlee** [comment]
egg-sequelize@2.1.2 版本可以用了

**Comment by stonegithubs** [comment]
egg-sequelize最新版没问题了，谢谢
