### ISSUE TITLE
fs performance improve

### ISSUE THREAD

**Issue by shaoshuai0102** [eggjs/egg#891]
写了一个脚本 https://github.com/shaoshuai0102/fs-perf

测试方法：写入 10w 条字符串，测试不同的写入方式耗时

1. fs writeStream 直接调用 write 10w 次，耗时 8758ms
2. 直接写入 10w 条 join 到一起的一个大字符串，调用 write 一次，耗时 131 ms
3. 每隔 1s cork 一次写入方式，9985ms
4. write 返回 false 的时候 push 到自己维护的数组，drain 事件后一次行 join 成一个字符串写入，935 ms.
5. 覆盖 fs.WriteStream 的 _writev 方法，修改为把内建的 chunks join 为一个大 buffer，一次写入，1462ms

对比，可以发现，其实真正能够提升性能的是：一次性多写数据，而不是分多次调用。所以我们的 logger 的 FileBuffer Transport 之所以有性能提升，其实是避免了内建的 writev 的低性能实现。

为何 writev 性能低，@洗影 帮忙分析下？

**Comment by shaoshuai0102** [comment]
@popomore @fengmk2

**Comment by popomore** [comment]
记得之前有讨论过，当时听的不是很明白。

**Comment by shaoshuai0102** [comment]
特别是 https://github.com/shaoshuai0102/fs-perf/blob/master/fs_with_writev.js#L10 覆盖了内建的 _writev 性能一下就 6 了

**Comment by fengmk2** [comment]
> 直接写入 10w 条 join 到一起的一个大字符串，调用 write 一次，耗时 131 ms

**Comment by JacksonTian** [comment]
覆盖writev其实没有用吧。没有调用 cork/uncork 的话 是不会触发 writev 的。

**Comment by shaoshuai0102** [comment]
只要数据产生速度（调用 fs write) 大于消费（写入磁盘）的话就会往 internal buf 里放，应该是走了 writev

**Comment by ngot** [comment]
感觉是要造个redis了

**Comment by joyeecheung** [comment]
没有@到我……@joyeecheung

**Comment by shaoshuai0102** [comment]
不知道你 github id。。sorry    btw 头像好萌

**Comment by huacnlee** [comment]
几乎所有的 IO 都是这样的结果啊！

一定是减少读写次数效率是最高的 - Buffer

累计一定量的时候写一次，或者每次 Request 周期结束的时候写

**Comment by joyeecheung** [comment]
@shaoshuai0102 这个benchmark只有写，没有读？

**Comment by shaoshuai0102** [comment]
嗯 只有写，因为是想看看日志写入有没有优化的空间。

**Comment by fengmk2** [comment]
@joyeecheung logger 场景，100% write。

**Comment by joyeecheung** [comment]
@shaoshuai0102 这个大部分时间花在 I/O 上了，你可以用 strace 或者 dtruss 比较一下几种方式的 write 调用次数，大字符串那个是最少的。

**Comment by shaoshuai0102** [comment]
好 我研究一下  回来贴结果

**Comment by dead-horse** [comment]
@shaoshuai0102 ...

**Comment by shaoshuai0102** [comment]
关了吧 弃坑
