### ISSUE TITLE
获取不到this.ctx.cookies.get('username')值

### ISSUE THREAD

**Issue by dangyanglim** [eggjs/egg#893]
* **Node Version**:v7.9
* **Egg Version**:1.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

我关掉了crsf

在一个post Controller里面有
      console.log("set");
      this.ctx.cookies.set('username', 1,{ maxAge: 900000 });
      var username= this.ctx.cookies.get('username');
      console.log(username);
但是打印的undefined
用浏览器看这个的response headers是有setcookies username=1的。

在执行上一个Controller后，再执行另一个get controler的里面代码
      var username= this.ctx.cookies.get('username');
      console.log(username);
还是undefined

用前端工程里面的mock是有获取到cookie，但是这个为什么获取不到

我这个有可能是跨域了，是因为跨域了吗？
即使是跨域，第一种情况那个是也不能获取吗？

另外我用curl这个发送cookie也打印undefined？
curl  "http://127.0.0.1:7001/api/v1/user" -b "username=1"

![qq 20170509175425](https://cloud.githubusercontent.com/assets/16640185/25939177/8cb83d90-3664-11e7-840c-e5bb64d88571.png)

**Comment by dead-horse** [comment]
```js
this.ctx.cookies.set('username', 1,{ maxAge: 900000 });
var username= this.ctx.cookies.get('username');
```

第一句是通过响应给前端设置，第二句代表从请求中获取 cookie 的值，所以设置完要到下一个请求才能获取到。

> 另外我用curl这个发送cookie也打印undefined？
> curl "http://127.0.0.1:7001/api/v1/user" -b "username=1"

你的请求中根本就没有带 cookie 。

先了解一下 cookie 到底是什么：https://en.wikipedia.org/wiki/HTTP_cookie ，再看看 egg 的文档：https://eggjs.org/zh-cn/core/cookie-and-session.html

**Comment by dangyanglim** [comment]
@dead-horse 

谢谢，egg那个文档有在看，可以给个带cookie的curl吗？

**Comment by dangyanglim** [comment]
保存使用cookie
curl -b cookiec.txt "http://127.0.0.1:7001/api/v1/user"
curl -c cookiec.txt "http://127.0.0.1:7001/api/v1/user"
用这种方法能打印到cookie，那服务端没写错，不知道为什么浏览器没带cookie发下来了

**Comment by popomore** [comment]
如果是前端设置的 cookie 要设置 sign: false，默认是加签的，可以先通读文档再问。

```js
ctx.cookies.set(key, value, {
  httpOnly: false,
  sign: false,
});
```

**Comment by athlan20** [comment]
可否通过配置设置不用每次都要显示写一下{signed:false}。。

**Comment by atian25** [comment]
你可以自定义一个 extend

```js
// app/extend/context.js
module.exports = {
  setCookies(key, value, options = { signed: false } ) {
    return this.cookies.set(key, value, options);
  }
};
```
