### ISSUE TITLE
egg-sequelize cannot use config.test.js for migrations

### ISSUE THREAD

**Issue by ladrift** [eggjs/egg#895]
* **Node Version**: 7.10.0
* **Egg Version**: 1.2.1
* **Plugin Name**: egg-sequelize
* **Plugin Version**: 2.1.3
* **Platform**: macOS, Linux
* **Mini Showcase Repository**: None

I cannot configurate the environment variable to migrate using `config.test.js`.
I inspected in its source code around [here](https://github.com/eggjs/egg-sequelize/blob/master/lib/database.js#L20).
```javascript
module.exports = {
  development: Object.assign(defaultConfig, localConfig),
  test: Object.assign(defaultConfig, unittestConfig),
  production: Object.assign(defaultConfig, prodConfig),
};
```
It uses `NODE_ENV=test` for `config.unittest.js`.

I want the feature that we can use the value of `EGG_SERVER_ENV` to specify the migration environment.

I have not figure out how to add this feature, so I issue this for your help. Thanks.

**Comment by zhangjx** [comment]
这个代码本身就有 bug, 导出的三套环境的配置，其实都被最后一个环境覆盖了，所以加环境变量都是不生效的

**Comment by popomore** [comment]
2.1.4 is out
