### ISSUE TITLE
egg-passport信息存档的位置？

### ISSUE THREAD

**Issue by zenjava** [eggjs/egg#897]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

请问该插件中，ctx.user的信息是存放在哪里？是sesion么？因为，要考虑集群的处理问题

**Comment by popomore** [comment]
这个自己处理的，有个 verify 接口，插件文档有

**Comment by zenjava** [comment]
我的疑问是，我登录完成后。把egg重启后，只要不删除session。就不用再登录。是egg本身session有持久化到某个地方吗？还是user的信息持久化到某个地方了

**Comment by popomore** [comment]
默认是 cookie session，把 cookie 清了就没了
zenjava <notifications@github.com>于2017年5月12日 周五10:40写道：
