### ISSUE TITLE
egg-view-nunjucks  如何设置 nunjucks  autoescape: false

### ISSUE THREAD

**Issue by a526672351** [eggjs/egg#899]
var env = nunjucks.configure('/path/to/templates', { autoescape: false });
默认是 true，我在egg上面如何设置为false

**Comment by a526672351** [comment]
已解决使用     
config.nunjucks = {
        autoescape: false
    };

**Comment by atian25** [comment]
非常不建议你关掉，太不安全了

用 egg-securty 提供的 `{{ helper.safeHtml(html) }}` 方式吧

**Comment by hbrls** [comment]
我现在用的是 `{{ htmlstr | safe }}`，两者有区别吗？

**Comment by atian25** [comment]
@hbrls `safe` 是直接信任这段 html，而 egg-security 提供的 helper 是把 html 做下清洗
