### ISSUE TITLE
Framework Slogan

### ISSUE THREAD

**Issue by mattma** [eggjs/egg#90]
Here are a few ideas for the Egg.js framework slogan

1. A supreme node.js framework builder to maximize productivity

2. A modular framework builder for node.js developer

3.  The last node.js framework you ever need

4. The node.js framework changes everything

5. A promise to your success

6. A node.js framework Builder

7. next generation web framework builder for node.js (Note: compared with http://koajs.com/ slogan)

8. Modular, opinionated, feature rich web framework for Node.js (Note: compared with http://expressjs.com/ slogan)

**Comment by fengmk2** [comment]
1 look better.

"Born to build better enterprise frameworks and apps"

**Comment by mattma** [comment]
For some reason, the current slogan does not really communicate well in my opinion. Since the launch party has been done. I will take some good time to think of it. And improve it based on enterprise idea.
