### ISSUE TITLE
egg-sequelize按文档添加了model，但是生成的migration.js里面的up和down是空的

### ISSUE THREAD

**Issue by jay763190097** [eggjs/egg#900]
* **Node Version**:7.10.0
* **Egg Version**:1.1.0
* **Plugin Name**:egg-sequelize
* **Plugin Version**:2.1.4
* **Platform**:windows
* **Mini Showcase Repository**:
问题一：20170512041506-unnamed-migration.js
```
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.createTable('users', { id: Sequelize.INTEGER });
    */
  },

  down: function (queryInterface, Sequelize) {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.dropTable('users');
    */
  }
};
```
没有生成创建表的语句。
问题二：文件名unnamed,文档上没有说怎么给生成的文件起名。

**Comment by vance-liu** [comment]
1，just do not know
2，npm run [script name] -- --name user

**Comment by ityao** [comment]
`module.exports = app => {
  
  // 应用会等待这个函数执行完成才启动
  app.beforeStart(async () => {
    //自动创建对应的model
    app.model.User.sync({force: false})
  });
}`

**Comment by atian25** [comment]
`sync` 是 promise 的吧，要 `await` 下

```js
app.beforeStart(async () => {
  //自动创建对应的model
 await app.model.User.sync({force: false});
});
```

**Comment by huacnlee** [comment]
请阅读 Sequelize 官方关于 Migration 的文档

http://docs.sequelizejs.com/manual/tutorial/migrations.html

**Comment by IEfucker** [comment]
@huacnlee 请教下，migration方式相对model+sync方法更方便通用吗，这两种方式的适用场景不同吗，既然要手动维护一份独立于model的代码，感觉更麻烦了。

**Comment by huacnlee** [comment]
我建议使用 Migration 来维护数据结构。

**Comment by IEfucker** [comment]
谢谢，感觉至少代码应该和model用一份
