### ISSUE TITLE
更新数据库出存储json字符串的问题，导致那个数据表更新不了。

### ISSUE THREAD

**Issue by wscart** [eggjs/egg#901]
### html

$("button[type=submit]").click(function(){
        const dataStr = {
          site_name:'{{ site_name }}',
          site_keywords:'{{ site_keywords }}',
          site_mail:'{{ site_mail }}',
          site_beian:'{{ site_beian }}',
          site_description:'{{ site_description }}',
          site_statistic:'{{ site_statistic }}'
        }
        const data = JSON.stringify(dataStr);
        if(data){
            $.ajax({
            type:'get',
            url:'/setbasic/update/'+data,
            success:function(data){
                if(data == 'success'){
                  $.gritter.add({
                    title: '提交成功',
                    text: '更新站点配置项!',
                    class_name: 'color success'
                  });
                }
              }
           });
        }
        return false;
      });

### Service
    * update(){
        const data = this.ctx.params.data;
        console.log(data);
        const result = yield this.app.mysql.update('siteconfig',{ id: 1 , 'data':data });
        const updateSuccess = result.affectedRows === 1;
    }

这个egg-mysql到底是不是有问题，还是我写的方法错了？

**Comment by popomore** [comment]
Where is the error message?

**Comment by wscart** [comment]
@popomore No message，An egg - mysql may not be compatible.

**Comment by wscart** [comment]
找到了关键的问题，前端问题是
const dataStr = {
site_name:'{{ site_name }}',
site_keywords:'{{ site_keywords }}',
site_mail:'{{ site_mail }}',
site_beian:'{{ site_beian }}',
site_description:'{{ site_description }}',
site_statistic:'{{ site_statistic }}'
}
这个传不到了后台。。。
