### ISSUE TITLE
如何根据环境决定加载哪些插件？

### ISSUE THREAD

**Issue by Rwing** [eggjs/egg#902]
如题，plugin.js 似乎无法像 config.default.js 一样根据环境不同加载不同的配置文件。
例如我希望default 时加载egg-development-proxyworker插件，而 prod 时取消这个插件

**Comment by atian25** [comment]
plugin.local.js

发自我的 iPhone

**Comment by Rwing** [comment]
plugin.local.js 和 plugin.prod.js ？？

**Comment by popomore** [comment]
也可以通过 env 参数控制

```js
// plugin.js
module.exports = {
  proxyworker: {
    enable: true,
    env: [ 'local' ],
  }
}
```
