### ISSUE TITLE
egg-mysql app.instrument is not a function

### ISSUE THREAD

**Issue by Chen-xy** [eggjs/egg#903]
* **你好**
* **我按照了官网对egg-mysql进行了配置，但是现在出了一个问题。**
* **app.instrument is not a function，在egg-mysql的第25行。**
* **另：可以在不运行项目的情况下通过单独引用的形式来执行mysql嘛。**

**Comment by popomore** [comment]
请给出具体使用的版本
Chen-xy <notifications@github.com>于2017年5月12日 周五18:39写道：

**Comment by jtyjty99999** [comment]
不应该啊，egg和egg-mysql是什么版本的

**Comment by Chen-xy** [comment]
egg version 1.3.0
egg-mysql   1.1.1

**Comment by popomore** [comment]
egg-mysql 版本太低

**Comment by ngot** [comment]
issue模版，都看不见吗？ 这些提issue真是该拉出去打屁屁

**Comment by ngot** [comment]
我有个想法，做个bot检测所有issue，不符合要求的，全部自动回复&关闭

**Comment by popomore** [comment]
嗯，我也有想法，可以谋划一下
Hengfei Zhuang <notifications@github.com>于2017年5月12日 周五19:35写道：

**Comment by monkindey** [comment]
[ant-bot](https://github.com/ant-design/ant-bot) ant-design项目有用上

**Comment by okoala** [comment]
这个机器人还真可以有~

**Comment by ngot** [comment]
http://new-issue.ant.design/ 这个很棒的
