### ISSUE TITLE
egg-mongoose 的 Promise

### ISSUE THREAD

**Issue by Azard** [eggjs/egg#905]
* **Node Version**: v7.8.0
* **Egg Version**: v1.3.0
* **Plugin Name**: egg-mongoose
* **Plugin Version**: v2.0.0
* **Platform**: Darwin
* **Mini Showcase Repository**:
[Mongoose 官方不建议使用自带的 mpromise 库](http://mongoosejs.com/docs/promises.html)，在建立连接之后，在项目的初始化里自定义成 `app.mongoose.promise = global.Promise` 还是会弹 warning。
> DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own pro
mise library instead: http://mongoosejs.com/docs/promises.html

建议在 config 里加个 promise(optional) 字段，在[这行](https://github.com/eggjs/egg-mongoose/blob/master/lib/mongoose.js#L15)之前配置，或者默认使用 `global.Promise` 。

**Comment by zhangming0305** [comment]
+1

**Comment by popomore** [comment]
2.1.0 is out
