### ISSUE TITLE
linux 部署环境失败！

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#906]
* **Node Version**: 6.x
* **Egg Version**: 1.x.x
* **Plugin Name**: 
* **Plugin Version**: 
* **Platform**: ubuntu 16
* **Mini Showcase Repository**:

![rt8ta6c3ba0 i ls7d _ai](https://cloud.githubusercontent.com/assets/23026766/26022088/b9ac9c64-37cd-11e7-9287-488dcfbe1bb3.png)

**Comment by atian25** [comment]
excuse me？ node 6.x async？？？

发自我的 iPhone

**Comment by AkashiX** [comment]
🤣 Okay, I have found the solution...
