### ISSUE TITLE
如何在egg热重启成功后刷新浏览器页面

### ISSUE THREAD

**Issue by MrChongdong** [eggjs/egg#907]
egg 修改文件会引起 egg 服务热重启, 如何在热重启完成后刷新浏览器页面呢 ,worker 重启完成好像没有回调的接口

**Comment by bugss** [comment]
你可以试试看在这里
//  {baseDir}/app.js
```javascript
app.on('server', server => {

  })
```
works 最好在egg-bin 里面配置成1  . 不然可能会调多次 .
应该是可以的

**Comment by MrChongdong** [comment]
app.on 个应该是 koa 的 on 事件了吧,试了试,确实可以监听得到

**Comment by wangxuepeng** [comment]
这个问题有解决办法吗？

**Comment by atian25** [comment]
自己挂载 livereload 或 Webpack
