### ISSUE TITLE
能否增加一个egg结合ant-design的使用例子

### ISSUE THREAD

**Issue by junmaqiang** [eggjs/egg#910]
如果能把 egg作为后端的框架和antd作为前端框架结合起来,简直是一站式解决方案!
找了很多都没找到, 官方的朋友能否出一个例子? 因为这样的例子相信是可以帮助到很多朋友的!

**Comment by ngot** [comment]
可以增加，来发个PR吧 https://github.com/eggjs/examples @junmaqiang

**Comment by junmaqiang** [comment]
@ngot  PR是啥意思,求解!

**Comment by ngot** [comment]
@junmaqiang You should google it yourself!  https://www.google.com.hk/?gws_rd=ssl#newwindow=1&safe=strict&q=github+PR+

**Comment by AkashiX** [comment]
完全可以自己一个
