### ISSUE TITLE
app.resources中routerName有什么用

### ISSUE THREAD

**Issue by xiangle** [eggjs/egg#912]
RESTful路由中app.resources('routerName', 'pathMatch', 'controllerName')配置项，不知道routerName参数的应用场景是什么。

我想让多个路由指向同一个controller，希望在ctx中拿到routerName的值定位到对应的模型，但是不行，
目前临时的做法是用模型名称作为url，然后从url中提取。

想知道routerName是用来做什么的？

**Comment by atian25** [comment]
用于 app.pathFor

发自我的 iPhone

**Comment by fengmk2** [comment]
参考自 Ruby 社区的标准实现 http://api.rubyonrails.org/classes/ActionDispatch/Routing/UrlFor.html
