### ISSUE TITLE
egg-logger 不能获取customerLogger的bug

### ISSUE THREAD

**Issue by liuyu322** [eggjs/egg#915]
在使用egg-logger的过程中，发现不能够获取自定义logger，代码调试中，发现这个文件编写存在问题
[egg-logger](https://github.com/eggjs/egg-logger/blob/master/lib/egg/loggers.js)文件中第56行
```JavaScript
    const loggerConfig = utils.assign({}, defaults, config.logger);
    const customLoggerConfig = config.customLogger;
```
const customLoggerConfig = config.customLogger; 中的config应该写为loggerConfig

**Comment by dead-horse** [comment]
自定义 logger 要配置在 `config.customLogger` 下，而不是 `config.logger` 下。

**Comment by popomore** [comment]
自定义日志见 https://eggjs.org/zh-cn/core/logger.html#自定义日志
