### ISSUE TITLE
如何给模版引擎做拓展

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#917]
我的工程使用了`egg-view-handlebars`作为模版引擎，我需要给他做拓展，加上[koa-hbs](https://github.com/koajs/koa-hbs)的功能，让模板引擎支持`layouts`的能力。

开发大神有空的话求指点一下。

**Comment by popomore** [comment]
可以提 PR 来支持。

**Comment by atian25** [comment]
@popomore 貌似这个插件没有暴露 `app.handlebars`

**Comment by atian25** [comment]
@xjchenhao 给 https://github.com/eggjs/egg-view-handlebars 提 PR 支持下就好了

**Comment by xjchenhao** [comment]
@atian25 暴露api可以写拓展，还是集成进去，我是小菜不太会写啊。😅

**Comment by atian25** [comment]
你需要 koa-hbs 的什么功能?

**Comment by xjchenhao** [comment]
主要为了它俩。

```html
{{#block "sidebar"}}
  <!-- default content for the sidebar block -->
{{/block}}
```

```html
{{#contentFor "sidebar"}}
  <aside>
    <h2>{{sidebarTitleLocal}}</h2>
    <p>{{sidebarContentLocal}}</p>
  </aside>
{{/contentFor}}
```

**Comment by popomore** [comment]
其实跟 ejs 一个思路，模板引擎本身不支持，通过 hack 来支持。但是 handlebars 本身就不推崇强逻辑，后端模板何必用这个呢。

**Comment by xjchenhao** [comment]
我也想不用handlebars，老代码页面全是基于handlebars渲染的，不想重写啊，那么多页面🙈

**Comment by atian25** [comment]
欢迎 PR，或者自己写个二级插件扩展，先 close 了，有问题再开
