### ISSUE TITLE
不同单元测试mock之间会`串门`

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#919]
我们应用一共写了12个文件，72个用例。

* 每个文件单独用譬如`egg-bin test test/service/employee.test.js `去跑，均能跑过
* 但，用`egg-bin test`一起跑时，有3个跑不通（这3个在单独文件中跑时是ok的）

最后我定位到是因为`app.mockService`的原因，有时我需要mockService，有时不需要。

这3个case的共同点都是：

> 依赖的service曾经被mock过

我认为这些代码在文件之间是隔离的，但现在受影响了
```
 before(function *() {

        app = mock.app();

        yield app.ready();
        ctx = app.mockContext();

        app.mockService('ddUser', 'deleteUser', function*() {
        });

});
```

求解决方案

* 最好，文件之间隔离（或者`mock.app()`实例之间隔离）
* 最次，提供reset方法，还原mock的service

**Comment by popomore** [comment]
`afterEach(mm.restore);` 加上这句。

**Comment by johnnychen** [comment]
漂亮，75个用例全跑过了，加了`after(mock.restore);`

刚看了下文档，是有这句话的，谢谢

**Comment by atian25** [comment]
@johnnychen 最好看下 egg-init 生成的示例代码，应该用 `afterEach(mock.restore)` ，另外如果是插件的话，还要有  `after(() => app.close())`

**Comment by popomore** [comment]
写了好多用例
