### ISSUE TITLE
在使用typescript开发时，router的方法无法进行严格的typing定义

### ISSUE THREAD

**Issue by W1U02** [eggjs/egg#920]
当在使用Typescript进行egg的开发的时候，无法对router的函数进行严格定义。
现在的函数定义是这样的
`app.verb([name:string],rule:string|regex, [middleware1, ..., middlewareN,] controllerAction:middleware|string);`

在koa-router中，action是通过middleware的方式定义，Egg对koa-router进行了扩展，提供了一个string的格式，但是这样做，就会在函数后面添加了一个必须的参数，而这个参数和前面的可选middleware数组类型不一致。  

 建议将app中route的定义改成把controller.action 放到middlewares之前，这样的话函数的定义会比较统一。typings可以这样定义
`app.verb([name:string], rule:string|regex, controllerAction:middleware|string, ...middlewares:middleware[])`

**Comment by popomore** [comment]
代码不会改的，只能通过 ts 来描述，如果做不到应该去 typescript 提问。

cc @shepherdwind

**Comment by shepherdwind** [comment]
嗯，后面那种写法也不是很好。理论上，路由应该是

```ts
app.verb([name:string],rule:string|regex,  ...middlewares:middleware[]);
```

最后一个支持 string 是 egg 提供的简化形式，也可以直接用 function 的。ts 就直接用 function 模式应该更好些。

**Comment by W1U02** [comment]
@shepherdwind 的建议挺好，就是不使用egg提供的简化模式，这样还能对function的类型进行判断。
但是如果是这样的话，建议修改一下文档中关于router的那一节

**Comment by shepherdwind** [comment]
@popomore router 写法中，最后一个参数函数的模式，要不要在文档中放出来？现在文档中只有字符串模式的，ts 里面可能更习惯用函数模式，那样可以有代码补全提示，会好点。

**Comment by atian25** [comment]
可以提个 PR：
- 在 Controller 章节说明下会挂载到哪里，类似 Service。
- 在 Router 章节给出用法，注明两种都可以使用。

**Comment by dead-horse** [comment]
如果通过 string 形式简写对 ts 不好的话，文档里面还是推荐直接用 app.controller.xx 好了
