### ISSUE TITLE
egg-bin启动服务提示DEBUG=common-bin

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#922]
你好，我下载了`egg-view-handlebars`，在`/test/fixtures/apps/view-handlebars-test`目录下执行`egg-bin dev`提示`DEBUG=common-bin`。

怎样才能让这个模块的测试demo跑起来？

**Comment by atian25** [comment]
fixtures 不是 example，里面的 package.json 是没有写依赖的，你可以：

用 egg-init 生成一个 simple，把 fixtures 里面对应的东西复制过去，按插件的文档去配置 plugin 等。

**Comment by xjchenhao** [comment]
@atian25 👌我看看
