### ISSUE TITLE
egg-development-proxyworker install

### ISSUE THREAD

**Issue by cuyl** [eggjs/egg#924]
* **Node Version**: *
* **Egg Version**: 1.3.0
* **Plugin Name**: egg-development-proxyworker
* **Plugin Version**: 1.0.1

egg-development-proxyworker配置在config/plugin.js中
使用`npm i egg-development-proxyworker --save` 安装
调试工具安装在dependencies而不是devDependencies感觉不太好

**Comment by popomore** [comment]
也可以装在 dev，配在 plugin.local.js

**Comment by cuyl** [comment]
原来如此，好像文档里没写可以这样

**Comment by okoala** [comment]
@cuyl  这个确实是文档问题，装在 dev 就可以了，我改下~

**Comment by okoala** [comment]
计划下周发一个版，安装的时候自动把 vscode 的配置写上，文档到时候一起改吧~

**Comment by tong3jie** [comment]
@okoala 文档确实有问题

**Comment by cuyl** [comment]
看到发了一个新版本 eggjs/egg-development-proxyworker/pull/5
但是没有更新文档

**Comment by okoala** [comment]
@cuyl  谢谢提醒，我更新下~

**Comment by cuyl** [comment]
应该把安装改成
`npm i egg-development-proxyworker --save-dev`
配置在配在 plugin.local.js

**Comment by okoala** [comment]
@cuyl  这个忘了，我稍后再修下~

**Comment by atian25** [comment]
都 ok 吧，如果这个插件集成到 egg 的话，就要在 dep 而不是 devdep 了。

**Comment by cuyl** [comment]
集成到egg到话，那么默认在prod环境关闭比较好

**Comment by atian25** [comment]
肯定必然是 local 才启动啊，就像 egg-development 那样。

**Comment by cuyl** [comment]
嗯

**Comment by okoala** [comment]
已经是配置上了的，放心~

**Comment by okoala** [comment]
先关掉吧~
