### ISSUE TITLE
egg-userrole权限验证模块怎么使用啊？我想用它来判断用户session

### ISSUE THREAD

**Issue by lzq920** [eggjs/egg#927]
* **Node Version**:7.9
* **Egg Version**: 1.3
* **Plugin Name**: egg-userrole
* **Plugin Version**:1.1.1
目前我的代码是这样写的：
```
config/plugin.js

exports.userrole = {
  enable: true,
  package: 'egg-userrole',
};

```
```
confing/role.js
module.exports = app => {
  app.role.use('admin', function() {
    const userid = this.session.userid;
    console.log(userid);
    if (userid) {
      return true;
    }
    this.redirect('/');
  });
};
```
```
app/router.js

module.exports = app => {
  const islogin = app.role.can('admin');
  app.get('/', 'home.index');
  app.get('/topic/:id', 'home.articletopic');
  app.get('/login', 'home.getlogin');
  app.post('/login', 'home.login');
  app.get('/admin', islogin, 'admin.index');
};

```

问题就在于如果有session的情况下是对的，而没有session的情况下，它不会跳转，页面提示重定向次数过多

**Comment by dead-horse** [comment]
你可以用 `curl -v` 看一下整个重定向的过程，是怎么循环导致重定向过多的

**Comment by lzq920** [comment]
@dead-horse curl -v怎么使用呀？？不懂。。求指教

**Comment by dead-horse** [comment]
`curl -v http://localhost:7001/admin`

**Comment by lzq920** [comment]
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 7001 (#0)
> GET /admin HTTP/1.1
> Host: localhost:7001
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< set-cookie: csrfToken=ov_ZtTDh3Th_eZotRmxnmOA0; path=/
< Location: /
< content-type: text/html; charset=utf-8
< content-length: 33
< x-frame-options: SAMEORIGIN
< x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
< x-download-options: noopen
< x-readtime: 4
< Date: Wed, 17 May 2017 07:35:50 GMT
< Connection: keep-alive
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
Redirecting to <a href="/">/</a>.

**Comment by dead-horse** [comment]
后面没了么？如果从这个结果看就是正常的，访问 /admin 重定向到 / 了

**Comment by atian25** [comment]
@lzq920 或者提供下最小可复现的代码, 提交到自己的 GitHub

**Comment by lzq920** [comment]
@atian25 不知道怎么捣鼓给捣鼓出来了，但是希望能帮我看一看是不是对的。[https://github.com/lzq920/eggclub](https://github.com/lzq920/eggclub)

**Comment by dead-horse** [comment]
在 role.js 的 failureHandler 中必须要对响应做处理，redirect 或者直接响应一个页面，或者报 403 错误。
