### ISSUE TITLE
cookie文档与实现不一致

### ISSUE THREAD

**Issue by johnnychen** [eggjs/egg#931]
cookie文档关于签名参数`sign`有错误：https://eggjs.org/zh-cn/core/cookie-and-session.html

> sign（Boolean）：设置是否对 Cookie 进行签名，如果设置为 true，则设置键值对的时候会同时对这个键值对的值进行签名，后面取的时候做校验，可以防止前端对这个值进行篡改。默认为 true。

自己试了半天，发现不起作用，翻开源码后，发现应该为`signed`: https://github.com/eggjs/egg-cookies

譬如`set()`时
```
if (opts.signed) {
      cookie.value = value && this.keys.sign(cookie.toString());
      cookie.name += '.sig';
      headers = pushCookie(headers, cookie);
    }
```

**Comment by dead-horse** [comment]
提一个 PR 修复一下吧

**Comment by johnnychen** [comment]
okay

#932
