### ISSUE TITLE
ctx.cookies.get("xxx")失效

### ISSUE THREAD

**Issue by outlookxie** [eggjs/egg#936]
* **Node Version**: 4.4.4
* **Egg Version**:release-3
* **Plugin Name**: 
* **Plugin Version**:
* **Platform**: Mac OS
* **Mini Showcase Repository**:
在control层取不到cookie取不到

module.exports = function* (ctx) {
  console.log(ctx.cookies.get('dd_l')); //undefined
console.log(this.cookies.get('dd_l')); //undefined
console.log(this.get("cookie")) //得到所有cookie 
}

**Comment by ngot** [comment]
https://eggjs.org/zh-cn/intro/quickstart.html#环境准备 

 # 环境准备

- 操作系统：支持 macOS，Linux，Windows
- 运行环境：建议选择 LTS 版本，最低要求 6.x

**Comment by atian25** [comment]
这是啥时候的代码了..

egg 现在是 1.0, node 最低要求 6.x....

看下文档, 用 egg-init 初始化骨架吧

**Comment by outlookxie** [comment]
node已升级到6.10.3 还是有问题， 直接用koa是可以的，跟node版本应该无关

**Comment by outlookxie** [comment]
通过egg脚手架搭建的

**Comment by fengmk2** [comment]
> console.log(this.get("cookie")) //得到所有cookie

返回值是? dd_l cookie 是怎样设置的？

**Comment by ngot** [comment]
测试是怎么操作的呢? curl ，还是浏览器访问的，还是unit-test？

**Comment by outlookxie** [comment]
浏览器访问，dd_l是cookie里面的一个字段，是通过前端写入的，另外通过工具查看请求头的所有cookie，选择其他cookie子段也拿不到

**Comment by fengmk2** [comment]
@outlookxie 那就对了，根据 cookie 文档 https://eggjs.org/zh-cn/core/cookie-and-session.html#contextcookiesgetkey-options ，默认服务端只认 signed 的 cookie。

如果你的 cookie 是前端写入，你在读取的时候将 signed 设置为 false

```js
ctx.cookies.get('dd_l', { signed: false });
```

**Comment by outlookxie** [comment]
好，我试下

**Comment by runhwguo** [comment]
@fengmk2 潜规则太多了吧，向这样的规则，可否在日志里warn提示呢？

**Comment by jemmyzheng** [comment]
这个 文档 太不清晰了

**Comment by duncup** [comment]
欢迎 PR 完善 @jemmyzheng

**Comment by fengmk2** [comment]
@runhwguo cookies 本来就不是一个简单的功能。
