### ISSUE TITLE
按照文档来debug egg 项目不先行，求正确的debug 方式

### ISSUE THREAD

**Issue by yangnuowei88** [eggjs/egg#937]
求webstorm 下正确的debug 方式，按照文档上的，根本就不行！

**Comment by atian25** [comment]
请先阅读 [「如何向开源项目提交无法解答的问题」](https://zhuanlan.zhihu.com/p/25795393)

等补充完信息后，欢迎重启 reopen。

**Comment by yangnuowei88** [comment]
问题已经接近了，谢谢兄弟哈！

**Comment by yangnuowei88** [comment]
解决了

**Comment by ngot** [comment]
解决办法，可以贴一下。方便其他人看到。
