### ISSUE TITLE
快速入门，按照例子 请问为什么？在线等  很奇怪！

### ISSUE THREAD

**Issue by dmKiller** [eggjs/egg#939]
Can't find viewEngine for /Users/songt/songt/develop/nodejs/eggApp/app/view/news/list.tpl

**Comment by atian25** [comment]
看起来是没安装 egg-view-nunjucks 插件并配置了 plugin.js 和 config 里面的 config.view , config.nujucks

**Comment by dmKiller** [comment]
config.default.js

**Comment by dmKiller** [comment]
```
'use strict';

module.exports = appInfo => {
  const config = {};

  // should change to your own
  config.keys = appInfo.name + '_1495176918228_5805';

  // add your config here

  return config;
};

exports.view = {
  defaultViewEngine: 'nunjucks',
  mapping: {
    '.tpl': 'nunjucks',
  },
};
```
```

'use strict';

// had enabled by egg
// exports.static = true;
exports.nunjucks = {
	enable: true,
	package: 'egg-view-nunjucks'
};
```

**Comment by dmKiller** [comment]
npm i egg-view-nunjucks --save  这个我安装了 我在module中也看到了。很奇怪

**Comment by hbrls** [comment]
要么 module.export 要么 exports，参考 #732。

话说这个入门文档真的不需要改么。。。

**Comment by popomore** [comment]
用来检测 node is用户的水平吗

**Comment by dmKiller** [comment]
我也发现了，我把app.config打印了 才发现，学习到了 module.exports 和 exports的区别  这是入门坎麽？

**Comment by atian25** [comment]
@dmKiller 这个是 Node.js 的基础入门知识。

**Comment by dmKiller** [comment]
继续学习中，谢谢您的指导

**Comment by ngot** [comment]
这个问题差不多就是不带脑子

**Comment by dmKiller** [comment]
呵呵

**Comment by ngot** [comment]
嗯，算了

**Comment by ngot** [comment]
https://nodejs.org/dist/latest-v7.x/docs/api/modules.html#modules_module_exports @dmKiller 这个是在模块文档一开始就讲了。然而这种问问，却量多的惊人。被问多了，自然就会觉得烦。不是针对你而说的。

**Comment by dmKiller** [comment]
理解
