### ISSUE TITLE
sos，生产环境，怎么修改端口号？

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#940]
跟目录下执行`node index.js --port 7777`无法设置端口号。

我知道开发环境基于`egg-bin`可以设置端口号，可是生产环境不需要安装`egg-bin`这个依赖吧？那应该怎么设置呢？？

**Comment by atian25** [comment]
`startCluser({ port })`

**Comment by xjchenhao** [comment]
具体怎么弄，求教，最后一一步了。。。。 🙏🏻

**Comment by atian25** [comment]
不是已经讲得很清楚了么。。。
看看你的 index.js 找到 `startCluser` 这个关键词，再看看我的回复。

**Comment by xjchenhao** [comment]
额 我看到了 醉了 原来有提供`process.env.PORT`的设置。。。 🙈  谢谢

**Comment by ngot** [comment]
process.env.PORT 这不是egg提供的。是node.js基础api

**Comment by atian25** [comment]
@ngot 也不算 node 的，只是骨架生成的代码里面，默认了
```js
startCluster({
  port: process.env.PORT || 7001,
})
```

**Comment by ngot** [comment]
@atian25 哈，那也可以算。
