### ISSUE TITLE
如何在生产环境关闭`egg-static`的缓存

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#941]
你好，我想问下。

在生产环境上修改下css，都要重启服务来生效，好麻烦。看了文档应该是`egg-static`做的处理吧。然后我做了如下代码修改，但是并没有用。应该怎么处理？

```
// config/config.default.js

    config.static = {
        prefix: '/',
        buffer: false
    };
```

**Comment by atian25** [comment]
cache 不是 buffer。

为什么要在服务器改 css.... 你需要的是 fiddle 本地拦截改

**Comment by ngot** [comment]
https://github.com/eggjs/egg-static/blob/master/README.md#configuration 

配置：

config.prod.js

```js

exports.static  = {
   buffer: false
};

```

**Comment by ngot** [comment]
为什么要 "在生产环境上修改下css"，这个看起来不太合理。

**Comment by xjchenhao** [comment]
嗯 可以了。
需求是 前端页面样式做了修改，比如改了个颜色，然后ftp上传css文件。

这种小改动都要重启服务器，太蛋疼了。。。

**Comment by ngot** [comment]
"在生产环境上修改下css" => 发布静态静态。 这个需求看起来是合理的。

**Comment by xjchenhao** [comment]
是我描述不够恰当，哈～ 

感觉这个默认设置，不是很科学呀，发布静态文件是常有的事。

**Comment by ngot** [comment]
线上默认缓存是合理的。发布静态资源也是合理的。需要组合一下。@xjchenhao 研究下，搞个插件来

**Comment by atian25** [comment]
静态资源不是该上 cdn 么

发自我的 iPhone

**Comment by xjchenhao** [comment]
小公司 新项目 木有cdn..  @atian25 
小菜，还没达到能贡献代码的水平，😅 @ngot

**Comment by lairdutemps** [comment]
> https://github.com/eggjs/egg-static/blob/master/README.md#configuration
> 
> 配置：
> 
> config.prod.js
> 
> ```js
> exports.static  = {
>    buffer: false
> };
> ```

可以了，谢谢
