### ISSUE TITLE
线上工程能否一键重启？

### ISSUE THREAD

**Issue by xjchenhao** [eggjs/egg#945]
我的工程已经部署上线了，并配置了`dispatch.js`，跟官方示例一样在线上服务器上通过`EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &`，启动项目进程。
```
//dispatch.js
const egg = require('egg');
egg.startCluster({
    baseDir: __dirname,
    port:7777
});
```

每次代码更新上传到服务器，需要重启服务。我现在的处理方式如下：
1. 服务器上执行`lsof -i :7777`，查看进程的`PID`
2. `kill -9 123123`关闭进程（123123替换为前面查看的`PID`）
3. 项目根目录下执行`EGG_SERVER_ENV=prod nohup node dispatch.js > stdout.log 2> stderr.log &`

感觉好繁琐啊，有没有一键重启的方式呢？

**Comment by atian25** [comment]
停止的话， 目前 kill master 进程即可，里面会做优雅退出的，**切忌不要 -9  **

后面有个 egg-scripts 的命令行工具会来辅助这块，最近有点忙还没时间开源出来，但原理其实跟上面说的差不多，只是用 node 包装了下。

**Comment by xjchenhao** [comment]
好的 谢谢 @atian25

**Comment by tageecc** [comment]
能否设置watcfile自动重启

**Comment by atian25** [comment]
不建议，你集群情况怎么办？
