### ISSUE TITLE
想用egg实现视频上传后压缩转码存储在服务器

### ISSUE THREAD

**Issue by jinchaoxiang** [eggjs/egg#946]
* **Node Version**:
v7.0.0
* **Egg Version**:
v1.3.0
* **Plugin Name**:
fluent-ffmpeg.js
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

想用egg实现视频上传后压缩转码存储在服务器，发现压缩转码存储非常的慢，看了下egg的官方文档 是否可以用app发出通知让agent或者worker来处理视频压缩转码的脏活，能否请大神指点一二

**Comment by dead-horse** [comment]
这类 CPU 密集的场景，没有办法真正的缓解，有几种方案：

1. 尽量采用 stream，`用户上传 | 压缩 | 转储`，减少用户等待时间。
2. 如果不能 stream 形式，可以考虑用户上传文件之后，通过 `ctx.runInBackground(function*() { // dosomething})` 让压缩和转储继续执行，同时先返回响应给用户。这样存在的风险是可能文件压缩和转储失败，用户无感知，需要增加查询。
3. 收到上传文件后，上传到共享文件存储中，并异步让其他压缩集群来做后面的压缩和转储，这个方案更复杂，需要重新设计架构了。

**Comment by jinchaoxiang** [comment]
感谢

**Comment by popomore** [comment]
最好是离线转码，比如类似 lamda 的方式 https://www.qcloud.com/product/scf
