### ISSUE TITLE
求教如何实现文件下载。

### ISSUE THREAD

**Issue by dear-lizhihua** [eggjs/egg#948]
是否是因为我使用方法不对，在文档里搜索，只看到文件上传，但是没有找到文件下载的相关文档。
网上找了许多文件流的使用说明，终于能够正常将 Content-Type 设置为 application/octet-stream，以及将 Content-Disposition 设置为 attachment; filename=test.txt，但是浏览器并没有进行预期的下载。我觉得或许是我把文件流赋给 ctx.body 造成的，实在没有实现的思路，所以前来请教如何是正确的下载方式。

* **Node Version**: v6.10.3
* **Egg Version**: v1.3.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

```
// /app/controller/test.js
'use strict';

const fs = require('fs');

module.exports = app => {
  class TestController extends app.Controller {
    * index() {
      const {ctx} = this;
      var stats = fs.statSync(__dirname + '/test.txt', {
        encoding: 'utf8'
      });
      ctx.response.set({
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': `attachment; filename=test.txt`,
        'Content-Length': stats.size
      });
      const stream = fs.createReadStream(__dirname + '/test.txt');
      stream.pipe(ctx.res);
      ctx.body = stream.pipe(ctx.res);
    }
  }
  return TestController;
};

// /app/controller/test.txt
hello, egg.
```

**Comment by ngot** [comment]
为什么不在nginx那层做。

**Comment by dear-lizhihua** [comment]
因为是内部的一个管理平台，属于初步搭建阶段，而且我本人对 Node.js 算是新手，所以是以 Node.js 来实现的，我记得之前的后端 Java 同事可以实现文件下载，Node.js 作为 HTTP 客户端，应该也是可以实现的吧。

**Comment by dead-horse** [comment]
```js
      const stream = fs.createReadStream(__dirname + '/test.txt');
      stream.pipe(ctx.res);
      ctx.body = stream.pipe(ctx.res);
```

改成 

```js
ctx.body = fs.createReadStream(dirname + '/test.txt');
```

**Comment by dear-lizhihua** [comment]
浏览器还是没有正常下载。

**Comment by dear-lizhihua** [comment]
router.js
```js
'use strict';
module.exports = app => {
  app.get('/api/term/test', 'test.index').post('/api/term/test', 'test.index');
  app.get('*', 'default.index').post('*', 'default.index');
};
```

controller/test.js
```js
'use strict';

const fs = require('fs');

module.exports = app => {
  class TestController extends app.Controller {
    * index() {
      const {ctx} = this;
      var stats = fs.statSync(__dirname + '/test.txt', {
        encoding: 'utf8'
      });
      ctx.response.set({
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': `attachment; filename=test.txt`,
        'Content-Length': stats.size
      });
      ctx.body = fs.createReadStream(__dirname + '/test.txt');
    }
  }
  return TestController;
};
```

**Comment by dead-horse** [comment]
将可复现的完整 demo 提交到 github 发出来

**Comment by dear-lizhihua** [comment]
@dead-horse OK，非常感谢。我去建立一个仓库。

**Comment by wangzhenggui** [comment]
解决了吗，遇到同样的问题了

**Comment by unclexiao** [comment]
1. 后端下载到服务器（指定目录），引入[request](https://www.npmjs.com/package/request)模块，指定文件流的重定向位置即可：
```js
const request = require('request'); // 引入模块
const targetPath = path.resolve(`temp/xxx.jpg`);  //目标路径
const stream = request.get(url).pipe(fs.createWriteStream(targetPath)); // 流处理
stream.on('finish', () => {
     resolve(targetPath); // 下载完成
 });
```

2. 前端下载文件，直接一个a标签是最简单的，href带上可访问的文件路径。
```html
<a href="可访问地址" target="_blank">下载</a>
```

3. 跟EggJS结合，后端下把文件放到可`public`文件夹，生成链接返回给前端，浏览器点击则自动下载。

**Comment by atian25** [comment]
@unclexiao 

1. request 这个库已经放弃维护的，也没必要引入，自带的 httpclient 就够了。
2. 放到 public，在集群情况下会有问题，一般是丢 oss 去。
3. 在 eggjs/examples 里面有示例 @wangzhenggui

**Comment by kaqiinono** [comment]
现在的问题是 把文件丢到oss里去又会遇到跨域的问题 又不能改cdn服务器的反向代理设置 这个怎么办呢
难道真的要再在项目里创建一个下载接口读取cdn图片进行下载吗 有没有更好的办法 @atian25

**Comment by atian25** [comment]
oss 的访问都是通过 cdn 的，cdn 都是 * 的，怎么会有跨域问题？

**Comment by kaqiinono** [comment]
我遇到的cdn确实存在跨域问题，如果出现这种情况该怎么处理呢？
怎么设置如下属性：
{
      'Content-Type': 'application/octet-stream',
      'Content-Disposition': 'attachment; filename='+fileName,
      'Content-Length': stats.size
    }

@atian25

**Comment by atian25** [comment]
看 CDN 配置文档，或找 CDN 客服

**Comment by speedsmile** [comment]
今天还遇到了下载问题，使用
ctx.body = fs.createReadStream(filePath);
前端一直处于download状态，最后就提示网络错误失败。在本地试了好多次都不管用

**Comment by 2462870727** [comment]
经过本人实验， 我觉得即使egg 返回这样的响应 
![image](https://user-images.githubusercontent.com/50451924/167837571-3bff6596-e916-4e2f-b842-9bb170295560.png)

前端也应当做对流的处理，比如a链接下载， 浏览器似乎并不能自动询问下载
