### ISSUE TITLE
启动eggt老是显示--debug-port=58656

### ISSUE THREAD

**Issue by dangyanglim** [eggjs/egg#949]
* **Node Version**:v6.9.5
* **Egg Version**:1.1
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:centos6.8
* **Mini Showcase Repository**:

我用pm2 启动egg

启动文件pm2.js如下
const egg = require('egg');
// const workers = Number(process.argv[2] || require('os').cpus().length);
const workers = Number(process.argv[2] || 1);
egg.startCluster({
  workers,
  baseDir: __dirname,
  port: process.env.PORT || 7001, // default to 7001
});

启动方法
EGG_SERVER_ENV=prod pm2 start pm2.js

用ps -ef| grep node 查看

root     11210 11192  3 10:23 ?        00:00:00 /usr/local/sbin/node --debug-port=5856 /root/manage/node_modules/egg-cluster/lib/agent_worker.js {"framework":"/root/manage/node_modules/egg","baseDir":"/root/manage","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":"","clusterPort":36035}
root     11220 11192  5 10:23 ?        00:00:00 /usr/local/sbin/node /root/manage/node_modules/egg-cluster/lib/app_worker.js {"framework":"/root/manage/node_modules/egg","baseDir":"/root/manage","port":7001,"workers":1,"plugins":null,"https":false,"key":"","cert":"","clusterPort":36035}

老是有个 --debug-port=5856

我不用pm2 直接启动egg也是有个 --debug-port=5856的

这是在调试模式下运行吗？

**Comment by alex-zhang** [comment]
同问

**Comment by atian25** [comment]
不是的，没有 `--debug` 的情况下， `debug-port` 是没有意义的，那个只是用来在 debug 时修改 agent 的端口，因为一般调试主要调试 worker。

https://github.com/eggjs/egg-cluster/blob/master/lib/master.js#L153
