### ISSUE TITLE
controller目录下的文件名不能取MobileUser.js这样的大小写文件名？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#952]
我在controller目录下取名了一个MobileUser这样大小写分的文件名，但是在router.js文件里配置映射：
app.get('/api/v1/mobile/user/update', 'MobileUser.update');
老是说找不到MobileUser呢？用mobileuser或者mobile_user都不行。
只能把controller下的MobileUser.js改成mobileuser.js才行，这个controler下的文件名不能用大小写？

**Comment by atian25** [comment]
会自动驼峰处理为 `mobileUser.update`

**Comment by popomore** [comment]
controller 只支持首字母小写，这不是一个类，是实例

https://eggjs.org/zh-cn/advanced/loader.html#casestyle-string
