### ISSUE TITLE
egg用生产环境运行后，用什么命令可以停止应用？

### ISSUE THREAD

**Issue by arden** [eggjs/egg#953]
我用 EGG_SERVER_ENV=prod nohup node index.js > ./logs/stdout.log 2> ./logs/stderr.log & 命令运行后，有什么命令能够停止这个应用，有没有像pm2这样直接有stop命令停止这个应用？

**Comment by atian25** [comment]
dup: https://github.com/eggjs/egg/issues/945#issuecomment-303010988

**Comment by popomore** [comment]
kill "进程 PID"

部署脚本项目还未完成，可以先用这种方式。

**Comment by atian25** [comment]
master 进程 PID，切忌不要 -9

**Comment by arden** [comment]
@atian25 OK，谢谢。

**Comment by shanelau** [comment]
那我的生产环境怎么重启呢？ 每次登陆到服务器执行脚本吗？

**Comment by atian25** [comment]
@shanelau 你这个是杀 worker 吧

BTW，现在 `-9` 也不怕了，会优雅退出： https://github.com/eggjs/egg-cluster/pull/30

**Comment by shanelau** [comment]
测试了很多遍，master 进程会在 cluster 之前。用以下的脚本

```
ps -ef|grep node | awk '{print $2}'|xargs kill
```
