### ISSUE TITLE
请问是否可以直接渲染html，不使用模板？或者说是否有渲染html的模板？

### ISSUE THREAD

**Issue by yuanzx** [eggjs/egg#955]
不需要服务器端渲染，又不能改文件后缀

**Comment by popomore** [comment]
放 public 下 https://eggjs.org/zh-cn/intro/quickstart.html#静态资源

**Comment by yuanzx** [comment]
@popomore 这文件的访问是受controller控制的，放静态资源里不太合适

**Comment by popomore** [comment]
controller redirect 就好了

**Comment by atian25** [comment]
rediect 或者自己 `ctx.body =  fs.createReadStream(path.join(app.config.static.dir, 'path/to/file'))`

**Comment by atian25** [comment]
参考下 https://github.com/eggjs-community/egg-view-static
