### ISSUE TITLE
egg 能支持graphql 吗

### ISSUE THREAD

**Issue by grubed** [eggjs/egg#956]
egg 能支持graphql 吗？或者规划中有计划做支持吗

**Comment by luicfer** [comment]
有个插件草案#468
但是没有定下具体的规划

**Comment by dead-horse** [comment]
可以，和其他 web 框架的实现方式没有区别，可以自行实现。暂时不会有官方支持计划。

**Comment by jtyjty99999** [comment]
已经发布  egg-graphql@1.0.0
