### ISSUE TITLE
Document improvement

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#958]
一张草图

![default](https://cloud.githubusercontent.com/assets/360661/26405122/f1db0b5a-40c6-11e7-935e-d894e3cfa795.png)

1. 通过面包屑支持文章的 toc
1. 侧栏可折叠

**Comment by popomore** [comment]
@hi-caicai 补充一下完整的图

**Comment by dead-horse** [comment]
感觉面包屑导航没有云雀那种清晰？

**Comment by okoala** [comment]
![image](https://cloud.githubusercontent.com/assets/2127199/26411404/6939236a-40d8-11e7-938a-6522dd2d84ff.png)

我觉得布局可以稍微再大点，类似这种~ 

![image](https://cloud.githubusercontent.com/assets/2127199/26411545/b77beae4-40d8-11e7-9679-4638015fe310.png)

而且这里有三层背景色，比较乱~

**Comment by monkindey** [comment]
侧边栏顺便可以支持高亮当前选中内容在侧边栏位置
