### ISSUE TITLE
Make sure worker and agent process auto exit after master exit accident

### ISSUE THREAD

**Issue by fengmk2** [eggjs/egg#959]
- ref https://zhuanlan.zhihu.com/p/27069865

**Comment by fengmk2** [comment]
kill -9 master 退出，worker 也退出了，但是 agent 没有退出。感觉是 cluster fork 和 child_process.fork 有差别。

**Comment by fengmk2** [comment]
只需要加 agent 与 master 直接的心跳了。

**Comment by fengmk2** [comment]
```js
process.once('disconnect', () => {
    worker.emit('disconnect');

    if (!worker.exitedAfterDisconnect) {
      // Unexpected disconnect, master exited, or some such nastiness, so
      // worker exits immediately.
      process.exit(0);
    }
  });
```

https://github.com/nodejs/node/blob/master/lib/internal/cluster/child.js#L31

**Comment by fengmk2** [comment]
只需要在 agent.js 里面监听 `process.once('disconnect', () => {}` 做 exit 处理即可。

**Comment by popomore** [comment]
好像要设 ipc 才有这个事件

**Comment by fengmk2** [comment]
child_process.fork  的子进程都会有这个事件。

**Comment by popomore** [comment]
https://nodejs.org/api/process.html#process_event_disconnect

**Comment by popomore** [comment]
> It is important to keep in mind that spawned Node.js child processes are independent of the parent with exception of the IPC communication channel that is established between the two. 

好像默认的

**Comment by fengmk2** [comment]
只要是子进程，parent 意外退出，IPC 都会关闭，于是子进程会收到 disconnect 事件。

**Comment by popomore** [comment]
https://github.com/eggjs/egg-cluster/pull/27
