### ISSUE TITLE
关于session跨域问题

### ISSUE THREAD

**Issue by AkashiX** [eggjs/egg#960]
跨域访问导致session丢失，请问如何解决session共享问题？egg有提供相关的解决方案么？

**Comment by jtyjty99999** [comment]
有redis store的session store

**Comment by dead-horse** [comment]
说的是前端跨域么？跨域 cookie 无法传递，当然无法共享 session，这个解决起来要做跨域的免登和 cookie 同步。

**Comment by AkashiX** [comment]
@dead-horse 前端跨域。
http://www.cnblogs.com/zhangcybb/p/6594991.html
这种解决方案能解决么？

**Comment by AkashiX** [comment]
尽量是想把解决方案简化，走redis太重了，项目本身不是很大。

**Comment by popomore** [comment]
所以你是我 ajax 跨域调用？

**Comment by AkashiX** [comment]
fetch，Promise方式处理。

**Comment by dead-horse** [comment]
与 egg 没什么关系，你去研究一下跨域和 CORS 吧。
