### ISSUE TITLE
egg 文件下载该如何设置？有没有大神可以指点一下

### ISSUE THREAD

**Issue by GeneralFy** [eggjs/egg#962]
* **Node Version**:
* **Egg Version**:
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

**Comment by popomore** [comment]
可以写具体一点吗？一般资源文件放 app/public 就好了

**Comment by GeneralFy** [comment]
ctx.res.setHeader('content-type','application/octet-stream');
            ctx.res.setHeader('content-disposition','attachment; filename='+'1111.json');
            console.log(ctx.res.getHeader('content-type'));
            ctx.res.statusCode = 200;
            ctx.res.write(buffer,'utf8',function () {
                console.log('------------test');
            });
            ctx.res.end();
我是这么写的,获取一个buffer 然后发送给浏览器 但浏览器被没有下载文件

**Comment by popomore** [comment]
`ctx.body = buffer;`

**Comment by popomore** [comment]
设置 header 这样写 https://eggjs.org/zh-cn/basics/controller.html#设置-header

**Comment by GeneralFy** [comment]
ctx.body = buffer; 
这个我也试了不行

**Comment by GeneralFy** [comment]
2017-05-26 13:33:08,712 ERROR 9416 [-/::1/-/4ms POST /saveFile] nodejs.Error: Can't set headers after they are sent.

**Comment by popomore** [comment]
在前面设置

**Comment by GeneralFy** [comment]
ctx.res.statusCode = 200;
            ctx.set('content-type','application/octet-stream');
            ctx.set('content-disposition','attachment; filename='+'1111.json');
            ctx.body = buffer;
这么设置的   我的页面响应的的是 json串  不是文件
不知道什么原因

**Comment by GeneralFy** [comment]
ctx.res.statusCode = 200;
            ctx.set('content-type','application/octet-stream');
            ctx.set('content-disposition','attachment; filename='+'1111.json');
            ctx.body = buffer;
这么设置的   我的页面响应的的是 json串  不是文件
不知道什么原因
