### ISSUE TITLE
egg-cluster生产更新之后是否能自动重启

### ISSUE THREAD

**Issue by xxwade** [eggjs/egg#963]
pm2 可以watch文件的变化，自动重启
想问下egg-cluster有没有该功能，还是说得自己额外写方法

**Comment by popomore** [comment]
不可以，egg 现在只支持应用发布，不可覆盖及时发布。

**Comment by cokeknight** [comment]
@popomore 这个不支持及时发布是基于什么考虑不想支持吗？

**Comment by popomore** [comment]
因为这不是 egg 希望的启动方式，egg 发布要做到平滑过渡，重启需要将当前服务器剔除集群，那热部署其中没什么意义了，而且可能会发生无法预期的问题。

如果采取粗暴的方式也可以用 pm2 来启动 egg-cluster，变化后重启 egg-cluster。

**Comment by qiuyue** [comment]
那目前如何杀掉egg呢， 只能用kill吗？
