### ISSUE TITLE
vulnerable dependency about ms

### ISSUE THREAD

**Issue by popomore** [eggjs/egg#964]
https://snyk.io/vuln/npm:ms:20170412

- [x] egg-bin
    https://github.com/mochajs/mocha/pull/2710
- [x] eggjs/egg-jwt
    https://github.com/auth0/node-jsonwebtoken/pull/352
    https://github.com/eggjs/egg-jwt/pull/4
- [ ] ~~egg-lint~~ close snyk
- [x] eggjs/egg-mock
    https://github.com/popomore/coffee/pull/56
- [x] eggjs/egg-mongoose
    https://github.com/aheckmann/mquery/issues/86
    https://github.com/Automattic/mongoose/issues/5275
- [x] eslint-config-egg
    https://github.com/benmosher/eslint-plugin-import/pull/844
- [ ] egg-socket.io

**Comment by popomore** [comment]
@okoala https://github.com/eggjs/egg-jwt/pull/4 需要升级到最新版本

**Comment by popomore** [comment]
socket.io 可以升级到 2.0 了

**Comment by okoala** [comment]
目前 egg-jwt 已经迁到我自己仓库进行维护了~ 今天完成更新~

**Comment by popomore** [comment]
https://github.com/mochajs/mocha/pull/2860
