### ISSUE TITLE
egg-mysql select 语句写法问题

### ISSUE THREAD

**Issue by kuangcaibao** [eggjs/egg#967]
egg-mysql 操作数据库，官方示例：

```
const results = yield this.app.mysql.select('posts', { // 搜索 post 表
  where: { status: 'draft', author: ['author1', 'author2'] }, // WHERE 条件
  columns: ['author', 'title'], // 要查询的表字段
  orders: [['created_at','desc'], ['id','desc']], // 排序方式
  limit: 10, // 返回数据量
  offset: 0, // 数据偏移量
});
=> SELECT `author`, `title` FROM `posts`
  WHERE `status` = 'draft' AND `author` IN('author1','author2')
  ORDER BY `created_at` DESC, `id` DESC LIMIT 0, 10;
```

这里 `where` 中，`column` 和 `value` 只能使用 `=` ? 如果这里需要逻辑 `>=` 这种逻辑，目前的 `app.mysql.select` 是否支持，找了下没有看到文档说明。

难道只能使用 `app.mysql.query` ?

thx :)

**Comment by iyuq** [comment]
egg-mysql是对[ali-rds](https://github.com/ali-sdk/ali-rds)的封装，文档也就看[ali-rds](https://github.com/ali-sdk/ali-rds)。

**Comment by kuangcaibao** [comment]
看了下 [ali-rds](https://github.com/ali-sdk/ali-rds/blob/master/lib/operator.js) 的源码，确实没有支持。

thx :)
