### ISSUE TITLE
this.ctx.getFileStream().fields 获取请求参数问题

### ISSUE THREAD

**Issue by acrens** [eggjs/egg#973]
``` javascript
const that = this;
const ctx = that.ctx;
let stream;
let result;
let content; // 接口处理逻辑判断
try {
    stream = yield ctx.getFileStream();
    console.log(stream.fields);    // 1、此处无法获取到参数列表
    content = stream.fields.content;

    if (content == 'material') {
        // 新增素材
        result = '';
    } else {
        // 新增图片
    }
} catch (err) {
    result = {
        success: false,
        message: '上传文件异常'
    };
    yield sendToWormhole(stream);
    throw err;
}
console.log(stream.fields);    // 2、此处可以获取到参数列表
ctx.body = result;
```

在以上代码注释 1、处无法获取参数，注释 2、可以获取到参数，但是在上传文件出我需要使用参数

**Comment by dead-horse** [comment]
注释1 和 注释2 的代码执行看来是同步的，也就是说不可能存在 1 无法获取到， 2 可以获取到的场景，你再看看现象到底是什么？

**Comment by acrens** [comment]
我特意加了注释打印：
console.log('注释1' + JSON.stringify(stream.fields));
``` bash
2017-05-31 18:57:17,318 INFO 24125 [master] egg started on http://127.0.0.1:7001 (1742ms)
注释1{}
2017-05-31 18:57:22,593
```

console.log('注释2' + JSON.stringify(stream.fields));
``` base
2017-05-31 18:57:22,613 INFO 24125 [master] App Worker#8:24137 start, state: none, current workers: ["1","5","6","7","8"]
注释2{"content":"material","type":"image"}
2017-05-31 18:57:23,522
```
这是控制台部分内容。

**Comment by acrens** [comment]
不过在两个内容输出之间有一个上传文件的调用：
``` javascript
uploadTempFile(stream, filepath) {
            return new Promise((resolve, reject) => {
                const ws = fs.createWriteStream(filepath);
                stream.pipe(ws);
                ws.on('error', reject);
                ws.on('finish', resolve);
            });
        }
```

**Comment by acrens** [comment]
再次重新看了一遍 API，找到原因了，有说明：

``` bash
要通过 context.getFileStream 便捷的获取到用户上传的文件，需要满足两个条件：

上传文件必须在其他 field 之前。
只支持上传一个文件。
```

抱歉！不过还是不明白为什么上传文件必须在 field 之前，难道和管道有关？

**Comment by dead-horse** [comment]
看起来文档还是有误的，正确的应该是将文件上传放在最后，否则可能出现你遇到的这种情况，在文件流读完之前拿不到 fields。原因是 http 是流式上传的，在文件上传时，如果文件比较大， 一个请求包中可能只有一部分文件信息，如果 fields 放在后面，则会先拿到上传文件的 stream，此时只有等这个 stream 消费完之后才能拿到 fields。

**Comment by acrens** [comment]
你的解释我明白。

但是目前框架确实是支持（以下流程正常）：
1、获得 stream；
2、上传文件；
3、获取 fields。

如果换成以下流程（这个应该是你说的流程，无法获取到 fields）：
1、获取 stream；
2、获取 fields；
3、上传文件。

**Comment by dead-horse** [comment]
@acrens 因为你如果把上传文件放到第二步，就会让上传文件的 http 请求的 stream 完整读完，此时就会读到 fields 了，如果你把上传文件放到第三步，在第二步获取 fields 的时候可能 http 请求 stream 还没解析到 fields。

**Comment by acrens** [comment]
@dead-horse 我明白你的意思，stream 获取与上传文件肯定是需要前后关系才能够使用。但是我是 form multipart/form-data 方式提交，所以获取 fields 首先需要获取 stream = yield ctx.getFileStream(); ，然后才能在 stream 里面获取 fields。在这种情况下，我也就只能够先将文件上传完成，再去读取 fields 参数，而不能够先获取 fields，再去上传文件。
