### ISSUE TITLE
单测如何优雅的去模拟token

### ISSUE THREAD

**Issue by a304885433** [eggjs/egg#977]
* **Node Version**:7.9
* **Egg Version**:1.1.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**:
* **Mini Showcase Repository**:

后台很多接口，都是需要先登陆，拿到返回的token在去请求，每次请求完毕后，token也许需要交换。
单测如何优雅的去模拟token，token可以是url参数，也可以是cookie。

**Comment by atian25** [comment]
`mm.mockContext({})`
