### ISSUE TITLE
请问，restful接口中app.controller.posts.new是代表进入新建post页面吗

### ISSUE THREAD

**Issue by acid122** [eggjs/egg#979]
* **Node Version**:7.10.0
* **Egg Version**:1.2.1
* **Platform**:win10

请问一下大家：restful接口中的app.controller.posts.new方法是指进入新建post页面，那么是不是其对应的新建post方法是app.controller.posts.create，谢谢

**Comment by dead-horse** [comment]
可以这样理解，但是 RESTFul 并不关心创建 post 的页面的 URL 是什么，所以 `GET /posts/new` 可以不实现，或者在其他页面来创建 POST。
