### ISSUE TITLE
Can't use webstorm for debugging

### ISSUE THREAD

**Issue by caoer** [eggjs/egg#983]
* **Node Version**: 7.10.0

* **Egg Version**: 1.4.0
* **Plugin Name**:
* **Plugin Version**:
* **Platform**: Mac
* **Mini Showcase Repository**:

![ace-dev-server_-____documents_projects_lighthousex_ace-dev-server_](https://cloud.githubusercontent.com/assets/225856/26703825/939042d4-46f9-11e7-9db6-c197ef9e7051.png)

see image attached above, it stopped after saying Debugger listen at xxxx.
I can type things under the cursor but egg won't start. Any clue?

**Comment by caoer** [comment]
this is the npm script:

```
    "debug": "egg-bin dev $NODE_DEBUG_OPTION",

```
and websotrm settings:
![run_debug_configurations](https://cloud.githubusercontent.com/assets/225856/26704017/9bad320a-46fa-11e7-9861-8481abef6d20.png)

**Comment by atian25** [comment]
webstorm version? some version of webstorm don't works with node7, it's webstorm bug, had you try latest webstorm and node 8?

发自我的 iPhone

**Comment by caoer** [comment]
using node 8 report error, see screenshots:
![ace-dev-server_-____documents_projects_lighthousex_ace-dev-server__-_webstorm_2017_2_eap](https://cloud.githubusercontent.com/assets/225856/26705556/df80361c-4704-11e7-862e-1e48b36747c7.png)

this is the webstorm version, just updated. Do you know what version it works?

![screenshot_6_1_17__8_00_pm](https://cloud.githubusercontent.com/assets/225856/26705574/e8647018-4704-11e7-8bda-2e2e7b8667af.png)

**Comment by caoer** [comment]
I'm going to try release version instead of EAP, will update soon.

**Comment by geekdada** [comment]
WebStorm supports Node 7 debugging by far, it will hang when debugging with Node 8. Using DevTools to debug Node 8 applications is recommended.

First, make sure your WebStrom and NodeJS plugin both are up to date.

![image](https://cloud.githubusercontent.com/assets/3274850/26768508/e9db166c-49da-11e7-83ba-13f308093b76.png)

![image](https://cloud.githubusercontent.com/assets/3274850/26768520/037d1d04-49db-11e7-8df3-7f550d35aae3.png)

`egg-bin debug` is meant to be working with Chrome DevTools. Instead, you should use `npm start`(add `$NODE_DEBUG_OPTION`) or `node index.js` to start the application and let WebStorm attach the debug socket automatically.

```json
{
  "scripts": {
     "start": "node $NODE_DEBUG_OPTION index.js",
  }
}
```

Please make sure that only 1 worker being started when debugging.

**Comment by atian25** [comment]
@geekdada try `egg-bin dev --inspect`

**Comment by geekdada** [comment]
@atian25 This works, but I think you miss the point here.

WebStorm runs or debugs applications based on same configuration, like launch script, environment variables, etc. It would be a mess if you setting up different configurations for running and debugging.

In terms of 'configuration':

![image](https://cloud.githubusercontent.com/assets/3274850/26769094/bd4b71d8-49de-11e7-996e-7e84b45195db.png)

If you use DevTools for debugging, then use `npm start` and `npm run debug` for running and debugging. If you use WebStorm, then use one configuration and let WebStorm do the rest.

**Comment by atian25** [comment]
@geekdada you can just left `egg-bin dev` at `npm scripts`, then setup webstorm with `npm` not `node.js`, then pass `-- --debug` to it. just like `npm run dev -- --debug`.

**Comment by geekdada** [comment]
![image](https://cloud.githubusercontent.com/assets/3274850/26769256/0bae7c98-49e0-11e7-80b4-b537e41acb27.png)

This configuration would've worked, but the Node parameter WebStorm add is `--debug`. This breaks WebStorm because WebStorm uses inspect protocol when using Node 7 by default.

**Comment by atian25** [comment]
so, webstorm is buggy~

**Comment by geekdada** [comment]
It seems to be a bug with `$NODE_DEBUG_OPTION`, which in this case should be `--inspect-brk` instead of `--debug-brk`.

![image](https://cloud.githubusercontent.com/assets/3274850/26769676/52f6ba54-49e3-11e7-8d4f-a6fec2799797.png)

**Comment by StephenSeraph** [comment]
For Node 8.0.0, the only way to debug that I found is `--inspect`, the step is like this [Debugging Node.js with Chrome DevTools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27).
Both VSCode and WebStorm can not work well as `debug` is a bad option.
But I feel It's fussy to debug node with chrome dev tools, especially for multiprocess. So, I wish there is some way to debug in IDE early.

**Comment by geekdada** [comment]
You will have to stick with the DevTools until the next minor 7.x release of WebStorm.

**Comment by dead-horse** [comment]
issues about debug are closing for now. you can still discuss here.
