### ISSUE TITLE
chrome devtools调试无法找到自己写的代码

### ISSUE THREAD

**Issue by akliyiping** [eggjs/egg#985]
Node Version**:8.0.0
     Egg Version**:1.4.0
    "autod-egg": "^1.0.0",
    "egg-bin": "^3.4.0",
    "egg-ci": "^1.6.0",
    "egg-mock": "^3.7.0",
     chrome: 58.0.3029.110 (64-bit)
     Platform**:mac
     Mini Showcase Repository**:

cli初始化项目
运行 egg-bin debug
在devtools=>sources=>file=>只能看到node_modules内容

**Comment by atian25** [comment]
貌似是 node 8 的问题.

**Comment by atian25** [comment]
试了下，会输出几个地址，你访问的第一个是 master 的，自然没有。
访问第二个即可。

![image](https://cloud.githubusercontent.com/assets/227713/26718662/51567198-47b4-11e7-9244-111ef8e61260.png)

手动构造 URL 就可以，在 `chrome://inspect` 里面只显示 master 了。

**Comment by akliyiping** [comment]
是node8的问题，node8用devtools和webstorm的npm debug都不行，换成lts版本就都能正常debug了

**Comment by atian25** [comment]
@akliyiping 我试过 node8 了，按我上面说的就可以了。

**Comment by akliyiping** [comment]
@atian25 3q

**Comment by atian25** [comment]
根据 https://github.com/nodejs/node/issues/13387#issuecomment-306851784 的描述，可以自己 configure 下，访问 `chrome://inspect` 配置下端口，就能访问了，有 `app_worker` 那个就是我们的 app。

![image](https://user-images.githubusercontent.com/227713/26908441-4630dbfa-4c2d-11e7-8d17-f1b7a4da9662.png)

cc @m31271n

**Comment by atian25** [comment]
文档已经补充到 https://eggjs.org/zh-cn/core/development.html#使用-egg-bin-调试

**Comment by okoala** [comment]
@akliyiping 这里有个 PR，是个在 chrome devtools 中调试比较理想的方案，可以关注下~
https://github.com/eggjs/egg-development-proxyworker/pull/5
