### ISSUE TITLE
vcode调试问题

### ISSUE THREAD

**Issue by tong3jie** [eggjs/egg#986]
### 今天按照官方《本地开发》的文档进行配置launch.json并调试出现如下提示：

> 正在使用旧版协议调试，因为设置了运行时可执行文件。
> npm.cmd run debug index.js 
> 无法确定 Node.js 版本，因此使用旧版协议进行调试: Error: connect ECONNREFUSED 127.0.0.1:10086
> 无法确定 Node.js 版本，因此使用旧版协议进行调试: Error: connect ECONNREFUSED 127.0.0.1:5856
> spmanage@1.0.0 debug f:\nodeProject\spManage\spmanage
> egg-bin debug "index.js"

> ⚠️  Command Error, enable `DEBUG=common-bin` for detail

# 而直接在终端进行使用egg-bin debug可启动

**Comment by tong3jie** [comment]
###  >egg-bin debug“index.js”
### 怎么多了一个index.js

**Comment by atian25** [comment]
你自己的 `launch.json` 写多了?

**Comment by tong3jie** [comment]
@atian25 没有写多

![_20170602182250](https://cloud.githubusercontent.com/assets/14191774/26721950/86eefc92-47c0-11e7-9139-79c2628cd5dc.png)

**Comment by okoala** [comment]
@tong3jie  去掉 program 那串看看~ 文档里面也没有这个啊 https://eggjs.org/zh-cn/core/development.html

**Comment by tong3jie** [comment]
感谢，program节点是VSCODE自动生成的

**Comment by libchaos** [comment]
1. node version8.0
2. egg-development-proxyworker: "^1.0.1"
@tong3jie 能看下你修改后的launch.json文件吗？
![](http://7xojpa.com1.z0.glb.clouddn.com/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/2ca799a9d6beb2639d5d1d71ed89e876.png)[](url)

**Comment by okoala** [comment]
@libchaos 分开运行命令看看，在 shell 窗口中运行 npm run debug. 然后在 vscode 中进行 attach worker

**Comment by libchaos** [comment]
@okoala 分开是可以debug的，不过在shell需要运行`npm run debug --inspect`指定协议，但是仍然得到如下错误而提示，但不影响debug
![](http://7xojpa.com1.z0.glb.clouddn.com/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/755462c1520b02a9399c7d4bb4540296.png)

**Comment by okoala** [comment]
@libchaos  debug 默认就是 inspect 啊，不用指定~

**Comment by tong3jie** [comment]
日了狗啊，好几天了都没有调试成功



![_20170614143236](https://user-images.githubusercontent.com/14191774/27119409-66f2f69a-5112-11e7-8441-87459fb43c1b.jpg)

**Comment by okoala** [comment]
![image](https://user-images.githubusercontent.com/2127199/27121406-c4926b4e-5119-11e7-8053-dd8ccecd1295.png)
@tong3jie  你这里设置`timeout: 20`  或者 直接使用 chrome devtools 调试： chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:10087
