### ISSUE TITLE
config.prod.js value is not being used when NODE_ENV is production. 

### ISSUE THREAD

**Issue by mattma** [eggjs/egg#99]
When I set the key/value in `config.default.js`, it will work in any environment.

If I separated key/value into `config.local.js` and `config.prod.js` with different value on the same key, it will read the key/value in `development` mode just fine, but not in `config.prod.js`.

To reproduce it,

```js
// config.local.js
...
rest: {
  username: 'matt',
},
...
```

When I console log the `this.app.config.rest.username` inside `app/apis/demo.js` `* index()` function, I can get the value of 'matt'. In this case, the value of `this.app.env` is `development`

```js
// config.prod.js
...
rest: {
  username: 'matt_prod',
},
...
```

If I start the server with `NODE_ENV=production npm start`, When I console log the `this.app.config.rest.username` inside `app/apis/demo.js` `* index()` function, I can get the value of 'undefined'. In this case, the value of `this.app.env` is `production`. So it is not reading the value from `config.prod.js`.  Also tried with `NODE_ENV=prod npm start`. it does not work either.

**Comment by atian25** [comment]
use EGG_SERVER_ENV, not use NODE_ENV

see https://github.com/eggjs/egg-core/blob/master/lib/loader/egg_loader.js

**Comment by mattma** [comment]
I guess it is something simple like that. 

1. we need to make a better doc on this issue. `EGG_SERVER_ENV=prod node index.js`

2. can we even make it works with `NODE_ENV=production node index.js` fallback to `EGG_SERVER_ENV=prod node index.js`? Most of developers should use the second format without reading the doc. It should work out of box, do not you think?

**Comment by popomore** [comment]
NODE_ENV 被广泛使用，生产环境还是得指定 production。而且大型项目都有很多环境，比如集成测试环境，这些环境其实都需要使用 production 部署的，但是仍然需要区分这些环境。EGG_SERVER_ENV 可以更细的区分这些环境。

**Comment by atian25** [comment]
所以这个的结论就是补文档？

**Comment by mattma** [comment]
something like,

if you want to run Egg server in production mode, you may run a NPM script like this

```js
...
'prod': NODE_ENV=production EGG_SERVER_ENV=prod npm start
...
```

To start your server in production, try this in terminal

```bash
npm run prod
```
