### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/json

### ISSUE THREAD

**Issue by guzuomuse** [eggjs/egg#992]
when the response format is json
how to remove this console info without using JSON.stringify()
thanks

**Comment by popomore** [comment]
Can you show us the code?

**Comment by guzuomuse** [comment]
@popomore ,sure, easy! here there are:

in controller:
~~~
`this.ctx.body={};`
~~~
with chrome console. you can see the console info 

> Resource interpreted as Document but transferred with MIME type application/json

i know that must be some reason about  **header**. i just want to know how to deal with this for removing the console info without `JSON.stringify()`?
is there any function like express's res.json()?
thanks .

**Comment by dead-horse** [comment]
`this.ctx.body={}` will automatically set content-type to json, you should manually set content-type to what you want:

```js
this.ctx.body = {};
this.ctx.type= 'html';
```
