### ISSUE TITLE
如何编译egg-view-nunjucks插件view中使用到的es6语法

### ISSUE THREAD

**Issue by acid122** [eggjs/egg#993]
* **Node Version**:7.10
* **Egg Version**:1.2.1

请问一下，当我使用egg-view-nunjucks插件时，其对应的view(.nj后缀)中使用了let等es6的新语法，但是发现在低版本的微信浏览器中不支持，请问有类似babel之类的插件可以将这些语法编译成es5语法吗，谢谢：）

**Comment by solarhell** [comment]
这个插件只负责帮你把变量注入啊-- 你可以这么做 把js文件单独拉到一个文件 编译后在模板中src进去

**Comment by popomore** [comment]
这个是服务端渲染插件，前端编译该怎么用还是怎么用。
