### ISSUE TITLE
安装egg-socket.io出现这个提示

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#994]
deprecate egg-socket.io@2.0.0 › socket.io@2.0.2 › socket.io-parser@3.1.2 › isarray@2.0.1 Just use Array.isArray directlyRecently updated (since 2017-05-29): 4 packages (detail see file C:\Users\Cat\Desktop\server\node_modules\.recently_updates.txt)

**Comment by atian25** [comment]
不用管，提示里面写的很清楚了，一个底层依赖用到了 `deprecate` 的 API，只是 warning。
