### ISSUE TITLE
安装报 UNMET PEER DEPENDENCY mocha@3.4.2

### ISSUE THREAD

**Issue by acodercat** [eggjs/egg#996]

**Comment by atian25** [comment]
提供下详细报错

**Comment by popomore** [comment]
删除 node_modules 试试

**Comment by acodercat** [comment]
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.

尝试过删除node_modules   还是不行

**Comment by atian25** [comment]
@acodercat 提供下复现方式

**Comment by acodercat** [comment]
按照官方提供的安装流程，安装一遍就会有

**Comment by atian25** [comment]
@acodercat 麻烦把你生成的代码上传一份到你的仓库，我看看

**Comment by acodercat** [comment]
好像跟NPM的版本，有关系，我用的NPM5.0

**Comment by atian25** [comment]
```bash
$ npm -v
5.0.0
$ egg-init --type=simple mocha-test
$ cd mocha-test
$ npm i
```
无法复现.

**Comment by popomore** [comment]
如果还有问题给出完整重现步骤

**Comment by acodercat** [comment]
{
  "name": "server",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "dependencies": {
    "egg": "^1.4.0",
    "egg-cors": "^1.1.0",
    "egg-jwt": "^2.0.0",
    "egg-mysql": "^3.0.0"
  },
  "devDependencies": {
    "autod": "^2.8.0",
    "autod-egg": "^1.0.0",
    "egg-bin": "^3.4.0",
    "egg-ci": "^1.6.0",
    "egg-mock": "^3.7.0",
    "eslint": "^3.19.0",
    "eslint-config-egg": "^4.2.0",
    "webstorm-disable-index": "^1.2.0"
  },
  "engines": {
    "node": ">=6.0.0"
  },
  "scripts": {
    "start": "node index.js",
    "dev": "egg-bin dev",
    "test": "npm run lint -- --fix && npm run test-local",
    "test-local": "egg-bin test",
    "cov": "egg-bin cov",
    "lint": "eslint .",
    "ci": "npm run lint && npm run cov",
    "autod": "autod"
  },
  "ci": {
    "version": "6, 8"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "codercat",
  "license": "MIT"
}
你们按照这个执行一次npm i 看看

**Comment by acodercat** [comment]
npm 5.0

**Comment by atian25** [comment]
mac, npm 5.0.0 试了还是不能复现.

**Comment by leyi422** [comment]
按照官方的快速入门教程，我也遇到同样的问题：
$ mkdir egg-example
$ cd egg-example
$ npm init
$ npm i egg --save
$ npm i egg-bin --save-dev

node版本6.10.3  npm版本5.0.3

**Comment by atian25** [comment]
node 6.x 的时候，为什么 npm 是 5.x 呢？ node 6.x 自带的 npm 是 3.x 的.

**Comment by leyi422** [comment]
我试了，npm 3.10.10 也一样有这个问题
UNMET PEER DEPENDENCY mocha@3.4.2

**Comment by okoala** [comment]
这个只是警告吧？截图看看~

**Comment by atian25** [comment]
`npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.` 和
 `UNMET PEER DEPENDENCY mocha@3.4.2` 是不一样的。

前者是会阻塞安装，后者应该只是 warning （尤其是用 cnpm 这些有 link 方式安装的，再用 npm 混合时就会看到这个提示，清除 node_modules 后一般就没了。)

**Comment by popomore** [comment]
我还是没重现，而且教程是不是用错了 https://eggjs.org/zh-cn/intro/quickstart.html#快速初始化

**Comment by atian25** [comment]
> npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.

这个报错不是不符合，而是 `none was installed.`，而这两个都是 egg-bin 里面的依赖，只有安装到一半失败才会出现这种报错才对，按理说清空 node_modules 再装是没问题。

@acodercat 你新起一个干净目录，只复制 package.json 过去再试试吧。

**Comment by popomore** [comment]
感觉是 npm 的 bug

**Comment by popomore** [comment]
```
$ npm -v 
3.10.10
$ npm i egg-bin
$ npm ls mocha 
/Users/popomore/code/tmp/a
└── (empty)
$ npm ls co-mocha
/Users/popomore/code/tmp/a
└─┬ egg-bin@3.4.2
  ├── co-mocha@1.2.0 
  └── UNMET PEER DEPENDENCY mocha@3.4.2
$ ll node_modules/egg-bin/node_modules/mocha 
```

**Comment by popomore** [comment]
npm5 到时没这样的提示

```
$ npm ls mocha 
/Users/popomore/code/tmp/a
└── (empty)
$ npm ls co-mocha
/Users/popomore/code/tmp/a
└─┬ egg-bin@3.4.2
  └── co-mocha@1.2.0 
```

**Comment by dead-horse** [comment]
只要能够正常使用就好了，这只是一个 WARNING

**Comment by atian25** [comment]
`UNMET PEER DEPENDENCY mocha@3.4.2` 这个只是 warning 不用管了。

这个讨论里面混杂了两个不同的报错，楼主的是 `npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed. `

**Comment by NARUTOyuyang** [comment]
npm 5.0.3 据说有问题，RN 的 0.45 官方也有问题

**Comment by zhangxuanming** [comment]
npm 5.03 报错。。

$ npm i egg-bin --save-dev
npm WARN co-mocha@1.2.0 requires a peer of mocha@>=1.18 <4 but none was installed.
npm WARN egg1@1.0.0 No description
npm WARN egg1@1.0.0 No repository field.

**Comment by atian25** [comment]
@zhangxuanming 这是 warning 不用管。第一行上面有讨论过了，后面两行是你自己的项目的 package 没有写着这两个字段。
