### ISSUE TITLE
filestream

### ISSUE THREAD

**Issue by weizeng** [eggjs/egg#998]
* duct() {
 const stream = yield this.ctx.getFileStream();
 var fileName = sd.format(new Date(), 'YYYY-MM-DD_HH-mm-ss') + ".jpg";
}

请问下让fs.writeFileSync 可以将上传的图片保存到本地呢？

**Comment by fengmk2** [comment]
我给 multipart 写一个保存上传文件到磁盘的例子，稍等。

**Comment by weizeng** [comment]
非常感谢！
刚正在尝试分块写入

**Comment by fengmk2** [comment]
@weizeng 发现已经有例子，可以直接参考 https://github.com/eggjs/examples/blob/master/multipart/app/controller/upload.js#L40

**Comment by weizeng** [comment]
我没认真看，感谢分享！知道了！

**Comment by yulaughing** [comment]
@fengmk2 
https://github.com/eggjs/examples/blob/master/multipart/app/controller/upload.js#L40
这个链接404了

**Comment by atian25** [comment]
自己点上一级看不就行了
