### ISSUE TITLE
如何在egg-socket.io中使用Rooms？

### ISSUE THREAD

**Issue by dreamStar** [eggjs/egg#999]
hi，我在使用egg－socket.io插件实现一个需求，希望client端发起的连接在server端能保存下来并且定期交互。我们期望使用socket.io的rooms特性来实现这一点，不知道在egg-socket.io中如何使用这一特性呢？能否提供一个简单的例子，谢谢。
另外一个问题，我们现在的server端使用egg框架混布了http和socket两种协议，两个协议的service函数如何互相调用呢？

**Comment by ngot** [comment]
app.io 拿到的对象就是 socket.io 。具体用法，参见 socket.io 文档。用法没有什么不同。

**Comment by ngot** [comment]
https://socket.io/docs/rooms-and-namespaces/

**Comment by ngot** [comment]
service  看这个demo https://github.com/eggjs/egg-socket.io/blob/master/example/app/io/controller/chat.js#L7

**Comment by dreamStar** [comment]
OK，thx
看来可以直接yield调用service里的接口，但是其实这时在service里调用不到this.ctx对吧，我可以自己添加一个ctx来试试

**Comment by ngot** [comment]
https://eggjs.org/zh-cn/basics/service.html#定义-servicel service看这里文档
